### ISSUE TITLE
gflenv.com: breakage

### ISSUE THREAD

**Issue by Imboredofu** [uBlockOrigin/uAssets#16035]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://gflenv.com/pay-my-bill/`

### Category

breakage

### Describe the issue

Account login page will not load. Problem loading page appears when Ublock is enabled. Same website works properly when disabled. Only after selecting account login does the page not load.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 88856
  cosmetic: 38556
  scriptlet: 16681
  html: 868
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32288-60, 2d.18h.1m
    ublock-badware: 4191-0, 2d.18h
    ublock-privacy: 307-0, 12d.19h.45m
    ublock-abuse: 77-0, 12d.19h.44m
    ublock-unbreak: 1930-2, 2d.17h.59m
    ublock-quick-fixes: 398-0, 52m
    easylist: 64996-608, 55m
    easyprivacy: 30998-1739, 54m
    urlhaus-1: 8679-0, 53m
    plowe-0: 3675-3, 12d.19h.38m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 742 ms
  maxAssetCacheWait: 196 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
using a us ip I'm able to access this login page:

![image](https://user-images.githubusercontent.com/10303732/208239646-0495162c-e3d3-4f7c-9094-dce08a532ba6.png)

**Comment by Imboredofu** [comment]
I didn’t think to use a VPN, that worked! Thanks for the tip. I’m currently deployed overseas and sometimes I don't have the speeds to run a VPN.

Thank you!
