### ISSUE TITLE
soap2day.ac: popups

### ISSUE THREAD

**Issue by NLT319** [uBlockOrigin/uAssets#16032]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soap2day.ac/EczoxOToiMjk4NzZ8fDY3LjE2OS4xMzguMSI7.html`

### Category

popups

### Describe the issue

When opening a TV series stream, it keeps opening new tabs and immediately closing them and I guess it's bypassing the blocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 88422
  cosmetic: 38317
  scriptlet: 16582
  html: 792
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 31834-52, 1d.4h.22m
    ublock-badware: 3947-0, 1d.4h.23m
    ublock-privacy: 288-0, 19m
    ublock-abuse: 76-0, 4h.20m
    ublock-unbreak: 1886-0, 1d.4h.21m
    easylist: 62416-612, 2d.7h.46m
    easyprivacy: 30822-1722, 2d.7h.45m
    urlhaus-1: 11291-0, 12h.17m
    plowe-0: 3671-3, 8d.11h.55m
    ublock-quick-fixes: 430-0, 12h.16m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 286 ms (selfie)
  maxAssetCacheWait: 191 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    clksite.com: 1
    d27qffx6rqb3qm.cloudfront.net: 2
    jwpltx.com: 1
    pogothere.xyz: 2
    s3.us-east-1.amazonaws.com: 1
    serving-passthrough.com: 3
```
</details>

**Comment by mapx-** [comment]
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
