### ISSUE TITLE
cloud-computing-central.com: detection

### ISSUE THREAD

**Issue by kuchienkz** [uBlockOrigin/uAssets#16039]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [ ] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://cloud-computing-central.com/`

### Category

detection

### Describe the issue

Full URL (in my case):
`https://cloud-computing-central.com/?cID=bWVsME4zTTBEd1ppWWd3cTovVVk0T1JMa3d2SlBZUnE2YmI4cWpRPT0=`

This url was reported, but lacks more info and therefore not solved yet (?)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 86987
  cosmetic: 38780
  scriptlet: 16678
  html: 868
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 32287-136, 8h.6m
    ublock-badware: 4191-0, 2d.5h.11m
    ublock-privacy: 301-0, 6d.15h.25m
    ublock-abuse: 77-0, 6d.15h.24m
    ublock-unbreak: 1929-2, 2d.5h.10m
    ublock-quick-fixes: 398-0, 7m
    easylist: 64425-517, 6d.3h.26m
    easyprivacy: 30998-1757, 9m
    urlhaus-1: 7606-0, 8m
    plowe-0: 3678-3, 6d.15h.22m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 892 ms (selfie)
  maxAssetCacheWait: 103 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    cloudflareinsights.com: 2
    getadmiral.com: 1
    yieldmo.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
The link just redirects to `https://www.google.com/` on my machine.

**Comment by kuchienkz** [comment]
Damn...

I love Ublock Origin so much, its already excelent as is, and it's thanks to you guys and the devs. Also this link totally not important to me, so I don't want to trouble you guys any further.

But, in case you guys have some free time and willing to solve this damned link, here is the step to reproduce this, which may help.

Before that, I want to warn you This link was generated by a free Premium Link Generator service: any[d]ebrid.com (ofc without bracket). With free service

**Comment by stephenhawk8054** [comment]
Can you test if this filter works?

```adb
cloud-computing-central.com##+js(acis, showInstruction)
```

**Comment by kuchienkz** [comment]
The link expired, I will try it when it shows up again.

**Comment by kuchienkz** [comment]
> Can you test if this filter works?
> 
> ```
> cloud-computing-central.com##+js(acis, showInstruction)
> ```

Although its different domain, the exactly same adblock detection shows up, adding this to my rules (after matching the domain), really solved the problem 🔥🥳

Many many thanks!

I will close this now.

**Comment by stephenhawk8054** [comment]
Can you tell us the other domain that you encountered so we can add it to the main list too?

**Comment by kuchienkz** [comment]
> Can you tell us the other domain that you encountered so we can add it to the main list too?

cloudcomputingtopics.com

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16980
