### ISSUE TITLE
app.mailbrew.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#16036]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://app.mailbrew.com/edit/81019`

### Category

breakage

### Describe the issue

![image](https://user-images.githubusercontent.com/19517680/208245962-e0b88269-b408-487e-8fa7-dce855b9b456.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/208245968-9035e49c-bf62-463c-8705-201f60f2f4cd.png)

![image](https://user-images.githubusercontent.com/19517680/208245984-1e7dc9c5-239d-4072-b23f-3f4ff6fba4e6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 110
filterset (summary): 
  network: 124838
  cosmetic: 190167
  scriptlet: 27204
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7712-3, 3d.3h.24m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 3d.3h.23m
    RUS-0: 39568-48, 23h.50m
    adguard-annoyance: 62189-800, 3d.3h.26m
    adguard-spyware: 33776-3271, 3d.3h.25m
    fanboy-annoyance: 83662-3994, 7d.4h.5m
    fanboy-cookiemonster: 43796-43796, 7d.4h.5m
    ublock-annoyances: 4796-214, 3d.3h.21m
  default: 
    user-filters: 19-0, never
    easylist: 63024-160, 1d.3h.53m
    easyprivacy: 30908-12339, 1d.3h.52m
    ublock-abuse: 77-1, 3d.3h.22m
    ublock-badware: 4181-106, 3d.3h.20m
    ublock-filters: 31496-641, 3d.3h.19m
    ublock-privacy: 260-49, 3d.3h.18m
    ublock-quick-fixes: 387-18, 40m
    ublock-unbreak: 1917-64, 3d.3h.17m
filterset (user): [array of 19 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1405 ms (selfie)
  maxAssetCacheWait: 658 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    mailbrew.com: 1
    sentry.io: 3
```
</details>

**Comment by mapx-** [comment]
add
`mailbrew.com#@#body > div[style^="position: fixed; top: 0px; left: 0px; width: 100%;"]`

adguard annoyances issue
