### ISSUE TITLE
blog.nationapk.com: detection

### ISSUE THREAD

**Issue by copycopyhumancat** [uBlockOrigin/uAssets#16034]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://blog.nationapk.com/`

### Category

detection

### Describe the issue

That Website mentioned says "adblock detected" and "disable it to continue"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20221217-164242_Firefox](https://user-images.githubusercontent.com/108836571/208238949-24d5da12-b6d4-49a0-9bb5-320789d94916.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 108
filterset (summary): 
  network: 88343
  cosmetic: 28248
  scriptlet: 16741
  html: 865
listset (total-discarded, last-updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32394-297, 3d.14h.23m
    ublock-badware: 4184-0, 3d.14h.22m
    ublock-privacy: 301-1, 2d.15h.10m
    ublock-abuse: 77-0, 2d.15h.57m
    ublock-unbreak: 1929-2, 3d.14h.21m
    ublock-quick-fixes: 492-0, 20h.17m
    adguard-mobile: 8353-167, 3d.14h.25m
    easylist: 62662-17803, 1d.2h.39m
    easyprivacy: 30908-1722, 2d.13h.7m
    urlhaus-1: 9370-0, 17h.34m
    plowe-0: 3679-3, 2d.13h.8m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 590 ms (selfie)
  maxAssetCacheWait: 156 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    doubleclick.net: 1
    googlesyndication.com: 2
    wp.com: 2
```
</details>

**Comment by copycopyhumancat** [comment]
But I managed to bypass that picker mode in ublock

**Comment by mapx-** [comment]
Provide the original shortener link
