### ISSUE TITLE
pornqd.net [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1604]
URL(s) where the issue occurs

`https://www.pornqd.net/movie/giorgiogrand-angel-smalls-beautiful-girls-gather-in-the-evening-to-take-part-in-the-chic-orgies.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by okiehsch** [comment]
`pornqd.net##a[href^="http://www.poweredbyliquidfire.mobi/"]`

**Comment by SMed79** [comment]
@KiLL4FuNK add these filters https://forums.lanik.us/viewtopic.php?f=62&t=40049

**Comment by okiehsch** [comment]
OK, I missed the popups, will add a fix.
