### ISSUE TITLE
fastfoodnutrition.org: ads

### ISSUE THREAD

**Issue by ORIOLESFan02** [uBlockOrigin/uAssets#16058]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://fastfoodnutrition.org/`

### Category

ads

### Describe the issue

Shows two amazon ads. One at the top, another one at the bottom. Annoying, but I'm pretty sure it's an ad or at least a sponsored segment.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/48143202/208323135-2adb1a2b-4313-49f9-bb27-3f12255de2e1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 88836
  cosmetic: 39937
  scriptlet: 19966
  html: 886
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4820-4, 1d.17m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32313-55, 1d.22m
    ublock-badware: 4191-0, 1d.21m
    ublock-privacy: 307-0, 1d.20m
    ublock-abuse: 77-0, 1d.19m
    ublock-unbreak: 1930-2, 1d.18m
    ublock-quick-fixes: 490-0, 1d.16m
    easylist: 64996-627, 3d.6h.55m
    easyprivacy: 30990-1740, 3d.6h.54m
    urlhaus-1: 8430-0, 1d.15m
    plowe-0: 3678-3, 9d.7h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 251 ms (selfie)
  maxAssetCacheWait: 79 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    fastfoodnutrition.org: 4
    amazon-adsystem.com: 1
    ancientact.com: 1
    ay.delivery: 2
    ex.co: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    newrelic.com: 1
    skillfuldrop.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
/amz728x90.gif$image
fastfoodnutrition.org###desk_leader_ad
fastfoodnutrition.org##.sticky_footer
```

@ryanbr
