### ISSUE TITLE
megaup.net: ads

### ISSUE THREAD

**Issue by Schmogg** [uBlockOrigin/uAssets#16054]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://megaup.net/Uyzq/CB-NST-RF-NSwTcH-NSP-Ziperto.part1.rar`

### Describe the issue

Not all ads are blocked

### Screenshot(s)

https://imgur.com/TiAQMxf

### Notes

Thanks!

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 86191
  cosmetic: 42773
  scriptlet: 16715
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32309-66, 7h.21m
    ublock-badware: 4206-0, 7h.21m
    ublock-privacy: 301-0, 7h.21m
    ublock-abuse: 77-0, 7h.21m
    ublock-unbreak: 1930-2, 7h.21m
    ublock-quick-fixes: 483-0, 7h.21m
    easylist: 61497-614, 7h.21m
    easyprivacy: 31005-1748, 7h.21m
    urlhaus-1: 7606-0, 7h.21m
    plowe-0: 3671-3, 7h.21m
    DEU-0: 6061-2, 7h.21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 166 ms (selfie)
  maxAssetCacheWait: 100 ms
```
</details>

**Comment by mapx-** [comment]
update now all your filter lists, it was fixed recently
