### ISSUE TITLE
tranimeizle.co: ads

### ISSUE THREAD

**Issue by Sariserpito** [uBlockOrigin/uAssets#16057]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.tranimeizle.co/`

### Category

ads

### Describe the issue

left and right some of the ads are still stays

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 85600
  cosmetic: 48026
  scriptlet: 17829
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 12010-11, 1d.4h.30m
    easylist: 61703-71, 1d.5h.22m
    easyprivacy: 30995-1176, 1d.4h.31m
    plowe-0: 3671-903, 4h.36m
    ublock-abuse: 77-0, 1d.4h.29m
    ublock-badware: 4045-109, 1d.4h.28m
    ublock-filters: 31491-124, 1d.4h.27m
    ublock-privacy: 260-1, 1d.4h.26m
    ublock-quick-fixes: 387-18, 2h.51m
    ublock-unbreak: 1915-44, 1d.4h.25m
    urlhaus-1: 7521-0, 2h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 243 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
tranimeizle.co##.page-left-ad
tranimeizle.co##.page-right-ad
```

for `Adgurad Turkish`.

@Yuki2718
