### ISSUE TITLE
[nsfw] 7mmtv.sx: nuisance

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#16051]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://7mmtv.sx/en/censored_content/2499/DVDES-734.html`

### Category

nuisance

### Describe the issue

![image](https://user-images.githubusercontent.com/98657967/208293224-71d19443-1fe3-4967-803f-d07b57f1927f.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 110
filterset (summary): 
  network: 83480
  cosmetic: 118817
  scriptlet: 22836
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7741-2, 20m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-6, 20m
    fanboy-annoyance: 83920-355, 20m
    fanboy-cookiemonster: 44045-44045, 20m
    ublock-annoyances: 4797-75, 20m
  default: 
    user-filters: 10-0, never
    easylist: 61497-56, 20m
    easyprivacy: 31005-1171, 20m
    ublock-abuse: 77-0, 20m
    ublock-badware: 4202-105, 20m
    ublock-filters: 31519-413, 20m
    ublock-privacy: 254-8, 20m
    ublock-quick-fixes: 476-14, 20m
    ublock-unbreak: 1917-49, 20m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1132 ms (selfie)
  maxAssetCacheWait: 513 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 1
    histats.com: 1
    realsrv.com: 2
    xlrdr.com: 1
```
</details>

**Comment by ghajini** [comment]
does this `7mmtv.sx##+js(nowoif)` fix what you are describing?
