### ISSUE TITLE
namasce.pl: detection "AdQuesto"

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#16056]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://namasce.pl/odsniezanie-poziom-ekspert-miotacz-ognia-poszedl-w-ruch-video/`

### Describe the issue

AdQuesto after few second in articles and bulred arcticle under bar with warning.

### Screenshot(s)

<details>

![obraz](https://user-images.githubusercontent.com/35370833/208321444-ea6a75d0-402a-416f-9f17-367860509f35.png)

![obraz](https://user-images.githubusercontent.com/35370833/208330546-a71c9cca-0ea6-47f1-b1bc-5838634ac821.png)

</details>

### uBlock Origin version

1.45.3rc5

### Browser name and version

109b3

### Settings

- uBo Annoyances
- POL-0
- POL-2

### Notes

fyi @olegwukr - polish anti-adblock list have few solutions to disable these AdQuesto.

**Comment by mapx-** [comment]
uBO filter still working 

`namasce.pl##+js(no-setTimeout-if, , 1)`

**Comment by krystian3w** [comment]
So something form pol-0 or pol-2 break filter from file:

- filters.txt
- filters-2020.txt
- filters-2021.txt
- filters-2022.txt
