### ISSUE TITLE
[nsfw] bluemediafile.sbs: detection

### ISSUE THREAD

**Issue by camboozle** [uBlockOrigin/uAssets#16055]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://bluemediafile.sbs/url-generator.php?url=KH1TK0eBXmDmljELeo4C+NAndiA2xHwWqPtDspENjO7v7e85S0xp3XE0QUU3W4MA`

### Category

detection

### Describe the issue

Gives the message "Please support us by disabling Adblock and refresh page, thank you."

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/102335295/208320545-3901e6be-0191-434e-b3e0-d5c102934a5a.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 87114
  cosmetic: 38836
  scriptlet: 16763
  html: 862
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32313-54, 21h.40m
    ublock-badware: 4191-0, 21h.39m
    ublock-privacy: 301-0, 4d.19h.10m
    ublock-abuse: 77-0, 4d.19h.9m
    ublock-unbreak: 1928-2, 21h.38m
    ublock-quick-fixes: 490-0, 21h.37m
    easylist: 63778-627, 5d.20h.51m
    easyprivacy: 30977-1740, 5d.20h.50m
    urlhaus-1: 8430-0, 21h.36m
    plowe-0: 3679-3, 3d.22h.36m
filterset (user): [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 2428 ms (selfie)
  maxAssetCacheWait: 68 ms
popupPanel: 
  blocked: 42
  blockedDetails: 
    bluemediafile.sbs: 2
    adskeeper.com: 4
    ascentcolley.com: 1
    bookljlihooli.com: 1
    choobinoobi.com: 2
    ctsjackupspete.com: 12
    googletagmanager.com: 1
    onhadintrepha.info: 11
    pogothere.xyz: 8
```
</details>

**Comment by krystian3w** [comment]
Try backup setting and reinstall uBlock Origin from Moz://a Addon Store.

https://addons.mozilla.org/addon/ublock-origin/

**Comment by krystian3w** [comment]
As workaround can works user script:

https://greasyfork.org/pl/scripts/423435-igg-games-bluemediafiles-bypass/code

If anti-adblock detector works very late.

**Comment by mapx-** [comment]
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by einstein95** [comment]
Caused by a filter in Easylist, the following filters solve the detection as well as removing the popup ad
```
bluemediafile.sbs##^script:has-text(FingerprintJS)
bluemediafile.sbs#@##ads-right
```

These are the anti-adblock conditions:
```js
if (Math.abs(new Date().getTime() - Time_Start) < 3000) {}
if ($('.item').css('display') == 'none') {}
if ($('#ads-right').css('display') == 'none' || $('#305361').width() == 1 || $('[id^="ads-"]').css('height') == '10px') {}
```

**Comment by krystian3w** [comment]
Why this post is not deleted:
https://github.com/uBlockOrigin/uAssets/issues/15944#issuecomment-1341053866

**Comment by stephenhawk8054** [comment]
I cannot reproduce it either. There's only 1 generic filter `###ads-right` in EasyList and it's already ignored by `@@||bluemediafile.$generichide` in ublock filters.
