### ISSUE TITLE
mispelisyseries.com [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1605]
URL(s) where the issue occurs

`http://mispelisyseries.com/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by lain566** [comment]
Anti adblock
`http://mispelisyseries.com/descargar/peliculas-castellano/la-noche-de-halloween/bluray-screeener/`
