### ISSUE TITLE
caseking.de: breakage

### ISSUE THREAD

**Issue by hrrd** [uBlockOrigin/uAssets#16053]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.caseking.de/`

### Category

breakage

### Describe the issue

Cosent Manager is blocked. Website blurred because of this

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 134518
  cosmetic: 132819
  scriptlet: 35428
  html: 888
listset (total-discarded, last-updated): 
  removed: 
    DEU-0: null
  added: 
    adguard-generic: 66296-4942, 3d.3h.44m
    adguard-mobile: 8354-148, 3d.17h.49m
    adguard-annoyance: 62223-755, 3d.3h.45m
    ublock-annoyances: 4820-4, 3d.17h.50m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32281-87, 1d.4h.48m
    ublock-badware: 4191-0, 1d.4h.47m
    ublock-privacy: 301-0, 5d.1h.22m
    ublock-abuse: 77-0, 5d.1h.21m
    ublock-unbreak: 1928-3, 1d.4h.46m
    ublock-quick-fixes: 492-0, 2h.22m
    easylist: 63778-759, 4d.17h.10m
    adguard-spyware-url: 861-3, 1d.4h.49m
    easyprivacy: 30983-1747, 3d.16h.55m
    urlhaus-1: 7521-0, 2h.21m
    curben-phishing: 22726-1, 2h.23m
    plowe-0: 3676-3, 12d.17h.35m
    LegitimateURLShortener: 2046-125, 21m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 217 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    cloudflareinsights.com: 2
    google.com: 5
    googletagmanager.com: 1
    visualwebsiteoptimizer.com: 1
```
</details>

**Comment by krystian3w** [comment]
Test without AG Annoyances.

Also a litte scary is made  `adguard-spyware-url` and new `LegitimateURLShortener` as stock lists.

**Comment by hrrd** [comment]
> Test without AG Annoyances / AdGuard Base.
> 
> Try find in logger these allowing: `#@##ckLbOverlay`, then possible see blueish transparency background.
> 
> Also a litte scary is made `curben-phishing` (e.g. PhisTank FP), `adguard-spyware-url` and new `LegitimateURLShortener` as stock lists:
> 
> > ```yaml
> >   default: 
> >     user-filters: 0-0, never
> >     ublock-filters: 32281-87, 1d.4h.48m
> >     ublock-badware: 4191-0, 1d.4h.47m
> >     ublock-privacy: 301-0, 5d.1h.22m
> >     ublock-abuse: 77-0, 5d.1h.21m
> >     ublock-unbreak: 1928-3, 1d.4h.46m
> >     ublock-quick-fixes: 492-0, 2h.22m
> >     easylist: 63778-759, 4d.17h.10m
> >     adguard-spyware-url: 861-3, 1d.4h.49m    <-----------------
> >     easyprivacy: 30983-1747, 3d.16h.55m
> >     urlhaus-1: 7521-0, 2h.21m
> >     curben-phishing: 22726-1, 2h.23m         <-----------------
> >     plowe-0: 3676-3, 12d.17h.35m
> >     LegitimateURLShortener: 2046-125, 21m    <-----------------
> > ```
> 
> So uBo memory/data base can be malformed..., then recommended is backup configuration and reset uBo, if still glitches then reinstall from Moz://a Addon store: https://addons.mozilla.org/firefox/ublock-origin/
> 
> If you read very often DEU pages then enable again regional list:
> 
> > ```yaml
> >   removed: 
> >     DEU-0: null
> > ```
> 
> But for delete correct cookie bar is not needed.

thanks for the help. i tried it seems to work even with ag annoyances and base. don't know why it works now didn't changed anything but im glad.
