### ISSUE TITLE
bolugundem.com: privacy

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#16069]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bolugundem.com/haber/13266035/golcukte-dans-resitali`

### Category

privacy

### Describe the issue

`bolugundem.com` website does not allow right-click functionality. Can you please suggest a rule to access the right click again.
No need to add the rule to uBO filters. I want it for my own user filter.

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/208526301-4cfa0cec-9afd-426c-8a72-2c0bedbffe3d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 117465
  cosmetic: 152875
  scriptlet: 34002
  html: 864
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 66487-5500, now
    adguard-spyware: 35779-3760, now
    adguard-spyware-url: 864-4, now
    adguard-annoyance: 62319-1529, now
    adguard-social: 19501-30, now
  default: 
    user-filters: 66-0, never
    ublock-filters: 32324-40, now
    ublock-badware: 4211-0, now
    ublock-privacy: 301-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1931-3, now
    ublock-quick-fixes: 482-14, now
    easylist: 61548-324, now
    easyprivacy: 31006-12237, now
    TUR-0: 12022-20, now
filterset (user): [array of 71 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 594 ms (selfie)
  maxAssetCacheWait: 700 ms
  unsuspendAfter: 138 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    bolugundem.com: 3
    bildirt.com: 2
    cloudflare.com: 3
    daktilo.com: 4
    facebook.net: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`
