### ISSUE TITLE
coincheckup.com: ads

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#16060]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://coincheckup.com/coins/stellar`

### Category

ads

### Describe the issue

The websites below have an ad server called `czilladx.com`

```
https://coincheckup.com/coins/stellar
https://kriptokoin.com/
http://icotokennews.com/
```

`||czilladx.com^` rule already exists in EasyList but is not blocked by uBO for some reason.

https://github.com/easylist/easylist/blob/79dd21808d4cf2ef04def6501753d017c57dca76/easylist/easylist_adservers.txt#L3990

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![ubobug](https://user-images.githubusercontent.com/110184059/208351351-1f34575d-0ada-4078-84e9-aa9353266c85.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 116120
  cosmetic: 152766
  scriptlet: 34001
  html: 864
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 66358-5394, now
    adguard-spyware: 33787-3160, now
    adguard-spyware-url: 861-3, now
    adguard-annoyance: 62277-1514, now
    adguard-social: 19476-25, now
  default: 
    user-filters: 66-0, never
    ublock-filters: 32316-75, now
    ublock-badware: 4211-0, now
    ublock-privacy: 301-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1931-3, now
    ublock-quick-fixes: 492-0, now
    easylist: 61519-322, now
    easyprivacy: 31006-12183, now
    TUR-0: 12014-11, now
filterset (user): [array of 71 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1317 ms (selfie)
  maxAssetCacheWait: 1029 ms
  unsuspendAfter: 166 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    coincheckup.com: 4
    coinzilla.io: 1
    coinzillatag.com: 12
    google-analytics.com: 1
    google.com: 4
    onesignal.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
`||czilladx.com^` is currently not in EL:

https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt

@ryanbr
