### ISSUE TITLE
voe.sx: detection

### ISSUE THREAD

**Issue by wilhelm115** [uBlockOrigin/uAssets#16068]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://voe.sx`

### Describe the issue

`https://voe.sx/`

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 89947
  cosmetic: 42482
  scriptlet: 16707
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 22-0, never
    ublock-filters: 32281-65, 2d.23h.24m
    ublock-badware: 4191-0, 2d.23h.25m
    ublock-privacy: 301-0, 10d.58m
    ublock-abuse: 77-0, 10d.59m
    ublock-unbreak: 1924-2, 2d.23h.26m
    easylist: 64996-613, 2d.23h.28m
    easyprivacy: 30908-1724, 2d.23h.27m
    plowe-0: 3678-3, 7d.27m
    DEU-0: 6061-2, 7h.22m
    urlhaus-1: 7644-0, 7h.24m
    ublock-quick-fixes: 493-0, 7h.23m
filterset (user): [array of 23 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 240 ms (selfie)
  maxAssetCacheWait: 290 ms
```
</details>

**Comment by mapx-** [comment]
Provide the original link / movies page.
