### ISSUE TITLE
tvsinpagar.com [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1606]
URL(s) where the issue occurs

`http://www.tvsinpagar.com/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by lain566** [comment]
Anti adblock
`http://www.tvsinpagar.com/descargar/peliculas-castellano/bienvenidas-a-brasil/`
