### ISSUE TITLE
store.epicgames.com: breakage

### ISSUE THREAD

**Issue by aerno** [uBlockOrigin/uAssets#16078]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://store.epicgames.com/en-US/cart/success`

### Category

breakage

### Describe the issue

Checkout on Epic Games Store (epicgames.com) doesn't work. Popup for purchase approval doesn't appear. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 41020
  cosmetic: 42960
  scriptlet: 29381
  html: 850
listset (total-discarded, last-updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-10, 1d.1h.27m
    adguard-generic: 66355-4028, 2d.8h.38m
  default: 
    user-filters: 19-0, never
    ublock-filters: 32304-76, 2d.8h.39m
    ublock-badware: 4206-0, 2d.8h.41m
    ublock-privacy: 301-0, 8d.5h.22m
    ublock-abuse: 77-0, 8d.5h.21m
    ublock-unbreak: 1930-1, 2d.8h.40m
    urlhaus-1: 10154-0, 1h.4m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 33 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 358 ms (selfie)
  maxAssetCacheWait: 169 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

Do not disable Easylist / Easyprivacy

**Comment by aerno** [comment]
No problem, the triage system just closes tickets without solving them. Helpless desk.

Nowadays trying to help improve a piece of open source software over Github seems to get the user nowhere. Why doesn't anybody report any more ?

I can reproduce the issue with 1.45.2 having the default filters active plus Fanboy's list:

Built-in (5/6)
uBlock filters
32,241 used out of 32,316
uBlock filters – Badware risks
4,236 used out of 4,236
uBlock filters – Privacy
301 used out of 301
uBlock filters – Resource abuse
77 used out of 77
uBlock filters – Unbreak
1,923 used out of 1,924
Ads (1/3)
AdGuard Base
62,591 used out of 66,647
AdGuard Mobile Ads
EasyList
Privacy (0/4)
AdGuard Tracking Protection
AdGuard URL Tracking Protection
Block Outsider Intrusion into LAN
EasyPrivacy
Malware domains (1/3)
Online Malicious URL Blocklist
7,787 used out of 7,787
Annoyances (0/7)
Multipurpose (0/2)
Peter Lowe’s Ad and tracking server list
Regions, languages (0/34)
ALB: Adblock List for Albania
ara: Liste AR
BGR: Bulgarian Adblock list
CHN: AdGuard Chinese (中文)
CZE, SVK: EasyList Czech and Slovak
DEU: EasyList Germany
EST: Eesti saitidele kohandatud filter
FIN: Adblock List for Finland
FRA: AdGuard Français
GRC: Greek AdBlock Filter
HUN: hufilter
IDN, MYS: ABPindo
IND, LKA, NPL: IndianList
IRN: PersianBlocker
ISL: Icelandic ABP List
ISR: EasyList Hebrew
ITA: EasyList Italy
JPN: AdGuard Japanese
KOR: List-KR
LTU: EasyList Lithuania
LVA: Latvian List
NLD: EasyDutch
NOR, DNK, ISL: Dandelion Sprouts nordiske filtre
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
ROU: Romanian Ad (ROad) Block List Light
RUS: RU AdList
spa, por: AdGuard Spanish/Portuguese
spa: EasyList Spanish
SVN: Slovenian List
SWE: Frellwit's Swedish Filter
THA: EasyList Thailand
TUR: AdGuard Turkish
VIE: ABPVN List
Custom (1/1)
Fanboy's Enhanced Tracking List
2,979 used out of 2,989
Import…

I just added epicgames.com to uBlock Origin's trusted sites list, issue solved for me. Not for others.

**Comment by gwarser** [comment]
Disable `https://www.fanboy.co.nz/enhancedstats.txt` subscription?

**Comment by mapx-** [comment]
@aerno closing the issue does not mean we cannot continue debugging the issue.
Did you follow ALL the indications above ?
