### ISSUE TITLE
imageweb.ws [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1607]
URL(s) where the issue occurs

`https://www.imageweb.ws/hayek-porn-salma/883670.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by mapx-** [comment]
For your next issues: just make clear if there are only (normal) ads or ads + popups / redirects.
