### ISSUE TITLE
[nsfw] chaturbate.com: breakage

### ISSUE THREAD

**Issue by LivexMania** [uBlockOrigin/uAssets#16070]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://chaturbate.com/`

### Category

breakage

### Describe the issue

Some privacy/tracking related filters are causing infinite memory increase on any livestreams tabs:

- AdGuard Tracking Protection
- EasyPrivacy
- Dan Pollock’s hosts file
- Peter Lowe’s Ad and tracking server list
- MVPS HOSTS
- Some region, languages filters (I didn't tested all, but the french one has the issue, the japanese and italian ones don't)

I tried this on Chrome 108 and Opera GX 93.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 115224
  cosmetic: 221561
  scriptlet: 37255
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 4m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, 5m
    adguard-annoyance: 62319-96, 8m
    adguard-generic: 66487-517, 8m
    adguard-mobile: 8354-194, 8m
    adguard-social: 19501-824, 8m
    adguard-spyware-url: 864-2, 8m
    block-lan: 44-0, now
    curben-phishing: 22340-0, 8m
    curben-pup: 187-0, 8m
    fanboy-annoyance: 83874-4975, 8m
    fanboy-cookiemonster: 44004-44004, 8m
    fanboy-social: 23473-23462, 8m
    fanboy-thirdparty_social: 68-21, 8m
    ublock-annoyances: 4799-235, 8m
  default: 
    user-filters: 49-2, never
    easylist: 61590-1269, 8m
    ublock-abuse: 77-0, 8m
    ublock-badware: 4207-270, 8m
    ublock-filters: 31534-3749, 8m
    ublock-privacy: 254-10, 8m
    ublock-quick-fixes: 476-48, 8m
    ublock-unbreak: 1918-63, 8m
    urlhaus-1: 7644-1, 8m
filterset (user): [array of 51 redacted]
trustedset: 
  added: [array of 41 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdateDelayAfterLaunch: 180
  autoUpdatePeriod: 7
  cloudStorageCompression: false
  selfieAfter: 3
supportStats: 
  allReadyAfter: 285 ms (selfie)
  maxAssetCacheWait: 798 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    highwebmedia.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
You are enabling many additional lists. Turn off one by one to see which one causes the issue.

**Comment by stephenhawk8054** [comment]
> - EasyPrivacy
> - Peter Lowe’s Ad and tracking server list

The default settings have these 2 filter lists, and I opened one link `https://chaturbate.com/chillwithkira/` but still cannot reproduce high memory issue.

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by LivexMania** [comment]
I tried everything you said mapx, the issue still present because EasyPrivacy and Peter Lowe’s Ad and tracking server list are enabled by default (everything works fine when I disable both), the only thing that changed is by how much the memory increase, it was between 20 and 50 MB per second before, now it's like 2MB per second but still infinite. The normal memory usage should be between 140MB and 250MB.

**Comment by mapx-** [comment]
Open uBO logger, repeat the steps to get again the issue, go back into the logger and you should see what blocked request is repeated ad infinitum

post it here

**Comment by LivexMania** [comment]
![image](https://user-images.githubusercontent.com/121063829/208726611-8c5ea929-c04c-4865-af9d-eaeb93bc1d6e.png)
The thing is, if I understand the log correctely, that there are no repeated blocked requests

**Comment by mapx-** [comment]
test these filters

```
chaturbate.com##+js(aopr, NREUM)
chaturbate.com##+js(aopr, tsQueue)
||static-assets.highwebmedia.com/CACHE/$script,domain=chaturbate.com
@@||static-assets.highwebmedia.com/CACHE/js/output.7ea37368a42d.js$script,domain=chaturbate.com
@@||static-assets.highwebmedia.com/CACHE/js/output.97a5db11ca63.js$script,domain=chaturbate.com
```

**Comment by LivexMania** [comment]
doesn't change anything

**Comment by mapx-** [comment]
try this too

`||chaturbate.com^$csp=script-src * 'unsafe-inline'`

**Comment by LivexMania** [comment]
still nothing

**Comment by mapx-** [comment]
use only 

```
@@||nr-data.net^$domain=chaturbate.com
@@||js-agent.newrelic.com^$script,domain=chaturbate.com
```

**Comment by LivexMania** [comment]
doesn't work. I also just tried on a linux vm and the issue is present with Chrome, I will try with Firefox later

**Comment by LivexMania** [comment]
ok nevermind, I forgot to check the filters when testing.... Sorry

So your 2 options seems to work:
```
chaturbate.com##+js(aopr, NREUM)
chaturbate.com##+js(aopr, tsQueue)
||static-assets.highwebmedia.com/CACHE/$script,domain=chaturbate.com
@@||static-assets.highwebmedia.com/CACHE/js/output.7ea37368a42d.js$script,domain=chaturbate.com
@@||static-assets.highwebmedia.com/CACHE/js/output.97a5db11ca63.js$script,domain=chaturbate.com
```
```
@@||nr-data.net^$domain=chaturbate.com
@@||js-agent.newrelic.com^$script,domain=chaturbate.com
```

**Comment by blkdak2002** [comment]
Ublock Origin Lite is breaking this website.  It started recently and disabling the filtering for the site returns it to normal (but with ads of course). Maybe this is because the thumbnail urls use "https://thumb.live.mmcdn.com/riw/" as part of it. It was a recent change to the lists because it just started breaking the site.

**Comment by stephenhawk8054** [comment]
It will be fixed in next uBOL version.

**Comment by solidsnake8282** [comment]
Looks like uBO is preventing Chaturbate's CSS from loading.

**Comment by b4zz44** [comment]
uBlock is stopping the site loading pages properly, seems to break the CSS? When first enabled uBlock reports between 60 and 140 items blocked (at different times), normally it's adround 5 items. The number of blocked items keeps growing over time, after a few minutes it can be over 1000. 
It even stops the video streams.
If you reset uBlock to defaults the site will load normally. However after a few minutes it stops working again. If you had a video feed open it stops at the same time.
You can keep resetting to defaults and the site will work again for a few minutes, then break again.
Disabling uBlock allows the site to function normally.

**Comment by stephenhawk8054** [comment]
Fixed at https://github.com/uBlockOrigin/uAssets/commit/2643a7738c04c0d82b937c295287982936596cb6
