### ISSUE TITLE
duplichecker.com: breakage

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#16075]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.duplichecker.com/compress-image-to-20kb.php`

### Category

breakage

### Describe the issue

It seems to be caused by uBO's filters.

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![d2](https://user-images.githubusercontent.com/110184059/208584679-67028253-37bb-48c4-b603-64230f74aaa1.png)

</details>

<details><summary>Screenshot (Expected behavior)</summary>

![d1](https://user-images.githubusercontent.com/110184059/208584778-842802f0-829c-467e-9aae-f7575f272069.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 117465
  cosmetic: 152875
  scriptlet: 34002
  html: 864
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 66487-5500, 7h.17m
    adguard-spyware: 35779-3760, 7h.17m
    adguard-spyware-url: 864-4, 7h.17m
    adguard-annoyance: 62319-1529, 7h.17m
    adguard-social: 19501-30, 7h.17m
  default: 
    user-filters: 66-0, never
    ublock-filters: 32324-40, 7h.17m
    ublock-badware: 4211-0, 7h.17m
    ublock-privacy: 301-0, 7h.17m
    ublock-abuse: 77-0, 7h.17m
    ublock-unbreak: 1931-3, 7h.17m
    ublock-quick-fixes: 482-14, 7h.17m
    easylist: 61548-324, 7h.17m
    easyprivacy: 31006-12237, 7h.17m
    TUR-0: 12022-20, 7h.17m
filterset (user): [array of 71 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 597 ms (selfie)
  maxAssetCacheWait: 286 ms
  unsuspendAfter: 117 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    duplichecker.com: 9
    adrecover.com: 1
    google-analytics.com: 2
    google.com: 5
    googletagmanager.com: 1
```
</details>

**Comment by liamengland1** [comment]
caused by `duplichecker.com##.clearfix + style:has-text(min-height:) + div` in uBlock filters
