### ISSUE TITLE
packagetrackr.com: breakage

### ISSUE THREAD

**Issue by Tarun80** [uBlockOrigin/uAssets#16073]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.packagetrackr.com/`

### Category

breakage

### Describe the issue

Error message appears when you enter your tracking numbers.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 116927
  cosmetic: 164261
  scriptlet: 37742
  html: 888
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 66487-5540, 4h.58m
    adguard-spyware: 35779-3788, 4h.58m
    adguard-spyware-url: 864-4, 4h.57m
    adguard-annoyance: 62319-3945, 4h.57m
    fanboy-cookiemonster: 44020-153, 4h.57m
    ublock-annoyances: 4821-4, 4h.57m
  default: 
    user-filters: 4-1, never
    ublock-filters: 32324-68, 4h.58m
    ublock-badware: 4211-0, 4h.58m
    ublock-privacy: 301-0, 4h.58m
    ublock-abuse: 77-0, 4h.58m
    ublock-unbreak: 1931-3, 4h.58m
    ublock-quick-fixes: 482-0, 4h.58m
    easylist: 61590-377, 4h.58m
    easyprivacy: 31007-12264, 4h.57m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 793 ms (selfie)
  maxAssetCacheWait: 144 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    packagetrackr.com: 3
    cloudflareinsights.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||packagetrackr.com/api/v1/track/detecting.json$xhr,1p
```
@ryanbr
