### ISSUE TITLE
ray-ban.com: nuisance

### ISSUE THREAD

**Issue by j5155** [uBlockOrigin/uAssets#16079]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.ray-ban.com/usa/eyeglasses/view-all?facet=ads_f56502_ntk_cs%253A%2522Multicolor%2522%2Cads_f56002_ntk_cs%253A%2522Multicolor%2522%2Cads_f46002_ntk_cs%253A%2522Multicolor%2522%2Cads_f46502_ntk_cs%253A%2522Multicolor%2522&facet=ads_f56502_ntk_cs%253A%2522Blue%2522%2Cads_f56002_ntk_cs%253A%2522Blue%2522%2Cads_f46002_ntk_cs%253A%2522Blue%2522%2Cads_f46502_ntk_cs%253A%2522Blue%2522&pageNumber=1`

### Category

nuisance

### Describe the issue

Ray-Ban Stories popups and in-gallery insertions. Minor and not a super irritating or high priority thing, but it would be great if I didn't have to see them.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2022-12-20 18-54-07](https://user-images.githubusercontent.com/54331556/208817821-c5dc47fb-6489-4ab1-8021-d2886dd2fb9a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 104
filterset (summary): 
  network: 168879
  cosmetic: 221366
  scriptlet: 37797
  html: 888
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 66356-5536, 2d.1h.28m
    adguard-mobile: 8358-148, 2d.1h.29m
    adguard-spyware: 35779-4053, 1d.52m
    adguard-spyware-url: 861-3, 2d.1h.25m
    curben-phishing: 21429-2, 1d.48m
    curben-pup: 187-0, 1d.49m
    adguard-annoyance: 62277-4804, 2d.1h.24m
    adguard-social: 19476-1075, 2d.1h.23m
    fanboy-thirdparty_social: 68-0, 7d.8h.44m
    fanboy-annoyance: 83700-68014, 7d.8h.45m
    fanboy-cookiemonster: 43834-240, 7d.8h.43m
    fanboy-social: 23473-28, 1d.53m
    ublock-annoyances: 4821-4, 2d.1h.30m
    dpollock-0: 11397-517, 2d.1h.32m
  default: 
    user-filters: 4-0, never
    ublock-filters: 32314-88, 2d.1h.31m
    ublock-badware: 4206-0, 2d.1h.27m
    ublock-privacy: 301-0, 2d.22h.16m
    ublock-abuse: 77-0, 2d.22h.15m
    ublock-unbreak: 1930-3, 2d.1h.26m
    ublock-quick-fixes: 482-0, 1d.50m
    easylist: 61719-981, 3d.5h.41m
    easyprivacy: 30998-12767, 3d.5h.40m
    urlhaus-1: 9803-0, 1d.51m
    plowe-0: 3679-3, 6d.3h.49m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 23 redacted]
switchRuleset: 
  added: [array of 40 redacted]
hostRuleset: 
  added: [array of 192 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3616 ms (selfie)
  maxAssetCacheWait: 2000 ms
popupPanel: 
  blocked: 18
  no-remote-fonts: true
  blockedDetails: 
    ray-ban.com: 12
    bounceexchange.com: 1
    d35u1vg1q28b3w.cloudfront.net: 1
    demdex.net: 1
    forter.com: 1
    go-mpulse.net: 1
    monetate.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`ray-ban.com##.rb-banner-tile`

@ryanbr
