### ISSUE TITLE
manofadan.com: detection

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#16087]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crypto.manofadan.com/dashboard`

### Category

detection

### Describe the issue

Detection after login

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 110
filterset (summary): 
  network: 88208
  cosmetic: 28263
  scriptlet: 16778
  html: 865
listset (total-discarded, last-updated): 
  default: 
    user-filters: 18-0, never
    ublock-filters: 32426-309, 2m
    ublock-badware: 4230-0, 2m
    ublock-privacy: 302-1, 2m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1940-2, 2m
    ublock-quick-fixes: 463-4, 2m
    adguard-mobile: 8362-167, 2m
    easylist: 62062-17812, 2m
    easyprivacy: 30820-1748, 2m
    urlhaus-1: 9956-0, 2m
    plowe-0: 3671-3, 2m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1851 ms
  maxAssetCacheWait: 796 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    a-ads.com: 2
    googlesyndication.com: 1
```
</details>

**Comment by king-iskan** [comment]
@mapx- 
this site already update for adblock, so now detection again adblock. can u fix it for this site? thanks

**Comment by mapx-** [comment]
try

```
@@||googlesyndication.com^$xhr,script,domain=manofadan.com
@@||googletagmanager.com/gtm.js$script,xhr,domain=manofadan.com
@@||surfe.pro^$script,xhr,domain=manofadan.com
```

chrome only the last 2 filters

**Comment by king-iskan** [comment]
work. thanks

> try
> 
> ```
> @@||googlesyndication.com^$xhr,script,domain=manofadan.com
> @@||googletagmanager.com/gtm.js$script,xhr,domain=manofadan.com
> @@||surfe.pro^$script,xhr,domain=manofadan.com
> ```
> 
> chrome only the last 2 filters

work. thanks

**Comment by king-iskan** [comment]
@mapx- @JobcenterTycoon 
i need your help again fo this site, already detection. ill already try in chrome dekstop & firefox mobile. same detection.

**Comment by JobcenterTycoon** [comment]
Fixed.

**Comment by king-iskan** [comment]
> Fixed.

@JobcenterTycoon 
need help again, for update this site. he have already update adblock detection again. thanks

**Comment by JobcenterTycoon** [comment]
Works fine for me

**Comment by king-iskan** [comment]
what happend with my device? or maybe can u reproduce for another site, More or less the model is the same as the Manofadan site. name site is cempakajaya.com
or i open new issue for that?
help

**Comment by JobcenterTycoon** [comment]
Ok test

```
manofadan.com,cempakajaya.com##^script:has-text(htmls)
manofadan.com,cempakajaya.com##+js(aeld, load, htmls)
@@||g.adspeed.net/ad.php?do=detectadblocker|$script,xhr
```

**Comment by king-iskan** [comment]
work better, thanks bro. youre the best
