### ISSUE TITLE
m.facebook.com and www.facebook.com filters no longer effective.

### ISSUE THREAD

**Issue by macerg** [uBlockOrigin/uAssets#16082]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://m.facebook.com
https://www.facebook.com

### Describe the issue

Sponsored adds and others no longer being blocked since Facebook page layouts change.

### uBlock Origin version

1.45.2

### Browser name and version

Firefox beta 109.0b2

### Settings

None

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/3367

**Comment by krystian3w** [comment]
adds =/= ads

**Comment by krystian3w** [comment]
The status is more or less:

- we don't cut it in Quick Fixes or Filters*.txt or Annoyances.txt (fears of spoiling the site or the pace exceeding the chance of a procedural filter reaching the widest possible audience on any given day)
- if a sponsored post uses shadow home/root then the chance of distinguishing it is much harder with a procedural filter
