### ISSUE TITLE
mail.google.com: nuisance

### ISSUE THREAD

**Issue by technicallyalex** [uBlockOrigin/uAssets#16085]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

nuisance

### Describe the issue

Google displays an overlay popup suggesting you switch to chrome constantly in gmail.  It seems like the element zapper has stopped being able to block this overlay as using it and then refreshing the page just loads the overlay again and again until you interact with it directly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 86505
  cosmetic: 38848
  scriptlet: 16739
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61519-52, 1d.15h.48m
    easyprivacy: 30990-1171, 5d.16h.1m
    plowe-0: 3678-903, 12d.1h.58m
    ublock-abuse: 77-0, 2d.23h.26m
    ublock-badware: 4187-107, 3d.22h.8m
    ublock-filters: 31525-129, 3d.22h.7m
    ublock-privacy: 254-1, 2d.23h.25m
    ublock-quick-fixes: 387-25, 17h.35m
    ublock-unbreak: 1915-44, 3d.22h.6m
    urlhaus-1: 10154-0, 17h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 217 ms (selfie)
  maxAssetCacheWait: 127 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    google.com: 19
```
</details>

**Comment by mapx-** [comment]
Try enabling one of annoyances list
