### ISSUE TITLE
inquirer.com: breakage

### ISSUE THREAD

**Issue by mzucker** [uBlockOrigin/uAssets#16084]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.inquirer.com/`

### Category

breakage

### Describe the issue

When uBlock origin is enabled, much of the Inquirer.com website is blank. When disabled, headlines and article summaries appear.

### Screenshot(s)

<details>
<summary>Many areas of page blanked with uBlock origin enabled, same areas appear populated when disabled</summary>

Enabled:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3287580/208969474-cf7086d0-0c9d-488d-9f76-25108d850a6e.png">

Disabled:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3287580/208969549-c60cb54d-5fea-41d9-87b3-901df3c94383.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 88955
  cosmetic: 38844
  scriptlet: 16680
  html: 868
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32305-135, 3d.12h.56m
    ublock-badware: 4049-1, 3d.12h.40m
    ublock-privacy: 301-0, 1d.22h.53m
    ublock-abuse: 77-0, 2d.3h.22m
    ublock-unbreak: 1924-2, 3d.12h.22m
    ublock-quick-fixes: 398-0, 16h.5m
    easylist: 63151-517, 3d.13h.13m
    easyprivacy: 30998-1757, 3d.13h.12m
    urlhaus-1: 11053-0, 16h.6m
    plowe-0: 3671-3, 1d.22h.51m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1390 ms (selfie)
  maxAssetCacheWait: 177 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    inquirer.com: 2
    amazon-adsystem.com: 1
    chartbeat.com: 3
    cxense.com: 1
    doubleclick.net: 1
    go-mpulse.net: 2
    google.com: 1
    googlesyndication.com: 4
    googletagmanager.com: 1
    matheranalytics.com: 1
    npttech.com: 1
    ntv.io: 2
    permutive.app: 1
    permutive.com: 1
    qualaroo.com: 1
    rubiconproject.com: 1
    speedcurve.com: 2
    wknd.ai: 2
    yahoo.com: 1
```
</details>

**Comment by okiehsch** [comment]
Looks fine on my end.
![image](https://user-images.githubusercontent.com/16838044/208974502-ad8ab472-28f3-4a6f-97fa-a9f2faaca2cf.png)

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by ethanbb** [comment]
I reproduce this issue, but only when signed into an inquirer.com account. Other pages on the website appear totally blank when signed in.

**Comment by mapx-** [comment]
Test

`@@||c.amazon-adsystem.com/aax2/apstag.js$script,domain=inquirer.com`

**Comment by ethanbb** [comment]
Thanks, this seems to mostly fix it! There are some ad containers still shown, but the ads themselves are blocked. (Shown: https://www.inquirer.com/food/craig-laban/inq2/philadelphia-best-restaurants-2022-20221221.html) 
![image](https://user-images.githubusercontent.com/8973825/208983786-1ddf0225-b616-433c-b597-a4d3c923c69e.png)

**Comment by mapx-** [comment]
maybe these ones ?

```
inquirer.com##.inno-ad__ad
inquirer.com##.inno-ad
```

**Comment by mapx-** [comment]
@ryanbr 

```
@@||c.amazon-adsystem.com/aax2/apstag.js$script,domain=inquirer.com
inquirer.com##.inno-ad__ad
inquirer.com##.inno-ad
```

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/a6fabf350847a65cba5fe972013759a84e733827

**Comment by mzucker** [comment]
Thanks everyone!
