### ISSUE TITLE
uberhumor.com: popups

### ISSUE THREAD

**Issue by thesneakyTiki** [uBlockOrigin/uAssets#16095]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://uberhumor.com/`

### Category

popups

### Describe the issue

the nowpayments.io popups were fixed last week (immediately i might add, thank you) but have returned

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 83845
  cosmetic: 38892
  scriptlet: 16769
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32306-54, 20h.16m
    ublock-badware: 4211-0, 20h.18m
    ublock-privacy: 301-0, 9d.10h.27m
    ublock-abuse: 77-0, 9d.10h.27m
    ublock-unbreak: 1935-1, 20h.17m
    easylist: 61243-625, 3d.10h.17m
    easyprivacy: 30906-1711, 3d.10h.16m
    urlhaus-1: 7787-0, 24m
    plowe-0: 3678-3, 9d.10h.27m
    ublock-quick-fixes: 482-1, 1d.9h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 20 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 194 ms (selfie)
  maxAssetCacheWait: 83 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    connatix.com: 2
    d188m5xxcpvuue.cloudfront.net: 1
    doubleclick.net: 1
    geoedge.be: 1
    gfycat.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    pinterest.com: 1
    pubmatic.com: 1
    sendtonews.com: 2
    statcounter.com: 2
    storage.googleapis.com: 2
    voqally.com: 1
```
</details>

**Comment by okiehsch** [comment]
An alternative filter is
`uberhumor.com##+js(nostif, nowpayments)`
you can try adding it to your filter list to see if it works for you but the existing filter should be good enough to be honest.

**Comment by thesneakyTiki** [comment]
well i purged and updated again and it seems to have taken care of it.. thanks
