### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by ozanbjk** [uBlockOrigin/uAssets#16093]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Describe the issue

so many ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 88044
  cosmetic: 48086
  scriptlet: 17840
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 12022-11, 2d.19h.20m
    easylist: 61568-73, 2d.19h.17m
    easyprivacy: 31006-1176, 2d.19h.16m
    plowe-0: 3671-903, 2d.19h.14m
    ublock-abuse: 77-0, 2d.19h.12m
    ublock-badware: 4207-107, 2d.19h.10m
    ublock-filters: 31524-121, 2d.19h.1m
    ublock-privacy: 254-1, 2d.19h
    ublock-quick-fixes: 387-18, 15h.50m
    ublock-unbreak: 1917-45, 2d.18h.55m
    urlhaus-1: 9956-0, 15h.49m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 228 ms (selfie)
  maxAssetCacheWait: 74 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    doubleclick.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 2
    sentry.io: 3
    ttvnw.net: 1
```
</details>

**Comment by mapx-** [comment]
twitch
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
