### ISSUE TITLE
portal.discover.com: breakage

### ISSUE THREAD

**Issue by r0ute** [uBlockOrigin/uAssets#16091]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://portal.discover.com/customersvcs/ficoscore/score/showUniversalScore`

### Category

breakage

### Describe the issue

Tabs like "Total accounts", "Lenght of Credit" are not working when uBlock is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 129596
  cosmetic: 99880
  scriptlet: 19711
  html: 872
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 44004-197, 4d.16h.57m
    RUS-0: 39537-185, 1d.2h.34m
    curben-phishing: 22058-1, 5h.38m
  default: 
    user-filters: 17-0, never
    ublock-filters: 32316-56, 9h.40m
    ublock-badware: 4211-0, 5h.39m
    ublock-privacy: 307-0, 11d.9h.56m
    ublock-abuse: 77-0, 11d.9h.55m
    ublock-unbreak: 1935-2, 13h.41m
    easylist: 64996-624, 1d.6h.39m
    easyprivacy: 30819-1738, 1d.6h.38m
    urlhaus-1: 8695-0, 5h.36m
    plowe-0: 3678-3, 10d.16h.11m
    ublock-quick-fixes: 398-0, 5h.37m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 13 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1663 ms (selfie)
  maxAssetCacheWait: 994 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    discover.com: 3
    btstatic.com: 1
    omtrdc.net: 2
```
</details>

**Comment by mapx-** [comment]
- open uBO logger
- repeat the steps to get again the issue
- go back into the logger, copy and post here all the blocked requests you get there

**Comment by r0ute** [comment]
+1
||omtrdc.net^
--
portal.discover.com
3
beacon
https://mboxedge34.tt.omtrdc.net/m2/discover/mbox/json?
+1
||btstatic.com^$3p
--
portal.discover.com
3
script
https://s.btstatic.com/tag.js#<truncated>

+1
/appmeasurement.js
--
portal.discover.com
1
script
https://portal.discover.com/global/scripts/AppMeasurement.js

+1
||omtrdc.net^
--
portal.discover.com
3
xhr
https://mboxedge34.tt.omtrdc.net/m2/discover/mbox/json?

+1
/appmeasurement.js
--
portal.discover.com
1
script
https://portal.discover.com/global/scripts/AppMeasurement.js

+1
/visitorapi.js
--
portal.discover.com
1
script
https://portal.discover.com/global/scripts/visitorAPI.js?

+0
https://portal.discover.com/customersvcs/ficoscore/score/showUniversalScore

**Comment by r0ute** [comment]
Query params are truncated for privacy reasons

**Comment by mapx-** [comment]
test

`@@||portal.discover.com/global/scripts/visitorAPI.js$script,1p`

if does not work add too:
`@@||portal.discover.com/[global/scripts/AppMeasurement.js$script,1p`

**Comment by mapx-** [comment]
report back with your feedback

**Comment by r0ute** [comment]
It works. Thank you!

**Comment by ryanbr** [comment]
@r0ute can you test if we need both filters or just one?
