### ISSUE TITLE
[nsfw] s.viisaqyw.com: popups

### ISSUE THREAD

**Issue by missisponchik** [uBlockOrigin/uAssets#16097]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://s.viisaqyw.com/h/1645/no5hsxgztfoxt6wmx3ugm4fqz2rzx7xy6zkgossrkranjurzbflhuvi7qopmdzkshjenc2g7lltuv67jodsfhaeinoffpt6l4hipr7obqy62cmz2s5fnow4ykvmnashvydpkjm46v6d2wu6ijd24bxvewopk7b5lko4exz47sczljhvpq6vvhkclncmfitizgtqhu7e7hjewsmqxt5ewbid2kwvduqpjggp62vxjkpo744pyjkz5v65liwzvg4ngza54jszrl5gezoktz3my5zserey4otndmjiyqv2txbg2dtoh2jg7cvdz6zlce6c7avtxq6kumbegizqkp5iai3tzpbkgat3gmufhcumckjhigzpxtxsispnbnvbeibcdugmmqvsc7oghmksxn5rtswqywnnfbidotjl2psdg4b4452zqufunvvkiznrvd4cwslyps24pkrmpzmdixvlo6tg2kltviwh4wbuiqvwo73h4t6wb6x55culcdjmbylkrbm2xu42sgrkwons4prcao3ropzggstdemukxuxqegr5xqvrtibtdow2zst3nfz4fs6vm3nktcde67twziynyxspd5nlgbsmh4lveok437pyj3k6hw2lm2v3njvu4q5dexm7wc2yct2ynv7cwijefuokrqgyvc36r3bmecvcshdeviohr6afctmicad3opv2w?u=https%3A%2F%2Fbongacams10.com%2Ftrack%3Fc%3D756520%26subid%3D1425566024355144%26csurl%3Dhttps%3A%2F%2Fbongacams10.com%2Ffemale%2Ftags%2Fmobile-live%26subid2%3D331915`

### Category

popups

### Describe the issue

> нежелательный сайт.

**unwanted site.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 104348
  cosmetic: 59803
  scriptlet: 17768
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39577-11, 11m
    easylist: 61542-56, 6m
    easyprivacy: 30908-1284, 5m
    plowe-0: 3671-878, 4m
    ublock-abuse: 77-1, 2m
    ublock-badware: 3943-107, never
    ublock-filters: 31097-171, never
    ublock-privacy: 260-1, never
    ublock-quick-fixes: 424-21, never
    ublock-unbreak: 1873-41, never
    urlhaus-1: 11291-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 929 ms
  maxAssetCacheWait: 495 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
You should tell us not the landing page, but the page from which you were redirected to the unwanted page.
