### ISSUE TITLE
bestproducts.com: nuisance

### ISSUE THREAD

**Issue by LikeGamerTr** [uBlockOrigin/uAssets#16096]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bestproducts.com/tech/electronics/g2286/apple-macbook-and-macbook-pro-accessories/?slide=1`

### Category

nuisance

### Describe the issue

The website blocks going back to the previous page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 87148
  cosmetic: 38928
  scriptlet: 16734
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32328-54, 2d.6h.28m
    ublock-badware: 4211-0, 2d.6h.27m
    ublock-privacy: 301-0, 3d.7h.29m
    ublock-abuse: 77-0, 3d.7h.28m
    ublock-unbreak: 1931-2, 2d.6h.26m
    ublock-quick-fixes: 489-0, 1d.4h.18m
    easylist: 61243-608, 2d.17h.50m
    easyprivacy: 30908-1711, 2d.17h.49m
    urlhaus-1: 11053-0, 1d.4h.17m
    plowe-0: 3678-3, 12d.3h.43m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 388 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    ensighten.com: 1
    google.com: 1
    hearstapps.com: 4
    skimresources.com: 1
    youtube.com: 5
```
</details>

**Comment by Procyon-b** [comment]
When I test, clicking on a link in an article opens a new tab. Hence not back history. Are you sure that it's not what's happening to you?

**Comment by LikeGamerTr** [comment]
Yes, it might be because of the operating system and the browser I'm using.
For me, it didn't open a new tab and when i tried to go back, either using
the button or alt+left arrow, it would just redirect me to that page. It's
probably an edge case, so doubt it would be that much of an issue but I
thought I should report it anyway. As some extra info, i'm using firefox
108.0 on Ubuntu 20.04LTS.

Marc Boucher ***@***.***>, 24 Ara 2022 Cmt, 02:11 tarihinde
şunu yazdı:
