### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1609]
![2018-02-23-ogloszenia - sprzedam kupie na olx pl](https://user-images.githubusercontent.com/5884000/36599036-58e5656a-18ae-11e8-80cf-0dc7970a1565.png)

click not work

uBlock filters – Privacy

https://github.com/MajkiIT/polish-ads-filter/issues/6287

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.33
Nano Defender 13.36
Chrome 64.0.3282.186

</details>

**Comment by mapx-** [comment]
I cannot reproduce using default setup + 2 polish lists.

Test uBo or report at nano repository.

**Comment by KonoromiHimaries** [comment]
@mapx- of course, i have this same bug on the ublock

![2018-02-23-ogloszenia - sprzedam kupie na olx pl](https://user-images.githubusercontent.com/5884000/36611319-55980564-18d3-11e8-94ee-b9d5b9152893.png)
`https://www.olx.pl/`

filters list
https://gist.github.com/KonoromiHimaries/6d45189eafa4935cb0ed81050db154fc

uBlock Origin 1.15.2
Chrome 64.0.3282.186
