### ISSUE TITLE
spcs.pro: ads

### ISSUE THREAD

**Issue by ssdhub** [uBlockOrigin/uAssets#16094]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://spcs.pro/sz/igry/android/azartnye/?Link_id=162899`

### Category

ads

### Describe the issue

Уже писал по поводу этого сайта тут https://github.com/uBlockOrigin/uAssets/issues/16025
Они переехали на другй адрес и опять все снова началось 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://cggeajaigdeehhdhb.ru/3fd7223c089a80a2ec2f18722d3d345642345/j7isrhbisuv0ndyu50te.gif
https://cggeajaigdeehhdhb.ru/3fd7223c089a80a2ec2f18722d3d345642345/ixwecz7pyuaj6yai1ton.mp4
https://cggeajaigdeehhdhb.ru/3fd7223c089a80a2ec2f18722d3d345642345/rd46rwhbqtq23fejcyyi.gif.mp4
https://cggeajaigdeehhdhb.ru/3fd7223c089a80a2ec2f18722d3d345642345/j7isrhbisuv0ndyu50te.gif

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 80
filterset (summary): 
  network: 101316
  cosmetic: 60042
  scriptlet: 17869
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 165-2, never
    RUS-0: 39575-11, 49m
    easylist: 61500-56, 51m
    easyprivacy: 30908-1284, 52m
    plowe-0: 3678-879, 9d.44m
    ublock-abuse: 77-1, 55m
    ublock-badware: 4187-108, 3d.19h.29m
    ublock-filters: 31519-144, 3d.19h.27m
    ublock-privacy: 255-1, 54m
    ublock-quick-fixes: 387-18, 47m
    ublock-unbreak: 1917-44, 3d.19h.28m
    urlhaus-1: 7787-0, 48m
filterset (user): [array of 165 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 431 ms (selfie)
  maxAssetCacheWait: 288 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    cggeajaigdeehhdhb.ru: 2
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/6176a8a6cd8e7310017d035ab25916cca3816e5b
