### ISSUE TITLE
Pictures and Videos are blocked together with Ads

### ISSUE THREAD

**Issue by Buffmutti** [uBlockOrigin/uAssets#161]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[http://web.de/magazine/politik/tausende-beten-krankenhaus-thailaendischen-koenig-31957762]`

### Describe the issue

The page of web.de looks normal, but if you click on any article the pictures and videos (and some texts too) in that article are blocked together with the ads.

### Screenshot(s)
WITH uBlock Origin:
![web_de1](https://cloud.githubusercontent.com/assets/22818031/19353267/10d5e30e-9163-11e6-8853-66869fb8204c.JPG)

WITHOUT uBlock Origin:
![web_de2](https://cloud.githubusercontent.com/assets/22818031/19353325/44ca7abc-9163-11e6-89f4-4cd0cdc30efa.JPG)

### Versions

- Browser/version: Chrome Version 53.0.2785.143 m (64-bit)
- uBlock Origin version: uBlock Origin v1.9.10

### Settings

- Activated these Filters:
uBlock Filters,
uBlock Filters - Badware risks,
uBlock Filters - Privacy,
uBlock Filters - Unbreak,
EasyList,
Peter Lowe's Ad Server List,
EasyPrivacy,
Malware Domain List,
Malware domains,
DEU EasyList Germany

Changed nothing else.

### Notes

web.de is the only domain with this issue which i know. I have never seen anything like that on another domain. Maybe its sort of a Anti-Adblock thingy? Or do they store the pictures and videos on the same servers which they use for the ads?

**Comment by gorhill** [comment]
The filter `||uim.tifbs.net^` is EasyPrivacy is causing the issue. Please report to maintainers of EasyPrivacy: <https://forums.lanik.us/viewforum.php?f=64>.

Meanwhile, this custom filter will fix the issue: `@@||uim.tifbs.net/js/$script,domain=web.de`.

**Comment by IDKwhattoputhere** [comment]
@gorhill: This rule will allow the images to load too while keeping the script blocked:
`||uim.tifbs.net/js/*.js$script,redirect=noopjs,domain=web.de`

**Comment by gorhill** [comment]
> This rule will allow the images to load too while keeping the script blocked

I had assumed a redirect would not accomplish anything since there was no error message at the console. There is already an exception in EasyPrivacy for that script for `gewinnspiel.web.de`.

**Comment by IDKwhattoputhere** [comment]
Same goes for `gmx.net`: https://forums.lanik.us/viewtopic.php?p=105627#p105627
`||uim.tifbs.net/js/*.js$script,redirect=noopjs,domain=gmx.net`
