### ISSUE TITLE
[nsfw] tr-us.adsmoloco.com: popups

### ISSUE THREAD

**Issue by StiffGryffindor** [uBlockOrigin/uAssets#16108]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tr-us.adsmoloco.com/rtb/click?exchange=INMOBI&imp_id=3c29c302-0185-1000-e443-5b4babed0030&info=ChDPxrn0xCRPArgBbcTy8jcDEODPk50GGhQIBRoQiuw8SNQoRcCAAAAAAAAAASABKgAyAA&campaign_name=M0pxy0zUCxFvEzRA&dcr=`

### Category

popups

### Describe the issue

This is the site Ublock says is trying to open

`https://tr-us.adsmoloco.com/rtb/click?exchange=INMOBI&imp_id=3c29c302-0185-1000-e443-5b4babed0030&info=ChDPxrn0xCRPArgBbcTy8jcDEODPk50GGhQIBRoQiuw8SNQoRcCAAAAAAAAAASABKgAyAA&campaign_name=M0pxy0zUCxFvEzRA&dcr=`

This is the ad that pops up as a result of it

`https://energystoragect.com/?utm_source=decibel&utm_medium=stackadapt-banner&utm_campaign=ess-fy23&utm_content=prospecting`

I got an email saying my ticket is closed but this same site keeps popping up....please help

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 108
filterset (summary): 
  network: 91533
  cosmetic: 81755
  scriptlet: 22330
  html: 889
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 61628-2333, 1m
    ublock-annoyances: 4880-7, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32424-300, 3d.1h.13m
    ublock-badware: 4210-0, 3d.1h.12m
    ublock-privacy: 302-1, 17h.53m
    ublock-abuse: 77-0, 2h.5m
    ublock-unbreak: 1936-2, 3d.1h.11m
    ublock-quick-fixes: 471-0, 5h.40m
    adguard-mobile: 8362-167, 3d.1h.14m
    easylist: 61866-17814, 3d.1h.16m
    easyprivacy: 30817-1747, 3d.1h.15m
    urlhaus-1: 8397-0, 5h.39m
    plowe-0: 3678-3, 12d.17h.50m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1522 ms
  maxAssetCacheWait: 599 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    adsmoloco.com: 1
```
</details>

**Comment by mapx-** [comment]
What page did you visit and what did you click to be then redirected to that unwanted page ?

**Comment by StiffGryffindor** [comment]
I have no idea...all I know is I can be looking at something say netflix
app or CoD mobile and a screen will pop up saying Ublock has prevented this
ad from opening I back out and it sends me to either the play store to
download a crypto currency app or a website for home energy savings

**Comment by StiffGryffindor** [comment]
I just deleted Mozilla fox and will shut my phone off and redownload it
after I turn it back on in about 10 mins....hopefully that will help

**Comment by mapx-** [comment]
You should scan your device for malware using:
https://www.malwarebytes.com/android

**Comment by stephenhawk8054** [comment]
You opened the same issue already:

https://github.com/uBlockOrigin/uAssets/issues/16102

As it happens outside of the browser, I don't think it can be solved by uBO. You should check your apps or malwares on your phone.

**Comment by StiffGryffindor** [comment]
I understand but I have done a virus scan through Dfender app...cleared
cache, cookies and closed all background apps...since I deleted the Mozilla
I have not had it happen again🤷🏽‍♂️

**Comment by stephenhawk8054** [comment]
Then you might need to report it to Firefox. As you said it happened when the browser isn't opened, it's not related to uBO and nothing uBO can do about it.
