### ISSUE TITLE
dbcnews.tv: ads

### ISSUE THREAD

**Issue by htrafsan** [uBlockOrigin/uAssets#16104]
### Prerequisites

- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.
- [ ] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [x] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [x] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [ ] The issue is not present after disabling uBO in the browser.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Website name: dbc news
Type: news tv channel on Bangladesh
Page URL (specific):
`https://dbcnews.tv/sports`
Bug: Didn't blocked banner ads

https://user-images.githubusercontent.com/61630021/209341434-1bc5f84b-f300-4b27-9383-97506924f2fa.PNG

https://user-images.githubusercontent.com/61630021/209341373-0ac7f144-de2b-49c8-bb03-55c19674c180.png

### A specific URL where the issue occurs.

`https://dbcnews.tv/_next/image?url=%2Fimages%2F300x250%E2%80%93inline-rectangle.png&w=384&q=75`

### Steps to Reproduce

.

### Expected behavior

Block banner ads & trackers

### Actual behavior

Didn't perform blocking banner ads on some page (after enabling all ublock origins filtes in the settings)

### uBO version

1.45.2 (Chrome Web Store)

### Browser name and version

Chrome 108.0.5359.125 (Official Build) (32-bit)

### Operating System and version

Windows 10 2022

**Comment by gorhill** [comment]
Suggested filter:

    dbcnews.tv##[alt^="this is ad"]

**Comment by mapx-** [comment]
@mediumkreation for IndianList
