### ISSUE TITLE
zone-telechargement.bond: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16106]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.zone-telechargement.bond/`

### Category

nuisance

### Describe the issue

Displays unwanted items.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/209356317-e14b42f9-fbd5-4392-9861-be76d27350d5.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 122028
  cosmetic: 68969
  scriptlet: 18137
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1533-0, 10h.26m
    RUS-0: 39602-181, 10h.26m
  default: 
    user-filters: 0-0, never
    FRA-0: 29991-28, 10h.26m
    easylist: 61549-195, 10h.26m
    easyprivacy: 30820-1802, 10h.26m
    plowe-0: 3671-932, 10h.26m
    ublock-abuse: 77-2, 10h.26m
    ublock-badware: 4232-126, 10h.26m
    ublock-filters: 31553-247, 10h.26m
    ublock-privacy: 255-1, 10h.26m
    ublock-quick-fixes: 459-23, 10h.26m
    ublock-unbreak: 1922-45, 10h.26m
    urlhaus-1: 7787-0, 10h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 218 ms (selfie)
  maxAssetCacheWait: 137 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    zone-telechargement.bond: 1
    apathylahuli.website: 1
    facebook.com: 1
    google.com: 2
    pogothere.xyz: 2
    sesoionsglear.xyz: 1
    syenitetatler.tech: 1
```
</details>

**Comment by ghajini** [comment]
can you test this 
```
dl-protect.net,wawacity.*,zone-telechargement.*##+js(aopw, AaDetector)
||stt.zone-telechargement.co^$script,1p
||stt.wawacity.onl^$script,1p
*$script,xhr,3p,denyallow=challenges.cloudflare.com,domain=dl-protect.net
*$script,3p,denyallow=googleapis.com,domain=wawacity.onl
zone-telechargement.*,wawacity.*##[href^="https://dl-protect.net/request-premium-url"]
```

**Comment by mapx-** [comment]
could you refresh all your lists ? or even reinstall uBO + update the lists

**Comment by mapx-** [comment]
Did you report at french list ?

`zone-telechargement.boo##[href*="premium"]`

**Comment by stephenhawk8054** [comment]
Most filters are already in wildcard `zone-telechargement.*`

**Comment by mapx-** [comment]
yes, remove it , it was for those fake buttons (`telechargement direct`)

**Comment by JobcenterTycoon** [comment]
Its already covered.
