### ISSUE TITLE
poczta.wp.pl: ads

### ISSUE THREAD

**Issue by EnderCorePL** [uBlockOrigin/uAssets#16100]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://poczta.wp.pl/w/`

### Category

ads

### Describe the issue

Ads pop up on email page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 84380
  cosmetic: 38946
  scriptlet: 16727
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-4, never
    ublock-filters: 32308-55, 1d.19h.44m
    ublock-badware: 4211-0, 23h.28m
    ublock-privacy: 301-0, 2d.21h.8m
    ublock-abuse: 77-0, 2d.21h.7m
    ublock-unbreak: 1935-2, 23h.27m
    ublock-quick-fixes: 464-0, 1h.12m
    easylist: 61909-609, 1d.23h.11m
    easyprivacy: 30815-1737, 1d.23h.10m
    urlhaus-1: 7787-0, 1h.11m
    plowe-0: 3678-3, 11d.23h.51m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 196 ms (selfie)
  maxAssetCacheWait: 92 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    wp.pl: 3
    criteo.net: 6
    gemius.pl: 1
    googletagservices.com: 3
    grupawp.pl: 1
    inistrack.net: 1
```
</details>

**Comment by mapx-** [comment]
Enable the polish lists.
Still viewing ads => report at polish lists repositories.

**Comment by EnderCorePL** [comment]
Works, thank you and sorry.  
            
          
     
      
       
        Dnia 22 grudnia 2022 19:31 mapx ***@***.***&gt; napisał(a):
       
    
       
         
 Enable the polish lists.  
Still viewing ads =&gt; report at polish lists repositories.
