### ISSUE TITLE
[nsfw] tr-us.adsmoloco.com: popups

### ISSUE THREAD

**Issue by StiffGryffindor** [uBlockOrigin/uAssets#16102]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tr-us.adsmoloco.com/rtb/click?exchange=INMOBI&imp_id=3c29c302-0185-1000-e443-5b4babed0030&info=ChDPxrn0xCRPArgBbcTy8jcDEODPk50GGhQIBRoQiuw8SNQoRcCAAAAAAAAAASABKgAyAA&campaign_name=M0pxy0zUCxFvEzRA&dcr=`

### Category

popups

### Describe the issue

Unwanted pop ups...at random times, the web browsers aren't even open and the internet will open a pop up in the middle of ANYTHING. I have ublock origin and it prevents the popup from opening fully but still annoying that I am in the middle of a CoD mobile match and my game will force close and show the pop block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox Mobile: 108
filterset (summary): 
  network: 85835
  cosmetic: 28260
  scriptlet: 16766
  html: 865
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32424-299, 2d.7h.26m
    ublock-badware: 4210-0, 2d.7h.25m
    ublock-privacy: 302-1, 6m
    ublock-abuse: 77-0, 12d.10h.37m
    ublock-unbreak: 1936-2, 2d.7h.24m
    ublock-quick-fixes: 464-0, 13h.20m
    adguard-mobile: 8362-167, 2d.7h.27m
    easylist: 61866-17812, 2d.7h.29m
    easyprivacy: 30817-1747, 2d.7h.28m
    urlhaus-1: 7787-0, 13h.19m
    plowe-0: 3678-3, 12d.3m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 405 ms (selfie)
  maxAssetCacheWait: 202 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    adsmoloco.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> the web browsers aren't even open

I don't think this is related to uBO.
