### ISSUE TITLE
spanishdict.com redux

### ISSUE THREAD

**Issue by CaptainFrosty** [uBlockOrigin/uAssets#1611]
### URL(s) where the issue occurs

`http://www.spanishdict.com`

### Describe the issue

Ad blocker popup window and notice on the right side of the page are showing although there is an entry for spanishdict.com in the Adblock Warning Removal List and the uBlock Annoyances filter. The Annoyances filter may be outdated as I can't find the element `.ad-wrapper` it refers to.

### Screenshot(s)

![ss1](https://user-images.githubusercontent.com/8523498/36441430-9fd77e60-1640-11e8-9e3a-e1a611b8a970.jpg)
![ss2](https://user-images.githubusercontent.com/8523498/36441438-a86105ec-1640-11e8-8196-9372f10cebee.jpg)

### Versions

- Browser/version: Chrome 64.0.3282.167 (Official Build) (32-bit)
- uBlock Origin version: v1.15.2

### Settings

- Disable pre-fetching (to prevent any connection for blocked network requests) 
- Disable hyperlink auditing 
- Prevent WebRTC from leaking local IP addresses 
- Block CSP report

**Comment by mapx-** [comment]
continue here:
https://github.com/uBlockOrigin/uAssets/issues/1579
