### ISSUE TITLE
[nsfw] linkvertise.com: detection

### ISSUE THREAD

**Issue by apkmodz** [uBlockOrigin/uAssets#16110]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://linkvertise.com/530799/fluxus-android-free2/2`

### Category

detection

### Describe the issue

why doesn't ublock origin bypass linkvertise.com?😡

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium Mobile: 107
filterset (summary): 
  network: 90017
  cosmetic: 29430
  scriptlet: 16785
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    IDN-0: 5399-231, 1d.21h.34m
    adguard-mobile: 8362-31, 1d.21h.34m
    easylist: 61953-17309, 1d.21h.31m
    easyprivacy: 30908-1185, 1d.21h.30m
    plowe-0: 3671-957, 1d.21h.28m
    ublock-abuse: 77-0, 1d.21h.26m
    ublock-badware: 4226-108, 1d.21h.24m
    ublock-filters: 31635-374, 1d.21h.23m
    ublock-privacy: 260-2, 1d.21h.22m
    ublock-quick-fixes: 458-22, 21h.21m
    ublock-unbreak: 1927-47, 1d.21h.20m
    urlhaus-1: 7787-0, 20h.59m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1846 ms (selfie)
  maxAssetCacheWait: 802 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    brightcove.com: 4
    doubleclick.net: 2
    googletagmanager.com: 1
    media.net: 1
    nighttstand.com: 1
    ostrichesica.com: 2
    streamrail.com: 1
    taboola.com: 1
    youtube.com: 4
```
</details>

**Comment by liamengland1** [comment]
` [x]  I did not answer truthfully to all the above checkpoints`

**Comment by stephenhawk8054** [comment]
I don't see any anti-adblock on the page.

**Comment by apkmodz** [comment]
but, why ublock origin can't bypass it?, you can, but how come you have to
use a VPN first then you can?, I'm from Indonesia, please fix it, maybe
ublock origin doesn't support Indonesia?

Pada tanggal Sab, 24 Des 2022 10:39, stephenhawk8054 <
***@***.***> menulis:

**Comment by stephenhawk8054** [comment]
I'm afraid I don't understand what you mean and what you want. I do not have VPN to Indonesia so I used VPN to Singapore.

The `Free Access` button appears normally for me

![image](https://user-images.githubusercontent.com/66517106/209418776-82828ae9-0a60-4738-b1c6-697c81087586.png)

**Comment by apkmodz** [comment]
I mean, maybe ublock origin doesn't support Indonesia, so when I want to
bypass linkvertise, I have to use a VPN, if you don't use a VPN, it won't
bypass linkvertise

Pada tanggal Sab, 24 Des 2022 10:53, stephenhawk8054 <
***@***.***> menulis:

**Comment by stephenhawk8054** [comment]
What do you mean by bypass? Can you take a screenshot of the page?

**Comment by apkmodz** [comment]
bruh, look this vid https://youtu.be/VnD23AWiyCM

Pada tanggal Sab, 24 Des 2022 11:01, stephenhawk8054 <
***@***.***> menulis:

**Comment by stephenhawk8054** [comment]
I'm still not clear what you mean. The steps I took is:

1. Open the link you give in OP: `https://linkvertise.com/530799/fluxus-android-free2/2`
2. Solve the captcha
3. Click on `Free Access` button
4. A `flux.li` link appears in new tab
5. Solve the captcha on the `flux.li` page and it redirects to `linkvertise.com` again
6. Repeat the 2 -> 5 steps

I'm not sure what else you mean. If you mean bypass all of those steps in one click, then you might need a userscript or extension dedicated for it as uBO does not support it yet.

**Comment by ghajini** [comment]
he means bypass from linkvertise to directly to destination link which extensions like fastforward/universal bypass liked to do

**Comment by ghajini** [comment]
Test
 
`linkvertise.com##+js(json-prune, data.meta.require_custom_ad_step data.meta.og_ads_offers)`

**Comment by FaerC** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/149038277/20a82f57-df90-4d8c-b720-e60742fd8b9f)

**Comment by FaerC** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/149038277/1b59f01c-acc9-4633-9962-2034f2ee57a4)

**Comment by FaerC** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/149038277/6f12e5a8-972c-4fa2-b409-527767c03d63)

**Comment by FaerC** [comment]
What doing?

**Comment by mapx-** [comment]
I get the **detection** only when I'm **using a vpn** - **even disabling uBO**
