### ISSUE TITLE
na.se: breakage

### ISSUE THREAD

**Issue by subtilt** [uBlockOrigin/uAssets#16117]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.na.se/2022-12-19/se-oxfilestolderna-pa-parkhallen--rensar-kylen`

### Category

breakage

### Describe the issue

Can't view the video frames used on this website (video host is flowplayer)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 102
filterset (summary): 
  network: 207107
  cosmetic: 201739
  scriptlet: 39083
  html: 914
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 66639-6123, 2d.21h.55m
    adguard-spyware: 35797-4070, 2d.11h.16m
    adguard-spyware-url: 865-4, 2d.11h.14m
    block-lan: 44-0, 2d.11h.19m
    curben-phishing: 20430-2, 18h.35m
    curben-pup: 186-0, 6h.29m
    adguard-annoyance: 61629-5782, 1d.5h.33m
    adguard-social: 19552-1677, 1d.2h.28m
    fanboy-thirdparty_social: 69-1, 4d.8h.49m
    fanboy-annoyance: 84023-72044, 4d.7h.30m
    fanboy-cookiemonster: 44141-17396, 4d.7h.29m
    fanboy-social: 23476-13749, 2d.11h.18m
    ublock-annoyances: 4880-7, 1d.2h.31m
    dpollock-0: 11397-475, 9d.10h.38m
    CHN-0: 28658-1387, 1d.2h.30m
    NOR-0: 3049-181, 18h.36m
    RUS-0: 39626-1210, 1h
    SWE-1: 4362-310, 1d.2h.29m
  default: 
    user-filters: 707-0, never
    ublock-filters: 32426-318, 2d.21h.58m
    ublock-badware: 4210-0, 2d.21h.57m
    ublock-privacy: 307-1, 1d.8h.5m
    ublock-abuse: 77-0, 1d.8h.4m
    ublock-unbreak: 1940-3, 2d.21h.56m
    ublock-quick-fixes: 398-0, 18h.34m
    adguard-mobile: 8370-207, 2d.11h.17m
    easylist: 64996-18041, 18h.39m
    easyprivacy: 30820-12681, 18h.38m
    urlhaus-1: 8118-0, 11h.17m
    plowe-0: 3671-3, 5d.7h.55m
filterset (user): [array of 707 redacted]
trustedset: 
  added: [array of 26 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 8 redacted]
hostRuleset: 
  added: [array of 34 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  popupPanelLockedSections: 1
  popupPanelHeightMode: 1
  uiStyles: font-family: sans-serif
supportStats: 
  allReadyAfter: 1327 ms (selfie)
  maxAssetCacheWait: 664 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    bonad.io: 1
    privacy-center.org: 1
```
</details>

**Comment by mapx-** [comment]
I guess an account is required

@lassekongo83

**Comment by subtilt** [comment]
I am logged in @ na.se with a registered account

**Comment by subtilt** [comment]
The video frame that is blocked on this site uses flowplayer.com to store their video material on apparently. I've tried to whitelist the flowplayer.com domain but to no avail.

**Comment by subtilt** [comment]
Nevermind. It fixed the issue. Closing ticket.

**Comment by mapx-** [comment]
> I fixed the problem

Tell us what filter did you add to fix it ?

**Comment by subtilt** [comment]
![Screenshot_20221225_163115](https://user-images.githubusercontent.com/43752157/209473888-df10ac0d-9d6a-424a-9eec-e3fa06e9cc1a.png)

**Comment by mapx-** [comment]
well, is not a fix you whitelisted almost all requests, let's see swedish list maintainer

**Comment by subtilt** [comment]
I know but it works for me on this site. As long as I can view the video frames on that site I'm happy. However, if you think you'll be able to fix it properly, I am more than happy for you to help me fix the issue.

**Comment by subtilt** [comment]
![Screenshot_20221225_164319](https://user-images.githubusercontent.com/43752157/209474218-6d2675db-d3af-42b1-9e42-d59c6eb50db1.png)

na.se is listed on Swedish Frellwill filter list.

**Comment by lassekongo83** [comment]
I can't access anything on na.se. But on hd.se (same owner and site design) I can access a page with a flowplayer video: `https://www.hd.se/2022-12-23/nyhetskollen-med-hd-pixlapirens-verksamheter-stangs` and it works just fine. The video will not be visible if you block `privacy-center.org` which is in Fanboy's Cookiemonster list. So try: `@@||privacy-center.org^$domain=na.se`

**Comment by subtilt** [comment]
"@@||privacy-center.org^$domain=na.se" worked flawlessly. So that solved the issue. Thanks!

**Comment by mapx-** [comment]
@ryanbr
