### ISSUE TITLE
[nsfw] youtube.com: privacy

### ISSUE THREAD

**Issue by 666Guest666Master666** [uBlockOrigin/uAssets#16119]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.youtube.com/`

### Category

privacy_entries

### Describe the issue

it's not loading

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 93
filterset (summary): 
  network: 88768
  cosmetic: 38638
  scriptlet: 16732
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64996-53, 1d.1h.40m
    easyprivacy: 30908-1171, 1d.1h.39m
    plowe-0: 3672-869, 1d.1h.38m
    ublock-abuse: 77-0, 1d.1h.36m
    ublock-badware: 4237-108, 1d.1h.34m
    ublock-filters: 31589-109, 1d.1h.33m
    ublock-privacy: 255-1, 1d.1h.32m
    ublock-quick-fixes: 387-16, 1d.1h.31m
    ublock-unbreak: 1911-46, 1d.1h.30m
    urlhaus-1: 8642-0, 1d.1h.29m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8439 ms (selfie)
  maxAssetCacheWait: 2955 ms
popupPanel: 
  blocked: 3
  no-scripting: true
  blockedDetails: 
    youtube.com: 1
    doubleclick.net: 1
    ytimg.com: 1
```
</details>

**Comment by 666Guest666Master666** [comment]
- `[https://www.youtube.com/](url)` 
- fix this Youtube

> https://www.youtube.com/

**Comment by Nojuuu** [comment]
You seem to have Javascript blocked, you need to allow it.

**Comment by 666Guest666Master666** [comment]
Ok @Nojuuu 
I'll allow

**Comment by 666Guest666Master666** [comment]
I allowed it
