### ISSUE TITLE
gettr.com: breakage

### ISSUE THREAD

**Issue by TheNightRider12** [uBlockOrigin/uAssets#16112]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://gettr.com/`

### Describe the issue

With the following filter lists enabled: EasyList Cookie and Fanboy's Annoyance, and then going to: `https://gettr.com/`,
the only button available on the left hand side is the Plus button to create a post. Whereas without those filters enabled, there are options for: "Home", "Live", "Vision", "Notifications", etc. 

According to the log, I believe both of those filters are at fault.

### Screenshot(s)

With those filters not enabled:
![image](https://user-images.githubusercontent.com/8153239/209453197-4594f818-11be-458a-b71c-dd13686f2381.png)

With those filters enabled:
![image](https://user-images.githubusercontent.com/8153239/209453209-9ead9c51-5c18-4b1d-b62a-7e42e216d938.png)

uBo Filter Log
![image](https://user-images.githubusercontent.com/8153239/209453221-9d9d96b1-c7dc-4335-b8cd-55f30b112e67.png)

### uBlock Origin version

1.46.0

### Browser name and version

Firefox Nightly. Version: 110. 12-24-2022

### Settings

- Default Settings
- Then: Enabled Easy List Cookie and Fanboy Annoyances.

**Comment by stephenhawk8054** [comment]
@ryanbr
