### ISSUE TITLE
spigotunlocked.com: detection

### ISSUE THREAD

**Issue by thedifference12** [uBlockOrigin/uAssets#16115]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://spigotunlocked.com/`

### Category

detection

### Describe the issue

Adblock detected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20221225-144700~2](https://user-images.githubusercontent.com/121382995/209466737-901253ce-b77b-49e0-9bc3-15d169e047f8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 87733
  cosmetic: 37681
  scriptlet: 18036
  html: 865
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32503-385, 2m
    ublock-badware: 4245-0, 2m
    ublock-privacy: 302-1, 2m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1942-2, 2m
    ublock-quick-fixes: 456-0, 2m
    adguard-mobile: 8398-167, 3m
    easylist: 61841-17773, 2m
    easyprivacy: 30828-1752, 2m
    urlhaus-1: 8118-0, 2m
    plowe-0: 3672-2, 2m
    TUR-0: 12364-182, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10496 ms
  maxAssetCacheWait: 1052 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    spigotunlocked.com: 4
    google.com: 2
    googlesyndication.com: 4
    googletagmanager.com: 1
```
</details>

**Comment by Raidware** [comment]
@mapx- again

![Screenshot_20240526_175953](https://github.com/uBlockOrigin/uAssets/assets/136184400/3e301f6b-1f98-4423-9da4-9a1af3b53aa8)
