### ISSUE TITLE
sms24.me: breakage

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#16114]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [ ] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [ ] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://sms24.me/en/countries/ge`

### Category

breakage

### Describe the issue

website content not showing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![wwwww](https://user-images.githubusercontent.com/110184059/209458453-3ebc4265-8f69-49f0-a711-af9d4c82d024.png)

</details>

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/209458456-dedf72ab-e044-4948-b377-4e108278ce84.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 117705
  cosmetic: 153137
  scriptlet: 33726
  html: 864
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 66722-5561, 36m
    adguard-spyware: 35806-3755, 36m
    adguard-spyware-url: 866-5, 36m
    adguard-annoyance: 61645-1513, 36m
    adguard-social: 19555-25, 36m
  default: 
    user-filters: 66-0, never
    ublock-filters: 32393-80, 36m
    ublock-badware: 4241-0, 36m
    ublock-privacy: 302-0, 36m
    ublock-abuse: 77-0, 36m
    ublock-unbreak: 1938-2, 36m
    ublock-quick-fixes: 456-0, 36m
    easylist: 61841-317, 36m
    easyprivacy: 30828-12148, 36m
    TUR-0: 12364-11, 36m
filterset (user): [array of 71 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1032 ms (selfie)
  maxAssetCacheWait: 400 ms
  unsuspendAfter: 221 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    adoptum.net: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Adguard base issue @Yuki2718

**Comment by Yuki2718** [comment]
> Adguard base issue

But happens only on uBO. Will exclude.
