### ISSUE TITLE
colamanhua.com: detection

### ISSUE THREAD

**Issue by Kaiko77456** [uBlockOrigin/uAssets#16111]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.colamanhua.com/manga-hk27639/1/59.html`

### Category

detection

### Describe the issue

The browser blocks the display of important components, please ensure that no small plug-ins are enabled, which will affect page loading

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 105388
  cosmetic: 37343
  scriptlet: 16925
  html: 865
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32450-305, 15m
    ublock-badware: 4240-0, 14m
    ublock-privacy: 307-1, 13m
    ublock-abuse: 77-0, 12m
    ublock-unbreak: 1940-2, 11m
    ublock-quick-fixes: 465-0, 10m
    adguard-mobile: 8395-167, 20m
    easylist: 61745-17855, 9m
    easyprivacy: 30908-1720, 8m
    urlhaus-1: 9273-0, 7m
    plowe-0: 3672-2, 6m
    CHN-0: 28658-1390, 20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1058 ms
  maxAssetCacheWait: 349 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    colamanhua.com: 2
    couplestupidity.com: 1
    googletagmanager.com: 1
    vouninked.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't see any important components being blocked. Can you take a screenshot to show it?

**Comment by mapx-** [comment]
I cannot reproduce the issue, however CHN list is blocking a xhr (bait) request 

try adding
`@@||colamanhua.com/logo/ad.js$xhr,1p`

**Comment by huizichin** [comment]
Seem to be on the mobile site, once again.
https://github.com/uBlockOrigin/uAssets/issues/13003#issuecomment-1113188059
For mobile, add an exception of 
`@@||[www.colamanhua.com/js/a_d/pic1.png$image,domain=www.colamanhua.com](http://www.colamanhua.com/js/a_d/pic1.png$image,domain=www.colamanhua.com)`

**Comment by huizichin** [comment]
> I cannot reproduce the issue, however CHN list is blocking a xhr (bait) request
> 
> try adding `@@||colamanhua.com/logo/ad.js$xhr,1p`

that didn't seem to work. migrate the rule from old domain to new domain from cocomanga.com to colamanhua.com

**Comment by stephenhawk8054** [comment]
Last time I could not reproduce on mobile, but I can today. Confirm `colamanhua.com##+js(nostif, loadErrorTip)` works

**Comment by stephenhawk8054** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
I can't reproduce.

**Comment by ghyeng** [comment]
The site's domain has changed from https://colamanhua.com/ to https://www.colamanga.com/ and the same issue happens again, requiring an update to the filter.

**Comment by stephenhawk8054** [comment]
@ghyeng Does this filter work?

```adb
colamanga.com##+js(nostif, loadErrorTip)
```

**Comment by ghyeng** [comment]
> @ghyeng Does this filter work?
> 
> ```
> colamanga.com##+js(nostif, loadErrorTip)
> ```

Yes, it works.

**Comment by stephenhawk8054** [comment]
@Yuki2718
