### ISSUE TITLE
kanald.ro: breakage

### ISSUE THREAD

**Issue by sn-o-w** [uBlockOrigin/uAssets#16121]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.kanald.ro/live.html`

### Category

breakage

### Describe the issue

The videoplayer refuses to load.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.1b1
Chromium: 109
filterset (summary): 
  network: 128882
  cosmetic: 103799
  scriptlet: 46663
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://cdn.jsdelivr.net/gh/bogachenko/fuckfuckadblock/fuckfuckadblock.txt: 24191-41, never
    https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 0-0, never
    https://www.i-dont-care-about-cookies.eu/abp/: 25670-14, never
    adguard-generic: 66728-6009, never
    adguard-mobile: 8395-332, never
    adguard-spyware: 35806-14825, never
  default: 
    user-filters: 21-1, never
    ROU-1: 1156-57, never
    easylist: 61783-173, never
    easyprivacy: 30824-1147, never
    plowe-0: 3672-902, never
    ublock-abuse: 77-0, never
    ublock-badware: 4237-0, never
    ublock-filters: 31597-2841, never
    ublock-privacy: 255-0, never
    ublock-quick-fixes: 446-0, never
    ublock-unbreak: 1925-44, never
    urlhaus-1: 9273-0, never
filterset (user): [array of 21 redacted]
trustedset: 
  added: [array of 221 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 14 redacted]
  removed: 
    no-large-media: behind-the-scene false
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 2834 ms
  maxAssetCacheWait: 18 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    adtlgc.com: 1
    cloudflare.com: 1
    cxense.com: 2
```
</details>

**Comment by mapx-** [comment]
update the romanian list

**Comment by sn-o-w** [comment]
@mapx- It looks like it no longer works. 😥

**Comment by mapx-** [comment]
I tested FF / chrome with a non-romanian ip => failed, then using a ROU IP is working fine

**Comment by mapx-** [comment]
if you are not in Romania, use this page:

`https://www.cool-etv.net/ch/kanald.htm`

**Comment by sn-o-w** [comment]
@mapx- I live in Romania.

**Comment by mapx-** [comment]
You can use that link in Romania too.

However it seems a little instable kanald site even using a romanian ip, sometimes I get hls errors with / without uBO enabled => no uBO issue

**Comment by sn-o-w** [comment]
@mapx- In my case, the live stream fails to load if uBO is enabled, but it works well if uBO is disabled. 🤔

I have a Romanian IP, and my ISP is DIGI.

**Comment by mapx-** [comment]
tested again in chrome, I added all your lists you are using => still ok on my end

follow these indications (even if you say disabling uBO the video will play ok)

- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by sn-o-w** [comment]
@mapx- Clearing the cookies and cache really helped. Thanks! 😊
