### ISSUE TITLE
nobook.com: breakage

### ISSUE THREAD

**Issue by shc0743** [uBlockOrigin/uAssets#16125]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.nobook.com/`

### Category

breakage

### Describe the issue

The website `www.nobook.com` stops working when I enable uBlock Origin.
After I check it, it works in these situations:
- Disable uBo
- Disable the filter: `EasyPrivacy`  
- Add a dynamic rule: ` www.nobook.com nobook-oss-publish-cdn.nobook.com * allow `

In the recorder, it shows that the required script was blocked by the rule: ` /sensorsdata.$domain=~sensorsdata.cn ` in the filter ` EasyPrivacy `, so the website stops working.

<details>
<summary>Browser Console</summary>

![image](https://user-images.githubusercontent.com/60457042/209504596-09e2d03b-c738-46a8-b8c8-c134e4727884.png)

</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/60457042/209503556-949946f1-e32b-4d38-90a9-80732ba9730c.png)
![image](https://user-images.githubusercontent.com/60457042/209503581-1632c9d5-4ec8-416e-88f1-39ca8fd34f0d.png)
![image](https://user-images.githubusercontent.com/60457042/209503591-09f07032-f731-4b72-af72-8ef8202a652f.png)
![image](https://user-images.githubusercontent.com/60457042/209503658-e74de9ca-0811-4e6c-8cf8-f0a815551b86.png)
![image](https://user-images.githubusercontent.com/60457042/209504268-2dd98be1-8ba3-4b80-81e7-e6d75d597382.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 142099
  cosmetic: 155138
  scriptlet: 35758
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    adguard-annoyance: 61645-98, 1d.2h.8m
    adguard-generic: 66718-535, 1d.2h.8m
    adguard-social: 19555-823, 1d.2h.8m
    adguard-spyware: 35806-4453, 1d.2h.8m
    adguard-spyware-url: 866-2, 1d.2h.8m
    curben-pup: 193-0, 47m
    fanboy-thirdparty_social: 69-3, 1d.2h.7m
    ublock-annoyances: 4806-185, 1d.2h.7m
  default: 
    user-filters: 41-0, never
    CHN-0: 28667-102, 1d.2h.8m
    easylist: 61832-960, 1d.2h.7m
    easyprivacy: 30824-12325, 1d.2h.7m
    ublock-abuse: 77-0, 1d.2h.7m
    ublock-badware: 4237-289, 1d.2h.7m
    ublock-filters: 31599-3772, 1d.2h.6m
    ublock-privacy: 255-47, 1d.2h.6m
    ublock-quick-fixes: 451-51, 46m
    ublock-unbreak: 1925-107, 1d.2h.6m
    urlhaus-1: 7431-0, 45m
filterset (user): [array of 42 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoUpdateDelayAfterLaunch: 120
supportStats: 
  allReadyAfter: 25319 ms (selfie)
  maxAssetCacheWait: 2441 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    nobook.com: 1
    baidu.com: 1
```
</details>

**Comment by mapx-** [comment]
`@@||nobook-oss-publish-cdn.nobook.com/open-interface/official-sensors.git/$script,1p`

@ryanbr
