### ISSUE TITLE
ebay-kleinanzeigen.de: suppresses images from thumbnail / gallery

### ISSUE THREAD

**Issue by VetaLioSTV** [uBlockOrigin/uAssets#16128]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.ebay-kleinanzeigen.de/s-anzeige/bmw-e46-320d-lichtschalter-lichtmodul-xenon/2310552971-223-1652`

### Describe the issue

As it mentioned here (#14039 , #215 , #14459 ) , problem still remains with much worse experience. In preview mode it just swaps image with blank white screen(check video below) and in gallery mode it breaks functionality and suppresses / hides (check video below) image at all.

### Screenshot(s)

With uBlock Enabled - 

https://user-images.githubusercontent.com/15155286/209579539-a4ad19b6-ea24-465f-b8a0-9665badbe6f3.mp4

With uBlock Disabled -

https://user-images.githubusercontent.com/15155286/209580764-d55131f9-15ea-451d-aa24-7b9ed3f18b01.mp4

### uBlock Origin version

1.45.2

### Browser name and version

Chrome 108.0.5359.125

### Settings

No changes, all stuff is default.

### Notes

- Account isn't needed , you can test it in incognito or just without account
- Its hard to say which excatly image it blocks/suppresses, sometimes somewhere in middle(i think it depends on quantity of images?), but can't say on 100% thats everytime like this, since usually its a random.

**Comment by mapx-** [comment]
add

`@@||img.ebay-kleinanzeigen.de/api/$image,1p`

@ryanbr

**Comment by VetaLioSTV** [comment]
> add
> 
> `@@||img.ebay-kleinanzeigen.de/api/$image,1p`
> 
> @ryanbr

Hi, thanks for fast reply. 

I have been added to my filter your code and it worked partially. Preview images are shown now, same as in gallery, but only missing thumbnail from bottom. 

Check this - 

https://user-images.githubusercontent.com/15155286/209584159-9ea88174-6e10-4408-80f1-c69e313a2fff.mp4

**Comment by mapx-** [comment]
I get all 3 thumbnails at the bottom, did you use other regional lists (other than german list) ?

**Comment by VetaLioSTV** [comment]
> I get all 3 thumbnails at the bottom, did you use other regional lists (other than german list) ?

Nope, just default settings of uBlock.

**Comment by VetaLioSTV** [comment]
@mapx- hey, what about my last video, what can i do?... I dont know why you closed issue, since it not fixed till end :(

**Comment by mapx-** [comment]
> I get all 3 thumbnails at the bottom

if your issue is missing some thumbnails I cannot reproduce it

open the logger, reproduce the issue, go back into the logger, post here all blocked items

**Comment by VetaLioSTV** [comment]
> > I get all 3 thumbnails at the bottom
> 
> if your issue is missing some thumbnails I cannot reproduce it
> 
> open the logger, reproduce the issue, go back into the logger, post here all blocked items

here it is(blocked stuff) :

`<details><summary>Logger output</summary>

```
+6
##.ad-active
www.ebay-kleinanzeigen.de
dom
https://www.ebay-kleinanzeigen.de/s-anzeige/bmw-e46-320d-lichtschalter-lichtmodul-xenon/2310552971-223-1652
```
```
+5
/roverimp/*
--
www.ebay-kleinanzeigen.de
3
image
https://rover.ebay.de/roverimp/0/0/9?imp=1605053&trknvp=user_id%3D89138892%26cadid%3D2310552971%26reg%3DNordrhein-Westfalen%2520-%2520Augustdorf%26rurl%3D&mpt=1672167004111
```
```
+2
##.ad-loader
www.ebay-kleinanzeigen.de
dom
https://www.ebay-kleinanzeigen.de/s-anzeige/bmw-e46-320d-lichtschalter-lichtmodul-xenon/2310552971-223-1652
```
```
+2
###banner-skyscraper
www.ebay-kleinanzeigen.de
dom
https://www.ebay-kleinanzeigen.de/s-anzeige/bmw-e46-320d-lichtschalter-lichtmodul-xenon/2310552971-223-1652
```
```
+2
||googleadservices.com^
--
www.ebay-kleinanzeigen.de
3
script
https://www.googleadservices.com/pagead/conversion.js
```
```
+2
||bat.bing.com^
--
www.ebay-kleinanzeigen.de
3
script
https://bat.bing.com/bat.js
```
```
+2
||ioam.de^
--
www.ebay-kleinanzeigen.de
3
script
https://script.ioam.de/iam.js?m=1
```
```
+2
google-analytics_analytics.js
<<
www.ebay-kleinanzeigen.de
3
script
https://www.google-analytics.com/analytics.js
```
```
+2
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics_analytics.js:5
--
www.ebay-kleinanzeigen.de
3
script
https://www.google-analytics.com/analytics.js
```
```
+2
||google-analytics.com^
--
www.ebay-kleinanzeigen.de
3
script
https://www.google-analytics.com/analytics.js
```
```
+2
||criteo.net^
--
www.ebay-kleinanzeigen.de
3
script
https://static.criteo.net/js/ld/ld.js
```
```
+2
||criteo.net^
--
www.ebay-kleinanzeigen.de
3
script
https://static.criteo.net/js/ld/publishertag.js
```
```
+2
||aaxads.com^
--
www.ebay-kleinanzeigen.de
3
script
https://c.aaxads.com/aax.js?pub=AAX255244&hst=www.ebay-kleinanzeigen.de&ver=1.2
```
```
+2
/advertisingwebrenderer.min.js
--
www.ebay-kleinanzeigen.de
1
script
https://www.ebay-kleinanzeigen.de/liberty/advertising-web-renderer/umd/advertisingWebRenderer.min.js
```
```
+2
amazon_apstag.js
<<
www.ebay-kleinanzeigen.de
3
script
https://c.amazon-adsystem.com/aax2/apstag.js
```
```
+2
||amazon-adsystem.com/*/apstag.js$script,redirect-rule=amazon_apstag.js
--
www.ebay-kleinanzeigen.de
3
script
https://c.amazon-adsystem.com/aax2/apstag.js
```
```
+2
||amazon-adsystem.com^
--
www.ebay-kleinanzeigen.de
3
script
https://c.amazon-adsystem.com/aax2/apstag.js
```
```
+1
||googletagmanager.com^
--
www.ebay-kleinanzeigen.de
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-WHRTL83
```
```
+1
/akam/13/*
--
www.ebay-kleinanzeigen.de
1
script
https://www.ebay-kleinanzeigen.de/akam/13/78cb45c2
```
```
+1
||google.com/adsense/search/
--
www.ebay-kleinanzeigen.de
3
script
https://www.google.com/adsense/search/ads.js
```
```
+1
googletagservices_gpt.js
<<
www.ebay-kleinanzeigen.de
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+1
||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule=googletagservices_gpt.js:5
--
www.ebay-kleinanzeigen.de
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+1
||doubleclick.net^
--
www.ebay-kleinanzeigen.de
3
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js
```
```
+1
/prebid/*$script
--
www.ebay-kleinanzeigen.de
1
script
https://www.ebay-kleinanzeigen.de/liberty/liberty-js/prebid/prebid.js
```
```
+1
/prebid.$domain=~prebid.org
--
www.ebay-kleinanzeigen.de
1
script
https://static.ebay-kleinanzeigen.de/static/js/belen/tracking/adblock-detection/prebid.o6vsfdxitnq.js
```
```
+0
https://www.ebay-kleinanzeigen.de/s-anzeige/bmw-e46-320d-lichtschalter-lichtmodul-xenon/2310552971-223-1652
```
</details>
`

Also, when i disable "cosmetic" filters on page, it works as it should, please check -


https://user-images.githubusercontent.com/15155286/209710411-6823e02a-e8fe-4972-ab0d-655015d9c6ca.mp4

**Comment by mapx-** [comment]
The site is a german one.
I guess you didn't enable the regional list => `DEU: EasyList Germany`

**Comment by VetaLioSTV** [comment]
> The site is a german one. I guess you didn't enable the regional list => `DEU: EasyList Germany`

yes, i didn't, since i'm not from Germany and its only one german website i visit frequently... So i need to enable it additionally ?

**Comment by mapx-** [comment]
regions, languages => enable DEU list

**Comment by VetaLioSTV** [comment]
> click `Regions, languages` => enable DEU list

I added DEU in setting of uBlock and seems to be it works from now as it should. Many thanks. Cheers!

**Comment by VetaLioSTV** [comment]
@mapx- hey, does some regression appeared ? I have again issues with images :(

Should i open new standalone issue?

**Comment by stephenhawk8054** [comment]
Just continue in this thread.

**Comment by VetaLioSTV** [comment]
> Just continue in this thread.

Ok, so again at gallery mode it hides one image (e.g. 4 image available inside of ad and only 3 are shown in gallery mode).

[Source link](https://www.kleinanzeigen.de/s-anzeige/fahrrad-maedchen-zundapp-20-zoll/2433381155-217-7531) ( account not required, you can do it even in anonymous tab)

With uBlock enabled( plus all settings which are applied are described in comments above ^, like enabled regional list "DEU" and etc) -

https://user-images.githubusercontent.com/15155286/236344569-2e79df8b-09bf-4912-99d9-bb6b5aab2b92.mp4

uBlock disabled -

https://user-images.githubusercontent.com/15155286/236344825-4a199fa8-9826-40dc-9841-889eea1ce0da.mp4

**Comment by mapx-** [comment]
Update all ubo lists

**Comment by VetaLioSTV** [comment]
> Update all ubo lists

Could you assist? I can't see where i can do it. "Update now" button isnt active (at category "Filter list").

**Comment by stephenhawk8054** [comment]
Click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now).

**Comment by VetaLioSTV** [comment]
> Click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now).

I did it another way, added checkmark on **uBlock filters – Quick fixes** afterwards **Update now** button became enabled and it did the job, now it works as it should.

Two poitns - 

1) what excatly happened? Someone made rollback of applied changes?

2) Should i uncheck **uBlock filters – Quick fixes** or its fine to have it?

Thank you!

**Comment by stephenhawk8054** [comment]
It was not fixed in `uBlock filters – Quick fixes` list. It was fixed in `uBlock filters – Unbreak` list. Just do the steps above to force update all the filter lists.

> Should i uncheck uBlock filters – Quick fixes or its fine to have it?

It's one of the default list to hotfix if some issues are urgent. Just leave it be and don't disable it.

**Comment by VetaLioSTV** [comment]
> It's one of the default list to hotfix if some issues are urgent. Just leave it be and don't disable it.

Ok, got you. I will leave it as enabled(checkmark applied), but why its not active by default? I mean, in my case i didn't tweak uBo at all and it wasn't enabled. Does it has some side effect?

**Comment by stephenhawk8054** [comment]
That's weird. It should be enabled by default. Which version of uBO are you using?

**Comment by VetaLioSTV** [comment]
> That's weird. It should be enabled by default. Which version of uBO are you using?

current version uBlock Origin 1.49.2 , i downloaded its from chrome store (official extension)

**Comment by VetaLioSTV** [comment]
@stephenhawk8054 Hi there. 
So again problem appears.

Could you check [here is link](https://www.kleinanzeigen.de/s-anzeige/bmw-e46-teile/2000438220-223-2181) , in preview / gallery mode one image at center hides and not available.

I already tried to clear cache and update all lists, didn't helped.

**Comment by VetaLioSTV** [comment]
@mapx- any updates? Why that happens? It was fixed once (a long time ago), why it appears again?
