### ISSUE TITLE
New Spotify adds

### ISSUE THREAD

**Issue by Affratus** [uBlockOrigin/uAssets#1612]
Hi, It's seems the ads on spotify again, here is the log for the current problem 
![image](https://user-images.githubusercontent.com/10071459/36617415-efd24cf2-1919-11e8-83f3-46aba5240d16.png)

The reproduction step is the same as the previous problem, add some song to library and spam next button until the ads show up. Could you help again this time @okiehsch ,Thanks :)

**Comment by okiehsch** [comment]
Do you get ads, or do you get stuck like in the previous issue?

**Comment by Affratus** [comment]
stuck ads like the previous issue
![image](https://user-images.githubusercontent.com/10071459/36619449-72e6251c-1921-11e8-96c0-c6013d062936.png)

**Comment by okiehsch** [comment]
I can't reproduce that, this is my logger output with your repro steps
![unbenannt](https://user-images.githubusercontent.com/16838044/36619808-76119090-18f0-11e8-8697-9325ecb1c1db.PNG)
and I do not get stuck.

**Comment by Affratus** [comment]
Huh.. that is weird, maybe because I allow the doubleclick? I'll try to remove the doubleclick first.

**Comment by Affratus** [comment]
so, here's my log after removing the the allow doubleclick filter
![image](https://user-images.githubusercontent.com/10071459/36620272-d6940e64-1924-11e8-9685-324b9653e38a.png)

the difference between my filter and yours is the red spotify.com^&/metric at the top and in my log after the doubleclick there's quadruple https://gae-spclient.spotify.com/melody/v1/logging/client_event and there is none on your log, maybe that is what caused the difference?

**Comment by okiehsch** [comment]
Well, allow the blocked metrics-backend request and try again.

**Comment by Affratus** [comment]
wait, It's weird, I've 2 instance where the ads is just passing by without getting stuck, but it's pretty rare, try to redo the  reproduction step, maybe you will get stuck ads this time.

And also, how to I allow the blocked metric-backend request?

**Comment by okiehsch** [comment]
`@@||spclient.wg.spotify.com/metrics-backend/*$xmlhttprequest,first-party`

**Comment by Affratus** [comment]
I've got a new result after adding that filter, the ads is not stuck anymore, it's just that the player itself is stopped, return to the state like when it's first opened, no songs playing and the time bar set to 0:00

Here's the log after I use the filter
![image](https://user-images.githubusercontent.com/10071459/36621293-d6edb2b6-1929-11e8-8538-26dffbeb0773.png)

and this is what the player is looks like
![image](https://user-images.githubusercontent.com/10071459/36621322-fc5e8d7c-1929-11e8-88e4-c29800da01b8.png)

I've tried both allowing and blocking the doubleclick, neither is working.

**Comment by okiehsch** [comment]
Well , I tried quite a few times and I never got stuck, so I can't help.
Maybe somebody else can reproduce your issue and come up with a working solution.

**Comment by Affratus** [comment]
yeah, looks like no luck for me this time, I was also checking the reddit first to see if anyone else is having the same problem, looks like there are some that are also encountering this problem, https://www.reddit.com/r/uBlockOrigin/comments/7zb9id/ads_are_back_on_spotify_web_player_need_help/
but looks like not everyone is affected, oh well, maybe someone will stumble upon this issue page and could provide some more detail of what is missing in the reproduction  step. Thanks for your time btw :)

**Comment by okiehsch** [comment]
No problem. I also noticed some reddit threads that sounded similar to your issue but, like you said, it seems to affect only some users.

**Comment by Nofritofi** [comment]
Hi, I had the same issue. Since there didn't seem to be a solution I decided to allow/block things one after the other to see if I might find something that works well enough.
Maybe this set up works for you too. Haven't been stuck on an ad since and had 'em ever 15 songs or so before.
First I put everything green on Spotify only:

![new 1](https://user-images.githubusercontent.com/36949648/36868020-5ddfe818-1d97-11e8-83c9-2a0c9b8f89c3.png)

then I added these perm. rules:

![new 2](https://user-images.githubusercontent.com/36949648/36868145-b61412c0-1d97-11e8-8ebf-b19a8d40782f.png)

plus this filter: (though I don't know if it's having any effect)
||audio-fa.scdn.co/audio/*$media,redirect=noopmp3-0.1s,domain=open.spotify.com

good luck.
