### ISSUE TITLE
royalroad.com: ads

### ISSUE THREAD

**Issue by harrysalzman** [uBlockOrigin/uAssets#16126]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.royalroad.com/fiction/57505/his-soul-is-marching-on-to-another-world-or-the/chapter/967946/ii-john-browns-knapsack-is-strapped-upon-his-back`

### Category

ads

### Describe the issue

Still shows an ad towards the bottom of each chapter, blocking it doesn't seem to work. On Firefox Android.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 84960
  cosmetic: 28352
  scriptlet: 16808
  html: 865
listset (total-discarded, last-updated): 
  default: 
    user-filters: 26-6, never
    ublock-filters: 32486-301, 2d.10h.59m
    ublock-badware: 4048-1, 7h.27m
    ublock-privacy: 301-1, 7h.28m
    ublock-abuse: 77-0, 2h.3m
    ublock-unbreak: 1940-1, 1d.23h.5m
    adguard-mobile: 8395-167, 1d.23h.6m
    easylist: 61549-17821, 2d.13h.53m
    easyprivacy: 30820-1748, 2d.13h.52m
    urlhaus-1: 7431-0, 2h.2m
    plowe-0: 3672-2, 15h.23m
    ublock-quick-fixes: 456-1, 15h.21m
filterset (user): [array of 26 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6129 ms (selfie)
  maxAssetCacheWait: 2053 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googletagmanager.com: 1
    nitropay.com: 6
```
</details>

**Comment by mapx-** [comment]
add

```
royalroad.com##[href^="/advertising/redirect"]
royalroad.com##.text-center
royalroad.com##.wide
```

@ryanbr
