### ISSUE TITLE
lmtribune.com: nuisance

### ISSUE THREAD

**Issue by sniffersnipe** [uBlockOrigin/uAssets#16129]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lmtribune.com/northwest/`

### Category

nuisance

### Description

Pop-up soliciting subscription.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 68
filterset (summary): 
  network: 88803
  cosmetic: 27970
  scriptlet: 16780
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32417-295, 46m
    ublock-badware: 4245-0, 45m
    ublock-privacy: 302-1, 2d.7h.39m
    ublock-abuse: 77-0, 2d.7h.38m
    ublock-unbreak: 1942-2, 44m
    adguard-mobile: 8404-167, 48m
    easylist: 64993-17790, 1d.5h.30m
    easyprivacy: 30824-1747, 1d.5h.31m
    urlhaus-1: 7316-0, 43m
    plowe-0: 3670-3, 9d.11h.15m
    ublock-quick-fixes: 398-0, 42m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
    moz-extension-scheme
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4901 ms (selfie)
  maxAssetCacheWait: 1058 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    lmtribune.com: 6
    adlightning.com: 2
    amazon-adsystem.com: 1
    crwdcntrl.net: 3
    doubleclick.net: 1
    googleadservices.com: 2
    googletagmanager.com: 2
    liqwid.net: 2
    townnews.com: 14
```
</details>

**Comment by mapx-** [comment]
Test

`lmtribune.com##.modal`

@ryanbr
