### ISSUE TITLE
mopar.com: breakage

### ISSUE THREAD

**Issue by nomaddc** [uBlockOrigin/uAssets#16131]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mopar.com/dodge/en-us/my-vehicle/dashboard.html`

### Category

breakage

### Description

Breaks the website functionality - major chunks of page get stuck in loading splash and nothing happens. uBlock was reset to default. Turning uBlock off lets the page work as intended.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 83778
  cosmetic: 39070
  scriptlet: 16770
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61850-43, now
    easyprivacy: 30831-1171, now
    plowe-0: 3672-900, now
    ublock-abuse: 77-0, now
    ublock-badware: 4242-107, now
    ublock-filters: 31609-111, now
    ublock-privacy: 257-1, now
    ublock-quick-fixes: 454-29, now
    ublock-unbreak: 1925-44, now
    urlhaus-1: 7271-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 727 ms
  maxAssetCacheWait: 104 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    mopar.com: 2
    go-mpulse.net: 2
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Test this filter

`@@||mopar.com/moparsvc/mopar-analytics-state$script,1p`

**Comment by nomaddc** [comment]
It worked, everything loads now properly

**Comment by Nautious** [comment]
### URL address of the web page
https://www.mopar.com/en-ca/my-vehicle/recalls/search.html

### Category
breakage

### Description
Entering your vehicle VIN on this page with Basic or Optimal filtering enabled causes the website to briefly load the next page but then takes you back to the page with the fill-in form. Disabling filtering makes it work. 

Note: I can provide a VIN if necessary.

### Configuration

```yaml
name: uBlock Origin Lite
version: 2025.1116.1841
browser: Chrome 142 (win)
filtering:
 site: basic
 default: optimal
permission: all
rulesets:
 easylist
 easyprivacy
 pgl
 ublock-badware
 ublock-filters
 urlhaus-full
```

**Comment by stephenhawk8054** [comment]
Please provide the VIN. If it's personal information, you can send to this email: `stephenhawk8054@protonmail.com`

**Comment by Nautious** [comment]
Here's some public VINs for testing:

3C6UR5FL9NG261014
1C4RJFBG5JC269774

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtag/js$domain=mopar.com
```

@ryanbr
