### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by abdulmajidsir** [uBlockOrigin/uAssets#16133]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Description

اعلانات بشكل فضيع 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 104
filterset (summary): 
  network: 105718
  cosmetic: 48369
  scriptlet: 16855
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30002-28, 17h.6m
    ara-0: 2737-5, 17h.6m
    easylist: 61843-223, 17h.3m
    easyprivacy: 30908-1502, 17h.2m
    plowe-0: 3672-897, 17h.1m
    ublock-abuse: 77-1, 16h.59m
    ublock-badware: 4045-126, 16h.57m
    ublock-filters: 31525-238, 16h.56m
    ublock-privacy: 257-1, 16h.55m
    ublock-quick-fixes: 454-21, 16h.53m
    ublock-unbreak: 1911-46, 16h.52m
    urlhaus-1: 7316-0, 16h.51m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 276 ms (selfie)
  maxAssetCacheWait: 68 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    google-analytics.com: 1
    imrworldwide.com: 1
    scorecardresearch.com: 2
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
twitch
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
