### ISSUE TITLE
[nsfw] shopee-0903.myshopify.com: privacy

### ISSUE THREAD

**Issue by tcharles13** [uBlockOrigin/uAssets#16134]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shopee-0903.myshopify.com/products/geladeira-top-freezer-com-dispenser-de-agua-platinum-400l-dw44s?variant=44207096037662&currency=BRL&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic`

### Category

privacy

### Description

fake brazilian store

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 348506
  cosmetic: 224892
  scriptlet: 37722
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD@master/anti-ad-surge.txt: 59147-2, 4d.23h.47m
    https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.tpl: 9-0, 4d.23h.50m
    https://easylist-msie.adblockplus.org/antiadblockfilters.tpl: 101-1, 4d.23h.29m
    https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/dnsmasq.conf: 113651-0, 4d.23h.51m
    https://raw.githubusercontent.com/badmojr/1Hosts/master/mini/dnsmasq.conf: 57247-48651, 4d.23h.52m
    adguard-annoyance: 61673-89, 1d.43m
    adguard-generic: 66882-555, 23h.5m
    adguard-mobile: 8398-44, 23h.4m
    adguard-social: 19566-824, 1d.44m
    adguard-spyware: 36998-4445, 23h.2m
    adguard-spyware-url: 867-2, 23h.3m
    block-lan: 44-0, 4d.23h.27m
    curben-phishing: 19042-0, 1d.39m
    curben-pup: 193-0, 1d.40m
    dpollock-0: 11397-282, 5d.16h.1m
    fanboy-annoyance: 84024-5147, 5d.16h.2m
    fanboy-cookiemonster: 44141-44141, 5d.16h.2m
    fanboy-social: 23473-23473, 5d.16h.2m
    fanboy-thirdparty_social: 69-21, 5d.16h.2m
    ublock-annoyances: 4807-236, 1d.45m
  default: 
    user-filters: 0-0, never
    easylist: 62062-1339, 5d.16h.2m
    easyprivacy: 30820-12609, 5d.16h.2m
    plowe-0: 3671-1422, 5d.16h.2m
    spa-1: 4897-84, 1d.49m
    ublock-abuse: 77-0, 5d.16h.2m
    ublock-badware: 4237-294, 1d.48m
    ublock-filters: 31604-3829, 1d.47m
    ublock-privacy: 255-53, 5d.16h.2m
    ublock-quick-fixes: 450-51, 1d.42m
    ublock-unbreak: 1924-111, 1d.46m
    urlhaus-1: 7431-1, 1d.41m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1934 ms (selfie)
  maxAssetCacheWait: 1408 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    shopify.com: 4
    shopifycloud.com: 5
    shopifysvc.com: 1
```
</details>

**Comment by krystian3w** [comment]
Blacklisted by Eset (anti-phishing list).

**Comment by krystian3w** [comment]
Portuguese error about store unavailability may be a ploy to get Google and Microsoft to overlook phishing report,

**Comment by mapx-** [comment]
`This store is unavailable`
