### ISSUE TITLE
mreader.co: breakage

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#16139]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mreader.co/reader/en/martial-peak-chapter-2908-eng-li/`

### Category

breakage

### Description

doesnt load Comments with adblock on 
1 pic expected behavior
2 pic reality

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-12-27 195053](https://user-images.githubusercontent.com/100969549/209710110-30778ac8-7e70-4a06-912a-6cba507f6e37.png)

![Screenshot 2022-12-27 195028](https://user-images.githubusercontent.com/100969549/209710136-59303027-c2fb-4004-8cad-dc580d467a66.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 226677
  cosmetic: 248402
  scriptlet: 39117
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/6_optimized.txt: 6167-108, 2d.21h.38m
    https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4251-4, 2h.39m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 42-0, 20h.31m
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, 2h.38m
    https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, 2h.37m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5619-1, 11d.38m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-5, 6d.23h.45m
    https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, 2h.36m
    https://raw.githubusercontent.com/nabble/semalt-blocker/master/domains/blocked: 2433-2, 2h.35m
    https://winhelp2002.mvps.org/hosts.txt: 8730-63, 2h.34m
    CHN-0: 28659-102, 2d.21h.33m
    JPN-1: 8593-12, 2d.21h.32m
    adguard-annoyance: 61646-122, 2d.21h.44m
    adguard-generic: 66718-709, 2d.21h.43m
    adguard-mobile: 8395-148, 2d.21h.42m
    adguard-social: 19555-825, 2d.21h.41m
    adguard-spyware: 35806-4851, 2d.21h.40m
    adguard-spyware-url: 866-2, 2d.21h.39m
    block-lan: 44-0, 13d.3h.55m
    curben-phishing: 18494-0, 5h.26m
    [7 lists not shown]: [too many]
  default: 
    user-filters: 94-3, never
    DEU-0: 6072-2580, 5h.25m
    easylist: 61846-1583, 1d.1h.36m
    easyprivacy: 30908-12898, 1d.1h.35m
    plowe-0: 3671-1558, 5d.3h.34m
    ublock-abuse: 77-57, 7d.4h.34m
    ublock-badware: 4237-294, 2d.21h.36m
    ublock-filters: 31525-3778, 2d.21h.35m
    ublock-privacy: 254-83, 7d.4h.33m
    ublock-quick-fixes: 387-50, 5h.23m
    ublock-unbreak: 1925-116, 2d.21h.34m
    urlhaus-1: 7422-1, 5h.22m
filterset (user): [array of 94 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 35 redacted]
hostRuleset: 
  added: [array of 82 redacted]
urlRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1646 ms (selfie)
  maxAssetCacheWait: 651 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    bidgear.com: 4
    disqus.com: 2
    neeladou.net: 9
    outoctillerytor.com: 1
    pubfuture.com: 1
    tzegilo.com: 1
```
</details>

**Comment by mapx-** [comment]
for comments issue add

`mreader.co#@#iframe[src]`

explain better:

> 1 pic expected behavior 2 pic reality

**Comment by mapx-** [comment]
@ryanbr
