### ISSUE TITLE
[nsfw] ddys.art: detection

### ISSUE THREAD

**Issue by 0xiaoluli0** [uBlockOrigin/uAssets#16135]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ddys.art/`

### Category

detection

### Description

When watching videos on this site, an ad blocking plugin is detected at the beginning of the video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 101942
  cosmetic: 49268
  scriptlet: 16906
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    CHN-0: 28683-103, 10h.8m
    easylist: 61843-78, 10h.5m
    easyprivacy: 30831-1194, 10h.4m
    plowe-0: 3672-902, 10h.3m
    ublock-abuse: 77-0, 10h.1m
    ublock-badware: 4242-107, 9h.58m
    ublock-filters: 31614-129, 9h.57m
    ublock-privacy: 257-1, 9h.56m
    ublock-quick-fixes: 454-29, 9h.55m
    ublock-unbreak: 1924-45, 9h.54m
    urlhaus-1: 7271-0, 9h.53m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 993 ms
  maxAssetCacheWait: 86 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    cloudflareinsights.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
ddys.*##+js(no-fetch-if, analytics)
```

@Yuki2718 For adguard chinese. Site might have other TLDs too: `https://ddys.site/`

**Comment by Yuki2718** [comment]
It detects EP so AG doesn't suffer, and the anti-adb is only 10 seconds delay (soft anti-adb). Should be added to Annoyances.
