### ISSUE TITLE
sozcu.com.tr: detection

### ISSUE THREAD

**Issue by hbelgen** [uBlockOrigin/uAssets#16149]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sozcu.com.tr/2022/gundem/son-dakika-sabiha-gokcende-ucus-trafigi-durdu-tuzlada-dogal-gaz-borusu-patladi-7538376/`
=>
`https://www.sozcu.com.tr/reklam-engelleyici`

### Category

detection

### Description

Until today it was working fine, but now te site dedected ublock. Please fix it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 101738
  cosmetic: 174875
  scriptlet: 22261
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 61746-91, 11m
    fanboy-annoyance: 84546-4064, 11m
  default: 
    user-filters: 2196-40, never
    TUR-0: 12365-11, 2d.4h.3m
    easylist: 64996-129, 2d.4h.4m
    easyprivacy: 30828-1263, 2d.4h.5m
    plowe-0: 3672-900, 2d.4h.7m
    ublock-abuse: 77-0, 1d.13m
    ublock-badware: 4242-108, 2d.4h.2m
    ublock-filters: 31600-502, 2d.4h.1m
    ublock-privacy: 257-9, 1d.12m
    ublock-quick-fixes: 452-23, 10m
    ublock-unbreak: 1924-49, 2d.3h.59m
    urlhaus-1: 7327-0, 9m
filterset (user): [array of 1995 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1157 ms (selfie)
  maxAssetCacheWait: 331 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    sozcu.com.tr: 1
    becdn.net: 1
    cookiepro.com: 2
    doubleclick.net: 1
    gemius.pl: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    ilan.gov.tr: 1
    onesignal.com: 1
    sozcucdn.com: 3
    taboola.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update your filter lists. Its already fixed in the regional filter list `TUR: AdGuard Turkish`
