### ISSUE TITLE
novaflix.io: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16141]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wvw.novaflix.io/`

### Category

nuisance

### Description

Fake download buttons appear.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/209715327-8ba76557-a80e-4977-bdb3-ee333552cd60.png)

`https://wvw.novaflix.io/12861-la-mort-vous-va-si-bien.html`

The fake buttons are displayed on the different pages of the site

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 122683
  cosmetic: 109301
  scriptlet: 19870
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39651-171, 1h.47m
    fanboy-cookiemonster: 44374-215, 1h.47m
  default: 
    user-filters: 0-0, never
    FRA-0: 30004-28, 1h.47m
    easylist: 61700-232, 1h.47m
    easyprivacy: 30835-1590, 1h.47m
    plowe-0: 3673-931, 1h.47m
    ublock-abuse: 77-2, 1h.47m
    ublock-badware: 4242-125, 1h.47m
    ublock-filters: 31607-263, 1h.47m
    ublock-privacy: 257-1, 1h.47m
    ublock-quick-fixes: 454-29, 1h.47m
    ublock-unbreak: 1925-46, 1h.47m
    urlhaus-1: 7422-0, 1h.47m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 208 ms (selfie)
  maxAssetCacheWait: 117 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    ads-blue.com: 1
    histats.com: 2
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
add

```
novaflix.io##.pmovie__rbutton
novaflix.io###pub
```

for classic filters - french sites report here:
https://github.com/easylist/listefr/issues

@smed79
