### ISSUE TITLE
linkneverdie.net: detection

### ISSUE THREAD

**Issue by Ungic** [uBlockOrigin/uAssets#16147]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkneverdie.net/`

### Category

detection

### Description

If no log in the website, ublock is not be detected
But when i log in, the website detects ublock

### Screenshot(s)

https://user-images.githubusercontent.com/119843310/209771889-967afd08-50cf-4c8c-9234-e5e065c5ebff.png

https://user-images.githubusercontent.com/119843310/209771920-3a836d71-14f8-4acc-a128-6747ceec65ce.png

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 84545
  cosmetic: 40055
  scriptlet: 16854
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1919-0, 17m
    easylist: 61738-65, 17m
    easyprivacy: 30843-1174, 17m
    plowe-0: 3673-901, 17m
    ublock-abuse: 77-0, 17m
    ublock-badware: 4242-107, 17m
    ublock-filters: 31613-118, 17m
    ublock-privacy: 257-1, 17m
    ublock-quick-fixes: 454-29, 17m
    ublock-unbreak: 1914-44, 17m
    urlhaus-1: 7327-0, 17m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5947 ms (selfie)
  maxAssetCacheWait: 448 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    linkneverdie.net: 2
    addthis.com: 1
    doubleclick.net: 1
    facebook.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    optad360.io: 2
    pubmatic.com: 2
```

</details>

**Comment by mapx-** [comment]
Test

`linkneverdie.net##+js(nostif, catch)`

@hoang-rio
