### ISSUE TITLE
upfilesurls.com: detection

### ISSUE THREAD

**Issue by ahmadk13** [uBlockOrigin/uAssets#16140]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://upfilesurls.com/`

### Category

detection

### Description

The website is detecting uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Screenshot_20221227-201333](https://user-images.githubusercontent.com/55244712/209712419-4994aa84-07df-4006-b09b-c8e491f4d190.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium Mobile: 107
filterset (summary): 
  network: 139257
  cosmetic: 156625
  scriptlet: 37843
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 22h.23m
    NOR-0: 3052-176, 22h.20m
    SWE-1: 4344-306, 22h.36m
    adguard-annoyance: 61714-1675, 22h.33m
    adguard-generic: 66916-996, 22h.25m
    adguard-spyware: 37002-4465, 22h.32m
    adguard-spyware-url: 867-2, 22h.30m
    ara-0: 2737-256, 22h.24m
    fanboy-annoyance: 84055-37756, 5d.1h.18m
    fanboy-cookiemonster: 44004-43971, 8d.3h.32m
    ublock-annoyances: 4853-259, 22h.26m
  default: 
    user-filters: 10-1, never
    adguard-mobile: 8404-63, 22h.34m
    easylist: 61783-18141, 2d.1h.33m
    easyprivacy: 30828-12505, 1d.6h.23m
    plowe-0: 3671-1072, 8d.3h.33m
    ublock-abuse: 77-0, 8d.3h.36m
    ublock-badware: 4241-298, 2d.1h.40m
    ublock-filters: 31721-4012, 22h.27m
    ublock-privacy: 254-53, 8d.3h.35m
    ublock-quick-fixes: 454-55, 22h.21m
    ublock-unbreak: 1927-110, 2d.1h.39m
    urlhaus-1: 7316-0, 22h.22m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 6847 ms
  maxAssetCacheWait: 4057 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
provide the complete link
