### ISSUE TITLE
symless.com: breakage

### ISSUE THREAD

**Issue by traderhut** [uBlockOrigin/uAssets#16157]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://symless.com/synergy/download`

### Category

breakage

### Description

Comes up blank on Raspberry Pi

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 84
filterset (summary): 
  network: 83823
  cosmetic: 39065
  scriptlet: 16783
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61848-43, 1d.19h.4m
    easyprivacy: 30827-1171, 1d.19h.3m
    plowe-0: 3670-901, 10d.19h.33m
    ublock-abuse: 77-0, 1d.10h.55m
    ublock-badware: 4242-108, 1d.19h
    ublock-filters: 31614-111, 1d.19h.2m
    ublock-privacy: 260-1, 1d.10h.56m
    ublock-quick-fixes: 454-29, 18h.53m
    ublock-unbreak: 1924-44, 1d.19h.1m
    urlhaus-1: 7327-0, 18h.54m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1026 ms (selfie)
  maxAssetCacheWait: 460 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    facebook.net: 1
    googletagmanager.com: 2
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
open the logger, reproduce the issue, go back in the logger. copy & paste here all the blocked itens you see there

**Comment by traderhut** [comment]
What logger???

I was assuming this was a note to yourself, as you would need to see why
the website wasn't sending anything to the browser?   (Standard browser on
Raspberry Pi - is there a logger in it??)

Are you talking about the Developer Tools dialog?  I've never heard any
developer call that the 'logger', so that would be doubtful, but there is a
.Js file that is showing as blocked there..
fbevents.js seems to be blocked, but I can't figure out why.  (and I don't
remember how I got the Pi to move something to the clipboard, and it seems
that no one else on the planet knows either...  I did it once...





-------

**Comment by stephenhawk8054** [comment]
> What logger???

This one:

https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by traderhut** [comment]
I guess this, from the web page:
"uBlock Origin (uBO) comes with a logger,"

This begs the question: WTF is uBlock Origin??

 (My question has to do with the download page for the Synergy 1 Pro, for
the Raspberry Pi, which you should see the issue by going to that page from
ANY Raspberry Pi 4, and you will see a blank page.
-------

**Comment by mapx-** [comment]
You are here because you are using uBO.
That page explains how to enable the logger.
We don't have an account on symless, so, if you want to be helped, instead of WTF => follow the steps above then post here the items you see in the logger.

**Comment by traderhut** [comment]
Oh, I must have been using this software (which I've never heard of ) for
years and find it amazing.. :-). I looked up on the Wiki page for it, and
found it came out in 2014, so it could, in fact, be included and installed
with Rasbian WITHOUT my knowledge.    As you pointed out, I am here because
I can't get the Download page on Symless.com/Download to work on a
Raspberry Pi, and have never heard of, or used (to my knowledge)
uBlockOrigin before, So, Rather than telling me to click on a button in the
UI of a popup for software that I've never heard of...  You might consider
telling what it *IS*... However, thankfully, I can go off and google and
read WikI's and such on my own to see if there is, in fact, any
correlation between the web page and this software you are telling me
exists on my machine... So, I did...

In particular, I did some research, and found that this software apparently
is a plug-in for Chromium, so IF it is installed BY DEFAULT on raspbian,
then I could, in fact be 'using' it (without knowing it)

My configuration:
     CLEAN install of Raspbian, a bit over 3 years ago.   So, keep in mind
that I'd be running a version of uBlock that is at *least* 3 years old, and
running on (of course) a Raspberry Pi.  Specifically, I'm running:
Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l
GNU/

     It appears that it was added to Debian 9, in 2017, so apparently, it
is possible that this software is in fact installed and running..

OK... So,I had ZERO clue how to confirm that, I don't use Chromium much on
that machine, it is running unattended for the most part on a 10" monitor
and it is hard to see..

After spending a bunch of time trying to find this software's 'popup' I
finally located that it was under a little red icon in Chromium that I had
never clicked on before.  (I didn't even know what browser was installed on
this machine, as I just used it to get to a couple websites to install some
software)...

And the screen was blank, but then I figured out that I needed to reload
the webpage to get it to populate..

Instead of telling me to 'follow the directions, it might have been nice to
tell me WT.. the software WAS, and how to bring up the UI for it, so I
*COULD* follow the instructions that you assumed that I could 'just follow'
without having a CLUE what I was looking for!  That would have been REALLY
helpful...

Anyway, I did, in fact find the popup that I needed to bring up, and I did
get the log...   (Clicked on the copy log to clipboard, so hopefully, you
can figure out what this mess is:


<details><summary>Logger output</summary>

```
+3
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/5f7c37eb6a292e3352372975_favicon%2032.png
```
```
+3
||sentry.io^$3p
--
symless.com
3
xhr
https://o372000.ingest.sentry.io/api/5889528/envelope/?sentry_key=fdaa6a6082ee46d9bf717b09cf36a5e9&sentry_version=7
```
```
+2
symless.com
1
xhr
https://api2.prod.symless.com/auth/refresh
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/60d0674a440361e4906084ea_password.svg
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/5fa05a91d65f0e59c2188614_linux-logo.svg
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/5fd8c132a3d647bc2cac10c6_Group%20318.svg
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/5fd8c1329802b3248ac57221_centos.svg
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/5fd8c1320a607e38f7dcc7af_Ubuntu.svg
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/5fd8c1316ae3ae50b0167349_windows.svg
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/5fd8c131da46eb7bb557c520_macOS.svg
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/606c7410050ef840ef88dfb1_Move%20the%20needle.svg
```
```
+2
symless.com
3
image
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/60ec40bfbaaae6589158265f_info_white.svg
```
```
+1
symless.com
3
css
https://fonts.googleapis.com/css?family=Inconsolata:400,700%7CRoboto:regular,500%7CManrope:regular,600,700,800
```
```
+1
symless.com
3
script
https://cdn.jetboost.io/jetboost.js
```
```
+1
googletagmanager_gtm.js
<<
symless.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-W9JX993
```
```
+1
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
symless.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-W9JX993
```
```
+1
||googletagmanager.com^
--
symless.com
3
script
https://www.googletagmanager.com/gtm.js?id=GTM-W9JX993
```
```
+1
/fbevents.js
--
symless.com
3
script
https://connect.facebook.net/en_US/fbevents.js
```
```
+1
symless.com
3
script
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/js/symless-v2.c89b8a242.js
```
```
+1
symless.com
3
script
https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5cb7274cc3cc0c1bc1771305
```
```
+1
symless.com
3
css
https://fonts.googleapis.com/css?family=Inconsolata:400,700%7CRoboto:regular,500%7CManrope:regular,600,700,800
```
```
+0
symless.com
1
script
https://webflow.prod.a.symless.com/downloads.js
```
```
+0
symless.com
1
script
https://website-cdn.symless.com/cookie-consent.js
```
```
+0
symless.com
1
css
https://website-cdn.symless.com/cookie-consent.css
```
```
+0
googletagmanager_gtm.js
<<
symless.com
3
script
https://www.googletagmanager.com/gtag/js?id=UA-10292290-10
```
```
+0
||
googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5
--
symless.com
3
script
https://www.googletagmanager.com/gtag/js?id=UA-10292290-10
```
```
+0
||googletagmanager.com^
--
symless.com
3
script
https://www.googletagmanager.com/gtag/js?id=UA-10292290-10
```
```
+0
symless.com
3
css
https://assets-global.website-files.com/5cb7274cc3cc0c1bc1771305/css/symless-v2.a5e8b87aa.min.css
```
```
+0
||sentry.io^$3p
--
symless.com
3
ping
https://o372000.ingest.sentry.io/api/5889528/envelope/?sentry_key=fdaa6a6082ee46d9bf717b09cf36a5e9&sentry_version=7
```
```
+0
symless.com
1
doc
https://symless.com/synergy/download
```
```
+0
https://symless.com/synergy/download
```
</details>


-------

**Comment by stephenhawk8054** [comment]
Because no one is behind your back and know about your stories or your configurations to understand why you created an issue and how to guide you properly. As you see, this is an extension that users mostly install by themselves (and at least know why they want to install). We cannot know which system installs it by default, and we cannot know the whole stories giving so few of words from the issue.

**Comment by traderhut** [comment]
OK, well, I've DISABLED the extension completely... and I STILL get the
same download with the logo at the top, and a color bar between that and
the footer at the bottom, with (they call it a hamburger, but the 3 lines
at the upper right), where there is a 'download' button which just brings
me back to this page...

There is now way to download the software...

Is it possible to just get a link to the URL that is normally put up on the
screen for the Raspberry Pi? to download the latest software?


-------

**Comment by traderhut** [comment]
Yes, this has NOTHING to do with uBlockOrigin. - so whomever put it into
that queue was in error.   Apparently, there isn't any way to download
currently on a Pi.

I also tried the following:
    1. Selecting the 'Account' tab to login.   It instantly came up showing
my account information, as my being logged in.
    2. Going back to the download page, still empty
    3. Getting the download URL directly from another machine, and going
directly to that download URL (Authorization issue) (which both machines
were logged into the same account)

So, the site itself, is somehow broken, at least, on this version of
Chromium.  Maybe I need a newer version, or maybe I need to download it on
another machine, and make it available another way...


-------

**Comment by mapx-** [comment]
Maybe you should contact their support team
https://symless.com/synergy/contact-support

**Comment by stephenhawk8054** [comment]
You might need to find supports from other communities (raspian... for example) since it's not related to ublock origin now. Or you can check your DNS set up if you are using any blockings with it.
