### ISSUE TITLE
sourceforge.net: breakage

### ISSUE THREAD

**Issue by anzepintar** [uBlockOrigin/uAssets#16158]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sourceforge.net/projects/mpcbe/`

### Category

breakage

### Description

When cosmetic filtering is enabled, scrolling is disabled unless the user has accepted cookies. If I disable cosmetic filtering or accept cookies with uBlock disabled, I am able to use the website normally, even when I have reenabled cosmetic filtering.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 84325
  cosmetic: 82556
  scriptlet: 19984
  html: 888
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42576-93, 8h.54m
    ublock-annoyances: 4831-5, 2d.3h.14m
  default: 
    user-filters: 5-0, never
    ublock-filters: 32395-39, 2d.3h.13m
    ublock-badware: 4246-0, 2d.3h.11m
    ublock-privacy: 301-0, 2d.3h.16m
    ublock-abuse: 77-0, 2d.3h.15m
    ublock-unbreak: 1937-2, 2d.3h.12m
    ublock-quick-fixes: 460-22, 8h.53m
    easylist: 61738-655, 2h.27m
    easyprivacy: 30820-1739, 5d.11h.5m
    urlhaus-1: 7422-0, 1d.19m
    plowe-0: 3670-3, 10d.11h.12m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 29 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 228 ms (selfie)
  maxAssetCacheWait: 225 ms
popupPanel: 
  blocked: 20
  no-cosmetic-filtering: true
  blockedDetails: 
    adnxs.com: 1
    btloader.com: 1
    cloudflareinsights.com: 2
    doubleclick.net: 1
    fsdn.com: 2
    lijit.com: 1
    ml314.com: 1
    pubmatic.com: 2
    rubiconproject.com: 1
    sf-syn.com: 1
    sharethrough.com: 6
    slashdotmedia.com: 1
```
</details>

**Comment by anzepintar** [comment]
Sorry, this is caused by [https://github.com/yourduskquibbles/webannoyances](https://github.com/yourduskquibbles/webannoyances) list. Looks like, I haven't disabled It when I was making a report.

**Comment by mapx-** [comment]
@yourduskquibbles

**Comment by mapx-** [comment]
@anzepintar 

add
`sourceforge.net##body:style(overflow: auto !important;)`

**Comment by anzepintar** [comment]
> @anzepintar
> 
> add `sourceforge.net##body:style(overflow: auto !important;)`

Thank you!

**Comment by krystian3w** [comment]
Cookies can be again blocked by simple network filtering - webmaster fixed glitch with frozen nodes.
