### ISSUE TITLE
sozcu.com.tr: detection

### ISSUE THREAD

**Issue by Kuroiteiken** [uBlockOrigin/uAssets#16152]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sozcu.com.tr/`

### Category

detection

### Description

When i enter site, it detects ublock origin and redirects me to https://www.sozcu.com.tr/reklam-engelleyici and forces me to close ublock to enter site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 90323
  cosmetic: 103626
  scriptlet: 23551
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 4m
    adguard-annoyance: 61762-91, now
    ublock-annoyances: 4809-156, now
  default: 
    user-filters: 0-0, never
    TUR-0: 12365-11, 2d.3h.24m
    easylist: 61549-116, 3d.15h.22m
    easyprivacy: 30908-1264, 14h.25m
    plowe-0: 3672-875, 4d.16h.48m
    ublock-abuse: 77-0, 8d.14h.8m
    ublock-badware: 4045-108, 1h.17m
    ublock-filters: 31605-483, 1h.16m
    ublock-privacy: 254-1, 8d.14h.7m
    ublock-quick-fixes: 454-29, 22h.27m
    ublock-unbreak: 1924-46, 2d.3h.23m
    urlhaus-1: 7422-0, 22h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1197 ms (selfie)
  maxAssetCacheWait: 838 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    sozcu.com.tr: 1
    becdn.net: 1
    cookiepro.com: 2
    doubleclick.net: 1
    gemius.pl: 1
    google-analytics.com: 2
    googletagmanager.com: 2
    ilan.gov.tr: 1
    onesignal.com: 1
    sozcucdn.com: 3
    taboola.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Force update your filter lists
