### ISSUE TITLE
sozcu.com.tr: detection

### ISSUE THREAD

**Issue by myldrm82** [uBlockOrigin/uAssets#16151]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sozcu.com.tr/`

### Category

detection

### Description

There has been no problem so far, it has been detected for the last 2 hours.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-12-28 at 15-17-36 Reklam Engelliyici](https://user-images.githubusercontent.com/121555499/209811119-ea3a36a9-f891-4175-b3fe-ff37da1bed54.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 85736
  cosmetic: 49835
  scriptlet: 21194
  html: 888
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4833-7, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 32398-72, 2d.6h
    ublock-badware: 4246-0, 2d.5h.59m
    ublock-privacy: 302-0, 2d.4h.52m
    ublock-abuse: 77-0, 2d.6h.3m
    ublock-unbreak: 1937-2, 2d.5h.58m
    ublock-quick-fixes: 460-1, 2h.16m
    easylist: 61841-621, 2d.4h.51m
    easyprivacy: 30824-1743, 2d.4h.50m
    urlhaus-1: 7327-0, 2h.15m
    plowe-0: 3672-2, 2d.6h.2m
    TUR-0: 12364-12, 2d.6h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 184 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 637
  blockedDetails: 
    becdn.net: 43
    doubleclick.net: 45
    gemius.pl: 43
    google-analytics.com: 82
    googletagmanager.com: 88
    onesignal.com: 45
    sozcucdn.com: 162
    taboola.com: 129
```
</details>

**Comment by mapx-** [comment]
update `TUR: AdGuard Turkish` and all other lists
