### ISSUE TITLE
btcbitco.in: detection

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#16153]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://btcbitco.in/dashboard`

### Category

detection

### Description

Detection after login

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 110
filterset (summary): 
  network: 85313
  cosmetic: 28415
  scriptlet: 16818
  html: 865
listset (total-discarded, last-updated): 
  default: 
    user-filters: 24-0, never
    ublock-filters: 32509-313, 1d.11h.49m
    ublock-badware: 4245-0, 1d.11h.49m
    ublock-privacy: 304-1, 1d.11h.49m
    ublock-abuse: 77-0, 1d.11h.49m
    ublock-unbreak: 1942-2, 1d.11h.49m
    ublock-quick-fixes: 460-5, 11h.17m
    adguard-mobile: 8404-167, 1d.11h.49m
    easylist: 61848-17829, 1d.11h.49m
    easyprivacy: 30831-1747, 1d.11h.49m
    urlhaus-1: 7327-0, 11h.16m
    plowe-0: 3672-2, 1d.11h.49m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 960 ms (selfie)
  maxAssetCacheWait: 366 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    a-ads.com: 1
    adhitzads.com: 2
    googletagmanager.com: 2
    stimulateartificial.com: 5
    surfe.pro: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
What about `btcbitco.in##+js(acis, window.onload, abb)`? So nothing need to be whitelisted

**Comment by mapx-** [comment]
ok
