### ISSUE TITLE
delta.com: breakage

### ISSUE THREAD

**Issue by lucasec** [uBlockOrigin/uAssets#16161]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.delta.com/`

### Category

breakage

### Description

When UBO is enabled, the alert banner at the top of the page does not layer correctly. The banner is a `div` with classes `alert-advisory-main-container fixed-top advisory-on-load ng-star-inserted`. Without UBO, this banner appears at the very top of the page, with the normal navigation banner below it. With UBO, the navigation banner renders on top of the alert banner, partially obscuring the alert banner.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Broken page:
<img width="1840" alt="Screenshot 2022-12-28 at 8 24 11 PM" src="https://user-images.githubusercontent.com/1920373/209903222-8a762ec3-95ec-4202-b2a7-524d818f5780.png">

Working page (UBO disabled):
<img width="1840" alt="Screenshot 2022-12-28 at 8 28 12 PM" src="https://user-images.githubusercontent.com/1920373/209903489-3dc09742-44c4-496f-ac7a-0fedaaaaef96.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 83701
  cosmetic: 39000
  scriptlet: 16742
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32340-56, 4d.39m
    ublock-badware: 4241-0, 3d.23h.52m
    ublock-privacy: 304-0, 2h.48m
    ublock-abuse: 77-0, 2h.25m
    ublock-unbreak: 1924-2, 3d.23h.35m
    easylist: 61549-601, 4d.2h.26m
    easyprivacy: 30908-1712, 4d.2h.6m
    urlhaus-1: 7374-0, 2h.16m
    plowe-0: 3670-3, 11d.6h.37m
    ublock-quick-fixes: 460-1, 2h.15m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 395 ms (selfie)
  maxAssetCacheWait: 112 ms
popupPanel: 
  blocked: 35
  blockedDetails: 
    delta.com: 12
    bing.com: 2
    c212.net: 1
    criteo.com: 1
    demdex.net: 3
    dotomi.com: 1
    doubleclick.net: 4
    dynatrace-managed.com: 1
    facebook.net: 1
    flashtalking.com: 1
    foresee.com: 1
    go-mpulse.net: 1
    omtrdc.net: 1
    pinterest.com: 1
    t.co: 1
    trackjs.com: 1
    twitter.com: 1
    yahoo.com: 1
```
</details>

**Comment by mapx-** [comment]
Test

```
@@||gateway.foresee.com/sites/delta/production/gateway.min.js$script,domain=delta.com
@@||gateway.foresee.com/code/19.13.0-fs/fs.feedback.js$script,domain=delta.com
```

**Comment by lucasec** [comment]
Not sure if this is what you intended, but I tried adding the above to "my filters". No change in behavior.

**Comment by okiehsch** [comment]
It's a Firefox only issue.
Adding
`@@||delta.com/dlhome/ruxitagentjs$script,1p`
fixes it on my end.
