### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by Irdilavice** [uBlockOrigin/uAssets#16175]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/`

### Category

detection

### Description

After waiting for any download to finish, the download link is replaced with an image stating to remove ad blockers.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_brrF4FOgP9](https://user-images.githubusercontent.com/14914803/210082709-5a4e187f-137d-44fd-a9d3-e6aa962bb639.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 106911
  cosmetic: 39827
  scriptlet: 17232
  html: 850
listset (total-discarded, last-updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-10, 6m
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 6m
    adguard-spyware: 37010-14907, 6m
    block-lan: 44-0, 6m
  default: 
    user-filters: 7-0, never
    ublock-filters: 32344-77, 7m
    ublock-badware: 4272-0, 6m
    ublock-privacy: 304-0, 6m
    ublock-abuse: 77-0, 6m
    ublock-unbreak: 1926-1, 6m
    easylist: 61774-651, 6m
    easyprivacy: 30848-1780, 6m
    urlhaus-1: 7153-0, 6m
    plowe-0: 3669-3, 6m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 35 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 248 ms (selfie)
  maxAssetCacheWait: 130 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    megaup.net: 2
    a-ads.com: 1
    altowriestwispy.com: 1
    bidgear.com: 1
    dmmzkfd82wayn.cloudfront.net: 3
    googletagmanager.com: 1
    keydawnawe.com: 1
    s3.amazonaws.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable the filterlist `uBlock filters – Quick fixes` and test again

**Comment by Irdilavice** [comment]
> Enable the filterlist `uBlock filters – Quick fixes` and test again

I just tried it, and it's still doing the same thing.

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by Irdilavice** [comment]
> * clear cookies / cache for the tested page
> 
>     * reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> 
>     * disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> 
>     * if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
> 
>     * disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> 
>     * restart the system, reopen the browser, test again.

I still have this problem, sadly.
