### ISSUE TITLE
[nsfw] hotpornfile.org: breakage

### ISSUE THREAD

**Issue by is42theanswer** [uBlockOrigin/uAssets#16174]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hotpornfile.org/bjraw-22-12-29-jessica-ryan-xxx-1080p-mp4-nbq/775879`

### Category

breakage

### Description

When uBlock Origin is enabled, Download button is not visible.  Instead, text appears saying, "If the download button does not show up. It has been broken by an adblocker. Please disable it." If uBlock Origin is disabled, clicking on Download button triggers CAPTCHA check, and then Adsearch, which takes you to a search.crowdsearch.net site in which you have to click on top link in order to show download links.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 102
filterset (summary): 
  network: 87374
  cosmetic: 38572
  scriptlet: 16774
  html: 862
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32311-54, 2d.13h.32m
    ublock-badware: 4246-0, 2d.13h.31m
    ublock-privacy: 304-0, 1d.9h.24m
    ublock-abuse: 77-0, 1d.9h.23m
    ublock-unbreak: 1924-2, 2d.13h.30m
    ublock-quick-fixes: 452-0, 13h.22m
    easylist: 64996-608, 4d.13h.41m
    easyprivacy: 30824-1757, 4d.13h.40m
    urlhaus-1: 7363-0, 13h.21m
    plowe-0: 3672-2, 3d.13h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 115 ms (selfie)
  maxAssetCacheWait: 59 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    hotpornfile.org: 4
    commentsengine.com: 1
    googletagmanager.com: 1
    testingmetriksbre.ru: 2
```
</details>

**Comment by ghifarisidiq** [comment]
Hello,

Although the button is showing now, the site is still broken, as shown on the comment [here](https://github.com/uBlockOrigin/uAssets/commit/20f1238c39ff45e17315af334af799feff505ce8#commitcomment-94596650)

After fiddling with the logger, I managed to fix it by disabling this filter

`hotpornfile.org##+js(window.open-defuser)`

From the name I guess this is related to popups. However, I haven't seen any popups yet while browsing the site with this filter disabled , So its doing more harm than good.

**Comment by stephenhawk8054** [comment]
I can click on the download normally and it just opens the captcha

**Comment by ghifarisidiq** [comment]
weird. I have something similar to what was reported [here](https://github.com/uBlockOrigin/uAssets/commit/20f1238c39ff45e17315af334af799feff505ce8#commitcomment-94596650)
Maybe it doesn't show to everyone? I don't know
