### ISSUE TITLE
trustedreviews.com

### ISSUE THREAD

**Issue by skanskan** [uBlockOrigin/uAssets#1617]
Hello

Some web sites don't work. They start loading but at the end refuse to continue loading and casta an error saying maybe it's caused by an adblock.
For example this well-known site:

### Test link (required): 
`http://www.trustedreviews.com/news/sony-xperia-xz-pro-release-date-price-design-specs-leak-3373728`

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/NKSuSxn.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://i.imgur.com/JdeuqJI.png

### Environment (Required): 

Windows 10 X64
Chrome  63.0.3239.132 (Official Build) (64-bit)
uBlock Origin v1.15.2
Nano Defender 13.36

#### Your filter lists (Required): 

Ru Adlist
EasyList Spanish
Peter Lowe’s Ad and tracking server list
Fanboy’s Annoyance List
Malware domains and list
EasyPrivacy
Easylist
Adblock Warning Removal List
uBlock filters

**Comment by okiehsch** [comment]
I can't reproduce your screenshot, but the site uses an ad-reinsertion script, which circumvents adblockers.
````
trustedreviews.com##script:inject(abort-current-inline-script.js, setTimeout, ad-blocker)
````
disables that script on my end, does it also fix your issue?

**Comment by skanskan** [comment]
Yes, it works, thanks.
Is there a generic automatic way to deal with this pages?

**Comment by okiehsch** [comment]
What are the other pages?
There is no "automatic way", uBO simply enforces filters, if there is no filter for a given site there is nothing 
for uBlock to do.

**Comment by gwarser** [comment]
`||lip11t.com^`?
https://old.reddit.com/r/uBlockOrigin/comments/8ut2ey/my_ublock_origin_not_blocking_all_ads_on/

**Comment by okiehsch** [comment]
````
https://old.reddit.com/r/uBlockOrigin/comments/8ut2ey/my_ublock_origin_not_blocking_all_ads_on/
````
is the same issue and https://github.com/uBlockOrigin/uAssets/commit/d81ee14b17eae244f8fa0acb329a425d493d68c7 fixed it.
`lip11t.com` is pulled through the inline-script, blocking, so if you use an updated `uBO` there are no `lip11t.com-requests`.
