### ISSUE TITLE
[NSFW] xrares.com: breakage

### ISSUE THREAD

**Issue by jasch1991** [uBlockOrigin/uAssets#16173]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

can't see video controls, can only pause and resume video by clicking the video

### URL(s) where the issue occurs.

`https://www.xrares.com/video/12556/busty-gf-fucking-in-the-kitchen`
NSFW

### Screenshot(s)

`https://ibb.co/61bh3ZX`

### Notes

disabeling ublock on this site fixed the video controls but without ublock its littered with ads and popups

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 84047
  cosmetic: 38910
  scriptlet: 16722
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61860-44, 8h.19m
    easyprivacy: 30843-1171, 8h.20m
    plowe-0: 3670-901, 12d.15h.11m
    ublock-abuse: 77-0, 23h.56m
    ublock-badware: 4268-111, 8h.18m
    ublock-filters: 31594-113, 8h.17m
    ublock-privacy: 257-1, 23h.55m
    ublock-quick-fixes: 387-17, 23h.53m
    ublock-unbreak: 1915-44, 8h.16m
    urlhaus-1: 7374-0, 23h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4896 ms (selfie)
  maxAssetCacheWait: 2547 ms
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce, all video controls are visible on my end.

**Comment by Yuki2718** [comment]
Me neither.
