### ISSUE TITLE
howifx.com: detection

### ISSUE THREAD

**Issue by quangchieens** [uBlockOrigin/uAssets#16179]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://howifx.com/how-do-i-fix-the-touchscreen-on-my-hp-printer/`

### Category

detection

### Description

for turkdown

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83934
  cosmetic: 38833
  scriptlet: 16774
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61888-44, 4h
    easyprivacy: 30908-1171, 3h.59m
    plowe-0: 3669-870, 3h.58m
    ublock-abuse: 77-0, 3h.56m
    ublock-badware: 4268-110, 3h.54m
    ublock-filters: 31523-131, 3h.53m
    ublock-privacy: 257-1, 3h.52m
    ublock-quick-fixes: 438-18, 3h.51m
    ublock-unbreak: 1913-44, 3h.50m
    urlhaus-1: 7153-0, 3h.48m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 147 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    histats.com: 1
    netpub.media: 4
    push-sdk.net: 1
    tapioni.com: 1
    vlitag.com: 1
```
</details>

**Comment by mapx-** [comment]
provide the first link (shortener link ?)

howifx is already fixed, testing another link:

`https://enit.in/P0ULhF#`

brpught me to another issue, fixed using:
`vavada5com.com##+js(set, adblockDetector, noopFunc)`
