### ISSUE TITLE
animepahe.com: ads

### ISSUE THREAD

**Issue by MingMing0000** [uBlockOrigin/uAssets#16189]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animepahe.com/play/e81c6615-5ead-5220-e786-76234510a6a3/94c6b3aab35d16687595b99ed5e70587639a8c322501c929fe2e6bc4cb9cee30`

### Category

ads

### Description

There's still ads on the website 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 88774
  cosmetic: 28057
  scriptlet: 16760
  html: 869
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32462-301, 19h.40m
    ublock-badware: 4271-0, 13h.48m
    ublock-privacy: 307-1, 13h.44m
    ublock-abuse: 77-0, 13h.43m
    ublock-unbreak: 1932-2, 13h.42m
    ublock-quick-fixes: 398-0, 13h.41m
    adguard-mobile: 8419-167, 19h.41m
    easylist: 64996-17774, 5d.18m
    easyprivacy: 30908-1719, 5d.17m
    urlhaus-1: 7151-0, 13h.40m
    plowe-0: 3672-2, 5d.15m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1401 ms (selfie)
  maxAssetCacheWait: 415 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    citatumpity.com: 1
    cloudflareinsights.com: 2
    stampburpcolored.com: 1
    syenitetatler.tech: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/16187
