### ISSUE TITLE
cnnamador.com [NSFW][ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1618]
URL(s) where the issue occurs

`https://www.cnnamador.com/videos-de-sexo-amador-gozando-dentro-da-safada-cheia-de-tesao/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
block the ad that appears in the video playback?

https://i.imgur.com/R06p6nW.png

**Comment by KiLL4FuNK** [comment]
block the ad that appears in the video playback? @mapx-

https://i.imgur.com/R06p6nW.png

**Comment by mapx-** [comment]
I already asked you to report correctly the issues:

ads, popups, preroll video ads, all tthese details help us and you, ok ?

**Comment by KiLL4FuNK** [comment]
but are you supposed to test the weg before adding the filter?

**Comment by mapx-** [comment]
yes, I can test correctly if you report with all necessary details.

**Comment by KiLL4FuNK** [comment]
Pop-up
