### ISSUE TITLE
[nsfw] txxx.com: nuisance

### ISSUE THREAD

**Issue by 811580** [uBlockOrigin/uAssets#16188]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://txxx.com/`

### Category

nuisance

### Description

hhfggfhghfghfghfghf

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<!- https://i.imgur.com/VB7oQXd.jpeg -->

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 123361
  cosmetic: 144431
  scriptlet: 37014
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
  added: 
    RUS-0: 39356-879, 40m
    adguard-annoyance: 61809-2065, 2d.8h
    adguard-generic: 66977-1119, 2d.8h
    adguard-social: 19625-1947, 2d.8h
    adguard-spyware: 37005-4508, 2d.8h
    adguard-spyware-url: 871-2, 2d.8h
    ublock-annoyances: 4809-191, 2d.8h
  default: 
    user-filters: 21-0, never
    easylist: 61860-17964, 2d.8h
    ublock-abuse: 77-1, 2d.8h
    ublock-badware: 4268-297, 2d.8h
    ublock-filters: 31578-3801, 2d.8h
    ublock-privacy: 257-48, 2d.7h.59m
    ublock-quick-fixes: 438-43, 40m
    ublock-unbreak: 1913-97, 2d.7h.59m
    urlhaus-1: 7151-0, 40m
filterset (user): [array of 21 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  hyperlinkAuditingDisabled: false
  ignoreGenericCosmeticFilters: true
  prefetchingDisabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1920 ms (selfie)
  maxAssetCacheWait: 1434 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    txxx.com: 2
    googletagmanager.com: 2
    realsrv.com: 1
    yandex.ru: 3
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr @Yuki2718 Cookie popup

```adb
txxx.com##.cookie-notify
```

**Comment by Yuki2718** [comment]
AG Cookie already has `##.cookie-notify`.

**Comment by stephenhawk8054** [comment]
@811580 Can you force update the filter lists and test again?

**Comment by Yuki2718** [comment]
Possibly generichide?

**Comment by stephenhawk8054** [comment]
I don't see generichide in the logger and `##.cookie-notify` appears after updating Adguard Annoyances for me

![image](https://user-images.githubusercontent.com/66517106/210159817-a78eba90-dd28-42f0-a22f-f72bc451df75.png)

**Comment by Yuki2718** [comment]
Found the culprit:
> ignoreGenericCosmeticFilters: true

**Comment by Yuki2718** [comment]
`##.cookie-notify` is in the most popular cookie rules and has only 1 exception in AG Cookie, so I'll add `*##.cookie-notify` to our Annoyances list but only for mobile. Those who check ignoreGenericCosmeticFilters should be aware of the result.

**Comment by Yuki2718** [comment]
@gorhill @gwarser Maybe explanation about side effect of the ignoreGenericCosmeticFilters switch is needed on the popup tip?
