### ISSUE TITLE
promo.ladbrokes.com: breakage

### ISSUE THREAD

**Issue by BallerG** [uBlockOrigin/uAssets#16186]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://promo.ladbrokes.com/en/promo/p/free-to-play-games`

### Category

breakage

### Description

Website just 'hangs' when loading with uBlock enabled, but works fine when disabled

![Screenshot 2022-12-31 at 20-31-14 Free To Play Games Promotions Ladbrokes](https://user-images.githubusercontent.com/64506538/210155143-c39d924b-3bcb-4dc8-adda-341cc19aa15e.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83917
  cosmetic: 38705
  scriptlet: 16736
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32349-53, 3h.12m
    ublock-badware: 4272-0, 3h.11m
    ublock-privacy: 304-0, 3h.10m
    ublock-abuse: 77-0, 3h.9m
    ublock-unbreak: 1927-2, 3h.8m
    ublock-quick-fixes: 444-0, 3h.7m
    easylist: 61749-611, 3h.6m
    easyprivacy: 30854-1740, 3h.5m
    urlhaus-1: 7151-0, 3h.4m
    plowe-0: 3669-2, 3h.3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1096 ms (selfie)
  maxAssetCacheWait: 107 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    cloudflare.net: 6
    go-mpulse.net: 2
    quantummetric.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It opens normally for me

![image](https://user-images.githubusercontent.com/66517106/210157883-1253804a-cb61-46f2-b48b-398fc07a2dc0.png)

Are you logging in to the site?

**Comment by BallerG** [comment]
Strange, it seems to be working today. Maybe it was an issue with the site rather than the ad block.
