### ISSUE TITLE
animepahe.ru: popups (again)

### ISSUE THREAD

**Issue by Archilyte** [uBlockOrigin/uAssets#16187]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animepahe.ru/`

### Category

popups

### Description

same issue as #16180, except it is NOT fixed and now it also opens malicious ad websites (such as `operarymishear.store`) when i click anywhere when an episode is running. (either that or I am doing something wrong, but I have never touched Ublock Origin settings...)

### Screenshot(s)

N/A, see #16180

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 83699
  cosmetic: 39047
  scriptlet: 16741
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32347-39, 1d.2h.44m
    ublock-badware: 4272-0, 21h.27m
    ublock-privacy: 304-0, 2d.3h.26m
    ublock-abuse: 77-0, 2d.3h.25m
    ublock-unbreak: 1926-2, 21h.26m
    ublock-quick-fixes: 460-25, 21h.25m
    easylist: 61843-606, 5d.7h.25m
    easyprivacy: 30851-1739, 2h.26m
    urlhaus-1: 7182-0, 21h.24m
    plowe-0: 3671-3, 10d.6h.5m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1115 ms (selfie)
  maxAssetCacheWait: 921 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    citatumpity.com: 1
    cloudflareinsights.com: 4
    stampburpcolored.com: 3
    syenitetatler.tech: 1
```
</details>

**Comment by stephenhawk8054** [comment]
You can continue commenting in old threads, since all of the contributors can still be notified with new comments.

Anyway, have you forced update the filter lists and test again? It was updated a few hours ago and currently I don't see any popups

https://github.com/uBlockOrigin/uAssets/commit/2da9930ccf5816a4c99d55bfd0f8b322ffd2d834

**Comment by Archilyte** [comment]
How do I force update the lists? (Sorry if I appear clueless...)

**Comment by mapx-** [comment]
Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button

**Comment by Archilyte** [comment]
Thank you! It worked!
