### ISSUE TITLE
eu.tamrieltradecentre.com: detection

### ISSUE THREAD

**Issue by EoD** [uBlockOrigin/uAssets#16196]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?ItemNamePattern=Ale`

### Category

detection

### Description

When opening the link with ublock enabled, it states "Please do not block first party ads as they are tracker free, cookie free and script free. Consider switching to another less aggressive adblocker if needed", similar to #16004

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 84895
  cosmetic: 39005
  scriptlet: 16740
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61524-186, never
    easyprivacy: 30820-1176, never
    plowe-0: 3671-904, never
    ublock-abuse: 77-0, never
    ublock-badware: 4232-0, never
    ublock-filters: 31551-132, never
    ublock-privacy: 255-0, never
    ublock-quick-fixes: 458-1, never
    ublock-unbreak: 1922-1, never
    urlhaus-1: 8695-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 718 ms
  maxAssetCacheWait: 4 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    criteo.com: 2
    doubleclick.net: 2
    google-analytics.com: 1
    google.com: 1
    google.de: 1
    googleadservices.com: 1
    googlesyndication.com: 4
    paypalobjects.com: 2
    twitter.com: 1
```
</details>

**Comment by EoD** [comment]
> You didn't.

Would you like a screen recording?

@MasterKia @mapx- I have tested this also in a brand new chrome profile with the same results.

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
