### ISSUE TITLE
[nsfw] hotpornfile.org: breakage

### ISSUE THREAD

**Issue by ghifarisidiq** [uBlockOrigin/uAssets#16197]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hotpornfile.org/brazzersexxtra-23-01-02-suttin-dick-squatter-xxx-2160p-mp4-wrb/776237`

### Category

breakage

### Description

When uBlock Origin is enabled, clicking the download button shows a modal. then, to get the download links, you must click on the "get links" button (you might get a captcha 1st, solve it, then the "get links" appear). Clicking that button shows an alert "Your browser is blocking the loading of a new tab."

With the help of the debugger I narrowed the issue down to the following filter:

`hotpornfile.org##+js(window.open-defuser)`

Since disabling the filter, I havent seen a popup on the site yet. So its (probably) safe to remove

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration
<details>
<summary>Details</summary>

uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 44608
  cosmetic: 38703
  scriptlet: 16747
  html: 864
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 32349-53, now
    ublock-badware: 4277-0, now
    ublock-privacy: 305-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1929-2, now
    ublock-quick-fixes: 445-0, now
    easylist: 61911-254, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1602 ms
  maxAssetCacheWait: 841 ms

</details>

**Comment by stephenhawk8054** [comment]
Please just continue commenting in old threads since all of the contributors can be notified with new comments

https://github.com/uBlockOrigin/uAssets/issues/16174

I still cannot reproduce the issue, after solving the captcha, all the links appear and I can click on them to open in new tab normally.

**Comment by ghifarisidiq** [comment]
Maybe this thing is geo based (cant think of reasonable explanation other than this). Can you please try with a US VPN ?

I didn't know contributors would get notified on closed issues. Sorry for that

**Comment by stephenhawk8054** [comment]
Tks, I can reproduce it when using VPN to US now. Can you test if these filters work?

```adb
hotpornfile.org#@#+js(nowoif)
hotpornfile.org##+js(nowoif, !bergblock)
```

**Comment by ghifarisidiq** [comment]
I updated my filters, and this is working good. Thanks for your help!

**Comment by gwarser** [comment]
With `search.bergfried.tech##+js(window-close-if, /^/)` disabled, a new tab opens with "No configuration available for stated PartnerID and SubID." text only, and then after a minute links appear.

**Comment by stephenhawk8054** [comment]
It was added due to https://github.com/uBlockOrigin/uAssets/issues/17421. I think we need to disable it until another fix comes.
