### ISSUE TITLE
[nsfw] spankbang.com popunder filter => google.com: breakage

### ISSUE THREAD

**Issue by 331212** [uBlockOrigin/uAssets#16194]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.google.com/search?q=Amanda+Rendall+bbc&tbm=isch&ved=2ahUKEwiawdeOmdj5AhX_qlYBHVbZALYQ_AUoAnoECAEQBA&dpr=1.25`

### Category

breakage

### Description

Google.com tab closes when I view or open a `spankbang.com` link in a new tab.

I've been experiencing this issue where I would view or open stuff with a `spankbang.com` link from Google Search/Google Images in a new tab and it would close the current tab (Google) and jump on spankbang.com or just close the current tab if I just viewed stuff with a spankbang.com link and not open them in a new tab.

I've also seen  `encrypted-tbn0.gstatic.com/images` | `encrypted.gstatic.com` tabs close on its own while I was on a different tab, this was back in May before I switched to AdGuard.

This has also happened to me once while I was on Google Search opening spankbang.com links with AdGuard extension enabled.

**My filters on AdGuard extension if they're relevant**
- AdGuard Base filter
- AdGuard Tracking Protection filter
- AdGuard URL Tracking Protection filter
- AdGuard Annoyances filter
- AdGuard Social Media filter
- AdGuard Russian filter

### Screen recordings

<details>
<summary>Screen recordings</summary>

https://drive.google.com/file/d/11Hl_R06P1bYgYStGjpMOZd6fpl12R7Ji/view?usp=sharing, https://drive.google.com/file/d/18epIkCm20qwGXm-ph11n3R1T6qG36os5/view?usp=sharing, https://drive.google.com/file/d/1ueUG4dl1yn_QsyiZSDdAxtbt0Xw8k-XI/view?usp=sharing

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 123361
  cosmetic: 165626
  scriptlet: 37014
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
  added: 
    RUS-0: 39356-11, 12h.51m
    adguard-annoyance: 61809-490, 2d.20h.11m
    adguard-generic: 66977-719, 2d.20h.11m
    adguard-social: 19625-833, 2d.20h.11m
    adguard-spyware: 37005-4492, 2d.20h.11m
    adguard-spyware-url: 871-2, 2d.20h.11m
    ublock-annoyances: 4809-187, 2d.20h.11m
  default: 
    user-filters: 23-0, never
    easylist: 61860-947, 2d.20h.11m
    ublock-abuse: 77-1, 2d.20h.11m
    ublock-badware: 4268-297, 2d.20h.11m
    ublock-filters: 31578-3602, 2d.20h.11m
    ublock-privacy: 257-48, 2d.20h.11m
    ublock-quick-fixes: 438-43, 12h.51m
    ublock-unbreak: 1913-97, 2d.20h.11m
    urlhaus-1: 7151-0, 12h.51m
filterset (user): [array of 23 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1437 ms
  maxAssetCacheWait: 922 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google.com: 3
```
</details>

**Comment by mapx-** [comment]
add

`*$popunder,3p,from=spankbang.com,badfilter`

and test `spankbang` for not blocked popunders

**Comment by 331212** [comment]
Which filter caused it?

**Comment by 331212** [comment]
Is that uBO, AdGuard or Easylist? Thanks.

**Comment by mapx-** [comment]
uBO filters
