### ISSUE TITLE
txstreet.com: ads

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [uBlockOrigin/uAssets#16190]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://txstreet.com/v/eth-btc`

### Category

ads

### Description

small ad for a NFTs and advertising for you to buy ads with them

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/104040739/210159634-404e1172-f931-41a8-a6e6-2eb498f5c962.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 83979
  cosmetic: 38694
  scriptlet: 16737
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32334-55, 1m
    ublock-badware: 4272-0, 1m
    ublock-privacy: 304-0, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1927-2, 1m
    ublock-quick-fixes: 444-0, 1m
    easylist: 61749-610, 1m
    easyprivacy: 30854-1738, 1m
    urlhaus-1: 7217-0, 1m
    plowe-0: 3669-2, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3433 ms
  maxAssetCacheWait: 733 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cloudflareinsights.com: 2
    facebook.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
txstreet.com###zoomer_video
```

@ryanbr
