### ISSUE TITLE
flashx.sx [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1619]
URL(s) where the issue occurs

`https://www.flashx.sx/1d9a183b7b52728cf279837c833be7f9.jsp`

Describe the issue

ADS Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
@mapx-  Anti-Adblock Continue To Video

`https://www.flashx.tv/45zsuubp52kc.html`

**Comment by KiLL4FuNK** [comment]
@mapx- Anti-Adblock Continue To Video

https://www.flashx.tv/45zsuubp52kc.html

**Comment by KiLL4FuNK** [comment]
ADS @mapx-

**Comment by mapx-** [comment]
try
```
flashx.*##script:inject(abort-current-inline-script.js, parseInt, tabunder)
flashx.*##script:inject(abort-on-property-write.js, Fingerprint2)
flashx.*##script:inject(popads-dummy.js)
flashx.*##script:inject(popads.net.js)
flashx.*##script:inject(window.open-defuser.js)
flashx.*##script:inject(nowebrtc.js)
flashx.*##a[href^="https://adsrvmedia.adk2x.com/"]
```

**Comment by KiLL4FuNK** [comment]
It works well @mapx-
