### ISSUE TITLE
southpark.cc.com

### ISSUE THREAD

**Issue by kenwiel** [uBlockOrigin/uAssets#162]
Replace the bracketed [...] placeholders with your own information.
### URL(s) where the issue occurs

`southpark.cc.com`
### Describe the issue

When watching episodes, adds are not blocked
### Versions
- Browser/version: 
  Google Chrome   55.0.2883.9 (Official Build) dev (64-bit)
  Revision    45b55807ff8de03fa7d9057100ae0e3f3861b3ac-refs/branch-heads/2883@{#32}
- uBlock Origin version: 
  uBlock Origin v1.9.10
### Settings

added additional filter lists
### Notes

i would love to provide a url which needs to be blocked, but I do not know how to.

**Comment by gorhill** [comment]
Will let someone else investigate, I can't see episodes from outside the U.S.

**Comment by Atavic** [comment]
I denied connections in the firewall to some IP owned by:
`Level 3 Communications, Inc. (LVLT)`
and the cartoons started with no ads.

**Comment by IDKwhattoputhere** [comment]
@Atavic Take a look into the browser console if there are refused connections.

**Comment by Atavic** [comment]
Nothing there, as I use a firewall and it denied two different IP, both owned by that media group.

**Comment by IDKwhattoputhere** [comment]
Usually the connections blocked by my firewall show up for as refused connections in the console. Maybe you can figure out a working filter with the logger that blocks the same connection your firewall blocked.
My VPN is blocked by Hulu and therefore this site too so I can't help either.

**Comment by lewisje** [comment]
I remember reading that it's nearly impossible to block ads inside the Hulu player without also blocking the content; my own setup does block some of the ads (probably because of my HOSTS file, because the logger doesn't see anything amiss), and instead Hulu plays a 30-second "we couldn't load" filler card.

**Comment by Atavic** [comment]
In full episodes, I got blocked at the end of an act. By stopping the Ad Provider, I got blocked.
In the videos that are a few minutes long I had no problems.

**Comment by mapx-** [comment]
tested (outside the us)
`http://southpark.cc.com/full-episodes/s21e09-super-hard-pcness`

no video ads
