### ISSUE TITLE
imperioscans.com.br: detection

### ISSUE THREAD

**Issue by iKormann** [uBlockOrigin/uAssets#16205]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://imperioscans.com.br/`

### Category

detection

### Description

I can only when I check the option to disable JAVA.
but I can't access anything on the page because I don't load the menus.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 107
filterset (summary): 
  network: 84818
  cosmetic: 41845
  scriptlet: 17014
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/pixeltris/TwitchAdSolutions/master/vaft/vaft-ublock-origin.js: 131-68, now
  default: 
    user-filters: 13-5, never
    easylist: 61199-44, now
    easyprivacy: 30858-1171, now
    plowe-0: 3671-900, now
    spa-1: 4904-68, now
    ublock-abuse: 77-0, now
    ublock-badware: 4219-111, now
    ublock-filters: 31519-151, now
    ublock-privacy: 258-1, now
    ublock-quick-fixes: 438-18, now
    ublock-unbreak: 1913-45, now
    urlhaus-1: 7225-0, now
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 37 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2275 ms (selfie)
  maxAssetCacheWait: 274 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    agkn.com: 1
    disqus.com: 4
    googletagmanager.com: 1
    imrworldwide.com: 1
    narrative.io: 1
    onesignal.com: 1
    pippio.com: 1
    retargetly.com: 1
    rezync.com: 1
    viglink.com: 2
    wp.com: 1
```
</details>

**Comment by u-RraaLL** [comment]
> [✓] I did not answer truthfully to ALL the above checkpoints.

So maybe now follow the steps for real, because I don't get any detection.
