### ISSUE TITLE
clubmonaco.com: annoyance ?

### ISSUE THREAD

**Issue by Starffirre** [uBlockOrigin/uAssets#16202]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

floating banner is shown on the site

### URL(s) where the issue occurs.

`https://www.clubmonaco.com/`

### Screenshot(s)

![before-3](https://user-images.githubusercontent.com/121527177/209744475-e65dea26-1c24-4761-88c4-ca72cf79ddad.jpg)
![before-1](https://user-images.githubusercontent.com/121527177/209744049-97c5730b-8231-474a-b7cb-620626b9fb4c.jpg)

### uBO version

1.45.2

### Browser name and version

Chrome 108.0.5359.124

### Settings

Default

**Comment by u-RraaLL** [comment]
Looks to me like something for EL/Fanboy's Annoyance.

Your filters aren't extended syntax so it shouldn't be addressed by uAssest. And no, the popup exception doesn't apply - this is an overlay, not a popup (opens a new window).

**Comment by mapx-** [comment]
You should report at easylist repository, I'm not even sure it's an annoyance

@ryanbr

**Comment by krystian3w** [comment]
EL will not adress: https://github.com/easylist/easylist/issues/14551#issuecomment-1368862849

![image](https://user-images.githubusercontent.com/35370833/210323937-5ef57ca0-8ded-4d36-bdd7-b26edb59af06.png)

If element are sticky/floating then IMO is anoying.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/14551#issuecomment-1368862849
