### ISSUE TITLE
mdn.lol: breakage

### ISSUE THREAD

**Issue by blader-render** [uBlockOrigin/uAssets#16207]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

[`https://mdn.lol/`]
that's url start from this link `https://clks.pro/OWmgpc5supk`

### Category

breakage

### Description

cannot see timer if enable adblock becouse must be click some ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83374
  cosmetic: 38762
  scriptlet: 16779
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 52-24, never
    easylist: 61309-45, 18m
    easyprivacy: 30866-1171, 17m
    plowe-0: 3671-900, 17m
    ublock-abuse: 77-0, 17m
    ublock-badware: 4219-111, 17m
    ublock-filters: 31576-123, 17m
    ublock-privacy: 258-1, 17m
    ublock-quick-fixes: 438-18, 17m
    ublock-unbreak: 1914-44, 17m
    urlhaus-1: 7137-0, 17m
filterset (user): [array of 35 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2564 ms
  maxAssetCacheWait: 1083 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    bambarmedia.com: 3
    bannertrack.net: 1
    clickiocdn.com: 2
    d3u598arehftfk.cloudfront.net: 1
    doubleclick.net: 1
    googletagmanager.com: 2
```
</details>

**Comment by krystian3w** [comment]
Maybe site issue.

**Comment by blader-render** [comment]
> Maybe site issue.

he update the site, different from the look of the previous site

**Comment by blader-render** [comment]
step 1 until step 2 its ok, but step 3 until finish breakage

**Comment by krystian3w** [comment]
In my Chrome 108 with uBo dev I can't end first step:

- sometimes don't appear Google recaptcha
- sometimes don't appear Google recaptcha and buttons "0 of 4 steps" (big blank white gap)

**Comment by blader-render** [comment]
> https://clks.pro/OWmgpc5supk

in firefox android, issue with screen
mdn.lol/screen.html

**Comment by blader-render** [comment]
> I Can Reproduce On FireFox Android Only

in firefox android, issue with screen
mdn.lol/screen.html

**Comment by mapx-** [comment]
@blader-render 

add
`||mdn.lol^$csp=style-src *`

then keep clicking `step`

**Comment by blader-render** [comment]
> @blader-render
> 
> add `||mdn.lol^$csp=style-src *`
> 
> then keep clicking `step`

working bro. thanks

**Comment by mapx-** [comment]
Test

```
@@||holid.io^$script,domain=mdn.lol
mdn.lol##+js(nostif, /^/)
mdn.lol##+js(aopr, pbjs)
@@||clickiocdn.com^$script,domain=mdn.lol
||hbagency.it^
```

**Comment by blader-render** [comment]
> 
Same condition, not show the site "blank"

**Comment by mapx-** [comment]
Are you using android now ?

**Comment by blader-render** [comment]
> Are you using android now ?

Yes, also I try in my laptop. Same condition

**Comment by blader-render** [comment]
Oh I see, working bro. I remove checklist easylist

**Comment by mapx-** [comment]
No, don't remove it, update it, see if works

**Comment by blader-render** [comment]
> No, don't remove it, update it, see if works

Not work if not remove easylist

**Comment by mapx-** [comment]
add also and test again

`@@||cdn.unblockia.com^$script,domain=mdn.lol`

**Comment by blader-render** [comment]
> 

Ok, this is work. Great.

**Comment by garry-ut99** [comment]
> mapx- : https://github.com/uBlockOrigin/uAssets/issues/16207#issuecomment-1369689243 : add `||mdn.lol^$csp=style-src *`

<br>

This filter breaks the stylesheet/look of the mainpage:


<details>
<summary>SCREENSHOOT 1 (BROKEN)</summary>



![1](https://user-images.githubusercontent.com/72945564/212415311-d278854f-afd8-4b89-89e4-b86d9a17e48e.png)

</details>

<br>

As a proof it gets fixed with: `||mdn.lol^$csp=style-src *,badfilter`

<details>
<summary>SCREENSHOOT 2 (FIXED)</summary>

![2](https://user-images.githubusercontent.com/72945564/212415325-b3d28f35-bb0f-4eda-9417-c92b9acb29bb.png)

</details>

**Comment by mapx-** [comment]
fake content, if you remove that filter the shortener link does not work, test the original link
`https://clks.pro/OWmgpc5supk`

**Comment by garry-ut99** [comment]
One more thing, not sure whether it is an issue or not (fake): on Firefox, a Cookie/Privacy notification is missing.

- after adding `||mdn.lol^$csp=style-src *,badfilter` the notification does appear and Agree/Close privacy button does work (clicking it closes the notification as expected):

screenshoot 3 : https://user-images.githubusercontent.com/72945564/212428762-b3a78652-844e-41d4-80f3-3a1633e5d557.png

- but Manage Options button still broken, after clicking it, a white circle rotates endlessly:

screenshoot 4: https://user-images.githubusercontent.com/72945564/212428888-184dbb61-0411-4c02-b381-bac0c39fe438.png

- haven't been investigating further which filters break the Manage Option button,  but after disabling 'ublock filtes', it gets fixed - Manage Options button does work:

screenshoot 5: https://user-images.githubusercontent.com/72945564/212429497-3cee0e32-3983-4796-b065-ece4d88bb99a.png

**Comment by krystian3w** [comment]
If this is not fake block with AI/SI content.

**Comment by blader-render** [comment]
> fake content, if you remove that filter the shortener link does not work, test the original link `https://clks.pro/OWmgpc5supk`

@mapx- 
Today this site detection adblock again😂, please fix it again thanks
![az_recorder_20230115_150450](https://user-images.githubusercontent.com/120096290/212529672-e49aef80-9c10-4dfc-b450-7c9de87025d2.jpg)

**Comment by ghajini** [comment]
what type of breakage?
can you post link or provide steps to reproduce?

**Comment by blader-render** [comment]
> what type of breakage? can you post link or provide steps to reproduce?

![az_recorder_20230118_001054](https://user-images.githubusercontent.com/120096290/212965959-da5df07a-10ac-4ca7-ad8d-76dca1e94afb.jpg)
Stuck in there
You can try original link https://clks.pro/OWmgpc5supk

**Comment by stephenhawk8054** [comment]
I cannot reproduce the issue

![https://i.imgur.com/RzSm0Rt.png](https://i.imgur.com/RzSm0Rt.png)

**Comment by ghajini** [comment]
which browser is that? can you disable its own adblock if any?

**Comment by blader-render** [comment]
> I cannot reproduce the issue
> 
> ![https://i.imgur.com/RzSm0Rt.png](https://camo.githubusercontent.com/4df45e409960967bf2f19ffbc848e60eaccb7a962145d5194fe21e8bfc7fe427/68747470733a2f2f692e696d6775722e636f6d2f527a536d3052742e706e67)

In Firefox working, in lemur browser & yandex breakage, what I should do?

**Comment by garry-ut99** [comment]
- I can reproduce the breakage on Firefox Mobile, but not on Opera Mobile
- in Firefox Mobile I can reproduce even with uBO disabled
- better to post links to screenshoots instead of screenshoots, otherwise this thread gonna be unreadable
- anyway the whole `mdn.lol` issue, regardless of whether it's an anti-adblock or a breakege, is really insane (it's randomness)

**Comment by krystian3w** [comment]
What Opera Mobile added support MV2 WebExtensions...

**Comment by krystian3w** [comment]
> in lemur browser & yandex breakage, what I should do?

The best not open in both that site if no possible reproduce in PC Chrome version.

**Comment by garry-ut99** [comment]
I use Mobile Site View:
- https://firefox-source-docs.mozilla.org/devtools-user/responsive_design_mode/
- https://browserhow.com/how-to-load-mobile-site-view-on-opera-computer/

**Comment by stephenhawk8054** [comment]
Chromium mobile browser is not supported yet, so I don't think we can address it. I can't even use custom filter on lemur browser.

**Comment by garry-ut99** [comment]
https://browserhow.com/installing-extensions-on-android-chromium-browser-experimental/

**Comment by stephenhawk8054** [comment]
Kiwi, yandex... can install extension by modifying their own ways with chromium source code. But as it's not officially supported by chromium and there are no documentations, debugger... to work with, it's difficult to address these issues.

**Comment by krystian3w** [comment]
IMO Chromium dropped implement API to run WebExtensions.

**Comment by lkzlk** [comment]
L Adblocker

**Comment by garry-ut99** [comment]
> krystian3w :
> > lkzlk : [#16207 (comment)](https://github.com/uBlockOrigin/uAssets/issues/16207#issuecomment-1385992120): L Adblocker
> 
> You speak in Italian/French? due:

Or not, and probably he just saw this anti-adblock text: https://user-images.githubusercontent.com/72945564/213035663-c58721bd-03cd-40b2-a90a-5f5e7f45345f.png and he wrongly was thinking it's still not fixed, thus he reported it.

<hr>


By the way: 
- `clks.pro/OWmgpc5supk` died: `404 Not Found Error: The requested address '/OWmgpc5supk' was not found on this server.`
- `clks.pro/Ojot` still working

**Comment by blader-render** [comment]
> 

Invalid

**Comment by stephenhawk8054** [comment]
The `My filters` page does not get stuck for me. It's just it does not use the custom filter I add in it.

**Comment by blader-render** [comment]
@mapx- @stephenhawk8054 
for this issue, now he change site (domain).can fix for this? thanks

**Comment by blader-render** [comment]
> if you do not provide a working starting link we cannot investigate

Still same link, but ok this original link
http://clks.pro/sf2kd5ia

**Comment by mapx-** [comment]
I get the same domain `mdn.lol` but with this message:
`Sorry, This Page Is Moved To The Main Page https://mdn.lol/`

**Comment by stephenhawk8054** [comment]
I get this message

Screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/214190457-f8cc69c1-af85-4472-8af1-91be0505086c.png)

</details>

**Comment by blader-render** [comment]
@mapx- @stephenhawk8054 
now in step 2 detection adblock
![image](https://user-images.githubusercontent.com/120096290/215765526-1caff475-51d8-4f81-b671-4316adf306ab.png)

**Comment by garry-ut99** [comment]
> blader-render : now in step 2 detection adblock
- I can reproduce
- wrong issue, should here: https://github.com/uBlockOrigin/uAssets/issues/16345
- too big screenshoot again, you ignored what has been asked in https://github.com/uBlockOrigin/uAssets/issues/16207#issuecomment-1385785585

> better to post links to screenshoots instead of screenshoots, otherwise this thread gonna be unreadable

this would be sufficient (example):
![yyyyy](https://user-images.githubusercontent.com/72945564/215785155-708621fb-c055-43a2-8398-0a64f68f567d.png)

**Comment by blader-render** [comment]
> > blader-render : now in step 2 detection adblock
> 
> * I can reproduce
> * wrong issue, should here: [mdn.lol: detection #16345](https://github.com/uBlockOrigin/uAssets/issues/16345)
> * too big screenshoot again, you ignored what has been asked in [mdn.lol: breakage #16207 (comment)](https://github.com/uBlockOrigin/uAssets/issues/16207#issuecomment-1385785585)
> 
> > better to post links to screenshoots instead of screenshoots, otherwise this thread gonna be unreadable
> 
> who needs all the useless white space, this would be sufficient (example): ![yyyyy](https://user-images.githubusercontent.com/72945564/215785155-708621fb-c055-43a2-8398-0a64f68f567d.png)

- wrong issue, should here: https://github.com/uBlockOrigin/uAssets/issues/16345 (i not understand )
- too big screenshoot again, you ignored what has been asked in ( sorry, I screenshot directly from the PC. and I just opened this page. once again, I am sorry. didn't mean to ignore. )
-
