### ISSUE TITLE
[nsfw] bra.barlear.ru: ads

### ISSUE THREAD

**Issue by RutD0g** [uBlockOrigin/uAssets#16209]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bra.barlear.ru/?u=dmzpte4&o=v49g540&t=dt&cid=dtc|Q2xhaXJlIGV2YW5zIDR0aCB2aXNpdDsgcG9wdW5kZXI9MQ`

### Category

ads

### Description

Ad, nsfw

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 89402
  cosmetic: 27941
  scriptlet: 16653
  html: 849
listset (total-discarded, last-updated): 
  added: 
    https://www.topcashback.co.uk/misc/AdBlockWhiteList.aspx: 4722-0, 2d.4m
  default: 
    user-filters: 55-0, never
    ublock-filters: 32417-264, 19m
    ublock-badware: 4271-0, 2d.14h.11m
    ublock-privacy: 304-1, 6d.3h.57m
    ublock-abuse: 77-0, 6d.3h.56m
    ublock-unbreak: 1931-1, 3d.1h.34m
    adguard-mobile: 8427-167, 18m
    easylist: 61199-17856, 3h.37m
    easyprivacy: 30837-1749, 5d.12h.10m
    urlhaus-1: 7137-0, 3h.36m
    plowe-0: 3672-2, 10d.11h.36m
filterset (user): [array of 56 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1065 ms (selfie)
  maxAssetCacheWait: 381 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
- is `bra.barlear.ru`  page the ad you want to block ?
- what other page did you visit to get `bra.barlear.ru` ad (as popup ?) ?
