### ISSUE TITLE
banking.postbank.de: breakage

### ISSUE THREAD

**Issue by ghulmarduk** [uBlockOrigin/uAssets#16200]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://banking.postbank.de/`

### Category

breakage

### Description

Page won´t load. That´s it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![postbank](https://user-images.githubusercontent.com/89010058/210246639-01579cac-20a2-409a-8267-8a67c01d0986.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 85997
  cosmetic: 42736
  scriptlet: 16740
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6077-0, 6h.28m
    easylist: 61738-48, 5d.57m
    easyprivacy: 30908-1182, 5d.56m
    plowe-0: 3671-874, 11d.1h.41m
    ublock-abuse: 77-0, 2d.1h.29m
    ublock-badware: 4268-111, 2d.1h.27m
    ublock-filters: 31543-124, 2d.1h.26m
    ublock-privacy: 257-1, 2d.1h.28m
    ublock-quick-fixes: 439-18, 2h.27m
    ublock-unbreak: 1913-45, 2d.1h.25m
    urlhaus-1: 7152-0, 6h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1867 ms
  maxAssetCacheWait: 1172 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    nr-data.net: 1
    usercentrics.eu: 1
```
</details>

**Comment by okiehsch** [comment]
> Page won´t load. That´s it.

![image](https://user-images.githubusercontent.com/16838044/210250725-ab936cfe-86e9-4a26-ba39-cbe36057cfb5.png)
