### ISSUE TITLE
wrzesnia.info.pl: detection

### ISSUE THREAD

**Issue by pawelslowinski** [uBlockOrigin/uAssets#16206]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wrzesnia.info.pl/pl/19_wiadomosci-z-regionu/635_wrzesnia/21158_wspolnota-zdrowia-klub-36-minut-wrzesnia-zaprasza-do-lepszego-zycia.html`

### Category

detection

### Description

detect ublock and hide article

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 88693
  cosmetic: 46111
  scriptlet: 16946
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    POL-0: 7879-8, 27m
    POL-2: 1276-13, 1d.3h
    easylist: 64996-78, 30m
    easyprivacy: 30850-1171, 29m
    plowe-0: 3671-907, 12d.14h.51m
    ublock-abuse: 77-0, 31m
    ublock-badware: 4268-112, 3d.10h.58m
    ublock-filters: 31559-145, 2d.8h.32m
    ublock-privacy: 257-1, 32m
    ublock-quick-fixes: 438-15, 26m
    ublock-unbreak: 1915-45, 3d.10h.59m
    urlhaus-1: 7225-0, 28m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2617 ms
  maxAssetCacheWait: 1534 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    wrzesnia.info.pl: 1
    doubleclick.net: 1
    dqst.pl: 3
    googletagmanager.com: 1
    googletagservices.com: 1
    powerad.ai: 1
    s-onetag.com: 1
    taboola.com: 1
    yieldbird.com: 1
```
</details>

**Comment by u-RraaLL** [comment]
Shouldn't this be addressed in the POL anti-adblock list?

Or have the maintainers given up? Last update in June, it seems.

Does uBO keep inactive regional lists indefinitely?

**Comment by mapx-** [comment]
I guess those lists are still useful for specific polish ads / issues

**Comment by krystian3w** [comment]
Or his village is cut off from electricity and Internet for a good next few months.
