### ISSUE TITLE
youjizz.com: breakage

### ISSUE THREAD

**Issue by SatanNintendo** [uBlockOrigin/uAssets#16201]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youjizz.com/`

### Category

breakage

### Description

The preview of the video is not displayed (storyboard scenes of the video).
It seemed to work fine before.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 100
filterset (summary): 
  network: 101201
  cosmetic: 59532
  scriptlet: 17938
  html: 868
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32335-55, 20h.59m
    ublock-badware: 4272-0, 20h.58m
    ublock-privacy: 307-0, 9d.5h.57m
    ublock-abuse: 77-0, 9d.5h.56m
    ublock-unbreak: 1927-2, 20h.57m
    ublock-quick-fixes: 444-0, 1d.1h.1m
    easylist: 61749-625, 1d.1h.4m
    easyprivacy: 30850-1737, 1d.1h.3m
    urlhaus-1: 7297-0, 1d.1h
    plowe-0: 3672-2, 6d.19h.36m
    RUS-0: 39370-158, 1d.1h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 214 ms (selfie)
  maxAssetCacheWait: 119 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    youjizz.com: 1
    exosrv.com: 1
    google-analytics.com: 1
    realsrv.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`youjizz.com#@#video[autoplay]`

@ryanbr

**Comment by SatanNintendo** [comment]
> 

Thanks a lot, I added it, and now it's working!
