### ISSUE TITLE
exeo.app: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#16217]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://exeo.app/qxEq3N`

### Category

detection

### Description

Adblocker detected...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/75168867/210499659-2371f5a6-677f-488c-b514-41920ab34b79.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 87069
  cosmetic: 38632
  scriptlet: 16739
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3974-1, never
    easylist: 64996-67, 3d.15h.43m
    easyprivacy: 30854-1172, 3d.15h.42m
    plowe-0: 3669-896, 2d.20h
    ublock-abuse: 77-0, 4d.15h.16m
    ublock-badware: 4045-109, 3d.15h.41m
    ublock-filters: 31543-4067, 3d.15h.40m
    ublock-privacy: 257-1, 4d.15h.15m
    ublock-quick-fixes: 438-14, 35m
    ublock-unbreak: 1914-44, 3d.15h.39m
    urlhaus-1: 7211-0, 34m
filterset (user): [array of 3044 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4549 ms (selfie)
  maxAssetCacheWait: 3374 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    demand.supply: 1
    exe.io: 1
    googletagmanager.com: 1
    wimplesbooklet.com: 1
```
</details>

**Comment by l-eber-a-c-87** [comment]
Same problem, site is asking to disable adblocking
