### ISSUE TITLE
nbc.com: breakage

### ISSUE THREAD

**Issue by jjcole09** [uBlockOrigin/uAssets#16216]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nbc.com/the-tonight-show/video/regina-hall-f-murray-abraham-edvin-ryding-and-omar-rudberg-andrea-matteo-and-virginia-bocelli/9000156382`

### Category

breakage

### Description

Playback for videos is unavailable on the website when the extension is enabled on Firefox. It gives an error stating, "error occurred with HLS" is there any way we can resolve this issue? Any assistance would be greatly appreciated. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1440" alt="Screenshot 2023-01-03 at 9 57 40 PM" src="https://user-images.githubusercontent.com/121923561/210493680-b205b3d0-8f7d-4d30-b2e1-641ebc134337.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 102
filterset (summary): 
  network: 52157
  cosmetic: 9408
  scriptlet: 16762
  html: 864
listset (total-discarded, last-updated): 
  removed: 
    easylist: null
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 23h.58m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32369-54, 53m
    ublock-badware: 4228-0, 1h.17m
    ublock-privacy: 305-0, 1h.15m
    ublock-abuse: 77-0, 1h.14m
    ublock-unbreak: 1927-2, 1h.6m
    ublock-quick-fixes: 444-0, 1h.5m
    easyprivacy: 30873-1738, 1h.4m
    urlhaus-1: 7211-0, 1h.3m
    plowe-0: 3671-2, 1h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 925 ms
  maxAssetCacheWait: 324 ms
popupPanel: 
  blocked: 71
  blockedDetails: 
    nbc.com: 23
    adobedtm.com: 4
    amplitude.com: 1
    app.link: 4
    branch.io: 5
    browser-intake-datadoghq.com: 12
    conviva.com: 2
    doubleclick.net: 1
    go-mpulse.net: 1
    googleadservices.com: 1
    googletagmanager.com: 4
    imrworldwide.com: 2
    launchdarkly.com: 2
    moatads.com: 1
    nbcuni.com: 1
    nervoussummer.com: 1
    scorecardresearch.com: 4
    stickyadstv.com: 2
```
</details>

**Comment by jjcole09** [comment]
@mapx- Thanks for resolving this issue. However, I am still receiving ads in between the videos. Can that be fixed?

**Comment by mapx-** [comment]
The filter commented in my commit was originally created to remove ads, obviously now they have fought back

**Comment by mapx-** [comment]
Test

`player.theplatform.com##+js(m3u-prune, tvessaiprod.nbcuni.com, /theplatform\.com\/.*?\.m3u8/)`

You will notice that the ad countdown is still visible, but the ad is blocked / skipped

**Comment by jjcole09** [comment]
@mapx- Awesome! Thank you soooo much! I really appreciate the assistance! ❤️ ☺️
