### ISSUE TITLE
rte.ie: ads

### ISSUE THREAD

**Issue by computerfan0** [uBlockOrigin/uAssets#16226]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.rte.ie/archives/2021/0113/1189480-demolition-failure/`

### Category

ads

### Description

When I try to watch the video embedded in this page, ads still display. These are 20 second unskippable videos.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[](https://ibb.co/0mvhKtd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 83744
  cosmetic: 38895
  scriptlet: 16743
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 32302-51, 2d.1h.24m
    ublock-badware: 4223-0, 2d.1h.23m
    ublock-privacy: 304-0, 2d.1h.26m
    ublock-abuse: 77-0, 2d.1h.25m
    ublock-unbreak: 1929-2, 2d.1h.12m
    ublock-quick-fixes: 450-0, 9h.20m
    easylist: 61798-606, 6d.1h.36m
    easyprivacy: 30847-1740, 6d.1h.35m
    urlhaus-1: 7211-0, 9h.19m
    plowe-0: 3671-2, 2d.10m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1006 ms (selfie)
  maxAssetCacheWait: 104 ms
popupPanel: 
  blocked: 31
  blockedDetails: 
    rte.ie: 2
    2mdn.net: 1
    ati-host.net: 4
    bluebillywig.com: 2
    cookielaw.org: 3
    doubleclick.net: 6
    ebu.io: 1
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 3
    googletagservices.com: 1
    gstatic.com: 4
    myfonts.net: 1
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce the ads, trying using an IE vpn too

**Comment by mapx-** [comment]
Test

`*/media/*.mp4|$media,domain=rte.ie,redirect=noopmp3-0.1s`
