### ISSUE TITLE
animedao.to: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#16225]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animedao.to/view/6950693798/`

### Category

[unknown]

### Description

Lines above and below video player need to be removed as it is an advertisement remnant and show cover art needs to be brought back up to be next to the video player. Line remnants circled and art that needs to be moved up is also circled. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1016" alt="Screenshot 2023-01-04 130157" src="https://user-images.githubusercontent.com/69532417/210649724-3e5b17a4-2b75-479d-9b71-a661a8a774c1.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 155674
  cosmetic: 205394
  scriptlet: 37397
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62071-89, 1m
    adguard-generic: 67023-518, 1m
    adguard-mobile: 8430-44, 1m
    adguard-spyware: 36621-4107, 1m
    adguard-spyware-url: 871-2, 1m
    block-lan: 44-0, 1m
    curben-phishing: 20659-0, 1m
    curben-pup: 187-0, 1m
    fanboy-annoyance: 84647-4153, 1m
    fanboy-cookiemonster: 44491-44491, 1m
    ublock-annoyances: 4707-241, 1m
  default: 
    user-filters: 0-0, never
    easylist: 61466-1155, 1m
    easyprivacy: 30878-12399, 1m
    plowe-0: 3671-1068, 1m
    ublock-abuse: 77-0, 1m
    ublock-badware: 4239-306, 1m
    ublock-filters: 31583-3859, 1m
    ublock-privacy: 258-54, 1m
    ublock-quick-fixes: 447-44, 1m
    ublock-unbreak: 1914-109, 1m
    urlhaus-1: 7152-1, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 552 ms (selfie)
  maxAssetCacheWait: 510 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    bidgear.com: 3
```
</details>

**Comment by u-RraaLL** [comment]
You should've just replied in your previous issue.

> art that needs to be moved up is also circled.

That's impossible. The website is divided into rows. The "art" and the comments are i the same row. One below the player.

**Comment by mapx-** [comment]
No such lines on my end

**Comment by jimmysofat6864** [comment]
I still see the lines even after purging cache in both firefox and chrome.

**Comment by mapx-** [comment]
try following these indications:

- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by u-RraaLL** [comment]
> No such lines on my end

I can see them on my end.

A simple `animedao.to##hr` will take care of them.

**Comment by jimmysofat6864** [comment]
@mapx- Those steps didn't work but what @u-RraaLL suggested worked.
