### ISSUE TITLE
spcs.pro: ads

### ISSUE THREAD

**Issue by lao-mang** [uBlockOrigin/uAssets#16220]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://spcs.pro/`

### Category

ads

### Description

не работает. no work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 101008
  cosmetic: 59723
  scriptlet: 17982
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 7-0, never
    RUS-0: 39566-11, 22h.47m
    easylist: 61750-57, 3d.18h.36m
    easyprivacy: 30848-1281, 3d.18h.35m
    plowe-0: 3672-904, 9d.1h.6m
    ublock-abuse: 77-1, 22h.49m
    ublock-badware: 4273-111, 1d.21h.21m
    ublock-filters: 31523-165, 1d.21h.20m
    ublock-privacy: 258-1, 22h.48m
    ublock-quick-fixes: 444-18, 13m
    ublock-unbreak: 1916-44, 1d.21h.19m
    urlhaus-1: 7152-0, 12m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8272 ms (selfie)
  maxAssetCacheWait: 3052 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    googletagmanager.com: 1
    spac.me: 1
    yadro.ru: 22
```
</details>

**Comment by mapx-** [comment]
@lao-mang provide a screenshot with the ads and eventually the specific page where the ads appear on your side

follow these indications too:

- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
