### ISSUE TITLE
espn.com: nuisance

### ISSUE THREAD

**Issue by DangerousNights** [uBlockOrigin/uAssets#16227]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.espn.com/nfl/story/_/id/35377747/damar-hamlin-showed-signs-overnight-progress-friend-says`

### Category

nuisance

### Description

Autoplay media that blocks context menu

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[right_click_menu](https://user-images.githubusercontent.com/38265370/210657911-f1327469-2904-4dd4-a5d4-750d1a59fd5f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 84011
  cosmetic: 38779
  scriptlet: 16757
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 56-3, never
    ublock-filters: 32359-54, 1d.6h.31m
    ublock-badware: 4224-0, 1d.6h.30m
    ublock-privacy: 304-0, 3d.22h.39m
    ublock-abuse: 77-0, 3d.22h.38m
    ublock-unbreak: 1929-1, 1d.6h.29m
    easylist: 61836-615, 3d.6h.37m
    easyprivacy: 30850-1738, 3d.6h.36m
    urlhaus-1: 7234-0, 1d.2h.27m
    plowe-0: 3673-2, 6d.16h.20m
    ublock-quick-fixes: 450-1, 1d.2h.28m
filterset (user): [array of 56 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1549 ms (selfie)
  maxAssetCacheWait: 1126 ms
popupPanel: 
  blocked: 65
  no-cosmetic-filtering: true
  no-large-media: true
  blockedDetails: 
    espn.com: 3
    bkrtx.com: 1
    bluekai.com: 1
    brightcove.com: 8
    chartbeat.com: 1
    chartbeat.net: 3
    conviva.com: 1
    demdex.net: 4
    espncdn.com: 5
    go.com: 1
    googletagservices.com: 1
    imrworldwide.com: 1
    omtrdc.net: 29
    rubiconproject.com: 1
    scorecardresearch.com: 5
```
</details>

**Comment by mapx-** [comment]
You are using firefox, use the browser settings to stop autoplay for ALL pages or only for the wanted ones

![image](https://user-images.githubusercontent.com/10303732/210663504-539e7cf6-55d8-4e55-8344-dd166014f5e3.png)

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances` list

**Comment by DangerousNights** [comment]
> You are using firefox, use the browser settings to stop autoplay for ALL pages or only for the wanted ones
> 
> ![image](https://user-images.githubusercontent.com/10303732/210663504-539e7cf6-55d8-4e55-8344-dd166014f5e3.png)

The reason I reported the site is because I have that setting set as block all

![image](https://user-images.githubusercontent.com/38265370/210869077-6c013367-79ca-414a-af06-2b6ea813d38f.png)
