### ISSUE TITLE
studyflix.de: nuisance

### ISSUE THREAD

**Issue by CrazyTim71** [uBlockOrigin/uAssets#16224]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://studyflix.de/informatik/flipflop-schaltungen-995`

### Category

nuisance

### Description

When clicking on a video, the website always shows an popup to create an account. It can be closed by clicking on "Später anmelden" (marked red).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_5](https://user-images.githubusercontent.com/118295691/210617316-d938b95d-346e-447b-b595-fc43167b7b32.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 85652
  cosmetic: 42610
  scriptlet: 16757
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32350-65, 1d.15h.14m
    ublock-badware: 4223-0, 1d.15h.15m
    ublock-privacy: 304-0, 5d.5h
    ublock-abuse: 77-0, 5d.5h.1m
    ublock-unbreak: 1927-2, 1d.1h.29m
    easylist: 61312-625, 1h.24m
    easyprivacy: 30868-1747, 1h.25m
    urlhaus-1: 7234-0, 20h.37m
    plowe-0: 3669-2, 4d.9m
    DEU-0: 6077-2, 20h.38m
    ublock-quick-fixes: 452-0, 20h.36m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 169 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 112
  blockedDetails: 
    studyflix.de: 7
    2mdn.net: 12
    amplitude.com: 5
    doubleclick.net: 26
    google-analytics.com: 45
    google.com: 5
    googlesyndication.com: 12
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances` list

**Comment by CrazyTim71** [comment]
Seems to work. Thanks.
