### ISSUE TITLE
apkpure.com [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1622]
URL(s) where the issue occurs

`https://apkpure.com/pocket-monster-remake/yoyo.Easy2play.now`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
advertising on the side and advertising when you put to download

**Comment by okiehsch** [comment]
`||promopure.com^$domain=apkpure.com`

**Comment by SMed79** [comment]
```
||promopure.com^$subdocument,third-party
```
[#p115874](https://forums.lanik.us/viewtopic.php?f=62&t=36194&hilit=promopure.com#p115874) [#p124584](https://forums.lanik.us/viewtopic.php?f=62&t=34526&hilit=promopure.com#p124584)
