### ISSUE TITLE
webdesign.tutsplus.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#16222]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://webdesign.tutsplus.com/id/tutorials/20-popular-wordpress-user-interface-elements--cms-29004`

### Category

ads

### Description

![image](https://user-images.githubusercontent.com/19517680/210600247-6b846446-eb10-42f2-998a-1f5fefaae8ed.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 122001
  cosmetic: 140423
  scriptlet: 24664
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7748-3, 1d.5h.38m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 58-4, 1d.5h.37m
    RUS-0: 39366-48, 1d.5h.31m
    adguard-spyware: 36617-3421, 1d.5h.39m
    fanboy-annoyance: 84454-410, 9d.34m
    fanboy-cookiemonster: 44322-44322, 9d.33m
    ublock-annoyances: 4809-85, 1d.5h.36m
  default: 
    user-filters: 20-0, never
    easylist: 61860-98, 5d.10h.55m
    easyprivacy: 30847-12298, 5d.10h.54m
    ublock-abuse: 77-1, 4d.15h.53m
    ublock-badware: 4219-109, 1d.5h.35m
    ublock-filters: 31560-445, 1d.5h.34m
    ublock-privacy: 257-51, 4d.15h.52m
    ublock-quick-fixes: 446-18, 4h.33m
    ublock-unbreak: 1914-64, 1d.5h.33m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 21 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 17673 ms (selfie)
  maxAssetCacheWait: 405 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    tutsplus.com: 5
    cookiebot.com: 1
    fuseplatform.net: 1
    google-analytics.com: 1
    googleadservices.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
indonesian site, enable `IDN, MYS: ABPindo` list

add also
`webdesign.tutsplus.com##.avert`

@gmarcher
