### ISSUE TITLE
clash.ninja: breakage

### ISSUE THREAD

**Issue by Viceroyy** [uBlockOrigin/uAssets#16234]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Push notifications unavailable

### URL(s) where the issue occurs.

`https://www.clash.ninja/my-account/notification-settings`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/97338859/210745633-4efce78a-2472-46f1-8e71-27be7c917eb2.png)

### uBO version

1.46.0

### Browser name and version

Brave Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

### Settings

**ALL** filters enabled, added [I don't care about cookies](https://www.i-dont-care-about-cookies.eu/) as a custom filter. _Auto-update filter lists_, _Suspend network activity until all filter lists are loaded_ and _Parse and enforce cosmetic filters_ are checked, _Ignore generic cosmetic filters_ unchecked.

**Comment by Viceroyy** [comment]
> I get that error even with uBO disabled.

I don't.
![image](https://user-images.githubusercontent.com/97338859/210749958-f25affe7-9118-4d29-ad34-5b4826df4d62.png)

**Comment by mapx-** [comment]
@Viceroyy 
test

`@@||onesignal.com/api/$xhr,domain=clash.ninja`

**Comment by stephenhawk8054** [comment]
> > @Viceroyy test
> > `@@||onesignal.com/api/$xhr,domain=clash.ninja`
> 
> Issue persists

That filter works for me

![image](https://user-images.githubusercontent.com/66517106/210754548-0f2fa7a5-c122-4ad6-9863-ab9f9b688147.png)

**Comment by mapx-** [comment]
it seems to be a brave issue even disabling uBO and brave shields:

xhr requests are "invisible" in brave, I get them in chrome

`https://onesignal.com/api/v1/players`

**Comment by Viceroyy** [comment]
I setup a firefox installation with the same browser settings (best as I can copy on surface level) and extension settings and it seems like in firefox it works by default

**Comment by mapx-** [comment]
chrome

![image](https://user-images.githubusercontent.com/10303732/210757529-844b26dc-3745-4340-8fe3-cf3532f5b3ba.png)

**Comment by mapx-** [comment]
firefox

![image](https://user-images.githubusercontent.com/10303732/210758051-72754099-33ab-4e3c-b275-60f7b1f66215.png)

**Comment by stephenhawk8054** [comment]
> I get "Push notifications unavailable" using Firefox 108.0.1. There is no `xhr` request to onesignal: 

Did you enable notifications permission in Firefox?

![image](https://user-images.githubusercontent.com/66517106/210758276-29eedc8b-ccb7-4faa-869f-de3b9e37237a.png)

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/labels/geo%20specific?

**Comment by mapx-** [comment]
brave issue, the filter added fixes the issue in FF / chrome

**Comment by krystian3w** [comment]
But MasterKia don't compile brave with Firefox theme...
