### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by icecoldmc** [uBlockOrigin/uAssets#16233]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/2lLix/Vampire.The.Masquerade.Parliament.of.Knives.rar`

### Category

detection

### Description

it removes the ads but doesnt let you get the link gets detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 84896
  cosmetic: 39005
  scriptlet: 16740
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 61524-598, never
    easyprivacy: 30820-1176, never
    plowe-0: 3671-564, never
    ublock-abuse: 77-0, never
    ublock-badware: 4232-0, never
    ublock-filters: 31551-60, never
    ublock-privacy: 255-0, never
    ublock-quick-fixes: 458-0, never
    ublock-unbreak: 1922-2, never
    urlhaus-1: 8695-0, never
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2291 ms
  maxAssetCacheWait: 15 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    megaup.net: 2
    a-ads.com: 1
    altowriestwispy.com: 1
    bidgear.com: 1
    dmmzkfd82wayn.cloudfront.net: 2
    googletagmanager.com: 1
    keydawnawe.com: 1
    s3.amazonaws.com: 1
```
</details>

**Comment by mapx-** [comment]
- fixed 1 h ago
- update ALL your filter lists
