### ISSUE TITLE
jbzd.com.pl: ads

### ISSUE THREAD

**Issue by Gomido** [uBlockOrigin/uAssets#16249]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://jbzd.com.pl/`

### Category

ads

### Description

Well. There are ads everywhere, whether it's a pure browser with only adblock or without it - there is no difference. Dating pop-ups, ads left and right, between memes too.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![t1NCYoh](https://user-images.githubusercontent.com/33147683/210848316-1ab1fa98-8495-49c1-a07c-e74cab83f67b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.1b5
Chromium: 108
filterset (summary): 
  network: 21080
  cosmetic: 16926
  scriptlet: 16966
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    easylist: null
    easyprivacy: null
    plowe-0: null
  added: 
    https://letyshops.com/adblock.txt: 0-0, 22h.3m
    fanboy-thirdparty_social: 69-0, 6d.23h.47m
  default: 
    user-filters: 87-1, never
    POL-0: 7877-8, 22h.4m
    POL-2: 1276-13, 1d.23h.24m
    ublock-abuse: 77-0, 2d.22h.34m
    ublock-badware: 4268-0, 3d.23h.58m
    ublock-filters: 31558-73, 3d.23h.57m
    ublock-privacy: 260-0, 2d.22h.33m
    ublock-quick-fixes: 447-15, 26m
    ublock-unbreak: 1915-3, 3d.23h.56m
    urlhaus-1: 7264-0, 25m
filterset (user): [array of 87 redacted]
trustedset: 
  added: [array of 65 redacted]
switchRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 686 ms (selfie)
  maxAssetCacheWait: 152 ms
popupPanel: 
  blocked: 53
  blockedDetails: 
    a-mx.com: 2
    adform.net: 5
    doubleclick.net: 11
    facebook.net: 1
    gemius.pl: 1
    googlesyndication.com: 1
    googletagservices.com: 2
    smartadserver.com: 18
    spolecznosci.net: 1
    taboola.com: 6
    tapad.com: 1
    wp.pl: 4
```
</details>

**Comment by mapx-** [comment]
Enable back those 3 important lists

```
   easylist: null
   easyprivacy: null
   plowe-0: null

```
