### ISSUE TITLE
[nsfw] k2s.cc: nuisance

### ISSUE THREAD

**Issue by Gbt12** [uBlockOrigin/uAssets#16242]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://k2s.cc/file/6762e1bf5e4d6/niddhch.mp4`

### Category

nuisance

### Description

after few minute player start showing popup and video not streaming even after skiping the nuiances.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/122017553/210775028-917150bd-94c0-44eb-8036-7658357b515f.jpeg

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 142694
  cosmetic: 95360
  scriptlet: 23595
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://abp.oisd.nl/basic/: 69823-0, 25m
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 854-0, 25m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2069-1, 25m
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1877-20, 25m
    https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4589-45, 25m
    adguard-annoyance: 62090-248, 25m
    adguard-spyware-url: 878-130, 25m
    ublock-annoyances: 4709-154, 25m
  default: 
    user-filters: 6-0, never
    easylist: 61578-17608, 25m
    easyprivacy: 30880-4511, 25m
    plowe-0: 3671-2729, 25m
    ublock-abuse: 77-2, 25m
    ublock-badware: 4239-167, 25m
    ublock-filters: 31594-658, 25m
    ublock-privacy: 258-26, 25m
    ublock-quick-fixes: 447-18, 25m
    ublock-unbreak: 1915-49, 25m
    urlhaus-1: 7234-605, 25m
filterset (user): [array of 6 redacted]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 865 ms (selfie)
  maxAssetCacheWait: 543 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    k2s.cc: 1
    googletagmanager.com: 1
```
</details>

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets
> Circumventing a paywall is considered [out of scope](https://github.com/uBlockOrigin/uAssets/issues/2317#issuecomment-392009540).
