### ISSUE TITLE
ladbible.com: detection

### ISSUE THREAD

**Issue by trulyx** [uBlockOrigin/uAssets#16248]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ladbible.com/news/salt-bae-slammed-talking-on-airpods-895494-20221227?source=foodbiblestatic&fbclid=IwAR2G5VLcKbuuFLEC71IwTRYIkiaOuoTi9GFb_cWvFpgb1w2JBmmeGSwsIIw`

### Category

detection

### Description

"Please turn off your ad blocking software to view this video"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 84152
  cosmetic: 39654
  scriptlet: 16825
  html: 872
listset (total-discarded, last-updated): 
  added: 
    ISR-0: 1665-0, 20h.52m
  default: 
    user-filters: 3-0, never
    ublock-filters: 32359-54, 2d.27m
    ublock-badware: 4224-0, 2d.26m
    ublock-privacy: 307-0, 11d.5m
    ublock-abuse: 77-0, 11d.4m
    ublock-unbreak: 1929-1, 2d.28m
    easylist: 61368-620, 20h.55m
    easyprivacy: 30878-1739, 20h.56m
    plowe-0: 3673-2, 8d.21h.11m
    urlhaus-1: 7152-0, 20h.54m
    ublock-quick-fixes: 453-1, 20h.53m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4266 ms (selfie)
  maxAssetCacheWait: 79 ms
popupPanel: 
  blocked: 43
  blockedDetails: 
    ladbible.com: 3
    adsafeprotected.com: 6
    amazon-adsystem.com: 1
    ay.delivery: 2
    chartbeat.com: 1
    clouderrorreporting.googleapis.com: 2
    connatix.com: 2
    datadoghq.com: 1
    dotmetrics.net: 1
    doubleclick.net: 6
    facebook.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    imrworldwide.com: 1
    outbrain.com: 1
    permutive.com: 1
    quantserve.com: 1
    rubiconproject.com: 1
    scorecardresearch.com: 1
    spot.im: 8
```
</details>

**Comment by stephenhawk8054** [comment]
I cannot reproduce the anti-adb. Can you force update the filter lists and test again? Also heck if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by trulyx** [comment]
Seems to have been resolved now (haven't changed anything, just tried again today).
Thanks.

**Comment by mapx-** [comment]
Are you using `Fanboy’s Annoyance` list ?

`||consent.ladbible.com^$badfilter`

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/f3d5c375034d23ead24ccce964f6d61af01aedb9

**Comment by stephenhawk8054** [comment]
I enabled both RU and FR lists but still cannot reproduce the anti-adblock.
