### ISSUE TITLE
skincarie.com: detection

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#16250]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://skincarie.com/Jnnx`

### Category

detection

### Description

these URLs will redirect you
```
https://clk.asia/Jnnx
https://clk.today/Jnnx
```

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/210914018-5d671519-5fc0-4a54-bfd2-141e0f7ac185.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 119029
  cosmetic: 153754
  scriptlet: 33796
  html: 864
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-generic: 67048-5697, now
    adguard-spyware: 36626-14398, now
    adguard-spyware-url: 879-4, now
    adguard-annoyance: 62105-1512, now
    adguard-social: 19722-26, now
  default: 
    user-filters: 68-0, never
    ublock-filters: 32379-74, now
    ublock-badware: 4250-0, now
    ublock-privacy: 305-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1928-4, now
    ublock-quick-fixes: 453-0, now
    easylist: 61608-339, now
    easyprivacy: 30880-1190, now
    TUR-0: 12623-13, now
filterset (user): [array of 73 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1783 ms (selfie)
  maxAssetCacheWait: 1216 ms
  unsuspendAfter: 243 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    skincarie.com: 1
    bringsconserve.com: 2
    googletagmanager.com: 1
    netpub.media: 1
    purpleads.io: 1
    system-notify.app: 1
    taghaugh.com: 1
    vlitag.com: 1
```
</details>

**Comment by mapx-** [comment]
I get no such page on the various redirections starting from your links above

However, could you test if this link fixes the issue on your side:

`skincarie.com##+js(set, adblockDetector, noopFunc)`
