### ISSUE TITLE
memoryhackers.org: detection

### ISSUE THREAD

**Issue by hieuck** [uBlockOrigin/uAssets#16251]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://memoryhackers.org/`

### Category

detection

### Description

tắt bộ lọc phần tử ẩn thì không hiện thông báo

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/30469654/210971778-7f9d26e8-f7ff-4879-9d1c-f243a092c3bd.png)

![image](https://user-images.githubusercontent.com/30469654/210972281-d8f69a81-70b4-4a05-9062-f30b4e5e685d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 102
filterset (summary): 
  network: 84528
  cosmetic: 39974
  scriptlet: 16856
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 28-0, never
    VIE-1: 1935-2, now
    easylist: 61679-68, 7m
    easyprivacy: 30884-1174, 7m
    plowe-0: 3671-901, 7m
    ublock-abuse: 77-0, 7m
    ublock-badware: 4246-112, 7m
    ublock-filters: 31592-129, 7m
    ublock-privacy: 258-1, 7m
    ublock-quick-fixes: 447-18, 6m
    ublock-unbreak: 1915-45, 6m
    urlhaus-1: 7241-0, 6m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 590 ms (selfie)
  maxAssetCacheWait: 834 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    doubleclick.net: 4
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    youtube.com: 10
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce.
It's a turkish site and the regional list has some filters for it.
Is your problem fixed if you enable `AdGuard Turkish`?

**Comment by hieuck** [comment]
> 

i enabled the filter TUR: AdGuard Turkish and still getting detected

if you are not detected can you give me a picture of that page and the filter list enabled

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/210977207-54b98576-bdd2-4a69-b8c4-2300c34af174.png)

I have only the default filter lists enabled.

**Comment by hieuck** [comment]
i restored default+browse incognito using uBlock Origin only and went to homepage -> undetected

But logging in is detected
![image](https://user-images.githubusercontent.com/30469654/210978318-53cde7d2-bdce-434b-b752-9726a4591306.png)

![image](https://user-images.githubusercontent.com/30469654/210978207-965af6de-e962-4878-9e23-8302375a6598.png)

**Comment by hieuck** [comment]
> Can you test if adding this filter works?
> 
> ```
> memoryhackers.org##+js(acs, RegExp, googlebot)
> ```

thank you. 
![image](https://user-images.githubusercontent.com/30469654/210999468-084b4740-973a-4807-ad3b-75f04475837f.png)

**Comment by okiehsch** [comment]
No site functionality appears to be disabled by the detection, looks like an annoyance at first glance.

**Comment by stephenhawk8054** [comment]
> No site functionality appears to be disabled by the detection, looks like an annoyance at first glance.

Ah you're right, I didn't realize that. I'll move it to annoyance.

**Comment by stephenhawk8054** [comment]
@hieuck Since the filter is moved to annoyance list, you can enable `uBlock filters – Annoyances` in about 10 minutes.
