### ISSUE TITLE
writedroid.eu.org: detection

### ISSUE THREAD

**Issue by yashzade** [uBlockOrigin/uAssets#16253]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.writedroid.eu.org/?m=1`

### Category

detection

### Description

Detected as blocker 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 85335
  cosmetic: 28172
  scriptlet: 16824
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 17-0, never
    adguard-mobile: 8432-27, now
    easylist: 61679-17338, now
    easyprivacy: 30884-1182, now
    plowe-0: 3671-985, now
    ublock-abuse: 77-0, now
    ublock-badware: 4245-113, now
    ublock-filters: 31702-365, now
    ublock-privacy: 258-2, now
    ublock-quick-fixes: 447-18, now
    ublock-unbreak: 1920-47, now
    urlhaus-1: 7241-0, now
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 478 ms (selfie)
  maxAssetCacheWait: 212 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    crankyderangeabound.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 2
```
</details>

**Comment by yashzade** [comment]
Still the ad blocker got detected.

**Comment by mapx-** [comment]
- Did you see the new filter in the logger ?
`writedroid.in##+js(nostif, _0x)`

You are using a browser not always supported by uBO (probably kiwi).

**Comment by mapx-** [comment]
ok, I understood, very strange:

on desktop your link brings me to `writedroid.in`, on mobile keeps still `writedroid.eu.org`

**Comment by mapx-** [comment]
update again your filters in 5 - 10 min
