### ISSUE TITLE
EITB.eus detects ad-blocking

### ISSUE THREAD

**Issue by davidmef** [uBlockOrigin/uAssets#16259]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I press the Play button, a popup appears saying
> Desactiva el bloqueador de publicidad y recarga la página para poder reproducir el contenido.
That is:
> Disable the ad-blocker and reload the page to play the content.

(I haven't really tried the lines under "I tried to reproduce the issue when...". I don't think they are related to the issue).

### URL(s) where the issue occurs.

`https://www.eitb.eus/es/nahieran/divulgativos/una-historia-de-vasconia/los-pueblos-guerreros-de-vasconia/detalle/5547/115374/`

### uBO version

 v1.16.4.30

### Browser name and version

Pale Moon 31.4.2 (64-bit) Windows

### Settings

Filters I use:
uBlock filters 30.697 utilizados de 30.864
uBlock filters - Legacy 148 utilizados de 149
uBlock filters – Badware risks 4.102 utilizados de 4.214
uBlock filters – Privacy 298 utilizados de 299
uBlock filters – Resource abuse 56 utilizados de 56
uBlock filters – Unbreak 2.052 utilizados de 2.098
EasyList 61.267 utilizados de 61.713
EasyPrivacy 29.297 utilizados de 31.022
Online Malicious URL Blocklist 8.425 utilizados de 8.425
uBlock filters – Annoyances 4.796 utilizados de 4.800
Peter Lowe’s Ad and tracking server list 3.669 utilizados de 3.671
spa, por: AdGuard Spanish/Portuguese 4.801 utilizados de 4.813
spa: EasyList Spanish 3.327 utilizados de 3.430
Malware Domain List 1.104 utilizados de 1.104
Malware domains 0 utilizados de 0

**Comment by Procyon-b** [comment]
Try this filter:
```
||imasdk.googleapis.com^$redirect-rule=noopjs,domain=eitb.eus
```

**Comment by davidmef** [comment]
No, it shows the same message.

**Comment by Procyon-b** [comment]
It shows a different message to me (the same when visiting without ublock)
```
El archivo multimedia no se ha podido cargar. El servidor o la red han fallado o el formato no es compatible.
```

**Comment by stephenhawk8054** [comment]
This works for me with Firefox 108.0.2

```adb
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=eitb.eus,redirect-rule=google-ima.js
```

But I'm not sure if uBO's legacy version would work or not.

**Comment by stephenhawk8054** [comment]
@davidmef Can you test this?

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=eitb.eus
```

**Comment by davidmef** [comment]
It works with @@ 
Thanks a lot.
