### ISSUE TITLE
German finance sites: ads

### ISSUE THREAD

**Issue by oliuo1** [uBlockOrigin/uAssets#16252]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Onvista Homppage big white gaps:  `www.onvista.de`
https://user-images.githubusercontent.com/122091080/210999064-2d935dba-c019-4b32-ad09-650eaccfcf0b.png

scrolling down on HP:
https://user-images.githubusercontent.com/122091080/210999219-3083b028-fad7-48a7-8f18-884f24f6e803.png

scrolling even further down on HP:
https://user-images.githubusercontent.com/122091080/210999390-63076126-1339-49a8-8a71-ee69287cf0fa.png

white gaps also on article pages eg:
`https://www.onvista.de/news/2023/01-06-meta-whatsapp-nutzer-koennen-nun-internet-sperren-der-app-umgehen-20-26083260`
or:
`https://www.onvista.de/news/2023/01-06-insider-kryptofirma-genesis-entlaesst-30-prozent-des-personals-20-26083250`

https://user-images.githubusercontent.com/122091080/210999701-5ade0532-62e5-4dbd-b37d-f050b94e8632.png

near footer on the same page:
https://user-images.githubusercontent.com/122091080/210999807-2a6b8abd-d6e0-4fb9-836d-4157496f540a.png

also white gaps on share price pages eg:
`https://www.onvista.de/aktien/Meta-Platforms-ehem-Facebook-Aktie-US30303M1027`

right below the heaer, then before the block "Weitere Kurse der Meta Platforms (ehem. Facebook) Aktie", and before the footer

also here white gaps:  just scroll down the page to see several "spots"
`https://www.onvista.de/index/Nikkei-Index-60972397`

### URL(s) where the issue occurs.

`https://www.onvista.de/news/2023/01-06-insider-kryptofirma-genesis-entlaesst-30-prozent-des-personals-20-26083250`

### uBO version

last one

### Browser name and version

Firefox

### Settings

-

**Comment by oliuo1** [comment]
now finanzen100.de:
https://finanzen100.de/finanznachrichten/boerse/70-prozent-minus-oder-1400-prozent-plus-bei-bitcoin-ist-alles-denkbar_H1978151306_182043659/
![image](https://user-images.githubusercontent.com/122091080/211001419-5eb87f9e-aace-4c55-9a91-fbf49bc18376.png)


scrolling down:

![image](https://user-images.githubusercontent.com/122091080/211001521-83a91a1b-b1ed-42fc-ac2c-576b2f23fd77.png)

buchtipp ad and you see many white gaps in the page

https://finanzen100.de/finanznachrichten/boerse/das-raet-top-boersenprofi-jens-ehrhardt-anlegern-im-neuen-jahr_H570937628_182042709/

on this URL also many white gaps

on every page at the end big gap see here
https://www.finanzen100.de/index/l-s-dax_H771900592_14734849/

![image](https://user-images.githubusercontent.com/122091080/211001899-8ad4572c-9ebc-4092-a321-ffcaa4d3636c.png)

**Comment by oliuo1** [comment]
right on the HP https://www.bloomberg.com/europe in the header big grey gap

**Comment by oliuo1** [comment]
ariva.de homepage see screenshot
![image](https://user-images.githubusercontent.com/122091080/211003043-b23113a3-cf27-441b-9e84-2fbdc162c2cd.png)

share page: https://www.ariva.de/fresenius_se_co_kgaa-aktie

![image](https://user-images.githubusercontent.com/122091080/211003396-9dd1c4f6-be92-45b4-a13d-c691f373b252.png)
![image](https://user-images.githubusercontent.com/122091080/211003483-0db51018-4870-4407-97a0-9007fc80b096.png)
![image](https://user-images.githubusercontent.com/122091080/211003560-735ffc46-8c28-4306-ac1a-90efca359fe3.png)

https://www.ariva.de/fresenius_se_co_kgaa-aktie/kurse/times-sales?boerse_id=1
![image](https://user-images.githubusercontent.com/122091080/211003780-da7f7997-a20f-48b3-b322-9fa1219edb63.png)

every page in navigation drodowns see here:
![image](https://user-images.githubusercontent.com/122091080/211003930-bdfde361-f3c0-4376-a550-4c9b7423a94d.png)

**Comment by oliuo1** [comment]
finanznachrichten.de

https://www.finanznachrichten.de/aktienkurse/realtime-kurse.htm

![image](https://user-images.githubusercontent.com/122091080/211005733-2413253c-8325-4cd2-9826-24968d909962.png)

Ads in News:
https://www.finanznachrichten.de/nachrichten-aktien/adidas-ag.htm

![image](https://user-images.githubusercontent.com/122091080/211006039-9e3cd4f3-82d9-4b78-a256-e06c86510f49.png)

if you go on Page 2 in news
![image](https://user-images.githubusercontent.com/122091080/211006157-9f7b9cd5-07f7-4f43-9908-a86e1177c988.png)

or here: https://www.finanznachrichten.de/nachrichten-aktien/sap-se.htm

![image](https://user-images.githubusercontent.com/122091080/211006330-767bba1d-b303-4a5e-9e62-14873aacf8b8.png)

MORE ADS ON EVERY share page. https://www.finanznachrichten.de/aktien-analysen/sap-se.htm

![image](https://user-images.githubusercontent.com/122091080/211006526-cecfeefa-8f7b-4c1c-b453-b263a5e4bef0.png)

https://aktienkurs-orderbuch.finanznachrichten.de/sap.htm
![image](https://user-images.githubusercontent.com/122091080/211006716-bc862e24-3625-4ea8-84c4-b8e44b4af32b.png)

https://www.finanznachrichten.de/aktien-analysen/volkswagen-ag-vz.htm
![image](https://user-images.githubusercontent.com/122091080/211006967-4c6c2e18-22b0-4d85-9c70-a0f8d97b82a7.png)

https://aktienkurs-orderbuch.finanznachrichten.de/vow3.htm
![image](https://user-images.githubusercontent.com/122091080/211007101-c00ef5f6-32cf-4b69-8972-c196daa7ee7d.png)

**Comment by oliuo1** [comment]
even more ads:
https://www.finanznachrichten.de/aktienkurse-boersen/sap-se.htm
![image](https://user-images.githubusercontent.com/122091080/211007245-ea2dff41-4956-4924-a7ea-413cb151b35f.png)

**Comment by okiehsch** [comment]
Before you continue, this is not the repo for this kind of issues.
These are all german sites with "normal" text ads.

Go to https://github.com/easylist/easylistgermany and open it there.
