### ISSUE TITLE
lehibou.com: ads

### ISSUE THREAD

**Issue by Hkllopp** [uBlockOrigin/uAssets#16264]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lehibou.com/communaute/methode-agile/`

### Category

ads

### Description

There are three ads on this webpage, the first one is a slider you can close by clicking the X button, the second one is another slider from the bottom also closable by the X mark and the third one is an ad for Sodexo on the right sidebar.

__Without the numbers :__
![image](https://user-images.githubusercontent.com/9498111/211168338-4e067413-68e2-4003-835f-5ea877b6ca59.png)

__With the numbers :__
![image](https://user-images.githubusercontent.com/9498111/211168323-16ac0d9f-ce87-4b7e-836c-8560155b92c0.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 86833
  cosmetic: 38682
  scriptlet: 16766
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32361-54, 2d.8h.6m
    ublock-badware: 4243-0, 2d.2m
    ublock-privacy: 304-0, 7d.45m
    ublock-abuse: 77-0, 7d.4h.48m
    ublock-unbreak: 1927-2, 2d.8h.7m
    ublock-quick-fixes: 461-0, 1h.29m
    easylist: 64996-606, 5d.20h.35m
    easyprivacy: 30878-1738, 2d.4h.3m
    urlhaus-1: 6797-0, 1h.28m
    plowe-0: 3671-2, 5d.2h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1041 ms (selfie)
  maxAssetCacheWait: 532 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    lehibou.com: 2
    googletagmanager.com: 1
    omappapi.com: 1
    pinterest.com: 1
```
</details>

**Comment by mapx-** [comment]
- all 3 are self-promotion so no maintainer will add filters for such "issues"
- for french pages Enable the dedicated list: `FRA: AdGuard Français`
- if you still want another opinion just report at french list repository:
https://github.com/easylist/listefr/issues

**Comment by Hkllopp** [comment]
Ok, thanks a lot for you help and sorry these mistakes.
