### ISSUE TITLE
remkomplekty.ru: privacy

### ISSUE THREAD

**Issue by proton1k** [uBlockOrigin/uAssets#16268]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://remkomplekty.ru/`

### Category

privacy

### Description

Website uploads information to 3rds party malicious websites. Privacy under huge concern. Names of websites:
```
fuyviz.com
ybej5ohp0x.ru
rbthre.work
tat3ayogh6.com
prodmp.ru
dmpprof.com
cau1aighae.com
mixprise.ru
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 82969
  cosmetic: 38760
  scriptlet: 16769
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 19-2, never
    easylist: 61199-44, 5d.9h.18m
    easyprivacy: 30880-1171, 1d.3h.13m
    plowe-0: 3669-898, 7d.22h.56m
    ublock-abuse: 77-0, 2d.22h.39m
    ublock-badware: 4234-111, 2d.22h.36m
    ublock-filters: 31571-121, 2d.22h.37m
    ublock-privacy: 258-1, 2d.22h.38m
    ublock-quick-fixes: 455-18, 33m
    ublock-unbreak: 1914-44, 2d.22h.35m
    urlhaus-1: 6797-0, 32m
filterset (user): [array of 19 redacted]
trustedset: 
  added: [array of 25 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2332 ms (selfie)
  maxAssetCacheWait: 204 ms
popupPanel: 
  blocked: 18
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  blockedDetails: 
    dmpprof.com: 1
    doubleclick.net: 4
    google.com: 5
    googlesyndication.com: 1
    prodmp.ru: 1
    rbthre.work: 1
    yandex.ru: 1
    youtube.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `RUS: RU AdList` filter list and test again?

**Comment by mapx-** [comment]
RU AdList is blocking 3rd party stuff, however it seems the pics are broken, maybe @dimisa-RUAdList could help here

**Comment by dimisa-RUAdList** [comment]
@proton1k 
Please indicate the exact link where there are requests to `fuyviz.com`, `ybej5ohp0x.ru`, and so on. There is no such thing on `https://remkomplekty.ru/`.

@mapx- 
Please indicate the exact link where, due to the blocker, images are broken.

**Comment by mapx-** [comment]
using RUAdList

![image](https://user-images.githubusercontent.com/10303732/211188158-c80b0d0a-72c4-4491-81b0-77469e95755b.png)

without RUAdList
![image](https://user-images.githubusercontent.com/10303732/211188177-2edd93ed-2d2c-460b-92bd-c71f7db1282f.png)

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/211188248-360ce5b9-15d8-4712-b9c8-07b186ba5d49.png)

**Comment by dimisa-RUAdList** [comment]
This site has two incarnations - a building materials store: `https://remkomplekty.ru/` and a collection of articles on computer topics: `https://remkomplekty.ru/excel/kak-skachat-video-s-hdrezka-ag.html`.

The last publication on computer topics was made more than 2 years ago.

I also called the director of the building materials store, who informed me that the site had been abandoned for more than 2 years, and the store itself was physically closed.

I think we don't have to worry about this site. At least until he returns to normal work.

**Comment by proton1k** [comment]
Could you please review the sub-link https://remkomplekty.ru/excel/kak-skachat-video-s-hdrezka-ag.html ? 
The page does not correspond to the apex page content at all.

**Comment by mapx-** [comment]
@proton1k did you enable the russian list ?

**Comment by proton1k** [comment]
> @proton1k did you enable the russian list ?

Yes, that works. Thank you!
