### ISSUE TITLE
linkneverdie.net: detection

### ISSUE THREAD

**Issue by lebaominh12** [uBlockOrigin/uAssets#16263]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkneverdie.net/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 https://imgur.com/a/be7MFdH

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 87291
  cosmetic: 38581
  scriptlet: 16780
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    VIE-1: null
  default: 
    user-filters: 6-0, never
    easylist: 64996-53, 10h.23m
    easyprivacy: 30908-1171, 14h.48m
    plowe-0: 3673-869, 11d.3h.18m
    ublock-abuse: 77-0, 1d.23h.37m
    ublock-badware: 4219-111, 4d.2h.2m
    ublock-filters: 31523-129, 4d.2h.1m
    ublock-privacy: 258-1, 1d.23h.36m
    ublock-quick-fixes: 450-14, 10h.22m
    ublock-unbreak: 1911-46, 4d.2h
    urlhaus-1: 7188-0, 23h.49m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 259 ms (selfie)
  maxAssetCacheWait: 127 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    linkneverdie.net: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    optad360.io: 2
    pubmatic.com: 1
    tawpykheda.com: 1
```
</details>

**Comment by mapx-** [comment]
- add back the regional list VIE
- if still get some issue report directly here:
https://github.com/abpvn/abpvn/issues
