### ISSUE TITLE
card.discover.com: breakage

### ISSUE THREAD

**Issue by bikrrr** [uBlockOrigin/uAssets#16265]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://card.discover.com/web/rewards/5percent/`

### Category

breakage

### Description

Missing body content. The only thing that displays is the navigation header of the page. The remaining page is blank.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![uBlock Origin Discover Card Issue](https://user-images.githubusercontent.com/2607653/211170516-78b8c3a6-6b5e-433a-8d04-6ab4a99244a2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 84055
  cosmetic: 38742
  scriptlet: 16766
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 61911-44, 5d.4h.4m
    easyprivacy: 30858-1171, 5d.4h.3m
    plowe-0: 3673-899, 10d.9h.4m
    ublock-abuse: 77-0, 2d.5h.14m
    ublock-badware: 4234-111, 3d.41m
    ublock-filters: 31571-120, 3d.40m
    ublock-privacy: 258-1, 2d.5h.13m
    ublock-quick-fixes: 450-18, 1d.2h.55m
    ublock-unbreak: 1915-45, 3d.39m
    urlhaus-1: 7188-0, 1d.2h.54m
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 50699 ms (selfie)
  maxAssetCacheWait: 179 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    discover.com: 2
    appdynamics.com: 4
    btstatic.com: 1
    clicktale.net: 1
    instana.io: 1
```
</details>

**Comment by mapx-** [comment]
- an account is required
- an issue for discover was reported 2 weeks ago: https://github.com/uBlockOrigin/uAssets/issues/16091
- in order to investigate we need an account or let's try this:

-- open uBO logger
-- repeat the steps to get again the issue
-- go back into the logger, copy and post here all the blocked requests you get there

**Comment by bikrrr** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +177 |  |  | card.discover.com | 1 | font | `https://card.discover.com/web/rewards/5percent/static/media/DiscoverSans-Semibold.89ae07fa92e7f1c7cf4a.woff2` |
| +177 |  |  | card.discover.com | 1 | image | `https://card.discover.com/applications/5percent/images/groceryDrugStreaming_header.png` |
| +177 |  |  | card.discover.com | 1 | image | `https://card.discover.com/applications/5percent/images/groceryDrugStreaming.jpg` |
| +177 | /adrum- | -- | card.discover.com | 3 | script | `https://cdn.appdynamics.com/adrum/adrum-4.5.17.2890.js` |
| +177 | /adrum- | -- | card.discover.com | 3 | script | `https://cdn.appdynamics.com/adrum/adrum-4.5.17.2890.js` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://card.discover.com/cardissuer/rewards/enrollment/v1/offer-enroll-category-details?throttle=false&includeEarnedAmounts=true&incentiveType=CBB&incentiveCode=000016&channelCode=AC` |
| +177 |  |  | card.discover.com | 1 | image | `https://card.discover.com/global/images/discover/account/customerservice/cards/DISCOVER_IT_CHP.gif` |
| +177 | /adrum- | -- | card.discover.com | 3 | script | `https://cdn.appdynamics.com/adrum/adrum-4.5.17.2890.js` |
| +177 |  |  | card.discover.com | 1 | script | `https://portal.discover.com/bRJWFncjQ4K51CkB9glU/1bQabNQzOw/bBJnKQVZfQ/OhhbM/hxnSX4` |
| +177 |  |  | card.discover.com | 1 | font | `https://card.discover.com/web/rewards/5percent/static/media/DiscoverSans-Bold.a2e0cdf51cf774d8fe10.woff2` |
| +177 |  |  | card.discover.com | 1 | image | `https://card.discover.com/global/images/utility-icons.png` |
| +177 | /adrum- | -- | card.discover.com | 3 | script | `https://cdn.appdynamics.com/adrum/adrum-4.5.17.2890.js` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://portal.discover.com/enterprise/navigation-api/v1/customer/info/card?` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://portal.discover.com/enterprise/navigation-api/v1/messages/card/messageCount?` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://portal.discover.com/enterprise/navigation-api/v1/navigation/card?` |
| +177 |  |  | card.discover.com | 1 | other | `https://card.discover.com/web/rewards/5percent/manifest.json` |
| +177 |  |  | card.discover.com | 1 | font | `https://card.discover.com/web/rewards/5percent/static/media/DiscoverSans-Medium.ae7a7f50dcd06e650243.woff2` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://card.discover.com/global/components/templates/html/footer.html` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://card.discover.com/cardmembersvcs/rewards/app/redemption/headerInfo` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://card.discover.com/cardissuer/rewards/rewardaccount/v2/program` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://card.discover.com/cardissuer/rewards/oneclick/v1/generateOneClickId` |
| +177 | \|\|btstatic.com^$3p | -- | card.discover.com | 3 | script | `https://s.btstatic.com/tag.js#site=p9zWtoq&referrer=https%3A%2F%2Fcard.discover.com%2Fweb%2Frewards%2F5percent%2F%3FICMPGN%3DAC_NAV_L3_5PCT_CBB` |
| +177 | \|\|clicktale.net^$3p | -- | card.discover.com | 3 | script | `https://cdnssl.clicktale.net/www15/ptc/fd145cf2-4109-439c-97f8-e0bc3c3e290d.js` |
| +177 |  |  | card.discover.com | 1 | xhr | `https://card.discover.com/web/navigation/ui/navigation-map.json` |
| +177 |  |  | card.discover.com | 1 | script | `https://card.discover.com/web/rewards/5percent/static/js/main.c5cefec8.js` |
| +177 | \|\|instana.io^$3p | -- | card.discover.com | 3 | script | `https://eum.instana.io/eum.min.js` |
| +176 |  |  | card.discover.com | 1 | script | `https://card.discover.com/web/rewards/5percent/vendor/clicktaleHeatmap.min.js` |
| +176 | /appmeasurement.min.js | -- | card.discover.com | 1 | script | `https://card.discover.com/web/rewards/5percent/vendor/AppMeasurement.min.js` |
| +176 |  |  | card.discover.com | 1 | script | `https://card.discover.com/global/libs/scripts/jquery.optimize.min.js` |
| +176 |  |  | card.discover.com | 1 | script | `https://card.discover.com/web/navigation/ui/system.min.js` |
| +176 |  |  | card.discover.com | 1 | css | `https://card.discover.com/web/rewards/5percent/static/css/main.04d10a3c.css` |
| +176 |  |  | card.discover.com | 1 | script | `https://card.discover.com/web/rewards/5percent/vendor/instana.js?redirect=false` |
| +176 | /visitorapi.js | -- | card.discover.com | 1 | script | `https://card.discover.com/global/scripts/visitorAPI.js?ver=9071d5d8ef` |
| +176 |  |  | card.discover.com | 1 | css | `https://card.discover.com/global/css/private-header-footer.css` |
| +176 |  |  | card.discover.com | 1 | doc | `https://card.discover.com/web/rewards/5percent/?ICMPGN=AC_NAV_L3_5PCT_CBB` |
| +176 |  |  | card.discover.com | 1 | doc | `https://card.discover.com/cardmembersvcs/promotions/app/5percent?ICMPGN=AC_NAV_L3_5PCT_CBB` |
| +8 |  |  | `www.reddit.com` | 0,1 | script | `https://www.reddit.com/sw.1ab8087c79dd3679b0bd38e1c9ebc5de.js` |
| +0 |  |  | `www.reddit.com` | 0,1 | xhr | `https://www.reddit.com/` |
</details>

**Comment by bikrrr** [comment]
Not sure if this will also help, but here's the console log from Chrome for the problem page: 
[card.discover.com-1673127040436.log](https://github.com/uBlockOrigin/uAssets/files/10367227/card.discover.com-1673127040436.log)

**Comment by mapx-** [comment]
Test

```
@@||discover.com/*/visitorAPI.js$script,1p
@@||discover.com/*/AppMeasurement.js$script,1p
```

**Comment by bikrrr** [comment]
Hey @mapx, I'm new to uBlock Origin. Where should I put those?

**Comment by mapx-** [comment]
right click uBO icon, options, "my filters" tab, add the filters above, click "apply changes"

**Comment by bikrrr** [comment]
Thanks for the instructions. Unfortunately, after adding those to my filters and applying changes, I still get the same issue.

**Comment by mapx-** [comment]
add this filter too and test again:

`/adrum-$badfilter`

**Comment by stephenhawk8054** [comment]
I think the 2nd one should be

```adb
@@||discover.com/*/AppMeasurement.min.js$script,1p
```

**Comment by mapx-** [comment]
yes, indeed, @bikrrr test again only

```
@@||discover.com/*/visitorAPI.js$script,1p
@@||discover.com/*/AppMeasurement.min.js$script,1p
```

**Comment by bikrrr** [comment]
Those last two worked! 🙌
