### ISSUE TITLE
zamundatv.com: ads

### ISSUE THREAD

**Issue by Jeymen** [uBlockOrigin/uAssets#16279]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://zamundatv.com/bay-ivan-filmat-2021/`

### Category

ads

### Description

There is an leftover banner ad at the right.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 86868
  cosmetic: 38693
  scriptlet: 16785
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32381-52, 23h.50m
    ublock-badware: 4255-0, 23h.49m
    ublock-privacy: 307-0, 2d.4h.21m
    ublock-abuse: 77-0, 2d.4h.20m
    ublock-unbreak: 1933-3, 23h.48m
    ublock-quick-fixes: 470-0, 2m
    easylist: 64996-605, 3d.2h.33m
    easyprivacy: 30880-1740, 3d.2h.32m
    urlhaus-1: 6814-0, 9m
    plowe-0: 3669-2, 2d.12m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1417 ms (selfie)
  maxAssetCacheWait: 155 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    geniusdexchange.com: 2
    google-analytics.com: 1
    google.com: 1
    laurieinevitablyhistorian.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`||ad.serv1for.pro^`

@RealEnder for BGR list
