### ISSUE TITLE
writedroid.eu.org: detection

### ISSUE THREAD

**Issue by Gbt12** [uBlockOrigin/uAssets#16271]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.writedroid.eu.org/#?link4rev=JfXsJ`

### Category

detection

### Description

original link
![Web capture_8-1-2023_10513_www writedroid eu org](https://user-images.githubusercontent.com/122017553/211180610-4fa51ac7-c9ea-4ceb-b6b5-98ea34e193bc.jpeg)

`https://www.writedroid.eu.org/#?link4rev=JfXsJ`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Web capture_8-1-2023_10513_www writedroid eu org](https://user-images.githubusercontent.com/122017553/211180598-5fb54f8e-8ac0-456a-83d0-df132c07ca27.jpeg)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 91912
  cosmetic: 96961
  scriptlet: 23628
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 860-0, 5m
    https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/Popups/sections/antiadblock.txt: 4865-14, 5m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2084-1, 5m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Other%20domains%20versions/BrowseWebsitesWithoutLoggingInAGH.txt: 7-0, 5m
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1877-18, 5m
    adguard-annoyance: 62140-3145, 5m
    adguard-spyware-url: 880-130, 5m
    ublock-annoyances: 4715-156, 5m
  default: 
    user-filters: 5-0, never
    easylist: 61690-108, 5m
    easyprivacy: 30891-1263, 5m
    plowe-0: 3669-903, 5m
    ublock-abuse: 77-0, 5m
    ublock-badware: 4251-112, 5m
    ublock-filters: 31628-507, 5m
    ublock-privacy: 258-6, 5m
    ublock-quick-fixes: 456-19, 5m
    ublock-unbreak: 1921-48, 5m
    urlhaus-1: 6825-0, 5m
filterset (user): [array of 5 redacted]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 315 ms (selfie)
  maxAssetCacheWait: 433 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adoto.net: 2
    crankyderangeabound.com: 1
    googletagmanager.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce any anti-adblock on the page

![image](https://user-images.githubusercontent.com/66517106/211180823-2f2ebd8e-126b-49ee-ac23-e06bb3d929d3.png)

Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by Gbt12** [comment]
issue is resolved Automatically
