### ISSUE TITLE
igg-games.com: detection

### ISSUE THREAD

**Issue by lebaominh12** [uBlockOrigin/uAssets#16275]
### Prerequisites

- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bluemediafile.sbs/url-generator.php?url=KH1TK0eBXmDmljELeo4C+K3Y3FrsoXq7Vd5hLFSbmuTcugZ9zrijtGtu8d9D9F1XcOkNrCmBl2sYge2x9hhwSg==`

### Category

detection

### Description

detected adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 https://imgur.com/a/pa4D1ny

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 86940
  cosmetic: 38582
  scriptlet: 16783
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    VIE-1: null
  default: 
    user-filters: 6-0, never
    easylist: 64996-53, 1d.8h.17m
    easyprivacy: 30908-1171, 1d.12h.42m
    plowe-0: 3673-869, 12d.1h.12m
    ublock-abuse: 77-0, 2d.21h.31m
    ublock-badware: 4251-111, 21h.36m
    ublock-filters: 31523-129, 21h.35m
    ublock-privacy: 258-1, 2d.21h.30m
    ublock-quick-fixes: 456-14, 7h.18m
    ublock-unbreak: 1920-45, 21h.34m
    urlhaus-1: 6797-0, 21h.33m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 214 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 182
  blockedDetails: 
    igg-games.com: 1
    a-ads.com: 1
    adskeeper.com: 2
    ctoziphius.com: 1
    fastcomments.com: 172
    googletagmanager.com: 1
    pogothere.xyz: 4
```
</details>

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
