### ISSUE TITLE
iemqualifiers.com: privacy

### ISSUE THREAD

**Issue by 2ndSky95** [uBlockOrigin/uAssets#16277]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://iemqualifiers.com/?r=page_votes`

### Category

privacy

### Description

steals information

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 85661
  cosmetic: 42677
  scriptlet: 16765
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 13-0, never
    ublock-filters: 32367-63, 1d.17h.32m
    ublock-badware: 4250-0, 1d.17h.31m
    ublock-privacy: 304-0, 6d.22h.31m
    ublock-abuse: 77-0, 6d.22h.30m
    ublock-unbreak: 1931-3, 1d.17h.30m
    ublock-quick-fixes: 461-0, 1h.23m
    easylist: 61718-631, 1h.27m
    easyprivacy: 30893-1751, 1h.26m
    urlhaus-1: 6814-0, 1h.25m
    plowe-0: 3669-2, 2d.2h.55m
    DEU-0: 6091-2, 1h.24m
filterset (user): [array of 13 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 183 ms (selfie)
  maxAssetCacheWait: 69 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    googletagmanager.com: 1
    usercentrics.eu: 1
    youtube-nocookie.com: 6
```
</details>

**Comment by JobcenterTycoon** [comment]
When its phishing report here:

https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en

https://www.microsoft.com/en-us/wdsi/support/report-unsafe-site

https://openphish.com/ (scroll down to the link "Report Phishing")

**Comment by krystian3w** [comment]
https://phishing.eset.com/en-us/report - sometimes faster than Google and MS.

**Comment by JobcenterTycoon** [comment]
`intelauthpage.com` is down already
