### ISSUE TITLE
sledujfilmy.io: nuisance

### ISSUE THREAD

**Issue by Gbt12** [uBlockOrigin/uAssets#16273]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sledujfilmy.io/filmy/the-hanging-sun-2022`

### Category

nuisance

### Description

Video Player Not Showing when Ublock Is Detected .
Play Button Is Hiden Behind Youtube Player Nuisance when Adblocker detected by using Evasive technique.
![Web capture_8-1-2023_113426_www sledujfilmy io](https://user-images.githubusercontent.com/122017553/211182873-c56a051f-3f0c-475b-9f7a-c6401a2f93fa.jpeg)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Web capture_8-1-2023_113426_www sledujfilmy io](https://user-images.githubusercontent.com/122017553/211182878-f3d4d1d6-861e-4b94-b03a-ad408570d936.jpeg)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 91650
  cosmetic: 95435
  scriptlet: 23632
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 860-0, 14m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2084-1, 14m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Other%20domains%20versions/BrowseWebsitesWithoutLoggingInAGH.txt: 7-0, 13m
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1877-18, 13m
    adguard-annoyance: 62140-98, 14m
    adguard-spyware-url: 880-130, 14m
    ublock-annoyances: 4715-156, 13m
  default: 
    user-filters: 5-0, never
    easylist: 61690-108, 14m
    easyprivacy: 30891-1263, 14m
    plowe-0: 3669-903, 13m
    ublock-abuse: 77-0, 13m
    ublock-badware: 4251-112, 13m
    ublock-filters: 31638-497, 13m
    ublock-privacy: 258-6, 13m
    ublock-quick-fixes: 456-19, 13m
    ublock-unbreak: 1921-48, 13m
    urlhaus-1: 6825-0, 13m
filterset (user): [array of 5 redacted]
trustedset: 
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 315 ms (selfie)
  maxAssetCacheWait: 433 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    embodyopenlyoppose.com: 1
    google.com: 1
    youtube.com: 3
```
</details>

**Comment by mapx-** [comment]
- You have to use a slovak / czech ip
- enable the regional list too (CZE, SVK: EasyList Czech and Slovak)
- I added a filter in unbreak list to kill a bad filter from CZE, SVK: EasyList Czech and Slovak => update unbreak list
