### ISSUE TITLE
techcyan.com: detection

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#16278]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://techcyan.com/apple-airpods-pro-offer/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 100221
  cosmetic: 59620
  scriptlet: 17969
  html: 868
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    ublock-filters: 32381-54, 21h.29m
    ublock-badware: 4255-0, 21h.28m
    ublock-privacy: 305-0, 4d.21h.32m
    ublock-abuse: 77-0, 4d.21h.32m
    ublock-unbreak: 1933-3, 21h.27m
    ublock-quick-fixes: 462-0, 16h.47m
    easylist: 61312-632, 4d.21h.32m
    easyprivacy: 30868-1738, 4d.21h.32m
    urlhaus-1: 6825-0, 16h.47m
    plowe-0: 3671-2, 4d.21h.32m
    RUS-0: 39357-159, 18h.4m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1316 ms (selfie)
  maxAssetCacheWait: 367 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    doubleclick.net: 7
    googletagmanager.com: 1
    ibb.co: 1
    kiktu.com: 1
    wp.com: 3
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16274

**Comment by mapx-** [comment]
update all your lists
