### ISSUE TITLE
Adblocker detected by mercurynews

### ISSUE THREAD

**Issue by LearZhou** [uBlockOrigin/uAssets#1627]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://www.mercurynews.com/2018/02/26/apple-plans-largest-iphone-ever-and-a-cheaper-alternative-with-iphone-x-features-report-says/]`

### Describe the issue

["LOOKS LIKE YOU ARE RUNNING AN AD BLOCKER" displayed, and the whole article not showed.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [Firefox 58.0.2 64-bit for windows]
- uBlock Origin version: [1.15.10]

### Settings

- [enabled 'Adblock Removal List' and 'CHN easy list']

### Notes

[]

**Comment by gorhill** [comment]
@@||mercurynews.com^$generichide

**Comment by LearZhou** [comment]
It doesn't work with recently published reports from www.mercurynews.com.

Would you please give me some hints on how to detect these tricks and apply
my own rules with uBlock?

**Comment by LearZhou** [comment]
Never mind, the rule you listed work on my windows 10 machine, not on my
other windows 8.1 computer, probably just configuration problem. I'll check
it out.
