### ISSUE TITLE
go.cnn.com: breakage

### ISSUE THREAD

**Issue by phanatic88888** [uBlockOrigin/uAssets#16276]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://go.cnn.com/?stream=cnn`

### Category

breakage

### Description

Will not play video with ad block enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 93
filterset (summary): 
  network: 83003
  cosmetic: 38761
  scriptlet: 16769
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 6-0, never
    easylist: 61199-44, 5d.9m
    easyprivacy: 30868-1171, 5d.8m
    plowe-0: 3671-900, 4d.13h.2m
    ublock-abuse: 77-0, 8d.10h.9m
    ublock-badware: 4251-111, 21h.38m
    ublock-filters: 31580-121, 21h.37m
    ublock-privacy: 257-1, 8d.10h.8m
    ublock-quick-fixes: 456-18, 11h.38m
    ublock-unbreak: 1920-45, 21h.36m
    urlhaus-1: 6825-0, 11h.37m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6492 ms (selfie)
  maxAssetCacheWait: 3342 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    cnn.com: 5
    adsafeprotected.com: 1
    amazon-adsystem.com: 3
    bounceexchange.com: 1
    chartbeat.com: 1
    doubleclick.net: 1
    imrworldwide.com: 1
    krxd.net: 1
    ml314.com: 1
    ngtv.io: 1
    scorecardresearch.com: 1
    turner.com: 1
    wmcdp.io: 3
```
</details>

**Comment by okiehsch** [comment]
Does adding 
`@@||mssl.fwmrm.net/libs/*$script,domain=go.cnn.com`
to your filter llist fix the issue?

**Comment by gorhill** [comment]
This filter fixes the issue on my side.

**Comment by phanatic88888** [comment]
It fixes the video issue but it doesnt block the ads
