### ISSUE TITLE
[nsfw] newsongs.co.in: ads

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#16284]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://newsongs.co.in/category/tech/page/2/`

### Category

ads

### Description

Can you create bypass rule for this site plz

### Screenshot(s)
https://user-images.githubusercontent.com/96541364/211250114-e2030758-1e37-47ce-8adc-74afe549b2f0.jpg

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 82965
  cosmetic: 122228
  scriptlet: 21672
  html: 983
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    fanboy-annoyance: 84753-476, 3h.11m
    ublock-annoyances: 4742-4, 3h.11m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32550-88, 3h.11m
    ublock-badware: 4281-0, 3h.11m
    ublock-privacy: 305-0, 3h.11m
    ublock-abuse: 77-0, 3h.11m
    ublock-unbreak: 1940-3, 3h.11m
    ublock-quick-fixes: 468-0, 3h.11m
    adguard-mobile: 8440-11, 3h.13m
    easylist: 61744-483, 3h.11m
    easyprivacy: 30893-1186, 3h.11m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1621 ms (selfie)
  maxAssetCacheWait: 627 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    newsongs.co.in: 8
    connatix.com: 1
    doubleclick.net: 1
    ezodn.com: 1
    ezoic.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
Which is the original shortener link ?

**Comment by MayaBi7** [comment]
https://hubcloud.work/drive/4qby1t46ci9ytyv

**Comment by mapx-** [comment]
I get only `technorozen.com` and no issue here to get the mkv final file / download link

> Can you create bypass rule for this site plz

if you mean skipping the various steps / countdowns to get directly the final download => not possible without some userscript dedicated to this goal

**Comment by MayaBi7** [comment]
Yup! I mean skiping the countdown 👍

**Comment by MayaBi7** [comment]
Showing invalid! but nice try though 👍
