### ISSUE TITLE
kissanime.com.ru: detection

### ISSUE THREAD

**Issue by Yashasewi** [uBlockOrigin/uAssets#16287]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kissanime.com.ru/Anime/One-Piece.54191/Episode-1046?id=181917&s=hserver`

### Category

detection

### Description

this site can detect adblock and because of this the video player is not playing until ad blocker is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Watch One Piece Episode 1046 Online Free _ KissAnime — Firefox Developer Edition 09-01-2023 01_43_01 PM](https://user-images.githubusercontent.com/32950332/211264546-5bfaef23-02fa-4e10-80da-f4c4e2ab5961.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 86939
  cosmetic: 38571
  scriptlet: 16780
  html: 858
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32297-52, 3d.20h.48m
    ublock-badware: 4250-0, 3d.1h.41m
    ublock-privacy: 305-0, 1d.22h.44m
    ublock-abuse: 77-0, 1d.22h.43m
    ublock-unbreak: 1928-3, 3d.1h.40m
    ublock-quick-fixes: 468-0, 12h.41m
    easylist: 64993-625, 3d.20h.50m
    easyprivacy: 30906-1709, 3d.20h.49m
    urlhaus-1: 6814-0, 12h.40m
    plowe-0: 3668-2, 20h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 15 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 568 ms (selfie)
  maxAssetCacheWait: 317 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    kissanime.com.ru: 9
    bebi.com: 2
    demand.supply: 2
    disqus.com: 2
    facebook.com: 1
    google.com: 1
    googletagmanager.com: 1
    rezync.com: 1
```
</details>

**Comment by ghajini** [comment]
try only with ublock origin enabled,disable other addons

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by Yashasewi** [comment]
i tried but still it detect adblock

**Comment by Yashasewi** [comment]
i dont know how but it is working .
