### ISSUE TITLE
arsiv.mackolik.com: detection

### ISSUE THREAD

**Issue by burhan1961** [uBlockOrigin/uAssets#16286]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://arsiv.mackolik.com/Canli-Sonuclar`

### Category

detection

### Description

Accept Cookies section does not work when uBlock is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![mackolik accept cookies bug](https://user-images.githubusercontent.com/46867065/211261449-796b8520-e4d8-429f-aff1-3a3e9524c446.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 85017
  cosmetic: 48470
  scriptlet: 18016
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 15-0, never
    TUR-0: 12623-11, 3d.14h.8m
    easylist: 61608-64, 2d.8h.33m
    easyprivacy: 30884-1176, 2d.8h.32m
    plowe-0: 3671-901, 4d.21h.40m
    ublock-abuse: 77-0, 5d.19h.6m
    ublock-badware: 4239-111, 3d.14h.10m
    ublock-filters: 31571-133, 3d.14h.9m
    ublock-privacy: 257-1, 5d.19h.5m
    ublock-quick-fixes: 456-19, 14h.27m
    ublock-unbreak: 1915-45, 3d.14h.11m
    urlhaus-1: 6814-0, 14h.28m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 279 ms (selfie)
  maxAssetCacheWait: 216 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    mackolik.com: 1
    admost.com: 2
    cdn.md: 1
    d3avqv6zaxegeu.cloudfront.net: 1
    dimml.io: 1
    gemius.pl: 1
    google-analytics.com: 2
    hotjar.com: 1
    scorecardresearch.com: 1
    virgul.com: 1
```
</details>

**Comment by 96273** [comment]
`https://arsiv.mackolik.com/Mac/4308588/Fenerbahce-Caykur-Rizespor`

I discovered a heavily obfuscated JavaScript malware loader that injects a tracking script from fontscanvas.com. It collects visitor data (referrer, title, URL, etc.) and dynamically loads additional payload using localStorage and window config. VirusTotal flagged this script as malware by multiple antivirus engines.

Please add it to the badware/malware filters. `||adxxxxxmost.co^`

Script: `https://run.adxxxxxmost.co/adx/get.ashx?k=55002&preredir={amClickThru}`


<details><summary>Image</summary>

<img width="1354" height="768" alt="Image" src="https://github.com/user-attachments/assets/6860290d-1d09-4804-877d-a87932000d81" />

</details>
