### ISSUE TITLE
onlineservice.ewr-gmbh.de: breakage

### ISSUE THREAD

**Issue by RubenKelevra** [uBlockOrigin/uAssets#16289]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://onlineservice.ewr-gmbh.de/ewr/`

### Category

breakage

### Description

Webpage ends loading and Firefox shows just a white page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 110
filterset (summary): 
  network: 99014
  cosmetic: 123722
  scriptlet: 23985
  html: 983
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62139-4163, 1d.18h.54m
    fanboy-annoyance: 84582-63069, 7d.4h.50m
    fanboy-cookiemonster: 44433-17377, 8d.52m
    ublock-annoyances: 4746-8, 15h.7m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32472-312, 2d.21h.37m
    ublock-badware: 4254-0, 2d.2h.21m
    ublock-privacy: 307-1, 3d.21h.29m
    ublock-abuse: 77-0, 3d.21h.30m
    ublock-unbreak: 1940-2, 15h.8m
    adguard-mobile: 8440-175, 15h.6m
    easylist: 61692-17875, 1d.4h.16m
    easyprivacy: 30891-1759, 23h.14m
    urlhaus-1: 6868-0, 46m
    plowe-0: 3671-2, 5d.2h.24m
    DEU-0: 6091-384, 23h.13m
    ublock-quick-fixes: 398-0, 23h.12m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2326 ms (selfie)
  maxAssetCacheWait: 234 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add & test

`@@||onlineservice.ewr-gmbh.de/ui.components.extended/material/nli-cookie-banner/$script,1p`

**Comment by mapx-** [comment]
@ryanbr
