### ISSUE TITLE
myaccount.payoneer.com: breakage

### ISSUE THREAD

**Issue by rollsch** [uBlockOrigin/uAssets#16282]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://myaccount.payoneer.com/ma/pay/online`

### Category

breakage

### Description

Clicking "PAY" just causes nothing to happen. This is an online payment gateway for paying people internationally.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1109554/211230571-12c7e47d-e05f-4300-bf47-0c237326a916.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83018
  cosmetic: 38761
  scriptlet: 16781
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61199-44, 4d.22h.31m
    easyprivacy: 30868-1171, 4d.22h.30m
    plowe-0: 3672-898, 12d.22h.13m
    ublock-abuse: 77-0, 2h.28m
    ublock-badware: 4276-111, 2h.27m
    ublock-filters: 31594-121, 2h.26m
    ublock-privacy: 258-1, 2h.29m
    ublock-quick-fixes: 456-19, 2h.24m
    ublock-unbreak: 1922-45, 2h.25m
    urlhaus-1: 6814-0, 2h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1076 ms
  maxAssetCacheWait: 723 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    payoneer.com: 1
    googletagmanager.com: 1
    sift.com: 1
```
</details>

**Comment by rollsch** [comment]
Unsure if this meets the "I did not enable external filter lists" option or not.

![image](https://user-images.githubusercontent.com/1109554/211230697-9722eb9a-147b-425f-a00d-0401959f44b5.png)

**Comment by mapx-** [comment]
Does this help ?

`@@||payoneer.com/*ruxitagentjs$script,1p`
