### ISSUE TITLE
diziyou.co: ads

### ISSUE THREAD

**Issue by erdemmolmez** [uBlockOrigin/uAssets#16291]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.diziyou.co/breaking-bad-1-sezon-1-bolum/`

### Category

ads

### Description

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83440
  cosmetic: 38800
  scriptlet: 16769
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 8-4, never
    easylist: 61679-46, 2d.4h.37m
    easyprivacy: 30888-1171, 2d.4h.36m
    plowe-0: 3671-901, 5d.8h.52m
    ublock-abuse: 77-0, 7d.5h.47m
    ublock-badware: 4251-112, 2d.4h.35m
    ublock-filters: 31580-124, 2d.29m
    ublock-privacy: 258-1, 7d.5h.46m
    ublock-quick-fixes: 456-19, 1d.43m
    ublock-unbreak: 1915-45, 2d.4h.33m
    urlhaus-1: 6814-0, 23h.57m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 246 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 4
  no-popups: true
  blockedDetails: 
    diziyou.co: 2
    adform.net: 1
    googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `TUR: AdGuard Turkish`
