### ISSUE TITLE
mp3clan.one

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1629]
### URL(s) where the issue occurs

`http://mp3clan.one/mp3/enya_may_it_be.html`

### Describe the issue

Popup

### Versions

- Browser/version: Chrome 64.0.3282.167
- uBlock Origin version: v1.15.2

### Settings
Default settings

### Notes
These 3 help, but you might add more filters.
```
||cowledges.com^$third-party,popup
||squartedo.info*
||whistorica.info*
```

**Comment by SMed79** [comment]
@mapx- https://github.com/easylist/easylist/commit/0704863caf22a7234fd3228ea1ce03b4528b0113#commitcomment-27824092
