### ISSUE TITLE
warning.or.kr: nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#16297]
`http://warning.or.kr/`

Blocked right click (maybe possible fix without user.js solution - I don't detected @[piquark6046](https://github.com/List-KR/List-KR/commits?author=piquark6046) or @[green1052](https://github.com/List-KR/List-KR/issues?q=is%3Aissue+is%3Aopen+author%3Agreen1052) address in AdGuard Annoyances)

**Comment by mapx-** [comment]
another case when `:remove-attr` does not work ?!
`warning.or.kr##body:remove-attr(oncontextmenu)`

**Comment by krystian3w** [comment]
Works in Firefox 109 + uBo Dev, on stable maybe needed inject attr in brackets as selector:

```adb
warning.or.kr##body[oncontextmenu]:remove-attr(oncontextmenu)
```

Then fail is rare.

**Comment by krystian3w** [comment]
I'm rather not concerned with what "world" javascript removes the class/attribute.

**Anecdotal** evidence of quality:

Somewhere I tested and deletion in the stable version started only when I explicitly specified the attribute in parentheses.

I don't think I have a url or filter syntax anywhere to do more tests, whether it's a limitation of "worlds" or a bug accidentally fixed in the development cycle.

Then you can at most throw it into your discussion thread (it is unlikely to report an (unique) issue).
