### ISSUE TITLE
yandex.ru: breakage

### ISSUE THREAD

**Issue by 20052312** [uBlockOrigin/uAssets#16293]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yandex.ru/images/search?text=%D0%B0%D0%BB%D1%8F%D1%81%D0%BA%D0%B0`

### Category

breakage

### Description

The site is broken when working with Ublock origin (hover does not work, the interface is broken)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 107414
  cosmetic: 170659
  scriptlet: 25254
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62140-492, 20h.17m
    adguard-social: 19493-833, 20h.16m
    fanboy-cookiemonster: 44431-3401, 9d.27m
    ublock-annoyances: 4715-192, 20h.18m
  default: 
    user-filters: 0-0, never
    RUS-0: 39343-12, 2d.1h.2m
    easylist: 61679-115, 2d.20h.38m
    easyprivacy: 30884-1341, 2d.20h.37m
    plowe-0: 3669-906, 8d.3h.25m
    ublock-abuse: 77-1, 9d.20h.33m
    ublock-badware: 4045-109, 20h.21m
    ublock-filters: 31523-538, 20h.20m
    ublock-privacy: 260-3, 9d.20h.32m
    ublock-quick-fixes: 465-15, 2h.31m
    ublock-unbreak: 1922-48, 20h.19m
    urlhaus-1: 6868-0, 2h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8702 ms (selfie)
  maxAssetCacheWait: 1210 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    yandex.ru: 13
    yandex.net: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
Try restoring default settings in uBlock Origin. Will this solve the problem?
