### ISSUE TITLE
leedsunited.news: breakage

### ISSUE THREAD

**Issue by KarlG1965** [uBlockOrigin/uAssets#16290]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.leedsunited.news/news/ally-mccoist-posts-brilliant-picture-with-leeds-legend-robbie-keane-responds/`

### Category

breakage

### Description

The page doesn't load correctly when uBlock is enabled. If I deactivate uBlock I can see the page (sadly with loads of ads as well)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.1b8
Firefox: 108
filterset (summary): 
  network: 85666
  cosmetic: 43170
  scriptlet: 16764
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 560-13, never
    ublock-filters: 32366-65, 2d.13h.5m
    ublock-badware: 4255-0, 2d.13h.4m
    ublock-privacy: 305-0, 5d.21h.8m
    ublock-abuse: 77-0, 5d.21h.7m
    ublock-unbreak: 1928-3, 2d.13h.3m
    easylist: 61678-630, 23h.32m
    easyprivacy: 30891-1749, 23h.31m
    urlhaus-1: 6814-0, 23h.30m
    plowe-0: 3671-2, 3d.11h.23m
    DEU-0: 6091-2, 23h.29m
    ublock-quick-fixes: 462-0, 23h.28m
filterset (user): [array of 560 redacted]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  hyperlinkAuditingDisabled: false
  showIconBadge: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1861 ms (selfie)
  maxAssetCacheWait: 203 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    leedsunited.news: 1
    adlightning.com: 1
    ampproject.org: 1
    criteo.net: 4
    doubleclick.net: 1
    gstatic.com: 2
    instagram.com: 1
    primis.tech: 4
    quantserve.com: 1
    revcontent.com: 1
    rlcdn.com: 1
```
</details>

**Comment by mapx-** [comment]
What exactly is missing on your side ? upload a screenshot pointing out the missing parts

**Comment by KarlG1965** [comment]
Here are two screenshots, one with and the other without uBlock. As you can see, the content isn't loading when uBlock is active

![grafik](https://user-images.githubusercontent.com/39383053/211356626-8d5b9a6a-99ca-4767-99db-9d3aa03118c6.png)

![grafik](https://user-images.githubusercontent.com/39383053/211356525-b6964759-fa87-4832-920a-93df475050c3.png)

**Comment by mapx-** [comment]
> user-filters: 560-13, never

maybe you have some custom bad filters ?

**Comment by KarlG1965** [comment]
Yes, good shout. I removed all my custom filters and reloaded the page and now it's working as expected with uBlock active. It's strange, because I don't have any custom filters for that particular site,  but obviously one of my other filters is having unintended side-effects.

Thanks for your quick replies and keep up the good work :-)
