### ISSUE TITLE
sezonlukdizi.com

### ISSUE THREAD

**Issue by intensivefootcream** [uBlockOrigin/uAssets#1630]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[http://sezonlukdizi.net/altered-carbon/1-sezon-9-bolum.html]`

### Describe the issue

[When "uBlock Filters" is selected from 3rd-party filters, subtitles (CC) of the videos are blocked too.]

### Versions

- Browser/version: [Any browser]
- uBlock Origin version: [1.15.10]

### Settings

- [All selected except regionals, adguard mobile and ublock experimental]

**Comment by okiehsch** [comment]
Fixed by removing the filter
`rapidvideo.com##script:inject(abort-on-property-write.js, decodeURIComponent)`

**Comment by intensivefootcream** [comment]
how will I remove it?

**Comment by okiehsch** [comment]
I have removed it int the commit mentioned above
"closed this in 2b86a5f"
You only have to update your uBlock filters list.

**Comment by intensivefootcream** [comment]
thank you @okiehsch
