### ISSUE TITLE
bankrate.com: breakage

### ISSUE THREAD

**Issue by ngopaul** [uBlockOrigin/uAssets#16304]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bankrate.com/banking/savings/rates/`

### Category

breakage

### Description

Apparently, CSS is blocked on this webpage (everything is not formatted properly).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

This is one section of the webpage with apparently no CSS (the home button is high quality, so it takes up the whole first part of the page)

![image](https://user-images.githubusercontent.com/19920559/211750050-8b3a1c70-b6b7-4ca0-811f-fef1821844b0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83357
  cosmetic: 38800
  scriptlet: 16790
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61692-46, 2d.11h
    easyprivacy: 30908-1174, 2d.10h.59m
    plowe-0: 3668-870, 2d.10h.58m
    ublock-abuse: 77-0, 2d.10h.56m
    ublock-badware: 4045-109, 2d.10h.54m
    ublock-filters: 31594-124, 2d.10h.53m
    ublock-privacy: 258-1, 2d.10h.52m
    ublock-quick-fixes: 465-16, 9h.45m
    ublock-unbreak: 1922-45, 2d.10h.50m
    urlhaus-1: 6868-0, 9h.44m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 732 ms
  maxAssetCacheWait: 119 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    bankrate.com: 6
    cohesionapps.com: 7
    googletagmanager.com: 2
    newrelic.com: 1
    nr-data.net: 2
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||cohesion.bankrate.com/cohesion/cohesion-latest.min.js$script,1p`
fixes the issue.
The site is completely broken, so I will add it to unbreak for now.

**Comment by okiehsch** [comment]
@ngopaul 
After updating the `uBO-unbreak` list the site should work as expected.
