### ISSUE TITLE
mobile01.com: breakage

### ISSUE THREAD

**Issue by Yoshinosido** [uBlockOrigin/uAssets#16302]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mobile01.com/forumtopic.php?c=19`

### Category

breakage

### Description

If enable the ad block and few moments later, the any element on this site can't click.

I test when disable the ad block,
after few moments later this site will pop up an always on top window,
and the ad block will remove the always on top window, 
if don't close the always on top window, it will block any click action.
when refreshing the site the always on top window disappears then again normal use.

But enable the ad block can't see the always on top window's close button.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 144851
  cosmetic: 162060
  scriptlet: 35795
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62209-101, 23h.7m
    adguard-generic: 67260-540, 4h.55m
    adguard-mobile: 8444-65, 23h.12m
    adguard-social: 19513-827, 23h.15m
    adguard-spyware: 36143-4365, 23h.13m
    ublock-annoyances: 4716-185, 23h.8m
    ublock-quick-fixes: 465-48, 4h.54m
  default: 
    user-filters: 5-1, never
    CHN-0: 28188-103, 23h.14m
    easylist: 61692-1176, 2d.11h.48m
    easyprivacy: 30891-12381, 2d.11h.49m
    plowe-0: 3669-1066, 9d.1h.20m
    ublock-abuse: 77-0, 10d.5h.19m
    ublock-badware: 4287-305, 23h.10m
    ublock-filters: 31603-3862, 23h.11m
    ublock-privacy: 257-47, 10d.5h.16m
    ublock-unbreak: 1925-107, 23h.9m
    urlhaus-1: 6868-0, 4h.53m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1185 ms (selfie)
  maxAssetCacheWait: 677 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 4
```
</details>

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
