### ISSUE TITLE
sozcu.com.tr: nuisance

### ISSUE THREAD

**Issue by sanigerson** [uBlockOrigin/uAssets#16306]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sozcu.com.tr/`

### Category

nuisance

### Description

Blocking thing that shouldn't be blocked. Screenshot taken from nonblocked Edge browser since even disabling ublock, it still blocks.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![sozcu](https://user-images.githubusercontent.com/94021014/211760345-d31c2c64-79a8-4f33-ae99-159ecde6200b.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 85424
  cosmetic: 47930
  scriptlet: 17842
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 11794-11, 39m
    easylist: 61904-65, 39m
    easyprivacy: 30910-1176, 39m
    plowe-0: 3668-901, 39m
    ublock-abuse: 77-0, 39m
    ublock-badware: 4292-113, 39m
    ublock-filters: 31682-134, 39m
    ublock-privacy: 258-1, 39m
    ublock-quick-fixes: 465-23, 39m
    ublock-unbreak: 1918-47, 39m
    urlhaus-1: 6868-0, 39m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 341 ms (selfie)
  maxAssetCacheWait: 199 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    doubleclick.net: 1
    gemius.pl: 1
    google-analytics.com: 2
    googletagmanager.com: 2
    membrana.media: 1
    onesignal.com: 1
    sozcucdn.com: 1
    taboola.com: 2
```
</details>

**Comment by okiehsch** [comment]
So your saying that the dollar exchange rate is blocked on your end with uBO-enabled?

If that's your issue I can't reproduce,

![image](https://user-images.githubusercontent.com/16838044/211763616-7a1c78e3-24d7-499e-80cf-9e91147013c8.png)

**Comment by sanigerson** [comment]
Yes, dollar exchange rate is blocked. Try to refresh in 1 to 2 hours later because it doesn't happen always.
What is your browser also? I tried to clear my cache but still same with ublock. If i reset my browser and uninstall ublock, everything is fine.

**Comment by krystian3w** [comment]
> since even disabling ublock, it still blocks.

Try then <kbd>Ctrl</kbd>/<kbd>Command</kbd> + <kbd>F5</kbd> or <kbd>Ctrl<kbd>/<kbd>Command</kbd> + <kbd>R</kbd> to omit glitched cache.

**Comment by okiehsch** [comment]
> What is your browser also?

I tried with Chrome and Edge with the same result.

> Try to refresh in 1 to 2 hours later because it doesn't happen always.

Well, that sounds more like a site issue.

**Comment by okiehsch** [comment]
At the moment it works without issue on my end.

**Comment by sanigerson** [comment]
![sozcu2](https://user-images.githubusercontent.com/94021014/211777331-73659fc7-f102-4755-81b5-23da87703e6e.jpg)

This is my screen

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/211777554-94bbee1d-8ee1-4441-9e56-1789ae0b72bc.png)

**Comment by stephenhawk8054** [comment]
Works fine for me too

![image](https://user-images.githubusercontent.com/66517106/211793845-71a9fe75-f70a-446b-94a7-ea0c587aaebb.png)

Maybe geo-related?

**Comment by krystian3w** [comment]
Also try use dom inspector and/or eye button to exclude cosmetic filtering:

https://github.com/gorhill/uBlock/wiki/DOM-inspector
https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering

To detect bad network filters or scriplets maybe logger output:

https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output
https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog
