### ISSUE TITLE
writedroid.eu.org: detection

### ISSUE THREAD

**Issue by yashzade** [uBlockOrigin/uAssets#16305]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.writedroid.eu.org/`

### Category

detection

### Description

Ad blocker detected 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230111_142425_Kiwi Browser](https://user-images.githubusercontent.com/42665606/211761468-a4344db8-e29e-4ea9-8548-1f2bd7e8d6e7.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 85248
  cosmetic: 28220
  scriptlet: 16869
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-1, never
    adguard-mobile: 8447-27, 1m
    easylist: 61904-17351, now
    easyprivacy: 30910-1182, now
    plowe-0: 3668-984, now
    ublock-abuse: 77-0, now
    ublock-badware: 4291-114, now
    ublock-filters: 31791-367, now
    ublock-privacy: 258-2, now
    ublock-quick-fixes: 465-23, now
    ublock-unbreak: 1924-49, now
    urlhaus-1: 6868-0, now
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 402 ms (selfie)
  maxAssetCacheWait: 233 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googlesyndication.com: 4
    googletagmanager.com: 1
```
</details>

**Comment by yashzade** [comment]
Still Ad blocker detected from chrome desktop

**Comment by yashzade** [comment]
starting link to the website - https://privatemoviez.best/secret/?data=SXNyblMvbW5YSllFUjgyci9lUFloSVEyY2RFMGlaYXZMMDRDZUhZbmFqMD06OlUgYa3ri_s_kPZBLeOSTjwdQ_e_

**Comment by okiehsch** [comment]
If the issue involvesa link shortener we always need the starting point.

Does it work if you add 
`@@||writedroid.*^$ghide`
to your filter list?

**Comment by yashzade** [comment]
> 

Yes
