### ISSUE TITLE
elnuevodia.com: breakage

### ISSUE THREAD

**Issue by Hallelujah3** [uBlockOrigin/uAssets#16303]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.elnuevodia.com/entretenimiento/television/fotogalerias/golden-globes-reina-el-brillo-y-la-elegancia-en-la-alfombra-roja-de-los-premios/`

### Category

breakage

### Description

When uBlockOrigin is enabled, the pictures are not showing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83301
  cosmetic: 38785
  scriptlet: 16787
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 61466-45, 5d.11h.31m
    easyprivacy: 30880-1171, 5d.11h.32m
    plowe-0: 3671-900, 8d.2h.22m
    ublock-abuse: 77-0, 11d.15h.13m
    ublock-badware: 4251-111, 3d.1h.25m
    ublock-filters: 31592-123, 3d.1h.27m
    ublock-privacy: 257-1, 11d.15h.12m
    ublock-quick-fixes: 465-15, 5h.12m
    ublock-unbreak: 1921-45, 3d.1h.26m
    urlhaus-1: 6868-0, 2h.7m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 269 ms (selfie)
  maxAssetCacheWait: 110 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    aswpsdkus.com: 1
    datadoghq.com: 1
    go-mpulse.net: 2
    googletagmanager.com: 1
    spot.im: 18
```
</details>

**Comment by Procyon-b** [comment]
Try this filter:
```
@@||www.googletagmanager.com/gtm.js$domain=elnuevodia.com
```

**Comment by stephenhawk8054** [comment]
@ryanbr
