### ISSUE TITLE
hi.ru: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#16308]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hi.ru/`

### Category

breakage

### Description

automatic scrolling up when ubo active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 125435
  cosmetic: 142052
  scriptlet: 24700
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7780-3, 1m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-4, 1m
    IDN-0: 5422-356, 1m
    RUS-0: 39374-52, 1m
    adguard-spyware: 36156-3654, 1m
    fanboy-annoyance: 84907-404, 1m
    fanboy-cookiemonster: 44716-44716, 1m
    ublock-annoyances: 4719-82, 1m
  default: 
    user-filters: 20-0, never
    easylist: 61904-103, 1m
    easyprivacy: 30911-12268, 1m
    ublock-abuse: 77-1, 1m
    ublock-badware: 4292-112, 1m
    ublock-filters: 31694-479, 1m
    ublock-privacy: 258-51, 1m
    ublock-quick-fixes: 466-23, 1m
    ublock-unbreak: 1920-70, 1m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 24 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 19148 ms (selfie)
  maxAssetCacheWait: 1211 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    cpmstar.com: 1
    criteo.net: 1
    googlesyndication.com: 2
    scorecardresearch.com: 1
    tns-counter.ru: 1
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
to be removed from EL ? @ryanbr 

`##div[id^="crt-"][style]`

**Comment by dportvine** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This is a russian site, and corrections for it should be contained in RU AdList: https://github.com/easylist/ruadlist/commit/cc2d7b21ac053fb6344153087a35084f8fcd7eda

`##div[id^="crt-"][style]` - no need to delete, this rule does a lot of useful work.
