### ISSUE TITLE
anwb.nl: breakage

### ISSUE THREAD

**Issue by frankknarf** [uBlockOrigin/uAssets#16318]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.anwb.nl/verzekeringen/reisverzekering/wintersportverzekering`

### Category

breakage

### Description

The scrollbar is gone. I can't scroll down any more

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 86191
  cosmetic: 80496
  scriptlet: 18636
  html: 866
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 43650-157, 8d.16h.46m
  default: 
    user-filters: 9-1, never
    ublock-filters: 32409-38, 1d.11h.10m
    ublock-badware: 4291-0, 1d.11h.9m
    ublock-privacy: 305-0, 1d.11h.15m
    ublock-abuse: 77-0, 1d.11h.14m
    ublock-unbreak: 1933-3, 1d.11h.8m
    easylist: 61904-649, 1d.11h.13m
    easyprivacy: 30910-1745, 1d.11h.12m
    urlhaus-1: 6868-0, 8m
    plowe-0: 3671-2, 8d.16h.48m
    NLD-0: 2527-55, 1d.11h.11m
    ublock-quick-fixes: 472-17, 7m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2692 ms (selfie)
  maxAssetCacheWait: 562 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 1
    newrelic.com: 1
    optimizely.com: 3
```
</details>

**Comment by krystian3w** [comment]
Try without fanboy-cookiemonster.

**Comment by mapx-** [comment]
update all your filter lists, already fixed by Easylist cookie
