### ISSUE TITLE
blog.cryptowidgets.net: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#16313]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.cryptowidgets.net/post/what-is-bitcoin`

### Category

detection

### Description

Adblocker Detected.....

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83536
  cosmetic: 38807
  scriptlet: 16801
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 12-0, never
    easylist: 61679-46, 4d.5h.20m
    easyprivacy: 30891-1171, 4d.5h.19m
    plowe-0: 3669-899, 10d.20h.39m
    ublock-abuse: 77-0, 12d.15h.55m
    ublock-badware: 4287-112, 1d.21h.10m
    ublock-filters: 31603-124, 2d.5h.40m
    ublock-privacy: 257-1, 12d.15h.54m
    ublock-quick-fixes: 465-22, 8m
    ublock-unbreak: 1922-45, 2d.5h.39m
    urlhaus-1: 6868-0, 7m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 24463 ms (selfie)
  maxAssetCacheWait: 4260 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    a-ads.com: 1
    adapex.io: 1
    d3u598arehftfk.cloudfront.net: 1
    demand.supply: 1
    doubleclick.net: 1
    filetstaipo.com: 1
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 2
    surfe.pro: 2
    wtg-ads.com: 2
    www.googleapis.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter litsts and test again?
