### ISSUE TITLE
sozcu.com.tr: detection

### ISSUE THREAD

**Issue by leysivle** [uBlockOrigin/uAssets#16314]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sozcu.com.tr/`

### Category

detection

### Description

This site detected ublock origin and redirect other page. Image attached.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://user-images.githubusercontent.com/122460777/212055070-4dca75a9-5ca6-4ba1-b5f0-dbb53b47f71f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 85181
  cosmetic: 47630
  scriptlet: 17808
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 11540-11, 2d.6h.3m
    easylist: 61679-65, 3d.16h.25m
    easyprivacy: 30888-1176, 3d.16h.24m
    plowe-0: 3671-902, 6d.20h
    ublock-abuse: 77-0, 8d.3h.32m
    ublock-badware: 4287-112, 2d.6h.2m
    ublock-filters: 31603-133, 2d.6h
    ublock-privacy: 258-1, 8d.3h.31m
    ublock-quick-fixes: 466-23, 2h.34m
    ublock-unbreak: 1911-45, 2d.5h.59m
    urlhaus-1: 6868-0, 2h.33m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1552 ms (selfie)
  maxAssetCacheWait: 614 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    sozcucdn.com: 1

```
</details>

**Comment by okiehsch** [comment]
Update the AdGuard Turkish list it has been fixed 2 days ago.

**Comment by BlocksAds** [comment]
By the way, from the screenshot it looks like you had Opera's ad + tracker capabilities enabled on the web page. Using third-party content blockers may affect uBO's anti-anti-ad-blocking capabilities.
