### ISSUE TITLE
arcadepunks.com: detection

### ISSUE THREAD

**Issue by gj98awsm** [uBlockOrigin/uAssets#16316]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.arcadepunks.com/`

### Category

detection

### Description

The ad block is detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/63322332/212213554-fc334f7e-1b13-46de-b326-26014335552c.png">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83706
  cosmetic: 38832
  scriptlet: 16797
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61844-46, 17h.11m
    easyprivacy: 30917-1171, 17h.10m
    plowe-0: 3669-900, 17h.12m
    ublock-abuse: 77-0, 2d.17h.13m
    ublock-badware: 4287-113, 2d.17h.16m
    ublock-filters: 31605-125, 2d.17h.15m
    ublock-privacy: 258-1, 2d.17h.12m
    ublock-quick-fixes: 473-22, 4m
    ublock-unbreak: 1925-45, 2d.17h.14m
    urlhaus-1: 6868-0, 21h.14m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 726 ms (selfie)
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    arcadepunks.com: 2
    facebook.com: 1
    googlesyndication.com: 3
    truepush.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Force update your filter lists and check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by einstein95** [comment]
The only detection they use was solved by 606e65eb350d8cb9f423a347aeaf7fc2b29e10e2 which is why it can't be reproduced.

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by timekills** [comment]
I've done all above (including cleared cache/cookies for the site vice ALL cookies/cache - but that was as per instructions.)
Unchecked the auto-update in uBO, cleared all uBO caches and redownloaded updates.
Ensured ALL security blocks in Edge are disabled - including some that have likely no impact (i.e. image enhancement.)
It still is detecting the blocker us MS Edge.
![Screenshot 2023-02-05 223805](https://user-images.githubusercontent.com/3918587/216847601-1a7373eb-8194-4d10-8b3d-bbf81588722b.png)
[ArcadePunks_uBO_detect_log.txt](https://github.com/uBlockOrigin/uAssets/files/10613895/ArcadePunks_uBO_detect_log.txt)

**Comment by john-clark** [comment]
![Image](https://github.com/user-attachments/assets/44ff0a70-7869-442c-b3da-37c48be83225)
