### ISSUE TITLE
blog.coinsvalue.net: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#16317]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.coinsvalue.net/post/what-is-bitcoin`

### Category

detection

### Description

Adblocker detected....

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83537
  cosmetic: 38807
  scriptlet: 16801
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 12-0, never
    easylist: 61679-46, 5d.1h.59m
    easyprivacy: 30891-1171, 5d.1h.58m
    plowe-0: 3669-899, 11d.17h.19m
    ublock-abuse: 77-0, 1h.8m
    ublock-badware: 4287-112, 2d.17h.49m
    ublock-filters: 31603-124, 3d.2h.19m
    ublock-privacy: 258-1, 1h.7m
    ublock-quick-fixes: 465-22, 20h.47m
    ublock-unbreak: 1922-45, 3d.2h.18m
    urlhaus-1: 6868-0, 20h.46m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 15 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 27490 ms (selfie)
  maxAssetCacheWait: 2419 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    d3u598arehftfk.cloudfront.net: 1
    doubleclick.net: 1
    google.com: 2
    googletagmanager.com: 2
    rebindskayoes.com: 1
    surfe.pro: 2
    www.googleapis.com: 1
```
</details>

**Comment by king-iskan** [comment]
@ghajini @stephenhawk8054 
seems to have to be updated, when adblock is active. there are malfunctions. site blog.coinsvalue.net changed to coinsvalue.net/en. so the link can not be resolved.
you can try from first step original link this 
http://shortano.link/hi5lr7

**Comment by king-iskan** [comment]
> @ghajini @stephenhawk8054 seems to have to be updated, when adblock is active. there are malfunctions. site blog.coinsvalue.net changed to coinsvalue.net/en. so the link can not be resolved. you can try from first step original link this
> 
> `http://shortano.link/hi5lr7`

@JobcenterTycoon 
can u help for that issue. thanks

**Comment by JobcenterTycoon** [comment]
Try `freeoseocheck.com##+js(ra, disabled, #wait)`

**Comment by king-iskan** [comment]
> Try `freeoseocheck.com##+js(ra, disabled, #wait)`

not work, for step 2.
ok i will explain from first.
step 1 go to https://blog.freeoseocheck.com/ after klik continue and continue again, he will go to step 2 https://blog.coinsvalue.net/
for step 1 no malfunctions, but step 2 when adblock is active,which should stay at https://blog.coinsvalue.net/, instead goes to the site https://coinsvalue.net
but if adblock not active he not go to https://coinsvalue.net

**Comment by stephenhawk8054** [comment]
I cannot reproduce the anti-adb (aka redirecting to `https://coinsvalue.net`) both on chromium and firefox.

For the buttons' nuisance, test

```adb
||blog.freeoseocheck.com/post/$csp=style-src *
blog.freeoseocheck.com##.floating-banner
blog.freeoseocheck.com##a[href^="https://shortano.link"] ~ :not(center)
```

**Comment by king-iskan** [comment]
> I cannot reproduce the anti-adb (aka redirecting to `https://coinsvalue.net`) both on chromium and firefox.
> 
> For the buttons' nuisance, test
> 
> ```
> ||blog.freeoseocheck.com/post/$csp=style-src *
> blog.freeoseocheck.com##.floating-banner
> blog.freeoseocheck.com##a[href^="https://shortano.link"] ~ :not(center)
> ```

It's ok if cannot reproduce, 
For buttons work better

**Comment by king-iskan** [comment]
same condition, still redirect
![image](https://user-images.githubusercontent.com/120553425/228002065-62ae8ce1-6fa4-474a-a1c5-b6eb00efacfd.png)

**Comment by king-iskan** [comment]
Still same, cookinguide redirect

**Comment by stephenhawk8054** [comment]
I can't reproduce the redirect

**Comment by JobcenterTycoon** [comment]
Works fine for me

**Comment by king-iskan** [comment]
> I can't reproduce the redirect

I got a code that can block redirects, but can only be used on FF Android.  can you check the code and modify it so that it can be used in chrome or Chromium based android browsers?

**Comment by king-iskan** [comment]
> Works fine for me

Use in android or PC?

**Comment by stephenhawk8054** [comment]
> > Works fine for me
> 
> Use in android or PC?

You should specify that from beginning

**Comment by stephenhawk8054** [comment]
It doesn't redirect on Firefox android for me either

**Comment by king-iskan** [comment]
sorry, I found a problem on my FF, in my filter column there are lots of filters for that site.  maybe collide.  after i clean.  work well.
I'm so sorry.
