### ISSUE TITLE
lightnovelworld.com: detection

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#16326]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lightnovelworld.com/novel/divine-path-system-1323/chapter-381`

### Category

detection

### Description

self explanitory with screenshot 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-01-13 215730](https://user-images.githubusercontent.com/100969549/212418035-35413ac6-33ee-4a8e-8821-a901f9b69d96.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 227306
  cosmetic: 252709
  scriptlet: 39231
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/6_optimized.txt: 6357-109, 3d.4h.20m
    https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4252-4, 2d.3h.23m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 42-0, 7d.9h.53m
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, 2d.3h.22m
    https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, 2d.3h.21m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5619-1, 13d.2h.18m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-5, 2d.6h.26m
    https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, 2d.2h.25m
    https://raw.githubusercontent.com/nabble/semalt-blocker/master/domains/blocked: 2433-2, 2d.2h.24m
    https://winhelp2002.mvps.org/hosts.txt: 8730-63, 2d.2h.23m
    CHN-0: 28223-103, 3d.4h.15m
    JPN-1: 8704-12, 3d.4h.14m
    KOR-1: 4095-42, 23h.10m
    adguard-annoyance: 62276-126, 3d.4h.26m
    adguard-generic: 67267-726, 3d.4h.25m
    adguard-mobile: 8446-169, 3d.4h.24m
    adguard-social: 19531-828, 3d.4h.23m
    adguard-spyware: 36147-4744, 3d.4h.22m
    adguard-spyware-url: 881-2, 3d.4h.21m
    block-lan: 44-0, 1d.2h.29m
    [8 lists not shown]: [too many]
  default: 
    user-filters: 101-1, never
    DEU-0: 6137-2670, 23h.14m
    easylist: 62107-1629, 33m
    easyprivacy: 30922-12822, 32m
    plowe-0: 3671-1589, 9d.5h.31m
    ublock-abuse: 77-57, 10d.7h.51m
    ublock-badware: 4292-308, 3d.4h.18m
    ublock-filters: 31606-3950, 3d.4h.17m
    ublock-privacy: 258-85, 10d.7h.50m
    ublock-quick-fixes: 466-52, 23h.12m
    ublock-unbreak: 1923-116, 3d.4h.16m
    urlhaus-1: 6868-1, 23h.11m
filterset (user): [array of 101 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 36 redacted]
hostRuleset: 
  added: [array of 77 redacted]
urlRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2466 ms (selfie)
  maxAssetCacheWait: 736 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    quantcast.com: 1
    vntsm.com: 1
```
</details>

**Comment by mapx-** [comment]
fixed 2 hours ago, update all your lists

**Comment by big-cat-loaf** [comment]
oh sorry
