### ISSUE TITLE
vidoza.net [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1632]
URL(s) where the issue occurs

`https://vidoza.net/29g6oes3lk9i.html`

Describe the issue

ADS Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by ghajini** [comment]
double screen when ubo enabled
`https://vidoza.net/s2ign06fsgtj.html`
![Screenshot (9)](https://user-images.githubusercontent.com/20338483/58316087-67696080-7e30-11e9-92f1-744ef4faa3b9.png)

**Comment by mapx-** [comment]
android ?

**Comment by ghajini** [comment]
Sorry due to no coin filter list in opera browser

**Comment by ghajini** [comment]
`https://vidoza.net/dl?op=download_orig&id=gs2plmctlvuc&mode=n&hash=25156312-139-99-1591086384-a171ac4439ccfecd4c3a8bc9aa390bb3`

Fake download button

**Comment by ghajini** [comment]
Breakage = video controls not available like play,pause
 
URL = `https://str09.vidoza.net/x4lfo5nepjz7vjumxcxf4x2svdvqlea5xmhwpsinfno6jlzehcdn4jep5ezq/Moana+%282016%29+1080p+5.1+-+2.0+x264+Phun+Psyz.mp4`

Platform = firefox A., ublock origin 1.27.11.2

Screenshots=

**Ublock origin enabled :**
 
https://user-images.githubusercontent.com/20338483/83511749-c6a28c00-a4ec-11ea-8f3e-88a5c0ce2e17.jpg



**Ublock origin disabled=**

https://user-images.githubusercontent.com/20338483/83511764-cefac700-a4ec-11ea-9ea3-aeb02fba8004.jpg

**Comment by ghajini** [comment]
`vidoza.net/y4j188e6pfbv.html`

Notification ads 
Opera browser

Screenshot= 
`prnt.sc/t19qrn`

**Comment by ghajini** [comment]
`https://vidoza.net/ych4lbkt189u.html`
ubo1.32.5b10 opera browser

captcha don't load for a verification when downloading a file 
`https://vidoza.net/ych4lbkt189u.html`

![image](https://user-images.githubusercontent.com/20338483/104746237-044edf00-5775-11eb-83b0-c14509d842d5.png)

**Comment by mapx-** [comment]
this should work

`@@||google.com/recaptcha/$csp`

**Comment by ghajini** [comment]
generalised approach?

That will work

**Comment by mapx-** [comment]
yeah due to worker-src (csp) to defeat some resource abuse stuff

**Comment by mapx-** [comment]
waiting for ryan to see if he want to add it to EL

**Comment by Yuki2718** [comment]
Personally expecting him to remove the filter than adding exception. I think the filter was added for resource abuse which I suspect no more exist.

**Comment by mapx-** [comment]
captcha should never be blocked, so it's ok

**Comment by Yuki2718** [comment]
Oh, mu guess was wrong!

**Comment by mapx-** [comment]
yes, keeping it like we did for `gstatic` for example `@@||gstatic.com^*/recaptcha/$script`

**Comment by ghajini** [comment]
easylist done like this https://github.com/easylist/easylist/commit/ea93b16160094e21e1f1037ab16e7bea71c09609
but does that work for abp users

then mapx- filter is way better okay

**Comment by Yuki2718** [comment]
We have `@@||google.com^*recaptcha/$frame` somehow in uBlock filters. Maybe we can move it to Unbreak and merge?

**Comment by Yuki2718** [comment]
> but does that work for abp usersusers?😂
> 
Should work as no type-options specified.

OMG I occasionally wrongly edit others' post.
