### ISSUE TITLE
sportfacts.net

### ISSUE THREAD

**Issue by BlocksAds** [uBlockOrigin/uAssets#16327]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

anti-ad-blocker

### URL(s) where the issue occurs.

`https://www.sportfacts.net/total/sports/2023/premier-league-aston-villa-vs-leeds-united-s2/`

### uBO version

1.46.0

### Browser name and version

Google Chrome

### Settings

.

### Notes

- https://github.com/AdguardTeam/AdguardFilters/issues/140010
- `https://www.topsporter.net/wp-content/plugins/deblocker/js/ads.min.js?ver=6.1.1`

**Comment by mapx-** [comment]
You should provide another event or explain where getting new ones

**Comment by BlocksAds** [comment]
I don't know, I just saw the report in the AdGuardFilters repository

**Comment by mapx-** [comment]
some filters, tested partially (first one could be replaced but needing another stream to test)

```
@@||pagead2.googlesyndication.com^$script,xhr,domain=sportfacts.net|topsporter.net
sportfacts.net###footy-side-menu
sportfacts.net##.footy-related-posts
sportfacts.net##.aoa_overlay
sportfacts.net##.scroller
sportfacts.net###footy_post_extensions-2
sportfacts.net##+js(aopr, document.oncontextmenu)
```

**Comment by BlocksAds** [comment]
Did you find a stream?

Yesterday allowing `pagead2 [...]` xhr for `topsporter.net` worked from what I remember

**Comment by mapx-** [comment]
filters created during testing last night (but unexpectedly the stream ended)

**Comment by BlocksAds** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/140070

**Comment by stephenhawk8054** [comment]
mapx's filters work for me
