### ISSUE TITLE
seznam.cz: ads

### ISSUE THREAD

**Issue by Radegast1980** [uBlockOrigin/uAssets#16320]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.seznam.cz/`

### Category

ads

### Description

reklama still on displey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83771
  cosmetic: 39153
  scriptlet: 16956
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    CZE-0: 731-0, 1d.10m
    easylist: 61692-48, 5d.18h.30m
    easyprivacy: 30888-1177, 5d.18h.29m
    plowe-0: 3669-900, 5d.6h.58m
    ublock-abuse: 77-0, 9d.3h.15m
    ublock-badware: 4287-112, 3d.5h.52m
    ublock-filters: 31605-124, 3d.5h.51m
    ublock-privacy: 258-1, 9d.3h.14m
    ublock-quick-fixes: 473-22, 1d.9m
    ublock-unbreak: 1925-45, 3d.5h.50m
    urlhaus-1: 6868-0, 1d.8m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 641 ms (selfie)
  maxAssetCacheWait: 462 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    seznam.cz: 1
    adform.net: 1
    adnxs.com: 1
    gemius.pl: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
@addisr

**Comment by mapx-** [comment]
maybe

```
||sdn.cz/*/loader.js$badfilter
seznam.cz##.banner-wrapper:upward(2):remove()
seznam.cz##.text-right.atm-advert-label
seznam.cz##[data-draggable-target]:has-text(Rekl):not(*:has([href*="radio"]))
```

**Comment by mapx-** [comment]
first one has been removed from EP
https://github.com/easylist/easylist/commit/0e82d3166d76268a0835b24e8b153e6032b0f6a6

**Comment by jathri** [comment]
Filter ||seznam.cz/$frame,1p prevents me from seeing cookie consent when loading mapy.cz. Had to add @@||seznam.cz/$frame,1p to my filter list to make consent page works again.
