### ISSUE TITLE
[nsfw] t66y.com: detection

### ISSUE THREAD

**Issue by chuyueye** [uBlockOrigin/uAssets#16323]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://t66y.com/htm_data/2301/7/5491441.html`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 101467
  cosmetic: 49081
  scriptlet: 16934
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 46-3, never
    CHN-0: 28226-103, 1d.13h.28m
    easylist: 61904-81, 1d.9h.26m
    easyprivacy: 30911-1192, 1d.9h.27m
    plowe-0: 3671-903, 10d.10h.2m
    ublock-abuse: 77-0, 1d.5h.25m
    ublock-badware: 4287-113, 2d.1h.31m
    ublock-filters: 31616-141, 2d.1h.33m
    ublock-privacy: 258-1, 1d.5h.24m
    ublock-quick-fixes: 473-22, 1h.20m
    ublock-unbreak: 1920-48, 2d.1h.32m
    urlhaus-1: 6868-0, 1h.19m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 18 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 326 ms (selfie)
  maxAssetCacheWait: 198 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by einstein95** [comment]
Only detection I could see was in posts.js but is commented out(?)
To get rid of the actual ads on the page `t66y.com##.sptable_do_not_remove`

**Comment by mapx-** [comment]
@cjx82630 are you able to reproduce any detection ?

**Comment by cjx82630** [comment]
@mapx- https://github.com/uBlockOrigin/uAssets/issues/4306
