### ISSUE TITLE
novinky.cz: breakage

### ISSUE THREAD

**Issue by grongor** [uBlockOrigin/uAssets#16325]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.novinky.cz/clanek/krimi-muzi-spadly-cigarety-do-kolejiste-srazil-ho-rychlik-nehodu-zachytila-kamera-40419961`

### Category

breakage

### Description

All videos are unplayable (looks like buffering) when uBlockOrigin is enabled. I hope the `CZE, SVK: EasyList Czech and Slovak` regional list is not considered an "external filter list".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/972493/212398248-8cb0c13c-322d-4399-bd21-ee90b5308ebc.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 125065
  cosmetic: 182061
  scriptlet: 34032
  html: 0
listset (total-discarded, last-updated): 
  added: 
    CZE-0: 731-0, 10h.31m
    adguard-annoyance: 62300-91, 2d.6h.25m
    adguard-generic: 67287-528, 2d.6h.24m
    adguard-social: 19533-826, 2d.6h.23m
    curben-phishing: 17726-0, 10h.29m
    fanboy-cookiemonster: 44492-3402, 7d.23h.58m
  default: 
    user-filters: 2-0, never
    easylist: 61689-914, 4d.6h.51m
    easyprivacy: 30894-1372, 4d.2h.50m
    plowe-0: 3669-915, 1d.6h.16m
    ublock-abuse: 77-0, 2d.1h.55m
    ublock-badware: 4292-305, 2d.6h.22m
    ublock-filters: 31608-3828, 2d.6h.26m
    ublock-privacy: 258-3, 2d.6h.28m
    ublock-quick-fixes: 466-48, 10h.28m
    ublock-unbreak: 1918-92, 2d.6h.27m
    urlhaus-1: 6868-1, 10h.30m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 357 ms (selfie)
  maxAssetCacheWait: 338 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adform.net: 2
    gemius.pl: 2
    googletagmanager.com: 1
    sdn.cz: 2
    seznam.cz: 3
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
Caused by `EasyPrivacy` filter `||sdn.cz/*/loader.js`

@grongor
Add
`@@||sdn.cz/*/loader.js$script,domain=novinky.cz`
to your filter list until it is fixed.
