### ISSUE TITLE
mycourses.pearson.com: breakage

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#16328]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mycourses.pearson.com/course-home`

### Category

breakage

### Description

Page is just blank and white when ublock origin is on. Note that you'll need a free pearson account to access this page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/11874211/212431767-c304e99e-04cd-4a96-8bb9-437e943f91f8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 102
filterset (summary): 
  network: 101714
  cosmetic: 50397
  scriptlet: 19986
  html: 994
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4728-5, 18m
    CHN-0: 28233-122, 17m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32524-38, now
    ublock-badware: 4298-0, 22m
    ublock-privacy: 305-0, 21m
    ublock-abuse: 77-0, 20m
    ublock-unbreak: 1940-3, 19m
    ublock-quick-fixes: 472-18, 20h.28m
    easylist: 61844-661, 1d.20h.20m
    easyprivacy: 30917-1764, 1d.20h.19m
    urlhaus-1: 6868-0, 20h.27m
    plowe-0: 3671-2, 8d.21h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 540 ms (selfie)
  maxAssetCacheWait: 396 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    pearson.com: 2
    crazyegg.com: 1
    go-mpulse.net: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> free account

![image](https://user-images.githubusercontent.com/10303732/212462600-b8562fa3-65cf-4869-8ba7-fd185b5b233a.png)

**Comment by mapx-** [comment]
@aaronliu0130 if you agree just send your account credentials here: `axis.trivia@gmail.com`

**Comment by aaronliu0130** [comment]
@mapx- Done, please tell me when you're done using it so I can change it, thanks

**Comment by mapx-** [comment]
@aaronliu0130 

add & test for other breakages

`@@||mycourses.pearson.com/shared/static/*/component/ga.min.js$script,1p`

@ryanbr 
EP issue  `/ga.min.js`

**Comment by aaronliu0130** [comment]
Thanks! Looks good now.
