### ISSUE TITLE
steamgifts.com: ads

### ISSUE THREAD

**Issue by Drevneus** [uBlockOrigin/uAssets#16334]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.steamgifts.com/`

### Category

ads

### Description

A new ad has appeared, I think it's worth adding to the filter.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![Снимок экрана 2023-01-14 151636](https://user-images.githubusercontent.com/25377122/212471246-8e19289e-0c23-4707-9227-1f0afce6786b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 101011
  cosmetic: 59675
  scriptlet: 18016
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39124-12, 1m
    easylist: 62140-59, 1m
    easyprivacy: 30931-1280, 1m
    plowe-0: 3666-903, 1m
    ublock-abuse: 77-1, 1m
    ublock-badware: 4294-113, 1m
    ublock-filters: 31738-159, 1m
    ublock-privacy: 257-1, 1m
    ublock-quick-fixes: 457-17, 1m
    ublock-unbreak: 1920-47, 1m
    urlhaus-1: 6868-0, 1m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 391 ms
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    doubleclick.net: 1
    googletagmanager.com: 1
    quantcast.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
steamgifts.com##.sidebar__mpu
```

or

```adb
steamgifts.com##[href^="https://www.steamgifts.com/redirect"]
```

@ryanbr

**Comment by Drevneus** [comment]
Thanks, should I add this manually (never done before)? Will filters be added in a future update?

**Comment by stephenhawk8054** [comment]
I have informed EasyList maintainers, you can add manually until it's fixed in EasyList.

**Comment by splaweek** [comment]
The issue still persist with every listed EasyList list.

**Comment by mapx-** [comment]
- same in uBO
- the filter above is working (but is hiding all `new bundles` items)
```
adb
steamgifts.com##[href^="https://www.steamgifts.com/redirect"]
```

**Comment by mapx-** [comment]
@splaweek report the "issue" at easylist repo

**Comment by splaweek** [comment]
> [@splaweek](https://github.com/splaweek) report the "issue" at easylist repo

thanks, not interested
