### ISSUE TITLE
msn.com: ads

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#16330]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.msn.com/en-au/news/australia/death-railway-thailand-new-zealand-tourist-45-dies-taking-pictures-near-krasae-cave/ar-AA15JiMS?ocid=EMMX&cvid=bb1b95d75600406cbdd18e26b35a38aa`

### Category

ads

### Description

I have attached a screenshot showing blank dark grey boxes.
What are they and why aren't removed fully if ads or shown correctly if not ads?

Scroll down the page and you'll see more and more of these blank boxes.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Page](https://user-images.githubusercontent.com/20948631/212468289-566ead48-c9a7-4160-9332-733bd49435ae.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 161442
  cosmetic: 216521
  scriptlet: 37612
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36171-3501, 1h.29m
    adguard-annoyance: 62441-234, 1h.29m
    adguard-generic: 67397-1210, 1h.29m
    adguard-social: 19580-832, 1h.29m
    block-lan: 44-0, 1h.29m
    curben-phishing: 17726-0, 1h.29m
    curben-pup: 194-0, 1h.29m
    dpollock-0: 11397-189, 1h.29m
    fanboy-annoyance: 84546-5200, 1h.29m
    fanboy-thirdparty_social: 68-21, 1h.29m
    ublock-annoyances: 4748-245, 1h.28m
  default: 
    user-filters: 10-0, never
    easylist: 62140-1206, 1h.29m
    easyprivacy: 30931-12412, 1h.29m
    plowe-0: 3666-1345, 1h.28m
    ublock-abuse: 77-0, 1h.28m
    ublock-badware: 4294-306, 1h.28m
    ublock-filters: 31736-3855, 1h.28m
    ublock-privacy: 257-52, 1h.28m
    ublock-quick-fixes: 457-43, 1h.28m
    ublock-unbreak: 1927-113, 1h.28m
    urlhaus-1: 6868-1, 1h.28m
filterset (user): [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 419 ms (selfie)
  maxAssetCacheWait: 636 ms
popupPanel: 
  blocked: 187
  blockedDetails: 
    msn.com: 118
    azure.com: 2
    btloader.com: 1
    civicscience.com: 1
    dailymotion.com: 9
    dm-event.net: 39
    dmcdn.net: 1
    imasdk.googleapis.com: 4
    outbrain.com: 1
    scorecardresearch.com: 11
```
</details>

**Comment by BlocksAds** [comment]
`msn.com##[style*="slot"]:has(.native-ad)`

**Comment by stephenhawk8054** [comment]
Those are ads placeholders, you can "hide" them by

```adb
msn.com##msft-article-card:not(.contentCard)
```

However, other news cards will still not fill the blank spot since their positions are fixed by the styles

```css
{ grid-area: slot4 }
```

or `slot5`, `slot6`...

**Comment by mapx-** [comment]
does not work on my end, I get shadow-root stuff

![image](https://user-images.githubusercontent.com/10303732/212468949-0d058949-793c-4351-b523-a79a8fb6742f.png)

**Comment by stephenhawk8054** [comment]
It does change the `display` to `none` for me

![image](https://user-images.githubusercontent.com/66517106/212469433-e65622ae-43e5-4a87-8024-0dc160ae9b53.png)

but looks like all of these positions are fixed with `grid-area` style so I don't think we can fix that.

**Comment by Yuki2718** [comment]
Placeholders were fixed by `json-prune-fetch-response`.
