### ISSUE TITLE
nykaa.com logging

### ISSUE THREAD

**Issue by matter-it-does** [uBlockOrigin/uAssets#16338]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`||prod-events.nykaa.com/log_data/*$xhr,domain=www.nykaa.com`

`https://prod-events.nykaa.com/log_data/log`

### URL(s) where the issue occurs.

nykaa.com

### uBO version

 1.46.0

### Browser name and version

Firefox 108.0.2

### Settings

N/A

**Comment by okiehsch** [comment]
What is your issue?

**Comment by matter-it-does** [comment]
other log related requests are blocked.. so I assumed this should be too

**Comment by okiehsch** [comment]
I see, is an account needeed to reproduce the request?

**Comment by matter-it-does** [comment]
no, just see the logger

**Comment by okiehsch** [comment]
What, I meant is I don't see `https://prod-events.nykaa.com/log_data/log` in the logger if I go to 
``nykaa.com`, so I assume you are logged in, or is there a specific link for me to reproduce.

**Comment by matter-it-does** [comment]
scroll down

**Comment by mapx-** [comment]
I get only

![image](https://user-images.githubusercontent.com/10303732/212488015-55565f74-ba7c-40d4-9344-3d39afed61b0.png)

so ... **should we have an account to reproduce the issue** ?

**Comment by matter-it-does** [comment]
> so ... should we have an account to reproduce the issue ?

no

**Comment by mapx-** [comment]
well, the company seems to be from India, I used an indian ip and I reproduced the issue

`||prod-events.nykaa.com/log_data/log$xhr,1p`

@ryanbr
