### ISSUE TITLE
[nsfw] sg.mix-bestboost.club: nuisance

### ISSUE THREAD

**Issue by achuka889** [uBlockOrigin/uAssets#16335]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sg.mix-bestboost.club/terra/rpdac/?type=new8&button=2&clickid=1bd3452f8e8eb5623fc59bfdbcc1a017&campaign_id=689615&source_id=14379457`

### Category

nuisance

### Description

The site is a nuisance and I'm redirected to it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 90340
  cosmetic: 81297
  scriptlet: 19375
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62389-1668, 1d.27m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8653-30, 1d.28m
    easylist: 62107-17407, 1d.27m
    easyprivacy: 30923-1269, 1d.27m
    plowe-0: 3669-986, 1d.27m
    ublock-abuse: 77-0, 1d.27m
    ublock-badware: 4291-114, 1d.27m
    ublock-filters: 31835-739, 1d.27m
    ublock-privacy: 258-2, 1d.27m
    ublock-quick-fixes: 473-23, 1d.27m
    ublock-unbreak: 1928-51, 1d.27m
    urlhaus-1: 6868-0, 1d.27m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1880 ms (selfie)
  maxAssetCacheWait: 792 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    stoomawy.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give original URL that has popups/redirections to this site?

**Comment by achuka889** [comment]
stagatv.com

**Comment by achuka889** [comment]
waploaded.com also redirects to this following nuisance site.
https://sg.rpboostpro.club/adsrpd/?type=new4&button=2&clickid=1bd3af919a3f7547024705f525462d0a&campaign_id=639128&source_id=14379457&traff=Downloads&geo=NG#

**Comment by stephenhawk8054** [comment]
Looks like you are using Kiwi browser. I tested the sites on it and cannot reproduce the issue.

**Comment by achuka889** [comment]
I use lemur browser and use ublock origin extension from edge store

**Comment by stephenhawk8054** [comment]
I tested on that browser and still cannot reproduce the issue.

**Comment by achuka889** [comment]
It just doesn't happen always

**Comment by ghajini** [comment]
use the firefox browser on mobile
