### ISSUE TITLE
game3rb.com: nuisance

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16339]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Clicking anywhere on the site results a new tab opened with suspicious pages.

### URL(s) where the issue occurs.

`https://game3rb.com/`

### uBO version

1.46.0+

### Browser name and version

Firefox 108.0.2 & Opera 94.0.4606.65

### Settings

Default, enabling additionally ublock/fanboy/adguard annoyances didn't help either.

**Comment by MicrowaveSnacks** [comment]
`https://game3rb.com/barista-simulator-fitgirl-repack/`
`https://mrpcgamer.com/download-resident-evil-4-empress/`

```
##[href*="//welaadmi.click/"]
##[href*="//freemood.click/"]
||freemood.click^$all
||welaadmi.click^$all
||143.244.215.130^$all
||jug4you.click^$all
/?sandy=$doc
```
