### ISSUE TITLE
cinemakottaga.top: detection

### ISSUE THREAD

**Issue by DavE7005** [uBlockOrigin/uAssets#16331]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cinemakottaga.top/`

### Category

detection

### Description

Website detects adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 841298
  cosmetic: 139614
  scriptlet: 41076
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://abp.oisd.nl/: 355182-0, 2d.18h.3m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2087-1, 2d.18h.3m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24193-28, 2d.18h.4m
    https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt: 428723-13715, 2d.18h.3m
    adguard-annoyance: 62308-298, 2d.18h.4m
    fanboy-cookiemonster: 44491-3481, 9d.21h.25m
    ublock-annoyances: 4778-234, 2d.18h.4m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8448-761, 2d.18h.4m
    easylist: 61904-17938, 2d.18h.4m
    easyprivacy: 30911-5928, 2d.18h.4m
    plowe-0: 3671-3309, 9d.21h.25m
    ublock-abuse: 77-4, 7d.17h.53m
    ublock-badware: 4291-385, 2d.18h.4m
    ublock-filters: 31803-3423, 2d.18h.4m
    ublock-privacy: 258-27, 7d.8h.30m
    ublock-quick-fixes: 466-31, 2d.18h.3m
    ublock-unbreak: 1925-54, 2d.18h.4m
    urlhaus-1: 6868-602, 2d.18h.3m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 634 ms (selfie)
  maxAssetCacheWait: 480 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    cinemakottaga.top: 2
    arc.io: 1
    comparedsilas.com: 1
```
</details>

**Comment by BlocksAds** [comment]
`https://cinemakottaga.top/wp-content/plugins/deblocker/js/ads.min.js?ver=6.1.1`
