### ISSUE TITLE
geotastic.net: ads and detection

### ISSUE THREAD

**Issue by Matr1x-101** [uBlockOrigin/uAssets#16336]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

It's a collection of several issues with ads on geotastic. See sections "Screenshots" and "notes"

### URL(s) where the issue occurs.

`https://geotastic.net`

### Screenshot(s)

![Screenshot 1](https://user-images.githubusercontent.com/70490301/212476320-3796b8e1-85e8-46c3-a512-401b7cdde267.png)
![Screenshot 2](https://user-images.githubusercontent.com/70490301/212476402-520100f4-572d-4a9f-8f65-466952627bae.png)
![Screenshot 3](https://user-images.githubusercontent.com/70490301/212476506-155f4ccf-9a71-423c-8ccd-e50a9e0922b5.png)

Explanations on how to get here are found in the notes section.

### uBO version

uBlock Origin 1.46.0

### Browser name and version

Mozilla Firefox 108.0.1

### Settings

- Enabled Annoyance and Fanboy filters.

### Notes

This is NOT a duplicate of #15106 . That issue only removed the flicking viewport,
When we solve the issue at Screenshot 2, the issue at Screenshot 3 _could_ be already solved.

To get to Screenshot 2, create a burner account (with a burner email) and then click "Local game". Clicking "Watch ad to continue" does nothing.

To get to Screenshot 3, temporarily disable uBlock, and click "Local game". Watch the ad.

**Comment by mapx-** [comment]
Test

```
@@||api.adinplay.com/libs/aiptag/pub/GTS/geotastic.net/tag.min.js$script,domain=geotastic.net
geotastic.net###wetter-de-banner
```
