### ISSUE TITLE
tvnow.at (de): ads

### ISSUE THREAD

**Issue by razzor1984** [uBlockOrigin/uAssets#16348]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The ads arn't blocked anymore, sometimes the ad detection system detects that some domains where blocked and it shows this information when you try to play videos back:
https://user-images.githubusercontent.com/3404263/212561075-e250d397-72b0-49ff-b786-1962706b4a5b.png

```
https://www.tvnow.at/shows/auto-mobil-174/2023-01/episode-2-das-vox-automagazin-2023-01-15-17-00-00-5361272
https://www.tvnow.at/shows/grip-das-motormagazin-1669/2023-01/episode-607-zwei-elektrische-alleskoenner-im-duell-5356505
```
The full log when you play videos back.
[log_nowtv.txt](https://github.com/uBlockOrigin/uAssets/files/10420934/log_nowtv.txt)

### URL(s) where the issue occurs.

```
https://www.tvnow.at
https://www.tvnow.de
```

### Screenshot(s)

![2023-01-15 19_23_15-Window](https://user-images.githubusercontent.com/3404263/212560788-381227fd-6355-4d2d-b6e0-e4a2a1f1fd83.png)
![2023-01-15 19_30_34-Window](https://user-images.githubusercontent.com/3404263/212560790-1982dcef-6dd8-4311-bfba-9fbd31f8605c.png)
I have marked the sections, when ads are played back.

### uBO version

1.38.2

### Browser name and version

Firefox 108.0.2

### Settings

[ublock-sicherung_2023-01-15_19.48.12.txt](https://github.com/uBlockOrigin/uAssets/files/10420932/ublock-sicherung_2023-01-15_19.48.12.txt)

### Notes

In the past it helped if you cleared the cache of the browser but not anymore.

**Comment by JobcenterTycoon** [comment]
Try 

```
tvnow.*##+js(no-xhr-if, damoh)
```

**Comment by razzor1984** [comment]
> Try
> 
> ```
> tvnow.*##+js(no-xhr-if, damoh)
> ```
> 
> `tvnow.at` redirect me to `tvnow.de` and on the .de TLD i get no ads or anti adblock

This did the trick i added it  in ublock under the section, "my filters" (meine Filter) and it worked. Suddenly no ads or anything, if you want to play videos back - big cudos to you :) !!!!
