### ISSUE TITLE
allotech-dz.com: anti-adb

### ISSUE THREAD

**Issue by BlocksAds** [uBlockOrigin/uAssets#16343]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

anti-adb

### URL(s) where the issue occurs.

`https://www.allotech-dz.com/`

### uBO version

1.46.0

### Browser name and version

Google Chrome 109.0.5414.75 (Official Build) (64-bit)

### Settings

.

### Notes

https://github.com/AdguardTeam/AdguardFilters/issues/140108

**Comment by okiehsch** [comment]
@Yuki2718 
`allotech-dz.com##+js(acis, eval, replace)`
for `AdGuard Français`.

**Comment by BlocksAds** [comment]
i think it will be fixed in adguard base (I think it's generic anti-adb)

**Comment by Yuki2718** [comment]
Right, deblocker is always fixed in Base so we need our own fix.

**Comment by garry-ut99** [comment]
> Yuki2718 : Right, deblocker is always fixed in Base so we need our own fix.

Why it's fixed in uBO additionally, given it's already fixed in uBO's regional AG French list (which is enabled by default in uBO for FRA users) ?
