### ISSUE TITLE
katfile.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1634]
URL(s) where the issue occurs

`https://katfile.com/hiyv7y3ln527`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
Download

**Comment by KiLL4FuNK** [comment]
fill the Captcha then it comes Anti-Adblock @mapx-

**Comment by mapx-** [comment]
test this filter
`katfile.com##script:inject(set-constant.js, adblock, false)`

**Comment by KiLL4FuNK** [comment]
It works perfect @mapx-
