### ISSUE TITLE
kimcartoon.li: ads

### ISSUE THREAD

**Issue by Cryptings** [uBlockOrigin/uAssets#16346]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kimcartoon.li/Cartoon/Gravity-Falls-Season-02/Episode-17?id=65124&s=beta&pfail=1`

### Category

ads

### Description

Popup free money ad appeared while browsing the sire

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Could not screen shot it in time as it disappeared quickly

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 84012
  cosmetic: 38869
  scriptlet: 16818
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62178-46, 5h.1m
    easyprivacy: 30910-1171, 3d.4h.8m
    plowe-0: 3668-900, 6d.23h.3m
    ublock-abuse: 77-0, 9d.16h.4m
    ublock-badware: 4294-114, 1d.8h.54m
    ublock-filters: 31652-126, 1d.8h.53m
    ublock-privacy: 258-1, 9d.16h.3m
    ublock-quick-fixes: 460-16, 16h.17m
    ublock-unbreak: 1923-47, 1d.8h.52m
    urlhaus-1: 6868-0, 16h.16m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2853 ms (selfie)
  maxAssetCacheWait: 218 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    kimcartoon.li: 3
    disqus.com: 4
    eehuzaih.com: 1
    enactsbasiate.com: 1
    genieessp.com: 1
    glizauvo.net: 3
    google-analytics.com: 1
    googletagmanager.com: 1
    idocdn.com: 2
    nessainy.net: 1
    nimrute.com: 1
    offerimage.com: 3
    player-cdn.com: 1
    propellerads.com: 1
    pubmatic.com: 1
    rndskittytor.com: 1
    rtmark.net: 4
    sharethis.com: 1
    thaudray.com: 1
    twitter.com: 1
    tzegilo.com: 1
    viglink.com: 2
```
</details>

**Comment by ghajini** [comment]
try to upload screenshot indicating ads in new reply when you can
