### ISSUE TITLE
videolyrics.in: detection

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#16358]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://videolyrics.in/`

### Category

detection

### Description

This site detect uBo.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/212699383-e05301a8-2cfa-4c71-a405-5bf0c05f15d9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 87826
  cosmetic: 40366
  scriptlet: 16882
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://easylist.to/easylist/easylist.txt: 62224-46, 2m
  default: 
    user-filters: 28-0, never
    IDN-0: 5430-1, 2m
    easylist: 62224-62224, 2m
    easyprivacy: 30941-1173, 2m
    plowe-0: 3666-898, 2m
    ublock-abuse: 77-0, 2m
    ublock-badware: 4304-114, 2m
    ublock-filters: 31789-153, 1m
    ublock-privacy: 257-1, 1m
    ublock-quick-fixes: 472-21, 1m
    ublock-unbreak: 1923-49, 1m
    urlhaus-1: 6589-0, 1m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 20 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2072 ms
  maxAssetCacheWait: 1025 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    surfe.pro: 2
```
</details>

**Comment by BlocksAds** [comment]
@JobcenterTycoon Is it from `https://viefaucet.com/`?

**Comment by yohanes4dip** [comment]
Yes, sorry late to reply

Pada tanggal Sen, 16 Jan 2023 23.56, BlocksAds ***@***.***>
menulis:

**Comment by stephenhawk8054** [comment]
Please give the exact original link or give steps to reproduce in details to not waste others' time. I have registered on `viefaucet.com` but I don't know what to do next

![image](https://user-images.githubusercontent.com/66517106/212787594-c2a1ce0e-5abc-4052-be22-66de5d6fdd47.png)

**Comment by yohanes4dip** [comment]
Sorry sorry,
Go to shortlink and click cbshort.com
[image: image.png]

Pada tanggal Sel, 17 Jan 2023 08.04, stephenhawk8054 <
***@***.***> menulis:

**Comment by yohanes4dip** [comment]
And you will go to this page
[image: image.png]

Pada tanggal Sel, 17 Jan 2023 pukul 08.04 stephenhawk8054 <
***@***.***> menulis:

**Comment by blader-render** [comment]
@stephenhawk8054  
He cannot find original link. This original link. https://ser2.crazyblog.in/Pr1pI
I have same issue

**Comment by blader-render** [comment]
> @stephenhawk8054 He cannot find original link. This original link: `https://ser2.crazyblog.in/Pr1pI`
> 
> I have same issue

@mapx- 
Can u help for this issue? Many thank.
