### ISSUE TITLE
Yamli.com is broken when uBlock is enabled

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#1635]
### URL(s) where the issue occurs

`https://www.yamli.com/`

### Describe the issue

When uBlock is enabled the button below the text bar in the webpage with "Loading..." stays so. When uBlock is disabled and the page is refreshed then it finally loads up with "Search".

### Versions

- Browser/version: Chrome 64
- uBlock Origin version: 1.15.10

### Settings

- Default.

### Notes

Seems like it may have to do with Google-Analytics being blocked

**Comment by gorhill** [comment]
Can only replicate reported symptoms if blocking `ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js` -- that would be a custom setting on user side.
