### ISSUE TITLE
instagram.com: ads

### ISSUE THREAD

**Issue by coreanoloco** [uBlockOrigin/uAssets#16352]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.instagram.com/`

### Category

ads

### Description

ads at biography

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 86099
  cosmetic: 44037
  scriptlet: 17072
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61929-46, 2d.20h.36m
    easyprivacy: 30923-1171, 2d.4h.56m
    plowe-0: 3666-898, 2d.4h.54m
    spa-0: 3450-11, 9h
    spa-1: 4918-182, 2d.20h.39m
    ublock-abuse: 77-0, 2d.4h.52m
    ublock-badware: 4045-110, 2d.4h.50m
    ublock-filters: 31523-179, 2d.4h.48m
    ublock-privacy: 257-1, 2d.4h.47m
    ublock-quick-fixes: 464-15, 8h.59m
    ublock-unbreak: 1911-47, 2d.4h.43m
    urlhaus-1: 6868-0, 8h.58m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 364 ms (selfie)
  maxAssetCacheWait: 241 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    instagram.com: 19
```
</details>

**Comment by mapx-** [comment]
> ads at biography

screenshot ?

**Comment by krystian3w** [comment]
You link homepage knowingly? Bio section IMO exist after open profile and instagram don't disable change url to avoid copy direct link to custom profile.
