### ISSUE TITLE
cyclingnews.com: breakage

### ISSUE THREAD

**Issue by whdmike** [uBlockOrigin/uAssets#16357]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cyclingnews.com/news/vincenzo-nibali-pays-tribute-to-the-late-lieuwe-westra/`

### Category

breakage

### Description

comments on a page are not visible (again)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/45095424/212694713-9e1d8345-7266-4866-9636-1babe78aa6bb.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 107
filterset (summary): 
  network: 83740
  cosmetic: 38710
  scriptlet: 16797
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62107-46, 3d.2m
    easyprivacy: 30917-1171, 3d.1m
    plowe-0: 3666-898, 1d.18h.33m
    ublock-abuse: 77-0, 5d.44m
    ublock-badware: 4045-110, 2d.21h.44m
    ublock-filters: 31523-139, 2d.21h.43m
    ublock-privacy: 258-1, 5d.46m
    ublock-quick-fixes: 457-15, 17h.56m
    ublock-unbreak: 1923-47, 2d.21h.42m
    urlhaus-1: 6868-0, 17h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 322 ms (selfie)
  maxAssetCacheWait: 287 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    dotmetrics.net: 1
    futurecdn.net: 2
    google-analytics.com: 1
    onesignal.com: 1
    parsely.com: 1
    permutive.app: 1
    quantcast.com: 4
    quantserve.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by whdmike** [comment]
*comments

**Comment by mapx-** [comment]
Test

```
@@||cmp.quantcast.com^$xhr,script,domain=cyclingnews.com
cyclingnews.com##.related-articles-wrap
```

@ryanbr

**Comment by whdmike** [comment]
thanks. works.
