### ISSUE TITLE
bestiemovies.xyz: nuisance

### ISSUE THREAD

**Issue by Gbt12** [uBlockOrigin/uAssets#16355]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bestiemovies.xyz/movie/337167/fifty-shades-freed.html`

### Category

nuisance

### Description

unwanted popup and nuiances In front Of Video Player after 1 minute of playing video.
https://user-images.githubusercontent.com/122017553/212637876-89d5b63b-da8c-495d-b229-fb559a13ee09.jpeg

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Web capture_16-1-2023_142539_bestiemovies xyz](https://user-images.githubusercontent.com/122017553/212637591-6a5dec45-0c05-42f4-ac21-7e7dfe8fb2e8.jpeg)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 98769
  cosmetic: 168032
  scriptlet: 25615
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 847-0, 40m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2102-1, 40m
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1878-18, 40m
    adguard-annoyance: 62448-100, 40m
    adguard-spyware-url: 885-130, 40m
    fanboy-annoyance: 85099-4151, 40m
    ublock-annoyances: 4749-214, 40m
  default: 
    user-filters: 11-0, never
    easylist: 62220-108, 40m
    easyprivacy: 30940-1263, 40m
    plowe-0: 3666-901, 40m
    ublock-abuse: 77-0, 40m
    ublock-badware: 4294-114, 40m
    ublock-filters: 31788-525, 40m
    ublock-privacy: 257-13, 40m
    ublock-quick-fixes: 465-17, 40m
    ublock-unbreak: 1923-54, 40m
    urlhaus-1: 6547-0, 40m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 281 ms (selfie)
  maxAssetCacheWait: 397 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    cheesydebatablepantomime.com: 1
    histats.com: 1
    translate.googleapis.com: 3
```
</details>

**Comment by erik9012** [comment]
Blocking the pop up wont solve the issue. This site misleads you with the thumbnail, but the loaded movie is not related to the one you was looking for

**Comment by erik9012** [comment]
It loads a 17,02 mb movie with a intro and after that its for 2 hours just black. Test it out with jdownloader 2

**Comment by krystian3w** [comment]
Looks as scam page without ripped videos longer than first 5 minutes.
