### ISSUE TITLE
promo-visits.site: detection

### ISSUE THREAD

**Issue by blader-render** [uBlockOrigin/uAssets#16356]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://promo-visits.site/awGOR94S`

### Category

detection

### Description

Detection adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 110
filterset (summary): 
  network: 85537
  cosmetic: 28481
  scriptlet: 16910
  html: 869
listset (total-discarded, last-updated): 
  default: 
    user-filters: 31-0, never
    ublock-filters: 32661-307, 23h.9m
    ublock-badware: 4297-0, 23h.9m
    ublock-privacy: 304-1, 23h.9m
    ublock-abuse: 77-0, 23h.9m
    ublock-unbreak: 1940-2, 23h.9m
    ublock-quick-fixes: 467-6, 23h.9m
    adguard-mobile: 8660-167, 23h.9m
    easylist: 62178-17884, 23h.9m
    easyprivacy: 30938-1750, 23h.9m
    urlhaus-1: 6868-0, 23h.9m
    plowe-0: 3666-2, 23h.9m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 725 ms (selfie)
  maxAssetCacheWait: 307 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    arsnivyr.com: 1
    godpvqnszo.com: 1
    runative-syndicate.com: 1
    satoshi-win.xyz: 1
    zatnoh.com: 1
```
</details>

**Comment by mapx-** [comment]
fixed 8 hours ago, did you update all lists ?
https://github.com/uBlockOrigin/uAssets/commit/7528251e9e2ffed1c3d124e7ba2edf9fb0b29453

**Comment by blader-render** [comment]
> fixed 8 hours ago, did you update all lists ? [7528251](https://github.com/uBlockOrigin/uAssets/commit/7528251e9e2ffed1c3d124e7ba2edf9fb0b29453)

Already update.
![az_recorder_20230116_181523](https://user-images.githubusercontent.com/120096290/212665638-4b4f981c-6b0c-4d20-bb3e-816d00ca0acf.jpg)

**Comment by mapx-** [comment]
provide the real first link

**Comment by blader-render** [comment]
https://promo-visits.site/awGOR94S

**Comment by JobcenterTycoon** [comment]
`https://promo-visits.site/pjLW`

Seems to be the detection is back, will fix

**Comment by blader-render** [comment]
ok, nice. work for now

**Comment by blader-render** [comment]
> `https://promo-visits.site/pjLW`
> 
> Seems to be the detection is back, will fix
> 
> The site is known to circument filter after 1 - 2 days so i will keep this open

@mapx- @JobcenterTycoon 
need to fix it again. because already detect agan. thanks

**Comment by blader-render** [comment]
> Works fine for me

![image](https://user-images.githubusercontent.com/120096290/212904680-91740a84-68e1-4b79-b29a-5a4aab0e8043.png)

**Comment by blader-render** [comment]
he change the domain https://satoshi-win.xyz/url/pCn96R0o?no-adblock=false

**Comment by JobcenterTycoon** [comment]
Should be fine now
