### ISSUE TITLE
The Daily Dot falsely added to malware domain list.

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#1636]
The Daily Dot is a media website. Why is it added to the malware domain list which is enabled by default in UBO? Also website does not load correctly with UBO please fix that.

**Comment by gorhill** [comment]
Force an update of "uBlock filters -- Unbreak", a workaround was added yesterday. The `malwaredomains.com` list is 3rd-party to this project, you need to report to them.
