### ISSUE TITLE
trustradius.com: breakage

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#16367]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.trustradius.com/products/forticlient/reviews?qs=pros-and-cons`

### Category

breakage

### Description

FortiClient Video section breakage.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-01-17 at 12-07-02 FortiClient Reviews   Ratings 2023](https://user-images.githubusercontent.com/101707608/212871487-c370b32a-6728-4b87-821c-3b6cd7fb29b1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 206713
  cosmetic: 242450
  scriptlet: 37642
  html: 984
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 43730-627, 1d.1h.6m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-0, 6d.5m
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 1d.1h.5m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 66-0, 2d.23h.21m
    https://www.i-dont-care-about-cookies.eu/abp/: 25703-5, 1d.1h.8m
    adguard-generic: 67322-5929, 4d.44m
    adguard-mobile: 8451-188, 4d.44m
    adguard-spyware: 36164-14768, 4d.44m
    adguard-spyware-url: 885-4, 4d.44m
    block-lan: 44-0, 20d.2h.55m
    curben-phishing: 17726-3, 1d.1h.3m
    curben-pup: 187-0, 1d.1h.2m
    adguard-annoyance: 62372-5569, 4d.44m
    adguard-social: 19570-1097, 4d.44m
    fanboy-thirdparty_social: 69-0, 3d.23h.47m
    fanboy-annoyance: 85025-69137, 3d.1h.27m
    fanboy-cookiemonster: 44825-9428, 3d.1h.26m
    fanboy-social: 23493-31, 6d.6m
    ublock-annoyances: 4691-6, 4d.44m
    dpollock-0: 11397-474, 1d.1h.9m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32512-135, 4d.44m
    ublock-badware: 4296-0, 4d.44m
    ublock-privacy: 304-0, 1h.25m
    ublock-abuse: 77-4, 1h.24m
    ublock-unbreak: 1936-3, 4d.44m
    ublock-quick-fixes: 464-0, 1d.1h.4m
    easylist: 62220-1011, 1h.23m
    easyprivacy: 30941-2148, 1h.22m
    urlhaus-1: 6547-0, 1d.1h.1m
    plowe-0: 3668-4, 8d.1h.18m
    GRC-0: 1004-1, 1d.1h.7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 19798 ms (selfie)
  maxAssetCacheWait: 3972 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    trustradius.com: 2
    browser-update.org: 1
    cookielaw.org: 1
    newrelic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Have you tested this yet?

> - [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.

**Comment by DimitrisKalaboukas** [comment]
@stephenhawk8054 I disabled my custom filters, but the problem still occurs. I couldn’t figure out which list causes the breakage nor create an unbreak filter.

**Comment by stephenhawk8054** [comment]
Have you tried disabled the Annoyances filter lists?

**Comment by DimitrisKalaboukas** [comment]
@stephenhawk8054 Yeah, AdGuard Annoyances list is finally responsible. I have to report the issue to them?

**Comment by stephenhawk8054** [comment]
Caused by

```adb
||cookielaw.org^$3p
```

@Yuki2718
