### ISSUE TITLE
melty.fr: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16364]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.melty.fr/people/tu-lignores-peut-etre-mais-ces-acteurs-de-clem-sont-en-couple-et-voici-leurs-partenaires-654547.html`

### Category

nuisance

### Description

This site needs a good cleaning by ublock. We do not count the number of spaces reserved for ads and empty frames.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/212836659-de0d4887-e535-49a9-a681-d32ade2be6d7.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 122484
  cosmetic: 109431
  scriptlet: 20029
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39090-172, 20h.29m
    fanboy-cookiemonster: 44890-212, 20h.29m
  default: 
    user-filters: 0-0, never
    FRA-0: 29980-28, 20h.29m
    easylist: 62224-87, 20h.29m
    easyprivacy: 30941-1588, 20h.29m
    plowe-0: 3666-928, 20h.29m
    ublock-abuse: 77-2, 20h.29m
    ublock-badware: 4304-132, 20h.29m
    ublock-filters: 31787-278, 20h.29m
    ublock-privacy: 257-1, 20h.29m
    ublock-quick-fixes: 475-21, 20h.29m
    ublock-unbreak: 1923-49, 20h.29m
    urlhaus-1: 6547-0, 20h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 221 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    melty.fr: 2
    aaxads.com: 1
    adpaths.com: 1
    amazon-adsystem.com: 1
    dailymotion.com: 6
    dm-event.net: 4
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    instagram.com: 28
    newsroom.bi: 1
    pbstck.com: 1
    reworldmediafactory.com: 2
    smilewanted.com: 1
    viously.com: 1
```
</details>

**Comment by mapx-** [comment]
```
melty.fr##.placeholder-pub_dfp
@@||sonar.viously.com^$script,domain=melty.fr
```

second one => @ryanbr EP
first @smed79
