### ISSUE TITLE
loadout.tf: breakage

### ISSUE THREAD

**Issue by BinaryPrime** [uBlockOrigin/uAssets#16361]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://loadout.tf/`

### Category

breakage

### Description

The website lags and stutters significantly when uBlock Origin is enabled on it. This did not happen before about a week ago. Uninstalling and reinstalling uBO fixed the problem the previous time it occurred, but it is occurring again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 83692
  cosmetic: 38870
  scriptlet: 16825
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32452-50, 1d.14h.56m
    ublock-badware: 4298-0, 1d.14h.55m
    ublock-privacy: 304-0, 1d.14h.54m
    ublock-abuse: 77-0, 1d.14h.53m
    ublock-unbreak: 1933-2, 1d.14h.52m
    ublock-quick-fixes: 479-0, 3h.46m
    easylist: 62107-625, 1d.14h.50m
    easyprivacy: 30938-1742, 1d.14h.49m
    urlhaus-1: 6589-0, 3h.45m
    plowe-0: 3666-2, 1d.14h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 320 ms (selfie)
  maxAssetCacheWait: 54 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by garry-ut99** [comment]
- I'm unable to reproduce, you have to provide more detailed steps: which buttons pressed, what activities performed etc. for step 1, step 2, step 3 etc
- also: https://github.com/uBlockOrigin/uBlock-issues#performance-issues

**Comment by stephenhawk8054** [comment]
It's fixed yesterday. Can you force update the filter list and test again?
