### ISSUE TITLE
ge.globo.com: nuisance

### ISSUE THREAD

**Issue by ddcv1** [uBlockOrigin/uAssets#16369]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ge.globo.com/futebol/times/corinthians/noticia/2023/01/17/vai-contratar-o-que-corinthians-e-fernando-lazaro-pensam-sobre-a-chegada-de-reforcos.ghtml`

### Category

nuisance

### Description

content overlaps at bottom of page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/122881776/212894428-04614f49-bd58-4c3b-99ba-df1936da501f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 85413
  cosmetic: 42031
  scriptlet: 17084
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ublock-quick-fixes: 457-16, 23h.54m
  default: 
    user-filters: 0-0, never
    easylist: 62174-46, 2d.8h.13m
    easyprivacy: 30923-1171, 2d.8h.14m
    plowe-0: 3668-900, 8d.12h.29m
    spa-1: 4918-68, 2d.18h.35m
    ublock-abuse: 77-0, 2d.18h.39m
    ublock-badware: 4294-114, 2d.18h.37m
    ublock-filters: 31655-157, 2d.18h.36m
    ublock-privacy: 257-1, 2d.18h.41m
    ublock-unbreak: 1927-48, 2d.18h.38m
    urlhaus-1: 6868-0, 23h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 24 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2203 ms (selfie)
  maxAssetCacheWait: 281 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    globo.com: 8
    glbimg.com: 1
    imasdk.googleapis.com: 2
    scorecardresearch.com: 1
```
</details>

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
