### ISSUE TITLE
game3rb.com: popups

### ISSUE THREAD

**Issue by Moham-OverKill** [uBlockOrigin/uAssets#16360]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://game3rb.com/`

### Category

popups

### Description

it opens unwanted taps even with popups disabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83753
  cosmetic: 38861
  scriptlet: 16822
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61904-46, 5d.9h.13m
    easyprivacy: 30910-1171, 5d.9h.12m
    plowe-0: 3668-900, 6d.8h.12m
    ublock-abuse: 77-0, 8d.12h.46m
    ublock-badware: 4294-113, 2d.16h.14m
    ublock-filters: 31652-125, 2d.16h.13m
    ublock-privacy: 258-1, 8d.12h.45m
    ublock-quick-fixes: 465-16, 5h.24m
    ublock-unbreak: 1927-47, 2d.16h.12m
    urlhaus-1: 6868-0, 5h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 282 ms (selfie)
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
  no-popups: true
  no-remote-fonts: true
  blockedDetails: 
    amung.us: 1
    ayanpleasea.com.ua: 1
    bootstrapcdn.com: 3
    duscleouphes.com: 1
    wp.com: 1
```
</details>

**Comment by mapx-** [comment]
Update all your filter lists.
(Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
