### ISSUE TITLE
[nsfw] wp.sekilastekno.com: popups

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#16373]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wp.sekilastekno.com/stock-investment-164`

### Category

popups

### Description

![Screenshot_2023-01-17-22-41-07-086_us spotco fennec_dos](https://user-images.githubusercontent.com/96541364/212965943-68c8a718-836a-4821-aa7d-4698e155157f.jpg)

when I'm clicking on download button opening unwanted tab 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 83488
  cosmetic: 122828
  scriptlet: 21836
  html: 997
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    fanboy-annoyance: 85099-476, 1d.8h.32m
    ublock-annoyances: 4788-4, 1d.8h.32m
  default: 
    user-filters: 10-0, never
    ublock-filters: 32690-93, 1d.8h.32m
    ublock-badware: 4297-0, 1d.8h.32m
    ublock-privacy: 304-0, 1d.8h.32m
    ublock-abuse: 77-0, 1d.8h.32m
    ublock-unbreak: 1941-1, 1d.8h.32m
    ublock-quick-fixes: 478-0, 5h.56m
    adguard-mobile: 8662-11, 1d.8h.33m
    easylist: 62220-486, 1d.8h.32m
    easyprivacy: 30940-1189, 1d.8h.32m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1800 ms (selfie)
  maxAssetCacheWait: 1551 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    googlesyndication.com: 4
    histats.com: 1
    mgid.com: 2
    vlitag.com: 2
    youtube.com: 1
```
</details>

**Comment by Yuki2718** [comment]
Is this from a short-link? Please provide the original link.

**Comment by stephenhawk8054** [comment]
Is it a redirection from another link? Can you give original URL?

**Comment by MayaBi7** [comment]
Click on PD

https://mkvdrama.org/download-island-2022-korean-drama/

**Comment by Yuki2718** [comment]
Mobile needs different fixes.
