### ISSUE TITLE
lecturel.com: detection

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16370]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Anti-adblock

### URL(s) where the issue occurs.

`https://www.lecturel.com/`

### 1
![hhh](https://user-images.githubusercontent.com/72945564/212919689-f3111db6-e3f0-4154-99f2-45ca8c5977c7.png)

After few seconds it changes to:

### 2
![jj](https://user-images.githubusercontent.com/72945564/212919451-256f2b4b-6d23-4a70-b98e-2c2ee93b1e22.png)

### uBO version

1.46.1b8

### Browser name and version

Firefox 108.0.2 & Opera 94

### Settings

default + uBO annoyances + AdGuard Fra

**Comment by ghajini** [comment]
```
@@||lecturel.com^$ghide

or

lecturel.com##+js(nosiif, visibility, 1000)
lecturel.com##+js(aeld, load, nextFunction)
```

**Comment by garry-ut99** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16343#issuecomment-1383113115

**Comment by Yuki2718** [comment]
> ( or in case there are two anti-adblocks, one of them will land in AdGuard Base and the other might land in Regional FRA )

antiblock .org and bab, so actually both will be Base.

**Comment by huyszn** [comment]
The site is detecting again, with the detection message looking like the first screenshot.

**Comment by ItsProfessional** [comment]
can't reproduce

**Comment by huyszn** [comment]
@ItsProfessional Try going to `https://www.lecturel.com/corps/index.php` and then clicking on the `Le Pendu` link on the right sidebar and wait 1-2 seconds. May have to repeat a few times to get the detection message.

**Comment by ItsProfessional** [comment]
still can't repro

**Comment by ItsProfessional** [comment]
@huyszn I can no longer reproduce with `@@||lecturel.com^$ghide`; can you confirm?

**Comment by huyszn** [comment]
@ItsProfessional Yes, I am not getting detected anymore with `@@||lecturel.com^$ghide`

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/commit/de3041efd8473b6cbf0cbcabd2eab5044d224865
