### ISSUE TITLE
hifiwigwam.com: detection

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16372]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

anti-adblock

### URL(s) where the issue occurs.

`https://hifiwigwam.com/`

### Screenshot(s)

![hghgh](https://user-images.githubusercontent.com/72945564/212947706-5a09a602-a468-40d9-8e8e-e7499c5184ce.png)

![g](https://user-images.githubusercontent.com/72945564/212984613-5c63055a-f3a0-4c3b-b881-d6ecfad3be9c.png)

![f](https://user-images.githubusercontent.com/72945564/212984631-fc50d088-d46e-4633-90c8-49ddabebe065.png)

### uBO version

1.46.1b8

### Browser name and version

Firefox 108.0.2 & Opera 94

### Settings

- default
- ubo Annoyances
- Fanboy Annoyance
- AdGuard Annoyance

enabling AdGuard Base didn't help either

**Comment by ghajini** [comment]
its just adblock warning ?

**Comment by Yuki2718** [comment]
Yeah, it seems most function are not restricted. Don't know if logged in user is affected more.

**Comment by garry-ut99** [comment]
Seems it's just an adblock warning, I don't have an account on that site.
