### ISSUE TITLE
mixpanel.com: breakage

### ISSUE THREAD

**Issue by luchfilip** [uBlockOrigin/uAssets#16374]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mixpanel.com/`

### Category

breakage

### Description

login page does not load.

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83408
  cosmetic: 38840
  scriptlet: 16762
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61905-46, 5d.16h.29m
    easyprivacy: 30917-1171, 5d.16h.28m
    plowe-0: 3671-901, 11d.16h.46m
    ublock-abuse: 77-0, 11d.16h.44m
    ublock-badware: 4294-113, 3d.2h.30m
    ublock-filters: 31659-125, 3d.2h.29m
    ublock-privacy: 258-1, 11d.16h.38m
    ublock-quick-fixes: 387-17, 19h.2m
    ublock-unbreak: 1927-47, 3d.2h.27m
    urlhaus-1: 6504-0, 19h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 980 ms (selfie)
  maxAssetCacheWait: 106 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cloudflare.com: 1
    dwin1.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this?

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by luchfilip** [comment]
yep I did that after report was generated but before I created the ticket. I just tried again - same thing. Does it work for you? 
https://mixpanel.com/login/

**Comment by stephenhawk8054** [comment]
It works normally for me

Screenshot
<details>

![image](https://user-images.githubusercontent.com/66517106/213072670-717c925f-af8d-41cf-b27e-64ec9b14067f.png)

</details>

**Comment by krystian3w** [comment]
Maybe cosmetic filter are malformed, try with disabled cosmetic filtering:

https://github.com/gorhill/uBlock/wiki/Per-site-switches -> https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering
