### ISSUE TITLE
fnac.com: breakage

### ISSUE THREAD

**Issue by donatelloOo** [uBlockOrigin/uAssets#16378]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fnac.com/`

### Category

breakage

### Description

Getting the below message from CloudFront protected websites after doing the capcha puzzle check.

```
You have been blocked.
Why this blocking? Something about the behaviour of the browser has caught our attention.

There are various possible explanations for this:

    you are browsing and clicking at a speed much faster than expected of a human being
    something is preventing Javascript from working on your computer
    there is a robot on the same network (IP) as you

Having problems accessing the site? Contact support
```

The website is available when disabling uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/29257279/213164808-c768d681-c01d-4e25-9807-197b6961c298.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 83398
  cosmetic: 38875
  scriptlet: 16824
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32450-140, 3d.15h.35m
    ublock-badware: 4298-0, 3d.15h.34m
    ublock-privacy: 305-0, 1m
    ublock-abuse: 77-0, 14h.25m
    ublock-unbreak: 1935-1, 14h.24m
    easylist: 61929-537, 5d.19h.17m
    easyprivacy: 30914-1741, 5d.19h.16m
    plowe-0: 3669-2, 5d.15h.12m
    urlhaus-1: 6481-0, 14h.23m
    ublock-quick-fixes: 494-0, 14h.22m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 867 ms (selfie)
  maxAssetCacheWait: 227 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    datadome.co: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I've been browsing the site for a while but cannot reproduce the issue

**Comment by donatelloOo** [comment]
I have another computer where I don't have any such CloudFront problem
Let me try to compare the differences

**Comment by garry-ut99** [comment]
I'm unable to reproduce on `https://www.fnac.com/`

However: https://forum.vivaldi.net/topic/72518/you-have-been-blocked :

> Websites where it happened :
> `https://www.cedeo.fr/`
> `https://www.pointp.fr/`

When going to the above websites they show the same message a in OP case: 
https://user-images.githubusercontent.com/72945564/213203532-47373a88-71f1-4bfc-98df-75422867850b.png
however after completing Captcha, the website loads fine. 
In any case I do not say it's uBO issue, just helping, it might be a website's issue as well.
