### ISSUE TITLE
[nsfw] blocked.goguardian.com: popups

### ISSUE THREAD

**Issue by trishull** [uBlockOrigin/uAssets#16388]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blocked.goguardian.com/?ctx=YWZpPTExMzU1NiZhcGk9ODM3MSZvaT0xNjE1MzA3NDYyOCZvdT1odHRwcyUzQSUyRiUyRm5pbmpha2l3aS5jb20lMkZHYW1lcyUyRlRvd2VyLURlZmVuc2UlMkZCbG9vbnMtVG93ZXItRGVmZW5zZS01Lmh0bWwmcnM9QURNSU5fU0lURV9DQVRFR09SWV9GSUxURVImc2NpPTMmc3Q9Y2hyb21pdW0tbSZ2PTE%3D&sum=c4c95d81`

### Category

popups

### Description

i dont want go guardian on my computer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83718
  cosmetic: 38752
  scriptlet: 16843
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62234-46, 1d.2h.32m
    easyprivacy: 30940-1172, 1d.2h.31m
    plowe-0: 3667-898, 3h.25m
    ublock-abuse: 77-0, 1d.4h.39m
    ublock-badware: 4305-114, 1d.4h.37m
    ublock-filters: 31688-129, 1d.4h.36m
    ublock-privacy: 257-1, 1d.4h.38m
    ublock-quick-fixes: 486-20, 3h.24m
    ublock-unbreak: 1923-46, 1d.4h.35m
    urlhaus-1: 6331-0, 3h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3272 ms (selfie)
  maxAssetCacheWait: 1988 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/15113

**Comment by krystian3w** [comment]
`&ou=https%3A%2F%2Fninjakiwi.com%2FGames%2FTower-Defense%2FBloons-Tower-Defense-5.html&rs=ADMIN_SITE_CATEGORY_FILTER&`
