### ISSUE TITLE
6vhao.net: ads

### ISSUE THREAD

**Issue by kuku1234us** [uBlockOrigin/uAssets#16381]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://www.6vhao.net/`

### Category

ads

### Description

ads are not being filtered on this site, i tried zapping the element, but ads reload on next visit

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 83
filterset (summary): 
  network: 86078
  cosmetic: 38682
  scriptlet: 16740
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 62275-46, 11m
    easyprivacy: 30944-1172, 10m
    plowe-0: 3667-899, 9m
    ublock-abuse: 77-0, 7m
    ublock-badware: 4232-111, never
    ublock-filters: 31551-118, never
    ublock-privacy: 255-1, never
    ublock-quick-fixes: 458-23, never
    ublock-unbreak: 1922-43, never
    urlhaus-1: 8695-0, never
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 659 ms
  maxAssetCacheWait: 226 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    baidu.com: 3
    cnzz.com: 1
```
</details>

**Comment by garry-ut99** [comment]
You must enable Regional filter lists `CHN: AdGuard Chinese (中文)` - ads dissappear then

<br>

> kuku1234us: i tried zapping the element, but ads reload on next visit

This is how Zapper works, it hides ads only for 1 visit, they are back next time you reload site, if want to hide ads permanently, use Picker instead.

**Comment by mapx-** [comment]
Enable the regional list: `CHN: AdGuard Chinese`
