### ISSUE TITLE
rubex.efilecabinet.net: breakage

### ISSUE THREAD

**Issue by mw-christensen** [uBlockOrigin/uAssets#16385]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rubex.efilecabinet.net/`

### Category

breakage

### Description

https://rubex.efilecabinet.net/ does not load at all when uBlock Origin is enabled. This seem to be due to the ||monitor.azure.com^ filter in the easy privacy list.

![2023-01-18_12-00-04](https://user-images.githubusercontent.com/103672717/213270666-e525396b-6997-462e-89ef-f75cd86bfb95.png)
![2023-01-18_11-59-43](https://user-images.githubusercontent.com/103672717/213270670-2124d377-a2c5-4a5e-9d5c-aa4517219d0c.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83732
  cosmetic: 38890
  scriptlet: 16840
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 62224-46, 1d.2h.32m
    easyprivacy: 30941-1171, 2h.35m
    plowe-0: 3667-898, 1d.2h.39m
    ublock-abuse: 77-0, 1d.2h.38m
    ublock-badware: 4325-114, 1d.2h.36m
    ublock-filters: 31688-126, 1d.2h.35m
    ublock-privacy: 257-1, 1d.2h.37m
    ublock-quick-fixes: 464-16, 1d.2h.30m
    ublock-unbreak: 1923-46, 1d.2h.34m
    urlhaus-1: 6481-0, 1d.2h.31m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4109 ms
  maxAssetCacheWait: 1745 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
`@@||js.monitor.azure.com/scripts/$script,domain=rubex.efilecabinet.net`

@ryanbr
