### ISSUE TITLE
nowwatchtvlive.net [Pop-up] [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1638]
URL(s) where the issue occurs

`http://nowwatchtvlive.net/espn2-hd-live-watch-online-espn2-hd-espn2-nba-online/`

Describe the issue

ADS Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by mapx-** [comment]
I addressed some ads. I get no popup on the page. Could you be more specific ? When do you get the popups ? clicking what ? link1, link2 ... ? other ?

**Comment by KiLL4FuNK** [comment]
only the window appears once afterwards no longer
