### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by SlimGenitals** [uBlockOrigin/uAssets#16380]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/pokelawls`

### Category

ads

### Description

ads on twitch showing again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 83546
  cosmetic: 38882
  scriptlet: 16833
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32481-54, 2h.10m
    ublock-badware: 4324-0, 2h.12m
    ublock-privacy: 305-0, 7d.8h.59m
    ublock-abuse: 77-0, 7d.8h.58m
    ublock-unbreak: 1936-1, 2h.11m
    ublock-quick-fixes: 478-0, 2h.9m
    easylist: 62146-626, 3d.6h.36m
    easyprivacy: 30934-1742, 3d.6h.35m
    urlhaus-1: 6374-0, 6h.13m
    plowe-0: 3666-2, 4d.7h.10m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3634 ms (selfie)
  maxAssetCacheWait: 1764 ms
popupPanel: 
  blocked: 201
  blockedDetails: 
    twitch.tv: 1
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    imrworldwide.com: 2
    scorecardresearch.com: 177
    sentry.io: 18
```
</details>

**Comment by krystian3w** [comment]
> - [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
> - [x] I did not answer truthfully to ALL the above checkpoints.

https://github.com/uBlockOrigin/uAssets/issues/5184
