### ISSUE TITLE
djxmaza.in: detection

### ISSUE THREAD

**Issue by blader-render** [uBlockOrigin/uAssets#16383]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://djxmaza.in/`

### Category

detection

### Description

Detection adblock. Original link https://linkszia.co/OWu0eywi1la

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 85297
  cosmetic: 28400
  scriptlet: 16948
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 31-15, never
    adguard-mobile: 8690-27, 10h.25m
    easylist: 62234-17371, 10h.24m
    easyprivacy: 30944-1183, 10h.24m
    plowe-0: 3667-983, 10h.24m
    ublock-abuse: 77-0, 10h.24m
    ublock-badware: 4319-115, 10h.24m
    ublock-filters: 31954-375, 10h.24m
    ublock-privacy: 258-2, 10h.24m
    ublock-quick-fixes: 480-20, 10h.24m
    ublock-unbreak: 1928-49, 10h.24m
    urlhaus-1: 6374-0, 10h.24m
filterset (user): [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 905 ms (selfie)
  maxAssetCacheWait: 377 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by blader-render** [comment]
@JobcenterTycoon 
I'll ready update and result like this. Use Firefox mobile
![az_recorder_20230118_235456](https://user-images.githubusercontent.com/120096290/213245304-7d12724a-36a9-461d-acda-308c80956c77.jpg)

**Comment by blader-render** [comment]
Same condition use chrome PC

**Comment by blader-render** [comment]
> 

Yes work, if I save the Code In my filter

**Comment by JobcenterTycoon** [comment]
`##+js(nobab)` or `##+js(nosiif, visibility, 1000)` ?

**Comment by blader-render** [comment]
> The `##+js(nobab)` one or `##+js(nosiif, visibility, 1000)` ?

Just this djxmaza.in,proviralhost.com##+js(nobab)
Work

**Comment by blader-render** [comment]
@JobcenterTycoon 
this issue must be fix again, because this site already update & detection adblock again. please. thanks
