### ISSUE TITLE
freepik.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#16393]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.freepik.com/search?format=search&query=matrix`

### Category

ads

### Description

showing pop up when click search button freepik

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/213327109-d350cc2d-2be9-4b51-87db-064742fb83aa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 111
filterset (summary): 
  network: 126374
  cosmetic: 143361
  scriptlet: 24797
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36800-3653, 14m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7856-3, 14m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-4, 14m
    IDN-0: 5430-357, 15m
    RUS-0: 39101-205, 15m
    fanboy-annoyance: 86311-405, 14m
    fanboy-cookiemonster: 44937-44937, 14m
    ublock-annoyances: 4752-82, 14m
  default: 
    user-filters: 20-0, never
    easylist: 62275-102, 15m
    easyprivacy: 30944-12291, 14m
    ublock-abuse: 77-1, 14m
    ublock-badware: 4325-113, 14m
    ublock-filters: 31859-483, 14m
    ublock-privacy: 258-52, 14m
    ublock-quick-fixes: 486-20, 14m
    ublock-unbreak: 1923-70, 14m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 29 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11254 ms (selfie)
  maxAssetCacheWait: 557 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    freepik.com: 9
    cdnpk.net: 2
    google.com: 1
    googletagmanager.com: 2
    prf.hn: 2
    ssm.codes: 1
```
</details>

**Comment by iam-py-test** [comment]
>```yml
>listset (total-discarded, last-updated): 
>  removed: 
>    plowe-0: null
>    urlhaus-1: null
>```

Why are Peter Lowe's list and URLHaus disabled? Peter's _might_ break something, but that should be reported instead of just completely disabling that list, as that decreases your protection against ads and tracking. URLHaus is unlikely to break anything, and provides valuable malware protection for Windows, Linux, and Android users.
Not saying that is the cause of this issue (I haven't tested)
Not part of the uBo team or anything, FYI. Just my two cents.

**Comment by stephenhawk8054** [comment]
Since the popup does not always happens, can anyone test this?

```adb
freepik.com##+js(set, FEATURE_DISABLE_ADOBE_POPUP_BY_COUNTRY, true)
```

**Comment by 3xploiton3** [comment]
> ```yaml
> urlhaus
> ```

thanks for suggestion, im using nextdns for dns level, i will activate URLHaus because they contain blocking list by IP level

**Comment by NicTanghe** [comment]
I am not getting that one but I do get a try adome stock one at the bottem right.

**Comment by 3xploiton3** [comment]
> ```css
> https://freepik.cdnpk.net
> ```

in my test, yeah i dont see popup again after add filter
