### ISSUE TITLE
[nsfw] 1tamilmv.autos: detection

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#16395]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.1tamilmv.autos/index.php?/forums/topic/167560-the-angry-birds-movie-2016-blu-ray-1080p-720p-27gb-1gb-x264-original-audios-dd51-640kbps-tamil-telugu-hindi-eng-esub-gdrive/&tab=comments`

### Category

detection

### Description

Detect ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/96541364/213382946-1f644cea-782b-4445-ba22-fb7ca63a1cb8.jpg

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 83723
  cosmetic: 123905
  scriptlet: 21799
  html: 996
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    fanboy-annoyance: 86309-477, 13h.33m
    ublock-annoyances: 4791-4, 13h.33m
  default: 
    user-filters: 10-0, never
    ublock-filters: 32595-92, 13h.35m
    ublock-badware: 4333-0, 13h.34m
    ublock-privacy: 305-0, 13h.33m
    ublock-abuse: 77-0, 13h.33m
    ublock-unbreak: 1941-1, 13h.33m
    ublock-quick-fixes: 500-0, 13h.33m
    adguard-mobile: 8697-10, 13h.40m
    easylist: 62275-485, 13h.33m
    easyprivacy: 30944-1189, 13h.33m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1555 ms (selfie)
  maxAssetCacheWait: 515 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    d3mzokty951c5w.cloudfront.net: 1
    displayvertising.com: 1
    ekgloczbsblg.com: 1
    googletagmanager.com: 1
    mhvllvgrefplg.com: 1
    profitablegatetocontent.com: 2
```
</details>

**Comment by mapx-** [comment]
maybe getting detection when click the download link

**Comment by MayaBi7** [comment]
Still showing ads

**Comment by mapx-** [comment]
for `mynewsmedia`

see https://github.com/uBlockOrigin/uAssets/issues/16399
