### ISSUE TITLE
Browserstack Pricing Blocked

### ISSUE THREAD

**Issue by gethubb** [uBlockOrigin/uAssets#16391]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [x] using a new, unmodified browser profile.

### Description

Pricing will not load unless I turn off UBO. Header appears regardless.

### URL(s) where the issue occurs.

https://www.browserstack.com/pricing

### uBO version

uBlock Origin 1.46.0

### Browser name and version

Firefox 108.0.2 

### Settings

N/A

**Comment by stephenhawk8054** [comment]
@gorhill The site detects if this CSS link is loaded properly or not

```
https://p.typekit.net/p.css?s=1&k=dhd2hrj&ht=tk&f=6848.6849.6851.6852&a=6381450&app=typekit&e=css
```

Its response is just

```css
/**/
```

I wonder if a neutered CSS redirection can help here?

**Comment by RomanFausek** [comment]
Hello @stephenhawk8054,

I noticed that our application is having problems loading fonts from `p.typekit.net` since around yesterday. Your reply is the closest thing that relates I found so far.

The file with just the comment inside gets thrown away with assets (fonts) from the network which leads to font fallback in our application.

You seem like a guy who knows what's happening, could you maybe point me in the right direction? It is not only a uBlock origin issue but an ad block extension issue in general.

**Comment by stephenhawk8054** [comment]
@RomanFausek Can you give exact URL where issue occurs?

**Comment by RomanFausek** [comment]
@stephenhawk8054 Unfortunately, the app is hidden behind a login, so there is no way. Would this be sufficient? It seems like something with the security policy together with ad blockers blocking `p.typekit.net`

![Uploading Screenshot 2023-01-19 at 10.53.03.png…]()
![Screenshot 2023-01-19 at 10 50 56](https://user-images.githubusercontent.com/8074997/213411729-ab1c2ca4-12ca-493d-8ca7-08626c7658f6.png)

**Comment by stephenhawk8054** [comment]
I mean at least we need the domain or the URL to whitelist the filter on that domain if any others can reproduce the issue. Otherwise, we don't know how to "fix" it.

**Comment by RomanFausek** [comment]
Why would you need to whitelist it? It doesn't make sense to me to blacklist the typekit at all. The problem might occur on every website using the typekit.

**Comment by RomanFausek** [comment]
Worth to mention, it is not a problem just of a uBlock...I guess you are taking some blacklist that is shared across multiple ad block extensions?

**Comment by stephenhawk8054** [comment]
`p.typekit.net` is blocked by EasyPrivacy, so it might be better to ask in EasyList repo:

https://github.com/easylist/easylist

---

@ryanbr I'm not sure about its privacy history. Looks like it's related to Adobe's trackers?

**Comment by RomanFausek** [comment]
Thank you for pointing me out. I will communicate it with them! ❤️

**Comment by garry-ut99** [comment]
Previous similiar reports:
- https://github.com/uBlockOrigin/uAssets/issues/10998
- https://github.com/AdguardTeam/AdguardFilters/issues/55288

**Comment by 0o5rlubm** [comment]
> Why would you need to whitelist it? It doesn't make sense to me to blacklist the typekit at all. The problem might occur on every website using the typekit.
> 
> IMO you are blocking something, you should not.

that's not typekit fonts that was blocked, only the tracking subdomain of typekit. As you can test by yourself, [large majority](https://publicwww.com/websites/%22p.typekit.net%22/) of websites using typekit are not impacted.

----

thanks @gorhill for the noop!

**Comment by krystian3w** [comment]
AdGuard rewrote block and allow to `removeparam` 7 months ago.

```adb
||p.typekit.net^$stylesheet,removeparam
```

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14716
