### ISSUE TITLE
ad.nl like sites probably needs injected script. 

### ISSUE THREAD

**Issue by Betsy25** [uBlockOrigin/uAssets#164]
### URL(s) where the issue occurs
[http://ad.nl](http://ad.nl) (Algemeen Dagblad = Dutch newspaper)

### Describe the issue
This site doesn't allow anyone who doesn't accept cookies access to the site.

### Screenshot(s)
[https://postimg.org/image/lpuf58sk9/](https://postimg.org/image/lpuf58sk9/)

### Versions
- Browser/version: Any
- uBlock Origin version: Any

### Settings
Default lists

### Notes
Most probably needs an injected script replace.
Thread on Easylist forums : [https://forums.lanik.us/viewtopic.php?f=100&t=33379](https://forums.lanik.us/viewtopic.php?f=100&t=33379)

**Comment by gorhill** [comment]
That is best addressed by an "annoyance" list. The notice is easy to accept, and one just need to set their browsers to erase all cookies and such data or install an extensions to take care of this if cookie et al. is a concern.
