### ISSUE TITLE
tubeload.tv

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1640]
### URL(s) where the issue occurs

`https://www.tubeload.tv/watch?v=hnjurTwkJ20`

### Describe the issue
 when you click a link from right pane (Next videos section), current tab gets closed and a new tab will be opened.

### Versions

- Browser/version: Chrome/64.0.3282.186 
- uBlock Origin version: 1.15.2

### Settings

Default

### Notes

Tabs get closed due to this filter from EasyList: `||fapmeth.com^$popup`. It's because after opening a link from right pane (next video section), current tab redirects to `tubeload.tv/po-direct.html` and results in loading `fapmeth.com`. Root cause is this script file `https://www.tubeload.tv/min/js/script-min.js`. 
I made following filters, but it results in closing player and also disabling conversion buttons at bottom of player. 

`tubeload.tv##script:inject(abort-on-property-read.js, adblockBypassPopupConfig)`
`tubeload.tv##script:inject(setTimeout-defuser.js)`

I would be thankful if you take a look at it.

Also, blocking `||tubeload.tv/sw_1540529.js*` seems has no effect and it still gets loaded in logger.

**Comment by mapx-** [comment]
see if works for you
`tubeload.tv##script:inject(addEventListener-defuser.js, click, trigger)`

**Comment by okiehsch** [comment]
`tubeload.tv##script:inject(setTimeout-defuser.js)` will break the site, this filter defuses **every** setTimeout call.
If you want to use `setTimeout-defuser`, the best practice is to first add `example.com##script:inject(setTimeout-logger.js)` then reload the site and open the console, where you will see a log of all `setTimeout` calls of the page your looking at.

Here is a part of that log for `tubeload.tv`
![aufzeichnen](https://user-images.githubusercontent.com/16838044/36815450-028efa1a-1cdb-11e8-8ddc-6a1977193f57.PNG)

As you can see disabling all setTimeout calls on a streaming site is a bad idea.

**Comment by okiehsch** [comment]
`tubeload.tv##script:inject(addEventListener-defuser.js, click, trigger)` will also break the conversion buttons.

**Comment by okiehsch** [comment]
I don't really get the issue, if I click a link from right pane the site triggers a popunder, which is closed as it should be by `||fapmeth.com^$popup`
![aufzeichn](https://user-images.githubusercontent.com/16838044/36815825-3463b610-1cdc-11e8-9e58-732afbed08fd.PNG)

Disabling the triggering of the popunder will lead to site breakage, the best way is probably the filter
mapx- mentioned, but I don't think it is really necessary in this case.

**Comment by nimasaj** [comment]
@mapx- , as okiehsch mentioned already, it breaks conversion buttons, and also breaks "Show more" under conversion buttons. In this link `https://www.tubeload.tv/watch?v=HzVJniRYgLs` "Show more" includes text.

**Comment by mapx-** [comment]
test this 1:
`tubeload.tv##script:inject(setTimeout-defuser.js, window.location.href, 300)`

**Comment by nimasaj** [comment]
The second one works perfectly. Thanks

**Comment by okiehsch** [comment]
That works on my end, but now you will have to close the tabs manually, or end up with a whole host of them after clicking on some links.

**Comment by okiehsch** [comment]
I really don't see the benefit, but nonetheless nice find mapx-.
It is your call if you want to add the filter.

**Comment by nimasaj** [comment]
@okiehsch , that's fine, as long as you don't need to open a tab from history to listen/watch again.

**Comment by okiehsch** [comment]
That is an actual benefit I did not think of.
