### ISSUE TITLE
file.org: ads

### ISSUE THREAD

**Issue by NicTanghe** [uBlockOrigin/uAssets#16402]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://file.org/extension/ocio`

### Category

ads

### Description

If i zap the adds and refresh the adds come back.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 102
filterset (summary): 
  network: 83774
  cosmetic: 38763
  scriptlet: 16838
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 32484-56, 18h.24m
    ublock-badware: 4324-0, 18h.23m
    ublock-privacy: 304-0, 18h.22m
    ublock-abuse: 77-0, 18h.21m
    ublock-unbreak: 1936-1, 18h.20m
    ublock-quick-fixes: 500-0, 18h.19m
    easylist: 62275-630, 18h.18m
    easyprivacy: 30940-1740, 18h.17m
    urlhaus-1: 6331-0, 18h.16m
    plowe-0: 3667-2, 18h.15m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 142 ms (selfie)
  maxAssetCacheWait: 65 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    file.org: 2
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
use the element picker
https://github.com/gorhill/uBlock/wiki/Element-picker

**Comment by garry-ut99** [comment]
> NicTanghe : If i zap the adds and refresh the adds come back.

`https://github.com/uBlockOrigin/uAssets/issues/16381#issuecomment-1387226377`
