### ISSUE TITLE
dzen.ru: ads

### ISSUE THREAD

**Issue by chainmoshko** [uBlockOrigin/uAssets#16401]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dzen.ru/video/watch/63ba80fb05f13443f3a06a13`

### Category

ads

### Description

advertisment in video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 100342
  cosmetic: 59636
  scriptlet: 17998
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39092-12, 1d.15h.58m
    easylist: 62140-59, 3d.16h.29m
    easyprivacy: 30931-1280, 3d.16h.30m
    plowe-0: 3667-903, 14h.41m
    ublock-abuse: 77-1, 1d.21h.47m
    ublock-badware: 4294-113, 3d.16h.28m
    ublock-filters: 31665-158, 3d.16h.27m
    ublock-privacy: 257-1, 1d.21h.48m
    ublock-quick-fixes: 486-16, 1h.58m
    ublock-unbreak: 1922-46, 3d.16h.26m
    urlhaus-1: 6211-0, 1h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7439 ms (selfie)
  maxAssetCacheWait: 514 ms
popupPanel: 
  blocked: 58
  blockedDetails: 
    mail.ru: 2
    yandex.ru: 56
```
</details>

**Comment by dimisa-RUAdList** [comment]
This is a new Yandex domain. Ads on this domain are blocked by the [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe).

See also:
https://github.com/uBlockOrigin/uAssets/issues/15119
https://github.com/uBlockOrigin/uAssets/issues/15181
https://github.com/uBlockOrigin/uAssets/issues/15854
