### ISSUE TITLE
world.taobao.com: cookie breakage, again

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#16403]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Cannot change region with uBO enabled. Exact same problem as issue #15974

### URL(s) where the issue occurs.

`https://world.taobao.com/`

### Screenshot(s)

There's a dropdown menu in the top left.
![Screen Shot 2022-12-10 at 11 51 24 PM](https://user-images.githubusercontent.com/54487525/206892420-040657d1-07df-46f5-a687-a73ccf9d02ed.png)
Here's a recording of the whole process (failing). Same result logged in or not.

https://user-images.githubusercontent.com/54487525/206892471-a9c8a1d3-0b75-4d59-923f-b7630bc2fd17.mov

_Originally posted by @contextnerror in https://github.com/uBlockOrigin/uAssets/issues/15974#issuecomment-1345483529_
            

### Notes

Fixed by adding `world.taobao.com https://ocservice.taobao.com/cookieController/processUserCookie script allow` to user rules or `@@/processusercookie?` to user filters. Misbehaving rule is `/processUserCookie?` in EasyPrivacy.

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83833
  cosmetic: 38834
  scriptlet: 16906
  html: 867
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32657-57, 2m
    ublock-badware: 4346-0, 2m
    ublock-privacy: 305-0, 2m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1938-1, 2m
    ublock-quick-fixes: 501-0, 2m
    easylist: 62310-631, 2m
    easyprivacy: 30944-1741, 2m
    urlhaus-1: 6299-0, 2m
    plowe-0: 3668-2, 2m
filterset (user): [empty]
urlRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1562 ms
  maxAssetCacheWait: 212 ms
```
</details>

**Comment by mapx-** [comment]
@ryanbr
