### ISSUE TITLE
earnbtc.pw: detection

### ISSUE THREAD

**Issue by blader-render** [uBlockOrigin/uAssets#16406]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://earnbtc.pw/dashboard`

### Category

detection

### Description

detection after login

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83744
  cosmetic: 38845
  scriptlet: 16943
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 100-36, never
    easylist: 62310-46, 7h.34m
    easyprivacy: 30944-1172, 7h.34m
    plowe-0: 3668-899, 7h.34m
    ublock-abuse: 77-0, 7h.34m
    ublock-badware: 4324-114, 7h.34m
    ublock-filters: 31864-130, 7h.34m
    ublock-privacy: 258-1, 7h.34m
    ublock-quick-fixes: 486-20, 7h.34m
    ublock-unbreak: 1921-47, 7h.34m
    urlhaus-1: 6216-0, 7h.34m
filterset (user): [array of 62 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2406 ms
  maxAssetCacheWait: 3760 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    earnbtc.pw: 2
    richinfo.co: 2
```
</details>

**Comment by blader-render** [comment]
@JobcenterTycoon 
after login still detection

**Comment by JobcenterTycoon** [comment]
Seems to be they use multiply layer of detection. Try

```
*$script,xhr,redirect-rule=noopjs,domain=earnbtc.pw
@@||static.surfe.pro/js/net.js$script,domain=earnbtc.pw
@@||earnbtc.pw/jse/vld.ads?ad_ids=$script,domain=earnbtc.pw
```

**Comment by blader-render** [comment]
> *$script,xhr,redirect-rule=noopjs,domain=earnbtc.pw
> @@||static.surfe.pro/js/net.js$script,domain=earnbtc.pw
> @@||earnbtc.pw/jse/vld.ads?ad_ids=$script,domain=earnbtc.pw

This work better

**Comment by JobcenterTycoon** [comment]
Added them 11 minutes ago https://github.com/uBlockOrigin/uAssets/commit/c930ddaf892ae781b6484b391dcb7a510a47c7a0 but it need a bit before its avaiable as a filter update
