### ISSUE TITLE
3kh0.github.io: ads

### ISSUE THREAD

**Issue by 17847814871842** [uBlockOrigin/uAssets#16404]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://3kh0.github.io/`

### Category

ads

### Description

an ad for "alienhub.xyz"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83745
  cosmetic: 38762
  scriptlet: 16842
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62275-46, 1d.3h.14m
    easyprivacy: 30941-1172, 1d.3h.13m
    plowe-0: 3667-898, 1d.21h.36m
    ublock-abuse: 77-0, 1d.3h.19m
    ublock-badware: 4320-114, 1d.3h.17m
    ublock-filters: 31690-129, 1d.3h.16m
    ublock-privacy: 257-1, 1d.3h.18m
    ublock-quick-fixes: 487-20, 2h.43m
    ublock-unbreak: 1923-46, 1d.3h.15m
    urlhaus-1: 6307-0, 2h.42m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3892 ms (selfie)
  maxAssetCacheWait: 1667 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`3kh0.github.io##[src^="https://hub.alienhub.xyz/"]`
