### ISSUE TITLE
fc-lc.com: detection

### ISSUE THREAD

**Issue by akaBross** [uBlockOrigin/uAssets#16419]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fc-lc.com/pAf7PxRa`

### Category

detection

### Description

detect adblock and try similar solutions and it didn't work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83585
  cosmetic: 38897
  scriptlet: 16840
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    spa-0: null
    spa-1: null
  default: 
    user-filters: 0-0, never
    easylist: 62224-46, 3d.7h.23m
    easyprivacy: 30941-1171, 3d.7h.22m
    plowe-0: 3668-900, 9d.6h.59m
    ublock-abuse: 77-0, 10d.7h.12m
    ublock-badware: 4325-114, 2d.3h.28m
    ublock-filters: 31688-126, 2d.3h.27m
    ublock-privacy: 258-1, 10d.7h.11m
    ublock-quick-fixes: 480-20, 23h.36m
    ublock-unbreak: 1923-46, 2d.3h.29m
    urlhaus-1: 6331-0, 23h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8779 ms (selfie)
  maxAssetCacheWait: 568 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    fc.lc: 2
    forfrogadiertor.com: 1
    googletagmanager.com: 1
    iclickcdn.com: 1
    nanesbewail.com: 1
    oaphoace.net: 1
```
</details>

**Comment by okiehsch** [comment]
Works fine for me.

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.
