### ISSUE TITLE
spiegel.de (anti adblock)

### ISSUE THREAD

**Issue by steffanson** [uBlockOrigin/uAssets#1641]
### URL(s) where the issue occurs

`http://www.spiegel.de/`

### Describe the issue

uBlock Origin gets detected and an overlay is displayed, asking to disable the blocker.

### Screenshot(s)

![spectacle j13431](https://user-images.githubusercontent.com/17642285/36841984-7cef9dae-1d4a-11e8-975e-7cb64f5b56b3.png)

### Versions

- Browser/version: 58.0.2
- uBlock Origin version: 1.15.10

### Settings

- Default + EasyList Germany

**Comment by mapx-** [comment]
test this filter
`||ad.doubleclick.net/ddm/ad/$image,redirect=1x1-transparent.gif,domain=spiegel.de`

**Comment by snottyone** [comment]
that filter works in chrome (nano adblocker/nano defender) when added to my filters, it does not work in palemoon (uBlock Origin)

**Comment by mnowiasz** [comment]
The filter doesn't work here when I add it to my filters -  Chromium 64.0.3282.167, uBlock origin, Nano Defender.

**Comment by mapx-** [comment]
what about
`@@||ad.doubleclick.net/ddm/ad/$image,domain=spiegel.de`
or
`||spiegel.de/*40*$script`

**Comment by gorhill** [comment]
@mnowiasz Does it work if Nano Defender is disabled?

**Comment by mnowiasz** [comment]
@mapx- 

||spiegel.de/*40*$script works for me :+1: 

@gorhill Nope - doesn't matter if Nano Defender is on or off.

**Comment by mapx-** [comment]
@steffanson  feedback ?

**Comment by snottyone** [comment]
||spiegel.de/*40*$script  works in Palemoon/uBlock, thank you VERY much.

**Comment by steffanson** [comment]
> @steffanson feedback ?

`||spiegel.de/*40*$script` works for me as well. Thanks!

**Comment by gorhill** [comment]
@mapx- Just bloccking this one script is sufficient on my side:

    ||spiegel.de/*/messaging-V8-40.js$script

**Comment by Unrepentant-Atheist** [comment]
||ad.doubleclick.net/ddm/ad/$image,redirect=1x1-transparent.gif,domain=spiegel.de

Works for me in Firefox

**Comment by uBlock-user** [comment]
Why whitelist or redirect when you can fix it with these filters ?

```
||spiegel.de/layout/js/http/spaab*.js
||spiegel-de.spiegel.de^
```

**Comment by snottyone** [comment]
and the popup is back as of today, please help (again)

**Comment by mapx-** [comment]
I cannot reproduce the issue, did you force an update of all lists ?

**Comment by snottyone** [comment]
everything force-updated, still popup

**Comment by snottyone** [comment]
try http://www.spiegel.de/wirtschaft/unternehmen/elizabeth-holmes-us-boersenaufsicht-stellt-betrug-bei-bluttest-startup-fest-a-1198153.html

**Comment by mapx-** [comment]
What about your uBo version ?

**Comment by snottyone** [comment]
i have to use this:
uBlock v0.9.5.0.1-let-fixed
because i'm using Palemoon (FF fork that still has XUL)
if there is a way to install origin, do tell

**Comment by mapx-** [comment]
Did you see this
https://addons.palemoon.org/addon/ublock0-updater/

**Comment by snottyone** [comment]
have that installed

**Comment by mapx-** [comment]
In that page is about 1.3.0, yours is outdated.

**Comment by snottyone** [comment]
re-installed, shows same version number when installed.
i also tried to install uBlock ORIGIN from the github page, only shows my an XML even when noscript is given a github exception for XSS :(

**Comment by snottyone** [comment]
save as also saves an xml instead of an xpi

**Comment by snottyone** [comment]
update: i managed to download and install uBlock Origin 1.15.10 (tried with 4 browsers, and the only one that would LET ME download the xpi was ... IE11)
had to re-add the ||spiegel.de/*40*$script filter, works.

i apologize.
