### ISSUE TITLE
lsrelay-config-production.s3.amazonaws.com: [unknown]

### ISSUE THREAD

**Issue by woolfblood22** [uBlockOrigin/uAssets#16412]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://lsrelay-config-production.s3.amazonaws.com/70466a27ff545b502cac54581636a5d5078c0e42e91fd8568e307cc22c2d7073/block_screen.html?id=1b0c961d-6b99-4324-a30b-c220f1003e41`

### Category

[unknown]

### Description

turn it off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 86519
  cosmetic: 38744
  scriptlet: 16838
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64996-53, 2d.2h.14m
    easyprivacy: 30944-1171, 2d.2h.13m
    plowe-0: 3668-897, 10d.2h.8m
    ublock-abuse: 77-0, 2d.25m
    ublock-badware: 4330-111, 2d.22m
    ublock-filters: 31684-108, 2d.21m
    ublock-privacy: 258-1, 2d.24m
    ublock-quick-fixes: 486-16, 1h.20m
    ublock-unbreak: 1923-47, 2d.20m
    urlhaus-1: 6307-0, 1h.19m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2484 ms (selfie)
  maxAssetCacheWait: 1491 ms
popupPanel: 
  blocked: 0
```
</details>YAML

**Comment by mapx-** [comment]
Explain what's the issue to be fixed, provide the steps to reproduce it

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/15836

related https://support.google.com/chromebook/thread/195802587/somebody-please-remove-the-https-lsrelay-config-production-s3-amazonaws-com-block-from-chrome?hl=en
"This forum does not support managed devices, managed accounts, or attempts to bypass parental, school, or work restrictions. You should contact your IT administrator for support."
