### ISSUE TITLE
https://onlinestudentseva.com/ detection

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#16413]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Adblock detection
how to reproduce:
1. go to https://onlinestudentseva.com/ scroll bit down, wait 3 seconds
2. warning will appear
3. 
![image](https://user-images.githubusercontent.com/57501353/213556042-08739664-da4e-4a2f-8b07-62ec57c68150.png)
![image](https://user-images.githubusercontent.com/57501353/213556182-e82de10a-cf60-4d4d-9bd8-a8d4cf79bf22.png)

### URL(s) where the issue occurs.

https://onlinestudentseva.com/

### Screenshot(s)

![image](https://user-images.githubusercontent.com/57501353/213556027-0c6ed5ec-f5c8-4a01-9ba0-8238505c705f.png)

### uBO version

1.46

### Browser name and version

chrome 109 on windows 10

### Settings

none

**Comment by erik9012** [comment]
Would it be okay if I would report multiple sites in 1 issue? I have this exact warning adlbokc detection thing on multiple sites.

**Comment by mapx-** [comment]
Better keeping separate issues
