### ISSUE TITLE
focus.de (Anti Adblock)

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#1642]
### URL(s) where the issue occurs

`https://www.focus.de`

### Describe the issue

Anti-Adblock overlay

### Screenshot(s)

https://ibb.co/daYgVx

### Versions

- Browser/version: Firefox 58.0.2
- uBlock Origin version: 1.15.10

### Settings

- default filters + Easylist Germany

Maybe the same measure as on spiegel.de today?

**Comment by gorhill** [comment]
This?

    ||focus.de/src/js/spmsg*.js$script

**Comment by TonyTough** [comment]
> This?
> 
> ||focus.de/src/js/spmsg*.js$script

Yes, it works.
Thanks!
