### ISSUE TITLE
2nftart.com: ads

### ISSUE THREAD

**Issue by afkvido** [uBlockOrigin/uAssets#16422]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://2nftart.com/NFT-Art-Gold-Effect.htm`

### Category

ads

### Description

Still getting an ad on this page:
```html
<a href="https://accounts.binance.com/en/register?ref=28077397" title="Sign up, Get 5% discount for your first purchase of Bitcoin and other Crypto currency." target="_blank" rel="nofollow">
     <img src="https://2nftart.com/binance.png" style="width:100%; max-width:400px;" alt="Sign up, Get 5% discount for your first purchase of Bitcoin and other Crypto currency.">
</a>
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1039" alt="Screenshot 2023-01-19 at 8 25 22 PM" src="https://user-images.githubusercontent.com/69060894/213617084-a73b9bb4-20c6-4ca2-9f0d-4292a849c009.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 96154
  cosmetic: 184148
  scriptlet: 24238
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62442-92, 4d.18h.58m
    adguard-social: 19580-828, 4d.18h.59m
    fanboy-annoyance: 86314-6171, 19h.57m
    fanboy-cookiemonster: 44939-44939, 19h.56m
    fanboy-social: 23492-23492, 6d.22h.58m
    fanboy-thirdparty_social: 69-21, 19h.55m
    ublock-annoyances: 4749-213, 4d.19h
  default: 
    user-filters: 25-5, never
    easylist: 62310-103, 19h.53m
    easyprivacy: 30944-1260, 19h.54m
    plowe-0: 3668-903, 9d.2h.50m
    ublock-abuse: 77-0, 4d.18h.56m
    ublock-badware: 4294-114, 4d.19h.2m
    ublock-filters: 31659-516, 4d.19h.1m
    ublock-privacy: 257-9, 4d.18h.55m
    ublock-quick-fixes: 486-16, 19h.52m
    ublock-unbreak: 1927-51, 4d.18h.57m
    urlhaus-1: 6211-0, 19h.51m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 387 ms (selfie)
  maxAssetCacheWait: 346 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    addthis.com: 1
    doubleclick.net: 2
    facebook.com: 2
    facebook.net: 2
    googletagmanager.com: 1
    twitter.com: 1
    youtube.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`2nftart.com##[href^="https://accounts.binance.com/"]`

@ryanbr

**Comment by afkvido** [comment]
Thank you!
