### ISSUE TITLE
offerup.com: ads

### ISSUE THREAD

**Issue by HaxNobody** [uBlockOrigin/uAssets#16421]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://offerup.com/search?q=ptz`

### Category

ads

### Description

ads that look like products still make it through

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 95893
  cosmetic: 184383
  scriptlet: 24284
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62650-93, 22h.3m
    adguard-social: 19641-829, 22h.4m
    fanboy-annoyance: 84987-5178, 6d.5h.50m
    fanboy-cookiemonster: 44990-44792, never
    fanboy-social: 23510-23494, never
    fanboy-thirdparty_social: 69-21, 7d.5h.44m
    ublock-annoyances: 4752-213, 3h.42m
  default: 
    user-filters: 17-0, never
    easylist: 62107-103, 4d.22h.9m
    easyprivacy: 30944-1259, 3h.46m
    plowe-0: 3666-901, 5d.7h.9m
    ublock-abuse: 77-0, 10d.2h.44m
    ublock-badware: 4342-113, 3h.43m
    ublock-filters: 31700-513, 3h.44m
    ublock-privacy: 258-9, 10d.6h.46m
    ublock-quick-fixes: 487-20, 5m
    ublock-unbreak: 1911-52, 3h.45m
    urlhaus-1: 6211-0, 22h.2m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 40 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 279 ms (selfie)
  maxAssetCacheWait: 302 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    adnxs.com: 1
    appboycdn.com: 1
    appsflyer.com: 1
    branch.io: 1
    d2hrivdxn8ekm8.cloudfront.net: 1
    doubleclick.net: 1
    facebook.net: 1
    googletagmanager.com: 1
    liadm.com: 1
    optimizely.com: 3
    simility.com: 1
    statsigapi.net: 12
```
</details>

**Comment by mapx-** [comment]
Do you mean "Promoted" ones ?

`offerup.com##a[title]:has-text(Promoted)`

**Comment by mapx-** [comment]
@ryanbr

**Comment by HaxNobody** [comment]
> Do you mean "Promoted" ones ?
> 
> `offerup.com##a[title]:has-text(Promoted)`
> 

No, it's the ones that say "AD" in the bottom right corner in a small gray box. I found that if I enabled one of the Adguard lists that would fix the problem, but not with the stock filter list.

**Comment by mapx-** [comment]
ok, then:

`offerup.com##a[href^="https://www.bing.com/aclick?"]`

@ryanbr

**Comment by HaxNobody** [comment]
They aren't all Bing, but what I have noticed is that they are all non-relative links, whereas all the normal items use relative links. Not sure if it's possible to target them that way instead?

**Comment by mapx-** [comment]
other possible filter

`offerup.com##a[title]:has(span:has-text("Ad"))`

**Comment by mapx-** [comment]
or
`offerup.com##a[title]:not([href^="/item"])`
