### ISSUE TITLE
anhautobot.com: detection

### ISSUE THREAD

**Issue by Kaisarisk** [uBlockOrigin/uAssets#16426]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://anhautobot.com/api/bypass/?name=https://anhautobot.com/api/bypass/api/?url=https://uniqueten.net/backup/w/?get=60M7&__cf_chl_rt_tk=Hingx3h2p1zhIVqpkIsvyCXUjcekjuC1xGjX9wr8pvw-1674215862-0-gaNycGzNCNE&timer=20000`

### Category

detection by adblock

### Description

de

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83818
  cosmetic: 38827
  scriptlet: 16911
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 51-0, never
    easylist: 62237-46, 2d.2h.40m
    easyprivacy: 30944-1172, 2d.2h.40m
    plowe-0: 3667-899, 2d.2h.40m
    ublock-abuse: 77-0, 2d.2h.40m
    ublock-badware: 4320-114, 2d.2h.40m
    ublock-filters: 31846-150, 2d.2h.40m
    ublock-privacy: 258-1, 2d.2h.40m
    ublock-quick-fixes: 480-21, 2d.2h.39m
    ublock-unbreak: 1923-47, 2d.2h.40m
    urlhaus-1: 6374-0, 2d.2h.39m
filterset (user): [array of 33 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2889 ms (selfie)
  maxAssetCacheWait: 809 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    anhautobot.com: 1
    a-ads.com: 1
    ladnova.info: 2
    mndsrv.com: 3
    nx.tc: 1
    richinfo.co: 1
    xawlop.com: 1
    xeryiar.gq: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Test `@@||scriptsoup.nx.tc/prebid.js$script`

**Comment by Kaisarisk** [comment]
work, thanks
