### ISSUE TITLE
geblitzt.de: breakage

### ISSUE THREAD

**Issue by p0nyh0f** [uBlockOrigin/uAssets#16429]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.geblitzt.de/unterlagen-einreichen/`

### Category

breakage

### Description

Cookie banner is blocked.
Without making a choice on the cookie banner, the website breaks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 163926
  cosmetic: 229221
  scriptlet: 37784
  html: 994
listset (total-discarded, last-updated): 
  added: 
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-0, 3d.20h.47m
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-10, 3d.20h.46m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-5, 1d.20h.33m
    https://winhelp2002.mvps.org/hosts.txt: 8730-317, 3d.20h.48m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36775-4310, 3d.20h.41m
    ublock-annoyances: 4729-8, 1d.22h.51m
    adguard-generic: 67779-5939, 1d.22h.50m
    adguard-mobile: 8696-218, 1d.22h.54m
    adguard-annoyance: 62626-4990, 1d.22h.52m
    adguard-social: 19631-1102, 1d.22h.56m
    fanboy-thirdparty_social: 69-0, 13h.45m
    fanboy-annoyance: 86365-70226, 13h.47m
    fanboy-cookiemonster: 44987-260, 13h.46m
    fanboy-social: 23494-31, 3d.20h.49m
    dpollock-0: 11397-1748, 10d.23h.19m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32484-149, 1d.22h.53m
    ublock-badware: 4334-0, 1d.22h.49m
    ublock-privacy: 304-0, 6d.1h.28m
    ublock-abuse: 77-0, 6d.1h.29m
    ublock-unbreak: 1936-0, 1d.22h.55m
    easylist: 62174-1095, 3d.20h.51m
    easyprivacy: 30938-12886, 3d.20h.50m
    plowe-0: 3666-1768, 3d.20h.52m
    DEU-0: 6142-12, 31m
    urlhaus-1: 6526-0, 30m
    ublock-quick-fixes: 504-1, 32m
filterset (user): [empty]
trustedset: 
  added: [array of 69 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4700 ms (selfie)
  maxAssetCacheWait: 3433 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by okiehsch** [comment]
@ryanbr for your cookie liss
`geblitzt.de#@##cookie-consent`

@p0nyh0f add that filter to your personal filter list.
