### ISSUE TITLE
interestingengineering.com: detection

### ISSUE THREAD

**Issue by her01n** [uBlockOrigin/uAssets#16425]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://interestingengineering.com/innovation/nasa-nuclear-propulsion-concept-mars-45-days`

### Category

detection

### Description

The website says "Attention! Adblocker detected." and disallows reading the article.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Snímka obrazovky zo dňa 2023-01-20 11-12-41](https://user-images.githubusercontent.com/10198016/213670797-e7d0a8c4-4442-45c1-838c-aca67cf08131.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83770
  cosmetic: 38608
  scriptlet: 16807
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32311-51, 2d.15h.13m
    ublock-badware: 4296-0, 2d.15h.12m
    ublock-privacy: 305-0, 9d.20h.21m
    ublock-abuse: 77-0, 9d.20h.20m
    ublock-unbreak: 1936-1, 2d.1h.51m
    ublock-quick-fixes: 500-0, 15h.15m
    easylist: 62312-639, 15h.18m
    easyprivacy: 30944-1743, 15h.17m
    urlhaus-1: 6307-0, 15h.14m
    plowe-0: 3666-2, 5d.22h.9m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 306 ms (selfie)
  maxAssetCacheWait: 163 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    cloudflareinsights.com: 3
    connatix.com: 2
    doubleclick.net: 7
    googletagmanager.com: 1
    ntv.io: 1
    outbrain.com: 1
    proper.io: 1
    youtube.com: 2
```
</details>

**Comment by mapx-** [comment]
- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- restart the system, reopen the browser, test again.

**Comment by TheGamer1002** [comment]
So I could actually reproduce this after resetting uBO and resetting cache, etc. If this issue isn't reopened, I'm going to create another issue.
Also, @mapx- , if you look at the details drop-down, you can see this user has no other lists. 
I'd have to pay 70 bucks to see this article without ads.

**Comment by TheGamer1002** [comment]
I would also like to say it can ***literally be solved just by deleting a few elements***. It isn't a hard thing to fix.

**Comment by mapx-** [comment]
Keep commenting here, don't open another one.
Are there some specific steps to get the issue ?

**Comment by stephenhawk8054** [comment]
> I would also like to say it can _**literally be solved just by deleting a few elements**_. It isn't a hard thing to fix.

It's not about hard or easy. Thing is, we don't know what to "fix" if we cannot reproduce the issue.

**Comment by TheGamer1002** [comment]
I apologize for my tone. I was a bit angry at the time for unrelated reasons.
It appears that the blocker element is at `/html/body/div[4]/div`, div id `adblockermodal`.

**Comment by stephenhawk8054** [comment]
I still cannot reproduce the issue

![image](https://user-images.githubusercontent.com/66517106/214008145-27337450-79ac-4982-8e29-115d530a5446.png)


Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by her01n** [comment]
I have:
- cleared cookies
- reset ubo settings, updated the filter lists, no other lists are configured
- disabled all the other extensions
- i am using firefox and no antivirus/antimalware
- rebooted
The issue is solved, the warning is not displayed and the web works.
The web works also after i have re-enabled all the extensions.

**Comment by mapx-** [comment]
Are you arriving on that page being redirected from other site ?

**Comment by her01n** [comment]
i tested both, directly going to https://interestingengineering.com/
and following link from https://www.reddit.com/r/Futurology/comments/10ioz6u/more_moores_law_through_2d/
Before clearing cookies and reseting settings and extensions, both were not working and now both work.

**Comment by mapx-** [comment]
> The issue is solved, the warning is not displayed and the web works

finally
