### ISSUE TITLE
[nsfw] cryptowin.io: ads

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#16424]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cryptowin.io/faucet`

### Category

ads

### Description

kosmetic

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 100751
  cosmetic: 59604
  scriptlet: 18072
  html: 871
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32657-148, 23h.19m
    ublock-badware: 4346-0, 23h.19m
    ublock-privacy: 305-0, 23h.19m
    ublock-abuse: 77-0, 23h.19m
    ublock-unbreak: 1934-1, 23h.19m
    ublock-quick-fixes: 501-0, 23h.19m
    easylist: 62310-521, 23h.19m
    easyprivacy: 30944-1760, 23h.19m
    urlhaus-1: 6216-0, 23h.19m
    plowe-0: 3668-2, 23h.19m
    RUS-0: 39123-172, 23h.19m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1468 ms (selfie)
  maxAssetCacheWait: 461 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    cryptowin.io: 3
    coinzillatag.com: 3
    google-analytics.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
The ads are coming from `bmcdn5.com`

**Comment by lyubomyrhv** [comment]
no completed.

**Comment by JobcenterTycoon** [comment]
What is wrong?

**Comment by garry-ut99** [comment]
And what about these: `bmcdn[6-10].com`, I don't have actual cases (websites) where they appear however, but I guess the serve the same purpose, tbu thiss is only guessing, maybe somebody else can verify it.

**Comment by JobcenterTycoon** [comment]
Just ping us when you see unblocked ads
