### ISSUE TITLE
marketingsentinel.com: ads

### ISSUE THREAD

**Issue by george-photon** [uBlockOrigin/uAssets#16423]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://marketingsentinel.com/2023/01/07/jackson-financial-inc-nysejxn-has-recovered-18-42-to-date-but-an-additional-34-46-is-possible/`

### Category

ads

### Description

Sections marked "Sponsored" are still included in the article.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/107697082/213669855-e11e3f3c-8eb7-4426-9ceb-1d41f0f57a80.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83771
  cosmetic: 38881
  scriptlet: 16842
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62172-46, 5d.9h.5m
    easyprivacy: 30938-1171, 4d.10h.47m
    plowe-0: 3668-900, 11d.15h.41m
    ublock-abuse: 77-0, 3d.14h.39m
    ublock-badware: 4325-114, 1d.8h.14m
    ublock-filters: 31678-126, 3d.14h.38m
    ublock-privacy: 257-1, 3d.14h.40m
    ublock-quick-fixes: 487-20, 41m
    ublock-unbreak: 1909-47, 42m
    urlhaus-1: 6577-0, 40m
filterset (user): [empty]
trustedset: 
  added: [array of 21 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1671 ms (selfie)
  maxAssetCacheWait: 213 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
to be reported at Easylist repository
@ryanbr 

add
`marketingsentinel.com##[class^="marke"]:not([href*="marketingsentinel.com"])`
