### ISSUE TITLE
Advertising posts on FB

### ISSUE THREAD

**Issue by King-Leo-1966** [uBlockOrigin/uAssets#16431]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Facebook has recently seen a resurgence of sponsored advertising. It's annoying! Apparently the filters have been bypassed. Please correct.

### A specific URL where the issue occurs.

https://www.facebook.com/

### Steps to Reproduce

Call up the page and normally designed posts appear in the feed. These carry the indication sponsored and are advertising contributions. 

### Expected behavior

As before, ad-free feed.

### Actual behavior

Previously blocked advertisements suddenly reappear.

### Configuration

I have no idea what to write about this.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/3367
