### ISSUE TITLE
[nsfw] tvhayyy.org: ads

### ISSUE THREAD

**Issue by dvdvn** [uBlockOrigin/uAssets#16438]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://tvhayyy.org/`

### Category

ads

### Description

vẫn còn barner quảng cáo

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83984
  cosmetic: 38742
  scriptlet: 16845
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    VIE-1: null
  default: 
    user-filters: 8-3, never
    easylist: 62208-46, 1d.18h.13m
    easyprivacy: 30941-1172, 1d.18h.11m
    plowe-0: 3668-898, 1d.18h.14m
    ublock-abuse: 77-0, 1d.18h.9m
    ublock-badware: 4325-114, 1d.18h.7m
    ublock-filters: 31697-129, 1d.18h.6m
    ublock-privacy: 258-1, 1d.18h.8m
    ublock-quick-fixes: 487-20, 17h.51m
    ublock-unbreak: 1923-46, 1d.18h.5m
    urlhaus-1: 6577-0, 17h.50m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 559 ms (selfie)
  maxAssetCacheWait: 328 ms
popupPanel: 
  blocked: 7
  no-popups: true
  blockedDetails: 
    dataqq.net: 5
    googletagmanager.com: 2
```
</details>

**Comment by ghajini** [comment]
@dvdvn 
enable back `VIE: ABPVN List` adblocking filter list which fixes ads on this site

**Comment by ghajini** [comment]
iam not iOS user so can't advice
