### ISSUE TITLE
inpaok.com: ads

### ISSUE THREAD

**Issue by Prowler73** [uBlockOrigin/uAssets#16439]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://inpaok.com/`

### Category

ads

### Description

Adverts are coming in

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/56029569/213842828-412fe7c8-cb69-442f-a572-9401c1384fad.png

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 84823
  cosmetic: 38890
  scriptlet: 16835
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32475-38, 3d.3h.34m
    ublock-badware: 4334-0, 3d.3h.33m
    ublock-privacy: 304-0, 5d.4h.47m
    ublock-abuse: 77-0, 7d.21h.15m
    ublock-unbreak: 1936-1, 3d.3h.32m
    easylist: 62174-627, 5d.4h.45m
    easyprivacy: 30931-1741, 5d.4h.44m
    urlhaus-1: 7608-0, 3h.22m
    plowe-0: 3667-2, 11h.24m
    ublock-quick-fixes: 504-16, 3h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 502 ms
  maxAssetCacheWait: 246 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    inpaok.com: 2
    addthis.com: 1
    adman.gr: 2
    dalecta.com: 1
    doubleclick.net: 1
    facebook.com: 3
    gblcdn.com: 1
    google-analytics.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    googletagservices.com: 1
    igaming-service.io: 1
    mediawayss.com: 1
    quantcast.com: 1
    quantserve.com: 1
```
</details>

**Comment by ghajini** [comment]
@Prowler73 
enable **GRC: Greek AdBlock Filter** filter list  under **ublock settings > regions, languages** which is **default** for *GReek** languages

**Comment by mapx-** [comment]
add
`inpaok.com##[href^="https://gml-grp.com/C.ashx"]`
