### ISSUE TITLE
ckk.ai: detection

### ISSUE THREAD

**Issue by KhairulNnN** [uBlockOrigin/uAssets#16436]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ckk.ai/SEAYO`

### Category

detection

### Description

The site keep detecting ublock origin. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 98
filterset (summary): 
  network: 86382
  cosmetic: 28652
  scriptlet: 16783
  html: 865
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32451-273, never
    ublock-badware: 4235-0, never
    ublock-privacy: 302-1, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1940-2, never
    ublock-quick-fixes: 464-0, never
    adguard-mobile: 8715-354, never
    easylist: 61524-17673, never
    easyprivacy: 30820-1739, never
    urlhaus-1: 8695-0, never
    plowe-0: 3671-3, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5468 ms
  maxAssetCacheWait: 50 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    ckk.ai: 2
    forfrogadiertor.com: 1
    googletagmanager.com: 1
    iclickcdn.com: 1
    trustbummler.com: 1
    upgulpinon.com: 2
```
</details>

**Comment by ghajini** [comment]
@KhairulNnN 

update filters like this

**addons >add on manager > ublock origin > settings => filter lists > purge all caches > update now**

( `https://youtu.be/Onr0frormCU`)

check website, if you are still getting antiadblock, provide original website from where you land on this website

**Comment by KhairulNnN** [comment]
> Update Your Filters Or Add In This In My Filters -
> ```
> oko.sh,ckk.ai##.td-container-wrap.td-main-content-wrap, .td-container-wrap.td-sub-footer-container
> @@||ckk.ai^$ghide
> ```

Thanks man , before sometimes it detect and sometimes it does not. Solved after add to your.
