### ISSUE TITLE
duden.de: detection

### ISSUE THREAD

**Issue by AstragoDE** [uBlockOrigin/uAssets#16430]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.duden.de/`

### Category

detection

### Description

Duden detects the ad blocker when I visit the website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/51675359/213723861-f2de937e-d08f-45a7-8dc4-599fbfbb3f7d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 143474
  cosmetic: 89609
  scriptlet: 33481
  html: 996
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://get.letsblock.it/list/72b6fe83-6670-4913-b2c7-0f9bc9a97d71: 5839-4, now
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
    adguard-generic: 67810-5874, now
    adguard-mobile: 8714-18, now
    adguard-spyware-url: 886-4, now
    block-lan: 44-0, now
    curben-phishing: 19649-0, now
    curben-pup: 187-0, now
    ublock-annoyances: 4750-4, now
    DEU-0: 6142-1, now
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36809-3758, never
  default: 
    user-filters: 34-0, never
    ublock-filters: 32697-113, now
    ublock-badware: 4364-5, now
    ublock-privacy: 305-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1910-2, now
    ublock-quick-fixes: 504-0, now
    easylist: 62162-526, now
    easyprivacy: 30950-12227, now
    urlhaus-1: 6526-0, now
filterset (user): [array of 34 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    chrome-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 42 redacted]
  removed: 
    no-csp-reports: * true
modifiedUserSettings: 
  cloudStorageEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 624 ms (selfie)
  maxAssetCacheWait: 499 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    duden.de: 1
    doubleclick.net: 1
    yieldlove.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
I get no detection

**Comment by okiehsch** [comment]
Me neither.

**Comment by JobcenterTycoon** [comment]
I see they changed `detectaab` to `checkAab` to counter the scriptlet but the adblock detection is still defused by the whitelist filter.

Its not a inline script so the entire detection stuff can be blocked with `||duden.de/modules/custom/duden_ads/`

**Comment by okiehsch** [comment]
If you think it is worthwhile, block it.

**Comment by JobcenterTycoon** [comment]
I also updated the scriptlet and excluded `mentor.duden.de` to be sure

**Comment by AstragoDE** [comment]
It works now. Thank you.

**Comment by JobcenterTycoon** [comment]
Maybe the `no-fetch-if` scriptlet can be improved to cover cases like this. There are 2 ways which sites use to check if a request got blocked or defused by uBO

`response.url`: Should be the blocked URL. uBO returns a empty string.
The length of `response.text()` should be extendable. uBO returns 0 length.

A example detection script:

```
async function detectAdblock() {
    try{
        var googlead = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js';
        var response = await fetch(googlead);
        var result = await response.text();
        if (result.length < 1000) {
            console.log("Adblock detected! response length is " + result.length + " but it should be larger than 1.000" );
        }
        if (response.url != googlead) {
            console.log("Adblock detected! response URL is " + response.url + " but it should be " + googlead);
        }
    }catch(e){
        console.log("Adblock detected! The request got blocked");
    }finally{
        // Unbreak the site when the script got executed
    }
  }
detectAdblock();
```

Real world cases:

`duden.de` - `response.url` checking
`theappstore.org` - `response.text()` length checking
`aosmark.com` - `response.text()` length checking

related Adguard issue: https://github.com/AdguardTeam/Scriptlets/issues/216

@gorhill

**Comment by JobcenterTycoon** [comment]
Demo page:  `https://adblock-testing.glitch.me/`

**Comment by hrrd** [comment]
i also got a detection. How to bypass?

**Comment by JobcenterTycoon** [comment]
@hrrd it got fixed now. Force update the filter lists to get the fix directly
