### ISSUE TITLE
Anti Adblock  urbia.de, sport1.de

### ISSUE THREAD

**Issue by Erikuio** [uBlockOrigin/uAssets#1644]
Browser: FF 58.0.2

Anti Adblock Layer: 
```
http://www.urbia.de
https://www.sport1.de/
```

**Comment by gorhill** [comment]
When creating a new issue, please mind [ISSUE_TEMPLATE](https://github.com/uBlockOrigin/uAssets/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by okiehsch** [comment]
The anti-adblock layer at `sport1.de` is already fixed.

I do not see any anti-adblock layer at `urbia.de`, the only thing I can reproduce is a broken video player.
Fixed by adding
`@@||static.urbia.de/*/gujAd.js$script,first-party`

**Comment by Erikuio** [comment]
Sorry my fault. -> after disabling AAK Antiadblock Filter everything layer disappeared.

ariva.de -> antiadblock picture
