### ISSUE TITLE
ensonhaber.com

### ISSUE THREAD

**Issue by tnr20** [uBlockOrigin/uAssets#16446]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Video Players on this Website dont work. i must disable the uBlock Origin add-on to play the Videos.

### URL(s) where the issue occurs.

`https://www.ensonhaber.com/dunya/bursada-gorulen-merceksi-bulut-dunyanin-gundemine-oturdu`

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/49328456/213875070-8b23dc17-eafd-4020-a5bf-e069a5a0cf7c.png)

![grafik](https://user-images.githubusercontent.com/49328456/213875122-8de62c27-32c1-45e4-9a8c-8b9e95f437bb.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 86501
  cosmetic: 42651
  scriptlet: 16838
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32481-38, 3d.7h.31m
    ublock-badware: 4329-0, 3d.7h.30m
    ublock-privacy: 304-0, 3d.7h.28m
    ublock-abuse: 77-0, 2d.20h.37m
    ublock-unbreak: 1936-1, 2d.20h.36m
    ublock-quick-fixes: 504-16, 50m
    easylist: 62208-619, 2d.20h.34m
    easyprivacy: 30940-1769, 2d.20h.33m
    urlhaus-1: 6900-0, 49m
    plowe-0: 3667-2, 2d.20h.31m
    DEU-0: 6142-14, 19h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1071 ms (selfie)
  maxAssetCacheWait: 227 ms
```
</details>

**Comment by mapx-** [comment]
Turkish page, enable `TUR: AdGuard Turkish`
