### ISSUE TITLE
wrangler.narvar.com: breakage

### ISSUE THREAD

**Issue by Vjedi729** [uBlockOrigin/uAssets#16445]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wrangler.narvar.com/tracking/wrangler/FEDEX?order_number=24321391&service=FG&dzip=61802&order_date=20232001T02:54-45+0000&tracking_numbers=630770317535&ship_date=20230120&utm_campaign=shipment_notification&utm_source=system&utm_medium=email&utm_content=Tracking+Number&utm_term=SFCC_Shipment_Notification&ktb_team=ecom&ktb_tac=paid&ktb_obj=do&subid=797389664&emid=de4d5d744518b4554d00107200fb79b62b4ac73e5dcde0108d21834bf0aa2257&jobid=2971088`

### Category

breakage

### Description

This is the most obvious of the issues with the Wrangler website. The entire page is a white rectangle.

It also seems to prevent adding to cart while uBO is on. It doesn't seem deliberate, but it might be.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/6351252/213874952-6710e731-549e-4931-953b-70a7403e87f9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83730
  cosmetic: 38870
  scriptlet: 16834
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32469-50, 4d.16h.7m
    ublock-badware: 4296-0, 4d.16h.6m
    ublock-privacy: 304-0, 4d.16h.5m
    ublock-abuse: 77-0, 13h.9m
    ublock-unbreak: 1936-1, 4d.16h.3m
    ublock-quick-fixes: 472-0, 4d.16h.1m
    easylist: 62146-626, 5d.19h.11m
    easyprivacy: 30934-1742, 5d.19h.12m
    urlhaus-1: 6589-0, 4d.16h.2m
    plowe-0: 3666-2, 5d.19h.13m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5894 ms (selfie)
  maxAssetCacheWait: 712 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    narvar.com: 2
    bugsnag.com: 3
```
</details>

**Comment by mapx-** [comment]
I get a blank page even disabling uBO.
Maybe an account is required ? Which are the steps to land on that page ?

**Comment by ghajini** [comment]
firstly only test ublock origin with its default settings & updated filters
soo

i get delivery info like this which is desired i guess

![image](https://user-images.githubusercontent.com/20338483/213905869-82a409af-98a1-4a79-a4cc-ba2baea7ba84.png)
@Vjedi729

**Comment by ghajini** [comment]
website = `wrangler.in/`  there are other international sites also
i even added 1 item to cart successfuly

![image](https://user-images.githubusercontent.com/20338483/213906280-fa614e0d-dc2c-488f-82ad-fcb208af2d9b.png)
 so more info is required from you such as website etc,steps to reproduce
