### ISSUE TITLE
meundies.com: breakage

### ISSUE THREAD

**Issue by Scott123456** [uBlockOrigin/uAssets#16441]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.meundies.com/products/mens-breathe-trunk`

### Category

breakage

### Description

Images of products do not appear on many of the product pages.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot 2023-01-20 232422](https://user-images.githubusercontent.com/10225537/213846774-ff0413e7-a2e6-4987-b0a2-db9236ed0b78.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 91488
  cosmetic: 115444
  scriptlet: 21749
  html: 994
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 85025-457, 6d.23h.17m
    ublock-annoyances: 4732-4, 2d.4h.12m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32488-55, 2d.4h.15m
    ublock-badware: 4329-0, 2d.4h.14m
    ublock-privacy: 304-0, 6d.23h.19m
    ublock-abuse: 77-0, 6d.23h.19m
    ublock-unbreak: 1936-1, 2d.4h.13m
    ublock-quick-fixes: 501-0, 1d.32m
    easylist: 62156-615, 2h.32m
    easyprivacy: 30949-1760, 2h.31m
    urlhaus-1: 6577-0, 1d.33m
    plowe-0: 3666-2, 6d.23h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 942 ms (selfie)
  maxAssetCacheWait: 530 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    meundies.com: 5
    bazaarvoice.com: 2
    zdassets.com: 1
```
</details>

**Comment by ghajini** [comment]
caused by `||zdassets.com/ekr/snippet.js` in `fanboy annoyances`
@ryanbr
