### ISSUE TITLE
Media Fails to Load on Zee5 Website

### ISSUE THREAD

**Issue by GimmeDemJigglypuffs** [uBlockOrigin/uAssets#16447]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Creating a new issue since similar issue related to the same site has been closed in 2021. Any free content (except for movie trailers) doesn't play as long as uBO is active. If I disable uBO, the media on the website plays. The issue has only started since December, there were no problems before that. I'm able to watch the same content using Brave browser with its built-in adblocking without any problem (no extensions). In the presence of uBO on Firefox, the player loads, but the media doesn't (screenshots below).

Additional information:
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary):
network: 120285
cosmetic: 205398
scriptlet: 34021
html: 851
listset (total-discarded, last-updated):
added:
https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3d.9h.47m
https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt: 8491-0, 247d.25m
adguard-generic: 67787-4203, 2d.7h.8m
adguard-mobile: 8699-179, 2d.7h.10m
adguard-annoyance: 62653-618, 2d.7h.7m
fanboy-annoyance: 86336-5207, 2d.13m
default:
user-filters: 25-0, never
ublock-filters: 32488-38, 2d.7h.5m
ublock-badware: 4329-0, 2d.7h.9m
ublock-privacy: 304-0, 7d.5h.21m
ublock-abuse: 77-0, 7d.5h.22m
ublock-unbreak: 1937-0, 2d.7h.6m
easylist: 62312-1553, 1d.10h
easyprivacy: 30950-1856, 6h.48m
plowe-0: 3666-2, 5d.9h.44m
urlhaus-1: 6900-2410, 54m
filterset (user): [array of 25 redacted]
trustedset:
added: [array of 9 redacted]
modifiedUserSettings:
webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats:
allReadyAfter: 5120 ms (selfie)
maxAssetCacheWait: 454 ms

(Screenshot 1) On Firefox with uBO - content fails to load:
![213875380-2e3d5760-98c6-436d-b9da-2ab9b5ace346](https://user-images.githubusercontent.com/123256589/213876045-7edbf8d7-d0fa-4d5e-a510-f482ca645ebe.jpg)

(Screenshot 2) Same URL on Brave Browser - media plays without problem
![Untitled](https://user-images.githubusercontent.com/123256589/213876091-4cfcbac5-2ee8-4a4a-9f10-144f2f25557c.jpg)

### URL(s) where the issue occurs.

https://www.zee5.com/movies/details/white-haired-devil-lady/0-0-1z5233998

### uBO version

1.46.0

### Browser name and version

Firefox version: 109, Brave version: [Version 1.47.171 Chromium: 109.0.5414.87]

### Settings

no changes made

**Comment by stephenhawk8054** [comment]
I cannot access your above link. Other links on the website work normally for me. Can you turn off these custom filter lists

```
https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3d.9h.47m
https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt: 8491-0, 247d.25m
adguard-generic: 67787-4203, 2d.7h.8m
adguard-mobile: 8699-179, 2d.7h.10m
adguard-annoyance: 62653-618, 2d.7h.7m
fanboy-annoyance: 86336-5207, 2d.13m
```

force update your filter lists (click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.) and test again.

**Comment by ghajini** [comment]
i can reproduce, caused by adguard base filters

```
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,important,domain=zee5.com
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,important,redirect-rule=google-ima.js,domain=zee5.com
```

with default settings, it plays fine
