### ISSUE TITLE
ark.intel.com: breakage

### ISSUE THREAD

**Issue by Koen1999** [uBlockOrigin/uAssets#16448]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [ ] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ark.intel.com/content/www/us/en/ark/products/230575/intel-core-i313100-processor-12m-cache-up-to-4-50-ghz.html`

### Category

breakage

### Description

The "send feedback" form at the bottom of the page is malfunctioning. Specifically, the submit button is not working when uBlock Origin is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/32361020/213880579-34a74151-3ff4-4ffa-997e-43664cb9beaa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83744
  cosmetic: 38891
  scriptlet: 16838
  html: 866
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32484-54, 3d.54m
    ublock-badware: 4324-0, 3d.55m
    ublock-privacy: 304-0, 4d.20h.25m
    ublock-abuse: 77-0, 5d.5h.44m
    ublock-unbreak: 1936-1, 3d.53m
    ublock-quick-fixes: 500-0, 1d.1h.58m
    easylist: 62174-627, 6d.2h.47m
    easyprivacy: 30944-1743, 3d.56m
    urlhaus-1: 6526-0, 1d.1h.57m
    plowe-0: 3667-2, 3d.58m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1745 ms (selfie)
  maxAssetCacheWait: 1227 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@ryanbr
