### ISSUE TITLE
[nsfw] moviesjoy.to: ads

### ISSUE THREAD

**Issue by Jimbo-Jim** [uBlockOrigin/uAssets#16443]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://moviesjoy.to/movie/the-old-way-92206`

### Category

ads

### Description

MoviesJoy Android app advert
![Screenshot from 2023-01-21 12-26-16](https://user-images.githubusercontent.com/55551115/213866737-86308e86-61e7-40ab-96ff-73186025c9a9.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 129277
  cosmetic: 152706
  scriptlet: 35935
  html: 996
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 67816-5892, 17h.52m
    adguard-mobile: 8715-147, 17h.52m
    adguard-spyware: 36809-14859, 17h.52m
    adguard-spyware-url: 887-4, 17h.52m
    adguard-annoyance: 62723-1675, 17h.52m
    adguard-social: 19672-31, 17h.52m
    ublock-annoyances: 4751-4, 17h.52m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32699-106, 17h.52m
    ublock-badware: 4364-5, 17h.52m
    ublock-privacy: 305-0, 17h.52m
    ublock-abuse: 77-0, 17h.52m
    ublock-unbreak: 1905-2, 17h.52m
    ublock-quick-fixes: 504-0, 17h.52m
    easylist: 62162-804, 17h.52m
    easyprivacy: 30950-1753, 17h.52m
    urlhaus-1: 6526-0, 17h.52m
    plowe-0: 3668-2, 12d.19h.19m
filterset (user): [empty]
modifiedUserSettings: 
  autoUpdate: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 320 ms (selfie)
  maxAssetCacheWait: 135 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    addthis.com: 1
    bigcache.ml: 2
    briareddollier.com: 1
    callerdumka.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
self promotion, add it as custom filter

`||i.imgur.com/*.gif$image,domain=moviesjoy.to`
