### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by WRtux** [uBlockOrigin/uAssets#16451]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bilibili.com/h5/comment/appeal`  
and all the similar pages.

### Category

breakage

### Description

> These pages are shown when reporting (flagging) and appealing to recover contents.

The script `https://s1.hdslb.com/bfs/seed/log/report/log-reporter.js` is blocked. Users will be directed to the login page when submitting and lose their filled forms.

### Screenshot(s)

No screenshots needed.

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 101824
  cosmetic: 49068
  scriptlet: 17055
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28337-104, 1d.13h.31m
    easylist: 62275-81, 3d.16h.1m
    easyprivacy: 30944-1193, 3d.20h.2m
    plowe-0: 3669-903, 8d.19h.1m
    ublock-abuse: 77-0, 9d.15h.9m
    ublock-badware: 4325-114, 2d.14h.55m
    ublock-filters: 31903-146, 1d.13h.27m
    ublock-privacy: 258-1, 9d.19h.10m
    ublock-quick-fixes: 490-20, 1d.13h.26m
    ublock-unbreak: 1924-48, 2d.14h.53m
    urlhaus-1: 6526-0, 1d.13h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 154 ms (selfie)
  maxAssetCacheWait: 384 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    hdslb.com: 2
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16450#issuecomment-1399416633
