### ISSUE TITLE
[nsfw]Blocked with cosmestic filtering, not permanent

### ISSUE THREAD

**Issue by beakwood** [uBlockOrigin/uAssets#16457]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Anytime I block the ad using cosmetic filtering of the ad at top and bottom of page. When I refresh the page, the ad is still showing afterwards.

### URL(s) where the issue occurs.

nsfw
`https://titsi'ntops.com/phpBB2/index.php` 

### Screenshot(s)

'https://user-images.githubusercontent.com/43938224/213922837-efc90ae1-22ed-4d3b-8f69-5971a71b7081.png'

### uBO version

1.46.0

### Browser name and version

Firefox Nightly 110.0a1

### Settings

-Default Settings

**Comment by 924nf9sh33nf** [comment]
This issue has started occurring again for me. 
![Screenshot_20231119_130843](https://github.com/uBlockOrigin/uAssets/assets/151471800/6a023246-db1e-4720-86e4-5854b18fe396)

The failure of the ad to load is from my pihole instance, but the ad is still being placed on the page. So this filter needs to be updated.

@mapx- @beakwood

**Comment by mapx-** [comment]
I added a filter to kill the popMagic popup.
That "ad" is self-promotion.

add
`titsintops.com##.samItem`

**Comment by 924nf9sh33nf** [comment]
Actually, it might just have missed the most recent ublock origin lite update

**Comment by 924nf9sh33nf** [comment]
@mapx- This is still showing under a div with the id "sub-frame-error"

**Comment by 924nf9sh33nf** [comment]
> > This is still showing
> 
> "This" what ? screenshot, specific link ?

The exact same behavior as before:

![image](https://github.com/uBlockOrigin/uAssets/assets/151471800/33306cc4-eb76-4909-b848-515875efcec4)
https://titsintops.com/phpBB2/index.php


This div is still showing up:

```
<div id="sub-frame-error" jstcache="0">
    <!-- Show details when hovering over the icon, in case the details are
         hidden because they're too large. -->
    <div class="icon icon-generic" jstcache="0"></div>
    <div id="sub-frame-error-details" jsselect="summary" jsvalues=".innerHTML:msg" jstcache="1"><strong jscontent="hostName" jstcache="22">cams.titsintops.com</strong> refused to connect.</div>
  </div>
```

I have UBO lite installed with filtering mode Complete

**Comment by mapx-** [comment]
You have to wait - in case of uBO Lite the new filters are active only after a new release will land in the google store.
Use uBO (not Lite)

**Comment by 924nf9sh33nf** [comment]
@mapx- 

I think ads are successfully being blocked, but that's triggering another div to error out. This causes the screenshot I showed.

the div has the id "sub-frame-error"

**Comment by mapx-** [comment]
No such behaviour on my end in uBO
