### ISSUE TITLE
langoguessr.com: breakage

### ISSUE THREAD

**Issue by betseg** [uBlockOrigin/uAssets#16454]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://langoguessr.com/`

### Category

breakage

### Description

The site doesn't load when uBlock is active. Inspect element shows an empty `body` element.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 166351
  cosmetic: 233518
  scriptlet: 38907
  html: 1001
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36810-14940, 16m
    adguard-generic: 67795-5825, 16m
    adguard-mobile: 8718-189, 16m
    adguard-spyware-url: 887-4, 16m
    block-lan: 44-0, 16m
    curben-phishing: 18648-2, 16m
    curben-pup: 187-0, 16m
    adguard-annoyance: 62727-4954, 16m
    adguard-social: 19674-1081, 16m
    fanboy-thirdparty_social: 69-0, 16m
    fanboy-annoyance: 86634-70482, 16m
    fanboy-cookiemonster: 45036-239, 16m
    fanboy-social: 23511-28, 16m
    ublock-annoyances: 4751-4, 16m
    dpollock-0: 11397-472, 16m
    TUR-0: 12008-26, 16m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32734-117, 16m
    ublock-badware: 4379-5, 16m
    ublock-privacy: 305-0, 16m
    ublock-abuse: 77-0, 16m
    ublock-unbreak: 1899-2, 16m
    ublock-quick-fixes: 504-0, 16m
    easylist: 61220-1008, 16m
    easyprivacy: 30952-1844, 16m
    urlhaus-1: 6705-0, 16m
    plowe-0: 3667-2, 16m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1579 ms (selfie)
  maxAssetCacheWait: 1773 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    buymeacoffee.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.

You didn't accomplish this rule

@Yuki2718 
AG annoyances
`@@||cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js$script,domain=langoguessr.com`

**Comment by betseg** [comment]
> You didn't accomplish this rule

What? I did not remove any default filter, Easylist and Adguard are enabled.

**Comment by mapx-** [comment]
>  I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
