### ISSUE TITLE
jetpunk.com: detection

### ISSUE THREAD

**Issue by betseg** [uBlockOrigin/uAssets#16452]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jetpunk.com/`

### Category

detection

### Description

Commenting is blocked with uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Grim-Screenshot-2023-01-22_08:36:16](https://user-images.githubusercontent.com/1706369/213902225-1dd02611-47db-4deb-8967-1c5f1b6f8c5b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 167126
  cosmetic: 233397
  scriptlet: 38729
  html: 994
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36810-14938, 19h.58m
    adguard-generic: 67785-5898, 2d.17h.1m
    adguard-mobile: 8712-189, 2d.17h
    adguard-spyware-url: 887-4, 2d.16h.58m
    block-lan: 44-0, 10d.20h.58m
    curben-phishing: 18389-2, 15h.56m
    curben-pup: 195-0, 15h.55m
    adguard-annoyance: 62670-4941, 2d.16h.57m
    adguard-social: 19656-1080, 2d.16h.56m
    fanboy-thirdparty_social: 68-0, 3d.19h.21m
    fanboy-annoyance: 86305-70168, 3d.19h.20m
    fanboy-cookiemonster: 44934-239, 3d.19h.19m
    fanboy-social: 23494-28, 4d.15h.25m
    ublock-annoyances: 4732-4, 2d.16h.55m
    dpollock-0: 11397-472, 6d.3h.18m
    TUR-0: 11999-26, 2d.17h.2m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32488-110, 2d.17h.5m
    ublock-badware: 4329-0, 2d.17h.4m
    ublock-privacy: 305-0, 2d.11h.43m
    ublock-abuse: 77-0, 2d.11h.42m
    ublock-unbreak: 1937-2, 2d.17h.3m
    ublock-quick-fixes: 504-0, 15h.58m
    easylist: 62312-1011, 2d.17h.7m
    easyprivacy: 30944-1845, 2d.17h.6m
    urlhaus-1: 6900-0, 15h.57m
    plowe-0: 3667-2, 19h.59m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1579 ms (selfie)
  maxAssetCacheWait: 1773 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 1
    hb-jetpunk.s3.us-east-2.amazonaws.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue

Screenshot
<details>

![image](https://user-images.githubusercontent.com/66517106/213902602-56be3ad2-b448-4f0b-8eeb-83cefe55dd5a.png)

</details>

**Comment by betseg** [comment]
I get that error when commenting, not when viewing comments.

**Comment by mapx-** [comment]
We need an account to test it:

![image](https://user-images.githubusercontent.com/10303732/213904556-424b7a01-20bb-483b-8b40-e26e10ca2c58.png)

Could you provide it to us?

**Comment by ghajini** [comment]
account/password = bugmenot

need exception `@@||hb-jetpunk.s3.us-east-2.amazonaws.com/asc_prebid.js$script,domain=jetpunk.com`
ad request

**Comment by mapx-** [comment]
@betseg 

Test
`jetpunk.com##+js(set, asc, 1)`

**Comment by betseg** [comment]
both of those work
