### ISSUE TITLE
free-telecharger.live: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16458]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.free-telecharger.live/1/recherche1/1.html?rech_fiche=Le+Chat+Potté`

### Category

Advertisements, fake links

### Description

The site displays advertisements and a lot of false links. A good cleaning would be welcome. Thanks to the team !

### Screenshot(s)

Advertisements

![image](https://user-images.githubusercontent.com/50231020/213931696-e0e119bc-e421-4dae-a86a-22e2eb8ddc33.png)

False links (There are several on the site)

![image](https://user-images.githubusercontent.com/50231020/213931813-11d39f39-64e7-4e1b-ba44-42bc3def16db.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 122800
  cosmetic: 109335
  scriptlet: 20004
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39114-172, 9h.22m
    fanboy-cookiemonster: 44935-213, 4d.10h.6m
  default: 
    user-filters: 0-0, never
    FRA-0: 29987-28, 10h
    easylist: 62234-94, 4d.10h.6m
    easyprivacy: 30944-1589, 4d.10h.6m
    plowe-0: 3667-929, 4d.10h.6m
    ublock-abuse: 77-2, 4d.10h.6m
    ublock-badware: 4375-137, 9h.59m
    ublock-filters: 31720-280, 9h.58m
    ublock-privacy: 258-1, 4d.10h.6m
    ublock-quick-fixes: 490-20, 5h.21m
    ublock-unbreak: 1883-48, 9h.57m
    urlhaus-1: 6687-0, 5h.20m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 376 ms (selfie)
  maxAssetCacheWait: 222 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    google-analytics.com: 1
    pubdirecte.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```
free-telecharger.live##.block:has-text(Pub)
free-telecharger.live##[onclick*="optimizesrv"]
```

report at Liste FR repository
https://github.com/easylist/listefr/issues
