### ISSUE TITLE
yenisafak.com: ads

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#16455]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.yenisafak.com/ekonomi`

### Category

ads

### Description

Filtering works in Firefox but not in Chrome.

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/110184059/213912870-00bc10d7-84a4-46e3-87f7-d27b1c898442.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 119206
  cosmetic: 153955
  scriptlet: 34051
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36810-3653, 46m
    adguard-annoyance: 62727-243, 46m
    adguard-generic: 67795-1267, 46m
    adguard-social: 19674-833, 46m
    adguard-spyware-url: 887-2, 46m
  default: 
    user-filters: 64-0, never
    TUR-0: 12008-16, 46m
    easylist: 61220-893, 46m
    easyprivacy: 30952-12395, 46m
    ublock-abuse: 77-0, 46m
    ublock-badware: 4375-309, 46m
    ublock-filters: 31937-3880, 46m
    ublock-privacy: 258-49, 46m
    ublock-quick-fixes: 490-47, 46m
    ublock-unbreak: 1886-110, 46m
filterset (user): [array of 67 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 881 ms (selfie)
  maxAssetCacheWait: 722 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cxense.com: 2
    doubleclick.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
yenisafak.com##.ads
yenisafak.com##.ys-masthead-ad-content
yenisafak.com##.layout:style(padding-top: 0px !important;)
```

For Adguard Turkish @Yuki2718
