### ISSUE TITLE
Spiegel.de Anti Adblock

### ISSUE THREAD

**Issue by yoshimo** [uBlockOrigin/uAssets#1645]
### URL(s) where the issue occurs

`http://www.spiegel.de/`

### Describe the issue

If you open the page , a window appears telling you to kindly disabling your adblock

### Versions

- Browser/version: FF 57
- uBlock Origin version: 1.15.10

### Settings
Adguard’s Annoyance List
Fanboy’s Annoyance List
Fanboy’s Social Blocking List
EasyPrivacy
uBlock filters
Peter Lowe’s Ad and tracking server list
Adguard Mobile Filters
and ||static.emsservice.de^ & ||emsmobile.de^

**Comment by mapx-** [comment]
see
https://github.com/uBlockOrigin/uAssets/issues/1641

update ublock filters
