### ISSUE TITLE
travel.capitalone.com: breakage

### ISSUE THREAD

**Issue by Jinra** [uBlockOrigin/uAssets#16469]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://travel.capitalone.com/flights/shop/`

### Category

breakage

### Description

Cannot search for flights with uBlock enabled. Leads to an error while searching. Works fine with uBlock off or disabled completely in extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/36873193/214126853-d5bac0cc-d456-41ac-870a-a5df9cd5394f.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 84128
  cosmetic: 38763
  scriptlet: 16851
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62234-46, 5d.1h.15m
    easyprivacy: 30944-1172, 5d.1h.14m
    plowe-0: 3669-901, 11d.1h.46m
    ublock-abuse: 77-0, 11d.1h.44m
    ublock-badware: 4360-119, 2d.20h.55m
    ublock-filters: 31705-129, 2d.20h.54m
    ublock-privacy: 258-1, 11d.1h.40m
    ublock-quick-fixes: 490-20, 17h.51m
    ublock-unbreak: 1912-46, 2d.20h.53m
    urlhaus-1: 6697-0, 17h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 142 ms (selfie)
  maxAssetCacheWait: 92 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    capitalone.com: 3
    datadoghq.com: 5
    maps.googleapis.com: 1
```
</details>

**Comment by Jinra** [comment]
@mapx- These are all the blocked events from loading the page

```+34	||rum-http-intake.logs.datadoghq.com^	--	travel.capitalone.com	3	ping	https://rum-http-intake.logs.datadoghq.com/v1/input/pube49bc0251dd25d9e302e480b031af06a?ddsource=browser&ddtags=sdk_version%3A3.11.0%2Cenv%3Aproduction%2Cservice%3Amclean%2Cversion%3Av1.168.0-hotfix-2&batch_time=1674502473414
+30	||rum-http-intake.logs.datadoghq.com^	--	travel.capitalone.com	3	ping	https://rum-http-intake.logs.datadoghq.com/v1/input/pube49bc0251dd25d9e302e480b031af06a?ddsource=browser&ddtags=sdk_version%3A3.11.0%2Cenv%3Aproduction%2Cservice%3Amclean%2Cversion%3Av1.168.0-hotfix-2&batch_time=1674502470076
+30	||browser-http-intake.logs.datadoghq.com^	--	travel.capitalone.com	3	ping	https://browser-http-intake.logs.datadoghq.com/v1/input/pub688fcec7e25e2470cfd4b6d2fe24253a?ddsource=browser&ddtags=sdk_version%3A2.18.0%2Cenv%3Aproduction%2Cservice%3Amclean%2Cversion%3Av1.168.0-hotfix-2
+7	/tracking/event|	--	travel.capitalone.com	1	xhr	https://travel.capitalone.com/api/v0/tracking/event
+7	/tracking/event|	--	travel.capitalone.com	1	xhr	https://travel.capitalone.com/api/v0/tracking/event
+1	||rum-http-intake.logs.datadoghq.com^	--	travel.capitalone.com	3	ping	https://rum-http-intake.logs.datadoghq.com/v1/input/pube49bc0251dd25d9e302e480b031af06a?ddsource=browser&ddtags=sdk_version%3A3.11.0%2Cenv%3Aproduction%2Cservice%3Amclean%2Cversion%3Av1.168.0-hotfix-2&batch_time=1674502441099
+1	/tracking/event|	--	travel.capitalone.com	1	xhr	https://travel.capitalone.com/api/v0/tracking/event
+1	||googleapis.com^*/gen_204?	--	travel.capitalone.com	3	xhr	https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true
+1	||rum-http-intake.logs.datadoghq.com^	--	travel.capitalone.com	3	ping	https://rum-http-intake.logs.datadoghq.com/v1/input/pube49bc0251dd25d9e302e480b031af06a?ddsource=browser&ddtags=sdk_version%3A3.11.0%2Cenv%3Aproduction%2Cservice%3Amclean%2Cversion%3Av1.168.0-hotfix-2&batch_time=1674502440450
+0	https://travel.capitalone.com/flights/shop/?adultsCount=1&departureDate=2023-02-04&destination=LAX&flightShopProgress=1&noLCC=false&origin=SFO&returnDate=2023-02-08&stopsOption=ANY_NUMBER&tripCategory=round_trip
+0	||rum-http-intake.logs.datadoghq.com^	--	travel.capitalone.com	3	ping	https://rum-http-intake.logs.datadoghq.com/v1/input/pube49bc0251dd25d9e302e480b031af06a?ddsource=browser&ddtags=sdk_version%3A3.11.0%2Cenv%3Aproduction%2Cservice%3Amclean%2Cversion%3Av1.168.0-hotfix-2&batch_time=1674502439708
```

**Comment by mapx-** [comment]
try

`@@||travel.capitalone.com/api/v0/tracking/event$xhr,1p`

if does not work add also:
`@@||maps.googleapis.com/maps/api/$domain=travel.capitalone.com`

If finally it works try all combinations to identify if only 1 or both filters are needed

**Comment by Jinra** [comment]
I just added `travel.capitalone.com` as a trusted site and it worked. I tried creating a static filter for each event, but none of that fixed it.

**Comment by stephenhawk8054** [comment]
Putting the site in `trusted site` means you are disabling uBO on that page, so it won't help others if they get the same issue. Can you copy paste the log like previously after adding the 2 filters above?

**Comment by Jinra** [comment]
I found it, adding this filter seems to fix the issue

@@||travel.capitalone.com/api/v0/tracking/event$xhr,domain=travel.capitalone.com
