### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by negf** [uBlockOrigin/uAssets#16466]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.investing.com/equities/pre-market`

### Category

detection

### Description

ublock origin detected when uBlock filters enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 128853
  cosmetic: 9
  scriptlet: 33277
  html: 0
listset (total-discarded, last-updated): 
  added: 
    DEU-0: 6156-3937, 20m
    JPN-1: 8880-7418, 20m
    THA-0: 1467-698, 20m
    adguard-generic: 67877-35008, 20m
    adguard-mobile: 8724-6961, 20m
    block-lan: 44-0, 20m
    curben-phishing: 19326-0, 20m
    curben-pup: 190-0, 20m
    fanboy-social: 23505-19881, 20m
    ublock-annoyances: 4770-1373, 20m
    ublock-quick-fixes: 498-175, 20m
  default: 
    user-filters: 17-0, never
    easylist: 61235-29659, 20m
    easyprivacy: 30870-1325, 20m
    plowe-0: 3667-1001, 20m
    ublock-abuse: 77-1, 20m
    ublock-badware: 4160-960, 20m
    ublock-filters: 31892-10795, 20m
    ublock-privacy: 258-11, 20m
    ublock-unbreak: 1880-303, 20m
    urlhaus-1: 6490-1, 20m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 91 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 980 ms (selfie)
  maxAssetCacheWait: 527 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    investing.com: 2
    amazon-adsystem.com: 1
    dggaenaawxe8z.cloudfront.net: 1
    doubleclick.net: 2
    google.co.jp: 1
    google.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    gstatic.com: 1
    hotjar.com: 1
    pbstck.com: 1
    primis.tech: 2
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard one)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
