### ISSUE TITLE
gamestorrents.fm: ads

### ISSUE THREAD

**Issue by Rebecca-du-58** [uBlockOrigin/uAssets#16463]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gamestorrents.fm/`

### Category

ads

### Description

Netflix advert.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 104047
  cosmetic: 47331
  scriptlet: 16940
  html: 872
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-1, never
    ublock-filters: 32471-163, 28m
    ublock-badware: 4164-5, 31m
    ublock-privacy: 304-0, 5d.14h.23m
    ublock-abuse: 77-0, 5d.14h.22m
    ublock-unbreak: 1892-1, 30m
    ublock-quick-fixes: 510-0, 27m
    easylist: 62162-671, 2d.18h.29m
    easyprivacy: 30946-1741, 2d.18h.28m
    urlhaus-1: 6697-0, 26m
    plowe-0: 3667-2, 2d.18h.30m
    FRA-0: 29988-396, 29m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8741 ms (selfie)
  maxAssetCacheWait: 2397 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    gamestorrents.fm: 1
    googletagmanager.com: 1
```
</details>

**Comment by ghajini** [comment]
spanish page so enable `spa, por: AdGuard Spanish/Portuguese`
from filter lists
