### ISSUE TITLE
abola.pt: [detection]

### ISSUE THREAD

**Issue by ihavenokia** [uBlockOrigin/uAssets#16467]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://abola.pt/nnh/2023-01-23/tenis-open-da-australia-djokovic-limpinho-nos-quartos/973596`

### Category

[detection]

### Description

"You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."  at the bottom of page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-01-23 at 14-25-42 Open da Austrália Djokovic limpinho nos ‘quartos’ (Ténis)](https://user-images.githubusercontent.com/7032279/214063837-fa419645-4442-48eb-8f1e-db778d2f1e08.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 84189
  cosmetic: 41889
  scriptlet: 17216
  html: 873
listset (total-discarded, last-updated): 
  default: 
    user-filters: 6-0, never
    ublock-filters: 32689-86, 1m
    ublock-badware: 4165-5, 1m
    ublock-privacy: 305-0, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1891-1, 1m
    easylist: 61252-675, 1m
    easyprivacy: 30871-1758, 1m
    urlhaus-1: 6490-0, 1m
    plowe-0: 3667-2, 1m
    spa-1: 4952-10, 1m
    ublock-quick-fixes: 512-0, 1m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1085 ms (selfie)
  maxAssetCacheWait: 492 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    abola.pt: 2
    amazon-adsystem.com: 1
    doubleclick.net: 1
    facebook.net: 1
    gemius.pl: 1
    google.com: 5
    imasdk.googleapis.com: 2
    teads.tv: 2
    vidoomy.com: 2
    viglink.com: 1
```
</details>

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/214067803-428bed79-9629-45d9-abcf-89d3ea1ba99f.png)

Try again, really following these indications:

- clear cookies / cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard one) => testing using another one (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
