### ISSUE TITLE
[nsfw] eroprofile.com: nuisance

### ISSUE THREAD

**Issue by sesinger** [uBlockOrigin/uAssets#16460]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.eroprofile.com/m/videos/search?niche=13.14.12.19.27.25.5.11.18.20.23.33.1.24.10.26.17.7.15.6.30.16.28.22.32.34.8&pnum=1`

### Category

nuisance

### Description

Black box slides up onto the lower right quadrant. It generally is not there when the site is first opened but shows up on a page reload or subsequent pages.

uBlock 1.46.0
Firefox  109.0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 84070
  cosmetic: 38624
  scriptlet: 16649
  html: 852
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32497-130, 1d.15h.57m
    ublock-badware: 4358-5, 1d.15h.56m
    ublock-privacy: 304-0, 7d.3h.32m
    ublock-abuse: 77-0, 7d.3h.31m
    ublock-unbreak: 1925-0, 1d.11h.53m
    easylist: 62304-517, 3d.19h.9m
    easyprivacy: 30941-1759, 4d.14h.20m
    urlhaus-1: 6705-0, 15h.27m
    plowe-0: 3667-2, 4d.18h.21m
filterset (user): [empty]
trustedset: 
  added: [array of 57 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 501 ms (selfie)
  maxAssetCacheWait: 267 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    eroprofile.com: 2
    adsessionserv.com: 4
    aj2526.bid: 4
    bullionyield.com: 1
    chaturbate.com: 1
    google-analytics.com: 1
    typekit.net: 1
    wpncdn.com: 2
```
</details>

**Comment by sesinger** [comment]
See attached.

![Screenshot (2)](https://user-images.githubusercontent.com/70541816/214067508-c82e9bde-63dd-43b7-b400-393c14c7b011.png)

**Comment by mapx-** [comment]
I tested again, still no such ad, black frame.

Follow these indications

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard one)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by sesinger** [comment]
Did you do a reload on the tab or go to the 2nd page (using the page numbers at the bottom)? It doesn’t typically show up the first time you open a page in that site.

**Comment by mapx-** [comment]
yes. Now, just follow ALL the indications above.
