### ISSUE TITLE
kwejk.pl: detection

### ISSUE THREAD

**Issue by Kiliusz** [uBlockOrigin/uAssets#16465]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kwejk.pl/`

### Category

detection

### Description

Site detectes ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83893
  cosmetic: 38587
  scriptlet: 16858
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62162-46, 5h.38m
    easyprivacy: 30870-1172, 5h.37m
    plowe-0: 3666-898, 8d.23h.30m
    ublock-abuse: 77-0, 12d.2h.43m
    ublock-badware: 4160-119, 5h.36m
    ublock-filters: 31674-127, 5h.34m
    ublock-privacy: 258-1, 11d.3h.45m
    ublock-quick-fixes: 490-20, 5h.32m
    ublock-unbreak: 1881-46, 5h.35m
    urlhaus-1: 6697-0, 5h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 136 ms (selfie)
  maxAssetCacheWait: 47 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    aaxads.com: 1
    facebook.com: 1
    facebook.net: 1
    gemius.pl: 1
    googletagmanager.com: 2
    hotjar.com: 1
    maps.googleapis.com: 1
    optad360.io: 2
    pushpushgo.com: 2
    spolecznosci.net: 1
    taboola.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable the filterlist `POL: Oficjalne polskie filtry przeciwko alertom o Adblocku`
