### ISSUE TITLE
dragontea.ink: detection

### ISSUE THREAD

**Issue by Taras255** [uBlockOrigin/uAssets#16461]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dragontea.ink/`

### Category

detection

### Description

When the ad block is enabled it gives an infinite loading page but when it is disabled it loads in fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/117605241/213947918-221be880-d4f0-4231-8bd5-f4a85c137f7b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 84723
  cosmetic: 0
  scriptlet: 17158
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7883-6674, 3m
    POL-2: 1276-811, 3m
    easylist: 61230-29217, now
    easyprivacy: 30952-1174, never
    plowe-0: 3667-907, never
    ublock-abuse: 77-1, never
    ublock-badware: 4375-769, never
    ublock-filters: 31934-8638, never
    ublock-privacy: 258-11, never
    ublock-quick-fixes: 496-172, never
    ublock-unbreak: 1881-288, never
    urlhaus-1: 6687-0, never
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3279 ms
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    doubleclick.net: 2
    googlesyndication.com: 2
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16083
