### ISSUE TITLE
hmhco.com: detection

### ISSUE THREAD

**Issue by TylerBloxOfficialOtherAccount** [uBlockOrigin/uAssets#16468]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hmhco.com/content/reading/into_reading_v2/g5/student/epub/hmh_ir5_ese05_v2_student/`

### Category

made errors
:(

### Description

it is just black
i dont know what to do

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 HMH.CO.HMEODCEFNCOEFOIhweohfewhifewhfiehufew.jpg (200 x 300)
die
die
die
die
die
help
hel

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83703
  cosmetic: 38619
  scriptlet: 16749
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 106-14, never
    easylist: 62208-46, 5d.1h.49m
    easyprivacy: 30944-1172, 5d.1h.50m
    plowe-0: 3667-899, 2h.56m
    ublock-abuse: 77-0, 2h.55m
    ublock-badware: 4160-119, 2h.53m
    ublock-filters: 31523-140, 2h.51m
    ublock-privacy: 260-1, 2h.54m
    ublock-quick-fixes: 387-25, 2h.49m
    ublock-unbreak: 1880-47, 2h.50m
    urlhaus-1: 6490-0, 2h.47m
filterset (user): [array of 106 redacted]
trustedset: 
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5947 ms (selfie)
  maxAssetCacheWait: 3115 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    browser-intake-datadoghq.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
try

`@@||browser-intake-datadoghq.com^$domain=hmhco.com`

If does not work and you want to share (if possible) your account credentials (in private ofc) we could investigate further
