### ISSUE TITLE
PyFunceble report of uAssets (23/01/2023)

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uAssets#16462]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Remove and Prune any "INACTIVE" filters. Attached is various text files generated from [PyFunceble](https://github.com/funilrys/PyFunceble)

### URL(s) where the issue occurs.

See attachments.

### uBO version

uBlock Origin 1.46.0

### Browser name and version

All Bravey baby

### Settings

Various reports

- [ ] filters.txt: [ubo-filters.txt](https://github.com/uBlockOrigin/uAssets/files/10476472/ubo-filters.txt)
- [ ] filters-2020.txt: [ubo-filters-2020.txt](https://github.com/uBlockOrigin/uAssets/files/10476473/ubo-filters-2020.txt)
- [ ] filters-2021.txt: [ubo-filters-2021.txt](https://github.com/uBlockOrigin/uAssets/files/10476474/ubo-filters-2021.txt)
- [ ] filters-2022.txt: [ubo-filters-2022.txt](https://github.com/uBlockOrigin/uAssets/files/10476466/ubo-filters-2022.txt)
- [ ] filters-2023.txt: [ubo-filters-2023.txt](https://github.com/uBlockOrigin/uAssets/files/10476467/ubo-filters-2023.txt)
- [ ] privacy.txt: [ubo-privacy.txt](https://github.com/uBlockOrigin/uAssets/files/10476468/ubo-privacy.txt)
- [ ] unbreak.txt: [ubo-unbreak.txt](https://github.com/uBlockOrigin/uAssets/files/10476469/ubo-unbreak.txt)
- [ ] annoyances.txt: [ubo-annoy.txt](https://github.com/uBlockOrigin/uAssets/files/10476470/ubo-annoy.txt)
- [ ] badware.txt: [ubo-badware.txt](https://github.com/uBlockOrigin/uAssets/files/10476471/ubo-badware.txt)

**Comment by garry-ut99** [comment]
And what about this: https://github.com/uBlockOrigin/uAssets/tree/master/tools/validate.
