### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by ispokore** [uBlockOrigin/uAssets#16470]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aternos.org/`

### Category

detection

### Description

detected by the site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 107
filterset (summary): 
  network: 104052
  cosmetic: 47325
  scriptlet: 16941
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 29988-28, 2h.20m
    easylist: 62156-89, 2d.21h.36m
    easyprivacy: 30951-1495, 2d.21h.35m
    plowe-0: 3666-924, 8d.23h.21m
    ublock-abuse: 77-1, 10d.1h.49m
    ublock-badware: 4375-137, 2h.23m
    ublock-filters: 31674-234, 2h.22m
    ublock-privacy: 258-1, 10d.1h.48m
    ublock-quick-fixes: 490-20, 2h.19m
    ublock-unbreak: 1880-48, 2h.21m
    urlhaus-1: 6490-0, 2h.18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 426 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    ad-delivery.net: 1
    amazon-adsystem.com: 1
    cloudflareinsights.com: 1
    d1oykxszdrgjgl.cloudfront.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    quantserve.com: 1
    upapi.net: 1
    venatusmedia.com: 1
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/13144
