### ISSUE TITLE
519.best: breakage

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#16477]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Download links dissapear if you turn on ublock

how to reproduce:
1. go to `https://www.519.best/e-book/lishizhuanji/qingmoming-jfynp.html`
2. scroll down
![image](https://user-images.githubusercontent.com/57501353/214312977-b127ffae-371f-4cc8-870e-25a6f59e251a.png)
After turning off ublock
![image](https://user-images.githubusercontent.com/57501353/214313154-5e38beeb-5c27-416f-b10c-6326a31ab512.png)

### URL(s) where the issue occurs.

`https://www.519.best/e-book/lishizhuanji/qingmoming-jfynp.html`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/57501353/214312977-b127ffae-371f-4cc8-870e-25a6f59e251a.png)
![image](https://user-images.githubusercontent.com/57501353/214313154-5e38beeb-5c27-416f-b10c-6326a31ab512.png)

### uBO version

1.46

### Browser name and version

chrome 108

### Settings

none

**Comment by mapx-** [comment]
@cjx82630 maybe it could be added in CHN list as fixing a breakage

**Comment by erik9012** [comment]
> `@@||519.best^$ghide`
> 
> Add In My Filters

thanks
