### ISSUE TITLE
italiashare.net right click

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#1647]
### URL(s) where the issue occurs

`www.italiashare.net`

### Describe the issue

Right click on `www.italiashare.net` don't work.
In uBlock Annoyances there are these filters (that don't work for me):
`italiashare.*##script:inject(abort-current-inline-script.js, isCtrl, mousehandler) italiashare.*##script:inject(abort-on-property-write.js, clickIE4)`

### Versions

- Browser/version: Firefox
- uBlock Origin version: 1.15.10

### Settings

default settings

**Comment by nimasaj** [comment]
Does it work for you?
`||italiashare.net^$inline-script`

**Comment by mapx-** [comment]
does not work, is breaking functionalities

**Comment by krystian3w** [comment]
<ul>
<li>

```javascript
javascript:(function(w){var d=w.document,us='user-select',uv='initial',f='getElementsByTagName',b=d.body||d[f]('body')[0],h=d.documentElement||d[f]('html')[0],w=[b,h,d],p=['webkit','khtml','moz','ms',''],e=['contextmenu','selectstart','select','mousedown','mouseup'],i,s;for(i=w.length;i--;)if(h=w[i]){for(s=e.length;s--;)h['on'+e[s]]=null;if(d=h.style){d.cursor='';d.webkitTouchCallout=uv;for(s=p.length;s--;)d[((b=p[s])?'-'+b+'-':b)+us]=uv}}(b=w.jQuery||w.Zepto)&&b(w).off(e)}(this));
```
<sup>[gist.githubusercontent.com/duzun/d66c775a39a5be9fb519/raw/f84e92f672a22ff4625b3deec8bf4ff771ec5ec3/enableSelect.min.js](https://gist.githubusercontent.com/duzun/d66c775a39a5be9fb519/raw/f84e92f672a22ff4625b3deec8bf4ff771ec5ec3/enableSelect.min.js)</sup>

</li>
</ul>

---

<ul>
<li>

```javascript
javascript:(function(){var d=document,b=d.body;b.onmousedown=null;d.onmousedown=null;b.onmouseup=null;d.onmouseup=null;b.oncontextmenu=null;d.oncontextmenu=null;})();
```
```javascript
javascript:(function(w){for(var i=0;i<w.length;i++){arguments.callee(w.frames[i]);}try{function n(r) {r.onclick=r.oncontextmenu=r.onmousedown=r.onmouseup=null;}n(w.document);n(w.document.body);}catch(e){alert('Bookmarklet failed:\n\n'+e.message);}})(top);
```
<sup> http://4umi.com/web/bookmarklet/rightclick.php <sup>

</li>
</ul>

**Comment by nimasaj** [comment]
the following one also could be added to enable CTRL key (CTRL+U).
`italiashare.net##script:inject(abort-current-inline-script.js, document.onkeydown)`

**Comment by bup4gr** [comment]
This two fixes don't work for me.
Is it only my problem?

**Comment by okiehsch** [comment]
Your using Firefox, the fix included a new scriptlet `remove-attr.js`,because of https://github.com/gorhill/uBlock/commit/126110c9a0a0630cd556f5cb215422296a961029 the new scriptlet will not work with the current uBlock stable version of Firefox.

**Comment by mapx-** [comment]
You could use the last dev version installable clicking
 uBlock0.webext.signed.xpi

here:
https://github.com/gorhill/uBlock/releases

**Comment by okiehsch** [comment]
Hm, the fix does not work with the latest Firefox dev build on my end, does it work for you?

**Comment by mapx-** [comment]
No .. I don't see the `remove-attr.js` filter in the logger

**Comment by okiehsch** [comment]
Trying to update the resource.txt by updating uBlock-filters does not work with Firefox on my end,
at least it does not show upin the logger.

With Chrome:
![unbenannt](https://user-images.githubusercontent.com/16838044/37145979-bf3acac6-22c2-11e8-8071-847af5efac5f.PNG)


With Firefox:
![unbenannt1](https://user-images.githubusercontent.com/16838044/37146110-22770550-22c3-11e8-8c44-2aa74785d33b.PNG)

**Comment by mapx-** [comment]
right, `resources.txt` is not updated

**Comment by mapx-** [comment]
in console (probably nothing related ..):

![image](https://user-images.githubusercontent.com/10303732/37146511-3ee2f2c0-22c4-11e8-83d5-b46e0f4cb397.png)

**Comment by gorhill** [comment]
uBO is not allowed to update resources.txt, it's a AMO requirement: <https://github.com/gorhill/uBlock/commit/126110c9a0a0630cd556f5cb215422296a961029>.

**Comment by mapx-** [comment]
not even when self hosted ?

**Comment by gorhill** [comment]
I would need to modify the code for this, I will look into this.

**Comment by gorhill** [comment]
`resources.txt` will now update with the self-hosted version:
https://github.com/gorhill/uBlock/commit/dd979ff5ffff013cf32c96fdfa26f4c6d0721ea1

**Comment by JustOff** [comment]
I'm sorry about posing a kind of offtopic here, but I neither can open new issue, nor comment at the https://github.com/gorhill/uBlock/commit/dd979ff5ffff013cf32c96fdfa26f4c6d0721ea1, but this change make it impossible to update in Pale Moon: `ReferenceError: chrome is not defined assets.js:916:12`. Could you please add an extra check before calling `chrome.runtime.getManifest()`?

**Comment by gorhill** [comment]
I fixed the issue, I will release a new dev build at some point before tomorrow hopefully.

**Comment by bup4gr** [comment]
The filters don't work because `italiashare.net` is now `italiashare.co`.

Can you update the filter from
```
italiashare.*##script:inject(abort-current-inline-script.js, document.onkeydown)
italiashare.*##script:inject(abort-current-inline-script.js, isCtrl, mousehandler)
italiashare.*##script:inject(abort-on-property-write.js,  clickIE4)
italiashare.net##script:inject(remove-attr.js, oncontextmenu)
```
to
```
italiashare.*##script:inject(abort-current-inline-script.js, document.onkeydown)
italiashare.*##script:inject(abort-current-inline-script.js, isCtrl, mousehandler)
italiashare.*##script:inject(abort-on-property-write.js,  clickIE4)
italiashare.*##script:inject(remove-attr.js, oncontextmenu)
```
