### ISSUE TITLE
weathernews.jp freezes when accessing

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [uBlockOrigin/uAssets#16474]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

With uBlock turned on, when I go to weathernews.jp and click the button for the region I want to check the weather forecast for, the Edge process gets involved and freezes.

### URL(s) where the issue occurs.

`https://weathernews.jp/`
`https://weathernews.jp/onebox/tenki/tohoku/`

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 84234
  cosmetic: 46150
  scriptlet: 17078
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 8-0, never
    JPN-1: 8940-6, 2m
    easylist: 61352-55, 2m
    easyprivacy: 30872-1199, 2m
    plowe-0: 3667-904, 2m
    ublock-abuse: 77-0, 2m
    ublock-badware: 4164-119, 2m
    ublock-filters: 31891-146, 2m
    ublock-privacy: 258-1, 2m
    ublock-quick-fixes: 498-21, 2m
    ublock-unbreak: 1880-49, 2m
    urlhaus-1: 6525-0, 2m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 17 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 500 ms
  maxAssetCacheWait: 227 ms
```
</details>

**Comment by mapx-** [comment]
I guess @Yuki2718 could help here

**Comment by Yuki2718** [comment]
I can't reporoduce. Is this always happens?

**Comment by Yuki2718** [comment]
I could reproduce once on Edge, but no more.

**Comment by ShintakuNobuhiro** [comment]
@Yuki2718 Yes, if uBlock Origin is disabled, the freezing issue will not occur.

**Comment by Yuki2718** [comment]
I also can not reproduce any more. Test on a new Edge profile with fresh uBO. If it still always happens, open the logger and allow requests one by one to narrow down the culprit.

**Comment by Yuki2718** [comment]
@ShintakuNobuhiro Just my hunch from past experience, but does adding `*$script,redirect-rule=weathernews.jp` to My filters fixes the issue?

**Comment by ShintakuNobuhiro** [comment]
@Yuki2718 No, it didn't help.

**Comment by Yuki2718** [comment]
Then https://github.com/uBlockOrigin/uAssets/issues/16474#issuecomment-1403698608
