### ISSUE TITLE
linkedin.com: privacy

### ISSUE THREAD

**Issue by matter-it-does** [uBlockOrigin/uAssets#16478]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`linkedin.com/li/track$xhr`

is an event logging request. On webpage provided with an account.

### URL(s) where the issue occurs.

`linkedin.com/learning`

### uBO version

 1.46.0

### Browser name and version

FF 

### Settings

NA

**Comment by orbanbalage** [comment]
I've just posted about this on Reddit where others were having the same issue. Thanks for the fix.

cf. https://www.reddit.com/r/linkedin/comments/vdl84l/i_cant_add_course_certificate/

**Comment by mapx-** [comment]
I commented that filter, update privacy list & test again

**Comment by matter-it-does** [comment]
they use the same endpoint for course progress as well as navigation events.
