### ISSUE TITLE
Can't watch a video hosted in a filtered domain after whitelisting it

### ISSUE THREAD

**Issue by wodim** [uBlockOrigin/uAssets#16475]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://a.pomf.cat/gfviuf.webm is hosted in a.pomf.cat which is in the "Online Malicious URL Blocklist" list which comes enabled by default. 

When you navigate to that URL, you are asked if you want to proceed, but if you say you do the video doesn't play anyway. Looking at the developer tools it seems ublock is still blocking the video.

### A specific URL where the issue occurs.

https://a.pomf.cat/gfviuf.webm

### Steps to Reproduce

...

### Expected behavior

...

### Actual behavior

...

### uBO version

uBlock Origin 1.46.0

### Browser name and version

Chrome Version 109.0.5414.75 (Official Build) (64-bit)

### Operating System and version

Windows 11

**Comment by mapx-** [comment]
`a.pomf.cat` will stay blocked as a source of recent malware

**Comment by garry-ut99** [comment]
> wodim : When you navigate to that URL, you are asked if you want to proceed, but if you say you do the video doesn't play anyway. Looking at the developer tools it seems ublock is still blocking the video.

https://github.com/uBlockOrigin/uBlock-issues/issues/544

**Comment by wodim** [comment]
@mapx- I don't know who told you I was complaining about the domain being blocked or anything. You moved this issue when you hadn't even read it. Very disappointed.

**Comment by mapx-** [comment]
@wodim read here:

https://github.com/uBlockOrigin/uBlock-issues/issues/544#issuecomment-486243849

**Comment by mapx-** [comment]
@gorhill

**Comment by gorhill** [comment]
uBO acts according to what the information the browser gives it, and in this case the browser tells uBO that there is a secondary `media` resource, and thus it's being blocked as per filter, while the request for the document itself is not blocked:

![Screenshot from 2023-01-24 09-37-12](https://user-images.githubusercontent.com/585534/214323713-08c7f90e-e57e-48a1-b57e-52c6bd480c2c.png)

**Comment by iam-py-test** [comment]
@wodim where did you find this URL?
If you think this domain is a hosting site and should not be blocked, then reported it at https://gitlab.com/malware-filter/urlhaus-filter/-/issues

**Comment by wodim** [comment]
Doesn't matter; as I said I am not reporting a bug in a list but in ublock origin itself. The author does not want to fix it, so I am not going to pursue the matter any further.

**Comment by garry-ut99** [comment]
It's by design due to security reasons, to prevent an user from being attacked by a malicious website, if a site still isn't fully unblocked after clicking Continue button, there are two ways to access the site at own risk and wish:
- harder/longer but more secure way for advanced users:  
find out which filters are blocking, and create only necessary whitelist filters 
(for example unlock an video only, while still keeping malicious scripts blocked)
- easier/quicker but more dangerous way for novice users users: 
after clicking Continue: [click the large power button to turn off uBO for the current site](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button)
(this is dangerous, as not only the video will be unblocked, but all the malicious scripts as well)
