### ISSUE TITLE
zerotopay.com detection

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#16476]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Adblock detected.Used ublock only. I got here after using some ebooks download site 

### URL(s) where the issue occurs.

https://zerotopay.com/2aa2871790021160

### Screenshot(s)

![image](https://user-images.githubusercontent.com/57501353/214309681-0e1f468f-914f-44fb-89b4-45218479a549.png)

### uBO version

1.46

### Browser name and version

chrome 108

### Settings

none

**Comment by erik9012** [comment]
> Add In My Filters -
> 
> `@@||zerotopay.com^$ghide`
> 
> If You Want Clean WebPage -
> 
> `zerotopay.com##tbody:others()`

Thanks, works great.

**Comment by ghajini** [comment]
> `zerotopay.com##tbody:others()`
 
don't suggest breaking filters
