### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by galoriian** [uBlockOrigin/uAssets#16473]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Description

loading starts but hangs, and after 20sec/60sec loading stops (no new page loaded)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 104086
  cosmetic: 47325
  scriptlet: 16930
  html: 867
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 32497-38, 3d.9h.59m
    ublock-badware: 4346-0, 3d.9h.58m
    ublock-privacy: 305-0, 3d.9h.57m
    ublock-abuse: 77-0, 3d.9h.56m
    ublock-unbreak: 1905-1, 3d.9h.55m
    easylist: 62162-673, 1d.10h.32m
    easyprivacy: 30952-1742, 1d.10h.31m
    plowe-0: 3666-2, 7d.13h.13m
    FRA-0: 29987-503, 3d.9h.54m
    urlhaus-1: 6490-0, 16h.25m
    ublock-quick-fixes: 504-16, 16h.24m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 55 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 623 ms (selfie)
  maxAssetCacheWait: 189 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    youtube.com: 2
    doubleclick.net: 1
    facebook.com: 1
```
</details>

**Comment by mapx-** [comment]
YT issues => https://github.com/uBlockOrigin/uAssets/issues/7636

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard one)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
