### ISSUE TITLE
bing.com: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#16472]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bing.com/search?q=bushido+7&qs=n&form=QBRESH&sp=-1&pq=bushido+7&sc=9-9&sk=&cvid=D85D993ABE814F2D80A4883DD35A8C5A&ghsh=0&ghacc=0&ghpl=`

### Category

ads

### Description

ads showing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/81616288/214176334-bccc4a76-41cc-4bc0-9838-60862bb9c103.jpeg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 85011
  cosmetic: 42602
  scriptlet: 16953
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6155-0, 1h.5m
    easylist: 61252-50, 1h.5m
    easyprivacy: 30871-1181, 1h.5m
    plowe-0: 3667-899, 1h.5m
    ublock-abuse: 77-0, 1h.5m
    ublock-badware: 4164-119, 1h.5m
    ublock-filters: 31892-147, 1h.5m
    ublock-privacy: 258-1, 1h.5m
    ublock-quick-fixes: 498-20, 1h.5m
    ublock-unbreak: 1880-49, 1h.5m
    urlhaus-1: 6490-0, 1h.5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7265 ms (selfie)
  maxAssetCacheWait: 722 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    bing.com: 34
```
</details>

**Comment by stephenhawk8054** [comment]
Which browser are you using?

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue

Screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/214193984-bb104419-39c4-4b9a-b062-a029d93fba16.png)

</details>

**Comment by stephenhawk8054** [comment]
I still can't reproduce even after refreshing multiple times: https://pixeldrain.com/u/VSg6EeDZ

**Comment by mapx-** [comment]
@i8cczshd 
Test
```
bing.com##[data-partnertag]
bing.com##.b_adPATitleBlock
```

@stephenhawk8054 try using a german ip
@ryanbr
