### ISSUE TITLE
chess-teacher.com: breakage

### ISSUE THREAD

**Issue by BlackCatHacker2** [uBlockOrigin/uAssets#16484]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chess-teacher.com/`

### Category

breakage

### Description

Scrolling breaks on this page, i.e the page is frozen in a state and treated as if there is no more page above or below after a short delay
Applies to all pages in domain
Works if uBlock is disabled temporarily

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83170
  cosmetic: 38600
  scriptlet: 16859
  html: 872
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32514-38, 2d.21m
    ublock-badware: 4364-5, 2d.20m
    ublock-privacy: 305-0, 2d.19m
    ublock-abuse: 77-0, 2d.18m
    ublock-unbreak: 1892-1, 2d.17m
    ublock-quick-fixes: 512-16, 18h.29m
    easylist: 61301-632, 2d.16m
    easyprivacy: 30950-1743, 2d.15m
    urlhaus-1: 6525-0, 18h.28m
    plowe-0: 3667-2, 1d.18h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 486 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by BlackCatHacker2** [comment]
Tested across multiple devices, non-environmental

**Comment by stephenhawk8054** [comment]
I have waited a site for a while but it still works normally for me. Except if I move the mouse to the top bar there's an overlay appears

Screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/214463137-5c91aa51-adea-429e-8a5f-c37f127a33e5.png)

</details>

**Comment by BlackCatHacker2** [comment]
Ah yup,
Tested on a fresh browser install with only uBlock installed, same results as above with visible overlay

It looks like I did a very large dumb and failed to fully disable one other extensions, this is not a uBlock problem (unless you count unblocked pop-up overlays)

Apologies!
Closing
