### ISSUE TITLE
examtadka.com: detection

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#16483]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://examtadka.com/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 99835
  cosmetic: 59453
  scriptlet: 18109
  html: 877
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32688-156, 1d.13h.17m
    ublock-badware: 4164-5, 1d.13h.17m
    ublock-privacy: 305-0, 1d.13h.17m
    ublock-abuse: 77-0, 1d.13h.17m
    ublock-unbreak: 1891-1, 1d.13h.17m
    ublock-quick-fixes: 504-0, 13h.17m
    easylist: 61235-519, 1d.13h.17m
    easyprivacy: 30870-1757, 1d.13h.17m
    urlhaus-1: 6525-0, 13h.16m
    plowe-0: 3667-2, 1d.13h.17m
    RUS-0: 39139-173, 1d.13h.17m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1354 ms (selfie)
  maxAssetCacheWait: 950 ms
popupPanel: 
  blocked: 1268
  blockedDetails: 
    examtadka.com: 40
    adclixx.net: 1
    adtrue.com: 235
    freychang.fun: 244
    googlesyndication.com: 1
    orquideassp.com: 504
    rtunitytostar.com: 243
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by ghajini** [comment]
fixed yesterday https://github.com/uBlockOrigin/uAssets/commit/251b5569c0ba12c83707d7702fc17ca1f1017203

update filters
