### ISSUE TITLE
surreyhillsgrocer.sg: nuisance

### ISSUE THREAD

**Issue by lightwing3** [uBlockOrigin/uAssets#16486]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.surreyhillsgrocer.sg/`

### Category

nuisance

### Description

Pop up for newsletter keeps reappearing on every page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 82959
  cosmetic: 38707
  scriptlet: 16961
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61417-46, 1m
    easyprivacy: 30879-1172, 1m
    plowe-0: 3667-898, 1m
    ublock-abuse: 77-0, 1m
    ublock-badware: 4169-119, 1m
    ublock-filters: 31902-136, 1m
    ublock-privacy: 258-1, 1m
    ublock-quick-fixes: 499-20, 1m
    ublock-unbreak: 1876-49, 1m
    urlhaus-1: 6495-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1490 ms (selfie)
  maxAssetCacheWait: 920 ms
popupPanel: 
  blocked: 0
  no-popups: true
```
</details>

**Comment by lightwing3** [comment]
<img width="1439" alt="Screenshot 2023-01-25 at 12 44 07" src="https://user-images.githubusercontent.com/30489545/214481816-1177ce6b-60cf-4c7d-a1cd-e1ec5276cd0a.png">

**Comment by stephenhawk8054** [comment]
You can enable `uBlock filters – Annoyances` list and force update the filter lists in about 10 minutes.
