### ISSUE TITLE
bluesky-soft.com: breakage

### ISSUE THREAD

**Issue by antoniogott** [uBlockOrigin/uAssets#16489]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bluesky-soft.com/en/emcc/download/?vs=2.4.0&tp=p&hs=839A5075D3C37CDF2676556B2C9AEBAD831EE86D326F1E8CD4C38859BD47AEDB`

### Category

breakage

### Description

Automatic download does not work with eBO enabled, will probably have to generate a new download link in `https://bluesky-soft.com/en/EasyMCC.html` to test.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83070
  cosmetic: 38706
  scriptlet: 16964
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61419-46, 4m
    easyprivacy: 30879-1172, 4m
    plowe-0: 3667-898, 4m
    ublock-abuse: 77-0, 4m
    ublock-badware: 4169-119, 4m
    ublock-filters: 31900-136, 4m
    ublock-privacy: 259-1, 4m
    ublock-quick-fixes: 505-20, 4m
    ublock-unbreak: 1874-49, 4m
    urlhaus-1: 6603-0, 3m
filterset (user): [empty]
trustedset: 
  added: [array of 17 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 622 ms (selfie)
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    bluesky-soft.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||bluesky-soft.com/common/script/ga.js$script,1p`

@ryanbr
