### ISSUE TITLE
faceswaponline.com: breakage

### ISSUE THREAD

**Issue by matazaOG** [uBlockOrigin/uAssets#16481]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://faceswaponline.com/composite`

### Category

breakage

### Description

Site is for editing pictures and when ublock is on i cant upload a picture(by dragging it or by selecting insert-> pic by commands) or edit it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 82948
  cosmetic: 38380
  scriptlet: 16742
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32311-69, 3d.3h.41m
    ublock-badware: 4364-5, 3d.3h.40m
    ublock-privacy: 307-0, 7d.6h.6m
    ublock-abuse: 77-0, 7d.6h.5m
    ublock-unbreak: 1925-1, 3d.3h.39m
    ublock-quick-fixes: 398-0, 1d.8m
    easylist: 61143-615, 1d.10m
    easyprivacy: 30870-1759, 1d.9m
    urlhaus-1: 6490-0, 1d.7m
    plowe-0: 3667-2, 6d.21h.54m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 672 ms (selfie)
  maxAssetCacheWait: 64 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    facebook.com: 1
    google-analytics.com: 2
    googlesyndication.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
I was able to reproduce only in firefox:

@matazaOG add & test (after clearing all cookies for that page)

`faceswaponline.com##+js(set, bound, 1)`

**Comment by matazaOG** [comment]
My bad i forgot to mention browser its firefox, im sorry.

@mapx-  cleared cookies and added it to my filters but it didnt change the problem for me.

**Comment by mapx-** [comment]
I was able to reproduce the issue / error even disabling uBO (firefox).

![image](https://user-images.githubusercontent.com/10303732/214512028-e90d09d6-a9ba-4841-90fb-f503054d50fe.png)

It should be reported to the site owner or to whoever created / modified this plugin
`/wp-content/plugins/image-transformer`
