### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by Tuziukaz** [uBlockOrigin/uAssets#16494]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/loltyler1`

### Category

ads

### Description

There is still ads in twitch. I installed extension in new pc and it doesnt work. I tried reset to default but still haven't helped

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 82962
  cosmetic: 38612
  scriptlet: 16866
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-2, never
    easylist: 61352-46, 12m
    easyprivacy: 30872-1172, 11m
    plowe-0: 3667-898, 10m
    ublock-abuse: 77-0, 8m
    ublock-badware: 4169-119, 6m
    ublock-filters: 31675-134, 5m
    ublock-privacy: 258-1, 4m
    ublock-quick-fixes: 499-20, 3m
    ublock-unbreak: 1874-48, 2m
    urlhaus-1: 6603-0, 1m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 710 ms
  maxAssetCacheWait: 110 ms
popupPanel: 
  blocked: 25
  blockedDetails: 
    twitch.tv: 1
    amazon-adsystem.com: 3
    d2v02itv0y9u9t.cloudfront.net: 1
    imrworldwide.com: 2
    scorecardresearch.com: 13
    sentry.io: 3
    serving-sys.com: 1
    ttvnw.net: 1
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
