### ISSUE TITLE
radiofrance.fr: residues

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16493]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.radiofrance.fr/franceinter/paye-ton-pinard-quand-le-monde-du-vin-mesure-son-taux-de-sexisme-5298395`

### Category

residues

### Description

The ads are well blocked, but there are still empty elements and frames that take up space unnecessarily.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/214647095-d23290b4-0306-4954-9e6b-65212fd6d669.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 121852
  cosmetic: 109174
  scriptlet: 20058
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39170-172, 1d.6h.21m
    fanboy-cookiemonster: 44935-213, 7d.10h.25m
  default: 
    user-filters: 0-0, never
    FRA-0: 29987-28, 3d.10h.19m
    easylist: 61280-109, 1d.6h.23m
    easyprivacy: 30872-1588, 1d.6h.22m
    plowe-0: 3667-928, 7d.10h.25m
    ublock-abuse: 77-2, 7d.10h.25m
    ublock-badware: 4375-137, 3d.10h.18m
    ublock-filters: 31720-285, 3d.10h.17m
    ublock-privacy: 258-1, 7d.10h.25m
    ublock-quick-fixes: 505-20, 1h.16m
    ublock-unbreak: 1883-48, 3d.10h.16m
    urlhaus-1: 6603-0, 1h.16m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 423 ms (selfie)
  maxAssetCacheWait: 256 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    aticdn.net: 1
    go-mpulse.net: 2
    privacy-center.org: 1
```
</details>

**Comment by mapx-** [comment]
maybe @smed79 could reproduce the issue

**Comment by Procyon-b** [comment]
I see 4 of them on that page. At the top, 2 on the right side and another in the middle of the text.

```
radiofrance.fr##.PopSlot
```

**Comment by mapx-** [comment]
@x-R0b0T-x report here: https://github.com/easylist/listefr/issues

**Comment by smed79** [comment]
I can reproduce **only if i disable**
```adblock
##.ad_unit
##.dfp-slot
```
or add
```adblock
@@||radiofrance.fr^$generichide
```

**Comment by Procyon-b** [comment]
I still see the placeholders on several computers/browsers (chrome & FF).
`##.dfp-slot``is filtered but the placeholder is above in the html tree.

![rf-source](https://user-images.githubusercontent.com/40043075/215192751-05081479-4ee4-406c-9531-1fe8bedc4fbf.gif)
