### ISSUE TITLE
mirrorcreator detects adblock

### ISSUE THREAD

**Issue by aeosynth** [uBlockOrigin/uAssets#165]
### URL(s) where the issue occurs

`http://www.mirrorcreator.com/files/QWLQGHXB/ade2OTR1.rar_links`

sfw site, nsfw download

### Describe the issue

the site normally loads mirror links; if ublock is enabled, the links are not loaded, and a red bar appears at the bottom of the screen:

> You have Adblock enabled! Recent Adblock filters are known to cause issues with site functionality. If you are unable to access links, please disable Adblock on this domain.

### Versions

- Browser/version: Chromium Version 53.0.2785.143 (64-bit)
- uBlock Origin version: v1.9.10

**Comment by gorhill** [comment]
EasyPrivacy's `/mstats.` is causing this issue. Please report to EasyPrivacy maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

Meanwhile this filter works as a solution: `@@||mirrorcreator.com/mstats.php$xmlhttprequest,first-party`.
