### ISSUE TITLE
rumble.com: breakage

### ISSUE THREAD

**Issue by achuka889** [uBlockOrigin/uAssets#16503]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rumble.com/user/RTnews`

### Category

breakage

### Description

Images don't show on page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 89621
  cosmetic: 81311
  scriptlet: 19436
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62727-1677, 4d.3h.34m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8715-30, 4d.3h.35m
    easylist: 61352-17438, 10h.19m
    easyprivacy: 30872-1268, 10h.18m
    plowe-0: 3669-985, 12d.23h.21m
    ublock-abuse: 77-0, 12d.23h.21m
    ublock-badware: 4374-120, 4d.3h.33m
    ublock-filters: 31829-746, 4d.3h.31m
    ublock-privacy: 258-2, 12d.23h.21m
    ublock-quick-fixes: 505-20, 18h.42m
    ublock-unbreak: 1891-50, 4d.3h.30m
    urlhaus-1: 6603-0, 18h.41m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2509 ms (selfie)
  maxAssetCacheWait: 937 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    facebook.net: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by achuka889** [comment]
I will but it's just that at times the images Show and some and some other
times it doesn't at all

**Comment by stephenhawk8054** [comment]
Which browser are you using?

**Comment by achuka889** [comment]
Lemur browser for android

**Comment by krystian3w** [comment]
Mobile Chromium is not supported.

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue on that browser even when refreshing multiple times or go to other links. Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps outside browser,
