### ISSUE TITLE
Anti-adblock at The Mercury News

### ISSUE THREAD

**Issue by loganrosen** [uBlockOrigin/uAssets#1650]
### URL(s) where the issue occurs

`https://www.mercurynews.com/2018/03/02/sunnyvale-home-shatters-new-record-with-enormous-price-tag/`

### Describe the issue

The article can't be read if ad blocking is turned on. It says that you must subscribe or turn off the ad blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/512317/36930726-39b5ac0a-1e5c-11e8-806a-87b13497fc15.png)

### Versions

- Browser/version: Chrome 64.0.3282.186
- Nano Adblocker version: 1.0.0.33

### Settings

- No changes

### Notes

N/A

**Comment by mapx-** [comment]
Did you test uBo too ?

test also these filters
```
mercurynews.com##script:inject(set-constant.js, dfmCanRunAds, true)
/wp-content/client-mu-plugins/src/Paywall/static/js/connext-paywall-analytics.min.js
```

**Comment by loganrosen** [comment]
I tested uBlock Origin as well. Adding those filters fixes it, thanks!
