### ISSUE TITLE
totalsportk.org: popups

### ISSUE THREAD

**Issue by ScientificEhsan** [uBlockOrigin/uAssets#16508]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://totalsportk.org/`

### Category

popups

### Description

opens up tabs and ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83020
  cosmetic: 38601
  scriptlet: 16863
  html: 872
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32470-56, 2d.7h.8m
    ublock-badware: 4329-0, 2d.7h.9m
    ublock-privacy: 304-0, 10d.26m
    ublock-abuse: 77-0, 10d.27m
    ublock-unbreak: 1891-1, 2d.7h.7m
    easylist: 61230-633, 2d.17h.14m
    easyprivacy: 30872-1741, 2d.17h.13m
    urlhaus-1: 6601-0, 2h.33m
    plowe-0: 3667-2, 9d.16h.55m
    ublock-quick-fixes: 519-0, 2h.32m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 223 ms (selfie)
  maxAssetCacheWait: 102 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
You should provide more details: main page ? a specific channel / server ?

**Comment by ghajini** [comment]
i come with this much ,i can't guess which are live sports now 

```
streamcheck.link,tutelehd.com,unbiasedsenseevent.com,weakstream.org##+js(acs, setTimeout, admc)
crackstreamshd.click,footyhunter.lol,gameshdlive.xyz,tutelehd.com,tvpclive.com,worldstreams.click##+js(aopw, _pop)
crackstreamshd.click,freelivetvon.com,footyhunter.lol,tvpclive.com,wecast.to,worldstreams.click##+js(acs, document.documentElement, break;case $.)
crackstreamshd.click,freelivetvon.com,tvpclive.com,worldstreams.click##+js(aopw, u_cfg)
footyhunter.lol,poscitech.click,wecast.to##+js(nostif, sadbl)
||dgqlwqedzowhqb.com^
||fwilmdact.com^
||yovqnwnmpzz.com^
/adblock.php$script,domain=freelivetvon.com|poscitech.click|tvpclive.com
||switchcast2.com/z-$script
```

**Comment by ghajini** [comment]
@ScientificEhsan update filters & comment here if you find an issue
