### ISSUE TITLE
swarajyamag.com: breakage

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#16518]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://swarajyamag.com/infrastructure/delhi-to-mumbai-expressway-tracker-with-21-packages-totalling-607-kms-complete-pm-modis-dream-project-is-on-a-fast-lane`

### Category

breakage

### Description

Page content completely gets removed after a while, leaving only the header and footer. May have something to do with the subscription filter as the timing is similar to the subscription thingy load time.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 102
filterset (summary): 
  network: 101058
  cosmetic: 50156
  scriptlet: 20043
  html: 1002
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4756-5, 19h.7m
    CHN-0: 28378-143, 19h.6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32507-38, 19h.5m
    ublock-badware: 4190-5, 14h.18m
    ublock-privacy: 305-0, 9d.17h.32m
    ublock-abuse: 77-0, 9d.17h.31m
    ublock-unbreak: 1880-2, 14h.17m
    ublock-quick-fixes: 520-16, 19h.4m
    easylist: 61301-669, 2d.15h.2m
    easyprivacy: 30872-1743, 2d.15h.1m
    urlhaus-1: 6601-0, 19h.2m
    plowe-0: 3667-2, 8d.19h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1041 ms (selfie)
  maxAssetCacheWait: 207 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    swarajyamag.com: 1
    affinity.com: 1
    datawrapper.de: 2
    doubleclick.net: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    onesignal.com: 4
    sentry-cdn.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by Procyon-b** [comment]
It's still doing it with the fix. At least for me.
This seem to work:
```
||swarajyanode-web.quintype.io/quintype-malibu/assets/vendors~access~story-*$script,domain=swarajyamag.com
```

**Comment by mapx-** [comment]
@Procyon-b which filter is blocking it ?

**Comment by Procyon-b** [comment]
I block one more script on `quintype.io`

**Comment by Procyon-b** [comment]
I'm checking on another computer to verify if it's not a glitch on this installation...
