### ISSUE TITLE
nytimes.com: nuisance

### ISSUE THREAD

**Issue by Jimmy59601** [uBlockOrigin/uAssets#16519]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nytimes.com/2023/01/27/climate/colorado-river-biden-cuts.html`

### Category

nuisance

### Description

Although the ads are blocked, the pop-up block appears without the ad content. See screenshot.

![Ad ](https://user-images.githubusercontent.com/56486676/215155103-743d6014-9da1-4dc6-9eb3-30d26f3596bc.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83806
  cosmetic: 38629
  scriptlet: 16885
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.9m
  default: 
    user-filters: 20-0, never
    easylist: 62156-46, 5d.15h.37m
    easyprivacy: 30870-1172, 2d.15h.59m
    plowe-0: 3667-898, 4d.15h.38m
    ublock-abuse: 77-0, 9d.20h.17m
    ublock-badware: 4186-119, 15h.19m
    ublock-filters: 31710-127, 15h.18m
    ublock-privacy: 258-1, 9d.20h.16m
    ublock-quick-fixes: 505-20, 1d.8m
    ublock-unbreak: 1869-48, 15h.17m
    urlhaus-1: 6601-0, 1d.7m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 30 redacted]
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 373 ms (selfie)
  maxAssetCacheWait: 197 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    nytimes.com: 6
    amazon-adsystem.com: 1
    geoedge.be: 1
    googletagmanager.com: 1
    nyt.com: 1
```
</details>

**Comment by mapx-** [comment]
Try using the element picker

**Comment by Jimmy59601** [comment]
Thanks, but I did that and the box still pops up.

**Comment by mapx-** [comment]
What box are you talking about ? screenshot ?

**Comment by Jimmy59601** [comment]
I attached a screenshot to this email. The grayish box is where the ad would appear. uBlock blocks the ad, but the box still appears.
Jimmy
    On Friday, January 27, 2023 at 09:58:55 AM PST, mapx ***@***.***> wrote:  
 
 


What box are you talking about ? screenshot ?

**Comment by mapx-** [comment]
to be able to bypass (for test reasons) the paywall, I added

`nytimes.com##+js(aopr, NYTD)`

However, I get no advertisement marked boxes. I get some grey stuff but where I suppose should be a legit image.

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/215181410-9c764c84-df65-47dc-b80d-933c29afee2d.png)

**Comment by Jimmy59601** [comment]
Yes. That's were the ad/image normally appears. The element picker avoids the image, but the word "Advertisement" appears faintly in the top of the gray box.

**Comment by mapx-** [comment]
I get no `Advertisement` word

**Comment by mapx-** [comment]
You should reset uBO to default settings, update all the lists and test again.

**Comment by stephenhawk8054** [comment]
@Jimmy59601 Can you check if this filter works?

```adb
nytimes.com##[id^="story-ad"][id$="wrapper"]
```

**Comment by Jimmy59601** [comment]
Thanks! That filter seems to work. I'm kind of new to uBlock, so I simply added the string to the end of my filters, as below.

! 2023-01-28 https://www.nytimes.com
www.nytimes.com###story-ad-3-wrapper

nytimes.com##[id^="story-ad"][id$="wrapper"]

**Comment by stephenhawk8054** [comment]
Are you using any extensions to bypass the paywall?
