### ISSUE TITLE
lun.com: ads

### ISSUE THREAD

**Issue by Residentcl** [uBlockOrigin/uAssets#16512]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lun.com/`

### Category

ads

### Description

floating video with advertisement on the home page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![lun com](https://user-images.githubusercontent.com/1659401/214983387-fbfb54b9-8ebb-4c44-b6eb-f293da4092fa.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 87437
  cosmetic: 44437
  scriptlet: 17011
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61524-186, never
    easyprivacy: 30820-1147, never
    plowe-0: 3671-904, never
    spa-0: 3469-21, never
    spa-1: 5017-217, never
    ublock-abuse: 77-0, never
    ublock-badware: 4232-0, never
    ublock-filters: 31551-132, never
    ublock-privacy: 255-0, never
    ublock-quick-fixes: 458-0, never
    ublock-unbreak: 1922-31, never
    urlhaus-1: 8695-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1498 ms
  maxAssetCacheWait: 4 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    lun.com: 6
    alexametrics.com: 1
    google-analytics.com: 1
    twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
`lun.com###dvVideo1`

**Comment by mapx-** [comment]
spanish list @Yuki2718 ?

**Comment by Yuki2718** [comment]
Although I see the rule hit, I can't reproduce the issue. @AdamWr Pls take a look.

**Comment by AdamWr** [comment]
I cannot reproduce it either, but if I'm not wrong, it looks like that website displays this element only if there is a video loaded from external source.
I guess that it may be displayed only sometimes, so I have added this rule.

**Comment by Residentcl** [comment]
The video is no longer available.
Thank you!
PS: Is it possible that you can not see it geographic area?

![lun](https://user-images.githubusercontent.com/1659401/215362084-e94950b0-1f62-458a-80f2-d1a617d2f6d3.jpg)

**Comment by Yuki2718** [comment]
> PS: Is it possible that you can not see it geographic area?

Possible, and if I use VPN they didn't show contents.

**Comment by Residentcl** [comment]
new ad video:
`https://www.lun.com/Pages/NewsDetail.aspx?dt=2023-07-18&EsAviso=0&PaginaId=4&bodyid=0
`![lun](https://github.com/uBlockOrigin/uAssets/assets/1659401/0f35b82b-2cdc-45b5-a6e6-9783658392fa)

**Comment by stephenhawk8054** [comment]
```adb
lun.com##.media
```

**Comment by stephenhawk8054** [comment]
I can reproduce with Vietnamese IP, and looks like this site is in Portuguese so maybe Brazil / Portugal IP might help?

**Comment by AdamWr** [comment]
I can reproduce video player, but as far as I understand, it's rather related to content (at least on my end).

<details><summary>Screenshot</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29142494/e1497a3e-6b71-414d-ba23-d9c84655a4d1)

</details>

I will fix incorrect blocking.

**Comment by Residentcl** [comment]
new ad:
![lun](https://github.com/uBlockOrigin/uAssets/assets/1659401/22e4390e-89fa-404a-9d5d-c9a6cc9e0de0)

**Comment by mapx-** [comment]
@Residentcl provide the exact link of that page

**Comment by Residentcl** [comment]
(https://github.com/uBlockOrigin/uAssets/assets/1659401/9676ab98-bd08-48a6-a263-ca36843f2445

**Comment by mapx-** [comment]
@Yuki2718 

```
||images.lun.com/luncontents/Banners/
lun.com###uctNoticesBanner_divbanner
```

**Comment by Residentcl** [comment]
Ready.
Won't let me close the topic now 🤔
