### ISSUE TITLE
gmx.co.uk: breakage

### ISSUE THREAD

**Issue by DamionD** [uBlockOrigin/uAssets#16515]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gmx.co.uk/`

### Category

breakage

### Description

The login control fails to appear when uBlock Origin is enabled on the page. Disabling the control and reloading the page allows it to appear.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 82996
  cosmetic: 38605
  scriptlet: 16865
  html: 872
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32472-38, 1d.16h.59m
    ublock-badware: 4173-5, 1d.16h.58m
    ublock-privacy: 304-0, 11d.1h.2m
    ublock-abuse: 77-0, 11d.1h.1m
    ublock-unbreak: 1885-2, 1d.16h.57m
    easylist: 61301-632, 4d.58m
    easyprivacy: 30950-1744, 4d.59m
    urlhaus-1: 6601-0, 17h.5m
    plowe-0: 3666-2, 11d.59m
    ublock-quick-fixes: 519-16, 17h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 762 ms (selfie)
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    gmx.co.uk: 1
    criteo.net: 1
    gmx.com: 2
    googletagmanager.com: 1
    uicdn.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
I don’t know what do you mean with `login control` but i can reproduce ads and a failed redirect after i accepted the cookie consent.

Try:

```
@@||uicdn.com/shared/sentry/*/bundle.min.js$script,domain=gmx.*
gmx.*##+js(nostif, UABP)
gmx.*###adservice-top
```

**Comment by DamionD** [comment]
> I don’t know what do you mean with `login control` but i can reproduce ads and a failed redirect after i accepted the cookie consent.
> 
> Try:
> 
> ```
> @@||uicdn.com/shared/sentry/*/bundle.min.js$script,domain=gmx.*
> gmx.*##+js(nostif, UABP)
> gmx.*###adservice-top
> ```

Thanks @JobcenterTycoon. The filter you provided blocks the adverts that were getting around uBlock, but I still cannot login. If you click the envelope graphic with "Log in" below it top right, a login dialogue should slide down from the top of the page:
![image](https://user-images.githubusercontent.com/12510451/215066412-835f1540-22b7-4f61-a187-6ac8b8469a7f.png)

With uBlock enabled on the page, nothing happens.

**Comment by JobcenterTycoon** [comment]
Works fine for me with enabled uBlock Origin

<img width="894" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/215068427-8b09466f-85a6-40c1-9b9d-04e2bb6ed159.PNG">

**Comment by DamionD** [comment]
I will test this at home to see if I get the same results. Thanks for your help @JobcenterTycoon

**Comment by Procyon-b** [comment]
I have an account on gmx.co.uk, and have no problem to log in. It's a spare account and I don't log in very often, but apart from the cookie redirect problem that JobcenterTycoon mentionned I don't have a problem with that site.

I have an email account on all versions of gmx (8 so far) to test my userstyle and userscripts. I also have a set of filters to block unneeded tracking/ad scripts & frames. I'll post them here once your problem is solved (if you want).

**Comment by JobcenterTycoon** [comment]
The ads and the broken redirect are fixed now
