### ISSUE TITLE
gulf-times.com: ads (placeholders)

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16521]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad placeholders all over the site caused by `ghide` in "uBlock filters".

### URL(s) where the issue occurs.

`https://www.gulf-times.com/article/654290/qatar/qatar-pavilion-shares-experiences-from-world-cup-at-municipal-forum-in-riyadh`

### Screenshot(s)

![1 (1)](https://user-images.githubusercontent.com/72945564/215213404-dca44338-9358-4296-a021-5cfc3e366fca.png)

![2](https://user-images.githubusercontent.com/72945564/215213873-e7b25f30-36f5-4c6a-92f2-85079769c6a2.png)

![3](https://user-images.githubusercontent.com/72945564/215213938-40da54aa-3db1-4f45-abdd-53ac50d6dd3d.png)

### uBO version

1.46.1b11

### Browser name and version

Firefox 109 & Opera 94

### Settings

-

**Comment by mapx-** [comment]
I see no ghide in ublock filters

```
gulf-times.com##.gt-horizontal-ad
gulf-times.com##.gt-square-desktop-ad
gulf-times.com##.gt-vertical-ad
```

@ryanbr

**Comment by garry-ut99** [comment]
Ad placeholders dissappear after disabling "uBlock filters", indeed not caused by `ghide` this time, however still caused by uBO filters: `#@#` exceptions.

**Comment by garry-ut99** [comment]
Hmm, ok seems the ad placeholders fooled me, they appear even with "uBlock filters" disabled, what fooled me was they appear after several (like 5) seconds.
