### ISSUE TITLE
streamcheck.link: popups

### ISSUE THREAD

**Issue by Strom415** [uBlockOrigin/uAssets#16525]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://streamcheck.link/97gu?sport=basketball`

### Category

popups

### Description

Adblock no longer works for popups on the reddit nba streaming sites

The sites in question are:

reddit.rnbastreams.com
reddit1.nbastreamlinks.net

The popups actually occur on all of the actual streams linked from these hubs. It was working fine until a month or so ago I believe.

I am using version uBlockOrigin 1.46.0 and have all the default settings

My browser is Chrome version 109.0.5414.119

macOS Ventura 13.1

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83160
  cosmetic: 38395
  scriptlet: 17000
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61176-46, 17m
    easyprivacy: 30886-1172, 17m
    plowe-0: 3665-898, 17m
    ublock-abuse: 77-0, 17m
    ublock-badware: 4191-119, 17m
    ublock-filters: 31995-146, 17m
    ublock-privacy: 260-1, 17m
    ublock-quick-fixes: 504-20, 17m
    ublock-unbreak: 1868-47, 17m
    urlhaus-1: 6554-0, 17m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 495 ms
  maxAssetCacheWait: 234 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    celeritascdn.com: 1
    despik.com: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    youradexchange.com: 1
```
</details>

**Comment by mapx-** [comment]
Test 

`streamcheck.link##+js(rmnt, script, runPop)`
