### ISSUE TITLE
colonist.io: detection

### ISSUE THREAD

**Issue by jayPare** [uBlockOrigin/uAssets#16524]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://colonist.io/`

### Category

detection

### Description

When trying to launch a ranked game, you get a popup that prevents you to do so because it detects an ad blocker (see Screenshot(s) section).

Steps to reproduce
* Log in with an account (Google Account).
* Play at least 5 games
* Try to launch any ranked game  (4 playes or 1 vs 1)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-01-27 205458](https://user-images.githubusercontent.com/8458193/215235856-6bc3c595-6032-4f71-9ec2-e11a9c6819fa.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83789
  cosmetic: 38585
  scriptlet: 16863
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62162-46, 4d.19h.46m
    easyprivacy: 30870-1172, 3d.23h.42m
    plowe-0: 3667-898, 9d.19h.48m
    ublock-abuse: 77-0, 49m
    ublock-badware: 4160-119, 3d.23h.40m
    ublock-filters: 31705-129, 6d.23h.53m
    ublock-privacy: 257-1, 9d.23h.54m
    ublock-quick-fixes: 506-20, 47m
    ublock-unbreak: 1880-47, 3d.23h.41m
    urlhaus-1: 6554-0, 48m
filterset (user): [empty]
urlRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1229 ms (selfie)
  maxAssetCacheWait: 3557 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    adinplay.com: 1
    doubleclick.net: 4
    googleoptimize.com: 1
    googletagmanager.com: 2
    jsdelivr.net: 1
    lr-ingest.io: 1
    threetruck.com: 1
    vlitag.com: 1
    youtube.com: 12
```
</details>

**Comment by stephenhawk8054** [comment]
I did all the steps but even after launching ranked games many times, there are still no anti adblock for me. Force update your filter lists and check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by jayPare** [comment]
This is really from uBlock since when I deactivate it, it goes through. Maybe there is a minimum of game to play before getting to that message?
* Force update your filter lists
_Already did, not change._

* Custom filters
_No custom filter._

* Other extensions
_Deactivated all of them and still get it._

* Browser's built-in blocker
_Not aware of any on Chrome._

* DNS blocking methods
_No DNS blocking methods._

* Blocking apps/softwares outside browser
_None that I'm aware of._

* OS' hosts file to block domains
_Nothing in my host file._

**Comment by stephenhawk8054** [comment]
Did you need to wait a bit after launching a ranked game before the popup appears?

**Comment by jayPare** [comment]
> Did you need to wait a bit after launching a ranked game before the popup appears?

Not really:

https://user-images.githubusercontent.com/8458193/215239806-e6bdda32-819b-482b-9168-315fd773746e.mp4

**Comment by stephenhawk8054** [comment]
It might depend on the account. I cannot reproduce the issue

Video
<details>

https://user-images.githubusercontent.com/66517106/215240481-a5e5f153-7783-45c0-afc6-3f5c687c0f70.mp4

</details>

**Comment by jayPare** [comment]
I don't know if this help:
![image](https://user-images.githubusercontent.com/8458193/215241222-c7681e52-a63a-4113-b977-411482944136.png)

Source: https://blog.colonist.io/colonist-ranked-games-leaderboards-memberhip-system/

**Comment by stephenhawk8054** [comment]
As I cannot reproduce the issue, it would be difficult for me to solve the issue. You might need to wait for others.

**Comment by JobcenterTycoon** [comment]
Can’t reproduce too

**Comment by erik9012** [comment]
send picture of active filter lists

**Comment by jayPare** [comment]
> send picture of active filter lists

ok
![image](https://user-images.githubusercontent.com/8458193/215292171-134b449b-90a3-4b2d-ab7b-49e6e31c48f8.png)

**Comment by jayPare** [comment]
Here is homepage-6bc51053014917aaa004.js. I beautified it so it's easier to read and renamed it to .txt since .js aren't allowed. I think all the magic happens there. Simply Ctrl-F "adblock".

[homepage-6bc51053014917aaa004.txt](https://github.com/uBlockOrigin/uAssets/files/10528733/homepage-6bc51053014917aaa004.txt)

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
colonist.io##+js(set, Object.prototype.adblockState.isAdblockActive, false)
```

**Comment by jayPare** [comment]
> ```
> colonist.io##+js(set, Object.prototype.adblockState.isAdblockActive, false)
> ```

Not working unfortunately.

**Comment by stephenhawk8054** [comment]
Yeah, crafting filters requires a lot of test and error, just the js file is not enough. Can you test

```adb
colonist.io##+js(nostif, Adblock)
```

**Comment by jayPare** [comment]
Now the popup doesn't appear, but the game is not starting either.

**Comment by stephenhawk8054** [comment]
This will just be guessing around, test one by one

```adb
colonist.io##+js(set, adBreak, noopFunc)
colonist.io##+js(aost, adBreak, startPreRoll)
colonist.io##+js(aost, console.log, startPreRoll)
colonist.io##+js(aost, vitag, startPreRoll)
colonist.io##+js(set, Object.prototype.adBlockController, noopFunc)
```

**Comment by jayPare** [comment]
No luck. :(

**Comment by jayPare** [comment]
@mapx- closed as completed?

I just did all the step you provided, still the same result.
