### ISSUE TITLE
Couchtuner player is broken

### ISSUE THREAD

**Issue by DarkRedman** [uBlockOrigin/uAssets#16528]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I navigate on couchtuner with uBO on, the player is broken, but when I deactivate it works.

Checking the the requests journal it seems EasyList is the culprit blocking some inline scripts.

### URL(s) where the issue occurs.

`https://ww1.couchtuner.guru/`

### Notes

Thoses are the 3 rules impacting couchtuner on the js part, the js is used to initialize the player with the video.

couchtuner.*##+js(addEventListener-defuser, , break;case $.)
couchtuner.*##+js(set-constant, atob, trueFunc)
couchtuner.*##+js(abort-current-script, RegExp, 0x)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 103104
  cosmetic: 47077
  scriptlet: 16956
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 64-1, never
    FRA-0: 29989-28, 2d.1h.19m
    easylist: 61117-99, 5h.26m
    easyprivacy: 30885-1494, 5h.27m
    plowe-0: 3668-923, 8d.11h.55m
    ublock-abuse: 77-1, 12d.10h.50m
    ublock-badware: 4169-137, 2d.1h.22m
    ublock-filters: 31679-242, 2d.1h.21m
    ublock-privacy: 257-1, 12d.10h.49m
    ublock-quick-fixes: 507-20, 20h.26m
    ublock-unbreak: 1873-51, 2d.1h.20m
    urlhaus-1: 6559-0, 20h.25m
filterset (user): [array of 64 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 616 ms (selfie)
  maxAssetCacheWait: 348 ms
```
</details>

**Comment by okiehsch** [comment]
Update the `uBO-filters` list.

**Comment by DarkRedman** [comment]
Now it's working.
