### ISSUE TITLE
futemax.app: ads

### ISSUE THREAD

**Issue by willianfsantos** [uBlockOrigin/uAssets#16526]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://futemax.app/`

### Category

ads

### Description

Still opening ads when i click the banner anoucing other live channel website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 84437
  cosmetic: 41919
  scriptlet: 17156
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61437-46, 22h.27m
    easyprivacy: 30879-1172, 22h.26m
    plowe-0: 3667-898, 22h.25m
    spa-1: 5017-65, 22h.30m
    ublock-abuse: 77-0, 22h.20m
    ublock-badware: 4186-119, 22h.18m
    ublock-filters: 31716-166, 22h.17m
    ublock-privacy: 260-1, 22h.15m
    ublock-quick-fixes: 505-20, 22h.14m
    ublock-unbreak: 1869-49, 22h.13m
    urlhaus-1: 6605-0, 22h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 266 ms (selfie)
  maxAssetCacheWait: 165 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    achcdn.com: 1
    celeritascdn.com: 1
    despik.com: 1
    youradexchange.com: 1
```
</details>

**Comment by mapx-** [comment]
You have to be more precise: what exactly to click ? upload a screenshot indicating it
Did you update all your filter lists ?
