### ISSUE TITLE
[nsfw] sextb.net: detection

### ISSUE THREAD

**Issue by ghudengrhandong** [uBlockOrigin/uAssets#16527]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sextb.net/sbnr-323`

### Category

detection

### Description

adblockdetected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="717" alt="adblockdetected" src="https://user-images.githubusercontent.com/123221197/215254657-a26ac624-e8fe-4752-b9ac-ff12eb7934eb.PNG">
<img width="717" alt="adblockdetected" src="https://user-images.githubusercontent.com/123221197/215254690-9645464e-3c36-4027-844a-665ec403fc43.PNG">

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 91325
  cosmetic: 40634
  scriptlet: 33895
  html: 921
listset (total-discarded, last-updated): 
  added: 
    https://cdn.jsdelivr.net/gh/bogachenko/fuckfuckadblock/fuckfuckadblock.txt: 24284-38, 15m
    https://cdn.statically.io/gh/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24284-24284, 15m
    https://raw.githack.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24284-24284, 15m
    https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoBL.hosts: 320-3, 3d.18h.37m
    https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoPF.txt: 295-1, 15m
    https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoWL.dns: 16-0, 3d.18h.37m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24284-24284, 15m
    IDN-0: 5430-1, 3d.18h.37m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32470-2765, 3d.18h.32m
    ublock-badware: 4168-6, 3d.18h.31m
    ublock-privacy: 305-0, 3d.18h.30m
    ublock-abuse: 77-0, 3d.18h.29m
    ublock-unbreak: 1885-1, 3d.18h.13m
    ublock-quick-fixes: 518-0, 15m
    easylist: 61355-649, 3d.18h.13m
    easyprivacy: 30872-1762, 3d.18h.13m
    urlhaus-1: 6554-0, 15m
    plowe-0: 3667-41, 3d.18h.23m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 299 ms (selfie)
  maxAssetCacheWait: 261 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    sextb.net: 1
    addthis.com: 1
    bambao.lol: 12
    cloudflareinsights.com: 2
    googletagmanager.com: 2
    histats.com: 1
    realsrv.com: 4
    streamsb.net: 2
    wpnsrv.com: 2
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
disable all these lists, update the default lists and test again

```
    https://cdn.jsdelivr.net/gh/bogachenko/fuckfuckadblock/fuckfuckadblock.txt: 24284-38, 15m
    https://cdn.statically.io/gh/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24284-24284, 15m
    https://raw.githack.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24284-24284, 15m
    https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoBL.hosts: 320-3, 3d.18h.37m
    https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoPF.txt: 295-1, 15m
    https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoWL.dns: 16-0, 3d.18h.37m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24284-24284, 15m
```

**Comment by mapx-** [comment]
badlist
`https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoPF.txt`

update all lists => purge all caches

**Comment by ghudengrhandong** [comment]
thank you.. (:
