### ISSUE TITLE
fifetoday.co.uk: ads (placeholders)

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16538]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad placeholders caused by `ghide` in "uBlock filters"

### URL(s) where the issue occurs.

`https://www.fifetoday.co.uk/`

### Screenshot(s)

![ttt (1)](https://user-images.githubusercontent.com/72945564/215283517-7be01dce-9ae6-49ff-b8ad-1e6a9204e1d6.png)
![ttt (2)](https://user-images.githubusercontent.com/72945564/215283525-95138975-8961-437d-b211-03814aea550d.png)

### uBO version

1.46.1b11

### Browser name and version

Firefox 109 & Opera 94

### Settings

-

**Comment by Procyon-b** [comment]
Try this:
```
fifetoday.co.uk##[class*="AdWrapper-sc"], [class*="mpu-ad"]
```

**Comment by garry-ut99** [comment]
Yeah, works.
