### ISSUE TITLE
ffcv.es: ads (placeholders)

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16537]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

An ad placeholder on article subpages caused by `ghide` in "uBlock filters".

### URL(s) where the issue occurs.

`https://ffcv.es/wp/blog/2023/01/27/estos-son-los-12-partidos-de-la-tercera-ronda-de-la-nostra-copa-valenta/`

### Screenshot(s)

!['](https://user-images.githubusercontent.com/72945564/215283229-8682c5ea-172b-4075-ac58-9a787f2e6887.png)

### uBO version

1.46.1b11

### Browser name and version

Firefox 109 & Opera 94

### Settings

-

**Comment by Procyon-b** [comment]
try this:
```
ffcv.es###page_wrapper > section.zn_section
ffcv.es##.banneradaptable
```

**Comment by garry-ut99** [comment]
Yes, working.

**Comment by Procyon-b** [comment]
Still, @garry-ut99, you might want to continue to use the 2 filters if you want to recover all the whitespace.

**Comment by garry-ut99** [comment]
Thx, indeed a good idea to hide the white top container as well because it's kinda annoying as it takes unnecessary space in a critical place of the site, but I would rather not maintain my own list as it takes extra time and effort, and not everyone benefits of it, so maybe it can go to EasyList Spanish but I'm not sure whether hidding this container won't break anything, if you're sure it doesn't break anything, I can fill issue on [EasyList Spanish](https://github.com/easylist/easylistspanish/issues) tracker, ok filled anyway: https://github.com/easylist/easylistspanish/issues/295
