### ISSUE TITLE
vk.com: ads

### ISSUE THREAD

**Issue by nightwanderer2010** [uBlockOrigin/uAssets#16535]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vk.com/feed`

### Category

ads

### Description

Advertising in news feed are not blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://user-images.githubusercontent.com/123824989/215276792-d2238bf2-fac3-44d0-bc6b-70c128cc22d4.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 112356
  cosmetic: 205229
  scriptlet: 25542
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62998-982, never
    adguard-social: 19793-848, never
    fanboy-annoyance: 86693-48196, never
    fanboy-cookiemonster: 45207-3550, never
    fanboy-social: 23503-23503, never
    fanboy-thirdparty_social: 69-0, never
    ublock-annoyances: 4782-157, never
  default: 
    user-filters: 15-0, never
    RUS-0: 39182-12, 7h.20m
    easylist: 61239-60, 3h.19m
    easyprivacy: 30886-1281, 3h.18m
    plowe-0: 3667-903, 3d.23h.5m
    ublock-abuse: 77-1, 4d.11h.9m
    ublock-badware: 4169-119, 2d.3h.8m
    ublock-filters: 31679-167, 2d.3h.7m
    ublock-privacy: 258-1, 5d.7h.5m
    ublock-quick-fixes: 507-20, 23h.5m
    ublock-unbreak: 1873-50, 2d.3h.6m
    urlhaus-1: 6559-0, 23h.4m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 275 ms (selfie)
  maxAssetCacheWait: 186 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    vk.com: 2
    mail.ru: 2
    tns-counter.ru: 2
    vk-portal.net: 1
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Looks like they've started a redesign. And for some users it already works.

Fix: https://github.com/easylist/ruadlist/commit/46d91038a9e1fe4739408d140615f572d7ce1955
