### ISSUE TITLE
kiktu.com detection

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#16534]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

same as #16533 

### URL(s) where the issue occurs.

`https://kiktu.com/earn-money-online-without-paying-anything/`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/57501353/215273966-b0047e8f-8e25-4ef5-b31c-aa10cfdabc03.png)
![image](https://user-images.githubusercontent.com/57501353/215273985-b4614775-cfbd-4ff0-9886-b77f19213405.png)

### uBO version

1.46.0

### Browser name and version

chrome 109 on windows 10

### Settings

no changesb

**Comment by ghajini** [comment]
`kiktu.com,techcyan.com##+js(acs, RegExp, 0x)`

is this something an intermediate site?

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a9d488cea73a81dae496c4354c728de64c18b125

**Comment by king-iskan** [comment]
need update for adb, now detection again

**Comment by mapx-** [comment]
@king-iskan when you ask for help remember to provide the info. Where is the link to test ?

**Comment by king-iskan** [comment]
need update for adb, now detection again

> @king-iskan when you ask for help remember to provide all the necessary info. Where is the link to test ?

I'm sorry, I think it's just a matter of continuing the issue above.
This original link https://upshrink.com/OWenmmrhmxn
again sorry🙏

**Comment by mapx-** [comment]
I get the final link in chrome, no detection

**Comment by king-iskan** [comment]
In chrome already try this screenshoot
![20230326_004635](https://user-images.githubusercontent.com/120553425/227733281-108b39a2-ccaf-4977-bd81-2221ac05866a.jpg)
