### ISSUE TITLE
techcyan.com detection

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#16533]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

It appears if i enable ublock origin. It dissapears if i disable ublock origin

### URL(s) where the issue occurs.

`https://techcyan.com/us-allocates-supercomputer-access/`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/57501353/215273707-52960614-de75-4c3f-90c7-aa438e93f35c.png)

![image](https://user-images.githubusercontent.com/57501353/215273747-19283085-e45f-488b-82dd-bbc581d273f6.png)

### uBO version

1.46.0

### Browser name and version

chrome 109 on windows 10

### Settings

no changes

**Comment by mapx-** [comment]
@KinIcy already fixed in uBO
