### ISSUE TITLE
bootscore.me: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#16530]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bootscore.me/`

### Category

ads

### Description

cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 111
filterset (summary): 
  network: 94231
  cosmetic: 118534
  scriptlet: 21887
  html: 0
listset (total-discarded, last-updated): 
  added: 
    IDN-0: 5430-0, 3d.20h.40m
    fanboy-annoyance: 86615-352, 6d.21h.4m
    fanboy-cookiemonster: 45019-45019, 6d.21h.5m
    ublock-annoyances: 4771-73, 3d.20h.39m
  default: 
    user-filters: 0-0, never
    easylist: 61230-45, 3d.20h.45m
    easyprivacy: 30872-1174, 3d.20h.44m
    plowe-0: 3667-898, 2d.9h.42m
    ublock-abuse: 77-0, 2d.20h.53m
    ublock-badware: 4169-119, 3d.20h.43m
    ublock-filters: 31673-188, 3d.20h.42m
    ublock-privacy: 258-9, 2d.20h.52m
    ublock-quick-fixes: 504-20, 5m
    ublock-unbreak: 1874-52, 3d.20h.41m
    urlhaus-1: 6612-0, 4m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2509 ms (selfie)
  maxAssetCacheWait: 401 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    bootscore.me: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Cookie banner not getting fixed by uAssets.
