### ISSUE TITLE
tumblr.com: ads

### ISSUE THREAD

**Issue by chickenwithakeyboard** [uBlockOrigin/uAssets#16536]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tumblr.com/`

### Category

ads

### Description

Tumblr has an annoying "NEW" banner on its toolbar shop icon that never goes away. I tried to remove it using the zapper feature, but it keeps coming back whenever I refresh the page or open a new page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 84890
  cosmetic: 39005
  scriptlet: 16736
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32341-63, never
    ublock-badware: 4236-0, never
    ublock-privacy: 302-0, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1935-31, never
    ublock-quick-fixes: 464-0, never
    easylist: 61524-598, never
    easyprivacy: 30820-1147, never
    urlhaus-1: 8695-0, never
    plowe-0: 3671-564, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1049 ms
  maxAssetCacheWait: 733 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    tumblr.com: 4
    wp.com: 3
```
</details>

**Comment by chickenwithakeyboard** [comment]
WAIT actually I'm just silly and forgot that zapper doesn't create a new filter and thus of course doesn't retain block data. I used element picker and everything's good now. Sorry!

**Comment by mapx-** [comment]
`tumblr.com##.hlDot>*>*>*>[class]:has-text(New)`

or

`tumblr.com##span:xpath("//*[(text()='New')]"):remove()`

**Comment by garry-ut99** [comment]
> chickenwithakeyboard : https://github.com/uBlockOrigin/uAssets/issues/16536#issuecomment-1407438503 : WAIT actually I'm just silly and forgot that zapper doesn't create a new filter and thus of course doesn't retain block data. I used element picker and everything's good now. Sorry!

Not only you:
- `https://github.com/uBlockOrigin/uAssets/issues/16381#issuecomment-1387226377`
- `https://github.com/uBlockOrigin/uAssets/issues/16402#issuecomment-1397078758`
