### ISSUE TITLE
[nsfw] lyricslist.xyz: breakage

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#16544]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bloginguru.xyz/full?api=e7db1a569faabf9402957b7b0d9f3f50e9a18706&url=aHR0cHM6Ly9idXlqaW9jb2luLmNsdWIvdmlldy96S1JFMnNDN3N4&type=2`

### Category

breakage

### Description

Can't bypass..

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 108
filterset (summary): 
  network: 76421
  cosmetic: 47035
  scriptlet: 19975
  html: 1004
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-spyware-url: 897-4, 6m
    ublock-annoyances: 4821-4, 19h.38m
  default: 
    user-filters: 26-0, never
    ublock-filters: 32624-98, 19h.43m
    ublock-badware: 4194-5, 19h.42m
    ublock-privacy: 307-0, 19h.41m
    ublock-abuse: 77-0, 19h.40m
    ublock-unbreak: 1884-3, 19h.39m
    ublock-quick-fixes: 524-0, 5m
    adguard-mobile: 8754-10, 1d.22h.50m
    easylist: 61352-488, 4d.21h.23m
    easyprivacy: 30872-1188, 4d.21h.23m
filterset (user): [array of 10 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2520 ms (selfie)
  maxAssetCacheWait: 1199 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by MayaBi7** [comment]
https://bloginguru.xyz/full?api=e7db1a569faabf9402957b7b0d9f3f50e9a18706&url=aHR0cHM6Ly9idXlqaW9jb2luLmNsdWIvdmlldy96S1JFMnNDN3N4&type=2

**Comment by mapx-** [comment]
No issue on my end, arriving to the last page:

`https://buyjiocoin.club/view/zKRE2sC7sx`
