### ISSUE TITLE
soap2day.to: breakage

### ISSUE THREAD

**Issue by GardenOfEden418** [uBlockOrigin/uAssets#16540]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://soap2day.to/EczoxOToiOTk3N3x8MjQuMTAyLjE5MS40MiI7.html`

### Category

breakage

### Description

Website will not play videos when uBlock origin is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83255
  cosmetic: 38418
  scriptlet: 17039
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61201-46, 18h.59m
    easyprivacy: 30886-1172, 1d.18h.51m
    plowe-0: 3665-898, 4d.21h.38m
    ublock-abuse: 77-0, 19h.1m
    ublock-badware: 4196-119, 1d.18h.50m
    ublock-filters: 32063-151, 1d.18h.49m
    ublock-privacy: 260-1, 19h
    ublock-quick-fixes: 510-20, 18h.58m
    ublock-unbreak: 1868-47, 1d.18h.48m
    urlhaus-1: 6612-0, 18h.57m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 396 ms
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    clksite.com: 1
    d27qffx6rqb3qm.cloudfront.net: 2
    jwpltx.com: 2
    s2dmax.xyz: 9
    s3.us-east-1.amazonaws.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/215291734-04912778-9992-4224-9586-cd9a7ac2f993.png)
