### ISSUE TITLE
nilesoft.org: detection

### ISSUE THREAD

**Issue by JoeBarouneD** [uBlockOrigin/uAssets#16541]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nilesoft.org/docs/`

### Category

detection

### Description

"Adblock detected"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 103120
  cosmetic: 47444
  scriptlet: 16976
  html: 875
listset (total-discarded, last-updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32544-165, 19m
    ublock-badware: 4190-5, 18m
    ublock-privacy: 305-0, 3d.12h.48m
    ublock-abuse: 77-0, 3d.12h.47m
    ublock-unbreak: 1879-2, 17m
    ublock-quick-fixes: 524-0, 15m
    easylist: 61437-688, 3d.1h.21m
    easyprivacy: 30879-1740, 3d.1h.20m
    urlhaus-1: 6612-0, 14m
    plowe-0: 3667-2, 3d.1h.22m
    FRA-0: 30004-395, 16m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 632 ms (selfie)
  maxAssetCacheWait: 168 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by JoeBarouneD** [comment]
Even with the fix, it's the same.

**Comment by venkat2305** [comment]
hello, this issue isn't fixed. I was about to create a new issue but found this. should I create a new issue?
anyway, the website is detecting adblock. 
![image](https://user-images.githubusercontent.com/55329452/215470887-69ed4e7a-11af-4be9-99cb-cad8b680a44b.png)

**Comment by stephenhawk8054** [comment]
@venkat2305 Have you forced update the filter lists?

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by venkat2305** [comment]
the culprits are adguard base and easylist ad blocking lists. turning them off solved the issue. do I miss out anything significant if I turn those off?
![image](https://user-images.githubusercontent.com/55329452/215490688-40bfa219-2377-45fa-bba1-4d2550dd8b1e.png)

**Comment by stephenhawk8054** [comment]
Turning off EasyList is not recommend. Which region are you when accessing the site? Also can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by venkat2305** [comment]
I'm from **India**. 

**1. with easy list enabled**
`uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 153513
  cosmetic: 166979
  scriptlet: 25033
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 40536-4511, 42m
    adguard-annoyance: 63047-245, 42m
    adguard-spyware: 40536-40536, 43m
    adguard-spyware-url: 897-2, 43m
    block-lan: 44-0, 43m
    curben-phishing: 23046-0, 42m
    curben-pup: 188-0, 42m
    dpollock-0: 11395-148, 41m
    fanboy-annoyance: 85932-5358, 42m
    fanboy-cookiemonster: 45336-45336, 42m
    ublock-annoyances: 4784-211, 42m
  default: 
    user-filters: 46-2, never
    easylist: 61268-378, now
    easyprivacy: 30907-12634, 43m
    plowe-0: 3665-1335, 41m
    ublock-abuse: 77-0, 5d.1h.39m
    ublock-badware: 4186-120, 2d.1h.16m
    ublock-filters: 31988-553, 3d.4h.54m
    ublock-privacy: 258-54, 5d.1h.38m
    ublock-quick-fixes: 519-20, 1h.52m
    ublock-unbreak: 1869-74, 3d.4h.54m
    urlhaus-1: 6694-2, 42m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 607 ms (selfie)
  maxAssetCacheWait: 775 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
`

**2. with easy list disabled**
`uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 122004
  cosmetic: 138219
  scriptlet: 25033
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    easylist: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 40536-4511, 43m
    adguard-annoyance: 63047-245, 44m
    adguard-spyware: 40536-40536, 44m
    adguard-spyware-url: 897-2, 44m
    block-lan: 44-0, 44m
    curben-phishing: 23046-0, 44m
    curben-pup: 188-0, 44m
    dpollock-0: 11395-148, 43m
    fanboy-annoyance: 85932-5322, 44m
    fanboy-cookiemonster: 45336-45336, 44m
    ublock-annoyances: 4784-209, 44m
  default: 
    user-filters: 46-2, never
    easyprivacy: 30907-12612, 44m
    plowe-0: 3665-1062, 43m
    ublock-abuse: 77-0, 5d.1h.40m
    ublock-badware: 4186-9, 2d.1h.18m
    ublock-filters: 31988-445, 3d.4h.55m
    ublock-privacy: 258-54, 5d.1h.39m
    ublock-quick-fixes: 519-16, 1h.53m
    ublock-unbreak: 1869-62, 3d.4h.55m
    urlhaus-1: 6694-2, 44m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 607 ms (selfie)
  maxAssetCacheWait: 775 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 2
    googletagmanager.com: 1
`

**Comment by stephenhawk8054** [comment]
You haven't forced update the filter lists. Follow this

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by venkat2305** [comment]
It's fixed. Thanks for helping out
