### ISSUE TITLE
nationalgeographic.com: nuisance

### ISSUE THREAD

**Issue by yashzade** [uBlockOrigin/uAssets#16546]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nationalgeographic.com/travel/article/natural-wonders-that-disappeared`

### Category

nuisance

### Description

Please remove sign in popup, because after sign in they say you have only 3 articles left to read.
I want you to remove that sign in popup so that I can scroll full article.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230129_210806_Kiwi Browser](https://user-images.githubusercontent.com/42665606/215337562-315355a2-df67-4b6e-a822-e0cba7ece57b.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 84672
  cosmetic: 28314
  scriptlet: 16939
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    adguard-mobile: 8758-28, 6h.32m
    easylist: 61179-17021, 1d.2h.13m
    easyprivacy: 30885-1182, 1d.2h.12m
    plowe-0: 3665-982, 7h.52m
    ublock-abuse: 77-0, 7h.50m
    ublock-badware: 4190-120, 1d.2h.10m
    ublock-filters: 31842-384, 1d.2h.9m
    ublock-privacy: 260-2, 7h.49m
    ublock-quick-fixes: 510-20, 7h.44m
    ublock-unbreak: 1873-48, 1d.2h.11m
    urlhaus-1: 6641-0, 7h.46m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1358 ms (selfie)
  maxAssetCacheWait: 440 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
WE don't fix paywalls.

However, you can enable this list (which partially "fix" it)
`Fanboy’s Annoyance`

then add in "my filters"

`nationalgeographic.com##.PaywallModal.Modal`
