### ISSUE TITLE
southwest.com: breakage

### ISSUE THREAD

**Issue by yoIdontwannausername** [uBlockOrigin/uAssets#16542]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.southwest.com/air/booking/purchase.html`

### Category

breakage

### Description

Purchase flight button did not work despite refreshing page and disabling VPN. When southwest.com is added as an exception to uBlock I was able to purchasing a flight.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83201
  cosmetic: 38330
  scriptlet: 16893
  html: 875
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32544-56, 26m
    ublock-badware: 4195-5, 28m
    ublock-privacy: 304-0, 12d.4h.51m
    ublock-abuse: 77-0, 12d.4h.50m
    ublock-unbreak: 1880-1, 27m
    ublock-quick-fixes: 524-0, 25m
    easylist: 61134-641, 29m
    easyprivacy: 30952-1741, 5d.10h.10m
    urlhaus-1: 6641-0, 24m
    plowe-0: 3667-2, 12d.4h.52m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1531 ms (selfie)
  maxAssetCacheWait: 349 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    southwest.com: 4
    go-mpulse.net: 2
    mpeasylink.com: 1
    uplift-platform.com: 13
```
</details>

**Comment by stephenhawk8054** [comment]
Might need to exclude this from `/scripts/analytics/*` in EP

```adb
@@||southwest.com/swa-resources/scripts/analytics/analytics.js$script,1p
```

**Comment by liamengland1** [comment]
It might also be `/__imp_apg__/*` in EP

**Comment by mapx-** [comment]
@yourduskquibbles 

first test only
`@@||southwest.com/swa-resources/scripts/analytics/analytics.js$script,1p`

if does not fix your issue test:

`@@||southwest.com^$script,1p`
