### ISSUE TITLE
readm.org: nuisance

### ISSUE THREAD

**Issue by Burbla** [uBlockOrigin/uAssets#16552]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://readm.org/manga/20816/64/all-pages`

### Category

nuisance

### Description

When blocking the dailymotion ad/banner at the top of the page, it also stops the content from loading. Content can be shown if cosmetics filtering is turned OFF
![cosblocked](https://user-images.githubusercontent.com/30391811/215357886-60694465-7653-4c82-aae9-01c9565ca862.JPG)
![cosbl](https://user-images.githubusercontent.com/30391811/215357893-30a50fd4-af43-4171-b212-d3c93124bc30.JPG)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 113483
  cosmetic: 169642
  scriptlet: 34421
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62948-1678, 3d.8h.19m
    adguard-generic: 67898-938, 3d.8h.21m
    adguard-mobile: 8750-63, 3d.8h.20m
    adguard-social: 19760-1955, 3d.8h.25m
    fanboy-annoyance: 86756-39675, 3d.12h.29m
    fanboy-cookiemonster: 45191-45191, 3d.12h.30m
    fanboy-social: 23498-23498, 4d.20h.34m
    fanboy-thirdparty_social: 68-21, 3d.12h.31m
  default: 
    user-filters: 40-1, never
    easylist: 61235-18084, 5d.20h.38m
    easyprivacy: 30870-1376, 5d.20h.37m
    plowe-0: 3667-996, 8d.20h.52m
    ublock-abuse: 77-0, 1d.13h.39m
    ublock-badware: 4186-311, 3d.8h.24m
    ublock-filters: 31705-4079, 3d.8h.23m
    ublock-privacy: 260-9, 1d.13h.38m
    ublock-quick-fixes: 510-46, 6h.23m
    ublock-unbreak: 1873-93, 3d.8h.22m
    urlhaus-1: 6602-0, 6h.22m
filterset (user): [array of 40 redacted]
trustedset: 
  added: [array of 49 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 344 ms (selfie)
  maxAssetCacheWait: 406 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    audiopulsar.com: 1
    dailymotion.com: 5
    disqus.com: 4
    dm-event.net: 3
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    privacymanager.io: 1
    pubfuture.com: 3
    taboola.com: 1
    viglink.com: 2
    vlitag.com: 1
```
</details>

**Comment by garry-ut99** [comment]
`readm.org###“videoo”` works for me, it hides the banner and the site content loads fine, you most likely created a different bad filter
