### ISSUE TITLE
df.cl: popup

### ISSUE THREAD

**Issue by Residentcl** [uBlockOrigin/uAssets#16557]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.df.cl/`

### Category

nuisance

### Description

popup for account registration

This site has many different types of advertising,
it is necessary to see the contents in order for it to be visible.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![df](https://user-images.githubusercontent.com/1659401/215367777-7db27964-e130-493c-9365-51804b5c2c42.jpg)
Other subscription advertising: ![df 3](https://user-images.githubusercontent.com/1659401/215368381-0e573757-39dc-4852-b312-936dbb22cc06.jpg)
![df](https://user-images.githubusercontent.com/1659401/215522376-0b1b261b-b3eb-459e-ac18-41bb44f48648.jpg)

Separate question Is it possible to remove a block to read paid notes?
Like the following: 
https://www.df.cl/empresas/industria/nuevamente-pierden-los-taxistas-corte-suprema-rechaza-reclamacion
![df 2](https://user-images.githubusercontent.com/1659401/215368026-fa9b34eb-76d0-4083-88bc-959fe4aef2bb.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 85825
  cosmetic: 43897
  scriptlet: 17316
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61250-46, 1h.42m
    easyprivacy: 30904-1172, 1h.42m
    plowe-0: 3665-898, 1h.42m
    spa-0: 3469-10, 1h.42m
    spa-1: 5021-187, 1h.42m
    ublock-abuse: 77-0, 1h.42m
    ublock-badware: 4196-119, 1h.42m
    ublock-filters: 32083-191, 1h.42m
    ublock-privacy: 260-1, 1h.42m
    ublock-quick-fixes: 510-20, 1h.42m
    ublock-unbreak: 1868-49, 1h.42m
    urlhaus-1: 6602-0, 1h.42m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 199 ms (selfie)
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 49
  blockedDetails: 
    df.cl: 1
    chartbeat.com: 1
    cxense.com: 2
    doubleclick.net: 6
    facebook.net: 1
    google-analytics.com: 2
    google.com: 9
    googletagmanager.com: 2
    googletagservices.com: 1
    newsroom.bi: 4
    piano.io: 1
    scorecardresearch.com: 1
    youtube.com: 18
```
</details>

**Comment by stephenhawk8054** [comment]
Maybe for Annoyance lists?

@ryanbr

**Comment by mapx-** [comment]
In the end this site has implemented a paywall, we didn't fix officially such "issues".

add in your personal filters
`||tinypass.com^`

**Comment by Residentcl** [comment]
Sorry if I was not clear.
All advertising is for paid subscription with different modes.
The vast majority of the notes are free to read,
but there are different types of advertising for subscription.

That's why I asked separately if it was possible to remove the payment block.

**Comment by Residentcl** [comment]
It is useful to remove what is necessary to be able to read the free notes.

**Comment by mapx-** [comment]
> Did you test the filter above ?

**Comment by Residentcl** [comment]
Yes, this solution works.
