### ISSUE TITLE
Impossible to use certan website

### ISSUE THREAD

**Issue by trimechee** [uBlockOrigin/uAssets#16551]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I have message to disable adblock

### URL(s) where the issue occurs.

https://www.rjno1.com/

### uBO version

Block Origin 1.46.0

### Browser name and version

Microsoft edge   109.0.1518.70 

### Settings

I disable cosmetic filters

**Comment by liamengland1** [comment]
@JobcenterTycoon

**Comment by trimechee** [comment]
@liamengland1 @JobcenterTycoon Hello ! really I am sorry to to have disturbed you, I read the article of Banana and its purpose is to help websites monetize their content and i think it's legit, i think it is not a good thing to fight this ad detector and it's better that i close this issue, thank you vey much :)

**Comment by trimechee** [comment]
It seems that not all this website block ads, i can use this par of website with Ublock origin enabled :  https://www.rjno1.com/mpv-easy-player-en-us/
