### ISSUE TITLE
ejgiftcards.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#16554]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Add a gift card to your cart. Fill out billing info. Click Submit Order button to go to the next page to enter credit card info. Button stays loading forever.

### URL(s) where the issue occurs.

`https://ejgiftcards.com`

### uBO version

1.46.0

### Browser name and version

Chrome 109

### Settings

N/A

### Notes

`@@||www.googletagmanager.com^$script,domain=ejgiftcards.com`

Also, if paying with crypto, it said `a network error has occured`, but I wasn't able to reproduce that to test further, but I did see some Coinbase URLs being blocked. Please take a look at that too. Thanks!

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtag/js$script,domain=ejgiftcards.com
```

@ryanbr
