### ISSUE TITLE
hwinfo.com: ads

### ISSUE THREAD

**Issue by Uranite** [uBlockOrigin/uAssets#16562]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hwinfo.com/download/`

### Category

ads

### Description

A lansweeper ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/62639703/215452632-81b214ba-a920-4342-ab6c-b9d3bcbc4cba.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 111
filterset (summary): 
  network: 93289
  cosmetic: 115809
  scriptlet: 20632
  html: 881
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2115-3, never
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7796-2, 48m
    adguard-annoyance: 63020-1552, 49m
    adguard-social: 19795-36, 49m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32901-316, 49m
    ublock-badware: 4205-5, 49m
    ublock-privacy: 307-0, 49m
    ublock-abuse: 77-0, 49m
    ublock-unbreak: 1879-2, 49m
    ublock-quick-fixes: 524-0, 49m
    easylist: 61256-652, 49m
    easyprivacy: 30907-1744, 49m
    urlhaus-1: 6654-0, 49m
    plowe-0: 3665-2, 49m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 188 ms (selfie)
  maxAssetCacheWait: 107 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cloudflareinsights.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    quantcast.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
