### ISSUE TITLE
games2rule.com: detection

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16566]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

anti-adblock, (to reproduce, need to apply a fix for the breakge first: https://github.com/easylist/easylist/issues/14838)

### URL(s) where the issue occurs.

Example subpage with game: 
`https://www.games2rule.com/play/find-woodpecker-pair-html5/38642`

### Screenshot(s)

![ee](https://user-images.githubusercontent.com/72945564/215498751-b18c05a1-c50d-4f4a-8465-ca2efd7561f5.png)

### uBO version

1.46.1b13

### Browser name and version

Firefox 109 & Opera 94

### Settings

uBO annoyances

**Comment by stephenhawk8054** [comment]
It appears even when I disable uBO

Screenshot  
<details>

![image](https://user-images.githubusercontent.com/66517106/215506036-dedccaa8-c8b8-4263-bc6c-a68c0fa91026.png)

</details>

**Comment by ghajini** [comment]
just click play

**Comment by garry-ut99** [comment]
> stephenhawk8054 : It appears even when I disable uBO

Right, I did check with uBO disabled, before creating the issue, but it seems I only pressed Start game, and forgot to press Next.

> ghajini : just click play

Right, it's just a warning. lol
