### ISSUE TITLE
[nsfw] bluemediafile.sbs: breakage

### ISSUE THREAD

**Issue by Terunaru** [uBlockOrigin/uAssets#16565]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bluemediafile.sbs/url-generator.php?url=KH1TK0eBXmDmljELeo4C+LZSaS3jdAxFdZ1pTt/34+n9Y4qn/CPU1ipZMDfc/CXWTbRmsdneRr0Gp/DuRJFIxokgSApMNVMtI/EwB2MTWSo=`

### Category

breakage

### Description

breakage

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 85
filterset (summary): 
  network: 101211
  cosmetic: 49021
  scriptlet: 17147
  html: 874
listset (total-discarded, last-updated): 
  added: 
    https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt: 141-0, 53d.47m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-5, 7d.7h.29m
  default: 
    user-filters: 60-0, never
    ublock-filters: 32760-74, 4d.1h.38m
    ublock-badware: 4173-5, 4d.1h.36m
    ublock-privacy: 305-0, 6d.3h.35m
    ublock-abuse: 77-0, 6d.3h.36m
    ublock-unbreak: 1884-1, 4d.1h.37m
    easylist: 61394-997, 5d.19h.29m
    easyprivacy: 30872-1182, 5d.19h.30m
    urlhaus-1: 6641-0, 1d.1h.19m
    plowe-0: 3667-563, 12d.7h.17m
    CHN-0: 28377-133, 4d.1h.39m
    ublock-quick-fixes: 524-1, 1d.1h.21m
filterset (user): [array of 59 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5929 ms (selfie)
  maxAssetCacheWait: 2075 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adskeeper.com: 2
    choobinoobi.com: 3
    ctsjackupspete.com: 2
    google-analytics.com: 1
    picinow.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Did you

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
> - [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

?

**Comment by garry-ut99** [comment]
I've added: `bluemediafile.sbs##+js(nano-sib, dem, 1000)` to boost the timer and it's working, but then an anti-block appearing:

![ewe](https://user-images.githubusercontent.com/72945564/215504197-53588263-2c5e-4537-af21-faa97a28541c.png)

**Comment by garry-ut99** [comment]
To be clear, there is no such commit [in the closed issues.](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+bluemediafile), only two issues where someone mentions an userscript to bypass the timer: https://github.com/uBlockOrigin/uAssets/issues/14783#issuecomment-1243298970 +  https://github.com/uBlockOrigin/uAssets/issues/15944#issuecomment-1341053866.

**Comment by stephenhawk8054** [comment]
It was a constant cat-and-mouse scenario with the site (similar to other issues in quick list), so the filters were updated while minimizing mentioning the issues.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by mapx-** [comment]
> Firefox: 85

You should use an uodated browser

**Comment by krystian3w** [comment]
> where someone mentions an userscript 

User script links can by removed.
