### ISSUE TITLE
fosslinux.com: detection

### ISSUE THREAD

**Issue by SnowballV** [uBlockOrigin/uAssets#16563]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fosslinux.com/`

### Category

detection

### Description

Today, January 30, 2023, fosslinux.com detects uBO and says 'Adblock Detected; Please support us by disabling your AdBlocker extension from your browsers for our website.' This can be dismissed by selecting 'Dismiss this message'.
However, I tried adding the right filters using the element picker, to hide the message. After adding four filters, the page looks clean, but is unusable, cannot be scrolled, I guess there is still something blocking use of the page.
Therefore, the only way to get access is not to use the element picker rules and click 'Dismiss this message'.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 87684
  cosmetic: 59952
  scriptlet: 17063
  html: 882
listset (total-discarded, last-updated): 
  added: 
    fanboy-social: 23312-7, now
    NLD-0: 2568-20, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33031-210, now
    ublock-badware: 4210-5, now
    ublock-privacy: 307-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1879-2, now
    ublock-quick-fixes: 533-0, now
    easylist: 61257-654, now
    easyprivacy: 30907-1745, now
    urlhaus-1: 6654-0, now
    plowe-0: 3665-2, now
filterset (user): [empty]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2458 ms (selfie)
  maxAssetCacheWait: 1634 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    pubpowerplatform.io: 2
```
</details>

**Comment by iam-py-test** [comment]
Can you add this rule to your "My filters" tab and retest (and report back):
```adblock
@@||fosslinux.com^$ghide
```
Be sure you reenable Cosmetic Filtering if you disabled it.

**Comment by SnowballV** [comment]
Thank you, that works.
Adding that rule removes the detection, removing that rule brings back the detection.

And I see this issue was already closed as completed, two minutes ago.

**Comment by iam-py-test** [comment]
Please remove the rule I gave you and [update your filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches).
Thank you for reporting this.

**Comment by SnowballV** [comment]
Thanks, I already did.
Thank you again for fixing this so quickly.
