### ISSUE TITLE
emol.com: popups

### ISSUE THREAD

**Issue by Residentcl** [uBlockOrigin/uAssets#16564]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.emol.com/`

### Category

popups

### Description

1: automatic opening of facebook popup:

`https://www.facebook.com/v2.9/dialog/oauth?app_id=316568105042097&auth_type=rerequest&cbt=1675084077492&channel_url=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df2a9ebea00beec8%26domain%3Dwww.emol.com%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Fwww.emol.com%252Ff1ed34926337034%26relation%3Dopener&client_id=316568105042097&display=popup&domain=www.emol.com&e2e=%7B%7D&fallback_redirect_uri=https%3A%2F%2Fwww.emol.com%2Fnoticias%2FNacional%2F2018%2F08%2F31%2F919115%2FIntendente-de-Valparaiso-tras-COE-Indices-de-contaminacion-han-disminuido.html&locale=es_LA&logger_id=fd021b708f3bd4&origin=1&redirect_uri=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df353b8664183f14%26domain%3Dwww.emol.com%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Fwww.emol.com%252Ff1ed34926337034%26relation%3Dopener%26frame%3Df2af53ca2a7635&response_type=token%2Csigned_request%2Cgraph_domain&scope=email%2Cpublic_profile&sdk=joey&version=v2.9`

2: video advertising:
`https://www.emol.com/noticias/Nacional/2018/08/31/919115/Intendente-de-Valparaiso-tras-COE-Indices-de-contaminacion-han-disminuido.html`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

1:
![facebook](https://user-images.githubusercontent.com/1659401/215486926-287e59e2-ec0c-40e1-bc71-8009c417e7df.jpg)
2:
![video](https://user-images.githubusercontent.com/1659401/215487553-4531d269-cade-4129-91f4-5e1b4bacd3ec.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 85825
  cosmetic: 43897
  scriptlet: 17316
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61250-46, 13h.44m
    easyprivacy: 30904-1172, 13h.44m
    plowe-0: 3665-898, 13h.44m
    spa-0: 3469-10, 13h.44m
    spa-1: 5021-187, 13h.44m
    ublock-abuse: 77-0, 13h.44m
    ublock-badware: 4196-119, 13h.44m
    ublock-filters: 32083-191, 13h.44m
    ublock-privacy: 260-1, 13h.44m
    ublock-quick-fixes: 510-20, 13h.44m
    ublock-unbreak: 1868-49, 13h.44m
    urlhaus-1: 6602-0, 13h.44m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 98 ms (selfie)
  maxAssetCacheWait: 57 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    emol.com: 2
    emol.cl: 6
    facebook.com: 2
    google-analytics.com: 2
    guioteca.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
emol.com##.link-img[href*="banner"]
.emol.com##.banner_on_random
```

@Yuki2718

**Comment by mapx-** [comment]
nvm maybe I didn't enable the reginal lists in the first test

**Comment by Residentcl** [comment]
:(

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Residentcl** [comment]
I have done this process before,
Does it look like you can't see the advertisements by using VPN?
Here is another picture with more detail:
![emol](https://user-images.githubusercontent.com/1659401/215756221-2d7d43a9-f3dc-4f9c-bf05-b8514b502a54.jpg)

**Comment by mapx-** [comment]
Did you test these filters ?

```
emol.com##.link-img[href*="banner"]
emol.com##.banner_on_random
```

**Comment by Residentcl** [comment]
Yes, but a new one may come out.

**Comment by mapx-** [comment]
add this also filter & test again

`emol.com###publi_right`

**Comment by Residentcl** [comment]
There, now nothing comes out.

**Comment by mapx-** [comment]
ok, @Yuki2718 could you add to the regional list the filters above ?

**Comment by Yuki2718** [comment]
Neither could I reproduce, but added anyway.
