### ISSUE TITLE
gceguide.com: ads (placeholders)

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16567]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Yellow ad placeholders all over the site caused by `ghide` in "uBlock filters".

### URL(s) where the issue occurs.

`https://gceguide.com/`

### Screenshot(s)

![33333](https://user-images.githubusercontent.com/72945564/215517941-e071a34b-e43b-4ef2-a573-58c8078591e6.png)

### uBO version

1.46.1b13

### Browser name and version

Firefox 109 & Opera 94

### Settings

- uBO annoyances

**Comment by ghajini** [comment]
can't repro antiadb `https://github.com/NanoMeow/QuickReports/issues/805` so removed filters
