### ISSUE TITLE
fflogs.com: detection

### ISSUE THREAD

**Issue by Boxx1247** [uBlockOrigin/uAssets#16570]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fflogs.com/`

### Category

detection

### Description

Has a banner at the top and bottom of every page that asks the user to disable adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83094
  cosmetic: 38654
  scriptlet: 16888
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 61418-46, 5d.22h.20m
    easyprivacy: 30872-1172, 5d.22h.21m
    plowe-0: 3667-898, 3d.21h.4m
    ublock-abuse: 77-0, 5d.18h.17m
    ublock-badware: 4169-119, 3d.17h.1m
    ublock-filters: 31710-135, 3d.17h
    ublock-privacy: 258-1, 5d.18h.16m
    ublock-quick-fixes: 510-20, 3h.48m
    ublock-unbreak: 1869-47, 3d.16h.59m
    urlhaus-1: 6694-0, 3h.47m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 104 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by garry-ut99** [comment]
Example:
`||cdn.intergient.com/*/*/ramp.js$script,redirect-rule=noopjs,domain=fflogs.com`
`fflogs.com###top-banner, #bottom-banner`

**Comment by okiehsch** [comment]
Fixed in the annoyance list.
