### ISSUE TITLE
fosslinux.com: detection

### ISSUE THREAD

**Issue by SnowballV** [uBlockOrigin/uAssets#16579]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fosslinux.com/`

### Category

detection

### Description

Today, January 31, 2023, fosslinux.com detects uBO and says 'Adblock Detected; Please support us by disabling your AdBlocker extension from your browsers for our website.' This can be dismissed by selecting 'Dismiss this message'.

A similar issue was reported and fixed, yesterday, see: [https://github.com/uBlockOrigin/uAssets/issues/16563](https://github.com/uBlockOrigin/uAssets/issues/16563)
It looks like fosslinux.com circumvents that fix, today.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 87813
  cosmetic: 59909
  scriptlet: 17070
  html: 883
listset (total-discarded, last-updated): 
  added: 
    fanboy-social: 23238-7, now
    NLD-0: 2568-20, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33046-210, now
    ublock-badware: 4220-5, now
    ublock-privacy: 306-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1880-3, now
    ublock-quick-fixes: 533-0, now
    easylist: 61357-657, now
    easyprivacy: 30909-1745, now
    urlhaus-1: 6697-1, now
    plowe-0: 3668-2, now
filterset (user): [empty]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1709 ms (selfie)
  maxAssetCacheWait: 1041 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    pubpowerplatform.io: 2
```
</details>

**Comment by SnowballV** [comment]
@ghajini,
Thanks very much.
Please let me know when this is updated in uBO filters. I purged and updated, but it didn't help, I guess the fix was not in the filters, yet.

**Comment by iam-py-test** [comment]
GitHub takes a few minutes before it makes the update available. It shows as available now. Please open the uBo settings, and click on "Purge all caches" in the "filterlists" tab, and then click "update now".

**Comment by SnowballV** [comment]
I purged and updated again, and now all is well.
Thanks very much.
