### ISSUE TITLE
booktoki215.com: ads

### ISSUE THREAD

**Issue by pololoduck** [uBlockOrigin/uAssets#16574]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://booktoki215.com/`

### Category

ads

### Description

Hello, no matter what I do, I could never remove the flashing multiple row of ads that are on the top of this website. This website also changes its url to other domain frequently with the same look, but even with element zapper it would remove the ad for a few seconds then the same ad would just come back.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/121998563/215683657-885954b3-7ecc-4c1f-89a1-42a5a3c31db8.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83128
  cosmetic: 38314
  scriptlet: 16891
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 61117-46, 2d.23h.16m
    easyprivacy: 30879-1172, 2d.23h.15m
    plowe-0: 3665-898, 2d.23h.14m
    ublock-abuse: 77-0, 2d.23h.12m
    ublock-badware: 4191-119, 2d.23h.10m
    ublock-filters: 31715-135, 2d.23h.9m
    ublock-privacy: 260-1, 2d.23h.8m
    ublock-quick-fixes: 519-20, 1h.16m
    ublock-unbreak: 1868-46, 2d.23h.5m
    urlhaus-1: 6650-0, 5h.17m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 176 ms (selfie)
  maxAssetCacheWait: 156 ms
popupPanel: 
  blocked: 0
  no-cosmetic-filtering: true
  no-large-media: true
```
</details>

**Comment by mapx-** [comment]
add

`com##[src*=".gif?_="]`

@piquark6046

**Comment by pololoduck** [comment]
Thank you!

**Comment by piquark6046** [comment]
@mapx- The related filters exist in List-KR filters list.
`/^https:\/\/booktoki[0-9]+\.com\/tokinbtoki\/[0-9]+/`

@pololoduck Please enable List-KR filters list and reload it.
