### ISSUE TITLE
riteaid.com: breakage

### ISSUE THREAD

**Issue by brettowe** [uBlockOrigin/uAssets#16571]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.riteaid.com/shop/catalogsearch/result/?q=super`

### Category

breakage

### Description

search's on this site doesn't work until ublock is turned off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83130
  cosmetic: 38359
  scriptlet: 16898
  html: 876
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32568-54, 15h.46m
    ublock-badware: 4190-5, 4d.28m
    ublock-privacy: 307-0, 2d.22h.48m
    ublock-abuse: 77-0, 2d.22h.47m
    ublock-unbreak: 1884-0, 4d.27m
    easylist: 61177-641, 1d.16h.32m
    easyprivacy: 30887-1745, 15h.47m
    urlhaus-1: 6602-0, 1d.3h.50m
    plowe-0: 3665-2, 15h.48m
    ublock-quick-fixes: 524-1, 1d.3h.49m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 80 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2612 ms (selfie)
  maxAssetCacheWait: 58 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    adobedtm.com: 4
    bazaarvoice.com: 1
    d26opx5dl8t69i.cloudfront.net: 1
    demdex.net: 1
    elevaate.io: 1
    everestjs.net: 1
    everesttech.net: 1
    googletagmanager.com: 1
    newrelic.com: 1
    omtrdc.net: 1
    signifyd.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||cloudfront.net/js/reflektion.js$script,domain=riteaid.com`
