### ISSUE TITLE
mountainstar.com: breakage

### ISSUE THREAD

**Issue by tmccombs** [uBlockOrigin/uAssets#16575]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mountainstar.com/locations/timpanogos-regional-hospital/about/contact-us.dot`

### Category

breakage

### Description

Attempting to submit with the contact form with uBO enabled just hangs forever with the button saying "Submitting..." (see screenshot).

If I disable uBO it submits fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/2541726/215686926-b4ab3323-4b12-43a9-967b-45248017b641.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 84968
  cosmetic: 79569
  scriptlet: 18591
  html: 860
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 18d.15m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    fanboy-cookiemonster: 45213-192, 2d.39m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32544-38, 2d.37m
    ublock-badware: 4200-5, 2d.36m
    ublock-privacy: 305-0, 6d.23h.57m
    ublock-abuse: 77-0, 6d.23h.56m
    ublock-unbreak: 1879-0, 2d.38m
    easylist: 61354-658, 24m
    easyprivacy: 30908-1742, 23m
    plowe-0: 3665-2, 2d.41m
    urlhaus-1: 6650-0, 22m
filterset (user): [empty]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3297 ms (selfie)
  maxAssetCacheWait: 141 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    ehc.com: 7
    formstack.com: 1
    google.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by tmccombs** [comment]
My guess is it is probably because it uBO is blocking "https://www.formstack.com/forms/analytics.php?f=4897216&a=v&m=htmlembed"

and when I try to submit I see the following JS error in the console: 

```
Uncaught ReferenceError: hcaAnalyticsEventMap is not defined
    onreadystatechange https://core.secure.ehc.com/src/widgets/forms/formstack/v1/assets/formstack.min.js?v=01252023181400:1
    onsubmit https://core.secure.ehc.com/src/widgets/forms/formstack/v1/assets/formstack.min.js?v=01252023181400:1
formstack.min.js:1:2960
    onreadystatechange https://core.secure.ehc.com/src/widgets/forms/formstack/v1/assets/formstack.min.js?v=01252023181400:1
    (Async: EventHandlerNonNull)
    onsubmit https://core.secure.ehc.com/src/widgets/forms/formstack/v1/assets/formstack.min.js?v=01252023181400:1
```

**Comment by mapx-** [comment]
Test this filter

`@@||core.secure.ehc.com/design/lib/analytics/google-tag-manager/assets/hut-analytics-api-controller.min.js$script,domain=mountainstar.com`
