### ISSUE TITLE
alternativeto.net: ads

### ISSUE THREAD

**Issue by schackbrian2012** [uBlockOrigin/uAssets#16572]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://alternativeto.net/tag/ai/`

### Category

ads

### Description

This webpage contains an advertisement. uBlock Origin correctly removes the advertisement. But it leaves a blank space where the advertisement would go.

`https://alternativeto.net/tag/ai/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 82946
  cosmetic: 38297
  scriptlet: 16681
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61239-46, 3d.1h.38m
    easyprivacy: 30882-1172, 3d.1h.37m
    plowe-0: 3667-898, 9d.17h.43m
    ublock-abuse: 77-0, 5d.6h.35m
    ublock-badware: 4196-119, 1d.3h.28m
    ublock-filters: 31718-135, 1d.3h.27m
    ublock-privacy: 258-1, 5d.6h.34m
    ublock-unbreak: 1868-44, 1d.3h.26m
    urlhaus-1: 6602-0, 23h.19m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 100 ms (selfie)
  maxAssetCacheWait: 40 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    alternativeto.net: 1
    google-analytics.com: 1
    google.com: 5
    googlesyndication.com: 3
    googletagmanager.com: 1
    requestmetrics.com: 2
    trackjs.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`alternativeto.net##.AdsenseAd_atf1_experiment__Fm3pU`

@ryanbr

**Comment by stephenhawk8054** [comment]
For me it's `.AdsenseAd_atf1__gjOt9` so maybe `##[class^="AdsenseAd_atf1"]`

**Comment by krystian3w** [comment]
Won:

```adb
##[class^="AdsenseAd"]
```
