### ISSUE TITLE
[Request] Reporting Tool Like AdGuard Has

### ISSUE THREAD

**Issue by zero77** [uBlockOrigin/uAssets#1657]
Can you please consider making a reporting tool like adguard provides users to report adds.

Because it makes things a lot easier for both developers and users.
Thanks

https://reports.adguard.com/en/new_issue.html -Report Tool

https://github.com/AdguardTeam/AdguardFilters/issues - Repository

**Comment by gorhill** [comment]
Given that uBO has no server, how would you do it?

**Comment by zero77** [comment]
Yes, this has crossed my mind, one I dear could be to use surveys.
Although, they must be a better service available than this.

**Comment by cryguy** [comment]
Maybe do it via github? using the api?

**Comment by Erikuio** [comment]
+1

i must create account here-much work-tool is good-easy to use-better reports for filters creators

**Comment by jspenguin2017** [comment]
On my side all I'm missing is backend code. I don't want to use GitHub API because it forces the user to create an account which means it'll be not a one-click report button. 

For server, can't you use `http://raymondhill.net/`?

**Comment by gorhill** [comment]
I don't want to maintain a web site aside everything else. My question to @zero77 was rhetorical: I want people who ask for stuff to imagine what they would need to do it they directed theit own request at themselves to realize the work they are asking someone else to do.
