### ISSUE TITLE
gathering.tweakers.net: breakage

### ISSUE THREAD

**Issue by Vansloneker** [uBlockOrigin/uAssets#16585]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gathering.tweakers.net/forum/list_messages/2168160/last`

### Category

breakage

### Description

Images are being blocked, issue appeared a couple of days ago. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 91
filterset (summary): 
  network: 89669
  cosmetic: 113508
  scriptlet: 19285
  html: 864
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62992-598, 4d.5m
    adguard-social: 19793-836, 4d.6m
    fanboy-thirdparty_social: 68-3, 5h.34m
    NLD-0: 2568-54, 23h.57m
  default: 
    user-filters: 437-5, never
    ublock-filters: 32313-40, 4d.4m
    ublock-badware: 4195-6, 4d.3m
    ublock-privacy: 307-0, 2d.9h.22m
    ublock-abuse: 77-0, 2d.9h.21m
    ublock-unbreak: 1880-0, 4d.1m
    ublock-quick-fixes: 398-30, 22h.21m
    easylist: 61179-277, 3d.5h.25m
    easyprivacy: 30886-1208, 3d.5h.24m
    urlhaus-1: 6694-0, 22h.20m
    plowe-0: 3668-902, 12d.8h.42m
filterset (user): [array of 437 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1459 ms (selfie)
  maxAssetCacheWait: 1138 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    tweakers.net: 5
    usabilla.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
Caused by
`||tweakers.net/*/?$image`

**Comment by JohnyP36** [comment]
`||tweakers.net/*/?url$image` (new rule in EasyList) will not fix the problem.

Tweakers put both the tracking images as normal pictures in the same url. Which is stupid, because it is hard to block them

**Comment by Vansloneker** [comment]
I want to thank for the quick solution. It works good for me.
For as much as I understand Tweakers has made it their policy to not use advertisement tracking: https://tweakers.net/reviews/10152/advertenties-zonder-tracking-de-techniek-achter-trackingvrij-adverteren.html
