### ISSUE TITLE
chromeactions.com: detection

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16588]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

anti-adblock

### URL(s) where the issue occurs.

`https://www.chromeactions.com/`

### Screenshot(s)

![gfgfgfgfg](https://user-images.githubusercontent.com/72945564/215855554-15a394bb-6da1-4168-a3dc-2868ae0fad14.png)

### uBO version

1.46.1b14

### Browser name and version

Firefox 109 & Opera 94

### Settings

-

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`.

**Comment by JobcenterTycoon** [comment]
The fix doesn’t work for me. The obfuscated detection script coming from `https://www.chromeactions.com/js/JZJjSshCW.js` on my end and not even has a setTimeout

**Comment by garry-ut99** [comment]
Yeah, I've been just about to say it does work randomly like 5 out of 10 times, like race condition, both on Firefox and Opera, and when I was checking at the time it wasn't working I noticed uBO console showing no `setTimeout` on the site.

**Comment by mapx-** [comment]
Does this work for you @JobcenterTycoon 

`chromeactions.com##+js(acs, Math.random)`

**Comment by ghajini** [comment]
is it just warning, no real function of website is obscured

**Comment by okiehsch** [comment]
> The fix doesn’t work for me.

Hm, I reloaded the site 10+times with no detection. As soon as I disable the filter the detection returns.
Tested with chromium.

**Comment by garry-ut99** [comment]
> mapx-:  `chromeactions.com##+js(acs, Math.random)`

Working always in Chrome, not working in Firefox at all 
(disabled temporary  `chromeactions.com##.adsbygoogle:upward(div)` while testing)

> ghajini : is it just warning, no real function of website is obscured

If that would be true then in this case: `chromeactions.com##.adsbygoogle:upward(div)` is sufficient and no need `+js`.

**Comment by okiehsch** [comment]
> `chromeactions.com##+js(acs, Math.random)`

Working always in Chrome, not working in Firefox at all.
So my filter does not work with Chrome for you?

> I noticed uBO console showing no `setTimeout`` on the site.

![image](https://user-images.githubusercontent.com/16838044/215877189-ef124e4c-a170-454e-88b9-21773009f7e6.png)

**Comment by garry-ut99** [comment]
> okiehsch : So my filter does not work with Chrome for you?

I don't use Chrome at all, and as for Opera and Firefox, it's like I already said in my previous comment:

> garry-ut99 : https://github.com/uBlockOrigin/uAssets/issues/16588#issuecomment-1410955034 : it does work randomly like 5 out of 10 times, both on Firefox and Opera, and when I was checking at the time it wasn't working I noticed uBO console showing no setTimeout on the site.

**Comment by JobcenterTycoon** [comment]
```
||www.chromeactions.com/js/*.js$script,1p
chromeactions.com##.adsbygoogle:upward(1)
```
would be the easiest solution. I clicked through the site and always only see the anti adblock script coming from this path

**Comment by mapx-** [comment]
@okiehsch your filter is working fine on my end (chrome)

For FF we have html filtering (removing what I did in chrome with `acs`)

**Comment by okiehsch** [comment]
Ok, I can't test with Firefox atm, change my fix as you see fit.

**Comment by garry-ut99** [comment]
> For FF we have html filtering (removing what I did in chrome with `acs` : https://github.com/uBlockOrigin/uAssets/commit/2048be64ad9c3134c621f92c195016bd59d5a87b :
> `chromeactions.com##^script:has-text(Math.random)`

This script works but also has broken many "PAGE UP" and "HOME" buttons on the site, but I think we can still live with it as such buttons are not so much important:
 - `https://www.chromeactions.com/news.html` : "Home" button (top right)  + "READ ALL OVER" (aka Page Up) 
- `https://www.chromeactions.com/100-top-music-videos.html` : "BACK TO TOP" (the bottom) not working
- `https://www.chromeactions.com/download-for-firefox.html` : "PAGE UP" (the bottom)
`https://www.chromeactions.com/features.html` :  "PAGE UP" (the bottom)
- `https://www.chromeactions.com/contribute.html` : "PAGE UP" (the bottom)
- `https://www.chromeactions.com/support.html` : "SUPPORT"  (the bottom)  (a fake support button, as it's Page Up)

But not sure about these, as they seem to be more important, and are broken as well:
- `https://www.chromeactions.com/support.html` : "EMAIL" (the bottom), the whole form is broken and selectors broken, also it should open another email form: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/215905034-1e64da12-8e8d-4800-8173-5c8d9bdd7b2d.png) but is broken as well
- `https://www.chromeactions.com/contribute.html` : "CONTRIBUTE" should redirect to PayPal donation: [SCREENSH](https://user-images.githubusercontent.com/72945564/215906328-bc54b138-71f3-44b6-a91f-e1bad38d4ddc.png)

Additionaly, some of the ad placeholders still not hidden on many subpages, example:
`https://www.chromeactions.com/download-for-opera.html` 
`https://www.chromeactions.com/screenshots.html`
`https://www.chromeactions.com/themes.html`: 
 [SCREENSHOOT (1)](https://user-images.githubusercontent.com/72945564/215907397-378cdfab-ab51-4974-8cf6-e47e5bdba289.png) + [SCREENSHOOT (2)](https://user-images.githubusercontent.com/72945564/215907398-79cac1a3-a58c-43c8-9237-b9c2b755d3c2.png)
I've tried: `chromeactions.com##body > div:has(div > .adsbygoogle)` and `chromeactions.com##.adsbygoogle:upward(2)`
both of them work but they break the main page so must think something better

In the end it's up to you whether you decide to fix or just leave it as it is now, however it would be good to at least fix the remaining ad placehoders (if possible).

**Comment by mapx-** [comment]
Nothing works, nostif filter neither

**Comment by ghajini** [comment]
why not just
`||chromeactions.com/i/er*$image,1p`

**Comment by mapx-** [comment]
still clickable PH (to "how to whitelist ...")

**Comment by mapx-** [comment]
If someone has better ideas ;)

**Comment by okiehsch** [comment]
It's just an annoyance your fix is good enough.

**Comment by garry-ut99** [comment]
The same anti-adblock on another family sites: 
- `mixesoft.com` : adding domain to already existing filters does work
- `mycinema.pro` 
   - `mycinema.pro/options.html` (subpage) : [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/216067908-22af0b19-4c2b-4c1d-b73a-d436eb29b555.png) , adding domain to already existing filters does work
   - `mycinema.pro` (mainpage) : [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/216076523-35236160-f535-44f5-86d4-336c86a97885.png) adding domain to already existing filters does not work, needs additional fix
   - `mycinema.pro` related issues:
   (uBO) https://github.com/uBlockOrigin/uAssets/issues/13001) 
  (AG) https://github.com/AdguardTeam/AdguardFilters/issues?q=is%3Aissue+mycinema.pro

**Comment by garry-ut99** [comment]
> with remaining ad placeholders

A task for a specialist in difficult ad placeholder cases: @JobcenterTycoon
