### ISSUE TITLE
messages.google.com: breakage

### ISSUE THREAD

**Issue by JoJawesome2** [uBlockOrigin/uAssets#16589]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [ ] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description

Upon messages.google.com/web/authentication pair with phone attempt, pair succeeds but page doesn't reload as should. Page freezes, hangs browser unless uBlock disabled.

### URL(s) where the issue occurs.

`messages.google.com/web/authentication`

### uBO version

1.46.0

### Browser name and version

Chromium Edge 109.0.1518.70

### Settings

None?

**Comment by mapx-** [comment]
Provide all the steps to reproduce the issue.

**Comment by mapx-** [comment]
- ok, tested in edge, no issue here
- reset uBO to default settings / lists, disable any other blocking extension
