### ISSUE TITLE
eleconomista.es: breakage

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#16587]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.eleconomista.es/actualidad/noticias/11857055/07/22/Este-es-el-mayor-moroso-de-Espana-debe-15-millones-cobra-una-sola-pension-y-tiene-un-documental.html`

### Category

breakage

### Description

Cannot scroll (no scroll bar), site appears darkened.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![23fdd440-d1a1-478b-8294-ee7f9ae32232](https://user-images.githubusercontent.com/43375046/215853766-6905908c-fb99-4acb-af1e-f51c60c2563f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 85840
  cosmetic: 43783
  scriptlet: 17165
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61250-46, 2d.4h.11m
    easyprivacy: 30904-1172, 2d.4h.10m
    plowe-0: 3665-898, 2d.4h.9m
    spa-0: 3469-10, 23h.19m
    spa-1: 5021-187, 2d.3h.59m
    ublock-abuse: 77-0, 2d.4h.7m
    ublock-badware: 4196-119, 2d.4h.5m
    ublock-filters: 31718-180, 2d.4h.4m
    ublock-privacy: 260-1, 2d.4h.3m
    ublock-quick-fixes: 519-20, 23h.22m
    ublock-unbreak: 1868-48, 2d.4h.1m
    urlhaus-1: 6694-0, 23h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 536 ms (selfie)
  maxAssetCacheWait: 94 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    amazon-adsystem.com: 1
    citiservi.es: 3
    doubleclick.net: 1
    facebook.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    hotjar.com: 1
    newsroom.bi: 2
    richaudience.com: 1
    scorecardresearch.com: 1
    sensic.net: 1
```
</details>

**Comment by mapx-** [comment]
add

```
eleconomista.es#@#[class*="banner"]
eleconomista.es#@##banners-superiores
```

filters from 2 lists
```
spa, por: AdGuard Spanish/Portuguese
spa: EasyList Spanish
```

@Yuki2718

**Comment by mapx-** [comment]
@khrin for `spa: EasyList Spanish`

**Comment by Khrin** [comment]
@mapx- Are you sure that's problem here? Looks like instead the cookie banner has been hidden without removing the grey background.

**Comment by mapx-** [comment]
cleared cookies, refresh, I disabled AG filter, the scrolling still broken, after disabling the second one I get a normal behaviour

**Comment by Khrin** [comment]
The cookie banner is called `didomi-notice-banner`, that's why is blocked by the first filter, which is only in the Adguard list.

**Comment by mapx-** [comment]
Sure.
I disabled AG list, cleared the cookies, refreshed the page => accept the cookies => scrolling broken.
On the next refresh the page is working ok.

**Comment by mapx-** [comment]
I'm wrong, it's not about cosmetic filters, it's about EP, I'm testing ..

**Comment by mapx-** [comment]
Nevermind. Even disabling uBO  I get the scrolling broken. Needing another refresh, so spa: EasyList Spanish it's ok.

**Comment by mapx-** [comment]
AG filter needing correction + site issue.

**Comment by Yuki2718** [comment]
What's the matter? I see no trouble, accept the cookie dialogue and everything works fine.

**Comment by krystian3w** [comment]
```css
[class="didomi-regular-notice didomi-banner-notice-info-type didomi-notice-banner shape-banner bottom didomi-regular-notice-with-data-processing"]
```

cover: `##[class*="banner"]` so `#didomi-notice` are hidden.
