### ISSUE TITLE
discogs.com: breakage

### ISSUE THREAD

**Issue by goodstuff626** [uBlockOrigin/uAssets#16586]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.discogs.com/release/2222546-John-Lennon-Walls-And-Bridges`
https://www.discogs.com/release/ (any release page)

### Category

breakage

### Description

Using default ubo settings, no custom filters, discogs.com releases pages will hide the top right "Edit release, All versions of this release, Data Correct" area that should be visible. When I disable ubo, the text show up again like it should. So for now I have to disable ubo when using the discogs.com website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 138170
  cosmetic: 216632
  scriptlet: 37601
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 63284-96, 11m
    adguard-generic: 68165-534, 11m
    adguard-social: 19810-835, 11m
    adguard-spyware-url: 897-2, 11m
    block-lan: 44-0, 11m
    curben-phishing: 24087-0, 11m
    curben-pup: 188-0, 11m
    fanboy-annoyance: 85304-6422, 11m
    fanboy-cookiemonster: 45345-45345, 10m
    fanboy-social: 23238-23238, 10m
    fanboy-thirdparty_social: 69-21, 10m
    ublock-annoyances: 4787-243, 10m
  default: 
    user-filters: 31-0, never
    easylist: 61371-842, 11m
    easyprivacy: 30909-1368, 11m
    plowe-0: 3668-913, 10m
    ublock-abuse: 77-0, 10m
    ublock-badware: 4216-310, 10m
    ublock-filters: 32251-3906, 10m
    ublock-privacy: 259-10, 10m
    ublock-quick-fixes: 519-163, 10m
    ublock-unbreak: 1869-95, 10m
    urlhaus-1: 6697-3, 10m
filterset (user): [array of 31 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 663 ms (selfie)
  maxAssetCacheWait: 705 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
> Using default ubo settings

Your configuration is not a default setup, far from it.
The breakage is caused by a filter in ` adguard-social`.
`discogs.com#@##page > div[class^="content_"] > div[style="order:3"]`
fixes the issue.

@Yuki2718

**Comment by stephenhawk8054** [comment]
The lists that are enabled by default when you install uBO are the default ones (1st image in https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists)

```yaml
  default: 
    user-filters: 31-0, never
    easylist: 61371-842, 11m
    easyprivacy: 30909-1368, 11m
    plowe-0: 3668-913, 10m
    ublock-abuse: 77-0, 10m
    ublock-badware: 4216-310, 10m
    ublock-filters: 32251-3906, 10m
    ublock-privacy: 259-10, 10m
    ublock-quick-fixes: 519-163, 10m
    ublock-unbreak: 1869-95, 10m
    urlhaus-1: 6697-3, 10m
```

any change at the filter lists pane is not default.
