### ISSUE TITLE
autosport.com: detection

### ISSUE THREAD

**Issue by osbornphil** [uBlockOrigin/uAssets#16581]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.autosport.com/f1/news/haas-reveals-f1-car-livery-for-2023-season/10426517/`

### Category

detection

### Description

All articles now seem to be detecting ad blockers, its only just started doing this

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/2124635/215786352-fd2fa6f5-94f5-4a93-8132-47eafed8b07e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83271
  cosmetic: 38430
  scriptlet: 16902
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 41-6, never
    easylist: 61294-46, 15h.41m
    easyprivacy: 30882-1172, 5d.2h.37m
    plowe-0: 3668-898, 23h.18m
    ublock-abuse: 77-0, 1d.2h.55m
    ublock-badware: 4206-119, 21h.5m
    ublock-filters: 31884-141, 21h.7m
    ublock-privacy: 260-1, 1d.2h.54m
    ublock-quick-fixes: 510-137, 6h.16m
    ublock-unbreak: 1869-47, 21h.6m
    urlhaus-1: 6650-1, 6h.15m
filterset (user): [array of 41 redacted]
trustedset: 
  added: [array of 32 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 715 ms (selfie)
  maxAssetCacheWait: 447 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    autosport.com: 2
    adgrid.io: 1
    aniview.com: 2
    bounceexchange.com: 1
    btloader.com: 1
    cxense.com: 1
    doubleclick.net: 3
    motorsport.com: 2
    ntv.io: 1
    outbrain.com: 1
    pubmatic.com: 1
    snackly.co: 1
    tldw.me: 2
    youtube.com: 1
```
</details>

**Comment by erik9012** [comment]
this has been fixed like yesterday or something. Refresh filterlists in ublock settings by  clearing cache and updating 
![image](https://user-images.githubusercontent.com/57501353/215836997-fc236a8f-ea92-4ae0-9b0e-2e4a3aab099a.png)

**Comment by Marko-98** [comment]
Cookie notice

URL: https://www.autosport.com/

<details>
<summary>Screenshot(s)</summary>




<img width="2557" height="1381" alt="Image" src="https://github.com/user-attachments/assets/284a1533-03f6-464e-98ec-b751810d59e3" />



</details>

<details>

```yaml
uBlock Origin: 1.71.0
Firefox: 151
filterset (summary):
 network: 189983
 cosmetic: 166326
 scriptlet: 65646
 html: 3812
listset (total-discarded, last-updated):
 added:
  adguard-generic: 96266-5809, now
  adguard-spyware-url: 2529-134, now
  block-lan: 91-0, now
  fanboy-cookiemonster: 46581-100, now
  ublock-cookies-easylist: 5679-46, now
  fanboy-social: 17694-16, now
  easylist-annoyances: 5214-64, now
  fanboy-ai-suggestions: 251-0, now
  easylist-newsletters: 9327-37, now
  easylist-notifications: 2508-177, now
  ublock-annoyances: 4932-103, now
  HRV-0: 526-110, now
 default:
  user-filters: 2-0, never
  ublock-filters: 52510-70, now
  ublock-badware: 10355-28, now
  ublock-privacy: 4029-2, now
  ublock-unbreak: 2830-1, now
  ublock-quick-fixes: 441-14, now
  easylist: 87730-1223, now
  easyprivacy: 55828-122, now
  urlhaus-1: 26325-11, now
  plowe-0: 3508-1039, now
filterset (user): [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 210 ms (selfie)
 maxAssetCacheWait: 140 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  autosport.com: 2
  doubleclick.net: 1
  privacy-mgmt.com: 1
  relevant-digital.com: 1
 extended:
  ##.ms-ap-native
  ##.ms-apb
  ##a[href^="https://google.com/preferences/source?q="]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/cws/share?"]
  ##a[href^="https://www.pinterest.com/pin/create/button/"]
  ##+js(trusted-replace-argument, document.querySelector, 0, noopF…
  ##+js(noeval-if, interactionCount)
  ##+js(remove-node-text, script, .cmd.unshift, excludes, ',\"')
  ##+js(noeval-if, /chp_?ad/)
```
</details>
