### ISSUE TITLE
ww4.gogoanime2.org: detection

### ISSUE THREAD

**Issue by iakeehc** [uBlockOrigin/uAssets#16597]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ww4.gogoanime2.org/watch/mobile-suit-gundam-the-witch-from-mercury/1`

### Category

detection

### Description

it does not allow me to go fullscreen with it enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83212
  cosmetic: 38361
  scriptlet: 16907
  html: 877
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32705-286, 23h.18m
    ublock-badware: 4220-5, 23h.17m
    ublock-privacy: 306-0, 23h.20m
    ublock-abuse: 77-0, 23h.19m
    ublock-unbreak: 1880-2, 23h.16m
    ublock-quick-fixes: 533-0, 23h.15m
    easylist: 61134-537, 4d.21h.57m
    easyprivacy: 30884-1740, 4d.21h.56m
    urlhaus-1: 6697-1, 23h.14m
    plowe-0: 3667-2, 10d.9h.42m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 600 ms (selfie)
  maxAssetCacheWait: 236 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    gogoanime2.org: 2
    amung.us: 1
    anicli.click: 2
    d1ev866ubw90c6.cloudfront.net: 2
    oomsoapt.net: 6
    outoctillerytor.com: 1
    thaudray.com: 2
```
</details>

**Comment by mapx-** [comment]
Disable uBO and try it on your side => does not work for me.

**Comment by mapx-** [comment]
workaround too watch fullscreen:

- open uBO logger
- select only the `frame` requests
- copy and go with that address

`https://playgo1.cc/streaming.php?id=MTkzMTg3&title=Mobile+Suit+Gundam%3A+The+Witch+from+Mercury+Episode+1`

![image](https://user-images.githubusercontent.com/10303732/216058522-a3d23614-3d5e-4e61-a0dc-e4ad8aef1561.png)

**Comment by garry-ut99** [comment]
> - copy and go with that address (red arrow)

Or faster, click native dedicated arrow in uBO Logger for opening requests in a new tab:

<img src="https://user-images.githubusercontent.com/72945564/216089967-6c2b1674-bb5c-4056-aadc-e9951446c9a8.png" width="70%" />
