### ISSUE TITLE
gasteizhoy.com: ads

### ISSUE THREAD

**Issue by abbio68** [uBlockOrigin/uAssets#16590]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gasteizhoy.com/`

### Category

ads

### Description

Ads in this website are custom made so it appears that uBlock is not blocking any ad at all.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 85635
  cosmetic: 43973
  scriptlet: 17173
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    easylist: 61282-46, 5d.2h.34m
    easyprivacy: 30879-1172, 5d.2h.35m
    plowe-0: 3667-898, 7d.3h.16m
    spa-0: 3470-10, 18h.13m
    spa-1: 5020-187, 2d.22h.49m
    ublock-abuse: 77-0, 7d.23h.54m
    ublock-badware: 4191-119, 2d.22h.52m
    ublock-filters: 31745-175, 2d.22h.51m
    ublock-privacy: 258-1, 7d.9h.44m
    ublock-quick-fixes: 519-20, 18h.12m
    ublock-unbreak: 1868-48, 2d.22h.50m
    urlhaus-1: 6650-0, 18h.14m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 26 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3321 ms (selfie)
  maxAssetCacheWait: 141 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    gasteizhoy.com: 1
    ampproject.org: 2
    doubleclick.net: 1
    googletagmanager.com: 3
    hotjar.com: 1
    quantserve.com: 2
    videoo.tv: 1
```
</details>

**Comment by mapx-** [comment]
add

```
gasteizhoy.com##.bannerclick
gasteizhoy.com##.macrobannerblock
```

@khrin
