### ISSUE TITLE
app.homebinder.com: breakage

### ISSUE THREAD

**Issue by joshsleeper** [uBlockOrigin/uAssets#16598]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.homebinder.com/`

### Category

breakage

### Description

When clicking "Login" after entering correct credentials I would, unsurprisingly, expect the login to succeed and navigate me to the logged-in dashboard page or similar.

While the network request for an auth token seems to succeed without issue, the web page fails to actually move past the login form without any obvious errors other than a mention of `Error: $window.Sentry is undefined` in the console log.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83427
  cosmetic: 38493
  scriptlet: 17054
  html: 882
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33040-185, 1d.21h.49m
    ublock-badware: 4220-5, 1d.21h.49m
    ublock-privacy: 307-0, 1d.21h.49m
    ublock-abuse: 77-0, 1d.21h.49m
    ublock-unbreak: 1880-3, 1d.21h.49m
    ublock-quick-fixes: 533-0, 21h.48m
    easylist: 61289-651, 1d.21h.49m
    easyprivacy: 30907-1740, 1d.21h.49m
    urlhaus-1: 6697-1, 21h.47m
    plowe-0: 3668-2, 1d.21h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 908 ms (selfie)
  maxAssetCacheWait: 154 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    facebook.net: 1
    google-analytics.com: 1
    hs-analytics.net: 1
    hs-banner.com: 1
    hsadspixel.net: 1
    hsleadflows.net: 1
    newrelic.com: 1
    sentry-cdn.com: 1
    stripe.com: 1
```
</details>

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

or tell us if you are willing to provide your account credentials for an accurate test

**Comment by mapx-** [comment]
Test 1 by 1 these filters (if does not work test using both of them) and report back:

```
@@||js-agent.newrelic.com/nr-$script,domain=app.homebinder.com
@@||js.sentry-cdn.com^$script,domain=app.homebinder.com
```

**Comment by joshsleeper** [comment]
sorry for the delayed response, I got caught up with other junk yesterday

this filter didn't seem to have any impact:
```
@@||js-agent.newrelic.com/nr-$script,domain=app.homebinder.com
```

but this filter immediately allowed login to work normally!
```
@@||js.sentry-cdn.com^$script,domain=app.homebinder.com
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by joshsleeper** [comment]
thanks a bunch for the quick turnaround @mapx-, it's greatly appreciated!
