### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by Doculean** [uBlockOrigin/uAssets#16599]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243`

### Category

detection

### Description

When trying to open or play videos, the video loads indefinitely using beta server. I get the standard error 224003 error on FE. SB loads then stops after 10 seconds. HX Loads and will randomly play, but the quality is degraded and frame rate is quite low and choppy. All of which play fine with the adblocker completely disabled.

Here is a log output with the +js detection doing its thing.

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | ##+js(abort-current-script, $, adbWarn) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(no-setTimeout-if, adbWarnContainer) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(addEventListener-defuser, /^(?:click\|mousedown)$/, tabunder) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(set-constant, check_adblock, true) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(abort-on-property-write, Fingerprint2) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(abort-on-property-read, AaDetector) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(window.open-defuser) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(set-constant, alb, false) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(abort-current-script, $, adbWarn) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(no-setTimeout-if, adbWarnContainer) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(addEventListener-defuser, /^(?:click\|mousedown)$/, tabunder) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(set-constant, check_adblock, true) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(abort-on-property-write, Fingerprint2) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(abort-on-property-read, AaDetector) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(window.open-defuser) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +2 | ##+js(set-constant, alb, false) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +1 | ##.share__button-container |  | disqus.com |  | dom | `https://disqus.com/embed/comments/?base=default&f=kimcartoon&t_i=e107243&t_u=https%3A%2F%2Fkimcartoon.li%2FCartoon%2FStar-Wars-The-Bad-Batch-Season-2%2FEpisode-6%3Fid%3D107243&t_d=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&t_t=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&s_o=default#version=b133d00378c8c890852ec65469c697c4` |
| +1 | ##.share__button |  | disqus.com |  | dom | `https://disqus.com/embed/comments/?base=default&f=kimcartoon&t_i=e107243&t_u=https%3A%2F%2Fkimcartoon.li%2FCartoon%2FStar-Wars-The-Bad-Batch-Season-2%2FEpisode-6%3Fid%3D107243&t_d=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&t_t=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&s_o=default#version=b133d00378c8c890852ec65469c697c4` |
| +1 | ##.share-icons-wrapper |  | disqus.com |  | dom | `https://disqus.com/embed/comments/?base=default&f=kimcartoon&t_i=e107243&t_u=https%3A%2F%2Fkimcartoon.li%2FCartoon%2FStar-Wars-The-Bad-Batch-Season-2%2FEpisode-6%3Fid%3D107243&t_d=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&t_t=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&s_o=default#version=b133d00378c8c890852ec65469c697c4` |
| +1 | ##.comment__share |  | disqus.com |  | dom | `https://disqus.com/embed/comments/?base=default&f=kimcartoon&t_i=e107243&t_u=https%3A%2F%2Fkimcartoon.li%2FCartoon%2FStar-Wars-The-Bad-Batch-Season-2%2FEpisode-6%3Fid%3D107243&t_d=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&t_t=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&s_o=default#version=b133d00378c8c890852ec65469c697c4` |
| +1 | ##.comment-share__buttons |  | disqus.com |  | dom | `https://disqus.com/embed/comments/?base=default&f=kimcartoon&t_i=e107243&t_u=https%3A%2F%2Fkimcartoon.li%2FCartoon%2FStar-Wars-The-Bad-Batch-Season-2%2FEpisode-6%3Fid%3D107243&t_d=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&t_t=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&s_o=default#version=b133d00378c8c890852ec65469c697c4` |
| +1 | ###thread-share-bar |  | disqus.com |  | dom | `https://disqus.com/embed/comments/?base=default&f=kimcartoon&t_i=e107243&t_u=https%3A%2F%2Fkimcartoon.li%2FCartoon%2FStar-Wars-The-Bad-Batch-Season-2%2FEpisode-6%3Fid%3D107243&t_d=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&t_t=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&s_o=default#version=b133d00378c8c890852ec65469c697c4` |
| +1 | ###placement-top |  | disqus.com |  | dom | `https://disqus.com/embed/comments/?base=default&f=kimcartoon&t_i=e107243&t_u=https%3A%2F%2Fkimcartoon.li%2FCartoon%2FStar-Wars-The-Bad-Batch-Season-2%2FEpisode-6%3Fid%3D107243&t_d=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&t_t=Watch%20Star%20Wars%3A%20The%20Bad%20Batch%20Season%202%20Episode%206%20online%20FREE%20%7C%20KimCartoon&s_o=default#version=b133d00378c8c890852ec65469c697c4` |
| +1 | ##iframe[width="300"][height="250"] |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +1 | ##.twitter-follow-button |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +1 | ##.st_twitter_hcount |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +1 | ##.st_facebook_hcount |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +1 | ##.kcAds1 |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +1 | ##.adbWarnContainer |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +1 | ###videoAd |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +1 | ###adbWarnContainer |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +0 | ##+js(abort-current-script, $, adbWarn) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +0 | ##+js(no-setTimeout-if, adbWarnContainer) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +0 | ##+js(addEventListener-defuser, /^(?:click\|mousedown)$/, tabunder) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +0 | ##+js(set-constant, check_adblock, true) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +0 | ##+js(abort-on-property-write, Fingerprint2) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +0 | ##+js(abort-on-property-read, AaDetector) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +0 | ##+js(window.open-defuser) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
| +0 | ##+js(set-constant, alb, false) |  | kimcartoon.li |  | dom | `https://kimcartoon.li/Cartoon/Star-Wars-The-Bad-Batch-Season-2/Episode-6?id=107243&s=beta&pfail=1` |
</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 116414
  cosmetic: 215653
  scriptlet: 51096
  html: 937
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24267-15, 42m
    adguard-generic: 68215-5473, 1h.4m
    adguard-annoyance: 63328-1478, 1h.4m
    adguard-social: 19818-35, 1h.4m
    fanboy-annoyance: 85009-6447, 1h.4m
  default: 
    user-filters: 3-0, never
    ublock-filters: 33079-2866, 1h.4m
    ublock-badware: 4220-5, 1h.4m
    ublock-privacy: 306-0, 1h.4m
    ublock-abuse: 77-0, 1h.4m
    ublock-unbreak: 1881-3, 1h.4m
    ublock-quick-fixes: 544-0, 1h.4m
    easylist: 60910-637, 1h.4m
    easyprivacy: 30917-1762, 1h.4m
    urlhaus-1: 6911-1, 1h.4m
    plowe-0: 3670-2, 1h.4m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 715 ms
  maxAssetCacheWait: 567 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    kimcartoon.li: 3
    amung.us: 2
    disqus.com: 4
    eehuzaih.com: 1
    enactsbasiate.com: 1
    facebook.com: 2
    genieessp.com: 1
    googletagmanager.com: 3
    jwpcdn.com: 1
    jwpsrv.com: 1
    privacymanager.io: 1
    propellerads.com: 1
    pubmatic.com: 1
    rndskittytor.com: 1
    sblongvu.com: 1
    sharethis.com: 2
    viglink.com: 2
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
reset uBO to default settings / lists, disable other blocking addons, do not add other lists

**Comment by mapx-** [comment]
This is a weird issue, opening on February 1st! probably lost in GH space and only now came back to life
