### ISSUE TITLE
Google invalid search result

### ISSUE THREAD

**Issue by piquark6046** [uBlockOrigin/uAssets#16596]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

In Google search result with a Korean language query, there are some spam websites that its domain is changed frequently.

It seems that importing the following rules into uBO badware risks filters list is best idea.

```adblock
/^https:\/\/[A-z0-9\.]*[A-z0-9]+\.[A-z]+\/\?u=[A-z0-9]{7}&o=[A-z0-9]{7}/$document
/^https:\/\/[A-z]+\.[A-z]+\.[A-z]+\/[A-z]+-robot\/\?pl=[A-z0-9-]{22}&sm=[A-z]+-robot&hash=[A-z0-9-]{22}&exp=[0-9]{10}/$document
/^https:\/\/[0-9]{9}\.[A-z0-9-]+\.[A-z]{2}\/[0-9]{6}\.html$/$document
```

### URL(s) where the issue occurs.

`https://www.google.com/search?q=%EC%9C%A0%EB%B8%94%EB%A1%9D&tbs=qdr:d&start=70`

### Screenshot(s)

![Screenshot](https://user-images.githubusercontent.com/98787049/216040821-1cb5412d-26a2-4f5e-9850-e79854328e49.png)

### uBO version

1.46.0

### Browser name and version

Mozilla Firefox Developer Edition 110.0b8

### Settings

```
uBlock Origin: 1.46.0
Firefox: 110
filterset (summary): 
  network: 84748
  cosmetic: 41401
  scriptlet: 17165
  html: 884
listset (total-discarded, last-updated): 
  added: 
    KOR-1: 4143-53, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33069-187, now
    ublock-badware: 4220-5, now
    ublock-privacy: 306-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1881-3, now
    ublock-quick-fixes: 536-0, now
    easylist: 61413-680, now
    easyprivacy: 30914-1749, now
    urlhaus-1: 6824-1, now
    plowe-0: 3668-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 383 ms
  maxAssetCacheWait: 133 ms
```

### Notes

Related issues:
 - https://github.com/List-KR/List-KR/issues/598
 - https://github.com/AdguardTeam/AdguardFilters/issues/139667
 - https://github.com/AdguardTeam/AdguardFilters/issues/141681

**Comment by mapx-** [comment]
@ryanbr maybe for EL ?

**Comment by mapx-** [comment]
If those sites are Korean-specific ones maybe should be added in the regional list

**Comment by mapx-** [comment]
https://github.com/List-KR/List-KR/blob/master/filters-share/general_url.txt#L1

**Comment by piquark6046** [comment]
> Weren't they covered by the existing rule(s)? 

Just moving from List-KR filters list to uAssets badware filters list and AdGuard Browsing Security module as @green1052 said.

> Please provide actual URLs of the scam sites, Google search results varies by various factor.

<details>
<summary>URLs</summary>
[Google Search result](https://www.google.com/search?q=%EC%95%A0%EB%93%9C%EA%B0%80%EB%93%9C&tbs=qdr:d) (`애드가드`):
```
https://140848027.hami.com.pl/830136.html
https://bizuteriamonika.pl/708650.html
https://757317958.okcommunication.eu/722779.html
https://199324660.psicologiaparamejorvivir.cl/787472.html
https://rossett.cl/568194.html
```
[Google Search result](https://www.google.com/search?q=%EC%8A%B9%EC%9A%B0%EC%95%84%EB%B9%A0&tbs=qdr:d) (`승우아빠`):
```
https://mighcon.avmov.cfd/ufirbgjc/
https://489236544.mdb-consulting.at/%EB%AF%BC%EC%B4%88-%EB%B2%84%EA%B1%B0.html&usg=AOvVaw1Gu1AdFL0A9pZYRaSV4ba
```
</details>

Do you need more data?

**Comment by Yuki2718** [comment]
`https://mighcon.avmov.cfd/ufirbgjc/` => 404
`https://489236544.mdb-consulting.at/%EB%AF%BC%EC%B4%88-%EB%B2%84%EA%B1%B0.html&usg=AOvVaw1Gu1AdFL0A9pZYRaSV4ba` => eventually caught after redirect (same for other links if you click the button), but good to adjust for
```
https://ip23.f9rlf.yachts/?u=na8k605&o=a1tm57q&t=old_ip&cid=4j6vcq32nq9
https://cname.ophe.im/?u=na8k605&o=a1tm57q&t=new_ip&cid=bg5678q37929
https://cname.f8eke.quest/?u=na8k605&o=a1tm57q&t=new_ip&cid=bg5678q37n27
```
i.e. `/^https?:\/\/(?!www)[0-9a-z]*\.?[-0-9a-z]{4,}\.[a-z]{2,6}\/(?:[0-9a-z]{6,8}\/)?\/?\?u=[0-9a-z]{7}&o=[0-9a-z]{7}/$doc,frame,match-case,domain=buzz|com|de|fun|guru|im|info|life|live|mobi|online|pw|quest|shop|site|skin|space|top|us|xyz|yachts`

IMO only those starting from 9 digits can be blocked by regex, others should be individul domain rules. I also wanna limit to these TLDs for additional safety and performance impact:
`/^https:\/\/\d{9}\.[a-z]*\.?[a-z]{3,}\.[a-z]{2}\/\d{6}\.html$/$document,domain=cl|eu|pl`

**Comment by Yuki2718** [comment]
It seems the 9 digit case is indeed Korean specific. I'll remove the added filter as Fixed by regional list.
