### ISSUE TITLE
crunchyroll.com: ads

### ISSUE THREAD

**Issue by Judas87Swiff** [uBlockOrigin/uAssets#16591]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.crunchyroll.com/`

### Category

ads

### Description

Street Fighter Mobile game ad multiple shown with special banners that also have "Crunchroll Games" branding on them.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83280
  cosmetic: 38353
  scriptlet: 16905
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 3-0, never
    easylist: 61201-46, 3d.5h.51m
    easyprivacy: 30886-1172, 3d.5h.52m
    plowe-0: 3669-898, 1d.2h.42m
    ublock-abuse: 77-0, 3d.21h.32m
    ublock-badware: 4216-119, 1d.2h.40m
    ublock-filters: 31756-140, 1d.2h.39m
    ublock-privacy: 260-1, 3d.21h.31m
    ublock-quick-fixes: 519-20, 4h.21m
    ublock-unbreak: 1869-47, 1d.2h.41m
    urlhaus-1: 6697-1, 8h.44m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 55 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1778 ms (selfie)
  maxAssetCacheWait: 484 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    browser-intake-us5-datadoghq.com: 12
    etp-prod.com: 1
    googletagmanager.com: 1
    segment.com: 1
```
</details>

**Comment by mapx-** [comment]
Provide screenshots and eventually specific links (are all episodes .. premium ?! )

**Comment by mapx-** [comment]
It's self-promotion.

add in "my filters"

`crunchyroll.com##[href*="Marketing"]`
