### ISSUE TITLE
facebook.com (round 2)

### ISSUE THREAD

**Issue by trlkly** [uBlockOrigin/uAssets#166]
Replace the bracketed [...] placeholders with your own information.
### URL(s) where the issue occurs

`http://facebook.com`
### Describe the issue

Ads are showing in the right hand sidebar. I have not seen any in the newsfeed itself, as in Issue #98.
### Screenshot(s)

http://i.imgur.com/NWb1Wi7.png
### Versions
- Browser/version: Firefox 49.0.1 (Both 32- and 64-bit)
- uBlock Origin version: 1.9.12
### Settings
- Disabled "Show the number of blocked requests on the icon"
### Notes

I  recently Refreshed Firefox, and reinstalled uBlock Origin. I have also tried the Facebook Unsponsored GreaseMonkey script to no avail.

**Comment by migueldemoura** [comment]
Fixed already, please close it @trlkly.

**Comment by trlkly** [comment]
Yeah. It's been fixed so long I figured it had already been closed.
