### ISSUE TITLE
Facebook Videos

### ISSUE THREAD

**Issue by Billystorm** [uBlockOrigin/uAssets#16600]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.facebook.com/?sk=h_chr`

### Category

VIDEOS

### Description

very sorry to bother you, but i really need to know if there's any way to use this extension to block facebook videos from playing automatically. 
i've gone to the "settings" section of facebook on all the browsers i use and also on different accounts, and when i click the 'videos' section it's totally BLANK - looks like they removed the option to keep videos from auto-playing and it really pisses me off, and i'm sure you know why - i don't want EVERY video auto-playing. 
anyway - if you have any suggestions, i'd LOVE the info. 
THANKS!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/49542088/216180488-2393dff1-4fed-4204-bd73-ad39c53169ca.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83753
  cosmetic: 38524
  scriptlet: 17076
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61395-46, 8m
    easyprivacy: 30914-1172, 7m
    plowe-0: 3673-898, never
    ublock-abuse: 77-0, 5m
    ublock-badware: 4216-119, 5m
    ublock-filters: 32262-156, 5m
    ublock-privacy: 259-1, 5m
    ublock-quick-fixes: 526-137, 5m
    ublock-unbreak: 1870-48, 5m
    urlhaus-1: 6911-1, 5m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  largeMediaSize: 500
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5598 ms
  maxAssetCacheWait: 771 ms
popupPanel: 
  blocked: 2
  no-large-media: true
  no-popups: true
  blockedDetails: 
    facebook.com: 2
```
</details>

**Comment by mapx-** [comment]
yes, the video section settings is empty now, report to FB, I guess they broke it

`https://www.facebook.com/settings?tab=videos`
