### ISSUE TITLE
[nsfw] fx4vip.com: ads

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#16601]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fx4vip.com/what-is-the-definitive-reason-to-trading-in-forex/`

### Category

ads

### Description

You can access it by clicking this link
`https://linkjust.com/fNxmTrovEQCrNK0kKAlGzSe0Or`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![fdku](https://user-images.githubusercontent.com/110184059/216216778-7cf7eb16-28c7-47c3-bfd8-6ee3e08aa171.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 121888
  cosmetic: 154592
  scriptlet: 34287
  html: 888
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 40551-15942, now
    adguard-generic: 68215-5694, now
    adguard-spyware-url: 897-4, now
    adguard-annoyance: 63328-1483, now
    adguard-social: 19818-30, now
  default: 
    user-filters: 63-0, never
    ublock-filters: 33080-213, now
    ublock-badware: 4220-5, now
    ublock-privacy: 306-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1881-4, now
    ublock-quick-fixes: 544-0, now
    easylist: 60941-418, now
    easyprivacy: 30918-1194, now
    TUR-0: 12061-10, now
filterset (user): [array of 67 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 589 ms (selfie)
  maxAssetCacheWait: 784 ms
  unsuspendAfter: 141 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    brid.tv: 3
    demand.supply: 2
    doubleclick.net: 6
    forexrw7.com: 1
    googletagmanager.com: 2
    imasdk.googleapis.com: 1
    surfe.pro: 1
```
</details>

**Comment by ghajini** [comment]
does this work for you?
```
||tags.worldglobalssp.xyz^$3p
||forexrw7.com^$frame,3p
```

**Comment by mapx-** [comment]
or

```
fx4vip.com##div#orquidea-slideup
fx4vip.com###content > center
fx4vip.com##.g-recaptcha, .btn:others()
```

**Comment by mapx-** [comment]
at least using chrome: yes and I get the final destination (video)

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8da65d233926a2ade28fa242a13ae8614dba949f
update filters
