### ISSUE TITLE
divinity.es [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1660]
URL(s) where the issue occurs

`https://www.divinity.es/mamas/Eva-Gonzalez-modelo-pequeno-Cayetano_0_2525250286.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
`https://www.factoriadeficcion.com/`
`https://www.energytv.es/`
`https://www.mtmad.es/`

**Comment by KiLL4FuNK** [comment]
@Alex-302 @okiehsch @diaux

**Comment by Alex-302** [comment]
> https://www.radioset.es/

fixed for AdGuard

**Comment by KiLL4FuNK** [comment]
@mapx-  @Alex-302 Anti-Adblock

**Comment by mapx-** [comment]
@KiLL4FuNK  anti adblock which site ?

**Comment by KiLL4FuNK** [comment]
@mapx-

`https://www.factoriadeficcion.com/
https://www.energytv.es/
https://www.mtmad.es/
https://www.factoriadeficcion.com/
https://www.radioset.es/
https://www.bemad.es/
https://www.eltiempohoy.es/
https://www.divinity.es/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

https://www.mitele.es/programas-tv/supervivientes/1492618836132

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://www.cincomas.com/programas/Salvame-desvela-comprometido-Kiko-Matamoros_0_2619750033.html`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://www.cuatro.com/noticias/sociedad/embarazada-seis-meses-nina-70-anos_0_2566200142.html`
`https://www.telecinco.es/laqueseavecina/test-vecino-personaje-laqueseacevina_0_2479575711.html`

**Comment by ZaphodBeebblebrox** [comment]
I only get cookie consent messages.

**Comment by KiLL4FuNK** [comment]
the page does not show the video

`https://www.cuatro.com/mujeresyhombres/programa-completo_2_2663880103.html`

**Comment by mapx-** [comment]
Where is the video on `telecinco` ? Even disabling uBo I get no video on that page

**Comment by KiLL4FuNK** [comment]
`https://www.telecinco.es/laqueseavecina/temporadas/temporada-06/t06xc08-un-phoskito-un-detective-leon-y-una-quisquilla-a-babor/lola-embarazada_2_1511505104.html`
