### ISSUE TITLE
easyjet.com: breakage

### ISSUE THREAD

**Issue by Massedil** [uBlockOrigin/uAssets#16606]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

After navigating on some pages of `easyjet.com` website, the browser suddenly stop to successfully contact `easyjet.com`.

I have found a closed issue : #11715 and a reddit thread about that problem : https://www.reddit.com/r/uBlockOrigin/comments/rovnm8/is_ublock_origin_messes_booking_pages_on_easyjets/

I can confirm disabling uBlockOrigin and deleting cookies from Firefox website menu solves the problem : I can navigate fully on the website.

### URL(s) where the issue occurs.

`https://www.easyjet.com`

### Screenshot(s)

![easyjet-infinite-loading](https://user-images.githubusercontent.com/20357783/216355543-68799a33-bcab-427c-9c32-1bbc05619f46.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 107
filterset (summary): 
  network: 86871
  cosmetic: 38857
  scriptlet: 16913
  html: 879
listset (total-discarded, last-updated): 
  removed: 
    FRA-0: null
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 16h.7m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 32720-183, 23h.8m
    ublock-badware: 4220-5, 23h.7m
    ublock-privacy: 306-0, 23h.6m
    ublock-abuse: 77-0, 23h.5m
    ublock-unbreak: 1880-3, 23h.4m
    easylist: 64996-598, 23h.10m
    easyprivacy: 30909-1740, 23h.9m
    plowe-0: 3668-2, 23h.2m
    urlhaus-1: 6911-1, 23h
    ublock-quick-fixes: 536-0, 23h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 366 ms (selfie)
  maxAssetCacheWait: 140 ms
```
</details>

**Comment by ghajini** [comment]
site doesn't load even when all addons are disabled on my end

**Comment by Massedil** [comment]
> site doesn't load even when all addons are disabled on my end

I also experienced it. Like if your IP was "banned" on easyjet side. But if you can try with another IP (or wait some time) and with no ublock addon, it will work, if it is the same behavior as me.

**Comment by krystian3w** [comment]
Akami ban?

https://github.com/easylist/easylist/issues/14805

**Comment by ius** [comment]
Indeed, this is the EasyPrivacy filter (see linked issue) causing an Akamai block (confirmed by deleting the `ak_bmsc` fingerprint cookie after being blocked).

@mapx- Not a site issue. Should be reopened.

**Comment by stephenhawk8054** [comment]
Does the filter krystian3w suggested work?

```adb
easyjet.com##+js(cookie-remover, ak_bmsc)
```

**Comment by krystian3w** [comment]
For my on my side doesn't work, but I don't have a text message similar to `ing.nl` - the loading of the page access request has stopped similar to slow bandwidth.

Manually delete itself for few time disable fake slow bandwidth.

**Comment by ius** [comment]
@krystian3w to clarify, the implementation of Akamai Bot Manager on easyjet.com indeed is slightly different compared to ING. It doesn't return a 403, but simply drops the connection if you provide a `ak_bmsc` cookie it deems unacceptable.

Another major website. I'd like to reiterate many others won't be reported as far as coming up with a solution. In this issue there's confusion about disabling uBlock not helping and it being a site issue, and that's _after_ someone went through the effort of reporting it in the first place..

Deleting the cookie works (at least temporarily), but that seems like a website-specific fragile solution.

**Comment by krystian3w** [comment]
But we have to continue to do it manually until someone experienced catches on to what the scriptlet is blocking in both cases.

It is unlikely that Akamai script approvals will be added (they do not fool with noop.js/noop.txt). and the cleaned-up surrogate redirect resource may be too difficult to write.

**Comment by stephenhawk8054** [comment]
Site-specific unbreaking is not uncommon (similar to many sites in unbreak list), especially if it's related to tracking connections. The important thing is whether there's any solution filter to it except allowing the connections or not.
