### ISSUE TITLE
[nsfw] katmoviehd.cat: ads

### ISSUE THREAD

**Issue by adsdestroyer** [uBlockOrigin/uAssets#16602]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://katmoviehd.cat/the-devil-conspiracy-2022-hindi-dubbed/`

### Category

ads

### Description

in this page player showing video ads when play and opens popups also on pause click.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83939
  cosmetic: 38425
  scriptlet: 16913
  html: 878
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32719-181, 1d.8h.1m
    ublock-badware: 4220-5, 1d.8h
    ublock-privacy: 306-0, 16h.25m
    ublock-abuse: 77-0, 16h.24m
    ublock-unbreak: 1880-3, 1d.7h.59m
    ublock-quick-fixes: 536-0, 50m
    easylist: 61393-625, 1d.8h.4m
    easyprivacy: 30909-1759, 1d.8h.2m
    urlhaus-1: 7196-1, 49m
    plowe-0: 3668-2, 16h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 72 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 302 ms (selfie)
  maxAssetCacheWait: 157 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    a-ads.com: 5
    antijamburet.com: 2
    google-analytics.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by ghajini** [comment]
@ryanbr 
```
||aj2550.bid^
katmoviehd.*###sidebar > #custom_html-6
```

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8da65d233926a2ade28fa242a13ae8614dba949f
update filters
