### ISSUE TITLE
cssbattle.dev: nuisance

### ISSUE THREAD

**Issue by Bader-Idris** [uBlockOrigin/uAssets#16609]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cssbattle.dev/play/48`

### Category

nuisance

### Description

When I work on the challenge of this page, I get sounds of ads, that are not appearing!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

`https://cssbattle.dev/play/48`

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83798
  cosmetic: 38376
  scriptlet: 16922
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 61226-46, 4d.22h.15m
    easyprivacy: 30885-1172, 4d.22h.14m
    plowe-0: 3665-898, 4d.22h.13m
    ublock-abuse: 77-0, 4d.22h.11m
    ublock-badware: 4216-119, 14h.32m
    ublock-filters: 31907-140, 14h.31m
    ublock-privacy: 260-1, 4d.22h.7m
    ublock-quick-fixes: 526-137, 10h.29m
    ublock-unbreak: 1870-47, 14h.30m
    urlhaus-1: 7196-1, 10h.28m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 23338 ms (selfie)
  maxAssetCacheWait: 1453 ms
popupPanel: 
  blocked: 98
  blockedDetails: 
    doubleclick.net: 8
    ethicalads.io: 1
    firestore.googleapis.com: 1
    google.com: 8
    googletagmanager.com: 1
    sentry.io: 3
    youtube.com: 76
```
</details>

**Comment by mapx-** [comment]
Are you sure it's not about this notification ?

![image](https://user-images.githubusercontent.com/10303732/216673140-470c0fb2-000a-432d-bff7-98d77c606b3b.png)
