### ISSUE TITLE
shaalaa.com: detection

### ISSUE THREAD

**Issue by surSD1** [uBlockOrigin/uAssets#16607]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.shaalaa.com/question-bank-solutions/simplify-cos-cos-sin-sin-cos-sin-sin-cos-cos-sin-algebra-matrices_169679`

### Category

detection

### Description

Ad block detection 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 230212
  cosmetic: 240436
  scriptlet: 45319
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24220-192, 6h.1m
    ALB-0: 301-10, 6h.1m
    BGR-0: 1091-19, 6h.1m
    CHN-0: 28432-1348, 6h.1m
    CZE-0: 733-40, 6h.1m
    DEU-0: 6168-386, 6h.1m
    EST-0: 451-10, 6h.1m
    FIN-0: 2160-69, 6h.1m
    FRA-0: 30001-3013, 6h.1m
    GRC-0: 994-19, 6h.1m
    HUN-0: 2155-82, 6h.1m
    IDN-0: 5433-245, 6h.1m
    IND-0: 12259-0, 6h.1m
    IRN-0: 2745-74, 6h.1m
    ISL-0: 194-2, 6h.1m
    ISR-0: 1671-7, 6h.1m
    ITA-0: 13376-483, 6h.1m
    JPN-1: 9130-91, 6h.1m
    KOR-1: 4140-98, 6h.1m
    LTU-0: 1190-16, 6h.1m
    [26 lists not shown]: [too many]
  default: 
    user-filters: 6-0, never
    adguard-mobile: 8769-139, 13h.12m
    easylist: 60981-17307, 13h.9m
    easyprivacy: 30913-1786, 13h.8m
    plowe-0: 3670-1050, 11h.57m
    ublock-abuse: 77-3, 11h.53m
    ublock-badware: 4215-171, 11h.51m
    ublock-filters: 32014-3755, 11h.50m
    ublock-privacy: 259-12, 11h.49m
    ublock-quick-fixes: 526-139, 11h.48m
    ublock-unbreak: 1874-71, 11h.47m
    urlhaus-1: 7196-3, 11h.46m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1544 ms (selfie)
  maxAssetCacheWait: 1030 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google-analytics.com: 1
    pubguru.net: 1
```
</details>

**Comment by ghajini** [comment]
@surSD1 
use default settings & use firefox browser on mobile
if not then disable inbuilt blocker on browser
