### ISSUE TITLE
nurparatodos.com.ar: detection

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#16605]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The notice appears just when you enter the page.

Even if I follow the instructions to deactivate it, the blocking still appears.

If I deactivate all the Custom filters and leave the default ones, the blocking also appears.

I have tried disabling all extensions and the block also appears.

### URL(s) where the issue occurs.

`https://nurparatodos.com.ar/`

### Screenshot(s)

http://imgfz.com/i/aT1sg0N.jpeg

### uBO version

uBlock Origin 1.46.0

### Browser name and version

Firefox 109.0.1 (64-Bit)

### Settings

Disable Custom filters.

This is my uBlock setup --> https://imgfz.com/i/nEbvRjo.png

**Comment by krystian3w** [comment]
```adb
nurparatodos.com.ar##+js(noeval-if, adsBlocked)
```

by AdGuard Team?

**Comment by Jose1971AB** [comment]
At the moment it is solved.... The notice to deactivate the blocker no longer appears.

Thank you very much to all of you who have taken an interest... @MasterKia @iSmokeMid69 @Krystian3w and @ghajini 

Greetings to all
