### ISSUE TITLE
[nsfw] daddylivehd.sx: popups

### ISSUE THREAD

**Issue by workingmice2345** [uBlockOrigin/uAssets#16603]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://daddylivehd.sx/stream/stream-371.php`

### Category

popups

### Description

Will click something. Pop up tab appears. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83569
  cosmetic: 38401
  scriptlet: 16901
  html: 876
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32557-56, 3d.4h.38m
    ublock-badware: 4200-5, 3d.4h.37m
    ublock-privacy: 306-0, 3m
    ublock-abuse: 77-0, 2m
    ublock-unbreak: 1879-2, 3d.4h.36m
    ublock-quick-fixes: 536-0, 10h.26m
    easylist: 61354-642, 10h.28m
    easyprivacy: 30879-1740, 5d.14h.51m
    urlhaus-1: 6911-0, 10h.27m
    plowe-0: 3667-2, 12d.5h.6m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1583 ms (selfie)
  maxAssetCacheWait: 724 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    a-ads.com: 3
    adsco.re: 1
    asacdn.com: 2
    becorsolaom.com: 1
    cdnondemand.org: 1
    commissionkings.ag: 1
    coonandeg.xyz: 1
    d11enq2rymy0yl.cloudfront.net: 1
    gaiphaud.xyz: 8
    google-analytics.com: 2
    histats.com: 1
    moksoxos.com: 1
    osaud.com: 1
    rodaimlessale.com: 2
    taboola.com: 1
    wheeledajar.com: 2
    woafoame.net: 1
    xadsmart.com: 1
    youradexchange.com: 1
```
</details>

**Comment by ghajini** [comment]
update filters & report if any ads
