### ISSUE TITLE
fedex.com: breakage

### ISSUE THREAD

**Issue by kkoves** [uBlockOrigin/uAssets#16614]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fedex.com/fedextrack/`

### Category

breakage

### Description

Element near top of page stating, "Service Alert: Operational updates on severe weather." and a link "Learn more" are missing when uBlock is on, but present when it is disabled. Checked DevTools, element `<div class="atrk-wrapper" data-optly-e256bf8f-1263-4d93-81eb-8bebc1ea7284="">` that contains the text and link is missing when uBlock is on. From what I can tell from that element and `blockedDetails` in the Configuration section below, it might be the blockage of optimizely.com causing this? I assume `data-optly-[...]` in the element listed above could be related to optimizely.com, since the names are similar.

Edit: also tested on another computer and browser (issue reported from Vivaldi, tested on Chrome) with nearly no other browser extensions (just Adobe Acrobat extension), and the issue was present there as well and fixed by disabling uBlock for the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

When alert is missing:
![image](https://user-images.githubusercontent.com/3821666/216459204-be8f1796-212b-40c3-86c8-bd4a81ab277c.png)

When alert is present:
![image](https://user-images.githubusercontent.com/3821666/216459264-51ec7b76-d55b-49fa-b5a0-9678d6fa1418.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83471
  cosmetic: 38372
  scriptlet: 16918
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    easylist: 61177-46, 5d.3h.12m
    easyprivacy: 30886-1172, 5d.3h.11m
    plowe-0: 3668-898, 3d.3h
    ublock-abuse: 77-0, 4d.3h.5m
    ublock-badware: 4216-119, 22h.55m
    ublock-filters: 31907-140, 22h.54m
    ublock-privacy: 260-1, 4d.3h.4m
    ublock-quick-fixes: 522-137, 22h.52m
    ublock-unbreak: 1870-47, 22h.53m
    urlhaus-1: 6911-1, 22h.51m
filterset (user): [empty]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 458 ms (selfie)
  maxAssetCacheWait: 409 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    fedex.com: 2
    adobedtm.com: 2
    demdex.net: 2
    googletagmanager.com: 1
    optimizely.com: 1
    qualtrics.com: 1
    techlab-cdn.com: 5
```
</details>

**Comment by mapx-** [comment]
I guess the "Service Alert" is only present on the page when certain conditions happen.

I get no alert even disabling uBO

**Comment by kkoves** [comment]
> I guess the "Service Alert" is only present on the page when certain conditions happen.
> 
> I get no alert even disabling uBO

Probably, I'm in the US so it was notifying me about service impacts due to severe weather in their Memphis and Dallas/Ft. Worth hubs. They also have a notice for "Ukraine, Russia, and Belarus Service Suspension," though, which I assume would be global, but maybe not displayed site-wide since it's an older notice?

**Comment by mapx-** [comment]
I was able to reproduce the issue using a Denver zone ip

@ryanbr
