### ISSUE TITLE
shareus.in: nuisance

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#16610]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ask To Complete Task/Answer Questions

### URL(s) where the issue occurs.

`https://shareus.in/?i=7oYZVW`

### uBO version

*

### Browser name and version

*

### Settings

*

**Comment by stephenhawk8054** [comment]
I don't think we could address this.
