### ISSUE TITLE
nerdiess.com: detection

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#16611]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nerdiess.com/t/javascript-obfuscate`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 100635
  cosmetic: 59340
  scriptlet: 18294
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39280-12, 1m
    easylist: 60989-61, 1m
    easyprivacy: 30913-1282, 1m
    plowe-0: 3670-902, 1m
    ublock-abuse: 77-1, 1m
    ublock-badware: 4205-121, 1m
    ublock-filters: 32264-184, 1m
    ublock-privacy: 259-1, 1m
    ublock-quick-fixes: 527-137, 1m
    ublock-unbreak: 1870-49, 1m
    urlhaus-1: 7145-1, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 476 ms (selfie)
  maxAssetCacheWait: 470 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    duhestyce.com: 1
    googletagmanager.com: 2
    pubfuture.com: 4
```
</details>

**Comment by garry-ut99** [comment]
I can't reproduce either (Firefox & Opera).

> lyubomyrhv:
>  * [x]  I did not answer truthfully to **ALL** the above checkpoints.

**Comment by king-iskan** [comment]
@mapx- 
this issue already close? but still detection in step 2

**Comment by mapx-** [comment]
> detection in step 2

explain what's step 2

**Comment by king-iskan** [comment]
> > detection in step 2
> 
> explain what's step 2

sorry, I just opened my cellphone again.  it turns out that from the start it was detected by adblock
![az_recorder_20230205_131350_edited](https://user-images.githubusercontent.com/120553425/216804873-c2aaacf0-7447-4b89-bff7-40e3ec66a3aa.jpg)
