### ISSUE TITLE
autokult.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#1661]
### URL(s) where the issue occurs

`https://autokult.pl/30916,alpine-a110-pure-i-legende-dwie-wersje-dla-roznych-klientow`

### Describe the issue
Message about cookies isn't blocked despite added rule `##.cookie-disclaimer:not(body):not(html)` on Chromium 64 (this rule even shows up on logger). On Firefox this issue doesn't happen.

### Screenshot(s)
![screenshot_20180304_211412](https://user-images.githubusercontent.com/19818572/36950062-0383d530-1ff1-11e8-93e3-cfd112e8ce86.png)

![screenshot_20180304_211757](https://user-images.githubusercontent.com/19818572/36950116-86cc1f9c-1ff1-11e8-8402-d6c3aa29defa.png)

### Versions

- Browser/version: Chromium 64.0.3282.167 (Build) 64-bit
- uBlock Origin version: 1.15.2

### Settings

```
"selectedFilterLists": [
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt",
    "POL-0",
    "plowe-0",
    "malware-1",
    "malware-0",
    "easyprivacy",
    "easylist",
    "awrl-0",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-badware",
    "ublock-filters",
    "user-filters"
  ],
```

**Comment by okiehsch** [comment]
I can not reproduce 
`##.cookie-disclaimer:not(body):not(html)`
works on my end with Chrome/Chromium 64.

**Comment by krystian3w** [comment]
Try refresh without cache / incognito mode with allow uBlock.

**Comment by hawkeye116477** [comment]
Sometimes happens that this cookie message isn't hidden. Try clear cache and cookies few times and you will reproduce that issue.
I have another problem also, with Fanboy's Social Blocking List enabled, Facebook, Twitter and Pinterest icons should be hidden, but they are visible. On Firefox however everything is fine.
![screenshot_20180305_145829](https://user-images.githubusercontent.com/19818572/36978769-b4cd28b6-2085-11e8-966d-522a4ba04f87.png)

**Comment by KonoromiHimaries** [comment]
to reproduce try clear your cookie/cache + click ctrl+f5

**Comment by gorhill** [comment]
Can you reproduce if you use `autokult.pl##.cookie-disclaimer:not(body):not(html)` instead?

**Comment by KonoromiHimaries** [comment]
@gorhill when i add a this rule `autokult.pl##.cookie-disclaimer:not(body):not(html)`, i still have cookie alert.

![2018-03-05-alpine a110 pure i legende dwie wersje dla roznych klientow](https://user-images.githubusercontent.com/5884000/36979379-9d6050fc-2087-11e8-9a04-541e2929de05.png)

**Comment by gorhill** [comment]
I can't reproduce. Investigate the DOM, see what it says about the `.cookie-disclaimer` DOM node.

**Comment by hawkeye116477** [comment]
@gorhill For me with `autokult.pl##.cookie-disclaimer:not(body):not(html)`, I don't see cookie alert. But why generic filter works on Firefox and not on Chromium?

**Comment by krystian3w** [comment]
Maybe bug `$generichide` implementation?

**Comment by krystian3w** [comment]
Maybe bug with **`@@||autokult.pl^$generichide`**, this "`@@||4free.waw.pl$generichide`" show cookies baner on `4free.waw.pl` or my private website in blink browsers engine.

**Comment by mapx-** [comment]
When there is a `$generichide` filter you have to use `4free.waw.pl###cookies-alert`

**Comment by hawkeye116477** [comment]
> Maybe bug with @@||autokult.pl^$generichide (I can not find in Polish list).
No, I don't have that rule on any filterlists. Also social icons should be hidden with Fanboy's Social, but they are here. I tried even these rules:
```
autokult.pl##a[href^="https://www.facebook.com/sharer.php"]
autokult.pl##a[href^="http://twitter.com/intent/tweet"]
autokult.pl##a[href^="http://pinterest.com/pin/create/link/"]
```
But these rules not work on Chromium, they are still visible when I refresh page, even tried to clear cache and cookies, nothing helps.

@jspenguin2017 Can you look here?

**Comment by Raaviiz** [comment]
I can reproduce both the cookie and the social issues on Chropera 51.0 64bit & uBO  1.15.11.9 & Win 7 SP1 U 64bit:
- as for the cookie issue I can reproduce very rarely like one time per 10-15 hard page reloads, when I've reproduced it, the cookie DOM element `##.cookie-disclaimer` had no `:style(visible: none!impotant;)` attached to it by uBO. I don't know if that is related or not to a fact that there are 2 cookie filters which hide the same element: `##div[class*="cookie"]` and `##.cookie-disclaimer:not(body):not(html)`, maybe they sometimes collide somehow / break at race condition.
- as for the social issue I can reproduce every time, and also have encountered some odd uBO behaviour which doesn't happen on Firefox 58.0.2 64bit:
1. after I click rmb at the social icons panel
2. and choose uBO's "block element" from the context menu
3. then select filter `##.social-links.share-links`
4. click uBO's Preview button
5. the element disappear as expected
6. but after I click the button again
7. the element doesn't appear again, instead the element's highlighted empty container appears
8. after I click Peview again it disappear as expected
9. after I click Preview again nothing appears anymore

I've attached the video below:

![issue_1661_autokult_pl](https://user-images.githubusercontent.com/36993809/37093671-72a89cf4-2210-11e8-9c0c-0f3d222e5cae.gif)

**Comment by jspenguin2017** [comment]
@hawkeye116477 What do you mean? They work fine for me: 
![image](https://user-images.githubusercontent.com/7283682/37095288-ac7bc05c-21d2-11e8-9b9b-63b4cb0e20cb.png)
Facebook, Twitter, and the other thing are hidden as expected. Your rules doesn't match the entire row.

**Comment by jspenguin2017** [comment]
Also, `@@||example.com^$generichide` can be overriden with `||example.com^$generichide,important`.

**Comment by Raavizz** [comment]
I can reproduce both the cookie and the social issues on Chropera 51.0 64bit & uBO  1.15.11.9 & Win 7 SP1 U 64bit:
- as for the cookie issue I can reproduce very rarely like one time per 10-15 hard page reloads, when I've reproduced it, the cookie DOM element `##.cookie-disclaimer` had no `:style(visible: none!impotant;)` attached to it by uBO. I don't know if that is related or not to a fact that there are 2 cookie filters which hide the same element: `##div[class*="cookie"]` and `##.cookie-disclaimer:not(body):not(html)`, maybe they sometimes collide somehow / break at race condition.
- as for the social issue I can reproduce every time, and also have encountered some odd uBO behaviour which doesn't happen on Firefox 58.0.2 64bit:
1. after I click rmb at the social icons panel
2. and choose uBO's "block element" from the context menu
3. then select filter `##.social-links.share-links`
4. click uBO's Preview button
5. the element disappears as expected
6. but after I click the button again
7. the element doesn't appear again, instead the element's highlighted empty container appears
8. after I click Peview again it disappears as expected
9. after I click Preview again nothing appears anymore

I've attached the video below:

![issue_1661_autokult_pl](https://user-images.githubusercontent.com/36993809/37093671-72a89cf4-2210-11e8-9c0c-0f3d222e5cae.gif)
