### ISSUE TITLE
rl.techysuccess.com: breakage

### ISSUE THREAD

**Issue by rehman89** [uBlockOrigin/uAssets#16617]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rl.techysuccess.com/hcleJG`

### Category

breakage

### Description

![Web capture_3-2-2023_114847_rl techysuccess com](https://user-images.githubusercontent.com/78687543/216533241-f6db44fe-c6a4-4a3a-a733-e9532bc7d79a.jpeg)

### Screenshot(s)

`https://drive.google.com/file/d/1Tna7DpzhzOo0kgxGBMmLimr6NcNhMXyF/view?usp=share_link`

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83755
  cosmetic: 38408
  scriptlet: 16912
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 22-0, never
    easylist: 61250-46, 2d.23h.13m
    easyprivacy: 30904-1172, 2d.23h.11m
    plowe-0: 3667-898, 9d.13h.55m
    ublock-abuse: 77-0, 1d.23h.19m
    ublock-badware: 4201-119, 3d.18h.20m
    ublock-filters: 31768-140, 3d.18h.23m
    ublock-privacy: 259-1, 1d.23h.20m
    ublock-quick-fixes: 526-20, 13h.57m
    ublock-unbreak: 1869-46, 3d.18h.21m
    urlhaus-1: 7145-1, 13h.56m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 19 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 17 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11047 ms (selfie)
  maxAssetCacheWait: 816 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
What exactly is broken?

**Comment by krystian3w** [comment]
I think lost <kbd> get link </kbd> button.

**Comment by stephenhawk8054** [comment]
Can you do this?

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
