### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by Pdrewicz** [uBlockOrigin/uAssets#16625]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/3yGU7/Mafia.II.Definitive.Edition-CODEX.part1.rar`

### Category

detection

### Description

Site detects adblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![a](https://user-images.githubusercontent.com/106173218/216719965-f9389677-0c34-4160-88db-701f34d3a86a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 107
filterset (summary): 
  network: 85575
  cosmetic: 45693
  scriptlet: 16994
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7884-8, 7h.17m
    POL-2: 1276-13, 1d.4h.25m
    easylist: 61245-72, 5d.10h.52m
    easyprivacy: 30889-1172, 5d.10h.53m
    plowe-0: 3670-907, 1d.4h.29m
    ublock-abuse: 77-0, 5d.1h.34m
    ublock-badware: 4200-119, 1d.4h.28m
    ublock-filters: 31909-176, 1d.4h.27m
    ublock-privacy: 260-1, 6d.21h.59m
    ublock-unbreak: 1869-45, 1d.4h.26m
    urlhaus-1: 7670-1, 7h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 33 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 355 ms (selfie)
  maxAssetCacheWait: 146 ms
popupPanel: 
  blocked: 11
  no-popups: true
  blockedDetails: 
    megaup.net: 1
    a-ads.com: 1
    altowriestwispy.com: 1
    bidgear.com: 1
    dmmzkfd82wayn.cloudfront.net: 2
    googletagmanager.com: 1
    keydawnawe.com: 1
    parrecleftne.xyz: 1
    s3.amazonaws.com: 1
    theharityhild.buzz: 1
```
</details>

**Comment by krystian3w** [comment]
Works without regional? Because this is not Polish page.

**Comment by yvvki** [comment]
I use a userscript as workaround for the time being:
https://greasyfork.org/en/scripts/422770-megaupskipadbcheck/code

**Comment by krystian3w** [comment]
Userscripts can be removed at all (your post can disappear).

**Comment by krystian3w** [comment]
In Poland works disable specific cosmetic filtering but Logger don't save compatible with shide:

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specifichide
