### ISSUE TITLE
soap2day.ac: popups

### ISSUE THREAD

**Issue by samuraino** [uBlockOrigin/uAssets#16624]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`soap2day.ac` => popups => `https://subscribe-notifications.com/ext/thank-you?clickid=wjhiijhmnim8mbcmi6sn5ldi&d=securedcdn.com&ext_id=916806&user=Love%20Jones&cid=wjhiijhmnim8mbcmi6sn5ldi&sid=57efd96e-3567-49c7-9a0a-8e6148ee7590`

### Category

popups

### Description

Popups from soap2day.ac. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 90559
  cosmetic: 97125
  scriptlet: 19898
  html: 891
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 63447-565, never
    spa-1: 5030-54, never
  default: 
    user-filters: 1-0, never
    ublock-filters: 33110-185, 7m
    ublock-badware: 4220-5, 7m
    ublock-privacy: 310-0, 7m
    ublock-abuse: 77-0, 7m
    ublock-unbreak: 1881-5, 7m
    ublock-quick-fixes: 553-0, 7m
    easylist: 61071-749, 7m
    easyprivacy: 30917-1741, 7m
    urlhaus-1: 7670-1, 7m
    plowe-0: 3667-2, 7m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1796 ms (selfie)
  maxAssetCacheWait: 4095 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    ocmhood.com: 1
```
</details>

**Comment by mapx-** [comment]
I can not reproduce the popups, however try:

`*$script,3p,domain=soap2day.ac,denyallow=fastly.net|jwpcdn.com`

**Comment by samuraino** [comment]
That stopped the popups. Thank you.
