### ISSUE TITLE
onlineonderdelenshop.nl nuisance/annoyance

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#16623]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

this websites is not allowing right click. If you right click it gives some notification about that my ip is logged and that this action is blocked. Is it possible to enable right click again with ublock annnoyance filter?

Easydutch explicitely said it is only doing ads and detection of ads which makes me wonder if  ublock annyoance is doing filters to reenable rightclick

### URL(s) where the issue occurs.

`https://onlineonderdelenshop.nl/blog/storingcode-foutcode-asko-wasautomaat-wasmachine/`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/57501353/216687893-c57eccd0-b058-40d5-999b-32366a4f8b29.png)

### uBO version

1.46.0

### Browser name and version

chrome 109 on windows 10

### Settings

none

**Comment by okiehsch** [comment]
>  which makes me wonder if ublock annyoance is doing filters to reenable rightclick 

We do.
