### ISSUE TITLE
dailymail.co.uk: breakage

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#16632]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dailymail.co.uk/columnists/article-302201/Millions-riding-putt--thats-pressure.html`

### Category

breakage

### Description

![image](https://user-images.githubusercontent.com/91396482/216798262-ebc150b8-f431-4637-b031-f0fde801ab7a.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 74455
  cosmetic: 38588
  scriptlet: 17087
  html: 891
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1374-0, 38m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 6d.1h.59m
  default: 
    ublock-filters: 33088-183, 38m
    ublock-badware: 4235-5, 38m
    ublock-privacy: 310-0, 38m
    ublock-abuse: 77-0, 1h.1m
    ublock-unbreak: 1880-3, 38m
    ublock-quick-fixes: 550-0, 38m
    easylist: 61216-293, 38m
    easyprivacy: 30925-2123, 38m
filterset (user): [array of 551 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 456 ms (selfie)
  maxAssetCacheWait: 278 ms
  unsuspendAfter: 107 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    dailymail.co.uk: 3
    dotmetrics.net: 1
    go-mpulse.net: 2
    googletagmanager.com: 1
    imasdk.googleapis.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
dailymail.co.uk#@#.article-advert
```

@ryanbr

**Comment by Daxy7** [comment]
New breakage at https://www.dailymail.co.uk/home/article-7759273/Privacy-Cookies-Policy-Policy.html caused by `dailymail.co.uk##.module.html_snippet:has-text(Shop)` (Broken @ uBlock Filters)
![image](https://user-images.githubusercontent.com/91396482/219991460-b79fc979-92ce-483b-a04d-feb041740721.png)

**Comment by Daxy7** [comment]
Why is filter `dailymail.co.uk,thisismoney.co.uk#@#.article-advert` missing in EasyList? Breakage is still here.

**Comment by Daxy7** [comment]
Example Image (On homepage you'll find via scrolling down)
![img](https://user-images.githubusercontent.com/91396482/232905078-6710ff94-f1cb-464d-a72f-7a6124400aaf.png)
Tiktok-esque carousel videos are a placeholder with filter (uBlock Filters)
`dailymail.co.uk##+js(acis, document.addEventListener, adverts)`

**Comment by stephenhawk8054** [comment]
Do these work?

```adb
||dailymail.co.uk/static/mol-adverts/$1p,badfilter
||dailymail.co.uk/static/mol-adverts/demo/$1p
```

**Comment by Daxy7** [comment]
[It works. No issues so far](https://user-images.githubusercontent.com/91396482/232956043-9f68fd63-5a44-4f5f-a442-c5731d377c52.png)

**Comment by Daxy7** [comment]
[317fe85](https://github.com/easylist/easylist/commit/317fe853cca116cf93afecf7c5ac944c0d8e34ac)

**Comment by Daxy7** [comment]
new bug, website layout changed perhaps (also connects to 5 instead of 10 more domains and 90 more gets blocked about)

https://github.com/uBlockOrigin/uAssets/assets/91396482/366d233e-9d50-483f-afdc-e53c85f612e1

**Comment by stephenhawk8054** [comment]
The shorts carousel works normally for me? https://github.com/uBlockOrigin/uAssets/assets/66517106/5b958dd3-1f5c-47a9-9373-660d818a3d90

**Comment by Daxy7** [comment]
ye. also 200 requests blocked on average for it to work normally. 
cleared my cookies and site data for daily mail. it was a site issue. now resolved

**Comment by Daxy7** [comment]
Update: Carousel videos are blocked again.
```
https://www.dailymail.co.uk/home/index.html
```
Problematic filter:
```
dailymail.co.uk##+js(abort-current-script, document.addEventListener, adverts)
```

**Comment by stephenhawk8054** [comment]
Can you screenshot it?

**Comment by Daxy7** [comment]
on my side `https://cmp.dmgmediaprivacy.co.uk` is being blocked by `dailymail.co.uk##+js(abort-current-script, document.addEventListener, adverts)`. allowing with `#@#` enables the cookie notice so carousels work.

the placeholder is the same as the previous photo.
this is unseen with `+js` edit on default profile.
https://github.com/uBlockOrigin/uAssets/assets/91396482/a1def417-a795-4539-81c5-63081753542a
