### ISSUE TITLE
[nsfw] lyon.managebac.com: popups

### ISSUE THREAD

**Issue by tom2010y** [uBlockOrigin/uAssets#16639]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lyon.managebac.com/student`

### Category

popups

### Description

it is not working

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

it is not working
![bg1](https://user-images.githubusercontent.com/101730151/216820955-e2b61565-db29-4012-9ab8-4b6ff2f7d698.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83361
  cosmetic: 38413
  scriptlet: 16916
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    easylist: 61166-46, 22h.28m
    easyprivacy: 30917-1173, 22h.27m
    plowe-0: 3668-897, 5d.20h.56m
    ublock-abuse: 77-0, 10d.20h.7m
    ublock-badware: 4216-121, 3d.19h.14m
    ublock-filters: 31906-141, 3d.19h.13m
    ublock-privacy: 259-1, 10d.20h.6m
    ublock-quick-fixes: 519-137, 22h.25m
    ublock-unbreak: 1870-47, 3d.19h.12m
    urlhaus-1: 6822-0, 22h.26m
filterset (user): [array of 3 redacted]
switchRuleset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 15723 ms (selfie)
  maxAssetCacheWait: 884 ms
popupPanel: 
  blocked: 5
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    managebac.com: 4
    airbrake.io: 1
```
</details>

**Comment by mapx-** [comment]
> popups

What type of popups ? Screenshot ?
