### ISSUE TITLE
gls-us.com: breakage

### ISSUE THREAD

**Issue by slickxz** [uBlockOrigin/uAssets#16631]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gls-us.com/track-and-trace`

### Category

breakage

### Description

uBlock blocks the request to the website's parcel tracking API

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![block2](https://user-images.githubusercontent.com/25731011/216786919-44cdb341-cc54-48b5-9300-d7c70e7c3be5.jpg)

![block1](https://user-images.githubusercontent.com/25731011/216786916-39e5a65a-db61-4dea-a5dc-d432e17afc11.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83494
  cosmetic: 38531
  scriptlet: 17087
  html: 891
listset (total-discarded, last-updated): 
  default: 
    user-filters: 8-1, never
    ublock-filters: 33088-185, 3m
    ublock-badware: 4235-5, 3m
    ublock-privacy: 310-0, 3m
    ublock-abuse: 77-0, 3m
    ublock-unbreak: 1879-3, 3m
    easylist: 61198-645, 3m
    easyprivacy: 30923-1741, 3m
    urlhaus-1: 6822-0, 3m
    plowe-0: 3667-2, 3m
    ublock-quick-fixes: 550-0, 3m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2825 ms (selfie)
  maxAssetCacheWait: 1354 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    gls-us.com: 3
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr
