### ISSUE TITLE
urlvoid.com: ads

### ISSUE THREAD

**Issue by Nikolas-Lehto** [uBlockOrigin/uAssets#16635]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.urlvoid.com/scan/ajax.googleapis.com/`

### Category

ads

### Description

in the topnav it has text that says

`"SPONSORED: APIs for Threat Analysis & Detection - Remove Malware from Website - Compress Multimedia Files"`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/86280620/216807197-9c97162b-cbcd-4052-a8ad-6e9e1bb285da.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83446
  cosmetic: 38447
  scriptlet: 16926
  html: 886
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32752-183, 13h.10m
    ublock-badware: 4220-5, 13h.9m
    ublock-privacy: 306-0, 3d.16h.13m
    ublock-abuse: 77-0, 3d.15h.37m
    ublock-unbreak: 1880-2, 13h.8m
    ublock-quick-fixes: 550-0, 5m
    easylist: 61371-642, 4d.14h.45m
    easyprivacy: 30907-1740, 4d.14h.44m
    urlhaus-1: 6721-0, 4m
    plowe-0: 3668-2, 3d.15h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 250 ms (selfie)
  maxAssetCacheWait: 204 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

`urlvoid.com##.search-section:has-text(SPONSORED)`

@ryanbr
