### ISSUE TITLE
traffic1s.com: ads

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#16638]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://traffic1s.com/WIfoDkux`

### Category

ads

### Description

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 100312
  cosmetic: 59348
  scriptlet: 18300
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39286-12, 11h.42m
    easylist: 60989-61, 2d.16h.17m
    easyprivacy: 30913-1282, 2d.16h.17m
    plowe-0: 3670-902, 2d.16h.16m
    ublock-abuse: 77-1, 2d.16h.16m
    ublock-badware: 4205-121, 2d.16h.16m
    ublock-filters: 32264-184, 2d.16h.16m
    ublock-privacy: 259-1, 2d.16h.16m
    ublock-quick-fixes: 532-137, 11h.41m
    ublock-unbreak: 1870-47, 2d.16h.16m
    urlhaus-1: 6822-0, 11h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 519 ms (selfie)
  maxAssetCacheWait: 1174 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    csp.withgoogle.com: 1
    doubleclick.net: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    youtube.com: 1
```
</details>

**Comment by mapx-** [comment]
maybe you should report here:

https://github.com/abpvn/abpvn/issues

@hoang-rio

**Comment by hoang-rio** [comment]
This is url shorten link and it's not contains at with EL
