### ISSUE TITLE
[nsfw] streamkiste.tv: detection

### ISSUE THREAD

**Issue by Titanfinger** [uBlockOrigin/uAssets#16647]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://streamkiste.tv/serie/die-legende-von-korra-1695360`

### Category

detection

### Description

Adblock detection, refuse to play the video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 85394
  cosmetic: 42188
  scriptlet: 16785
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 29-12, never
    DEU-0: 6173-0, 20h.41m
    easylist: 61166-52, 20h.45m
    easyprivacy: 30917-1182, 20h.43m
    plowe-0: 3667-898, 10d.8h.12m
    ublock-abuse: 77-0, 3d.12h.52m
    ublock-badware: 4216-121, 3d.20h.34m
    ublock-filters: 31907-153, 3d.20h.35m
    ublock-privacy: 259-1, 3d.12h.51m
    ublock-unbreak: 1869-45, 3d.20h.33m
    urlhaus-1: 6721-0, 20h.42m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 124 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2789 ms (selfie)
  maxAssetCacheWait: 896 ms
popupPanel: 
  blocked: 11
  no-popups: true
  blockedDetails: 
    streamkiste.tv: 3
    ads-twitter.com: 1
    antiadblocksystems.com: 1
    d3cod80thn7qnd.cloudfront.net: 1
    imasdk.googleapis.com: 1
    scriptcdn.net: 1
    strodesoot.com: 1
    suozmtcc.com: 1
    vsmokhklbw.com: 1
```
</details>

**Comment by Dan-cer** [comment]
It is detected again by streamkiste.tv although my lists are uptodate.

**Comment by ghajini** [comment]
update filters again in 5-10 mins

**Comment by Dan-cer** [comment]
Fine. Works again. Thank you!
