### ISSUE TITLE
google.com: search ads

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#16641]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad in google after doing a search

![11](https://user-images.githubusercontent.com/33556647/216825016-195ba357-2424-481c-9794-11a8cf1556fa.png)

### URL(s) where the issue occurs.

1, go to `https://www.google.es`
2. write `lag in stream obs only me`
3. click in:  **Search for:** **`Why is obs so laggy for me?`**  marked in red in first picture

Result:
![22](https://user-images.githubusercontent.com/33556647/216824988-7cc61b12-bb30-40b4-b366-40082bae5a97.png)

### Configuration

Browser: Opera 
Windows 11
Default Settings in uBlock Origin

**Comment by iam-py-test** [comment]
FYI, DriverEasy is a very shady website/software.
> other issue, the uBO picker is unusable for me in the results of google whit opera ( no works )

You need to allow uBlock Origin to access your search results. Open opera://extensions/ and check the "allow access to search page results" option
