### ISSUE TITLE
acortalink.me: detection

### ISSUE THREAD

**Issue by pelinski46** [uBlockOrigin/uAssets#16645]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://acortalink.me/`

### Category

detection

### Description

detect ublock origin 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230205_213419](https://user-images.githubusercontent.com/54651066/216856216-b2a90c83-ce37-4fcc-a6af-191c0ee136c8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 84890
  cosmetic: 39005
  scriptlet: 16736
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32341-135, never
    ublock-badware: 4236-0, never
    ublock-privacy: 302-0, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1935-1, never
    ublock-quick-fixes: 464-1, never
    easylist: 61524-162, never
    easyprivacy: 30820-1200, never
    urlhaus-1: 8695-0, never
    plowe-0: 3671-904, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1372 ms
  maxAssetCacheWait: 20 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
provide the original link

**Comment by DimaSheiko** [comment]
Hello @mapx- 
This problem persists to this day.
It is difficult to provide a direct link as the url's expire or it is not possible to share them, they have to be opened from another page or you will be redirected to google.
But I could provide a link from which you can open the acortalink.me link in question.
You could for example go to [https://www.hackstore.fo/peliculas/godzilla-y-kong-el-nuevo-imperio-2024/](https://www.hackstore.fo/peliculas/godzilla-y-kong-el-nuevo-imperio-2024/) and scroll down a bit to the download section and click on any download option and it will open the acortalink.me link.

https://github.com/user-attachments/assets/f8096483-9b70-4b75-a91c-37a80e4e892c
