### ISSUE TITLE
alkosto.com: breakage

### ISSUE THREAD

**Issue by jonathan-guevara-a** [uBlockOrigin/uAssets#16649]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.alkosto.com/search/?text=colchon`

### Category

breakage

### Description

E-comerce site, doesn't show items list after using the search options. It happens with any keyword. 
After using "Disable for this site" it works properly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<strong>Before</strong>
![before](https://user-images.githubusercontent.com/14851431/216994939-9965317f-d01f-4b73-977d-1cb5b8d17d00.png)

<strong>After</strong>
![after](https://user-images.githubusercontent.com/14851431/216995004-afa583a9-3baa-4cdb-8358-49c45efeca42.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 84660
  cosmetic: 38412
  scriptlet: 16912
  html: 881
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32705-183, 5d.19h.59m
    ublock-badware: 4220-5, 5d.19h.58m
    ublock-privacy: 310-0, 2d.14h.12m
    ublock-abuse: 77-0, 2d.14h.11m
    ublock-unbreak: 1880-2, 5d.19h.57m
    ublock-quick-fixes: 545-0, 3d.9h.27m
    easylist: 61289-641, 6d.19h.41m
    easyprivacy: 30907-1740, 6d.19h.40m
    urlhaus-1: 8009-1, 3d.9h.26m
    plowe-0: 3669-2, 6d.15h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 669 ms (selfie)
  maxAssetCacheWait: 235 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    alkosto.com: 2
    alkomprar.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by liamengland1** [comment]
Test
`@@||media.aws.alkomprar.com/resources/assets/alkosto/_ui/responsive/common/js/modules/algolia/widgets/analytics.js`
