### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by stapuft** [uBlockOrigin/uAssets#16644]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kimcartoon.li/Cartoon/Legion-of-Super-Heroes-2023/Movie?id=107242&s=beta&pfail=1`

### Category

detection

### Description

they have ACTUALLY updated their detection and this time around they have added at least part of their script into the video players script itself

`https://kimcartoon.li/Scripts/kimplayer.js?v=1.3.4`

if it detects that ads were not loaded then it doesn't allow mouse or keyboard events to trigger anything, which it did before, but now it also doesn't even load the video the only server this doesn't effect is the HX server, the FE server also ACTS like it will play, but stops playing once the script actually loads. beta server just utterly refuses to work, even if ubo is disabled completely. so that one might just not work anymore.

i tried this many times both with my extra rules and without purged and updated after each change to the filters, no custom rules for this site......im at a los, i think they FINALLY managed to strp up their game.....(my extra filters but theyve been disabled for a while [outside of turning them on for this test] were AdGuard Tracking Protection filter,,Fanboy's Enhanced Tracking List,MVPS HOSTS,Spam404)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 124913
  cosmetic: 222889
  scriptlet: 37548
  html: 1038
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
  added: 
    adguard-generic: 68207-5092, 5m
    adguard-mobile: 8777-190, 5m
    adguard-annoyance: 63446-6534, 5m
    adguard-social: 19841-1038, 5m
    fanboy-thirdparty_social: 68-0, 5m
    fanboy-annoyance: 84399-68405, 5m
    fanboy-cookiemonster: 45353-240, 5m
    fanboy-social: 22807-26, 5m
    ublock-annoyances: 4772-4, 5m
    dpollock-0: 11395-472, 5m
    ublock-quick-fixes: 561-3, 5m
  default: 
    ublock-filters: 33092-228, 5m
    ublock-badware: 4251-5, 5m
    ublock-privacy: 310-0, 5m
    ublock-abuse: 77-0, 5m
    ublock-unbreak: 1877-0, 5m
    easylist: 61249-968, 5m
    easyprivacy: 30930-1839, 5m
    urlhaus-1: 6686-0, 5m
    plowe-0: 3667-2, 5m
filterset (user): [array of 69 redacted]
trustedset: 
  added: [array of 31 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 31898 ms (selfie)
  maxAssetCacheWait: 28406 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    kimcartoon.li: 4
    eehuzaih.com: 1
    enactsbasiate.com: 1
    facebook.com: 2
    genieessp.com: 1
    googletagmanager.com: 1
    propellerads.com: 1
    pubmatic.com: 1
    rndskittytor.com: 1
    sharethis.com: 1
    twitter.com: 1
```
</details>

**Comment by mapx-** [comment]
AG base issue @Yuki2718  (`luxubu` requests blocked)

@stapuft 
add
`/asset/*.min.js?*=*&$from=animepl.xyz|asianclub.tv|av4asia.com|avhost.xyz|baldrfilms.xyz|bazavox.com|cinegrabber.com|cinemaemcasa.xyz|cloudrls.com|cutl.xyz|dfmagazine.co.uk|diasfem.com|fakyutube.com|fplayer.info|gdstream.net|hentai4.me|izleorg3.org|javcl.me|javenglish.me|javip.pro|javlove.club|javmvp.com|javpornhd.online|javsubbed.xyz|layarkacaxxi.icu|luxubu.review|m4uhd.club|mavavid.com|mavlecteur.com|mavplayer.xyz|mm9842.com|mycloudzz.com|myvideoplayer.monster|nezuko-ah.nl|ns21.online|obaplayer.xyz|ondembed.xyz|playerjavhd.com|rubicstreaming.com|streamabc.xyz|streamm4u.club|suzihaza.com|ujav.me|vanfem.com|vcdn-stream.xyz|vcdn.io|vcdn2.space|videogreen.xyz|vidplay.ch|watch-jav-english.live|xsub.cc|xxxjaa.xyz|yuamikami.xyz|zojav.com|vidcloud.*,badfilter`

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
