### ISSUE TITLE
promo-visits.site: breakage

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#16658]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://promo-visits.site/QtaU`

### Category

breakage

### Description

Cannot be solve if AdBlock active, button for next not working. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 84900
  cosmetic: 28559
  scriptlet: 17194
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 149-58, never
    adguard-mobile: 8774-29, 1d.21h.32m
    easylist: 61248-17021, 1d.21h.32m
    easyprivacy: 30930-1183, 1d.21h.32m
    plowe-0: 3667-982, 1d.21h.32m
    ublock-abuse: 77-0, 1d.21h.32m
    ublock-badware: 4240-122, 1d.21h.31m
    ublock-filters: 32378-390, 1d.21h.31m
    ublock-privacy: 263-2, 1d.21h.31m
    ublock-quick-fixes: 543-137, 21h.17m
    ublock-unbreak: 1871-50, 1d.21h.31m
    urlhaus-1: 6657-0, 21h.16m
filterset (user): [array of 80 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 832 ms (selfie)
  maxAssetCacheWait: 411 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    cdnspace.io: 1
    loganfeels.com: 1
    themoneytizer.com: 10
    unblockia.com: 1
    whairtoa.com: 2
    zatnoh.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can only think of

```adb
promo-visits.site#@#+js(abort-on-property-read, open)
promo-visits.site##+js(set, puURL, '')
```

Anybody has any ideas?

**Comment by king-iskan** [comment]
> ```
> promo-visits.site#@#+js(abort-on-property-read, open)
> promo-visits.site##+js(set, puURL, '')
> ```

this work, but must be open new tab every click button nex step. could it be made easier?

**Comment by okiehsch** [comment]
I don't thinks so, you have to pass all steps and it takes a few seconds before the "submit to continue" part gets clickable.

**Comment by stephenhawk8054** [comment]
> this work, but must be open new tab every click button nex step. could it be made easier?

That's the point of the site's script above. We cannot modify its code, you'll need a userscript for it.
