### ISSUE TITLE
viki.com: detection

### ISSUE THREAD

**Issue by xbingbing135** [uBlockOrigin/uAssets#16657]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

viki.com wont allow ublock to work - anti ad block detected

### URL(s) where the issue occurs.

`https://www.viki.com/videos/1208677v`

### uBO version

uBlock Origin 1.46.0

### Browser name and version

Chrome Version 109.0.5414.119 

### Settings

no changes

**Comment by ghajini** [comment]
it shows warning even ublock off

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by xbingbing135** [comment]
> * clear cookies / localStorage/ cache for the tested page
> * reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> * disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> * if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
> * disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> * are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
> * restart the system, reopen the browser, test again.

Hi mapx,

Nothing works

**Comment by ghajini** [comment]
@xbingbing135 
this will work 
`viki.com##+js(set, player.options.disableAds, true)`

**Comment by xbingbing135** [comment]
> @xbingbing135 this will work `viki.com##+js(set, player.options.disableAds, true)`

Thankyou!

**Comment by D4niloMR** [comment]
@ghajini while logged-in i'm detected. `viki.com/videos/1242990v`

user: `cassy9212@wireconnected.com`
pass: `cassy9212@wireconnected.com`


this fixed here:

`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=viki.com`

**Comment by D4niloMR** [comment]
> does redirecting to google-ima.js not worked?

no

**Comment by D4niloMR** [comment]
Working fine
