### ISSUE TITLE
monitor.rs: breakage

### ISSUE THREAD

**Issue by MDM-79** [uBlockOrigin/uAssets#16650]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.monitor.rs/ram-memorija/16GB-DDR4-3200MHz-Kingston-KF432S20IB-16`

### Category

breakage

### Description

Just broken - main site works just not any of the product pages...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-02-06 152412](https://user-images.githubusercontent.com/87946426/216996904-32ada8ff-a8b2-421c-ae11-32da5d191128.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 102
filterset (summary): 
  network: 90205
  cosmetic: 113491
  scriptlet: 18715
  html: 877
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 84399-395, 14h.54m
  default: 
    user-filters: 131-1, never
    ublock-filters: 32734-38, 14h.52m
    ublock-badware: 4251-5, 14h.50m
    ublock-privacy: 307-0, 7d.2h.42m
    ublock-abuse: 77-0, 7d.2h.40m
    ublock-unbreak: 1924-1, 14h.48m
    easylist: 61166-632, 13h.5m
    easyprivacy: 30919-1740, 13h.7m
    plowe-0: 3670-2, 4d.15h.49m
    urlhaus-1: 6686-0, 14h.46m
filterset (user): [array of 131 redacted]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdateDelayAfterLaunch: 180
  autoUpdatePeriod: 7
  selfieAfter: 3
supportStats: 
  allReadyAfter: 1315 ms (selfie)
  maxAssetCacheWait: 776 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    monitor.rs: 3
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`/socialshare.$badfilter`

@ryanbr
