### ISSUE TITLE
sports.yahoo.com: breakage

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#16654]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sports.yahoo.com/`

### Category

breakage

### Description

Seems that the lower content on yahoo sports is missing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![erroryahoosports](https://user-images.githubusercontent.com/24624945/217121995-e7e7154d-4bfe-4e7e-a4cd-a442171ed29b.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.1b18
Firefox: 109
filterset (summary): 
  network: 87872
  cosmetic: 114976
  scriptlet: 22006
  html: 1038
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    block-lan: 44-0, 6m
    fanboy-annoyance: 84413-461, 6m
    ublock-annoyances: 4772-4, 6m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33102-61, 6m
    ublock-badware: 4256-5, 6m
    ublock-privacy: 310-0, 6m
    ublock-abuse: 77-0, 6m
    ublock-unbreak: 1876-2, 6m
    ublock-quick-fixes: 436-0, 6m
    easylist: 61261-305, 6m
    easyprivacy: 30930-1180, 6m
    urlhaus-1: 6520-0, 6m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 54 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: none
  extensionUpdateForceReload: true
  filterAuthorMode: true
  filterOnHeaders: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 501 ms
  maxAssetCacheWait: 217 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    yahoo.com: 9
    advertising.com: 2
    doubleclick.net: 1
    doubleverify.com: 1
    oath.com: 4
    yimg.com: 9
```
</details>

**Comment by troysjanda** [comment]
I think that its Fanboys annoyance list but i am not very good at investigating. but when i disable that list it seem that the content reappears.

**Comment by troysjanda** [comment]
I think i have narrowedd it  to this filter from Fanboy Annoyance list 
`
https://s.yimg.com/xe/tdv2-sports-site/js/react-share-buttons.931b51b9103c254782c9.min.js`

**Comment by stephenhawk8054** [comment]
Caused by `Fanboy Annoyance`

```adb
@@||s.yimg.com/*/tdv2-sports-site/js/react-share-buttons.$script,domain=sports.yahoo.com
```

@ryanbr

**Comment by troysjanda** [comment]
> Caused by `Fanboy Annoyance`
> 
> ```
> @@||s.yimg.com/*/tdv2-sports-site/js/react-share-buttons.$script,domain=sports.yahoo.com
> ```
> 
> @ryanbr

this one work for me 

`@@||s.yimg.com/xe/tdv2-sports-site/js/react-share-buttons.931b51b9103c254782c9.min.js$script,domain=sports.yahoo.com`

**Comment by troysjanda** [comment]
seems that this is affecting more than just the sports part, it also is broken on finance, entertainment, news and there is differences in the filters here is what I am seeing

```
||s.yimg.com/uc/finance/dd-site/js/react-share-buttons.101152268d80dd136c30.modern.js$script,domain=finance.yahoo.com
||s.yimg.com/aaq/news/js/react-share-buttons.cc0d64187cf8139fac5e.min.js$script,domain=yahoo.com
```

**Comment by troysjanda** [comment]
Confirmd works, thank you
