### ISSUE TITLE
legendaryrttextures.com: detection

### ISSUE THREAD

**Issue by Nazosan** [uBlockOrigin/uAssets#16655]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://legendaryrttextures.com/`

### Category

detection

### Description

Pops up an in-page "window" declaring a blocker is in use and won't let you click or use the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83152
  cosmetic: 38193
  scriptlet: 16846
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 13-0, never
    easylist: 61169-47, 17h.40m
    easyprivacy: 30908-1175, 17h.39m
    plowe-0: 3665-868, 9d.19h.7m
    ublock-abuse: 77-0, 22h.41m
    ublock-badware: 4226-120, 2d.17h.3m
    ublock-filters: 31523-146, 2d.17h.2m
    ublock-privacy: 263-1, 22h.40m
    ublock-quick-fixes: 543-15, 2h.4m
    ublock-unbreak: 1870-46, 2d.17h.1m
    urlhaus-1: 6520-0, 2h.3m
filterset (user): [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 101 ms (selfie)
  maxAssetCacheWait: 61 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googlesyndication.com: 2
    tawk.to: 1
    wp.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot the anti-adblock and describe the steps to reproduce in details?
