### ISSUE TITLE
zh.moegirl.org.cn: detection

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#16656]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://zh.moegirl.org.cn/Mainpage`

### Category

detection

### Description

After logging in, there will be a banner declaring "You are seeing this message because ad or script blocking software is interfering with this page".

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot](https://user-images.githubusercontent.com/35957435/217143219-71b358a7-3ef4-445a-b1dd-2e9fcac26678.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 111
filterset (summary): 
  network: 146943
  cosmetic: 81715
  scriptlet: 30293
  html: 891
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 68207-4207, 22h.30m
    adguard-spyware-url: 898-5, 22h.31m
    curben-phishing: 27668-3, 13h.25m
    curben-pup: 195-1, 13h.24m
  default: 
    user-filters: 2-0, never
    ublock-filters: 33092-39, 22h.26m
    ublock-badware: 4251-5, 21h.26m
    ublock-privacy: 310-0, 21h.25m
    ublock-abuse: 77-0, 21h.24m
    ublock-unbreak: 1877-1, 21h.22m
    ublock-quick-fixes: 561-149, 13h.23m
    easylist: 61071-953, 3d.11h.55m
    easyprivacy: 30918-1316, 3d.1h.38m
    urlhaus-1: 6657-0, 13h.22m
    plowe-0: 3665-912, 9d.12h.9m
    CHN-0: 28516-204, 22h.32m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1352 ms (selfie)
  maxAssetCacheWait: 2258 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    moegirl.org.cn: 3
    ezojs.com: 2
    google.com: 7
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
We cannot register an account. If you want to share your credentials account with us (if you conform I'll share an email address) we can investigate the issue, otherwise you could directly close it.

**Comment by Linisdjxm** [comment]
@mapx-  Sure, I would like to share my account.

**Comment by mapx-** [comment]
Just send your info here: `axis.trivia@gmail.com`

**Comment by Linisdjxm** [comment]
I have sent an email.

**Comment by mapx-** [comment]
Test on your side too:

`moegirl.org.cn##+js(nostif, offsetHeight)`

**Comment by Linisdjxm** [comment]
It seems to work.
