### ISSUE TITLE
stape.io: breakage

### ISSUE THREAD

**Issue by kHorozhanov** [uBlockOrigin/uAssets#16651]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

**Our website is broken due to an incorrect filter.**
Built-in uBlock filters contain stape.*  regex due to this issue:
https://github.com/uBlockOrigin/uAssets/issues/7308
Next js app failed to initialize when uBlock filters were turned on.
The menu, search, language selection, animations, and form validation can be checked.

When I turned off this section - all things were working correctly
<img width="556" alt="Screenshot 2023-02-06 at 23 38 57" src="https://user-images.githubusercontent.com/15924598/217093892-3e2fa29c-b233-47a8-88ce-61175b5d559f.png">

### URL(s) where the issue occurs.

```
https://stape.io/
https://stape.io/login
````
Our subdomains are also broken, but I can't provide a public URL to check it out (*.stape.io, *.stape.dog)

### Screenshot(s)

<img width="1728" alt="Screenshot 2023-02-06 at 23 31 58" src="https://user-images.githubusercontent.com/15924598/217092618-deb15822-1f3d-4f09-b27c-468afb901cae.png">
<img width="1728" alt="Screenshot 2023-02-06 at 23 32 39" src="https://user-images.githubusercontent.com/15924598/217092712-b9cef0ea-01c6-4649-a8cb-6e9f14650ffc.png">
<img width="1728" alt="Screenshot 2023-02-06 at 23 36 47" src="https://user-images.githubusercontent.com/15924598/217093431-03745a4a-0e4b-49d2-b168-f225961280d7.png">

### uBO version

1.46.0

### Browser name and version

Chrome/109.0.0.0

### Settings

Nothing changed, the issue can be reproduced with default settings

**Comment by mapx-** [comment]
Could you test these exceptions

```
stape.io#@#+js(abort-on-stack-trace, Math.random, /\st\.[a-zA-Z]*\s/)
stape.dog#@#+js(abort-on-stack-trace, Math.random, /\st\.[a-zA-Z]*\s/)
```

**Comment by iam-py-test** [comment]
> The easiest way to server-side tracking

Shouldn't this fall under policy? IMO waste of time to unbreak pages like this

**Comment by kHorozhanov** [comment]
> Could you test these exceptions
> 
> ```
> stape.io#@#+js(abort-on-stack-trace, Math.random, /\st\.[a-zA-Z]*\s/)
> stape.dog#@#+js(abort-on-stack-trace, Math.random, /\st\.[a-zA-Z]*\s/)
> ```
It works, but subdomains are still blocked, for example, customer dashboard   - app.stape.io, app.stape.dog

**Comment by mapx-** [comment]
@ghajini are still necessary these filters ?
`Math.random, /\st\.[a-zA-Z]*\s/`

**Comment by kHorozhanov** [comment]
@mapx- we also need our other subdomains to work correctly, for example, support.stape.io, community.stape.io, help.stape.io, and others (not right now, but in a few months). 
Can you please exclude all our subdomains?

**Comment by mapx-** [comment]
for example, what is broken here:

`https://community.stape.io/`

**Comment by ghajini** [comment]
@mapx- we can remove these filters if its breaking there are alternative filters we can craft

**Comment by mapx-** [comment]
@ghajini if you can safely remove them it would be better or (only for `aost` filters) indicate the real domain (`stape.fun` etc)

**Comment by ghajini** [comment]
yeah iam looking into it on several browsers

**Comment by mapx-** [comment]
@kHorozhanov update all filter lists and test again.

If still something broken provide all the details (test links, broken functionality, etc)
