### ISSUE TITLE
electriclove.at: breakage

### ISSUE THREAD

**Issue by mgrundnig** [uBlockOrigin/uAssets#16652]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.electriclove.at/en/`

### Category

breakage

### Description

Cookie Consent Modal is not opening, only semi-transparent black modal backdrop.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 147683
  cosmetic: 187393
  scriptlet: 25145
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36110-3075, 1m
    DEU-0: 6173-3, 1m
    adguard-annoyance: 63481-243, 1m
    adguard-social: 19851-836, 1m
    adguard-spyware-url: 898-2, 1m
    curben-phishing: 27668-0, 1m
    fanboy-annoyance: 84410-6372, 1m
    fanboy-cookiemonster: 45362-45362, 1m
    fanboy-social: 22808-22808, 1m
    fanboy-thirdparty_social: 68-20, 1m
    ublock-annoyances: 4815-210, 1m
  default: 
    user-filters: 0-0, never
    easylist: 61211-145, 1m
    easyprivacy: 30930-12003, 1m
    plowe-0: 3667-970, 1m
    ublock-abuse: 77-0, 1m
    ublock-badware: 4252-122, 1m
    ublock-filters: 32280-557, 1m
    ublock-privacy: 263-57, 1m
    ublock-quick-fixes: 428-22, 1m
    ublock-unbreak: 1868-73, 1m
    urlhaus-1: 6657-2, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 330 ms (selfie)
  maxAssetCacheWait: 396 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    electriclove.at: 1
```
</details>

**Comment by iam-py-test** [comment]
You are using
> ```yml
>    adguard-annoyance: 63481-243, 1m
>    fanboy-cookiemonster: 45362-45362, 1m
>    fanboy-social: 22808-22808, 1m
>    ublock-annoyances: 4815-210, 1m
> ```
I suspect that Fanboy's CookieMonster list is the cause.
Please disable that list (and all other custom lists) and retest.

**Comment by mgrundnig** [comment]
@iam-py-test  cheers, thanks for your help!

**Comment by mgrundnig** [comment]
It's an EasyList Cookie issue, not an uBlockOrigin issue, closing.
