### ISSUE TITLE
einthusan.tv: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#16659]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://einthusan.tv/movie/watch/1QSI/?lang=hindi`

### Category

breakage

### Description

The video does not play at all.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 172140
  cosmetic: 216213
  scriptlet: 38452
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36109-3075, 1m
    adguard-annoyance: 63498-240, 1m
    adguard-generic: 68394-1139, 1m
    adguard-social: 19851-837, 1m
    block-lan: 44-0, 1m
    curben-phishing: 28201-0, 1m
    curben-pup: 195-0, 1m
    dpollock-0: 11395-165, 1m
    fanboy-annoyance: 84164-6409, 1m
    fanboy-cookiemonster: 45380-45380, 1m
    fanboy-social: 22759-22759, 1m
    fanboy-thirdparty_social: 69-20, 1m
    ublock-annoyances: 4815-242, now
  default: 
    user-filters: 10-0, never
    easylist: 61276-1104, 1m
    easyprivacy: 30932-12146, 1m
    plowe-0: 3668-1347, now
    ublock-abuse: 77-0, now
    ublock-badware: 4262-314, now
    ublock-filters: 32283-3930, now
    ublock-privacy: 263-55, now
    ublock-quick-fixes: 428-47, now
    ublock-unbreak: 1868-113, now
    urlhaus-1: 6520-2, now
filterset (user): [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4685 ms (selfie)
  maxAssetCacheWait: 733 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    einthusan.tv: 1
    facebook.net: 1
    getpublica.com: 1
    googletagmanager.com: 1
    privacymanager.io: 2
    pubmatic.com: 1
    stathat.com: 1
    vntsm.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Test again without these

```yaml
added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36109-3075, 1m
    adguard-annoyance: 63498-240, 1m
    adguard-generic: 68394-1139, 1m
    adguard-social: 19851-837, 1m
    block-lan: 44-0, 1m
    curben-phishing: 28201-0, 1m
    curben-pup: 195-0, 1m
    dpollock-0: 11395-165, 1m
    fanboy-annoyance: 84164-6409, 1m
    fanboy-cookiemonster: 45380-45380, 1m
    fanboy-social: 22759-22759, 1m
    fanboy-thirdparty_social: 69-20, 1m
    ublock-annoyances: 4815-242, now
```

**Comment by ghajini** [comment]
works correct on default settings of ublock origin

**Comment by mapx-** [comment]
add

`/gdpr-consent-$badfilter`

@ryanbr
