### ISSUE TITLE
dooball66.com: breakage

### ISSUE THREAD

**Issue by orcath** [uBlockOrigin/uAssets#16667]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dooball66.com/`

### Category

breakage

### Description

I can open videos if I close Ublock Origin. But I found a video advertisement. However, when I open Ublock Origin, the notice "Error code: hls:networkError manifestLoadError" appears.

When I tried to find it in Ublock Logger, I saw "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.js". Is this a cryptocurrency mining script?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 174919
  cosmetic: 221011
  scriptlet: 35840
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 48078-0, 2d.5h.21m
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29562-626, 2d.5h.14m
    https://www.fanboy.co.nz/enhancedstats.txt: 2990-16, 2d.5h.22m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 40566-7797, 2d.5h.18m
    CHN-0: 28516-8411, 2d.5h.7m
    THA-0: 1467-3, 2d.5h.6m
    adguard-annoyance: 63446-331, 2d.5h.15m
    adguard-generic: 68207-2258, 2d.5h.16m
    adguard-mobile: 8777-1033, 2d.5h.12m
    adguard-social: 19841-862, 2d.5h.11m
    adguard-spyware-url: 898-2, 2d.5h.13m
    fanboy-cookiemonster: 45263-3513, 7d.6h.4m
    fanboy-thirdparty_social: 69-3, 7d.6h.5m
  default: 
    user-filters: 83-0, never
    easylist: 61157-20456, 2d.5h.19m
    easyprivacy: 30930-15270, 2d.5h.20m
    plowe-0: 3667-1668, 2d.5h.23m
    ublock-abuse: 77-0, 9d.5h.56m
    ublock-badware: 4247-315, 2d.5h.17m
    ublock-filters: 31917-3962, 2d.5h.10m
    ublock-privacy: 260-53, 9d.5h.55m
    ublock-quick-fixes: 546-162, 1d.1h.49m
    ublock-unbreak: 1869-114, 2d.5h.8m
    urlhaus-1: 6520-0, 1d.1h.48m
filterset (user): [array of 75 redacted]
trustedset: 
  added: [array of 79 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 873 ms (selfie)
  maxAssetCacheWait: 733 ms
popupPanel: 
  blocked: 87
  blockedDetails: 
    dooball66.com: 2
    addtoany.com: 7
    blackboxsys.net: 4
    facebook.net: 2
    googletagmanager.com: 2
    onlineprostream.com: 33
    rentm3u8.com: 4
    waust.at: 33
```
</details>

**Comment by orcath** [comment]
> It seems to be a site issue. Even disabling uBO (and using a thai ip) I get the same error in console:
> 
> ![image](https://user-images.githubusercontent.com/10303732/217617400-62acf4cb-ee66-48bc-9d6c-d0cef16c7fb9.png)

When I disable ublock, it may be opened, but it must first play video advertising.

However, certain channels may be unable to open at specific periods.

![dooball66](https://user-images.githubusercontent.com/124774859/217716916-f4297426-c203-44e2-b972-9fdc6f68d0fd.jpg)

**Comment by mapx-** [comment]
I tested again and now I got the stream running fine

![image](https://user-images.githubusercontent.com/10303732/217738808-bbcb1a60-5ca9-42db-ac1d-a281d520e7a0.png)

add & test again (but it's only a "cosmetic" change)

```
*.gif$domain=dooball66.com,image
playerembed-lb.blackboxsys.net###overlay
@@||waust.at/s.js$script,domain=playerembed-lb.blackboxsys.net
```

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by orcath** [comment]
I can now open Video using Enable Ublock. I discovered that it was stuck on some MyFilter

But, before watching the video, I saw that there are Call Script Ads every time; can we avoid them?

​https://edge-s10.onlineprostream.com:476/upload/ufanance_720p.mp4/playlist.m3u8
https://edge-c2.onlineprostream.com:467/upload/ufanance_720p.mp4/playlist.m3u8
https://edge-s2g.onlineprostream.com:450/upload/ufanance_720p.mp4/playlist.m3u8
https://edge-c1.onlineprostream.com:466/upload/ufanance_720p.mp4/playlist.m3u8
https://edge-c1.onlineprostream.com:442/upload/ufanance_720p.mp4/playlist.m3u8

**Comment by mapx-** [comment]
> can we avoid them?

nothing works, the main script is obfuscated etc

**Comment by orcath** [comment]
Thank you so much for your help. :)
