### ISSUE TITLE
arcadepunks.com: detection

### ISSUE THREAD

**Issue by Jabahhh** [uBlockOrigin/uAssets#16662]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.arcadepunks.com/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 84319
  cosmetic: 41740
  scriptlet: 17208
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 9h.44m
  default: 
    user-filters: 70-14, never
    easylist: 60989-46, 4d.21h.14m
    easyprivacy: 30913-1173, 4d.21h.13m
    plowe-0: 3669-897, 7d.9h.28m
    spa-1: 5039-64, 1d.20h.51m
    ublock-abuse: 77-0, 12d.7h.32m
    ublock-badware: 4226-121, 2d.7h.28m
    ublock-filters: 31922-161, 2d.7h.29m
    ublock-privacy: 259-1, 12d.7h.33m
    ublock-quick-fixes: 428-20, 9h.42m
    ublock-unbreak: 1869-47, 1d.20h.52m
    urlhaus-1: 6520-0, 9h.43m
filterset (user): [array of 70 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 109 ms (selfie)
  maxAssetCacheWait: 65 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    arcadepunks.com: 5
    facebook.com: 1
    googlesyndication.com: 3
    truepush.com: 1
```
</details>

**Comment by mapx-** [comment]
> I forced an update of my filter lists

You didn't. Do it now & test again.
