### ISSUE TITLE
[NSFW] jpvhub.com: popups

### ISSUE THREAD

**Issue by sabotendaaaa** [uBlockOrigin/uAssets#16679]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jpvhub.com/jp/9edgp69d8k/jav/%E6%9C%89%E4%BF%AE%E6%AD%A3/first-impression-azumi-ipz-094`

### Category

popups

### Description

When I click "Skip Ad", then new tab opens and fail to skip ad.

NSFW
### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

1. I click "Skip Ad".
![jpvhub1](https://user-images.githubusercontent.com/123542342/217732460-759a5891-56bd-4cdd-a3b0-8fbb2e8b3160.jpg)

2. Then, the original tab changes chrome-extension, and new tab opens (but not skip ad).
![jpvhub3](https://user-images.githubusercontent.com/123542342/217733003-26b4b1f8-8210-4026-8c6f-edb2e13f3a90.jpg)
![jpvhub2](https://user-images.githubusercontent.com/123542342/217733027-95fc1544-eb4a-4724-bfc1-6bd8fb4e27a5.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 79235
  cosmetic: 48290
  scriptlet: 17136
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/tofukko/filter/master/Adblock_Plus_list.txt: 5293-10, 1d.2h.51m
  default: 
    user-filters: 6-0, never
    JPN-1: 9226-1010, 2d.5h.22m
    easylist: 61276-367, 2h.41m
    easyprivacy: 30932-1415, 2h.40m
    plowe-0: 3671-906, 6d.5h.42m
    ublock-abuse: 77-0, 2d.5h.28m
    ublock-badware: 4231-121, 2d.5h.27m
    ublock-filters: 31917-438, 2d.5h.26m
    ublock-privacy: 263-18, 2d.5h.24m
    ublock-quick-fixes: 439-23, 2h.39m
    ublock-unbreak: 1868-59, 2d.5h.23m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 79 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 11 redacted]
hostRuleset: 
  added: [array of 22 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 5542 ms (selfie)
  maxAssetCacheWait: 2630 ms
popupPanel: 
  blocked: 37
  blockedDetails: 
    dmm.co.jp: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    juicyads.com: 5
    newrelic.com: 5
    realsrv.com: 16
    tsyndicate.com: 8
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the popup on desktop after adding the filter, but I have adjusted it to work on mobile.

**Comment by mapx-** [comment]
maybe on pause is necessary this too:

`asianclub.tv###player_ad`

**Comment by stephenhawk8054** [comment]
> Download > Link Still Has PopUps

The site uses `window.location` to redirect to ads site

```js
r.a.createElement(o, null), r.a.createElement("a", {
    className: "".concat(n.text_container),
    onClick: function() {
        window.open("http://".concat(i), "_blank"), window.location = "https://remorsefulindependence.com/bR3/Vv0hP.3dpQvCbMmXVLJ-ZMDD0N0QN/DKQk1/NEznks5/L/TPQq0SNOD-Uw4dMiDLAd"
    }
}
```

so I don't think we can do much with the popup except blocking that domain.

**Comment by stephenhawk8054** [comment]
It requires modifying local storage (not possible with uBO yet) and modifying URL (not possible yet due to security issue)

**Comment by ghajini** [comment]
Test link=
NSFW `https://www.jpvhub.com/download?link=streamtape.com/v/ZDykQMqbRYsyYl`

@gorhill will you see

random adserver redirections ,
detail what is happening
https://github.com/uBlockOrigin/uAssets/issues/16699#issuecomment-1426587477

**Comment by gorhill** [comment]
`location` is read-only, it can't be trapped.

**Comment by gorhill** [comment]
[`window.location`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location) is read-only, it can't be trapped.

**Comment by gorhill** [comment]
I linked to the documentation above.

**Comment by ghajini** [comment]
apart from this ,what's recommended fix here ?

**Comment by mapx-** [comment]
`jpvhub.com##+js(rpnt, script, /.*adConfig.*frequency_period.*/, (async () => {const a=location.href;if(!a.includes("/download?link="))return;const b=new URL(a)\,c=b.searchParams.get("link");try{location.assign(`${location.protocol}//${c}`)}catch(a){}} )();)`

**Comment by Fatcavill** [comment]
hello
There is a skip ad button
clicking download>any mirror>click hre>causes popup or page blocked
