### ISSUE TITLE
Both tag element selector and URL filter are invalid.

### ISSUE THREAD

**Issue by 2083696923** [uBlockOrigin/uAssets#16681]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On the search results page in bing.com, both the element filter and the background URL filter of ublockorgin are invalid. Bing.com didn't show a shadow when I clicked on the tag filter. I used easylist and easyprivacy, but only the whitelist rule in esaylist takes effect, but I didn't find the bing rule contained in easyprivacy in the filter (actually it should be displayed), but the whitelist rule of easylist can be displayed.Moreover, the URL filter only shows the whitelist rule of easylist, and all other URLs are not displayed.

### URL(s) where the issue occurs.

`https://www.bing.com/search?q=%E6%8B%BC%E5%A4%9A%E5%A4%9A`

### Screenshot(s)

https://user-images.githubusercontent.com/54367641/217732676-df1de6a1-82f5-4a94-98c2-2595b6443d91.jpg
There is only one message in Figure 1, easylist White List, and Figure 2 is Firefox Night.
https://user-images.githubusercontent.com/54367641/217733878-6be69a78-b348-4249-8a6b-744ba39596f1.jpg

### uBO version

1.46.0

### Browser name and version

kiwi browser 105.0.5195.26

### Settings

- Tick easylist and easyprivacy

### Notes

1. I tried adguard and found that, like ublock, the URL filter can't work normally, and only the rule of easylist white list is displayed.
2. I tried Firefox browser and lemur browser, and ublock can work normally.

**Comment by mapx-** [comment]
> I tried Firefox browser and ublock can work normally.

kiwi is not supported, if FF works for you just stick to it

**Comment by stephenhawk8054** [comment]
FYI, Kiwi disables adblockers on Bing: https://www.reddit.com/r/uBlockOrigin/comments/10xntsr/both_tag_element_selector_and_url_filter_are/j7teo9p/
