### ISSUE TITLE
skionline.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#1668]
### URL(s) where the issue occurs

`http://www.skionline.pl/`

### Describe the issue

Right click is blocked.

### Versions

- Browser/version: Waterfox 56.0.4.1
- Nano Adblocker 1.0.0.33 (based on uBO 1.15.6)

### Settings

- `https://gist.github.com/hawkeye116477/20c5dc53efda943a34d8dcf02aecb532`

**Comment by mapx-** [comment]
see if breaks something
`||skionline.pl^$inline-script`

**Comment by hawkeye116477** [comment]
@mapx- Unfortunately it breaks some content here -> `http://www.skionline.pl/pogoda/polska-beskid-slaski-szczyrk,osrodek,642,prognoza.html`. Can't some uBO rule just remove attributes?

**Comment by mapx-** [comment]
- it was added a new scriptlet to uBo, so you should use it (add it to nano ?). In uBo just purge all caches and update.

```
skionline.pl##script:inject(remove-attr.js, oncontextmenu)
skionline.pl##script:inject(remove-attr.js, oncopy)
skionline.pl##script:inject(remove-attr.js, onselectstart)
```

the new scriptlet
https://github.com/uBlockOrigin/uAssets/commit/3c97912c7303198695c40ad85c317bd2298a44eb

**Comment by mapx-** [comment]
added filters in annoyances list

**Comment by gorhill** [comment]
I'm thinking of maybe supporting syntax such as `oncontextmenu|oncopy|onselectstart` for convenience.

**Comment by gorhill** [comment]
I extended the syntax to support multiple attributes in one filter. For the current case, one single filter can replace all three above:

    skionline.pl##script:inject(remove-attr.js, oncontextmenu|oncopy|onselectstart)

**Comment by hawkeye116477** [comment]
Ok, thanks, works in Nano too :smile:.

**Comment by gorhill** [comment]
I think the filter should really be added to <https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters> instead of in here.

**Comment by hawkeye116477** [comment]
@gorhill Ok, added. You can remove it from you filterlist.

**Comment by krystian3w** [comment]
Sould be recovered: #26896
