### ISSUE TITLE
fosslinux.com: detection

### ISSUE THREAD

**Issue by Titanfinger** [uBlockOrigin/uAssets#16684]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Adblock detected

### URL(s) where the issue occurs.

`https://www.fosslinux.com`

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 85489
  cosmetic: 42431
  scriptlet: 16939
  html: 887
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32753-77, 1h.57m
    ublock-badware: 4317-5, 1h.56m
    ublock-privacy: 307-0, 10d.5h.43m
    ublock-abuse: 77-0, 10d.5h.42m
    ublock-unbreak: 1885-2, 1h.55m
    ublock-quick-fixes: 449-0, 1h.53m
    easylist: 61287-640, 1h.59m
    easyprivacy: 30933-1749, 1h.58m
    urlhaus-1: 6537-0, 1h.54m
    plowe-0: 3665-2, 10d.5h.40m
    DEU-0: 6190-2, 1h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2561 ms (selfie)
  maxAssetCacheWait: 474 ms
```
</details>

**Comment by mapx-** [comment]
I get the detection only disabling the current filter

`fosslinux.com#@#+js(nostif, ShowAdBLockerNotice)`

reset uBO to default settings, don't use other blocking addons, disable ETP too in FF

**Comment by Prakash4844** [comment]
Resetting and Disabling ETP doesn't help, it still get detected.

![image](https://user-images.githubusercontent.com/81550376/218242583-44233ce1-e48d-4f1b-8a4c-52bea5e0de02.png)

**Comment by stephenhawk8054** [comment]
I can't reproduce the anti-adblock either. Check if you are using any:

- Other extensions,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by mapx-** [comment]
@Prakash4844 

add & test
```
fosslinux.com###penci-adblocker-popup-adblock
fosslinux.com##.penci-promo-popup-wrapper
fosslinux.com##html,body:style(background: none !important; overflow: auto !important;)
```
