### ISSUE TITLE
[nsfw] yydstxt.vip: ads

### ISSUE THREAD

**Issue by hxy0922** [uBlockOrigin/uAssets#16682]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://www.yydstxt.vip/25/25479/753765_3.html`

### Category

ads

### Description

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 109
filterset (summary): 
  network: 84966
  cosmetic: 130592
  scriptlet: 33132
  html: 892
listset (total-discarded, last-updated): 
  removed: 
    easylist: null
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/220.txt: 1838-23, 20m
    adguard-generic: 68190-4805, 14m
    block-lan: 44-0, 15h.1m
    adguard-annoyance: 63628-2980, 15h.1m
    adguard-social: 19869-1158, 15h.1m
  default: 
    user-filters: 5-1, never
    ublock-filters: 33234-331, 15h.1m
    ublock-badware: 4311-5, 15h.1m
    ublock-privacy: 310-1, 15h.1m
    ublock-abuse: 77-0, 15h.1m
    ublock-unbreak: 1884-3, 15h.1m
    ublock-quick-fixes: 445-0, 15h.1m
    adguard-mobile: 8786-34, 15h.2m
    easyprivacy: 30934-1215, 15h.1m
    CHN-0: 27996-1370, 15h.2m
filterset (user): [array of 5 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 497 ms (selfie)
  maxAssetCacheWait: 651 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    yydstxt.vip: 2
    baidu.com: 11
    htjrlm.com: 1
    nxxyjn.com: 1
```
</details>

**Comment by mapx-** [comment]
I cannot access the page


```
Access denied
Error code 1020

You do not have access to www.yydstxt.vip.
```

**Comment by mapx-** [comment]
@hxy0922 do we need some regional ip to view / test the page ?
