### ISSUE TITLE
kaguya.live: ads

### ISSUE THREAD

**Issue by venkat2305** [uBlockOrigin/uAssets#16685]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://user-images.githubusercontent.com/55329452/217915851-fd4a3aa1-5779-46e4-bb5f-95f9b8d6f406.png

this ad is not blocked. please block this ad

### URL(s) where the issue occurs.

`https://kaguya.live/`

### Screenshot(s)

https://user-images.githubusercontent.com/55329452/217915948-869b2833-91dc-4347-8c61-c73dbc167f20.png

### uBO version

1.45.0

### Browser name and version

microsoft edge 109.0.1518.70

### Settings

default settings

**Comment by mapx-** [comment]
click uBO icon, click dashboard button ("gear" button), "my filters" tab, add the filters, click "apply changes", test the page

**Comment by venkat2305** [comment]
@mapx- this filter fixed the issue. Thanks
