### ISSUE TITLE
virustotal.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#16689]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.virustotal.com/gui/file/257623cce11c11be6cbf254545396b9925204c4d44a841159ab8cb2c1d2a9456/summary`

### Category

nuisance

### Description

Permanent prompt to join the VT Community at the top of every VT page, although I’m logged in with my VT account. If this annoyance doesn’t meet your blocking criteria, please provide me with a custom filter.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-02-10 at 13-56-36 VirusTotal - File - 257623cce11c11be6cbf254545396b9925204c4d44a841159ab8cb2c1d2a9456](https://user-images.githubusercontent.com/101707608/218088920-a1a499a8-1843-4bba-91b9-955a73638390.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 213669
  cosmetic: 242293
  scriptlet: 38177
  html: 1005
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36110-14667, 3d.2h.55m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 33713-589, 23h.9m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-0, 1d.3h.13m
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 23h.10m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 72-0, 3d.3h.6m
    https://www.i-dont-care-about-cookies.eu/abp/: 25713-5, 59m
    adguard-generic: 68392-908, 3d.3h.1m
    adguard-mobile: 8781-219, 3d.3h
    adguard-spyware-url: 898-4, 3d.2h.59m
    block-lan: 44-0, 15d.3h.33m
    curben-phishing: 30895-2, 23h.8m
    curben-pup: 195-0, 23h.7m
    adguard-annoyance: 63490-7289, 3d.2h.56m
    adguard-social: 19851-88, 3d.2h.58m
    fanboy-thirdparty_social: 68-0, 1h
    fanboy-annoyance: 84095-10800, 23h.12m
    ublock-annoyances: 4772-38, 3d.2h.57m
    dpollock-0: 11395-501, 2d.21h.43m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32311-3312, 3d.3h.4m
    ublock-badware: 4220-5, 3d.3h.3m
    ublock-privacy: 307-0, 11d.2h.24m
    ublock-abuse: 77-4, 11d.2h.23m
    ublock-unbreak: 1877-46, 3d.3h.2m
    ublock-quick-fixes: 449-0, 23h.5m
    easylist: 64996-1671, 3d.3h.8m
    easyprivacy: 30930-2206, 3d.3h.7m
    urlhaus-1: 6537-0, 23h.6m
    plowe-0: 3668-21, 3d.3h.9m
    GRC-0: 995-2, 23h.11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12757 ms (selfie)
  maxAssetCacheWait: 4083 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
All page sections are in shadow roots and we don't have a tool to work inside them.

However, if you want some custom stuff:

- go into [advanced settings in uBO](https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation)
- userResourcesLocation => put `https://axistrivia.altervista.org/list/vt12.js` then click "apply changes"
- add this filter in "my filters":

`virustotal.com##+js(vt)`

**Comment by krystian3w** [comment]
If element have unique class/ID/attributes then works simple like:

`virustotal.com##.alert-info`

https://github.com/AdguardTeam/AdguardFilters/commit/169b799e6550b37f60b5d4b829b491d1004f82bb#commitcomment-100102786
