### ISSUE TITLE
[nsfw] youtube.com: breakage

### ISSUE THREAD

**Issue by Live73** [uBlockOrigin/uAssets#16683]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=ZDyDpdFZHBo`

### Category

breakage

### Description

When Ublock is enabled, the Youtube prompt for user, to acknowledge the fact that the video might only be suitable for mature audience, is not showned..........and you can't access to the video.

Thank you for your help because it's the case for lots of rock videos with mature lyrics.

And sorry for my English.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Youtube prompt](https://user-images.githubusercontent.com/51527281/217791022-d6596014-9ae6-4475-b0be-2dbef6f01208.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 102908
  cosmetic: 47178
  scriptlet: 17022
  html: 885
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32743-38, 2h.13m
    ublock-badware: 4312-5, 2h.11m
    ublock-privacy: 310-0, 3d.59m
    ublock-abuse: 77-0, 3d.58m
    ublock-unbreak: 1879-2, 2h.12m
    easylist: 61071-616, 5d.59m
    easyprivacy: 30919-1761, 5d.58m
    urlhaus-1: 6299-0, 2h.10m
    plowe-0: 3667-2, 3d.1h
    FRA-0: 29997-567, 2h.14m
    ublock-quick-fixes: 441-22, 2h.9m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 218 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2004 ms
  maxAssetCacheWait: 6652 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    youtube.com: 8
    doubleclick.net: 2
    google.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It shows normally for me

Screenshot
<details>

![image](https://user-images.githubusercontent.com/66517106/217796272-6694f010-4f38-472b-9a6a-71bc13a13ff3.png)

</details>

**Comment by okiehsch** [comment]
Works as expected for me too,

**Comment by krystian3w** [comment]
Reset uBo to stock config.

**Comment by Live73** [comment]
thank you very much.
I've reseted uBo and all works perfectly. 👍
I would have started from here....

I don't know from where came this filter that fooled Youtube. 
 I close this issue.

Have a nice day.

**Comment by Live73** [comment]
> > I've reseted uBo and all works perfectly.
> 
> > * [x]  I do not have custom filters.
> 
> Please answer the prerequisites carefully and truthfully instead of just ticking all of them.

Sorry.
I didn't know I had a custom filter.
Thanks for your help.
In the future, First thing to do: restore uBo to stock.
