### ISSUE TITLE
atresplayer.com: breakage

### ISSUE THREAD

**Issue by josandluq** [uBlockOrigin/uAssets#16686]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.atresplayer.com/directos/mega/`

### Category

breakage

### Description

Break the stream

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 85762
  cosmetic: 43943
  scriptlet: 17217
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61287-45, 1d.2h.21m
    easyprivacy: 30932-1173, 1d.2h.20m
    plowe-0: 3667-898, 5d.1h.17m
    spa-0: 3492-10, 2h.54m
    spa-1: 5041-188, 2d.1h.59m
    ublock-abuse: 77-0, 9d.6h.17m
    ublock-badware: 4247-120, 2d.1h.58m
    ublock-filters: 31926-172, 2d.1h.57m
    ublock-privacy: 259-1, 9d.6h.16m
    ublock-quick-fixes: 441-25, 2h.53m
    ublock-unbreak: 1868-48, 2d.1h.56m
    urlhaus-1: 6537-0, 2h.52m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2872 ms (selfie)
  maxAssetCacheWait: 219 ms
popupPanel: 
  blocked: 42
  blockedDetails: 
    adsrvr.org: 2
    amazon-adsystem.com: 6
    appsflyer.com: 1
    atresmedia.com: 1
    chartbeat.com: 6
    everesttech.net: 2
    facebook.net: 1
    fwmrm.net: 2
    getpublica.com: 1
    google-analytics.com: 1
    google.com: 1
    google.es: 1
    googletagmanager.com: 2
    hotjar.com: 1
    mathtag.com: 2
    scorecardresearch.com: 6
    smartclip.net: 1
    spotxchange.com: 2
    stickyadstv.com: 1
    tiktok.com: 2
```
</details>

**Comment by mapx-** [comment]
@josandluq 
Test

```
||mssl.fwmrm.net/libs/adm/*/AdManager.js$script,domain=atresplayer.com,important,badfilter
||mssl.fwmrm.net/libs/adm/*/admanager.js$important,from=atresplayer.com,badfilter
atresplayer.com#@#+js(nostif, _creatBait)
atresplayer.com#@#+js(no-fetch-if, /conversion_async.js)
atresplayer.com#@#[href^="https://www3.smartadserver.com/click"]
```

**Comment by MrJustMe** [comment]
Those filters do not work for me at this moment, i have check them in Firefox and MS Edge, it has the same problem

**Comment by mapx-** [comment]
I tested again firefox, no issue on my side: default settings + regional lists + filters above

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by MrJustMe** [comment]
After doing all in your last post is working again in both browsers, thanks!

**Comment by mapx-** [comment]
try

`atresplayer.com#@#+js(no-fetch-if, adpass.atresmedia.com)`

but I guess the filter was added for ads in video ?!

**Comment by AdamWr** [comment]
I have removed this rule - https://github.com/AdguardTeam/AdguardFilters/commit/40a620b80a38e6bfbaa9179be9c42ca3c8b42e8e

>but I guess the filter was added for ads in video ?!

This rule was added to fix adblock detection (it's also fixed by another rule), but it seems that they changed something and if I'm not wrong, the website expects that the [response status](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) to be `0` or `404`, but `no-fetch-if`/`prevent-fetch` sets status to `200` and it looks like that in this case it causes a problem.
