### ISSUE TITLE
kjprivateinvestments.com: breakage

### ISSUE THREAD

**Issue by zlti-enterprize-llc** [uBlockOrigin/uAssets#16687]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kjprivateinvestments.com/file-share/53968899-4dbe-4001-8637-6a74773f98c1`

### Category

breakage

### Description

THE SYSTEM ,KEEP BLOCKING THE SITE,THAT I NEED WORK ON...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 93
filterset (summary): 
  network: 83225
  cosmetic: 38477
  scriptlet: 16939
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61287-45, 1d.1h.34m
    easyprivacy: 30934-1173, 1d.1h.33m
    plowe-0: 3667-898, 4d.19h.19m
    ublock-abuse: 77-0, 5d.15h.24m
    ublock-badware: 4252-120, 2d.22h.44m
    ublock-filters: 31925-134, 2d.22h.43m
    ublock-privacy: 263-1, 5d.15h.23m
    ublock-quick-fixes: 442-22, 9h.32m
    ublock-unbreak: 1866-46, 2d.22h.42m
    urlhaus-1: 6537-0, 9h.31m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 23648 ms (selfie)
  maxAssetCacheWait: 1101 ms
popupPanel: 
  blocked: 816
  blockedDetails: 
    firebaseio.com: 733
    newrelic.com: 9
    sentry-cdn.com: 2
    visitor-analytics.io: 2
    wix.com: 70
```
</details>

**Comment by mapx-** [comment]
- I'm redirected to `kjpta.com` (is it geo-specific ?)
- explain what's broken
- Provide step by step indications on how to reproduce your issue and (in case an account is necessary) a test account
