### ISSUE TITLE
ublock origin is blocking a public tv station on Firefox

### ISSUE THREAD

**Issue by MrJustMe** [uBlockOrigin/uAssets#16697]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ublock origin is blocking a public tv station since yesterday on Firefox for me
The tv streaming is not runing, only shows an static frame, it happens to me since yesterday.
I try this in ublock: Config >> Filter Lists >> Purge All Caches >> Update Now, but does not work for me.
Streaming goes normal  if ublock is disabled. No more extensions are ative at this moment in browser.

### URL(s) where the issue occurs.

`https://www.atresplayer.com/directos/mega/`

### Screenshot(s)

![Screenshot_3](https://user-images.githubusercontent.com/16737366/218176143-db7cb62a-cd2d-4f20-a428-930a25f0dfd2.png)

### Notes

I have do nothing except:  Config  >> Filter Lists >> Purge All Caches >> Update Now. Ublock must have default config, i have touching nothing there.

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 86675
  cosmetic: 44101
  scriptlet: 17393
  html: 892
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33275-194, 1m
    ublock-badware: 4297-5, 1m
    ublock-privacy: 315-0, now
    ublock-abuse: 77-0, now
    ublock-unbreak: 1887-2, now
    ublock-quick-fixes: 450-0, now
    easylist: 61412-691, now
    easyprivacy: 30943-1759, now
    urlhaus-1: 7170-0, now
    plowe-0: 3676-2, now
    spa-0: 3492-1, now
    spa-1: 5038-133, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 228 ms (selfie)
  maxAssetCacheWait: 140 ms
```
</details>

**Comment by mapx-** [comment]
duplicate

Test the filters here:
https://github.com/uBlockOrigin/uAssets/issues/16686#issuecomment-1425222280
