### ISSUE TITLE
filemoon.sx: VAST ads bypassed

### ISSUE THREAD

**Issue by MK1338** [uBlockOrigin/uAssets#16696]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://filemoon.sx/e/owjduvgixvmj`

### Category

VAST ads

### Description

VAST ads are bypassed 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83347
  cosmetic: 38501
  scriptlet: 16941
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61379-45, 19h.12m
    easyprivacy: 30937-1173, 3h.8m
    plowe-0: 3672-899, 2d.3h.17m
    ublock-abuse: 77-0, 11d.13h.18m
    ublock-badware: 4313-120, 15h.11m
    ublock-filters: 31926-137, 15h.10m
    ublock-privacy: 260-1, 11d.13h.17m
    ublock-quick-fixes: 433-25, 23h.14m
    ublock-unbreak: 1874-46, 15h.9m
    urlhaus-1: 6537-0, 23h.13m
filterset (user): [empty]
trustedset: 
  added: [array of 133 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 179 ms (selfie)
  maxAssetCacheWait: 194 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    filemoon.sx: 3
```
</details>

**Comment by ghajini** [comment]
@ryanbr 
||filemoon.*/player/jw8/vast.js

**Comment by ave9858** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/00a620e5-12e6-486f-a473-105f24930089)
Trying to upload with account fails

**Comment by ave9858** [comment]
I used Firefox, might be an issue with my config

**Comment by ave9858** [comment]
Tried again with default config on Firefox and still getting the detection

**Comment by ave9858** [comment]
> okay firefox specific does this work `filemoon.*#@#^script:has-text(/Math.floor|FMPoopS/)`

Yes, this fixes the upload box
