### ISSUE TITLE
fluz.app: breakage

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#16694]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

QR code blocked.

### URL(s) where the issue occurs.

`https://fluz.app/join/`

### uBO version

1.46.0

### Browser name and version

Chrome 109

### Settings

N/A

### Notes

```
@@||app.link^$script,domain=fluz.app
@@||api2.branch.io/v1/open$xhr,domain=fluz.app
```

**Comment by terrorist96** [comment]
> Even disabling uBO I get no QR code

Interesting.. me too now. Maybe one of those sites that are needed is down currently?

**Comment by mapx-** [comment]
However, you already tested it, enough adding those exceptions, right ?

**Comment by mapx-** [comment]
similar issue

```
! https://github.com/uBlockOrigin/uAssets/issues/13538
@@||cdn.branch.io/branch-latest.min.js$script,domain=ecwid.com
@@||app.link/_r?sdk$script,domain=ecwid.com
@@||api2.branch.io/v1/url$xhr,domain=ecwid.com
```

**Comment by terrorist96** [comment]
> However, you already tested it, enough adding those exceptions, right ?

Yeah. I'll check back later on to see if it's working.

**Comment by terrorist96** [comment]
@mapx- I realized the QR code wasn't loading because I had stripped the URL of its UTM. See it in action here:
https://fluz.app/join/?_branch_match_id=1099313529680542377&utm_source=Website&utm_medium=marketing&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXz8rPzEvLKa3SSywo0MvJzMvWrwj3KIxyjQhxjwIAnhdGJyQAAAA%3D

**Comment by stephenhawk8054** [comment]
> @mapx- I realized the QR code wasn't loading because I had stripped the URL of its UTM. See it in action here:
> 
> ```
> https://fluz.app/join/?_branch_match_id=1099313529680542377&utm_source=Website&utm_medium=marketing&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXz8rPzEvLKa3SSywo0MvJzMvWrwj3KIxyjQhxjwIAnhdGJyQAAAA%3D
> ```

With the above link I can see the QR code, no breakage for me.

**Comment by terrorist96** [comment]
> > @mapx- I realized the QR code wasn't loading because I had stripped the URL of its UTM. See it in action here:
> > ```
> > https://fluz.app/join/?_branch_match_id=1099313529680542377&utm_source=Website&utm_medium=marketing&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXz8rPzEvLKa3SSywo0MvJzMvWrwj3KIxyjQhxjwIAnhdGJyQAAAA%3D
> > ```
> 
> With the above link I can see the QR code, no breakage for me.

Correct, because it's been fixed above. 😃
