### ISSUE TITLE
[nsfw] segavideo.online: detection

### ISSUE THREAD

**Issue by Padrepio18** [uBlockOrigin/uAssets#16691]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://segavideo.online/s?jqc`

### Category

detection

### Description

It detects ublock, i'm using anti adblock killer but didn't work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 109
filterset (summary): 
  network: 166099
  cosmetic: 117605
  scriptlet: 42511
  html: 1092
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36117-3346, 8m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 8m
    https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/nocoin.txt: 688-0, 8m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24291-231, 8m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5640-172, 8m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-95, 8m
    adguard-spyware-url: 899-4, 1d.6h.6m
    curben-phishing: 31074-5, 8m
    adguard-annoyance: 63632-4483, 1d.6h.6m
    fanboy-cookiemonster: 45264-17448, 1d.6h.6m
    ublock-annoyances: 4837-8, 8m
    dpollock-0: 11395-108, 6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33233-3028, 1d.6h.6m
    ublock-badware: 4311-5, 1d.6h.6m
    ublock-privacy: 310-1, 1d.6h.6m
    ublock-abuse: 77-4, 1d.6h.6m
    ublock-unbreak: 1887-3, 1d.6h.6m
    adguard-mobile: 8786-125, 1d.6h.6m
    easylist: 61382-17629, 1d.6h.6m
    easyprivacy: 30937-12306, 1d.6h.6m
    urlhaus-1: 7170-0, 8m
    ITA-0: 13439-454, 8m
    ublock-quick-fixes: 448-0, 8m
filterset (user): [empty]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3981 ms
  maxAssetCacheWait: 1259 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    dfdgfruitie.xyz: 1
```
</details>

**Comment by mapx-** [comment]
maybe

```
*$script,domain=segavideo.online,redirect-rule=noopjs
@@||d2oy22m6xey08r.cloudfront.net^$script,domain=segavideo.online
```

`d2oy22m6xey08r` was blocked by a regex, @Yuki2718 could you take a look ?

@Padrepio18 I'm not sure if now the page saying to install an app it's ok ?!

**Comment by Yuki2718** [comment]
> maybe
> 
> ```
> *$script,domain=segavideo.online,redirect-rule=noopjs
> @@||d2oy22m6xey08r.cloudfront.net^$script,domain=segavideo.online
> ```
> 
> `d2oy22m6xey08r` was blocked by a regex, 

On my end not, only `/yzfdmoan.js` is blocked.

**Comment by Padrepio18** [comment]
> maybe
> 
> ```
> *$script,domain=segavideo.online,redirect-rule=noopjs
> @@||d2oy22m6xey08r.cloudfront.net^$script,domain=segavideo.online
> ```
> 
> `d2oy22m6xey08r` was blocked by a regex, @Yuki2718 could you take a look ?
> 
> @Padrepio18 I'm not sure if now the page saying to install an app it's ok ?!
> 

The page is safe but they force to install the app from google play and activate the notifications

**Comment by mapx-** [comment]
@Padrepio18 

it's this filter enough to get a normal behaviour ?
`/yzfdmoan.js$badfilter`

**Comment by kilianr20** [comment]
> @Padrepio18
> 
> is this filter enough to get a normal behaviour ? `/yzfdmoan.js$badfilter`

Hello, i open another thread and i think this site is using the same script as the thread i open, i tried your filter and is not working the page keeps reloading. the "normal behaviour" is get redirected to the "real" content without complete the offer, the page ask you for download apps, register... etc but that was bypassed by ublock some days ago, now they patched it.

for example https://free-content.pro/s?ngMH should redirect you to a paste site wich contains a mega.nz link, now they patched it... and page keeps reloading all the time with ublock enabled.

this links are created by ad-maven advertising network, is like a "monetized url shortener". you will see a lot of domains with the exactly same script.
