### ISSUE TITLE
sflix.to: anti-devtools nuisance

### ISSUE THREAD

**Issue by DatGuy1** [uBlockOrigin/uAssets#16690]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sflix.to`

### Category

nuisance

### Description

When watching anything (not on main/search pages), if devtools are open you are redirected back to the main page.

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 193329
  cosmetic: 224157
  scriptlet: 35486
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7251-0, 52m
    https://www.fanboy.co.nz/enhancedstats.txt: 2990-10, 1d.4h.5m
    https://winhelp2002.mvps.org/hosts.txt: 8730-3, 1d.4h.4m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36114-3354, 2d.4h.26m
    adguard-annoyance: 63516-288, 2d.4h.25m
    adguard-generic: 68175-1229, 2d.4h.24m
    adguard-mobile: 8783-109, 2d.4h.23m
    adguard-social: 19856-859, 2d.4h.22m
    adguard-spyware-url: 898-2, 2d.4h.21m
    block-lan: 44-0, 15d.3h.19m
    curben-phishing: 30631-0, 50m
    curben-pup: 195-0, 49m
    dpollock-0: 11395-1472, 4d.32m
    fanboy-annoyance: 84876-6459, 6d.46m
    fanboy-cookiemonster: 45337-45337, 6d.45m
    fanboy-social: 23037-23037, 6d.5h.5m
    fanboy-thirdparty_social: 69-20, 6d.44m
  default: 
    user-filters: 44-1, never
    easylist: 61276-1372, 1d.4h.6m
    easyprivacy: 30933-12299, 1d.4h.7m
    plowe-0: 3668-1560, 2d.8m
    ublock-abuse: 77-0, 2d.11m
    ublock-badware: 4252-320, 2d.4h.18m
    ublock-filters: 31926-3933, 2d.4h.20m
    ublock-privacy: 263-57, 2d.10m
    ublock-quick-fixes: 442-54, 47m
    ublock-unbreak: 1868-113, 2d.4h.19m
    urlhaus-1: 6880-1, 48m
filterset (user): [array of 50 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 704 ms (selfie)
  maxAssetCacheWait: 759 ms
popupPanel: 
  blocked: 0
```
</details>
(Tested with stock installation)

**Comment by JobcenterTycoon** [comment]
I fixed the redirect here: https://github.com/uBlockOrigin/uAssets/commit/7e15b9940efec321330a715b1304d617b30aab40 but the debugging lag still can appear. Just open, close and open the dev console and the crasher is gone.

I tested with: `https://sflix.to/watch-movie/free-planet-dune-hd-73705.4743715`

**Comment by DatGuy1** [comment]
Works, thanks, I tore my hair out trying to deobfuscate the inline script.
