### ISSUE TITLE
[YouTube] Home feed displaying unwanted recommended videos that can not be hidden

### ISSUE THREAD

**Issue by Xbye** [uBlockOrigin/uAssets#167]
### URL(s) where the issue occurs

`https://www.youtube.com/`
### Describe the issue

YouTube's home feed displays random(?) videos to recommend to me, some of them even borderline pornographic and annoying clickbait. Blocking the element manually via Block Element option with right-click removes it, however upon refreshing the page the recommended section is back.

These recommended videos are listed at the top, and there is no [X] to close out the section like the recommended channels.
### Screenshot(s)

[Screenshot](https://cdn.discordapp.com/attachments/236980395386732554/237687815394033664/YouTube-Recommend-Advert.jpg)
### Versions
- **Browser/version**: Version 53.0.2785.143 m
- uBlock Origin version: 1.9.10
### Settings

[Settings](https://cdn.discordapp.com/attachments/236980395386732554/237690956923535360/unknown.png)
### Notes

None

**Comment by Betsy25** [comment]
I think that's normal, the home page contains recommended video's of all kind based on your interests and previous watching history according to their algorithms, these are not ads, they're regular video's.
I'm no Youtube pro, but I'm sure there's some deeply nested setting on youtube somewhere to configure what shows up on your YT homepage.

**Comment by IDKwhattoputhere** [comment]
I don't get these recommendations. Probably because my watch history is empty.

**Comment by Xbye** [comment]
> I don't get these recommendations. Probably because my watch history is empty.
Maybe try the element picker again and see if you can find a filter that works with a little bit of clicking around.

I am unable to hide it via element picker. I'm not knowledgeable enough to understand what to block that would work after I refresh. I didn't get this recommendations until a while back.

> I think that's normal, the home page contains recommended video's of all kind based on your interests and previous watching history according to their algorithms, these are not ads, they're regular videos.
I'm no Youtube pro, but I'm sure there's some deeply nested setting on youtube somewhere to configure what shows up on your YT homepage.

They're random videos that have **zero** relation to my interests that are being forced into the top of my feed and I have no way to close them. At least when YouTube recommends some useless channel to me, I can press [X] to remove it from my suggested feed. However I can't get rid of these, and some of them can be out-right obnoxious.

I would like a way to block them, and I figured I'd come here again since my knowledge in custom filters is non-existent. If this isn't the proper place to this, then please direct me to somewhere where I can find a way to possible block these elements.

**Comment by gorhill** [comment]
`youtube.com###feed-main-what_to_watch > ol > li:nth-of-type(1)`?

**Comment by Xbye** [comment]
> youtube.com###feed-main-what_to_watch > .section-list > li:nth-of-type(1)

This did not work.

**Comment by IDKwhattoputhere** [comment]
Did you try the filter list recommended by @Betsy25? Because it would be easy to find the one filter that does the job if the filter list works.

**Comment by Xbye** [comment]
> Did you try the filter list recommended by @Betsy25? Because it would be easy to find the one filter that does the job if the filter list works.

Based on the page, it seems to only really affect youtube when you get to the video section, not the home page.

**Comment by IDKwhattoputhere** [comment]
Actually it says `YouTube Homepage` in the details. I don't see what's stopping you from trying it out. Takes a whole 30 seconds.

**Comment by gotitbro** [comment]
@Xbye what did you use to highlight the portion of the image? It seems really nice.

**Comment by kowith337** [comment]
Did you mean to remove _**Recommended channel for you**_ random topic suggestion, right?
![screenshot 69](https://cloud.githubusercontent.com/assets/16535467/20038099/302b567a-a460-11e6-8c17-fcb98c02e396.jpg)
If it so, I can thanks for `:has()` support, I don't know is it conflict to hide other things or not, but it seems to work.
*I think it seems cut everything down except _**Trending**_, and remain your subscribed channel to show only.
`youtube.com##.clearfix.branded-page-box:has(.shelf-title-annotation.shelf-annotation)`

**Comment by Xbye** [comment]
@gotitbro 
I used Photoshop. Combination of blur + black overlay using a layer mask.

@kowith337 
I'm not sure what you are asking...? The [X] doesn't exist for the entire section. It's just obnoxiously there, filled with clickbait.

@IDKwhattoputhere 
I'll try it later today.

**Comment by kowith337** [comment]
@Xbye Hope this work, because it seems all _**Recommended channel for you**_ have a subscribe button.
`youtube.com##.clearfix.branded-page-box:has(span.shelf-subscription-button)`

**Comment by kowith337** [comment]
Sorry, i'm misunderstood of entire topic.

**Comment by mapx-** [comment]
try this filter
`youtube.com###dismissable:has-text(Recommended)`

**Comment by LordOfLA** [comment]
I would argue this should be left to a users "my filters" tab. Some of us make use of the Youtube recommended video's section.

In the mean time how do I add a bypass for this filter?

I have youtube.com###dismissable:has-text(Recommended),badfilter  at the moment but that doesn't seem to override it. I'm going to keep poking at the uBO wiki however.

**Comment by gorhill** [comment]
> I still suggest this be removed from the filter list.

I agree with this, this is far for a clear case of "annoyance", it easily fit the "feature" category.
