### ISSUE TITLE
sozcu.com.tr: detection

### ISSUE THREAD

**Issue by firstaawi** [uBlockOrigin/uAssets#16702]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sozcu.com.tr`

### Category

detection

### Description

filter is detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 84619
  cosmetic: 40098
  scriptlet: 16810
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    NLD-0: 2565-14, 3d.5h.15m
    easylist: 61410-48, 8h.1m
    easyprivacy: 30943-1174, 8h
    plowe-0: 3665-897, 11d.15h.1m
    ublock-abuse: 77-0, 7d.21h.24m
    ublock-badware: 4278-120, 2d.10h.15m
    ublock-filters: 31924-162, 2d.6h.13m
    ublock-privacy: 259-1, 7d.16h.32m
    ublock-unbreak: 1868-49, 2d.10h.14m
    urlhaus-1: 7170-0, 7h.59m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 49 redacted]
switchRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 524 ms (selfie)
  maxAssetCacheWait: 266 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    sozcucdn.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `TUR: AdGuard Turkish` list and test again?
