### ISSUE TITLE
bing.com: image and video search breakage

### ISSUE THREAD

**Issue by tedharris600** [uBlockOrigin/uAssets#16701]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bing.com/images/search?q=cat&qs=n&form=QBILPG&sp=-1&pq=cat&sc=10-3&sk=&cvid=B1AEAEF7C47B497F97723FD8DC26D20F&ghsh=0&ghacc=0&ghpl=`

### Category

breakage

### Description

Hello.  Since Wednesday the 8th, Ublock is blocking some image thumbnails on Bing image and video search result pages.  Some search result thumbnails are replaced with solid colored blocks, and most of the search results are cut off.  I attached an image to illustrate this.  I have been using ublock for years, and this is the first time I can remember seeing this.  

I am using Firefox 109.0.1 and Edge 110.0.1587.41.  This problem happens on both browsers.  Turning off ublock on Bing.com fixes the problem, but then I have ads and other nuisances.
  
Purging and updating the filter lists did not help.  Disabling other extensions did not help.  Resetting ublock to default settings did not help.

Ublock on Firefox is version 1.46.1rc0.  Ublock on Edge is version 1.46.0.  I am running Windows 10 Pro 64 bit with all of the latest updates.  Edge and Firefox are updated to the latest versions.  

I believe Microsoft updating Bing recently. 
Your help is appreciated.

### Screenshot(s)

https://user-images.githubusercontent.com/47835331/218235759-0f1b5cd6-d2bb-4f21-af7c-884aebe6bb09.png

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 84895
  cosmetic: 39005
  scriptlet: 16740
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61524-43, never
    easyprivacy: 30820-1171, never
    plowe-0: 3671-901, never
    ublock-abuse: 77-0, never
    ublock-badware: 4232-108, never
    ublock-filters: 31551-109, never
    ublock-privacy: 255-1, never
    ublock-quick-fixes: 458-23, never
    ublock-unbreak: 1922-44, never
    urlhaus-1: 8695-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2248 ms
  maxAssetCacheWait: 107 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    bing.com: 7
```
</details>

**Comment by stephenhawk8054** [comment]
Which region are you when accessing the site?

**Comment by tedharris600** [comment]
Hello,
I'm in the United States.  Thank you.

**Comment by stephenhawk8054** [comment]
Thanks, I can reproduce now

**Comment by liamengland1** [comment]
i can reproduce, fixed with https://github.com/uBlockOrigin/uAssets/commit/bdee9a53867acaab0e9d4394680755e613e5f18a

**Comment by tedharris600** [comment]
Thank you!
