### ISSUE TITLE
digikala.com: breakage

### ISSUE THREAD

**Issue by kavim8** [uBlockOrigin/uAssets#16706]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.digikala.com/`

### Category

breakage

### Description

blocks all contents, blank page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83941
  cosmetic: 38515
  scriptlet: 16938
  html: 886
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 3d.20h.58m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 104-14, never
    ublock-filters: 32746-157, 2d.21h.24m
    ublock-badware: 4317-5, 1d.17h.49m
    ublock-privacy: 310-0, 4d.16h.59m
    ublock-abuse: 77-0, 4d.17h
    ublock-unbreak: 1885-2, 1d.17h.48m
    easylist: 61249-523, 3d.20h.59m
    easyprivacy: 30932-1762, 3d.21h
    plowe-0: 3681-2, 1d.15h.8m
    urlhaus-1: 7170-0, 18h.21m
    ublock-quick-fixes: 449-0, 18h.20m
filterset (user): [array of 104 redacted]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 437 ms (selfie)
  maxAssetCacheWait: 200 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    digikala.com: 4
    googletagmanager.com: 1
    mediaad.org: 2
    useinsider.com: 2
    yektanet.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
user-filters: 104-14, never
```

Can you test again after disabling your custom filters?

**Comment by kavim8** [comment]
@stephenhawk8054: tested. same result

**Comment by stephenhawk8054** [comment]
Have you forced update the filter lists?

**Comment by kavim8** [comment]
yes

**Comment by stephenhawk8054** [comment]
```yaml
default: 
    user-filters: 104-14, never
    ublock-filters: 32746-157, 2d.21h.24m
    ublock-badware: 4317-5, 1d.17h.49m
    ublock-privacy: 310-0, 4d.16h.59m
    ublock-abuse: 77-0, 4d.17h
    ublock-unbreak: 1885-2, 1d.17h.48m
    easylist: 61249-523, 3d.20h.59m
    easyprivacy: 30932-1762, 3d.21h
    plowe-0: 3681-2, 1d.15h.8m
    urlhaus-1: 7170-0, 18h.21m
    ublock-quick-fixes: 449-0, 18h.20m
```

Your settings say otherwise. Anyways, I cannot reproduce the issue

Screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/218254516-ffa29dab-2188-4089-982f-3a1751742b8b.png)

</details>

Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.
