### ISSUE TITLE
psl.pw [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1670]
URL(s) where the issue occurs

`http://psl.pw/bijkkT`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
ads

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters

**Comment by mapx-** [comment]
already removed time ago
