### ISSUE TITLE
vserpg.ru: breakage

### ISSUE THREAD

**Issue by billi0909** [uBlockOrigin/uAssets#16704]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vserpg.ru/2434-eve-online.html`

### Category

breakage

### Description

чтото нетак => **there is something wrong** (blank page)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 101294
  cosmetic: 59390
  scriptlet: 18150
  html: 890
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32741-56, 2d.18h.59m
    ublock-badware: 4282-5, 2d.18h.58m
    ublock-privacy: 310-0, 2d.16h.29m
    ublock-abuse: 77-0, 6d.23h.45m
    ublock-unbreak: 1879-0, 2d.18h.57m
    ublock-quick-fixes: 436-2, 26m
    easylist: 61410-652, 29m
    easyprivacy: 30943-1743, 28m
    urlhaus-1: 7459-0, 25m
    plowe-0: 3667-2, 6d.23h.44m
    RUS-0: 39317-158, 27m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 775 ms (selfie)
  maxAssetCacheWait: 487 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    vserpg.ru: 2
    admachina.com: 1
    doubleclick.net: 4
    ensurania.com: 4
    mega-leech.net: 1
    pusherism.com: 1
    uptolike.com: 1
    yadro.ru: 1
    youtube.com: 4
```
</details>

**Comment by mapx-** [comment]
add

`vserpg.ru#@#*`

only @dimisa-RUAdList could fix / explain why that filter

**Comment by dimisa-RUAdList** [comment]
I usually use these rules for domains that intentionally promote malware or are fake.

Specifically, on `vserpg.ru`, instead of the game, a malware browser is downloaded, the game itself does not exist and never has been.

**Comment by mapx-** [comment]
@billi0909 well, you shouldn't use that malicious site, it's up to you
