### ISSUE TITLE
eltiempo.es: breakage

### ISSUE THREAD

**Issue by Yllelder** [uBlockOrigin/uAssets#16703]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.eltiempo.es/madrid.html`

### Category

breakage

### Description

The website takes a few seconds to display the scroll bar, and it appears with a lot of white space, as well as poorly organized text.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2023-02-11 074548](https://user-images.githubusercontent.com/6941502/218244868-8d978e3e-5484-48de-bddd-8c846847b613.jpg)
![Captura de pantalla 2023-02-11 074613](https://user-images.githubusercontent.com/6941502/218244869-2941ebaf-4a8e-4424-8204-7d540fbfb312.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 86519
  cosmetic: 44012
  scriptlet: 17217
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://github.com/josemirm/Remove-Webedia-Embed-DailyMotion/raw/main/Remove-Embed-Dailymotion-Webedia.txt: 22-1, 2d.15h.22m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 15h.14m
  default: 
    user-filters: 6-0, never
    easylist: 61410-45, 15h.16m
    easyprivacy: 30941-1173, 15h.15m
    plowe-0: 3667-898, 6d.16h.56m
    spa-0: 3492-10, 15h.12m
    spa-1: 5038-187, 2d.16h.42m
    ublock-abuse: 77-0, 6d.16h.55m
    ublock-badware: 4278-120, 2d.16h.41m
    ublock-filters: 31929-175, 2d.16h.40m
    ublock-privacy: 263-1, 5d.17h.7m
    ublock-quick-fixes: 442-25, 15h.11m
    ublock-unbreak: 1868-48, 2d.16h.39m
    urlhaus-1: 7170-0, 15h.13m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 281 ms (selfie)
  maxAssetCacheWait: 66 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    adnxs.com: 2
    amazon-adsystem.com: 1
    appsflyer.com: 1
    casalemedia.com: 1
    criteo.com: 1
    criteo.net: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    indexww.com: 1
    jwpcdn.com: 1
    pghub.io: 1
    richaudience.com: 4
    rubiconproject.com: 3
    scorecardresearch.com: 1
    smartadserver.com: 2
    socy.es: 1
    taboola.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Except white space, the weather table loads correctly for me

Screenshot

<details>

![image](https://user-images.githubusercontent.com/66517106/218245801-24362ea5-802a-440a-b2bd-a6d42c4e05a3.png)

</details>

Can you force update the filter lists and test again?

**Comment by mapx-** [comment]
white spice + scroll delay

```
eltiempo.es##.cls-publi-height-city
eltiempo.es##body:style(overflow: auto !important;)
```

**Comment by Yllelder** [comment]
> Except white space, the weather table loads correctly for me
> 
> Screenshot
> 
> Can you force update the filter lists and test again?

I have forced the filter update and it doesn't work :(



> white space + scroll delay
> 
> ```
> eltiempo.es##.cls-publi-height-city
> eltiempo.es##body:style(overflow: auto !important;)
> ```

It worked perfectly.

Although I keep getting a table that doesn't load correctly, is it just me?

![Captura de pantalla 2023-02-12 071431](https://user-images.githubusercontent.com/6941502/218296207-ad7d3918-ee01-436d-9575-67a15c02141d.jpg)

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
