### ISSUE TITLE
onlinevideoconverter.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#1671]
`https://www.onlinevideoconverter.com/video-converter`

When you put in a youtube link to convert it and click start, it shows the loading icon at 0% and doesn't do anything, but if you disable ublock origin, then it works properly, and takes you to the next page. This website used to work fine with ublock origin. Is there a way to fix that? Thanks.

![onlinevideoconverter com](https://user-images.githubusercontent.com/35790889/36994288-a2e561b0-207e-11e8-94c7-5518a2aae70f.jpg)

Waterfox 56.0.4.1

**Comment by IoanPaleru** [comment]
When using these filters "@@ -917,3 +917,8 @@ vhacks.org#@#.sponsor-logo
 @@||ajax.googleapis.com^$script,domain=fmovies.is|fmovies.se|fmovies.to
 @@||akacdn.ru/assets/$script,domain=fmovies.is|fmovies.se|fmovies.to
 @@||cloudflare.com/*/jquery/$script,domain=fmovies.is|fmovies.se|fmovies.to
+
+! https://github.com/uBlockOrigin/uAssets/issues/1671
+@@||onlinevideoconverter.com/webservice$xmlhttprequest,domain=onlinevideoconverter.com
+@@||onlinevideoconverter.com^$popup,domain=onlinevideoconverter.com
+@@about:blank$popup,domain=onlinevideoconverter.com" from "https://github.com/uBlockOrigin/uAssets/commit/9ec9797c251a31b78856e9fb3d512c71ff1b1eb0", "https://www.onlinevideoconverter.com/video-converter" still doesn't work properly. Is there any other way to fix that? Thanks. Have a nice day.

**Comment by mapx-** [comment]
Could you test in firefox / chrome ?

**Comment by IoanPaleru** [comment]
Actually when using these filters "@@||onlinevideoconverter.com/webservice$xmlhttprequest,domain=onlinevideoconverter.com
@@||onlinevideoconverter.com^$popup,domain=onlinevideoconverter.com
@@about:blank$popup,domain=onlinevideoconverter.com" it works now. uBlock Origin is a great program because it lets you customize it. Thanks.
