### ISSUE TITLE
snapfiles.com: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#16714]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.snapfiles.com/new/list-whatsnew.html`

### Category

breakage

### Description

With uBlock enabled, the page shows the software listing without the software icons on the left hand side, as indicated in the screenshot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bad](https://user-images.githubusercontent.com/20948631/218283289-43471109-accd-4025-81d3-747a71d3054e.png)
![Good](https://user-images.githubusercontent.com/20948631/218283293-881d890d-5534-402c-bd80-660f8d7a4ce2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 119239
  cosmetic: 215201
  scriptlet: 38183
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
    urlhaus-1: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36121-3076, 9h.26m
    adguard-annoyance: 63804-241, 9h.26m
    adguard-generic: 68097-1137, 9h.26m
    adguard-social: 19888-838, 9h.26m
    fanboy-annoyance: 84137-6461, 9h.26m
    ublock-annoyances: 4824-242, 9h.26m
  default: 
    user-filters: 10-0, never
    easylist: 61465-880, 9h.26m
    easyprivacy: 30947-12102, 9h.26m
    ublock-filters: 32480-3979, 9h.26m
filterset (user): [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2453 ms (selfie)
  maxAssetCacheWait: 369 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 3
```
</details>

**Comment by mapx-** [comment]
You disabled very important lists

```
   ublock-privacy: null
   ublock-quick-fixes: null
   ublock-unbreak: null
```

Reset uBO to default settings / lists, test again

**Comment by liamengland1** [comment]
caused by `##[class*="pico"]` in adguard base

**Comment by stephenhawk8054** [comment]
@Yuki2718
