### ISSUE TITLE
logistics.costco.com: breakage

### ISSUE THREAD

**Issue by slickxz** [uBlockOrigin/uAssets#16717]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [x] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://logistics.costco.com/tracking`

### Category

breakage

### Description

uBlock blocks request to website's parcel tracking API

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/25731011/218288949-fabb51ae-1872-4f4b-a438-d76f8b0484e2.png)
![image](https://user-images.githubusercontent.com/25731011/218288952-8e86d054-1e5b-4bac-9466-181035ac6d44.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 84421
  cosmetic: 38629
  scriptlet: 17114
  html: 892
listset (total-discarded, last-updated): 
  default: 
    user-filters: 8-1, never
    ublock-filters: 33243-154, 1d.21h.37m
    ublock-badware: 4317-5, 1d.21h.37m
    ublock-privacy: 315-0, 1d.21h.37m
    ublock-abuse: 77-0, 1d.21h.37m
    ublock-unbreak: 1885-0, 1d.21h.37m
    easylist: 61412-644, 1d.21h.37m
    easyprivacy: 30943-1744, 1d.21h.37m
    urlhaus-1: 7459-0, 21h.37m
    plowe-0: 3681-2, 1d.21h.37m
    ublock-quick-fixes: 449-2, 21h.36m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2234 ms (selfie)
  maxAssetCacheWait: 1677 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    costco.com: 3
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
@@||logistics.costco.com/innovel-services/api/tracking$xhr,1p
```

Also, can you describe the issue's behaviors besides the warning banner?

**Comment by slickxz** [comment]
When I hit track, the site won't do anything, just pop up with that banner. Filter is working though!

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by tyrosinase** [comment]
Great news! :roll_eyes: they've got a new API version and the url is now `api/v2/tracking`.

(aside from that change the filter still works though)
