### ISSUE TITLE
phoronix.com: detection

### ISSUE THREAD

**Issue by romulasry** [uBlockOrigin/uAssets#16716]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This site is detecting adblock

### URL(s) where the issue occurs.

`https://www.phoronix.com/`

### Screenshot(s)

https://user-images.githubusercontent.com/19944656/218287642-afdcf340-bf1c-499d-b6af-07a241d66fde.png

### uBO version

3.16.0

### Browser name and version

Firefox 109.0

### Settings

uBlock filters – Annoyances

**Comment by stephenhawk8054** [comment]
Which region are you when accessing the site?

**Comment by romulasry** [comment]
US, Southern California.

**Comment by stephenhawk8054** [comment]
Can you force update your filter lists (dlick the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button) and test again?

**Comment by romulasry** [comment]
It seems to work now but it doesn't load that but once in a while. I will reopen if it does it again.

**Comment by romulasry** [comment]
Seems to open more now.

**Comment by romulasry** [comment]
![Screenshot from 2023-02-27 22-38-52](https://user-images.githubusercontent.com/19944656/221774041-edab356d-3b79-42cb-8911-f0b68dbe9d9e.png)

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by gwarser** [comment]
New detection with uBO and EL annoyancess:

![image](https://github.com/uBlockOrigin/uAssets/assets/886325/cb1e15f3-8971-4692-8f91-e8e94ca0095e)

    https://www.phoronix.com/news/Intel-Data-Center-GPU-Flex-170G

`$generichide` exception helps.


<details>
<summary>Details</summary>


```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 128841
 cosmetic: 119404
 scriptlet: 27628
 html: 1996
listset (total-discarded, last-updated):
 removed:
  POL-0: null
  POL-2: null
 added:
  easylist-annoyances: 4427-126, never
  easylist-chat: 186-0, never
  fanboy-cookiemonster: 50350-228, never
  ublock-cookies-easylist: 1040-1032, never
  easylist-newsletters: 7120-17, never
  easylist-notifications: 2958-83, never
  fanboy-social: 15786-14, never
  ublock-annoyances: 6839-68, never
 default:
  user-filters: 1-0, never
  ublock-filters: 37563-119, 4d.10h.41m Δ
  ublock-badware: 7840-14, 4d.10h.41m Δ
  ublock-privacy: 759-0, 2m Δ
  ublock-unbreak: 2303-2, 4d.10h.41m Δ
  ublock-quick-fixes: 191-0, 2m Δ
  easylist: 82054-629, 4d.10h.41m Δ
  easyprivacy: 50346-861, 4d.10h.41m Δ
  urlhaus-1: 7690-5, 2m
  plowe-0: 3772-1, 6d.2h.57m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 140 ms (selfie)
 maxAssetCacheWait: 66 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  facebook.com: 2
  googletagmanager.com: 1
  pub.network: 1
  twitter.com: 1
 extended:
  ###social
  ###sharebar
  ##.twitter-share-button
  ##+js(abort-current-script, onload, setTimeout)
  ##+js(uBO-console-info)
  ##html:style(overflow:auto!important)
```

</details>

There can be an issue in the logger - using exceptor widget on visible cosmetic filters and then adding `$generichide` to My filters leaves some exception logged with 

```Filter #@##social
Filter list Static filter could not be found in any of the currently enabled filter lists
```

**Comment by gwarser** [comment]
This pops up randomly

![image](https://github.com/uBlockOrigin/uAssets/assets/886325/5a6eaade-09ac-4185-be51-d637585ccfbf)

https://www.phoronix.com/news/AMD-FSR-3.1-Announced
