### ISSUE TITLE
Cosmetic Filtering

### ISSUE THREAD

**Issue by LambLeeg** [uBlockOrigin/uAssets#16720]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

1. Introvert, Dear site has annoying gaps where the ads are supposed to be. So, I have a fix for that which is not currently included, as far, as I am concerned:

```
introvertdear.com##[id^=AdThrive_]
introvertdear.com##.slick-inline-search-panel
introvertdear.com##.has-background.has-text-color.has-theme-palette-1-color.top-bar-callout.has-text-align-center
```

2. Reddit mobile prompts to install Reddit app are appearing sometimes. However, they all have the same ID parts, and here is a working solution:

```
reddit.com##[id^=XPromo]
reddit.com##[id^=xpromo]
```

3. Yandex Weather has randomly generated IDs and Classes which is annoying. However, I found a solution for mobile version of site, and for commonly used IDs:

```
! Yandex Weather

yandex.ru##.card_without-card-decoration

yandex.ru##[id^=z1gz_]
yandex.ru##[id^=xiam]
yandex.ru##[id^=xonok]
yandex.ru##[id^=ccywkli]

yandex.ru##[class^=pic]
yandex.ru##[class^=ik]
yandex.ru##[class^=qJ]
yandex.ru##[class^=z1]

yandex.ru##.air-wymibr

yandex.ru##[data-name^=adaptiveImageContainer]
yandex.ru##[data-name^=adWrapper]

! Yandex Weather mobile

yandex.ru##[class*=Advert]

yandex.ru##[id^=ADVERT]
```

4. The Verge in its mobile version has a gap, which happens all the time for me, so here is a fix:

```
theverge.com##[id^=flex]
```

5. Android Police is the same story as the Introvert, Dear site:

```
androidpolice.com##[id^=ad-]
```

### URL(s) where the issue occurs.

`https://introvertdear.com/`
`https://www.reddit.com/`
`https://yandex.ru/pogoda/`
`https://theverge.com/`
`https://www.androidpolice.com/`

### Screenshot(s)

https://user-images.githubusercontent.com/59935189/218306045-282bc377-dc58-4595-9319-4541525800c0.png
https://user-images.githubusercontent.com/59935189/218306046-f5a4876e-aff8-432a-80cc-0809329fd61c.png
https://user-images.githubusercontent.com/59935189/218306240-650eb082-e983-4e16-920f-b3c2872af72d.JPG

### uBO version

1.46.0

### Browser name and version

Firefox (Windows 11 Pro) 109.0.1

### Settings

{
  "timeStamp": 1676198619774,
  "version": "1.46.0",
  "userSettings": {
    "uiAccentCustom": true,
    "uiAccentCustom0": "#ad75f4",
    "externalLists": 

https://abp.oisd.nl/\nhttps://abp.oisd.nl/extra/
https://abp.oisd.nl/nsfwbig/
https://cdn.jsdelivr.net/gh/badmojr/1Hosts@master/Pro/adblock.txt
https://filters.adtidy.org/extension/ublock/filters/3.txt
https://get.letsblock.it/list/0ee7f19b-32ec-4f23-9bb9-bd4ed0bfd320.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt
https://raw.githubusercontent.com/LambLeeg/LambList/master/LambList.txt

    "importedLists": [
      "https://abp.oisd.nl/",
      "https://abp.oisd.nl/extra/",
      "https://abp.oisd.nl/nsfwbig/",
      "https://cdn.jsdelivr.net/gh/badmojr/1Hosts@master/Pro/adblock.txt",
      "https://filters.adtidy.org/extension/ublock/filters/3.txt",
      "https://get.letsblock.it/list/0ee7f19b-32ec-4f23-9bb9-bd4ed0bfd320.txt",
      "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt",
      "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt",
      "https://raw.githubusercontent.com/LambLeeg/LambList/master/LambList.txt"
    ],
    "popupPanelSections": 63
  },
  "selectedFilterLists": [
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-quick-fixes",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "adguard-mobile",
    "easylist",
    "adguard-spyware-url",
    "block-lan",
    "easyprivacy",
    "urlhaus-1",
    "adguard-annoyance",
    "adguard-social",
    "fanboy-thirdparty_social",
    "fanboy-cookiemonster",
    "fanboy-annoyance",
    "fanboy-social",
    "ublock-annoyances",
    "dpollock-0",
    "plowe-0",
    "CHN-0",
    "DEU-0",
    "FRA-0",
    "IND-0",
    "RUS-0",
    "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt",
    "https://filters.adtidy.org/extension/ublock/filters/3.txt",
    "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt",
    "https://abp.oisd.nl/",
    "https://raw.githubusercontent.com/LambLeeg/LambList/master/LambList.txt"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "chrome-extension-scheme",
    "chrome-scheme",
    "edge-scheme",
    "github.com",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "wyciwyg-scheme"
  ],
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false\nno-csp-reports: * true",
  "userFilters": ""
}

### Notes

Written at the description

**Comment by mapx-** [comment]
- You should test again using only the default lists / settings (reset uBO to default setup)
- if you still find necessary cosmetic filters report them at easylist repository
- for yandex you should add `RU AdList: Counters` list

subscribe RU AdList: Counters list
[RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe)

read https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

**Comment by LambLeeg** [comment]
> * You should test again using only the default lists / settings (reset uBO to default setup)
> 
>     * if you still find necessary cosmetic filters report them at [easylist repository](https://github.com/easylist/easylist/issues)
> 
>     * for yandex you should add `RU AdList: Counters` list
> 
> 
> subscribe RU AdList: Counters list [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe)
> 
> read https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

I mean, I had to check the mark that I tried resetting my uBlock config. So, I tried all of that, actually. RU Adlist is added, and I entered my daily config here (I also made my own list because it's easier than manually adding it to all PCs, and phone with all these filters. But, I wanna share that with others because I am not the only one who reads those sites). I tried to report it to EasyList, but got no response, unfortunately.

**Comment by mapx-** [comment]
- Did you add `RU AdList: Counters` ?
- It seems your test are on mobile but you wrote it's about windows
- on mobile => be sure do not enable this setting: `Ignore generic cosmetic filters`

**Comment by LambLeeg** [comment]
> * Did you add `RU AdList: Counters` ?
> 
>     * It seems your tests are on mobile but you wrote it's about windows
> 
>     * on mobile => be sure do not enable this setting: `Ignore generic cosmetic filters`

My bad, I misread it as a default uBlock list for RU (RUS: RU AdList). This [one](https://easylist-downloads.adblockplus.org/cntblock.txt) works fine for the Yandex Weather (in fact, I have precisely the same rule I discovered per se). Lots of thanks for this list, I have no idea why it's not included by default.

I made my test both on Windows PC and Android phone. And I never choose to disable cosmetic filtering because I heavily use it myself.

**Comment by mapx-** [comment]
I'm not talking about disabling `cosmetic filtering` but about `generic cosmetic filters` which is another settings

**Comment by LambLeeg** [comment]
> I'm not talking about disabling `cosmetic filtering` but about `generic cosmetic filters` which is another setting
> 
> However, I tested `introvertdear.com` and I get no "gaps" => it's why I asked you to test using only the default settings (+ regional ones+RU counters list). No other list.

`Disable cosmetic filtering` and `Ignore generic cosmetic filters` are not checked.

Hmm, I tried `introvertdear.com` with default uBlock Origin, and, even tried to ensure it by using Brave Shields and got the same result which is those gaps.

**Comment by stephenhawk8054** [comment]
I also see no gaps either

Screenshot:

<details>

![image](https://user-images.githubusercontent.com/66517106/218310641-34f760bb-6a7b-4185-97b3-867bbcbaf9a1.png)

</details>

**Comment by stephenhawk8054** [comment]
Which region are you when accessing the site?

**Comment by LambLeeg** [comment]
> I see no gaps either
> 
> Screenshot:

Try to open any article, and then scroll it. AdThrive has about 16 div IDs there

**Comment by garry-ut99** [comment]
> LambLeeg: `introvertdear.com##[id^=AdThrive_]`
> Try to open any article, and then scroll it. AdThrive has about 16 div IDs there

What this filter aims to hide (10 items) is already hidden by EasyList by similiar filters: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218310888-643dcda6-0160-4100-bdba-65f4f6dee077.png)
No gaps for me, unless you provide a new link, so that we can reproduce.
`https://introvertdear.com/news/what-teachers-need-to-know-about-their-introverted-students-and-class-participation/`

> LambLeeg: `introvertdear.com##.slick-inline-search-panel`

It just looks like a gap, but it's not a gap, there is a delay and the gap dissapears after several seconds, and the widget loads: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218310705-9b289800-eb97-4b78-935b-7d053540a56f.png) 
`https://introvertdear.com/news/what-teachers-need-to-know-about-their-introverted-students-and-class-participation/`

> LambLeeg: `introvertdear.com##.has-background.has-text-color.has-theme-palette-1-color.top-bar-callout.has-text-align-center`

That is not for gap, it hides some header, I'm not sure whether it should be hidden:  [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218310793-d769befa-63f1-4d02-a66c-c289876e675e.png) `https://introvertdear.com/`

**Comment by stephenhawk8054** [comment]
I tried browsing the site with going to the articles and scrolling through. There are still no gaps for me

Video recording: https://pixeldrain.com/u/2mtwEHiE

`adthrive` ads are already hidden by default lists

Screenshots:

<details>

![image](https://user-images.githubusercontent.com/66517106/218311343-a8807717-7e7e-40f4-9298-567b369cc717.png)

![image](https://user-images.githubusercontent.com/66517106/218311367-f1d091c9-7c77-4ff5-aff7-7a99dc016ee4.png)

</details>

**Comment by LambLeeg** [comment]
> > LambLeeg: `introvertdear.com##[id^=AdThrive_]`
> > Try to open any article, and then scroll it. AdThrive has about 16 div IDs there
> 
> What this filter aims to hide (10 items) is already hidden by EasyList by similiar filters: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218310888-643dcda6-0160-4100-bdba-65f4f6dee077.png) No gaps for me, unless you provide a new link, so that we can reproduce. `https://introvertdear.com/news/what-teachers-need-to-know-about-their-introverted-students-and-class-participation/`
> 
> > LambLeeg: `introvertdear.com##.slick-inline-search-panel`
> 
> It just looks like a gap, but it's not a gap, there is a delay and the gap dissapears after several seconds, and the widget loads: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218310705-9b289800-eb97-4b78-935b-7d053540a56f.png) `https://introvertdear.com/news/what-teachers-need-to-know-about-their-introverted-students-and-class-participation/`
> 
> > LambLeeg: `introvertdear.com##.has-background.has-text-color.has-theme-palette-1-color.top-bar-callout.has-text-align-center`
> 
> That is not for gap, it hides some header, I'm not sure whether it should be hidden: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218310793-d769befa-63f1-4d02-a66c-c289876e675e.png) `https://introvertdear.com/`

I tried once again, and yup. AdThrive is dead over there. I wonder what came wrong previously. Now, it has exactly that prompt you made a screenshot of, and a [slicker](https://user-images.githubusercontent.com/59935189/218311239-5ff42817-f942-46ce-885c-b4800621a327.png)

I guess, I am gonna dig it deeper to understand what precisely causes it for me with my config I posted before. Thanks, and I guess those two rules still may be added to default uBlock list. However, Reddit on mobile anyways may be simplified to `reddit.com##[id^=XPromo]` instead of exact rules for each of those. I suppose this thread may be closed, thanks once again!

```
introvertdear.com##.slick-inline-search-panel
introvertdear.com##.has-background.has-text-color.has-theme-palette-1-color.top-bar-callout.has-text-align-center
```

**Comment by garry-ut99** [comment]
>LambLeeg :  I guess those two rules still may be added to default uBlock list:

Whatever you think should be added, report here:

>  https://github.com/uBlockOrigin/uAssets/issues/16720#issuecomment-1427003067 : if you still find necessary cosmetic filters report them at [easylist repository](https://github.com/easylist/easylist/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

Also before reporting anything, make sure it qualifies to be reported:

> https://github.com/easylist/easylist#readme

> https://github.com/uBlockOrigin/uAssets#uassets :
> The rationale for including a specific filter in uBO's filter lists is the same as the [EasyList/EasyPrivacy policies](https://easylist.to/pages/policy.html) and also takes into account whether a filter requires uBO's extended filter syntax.
> It is preferred to fix filter issues in EasyList. Any filters included in uBO's filter lists must use the [extended syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#extended-syntax).

**Comment by krystian3w** [comment]
>  Lots of thanks for this list, I have no idea why it's not included by default.

As active by default for everyone, it loses power, as most site developers supposedly do not check this list when you need to manually subscribe it.
It then avoids updating the list several times a day (for a certain group, the fix may be outdated as the site fiercely struggles to restore ads or a message "We detected blocking ads").
