### ISSUE TITLE
work.ink: detection

### ISSUE THREAD

**Issue by Appleu123** [uBlockOrigin/uAssets#16723]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://work.ink/21T/UtWYWoy9MA`

### Category

detection

### Description

Its detecting Ublock and its not bypassing the steps 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 189848
  cosmetic: 253182
  scriptlet: 39159
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39289-15, 1h.53m
    adguard-annoyance: 63709-515, 2d.22h.47m
    adguard-generic: 68196-731, 2d.22h.46m
    adguard-mobile: 8787-95, 2d.22h.50m
    adguard-social: 19882-844, 2d.22h.49m
    adguard-spyware-url: 899-2, 2d.22h.48m
    block-lan: 44-0, 7d.2h.26m
    curben-phishing: 31537-0, 1h.49m
    curben-pup: 195-0, 1h.48m
    dpollock-0: 11395-140, 7d.2h.26m
    fanboy-annoyance: 84394-6457, 7d.2h.26m
    fanboy-cookiemonster: 45348-45348, 7d.2h.26m
    fanboy-social: 22765-22744, 1h.54m
    fanboy-thirdparty_social: 68-20, 7d.2h.26m
    ublock-annoyances: 4818-243, 2d.22h.51m
  default: 
    user-filters: 25695-142, never
    CZE-0: 736-0, 1h.50m
    easylist: 61248-1612, 5d.22h.14m
    easyprivacy: 30930-1613, 5d.22h.13m
    plowe-0: 3667-1362, 5d.22h.17m
    ublock-abuse: 77-1, 1d.20h.58m
    ublock-badware: 4293-317, 1d.20h.56m
    ublock-filters: 31926-3936, 1d.20h.55m
    ublock-privacy: 268-10, 1d.20h.57m
    ublock-quick-fixes: 442-54, 1h.52m
    ublock-unbreak: 1874-96, 1d.20h.54m
    urlhaus-1: 6351-1, 1h.51m
filterset (user): [array of 21495 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 626 ms (selfie)
  maxAssetCacheWait: 1002 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    work.ink: 1
```
</details>

**Comment by garry-ut99** [comment]
> `https://work.ink/21T/UtWYWoy9MA`

Ad placeholders due to `ghide` in uBlock Filters: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218329150-110fbc8f-66d1-41c5-ab06-bd2de47c6394.png)
No AA for me with `ghide` off, but still AA in the source code, 
so if not to remove `ghide`, then: `work.ink##.waldo-display-unit`.

**Comment by garry-ut99** [comment]
Seems the anti-adblock is back, as going to above link triggers anti-adblock.

Also I wonder whether have been the ad placeholders forgotten to be fixed or was there a reason ( fo ex. to not change the layout, because it seems that hidding them changes a little the layout, if that was the reason, then fine ).

**Comment by garry-ut99** [comment]
Anti-adblock again, on the same link the last time.
