### ISSUE TITLE
fx4vip.com: detection

### ISSUE THREAD

**Issue by ahmadk13** [uBlockOrigin/uAssets#16722]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fx4vip.com/the-dual-effect-of-interest-rates-on-the-forex-market/`

### Category

detection

### Description

This site is detecting uBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 139498
  cosmetic: 157879
  scriptlet: 38700
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 34m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36113-3094, 3d.21h.20m
    NOR-0: 3363-176, 37m
    SWE-1: 4350-315, 1d.45m
    adguard-annoyance: 63623-1843, 3d.21h.22m
    adguard-generic: 68182-1591, 3d.21h.21m
    adguard-spyware-url: 899-2, 1d.43m
    ara-0: 2749-256, 36m
    fanboy-annoyance: 84394-39063, 6d.23h.38m
    fanboy-cookiemonster: 45348-45348, 6d.21h.57m
    ublock-annoyances: 4883-267, 1d.42m
  default: 
    user-filters: 10-1, never
    adguard-mobile: 8789-81, 1d.44m
    easylist: 61410-17787, 58m
    easyprivacy: 30943-12117, 1d.46m
    plowe-0: 3667-1068, 6d.23h.39m
    ublock-abuse: 77-0, 8d.2h.30m
    ublock-badware: 4312-313, 1d.41m
    ublock-filters: 32041-4120, 3d.21h.24m
    ublock-privacy: 263-57, 8d.2h.29m
    ublock-quick-fixes: 440-54, 35m
    ublock-unbreak: 1873-114, 3d.21h.23m
    urlhaus-1: 6351-0, 38m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 551 ms (selfie)
  maxAssetCacheWait: 437 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
provide the shortener link

**Comment by mapx-** [comment]
> Chromium Mobile

Test in FF mobile, maybe you are using kiwi browser

**Comment by garry-ut99** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16681#issuecomment-1423748636
