### ISSUE TITLE
pinterest.com: ads

### ISSUE THREAD

**Issue by basilwizard** [uBlockOrigin/uAssets#16721]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.com/`

### Category

ads

### Description

All ads on pinterest are no longer being blocked. says 0% of ads being blocked. 8 out of 10 domains connected. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83111
  cosmetic: 38477
  scriptlet: 16944
  html: 887
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32786-65, 14h.56m
    ublock-badware: 4302-5, 14h.55m
    ublock-privacy: 307-0, 11d.22h.41m
    ublock-abuse: 77-0, 11d.17h.56m
    ublock-unbreak: 1890-2, 14h.54m
    ublock-quick-fixes: 450-0, 5m
    easylist: 61276-633, 3d.13h.44m
    easyprivacy: 30933-1740, 3d.13h.43m
    urlhaus-1: 6351-0, 4m
    plowe-0: 3670-2, 10d.14h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 676 ms (selfie)
  maxAssetCacheWait: 119 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    pinterest.com: 1
    cedexis.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
You have to be specific especially with sites like pinterest: specific pages, screenshot where we could see the ads etc

**Comment by basilwizard** [comment]
Ok, i grabbed some screenshots. Specific pages is hard because it seems to be the whole site.
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/74745829/218318902-2929404b-5f8b-4275-ba75-28de6562a0fe.png">
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/74745829/218318910-1cf2f8c6-0193-4b0c-8be7-0bc9835dae56.png">

**Comment by mapx-** [comment]
The promoted items are already hidden by this filter in Easylist:

`pinterest.com##div[data-test-id="pin"]> *:has-text(Promoted by)`

You should reset uBO to default settings, update all lists and test again

**Comment by basilwizard** [comment]
Ok, I rest uBO to default, updated all the lists and the promoted ads are still there

**Comment by mapx-** [comment]
There is only a delay on my side: scrolling down the promoted stuff appears for a second then it's hidden

**Comment by garry-ut99** [comment]
Maybe another hard to reproduce case, like before: https://github.com/uBlockOrigin/uAssets/issues/10803

**Comment by mapx-** [comment]
@basilwizard test this filter

`pinterest.*##:xpath('//*[contains(text(),"Promoted")]'):upward([data-grid-item])`

**Comment by basilwizard** [comment]
omg that worked thank you!

**Comment by Yuki2718** [comment]
I wonder why the current rules are not working (working fine on my end). @basilwizard Can you disable the current rule by adding `pinterest.*#@#:xpath('//*[contains(text(),"Promoted")]'):upward([data-grid-item])` and take screenshots of DOM of the ads like https://github.com/uBlockOrigin/uAssets/issues/10803#issuecomment-991607096? Right-click on the ad and choose "Inspect element".

**Comment by Yuki2718** [comment]
Still unable to reproduce, not only the EL rule but also `pinterest.*##div[data-test-id="pin"] span:not([class]):has-text(/Promoted by|広告/):upward([data-grid-item="true"])` is covering exactly the same and thus redundant. I'll merge them.
