### ISSUE TITLE
vod.tvp.pl: detection

### ISSUE THREAD

**Issue by blackshibe** [uBlockOrigin/uAssets#16724]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vod.tvp.pl/seriale,18/m-jak-milosc-odcinki,274703/odcinek-1707,S18E1707,388493`

### Category

detection

### Description

detected after pressing the watch (odtwórz) button.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 117160
  cosmetic: 38517
  scriptlet: 16941
  html: 887
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32736-58, 5d.9h.48m
    ublock-badware: 4256-5, 5d.9h.47m
    ublock-privacy: 315-0, 2d.8h.54m
    ublock-abuse: 77-0, 2d.8h.53m
    ublock-unbreak: 1877-3, 5d.9h.46m
    ublock-quick-fixes: 450-0, 2d.8h.48m
    easylist: 61412-637, 2d.8h.51m
    adguard-spyware-url: 898-4, 5d.9h.49m
    easyprivacy: 30941-1740, 2d.8h.50m
    urlhaus-1: 6880-0, 2d.8h.47m
    curben-phishing: 30631-3, 2d.8h.49m
    plowe-0: 3671-2, 9d.15h.44m
    LegitimateURLShortener: 2116-131, 2d.8h.46m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 283 ms (selfie)
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    gemius.pl: 3
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
    snrbox.com: 3
```
</details>

**Comment by mapx-** [comment]
polish site, enable the regional lists
