### ISSUE TITLE
rumble.com: ads

### ISSUE THREAD

**Issue by ThatStoat** [uBlockOrigin/uAssets#16727]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ads appear on Rumble.com now. It appears to only show up on certain creators, likely ones who have monetization active.

Filtering `a-delivery.rmbl.ws` via Dynamic Filtering DOES fix this.

### URL(s) where the issue occurs.

`https://rumble.com/v297t6c-amsterdam-to-ban-outdoor-weed-in-the-red-light-district-lol.html`

### uBO version

1.46.0

### Browser name and version

Chrome Version 109.0.5414.120 (Official Build) (64-bit)

### Settings

Only cosmetic filters. All default filter lists are active.

### Notes

Filtering `a-delivery.rmbl.ws` via Dynamic Filtering blocks ads.

**Comment by krystian3w** [comment]
Try transfer dynamic filtering from rules to My filters by:
```adb
||a-delivery.rmbl.ws^$domain=rumble.com
```

**Comment by stephenhawk8054** [comment]
Do these work for you?

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=rumble.com,badfilter
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=rumble.com,redirect-rule=google-ima.js
||a-delivery.rmbl.ws^
*$script,redirect-rule=noopjs,domain=rumble.com
*$xhr,redirect-rule=nooptext,domain=rumble.com
```

**Comment by JohnyP36** [comment]
Although `a-delivery.rmbl.ws` is currently not blocked on Rumble I did not encounter any ads watching the example video you gave.

**Comment by krystian3w** [comment]
But possible test rewrite allow ima3 to `redirect-rule=google-ima.js` to improve "privacy".

Also `redirect-rule` can be problematic for MV3 if Google reject improve API: https://github.com/uBlockOrigin/uBOL-issues/issues/26

**Comment by stephenhawk8054** [comment]
> Although `a-delivery.rmbl.ws` is currently not blocked on Rumble I did not encounter any ads watching the example video you gave.

Ads on rumble seem to be not easily reproducible. I could not in this reddit thread either: `https://old.reddit.com/r/uBlockOrigin/comments/10yvh3p/sudden_rumble_ads/`. However, this case is easier to reproduce for me.

> But possible test rewrite allow ima3 to `redirect-rule=google-ima.js` to improve "privacy".
> 
> It is certainly worthwhile to check whether all xhr is definitely text (Supposedly browsers are to start rejecting unmatched file type as surrogate).

We have been rewriting `google-ima` filters recently: https://github.com/uBlockOrigin/uAssets/commits/master/filters/unbreak.txt

In some cases, allow is still required, but many other cases have been replaced by the shim.

**Comment by stephenhawk8054** [comment]
Some feedbacks: `https://www.reddit.com/r/uBlockOrigin/comments/10yvh3p/sudden_rumble_ads/j8ds0yx/`
