### ISSUE TITLE
guidon40hyporadius9.com: breakage

### ISSUE THREAD

**Issue by johanno** [uBlockOrigin/uAssets#16739]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [ ] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://guidon40hyporadius9.com/e/tnfrtufec0wx`

### Category

breakage

### Description

It seems that  guidon40hyporadius9.com has been bought by voe.sx and now is used to show videos.

Those can not be opened with this filter

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 85521
  cosmetic: 43001
  scriptlet: 17124
  html: 893
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 33355-198, 24m
    ublock-badware: 4297-5, 1d.9h.32m
    ublock-privacy: 315-0, 1h.37m
    ublock-abuse: 77-0, 1h.36m
    ublock-unbreak: 1924-1, 1d.9h.33m
    ublock-quick-fixes: 449-0, 1h.32m
    easylist: 61622-655, 24m
    easyprivacy: 30952-1748, 1h.33m
    urlhaus-1: 6134-0, 1h.30m
    plowe-0: 3670-2, 12d.2h.26m
    DEU-0: 6525-2, 1h.31m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 24 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 219 ms (selfie)
  maxAssetCacheWait: 384 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by johanno** [comment]
removing the default easy list fixes the issue. (Or creating a custom enable rule)

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
Fixed: https://github.com/easylist/easylist/commit/032415cd39a0c1dcd5118fb2789d781e924aedfd
