### ISSUE TITLE
gq.com.mx: ads

### ISSUE THREAD

**Issue by ElectroDia** [uBlockOrigin/uAssets#16736]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gq.com.mx/estilo-de-vida/articulo/contaminacion-digital-huella-carbono-digital`

### Category

ads

### Description

sometimes, not always one or two ads come threw the filters and get shown on the right side of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/53010801/218572129-788f99a7-106c-4a68-a937-27e7088cd29f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 85188
  cosmetic: 42362
  scriptlet: 16797
  html: 878
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32776-38, 3d.11h.27m
    ublock-badware: 4317-5, 3d.11h.26m
    ublock-privacy: 310-0, 6d.12h.34m
    ublock-abuse: 77-0, 6d.12h.35m
    ublock-unbreak: 1885-0, 3d.11h.28m
    easylist: 61530-643, 1d.8h.1m
    easyprivacy: 30952-1754, 1d.8h.2m
    urlhaus-1: 6134-0, 7h.28m
    plowe-0: 3680-2, 5d.5h.33m
    DEU-0: 6194-14, 6h.33m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 509 ms (selfie)
  maxAssetCacheWait: 112 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    gq.com.mx: 2
    condenastdigital.com: 10
    doubleclick.net: 1
    facebook.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
    moatads.com: 1
    permutive.app: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Maybe

```adb
||player.cnevids.com/interlude/gq-mx.js$script,domain=gq.com.mx
```

@Yuki2718 Spanish site?

**Comment by Yuki2718** [comment]
GQ itself is an international site with .mx being Spanish version. I see a similar video and script on `https://www.gq.com/gallery/gq-sports-style-hall-of-fame-phoenix-2023` too, but are they ads? To me look more of annoyances.

**Comment by stephenhawk8054** [comment]
Yeah looks like it's kind of a self-promo annoyance video
