### ISSUE TITLE
7xm.xyz: detection

### ISSUE THREAD

**Issue by absouini** [uBlockOrigin/uAssets#16738]
### Prerequisites

- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://7xm.xyz/`

### Category

detection

### Description

Ai

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 105086
  cosmetic: 48012
  scriptlet: 17026
  html: 0
listset (total-discarded, last-updated): 
  added: 
    FRA-0: 30000-28, 6h.9m
    ara-0: 2749-5, 6h.9m
  default: 
    user-filters: 77-4, never
    easylist: 61410-125, 4d.29m
    easyprivacy: 30934-1501, 4d.28m
    plowe-0: 3676-926, 1d.7h.24m
    ublock-abuse: 77-1, 2d.4h
    ublock-badware: 4313-139, 3d.21h.42m
    ublock-filters: 31926-242, 3d.21h.40m
    ublock-privacy: 268-1, 2d.3h.59m
    ublock-quick-fixes: 442-25, 9h.25m
    ublock-unbreak: 1874-47, 3d.21h.39m
    urlhaus-1: 6134-0, 9h.24m
filterset (user): [array of 158 redacted]
trustedset: 
  added: [array of 23 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 89562 ms (selfie)
  maxAssetCacheWait: 2019 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googlesyndication.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
I can't see any anti-adblocks. Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.
