### ISSUE TITLE
chartway.com: breakage

### ISSUE THREAD

**Issue by jbarber13** [uBlockOrigin/uAssets#16735]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.chartway.com/personal/access/video-banking.html`

### Category

breakage

### Description

There is supposed to be a chat widget in the bottom right. This is breaking when uBlock origin is running. Stopping the extension and refreshing the page resolves the issue. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/26093322/218559198-456a1702-b265-4b78-a857-c339ce6860db.png)

</details>
This shows the widget

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83232
  cosmetic: 38512
  scriptlet: 16942
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61530-45, 20h.45m
    easyprivacy: 30952-1173, 1d.51m
    plowe-0: 3667-899, 6d.22h.25m
    ublock-abuse: 77-0, 5d.2h.17m
    ublock-badware: 4293-120, 1d.50m
    ublock-filters: 31976-141, 1d.48m
    ublock-privacy: 263-1, 4d.22h.11m
    ublock-quick-fixes: 322-24, 1d.46m
    ublock-unbreak: 1877-46, 1d.49m
    urlhaus-1: 6351-0, 1d.47m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1281 ms (selfie)
  maxAssetCacheWait: 456 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    glia.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    kampyle.com: 1
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
add

```
@@||api.glia.com^$script,xhr,domain=chartway.com
@@||api.salemove.com^$xhr,domain=chartway.com
@@||salemove.com^$script,css,websocket,domain=chartway.com
```

@ryanbr
