### ISSUE TITLE
Freestar VRM by Admiral popup: ublock detector

### ISSUE THREAD

**Issue by romulasry** [uBlockOrigin/uAssets#16737]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Annoying anti-adblock detector

### URL(s) where the issue occurs.

https://www.craiyon.com

### Screenshot(s)

![Screenshot from 2023-02-13 15-39-36](https://user-images.githubusercontent.com/19944656/218599518-4cd7c56e-93f7-459c-9834-438934b09eb3.png)

### uBO version

1.44.4

### Browser name and version

Firefox 109.0

### Settings

uBlock filters – Annoyances

### Notes

AdNauseam v3.16.0

**Comment by stephenhawk8054** [comment]
Which region are you when accessing the site?

**Comment by romulasry** [comment]
Southern California, USA.

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue with uBO.

Screenshot:

<details>

![image](https://user-images.githubusercontent.com/66517106/218636755-51c54f36-f989-4735-ab53-f234d20cf123.png)

</details>

> AdNauseam v3.16.0

Please report here: https://github.com/dhowe/AdNauseam/issues

**Comment by romulasry** [comment]
Done: https://github.com/dhowe/AdNauseam/issues/2271

**Comment by romulasry** [comment]
> I can't reproduce the issue with uBO.
> 
> Screenshot:
> 
> > AdNauseam v3.16.0
> 
> Please report here: https://github.com/dhowe/AdNauseam/issues

It comes up randomly.
