### ISSUE TITLE
flashscore.fr: ads

### ISSUE THREAD

**Issue by christop69** [uBlockOrigin/uAssets#16743]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.flashscore.fr/tennis/`

### Category

ads

### Description

Encart publicitaire résiduel en bas de page 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot_2023-02-14-09-46-15-79_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/55764547/218686460-7a9ff5bd-530a-4d91-be0d-6ee01ecdb75a.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 109
filterset (summary): 
  network: 104540
  cosmetic: 34344
  scriptlet: 17077
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32891-407, 4d.4m
    ublock-badware: 4316-5, 4d.1m
    ublock-privacy: 319-1, 12h.3m
    ublock-abuse: 77-0, 1d.21h.17m
    ublock-unbreak: 1890-2, 4d.3m
    adguard-mobile: 8789-170, 2d.14h.1m
    easylist: 61385-17641, 4d.5m
    easyprivacy: 30952-1752, 11h.10m
    urlhaus-1: 6134-0, 19h.36m
    plowe-0: 3680-2, 5d.13h.41m
    FRA-0: 29998-3337, 2d.14h.3m
    ublock-quick-fixes: 448-0, 19h.27m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 259 ms (selfie)
  maxAssetCacheWait: 96 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    flashscore.fr: 2
    criteo.net: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
```
</details>

**Comment by mapx-** [comment]
I get no ad, however for french pages report here:
https://github.com/easylist/listefr/issues
