### ISSUE TITLE
futbolfantasy.com: detection

### ISSUE THREAD

**Issue by xDesert21** [uBlockOrigin/uAssets#16746]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I can hide pop up but cant disable scrollbar lock

### URL(s) where the issue occurs.

`https://www.futbolfantasy.com/`

### Screenshot(s)

![Captura de pantalla_20230214_132748](https://user-images.githubusercontent.com/125368109/218738778-17293b56-0775-40aa-84b2-af81dd06ff9e.png)

### uBO version

uBlock Origin 1.46.0

### Browser name and version

Google Chrome Last Version

### Settings

0 changes

### Notes

I can hide pop up but cant disable scrollbar lock

**Comment by garry-ut99** [comment]
It's rather  to be fixed in Regional List.

**Comment by oxkrprez** [comment]
the problem is back

**Comment by oxkrprez** [comment]
Thanks Yuki2718

**Comment by EmilioJoseP** [comment]
Its happening again :(

**Comment by Yuki2718** [comment]
I can't reproduce.

**Comment by oxkrprez** [comment]
I think only works on android/iOS, maybe ??
I blocked consentframework.com and all works for me

**Comment by EmilioJoseP** [comment]
Sorry, forgot to update. Adding both spanish filter list works and blocks the pop up.

**Comment by Yuki2718** [comment]
So no update is needed, right?

**Comment by EmilioJoseP** [comment]
yes, no update needed. Sorry again!
