### ISSUE TITLE
yandex.ru: ads

### ISSUE THREAD

**Issue by WizalinLazinas** [uBlockOrigin/uAssets#16741]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yandex.ru/pogoda/rostov-na-donu`

### Category

ads

### Description

Ads still here, even if I choose it's elements previously. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox Mobile: 109
filterset (summary): 
  network: 101536
  cosmetic: 48524
  scriptlet: 18207
  html: 892
listset (total-discarded, last-updated): 
  default: 
    user-filters: 7-0, never
    ublock-filters: 32900-433, 2d.20h.34m
    ublock-badware: 4296-5, 2d.10h.7m
    ublock-privacy: 306-1, 12d.19h.15m
    ublock-abuse: 77-0, 12d.19h.12m
    ublock-unbreak: 1890-3, 2d.10h.6m
    ublock-quick-fixes: 564-0, 11h.36m
    adguard-mobile: 8789-170, 2d.20h.35m
    easylist: 61435-17568, 23h.43m
    easyprivacy: 30954-1751, 23h.42m
    urlhaus-1: 6134-0, 11h.37m
    plowe-0: 3667-2, 7d.22h.4m
    RUS-0: 39307-1052, 1d.18h.7m
filterset (user): [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3509 ms (selfie)
  maxAssetCacheWait: 1101 ms
popupPanel: 
  blocked: 92
  blockedDetails: 
    yandex.ru: 91
    yandex.net: 1
```
</details>

**Comment by liamengland1** [comment]
Yandex ads are a special case, you likely need to use RU Adlist counters list. `https://easylist-downloads.adblockplus.org/cntblock.txt`

**Comment by mapx-** [comment]
subscribe RU AdList: Counters list
[RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe)
