### ISSUE TITLE
redensarten-index.de: ads and nuisance

### ISSUE THREAD

**Issue by gettysburg** [uBlockOrigin/uAssets#16740]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Site detects uBlock Origin and possibly other AdBlockers.

When an AdBlocker is detected, they claim to not track you and get/set any cookies, however upon proceed to show Google (PlayStore) ads,

The initial detection notification can be filtered by filtering either obect:

`###hinweis`

or

`##.hinweis-fenster`

The gray background behind the detection notification that is also applied to make navigating the site impossible can be filtered by either of these two cosmetic filters:

`www.redensarten-index.de###grau`

or

``www.redensarten-index.de##.grauer-hintergrund`

There are  many others ads and social media buttons, such as "Follow on Pinterest".

This is, after the anti adblock script has been identified and defused (I didn't have time to take a look yet, sorry), and all the ads and social media buttons removed, a possible candidate for **EasyList Germany**, since the caters to Germans and also lacks other language options.

### URL(s) where the issue occurs.

`https://www.redensarten-index.de`

### uBO version

1.46.0

### Browser name and version

Firefox 102.7.0esr (64-bit)

### Settings

```
autoUpdateAssetFetchPeriod 5
autoUpdateDelayAfterLaunch 15
```

**Comment by stephenhawk8054** [comment]
I have added fix for the anti-adblock

> There are many others ads and social media buttons, such as "Follow on Pinterest".

Can you screenshot the ads?

For social media buttons, you can enable `Fanboy’s Social` list.

**Comment by mapx-** [comment]
after adding the social list, add too

`redensarten-index.de##[href^="https://www.pinterest.de/"]`

**Comment by gettysburg** [comment]
I must have been drunk when writing the text for the ticket yesterday evening, sorry for the errors and lack of a few crucial words / sentences.

Pinterest button is still there, on the bottom right side of the page, when you scroll down a bit:

![image](https://user-images.githubusercontent.com/2256003/218715557-1dfdf6ee-bbd2-41d5-8d9b-54eb9d5da790.png)

**Comment by gettysburg** [comment]
I purged all of uBlock's caches and re-fetched all lists this morning, since I figured this filter was already merged.

I tried to reproduce it right now after manually adding the filter to my list, and the filter does get triggered, however it shows only in "My filters", not any filter list - I'd recommend that we merge it into Fanboy's Social list?

![image](https://user-images.githubusercontent.com/2256003/218776522-b704294e-8246-4507-a004-afb833b04812.png)

**Comment by mapx-** [comment]
@ryanbr
