### ISSUE TITLE
epson.com.cn: breakage

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#16742]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.epson.com.cn/Apps/tech_support/GuideDrive.aspx`

### Category

breakage

### Description

The search bar is unavailable.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 111
filterset (summary): 
  network: 162708
  cosmetic: 226129
  scriptlet: 37771
  html: 1034
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 68095-4196, 2d.40m
    adguard-spyware-url: 899-5, 2d.39m
    curben-phishing: 31332-7, 21h.45m
    curben-pup: 195-1, 21h.44m
    adguard-annoyance: 63813-614, 2d.36m
    adguard-social: 19888-840, 2d.38m
    fanboy-thirdparty_social: 68-3, 6d.3h.10m
    fanboy-annoyance: 84207-6458, 6d.3h.10m
    fanboy-cookiemonster: 45395-45395, 6d.3h.10m
    fanboy-social: 22762-22762, 6d.3h.10m
    ublock-annoyances: 4780-242, 2d.37m
  default: 
    user-filters: 16-3, never
    ublock-filters: 32792-38, 14h.31m
    ublock-badware: 4312-5, 2d.42m
    ublock-privacy: 310-0, 6d.3h.12m
    ublock-abuse: 77-0, 6d.3h.12m
    ublock-unbreak: 1890-0, 2d.41m
    ublock-quick-fixes: 449-27, 21h.47m
    easylist: 61635-971, 2h.58m
    easyprivacy: 30956-1316, 2h.57m
    urlhaus-1: 6395-0, 21h.46m
    plowe-0: 3668-917, 6d.3h.11m
    CHN-0: 28067-214, 21h.48m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 872 ms (selfie)
  maxAssetCacheWait: 654 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr 

```adb
@@||epson.com.cn/common/new/js/tracking_code.js$script,1p
```

---

There's another way to solve without whitelisting the tracking script

```adb
epson.com.cn##+js(set, _gsq, {})
epson.com.cn##+js(set, Object.prototype.push, noopFunc)
```

but `Object.prototype.push` is quite dangerous since `push` is a common function name. Do we have any ways to chain the object here? I have seen other situations that need to set `objectA.objectB` to empty/noop, but using `##+js(set, objectA.objectB, noopFunc)` will fail if `objectA` is not initialized yet.
