### ISSUE TITLE
wp.pl: detection

### ISSUE THREAD

**Issue by jadszym44** [uBlockOrigin/uAssets#16744]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wp.pl/`

### Category

detection

### Description

doesnt works, 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 84570
  cosmetic: 45986
  scriptlet: 17146
  html: 895
listset (total-discarded, last-updated): 
  default: 
    user-filters: 5-0, never
    ublock-filters: 32791-95, 13h.37m
    ublock-badware: 4337-5, 33m
    ublock-privacy: 320-0, 32m
    ublock-abuse: 77-0, 31m
    ublock-unbreak: 1892-2, 30m
    ublock-quick-fixes: 330-0, 29m
    easylist: 61633-662, 28m
    easyprivacy: 30952-1745, 27m
    urlhaus-1: 6138-0, 26m
    plowe-0: 3680-2, 25m
    POL-0: 7889-24, 13h.42m
    POL-2: 1279-12, 13h.43m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 753 ms
  maxAssetCacheWait: 279 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    wp.pl: 1
    adform.net: 4
    adnxs-simple.com: 4
    connectad.io: 4
    criteo.net: 1
    doubleclick.net: 6
    gemius.pl: 1
    inistrack.net: 1
    teads.tv: 2
```
</details>

**Comment by krystian3w** [comment]
What deos not work.

Placeholders can back on any page.

**Comment by jadszym44** [comment]
[image: obraz.png]


wt., 14 lut 2023 o 11:04 krystian3w ***@***.***> napisał(a):

**Comment by krystian3w** [comment]
By e-mail you can not inject photos: https://i.imgur.com/RkvmfoW_d.png?maxwidth=1968, not everyone have enabled copy you comment as e-mail notification where maybe can survive your photo.
