### ISSUE TITLE
sportalkorea.com: ads (placeholders)

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#16749]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad placeholders due to `ghide` in uBlock Filters: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218762911-b81675f6-e306-4af7-925a-e9e6c9bdbc41.png)
No AA for me with `ghide` off, but still AA in the source code, 
so most likely: `sportalkorea.com##ad-shield-inventory`
Also related to: https://github.com/uBlockOrigin/uAssets/issues/12163

### URL(s) where the issue occurs.

`https://www.sportalkorea.com/news/view.php?gisa_uniq=2023021408221855&section_code=20&newsstand=1`

### uBO version

1.46.1rc1

### Browser name and version

Firefox 109.0.1 & Opera 95

### Settings

-

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon I wonder if this site's still affected by ad-shield?

**Comment by JobcenterTycoon** [comment]
Yes the site still use Ad-Crap

@piquark6046 the site is calling a unblocked script from `https://ad.admine.co.kr/cgi-bin/PelicanC.dll?impr?pageid=0F4P&out=script` please take a look

For the placeholder i will add `loawa.com,ygosu.com,feedclick.net,sportalkorea.com,algumon.com,ondemandkorea.com##ad-shield-inventory`

**Comment by piquark6046** [comment]
The placeholders exist in the webpage.
However, when I use AdGuard Browser Extension and [microShield](https://github.com/List-KR/microShield), they are invisible.
