### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by karimov-javokhir** [uBlockOrigin/uAssets#16745]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/`

### Category

breakage

### Description

I've enabled uBlockOrigin and tried to listen to spotify. Now, somehow web player is not working. If I disable it, everything is fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83037
  cosmetic: 38558
  scriptlet: 16951
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61491-45, 2d.16h.58m
    easyprivacy: 30943-1173, 2d.16h.56m
    plowe-0: 3668-898, 35d.23h.19m
    ublock-abuse: 77-0, 10d.28m
    ublock-badware: 4298-120, 3h.43m
    ublock-filters: 31974-139, 3h.40m
    ublock-privacy: 263-1, 10d.29m
    ublock-quick-fixes: 441-28, 19h.48m
    ublock-unbreak: 1880-46, 3h.42m
    urlhaus-1: 6134-0, 19h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 17 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 243 ms (selfie)
  maxAssetCacheWait: 164 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googleoptimize.com: 1
    googletagmanager.com: 1
    sentry.io: 2
    spotifycdn.com: 1
```
</details>

**Comment by mapx-** [comment]
No such issue on my end.

However, even disabling uBO, the bottom controls bar does not work

![image](https://user-images.githubusercontent.com/10303732/218698317-d48e5dec-cd5f-4b36-80be-95f13910a612.png)

**Comment by mapx-** [comment]
Now it's ok, the bottom bar works again, so some site issue.
