### ISSUE TITLE
eu.tamrieltradecentre.com: detection

### ISSUE THREAD

**Issue by Dorennor** [uBlockOrigin/uAssets#16750]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Detection on `https://eu.tamrieltradecentre.com/`

### URL(s) where the issue occurs.

`https://eu.tamrieltradecentre.com/`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40647609/218798073-7d951e0f-12eb-46ae-b5c0-a9eb5802ace2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Chromium: 110
filterset (summary): 
  network: 100015
  cosmetic: 59424
  scriptlet: 18170
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-0, never
    RUS-0: 39327-12, 1h.41m
    easylist: 61371-60, 4d.16h.14m
    easyprivacy: 30942-1281, 4d.16h.13m
    plowe-0: 3681-905, 4d.16h.12m
    ublock-abuse: 77-1, 4d.16h.10m
    ublock-badware: 4308-120, 1h.45m
    ublock-filters: 31975-167, 1h.44m
    ublock-privacy: 268-1, 1h.43m
    ublock-quick-fixes: 442-29, 22h.7m
    ublock-unbreak: 1878-46, 1h.42m
    urlhaus-1: 6134-0, 21h.59m
filterset (user): [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3672 ms
  maxAssetCacheWait: 889 ms
```
</details>

**Comment by Dorennor** [comment]
> I'm unable to reproduce
> 
> > * [x]   I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+sort%3Aupdated-desc) to avoid opening a duplicate issue.
> 
> No, another duplicate of https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+tamrieltradecentre.com%3A+detection+

try to search something

**Comment by Dorennor** [comment]
> I'm unable to reproduce
> 
> > * [x]   I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+sort%3Aupdated-desc) to avoid opening a duplicate issue.
> 
> No, another duplicate of https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+tamrieltradecentre.com%3A+detection+

The error appears when you start the search and it is on the search result page that the detection error occurs.

**Comment by Dorennor** [comment]
> I'm unable to reproduce
> 
> > * [x]   I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+sort%3Aupdated-desc) to avoid opening a duplicate issue.
> 
> No, another duplicate of https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+tamrieltradecentre.com%3A+detection+

Bow of Bahraha's Curse - search it

**Comment by JobcenterTycoon** [comment]
I did but still no detection

**Comment by Dorennor** [comment]
![image](https://user-images.githubusercontent.com/40647609/218803853-82af71b8-40eb-4ea1-bfe6-fab8f07d0f7d.png)
![image](https://user-images.githubusercontent.com/40647609/218803906-ba465188-8676-4809-ba25-cda9e1d113e1.png)
![image](https://user-images.githubusercontent.com/40647609/218803982-644a4db1-1c0d-4c24-ac99-a1c2ff2c529b.png)
Press button "Search" with these advanced settings 
![image](https://user-images.githubusercontent.com/40647609/218804125-5644fb84-2a67-48e3-a66b-389d4dc496bd.png)
![image](https://user-images.githubusercontent.com/40647609/218804198-661e68e0-b552-4388-9d7f-e2cff5dbb8b5.png)




> I did but still no detection

**Comment by Dorennor** [comment]
> I did but still no detection

I can provide any information you need, just tell me what exactly.

**Comment by JobcenterTycoon** [comment]
Oh you are using edge not chrome. Maybe the build in tracking protection trigger this but i can’t test because im not using edge.
@mapx-

**Comment by Dorennor** [comment]
> Oh you are using edge not chrome. Maybe the build in tracking protection trigger this but i can’t test because im not using edge. @mapx-

Chrome also has this problem. I can check Firefox too.

**Comment by Dorennor** [comment]
> Oh you are using edge not chrome. Maybe the build in tracking protection trigger this but i can’t test because im not using edge. @mapx-

Chrome also has this problem, but Firefox works correctly.

https://user-images.githubusercontent.com/40647609/218811732-644a81f4-5704-493e-9de2-de67ff11acbf.mp4



https://user-images.githubusercontent.com/40647609/218811620-73e72dcd-5b8d-451b-be6f-d32cbb947799.mp4

**Comment by JobcenterTycoon** [comment]
I tested on chrome already and it works fine. Do you have any other blocking enabled like

- Adblocker DNS or Adblocker VPN Server
- Adblocker, "banner removal" or tracking blocker from any other program like avast
- Any other blocking methods (like blocking hosts in the windows host file, Firewall or Router blacklist)

? Those blocking can impact the result.

**Comment by Dorennor** [comment]
> I tested on chrome already and it works fine. Do you have any other blocking enabled like
> 
> * Adblocker DNS or Adblocker VPN Server
> * Adblocker, "banner removal" or tracking blocker from any other program like avast
> * Any other blocking methods (like blocking hosts in the windows host file, Firewall or Router blacklist)
> 
> ? Those blocking can impact the result.

None of these. Windows almost clean, I've reinstalled it few days ago. I don't use any antivirus except of Windows Defender with default settings.

**Comment by Dorennor** [comment]
![image](https://user-images.githubusercontent.com/40647609/218814331-5f2d3b11-e312-4e43-9047-caf16789dc7e.png)
There are list of my extensions, they are same for all 3 browsers.

**Comment by Dorennor** [comment]
Result with only Ublock extension turned on the same.

**Comment by JobcenterTycoon** [comment]
Hmmm ok i will wait until a other contributer has time for this issue. Maybe a other contributer can reproduce

**Comment by mapx-** [comment]
I can reproduce in chrome, but it's very unstable

try
```
tamrieltradecentre.com#@#a[href*=".sjv.io"] > img:style(width: 1% !important; opacity: 0 !important;)
tamrieltradecentre.com##[href*="sjv.io"]:remove()
```

**Comment by Dorennor** [comment]
tamrieltradecentre.com#@#a[href*=".sjv.io"] > img:style(width: 1% !important; opacity: 0 !important;)
tamrieltradecentre.com##[href*="sjv.io"]:remove()

It works perfectly.

tamrieltradecentre.com##+js(nostif, , 0)

It works but there are empty space.
![image](https://user-images.githubusercontent.com/40647609/218820439-f29a89e9-ae30-4694-95df-b9d86a685dac.png)


> I can reproduce in chrome, but it's very unstable
> 
> try
> 
> ```
> tamrieltradecentre.com#@#a[href*=".sjv.io"] > img:style(width: 1% !important; opacity: 0 !important;)
> tamrieltradecentre.com##[href*="sjv.io"]:remove()
> ```
> 
> or `tamrieltradecentre.com##+js(nostif, , 0)`

**Comment by garry-ut99** [comment]
> > `tamrieltradecentre.com#@#a[href*=".sjv.io"] > img:style(width: 1% !important; opacity: 0 !important;)`
> > `tamrieltradecentre.com##[href*="sjv.io"]:remove()`
> 
> It works perfectly.

Not perfectly, like in 50% of cases, just like in a casino: 
- sometimes AA still appear X times in a row, 
- sometimes AA never appear X times in a row, 
- and sometimes less or more alternately
- also sometimes a big ad placeholder appears

Steps to reproduce:
- refresh 10-20 times: `https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?ItemNamePattern=test`

**Comment by Dorennor** [comment]
> > > `tamrieltradecentre.com#@#a[href*=".sjv.io"] > img:style(width: 1% !important; opacity: 0 !important;)`
> > > `tamrieltradecentre.com##[href*="sjv.io"]:remove()`
> > 
> > 
> > It works perfectly.
> 
> Not perfectly, like in 50% of cases, just like in a casino:
> 
> * sometimes AA still appear X times in a row,
> * sometimes AA never appear X times in a row,
> * and sometimes less or more alternately
> * also sometimes a big ad placeholder appears
> 
> Steps to reproduce:
> 
> * refresh 10-20 times: `https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?ItemNamePattern=test`
> * if still can't reproduce, clear cache & cookies and try again

Yep, you're right.

**Comment by Dorennor** [comment]
> * https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?ItemNamePattern=test

Could the author of the site change something in response to new filters and your fixes? Since the fix has really become unstable, I have it now :/

**Comment by mapx-** [comment]
I said it's unstable,
However, the other filter works fine for me 

`tamrieltradecentre.com##+js(nostif, , 0)`

**Comment by Dorennor** [comment]
> I said it's unstable, However, the other filter works fine for me
> 
> `tamrieltradecentre.com##+js(nostif, , 0)`

It's also unstable, cause when I try to sort items I've also got detection

**Comment by garry-ut99** [comment]
> I can reproduce in chrome, but it's very unstable
> I said it's unstable,

It sounded for me more like AA reproduction was unstable and not a filter, maybe badly worded.

> However, the other filter works fine for me
> `tamrieltradecentre.com##+js(nostif, , 0)` 

No AA as so far for me, but almost everytime a big ad placeholder appears: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218832813-3ec340c7-3388-45e6-9751-2c5f9683cbd2.png), sometimes ads leak: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218833019-9759c561-5753-47ab-8300-198d5da3df67.png)

**Comment by garry-ut99** [comment]
> test `tamrieltradecentre.com##+js(nostif, /^/)`

The difference is no ads leak this time, but still two big ad placeholders, this URL:
`https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?ItemID=211&ItemNamePattern=Dreugh`

> It's also unstable, because when I try to sort items I've also got detection

I got no detection when trying to sort item, but I don't deny that you can still get detection.

**Comment by Dorennor** [comment]
> https://eu.tamrieltradecentre.com/pc/Trade/SearchResult?ItemID=211&ItemNamePattern=Dreugh

![image](https://user-images.githubusercontent.com/40647609/218851807-24089520-b448-44dc-a23d-2d8f6273e1df.png)

With this filter, the proposed options are not displayed (there is no this panel).

![image](https://user-images.githubusercontent.com/40647609/218851905-afc03f7d-43a6-4829-85ce-6aeacebc2db5.png)

**Comment by mapx-** [comment]
Test

```
tamrieltradecentre.com##+js(nostif, , 0)
tamrieltradecentre.com##+js(nostif, ad)
```

**Comment by Dorennor** [comment]
> tamrieltradecentre.com##+js(nostif, , 0)
> tamrieltradecentre.com##+js(nostif, ad)

Filter works but there are free space.

![image](https://user-images.githubusercontent.com/40647609/218854796-d97daac7-dfa8-462a-a2bf-930bc46c5111.png)

**Comment by mapx-** [comment]
for PH you could try (but possible getting breakages)

```
||tamrieltradecentre.com/bundles/View
tamrieltradecentre.com##.adsbygoogle
```

**Comment by Dorennor** [comment]
> for PH you could try (but possible getting breakages)
> 
> ```
> ||tamrieltradecentre.com/bundles/View
> tamrieltradecentre.com##.adsbygoogle
> ```

Page don't load correctly with these filters.

**Comment by garry-ut99** [comment]
> Page don't load correctly with these filters.

For me Anti-Adblock is back, it appears like in 50% of cases.
