### ISSUE TITLE
ladbible.com: detection and ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#16754]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ladbible.com/news/most-powerful-nuclear-bomb-detonated-657408-20230214`

### Category

detection

### Description

JWPlayer is on a black screen with uBlock enabled, and below is with Firefox Standard Tracking Protection enabled. [screenshots]
There is also an advert banner leftover.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![tsarbombaublock0](https://user-images.githubusercontent.com/91396482/218829639-8447b33c-8bcd-41e3-b9eb-71128b927b08.png)
![tsarbombafirefoxtrackingdefault0](https://user-images.githubusercontent.com/91396482/218829643-ebf5283a-6b39-420e-922b-68fc8cb38a29.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 74907
  cosmetic: 39923
  scriptlet: 16941
  html: 884
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1374-0, 54m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 10h.42m
  default: 
    user-filters: 1545-11, never
    ublock-filters: 32784-68, 3d.8h.20m
    ublock-badware: 4297-5, 3d.8h.19m
    ublock-privacy: 315-0, 3d.8h.18m
    ublock-abuse: 77-0, 3d.8h.17m
    ublock-unbreak: 1888-2, 3d.8h.16m
    ublock-quick-fixes: 334-0, 55m
    easylist: 61620-307, 1d.2h.42m
    easyprivacy: 30952-2107, 1d.10h.24m
filterset (user): [array of 571 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 484 ms (selfie)
  maxAssetCacheWait: 242 ms
  unsuspendAfter: 262 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
All fine chrome / FF + standard etp

> user-filters: 1545-11

disable "my filters", test again

**Comment by Daxy7** [comment]
Had to disable etp aswell for it to work. Apparently blocking `cdn-82.privacy-mgmt.com consent.ladbible.com` disables the JWPlayer

**Comment by garry-ut99** [comment]
> detection

I can't reproduce.

> There is also an advert banner leftover.

https://github.com/easylist/easylist/issues <== report here
