### ISSUE TITLE
Unblocking websites

### ISSUE THREAD

**Issue by Justin111997** [uBlockOrigin/uAssets#16753]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

4v5ryvbretgcge

### URL(s) where the issue occurs.

```
https://y8online.github.io/best-games.html
https://echo-website-dfol.onrender.com/projects.html
```

### Screenshot(s)

g vrsgcdf

### Notes

I want to unblock websites!!!!!!

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 0
  cosmetic: 0
  scriptlet: 0
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-filters: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
    urlhaus-1: null
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
  autoUpdate: false
  collapseBlocked: false
  contextMenuEnabled: false
  hyperlinkAuditingDisabled: false
  parseAllABPHideFilters: false
  prefetchingDisabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3998 ms (selfie)
  maxAssetCacheWait: 621 ms
```
</details>

**Comment by mapx-** [comment]
> 4v5ryvbretgcge

I don't speak unknown languages.
Get back with human explanation.
