### ISSUE TITLE
puhutv.com: detection

### ISSUE THREAD

**Issue by sistemforum** [uBlockOrigin/uAssets#16757]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://puhutv.com/dip-1-bolum-izle`

### Category

detection

### Description

adblock detection by website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://user-images.githubusercontent.com/2803525/218875019-a3fa69c1-3022-4f00-9214-fba3a6d19aab.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 155061
  cosmetic: 163744
  scriptlet: 36807
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 68200-521, 1d.4h.40m
    adguard-mobile: 8794-44, 1d.4h.54m
    adguard-spyware-url: 899-2, 1d.4h.54m
    block-lan: 44-0, 1d.4h.54m
    curben-phishing: 32312-0, 4h.3m
    curben-pup: 193-0, 4h.2m
    dpollock-0: 11395-124, 1d.4h.54m
    fanboy-annoyance: 84110-411, 1d.4h.54m
    fanboy-cookiemonster: 45514-45514, 1d.4h.54m
    fanboy-social: 22764-22764, 1d.4h.54m
    ublock-annoyances: 4829-104, 1d.4h.54m
  default: 
    user-filters: 679-17, never
    TUR-0: 12081-11, 1d.4h.54m
    easylist: 61622-1213, 1d.4h.54m
    easyprivacy: 30956-1399, 1d.4h.54m
    plowe-0: 3679-1357, 1d.4h.54m
    ublock-abuse: 77-0, 1d.4h.54m
    ublock-badware: 4333-319, 1d.4h.54m
    ublock-filters: 32534-3639, 1d.4h.54m
    ublock-privacy: 272-10, 1d.4h.54m
    ublock-quick-fixes: 321-60, 4h.1m
    ublock-unbreak: 1881-95, 1d.4h.53m
    urlhaus-1: 6078-2, 4h
filterset (user): [array of 180 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 632 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 2231 ms (selfie)
  maxAssetCacheWait: 411 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    analytics.edgekey.net: 1
    cookielaw.org: 1
    doubleclick.net: 1
    dygdigital.com: 2
    gemius.pl: 2
    googletagmanager.com: 1
    sentry.io: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by mapx-** [comment]
> user-filters: 679-17, never

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
