### ISSUE TITLE
app.veggly.net: breakage

### ISSUE THREAD

**Issue by Flashwalker** [uBlockOrigin/uAssets#16755]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.veggly.net/`

### Category

breakage

### Description

This site (app) works only if i disable **uBlock** for this site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/2188215/218847637-de50af86-1869-43bc-a8e6-32ed9a94b61e.png)
![image](https://user-images.githubusercontent.com/2188215/218849197-e4a785c8-0bf4-47ae-aaf7-a6992c91bc68.png)

![image](https://user-images.githubusercontent.com/2188215/218847801-e5c9b58a-568d-4983-b5e7-4383e749a506.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 100345
  cosmetic: 59632
  scriptlet: 18375
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39333-12, 11m
    easylist: 61690-61, 11m
    easyprivacy: 30964-1282, 11m
    plowe-0: 3680-908, 11m
    ublock-abuse: 79-1, 11m
    ublock-badware: 4338-121, 11m
    ublock-filters: 32703-180, 11m
    ublock-privacy: 276-1, 11m
    ublock-quick-fixes: 334-207, 11m
    ublock-unbreak: 1884-47, 11m
    urlhaus-1: 6078-0, 11m
filterset (user): [empty]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 474 ms
  maxAssetCacheWait: 287 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    veggly.net: 1
    maps.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
add & test

`@@||app.veggly.net/plugins/$script,1p`

@ryanbr

**Comment by Flashwalker** [comment]
> add & test
> 
> `@@||app.veggly.net/plugins/$script,1p`
> 
> @ryanbr bad filter: `/admob.$domain=~google.com`

Yes, it helps
