### ISSUE TITLE
genshin-impact.fandom.com: ads

### ISSUE THREAD

**Issue by thecutefinder** [uBlockOrigin/uAssets#16767]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://genshin-impact.fandom.com/wiki/Eleazar`

### Category

ads

### Description

Sponsored crap in the navigation bar (Fandom just can't stand to not deface their site with ads).

The non-sponsored links all have a `data-tracking-label` attribute. The sponsored links don't. May use that to make a selector.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/123335166/219101238-673cc6fd-9825-4847-a021-f92f713b6a63.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 271462
  cosmetic: 333614
  scriptlet: 42218
  html: 1101
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38466-4098, 1d.5h.28m
    adguard-generic: 68097-6580, 3d.21h.30m
    adguard-mobile: 8789-206, 3d.21h.29m
    adguard-spyware-url: 899-4, 3d.21h.28m
    block-lan: 44-0, 2d.18h.26m
    curben-phishing: 32778-7, 8h.47m
    curben-pup: 193-0, 16h.14m
    adguard-annoyance: 63804-5380, 3d.21h.27m
    adguard-social: 19888-1042, 3d.21h.26m
    fanboy-thirdparty_social: 69-0, 6d.11h.6m
    fanboy-annoyance: 84074-70110, 6d.11h.4m
    fanboy-cookiemonster: 45410-308, 6d.11h.3m
    fanboy-social: 22776-38, 3d.18h.27m
    ublock-annoyances: 4780-34, 3d.21h.25m
    dpollock-0: 11395-481, 5d.1h.34m
    ALB-0: 301-4, 12h.12m
    ara-0: 2749-0, 12h.11m
    BGR-0: 1091-11, 4d.20h.36m
    CHN-0: 28038-139, 3d.21h.24m
    CZE-0: 737-0, 16h.28m
    [29 lists not shown]: [too many]
  default: 
    user-filters: 10-0, never
    ublock-filters: 32780-412, 3d.21h.33m
    ublock-badware: 4302-5, 3d.21h.32m
    ublock-privacy: 310-0, 9d.11h.10m
    ublock-abuse: 77-0, 9d.11h.9m
    ublock-unbreak: 1890-3, 3d.21h.31m
    ublock-quick-fixes: 338-0, 16h.16m
    easylist: 61379-1304, 6d.33m
    easyprivacy: 30935-12799, 6d.32m
    urlhaus-1: 6146-0, 16h.17m
    plowe-0: 3668-2, 8d.12h.45m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 566 ms (selfie)
  maxAssetCacheWait: 283 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    ad.gt: 2
    adsafeprotected.com: 1
    btloader.com: 1
    cookielaw.org: 1
    cpx.to: 1
    duckduckgo.com: 2
    durationmedia.net: 1
    eyeota.net: 1
    fastly-insights.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    imrworldwide.com: 1
    liadm.com: 1
    nocookie.net: 1
    ntv.io: 1
    pubmatic.com: 1
    quantserve.com: 1
    rlcdn.com: 1
    scorecardresearch.com: 1
    wikia-services.com: 29
```
</details>

**Comment by u-RraaLL** [comment]
Hidden for me by EasyList.

> [x] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
>  easylist: 61379-1304, 6d.33m

Clearly, you didn't do what you were supposed to.

**Comment by thecutefinder** [comment]
Sorry about that.
