### ISSUE TITLE
Youtube Ads

### ISSUE THREAD

**Issue by validMyID** [uBlockOrigin/uAssets#16762]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello,
now (edge) i can see youtube ads at homepage and youtube ads at first time video play.

### A specific URL where the issue occurs.

https://www.youtube.com/

### Steps to Reproduce

1. open youtube
2. refer to https://i.vgy.me/42sXXu.png
3. if you play video (maybe first video in 3 hours... the first frame will play ads first....

### Expected behavior

1. back like before :D

### Actual behavior

ads

note: some of checklist option are mandatory, so i need to click it even un related. please ignore them

### uBO version

uBlock Origin 1.47.0

### Browser name and version

edge Version 110.0.1587.46 (Official build) (64-bit) stable

### Operating System and version

w10 22h2 19045.2546

**Comment by krystian3w** [comment]
Try open pages a few minutes after Edge loaded window.

https://github.com/gorhill/uBlock/wiki/Dashboard%3A-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded

Then you will rule out that it is a bug in the logic of Chromium operation for which there is no good solution.


---

In order not to lose both DOM trees, you can in uBo force update the filters, when it finishes, on the page "edge://extensions" turn off uBo for a few seconds and then turn it on to hide the ads in the form of a tile and a side banner (this may not work for ads in the player).

**Comment by validMyID** [comment]
> Try open pages a few minutes after Edge loaded window.
> 
> https://github.com/gorhill/uBlock/wiki/Dashboard%3A-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded
> 
> Then you will rule out that it is a bug in the logic of Chromium operation for which there is no good solution.
> 
> In order not to lose both DOM trees, you can in uBo force update the filters, when it finishes, on the page "`edge://extensions`" turn off uBo for a few seconds and then turn it on to hide the ads in the form of a tile and a side banner (this may not work for video ads in the player - these can simply bypass the current version of web filters and set-constant/json-prune in A/B testing).
> 
> If it works it will almost certainly be a problem that the site turned on before uBo could do something on Chromium.

i do that now... and no ads appears 
https://i.vgy.me/rj9AtM.png
if i enable this. it can help ?

**Comment by krystian3w** [comment]
Yes it's uBo option for some combat these logic with it in Chromium as you can't change habits:

- never open pages from a previous session immediately after opening a browser window

- never open links from other sources like outdated email or more modern messengers

but there is no guarantee that the option will always help to hide ads cosmetically and even so that the scriptlets under YouTube will manage to execute (to disable known pre-roll and mid-roll ads version).

**Comment by validMyID** [comment]
> Yes it's uBo option for some combat these logic with it in Chromium as you can't change habits:
> 
> * never open pages from a previous session immediately after opening a browser window
> * never open links from other sources like "outdated" e-mail (almost 44 years in use) or more modern messengers (when the browser window is not shown correctly about 30 seconds before)
> 
> but there is no guarantee that the option will always help to hide ads cosmetically and even so that the scriptlets under YouTube will manage to execute (to disable known pre-roll and mid-roll ads version).

understood sir.... thankyou for the clarification. at least. i have a little more knowledge how to prevent this in the future.
