### ISSUE TITLE
tcgplayer.com: breakage

### ISSUE THREAD

**Issue by BeetleG** [uBlockOrigin/uAssets#16760]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This site let's you enter a list of cards to buy, the whole entry element doesn't load while I have uBlock active for the site. When I disable uBlock it works again.

### URL(s) where the issue occurs.

`https://www.tcgplayer.com/massentry`

### uBO version

1.46.0

### Browser name and version

Chrome Version 110.0.5481.96 (Official Build) (64-bit)

### Settings

No changes

**Comment by mapx-** [comment]
add

`@@||cdn.optimizely.com/js/$script,domain=tcgplayer.com`

@ryanbr

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/1ac3c707ef5a102d47cb93f6935396c783e05026
