### ISSUE TITLE
ua.tribuna.com: breakage

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#16779]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ua.tribuna.com/`, `https://by.tribuna.com/`

### Category

breakage

### Description

The language selection does not work.
If you disable **uBlock filters - Privacy** and **EasyPrivacy**, the problem will be solved.

### Screenshot(s)

[Gif](https://imgur.com/QFxldh9)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 100842
  cosmetic: 128607
  scriptlet: 23533
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31602-26, 37m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1551-26, 37m
    https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 569-0, 37m
    fanboy-cookiemonster: 45564-387, 37m
    ublock-annoyances: 4832-53, 37m
  default: 
    user-filters: 3-0, never
    RUS-0: 39353-146, 37m
    easylist: 61867-77, 23m
    easyprivacy: 30975-1582, 5m
    ublock-abuse: 79-1, 37m
    ublock-badware: 4353-120, 37m
    ublock-filters: 32700-203, 37m
    ublock-privacy: 276-7, 2m
    ublock-quick-fixes: 167-22, 37m
    ublock-unbreak: 1897-50, 37m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 434 ms (selfie)
  maxAssetCacheWait: 810 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    doubleclick.net: 1
    facebook.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    trbna.com: 2
```
</details>

**Comment by iam-py-test** [comment]
Please test the following filter:
```adblock
@@||www.googletagmanager.com/gtm.js?id=$script,domain=ua.tribuna.com
```

**Comment by dportvine** [comment]
Works for me:
```adb
@@||googletagmanager.com/gtm.js$script,domain=by.tribuna.com|ua.tribuna.com
@@||google-analytics.com/analytics.js$script,domain=by.tribuna.com|ua.tribuna.com
```

**Comment by stephenhawk8054** [comment]
On my end, I have to allow 2 scripts:

```adb
@@||googletagmanager.com/gtm.js$script,domain=tribuna.com
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=tribuna.com
```

**Comment by iam-py-test** [comment]
Ok. Odd. Not sure why I didn't need the second one on my end

**Comment by dimisa-RUAdList** [comment]
@ryanbr
