### ISSUE TITLE
[nsfw] noodlemagazine.com: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#16775]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://noodlemagazine.com/download/-98962926_456247921?m=8d0d4f9e2c6a1532798d99d5bc651628`

### Category

ads

### Description

https://i.imgur.com/D74aat0.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 111
filterset (summary): 
  network: 93739
  cosmetic: 120095
  scriptlet: 23173
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7830-2, 1d.23h.46m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-4, 1d.23h.45m
    IDN-0: 5437-356, 1d.23h.39m
    fanboy-annoyance: 84122-363, 5d.7h.47m
    fanboy-cookiemonster: 45463-45462, 5d.7h.46m
    ublock-annoyances: 4829-78, 1d.23h.44m
  default: 
    user-filters: 10-0, never
    easylist: 61647-54, 1d.23h.48m
    easyprivacy: 30954-1175, 1d.23h.47m
    ublock-abuse: 77-0, 8d.2m
    ublock-badware: 4303-120, 1d.23h.43m
    ublock-filters: 31974-454, 1d.23h.41m
    ublock-privacy: 263-7, 7d.23h.58m
    ublock-quick-fixes: 326-25, 1h.14m
    ublock-unbreak: 1880-51, 1d.23h.40m
    urlhaus-1: 6076-0, 1h.15m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1258 ms (selfie)
  maxAssetCacheWait: 334 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 1
    huffson-delivery.com: 1
    realsrv.com: 2
```
</details>

**Comment by PedroHome18207** [comment]
@stephenhawk8054 same issue on their mirror/sister websites. Ads leftover in mobile version. Search any video and play it to test.

Mirror/sister websites:
```
https://tyler-brown.com/
https://ukdevilz.com/
https://mat6tube.com/
https://exporntoons.net/
https://actionviewphotography.com/
```

`noodlemagazine.com` filters could also be applied on mirror/sister websites.

**Comment by PedroHome18207** [comment]
@stephenhawk8054 @Yuki2718 @ghajini @MasterKia @JobcenterTycoon please help on this issue. 

Same issue on their mirror/sister websites of `noodlemagazine.com`. Ads leftover in **mobile version**. Search any video and play it to test.

Suggested filter: `tyler-brown.com,ukdevilz.com,mat6tube.com,exporntoons.net,actionviewphotography.com##div[style] > ins:upward(1)`

`noodlemagazine.com` filters could also be applied on mirror/sister websites?

Mirror/sister websites:
```
https://tyler-brown.com/
https://ukdevilz.com/
https://mat6tube.com/
https://exporntoons.net/
https://actionviewphotography.com/
```

**Comment by PedroHome18207** [comment]
@stephenhawk8054 I found these related filters. Are these filters obsolete? If not, they could cover their mirror/sister websites?
https://github.com/uBlockOrigin/uAssets/blob/e9fea02ce251a44c889841bc6f24520f7e6c8e58/filters/filters-2021.txt#L863
https://github.com/uBlockOrigin/uAssets/blob/e9fea02ce251a44c889841bc6f24520f7e6c8e58/filters/filters-2022.txt#L2148
**Likely update:**
`*$3p,script,xhr,denyallow=cloudflare.com|cloudflare.net|google.com|gstatic.com|googleapis.com|hcaptcha.com|jsdelivr.net|jwpcdn.com|pvvstream.pro|recaptcha.net|userapi.com,domain=actionviewphotography.com|exporntoons.net|mat6tube.com|noodlemagazine.com|tyler-brown.com|ukdevilz.com`

I added the domains `cloudflare.com`,`jwpcdn.com` because of these requests, but I may be wrong:
`https://ajax.cloudflare.com/cdn-cgi/scripts/04b3eb47/cloudflare-static/mirage2.min.js`
`https://ssl.p.jwpcdn.com/player/v/8.26.8/translations/es.json`

**Likely update:**
`actionviewphotography.com,exporntoons.net,mat6tube.com,noodlemagazine.com,tyler-brown.com,ukdevilz.com##+js(set, ads, undefined)`

**If these filters are obsolete or not applied, please ignore my suggestions, thanks.**

**Comment by huyszn** [comment]
`noodlemagazine.com/watch/-200487552_456239024`
There is an ad placeholder to the right of the video.
**NSFW** (https://github.com/uBlockOrigin/uAssets/assets/46979193/03cd80fb-e971-49b8-9e1b-d389b416e849)
Ads also occasionally appear over the ad placeholder.
**NSFW** (https://github.com/uBlockOrigin/uAssets/assets/46979193/cc2e6951-0e47-40bc-920a-260e31b1d9c7)

This also occurs in the other related domains.

**Comment by mapx-** [comment]
examples on the other pages ?

**Comment by huyszn** [comment]
The new filter breaks `noodlemagazine.com` by making the video disappear.
It looks like `mat6tube.com` is the only other domain that has the ad placeholder. The other domains don't have the ad placeholder.

**Comment by mapx-** [comment]
ok, blocking tbpot it's enough for that site too

**Comment by PedroHome18207** [comment]
@stephenhawk8054 please help on this issue.

Popup when clicking any video (**Firefox Mobile**).
Test URLs:
```
https://actionviewphotography.com/video/milf
https://exporntoons.net/video/milf
https://tyler-brown.com/video/milf
https://ukdevilz.com/video/milf
```

**Comment by Rachitidk** [comment]
Reopen this issue, popup appear when clicked on any button for first time.
https://noodlemagazine.com/video/samantha+flair#

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue
