### ISSUE TITLE
thumb9.net: detection

### ISSUE THREAD

**Issue by craticar** [uBlockOrigin/uAssets#16771]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://thumb9.net/adblock.html`

### Category

detection

### Description

I've disabled every filter I could think of that could be setting off the detection but it only works for a while then gets detected again. So now I'm reporting it. I've seen this issue reported last year. Every time the issue is patched, they update something that makes detection happen 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-02-15 210825](https://user-images.githubusercontent.com/79741887/219233457-f3308067-758a-4903-be03-4d24fb12778f.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 6900
  cosmetic: 8817
  scriptlet: 16928
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
    urlhaus-1: null
  default: 
    ublock-filters: 32687-36, 50m
filterset (user): [array of 37 redacted]
trustedset: 
  added: [array of 410 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 44 redacted]
hostRuleset: 
  added: [array of 40 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 16014 ms
  maxAssetCacheWait: 115 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give original link?

**Comment by craticar** [comment]
https://thumb9.net/the-pros-and-cons-of-compressed-work-schedules-and-how-to-implement-them/ it's a shortlink, it might not show unless you're passing it. The shortlinks are made using linkfly .me

**Comment by stephenhawk8054** [comment]
Can you give original short link? The link after redirection would not help anybody who wants to investigate the issue.

**Comment by craticar** [comment]
That is the original shortlink link, someone's posted similar on reddit's ubo where they got help. No one can see or post the original shortlink with its contents unless signed up to a faucet that has these shortlinks, if not, it directs to the blog because each shortlink generates a token linked to the faucet.

**Comment by stephenhawk8054** [comment]
`https://thumb9.net/the-pros-and-cons-of-compressed-work-schedules-and-how-to-implement-them/`

This is not original short link. I can't see any anti-adblock on the page, and without the beginning short link, it just shows as an article without redirecting to anything

![image](https://user-images.githubusercontent.com/66517106/219293852-7ae6f4e9-afa9-402d-a5cc-a5e8c6796565.png)

Which site did you use to generate the short links?

**Comment by craticar** [comment]
![Screenshot 2023-02-16 031507](https://user-images.githubusercontent.com/79741887/219294394-08f729b9-fe77-4fca-b56f-2b6bcfc12073.jpg)
Yes, that's what I'm talking about as this user explained, it will not be seen unless doing the shortlink itself, you can go to https://thumb9. net/ or https://shinbhu. net/ and it just takes you to the blog the only links that show are the detections https://allcryptoz.net/adblock.html and daily limit https://linksfly.me/limit.html

**Comment by stephenhawk8054** [comment]
Yes, at least give us a site or describe a way to generate the short links. Otherwise, how can we investigate?

**Comment by stephenhawk8054** [comment]
So I have registered in `firefaucet.win` site and go to `https://firefaucet.win/shortlinks`.

Which step should I do next to generate the `thumb9.net` link?

Screenshot:
https://user-images.githubusercontent.com/66517106/219297047-8f44119a-28de-4d88-b705-f01dba100142.png

**Comment by craticar** [comment]
Ah yes. autofaucet.org and firefaucet.win has these shortlinks. It can be generated there, detections sneakily happen at times

**Comment by craticar** [comment]
> So I have registered in `firefaucet.win` site and go to `https://firefaucet.win/shortlinks`.
> 
> Which step should I do next to generate the `thumb9.net` link?
> 
> Screenshot: https://user-images.githubusercontent.com/66517106/219297047-8f44119a-28de-4d88-b705-f01dba100142.png
sorry the linksfly shortlink

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
@@||banner.infoey.com/adbanner.png$image,domain=allcryptoz.net|crewbase.net|crewus.net|shinbhu.net|shinchu.net|thumb8.net|thumb9.net|topcryptoz.net|ultraten.net|uniqueten.net
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net##+js(nosiif, console)
```

**Comment by craticar** [comment]
Pasted into filters? doesn't work for me

**Comment by stephenhawk8054** [comment]
Paste into `My filters` pane, click `Apply changes`.

It works for me. Screenshot: https://user-images.githubusercontent.com/66517106/219305791-b217eedb-3f13-4d44-88dc-7a4a111ac1bf.png

Test again with resetting to default ublock settings, force update the filter lists and add the above filter. Also check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

This is the link I used to test: `https://linksfly.me/BXgEFu`

**Comment by craticar** [comment]
I can get it to work with easy list off for me with the filter, I sent the filter to others to trst, and it worked until step 3 for some, another it gets detected right away,

**Comment by craticar** [comment]
![331414665_876887090252759_3552056103723160572_n (1)](https://user-images.githubusercontent.com/79741887/219320641-aa3adf6d-efd9-4bfe-bbe9-c1f6deb1911b.jpg)
Screenshot of vids they sent. Works somewhat for me and others, still gets detected at times, clearing the cookies and  restarting the browser helps. It's the only fix that works enough for now, so thanks.

**Comment by Sandor-Helper** [comment]
Is it possible to make the buttons to continue at each step visible? Similarly, as it is immediately visible in the 3rd step.

![image_2023_02_20T08_44_04_589Z](https://user-images.githubusercontent.com/31479044/220063609-0d8cfecc-08d6-43db-ba46-0e6e894e45c4.png)
