### ISSUE TITLE
huya.com: ads

### ISSUE THREAD

**Issue by Heporis** [uBlockOrigin/uAssets#16777]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There is advertising when the broadcaster is offline.
The advertising disappers after I click X. 

### URL(s) where the issue occurs.

`https://www.huya.com/yuno1202`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/51895154/219362595-97da9d7e-2a55-4b3c-8350-ce25c0779367.png)

**After clicking X, it disappers**

![image](https://user-images.githubusercontent.com/51895154/219363162-baa1072d-c86a-40d6-aac0-a3cf10ac8274.png)

### uBO version

1.47.0

### Browser name and version

edge chromium 108

### Settings

none

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||cdnws.api.huya.com^$xhr,1p
```

**Comment by mapx-** [comment]
@cjx82630

**Comment by Heporis** [comment]
> Can you test this filter?
> 
> ```
> ||cdnws.api.huya.com^$xhr,1p
> ```

It doesn't work.
![image](https://user-images.githubusercontent.com/51895154/219664826-92818ef9-0dd7-4b43-bfc0-e3cf0b5c74ce.png)

**Comment by cjx82630** [comment]
@mapx- It's self-promotion, It will be fixed by [CJX's Annoyance List](https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt)

**Comment by Heporis** [comment]
> @mapx- It's self-promotion, It will be fixed by [CJX's Annoyance List](https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt)

The new video AD comes.
![image](https://user-images.githubusercontent.com/51895154/229341203-83700ce6-9389-4220-b76c-c3419892dfc2.png)

**Comment by mapx-** [comment]
@Heporis report directly here:
https://github.com/cjx82630/cjxlist/issues
