### ISSUE TITLE
app.prodia.com: breakage

### ISSUE THREAD

**Issue by NintendoManiac64** [uBlockOrigin/uAssets#16772]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.prodia.com/`

### Category

breakage

### Description

All of a few minutes ago, the site worked fine and then... it no longer did.  Generated images always display the "succeeded" and the spinning loading animation but do not show any actual images unless you disable uBlock Origin at which point images will successfully generate without issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![on](https://user-images.githubusercontent.com/11896003/219235685-21444c90-3586-457e-b964-6efd69234c83.png)

![off](https://user-images.githubusercontent.com/11896003/219235706-7a957962-6e29-41cd-8fc7-bcdcd3bc3db9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0 
Firefox: 108 
filterset (summary):   
  network: 119678  
  cosmetic: 38527  
  scriptlet: 16958  
  html: 884 
listset (total-discarded, last-updated):   
  default:   
    user-filters: 0-0, never  
    ublock-filters: 32791-60, 2d.3h.57m  
    ublock-badware: 4337-5, 2d.3h.56m  
    ublock-privacy: 323-0, 11m  
    ublock-abuse: 79-0, 12m  
    ublock-unbreak: 1889-3, 2d.2h.7m  
    ublock-quick-fixes: 349-0, 21m  
    easylist: 61522-640, 1d.23h.30m  
    adguard-spyware-url: 899-4, 2d.2h.6m  
    easyprivacy: 30952-1743, 1d.19h.29m  
    urlhaus-1: 6076-0, 20m  
    curben-phishing: 33812-9, 22m  
    plowe-0: 3668-2, 8d.2h.7m  
    LegitimateURLShortener: 2122-132, 19m 
filterset (user):  empty  
trustedset:   
  added: [array of 2 redacted]  
modifiedUserSettings:   
  advancedUserEnabled: true 
  modifiedHiddenSettings:  none  
supportStats:   
  allReadyAfter: 384 ms (selfie)   
  maxAssetCacheWait: 217 ms 
popupPanel:   
  blocked: 4  
  blockedDetails:   
    googletagmanager.com: 2  
    storjshare.io: 2
```

</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by NintendoManiac64** [comment]
I mean, I already tried that considering that suggestion is listed in the initial checklist...

It may or may not be worth mentioning that, as shown in the screenshots, I'm actually using LibreWolf rather than Firefox which actually comes with uBlock Origin installed by default.  This is a key point because there's a non-zero chance that LibreWolf may be using custom uBlock Origin settings as their defaults, but I have no idea if this is the case or not - all I know is, I haven't altered the settings for it at all since LibreWolf is actually by sort of "plan B" browser (https://app.prodia.com/ doesn't work in my primary browser).

**Comment by stephenhawk8054** [comment]
Librewolf additionally enables these 3 lists when first install comparing to uBO's default lists

```
AdGuard URL Tracking Protection
➗ Actually Legitimate URL Shortener Tool
Phishing URL Blocklist
```

You should report it to `https://gitlab.com/malware-filter/phishing-filter#phishing-url-blocklist` or add this to your custom list

```adb
@@||link.storjshare.io^$xhr,domain=app.prodia.com
```
