### ISSUE TITLE
bleachernation.com: breakage

### ISSUE THREAD

**Issue by Waspo98** [uBlockOrigin/uAssets#16787]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bleachernation.com/`

### Category

breakage

### Description

The menu/navigation bar at the top is gone (both desktop and mobile)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox Mobile: 110
filterset (summary): 
  network: 84612
  cosmetic: 28238
  scriptlet: 16796
  html: 864
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32413-297, 3d.19h.10m
    ublock-badware: 4281-5, 3d.19h.9m
    ublock-privacy: 307-1, 3d.19h.8m
    ublock-abuse: 77-0, 3d.19h.7m
    ublock-unbreak: 1894-2, 3d.19h.6m
    ublock-quick-fixes: 398-0, 19h.8m
    adguard-mobile: 8786-170, 3d.21h.53m
    easylist: 61625-17580, 1d.16h.46m
    easyprivacy: 30954-1752, 1d.16h.45m
    urlhaus-1: 6076-0, 19h.7m
    plowe-0: 3680-2, 7d.22h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 265 ms (selfie)
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    bleachernation.com: 2
    amazon-adsystem.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    omappapi.com: 1
    rubiconproject.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`bleachernation.com##.code-block`
