### ISSUE TITLE
Qualtrics.com completely blocked

### ISSUE THREAD

**Issue by morgana-qualtrics** [uBlockOrigin/uAssets#1678]
### URL(s) where the issue occurs

`https://www.qualtrics.com/`

### Describe the issue

Our customers recently notified us that the entire qualtrics.com domain is being blocked by uBlock due to a listing on the Peter Lowe's Ad and Tracking Server List. Although one of our products, Site Intercept, does provide the ability to present pop-ups to customers for the purpose of gathering feedback, the listing is broad and affects our corporate website, Employee Engagement products and Surveys which are used by many Fortune 500 companies. For example, Google `https://support.google.com/faqs/answer/6377139?hl=en`

The Qualtrics platform is used to allow our customers to gather feedback 
usually in the form of surveys - `https://www.qualtrics.com/customers/`. Privacy is a priority for Qualtrics and we are compliant with major frameworks such as Privacy Shield.

Could you provide us some recommendations for a path forward to help our customers? Ideally we would like our domain white-listed.

### Screenshot(s)

Going to the qualtrics.com website should demonstrate the issue adequately.

### Versions

- Browser/version: Any with ublock origin extension installed
- uBlock Origin version: varies by customer. Internally we run the latest for our testing purposes.

### Settings

- N/A

### Notes

We've confirmed on our end that it's an issue. We first appeared on the list on Sunday, March 4th. Customer complaints soon followed.

**Comment by okiehsch** [comment]
I [disabled](https://github.com/uBlockOrigin/uAssets/commit/ab2e05dd60deb521d9c950f8dea1aba8d9ad7a5a) all 1st-party blocking of `qualtrics.com` requests, so your website should work fine if you update the `uBO-unbreak` list or wait for it to auto-update.

**Comment by schristiaens** [comment]
This whitelist entry appears to have been removed, breaking our site once again. Can we get re-added?
