### ISSUE TITLE
tweakers.net: detection

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#16782]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tweakers.net/reviews/10866/2/is-matter-de-toekomst-van-smarthome-alles-wat-je-moet-weten-over-deze-standaard-hoe-werkt-matter.html`

### Category

detection

### Description

One of the EasyDutch list maintainers here. 

We have ongoing problems with `tweakers.net`. They're doing everything to detect adblock. 
Now, they are using the blocked `aa.tweakers.nl` domain to detect. 

We can not allow that domain, as is shows ads. But the problem is not only a notice *(as we can block it)* but without whitelisting `aa.tweakers.nl` it is impossible to read parts of their articles.

We cannot come up with a solution. Do you have?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![afbeelding](https://user-images.githubusercontent.com/81161435/219410472-31729888-ab4c-4d19-ada8-a61da2778095.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 110
filterset (summary): 
  network: 72922
  cosmetic: 40488
  scriptlet: 16857
  html: 826
listset (total-discarded, last-updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-quick-fixes: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2990-10, 3d.8h.27m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal List (uBo).txt: 2316-0, 3d.8h.28m
  default: 
    user-filters: 233-0, never
    ublock-filters: 32792-81, 2d.4h.50m
    ublock-unbreak: 1892-7, 2d.4h.49m
    easylist: 61530-201, 2d.8h.53m
    easyprivacy: 30952-1225, 2d.8h.52m
filterset (user): [array of 177 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
hostRuleset: 
  added: [array of 8 redacted]
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  popupPanelLockedSections: 35
  popupPanelHeightMode: 1
  uiStyles: --popup-main-min-width: 168px; --popup-gap: 0.5em; --popup-gap-thin: calc(var(--popup-gap)/9); --popup-power-ink: rgb(0,110,254); --popup-ruleset-tool-surface: rgb(240,190,64); --popup-ruleset-tool-surface-hover: rgb(240,190,64); --popup-toolbar-surface: rgb(226,226,229); --popup-toolbar-surface-hover: rgb(32 18 58 / 40%); --popup-icon-x-ink: rgb(226,40,80);
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 3250 ms (selfie)
  maxAssetCacheWait: 1134 ms
  unsuspendAfter: 2534 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    tweakers.nl: 2
    usabilla.com: 1
```
</details>

**Comment by okiehsch** [comment]
Why not simply adding
`@@||tweakers.nl/json$xhr,domain=tweakers.net`
?

**Comment by JohnyP36** [comment]
@okiehsch I will add it for now. 
We found the problem to be in the file `tweakers.net/x/build/frontpage.*.js`. So we are looking to block or redirect that part of the script that causes the notice without breaking the site.

**Comment by okiehsch** [comment]
If you don't want to allow even one request add
`tweakers.net##+js(aeld, , adblock)`

**Comment by JohnyP36** [comment]
Thanks @okiehsch for thinking along with us.
