### ISSUE TITLE
ftb.ca.gov: breakage

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#16786]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When opening one of the wait time dropdown menus, the website will say an error has occurred. After this, no other wait time menus can be opened.

### URL(s) where the issue occurs.

`https://www.ftb.ca.gov/help/time-frames/#/contact`

### Screenshot(s)

https://user-images.githubusercontent.com/54487525/219481477-36a8a390-a706-4b82-a34e-3ce1f0cc63c4.mov

### Notes

Works when the page is whitelisted.

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 109
filterset (summary): 
  network: 83476
  cosmetic: 38819
  scriptlet: 17157
  html: 891
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33533-57, now
    ublock-badware: 4357-5, now
    ublock-privacy: 323-0, now
    ublock-abuse: 79-0, now
    ublock-unbreak: 1906-2, now
    ublock-quick-fixes: 165-0, now
    easylist: 61867-654, now
    easyprivacy: 30976-1745, now
    urlhaus-1: 6103-0, now
    plowe-0: 3680-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1533 ms
  maxAssetCacheWait: 975 ms
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||ftb.ca.gov/js/webtrends.min.js$script,1p`
