### ISSUE TITLE
idrive.com: breakage

### ISSUE THREAD

**Issue by chrisbaber** [uBlockOrigin/uAssets#16783]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.idrive.com/idrive/home/account.html`

### Category

breakage

### Description

clicking items on the tree should expand to show sub-items, but does not.  Turning off uBlock for the whole website resolves this issue.  I tried enabling 'all' from the rules list, both locally and globally but this did not resolve the issue.  Only turning off the plugin fixes the issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 130486
  cosmetic: 183392
  scriptlet: 24323
  html: 1032
listset (total-discarded, last-updated): 
  added: 
    adguard-spyware-url: 920-4, 1h.14m
    block-lan: 44-0, 4d.1h.43m
    curben-phishing: 33806-8, 1h.9m
    curben-pup: 193-0, 1h.8m
    adguard-annoyance: 64083-4914, 1h.13m
    adguard-social: 19916-1035, 1h.12m
    fanboy-thirdparty_social: 68-0, 6d.14h.54m
    fanboy-annoyance: 84076-70053, 6d.14h.53m
    fanboy-cookiemonster: 45431-240, 6d.14h.52m
    fanboy-social: 22776-26, 5d.10h.25m
    ublock-annoyances: 4788-4, 1h.11m
  default: 
    user-filters: 28-2, never
    ublock-filters: 32948-213, 1h.17m
    ublock-badware: 4357-5, 1h.16m
    ublock-privacy: 310-0, 8d.4h.53m
    ublock-abuse: 77-0, 8d.4h.52m
    ublock-unbreak: 1898-3, 1h.15m
    ublock-quick-fixes: 349-0, 1h.10m
    easylist: 61530-666, 2d.19h.23m
    easyprivacy: 30952-1749, 2d.19h.22m
    urlhaus-1: 6103-0, 1h.7m
    plowe-0: 3680-2, 7d.17h.17m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 68 redacted]
  removed: 
    about-scheme
hostRuleset: 
  added: [array of 11 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1383 ms (selfie)
  maxAssetCacheWait: 648 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    stripe.com: 14
```
</details>

**Comment by mapx-** [comment]
add

`idrive.com#@#.socialBlock`

@ryanbr
