### ISSUE TITLE
rawconfessions.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#1679]
**MGID** ads are loaded through **_piguiqproxy.com_** and **_amgload.net_** on `https://www.rawconfessions.com`.
Blocking the domains breaks the website. 

This filter works in stopping the ads `||piguiqproxy.com^$xmlhttprequest,redirect=nooptext,domain=rawconfessions.com`
(Based on this https://github.com/uBlockOrigin/uAssets/commit/25bb6a392d71580efcac27f4d017324da69ea2d4)

_amgload.net_ should probably be nooped as well.

**Error URL:** `https://www.rawconfessions.com/confession/show/mick-howard-and-shelly-thornhill`

**Related:** https://github.com/uBlockOrigin/uAssets/issues/602

_**Note:** Using 1.15.2 on Chrome 65 with the default filters and settings._

**Comment by mapx-** [comment]
not sure for firefox (I get a "`sorry`" page)

**Comment by uBlock-user** [comment]
`rawconfessions.com##script:inject(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)`

They will keep adding new random domains to the scripts and the filters will only increase. This one kills in it one fell swoop.
