### ISSUE TITLE
bing.com: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#16791]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bing.com/images/search?q=ps4&qs=n&form=QBIR&sp=-1&pq=ps4&sc=10-3&cvid=45572E398B9C4924BE9C172720D05EF7&ghsh=0&ghacc=0&first=1`

### Category

ads

### Description

ads showing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/81616288/219593092-a31bd95b-88d3-4426-a3d2-610bce48e795.jpeg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 85682
  cosmetic: 43121
  scriptlet: 17163
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6541-0, 7h.15m
    easylist: 61904-53, 7h.15m
    easyprivacy: 30977-1182, 7h.15m
    plowe-0: 3680-904, 7h.15m
    ublock-abuse: 79-0, 7h.15m
    ublock-badware: 4353-121, 7h.15m
    ublock-filters: 32703-162, 7h.15m
    ublock-privacy: 276-1, 7h.15m
    ublock-quick-fixes: 161-22, 7h.15m
    ublock-unbreak: 1899-48, 7h.15m
    urlhaus-1: 6067-0, 7h.15m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 28262 ms (selfie)
  maxAssetCacheWait: 275 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    bing.com: 21
```
</details>

**Comment by garry-ut99** [comment]
I get no ads, except only an ads header: [screenshoot](https://user-images.githubusercontent.com/72945564/219612688-989208ac-7814-41ac-9c71-a9b0c67367de.png), after enabling AdGuard base, the header is hidden, they use EasyList compatible filter: `bing.com###b_content > div#pole > div[class="ra_car_block ra_pole"] > div.ra_car_container`.

Possible reasons you get ads:

- your uBO loads too slowly: `allReadyAfter: 28262 ms (selfie)` see: 
https://github.com/uBlockOrigin/uBlock-issues/issues/1865
- you use Opera and you didn't enable "allow extensions to work in search engines" option:
https://forums.opera.com/topic/60194/solved-extensions-don-t-work-in-search-engines

**Comment by mapx-** [comment]
@i8cczshd 

test

```
bing.com##[mv-data^="Ads"]:has([href*="aclick"]):upward(.b_overlay)
bing.com###pole:has-text(Ads)
bing.com##.ra_car_label:has-text(Ads)
```

**Comment by garry-ut99** [comment]
Interesting, I wonder if you are sure that it was the filters that helped and not the simple fact that this time you might have visited Bing **after** uBO was ready (`allReadyAfter`) and not **before** it was ready (like in the previous case), to check it, you can whitelist the current fix and visit Bing again, (make sure you don't visit Bing immediately after opening browser / enabling uBO, in that case try to wait 40 secs to let uBO be ready):
```
bing.com#@#[mv-data^="Ads"]:has([href*="aclick"]):upward(.b_overlay)
bing.com#@##pole:has-text(/Ads|Anzeigen/)
bing.com#@#.ra_car_label:has-text(/Ads|Anzeigen/)
```
