### ISSUE TITLE
ytmp3eu.net: ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#16796]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ytmp3eu.net/en45/`

### Category

ads

### Description

Can this be blocked with [untrusted].js or [untrusted].asp random chars filter?
![image](https://user-images.githubusercontent.com/91396482/219686078-0425799b-5be5-4b1d-8ed9-b2949c6ea73f.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 110
filterset (summary): 
  network: 75066
  cosmetic: 40004
  scriptlet: 16939
  html: 885
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1374-0, 15h.31m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 3d.5h.46m
  default: 
    user-filters: 1545-11, never
    ublock-filters: 32937-168, 2d.2h.48m
    ublock-badware: 4337-5, 2d.2h.47m
    ublock-privacy: 323-0, 2d.2h.46m
    ublock-abuse: 79-0, 2d.2h.45m
    ublock-unbreak: 1895-2, 2d.2h.44m
    ublock-quick-fixes: 165-0, 15h.32m
    easylist: 61816-206, 1d.18h.7m
    easyprivacy: 30952-2107, 4d.5h.28m
filterset (user): [array of 570 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 311 ms (selfie)
  maxAssetCacheWait: 138 ms
  unsuspendAfter: 125 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    adsco.re: 1
    d3mzokty951c5w.cloudfront.net: 1
    displayvertising.com: 1
```
</details>

**Comment by iam-py-test** [comment]
> ```yml
> removed: 
>    urlhaus-1: null
>    plowe-0: null
> ```

You have disabled Peter Lowe's list and URLHaus.

**Comment by krystian3w** [comment]
You mean both block at all or report to both due uAssets rejects?

**Comment by iam-py-test** [comment]
Neither (I can reproduce popups, should have put that). Still not recommended by the uBo people
