### ISSUE TITLE
visitacity.com: ads

### ISSUE THREAD

**Issue by makislog** [uBlockOrigin/uAssets#16794]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.visitacity.com/itineraries-user?id=3aca5a3a-f9ca-48b4-a6eb-6c97e7f070c6&day=1`

### Category

ads

### Description

in-text ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 90462
  cosmetic: 113906
  scriptlet: 18879
  html: 0
listset (total-discarded, last-updated): 
  added: 
    GRC-0: 995-0, 21h.45m
    fanboy-annoyance: 84075-360, 8d.2h.19m
  default: 
    user-filters: 55-1, never
    easylist: 61530-50, 4d.1h.37m
    easyprivacy: 30952-1173, 4d.1h.38m
    plowe-0: 3680-903, 17h.42m
    ublock-abuse: 79-0, 21h.50m
    ublock-badware: 4343-120, 21h.46m
    ublock-filters: 32129-165, 21h.48m
    ublock-privacy: 276-8, 21h.49m
    ublock-quick-fixes: 167-21, 21h.43m
    ublock-unbreak: 1887-50, 21h.47m
    urlhaus-1: 6103-0, 21h.44m
filterset (user): [array of 55 redacted]
trustedset: 
  added: [array of 45 redacted]
  removed: 
    chrome-scheme
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4622 ms (selfie)
  maxAssetCacheWait: 326 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    ads-twitter.com: 1
    bing.com: 1
    facebook.net: 1
    google-analytics.com: 1
    googleadservices.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by iam-py-test** [comment]
> - [X]  I did not answer truthfully to ALL the above checkpoints.

Please don't just check the checkboxes to get the issue to submit. Your diagnostic information shows some lists haven't been updated in 4 days. Please click "purge all caches" and then "update now" (or the equivalent in other languages).

What in-text ads are you seeing? These?
![image](https://user-images.githubusercontent.com/84232764/219797287-e90adaa4-05ef-4257-b7b5-ba44776d9ab7.png)

**Comment by makislog** [comment]
Hey, I didn't notice the "not" part! I made a purge and list update just before submitting. Is it possible that the report shows that my lists are outdated because I created the report first? Ads still persist even after the update, but I might be missing something. 

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 17, 2023 at 23:30, ***@***.***> wrote:   


   
   -  I did not answer truthfully to ALL the above checkpoints.


Please don't just check the checkboxes to get the issue to submit. Your diagnostic information shows some lists haven't been updated in 4 days. Please click "purge all caches" and then "update now" (or the equivalent in other languages).

What in-text ads are you seeing? These?

**Comment by iam-py-test** [comment]
> Is it possible that the report shows that my lists are outdated because I created the report first? 

That's probably it. I'm still not seeing any ads, but that could just be an issue on my end.

**Comment by mapx-** [comment]
I guess it's self-promo

- go to `https://www.visitacity.com/en/istanbul/activities/cultural--theme-tours`
- all the trip proposals there will be open on the same `viator.com` site which seems to be related to `visitacity`
