### ISSUE TITLE
marketwatch.com: ads

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#16797]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Unblocked WSJ ads. Not sure if it counts as self-promotion?

### URL(s) where the issue occurs.

`https://www.marketwatch.com/`

### uBO version

1.46.0

### Browser name and version

Chrome 110

### Settings

N/A

**Comment by mapx-** [comment]
add & test:

`||d2zue0pgsssbc6.cloudfront.net/a.txt$xhr,domain=marketwatch.com`

![image](https://user-images.githubusercontent.com/10303732/219804272-1e16183e-7c14-4e52-bb00-4171b1e1a37d.png)

**Comment by ryanbr** [comment]
That text seems relevant to the site, Would be overblocking if we added that,
