### ISSUE TITLE
blog.coinsvalue.net: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#16793]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.coinsvalue.net/detected.html`

### Category

detection

### Description

Ad blocker detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83332
  cosmetic: 38616
  scriptlet: 16940
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61904-47, now
    easyprivacy: 30981-1173, now
    plowe-0: 3680-903, now
    ublock-abuse: 79-0, now
    ublock-badware: 4353-121, now
    ublock-filters: 32112-139, now
    ublock-privacy: 276-1, now
    ublock-quick-fixes: 161-22, now
    ublock-unbreak: 1899-46, now
    urlhaus-1: 6067-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7589 ms
  maxAssetCacheWait: 1494 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    d3u598arehftfk.cloudfront.net: 1
    doubleclick.net: 1
    rebindskayoes.com: 1
```
</details>

**Comment by ghajini** [comment]
continue here https://github.com/uBlockOrigin/uAssets/issues/16317
