### ISSUE TITLE
indiatimes.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#168]
Getting the anti adb warning on http://timesofindia.indiatimes.com/ with the latest uBlock filters.

**Error URL:** http://timesofindia.indiatimes.com/city/jaipur/University-to-grants-PhD-to-clueless-agriculture-minister-Prabhu-Lal-Saini/articleshow/54908176.cms

uBlock version 1.9.10

**Comment by gorhill** [comment]
No anti-blocker warning here, using default filter lists.

Investigate why this happens on your side.

**Comment by gotitbro** [comment]
Ah, it was the **AdsBypasser** script I was running in **Tampermonkey**. But I can't really tell what's causing the issue in the script, can you maybe help me with pinpointing the issue?

Thanks

**Comment by IDKwhattoputhere** [comment]
Makes more sense if you report it to the devs: https://github.com/adsbypasser/adsbypasser

**Comment by gotitbro** [comment]
> Makes more sense if you report it to the devs: https://github.com/adsbypasser/adsbypasser

But I can't really find what the issue is to report it.

**Comment by IDKwhattoputhere** [comment]
Isn't the issue that it causes the anti-adblock to be triggered?

**Comment by gotitbro** [comment]
@okiehsch I am getting an anti adb warning on `http://ahmedabadmirror.indiatimes.com`. This is probably due to the fact because of me using this filter: `||indiatimes.com^$generichide,important` (Too many ad spaces without this). Can you help me with this?

**Error URL:** 
`http://ahmedabadmirror.indiatimes.com/news/india/khichdis-global-moment/articleshow/61511280.cms`

They use JS to detect whether `##div[id^="div-gpt-ad"]` has been hidden. Could be this js that is embedded on the page: https://ctrlv.it/javascript/59237/4263530783

**Comment by gorhill** [comment]
Try:

    indiatimes.com##div[id^="div-gpt-ad"]:style(max-height: 1px !important)

**Comment by gotitbro** [comment]
@gorhill Yes that works as well. the comments section seems to be broken as well it keeps on loading even with default filters and settings. Loads fine when uBO is disabled not sure what is causing that.

Error URL: 
http://ahmedabadmirror.indiatimes.com/news/india/khichdis-global-moment/articleshow/61511280.cms

**Comment by gorhill** [comment]
Comments show fine for me on pages where there are comments. Using default settings.

**Comment by gotitbro** [comment]
@gorhill Okay it was an issue on my side completely disabling uBO and re-enabling it fixed the above issue.

A bit off topic but it would be really nice to have a sort of "profile manager" in uBO. Returning to the default settings and back again is much time consuming and hectic also profiles would be nice to switch between full privacy mode (say I have all the social lists and privacy lists enabled in this one) and a normal adblocker mode.

Personally for me it would make it easier to switch between default mode and my own settings to see what is causing the issue.

**Comment by gotitbro** [comment]
@okiehsch The generichide exclusion still shows some ad spaces and elements. Any way to stop the adblock detection on this website while still using generichide (`||indiatimes.com^$generichide,important`).

**Error URL:** 
`http://ahmedabadmirror.indiatimes.com/news/india/khichdis-global-moment/articleshow/61511280.cms`

**Comment by okiehsch** [comment]
`||ahmedabadmirror.indiatimes.com/detector.cms$script,first-party,important`

**Comment by gotitbro** [comment]
@okiehsch Thanks that works. Wonder why EasyList allows it, many EasyList filters for this domain are redundant now.

**Comment by gotitbro** [comment]
@okiehsch The next article does not autoload when scrolling down on `https://recipes.timesofindia.com`. It loads fine when uBO is disabled.

**Error URL:** `https://recipes.timesofindia.com/recipes/aloo-gobi/rs52603313.cms`

_**Note:** Using uBO 1.14.20 on Chrome 62 with the default filters and settings._

**Comment by mapx-** [comment]
add
`@@||recipes.timesofindia.com/*ads.cms$script`

**Comment by gotitbro** [comment]
@mapx- That works thanks. Should/Would this be added to the filter list?

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/35e10bc32a9ab7e6ebadd1f24ac6404da4579bbf

**Comment by ghajini** [comment]
***Breakage*** related to `indiatimes.com` affiliated sites
1.
a]
videos broken=

`https://punemirror.indiatimes.com/videos/sectionhomelist/sudhir-hanumant-pundekars-dream-of-building-a-sports-complex-gets-fighting-chance/videoshow/72055551.cms`

b]
horoscope today video widget broken
 
`https://punemirror.indiatimes.com`

2.

a]
Live tv [timesnow/et now,mirror now,zoom] broken

`https://maharashtratimes.indiatimes.com/livetv.cms`

b]
widget video broken here

`https://maharashtratimes.indiatimes.com/`

***screenshot***=
`https://user-images.githubusercontent.com/20338483/68891969-f4d69f00-0747-11ea-8401-ab7d6071784a.png`

c]
comments dock window doesn't load more comments

`https://maharashtratimes.indiatimes.com/maharashtra/mumbai-news/bjp-leader-devendra-fadnavis-after-bjp-meeting-in-mumbai-on-maharashtra-govt-formation/articleshow/72060879.cms`

***screenshot***=
i}ubo enabled=
`https://user-images.githubusercontent.com/20338483/68892258-8fcf7900-0748-11ea-8a2b-b3ba537d07ac.png`

ii)ubo disabled=
`https://user-images.githubusercontent.com/20338483/68892283-a675d000-0748-11ea-88de-0b5c001fda20.png`


3.
a]
horoscope today widget video
 broken 
`https://ahmedabadmirror.indiatimes.com`

***screenshot***
=
`https://user-images.githubusercontent.com/20338483/68892401-ef2d8900-0748-11ea-8282-102ccbad619c.png`


b]
videos broken here

`https://ahmedabadmirror.indiatimes.com/videos/sectionhomelist/horoscope-today-november-15-2019-here-are-the-astrological-predictions-for-your-zodiac-sign/videoshow/72061394.cms`

4.

a]

lower right side widget video broken
`https://bangaloremirror.indiatimes.com`

***screenshot***=
`https://user-images.githubusercontent.com/20338483/68892643-71b64880-0749-11ea-8ebb-01043e16f7fe.png`

b]videos broken here

`https://bangaloremirror.indiatimes.com/videos/sectionhomelist/bangalore-mirror-news-wrap-here-are-the-top-5-stories-of-14th-november-2019/videoshow/72055336.cms`

***screenshot***=
`https://user-images.githubusercontent.com/20338483/68892668-82ff5500-0749-11ea-9c80-67e8e1fd7aee.png`

5.

a]
lower right widget video broken

`https://eisamay.indiatimes.com`
 
b]
live tv broken

`https://eisamay.indiatimes.com/livetv/16682993.cms`

6]
video broken here & widget video also broken

`https://tamil.samayam.com/news-video/news/tennessee-court-judge-held-the-baby-in-oath-function/videoshow/72058235.cms`

**Comment by mapx-** [comment]
2 c => comments I have no clue what to do to reproduce your issue

**Comment by ghajini** [comment]
> 2 c => comments => I have no clue what to do to reproduce your issue

Its fixed somehow (it's about comments at the end of article in language 'Marathi')...👍👍👍

**Comment by ghajini** [comment]
Link=

`https://maharashtratimes.com/maharashtra/aurangabad-marathwada-news/aurangabad/shiv-sena-leader-chandrakant-khaire-warns-arnab-goswami/articleshow/79191397.cms`

### Describe your issue=

Some ads notably Amazon promotions,Amazon app, empty ads placeholders, embedded ads etc

###platform=

Firefox android nightly as well as stable
Ublock origin 1.30.6

### Screenshot=
```
https://user-images.githubusercontent.com/20338483/98955716-3b123a00-2525-11eb-8cbb-51f80a5f766f.jpg

https://user-images.githubusercontent.com/20338483/98955762-4b2a1980-2525-11eb-8e36-91b3c43d11e8.jpg

https://user-images.githubusercontent.com/20338483/98955806-59783580-2525-11eb-90d3-30ca7cc3cca4.jpg

https://user-images.githubusercontent.com/20338483/98955860-6c8b0580-2525-11eb-95ab-e165f010d3e6.jpg

https://user-images.githubusercontent.com/20338483/98955907-79a7f480-2525-11eb-8db6-c71c2b1480e7.jpg
```
### Fix as per i see=
```
maharashtratimes.com##.float-amz.btn_openinapp
maharashtratimes.com##.ad1
maharashtratimes.com##.colombia
maharashtratimes.com##[href^="https://trk.clmbtrck.in/click"]
maharashtratimes.com##[href^="https://maharashtratimes.com/pwafeeds/affiliate_amazon.cms"]
/pwafeeds/amazon_wdt_tas.cms
```

**Comment by mapx-** [comment]
maybe

```
maharashtratimes.com##[class^="ad"]
maharashtratimes.com##.colombia
maharashtratimes.com##.pwa-deals
maharashtratimes.com##.banner
||navbharattimes.indiatimes.com/pwafeeds/$frame
```

**Comment by ghajini** [comment]
> maybe
> 
> ```
> maharashtratimes.com##[class^="ad"]
> maharashtratimes.com##.colombia
> maharashtratimes.com##.pwa-deals
> maharashtratimes.com##.banner
> ||navbharattimes.indiatimes.com/pwafeeds/$frame
> ```

It doesn't addresses some ads in Marathi language as per above screenshots

**Comment by ryanbr** [comment]
Easylist is an english list @ghajini

**Comment by ghajini** [comment]
There's no special list for these languages(over 100+) as per I know, filters get added in Easylist only

**Comment by ghajini** [comment]
whom to contact @gorhill i tried everything ,everyone to ping

**Comment by mapx-** [comment]
added

**Comment by ghajini** [comment]
thank you @mapx- 
@ryanbr  i do know easylist is english but there are lot of filters for indian websites in easylist
iam also aware of `https://github.com/mediumkreation/IndianList/tree/master/IndianList` that is recommended by abp but that list literally funny which blocks youtube embeds and i find that inconclusive ,barely maintained ,content/filters are not robust,doesn't address major ad trackers on indian websites, why is even that recoommended by abp guys?

**Comment by gorhill** [comment]
Well maybe we should kick-start a uBO list for Indian languages -- India is such a populous country surely eventually some people from India will volunteer to maintain that list? I fear that to keep burdening long time maintainers is just going to cause them to eventually to lose motivation -- we need more skilled volunteers, not more burden on existing volunteers.

**Comment by ghajini** [comment]
yes that's why i first pinged Alex-302 from adguard because `adguard mobile ads `filter is default in ublock origin for firefox android

yes volunteer who knows many languages of india(100+) (mainly hindi,english,marathi,gujrati,bengali,tamil,kannada,telugu etc) to add adfilters

**Comment by mapx-** [comment]
@ghajini do you know this list:
https://easylist-downloads.adblockplus.org/indianlist.txt

listed here:
https://adblockplus.org/en/subscriptions

**Comment by ghajini** [comment]
yes i just mentioned it above `https://github.com/uBlockOrigin/uAssets/issues/168#issuecomment-727220833`
(https://github.com/mediumkreation/IndianList)
need to review that list but...their readme file just ask to adblock browser as compatible or abp 
content is also not good as i see list

**Comment by mapx-** [comment]
ah, ok .. it's on github too

**Comment by Yuki2718** [comment]
FYI (if you're not aware of): the list author has opened some PR in EL. In my view, as well as the entries in the list, the filters look bit too specific which will result in future burden on maintenance.

**Comment by ghajini** [comment]
URL =

`https://maharashtratimes.com/maharashtra/mumbai-news/coronavirus-night-curfew-in-mumbai-taxi-car-and-auto-rickshaws-are-allowed-to-operate/articleshow/79910358.cms`

**Issue=**

1.

Amazon recommended deals /ads again 

**Screenshot =**

`https://user-images.githubusercontent.com/20338483/103063070-3639af00-45d6-11eb-893b-ac65e206e804.jpg`

**Suggested filter(1)=**
So old filter `/pwafeeds/amazon_wdt_tas.cms` in ublock filters can be changed to `/pwafeeds/amazon_wdt*.cms`

2.

Some empty ads placeholders

**Screenshots=**

`https://user-images.githubusercontent.com/20338483/103063298-dabbf100-45d6-11eb-9816-16be1a5a4e03.png`

`https://user-images.githubusercontent.com/20338483/103063305-dd1e4b00-45d6-11eb-8079-df427450d659.png`

Filter for this(2) either `maharashtratimes.com##.fbnad`
Or
`maharashtratimes.com##.ads-open-close`

**Comment by ghajini** [comment]
@mapx- pls add

domains = `m.timesofindia.com` and `timesofindia.indiatimes.com`

Filters =
```
m.timesofindia.com##.asAffiliate
##.slick-track
timesofindia.indiatimes.com##.asAffiliate
##[href^="https://timesofindia.indiatimes.com/affiliate_amazon.cms"]
##[href^="https://m.timesofindia.com/affiliate_amazon.cms"]
```
I notified ryanbr about this but iam not sure he will add or not?

**Comment by jeiea** [comment]
> ##.slick-track

Is it really necessary to global? It seems [react-slick](https://react-slick.neostack.com/) library inserts this class by default.
