### ISSUE TITLE
lightnovelpub.com: detection

### ISSUE THREAD

**Issue by razdle** [uBlockOrigin/uAssets#16807]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lightnovelpub.com/novel/lightning-is-the-only-way-1485/chapter-22`

### Category

detection

### Description

bright red on dark screen hurts my eyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 82968
  cosmetic: 38622
  scriptlet: 16853
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 208-0, never
    easylist: 61503-45, 5d.10m
    easyprivacy: 30952-1173, 5d.9m
    plowe-0: 3676-901, 4d.15h.15m
    ublock-abuse: 77-0, 7d.21h.43m
    ublock-badware: 4298-120, 4d.15h.14m
    ublock-filters: 31977-141, 4d.15h.13m
    ublock-privacy: 263-1, 7d.21h.41m
    ublock-quick-fixes: 161-19, 17h.56m
    ublock-unbreak: 1879-46, 4d.15h.12m
    urlhaus-1: 6067-0, 17h.55m
filterset (user): [array of 208 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 628 ms
  maxAssetCacheWait: 369 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    doubleclick.net: 1
    googletagmanager.com: 1
    stpd.cloud: 1
    translate.googleapis.com: 2
```
</details>

**Comment by ghajini** [comment]
> 

did you get to updated filters?
