### ISSUE TITLE
sso.godaddy.com: breakage

### ISSUE THREAD

**Issue by jyork** [uBlockOrigin/uAssets#16802]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sso.godaddy.com/?realm=idp&app=venture-redirector&path=%2f&marketid=en-US`

### Category

breakage

### Description

Get a message "Your browser is a bit unusual...Try disabling ad blockers and other extensions, enabling javascript, using a different web browser or turning off your VPN." and it blocks me logging in.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://user-images.githubusercontent.com/102590/219791687-c992973d-e6e5-4ab3-bc99-48a63297e2f8.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83290
  cosmetic: 38541
  scriptlet: 16855
  html: 884
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32793-55, 3d.4h.30m
    ublock-badware: 4337-5, 3d.4h.29m
    ublock-privacy: 323-0, 4h.23m
    ublock-abuse: 79-0, 4h.22m
    ublock-unbreak: 1888-2, 3d.4h.28m
    easylist: 61896-648, 20m
    easyprivacy: 30975-1743, 21m
    urlhaus-1: 6067-0, 19h.58m
    plowe-0: 3676-2, 6d.20h.7m
    ublock-quick-fixes: 165-0, 19h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12192 ms
  maxAssetCacheWait: 5430 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    godaddy.com: 16
    elastic-cloud.com: 4
```
</details>

**Comment by mapx-** [comment]
I get no error just loading the page => do I need an account to reproduce the issue ?

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
