### ISSUE TITLE
yandex direct not blocked at all (lenta.ru for example)

### ISSUE THREAD

**Issue by leosher** [uBlockOrigin/uAssets#1681]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://lenta.ru/ or https://www.gazeta.ru/]`

### Describe the issue

[advertising blocks marked "Яндекс Директ" - Yandex direct ads network ]

### Screenshot(s)

[![lenta ru](https://user-images.githubusercontent.com/37189525/37167189-46d6f0dc-2312-11e8-8a36-66f0c41e2700.png)
![gazeta ru](https://user-images.githubusercontent.com/37189525/37167567-55de75cc-2313-11e8-960d-e39046742ad1.png)

]

### Versions

- Browser/version: [Firefox 58.02]
- uBlock Origin version: [uBlock Origin v1.15.10]

### Settings

- [Default, no user made filters]

### Notes

[Closed issues about yandex direct: https://github.com/uBlockOrigin/uAssets/issues/357, https://github.com/uBlockOrigin/uAssets/issues/84]

**Comment by vasili111** [comment]
Confirming the issue.

**Comment by mapx-** [comment]
You should ask at ruadlist forum
https://forums.lanik.us/viewforum.php?f=102

I cannot reproduce the issue (probably is geo based)

**Comment by mapx-** [comment]
@dimisa

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
https://forums.lanik.us/viewtopic.php?f=102&t=22512  >
https://greasyfork.org/ru/scripts/19993-ru-adlist-js-fixes

**Comment by vasili111** [comment]
@mapx- 
Yes, it maybe geo dependent. I am now in the USA and have that issue but did not have it outside the USA.
You can try to reproduce it by use USA VPN.

Also, it is not directly related to the issue but I had several clearly scam adds from that website after I initially access the website from the USA but never had any such issue before (accessing lenta.ru for many years.). These ads appear several times but now they are gone.

**Comment by mapx-** [comment]
I tried also using a USA VPN, no dice
