### ISSUE TITLE
ajc.com: detection

### ISSUE THREAD

**Issue by tjthayer** [uBlockOrigin/uAssets#16818]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ajc.com/`

### Category

detection

### Description

This website detecting UBO again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 109
filterset (summary): 
  network: 83473
  cosmetic: 38872
  scriptlet: 17183
  html: 891
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33551-171, 5m
    ublock-badware: 4390-5, 5m
    ublock-privacy: 321-0, 5m
    ublock-abuse: 79-0, 5m
    ublock-unbreak: 1908-1, 5m
    ublock-quick-fixes: 174-0, 5m
    easylist: 61942-536, 5m
    easyprivacy: 30983-1744, 5m
    urlhaus-1: 6035-0, 5m
    plowe-0: 3675-2, 5m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1407 ms
  maxAssetCacheWait: 918 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    chartbeat.com: 1
    db-ip.com: 2
    go-mpulse.net: 2
    googletagmanager.com: 2
    htlbid.com: 1
    includemodal.global.ssl.fastly.net: 2
    mg2insights.com: 5
    msecnd.net: 2
    ntv.io: 1
    sophi.io: 1
```
</details>

**Comment by liamengland1** [comment]
detection and 3p garbage back again
![image](https://user-images.githubusercontent.com/16567977/221629579-f96fea3f-eb45-4c20-83a0-09c98cc1316f.png)

`ajc.com##+js(aopr, MG2Loader.init)` from AG filters works

**Comment by mapx-** [comment]
Weird, tested via vpn => chrome still ok, FF I got the crap only once then nothing more
