### ISSUE TITLE
1412.rest: detection

### ISSUE THREAD

**Issue by pololoduck** [uBlockOrigin/uAssets#16812]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

[`(https://1412.rest/notice)']https://1412.rest/notice/26384677

### Category

detection

### Description

I purged my cache today and updated my filters and it seemed to have led to a detection of adblock on this site. While I managed to disable the adblock ban through disabling all cosmetic filters, it seems that each page still detected adblock and shows a message that I could not zip away. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/121998563/219845088-aabd510b-53c7-462a-a236-3fbf3102e369.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 102113
  cosmetic: 52017
  scriptlet: 17419
  html: 0
listset (total-discarded, last-updated): 
  added: 
    CHN-0: 28145-102, 4h.44m
    KOR-1: 4200-29, 4h.44m
  default: 
    user-filters: 7-0, never
    easylist: 61924-125, 4h.44m
    easyprivacy: 30981-1204, 4h.44m
    plowe-0: 3675-916, 4h.44m
    ublock-abuse: 79-0, 4h.44m
    ublock-badware: 4368-121, 4h.44m
    ublock-filters: 32731-168, 4h.44m
    ublock-privacy: 274-3, 4h.44m
    ublock-quick-fixes: 171-18, 4h.44m
    ublock-unbreak: 1900-47, 4h.44m
    urlhaus-1: 6006-0, 4h.44m
filterset (user): [array of 7 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 126 ms (selfie)
  maxAssetCacheWait: 83 ms
popupPanel: 
  blocked: 10
  no-cosmetic-filtering: true
  blockedDetails: 
    google.com: 6
    googlesyndication.com: 1
    googletagmanager.com: 3
```
</details>

**Comment by mapx-** [comment]
> KOR-1: 4200-29, 4h.44m

fixed 1 h ago by KOR: List-KR
update that list
