### ISSUE TITLE
client.falixnodes.net: detection

### ISSUE THREAD

**Issue by tlostshadow01** [uBlockOrigin/uAssets#16819]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://client.falixnodes.net/disableadblock`
`https://dev.falixnodes.net/disableadblock`

### Category

detection

### Description

adblock detected its annoying 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230218-191014](https://user-images.githubusercontent.com/101035482/219876161-85edc0df-83c6-4783-bcca-c7e1c9ea25ac.jpg)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 122784
  cosmetic: 39494
  scriptlet: 21451
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-spyware-url: 920-2, 22h.34m
    curben-phishing: 34931-0, 22h.34m
    ublock-annoyances: 4893-10, 22h.34m
  default: 
    user-filters: 2-0, never
    TUR-0: 12177-193, 22h.37m
    adguard-mobile: 8803-33, 22h.37m
    easylist: 61924-17062, 22h.36m
    easyprivacy: 30981-1188, 22h.36m
    plowe-0: 3675-985, 22h.36m
    ublock-abuse: 79-0, 22h.36m
    ublock-badware: 4352-128, 22h.36m
    ublock-filters: 32852-402, 22h.35m
    ublock-privacy: 274-4, 22h.35m
    ublock-quick-fixes: 169-19, 22h.35m
    ublock-unbreak: 1904-49, 22h.35m
    urlhaus-1: 6050-2, 22h.35m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 566 ms (selfie)
  maxAssetCacheWait: 357 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    google.com: 2
```
</details>

**Comment by tlostshadow01** [comment]
im not using chrome 
kiwi browser + ublockorigin

**Comment by mapx-** [comment]
Test using FF mobile

**Comment by tlostshadow01** [comment]
> @tlostshadow01 Did You Allow Ads On Kiwi Browser? Setting>Site Setting>Ads>Allowed

yes

![Screenshot_20230219-171753](https://user-images.githubusercontent.com/101035482/219953984-93a3542e-dc4d-42c5-bb4e-dcfa85b25cec.jpg)
