### ISSUE TITLE
UBO blocks in firefox but not in edge

### ISSUE THREAD

**Issue by numloxxx** [uBlockOrigin/uAssets#16811]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I'm trying to block the same watermark on the Landgate map viewer website.

The url for the water mark is 
`https://map-viewer-plus.app.landgate.wa.gov.au/widgets/Watermark/images/watermark.png` 
and this is blocked easily in the firefox plugin, but it doesn't get blocked in the Edge plugin. Any suggestions?

The Landgate website is `https://map-viewer-plus.app.landgate.wa.gov.au/index.html`

### URL(s) where the issue occurs.

`https://map-viewer-plus.app.landgate.wa.gov.au/index.html`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61281300/219843529-bebb31fb-61ee-451a-b593-69b569a8f14d.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83311
  cosmetic: 38623
  scriptlet: 16936
  html: 885
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32952-54, 3d.7m
    ublock-badware: 4347-5, 3d.6m
    ublock-privacy: 323-0, 2d.20h
    ublock-abuse: 79-0, 3d.4m
    ublock-unbreak: 1892-2, 3d.3m
    ublock-quick-fixes: 165-0, 18h.41m
    easylist: 61911-648, 1d.2h.43m
    easyprivacy: 30968-1745, 1d.2h.42m
    urlhaus-1: 6067-0, 18h.40m
    plowe-0: 3680-2, 1d.2h.44m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3701 ms (selfie)
  maxAssetCacheWait: 3175 ms
```
</details>

**Comment by mapx-** [comment]
add

`map-viewer-plus.app.landgate.wa.gov.au###watermarkGraphicsLayer_layer`
