### ISSUE TITLE
gasteizhoy.com: ads

### ISSUE THREAD

**Issue by abbio68** [uBlockOrigin/uAssets#16815]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gasteizhoy.com/`

### Category

ads

### Description

Even if it was reported and fixed recently, I think the site changed the way they show the banners and implemented new ones (destacadosbanner) to show ads 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 85982
  cosmetic: 44355
  scriptlet: 17470
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 61939-47, now
    easyprivacy: 30982-1173, now
    plowe-0: 3675-900, now
    spa-0: 3497-10, now
    spa-1: 5056-187, now
    ublock-abuse: 79-0, now
    ublock-badware: 4368-121, now
    ublock-filters: 32733-188, now
    ublock-privacy: 274-1, now
    ublock-quick-fixes: 172-18, now
    ublock-unbreak: 1900-48, now
    urlhaus-1: 6006-0, now
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 34 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5634 ms (selfie)
  maxAssetCacheWait: 218 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    ampproject.org: 2
    doubleclick.net: 1
    facebook.com: 1
    googletagmanager.com: 3
    hotjar.com: 1
    quantserve.com: 2
    videoo.tv: 1
```
</details>

**Comment by okiehsch** [comment]
@Yuki2718 
````
gasteizhoy.com##.banclick
gasteizhoy.com##.macrobanblock
````
for the spanish list.
