### ISSUE TITLE
trustedreviews.com: ads

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#16814]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.trustedreviews.com/how-to/how-to-turn-off-notifications-in-avast-antivirus-4210974`

### Category

ads

### Description

Ads about Kaspersky products

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-02-18 at 11-34-39 How to turn off notifications in Avast Antivirus](https://user-images.githubusercontent.com/101707608/219853455-005d2553-0fba-49b0-9976-67f33cd166c6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 239022
  cosmetic: 242502
  scriptlet: 38532
  html: 1038
listset (total-discarded, last-updated): 
  added: 
    https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 48507-0, 1d.22h.40m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38480-17833, 1d.22h.40m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 36627-34, 1d.22h.40m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-71, 1d.22h.40m
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-9, 1d.22h.40m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 73-0, 1d.22h.40m
    https://www.i-dont-care-about-cookies.eu/abp/: 25745-8, 1d.22h.40m
    adguard-generic: 68262-2508, 1d.22h.41m
    adguard-mobile: 8804-951, 1d.22h.41m
    adguard-spyware-url: 920-136, 1d.22h.41m
    block-lan: 44-0, 1d.22h.41m
    curben-phishing: 34570-9, 22h.9m
    curben-pup: 193-1, 22h.8m
    adguard-annoyance: 64065-3456, 1d.22h.41m
    adguard-social: 19926-80, 1d.22h.41m
    fanboy-thirdparty_social: 69-3, 1d.22h.41m
    fanboy-annoyance: 84059-14781, 1d.22h.41m
    ublock-annoyances: 4788-51, 1d.22h.41m
    dpollock-0: 11339-687, 1d.22h.40m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33515-3725, 1d.22h.41m
    ublock-badware: 4357-491, 1d.22h.41m
    ublock-privacy: 323-16, 1d.22h.41m
    ublock-abuse: 79-4, 1d.22h.41m
    ublock-unbreak: 1905-0, 1d.22h.41m
    ublock-quick-fixes: 171-2, 22h.11m
    easylist: 61858-20288, 1d.22h.41m
    easyprivacy: 30975-4895, 1d.22h.41m
    urlhaus-1: 6067-0, 22h.10m
    plowe-0: 3680-1919, 1d.22h.40m
    GRC-0: 995-4, 1d.22h.40m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13098 ms (selfie)
  maxAssetCacheWait: 4167 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    dwin2.com: 1
    google.gr: 1
    googletagmanager.com: 1
    newrelic.com: 2
    onesignal.com: 1
    onthe.io: 2
    remixd.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
trustedreviews.com##.keystone-deal
```

@ryanbr
