### ISSUE TITLE
geeksforgeeks.org: breakage

### ISSUE THREAD

**Issue by zeeshan089** [uBlockOrigin/uAssets#16817]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.geeksforgeeks.org/`

### Category

breakage

### Description

I am unable to scroll after blocking the sign-in overlay

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 84895
  cosmetic: 39007
  scriptlet: 16740
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 61524-526, never
    easyprivacy: 30820-1147, never
    plowe-0: 3671-564, never
    ublock-abuse: 77-0, never
    ublock-badware: 4232-0, never
    ublock-filters: 31551-132, never
    ublock-privacy: 255-0, never
    ublock-quick-fixes: 458-0, never
    ublock-unbreak: 1922-31, never
    urlhaus-1: 8695-0, never
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 473 ms
  maxAssetCacheWait: 24 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    geeksforgeeks.org: 4
    google.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 2
    googletagservices.com: 1
    servedby-buysellads.com: 1
```
</details>

**Comment by mapx-** [comment]
> I am unable to scroll after blocking the sign-in overlay

what filter are you using to block that overlay ?

**Comment by zeeshan089** [comment]
Hi Ublockorigin/Uassets, I was able to scroll after disabling javascript
from dev tools.

And to answer your question, I right clicked on the overlay element and
blocked it using ublock.

**Comment by mapx-** [comment]
- see in "my filters" what filter was created and post it here

**Comment by zeeshan089** [comment]
This filter is created:

www.geeksforgeeks.org##
www.geeksforgeeks.org##
www.geeksforgeeks.org##.modal-container

**Comment by mapx-** [comment]
I get nothing broken, however you could test:

- first delete the filters above, then try again to create a filter for whatever modal you see on your side, then add

`geeksforgeeks.org##body:style(overflow: auto !important;)`
