### ISSUE TITLE
work.ink: detection

### ISSUE THREAD

**Issue by Beetruce** [uBlockOrigin/uAssets#16829]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://work.ink/18Z/flyrace2`

### Category

detection

### Description

detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 83127
  cosmetic: 38615
  scriptlet: 16938
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61799-46, 3d.6h.57m
    easyprivacy: 30964-1173, 3d.6h.56m
    plowe-0: 3681-901, 9d.13h.22m
    ublock-abuse: 77-0, 9d.13h.19m
    ublock-badware: 4368-121, 1d.5h.22m
    ublock-filters: 32092-139, 1d.5h.21m
    ublock-privacy: 274-1, 1d.5h.20m
    ublock-quick-fixes: 170-17, 3h.41m
    ublock-unbreak: 1900-45, 3h.42m
    urlhaus-1: 5970-0, 3h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 658 ms (selfie)
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    work.ink: 1
```
</details>

**Comment by garry-ut99** [comment]
> * [x]  I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

It has been already reported and fixed 13 hours ago: https://github.com/uBlockOrigin/uAssets/issues/16723#issuecomment-1435772915, and your last filters update is 29 hours ago.
