### ISSUE TITLE
netcine.to: breakage

### ISSUE THREAD

**Issue by maldek4017** [uBlockOrigin/uAssets#16825]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://netcine.to/episode/theark-01x01/`

### Category

breakage

### Description

site blocks video when uBlock is running

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Chromium: 110
filterset (summary): 
  network: 84408
  cosmetic: 41825
  scriptlet: 17218
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 61635-45, 4d.1h.58m
    easyprivacy: 30954-1172, 4d.1h.55m
    plowe-0: 3680-901, 9d.23h.31m
    spa-1: 5058-63, 39m
    ublock-abuse: 79-0, 41m
    ublock-badware: 4353-121, 38m
    ublock-filters: 32089-168, 37m
    ublock-privacy: 274-1, 40m
    ublock-quick-fixes: 170-17, 35m
    ublock-unbreak: 1896-46, 36m
    urlhaus-1: 5970-0, 34m
filterset (user): [empty]
trustedset: 
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1809 ms (selfie)
  maxAssetCacheWait: 339 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    disqus.com: 1
    histats.com: 3
    inklinkor.com: 3
    ophoacit.com: 1
```
</details>

**Comment by maldek4017** [comment]
site blocks video when uBlock is running

**Comment by stephenhawk8054** [comment]
@Yuki2718 Spanish list

**Comment by Yuki2718** [comment]
I see it gets update an hours ago in https://github.com/AdguardTeam/AdguardFilters/issues/142951 and the video doesn't work only on uBO.

**Comment by gorhill** [comment]
I force updated all lists, disabled `netcine.to##+js(acs, adblockOK)`, and I don't get an anti-adblock on my side.

**Comment by Yuki2718** [comment]
Okay, working fine on my end too. I guess I did somthing wrong, sorry.

**Comment by mapx-** [comment]
> the video doesn't work only on uBO

When I tested the page, the video was occasionally not playable even disabling uBO, so maybe a temporary site issue.
