### ISSUE TITLE
jacksonguitars.com: breakage

### ISSUE THREAD

**Issue by jcf-junior** [uBlockOrigin/uAssets#16827]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jacksonguitars.com/en-PT/start`

### Category

breakage

### Description

It is not possible to interact with the menu on the website when uBlock is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 84747
  cosmetic: 41962
  scriptlet: 17209
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-0, never
    easylist: 62017-46, 1h.34m
    easyprivacy: 30977-1173, 1h.33m
    plowe-0: 3675-900, 1h.32m
    spa-1: 5058-63, 1h.37m
    ublock-abuse: 79-0, 1h.30m
    ublock-badware: 4387-121, 1h.28m
    ublock-filters: 32088-168, 1h.27m
    ublock-privacy: 274-1, 1h.25m
    ublock-quick-fixes: 170-18, 1h.24m
    ublock-unbreak: 1910-44, 1h.23m
    urlhaus-1: 5970-0, 1h.22m
filterset (user): [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 821 ms
  maxAssetCacheWait: 128 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    jacksonguitars.com: 1
    cquotient.com: 1
    d2wy8f7a9ursnm.cloudfront.net: 1
    segment.com: 1
    sentry.io: 3
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||cdn.segment.com/analytics.js/v1/*/analytics.min.js$script,domain=jacksonguitars.com
```

@ryanbr
