### ISSUE TITLE
voe.sx: detection

### ISSUE THREAD

**Issue by wilhelm115** [uBlockOrigin/uAssets#16824]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

adblocker detection on
`https://voe.sx/e/pw9popfqaske`

### URL(s) where the issue occurs.

`https://voe.sx/e/pw9popfqaske`

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 85216
  cosmetic: 42825
  scriptlet: 16932
  html: 885
listset (total-discarded, last-updated): 
  default: 
    user-filters: 23-0, never
    ublock-filters: 32935-68, 2d.3h.8m
    ublock-badware: 4357-5, 1d.6h.4m
    ublock-privacy: 310-0, 13d.1h.23m
    ublock-abuse: 77-0, 13d.1h.24m
    ublock-unbreak: 1910-1, 1d.6h.5m
    easylist: 61503-640, 5d.13h.24m
    easyprivacy: 30956-1751, 5d.13h.23m
    plowe-0: 3667-2, 13d.1h.21m
    DEU-0: 6541-2, 1d.2h.1m
    urlhaus-1: 6050-0, 1d.2h.2m
    ublock-quick-fixes: 174-0, 2h.52m
filterset (user): [array of 24 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 803 ms (selfie)
  maxAssetCacheWait: 300 ms
```
</details>

**Comment by ghajini** [comment]
update filters, your filters are out of date

**Comment by wilhelm115** [comment]
oh yes thanks, I found it:
 settings -> filterlist -> update
but why does this not happen by itself?

**Comment by stephenhawk8054** [comment]
The site was fixed recently, extension auto-updates the filter lists per 4-day by default. So you might need to force update manually if you need quick fix.
