### ISSUE TITLE
a.eg-akw.com: detection

### ISSUE THREAD

**Issue by K-BeBO** [uBlockOrigin/uAssets#16828]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://a.eg-akw.com/series`

### Category

detection
![PyxLj2NKrN](https://user-images.githubusercontent.com/78613040/219936709-5e997517-a93f-41e1-a828-d367832cd305.png)

### Description

![PyxLj2NKrN](https://user-images.githubusercontent.com/78613040/219936727-eafa0d31-2913-4894-bf8d-b8f69fc16272.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 83285
  cosmetic: 38647
  scriptlet: 16933
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    easylist: 61939-47, 19h.37m
    easyprivacy: 30981-1173, 19h.36m
    plowe-0: 3676-901, 7d.19h.46m
    ublock-abuse: 77-0, 7d.19h.49m
    ublock-badware: 4368-121, 19h.35m
    ublock-filters: 32092-139, 19h.34m
    ublock-privacy: 268-1, 7d.19h.48m
    ublock-quick-fixes: 172-18, 19h.31m
    ublock-unbreak: 1900-45, 19h.33m
    urlhaus-1: 6006-0, 19h.32m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 12 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 146 ms (selfie)
  maxAssetCacheWait: 87 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googlesyndication.com: 2
    googletagmanager.com: 1
    histats.com: 1
    smartlook.com: 1
```
</details>

**Comment by mapx-** [comment]
I'm redirected to `https://akwam.to/series` which is ok.

What country are you accessing that link (`https://a.eg-akw.com/series`) ?

**Comment by K-BeBO** [comment]
> I'm redirected to `https://akwam.to/series` which is ok.
> 
> What country are you accessing that link (`https://a.eg-akw.com/series`) ?

Egypt
