### ISSUE TITLE
cbsnews.com: breakage

### ISSUE THREAD

**Issue by yokoffing** [uBlockOrigin/uAssets#16821]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cbsnews.com/live/`

### Category

breakage

### Description

See https://github.com/hagezi/dns-blocklists/issues/422#issuecomment-1434863512

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 109
filterset (summary): 
  network: 83447
  cosmetic: 38854
  scriptlet: 17164
  html: 891
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33547-57, 1d.37m
    ublock-badware: 4362-5, 1d.36m
    ublock-privacy: 310-0, 12d.2h.59m
    ublock-abuse: 77-0, 12d.2h.58m
    ublock-unbreak: 1910-1, 1d.36m
    ublock-quick-fixes: 174-0, now
    easylist: 61924-649, 1d.37m
    easyprivacy: 30981-1744, 1d.37m
    urlhaus-1: 6035-0, now
    plowe-0: 3675-2, 1d.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 102 ms (selfie)
  maxAssetCacheWait: 78 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    adsrvr.org: 1
    amazon-adsystem.com: 1
    cbsi.com: 1
    cedexis.com: 1
    chartbeat.com: 1
    confiant-integrations.net: 1
    doubleclick.net: 1
    getpublica.com: 1
    google.com: 2
    googlesyndication.com: 2
    imasdk.googleapis.com: 4
    liadm.com: 1
    moatads.com: 1
    qualtrics.com: 1
    rkdms.com: 1
    rlcdn.com: 1
    trackonomics.net: 1
    uninterestedquarter.com: 1
```
</details>

**Comment by mapx-** [comment]
- working fine, no breakage here
- update again all the filter lists, disable other addons
- if you are using a DNS with blocking capabilities try a normal one

**Comment by yokoffing** [comment]
Give me a bit. I will test again and report back.

**Comment by yokoffing** [comment]
@mapx- I've isolated the issue to Firefox's Strict tracking protection. The live stream works in other browsers after purging + updating the lists in uBO. Thank you for testing the site.
