### ISSUE TITLE
topsporter.net: detection

### ISSUE THREAD

**Issue by Alphamen16** [uBlockOrigin/uAssets#16835]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.topsporter.net/sports/2023/ligue-1-psg-vs-lille-s2/`

### Category

detection

### Description

I've managed to deal with most of the issue but there is still the matter of the blur in the page which i can't get rid of without aborting the "Math" inline-script, which removes the video player was well.

Currently using this filter: `www.topsporter.net##.wpdtpXjrTLutRcNM-wrapper, .active.wpdtpXjrTLutRcNM-blackout, .wpdtpXjrTLutRcNM-css`

Hope you guys can help!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83216
  cosmetic: 39809
  scriptlet: 19998
  html: 1038
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4788-4, 3d.13h.1m
  default: 
    user-filters: 81-0, never
    ublock-filters: 32933-156, 3d.13h.6m
    ublock-badware: 4347-5, 3d.13h.5m
    ublock-privacy: 323-0, 3d.13h.4m
    ublock-abuse: 79-0, 3d.13h.3m
    ublock-unbreak: 1895-0, 3d.13h.2m
    easylist: 61377-518, 3d.2h.16m
    easyprivacy: 30968-1760, 3d.2h.15m
    urlhaus-1: 6035-0, 16h.7m
    plowe-0: 3681-2, 9d.4h.19m
    ublock-quick-fixes: 175-1, 20h.8m
filterset (user): [array of 69 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 134 redacted]
hostRuleset: 
  added: [array of 434 redacted]
urlRuleset: 
  added: [array of 104 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  selfieAfter: 11
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 744 ms (selfie)
  maxAssetCacheWait: 470 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    topsporter.net: 2
    adipolo.com: 2
    chatango.com: 2
    doubleclick.net: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    googletagservices.com: 1
    greeter.me: 2
    histats.com: 1
    modoro360.com: 1
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Alphamen16** [comment]
@mapx- does this mean that once you open the link, you see everything the correct way, without an adblock banner and no blur in the page whatsoever?

This is what i see with the filter i posted with the request: 
![image](https://user-images.githubusercontent.com/95193005/219958534-f1fb9efc-2f14-46c8-8abb-4452a85c7406.png)

I did reset UBO and i'm using Firefox on windows 10, i've reset the PC as well, cloudflare DNS so not using Adguard or anything of the sort, UBO is my only blocker and i've been a user for years, i'm a fairly advanced user so i don't think this would be the issue

**Comment by Alphamen16** [comment]
Without any filters: 
![image](https://user-images.githubusercontent.com/95193005/219958777-a56e3249-b5ff-46fa-a57c-5169861d004e.png)

**Comment by mapx-** [comment]
Follow ALL the indications above.

**Comment by Alphamen16** [comment]
@mapx- Nevermind, i see what the issue is now. I uptaded all filter lists again and there must've been a recent update because there was a filter there i was missing before: 

`@@||pagead2.googlesyndication.com^$script,xhr,domain=sportfacts.net|topsporter.net`

Apologies for the inconvenience, we can close this now! Can't believe i reset everything and it was a filter update -.-

**Comment by Alphamen16** [comment]
@mapx- detection seems to have returned on my end today, is it just me or do you see it as well?

**Comment by Alphamen16** [comment]
That did it, thanks very much! Couldn't figure it out by myself, so frustrating

**Comment by Alphamen16** [comment]
@mapx- they appear to be persistent, it's changed again: https://www.topsporter.net/sports/2023/premier-league-arsenal-vs-afc-bournemouth-s1/

**Comment by Alphamen16** [comment]
Legend, it works thanks!
