### ISSUE TITLE
techcyan.com: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#16834]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://techcyan.com/bluecloud-obtained-ai-technology/`

### Category

detection

### Description

Adblocker detected...viefaucet.com (shortlink)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83385
  cosmetic: 38852
  scriptlet: 17195
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 645-11, never
    easylist: 61904-47, 1d.12h.51m
    easyprivacy: 30981-1173, 1d.12h.50m
    plowe-0: 3680-903, 1d.12h.49m
    ublock-abuse: 79-0, 1d.12h.47m
    ublock-badware: 4353-121, 1d.12h.45m
    ublock-filters: 32112-139, 1d.12h.44m
    ublock-privacy: 276-1, 1d.12h.43m
    ublock-quick-fixes: 170-18, 7h.40m
    ublock-unbreak: 1899-45, 1d.12h.41m
    urlhaus-1: 5970-0, 7h.39m
filterset (user): [array of 493 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2980 ms (selfie)
  maxAssetCacheWait: 1353 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    wp.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me. Update all your filter lists and try again and be sure you use no other content blocking extensions like Adblock Plus. When its still not working pass us the shortened link you used

**Comment by thedeathcoder** [comment]
listen JobcenterTycoon, 
We are just fed up with you, stop blocking our ads, Don't u have a job. Go and do that. Don't mess with us. Those peoples who are reporting our site are earning money from us and we are not earning bcoz of your frequent changes. Its creating huge loss for us. STOP MESSING WITH US. and you Lahiru ur account from viefaucet will be blocked soon.

**Comment by thedeathcoder** [comment]
Don't u understand what I told u ? Why the hell u r creating issue for us. JUST STOP IRRITATING US.

**Comment by king-iskan** [comment]
@JobcenterTycoon 
Need your help, for this issue.
After finish recapthca, we have notification "adblock detection, cannot be generate"
We need fix for this. 🙏

**Comment by king-iskan** [comment]
> 

Ok thanks

**Comment by king-iskan** [comment]
> Should work now. At the moment the site dev is very aggressive

Still same condition
![az_recorder_20230301_210210_edited](https://user-images.githubusercontent.com/120553425/222162651-b192d6c2-727b-469a-a1b4-dd76b5392a14.jpg)

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/commit/681e853ced6baf778524fb9fff53b86948307776

**Comment by king-iskan** [comment]
Ok, work better🙏
