### ISSUE TITLE
1412.rest: breakage

### ISSUE THREAD

**Issue by pololoduck** [uBlockOrigin/uAssets#16838]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://1412.rest/fantasy05`

### Category

breakage

### Description

When UBO is enabled, all the dropdown menus on this site breaks and does not work, and it becomes impossible to make a post with the default 'anonymous' mode. If I turn off UBO then those issues disappear and the site functions as normal, but then ads appear.

I enabled a few regional language lists like the KOR list but did not change any other settings from the default, but I'm not sure what is causing all of the dropdown menus and buttons to break (outside of the home button), alongside the anonymous function disappearing as well. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/121998563/219967521-1176978d-2dc9-4f7e-910e-f4545779a41d.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 103765
  cosmetic: 62096
  scriptlet: 17578
  html: 0
listset (total-discarded, last-updated): 
  added: 
    CHN-0: 28160-102, 11h.59m
    FIN-0: 2150-0, 11h.59m
    JPN-1: 9716-9, 11h.59m
    KOR-1: 4201-29, 11h.59m
  default: 
    user-filters: 4-1, never
    easylist: 62017-133, 11h.59m
    easyprivacy: 30984-1231, 11h.59m
    plowe-0: 3675-923, 11h.58m
    ublock-abuse: 79-0, 11h.58m
    ublock-badware: 4387-122, 11h.58m
    ublock-filters: 32732-183, 11h.58m
    ublock-privacy: 274-3, 11h.58m
    ublock-quick-fixes: 170-18, 11h.58m
    ublock-unbreak: 1900-48, 11h.58m
    urlhaus-1: 5970-0, 11h.58m
filterset (user): [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 953 ms
  maxAssetCacheWait: 297 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    google.com: 6
    googlesyndication.com: 2
    googletagmanager.com: 3
```
</details>

**Comment by mapx-** [comment]
@piquark6046 

breaking filter
`1412.rest##+js(abort-on-stack-trace, jQuery.prototype.css, check_adBlock)`

**Comment by piquark6046** [comment]
Resolved.
