### ISSUE TITLE
docs.qq.com: breakage

### ISSUE THREAD

**Issue by EdwardRS04** [uBlockOrigin/uAssets#16836]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://docs.qq.com/desktop/mydoc?`

### Category

breakage

### Description

The sharing pop-up window of the document is blocked, resulting in the inability to share

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 179314
  cosmetic: 233340
  scriptlet: 38188
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 64111-103, 2d.3h.32m
    adguard-generic: 68225-549, 2d.3h.32m
    adguard-mobile: 8771-66, 2d.3h.32m
    adguard-social: 19848-834, 2d.3h.32m
    adguard-spyware-url: 920-2, 2d.3h.32m
    block-lan: 44-0, 11d.19h.29m
    curben-phishing: 35894-0, 22m
    curben-pup: 200-0, 19m
    dpollock-0: 11396-122, 3h.18m
    fanboy-annoyance: 83970-6488, 2d.3h.31m
    fanboy-cookiemonster: 45596-45596, 2d.3h.31m
    fanboy-social: 22764-22764, 2d.3h.32m
    fanboy-thirdparty_social: 68-20, 2d.3h.31m
    ublock-annoyances: 4834-243, 2d.3h.31m
  default: 
    user-filters: 0-0, never
    CHN-0: 28135-102, 2d.3h.31m
    easylist: 61866-1294, 2d.3h.34m
    easyprivacy: 30977-1500, 2d.3h.31m
    plowe-0: 3676-1357, 8d.7h.38m
    ublock-abuse: 79-0, 2d.3h.31m
    ublock-badware: 4358-320, 2d.3h.31m
    ublock-filters: 32718-4019, 2d.3h.31m
    ublock-privacy: 276-10, 2d.3h.35m
    ublock-quick-fixes: 169-24, 21m
    ublock-unbreak: 1899-95, 2d.3h.31m
    urlhaus-1: 5908-2, 20m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3286 ms
  maxAssetCacheWait: 1072 ms
popupPanel: 
  blocked: 43
  blockedDetails: 
    qq.com: 22
    gtimg.com: 2
    idqqimg.com: 19
```
</details>

**Comment by mapx-** [comment]
@cjx82630 , could you help here ?

**Comment by cjx82630** [comment]
@ryanbr 
Could you take a look? The following rules may solve the issue.
> qq.com#@#.share-title
qq.com#@#.share-btns
qq.com#@##main-share
qq.com#@#.share-link

![2023-02-20_081530](https://user-images.githubusercontent.com/9707241/219984391-baca8909-683f-480d-be05-5afee0d15bdf.jpg)
