### ISSUE TITLE
leaveadvice.com: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#16832]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://leaveadvice.com/new-zealand-paid-paternity-leave-2020/`

### Category

detection

### Description

Adblocker detected...Short link claim (viefaucet.com)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83382
  cosmetic: 38849
  scriptlet: 17167
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 611-1, never
    easylist: 61904-56, 1d.11h.52m
    easyprivacy: 30981-1173, 1d.11h.51m
    plowe-0: 3680-903, 1d.11h.50m
    ublock-abuse: 79-0, 1d.11h.47m
    ublock-badware: 4353-121, 1d.11h.45m
    ublock-filters: 32112-139, 1d.11h.44m
    ublock-privacy: 276-1, 1d.11h.43m
    ublock-quick-fixes: 170-18, 6h.41m
    ublock-unbreak: 1899-46, 1d.11h.41m
    urlhaus-1: 5970-0, 6h.40m
filterset (user): [array of 482 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2980 ms (selfie)
  maxAssetCacheWait: 1353 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    leaveadvice.com: 10
    connatix.com: 1
    doubleclick.net: 1
    ezodn.com: 1
    ezoic.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    jsdelivr.net: 1
    quantserve.com: 1
    vlitag.com: 1
```
</details>

**Comment by king-iskan** [comment]
Hi, for the issue above needs to be updated, because it has been detected again

**Comment by king-iskan** [comment]
If need original link, this 
https://srt.shortyearn.com/I62y8Bt
![Screenshot_20230326-135537](https://user-images.githubusercontent.com/120553425/227760454-f823f2a6-0d25-47cd-a9a9-aaffdc811ed7.png)

**Comment by king-iskan** [comment]
> `leaveadvice.com##+js(aopr, detectIncognito)`

Work for FF android, for chromium based browser android not working.
Can reproduce too for chromium based?

**Comment by mapx-** [comment]
```
/wp-content/plugins/wp-hide-security-enhancer/assets/js/devtools-detect.js$script,1p
||cdn.jsdelivr.net/*/detectIncognito$script
```

**Comment by king-iskan** [comment]
> 



> ```
> /wp-content/plugins/wp-hide-security-enhancer/assets/js/devtools-detect.js$script,1p
> ||cdn.jsdelivr.net/*/detectIncognito$script
> ```

Done. Work,

**Comment by mapx-** [comment]
If I disable uBO for leaveadvice => still detection

**Comment by king-iskan** [comment]
> If I disable uBO for leaveadvice => still detection

Yeah, before you send filter. Condition like that
