### ISSUE TITLE
112amsterdam.nl: detection

### ISSUE THREAD

**Issue by sparkfear** [uBlockOrigin/uAssets#16839]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://112amsterdam.nl/p2000-amsterdam`

### Category

detection

### Description

The element creating an overlay alerting you that you have an adblock enabled constantly changes it's string.
Manually adding this does not seem to work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/1058823/219967379-cd8867e1-6eeb-40ce-8290-198ad8550736.png)

After adding a custom filter rule, the site will bypass this with a new string.
![image](https://user-images.githubusercontent.com/1058823/219967712-921f84dd-2e87-4d1d-b4e8-65d8035746d8.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 85442
  cosmetic: 41977
  scriptlet: 20243
  html: 1040
listset (total-discarded, last-updated): 
  added: 
    adguard-spyware-url: 920-4, 5m
    ublock-annoyances: 4798-4, 5m
    NLD-0: 2577-24, 5m
  default: 
    user-filters: 5-0, never
    ublock-filters: 33569-83, 5m
    ublock-badware: 4391-5, 5m
    ublock-privacy: 321-0, 5m
    ublock-abuse: 79-0, 5m
    ublock-unbreak: 1909-1, 5m
    ublock-quick-fixes: 178-0, 5m
    easylist: 62092-656, 5m
    easyprivacy: 30987-1747, 5m
    urlhaus-1: 5908-0, 5m
    plowe-0: 3675-2, 5m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 131 ms (selfie)
  maxAssetCacheWait: 144 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    addthis.com: 1
    doubleclick.net: 1
    google.com: 2
    googlesyndication.com: 2
    googletagmanager.com: 2
    onesignal.com: 3
```
</details>

**Comment by mapx-** [comment]
Test 

`112amsterdam.nl##+js(nostif, Height)`

**Comment by Yuki2718** [comment]
@BPower0036 `112amersfoort.nl,112amsterdam.nl,112apeldoorn.nl,112arnhem.nl,112barneveld.nl,112bunschoten.nl,112doetinchem.nl,112harderwijk.nl,112hilversum.nl,112inbeeld.nl,112nijkerk.nl,112ridderkerk.nl,112rotterdam.nl,112scherpenzeel.nl,112schiedam.nl,112vallei.nl,112veenendaal.nl,112wageningen.nl,112zeewolde.nl,112zwolle.nl##+js(noeval-if, /chp_?ad/)`

**Comment by sparkfear** [comment]
I believe the websites have been updated, the detection is back.
Thank you guys

**Comment by Yuki2718** [comment]
@BPower0036 I missed but `112ede.nl` is addressed in uBlock filters.

**Comment by BPower0036** [comment]
@Yuki2718 added to EasyDutch
