### ISSUE TITLE
how can i block recaptcha verification with ublock origin?

### ISSUE THREAD

**Issue by recaptchaismyenemy** [uBlockOrigin/uAssets#16847]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://opensea.io/collection/entities-5/assets/create`

### Category

recaptcha bypass

### Description

how can i block recaptcha verification with ublock origin?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 83841
  cosmetic: 39332
  scriptlet: 16946
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ROU-1: 1204-4, 22m
    easylist: 62100-62, 19m
    easyprivacy: 30984-1188, 18m
    plowe-0: 3675-911, 17m
    ublock-abuse: 79-0, 15m
    ublock-badware: 4387-121, 13m
    ublock-filters: 32099-141, 12m
    ublock-privacy: 274-1, 11m
    ublock-quick-fixes: 171-18, 10m
    ublock-unbreak: 1900-45, 9m
    urlhaus-1: 5908-0, 8m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1297 ms
  maxAssetCacheWait: 149 ms
popupPanel: 
  blocked: 65
  blockedDetails: 
    opensea.io: 8
    amplitude.com: 21
    google-analytics.com: 16
    sentry.io: 20
```
</details>

**Comment by garry-ut99** [comment]
Description and title unnecessarily duplicated, title to `opensea.io`.

**Comment by iam-py-test** [comment]
Do you want to bypass captchas or just block them from loading?
Bypassing captchas is out of scope for uBo. If you want to block RECAPTCHA, try these filters:
```adblock
||google.com/recaptcha/$important
||gstatic.com/recaptcha/$important
```
This will break any website "protected" by RECAPTCHA (there may be a better solution)
