### ISSUE TITLE
lexulous.com: breakage

### ISSUE THREAD

**Issue by Vizbhume** [uBlockOrigin/uAssets#16849]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lexulous.com/email/playboard`

### Category

breakage

### Description

After adding uBlock to Firefox, the functionality of Lexulous.com (a Scrabble type game) is broken.  Tiles at the bottom of the screen can no longer be selected and dragged onto the game board.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 86047
  cosmetic: 38848
  scriptlet: 16936
  html: 885
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-2, never
    ublock-filters: 32935-55, 2d.23h.30m
    ublock-badware: 4357-5, 2d.23h.29m
    ublock-privacy: 319-0, 3d.17h.17m
    ublock-abuse: 79-0, 3d.17h.16m
    ublock-unbreak: 1906-0, 2d.23h.28m
    ublock-quick-fixes: 174-1, 2h.21m
    easylist: 64987-595, 4d.22h.51m
    easyprivacy: 30908-1712, 4d.22h.50m
    urlhaus-1: 5908-0, 2h.20m
    plowe-0: 3680-2, 10d.23h.15m
filterset (user): [array of 9 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 469 ms (selfie)
  maxAssetCacheWait: 195 ms
popupPanel: 
  blocked: 11
  no-cosmetic-filtering: true
  blockedDetails: 
    aaxads.com: 1
    avantisvideo.com: 2
    btloader.com: 2
    doubleclick.net: 2
    google-analytics.com: 1
    quantserve.com: 1
    stpd.cloud: 2
```
</details>

**Comment by liamengland1** [comment]
Test account required. I created one and was able to drag the letter tiles to the game board without issue

**Comment by mapx-** [comment]
> no-cosmetic-filtering: true

You should re-test after resetting uBO to the defasult settings, updating all the lists etc

**Comment by garry-ut99** [comment]
> Test account required

Not necessarily, clicking "QUICK PLAY" button is enought to play demo as a guest.
I'm unable to reproduce the breakage.

**Comment by mapx-** [comment]
@Vizbhume 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Vizbhume** [comment]
Thank you everyone for the fast responses.  Mapx, I did everything you recommended and the issue is now fixed.  Thanks!
