### ISSUE TITLE
darmowe-torenty.pl: detection

### ISSUE THREAD

**Issue by mailing12** [uBlockOrigin/uAssets#16846]
`https://darmowe-torenty.pl`

Annoyance bar at top (fixed/sticky positioned)

<sup> https://github.com/MajkiIT/polish-ads-filter/issues/21332 </sup>

**Comment by pololoduck** [comment]
I think you can just use the element picker to create a rule to remove it (I tried it and after closing and loading it a few times it didn't come back up).

**Comment by mailing12** [comment]
But in Poland page can load 11 milion of users ≈ better cover it in list instead 11M times use picker or manually copy solution.

Also page can reinject bar to DOM to generate CPU/RAM abuse.

**Comment by mailing12** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16845
