### ISSUE TITLE
manchestereveningnews.co.uk: breakage

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#16850]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.manchestereveningnews.co.uk/whats-on/shopping/the-co-op-having-laugh-26268880`

### Category

breakage

### Description

Inline video infinitely loading. Broken by EasyList.
https://user-images.githubusercontent.com/91396482/219982273-bb0165b5-6677-47db-85a5-1117f2d8769c.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 110
filterset (summary): 
  network: 75541
  cosmetic: 40286
  scriptlet: 17205
  html: 893
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1374-0, 2m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 1d.37m
  default: 
    user-filters: 1551-13, never
    ublock-filters: 33581-66, 1h.53m
    ublock-badware: 4391-5, 1d.37m
    ublock-privacy: 321-0, 1d.37m
    ublock-abuse: 79-0, 1d.37m
    ublock-unbreak: 1911-0, 1d.37m
    ublock-quick-fixes: 178-0, 2m
    easylist: 62100-319, 1h.53m
    easyprivacy: 30987-2109, 1h.53m
filterset (user): [array of 576 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 393 ms (selfie)
  maxAssetCacheWait: 370 ms
  unsuspendAfter: 224 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    manchestereveningnews.co.uk: 3
    adsafeprotected.com: 2
    amazon-adsystem.com: 1
    aswpsdkus.com: 1
    chartbeat.com: 1
    convrse.media: 1
    doubleclick.net: 1
    google.com: 1
    googletagmanager.com: 1
    grapeshot.co.uk: 1
    hotjar.com: 2
    indexww.com: 1
    jwpcdn.com: 1
    m32.media: 1
    mirror.co.uk: 1
    quantcast.com: 1
    tm-awx.com: 2
    viafoura.co: 8
    webcontentassessor.com: 2
```
</details>

**Comment by liamengland1** [comment]
Doesn't work for me even with uBo disabled. Might be because I'm in the US

**Comment by garry-ut99** [comment]
I confirm it's broken by EasyList, because the video works after disabling EasyList.

**Comment by Daxy7** [comment]
> Doesn't work for me even with uBo disabled. Might be because I'm in the US

Try disabling any cookie/tracking protection in the browser

**Comment by Daxy7** [comment]
similar problem at `https://www.mirror.co.uk/usvsth3m/once-you-realise-just-how-5449133` near the bottom of the page
![image](https://user-images.githubusercontent.com/91396482/221047150-7f2525bc-5457-416b-be0c-ec9c8daccdcf.png)

**Comment by garry-ut99** [comment]
It's a wide breakage, on many more sites: https://publicwww.com/websites/trinitymirrordigital/
