### ISSUE TITLE
deezer.com: detection

### ISSUE THREAD

**Issue by 2emepied** [uBlockOrigin/uAssets#16857]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

~~`https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm`~~
`deezer.com`

### Category

detection

### Description

site `https://www.deezer.com/fr/` detects Ublockorigin and in addition audio ads are also emitted regularly withoit being blocked 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 103212
  cosmetic: 47403
  scriptlet: 17023
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30003-28, 1d.21h.16m
    easylist: 61950-133, 1d.21h.14m
    easyprivacy: 30977-1495, 1d.21h.10m
    plowe-0: 3675-926, 1d.21h.9m
    ublock-abuse: 79-1, 1d.21h.6m
    ublock-badware: 4353-140, 1d.21h.4m
    ublock-filters: 32086-241, 1d.20h.24m
    ublock-privacy: 274-1, 1d.20h.23m
    ublock-quick-fixes: 169-18, 20h.21m
    ublock-unbreak: 1900-45, 1d.20h.21m
    urlhaus-1: 5908-0, 20h.20m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3240 ms (selfie)
  maxAssetCacheWait: 231 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by garry-ut99** [comment]
There is main thread aswell: https://github.com/uBlockOrigin/uAssets/issues/13571

**Comment by mapx-** [comment]
- Tested using a french ip, french list, no detection
- if you get detection how could you get also audio ads (you disabled uBO !?)

follow ALL these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by bergerst** [comment]
Their adblock detection seems to be buggy now. Even after disabling all browser extensions they still say I'm using an adblocker.

Just posting here in case anyone else also encounters these issues.

**Comment by stephenhawk8054** [comment]
> Their adblock detection seems to be buggy now. Even after disabling all browser extensions they still say I'm using an adblocker.
> 
> Just posting here in case anyone else also encounters these issues.

Then there's something else on your machine that is also blocking things.

Check if you are using any:

- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by bergerst** [comment]
From their Twitter support:

> It seems like the issue may be coming from an update we have done on our end.
>
> I apologise for the inconvenience.
> 
> However, it should work again now.
