### ISSUE TITLE
anacondastores.com: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#16858]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.anacondastores.com/camping-hiking/power-cooling/generators/dune-4wd-2100w-inverter-generator/BP90166083-grey`

### Category

breakage

### Description

Click on the spot to get a bigger picture of the product. Refer to screenshot below.
With uBlock enabled, nothing happens when you click on the spot.
With uBlock disabled, a bigger picture opens up properly.

![Adblock](https://user-images.githubusercontent.com/20948631/220100655-7203e312-2ee2-40db-8101-ca8208fae1b8.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 268096
  cosmetic: 216673
  scriptlet: 38637
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38485-3629, 41m
    https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 92163-0, 41m
    adguard-annoyance: 64210-248, 41m
    adguard-generic: 68277-1215, 41m
    adguard-social: 19852-834, 41m
    block-lan: 44-0, 41m
    curben-phishing: 36073-39, 41m
    curben-pup: 193-0, 41m
    dpollock-0: 11396-171, 41m
    fanboy-annoyance: 84144-6484, 41m
    fanboy-thirdparty_social: 68-20, 41m
    ublock-annoyances: 4841-244, 41m
  default: 
    user-filters: 10-0, never
    easylist: 62104-1130, 41m
    easyprivacy: 30988-12399, 41m
    plowe-0: 3680-1350, 41m
    ublock-abuse: 79-0, 41m
    ublock-badware: 4407-322, 41m
    ublock-filters: 32674-4010, 41m
    ublock-privacy: 274-58, 41m
    ublock-quick-fixes: 173-22, 41m
    ublock-unbreak: 1901-114, 41m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4255 ms (selfie)
  maxAssetCacheWait: 936 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    bazaarvoice.com: 7
    bing.com: 1
    google.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
    krxd.net: 1
    newrelic.com: 2
    nr-data.net: 3
    paypal.com: 3
    serving-sys.com: 2
```
</details>

**Comment by krystian3w** [comment]
Bad is: `anacondastores.com##.modal`

 from EasyList Cookies (included in Fanboy Annoyances).

I think filter should be changed to one of:

```adb
anacondastores.com##div.cookies-popup-wrapper
anacondastores.com##div.cookies-popup-wrapper .modal
anacondastores.com##footer .modal
```

To avoid create: `anacondastores.com##.modal:not(.dp-popup-wrapper)` - many elements have only .fade then that simple not may not enough.

**Comment by ghajini** [comment]
@ryanbr
