### ISSUE TITLE
elle.com.tr: breakage

### ISSUE THREAD

**Issue by kmnvq** [uBlockOrigin/uAssets#16859]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.elle.com.tr/`

### Category

breakage

### Description

The click function does not work. It works as expected if [uBlock filters](https://ublockorigin.github.io/uAssets/filters/filters.txt) is turned off.

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/220100059-04e71970-f25a-410d-af8a-ac904464164f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 122968
  cosmetic: 155469
  scriptlet: 34740
  html: 892
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39305-14942, now
    adguard-generic: 68343-5845, now
    adguard-spyware-url: 920-4, now
    adguard-annoyance: 64214-1541, now
    adguard-social: 19852-30, now
  default: 
    user-filters: 63-0, never
    ublock-filters: 33500-92, now
    ublock-badware: 4421-5, now
    ublock-privacy: 321-0, now
    ublock-abuse: 79-0, now
    ublock-unbreak: 1909-1, now
    ublock-quick-fixes: 178-0, now
    easylist: 62096-372, now
    easyprivacy: 30988-1194, now
    TUR-0: 12176-11, now
filterset (user): [array of 67 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2193 ms
  maxAssetCacheWait: 1454 ms
  unsuspendAfter: 136 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    cloudflareinsights.com: 2
    doganburda.com: 1
    doubleclick.net: 1
    efilli.com: 1
    googletagmanager.com: 1
    onesignal.com: 1
```
</details>

**Comment by umut-nb0** [comment]
@okiehsch This rule seems obsolete now
