### ISSUE TITLE
flickr.com: ads

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#16854]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Sponsored ads for iStock are shown. 

### URL(s) where the issue occurs.

`https://www.flickr.com/photos/123430582@N06/13992937368/in/album-72157644660740995/`

### Screenshot(s)

![Screen Shot 2023-02-19 at 11 35 13 PM](https://user-images.githubusercontent.com/54487525/220042508-7c746ff4-8b18-41f7-91e3-5d3209e5e209.png)

### Notes

Blocking `https://combo.staticflickr.com/zz/combo?ap:build/hermes-2.0.0+e343053/hermes-template-sub-photo-additional-info/hermes-template-sub-photo-additional-info-min.js&ap:build/hermes-2.0.0+e343053/hermes-template-flag-photo-dialog-content/hermes-template-flag-photo-dialog-content-min.js&ap:build/hermes-2.0.0+e343053/sub-photo-additional-info-view/sub-photo-additional-info-view-min.js&ap:build/hermes-2.0.0+e343053/hermes-template-getty-widget/hermes-template-getty-widget-min.js&ap:build/hermes-2.0.0+e343053/getty-helper/getty-helper-min.js&ap:build/hermes-2.0.0+e343053/flickr-getty-search-fetcher/flickr-getty-search-fetcher-min.js&ap:build/hermes-2.0.0+e343053/getty-search-models/getty-search-models-min.js` seems to get rid of it but also hides the image metadata. 

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83532
  cosmetic: 38889
  scriptlet: 17200
  html: 892
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33580-58, now
    ublock-badware: 4391-5, now
    ublock-privacy: 321-0, now
    ublock-abuse: 79-0, now
    ublock-unbreak: 1909-0, now
    ublock-quick-fixes: 178-0, now
    easylist: 62069-652, now
    easyprivacy: 30988-1746, now
    urlhaus-1: 5966-0, now
    plowe-0: 3675-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 762 ms (selfie)
  maxAssetCacheWait: 212 ms
```
</details>

**Comment by krystian3w** [comment]
```adb
! simple hide
flickr.com##.getty-photo-page-widget
! procedural / CSS4 hide (if you found too many hidden elements):
flickr.com##.getty-photo-page-widget:has(.upgrade-to-pro-cta, .upgrade-pro-container)
```

**Comment by mapx-** [comment]
add

`flickr.com##.getty-photo-page-widget`

@krystian3w
