### ISSUE TITLE
sozcu.com.tr: detection

### ISSUE THREAD

**Issue by SleepyZiggi** [uBlockOrigin/uAssets#16855]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sozcu.com.tr/reklam-engelleyici`

### Category

detection

### Description

When I visit this webpage (https://www.sozcu.com.tr), it detects and forwards to the above auto-filled page: https://www.sozcu.com.tr/reklam-engelleyici. The page is in Turkish and the las two words connected with a dash says ad-blocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 83152
  cosmetic: 38632
  scriptlet: 16936
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 33m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 25m
  default: 
    user-filters: 5-0, never
    easylist: 61816-46, 3d.18h.9m
    easyprivacy: 30976-1173, 3d.18h.8m
    plowe-0: 3668-900, 11d.19h.11m
    ublock-abuse: 77-0, 11d.19h.14m
    ublock-badware: 4387-121, 28m
    ublock-filters: 32098-139, 30m
    ublock-privacy: 263-1, 11d.19h.13m
    ublock-quick-fixes: 175-16, 26m
    ublock-unbreak: 1901-44, 29m
    urlhaus-1: 5966-0, 27m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  manualUpdateAssetFetchPeriod: 501
supportStats: 
  allReadyAfter: 4278 ms (selfie)
  maxAssetCacheWait: 296 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    doubleclick.net: 1
    gemius.pl: 1
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 5
    googletagmanager.com: 1
    membrana.media: 1
    onesignal.com: 1
    sozcucdn.com: 3
    taboola.com: 2
```
</details>

**Comment by okiehsch** [comment]
Enable the regional turkish filter list.
