### ISSUE TITLE
pepephone.com: breakage

### ISSUE THREAD

**Issue by Karrrl** [uBlockOrigin/uAssets#16866]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pepephone.com/mi-pepephone/inicio`

### Category

breakage

### Description

I can't enter in my user space

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83263
  cosmetic: 38713
  scriptlet: 16950
  html: 886
listset (total-discarded, last-updated): 
  default: 
    user-filters: 10-0, never
    ublock-filters: 32919-55, 23h.56m
    ublock-badware: 4391-5, 23h.55m
    ublock-privacy: 323-0, 4d.23h.18m
    ublock-abuse: 77-0, 4d.23h.17m
    ublock-unbreak: 1908-0, 23h.54m
    ublock-quick-fixes: 284-0, 4h.26m
    easylist: 61916-638, 2d.23h.6m
    easyprivacy: 30977-1745, 2d.23h.5m
    urlhaus-1: 5950-0, 4h.25m
    plowe-0: 3675-2, 2d.11h.45m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 562 ms (selfie)
  maxAssetCacheWait: 133 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    abtasty.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> I can't enter in my user space

Explain what's the breakage ? 

Try adding the regional lists too, it's a spanish site. Test again.

If still broken:
- open uBO's logger
- reproduce again the issue
- go back in the logger, copy and paste here all the blocked requests you see there.
