### ISSUE TITLE
lastminuteengineers.com: ads

### ISSUE THREAD

**Issue by mrlinuxfish** [uBlockOrigin/uAssets#16865]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lastminuteengineers.com/oled-display-arduino-tutorial/`

### Category

ads

### Description

Leftover ad containers remain after blocking ads. `##.adtester-container-141.adtester-container.square-2141.square-2.ezoic-at-0.ezoic-ad`.

I'm not sure why, but running with the exact same filters on Firefox blocks the ad containers, but on Chrome the containers remain

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot 2023-02-20 133333](https://user-images.githubusercontent.com/444722/220194693-9d254512-7acc-4e7f-8b1d-c5a09fa42fbf.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 120642
  cosmetic: 138982
  scriptlet: 25018
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38481-3647, 3d.4h.45m
    https://www.i-dont-care-about-cookies.eu/abp/: 25737-13667, 5h.51m
    adguard-annoyance: 64219-2589, 5h.52m
    adguard-social: 19853-1956, 5h.53m
    adguard-spyware-url: 920-2, 3d.4h.47m
    fanboy-annoyance: 82500-40379, 4h.31m
    fanboy-cookiemonster: 45643-45643, 4h.30m
    fanboy-social: 22765-22549, 6d.1h.33m
    fanboy-thirdparty_social: 69-20, 6d.1h.33m
    ublock-annoyances: 4832-215, 3d.4h.49m
  default: 
    user-filters: 46-0, never
    easylist: 62100-16947, 5h.55m
    easyprivacy: 30988-12255, 5h.54m
    plowe-0: 3676-972, 7d.17h.42m
    ublock-abuse: 77-0, 10d.59m
    ublock-badware: 4358-121, 3d.4h.46m
    ublock-filters: 32113-741, 3d.4h.50m
    ublock-privacy: 268-60, 10d.10h.28m
    ublock-quick-fixes: 175-17, 4h.47m
    ublock-unbreak: 1899-71, 3d.4h.48m
    urlhaus-1: 5950-0, 5h.50m
filterset (user): [array of 46 redacted]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4353 ms (selfie)
  maxAssetCacheWait: 1261 ms
popupPanel: 
  blocked: 65
  blockedDetails: 
    lastminuteengineers.com: 55
    amazon-adsystem.com: 1
    connatix.com: 2
    doubleclick.net: 1
    ezodn.com: 3
    googlesyndication.com: 1
    googletagmanager.com: 1
    quantserve.com: 1
```
</details>

**Comment by mapx-** [comment]
> `ignoreGenericCosmeticFilters: true`

You chose to `ignore the cosmetic filters`. Unselect that setting & test again.

**Comment by mrlinuxfish** [comment]
Thanks for noticing I had the cosmetic filter set incorrectly. It’s working correctly with that setting changed
