### ISSUE TITLE
videolyrics.in: detection

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#16863]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://videolyrics.in/verify/?OWtv2f8dyya`

### Category

detection

### Description

detection adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 83187
  cosmetic: 38554
  scriptlet: 17005
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 160-44, never
    easylist: 61826-46, 4d.21h.39m
    easyprivacy: 30969-1173, 4d.21h.39m
    plowe-0: 3680-903, 4d.21h.39m
    ublock-abuse: 79-0, 4d.21h.39m
    ublock-badware: 4387-121, 4h.20m
    ublock-filters: 32009-139, 4h.18m
    ublock-privacy: 276-1, 4d.21h.39m
    ublock-quick-fixes: 169-17, 1h.26m
    ublock-unbreak: 1900-44, 4h.17m
    urlhaus-1: 5950-0, 1h.25m
filterset (user): [array of 73 redacted]
trustedset: 
  added: [array of 21 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1077 ms (selfie)
  maxAssetCacheWait: 1354 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by king-iskan** [comment]
@mapx- 
Still detection (attach)
![az_recorder_20230221_044056_edited](https://user-images.githubusercontent.com/120553425/220202805-cb9c3a59-88cb-484c-b8a5-cc700bd7ed6f.jpg)

**Comment by mapx-** [comment]
mobile ? What mobile ? In the details above you are using chrome.

**Comment by stephenhawk8054** [comment]
The fix works for me on Firefox mobile. Screenshot: 
[https://user-images.githubusercontent.com/66517106/220214862-84c414eb-578d-4159-833a-40b1fe38cf80.png](https://user-images.githubusercontent.com/66517106/220214862-84c414eb-578d-4159-833a-40b1fe38cf80.png)

Have you forced update the filter lists?

**Comment by king-iskan** [comment]
> mobile ? What mobile ? In the details above you are using chrome.

I'm using Firefox mobile browser. Right, I submit issue from my laptop use chrome. 
@stephenhawk8054 
Still detection in next step, after working on recaptha And click next, then continue.  there will be visible detection.

**Comment by stephenhawk8054** [comment]
I see. Please describe it in more details like that next time.

Can you test this filter?

```adb
videolyrics.in##+js(no-xhr-if, doubleclick)
```

**Comment by king-iskan** [comment]
> I see. Please describe it in more details like that next time.
> 
> Can you test these filters?
> 
> ```
> videolyrics.in##+js(no-xhr-if, doubleclick)
> videolyrics.in##+js(aeld, load, htmls)
> videolyrics.in##^script:has-text(htmls)
> ```

Not work, still same condition

**Comment by stephenhawk8054** [comment]
Well, I can go through all 6 steps and to the next site, so sorry can't help you more. Screenshots:

https://user-images.githubusercontent.com/66517106/220276015-efcbac54-f573-4664-b10f-60f6ef39bc29.png
https://user-images.githubusercontent.com/66517106/220276036-586d9cf6-0781-468a-ab16-0152942a652e.png

You need to check yourself if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by king-iskan** [comment]
> Well, I can go through all 6 steps and to the next site, so sorry can't help you more. Screenshots:
> 
> https://user-images.githubusercontent.com/66517106/220276036-586d9cf6-0781-468a-ab16-0152942a652e.png https://user-images.githubusercontent.com/66517106/220276015-efcbac54-f573-4664-b10f-60f6ef39bc29.png
> 
> You need to check yourself if you are using any:
> 
>     * Custom filters,
> 
>     * Other extensions,
> 
>     * Browser's built-in blocker,
> 
>     * DNS blocking methods,
> 
>     * Blocking apps/softwares outside browser,
> 
>     * OS' hosts file to block domains.
> 
> 
> Good luck

It seems there is something wrong with the ublock origin setting on my mobile phone.  after i reset to default settings and update filters.  finally got resolved.  Sorry to bother.  Thank You.🙏
