### ISSUE TITLE
adshnk.com: detection

### ISSUE THREAD

**Issue by Theorchero** [uBlockOrigin/uAssets#16868]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://adshnk.com/OTE1MDU=/https://hitf.cc/EQkNmZ2`

### Category

detection

### Description

adshnk.com 

Exact link I was using: 
`https://adshnk.com/OTE1MDU=/https://hitf.cc/EQkNmZ2`

Message that is displayed: https://i.gyazo.com/671f4e6dcbf9c72f66c4915fa22c7d9c.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 127242
  cosmetic: 113546
  scriptlet: 18907
  html: 885
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 84138-23008, 5d.16h.48m
    fanboy-social: 22634-7, 2d.7h.25m
    curben-phishing: 36882-8, 54m
    curben-pup: 195-0, 54m
  default: 
    user-filters: 154-12, never
    ublock-filters: 32915-54, 3d.4h.30m
    ublock-badware: 4362-5, 3d.4h.29m
    ublock-privacy: 321-0, 2h.54m
    ublock-abuse: 79-0, 2h.53m
    ublock-unbreak: 1907-0, 3d.4h.28m
    easylist: 61711-641, 5d.6h.8m
    easyprivacy: 30969-1748, 5d.6h.7m
    urlhaus-1: 6000-0, 54m
    plowe-0: 3676-2, 10d.12h.47m
    ublock-quick-fixes: 296-0, 54m
filterset (user): [array of 150 redacted]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 288 ms (selfie)
  maxAssetCacheWait: 335 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    adshnk.com: 1
    2mdn.net: 1
    cdn4ads.com: 1
    google-analytics.com: 1
    sentry-cdn.com: 1
    smartlook.com: 1
    trackjs.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

Did you?

**Comment by Theorchero** [comment]
Yes I did!

Though it works now (And now I feel dumb..)

**Comment by stephenhawk8054** [comment]
I can't see any thing broken. Screenshot:

https://user-images.githubusercontent.com/66517106/220276800-6a8d72af-a93d-4fdb-8525-5d5c637963f8.png

Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

Good luck

**Comment by okiehsch** [comment]
@stephenhawk8054 
You can download the file?

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 You can download the file?

Yes, it leads me to `hitfile.net` page:

https://user-images.githubusercontent.com/66517106/220285960-8d91d2da-e3f6-44c5-a623-9a740947821d.png

and I can download (`Free download` one) on that page normally.

**Comment by okiehsch** [comment]
After clicking Continue I see
![image](https://user-images.githubusercontent.com/16838044/220286544-bcef2d10-96dc-4830-bb79-13af961e7b60.png)

Step one works step two is not responsive on my end.

**Comment by stephenhawk8054** [comment]
I only have 1 step. Might relate to geo location?

**Comment by okiehsch** [comment]
> Might relate to geo location?

On my end it's a browser issue, using Firefox I get the 1 step screen, using Chrome I get the 2 step screen.

**Comment by stephenhawk8054** [comment]
> > Might relate to geo location?
> 
> On my end it's a browser issue, using Firefox I get the 1 step screen, using Chrome I get the 2 step screen.

Yeah, I confirm it happens with chromium on my end too. You need to click on the 2 buttons: 1st one to load countdown ads, 2nd one to load a search page with ads and you need to click on the results with ads there.

**Comment by okiehsch** [comment]
> 2nd one to load a search page with ads and you need to click on the results with ads there.

That does not work on my end, I get an anti adblock warning even if I allow everything, maybe something to do with the laptop I am on now.

**Comment by stephenhawk8054** [comment]
This enough works for me on chromium

```adb
adshnk.com##+js(nano-sib, countdown, *, 0.02)
```

I still can't reproduce any anti-adblock

**Comment by okiehsch** [comment]
> I still can't reproduce any anti-adblock

![image](https://user-images.githubusercontent.com/16838044/220319585-a60bad02-3917-45e9-903d-6b1ab3b1acb1.png)

If I click the button I get an error message even with uBO disabled, but like I mentioned I use a work laptop atm and it has 3rd party security software that I can't disable.


`adshnk.com##+js(nano-sib, countdown, *, 0.02)`
works for me.

**Comment by okiehsch** [comment]
OK, maybe I got confused by the symbol, still I can't finish the task unless I add 
`adshnk.com##+js(nano-sib, countdown, *, 0.02)`
