### ISSUE TITLE
8tracks detecting nano defender

### ISSUE THREAD

**Issue by MidnightMemory** [uBlockOrigin/uAssets#1686]
### URL(s) where the issue occurs

8tracks.com

### Issue

8tracks detects sites with adblock, and doesn't let you use any functions (listening to music) if adblock is enabled. for some reason, even though i have nano defender installed and working, 8tracks still detects the nano adblock blocking its ads.

### Versions

- Browser/version: Version 64.0.3282.186 (Official Build) (64-bit)
- uBlock Origin version: Nano Adblocker v1.0.0.34

### Settings

- none, all set to default

### Notes

i use a vpn based in canada on 8tracks to avoid the listening time limit. i don't think it's part of the issue, since it has no effect on other sites, but i'm including it just in case.

**Comment by mapx-** [comment]
You should test without vpn and test also uBo (disabling nano). I get no anti adb on FF / chrome + uBo.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/37237842-f60a0872-23d6-11e8-8418-12e5a95d9f49.png)

**Comment by okiehsch** [comment]
I can not reproduce the anti-adblock message, but I can see the bait script,
`@@||8tracks.com/ads.js$script,first-party` should fix it.

**Comment by okiehsch** [comment]
OK, I can reproduce using a canadian IP, I will add a fix.

**Comment by jspenguin2017** [comment]
@mapx- If you can't reproduce on uBO, please just ping me.

**Comment by MidnightMemory** [comment]
@jspenguin2017 i'm not sure how to reopen an issue, however it seems 8tracks has reinforced their anti adblock, as i can (once again) no longer get past it. i'm not sure if i should write a new issue or not, and if i should, i apologize for pinging you

**Comment by jspenguin2017** [comment]
@okiehsch `8tracks.com##+js(set-constant.js, App.views.adsView.adblock, false)`
