### ISSUE TITLE
chromeunboxed.com: nuisance

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#16861]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chromeunboxed.com/`

### Category

nuisance

### Description

Split second ezodn overlay with EasyPrivacy enabled. Can this be instant?
Seen on multiple websites.

`https://user-images.githubusercontent.com/91396482/220176111-5c0e9c96-b653-4ecb-8c45-85952461b7c9.mp4`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 103
filterset (summary): 
  network: 75437
  cosmetic: 39901
  scriptlet: 16947
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1374-0, 18h.36m
  default: 
    user-filters: 5-0, never
    easylist: 62137-58, 4d.7h.55m
    easyprivacy: 30989-2097, 4d.7h.55m
    ublock-abuse: 79-0, 4d.7h.55m
    ublock-badware: 4417-120, 16m
    ublock-filters: 32009-141, 15m
    ublock-privacy: 276-0, 4d.7h.55m
    ublock-quick-fixes: 169-18, 13m
    ublock-unbreak: 1902-44, 14m
filterset (user): [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 422 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    chromeunboxed.com: 9
    amazon-adsystem.com: 1
    doubleclick.net: 1
    ezodn.com: 3
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
Now you'll have the normal cookies dialogue.

If you want to hide it just use fanboy's annoyances list or Adguard annoyances list

**Comment by Daxy7** [comment]
`EasyPrivacy` is blocking the modal again.
[Allowed filters aren't coming through](https://user-images.githubusercontent.com/91396482/228339517-6f5ef389-4d2e-45f3-9dcf-965702eeec8c.png)?
