### ISSUE TITLE
multiup.net: detection

### ISSUE THREAD

**Issue by naughtok** [uBlockOrigin/uAssets#16879]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Multiup detects adblock when trying to download a file. 

### URL(s) where the issue occurs.

```
https://multiup.net
https://megaup.net/1Q8ab/SPIDERMAN.MILES.MORALES.UPDATE.1.1121.0.0.rar
```

### Screenshot(s)

https://user-images.githubusercontent.com/100434365/220397745-3d210841-4b5d-4798-b2ec-4b8c248974da.png

### uBO version

1.46.0

### Browser name and version

Google Chrome Version 110.0.5481.104 (Official Build) (64-bit)

### Settings

- none

### Notes

Originally tried in Firefox with many other extensions running. Tried it in a brand new unmodified chrome and got the same result.

**Comment by Daxy7** [comment]
Works on hard mode, guess it is some js or xhr that needs correcting
`https://user-images.githubusercontent.com/91396482/220494408-f388bb68-312f-4973-83b3-3ed731ce2883.png`
Downloading:
`https://user-images.githubusercontent.com/91396482/220494222-47a370fe-eb3e-4c48-acfe-b269d639fb45.png`

**Comment by mapx-** [comment]
@naughtok 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
