### ISSUE TITLE
poczta.wp.pl: breakage

### ISSUE THREAD

**Issue by pawcik2016** [uBlockOrigin/uAssets#16877]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://poczta.wp.pl/login/login.html`

### Category

breakage

### Description

The page is not displaying correctly..

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Chromium: 110
filterset (summary): 
  network: 84917
  cosmetic: 46152
  scriptlet: 17180
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    POL-0: 7875-8, 7h.23m
    POL-2: 1275-13, 7h.23m
    easylist: 62229-73, 7h.20m
    easyprivacy: 30984-1172, 7h.19m
    plowe-0: 3675-910, 7h.18m
    ublock-abuse: 79-0, 7h.16m
    ublock-badware: 4387-121, 59m
    ublock-filters: 32027-177, 58m
    ublock-privacy: 274-1, 57m
    ublock-quick-fixes: 301-18, 56m
    ublock-unbreak: 1904-45, 55m
    urlhaus-1: 5952-0, 54m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 136 ms (selfie)
  maxAssetCacheWait: 101 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    wp.pl: 3
    doubleclick.net: 1
    gemius.pl: 1
    grupawp.pl: 1
    inistrack.net: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
How should the site looks like?

Without adblocker the site loading a huge adbanner which hides all except the login panel. With uBO enabled i get the same but the adbanner is hidden

**Comment by garry-ut99** [comment]
> Without adblocker the site loading a huge adbanner which hides all except the login panel. With uBO enabled i get the same but the adbanner is hidden

Same here, no breakage, (not logged in), but I don't have an account on WP thus I can't say what happens after logging in.

**Comment by krystian3w** [comment]
After logon still fine.

But possible generate breakage by open "/WP" or "/O2" spam mails to have free account - also once MajkiIT filter break load image/text in that spam e-mail.

**Comment by krystian3w** [comment]
To recover  hidden intentionally (deliberately/on purpose) elements by WP company maybe needed is remove randomized class (on body), inline style tag (at end of body) or revert by css filters fixed positioning (the hardest):

![image](https://user-images.githubusercontent.com/35370833/220612525-d6944b9e-2215-46f6-b3f4-cfbbab50870a.png)

**Comment by Daxy7** [comment]
When accepting/rejecting cookies, the layout shifts to that adbanner stylesheet

`https://user-images.githubusercontent.com/91396482/220653129-d514502a-3826-4321-b4f1-ef74aec33543.mp4`

**Comment by krystian3w** [comment]
This happed even uBo is disabled and helps one of https://github.com/uBlockOrigin/uAssets/issues/16877#issuecomment-1439894174 after accepted by uAsset team (I mean mark as worth to risk break default logic on page e.g. here is "unforgivable" https://github.com/uBlockOrigin/uAssets/issues/16860 / https://github.com/uBlockOrigin/uAssets/issues/16516).

**Comment by garry-ut99** [comment]
> This happed even uBo is disabled

Exactly, it's a site's bug.

**Comment by krystian3w** [comment]
Feature at site due more at middle obscures readable ad.
