### ISSUE TITLE
gab.com: wrongly blocked

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#16878]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Easylist blocks `gab.com##a[rel="noopener"][target="_blank"]`
This caused that in gab messages (`https://gab.com/messages`) links got wrongly hidden.

### URL(s) where the issue occurs.

`https://gab.com/messages/`

### Screenshot(s)

![afbeelding](https://user-images.githubusercontent.com/80090789/220380374-969f8496-452e-44ad-ba25-eef514a70244.png)
![afbeelding](https://user-images.githubusercontent.com/80090789/220380490-bc7ac401-ac02-4f0d-a058-058ee00c41f4.png)

### uBO version

1.47.0

### Browser name and version

FireFox 110

### Settings

```
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 75062
  cosmetic: 40883
  scriptlet: 17189
  html: 887
listset (total-discarded, last-updated): 
  removed: 
    ublock-badware: null
    ublock-abuse: null
    urlhaus-1: null
    ublock-quick-fixes: null
  default: 
    user-filters: 1283-3, never
    ublock-filters: 33539-69, now
    ublock-privacy: 321-0, now
    ublock-unbreak: 1915-0, now
    easylist: 62267-542, now
    easyprivacy: 30962-1768, now
    plowe-0: 3738-1, now
    NLD-0: 2579-20, now
filterset (user): [array of 765 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    opera-scheme
    vivaldi-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 1280 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 21 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 10
  autoUpdateDelayAfterLaunch: 60
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 12px
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 1917 ms (selfie)
  maxAssetCacheWait: 2367 ms

```

**Comment by mapx-** [comment]
@ryanbr
