### ISSUE TITLE
thenounproject.com: breakage

### ISSUE THREAD

**Issue by GooseWithAKnife** [uBlockOrigin/uAssets#16871]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://thenounproject.com/search/icons/?iconspage=1&q=medical%20cross`

### Category

breakage

### Description

icons do not load with ublockorigin enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83423
  cosmetic: 38776
  scriptlet: 16954
  html: 885
listset (total-discarded, last-updated): 
  default: 
    user-filters: 40-0, never
    ublock-filters: 32915-158, 3d.16h.33m
    ublock-badware: 4357-5, 3d.16h.32m
    ublock-privacy: 321-0, 1d.16h.23m
    ublock-abuse: 79-0, 1d.16h.24m
    ublock-unbreak: 1895-0, 3d.16h.31m
    easylist: 62092-519, 1d.16h.26m
    easyprivacy: 30984-1763, 1d.16h.25m
    urlhaus-1: 6000-0, 1h.48m
    plowe-0: 3680-2, 7d.9m
    ublock-quick-fixes: 296-0, 1h.47m
filterset (user): [array of 40 redacted]
trustedset: 
  added: [array of 24 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 148 ms (selfie)
  maxAssetCacheWait: 111 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    doubleclick.net: 8
    google-analytics.com: 1
    googletagmanager.com: 2
    paypal.com: 2
    sentry.io: 1
    stripe.com: 13
```
</details>

**Comment by stephenhawk8054** [comment]
It loads normally for me: https://user-images.githubusercontent.com/66517106/220348791-42406b93-6ab1-4125-8e54-1183dc2c5075.png

Can you force update the filter lists and test again?
