### ISSUE TITLE
deezer.com: detection

### ISSUE THREAD

**Issue by gugugujoo** [uBlockOrigin/uAssets#16874]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.deezer.com/fr/`

### Category

detection

### Description

Clearly the website tells it detects an ad-blocker and that i'd rather shut it off or/subscribe for 10euros a month to get my ears satisfied whit no ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 103327
  cosmetic: 47464
  scriptlet: 17045
  html: 885
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 32932-54, 3d.22h.3m
    ublock-badware: 4357-5, 3d.22h.2m
    ublock-privacy: 321-0, 1d.15h.16m
    ublock-abuse: 79-0, 1d.15h.15m
    ublock-unbreak: 1907-0, 3d.22h.1m
    easylist: 61916-623, 2d.6h.30m
    easyprivacy: 30984-1764, 2d.6h.29m
    plowe-0: 3680-2, 5d.11h.1m
    FRA-0: 30003-594, 3d.22h
    urlhaus-1: 6000-0, 4h.22m
    ublock-quick-fixes: 296-0, 4h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1751 ms (selfie)
  maxAssetCacheWait: 1447 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    deezer.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

Did you?

**Comment by MonsieurZed** [comment]
Same error here, Purged and updated

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by MonsieurZed** [comment]
My bad i removed my message. I saw after that the opera adblock was still active.

**Comment by gugugujoo** [comment]
yes i did, but i have to admit i did not verify after. I re-opened Deezer one or two hours later and it worked perfectly. Sorry  i've been bothering you with such easily fixable issue, and thank you to be there.
 
   Le mercredi 22 février 2023 à 03:01:49 UTC+1, stephenhawk8054 ***@***.***> a écrit :  
 
 


   
   -  I forced an update of my filter lists. (Click the "Purge all caches" button while holding the 'Shift' key, then click the "Update now" button.)


Did you?
