### ISSUE TITLE
gyanitheme.com: detection

### ISSUE THREAD

**Issue by yashzade** [uBlockOrigin/uAssets#16884]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gyanitheme.com/?m=1`

### Category

detection

### Description

Starting link:
`https://privatemoviez.cfd/secret/?data=N25EblowOG5lbHpmTHZDdmFzTEJVbmlvVnB4WDVYK1AzVEJGNTFPbURHOD06OsxHyAVSxV8xjJTcbVJx9MQ_e_`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230222_094326_Kiwi Browser](https://user-images.githubusercontent.com/42665606/220520397-6818c783-23d1-4e82-86b6-1293e48b1291.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium Mobile: 107
filterset (summary): 
  network: 92131
  cosmetic: 67214
  scriptlet: 19240
  html: 0
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 82204-34981, now
  default: 
    user-filters: 1-0, never
    adguard-mobile: 8708-32, now
    easylist: 62304-17058, now
    easyprivacy: 30963-1183, now
    plowe-0: 3739-1007, now
    ublock-abuse: 79-0, now
    ublock-badware: 4466-123, now
    ublock-filters: 32838-409, now
    ublock-privacy: 276-8, now
    ublock-quick-fixes: 320-132, now
    ublock-unbreak: 1916-55, now
    urlhaus-1: 5937-0, now
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3072 ms (selfie)
  maxAssetCacheWait: 1372 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    clarity.ms: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    jsdelivr.net: 1
    playstream.media: 1
```
</details>

**Comment by yashzade** [comment]
Still Ad blocker  detected.
I use in Firefox and also purge cache.

**Comment by stephenhawk8054** [comment]
I can't see the anti-adblock after adding the fix: https://user-images.githubusercontent.com/66517106/220550145-d8382ad6-3d30-4ff5-ad30-43c1e6c972b5.png

**Comment by yashzade** [comment]
I use Firefox on android

**Comment by mapx-** [comment]
add & test

```
@@||gyanitheme.com^$ghide
@@||hipsonyc.com^$ghide
```

**Comment by yashzade** [comment]
Working
