### ISSUE TITLE
paizo.com: breakage

### ISSUE THREAD

**Issue by tangentsoft** [uBlockOrigin/uAssets#16883]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On attempting to download purchased digital assets from `https://paizo.com` I got numerous failures, which I eventually traced to a refusal to load `https://matomo.paizo.com/piwik.js`, causing further breakage in the page.

I see other problems with Matomo/Piwik in my "cursory searches of the issue tracker," but nothing specifically for Paizo. This use of analytics looks benign, but I haven't dived deeply into it. All I know for certain is that switching to a browser without uBO installed or disabling uBO on the original browser both solve the problem.

Part of the difficulty in addressing this will be that I only saw it when trying to redeem codes for digital assets I've purchased, so I can't easily give you a URL to test with. I doubt you want to go purchase some Pathfinder e-books purely to test this.

Perhaps part of the problem is that there's a cross-origin loading issue here. Would it help if `paizo.com` loaded this JS from the same origin rather than the subdomain `matomo.paizo.com`?

### URL(s) where the issue occurs.

`https://paizo.com/paizo/account/assets`

### uBO version

1.47.0

### Browser name and version

Firefox 110.0 on macOS 13 initially, then Chrome latest on same to test the without-uBO case

### Settings

I'm not aware of anything other than page filters on specific sites (none of which are `paizo.com`) but I can't be sure because I've been using this for years and I'm not going to reset all of my years worth of incremental settings changes just for a test.

If there's some kind of "Safe  Mode" that won't throw away years of work, and you disagree with me that settings changes are irrelevant to this case, do let me know. I'm willing to try *nondestructive* tests.

**Comment by stephenhawk8054** [comment]
Can you test if adding this filter work?

```adb
@@||matomo.paizo.com/piwik.js$1p
```

**Comment by tangentsoft** [comment]
It looks okay from my inexpert perspective. I had to log out of the site and toss my cache to get it to work, but I was able to log in and download assets with this rule in place, where I was not before.

**Comment by tangentsoft** [comment]
Thank you!
