### ISSUE TITLE
[nsfw] 173.212.240.190: ads

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#16885]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://173.212.240.190/`

### Category

ads

### Description

Too many ads..😬

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox Mobile: 110
filterset (summary): 
  network: 77871
  cosmetic: 47214
  scriptlet: 20315
  html: 1045
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    adguard-spyware-url: 921-4, 13h.57m
    ublock-annoyances: 4857-4, 13h.57m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33657-187, 13h.57m
    ublock-badware: 4470-5, 13h.57m
    ublock-privacy: 321-0, 13h.57m
    ublock-abuse: 79-0, 13h.57m
    ublock-unbreak: 1920-1, 13h.57m
    ublock-quick-fixes: 306-3, 13h.57m
    adguard-mobile: 8708-13, 13h.58m
    easylist: 62267-513, 13h.57m
    easyprivacy: 30962-1189, 13h.57m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1317 ms (selfie)
  maxAssetCacheWait: 650 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    googletagmanager.com: 1
    histats.com: 1
    statically.io: 6
```
</details>

**Comment by mapx-** [comment]
indonesian site, enable the regional list `IDN, MYS: ABPindo`
