### ISSUE TITLE
plaion.com: breakage

### ISSUE THREAD

**Issue by Player701** [uBlockOrigin/uAssets#16888]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://plaion.com/`

### Category

breakage

### Description

Blank page, then shows the following error message after a while:
"JavaScript needs to be enabled and adblockers might affect the functionality, because your consent is compulsory"

Loads fine with uBo disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/9046118/220624609-2b9cf6d8-fe96-476d-a913-5f550be3e937.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 100745
  cosmetic: 60844
  scriptlet: 21156
  html: 1034
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4798-4, 17h.14m
    RUS-0: 39386-178, 22h.49m
  default: 
    user-filters: 79-0, never
    ublock-filters: 32854-40, 17h.15m
    ublock-badware: 4476-5, 17h.16m
    ublock-privacy: 323-0, 6d.22h.52m
    ublock-abuse: 79-0, 6d.6h.57m
    ublock-unbreak: 1909-0, 17h.17m
    easylist: 62069-639, 22h.50m
    easyprivacy: 30988-1746, 22h.51m
    plowe-0: 3675-2, 3d.3h.17m
    urlhaus-1: 5937-0, 27m
filterset (user): [array of 80 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 210 ms (selfie)
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    typekit.net: 2
```
</details>

**Comment by krystian3w** [comment]
@kiboke cookies can be blocked, so this is bad:

```adb
consent.cookiebot.com$domain=~asambeauty.com|~bankia.es|~bergbauernmilch.de|~berlingske.dk|~biomarkt.de|~bt.dk|~cajamar.es|~cineplex.de|~danbolig.dk|~dasinvestment.com|~derivate.bnpparibas.com|~deutschesapothekenportal.de|~digimon.kochfilms.de|~digitaltrends.com|~egmont.com|~ekstrabladet.dk|~epochtimes.de|~finanzmarktwelt.de|~harzwasserwerke.de|~hoyavision.com|~jyllands-posten.dk|~kino.dk|~linak.de|~linak.es|~login.nos.pt|~mein-grundeinkommen.de|~nngroup.com|~scubadiving.com|~spiele-kostenlos-online.de|~stadtmobil.de|~stern.de|~storyhouseegmont.dk|~storyhouseegmont.no|~storyhouseegmont.se|~swspremberg.de|~tme.eu|~werder.de|~werkenbijlidl.nl|~wwf.fi
```

**Comment by krystian3w** [comment]
@THEtomaso you can in free time check other cookies list know from generic block "`cookiebot.com`".

**Comment by THEtomaso** [comment]
Well, appart from the sites that you've already mentioned, **AdGuard Annoyances filter** and **Easylist Cookie List** also contains whitelistings for the following ones:
```
adac-shop.de
berchtesgadener-anzeiger.de
clo3d.com
compress-or-die.com
cookiebot.com
deadwalk.io
koeln.de
lootboy.de
netkom.de
cliente.nos.pt
parkerlebnis.de
popsci.com
puls4.com
radiodresden.de
saveur.com
statisticshowto.com
steuertipps.de
traunsteiner-tagblatt.de
trendsales.dk
wakeboardingmag.com
webradio.de
woolworth.de
```

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/143693

**Comment by kiboke** [comment]
@krystian3w - or, in Croatian, Kristijan :) - thanks, it will be fixed in IDCAC.

@THEtomaso - thanks, I reviewed the list of additional sites and I'll add the ones that really need it.

These don't need an `consent.cookiebot.com` exception because they don't load anything from that subdomain:
```
adac-shop.de
berchtesgadener-anzeiger.de
clo3d.com
compress-or-die.com
cookiebot.com
netkom.de
popsci.com
puls4.com
radiodresden.de
saveur.com
traunsteiner-tagblatt.de
wakeboardingmag.com
webradio.de
woolworth.de
```

These don't need an `consent.cookiebot.com` exception, they seem to work fine with the script blocked:
```
lootboy.de
statisticshowto.com
steuertipps.de
trendsales.dk
```
