### ISSUE TITLE
lifehacker.com: breakage

### ISSUE THREAD

**Issue by CosCal** [uBlockOrigin/uAssets#16891]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lifehacker.com/five-things-youre-not-cleaning-in-your-washing-machine-1849631969`

### Category

breakage

### Description

This breakage is related to playing videos while uBlock origin is enabled. 
The videos on the website fail to play when uBlock origin is enabled, even with it's default settings.
I have followed the exhaustive list of checks as well.

I have tested to confirm that it is in fact being caused by this extension, by:
1) Refreshing lists, as per your instructions. Restart Firefox. Video play problem present.
2) Disable uBlock origin.  Restart Firefox. The video play problem disappears.
3) Re-enable uBlock origin. Restart Firefox. The problem returns.
4) Uninstalling uBlock origin,  Restart Firefox. The problem disappears again.
5) Restart Firefox, re-install uBlock origin with stock settings, restart Firefox, problem returns.
6) Disable all other extensions except uBlock. Restart Firefox. Problem remains. 

My lists used before reset: ![Before_reset](https://user-images.githubusercontent.com/34515453/220735994-083fa74e-bc4a-480f-a1be-b82f8464a144.png)
Stock lists used after reset: ![After_Reset](https://user-images.githubusercontent.com/34515453/220736013-68bd7d03-27bf-4d76-816a-26678273f88a.png)
My Enabled extensions: ![Screenshot from 2023-02-22 14-26-06](https://user-images.githubusercontent.com/34515453/220737616-6bedc24d-2a15-4443-8559-1f8f72e80208.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83602
  cosmetic: 40074
  scriptlet: 19988
  html: 1032
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4798-5, 1d.12h.11m
  default: 
    user-filters: 15-0, never
    ublock-filters: 32907-55, 3d.16h.27m
    ublock-badware: 4391-5, 3d.16h.26m
    ublock-privacy: 321-0, 2d.19h.22m
    ublock-abuse: 79-0, 2d.19h.21m
    ublock-unbreak: 1908-0, 3d.16h.25m
    ublock-quick-fixes: 309-0, 22h.42m
    easylist: 61942-640, 3d.16h.28m
    easyprivacy: 30977-1745, 4d.29m
    urlhaus-1: 6000-0, 22h.41m
    plowe-0: 3675-2, 4d.17h.44m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 164 ms (selfie)
  maxAssetCacheWait: 71 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    lifehacker.com: 3
    adlightning.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    indexww.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
It''s a Firefox specific issue.
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=lifehacker.com`
fixes the issue on my end.

**Comment by CosCal** [comment]
Thank you for the info. 
I'm running Firefox v110.0 (64-bit) on Linux
Adding that line to "My Lists" does in fact re-enable video play. 
Interesting...

**Comment by mapx-** [comment]
@okiehsch 

Yes, the video starts now, but what if you pause it ? Cannot be started again on my end.

I need:

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=lifehacker.com
@@||pubads.g.doubleclick.net/gampad/ads*lifehacker$xhr,domain=imasdk.googleapis.com
||googlevideo.com/videoplayback?expire$media,domain=lifehacker.com,redirect=noopmp3-0.1s
```

**Comment by okiehsch** [comment]
Your right I did not test further after the replay started, so I missed that.

**Comment by CosCal** [comment]
Ah, alas, same glitch here. Video play pauses but will not resume without a page refresh.
I did not catch that glitch right away. (wouldn't have thought that could be a side-effect)
Oddly, it allows seeking with updated frames, but not unpausing.

**Comment by mapx-** [comment]
We have to add the filters in our list.

**Comment by okiehsch** [comment]
I willd add them to unbreak.

**Comment by okiehsch** [comment]
Or not. 😉

**Comment by mapx-** [comment]
It's more a site issue in the end.
