### ISSUE TITLE
masrawy.com: ads leftovers 

### ISSUE THREAD

**Issue by tadtk** [uBlockOrigin/uAssets#16893]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.masrawy.com/`

### Category

ads

### Description

Excuse me, there are a lot of ads leftovers on this website even after updating UBlock filters they still appear. 

### Screenshot(s)

![screenshot 1](https://user-images.githubusercontent.com/126111369/220747897-a447afc1-9f43-41f3-802c-545248940589.png)
![screenshot 2](https://user-images.githubusercontent.com/126111369/220747935-820ee90a-596b-4067-b696-566dfe02de7d.png)
![screenshot 3](https://user-images.githubusercontent.com/126111369/220747955-3b908f36-d686-4b8a-bce2-a51079522f90.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 166792
  cosmetic: 224016
  scriptlet: 37775
  html: 1033
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 68273-5164, 2d.19h.10m
    adguard-mobile: 8704-205, 1d.20h.10m
    adguard-spyware-url: 920-4, 2d.19h.8m
    curben-phishing: 38803-9, 2h.29m
    curben-pup: 200-0, 2h.25m
    adguard-annoyance: 64284-624, 15h.43m
    adguard-social: 19878-834, 15h.39m
    fanboy-annoyance: 84162-6498, 7d.17h.24m
    ublock-annoyances: 4798-5, 15h.41m
    dpollock-0: 11339-474, 5d.23h.57m
    ara-0: 2744-0, 2h.28m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32919-38, 2d.19h.12m
    ublock-badware: 4391-5, 2d.19h.11m
    ublock-privacy: 323-0, 6d.16h.46m
    ublock-abuse: 79-0, 6d.16h.45m
    ublock-unbreak: 1909-1, 2d.19h.9m
    ublock-quick-fixes: 323-17, 2h.27m
    easylist: 62230-1042, 1d.11h.36m
    easyprivacy: 30977-1930, 4d.3h.32m
    urlhaus-1: 5874-0, 2h.26m
    plowe-0: 3675-2, 2d.4h.10m
filterset (user): [array of 1 redacted]
trustedset: 
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1381 ms (selfie)
  maxAssetCacheWait: 843 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    masrawy.com: 2
    crazyegg.com: 1
    crwdcntrl.net: 2
    doubleclick.net: 2
    googlesyndication.com: 1
    googletagmanager.com: 2
    izooto.com: 4
```
</details>

**Comment by mapx-** [comment]
add

```
masrawy.com##.adAsync
masrawy.com##.monsterDiv:has(.adTtl)
masrawy.com##.showcaseDiv:has(.adTtl)
masrawy.com##.billboardDiv:has(.adTtl)
masrawy.com##.leaderboardDiv:has(.adTtl)
```

@smed79 

for the arabic sites you should report directly here:
https://github.com/easylist/listear/issues
