### ISSUE TITLE
lingojam.com: ads

### ISSUE THREAD

**Issue by MaximusFullius** [uBlockOrigin/uAssets#16892]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lingojam.com/FancyTextGenerator`

### Category

ads

### Description

An ad showed up for me on a "Fancy text generator" website (`https://lingojam.com/FancyTextGenerator`). I do have other ad blockers enabled, such as Ghostery and Adblocker Ultimate, but disabling them on the website led to the same result (the ad was still there.) I also disabled **Firefox's** enhanced tracking protection for the site, but ublock origin still wouldn't block the ad. Like the checkboxes said, I also made sure to force an update of my filter lists. I made sure that all of the other prerequisites mentioned in the required checkboxes were met to the best of my ability.

### Screenshot(s)

<details>
<summary>Screenshot(s)
![image](https://user-images.githubusercontent.com/12753462/220744666-5f0cf3da-6ab3-4aaf-976f-f401d33e5d2c.png)

</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 175477
  cosmetic: 223536
  scriptlet: 38256
  html: 1027
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39324-3726, 1d.2h.42m
    ublock-annoyances: 4791-6, 2d.20h.11m
    adguard-generic: 68273-4917, 2d.20h.6m
    adguard-mobile: 8807-85, 2d.20h.7m
    adguard-annoyance: 64180-898, 2d.20h.9m
    adguard-social: 19849-840, 2d.20h.10m
    fanboy-thirdparty_social: 69-3, 8d.6h.34m
    fanboy-annoyance: 84144-6590, 8d.6h.35m
    fanboy-cookiemonster: 45540-45540, 8d.6h.36m
    fanboy-social: 22563-22548, 3d.1h.9m
    adguard-spyware-url: 920-5, 2d.20h.8m
    block-lan: 44-0, 13d.20h.33m
    curben-phishing: 37441-8, 1d.28m
    curben-pup: 195-1, 1d.26m
  default: 
    user-filters: 233-18, never
    ublock-filters: 32919-45, 2d.20h.12m
    ublock-badware: 4391-5, 2d.20h.14m
    ublock-privacy: 321-51, 2d.4h.35m
    ublock-abuse: 79-0, 2d.4h.34m
    ublock-unbreak: 1908-45, 2d.20h.13m
    easylist: 62092-1209, 1d.21h.8m
    easyprivacy: 30949-12414, 1d.21h.7m
    plowe-0: 3675-1072, 3d.1h.10m
    urlhaus-1: 5952-0, 1d.27m
filterset (user): [array of 233 redacted]
trustedset: 
  added: [array of 66 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1986 ms (selfie)
  maxAssetCacheWait: 642 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    btloader.com: 2
    googletagmanager.com: 2
    quantcast.com: 1
    snigelweb.com: 1
```
</details>

**Comment by mapx-** [comment]
1. remove adblock ultimate + ghostery. They are useless and can generate conflicts with uBO.
2. add

```
lingojam.com###adsense-area-label
lingojam.com##[href^="https://animefilter.com"]
```

**Comment by mapx-** [comment]
@ryanbr
