### ISSUE TITLE
chpadblock.com: detection

### ISSUE THREAD

**Issue by Nazosan** [uBlockOrigin/uAssets#16895]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chpadblock.com/`

### Category

detection

### Description

This site appears to offer a service to other sites to do an invasive popup covering the entire page on people's browsers if they have adblockers enabled.  It looks like it even specifically targets uBlock Origin (note the icon from it on their site.)  Each time it generates a random series of characters for the cosmetic it uses to make it hard to target with universal filters.  More specifically, rather than this site itself, it is the mechanisms it uses which should be examined since it deploys this to other sites.  It can be blocked manually each time, but as it's randomly generating characters, setting a filter won't stop it from showing up on the next page load.  Dragging either slider even all the way to the left won't produce a filter wildcard that can stop it.  The darkened area around the central "popup" can't be clicked through, so you can't try to interact around the rather invasive "popup" anyway.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Chrome:
![ChromeAdblock](https://user-images.githubusercontent.com/13072654/220758116-9b8fb1eb-9ee3-4a0d-89fd-79a3f5bdaa5d.jpg)

For some reason it looks different on my Firefox (maybe images simply didn't load for some reason, but I have basically just the default configuration in my Firefox since it's only for sites that give me trouble with Chrome):
![FirefoxAdblock](https://user-images.githubusercontent.com/13072654/220758268-7a359b54-c489-43b6-b4cf-99c1ac754655.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 83925
  cosmetic: 38929
  scriptlet: 17259
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 29-1, never
    easylist: 62346-47, 1m
    easyprivacy: 30963-1172, 1m
    plowe-0: 3739-923, 1m
    ublock-abuse: 79-0, 1m
    ublock-badware: 4591-122, 1m
    ublock-filters: 32760-158, 1m
    ublock-privacy: 276-1, 1m
    ublock-quick-fixes: 322-128, 1m
    ublock-unbreak: 1913-49, 1m
    urlhaus-1: 5874-0, 1m
filterset (user): [array of 29 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3665 ms
  maxAssetCacheWait: 585 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
    translate.googleapis.com: 2
```
</details>

**Comment by Nazosan** [comment]
The Chrome screenshot didn't work right for some reason, so here it is separately.  (Firefox probably should look like this, I suspect my connection was just a bit too slow or something.)
![ChromeAdblock](https://user-images.githubusercontent.com/13072654/220760360-0a99b516-418b-49f6-9861-5f67ba75549e.jpg)

**Comment by mapx-** [comment]
yes, we know chp very well. 
We wont fix their site.

If you know some other unfixed page just report it.
