### ISSUE TITLE
animeflv.ru [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1689]
URL(s) where the issue occurs

`https://animeflv.ru/`

Describe the issue

Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by lain566** [comment]
The video player is broken.
`https://animeflv.ru/ver/2342/naruto-shippuuden-episodio-001`
