### ISSUE TITLE
coinhub.wiki: detection

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#16894]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://coinhub.wiki/link/in/yZLsttKk`

### Category

detection

### Description

detection adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 83919
  cosmetic: 38929
  scriptlet: 17295
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 97-1, never
    easylist: 62346-47, 3h.2m
    easyprivacy: 30963-1172, 3h.2m
    plowe-0: 3739-923, 3h.2m
    ublock-abuse: 79-0, 3h.2m
    ublock-badware: 4586-122, 3h.2m
    ublock-filters: 32762-189, 3h.2m
    ublock-privacy: 276-1, 3h.2m
    ublock-quick-fixes: 322-128, 3h.2m
    ublock-unbreak: 1909-49, 3h.2m
    urlhaus-1: 5874-0, 3h.1m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 25689 ms
  maxAssetCacheWait: 13661 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
test

`@@||coinhub.wiki^$ghide`
