### ISSUE TITLE
Rezonence detects ad blocking and hides context

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#169]
### URL(s) where the issue occurs

http://www.v3.co.uk/v3-uk/news/2474845/linux-users-urged-to-protect-against-dirty-cow-security-flaw

### Describe the issue

When visiting pages with Rezonence ads, the content of the page will be hidden unless advertising can be displayed.

### Screenshot(s)

![Screenshot](https://cloud.githubusercontent.com/assets/16061266/19581005/01756de0-96f8-11e6-9fd4-71b2a20e3bc6.png)

### Versions

- Browser/version: Google Chrome 54.0.2840.59
- uBlock Origin version: 1.9.10

### Settings

- None.

### Notes

This appears to work by including the following code snippet in advertisement JavaScript that we block:
```
(function(){
 
    var id = setInterval(checkAABLoaded,100);
 
    function checkAABLoaded(){
 
        try {
            _r3z.jq("#r3z-wait").hide();
            _r3z.pub.fns.rev();
            clearInterval(id);
 
        } catch(err){
 
        }
    }
 
})();
```
If the above never runs, the text never goes back to normal, and the "disable your ad blocker" message appears. Adding similar code as an injection should fix this. Also, any pure CSS solution is insufficient to fix this, as JavaScript is used to garble the HTML in addition to the redaction CSS (see above in the screenshot where I used the DOM inspector to remove the CSS from one of the hidden paragraphs).

**Comment by Betsy25** [comment]
Sorry, this is definitely not the perfect solution, but until someone knows, blocking 1st party inline scripts gets rid of the hiding.

**Comment by IDKwhattoputhere** [comment]
Try adding `v3.co.uk##script:inject(r3z-defuser.js)`.

**Comment by josephcsible** [comment]
> Try adding ```v3.co.uk##script:inject(r3z-defuser.js)```
That works for me. I didn't know we had that defuser (guess I should have looked). So all we need now is to add that to filters.txt I guess.

**Comment by gorhill** [comment]
@IDKwhattoputhere Thanks for investigating the issue+solution -- added to uBO's filters.
