### ISSUE TITLE
king-ptcs.com: detection

### ISSUE THREAD

**Issue by absouini** [uBlockOrigin/uAssets#16906]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://king-ptcs.com/dashboard`

### Category

breakage

### Description

Network Error
Opps! You might be using an ad blocker.
If you are, please disable it and try again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 106328
  cosmetic: 48427
  scriptlet: 17368
  html: 0
listset (total-discarded, last-updated): 
  added: 
    FRA-0: 30029-34, 5m
    ara-0: 2744-5, 5m
  default: 
    user-filters: 78-3, never
    easylist: 62674-215, 5m
    easyprivacy: 30964-1498, 5m
    plowe-0: 3739-951, 5m
    ublock-abuse: 79-1, 5m
    ublock-badware: 4601-142, 5m
    ublock-filters: 32772-266, 5m
    ublock-privacy: 276-1, 5m
    ublock-quick-fixes: 329-128, 5m
    ublock-unbreak: 1914-50, 5m
    urlhaus-1: 5931-0, 5m
filterset (user): [array of 155 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5913 ms (selfie)
  maxAssetCacheWait: 1276 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adsfcdn.com: 1
    antiadblocksystems.com: 1
    d3cod80thn7qnd.cloudfront.net: 1
    googletagmanager.com: 1
    regie-cpc.com: 1
    reklamstore.com: 3
    surfe.pro: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
For Firefox i need

```
king-ptcs.com##+js(aeld, load, htmls)
king-ptcs.com##^script:has-text(/htmls|google_ad_client/)
king-ptcs.com##+js(acis, addEventListener, google_ad_client)
king-ptcs.com###p7a1:remove()
```

Maybe there is a better fix but i can’t find one

**Comment by mapx-** [comment]
working for me too (chrome)

```
king-ptcs.com##+js(aeld, load, htmls)
king-ptcs.com##+js(acs, addEventListener, google_ad_client)
```

**Comment by JobcenterTycoon** [comment]
Yes but for firefox i need:

```
king-ptcs.com##^script:has-text(/htmls|google_ad_client/)
king-ptcs.com###p7a1:remove()
```

**Comment by mapx-** [comment]
well, add all those filters then

**Comment by absouini** [comment]
thank you

**Comment by jadreas** [comment]
> working for me too (chrome)
> 
> ```
> king-ptcs.com##+js(aeld, load, htmls)
> king-ptcs.com##+js(acs, addEventListener, google_ad_client)
> ```

This works for ourcoincash.xyz too thanks.
Like this:
ourcoincash.xyz##+js(aeld, load, htmls)
ourcoincash.xyz##+js(acs, addEventListener, google_ad_client)
