### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#16907]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

If ublock is enabled it detects adblock, without ublock no detection

### URL(s) where the issue occurs.

`https://megaup.net/2ym9s`

### Screenshot(s)

https://user-images.githubusercontent.com/57501353/220976865-463e9136-bdf6-4cc8-b998-a204383e8175.jpg
https://user-images.githubusercontent.com/57501353/220976870-70ac3713-1015-42c2-815c-29fd0fca24dc.jpg

### uBO version

1.46.0

### Browser name and version

Kiwi browser 110

### Settings

I did add vaft script for twitch. But tested without too

**Comment by mapx-** [comment]
Test in FF mobile

**Comment by erik9012** [comment]
> Test in FF mobile

Same issue
![Screenshot_2023-02-23-21-19-21-765_org mozilla firefox](https://user-images.githubusercontent.com/57501353/221020893-8976136c-4ec7-48d6-bd25-b612517e1909.jpg)
![Screenshot_2023-02-23-21-19-16-930_org mozilla firefox](https://user-images.githubusercontent.com/57501353/221020900-699a436b-ce35-47bc-80d5-528c2f607ab9.jpg)

**Comment by erik9012** [comment]
Is it mobile only?

**Comment by mapx-** [comment]
@ghajini @stephenhawk8054  can you reproduce the detection ?

**Comment by ghajini** [comment]
unable to reproduce with recommended settings on mobile(firefox +ublock origin)

kiwi is not supported, if you want to use kiwi then disable **Hide annoying Ads** feature

**Comment by erik9012** [comment]
Here is the Firefox screenfecord where I Fresh install Firefox https://we.tl/t-IOr1ypvHyP with only ublock. hide annyoing ads is disabled  in Kiwi browser

**Comment by erik9012** [comment]
I dont use hide annyoing ads kiwi browser as it breaks too many sites. I have a vpn somehwere installed but is disabled for this

**Comment by ghajini** [comment]
you forgot to update filter lists

(`https://youtu.be/Onr0frormCU`)

**Comment by erik9012** [comment]
> you forgot to update filter lists
> 
> (`https://youtu.be/Onr0frormCU`)

Ow sorry my bad. I thought that Fresh install gave a force update too which js obviously not the case. Sorry
