### ISSUE TITLE
jkanime.net [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1690]
URL(s) where the issue occurs

`http://jkanime.net/saiki-kusuo-no-nan/`

Describe the issue

Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://jkanime.net/eromanga-sensei-ova/2/`

**Comment by lain566** [comment]
Comments are not displayed.

These filters are breaking it.
```
|https://$third-party,script,domain=descargasnsn.com|jkanime.net
|https://$third-party,xmlhttprequest,domain=descargasnsn.com|jkanime.net
```

`https://jkanime.net/planetarian-hoshi-no-hito/`

<details>

![{71349D5C-67AA-4D5F-8891-89F89E84C656}](https://user-images.githubusercontent.com/27441315/54056461-72790100-41f0-11e9-8a67-5a27e9bfa8d8.png)
</details>

----------------------------------------

`https://jkanime.net/sword-art-online/1/`

<details>

![{C26B4523-603F-4D7F-9FE9-EFD9CFC21057}](https://user-images.githubusercontent.com/27441315/54056511-92102980-41f0-11e9-830b-596cf8e43707.png)
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ef36332745cbf137e0ed48b19911587ab11a126d
