### ISSUE TITLE
uBlock Origin disables dark mode on new 9to5mac in Arc browser

### ISSUE THREAD

**Issue by MrAbidPatel** [uBlockOrigin/uAssets#16901]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Just installed uBlock Origin on Arc browser and found that it seems to break dark mode on 9to5mac.com when uBlock Origin is enabled. The option to toggle between light and dark mode doesn't do anything. Disabling uBlock Origin seems to fix the issue. Just checked Google Chrome and the issue doesn't seem to occur on Chrome.

### A specific URL where the issue occurs.

9to5mac.com

### Steps to Reproduce

Simply visit the website to uBlock Origin enabled.
Try to toggle between light and dark mode in the top left corner.

### Expected behavior

Should be able to toggle between light and dark mode.

### Actual behavior

Website only appears in light mode. Toggle to change to dark mode doesn't respond to clicks when uBlock Origin is enabled.

### uBO version

uBlock Origin 1.47.2

### Browser name and version

Arc browser version 0.90.0 (37254)

### Operating System and version

macOS Ventura 13.1

**Comment by MrAbidPatel** [comment]
Thank you for your help. That fixed the issue in Arc 👍

**Comment by krystian3w** [comment]
Also possible extend to:

`@@||cdn.viglink.com/api/vglnk.js$script,domain=9to5mac.com|electrek.co`

other don't have disable button or works diffrent (9to5google).
