### ISSUE TITLE
6play.fr: detection

### ISSUE THREAD

**Issue by cabaud** [uBlockOrigin/uAssets#16905]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.6play.fr/mission-travaux-ma-maison-est-un-chantier-p_21336/emission-2-c_12985094`

### Category

ads

### Description

la publicité n'est pas bloquée

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 104265
  cosmetic: 47686
  scriptlet: 17362
  html: 896
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33600-393, 3m
    ublock-badware: 4605-5, 3m
    ublock-privacy: 323-0, 3m
    ublock-abuse: 79-0, 3m
    ublock-unbreak: 1925-4, 3m
    ublock-quick-fixes: 333-4, 3m
    easylist: 62674-523, 3m
    easyprivacy: 30964-2060, 3m
    urlhaus-1: 5931-0, 3m
    plowe-0: 3739-2, 3m
    FRA-0: 30029-288, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 772 ms
  maxAssetCacheWait: 306 ms
popupPanel: 
  blocked: 187
  blockedDetails: 
    2mdn.net: 4
    adsafeprotected.com: 10
    adsrvr.org: 9
    doubleclick.net: 3
    estat.com: 1
    facebook.net: 1
    fwmrm.net: 29
    google.com: 1
    googlesyndication.com: 12
    googletagmanager.com: 1
    googletagservices.com: 1
    gstatic.com: 6
    imrworldwide.com: 2
    m6web.fr: 92
    newrelic.com: 2
    outbrain.com: 1
    pghub.io: 1
    sddan.com: 1
    smartclip.net: 2
    stickyadstv.com: 1
    tealiumiq.com: 3
    usabilla.com: 1
    youborafds01.com: 3
```
</details>

**Comment by mapx-** [comment]
It's not clear, do you get detection or you get ads playing the video ?

**Comment by mapx-** [comment]
I get anti adblocking, this is working on my side

`@@||7cbf2.v.fwmrm.net^$xhr,domain=6play.fr`
