### ISSUE TITLE
behealthymagazine.abczdrowie.pl: nuisance

### ISSUE THREAD

**Issue by Bednar87** [uBlockOrigin/uAssets#16909]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://behealthymagazine.abczdrowie.pl/zlota-czworka-naturalnych-probiotykow-znajdziesz-je-w-swojej-kuchni,6861933191572064a`

### Category

nuisance

### Description

uBlock seems to be detected and an annyoing popup/overlay shows up. it doesn't seem to want to go away

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![2023-02-23_20-32](https://user-images.githubusercontent.com/42691446/221011553-37c2f415-fdac-4222-b864-29f8a7bdb809.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83399
  cosmetic: 38770
  scriptlet: 16957
  html: 886
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32918-38, 3d.11h.26m
    ublock-badware: 4391-5, 3d.11h.25m
    ublock-privacy: 321-0, 3d.3h.21m
    ublock-abuse: 79-0, 3d.3h.20m
    ublock-unbreak: 1909-0, 3d.11h.24m
    ublock-quick-fixes: 326-17, 4h.53m
    easylist: 62092-622, 3d.11h.28m
    easyprivacy: 30988-1762, 3d.11h.27m
    urlhaus-1: 5931-0, 4h.52m
    plowe-0: 3676-2, 10d.11h.14m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 418 ms (selfie)
  maxAssetCacheWait: 129 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    3lift.com: 1
    adform.net: 1
    adnxs.com: 1
    adscale.de: 1
    casalemedia.com: 1
    connectad.io: 1
    creativecdn.com: 1
    criteo.net: 2
    emxdgt.com: 1
    facebook.net: 1
    gemius.pl: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    id5-sync.com: 1
    openx.net: 1
    pubmatic.com: 1
    rubiconproject.com: 1
    smartadserver.com: 1
    wp.pl: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
For what is `behealthymagazine.abczdrowie.pl##[href*="/?utm_source="]`? The left top button getting hidden with this filter but its just a button which redirect the user to the main page `https://portal.abczdrowie.pl/`

**Comment by mapx-** [comment]
Go ahead and fix it - I have no access to a pc till may 11
