### ISSUE TITLE
Impossible to star https://github.com/rrweb-io/rrweb on GitHub

### ISSUE THREAD

**Issue by TomasHubelbauer** [uBlockOrigin/uAssets#16900]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi, when going to https://github.com/rrweb-io/rrweb while signed into GitHub with uBO enabled, clicking the Star button on this repo doesn't do anything and in the Network tab I can see the POST request to the GitHub API to start the repo is blocked by uBO.

### URL(s) where the issue occurs.

`https://github.com/rrweb-io/rrweb`
`https://github.com/rrweb-io/rrweb/star`
`https://github.com/rrweb-io/rrweb/unstar`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/6831144/220845734-853c6411-6471-4a32-bf32-1f9c33ed7b72.png)

### uBO version

1.47.0

### Browser name and version

Firefox 110.0

### Settings

None

**Comment by mapx-** [comment]
add
`@@||github.com/rrweb-io/rrweb/$xhr,1p`

@ryanbr 

still needing `/rrweb/*` ?
