### ISSUE TITLE
nsw2u.com: detection

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#16904]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nsw2u.com/`

### Category

detection

### Description

It detects the use of uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 97062
  cosmetic: 102549
  scriptlet: 19252
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 64340-97, 22h.47m
  default: 
    user-filters: 65-3, never
    ITA-0: 13470-0, 22h.44m
    easylist: 64987-117, 3d.5h.6m
    easyprivacy: 30977-1258, 4d.22h.55m
    plowe-0: 3676-900, 12d.13h.44m
    ublock-abuse: 79-0, 5h.20m
    ublock-badware: 4591-110, 17h.48m
    ublock-filters: 31519-495, 17h.47m
    ublock-privacy: 276-1, 5h.19m
    ublock-quick-fixes: 319-14, 22h.46m
    ublock-unbreak: 1904-48, 17h.46m
    urlhaus-1: 5874-0, 22h.45m
filterset (user): [array of 65 redacted]
trustedset: 
  added: [array of 20 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5561 ms (selfie)
  maxAssetCacheWait: 162 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    amazon-adsystem.com: 1
    doubleclick.net: 1
    google-analytics.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    media.net: 1
    quantserve.com: 1
    sovrn.com: 1
    whairtoa.com: 2
    wp.com: 1
```
</details>

**Comment by theinstantmatrix** [comment]
Dead domain: Seized by government
