### ISSUE TITLE
streamz.ws: detection

### ISSUE THREAD

**Issue by gettysburg** [uBlockOrigin/uAssets#16915]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Tried streaming an episode of Star Trek TOS through StreamZ, but they detect uBlock Origin and play an 18 second video which tells you to turn it off instead.

Happens on embedded links or directly on one of their many domains, purged caches and updated all lists, still no luck

They also try to detect if the debug console is opened, by inserting the JS `debugger` statement, which acts like a breakpoint if any debugger is available, which is the case if you open the debug console, regardless of what console tab is opened.
```html
<script>
	var tryCount = 0;
	var minimalUserResponseInMiliseconds = 200;
	
    function check() {
		console.clear();	
		before = new Date().getTime();	
		debugger;	
		after = new Date().getTime();
	}
    
	if(after - before > minimalUserResponseInMiliseconds){document.write(" Dont open Developer Tools.");
</script>
```

This is just one example, I've seen more code like this but due to mangled and obfuscated JS I couldn't find the main AdBlock check yet.

### URL(s) where the issue occurs.

```
https://streamkiste.tv/serie/raumschiff-enterprise-0060028

https://streamz.to
https://streamz.cc
https://streamz.ws
https://streamz.vg

```

### uBO version

1.47.1b1

### Browser name and version

102.8.0esr

### Settings

Enabled all built in filter lists, additionally re-added the filter lists "MVPS hosts" and "AdGuard Tracking Protection" which were removed from the built-in set of lists in previous uBlock Origin updates.

Other changes:

```
autoUpdateAssetFetchPeriod 5
autoUpdateDelayAfterLaunch 15
```

### Notes

I have included all known TLD's from StreamZ just for completeness - **if you actually want to reproduce the detection**, visit the first site, StreamKiste.tv, select any episode, choose StreamZ as the mirror and try to start watching - you will likely get the 18 second "AdBlock detected" video.

**Comment by stephenhawk8054** [comment]
That 18-second video happens even when I turn off uBO, and I cannot proceed to actual video either.

**Comment by ghajini** [comment]
site issue

**Comment by gettysburg** [comment]
Okay, great, thanks for removing the anti devtools stuff too.

**Comment by gettysburg** [comment]
Okay,, I will wait for them to fix it then. 

Thanks for dealing with the anti developer-tool scripts too.
