### ISSUE TITLE
6play.fr: detection

### ISSUE THREAD

**Issue by Mison44** [uBlockOrigin/uAssets#16910]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.6play.fr/the-shield-p_23254/s4-e11-un-temoin-capital-c_12987999`

### Category

detection

### Description

It seems that the website is able to know that i am using ublock. I watched a video on the same website yesterday and it was working fine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://user-images.githubusercontent.com/126199190/221011299-5aed8831-06e4-4c1a-914a-a3ede50a325b.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 103554
  cosmetic: 47567
  scriptlet: 17047
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30003-34, 3d.23h.2m
    easylist: 62346-141, 22h.39m
    easyprivacy: 30963-1492, 22h.38m
    plowe-0: 3676-932, 10d.23h.22m
    ublock-abuse: 79-1, 22h.41m
    ublock-badware: 4387-141, 3d.23h.5m
    ublock-filters: 32099-241, 3d.23h.4m
    ublock-privacy: 276-1, 22h.40m
    ublock-quick-fixes: 322-18, 22h.36m
    ublock-unbreak: 1898-45, 3d.23h.3m
    urlhaus-1: 5874-0, 22h.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3898 ms (selfie)
  maxAssetCacheWait: 255 ms
popupPanel: 
  blocked: 158
  blockedDetails: 
    adsafeprotected.com: 5
    estat.com: 1
    fwmrm.net: 10
    googlesyndication.com: 6
    m6web.fr: 107
    newrelic.com: 9
    smartclip.net: 2
    tealiumiq.com: 14
    youborafds01.com: 4
```
</details>

**Comment by mapx-** [comment]
fixed 1 hour ago, update all your lists
