### ISSUE TITLE
sozcu.com.tr: detection

### ISSUE THREAD

**Issue by Remdosa** [uBlockOrigin/uAssets#16921]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sozcu.com.tr/`

### Category

detection

### Description

Redirects to an "adblock detected" page https://www.sozcu.com.tr/reklam-engelleyici

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 83853
  cosmetic: 38746
  scriptlet: 16989
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62348-47, 21h.29m
    easyprivacy: 30963-1172, 21h.30m
    plowe-0: 3739-923, 21h.32m
    ublock-abuse: 79-0, 21h.25m
    ublock-badware: 4596-122, 21h.24m
    ublock-filters: 32049-141, 21h.23m
    ublock-privacy: 276-1, 21h.26m
    ublock-quick-fixes: 322-21, 21h.28m
    ublock-unbreak: 1913-48, 21h.22m
    urlhaus-1: 5949-0, 21h.27m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2207 ms (selfie)
  maxAssetCacheWait: 78 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    sozcucdn.com: 1
```
</details>

**Comment by ghajini** [comment]
add regional list **adguard turkish** from ubo settings
