### ISSUE TITLE
bigbearmountainresort.com: breakage

### ISSUE THREAD

**Issue by jpswanson** [uBlockOrigin/uAssets#16928]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bigbearmountainresort.com/transportation/road-condition-updates`

### Category

breakage

### Description

uBO is blocking the main content area of this web site. It loads properly when uBO is disabled. See the screenshot below for the correct behavior. This content, starting with "Last Updated" and continuing through the second "R3 CHAINS REQUIRED ALL VEHICLES" simply does not appear when uBO is enabled.

The same basic issue occurs at https://www.bigbearmountainresort.com/mountain-information

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![BBMR_content_issue](https://user-images.githubusercontent.com/8871374/221335005-0268bb9e-cbbd-4353-895d-d1f56df8866f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 88881
  cosmetic: 96033
  scriptlet: 22425
  html: 1031
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
    ublock-annoyances: 4800-4, 1d.23h.3m
    adguard-annoyance: 64353-749, 1d.22h.59m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32872-41, 1d.23h.4m
    ublock-badware: 4600-5, 1d.23h
    ublock-privacy: 323-0, 1d.23h.6m
    ublock-abuse: 79-0, 1d.23h.5m
    ublock-unbreak: 1924-0, 1d.23h.2m
    easylist: 62346-643, 1d.23h.7m
    easyprivacy: 30963-1751, 1d.23h.8m
    plowe-0: 3680-2, 8d.20h.34m
    urlhaus-1: 5797-0, 2h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 18 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 372 ms (selfie)
  maxAssetCacheWait: 353 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    cookielaw.org: 1
    googletagmanager.com: 1
    newrelic.com: 1
    nr-data.net: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by

```adb
||cookielaw.org^$3p
```

in your added `AdGuard Annoyances` list.

@Yuki2718 It's not always reproducible, might need to clear cookies
