### ISSUE TITLE
roblox.cashstar.com: [unknown]

### ISSUE THREAD

**Issue by ouwais012** [uBlockOrigin/uAssets#16925]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://roblox.cashstar.com/`

### Category

[unknown]

### Description

OUWAIS

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 109
filterset (summary): 
  network: 103402
  cosmetic: 47482
  scriptlet: 17060
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 30004-34, 3d.21h.2m
    easylist: 62296-140, 1d.23h.58m
    easyprivacy: 30955-1492, 1d.23h.57m
    plowe-0: 3675-932, 6d.20h.2m
    ublock-abuse: 79-1, 2d.19h.42m
    ublock-badware: 4387-141, 3d.21h.5m
    ublock-filters: 32024-244, 3d.21h.4m
    ublock-privacy: 276-1, 2d.19h.41m
    ublock-quick-fixes: 331-18, 2h.41m
    ublock-unbreak: 1902-45, 3d.21h.3m
    urlhaus-1: 5774-0, 2h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6906 ms (selfie)
  maxAssetCacheWait: 762 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by ouwais012** [comment]
OWUIS

**Comment by mapx-** [comment]
> OUWAIS

try again
