### ISSUE TITLE
wplocker.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#16929]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wplocker.com/template/themeforest-themes/67607167-konstrakt-v113-wordpress-theme-for-construction.html`

### Category

ads

### Description

![image](https://user-images.githubusercontent.com/19517680/221339756-36c265f8-9af5-4448-8d23-34f9bea3b2bd.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 112
filterset (summary): 
  network: 134618
  cosmetic: 139826
  scriptlet: 25291
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39330-3726, 2d.15h.27m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7830-2, 2d.15h.27m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-4, 2d.15h.27m
    IDN-0: 5445-358, 2d.15h.27m
    RUS-0: 39405-205, 5h.50m
    fanboy-annoyance: 82155-415, 2d.15h.27m
    fanboy-cookiemonster: 45660-45660, 2d.15h.27m
    ublock-annoyances: 4841-82, 2d.15h.27m
  default: 
    user-filters: 28-0, never
    easylist: 62346-110, 2d.15h.27m
    easyprivacy: 30963-12367, 2d.15h.27m
    ublock-abuse: 79-1, 2d.15h.27m
    ublock-badware: 4486-121, 2d.15h.27m
    ublock-filters: 32743-526, 2d.15h.27m
    ublock-privacy: 276-59, 2d.15h.27m
    ublock-quick-fixes: 331-128, 2h.55m
    ublock-unbreak: 1913-75, 2d.15h.27m
    urlhaus-1: 5797-0, 2h.54m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 34 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7499 ms (selfie)
  maxAssetCacheWait: 735 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    demand.supply: 1
    popads.net: 1
    statcounter.com: 1
```
</details>

**Comment by 3xploiton3** [comment]
@ryanbr

**Comment by mapx-** [comment]
add
`wplocker.com##[href^="https://bluehost.sjv.io/"]`

open an issue directly at [easylist repository](https://github.com/easylist/easylist/issues)
