### ISSUE TITLE
bolnews.com: ads

### ISSUE THREAD

**Issue by johnconner122** [uBlockOrigin/uAssets#16920]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bolnews.com/technology/2023/02/infinix-note-12-price-in-pakistan-special-features-2/`

### Category

ads

### Description

ads leftovers.

### Screenshot(s)

https://user-images.githubusercontent.com/107796137/221126457-cab2e275-2629-492e-a9ea-4bf2b2780810.png

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 246123
  cosmetic: 290497
  scriptlet: 41026
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39330-3726, 1d.14h.46m
    CHN-0: 28190-114, 2d.19m
    CZE-0: 736-4, 51m
    DEU-0: 6544-3, 53m
    FIN-0: 2151-0, 2d.13h.50m
    FRA-0: 30026-124, 2d.18m
    GRC-0: 995-0, 19h.42m
    ISR-0: 1675-2, 52m
    ITA-0: 13470-79, 58m
    JPN-1: 9737-34, 2d.17m
    KOR-1: 4217-41, 50m
    LTU-0: 1219-8, 6d.22h.45m
    NLD-0: 2574-21, 14h.22m
    SWE-1: 4367-16, 2d.13h.51m
    THA-0: 1466-3, 14h.21m
    TUR-0: 12194-35, 2d.16m
    VIE-1: 1802-7, 54m
    adguard-annoyance: 64287-342, 2d.14m
    adguard-generic: 68505-1737, 2d.15m
    adguard-mobile: 8708-133, 2d.12m
    [13 lists not shown]: [too many]
  default: 
    user-filters: 59-2, never
    easylist: 62346-1519, 20h.33m
    easyprivacy: 30963-12830, 20h.32m
    plowe-0: 3676-1450, 11d.23h.1m
    ublock-abuse: 79-1, 1d.22h.29m
    ublock-badware: 4486-345, 1d.17h.7m
    ublock-filters: 32037-4113, 1d.17h.6m
    ublock-privacy: 276-63, 1d.22h.28m
    ublock-quick-fixes: 331-52, 57m
    ublock-unbreak: 1913-133, 1d.17h.5m
    urlhaus-1: 5916-2, 56m
filterset (user): [array of 59 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4396 ms (selfie)
  maxAssetCacheWait: 1090 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 2
    onesignal.com: 1
    resonance.pk: 1
    youtube.com: 1
```
</details>

**Comment by johnconner122** [comment]
> ```
> bolnews.com##.adspadding
> bolnews.com##.advertising
> bolnews.com##.adsheading
> bolnews.com##[style*="center"]:has-text(Ad)
> ```

What will be equivalent filter syntax for brave browser's built-in adblocker?

**Comment by mapx-** [comment]
same syntax
