### ISSUE TITLE
dragontea.ink: detection

### ISSUE THREAD

**Issue by asidsx** [uBlockOrigin/uAssets#16926]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dragontea.ink/novel-genre/comics/`

### Category

detection

### Description

If this screen persists please try clearing history and cache, disabling adblock, or changing browser.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 107
filterset (summary): 
  network: 194962
  cosmetic: 191069
  scriptlet: 37931
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ALB-0: 301-4, 14h.15m
    BGR-0: 1091-11, 14h.15m
    CHN-0: 28224-103, 14h.15m
    CZE-0: 736-0, 14h.15m
    DEU-0: 6544-0, 14h.15m
    EST-0: 458-2, 10h.14m
    FIN-0: 2151-0, 14h.14m
    FRA-0: 30029-84, 14h.14m
    GRC-0: 995-0, 14h.14m
    HUN-0: 2155-2, 14h.14m
    IDN-0: 5453-20, 14h.14m
    IND-0: 12359-0, 14h.14m
    IRN-0: 2880-32, 14h.14m
    ISL-0: 194-1, 14h.14m
    ISR-0: 1675-2, 14h.14m
    ITA-0: 13470-78, 14h.14m
    JPN-1: 9804-13, 14h.14m
    KOR-1: 4222-34, 14h.14m
    LTU-0: 1219-7, 14h.14m
    LVA-0: 396-4, 14h.14m
    [16 lists not shown]: [too many]
  default: 
    user-filters: 3-0, never
    RUS-0: 39413-209, 14h.14m
    easylist: 62719-1409, 14h.14m
    easyprivacy: 30966-1819, 14h.14m
    plowe-0: 3739-1086, 14h.14m
    ublock-abuse: 79-2, 14h.14m
    ublock-badware: 4591-344, 14h.14m
    ublock-filters: 32747-3908, 14h.14m
    ublock-privacy: 276-3, 14h.14m
    ublock-quick-fixes: 331-138, 14h.14m
    ublock-unbreak: 1916-108, 14h.14m
    urlhaus-1: 5916-0, 14h.14m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 9 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 727 ms (selfie)
  maxAssetCacheWait: 1341 ms
popupPanel: 
  blocked: 84
  blockedDetails: 
    1rx.io: 4
    4dex.io: 5
    a-mo.net: 4
    adlightning.com: 2
    adnxs.com: 12
    adxpremium.services: 4
    amazon-adsystem.com: 6
    ampproject.org: 3
    creativecdn.com: 4
    criteo.com: 5
    criteo.net: 1
    doubleclick.net: 3
    google.com: 5
    google.kz: 4
    googlesyndication.com: 11
    googletagmanager.com: 1
    googletagservices.com: 2
    id5-sync.com: 1
    onetag-sys.com: 7
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16083
