### ISSUE TITLE
french-stream.gg: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16936]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://french-stream.gg/film/9310-camping-3-film-streaming-complet-vf.html`

### Category

nuisance

### Description

Excellent French streaming site that unfortunately has some small problems. Only uBlock can do something 😄

### Screenshot(s)

Fake download buttons
![image](https://user-images.githubusercontent.com/50231020/221355895-ad0f5868-1a64-4681-a851-5a437cbbd2e0.png)

Some players are blocked and won't launch.
![image](https://user-images.githubusercontent.com/50231020/221355946-3d0f2bd9-5416-4ad5-8a1e-657ef1f8e42d.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 109
filterset (summary): 
  network: 122329
  cosmetic: 110166
  scriptlet: 20249
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39415-172, 12m
    fanboy-cookiemonster: 45639-215, 4d.4h.55m
  default: 
    user-filters: 0-0, never
    FRA-0: 30038-34, 4h.43m
    easylist: 62229-153, 4d.4h.55m
    easyprivacy: 30955-1584, 4d.4h.55m
    plowe-0: 3675-937, 4d.4h.55m
    ublock-abuse: 79-2, 4h.42m
    ublock-badware: 4601-140, 4h.4m
    ublock-filters: 32064-253, 4h.3m
    ublock-privacy: 276-1, 4h.2m
    ublock-quick-fixes: 331-21, 11m
    ublock-unbreak: 1923-50, 4h.1m
    urlhaus-1: 5797-0, 7m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 413 ms
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    histats.com: 2
    instinctcringe.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
french-stream.gg##.have-brand > div[style]
```

@smed79 

---

> Some players are blocked and won't launch.

All 5 load normally for me

**Comment by mapx-** [comment]
or
`french-stream.gg###banning`

all servers working fine on my side too
