### ISSUE TITLE
wvw.novaflix.io: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16938]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wvw.novaflix.io/6983-camping-3.html`

### Category

nuisance

### Description

Excellent French streaming site which, unfortunately, also has problems.

### Screenshot(s)

The UPVID reader opens many popups

![image](https://user-images.githubusercontent.com/50231020/221356073-20fe01da-97aa-43d0-b118-7466fbc8d6b4.png)
![image](https://user-images.githubusercontent.com/50231020/221356080-48409710-479d-4241-b95b-fa27dd9d71d2.png)
![image](https://user-images.githubusercontent.com/50231020/221356092-29b00336-e824-4dea-983c-b45e6f0192e7.png)
![image](https://user-images.githubusercontent.com/50231020/221356104-5fa52cfb-dfde-404c-afa2-a50eb2ae7fbe.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 109
filterset (summary): 
  network: 122329
  cosmetic: 110166
  scriptlet: 20249
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39415-172, 18m
    fanboy-cookiemonster: 45639-215, 4d.5h
  default: 
    user-filters: 0-0, never
    FRA-0: 30038-34, 4h.49m
    easylist: 62229-153, 4d.5h
    easyprivacy: 30955-1584, 4d.5h
    plowe-0: 3675-937, 4d.5h
    ublock-abuse: 79-2, 4h.48m
    ublock-badware: 4601-140, 4h.10m
    ublock-filters: 32064-253, 4h.9m
    ublock-privacy: 276-1, 4h.8m
    ublock-quick-fixes: 331-21, 17m
    ublock-unbreak: 1923-50, 4h.7m
    urlhaus-1: 5797-0, 13m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 413 ms
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    allfb8dremsiw09oiabhboolsebt29jhe3setn.com: 1
    amung.us: 1
    buqkrzbrucz.com: 1
    getcookiestxt.com: 1
    googletagmanager.com: 3
    histats.com: 2
    lassampy.com: 2
    rndskittytor.com: 1
    wwkedpbh4lwdmq16okwhiteiim9nwpds2.com: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
upvid popups issue was fixed previously, update uBO main list
