### ISSUE TITLE
doubtnut.com: breakage

### ISSUE THREAD

**Issue by MebishP** [uBlockOrigin/uAssets#16931]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.doubtnut.com/question-answer/the-value-of-i5-i6-i7-i8-i91-iis-646467790`

### Category

breakage

### Description

When I went to the page the video player doesn't show up, when ublock is disabled the video plays with ads

### Screenshot(s)

![image](https://user-images.githubusercontent.com/83964694/221344175-3728b6d1-72f8-4722-86ac-df82de0cb6c5.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 109
filterset (summary): 
  network: 83989
  cosmetic: 38798
  scriptlet: 16988
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32872-55, 1d.15h.7m
    ublock-badware: 4600-5, 1d.15h.6m
    ublock-privacy: 323-0, 6d.23h.46m
    ublock-abuse: 79-0, 6d.23h.45m
    ublock-unbreak: 1920-0, 1d.15h.5m
    ublock-quick-fixes: 335-8, 21m
    easylist: 62742-650, 23m
    easyprivacy: 30966-1752, 22m
    urlhaus-1: 5797-0, 20m
    plowe-0: 3675-2, 6d.18h
filterset (user): [empty]
trustedset: 
  added: [array of 48 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1603 ms (selfie)
  maxAssetCacheWait: 1089 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    doubtnut.com: 2
    doubleclick.net: 2
    googlesyndication.com: 2
    googletagmanager.com: 1
    gstatic.com: 1
    imasdk.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
however, on my side, in firefox is broken even disabling uBO.
Now is working fine in chrome.
