### ISSUE TITLE
menulog.com.au: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#16937]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.menulog.com.au/restaurants-metro-bonnyrigg/menu`

### Category

breakage

### Description

With uBlock running, when I click on any of the items, nothing happens.
With uBlock disabled, this dialog opens up.
Please fix.

![pic](https://user-images.githubusercontent.com/20948631/221356673-53192348-2d32-40a3-909c-7e83020329f9.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 270420
  cosmetic: 215490
  scriptlet: 38792
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39335-3726, 1h.56m
    https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 91275-0, 1h.55m
    adguard-annoyance: 64389-250, 1h.56m
    adguard-generic: 68661-1276, 1h.56m
    adguard-social: 19904-834, 1h.56m
    block-lan: 44-0, 1h.56m
    curben-phishing: 37707-39, 1h.56m
    curben-pup: 195-0, 1h.56m
    dpollock-0: 11340-179, 1h.56m
    fanboy-annoyance: 82352-6455, 1h.56m
    fanboy-thirdparty_social: 69-20, 1h.56m
    ublock-annoyances: 4841-245, 1h.55m
  default: 
    user-filters: 10-0, never
    easylist: 62916-1152, 1h.56m
    easyprivacy: 30974-12507, 1h.56m
    plowe-0: 3749-1375, 1h.55m
    ublock-abuse: 79-0, 1h.55m
    ublock-badware: 4601-335, 1h.55m
    ublock-filters: 32826-4054, 1h.55m
    ublock-privacy: 276-60, 1h.55m
    ublock-quick-fixes: 331-133, 1h.55m
    ublock-unbreak: 1925-118, 1h.55m
filterset (user): [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3055 ms (selfie)
  maxAssetCacheWait: 745 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    bing.com: 1
    braze.com: 3
    google-analytics.com: 1
    googletagmanager.com: 1
    usabilla.com: 1
```
</details>

**Comment by mapx-** [comment]
FA annoyances breakage

add

`@@*-cookie-banner$script,domain=menulog.com.au`

@ryanbr
