### ISSUE TITLE
hdfcfund.com: breakage

### ISSUE THREAD

**Issue by TheHuntRider** [uBlockOrigin/uAssets#16930]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hdfcfund.com/`

### Category

breakage

### Description

Websie showing blank page when addon enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83513
  cosmetic: 38736
  scriptlet: 16981
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32860-39, 2d.15h.28m
    ublock-badware: 4490-5, 2d.15h.27m
    ublock-privacy: 321-0, 5d.3h.27m
    ublock-abuse: 79-0, 5d.3h.26m
    ublock-unbreak: 1915-0, 2d.15h.26m
    ublock-quick-fixes: 335-20, 3h.52m
    easylist: 62229-640, 3d.3h.20m
    easyprivacy: 30988-1753, 3d.3h.19m
    urlhaus-1: 5797-0, 3h.51m
    plowe-0: 3739-2, 1d.16h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 535 ms (selfie)
  maxAssetCacheWait: 171 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    hdfcfund.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    netcore.co.in: 2
    netcoresmartech.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||cdnt.netcoresmartech.com/smartechclient.js$script,domain=hdfcfund.com`

@ryanbr

**Comment by stephenhawk8054** [comment]
I think it can be fixed by

```adb
hdfcfund.com##+js(set, smartech, noopFunc)
```

**Comment by mapx-** [comment]
that's true, however, even whitelisting that script in EP, the main one (with privacy concerns) still gets blocked afterwards

`https://osjs.netcoresmartech.com/v1/js-versioning?clientkey=...`

**Comment by stephenhawk8054** [comment]
Ah I see
