### ISSUE TITLE
hdss.plus: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16935]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hdss.plus/1314677-camping-3.html`

### Category

nuisance

### Description

It's a great streaming site, only it's rotten with ads. Thanks to uBlock, most of it is blocked, but there's still a lot of cleaning up to do.

### Screenshot(s)

Fake download buttons
![image](https://user-images.githubusercontent.com/50231020/221355581-fa132fc2-55cc-44f5-a0fa-0beca208ed12.png)

Overlay
![image](https://user-images.githubusercontent.com/50231020/221355596-dcb59a79-be61-466a-a80e-c03f38e08a2f.png)

Redirect popups
![image](https://user-images.githubusercontent.com/50231020/221355650-8472ae97-c351-44a7-a3aa-da9c3101b5aa.png)
![image](https://user-images.githubusercontent.com/50231020/221355663-1a612835-56dc-4ef1-bb2a-e28464a041f5.png)
![image](https://user-images.githubusercontent.com/50231020/221355670-2e3a11d8-4efe-4e70-a04b-114aa81f02cd.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 109
filterset (summary): 
  network: 122329
  cosmetic: 110166
  scriptlet: 20249
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39415-172, 6m
    fanboy-cookiemonster: 45639-215, 4d.4h.49m
  default: 
    user-filters: 0-0, never
    FRA-0: 30038-34, 4h.37m
    easylist: 62229-153, 4d.4h.49m
    easyprivacy: 30955-1584, 4d.4h.49m
    plowe-0: 3675-937, 4d.4h.49m
    ublock-abuse: 79-2, 4h.36m
    ublock-badware: 4601-140, 3h.58m
    ublock-filters: 32064-253, 3h.57m
    ublock-privacy: 276-1, 3h.56m
    ublock-quick-fixes: 331-21, 5m
    ublock-unbreak: 1923-50, 3h.55m
    urlhaus-1: 5797-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 413 ms
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    histats.com: 1
    yandex.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
hdss.plus###pub
hdss.plus##center
```

@smed79 Sorry, can you take a look?

**Comment by mapx-** [comment]
popups from last player (lien 5)

`opvid.net##+js(nowoif)`

**Comment by mapx-** [comment]
we already have hdss cosmetic filters in filters-2020 as a consequence of pp filter
