### ISSUE TITLE
dmv.ca.gov: breakage

### ISSUE THREAD

**Issue by evandjohnston** [uBlockOrigin/uAssets#16942]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dmv.ca.gov/portal/customer-service/dmv-customer-surveys/`

### Category

breakage

### Description

When uBlock Origin is disabled, upon clicking the `Take survey` button, a modal appears with a feedback survey.

When uBlock Origin is enabled, the modal does not appear, and clicking the button has no apparent effect.

Thanks for your time in investigating this issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 104
filterset (summary): 
  network: 83971
  cosmetic: 38760
  scriptlet: 16990
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32847-129, 1d.6h.16m
    ublock-badware: 4611-5, 1d.6h.18m
    ublock-privacy: 321-0, 5d.23h.3m
    ublock-abuse: 79-0, 5d.23h.2m
    ublock-unbreak: 1930-0, 1d.6h.17m
    easylist: 62682-522, 1d.6h.39m
    easyprivacy: 30964-1769, 1d.6h.19m
    urlhaus-1: 5774-0, 1d.6h.15m
    plowe-0: 3675-2, 5d.23h
    ublock-quick-fixes: 335-8, 1d.6h.14m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1410 ms
  maxAssetCacheWait: 332 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    translate.googleapis.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=dmv.ca.gov`

@ryanbr
