### ISSUE TITLE
nswrom.com: detection

### ISSUE THREAD

**Issue by Xiseous** [uBlockOrigin/uAssets#16944]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nswrom.com/`

### Category

detection

### Description

Adblock Detected Popup, site had deployed "CHP Adblock", can block the window per page but does not apply to the whole domain.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[image](https://user-images.githubusercontent.com/64169979/221383945-aad5a3a5-bf30-4c07-8c99-710a17b0b685.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83543
  cosmetic: 38709
  scriptlet: 17135
  html: 893
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 33355-203, never
    ublock-badware: 4337-5, never
    ublock-privacy: 319-0, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1889-0, never
    ublock-quick-fixes: 332-2, never
    easylist: 61614-174, never
    easyprivacy: 30956-1205, never
    urlhaus-1: 6395-0, never
    plowe-0: 3676-903, never
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 722 ms
  maxAssetCacheWait: 6 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    a-ads.com: 3
    googlesyndication.com: 1
    steadfastsystem.com: 1
    wp.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue. Screenshot: https://user-images.githubusercontent.com/66517106/221386156-f6d1dad9-e717-4508-8c00-45ce5200be7a.png

Can you force update the filter lists and test again?

**Comment by stephenhawk8054** [comment]
That's why we have the prerequisite before submitting issue

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by Xiseous** [comment]
I did click, just redid it one more time to confirm

**Comment by stephenhawk8054** [comment]
The configuration when you submitted the issue said otherwise

```yaml
default: 
    user-filters: 2-0, never
    ublock-filters: 33355-203, never
    ublock-badware: 4337-5, never
    ublock-privacy: 319-0, never
    ublock-abuse: 77-0, never
    ublock-unbreak: 1889-0, never
    ublock-quick-fixes: 332-2, never
    easylist: 61614-174, never
    easyprivacy: 30956-1205, never
    urlhaus-1: 6395-0, never
    plowe-0: 3676-903, never
```

Anyway, as it cannot be reproduced, I think the issue can be closed.
