### ISSUE TITLE
app.infinityfree.net: breakage

### ISSUE THREAD

**Issue by Wh1teT1ger55** [uBlockOrigin/uAssets#16949]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.infinityfree.net/`

### Category

breakage

### Description

Can't click some buttons until disabling uBlockOrigin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 109
filterset (summary): 
  network: 83880
  cosmetic: 38798
  scriptlet: 16985
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 5-0, never
    easylist: 62743-47, 1d.18h.42m
    easyprivacy: 30964-1172, 1d.18h.41m
    plowe-0: 3675-908, 7d.16h.45m
    ublock-abuse: 79-0, 3d.14h.23m
    ublock-badware: 4486-123, 3d.14h.22m
    ublock-filters: 32037-148, 3d.14h.21m
    ublock-privacy: 276-1, 3d.14h.20m
    ublock-quick-fixes: 331-21, 19h.53m
    ublock-unbreak: 1909-48, 3d.14h.19m
    urlhaus-1: 5797-0, 19h.52m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 195 ms (selfie)
  maxAssetCacheWait: 97 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    quantcast.com: 9
    quantserve.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> some buttons

Can you screenshot which buttons?

**Comment by Wh1teT1ger55** [comment]
I'm sorry. I re-enabled uBO and now all works fine. But it were these buttons:
![image](https://user-images.githubusercontent.com/125185383/221400304-e2985fd0-c216-4d9b-be10-17055dbd828c.png)
