### ISSUE TITLE
france24.com: nuisance

### ISSUE THREAD

**Issue by RMRubert** [uBlockOrigin/uAssets#16943]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.france24.com/es/programas/historia/20230223-la-guerra-en-ucrania-un-conflicto-fraguado-desde-hace-d%C3%A9cadas`

### Category

nuisance

### Description

Website doesn't move, likely to GDPR pop up.

I also have installed I dont care about cookies extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 93666
  cosmetic: 117437
  scriptlet: 19237
  html: 889
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1066-0, 3d.1h.20m
    fanboy-annoyance: 82374-163, 4h.52m
  default: 
    user-filters: 2-0, never
    ublock-filters: 32872-117, 3d.1h.15m
    ublock-badware: 4476-5, 3d.1h.14m
    ublock-privacy: 323-0, 9d.6h.2m
    ublock-abuse: 79-4, 9d.6h.3m
    ublock-unbreak: 1920-0, 3d.1h.17m
    easylist: 62346-731, 3d.1h.19m
    easyprivacy: 30963-2223, 3d.1h.18m
    plowe-0: 3675-3, 7d.10h.37m
    spa-0: 3507-1, 12h.53m
    spa-1: 5061-134, 3d.1h.16m
    urlhaus-1: 5797-0, 12h.54m
    ublock-quick-fixes: 335-8, 12h.55m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 81 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1334 ms (selfie)
  maxAssetCacheWait: 211 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    batch.com: 1
    fmm.io: 2
    privacy-center.org: 1
```
</details>

**Comment by krystian3w** [comment]
then detect who inccorect hide cookie modal, uAssets need exclude this modal as GDPR/CCPA implementation on UE webpage.

**Comment by iam-py-test** [comment]
I can not reproduce on default settings. This is either caused by Fanboy's Annoyances list or "I Don't Care About Cookies". Either way, this should not be reported to uAssets, and should instead be reported to them.

**Comment by krystian3w** [comment]
Kiboke Extension and fork: https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/
correctly accept "cookie" modal (I do not specialise in detecting when such a pop-up is already GDPR / CCPA).

[Fork faster than Kiboke with Avast Support]

Maybe @peace2000 / @Nojuuu made PR to avoid wait to months to address by ryanbr / khrin hands.

**Comment by RMRubert** [comment]
Sorry I didn't specify it. The other extension I was using is Consent-o-matic: https://github.com/cavi-au/Consent-O-Matic

**Comment by iam-py-test** [comment]
Before submitting an issue, please make sure it is reproducible using the default uBlock Origin configuration, and with no other extensions or DNS blocking running which could interfere. Sorry if I am a bit rude, but issues like this need to be reported to the filterlist/extension authors responsible and not uAssets.
Thank you.

**Comment by krystian3w** [comment]
I don't use this one but rather the same conflicts can occur as with active uBo with AdGuard/ABP/AdBlock between IDCAC with C-O-M.

Also now VPN-s and Moz://a implements hide cookies/GDPR/CCPA:

https://www.ghacks.net/2020/07/22/never-consent-refuses-gdpr-consents-automatically/

**Comment by Nojuuu** [comment]
Works fine with EasyList Cookie.

**Comment by ryanbr** [comment]
`france24.com#$#:root { overflow: visible !important; padding-right: 0 !important; overflow-y: visable !important; overflow-x: visable !important}` 

Is `visable` a typo?  @iam-py-test

**Comment by iam-py-test** [comment]
Probably. I just copied that from an old rule for another site

**Comment by krystian3w** [comment]
> https://github.com/easylist/easylist/commit/cc5b1227ee15c5821e5a89228eae39a1fb5a38cb

Last two CSS properties are duplicates of first property.

```
overflow: visible !important = overflow-y: visible !important + overflow-x: visible !important
```

**Comment by mapx-** [comment]
@Oxygen112 

add
`@@||sdk.privacy-center.org^$from=france24.com,badfilter`

@Yuki2718 
ELC + AA => breakage

**Comment by Yuki2718** [comment]
I can reproduce https://github.com/AdguardTeam/AdguardFilters/issues/125097 so the exception is needed for ELC as well. Will fix by `trusted-click-element`.
