### ISSUE TITLE
ww3.putlockers.li: popups

### ISSUE THREAD

**Issue by koreachess** [uBlockOrigin/uAssets#16945]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ww3.putlockers.li/tv-show/his-dark-materials-2019_VmgzL2gzekpVTkE9/S01E04/watch.html`

### Category

popups

### Description

previously no pop up, now there are pop ups and the tab is flashing 2 new messages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 83529
  cosmetic: 38769
  scriptlet: 16975
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 29-0, never
    ublock-filters: 32853-55, 3d.17h.13m
    ublock-badware: 4476-5, 3d.17h.15m
    ublock-privacy: 323-0, 3d.21h.17m
    ublock-abuse: 79-0, 3d.21h.16m
    ublock-unbreak: 1919-4, 3d.17h.14m
    ublock-quick-fixes: 335-4, 15h.30m
    easylist: 62348-642, 23h.32m
    easyprivacy: 30964-1750, 23h.31m
    urlhaus-1: 5797-0, 15h.29m
    plowe-0: 3676-2, 12d.23h.13m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13615 ms
  maxAssetCacheWait: 3195 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    apathylahuli.website: 2
    googletagmanager.com: 2
    gripqueer.com: 2
    syenitetatler.tech: 1
    tonganserried.life: 2
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 The popup scripts in this case are 

```
https://tonganserried.life/fOFeVZbkyJ7dyuc9/48635
https://tonganserried.life/raQN9DOWByi4/37035
```

Should we add another regex of

```adb
/^https?:\/\/(?:[a-z]{2}\.)?[0-9a-z]{7,16}\.life\/[a-z](?=[a-z]{0,25}[0-9A-Z])[0-9a-zA-Z]{3,26}\/(?:[1-6]\d{4}|[3-9]\d{3})\??(?:_=\d+|v=\d)?$/$frame,script,xhr,popup,3p,match-case
```

or merge with the old ones (`com` and `website`)

**Comment by ghajini** [comment]
let's gather all the websites here on which above crap occurs

**Comment by Yuki2718** [comment]
Hmmm, maybe merge and then address 14 char case separately for uBOL?

**Comment by Yuki2718** [comment]
So far limited to script, but if you find other cases such as xhr, feel free to add.
