### ISSUE TITLE
byjus.com: ads

### ISSUE THREAD

**Issue by nxs-neo** [uBlockOrigin/uAssets#16941]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://byjus.com/chemistry/what-is-enthalpy/`

### Category

ads

### Description

Ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 82559
  cosmetic: 38748
  scriptlet: 16988
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32872-56, 2d.11h.12m
    ublock-badware: 4600-5, 2d.11h.11m
    ublock-privacy: 323-0, 2d.11h.16m
    ublock-abuse: 79-0, 2d.11h.15m
    ublock-unbreak: 1924-4, 2d.11h.10m
    ublock-quick-fixes: 335-4, 5h.7m
    easylist: 62346-642, 2d.11h.14m
    easyprivacy: 30963-1752, 2d.11h.13m
    urlhaus-1: 4702-0, 5h.6m
    plowe-0: 3680-2, 9d.9h.7m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 275 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    cloudflareinsights.com: 2
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
You should enable `AdGuard Annoyances` list
