### ISSUE TITLE
ebay-kleinanzeigen.de: ads

### ISSUE THREAD

**Issue by florianjokeit** [uBlockOrigin/uAssets#16951]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ebay-kleinanzeigen.de/`

### Category

ads

### Description

Getting ads on ebay-kleinanzeigen.de

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-02-26 130702](https://user-images.githubusercontent.com/4364017/221409519-b460b5d8-af0e-4e28-a0c9-b2559b0f025a.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 82463
  cosmetic: 38707
  scriptlet: 16992
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32867-56, 1d.16h.17m
    ublock-badware: 4620-5, 10h.28m
    ublock-privacy: 323-0, 1d.16h.14m
    ublock-abuse: 79-0, 1d.16h.15m
    ublock-unbreak: 1924-4, 1d.16h.16m
    ublock-quick-fixes: 335-4, 14h.29m
    easylist: 62092-610, 5d.18h.32m
    easyprivacy: 30988-1746, 5d.18h.31m
    urlhaus-1: 4745-0, 10h.27m
    plowe-0: 3680-2, 11d.2h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 274 ms (selfie)
  maxAssetCacheWait: 90 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    ebay-kleinanzeigen.de: 6
    aaxads.com: 1
    amazon-adsystem.com: 1
    doubleclick.net: 1
    ebay.de: 1
    google.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@Khrin

**Comment by okiehsch** [comment]
@JobcenterTycoon You see adsin your end?

**Comment by JobcenterTycoon** [comment]
I get a placeholder but no ads.

@florianjokeit you need to enable `DEU: EasyList Germany`

**Comment by okiehsch** [comment]
Ok, I can see the placeholder.
`ebay-kleinanzeigen.de###liberty-home-billboard`

**Comment by okiehsch** [comment]
I can't reproduce the ads in the screenshot of the OP even f I disable uBO.
Maybe an account is required to reproduce.

**Comment by florianjokeit** [comment]
> I get a placeholder but no ads.
> 
> @florianjokeit you need to enable `DEU: EasyList Germany`

yeah, this seems to solve it for me. First time i have to enable sth on my own. Thank you! :)
