### ISSUE TITLE
wedel.de: ads

### ISSUE THREAD

**Issue by jknerdYT** [uBlockOrigin/uAssets#16953]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wedel.de/tourismus-freizeit/elbe-maritimes/webcams/willkommhoeft-westen`

### Category

ads

### Description

I am still seeing ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 109
filterset (summary): 
  network: 85196
  cosmetic: 43066
  scriptlet: 17006
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    DEU-0: 6544-0, 3h.50m
    easylist: 62674-53, 2d.8h.25m
    easyprivacy: 30963-1181, 2d.8h.24m
    plowe-0: 3675-909, 9d.1h.32m
    ublock-abuse: 79-0, 7h.52m
    ublock-badware: 4616-123, 11h.55m
    ublock-filters: 32070-123, 11h.54m
    ublock-privacy: 276-1, 7h.51m
    ublock-quick-fixes: 331-21, 3h.49m
    ublock-unbreak: 1925-49, 11h.53m
    urlhaus-1: 4745-0, 3h.48m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 307 ms (selfie)
  maxAssetCacheWait: 147 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
report here:
https://github.com/easylist/easylistgermany/issues
