### ISSUE TITLE
1337x.to: popups

### ISSUE THREAD

**Issue by 2u841r** [uBlockOrigin/uAssets#16958]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://1337x.to/sort-search/hin/time/desc/1/`

### Category

popups

### Description

redirects to me this page https://uptimecdn.com/prod/redirect.html?lu=https%3A%2F%2Fjdufppsi.trafficmediaareus.com%2F%3Fcid%3D5298%26clkid%3D167746331810000TBDTV417376324614Vfe%26sid%3D6510742

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 84145
  cosmetic: 38770
  scriptlet: 17002
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 5-1, never
    easylist: 62702-47, 2d.14h.29m
    easyprivacy: 30963-1172, 4d.13h.20m
    plowe-0: 3680-911, 13d.1h.11m
    ublock-abuse: 79-0, 4d.11h.19m
    ublock-badware: 4591-123, 1d.13h.23m
    ublock-filters: 32064-110, 1d.13h.19m
    ublock-privacy: 276-1, 4d.11h.18m
    ublock-quick-fixes: 331-21, 13h.12m
    ublock-unbreak: 1916-48, 1d.13h.18m
    urlhaus-1: 5915-0, 13h.11m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 157 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 43253 ms (selfie)
  maxAssetCacheWait: 99 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    youradexchange.com: 2
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
