### ISSUE TITLE
extremetech.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1695]
### URL(s) where the issue occurs

`https://www.extremetech.com/electronics/265299-samsungs-new-4k-televisions-can-turn-invisible`

### Describe the issue

Unblocked ads at end of article.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/37244250-e954bb40-2453-11e8-95e0-b47ba0d32602.png)

### Versions

- Browser/version: Chrome 64
- uBlock Origin version: 1.15.2

### Settings

Default

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by gorhill** [comment]
I also can't reproduce.

**Comment by nimasaj** [comment]
Does it work for you?
`||zergnet.com^$third-party,script`
this filter is coming from `AdBlock Protector 2 List for uBlock Origin` in following address:
`https://raw.githubusercontent.com/AdBlockProtector2/AdBlockProtector2/master/filter/abr2-ubo.txt`

**Comment by terrorist96** [comment]
@nimasaj No, it doesn't. I can still reproduce on a test profile with only uBO and updated default filters. Maybe it's US IP specific?

**Comment by terrorist96** [comment]
This might actually be g00 related. Seeing a lot of it in the logs.

**Comment by mapx-** [comment]
Are you using `ublock extra` ?

**Comment by terrorist96** [comment]
No.

**Comment by terrorist96** [comment]
Always wondered why the functionality of uBO Extra can't be integrated with uBO.

**Comment by mapx-** [comment]
Install it. 
read why here:
https://github.com/gorhill/uBO-Extra

> to gain ability to foil early anti-user mechanisms working around content blockers or even a browser privacy settings

**Comment by terrorist96** [comment]
Yeah, I know its benefit but still don't understand why it can't be integrated with uBO so it's just 1 extension.

**Comment by terrorist96** [comment]
Can confirm the issue is fixed with uBO Extra, though still wish I didn't have to install two extensions.

**Comment by gorhill** [comment]
> I know its benefit but still don't understand why it can't be integrated with uBO

https://github.com/gorhill/uBlock/issues/1801#issuecomment-231601462

**Comment by terrorist96** [comment]
Thanks. My follow up question would be, why not make the websocket injection functionality a switch that's off by default within uBO?

**Comment by terrorist96** [comment]
I just read this:

> I had thought about putting the feature behind a setting, and opt-in, but given the nature of the WebSocket solution, this was not feasible.

do you mind expanding on this?

**Comment by gorhill** [comment]
The issue is not websocket, it's being force to inject the content script everywhere, i.e. on pages where it's not needed, because it has to be injected declaratively. Best is to read the dev documentation, I am unable to explain without being technical.
