### ISSUE TITLE
serialfan.net: breakage

### ISSUE THREAD

**Issue by glebpavlov** [uBlockOrigin/uAssets#16954]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://serialfan.net/57953-the-ark/1-season/3-episode.html`

### Category

breakage

### Description

empty video block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 99998
  cosmetic: 59773
  scriptlet: 18214
  html: 893
listset (total-discarded, last-updated): 
  default: 
    user-filters: 64-8, never
    ublock-filters: 32872-166, 3d.3h.21m
    ublock-badware: 4600-5, 3d.3h.22m
    ublock-privacy: 321-0, 6d.23h.14m
    ublock-abuse: 79-0, 6d.23h.13m
    ublock-unbreak: 1924-0, 3d.1h.57m
    easylist: 62702-522, 1d.2h.27m
    easyprivacy: 30964-1769, 1d.2h.26m
    urlhaus-1: 4745-0, 5h.11m
    plowe-0: 3675-2, 7d.19h.22m
    RUS-0: 39429-171, 5h.12m
    ublock-quick-fixes: 335-8, 5h.10m
filterset (user): [array of 64 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 338 ms (selfie)
  maxAssetCacheWait: 297 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    aj1907.online: 4
    googletagmanager.com: 1
    sourserve.com: 1
    vak345.com: 2
    vb17121coramclean.pw: 2
    yadro.ru: 1
    yandex.ru: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
>I forced an update of my filter lists

It wasn't done. This issue has already been resolved.

https://github.com/easylist/easylist/commit/28eda19529cd4658309eaa6750d748088836fb71#comments ~> https://github.com/easylist/easylist/commit/cec9bbcb3c7854aa0bced7164e633935842cafc4
