### ISSUE TITLE
muvicinemas.com: detection

### ISSUE THREAD

**Issue by haitham506** [uBlockOrigin/uAssets#16955]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.muvicinemas.com/en`

### Category

detection

### Description

- Site Detecting Adblocker
- Only with **Edge Browser**
### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/66400184/221423372-88ea5479-4ea7-4d97-9242-97ca9de5ed1f.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 86589
  cosmetic: 39795
  scriptlet: 17302
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ara-0: 2744-0, 19m
  default: 
    user-filters: 43-1, never
    easylist: 62966-53, 19m
    easyprivacy: 30978-1178, 19m
    plowe-0: 3749-928, 19m
    ublock-abuse: 79-0, 19m
    ublock-badware: 4605-123, 19m
    ublock-filters: 32836-114, 19m
    ublock-privacy: 276-1, 19m
    ublock-quick-fixes: 321-126, 19m
    ublock-unbreak: 1925-49, 19m
    urlhaus-1: 5915-0, 19m
filterset (user): [array of 43 redacted]
trustedset: 
  added: [array of 67 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdatePeriod: 7
  cloudStorageCompression: false
supportStats: 
  allReadyAfter: 1069 ms
  maxAssetCacheWait: 895 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    browser-intake-datadoghq.com: 5
    google.com: 1
    googletagmanager.com: 2
    onesignal.com: 1
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
Even disabling uBO, tracking prevention, ads blocking, I still get the detection

**Comment by mapx-** [comment]
see if helps 

```
muvicinemas.com##.MuiModal-root.MuiDialog-root
muvicinemas.com##body:style(overflow: auto !important;)
```

**Comment by Daxy7** [comment]
> It works fine on **Chrome** even without the filters but not on **Edge**

Disable tracking prevention in Edge
