### ISSUE TITLE
thehindu.com: ads

### ISSUE THREAD

**Issue by Malgotra** [uBlockOrigin/uAssets#16950]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.thehindu.com/`

### Category

ads

### Description

Floating ads leftover

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/122884037/221407499-36f2cf3c-217b-43f4-9c5b-264b6344af55.png
https://user-images.githubusercontent.com/122884037/221407504-ba17a1d0-6a66-4748-942d-ab757ae262c4.png

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox Mobile: 110
filterset (summary): 
  network: 164275
  cosmetic: 221910
  scriptlet: 38155
  html: 1049
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 68670-5345, 6m
    adguard-spyware-url: 926-4, 6m
    block-lan: 44-0, 6m
    curben-phishing: 38153-16, 6m
    curben-pup: 195-0, 6m
    adguard-annoyance: 64389-4980, 6m
    adguard-social: 19904-996, 6m
    fanboy-thirdparty_social: 69-0, 6m
    fanboy-annoyance: 82114-70058, 5m
    fanboy-cookiemonster: 45843-246, 5m
    fanboy-social: 22363-26, 6m
    ublock-annoyances: 4858-4, 6m
    dpollock-0: 11340-472, 5m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33781-194, 5m
    ublock-badware: 4619-5, 5m
    ublock-privacy: 323-0, 5m
    ublock-abuse: 79-0, 5m
    ublock-unbreak: 1941-5, 5m
    ublock-quick-fixes: 336-4, 5m
    adguard-mobile: 8718-191, 7m
    easylist: 62953-946, 5m
    easyprivacy: 30976-1867, 5m
    urlhaus-1: 4745-0, 5m
    plowe-0: 3749-2, 5m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12348 ms
  maxAssetCacheWait: 16161 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    amazon-adsystem.com: 1
    automatad.com: 1
    cloudflareinsights.com: 2
    cxense.com: 3
    google-analytics.com: 1
    google.com: 1
    googletagmanager.com: 1
    npttech.com: 1
    pubmatic.com: 1
    scorecardresearch.com: 1
    site24x7rum.in: 1
    taboola.com: 1
    truste.com: 1
```
</details>

**Comment by ghajini** [comment]
i don't see any, can you test with only **_Default filters_**

**Comment by Malgotra** [comment]
![Screenshot_20230226-174958](https://user-images.githubusercontent.com/122884037/221410121-c526f60d-9094-49c7-9517-3fe82552646f.png)
![Screenshot_20230226-175006](https://user-images.githubusercontent.com/122884037/221410124-4a903db2-e4d2-4e64-8863-ac279fcb7871.png)
Still visible with default filters.
uBlock Origin: 1.47.0
Firefox Mobile: 110
filterset (summary): 
  network: 84925
  cosmetic: 45998
  scriptlet: 17344
  html: 900
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33781-184, 2m
    ublock-badware: 4619-5, 2m
    ublock-privacy: 323-0, 2m
    ublock-abuse: 79-0, 2m
    ublock-unbreak: 1941-4, 1m
    ublock-quick-fixes: 344-4, 1m
    adguard-mobile: 8718-149, 2m
    easylist: 62955-760, 1m
    easyprivacy: 30976-1776, 1m
    urlhaus-1: 4745-0, 1m
    plowe-0: 3749-2, 1m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 11475 ms
  maxAssetCacheWait: 1048 ms

**Comment by stephenhawk8054** [comment]
There's a small placeholder at the bottom

```adb
thehindu.com##.flooting-ad
```

Maybe more suitable for EasyList?

@ryanbr

**Comment by mapx-** [comment]
other 2 filters (Desktop edition)

```
thehindu.com###articledivrec
thehindu.com##.artShrEnd
```
