### ISSUE TITLE
worldofiptv.com: detection

### ISSUE THREAD

**Issue by thiagojramos** [uBlockOrigin/uAssets#16969]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.worldofiptv.com/`

### Category

detection

### Description

Whenever I access this website, it gives me a warning that it has detected my adblock. I have my ublock enabled and the filters updated. I have already cleared the cache and updated everything. I tried the following filter, but it didn't work:

`||worldofiptv.com^$generichide`

I can remove the warning using the "Element Picker" shortcut on the page I'm on, but when, for example, I click to go to the second page of the topic or click on the banner to go to the site's home, the warning comes back.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![image](https://user-images.githubusercontent.com/45890502/221672911-c681e0c2-69ef-42d6-9727-401d0776549b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 111
filterset (summary): 
  network: 169204
  cosmetic: 187000
  scriptlet: 38150
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1551-0, 15h.30m
    JPN-1: 9813-5, 1d.17h.9m
    RUS-0: 39419-22, 1d.17h.9m
    adguard-annoyance: 64389-508, 1d.17h.8m
    adguard-generic: 68669-704, 1d.17h.8m
    adguard-mobile: 8717-84, 1d.17h.8m
    adguard-social: 19904-843, 1d.17h.8m
    curben-phishing: 39077-0, 15h.32m
    curben-pup: 194-0, 15h.31m
    ublock-annoyances: 4841-190, 1d.17h.8m
  default: 
    user-filters: 117-4, never
    easylist: 62949-1100, 1d.17h.8m
    easyprivacy: 30975-1679, 1d.17h.8m
    plowe-0: 3749-1038, 1d.17h.8m
    spa-1: 5062-75, 1d.17h.8m
    ublock-abuse: 79-1, 1d.17h.8m
    ublock-badware: 4616-337, 1d.17h.8m
    ublock-filters: 32831-4093, 1d.17h.8m
    ublock-privacy: 276-3, 1d.17h.8m
    ublock-quick-fixes: 331-138, 15h.29m
    ublock-unbreak: 1925-95, 1d.17h.8m
    urlhaus-1: 6135-2, 15h.28m
filterset (user): [array of 117 redacted]
trustedset: 
  added: [array of 236 redacted]
switchRuleset: 
  added: [array of 1 redacted]
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  showIconBadge: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3695 ms (selfie)
  maxAssetCacheWait: 792 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    worldofiptv.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by Daxy7** [comment]
Working filter:

`worldofiptv.com##+js(ra, style, body > div, stay)`

Copied from:
`https://github.com/uBlockOrigin/uAssets/issues/16083#issuecomment-1362103717`

**Comment by vipeweb** [comment]
filter needs updating, again blocking displaying message.

**Comment by mapx-** [comment]
Did you update all your lists ? no other blocking extension

**Comment by Daxy7** [comment]
> filter needs updating, again blocking displaying message.

no problems my end, try using only default filter lists

**Comment by garry-ut99** [comment]
No problem on my end either.
