### ISSUE TITLE
 (SFW) sbchill.com  adblock is detected

### ISSUE THREAD

**Issue by xpufx** [uBlockOrigin/uAssets#16961]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Within the video player a box titled "Adblock detected" is displayed and video won't play until adblock is disabled and an "I disabled adblock" button is clicked.

### URL(s) where the issue occurs.

`https://sbchill.com/lf27d353wzve.html`  

### uBO version

1.47.0

### Browser name and version

Firefox 109.0.1

### Settings

I have tested with a new profile where I installed UBO fresh. In the default configuration the anti-adblock box in the video did not show for a few refreshes. In order to start to match the clean config to my daily config I started to enable the configs differing from a default install one by one. In the filter lists when I enabled the first Annoyance filter "AdGuard Annoyances" the site started to show the described box. However, disabling and refreshing does not make a difference now so I stopped trying to isolate the source of the issue since it's erratic (or tied to IP etc).

### Notes

Please do not hesistate to ask for more details.

**Comment by ghajini** [comment]
@ryanbr
`||appcdn01.xyz^$badfilter`

**Comment by xpufx** [comment]
This filter works for me as well.

> @ryanbr bait `||appcdn01.xyz^$badfilter`
