### ISSUE TITLE
ad can't disable

### ISSUE THREAD

**Issue by 1208041822** [uBlockOrigin/uAssets#16968]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://bbs.pcbeta.com/  ad can't disable

### URL(s) where the issue occurs.

https://bbs.pcbeta.com/

### Screenshot(s)

![2023 02 28 03 29 40](https://user-images.githubusercontent.com/28993260/221663767-458f1d9e-c12c-4b8e-9c87-20242ee4aa58.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 102
filterset (summary): 
  network: 102137
  cosmetic: 49121
  scriptlet: 17151
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28297-104, 3h.3m
    easylist: 63044-95, 3h
    easyprivacy: 30980-1193, 2h.59m
    plowe-0: 3749-930, 2h.58m
    ublock-abuse: 79-0, 2h.56m
    ublock-badware: 4606-123, 2h.54m
    ublock-filters: 32092-128, 2h.53m
    ublock-privacy: 276-1, 2h.52m
    ublock-quick-fixes: 318-19, 2h.51m
    ublock-unbreak: 1926-49, 2h.50m
    urlhaus-1: 5856-0, 2h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6650 ms
  maxAssetCacheWait: 169 ms
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16966#issuecomment-1446912955
