### ISSUE TITLE
gacop.katerionews.com: ads

### ISSUE THREAD

**Issue by IamFarmerSoWhat** [uBlockOrigin/uAssets#16962]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gacop.katerionews.com/hot-news/?data=def50200b09c2c21a74c5a31a4d7589d6fad7f7aee8ebbe8b5a1597b88f70b152b91f1d4f21f5f49c93d99439cf2a1b8b3faeadc0c276c992697020e6675df0fe59bfd3fcb8c07b4686a2ea4ecc4fff22f4dee0418a4221437784aed384eff0727819e3bff3ee0cb1d32bcc35923fc1a2e1be4127b8811dbd894a3210608e66f30a39796614927100fa304479dfd718e0f0a37d442afff263dfd5e54cafe6c47a89c3449cf24762b14c637c4357a94965f94e34c8d08153285aaf4cfecf1ef0ded48e1c33ada8a54a8942379129f2c866e94231fc5ef1b95d8d573882349bb4d581a7db0f92d2e1767a8e5a21894bc4d949989b63abb144d22a1caa22193f72fce9cc5`

### Category

ads

### Description

Katerio news is site which I am redirected to from local site for streaming videos. This site is surpasing my filters and is showing me sponsorend content, even after setting custom filters to show only desired content on page. Site si hiding ads behind kind of "news". Site which is redirecting me to katerio news is sledujserialy.io

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/126474413/221561640-567d6f81-e2a3-4561-9b37-00aee8f92dfb.png

https://user-images.githubusercontent.com/126474413/221561669-984bd934-0f61-402a-b50f-4ce717589c51.png

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 84058
  cosmetic: 39133
  scriptlet: 17150
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 43-4, never
    ublock-filters: 32877-39, 3d.16h.57m
    ublock-badware: 4611-5, 2d.19h.47m
    ublock-privacy: 321-0, 6d.22h
    ublock-abuse: 79-0, 6d.21h.59m
    ublock-unbreak: 1920-4, 3d.16h.58m
    ublock-quick-fixes: 343-20, 17h.23m
    easylist: 62346-643, 3d.16h.59m
    easyprivacy: 30964-1773, 4d.5h.33m
    urlhaus-1: 5915-0, 17h.22m
    plowe-0: 3739-2, 4d.17h.45m
    CZE-0: 737-0, 17h.21m
filterset (user): [array of 43 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 141 ms (selfie)
  maxAssetCacheWait: 67 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    katerionews.com: 1
    aaa111.site: 2
    greeter.me: 4
    modoro360.com: 2
    testingmetriksbre.ru: 2
```
</details>

**Comment by mapx-** [comment]
report here
https://github.com/tomasko126/easylistczechandslovak/issues

**Comment by IamFarmerSoWhat** [comment]
Thank you for quick response and your time.

Dňa po 27. 2. 2023, 19:25 mapx ***@***.***> napísal(a):
