### ISSUE TITLE
novinky.cz: ads

### ISSUE THREAD

**Issue by jsfsbrv** [uBlockOrigin/uAssets#16963]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.novinky.cz/`

### Category

ads

### Description

Ads are displayed with uBlock enabled. The uBlock settings are default, filters are updated and cache is cleared. "Zap-mode" on the displayed ads works.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![novinky cz ads](https://user-images.githubusercontent.com/97737331/221565848-d1f6dddb-a530-4d6a-9f9d-42b3b439b443.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 84167
  cosmetic: 39095
  scriptlet: 17147
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32879-39, 3d.3h.45m
    ublock-badware: 4595-5, 3d.3h.44m
    ublock-privacy: 323-0, 11d.6h.14m
    ublock-abuse: 79-0, 11d.6h.13m
    ublock-unbreak: 1924-4, 3d.3h.43m
    ublock-quick-fixes: 335-20, 6h.30m
    easylist: 62296-627, 5d.2h.40m
    easyprivacy: 30963-1775, 5d.2h.39m
    urlhaus-1: 6135-0, 6h.29m
    plowe-0: 3680-2, 11d.6h.7m
    CZE-0: 737-0, 6h.28m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1578 ms (selfie)
  maxAssetCacheWait: 303 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    seznam.cz: 2
    adnxs.com: 1
    gemius.pl: 2
    post.cz: 1
```
</details>

**Comment by krystian3w** [comment]
Try clear data for webpage?
