### ISSUE TITLE
shinbhu.net: detection

### ISSUE THREAD

**Issue by Gladiator1st** [uBlockOrigin/uAssets#16960]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shinbhu.net/`

### Category

detection

### Description

before sometime the website could not detect the ublock origin but now when i went to this site it keeps detecting it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/123251375/221503603-4a0f2a28-374d-4613-aa18-56370f6bf2c2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 120754
  cosmetic: 38752
  scriptlet: 16994
  html: 0
listset (total-discarded, last-updated): 
  added: 
    curben-phishing: 38153-0, 21h.4m
  default: 
    user-filters: 5-0, never
    easylist: 62346-47, 4d.13h.55m
    easyprivacy: 30955-1172, 4d.13h.54m
    plowe-0: 3680-909, 10d.13h.20m
    ublock-abuse: 79-0, 4d.13h.16m
    ublock-badware: 4601-132, 3d.13h.40m
    ublock-filters: 32029-110, 2d.15h.54m
    ublock-privacy: 276-1, 4d.13h.15m
    ublock-quick-fixes: 331-21, 21h.3m
    ublock-unbreak: 1914-48, 2d.15h.53m
    urlhaus-1: 4745-1, 21h.5m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 65 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2423 ms (selfie)
  maxAssetCacheWait: 208 ms
popupPanel: 
  blocked: 0
  no-popups: true
```
</details>

**Comment by mapx-** [comment]
- provide a specific link
- did you try yourself to visit directly `https://shinbhu.net/` ? do you get any detection ?
