### ISSUE TITLE
bbs.pcbeta.com: ads

### ISSUE THREAD

**Issue by 1208041822** [uBlockOrigin/uAssets#16966]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bbs.pcbeta.com/`

### Category

ads

### Description

can't disappear

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/28993260/221591955-bcf82027-bb5a-4647-8c7f-730d8543e7eb.png

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 102362
  cosmetic: 49049
  scriptlet: 17141
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    CHN-0: 28267-110, 1d.7h.30m
    easylist: 62953-94, 1d.7h.28m
    easyprivacy: 30976-1193, 1d.7h.27m
    plowe-0: 3749-930, 1d.7h.25m
    ublock-abuse: 79-0, 1d.7h.23m
    ublock-badware: 4616-123, 1d.7h.21m
    ublock-filters: 32070-126, 1d.7h.20m
    ublock-privacy: 276-1, 1d.7h.19m
    ublock-quick-fixes: 318-16, 42m
    ublock-unbreak: 1925-49, 1d.7h.17m
    urlhaus-1: 6135-0, 4h.43m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3239 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    baidu.com: 1
    baidustatic.com: 1
```
</details>

**Comment by mapx-** [comment]
already fixed by chn list, update it
