### ISSUE TITLE
yahoo.co.jp: ads

### ISSUE THREAD

**Issue by Mocchanpapa** [uBlockOrigin/uAssets#16974]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.yahoo.co.jp/`

### Category

ads

### Description

When I updated my PC from WIN10 to WIN11, this issue has started.  On yahoo portal page, ads pops up regularly and some times it stays there and some time it goes away after a few soconds.  When I used WIN10, this issue never happened.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 85703
  cosmetic: 46979
  scriptlet: 17160
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    JPN-1: 9813-5, 2d.5h.33m
    easylist: 62906-59, 2d.5h.41m
    easyprivacy: 30975-1196, 2d.5h.38m
    plowe-0: 3680-917, 11d.5h.25m
    ublock-abuse: 79-0, 2d.5h.37m
    ublock-badware: 4601-124, 2d.5h.32m
    ublock-filters: 32070-121, 2d.5h.31m
    ublock-privacy: 276-1, 2d.5h.36m
    ublock-quick-fixes: 320-16, 4h.51m
    ublock-unbreak: 1925-49, 2d.5h.30m
    urlhaus-1: 5856-0, 4h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 15480 ms (selfie)
  maxAssetCacheWait: 400 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    yimg.jp: 5
    yjtag.jp: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
supportStats: 
  allReadyAfter: 15480 ms (selfie)
  maxAssetCacheWait: 400 ms
```

Might relate to this discussion https://github.com/uBlockOrigin/uAssets/discussions/16939

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16882
