### ISSUE TITLE
analyticsinsight.net: ads

### ISSUE THREAD

**Issue by chirag127** [uBlockOrigin/uAssets#16977]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.analyticsinsight.net/top-10-python-code-generators-that-data-scientists-should-know/`

### Category

ads

### Description

pop up ads and the some sidebar

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/76880977/221856425-c556ce14-9014-4805-b4bf-548bac9e20aa.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 111
filterset (summary): 
  network: 83782
  cosmetic: 38865
  scriptlet: 17232
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 62267-47, never
    easyprivacy: 30962-1172, never
    plowe-0: 3675-906, never
    ublock-abuse: 79-0, never
    ublock-badware: 4467-121, never
    ublock-filters: 32706-158, never
    ublock-privacy: 274-1, never
    ublock-quick-fixes: 301-128, never
    ublock-unbreak: 1904-45, never
    urlhaus-1: 6000-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 413 ms
  maxAssetCacheWait: 202 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 1
    translate.googleapis.com: 2
    webpushs.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
````
analyticsinsight.net##.head-banner
analyticsinsight.net##.sgpb-popup-overlay
analyticsinsight.net##.sgpb-popup-dialog-main-div-wrapper
analyticsinsight.net##[href^="https://docs.google.com/forms"]
analyticsinsight.net##[href^="https://snowfallprotocol.io/"]
analyticsinsight.net##[href^="https://intellipaat.com/"]
analyticsinsight.net##[href^="https://miner-us.com/share"]
analyticsinsight.net##[href="https://app.budblockz.io/sign-up"]
````
