### ISSUE TITLE
hyperdebrid.download [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1697]
URL(s) where the issue occurs

`http://hyperdebrid.download/download/48QUDEFSNGBTZ`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by injust** [comment]
@zaphodbeebblebrox As far as I can tell, `hyperdebrid.download` no longer resolves, and this rule now only applies to `hyperdebrid.net`.

**Comment by mapx-** [comment]
The current filters
```
@@||hyperdebrid.*^$generichide
hyperdebrid.*##script:inject(abort-current-inline-script.js, decodeURI, atob)
```

should work on `.net` too

If you jave some other issue provide details and an available example link
