### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by salaojulian** [uBlockOrigin/uAssets#16978]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.facebook.com/marketplace/110000195689236/sports`

### Category

ads

### Description

Facebook ads keep appearing among purchase items

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![facebook](https://user-images.githubusercontent.com/51297573/221866414-5d7fb38e-2a7e-417d-ae31-0aeed294138a.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 86328
  cosmetic: 44372
  scriptlet: 17515
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 6-0, never
    easylist: 62267-72, never
    easyprivacy: 30962-1147, never
    plowe-0: 3675-908, never
    spa-0: 3507-145, never
    spa-1: 5065-64, never
    ublock-abuse: 79-0, never
    ublock-badware: 4467-120, never
    ublock-filters: 32706-312, never
    ublock-privacy: 274-0, never
    ublock-quick-fixes: 301-5, never
    ublock-unbreak: 1904-44, never
    urlhaus-1: 6000-0, never
filterset (user): [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1272 ms
  maxAssetCacheWait: 3 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    facebook.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
There is a open issue already https://github.com/uBlockOrigin/uAssets/issues/3367
