### ISSUE TITLE
quora.com: breakage (YouTube videos)

### ISSUE THREAD

**Issue by mikkorantalainen** [uBlockOrigin/uAssets#16979]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.quora.com/Why-aren-t-trijets-used-anymore-I-understand-they-were-used-to-bypass-the-faa-60-min-rule-but-wouldn-t-they-be-more-efficient-than-4-engine-jets-for-long-haul-flights/answer/Franklin-Veaux?comment_id=320744964&comment_type=2`

### Category

breakage

### Description

Youtube videos in Quora comments (created by adding a suitable URL in the comment, e.g. `https://youtu.be/vJhB_ikhym8`) show up as a thumbnail and play button but when the play button is clicked, the video simply disappears. There are no errors in developer console.

I'm using the filter lists listed in the configuration. I checked "I did not answer truthfully to ALL the above checkpoints." because I'm not sure if this is considered as "external filter list".

I verified that the issue happens with all my custom rules removed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 90742
  cosmetic: 137061
  scriptlet: 24523
  html: 0
listset (total-discarded, last-updated): 
  added: 
    FIN-0: 2151-0, 2d.23h.40m
    adguard-annoyance: 64389-95, 2d.23h.39m
    fanboy-cookiemonster: 45815-3599, 4d.3h.56m
    ublock-annoyances: 4841-192, 2d.23h.38m
  default: 
    user-filters: 20-2, never
    easylist: 62346-102, 5d.4h.43m
    easyprivacy: 30963-1257, 5d.4h.42m
    plowe-0: 3675-908, 10d.19h.9m
    ublock-abuse: 79-0, 1d.1h.46m
    ublock-badware: 4601-122, 2d.23h.37m
    ublock-filters: 32069-480, 2d.23h.36m
    ublock-privacy: 276-1, 1d.1h.47m
    ublock-quick-fixes: 321-19, 1d.1h.44m
    ublock-unbreak: 1925-51, 2d.23h.35m
    urlhaus-1: 5856-0, 1d.1h.45m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 39 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 3 redacted]
urlRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 21702 ms
  maxAssetCacheWait: 8085 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    quora.com: 3
    cookielaw.org: 1
    stripe.com: 1
```
</details>

**Comment by okiehsch** [comment]
> I'm not sure if this is considered as "external filter list".

All manually added lists besides your default setup are considered external.
I am not sure I completely understand how to reproduce the issue,
Here is what I see.
![image](https://user-images.githubusercontent.com/16838044/221902525-895de553-2111-4d3c-94c6-a8fac83a8443.png)

Is a subscription needed to reproduce?

**Comment by mapx-** [comment]
@mikkorantalainen 

add

```
@@||cdn.cookielaw.org/scripttemplates/otSDKStub.js$script,domain=quora.com
@@||cdn.cookielaw.org/consent/*.json$xhr,domain=quora.com
```

FA & AA breakage

**Comment by mapx-** [comment]
@okiehsch I'm using a normal quora account
