### ISSUE TITLE
trutnovinky.cz: ads

### ISSUE THREAD

**Issue by jsfsbrv** [uBlockOrigin/uAssets#16976]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://trutnovinky.cz/`

### Category

ads

### Description

Even with uBlock enabled, ads are still displayed. In this case the banner on the top and the right one on the bottom (not visible in the screenshot)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-02-28 10_41_26-Regionální portál pro Trutnov a okolí _ Trutnovinky — Mozilla Firefox](https://user-images.githubusercontent.com/97737331/221814425-879fc903-d061-4084-8946-dba0925ed828.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 85870
  cosmetic: 39435
  scriptlet: 17475
  html: 894
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33704-165, 2h.17m
    ublock-badware: 4612-5, 2h.17m
    ublock-privacy: 323-0, 2h.17m
    ublock-abuse: 79-0, 2h.17m
    ublock-unbreak: 1937-4, 2h.17m
    ublock-quick-fixes: 322-0, 2h.17m
    easylist: 63092-622, 2h.17m
    easyprivacy: 30990-1774, 2h.16m
    urlhaus-1: 6881-0, 2h.16m
    plowe-0: 3749-2, 2h.16m
    CZE-0: 737-0, 2h.16m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4523 ms (selfie)
  maxAssetCacheWait: 364 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 1
    leady.com: 4
```
</details>

**Comment by okiehsch** [comment]
`trutnovinky.cz##.banner`

**Comment by mapx-** [comment]
last commit 3 weeks ago
`CZE, SVK: EasyList Czech and Slovak`
