### ISSUE TITLE
[nsfw] h-flash.com: ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#16971]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://h-flash.com/flashjokeoftheday-checked-out/`

### Category

ads

### Description

animated banner ad removed with
```
||h-flash.com/data/image/mcs/*.jpg$image
||imobileporn.com^$all
h-flash.com##+js(set, adblocked, undefined)
```
last filter for blocked download button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 110
filterset (summary): 
  network: 76640
  cosmetic: 40475
  scriptlet: 17319
  html: 896
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1374-0, 4h.53m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 4h.53m
  default: 
    user-filters: 1564-13, never
    ublock-filters: 33698-173, 1h.37m
    ublock-badware: 4612-5, 4h.53m
    ublock-privacy: 323-0, 4h.53m
    ublock-abuse: 79-0, 4h.53m
    ublock-unbreak: 1940-4, 4h.53m
    ublock-quick-fixes: 320-0, 4h.53m
    easylist: 63075-284, 4h.53m
    easyprivacy: 30980-2120, 4h.53m
filterset (user): [array of 584 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 308 ms (selfie)
  maxAssetCacheWait: 314 ms
  unsuspendAfter: 98 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    cloudflareinsights.com: 2
    imobileporn.com: 1
    jsdelivr.net: 1
    realsrv.com: 1
    skynetworkcdn.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's fixed here: https://github.com/uBlockOrigin/uAssets/commit/bce06fa

**Comment by Daxy7** [comment]
Another url image link:
`https://h-flash.com/test`

**Comment by Daxy7** [comment]
Filter `h-flash.com##.pagebody:style(height: auto !important;)` 
Resets after attempt to collapse empty space.
**https://user-images.githubusercontent.com/91396482/224491876-f648250b-74ca-42e8-a91a-4efc89df7fe6.mp4**

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue although trying to refresh many times: https://user-images.githubusercontent.com/66517106/224519321-54b8f09d-7c7c-4d3a-be9c-e72f947e742c.mp4

Can you screenshot the logger with `blocked` option?

**Comment by Daxy7** [comment]
> Can you screenshot the logger with `blocked` option?

Blocked: https://user-images.githubusercontent.com/91396482/224529008-278aa23f-92e1-4563-81f0-65f826cb6e15.png

**Comment by stephenhawk8054** [comment]
Does this work for you?

```adb
h-flash.com##a[style*="/data/image/mcs/chat"]
```

**Comment by Daxy7** [comment]
> Does this work for you?
> 
> ```
> ||imobileporn.com/premium/
> h-flash.com##a[style*="/data/image/mcs/chat"]
> ```

Working. Thanks.

**Comment by Daxy7** [comment]
Ads are back on homepage. Banner name is now a hex code. The mcs directory has other ads too such as `2adultflashgames.com` links hidden with `h-flash.com###randomzone1`


[Unblocked ads](https://user-images.githubusercontent.com/91396482/229383114-cde99dbf-7743-4da2-a49b-1e860549271f.png)

**Comment by Daxy7** [comment]
`https://h-flash.com/nekogames-harunopan-chira-matsuri/`

Download Detection
```
h-flash.com##+js(set, ublocked, false)
```

`h-flash.com##+js(set, adblocked, false)` Obsolete

**Comment by Daxy7** [comment]
```
https://h-flash.com/x-seman-fapwall/
```

`h-flash.com##[style*="url"]` is blocking resource `Download` button

**Comment by Daxy7** [comment]
ad crap is back again
```
https://h-flash.com/gamebp-strip-snake-allison-tyler/
```
https://github.com/uBlockOrigin/uAssets/assets/91396482/73f3c9e1-42f1-4438-b816-eb72f5f2cebf
download button is blocked too

**Comment by Daxy7** [comment]
code update ads are back 

```
https://h-flash.com/gamebp-strip-snake-allison-tyler/
```
https://github.com/uBlockOrigin/uAssets/assets/91396482/5601c8fc-0912-4a48-8b83-37a920ba47d3

**Comment by stephenhawk8054** [comment]
Have you forced update all your filter lists yet?

**Comment by Daxy7** [comment]
works

**Comment by Daxy7** [comment]
placeholders can be hidden without issue 
```
https://h-flash.com/gamebp-strip-snake-allison-tyler/
```
```
h-flash.com##[id^="ads"]
```

**Comment by Daxy7** [comment]
ads and the download button is blocked

```
https://h-flash.com/k-on-dress-up-2/
```
```

```

**Comment by stephenhawk8054** [comment]
I don't see any ads and the download button appears normally for me: https://github.com/uBlockOrigin/uAssets/assets/66517106/29f0a57d-b320-4e1e-ba62-78326679289b

**Comment by Daxy7** [comment]
got it working 👍. i was using a month old filter to hide divs.
```
! h-flash.com##[id^="ads"]
h-flash.com###rightzone
h-flash.com###ads_2
```

**Comment by Daxy7** [comment]
ads are back
```
https://h-flash.com/
https://h-flash.com/phazed-rainbow-brains/
```
```
h-flash.com###randomzone1
! network
||h-flash.com/data/image/mcs/*.gif$image,1p
! cosmetic
##[href^="https://candy.ai/characters/new"]
```
https://github.com/uBlockOrigin/uAssets/assets/91396482/0537b78f-97a8-4c79-9661-63f8db38b3c4
https://github.com/uBlockOrigin/uAssets/assets/91396482/5261c261-4c2f-4624-adc0-a89ba8709410

**Comment by Daxy7** [comment]
it's loading `*.gif` from new dir `/candyai/`, best to filter incase they rename one of the img files to random
```
https://h-flash.com/phazed-rainbow-brains/
```
```
||h-flash.com/data/image/candyai/*$frame
```

**Comment by Daxy7** [comment]
it's loading `/candyai/` from the webdev team's site now, best to filter as a general rule[?]
`https://h-flash.com/phazed-rainbow-brains/`
`||mediacandy.ai^$3p`
https://github.com/uBlockOrigin/uAssets/assets/91396482/2c4c5f1d-21ce-40ea-84a2-c80b9f3e0286

**Comment by rakleed** [comment]
Ad link in the header on `https://h-flash.com/moemoe-photo/`:

https://cln.sh/Q7J8GQQNWv3cHy5qrZ1t

<details><summary>Configuration</summary>
<p>

```
uBlock Origin: 1.62.0
Chromium: 134
filterset (summary):
 network: 330629
 cosmetic: 275986
 scriptlet: 61735
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 103597-6013, 48m
  adguard-mobile: 10657-25, 48m
  adguard-spyware-url: 2014-137, 48m
  adguard-spyware: 148770-30222, 48m
  adguard-cookies: 33542-119, 48m
  ublock-cookies-adguard: 3634-20, 48m
  fanboy-cookiemonster: 44749-3752, 48m
  ublock-cookies-easylist: 3634-3634, 48m
  adguard-social: 23711-1615, 48m
  fanboy-social: 16633-4, 48m
  adguard-popup-overlays: 28826-168, 48m
  adguard-mobile-app-banners: 5913-94, 48m
  [9 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40407-111, 48m
  ublock-badware: 12014-7, 48m
  ublock-privacy: 2580-34, 48m
  ublock-unbreak: 2563-2, 48m
  ublock-quick-fixes: 315-8, 48m
  easylist: 70211-742, 48m
  easyprivacy: 53400-1876, 48m
  urlhaus-1: 27215-0, 48m
  plowe-0: 3470-383, 48m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 275 ms (selfie)
 maxAssetCacheWait: 35 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  adglare.net: 3
  cloudflareinsights.com: 1
  googletagmanager.com: 1
 extended:
  ###ads_2
  ##.nav + a[target="_blank"]
  ##[id^="ads"]
  ##body > a[target="_blank"][rel="nofollow,noopener"]
  ##+js(prevent-window-open)
```

</p>
</details>
