### ISSUE TITLE
bilibili.com: nuisance

### ISSUE THREAD

**Issue by zhao110007** [uBlockOrigin/uAssets#16987]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bilibili.com/`

### Category

nuisance

### Description

> 有一些视频位置被遮盖

**Some video locations are covered**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 103114
  cosmetic: 49114
  scriptlet: 17154
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 7-0, never
    CHN-0: 28267-110, 2d.15h.54m
    easylist: 63067-96, 1d.9m
    easyprivacy: 30990-1193, 1d.8m
    plowe-0: 3749-930, 2d.15h.55m
    ublock-abuse: 79-0, 4d.18h.39m
    ublock-badware: 4605-123, 1d.23h.57m
    ublock-filters: 32077-127, 1d.23h.56m
    ublock-privacy: 276-1, 5d.12h.5m
    ublock-quick-fixes: 328-19, 11h.14m
    ublock-unbreak: 1925-49, 1d.23h.55m
    urlhaus-1: 6831-0, 11h.13m
filterset (user): [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2182 ms (selfie)
  maxAssetCacheWait: 89 ms
popupPanel: 
  blocked: 30
  blockedDetails: 
    bilibili.com: 27
    hdslb.com: 3
```
</details>

**Comment by mapx-** [comment]
> Some video locations are covered

provide precise info, specific links, screenshot
