### ISSUE TITLE
cloudcomputingtopics.net: detection

### ISSUE THREAD

**Issue by tlostshadow01** [uBlockOrigin/uAssets#16980]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cloudcomputingtopics.net/?h=2`

### Category

detection

### Description

adblock detected its annoying

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/101035482/221909523-9382a92d-0967-4278-a06d-be87eaaaba82.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 140958
  cosmetic: 54828
  scriptlet: 18440
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt: 132-2, 22m
    adguard-mobile: 8722-21, 1d.6h.45m
    adguard-spyware-url: 926-2, 1d.6h.45m
    block-lan: 44-0, 1d.6h.45m
    curben-phishing: 40386-0, 21m
    curben-pup: 201-0, 20m
    dpollock-0: 11397-107, 1d.6h.45m
    fanboy-thirdparty_social: 69-0, 1d.6h.45m
  default: 
    user-filters: 1-0, never
    TUR-0: 11712-11, 1d.6h.42m
    easylist: 63002-477, 1d.6h.42m
    easyprivacy: 30980-1308, 1d.6h.42m
    plowe-0: 3675-1366, 10d.2h.46m
    ublock-abuse: 79-0, 10d.2h.46m
    ublock-badware: 4606-135, 1d.6h.42m
    ublock-filters: 32855-136, 1d.6h.42m
    ublock-privacy: 274-3, 10d.2h.46m
    ublock-quick-fixes: 328-123, 19m
    ublock-unbreak: 1929-53, 1d.6h.42m
    urlhaus-1: 6831-2, 19m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1233 ms (selfie)
  maxAssetCacheWait: 815 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    yieldmo.com: 2
```
</details>

**Comment by mapx-** [comment]
redirecting to `google.com`

**Comment by krystian3w** [comment]
Add origin url than fake page.

**Comment by stephenhawk8054** [comment]
Looks like it's from `anydebrid.com`: https://github.com/uBlockOrigin/uAssets/issues/16039#issuecomment-1356629366

This works for me:

```adb
@@||static.yieldmo.com/ym.adv.min.js$script,domain=cloud-computing-central.com|cloudcomputingtopics.net
```

Can anyone test it?
