### ISSUE TITLE
[nsfw] rule34.paheal.net: popups

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#16988]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rule34.paheal.net/post/list/test/1`

### Category

popups

### Description

inline popups by clicking on page or featured post

Additional Notes:
`rule34.paheal.com##+js(acis, document.querySelectorAll, popMagic)`
resolves the issue
### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://user-images.githubusercontent.com/91396482/222076092-b35dadf5-672c-4743-b9fd-0e6e7c91528e.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 110
filterset (summary): 
  network: 76661
  cosmetic: 40491
  scriptlet: 17322
  html: 896
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1374-0, 19h.27m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 19h.27m
  default: 
    user-filters: 1560-13, never
    ublock-filters: 33704-172, 19h.28m
    ublock-badware: 4612-5, 19h.28m
    ublock-privacy: 323-0, 19h.28m
    ublock-abuse: 79-0, 19h.27m
    ublock-unbreak: 1940-4, 19h.27m
    ublock-quick-fixes: 322-0, 19h.27m
    easylist: 63100-284, 19h.27m
    easyprivacy: 30990-2121, 19h.27m
filterset (user): [array of 584 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 425 ms (selfie)
  maxAssetCacheWait: 246 ms
  unsuspendAfter: 228 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    paheal.net: 1
    amung.us: 2
    ero-advertising.com: 2
    jads.co: 2
    juicyads.com: 4
    realsrv.com: 5
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/48b111bceeeba11a758a70dfcb600ffc5103d8cb
