### ISSUE TITLE
disneyplus.com: ads

### ISSUE THREAD

**Issue by tuseroni** [uBlockOrigin/uAssets#16998]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.disneyplus.com/video/6670ce77-8880-481a-aa29-ada7366ca13e`

### Category

ads

### Description

looks to be the case for all disney plus videos not just that one.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 84905
  cosmetic: 38890
  scriptlet: 17017
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63067-48, 1d.19h.10m
    easyprivacy: 30990-1172, 1d.19h.9m
    plowe-0: 3749-928, 2d.23h.14m
    ublock-abuse: 79-0, 3h.8m
    ublock-badware: 4601-123, 3d.19h.19m
    ublock-filters: 32070-111, 3d.19h.17m
    ublock-privacy: 284-1, 3h.7m
    ublock-quick-fixes: 321-16, 19h.5m
    ublock-unbreak: 1925-48, 3d.19h.18m
    urlhaus-1: 6342-0, 19h.6m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4725 ms
  maxAssetCacheWait: 1410 ms
popupPanel: 
  blocked: 55
  blockedDetails: 
    adobedtm.com: 1
    conviva.com: 30
    demdex.net: 2
    doubleclick.net: 2
    doubleverify.com: 8
    googlesyndication.com: 5
    innovid.com: 7
```
</details>

**Comment by mapx-** [comment]
@tuseroni 
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by krystian3w** [comment]
Maybe Geo specific due in Poland don't have ads yet.

**Comment by mapx-** [comment]
as reported here https://github.com/uBlockOrigin/uAssets/issues/17015

`Disney Plus, ad-supported subscription, uBlock Origin didn't block ads.`

**Comment by krystian3w** [comment]
Alex-302 in January made these scriptlets:

https://github.com/AdguardTeam/AdguardFilters/issues/137943#issuecomment-1385921670

>    ```adb
>    disneyplus.com##+js(json-prune, stream.insertion.adSession)
>    disneyplus.com##+js(json-prune, stream.insertion.points)
>    ```
 
 
>    ```adb
>    disneyplus.com##+js(json-prune, stream.insertion)
>    disneyplus.com##+js(json-prune, stream.sources.*.insertion)
>    ```

>      
>    ```adb
>    disneyplus.com##+js(json-prune, stream)
>    ```       


>    ```adb
>    disneyplus.com##+js(json-prune, pods.0.ads)
>    ```


but I don't what works and what generate delay "similar to Hulu".

**Comment by mapx-** [comment]
@JJDizz1L as I wrote above, if you are willing to share your account credentials (in private ofc) we could investigate the issue

**Comment by JJDizz1L** [comment]
@mapx- sure

**Comment by mapx-** [comment]
send the info here: `axis.trivia@gmail.com`

**Comment by JJDizz1L** [comment]
@mapx- Seems to be working just fine. Thanks for the assistance.

**Comment by Shoresy69** [comment]
FYI, the fix here also seems to work for hulu by replacing the URL.

**Comment by stephenhawk8054** [comment]
@Shoresy69 hulu is already fixed. Can you force update all your filter lists and test again?

**Comment by Shoresy69** [comment]
> @Shoresy69 hulu is already fixed. Can you force update all your filter lists and test again?

Maybe it's just a coincidence then but I tested Hulu last week and got ads. 

Was looking for a fix and came across this a few days ago. Today, I had time to try it, so I changed "disneyplus.com" to "hulu.com" from this solution and added it to my filters and it worked, but maybe it would've worked anyway and my filters just updated in the mean time. 

Just left the comment in case anyone came across this thread like I did.

In any case, it's working, thank you.

**Comment by stephenhawk8054** [comment]
> Was looking for a fix and came across this a few days ago. Today, I had time to try it, so I changed "disneyplus.com" to "hulu.com" from this solution and added it to my filters and it worked, but maybe it would've worked anyway and my filters just updated in the mean time.

It maybe because of the hulu's fix has updated to you: https://github.com/uBlockOrigin/uAssets/commit/b099d0be256b90c749b32e106668e2baa39f6133 . It was fixed 2 days ago.

Nothing related to the above filters.
