### ISSUE TITLE
veryansintv.com: detection

### ISSUE THREAD

**Issue by agritux** [uBlockOrigin/uAssets#16991]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.veryansintv.com/`

### Category

detection

### Description

Website detects blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ekran Alıntısı](https://user-images.githubusercontent.com/3532974/222058694-75060904-7080-4733-842a-bacf1bd33875.JPG)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 87014
  cosmetic: 47587
  scriptlet: 18028
  html: 883
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32926-46, 21h.56m
    ublock-badware: 4612-5, 21h.55m
    ublock-privacy: 321-0, 7d.23h.41m
    ublock-abuse: 79-0, 7d.23h.40m
    ublock-unbreak: 1925-0, 17h.12m
    easylist: 62967-616, 1d.23h.42m
    easyprivacy: 30976-1791, 1d.23h.43m
    urlhaus-1: 6881-0, 21h.54m
    plowe-0: 3749-2, 1d.23h.45m
    TUR-0: 11719-12, 21h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1549 ms (selfie)
  maxAssetCacheWait: 139 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    google.com: 2
    googlesyndication.com: 12
    googletagmanager.com: 1
    onesignal.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
veryansintv.com##+js(nostif, adblock)
```

For Turkish list? @Yuki2718

**Comment by agritux** [comment]
thank you very much

**Comment by Yuki2718** [comment]
This looks to be dismissable.
