### ISSUE TITLE
la7.it: breakage

### ISSUE THREAD

**Issue by EliaGeretto** [uBlockOrigin/uAssets#16993]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.la7.it/dirette-tv`

### Category

breakage

### Description

The live stream in the middle of the page is not displayed. It is just a black box in Firefox and a placeholder in Chrome.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 85344
  cosmetic: 38875
  scriptlet: 17024
  html: 885
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32925-58, 21h.18m
    ublock-badware: 4612-5, 21h.17m
    ublock-privacy: 323-0, 21h.21m
    ublock-abuse: 79-0, 21h.22m
    ublock-unbreak: 1937-4, 21h.16m
    ublock-quick-fixes: 329-0, 21h.12m
    easylist: 62989-615, 21h.15m
    easyprivacy: 30980-1769, 21h.14m
    urlhaus-1: 6831-0, 21h.13m
    plowe-0: 3750-2, 21h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1608 ms (selfie)
  maxAssetCacheWait: 889 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    amazon-adsystem.com: 1
    iltrovatore.it: 5
    imasdk.googleapis.com: 2
    imrworldwide.com: 2
    permutive.app: 1
    rcsmetrics.it: 1
    rcsobjects.it: 2
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
No issue in chrome on my end, instead FF .. very unstable:

sometimes working using

```
@@||components2.rcsobjects.it/rcs_adv/v1/distro/dfp/common/prebid.js$script,domain=la7.it
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=la7.it
@@||la7.it^$ghide
@@||securepubads.g.doubleclick.net/gampad/ads*la7.it$xhr,domain=imasdk.googleapis.com
*$media,domain=la7.it,redirect-rule=noopmp3-0.1s
```

@okiehsch did you test in chrome / FF / both ?

**Comment by okiehsch** [comment]
> No issue in chrome on my end, instead FF .. very unstable:

Yes, both times it did not work without `EasyList Italy` enabled. 
With chrome it worked without issue as soon as I enabled the list, same with Firefox, though the video did not start immediately it took some time to load.

**Comment by mapx-** [comment]
@EliaGeretto enable EasyList Italy
