### ISSUE TITLE
hdtoday.cc: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#16997]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hdtoday.cc/watch-movie/watch-berlin-syndrome-full-17739.1028250`

### Category

Advertisements / Residuals

### Description

Very good streaming site but some ads and layers.

`https://hdtoday.cc/home`

Try it on any movie and player to see which sources to block. Thanks a lot.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/222250780-655a6353-320e-4b29-8572-7989ac2cb898.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 127425
  cosmetic: 115252
  scriptlet: 20689
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
  added: 
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1551-229, never
    DEU-0: 6557-0, 22h.10m
    RUS-0: 39436-172, 2d.1h.5m
    fanboy-cookiemonster: 45852-214, 2d.1h.5m
  default: 
    FRA-0: 30038-47, 2d.1h.5m
    easylist: 63067-245, 2d.1h.5m
    easyprivacy: 30980-1593, 2d.1h.5m
    plowe-0: 3749-960, 2d.1h.5m
    ublock-abuse: 79-2, 2d.1h.5m
    ublock-badware: 4608-142, 2d.1h.5m
    ublock-filters: 32866-275, 2d.1h.5m
    ublock-privacy: 276-1, 2d.1h.5m
    ublock-quick-fixes: 329-123, 22h.10m
    ublock-unbreak: 1926-52, 2d.1h.5m
    urlhaus-1: 6831-0, 22h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 252 ms (selfie)
  maxAssetCacheWait: 128 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    addthis.com: 1
    googletagmanager.com: 2
    inaickoo.com: 2
    westats.dev: 1
    whoursie.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Maybe Fanboy's Annoyance, you can report at EasyList's repo.
