### ISSUE TITLE
forums.overclockers.ru

### ISSUE THREAD

**Issue by ERYuyNIrbNKrsc** [uBlockOrigin/uAssets#170]
### URL(s) where the issue occurs

`[https://forums.overclockers.ru]`

### Describe the issue

[when you come to the forum, he complains that I use a system of removal of advertising, and display the hungry cat..]

### Screenshot(s)

[uBlockOrigin On http://imgur.com/a/Nlg8W uBlockOrigin Off http://imgur.com/a/6ObXA]

### Versions

- Browser/version: [Vivaldi	1.5.638.3 (Official Build) dev (64-bit)]
- uBlock Origin version: [uBlock Origin v1.9.15.101]

### Settings

- [nothing changed]

### Notes

[sorry but I do not understand this, to do the investigation :(]

**Comment by IDKwhattoputhere** [comment]
Make sure you're subscribed to ![](https://cloud.githubusercontent.com/assets/16030872/19603620/2b218970-97b2-11e6-9abd-d1e5a3634978.png)

**Comment by gorhill** [comment]
> Make sure you're subscribed to Ru AdList

That is the solution.
