### ISSUE TITLE
librefutboltv.com: breakage

### ISSUE THREAD

**Issue by MaurOwO** [uBlockOrigin/uAssets#17001]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://librefutboltv.com/`

### Category

breakage

### Description

it list tv channels and sometimes the css file doesn't load.
And it even blocks the page when the page is safe

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![imagen](https://user-images.githubusercontent.com/89175228/222298453-ff5e3058-2993-4581-84f2-d31ea3cf3232.png)
![imagen](https://user-images.githubusercontent.com/89175228/222298506-ac962572-26e7-436e-9ff7-a7ee3e8ac0eb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 87953
  cosmetic: 44403
  scriptlet: 17306
  html: 885
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32920-39, 2d.3h.36m
    ublock-badware: 4612-5, 2d.3h.35m
    ublock-privacy: 323-0, 2d.3h.34m
    ublock-abuse: 79-0, 2d.3h.33m
    ublock-unbreak: 1937-4, 2d.3h.32m
    ublock-quick-fixes: 332-18, 1d.3h.1m
    easylist: 63083-664, 2d.3h.23m
    easyprivacy: 30980-1787, 2d.3h.22m
    urlhaus-1: 6831-0, 1d.3h
    plowe-0: 3749-2, 2d.3h.20m
    spa-0: 3507-10, 1d.3h.2m
    spa-1: 5065-164, 2d.3h.41m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 360 ms (selfie)
  maxAssetCacheWait: 178 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    librefutboltv.com: 4
    googletagmanager.com: 1
    sharethis.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test if adding these filters work?

```adb
||librefutboltv.com^$badfilter
||librefutboltv.com^$3p
```

(Add in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click Apply changes, go back to the website and press Ctrl + F5 to reload the page.)

**Comment by MaurOwO** [comment]
Thanks it worked!

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
Fixed here: https://github.com/easylist/easylist/commit/5eea1f5
