### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by TitoFlores97** [uBlockOrigin/uAssets#17007]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/`

### Category

ads

### Description

I keep getting advertisements before and during broadcasts.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 109
filterset (summary): 
  network: 87055
  cosmetic: 44419
  scriptlet: 17324
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63067-48, 2d.23h.59m
    easyprivacy: 30980-1172, 2d.23h.58m
    plowe-0: 3739-925, 6d.9h.56m
    spa-0: 3508-10, 20h.33m
    spa-1: 5088-192, 1h.34m
    ublock-abuse: 79-0, 8d.3h.33m
    ublock-badware: 4618-123, 1h.33m
    ublock-filters: 32083-143, 1h.32m
    ublock-privacy: 274-1, 8d.3h.32m
    ublock-quick-fixes: 332-19, 20h.32m
    ublock-unbreak: 1928-51, 1h.31m
    urlhaus-1: 5962-0, 20h.31m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1147 ms (selfie)
  maxAssetCacheWait: 839 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    amazon-adsystem.com: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
