### ISSUE TITLE
[nsfw] sacoronavirus.co.za: popups

### ISSUE THREAD

**Issue by zs5zk** [uBlockOrigin/uAssets#17002]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sacoronavirus.co.za/`

### Category

popups

### Description

I Do not want `https://sacoronavirus.co.za` to appear on my PC as a popup or any other method. How do I block this URL to appear on my pages?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 84885
  cosmetic: 38909
  scriptlet: 17017
  html: 887
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32896-58, 3d.18h.32m
    ublock-badware: 4625-5, 3d.18h.31m
    ublock-privacy: 323-0, 3d.22h.34m
    ublock-abuse: 79-0, 3d.22h.33m
    ublock-unbreak: 1936-4, 3d.18h.30m
    ublock-quick-fixes: 335-0, 4h.12m
    easylist: 63144-613, 1d.17h.5m
    easyprivacy: 30992-1767, 1d.17h.4m
    urlhaus-1: 6250-0, 4h.11m
    plowe-0: 3739-2, 7d.20h.13m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3148 ms (selfie)
  maxAssetCacheWait: 2403 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
> to appear on my PC as a popup

If that popup does not appear on your desktop as a result of browser navigation then it's about some malware. 

scan your system using:
https://www.f-secure.com/online-scanner

**Comment by iam-py-test** [comment]
This appears to be South Africa's SARS-CoV2/COVID-19 resource website. I do not see anything malicious about it. Can you take a screenshot of the "popups" you are seeing? Is this a Windows, MacOS, or Linux computer?
If you want to block this website, you can use this filter (put it in the My Filters tab in uBo):
```adblock
||sacoronavirus.co.za^$all
```
Can you try [Mozilla's steps on cleaning Firefox?](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-caused-malware)
If you are having malware problems, you are probably better off asking for help somewhere like [Malwarebytes Forums](https://forums.malwarebytes.com/topic/9573-im-infected-what-do-i-do-now/) or [BleepingComputer](http://www.bleepingcomputer.com/forums), as this is for reporting issues with uBo **not** seeking malware removal help.
