### ISSUE TITLE
gyanitheme.com: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#17004]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gyanitheme.com/`

### Category

detection

### Description

Shortener

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox Mobile: 110
filterset (summary): 
  network: 86051
  cosmetic: 28844
  scriptlet: 17074
  html: 890
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33037-281, 2d.17h.18m
    ublock-badware: 4604-5, 2d.21h.43m
    ublock-privacy: 323-1, 13d.2h.11m
    ublock-abuse: 79-0, 16h.26m
    ublock-unbreak: 1942-0, 2d.21h.42m
    ublock-quick-fixes: 336-4, 12h.25m
    adguard-mobile: 8732-172, 2d.17h.17m
    easylist: 63168-17589, 1d.15h.43m
    easyprivacy: 30990-1761, 1d.15h.42m
    urlhaus-1: 5962-0, 12h.24m
    plowe-0: 3675-2, 9d.9h.6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2810 ms (selfie)
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    clarity.ms: 1
    doubleclick.net: 14
    googlesyndication.com: 1
    googletagmanager.com: 1
    jsdelivr.net: 1
```
</details>

**Comment by aicynide** [comment]
https://toonshub.ml/redirect/?url=S3AraEdBSExIRlk1aHFhbHMveFdoZlJzS2ZiZnFFY1NZUFdJQ0RuVjJJMWQ4Q3YzeEZtTHpPZ252WDR2WEJpK2dpd2t1a1NoSFo5Q3RBMGwwbHRvTmc9PQ==

**Comment by ghajini** [comment]
@aicynide
describe your issue with screenshots, i can't reproduce detection

**Comment by aicynide** [comment]
@ghajini @ghajini I'm not sure which website is actually detecting uBlock. You'll get the website by opening https://toonshub.ml/redirect/?url=S3AraEdBSExIRlk1aHFhbHMveFdoZlJzS2ZiZnFFY1NZUFdJQ0RuVjJJMWQ4Q3YzeEZtTHpPZ252WDR2WEJpK2dpd2t1a1NoSFo5Q3RBMGwwbHRvTmc9PQ==

**Comment by aicynide** [comment]
@MasterKia @ghajini 
![Screenshot_20230302-211712_Mull](https://user-images.githubusercontent.com/97217381/222477996-5c7fa2be-66a3-40b0-88f0-f6de98bff7c7.jpg)

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by aicynide** [comment]
I think restarting browser fixed it
