### ISSUE TITLE
tii.la: [unknown]

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#17019]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tii.la/reGL62E`

### Category

[unknown]

### Description

 Adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 102229
  cosmetic: 60035
  scriptlet: 18563
  html: 901
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33685-165, 1d.16h.14m
    ublock-badware: 4622-5, 1d.16h.14m
    ublock-privacy: 321-0, 10d.3h.36m
    ublock-abuse: 79-0, 10d.3h.35m
    ublock-unbreak: 1931-5, 1d.16h.14m
    ublock-quick-fixes: 339-0, 2h.42m
    easylist: 62998-593, 3d.20h.34m
    easyprivacy: 30976-1784, 3d.20h.33m
    urlhaus-1: 6492-0, 2h.43m
    plowe-0: 3739-2, 8d.20h.50m
    RUS-0: 39459-171, 1d.8h.14m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1616 ms (selfie)
  maxAssetCacheWait: 632 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    tii.la: 2
    arsnivyr.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    iclickcdn.com: 1
    trustbummler.com: 1
```
</details>

**Comment by mapx-** [comment]
You already reported the issue
https://github.com/uBlockOrigin/uAssets/issues/17010

Did you update the filter lists ?
