### ISSUE TITLE
whatfontis.com: detection

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17016]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.whatfontis.com/`

### Category

detection

### Description

Video of the steps:

`https://user-images.githubusercontent.com/91396482/222616168-ea483ec4-6a27-44d9-8653-d4dd17e8f172.mp4`

Code at the bottom of the website:

```
function checkImageExists(imageUrl, callBack) {
var imageData = new Image();
imageData.onload = function() {
callBack(true);
};
imageData.onerror = function() {
callBack(false);
};
imageData.src = imageUrl;
}
</script>
<script>
$(document).ready( function() {
  window.setTimeout( function() 
  {
    var bottomad = $('#bottomAd');
    
    if (bottomad.length == 1) 
    {
      if (bottomad.height() == 0) 
      {
        gtag('event', 'display', {'event_category': 'adBlock','event_label': 'adBlockDetected1','value': '1'});
        
        $( "(long message)" );
        	
      } 
      else 
      {
        gtag('event', 'display', {'event_category': 'adBlock','event_label': 'adBlockDetected0','value': '0'});
      }
    }      
  }, 1);
});
</script>
<div id="bottomAd" style="font-size: 2px;">&nbsp;</div>
```

Additional Notes:
`whatfontis.com##+js(set, gtag, undefined)`
resolves the issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 110
filterset (summary): 
  network: 76876
  cosmetic: 40523
  scriptlet: 17337
  html: 901
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1437-0, 1d.3h.12m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 2d.6m
  default: 
    user-filters: 1562-13, never
    ublock-filters: 33684-240, 1d.18h.20m
    ublock-badware: 4622-5, 2d.6m
    ublock-privacy: 333-0, 2d.6m
    ublock-abuse: 79-0, 2d.6m
    ublock-unbreak: 1942-5, 2d.6m
    ublock-quick-fixes: 335-0, 23h.59m
    easylist: 63275-187, 23h.33m
    easyprivacy: 30999-2145, 23h.33m
filterset (user): [array of 590 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 275 ms (selfie)
  maxAssetCacheWait: 291 ms
  unsuspendAfter: 95 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
    powerad.ai: 1
```
</details>

**Comment by ghajini** [comment]
It's an annoyance , intended functions work

fix is in `uBlock filters – Annoyances` ,enable list from ublock settings

**Comment by mapx-** [comment]
right, I have always that list enabled ;)
