### ISSUE TITLE
chess.com: detection

### ISSUE THREAD

**Issue by DautTheGod** [uBlockOrigin/uAssets#17013]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.chess.com/puzzles/rated`

### Category

detection

### Description

It shows disable adblocker message

### Screenshot(s)

![image](https://user-images.githubusercontent.com/99358963/222564088-eb0c2100-6959-41b9-8c7c-aaba7a879e93.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 109
filterset (summary): 
  network: 84689
  cosmetic: 38932
  scriptlet: 17037
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63249-47, 22h.39m
    easyprivacy: 30996-1172, 22h.38m
    plowe-0: 3750-928, 22h.37m
    ublock-abuse: 79-0, 22h.35m
    ublock-badware: 4618-123, 22h.33m
    ublock-filters: 32075-105, 22h.32m
    ublock-privacy: 284-2, 22h.31m
    ublock-quick-fixes: 338-19, 22h.30m
    ublock-unbreak: 1920-48, 22h.29m
    urlhaus-1: 5962-0, 22h.28m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 293 ms (selfie)
  maxAssetCacheWait: 80 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    moatads.com: 2
```
</details>

**Comment by mapx-** [comment]
You didn't tell us the steps to get that message.
I guess it's when "You’ve hit your daily limit" and clicking the link to see the video.
