### ISSUE TITLE
ghostbin.me: ads

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [uBlockOrigin/uAssets#17017]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ghostbin.me/`

### Category

ads

### Description

two gif ads on the top, showing randomized ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 85441
  cosmetic: 39198
  scriptlet: 17348
  html: 900
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33588-56, now
    ublock-badware: 4614-0, now
    ublock-privacy: 336-0, now
    ublock-abuse: 78-0, now
    ublock-unbreak: 1932-16, now
    ublock-quick-fixes: 339-0, now
    easylist: 63339-566, now
    easyprivacy: 31004-1768, now
    urlhaus-1: 6492-0, now
    plowe-0: 3751-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2500 ms
  maxAssetCacheWait: 367 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    cloudflareinsights.com: 2
```
</details>

**Comment by mapx-** [comment]
@hippopotamusgoldfish report at [easylist repository](https://github.com/easylist/easylist/issues)

@ryanbr
