### ISSUE TITLE
tii.la: detection

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#17010]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tii.la/TXvrqq?utm_source=AutoBitco.in`

### Category

detection

### Description

shortlink

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 101989
  cosmetic: 60031
  scriptlet: 18563
  html: 901
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 33685-169, 1d.10m
    ublock-badware: 4622-5, 1d.10m
    ublock-privacy: 321-0, 9d.11h.32m
    ublock-abuse: 79-0, 9d.11h.31m
    ublock-unbreak: 1931-5, 1d.10m
    ublock-quick-fixes: 341-0, 10h.40m
    easylist: 62998-610, 3d.4h.31m
    easyprivacy: 30976-1767, 3d.4h.30m
    urlhaus-1: 6250-0, 10h.41m
    plowe-0: 3739-2, 8d.4h.46m
    RUS-0: 39459-171, 16h.10m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1616 ms (selfie)
  maxAssetCacheWait: 537 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    arsnivyr.com: 2
    e2ertt.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    iclickcdn.com: 1
    trustbummler.com: 1
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/839f9e78696a39f60311c6277ccfc5b9c8e98960
