### ISSUE TITLE
Disney Plus

### ISSUE THREAD

**Issue by JJDizz1L** [uBlockOrigin/uAssets#17015]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Disney Plus, ad-supported subscription, uBlock Origin didn't block ads.

### URL(s) where the issue occurs.

`https://www.disneyplus.com`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/37751357/222614276-0d353871-f75b-4020-857d-808980bc2986.png)

### uBO version

1.47.2

### Browser name and version

Microsoft Edge 110.0.1587.57 (64-bit)

### Settings

n/a

### Notes

n/a

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues/16998
