### ISSUE TITLE
mbe.modelica.university: breakage

### ISSUE THREAD

**Issue by BrunaPitanga** [uBlockOrigin/uAssets#17024]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mbe.modelica.university/components/subsystems/heat_transfer/`

### Category

breakage

### Description

`...` buttons don't work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://user-images.githubusercontent.com/115604365/222766111-88799ba0-7f36-4a8b-b321-d7968188574c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 83781
  cosmetic: 38865
  scriptlet: 17226
  html: 895
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33533-285, never
    ublock-badware: 4471-5, never
    ublock-privacy: 321-0, never
    ublock-abuse: 79-0, never
    ublock-unbreak: 1915-0, never
    ublock-quick-fixes: 305-3, never
    easylist: 62267-174, never
    easyprivacy: 30962-1206, never
    urlhaus-1: 6000-0, never
    plowe-0: 3675-908, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5807 ms
  maxAssetCacheWait: 36 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    modelica.university: 2
    cloudflareinsights.com: 2
    google-analytics.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||mbe.modelica.university/_next/static/*/pages/pageview.js$script,1p`
