### ISSUE TITLE
[nsfw] porntn.com: breakage

### ISSUE THREAD

**Issue by femto-mq** [uBlockOrigin/uAssets#17027]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://porntn.com/videos/9176/asmr-claudy-29-october-2021-vampire-claudy/`

### Category

breakage

### Description

video does not show when ublock is on 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 106901
  cosmetic: 48197
  scriptlet: 17064
  html: 0
listset (total-discarded, last-updated): 
  added: 
    FRA-0: 30039-34, 1d.12h.10m
    ara-0: 2745-5, 9h.5m
  default: 
    user-filters: 0-0, never
    easylist: 62959-227, 5d.9h.22m
    easyprivacy: 31007-1498, 3m
    plowe-0: 3749-954, 3d.22h.40m
    ublock-abuse: 79-1, 1d.20h.32m
    ublock-badware: 4618-142, 1d.12h.14m
    ublock-filters: 32075-205, 1d.12h.13m
    ublock-privacy: 284-2, 2d.22h.33m
    ublock-unbreak: 1934-45, 1d.12h.12m
    urlhaus-1: 6492-0, 9h.6m
filterset (user): [empty]
trustedset: 
  added: [array of 48 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 183 ms (selfie)
  maxAssetCacheWait: 209 ms
popupPanel: 
  blocked: 8
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-scripting: true
  blockedDetails: 
    41291ba668.com: 2
    bookmsg.com: 4
    nereserv.com: 1
    ntvpforever.com: 1
```
</details>

**Comment by okiehsch** [comment]
`porntn.com#@#.banner_ad`
@ryanbr
