### ISSUE TITLE
Using element picker on bing chat  

### ISSUE THREAD

**Issue by tom-321** [uBlockOrigin/uAssets#17026]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

How can I block these (screenshot) elements on bing.com/chat 
https://workupload.com/file/uTKTFnVZ8R2

It always blocks the whole page ?!

### URL(s) where the issue occurs.

https://bing.com/chat

### Screenshot(s)

https://workupload.com/file/uTKTFnVZ8R2

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 86835
  cosmetic: 43156
  scriptlet: 17032
  html: 887
listset (total-discarded, last-updated): 
  default: 
    user-filters: 21-0, never
    ublock-filters: 32898-70, 1d.23h.10m
    ublock-badware: 4622-5, 1d.23h.9m
    ublock-privacy: 321-0, 11d.23h.39m
    ublock-abuse: 79-0, 11d.23h.39m
    ublock-unbreak: 1931-5, 1d.23h.8m
    easylist: 62906-613, 5d.4h.24m
    easyprivacy: 30974-1760, 5d.4h.23m
    plowe-0: 3675-2, 11d.23h.39m
    DEU-0: 6562-2, 19h.52m
    urlhaus-1: 6216-0, 19h.51m
    ublock-quick-fixes: 339-0, 19h.50m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 516 ms (selfie)
  maxAssetCacheWait: 174 ms
```
</details>

**Comment by mapx-** [comment]
add

```
bing.com##.container-item
bing.com##.learn-tog-item
bing.com##.privacy-statement
```
