### ISSUE TITLE
proiezionidiborsa.it [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1702]
URL(s) where the issue occurs

`https://www.proiezionidiborsa.it/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.2

Settings

Default

**Comment by gorhill** [comment]
@@||proiezionidiborsa.it^$generichide
