### ISSUE TITLE
Freegeoip is blocked and it is not an ad service.

### ISSUE THREAD

**Issue by pwnrod** [uBlockOrigin/uAssets#1703]
### URL(s) where the issue occurs

`https://www.familyallergy.com/find-a-location/`
`https://www.familyallergy.com/`

### Describe the issue

With uBlock Origin enabled the website cannot get your location so the map fails to load on the first link.

The second link, the Pollen count widget on the top right of the page should show the region that you are in but fails and only shows a blank box.

### Screenshot(s)

Screenshot reference for the first link: http://prntscr.com/iq6n4r
Screenshot reference for the second link: http://prntscr.com/iq6msc

### Versions

- Browser/version: [Firefox 58.0.2 (64-bit)]
- uBlock Origin version: [1.15.10]

### Settings

- No Changes

### Notes
The website uses freegeoip.net to get a general lat/lng associated with the client's ip address to show map locations etc.

freegeoip.net seems be referenced in the following locations. I see it in filters and third party lists  however this service has nothing to do with ads.

https://github.com/uBlockOrigin/uAssets/blob/2fb50109b3307c51303bed97219388932c39bd76/filters/unbreak.txt#L672

https://github.com/uBlockOrigin/uAssets/blob/2fb50109b3307c51303bed97219388932c39bd76/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt#L4517

https://github.com/uBlockOrigin/uAssets/blob/2fb50109b3307c51303bed97219388932c39bd76/thirdparties/winhelp2002.mvps.org/hosts.txt#L845

**Comment by mapx-** [comment]
@ryanbr

**Comment by pwnrod** [comment]
@mapx- Thanks for the quick response to the issue, however this doesn't resolve the underlying problem we're running into. freegeoip.net is a service that we'll want to use in the future for other sites. I don't see a reason why the service itself is being blocked?

**Comment by uBlock-user** [comment]
Ask the source. It's being blocked by MVPS Hosts File, asking for the reason here won't help. uAssets can only whitelist to overide the underlying blacklist by MVPS.

**Comment by SMed79** [comment]
> I don't see a reason why the service itself is being blocked?

user privacy.

**Comment by jasekiw** [comment]
@SMed79 ip geolocation is extremely inaccurate and the ip address is given as soon as you arrive on a website. An ip location can be grabbed on the back-end instead invalidating this block. This should be the user's decision similar to how `navigator.geolocation` requires it but this block prevents the use of location completely.

This case will have to be argued with MVPS but there is more depth to it than it's blocked because of user privacy.

**Comment by SMed79** [comment]
@jasekiw The map can be displayed without the dependency of the IP address.
