### ISSUE TITLE
geeksforgeeks.org: breakage

### ISSUE THREAD

**Issue by nandanreddyp** [uBlockOrigin/uAssets#17038]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.geeksforgeeks.org/python-program-to-insert-an-element-into-sorted-list/`

### Category

breakage

### Description

I can't scroll after hiding  login element in provided website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 85149
  cosmetic: 38921
  scriptlet: 17034
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 6-0, never
    easylist: 63092-48, 3d.16h.16m
    easyprivacy: 30990-1172, 3d.16h.15m
    plowe-0: 3750-928, 3d.3h.23m
    ublock-abuse: 79-0, 3d.6h.3m
    ublock-badware: 4608-123, 3d.16h.14m
    ublock-filters: 32102-112, 3d.16h.13m
    ublock-privacy: 276-1, 3d.6h.2m
    ublock-quick-fixes: 340-15, 7h.8m
    ublock-unbreak: 1928-48, 3d.16h.12m
    urlhaus-1: 6552-0, 7h.7m
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3085 ms (selfie)
  maxAssetCacheWait: 274 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    geeksforgeeks.org: 5
    google.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 2
    googletagservices.com: 1
    servedby-buysellads.com: 1
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
remove whatever filter you created and enable fanboy's annoyances list or AdGuard annoyances list
