### ISSUE TITLE
[nsfw] youtube.com: ads

### ISSUE THREAD

**Issue by ksmcmldg** [uBlockOrigin/uAssets#17033]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=ze81ifx7s5g`

### Category

ads

### Description

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 86977
  cosmetic: 47597
  scriptlet: 18111
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    TUR-0: 11489-11, 1d.13h.45m
    easylist: 63249-66, 2d.14h.3m
    easyprivacy: 30980-1177, 2d.14h.2m
    plowe-0: 3749-929, 7d.12h.18m
    ublock-abuse: 79-0, 10d.10h.15m
    ublock-badware: 4612-123, 1d.13h.44m
    ublock-filters: 32083-112, 1d.13h.43m
    ublock-privacy: 276-1, 10d.10h.14m
    ublock-quick-fixes: 342-19, 13h.40m
    ublock-unbreak: 1932-53, 1d.13h.42m
    urlhaus-1: 6555-0, 13h.39m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2271 ms (selfie)
  maxAssetCacheWait: 73 ms
popupPanel: 
  blocked: 52
  blockedDetails: 
    googleadservices.com: 2
    googlesyndication.com: 1
    youtube.com: 49
```
</details>

**Comment by ksmcmldg** [comment]
.

**Comment by mapx-** [comment]
see https://github.com/easylist/easylist/wiki/Youtube-Issues
duplicate #7636
