### ISSUE TITLE
nytimes.com: breakage

### ISSUE THREAD

**Issue by rohitsud** [uBlockOrigin/uAssets#17031]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nytimes.com/`

### Category

breakage

### Description

Nytimes opens with a blank page on Firefox on Android.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox Mobile: 110
filterset (summary): 
  network: 86440
  cosmetic: 28780
  scriptlet: 17094
  html: 893
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32923-278, 19h.2m
    ublock-badware: 4616-5, 23h.7m
    ublock-privacy: 336-1, 3h.10m
    ublock-abuse: 78-0, 1d.4h.56m
    ublock-unbreak: 1948-16, 23h.5m
    adguard-mobile: 8746-172, 23h.6m
    easylist: 62967-17542, 5d.3h.24m
    easyprivacy: 30980-1778, 4d.23h.56m
    urlhaus-1: 6492-0, 23h.4m
    plowe-0: 3749-2, 5d.5h.19m
    ublock-quick-fixes: 340-0, 23h.3m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1612 ms (selfie)
  maxAssetCacheWait: 220 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    nytimes.com: 8
    amazon-adsystem.com: 1
    geoedge.be: 1
    googletagmanager.com: 1
    nyt.com: 1
```
</details>

**Comment by mapx-** [comment]
Are you logged in ?

**Comment by rohitsud** [comment]
Yes

**Comment by mapx-** [comment]
logged on / free subscription => no issue on my end

**Comment by rohitsud** [comment]
That is odd. It is working for me too today. We can mark it as closed and I will report if this happens consistently again.
