### ISSUE TITLE
notalwaysright.com: breakage

### ISSUE THREAD

**Issue by kotenok2000** [uBlockOrigin/uAssets#17039]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

"uBlock filters" breaks disqus at `https://notalwaysright.com/thanks-for-clearing-that-up/68931/`

### URL(s) where the issue occurs.

`https://notalwaysright.com/thanks-for-clearing-that-up/68931/`

### Screenshot(s)

Without filter
https://user-images.githubusercontent.com/8822292/222923417-03700d50-d8a9-4944-ac4f-b485cad7e007.png
With filter
https://user-images.githubusercontent.com/8822292/222923420-6f6b71cf-9cd9-400b-982a-25ca44629d25.png

### uBO version

1.47.2

### Browser name and version

Google Chrome	110.0.5481.178 (Официальная сборка) (64 бит) (cohort: Bypass)

### Settings

It  works with this filter set:
https://user-images.githubusercontent.com/8822292/222923583-54652104-2a4c-4454-b5c2-282c615bbcf0.png
Doesn't work when i enable "Ublock filters"
https://user-images.githubusercontent.com/8822292/222923645-172c662d-f54e-4660-aa83-70f442a41ccd.png

[my-ublock-dynamic-rules_2023-03-04_21.51.20.txt](https://github.com/uBlockOrigin/uAssets/files/10889410/my-ublock-dynamic-rules_2023-03-04_21.51.20.txt)
[my-ublock-static-filters_2023-03-04_21.51.13.txt](https://github.com/uBlockOrigin/uAssets/files/10889411/my-ublock-static-filters_2023-03-04_21.51.13.txt)

**Comment by garry-ut99** [comment]
I've tried on Firefox and Opera and can't reproduce (I don't use Chrome).

**Comment by kotenok2000** [comment]
Here is exported ublock origin settings
[my-ublock-backup_2023-03-05_00.43.50.txt](https://github.com/uBlockOrigin/uAssets/files/10889736/my-ublock-backup_2023-03-05_00.43.50.txt)

**Comment by garry-ut99** [comment]
Still can't reproduce the issue on Opera with your settings.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by kotenok2000** [comment]
I noticed that having ublock filters enabled displays this filtration rule in logger
notalwaysright.com##+js(abort-current-script, document.createElement, admiral)

**Comment by garry-ut99** [comment]
I see many issues on uAssets tracker with Disqus comments blocked: 
https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+disqus+sort%3Aupdated-desc+
And a single issue on AG tracker: https://github.com/AdguardTeam/AdguardFilters/issues/3531

If you suspect some filter you can try to whitelist it, for example:
`notalwaysright.com#@#+js(acis, document.createElement, admiral)`
I don't know what else is blocked at your end, but you can also try some generic unblocking filters, for example:
`@@||disqus.com^` or `@@||disquscdn.com^` - if one of them work, it will need to be narrowed further because they are too generic and their purpose is only temporary unblock to confirm the breakage.

**Comment by kotenok2000** [comment]
Whitelist filter fixes it

**Comment by stephenhawk8054** [comment]
> Whitelist filter fixes it

Which one?

**Comment by kotenok2000** [comment]
|notalwaysright.com#@#+js(acis, document.createElement, admiral)|

**Comment by stephenhawk8054** [comment]
It's weird. I have that filter enabled on chromium but disqus loads normally.

**Comment by garry-ut99** [comment]
Related bug: https://github.com/uBlockOrigin/uBlock-issues/issues/1274#issuecomment-1455021945

**Comment by mapx-** [comment]
however, removed (obsolete)
https://github.com/uBlockOrigin/uAssets/commit/3f6f843e9f861ed2b24efa30171a5e7103c8017f
