### ISSUE TITLE
bostonglobe.com uBlock filter causes unnecessary scroll bar

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#1704]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.bostonglobe.com/

### Describe the issue

`bostonglobe.com##html:style(overflow: auto !important;)` in uBlock filters add an unnecessary scroll bar.

### Screenshot(s)

![capture](https://user-images.githubusercontent.com/22258847/37321840-2adecdce-2672-11e8-9694-1dffb617c8c4.PNG)

### Notes
You should be able to remove `bostonglobe.com##html:style(overflow: auto !important;)` to fix the issue -- the ##body overflow fix filter should be enough to override the issue.

**Comment by okiehsch** [comment]
Thx, I will remove the filter.

Annother issue with the site is that comments are broken, I will fix that.
