### ISSUE TITLE
open.spotify.com: nuisance

### ISSUE THREAD

**Issue by Vicantropo** [uBlockOrigin/uAssets#17040]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/playlist/5fYJJqmgJKGeibfqR7RG0e`

### Category

nuisance

### Description

When listening my playlist, it pauses. At some point it didn't play no longer even if i jump to another song or play another song in the same playlist. So i used first the "element selection mode" feature then the "element removal mode" feature cause it show a spotify disturbing ad but without audio and it held there not allowing to continue playing the playlist or other songs. It seemed to work a little but the music still pauses and although the song is still "plaiying", nothing is heard. It's worth mentioning that just today i experience these issues 'cause before i didn't have any trouble of this kind.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 184115
  cosmetic: 84249
  scriptlet: 31380
  html: 887
listset (total-discarded, last-updated): 
  added: 
    https://winhelp2002.mvps.org/hosts.txt: 8729-0, 1d.4h.34m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39190-3941, 3d.23h.45m
    adguard-generic: 68236-5770, 3d.23h.41m
    adguard-mobile: 8734-200, 3d.23h.42m
    adguard-spyware-url: 928-4, 3d.23h.43m
    block-lan: 44-0, 16d.20h.34m
    curben-phishing: 46142-13, 3h.38m
    curben-pup: 200-0, 3h.39m
  default: 
    user-filters: 1-0, never
    ublock-filters: 32925-112, 3d.23h.40m
    ublock-badware: 4612-6, 3d.23h.39m
    ublock-privacy: 323-53, 3d.18h.18m
    ublock-abuse: 79-0, 3d.15h.7m
    ublock-unbreak: 1939-52, 3d.23h.38m
    ublock-quick-fixes: 335-0, 3h.37m
    easylist: 63278-921, 1d.4h.32m
    easyprivacy: 31000-12907, 1d.4h.35m
    urlhaus-1: 6532-0, 3h.36m
    plowe-0: 3739-447, 8d.14h.1m
    spa-0: 3508-1, 3h.40m
    spa-1: 5067-149, 3d.23h.44m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9192 ms (selfie)
  maxAssetCacheWait: 6651 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    spotify.com: 2
    doubleclick.net: 3
    googleoptimize.com: 1
    googletagmanager.com: 1
    scdn.co: 1
    sentry.io: 3
    spotifycdn.com: 1
```
</details>

**Comment by garry-ut99** [comment]
Similiar issues: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+spotify, some people say it a site's issue, so it's good to check whether the issue is still here with uBO disabled.

**Comment by mapx-** [comment]
@Vicantropo you should try using only the default settings / lists in uBO and disable other addons / extensions just to avoid some possible conflict during the tests

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
