### ISSUE TITLE
onepiece-drip.net: detection

### ISSUE THREAD

**Issue by C7LS** [uBlockOrigin/uAssets#17043]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://onepiece-drip.net/watch/one-piece-folge-361-ger-dub/`

### Category

detection

### Description

on this site you can choose between 2 streaming hosters.
anividz and voe.
voe is the one who detects ublock and tells you that using a blocker is the same like theft.
blocking java scripts will completly disable the streams.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/126999734/222939443-60a95be6-37de-43c8-bd8e-eb75d534a096.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 87405
  cosmetic: 43270
  scriptlet: 17034
  html: 888
listset (total-discarded, last-updated): 
  default: 
    user-filters: 29-2, never
    ublock-filters: 32807-38, 1d.16h.58m
    ublock-badware: 4614-0, 1d.16h.57m
    ublock-privacy: 321-0, 10d.15h
    ublock-abuse: 79-0, 10d.14h.59m
    ublock-unbreak: 1932-0, 1d.16h.56m
    ublock-quick-fixes: 335-31, 3h.25m
    easylist: 63249-200, 3d.13h.10m
    easyprivacy: 30990-1205, 3d.17h.12m
    urlhaus-1: 6532-0, 3h.27m
    plowe-0: 3739-927, 10d.10h.57m
    DEU-0: 6577-30, 3h.26m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 241 ms (selfie)
  maxAssetCacheWait: 144 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    ads-twitter.com: 2
    adscale.de: 3
    convenientcertificate.com: 2
    doubleclick.net: 1
    google-analytics.com: 1
    highrevenuecpmnetwork.com: 4
    imasdk.googleapis.com: 2
    taboola.com: 1
    yieldlove.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
There was update to voe hours ago.

Can you do this?

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by C7LS** [comment]
Ha i love you guys.
It worked instandly.
Thank you!

Some day i will support you some money when i have something left because
its worth it.

Have a nice day!


stephenhawk8054 ***@***.***> schrieb am So., 5. März 2023,
04:13:
