### ISSUE TITLE
hipertextual.com: breakage

### ISSUE THREAD

**Issue by jmoyola** [uBlockOrigin/uAssets#17047]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hipertextual.com/`

### Category

breakage

### Description

Domain is inaccessible... Timeout occurs...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox Mobile: 110
filterset (summary): 
  network: 89392
  cosmetic: 34170
  scriptlet: 17414
  html: 927
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33089-323, 1d.28m
    ublock-badware: 4608-0, 1d.27m
    ublock-privacy: 336-1, 1d.25m
    ublock-abuse: 78-0, 1d.24m
    ublock-unbreak: 1937-16, 16h.46m
    ublock-quick-fixes: 343-0, 12h.10m
    adguard-mobile: 8756-174, 1d.33m
    easylist: 63427-17583, 12h.9m
    easyprivacy: 30980-1794, 23h.33m
    urlhaus-1: 6532-0, 12h.8m
    plowe-0: 3755-2, 12h.7m
    spa-0: 3508-252, 1d.33m
    spa-1: 5090-216, 1d.33m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4814 ms (selfie)
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by jmoyola** [comment]
Tested in mobile Firefox (android).
If uninstall, clear cache and install fix it... But in 24h other time occur...

**Comment by Forero-0** [comment]
https://hipertextual.com/politica/pavel-durov-telegram-pedro-sanchez-libertad/

At the end of any article, it shows this error: 

```
Error Type: ServiceError
Message: Failed to fetch
```

<img width="1899" height="1040" alt="Image" src="https://github.com/user-attachments/assets/e3cac0d5-26b1-468c-b169-8ebbad4cd396" />

When I disable uBlock, the error no longer appears.

**Comment by mapx-** [comment]
```adb
hipertextual.com##.tpx-player-editorial
```
