### ISSUE TITLE
colearn.id: ads

### ISSUE THREAD

**Issue by ciotanuki** [uBlockOrigin/uAssets#17044]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://colearn.id/tanya/159d5258-6df5-4e5a-9f7f-b86ae8cb4fe1/Dua-batang-logam-A-dan-B-masing-masing-memiliki-besar-modulus-Young-02-x-1011-Pa-dan-4-x-1011-Pa`

### Category

ads

### Description

Ads from the original website always appears.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox Mobile: 108
filterset (summary): 
  network: 90489
  cosmetic: 30146
  scriptlet: 17113
  html: 925
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33086-305, 12h.29m
    ublock-badware: 4609-0, 12h.28m
    ublock-privacy: 323-1, 4d.23h.7m
    ublock-abuse: 79-0, 4d.23h.6m
    ublock-unbreak: 1920-18, 22h.15m
    ublock-quick-fixes: 338-0, 12h.27m
    adguard-mobile: 8756-34, 22h.23m
    easylist: 63067-17540, 4d.23h.2m
    easyprivacy: 30980-1776, 4d.23h.1m
    urlhaus-1: 6532-0, 12h.26m
    plowe-0: 3749-138, 4d.22h.59m
    IDN-0: 5458-238, 12h.30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 16239 ms (selfie)
  maxAssetCacheWait: 1486 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    clarity.ms: 1
    doubleclick.net: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    newrelic.com: 1
    sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
What ads are you talking about ?

- the app add on the right side => self promotion
- video ads ?

test
`colearn.id##+js(json-prune, *.tanya_video_ads)`

**Comment by garry-ut99** [comment]
I only have video ads on Opera Desktop & Mobile, but not on Firefox Desktop & Mobile.
The above proposed filter works for video ads.
