### ISSUE TITLE
gloryshole.com: ads

### ISSUE THREAD

**Issue by junaidd09** [uBlockOrigin/uAssets#17042]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gloryshole.com/en/brisbane/queensland/australia`

### Category

ads

### Description

I've never faced a webpage that could bypass uBlock Origin and display ads on their website. O

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox Mobile: 110
filterset (summary): 
  network: 86665
  cosmetic: 28850
  scriptlet: 17089
  html: 891
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32923-277, 1d.20h.21m
    ublock-badware: 4605-0, 1d.20h.20m
    ublock-privacy: 323-1, 3d.20h.4m
    ublock-abuse: 79-0, 3d.20h.3m
    ublock-unbreak: 1937-16, 1d.20h.19m
    ublock-quick-fixes: 342-0, 20h.24m
    adguard-mobile: 8746-172, 1d.20h.22m
    easylist: 63212-17542, 2d.12h.9m
    easyprivacy: 31000-1777, 1d.20h.23m
    urlhaus-1: 6532-0, 6h.56m
    plowe-0: 3755-2, 14h.50m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 660 ms (selfie)
  maxAssetCacheWait: 158 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    googletagmanager.com: 1
    newrelic.com: 2
    realsrv.com: 12
```
</details>

**Comment by Charlotte0234** [comment]
Down for fun

**Comment by Charlotte0234** [comment]
Hello honey how are you doing..
Do you care for a chat.
Do you have instagram or Facebook or Imessage or discord or zangi or signal
