### ISSUE TITLE
vk.com: breakage

### ISSUE THREAD

**Issue by AntowkaSabaton** [uBlockOrigin/uAssets#17049]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vk.com/feed`

### Category

breakage

### Description

Всплывающие посты пытаются появится, тем самым перенося пролистывание сайта наверх, что мешает пролистывать посты в ленте.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 102489
  cosmetic: 59956
  scriptlet: 18280
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 16-2, never
    RUS-0: 39445-12, 1d.11h.54m
    easylist: 63425-58, 1d.11h.56m
    easyprivacy: 31010-1279, 1d.11h.55m
    plowe-0: 3749-933, 7d.12h.41m
    ublock-abuse: 79-1, 11d.4h.18m
    ublock-badware: 4621-114, 11h.51m
    ublock-filters: 32037-98, 11h.49m
    ublock-privacy: 276-1, 11d.4h.19m
    ublock-quick-fixes: 341-20, 11h.48m
    ublock-unbreak: 1904-55, 11h.50m
    urlhaus-1: 6573-0, 11h.47m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 65 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7087 ms (selfie)
  maxAssetCacheWait: 319 ms
popupPanel: 
  blocked: 1295
  blockedDetails: 
    vk.com: 1184
    adriver.ru: 3
    doubleclick.net: 5
    google.com: 8
    mail.ru: 9
    mycdn.me: 16
    tns-counter.ru: 34
    vk-portal.net: 2
    weborama.fr: 1
    youtube.com: 33
```
</details>

**Comment by dimisa-RUAdList** [comment]
It's better to discuss it here: https://forums.lanik.us/viewtopic.php?t=28751
