### ISSUE TITLE
mediamarkt.com.tr: breakage

### ISSUE THREAD

**Issue by tlostshadow01** [uBlockOrigin/uAssets#17051]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mediamarkt.com.tr/tr/product/_goldmaster-sp-411-1-5m-5-li-ak%C4%B1m-korumal%C4%B1-priz-1188849.html?v=1.46.5`

### Category

breakage

### Description

website doesn't load

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Without ublockorigin 
</details>

https://user-images.githubusercontent.com/101035482/222975580-04b3a652-0e4e-4f91-b424-2a9f6bd4dcf4.jpg

With ublockorigin
https://user-images.githubusercontent.com/101035482/222975599-2fba2f0d-83bd-4429-8258-5aa648364754.jpg

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium Mobile: 107
filterset (summary): 
  network: 149737
  cosmetic: 62525
  scriptlet: 20448
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock: 132-2, 2h.9m
    adguard-spyware-url: 928-2, 2h.11m
    block-lan: 44-0, 2h.11m
    curben-phishing: 47292-0, 2h.11m
    curben-pup: 194-0, 2h.11m
    dpollock-0: 11336-106, 2h.10m
    fanboy-cookiemonster: 45937-17434, 2h.10m
    fanboy-thirdparty_social: 68-1, 2h.10m
  default: 
    user-filters: 1-0, never
    TUR-0: 11484-195, 2h.12m
    adguard-mobile: 8754-44, 2h.12m
    easylist: 63430-17308, 2h.10m
    easyprivacy: 31016-1309, 2h.10m
    plowe-0: 3755-1387, 2h.10m
    ublock-abuse: 78-0, 2h.10m
    ublock-badware: 4615-128, 2h.10m
    ublock-filters: 33051-317, 2h.10m
    ublock-privacy: 287-4, 2h.10m
    ublock-quick-fixes: 343-22, 2h.10m
    ublock-unbreak: 1909-60, 2h.10m
    urlhaus-1: 6553-2, 2h.10m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 939 ms (selfie)
  maxAssetCacheWait: 563 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    mediamarkt.com.tr: 2
    bazaarvoice.com: 11
    criteo.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Test in firefox mobile with default settings / lists

**Comment by krystian3w** [comment]
Also don't use "raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock".

**Comment by tlostshadow01** [comment]
> Also don't use "raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock".

its blocking some ads

**Comment by mapx-** [comment]
> Test in firefox mobile with default settings / lists

**Comment by krystian3w** [comment]
Report these ads to EasyList on real pages and don't report due lack in insane d3wart test of fake points.
