### ISSUE TITLE
spiegel.de: ads

### ISSUE THREAD

**Issue by C7LS** [uBlockOrigin/uAssets#17054]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.spiegel.de/panorama/gesellschaft/peking-kuriose-felsenvilla-auf-wohnturm-aengstigt-anwohner-a-916184.html`

### Category

ads

### Description

Side information: yesterday i cleared the caches and forced an update of all my filter lists after telling you VOE would detect the blocker.
(not the actual problem)

Spiegel.de shows adversitings even if the blocker is active.
the fun thing, the blocker shows me 40+ blocked things but i still have ad's.

a screenshot would be useless because you have to run the video to see what happens.

and because im not sure if you have the right link to the video i watched i post the link here again.
please dont bann my account if this is forbidden.

the link:  
`https://www.spiegel.de/panorama/gesellschaft/peking-kuriose-felsenvilla-auf-wohnturm-aengstigt-anwohner-a-916184.html`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 87826
  cosmetic: 43629
  scriptlet: 17357
  html: 903
listset (total-discarded, last-updated): 
  default: 
    user-filters: 29-2, never
    ublock-filters: 33673-38, 21h.51m
    ublock-badware: 4625-0, 21h.51m
    ublock-privacy: 336-0, 21h.51m
    ublock-abuse: 78-0, 21h.51m
    ublock-unbreak: 1915-1, 21h.51m
    ublock-quick-fixes: 335-37, 21h.51m
    easylist: 63427-198, 21h.51m
    easyprivacy: 31011-1202, 21h.51m
    urlhaus-1: 6573-0, 21h.51m
    plowe-0: 3755-931, 21h.51m
    DEU-0: 6577-30, 21h.51m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 224 ms (selfie)
  maxAssetCacheWait: 148 ms
popupPanel: 
  blocked: 76
  blockedDetails: 
    spiegel.de: 1
    adalliance.io: 3
    adnxs.com: 2
    adobedtm.com: 14
    adobetarget.com: 11
    amazon-adsystem.com: 1
    bilder-a.akamaihd.net: 1
    bing.com: 1
    criteo.net: 1
    cwi.re: 1
    demdex.net: 1
    doubleclick.net: 3
    emetriq.de: 1
    emsservice.de: 5
    indexww.com: 1
    jubbie.de: 1
    justpremium.com: 2
    jwpltx.com: 14
    omtrdc.net: 1
    opecloud.com: 1
    openx.net: 1
    outbrain.com: 1
    s3.amazonaws.com: 1
    technical-service.net: 1
    vtracy.de: 1
    yieldlab.net: 5
```
</details>

**Comment by mapx-** [comment]
> a screenshot would be useless because you have to run the video to see what happens.

what happens ?

**Comment by mapx-** [comment]
I was able to see video ads, but very rarely.

Could you test

```
spiegel.de##+js(json-prune, adBehavior)
spiegel.de##+js(no-xhr-if, ads)
```

on videos page ?
`https://www.spiegel.de/video/`

**Comment by garry-ut99** [comment]
> I was able to see video ads, but very rarely.

Same for me today, but yesterday I could reproduce almost everytime.

> Could you test

I'm unable to verify because video ads appear too rarely for me today, so I don't know whether it's the proposed fix working or video ads just not appearing.

**Comment by C7LS** [comment]
yes video ad's.
i copy pasted the code in my filter lists and it works.
thank you :)

**Comment by JobcenterTycoon** [comment]
I still get video ads

**Comment by mapx-** [comment]
Yesterday it was `"adBehavior": "prerolls"`
today: `"adBehavior": "default"`
