### ISSUE TITLE
[nsfw] kick.com: detection

### ISSUE THREAD

**Issue by Bun01294** [uBlockOrigin/uAssets#17055]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kick.com/classybeef`

### Category

detection

### Description

Detects ublock and doesn't show me the stream until i disable it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 158786
  cosmetic: 223326
  scriptlet: 38688
  html: 1041
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39141-3630, 2d.2h.12m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 3m
    https://winhelp2002.mvps.org/hosts.txt: 8729-592, 3d.1h.5m
    https://www.fanboy.co.nz/enhancedstats.txt: 2990-23, 3d.1h.6m
    adguard-generic: 68164-5830, 2d.2h.18m
    adguard-mobile: 8756-225, 2d.2h.17m
    adguard-annoyance: 64687-5091, 2d.2h.16m
    adguard-social: 19971-1021, 2d.2h.15m
    fanboy-thirdparty_social: 69-0, 7d.12h.16m
    fanboy-annoyance: 82116-70068, 7d.12h.15m
    fanboy-cookiemonster: 45843-240, 7d.12h.14m
    fanboy-social: 22359-31, 1d.1h.33m
    ublock-annoyances: 4804-8, 2d.2h.14m
    dpollock-0: 11339-1703, 10d.16h.10m
    adguard-spyware-url: 928-4, 2d.2h.13m
    block-lan: 44-0, 14d.18h.11m
    curben-pup: 200-0, 2m
  default: 
    user-filters: 95-18, never
    ublock-filters: 32849-112, 2d.2h.21m
    ublock-badware: 4615-0, 2d.2h.20m
    ublock-privacy: 333-54, 5d.25m
    ublock-abuse: 79-0, 5d.24m
    ublock-unbreak: 1933-60, 2d.2h.19m
    easylist: 63345-1062, 20h.17m
    easyprivacy: 31009-12967, 20h.16m
    urlhaus-1: 6575-0, 4m
    plowe-0: 3750-148, 4d.10h.9m
    ublock-quick-fixes: 340-1, 1m
filterset (user): [array of 95 redacted]
trustedset: 
  added: [array of 38 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 487 ms (selfie)
  maxAssetCacheWait: 487 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    datadoghq-browser-agent.com: 1
    dbxmjjzl5pc1g.cloudfront.net: 2
    google.com: 1
    googletagmanager.com: 1
    stripe.com: 10
```
</details>

**Comment by mapx-** [comment]
Is it an account necessary ?

**Comment by Bun01294** [comment]
for the website? then no

**Comment by mapx-** [comment]
I'm able to watch the video there (now the stream is offline)

![image](https://user-images.githubusercontent.com/10303732/223039677-f25d18ac-64d8-4d1e-a46b-505c006db3fa.png)

**Comment by Bun01294** [comment]
Does the website work again with other streamers with the ublock? Idk if its bug within the website, because it now works with the adblocker.

**Comment by mapx-** [comment]
> Detects ublock

Did you see an anti adblocking message or it's only your supposition ?

**Comment by Bun01294** [comment]
I didn't see an adblocking message, it was a suppposition then, it only showed a black screen, disabling the ublock removed the issue. I  updated the fliters and removed all the custom fliters to see if it was my own issue. the problem that it didn't work

**Comment by mapx-** [comment]
if you still will get some problem comment here again
