### ISSUE TITLE
bluemediafile.site: detection /ads

### ISSUE THREAD

**Issue by miyakohebi** [uBlockOrigin/uAssets#17056]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bluemediafile.site/url-generator.php?url=onAhF5ZLCDGjfP3AAUIv/b2DJLi0YBRL/g/VlBQbxQR7cMu+fwR5qyWfKTSD77aJz4wVzlVyOfdpYP1NU2RNUKXq0VuWRVgW6AINSzUdGjOYYu0J5FJgpcYlGZ1QARt8`

### Category

detection

### Description

NA

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/38079662/223048136-9609a1cd-3cda-4f16-a7f2-6162e4ed21cc.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 86970
  cosmetic: 46961
  scriptlet: 16871
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 36-13, never
    JPN-1: 9940-5, 13h.40m
    easylist: 63466-54, 13h.48m
    easyprivacy: 31009-1196, 13h.47m
    plowe-0: 3738-930, 12d.17h.2m
    ublock-abuse: 78-0, 13h.45m
    ublock-badware: 4621-115, 13h.39m
    ublock-filters: 31519-162, 13h.42m
    ublock-privacy: 287-1, 13h.44m
    ublock-quick-fixes: 340-13, 13h.34m
    ublock-unbreak: 1908-45, 13h.41m
    urlhaus-1: 6553-0, 13h.33m
filterset (user): [array of 36 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2228 ms (selfie)
  maxAssetCacheWait: 46 ms
popupPanel: 
  blocked: 42
  blockedDetails: 
    bluemediafile.site: 2
    apathylahuli.website: 2
    bookljlihooli.com: 1
    choobinoobi.com: 2
    ctsjackupspete.com: 12
    galeaeevovae.com: 1
    googletagmanager.com: 1
    igg-games.com: 1
    onhadintrepha.info: 11
    pogothere.xyz: 8
    syenitetatler.tech: 1
```
</details>

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17057

**Comment by krystian3w** [comment]
#17058

**Comment by krystian3w** [comment]
Maybe https://github.com/uBlockOrigin/uBlock-issues/issues/2525

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
