### ISSUE TITLE
ziare.com: detection

### ISSUE THREAD

**Issue by vixxtor** [uBlockOrigin/uAssets#17053]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ziare.com/canalul-bistroe/intrat-la-apa-retorica-grindeanu-masuratori-bistroe-ministrul-dat-de-gol-oficiali-1792397`

### Category

detection

### Description

the website started to detect ublock origin recently.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/7295475/222993433-cdd6a1f0-2be8-42ee-81b8-4141b0364d80.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 83781
  cosmetic: 38865
  scriptlet: 17226
  html: 895
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33533-165, never
    ublock-badware: 4471-5, never
    ublock-privacy: 321-0, never
    ublock-abuse: 79-0, never
    ublock-unbreak: 1915-0, never
    ublock-quick-fixes: 305-3, never
    easylist: 62267-655, never
    easyprivacy: 30962-1751, never
    urlhaus-1: 6000-0, never
    plowe-0: 3675-2, never
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 247 ms
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    addthis.com: 1
    doubleclick.net: 1
    etop.ro: 2
    facebook.com: 2
    google.com: 2
    googletagmanager.com: 1
    ineed2s.ro: 1
    newrelic.com: 2
```
</details>

**Comment by mapx-** [comment]
Romanian site, enable `ROU: Romanian Ad (ROad) Block List Light`
