### ISSUE TITLE
Seekingalpha.com anti-adblock

### ISSUE THREAD

**Issue by Oahoahoah** [uBlockOrigin/uAssets#1705]
### URL(s) where the issue occurs

`https://seekingalpha.com/`

### Describe the issue

Anti-adblock pop-up

### Screenshot(s)
![image](https://user-images.githubusercontent.com/37158536/37333183-f640476e-26a8-11e8-9d57-553b8cdb2408.png)

### Versions
- Browser/version: Chrome - 64.0.3282.186 (64-bit)
- uBlock Origin version: 1.15.2

### Settings
Default

### Notes

Have tried Nano-Defender as well, but anti-adblock persists (so far).

**Comment by mapx-** [comment]
I cannot reproduce the issue. 
Did you test using only uBo (default setup) and no other blocking extension ?

**Comment by Oahoahoah** [comment]
I restored to default all settings and went into seekingalpha.com - and
correctly no pop-up re-appeared despite spending some minutes at the site
(and clicking several articles).

But, I was then not logged into the site. I then logged into the site as a
free member, and immediately after logging in the pop-up reappeared. So the
anti-adblock pop-ups might only appear after logging into the site?

I also attach "console" print:

**Comment by mapx-** [comment]
still unable to reproduce (even using an account), let's see if someone else could reproduce it

**Comment by Oahoahoah** [comment]
I gets this screen after a few clicks on articles:
![image](https://user-images.githubusercontent.com/37158536/37335461-e3e6ed4c-26ae-11e8-8844-5c98f1fb5a8b.png)

Console view:
![image](https://user-images.githubusercontent.com/37158536/37335508-03f5fe66-26af-11e8-940b-e8cc54ec68ab.png)

When I log out, I do not get any anti-adblocks again. When logging in and clicking a few articles, I again get the errors. Attached console when the errors reappear:
![image](https://user-images.githubusercontent.com/37158536/37335716-8e862e0c-26af-11e8-901b-a81caf8e3222.png)

**Comment by nimasaj** [comment]
@ Oahoahoah,
try this one:
`@@||seekingalpha.com^$generichide`

**Comment by Oahoahoah** [comment]
Thanks,
no popups have showed up after adding:  @@||seekingalpha.com^$generichide

**Comment by ItsProfessional** [comment]
Site is apparently detecting again. Report: https://www.reddit.com/r/uBlockOrigin/comments/1adzaga/seeking_alpha_anti_adblock_popup/

Can't reproduce, though.

**Comment by liamengland1** [comment]
@ItsProfessional that's not anti-adblock. That's an anti-scraping thing (PerimeterX)

**Comment by stephenhawk8054** [comment]
The anti-bot/anti-scraping is not stable to reproduce. You might need to log in or use the site for a while to trigger it. It's very annoyed for users, and I don't actually agree with EP to block these because I experienced this myself in other sites and very difficult fix since they can affect your IP if they think your IP is used for bots.
