### ISSUE TITLE
nettavisen.no: breakage

### ISSUE THREAD

**Issue by h3xh3xh3x** [uBlockOrigin/uAssets#17052]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nettavisen.no/nyheter/innenriks/redaktor-frikjent-etter-a-ha-navngitt-sexdomt-mann/s/12-95-3423257275`

### Category

breakage

### Description

The article didn't load without disabling/reenabling ad blocking

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 109294
  cosmetic: 133450
  scriptlet: 22458
  html: 908
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 35578-7248, 7h.41m
    adguard-annoyance: 64629-4242, 7h.38m
    fanboy-thirdparty_social: 69-1, 7d.8h.22m
    fanboy-annoyance: 82103-64975, 4d.3h.30m
    fanboy-cookiemonster: 45852-17452, 6d.3m
    NOR-0: 2824-180, 3h.20m
    SWE-1: 4393-312, 7h.37m
  default: 
    user-filters: 221-8, never
    ublock-filters: 32865-269, 7h.39m
    ublock-badware: 4625-0, 7h.40m
    ublock-privacy: 323-1, 10d.20h.32m
    ublock-abuse: 77-0, 13d.5h.14m
    ublock-unbreak: 1924-1, 7h.42m
    easylist: 63152-17504, 4d.19h.40m
    easyprivacy: 31009-1819, 3h.22m
    plowe-0: 3750-2, 2d.19h.19m
    urlhaus-1: 6553-0, 3h.21m
    ublock-quick-fixes: 340-0, 3h.19m
filterset (user): [array of 222 redacted]
trustedset: 
  added: [array of 163 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 23 redacted]
urlRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 765 ms (selfie)
  maxAssetCacheWait: 927 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    acdn.no: 3
    adplogger.no: 1
    api.no: 3
    brandmetrics.com: 1
    de17a.com: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    k5a.io: 1
    opinionstage.com: 1
    rubiconproject.com: 1
    seenthis.se: 13
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
