### ISSUE TITLE
joyn.de: ads

### ISSUE THREAD

**Issue by Alfondorion** [uBlockOrigin/uAssets#17050]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.joyn.de/play/serien/wer-stiehlt-mir-die-show/5-2-wer-stiehlt-helena-die-show`

### Category

ads

### Description

Hast prerolls and midrolls

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 111
filterset (summary): 
  network: 89447
  cosmetic: 69328
  scriptlet: 20403
  html: 1056
listset (total-discarded, last-updated): 
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 25737-4, now
    ublock-annoyances: 4806-4, now
  default: 
    user-filters: 10-0, never
    ublock-filters: 33691-74, now
    ublock-badware: 4625-0, now
    ublock-privacy: 336-0, now
    ublock-abuse: 78-0, now
    ublock-unbreak: 1915-16, now
    easylist: 63430-579, now
    easyprivacy: 31016-1777, now
    urlhaus-1: 6553-0, now
    plowe-0: 3755-2, now
    DEU-0: 6582-2, now
    ublock-quick-fixes: 339-0, now
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 1 redacted]
hostRuleset: 
  removed: 
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 306 ms (selfie)
  maxAssetCacheWait: 192 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    braze.eu: 4
    launchdarkly.com: 2
    sentry.io: 1
    theadex.com: 1
    usercentrics.eu: 3
    vercel-insights.com: 4
    youborafds01.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
Try

```
||hybrid-prd.ad-prd.s.joyn.de^
||event-collector.prd.data.s.joyn.de^
||somquery.sqrt-5041.de/tv/tracking-event
```

**Comment by Alfondorion** [comment]
Thank you, at first glance it works! The pre-rolls are gone.

**Comment by JobcenterTycoon** [comment]
@ryanbr @khrin

Ads:
```
||hybrid-prd.ad-prd.s.joyn.de^
||somquery.sqrt-5041.de/tv/ad-wrapper
```

Tracking:
```
||somquery.sqrt-5041.de/tv/tracking-event
||event-collector.prd.data.s.joyn.de^
```

**Comment by Remus76** [comment]
Video player is broken for some days, only audio is playing as long as the filter
`||hybrid-prd.ad-prd.s.joyn.de^`
is applied. However if you counter that filter you get ads at the beginning of each video.
Example URL (needs site account): https://www.joyn.de/play/serien/detektiv-conan/1-280-grusellegende-von-einer-winternacht-1

**Comment by mapx-** [comment]
No issue on my end (using a german ip) => I didn't find that filter in the logger
`||hybrid-prd.ad-prd.s.joyn.de^`

**Comment by Remus76** [comment]
I use Firefox 114.0.2 (Windows 10/11) with uBO 1.50.0 and EasyList Germany enabled by default.
I wont be able to test further or comment until tomorrow afternoon.

**Comment by JobcenterTycoon** [comment]
Works also fine for me on Firefox and i also don’t see `hybrid-prd.ad-prd.s.joyn.de` in the logger.

Be sure the `uBlock filters – Ads` filterlist is enabled.

**Comment by Remus76** [comment]
I just tested another video on a new profile in Google Chrome while being logged in and it does not show the video, just audio is playing. The video is selected via a link from
`https://www.joyn.de/serien/detektiv-conan`
where you can select a video and wait for autoplay.
I can reproduce every time even on two different machines and have that entry in the logger:

https://github.com/uBlockOrigin/uAssets/assets/75799128/82ca4e49-a0ca-42c3-a8c7-3df9298edebb

When I create an exception filter or disable EasyList Germany the video is playing after showing about 3 ads.

**Comment by JobcenterTycoon** [comment]
@Yuki2718 can you reproduce?

**Comment by Remus76** [comment]
Me and someone else were able to do so. I did some testing today and applying the following filter solved the issue for both of us:
`||sqrt-5041.de^$xhr,domain=joyn.de`
So I no longer have any problems. Now the player works fine (and of course also without ads).

**Comment by JobcenterTycoon** [comment]
Got added https://github.com/uBlockOrigin/uAssets/commit/1293f79a1cfeba8905fa33b58286fdef02008ac1 from the issue https://github.com/uBlockOrigin/uAssets/issues/18684

**Comment by ghost** [comment]
Got a cookie notice on the page.

### Browser name and version

Google Chrome
Version 141.0.7390.76

### Other extensions used

- Bitwarden
- LanguageTool
- Gumbo
- SponsorBlock
- Tampermonkey (no scripts on this site)
- YouTube No Translation
- YouTube Row Fixer

### Country

Germany

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>




<img width="2543" height="1290" alt="Image" src="https://github.com/user-attachments/assets/c6fcc076-1442-4748-b75d-db5cfa4ca7cc" />



</details>


### Configuration

```yaml
name: uBlock Origin Lite
version: 2025.1002.1210
browser: Chrome 141 (linux)
filtering:
 site: complete
 default: complete
rulesets:
 +adguard-spyware-url
 +annoyances-cookies
 +annoyances-notifications
 +annoyances-others
 +annoyances-overlays
 +annoyances-social
 +annoyances-widgets
 +block-lan
 deu-0
 easylist
 easyprivacy
 pgl
 ublock-badware
 ublock-filters
 urlhaus-full
```
