### ISSUE TITLE
regex record under trusted site not working

### ISSUE THREAD

**Issue by bboysnick5** [uBlockOrigin/uAssets#17059]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

My goal is to whitelist any static sites like gstatic.com when 3p dynamic filtering is in play. Below regex does the job when putting into trusted site. However it's not working when 3p dynamic filtering is in use. 

 /^([a-zA-Z0-9]+\.)?[a-zA-Z0-9]+static\.[a-zA-Z0-9]+$/

### URL(s) where the issue occurs.

 /^([a-zA-Z0-9]+\.)?[a-zA-Z0-9]+static\.[a-zA-Z0-9]+$/

### uBO version

latest

### Browser name and version

chrome 110

### Settings

trusted site
hard mode

**Comment by Yuki2718** [comment]
Issues is for issues, do not burden volunteers for your personal question.
