### ISSUE TITLE
ipcimeeting.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#17068]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ipcimeeting.com/`

### Category

ads

### Description

![image](https://user-images.githubusercontent.com/19517680/223285403-4d79564e-1bbd-4b06-ae87-63343a8d945c.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 112
filterset (summary): 
  network: 112640
  cosmetic: 139683
  scriptlet: 24531
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7902-2, 1d.17h.13m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-4, 1d.17h.12m
    IDN-0: 5458-353, 1d.17h.14m
    RUS-0: 39468-52, 1d.17h.5m
    fanboy-annoyance: 82102-412, 5d.18h.43m
    fanboy-cookiemonster: 45869-45869, 5d.18h.43m
    ublock-annoyances: 4844-83, 1d.17h.10m
  default: 
    user-filters: 29-0, never
    easylist: 63212-72, 5d.18h.43m
    easyprivacy: 30996-1281, 5d.18h.43m
    ublock-abuse: 78-1, 1d.17h.11m
    ublock-badware: 4611-113, 1d.17h.9m
    ublock-filters: 32039-408, 1d.17h.8m
    ublock-privacy: 287-7, 1d.17h.7m
    ublock-quick-fixes: 348-19, 2m
    ublock-unbreak: 1904-59, 1d.17h.6m
    urlhaus-1: 6481-0, 3m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 36 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13528 ms (selfie)
  maxAssetCacheWait: 1667 ms
popupPanel: 
  blocked: 67
  blockedDetails: 
    ads-twitter.com: 1
    d2ry9vue95px0b.cloudfront.net: 61
    d39ion77s0ucuz.cloudfront.net: 3
    googletagmanager.com: 1
    marketo.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||d2ry9vue95px0b.cloudfront.net^$script,image,css,domain=ipcimeeting.com
@@||d39ion77s0ucuz.cloudfront.net^$script,image,domain=ipcimeeting.com
```
@ryanbr
