### ISSUE TITLE
click.discord.com: breakage

### ISSUE THREAD

**Issue by leecheeyong** [uBlockOrigin/uAssets#17061]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

It seems like Peter Lowe's tracking list included the `click.discord.com` sub domain which was used for Discord Email Verification.

### URL(s) where the issue occurs.

`https://click.discord.com`

### Screenshot(s)

<img width="1301" alt="Screenshot 2023-03-06 at 10 03 01 PM" src="https://user-images.githubusercontent.com/81070048/223135141-d8a5dfdc-6177-4191-a93e-79bb34599663.png">

### uBO version

1.47.2

### Browser name and version

Firefox 110.0.1

### Settings

Not sure if Peter Lowe's tracking list is enabled by default, if not, I've enabled that.

**Comment by Yuki2718** [comment]
@pgl

**Comment by pgl** [comment]
@leecheeyong `click.discord.com` is a tracker. It tracks your clicks. If you're OK with that, you can add an exclusion.

**Comment by leecheeyong** [comment]
alright, noted with thanks

**Comment by MacStevins** [comment]
is it not the one that you use to verify a login to discord? i have 2 emails of the same link which came from discord directly and not from a scam site

**Comment by iam-py-test** [comment]
It **isn't** a scam site. It is a click tracker, hence why it it blocked. You can unblock it on the uBo block page, or add this to "my filters":
```adblock
||click.discord.com^$badfilter
```
