### ISSUE TITLE
fcpeuro.com: breakage

### ISSUE THREAD

**Issue by obiwantoby** [uBlockOrigin/uAssets#17062]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fcpeuro.com/products/mercedes-hvac-blower-motor-resistor-2308216451`

### Category

breakage

### Description

If I click "Email Me When Available", the subsequent dialog that accepts the email and 'submit' button will not function. The submit button fails. If I disabled my default installation of Ublock Origin, the email button works.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1486238/223154978-65702dd7-f8c9-45ab-a9d7-34b4d0b3f366.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 85311
  cosmetic: 38972
  scriptlet: 17046
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63345-47, 1d.15h.11m
    easyprivacy: 31011-1172, 1d.15h.10m
    plowe-0: 3750-928, 4d.15h.31m
    ublock-abuse: 79-0, 7d.17h.23m
    ublock-badware: 4611-114, 2d.7h.16m
    ublock-filters: 32033-67, 2d.7h.15m
    ublock-privacy: 260-1, 7d.17h.22m
    ublock-quick-fixes: 340-19, 23h.58m
    ublock-unbreak: 1922-57, 2d.7h.14m
    urlhaus-1: 6553-0, 23h.57m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3748 ms (selfie)
  maxAssetCacheWait: 69 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    bing.com: 1
    bluecore.com: 1
    facebook.com: 2
    google-analytics.com: 1
    googletagmanager.com: 2
    stackadapt.com: 1
    typekit.net: 1
```
</details>

**Comment by okiehsch** [comment]
`@@||api.bluecore.com/triggermail.js/fcpeuro.js$script,domain=fcpeuro.com`

@ryanbr
