### ISSUE TITLE
imgur.com: [privacy]

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17067]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://imgur.com/`

### Category

[unknown]

### Description

`xeno-soswcrde4a-uc.a.run.app/events` is a 3p xhr tracking url? Not seen in imgur until `2023-03-01 14:48:24 UTC` and blocking it does not affect functionality.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/91396482/223282389-167ae330-3417-4ff8-9f5a-900ba49b2ad1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 110
filterset (summary): 
  network: 76971
  cosmetic: 40682
  scriptlet: 17355
  html: 905
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1437-0, 6h.52m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 2d.10h.5m
  default: 
    user-filters: 1562-13, never
    ublock-filters: 33662-68, 2d.8h.17m
    ublock-badware: 4615-0, 2d.10h.6m
    ublock-privacy: 336-0, 2d.10h.6m
    ublock-abuse: 78-0, 2d.10h.5m
    ublock-unbreak: 1917-16, 2d.10h.5m
    ublock-quick-fixes: 346-0, 6h.53m
    easylist: 63435-228, 2d.10h.5m
    easyprivacy: 31011-2126, 2d.10h.5m
filterset (user): [array of 590 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 434 ms (selfie)
  maxAssetCacheWait: 263 ms
  unsuspendAfter: 124 ms
popupPanel: 
  blocked: 33
  blockedDetails: 
    imgur.com: 4
    alexametrics.com: 2
    amazon-adsystem.com: 1
    assemblyexchange.com: 12
    btloader.com: 2
    consensu.org: 1
    d3c8j8snkzfr1n.cloudfront.net: 1
    facebook.net: 1
    google-analytics.com: 1
    media-lab.ai: 1
    quantserve.com: 2
    sascdn.com: 2
    scorecardresearch.com: 1
    stretchsquirrel.com: 1
    xeno-soswcrde4a-uc.a.run.app: 1
```
</details>

**Comment by Daxy7** [comment]
There's three related filters in EasyPrivacy for `run.app`, to add it shortened

```
||run.app/data.log
||run.app/metrics/
||run.app/events
```

**Comment by stephenhawk8054** [comment]
```adb
||run.app/data.log
||run.app/metrics/
```

I don't see these connections when loading the site. Does it need an account?

**Comment by Daxy7** [comment]
I mean to insert in this bit of the EP list
https://user-images.githubusercontent.com/91396482/223301934-d63e1678-dd06-45bf-809f-d836f25c5633.png

**Comment by Daxy7** [comment]
new ep filters arent showing up
tested in firefox and chromium
https://user-images.githubusercontent.com/91396482/223328255-f72476fc-296b-48e0-bb54-e52df1d9add1.png

**Comment by stephenhawk8054** [comment]
You'll need to wait a bit for EL/EP lists

**Comment by sebr** [comment]
This is an incorrect rule to apply - `run.app` is Google's hosted cloud domain and adding this domain will break any app which has an `/events` path.

see #17254
