### ISSUE TITLE
anilibria.tv: popups

### ISSUE THREAD

**Issue by Tomazzzzz** [uBlockOrigin/uAssets#17064]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.anilibria.tv/release/isekai-ojisan.html`

### Category

popups

### Description

pop ups windows with game warships

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 85334
  cosmetic: 38976
  scriptlet: 17034
  html: 890
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32855-57, 2d.2h.20m
    ublock-badware: 4615-0, 2d.2h.19m
    ublock-privacy: 323-0, 8d.20h.24m
    ublock-abuse: 79-0, 8d.20h.23m
    ublock-unbreak: 1915-16, 2d.2h.18m
    easylist: 63345-548, 1d.18h.17m
    easyprivacy: 31009-1782, 1d.6h.33m
    urlhaus-1: 6575-0, 3h.34m
    plowe-0: 3749-2, 8d.26m
    ublock-quick-fixes: 346-0, 3h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 618 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    digitalcaramel.com: 2
    googletagmanager.com: 1
    jsdelivr.net: 2
    yandex.ru: 4
```
</details>

**Comment by dimisa-RUAdList** [comment]
This is a russian website. The rules for it are contained in the RUS: RU AdList.
