### ISSUE TITLE
Ublock Origin not blocking Hulu or Disney Plus ads

### ISSUE THREAD

**Issue by IndomitusX** [uBlockOrigin/uAssets#17066]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I've never had a problem with uBlock Origin before today. It used to block Hulu ads just fine (I never tried it with Disney Plus before). It still blocks YouTube ads but not Hulu or Disney Plus. I saw someone resolved this issue like 4 days ago but it didn't make any sense to me and was resolved with them handing over sensitive account information. Is there a way to resolve this issue without that? That's not an option for me.

### A specific URL where the issue occurs.

`https://www.disneyplus.com/video/81361203-cc00-49dd-b60f-8b9203d165d3`

### Steps to Reproduce

1. Login to Disney Plus
2. Start watching the first episode of Andor
3. See if you have ads

### Expected behavior

Not to have ads

### Actual behavior

There were ads

### uBO version

1.47.4

### Browser name and version

Chrome Version 110.0.5481.178 (Official Build) (64-bit) 

### Operating System and version

Windows 10 19044.2604

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).

This is a filter list's issue, therefore it's invalid in https://github.com/uBlockOrigin/uBlock-issues
