### ISSUE TITLE
[nsfw] eatcells.com: popups

### ISSUE THREAD

**Issue by khaledbzk** [uBlockOrigin/uAssets#17069]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://eatcells.com/land/?token=jgktevr6n9rkvl216g7l`

### Category

popups

### Description

popups

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 105374
  cosmetic: 47723
  scriptlet: 17143
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    FRA-0: 30040-34, 4d.1h.24m
    easylist: 63521-229, 3h.54m
    easyprivacy: 31014-1492, 1d.55m
    plowe-0: 3750-954, 5d.10h.48m
    ublock-abuse: 79-1, 8d.23h.41m
    ublock-badware: 4607-133, 4d.1h.25m
    ublock-filters: 31984-167, 4d.1h.26m
    ublock-privacy: 276-1, 8d.2h.7m
    ublock-quick-fixes: 347-16, 9h.46m
    ublock-unbreak: 1932-62, 4d.1h.23m
    urlhaus-1: 6481-0, 9h.47m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3941 ms (selfie)
  maxAssetCacheWait: 430 ms
popupPanel: 
  blocked: 1
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    addthis.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
`https://eatcells.com/land/?token=jgktevr6n9rkvl216g7l`

Is it the site that the popups lead to? Can you give original link?

**Comment by PotapovaIrina87** [comment]
https:// api.monsterinsights.com /v2/auth/new/lite/?tt=cf90e1aafb9ff5ccef2d1f27151a0929c6e747f6c520a1a22c18e4d7f50d075800519f4dc7aedb753090dbf601faa990939b1b93da57461a576b878a132ddc43&sitei=WBmbj17tuGeJcU6ZaP87mFLuP7MjHI&miversion=8.14.1&ajaxurl=https://****.ru/wp-admin/admin-ajax.php&network=site&siteurl=https://****.ru&return=https://****.ru/wp-admin/admin.php?page=monsterinsights_settings&testurl=https://api.monsterinsights.com/v2/
