### ISSUE TITLE
vod.afreecatv.com: breakage

### ISSUE THREAD

**Issue by Taris9047** [uBlockOrigin/uAssets#17063]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vod.afreecatv.com/player/99227031`

### Category

breakage

### Description

This is a video streaming service. The video includes advertisement just like YouTube. But Ublock prevents both Ad and video to play.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 85261
  cosmetic: 38961
  scriptlet: 17047
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63278-47, 3d.20h.26m
    easyprivacy: 31003-1172, 3d.20h.25m
    plowe-0: 3749-928, 9d.22h.42m
    ublock-abuse: 78-0, 1d.18h.4m
    ublock-badware: 4611-114, 1d.18h.7m
    ublock-filters: 32037-67, 1d.18h.6m
    ublock-privacy: 287-1, 1d.18h.3m
    ublock-quick-fixes: 341-19, 17h.55m
    ublock-unbreak: 1904-54, 1d.18h.5m
    urlhaus-1: 6553-0, 17h.54m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2974 ms (selfie)
  maxAssetCacheWait: 276 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    afreecatv.com: 1
    google.com: 1
    imasdk.googleapis.com: 1
```
</details>

**Comment by prech** [comment]
> @@||afreecatv.com/api/$xhr,1p
> @@||afreecatv.com^$script,1p
> @@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=vod.afreecatv.com

Thank you so much, this fixed it!

**Comment by mapx-** [comment]
@piquark6046 did you fix the issue ? what adv request ? give all the details

**Comment by piquark6046** [comment]
I can play the player with a real Korean IP address and non-Korean IP address even if I disable them by adding the following filters:
```adblock
@@||afreecatv.com/api/$xhr,1p,badfilter
@@||afreecatv.com^$script,1p,badfilter
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=vod.afreecatv.com,badfilter
```

**Comment by mapx-** [comment]
The video is blocked on my side even adding only the last badfilter one

**Comment by piquark6046** [comment]
To reproduce, can you provide your environment?

**Comment by mapx-** [comment]
default setup, chrome

**Comment by piquark6046** [comment]
On my side, the issue can not be reproduced.
However, I added it into List-KR filter list.
