### ISSUE TITLE
Adblock detected - https://xerifetech.com/

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#17076]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Adblocker is detected when enabled and even when it's disabled.

### URL(s) where the issue occurs.

`https://xerifetech.com/`

### uBO version

1.47.4

### Browser name and version

Waterfox

### Settings

Added fanboy's annoyances list.

**Comment by Felipefpl** [comment]
@mapx- Thanks for fixing the issue but it seems the adblocker itself has a problem because even disabled the site is still blocked.

**Comment by mapx-** [comment]
Tested in waterfox too, all fine.

It's something on your side:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Felipefpl** [comment]
Thanks for the (lengthy) explanation, surely wasnt easy to write all of this. :+1:

**Comment by stephenhawk8054** [comment]
If the problem still persists after you disable ublock, it is caused by something else on your machine.
