### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by katamari1992** [uBlockOrigin/uAssets#17075]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Description

Started showing up a few days ago

layout="display-ad-layout-top-landscape-image"><div id="fulfilled-layout" class="style-scope ytd-ad-slot-renderer"><ytd-in-feed-ad-layout-renderer class="style-scope ytd-ad-slot-renderer"><div id="rendering-content" class="style-scope ytd-in-feed-ad-layout-renderer"><ytd-display-ad-renderer class="style-scope ytd-in-feed-ad-layout-renderer" rounded="" standardize-icon-size="" hide-endpoint-overflow="" layout="display-ad-layout-top-landscape-image" style="--ytd-display-ad-media-background-image: url(https://lh4.googleusercontent.com/proxy/5X70UEPC-qFTFuHmezR4EIAh4YqCIF9RwRFNECjUR-g6qqcoBPy2kpt96_RtJhQg49w3COMV5N7nIcC5Fx1p2Wr224VeMfpkbDcoJPhlsaUQ7CoRk3n2zMf1iCNQAmzyy2g=w128-h67-s-nd);"><div id="dismissible" class="style-scope ytd-display-ad-renderer">
  <div id="root" class="style-scope ytd-display-ad-renderer yt-simple-endpoint">
    <div id="media-container" aria-hidden="true" class="style-scope ytd-display-ad-renderer">
      <div id="media-background" class="style-scope ytd-display-ad-renderer">
      </div>
      <div id="media" class="style-scope ytd-display-ad-renderer">
      <yt-img-shadow class="style-scope ytd-display-ad-renderer no-transition" style="background-color: transparent;" fit-height="" object-fit="CONTAIN" loaded=""><img id="img" draggable="false" class="style-scope yt-img-shadow" alt="" src="https://lh4.googleusercontent.com/proxy/5X70UEPC-qFTFuHmezR4EIAh4YqCIF9RwRFNECjUR-g6qqcoBPy2kpt96_RtJhQg49w3COMV5N7nIcC5Fx1p2Wr224VeMfpkbDcoJPhlsaUQ7CoRk3n2zMf1iCNQAmzyy2g=w1152-h603-s-nd"></yt-img-shadow></div>
      <div id="media-badge" class="style-scope ytd-display-ad-renderer">
      <ytd-badge-supported-renderer class="style-scope ytd-display-ad-renderer" system-icons=""><div class="badge badge-style-type-black style-scope ytd-badge-supported-renderer"><yt-icon size="16" class="style-scope ytd-badge-supported-renderer"><svg viewBox="0 0 16 16" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon"><path d="M13,10h1v4H2V2h4v1H3v10h10V10z M8,3h4.29L6.15,9.15l0.71,0.71L13,3.71V8h1V2H8V3z" class="style-scope yt-icon"></path></g></svg></yt-icon><span class="style-scope ytd-badge-supported-renderer"></span></div><dom-repeat id="repeat" as="badge" class="style-scope ytd-badge-supported-renderer"><template is="dom-repeat"></template></dom-repeat></ytd-badge-supported-renderer></div>
      <div id="media-hover-overlay" class="style-scope ytd-display-ad-renderer">
      <ytd-button-renderer class="style-scope ytd-display-ad-renderer" button-renderer=""><yt-button-shape><button class="yt-spec-button-shape-next yt-spec-button-shape-next--text yt-spec-button-shape-next--overlay yt-spec-button-shape-next--size-m yt-spec-button-shape-next--icon-trailing " style="" aria-label="Visit site"><div class="cbox yt-spec-button-shape-next--button-text-content"><span class="yt-core-attributed-string yt-core-attributed-string--white-space-no-wrap" role="text">Visit site</span></div><div class="yt-spec-button-shape-next__icon"><yt-icon style="width: 24px; height: 24px;"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon"><path d="M21,21H3V3h9v1H4v16h16v-8h1V21z M15,3v1h4.32l-8.03,8.03L12,12.74l8-8V9h1V3H15z" class="style-scope yt-icon"></path></g></svg></yt-icon></div><yt-touch-feedback-shape style="border-radius: inherit;"><div class="yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--overlay-touch-response" aria-hidden="true"><div class="yt-spec-touch-feedback-shape__stroke" style=""></div><div class="yt-spec-touch-feedback-shape__fill" style=""></div></div></yt-touch-feedback-shape></button></yt-button-shape><tp-yt-paper-tooltip fit-to-visible-bounds="" offset="8" disable-upgrade=""></tp-yt-paper-tooltip></ytd-button-renderer></div>
    </div>
    <div class="title style-scope ytd-display-ad-renderer">
      <a class="yt-display-ad-renderer-endpoint title-link style-scope ytd-display-ad-renderer" aria-label="Ad: Find Single Ukrainian Ladies." href="https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=C5nyB1gMHZJmYH6bIp84Pm5GLkAbXkqKRb9Xk0reJEWQQAyAAYMme14vEpPwPggEXY2EtcHViLTYyMTk4MTE3NDcwNDkzNzGgAer0mbEoqAMEyAMKqgTAAU_QRCfpSJyNCbvBpD1RwhUZADi7thyHXuERz8yPHSi3SYu9Gh14QrM1oXOycsCLbHjGhdaxPMWKw9C6eiBpXSBBnEcJvBwUJfW8cMZjlKdW08aMyRoF-2WXRKTYkdADisf_6lnt-qQbEIRQGAFPJTz1J7sk3nzL1GqVuUVewPPCi3SKe6VpLu2ProRNP5eyrFvIYxwrArYGHT8hPU2PwE0ImuLUGffx1Mxr2Sy4LMgo5SUOMl4RjH4-CG_pCEm5e5IFCggTaAF4vpSbkwOgBm6AB-qs6pADiAcBkAcCqAeCqrECqAeECKgHqNIbqAe2B6gH4M8bqAfp1BuoB4zNG6gHsdwbqAekmrECqAeRn7ECqAewm7ECqAffobECqAemqrECqAeBxhuoB6vFG6gH5p2xAqgHyJ-xAqgHt6GxAtIIGAiAwIBAEAIYWjIEgYKADjoHg9CAgICABLEJMZwXv8dg1l7ICQCYCwG6C0EIAhAFGBYgCCgBMANAAUgAUAFYJWAAaABwAYgBAJgBAaIBFQoECAEgAvgBAZACAqgCBcACAtACAdgBAYACAYgCBtALErgMAZoNARK4E____________wGwFALAFYGAgEDQFQHYFQHiFgIIAYAXAYoXEggDEAoYASgBMAE4AUgBUAFYAaAXAakX3DpsZo2l7wk&amp;num=3&amp;cid=CAESD-D2f3dCqczPbZPicJPWiQ&amp;sig=AOD64_3eTFWfQqqefDV_Fea_zudB2RfIOQ&amp;adurl=https://myspecialdates.com/lnd43%3Futm_mar%3Dnik%26utm_netw%3Dmyspec_ggl_nik%26utm_campn%3Dgdn2%26utm_dev%3Dc%26utm_camp%3D17344555919%26utm_device_type%3D&amp;ms=[CLICK_MS]&amp;nb=[NB]&amp;nx=[NX]&amp;ny=[NY]&amp;dim=[DIM]">
        <yt-formatted-string class="title-text style-scope ytd-display-ad-renderer" title="Find Single Ukrainian Ladies">Find Single Ukrainian Ladies</yt-formatted-string>
      </a>
      <div id="menu" class="style-scope ytd-display-ad-renderer"><ytd-menu-renderer class="style-scope ytd-display-ad-renderer"><div id="top-level-buttons-computed" class="top-level-buttons style-scope ytd-menu-renderer"></div><div id="flexible-item-buttons" class="style-scope ytd-menu-renderer"></div><yt-icon-button id="button" class="dropdown-trigger style-scope ytd-menu-renderer" style-target="button"><button id="button" class="style-scope yt-icon-button" aria-label="Action menu"><yt-icon class="style-scope ytd-menu-renderer"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon"><path d="M12,16.5c0.83,0,1.5,0.67,1.5,1.5s-0.67,1.5-1.5,1.5s-1.5-0.67-1.5-1.5S11.17,16.5,12,16.5z M10.5,12 c0,0.83,0.67,1.5,1.5,1.5s1.5-0.67,1.5-1.5s-0.67-1.5-1.5-1.5S10.5,11.17,10.5,12z M10.5,6c0,0.83,0.67,1.5,1.5,1.5 s1.5-0.67,1.5-1.5S12.83,4.5,12,4.5S10.5,5.17,10.5,6z" class="style-scope yt-icon"></path></g></svg></yt-icon></button><yt-interaction id="interaction" class="circular style-scope yt-icon-button"><div class="stroke style-scope yt-interaction"></div><div class="fill style-scope yt-interaction"></div></yt-interaction></yt-icon-button><yt-button-shape id="button-shape" version="modern" class="style-scope ytd-menu-renderer" disable-upgrade="" hidden=""></yt-button-shape></ytd-menu-renderer></div>
    </div>
    <div id="support" class="style-scope ytd-display-ad-renderer">
      <yt-formatted-string id="body-text" class="style-scope ytd-display-ad-renderer" title="Meet Slavic Gorgeous Singles Seeking Love Online.">Meet Slavic Gorgeous Singles Seeking Love Online.</yt-formatted-string>
      <div id="badge" class="badge style-scope ytd-display-ad-renderer"><ytd-badge-supported-renderer class="style-scope ytd-display-ad-renderer" system-icons="" medium-font-ad-badge=""><div class="badge badge-style-type-ad style-scope ytd-badge-supported-renderer"><yt-icon size="16" class="style-scope ytd-badge-supported-renderer" disable-upgrade="" hidden=""></yt-icon><span class="style-scope ytd-badge-supported-renderer">Ad</span></div><dom-repeat id="repeat" as="badge" class="style-scope ytd-badge-supported-renderer"><template is="dom-repeat"></template></dom-repeat></ytd-badge-supported-renderer></div>
      <yt-formatted-string id="secondary-text" class="style-scope ytd-display-ad-renderer" title="My Special Dates">My Special Dates</yt-formatted-string>
      <span id="rating" class="style-scope ytd-display-ad-renderer" hidden=""></span>
      <yt-icon id="icon" default-to-filled="true" class="style-scope ytd-display-ad-renderer" hidden=""><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon"><path d="M12,17.27L18.18,21l-1.64-7.03L22,9.24l-7.19-0.61L12,2L9.19,8.63L2,9.24l5.46,4.73L5.82,21L12,17.27z" class="style-scope yt-icon"></path></g></svg></yt-icon>
      <yt-formatted-string id="price" class="style-scope ytd-display-ad-renderer" is-empty="" hidden=""></yt-formatted-string>
    </div>
    <div id="call-to-action" class="style-scope ytd-display-ad-renderer"><ytd-button-renderer class="style-scope ytd-display-ad-renderer" button-renderer=""><yt-button-shape><button class="yt-spec-button-shape-next yt-spec-button-shape-next--filled yt-spec-button-shape-next--call-to-action yt-spec-button-shape-next--size-m yt-spec-button-shape-next--icon-trailing " style="" aria-label="Visit site"><div class="cbox yt-spec-button-shape-next--button-text-content"><span class="yt-core-attributed-string yt-core-attributed-string--white-space-no-wrap" role="text">Visit site</span></div><div class="yt-spec-button-shape-next__icon"><yt-icon style="width: 24px; height: 24px;"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" focusable="false" style="pointer-events: none; display: block; width: 100%; height: 100%;" class="style-scope yt-icon"><g class="style-scope yt-icon"><path d="M21,21H3V3h9v1H4v16h16v-8h1V21z M15,3v1h4.32l-8.03,8.03L12,12.74l8-8V9h1V3H15z" class="style-scope yt-icon"></path></g></svg></yt-icon></div><yt-touch-feedback-shape style="border-radius: inherit;"><div class="yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--touch-response-inverse" aria-hidden="true"><div class="yt-spec-touch-feedback-shape__stroke" style=""></div><div class="yt-spec-touch-feedback-shape__fill" style=""></div></div></yt-touch-feedback-shape></button></yt-button-shape><tp-yt-paper-tooltip fit-to-visible-bounds="" offset="8" disable-upgrade=""></tp-yt-paper-tooltip></ytd-button-renderer></div>
  </div>
</div>
<div id="dismissed" class="style-scope ytd-display-ad-renderer">
  <div id="dismissed-content" class="style-scope ytd-display-ad-renderer"></div>
</div>
</ytd-display-ad-renderer></div>
</ytd-in-feed-ad-layout-renderer></div>
</ytd-ad-slot-renderer></div>
</ytd-rich-item-renderer>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Screenshot from 2023-03-07 08-18-34](https://user-images.githubusercontent.com/4704308/223434010-ddb9fde6-294c-4ddf-8d91-20b6ed731e98.png)
![Screenshot from 2023-03-07 08-18-47](https://user-images.githubusercontent.com/4704308/223434013-8107e487-ab72-4eb1-828d-1cb217fe1344.png)
https://imgur.com/a/KXu6CUL

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 85376
  cosmetic: 39017
  scriptlet: 17043
  html: 893
listset (total-discarded, last-updated): 
  default: 
    user-filters: 25-1, never
    ublock-filters: 32865-57, 2d.1h.16m
    ublock-badware: 4615-0, 2d.1h.14m
    ublock-privacy: 333-0, 6d.8h.13m
    ublock-abuse: 79-0, 6d.8h.12m
    ublock-unbreak: 1933-16, 2d.1h.13m
    ublock-quick-fixes: 346-0, 17h.54m
    easylist: 63466-563, 5h.52m
    easyprivacy: 31015-1769, 5h.51m
    urlhaus-1: 6481-0, 17h.53m
    plowe-0: 3751-2, 4d.4h.8m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 895 ms (selfie)
  maxAssetCacheWait: 739 ms
popupPanel: 
  blocked: 388
  no-cosmetic-filtering: true
  blockedDetails: 
    youtube.com: 86
    doubleclick.net: 4
    google.com: 281
    googleusercontent.com: 17
```
</details>

**Comment by krystian3w** [comment]
SCAM - NSFW:

```
https[:]//myspecialdates[.]com/lnd43/block1?utm_unik=true&utm_mar=nik&utm_netw=myspec_ggl_nik&utm_campn=gdn2&utm_dev=c&utm_camp=17344555919&utm_device_type&utm_country=PL
```

**Comment by krystian3w** [comment]
#7636

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by iam-py-test** [comment]
@mapx- please remove spam link
