### ISSUE TITLE
mail.ru: breakage

### ISSUE THREAD

**Issue by TeitokuPOI** [uBlockOrigin/uAssets#17074]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mail.ru/`

### Category

breakage

### Description

Добрый день.
При включенном фильтре (Регионы, языки RUS: RU AdList) не работает смена почты, при нажатии ничего не происходит, при отключении этого фильтра смена работает.
Во вложении скрин места где не работает смена и лог.

Good afternoon.
When the filter is enabled (Regions, languages RUS: RU AdList), the mail change does not work, nothing happens when you click it, when this filter is turned off, the change works.
Attached is a screenshot of the place where the shift and the log do not work.
![Снимок](https://user-images.githubusercontent.com/127194179/223380456-88840115-2100-4f64-a27f-52f5865590bf.PNG)
[лог.txt](https://github.com/uBlockOrigin/uAssets/files/10907856/default.txt)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 108
filterset (summary): 
  network: 102565
  cosmetic: 60221
  scriptlet: 18592
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39472-171, never
    easylist: 63372-534, never
    easyprivacy: 31007-1147, never
    plowe-0: 3751-590, never
    ublock-abuse: 78-0, never
    ublock-badware: 4611-0, never
    ublock-filters: 32807-86, never
    ublock-privacy: 287-0, never
    ublock-quick-fixes: 340-0, never
    ublock-unbreak: 1922-49, never
    urlhaus-1: 6492-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1640 ms
  maxAssetCacheWait: 11 ms
popupPanel: 
  blocked: 106
  blockedDetails: 
    mail.ru: 81
    imgsmail.ru: 14
    mradx.net: 1
    tns-counter.ru: 2
    yadro.ru: 1
    yandex.ru: 7
```
</details>

**Comment by dportvine** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
It's better to discuss it here: https://forums.lanik.us/viewtopic.php?t=39655-mail-ru

Or here: https://github.com/easylist/ruadlist/issues/new
