### ISSUE TITLE
maxstream.video: detection

### ISSUE THREAD

**Issue by Zaword** [uBlockOrigin/uAssets#17070]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://maxstream.video/nzmokf8476ex/V1RyWG1Qem1ZWFk2WHpJTUpKYmx1dz09`

### Category

detection

### Description

The website is a video hosting, it detects ublock and show a warning with a browser message after 5-10 seconds, then it hides the player and breaks the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/43016094/223309798-febb33e1-7c76-4e47-8a97-5df698733cd7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 98472
  cosmetic: 121057
  scriptlet: 22470
  html: 0
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 81845-370, 52m
    fanboy-cookiemonster: 45955-45955, 52m
    ublock-annoyances: 4845-74, 52m
  default: 
    user-filters: 0-0, never
    ITA-0: 13473-0, 53m
    easylist: 63521-50, 52m
    easyprivacy: 31015-1173, 52m
    plowe-0: 3755-930, 52m
    ublock-abuse: 78-0, 52m
    ublock-badware: 4640-114, 52m
    ublock-filters: 32864-102, 52m
    ublock-privacy: 289-8, 52m
    ublock-quick-fixes: 348-22, 52m
    ublock-unbreak: 1905-60, 52m
    urlhaus-1: 6503-0, 52m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4397 ms (selfie)
  maxAssetCacheWait: 494 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    biteneverthelessnan.com: 2
    googletagmanager.com: 1
    host-cdn.net: 1
    intellipopup.com: 1
```
</details>

**Comment by Daxy7** [comment]
Works for me

What do you see being blocked when you go to uBlock's logger -> filter logger content -> by blocked?

https://user-images.githubusercontent.com/91396482/223313406-ce61553b-26b0-448a-917f-1788724a4c2c.png

I notice there's this in the page source, maybe it's random

```
<div id="efefef" display: none;>
<center>Disable your adblock please.</center>

<center><h2>Problems?!? Try to disable adblock.</h2></center>

<script data-cfasync='false' type='text/javascript' src='[//maxstream.video/js/antiadblock0.js]'></script>
<script data-cfasync='false' type='text/javascript' src='[//maxstream.video/js/antiadblock1_check.js]'></script>
<script data-cfasync='false' type='text/javascript' src='[//maxstream.video/js/antiadblock2.js]'></script>
<div id="adv">
 
	if(rfrfrfef!=true)
		{
		$('#t5t5t5').fadeOut();
		document.body.style.overflow = 'hidden';
		  console.log(" not true ");
	}
	else
	{
	$('#dvdvdv').fadeIn();
console.log("ok var ");
		}	
 
 setTimeout(function(){ 
if ($("#adv").height() > 8) {
  console.log("ok...");
     		$('#t3t3t3').fadeIn();
} 
else {
  		$('#t5t5t5').fadeOut();
}
}, 2000);
```

**Comment by Zaword** [comment]
![image](https://user-images.githubusercontent.com/43016094/223323434-5ca659e9-800f-474e-9870-ed8aa78d62d3.png)

This is what I have in filter logger -> blocked

**Comment by Daxy7** [comment]
Does it happen in private browsing? if not, clear cookies for that site

**Comment by Zaword** [comment]
> 

I've tried in this moment, it does happen even in private browsing

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by garry-ut99** [comment]
When I visited the link OP provided:
- on Firefox I've been blocked by EasyList: [screenshoot](https://user-images.githubusercontent.com/72945564/223394925-61f8090d-1e64-4f6e-a530-677b3ca4535d.png)
- on Opera it has banned me: [screenshoot](https://user-images.githubusercontent.com/72945564/223395375-a963a2b0-bee9-4702-ac61-73177ac2400a.png)

**Comment by Daxy7** [comment]
>on Opera I've been banned

I tried using Tor Browser for this site and it's stuck in an infinite `Checking if the site connection is secure` loop. So if you're using Tor or a VPN, need to disable it

**Comment by liamengland1** [comment]
Lol, my IP is banned too.

**Comment by Daxy7** [comment]
Huh. I checked just now. I am banned in addition. :D
https://user-images.githubusercontent.com/91396482/223613974-4f45211f-0891-44bf-abe1-ee916c1d0da8.png

**Comment by krystian3w** [comment]
Are they playing with a second Kiss anime?

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17070

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/144903

**Comment by mapx-** [comment]
I guess all of us are banned right now or the webmaster ruined his site
