### ISSUE TITLE
wfmz.com, news.lee.net, ... (syndicated CNN videos): ads, breakage

### ISSUE THREAD

**Issue by liamengland1** [uBlockOrigin/uAssets#17071]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

CNN syndicated video embeds broken by EP filter `://lightning.*/launch/`. There are also SSAI preroll ads

### URL(s) where the issue occurs.

```
https://www.wfmz.com/news/cnn/us-politics/raw-dc-house-cmte-weaponization-of-fed-govt-opening/video_6f8e29e1-caa6-5948-b4c3-4999c5e13f60.html
https://news.lee.net/partners/cnn/schwarzenegger-addresses-rising-level-of-hate-and-antisemitism-at-stockton-university/video_f82cc992-17e5-53f4-8cfa-6fba8bd49e46.html
```

### uBO version

1.47.2

### Browser name and version

Firefox Stable

### Settings

n/a

### Notes

For quick fixes: `@@||lightning.cnn.com/launch/$script`

Prerolls: `||medium.ngtv.io/v2/media/*&ssaiProfile=$xhr,removeparam=ssaiProfile` (other Turner sites use `ngtv.io` for media API, but I didn't see the `ssaiProfile` param being used on Cartoon Network/TNT in a quick check)

**Comment by stephenhawk8054** [comment]
Does this work for you?

```adb
||lightning.cnn.com/launch/$script,redirect-rule=noopjs
```

**Comment by liamengland1** [comment]
Yep, works for me
