### ISSUE TITLE
[nsfw] xopenload.pw: nuisance

### ISSUE THREAD

**Issue by ChubbBear** [uBlockOrigin/uAssets#17086]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://xopenload.pw/toxic-fuck-attacks/`

### Category

nuisance

### Description

VPN checker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 85538
  cosmetic: 38630
  scriptlet: 16753
  html: 863
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32307-70, 2d.12h.53m
    ublock-badware: 4625-0, 2d.12h.52m
    ublock-privacy: 307-0, 2d.12h.51m
    ublock-abuse: 78-0, 2d.12h.50m
    ublock-unbreak: 1915-2, 2d.12h.49m
    ublock-quick-fixes: 398-0, 1m
    easylist: 63470-629, 2d.12h.46m
    easyprivacy: 31015-1786, 2d.12h.45m
    urlhaus-1: 6575-0, 2d.12h.44m
    plowe-0: 3755-2, 2d.12h.43m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10149 ms (selfie)
  maxAssetCacheWait: 2870 ms
popupPanel: 
  blocked: 32
  blockedDetails: 
    xopenload.pw: 2
    addthis.com: 1
    alleviatepracticableaddicted.com: 1
    cuddlethehyena.com: 2
    drivevideo.xyz: 12
    google-analytics.com: 1
    realsrv.com: 2
    testingmetriksbre.ru: 4
    wiztube.xyz: 3
    wp.com: 2
    wpadmngr.com: 2
```
</details>

**Comment by mapx-** [comment]
Test 

`wiztube.xyz##+js(acs, Math.floor, vpn)`
