### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by gyga0** [uBlockOrigin/uAssets#17089]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/r3jS/Far.Cry.5.Dead.Living.Zombies.part04.rar`

### Category

detection

### Description

This page requires adblock to be disabled to continue downloading the file.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 86777
  cosmetic: 46449
  scriptlet: 17261
  html: 904
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32883-94, 1d.8h.40m
    ublock-badware: 4644-0, 1d.8h.39m
    ublock-privacy: 338-0, 1d.8h.38m
    ublock-abuse: 78-0, 1d.8h.37m
    ublock-unbreak: 1915-12, 1d.8h.36m
    ublock-quick-fixes: 361-0, 6h.51m
    easylist: 63428-582, 1d.8h.34m
    easyprivacy: 31019-1768, 1d.8h.33m
    urlhaus-1: 6487-0, 6h.50m
    plowe-0: 3755-2, 1d.8h.31m
    POL-0: 7877-25, 6h.52m
    POL-2: 1278-12, 1d.8h.45m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 853 ms (selfie)
  maxAssetCacheWait: 273 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    megaup.net: 3
    a-ads.com: 1
    altowriestwispy.com: 1
    bidgear.com: 1
    dmmzkfd82wayn.cloudfront.net: 3
    googletagmanager.com: 1
    keydawnawe.com: 1
    s3.amazonaws.com: 1
```
</details>

**Comment by mapx-** [comment]
> I forced an update of my filter lists

You didn't.
