### ISSUE TITLE
stuk.tv: detection

### ISSUE THREAD

**Issue by B3CKDOOR** [uBlockOrigin/uAssets#17087]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [x] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.stuk.tv/episode/reislijders-afl2`

### Category

detection

### Description

"Your using an adblocker" warning

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![YFeI5DwrqV](https://user-images.githubusercontent.com/22119241/223786282-2117a2e2-925e-44b5-8e57-bcc6d5d3bd7e.png)

https://1drv.ms/u/s!ArON1UJDrhichKJ5EmgpR4mLwOeWAg?e=rRI2X4

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 85151
  cosmetic: 38970
  scriptlet: 17043
  html: 891
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32881-60, 15m
    ublock-badware: 4644-0, 14m
    ublock-privacy: 323-0, 8d.21h.46m
    ublock-abuse: 79-0, 8d.21h.45m
    ublock-unbreak: 1920-16, 13m
    ublock-quick-fixes: 347-0, 23h.21m
    easylist: 63314-565, 4d.23h.52m
    easyprivacy: 31004-1765, 4d.23h.51m
    urlhaus-1: 6374-0, 23h.22m
    plowe-0: 3750-2, 8d.1m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 161 ms (selfie)
  maxAssetCacheWait: 62 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    newrelic.com: 3
    sentry.io: 18
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `NLD: EasyDutch`
