### ISSUE TITLE
dalmacijadanas.hr: nuisance

### ISSUE THREAD

**Issue by IvoKvesic** [uBlockOrigin/uAssets#17088]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dalmacijadanas.hr/rubrika/dalmacija/`

### Category

nuisance

### Description

This and almost all other pages on the site at opening bring up a sort of a pop-up that takes focus and obscures the rest of the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 85185
  cosmetic: 38980
  scriptlet: 17056
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63345-47, 3d.18h.54m
    easyprivacy: 31009-1172, 3d.18h.53m
    plowe-0: 3755-929, 1d.22h.35m
    ublock-abuse: 78-0, 4d.2h.56m
    ublock-badware: 4640-114, 22h.23m
    ublock-filters: 32058-67, 22h.22m
    ublock-privacy: 287-1, 4d.2h.55m
    ublock-quick-fixes: 347-22, 1d.2h.26m
    ublock-unbreak: 1904-54, 22h.21m
    urlhaus-1: 6374-0, 1d.2h.25m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 99 ms (selfie)
  maxAssetCacheWait: 56 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    dalmacijadanas.hr: 1
    adform.net: 1
    facebook.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 3
    googletagservices.com: 1
    horvat.info: 1
    midas-network.com: 2
```
</details>

**Comment by mapx-** [comment]
Test

`dalmacijadanas.hr##[onload*="advert_name"]`

**Comment by IvoKvesic** [comment]
Still the same ☹

 

From: mapx ***@***.***>
Reply-To: uBlockOrigin/uAssets ***@***.***>
Date: Wednesday, March 8, 2023 at 19:55
To: uBlockOrigin/uAssets ***@***.***>
Cc: IvoKvesic ***@***.***>, Author ***@***.***>
Subject: Re: [uBlockOrigin/uAssets] dalmacijadanas.hr: nuisance (Issue #17088)

 

Test

dalmacijadanas.hr##[onload*="advert_name"]

**Comment by mapx-** [comment]
right,

```
dalmacijadanas.hr##[onload*="advert_name"]
dalmacijadanas.hr###html5box-html5-lightbox
```

**Comment by IvoKvesic** [comment]
That did it!

Thanks a million!

 

 

From: mapx ***@***.***>
Reply-To: uBlockOrigin/uAssets ***@***.***>
Date: Wednesday, March 8, 2023 at 20:25
To: uBlockOrigin/uAssets ***@***.***>
Cc: IvoKvesic ***@***.***>, Author ***@***.***>
Subject: Re: [uBlockOrigin/uAssets] dalmacijadanas.hr: nuisance (Issue #17088)

 

right,
dalmacijadanas.hr##[onload*="advert_name"]
dalmacijadanas.hr###html5box-html5-lightbox

**Comment by mapx-** [comment]
However, you should search for a regional list for Croatia

**Comment by mapx-** [comment]
@ryanbr for the international section in EL ?

**Comment by IvoKvesic** [comment]
> 

Tried. Couldn't find.

**Comment by mapx-** [comment]
@IvoKvesic 

Enable this list `AdGuard Base`

It has a Croatian section

![image](https://user-images.githubusercontent.com/10303732/223836596-7e0b1c47-ad05-4d3a-83dd-4fa7839ff31a.png)

If you report the ads at: https://github.com/AdguardTeam/AdguardFilters/issues
They will add filters to fix those issues

However, @Yuki2718 could you add the filters above to AG list ?

**Comment by IvoKvesic** [comment]
Thanks ————On Mar 8, 2023, at 21:09, mapx ***@***.***> wrote:﻿
@IvoKvesic
Enable this list AdGuard Base
It has a Croatian section

If you report the ads at: https://github.com/AdguardTeam/AdguardFilters/issues
They will add filters to fix those issues
However, @Yuki2718 could you add the filters above to AG list ?

**Comment by DandelionSprout** [comment]
To the best of my knowledge, EasyList has outright *rejected* reports for non-English sites in recent years, despite their Readme previously saying they did.

I suppose you can try https://raw.githubusercontent.com/DandelionSprout/adfilt/master/SerboCroatianList.txt (Disclosure: The list is made by me), which has recently grown to have enough entries recently that I think I can propose its inclusion to the uBlock Origin Team soon-ish.

**Comment by Yuki2718** [comment]
I'm surprised to find we don't have Croatian list, IIRC the exe-maintainer of IDCAC is Croatian so assumed we have something. @mapx- @MasterKia Will the @DandelionSprout 's list be stock list?

**Comment by Yuki2718** [comment]
I think he can add even if currently not. We should probably consider defaulting the list, assuming there's no alternative well-maintained by native Croatian. The list is included in AG tho without Recommended mark.

**Comment by DandelionSprout** [comment]
AdGuard's list has approx. ¼ as many Croatian-Serbian-Bosnian entries as what my list has, at least time I counted.

**Comment by mapx-** [comment]
@DandelionSprout 
Do you have all AG croatian filters in your list ?

**Comment by DandelionSprout** [comment]
https://github.com/DandelionSprout/adfilt/blob/e32b4b43ead1b9cc490762296a7f0c2ff4f940f2/SerboCroatianList.txt#L240-L290 indicates a yes, but I can doublecheck tonight.

**Comment by DandelionSprout** [comment]
Fantastic to hear, and thanks for the headsup.
