### ISSUE TITLE
rosenheim24.de: popup

### ISSUE THREAD

**Issue by hackgrid** [uBlockOrigin/uAssets#17085]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi,

since #9237

it worked fine, no popups, but since a few days, they appear again when trying to read an article, e.g:

`https://www.rosenheim24.de/rosenheim/mangfalltal/kolbermoor-ort45141/mini-club-geschlossen-kindersport-gestrichen-werden-kinder-in-kolbermoor-jetzt-wie-eine-last-abgeschoben-92130078.html`

The popup looks like a new design, so maybe some field-names changed?

Thanks and kind regards!

### URL(s) where the issue occurs.

```
https://www.rosenheim24.de/rosenheim/mangfalltal/kolbermoor-ort45141/mini-club-geschlossen-kindersport-gestrichen-werden-kinder-in-kolbermoor-jetzt-wie-eine-last-abgeschoben-92130078.html
https://www.chiemgau24.de/bayern/landkreis-muehldorf/unfalltod-einer-16-jaehrigen-so-gefaehrlich-ist-die-mue-27-zwischen-oberbergkirchen-und-irl-92129436.html
```

### uBO version

1.47.4

### Browser name and version

Firefox 110.0.1

### Settings

- None

### Notes

Clear cache to load page freshly.

**Comment by hackgrid** [comment]
Well it did in the past years, because the page was coded badly and the
whole article was always transmitted, but just hidden. And the old filter
circumvented that :)

iSmokeMid69 ***@***.***> schrieb am Mi., 8. März 2023, 17:50:

**Comment by mapx-** [comment]
```
pc-offer$script,domain=bgland24.de|chiemgau24.de|innsalzach24.de|mangfall24.de|rosenheim24.de|wasserburg24.de
bgland24.de,chiemgau24.de,innsalzach24.de,mangfall24.de,rosenheim24.de,wasserburg24.de##div.id-StoryElement-beepWrap
bgland24.de,chiemgau24.de,innsalzach24.de,mangfall24.de,rosenheim24.de,wasserburg24.de##.wv_story_el_cleverPushWidget
bgland24.de,chiemgau24.de,innsalzach24.de,mangfall24.de,rosenheim24.de,wasserburg24.de##.id-Recommendation
bgland24.de,chiemgau24.de,innsalzach24.de,mangfall24.de,rosenheim24.de,wasserburg24.de##.wv_story_el_pinpoll
```

**Comment by hackgrid** [comment]
> ```
> pc-offer$script,domain=bgland24.de|chiemgau24.de|innsalzach24.de|mangfall24.de|rosenheim24.de|wasserburg24.de
> bgland24.de,chiemgau24.de,innsalzach24.de,mangfall24.de,rosenheim24.de,wasserburg24.de##div.id-StoryElement-beepWrap
> bgland24.de,chiemgau24.de,innsalzach24.de,mangfall24.de,rosenheim24.de,wasserburg24.de##.wv_story_el_cleverPushWidget
> bgland24.de,chiemgau24.de,innsalzach24.de,mangfall24.de,rosenheim24.de,wasserburg24.de##.id-Recommendation
> bgland24.de,chiemgau24.de,innsalzach24.de,mangfall24.de,rosenheim24.de,wasserburg24.de##.wv_story_el_pinpoll
> ```

Amazing, this works fine, thank you very much! :-)
Could you add it to the main filter list please?

**Comment by mapx-** [comment]
considering it still a false / poor paywall

**Comment by hackgrid** [comment]
thanks! :)
