### ISSUE TITLE
useast2-www.securly.com: detectionn omg

### ISSUE THREAD

**Issue by hacckerrj** [uBlockOrigin/uAssets#17091]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://useast2-www.securly.com/blocked?useremail=20010618@eps.k12.mi.us&reason=domainblockedforuser&categoryid=67174400&policyid=2&keyword=&url=d3d3LmZvcnRuaXRlLmNvbS8/bGFuZz1lbi1VUw==&ver=2.98.44&lat=42.2415719&lng=-83.1465576`

### Category

detectionr

### Description

d

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
tg

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 0
  cosmetic: 0
  scriptlet: 0
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-filters: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
    urlhaus-1: null
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 12 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  autoUpdate: false
  collapseBlocked: false
  colorBlindFriendly: true
  contextMenuEnabled: false
  hyperlinkAuditingDisabled: false
  parseAllABPHideFilters: false
  prefetchingDisabled: false
  showIconBadge: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12455 ms
  maxAssetCacheWait: 8650 ms
popupPanel: 
  blocked: 0
```
</details>g

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/11381

**Comment by iam-py-test** [comment]
You are running a broken or poorly configured version of uBo. Please reset it to default settings using the "reset to default settings" button.
Also, this is something setup by your company/school; uBo can not touch it, you will need to talk to your admin or use a personal device.
