### ISSUE TITLE
unofficialtwrp.com: detection

### ISSUE THREAD

**Issue by user460** [uBlockOrigin/uAssets#17090]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://unofficialtwrp.com/`

### Category

detection

### Description

Detects ublock and block the entire website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 110
filterset (summary): 
  network: 149468
  cosmetic: 138922
  scriptlet: 34131
  html: 907
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38358-3719, 1m
    https://get.letsblock.it/list/4a8d39d8-1edd-470e-a3f7-946a174faeb9.txt: 1302-0, 1m
    https://raw.githubusercontent.com/robonxt/CleanYourTwitter/master/CleanYourTwitter%20(EXTRAS).txt: 5-0, 1m
    https://raw.githubusercontent.com/robonxt/CleanYourTwitter/master/CleanYourTwitter.txt: 17-0, 1m
    adguard-generic: 68324-5979, 1m
    adguard-annoyance: 64754-764, 1m
    FRA-0: 30071-698, 1m
  default: 
    user-filters: 28-0, never
    ublock-filters: 33712-123, 1m
    ublock-badware: 4649-0, 1m
    ublock-privacy: 338-0, 1m
    ublock-abuse: 78-0, 1m
    ublock-unbreak: 1922-12, 1m
    ublock-quick-fixes: 370-0, 1m
    easylist: 63614-553, 1m
    easyprivacy: 31028-12698, 1m
    urlhaus-1: 6523-0, 1m
    plowe-0: 3755-2, 1m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 39 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 283 ms (selfie)
  maxAssetCacheWait: 406 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by rajarshikhatua100** [comment]
![Screenshot (325)](https://github.com/uBlockOrigin/uAssets/assets/77912617/2d8148df-512d-45b1-816b-fa2c91d836ab)
the fix not working

**Comment by uBlock-user** [comment]
> ![Screenshot (325)](https://private-user-images.githubusercontent.com/77912617/308572042-2d8148df-512d-45b1-816b-fa2c91d836ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjkwODIsIm5iZiI6MTcwOTEyODc4MiwicGF0aCI6Ii83NzkxMjYxNy8zMDg1NzIwNDItMmQ4MTQ4ZGYtNTEyZC00NWIxLTgxNmItZmEyYzkxZDgzNmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEzNTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNDk3MjZkMDdkNTUxMGNmMGZiMjM2ZGU5ODVhYmZlOTAyMzllY2Y5NjU0MGZlMWZlOTY1ZGViZTRiY2Y4MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NjxgA87SFITqJY6H20N8RjzpMRgdClQ1fffXOhqjIEI) the fix not working

try `unofficialtwrp.com##+js(rmnt, script, mdpDeblocker)`
