### ISSUE TITLE
ratanygaimiaheo.com: ads

### ISSUE THREAD

**Issue by D3lt4dr0m** [uBlockOrigin/uAssets#17092]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ratanygaimiaheo.com/ice/p7125?atp=320883420_23571140_Adcash_6768718&goto=sitereg&click_id=1678312869100010TPLTV432397053854V4&plid=14756&bnid=26798&lang=pl&cc=PL`

### Category

ads

### Description

Possibly dangerous website, to which i have been redirected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 86793
  cosmetic: 46450
  scriptlet: 17260
  html: 904
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32882-94, 49m
    ublock-badware: 4649-0, 48m
    ublock-privacy: 336-0, 3d.9h.42m
    ublock-abuse: 78-0, 3d.9h.41m
    ublock-unbreak: 1915-0, 2d.23h.16m
    easylist: 63428-582, 1d.11h.27m
    easyprivacy: 31000-1765, 5d.22h.41m
    urlhaus-1: 6523-0, 5h.1m
    plowe-0: 3755-2, 50m
    POL-0: 7877-25, 5h.2m
    POL-2: 1278-12, 22h.23m
    ublock-quick-fixes: 353-12, 5h.3m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 420 ms (selfie)
  maxAssetCacheWait: 208 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
> Possibly dangerous website, to which i have been redirected.

We need the page from where you've been redirected to the site above

**Comment by D3lt4dr0m** [comment]
The page was https://zerion.cc/

śr., 8 mar 2023 o 23:12 mapx ***@***.***> napisał(a):

**Comment by Daxy7** [comment]
No popups from original link. I click on a movie:
```
Wymagane konto! -> Account required!
Zaloguj się, aby wykonać tą akcje. -> Sign in, to perform this action.
```
