### ISSUE TITLE
pop-up on videoplayer

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#17096]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On the link below when I press the play button, a pop-up appear.

### URL(s) where the issue occurs.

`https://filmeserialegratis.io/faraway/`

### uBO version

1.47.2

### Browser name and version

Firefox 111

### Settings

Default settings

**Comment by andreewmat** [comment]
@mapx- Hello, also on this website I get the same popup on NETU player: `https://www1.divxfilmeonline.net/s-w-a-t-sezonul-6-episodul-16/`

I guess these popus are the same for all the movies sites that has NETU player. Can't be blocked all of them at once?

**Comment by mapx-** [comment]
There are different domains.

If you are using a lot of these sites just add

`*##+js(nowoif)`

but keep in mind you could break other pages (in that case just add exceptions to that filter)
