### ISSUE TITLE
gpmdg.arrowtoldilim.com: popup

### ISSUE THREAD

**Issue by GodJohnson1** [uBlockOrigin/uAssets#17093]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gpmdg.arrowtoldilim.com/RMJTB?tag_id=916806&sub_id1=&sub_id2=878440446851676381&cookie_id=9b707537-03be-4e93-99a3-b9fa3b076160&lp=black_screen_arrow&tb=redirect&allb=redirect&ob=redirect&href=https%3A%2F%2Fmovementxvi.info%2F%3Ftid%3D916806%26noocp%3D1&hop=7&geo=US`

### Category

[unknown]

### Description

Does not block this site at all in which is most definitely a popup ad.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 86538
  cosmetic: 38587
  scriptlet: 16705
  html: 853
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 32307-52, 1d.17h.8m
    ublock-badware: 4049-1, 1d.17h.7m
    ublock-privacy: 323-0, 9d.22h.27m
    ublock-abuse: 79-0, 9d.22h.26m
    ublock-unbreak: 1921-1, 1d.17h.6m
    ublock-quick-fixes: 372-0, 5h.1m
    easylist: 64987-621, 3d.20h.31m
    easyprivacy: 31014-1766, 3d.20h.30m
    urlhaus-1: 6487-0, 9h.2m
    plowe-0: 3749-2, 9d.2h.1m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 128 ms (selfie)
  maxAssetCacheWait: 135 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by GodJohnson1** [comment]
This annoyance needs to be taken care of. I've tried everything and cannot get it to stop.

**Comment by D4niloMR** [comment]
Try:
`||gpmdg.arrowtoldilim.com^$popup`

**Comment by stephenhawk8054** [comment]
Is it a popup/redirection from another link? If yes, please provide original link.
