### ISSUE TITLE
mylivewallpapers.com: detection

### ISSUE THREAD

**Issue by thunderstrom122** [uBlockOrigin/uAssets#17099]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mylivewallpapers.com/category/anime/page/5/`

### Category

detection

### Description

it detected that I was using an adblocker thus not letting me use the webpage 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 109
filterset (summary): 
  network: 164046
  cosmetic: 78685
  scriptlet: 30632
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 68332-506, 2h.55m
    adguard-mobile: 8756-44, 3d.23h.20m
    curben-phishing: 49407-0, 15h.39m
    curben-pup: 200-0, 15h.40m
    dpollock-0: 11337-110, 6h.57m
  default: 
    user-filters: 4-1, never
    easylist: 63558-1054, 1d.23h.15m
    easyprivacy: 31015-1393, 1d.23h.14m
    plowe-0: 3751-1383, 6d.2h.31m
    ublock-abuse: 79-0, 7d.3h.26m
    ublock-badware: 4640-327, 2h.56m
    ublock-filters: 32021-3511, 2h.54m
    ublock-privacy: 283-1, 7d.3h.25m
    ublock-quick-fixes: 354-49, 15h.38m
    ublock-unbreak: 1904-93, 3d.18h.20m
    urlhaus-1: 6523-2, 15h.37m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7713 ms (selfie)
  maxAssetCacheWait: 4151 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    snigelweb.com: 1
```
</details>

**Comment by MandiYang** [comment]
It doesn't block me while using adblocker when accessing the url.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by garry-ut99** [comment]
Me too unable to reproduce anti-adblock.

> * [x]  I did not answer truthfully to **ALL** the above checkpoints.
