### ISSUE TITLE
atresplayer.com: breakage

### ISSUE THREAD

**Issue by Edushaktale** [uBlockOrigin/uAssets#17095]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.atresplayer.com/`

### Category

breakage

### Description

When starting a video in this webpage, it will charge a black-screen and sometimes ONLY the audio of the content after a while.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 117325
  cosmetic: 102466
  scriptlet: 23444
  html: 1042
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39141-3884, 3d.9h.38m
    adguard-spyware-url: 928-4, 3d.9h.40m
    block-lan: 44-0, 11d.14h.27m
    adguard-annoyance: 64629-881, 3d.9h.42m
    ublock-annoyances: 4806-4, 3d.9h.41m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32879-103, 3d.9h.45m
    ublock-badware: 4633-0, 3d.9h.44m
    ublock-privacy: 323-0, 11d.14h.27m
    ublock-abuse: 79-0, 11d.14h.27m
    ublock-unbreak: 1915-12, 3d.9h.43m
    ublock-quick-fixes: 361-0, 48m
    easylist: 63278-647, 5d.11h.38m
    easyprivacy: 31004-12793, 5d.11h.37m
    urlhaus-1: 6559-0, 47m
    plowe-0: 3749-2, 11d.14h.27m
    spa-0: 3508-1, 46m
    spa-1: 5090-139, 3d.9h.39m
filterset (user): [empty]
trustedset: 
  added: [array of 23 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1101 ms (selfie)
  maxAssetCacheWait: 463 ms
popupPanel: 
  blocked: 44
  blockedDetails: 
    atresplayer.com: 2
    adsafeprotected.com: 1
    adsrvr.org: 1
    amazon-adsystem.com: 1
    appsflyer.com: 1
    chartbeat.com: 1
    conviva.com: 6
    demdex.net: 4
    doubleclick.net: 1
    everesttech.net: 1
    facebook.net: 1
    fwmrm.net: 4
    getpublica.com: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    hotjar.com: 1
    mathtag.com: 1
    omtrdc.net: 6
    scorecardresearch.com: 2
    serving-sys.com: 1
    smartclip.net: 1
    spotxchange.com: 1
    stickyadstv.com: 1
    tiktok.com: 2
```
</details>

**Comment by mapx-** [comment]
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by Edushaktale** [comment]
Sure! :)

**Comment by mapx-** [comment]
send here the info: `axis.trivia@gmail.com`

**Comment by mapx-** [comment]
@Edushaktale 

I used the same filter lists as yours, firefox, Madrid ip etc => no issue on my end.

Follow all these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Edushaktale** [comment]
Thanks a lot for your support! I could solve it.
