### ISSUE TITLE
megadb.net: ads

### ISSUE THREAD

**Issue by ABBNojGau** [uBlockOrigin/uAssets#17106]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megadb.net/download`

### Category

ads

### Description

the website still shows ads, i was linked from https://steamrip.com/five-nights-at-freddys-vr-help-wanted-free-download/

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/116065858/224138585-d57dbedf-8261-432c-a720-bc9333a1b124.png)
![image](https://user-images.githubusercontent.com/116065858/224138634-bf7427e1-bfbf-4682-8a53-325c5f8d33ee.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 86925
  cosmetic: 41465
  scriptlet: 17343
  html: 910
listset (total-discarded, last-updated): 
  added: 
    SWE-1: 4308-2, 2d.23h.6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32883-90, 2d.23h.5m
    ublock-badware: 4644-0, 2d.23h.8m
    ublock-privacy: 337-0, 2d.23h.3m
    ublock-abuse: 78-0, 2d.23h.4m
    ublock-unbreak: 1916-12, 2d.23h.7m
    ublock-quick-fixes: 382-0, 3h.2m
    easylist: 63428-520, 2d.23h.11m
    easyprivacy: 31015-1789, 2d.23h.10m
    urlhaus-1: 6486-0, 3h.1m
    plowe-0: 3755-2, 2d.23h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 420 ms (selfie)
  maxAssetCacheWait: 152 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    betotodilea.com: 1
    google-analytics.com: 1
    goomaphy.com: 1
    offerimage.com: 4
    tzegilo.com: 1
    uponelectabuzzor.club: 1
```
</details>

**Comment by Daxy7** [comment]
3P Domain (spawns child domains but seems this is the only one to block. not good solution based on their IP history)
`||aguwehajqluorgv.com^`
`https://user-images.githubusercontent.com/91396482/224144190-0a8327eb-ea79-40ac-96b0-878391902599.png`
