### ISSUE TITLE
cybermania.ws: detection

### ISSUE THREAD

**Issue by shakibhasan009** [uBlockOrigin/uAssets#17102]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cybermania.ws/`

### Category

detection

### Description

Detected adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
https://www.cybermania.ws/

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 85232
  cosmetic: 38932
  scriptlet: 17014
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 11-1, never
    easylist: 63278-47, 5d.7h.32m
    easyprivacy: 30906-1174, 5d.7h.31m
    plowe-0: 3749-871, 10d.15h.36m
    ublock-abuse: 79-0, 11d.8h.2m
    ublock-badware: 4640-114, 2d.23h.48m
    ublock-filters: 32057-68, 2d.23h.47m
    ublock-privacy: 276-1, 11d.1h.20m
    ublock-quick-fixes: 387-146, 19h.41m
    ublock-unbreak: 1904-40, 2d.23h.46m
    urlhaus-1: 6523-0, 19h.40m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 10 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 27897 ms (selfie)
  maxAssetCacheWait: 390 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    cloudflareinsights.com: 1
    doubleclick.net: 2
    google.com: 1
    googlesyndication.com: 6
    googletagmanager.com: 1
    paypalobjects.com: 2
    revolvermaps.com: 1
    translate.googleapis.com: 1
```
</details>

**Comment by Daxy7** [comment]
quick workaround:

1. disable js in ublock origin
2. add this to your user filters
3. cybermania.ws###mdp-deblocker-js-disabled

**Comment by Mennaruuk** [comment]
Hello @mapx- , the anti-adblock seems to be back on. If you have some free time, may you please look into it? If not, no worries!

![265533132-efc19e8a-b741-4aa3-9285-348e8556d4c8](https://github.com/uBlockOrigin/uAssets/assets/52135169/03e3b0f1-0ab4-4bbd-b258-be876c01f67f)

**Comment by Sopor** [comment]
I still get a detection here `https://www.cybermania.ws/ip`
