### ISSUE TITLE
Spiegel.de Anti Adblock #1645 not working any more

### ISSUE THREAD

**Issue by snottyone** [uBlockOrigin/uAssets#1710]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.spiegel.de/`

### Describe the issue

uBlock gets detected and an overlay is displayed, asking to disable the blocker.

### Screenshot(s)

same popup as in +1645

### Versions

- Browser/version: Palemoon
- uBlock Origin version: v0.9.5.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
continue here:
https://github.com/uBlockOrigin/uAssets/issues/1641

uBlock Origin version: v0.9.5.2 ??
