### ISSUE TITLE
ytcomment.kmcat.uk: nuisance

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17107]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ytcomment.kmcat.uk/`

### Category

nuisance

### Description

Scroll script breakage in Firefox
Firefox:
**https://user-images.githubusercontent.com/91396482/224139485-70f16762-9a2f-4f72-a126-6125d98a3316.mp4**
Chromium:
**https://user-images.githubusercontent.com/91396482/224139549-4b75b19c-5c95-4a34-bd90-bbd6d2e48ac0.mp4**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 77660
  cosmetic: 42070
  scriptlet: 20411
  html: 1059
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1487-0, 56m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 56m
    ublock-annoyances: 4807-4, 56m
  default: 
    user-filters: 1564-13, never
    ublock-filters: 33688-69, 56m
    ublock-badware: 4659-0, 56m
    ublock-privacy: 338-0, 56m
    ublock-abuse: 78-0, 56m
    ublock-unbreak: 1922-12, 56m
    ublock-quick-fixes: 386-0, 56m
    easylist: 63775-242, 56m
    easyprivacy: 31032-2159, 56m
filterset (user): [array of 592 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 283 ms (selfie)
  maxAssetCacheWait: 327 ms
  unsuspendAfter: 130 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    firebaselogging-pa.googleapis.com: 3
    googletagmanager.com: 1
    report-uri.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in more details?

**Comment by Daxy7** [comment]
Enter a any video url with comments enabled. Sample: `https://www.youtube.com/watch?v=F-jQoWf_Iv8`
Click the search button.
And now click on any comment with replies: 0 or higher

**Comment by stephenhawk8054** [comment]
I don't think uBO can fix that. You might need to report to the site owner.

**Comment by Daxy7** [comment]
> You might need to report to the site owner.

Yeah the issue has been open on `https://gitlab.com/kmcat/ytcomment/-/issues/30` since `Feb 1, 2023 5:14 pm UTC`
No progress yet.

Thre is this funcs in `ytcomment.kmcat.uk/f0cb1e22.js` and using ctrl+f to search for `scroll` 
6 hits about
<details><summary>Source</summary>

scroll2

scrollHeight

scrollTop

scrollIntoView

@scroll="${e=>this.scroll2(e)}">
</details>

9 hits in `ytcomment.kmcat.uk/2f3bf148.js` 
<details><summary>Source</summary>

`getWidth:()=>e.scrollWidth 

["touchstart","touchmove","scroll","mousewheel"] 

("bottomsearch-section").scrollIntoView(!0)})),N  

("#resHoldcomments").scrollTop=e-80,I(R() 

.scrollIntoView({behavior:"smooth",block:"end",inline:"nearest"}),N` 
</details>

something about debounce too, related to scrolling?
