### ISSUE TITLE
ulusal.com.tr: ads

### ISSUE THREAD

**Issue by tlostshadow01** [uBlockOrigin/uAssets#17103]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ulusal.com.tr/egitim/depremzede-ogrencilere-egitim-yardimi-bakan-ozer-acikladi-15018059?`

### Category

ads

### Description

There are ad scraps on the website

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230309-201002_1](https://user-images.githubusercontent.com/101035482/224103270-35c30af3-ba43-465a-a2a9-ab49c0f400b2.jpg)

![Screenshot_20230309-201009_1](https://user-images.githubusercontent.com/101035482/224103283-c1bba3eb-f902-4b2b-aea8-1d51bac0855a.jpg)

![Screenshot_20230309-201141](https://user-images.githubusercontent.com/101035482/224103440-89b64bcf-6528-45ff-8390-bf743acf80a5.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium Mobile: 107
filterset (summary): 
  network: 152154
  cosmetic: 62318
  scriptlet: 20129
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock: 130-0, 12h.42m
    adguard-spyware-url: 939-2, 21m
    block-lan: 44-0, 4d.2h.3m
    curben-phishing: 49882-0, 12h.45m
    curben-pup: 196-0, 12h.46m
    dpollock-0: 11336-80, 4d.2h.2m
    fanboy-cookiemonster: 45937-17434, 4d.2h.3m
    fanboy-thirdparty_social: 68-1, 4d.2h.3m
  default: 
    user-filters: 4-0, never
    TUR-0: 11586-197, 23m
    adguard-mobile: 8529-38, 22m
    easylist: 63430-17158, 4d.2h.2m
    easyprivacy: 31016-1309, 4d.2h.2m
    plowe-0: 3755-1387, 4d.2h.2m
    ublock-abuse: 78-0, 20m
    ublock-badware: 4639-133, 19m
    ublock-filters: 32216-313, 18m
    ublock-privacy: 289-4, 17m
    ublock-quick-fixes: 357-20, 12h.44m
    ublock-unbreak: 1915-55, 16m
    urlhaus-1: 6559-2, 12h.43m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 981 ms (selfie)
  maxAssetCacheWait: 802 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    bildirt.com: 1
    bilgin.pro: 1
    doubleclick.net: 1
    google-analytics.com: 1
    google.com: 6
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
I get no such placeholders.
Use firefox mobile.

**Comment by tlostshadow01** [comment]
> I get no such placeholders. Use firefox mobile.

Firefox mobile very slow and google shopping page very laggy
