### ISSUE TITLE
numerade.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#17108]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.numerade.com/ask/question/identify-each-of-the-following-as-a-representative-element-or-a-transition-element-a-lithium-li-b-platinum-pt-c-promethium-pm-dcarbon-c/`

### Category

breakage

### Description

Having ublock origin enabled causes the videos to not play on the page. Account is required to play video. Disabling ublock then playing the video then turning it back on then refreshing the page fixes the issue. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture2](https://user-images.githubusercontent.com/69532417/224162177-39a536fe-4a21-449e-80c1-9f3fb8aa6aa0.png)
![Captur3](https://user-images.githubusercontent.com/69532417/224162179-3d25ff90-7fcd-4d6f-af7a-77b88b5513af.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 107
filterset (summary): 
  network: 85909
  cosmetic: 39339
  scriptlet: 17376
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63775-44, 1m
    easyprivacy: 31032-1174, 1m
    plowe-0: 3755-932, 1m
    ublock-abuse: 78-0, 1m
    ublock-badware: 4655-114, 1m
    ublock-filters: 32855-79, 1m
    ublock-privacy: 289-1, 1m
    ublock-quick-fixes: 385-23, 1m
    ublock-unbreak: 1911-52, 1m
    urlhaus-1: 6486-0, 1m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1085 ms
  maxAssetCacheWait: 136 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    numerade.com: 1
    facebook.net: 1
    googletagmanager.com: 1
    hotjar.com: 1
    mxpnl.com: 1
    optimonk.com: 1
    paypal.com: 2
    tiktok.com: 1
```
</details>

**Comment by mapx-** [comment]
Don't use any other blocking extension.
if you are using a chromium browser (other than chrome):

brave => disable the shields for that site
edge => don't use strict tracking protection => switch it to balanced

still in trouble:

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by jimmysofat6864** [comment]
> Don't use any other blocking extension. if you are using a chromium browser (other than chrome):
> 
> brave => disable the shields for that site edge => don't use strict tracking protection => switch it to balanced
> 
> still in trouble:
> 
> * open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
> * repeat the steps to get the issue
> * go back into the uBO's logger and then copy and paste here all blocked requests

This is what copy pasting the blocked log returns. 


```
Current tab / SOLVED:Identify each of the following elements as a representative, a transition








filter logger content


21:50:16​#shareBtn​​www.numerade.com​​get​dom​https://www.numerade.com/questions/identify-each-of-the-following-elements-as-a-representative-a-transition-or-an-inner-transition-el-3/
21:50:15​||paypal.com/xoplatform/logger/api/logger​--​www.numerade.com​3​post​xhr​https://www.paypal.com/xoplatform/logger/api/logger
21:50:14​||client.crisp.chat^$3p​--​www.numerade.com​3​get​script​https://client.crisp.chat/l.js
21:50:14​||front.optimonk.com^​--​www.numerade.com​3​get​script​https://front.optimonk.com/public/135399/js/preload.js
21:50:14​/fbevents.js​--​www.numerade.com​3​get​script​https://connect.facebook.net/en_US/fbevents.js
21:50:13​/icon/google.​--​www.numerade.com​1​get​xhr​https://www.numerade.com/static/img/Icon/google.4d4921c0fee1.svg
21:50:13​||paypal.com/tagmanager/pptm.js​--​www.numerade.com​3​get​script​https://www.paypal.com/tagmanager/pptm.js?id=www.numerade.com&t=xo&v=5.0.358&source=payments_sdk&client_id=AbzzTDENC1IUFQPKfGjS52yWyr_eLPdyD_w_9tMIx7foVfPOf4FnRHquqZE7PcZwxSnLQaxHIKU6JtsU&vault=true
21:50:13​||analytics.tiktok.com^​--​www.numerade.com​3​get​script​https://analytics.tiktok.com/i18n/pixel/events.js?sdkid=CBON8OJC77U1OJP16RO0&lib=ttq
21:50:13​||mxpnl.com^​--​www.numerade.com​3​get​script​https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js
21:50:13​||hotjar.com^$3p​--​www.numerade.com​3​get​script​https://static.hotjar.com/c/hotjar-1309276.js?sv=6
21:50:13​googletagmanager_gtm.js​<<​www.numerade.com​3​get​script​https://www.googletagmanager.com/gtm.js?id=GTM-P883H56
21:50:13​||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5​--​www.numerade.com​3​get​script​https://www.googletagmanager.com/gtm.js?id=GTM-P883H56
21:50:13​||googletagmanager.com^​--​www.numerade.com​3​get​script​https://www.googletagmanager.com/gtm.js?id=GTM-P883H56
21:50:12​-event-tracking.​--​www.numerade.com​1​get​script​https://www.numerade.com/static/videojs-event-tracking/videojs-event-tracking.b30b04635c81.js
21:50:12​/icon/google.​--​www.numerade.com​1​get​xhr​https://www.numerade.com/static/img/Icon/google.4d4921c0fee1.svg
21:50:12​https://www.numerade.com/questions/identify-each-of-the-following-elements-as-a-representative-a-transition-or-an-inner-transition-el-3/​​​​​​

```

**Comment by jimmysofat6864** [comment]
<details><summary>Logger output</summary>

```
+3
||paypal.com/xoplatform/logger/api/logger
--
www.numerade.com
3
post
xhr
https://www.paypal.com/xoplatform/logger/api/logger
```
```
+3
###shareBtn
www.numerade.com
get
dom
https://www.numerade.com/questions/identify-each-of-the-following-elements-as-a-representative-a-transition-or-an-inner-transition-el-3/
```
```
+2
||client.crisp.chat^$3p
--
www.numerade.com
3
get
script
https://client.crisp.chat/l.js
```
```
+2
||front.optimonk.com^
--
www.numerade.com
3
get
script
https://front.optimonk.com/public/135399/js/preload.js
```
```
+2
/fbevents.js
--
www.numerade.com
3
get
script
https://connect.facebook.net/en_US/fbevents.js
```
```
+1
/icon/google.
--
www.numerade.com
1
get
xhr
https://www.numerade.com/static/img/Icon/google.4d4921c0fee1.svg
```
```
+1
||paypal.com/tagmanager/pptm.js
--
www.numerade.com
3
get
script
https://www.paypal.com/tagmanager/pptm.js?id=www.numerade.com&t=xo&v=5.0.358&source=payments_sdk&client_id=AbzzTDENC1IUFQPKfGjS52yWyr_eLPdyD_w_9tMIx7foVfPOf4FnRHquqZE7PcZwxSnLQaxHIKU6JtsU&vault=true
```
```
+1
||analytics.tiktok.com^
--
www.numerade.com
3
get
script
https://analytics.tiktok.com/i18n/pixel/events.js?sdkid=CBON8OJC77U1OJP16RO0&lib=ttq
```
```
+1
||mxpnl.com^
--
www.numerade.com
3
get
script
https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js
```
```
+1
||hotjar.com^$3p
--
www.numerade.com
3
get
script
https://static.hotjar.com/c/hotjar-1309276.js?sv=6
```
```
+1
googletagmanager_gtm.js
<<
www.numerade.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-P883H56
```
```
+1
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
www.numerade.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-P883H56
```
```
+1
||googletagmanager.com^
--
www.numerade.com
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-P883H56
```
```
+1
-event-tracking.
--
www.numerade.com
1
get
script
https://www.numerade.com/static/videojs-event-tracking/videojs-event-tracking.b30b04635c81.js
```
```
+0
https://www.numerade.com/questions/identify-each-of-the-following-elements-as-a-representative-a-transition-or-an-inner-transition-el-3/
```
</details>

**Comment by jimmysofat6864** [comment]
@mapx- Log copied and pasted here.

**Comment by mapx-** [comment]
Test

`@@||numerade.com/static/videojs-event-tracking$scrfipt,1p`

**Comment by jimmysofat6864** [comment]
Yea it appears that fixed the issue.

**Comment by mapx-** [comment]
@ryanbr
