### ISSUE TITLE
flow.microsoft.com: privacy

### ISSUE THREAD

**Issue by ACK-J** [uBlockOrigin/uAssets#17119]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The endpoint `https://flow.microsoft.com/providers/Internal.Telemetry/collect` is used send telemetry data about the user's browser to microsoft and is not blocked by uBlock. 

### URL(s) where the issue occurs.

`https://flow.microsoft.com/providers/Internal.Telemetry/collect`

### uBO version

uBlock Origin 1.47.2

### Browser name and version

Firefox 110

### Settings

None

**Comment by ACK-J** [comment]
You need to go to Sharepoint and start a Microsoft "Flow" for it to trigger. I'll try to look for a public site for you to reference

**Comment by ACK-J** [comment]
Yea I'm not sure how else you would test it. If you have a microsoft account you can try it out

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in more details? I go to my sharepoint site, but can't see any telemetry connections (screenshot: https://user-images.githubusercontent.com/66517106/224458405-06d64a3c-4e8a-468b-b426-8d346be16ca6.png) and I don't know that to next to reproduce it.

**Comment by liamengland1** [comment]
@stephenhawk8054 
`https://make.powerautomate.com/`

![image](https://user-images.githubusercontent.com/16567977/224466050-6eb075a7-a19a-4196-8f3f-e9c3e63c8716.png)

**Comment by stephenhawk8054** [comment]
Thanks I can reproduce it now.

@ryanbr
