### ISSUE TITLE
tumblr.com: nuisance

### ISSUE THREAD

**Issue by pololoduck** [uBlockOrigin/uAssets#17115]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tumblr.com/slexenskee?redirect_to=%2Fslexenskee&source=blog_view_login_wall`

### Category

nuisance

### Description

Every time I view this site I get blocked by a big login wall that I could not remove. I don't ever plan to make a tumblr account so just want to know if it's possible to block that login wall popup on the page.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/121998563/224290633-0bea90a1-6352-4d14-b585-f74dddc2285b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 105918
  cosmetic: 62917
  scriptlet: 17778
  html: 0
listset (total-discarded, last-updated): 
  added: 
    CHN-0: 27719-104, 1m
    FIN-0: 2156-0, 1m
    JPN-1: 10077-13, 1m
    KOR-1: 4246-29, 1m
  default: 
    user-filters: 7-1, never
    easylist: 63808-140, 1m
    easyprivacy: 31035-1228, 1m
    plowe-0: 3755-954, 1m
    ublock-abuse: 78-0, 1m
    ublock-badware: 4666-115, 1m
    ublock-filters: 32863-109, 1m
    ublock-privacy: 289-3, 1m
    ublock-quick-fixes: 383-26, 1m
    ublock-unbreak: 1910-55, 1m
    urlhaus-1: 6576-0, 1m
filterset (user): [array of 7 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2941 ms (selfie)
  maxAssetCacheWait: 550 ms
popupPanel: 
  blocked: 1
  no-cosmetic-filtering: true
  no-large-media: true
  blockedDetails: 
    tumblr.com: 1
```
</details>

**Comment by krystian3w** [comment]
Is this stable video:

```html
<video autoplay="" loop="" playsinline="" width="600" height="277">
   <source src="https://assets.tumblr.com/pop/src/assets/images/login-wall/art_v2-004010f0.webm" type="video/webm;codec=vp9">
   <source src="https://assets.tumblr.com/pop/src/assets/images/login-wall/art_v2-5c3eb22e.mp4" type="video/mp4">
   <img src="https://assets.tumblr.com/pop/src/assets/images/login-wall/art_v2-3f0f7a0b.gif" alt="">
</video>
```

?

Maybe then works in Korea and Japan:

```adb
tumblr.com###glass-container:has([src*="/login-wall/"])
tumblr.com###glass-container style:has-text(/^body { overflow: hidden; }$/):remove()
```

**Comment by mapx-** [comment]
@pololoduck use the filters above as custom filters (in "my filters" tab)

**Comment by UnlimitedCookies** [comment]
> tumblr.com###glass-container > [aria-modal="true"]:not(:has(> button:first-child))
> tumblr.com###glass-container style:has-text(/^body { overflow: hidden; }$/):remove()

This seems to work, but when scrolling the website still appends a `?redirect_to=%2Fuser&source=blog_view_login_wall` to the url.

Also, why is this rule (or a similar) not included in `uBlock filters – Annoyances` or the EasyList equivalent?
