### ISSUE TITLE
medibang.com: ads

### ISSUE THREAD

**Issue by thecutefinder** [uBlockOrigin/uAssets#17114]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://medibang.com/picture/rr2211130800105890022376786/`

### Category

ads

### Description

This, which was meant to show an ad, still pops up:

![image](https://user-images.githubusercontent.com/123335166/224256019-0135aaae-0728-480e-b4e3-c8c972e6afe8.png)

Filter that seems to remove it, made using the element picker:
```
##.-fixed.mdbnAdBlock
##.icon-close01.iconfont.mdbnAdBlock__close
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 291764
  cosmetic: 333686
  scriptlet: 42676
  html: 1116
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38358-3928, 1d.1h.24m
    adguard-generic: 68326-6622, 1d.1h.42m
    adguard-mobile: 8529-13, 1d.1h.41m
    adguard-spyware-url: 928-4, 1d.1h.40m
    block-lan: 44-0, 13d.8h.27m
    curben-phishing: 50807-21, 7h.49m
    curben-pup: 196-0, 7h.48m
    adguard-annoyance: 64759-5467, 1d.1h.39m
    adguard-social: 19968-1010, 1d.1h.38m
    fanboy-thirdparty_social: 68-0, 4d.5h.47m
    fanboy-annoyance: 82062-70213, 4d.5h.46m
    fanboy-cookiemonster: 45937-309, 4d.5h.45m
    fanboy-social: 22358-40, 6d.7h.49m
    ublock-annoyances: 4807-37, 1d.1h.37m
    dpollock-0: 11336-518, 2d.7h.49m
    ALB-0: 301-4, 7h.47m
    ara-0: 2776-1, 7h.45m
    BGR-0: 1091-11, 3d.5h.48m
    CHN-0: 27682-173, 1d.1h.36m
    CZE-0: 737-0, 7h.44m
    [29 lists not shown]: [too many]
  default: 
    user-filters: 10-0, never
    ublock-filters: 32847-237, 1d.1h.45m
    ublock-badware: 4649-0, 1d.1h.44m
    ublock-privacy: 338-0, 7h.52m
    ublock-abuse: 78-0, 7h.51m
    ublock-unbreak: 1920-0, 1d.1h.43m
    ublock-quick-fixes: 372-12, 3h.34m
    easylist: 63645-1290, 1d.4h.35m
    easyprivacy: 31025-12823, 1d.4h.34m
    urlhaus-1: 6576-0, 3h.33m
    plowe-0: 3755-87, 7h.50m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 634 ms (selfie)
  maxAssetCacheWait: 284 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adingo.jp: 2
    doubleclick.net: 1
    facebook.com: 1
    googleadservices.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    nakanohito.jp: 1
```
</details>

**Comment by mapx-** [comment]
`medibang.com##.mdbnAdBlock`

You could report it to easylist repository

@ryanbr
