### ISSUE TITLE
novinky.cz: breakage

### ISSUE THREAD

**Issue by jgottvald** [uBlockOrigin/uAssets#17117]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.novinky.cz/`

### Category

breakage

### Description

Pictures and videos are not displayed correctly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obrazek](https://user-images.githubusercontent.com/30318592/224325522-34f5a386-5fd9-49f9-884f-7a726138e1d2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 86174
  cosmetic: 39532
  scriptlet: 17444
  html: 902
listset (total-discarded, last-updated): 
  default: 
    user-filters: 12-0, never
    ublock-filters: 33700-39, now
    ublock-badware: 4675-0, now
    ublock-privacy: 338-0, now
    ublock-abuse: 78-0, now
    ublock-unbreak: 1921-0, now
    easylist: 63808-581, now
    easyprivacy: 31035-1772, now
    urlhaus-1: 6564-0, now
    plowe-0: 3756-2, now
    CZE-0: 737-0, now
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 273 ms (selfie)
  maxAssetCacheWait: 113 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    adform.net: 3
    google-analytics.com: 1
```
</details>

**Comment by Daxy7** [comment]
Caused by `novinky.cz##+js(abort-on-stack-trace, Math, inlineScript)` @ `uBlock Filters`
No issues detected when allowing it

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/68078eddc1b3301709f482d70e5aac36983ac95c

**Comment by jgottvald** [comment]
After the last update of the filters in my browser, the images and videos on this website are now displayed correctly.
Thank you!
