### ISSUE TITLE
[nsfw] streamadblocker.com: detection

### ISSUE THREAD

**Issue by savagegaming636** [uBlockOrigin/uAssets#17126]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://streamadblocker.com/v/xe9lrzOGXwHkJrO`

### Category

detection

### Description

The site detects the adblock and forces me to turn it off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 85524
  cosmetic: 39010
  scriptlet: 17024
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63470-43, 3d.19h.27m
    easyprivacy: 31019-1172, 3d.19h.26m
    plowe-0: 3755-929, 3d.19h.28m
    ublock-abuse: 78-0, 7d.16h.1m
    ublock-badware: 4681-114, 16h.22m
    ublock-filters: 31980-68, 16h.24m
    ublock-privacy: 287-1, 7d.16h
    ublock-quick-fixes: 385-21, 21h.34m
    ublock-unbreak: 1910-51, 16h.23m
    urlhaus-1: 6564-0, 21h.33m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 84 ms (selfie)
  maxAssetCacheWait: 58 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    adforcast.com: 1
    cdn4ads.com: 1
    chebecsunsack.com: 1
    cwqljsecvr.com: 1
    d3g5ovfngjw9bw.cloudfront.net: 1
    fizazdokts.com: 1
    yandex.ru: 1
    zimpolo.com: 1
```
</details>

**Comment by ghajini** [comment]
reproduced at 
nsfw `https://streamadblocker.com/e/xe9lrzOGXwHkJrO`

fixed with
https://github.com/uBlockOrigin/uAssets/commit/ce2bfb4a0daca218368a8ce40d6ba4347acfc60b
