### ISSUE TITLE
amedia.online: ads

### ISSUE THREAD

**Issue by Forgant** [uBlockOrigin/uAssets#17121]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://amedia.online/1218-moja-gerojskaja-akademija-6.html`

### Category

ads

### Description

Lots if not all ads still on the site. I guess these ads provided by Yandex.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<![image](https://user-images.githubusercontent.com/127584633/224469478-8c96eca1-98ea-4d03-8bc3-3660ecd94796.png)>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 85675
  cosmetic: 39024
  scriptlet: 17016
  html: 894
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32806-98, 20m
    ublock-badware: 4685-0, 22m
    ublock-privacy: 336-0, 6d.13h.11m
    ublock-abuse: 78-0, 6d.13h.10m
    ublock-unbreak: 1921-21, 21m
    ublock-quick-fixes: 384-0, 18m
    easylist: 63613-157, 12h.29m
    easyprivacy: 31025-1786, 12h.30m
    urlhaus-1: 6592-0, 19m
    plowe-0: 3755-351, 5d.16h.21m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4377 ms (selfie)
  maxAssetCacheWait: 3296 ms
popupPanel: 
  blocked: 45
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
    jsdelivr.net: 2
    mangavost.org: 2
    yadro.ru: 1
    yandex.ru: 37
    yastatic.net: 1
```
</details>

**Comment by ghajini** [comment]
This is a russian website. Enable **RUS: RU AdList**
