### ISSUE TITLE
atomohd.chat: detection

### ISSUE THREAD

**Issue by helpman** [uBlockOrigin/uAssets#17128]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

after clicking links on `atomohd.chat`, the link protection service `acorta-enlace.com` shows a screen with "adblock detected" and ask you to shut it down and reload. even turning off ublock origin, still show the same popup

### URL(s) where the issue occurs.

`https://acorta-enlace.com/s.php?i=VTJGc2RHVmtYMTk0TVhJT1BRclhGcjJzKzBpUEZrdVB6cElhNXl6U1NRbW5XT1ZxMFduQ29nMU1ZazhjSkd0L3ZIRzNLTWp3QnVoaVphS3U0Sk1XVjFHTUNHbTVaMkgrTXVGWStURmxpOUVUNkxGcDhnYmRqWFlLWFFmd0NHYzNQd1JTZTJBVEROdlplWnRMS3Q1b1EyQWRRSzRoWkRTU2dtZytPMUYySzNOWTViL09nSmR4U3FPdHdVWEYxR1ZBMGIxbTRtejNSY29ybjhwcmdtV0ZOVzVCMmYrRDNoQm41Zkt6ZDd1ZUltTU1weHlyc3ZWZmUyU0JqMFNkL0E3Sw==`

### Screenshot(s)

![Clipboard01](https://user-images.githubusercontent.com/6162124/224503721-d4cdcde9-5b8b-41b8-8347-fd98a78aba72.jpg)

### Notes

refreshed filters. also tried disabling ublock for `acorta-enlace.com`

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 88658
  cosmetic: 44938
  scriptlet: 17638
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63872-44, 1m
    easyprivacy: 31041-1174, 1m
    plowe-0: 3757-932, 1m
    spa-0: 3509-11, 1m
    spa-1: 5104-192, 1m
    ublock-abuse: 78-0, 1m
    ublock-badware: 4686-114, 1m
    ublock-filters: 32808-115, 1m
    ublock-privacy: 290-1, now
    ublock-quick-fixes: 368-24, now
    ublock-unbreak: 1920-42, now
    urlhaus-1: 6629-0, now
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 30 redacted]
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 50254 ms (selfie)
  maxAssetCacheWait: 579 ms
```
</details>

**Comment by mapx-** [comment]
it's another domain too

add
```
@@||pagead2.googlesyndication.com^$xhr,domain=finanzasdomesticas.com
@@||googleadapis.l.google.com^$xhr,domain=finanzasdomesticas.com
```

**Comment by helpman** [comment]
still there. updated filters, popup still shows :(

**Comment by mapx-** [comment]
`finanzasdomesticas` page ? 

`acorta-enlace.com` page ?

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by helpman** [comment]
cookies cleared, cache cleared, ubo with default settings, filter list updated, chrome's blockers disabled, reset computer, using google's dns, still the same.
atomohd.cloud open links on atomtt.com, the links there point to acorta-enlace.com which shows different domains to protect links. (finanzasdomesticas.com, pequenutricion.com and seguridadinformaticahoy.com) which shows a countdown to enable links or supposedly a couple ads to click, but those ads are never shown and you have to repeat until the countdown is shown.

**Comment by mapx-** [comment]
for now I have only 

`atomohd.cloud => atomtt.com => acorta-enlace.com => finanzasdomesticas.com => google`

I asked you: where / which page do you still have anti adblocking ?

**Comment by helpman** [comment]
the url shows acorta-enlace.com
but soemthing seems to be weird, as I uninstalled ublock on opera, and disabled adblock in opera... yet the same page is shown?
![Clipboard01](https://user-images.githubusercontent.com/6162124/224538104-161b8e9d-6f5b-488c-94a8-4f1252cd0f22.jpg)

**Comment by mapx-** [comment]
well, it's something in your system then .. 
however, it's insane using this "chain" of pages just to download some movie, did you try using torrents ?

**Comment by helpman** [comment]
actally that's what I need to get access to the torrent :( I can't find it in any tracker. Once the link protection is done, you don't need to do that for 24 hours. still jumps from one site to another and you need to close 4 tabs for each link, though :(
I have no idea what could be causing this :(

**Comment by mapx-** [comment]
send me a private message on reddit about what you want do find
( this user `https://www.reddit.com/user/ajaxmix` )

**Comment by detyso** [comment]
Use this script to skip that shortener 
https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/

**Comment by detyso** [comment]
> still there. updated filters, popup still shows :(

You can use this to skip the mega enlace and also the other Spanish shorteners https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/
