### ISSUE TITLE
mail.google.com: ads

### ISSUE THREAD

**Issue by alfvid** [uBlockOrigin/uAssets#17129]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mail.google.com/mail/u/0/`

### Category

Mailtrack Signature

### Description

Mailtrack is a tool I use to track receipts of emails. However when I remove the Mailtrack signature, Mailtrack has a popup for an advertisement to upgrade my plan. While I am ok with removing the Mailtrack signature with all emails I send, I am not ok with the Mailtrak popup that appears immediately after doing this. I can temporarily block this popup using "enter element zapper mode" from UBlock Origin. However upon re-logging into gmail, the Mailtrack signature re-appears. I do not believe this violates the policy where "Circumventing a paywall is considered out of scope", as this is not considered a paywall. Additionally, I reviewed "uAssets" and did not see the issue listed there. If this post violates any other policies, please let me know before blocking me, as I am new to how both UWorld Origin and Github works and I'd be happy to correct any mistakes accordingly. Thank you!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/127621463/224504174-ac5f99db-0c6c-460c-ae92-0d4432f2e8aa.png">

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 85555
  cosmetic: 39013
  scriptlet: 17041
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63466-43, 5d.22h.8m
    easyprivacy: 31015-1172, 5d.6h.2m
    plowe-0: 3749-928, 11d.21h.44m
    ublock-abuse: 79-0, 12d.23h.7m
    ublock-badware: 4676-114, 1d.48m
    ublock-filters: 32031-68, 1d.47m
    ublock-privacy: 276-1, 12d.23h.6m
    ublock-quick-fixes: 383-19, 12h.45m
    ublock-unbreak: 1910-51, 1d.46m
    urlhaus-1: 6592-0, 12h.44m
filterset (user): [empty]
switchRuleset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 55924 ms (selfie)
  maxAssetCacheWait: 143 ms
popupPanel: 
  blocked: 483
  no-popups: true
  blockedDetails: 
    google.com: 453
    google-analytics.com: 7
    googleusercontent.com: 5
    mailtrack.io: 14
    nbme.org: 4
```
</details>

**Comment by iam-py-test** [comment]
> I can temporarily block this popup using "enter element zapper mode" from UBlock Origin. 

You will need to [use the Element Picker](https://github.com/uBlockOrigin/uBlock-issues/wiki/Element-picker)

**Comment by krystian3w** [comment]
> until you reopen/reload the page

IMO mailtrack can detect broken dom by Zapper and reinsert pop-up after second delete credits from e-mail in writing mode.

**Comment by mapx-** [comment]
@alfvid try the filters above, use the element picker.

**Comment by alfvid** [comment]
> 

Thank you, this worked! And yes, that extension is what I installed.

**Comment by alfvid** [comment]
> 

thank you!

**Comment by alfvid** [comment]
> @alfvid try the filters above, use the element picker.

thank you! This worked!
