### ISSUE TITLE
client-telemetry.roblox.com: privacy

### ISSUE THREAD

**Issue by Zarq0** [uBlockOrigin/uAssets#17120]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://client-telemetry.roblox.com/`

### Category

privacy

### Description

Endpoint `https://client-telemetry.roblox.com/` is used to send telemetry data to Roblox and is not blocked by uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 85602
  cosmetic: 39018
  scriptlet: 17044
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63585-44, 1d.9h.8m
    easyprivacy: 31025-1172, 1d.9h.7m
    plowe-0: 3753-930, 7d.9h.32m
    ublock-abuse: 79-0, 8d.8h.52m
    ublock-badware: 4640-114, 2d.22h.33m
    ublock-filters: 32021-74, 1d.19h.25m
    ublock-privacy: 284-2, 8d.8h.51m
    ublock-quick-fixes: 383-21, 16h.16m
    ublock-unbreak: 1910-51, 1d.19h.24m
    urlhaus-1: 6564-0, 9h.28m
filterset (user): [empty]
trustedset: 
  added: [array of 20 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4980 ms (selfie)
  maxAssetCacheWait: 321 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe how to reproduce the issue in more details?

**Comment by gorhill** [comment]
> `https://client-telemetry.roblox.com/`

This is not a valid webpage demonstrating the issue. Provide an actual webpage making use of `client-telemetry.roblox.com`, we can't just create filters without actual issues with real world cases.

**Comment by garry-ut99** [comment]
By the way:
- it has been added 2 weeks ago into "AdGuard Tracking Protection filter": https://github.com/AdguardTeam/AdguardFilters/commit/5af699072317599e8274ead9991589fd5e611e5b, so maybe @piquark6046 can "Provide an actual webpage"
- also it was  added 1 year and 9 months ago into "NoTrack Tracker Blocklist" 
https://gitlab.com/quidsup/notrack-blocklists/-/commit/d5482450e10b506f76f9199b89cc96842d6ff5c1, 
but as a host-file, thus maybe the intention was to block telemetry only from the application, and not from the webpage, anyway maybe @ quidsup can provide explanation and provide "Provide an actual webpage" (btw I dunno how to ping a nick from `gitlab` and not from `github`, perhaps there is a way, but I've not been investigated so far)

**Comment by piquark6046** [comment]
I saw the domain in AdGuard Home during my family plays Roblox game.

**Comment by garry-ut99** [comment]
For example here? : `https://www.roblox.com/games/4769825225/SQUID-GAME-ONLINE`
