### ISSUE TITLE
[nsfw] megaup.net: detection

### ISSUE THREAD

**Issue by PegHorse** [uBlockOrigin/uAssets#17125]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/1K4er/Fire_Emblem_Warriors_(NSP)(US)(Base_Game).part1.rar`

### Category

detection

### Description

![image](https://user-images.githubusercontent.com/7678316/224488228-c21675b3-9dee-44bb-9c6f-30b59b024f2d.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 104125
  cosmetic: 172879
  scriptlet: 24765
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
    ublock-badware: null
    urlhaus-1: null
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 13h.36m
    adguard-annoyance: 64743-111, 3d.1h.50m
    fanboy-annoyance: 81841-5489, 2d.2h.33m
    fanboy-cookiemonster: 46030-46030, 2d.2h.34m
    fanboy-thirdparty_social: 68-19, 2d.2h.35m
    ublock-annoyances: 4845-214, 3d.1h.51m
  default: 
    user-filters: 12-0, never
    FRA-0: 30065-34, 3d.1h.52m
    easylist: 63470-285, 3d.19h.16m
    easyprivacy: 31019-1576, 3d.19h.15m
    ublock-abuse: 79-1, 11d.3h.55m
    ublock-filters: 32055-540, 3d.1h.49m
    ublock-privacy: 276-7, 11d.3h.55m
    ublock-quick-fixes: 371-24, 13h.37m
    ublock-unbreak: 1905-57, 3d.1h.48m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 44 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3341 ms (selfie)
  maxAssetCacheWait: 297 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    megaup.net: 1
    a-ads.com: 1
    altowriestwispy.com: 1
    bidgear.com: 1
    dmmzkfd82wayn.cloudfront.net: 2
    googletagmanager.com: 1
    keydawnawe.com: 1
    s3.amazonaws.com: 1
```
</details>

**Comment by PegHorse** [comment]
Solved after purging the caches many times.

**Comment by iam-py-test** [comment]
> ```yml
>     https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 13h.36m
> ```

This list hasn't been updated in years; you probably want to remove it, as it will cause more problems than it solves
> ```yml
>   removed: 
>    plowe-0: null
>    ublock-badware: null
>    urlhaus-1: null
> ```

You have disabled three default filterlists (Peter Lowe's, uBlock Origin's badware list, and URLHaus/Online Malicious URL Blocklist). It is recommended you do not disable default lists:
> - [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
