### ISSUE TITLE
realtime-chart.info: detection

### ISSUE THREAD

**Issue by ts-ts** [uBlockOrigin/uAssets#17122]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://realtime-chart.info/`

### Category

detection

### Description

µBO is detected and part of the site disappears.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 102
filterset (summary): 
  network: 105524
  cosmetic: 75250
  scriptlet: 34959
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    JPN-1: null
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt: 50608-246, 9d.7h.45m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/fix_filter.txt: 43-0, 9h.48m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/ichigo_filter.txt: 1485-323, 9h.42m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/kame_filter.txt: 145-5, 9h.45m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/kotori_filter.txt: 76-1, 9h.41m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/kujira_filter.txt: 14-4, 9h.46m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/mochi_filter.txt: 1374-203, 9h.47m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/mochi_filter_extended.txt: 469-63, 9h.43m
    https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/negi_filter.txt: 200-8, 9h.44m
    adguard-generic: 68340-3885, 2d.2h.55m
    ublock-annoyances: 4796-123, 3d.9h.50m
  default: 
    user-filters: 28-0, never
    easylist: 63775-22505, 1d.11h.4m
    easyprivacy: 31035-5380, 1d.11h.3m
    ublock-abuse: 79-7, 11d.10h.33m
    ublock-badware: 4045-1820, 3d.9h.48m
    ublock-filters: 31519-9569, 3d.9h.51m
    ublock-privacy: 276-94, 11d.10h.32m
    ublock-quick-fixes: 359-41, 9h.49m
    ublock-unbreak: 1909-216, 3d.9h.47m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5331 ms (selfie)
  maxAssetCacheWait: 293 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googlesyndication.com: 1
    googletagmanager.com: 1
    xn--jx2a33n.com: 1
```
</details>

**Comment by mapx-** [comment]
@Yuki2718 japanese site ?

**Comment by Yuki2718** [comment]
> * [x]  I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

>   added: 
>     https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt: 50608-246, 9d.7h.45m
>     https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/fix_filter.txt: 43-0, 9h.48m
>     https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/ichigo_filter.txt: 1485-323, 9h.42m
>     https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/kame_filter.txt: 145-5, 9h.45m
>     https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/kotori_filter.txt: 76-1, 9h.41m
>     https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/kujira_filter.txt: 14-4, 9h.46m
>     https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/mochi_filter.txt: 1374-203, 9h.47m
>     https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/mochi_filter_extended.txt: 469-63, 9h.43m
>     https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/negi_filter.txt: 200-8, 9h.44m

`https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt` is deprecated, see anouncement on my homepage. I don't see problem with uBO default settings.

**Comment by ts-ts** [comment]
The filter list is used by default when installing the extension.
After using it for a certain period of time, a captcha-like message will appear and all content will become invisible.

uBlock Origin 1.57.0
![error](https://github.com/uBlockOrigin/uAssets/assets/37338372/5dc48840-6a46-4088-a51f-7fa36358bbef)

フィルターリストは拡張機能インストール時のデフォルトで使用しています。一定時間使用していると、キャプチャのようなメッセージが表示され、すべてのコンテンツが見えなくなります。

**Comment by Yuki2718** [comment]
Still untable to reproduce. Is it possible you block `googlesyndication.com` by e.g. DNS or browser's tracking protection?

**Comment by ts-ts** [comment]
Thank you for your reply!
I'm using centbrowser as my browser, but I don't think it's blocking googlesyndication.com.

Since the chart is hidden when a certain number of ads are blocked, is adding the following to My Filters a solution? (Please tell me if there are any grammatical mistakes)

　@@realtime-chart.info||googleads.g.doubleclick.net


返信ありがとうございます。
ブラウザはcentbrowserを使っていますが、おそらく googlesyndication.com をブロックしていないと思います。

広告を一定数ブロックするとチャートが非表示になることから、下記をマイフィルターに追加することは解決策になりますか？(文法的に間違っていれば教えて下さい)

![世界の株価_設定](https://github.com/uBlockOrigin/uAssets/assets/37338372/7488dd68-459f-4609-adca-d357fe786f35)

**Comment by Yuki2718** [comment]
@ts-ts
```
@@||googleads.g.doubleclick.net/pagead/ads?$subdocument,domain=realtime-chart.info
```
を試してみてください。

**Comment by ts-ts** [comment]
修正ありがとうございます。
マイフィルターに追記して、当該サイトを閲覧してみます。
もし、再度チャートが非表示になった場合はコメントします。
ありがとうございました。
