### ISSUE TITLE
spotify-downloader.com: detection

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17139]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://spotify-downloader.com/`

### Category

detection

### Description

Reproduce:
Enter Spotify track, sample: `https://open.spotify.com/track/24BYTj1tb5ovZcnIbtdTYD?si=a7e85958b64948b5`
Click [Start verification](https://user-images.githubusercontent.com/91396482/224545067-eefb3bd4-1eab-489f-8dcb-ec1da9f66675.png)
Taken to `https://digworm.io/` which displays [Adblocker detected!](https://user-images.githubusercontent.com/91396482/224544940-01d6ead3-8a59-4c89-82c6-3ca4beabf7e6.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 77885
  cosmetic: 42384
  scriptlet: 20914
  html: 1060
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 5h.24m
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1487-0, 5h.24m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 5h.24m
    ublock-annoyances: 4811-4, 5h.24m
  default: 
    user-filters: 1569-13, never
    ublock-filters: 33655-69, 3h.54m
    ublock-badware: 4690-0, 5h.24m
    ublock-privacy: 339-0, 5h.24m
    ublock-abuse: 78-0, 5h.24m
    ublock-unbreak: 1933-0, 5h.24m
    ublock-quick-fixes: 361-0, 5h.24m
    easylist: 63896-244, 5h.24m
    easyprivacy: 31045-2160, 5h.24m
filterset (user): [array of 597 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 337 ms (selfie)
  maxAssetCacheWait: 151 ms
  unsuspendAfter: 147 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    cloudflareinsights.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by iam-py-test** [comment]
```adblock
@@||digworm.io/adgpt.js$xhr,1p
```
fixes the issue

**Comment by Daxy7** [comment]
> Not relevant to this issue, but you have disabled two default filterlists (Peter Lowe's and URLHaus). It is recommended you enable them. 

I don't find them useful imo.

**Comment by iam-py-test** [comment]
Ok, it's your choice (and completely irrelevant to this issue). Just wanted you to be aware that disabling Peter Lowe's list might decrease your protection from trackers/ads which aren't covered yet by uBo's other default lists.

**Comment by Daxy7** [comment]
> @@||digworm.io/adgpt.js$xhr,1p

A 10 second count down appeared and the verification completed. Issue resolved

**Comment by Daxy7** [comment]
is `@@||digworm.io/adgpt.js$xhr,1p` being added? is there some complication down the line with the filter?
