### ISSUE TITLE
atomohd.cloud: ads

### ISSUE THREAD

**Issue by MandiYang** [uBlockOrigin/uAssets#17130]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [ ] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://atomohd.cloud/descargar/peliculas-castellano/wicked-witches-2023-/blurayrip-ac3-5-1/`

### Category

ads

### Description

Leftovers of ad, used element picker and choosed this and worked:

`atomohd.cloud##[src="/pctn/library/content/template/images/banners/n/HBOMAX-900x300.jpg"]`

I tested `||atomohd.cloud/pctn/library/content/template/images/banners/n/HBOMAX-900x300.jpg` but it doesn't seem to work

Note that I am a newbie

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

![Screenshot from 2023-03-11 19-00-23](https://user-images.githubusercontent.com/64307609/224504416-b270a1fe-1b37-4451-a96c-63e4d8f992d2.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 139613
  cosmetic: 42795
  scriptlet: 18470
  html: 923
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1912-0, 5h.12m
    curben-phishing: 51868-20, 5h.12m
    SWE-1: 4312-2, 5h.12m
  default: 
    user-filters: 1-0, never
    ublock-filters: 33653-70, 5h.9m
    ublock-badware: 4690-0, 5h.12m
    ublock-privacy: 339-1, 5h.12m
    ublock-abuse: 78-0, 5h.12m
    ublock-unbreak: 1931-0, 5h.12m
    ublock-quick-fixes: 365-0, 5h.12m
    easylist: 63872-592, 5h.12m
    easyprivacy: 31040-1778, 5h.12m
    urlhaus-1: 6629-0, 5h.12m
    plowe-0: 3757-3, 5h.12m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1291 ms (selfie)
  maxAssetCacheWait: 343 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    celeritascdn.com: 1
    pengobyzant.com: 1
```
</details>

**Comment by krystian3w** [comment]
Compatible with EasyList, you can prove "ad reinsertion" to cover in filters*.txt form uAssets?

**Comment by krystian3w** [comment]
Also "`||atomohd.cloud/pctn/library/content/template/images/banners/n/HBOMAX-900x300.jpg`" after force refresh page (CTRL + F5 or CTRL + F) or in incognito/private session.

**Comment by mapx-** [comment]
`||atomohd.cloud/*/banners$image`

or 

`atomohd.cloud##.ads`

@ryanbr
