### ISSUE TITLE
lavanguardia.com: ads

### ISSUE THREAD

**Issue by learn32** [uBlockOrigin/uAssets#17135]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lavanguardia.com/politica/20230311/8817392/nord-stream-mas-misterio.html`

### Category

ads

### Description

Many entries in https://www.lavanguardia.com pop messages not allowing read site content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230311-091006](https://user-images.githubusercontent.com/127590261/224532529-805ba521-b440-412a-95cf-2ab964cd0ddb.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox Mobile: 110
filterset (summary): 
  network: 87277
  cosmetic: 28854
  scriptlet: 17033
  html: 924
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33083-266, 2d.11h.47m
    ublock-badware: 4643-0, 2d.11h.19m
    ublock-privacy: 338-1, 1d.10h.24m
    ublock-abuse: 78-0, 1d.10h.25m
    ublock-unbreak: 1926-0, 2d.11h.20m
    adguard-mobile: 8529-120, 2d.11h.18m
    easylist: 63789-17439, 2d.12h.26m
    easyprivacy: 31025-1776, 2d.12h.8m
    urlhaus-1: 6695-0, 4h.47m
    plowe-0: 3757-2, 11h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1448 ms (selfie)
  maxAssetCacheWait: 783 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    adnxs-simple.com: 2
    adsafeprotected.com: 2
    amazon-adsystem.com: 1
    criteo.com: 1
    doubleclick.net: 1
    google-analytics.com: 2
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    newsroom.bi: 3
    permutive.app: 1
    permutive.com: 1
    richaudience.com: 3
    scorecardresearch.com: 1
    sensic.net: 1
    smartadserver.com: 3
```
</details>

**Comment by mapx-** [comment]
I see a paywall, not ads. Out of scope of uAssets.
