### ISSUE TITLE
tii.la: detection

### ISSUE THREAD

**Issue by AndresMinakata** [uBlockOrigin/uAssets#17132]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tii.la/N3QzyrPMdy`

### Category

detection

### Description

Detects Ublock and doesn't let me procede until I desactivate it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 88129
  cosmetic: 44530
  scriptlet: 17331
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 63466-43, 5d.10h.9m
    easyprivacy: 31025-1172, 3d.19m
    plowe-0: 3750-929, 11d.12h.41m
    spa-0: 3509-10, 5h.33m
    spa-1: 5104-192, 3d.18m
    ublock-abuse: 78-0, 3d.21m
    ublock-badware: 4645-114, 3d.17m
    ublock-filters: 32021-105, 3d.16m
    ublock-privacy: 289-1, 3d.20m
    ublock-quick-fixes: 363-19, 5h.32m
    ublock-unbreak: 1910-41, 3d.15m
    urlhaus-1: 6629-0, 5h.31m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 26 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3873 ms (selfie)
  maxAssetCacheWait: 120 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    tii.la: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    netpub.media: 4
    pubfuture.com: 1
```
</details>

**Comment by Daxy7** [comment]
Unable to reproduce. I got to the `mega.nz` link just fine

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
