### ISSUE TITLE
1337x - Ublocks  blocks avatar images on some forums

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#17138]
### Discussed in https://github.com/uBlockOrigin/uAssets/discussions/17137

<div type='discussions-op-text'>

<sup>Originally posted by **s1raz1** March 12, 2023</sup>
For a while now ublock blocks avatar images on  the  site 1337x  while also making it so i cant change pages if there are more than 1 page of comments.   I dont know if this is a bug or something in my options, i dont really fiddle with the settings so i have  the default ones.</div>

**Comment by mapx-** [comment]
@s1raz1 provide exact example link

**Comment by s1raz1** [comment]
[FireShot Capture 139 - Download CHRIS ROCK -SELECTIVE OUTRAGE (2023) Torrent - 1337x - 1337x.to.pdf](https://github.com/uBlockOrigin/uAssets/files/10953720/FireShot.Capture.139.-.Download.CHRIS.ROCK.-SELECTIVE.OUTRAGE.2023.Torrent.-.1337x.-.1337x.to.pdf) 

[FireShot Capture 140 - Download CHRIS ROCK -SELECTIVE OUTRAGE (2023) Torrent - 1337x - 1337x.to.pdf](https://github.com/uBlockOrigin/uAssets/files/10953726/FireShot.Capture.140.-.Download.CHRIS.ROCK.-SELECTIVE.OUTRAGE.2023.Torrent.-.1337x.-.1337x.to.pdf)

**Comment by mapx-** [comment]
update all filter lists and test again

**Comment by s1raz1** [comment]
The auto update list is ticked on, there is nothing to update.

**Comment by mapx-** [comment]
**update all filter lists => meaning "purge all caches" manually, then click "update now"**
