### ISSUE TITLE
acorta-enlace.com: detection

### ISSUE THREAD

**Issue by helpman** [uBlockOrigin/uAssets#17136]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://acorta-enlace.com/`

### Category

detection

### Description

it was marked as solved, yet it still shows the adblock detected when clicking on links from atomohd.cloud (it changes domains frequently), and no matter what I do, that popup keeps showing. 
using latest chrome, disabled every option in chrome for popups and invasive ads, and disabled ublock origin. refreshed the filter list, same result. that detection keeps showing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 88747
  cosmetic: 44798
  scriptlet: 17644
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63745-44, 8m
    easyprivacy: 31045-1174, 8m
    plowe-0: 3757-932, 8m
    spa-0: 3509-11, 8m
    spa-1: 5104-191, 8m
    ublock-abuse: 78-0, 8m
    ublock-badware: 4686-114, 8m
    ublock-filters: 32819-116, 8m
    ublock-privacy: 291-1, 8m
    ublock-quick-fixes: 363-22, 8m
    ublock-unbreak: 1924-42, 8m
    urlhaus-1: 6695-0, 8m
filterset (user): [empty]
trustedset: 
  added: [array of 30 redacted]
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 50254 ms (selfie)
  maxAssetCacheWait: 579 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
continue in the old issue
https://github.com/uBlockOrigin/uAssets/issues/17128
