### ISSUE TITLE
chat.d-id.com: breakage

### ISSUE THREAD

**Issue by EmirLogas** [uBlockOrigin/uAssets#17131]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chat.d-id.com/`

### Category

breakage

### Description

preventing the site from loading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 85649
  cosmetic: 39009
  scriptlet: 17037
  html: 894
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32852-57, 1d.23h.53m
    ublock-badware: 4659-0, 1d.23h.52m
    ublock-privacy: 339-0, 1h.2m
    ublock-abuse: 78-0, 1h.1m
    ublock-unbreak: 1922-0, 1d.23h.51m
    ublock-quick-fixes: 357-0, 8h.56m
    easylist: 63585-571, 2d.7h.55m
    easyprivacy: 31028-1768, 2d.7h.54m
    urlhaus-1: 6592-0, 8h.55m
    plowe-0: 3749-2, 12d.5h.24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 210 ms (selfie)
  maxAssetCacheWait: 152 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    d-id.com: 1
    googletagmanager.com: 1
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
Is this enough ?

`@@||chat.d-id.com/assets/mixpanel.$script,1p`

**Comment by Daxy7** [comment]
account required also

**Comment by EmirLogas** [comment]
![image](https://user-images.githubusercontent.com/76751818/224536301-a6684638-6d38-4b06-8810-d40a965a09be.png)
This is what happens to me when I log in, a blank screen.

**Comment by EmirLogas** [comment]
![image](https://user-images.githubusercontent.com/76751818/224541605-a08934d0-2dcd-45d2-818f-915eb49b4d7b.png)

I solved the problem by adding this line. Updating the filters did not work. Thanks for the help.
