### ISSUE TITLE
prismascans.net: ads

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#17142]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://prismascans.net/`

### Category

ads

### Description

Leftover button to close teaser, same goes to `prismahentai.com`(NSFW),`cerisescan.com`, `reaperscans.net`,`sinensisscans.com`,`asurascans.com`,`void-scans.com`,`realmscans.com`,`yugenmangas.com.br`,`randomscans.com`,`arthurscan.xyz`.

Note: I'm using this filter below since 2022-11-23 to hide the Close button on all the sites that got this, and it never gave me any problems, i don't think any site would have an element like this for any reason other than advertisement
`*###close-teaser`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/70459964/224522132-c417d281-6e01-4568-9902-b8825514c04e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 140983
  cosmetic: 201673
  scriptlet: 39344
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38353-3477, 11h.42m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2140-1, 11h.42m
    adguard-annoyance: 64877-248, 11h.42m
    adguard-generic: 68405-1262, 11h.42m
    adguard-spyware-url: 939-133, 11h.47m
    fanboy-annoyance: 81897-5529, 11h.42m
    ublock-annoyances: 4850-246, 11h.42m
  default: 
    user-filters: 34-4, never
    easylist: 63872-757, 11h.47m
    easyprivacy: 31041-12348, 11h.47m
    plowe-0: 3757-1014, 11h.47m
    spa-1: 5104-79, 11h.42m
    ublock-abuse: 78-0, 11h.47m
    ublock-badware: 4686-309, 11h.47m
    ublock-filters: 32800-4055, 11h.47m
    ublock-privacy: 290-65, 11h.47m
    ublock-quick-fixes: 368-49, 11h.47m
    ublock-unbreak: 1920-110, 11h.47m
    urlhaus-1: 6629-0, 11h.47m
filterset (user): [array of 27 redacted]
switchRuleset: 
  added: [array of 2 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 109 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 719 ms
  maxAssetCacheWait: 575 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    googlesyndication.com: 3
    gravatar.com: 2
    storage.googleapis.com: 12
```
</details>

**Comment by mapx-** [comment]
or

`##.adclose`

However, you should report it at easylist repository

@ryanbr
