### ISSUE TITLE
9anime.win: popups

### ISSUE THREAD

**Issue by kerryzx** [uBlockOrigin/uAssets#17146]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://9anime.win/`

### Category

popups

### Description

Website opens redirects to other streaming websites whenever something is clicked on a page (with content paying).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://ibb.co/MZ4CyZ5

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 94076
  cosmetic: 112232
  scriptlet: 19867
  html: 905
listset (total-discarded, last-updated): 
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 905-0, 10m
    adguard-spyware-url: 939-4, 10m
    fanboy-annoyance: 81925-207, 10m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33674-125, 10m
    ublock-badware: 4714-0, 10m
    ublock-privacy: 340-0, 10m
    ublock-abuse: 78-0, 10m
    ublock-unbreak: 1934-0, 10m
    ublock-quick-fixes: 366-0, 10m
    easylist: 63746-517, 10m
    easyprivacy: 31049-1962, 10m
    urlhaus-1: 6649-0, 10m
    plowe-0: 3757-2, 10m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 495 ms (selfie)
  maxAssetCacheWait: 631 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    amung.us: 4
    anigogo.net: 2
    effectivecreativeformats.com: 1
    googletagmanager.com: 3
    jwpcdn.com: 2
    jwpltx.com: 2
    jwpsrv.com: 2
    psychalwamble.com: 1
    yandex.ru: 4
```
</details>

**Comment by Daxy7** [comment]
hmm, I don't have popups, geo specific?

**Comment by ghajini** [comment]
update filters & report back if still ads
