### ISSUE TITLE
[NSFW] watchporn.to: popups

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#17149]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

NSFW
`https://watchporn.to/`

### Category

popups

### Description

Popup while playing video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox Mobile: 110
filterset (summary): 
  network: 87481
  cosmetic: 28953
  scriptlet: 17093
  html: 927
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33037-285, 2d.6h.39m
    ublock-badware: 4664-0, 2d.6h.38m
    ublock-privacy: 336-1, 10d.9h.25m
    ublock-abuse: 79-0, 10d.9h.25m
    ublock-unbreak: 1926-0, 2d.6h.37m
    ublock-quick-fixes: 364-0, 46m
    adguard-mobile: 8533-120, 2d.6h.36m
    easylist: 63745-17444, 4h.47m
    easyprivacy: 31025-1775, 4d.9h.16m
    urlhaus-1: 6795-0, 45m
    plowe-0: 3750-2, 10d.9h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3544 ms (selfie)
  maxAssetCacheWait: 1277 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    watchporn.to: 2
    exacdn.com: 2
    googletagmanager.com: 1
    variableexternal.com: 1
    xlirdr.com: 1
    xlivrdr.com: 2
```
</details>

**Comment by ghajini** [comment]
unable to reproduce

- backup your ublock settings
- reset ublock origin to default settings
- restart the browser
- go to ublock settings
- ensure all **default** ublock filter lists are checked
- update filter lists(`https://youtu.be/Onr0frormCU`)
- close all tabs
- restart the browser
- now try if popups appear again

**Comment by garry-ut99** [comment]
>  * [x]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

You didn't, a duplicate of https://github.com/uBlockOrigin/uAssets/issues/11210

**Comment by dportvine** [comment]
<details>
<summary>Video NSFW</summary>


https://github.com/uBlockOrigin/uAssets/assets/111344219/13d4d0cf-1597-4ef8-8456-69fbe69f3013
</details>

Also i see my ip in cookies.

<details>
<summary>Screen</summary>

![2023-07-26_110539](https://github.com/uBlockOrigin/uAssets/assets/111344219/055aca6d-697b-4ccf-bcd4-9000d11db80f)
</details>

<details>

```yaml
uBlock Origin: 1.51.1b3
Firefox: 115
filterset (summary):
 network: 121078
 cosmetic: 128234
 scriptlet: 25125
 html: 1222
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26291-168, 6m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1651-0, 6m
  fanboy-cookiemonster: 47815-458, 6m
  ublock-annoyances: 5267-222, 6m
  RUS-0: 39638-28, 6m
  ublock-cookies-easylist: 215-0, 6m
 default:
  user-filters: 0-0, never
  ublock-filters: 34994-134, 7m
  ublock-badware: 7528-2, 7m
  ublock-privacy: 479-1, 7m
  ublock-unbreak: 2146-6, 7m
  ublock-quick-fixes: 260-0, 6m
  easylist: 69100-829, 6m
  easyprivacy: 33352-1110, 6m
  urlhaus-1: 6330-0, 6m
  plowe-0: 3720-8, 6m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 842 ms (selfie)
 maxAssetCacheWait: 378 ms
popupPanel:
 blocked: 7
 network:
  watchporn.to: 1
  googletagmanager.com: 1
  troubled-stress.com: 1
  wpadmngr.com: 1
  xlirdr.com: 1
  xlivrdr.com: 2
 extended:
  ##+js(set-constant, flashvars.protect_block, )
```
</details>

**Comment by adblockenjoyer** [comment]
`NSFW: https://watchporn.to/video/156764/cory-chase-in-make-up-trip-with-step-mom-tabooheat/`

`watchporn.to##+js(prevent-setTimeout, offsetWidth)` breaks player

**Comment by stephenhawk8054** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/9a1dbc6eddb6cc7d639f215ac0fba3f732d5f388
