### ISSUE TITLE
hwzone.co.il: detection

### ISSUE THREAD

**Issue by Sarm1X** [uBlockOrigin/uAssets#17147]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hwzone.co.il/`

### Category

detection

### Description

The site undergo some changes and after that i keep getting a popup of "please disable your adblock to keep browsing this site" anti adblocker..

https://user-images.githubusercontent.com/17095848/224577543-fae71c89-5991-4f04-9a91-415a58f91713.png

### Screenshot(s)

https://user-images.githubusercontent.com/17095848/224577562-dce7d99b-3d9a-4d1e-9a92-1250fc759da5.png

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 114328
  cosmetic: 98150
  scriptlet: 23200
  html: 1055
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 6h.9m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38353-3721, 1d.1h.10m
    adguard-annoyance: 64880-889, 1d.1h.14m
    ublock-annoyances: 4811-4, 1d.6h.22m
    ISR-0: 1680-0, 6h.11m
  default: 
    user-filters: 70-8, never
    ublock-filters: 32793-65, 1d.1h.13m
    ublock-badware: 4690-0, 1d.1h.12m
    ublock-privacy: 338-0, 5d.6h.32m
    ublock-abuse: 78-0, 5d.6h.31m
    ublock-unbreak: 1931-0, 1d.1h.11m
    easylist: 63470-599, 5d.6h.28m
    easyprivacy: 31023-12687, 5d.6h.27m
    urlhaus-1: 6649-0, 6h.10m
    plowe-0: 3755-2, 5d.6h.30m
    ublock-quick-fixes: 365-0, 6h.8m
filterset (user): [array of 70 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    edge-scheme
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 237 ms (selfie)
  maxAssetCacheWait: 377 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    cloudflareinsights.com: 2
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    skimresources.com: 2
    themeruby.com: 1
```
</details>

**Comment by ghajini** [comment]
@Hebrew-uBO-User
can you reproduce this?

**Comment by Sarm1X** [comment]
@ghajini Issue fixed after second time purging all filters and forcing update.
According to the other discussion I have on Reddit, a user found that this filter is blocking the popup

This filter in uBlock filters is preventing the pop-up:
hwzone.co.il##+js(nostif, site-access-popup)

You can close this case guys, thank you!

**Comment by Sarm1X** [comment]
Hey guys, I am re-opening this case as this issue came back.
Anyone can look a deeper look into the matter?

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
