### ISSUE TITLE
lamda-academy.openu.ac.il: breakage

### ISSUE THREAD

**Issue by quartzbear** [uBlockOrigin/uAssets#17156]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This is a website for academic books, with some sort of graphical interface which is uBO does not seem to care for. 
Any time one tries to open a book, instead of a a book all you get is some gibberish at end of page.

When I disabled the extension or switched to a clean browser, the book displayed properly.

The problem happens at when selecting books from this website: [www.openu.ac.il](https://www.openu.ac.il/about/departments/publishinghouse/Pages/Lamda_for_Academic.aspx) or at the [OpenAthens ](https://en.wikipedia.org/wiki/OpenAthens) version of the site [www-openu-ac-il.eu1.proxy.openathens.net](https://www-openu-ac-il.eu1.proxy.openathens.net/about/departments/publishinghouse/Pages/Lamda_for_Academic.aspx).

When choosing a book, it leads you to a link such as `https://lamda-academy.openu.ac.il/lamda-ebooks/XXXXX/` or to the OpenAthens `https://lamda--academy-openu-ac-il.eu1.proxy.openathens.net/lamda-ebooks/XXXXX/` - both won't work with the extension.

I hope this was thorough enough.

### URL(s) where the issue occurs.

`https://lamda--academy-openu-ac-il.eu1.proxy.openathens.net/lamda-ebooks/10269c/`
`https://lamda-academy.openu.ac.il/lamda-ebooks/10269c/`

### Screenshot(s)

Here is the error caused by uBO:

https://user-images.githubusercontent.com/33700415/224712067-7696d936-0621-40e6-a91a-161b2becbb9a.jpg

Here is how it looks without uBO:
https://user-images.githubusercontent.com/33700415/224713089-8b2aaaca-24bc-4544-a151-da99630b441a.png

### uBO version

 Version 1.47.4

### Browser name and version

Firefox 110.0.1 (64-bit)

### Settings

<details>
```
uBlock Origin: 1.47.4

Firefox: 110

filterset (summary): 
  network: 85909
  cosmetic: 39053
  scriptlet: 17017
  html: 890

listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32807-56, 16h.40m
    ublock-badware: 4690-0, 16h.39m
    ublock-privacy: 323-0, 11d.18h.43m
    ublock-abuse: 79-0, 11d.18h.42m
    ublock-unbreak: 1934-0, 16h.41m
    ublock-quick-fixes: 360-0, 16h.38m
    easylist: 63813-577, 1d.20h.31m
    easyprivacy: 31035-1767, 1d.20h.30m
    urlhaus-1: 6649-0, 16h.37m
    plowe-0: 3755-2, 8d.20h.44m

filterset (user): [empty]
trustedset: 

  added: [array of 3 redacted]
modifiedUserSettings: [none]

modifiedHiddenSettings: [none]

supportStats: 

  allReadyAfter: 131 ms (selfie)
  maxAssetCacheWait: 59 ms

```
</details>
### Notes

Standard uBO installation. Site works without the extension with other extensions. 
An account is needed. If you don't have one available, I can supply one if that's safe.

**Comment by krystian3w** [comment]
Definitely https://github.com/uBlockOrigin/uAssets/labels/account%20required (subscription/prenuptial)

To avoid/exclude agresive html filtering then try open page in Brave/Vivaldi (or other Chromium like Edge, Opera or Google Chrome) = I mean page can use wrong encode character on server side (other than defined in html meta tag).

**Comment by quartzbear** [comment]
I tested it on Edge. It works fine without the extension, with uBO enabled it has the same error. Here is the logger output from edge:
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +5 | \|\|sentry.io^$3p | -- | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 3 | post | ping | `https://o1313669.ingest.sentry.io/api/6564067/envelope/?sentry_key=7573b90a7a0f4bb1ae7ff7423723f91e&sentry_version=7` |
| +3 | \|\|sentry.io^$3p | -- | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 3 | post | xhr | `https://o1313669.ingest.sentry.io/api/6564067/envelope/?sentry_key=7573b90a7a0f4bb1ae7ff7423723f91e&sentry_version=7` |
| +3 | \|\|sentry.io^$3p | -- | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 3 | post | xhr | `https://o1313669.ingest.sentry.io/api/6564067/envelope/?sentry_key=7573b90a7a0f4bb1ae7ff7423723f91e&sentry_version=7` |
| +1 | /static/analytics.js | -- | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 1 | get | script | `https://lamda--academy-openu-ac-il.eu1.proxy.openathens.net/lamda-ebooks/10269c/files/html/static/analytics.js?uni=01de1dbef90cd0023fdfb4897e1e3826` |
</details>

**Comment by krystian3w** [comment]
test:

```adb
@@/files/html/static/analytics.js?$domain=proxy.openathens.net
```

I doubt breakage by blocking sentry.

**Comment by mapx-** [comment]
Try also

`@@||ingest.sentry.io/api/$xmlhttprequest,domain=proxy.openathens.net|openu.ac.il`

**Comment by quartzbear** [comment]
> 



> Try also
> 
> `@@||ingest.sentry.io/api/$xhr,domain=proxy.openathens.net|openu.ac.il`

What does that mean?

**Comment by mapx-** [comment]
Open uBO dashboard, "my filters" tab, add the filter above, click "apply changes", test again the page

**Comment by krystian3w** [comment]
That mean "unlock"/"allo" these sentry xmlhttprequest on 2 domains:

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

**Comment by quartzbear** [comment]
Ok, thanks.
It didn't work. 

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | /static/analytics.js | -- | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 1 | get | script | `https://lamda--academy-openu-ac-il.eu1.proxy.openathens.net/lamda-ebooks/10104a/files/html/static/analytics.js?uni=96b4d0a0c7bf5b4b85d9e031e18ed3d7` |
| +1 |  |  | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 1 | get | image | `https://lamda--academy-openu-ac-il.eu1.proxy.openathens.net/lamda-ebooks/10104a/files/assets/html/skin/images/favicon2.ico?08cc2507` |
| +1 |  |  | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 1 | get | image | `https://lamda--academy-openu-ac-il.eu1.proxy.openathens.net/lamda-ebooks/10104a/files/assets/cover300.jpg` |
| +0 |  |  | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 1 | get | script | `https://lamda--academy-openu-ac-il.eu1.proxy.openathens.net/lamda-ebooks/10104a/files/html/static/build.js` |
| +0 |  |  | lamda--academy-openu-ac-il.eu1.proxy.openathens.net | 1 | get | doc | `https://lamda--academy-openu-ac-il.eu1.proxy.openathens.net/lamda-ebooks/10104a/` |
</details>


(The site still works when I add the domain to the "Trusted sites" tab, or if I disable uBO.)

**Comment by mapx-** [comment]
because it targets exactly what was blocked and it's crafted for both domain

**Comment by mapx-** [comment]
@ryanbr
