### ISSUE TITLE
eg1.ak4eg.cam: detection

### ISSUE THREAD

**Issue by Mah3ae** [uBlockOrigin/uAssets#17152]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://eg1.ak4eg.cam/search?q=the+good+doctor`

### Category

detection

### Description

Detects ublock and will not open unless it is disabled 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 85676
  cosmetic: 39020
  scriptlet: 17020
  html: 894
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32806-98, 1d.13h.41m
    ublock-badware: 4644-0, 1d.13h.40m
    ublock-privacy: 338-0, 5d.20h.14m
    ublock-abuse: 78-0, 5d.20h.13m
    ublock-unbreak: 1931-0, 1d.13h.39m
    ublock-quick-fixes: 361-0, 5m
    easylist: 63613-515, 2d.19h.25m
    easyprivacy: 31028-1784, 2d.19h.24m
    urlhaus-1: 6629-0, 1d.13h.38m
    plowe-0: 3755-2, 3d.1h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 104 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    ak4eg.cam: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    histats.com: 1
    phaurtuh.net: 2
    smartlook.com: 1
    taigrooh.net: 4
    thompaur.com: 5
```
</details>

**Comment by ghajini** [comment]
`https://eg1.ak4eg.cam/search?q=the+good+doctor` redirects to `https://akwam.to/search?q=the+good+doctor` & there is no detection there....

can you provide steps to reproduce this 
eg from where you arrived on this page

**Comment by Mah3ae** [comment]
Yes just open click on an icon for example the good doctor season 5 and then when it opens it will detect ublock and won't open unless ublock is disabled. It does not detect ublock when the website is just opened it detects it the second time (the time open something through the website).

**Comment by ghajini** [comment]
ok egyptian vpn used, reproduced, fixed
try updating the filters in couple of 15-20 mins
