### ISSUE TITLE
netuplayer.top: popups

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#17151]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://netuplayer.top/e/WXRNajNNZWdpam5CeUV6UEFncC9CQT09`

### Category

popups

### Description

if you click = popup appear

### Configuration

```
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 89165
  cosmetic: 46200
  scriptlet: 20819
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4850-6, 4m
  default: 
    user-filters: 1-0, never
    easylist: 63746-44, 5m
    easyprivacy: 31049-1174, 5m
    plowe-0: 3757-932, 5m
    spa-0: 3509-11, 5m
    spa-1: 5104-191, 4m
    ublock-abuse: 78-0, 4m
    ublock-badware: 4710-114, 4m
    ublock-filters: 32838-116, 4m
    ublock-privacy: 291-1, 4m
    ublock-quick-fixes: 367-22, 4m
    ublock-unbreak: 1923-42, 4m
    urlhaus-1: 6795-0, 4m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 163 ms (selfie)
  maxAssetCacheWait: 264 ms

```

**Comment by ghajini** [comment]
does this work
`netuplayer.top##+js(nowoif)`
