### ISSUE TITLE
jpopsingles.eu: detection

### ISSUE THREAD

**Issue by miyakohebi** [uBlockOrigin/uAssets#17158]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jpopsingles.eu/to/aHR0cHM6Ly9hZHNsaW5rLnB3L3dlYnJvb3QvbGluay9hcGk/dXJsPWh0dHBzOi8vd2RmaWxlcy5ydS9kNGE5Yzgy`

### Category

detection

### Description

jpopsingles.eu: detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/38079662/224755386-c35fbf54-9169-4dab-b7c3-b01a5a9efd2e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 87473
  cosmetic: 47539
  scriptlet: 17206
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 5h.45m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 36-17, never
    JPN-1: 10077-5, 3d.13h.36m
    easylist: 63872-55, 1d.13h.41m
    easyprivacy: 31035-1198, 1d.13h.40m
    plowe-0: 3755-938, 6d.1h.19m
    ublock-abuse: 78-0, 7d.21h.56m
    ublock-badware: 4655-115, 3d.13h.35m
    ublock-filters: 32026-88, 3d.13h.38m
    ublock-privacy: 287-1, 7d.21h.55m
    ublock-quick-fixes: 354-22, 5h.43m
    ublock-unbreak: 1910-52, 3d.13h.37m
    urlhaus-1: 6795-0, 5h.42m
filterset (user): [array of 36 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2067 ms (selfie)
  maxAssetCacheWait: 46 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adsco.re: 1
    bmcdn5.com: 2
    d3mzokty951c5w.cloudfront.net: 1
    displayvertising.com: 1
    eyebrowsasperitygarret.com: 2
    h12-media.com: 1
    outbrain.com: 1
    shrillwife.pro: 1
```
</details>

**Comment by advertblocker** [comment]
drag / select
```
jpopsingles.eu##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
```
