### ISSUE TITLE
[nsfw] sextb.net: detection

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#17154]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sextb.net/ssis-124-sub`

### Category

detection

### Description

![image](https://user-images.githubusercontent.com/98657967/224696145-e5ed6cea-c13e-4641-a153-406d81673074.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 113
filterset (summary): 
  network: 96527
  cosmetic: 118245
  scriptlet: 23189
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7495-2, 1h.34m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-4, 1h.33m
    IDN-0: 5459-346, 1h.35m
    fanboy-annoyance: 81804-369, 5d.4h.54m
    fanboy-cookiemonster: 45993-45993, 5d.4h.53m
    ublock-annoyances: 4850-80, 1h.32m
  default: 
    user-filters: 10-0, never
    easylist: 63781-54, 1h.40m
    easyprivacy: 31047-1176, 1h.39m
    ublock-abuse: 78-0, 1h.42m
    ublock-badware: 4710-113, 1h.38m
    ublock-filters: 31983-386, 1h.37m
    ublock-privacy: 291-7, 1h.41m
    ublock-quick-fixes: 367-20, 1h.30m
    ublock-unbreak: 1923-44, 1h.36m
    urlhaus-1: 6795-0, 1h.31m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5762 ms (selfie)
  maxAssetCacheWait: 359 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    sextb.net: 2
    addthis.com: 1
    cloudflareinsights.com: 1
    googletagmanager.com: 2
    histats.com: 1
    realsrv.com: 3
    toaioi.xyz: 9
    wpnsrv.com: 1
    yandex.ru: 1
```
</details>

**Comment by Daxy7** [comment]
invalid, duplicate: #16527

**Comment by ghajini** [comment]
use default settings
