### ISSUE TITLE
vrv.co: breakage

### ISSUE THREAD

**Issue by daxsic** [uBlockOrigin/uAssets#17168]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vrv.co/watch/GY1975EVR/My-Brother-My-Brother-and-Me:Resumes-Jamiroquais-Dad`

### Category

breakage

### Description

when ublock is turned on VRV claims it is having a network error, no issue with it turned off except ads :(

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 86210
  cosmetic: 39111
  scriptlet: 17016
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63900-44, 3d.4h.36m
    easyprivacy: 31032-1174, 4d.20h.41m
    plowe-0: 3755-932, 9d.20h.56m
    ublock-abuse: 78-0, 6h.57m
    ublock-badware: 4666-114, 2d.20h.35m
    ublock-filters: 31980-77, 2d.20h.34m
    ublock-privacy: 291-1, 6h.56m
    ublock-quick-fixes: 348-21, 6h.54m
    ublock-unbreak: 1913-55, 2d.20h.33m
    urlhaus-1: 6962-0, 6h.55m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3461 ms (selfie)
  maxAssetCacheWait: 240 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    adsrvr.org: 1
    etp-prod.com: 1
    segment.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
vrv.co##+js(set, analytics.options, noopFunc)
vrv.co##+js(set, analytics.options.integrations, noopFunc)
```

**Comment by thislooksfun** [comment]
I have this same issue, those filters did not work for me (Firefox 111.0.1, uBlockOrigin v1.48.2).
