### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Danielsvamp** [uBlockOrigin/uAssets#17162]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=_EsFyogVvkw`

### Category

ads

### Description

Showing normal ads as if there were no ad blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 87449
  cosmetic: 41579
  scriptlet: 17304
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    SWE-1: 4304-0, 1d.3h.42m
    easylist: 63872-51, 1d.1h.3m
    easyprivacy: 31028-1180, 5d.1h.5m
    plowe-0: 3757-934, 5h.35m
    ublock-abuse: 78-0, 1d.3h.46m
    ublock-badware: 4686-114, 1d.3h.45m
    ublock-filters: 31976-78, 1d.3h.44m
    ublock-privacy: 290-1, 1d.1h.4m
    ublock-quick-fixes: 359-22, 1d.3h.41m
    ublock-unbreak: 1923-39, 1d.3h.43m
    urlhaus-1: 6649-0, 1d.3h.40m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3752 ms (selfie)
  maxAssetCacheWait: 180 ms
popupPanel: 
  blocked: 34
  blockedDetails: 
    doubleclick.net: 2
    googlesyndication.com: 2
    youtube.com: 30
```
</details>

**Comment by mapx-** [comment]
duplicate, read this thread
https://github.com/uBlockOrigin/uAssets/issues/7636
