### ISSUE TITLE
talent.lowes.com: breakage

### ISSUE THREAD

**Issue by giraffekey** [uBlockOrigin/uAssets#17163]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://talent.lowes.com/us/en/job/2536663BR/Warehouse%E2%80%AFDistribution-Team-Member-All-Shifts`

### Category

breakage

### Description

The extension blocks the "cdn.phenompeople.com" domain (it's yellow) which prevents a chat bot required for the hiring process from showing up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 85875
  cosmetic: 39013
  scriptlet: 17042
  html: 894
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32855-57, 3d.19h.40m
    ublock-badware: 4670-0, 3d.19h.39m
    ublock-privacy: 338-0, 2d.10h.43m
    ublock-abuse: 78-0, 2d.10h.42m
    ublock-unbreak: 1921-0, 3d.19h.38m
    ublock-quick-fixes: 361-0, 13h.24m
    easylist: 63585-571, 3d.23h.44m
    easyprivacy: 31035-1767, 3d.23h.43m
    urlhaus-1: 6795-0, 13h.23m
    plowe-0: 3757-2, 21h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 10409 ms (selfie)
  maxAssetCacheWait: 6842 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    phenompeople.com: 1
```
</details>

**Comment by mapx-** [comment]
on my side the chat stuff is appearing adding this exception 

`@@||googletagmanager.com/gtm.js$script,domain=talent.lowes.com`

**Comment by giraffekey** [comment]
Ah I misdiagnosed what was causing it. That works for me too.

**Comment by stephenhawk8054** [comment]
@ryanbr
