### ISSUE TITLE
pplware.sapo.pt: ads

### ISSUE THREAD

**Issue by miguelarroba** [uBlockOrigin/uAssets#17164]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pplware.sapo.pt/`

### Category

ads

### Description

Test ads not disapear

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium Mobile: 107
filterset (summary): 
  network: 86931
  cosmetic: 29237
  scriptlet: 17405
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    adguard-mobile: 8537-162, never
    easylist: 63372-17033, never
    easyprivacy: 31007-1149, never
    plowe-0: 3751-930, never
    ublock-abuse: 78-0, never
    ublock-badware: 4605-0, never
    ublock-filters: 32968-298, never
    ublock-privacy: 287-1, never
    ublock-quick-fixes: 343-0, never
    ublock-unbreak: 1927-49, never
    urlhaus-1: 6492-0, never
filterset (user): [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1558 ms
  maxAssetCacheWait: 35 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    sapo.pt: 1
    google-analytics.com: 1
    sapo.io: 1
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
1. you missed the regional potuguese list => enable `spa, por: AdGuard Spanish/Portuguese`
2. if still does not work it's because you are using a not supported (mobile) browser
