### ISSUE TITLE
[nsfw] blog.zubatecno.com: breakage

### ISSUE THREAD

**Issue by datoshkr** [uBlockOrigin/uAssets#17166]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.zubatecno.com/?p=1%20.%20%27?session=1%27`

### Category

breakage

### Description

Shortened urls from `zuba.link`, for example `https://zuba.link/TlMT42T` redirects to `https://blog.zubatecno.com` and asks for click ad to continue... Without uBO , I can right click on any ad and continue...

I use only uBO with default settings.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![OnPaste 20230314-062605](https://user-images.githubusercontent.com/79659024/224877013-e655728e-d024-4895-9f72-acd0ac71c02a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 86502
  cosmetic: 39316
  scriptlet: 17380
  html: 907
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33725-107, 17m
    ublock-badware: 4724-0, 17m
    ublock-privacy: 341-0, 17m
    ublock-abuse: 78-0, 17m
    ublock-unbreak: 1934-0, 17m
    ublock-quick-fixes: 374-0, 17m
    easylist: 63833-536, 17m
    easyprivacy: 31047-1767, 17m
    urlhaus-1: 6883-0, 17m
    plowe-0: 3757-2, 17m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2338 ms
  maxAssetCacheWait: 205 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googletagmanager.com: 1
    holid.io: 1
    orquideassp.com: 2
    purpleads.io: 2
    respinor.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> `coinpayu.com` detects adblock when logged in

I can't reproduce after logging in
