### ISSUE TITLE
107.152.37.223: popups

### ISSUE THREAD

**Issue by acgl** [uBlockOrigin/uAssets#17165]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://107.152.37.223/`

### Category

popups

### Description

opening new tabs and unwanted popups
Please fix 
Thanks

> 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium Mobile: 107
filterset (summary): 
  network: 103699
  cosmetic: 138622
  scriptlet: 24752
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
  added: 
    adguard-annoyance: 64927-1695, 32m
    adguard-social: 19937-1959, 32m
    fanboy-annoyance: 81970-38985, 32m
    ublock-annoyances: 4912-238, 32m
  default: 
    IDN-0: 5459-233, 32m
    adguard-mobile: 8537-39, 32m
    easylist: 63558-16949, 26m
    easyprivacy: 31007-1270, never
    plowe-0: 3757-1016, 24m
    ublock-abuse: 78-0, 23m
    ublock-badware: 4704-115, 22m
    ublock-filters: 32202-711, 21m
    ublock-privacy: 292-8, 20m
    ublock-quick-fixes: 379-19, 19m
    ublock-unbreak: 1928-47, 18m
    urlhaus-1: 6883-0, 17m
filterset (user): [array of 1 redacted]
trustedset: 
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  collapseBlocked: false
  contextMenuEnabled: false
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1134 ms (selfie)
  maxAssetCacheWait: 553 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    afdashrafi.com: 1
```
</details>

**Comment by ghajini** [comment]
@gmarcher ABPindo

**Comment by mapx-** [comment]
- use firefox mobile
- reset uBO, update all filter lists 
- add
`*.gif$domain=107.152.37.223,image`

**Comment by acgl** [comment]
> 

Thanks
