### ISSUE TITLE
4kdownload.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#17171]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.4kdownload.com/thanks-for-installing?source=videodownloader&install=update`

### Category

nuisance

### Description

Aggressive self-promotion banner on every software update, although having bought premium license.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-03-14 at 13-04-51 Thanks for installing 4K Download](https://user-images.githubusercontent.com/101707608/224984818-4dbad0ce-aa9a-41c5-8faa-03c50b230e8b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 110
filterset (summary): 
  network: 260296
  cosmetic: 241885
  scriptlet: 38745
  html: 1043
listset (total-discarded, last-updated): 
  added: 
    https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 49642-0, 2h.41m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 37221-407, 2h.30m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1066-50, 3d.4h.17m
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-8, 2h.32m
    https://www.i-dont-care-about-cookies.eu/abp/: 25607-7, 2h.38m
    adguard-generic: 68405-6470, 3d.6m
    adguard-mobile: 8533-815, 3d.5m
    adguard-spyware-url: 939-135, 3d.4m
    block-lan: 44-0, 26d.12m
    curben-phishing: 53216-20, 2h.35m
    curben-pup: 191-0, 2h.34m
    adguard-annoyance: 64870-7413, 3d.3m
    adguard-social: 19921-81, 3d.2m
    fanboy-thirdparty_social: 68-0, 4d.23h.27m
    fanboy-annoyance: 82266-10679, 4d.23h.26m
    ublock-annoyances: 4811-47, 3d.1m
    dpollock-0: 11337-912, 3d.11m
    adguard-spyware: 38353-17007, 2d.23h.58m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32806-224, 3d.9m
    ublock-badware: 4685-102, 3d.8m
    ublock-privacy: 338-12, 3d
    ublock-abuse: 78-3, 2d.23h.59m
    ublock-unbreak: 1921-0, 3d.7m
    ublock-quick-fixes: 366-0, 2h.37m
    easylist: 63745-21795, 2h.42m
    easyprivacy: 31049-4994, 2h.39m
    urlhaus-1: 6962-0, 2h.36m
    plowe-0: 3750-1635, 12d.22h.14m
    GRC-0: 995-2, 2h.33m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1343 ms (selfie)
  maxAssetCacheWait: 5094 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    tapfiliate.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
4kdownload.com##.sale-line
4kdownload.com##.recommend
```

@ryanbr for FA list maybe

**Comment by DimitrisKalaboukas** [comment]
@mapx- Is it possible to move header bar to the top with a rule, in order to cover the gap?

**Comment by mapx-** [comment]
test

`4kdownload.com##.page-header:style(top:0 !important)`

**Comment by krystian3w** [comment]
```adb
4kdownload.com##.sale-line
4kdownload.com##header[class]:remove-class(/page-header--sale|page-header--with-margin/)
```

**Comment by krystian3w** [comment]
🍀 `4kdownload.com##.mascot` = `4kdownload.com/-ad0p9/pl/stogram`

**Comment by krystian3w** [comment]
You omit `4kdownload.com##.mascot` - sticky and don't closeable
