### ISSUE TITLE
tr.euronews.com: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#17178]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tr.euronews.com/kultur/2022/09/13/74-emmy-odulleri-2022-kimler-odul-aldi`

### Category

nuisance

### Description

This video is blocked by the `||minute.ly^$third-party` rule in EasyList. This is expected behavior. When the default uBO filters are enabled, the rule is not applied, so the video is shown.

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/225194894-d95c1bb6-4a96-488a-a3e5-6e6cd62526de.png)

</details>

The `||minute.ly^$third-party` rule works as expected when the default uBO filters are disabled.

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/225195649-54f145f7-cabe-4244-892b-c05e85b479b7.png)

</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/225193567-616c3c59-f39b-40cc-9db5-03152a984d5e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 124492
  cosmetic: 156411
  scriptlet: 35173
  html: 910
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38687-14619, 11h.23m
    adguard-generic: 68561-5841, 11h.23m
    adguard-spyware-url: 940-4, 11h.23m
    adguard-annoyance: 64966-1552, 11h.23m
    adguard-social: 19944-35, 11h.23m
  default: 
    user-filters: 63-0, never
    ublock-filters: 33747-66, 11h.23m
    ublock-badware: 4724-0, 11h.23m
    ublock-privacy: 341-0, 11h.23m
    ublock-abuse: 78-0, 11h.23m
    ublock-unbreak: 1937-0, 11h.23m
    ublock-quick-fixes: 374-0, 11h.23m
    easylist: 63848-296, 11h.23m
    easyprivacy: 31050-1191, 11h.23m
    TUR-0: 11611-11, 11h.23m
filterset (user): [array of 65 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1631 ms (selfie)
  maxAssetCacheWait: 1393 ms
  unsuspendAfter: 135 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    euronews.com: 1
    adobedtm.com: 3
    aniview.com: 2
    chartbeat.com: 2
    d24rtvkqjwgutp.cloudfront.net: 1
    demdex.net: 2
    doubleclick.net: 1
    facebook.net: 1
    geoedge.be: 1
    googlesyndication.com: 1
    moatads.com: 1
    omtrdc.net: 1
    outbrain.com: 1
    privacy-center.org: 1
    pubmatic.com: 1
    snackly.co: 2
    teads.tv: 1
    tldw.me: 1
    vuukle.com: 5
```
</details>

**Comment by krystian3w** [comment]
https://forums.lanik.us/viewtopic.php?p=164328-minute-ly&sid=1915a00292a886c89be1e12a179db427#p164328

So you should check formula1 - if don't longer have these local content then maybe more pages removed use minute.ly.

To override EasyList exception possible use:

```adb
||minute.ly^$third-party,important,domain=euronews.com
```

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#important
