### ISSUE TITLE
daddylivehd.sx: popup

### ISSUE THREAD

**Issue by KPreston2900050** [uBlockOrigin/uAssets#17179]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

DaddyLive.SX

I have tried to find the issue but I am not adept with web programing but no matter what, the picker find nothing to highlight so I guess it is embedded Java code.

No matter what, when you click anywhere within the window, it hijacks the browser to some random website that is active or not.
I wish I knew how to make my own filters because this happens using Firefox and Edge.  I have not tried Chrome.

Also, try googling for any help on popups and hijacks.

Using this bug report results from desperation and not due to laziness.

### A specific URL where the issue occurs.

`https://daddylivehd.sx/`

### Steps to Reproduce

click on anything

### Expected behavior

run the stream without incident.

### Actual behavior

hijacks browser
sends to anonymous web pages
hundreds of about pages popup

### uBO version

uBlock Origin 1.47.4

### Browser name and version

Firefox 110.01

### Operating System and version

Windows 11 64 bit

**Comment by ghajini** [comment]
As its sports site ,provide stream links on which you encounter popups/ads

**Comment by garry-ut99** [comment]
>  * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+sort%3Aupdated-desc) to avoid opening a duplicate issue.

You didn't, a duplicate of https://github.com/uBlockOrigin/uAssets/issues/16603

**Comment by KPreston2900050** [comment]
As its sports site ,provide stream links on which you encounter popups/ads
No, actually it is a streaming site that had embedded popups that hijack your browser as I described.

No matter what it is, no matter who runs it, no matter what it's legality....It STILL produces popups and ads that Ublock Origin does not block.

There are a lot of problems with the light box picker as well especially around youtube.

The only thing I recognize in this world is that people are completely in your face intrusive and will spin whatever narrative to excuse their behavior.

Just put the damn ad to the side and if I want to click on it then so be it but nope, throw it in your face or hijack your equipment to grab your attention.

If Ublock Origin is not up to the task then I take my business elsewhere.  I refuse to live in the 19th century anymore with you people.

**Comment by stephenhawk8054** [comment]
I went to the home page you give at the post and click everywhere but there's no popup for me.

I went to an arbitrary link in that home page: `https://daddylivehd.sx/stream/stream-60.php` but I cannot reproduce the popup either although trying to click everywhere on the page again. ghajini added a commit to deal with a popup with an iframe of `ntuplay` but as we were not sure if that is the right link you encountered or not, we asked what is the exact stream link that you had the issues. You can force update the filter lists and test again.

Not sure why you think this is `excuse their behavior`. How can we fix the issue if we cannot reproduce it (which means we cannot investigate where the source of the popup is)?

**Comment by mapx-** [comment]
@KPreston2900050 

follow ALL these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by huyszn** [comment]
New domain
`dlhd.sx`

**Comment by KPreston2900050** [comment]
broken again

**Comment by huyszn** [comment]
> broken again

The new domains are `daddylivestream.com` and `thedaddy.top`
