### ISSUE TITLE
animezone.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1717]
`https://streamango.com/embed/sknapenonmlfanor/`

popads in other sites
`http://www.animezone.pl/odcinek/jian-wangchao/1`

to reproduce click streamango button and play the video
![2018-03-15-jian wangchao - odcinek 1 - ogladaj anime online](https://user-images.githubusercontent.com/5884000/37484810-f37b4212-2889-11e8-88dd-fa84963afed2.png)

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.43
Chrome 65.0.3325.162

</details>

**Comment by zaphodbeebblebrox** [comment]
If you click on the green play buttons next to the sources, there is a 10 second ad timer. `animezone.pl##script:inject(nano-setInterval-booster.js)`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
`https://www.animezone.pl/odcinek/yuragi-sou-no-yuuna-san-ova/1`

**Comment by okiehsch** [comment]
@MajkiIT can you add the `animezone-filters` to the polish list?
````
animezone.pl##script:inject(nano-setInterval-booster.js)
@@||animezone.pl^$generichide
animezone.pl##[id*="ScriptRoot"]
````
should work for you.

**Comment by MajkiIT** [comment]
@okiehsch Thanks 
https://github.com/MajkiIT/polish-ads-filter/commit/b9b88bbcc261bd596a574e738597f4d5d45c8f05#diff-711027ed0794992ae3b8710d874f3df7
