### ISSUE TITLE
trutv.com: ads

### ISSUE THREAD

**Issue by ArsenaI4904** [uBlockOrigin/uAssets#17176]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I tried watching trutv.com live with cable and it's giving me ads before the live stream starts.

### URL(s) where the issue occurs.

`https://www.trutv.com/watchtrutv/east`

### uBO version

1.47.4

### Browser name and version

Google Chrome 111.0.5563.65

### Settings

None

**Comment by mapx-** [comment]
test this filter, see if helps

`||medium.ngtv.io/v2/media/*&ssaiProfile=$xhr,removeparam=ssaiProfile,domain=trutv.com`

**Comment by ArsenaI4904** [comment]
> test this filter, see if helps
> 
> `||medium.ngtv.io/v2/media/*&ssaiProfile=$xhr,removeparam=ssaiProfile,domain=trutv.com`

I think it works.

**Comment by ArsenaI4904** [comment]
Thank you.
