### ISSUE TITLE
coin360.com: ads

### ISSUE THREAD

**Issue by AngeloCore** [uBlockOrigin/uAssets#17172]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://coin360.com/`

### Category

ads

### Description

The top banner of the page doesnt hide

I am a new user, just switched from brave to edge and ublock, this is the only issue i got so far

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/62988428/225038790-aa2d8e65-aa6e-4beb-b092-905a462d4949.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 110
filterset (summary): 
  network: 86473
  cosmetic: 39329
  scriptlet: 17399
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63848-44, 4m
    easyprivacy: 31050-1174, 4m
    plowe-0: 3757-930, 4m
    ublock-abuse: 78-0, 4m
    ublock-badware: 4720-114, 3m
    ublock-filters: 32906-83, 4m
    ublock-privacy: 292-1, 4m
    ublock-quick-fixes: 375-22, 4m
    ublock-unbreak: 1926-40, 4m
    urlhaus-1: 6834-0, 4m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2481 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 2
    sentry.io: 1
    servedbyadbutler.com: 1
```
</details>

**Comment by Daxy7** [comment]
`coin360.com##.leader_wrapper` (sazJOX6, does not hide fully)
`coin360.com##.Sticky_Promo` (y49o7q)

`coin360.com##.azJOX6` (leader_wrapper, hides fully)
`coin360.com##.y49o7q` (Sticky_Promo)

**Comment by Daxy7** [comment]
Sticky promo is [this at the bottom right corner](https://user-images.githubusercontent.com/91396482/225093672-52489907-b577-43cf-92fa-8d4f7335860e.png) (same advertisement)

**Comment by mapx-** [comment]
@AngeloCore report at easylist repository

**Comment by mapx-** [comment]
@ryanbr

**Comment by AngeloCore** [comment]
> @AngeloCore report at easylist repository

Where can i find this repo?

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/issues
