### ISSUE TITLE
1movies.se WebRTC ads

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#1718]
### URL(s) where the issue occurs

`https://1movies.se/movie/memento-mori/406`

### Describe the issue

Ads loaded through WebRTC (amgload.net & piguiqproxy.com) between movie player and movie description. Also, 30 seconds ads after hitting play button.

### Versions

- Browser/version: Chrome 64.0.3282.186
- uBlock Origin version: v1.15.2

### Settings

Tested with default settings

**Comment by okiehsch** [comment]
Does 
````
||piguiqproxy.com^$xmlhttprequest,redirect=nooptext,domain=1movies.se
||amgload.net^$xmlhttprequest,redirect=nooptext,domain=1movies.se
1movies.se##script:inject(abort-on-property-write.js, Fingerprint2)
1movies.se###a_wrap
1movies.se###no_po_share
||loadshare.org/custom/*/1m_video.mp4$media,domain=1movies.se
````
work for you?

**Comment by mapx-** [comment]
or
```
1movies.*##script:inject(abort-current-inline-script.js, atob, encodeURIComponent)
1movies.*##script:inject(window.open-defuser.js)
1movies.*##.add_only
1movies.*###no_po_share
1movies.*##.right.superButton
```

**Comment by okiehsch** [comment]
````
1movies.*##script:inject(abort-current-inline-script.js, atob, encodeURIComponent)
````
what does this accomplish?

`1movies.*##script:inject(window.open-defuser.js)`
the popup that blocks opens `https://1movies.se/user/buyregistration`, so I would say that is self advertisement, maybe that filter could be added to `uBO-annoyances`

**Comment by mapx-** [comment]
nevermind, needed those posted by you

**Comment by nimasaj** [comment]
@okiehsch, Those work perfectly. Thanks
