### ISSUE TITLE
taskade.com: breakage

### ISSUE THREAD

**Issue by YuShyam** [uBlockOrigin/uAssets#17186]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.taskade.com/spaces/ynF99xWi81GApsnG`

### Category

breakage

### Description

cannot open 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 103322
  cosmetic: 49225
  scriptlet: 17159
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    CHN-0: 27743-104, 3d.23h.38m
    easylist: 63781-96, 1d.22h.26m
    easyprivacy: 31028-1194, 6d.41m
    plowe-0: 3757-934, 1d.22h.27m
    ublock-abuse: 78-0, 2d.22h.55m
    ublock-badware: 4686-114, 3d.23h.40m
    ublock-filters: 31980-94, 3d.23h.41m
    ublock-privacy: 291-1, 2d.22h.56m
    ublock-quick-fixes: 375-20, 22h.10m
    ublock-unbreak: 1920-40, 3d.23h.39m
    urlhaus-1: 6834-0, 22h.9m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 44 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2634 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 2
  no-cosmetic-filtering: true
  blockedDetails: 
    cloudflareinsights.com: 1
    wdfl.co: 1
```
</details>

**Comment by Daxy7** [comment]
what can't you open? is an account required?

**Comment by mapx-** [comment]
provide all the steps to get whatever breakage with thorough explanation
