### ISSUE TITLE
pvz2.hrgame.com.cn: breakage

### ISSUE THREAD

**Issue by aceace15** [uBlockOrigin/uAssets#17189]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

what is happening is a item in easylist filter (line 414 `/ad-cdn.$domain=~ad-cdn.getro.com`)

when you load into the page there should be a background of a lawn blurred out

but what happens is a false positive, where it's applying a filter where it shouldn't

### URL(s) where the issue occurs.

`https://pvz2.hrgame.com.cn/`

### Screenshot(s)

images failing to load
https://user-images.githubusercontent.com/113923776/225432452-30f75224-4a06-4050-8069-095a06c259fc.png

with the user added rule (in the `my rules` tab)
`pvz2.hrgame.com.cn https://ad-cdn.hrgame.com.cn * allow`

https://user-images.githubusercontent.com/113923776/225432733-f79d94fa-2d96-4efd-ae7d-083342ae116b.png

### uBO version

1.47.4

### Browser name and version

librewolf 110.0-1

### Settings

- using medium mode
- blocking javascript by default
- ticked `I am an advanced user` no advanced setting changed

### Notes

`pvz2.hrgame.com.cn https://ad-cdn.hrgame.com.cn * allow`

this is the rule that I used to get the images to load up, the cause is from the easylist filter

at line 414 you have `/ad-cdn.$domain=~ad-cdn.getro.com`

now from reading the `$domain=~ad-cdn.getro.com` I can guess that it is intended to only run on `getro.com`

but what's happening instead is that it's doing the filter on all sites, not just `~add-cdn.getro.com` 

the filter I used to fix this was (look bellow)

```adb
! 2023-03-12 https://pvz2.hrgame.com.cn
@@||ad-cdn.hrgame.com.cn/pvz2/upload/*$image,domain=pvz2.hrgame.com.cn
and
@@||ad-cdn.hrgame.com.cn/pvz2/upload/*$media,domain=pvz2.hrgame.com.cn
```

or use this filter in the my rules tab
`pvz2.hrgame.com.cn https://ad-cdn.hrgame.com.cn * allow`

for the sake of adding more information I'll add a logger log
(the first one is for when the images failed to load)

[failed_to_load.md](https://github.com/uBlockOrigin/uAssets/files/10984476/failed_to_load.md)

(this one is with `pvz2.hrgame.com.cn https://ad-cdn.hrgame.com.cn * allow` added to the `my rules` section)
[loaded_properly.md](https://github.com/uBlockOrigin/uAssets/files/10984456/loaded_properly.md)

sorry if I didn't do things properly I'll try answer questions if there are any problems with the way I wrote this

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/9bf185d041ca8fb3d2de048b0f4d259e0159368d
