### ISSUE TITLE
galaxytranslations97.com: detection

### ISSUE THREAD

**Issue by Suddenflame** [uBlockOrigin/uAssets#17187]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://galaxytranslations97.com/novel/i-wont-accept-your-regrets/`

### Category

detection

### Description

The website detects the Ublock as a blocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 86742
  cosmetic: 38905
  scriptlet: 17028
  html: 892
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 32812-37, 2d.2h.25m
    ublock-badware: 4049-1, 2d.2h.24m
    ublock-privacy: 341-0, 22h.36m
    ublock-abuse: 78-0, 22h.35m
    ublock-unbreak: 1934-0, 2d.2h.23m
    ublock-quick-fixes: 374-19, 22h.33m
    easylist: 64987-564, 2d.2h.27m
    easyprivacy: 30908-1710, 2d.2h.26m
    urlhaus-1: 6834-0, 22h.32m
    plowe-0: 3755-2, 9d.1h.23m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6323 ms (selfie)
  maxAssetCacheWait: 2318 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    disqus.com: 2
    google-analytics.com: 1
    googlesyndication.com: 2
    viglink.com: 2
    wp.com: 4
```
</details>

**Comment by Daxy7** [comment]
unable to reproduce

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
