### ISSUE TITLE
gplinks.co: detection

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#17188]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Needs Update - Lazy To Make PR : (

 !!!! Destination Link NSFW !!!!

```
mynewsmedia.co,revadvert.com##+js(set, AdBlockerDetected, noopFunc)
mynewsmedia.co,revadvert.com###VerifyBtn:style(display:block !important;)
mynewsmedia.co,revadvert.com##+js(nano-sib, timer, *)
mynewsmedia.co,revadvert.com###VerifyBtn, #myNextInst, #NextBtn, #NextInfo:others()
gplinks.co##+js(aopr, clickCount)
@@||gplinks.in/track/js/main.js$script,domain=revadvert.com|mynewsmedia.co
@@||gplinks.in/track/*$xhr,domain=revadvert.com|mynewsmedia.co
```

### URL(s) where the issue occurs.

`gplinks.co/6ha1`

### uBO version

*

### Browser name and version

*

### Settings

*

**Comment by Daxy7** [comment]
Do you mean `revadvert`?

`revadvert.com##+js(acs, document.createElement, fakeAd)`

<details><summary>Source</summary>
<p>
        var AdbModel = document.getElementById('AdbModel');
        
        let fakeAd = document.createElement("div");
        fakeAd.className = "textads banner-ads banner_ads ad-unit ad-zone ad-space adsbox";
        fakeAd.style.height = "1px";
    
        document.body.appendChild(fakeAd);
        let x_width = fakeAd.offsetHeight;

        if (x_width) {
            setTimeout(removefakeAd, 300);
        } else {
            AdBlockerDetected();
        }

        function removefakeAd() {
            fakeAd.remove();
        }

        async function detectAdBlock() {
            let adBlockEnabled = false
            const googleAdUrl = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'
            try {
                await fetch(new Request(googleAdUrl)).catch(_ => adBlockEnabled = true)
            } catch (e) {
                adBlockEnabled = true
            } finally {
                if (adBlockEnabled == true) {
                    AdBlockerDetected();
                }
            }
        }
        detectAdBlock()

        function AdBlockerDetected() {
            AdbModel.style.visibility = 'visible';
        }

        function AdbPageReload() {
            location.reload();
        }
    
</p>
</details>

**Comment by Daxy7** [comment]
what exactly is causing breakage?

**Comment by mapx-** [comment]
`gplinks.co/6ha1`  => `404 Not Found`

**Comment by Daxy7** [comment]
Oh, you meant to say about adding the proposed filters.
