### ISSUE TITLE
sinonimos.de: breakage

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#17198]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sinonimos.de/the-best-digital-marketing-tools/`

### Category

breakage

### Description

@JobcenterTycoon 
Please help
Hidden button continue if allow adblock. Step 2,step3,step4.
Original link
https://ctr.sh/OW2jbbk7fwk
Thanks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium Mobile: 105
filterset (summary): 
  network: 88028
  cosmetic: 29356
  scriptlet: 17533
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 155-48, never
    adguard-mobile: 8542-32, 1d.1h.45m
    easylist: 63897-16911, 1d.1h.45m
    easyprivacy: 31053-1184, 1d.1h.45m
    plowe-0: 3757-1015, 1d.1h.45m
    ublock-abuse: 78-0, 1d.1h.45m
    ublock-badware: 4697-115, 1d.1h.45m
    ublock-filters: 33121-316, 1d.1h.45m
    ublock-privacy: 292-2, 1d.1h.45m
    ublock-quick-fixes: 383-34, 1h.29m
    ublock-unbreak: 1933-43, 1d.1h.45m
    urlhaus-1: 6886-0, 1h.28m
filterset (user): [array of 60 redacted]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1802 ms (selfie)
  maxAssetCacheWait: 615 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    doubleclick.net: 1
    googletagmanager.com: 1
```
</details>

**Comment by krystian3w** [comment]
Check in Firefox Daylight 110 or 111:

https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&gl=US

**Comment by king-iskan** [comment]
Thanks @JobcenterTycoon

**Comment by king-iskan** [comment]
> Check in Firefox Daylight 110 or 111:
> 
> https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&gl=US

This can use adblock orgin? Can use extension?
