### ISSUE TITLE
google.com: breakage (search results in maps)

### ISSUE THREAD

**Issue by igor47** [uBlockOrigin/uAssets#17193]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.google.com/maps/search/vegetarian+restaurant/@-6.2176233,106.8135245,16z/data=!3m1!4b1`

### Category

breakage

### Description

search results sidebar is black

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/200575/225482743-9b59852f-bc45-4304-8c6d-9abee5ad971f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 86147
  cosmetic: 39136
  scriptlet: 17029
  html: 893
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32807-51, 2d.22h.16m
    ublock-badware: 4690-0, 2d.22h.18m
    ublock-privacy: 340-0, 2d.22h.21m
    ublock-abuse: 78-0, 2d.17h.27m
    ublock-unbreak: 1934-0, 2d.22h.17m
    easylist: 63872-578, 2d.22h.20m
    easyprivacy: 31049-1767, 2d.22h.19m
    plowe-0: 3757-2, 29m
    urlhaus-1: 6870-0, 28m
    ublock-quick-fixes: 379-0, 27m
filterset (user): [empty]
trustedset: 
  added: [array of 19 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 334 ms (selfie)
  maxAssetCacheWait: 142 ms
popupPanel: 
  blocked: 461
  blockedDetails: 
    google.com: 457
    csp.withgoogle.com: 3
    googlesyndication.com: 1
```
</details>

**Comment by dedaznamaz** [comment]
I have the same issue from around 2 weeks

**Comment by stephenhawk8054** [comment]
Which region are you when accessing the site?

**Comment by dedaznamaz** [comment]
> Which region are you when accessing the site?

Bulgaria. Something breaks the full loading of maps, almost nothing works. When I disable ublockorigin , everything is working as supposed to. In console there are some errors, but I don't know which one is connected to the issue.
![Snap1](https://user-images.githubusercontent.com/114338663/229333299-c98af084-6762-4fc4-a37e-552d0da2c0b5.jpg)

**Comment by dedaznamaz** [comment]
Ok found the issue. Usually I block google fonts, I've done it for years without issues. Probably something changed. But anyways, maps is working now.
