### ISSUE TITLE
hulu.com: ads

### ISSUE THREAD

**Issue by Datkitkatz** [uBlockOrigin/uAssets#17194]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hulu.com/hub/home`

### Category

ads

### Description

car commercials are relentless. watching Hulu went down the list of Prerequisites above refreshed . Tried in both Firefox and Chrome. no special filters. ads still made it through. watching Soul Eater... if that matters... Thank you.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 86573
  cosmetic: 39367
  scriptlet: 17396
  html: 912
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33770-73, 6m
    ublock-badware: 4717-0, 6m
    ublock-privacy: 341-0, 6m
    ublock-abuse: 78-0, 6m
    ublock-unbreak: 1940-0, 6m
    easylist: 63932-583, 6m
    easyprivacy: 31053-1767, 6m
    urlhaus-1: 6886-0, 6m
    plowe-0: 3757-2, 6m
    ublock-quick-fixes: 379-1, 6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 192 ms (selfie)
  maxAssetCacheWait: 102 ms
popupPanel: 
  blocked: 371
  blockedDetails: 
    hulu.com: 147
    ads-twitter.com: 1
    conviva.com: 33
    demdex.net: 14
    imrworldwide.com: 1
    omtrdc.net: 141
    scorecardresearch.com: 29
    tealiumiq.com: 2
    tiktok.com: 1
    yimg.com: 2
```
</details>

**Comment by Datkitkatz** [comment]
https://www.hulu.com/watch/46b73812-c072-4e14-8bf8-18e310bdc17d
Thanks everyone.

**Comment by mapx-** [comment]
Test (filter from AdGuard list)

`hulu.com##+js(json-prune, breaks pause_ads)`

**Comment by yokoffing** [comment]
I haven't tried `hulu.com##+js(json-prune, breaks pause_ads)` yet, but just wanted to add my experience. Right now, uBO doesn't block the first ad when I start an episode, but it does block subsequent ads when they appear during the stream.

**Comment by cglong** [comment]
While this is blocking the ads, it seems to have affected closed captions. Following each blocked ad break, the captions move ahead from the audio by about one second.
