### ISSUE TITLE
blogbux.net: breakage

### ISSUE THREAD

**Issue by MKaine9** [uBlockOrigin/uAssets#17191]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blogbux.net/serene-yoga-destinations-to-add-to-your-travel-bucket-list/`

### Category

breakage

### Description

> Para exibir esta página, o Firefox precisa enviar informações que repetirão qualquer ação (como uma pesquisa ou confirmação de compra) efetuada anteriormente.

**In order to display this page, Firefox needs to send information that will repeat any action (such as a search or purchase confirmation) that was previously performed.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 87611
  cosmetic: 42350
  scriptlet: 17323
  html: 897
listset (total-discarded, last-updated): 
  default: 
    user-filters: 10-0, never
    ublock-filters: 32841-85, 1d.11h.5m
    ublock-badware: 4714-0, 1d.23h.9m
    ublock-privacy: 335-0, 12d.8h.31m
    ublock-abuse: 78-0, 12d.8h.30m
    ublock-unbreak: 1934-0, 2d.6h
    ublock-quick-fixes: 375-0, 10h.24m
    easylist: 63805-620, 1d.19h.7m
    easyprivacy: 31032-1782, 5d.20h.15m
    urlhaus-1: 6870-0, 10h.23m
    plowe-0: 3755-2, 10d.13h.12m
    spa-1: 5106-10, 1d.19h.8m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 686 ms (selfie)
  maxAssetCacheWait: 241 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
What is broken ? Provide all the steps to reproduce the issue.
If it's another starting address just provide that one.

**Comment by Daxy7** [comment]
> In order to display this page, Firefox needs to send information that will repeat any action (such as a search or purchase confirmation) that was previously performed.

That is a message from the browser, not uBlock Origin
