### ISSUE TITLE
tv.vg.no: breakage

### ISSUE THREAD

**Issue by h3xh3xh3x** [uBlockOrigin/uAssets#17197]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tv.vg.no/video/261002/her-ser-man-sammenstottet?utm_source=vgfront&utm_content=hovedlopet_row1_pos1&utm_medium=dre-6412ea16069dcdee1ceaec1e`

### Category

breakage

### Description

Blank page, it doesn't work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Firefox: 108
filterset (summary): 
  network: 110789
  cosmetic: 133741
  scriptlet: 22477
  html: 915
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 29057-685, 22m
    adguard-annoyance: 65031-4279, 19m
    fanboy-thirdparty_social: 68-1, 6d.19h.26m
    fanboy-annoyance: 81921-65154, 3d.13h.1m
    fanboy-cookiemonster: 46041-17458, 6d.19h.25m
    NOR-0: 3147-185, 16m
    SWE-1: 4327-312, 18m
  default: 
    user-filters: 221-8, never
    ublock-filters: 32867-298, 20m
    ublock-badware: 4707-0, 21m
    ublock-privacy: 341-1, 17m
    ublock-abuse: 78-0, 10d.15h.54m
    ublock-unbreak: 1942-0, 23m
    easylist: 64034-17537, 24m
    easyprivacy: 31040-1819, 3d.17h.5m
    plowe-0: 3750-2, 13d.11h.55m
    urlhaus-1: 6886-0, 14m
    ublock-quick-fixes: 379-1, 15m
filterset (user): [array of 222 redacted]
trustedset: 
  added: [array of 163 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 24 redacted]
urlRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 765 ms (selfie)
  maxAssetCacheWait: 927 ms
popupPanel: 
  blocked: 1
  no-cosmetic-filtering: true
  blockedDetails: 
    schibsted.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
||sdk.pulse.schibsted.com^$script,badfilter
||schibsted.com/pulse$badfilter
```


@lassekongo83
