### ISSUE TITLE
Custom Redirector

### ISSUE THREAD

**Issue by redirectads** [uBlockOrigin/uAssets#172]
### URL(s) where the issue occurs

`http://vaughnlive.tv/newzviewz`

### Describe the issue

this is what appears in the video and it can be blocked http://vaughnlive.tv/abvs.php but it removes the play/ pause and volume so please resolve this thanks but after 5 seconds you can click on the [X] and close it manually here is the website http://vaughnlive.tv/newzviewz.

I just put it in the My filters in uBlock it works but the media controls does not show up
Using Google Chrome i can use this Switcheroo RedirectorPlus
https://github.com/jkischel/SwitcherooPlus
Here is the original Switcheroo Redirector 
https://github.com/ranjez/Switcheroo

So my wish is can you uBlock Origin implement this so we can a custom redirect if uBlock can't block ads we can just redirect it.
The only way is to redirect it like this from http://vaughnlive.tv/abvs.php to http://google.com

### Screenshot(s)

Switcheroo Redirector Plus
<a href='https://postimg.org/image/589c0n97n/' target='_blank'><img src='https://s21.postimg.org/589c0n97n/redirect1.png' border='0' alt="redirect1"/></a><br/><br/> Switcheroo Redirector Plus
<a href='https://postimg.org/image/p45bg6q8z/' target='_blank'><img src='https://s21.postimg.org/p45bg6q8z/redirect2.png' border='0' alt="redirect2"/></a><br Switcheroo RedirectorPlus/><br/> Switcheroo Redirector Plus
<a href='https://postimg.org/image/fxn0swl0j/' target='_blank'><img src='https://s21.postimg.org/fxn0swl0j/redirect3.png' border='0' alt="redirect3"/></a><br/><br/> Shows With Ads and http://vaughnlive.tv/abvs.php are not blocked
<a href='https://postimg.org/image/anmnfcq5f/' target='_blank'><img src='https://s21.postimg.org/anmnfcq5f/withads1.png' border='0' alt="withads1"/></a><br/><br/> Shows Without Ads the Video Controls are gone and http://vaughnlive.tv/abvs.php are blocked
<a href='https://postimg.org/image/s26vnmnab/' target='_blank'><img src='https://s21.postimg.org/s26vnmnab/withoutads2.png' border='0' alt="withoutads2"/></a><br/><br/> 

### Versions

- Browser/version: Firefox 49.0.2
- uBlock Origin version: 1.9.12

### Settings

- I want uBO to have Switcheroo Redirector Plus implement that would be great.

### Notes

None.

**Comment by IDKwhattoputhere** [comment]
Firstly don't post direct links.
Secondly this could be abused by redirecting to malicious resources etc., no?

**Comment by redirectads** [comment]
Not really if you have ever used  Switcheroo Redirector Plus it's very useful since can't really block it because it's an OBJECT in the video. I found out only way to resolve it is to redirect it. But i can't use this here on Firefox only Google Chrome https://chrome.google.com/webstore/detail/switcheroo-redirector-plu/eneklinboooejmebmgibifnhdnehgdja

**Comment by redirectads** [comment]
Can you tell me how uBlock Origin can redirect from this http://vaughnlive.tv/abvs.php to http://google.com      Just a simple answer how can i get to work you have and redirect filters?

**Comment by gorhill** [comment]
It's not possible with uBO.

**Comment by redirectads** [comment]
Well that makes a lot more sense. I guess i could be able to just make a simple filter similar to easylist. Thank you. I never give up i believe uBO will be able to do it somehow. I let you know if i find a way.
