### ISSUE TITLE
pikabu.ru ads bypassing ubo

### ISSUE THREAD

**Issue by Vozf** [uBlockOrigin/uAssets#17201]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Some ads on the side are present and ads after videos are played are present

### URL(s) where the issue occurs.

pikabu.ru

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22998537/225680386-13f9e604-f2da-4fb4-abed-b4cc554ba183.png)

### uBO version

last

### Browser name and version

chrome last

### Settings

-

**Comment by Vozf** [comment]
![image](https://user-images.githubusercontent.com/22998537/225680995-1dce7be2-b900-48f4-8792-880df3a13c85.png)

**Comment by mapx-** [comment]
Did you enable RUAdList ?

However, if you still see ads report directly here:
https://github.com/easylist/ruadlist/issues

**Comment by Vozf** [comment]
yes I did, Ok I'll ask there
