### ISSUE TITLE
Breaks Amazon Browsing history

### ISSUE THREAD

**Issue by wesinator** [uBlockOrigin/uAssets#1720]
### URL(s) where the issue occurs

`https://www.amazon.com/gp/history`

### Describe the issue

uBlock Origin enabled on amazon.com prevents viewed items from being saved to Amazon browsing history.
#### To reproduce:
- With your Amazon browsing history enabled, view products on Amazon.

**Expected**: Items are saved in Amazon's browsing history.
**Actual**: With uBO enabled, viewed items do not get saved to browsing history. Disabling uBO immediately fixes the issue.

### Versions

- Browser/version: Chrome 64.0.3282.167 (Official Build)
- uBlock Origin version: uBlock Origin 1.15.2

### Settings

- Prevent WebRTC from leaking local IP addresses
- uBlock filters – Resource abuse

**Comment by krystian3w** [comment]
EasyPrivacy block amazon history in my test.

**Comment by cloves2017** [comment]
Is there anyway to stop ublock from blocking amazon history without fully disabling ublock? As an end user I want to be able to see my browsing history in amazon.

**Comment by mapx-** [comment]
Does this work for you 
`||amazon.*/uedata/$badfilter`

**Comment by cloves2017** [comment]
Tried adding this to my filters and then tried to white list, doesn't seem to work.

**Comment by mapx-** [comment]
try
`@@||amazon.*/*uedata$image,1p`

it seems ok for me

**Comment by cloves2017** [comment]
Are you putting this code inside the "filters list" or "white list" tab? thanks

**Comment by mapx-** [comment]
unbreak list

**Comment by gwarser** [comment]
> Are you putting this code inside the "filters list" or "white list" tab? thanks

Filters need to be pasted into [uBO Dashboard](https://github.com/gorhill/uBlock/wiki/Dashboard) -> [My filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) tab and apply changes.

but this filter is already added to `uBlock filters – Unbreak`

What you need is to open [uBO Dashboard](https://github.com/gorhill/uBlock/wiki/Dashboard) -> [Filter lists](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) -> click on the clock icon at the end of "uBlock filters - unbreak" line -> click on "Update now" on top.

**Comment by mapx-** [comment]
@OdinVex the issue is that the history was blocked.

Test these filters:

```
@@||amazon.*/*uedata$image,1p,badfilter
@@||fls-na.amazon.*/1/batch/1/OP/$image,domain=amazon.*
```

**Comment by mapx-** [comment]
history page
`https://www.amazon.com/gp/history`

a random page:
`https://www.amazon.com/IZOD-School-Uniform-Front-5-Pocket/dp/B09XJCLXQX/?_encoding=UTF8&_encoding=UTF8&ref_=dlx_deals_sc_dcl_img_dt_dealz_bsfy&pd_rd_w=IzGYr&content-id=amzn1.sym.af35a610-c824-445c-97b7-11ecfd25385a&pf_rd_p=af35a610-c824-445c-97b7-11ecfd25385a&pf_rd_r=GBCYVKNHZESERFQ1P385&pd_rd_wg=o1SGj&pd_rd_r=bd2db2ff-bd91-44b7-8b05-b705aebf9096`


if you do not whitelist this request you cannot see the item in the history page:

    https://fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:134-9257037-9403444:ZD8ZCD8180CNZYD6V61Y$uedata=s:%2Frd%2Fuedata%3Fat%26v%3D0.268364.0%26id%3DZD8ZCD8180CNZYD6V61Y%26m%3D1%26sc%3Dcsa%3Asi%26si%3D446%26pc%3D5338%26at%3D5338%26t%3D1699553025408%26pty%3DDetail%26spty%3DGlance%26pti%3DB09XJCLXQX%26tid%3DGBCYVKNHZESERFQ1P385%26aftb%3D1%26lob%3D1:5338
