### ISSUE TITLE
myabandonware.com: ads

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#17209]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ads spaces are still on site. They are on right side/middle of the site/perhaps even in the bottom of the site.

### URL(s) where the issue occurs.

`https://www.myabandonware.com/browse/name/`

### uBO version

1.47

### Browser name and version

Waterfox

### Settings

Added fanboy's annoyances and removed the other lists except by easylist/easyprivacy/ublock lists.

**Comment by krystian3w** [comment]
Due still missed by EL: https://github.com/easylist/easylist/issues/14300

I proved fix are compatible with CSS 2.1 (so with EasyList syntax):

```adb
! mostly top (but resize rest 5 a little): 
myabandonware.com##div[align="center"]

! left column (optional, too much move in left):
myabandonware.com##.box div:not([id]):not([class])

! sidebar:
myabandonware.com##.menu:not([class*=" "])
! or
myabandonware.com##div[class="menu"]
```


these works only in uBo/AdGuard now:

```adb
! it's center table instead move too much on left
myabandonware.com##.metas.box > div + div:style(margin: auto !important;)
```

Also possible use ABP ExtendedCSS:

```adb
myabandonware.com#?#div:-abp-has(> div[align="center"] > script:-abp-contains(freestar.config.enabled_slots.push))
```

to hide 5 form 6 placeholders.

**Comment by Felipefpl** [comment]
Thank you all for the fixes.

**Comment by Felipefpl** [comment]
@mapx- Ads are back on top - middle - almost the bottom of the page:

https://www.myabandonware.com/game/cheese-in-space-mh1

I didnt create a new thread to avoid making gorhill angry as he doesnt like it. ;)

**Comment by krystian3w** [comment]
@stephenhawk8054 check: https://github.com/easylist/easylist/issues/14300#issuecomment-1636736240

`https://www.myabandonware.com/game/halloween-mhp`
