### ISSUE TITLE
pcgamer.com: ads

### ISSUE THREAD

**Issue by ldene** [uBlockOrigin/uAssets#17202]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pcgamer.com/uk/`

### Category

ads

### Description

Advert is wrapped around the edge of the page, as well as in a banner above the main content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 91182
  cosmetic: 39006
  scriptlet: 17039
  html: 897
listset (total-discarded, last-updated): 
  added: 
    https://www.topcashback.co.uk/Misc/AdBlockWhiteList.aspx: 4974-0, 1d.20h.43m
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 32841-55, 1d.20h.42m
    ublock-badware: 4724-0, 1d.20h.41m
    ublock-privacy: 338-0, 6d.19h.59m
    ublock-abuse: 78-0, 6d.19h.58m
    ublock-unbreak: 1936-0, 1d.20h.40m
    easylist: 63781-579, 1d.20h.44m
    easyprivacy: 31028-1767, 6d.44m
    plowe-0: 3755-2, 11d.23h.56m
    urlhaus-1: 6870-0, 20h.39m
    ublock-quick-fixes: 375-0, 20h.38m
filterset (user): [empty]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 18 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 460 ms (selfie)
  maxAssetCacheWait: 151 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    celtra.com: 2
    doubleclick.net: 1
    facebook.com: 1
    google-analytics.com: 2
    google.com: 3
```
</details>

**Comment by mapx-** [comment]
remove this crap:
`https://www.topcashback.co.uk/Misc/AdBlockWhiteList.aspx`
