### ISSUE TITLE
search.brave.com: ads

### ISSUE THREAD

**Issue by 4StuffuNo** [uBlockOrigin/uAssets#17208]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://search.brave.com/search?q=best%20student%20credit%20card`

### Category

ads

### Description

First result is an ad and is labeled as such 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox Mobile: 111
filterset (summary): 
  network: 88946
  cosmetic: 28741
  scriptlet: 17102
  html: 926
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33038-280, 4d.8h.41m
    ublock-badware: 4718-0, 3d.8h
    ublock-privacy: 307-1, 4d.8h.43m
    ublock-abuse: 78-0, 4d.8h.42m
    ublock-unbreak: 1936-0, 4d.8h.4m
    ublock-quick-fixes: 382-0, 12h.31m
    adguard-mobile: 8542-120, 2d.12h.21m
    easylist: 64987-17611, 4d.19h.44m
    easyprivacy: 31047-1776, 3d.8h.1m
    urlhaus-1: 6886-0, 23h.57m
    plowe-0: 3757-2, 9h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1200 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    brave.com: 1
```
</details>

**Comment by Daxy7** [comment]
are you seeing it like [this](https://user-images.githubusercontent.com/91396482/225915151-de7eb6c3-7809-4bf2-8c94-0bb98c7c2629.png), or [this](https://user-images.githubusercontent.com/91396482/225915368-59b2e8e8-6def-4367-b518-0b08458daab5.png)?

**Comment by 4StuffuNo** [comment]
> are you seeing it like [this](https://user-images.githubusercontent.com/91396482/225915151-de7eb6c3-7809-4bf2-8c94-0bb98c7c2629.png), or [this](https://user-images.githubusercontent.com/91396482/225915368-59b2e8e8-6def-4367-b518-0b08458daab5.png)?
> 
> if first one, uBlock may be corrupted. if second, it's working as intended

It was the first one. I initially uninstalled uBlock and reinstalled without success. I now tried uninstalling and reinstalling Firefox which appears to have fixed it.
