### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by DarkDragon189** [uBlockOrigin/uAssets#17215]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=hmiNolZTgs8`

### Category

ads

### Description

So normally it blocks all the ads and pop ups on the websites I visit but recently it hasn't blocked all of them and I often see random pop ups and ads here and there. I have checked a few things on uBlock to see why it has been doing this but I'm not too familiar with these types of things so I don't know what to do. Anyways, ads and what not are appearing on websites where they should be blocked by uBlock but haven't been recently.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![image](https://user-images.githubusercontent.com/108380303/226062482-bd67961e-f479-4000-bbed-1d44e606af90.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 6898
  cosmetic: 8848
  scriptlet: 17104
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
    urlhaus-1: null
  default: 
    ublock-filters: 32889-35, 3d.17h.58m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 63866 ms (selfie)
  maxAssetCacheWait: 534 ms
popupPanel: 
  blocked: 1
  no-popups: true
  blockedDetails: 
    doubleclick.net: 1
```
</details>

**Comment by mapx-** [comment]
Reinstall uBO, then force update all the filter lists
