### ISSUE TITLE
pucks.io: breakage

### ISSUE THREAD

**Issue by RadioDM** [uBlockOrigin/uAssets#17216]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pucks.io/`
`https://www.bumpyball.io/`

### Category

breakage

### Description

After a game (maybe second as 1st, short game end might not yet trigger ad), where ads would be shown, the two given pages/games return error, and stops working. Other adblockers can block these ads without breaking game. 

### Screenshot(s)

<details>
<summary>Screenshot(s): pucks.io and bumpyball.io</summary>

![image](https://user-images.githubusercontent.com/96387517/226063717-7458e74a-b96a-48e9-9daa-c75de3d3b4d2.png)

![image](https://user-images.githubusercontent.com/96387517/226064271-6f7b60a5-9a58-4bc4-96ba-b9413633008a.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 116271
  cosmetic: 203964
  scriptlet: 35420
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 65057-96, 1d.9h.27m
    adguard-generic: 68631-754, 1d.9h.28m
    fanboy-annoyance: 81916-5526, 5d.9h.18m
  default: 
    user-filters: 10-0, never
    POL-0: 7884-8, 6h.44m
    POL-2: 1275-13, 22h.16m
    easylist: 63893-752, 2d.22h
    easyprivacy: 31057-1367, 6h.45m
    plowe-0: 3757-952, 5d.18h.47m
    ublock-abuse: 78-0, 6d.6h.59m
    ublock-badware: 4713-309, 1d.9h.31m
    ublock-filters: 32035-3940, 1d.9h.30m
    ublock-privacy: 290-8, 6d.6h.58m
    ublock-quick-fixes: 378-55, 6h.43m
    ublock-unbreak: 1927-87, 1d.9h.29m
    urlhaus-1: 6970-0, 6h.42m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 586 ms (selfie)
  maxAssetCacheWait: 631 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    applixir.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
@RadioDM update all filter lists and test again

@ghajini I commented
`||cdn.applixir.com^$script,3p`

do you remember why that filter has been added ?
https://github.com/uBlockOrigin/uAssets/commit/e9d2ad7256386f19e17a792cb1b1d0addc1d3194

**Comment by ghajini** [comment]
it was serving banner ads

**Comment by mapx-** [comment]
@RadioDM 

could you also test using these filters

```
||cdn.applixir.com^$script,3p
bumpyball.io,pucks.io##+js(set, invokeApplixirVideoUnit, noopFunc)
```

**Comment by RadioDM** [comment]
> could you also test using these filters
So in Opera, updating filter lists works (no error, and no ads), while putting the given 2 lines into "My filters" gives the error again

But in Edge (same uBO settings and lists), updating filter lists (and clearing cache) does not fix, but the given 2 lines put into "My filters" works (no error, no ads). 

No idea why it is upside down on different browsers

**Comment by mapx-** [comment]
Did you disable the tracking prevention feature in edge ?

**Comment by RadioDM** [comment]
outcome is the same with it on or off

**Comment by mapx-** [comment]
If you get the same error it means the lists aren't updated yet.
Check in the logger if you still see  `cdn.applixir.com` blocked

**Comment by RadioDM** [comment]
So `cdn.applixir.com` is always blocked on the page load, no matter which browser and if with 2 lines in "My filters" or just updated filter lists. When the ad is invoked on the website, there is never any new content logged in the uBO console, no matter if the page breaks or successfully continue without ad shown.

Today on Opera, the situation is the same as it is on Edge, so just filter lists wasn't enough to prevent crash occur. I had to add to the opera uBO the 2 lines into My filter, so after that there is no ad and no crash. On Edge nothing changed, still need the 2 lines
