### ISSUE TITLE
startpage.com: breakage

### ISSUE THREAD

**Issue by arimal199** [uBlockOrigin/uAssets#17219]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.startpage.com/sp/search`

### Category

breakage

### Description

not showing sidebars with wikipedia and other integrations

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 171159
  cosmetic: 170385
  scriptlet: 38503
  html: 1075
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 68801-5166, 1h.52m
    block-lan: 44-0, 1h.52m
    adguard-annoyance: 65104-4202, 1h.52m
    fanboy-cookiemonster: 46147-237, 1h.52m
    ublock-annoyances: 4835-4, 1h.52m
    ISR-0: 1680-0, 1h.52m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33765-74, 1h.52m
    ublock-badware: 4736-0, 1h.52m
    ublock-privacy: 342-0, 1h.52m
    ublock-abuse: 78-0, 1h.52m
    ublock-unbreak: 1939-2, 1h.52m
    ublock-quick-fixes: 378-0, 1h.52m
    easylist: 64085-610, 1h.52m
    adguard-spyware-url: 949-4, 1h.52m
    easyprivacy: 31058-1770, 1h.52m
    urlhaus-1: 6976-0, 1h.52m
    curben-phishing: 56886-24, 1h.52m
    plowe-0: 3755-2, 1h.52m
    LegitimateURLShortener: 2142-135, 1h.52m
filterset (user): [empty]
hostRuleset: 
  added: [array of 77 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 316 ms (selfie)
  maxAssetCacheWait: 250 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    startpage.com: 2
```
</details>

**Comment by mapx-** [comment]
> not showing sidebars with wikipedia and other integrations

I get no such sidebars even disabling uBO.
Are you using some startpage extension ?

**Comment by stephenhawk8054** [comment]
OP is using Librewolf, it includes `LegitimateURLShortener` and `curben-phishing` lists as default.

**Comment by Yuki2718** [comment]
> * [x]  I did not answer truthfully to **ALL** the above checkpoints.

And no screenshot
