### ISSUE TITLE
fili.cc

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1721]
`https://streamango.com/embed/drqclqrmfsfaecbq`

popads in other sites
`https://fili.cc/serial/sekta/s01e05/the-hole/13643`

to reproduce click streamango button and play the video
![2018-03-16- s01e05 the hole - sekta _ the path - fili cc - filiser filmy i seriale online](https://user-images.githubusercontent.com/5884000/37497736-98fe22f6-28ba-11e8-8455-61ba4d682042.png)

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.43
Chrome 65.0.3325.162

</details>

**Comment by okiehsch** [comment]
`https://fili.cc` is down on my end.
![unbenannt](https://user-images.githubusercontent.com/16838044/37498089-7fbcfcb6-28bc-11e8-8cc2-09f4b810870d.JPG)

**Comment by uBlock-user** [comment]
`https://fili.cc/` has been shut down for good.

**Comment by KonoromiHimaries** [comment]
@uBlock-user normaly works on my end

**Comment by mapx-** [comment]
does work `fili.cc` for you ? the issue is (was) with` fili.cc` not with `streamango`, right ?

**Comment by KonoromiHimaries** [comment]
@mapx- yes works for me

i have popups in all services using `streamango` player

**Comment by mapx-** [comment]
the fili.cc link is working for you or only the streamango link?

**Comment by KonoromiHimaries** [comment]
both works for me

**Comment by uBlock-user** [comment]
Must be a geo shut down then, I can't access it.

**Comment by KonoromiHimaries** [comment]
@uBlock-user yes, it is
