### ISSUE TITLE
55188.com: ads

### ISSUE THREAD

**Issue by qibin8687** [uBlockOrigin/uAssets#17214]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.55188.com/forum-8-1.html`

### Category

ads

### Description

twin columns listed along wiith main body can not be blocked by ublock element blocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 102
filterset (summary): 
  network: 103810
  cosmetic: 49344
  scriptlet: 17177
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 50-14, never
    CHN-0: 27828-104, 6h.46m
    easylist: 64051-97, 10h.47m
    easyprivacy: 31047-1194, 3d.3h.29m
    plowe-0: 3755-933, 8d.3h.30m
    ublock-abuse: 78-0, 8d.12h.52m
    ublock-badware: 4732-114, 6h.45m
    ublock-filters: 32022-98, 6h.44m
    ublock-privacy: 289-1, 8d.12h.48m
    ublock-quick-fixes: 379-32, 1h.16m
    ublock-unbreak: 1927-41, 6h.43m
    urlhaus-1: 6970-0, 1h.15m
filterset (user): [array of 50 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 275 ms (selfie)
  maxAssetCacheWait: 138 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    55188.com: 1
    baidu.com: 1
    bdstatic.com: 1
```
</details>

**Comment by Daxy7** [comment]
side:
`55188.com##.couplet`
banner:
`55188.com##.gg_head_c`

**Comment by JobcenterTycoon** [comment]
@Yuki2718 its a case for `CHN: AdGuard Chinese (中文)`

**Comment by mapx-** [comment]
I guess in the "normal" CHN list @cjx82630

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/c05be0018c9928679c501391cc3ae0c2f43b307f

**Comment by JobcenterTycoon** [comment]
Ok now im checking its because Adguard Chinese has EasyList China
