### ISSUE TITLE
androidrepublic.org: detection

### ISSUE THREAD

**Issue by mavisutera** [uBlockOrigin/uAssets#17213]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://androidrepublic.org/forums/team-ar-public-mods.91/`

### Category

detection

### Description

Once the page is loaded, you will notice there's big label in red color box mentioning to disable adblock, it clearly shows adblock is detected, and it renders the page in a blurry state.

Browser: MicrosoftEdge

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 85476
  cosmetic: 39248
  scriptlet: 17362
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63372-47, never
    easyprivacy: 31007-1172, never
    plowe-0: 3751-928, never
    ublock-abuse: 78-0, never
    ublock-badware: 4611-114, never
    ublock-filters: 32807-68, never
    ublock-privacy: 287-1, never
    ublock-quick-fixes: 340-17, never
    ublock-unbreak: 1922-59, never
    urlhaus-1: 6492-0, never
filterset (user): [array of 1 redacted]
trustedset: 
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 194 ms
  maxAssetCacheWait: 102 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    androidrepublic.org: 1
    cloudflareinsights.com: 1
    googlesyndication.com: 1
    typekit.net: 1
```
</details>

**Comment by Daxy7** [comment]
`https://androidrepublic.org/threads/recruitment-opportunity.18989/`
On forum page for me adblock was detected

The code for detection script
`https://pastebin.com/raw/cDh4hCzz`
