### ISSUE TITLE
linkedin.com: ads

### ISSUE THREAD

**Issue by cbannister9** [uBlockOrigin/uAssets#17217]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.linkedin.com/jobs/search/?currentJobId=3525642487&distance=25&f_WT=2&geoId=103112676&keywords=pharmacist`

### Category

[unknown]

### Description

stop promoted

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 85476
  cosmetic: 39247
  scriptlet: 17362
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63372-160, never
    easyprivacy: 31007-1172, never
    plowe-0: 3751-930, never
    ublock-abuse: 78-0, never
    ublock-badware: 4611-0, never
    ublock-filters: 32807-86, never
    ublock-privacy: 287-0, never
    ublock-quick-fixes: 340-0, never
    ublock-unbreak: 1922-58, never
    urlhaus-1: 6492-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 532 ms
  maxAssetCacheWait: 5 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Yuki2718** [comment]
promoted what? Such sites like LinkedIn requires at least screenshot(s). I only see promotion for Premium.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Yuki2718** [comment]
I can't reproduce, which country/region do you access from?

**Comment by Yuki2718** [comment]
Still no problem in scrolling

**Comment by Yuki2718** [comment]
Did you narrow down the cause? I'm not very willing to waste more time on this.

**Comment by Yuki2718** [comment]
Default + all EasyList/AG Annoyances with `brave browser linkedin` search => linkedin, no issue at all.

**Comment by mapx-** [comment]
@Oxygen112 if you have issues with that site just disable the shields for it in brave.
You should also keep only EL annoyances or Adguard annoyances, not both of them.
