### ISSUE TITLE
[nsfw] e621.net: privacy

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17212]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://e621.net/posts?tags=test1`

### Category

[unknown]

### Description

tracking from dragonfru.it

`plausible.dragonfru.it/js/script.js -> plausible.dragonfru.it/api/event`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/91396482/225929116-55a0244b-0f75-4b2a-bda8-7be4c8782123.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 78187
  cosmetic: 42350
  scriptlet: 20971
  html: 1066
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 1h.48m
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1488-0, 1h.49m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 3d.4h.31m
    ublock-annoyances: 4831-4, 1d.6h.38m
  default: 
    user-filters: 1571-13, never
    ublock-filters: 33787-82, 1d.5h.22m
    ublock-badware: 4724-0, 3d.4h.31m
    ublock-privacy: 341-0, 3d.4h.31m
    ublock-abuse: 78-0, 3d.4h.31m
    ublock-unbreak: 1936-0, 3d.4h.31m
    ublock-quick-fixes: 378-0, 1h.50m
    easylist: 64026-250, 1d.5h.22m
    easyprivacy: 31054-2160, 1d.5h.22m
filterset (user): [array of 599 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 287 ms (selfie)
  maxAssetCacheWait: 206 ms
  unsuspendAfter: 146 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    dragonfru.it: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@ryanbr
