### ISSUE TITLE
prescouter.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#17211]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.prescouter.com/2014/04/malware-infection-rate-for-android-devices-measured-by-researchers/`

### Category

nuisance

### Description

Newsletter registration prompt.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-03-17 at 15-45-01 Malware Infection Rate For Android Devices Measured By Researchers - PreScouter - Custom Intelligence from a Global Network of Experts](https://user-images.githubusercontent.com/101707608/225923791-318f15c3-cb6d-4d69-bd60-b8d90abbbc61.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 263975
  cosmetic: 242172
  scriptlet: 39101
  html: 1064
listset (total-discarded, last-updated): 
  added: 
    https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 49715-1797, 2d.5h.7m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38703-7038, 2d.5h.7m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 37491-586, 5h.2m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1066-0, 2d.5h.7m
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 5h.1m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 73-0, never
    https://www.i-dont-care-about-cookies.eu/abp/: 25605-7, 2d.5h.7m
    adguard-generic: 68603-6146, 2d.5h.7m
    adguard-mobile: 8542-819, 2d.5h.7m
    adguard-spyware-url: 940-4, 2d.5h.7m
    block-lan: 44-0, 2d.5h.7m
    curben-phishing: 56069-27, 5h.5m
    curben-pup: 191-0, 5h.4m
    adguard-annoyance: 64986-7454, 2d.5h.7m
    adguard-social: 19947-85, 2d.5h.7m
    fanboy-thirdparty_social: 69-0, 2d.5h.7m
    fanboy-annoyance: 81982-10712, 2d.5h.7m
    ublock-annoyances: 4820-6, 2d.5h.7m
    dpollock-0: 11342-912, 2d.5h.7m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33751-260, 2d.5h.7m
    ublock-badware: 4707-0, 2d.5h.7m
    ublock-privacy: 341-0, 2d.5h.7m
    ublock-abuse: 78-3, 2d.5h.7m
    ublock-unbreak: 1938-0, 2d.5h.7m
    ublock-quick-fixes: 378-0, 5h.7m
    easylist: 63897-22340, 2d.5h.7m
    easyprivacy: 31054-14979, 2d.5h.7m
    urlhaus-1: 6820-0, 5h.6m
    plowe-0: 3757-4, 2d.5h.7m
    GRC-0: 995-2, 5h.3m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2357 ms (selfie)
  maxAssetCacheWait: 1008 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    prescouter.com: 2
    bing.com: 1
    googletagmanager.com: 2
    hellobar.com: 2
    licdn.com: 1
    pushengage.com: 2
    wp.com: 2
```
</details>

**Comment by Daxy7** [comment]
block with 

`www.prescouter.com##.sgpb-popup-dialog-main-div-wrapper`
