### ISSUE TITLE
techpowerup.com: breakage

### ISSUE THREAD

**Issue by DanielGianstefani** [uBlockOrigin/uAssets#17226]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.techpowerup.com/306095/crucial-t700-pcie-5-0-ssd-preview-unit-hits-12-gb-s-read-and-write-speeds-may-2023-release-hinted`

### Category

breakage

### Description

Blocks hosted images from the article.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/128243766/226117263-147994e7-81d5-41a7-bf9e-e26ee3e51786.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 86463
  cosmetic: 38898
  scriptlet: 16957
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64053-44, 1d.17h.4m
    easyprivacy: 31040-1174, 5d.17h.44m
    plowe-0: 3755-931, 12d.22h.7m
    ublock-abuse: 78-0, 20h.40m
    ublock-badware: 4732-114, 1d.17h.3m
    ublock-filters: 32023-83, 1d.17h.2m
    ublock-privacy: 293-1, 20h.39m
    ublock-unbreak: 1928-39, 1d.17h.1m
    urlhaus-1: 6970-0, 21h.51m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2809 ms (selfie)
  maxAssetCacheWait: 73 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    techpowerup.com: 5
    google-analytics.com: 3
```
</details>

**Comment by JobcenterTycoon** [comment]
I removed the obsolete filter now. Should work fine after a filterlist update.
