### ISSUE TITLE
kulturalnemedia.pl: breakage

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#17228]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

With uBO enabled, images don't load:
- in Firefox can always reproduce
- in Opera can reproduce only sometimes:
   - need to reload the page several times (F5),
   - if still can't reproduce, then need to try hard reload several times (CTRL + F5)

With uBO disabled, images always load

I'm not sure:
- which specific list causing it or multiple lists
- why different behaviour on different browsers
- eventually it might turn out to be a nasty random issue caused by the site itself

### URL(s) where the issue occurs.

`https://kulturalnemedia.pl`

### Screenshot(s)

BAD: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/226124185-b5052254-bd8d-4930-a2cf-408c1ad54fb1.png)
GOOD: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/226124139-a558c32f-7acf-4adc-aa03-769c7efaeae9.png)

### uBO version

1.47.5rc4

### Browser name and version

Firefox 111 & Opera 95

### Settings

-

**Comment by mapx-** [comment]
```
*$script,domain=kulturalnemedia.pl,redirect-rule=noopjs
@@||partner.googleadservices.com/gampad/cookie.js$script,domain=kulturalnemedia.pl
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=kulturalnemedia.pl
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*/show_ads_impl_$script,domain=kulturalnemedia.pl
```

**Comment by garry-ut99** [comment]
Still not works.

**Comment by stephenhawk8054** [comment]
Do these work?

```adb
@@||googleads.g.doubleclick.net/pagead/ads$subdocument,domain=kulturalnemedia.pl
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=kulturalnemedia.pl
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*/show_ads_impl$script,domain=kulturalnemedia.pl
```

**Comment by mapx-** [comment]
another try

```
*$script,domain=kulturalnemedia.pl,redirect-rule=noopjs
@@||partner.googleadservices.com/gampad/cookie.js$script,domain=kulturalnemedia.pl
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=kulturalnemedia.pl
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/$script,domain=kulturalnemedia.pl
@@||adservice.google.com/adsid/integrator.js?domain=kulturalnemedia.pl$script,domain=kulturalnemedia.pl
@@||googleads.g.doubleclick.net/pagead/ads$frame,domain=kulturalnemedia.pl
```

**Comment by garry-ut99** [comment]
All of the 3 propositions work always when CTRL + F5, but never (or very rare) with F5.

**Comment by mapx-** [comment]
The last filters are working fine in FF with F5, tested / retested (with POL lists enabled too)

**Comment by stephenhawk8054** [comment]
It worked on F5 for me on both firefox and chromium.

**Comment by garry-ut99** [comment]
I've debugged a little and I've noticed that (on both Firefox and Opera):
- every time the issue (images not loading) occurs, there is an jQuery error in the web console: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/226169386-506b13a4-e96c-4a15-90ac-8f2fc1939834.png)
- when the issue not occurs (images loading fine), the jQuery error is not present then

Another strange thing is that:
- when the issue (images not loading) occurs without dev console opened, pressing F12 (opening web console) makes the images load
- the same happens in the opposite direction: when the issue (images not loading) occurs with dev console opened, pressing F12 (closing web console) makes the images load

Now I remember experiencing the same issue in the past on: either the same site or other sites, and it's caused by bugged jQuery version.

**Comment by mapx-** [comment]
No issue in chrome / opera.

So, it's only a poor site implementation for firefox.

**Comment by garry-ut99** [comment]
> in Opera can reproduce only sometimes
> No issue in chrome / opera.

For me, on Opera, now the images are broken every visit.

The images breakage is caused by uBO, not by the site, because uBO blocks some google resources which are required by the site's scripts to display images properly, even if the root of the issue is due to bugs or a bad design in the site itself or bugs in jQuery, the images are displayed properly without uBO, and with uBO enabled images are broken, which makes a news site really dysfunctional.  Filter maintentainers can either:
- to not fix the breakage, adn prefer to keep a privacy with the side effect / cost of a broken and dysfunctional site, 
- or to fix, in this case this works: `@@||*google*$script,subdocument,xhr,domain=kulturalnemedia.pl`

**Comment by stephenhawk8054** [comment]
I don't think `@@||*google*$script,subdocument,xhr,domain=kulturalnemedia.pl` is a good idea as any malicious connection that's not google's resource just needs to add `google` into the link and it's unblocked.

Do these work for anyone?

```adb
@@||google.com^$script,frame,xhr,domain=kulturalnemedia.pl
@@||google.com.*^$script,frame,xhr,domain=kulturalnemedia.pl
@@||google-analytics.com^$script,frame,xhr,domain=kulturalnemedia.pl
@@||googleadservices.com^$script,frame,xhr,domain=kulturalnemedia.pl
@@||googlesyndication.com^$script,frame,xhr,domain=kulturalnemedia.pl
@@||googletagmanager.com^$script,frame,xhr,domain=kulturalnemedia.pl
@@||googleads.g.doubleclick.net^$script,frame,xhr,domain=kulturalnemedia.pl
```

**Comment by garry-ut99** [comment]
I didn't think about that, maybe you are right, your solution works fine, as it covers 22 out of 23 requests I needed to whitelist, the only one which left is `google.pl`.

But I've noticed another problem, appearing after adding whichever whitelist solution: sometimes an anti-adblock pop ups (if can't reproduce, need to try reloading site several times): [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/226558678-8a9c87dd-7089-4e16-9b6f-82e571915b55.png)

**Comment by garry-ut99** [comment]
I get anti-adblock on both Firefox & Opera, on default +  2 x POL lists, regardless of using F5 or CTRL + F5 to reproduce, it appears about once out of ten times, so it's best to try to reload 20 times to rperoduce.
