### ISSUE TITLE
AppMind radio group: ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17227]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

```
canli-radyo-dinle.com
emisorascolombianas.co
fmradiofree.com
greek-radio.org
internetradio-horen.de
internetradio-schweiz.ch
onlineradio-bg.com
radio-ao-vivo.com
radio-australia.org
radio-belgie.be
radio-canada-online.com
radio-danmark.dk
radio-dominicana.com
radio-ecuador.org
radio-en-ligne.fr
radio-en-vivo.mx
radio-espana.es
radio-hk.com
radio-hrvatska.com
radio-italiane.it
radio-korea.com
radio-maroc.org
radio-nederland.nl
radio-new-zealand.co.nz
radio-nigeria.com
radio-norge.org
radio-osterreich.at
radio-philippines.com
radio-south-africa.co.za
radio-polska.pl
radio-suomi.com
radio-sveriges.se
radio-thai.com
radio-trinidad.com
radio-ua.com
radio-uk.co.uk
radioindia.in
radioindonesia.org
radiojapan.org
radios-argentinas.org
radios-bolivia.com
radios-chilenas.com
radios-online.pt
radios-venezuela.com
radiosdelperu.pe
radiotaiwan.tw
```

### Category

ads

### Description

Filter
```
canli-radyo-dinle.com,emisorascolombianas.co,fmradiofree.com,greek-radio.org,internetradio-horen.de,internetradio-schweiz.ch,onlineradio-bg.com,radio-ao-vivo.com,radio-australia.org,radio-belgie.be,radio-canada-online.com,radio-danmark.dk,radio-dominicana.com,radio-ecuador.org,radio-en-ligne.fr,radio-en-vivo.mx,radio-espana.es,radio-hk.com,radio-hrvatska.com,radio-italiane.it,radio-korea.com,radio-maroc.org,radio-nederland.nl,radio-new-zealand.co.nz,radio-nigeria.com,radio-norge.org,radio-osterreich.at,radio-philippines.com,radio-polska.pl,radio-south-africa.co.za,radio-suomi.com,radio-sveriges.se,radio-thai.com,radio-trinidad.com,radio-ua.com,radio-uk.co.uk,radioindia.in,radioindonesia.org,radiojapan.org,radios-argentinas.org,radios-bolivia.com,radios-chilenas.com,radios-online.pt,radios-venezuela.com,radiosdelperu.pe,radiotaiwan.tw###body_centered_ad
```
to be added

```
radios-guatemala.com 
radioscostarica.org 
radios-uruguay.com 

podcasts-online.org
```
 Special case. Different site layouts.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 78286
  cosmetic: 42433
  scriptlet: 20987
  html: 1069
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 1h.1m
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1488-0, 1h.1m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 1h.1m
    ublock-annoyances: 4835-4, 1h.1m
  default: 
    user-filters: 1572-13, never
    ublock-filters: 33863-139, 1h.1m
    ublock-badware: 4747-0, 1h.1m
    ublock-privacy: 342-0, 1h.1m
    ublock-abuse: 78-0, 1h.1m
    ublock-unbreak: 1942-1, 1h.1m
    ublock-quick-fixes: 387-0, 1h.1m
    easylist: 64106-182, 1h.1m
    easyprivacy: 31059-2176, 1h.1m
filterset (user): [array of 601 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 305 ms (selfie)
  maxAssetCacheWait: 329 ms
  unsuspendAfter: 98 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    doubleclick.net: 1
    googletagmanager.com: 1
    taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
You have to report these ads to easylist and / or some regional lists

**Comment by DandelionSprout** [comment]
It's been 2 or 4 months now depending on the counting method, and it doesn't seem like the EasyList team has even noticed these reports.
