### ISSUE TITLE
[nsfw] reddit.com: nuisance

### ISSUE THREAD

**Issue by stephan8063** [uBlockOrigin/uAssets#17225]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reddit.com/r/gaming/comments/11uicve/the_new_diablo_4_snow_physics_is_unreal/`

### Category

nuisance

### Description

Any NSFW reddit page while not logged in. Android Firefox. filter blocks the NSFW pop-up, but doesn't block something else. This leaves the webpage unresponsive. Either needs a stronger filter to remove the "glass pane" between the user and the webpage, or a weaker filter to provide the actual error/content message to the user. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox Mobile: 111
filterset (summary): 
  network: 87692
  cosmetic: 29020
  scriptlet: 17115
  html: 933
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33080-299, 1d.22h.2m
    ublock-badware: 4684-0, 21h.17m
    ublock-privacy: 337-1, 11d.14h.8m
    ublock-abuse: 78-0, 8d.11h.12m
    ublock-unbreak: 1943-0, 1d.22h.3m
    ublock-quick-fixes: 383-0, 12h.1m
    adguard-mobile: 8557-120, 3h.38m
    easylist: 63888-17444, 3d.20h.41m
    easyprivacy: 31048-1776, 5d.9h.46m
    urlhaus-1: 6820-0, 1d.12h.28m
    plowe-0: 3757-2, 6d.6h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2897 ms (selfie)
  maxAssetCacheWait: 812 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Daxy7** [comment]
it works if you go to 
`https://old.reddit.com/r/gaming/comments/11uicve/the_new_diablo_4_snow_physics_is_unreal/`
or opt out of new Reddit if you have an account by going to settings and then ticking
- [ ] Opt out of the redesign

**Comment by mapx-** [comment]
Same behaviour disabling uBO.

**Comment by stephan8063** [comment]
I mean, you're wrong. If you don't want to do anything fine. But at least
bother with a good excuse.

**Comment by stephenhawk8054** [comment]
If I understand the issue correctly, you need filters that remove the nsfw modal?

**Comment by Daxy7** [comment]
> Try (Mobile only): `reddit.com##^xpromo-nsfw-blocking-modal`

Used IOS user agent and the modal dissapears but [NSFW images/videos are blocked](https://user-images.githubusercontent.com/91396482/226168914-a087250e-45e8-490a-9cb7-e252bab4568c.png), same with Android ua

**Comment by stephenhawk8054** [comment]
You need a userscript to bring the actual image to that location. In that location, the image they use is `https://preview.redd.it/4r76hz8ijgoa1.png?blur=40&format=pjpg&auto=webp&v=enabled&s=ec43719b7307f099869dfb214cae6ef42c6c8133` which is already a blurred image. The real image lies in the next element in the DOM, which is not showed in the first place.

This is how the DOM looks:

```html
<shreddit-blurred-container mode="slot" reason="nsfw" is-shredtop-pdp="">
	<div slot="blurred">
		<div class="max-h-[100vw] h-full w-full object-contain"> <img id="post-image" alt="r/gaming - The new Diablo 4 snow physics is unreal." class="max-h-[100vw] h-full w-full object-contain" loading="eager" src="https://preview.redd.it/4r76hz8ijgoa1.png?blur=40&amp;format=pjpg&amp;auto=webp&amp;v=enabled&amp;s=ec43719b7307f099869dfb214cae6ef42c6c8133"> </div>
		<script nonce="">
		function recordImagePerformanceMark() {
			performance.mark('first-post-meaningful-paint');
		}
		document && document.getElementById('post-image').addEventListener('load', recordImagePerformanceMark);
		</script>
	</div>
	<div slot="revealed" class="h-full">
		<div class="max-h-[100vw] h-full w-full object-containborder-none xs:rounded-[16px] relative overflow-hidden bg-black/20"> <img alt="" role="presentation" class="absolute top-0 left-0 w-full opacity-20 post-background-image-filter" loading="eager" src="https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?width=640&amp;crop=smart&amp;auto=webp&amp;v=enabled&amp;s=2c84aa27d76e24b117c31ebfc5fe965ca6944f6b" srcset="https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?width=320&amp;crop=smart&amp;auto=webp&amp;v=enabled&amp;s=2772b6935169a78247d9ba301ca17afb863f12b4 320w, https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?width=640&amp;crop=smart&amp;auto=webp&amp;v=enabled&amp;s=2c84aa27d76e24b117c31ebfc5fe965ca6944f6b 640w, https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?width=1080&amp;crop=smart&amp;auto=webp&amp;v=enabled&amp;s=3e1530a14532bc8c060783abad4b34d1763fa6ae 1080w, https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?auto=webp&amp;v=enabled&amp;s=af0d4ea173723a5dd40ae7a47076c63a23698600 1851w" sizes="(min-width: 1024px) 50vw, 100vw">
			<a href="https://i.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?s=02a208ee4310ad49e8810ac7f944f272c8b595d1" title="Image from r/gaming - The new Diablo 4 snow physics is unreal." rel="noopener noreferrer ugc" target="_blank"> <img alt="r/gaming - The new Diablo 4 snow physics is unreal." class="max-h-[100vw] h-full w-full object-contain relative" loading="lazy" src="https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?width=640&amp;crop=smart&amp;auto=webp&amp;v=enabled&amp;s=2c84aa27d76e24b117c31ebfc5fe965ca6944f6b" srcset="https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?width=320&amp;crop=smart&amp;auto=webp&amp;v=enabled&amp;s=2772b6935169a78247d9ba301ca17afb863f12b4 320w, https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?width=640&amp;crop=smart&amp;auto=webp&amp;v=enabled&amp;s=2c84aa27d76e24b117c31ebfc5fe965ca6944f6b 640w, https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?width=1080&amp;crop=smart&amp;auto=webp&amp;v=enabled&amp;s=3e1530a14532bc8c060783abad4b34d1763fa6ae 1080w, https://preview.redd.it/the-new-diablo-4-snow-physics-is-unreal-v0-4r76hz8ijgoa1.png?auto=webp&amp;v=enabled&amp;s=af0d4ea173723a5dd40ae7a47076c63a23698600 1851w" sizes="(min-width: 1024px) 50vw, 100vw"> </a>
		</div>
	</div>
</shreddit-blurred-container>
```

What you need to do is to remove the current `slot="blurred"` and change `slot="revealed"` to `slot="blurred"`, then apply these filters:

```adb
reddit.com##^xpromo-nsfw-blocking-modal
reddit.com##.prompt
reddit.com##.blurred:style(filter: none !important;)
reddit.com##.post-background-image-filter:style(filter: none !important; opacity: 1 !important;)
```

**Comment by stephenhawk8054** [comment]
It still shows for me

![image](https://user-images.githubusercontent.com/66517106/226170921-577e8f01-f283-4cc2-89f4-275008aa2f5d.png)

**Comment by mapx-** [comment]
like @Daxy7 said, enough using the old one
`https://old.reddit.com/r/gaming/comments/11uicve/the_new_diablo_4_snow_physics_is_unreal/`
