### ISSUE TITLE
coins-battle.com: detection

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#17229]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://coins-battle.com/`

### Category

detection

### Description

@stephenhawk8054 @JobcenterTycoon 
Please help for this issue, detection adblock. Thanks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox Mobile: 113
filterset (summary): 
  network: 88086
  cosmetic: 29399
  scriptlet: 17537
  html: 957
listset (total-discarded, last-updated): 
  default: 
    user-filters: 168-3, never
    ublock-filters: 34001-350, 1d.5h.56m
    ublock-badware: 4730-0, 1d.5h.56m
    ublock-privacy: 342-1, 1d.5h.56m
    ublock-abuse: 78-0, 1d.5h.56m
    ublock-unbreak: 1943-1, 1d.5h.55m
    ublock-quick-fixes: 388-6, 4h.5m
    adguard-mobile: 8553-120, 1d.5h.55m
    easylist: 64052-17454, 1d.5h.54m
    easyprivacy: 31057-1776, 1d.5h.53m
    urlhaus-1: 6802-0, 4h.4m
    plowe-0: 3755-2, 1d.5h.53m
filterset (user): [array of 60 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 819 ms (selfie)
  maxAssetCacheWait: 343 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    d3u598arehftfk.cloudfront.net: 1
    googletagmanager.com: 1
    hostingcloud.racing: 1
    vlitag.com: 2
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed.

Just a note: You do not need to ping us all the time when you open a new issue. We see all open issues in the issue tracker.

**Comment by king-iskan** [comment]
This working just in Firefox, for browser chromium based not working

**Comment by mapx-** [comment]
It's ok for me too in chrome.

**Comment by mapx-** [comment]
if FF android is ok just use it.
