### ISSUE TITLE
startpage.com: ads

### ISSUE THREAD

**Issue by 0xL33t** [uBlockOrigin/uAssets#17221]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.startpage.com/sp/search`

### Category

ads

### Description

Hey everyone,

just noticed this one ad popping up on Startpage. It happens with every query and is this sponsored link just on top of the page (refer to screenshot).

Hopefully it is reproducible for you and easily fixed.

Thank you all

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230318_103517_Firefox](https://user-images.githubusercontent.com/25265569/226097691-befdf99a-6d69-4782-813b-da95c4464bf6.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox Mobile: 111
filterset (summary): 
  network: 90543
  cosmetic: 33382
  scriptlet: 17484
  html: 948
listset (total-discarded, last-updated): 
  added: 
    DEU-0: 6686-388, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 34004-321, now
    ublock-badware: 4730-0, now
    ublock-privacy: 342-1, now
    ublock-abuse: 78-0, now
    ublock-unbreak: 1944-1, now
    ublock-quick-fixes: 388-0, now
    adguard-mobile: 8557-128, now
    easylist: 64106-17463, now
    easyprivacy: 31059-1785, now
    urlhaus-1: 6976-0, now
    plowe-0: 3755-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1247 ms (selfie)
  maxAssetCacheWait: 293 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    startpage.com: 1
```
</details>

**Comment by mapx-** [comment]
maybe the generic cosmetic filter are disabled and this EL filter is not applied:

`##.house-ads`

reset uBO to defaults and disable `Ignore generic cosmetic filters` setting

or add

`startpage.com##.house-ads`

**Comment by 0xL33t** [comment]
That did it. Thank you for the quick help!
