### ISSUE TITLE
fruitstreams.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1722]
`http://streamango.com/embed/keebnatkanmlsobk`

popads in other sites
`http://alltube.pl/riverdale/chapter-twenty-eight-there-will-be-blood/odcinek-15-sezon-2/137855`

to reproduce click streamango button and play the video
![2018-03-16-riverdale - odcinek 15 sezon 2 alltube - filmy i seriale online](https://user-images.githubusercontent.com/5884000/37519810-d981497e-291a-11e8-8109-584d12cb20df.png)

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.34
Nano Defender 13.43
Chrome 65.0.3325.162

</details>

**Comment by uBlock-user** [comment]
patched in uBlock Filters already.

```
streamango.com##script:inject(openload.co.js)
streamango.com##script:inject(abort-on-property-read.js, BetterJsPop)
streamango.com##script:inject(window.open-defuser.js)
```

**Comment by KonoromiHimaries** [comment]
@uBlock-user not worked in other sites

**Comment by uBlock-user** [comment]
Works perfectly fine on uBlock Origin, you're using Nano Adblocker.

**Comment by uBlock-user** [comment]
Works perfectly fine on uBlock Origin, you're using Nano Adblocker.

**Comment by KonoromiHimaries** [comment]
right

**Comment by KonoromiHimaries** [comment]
i still have a sometimes popup

**Comment by uBlock-user** [comment]
can't reproduce it on my end. I click play it plays, nothing else happens.

**Comment by KonoromiHimaries** [comment]
![untitled](https://user-images.githubusercontent.com/5884000/37524307-be8370ca-2929-11e8-9977-80d657d9c741.gif)

**Comment by uBlock-user** [comment]
Add

```
||liczniki.org^
||ininmacerad.pro^
||debadu.com^
||puserving.com^
||ffinwwfpqi.gq^
```

**Comment by KonoromiHimaries** [comment]
@uBlock-user still have a popads

**Comment by uBlock-user** [comment]
Not enough blocking on your end, all those domains are blocked along with popads on my end and everything goes flawless...

**Comment by mapx-** [comment]
test these filters
```
||alltube.pl^$csp=script-src 'self' 'unsafe-eval' 'unsafe-inline' data: *.gstatic.com *.google.com *.alltube.tv *.google-analytics.com *.googleapis.com
||alltube.pl^$csp=child-src 'self' *.streamango.com http://alltube.tv *.google.com *.speedvid.net
```

**Comment by uBlock-user** [comment]
you can merge it into one filter when defining multiple CSP policies

`||alltube.pl^$csp=script-src 'self' 'unsafe-eval' 'unsafe-inline' data: *.gstatic.com *.google.com *.alltube.tv *.google-analytics.com *.googleapis.com;child-src 'self' *.streamango.com http://alltube.tv *.google.com *.speedvid.net`

**Comment by KonoromiHimaries** [comment]
@mapx- i still have a popads

**Comment by mapx-** [comment]
You should test again in a completely new profile

**Comment by KonoromiHimaries** [comment]
in firefox 59 (nano adblocker - default set) = all ok
in opera 51 (ublock origin - default set) = all ok
in chrome 65 (ublock origin - default set) [clear cookie/cache + click ctrl+f5 in private mode] = bad popups i still seeing

**Comment by uBlock-user** [comment]
@KonoromiHimaries Disable all extensions except uBlock Origin and try again.

**Comment by KonoromiHimaries** [comment]
@uBlock-user i tried, and i have the same effect

**Comment by uBlock-user** [comment]
Sorry, I don't have anything else left to suggest.

**Comment by nimasaj** [comment]
@KonoromiHimaries, Do you have "**UBo Extra**" installed on Chrome? if not, please install it beside UBo and try again.

**Comment by okiehsch** [comment]
I can reproduce,
````
fruitstreams.com##script:inject(abort-on-property-read.js, _0xd959)
fruitstreams.com##script:inject(popads-dummy.js)
````
fixes the issue on my end.

**Comment by uBlock-user** [comment]
That's another clone of openload, yep that needs patching.

**Comment by okiehsch** [comment]
OK, I think
````
fruitstreams.com##script:inject(openload.co.js)
fruitstreams.com##script:inject(window.open-defuser.js)
````
should be sufficient.
@KonoromiHimaries if you can confirm, the filters will be added.

**Comment by KonoromiHimaries** [comment]
popups left gone, thanks : )

**Comment by KonoromiHimaries** [comment]
@okiehsch

**Comment by KonoromiHimaries** [comment]
works perfect, thanks : )

**Comment by KonoromiHimaries** [comment]
works perfect, thanks : )

**Comment by Hrxn** [comment]
So this can be closed (again)?

**Comment by KonoromiHimaries** [comment]
@okiehsch popads has back

**Comment by okiehsch** [comment]
How can I reproduce?
If I go to `http://alltube.pl/riverdale/chapter-twenty-eight-there-will-be-blood/odcinek-15-sezon-2/137855` and click the `streamango` button I can play the video without any popups.

**Comment by KonoromiHimaries** [comment]
after checking occurs only on `fili.cc`
https://github.com/uBlockOrigin/uAssets/issues/1721

**Comment by SMed79** [comment]
@okiehsch 

> How can I reproduce?

`fruitstreams.com` redirect me to `fruitadblock.net`

==>> https\://**fruitadblock.net**/embed/oepenqokqccfbfbt`

the `webrtc` filter does not help (see https://streamable.com/e/lzr3w/kbxfae)

When I abort `isSandboxed, fruitadblock` I get [propellerads popups](https://streamable.com/e/xaom5/jcxqzn
) instead of the ip adress popup.

Only the fix added here [#df3c9e63](https://github.com/uBlockOrigin/uAssets/commit/df3c9e639e561310c4d49fbb2b9e1179cc105743) by @marx work for me.

**Comment by okiehsch** [comment]
Well, looking at your second video you added 
````
streamango.com,streamango.com##script:inject(abort-current-inline-script.js, isSandboxed, fruitadblock)
````
and then loaded a `fruitSTREAMs` and got redirected to `fruitadblock`.

Does
`fruitstreams.com##script:inject(abort-current-inline-script.js, isSandboxed, fruitadblock)`
work, i.e, you do not get redirected to `fruitadblock`.

**Comment by SMed79** [comment]
> Does
> fruitstreams.com##script:inject(abort-current-inline-script.js, isSandboxed, fruitadblock)
> work, i.e, you do not get redirected to fruitadblock.

Yes work, (no redirection) and [the popups](http://i.imgur.com/TuA7mQf.png) are managed by easylist filters

Thank you for your time.
