### ISSUE TITLE
newyorker.com: breakage

### ISSUE THREAD

**Issue by jxxe** [uBlockOrigin/uAssets#17230]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.newyorker.com/account/profile`

### Category

breakage

### Description

None of the account information is loaded

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Enabled:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/64276359/226150774-a22e3ef1-5ca2-444e-89c6-7d6bf7cc3f02.png">

Disabled:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/64276359/226150789-5744d260-4000-4a3b-9e70-604c9af2464d.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 86386
  cosmetic: 39055
  scriptlet: 17046
  html: 898
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32852-69, 1d.3h.2m
    ublock-badware: 4736-0, 1d.3h.1m
    ublock-privacy: 342-0, 1d.3h.4m
    ublock-abuse: 78-0, 1d.3h.3m
    ublock-unbreak: 1940-1, 1d.3h
    ublock-quick-fixes: 387-0, 2h.21m
    easylist: 64026-582, 2d.3h.7m
    easyprivacy: 31059-1767, 22h.57m
    urlhaus-1: 6802-0, 2h.22m
    plowe-0: 3757-2, 5d.3h.47m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3874 ms (selfie)
  maxAssetCacheWait: 157 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    newyorker.com: 3
    amazon-adsystem.com: 1
    bing.com: 1
    condenastdigital.com: 2
    datadoghq-browser-agent.com: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    indexww.com: 1
    moatads.com: 1
    parsely.com: 1
    zqtk.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test if adding this filter works?

```adb
@@||martech.condenastdigital.com/lib/martech.js$script,domain=newyorker.com
```

Add in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click `Apply changes`, go back to the website and press Ctrl + F5 to reload the page.

**Comment by peace2000** [comment]
@stephenhawk8054 Works for me when I tested. EP issue.
