### ISSUE TITLE
japscan.lol: ads

### ISSUE THREAD

**Issue by Ever4engel** [uBlockOrigin/uAssets#17235]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.japscan.lol/lecture-en-ligne/batuque/90/`

### Category

ads

### Description

there ads the the end of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 157319
  cosmetic: 226299
  scriptlet: 55394
  html: 1115
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38715-14596, 2d.7h.23m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2142-1, 57m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23922-9, 2d.3h.23m
    adguard-generic: 68712-6679, 2d.7h.23m
    adguard-annoyance: 65082-5152, 2d.7h.23m
    adguard-social: 19994-944, 2d.7h.23m
    fanboy-thirdparty_social: 68-0, 3d.7h.30m
    fanboy-annoyance: 82021-70278, 1d.17h.6m
    fanboy-cookiemonster: 46133-243, 3d.7h.28m
    fanboy-social: 22245-26, 1d.21h.6m
    ublock-annoyances: 4835-39, 2d.7h.23m
    ara-0: 2776-0, 59m
    adguard-spyware-url: 941-136, 2d.7h.23m
    block-lan: 44-0, 21h
  default: 
    user-filters: 3-0, never
    ublock-filters: 33776-2806, 2d.7h.23m
    ublock-badware: 4736-0, 2d.7h.23m
    ublock-privacy: 341-2, 5d.7h.3m
    ublock-abuse: 78-1, 5d.7h.2m
    ublock-unbreak: 1938-3, 2d.7h.23m
    easylist: 64052-577, 1d.5h.5m
    easyprivacy: 31048-1187, 5d.7h
    FRA-0: 29567-406, 2d.7h.23m
    ublock-quick-fixes: 378-3, 58m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 250 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 512
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4414 ms (selfie)
  maxAssetCacheWait: 3016 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    dm-event.net: 1
    googletagmanager.com: 1
    ko-fi.com: 2
```
</details>

**Comment by mapx-** [comment]
add & test

```
||dailymotion.com/embed/$frame,domain=japscan.*,important
japscan.lol##iframe:upward(1)
```

I blocked the dailymotion frame, does the site provide videos (not video ads) too ?

**Comment by Daxy7** [comment]
Going into block element mode with `japscan.lol##iframe:upward(1)` turns the page into a white screen. Garbled html head

```
<html lang="fr"><head>
<html b1ai5t0br="" sxcwf12n6="" lang="fr"><head>
```

**Comment by mapx-** [comment]
I don't see anymore that video ad

**Comment by Ever4engel** [comment]
seem they removed it.
