### ISSUE TITLE
geenstijl.nl: breakage

### ISSUE THREAD

**Issue by Waxli** [uBlockOrigin/uAssets#17233]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.geenstijl.nl/`

### Category

breakage video

### Description

when pressing play on a video, it does not play. Somewhere in that player seems to be an issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 87080
  cosmetic: 40821
  scriptlet: 17064
  html: 0
listset (total-discarded, last-updated): 
  added: 
    NLD-0: 2563-14, 6h.38m
  default: 
    user-filters: 3-0, never
    easylist: 63930-47, 3d.17h.44m
    easyprivacy: 31047-1175, 5d.10h.2m
    plowe-0: 3757-931, 4d.15h.24m
    ublock-abuse: 78-0, 7d.10h.12m
    ublock-badware: 4708-114, 3d.17h.43m
    ublock-filters: 32029-100, 3d.17h.41m
    ublock-privacy: 290-1, 7d.10h.13m
    ublock-quick-fixes: 387-31, 10h.41m
    ublock-unbreak: 1927-44, 3d.17h.42m
    urlhaus-1: 6874-0, 10h.40m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 50 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 567 ms (selfie)
  maxAssetCacheWait: 181 ms
popupPanel: 
  blocked: 70
  blockedDetails: 
    geenstijl.nl: 2
    2mdn.net: 1
    bluebillywig.com: 25
    browser-update.org: 1
    doubleclick.net: 10
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
    mmcdn.nl: 1
    twitter.com: 3
    youtube.com: 24
```
</details>

**Comment by mapx-** [comment]
Test

`@@||cdn.bluebillywig.com/scripts/prebid/$script,domain=geenstijl.nl`

**Comment by mapx-** [comment]
@BPower0036

**Comment by BPower0036** [comment]
@mapx- It is now fixed in EasyDutch, see https://github.com/EasyDutch-uBO/EasyDutch/commit/758298e0996a10bbd75dd51448e1609283f407c5. Sorry for the delay, I had a weekend.
