### ISSUE TITLE
[nsfw] xhamster20.desi: ads

### ISSUE THREAD

**Issue by adsdestroyer** [uBlockOrigin/uAssets#17237]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://xhamster20.desi/videos/die-rache-der-comtessa-episode-2-xhyUHYN`

### Category

ads

### Description

ads are in player.
inplayer vast ads 5sec nonskip and banner in bottom player.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 86608
  cosmetic: 39093
  scriptlet: 17043
  html: 899
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32849-72, 1d.7h.34m
    ublock-badware: 4733-0, 1d.7h.33m
    ublock-privacy: 338-0, 9d.22h.44m
    ublock-abuse: 78-0, 9d.22h.43m
    ublock-unbreak: 1942-1, 1d.7h.32m
    ublock-quick-fixes: 387-0, 21h.5m
    easylist: 64225-585, 1h.24m
    easyprivacy: 31058-1767, 2d.14h.39m
    urlhaus-1: 6874-0, 21h.4m
    plowe-0: 3757-2, 6d.5h.15m
filterset (user): [empty]
trustedset: 
  added: [array of 82 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1374 ms (selfie)
  maxAssetCacheWait: 340 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    xhamster20.desi: 2
    google.com: 1
    googletagmanager.com: 1
    topvids.org: 3
    tsyndicate.com: 5
    xxxviijmp.com: 1
```
</details>

**Comment by 40OIL** [comment]
I confirm the problem.
`https://ru.xhamster.com/videos/<any video page>`
if you turn on the checkbox "disable cosmetic filtering" - the page starts working

**Comment by 40OIL** [comment]
> @adsdestroyer could you test
> `||doppiocdn.com/hls/*/master/*.m3u8`

added a filter, did not help
as before, a normal page opens first, and then it closes completely with a black background.

**Comment by mapx-** [comment]
> as before, a normal page opens first, and then it closes completely with a black background.

@40OIL you are talking about something else

reset uBO, update all filter lists, disable other extensions / internal adblockers, test again

**Comment by SnowManWithCarrot** [comment]
Please remove this any filters related to - "doppiocdn.com" 

This is the content delivery network of Stripchat.com and now no stream works because of this entry.

Please remove it.

If people have issues with xhamsterlive they should use the source of those streams which is - stripchat.com

**Comment by mapx-** [comment]
@SnowManWithCarrot in this case (xhamster) is doppiocdn the source of those video ads ?

**Comment by SnowManWithCarrot** [comment]
> @SnowManWithCarrot in this case (xhamster) is doppiocdn the source of those video ads ?

No it is not - those ads in xhasterlive are unrelated to doppiocdn (doppiocdn - is the stream source for all streams that stripchat provide to partner sites like xhamster).

desi ads are coming from xhaster ads partners not from the videos stream source - doppiocdn. (that is practically not possible)

**Comment by SnowManWithCarrot** [comment]
Thanks for remove it.

I went in and checked xhamsterlive - there are no ads for me. (both on desktop and mobile/tablet)

The person who reported ads there need to get a good anti-virus program and malware/adware program to scan their pc/laptop.

**Comment by mapx-** [comment]
When I get the preroll crap it's from doppiocdn

![image](https://user-images.githubusercontent.com/10303732/226846198-1b6cd15e-5870-44d9-926e-5c5c65150223.png)

**Comment by SnowManWithCarrot** [comment]
> When I get the preroll crap it's from doppiocdn
> 
> ![image](https://user-images.githubusercontent.com/10303732/226846198-1b6cd15e-5870-44d9-926e-5c5c65150223.png)

What exactly do you mean from "reloaded crap" ?

Because I'm not getting any ads in xhamster (video site) and xhamsterlive (the stream site).

**Comment by mapx-** [comment]
The (preroll)video ads are not always reproducible

**Comment by SnowManWithCarrot** [comment]
If anyone have issues with xhamster cdn here it is - https://sni.star.xhcdn.com.fpbns.net

But doppiocdn.com (stripchat cdn) thave nothing to do with ads only delivers video streaming.

**Comment by ghajini** [comment]
firefox android

**issue** = no access to website, website is blurred due to 18+ consent is blocked

**url** = `https://xhamster20.desi/videos/big-tit-playroom-hana-haruna-i-cup-108-cm-xhCYmSv?pb=`

filter breaking = `xhamster20.*##^script:has-text(popunder)`
clear cookie before test

**Comment by Malgotra** [comment]
@mapx- ads leftover appears again. adding ##.yfd-fd in my filters remove the space.
