### ISSUE TITLE
watchx.top: popups

### ISSUE THREAD

**Issue by iSmokeMid69** [uBlockOrigin/uAssets#17245]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Blank Popup On Play Button + DevTools Detector +Maybe Trackers Too

### URL(s) where the issue occurs.

`watchx.top/v/bnRyg6Ljkab8/`

### uBO version

*

### Browser name and version

*

### Settings

*

**Comment by mapx-** [comment]
test

```
watchx.top##+js(aopr, devtoolsDetector)
||trackerx.stream^$websocket,domain=watchx.top
```

**Comment by jazz1611** [comment]
Hello, we are related to watchx.top and ask you to remove filter for devtoolsDetector and websocket

- devtoolsDetector: help us avoid stealing URLs or sending spam queries via F12 (developer tools)
- websocket: it supports the player for better. You can find out through these 2 projects https://github.com/Novage/wt-tracker and https://github.com/Novage/p2p-media-loader

**Comment by mapx-** [comment]
That filter kills the popup too:

![image](https://user-images.githubusercontent.com/10303732/228365102-9e9d15d8-2dd6-4b86-9761-7cd326f82d6d.png)

If you remove any popup from your site I'll move the `devtoolsDetector` filter to the annoyances list (not enabled by default)

**Comment by jazz1611** [comment]
> The `devtoolsDetector` filter is in a filterlist which is **enabled** by default for all users (the `popup` related filter is also in that list).
> 
> If YOU remove the popups from your site then that `devtoolsDetector` filter will be moved to the "Annoyances" filterlist which is **disabled** by default.

so, basic user access to the page then enable F12 (developer tool) or do they just watch videos on the page? And we've already explained it. we are a service provider so there should be ads in the player

**Comment by jazz1611** [comment]
also this `||trackerx.stream^$websocket,domain=watchx.top` it also has no effect on the user. it's just a tracker to determine if the users are close to each other and send segments of the video to them.
We know you make this add-on to help avoid displaying or loading unwanted source code (like popups) but you should verify it thoroughly before including in your filters. We hope you will take a closer look at our case once more.
