### ISSUE TITLE
motorsport.com: detection

### ISSUE THREAD

**Issue by TheRealAlBanana** [uBlockOrigin/uAssets#17242]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.motorsport.com/f1/news/horner-perezs-concerns-over-verstappen-saudi-gp-pace-normal/10446353/`

### Category

detection

### Description

The site detects an Ad Blocker. This site was fully usable with uBlock up until a few days ago, so this is new behaviour. Now it wants me to subscribe or remove the Ad Blocker:

 Subscribe and access Motorsport.com with your ad-blocker.

From Formula 1 to MotoGP we report straight from the paddock because we love our sport, just like you. In order to keep delivering our expert journalism, our website uses advertising. Still, we want to give you the opportunity to enjoy an ad-free and tracker-free website and to continue using your adblocker.

You have 2 options:

    Become a subscriber.
    Disable your adblocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1533" alt="Screenshot 2023-03-20 at 17 52 04" src="https://user-images.githubusercontent.com/128428443/226473953-0979e295-7cd7-4f81-9169-cbfbba60fb31.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 86342
  cosmetic: 39044
  scriptlet: 17014
  html: 899
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32809-72, 8h.23m
    ublock-badware: 4733-0, 8h.22m
    ublock-privacy: 342-0, 8h.25m
    ublock-abuse: 78-0, 8h.24m
    ublock-unbreak: 1943-1, 8h.21m
    ublock-quick-fixes: 392-0, 8h.4m
    easylist: 64031-581, 4d.4h.18m
    easyprivacy: 31059-1767, 2d.4h.12m
    urlhaus-1: 6749-0, 8h.5m
    plowe-0: 3757-2, 4d.12h.3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 347 ms
  maxAssetCacheWait: 124 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    motorsport.com: 2
    adsafeprotected.com: 1
    cxense.com: 1
    googletagmanager.com: 2
    imasdk.googleapis.com: 1
```
</details>

**Comment by TheRealAlBanana** [comment]
Although this site has been reported before, it has been working up until a few days ago. I have tried updating Firefox, but problem remains.

**Comment by mapx-** [comment]
only FF on my side, update quick fixes list in 5-10 min

**Comment by TheRealAlBanana** [comment]
No sooner than posting that it had been fixed, it is now blocking again.

**Comment by TheRealAlBanana** [comment]
They are tenacious.
