### ISSUE TITLE
independent.co.uk: detection

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17249]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.independent.co.uk/news/world/americas/us-politics/trump-arrested-today-indict-stormy-daniels-manhattan-b2304990.html`

### Category

detection

### Description

![image](https://user-images.githubusercontent.com/91396482/226651268-ff3f09d2-f164-4028-b803-2d72e57506e9.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 78084
  cosmetic: 40876
  scriptlet: 20464
  html: 1067
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    urlhaus-1: null
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1488-0, 20h.53m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 2d.22h.51m
    ublock-annoyances: 4835-4, 2d.22h.51m
  default: 
    ublock-filters: 33864-77, 2d.16h.31m
    ublock-badware: 4747-0, 2d.22h.51m
    ublock-privacy: 342-0, 2d.22h.51m
    ublock-abuse: 78-0, 2d.22h.51m
    ublock-unbreak: 1942-1, 2d.22h.51m
    ublock-quick-fixes: 386-0, 20h.54m
    easylist: 64307-285, 1h.33m
    easyprivacy: 31059-2157, 2d.22h.51m
filterset (user): [array of 607 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 282 ms (selfie)
  maxAssetCacheWait: 313 ms
  unsuspendAfter: 123 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    independent.co.uk: 3
    amazon-adsystem.com: 1
    brandmetrics.com: 1
    chartbeat.com: 1
    cpx.to: 1
    cxense.com: 1
    demdex.net: 3
    dotmetrics.net: 1
    doubleclick.net: 1
    google-analytics.com: 1
    google.com: 3
    googletagmanager.com: 2
    mediavoice.com: 1
    ml314.com: 2
    permutive.app: 1
    pubmatic.com: 1
    taboola.com: 1
    twitter.com: 1
    viafoura.co: 2
    www.googleapis.com: 1
```
</details>

**Comment by Daxy7** [comment]
message is gone

**Comment by Daxy7** [comment]
Nvm. Took 10-20 secs to appear

**Comment by Daxy7** [comment]
Page:  
```
https://www.independent.co.uk/news/world/americas/us-politics/trump-mistrial-town-hall-e-jean-carroll-b2330641.html
```

1st party filter `https://www.independent.co.uk/_build/prebid.8edd46219a982abcc17e.js`
[EasyList is blocking the media player again](https://user-images.githubusercontent.com/91396482/235724078-1e86298e-022b-49f0-8c21-3752061bbcc2.png)

**Comment by Daxy7** [comment]
domain changed and video playback is disabled 

```
https://www.the-independent.com/news/world/americas/us-politics/trump-arrest-mugshot-news-georgia-b2399053.html
```

```
unknown
```

**Comment by Daxy7** [comment]
the media player only activates after removing all filter lists and individual filtering through medium mode. the player won't load when `doubleclick.net` is blocked.

note:  I am using a UK IP.

```
https://www.the-independent.com/news/world/americas/us-politics/trump-trial-dates-mark-meadows-latest-b2401012.html
```

https://github.com/uBlockOrigin/uAssets/assets/91396482/f95fb926-359f-41ee-a0cf-a0d2cd007aec

**Comment by Daxy7** [comment]
video player broken again
```
https://www.the-independent.com/news/world/americas/us-politics/trump-trial-prison-mugshot-latest-news-b2401658.html
```

```
@@||doubleclick.net^$xhr,domain=the-independent.com
```
https://github.com/uBlockOrigin/uAssets/assets/91396482/f3988acd-8549-42ec-96cb-de90ab19cc76

**Comment by mapx-** [comment]
on my side it's ok in chrome but completely broken in FF (even disabling uBO)

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue any more. I think the only filters we need now are:

```adb
@@||the-independent.com/_build/prebid$script,1p
the-independent.com###top-banner-wrapper
```

?
