### ISSUE TITLE
skai.gr: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#17247]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.skai.gr/`

### Category

nuisance

### Description

Push notification enabling prompt. The filter:

`skai.gr###popup-push`

blocks the message momentarily as created by uBO element picker, but it reloads as soon as you refresh or revisit the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-03-21 at 14-36-29 Ειδήσεις Οικονομία Πολιτική για την Ελλάδα και τον Κόσμο ΣΚΑΪ](https://user-images.githubusercontent.com/101707608/226630211-3682a04c-a020-48aa-b208-514060998894.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 268224
  cosmetic: 242467
  scriptlet: 38850
  html: 1053
listset (total-discarded, last-updated): 
  added: 
    https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 50026-2929, 1d.4h.55m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38716-7050, 1d.4h.54m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 37548-585, 1d.4h.48m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1066-0, 6d.5h.18m
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 1d.4h.47m
    https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 75-0, 1h.19m
    https://www.i-dont-care-about-cookies.eu/abp/: 25595-4, 1d.4h.56m
    adguard-generic: 68828-6509, 1d.5h.3m
    adguard-mobile: 8562-128, 1d.5h.2m
    adguard-spyware-url: 949-4, 1d.5h
    block-lan: 44-0, 6d.5h.18m
    curben-phishing: 60110-25, 4h.44m
    curben-pup: 187-0, 4h.44m
    adguard-annoyance: 65117-3427, 1d.4h.59m
    adguard-social: 20018-86, 1d.4h.58m
    fanboy-thirdparty_social: 69-0, 6d.5h.18m
    fanboy-annoyance: 82134-14715, 4h.44m
    ublock-annoyances: 4835-6, 1d.4h.57m
    dpollock-0: 11342-474, 6d.5h.18m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32809-225, 1d.5h.8m
    ublock-badware: 4740-0, 1d.5h.7m
    ublock-privacy: 342-0, 1d.5h.6m
    ublock-abuse: 78-3, 1d.5h.5m
    ublock-unbreak: 1943-1, 1d.5h.4m
    ublock-quick-fixes: 421-0, 4h.44m
    easylist: 64204-22136, 1d.5h.1m
    easyprivacy: 31065-14977, 5h.10m
    urlhaus-1: 6712-0, 4h.44m
    plowe-0: 3757-4, 6d.5h.18m
    GRC-0: 995-2, 1d.4h.49m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3189 ms
  maxAssetCacheWait: 2052 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    doubleclick.net: 1
    exitbee.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    quantcast.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`||skai.gr/modules/custom/wbnotifications/$script,1p`

report at fanboy's annoyances or AdGuard annoyances lists
