### ISSUE TITLE
unilad.com: detection

### ISSUE THREAD

**Issue by sanigerson** [uBlockOrigin/uAssets#17248]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.unilad.com/community/liz-kirkby-survived-killer-bradley-robert-edwards-438606-20230321`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![unilad](https://user-images.githubusercontent.com/94021014/226643789-28418f26-a651-41ed-a263-890de24ce8d6.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 88244
  cosmetic: 48247
  scriptlet: 18649
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-1, never
    TUR-0: 11859-11, 4d.1h.4m
    easylist: 64052-63, 4d.1h.3m
    easyprivacy: 31057-1179, 4d.1h.3m
    plowe-0: 3755-932, 4d.1h.3m
    ublock-abuse: 78-0, 4d.1h.3m
    ublock-badware: 4732-114, 4d.1h.3m
    ublock-filters: 32927-97, 4d.1h.3m
    ublock-privacy: 293-1, 4d.1h.3m
    ublock-quick-fixes: 392-33, 3h.48m
    ublock-unbreak: 1927-41, 4d.1h.3m
    urlhaus-1: 6712-0, 3h.47m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 16 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2538 ms (selfie)
  maxAssetCacheWait: 185 ms
popupPanel: 
  blocked: 64
  blockedDetails: 
    adsafeprotected.com: 4
    amazon-adsystem.com: 1
    ay.delivery: 1
    chartbeat.com: 1
    connatix.com: 4
    dotmetrics.net: 1
    doubleclick.net: 4
    doubleverify.com: 2
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    imrworldwide.com: 1
    instagram.com: 4
    outbrain.com: 1
    pbxai.com: 1
    permutive.com: 1
    quantserve.com: 1
    rubiconproject.com: 1
    scorecardresearch.com: 1
    twitter.com: 32
```
</details>

**Comment by mapx-** [comment]
> ublock-filters: 32927-97, 4d.1h.3m

fixed 20 h ago

**Comment by mapx-** [comment]
Update all your lists and test again.

**Comment by sanigerson** [comment]
I did again (as mentioned while opening issue) and now it works. It wasn't before.
Thanks.
