### ISSUE TITLE
fptplay.vn: detection

### ISSUE THREAD

**Issue by Jiutianxiayu** [uBlockOrigin/uAssets#17253]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fptplay.vn/`

### Category

detection

### Description

this web detection uBO 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.2
Chromium: 111
filterset (summary): 
  network: 86506
  cosmetic: 39101
  scriptlet: 17012
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    VIE-1: null
  default: 
    user-filters: 7-0, never
    easylist: 64204-44, 1d.19h.30m
    easyprivacy: 31062-1174, 1d.8h.10m
    plowe-0: 3757-931, 6d.20h.21m
    ublock-abuse: 78-0, 8d.14h.35m
    ublock-badware: 4748-114, 12h.14m
    ublock-filters: 32000-83, 12h.13m
    ublock-privacy: 291-1, 8d.14h.34m
    ublock-quick-fixes: 378-31, 1d.4h.9m
    ublock-unbreak: 1932-40, 12h.12m
    urlhaus-1: 6749-0, 1d.4h.8m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2511 ms (selfie)
  maxAssetCacheWait: 53 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    fptplay.vn: 1
    d2r1yp2w7bby2u.cloudfront.net: 2
    google-analytics.com: 1
    imasdk.googleapis.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
removed: 
    VIE-1: null
```

You are disabling `VIE: ABPVN` list. Can you re-enable that filter list and test again?
