### ISSUE TITLE
xn--mgba7fjn.cc: detection

### ISSUE THREAD

**Issue by K-BeBO** [uBlockOrigin/uAssets#17251]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://xn--mgba7fjn.cc/series`

### Category

detection

### Description

![wTepK0evNr](https://user-images.githubusercontent.com/78613040/226726954-3eeea9cd-a2a4-49dd-8f65-4ad77181790f.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 86240
  cosmetic: 38907
  scriptlet: 16956
  html: 895
listset (total-discarded, last-updated): 
  default: 
    user-filters: 8-0, never
    ublock-filters: 32852-37, 3d.22h.48m
    ublock-badware: 4726-0, 3d.22h.47m
    ublock-privacy: 342-0, 2d.52m
    ublock-abuse: 78-0, 2d.51m
    ublock-unbreak: 1940-0, 3d.22h.46m
    easylist: 64052-564, 23h.22m
    easyprivacy: 31057-1786, 3d.22h.49m
    urlhaus-1: 6749-0, 23h.21m
    plowe-0: 3755-2, 12d.23h.6m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 361 ms (selfie)
  maxAssetCacheWait: 111 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    xn--mgba7fjn.cc: 1
    googlesyndication.com: 6
    googletagmanager.com: 1
    histats.com: 1
    phaurtuh.net: 2
    thompaur.com: 5
```
</details>

**Comment by mapx-** [comment]
Does this work ? (I'm redirected to `akwam.to`)

`xn--mgba7fjn.cc##+js(aeld, load, 2000)`

**Comment by K-BeBO** [comment]
Thank you! Now it is working without an issue

> Does this work ? (I'm redirected to `akwam.to`)
> 
> `xn--mgba7fjn.cc##+js(aeld, load, 2000)`
> 
> LE: I get `xn--mgba7fjn.cc` using an egyptian ip

Thank you! Now it is working without an issue
