### ISSUE TITLE
bloomberg.com: breakage

### ISSUE THREAD

**Issue by jahnson** [uBlockOrigin/uAssets#17250]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I do not see how to re-open an issue.
Please see issue #8317, and #8568, the problem is identical.

The solution suggested there worked for me, almost daily until now, but as of a week or so ago it does not.
With uBlockOrigin off this video content plays:
`https://www.bloomberg.com/news/videos/2023-03-16/generation-ev-getting-warmer-with-kal-penn-episode-107?srnd=green`

The same sample URL I gave in the #8568 also does not play:
`https://www.bloomberg.com/news/videos/2021-02-12/solar-industry-can-t-escape-ties-to-xinjiang-china-video`

    Browser/version: firefox 111.0
    uBlock Origin version: 1.47.4

Thank you in advance.

### URL(s) where the issue occurs.
```
https://www.bloomberg.com/news/videos/2023-03-16/generation-ev-getting-warmer-with-kal-penn-episode-107?srnd=green

https://www.bloomberg.com/news/videos/2021-02-12/solar-industry-can-t-escape-ties-to-xinjiang-china-video
```

### uBO version

1.47.4

### Browser name and version

fireox 111.0

### Settings

the following solutions taken from the previous 2 identical issues are still in my filters:

```adb
@@||sourcepointcmp.bloomberg.com^$xhr,1p
@@||location.bloomberg.com/query$xhr,1p

@@||sourcepointcmp.bloomberg.com/ccpa.js$script,domain=bloomberg.com
@@||imasdk.googleapis.com/js/sdkloader/ima3.js^$script,domain=bloomberg.com
```

### Notes

restart 
upgraded browser to latest version
turn uBo off and the content plays 
turn uBo on and it does not 
tried noop-ing various things, to no effect

**Comment by jahnson** [comment]
> Works for me. Try clearing cookies and site data for bloomberg

Tried that thanks - no improvement here.

**Comment by jahnson** [comment]
> Works for me. Try clearing cookies and site data for bloomberg

Did you have the filter code I listed above, or without any special handling of bloomberg.com content ?

**Comment by Daxy7** [comment]
Yeah it played for me without modifying anything. I clicked on the video once to play

**Comment by peace2000** [comment]
Does the video play if you click it (black screen) and then wait a while?

**Comment by jahnson** [comment]
I normally have to wait a few seconds and click a couple of times for a video to start on this site.  Unfortunately giving it longer does not help.  
The place where the video should appear remains black.  

I also tried removing the filter code that was previously suggested for this site.  Makes no difference.  

What is interesting is that before [the video?] loads, right-clicking on the place where the content should appear does not result in the normal pop-up menu that I get when a video is playing.  But after a few seconds, the normal pop-up menu does appear, with options to set, for example, the speed.  Except that the speed (and most other menu items) are greyed out.  In other words, it is as if it has detected that a video will play here, but it does not.  

This is the way it was the previous two times that this problem appeared, and the addition of the filter code shown above fixed the problem at that time, until again recently.

**Comment by mapx-** [comment]
@jahnson 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
