### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by neltymind** [uBlockOrigin/uAssets#17256]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.derstandard.at`

### Category

detection

### Description

Websites detects Origin and asks to deactivate it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 88783
  cosmetic: 43523
  scriptlet: 17016
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6690-0, 20h.27m
    easylist: 64293-50, 20h.32m
    easyprivacy: 31065-1181, 20h.31m
    plowe-0: 3757-932, 4d.22h.44m
    ublock-abuse: 78-0, 4d.22h.42m
    ublock-badware: 4736-114, 20h.30m
    ublock-filters: 32000-96, 20h.29m
    ublock-privacy: 292-1, 4d.22h.38m
    ublock-quick-fixes: 386-33, 20h.26m
    ublock-unbreak: 1932-41, 20h.28m
    urlhaus-1: 6712-0, 20h.25m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2255 ms (selfie)
  maxAssetCacheWait: 133 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    derstandard.at: 1
    google.com: 3
```
</details>

**Comment by mapx-** [comment]
- do we need an account to reproduce the issue ?
- home page ? specific page ?

provide a screenshot with the detection message
