### ISSUE TITLE
[nsfw] aii.sh: detection

### ISSUE THREAD

**Issue by bloquing** [uBlockOrigin/uAssets#17274]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aii.sh/H0ENKI`

### Category

detection

### Description

No showing captcha

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 89250
  cosmetic: 45011
  scriptlet: 17716
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64059-44, 2d.4h.51m
    easyprivacy: 31058-1174, 2d.4h.50m
    plowe-0: 3755-931, 6d.6h.52m
    spa-0: 3548-15, 12h.48m
    spa-1: 5131-193, 2d.4h.49m
    ublock-abuse: 78-0, 2d.4h.48m
    ublock-badware: 4732-114, 2d.4h.47m
    ublock-filters: 32934-126, 2d.4h.46m
    ublock-privacy: 293-1, 2d.4h.45m
    ublock-quick-fixes: 429-4, 12h.54m
    ublock-unbreak: 1928-42, 2d.4h.44m
    urlhaus-1: 6854-0, 12h.53m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3378 ms (selfie)
  maxAssetCacheWait: 1200 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    e2ertt.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/227454085-03e3d9ed-0d68-4af9-aea6-018e14537309.png)
