### ISSUE TITLE
cryptowin.io: ads

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#17270]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cryptowin.io/faucet`

### Category

ads

### Description

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 104907
  cosmetic: 60313
  scriptlet: 18667
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39469-12, 4h.14m
    easylist: 64987-66, 1d.8h.49m
    easyprivacy: 31065-1275, 2d.6h.34m
    plowe-0: 3757-930, 6d.16h.12m
    ublock-abuse: 78-1, 2d.6h.33m
    ublock-badware: 4748-102, 2d.6h.34m
    ublock-filters: 32993-109, 2d.6h.33m
    ublock-privacy: 293-1, 2d.6h.33m
    ublock-quick-fixes: 434-6, 12m
    ublock-unbreak: 1937-41, 2d.6h.33m
    urlhaus-1: 6854-0, 13m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4112 ms (selfie)
  maxAssetCacheWait: 1088 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    cryptowin.io: 1
    coinzillatag.com: 3
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
- screenshot with the ads ?
- did you try using the element picker ?

**Comment by lyubomyrhv** [comment]
23 мар. 2023 г. 20:58 пользователь mapx ***@***.***> написал:
screenshot with the ads ?did you try using the element picker ?
