### ISSUE TITLE
atresplayer.com: detection

### ISSUE THREAD

**Issue by ebarti** [uBlockOrigin/uAssets#17272]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.atresplayer.com/lasexta/programas/equipo-de-investigacion/temporada-14/la-reina-de-la-burundanga_641342e8cfe5b0e4cf83dd2c/`

### Category

detection

### Description

I looked at past reports but none of the fixes work. Thank you in advance for all the amazing work you do and the countless hours saved of ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 85473
  cosmetic: 39246
  scriptlet: 17355
  html: 902
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33640-89, never
    ublock-badware: 4615-0, never
    ublock-privacy: 336-0, never
    ublock-abuse: 78-0, never
    ublock-unbreak: 1933-0, never
    ublock-quick-fixes: 339-16, never
    easylist: 63372-169, never
    easyprivacy: 31007-1205, never
    urlhaus-1: 6492-0, never
    plowe-0: 3751-930, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1009 ms
  maxAssetCacheWait: 5 ms
popupPanel: 
  blocked: 31
  blockedDetails: 
    atresplayer.com: 3
    adsrvr.org: 1
    amazon-adsystem.com: 1
    appsflyer.com: 1
    atresmedia.com: 3
    chartbeat.com: 1
    demdex.net: 5
    doubleclick.net: 1
    everesttech.net: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagmanager.com: 2
    googletagservices.com: 1
    hotjar.com: 1
    mathtag.com: 1
    richaudience.com: 1
    scorecardresearch.com: 1
    smartclip.net: 1
    spotxchange.com: 1
    stickyadstv.com: 1
    tiktok.com: 2
```
</details>

**Comment by ebarti** [comment]
The player stays black OR it detects adblock

**Comment by mapx-** [comment]
add & test

```
@@||atresmedia.com^$xhr,domain=atresplayer.com
@@||smetrics.atresplayer.com$xhr,1p
```

probably you'll get video ads, I didn't find a way to remove them

**Comment by ebarti** [comment]
Thank you all I will try it out. I need to start learning some frontend so I know wtf is going on and be able to help out 😅
