### ISSUE TITLE
imgur.com: breakage

### ISSUE THREAD

**Issue by ArliArdevlirn** [uBlockOrigin/uAssets#17271]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://imgur.com/`

### Category

breakage

### Description

The cosmetic filtering break the infinite scrolling imgur rely on.
When cosmetic filtering is on scrolling to the bottom of initialy loaded post will not load more post.

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 104
filterset (summary): 
  network: 106586
  cosmetic: 47985
  scriptlet: 17135
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 20-0, never
    FRA-0: 29602-35, 1d.13h.24m
    easylist: 64293-261, 1d.13h.25m
    easyprivacy: 31068-1493, 1d.13h.26m
    plowe-0: 3756-956, 12d.21h.53m
    ublock-abuse: 78-1, 17h.8m
    ublock-badware: 4748-133, 1d.13h.23m
    ublock-filters: 32027-177, 1d.13h.22m
    ublock-privacy: 293-1, 17h.7m
    ublock-quick-fixes: 430-7, 9h.5m
    ublock-unbreak: 1937-41, 1d.13h.21m
    urlhaus-1: 6788-0, 13h.6m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 34 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 964 ms (selfie)
  maxAssetCacheWait: 500 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    imgur.com: 4
    amazon-adsystem.com: 1
    assemblyexchange.com: 3
    btloader.com: 1
    d3c8j8snkzfr1n.cloudfront.net: 1
    facebook.net: 1
    google-analytics.com: 1
    quantserve.com: 1
    sascdn.com: 2
    scorecardresearch.com: 1
    sentry-cdn.com: 1
    stretchsquirrel.com: 1
    xeno-soswcrde4a-uc.a.run.app: 2
```
</details>

**Comment by ArliArdevlirn** [comment]
ps: It seem to come from the cosmetic filter that remove the div used for the ad(ad are placed among the post).
When those div are removed it result in the latest post beeing higher in the page(because no space is wasted by the ad) than the length needed to scroll before the page load new content and since you can't scroll past the latest loaded post it is not possible to reach the point where the page will load additional post.

**Comment by mapx-** [comment]
Maybe we should keep the empty placeholders otherwise we have that breakage
