### ISSUE TITLE
[nsfw] bunkr.su: ads

### ISSUE THREAD

**Issue by Pureblood4936** [uBlockOrigin/uAssets#17273]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bunkr.su/v/7f8c1e5d_%E3%82%B7%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%9E%E3%83%AA%E3%83%B3mp4-tOhXdEYJ.mp4`

### Category

ads

### Description

ads on the top!

### Screenshot(s)

`https://user-images.githubusercontent.com/122942559/227392797-2f34c743-6c18-4b87-b57c-d15d57b0b0f6.jpeg`

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 89480
  cosmetic: 43971
  scriptlet: 17448
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6701-0, 34m
    easylist: 64466-51, 34m
    easyprivacy: 30788-1183, 34m
    plowe-0: 3753-932, 34m
    ublock-abuse: 78-0, 34m
    ublock-badware: 5186-114, 34m
    ublock-filters: 33023-104, 34m
    ublock-privacy: 294-2, 34m
    ublock-quick-fixes: 434-8, 34m
    ublock-unbreak: 1938-43, 34m
    urlhaus-1: 6854-0, 34m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4312 ms
  maxAssetCacheWait: 503 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    dsnymrk0k4p3v.cloudfront.net: 2
    googletagmanager.com: 1
    privacity.se: 1
    s3.us-east-1.amazonaws.com: 1
    smearedbin.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`bunkr.su##[href^="https://charmingdatings.life/"]`

report at [easylist repository](https://github.com/easylist/easylist/issues)

**Comment by mapx-** [comment]
@ryanbr
