### ISSUE TITLE
jigidi.com padding

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#1727]
### URL(s) where the issue occurs

`https://www.jigidi.com/solve.php?id=IQHW1MS7`

### Describe the issue

Grey space at the right side

### Versions

- Browser/version: Chrome 65.0.3325.162 (64-bit) _[Latest stable]_
- uBlock Origin version: 1.15.2

### Settings

- Default + EasyList DE + Adguard Base Filters

### Notes

This should work, I think:

```
jigidi.com##body:style(padding-right: 0px !important)
```

**Comment by okiehsch** [comment]
I added your filter to `uBO-annoyances`.
