### ISSUE TITLE
hktvmall.com: breakage

### ISSUE THREAD

**Issue by Fanolian** [uBlockOrigin/uAssets#17275]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A hktvmall.com account is required to reproduce the issue.

The payment selection panel in the checkout page is blocked by `||hktvmall.com/_ui/shared/common/js/inappcommunicationmanager.js` from uBlock filters – Privacy, and AdGuard Tracking Protection filter.
The rule was probably added in #14653.

### URL(s) where the issue occurs.

```
https://www.hktvmall.com/hktv/en/checkout/express
https://www.hktvmall.com/hktv/zh/checkout/express
```
Payment selection panel is blocked

An account is required and at least 1 item is put in the cart.

### Screenshot(s)

uBO default settings:
https://user-images.githubusercontent.com/771216/227436038-745478ac-d4cf-44c6-a283-1870309c973b.png

uBO with `www.hktvmall.com https://www.hktvmall.com/_ui/shared/common/js/InappCommunicationManager.js script allow`:
https://user-images.githubusercontent.com/771216/227436081-8907a629-1b5a-45fe-9031-d909da9bd930.png

### Notes

A hktvmall.com account is required.

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 87348
  cosmetic: 39553
  scriptlet: 17440
  html: 922
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33876-39, 20m
    ublock-badware: 5205-0, 20m
    ublock-privacy: 343-0, 20m
    ublock-abuse: 78-0, 20m
    ublock-unbreak: 1949-12, 20m
    ublock-quick-fixes: 433-7, 20m
    easylist: 64493-213, 20m
    easyprivacy: 30769-1788, 20m
    urlhaus-1: 6954-0, 20m
    plowe-0: 3753-352, 20m
filterset (user): [empty]
urlRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2249 ms
  maxAssetCacheWait: 390 ms
```
</details>

**Comment by mapx-** [comment]
@Alex-302
