### ISSUE TITLE
monkeytype.com: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#17284]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://monkeytype.com/`

### Category

ads

### Description

Ad spot at the bottom of results screen after completing typing test

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2023-03-24 at 8 51 14 PM](https://user-images.githubusercontent.com/69532417/227691095-b82705ad-3775-467b-95a4-a50bf2a80a4f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 110
filterset (summary): 
  network: 160409
  cosmetic: 203772
  scriptlet: 37765
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62250-96, 98d.21h.1m
    adguard-generic: 66304-510, 98d.21h.16m
    adguard-mobile: 8353-54, 98d.21h.15m
    adguard-spyware: 33780-3748, 98d.21h.14m
    adguard-spyware-url: 862-1, 98d.21h.13m
    block-lan: 44-0, 75d.19h.27m
    curben-phishing: 23835-1, 98d.21h.6m
    curben-pup: 195-0, 98d.21h.5m
    fanboy-annoyance: 83240-4012, 35d.7h.39m
    fanboy-cookiemonster: 43408-43407, 35d.7h.38m
    ublock-annoyances: 4797-235, 98d.21h.10m
  default: 
    user-filters: 0-0, never
    easylist: 63015-1135, 98d.21h.12m
    easyprivacy: 30995-12354, 98d.21h.11m
    plowe-0: 3753-1059, 21h.55m
    ublock-abuse: 79-0, 35d.7h.41m
    ublock-badware: 4187-269, 98d.21h.9m
    ublock-filters: 31471-3750, 98d.21h.8m
    ublock-privacy: 274-57, 35d.7h.40m
    ublock-quick-fixes: 477-46, 98d.21h.4m
    ublock-unbreak: 1913-107, 98d.21h.7m
    urlhaus-1: 9884-1, 98d.21h.3m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3091 ms
  maxAssetCacheWait: 1872 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    intergient.com: 1
  hasUnprocessedRequest: true
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
monkeytype.com##.ad
```

@ryanbr
