### ISSUE TITLE
bluemediafile.site: detection

### ISSUE THREAD

**Issue by Kuroiteiken** [uBlockOrigin/uAssets#17282]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bluemediafile.site/url-generator.php?url=XWWUCOrsJWk+kpqcqmf3WZ3LDvbHxtRm4Kqk+saR+4Onh7rgujU70aIJP2pdI3jRVPpwl+BffBxj+YicRXkdiGsyc1uKQEsvx0cSgMGlkVk=`

### Category

detection

### Description

When i enter page, it detects and forces me to close ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://user-images.githubusercontent.com/882130/227630261-bd735abc-0307-4e4d-8b6c-5516cba18a3c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 94435
  cosmetic: 106546
  scriptlet: 24006
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 6h.15m
    adguard-annoyance: 65351-94, 1d.9h.31m
    ublock-annoyances: 4889-155, 1d.9h.30m
  default: 
    user-filters: 0-0, never
    TUR-0: 11931-11, 10h.18m
    easylist: 64334-121, 2d.10h.36m
    easyprivacy: 31065-1263, 1d.14h.35m
    plowe-0: 3757-934, 11d.6h.16m
    ublock-abuse: 78-0, 7d.6h.36m
    ublock-badware: 5099-114, 1d.9h.32m
    ublock-filters: 32037-462, 1d.9h.29m
    ublock-privacy: 293-1, 7d.6h.35m
    ublock-quick-fixes: 434-6, 6h.17m
    ublock-unbreak: 1938-42, 10h.19m
    urlhaus-1: 7156-0, 6h.16m
filterset (user): [empty]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4400 ms (selfie)
  maxAssetCacheWait: 366 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    bluemediafile.site: 1
    galeaeevovae.com: 1
    googletagmanager.com: 1
    igg-games.com: 1
    sipperamomum.guru: 1
```
</details>

**Comment by krystian3w** [comment]
Watch out: `https://mega.nz/file/NG5CiajC#B4_hY45rtQHpsWLScU9dtDOS7VDkasUfEATAaYrzoqc`

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Bluscream** [comment]
i have the same issue; using version 7.12
