### ISSUE TITLE
flightsim.to: detection

### ISSUE THREAD

**Issue by Archer374** [uBlockOrigin/uAssets#17287]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello

The Microsoft Flight Simulator addon site "flightsim.to" uses adverts as well as a countdown to limit the amount of downloads you can start in a certain time period.
Until yesterday UBlock disabled (i.e. massively accelerated) the countdown successfully and also blocked any ads. 
Ad-blocking still works, however unfortunately since today March 25th, 2023, flightsim.to detects UBlock and shows a message to disable all adblockers after the countdown. This message also prevents users with UBlock from downloading any content making the site unusable.

Would be great if this could be fixed. 
Thank you very much for your great tool and have a pleasant weekend.
Best regards
Archer
https://user-images.githubusercontent.com/128901668/227714080-23d2b361-f262-47c7-903e-92e65504563f.png

### URL(s) where the issue occurs.

`http://www.flightsim.to`

### Screenshot(s)

https://user-images.githubusercontent.com/128901668/227714156-76fab535-eed9-4122-a7b8-253e145f9fb3.png

### uBO version

1.47.4

### Browser name and version

Firefox 111.0.1

### Settings

- disabled popups
- disabled cosmetic filter
- disabled large media elements

**Comment by stephenhawk8054** [comment]
I can't reproduce.

**Comment by mapx-** [comment]
me neither,

OP page `https://flightsim.to/file/52119/rio-de-janeiro`

**Comment by mapx-** [comment]
@Archer374 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
