### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by Vispilio** [uBlockOrigin/uAssets#17280]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://twitter.com/search?q=%237500AKPyibitirecek&src=trend_click&vertical=trends`

### Category

breakage

### Description

Twitter trends or searches always gives the error: Something went wrong, but don’t fret — it’s not your fault.

The only thing that was enabled additionally was "easy list cookie" from the annoyances sections on top of the default configuration for UBLOCK... 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 88891
  cosmetic: 81391
  scriptlet: 18987
  html: 0
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 46150-200, 6d.1h.16m
  default: 
    user-filters: 18-1, never
    easylist: 64326-45, 2d.23m
    easyprivacy: 31065-1173, 1d.20h.18m
    plowe-0: 3757-931, 8d.2h.38m
    ublock-abuse: 78-0, 4d.6h.34m
    ublock-badware: 5099-114, 2d.22m
    ublock-filters: 32036-96, 1d.16h.17m
    ublock-privacy: 293-1, 4d.6h.33m
    ublock-quick-fixes: 434-6, 21h.13m
    ublock-unbreak: 1937-40, 3d.6h.7m
    urlhaus-1: 6854-0, 21h.11m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4141 ms (selfie)
  maxAssetCacheWait: 152 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    twitter.com: 10
    google-analytics.com: 1
```
</details>

**Comment by mapx-** [comment]
I get no error using your above link.

**Comment by krystian3w** [comment]
I have FP with blocked pop-up about update e-mail: 
![obraz](https://user-images.githubusercontent.com/35370833/227659128-a9b9b560-86cb-4275-9990-1a7927239866.png)


Bad working: 
```adb
##div[data-testid="sheetDialog"] > :not(div[data-testid="IntentLoginSheet_Login_Sheet"]) div[role="button"]:not([data-testid]) + div[role="button"]:not([data-testid]):upward(div[role="group"])
```

Filter may still exist in AG Annoyances @Yuki2718.

**Comment by Yuki2718** [comment]
> Filter may still exist in AG Annoyances 

The rule was commented out 4 months before: https://github.com/AdguardTeam/AdguardFilters/commit/6936f855927c60fe985f2f41e2c7f2ab605de924

**Comment by gorhill** [comment]
> `filterset (user): [array of 18 redacted]`

> The only thing that was enabled additionally was "easy list cookie" from the annoyances sections on top of the default configuration for UBLOCK

That's not the only thing, you have custom filters.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
