### ISSUE TITLE
Looker.com is being blocked, though I can't find it in the filter

### ISSUE THREAD

**Issue by jacobmovingfwd** [uBlockOrigin/uAssets#1728]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://looker.com/`
`https://*.looker.com/`

### Describe the issue

Looker.com is a corporate Data Analytics tool. I haven't found any evidence that they engage in advertising.
The filter that's triggering the block is:
> Static filter ||looker.com^ found in: [Peter Lowe’s Ad and tracking server list](https://pgl.yoyo.org/adservers/)

### Screenshot(s)

![](https://i.imgur.com/AkKd5W2.png)
![](https://i.imgur.com/zSbGhil.png)

### Versions

- Browser/version: Google Chrome Version 65.0.3325.162 (Official Build) (64-bit)
- uBlock Origin version:  uBlock Origin 1.15.2

### Settings

- None.

### Notes

When I got to the `https://pgl.yoyo.org/adservers/` site, I can't find `looker.com` in [the list](https://pgl.yoyo.org/adservers/serverlist.php?showintro=1&mimetype=plaintext) at all.
Searching this repo does not find `looker` or `||looker.com^`.  
It would be here if it existed: https://github.com/uBlockOrigin/uAssets/blob/master/thirdparties/pgl.yoyo.org/as/serverlist#L1717

I checked Chrome Web Store, and made sure my uBlock extension is up-to-date.

**Comment by mapx-** [comment]
just update Peter Lowe’s Ad and tracking server list

**Comment by jacobmovingfwd** [comment]
@mapx- Can you clarify? I don't have Peter's list on my personal system. I've never customized or modified my uBlock Origin setup. How would I update the list?

**Comment by mapx-** [comment]
Peter Lowe’s is part of the setup, go into 3rd-party-filters and force update that list

**Comment by jacobmovingfwd** [comment]
Awesome, thanks!

**Comment by uBlock-user** [comment]
@pgl

**Comment by pgl** [comment]
Yes, it was removed after discussion with someone from Looker.com.
