### ISSUE TITLE
cryptopaid.net: detection

### ISSUE THREAD

**Issue by MandiYang** [uBlockOrigin/uAssets#17285]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cryptopaid.net/side-scrolling-arpg-watcher-chronicles-coming-to-mobile-later-this-month/`

### Category

detection

### Description

Adblock detected and makes the waiting cool down in the green circle longer if using element picker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2023-03-25 08-48-12](https://user-images.githubusercontent.com/64307609/227704681-9b2f4d89-0d59-4669-8563-6d17c2c25d47.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 150154
  cosmetic: 42953
  scriptlet: 18566
  html: 940
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1912-0, now
    curben-phishing: 60722-27, now
    SWE-1: 4322-2, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 33897-56, now
    ublock-badware: 5232-0, now
    ublock-privacy: 342-1, now
    ublock-abuse: 78-0, now
    ublock-unbreak: 1949-1, now
    ublock-quick-fixes: 433-1, now
    easylist: 64659-609, now
    easyprivacy: 30724-1777, now
    urlhaus-1: 7248-0, now
    plowe-0: 3751-3, now
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 662 ms (selfie)
  maxAssetCacheWait: 368 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    doubleclick.net: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
    wpadmngr.com: 1
    youtube.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Is it a redirection from another link? Can you give original link?

**Comment by stephenhawk8054** [comment]
Which steps should I do next?

![image](https://user-images.githubusercontent.com/66517106/227707144-11e578fa-285a-4edf-91a1-d0d69b05bd18.png)
