### ISSUE TITLE
blog.verselemzes.hu: detection

### ISSUE THREAD

**Issue by Hulayki** [uBlockOrigin/uAssets#17291]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.verselemzes.hu/jegyzet/madach-az-ember-tragediaja-elemzes/9/`

### Category

detection

### Description

not working javascript block function, bc the website is really tricky and open the google search page when i activate the function

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 86737
  cosmetic: 39205
  scriptlet: 17039
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 23-3, never
    easylist: 64293-44, 4d.30m
    easyprivacy: 30787-1172, 19h.23m
    plowe-0: 3757-931, 12d.19h.4m
    ublock-abuse: 78-0, 12d.19h.3m
    ublock-badware: 4753-114, 2d.19h.56m
    ublock-filters: 32036-83, 2d.19h.55m
    ublock-privacy: 291-1, 12d.19h.2m
    ublock-quick-fixes: 435-8, 19h.21m
    ublock-unbreak: 1937-39, 2d.19h.54m
    urlhaus-1: 7156-0, 19h.22m
filterset (user): [array of 23 redacted]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 263 ms (selfie)
  maxAssetCacheWait: 137 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
> not working javascript block function, bc the website is really tricky and open the google search page when i activate the function

Try explaining again, provide all the steps to reproduce the issue, upload a screenshot with whatever detection you see
Is it detection (anti adblocking) or you are talking about the page avoiding right click, select, etc ?!

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d9e8ef95ab21d11f3c29ab7c1100f8d405137990

**Comment by Hulayki** [comment]
> blog.verselemzes. hu anti: right click, select, f-keys [d9e8ef9](https://github.com/uBlockOrigin/uAssets/commit/d9e8ef95ab21d11f3c29ab7c1100f8d405137990)

Thank you, but is it possible to use some kind of filter to select the text to copy? I know about the developer mode, just wondering

**Comment by mapx-** [comment]
It's what I fixed.
You have to enable this list: `uBlock filters – Annoyances`

**Comment by Hulayki** [comment]
Oh, sorry. I only added it to my own filters, I didn't know about this feature. Thank you, now it's working.
