### ISSUE TITLE
tweakers.net: detection

### ISSUE THREAD

**Issue by HDrenth** [uBlockOrigin/uAssets#17294]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tweakers.net/reviews/10952/ziggo-verhoogt-prijzen-wegens-inflatie-mogen-we-kosteloos-opzeggen.html`

### Category

detection

### Description

#16782 but still not fixed; yes I have ran the update list etc.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 88244
  cosmetic: 41330
  scriptlet: 17470
  html: 925
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33925-68, 1m
    ublock-badware: 5237-0, 1m
    ublock-privacy: 344-0, 1m
    ublock-abuse: 78-0, 1m
    ublock-unbreak: 1949-1, 1m
    ublock-quick-fixes: 432-1, 1m
    easylist: 64659-601, 1m
    easyprivacy: 30724-1768, 1m
    urlhaus-1: 6937-0, 1m
    plowe-0: 3751-2, 1m
    NLD-0: 2573-20, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1202 ms
  maxAssetCacheWait: 94 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    tweakers.net: 1
    tweakers.nl: 2
    usabilla.com: 1
```
</details>

**Comment by mapx-** [comment]
add & test

```
@@||tweakers.net^$shide
@@||tweakers.nl^$xhr,domain=tweakers.net
```

@BPower0036

**Comment by crisp-tweakers** [comment]
That first suggestion will surely break some legitimate functionality...

**Comment by mapx-** [comment]
continue here:
https://github.com/EasyDutch-uBO/EasyDutch/issues/34
