### ISSUE TITLE
yts.mx: popups

### ISSUE THREAD

**Issue by sr1992tm** [uBlockOrigin/uAssets#17290]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yts.mx/`

### Category

popups

### Description

New tabs open when i click elements

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 87616
  cosmetic: 39171
  scriptlet: 17044
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64659-45, 35m
    easyprivacy: 31065-1174, 3d.10h.20m
    plowe-0: 3757-933, 8d.6h.29m
    ublock-abuse: 78-0, 9d.1h.46m
    ublock-badware: 5228-114, 34m
    ublock-filters: 32012-85, 33m
    ublock-privacy: 292-1, 9d.1h.47m
    ublock-quick-fixes: 434-6, 31m
    ublock-unbreak: 1938-41, 32m
    urlhaus-1: 6937-0, 29m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 195139 ms (selfie)
  maxAssetCacheWait: 348 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    addthis.com: 1
    celeritascdn.com: 1
    cloudflareinsights.com: 1
    empied.com: 1
    userreport.com: 1
    youradexchange.com: 1
```
</details>

**Comment by mapx-** [comment]
update all filter lists, it was fixed 1 h ago
