### ISSUE TITLE
ebay.com: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#17298]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ebay.com/sch/i.html?_from=R40&_nkw=macbook+pro+&_sacat=0&LH_TitleDesc=0&LH_BIN=1&_sop=15&_blrs=recall_filtering&_pgn=2`

### Category

ads

### Description

Scroll to the bottom of the search results and there are sponsored listings. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2023-03-26 at 12 14 50 AM](https://user-images.githubusercontent.com/69532417/227761178-84a93abb-e3ce-422a-8e58-e582c9f910d1.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 110
filterset (summary): 
  network: 202892
  cosmetic: 208560
  scriptlet: 38883
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 65419-91, 1d.3h.7m
    adguard-generic: 69109-514, 1d.3h.22m
    adguard-mobile: 8625-46, 1d.3h.21m
    adguard-spyware-url: 956-2, 1d.3h.19m
    block-lan: 44-0, 1d.3h.6m
    curben-phishing: 60722-0, 1d.3h.12m
    curben-pup: 187-0, 1d.3h.11m
    fanboy-annoyance: 83240-4087, 1d.3h.2m
    fanboy-cookiemonster: 43408-43407, 1d.3h.1m
    ublock-annoyances: 4889-238, 1d.3h.16m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39329-15447, never
  default: 
    user-filters: 0-0, never
    easylist: 64466-780, 1d.3h.18m
    easyprivacy: 30722-1374, 1d.3h.17m
    plowe-0: 3753-1027, 2d.1h.18m
    ublock-abuse: 78-0, 1d.3h.4m
    ublock-badware: 5223-335, 1d.3h.15m
    ublock-filters: 32002-3920, 1d.3h.14m
    ublock-privacy: 293-12, 1d.3h.3m
    ublock-quick-fixes: 434-31, 1d.3h.10m
    ublock-unbreak: 1938-90, 1d.3h.13m
    urlhaus-1: 7248-3, 1d.3h.9m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1867 ms (selfie)
  maxAssetCacheWait: 1248 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    ebay.com: 2
    bluekai.com: 1
    ebayrtm.com: 1
    ebaystatic.com: 3
    perfdrive.com: 1
  hasUnprocessedRequest: true
```
</details>

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uBlock-issues/issues/2297

**Comment by gorhill** [comment]
> `hasUnprocessedRequest: true`

Means the page needs a reload.
