### ISSUE TITLE
[nsfw] pixlev.store: popups

### ISSUE THREAD

**Issue by nobuzero** [uBlockOrigin/uAssets#17296]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://pixlev.store/4xzdyt2`

### Category

popups

### Description

popups ads working

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 90060
  cosmetic: 45152
  scriptlet: 17754
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64659-45, 6m
    easyprivacy: 30724-1175, 6m
    plowe-0: 3751-934, 6m
    spa-0: 3550-11, 7m
    spa-1: 5133-195, 7m
    ublock-abuse: 78-0, 6m
    ublock-badware: 5233-114, 6m
    ublock-filters: 33071-128, 6m
    ublock-privacy: 295-2, 6m
    ublock-quick-fixes: 433-8, 6m
    ublock-unbreak: 1938-44, 6m
    urlhaus-1: 6937-0, 6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 310 ms
  maxAssetCacheWait: 171 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    pixlev.store: 1
    exosrv.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    imgair.net: 1
    realsrv.com: 2
```
</details>

**Comment by Daxy7** [comment]
Lol [hundreds of popups and an epilepsy in private browsing mode](https://user-images.githubusercontent.com/91396482/227742989-ec57804b-ca94-4088-b580-d0867f6168c2.png)
