### ISSUE TITLE
techacode.com: breakage

### ISSUE THREAD

**Issue by blader-render** [uBlockOrigin/uAssets#17299]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://techacode.com/cach-bien-soan-cau-hoi-trac-nghiem-trong-plickers-va-trien-khai-tren-lop/`

### Category

breakage

### Description

hidden button continue if allow adb
original link
1short.info/3Ibwl

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 87359
  cosmetic: 39581
  scriptlet: 17512
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 114-0, never
    easylist: 64659-45, 1d.4h.18m
    easyprivacy: 30724-1175, 1d.4h.18m
    plowe-0: 3751-934, 1d.4h.18m
    ublock-abuse: 78-0, 1d.4h.18m
    ublock-badware: 5228-114, 1d.4h.18m
    ublock-filters: 33049-118, 1d.4h.18m
    ublock-privacy: 295-2, 1d.4h.18m
    ublock-quick-fixes: 417-6, 11m
    ublock-unbreak: 1938-42, 1d.4h.18m
    urlhaus-1: 6817-0, 10m
filterset (user): [array of 40 redacted]
trustedset: 
  added: [array of 13 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3420 ms (selfie)
  maxAssetCacheWait: 1583 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    amazon-adsystem.com: 1
    avplayer.com: 5
    doubleclick.net: 3
    exmarketplace.com: 1
    googlesyndication.com: 3
    pinterest.com: 1
    twitter.com: 1
    vidcrunch.com: 3
```
</details>

**Comment by mapx-** [comment]
I get anti adb message at the bottom even disabling uBO

**Comment by blader-render** [comment]
> 1short.info/3Ibwl

yeah, but i cannot find button for continue

**Comment by blader-render** [comment]
> I get anti adb message at the bottom even disabling uBO (in chrome)

can u reproduce for that?

**Comment by blader-render** [comment]
> I get anti adb message at the bottom even disabling uBO (in chrome)

![image](https://user-images.githubusercontent.com/120096290/227786526-7b80adc2-ac7e-49da-85eb-85e8a416a7c8.png)

like that?

**Comment by mapx-** [comment]
yes. There is no continue button.

**Comment by blader-render** [comment]
> yes. There is no continue button.

so, this not problem with adb? this problem from he site?

**Comment by mapx-** [comment]
If the buttom is missing with uBO disabled, yes, it's a site issue.
