### ISSUE TITLE
cnx-software.com : ads

### ISSUE THREAD

**Issue by chromer030** [uBlockOrigin/uAssets#17295]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cnx-software.com/`

### Category

Ads
### Description

ads :
```
||cdn.cnx-software.com/wp-content/uploads/2023/01/NanoX-EL-COM-Express-Mini-module.png?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2021/06/gateworks-rugged-industrial-iot.webp?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2022/11/Ugoos-TV-Box-2022.webp?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2022/03/geniatech-developer-boards-arm-box-pc.webp?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2021/03/digital-signage-ds3.jpg?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2022/12/Mekotronics-R58X-4G-RK3588-mini-PC.jpg?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2023/02/RAK-WisGate-Connect.png?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2023/03/Smart-Home-Hotel-KA2-TV-box.jpg?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2023/01/Station-M3-Geek-PC.jpg?lossy=1&ssl=1
||cdn.cnx-software.com/wp-content/uploads/2022/11/WELLER-PCB-Manufacturer.gif?lossy=1&ssl=1
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration
```
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 703107
  cosmetic: 170479
  scriptlet: 39920
  html: 0
listset (total-discarded, last-updated): 
    DEU-0: 6701-431, 23h.47m
    IRN-0: 2967-198, 23h.49m
    adguard-annoyance: 65432-2024, 5h.9m
    adguard-generic: 69109-5593, 5h.7m
    adguard-social: 20096-1970, 5h.8m
    adguard-spyware-url: 956-2, 5h.10m
    block-lan: 44-0, 14d.3h.24m
    curben-phishing: 60292-14635, 23h.46m
    curben-pup: 187-5, 23h.48m
    dpollock-0: 11342-9309, 23h.40m
    fanboy-annoyance: 82138-39073, 4d.5h.26m
    fanboy-thirdparty_social: 68-20, 4d.5h.27m
    ublock-annoyances: 4875-287, 5h.11m
  default: 
    user-filters: 0-0, never
    easylist: 64583-39593, 5h.12m
    easyprivacy: 30724-17065, 5h.6m
    plowe-0: 3750-3118, 23h.50m
    ublock-abuse: 78-6, 4d.5h.25m
    ublock-badware: 5201-507, 5h.5m
    ublock-filters: 32012-4254, 5h.4m
    ublock-privacy: 293-85, 4d.5h.25m
    ublock-quick-fixes: 434-32, 23h.45m
    ublock-unbreak: 1938-116, 5h.2m
    urlhaus-1: 7156-608, 23h.44m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
  ignoreGenericCosmeticFilters: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1924 ms (selfie)
  maxAssetCacheWait: 1368 ms

```

**Comment by mapx-** [comment]
```
cnx-software.com##.textwidget:not([class]:has([href*="cnx-software.com"])):not([class]:has([href*="follow.it"])):not([class]:has([href*="news.google.com"]))
cnx-software.com###text-20:has-text(SPONSORS)
cnx-software.com##[href^="https://url2.cnx-software.com/"]
cnx-software.com##[href^="https://www.khadas.com/"]
cnx-software.com##[style]:has-text(Advertisement)
cnx-software.com##[href*="banner"]
cnx-software.com##.gvoodoo
```

@ryanbr

**Comment by mapx-** [comment]
@chromer030 

or you could report the issue directly at easylist repository (if EL maintainer does not "see" this issue)
https://github.com/easylist/easylist/issues

**Comment by chromer030** [comment]
@mapx- 

Reported : https://github.com/easylist/easylist/issues/15307

Thanks.

**Comment by DandelionSprout** [comment]
Doesn't seem like the maintainers noticed either of the 2 reports or the pinging after 4 months.
