### ISSUE TITLE
Cointent adblock detector / wall

### ISSUE THREAD

**Issue by orokusaki** [uBlockOrigin/uAssets#173]
(copied from https://github.com/gorhill/uBlock/issues/2088)
### Describe the issue

Cointent is a frame that shows up to wreck your web experience. It blocks the page and asks you for money in return for moving out of the way.

It also loads 72KB (the size _after_ gzip) of JavaScript, including redundant jQuery, etc.
### One or more specific URLs where the issue occurs

http://www.kiplinger.com/article/investing/T038-C007-S001-are-stocks-cruising-for-a-bruising.html
### Screenshot in which the issue can be seen

https://d17oy1vhnax1f7.cloudfront.net/items/3b3P1G1S1Y1S3O3E0x1m/Screen%20Shot%202016-10-21%20at%209.42.31%20AM.3B3T3m103L2N.png
### Steps for anyone to reproduce the issue
1. Visit the page
### Your settings

Default uBlock settings
- Browser/version: Firefox (48.0.2)
- uBlock Origin version: 1.9.12
##### Your filter lists

Everything default
##### Your custom filters (if any)

Everything default

**Comment by migueldemoura** [comment]
Fixed already. Screenshot url is down as well.
