### ISSUE TITLE
ebike-connect.com: breakage

### ISSUE THREAD

**Issue by A-Boers** [uBlockOrigin/uAssets#17307]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ebike-connect.com/login?state=%2Fdashboard`

### Category

breakage

### Description

In other brouwsers there is a question to accept cookies.
This is not happening with Brave.

![image](https://user-images.githubusercontent.com/75908738/228029469-a74a8f99-2296-4a33-beb6-946b6cade9d6.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 87119
  cosmetic: 39155
  scriptlet: 17038
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    NLD-0: null
  default: 
    user-filters: 0-0, never
    easylist: 64466-45, 3d.22h.58m
    easyprivacy: 30725-1174, 1d.10h.52m
    plowe-0: 3751-931, 1h.25m
    ublock-abuse: 78-0, 1d.10h.53m
    ublock-badware: 5267-114, 1h.20m
    ublock-filters: 32006-84, 1h.22m
    ublock-privacy: 293-2, 2d.2h.50m
    ublock-quick-fixes: 421-6, 1h.19m
    ublock-unbreak: 1939-41, 1h.21m
    urlhaus-1: 6934-0, 1h.18m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1073 ms (selfie)
  maxAssetCacheWait: 94 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
Turn OFF the shields for that page.
