### ISSUE TITLE
ibrahima-ndaw.com: breakage

### ISSUE THREAD

**Issue by FrankConijn** [uBlockOrigin/uAssets#17306]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Sometimes, the widget Disqus is blocked, but that just creates a comments section. Please allow it entirely if you can or explain how the user can make uBO allow it entirely. An example can be found on
`https://www.ibrahima-ndaw.com/blog/parallax-effect-with-10-lines-of-javascript/` 
(I have seen it on more pages) and the 'mother page' is `https://disqus.com/`. 

### URL(s) where the issue occurs.

`https://www.ibrahima-ndaw.com/blog/parallax-effect-with-10-lines-of-javascript/`

### uBO version

1.47.2

### Browser name and version

Edge 111

### Settings

None.

### Notes

None. I don't know how.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by FrankConijn** [comment]
Like I wrote, it happens sometimes, also on other sites with Disqus. I don't know how to reproduce it, but if you look at what is blocked by uBO on the referred-to page, you will see that that includes certain Disqus files.
