### ISSUE TITLE
realclearpolitics.com: breakage

### ISSUE THREAD

**Issue by Anoneemouse** [uBlockOrigin/uAssets#17308]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.realclearpolitics.com/`

### Category

breakage

### Description

I answered your checkbox questions as best I could, but I'm not sure on some, and it wasn't clear how to even check those items.  For example, when I clicked on the "use this button to check for duplicates" - it wasn't clear that it actually checked for duplicates. So I hope it's not. 

Regardless, very recently the RealClearPolitics page started displaying without the links that should be in the header and footers.  Turning off ublock origin and reloading the page, it displays just fine.  The problem only seems to be affecting this page, and not their other pages (e.g., RealClearScience.com, RealClearHealth.com, etc. all display and work normally with ublock turned on).  

I've pasted in a screenshot of how the RealClearPolitics page is displaying - if you compare the header area and footer area to one of their other pages, such as RealClearScience.com, you'll see most of the links in the header and footer areas are missing in RealClearPolitics.  When ublock is turned off, all the links display as they should.  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/16356703/228068208-096c1ac9-ba0d-47e6-8ce6-0a876f067404.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 87136
  cosmetic: 39144
  scriptlet: 17034
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64420-45, 2d.20h.41m
    easyprivacy: 30789-1173, 2d.20h.42m
    plowe-0: 3757-931, 11d.20h.24m
    ublock-abuse: 78-0, 8d.19h.47m
    ublock-badware: 5267-114, 17h.30m
    ublock-filters: 31986-84, 17h.29m
    ublock-privacy: 293-1, 8d.19h.46m
    ublock-quick-fixes: 417-6, 3h.7m
    ublock-unbreak: 1939-41, 9h.27m
    urlhaus-1: 6934-0, 3h.8m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1796 ms (selfie)
  maxAssetCacheWait: 742 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    realclearpolitics.com: 3
    google-analytics.com: 1
    googlesyndication.com: 3
    spot.im: 1
```
</details>

**Comment by mapx-** [comment]
add

```
@@||realclearpolitics.com/esm/assets/js/admiral.js$xhr,1p
@@||realclearpolitics.com/esm/assets/js/analytics/$xhr,1p
```

@ryanbr

**Comment by Anoneemouse** [comment]
Is this something that I need to do on my end? If so can you walk me
through how to do it? Or is this something that you folks will modify in
ublock, and once the system updates it should fix the issue? I apologize
for my ignorance on these sorts of things!

**Comment by mapx-** [comment]
if you want to fix immediately without waiting the list maintainer to add a fix:

- go into dashboard / options
- "my filters" tab
- add the 2 filters above, click "apply changes"
- test again

**Comment by Anoneemouse** [comment]
That worked like a charm! Thank you!
