### ISSUE TITLE
[nsfw] rou.video: breakage

### ISSUE THREAD

**Issue by DiabloPiotr** [uBlockOrigin/uAssets#17304]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rou.video/v/clf8sz18t0579x4ufyzxj5pxo`

### Category

breakage

### Description

videos won't play

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 102
filterset (summary): 
  network: 125526
  cosmetic: 89414
  scriptlet: 18885
  html: 923
listset (total-discarded, last-updated): 
  added: 
    CHN-0: 27999-117, 8m
    JPN-1: 10307-14, 2d.22h.24m
    KOR-1: 4270-61, 7m
    RUS-0: 39504-159, 19h.14m
  default: 
    user-filters: 17-0, never
    ublock-filters: 32841-108, 2d.22h.23m
    ublock-badware: 5210-0, 2d.22h.22m
    ublock-privacy: 342-0, 2d.22h.30m
    ublock-abuse: 78-0, 2d.22h.29m
    ublock-unbreak: 1949-1, 2d.22h.25m
    easylist: 64466-712, 2d.22h.26m
    easyprivacy: 30718-1820, 2d.22h.21m
    urlhaus-1: 6934-0, 2h
    plowe-0: 3750-2, 2d.22h.28m
    POL-0: 7888-26, 2h.1m
    POL-2: 1278-12, 19h.15m
    ublock-quick-fixes: 420-1, 2h.2m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1002 ms (selfie)
  maxAssetCacheWait: 477 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    google-analytics.com: 1
    googletagmanager.com: 1
    gstatic.com: 2
    imasdk.googleapis.com: 1
    kgdvs9ov3l2aasw4nuts.com: 1
    oghqvffmnt.com: 1
    realsrv.com: 2
    rn59.xyz: 1
    rn60.xyz: 1
    rou3.xyz: 4
```
</details>

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/52f126e8384ed311d5e1ccbf1df239e829f78b4b
