### ISSUE TITLE
[nsfw] hitbdsm.com: ads

### ISSUE THREAD

**Issue by mmmarlo** [uBlockOrigin/uAssets#17303]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hitbdsm.com/role-reversal-2/`

### Category

ads

### Description

5 second ad before all the videos of hitbdsm.com

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox Mobile: 109
filterset (summary): 
  network: 88790
  cosmetic: 29242
  scriptlet: 17124
  html: 946
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33114-266, 1d.1h.44m
    ublock-badware: 5189-0, 3d.8h.12m
    ublock-privacy: 343-1, 4d.46m
    ublock-abuse: 78-0, 4d.50m
    ublock-unbreak: 1954-1, 3d.8h.13m
    adguard-mobile: 8625-120, 1d.5h.7m
    easylist: 64570-17452, 1d.22h.50m
    easyprivacy: 30957-1775, 3d.19h.30m
    urlhaus-1: 6889-0, 3h.40m
    plowe-0: 3757-2, 10d.1h.48m
    ublock-quick-fixes: 422-1, 3h.41m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9988 ms (selfie)
  maxAssetCacheWait: 4495 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    banneradsday.com: 2
    deludereflexunderwater.com: 1
    dinarsonistprecisely.com: 4
    googletagmanager.com: 1
    resalag.com: 2
    rxeosevsso.com: 2
```
</details>

**Comment by Daxy7** [comment]
[More ads to filter out](https://user-images.githubusercontent.com/91396482/227996902-08e2db77-9a65-4a1e-8377-02b2d56464a1.png)
`hitbdsm.com##[href^="http://t.acam-2.com/aff_ad"]`
