### ISSUE TITLE
drive2.ru: breakage

### ISSUE THREAD

**Issue by LeninEnisey** [uBlockOrigin/uAssets#17301]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.drive2.ru/l/642836621078566229/?key=AggBR1BDVAjbLoR5qjo-2vNEKBxnkSa16M8lsRoL8IWan7o`

### Category

breakage

### Description

Мобильная версия сайта drive2, вставлено видео с YouTube, после просмотра видео предлагаются другие варианты, но их невозможно выбрать.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20230327-124409-137](https://user-images.githubusercontent.com/64343979/227851581-fe425070-2ace-4ddf-967b-445f50b11bf1.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium Mobile: 101
filterset (summary): 
  network: 105250
  cosmetic: 49303
  scriptlet: 18371
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39490-881, 24m
    adguard-mobile: 8625-53, 2d.13h.27m
    easylist: 64556-16921, 2d.15h.46m
    easyprivacy: 30724-1291, 19h.36m
    plowe-0: 3750-1023, 2d.15h.57m
    ublock-abuse: 78-1, 7d.2h.40m
    ublock-badware: 4723-115, 3d.15h.12m
    ublock-filters: 32205-338, 2d.13h.26m
    ublock-privacy: 293-2, 6d.19h.38m
    ublock-quick-fixes: 423-6, 19h.34m
    ublock-unbreak: 1943-43, 2d.13h.25m
    urlhaus-1: 6971-0, 19h.35m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1927 ms (selfie)
  maxAssetCacheWait: 253 ms
popupPanel: 
  blocked: 41
  blockedDetails: 
    adriver.ru: 1
    doubleclick.net: 2
    google.com: 2
    tns-counter.ru: 1
    yandex.net: 1
    yandex.ru: 2
    youtube.com: 32
```
</details>

**Comment by LeninEnisey** [comment]
Извиняюсь не доглядел отключил ublock origin но проблема там сохраняется.

**Comment by mapx-** [comment]
- use FF mobile
- russian site, ask here:
https://github.com/easylist/ruadlist/issues
