### ISSUE TITLE
Cannot view nsfwyoutube.com with uBlock enabled, piguiqproxy.com

### ISSUE THREAD

**Issue by nero1024** [uBlockOrigin/uAssets#1730]
### URL(s) where the issue occurs

`http://www.nsfwyoutube.com`

### Describe the issue

Website NSFW YouTube fails to render when uBlock is enabled. Site is used for watching age-restricted YouTube videos without having to sign-in and mess up your recommendations list.

### Screenshot(s)

![clipboarder 2018 03 17-002](https://user-images.githubusercontent.com/20376599/37561553-1d77cce8-2a1f-11e8-99e2-0e5524502d3f.png)

### Versions

- Browser/version: Google Chrome Version 64.0.3282.186 (Official Build) (32-bit)
- uBlock Origin version: 1.15.2

### Settings

- see the attached image

### Notes

If I whitelist/allow piguiqproxy.com the site renders as normal however I get bombarded with a bunch of shady looking banner ads. I just want to watch age-restricted YouTube videos incognito without having to mess up my recommendations.

**Comment by okiehsch** [comment]
Update your uBO-filter list, you can then noop `piguiqproxy.com`, or keep the block does not matter either way, the site will render fine and no "shaydy" looking ads will appear.
