### ISSUE TITLE
cashearn.cc: detection

### ISSUE THREAD

**Issue by Sandor-Helper** [uBlockOrigin/uAssets#17316]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

AdBlock detected.

### URL(s) where the issue occurs.

`https://cashearn.cc/LojVyzAF`

### Screenshot(s)

![image_2023_03_28T08_43_21_749Z](https://user-images.githubusercontent.com/31479044/228224605-ac643091-467b-40f5-8644-6ad0a9d7ed90.png)

### uBO version

uBlock Origin 1.47.4

### Browser name and version

FireFox 91.1.0esr x86

### Settings

No changes was made.

**Comment by Sandor-Helper** [comment]
I've updated filters, thank you.
But after pressing "... press to continue" button I'm getting this:
![image_2023_03_28T12_44_27_997Z](https://user-images.githubusercontent.com/31479044/228242937-b86b2bf0-16cc-4d5f-a032-fe3f55563ddb.png)

**Comment by stephenhawk8054** [comment]
Yes, you need to allow the pop-up with your browser settings to go to next step
