### ISSUE TITLE
cbsnews.com: ads

### ISSUE THREAD

**Issue by rogerdogswat** [uBlockOrigin/uAssets#17317]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cbsnews.com/evening-news/full-episodes/`

### Category

ads

### Description

this website's ad is gettng through ublock:
`https://protectfamilysavings.org/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 87054
  cosmetic: 39160
  scriptlet: 17039
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64570-45, 2d.5h.19m
    easyprivacy: 30725-1174, 18m
    plowe-0: 3668-911, 48d.22h.54m
    ublock-abuse: 78-0, 12d.13h.56m
    ublock-badware: 5223-114, 3d.10h.9m
    ublock-filters: 31999-84, 3d.10h.8m
    ublock-privacy: 292-1, 12d.13h.55m
    ublock-quick-fixes: 422-6, 13h.6m
    ublock-unbreak: 1938-41, 3d.10h.7m
    urlhaus-1: 6889-0, 13h.5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2669 ms (selfie)
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 1367
  blockedDetails: 
    cbsnews.com: 1
    2mdn.net: 1
    adsrvr.org: 1
    agkn.com: 1
    amazon-adsystem.com: 1
    cbsaavideo.com: 3
    cbsi.com: 1
    cbsivideo.com: 15
    cedexis.com: 1
    chartbeat.com: 1
    confiant-integrations.net: 1
    demdex.net: 6
    doubleclick.net: 1
    extremereach.io: 1
    getpublica.com: 1
    googlesyndication.com: 1
    gstatic.com: 4
    imasdk.googleapis.com: 2
    innovid.com: 2
    liadm.com: 1
    litix.io: 11
    moatads.com: 1
    mtvnservices.com: 2
    ns1p.net: 4
    omtrdc.net: 1256
    qualtrics.com: 1
    rkdms.com: 1
    rlcdn.com: 1
    scorecardresearch.com: 42
    trackonomics.net: 1
    uninterestedquarter.com: 1
```
</details>

**Comment by rogerdogswat** [comment]
Yes. FYI After reporting this I added the website as a personal filter and it was blocked effectively by ublock


Sent from Yahoo Mail for iPhone


On Tuesday, March 28, 2023, 08:15, stephenhawk8054 ***@***.***> wrote:




   
   -  I forced an update of my filter lists. (Click the "Purge all caches" button while holding the 'Shift' key, then click the "Update now" button.)


Did you do this yet?

**Comment by stephenhawk8054** [comment]
Your configuration said otherwise when you submitted the issue:

```yaml
default: 
    user-filters: 0-0, never
    easylist: 64570-45, 2d.5h.19m
    easyprivacy: 30725-1174, 18m
    plowe-0: 3668-911, 48d.22h.54m
    ublock-abuse: 78-0, 12d.13h.56m
    ublock-badware: 5223-114, 3d.10h.9m
    ublock-filters: 31999-84, 3d.10h.8m
    ublock-privacy: 292-1, 12d.13h.55m
    ublock-quick-fixes: 422-6, 13h.6m
    ublock-unbreak: 1938-41, 3d.10h.7m
    urlhaus-1: 6889-0, 13h.5m
```

**Comment by stephenhawk8054** [comment]
As I cannot reproduce the issue (there's no ads for me), I cannot help more, sorry.
