### ISSUE TITLE
callofwar.com: ads

### ISSUE THREAD

**Issue by ShadowRecon10** [uBlockOrigin/uAssets#17310]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.callofwar.com/game.php?bust=1`

### Category

ads

### Description

There were no ads displayed before, but now there is an ad bar to the right.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![AdScreenshot](https://user-images.githubusercontent.com/7759215/228126665-6a7d28dc-e29d-4eac-88f4-0f87aaebe01d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 87052
  cosmetic: 39167
  scriptlet: 17041
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64667-45, 1d.5h.39m
    easyprivacy: 30724-1175, 1d.17h.42m
    plowe-0: 3752-933, 5d.7h.4m
    ublock-abuse: 78-0, 9d.17h.42m
    ublock-badware: 5076-114, 3d.17h.37m
    ublock-filters: 32000-84, 3d.17h.36m
    ublock-privacy: 293-1, 8d.17h.52m
    ublock-quick-fixes: 417-6, 13h.38m
    ublock-unbreak: 1938-41, 3d.17h.35m
    urlhaus-1: 6889-0, 13h.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 141 ms (selfie)
  maxAssetCacheWait: 57 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    callofwar.com: 4
    bytro.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    helpshift.com: 1
    rubiconproject.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I don't see any ads. This might need a long-time account to reproduce like other game sites in the past
