### ISSUE TITLE
t.co: breakage

### ISSUE THREAD

**Issue by mild787** [uBlockOrigin/uAssets#17318]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://t.co/iZjozik6MR`

### Category

breakage

### Description

ridirect not to the destination site if allow ADB
for original link
`https://earnow.online/spzrO`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 111
filterset (summary): 
  network: 87969
  cosmetic: 39676
  scriptlet: 17466
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65010-45, 6m
    easyprivacy: 30741-1176, 6m
    plowe-0: 3751-934, 6m
    ublock-abuse: 78-0, 6m
    ublock-badware: 5421-114, 6m
    ublock-filters: 33085-93, 5m
    ublock-privacy: 295-2, 5m
    ublock-quick-fixes: 446-12, 5m
    ublock-unbreak: 1941-42, 5m
    urlhaus-1: 6938-0, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7208 ms
  maxAssetCacheWait: 2489 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by Daxy7** [comment]
Where do you go on the page after [step 1/7](https://user-images.githubusercontent.com/91396482/228320454-62b557c3-ef79-4299-88ea-1639bc4a731e.png)? (I landed on `blog.cryptowidgets.net`)

**Comment by mapx-** [comment]
with / without uBO => I get the same destination `https://cryptowidgets.net/`

**Comment by mild787** [comment]
> Ke mana Anda membuka halaman setelah [langkah 1/7](https://user-images.githubusercontent.com/91396482/228320454-62b557c3-ef79-4299-88ea-1639bc4a731e.png) ? (Saya mendarat di `blog.cryptowidgets.net`)

redirect in step first

**Comment by mild787** [comment]
> with / without uBO => I get the same destination `https://cryptowidgets.net/`

no, just wit uBO. if without uBO no redirect
![image](https://user-images.githubusercontent.com/121563747/228329307-0ec96f6e-978c-41b4-904a-e8508db61166.png)

sorry big screenshoot, i cannot edit
