### ISSUE TITLE
4ksg.vip: nuisance

### ISSUE THREAD

**Issue by jac10xu** [uBlockOrigin/uAssets#17311]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.4ksg.vip/forum.php`

### Category

nuisance

### Description

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 102
filterset (summary): 
  network: 126726
  cosmetic: 140246
  scriptlet: 17186
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1067-0, 3d.5h.6m
    https://raw.githubusercontent.com/kbinani/adblock-youtube-ads/master/signed.txt: 16-0, 3d.2h.40m
    https://raw.iqiq.io/uniartisan/adblock_list/master/adblock_plus.txt: 207815-1004, 19h.18m
  default: 
    user-filters: 29-1, never
    CHN-0: 27995-27774, 19h.19m
    easylist: 64659-64653, 2d.16h.52m
    easyprivacy: 30724-1618, 2d.16h.53m
    plowe-0: 3753-952, 4d.5h.9m
    ublock-abuse: 78-3, 10d.5h.8m
    ublock-badware: 5206-310, 3d.17h.17m
    ublock-filters: 31999-1943, 3d.17h.16m
    ublock-privacy: 293-1, 10d.2h.1m
    ublock-quick-fixes: 417-29, 19h.17m
    ublock-unbreak: 1938-86, 3d.17h.15m
    urlhaus-1: 6889-0, 19h.16m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2880 ms (selfie)
  maxAssetCacheWait: 379 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    baidu.com: 3
    dingxiang-inc.com: 1
    qhimg.com: 1
    toutiao.com: 1
```
</details>

**Comment by mapx-** [comment]
**nuisance => means nothing**

report directly at easylist China 
https://github.com/cjx82630/cjxlist/issues

but provide more details (not only .. nuisance)
