### ISSUE TITLE
mp3juices.cc: popups

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#17329]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Popups: 
1. paste a name of a song
2. click Search 
3. click Download
4. wait several seconds
5. click Download again
6. notice that apart from the music file download save dialog, 
another page gets opened in a new tab as well, 
with an shopping ad banner inside and spy parameters in URL

The tab URL is (I've redacted some personal data with "XXX") :
`https://bnr.clickofdata.net/get/Wo8NQsaFduJnTKsTEwpNh2j6?rollerAdsId=GKqSAjitqAJoxLkdcJzPSugBtIA0gAKMgIC5n7CiTA&campaignId=482500&zoneId=852020&feedId=0&clickId=GKqSAjitqAJoxLkdcJzPSugBtIA0gAKMgIC5n7CiTA&cost=0.0003&device=desktop&browser=Firefox&browserVersion=111&os=windows&osVersion=win_7&country=PL&countryName=Poland&isp=XXXXXXX+XXXXXXXXXXX&carrier=XXXXXXX+XXXXXXXXXXX&connectionType=XXXXXXX%2FXXX&userAgent=Mozilla%2F5.0+%28Windows+NT+6.1%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F111.0&format=onclick`
The shopping banner URL is: `https://bnr.clickofdata.net/click/Wo8NQsaFduJnTKsTEwpNh2j6`
after clicking leads to a quiz site: `https://www.justquiz.com/us/how-much-do-you-depend-on-technology`

### URL(s) where the issue occurs.

`https://www.mp3juices.cc`

### Screenshot(s)

[SCREENSHOOT](https://user-images.githubusercontent.com/72945564/228472779-acddf17c-e2be-49a3-bfc0-95493920f900.png)

### uBO version

1.48.1b7

### Browser name and version

Firefox 111 & Opera 95

### Settings

- def + annoy

**Comment by garry-ut99** [comment]
I've just realised here too: `mp3juices.link`, `mp3juices.icu`, `mp3juices.tech`

**Comment by garry-ut99** [comment]
Also can speed up 5s timer on `mp3juices.icu##+js(nano-sib, , 1000)`

**Comment by ghost** [comment]
On `mp3juice.co` if you press a download button, it wants to open a popup that gets closed. Second time when the download button is pressed, the popups no longer appear.

Recording:
https://streamable.com/5dab6e


<details>

```yaml
uBlock Origin: 1.66.4
Firefox: 143
filterset (summary):
 network: 163120
 cosmetic: 110923
 scriptlet: 34123
 html: 2462
listset (total-discarded, last-updated):
 added:
  ublock-experimental: 10-0, 1h.4m
  adguard-cookies: 35263-74, 1h.4m
  ublock-cookies-adguard: 5088-75, 1h.4m
  fanboy-cookiemonster: 57671-15230, 1h.4m
  ublock-cookies-easylist: 5088-5088, 1h.4m
 default:
  user-filters: 64-1, never
  ublock-filters: 41446-73, 59m Δ
  ublock-badware: 11059-31, 59m Δ
  ublock-privacy: 3500-3, 1h.4m
  ublock-unbreak: 2755-1, 59m Δ
  ublock-quick-fixes: 360-12, 59m Δ
  easylist: 79437-201, 59m Δ
  easyprivacy: 54591-61, 59m Δ
  urlhaus-1: 31220-5, 1h.4m
  plowe-0: 3440-920, 1h.4m
  ROU-1: 1581-38, 1h.4m
filterset (user): [array of 59 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 237 ms (selfie)
 maxAssetCacheWait: 113 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  eechicha.com: 1
  rv400.com: 1
```

</details>
