### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by gdienter** [uBlockOrigin/uAssets#17326]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/playlist/4dIWvg0YpeEkde7ykusn7d`

### Category

ads

### Description

spotify ads started appearing again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 87313
  cosmetic: 39179
  scriptlet: 17033
  html: 909
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32843-42, 1d.15h.45m
    ublock-badware: 5271-0, 1d.15h.44m
    ublock-privacy: 344-0, 1d.15h.43m
    ublock-abuse: 78-0, 1d.15h.42m
    ublock-unbreak: 1950-1, 1d.15h.41m
    ublock-quick-fixes: 446-3, 12h.6m
    easylist: 64667-592, 1d.15h.39m
    easyprivacy: 30725-1767, 1d.15h.38m
    urlhaus-1: 6938-0, 12h.5m
    plowe-0: 3751-2, 1d.15h.35m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2136 ms (selfie)
  maxAssetCacheWait: 1918 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    googleoptimize.com: 2
    googletagmanager.com: 1
    scdn.co: 1
    sentry.io: 10
    spotifycdn.com: 2
```
</details>

**Comment by Daxy7** [comment]
Image[s] show up and site alters content/title but no audio is played
<details><summary>Video</summary>
<p>

https://user-images.githubusercontent.com/91396482/228601038-aeea1504-236a-4371-adbc-08f2d581b1eb.mp4

</p>
</details>
