### ISSUE TITLE
finya.de: breakage

### ISSUE THREAD

**Issue by Evil2000** [uBlockOrigin/uAssets#17334]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.finya.de/MyFinya/`

### Category

breakage

### Description

The website displays normal before login. After login is only displays a gray page. When disabling uBlock origin the site displays as normal. It seems the site provider detects uBlock and then blocks displaying any content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 102
filterset (summary): 
  network: 89366
  cosmetic: 43605
  scriptlet: 17043
  html: 909
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 2h.25m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 12-1, never
    ublock-filters: 32864-55, 3d.22h.5m
    ublock-badware: 5232-0, 3d.22h.4m
    ublock-privacy: 342-0, 3d.22h.35m
    ublock-abuse: 78-0, 3d.22h.36m
    ublock-unbreak: 1949-1, 3d.22h.6m
    easylist: 64420-592, 3d.22h.7m
    easyprivacy: 30724-1776, 2d.10h.39m
    plowe-0: 3751-2, 2d.10h.40m
    DEU-0: 6704-2, 2h.23m
    urlhaus-1: 7006-0, 2h.21m
    ublock-quick-fixes: 451-1, 2h.22m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 22 redacted]
  removed: 
    about-scheme
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2440 ms (selfie)
  maxAssetCacheWait: 1515 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    amazon-adsystem.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
We cannot investigate the issue without an account (then sms to your phone etc etc)

1. Update all your lists 
(Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

2. 
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests
