### ISSUE TITLE
g1.globo.com: breakage

### ISSUE THREAD

**Issue by hiuahiuahiua** [uBlockOrigin/uAssets#17332]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://g1.globo.com/`

### Category

breakage

### Description

Videos don't work

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 89108
  cosmetic: 42917
  scriptlet: 17750
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 11-1, never
    easylist: 64667-45, 2d.10m
    easyprivacy: 30741-1175, 19h.17m
    plowe-0: 3751-934, 2d.11m
    spa-1: 5138-69, 19h.16m
    ublock-abuse: 78-0, 7d.18h.59m
    ublock-badware: 5421-114, 19h.15m
    ublock-filters: 33068-122, 19h.14m
    ublock-privacy: 293-1, 7d.18h.58m
    ublock-quick-fixes: 423-6, 23h.59m
    ublock-unbreak: 1939-43, 19h.13m
    urlhaus-1: 6933-0, 1d
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 78 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 228 ms (selfie)
  maxAssetCacheWait: 80 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    globo.com: 4
    aswpsdkus.com: 1
    doubleclick.net: 1
    glbimg.com: 4
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
    rubiconproject.com: 1
    scorecardresearch.com: 2
```
</details>

**Comment by mapx-** [comment]
- provide such video
- I tested a random one and no issue on my end:

`https://g1.globo.com/playlist/videos-personalidades-que-morreram-em-2023.ghtml`

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by mapx-** [comment]
@hiuahiuahiua if you update all the filter lists now, are you still able to reproduce the issue ?

**Comment by vitorflaibam** [comment]
i can comment on his behalf, the videos aren't working yet!

**Comment by vitorflaibam** [comment]
I fixed the issue by deactivating "easyprivacy". found the solution here https://github.com/uBlockOrigin/uAssets/issues/14379

**Comment by hiuahiuahiua** [comment]
> I fixed the issue by deactivating "easyprivacy". found the solution here #14379

Thanks! Now it's work fine

**Comment by mapx-** [comment]
Re-enable easyprivacy, update all the other lists (it was fixed in unbreak list)
