### ISSUE TITLE
zona-leros.com: detection

### ISSUE THREAD

**Issue by Mordius** [uBlockOrigin/uAssets#17335]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zona-leros.com/juegos-pc/resident-evil-4-pc-e`

### Category

detection

### Description

Zona-leros blocks download links when loading the site with ublock enabled, forcing me to disable the extesion in the site to access download links 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
 

![image](https://user-images.githubusercontent.com/48067152/228637867-62415a2f-5c22-490c-a8d1-b5e1c4b9e109.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Chromium: 111
filterset (summary): 
  network: 92073
  cosmetic: 40076
  scriptlet: 34389
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt: 177-0, 2d.19h.18m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 23980-11, 2d.19h.19m
  default: 
    user-filters: 0-0, never
    easylist: 64833-50, 1d.19h.10m
    easyprivacy: 30908-1178, 3d.21h.12m
    plowe-0: 3751-875, 4d.14h.48m
    ublock-abuse: 78-3, 4d.18h.17m
    ublock-badware: 5411-114, 1d.19h.9m
    ublock-filters: 33050-2691, 1d.19h.8m
    ublock-privacy: 293-1, 4d.18h.16m
    ublock-quick-fixes: 387-163, 14h.41m
    ublock-unbreak: 1939-44, 1d.19h.7m
    urlhaus-1: 7035-0, 14h.40m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 385 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 1
    imgur.com: 2
    powerad.ai: 1
```
</details>

**Comment by mapx-** [comment]
@Mordius remove the ffa lists
