### ISSUE TITLE
workhouses.org.uk: ads

### ISSUE THREAD

**Issue by Banaanae** [uBlockOrigin/uAssets#17338]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://workhouses.org.uk/`

### Category

ads

### Description

Ads on top and right side of page
Edit: Also on left side under the links column

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/83927639/228693421-e5a1c722-c96b-4ce4-82e7-1a72ad30f51c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 87418
  cosmetic: 39198
  scriptlet: 17033
  html: 909
listset (total-discarded, last-updated): 
  default: 
    user-filters: 14-0, never
    ublock-filters: 32843-42, 2d.14h.12m
    ublock-badware: 5271-0, 2d.14h.11m
    ublock-privacy: 342-0, 7d.10m
    ublock-abuse: 78-0, 7d.10m
    ublock-unbreak: 1950-1, 2d.18h.17m
    ublock-quick-fixes: 451-0, 3h.19m
    easylist: 64672-591, 2d.18h.16m
    easyprivacy: 30725-1767, 2d.18h.15m
    urlhaus-1: 7035-0, 12h.53m
    plowe-0: 3752-2, 7d.9m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1205 ms (selfie)
  maxAssetCacheWait: 157 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    amazon-adsystem.com: 3
    awin1.com: 4
    google-analytics.com: 1
    googlesyndication.com: 8
    googletagmanager.com: 2
    impactradius-go.com: 4
    prf.hn: 8
    pxf.io: 4
    tqlkg.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
workhouses.org.uk###inner-top-ad
workhouses.org.uk###sidebar
```

@ryanbr
