### ISSUE TITLE
bap.navigator.web.de: breakage

### ISSUE THREAD

**Issue by Korados** [uBlockOrigin/uAssets#17340]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bap.navigator.web.de/`

### Category

breakage

### Description

Web.de renewed the UI of their e-mail provider and now uBlock is blocking it. I can't access my mails because the new UI doesn't show up and I only get an error message that says: "A technical error has occurred". The tabs for mail, contacts and calender are broken. The mail tab still shows the number of new e-mails I have but when I click on one of the folders, nothing happens. 

Notice on the screenshot how I am supposed to have 5 new mails but the tab shows that folder is empty.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<!![Web de error](https://user-images.githubusercontent.com/13949999/228738731-7515dfe4-cb13-49af-afcf-0fd95f79cc20.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 107637
  cosmetic: 65106
  scriptlet: 18733
  html: 940
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39523-155, now
  default: 
    user-filters: 3-0, never
    ublock-filters: 33993-62, now
    ublock-badware: 5489-0, now
    ublock-privacy: 348-0, now
    ublock-abuse: 78-0, now
    ublock-unbreak: 1956-1, now
    easylist: 65185-625, now
    easyprivacy: 30754-1776, now
    urlhaus-1: 6995-0, now
    plowe-0: 3751-2, now
    DEU-0: 6704-2, now
    ublock-quick-fixes: 451-3, now
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 217 ms (selfie)
  maxAssetCacheWait: 94 ms
popupPanel: 
  blocked: 60
  blockedDetails: 
    web.de: 13
    360yield.com: 1
    3lift.com: 1
    adform.net: 1
    adition.com: 2
    adnxs.com: 2
    amazon-adsystem.com: 2
    casalemedia.com: 1
    criteo.com: 2
    criteo.net: 3
    g-ha-1und1.de: 13
    indexww.com: 2
    ioam.de: 1
    openx.net: 1
    otto.de: 1
    pbstck.com: 2
    pubmatic.com: 1
    rubiconproject.com: 1
    smartadserver.com: 1
    ui-portal.de: 4
    uicdn.com: 2
    uimserv.net: 2
    yieldlab.net: 1
```
</details>

**Comment by Procyon-b** [comment]
I don't have a problem. Is the issue only on "Ungelesen" or also with other folders?
I assume that it works with ublock disabled?

But I'll try tomorrow on another computer.

**Comment by mapx-** [comment]
@Korados 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by g13ba** [comment]
I had the same issue and found out that it was caused by this filter rule contained in RU Adlist:
||de/|$xhr,3p

I solved it by adding this to My filters:
!fix for https://navigator.web.de/mail breaks because of RU Adlist containing this filter rule: ||de/|$xhr,3p
@@||*.g-ha-1und1.de^$xmlhttprequest,domain=webmailer.web.de

**Comment by Korados** [comment]
What a blast from the past! That worked! Thank you so much for your help!

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Sorry, can you check this?

**Comment by dimisa-RUAdList** [comment]
This rule was added to block adservers like: `reth45dq.de`, `f27tltnd.de`, `9tp9jd4p.de` and so on:
https://github.com/easylist/ruadlist/commit/c83817237c9b207d5c99d32ee637d23bc4fccbd9
https://github.com/easylist/ruadlist/commit/0d2c9f5908770f306000864e74fbe5eb6a24bc85
https://github.com/easylist/ruadlist/commit/55bfa31d745c0721d613de91c89ce6cecdb928bb

I don't see these ad servers being used on the RuNet anymore, so I've removed this rule: https://github.com/easylist/ruadlist/commit/ec9592b9291c86a84f6a13c846eff7cac91d1273
