### ISSUE TITLE
[nsfw] milfnut.com: detection

### ISSUE THREAD

**Issue by Makverus** [uBlockOrigin/uAssets#17347]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://milfnut.com/penny-barber-bonding-with-mommy/`

### Category

detection

### Description

A "Adblock detected" pops up. Previously I was able to block it with blocking popups, but that doesn't work anymore. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![image](https://user-images.githubusercontent.com/28706786/228825064-46eb8f1a-2ea0-4442-956a-a5b054a9950a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 104895
  cosmetic: 60537
  scriptlet: 18719
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    RUS-0: 39503-12, 4h
    easylist: 64667-60, 1d.20h.10m
    easyprivacy: 30725-1282, 3d.23h.53m
    plowe-0: 3751-939, 1d.8m
    ublock-abuse: 78-1, 4d.23h.47m
    ublock-badware: 5438-114, 1d.4h.14m
    ublock-filters: 33080-122, 1d.4h.13m
    ublock-privacy: 293-2, 4d.23h.46m
    ublock-quick-fixes: 448-9, 3h.59m
    ublock-unbreak: 1940-42, 1d.4h.12m
    urlhaus-1: 6995-0, 3h.58m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 6 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 486 ms (selfie)
  maxAssetCacheWait: 71 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    appcdn01.xyz: 2
    appcdn03.xyz: 2
    favorable-sample.com: 1
    googletagmanager.com: 3
    iifvcfwiqi.com: 1
    mxmkhyrmup.com: 1
    realsrv.com: 1
    wpadmngr.com: 1
    yandex.ru: 2
```
</details>

**Comment by okiehsch** [comment]
It's caused by the regional russian list.
````
||xyz^$script,3p,from=~anidub.com|~anidub.vip|~anidubonline.com|~animedia.pro|~animeheaven.ru|~animevibe.wtf|~app.element.io|~assistir-filme.biz|~auth.magic.link|~avtomaty-i-bonusy.com|~baza.bz|~bdnewszh.com|~capshd.xyz|~cdnmovies.be|~cdnmovies.cc|~cdnmovies.nl|~coomeet.com|~crackstreams.com|~crackstreams.ga|~csgoreports.com|~cubeshot.io|~emblix.cc|~espnfree.xyz|~estream.to|~europixhd.io|~films.hds-stream.com|~flowcdn.nl|~fyshare.info|~getvi.tv|~github.io|~gsmware.com|~hanime.tv|~hentaiz.org|~herokuapp.com|~infoua.biz|~jokehd.com|~jokerswidget.com|~jokerswidget.org|~kinoguru.be|~kinoguru.me|~live-nhl.stream|~live94today.com|~lookbase.xyz|~lyra.finance|~mail.google.com|~mangahere.fit|~map-a-date.cc|~mas-stream2021.xyz|~matchat.online|~mikeamigorein.xyz|~miranimbus.ru|~my.mail.ru|~nccg.ru|~newdmn.icu|~odysee.com|~onmovies.se|~playjoke.xyz|~playm4u.xyz|~playmuvi.com|~realtime-chart.info|~roadhub.ru|~roblox.com|~rou.video|~sekai-kabuka.com|~sextop.net|~soccer365.ru|~soonwalk.net|~sportsbay.org|~streetbee.io|~streetbee.ru|~telerium.club|~telerium.live|~uacycling.info|~uploadedpremiumlink.net|~vercel.app|~vk-apps.com|~vk.com|~vmeste.tv|~web.app|~webflow.io
````
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/c65e9ef3ef4e02e6e93fe181f98d4b1958a8282e

**Comment by Bug-Cache** [comment]
https://github.com/user-attachments/assets/addbfa7b-ecff-49e0-9174-cfa8b932ddeb

`https://milfnut.com/`

**Comment by Bug-Cache** [comment]
https://milfnut.com/korina-kova-robo-mom-family-services-modifications/

<details>

<img width="873" height="530" alt="Image" src="https://github.com/user-attachments/assets/16ae011f-c486-4d31-813a-2e1fa02adb52" />

</details>

**Comment by stephenhawk8054** [comment]
Wait until next uBOL update.
