### ISSUE TITLE
terafly.me: detection

### ISSUE THREAD

**Issue by king-iskan** [uBlockOrigin/uAssets#17344]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://terafly.me/`

### Category

detection

### Description

Need help again 😄🙏 Detection adb for that link.
Original link
`https://crypteen.xyz/QrK3jyPi`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox Mobile: 113
filterset (summary): 
  network: 89511
  cosmetic: 29765
  scriptlet: 17590
  html: 995
listset (total-discarded, last-updated): 
  default: 
    user-filters: 150-0, never
    ublock-filters: 34192-304, 1d.11h.44m
    ublock-badware: 5436-0, 1d.11h.44m
    ublock-privacy: 343-1, 1d.11h.44m
    ublock-abuse: 78-0, 1d.11h.44m
    ublock-unbreak: 1957-1, 1d.11h.44m
    ublock-quick-fixes: 422-1, 11h.34m
    adguard-mobile: 8631-120, 1d.11h.44m
    easylist: 65003-17466, 1d.11h.44m
    easyprivacy: 30741-1776, 1d.11h.44m
    urlhaus-1: 7006-0, 11h.33m
    plowe-0: 3751-2, 1d.11h.44m
filterset (user): [array of 40 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 844 ms (selfie)
  maxAssetCacheWait: 323 ms
popupPanel: 
  blocked: 26
  blockedDetails: 
    clickiocdn.com: 1
    d3u598arehftfk.cloudfront.net: 1
    doubleclick.net: 1
    themoneytizer.com: 22
    unblockia.com: 1
```
</details>

**Comment by mapx-** [comment]
```
*$script,domain=terafly.me,redirect-rule=noopjs
terafly.me##+js(aopr, adsBlocked)
||terafly.me^$csp=style-src *
terafly.me##.qc-cmp2-container
```

again with these crap pages, what on earth are you downloading from ?

**Comment by king-iskan** [comment]
> 

What, I'm not understand. What your mean crap pages? I get thelink from site autofaucet.org

**Comment by mapx-** [comment]
indeed: autocrap is using lots of crap shorteners.
Did you test those filters ?

**Comment by stephenhawk8054** [comment]
I think we need to put these faucet/crypto farms as won't support like porn farms.

**Comment by mapx-** [comment]
yes, indeed, or keep opened a discussion only for these stuff

**Comment by stephenhawk8054** [comment]
Yeah, a general discussion for this is good, anyone who wants to help can put filters to specific links that get anti-adb.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/17361
