### ISSUE TITLE
nsw2u.com: detection

### ISSUE THREAD

**Issue by fernandessilvaredux** [uBlockOrigin/uAssets#17349]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nsw2u.com/`

### Category

detection

### Description

The site identifies the uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 89031
  cosmetic: 42612
  scriptlet: 17329
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65003-45, 14h.26m
    easyprivacy: 30735-1175, 2d.11h.11m
    plowe-0: 3751-934, 3d.20h.9m
    spa-1: 5134-69, 3d.45m
    ublock-abuse: 78-0, 3d.20h.12m
    ublock-badware: 5267-114, 3d.44m
    ublock-filters: 32001-116, 3d.43m
    ublock-privacy: 295-2, 3d.20h.11m
    ublock-quick-fixes: 451-8, 45m
    ublock-unbreak: 1939-42, 3d.42m
    urlhaus-1: 6995-0, 44m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 377 ms (selfie)
  maxAssetCacheWait: 118 ms
popupPanel: 
  blocked: 11
  no-scripting: true
  blockedDetails: 
    nsw2u.com: 5
    a-ads.com: 1
    amazon-adsystem.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    media.net: 1
    quantserve.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It was fixed few hours ago. Force update your filter lists and test again.
