### ISSUE TITLE
olhardigital.com.br: ads

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#17342]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://olhardigital.com.br/2023/03/29/internet-e-redes-sociais/stf-pode-mudar-a-forma-como-usamos-internet-no-brasil-entenda/`

### Category

ads

### Description

Empty space impacting layout 

In "Ad choices" "sponsored"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/129367686/228756527-88d9bdf0-4144-446a-9834-2aa4196e436b.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 91976
  cosmetic: 86306
  scriptlet: 19738
  html: 935
listset (total-discarded, last-updated): 
  added: 
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 1d.10h.45m
    fanboy-cookiemonster: 46357-214, 4d.3h.3m
  default: 
    user-filters: 61-7, never
    ublock-filters: 33993-116, 11m
    ublock-badware: 5489-0, 10m
    ublock-privacy: 344-0, 2d.4h.9m
    ublock-abuse: 78-0, 2d.4h.8m
    ublock-unbreak: 1950-1, 3d.6h.9m
    ublock-quick-fixes: 416-1, 6h.35m
    easylist: 64667-654, 1d.2h.50m
    easyprivacy: 30725-1785, 2d.5h.54m
    urlhaus-1: 7006-0, 6h.34m
    plowe-0: 3753-3, 6d.6h.18m
    spa-1: 5142-12, 12m
filterset (user): [array of 61 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 464 ms (selfie)
  maxAssetCacheWait: 157 ms
popupPanel: 
  blocked: 54
  blockedDetails: 
    olhardigital.com.br: 1
    adnxs.com: 1
    advertising.com: 1
    dailymotion.com: 6
    denakop.com: 1
    dm-event.net: 5
    doubleclick.net: 3
    dwin2.com: 2
    geoedge.be: 1
    google.com: 1
    googletagmanager.com: 1
    imasdk.googleapis.com: 2
    jsuol.com.br: 1
    mgid.com: 1
    newsroom.bi: 2
    onesignal.com: 1
    pubmatic.com: 1
    rlcdn.com: 1
    scorecardresearch.com: 1
    spot.im: 6
    spotxchange.com: 2
    youtube.com: 13
```
</details>

**Comment by mapx-** [comment]
I get the "popular" section only disabling uBO on page.

Only this leftover obn my side

`olhardigital.com.br##div.dstrip-padding.diagonal-strip`

@Yuki2718 for the AG spanish /port list ?

**Comment by mapx-** [comment]
@MasterKia you didn't enable 
`spa, por: AdGuard Spanish/Portuguese`

**Comment by mapx-** [comment]
I get that section only disabling the cosmetics and I see no such filter in the logger

Should be something like this:
`###widgetOpenWeb`

**Comment by mapx-** [comment]
ok, adding ghide I'm able to get that section, needing filter

`olhardigital.com.br##[data-mini-ad-unit]`
