### ISSUE TITLE
[nsfw] rg.ru: detection

### ISSUE THREAD

**Issue by Oleg-Kharchenko** [uBlockOrigin/uAssets#17353]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rg.ru/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 94003
  cosmetic: 65738
  scriptlet: 17573
  html: 940
listset (total-discarded, last-updated): 
  removed: 
    RUS-0: null
  default: 
    user-filters: 33208-384, never
    ublock-filters: 33923-39, 2d.3h.33m
    ublock-badware: 5271-0, 2d.19h.49m
    ublock-privacy: 342-0, 4d.21h.42m
    ublock-abuse: 78-0, 4d.21h.41m
    ublock-unbreak: 1950-1, 2d.19h.48m
    ublock-quick-fixes: 416-6, 1d.1h.20m
    easylist: 64659-224, 3d.16h.8m
    easyprivacy: 30724-1207, 3d.16h.9m
    urlhaus-1: 6901-0, 15d.4h.26m
    plowe-0: 3757-935, 15d.4h.30m
filterset (user): [array of 28375 redacted]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 9524 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 746 ms (selfie)
  maxAssetCacheWait: 252 ms
popupPanel: 
  blocked: 59
  no-cosmetic-filtering: true
  no-remote-fonts: true
  blockedDetails: 
    rg.ru: 31
    adfox.ru: 2
    adriver.ru: 2
    betweendigital.com: 1
    google-analytics.com: 1
    hybrid.ai: 1
    mail.ru: 3
    tns-counter.ru: 1
    yadro.ru: 2
    yandex.ru: 15
```
</details>

**Comment by mapx-** [comment]
No detection on my end.
However, reenable RUAdList
then add also this special russian list:

https://easylist-downloads.adblockplus.org/cntblock.txt

go into dashboard
filters list tab
at the bottom => import => add this link
https://easylist-downloads.adblockplus.org/cntblock.txt
click "apply changes"

**Comment by dimisa-RUAdList** [comment]
What can I say here? The work of the extension is broken by user settings.

**Comment by mapx-** [comment]
@Oleg-Kharchenko reset uBO to default settings / lists (and do not touch them anymore ..)
