### ISSUE TITLE
geeksforgeeks.org: ads

### ISSUE THREAD

**Issue by bepvte** [uBlockOrigin/uAssets#17354]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There is a anti adblock warning geeksforgeeks now.

```
geeksforgeeks.org##.ad-blocker-modal
```
Hides the warning.

Additionally, when disabling Javascript on the site, an annoyance appears at the bottom (`geeksforgeeks.org###openInApp-modal`):
![image](https://user-images.githubusercontent.com/8226605/228913076-1f2db4b7-b60a-4c37-93b5-b533e61eed68.png)

Do these lists cover annoyances like this or should I submit this to the EasyList Forum instead?
### URL(s) where the issue occurs.

`https://www.geeksforgeeks.org/perl-qw-operator/`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/8226605/228912588-126bac41-4785-4e7a-9496-2f6080a0857e.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 148667
  cosmetic: 200546
  scriptlet: 39318
  html: 1091
listset (total-discarded, last-updated): 
  removed: 
    ublock-quick-fixes: null
    urlhaus-1: null
  added: 
    https://ads-for-open-source.readthedocs.io/en/latest/_static/lists/opensource-ads.txt: 0-0, 6m
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 0-0, 6m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39355-14609, 6m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2145-0, 6m
    https://www.fanboy.co.nz/enhancedstats.txt: 2990-10, 6m
    adguard-generic: 69269-6073, 6m
    adguard-spyware-url: 962-137, 6m
    adguard-annoyance: 65779-6141, 6m
    fanboy-annoyance: 82116-46637, 6m
    fanboy-cookiemonster: 46445-146, 6m
    ublock-annoyances: 4852-8, 6m
    dpollock-0: 11349-470, 6m
  default: 
    user-filters: 40-0, never
    ublock-filters: 34007-122, 7m
    ublock-badware: 5774-0, 7m
    ublock-privacy: 348-2, 6m
    ublock-abuse: 78-0, 6m
    ublock-unbreak: 1955-1, 6m
    easylist: 65201-863, 6m
    easyprivacy: 30755-1973, 6m
    plowe-0: 3751-3, 6m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 90 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  cnameUncloakEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  autoUpdatePeriod: 7
supportStats: 
  allReadyAfter: 3777 ms (selfie)
  maxAssetCacheWait: 1927 ms
```
</details>

**Comment by mapx-** [comment]
yes, using US IP, even with european ip the code is still there

**Comment by stephenhawk8054** [comment]
Ah I see, I can reproduce with US IP now. I'll update it to `geeksforgeeks.org##+js(acs, showAdblockerModal)` so there won't be double scroll bars.

**Comment by mapx-** [comment]
or
`||utilapi.geeksforgeeks.org/api/geo/usergeodetails/*$xhr,1p`

as the relevant check is here:

```
const CheckUserCountry = () => {
   var e = `${utilDjangoCfUrl}api/geo/usergeodetails/`;
   $.ajax({
      url: e,
      type: "GET",
      success: function(e) {
         "US" == e.country_code && (null != window.wrapper && 0 == window.wrapper || null != isAdBlockerPresent && 1 == isAdBlockerPresent) && showAdblockerModal()
      },
      error: function(e, t, a) {
         console.log("HTTP Status : " + t)
      }
   })
};
```

**Comment by mapx-** [comment]
idk, they want to warn only us users, not so privacy-oriented imo

**Comment by stephenhawk8054** [comment]
Yeah I agree, I'll put it in annoyance list.
