### ISSUE TITLE
filecr.com: detection

### ISSUE THREAD

**Issue by hieuck** [uBlockOrigin/uAssets#17356]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://filecr.com/windows/finereader?id=720826011360`

### Category

detection

### Description

tôi đã thử tắt lần lượt toàn bộ bộ lọc mà vẫn bật uBO để xác minh rằng không có bộ lọc nào là nguyên nhân trực tiếp cho việc bị phát hiện này, tôi đã thử tắt toàn bộ tiện ích khác ngoài uBO để xác mình không có tiện ích nào là nguyên nhân cho việc bị phát hiện này, tôi đã thử sử dụng truy cập ẩn danh và chỉ bật uBO cùng với thử tắt lần lượt các bộ lọc như đã làm.

Quá trình thực hiện để "bị phát hiện":
truy cập trang chủ - không bị phát hiện
tìm phần mềm bất kỳ - không bị phát hiện
truy cập vào phần mềm bất kỳ - không bị phát hiện
nhấn tải xuống - bị phát hiện

I have tried disabling all filters one by one while still keeping uBO enabled to verify that no filter is directly causing this detection. I have also tried disabling all other extensions except uBO to confirm that no extension is causing this detection. I have tried using incognito mode and only enabling uBO while also trying to disable filters one by one as previously done.

The process of being "detected":
Access homepage - not detected
Search for any software - not detected
Access any software page - not detected
Click download - detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://user-images.githubusercontent.com/30469654/228985833-98ffe2a6-fb5c-474b-8939-c87b20ddcb20.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 102
filterset (summary): 
  network: 87347
  cosmetic: 40709
  scriptlet: 17505
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1816-2, never
    easylist: 64307-538, never
    easyprivacy: 31066-1175, never
    plowe-0: 3755-592, never
    ublock-abuse: 78-0, never
    ublock-badware: 4753-0, never
    ublock-filters: 33010-104, never
    ublock-privacy: 293-0, never
    ublock-quick-fixes: 421-0, never
    ublock-unbreak: 1937-0, never
    urlhaus-1: 6712-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2788 ms
  maxAssetCacheWait: 29 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
    sentry.io: 2
    zinlab.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
The site shows anti-adb even when I turn off all extensions. Screenshot: https://user-images.githubusercontent.com/66517106/229005908-4e584827-7f4f-40e8-921e-f07f554d120c.png

**Comment by hieuck** [comment]
> The site shows anti-adb even when I turn off all extensions (Screenshot: https://user-images.githubusercontent.com/66517106/229005908-4e584827-7f4f-40e8-921e-f07f554d120c.png)

Hiện tại tôi đang bận không thể kiểm tra khi gỡ uBO ra 
Bạn có thể giúp tôi bằng cách gở uBO ra và kiểm tra lại chứ?

I'm busy right now can't check when removing uBO

Can you help me by remove the uBO and checking again?

**Comment by stephenhawk8054** [comment]
This is a new profile with no extensions

![image](https://user-images.githubusercontent.com/66517106/229008831-af1a21c1-c5ae-467e-86f8-d7e5e5ed5d8d.png)

**Comment by mapx-** [comment]
I guess they fixed it, no such behaviour / tested with various ip

**Comment by coderwashere** [comment]
> I guess they fixed it, no such behaviour / tested with various ip

I turn off all extensions and use different devices and still shows that disable adblocker pop-up.
it seems the issue with the site itself..

**Comment by SpeedxThunder001** [comment]
for me without ublock its works and with it, it's not working

**Comment by mapx-** [comment]
> for me without ublock its works and with it, it's not working

other than opening the page do I have to take other steps to reproduce the detection ?

**Comment by stephenhawk8054** [comment]
I confirm it works normally for me now

**Comment by hieuck** [comment]
sau 1 ngày thì FileCR có vẻ như đã fix lỗi từ phía họ về vấn đề không sử dụng chặn quảng cáo mà vẫn báo tắt
It appears that after one day, FileCR has fixed the issue of not using an ad blocker yet still reporting it as disabled.

![image](https://user-images.githubusercontent.com/30469654/229261712-33fca451-e508-4008-bd80-5376b578e669.png)

**Comment by stephenhawk8054** [comment]
I have updated the filter, force update your filter lists and test again.

**Comment by hieuck** [comment]
![image](https://user-images.githubusercontent.com/30469654/229262345-121ea960-2740-43c5-bceb-ecefe554247a.png)
working after update

**Comment by SpeedxThunder001** [comment]
working here as well

**Comment by neviln** [comment]
It was all working great up until this morning, but the "Please Disable AdBlocker" message has returned.

**Comment by ronny941** [comment]
the popup are returned again

**Comment by neviln** [comment]
It started working again after one of the uBO team fixed the code last night, but the popup has returned again.
I have a feeling they are following one of the threads about this and modifying the code once they see that it's been fixed. I only say this due to the multiple times the adblocker popup returned shortly after you guys fix the issue.

**Comment by ronny941** [comment]
> It started working again after one of the uBO team fixed the code last night, but the popup has returned again. I have a feeling they are following one of the threads about this and modifying the code once they see that it's been fixed. I only say this due to the multiple times the adblocker popup returned shortly after you guys fix the issue.

i understand today the popup are disappeared but she's returned again in every browser
because they readded again with a new code

**Comment by mapx-** [comment]
```
*$image,domain=filecr.com,redirect-rule=1x1.gif
@@||googlesyndication.com^$script,domain=filecr.com
@@||doubleclick.net^$subdocument,domain=filecr.com
```

**Comment by ronny941** [comment]
> ```
> *$image,domain=filecr.com,redirect-rule=1x1.gif
> @@||googlesyndication.com^$script,domain=filecr.com
> @@||doubleclick.net^$frame,domain=filecr.com
> ```

this is the code or is a rule to add on ublock ?
sorry i'm not expert about blocking ads or anti adblocker

**Comment by neviln** [comment]
> *$image,domain=filecr.com,redirect-rule=1x1.gif
> @@||googlesyndication.com^$script,domain=filecr.com
> @@||doubleclick.net^$frame,domain=filecr.com

Go to settings (Dashboard) > My Filters
and then paste the above code and click apply

**Comment by ronny941** [comment]
> > *$image,domain=filecr.com,redirect-rule=1x1.gif
> > @@||googlesyndication.com^$script,domain=filecr.com
> > @@||doubleclick.net^$frame,domain=filecr.com
> 
> Go to settings (Dashboard) > My Filters and then paste the above code and click apply

i have added but the popup continue to appear

**Comment by stephenhawk8054** [comment]
Force update the filter lists again

**Comment by ronny941** [comment]
> Force update the filter lists again

i have force update the filter list but on firefox it don't work

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce?

**Comment by ronny941** [comment]
![Cattura](https://user-images.githubusercontent.com/32131958/230092139-557f1e3c-8f8e-4bb7-9cfd-671f11aaf815.JPG)

for me only on firefox it give that 
on the other browser works normally for now

**Comment by hieuck** [comment]
> > https://user-images.githubusercontent.com/30469654/229262345-121ea960-2740-43c5-bceb-ecefe554247a.png working after update
> 
> 4 ngày trước tôi chưa cập nhật gì nhưng vẫn hoạt động bình thường mà,
> 
> 4 days ago I didn't update anything but still working normally, ![image](https://user-images.githubusercontent.com/30469654/230091724-38f0dc90-18e8-4109-9063-818f1c93c137.png)

sau khi tôi cập nhật bộ lọc thì đã xuất hiện pop-up
after i updated the filter pop-up appeared
![image](https://user-images.githubusercontent.com/30469654/230092462-cb8fa259-1e3e-40a9-92f9-c0c25b182e65.png)

**Comment by stephenhawk8054** [comment]
> i have cleared the cache and update the filters again i closed firefox and i reopened firefox and when i go on filecr.com and i click to "direct download" the popup appear

I can't reproduce. Video: https://user-images.githubusercontent.com/66517106/230092863-25d56a47-6634-4612-9f45-fcb30be60604.mp4

Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by mapx-** [comment]
it's ok in FF too on my end

**Comment by ronny941** [comment]
https://user-images.githubusercontent.com/32131958/230094763-9303746c-c68d-4a4c-b647-8f071bf10ef5.mp4


i have done it but it appears again

**Comment by mapx-** [comment]
@ronny941 do not post again and again the same thing.

follow ALL these indications and then test again:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by ronny941** [comment]
i'm using the dns of cloudflare

**Comment by hieuck** [comment]
https://user-images.githubusercontent.com/30469654/230096848-322d0f95-b497-4db2-8fc0-f9a12cae6e6f.mp4

**Comment by stephenhawk8054** [comment]
> i'm using the dns of cloudflare

Check **all** the indications we list out, do not just check only 1 thing.

**Comment by stephenhawk8054** [comment]
@hieuck Turn off Firefox' built-in blocker

**Comment by hieuck** [comment]
> @hieuck Turn off Firefox' built-in blocker

ồ, tôi chỉ là quay video để nói rằng mọi thứ đã ổn, cám ơn
oh, i was just taking a video to say everything is fine, thanks

**Comment by ronny941** [comment]
> @ronny941 do not post again and again the same thing.
> 
> follow ALL these indications and then test again:
> 
>     * clear cookies / localStorage/ cache for the tested page
> 
>     * reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> 
>     * disable any custom filter for that site
> 
>     * disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> 
>     * if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
> 
>     * disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> 
>     * are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
> 
>     * restart the system, reopen the browser, test again.

i tried but the popup appear again
this only on firefox happens, on the other browser it works perfectly
i update the filters and cleared the cache but everytime that popup appear 
i have done all the steps but the popup is still here
in the others browser it works

**Comment by stephenhawk8054** [comment]
> it appear when i disabled all the extensions

You mean you disable **all** extensions and the anti adblock still appears? Can you screenshot that?

**Comment by ronny941** [comment]
![Cattura](https://user-images.githubusercontent.com/32131958/230108452-5397a14f-8bdb-492d-9814-03b288475156.JPG)

**Comment by ronny941** [comment]
on firefox for me sometimes it works and sometime not

**Comment by ronny941** [comment]
> 

It's not that I don't follow the guides
i try eliminate the cookies 
i try reset ublock origin and update the filters again
i have cleaned the cache and updated the filters again but the popup appears
i have removed and installed again ublock origin
on my filters i don't have any rule about filecr
antivirus or antimalware i don't have on my system
I follow all the steps I try but it doesn't work
for me before they added the popup again it works perfectly 
but now for some reasons only on firefox the popup appear in the other browsers it's ok

**Comment by stephenhawk8054** [comment]
> disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc

**Comment by ronny941** [comment]
https://user-images.githubusercontent.com/32131958/230112592-6073c5a6-6cbb-47db-b8e7-b5f0c45512ad.mp4

the tracking protection for firefox is disabled for filecr 
it seems when i closed the popup and i click to "direct download" it works but that popup it should be vanished right ?

**Comment by ronny941** [comment]
the popup appear but if i closed the download started again
i disabled privacy badger because when this extension are activated it appears normally

**Comment by stephenhawk8054** [comment]
> disable any other extension / addon in your browser

![image](https://user-images.githubusercontent.com/66517106/230108864-9ac6bad8-df79-4cb1-b4a5-b6573a7048b4.png)

**Comment by ronny941** [comment]
violentmonkey is the problem

**Comment by stephenhawk8054** [comment]
Thank you very much. Finally you've done the thing we have repeated 4 times.

**Comment by ronny941** [comment]
> Thank you very much. Finally you've done the thing we have repeated 4 times.

I noticed that after a while it reappears but if you close it it works

**Comment by ronny941** [comment]
i have blocked the popup with the block element function now it's gone
