### ISSUE TITLE
[nsfw] allporncomic.com: breakage

### ISSUE THREAD

**Issue by alexsndf** [uBlockOrigin/uAssets#17355]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://allporncomic.com/`

### Category

breakage

### Description

Realtime search bar doesn't work when uBlock is on

### Screenshot(s)

Here's an example of how it looks with uBlock on and off

<details>
<summary>Screenshot(s)</summary>

with uBlock enabled
![image](https://user-images.githubusercontent.com/120376205/228961615-b8407c8f-63bb-4d41-89c1-6079c84b66c1.png)

with uBlock disabled
![image](https://user-images.githubusercontent.com/120376205/228961876-940e41db-2e13-479a-bd5a-925872e28662.png)

</details>

It is also blocking other sites on Wordpress with this same layout

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 89427
  cosmetic: 43043
  scriptlet: 17763
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65003-45, 8h.40m
    easyprivacy: 30725-1175, 8h.39m
    plowe-0: 3751-934, 3h.24m
    spa-1: 5143-69, 8h.43m
    ublock-abuse: 78-0, 4h.21m
    ublock-badware: 5490-114, 4h.19m
    ublock-filters: 33106-123, 4h.18m
    ublock-privacy: 299-2, 4h.17m
    ublock-quick-fixes: 458-11, 4h.16m
    ublock-unbreak: 1944-43, 4h.15m
    urlhaus-1: 6931-0, 4h.14m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 145 ms (selfie)
  maxAssetCacheWait: 89 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    allporncomic.com: 2
    cloudflareinsights.com: 1
    googletagmanager.com: 1
    o333o.com: 7
    profield.ddns.net: 3
```
</details>

**Comment by Procyon-b** [comment]
This will solve the problem
```
allporncomic.com#@#+js(abort-on-property-read, document.dispatchEvent)
```

The filter was added in https://github.com/uBlockOrigin/uAssets/issues/12328

@mapx- any issue you foresee with this filter disabled?

**Comment by alexsndf** [comment]
I added the filter and the problem was solved!!
Thanks for the agility.

But what about other users who access sites with this same layout, wouldn't it be better to generate an update for everyone?

**Comment by mapx-** [comment]
> It is also blocking other sites on Wordpress with this same layout


Which ones ?

**Comment by mapx-** [comment]
This one has been fixed, if you identify other broken pages just post here example links. Closing for now.
