### ISSUE TITLE
swatchseries.ru: breakage

### ISSUE THREAD

**Issue by Anoneemouse** [uBlockOrigin/uAssets#17359]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://swatchseries.ru/movie/in-the-name-of-the-father-9oxn/1-full`

### Category

breakage

### Description

I tried to answer your questions as best I could - but for example, I can't find a button for checking duplicates and clicking the link doesn't seem to do anything.  

Anyhow, on this site, for all of their pages, plus on other pass through streaming sites that have streamtape as an option, it seems that Ublock is blocking streamtape videos.  This started very recently - they used to work just fine but now if you select streamtape, instead of being able to play the video, the video screen is gray with a frowny face in it and text saying it's being blocked by an extension.  

If I go to the streamtape.com site itself, however, their homepage displays fine and isn't blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 87766
  cosmetic: 39643
  scriptlet: 17460
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    easylist: 64765-45, 3d.7h.18m
    easyprivacy: 30729-1175, 3d.7h.18m
    plowe-0: 3751-934, 3d.7h.18m
    ublock-abuse: 78-0, 3d.7h.18m
    ublock-badware: 5411-114, 3d.7h.18m
    ublock-filters: 33074-92, 3d.7h.18m
    ublock-privacy: 295-2, 3d.7h.18m
    ublock-quick-fixes: 417-6, 1d.59m
    ublock-unbreak: 1939-42, 3d.7h.18m
    urlhaus-1: 6995-0, 1d.58m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 266 ms (selfie)
  maxAssetCacheWait: 82 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    swatchseries.ru: 2
    acscdn.com: 1
    addthis.com: 1
    amung.us: 1
    disqus.com: 1
    googletagmanager.com: 1
    rezync.com: 1
    streamadblocker.xyz: 1
    streamtape.com: 1
    subpenaveinery.com: 1
    vizcloud.co: 1
```
</details>

**Comment by mapx-** [comment]
force an update of all filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by ghajini** [comment]
force update the filters

**Comment by Anoneemouse** [comment]
Thank you!  I'm sorry also - I'd done that yesterday, and thought that was sufficient - obviously not, because it's working properly now after purging the cache and updating again!!
