### ISSUE TITLE
bs.to: breakage

### ISSUE THREAD

**Issue by OfficialDayL** [uBlockOrigin/uAssets#17366]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bs.to/serie/The-Wire/1/2-Die-Einheit/de/Streamtape`

### Category

breakage

### Description

streamtape gets completely blocked

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 90656
  cosmetic: 44098
  scriptlet: 17468
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    DEU-0: 6704-0, 18h.18m
    easylist: 64944-51, 3d.15h.17m
    easyprivacy: 30731-1184, 1d.15h.32m
    plowe-0: 3751-935, 5d.15h.30m
    ublock-abuse: 78-0, 7d.38m
    ublock-badware: 5411-114, 3d.15h.16m
    ublock-filters: 33075-105, 3d.15h.15m
    ublock-privacy: 293-2, 7d.36m
    ublock-quick-fixes: 458-6, 18h.20m
    ublock-unbreak: 1939-43, 3d.15h.14m
    urlhaus-1: 7456-0, 18h.19m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 141 ms (selfie)
  maxAssetCacheWait: 57 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    achcdn.com: 1
    addthis.com: 1
    fnbauniukvi.com: 1
    streamadblocker.xyz: 1
    streamtape.com: 1
    subpenaveinery.com: 1
    yandex.ru: 1
    youradexchange.com: 2
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0a9843fc13015897cc0bf03bdae29b9286f80af8
