### ISSUE TITLE
brittany-ferries.co.uk: breakage

### ISSUE THREAD

**Issue by LordGnomeMBE** [uBlockOrigin/uAssets#17363]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.brittany-ferries.co.uk/`

### Category

breakage

### Description

when uBO is enabled, the button in the top-righthand corner marked "My Account" does not function. I believe uBO is blobking the login popup.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 88814
  cosmetic: 39407
  scriptlet: 17477
  html: 933
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33993-49, 1d.7h.13m
    ublock-badware: 5489-0, 1d.7h.16m
    ublock-privacy: 307-0, 4d.7h.53m
    ublock-abuse: 78-0, 4d.7h.52m
    ublock-unbreak: 1955-1, 1d.7h.14m
    ublock-quick-fixes: 455-0, 3h.55m
    easylist: 64987-565, 2d.5h.55m
    easyprivacy: 30725-1767, 4d.49m
    urlhaus-1: 7456-0, 3h.56m
    plowe-0: 3751-2, 4d.7h.54m
filterset (user): [empty]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3264 ms (selfie)
  maxAssetCacheWait: 153 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googletagmanager.com: 1
    sentry.io: 2
    trustpilot.com: 1
    typekit.net: 2
```
</details>

**Comment by mapx-** [comment]
tested FF / chrome, no issue on my end (that button is clickable, click login a new login window is opened etc)

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by peace2000** [comment]
Can't repro either.
