### ISSUE TITLE
finya.de: breakage

### ISSUE THREAD

**Issue by jori2023** [uBlockOrigin/uAssets#17369]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.finya.de/MyFinya/`

### Category

breakage

### Description

hello,

I've been having the same problem described in issue #17334 for a few days. When ublock is on I get a blank web page. it looks like there is a problem in 'ublock filters' with  "finya.de##^script:has-text(===):has-text(/[\w\W]{16000}/)".  while ublock origin  is on and toggle the button to the right of the filter line to blue (see screenshot), the webpage opens as expected. 

i am a newbie and i have no experience with all the filters and rules of ublock origin. It seems to me that the button comments out the filter when it turns blue?! but I'm not really sure and I'm wondering how to fix this permanently?

### Screenshot(s)

![Screenshot from 2023-04-01 03-36-58](https://user-images.githubusercontent.com/129565925/229259657-e45f29d0-7be9-4e84-a0a2-eb84bd56d131.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 88506
  cosmetic: 39742
  scriptlet: 17489
  html: 937
listset (total-discarded, last-updated): 
  default: 
    user-filters: 51-1, never
    ublock-filters: 34018-49, now
    ublock-badware: 5481-0, 2d.3h.20m
    ublock-privacy: 344-0, 4d.5h.34m
    ublock-abuse: 78-0, 4d.5h.33m
    ublock-unbreak: 1955-1, 2d.3h.19m
    ublock-quick-fixes: 457-3, 3h.41m
    easylist: 65003-599, 2d.3h.21m
    easyprivacy: 30755-1767, 1d.8h.4m
    urlhaus-1: 7381-0, 3h.42m
    plowe-0: 3751-2, 2d.12h.24m
filterset (user): [array of 51 redacted]
trustedset: 
  added: [array of 70 redacted]
  removed: 
    about-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2081 ms (selfie)
  maxAssetCacheWait: 1000 ms
popupPanel: 
  blocked: 9
  no-cosmetic-filtering: true
  blockedDetails: 
    amazon-adsystem.com: 1
    google.com: 7
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Does this fix it for you?

```adb
finya.de#@#^script:has-text(===):has-text(/[\w\W]{16000}/)
```

**Comment by jori2023** [comment]
YEAHH!.. looks like this at first glance! thanks a lot for your hint.

**Comment by stephenhawk8054** [comment]
@okiehsch Sorry, is it ok to remove this flter for this website? Since I'm not sure what the filter is used for.

**Comment by okiehsch** [comment]
Sure, if a filter completely breaks a site it has to be removed.

**Comment by jori2023** [comment]
@stephenhawk8054 what does it mean? may i remove the this filter in future from my personal filters?

**Comment by stephenhawk8054** [comment]
It's fixed in the main lists. You can remove the filter in your custom filters and force update the filter lists.

**Comment by jori2023** [comment]
already done. thanks a lot again.
