### ISSUE TITLE
gem.cbc.ca: breakage

### ISSUE THREAD

**Issue by dcecile** [uBlockOrigin/uAssets#17367]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gem.cbc.ca/push`

### Category

breakage

### Description

Click on a video, should autoplay but doesn't

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 89245
  cosmetic: 39734
  scriptlet: 17492
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65218-46, 4h.24m
    easyprivacy: 30908-1178, 4d.6h.47m
    plowe-0: 3752-873, 9d.1m
    ublock-abuse: 78-0, 9d.8h.23m
    ublock-badware: 5831-114, 4h.23m
    ublock-filters: 33141-94, 4h.22m
    ublock-privacy: 293-1, 9d.8h.22m
    ublock-quick-fixes: 458-8, 8h.45m
    ublock-unbreak: 1944-42, 4h.21m
    urlhaus-1: 7381-0, 8h.44m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2283 ms (selfie)
  maxAssetCacheWait: 63 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    cbc.ca: 9
    amplitude.com: 3
    chartbeat.com: 2
    conductrics.com: 1
    crwdcntrl.net: 1
    cxense.com: 1
    doubleclick.net: 1
    facebook.net: 1
    googlesyndication.com: 2
    gstatic.com: 1
    imasdk.googleapis.com: 4
    radio-canada.ca: 2
    scorecardresearch.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test if adding this filter works for you?

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=gem.cbc.ca
```

Add in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click `Apply changes`, go back to the website and press Ctrl + F5 to reload the page and test again.

**Comment by mapx-** [comment]
@stephenhawk8054 working fine

**Comment by dcecile** [comment]
Thank you!
