### ISSUE TITLE
nl.teleqone.com: breakage

### ISSUE THREAD

**Issue by ZnoopTree** [uBlockOrigin/uAssets#17360]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

We use a website that uses clock.js, which is giving us problems since last monday. Works fine without uBO. I found the clock.js entry below in the uBlock Filterlist. I think this is meant to block clock.js on the yts domain, but am i correct in thinking somebody made an error and clock.js is now blocked globally on every website? Shouldn't this line '*/script/clock.js$script' be preceded by yts.? 
I'd like to have this fixed as soon as possible as a lot of our users are affected by this. Thanks in advance.

```adb
yts.*##+js(aeld, , _0x)
yts.*##+js(aopr, runAdblock)
yts.*##+js(aopw, _pop)
yts.*##+js(nowoif)
yts.*##+js(nostif, "admc")
yts.*##+js(acs, setTimeout, admc)
*/script/clock.js$script
yts.*##[id*="container"][id^="id"]
yts.*##html:style(overflow: auto !important;)
yts.*##.vpn-link:upward(1)
yts.*##.cborz-bordered
yts.*##.madikf
||empied.com^
```

### URL(s) where the issue occurs.

`https://nl.teleqone.com`
It happens after the login screen, so it's not reproducible from the outside.

### uBO version

1.48.2

### Browser name and version

Microsoft Edge 111.0.1661.44

### Settings

None

**Comment by krystian3w** [comment]
> be preceded by yts.*?

or ended by:

```adb
$domain=yts.*
```
