### ISSUE TITLE
creativecloud.adobe.com: breakage

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#17364]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://creativecloud.adobe.com/`

### Category

breakage

### Description

The “Download” button under “Download Creative Cloud” doesn't work with uBlock Origin enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/22180480/229178228-0b023d64-178d-4027-befa-7cf63cf37345.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Chromium: 111
filterset (summary): 
  network: 89418
  cosmetic: 39735
  scriptlet: 17497
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65360-46, now
    easyprivacy: 30755-1175, now
    plowe-0: 3750-935, now
    ublock-abuse: 78-0, now
    ublock-badware: 6080-114, now
    ublock-filters: 33148-96, now
    ublock-privacy: 302-2, now
    ublock-quick-fixes: 456-14, now
    ublock-unbreak: 1941-42, now
    urlhaus-1: 7381-0, now
filterset (user): [empty]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 12915 ms
  maxAssetCacheWait: 387 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    adobe.io: 25
    demdex.net: 1
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||cc-api-data.adobe.io/ingest/?api_key=cchome-web-service$xhr,domain=creativecloud.adobe.com`

@ryanbr
