### ISSUE TITLE
uBO is detected by onlinefreecourse.net and blockadblock.com

### ISSUE THREAD

**Issue by updeshxp** [uBlockOrigin/uAssets#1737]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
onlinefreecourse.net
blockadblock.com
### Describe the issue

uses Blockadblock.com which cannot be blocked.

### Screenshot(s)

![untitled2](https://user-images.githubusercontent.com/17386732/37570213-115214ba-2b13-11e8-8f78-dffa935a6fbb.png)

### Versions

- Browser/version: 65.0.3325.162 (Official Build) (64-bit)
- uBlock Origin version: 1.15.2

### Settings

- checked all ublock lists

### Notes

used *##script:inject(bab-defuser.js) in my filters but it didn't work.

**Comment by uBlock-user** [comment]
`*##script:inject(bab-defuser.js)` is invalid, put a hostname, not a wildcard.
