### ISSUE TITLE
mangadex.org: [unknown]

### ISSUE THREAD

**Issue by Dante2178** [uBlockOrigin/uAssets#17372]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mangadex.org/`

### Category

[unknown]

### Description

There are ads on this page. Using firefox mobile with uBlock as only extension.

Thanks for checking on my report!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

https://user-images.githubusercontent.com/16512441/229267417-1cd845e5-3443-46a5-a9ec-660f61bf67d3.png

https://user-images.githubusercontent.com/16512441/229267421-543ea045-a398-409d-86f7-5b2f697f0c21.png

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox Mobile: 111
filterset (summary): 
  network: 89439
  cosmetic: 29824
  scriptlet: 17538
  html: 963
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34185-316, never
    ublock-badware: 5436-0, never
    ublock-privacy: 344-4, never
    ublock-abuse: 78-0, never
    ublock-unbreak: 1955-0, never
    ublock-quick-fixes: 452-1, never
    adguard-mobile: 8711-162, never
    easylist: 65002-17392, never
    easyprivacy: 30741-1769, never
    urlhaus-1: 6933-0, never
    plowe-0: 3751-2, never
filterset (user): [empty]
trustedset: 
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6079 ms
  maxAssetCacheWait: 44 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like self-promo

```adb
mangadex.org##.header.flex-col
```
