### ISSUE TITLE
vk.com: nuisance

### ISSUE THREAD

**Issue by singularClouds** [uBlockOrigin/uAssets#17376]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vk.com/feed`

### Category

nuisance

### Description

the phone number confirmation window that cannot be closed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Без имени-1](https://user-images.githubusercontent.com/100662304/229274900-6bdae761-a84a-4a76-98e4-62a5b115dd46.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 105599
  cosmetic: 60640
  scriptlet: 18730
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    RUS-0: 39506-12, 1d.5h.12m
    easylist: 65080-63, 3d.5h.18m
    easyprivacy: 30745-1282, 1d.5h.13m
    plowe-0: 3751-939, 2d.13h.2m
    ublock-abuse: 78-1, 3d.11h.50m
    ublock-badware: 5411-114, 2d.21h.16m
    ublock-filters: 33099-123, 2d.21h.15m
    ublock-privacy: 295-2, 3d.11h.49m
    ublock-quick-fixes: 455-11, 17h.11m
    ublock-unbreak: 1939-42, 2d.21h.14m
    urlhaus-1: 7381-0, 17h.10m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 181 ms (selfie)
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This is not advertising and not an irritant, but an element of the security system.
