### ISSUE TITLE
linkvertise.com: ads

### ISSUE THREAD

**Issue by Hoangnguyen72628** [uBlockOrigin/uAssets#17373]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/`

### Category

ads

### Description

Linkvertise is still not appear free access

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium Mobile: 111
filterset (summary): 
  network: 88811
  cosmetic: 30878
  scriptlet: 17590
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1857-15, now
    adguard-mobile: 8711-33, now
    easylist: 64307-16907, never
    easyprivacy: 31066-1184, never
    plowe-0: 3755-1015, never
    ublock-abuse: 78-0, never
    ublock-badware: 4747-115, never
    ublock-filters: 33216-335, never
    ublock-privacy: 293-2, never
    ublock-quick-fixes: 426-7, never
    ublock-unbreak: 1942-42, never
    urlhaus-1: 6712-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3269 ms
  maxAssetCacheWait: 959 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    taboola.com: 2
    thinksuggest.org: 2
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
ads ? screenshot ?

> Linkvertise is still not appear free access

explain better this affirmation

**Comment by peace2000** [comment]
Probably if means this:

`https://linkvertise.com/106636/XRayUpdate/1`

https://user-images.githubusercontent.com/17256841/229357224-6af764f9-7c27-407e-8c77-d57cb9f0741f.png

When you click "Free Access with Ads" you'll have to install something crap in order to access the content:

https://user-images.githubusercontent.com/17256841/229357345-4849e370-9a62-4343-9d19-839e77968c39.png

**Comment by mapx-** [comment]
yes, indeed, however it's self-promo I'd say.
