### ISSUE TITLE
volkskrant.nl: nuisance

### ISSUE THREAD

**Issue by Waxli** [uBlockOrigin/uAssets#17374]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.volkskrant.nl/nieuws-achtergrond/vrouwonvriendelijke-influencer-andrew-tate-uit-gevangenis-en-krijgt-huisarrest~b9331969/`

### Category

nuisance

### Description

The payment popup appears and when trying to zapp it, the page becomes unscrollable. 
This happens with all newspaperwebsites from this publisher and makes browsing really annoying. These are the top dutch newssources.
Hereby a detailed list of all websites effected:

```
Het AD: [www.ad.nl](http://www.ad.nl/)
de Volkskrant: [www.volkskrant.nl](http://www.volkskrant.nl/)
Het Parool: [www.parool.nl](http://www.parool.nl/)
Trouw: [www.trouw.nl](http://www.trouw.nl/)
BN DeStem: [www.bndestem.nl](http://www.bndestem.nl/)
Brabants Dagblad: [www.bd.nl](http://www.bd.nl/)
het ED: [www.ed.nl](http://www.ed.nl/)
de Gelderlander: [www.gelderlander.nl](http://www.gelderlander.nl/)
de PZC: [www.pzc.nl](http://www.pzc.nl/)
de Stentor: [www.destentor.nl](http://www.destentor.nl/)
Tubantia: [www.tubantia.nl](http://www.tubantia.nl/)
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 88966
  cosmetic: 41348
  scriptlet: 17494
  html: 0
listset (total-discarded, last-updated): 
  added: 
    NLD-0: 2575-14, 2d.13h.23m
  default: 
    user-filters: 3-0, never
    easylist: 64672-48, 4d.5h.15m
    easyprivacy: 30731-1176, 2d.13h.24m
    plowe-0: 3751-934, 4d.9h.16m
    ublock-abuse: 78-0, 7d.2h.15m
    ublock-badware: 5411-114, 4d.5h.14m
    ublock-filters: 33075-113, 4d.5h.12m
    ublock-privacy: 293-2, 7d.2h.16m
    ublock-quick-fixes: 455-6, 1d.7h.6m
    ublock-unbreak: 1939-47, 4d.5h.13m
    urlhaus-1: 7456-0, 1d.7h.5m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 50 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 567 ms (selfie)
  maxAssetCacheWait: 817 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    volkskrant.nl: 4
    dpgmedia.cloud: 4
    usabilla.com: 1
```
</details>

**Comment by mapx-** [comment]
for this site

```
volkskrant.nl##.tm--overlay
volkskrant.nl##.tm-overflow-scroll__space
volkskrant.nl##.tm-overflow-scroll
volkskrant.nl##.tm-backdrop
volkskrant.nl##body:style(overflow: auto !important;)
```

however, then, you'll get their paywall (which we do not fix). To read the whole article just disable javascript on that page.

@BPower0036 your call

**Comment by Waxli** [comment]
Not being able to read the article is not the problem. The problem is that there is a popup that blocks my from continueing browsing. Disabling javascript on the page is not really an option always, for all the news websites in the netherlands. Besides that, then everyone in the netherlands should do that?

**Comment by mapx-** [comment]
did you test the filters above ?

**Comment by BPower0036** [comment]
@mapx- and @Waxli it is just a paywall. And in the right top corner you can close it. As uBlock Origin, does also EasyDutch not fix paywalls. You can add the suggested rules in your own list.
