### ISSUE TITLE
[nsfw] boyloves.fun: ads

### ISSUE THREAD

**Issue by chloe5685** [uBlockOrigin/uAssets#17378]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://boyloves.fun/`

### Category

ads

### Description

Everytime I block several ads manually, they just keep occuring later.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox Mobile: 111
filterset (summary): 
  network: 107453
  cosmetic: 38807
  scriptlet: 17694
  html: 974
listset (total-discarded, last-updated): 
  default: 
    user-filters: 28-3, never
    ublock-filters: 34233-291, 3d.25m
    ublock-badware: 5483-0, 3d.24m
    ublock-privacy: 348-1, 3d.23m
    ublock-abuse: 78-0, 3d.22m
    ublock-unbreak: 1958-1, 3d.18m
    ublock-quick-fixes: 463-3, 23h.58m
    adguard-mobile: 8649-120, 3d.31m
    easylist: 65102-17516, 3d.16m
    easyprivacy: 30744-1796, 3d.15m
    urlhaus-1: 7381-0, 23h.57m
    plowe-0: 3751-2, 3d.13m
    CHN-0: 28022-1401, 3d.31m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1343 ms (selfie)
  maxAssetCacheWait: 687 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    boyloves.fun: 7
    googlesyndication.com: 1
    googletagmanager.com: 1
    jads.co: 2
    realsrv.com: 2
```
</details>

**Comment by mapx-** [comment]
try

```
boyloves.fun##.reader-home-swiper
boyloves.fun##[src*=".gif"]:upward(1)
boyloves.fun##[href*="yfj8159.com"]
```

@cjx82630
