### ISSUE TITLE
z.gourlpro.com: popups

### ISSUE THREAD

**Issue by pastormorris** [uBlockOrigin/uAssets#17370]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://z.gourlpro.com/`

### Category

popups

### Description

`https://www.thenekodark.com/descargar-easeus-data-recovery-wizard-full/`

donwload software: 

`https://gourlpro.com/o.php?l=VjFaV2IxVXdNVWhVYTJ4VlZrWndUbHBXVW5OTlZtUnpXWHBXYTAxWGVGcFdSM0JEV1ZaV05sWnVSbHBoYTJ3eldrY3hUMUpGT1VsalJUbHNZbGhPTkZaSGRFWlBWa0pTVUZRd1BRPT0=`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 286031
  cosmetic: 140411
  scriptlet: 38563
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adavoid.org/ultimate-ad-filter.txt: 117082-1199, 12h.24m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39346-4226, 2d.16h.28m
    https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt: 65207-312, 1d.1h.38m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24112-21, 1d.11h.23m
    https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt: 200540-46079, 1d.1h.37m
    ublock-annoyances: 4881-138, 4d.51m
  default: 
    user-filters: 396-21, never
    easylist: 64839-64794, 4d.54m
    easyprivacy: 30735-16821, 4d.53m
    plowe-0: 3751-3074, 3d.2h.53m
    spa-0: 3555-40, 8h.22m
    spa-1: 5134-273, 4d.52m
    ublock-abuse: 78-2, 3d.2h.52m
    ublock-badware: 5267-356, 4d.50m
    ublock-filters: 33075-4799, 4d.49m
    ublock-privacy: 295-71, 3d.2h.51m
    ublock-quick-fixes: 455-34, 12h.25m
    ublock-unbreak: 1939-110, 4d.48m
    urlhaus-1: 7381-501, 12h.23m
filterset (user): [array of 396 redacted]
trustedset: 
  added: [array of 122 redacted]
switchRuleset: 
  added: [array of 44 redacted]
hostRuleset: 
  added: [array of 36 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 399 ms (selfie)
  maxAssetCacheWait: 229 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
I get no popup.
Ask on that site how to download if this is your issue.

You should use uBO default lists, no FFA list, no that other huge list (GoodbyeAds)
