### ISSUE TITLE
uhuseries.com: ads

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#17379]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://uhuseries.com/series-online/big-bang-theory-season-7-ep-1-ep-24-%e0%b8%88%e0%b8%9a-%e0%b8%8b%e0%b8%b1%e0%b8%9a%e0%b9%84%e0%b8%97%e0%b8%a2/`

### Category

ads

### Description

I have to watch an ad video before watching a real one.

Oh, I'll have to wait and then click the skip button.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 89411
  cosmetic: 40649
  scriptlet: 17534
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 584-75, never
    THA-0: 1466-3, 2d.21h.45m
    easylist: 65003-45, 2d.2h.43m
    easyprivacy: 30755-1175, 4h.12m
    plowe-0: 3752-933, 10d.14h.41m
    ublock-abuse: 78-0, 12h.14m
    ublock-badware: 5438-114, 3d.1h.46m
    ublock-filters: 33168-96, 4h.10m
    ublock-privacy: 302-2, 12h.15m
    ublock-quick-fixes: 462-20, 9m
    ublock-unbreak: 1945-42, 4h.11m
    urlhaus-1: 7324-0, 8h.13m
filterset (user): [array of 554 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 150 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1699 ms (selfie)
  maxAssetCacheWait: 693 ms
popupPanel: 
  blocked: 82
  blockedDetails: 
    uhuseries.com: 70
    bp.blogspot.com: 1
    facebook.com: 2
    googles.video: 2
    googletagmanager.com: 2
    histats.com: 2
    jwpltx.com: 3
```
</details>

**Comment by mapx-** [comment]
test

`||proxy.cdend.com/*.mp4.m3u8$xhr,domain=aplayer.xyz`
