### ISSUE TITLE
it.motorsport.com: detection

### ISSUE THREAD

**Issue by jackdddd** [uBlockOrigin/uAssets#17387]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://it.motorsport.com/f1/news/f1-le-paure-di-wittich-generano-un-effetto-con-piu-rischi/10452274/`

### Category

detection

### Description

The box in the mdlle of the page, titled "Iscriviti ed effettua l'accesso a Motorsport.com con il tuo blocco delle pubblicità" is detectioning the ad blocker and hiding content.

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/48905430/229358912-5cdd38a1-5c9d-4bd7-bb4c-abae72a6c8ed.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 94634
  cosmetic: 47272
  scriptlet: 17380
  html: 934
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34020-49, 1d.18h
    ublock-badware: 6084-0, 20h.4m
    ublock-privacy: 342-0, 8d.19h.42m
    ublock-abuse: 78-0, 8d.15h.40m
    ublock-unbreak: 1956-0, 20h.3m
    easylist: 65218-607, 1d.18h.1m
    easyprivacy: 30755-1767, 2d.17h.50m
    plowe-0: 3752-2, 4h.1m
    ITA-0: 13509-1, 20h.2m
    urlhaus-1: 7112-0, 8h.2m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 882 ms (selfie)
  maxAssetCacheWait: 582 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    motorsport.com: 3
    cxense.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Quick fixes`
