### ISSUE TITLE
hornoxe.com: breakage

### ISSUE THREAD

**Issue by Ageraluon** [uBlockOrigin/uAssets#17384]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hornoxe.com/hornoxe-com-picdump-688/`

### Category

breakage

### Description

Content, I.e. pictures are not visible when abp is active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox Mobile: 111
filterset (summary): 
  network: 92098
  cosmetic: 33839
  scriptlet: 17569
  html: 975
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    ublock-filters: 34249-292, 2d.14h.49m
    ublock-badware: 5488-0, 23h.39m
    ublock-privacy: 344-1, 5d.42m
    ublock-abuse: 78-0, 4d.18h
    ublock-unbreak: 1960-1, 23h.40m
    adguard-mobile: 8652-128, 2d.14h.47m
    easylist: 65170-17475, 3d.9h.33m
    easyprivacy: 30755-1785, 2d.6h.46m
    urlhaus-1: 7112-0, 2h.48m
    plowe-0: 3751-2, 6d.6h.56m
    DEU-0: 6705-388, 2h.50m
    ublock-quick-fixes: 469-3, 2h.47m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5457 ms (selfie)
  maxAssetCacheWait: 2626 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    hornoxe.com: 2
    amung.us: 2
    extreme-dm.com: 3
    google-analytics.com: 1
    themoneytizer.com: 12
```
</details>

**Comment by mapx-** [comment]
add

```
hornoxe.com#@#div.post:has(a[href^="https://www.amazon.de/"])
hornoxe.com##.ivycat-post:has(a[href^="https://www.amazon.de/"])
```

@khrin
