### ISSUE TITLE
hulu.com: breakage/ads

### ISSUE THREAD

**Issue by osterac** [uBlockOrigin/uAssets#17382]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hulu.com/watch/3f1757b7-c524-4706-9042-7b22ac36e10c`

### Category

breakage

### Description

When adblock is on, subtitles are out of sync by several seconds.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 14470
  cosmetic: 10143
  scriptlet: 17517
  html: 939
listset (total-discarded, last-updated): 
  removed: 
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 34071-56, 5m
    ublock-badware: 6221-0, 5m
    ublock-privacy: 352-0, 5m
    ublock-abuse: 78-0, 5m
    ublock-unbreak: 1956-1, 5m
    ublock-quick-fixes: 463-5, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 763 ms
  maxAssetCacheWait: 237 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    omtrdc.net: 1
```
</details>

**Comment by mapx-** [comment]
there is not much to do: disable uBO for hulu or use an extension and subtitles downloaded from somewhere that you can sync manually

**Comment by stephenhawk8054** [comment]
Based on this discussion here: https://www.reddit.com/r/uBlockOrigin/comments/146hnll/ads_on_hulu/

I guess the reason the subtitles are not in synced is because with only `json-prune`, the cuepoints for the ads are gone, but the ads connections are still played directly, and making the total timing wrong (total timing = video timing + ads timing). That's why we would need `xml-prune` or `m3u-prune` together with `json-prune` to remove those ads completely.

These filters might work:

```adb
hulu.com#@#+js(json-prune, breaks pause_ads)
hulu.com##+js(json-prune, breaks pause_ads video_metadata.end_credits_time)
hulu.com##+js(xml-prune, xpath(//*[name()="MPD"]/@mediaPresentationDuration | //*[name()="Period"][starts-with(@id\, "Ad")] | //*[name()="Period"]/@start), , .mpd)
```

**Comment by ShelbyCobraFan** [comment]
My post wasn't really duplicate as the site is not broken, the blocker simply does not block ads. The filters listed above did work however so thanks.

**Comment by terrorist96** [comment]
Works for me

**Comment by ShelbyCobraFan** [comment]
Yup that works, thank you very much.
