### ISSUE TITLE
autofaucet.dutchycorp.space: nuisance

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#17380]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://autofaucet.dutchycorp.space/coin_roll.php`

### Category

nuisance

### Description

in the browser window when viewing the mobile version of the site on android, a tab is attached at the top that constantly pops up and annoys with the content:
`https://advertisers.pubpower.io/create/?target_inventories=autofaucet.dutchycorp.space`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox Mobile: 111
filterset (summary): 
  network: 72599
  cosmetic: 37162
  scriptlet: 18824
  html: 979
listset (total-discarded, last-updated): 
  removed: 
    easylist: null
  default: 
    user-filters: 0-0, never
    ublock-filters: 34251-307, 2d.25m
    ublock-badware: 5829-0, 2d.27m
    ublock-privacy: 343-1, 9d.3h.54m
    ublock-abuse: 78-0, 9d.3h.53m
    ublock-unbreak: 1960-1, 2d.28m
    adguard-mobile: 8652-120, 2d.24m
    easyprivacy: 30744-1882, 3d.6h.9m
    urlhaus-1: 7324-0, 18h.4m
    plowe-0: 3755-2, 12d.15h.26m
    RUS-0: 39525-910, 1d.21h.30m
    ublock-quick-fixes: 463-1, 18h.5m
filterset (user): [empty]
modifiedUserSettings: 
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3815 ms (selfie)
  maxAssetCacheWait: 301 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    dutchycorp.space: 3
    a-ads.com: 4
    amazon-adsystem.com: 1
    cpx-research.com: 1
    googletagmanager.com: 3
    googletagservices.com: 1
    imasdk.googleapis.com: 1
    tradingview.com: 1
    vliplatform.com: 6
```
</details>

**Comment by mapx-** [comment]
use the element picker, see if you can create a filter

**Comment by mapx-** [comment]
I see only an add

`autofaucet.dutchycorp.space##.show-on-medium`
