### ISSUE TITLE
assettoworld.com: detection

### ISSUE THREAD

**Issue by swaytuned** [uBlockOrigin/uAssets#17386]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.assettoworld.com/`

### Category

detection

### Description

Load into site and it has a popup letting you know that it has detected an ad blocker. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![fa8ef7c3fbaf2a2835548d0416169967](https://user-images.githubusercontent.com/59124647/229349162-7dec2380-d580-4b42-9612-20d1f4b007b2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 89257
  cosmetic: 22652
  scriptlet: 17485
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 181-53, never
    easylist: 65198-16899, 2m
    easyprivacy: 30767-1179, 2m
    plowe-0: 3752-936, 2m
    ublock-abuse: 78-0, 2m
    ublock-badware: 6217-114, 2m
    ublock-filters: 33224-313, 2m
    ublock-privacy: 302-3, 2m
    ublock-quick-fixes: 362-25, 2m
    ublock-unbreak: 1944-43, 2m
    urlhaus-1: 7112-0, 2m
filterset (user): [array of 575 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 959 ms (selfie)
  maxAssetCacheWait: 223 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    assettoworld.com: 1
    googletagmanager.com: 1
    nitropay.com: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
Is the detection reproducible only after logging in the page ?

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by swaytuned** [comment]
It pops up everytime I have gone to the page in the last few weeks. Logged in or not. Accessing from the US.

**Comment by mapx-** [comment]
reproduced using us ip
