### ISSUE TITLE
entutes.com: detection

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#17385]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://entutes.com/easy-way-to-have-ghostface-voice-with-wootechy/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 106074
  cosmetic: 60711
  scriptlet: 18749
  html: 943
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34019-52, 9h.11m
    ublock-badware: 6084-0, 9h.10m
    ublock-privacy: 352-0, 9h.9m
    ublock-abuse: 78-0, 9h.8m
    ublock-unbreak: 1956-1, 9h.7m
    ublock-quick-fixes: 460-5, 9h.3m
    easylist: 65128-621, 9h.6m
    easyprivacy: 30766-1875, 9h.5m
    urlhaus-1: 7138-0, 9h.2m
    plowe-0: 3750-2, 8d.9h.57m
    RUS-0: 39539-49, 9h.4m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1467 ms (selfie)
  maxAssetCacheWait: 960 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    doubleclick.net: 1
    googletagmanager.com: 1
    orquideassp.com: 21
    wp.com: 4
```
</details>

**Comment by mapx-** [comment]
@lyubomyrhv 

Here is the thread for these shorteners:
https://github.com/uBlockOrigin/uAssets/discussions/17361

We'll dedicate less time to such issues.
