### ISSUE TITLE
deezer.com: breakage

### ISSUE THREAD

**Issue by daxpedda** [uBlockOrigin/uAssets#17392]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

While playing a playlist it sometimes just stops playing music, displaying that it's trying to run an "Ad", but you can't actually hear the Ad and it never continues playing music again.

### URL(s) where the issue occurs.

`https://www.deezer.com`

### Screenshot(s)

This is what it shows in the bottom instead of the song's title:
![image](https://user-images.githubusercontent.com/1645124/229278478-0a8a99c2-6080-4f02-b457-c1224a02b1d9.png)

### uBO version

1.48.2

### Browser name and version

Firefox 111.0.1 (64-bit)

### Settings

None. I'm in Austria, so there isn't even a region list I added.

### Notes

I created a new browser profile, installed uBlock Origin, deactivated Firefox's enhanced tracking protection and ran the logger there until the music stopped.
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +606 | \|\|hubvisor.io^$3p | -- | `www.deezer.com` | 3 | get | xhr | `https://beam.hubvisor.io/player-events?publisherId=01GBANTCTXS9RFE5JMJREEZJ2Y&source=audio-relay&version=1.0.122&pageViewId=96918035-c211-4ce8-b4bc-443723725213&auctionId=96918035-c211-4ce8-b4bc-443723725213&network=deezer&brand=deezer&support=deezer.web&zone=ros&layout=desktop&connector=backfill&currency=USD&rawCpm=0&rawUsdCpm=0&adjustedUsdCpm=0&netUsdCpm=0&placementId=audio-prod&mediaType=audio&consentString=CPl2bbgPl2bbgA7ABBENCsCgAAAAAAAAAAqIAAAAAAAA.flAAAAAAAAA&gdprApplies=true&userAgent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F111.0&kind=complete` |
| +599 | \|\|hubvisor.io^$3p | -- | `www.deezer.com` | 3 | get | xhr | `https://beam.hubvisor.io/player-events?publisherId=01GBANTCTXS9RFE5JMJREEZJ2Y&source=audio-relay&version=1.0.122&pageViewId=96918035-c211-4ce8-b4bc-443723725213&auctionId=96918035-c211-4ce8-b4bc-443723725213&network=deezer&brand=deezer&support=deezer.web&zone=ros&layout=desktop&connector=backfill&currency=USD&rawCpm=0&rawUsdCpm=0&adjustedUsdCpm=0&netUsdCpm=0&placementId=audio-prod&mediaType=audio&consentString=CPl2bbgPl2bbgA7ABBENCsCgAAAAAAAAAAqIAAAAAAAA.flAAAAAAAAA&gdprApplies=true&userAgent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F111.0&kind=third-quartile` |
| +592 | \|\|hubvisor.io^$3p | -- | `www.deezer.com` | 3 | get | xhr | `https://beam.hubvisor.io/player-events?publisherId=01GBANTCTXS9RFE5JMJREEZJ2Y&source=audio-relay&version=1.0.122&pageViewId=96918035-c211-4ce8-b4bc-443723725213&auctionId=96918035-c211-4ce8-b4bc-443723725213&network=deezer&brand=deezer&support=deezer.web&zone=ros&layout=desktop&connector=backfill&currency=USD&rawCpm=0&rawUsdCpm=0&adjustedUsdCpm=0&netUsdCpm=0&placementId=audio-prod&mediaType=audio&consentString=CPl2bbgPl2bbgA7ABBENCsCgAAAAAAAAAAqIAAAAAAAA.flAAAAAAAAA&gdprApplies=true&userAgent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F111.0&kind=midpoint` |
| +584 | \|\|hubvisor.io^$3p | -- | `www.deezer.com` | 3 | get | xhr | `https://beam.hubvisor.io/player-events?publisherId=01GBANTCTXS9RFE5JMJREEZJ2Y&source=audio-relay&version=1.0.122&pageViewId=96918035-c211-4ce8-b4bc-443723725213&auctionId=96918035-c211-4ce8-b4bc-443723725213&network=deezer&brand=deezer&support=deezer.web&zone=ros&layout=desktop&connector=backfill&currency=USD&rawCpm=0&rawUsdCpm=0&adjustedUsdCpm=0&netUsdCpm=0&placementId=audio-prod&mediaType=audio&consentString=CPl2bbgPl2bbgA7ABBENCsCgAAAAAAAAAAqIAAAAAAAA.flAAAAAAAAA&gdprApplies=true&userAgent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F111.0&kind=first-quartile` |
| +578 | \|\|hubvisor.io^$3p | -- | `www.deezer.com` | 3 | get | xhr | `https://beam.hubvisor.io/imp?publisherId=01GBANTCTXS9RFE5JMJREEZJ2Y&source=audio-relay&version=1.0.122&pageViewId=96918035-c211-4ce8-b4bc-443723725213&auctionId=96918035-c211-4ce8-b4bc-443723725213&network=deezer&brand=deezer&support=deezer.web&zone=ros&layout=desktop&connector=backfill&currency=USD&rawCpm=0&rawUsdCpm=0&adjustedUsdCpm=0&netUsdCpm=0&placementId=audio-prod&mediaType=audio&consentString=CPl2bbgPl2bbgA7ABBENCsCgAAAAAAAAAAqIAAAAAAAA.flAAAAAAAAA&gdprApplies=true&userAgent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F111.0` |
| +577 | noopmp3-0.1s | << | `www.deezer.com` | 3 | get | media | `https://e-cdns-content.dzcdn.net/ads/autopromo/2021/09/unlimited-skip/de_DE_13_unlimitedskip_.mp3` |
| +577 | /ads/autopromo/*$media,redirect-rule=noopmp3-0.1s,from=deezer.com | -- | `www.deezer.com` | 3 | get | media | `https://e-cdns-content.dzcdn.net/ads/autopromo/2021/09/unlimited-skip/de_DE_13_unlimitedskip_.mp3` |
| +577 | /ads/autopromo/*$media,from=deezer.com | -- | `www.deezer.com` | 3 | get | media | `https://e-cdns-content.dzcdn.net/ads/autopromo/2021/09/unlimited-skip/de_DE_13_unlimitedskip_.mp3` |
| +576 | \|\|smartadserver.com^$3p,from=~smartadserver.de\|~smartadserver.fr | -- | `www.deezer.com` | 3 | post | xhr | `https://ww400.smartadserver.com/400/call` |
| +576 | \|\|smartadserver.com^$3p,from=~smartadserver.de\|~smartadserver.fr | -- | `www.deezer.com` | 3 | post | xhr | `https://ww400.smartadserver.com/400/call` |
| +399 | \|\|smartadserver.com^$3p,from=~smartadserver.de\|~smartadserver.fr | -- | `www.deezer.com` | 3 | post | xhr | `https://ww400.smartadserver.com/400/call` |
| +172 | \|\|smartadserver.com^$3p,from=~smartadserver.de\|~smartadserver.fr | -- | `www.deezer.com` | 3 | post | xhr | `https://ww400.smartadserver.com/400/call` |
| +171 | noopmp3-0.1s | << | `www.deezer.com` | 3 | get | media | `https://e-cdns-content.dzcdn.net/ads/autopromo/2021/09/unlimited-skip/de_DE_13_unlimitedskip_.mp3` |
| +171 | /ads/autopromo/*$media,redirect-rule=noopmp3-0.1s,from=deezer.com | -- | `www.deezer.com` | 3 | get | media | `https://e-cdns-content.dzcdn.net/ads/autopromo/2021/09/unlimited-skip/de_DE_13_unlimitedskip_.mp3` |
| +171 | /ads/autopromo/*$media,from=deezer.com | -- | `www.deezer.com` | 3 | get | media | `https://e-cdns-content.dzcdn.net/ads/autopromo/2021/09/unlimited-skip/de_DE_13_unlimitedskip_.mp3` |
| +170 | \|\|smartadserver.com^$3p,from=~smartadserver.de\|~smartadserver.fr | -- | `www.deezer.com` | 3 | post | xhr | `https://ww400.smartadserver.com/400/call` |
| +170 | \|\|smartadserver.com^$3p,from=~smartadserver.de\|~smartadserver.fr | -- | `www.deezer.com` | 3 | post | xhr | `https://ww400.smartadserver.com/400/call` |
| +0 | \|\|smartadserver.com^$3p,from=~smartadserver.de\|~smartadserver.fr | -- | `www.deezer.com` | 3 | post | xhr | `https://ww400.smartadserver.com/400/call` |
</details>

**Comment by mapx-** [comment]
Go into uBO dashboard, support tab, copy and paste here the info from `Troubleshooting Information`

**Comment by daxpedda** [comment]
```
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 88224
  cosmetic: 39720
  scriptlet: 17484
  html: 936
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33991-50, 2d.9h.5m
    ublock-badware: 5481-0, 2d.9h.4m
    ublock-privacy: 348-0, 2d.9h.3m
    ublock-abuse: 78-0, 2d.9h.2m
    ublock-unbreak: 1955-1, 2d.9h.1m
    ublock-quick-fixes: 466-3, 3h.50m
    easylist: 65218-601, 2d.8h.59m
    easyprivacy: 30755-1767, 2d.8h.58m
    urlhaus-1: 6925-0, 3h.49m
    plowe-0: 3750-2, 2d.8h.56m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 325 ms (selfie)
  maxAssetCacheWait: 117 ms
```

**Comment by mapx-** [comment]
Strange .. I don't see in your logger filters like these
![image](https://user-images.githubusercontent.com/10303732/229381099-518460a2-c13f-4958-abb6-76b58280572c.png)

**Comment by daxpedda** [comment]
I literally didn't touch the settings and it's a new browser profile.
Is there some way to activate those manually?

In any case, if this is supposed to be here then I assume it's a bug? Is it maybe because I'm on Linux?

**Comment by mapx-** [comment]
no .. nvm .. those are in annoyances list

**Comment by mapx-** [comment]
add & test

`deezer.com##+js(nostif, Ads)`

**Comment by daxpedda** [comment]
I just added this line in "My filters"?

Giving it a try, will report back my findings.

**Comment by daxpedda** [comment]
Well, I listened for almost the whole day without interruption, clearly this fix worked.

I don't even know what this fix does. I'm happy to help, with some guidance, to get this upstreamed.

**Comment by mapx-** [comment]
ok, added to our list

**Comment by daxpedda** [comment]
Amazing, thank you so much.
