### ISSUE TITLE
game-2u.com: detection

### ISSUE THREAD

**Issue by sodablueghost** [uBlockOrigin/uAssets#17393]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://game-2u.com/Category/pc`

### Category

detection

### Description

Similar issue to the one that happened with nsw2u.com the other day, just with one of its affiliated sites. Cannot proceed to the site content with this pop-up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![game2u1](https://user-images.githubusercontent.com/26442764/229371411-cd00f04c-da8e-4e09-bc91-56d431987377.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 99537
  cosmetic: 39550
  scriptlet: 17453
  html: 936
listset (total-discarded, last-updated): 
  added: 
    dpollock-0: 11349-470, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 34127-43, now
    ublock-badware: 6237-0, now
    ublock-privacy: 352-0, now
    ublock-abuse: 78-0, now
    ublock-unbreak: 1955-0, now
    easylist: 65254-772, now
    easyprivacy: 30767-1854, now
    urlhaus-1: 6925-0, now
    plowe-0: 3752-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 628 ms
  maxAssetCacheWait: 140 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    a-ads.com: 3
    googlesyndication.com: 2
    googletagmanager.com: 2
    wp.com: 2
```
</details>

**Comment by theinstantmatrix** [comment]
Dead domain: Seized by government
