### ISSUE TITLE
ww2-weapons.com: ads

### ISSUE THREAD

**Issue by Satv9** [uBlockOrigin/uAssets#17391]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ww2-weapons.com/`

### Category

ads

### Description

See screenshots section

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/74662787/229366726-ed79072b-91dc-49f0-80ad-78ed23a6c541.png)

Giant overlays...

![image](https://user-images.githubusercontent.com/74662787/229366818-b810620b-5056-4bd9-8447-a6896af0f78a.png)

ads on sidebar

![image](https://user-images.githubusercontent.com/74662787/229366863-fcf9c9f2-67b6-40a8-afe9-f0ce7b8e39d4.png)

and in-pages too
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 88413
  cosmetic: 39701
  scriptlet: 17475
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 65170-46, 3d.18h.8m
    easyprivacy: 30767-1176, 1h.56m
    plowe-0: 3751-935, 5d.18h.14m
    ublock-abuse: 78-0, 7d.2h.18m
    ublock-badware: 5485-114, 3d.18h.7m
    ublock-filters: 33096-93, 3d.18h.6m
    ublock-privacy: 295-2, 7d.2h.17m
    ublock-quick-fixes: 459-11, 17h.58m
    ublock-unbreak: 1944-42, 3d.18h.5m
    urlhaus-1: 7138-0, 17h.57m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 41391 ms (selfie)
  maxAssetCacheWait: 148 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    ww2-weapons.com: 4
    amazon-adsystem.com: 1
```
</details>

**Comment by mapx-** [comment]
report at [easylist repository](https://github.com/easylist/easylist/issues)

**Comment by mapx-** [comment]
@ryanbr
