### ISSUE TITLE
seznam.cz: breakage

### ISSUE THREAD

**Issue by zwij** [uBlockOrigin/uAssets#17390]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.seznam.cz/`

### Category

breakage

### Description

Email is missing both on pc and mobile. Had to uncheck uBlock filters to show again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Chromium: 111
filterset (summary): 
  network: 83271
  cosmetic: 72575
  scriptlet: 15977
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
    ublock-filters: null
  added: 
    adguard-generic: 69346-521, 10h.56m
    adguard-mobile: 8712-43, 10h.55m
    dpollock-0: 11349-85, now
  default: 
    user-filters: 8-0, never
    CZE-0: 737-0, 10h.50m
    easylist: 65167-1046, 10h.54m
    plowe-0: 3750-824, 9d.2h.16m
    ublock-abuse: 78-0, 10h.58m
    ublock-badware: 6080-325, 10h.53m
    ublock-privacy: 302-1, 10h.57m
    ublock-quick-fixes: 457-28, 10h.49m
    ublock-unbreak: 1945-55, 10h.51m
    urlhaus-1: 7112-0, 10h.48m
filterset (user): [array of 16 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 373 ms (selfie)
  maxAssetCacheWait: 153 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    seznam.cz: 2
    adform.net: 2
    adnxs.com: 2
    adsrvr.org: 1
    amazon-adsystem.com: 1
    bidr.io: 1
    bidtheatre.com: 1
    crwdcntrl.net: 1
    de17a.com: 1
    dotomi.com: 1
    doubleclick.net: 4
    everesttech.net: 1
    gemius.pl: 2
    loopme.me: 1
    mathtag.com: 1
    quantserve.com: 1
    simpli.fi: 1
    sitescout.com: 1
    stackadapt.com: 1
    turn.com: 1
    weborama.fr: 1
    yahoo.com: 1
```
</details>

**Comment by mapx-** [comment]
What exactly is missing ? provide screenshot indicating what's broken between with / without uBO enabled on that site and eventually the steps to get the breakage

**Comment by mapx-** [comment]
invalid:

```
removed: 
    easyprivacy: null
    ublock-filters: null

```

**Comment by zwij** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/8824584/229367582-52ac39a0-29d4-4f0e-8330-5f66d26d09ed.png)
![Screenshot_3](https://user-images.githubusercontent.com/8824584/229367585-70689b1d-8942-431f-a974-a75b2f551cd7.png)
hidden my emails in second screenshot. but whole section is missing when ublock filters is enabled. easyprivacy doesnt make difference.

**Comment by mapx-** [comment]
see above: you are not using uBO filters.

reset uBO , update all lists, do not touch the settings or lists.
