### ISSUE TITLE
www.sueddeutsche.de anti-adblock

### ISSUE THREAD

**Issue by mario98** [uBlockOrigin/uAssets#174]
The german newspaper website sueddeutsche.de (Sueddeutsche is one of the largest german newspapers) recently implemented an anti-adblock technique, locking out users with adblock enabled. uBO recently successfully cracked other anti-adblock techniques, like those used on the german newspaper BILD.de, therefore I wonder if you have any ideas on how to crack this one as well.
### URL(s) where the issue occurs

`http://www.sueddeutsche.de/`
### Describe the issue

When uBlock Origin is installed, the user will be redirected to `http://www.sueddeutsche.de/adblock` immediately after visiting `http://www.sueddeutsche.de/`, cannot read any articles.
### Screenshot

![Image of Issue](http://fs5.directupload.net/images/161024/rvoiee9h.png)
### Versions
- Browser/version: Firefox, but affects other as well I guess
- uBlock Origin version: 1.9.12
### Settings

I'm using "Easylist German" in addition to the default filter lists.
### Appendix

A german security blogger investigated how many tracking and advertisement scripts are included by Sueddeutsche, and the results are quite shocking: https://blog.fefe.de/?ts=a6f0d544 So disabling adblock is not a solution if you care for privacy.

**Comment by yoshimo** [comment]
Can you confirm that it doesn't appear if you disable cookies?

**Comment by gorhill** [comment]
`@@||sueddeutsche.de^$generichide` works here.

If you confirm it works, this should be submitted to EasyList Germany.

**Comment by mario98** [comment]
Works, but I noticed that uMatrix (all host files enabled) is then detected as the "ad-blocker".
But only if I use this filter rule, disabling cookies works even with uMatrix enabled. Sueddeutsche seems to check if a certain script can be executed. I found out that scrip.ioam.de is responsible for this. (If you enable this script in uMatrix, it's not detected any more.)

**Comment by yoshimo** [comment]
how about 

`www.sueddeutsche.de##script:contains(AdBlock)`
instead?

http://pastebin.com/dPXJsrnV has the deminified source of http://media-cdn.sueddeutsche.de/globalassets/js/sde-header-desktop.js?36079097.

maybe there is a nicer solution as well

**Comment by gorhill** [comment]
Should avoid using `script:contains`, ability to block execution of specific inline script tags will be removed in Firefox: <https://bugzilla.mozilla.org/show_bug.cgi?id=1286822>.

**Comment by mario98** [comment]
That's bad news. I use this `script:contains` a lot for my private filter rules, because nearly half of the german websites use this stupid AdDefend now. `script:contains(uabInject)` or similar was the only thing that has worked... So sad that Google has so much power that they can just eliminate a web standard...

**Comment by gorhill** [comment]
Try `...##script:inject(uabinject-defuser.js)`. I stopped creating `...##script:contains(...)` fitlers, now I favor what works on all browsers.

**Comment by yoshimo** [comment]
as far as i can see there is no uab function in that file so the ad defend thing won't help.

**Comment by gorhill** [comment]
I was just answering to

> I use this script:contains a lot for my private filter rules, because nearly half of the german websites use this stupid AdDefend now. script:contains(uabInject) or similar was the only thing that has worked

**Comment by TonyTough** [comment]
They changed the Anti-Adblock-script:
Disabling Cookies no longer works.

`www.sueddeutsche.de##script:inject(uabinject-defuser.js)`
no longer works.

`www.sueddeutsche.de##script:contains(AdBlock)`
still works.

**Comment by Ghosty141** [comment]
Actually it doesn't work for me anymore, Safari, uBlock Origin 0.9.5.2

**Comment by okiehsch** [comment]
**ublock 0.9.5.2**, you are not using [uBlock Origin](https://github.com/gorhill/uBlock) , you are using [uBlock](https://github.com/chrisaljoudi/uBlock).

**Comment by Ghosty141** [comment]
Thanks! When I first installed uBlock there was no safari version out yet, thanks for pointing me to it!

**Comment by Raavizz** [comment]
> @mario98 : stupid AdDefend

Stop your drama / insulting / bad words.
