### ISSUE TITLE
lrepacks.net: ads

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#17403]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

annoying ads on the bottom left corner

### URL(s) where the issue occurs.

`https://lrepacks.net/repaki-multimedia-programm/189-format-factory-amp-portable.html`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24896778/229504784-0fbe175b-03af-44a1-804b-0069b53ace40.png)

### uBO version

1.48.4

### Browser name and version

Cent Browser Version 5.0.1002.295 (Official Build) (64-bit) (Portable) (Chromium 102.0.5005.167)

### Settings

n/a

**Comment by dportvine** [comment]
RU AdList enabled? I don't see any ads.

**Comment by patrickdrd** [comment]
no, I don't have RU AdList, could it be due to google translate?

**Comment by dportvine** [comment]
I only see these ads if I turn off uBO, yes, you are don't need RU AdList for this site

**Comment by mapx-** [comment]
russian site so you have to keep RUAdList enabled
