### ISSUE TITLE
n.fcd.su: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#17400]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://n.fcd.su/PpR/2t7to`

### Category

ads

### Description

https://user-images.githubusercontent.com/19517680/229437130-394a9763-83d8-4507-8d96-a7bb25be55aa.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium Mobile: 111
filterset (summary): 
  network: 99949
  cosmetic: 126701
  scriptlet: 23722
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7478-8, 3d.7h.41m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 77-4, 3d.7h.23m
    IDN-0: 5473-347, 3d.7h.43m
    fanboy-annoyance: 82292-381, 6d.16h.29m
    fanboy-cookiemonster: 46350-46350, 6d.16h.28m
    ublock-annoyances: 4940-87, 3d.7h.20m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8652-18, 3d.7h.42m
    easylist: 64659-73, 3d.7h.19m
    easyprivacy: 30741-1185, 3d.7h.18m
    ublock-abuse: 78-0, 3d.7h.22m
    ublock-badware: 5471-116, 3d.7h.16m
    ublock-filters: 33346-274, 3d.7h.15m
    ublock-privacy: 299-8, 3d.7h.14m
    ublock-quick-fixes: 471-13, 22h.36m
    ublock-unbreak: 1949-49, 3d.7h.13m
    urlhaus-1: 7112-0, 22h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  largeMediaSize: 200
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 13889 ms (selfie)
  maxAssetCacheWait: 5257 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    nextpsh.top: 1
    yandex.ru: 2
```
</details>

**Comment by krystian3w** [comment]
Maybe this works to skip modal without clicks: https://github.com/uBlockOrigin/uAssets/pull/16764/files

**Comment by mapx-** [comment]
No steps, no explanation on how to reproduce your "issue"
