### ISSUE TITLE
darksoftware.net: detection

### ISSUE THREAD

**Issue by Jabahhh** [uBlockOrigin/uAssets#17408]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://darksoftware.net/forums/switch-nsp-xci-roms.50/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 90270
  cosmetic: 43099
  scriptlet: 17746
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 13h.30m
  default: 
    user-filters: 74-14, never
    easylist: 65152-46, 3d.10h.6m
    easyprivacy: 30754-1175, 1d.14h.10m
    plowe-0: 3753-934, 10d.8h.17m
    spa-1: 5154-69, 6h.29m
    ublock-abuse: 78-0, 5d.10h.18m
    ublock-badware: 6217-114, 1d.1h.37m
    ublock-filters: 33163-124, 1d.1h.38m
    ublock-privacy: 295-2, 5d.10h.19m
    ublock-quick-fixes: 381-18, 13h.28m
    ublock-unbreak: 1944-44, 6h.30m
    urlhaus-1: 6870-0, 13h.29m
filterset (user): [array of 74 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 177 ms (selfie)
  maxAssetCacheWait: 55 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    add.pics: 1
    d3hv9xfqzxy46o.cloudfront.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by Procyon-b** [comment]
From here: https://www.reddit.com/r/uBlockOrigin/comments/1243uqi/adblock_detected_on_darksoftwarenet/
does this work?
```
darksoftware.net##+js(set, xv_ad_block, 0)
```

**Comment by Procyon-b** [comment]
@mapx-
the filter doesn't work anymore.
This one does
```
darksoftware.net##+js(set, xv_read_ad_0, noopFunc)
```

**Comment by mapx-** [comment]
It was updated yesyerday and it seems still working

`darksoftware.net##+js(acs, XV)`
