### ISSUE TITLE
broadwayworld.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1740]
URL(s) where the issue occurs

`https://www.broadwayworld.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.16

Settings

Default

**Comment by mapx-** [comment]
I cannot reproduce it consistently, so could be a race condition for the admiral crap, so I chose to block the external scripts for such trick

**Comment by zaphodbeebblebrox** [comment]
Doubleclick Ads @mapx-
