### ISSUE TITLE
techedubyte.com: detection

### ISSUE THREAD

**Issue by nagoffy** [uBlockOrigin/uAssets#17414]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.techedubyte.com/2023/03/chatgpt-free-premium-account-cookies.html`

### Category

detection

### Description

Ublock origine detected on website
Thank you for your help

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 89146
  cosmetic: 41064
  scriptlet: 20721
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4912-6, now
  default: 
    user-filters: 61-9, never
    easylist: 65185-46, now
    easyprivacy: 30764-1177, now
    plowe-0: 3752-936, now
    ublock-abuse: 78-0, now
    ublock-badware: 6244-124, now
    ublock-filters: 33263-110, now
    ublock-privacy: 302-2, now
    ublock-quick-fixes: 375-25, now
    ublock-unbreak: 1947-43, now
    urlhaus-1: 6704-0, now
filterset (user): [array of 59 redacted]
trustedset: 
  added: [array of 15 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 968 ms (selfie)
  maxAssetCacheWait: 234 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    doubleclick.net: 4
    doubleverify.com: 1
    flashtalking.com: 4
    google.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    tribalfusion.com: 1
    zemanta.com: 1
```
</details>

**Comment by punisher018** [comment]
Adblock detection. 

<details><summary>Details</summary>
<p>

![Image](https://github.com/user-attachments/assets/f3bc07e0-a848-4f76-8f80-e873e7706cc8)

</p>
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/27472
