### ISSUE TITLE
theralphretort.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1741]
URL(s) where the issue occurs

`https://theralphretort.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.16

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
Soft Anti-Adblock, but returns after every pageload @mapx- 
`@@||theralphretort.com^$generichide`

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by zaphodbeebblebrox** [comment]
I get ![this anti-adblock.](https://user-images.githubusercontent.com/22801430/38528999-629239ee-3c30-11e8-8818-ae1794dddd0d.png)

**Comment by okiehsch** [comment]
I get exactly the same, **if** I disable the filter
`theralphretort.com##script:inject(abort-on-property-write.js, adBlockDetected)`

**Comment by zaphodbeebblebrox** [comment]
Sorry, I'm dumb, I forgot that I had annoyances disabled.

**Comment by okiehsch** [comment]
Actually, I am dumb. 
You are right the message returns after every pageload, so I will move the fix from annoyances to
`uBO-filters`.
