### ISSUE TITLE
Powerapps fields blocking 

### ISSUE THREAD

**Issue by Gopi1991R** [uBlockOrigin/uAssets#17418]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ublock enabled Firefox is not working, which  is not allow me to enter the input values to the powerapps website 

### A specific URL where the issue occurs.

Everywhere

### Steps to Reproduce

1. create a power apps and deploy it on environment then at U block enabled firefox is not working 

### Expected behavior

It should allow the input values to the fields

### Actual behavior

doesn't allow me to enter input values

### uBO version

latest 

### Browser name and version

Mozilla firefox

### Operating System and version

Windows 10 and 11 latest

**Comment by mapx-** [comment]
> powerapps website

I see no useful link

Do we need an account ?
Provide all the steps to reproduce your issue.

Go to that site, then go into uBO dashboard, support tab, copy and paste here `Troubleshooting Information`

**Comment by peace2000** [comment]
Do you mean Microsoft Powerapps (Azure environment)?

If this is what was meant, I can set values, at least on Power BI:

![image](https://user-images.githubusercontent.com/17256841/230011821-4771f3b8-ba8c-4967-a4f4-c9847a46444d.png)

`https://app.powerbi.com/groups/me/quickcreate`

IF this is what you meant?

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2699

**Comment by gorhill** [comment]
Requires _"work or school account"_:

![a](https://github.com/uBlockOrigin/uAssets/assets/585534/ebffa531-2ba3-4730-8aef-7cb152ac21c1)

**Comment by mapx-** [comment]
@Gopi1991R you should export your test case and then I could import it to test your claim.

**Comment by Gopi1991R** [comment]
Hi team,
               Please find the app export file App A and App B. you should import both and start with A
[A screenshot of a computer  Description automatically generated]

Replace the app B link where the arrow point navigates!
[A screenshot of a computer  Description automatically generated]

You can find the link over here,

***@***.***
[A screenshot of a computer  Description automatically generated with medium confidence]

Thanks
Gopinath R

**Comment by mapx-** [comment]
@Gopi1991R 

Do not reply here using your email. 
I see no useful link. Come here on github and try again.

**Comment by Gopi1991R** [comment]
Share the mail ID to provide guest access.

**Comment by mapx-** [comment]
I asked you to export all the items to reproduce the issue and then provide a download link.

**Comment by Gopi1991R** [comment]
Please find the attachment , to reproduce the issue !

**Comment by mapx-** [comment]
@Gopi1991R 

I already told you: **do not use your email to reply here**.
`There is no attachment.`

**Come here on github and post here a link from where I can download your test case.**

**Comment by Gopi1991R** [comment]
[U block origin blocks power apps editing option · Issue #2699 · uBlockOrigin_uBlock-issues.pdf](https://github.com/uBlockOrigin/uAssets/files/11814740/U.block.origin.blocks.power.apps.editing.option.Issue.2699.uBlockOrigin_uBlock-issues.pdf)

Please find the attachment for issue recreation

**Comment by Gopi1991R** [comment]
[AppA_20230621055940 (1).zip](https://github.com/uBlockOrigin/uAssets/files/11814748/AppA_20230621055940.1.zip)
For App A export file

**Comment by Gopi1991R** [comment]
App B export file form powerapps

**Comment by Gopi1991R** [comment]
[AppB_20230621060024 (1).zip](https://github.com/uBlockOrigin/uAssets/files/11814769/AppB_20230621060024.1.zip)

**Comment by mapx-** [comment]
test these filters

```
@@||browser.pipe.aria.microsoft.com/Collector/$xhr,domain=powerapps.com
@@||events.data.microsoft.com^$xhr,domain=powerapps.com
```

However I cannot test completely:

`Selected user account does not exist in tenant 'Ascentec Engineering LLC`

**Comment by Gopi1991R** [comment]
These are filters not worked , please investigate this.

You can test with the link : https://apps.powerapps.com/play/e/default-1e1055a5-9ed4-4a2f-9eed-c38d74562c71/a/688535dc-7bdd-451b-a61f-05733c77cd75?tenantId=1e1055a5-9ed4-4a2f-9eed-c38d74562c71

Temp credentials
***@***.******@***.***>
Password: Welcome123

**Comment by mapx-** [comment]
- nothing to do, still telling my user is not in ascentec.
- well, you have to investigate on your side:

open the uBO logger
see what is blocked
whitelist 1 by 1 the requests (especially xhr, script ones) and see what's working
report back if you find the fix

**Comment by mapx-** [comment]
I created 2 apps A, B on my end, tested in preview mode, all fine here: I need no exception.
So, it seems it's sometyhing wrong on your end.

**Comment by Gopi1991R** [comment]
Could you please show the network options at the browser?

Here few of blocked by u-Block Origin while I try to second app from first app, can you track the get methods.
***@***.***

***@***.***

***@***.***

Thanks

**Comment by Gopi1991R** [comment]
Hi,
      You should check only at Firefox browser !

Thanks.

From: Gopinath R ***@***.***>
Sent: Wednesday, June 21, 2023 3:35 PM
To: uBlockOrigin/uAssets ***@***.***>; uBlockOrigin/uAssets ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [uBlockOrigin/uAssets] Powerapps fields blocking (Issue #17418)

Could you please show the network options at the browser?

Here few of blocked by u-Block Origin while I try to second app from first app, can you track the get methods.
***@***.***

***@***.***

***@***.***

Thanks

**Comment by Gopi1991R** [comment]
Also, it will work in preview mode or play mode, but actual errors occur only in the published version, so you should test in the published version of Mozilla Firefox.

Thanks
From: Gopinath R ***@***.***>
Sent: Wednesday, June 21, 2023 3:37 PM
To: Gopinath R ***@***.***>; uBlockOrigin/uAssets ***@***.***>; uBlockOrigin/uAssets ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [uBlockOrigin/uAssets] Powerapps fields blocking (Issue #17418)

Hi,
      You should check only at Firefox browser !

Thanks.

From: Gopinath R ***@***.******@***.***>>
Sent: Wednesday, June 21, 2023 3:35 PM
To: uBlockOrigin/uAssets ***@***.******@***.***>>; uBlockOrigin/uAssets ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [uBlockOrigin/uAssets] Powerapps fields blocking (Issue #17418)

Could you please show the network options at the browser?

Here few of blocked by u-Block Origin while I try to second app from first app, can you track the get methods.
***@***.***

***@***.***

***@***.***

Thanks

**Comment by Gopi1991R** [comment]
okay Sure.. Will do the same

**Comment by Gopi1991R** [comment]
How to unblock this path and screenshots for what I tried
![Picture1](https://github.com/uBlockOrigin/uAssets/assets/129826408/348afa1d-44e2-4d12-8af9-21f7e72f4b16)
![Picture2](https://github.com/uBlockOrigin/uAssets/assets/129826408/f59a8119-62ad-4e0d-bc8e-a4ef2e37baea)

**Comment by Gopi1991R** [comment]
please share your recommendations for this, Thank you

**Comment by Gopi1991R** [comment]
These images can be seen clearly.
![2023-06-21_16-07-35](https://github.com/uBlockOrigin/uAssets/assets/129826408/42b92ba5-0301-4223-9a08-82fcb729a72c)
![2023-06-21_16-06-37](https://github.com/uBlockOrigin/uAssets/assets/129826408/e9011736-54ca-4ab1-a0b5-236266528399)
![2023-06-21_16-37-00](https://github.com/uBlockOrigin/uAssets/assets/129826408/3e4bf61b-15fa-4fd3-bac9-60a2aedab1c3)

**Comment by Gopi1991R** [comment]
how to whitelist the above blocks.

**Comment by mapx-** [comment]
- remove what you put in `trusted sites`

add & test:

```
@@||browser.pipe.aria.microsoft.com/Collector/$xhr,domain=powerapps.com
@@||events.data.microsoft.com^$xhr,domain=powerapps.com
@@||measure.office.com^$xhr,domain=powerapps.com
```

**Comment by Gopi1991R** [comment]
![2023-06-21_17-12-50](https://github.com/uBlockOrigin/uAssets/assets/129826408/42d5d212-4ac9-4f84-b6ec-32ffe5a0b852)
you can see the line 2nd and 3rd directory not allow without "/". So I changed to
@@||events.data.microsoft.com^$xhr,domain=powerapps.com/*
@@||measure.office.com^$xhr,domain=powerapps.com/*
is that right?
Even after adding the three directories to the path, It still isn't working!

**Comment by Gopi1991R** [comment]
![2023-06-21_17-19-19](https://github.com/uBlockOrigin/uAssets/assets/129826408/4c6f2b43-9bc9-405f-9d6e-94f090d5c6e8)
![2023-06-21_17-19-07](https://github.com/uBlockOrigin/uAssets/assets/129826408/bebf8404-d107-48c3-b1ba-98d125f9426c)
![2023-06-21_17-18-52](https://github.com/uBlockOrigin/uAssets/assets/129826408/fb8a8311-760b-44c5-9828-872ac1b66c61)

please find the logs!

**Comment by mapx-** [comment]
@Gopi1991R 

**I said: remove all those lines from trusted sites** => remove lines 9,10,11

**You have to add in my filters above in "my filters"** tab

**Comment by Gopi1991R** [comment]
![2023-06-21_17-35-19](https://github.com/uBlockOrigin/uAssets/assets/129826408/8bc73fe0-c19a-4c1b-9966-f55e21a62f1a)
![2023-06-21_17-31-42](https://github.com/uBlockOrigin/uAssets/assets/129826408/7b8d6ee6-4f04-40bf-be2e-c709f71e1d82)

It is done even though the editing option was not enabled at first page load.

**Comment by mapx-** [comment]
TBH I cannot trust anymore in your feedback.

Try "translating" again:

> It is done even though the editing option was not enabled at first page load.

Did you test disabling completely uBO ? (from addons/ extension page)
Maybe it's something else (other addon / extension) blocking whatever functionality.

**Comment by Gopi1991R** [comment]
![2023-06-21_17-41-16](https://github.com/uBlockOrigin/uAssets/assets/129826408/a971f43d-8d3e-42e8-8f08-24e2867e07d1)

This log is found once I switch from one page to another and back to the same page.

**Comment by Gopi1991R** [comment]
Nope ! What I tried to say is, I added filters, which you exactly recommended, but the input field is not working on the second page. Let me share the video

**Comment by gorhill** [comment]
As per your screenshot of logger output, uBO is blocking nothing, so it can't be the cause of your issue.

**Comment by Gopi1991R** [comment]
https://github.com/uBlockOrigin/uAssets/assets/129826408/9fda1366-823e-43c0-836c-8a9ef747fa17

**Comment by Gopi1991R** [comment]
you can see in the video, after I change web page and return to input page it is starts working!

**Comment by Gopi1991R** [comment]
let me share new screen record

**Comment by Gopi1991R** [comment]
Nope!, all cleared, see the new one
https://github.com/uBlockOrigin/uAssets/assets/129826408/10d0847d-c887-435b-ae59-8589bcbcfa55

**Comment by Gopi1991R** [comment]
![2023-06-21_18-02-51](https://github.com/uBlockOrigin/uAssets/assets/129826408/96c4915d-f5a1-4a65-a527-4a55612da4d6)

**Comment by gorhill** [comment]
With these filters, is the logger still showing anything being blocked (red lines) when you load the page in a new tab?

**Comment by Gopi1991R** [comment]
![2023-06-21_18-12-48](https://github.com/uBlockOrigin/uAssets/assets/129826408/77b82920-f559-43ed-be90-8a5fae99712f)
There is no red lines at log at new tab.

**Comment by Gopi1991R** [comment]
There are no red lines in the log of the new tab.

**Comment by mapx-** [comment]
Did you follow these steps too ?

**Did you test disabling completely uBO ? (from addons/ extension page)
Maybe it's something else (other addon / extension) blocking whatever functionality.**

**Comment by Gopi1991R** [comment]
![2023-06-21_18-17-28](https://github.com/uBlockOrigin/uAssets/assets/129826408/b88c46cf-0e1c-4db2-82b6-e20164e7f6ed)

**Comment by Gopi1991R** [comment]
> Did you follow these steps too ?
> 
> **Did you test disabling completely uBO ? (from addons/ extension page) Maybe it's something else (other addon / extension) blocking whatever functionality.**

Yes, When I disabled and completely reinstall without addon. IT is working.. , This is what I tried from Microsoft support video call.

**Comment by mapx-** [comment]
Do you have this issue only in firefox ? did you test in chrome ?

if you add also this filter, does it help ?

`@@||powerapps.com^$cname`
