### ISSUE TITLE
instagram.com: ads

### ISSUE THREAD

**Issue by sfrigieri** [uBlockOrigin/uAssets#17415]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

From today, April 4, i'm seeing ads in between instagram stories. 

### URL(s) where the issue occurs.

`https://www.instagram.com/stories`

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/21245102/229683057-b5f5076c-db91-4d3b-ad08-df921657ef01.PNG)

### uBO version

1.48.2

### Browser name and version

Firefox: 106

### Settings

-

**Comment by mapx-** [comment]
a specific link ?

`https://www.instagram.com/stories` => `Sorry, this page isn't available.`

**Comment by sfrigieri** [comment]
> a specific link ?
> 
> `https://www.instagram.com/stories` => `Sorry, this page isn't available.`

Sorry. I didn't provide any specific link / story link because there's a new link for every story shown. The ads appear in a story between the normal stories.
Here are several links from my history, the ones in bold are from ads:

https://www.instagram.com/stories/manuarce98/3073070011419211593/
https://www.instagram.com/stories/llamameantiguo/3073131006398884605/
**_https://www.instagram.com/stories/sergiochala/3071082715144125620/_**
https://www.instagram.com/stories/shauntrack/3073145677119199045/
....
**_https://www.instagram.com/stories/lasmejorestarjetasutua1/3059206801721309633/_**
https://www.instagram.com/stories/diego/3073070641050561103/

**Comment by mapx-** [comment]
I'm not able to reproduce sponsored stuff using those links or some random stories around.

**Comment by sfrigieri** [comment]
> I'm not able to reproduce sponsored stuff using those links or some random stories around.

I think uBlock isn't filtering those ads stories like (https://www.instagram.com/stories/sergiochala/3071082715144125620/) because of what you mentioned: the ads stories are showing like normal stories, not sponsored. But I'm not following those accounts so I shouldn't see their stories... Instagram found a way to avoid filtering.

**Comment by sn-o-w** [comment]
@sfrigieri 

You can use something like this:

**`instagram.com##.x1fhwpqd.x132q4wb.xh93fs4:upward(8)`**

The downside is that you will see the empty space where it used to be the sponsored ads. I also tried to add `:remove()` at the end, but it will break the Stories page after seeing a few stories.

At least you won't see ads if you use the above filter I created. 😊

Perhaps others have better ideas. 🤔
