### ISSUE TITLE
mastercomfig.com: ads

### ISSUE THREAD

**Issue by hippopotamusgoldfish** [uBlockOrigin/uAssets#17411]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mastercomfig.com/`
`https://docs.mastercomfig.com/`
`https://mastercomfig.com/huds/1/`
`https://mastercomfig.com/app/`

### Category

ads

### Description

CSGO trading ad plastered on many pages, there's probably more I forgot to include. Surprisingly, it's unpickable by the element picker, except on the documentation.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 88907
  cosmetic: 39627
  scriptlet: 17508
  html: 939
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34144-57, now
    ublock-badware: 6242-10, now
    ublock-privacy: 352-0, now
    ublock-abuse: 78-0, now
    ublock-unbreak: 1958-2, now
    ublock-quick-fixes: 376-5, now
    easylist: 65159-605, now
    easyprivacy: 30764-1769, now
    urlhaus-1: 6786-0, now
    plowe-0: 3752-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3016 ms
  maxAssetCacheWait: 83 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    cloudflareinsights.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
mastercomfig.com##.md-typeset[style^="background:"]
mastercomfig.com##.text-start[style^="background:"]
mastercomfig.com##a[href^="https://tradeit.gg/"]
```

@ryanbr
