### ISSUE TITLE
demotywatory.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1742]
![2018-03-19-menedzer zadan](https://user-images.githubusercontent.com/5884000/37612906-cfe9c740-2ba6-11e8-8135-bfcb9d884781.png)

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

uBO 1.15.12
Nano Defender 13.46
Chrome 65.0.3325.162

</details>

**Comment by mapx-** [comment]
alltube or demotywatory ? example for the second ?

The mining stuff is already blocked on alltube for the link you posted above

**Comment by KonoromiHimaries** [comment]
exactly `demotywatory.pl` in main site

**Comment by mapx-** [comment]
I get no mining activity on that site

**Comment by KonoromiHimaries** [comment]
why do I have increased CPU usage when I enter these websites?

**Comment by mapx-** [comment]
alltube has such crap (blocked) but not `demotywatory.pl`

if you add this filter (only to test) 
`||connect.facebook.net`

probably the CPU will be less used

**Comment by KonoromiHimaries** [comment]
still nothing
![2018-03-19-greenshot](https://user-images.githubusercontent.com/5884000/37614216-70f05d7c-2baa-11e8-9c11-be0affe23f18.png)

**Comment by KonoromiHimaries** [comment]
@mapx- why was it closed?

**Comment by zaphodbeebblebrox** [comment]
`demotywatory.pl##script:inject(abort-current-inline-script.js,MMG)` stops the really high cpu usage for me.

**Comment by KonoromiHimaries** [comment]
@zaphodbeebblebrox this rule not resolved problem in related pages

example.
`http://piekielni.pl/`

**Comment by mapx-** [comment]
see if changes something:
`piekielni.pl##script:inject(noeval.js)`

**Comment by KonoromiHimaries** [comment]
@mapx- still nothing
