### ISSUE TITLE
bajeczki.org: breakage

### ISSUE THREAD

**Issue by Paszu94** [uBlockOrigin/uAssets#17428]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bajeczki.org/pelnometrazowe/thor-milosc-i-grom-2022-plsub/`

### Category

breakage

### Description

videos not loading when ublock runing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 90148
  cosmetic: 47220
  scriptlet: 17778
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-0, never
    POL-0: 7884-8, 23h.44m
    POL-2: 1275-13, 3h.8m
    easylist: 65097-73, 16h.40m
    easyprivacy: 30767-1176, 3h.9m
    plowe-0: 3751-944, 4d.22h.58m
    ublock-abuse: 78-0, 5d.21h.18m
    ublock-badware: 6233-114, 16h.36m
    ublock-filters: 33278-132, 16h.38m
    ublock-privacy: 294-2, 6d.1h.37m
    ublock-quick-fixes: 462-25, 23h.42m
    ublock-unbreak: 1944-43, 16h.37m
    urlhaus-1: 6786-0, 23h.43m
filterset (user): [array of 9 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 162 ms (selfie)
  maxAssetCacheWait: 66 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    a-ads.com: 3
    acdcdn.com: 1
    adform.net: 1
    aed5586e71.com: 1
    cloudflareinsights.com: 1
    exs.pl: 2
    googletagmanager.com: 1
    statsforads.com: 1
    wpadmngr.com: 1
```
</details>

**Comment by gorhill** [comment]
I don't see a video with uBO disabled.

**Comment by mapx-** [comment]
yeah, no video, tested using a polish ip too

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
