### ISSUE TITLE
allocine.fr: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#17422]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.allocine.fr/video/player_gen_cmedia=19543909&cfilm=15532.html`

### Category

breakage

### Description

video don't play.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/229730372-79aa7296-f987-4cd6-a650-f91e7024508f.png)

`https://www.allocine.fr/video/player_gen_cmedia=19543909&cfilm=15532.html`

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 125183
  cosmetic: 69366
  scriptlet: 18883
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39566-166, 4m
  default: 
    user-filters: 0-0, never
    FRA-0: 29149-35, 4m
    easylist: 65110-409, 4m
    easyprivacy: 30772-1578, 4m
    plowe-0: 3752-965, 4m
    ublock-abuse: 78-2, 4m
    ublock-badware: 6244-144, 4m
    ublock-filters: 33263-217, 4m
    ublock-privacy: 302-2, 4m
    ublock-quick-fixes: 375-25, 4m
    ublock-unbreak: 1947-47, 4m
    urlhaus-1: 6704-0, 4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 545 ms (selfie)
  maxAssetCacheWait: 90 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    allocine.fr: 1
    disqus.com: 4
    dm-event.net: 1
    webedia-group.com: 2
```
</details>

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/labels/geo%20specific?

**Comment by mapx-** [comment]
- no issue on my end.
- try updating again all the lists using shift button
(Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by gorhill** [comment]
No issue on my side either. I get a lot more stuff blocked than OP's troubleshooting information show. Possibly another extension is interfering.
