### ISSUE TITLE
us7p.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#17429]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.us7p.com/download-rehub-v18-0-marketplace/`

### Category

detection

### Description

anti adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 113
filterset (summary): 
  network: 96978
  cosmetic: 89075
  scriptlet: 23643
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7595-7, 6h.33m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 77-4, 6h.33m
    IDN-0: 5473-347, 6h.33m
    fanboy-cookiemonster: 46489-200, 6h.33m
    ublock-annoyances: 4913-55, 6h.32m
  default: 
    user-filters: 32-1, never
    easylist: 65087-56, 6h.33m
    easyprivacy: 30773-1179, 6h.33m
    plowe-0: 3752-936, 6h.32m
    ublock-abuse: 78-0, 6h.32m
    ublock-badware: 6254-126, 6h.32m
    ublock-filters: 33263-254, 6h.32m
    ublock-privacy: 302-2, 6h.32m
    ublock-quick-fixes: 375-25, 6h.32m
    ublock-unbreak: 1947-45, 6h.32m
    urlhaus-1: 6704-0, 6h.32m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 37 redacted]
  removed: 
    chrome-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6427 ms (selfie)
  maxAssetCacheWait: 912 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google.com: 1
    googlesyndication.com: 2
    googletagmanager.com: 1
    onesignal.com: 1
    youtube.com: 1
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce when using default settings/lists. Where is the "anti adblock"? How does it look? Did you _really_ try with default settings.lists as demanded in _Prerequisites_ steps?

**Comment by okiehsch** [comment]
I can reproduce with default setup.

**Comment by gorhill** [comment]
After updating the lists I can reproduce when I disable your fix, I should have updated the lists first.
