### ISSUE TITLE
adshnk.com: breakage

### ISSUE THREAD

**Issue by Ruzz23** [uBlockOrigin/uAssets#17421]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://adshnk.com/sBKi25`

### Category

Url shorter is blocked and does not advance with active Ublock.

### Description

The blocker of this page has a box with a 2 -stage button, it appears to continue 1/2 and then continue 2/2 should appear, but it is blocked in 1/2 and I cannot advance, disabled the Ublock is seen that after pressing 1/2 is generated an advertising window with a several second accountant, my browser is Chrome and I can't jump this step with the Ublock (continue 1/2). Advertising is practically infinitive and you can spend more than 10min jumping without filters. When I did the Firefox test, it detects the Ublock and with no filter of this page I can avoid detection in that browser ... Therefore I turn to a solution for Cchrome where I can avoid detection with the Ublock activated.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

![Capture001](https://user-images.githubusercontent.com/123111723/229726073-dd69c504-a384-46c7-985b-415333c378fa.JPG)

![Capture002](https://user-images.githubusercontent.com/123111723/229726078-88ce1b83-113e-461d-867a-a051b99b8c4f.JPG)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 96
filterset (summary): 
  network: 88744
  cosmetic: 39870
  scriptlet: 17444
  html: 0

</details>

**Comment by stephenhawk8054** [comment]
Can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and copy your `Troubleshooting Information` to here?

**Comment by mapx-** [comment]
however, needing

```
||search.bergfried.tech^$removeparam
search.bergfried.tech##+js(window-close-if, /^/)
```

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Yuki2718** [comment]
`||search.bergfried.tech^$removeparam` breaks ad search on (nsfw) `https://www.hotpornfile.org/tushy-22-06-26-kenzie-anne-xxx-1080p-mp4-nbq/749288` when you click Download => Get links. Not sure how much it matters thought, as you can download if refreshed page after that.
