### ISSUE TITLE
porn.es [NSFW][ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1743]
URL(s) where the issue occurs

`https://porn.es/videos/9052/una-chica-muy-excitada-acariciandose-en-su-cama.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.16

Settings

Default

**Comment by KiLL4FuNK** [comment]
pause video

**Comment by mapx-** [comment]
add
`||adn.porn.es^`

**Comment by SMed79** [comment]
add also
```
||porn.es/webcams/
||plxnt.com^$third-party
||plxnt.com^$popup,third-party
```
@diaux fyi. 

@ryanbr [#p104981](https://forums.lanik.us/viewtopic.php?f=62&t=33316&hilit=plxnt.com#p104981)
