### ISSUE TITLE
msn.com: ads

### ISSUE THREAD

**Issue by MandiYang** [uBlockOrigin/uAssets#17438]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.msn.com/sv-se/nyheter/other/%C3%A5talet-mot-donald-trump-34-fall-av-bokf%C3%B6ringsbrott/ar-AA19tHCa`

### Category

ads

### Description

Leftovers of ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/64307609/230011094-253efe49-e180-442e-a7cf-ce4c73806cd4.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 90927
  cosmetic: 43073
  scriptlet: 18669
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1912-0, 1m
  default: 
    user-filters: 0-0, never
    SWE-1: 4371-0, 2m
    easylist: 65095-57, 2m
    easyprivacy: 30782-1189, 2m
    plowe-0: 3753-938, 1m
    ublock-abuse: 78-0, 1m
    ublock-badware: 6293-124, 1m
    ublock-filters: 33368-107, 1m
    ublock-privacy: 302-3, 1m
    ublock-quick-fixes: 471-134, 1m
    ublock-unbreak: 1947-42, 1m
    urlhaus-1: 7070-0, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 782 ms (selfie)
  maxAssetCacheWait: 330 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    msn.com: 20
    adnxs.com: 3
    azure.com: 2
    btloader.com: 1
    civicscience.com: 1
    outbrain.com: 1
    scorecardresearch.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
msn.com##[class^="articlePage_eoabContent"]
```

@ryanbr
