### ISSUE TITLE
xmedia-recode.de: ads

### ISSUE THREAD

**Issue by MrDoZo** [uBlockOrigin/uAssets#17437]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.xmedia-recode.de/download_64bit.php`

### Category

ads

### Description

check 24 ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="865" alt="image" src="https://user-images.githubusercontent.com/42253558/229997341-4eb81416-5622-4ff8-b679-54df22073add.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 91440
  cosmetic: 44111
  scriptlet: 17569
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-0, never
    DEU-0: 6707-0, 1h
    easylist: 65160-52, 1d.9h.25m
    easyprivacy: 30767-1186, 1d.9h.24m
    plowe-0: 3752-937, 1d.9h.28m
    ublock-abuse: 78-0, 1d.9h.27m
    ublock-badware: 6238-124, 1d.9h.23m
    ublock-filters: 33278-111, 1d.9h.22m
    ublock-privacy: 302-2, 1d.9h.26m
    ublock-quick-fixes: 471-16, 59m
    ublock-unbreak: 1945-43, 1d.9h.21m
    urlhaus-1: 7070-0, 58m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 271 ms (selfie)
  maxAssetCacheWait: 54 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    amazon-adsystem.com: 2
    check24.net: 1
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
xmedia-recode.de###top_google_ads
xmedia-recode.de##.werbung_970
xmedia-recode.de##.box_banner-container
```

and report the issue ar german repository to be added to their list
https://github.com/easylist/easylistgermany/issues

**Comment by stephenhawk8054** [comment]
It has English version, so maybe in EL?

`https://www.xmedia-recode.de/en/`

**Comment by mapx-** [comment]
maybe .. @ryanbr
