### ISSUE TITLE
cardinalcommerce.com: breakage

### ISSUE THREAD

**Issue by saffad** [uBlockOrigin/uAssets#17431]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ublock origin was blocking Mastercard 3D Secure from working as expected. I confirmed this by turning off the extension and it worked. I looked at the logger and found that it was blocking cardinalcommerce.com and stripe.com I had set a rule to allow:  

`@@||authentication.cardinalcommerce.com/Content/dist/js/jsnlog.js$script,domain=authentication.cardinalcommerce.com `

`@@||r.stripe.com/0$xhr,domain=js.stripe.com`

### URL(s) where the issue occurs.

`cardinalcommerce.com`

### uBO version

1.48.0

### Browser name and version

Arc Version 0.96.0 (38004) Chromium Engine Version 111.0.5563.146

### Settings

[my-ublock-backup_2023-04-04_17.40.20.txt](https://github.com/uBlockOrigin/uAssets/files/11150879/my-ublock-backup_2023-04-04_17.40.20.txt)

**Comment by gorhill** [comment]
These filters can be rewritten more simply:

    @@||authentication.cardinalcommerce.com^$1p,script
    @@||r.stripe.com^$1p,xhr

**Comment by ryanbr** [comment]
stripe.com fix unlikely needed.

**Comment by mapx-** [comment]
@saffad update all filter lists and test again, see if works now even without whitelisting the `stripe` request

**Comment by saffad** [comment]
Unfortunately it was still blocking when testing 3D secure: https://authentication.cardinalcommerce.com/Content/dist/js/jsnlog.js

I was able to clear 3D secure after allowing this URL 
`@@||authentication.cardinalcommerce.com/Content/dist/js/jsnlog.js$script,domain=authentication.cardinalcommerce.com`

**Comment by saffad** [comment]
Yes, I forced update and cleared my rules before testing. Could it be another filter?

**Comment by saffad** [comment]
Ok. Will test again when I need to make a purchase.

**Comment by joshuabaker** [comment]
Encountered the same over the past few days (`cardinalcommerce.com` blocked) and found this issue.

I can confirm that a purge and update of the filters rectified the issue for me.

`r.stripe.com` remained blocked without issue and the SCA verification request worked as expected.
