### ISSUE TITLE
streamelements.com: breakage

### ISSUE THREAD

**Issue by mjevans** [uBlockOrigin/uAssets#17436]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://streamelements.com/diredwarf/tip`

### Category

breakage

### Description

It's probably the same for any other viewer of a streamer who uses this platform.

EXPECTED workflow:

Load page, fill out form, click Tip (maybe have to Oauth Twitch to confirm ID but not to offer control of account); money goes to streamer.

OBSERVED behavior:

Load page, popup wants to login to twitch first.  Redirection loop of user clicking the same button again as the process somehow fails.

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Firefox: 111
filterset (summary): 
  network: 167898
  cosmetic: 231896
  scriptlet: 40759
  html: 1108
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7250-4, 2h.50m
    https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/google_duckduckgo/all.txt: 4228-0, 14h.52m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39380-3737, 22h.55m
    adguard-generic: 69346-6204, 3d.7h.19m
    adguard-mobile: 8712-98, 3d.7h.17m
    adguard-annoyance: 65919-5490, 3d.7h.16m
    adguard-social: 20129-38, 3d.3h.10m
    fanboy-thirdparty_social: 68-0, 7d.18h.28m
    fanboy-cookiemonster: 46484-241, 2d.15h.7m
    ublock-annoyances: 4854-4, 3d.7h.18m
    FIN-0: 2251-0, 3d.7h.15m
    JPN-1: 10502-31, 3d.3h.9m
    NOR-0: 3143-3, 14h.53m
    RUS-0: 39553-336, 1d.14h.59m
  default: 
    user-filters: 252-5, never
    ublock-filters: 34015-111, 3d.7h.14m
    ublock-badware: 6221-5, 3d.7h.13m
    ublock-privacy: 352-0, 1d.19h.2m
    ublock-abuse: 78-0, 1d.19h.1m
    ublock-unbreak: 1956-2, 3d.7h.12m
    easylist: 65360-713, 3d.15h.23m
    easyprivacy: 30755-12624, 3d.15h.24m
    urlhaus-1: 6742-0, 6h.51m
    plowe-0: 3751-3, 8d.10h.32m
    ublock-quick-fixes: 376-5, 18h.54m
filterset (user): [array of 254 redacted]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 23 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1780 ms (selfie)
  maxAssetCacheWait: 766 ms
popupPanel: 
  blocked: 12
  no-remote-fonts: true
  blockedDetails: 
    cloudflareinsights.com: 2
    gstatic.com: 5
    redditstatic.com: 1
    typekit.net: 4
```
</details>

**Comment by mapx-** [comment]
est first using only the default filter lists. 
If it works test again with your current lists removing one by one the not-default lists. When you find the "bad" one just report it back here.

**Comment by mjevans** [comment]
I thought I _was_ only using the default lists.

Are there steps for getting to that state?

**Comment by mjevans** [comment]
Thank you, after finding and pressing the reset button on the main settings page (all the caches had been updated last night or auto-re-updated since then) I tried again.

This time it worked, so either UBO is proven to not be the problem, or if it was a site specific issue they fixed their workflow (it's not reproducible, at the moment).

**Comment by Jumper309** [comment]
I've encountered the same situation. However, when I click on 'https://streamelements.com/lirik/store' and replace 'lirik' with any account, the result is still a completely blank webpage.

**Comment by liamengland1** [comment]
Test `@@||static.zdassets.com/ekr/snippet.js$script,domain=streamelements.com` @Jumper309

**Comment by Jumper309** [comment]
I've followed the steps in #17436 (comment), but there hasn't been any change in the situation. The webpage is still completely blank.

**Comment by stephenhawk8054** [comment]
> However, when I click on `https://streamelements.com/lirik/store` and replace 'lirik' with any account, the result is still a completely blank webpage.

Can you give example link? Do you need to sign in? I don't know which `any account` here to reproduce.

**Comment by Jumper309** [comment]
> > However, when I click on `https://streamelements.com/lirik/store` and replace 'lirik' with any account, the result is still a completely blank webpage.
> 
> Can you give example link? Do you need to sign in? I don't know which `any account` here to reproduce.

Please find the account of any Twitch streamer to input. I believe I don't need to log in because when I click, the whole webpage is blank.

**Comment by stephenhawk8054** [comment]
@Jumper309 I access `https://streamelements.com/twitchmedia39/store` and it auto-redirects to `https://streamelements.com/login?redirect=https%3a%2f%2fstreamelements.com%2ftwitchmedia39%2fstore` for me

Video: https://github.com/uBlockOrigin/uAssets/assets/66517106/349c86d9-1e52-461b-b101-f346e6f72236

**Comment by Jumper309** [comment]
> @Jumper309 I access `https://streamelements.com/twitchmedia39/store` and it auto-redirects to `https://streamelements.com/login?redirect=https%3a%2f%2fstreamelements.com%2ftwitchmedia39%2fstore` for me
> 
> Video: https://github.com/uBlockOrigin/uAssets/assets/66517106/349c86d9-1e52-461b-b101-f346e6f72236

Perhaps try logging in and then reopening the URL? I'm not sure how this situation occurred either.
