### ISSUE TITLE
jn.pt: breakage

### ISSUE THREAD

**Issue by tnmendes** [uBlockOrigin/uAssets#17439]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A year ago a specific filter was added to this site because the video was not loading. But now it's not working again when it's videos.

Can you give a look at this?

Thank you

### URL(s) where the issue occurs.

`https://www.jn.pt/local/videos/incendio-destruiu-por-completo-um-camiao-na-a29-veja-o-momento-16125007.html`

### uBO version

1.48.4

### Browser name and version

Chrome Version 111.0.5563.146 (Official Build) (arm64)

### Settings

All default

**Comment by mapx-** [comment]
add

`@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=jn.pt`

**Comment by tnmendes** [comment]
yeap, it worked for me! Can this filter be available for everyone who uses uBlock?

**Comment by mapx-** [comment]
> yeap, it worked for me! Can this filter be available for everyone who uses uBlock?

I've notified the list maintainer
