### ISSUE TITLE
service.apport.net: breakage

### ISSUE THREAD

**Issue by Strubbl** [uBlockOrigin/uAssets#17430]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://service.apport.net/public/track/`

### Category

breakage

### Description

This page is about tracking the delivery status of packages. But the page stays empty and does not show any content. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 91146
  cosmetic: 44080
  scriptlet: 17538
  html: 939
listset (total-discarded, last-updated): 
  default: 
    user-filters: 6-0, never
    ublock-filters: 34212-181, 3m
    ublock-badware: 6275-10, 3m
    ublock-privacy: 352-0, 3m
    ublock-abuse: 78-0, 3m
    ublock-unbreak: 1958-2, 3m
    ublock-quick-fixes: 469-1, 3m
    easylist: 65138-611, 3m
    easyprivacy: 30785-1778, 3m
    urlhaus-1: 6742-0, 3m
    plowe-0: 3752-2, 3m
    DEU-0: 6705-2, 3m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 161 ms (selfie)
  maxAssetCacheWait: 56 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    apport.net: 4
    google-analytics.com: 1
```
</details>

**Comment by gorhill** [comment]
I note that the breakage would also occur with AdGuard Tracking Protection.

**Comment by Strubbl** [comment]
> test
> 
> `@@||service.apport.net/apport-spa-common/src/tracking/tracking.js$script,1p`

If i add this as a filter of mine, the website works.

**Comment by mapx-** [comment]
> I note that the breakage would also occur with AdGuard Tracking Protection.

AG maintainers notified
