### ISSUE TITLE
virginmedia.com: breakage

### ISSUE THREAD

**Issue by 1Mark** [uBlockOrigin/uAssets#17434]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.virginmedia.com/mobile/sim-only/pay-monthly-sim?contractDuration=30&tariffID=1225955497&buspart=uk_ps_cus_mobile_GOOGLE_Mobile_Acq_Brand_SIM_Exact_Brand_SIM_Only_Exact_virgin%2Bsim%2Bonly&CMP=DFA&medium=PPC&gclid=EAIaIQobChMI34CNlIuR_gIVDrrtCh0ZeAbZEAAYASABEgIFovD_BwE&gclsrc=aw.ds`

### Category

breakage

### Description

# Webpage looks like this 
![image](https://user-images.githubusercontent.com/15360245/229938593-87a4b3a7-e5eb-418d-8b3a-8c85b92e0cf3.png)
# Instead of 
![image](https://user-images.githubusercontent.com/15360245/229938669-e9b42ce6-612b-4bc7-9375-7a51e5bbc98e.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 88889
  cosmetic: 39609
  scriptlet: 17509
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 6-1, never
    easylist: 65121-46, 27m
    easyprivacy: 30764-1177, 26m
    plowe-0: 3751-936, 6d.2h.18m
    ublock-abuse: 78-0, 6d.2h.21m
    ublock-badware: 6288-124, 30m
    ublock-filters: 33263-97, 29m
    ublock-privacy: 299-2, 6d.2h.20m
    ublock-quick-fixes: 375-23, 25m
    ublock-unbreak: 1947-43, 28m
    urlhaus-1: 6742-0, 24m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1088 ms (selfie)
  maxAssetCacheWait: 316 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    15gifts.com: 2
    bing.com: 1
    contentsquare.net: 1
    d16fk4ms6rqz1v.cloudfront.net: 1
    dwin1.com: 2
    facebook.net: 1
    google-analytics.com: 1
    googleoptimize.com: 1
    googletagmanager.com: 1
    qualtrics.com: 1
```
</details>

**Comment by 1Mark** [comment]
The fix is to add
```
! 2023-04-04 https://www.virginmedia.com
@@||www.googleoptimize.com/optimize.js?id=OPT-N6V8RJP&l=VMdataLayer$script,domain=www.virginmedia.com

```

**Comment by stephenhawk8054** [comment]
@ryanbr
