### ISSUE TITLE
tf1.fr: breakage

### ISSUE THREAD

**Issue by Loxis972** [uBlockOrigin/uAssets#17442]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tf1.fr/tf1/jt-20h/videos/le-20-heures-du-mardi-4-avril-2023-10707475.html`

### Category

breakage

### Description

> Il n'y a pas de son.

**There is no sound.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 108198
  cosmetic: 48389
  scriptlet: 17548
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 29254-35, 3d.21h.45m
    easylist: 65185-391, 23h.45m
    easyprivacy: 30767-1493, 1d.23h.56m
    plowe-0: 3751-960, 11d.8h.40m
    ublock-abuse: 78-1, 11d.8h.43m
    ublock-badware: 6090-134, 3d.21h.44m
    ublock-filters: 33159-189, 3d.21h.47m
    ublock-privacy: 293-2, 11d.8h.42m
    ublock-quick-fixes: 375-16, 17h.56m
    ublock-unbreak: 1945-46, 3d.21h.46m
    urlhaus-1: 6742-0, 17h.55m
filterset (user): [empty]
trustedset: 
  added: [array of 14 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3534 ms (selfie)
  maxAssetCacheWait: 1030 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    abtasty.com: 1
    estat.com: 1
    facebook.net: 1
    facil-iti.app: 1
    googletagmanager.com: 1
    ipify.org: 1
    mediarithmics.com: 1
    sentry-cdn.com: 1
    stickyadstv.com: 10
    trustcommander.net: 1
    usabilla.com: 1
    xiti.com: 1
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Loxis972** [comment]
j'ai tout essayé sauf pour le DNS car je ne sais pas comment cela fonctionne. Je suis sur Chrome mais néanmoins, je n'ai toujours pas le son.

**Comment by mapx-** [comment]
@Loxis972 I cannot help as I cannot reproduce your issue. You have to investigate further on your end.

**Comment by Loxis972** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/129971706/230404268-25403994-3136-4bd6-a5fa-9d85b682c42f.png">
à la rigueur voici les bloqueurs que j'utilise, toutefois, je l'ai tous désactivés excepté celui-ci mais toujours rien.
