### ISSUE TITLE
[nsfw] badgirlsdrop.com: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#17440]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://badgirlsdrop.com/s?Nuu`

### Category

detection

### Description

Impossible to bypass

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/230068543-9eb691ad-20b4-4668-ab7a-3444dcca6d5a.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 125545
  cosmetic: 69422
  scriptlet: 18937
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39566-166, 1d.3h.24m
  default: 
    user-filters: 0-0, never
    FRA-0: 29149-35, 1d.3h.24m
    easylist: 65110-409, 1d.3h.24m
    easyprivacy: 30772-1578, 1d.3h.24m
    plowe-0: 3752-965, 1d.3h.24m
    ublock-abuse: 78-2, 1d.3h.24m
    ublock-badware: 6244-144, 1d.3h.24m
    ublock-filters: 33263-217, 1d.3h.24m
    ublock-privacy: 302-2, 1d.3h.24m
    ublock-quick-fixes: 471-16, 2h.4m
    ublock-unbreak: 1947-46, 1d.3h.24m
    urlhaus-1: 7070-0, 2h.3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 605 ms (selfie)
  maxAssetCacheWait: 95 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    dfdgfruitie.xyz: 5
```
</details>

**Comment by mapx-** [comment]
this is due to RUAdList blocking all *.xyz sites

add
`@@||dfdgfruitie.xyz/adserver/yzfdmoan.js$script,domain=badgirlsdrop.com`

dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/ad4699fac9554af7f3bcb8cc3784db35445fe49e
