### ISSUE TITLE
The Atlantic

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#1744]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
`https://www.theatlantic.com/education/archive/2018/03/michigan-state-university-is-botching-its-reputation-rehab/555932/`

Anti-Adblock

Appears to be fixed by `||theatlantic.com/packages/adsjs/ads.compat.min.js$script,first-party`

**Comment by zaphodbeebblebrox** [comment]
It is back @mapx-

**Comment by okiehsch** [comment]
I can't reproduce with Chrome or Firefox.

**Comment by mapx-** [comment]
Me neither.
