### ISSUE TITLE
landings.anlinkspots.com: ads

### ISSUE THREAD

**Issue by Talhac21** [uBlockOrigin/uAssets#17441]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://landings.anlinkspots.com/bettilt-tr/bettilt_slots/?partner=p4131p19715p318b`

### Category

ads

### Description

bet ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

`https://www.hizliresim.com/irxquaz`

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 90956
  cosmetic: 48774
  scriptlet: 18820
  html: 938
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34122-60, 3h.40m
    ublock-badware: 6297-10, 3h.39m
    ublock-privacy: 342-0, 11d.19h.20m
    ublock-abuse: 78-0, 11d.19h.19m
    ublock-unbreak: 1958-1, 3h.38m
    ublock-quick-fixes: 472-0, 3h.36m
    easylist: 65121-624, 3h.43m
    easyprivacy: 30785-1774, 3h.42m
    urlhaus-1: 7070-0, 3h.37m
    plowe-0: 3750-2, 11d.19h.17m
    TUR-0: 12155-12, 3h.41m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 808 ms (selfie)
  maxAssetCacheWait: 361 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
> `https://landings.anlinkspots.com/bettilt-tr/bettilt_slots/?partner=p4131p19715p318b`

provide the steps for landing on such page
