### ISSUE TITLE
uBlock Origin started breaking functionality at https://scribble.ninja 

### ISSUE THREAD

**Issue by yurique** [uBlockOrigin/uAssets#17443]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Recently (today or in the last couple of days) having uBlock Origin enabled started breaking this site: https://scribble.ninja/

It looks like it blocks all requests like this:
`https://scribble.website/sources/{source-file-id}`

For example:
* https://scribble.website/sources/chzjocyrkgfalkbylspmfcxnpzho
* https://scribble.website/sources/clafikskizzfsabsiaerezjwmftw

Requests to other endpoints seem to be working fine.

### URL(s) where the issue occurs.

https://scribble.ninja/u/scribble-ninja/dowbsuyistblnnczkkdohwndsvww

### Screenshot(s)

<img width="2555" alt="image" src="https://user-images.githubusercontent.com/919230/230167756-6ff589d1-31eb-4984-b0b1-5724505d7f94.png">

### uBO version

1.48.4

### Browser name and version

Google Chrome Version 111.0.5563.146 (Official Build) (arm64)

### Settings

none

**Comment by mapx-** [comment]
@ryanbr 

`/^https?:\/\/[0-9a-z]{5,}\.(digital|website|life|guru|space)\/[a-z0-9]{6,}\//$xhr,3p`

**Comment by yurique** [comment]
Out of curiosity – how long changes like this normally take to propagate to the user browsers? (the site is still broken with uBlock as of today).

**Comment by mapx-** [comment]
well, it was added a wrong filter in EL

**Comment by mapx-** [comment]
added to EL
https://github.com/easylist/easylist/commit/1aada500a9eaa68034bb350ecd6260fce2ed3be6

I'll remove my filter from unbreak list
