### ISSUE TITLE
pikabu.ru: breakage

### ISSUE THREAD

**Issue by trueR3W1ND** [uBlockOrigin/uAssets#17446]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pikabu.ru/`

### Category

breakage

### Description

Post at Горячее (hot)/also landing page didn't load up after scrolling down. This should be infine.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 146824
  cosmetic: 171130
  scriptlet: 25487
  html: 1109
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 27316-70, 22h.43m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39181-3833, 22h.44m
    ublock-annoyances: 4875-6, 19h.47m
    adguard-annoyance: 66072-922, 19h.47m
    fanboy-thirdparty_social: 68-0, 3d.28m
    fanboy-social: 21739-49, 1d.23h.4m
    adguard-social: 20160-1740, 19h.47m
  default: 
    user-filters: 48-3, never
    ublock-filters: 34229-82, 19h.47m
    ublock-badware: 6292-10, 19h.47m
    ublock-privacy: 352-59, 1d.4h.47m
    ublock-abuse: 78-0, 1d.4h.47m
    ublock-unbreak: 1958-47, 19h.47m
    easylist: 64987-421, 2d.23h.26m
    easyprivacy: 30767-12079, 1d.1h.47m
    plowe-0: 3751-1000, 11d.5h.34m
    RUS-0: 39574-3792, 23h.47m
    urlhaus-1: 7070-0, 18h.28m
    ublock-quick-fixes: 469-130, 18h.28m
filterset (user): [array of 48 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  allowGenericProceduralFilters: true
  assetFetchTimeout: 40
  autoUpdateAssetFetchPeriod: 1
  autoUpdateDelayAfterLaunch: 1
  autoUpdatePeriod: 1
  cacheStorageCompression: false
supportStats: 
  allReadyAfter: 2397 ms (selfie)
  maxAssetCacheWait: 1197 ms
popupPanel: 
  blocked: 19
  blockedDetails: 
    pikabu.ru: 10
    adfox.ru: 2
    googletagmanager.com: 1
    tns-counter.ru: 1
    vk.com: 1
    yandex.ru: 4
```
</details>

**Comment by dimisa-RUAdList** [comment]
Too many filters and they conflict. Try checking with default settings.

**Comment by mapx-** [comment]
> user-filters: 48-3

maybe some custom filter too

**Comment by trueR3W1ND** [comment]
Actually I've tested all filters to set off, custom included.

Not sure why, but now I've tried again... And everything works fine with the same filters applied.
