### ISSUE TITLE
peacocktv.com: breakage

### ISSUE THREAD

**Issue by matthew02** [uBlockOrigin/uAssets#17449]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.peacocktv.com/watch/profiles?return=%2Fwatch%2Fhome%3Fmethod%3Dweb_roadblock`

### Category

breakage

### Description

Site works only when uBO is disabled. Allowing all globally or locally does not help.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/416065/230206888-d6a666fa-f02f-45dc-817b-41e79067a10d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 112
filterset (summary): 
  network: 199544
  cosmetic: 172037
  scriptlet: 38911
  html: 1100
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 69271-5698, 1d.14h.51m
    adguard-mobile: 8709-150, 1d.14h.50m
    adguard-spyware-url: 969-5, 1d.14h.48m
    block-lan: 44-0, 26d.1h.55m
    curben-phishing: 67819-33, 2h.36m
    curben-pup: 199-0, 2h.35m
    adguard-annoyance: 65960-6986, 1d.14h.47m
    adguard-social: 20137-1539, 1d.14h.46m
    fanboy-thirdparty_social: 69-1, 8d.40m
    fanboy-annoyance: 82349-72022, 8d.39m
    fanboy-cookiemonster: 46401-17507, 8d.38m
    fanboy-social: 21769-13644, 2d.19h.17m
    ublock-annoyances: 4864-7, 1d.14h.45m
    dpollock-0: 11349-471, 3d.23h.23m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34128-290, 1d.14h.54m
    ublock-badware: 6237-0, 1d.14h.53m
    ublock-privacy: 352-1, 22h.40m
    ublock-abuse: 78-0, 22h.39m
    ublock-unbreak: 1958-1, 1d.14h.52m
    ublock-quick-fixes: 469-0, 2h.38m
    easylist: 65097-17622, 1d.14h.49m
    easyprivacy: 30755-1868, 3d.19h.22m
    urlhaus-1: 7056-0, 2h.37m
    plowe-0: 3752-2, 13d.47m
filterset (user): [empty]
trustedset: 
  added: [array of 37 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    opera-scheme
    vivaldi-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 289 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 54025 ms (selfie)
  maxAssetCacheWait: 338 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    peacocktv.com: 1
    cookielaw.org: 2
    demdex.net: 3
    freewheel.tv: 1
```
</details>

**Comment by mapx-** [comment]
I was able to start a (free - but needing an account) show in firefox / chrome

`https://www.peacocktv.com/watch/playback/vod/GMO_00000000190987_02_HDSDR/afd8274f-ad90-346a-a9a3-40943748bee7`

**Comment by matthew02** [comment]
Well, I can't get Peacock to work at all now. Not even in a fresh profile. Seems to not be related to uBO. My apologies.
