### ISSUE TITLE
hulu.com: ads

### ISSUE THREAD

**Issue by cweb19** [uBlockOrigin/uAssets#17448]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hulu.com/watch/5f02dc98-f05c-447f-b63f-a80cefb4cb8d`

### Category

ads

### Description

all ads are getting through UBlock on hulu

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 89168
  cosmetic: 39653
  scriptlet: 17538
  html: 939
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34209-168, 1d.4h.41m
    ublock-badware: 6263-10, 1d.4h.42m
    ublock-privacy: 352-0, 2d.20h.49m
    ublock-abuse: 78-0, 2d.20h.50m
    ublock-unbreak: 1958-1, 1d.4h.43m
    easylist: 65121-605, 5h.37m
    easyprivacy: 30767-1769, 1d.4h.44m
    urlhaus-1: 7056-0, 3h.37m
    plowe-0: 3752-2, 2d.4h.42m
    ublock-quick-fixes: 477-0, 5h.36m
filterset (user): [empty]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 379 ms (selfie)
  maxAssetCacheWait: 104 ms
popupPanel: 
  blocked: 108
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  blockedDetails: 
    hulu.com: 50
    assetshuluimcom-a.akamaihd.net: 16
    conviva.com: 10
    demdex.net: 15
    imrworldwide.com: 1
    omtrdc.net: 6
    scorecardresearch.com: 10
```
</details>

**Comment by mapx-** [comment]
No ad on my end.
You should reset uBO to default settings, force update all filter lists and then do not touch any setting and test again.
