### ISSUE TITLE
exportplanning.com: breakage

### ISSUE THREAD

**Issue by fcorallini** [uBlockOrigin/uAssets#17456]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

By default the extension blocks any javascript file loaded from url containing the word _analytics_ also blocking some legitimate website files.

### URL(s) where the issue occurs.

`https://www.exportplanning.com/analytics/getiframefull/YJcH0RlUcsRDT7zw/700/1100/`

```
https://www.example.com/static/analytics/jsi18n/it/djangojs.js
https://www.example.com/static/analytics/.../.../example.js
```

### uBO version

1.48.2

### Browser name and version

Firefox 111 && Google Chrome 111

### Settings

Default Settings

**Comment by fcorallini** [comment]
> Explain the steps required to reproduce your problem, including the links to those legitimate websites.

Try going to this url, with the extension active the chart is not loaded.
https://www.exportplanning.com/analytics/getiframefull/YJcH0RlUcsRDT7zw/700/1100/

**Comment by stephenhawk8054** [comment]
@ryanbr I think `/analytics/js$script` is quite broad

**Comment by stephenhawk8054** [comment]
@fcorallini It's fixed for your `exportplanning.com` link above, you can force update all your filter lists (click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.

If there are other links that you encounter breakages after force updating, please report here.

**Comment by fcorallini** [comment]
Now everything seems to be working fine, thanks!

**Comment by partingscientist** [comment]
Surely removing and/or assigning `badfilter` due to a single false positive are a bit much, no? Unless such false positive cases are widespread, wouldn't it be better to create an exception for the reporter's site instead?

**Comment by stephenhawk8054** [comment]
We do not only rely on reports. Sometimes if the filter word is too broad, it should be revised and analyzed how the pattern should be. The `badfilter` is just followed from the removal in EP: https://github.com/easylist/easylist/commit/1cd26982469fe81b05bb7f583958673cd8394c5f
