### ISSUE TITLE
qpt9xysmxb.larksuite.com: nuisance

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#17450]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://qpt9xysmxb.larksuite.com/file/boxusNKXYzAqmQbXgizE1gYm0Og`

### Category

nuisance

### Description

the "incompatible browser" despite the browser being waterfox and it working perfectly fine is a nuisance
`##.disabled-contextmenu.not-compatible__announce` solves this

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/11874211/230243680-7c074e09-7183-4703-866b-6fea91ab975c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 102
filterset (summary): 
  network: 110953
  cosmetic: 108865
  scriptlet: 23319
  html: 1099
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 65960-782, 2d.5h.29m
    ublock-annoyances: 4864-6, 2d.5h.28m
    CHN-0: 27341-124, 2d.5h.33m
  default: 
    user-filters: 1-0, never
    ublock-filters: 34143-39, 2d.5h.32m
    ublock-badware: 6242-10, 2d.5h.31m
    ublock-privacy: 344-0, 8d.21h.47m
    ublock-abuse: 78-0, 8d.21h.46m
    ublock-unbreak: 1956-2, 2d.5h.30m
    ublock-quick-fixes: 469-13, 1d.1h.38m
    easylist: 65185-660, 1d.5h.41m
    easyprivacy: 30767-1788, 2d.5h.27m
    urlhaus-1: 6742-0, 1d.1h.39m
    plowe-0: 3751-2, 7d.1h.12m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 465 ms (selfie)
  maxAssetCacheWait: 177 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    byteoversea.com: 4
```
</details>

**Comment by mapx-** [comment]
report at easylist repository (for the nnoyances list)
