### ISSUE TITLE
textcompare.org: ads

### ISSUE THREAD

**Issue by pickfire** [uBlockOrigin/uAssets#17452]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The ads which have been blocked still have some invisible `div` left that is blocking clicks on buttons, which is a bit annoying.

### URL(s) where the issue occurs.

`https://www.textcompare.org/excel/`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/4687791/230264016-206b863f-3927-4c43-b2b9-9bc5ee4eb2b5.png)

### uBO version

1.48.4

### Browser name and version

FIrefox 111.0.1

### Settings

- Enable medium mode blocking but all normal stuff is still preserved

### Notes

The suggested fix is
```
! 2023-04-05 https://www.textcompare.org
www.textcompare.org##.ez-sidebar-wall
```

**Comment by stephenhawk8054** [comment]
@ryanbr
