### ISSUE TITLE
lookup.icann.org: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#17451]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lookup.icann.org/en`

### Category

nuisance

### Description

![image](https://user-images.githubusercontent.com/19517680/230254643-abc1f4ed-9e87-4245-8c54-af1c825d04d0.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 113
filterset (summary): 
  network: 89567
  cosmetic: 39662
  scriptlet: 17575
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65159-46, 24m
    easyprivacy: 30755-1175, 23m
    plowe-0: 3751-936, 4d.14h.17m
    ublock-abuse: 78-0, 4d.14h.15m
    ublock-badware: 6301-124, 22m
    ublock-filters: 33376-97, 21m
    ublock-privacy: 302-2, 4d.14h.11m
    ublock-quick-fixes: 484-131, 19m
    ublock-unbreak: 1962-43, 20m
    urlhaus-1: 7368-0, 18m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1551 ms (selfie)
  maxAssetCacheWait: 276 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
already fixed in AdGuard Annoyances and Fanboy’s Annoyance, enable one of them
