### ISSUE TITLE
miraculous-es.jimdofree.com: detection

### ISSUE THREAD

**Issue by Agusstine** [uBlockOrigin/uAssets#17453]
### Prerequisites

- [ ] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [ ] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [ ] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://miraculous-es.jimdofree.com/temporadas/subt%C3%ADtulos-en-espa%C3%B1ol/temporada-5/`

### Category

detection

### Description

this page detects ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 109
filterset (summary): 
  network: 92122
  cosmetic: 45273
  scriptlet: 17851
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65121-46, 43m
    easyprivacy: 30782-1177, 42m
    plowe-0: 3753-936, 41m
    spa-0: 3561-11, 46m
    spa-1: 5155-198, 46m
    ublock-abuse: 78-0, 39m
    ublock-badware: 6301-124, 37m
    ublock-filters: 33376-132, 36m
    ublock-privacy: 302-2, 35m
    ublock-quick-fixes: 484-131, 34m
    ublock-unbreak: 1947-44, 33m
    urlhaus-1: 7368-0, 32m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4329 ms (selfie)
  maxAssetCacheWait: 561 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    d3mzokty951c5w.cloudfront.net: 2
    displayvertising.com: 2
    disqus.com: 2
    googlesyndication.com: 2
    jsdelivr.net: 1
    livetrafficfeed.com: 1
    narrative.io: 1
    pippio.com: 1
    retargetly.com: 1
    rezync.com: 1
    viglink.com: 2
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce the issue, however see if this filter helps

`||cdn.jsdelivr.net/gh/RockBlogger/Anti-AdBlocker$script`

**Comment by gorhill** [comment]
> - [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.

You didn't check this, be sure to not use another content blocker beside uBO, other blockers often interfere negatively when it comes to detection.
