### ISSUE TITLE
frandroid.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#17455]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.frandroid.com/culture-tech/intelligence-artificielle/1656733_chatgpt-cette-application-non-officielle-sintegre-parfaitement-a-windows`

### Category

nuisance

### Description

Empty frames

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/230329442-291b3b1b-50ba-446e-a3ac-ad15d027cf0b.png)

![image](https://user-images.githubusercontent.com/50231020/230329486-9bf88460-88b0-4428-8da3-e415ef840e71.png)

![image](https://user-images.githubusercontent.com/50231020/230329520-abfa61a0-9c99-4b98-949c-5a841156aa10.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 125599
  cosmetic: 69422
  scriptlet: 18928
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39561-166, 21h.29m
  default: 
    user-filters: 0-0, never
    FRA-0: 28842-33, 21h.29m
    easylist: 65095-90, 21h.29m
    easyprivacy: 30782-1577, 21h.29m
    plowe-0: 3753-965, 21h.29m
    ublock-abuse: 78-2, 21h.29m
    ublock-badware: 6293-144, 21h.29m
    ublock-filters: 33370-217, 21h.29m
    ublock-privacy: 302-2, 21h.29m
    ublock-quick-fixes: 475-137, 21h.29m
    ublock-unbreak: 1947-46, 21h.29m
    urlhaus-1: 7070-0, 21h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 735 ms (selfie)
  maxAssetCacheWait: 96 ms
popupPanel: 
  blocked: 46
  blockedDetails: 
    frandroid.com: 1
    3lift.com: 2
    adnxs.com: 2
    amazon-adsystem.com: 1
    cloudflareinsights.com: 1
    criteo.com: 1
    criteo.net: 1
    d2v02itv0y9u9t.cloudfront.net: 2
    disqus.com: 3
    doubleclick.net: 1
    googletagmanager.com: 1
    humanoid.fr: 2
    imrworldwide.com: 1
    onesignal.com: 2
    opti-digital.com: 5
    parsely.com: 1
    pubmatic.com: 2
    richaudience.com: 7
    rubiconproject.com: 3
    sddan.com: 3
    teads.tv: 1
    ttvnw.net: 1
    videostep.com: 1
    wp.com: 1
  hasUnprocessedRequest: true
```
</details>

**Comment by gorhill** [comment]
I don't see empty frames on my side with default lists and _FRA: AdGuard Français_.

> hasUnprocessedRequest: true

You need to force a reload of the page when uBO was not able to filter properly at browser launch -- this is likely the issue.

**Comment by gorhill** [comment]
Yeah my bad, I didn't realize this -- hence why I removed my comment.

**Comment by TheRealSkywarp** [comment]
Sponsored link on `https://www.frandroid.com/telecharger/apps/firefox`
<details>
<summary>Screenshot</summary>

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/5eaf9cf0-075c-4131-a926-5134b272991a" />

</details>

<details>

```yaml
uBlock Origin: 1.72.0
Firefox Mobile: 152
filterset (summary):
 network: 240769
 cosmetic: 289780
 scriptlet: 72064
 html: 3936
listset (total-discarded, last-updated):
 added:
  adguard-generic: 97462-5831, 3h.27m
  adguard-spyware-url: 2559-134, 3h.27m
  block-lan: 91-0, 3h.27m
  adguard-cookies: 39063-113, 3h.27m
  fanboy-cookiemonster: 47029-3878, 3h.27m
  ublock-cookies-easylist: 5747-96, 3h.27m
  adguard-social: 26552-45, 3h.27m
  fanboy-social: 17697-865, 3h.27m
  fanboy-thirdparty_social: 69-18, 3h.27m
  adguard-popup-overlays: 31892-1066, 3h.27m
  adguard-mobile-app-banners: 7531-115, 3h.27m
  adguard-other-annoyances: 16176-313, 3h.27m
  [9 lists not shown]: [too many]
 default:
  user-filters: 109-2, never
  ublock-filters: 52921-86, 3h.27m
  ublock-badware: 10244-27, 3h.27m
  ublock-privacy: 4054-2, 3h.27m
  ublock-unbreak: 2835-1, 3h.27m
  ublock-quick-fixes: 477-0, 2h.17m
  adguard-mobile: 12536-105, 3h.27m
  easylist: 84982-1286, 3h.27m
  easyprivacy: 55914-137, 3h.27m
  urlhaus-1: 48180-11, 3h.27m
  plowe-0: 3513-1438, 3h.27m
  FRA-0: 17318-397, 3h.27m
filterset (user): [array of 109 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 518 ms (selfie)
 maxAssetCacheWait: 266 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gorhill** [comment]
This works on my side:

    frandroid.com##.ops-next-mobile:has(.sponsored-label)

Should be fixed in "AdGuard Français".
