### ISSUE TITLE
filecr.com: detection

### ISSUE THREAD

**Issue by High-rider** [uBlockOrigin/uAssets#17454]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://filecr.com/windows/reason-studios-reason/?id=240916769964`

### Category

detection

### Description

It detects and asks me to turn off the adblocker after which it runs fine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<https://imgur.com/zY2Z2uG>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 167311
  cosmetic: 165839
  scriptlet: 25275
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 65960-93, 1d.23h.30m
    adguard-spyware-url: 969-2, 1d.16h.44m
    block-lan: 44-0, 17d.20h.27m
    curben-phishing: 65271-2, 19h.48m
    curben-pup: 190-0, 19h.49m
    fanboy-annoyance: 81157-5563, 1d.13h.38m
    ublock-annoyances: 4903-217, 1d.23h.29m
  default: 
    user-filters: 0-0, never
    easylist: 65110-101, 1d.13h.37m
    easyprivacy: 30754-1259, 3d.11h.59m
    plowe-0: 3753-938, 1d.53m
    ublock-abuse: 78-0, 7d.22h.58m
    ublock-badware: 6258-151, 2d.17h.1m
    ublock-filters: 33278-499, 2d.17h.3m
    ublock-privacy: 295-10, 7d.22h.57m
    ublock-quick-fixes: 471-16, 19h.47m
    ublock-unbreak: 1944-48, 2d.17h.2m
    urlhaus-1: 7070-2, 19h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1431 ms (selfie)
  maxAssetCacheWait: 340 ms
popupPanel: 
  blocked: 27
  blockedDetails: 
    doubleclick.net: 1
    fonts.googleapis.com: 1
    google.co.in: 2
    google.com: 3
    googleadservices.com: 1
    googlesyndication.com: 6
    googletagservices.com: 1
    gstatic.com: 3
    sentry.io: 8
    zinlab.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update the filter lists and test again?

**Comment by mapx-** [comment]
> I forced an update of my filter lists

You didn't
