### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by googie0815** [uBlockOrigin/uAssets#17463]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bild.de/adblockwall.html`

### Category

detection

### Description

Page cannot be used. It is requested to disable the AdBlocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bild](https://user-images.githubusercontent.com/56229424/230440148-8505fb8e-7dc8-4306-96a1-04e75f5099f0.PNG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 93272
  cosmetic: 86547
  scriptlet: 19457
  html: 938
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 46471-213, 5d.1h.51m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34005-40, 23h
    ublock-badware: 6297-10, 22h.59m
    ublock-privacy: 352-0, 1d.19m
    ublock-abuse: 78-0, 1d.20m
    ublock-unbreak: 1973-0, 23h.1m
    easylist: 65121-612, 23h.2m
    easyprivacy: 30785-1778, 23h.3m
    urlhaus-1: 7056-0, 22h.56m
    plowe-0: 3753-2, 1d.18m
    DEU-0: 6707-16, 22h.58m
    ublock-quick-fixes: 477-9, 22h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 6 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 443 ms (selfie)
  maxAssetCacheWait: 182 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    bild.de: 3
    consensu.org: 1
    ioam.de: 1
    iocnt.net: 1
```
</details>

**Comment by peace2000** [comment]
Can you try this filter?

`bild.de##+js(aeld, load, adBlockerCheck)`

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/commit/729076202217dd98a0f2996693844913abefd1aa

**Comment by mapx-** [comment]
already fixed 5 h ago
