### ISSUE TITLE
[nsfw] chrome.google.com: nuisance

### ISSUE THREAD

**Issue by thisishusseinali** [uBlockOrigin/uAssets#17462]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm/related?hl=en`

### Category

nuisance

### Description

**uBlock yellow color Error**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89250
  cosmetic: 39756
  scriptlet: 17525
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65103-76, never
    easyprivacy: 30755-1145, never
    plowe-0: 3751-937, never
    ublock-abuse: 78-0, never
    ublock-badware: 6217-113, never
    ublock-filters: 33203-112, never
    ublock-privacy: 302-5, never
    ublock-quick-fixes: 462-2, never
    ublock-unbreak: 1945-41, never
    urlhaus-1: 7324-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2348 ms
  maxAssetCacheWait: 21 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by peace2000** [comment]
Hi, where is that "yellow color"? Sorry but I didn't catch.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Toolbar-icon>
