### ISSUE TITLE
nsw2u.org: detection

### ISSUE THREAD

**Issue by troyyyyyyyyyyyyy** [uBlockOrigin/uAssets#17461]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nsw2u.org/`

### Category

detection

### Description

The site detects adblock and puts an overlay over the screen.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screen](https://user-images.githubusercontent.com/127453844/230403937-0eee5234-38c9-4c50-86b9-f0d3b0a7e011.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 89517
  cosmetic: 39680
  scriptlet: 17564
  html: 944
listset (total-discarded, last-updated): 
  default: 
    user-filters: 14-0, never
    ublock-filters: 34249-168, 2h.41m
    ublock-badware: 6297-10, 2h.40m
    ublock-privacy: 342-0, 11d.3h.43m
    ublock-abuse: 78-0, 11d.3h.42m
    ublock-unbreak: 1970-3, 2h.39m
    ublock-quick-fixes: 485-0, 10h.43m
    easylist: 65121-605, 10h.44m
    easyprivacy: 30767-1769, 2d.22h.18m
    urlhaus-1: 7368-0, 10h.42m
    plowe-0: 3751-2, 10d.15h.37m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 337 ms (selfie)
  maxAssetCacheWait: 75 ms
popupPanel: 
  blocked: 15
  blockedDetails: 
    a-ads.com: 3
    amazon-adsystem.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    lnqdtbcrilhrdye.com: 1
    media.net: 1
    quantserve.com: 1
    woafoame.net: 2
    wp.com: 2
```
</details>

**Comment by peace2000** [comment]
Hi, I can't see that window. Please update your lists and disable your custom filters to see if they cause the issue.

**Comment by gorhill** [comment]
I can reproduce as soon as I enable ABP or AdBlock, so possibly another case of using other blocker alongside uBO.

**Comment by troyyyyyyyyyyyyy** [comment]
Would NoScript trigger it? I do not have any other ad blockers installed.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by gorhill** [comment]
> Would NoScript trigger it?

Why not just disable it to find out?
