### ISSUE TITLE
teams.microsoft.com: breakage

### ISSUE THREAD

**Issue by DeniedCayden** [uBlockOrigin/uAssets#17468]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://teams.microsoft.com/_?culture=en-us&country=US&lm=deeplink&lmsrc=homePageWeb&cmpid=WebSignIn`

### Category

breakage

### Description

whenever i try to open assingments posted it just cancels as soon as it loads

### Screenshot(s)

![Screen recording 2023-04-06 12.20.49 PM.webm](https://user-images.githubusercontent.com/130091892/230462997-5223bbcf-ff1a-4338-8294-46ba416f6671.webm)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 89141
  cosmetic: 39804
  scriptlet: 17523
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 6-1, never
    easylist: 65254-46, 3d.3h.55m
    easyprivacy: 30764-1177, 3d.2h.44m
    plowe-0: 3752-936, 3d.4h
    ublock-abuse: 78-0, 4d.10h.52m
    ublock-badware: 6238-124, 3d.3h.56m
    ublock-filters: 33203-97, 3d.3h.58m
    ublock-privacy: 302-2, 3d.4h.52m
    ublock-quick-fixes: 484-11, 21h.37m
    ublock-unbreak: 1945-42, 3d.3h.57m
    urlhaus-1: 7056-0, 21h.38m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 440 ms (selfie)
  maxAssetCacheWait: 222 ms
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
  blockedDetails: 
    microsoft.com: 6
    msedge.net: 1
```
</details>

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests
