### ISSUE TITLE
When uBlock is on, videos on Pelispedia.tv fail loading

### ISSUE THREAD

**Issue by FedeMarshall** [uBlockOrigin/uAssets#1746]
### URL(s) where the issue occurs

`https://www.pelispedia.tv`

### Describe the issue

When uBlock is on, videos on Pelispedia fail loading. This happens, so far, with every video i've tried to load for any server used.

### Versions

- Browser/version: Chrome/64.0.3282.186
- uBlock Origin version: 1.15.2

**Comment by okiehsch** [comment]
Does
````
@@||freegeoip.net/json/*$xmlhttprequest,domain=pelispedia.vip
pelispedia.vip##script:inject(nowebrtc.js)
````
work for you?

**Comment by FedeMarshall** [comment]
Yes it does! Thanks!

**Comment by FedeMarshall** [comment]
I've added it to My filters (is it the right place?) and still not working.

**Comment by okiehsch** [comment]
Works for me for example if I go to 
`https://www.pelispedia.tv/pelicula/the-open-house/`
the video works after I added `@@||freegeoip.net/json/*$xmlhttprequest,domain=pelispedia.vip`

**Comment by FedeMarshall** [comment]
Thanks @okiehsch ! It does work indeed, yesterday i've tested only with html5 servers and did not work, today, after your comment, I've tested in the others and it is working.
Thanks again!
