### ISSUE TITLE
mad4wheels.com: breakage

### ISSUE THREAD

**Issue by KloneBaker** [uBlockOrigin/uAssets#17477]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

"uBlock filters" tend to break the main and latest page for mad4wheels.com

### URL(s) where the issue occurs.

[Main Page] `https://www.mad4wheels.com/`
[Latest Page] `https://www.mad4wheels.com/latest-galleries`

### Screenshot(s)

![121](https://user-images.githubusercontent.com/81959674/230553952-a915bb72-150b-490f-a3a0-9d52b3d4155a.jpg)
![122](https://user-images.githubusercontent.com/81959674/230553955-8a688d78-5a70-4c29-9b84-bea83fd06692.jpg)

### uBO version

1.48.4

### Browser name and version

LibreWolf 111.0.1-1

### Settings

No modification.

### Notes

Pages only break with the "uBlock filters" on.
Tested on Chrome, Firefox (stable and nightly.) [All brand new installs.]
No other AdBlock is used or installed, [dns/ip based, pihole based, etc...]

Thanks to everyone in the community for many years of amazing service. ❤️

**Comment by huyszn** [comment]
"AD BLOCKER DETECTED" image displays when going to the site. This only happens on chrome and not on firefox.
