### ISSUE TITLE
last.fm: breakage

### ISSUE THREAD

**Issue by Alliegaytor** [uBlockOrigin/uAssets#17470]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.last.fm/user/P-90_For_Retail/listening-report/week`

### Category

breakage

### Description

Upon enabling **Fanboy's Annoyance** or **Fanboy’s Social** lists the weekly listening charts in last.fm break (shown in the screenshots below)

I determined that the filter breaking it was `/social/twitter.$~xhr` from a snippet of the logger

```
+1
/social/twitter.$~xhr
--
www.last.fm
1
get
script
https://www.last.fm/static/js-build/social/twitter.js?1678881030
```

For some reason blocking `https://www.last.fm/static/js-build/social/twitter.js?1678881030` causes the listening graphs to break.

I managed to fix it locally by using this filter rule

```
! 2023-04-07 FIX LAST.FM
@@||www.last.fm/static/js-build/social/twitter.js?1678881030$script,domain=www.last.fm
```

I tested this fix in another browser with a fresh install of ublock and it appears to work with it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

## Not working
![2023-04-07-061658_screenshot](https://user-images.githubusercontent.com/61523203/230493098-f1dd5e5c-0609-4ed3-8b7f-c111330124cc.png)
## Working
![2023-04-07-061712_screenshot](https://user-images.githubusercontent.com/61523203/230493107-e94928c2-18f9-4d06-8ad3-4cea943d408a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 96127
  cosmetic: 111718
  scriptlet: 19579
  html: 945
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 80938-398, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34256-168, 1m
    ublock-badware: 6441-5, 1m
    ublock-privacy: 352-0, 1m
    ublock-abuse: 78-0, 1m
    ublock-unbreak: 1975-3, 1m
    ublock-quick-fixes: 489-0, 1m
    easylist: 65264-607, 1m
    easyprivacy: 30791-1770, now
    urlhaus-1: 7165-0, now
    plowe-0: 3753-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 774 ms
  maxAssetCacheWait: 140 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    last.fm: 1
    cbsi.com: 1
    confiant-integrations.net: 1
    doubleclick.net: 1
    moatads.com: 1
    newrelic.com: 2
    strangeclocks.com: 1
    youtube-nocookie.com: 1
```
</details>

**Comment by mapx-** [comment]
`@@||last.fm/static/js-build/social/twitter.js$script,1p`

@ryanbr

**Comment by mapx-** [comment]
fixed https://github.com/easylist/easylist/commit/f63b2bfbd0b98d65cb71605058afc41d2f739354

**Comment by Korb** [comment]
Is anyone else having this issue right now? I'm talking about Charts not showing on `%username%’s year in music` page.

**Comment by stephenhawk8054** [comment]
Please give exact link and screenshot of the issue.
