### ISSUE TITLE
letelegramme.fr

### ISSUE THREAD

**Issue by Francois-dag** [uBlockOrigin/uAssets#1747]
`http://www.letelegramme.fr/soir/la-question-du-soir-19-03-2018-11892369.php`

### Describe the issue

When ublock-origin is enabled, you just get an arrow looping image, getting the entire article when
disabled ...

### Versions

- Browser/version: last firefow and last chrome
- uBlock Origin version: 1.1511b0 (firefox) 1.15.2 (chrome)

### Settings

- personal filters : ||cdn.adsafeprotected.com/

Cheers.

**Comment by mapx-** [comment]
@SMed79

**Comment by SMed79** [comment]
EasyPrivacy issue.

**Comment by mapx-** [comment]
sure, I know, but I saw you duplicated a lot of easyprivacy filters in Liste fr :-)

@ryanbr
