### ISSUE TITLE
support.1password.com: breakage

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#17478]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The cookie banner is not shown with uBlock Origin enabled.

### URL(s) where the issue occurs.

`https://support.1password.com/`

### Screenshot(s)

Screenshot with uBlock Origin enabled

![screenshot with ublock origin enabled](https://user-images.githubusercontent.com/62190484/230579847-df99cef9-bf1d-4438-9818-92b471fdb3fe.png)

Screenshot with uBlock Origin disabled

![screenshot with ublock origin disabled](https://user-images.githubusercontent.com/62190484/230580025-53e92730-2314-48c4-90f9-1a4735653e2f.png)

### Notes

None.

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 95226
  cosmetic: 47442
  scriptlet: 17541
  html: 939
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34209-177, 2d.18h.18m
    ublock-badware: 6263-10, 2d.18h.17m
    ublock-privacy: 352-0, 6d.19h.45m
    ublock-abuse: 78-0, 6d.19h.45m
    ublock-unbreak: 1958-1, 2d.18h.16m
    ublock-quick-fixes: 486-0, 1d.27m
    easylist: 65121-611, 2d.18h.15m
    easyprivacy: 30785-1770, 2d.18h.14m
    urlhaus-1: 7368-0, 1d.26m
    plowe-0: 3750-2, 6d.19h.44m
    ITA-0: 13531-1, 1d.28m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 656 ms (selfie)
  maxAssetCacheWait: 54 ms
```
</details>

**Comment by mapx-** [comment]
add

`/js/analytics.$badfilter`

@ryanbr
