### ISSUE TITLE
yandex.com: ads

### ISSUE THREAD

**Issue by crazypitHACS** [uBlockOrigin/uAssets#17475]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yandex.com/weather/?lat=52.3731339&lon=4.8903147`

### Category

ads

### Description

не скрывается реклама яндекса

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 109
filterset (summary): 
  network: 106532
  cosmetic: 60761
  scriptlet: 18840
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 139-6, never
    RUS-0: 39580-12, 1d.8h.13m
    easylist: 65159-63, 4h.10m
    easyprivacy: 30764-1285, 2d.4h.16m
    plowe-0: 3751-941, 5d.8h.53m
    ublock-abuse: 78-1, 6d.22h.22m
    ublock-badware: 6301-124, 4h.9m
    ublock-filters: 33383-127, 4h.8m
    ublock-privacy: 302-2, 6d.22h.21m
    ublock-quick-fixes: 471-134, 16h.12m
    ublock-unbreak: 1964-43, 4h.7m
    urlhaus-1: 7165-0, 16h.11m
filterset (user): [array of 139 redacted]
trustedset: 
  added: [array of 24 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8052 ms (selfie)
  maxAssetCacheWait: 528 ms
popupPanel: 
  blocked: 22
  blockedDetails: 
    yandex.ru: 22
```
</details>

**Comment by dimisa-RUAdList** [comment]
Ads on this domain are blocked by the [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) filter (left-click to subscribe).
