### ISSUE TITLE
Invalid filter in filters-2021.txt

### ISSUE THREAD

**Issue by AnAccountForReportingBugs** [uBlockOrigin/uAssets#17473]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There are two filters, on lines 6175 and 6176, that are invalid due to being an improper selector in browsers that only support level 3. Only a single selector is allowed in a :not pseudo-class. If selected and enabled, it can cause other issues with blocking when injected.

##.Ad-Container:not(div.adsbygoogle)
##.sidebar-ad:not(div.adsbygoogle)

should be corrected to something like:

##.Ad-Container:not(div):not(.adsbygoogle)
##.sidebar-ad:not(div):not(.adsbygoogle)

### URL(s) where the issue occurs.

`https://old.Reddit.com/`

### uBO version

1.48.4

### Browser name and version

Chrome 84

### Settings

N/a

**Comment by krystian3w** [comment]
Your repair method unblocks more than one `<div>` with the `.adsbygoogle` family used as bait.

Demo:

> <div id="Ad-Container"> real "ad" </div>

> <div id="sidebar-ad"> real "ad" </div>

```adb
###user-content-ad-container:not(div), user-ad-sidebar:not(div)
```

> <p id="Ad-Container"> bait "ad" </p>

> <p id="ad-sidebar"> bait "ad" </p>

(test on webpage, don't in e-mail notification)

There have already been several threads about this since the implementation of CSSTree as a new parsing component.

**Comment by AnAccountForReportingBugs** [comment]
Sorry about that. I don’t do CSS that often and I must have misread the MDN CSS documents as those being equivalent filters. Probably confused an “and” with an “or” somewhere.

**Comment by krystian3w** [comment]
Most likely yes.

Now the only thing left to do is to wait whether gorhill will improve the filters manually, have the person who wrote them do it (I rather rule out that there is already ready a newer parser code independent of CSSTree and compatible with uBo Lite+Node JS or some api based on the "can I use" base).

**Comment by AnAccountForReportingBugs** [comment]
Your comment has exception rules and you said “unblocks” in the one previous. The originals I gave blocked elements. I think you might be confusing the rules I gave with two others in that set. I only point that out in case it affects the analysis at all. 

Somewhat ironically, if I am reading the README correctly, I believe those rules are disallowed anyway for not requiring uBO syntax.

**Comment by krystian3w** [comment]
I think it fits there, for the two rules above I usually use the word exception.

The syntax paradox in this case is that EasyList will not always remove or modify the filters that started as bait to activate the "ad blocking detected" messages.

**Comment by mapx-** [comment]
> Chrome 84

You should update your chrome

**Comment by dportvine** [comment]
Maybee need to upgrade a `minimum_chrome_version`?
https://github.com/gorhill/uBlock/blob/e23f0bd7d5d97c2b7fbcca96e77b26cb78b834d6/platform/chromium/manifest.json#L77

**Comment by AnAccountForReportingBugs** [comment]
Well, if you want to fix this one, inverting the not with DeMorgan’s law should work. I am not in a place to test it but :is(:not(div), :not(.adsbygoogle)) should be equivalent to the implicit and of :not(div.adsbygoogle).

**Comment by krystian3w** [comment]
But incompatible with Chromium 73-87: https://caniuse.com/?search=%3Ais requires the inclusion of an experimental wen platform or the use of an obsolete name.

**Comment by gorhill** [comment]
I am going to raise the minimum version to ensure CSS4  `:not()` is supported. Whoever wants to use vastly out of date browser versions shouldn't have issue using vastly out of data uBO.
