### ISSUE TITLE
ordertrack.it.att.com: breakage

### ISSUE THREAD

**Issue by debragcar** [uBlockOrigin/uAssets#17472]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ordertrack.it.att.com/ordertrack/dfOrderSearch.action`

### Category

breakage

### Description

broke the page. not loading properly and i dont see a way to put that site on a safe list in the extension. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 108
filterset (summary): 
  network: 89526
  cosmetic: 39666
  scriptlet: 17578
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65159-46, 2h.19m
    easyprivacy: 30782-1177, 2h.18m
    plowe-0: 3753-936, 2h.17m
    ublock-abuse: 78-0, 2h.15m
    ublock-badware: 6427-119, 2h.13m
    ublock-filters: 33385-97, 2h.12m
    ublock-privacy: 302-2, 2h.11m
    ublock-quick-fixes: 486-131, 2h.10m
    ublock-unbreak: 1964-44, 2h.9m
    urlhaus-1: 7165-0, 2h.8m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2375 ms
  maxAssetCacheWait: 22 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    att.com: 7
```
</details>

**Comment by debragcar** [comment]
im not an IT person but need to know how to exclude that site from ublock filtering

**Comment by liamengland1** [comment]
This site is not resolving, not a uBo issue

**Comment by mapx-** [comment]
yeah, it seems down, but this EP filter will break it:

`/ordertrack/*`

@debragcar can you test

`/ordertrack/*$badfilter`

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17472#issuecomment-1499786241 -
https://github.com/gorhill/uBlock/wiki/Dashboard:-Trusted-sites

And put:

`https://ordertrack.it.att.com/ordertrack/dfOrderSearch.action`

Similar works: https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button
