### ISSUE TITLE
linkvertise.com: breakage

### ISSUE THREAD

**Issue by Hoangnguyen72628** [uBlockOrigin/uAssets#17474]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/530799/fluxus-android-free2/1`

### Category

[unknown]

### Description

It didn't appear free access and it still no working. Please resolve this issue. Thank you.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium Mobile: 111
filterset (summary): 
  network: 91611
  cosmetic: 31010
  scriptlet: 17736
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1873-15, 23h.2m
    adguard-mobile: 8713-33, 23h.8m
    easylist: 65159-16896, 23h.7m
    easyprivacy: 30782-1189, 23h.6m
    plowe-0: 3751-1020, 5d.22h.42m
    ublock-abuse: 78-0, 5d.22h.40m
    ublock-badware: 6295-125, 23h.5m
    ublock-filters: 33584-344, 23h.4m
    ublock-privacy: 302-3, 5d.22h.35m
    ublock-quick-fixes: 477-130, 23h.1m
    ublock-unbreak: 1952-44, 23h.3m
    urlhaus-1: 7368-0, 23h
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  colorBlindFriendly: true
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4430 ms (selfie)
  maxAssetCacheWait: 729 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googletagmanager.com: 1
    media.net: 1
    taboola.com: 2
    thinksuggest.org: 2
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
> It didn't appear free access and it still no working

I see "free access" on page. What does not work ? 

Test using FF mobile (supported by uBO) not chromium mobile
