### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by ElementShadow** [uBlockOrigin/uAssets#17479]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/equartofficial`

### Category

ads

### Description

i see twitch ad 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2](https://user-images.githubusercontent.com/73000483/230581282-a531675f-7e7a-4d28-bcce-ef2b62ed6dd9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 106392
  cosmetic: 60740
  scriptlet: 18797
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 39579-12, 1m
    easylist: 65103-63, never
    easyprivacy: 30755-1283, never
    plowe-0: 3751-940, never
    ublock-abuse: 78-1, never
    ublock-badware: 6217-114, never
    ublock-filters: 33203-127, never
    ublock-privacy: 302-2, never
    ublock-quick-fixes: 462-20, never
    ublock-unbreak: 1945-42, never
    urlhaus-1: 7324-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 406 ms
  maxAssetCacheWait: 195 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    google-analytics.com: 1
    imrworldwide.com: 1
    scorecardresearch.com: 3
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
