### ISSUE TITLE
babelwuxia.com: detection

### ISSUE THREAD

**Issue by fatotak** [uBlockOrigin/uAssets#17483]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://babelwuxia.com/project/`

### Category

detection

### Description

"Adblocker detected, powered by chpadblock" prevents usage of the site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 88453
  cosmetic: 22642
  scriptlet: 17576
  html: 946
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34284-397, 6m
    ublock-badware: 6437-5, 6m
    ublock-privacy: 352-1, 6m
    ublock-abuse: 78-0, 6m
    ublock-unbreak: 1975-3, 6m
    ublock-quick-fixes: 489-0, 6m
    easylist: 63613-17424, 6m
    easyprivacy: 30792-1772, 6m
    urlhaus-1: 7631-0, 6m
    plowe-0: 3750-2, 6m
filterset (user): [empty]
modifiedUserSettings: 
  ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 347 ms (selfie)
  maxAssetCacheWait: 62 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    googlesyndication.com: 5
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
test

```
babelwuxia.com##+js(noeval-if, ads)
babelwuxia.com##*:matches-attr("id"="/[\w]{50,}/")
```

sometimes I get breakages even disabling uBO
