### ISSUE TITLE
[nsfw] bokepid.wiki: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#17487]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bokepid.wiki/juq-171-subindo-dihukum-lembur-berhadiah-ngentot/`

### Category

ads

### Screenshot(s)
NSFW
<details>

<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/98657967/230630204-3a23b251-f6be-4b79-987c-3a843d3fab0c.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 113
filterset (summary): 
  network: 100153
  cosmetic: 118698
  scriptlet: 23781
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7656-7, 27m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 77-4, 26m
    IDN-0: 5440-346, 29m
    fanboy-annoyance: 80843-369, 33m
    fanboy-cookiemonster: 46522-46522, 32m
    ublock-annoyances: 4917-80, 25m
  default: 
    user-filters: 11-0, never
    easylist: 65300-57, 28m
    easyprivacy: 30788-1179, 34m
    ublock-abuse: 78-0, 31m
    ublock-badware: 6438-120, 25m
    ublock-filters: 33409-262, 25m
    ublock-privacy: 302-7, 30m
    ublock-quick-fixes: 488-132, 24m
    ublock-unbreak: 1964-49, 24m
    urlhaus-1: 7631-0, 24m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3283 ms (selfie)
  maxAssetCacheWait: 496 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    clarity.ms: 1
    histats.com: 2
    juicyads.com: 10
    jwpltx.com: 1
    realsrv.com: 1
    wp.com: 1
    yandex.ru: 1
```
</details>

**Comment by mapx-** [comment]
add

`||bokepid.wiki/*.gif$image`

report at https://github.com/ABPindo

**Comment by stephenhawk8054** [comment]
@gmarcher Sorry, can you check this?

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/commit/7e7b547ee151fee4ceb2dd5eca250ce5ab76574d
