### ISSUE TITLE
top.gg: breakage

### ISSUE THREAD

**Issue by MandiYang** [uBlockOrigin/uAssets#17482]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://top.gg/bot/555955826880413696/vote`

### Category

breakage

### Description

Waits forever to vote, need to reload the tab a few times before it works.

UPDATE: It doesn't break often.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 160541
  cosmetic: 43067
  scriptlet: 18683
  html: 961
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1912-0, 23h.22m
    curben-phishing: 69361-32, 23h.22m
    SWE-1: 4383-2, 23h.22m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34250-178, 23h.22m
    ublock-badware: 6310-10, 23h.22m
    ublock-privacy: 352-1, 23h.22m
    ublock-abuse: 78-0, 23h.22m
    ublock-unbreak: 1970-3, 23h.22m
    ublock-quick-fixes: 487-0, 23h.22m
    easylist: 65252-618, 23h.22m
    easyprivacy: 30787-1780, 23h.22m
    urlhaus-1: 7165-0, 23h.22m
    plowe-0: 3753-3, 23h.22m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1349 ms (selfie)
  maxAssetCacheWait: 412 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    top.gg: 2
    googletagmanager.com: 1
    lngtd.com: 1
```
</details>

**Comment by iam-py-test** [comment]
Can you disable all non-default lists (Phishing URL Blocklist, Anti-paywall filters) and retest?

**Comment by mapx-** [comment]
You just have to follow the indications

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
