### ISSUE TITLE
pcgamestorrents.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#17481]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pcgamestorrents.com/supplice.html`

### Category

ads

### Description

ads

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/230612926-18972f10-4969-4c87-895a-0ac96a05a2c7.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 125812
  cosmetic: 69428
  scriptlet: 18950
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39572-166, 23h.52m
  default: 
    user-filters: 0-0, never
    FRA-0: 28892-33, 23h.52m
    easylist: 65160-119, 23h.52m
    easyprivacy: 30788-1577, 23h.52m
    plowe-0: 3753-965, 23h.52m
    ublock-abuse: 78-2, 23h.52m
    ublock-badware: 6301-144, 23h.52m
    ublock-filters: 33379-217, 23h.52m
    ublock-privacy: 302-2, 23h.52m
    ublock-quick-fixes: 486-131, 23h.52m
    ublock-unbreak: 1959-48, 23h.52m
    urlhaus-1: 7165-0, 23h.52m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 664 ms (selfie)
  maxAssetCacheWait: 121 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    a-ads.com: 2
    decreertenet.website: 2
    dephasevittate.com: 2
    galeaeevovae.com: 2
    gamingadult.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
add
`pcgamestorrents.com##[href^="https://startgAming.net/tienda/suscripcion-premium/"]`
