### ISSUE TITLE
[nsfw] yabaisub.com: detection

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#17488]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yabaisub.com/2022/11/08/mide-847-kana-kusakabe-sub-indonesia/`

### Category

detection

### Description

![image](https://user-images.githubusercontent.com/98657967/230634124-151e0d5f-cf81-4757-9ede-2f91c1e27a40.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.4
Chromium: 113
filterset (summary): 
  network: 100153
  cosmetic: 118698
  scriptlet: 23781
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7656-7, 51m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 77-4, 50m
    IDN-0: 5440-346, 53m
    fanboy-annoyance: 80843-369, 57m
    fanboy-cookiemonster: 46522-46522, 56m
    ublock-annoyances: 4917-80, 49m
  default: 
    user-filters: 11-0, never
    easylist: 65300-57, 52m
    easyprivacy: 30788-1179, 58m
    ublock-abuse: 78-0, 55m
    ublock-badware: 6438-120, 49m
    ublock-filters: 33409-262, 48m
    ublock-privacy: 302-7, 54m
    ublock-quick-fixes: 488-132, 48m
    ublock-unbreak: 1964-49, 48m
    urlhaus-1: 7631-0, 48m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3283 ms (selfie)
  maxAssetCacheWait: 496 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    2d12b2f25b.com: 1
    cdnstatic01.xyz: 1
    dalyai.com: 1
    go6shde9nj2itle.com: 2
    googletagmanager.com: 1
    wpadmngr.com: 1
    yandex.ru: 1
```
</details>

**Comment by Procyon-b** [comment]
Like okiehsch, I can't reproduce with your settings. (I can if I add my regional list)
The problem could be with one of your user filters. Try without them. Go to the "Filter lists" tab, uncheck "My filters", click "Apply changes". Test again.

If it still doesn't work, try disabling cosmetic filters on this site. Open ublock's popup menu, click the "eye" icon to disable and reload the page.

**Comment by iam-py-test** [comment]
You have 6 non-default filterlists and one default list disabled. Please reset uBo to default settings.
