### ISSUE TITLE
twitch.tv: detection

### ISSUE THREAD

**Issue by adyh91765** [uBlockOrigin/uAssets#17484]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/`

### Category

detection

### Description

ublock bloque mon twitch

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 109313
  cosmetic: 48462
  scriptlet: 17678
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    FRA-0: 28892-33, 23h.31m
    easylist: 65159-102, 23h.30m
    easyprivacy: 30787-1484, 23h.29m
    plowe-0: 3752-960, 5d.20m
    ublock-abuse: 78-1, 23h.28m
    ublock-badware: 6301-144, 23h.27m
    ublock-filters: 33379-188, 23h.26m
    ublock-privacy: 302-2, 23h.25m
    ublock-quick-fixes: 488-131, 3h.35m
    ublock-unbreak: 1959-48, 23h.24m
    urlhaus-1: 7679-0, 3h.34m
filterset (user): [array of 1 redacted]
trustedset: 
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 18763 ms (selfie)
  maxAssetCacheWait: 1445 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    twitch.tv: 1
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    google-analytics.com: 1
    imrworldwide.com: 1
    scorecardresearch.com: 5
    sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5184
