### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by PolatAlemdar121** [uBlockOrigin/uAssets#17489]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bild.de/`

### Category

detection

### Description

"https://www.bild.de" recognizes "uBlockOrigin" and does not display content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 91402
  cosmetic: 43953
  scriptlet: 17419
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6707-0, 1d.23h.15m
    easylist: 65381-52, 5d.5h
    easyprivacy: 30754-1184, 5d.5h.1m
    plowe-0: 3751-936, 11d.8h.43m
    ublock-abuse: 78-0, 11d.8h.45m
    ublock-badware: 6217-114, 5d.4h.58m
    ublock-filters: 33211-111, 5d.4h.57m
    ublock-privacy: 295-2, 11d.8h.46m
    ublock-unbreak: 1944-42, 5d.4h.59m
    urlhaus-1: 7056-0, 1d.23h.16m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 479 ms (selfie)
  maxAssetCacheWait: 237 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    bild.de: 4
    cxense.com: 1
    ioam.de: 1
    kameleoon.eu: 1
```
</details>

**Comment by okiehsch** [comment]
Update your filter lists.
