### ISSUE TITLE
[nsfw] twitch.tv: ads

### ISSUE THREAD

**Issue by tahalperen** [uBlockOrigin/uAssets#17480]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/levo`

### Category

ads

### Description

#it doesn't work anymore in twitch

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 91448
  cosmetic: 48782
  scriptlet: 18842
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 3-2, never
    TUR-0: 12164-11, 3h.40m
    easylist: 65159-64, 3h.36m
    easyprivacy: 30764-1182, 4d.1h.3m
    plowe-0: 3753-937, 3h.41m
    ublock-abuse: 78-0, 4d.23h.32m
    ublock-badware: 6433-119, 3h.39m
    ublock-filters: 33378-104, 3h.38m
    ublock-privacy: 302-2, 4d.23h.31m
    ublock-quick-fixes: 485-131, 1d.2h.17m
    ublock-unbreak: 1959-44, 3h.37m
    urlhaus-1: 7368-0, 1d.2h.18m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 289 ms (selfie)
  maxAssetCacheWait: 98 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    twitch.tv: 1
    amazon-adsystem.com: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    imrworldwide.com: 1
    scorecardresearch.com: 2
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
