### ISSUE TITLE
marmiton.org: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#17497]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.marmiton.org/recettes/recherche.aspx?aqt=poulet-bananes`

### Category

nuisance

### Description

empty frames

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/230711143-74409978-7eed-463d-809d-2d0bd106af22.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 125031
  cosmetic: 69510
  scriptlet: 18963
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39585-166, 31m
  default: 
    user-filters: 0-0, never
    FRA-0: 28945-33, 31m
    easylist: 63835-192, 31m
    easyprivacy: 30787-1577, 30m
    plowe-0: 3750-966, 30m
    ublock-abuse: 78-2, 30m
    ublock-badware: 6465-139, 30m
    ublock-filters: 33413-210, 30m
    ublock-privacy: 302-2, 30m
    ublock-quick-fixes: 490-133, 30m
    ublock-unbreak: 1965-48, 30m
    urlhaus-1: 7597-0, 30m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 665 ms (selfie)
  maxAssetCacheWait: 91 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    unifygroup.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||marmiton.org/adLogo.svg$image
marmiton.org#?#[data-ad-sticky-reference] + div:-abp-has(.ad-title)
```

@smed79

**Comment by mapx-** [comment]
report here:
https://github.com/easylist/listefr/issues
