### ISSUE TITLE
doge25.in: detection

### ISSUE THREAD

**Issue by apkmodz** [uBlockOrigin/uAssets#17492]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://doge25.in/auto/block/`

### Category

detection

### Description

detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium Mobile: 111
filterset (summary): 
  network: 95403
  cosmetic: 31071
  scriptlet: 17653
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    IDN-0: 5440-235, 3d.29m
    adguard-mobile: 8714-36, 1d.12h.50m
    easylist: 65121-16892, 2d.25m
    easyprivacy: 30772-1189, 3d.19h.57m
    plowe-0: 3753-1020, 15h.6m
    ublock-abuse: 78-0, 22h.10m
    ublock-badware: 6427-120, 23h.30m
    ublock-filters: 33589-354, 23h.29m
    ublock-privacy: 302-3, 22h.9m
    ublock-quick-fixes: 490-133, 15h.5m
    ublock-unbreak: 1969-47, 17h.27m
    urlhaus-1: 7679-0, 14h.59m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5101 ms (selfie)
  maxAssetCacheWait: 778 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-5558179
