### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by phcza** [uBlockOrigin/uAssets#17494]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bild.de`

### Category

detection

### Description

Test

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox Mobile: 111
filterset (summary): 
  network: 93493
  cosmetic: 33856
  scriptlet: 17637
  html: 976
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34372-302, 3d.23h.24m
    ublock-badware: 6242-10, 2d.14h.27m
    ublock-privacy: 344-1, 11d.12h.6m
    ublock-abuse: 78-0, 9d.12h.40m
    ublock-unbreak: 1963-2, 2d.22h.2m
    ublock-quick-fixes: 475-1, 9h.11m
    adguard-mobile: 8711-128, 2d.19h.2m
    easylist: 65145-17454, 2d.14h.26m
    easyprivacy: 30787-1787, 2d.9h.39m
    urlhaus-1: 7631-0, 9h.12m
    plowe-0: 3751-2, 10d.16h.24m
    DEU-0: 6719-388, 1d.54m
filterset (user): [empty]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1106 ms (selfie)
  maxAssetCacheWait: 137 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    bild.de: 1
    cxense.com: 1
    ioam.de: 1
    iocnt.net: 1
    kameleoon.eu: 1
```
</details>

**Comment by mapx-** [comment]
> I forced an update of my filter lists.

You didn't.
