### ISSUE TITLE
surveymonkey.com: breakage

### ISSUE THREAD

**Issue by DrusTheAxe** [uBlockOrigin/uAssets#17491]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.surveymonkey.com/r/GZHD2W8`

### Category

breakage

### Description

Click on the Next button after filling out the form and it brings me back to the same page. Nothing noted as 'you missed a required input' just stuck Groundhog Day'ing it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 89772
  cosmetic: 39671
  scriptlet: 17573
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65121-46, 3d.8h.41m
    easyprivacy: 30788-1177, 1d.19h.14m
    plowe-0: 3751-936, 11d.6h.48m
    ublock-abuse: 78-0, 11d.6h.50m
    ublock-badware: 6259-124, 3d.8h.44m
    ublock-filters: 33280-98, 3d.8h.43m
    ublock-privacy: 295-2, 11d.6h.51m
    ublock-quick-fixes: 488-16, 6h.42m
    ublock-unbreak: 1945-42, 3d.8h.42m
    urlhaus-1: 7631-0, 6h.41m
filterset (user): [empty]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 199 ms (selfie)
  maxAssetCacheWait: 68 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 1
    signalfx.com: 4
```
</details>

**Comment by mapx-** [comment]
> Click on the Next button after filling out the form and it brings me back to the same page

just after the first page or after all the survey pages ?
