### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by Flicker0931** [uBlockOrigin/uAssets#17493]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bilibili.com/?spm_id_from=..0.0`

### Category

breakage

### Description

CPU usage is very high when open uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 95
filterset (summary): 
  network: 107228
  cosmetic: 50470
  scriptlet: 17717
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/CN.txt: 782-0, 22h.52m
  default: 
    user-filters: 1-0, never
    CHN-0: 27387-108, 22h.53m
    easylist: 65302-99, 22h.49m
    easyprivacy: 30792-1206, 22h.54m
    plowe-0: 3750-939, 14h.52m
    ublock-abuse: 78-0, 21h.27m
    ublock-badware: 6433-119, 22h.50m
    ublock-filters: 33399-112, 22h.48m
    ublock-privacy: 302-4, 22h.57m
    ublock-quick-fixes: 488-132, 22h.46m
    ublock-unbreak: 1964-45, 22h.51m
    urlhaus-1: 7679-0, 22h.47m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2011 ms (selfie)
  maxAssetCacheWait: 150 ms
popupPanel: 
  blocked: 60
  no-cosmetic-filtering: true
  no-scripting: true
  blockedDetails: 
    bilibili.com: 10
    gwdang.com: 1
    hdslb.com: 49
```
</details>

**Comment by mapx-** [comment]
You should remove non-default lists `AdditionalFiltersCN`, reset uBO to default settings, update your chrome

I guess the bad filter is
`||hdslb.com/bfs/seed/log/`

You can kill it adding:
`||hdslb.com/bfs/seed/log/$badfilter`
