### ISSUE TITLE
ban.dark-gaming.com: breakage

### ISSUE THREAD

**Issue by Twofoursixeight2468** [uBlockOrigin/uAssets#17498]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ban.dark-gaming.com/`

### Category

breakage

### Description

When you load this specific website, an error message will occur.
Turning off the extension removes the error.
Note that the application only works when a number is inserted.
https://ban.dark-gaming.com/1 for example, will display the error "Your browser seems to be blocking some urls required for this application" but turning it off will display the ban details.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

When the blocker is off:
![Screenshot 2023-04-08 1 42 56 AM](https://user-images.githubusercontent.com/105664499/230712421-bfcb0f09-88fb-4323-a555-ac9e582eae91.png)
When the blocker is on:
![Screenshot 2023-04-08 1 42 38 AM](https://user-images.githubusercontent.com/105664499/230712425-b79abdb7-f848-4fc1-9170-31c63f340ca2.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 103
filterset (summary): 
  network: 88610
  cosmetic: 39722
  scriptlet: 17580
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63835-46, 2h.6m
    easyprivacy: 30791-1177, 2h.4m
    plowe-0: 3750-937, 2h.3m
    ublock-abuse: 78-0, 2h.1m
    ublock-badware: 6433-119, 1h.59m
    ublock-filters: 33400-91, 1h.58m
    ublock-privacy: 302-2, 1h.57m
    ublock-quick-fixes: 488-132, 1h.56m
    ublock-unbreak: 1964-44, 1h.55m
    urlhaus-1: 7597-0, 1h.54m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 21715 ms (selfie)
  maxAssetCacheWait: 1087 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    lr-ingest.io: 2
```
</details>

**Comment by Twofoursixeight2468** [comment]
Note that I am running a old chrome version. This is an old device.
This applies to every ban.dark-gaming.com link.

**Comment by Daxy7** [comment]
Allowing `||lr-ingest.io^$3p` from `EasyPrivacy` fixed it as it needed to call 
```
https://r.lr-ingest.io/i?a=drcjix/ban-manager&r=5-3dadc750-c6ec-45a1-84f8-c678a677d7e6&t=851d465a-f34c-41ab-a158-4b6e87f8f211&s=0&rs=0,t&u=2793f4d3-3749-456a-a49f-175689996899&is=1
```
 XHR script

Account required `You are not authorized to view this page. [Login]`

**Comment by stephenhawk8054** [comment]
This works for me but I can only check with logged out status. Does this work for you when logging in?

```adb
dark-gaming.com##+js(no-xhr-if, lr-ingest.io)
```

**Comment by Twofoursixeight2468** [comment]
Note tht you ne

> This works for me but I can only check with logged out status. Does it work for you when logging in?
> 
> ```
> dark-gaming.com##+js(no-xhr-if, lr-ingest.io)
> ```

I am referring to links like https://ban.dark-gaming.com/x where x is any number. I cannot login to main page, this is due to the fact that I don't moderate Dark Gaming. This is not an extension issue. 

ban.dark-gaming.com/1 will display said errors in proof. These have no login pages.
