### ISSUE TITLE
tv4play.se: detection

### ISSUE THREAD

**Issue by Gangst3rn** [uBlockOrigin/uAssets#17508]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tv4play.se/program/robinson/robinson-gr%C3%A4nslandet-del-8-s%C3%A4song-12/13815061?offset=21`

### Category

detection

### Description

it detects ublock and makes the content unplayable

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 106
filterset (summary): 
  network: 84623
  cosmetic: 41236
  scriptlet: 17141
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    SWE-1: 4348-0, 94d.11h.40m
    easylist: 61358-53, 94d.10h.50m
    easyprivacy: 30878-1177, 94d.10h.49m
    plowe-0: 3672-900, 103d.3h.36m
    ublock-abuse: 77-0, 103d.3h.38m
    ublock-badware: 4224-111, 94d.11h.38m
    ublock-filters: 31563-124, 94d.11h.39m
    ublock-privacy: 260-1, 103d.3h.37m
    ublock-quick-fixes: 499-15, 73d.10h.45m
    ublock-unbreak: 1911-43, 94d.10h.55m
    urlhaus-1: 6797-0, 91d.9h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 28 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2003 ms
  maxAssetCacheWait: 1059 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    tv4play.se: 1
    bugsnag.com: 1
    cookielaw.org: 1
    imrworldwide.com: 1
    videoplaza.tv: 1
    youborafds01.com: 1
```
</details>

**Comment by Sopor** [comment]
I get this when i try to use uBo

![image](https://github.com/uBlockOrigin/uAssets/assets/5789283/eb543b01-7990-4d4a-b8ea-db6e432fe6df)

**Comment by stephenhawk8054** [comment]
@Sopor Which browser are you using?

**Comment by stephenhawk8054** [comment]
The site shows anti-adb even when I don't use any extensions: https://github.com/uBlockOrigin/uAssets/assets/66517106/e8541a3c-bc85-4630-8f4b-f2d23e03e9e8

**Comment by stephenhawk8054** [comment]
@lassekongo83 Sorry can you check if you can reproduce the issue here: https://github.com/uBlockOrigin/uAssets/issues/17508#issuecomment-1685128094 ?

**Comment by lassekongo83** [comment]
Can't reproduce on my end. It may be triggered if `videoplaza.tv` is blocked either with another extension or a DNS blocker.

**Comment by lassekongo83** [comment]
Is the Swedish filter activated?

**Comment by Sopor** [comment]
Swedish filter is not activated.

It seems to be Easylist that is blocking `videoplaza.tv`.

I haven't made any changes to uBo.

I installed uBo on  Firefox and i'm only using this web browser to test detection.

I uninstalled uBo and reinstalled it and Easylist is enabled by default.

<details><summary>Logger output</summary>

```
+12
||youborafds01.com^
--
www.tv4play.se
3
get
xhr
https://a-fds.youborafds01.com/data?outputformat=json&system=mtvoy&pluginVersion=6.8.28-adapterless-js&requestNumber=0.515046557677175&username=34775513&timemark=1692834307659
```
```
+7
||youborafds01.com^
--
www.tv4play.se
3
get
xhr
https://a-fds.youborafds01.com/data?outputformat=json&system=mtvoy&pluginVersion=6.8.28-adapterless-js&requestNumber=0.515046557677175&username=34775513&timemark=1692834307659
```
```
+2
||videoplaza.tv^
--
www.tv4play.se
3
get
xhr
https://se-tv4.videoplaza.tv/proxy/distributor/v2?s=TV4Play%2FTV-Serier%2FThe+White+Queen&t=long_form%2CTV4Play%2CTV-Serier%2CThe+White+Queen%2CThe+White+Queen+del+1+-+In+Love+with+the+King%2C%2CNordicPlayer&f=long_form&cf=long_form&rt=vast_2.0&vbw=8000&vwt=1920&vht=1080&afr=0&trs=https&dcid=d918a1f3-0bcc-438b-a205-b2a87ad0daf6&tt=pa&obp=0&st=0%3A0%2C20%3A1&pid=34775513&gdpr=1&gdpr_consent=CPxAgDsPxAgDsAcABBENDTCsAP_AAAAAAChQJDwMwAEQAKAAsACAAFQALgAZAA8ACAAGQANAAiQBNAE8ALYAXwAxABuADmAICAQQBBgCFAEYAJgAUoA0QB-gEIAIiARYAjoBOACsgFzAMCAYoA2wB2wEyAKTAWGAvMBlgDdwHCAOIAcuA6uCN4I5gR1gjuCPkEfgSCgkICQ4AAACwkBEABAACwAKgAZAA8ACAAGQANAAiABPADmAKUAfoBcwDFALzAcuGAAgBPEAAQAnjgA4ACAALgBfAIQAREArICkx0BUABYAFQAMgAgABkADQAIgATwAxABzAEwAKUAaIA_QCLAFzAMUAmQBeYDLAHLkAAgACAAvgFZAUmQgCgALAAyAGIAuYBiiUAcABAACwAMgBEADEAYoBeZIAIABcAL4BWQFJlICIACwAKgAZABAADQAIgATwAxABzAFKANEAfoBFgC5gGKAXmA5coAEAAuAF8ArIB2wA.f_gAAAAAAAAA
```
```
+2
||youborafds01.com^
--
www.tv4play.se
3
get
xhr
https://a-fds.youborafds01.com/data?outputformat=json&system=mtvoy&pluginVersion=6.8.28-adapterless-js&requestNumber=0.515046557677175&username=34775513&timemark=1692834307659
```
```
+2
||imrworldwide.com^
--
www.tv4play.se
3
get
script
https://cdn-gl.imrworldwide.com/conf/P72755BF3-0E83-4549-B6A7-5D2688403B1A.js#name=nlsnInstance&ns=NOLBUNDLE
```
```
+2
www.tv4play.se
3
get
xhr
https://playback2.a2d.tv/play/d8a087942784c170467f?service=tv4play&device=browser&protocol=hls%2Cdash&drm=widevine&browser=MozillaFirefox&capabilities=live-drm-adstitch-2%2Cyospace3
```
```
+2
www.tv4play.se
3
post
xhr
https://a1110.dscr.akamai.net/
aliasURL=https://client-gateway.tv4.a2d.tv/graphql
```
```
+2
www.tv4play.se
3
post
xhr
https://client-gateway.tv4.a2d.tv/graphql
```
```
+2
www.tv4play.se
3
get
xhr
https://a1110.dscr.akamai.net/
aliasURL=https://client-gateway.tv4.a2d.tv/graphql?operationName=AutoPlay&variables=%7B%22episodeId%22%3A%22d8a087942784c170467f%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22180e5c121074d08be9b4e1638a36c6d45be76d37c3686c02fdb11eaaaff4bc0e%22%7D%7D
```
```
+2
www.tv4play.se
3
get
xhr
https://client-gateway.tv4.a2d.tv/graphql?operationName=AutoPlay&variables=%7B%22episodeId%22%3A%22d8a087942784c170467f%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22180e5c121074d08be9b4e1638a36c6d45be76d37c3686c02fdb11eaaaff4bc0e%22%7D%7D
```
```
+2
www.tv4play.se
3
get
xhr
https://a1110.dscr.akamai.net/
aliasURL=https://client-gateway.tv4.a2d.tv/graphql?operationName=Video&variables=%7B%22id%22%3A%22d8a087942784c170467f%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%224dcea324c293625422404f91d2db35b64a3a573ee846be66b40af6fc22711816%22%7D%7D
```
```
+2
www.tv4play.se
3
get
xhr
https://client-gateway.tv4.a2d.tv/graphql?operationName=Video&variables=%7B%22id%22%3A%22d8a087942784c170467f%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%224dcea324c293625422404f91d2db35b64a3a573ee846be66b40af6fc22711816%22%7D%7D
```
```
+2
||bugsnag.com^$3p
--
www.tv4play.se
3
post
xhr
https://sessions.bugsnag.com/
```
```
+0
www.tv4play.se
1
get
script
https://www.tv4play.se/_next/static/chunks/pages/min-lista-8f6b06b226270e9a.js
```
</details>

**Comment by stephenhawk8054** [comment]
@Sopor Can you enable Swedish list and test again?

**Comment by Sopor** [comment]
I enabled `Frellwit's Swedish Filter` and now it is working. No detection. 👍

**Comment by Sopor** [comment]
I have always been told to run uBo with default filters when reporting a detection.

So, it is a bit weird that i now should enable one that isn't default.

Should i have this enabled in the future when reporting detection?

**Comment by stephenhawk8054** [comment]
For sites with languages other than English, sometimes you'll need the filter lists dedicated to that language if you run into issue.

But if your browser is set to that language, when installing uBO, it will automatically enable that language's filter list by default and is considered one of the default lists.

**Comment by Sopor** [comment]
I see!

I always run everything in English including Windows.

That will explain why it didn't enable the Swedish filter list when i installed uBo.
