### ISSUE TITLE
Blocker failure.

### ISSUE THREAD

**Issue by fvwsedpgirepihg5r** [uBlockOrigin/uAssets#17506]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Your blocker icon has an exclamation mark on a yellow background. What is this problem and how to deal with it?

### URL(s) where the issue occurs.

The problem occurs on all sites.
![Снимок JPGсаиаикаит](https://user-images.githubusercontent.com/103879706/230740967-1d47140e-e240-4a72-905e-e12cfa547e64.JPG)

### Screenshot(s)

![Снимок JPGсаиаикаит](https://user-images.githubusercontent.com/103879706/230741306-27b98eab-9696-476c-8ad9-8670a83104ce.JPG)

### uBO version

uBlock Origin 1.48.4

### Browser name and version

111.0.1 (64-bit) Mozilla Firefox Browser.

### Settings

I didn't change anything. 

### Notes

I don't know how to fix this problem.
![Снимок JPGсаиаикаит](https://user-images.githubusercontent.com/103879706/230741403-3c606ea8-6d12-416a-b6d6-dcc6345a4071.JPG)

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/wiki/Toolbar-icon

**Comment by peace2000** [comment]
Hi, this place is for filter issues, that badge is related to uBlock itself.

For support, go either here: https://www.reddit.com/r/uBlockOrigin/
or here:
https://github.com/uBlockOrigin/uBlock-issues/discussions
