### ISSUE TITLE
dropbox.com: privacy

### ISSUE THREAD

**Issue by debsidian** [uBlockOrigin/uAssets#17507]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When logged into Dropbox (requires an account to test):

Unblocked content that requires uBO Assets: `www.dropbox.com/2/pap_event_logging/log_events`

Proposed fix: `||dropbox.com/*/log_events$xhr,1p,method=post,redirect-rule=nooptext`

This fix has a lot of narrowing (ie.`method`) and you might want to make it less narrow.

### URL(s) where the issue occurs.

`https://www.dropbox.com/home` (assumes user is logged-in)

### uBO version

1.48.4

### Browser name and version

FF 111

### Settings

- Default settings
- New FF profile

**Comment by stephenhawk8054** [comment]
@ryanbr
