### ISSUE TITLE
hdfilmcehennemi.life: ads

### ISSUE THREAD

**Issue by favorical** [uBlockOrigin/uAssets#17500]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hdfilmcehennemi.life/`

### Category

ads

### Description

reklam var

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89843
  cosmetic: 39662
  scriptlet: 17572
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    TUR-0: null
  default: 
    user-filters: 0-0, never
    easylist: 65160-46, 2d.2h.6m
    easyprivacy: 30767-1177, 3d.23h.5m
    plowe-0: 3751-936, 12d.22h.22m
    ublock-abuse: 78-0, 11h.49m
    ublock-badware: 6301-124, 2d.2h.5m
    ublock-filters: 33378-97, 2d.2h.4m
    ublock-privacy: 302-2, 10h.24m
    ublock-quick-fixes: 485-131, 11h.48m
    ublock-unbreak: 1959-44, 2d.2h.3m
    urlhaus-1: 7631-0, 11h.47m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 315 ms (selfie)
  maxAssetCacheWait: 84 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
Enable the regional turkish list.
