### ISSUE TITLE
dubz.co: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#17502]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dubz.co/video/ecee2f`

### Category

privacy

### Description

The page tracks video view impression by sending an `xhr` request to the domain `https://dubz.co/analytics/video/<video-id>`.

<details>

<summary>Relevant source section (for convenience)</summary>

```javascript
function trackVideoView() {
    $.ajax({
        url: "https://dubz.co/analytics/video/ecee2f",
        type: "GET",
        cache: false, // disable jQuery caching
        data: {
            // add a cache-busting parameter to the URL
            _cb: Date.now()
        },
    })
}
trackVideoView('');
```

</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.5b5
Firefox: 111
filterset (summary): 
 network: 207057
 cosmetic: 201278
 scriptlet: 39481
 html: 1109
listset (total-discarded, last-updated): 
 added: 
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 927-0, 23h.45m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 700-8, 23h.43m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2148-77, 23h.44m
  adguard-generic: 69648-5395, 2h.31m
  adguard-spyware-url: 974-167, 2h.28m
  block-lan: 46-0, 9d.6h.43m
  curben-phishing: 69622-32, 23h.42m
  curben-pup: 189-0, 12h.36m
  adguard-annoyance: 66226-5984, 2h.29m
  fanboy-annoyance: 81594-471, 8d.1h.42m
  ublock-annoyances: 4880-4, 2h.26m
  dpollock-0: 11349-470, 5d.10h.49m
  IDN-0: 5445-1, 2h.27m
 default: 
  user-filters: 45-0, never
  ublock-filters: 34285-194, 2h.30m
  ublock-badware: 6469-5, 2h.25m
  ublock-privacy: 352-2, 21h.41m
  ublock-abuse: 78-0, 21h.40m
  ublock-unbreak: 1975-4, 2h.32m
  ublock-quick-fixes: 491-0, 12h.35m
  easylist: 65121-778, 2d.9h.28m
  easyprivacy: 30787-1859, 2d.5h.27m
  urlhaus-1: 7631-0, 23h.46m
  plowe-0: 3750-2, 2h.33m
filterset (user): [array of 44 redacted]
hostRuleset: 
 added: [array of 81 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 colorBlindFriendly: true
 contextMenuEnabled: false
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 1417 ms (selfie)
 maxAssetCacheWait: 300 ms
popupPanel: 
 blocked: 2
 network: 
  googlesyndication.com: 1
  jquery.com: 1
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||dubz.co/analytics/
```

@ryanbr
