### ISSUE TITLE
[nsfw] id.javtiful.com: ads

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#17505]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://id.javtiful.com/video/22672/venx-164`

### Category

ads

### Description

![image](https://user-images.githubusercontent.com/98657967/230738087-d0f5688b-a952-41ef-b44f-f73f1645f453.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 114
filterset (summary): 
  network: 99911
  cosmetic: 118696
  scriptlet: 23781
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7656-7, 1d.4h.20m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 77-4, 1d.4h.19m
    IDN-0: 5440-346, 1d.4h.22m
    fanboy-annoyance: 80843-369, 1d.4h.26m
    fanboy-cookiemonster: 46522-46522, 1d.4h.25m
    ublock-annoyances: 4917-80, 1d.4h.18m
  default: 
    user-filters: 11-0, never
    easylist: 65300-57, 1d.4h.21m
    easyprivacy: 30788-1179, 1d.4h.28m
    ublock-abuse: 78-0, 1d.4h.24m
    ublock-badware: 6438-120, 1d.4h.18m
    ublock-filters: 33409-262, 1d.4h.18m
    ublock-privacy: 302-7, 1d.4h.23m
    ublock-quick-fixes: 485-132, 2h.16m
    ublock-unbreak: 1964-49, 1d.4h.18m
    urlhaus-1: 7389-0, 2h.15m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 2 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 100
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2764 ms (selfie)
  maxAssetCacheWait: 791 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    adxadserv.com: 1
    cloudflareinsights.com: 1
    fdelphaswcealifornica.com: 1
    googletagmanager.com: 1
    hhbypdoecp.com: 2
    nomorepecans.com: 1
    realsrv.com: 1
    xlivrdr.com: 1
```
</details>

**Comment by Linxgos** [comment]
Add `id.javtiful.com##.fs-7.p-1.v3sx.rounded-4.btn-danger.btn` to your filter list

**Comment by Bug-Cache** [comment]
![Image](https://github.com/user-attachments/assets/0e34899c-28a5-4b25-be5e-e8786fbb3753)
https://javtiful.com/video/80699/nima-051

```
name: uBlock Origin Lite
version: 2025.605.2042
browser: Chrome 137 (win)
filtering:
 site: optimal
 default: optimal
rulesets:
 ublock-filters
 easylist
 easyprivacy
 pgl
 ublock-badware
 urlhaus-full
 annoyances-cookies
 annoyances-overlays
 idn-0
```

**Comment by stephenhawk8054** [comment]
Enable "Complete" mode for this site in next uBOL version.
