### ISSUE TITLE
hulu.com: ads

### ISSUE THREAD

**Issue by jacob-more** [uBlockOrigin/uAssets#17504]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hulu.com/watch/18969ba4-e88d-4c72-b66a-32ae0bcc441d`

### Category

ads

### Description

Although most ads are still blocked, one specific ad for "the mccrispy" still seems to get through. This happens for all shows I have tried to watch, despite purging the cache and reloading the filters, as suggested in the prerequisites.

I haven't submitted a report here before so if I'm leaving anything important out, just let me know. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/50991557/230737701-e5867bb9-3400-4118-898a-a76e58604d64.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 200350
  cosmetic: 73067
  scriptlet: 31870
  html: 940
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 39181-4064, 3d.18h.47m
    adguard-generic: 69548-6063, 3d.18h.49m
    adguard-spyware-url: 969-5, 3d.18h.48m
    curben-phishing: 69622-32, 1d.46m
    curben-pup: 198-0, 1d.4h.59m
  default: 
    user-filters: 30-1, never
    ublock-filters: 34229-194, 3d.18h.52m
    ublock-badware: 6248-10, 3d.18h.51m
    ublock-privacy: 348-0, 9d.13h.1m
    ublock-abuse: 78-0, 14h.54m
    ublock-unbreak: 1958-0, 3d.18h.50m
    easylist: 65087-638, 3d.18h.53m
    easyprivacy: 30764-12540, 3d.18h.54m
    urlhaus-1: 7631-0, 1d.45m
    plowe-0: 3751-2, 11d.13h.16m
    ublock-quick-fixes: 486-1, 1d.9h.39m
filterset (user): [array of 30 redacted]
trustedset: 
  added: [array of 42 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2046 ms (selfie)
  maxAssetCacheWait: 355 ms
popupPanel: 
  blocked: 996
  blockedDetails: 
    hulu.com: 405
    conviva.com: 308
    demdex.net: 22
    imrworldwide.com: 1
    innovid.com: 1
    omtrdc.net: 112
    scorecardresearch.com: 147
```
</details>p

**Comment by Daxy7** [comment]
The adtidy custom list you added is allowing `@@||t2.hulu.com/*/adinteraction^$domain=player.hulu.com`
For ads can go through

**Comment by mapx-** [comment]
use only the default lists then test again

**Comment by liamengland1** [comment]
Test `||ads-a-darwin.hulustream.com^` - sometimes prerolls (non-SSAI) come from here

**Comment by stephenhawk8054** [comment]
> Test `||ads-a-darwin.hulustream.com^` - sometimes prerolls (non-SSAI) come from here. Probably won't help with mid-video ads, sometimes those get through uBO in my experience as well

That will cause breakages on the videos if I'm not mistaken.
