### ISSUE TITLE
linkvertise.com: breakage

### ISSUE THREAD

**Issue by tibe0124** [uBlockOrigin/uAssets#17516]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/530799/fluxus-android-free2/1`

### Category

breakage

### Description

Not working

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium Mobile: 111
filterset (summary): 
  network: 89665
  cosmetic: 29857
  scriptlet: 17663
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8713-32, 3d.4h.43m
    easylist: 63613-16890, 2d.5h.12m
    easyprivacy: 30782-1187, 3d.4h.47m
    plowe-0: 3753-1020, 3d.4h.48m
    ublock-abuse: 78-0, 7d.10h.16m
    ublock-badware: 6427-120, 2d.5h.11m
    ublock-filters: 33606-334, 2d.5h.10m
    ublock-privacy: 302-3, 8d.10h.20m
    ublock-quick-fixes: 496-132, 1d.35m
    ublock-unbreak: 1969-46, 2d.5h.9m
    urlhaus-1: 7389-0, 1d.36m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2963 ms (selfie)
  maxAssetCacheWait: 461 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    googletagmanager.com: 1
    media.net: 1
    taboola.com: 2
    thinksuggest.org: 2
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/17474

chromium mobile, try FF mobile
