### ISSUE TITLE
[nsfw] t66y.com: detection

### ISSUE THREAD

**Issue by chuyueye** [uBlockOrigin/uAssets#17513]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.t66y.com/htm_data/2304/20/5649169.html`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 106169
  cosmetic: 50044
  scriptlet: 17703
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 163-12, never
    CHN-0: 27356-105, 4d.14h.50m
    easylist: 65159-99, 2d.12h.21m
    easyprivacy: 30773-1196, 4d.14h.51m
    plowe-0: 3751-938, 13d.14h.12m
    ublock-abuse: 78-0, 2d.12h.22m
    ublock-badware: 6288-124, 4d.13h.10m
    ublock-filters: 33275-114, 4d.10h.27m
    ublock-privacy: 302-2, 2d.12h.23m
    ublock-quick-fixes: 485-16, 2d.12h.19m
    ublock-unbreak: 1947-43, 4d.14h
    urlhaus-1: 7165-0, 2d.12h.20m
filterset (user): [array of 163 redacted]
trustedset: 
  added: [array of 4 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1580 ms (selfie)
  maxAssetCacheWait: 317 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
test

`t66y.com##+js(acs, $, open)`
