### ISSUE TITLE
[nsfw] daemon-hentai.com: detection

### ISSUE THREAD

**Issue by Ruzz23** [uBlockOrigin/uAssets#17511]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.daemon-hentai.com/`

### Category

Site detection

### Description

The page detects the Ublock, I have performed a total cleaning of the browser leaving only remains Ublock and still detects it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

![Captura](https://user-images.githubusercontent.com/123111723/230767852-d2486191-2ef1-4361-9ceb-210005503f13.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 109
filterset (summary): 
  network: 91033
  cosmetic: 45332
  scriptlet: 17881
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63835-46, 1h.40m
    easyprivacy: 30799-1177, 1h.39m
    plowe-0: 3750-937, 1h.38m
    spa-0: 3561-11, 1h.43m
    spa-1: 5161-198, 1h.43m
    ublock-abuse: 78-0, 1h.36m
    ublock-badware: 6470-114, 1h.34m
    ublock-filters: 33415-126, 1h.34m
    ublock-privacy: 302-2, 1h.32m
    ublock-quick-fixes: 491-133, 1h.31m
    ublock-unbreak: 1967-47, 1h.30m
    urlhaus-1: 7389-0, 1h.29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4823 ms (selfie)
  maxAssetCacheWait: 114 ms
popupPanel: 
  blocked: 11
  blockedDetails: 
    amazon-adsystem.com: 1
    clicksfly.com: 1
    google-analytics.com: 2
    media.net: 1
    onesignal.com: 1
    quantserve.com: 1
    realsrv.com: 3
    wp.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me. Update the filter lists and test again and if you still have the issue test `daemon-hentai.com##+js(set, ExoVideoSlider, {})`

**Comment by stephenhawk8054** [comment]
I can reproduce on chromium, your filter works for me.

**Comment by Utkarshjadon** [comment]
How do i use this filter please help me , I am kinda of a newbie

**Comment by JobcenterTycoon** [comment]
The anti adblock got fixed 2 hours ago https://github.com/uBlockOrigin/uAssets/commit/f8568c332935d1770d0be3313941e864d0933858 the filter will be avaiable in a few hours as a auto update.
