### ISSUE TITLE
video.corriere.it: breakage

### ISSUE THREAD

**Issue by MolinengoLuigi** [uBlockOrigin/uAssets#17518]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Using uBlock on Firefox, with Italian regional custom list, any video player on video.corriere.it is broken: video is not played and it's not possibile to press pause/play/fullscreen.
If I disable uBlock extension everytinghing works fine.
On Chrome the problem doesn't appear.

I don't know hot to solve it. I've tried to exclude some blocking rules without success.

### URL(s) where the issue occurs.

```
https://video.corriere.it/
https://video.corriere.it/auto-la-famiglia-viene-inghiottita-una-voragine-piena-acqua-bollente/cfaa6948-d5dc-11ed-abda-87da1fb8b4f0
```

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 114715
  cosmetic: 130281
  scriptlet: 33365
  html: 946
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 69685-5330, 7h.30m
    adguard-mobile: 8746-98, 7h.29m
    fanboy-cookiemonster: 46490-195, 4d.23h.42m
  default: 
    user-filters: 11-0, never
    ublock-filters: 34290-187, 1d.6m
    ublock-badware: 6479-5, 1d.5m
    ublock-privacy: 352-0, 7h.33m
    ublock-abuse: 78-0, 7h.32m
    ublock-unbreak: 1977-3, 7h.31m
    ublock-quick-fixes: 492-0, 7h.26m
    easylist: 63835-645, 7h.28m
    easyprivacy: 30787-1778, 7h.27m
    urlhaus-1: 7389-0, 7h.25m
    plowe-0: 3752-2, 4d.23h.41m
    ITA-0: 13540-3, 7h.24m
filterset (user): [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 749 ms (selfie)
  maxAssetCacheWait: 202 ms
```
</details>

**Comment by mapx-** [comment]
Site issue in firefox, no issue with chrome.
I was able to get the video playing in FF only once in 20 tests even disabling uBO

**Comment by peace2000** [comment]
The video works fine on my end but if I enable Adguard base, the video won't start playing.

This whitelist rule seems to fix it for me @MolinengoLuigi, can you try this as well?

`@@||amazon-adsystem.com/aax2/apstag.js$script,domain=video.corriere.it`

**Comment by mapx-** [comment]
Tested again, nothing works on my end.

**Comment by dportvine** [comment]
Video works for me without **AdGuard Base** or without **EasyList**.
This rule is in **EasyList** `||amazon-adsystem.com^`. It didn't help `@@||amazon-adsystem.com/aax2/apstag.js$script,domain=video.corriere.it`
Gif - https://imgur.com/kP2i9uz
@MolinengoLuigi Try disabling AdGuard Base.

**Comment by peace2000** [comment]
Now @`@||amazon-adsystem.com/aax2/apstag.js$script,domain=video.corriere.it` doesn't help anymore on my end... `||amazon-adsystem.com^` is on Easylist but also on AG base and on Lowe's list. This site works oddly.

But I can still reproduce that enabling AG base breaks the video and disabling it fixes the video.
