### ISSUE TITLE
dev.miuiflash.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#17519]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.

### URL address of the web page

`https://dev.miuiflash.com/remix-how-the-react-framework-competes-with-next-js`

### Category

ads

### Description

ads

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/230786236-62a099f7-1d3c-474b-b62a-3077bc814eaa.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 124623
  cosmetic: 69527
  scriptlet: 18999
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39596-166, 5m
  default: 
    user-filters: 0-0, never
    FRA-0: 28934-33, 5m
    easylist: 64098-268, 5m
    easyprivacy: 30800-1577, 5m
    plowe-0: 3750-966, 5m
    ublock-abuse: 78-2, 5m
    ublock-badware: 6501-134, 5m
    ublock-filters: 33469-210, 5m
    ublock-privacy: 302-2, 5m
    ublock-quick-fixes: 374-22, 5m
    ublock-unbreak: 1969-47, 5m
    urlhaus-1: 6946-1, 5m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 718 ms (selfie)
  maxAssetCacheWait: 107 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    a-ads.com: 1
```
</details>

**Comment by mapx-** [comment]
no such ad on my end

**Comment by mapx-** [comment]
@x-R0b0T-x you still didn't learn to provide the original link ?
