### ISSUE TITLE
yandex.ru: uBlock modifies links in search results

### ISSUE THREAD

**Issue by Felix14-v2** [uBlockOrigin/uAssets#17512]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

As the title says, uBlock modifies links in search results (Yandex). Demo:

https://user-images.githubusercontent.com/75726196/230768840-fe4c5914-7479-4cac-a140-42ec4d153448.mp4

Disabling JavaScript for `yandex.ru` helps to avoid this issue, but it isn't a solution.

### A specific URL where the issue occurs.

yandex.ru

### Steps to Reproduce

1. Install uBO
2. Search something using yandex.ru
3. Try to copy any link
4. See the copied result

Perhaps this is browser-specific behavior.

### Expected behavior

uBO souldn't modify links in search results

### Actual behavior

uBO, well, modifies them

### Configuration

Default

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
It's better to discuss it here: https://forums.lanik.us/viewforum.php?f=102

Or here: https://github.com/easylist/ruadlist/issues/new

**Comment by Felix14-v2** [comment]
> > * [x]  uBO is the only extension.
> 
> @Felix14-v2 You should not use AdGuard alongside uBO.

I know, most of the time it is disabled, but I still have a lot of custom rules there that I haven't migrated to uBO yet.

**Comment by dimisa-RUAdList** [comment]
The problem was solved by subscribing to the filter [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters).
