### ISSUE TITLE
kimcartoon.me broken

### ISSUE THREAD

**Issue by supercoke** [uBlockOrigin/uAssets#1751]
### URL(s) where the issue occurs
**kimcartoon.me/Cartoon/Guardians-of-the-Galaxy-Season-3/Episode-1**
**kimcartoon.me/Cartoon/American-Dad-Season-14/Episode-7**
**kimcartoon.me/Cartoon/OK-K-O-Let-s-Be-Heroes-Commercial/Episode-52?id=80122**

### Describe the issue

ublock breaks any page with a video on it at kimcartoon.me

### Screenshot(s)

heres how it should look like **https://imgur.com/a/7sRdD**
heres how ublock breaks the site **https://imgur.com/a/BNRsr**

### Versions

- Browser/version: [56.0 (64bit)]
- uBlock Origin version: [1.15.18]

### Notes

its this line that breaks the site for me
||fghtem.com^$xmlhttprequest,redirect=nooptext,domain=kimcartoon.me
its in the first filter named ublock fllters

**Comment by okiehsch** [comment]
Works fine with the Firefox 59 which is the stable version, your version so you can either upgrade your browser or add
````
||fghtem.com^$xmlhttprequest,redirect=nooptext,domain=kimcartoon.me,badfilter
````
to your filter list.

**Comment by mapx-** [comment]
FF 56 is a buggy browser, update it to the last one.

**Comment by zaphodbeebblebrox** [comment]
Ads @mapx-

**Comment by uBlock-user** [comment]
Adguard Base Filter patched it, you can use that here too.

**Comment by zaphodbeebblebrox** [comment]
Ads @mapx-

**Comment by zaphodbeebblebrox** [comment]
It does not block everything on the page `kimcartoon.me`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8bced6496b1fc0c8a7e447775b2505d9ef6ea0ad

**Comment by uBlock-user** [comment]
> It does not block everything

what is not blocked ?

**Comment by zaphodbeebblebrox** [comment]
![image](https://user-images.githubusercontent.com/22801430/41253039-0d1c9a48-6d8d-11e8-9a11-c7f6732d5056.png)

**Comment by uBlock-user** [comment]
Those ads are not part of the ads that appear in the sidebar, so you would have to add another filter for that

`kimcartoon.me##[style*="width: 300px; height: 250px;"]`
