### ISSUE TITLE
spacepools.org subdomains broken

### ISSUE THREAD

**Issue by Dwynr** [uBlockOrigin/uAssets#1752]
### URL(s) where the issue occurs

`graft.spacepools.org, api.graft.spacepools.org, dero.spacepools.org, etc.. (I can provide a full list of subdomains when needed.`

### Describe the issue

All subdomains in the pattern of .spacepools. get blocked even though there is nothing malicious on the site.

### Screenshot(s)

That's how it looks for example when our CDN subdomain gets blocked: https://i.dwynr.io/3a5i3c7J.png

### Versions

- Browser/version: Google Chrome 64.0.3282.186
- uBlock Origin version: 1.15.2

### Settings

- [Nothing]

### Notes

Since I am the owner of this website I can assure there is nothing malicious on the site. I dont even know how it got blocked in the first place.

**Comment by okiehsch** [comment]
If you manually update your `uBO-unbreak` list, the issue should be fixed, your users will automatically update in the coming days.

**Comment by Dwynr** [comment]
Thanks! Do you know if there are any other plugins that might block it? Seems like somebody doesnt like us and put us on some filters..

**Comment by mapx-** [comment]
yeah, those sites are blocked in easyprivacy list:
https://easylist.to/easylist/easyprivacy.txt

by this filter `.spacepools.`

So, any other adblocker using that list is blocking the sites above.

Report here for easyprivacy:
https://github.com/easylist/easylist/issues

**Comment by mapx-** [comment]
@ryanbr
