### ISSUE TITLE
simuladoresmod.com: detection

### ISSUE THREAD

**Issue by x-Raiden-x** [uBlockOrigin/uAssets#17523]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://simuladoresmod.com/caminhao-bob-constellation-qualificado-mods-ets2-1-45`

### Category

[unknown]

### Description

website detects the adblock and you have to disable it to function properly 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 91097
  cosmetic: 43018
  scriptlet: 17855
  html: 942
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 34237-200, 4d.3m
    ublock-badware: 6305-10, 4d.2m
    ublock-privacy: 352-0, 4d.1m
    ublock-abuse: 78-0, 4d
    ublock-unbreak: 1973-2, 3d.23h.59m
    ublock-quick-fixes: 492-0, 20h.12m
    easylist: 65159-629, 3d.23h.58m
    easyprivacy: 30788-1806, 3d.23h.57m
    urlhaus-1: 7462-0, 20h.11m
    plowe-0: 3752-2, 8d.1h.12m
    spa-1: 5155-10, 3d.23h.56m
filterset (user): [array of 1 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 389 ms (selfie)
  maxAssetCacheWait: 94 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    sendwebpush.com: 2
    themoneytizer.com: 16
```
</details>

**Comment by x-Raiden-x** [comment]
https://webtoolls.com/download2/campanha.php?id=bWFnbmV0Oj94dD11cm46YnRpaDowMkZBQzQxODAxRUUwOUE5MDY2QTExRTkxQTUzREFCNTg4MzNEODFFJmFtcDtkbj1Eb2lzJTIwQ2FyYXMlMjBMZWdhaXMlMjAxMDgwcCUyMCUyODIwMTYlMjklMjBEdWFsJTIwJWMzJTgxdWRpbyUyMEJsdVJheSUyMC0tJTIwQnklMjAtJTIwTHVjYXMlMjBGaXJtbyZhbXA7dHI9dWRwJTNhJTJmJTJmdHJhY2tlci5vcGVudHJhY2tyLm9yZyUzYTEzMzclMmZhbm5vdW5jZSZhbXA7dHI9dWRwJTNhJTJmJTJmdHJhY2tlci5jY2MuZGUlM2E4MCUyZmFubm91bmNlJmFtcDt0cj1odHRwJTNhJTJmJTJmdHJhY2tlcjEud2FzYWJpaS5jb20udHclM2E2OTY5JTJmYW5ub3VuY2UmYW1wO3RyPWh0dHAlM2ElMmYlMmZ0cmFja2VyLnRmaWxlLm1lJTJmYW5ub3VuY2UmYW1wO3RyPXVkcCUzYSUyZiUyZnRyYWNrZXIuY29wcGVyc3VyZmVyLnRrJTNhNjk2OSUyZmFubm91bmNlJmFtcDt0cj1odHRwJTNhJTJmJTJmbWd0cmFja2VyLm9yZyUzYTI3MTAlMmZhbm5vdW5jZSZhbXA7dHI9dWRwJTNhJTJmJTJmOS5yYXJiZy5jb20lM2EyNzQwJTJmYW5ub3VuY2UmYW1wO3RyPXVkcCUzYSUyZiUyZjkucmFyYmcubWUlM2EyNzQwJTJmYW5ub3VuY2UmYW1wO3RyPWh0dHAlM2ElMmYlMmZ0Mi5wb3c3LmNvbSUyZmFubm91bmNlJmFtcDt0cj11ZHAlM2ElMmYlMmZleHBsb2RpZS5vcmclM2E2OTY5JTJmYW5ub3VuY2U= that's the real page

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by mapx-** [comment]
Brazil.
However, the link above redirects to home page on my end
`https://webtoolls.com/`

I guess OP didn't provide the real initial link.
