### ISSUE TITLE
create.kahoot.it: breakage

### ISSUE THREAD

**Issue by judemont** [uBlockOrigin/uAssets#17520]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://create.kahoot.it/profiles/1fabb625-bc02-4064-9635-19bb42d9eeee`

### Category

breakage

### Description

When I go to [kahoot.com](https://kahoot.com) --> [explore content](https://kahoot.com/academy/study/) and I click on any theme, I have an error : 
```
Uh-oh! Something went wrong

Unfortunately, Kahoot! has stopped working because of an unexpected error. We're sorry for the inconvenience!
```

**If I disable ublock, everything works fine.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/96385330/230786316-d607985f-5135-4149-a99d-696279a4ca33.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 113
filterset (summary): 
  network: 89923
  cosmetic: 39679
  scriptlet: 17564
  html: 941
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34137-53, 4d.3h.47m
    ublock-badware: 6248-10, 4d.3h.46m
    ublock-privacy: 352-0, 6d.22h.13m
    ublock-abuse: 78-0, 6d.22h.12m
    ublock-unbreak: 1958-1, 4d.3h.45m
    ublock-quick-fixes: 489-0, 1d.20h.58m
    easylist: 65300-607, 2d.59m
    easyprivacy: 30785-1769, 4d.3h.48m
    urlhaus-1: 7631-0, 1d.20h.57m
    plowe-0: 3752-2, 6d.1h.23m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 869 ms (selfie)
  maxAssetCacheWait: 325 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    kahoot.it: 2
    amplitude.com: 1
    hotjar.com: 1
    sentry.io: 4
```
</details>

**Comment by mapx-** [comment]
add

`/assets/tracking-$badfilter`

**Comment by mapx-** [comment]
@ryanbr
