### ISSUE TITLE
karanpc.com: detection

### ISSUE THREAD

**Issue by larcn** [uBlockOrigin/uAssets#17529]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://karanpc.com/idm-latest/`

### Category

detection

### Description

you have adblocker enabled 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-04-10_19h36_27](https://user-images.githubusercontent.com/37812098/230958573-64511113-7383-455f-895e-a5ab370d9375.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 88420
  cosmetic: 39759
  scriptlet: 17627
  html: 946
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 34329-56, 8m
    ublock-badware: 6542-2, 8m
    ublock-privacy: 344-0, 8m
    ublock-abuse: 78-0, 8m
    ublock-unbreak: 1979-2, 8m
    easylist: 64250-622, 8m
    easyprivacy: 30804-1770, 7m
    urlhaus-1: 6946-0, 7m
    plowe-0: 3750-1, 7m
    ublock-quick-fixes: 354-0, 7m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 28 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 1132 ms (selfie)
  maxAssetCacheWait: 446 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    doubleclick.net: 4
    googlesyndication.com: 7
    googletagmanager.com: 1
    onesignal.com: 2
    wp.com: 2
```
</details>

**Comment by Sopor** [comment]
`https://karanpc.com/blog/`

You need to wait a couple of seconds and scroll too

Firefox 111

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/5789283/230962041-62077b29-149e-4267-9fc6-b328b123d8f0.png)

</details>

**Comment by mapx-** [comment]
I cannot reproduce the detection

**Comment by Sopor** [comment]
They have made a coupe of GUI changes, but i can't reproduce the detection either.

**Comment by Sopor** [comment]
It seems that is it time for an update `https://karanpc.com/windows`

![image](https://github.com/uBlockOrigin/uAssets/assets/5789283/4987a983-35e9-431d-aaf6-2d53bb3a2d13)

Note that you need to wait a couple of seconds before it popup.

**Comment by stephenhawk8054** [comment]
Don't open new issue. All volunteers are notified with new comments

**Comment by Sopor** [comment]
It seems that is it back again...

`Enhanced Tracking Protection` in Firefox is turned off

![image](https://github.com/uBlockOrigin/uAssets/assets/5789283/280b463e-72c7-4b38-b709-a3a0a2982a19)

uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 106190
 cosmetic: 42718
 scriptlet: 18951
 html: 1088
listset (total-discarded, last-updated):
 added:
  SWE-1: 4710-2, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 35874-239, 1m
  ublock-badware: 7259-0, 1m
  ublock-privacy: 582-0, 1m
  ublock-unbreak: 2171-2, 1m
  ublock-quick-fixes: 225-0, 1m
  easylist: 71987-559, 1m
  easyprivacy: 33148-769, 1m
  urlhaus-1: 10980-0, 1m
  plowe-0: 3729-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 389 ms
 maxAssetCacheWait: 120 ms

**Comment by mapx-** [comment]
still working on my side

**Comment by Sopor** [comment]
@mapx- When i tested it in my uBO only Firefox it first worked but after a couple of minutes it showed up there too.

Do you get this windows if you do a reload of the page?

![image](https://github.com/uBlockOrigin/uAssets/assets/5789283/889def33-29fe-4ae9-a8e8-7675e243e1ba)

If not, you have to wait for it to show up.

**Comment by mapx-** [comment]
yes, getting it but no detection.

**Comment by Sopor** [comment]
Depending of what i have open it change. It seems that when doubleclick is there i get the detection.

![image](https://github.com/uBlockOrigin/uAssets/assets/5789283/4030ef1f-463b-4c3c-93e8-18556c5688bd)

**Comment by Sopor** [comment]
Detection back again:

```
uBlock Origin: 1.54.0
Firefox: 118
filterset (summary):
 network: 105731
 cosmetic: 46586
 scriptlet: 19625
 html: 1143
listset (total-discarded, last-updated):
 added:
  SWE-1: 4543-6, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 36730-62, 2m
  ublock-badware: 7593-11, 2m
  ublock-privacy: 923-4, 1m
  ublock-unbreak: 2202-0, 2m
  ublock-quick-fixes: 171-2, 2m
  easylist: 75899-706, 2m
  easyprivacy: 33073-799, 2m
  urlhaus-1: 9915-0, 2m
  plowe-0: 3776-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 358 ms
 maxAssetCacheWait: 126 ms
```

It seems to comes and go and i have no idea why.

**Comment by Omega-6** [comment]
```
karanpc.com##+js(rmnt, script, mdp)
```

**Comment by Sopor** [comment]
It seems that it worked for some days and now it is back again 🙁
