### ISSUE TITLE
thaiairways.com: breakage

### ISSUE THREAD

**Issue by DavHau** [uBlockOrigin/uAssets#17535]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.thaiairways.com/de_DE/fluege_buchen/fluege_buchen.page?`

### Category

breakage

### Description

When I type in my flight search and then click on `book`, which should take me to the search results, nothing happens

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 111
filterset (summary): 
  network: 87753
  cosmetic: 39704
  scriptlet: 17581
  html: 946
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34283-106, 3d.16h.51m
    ublock-badware: 6437-5, 3d.16h.45m
    ublock-privacy: 352-0, 8d.22h.19m
    ublock-abuse: 78-0, 8d.22h.18m
    ublock-unbreak: 1975-0, 3d.16h.48m
    easylist: 63623-546, 3d.16h.43m
    easyprivacy: 30767-1769, 3d.16h.46m
    plowe-0: 3752-2, 8d.22h.16m
    urlhaus-1: 6946-0, 1d.21h.49m
    ublock-quick-fixes: 383-3, 1d.21h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 16 redacted]
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3775 ms (selfie)
  maxAssetCacheWait: 81 ms
popupPanel: 
  blocked: 3
  no-cosmetic-filtering: true
  blockedDetails: 
    thaiairways.com: 2
    google-analytics.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test if these filters work for you?

```adb
thaiairways.com##+js(set, dcsMultiTrack, noopFunc)
thaiairways.com##+js(set, urlStrArray, noopFunc)
```

Add in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click `Apply changes`, go back to the website and press Ctrl + F5 to reload the page and test again.
