### ISSUE TITLE
watchsomuchproxy.com: nuisance

### ISSUE THREAD

**Issue by matiasmacarioo** [uBlockOrigin/uAssets#17533]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://watchsomuchproxy.com/`

### Category

nuisance

### Description

There is an ad that cant be blocked with the selector.
https://user-images.githubusercontent.com/86095509/231073080-8a873911-1dbf-40e5-b2c4-ca5143a83c8c.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![imagen](https://user-images.githubusercontent.com/86095509/231073172-b9b154dc-4d92-4194-a8b6-c7c90eacd613.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 90512
  cosmetic: 45342
  scriptlet: 17900
  html: 946
listset (total-discarded, last-updated): 
  default: 
    user-filters: 31-2, never
    ublock-filters: 34329-90, 2d.1h.8m
    ublock-badware: 6474-0, 2d.1h.7m
    ublock-privacy: 352-0, 1d.12h.36m
    ublock-abuse: 78-0, 1d.12h.35m
    ublock-unbreak: 1977-1, 2d.1h.6m
    ublock-quick-fixes: 377-0, 2m
    easylist: 63623-651, 2d.1h.5m
    easyprivacy: 30799-1787, 2d.1h.4m
    urlhaus-1: 7043-0, 1m
    plowe-0: 3750-2, 1d.12h.34m
    spa-0: 3564-1, 3m
    spa-1: 5161-141, 2d.1h.9m
filterset (user): [array of 31 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 292 ms (selfie)
  maxAssetCacheWait: 92 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by matiasmacarioo** [comment]
Yes, is there a way to block it? I tried but it shows up again after some
time.

**Comment by Linxgos** [comment]
Easy fix add `watchsomuchproxy.com##.in.fade.modal` and `watchsomuchproxy.com##.btn-warning.btn` sometimes the website will prevent you from clicking anything if it does that just refresh the page

**Comment by mapx-** [comment]
@matiasmacarioo 

Did you read what is written in my comment ?
There are also 3 filters, you can open uBO dashboard, "my filters" section, add those 3 filters, click "apply changes", test again.

**Comment by mapx-** [comment]
@matiasmacarioo enable fanboy's annoyances list

**Comment by matiasmacarioo** [comment]
Great, thanks!
