### ISSUE TITLE
theclashify.com: detection

### ISSUE THREAD

**Issue by art20040423** [uBlockOrigin/uAssets#17537]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://theclashify.com/`

### Category

detection

### Description

Adblock Detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-04-11 214724](https://user-images.githubusercontent.com/125237541/231183854-4fa245f5-6f42-4a83-8799-6de4e7f00c6a.jpg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 125996
  cosmetic: 99120
  scriptlet: 31762
  html: 0
listset (total-discarded, last-updated): 
  added: 
    JPN-1: 10631-13, 33m
    adguard-generic: 69745-538, 33m
    adguard-mobile: 8754-79, 33m
  default: 
    user-filters: 1-0, never
    CHN-0: 27456-106, 33m
    easylist: 64344-898, 33m
    easyprivacy: 30807-1334, 33m
    plowe-0: 3750-1039, 32m
    ublock-abuse: 78-0, 32m
    ublock-badware: 6559-333, 32m
    ublock-filters: 33650-3748, 32m
    ublock-privacy: 294-2, 32m
    ublock-quick-fixes: 365-224, 32m
    ublock-unbreak: 1970-87, 32m
    urlhaus-1: 7215-1, 32m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 714 ms (selfie)
  maxAssetCacheWait: 291 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    theclashify.com: 1
    googletagmanager.com: 2
    intergient.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I have waited for 5 minutes but no anti adblock for me so far with the new filter.

**Comment by art20040423** [comment]
我有開自動更新，不知甚麼原因沒更新到/卡舊版，手動後就沒問題了
