### ISSUE TITLE
displayspecifications nuisance 

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#17546]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

displayspecifications right click blocked? (maybe even left-click double click)

### URL(s) where the issue occurs.

`https://www.displayspecifications.com/en/model/3c4e1909`

### uBO version

1.48.4

### Browser name and version

cent browser Version 5.0.1002.295 (Official Build) (64-bit) (Portable) (Chromium 102.0.5005.167)

### Settings

n/a

**Comment by stephenhawk8054** [comment]
Right click works normal for me. However, text selection is blocked.
