### ISSUE TITLE
[nsfw] f95zone.to: ads

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#17540]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://f95zone.to/forums/games.2/`

### Category

ads

### Description

Leftover ad box in the bottom left corner of the page (seem to show up only if you're not logged).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://user-images.githubusercontent.com/22180480/231228876-b0b701f0-06be-4aec-98aa-06b6623daed5.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 89633
  cosmetic: 47263
  scriptlet: 17797
  html: 956
listset (total-discarded, last-updated): 
  default: 
    user-filters: 25-0, never
    ublock-filters: 34297-92, 2d.1h.43m
    ublock-badware: 6475-0, 2d.1h.42m
    ublock-privacy: 352-0, 10d.5h.25m
    ublock-abuse: 78-0, 10d.5h.25m
    ublock-unbreak: 1980-2, 2d.1h.41m
    ublock-quick-fixes: 352-0, 21h.43m
    easylist: 64100-622, 2d.1h.40m
    easyprivacy: 30787-1769, 2d.1h.39m
    urlhaus-1: 6946-0, 21h.42m
    plowe-0: 3751-2, 10d.5h.25m
    POL-0: 7936-26, 8h.41m
    POL-2: 1278-12, 1d.21h.35m
filterset (user): [array of 26 redacted]
trustedset: 
  added: [array of 31 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 876 ms
  maxAssetCacheWait: 289 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    f95zone.to: 2
    adtng.com: 1
    googletagmanager.com: 1
    trafficjunky.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
f95zone.to##.notices--floating.notices
```

**Comment by mapx-** [comment]
report at [easylist repository](https://github.com/easylist/easylist/issues)
