### ISSUE TITLE
devuploads.com: detection

### ISSUE THREAD

**Issue by venkat2305** [uBlockOrigin/uAssets#17548]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

please check the video

`https://user-images.githubusercontent.com/55329452/231496186-a4e099cb-c510-477e-8b11-0a6bd059089b.mp4`

### URL(s) where the issue occurs.

`https://devuploads.com/users/selfmuser0509/2199/Normal-Theme`

### Screenshot(s)

`https://user-images.githubusercontent.com/55329452/231496313-0777605a-5c80-4658-8bac-de5ae6e396c1.webm`

### uBO version

1.48.4

### Browser name and version

microsoft edge 112.0.1722.39

### Settings

s

**Comment by stephenhawk8054** [comment]
It's fixed hours ago. Can you force update all your filter lists (click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

**Comment by venkat2305** [comment]
i did as you mentioned. it didn't work

**Comment by mapx-** [comment]
Did you disable `tracking prevention` in edge ?

**Comment by stephenhawk8054** [comment]
It works for me. Video recording: https://user-images.githubusercontent.com/66517106/231505303-bb51eda1-99e4-4e73-a77e-5e4bb95447d8.mp4

Check if you are using any:

- Custom filters,
- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by stephenhawk8054** [comment]
I can reproduce using VPN to some locations. It's not stable so I can't assure it will work for everyone.

**Comment by stephenhawk8054** [comment]
It's site issues sometimes. I once turn off all extensions completely in add-ons settings, and it still says adblock detection. Try clearing cookies and/or using VPN for it.

**Comment by stephenhawk8054** [comment]
In that case I cannot help more as I cannot reproduce in both desktop and mobile.

**Comment by stephenhawk8054** [comment]
Try

```adb
thecubexguide.com#@#[data-google-query-id], iframe:style(height: 1px !important; width: 1px !important; visibility: hidden !important;)
thecubexguide.com##iframe
```

**Comment by venkat2305** [comment]
i didn't work for me.

**Comment by stephenhawk8054** [comment]
Force update all your filter lists (click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)).

Remember to check these listings: https://github.com/uBlockOrigin/uAssets/issues/17548#issuecomment-1505477931 as I see you are using many extensions in your video. Try clearing cookies/caches/history of that site in your browser.

As I cannot reproduce right now, I cannot help more. If it still didn't work for you, you need to investigate yourself or wait for other volunteers who can reproduce and update it. Good luck.

**Comment by mapx-** [comment]
try

```
thecubexguide.com#@##featuredimage
*$image,domain=thecubexguide.com,3p,redirect=1x1.gif
thecubexguide.com###featuredimage:style(pointer-events: none !important)
```

**Comment by venkat2305** [comment]
I created a new profile to test this. it isn't fixed. @mapx-

**Comment by mapx-** [comment]
do you see my filters in the logger aft6er updating ALL the lists ?

**Comment by mapx-** [comment]
they changed something again

**Comment by huyszn** [comment]
I am getting detected when trying to generate download link

**Comment by uurcan7** [comment]
same

**Comment by Fatcavill** [comment]
adblock detected

**Comment by mapx-** [comment]
dedicated thread https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by ItsProfessional** [comment]
That discussion is for link shorteners. This is a file hosting service, unless I'm mistaken

**Comment by DepressedDeity** [comment]
https://devuploads.com/2hrkd2vw1ogb

`Blank space of ads leftover appear`

[IMG_20241002_094658](https://github.com/user-attachments/assets/7ca86059-e3e8-4e57-8a1c-8e62564869a7)
