### ISSUE TITLE
shaka-player-demo.appspot.com: detection

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17545]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shaka-player-demo.appspot.com/demo/`

### Category

detection

### Description

Detection from `/ad_manager.` in EasyList
No ads present when allowing the filter
`@@||shaka-player-demo.appspot.com/lib/ads/ad_manager.js$script,1p`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 80140
  cosmetic: 42799
  scriptlet: 21230
  html: 1111
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 18h.47m
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1552-0, 18h.48m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 10h.24m
    ublock-annoyances: 4887-4, 21h.42m
  default: 
    user-filters: 1677-13, never
    ublock-filters: 34522-338, 20h.34m
    ublock-badware: 6563-0, 21h.42m
    ublock-privacy: 344-0, 21h.42m
    ublock-abuse: 78-0, 21h.42m
    ublock-unbreak: 1981-2, 20h.34m
    ublock-quick-fixes: 365-0, 20h.34m
    easylist: 64387-191, 20m
    easyprivacy: 30810-2215, 14h.24m
filterset (user): [array of 705 redacted]
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 321 ms (selfie)
  maxAssetCacheWait: 105 ms
  unsuspendAfter: 157 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    imasdk.googleapis.com: 5
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
