### ISSUE TITLE
maxstream.video: detection

### ISSUE THREAD

**Issue by Flareninja** [uBlockOrigin/uAssets#17542]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://maxstream.video/1rzdn5ptdtdb/bnF4cWNtVjIwdlcwSTRsaGtXKyttUT09`

### Category

detection

### Description

A popup shows up after some seconds saying "Disable your adblock please."

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.0
Chromium: 111
filterset (summary): 
  network: 94232
  cosmetic: 99883
  scriptlet: 23454
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    ITA-0: null
  added: 
    adguard-annoyance: 67096-94, 2m
    ublock-annoyances: 4934-162, 2m
  default: 
    easylist: 64386-102, 2m
    easyprivacy: 30810-1261, 2m
    plowe-0: 3750-939, 2m
    ublock-abuse: 78-0, 2m
    ublock-badware: 6579-116, 2m
    ublock-filters: 33696-498, 2m
    ublock-privacy: 294-2, 2m
    ublock-quick-fixes: 365-219, 2m
    ublock-unbreak: 1975-44, 2m
    urlhaus-1: 7215-1, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 54162 ms (selfie)
  maxAssetCacheWait: 554 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    biteneverthelessnan.com: 2
    googletagmanager.com: 1
    host-cdn.net: 1
    intellipopup.com: 1
```
</details>

**Comment by mapx-** [comment]
On my side will land on some scam site

`https://maxstream.video/1rzdn5ptdtdb/bnF4cWNtVjIwdlcwSTRsaGtXKyttUT09 => https://maxstream.video/readfile.php => https://needyscarcasserole.com/ibnb9rrd?key=80591b5f80bc1744cd651f4c1808f5d6`
