### ISSUE TITLE
weszlo.com: detection

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uAssets#17541]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://weszlo.com/2023/04/11/goraca-atmosfera-w-juventusie-paredes-spial-sie-z-allegrim/`

### Category

detection

### Description

On real mobile only.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-04-11-19-27-01](https://user-images.githubusercontent.com/886325/231243009-902ffb20-cf8f-4180-a3d4-083f84e0b0c0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox Mobile: 111
filterset (summary): 
  network: 91702
  cosmetic: 37366
  scriptlet: 17950
  html: 996
listset (total-discarded, last-updated): 
  added: 
    POL-0: 7936-144, 5m
    POL-2: 1278-17, 5m
  default: 
    user-filters: 22-0, never
    ublock-filters: 34818-544, 6m
    ublock-badware: 6577-2, 5m
    ublock-privacy: 344-1, 6m
    ublock-abuse: 78-0, 6m
    ublock-unbreak: 1988-0, 6m
    ublock-quick-fixes: 371-2, 6m
    adguard-mobile: 8754-120, 6m
    easylist: 64345-17485, 6m
    easyprivacy: 30810-1779, 6m
    urlhaus-1: 7215-1, 5m
    plowe-0: 3750-1, 5m
filterset (user): [array of 21 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 3996 ms (selfie)
  maxAssetCacheWait: 812 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    cloudflareinsights.com: 2
    doubleclick.net: 5
    googletagmanager.com: 1

```
</details>

**Comment by mapx-** [comment]
reproduced in FF native emulation, galaxy note 20 android 11
