### ISSUE TITLE
lightrun.com: breakage

### ISSUE THREAD

**Issue by ngoclong19** [uBlockOrigin/uAssets#17553]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The website turns blank after finish loading.

In the browser console, there is an error "TypeError: window.gtag is not a function".

### URL(s) where the issue occurs.

`https://lightrun.com/answers/vercel-vercel-vercel-doesnt-seem-to-run-pnpm-with-v7-in-ci`

### Notes

I could mitigate the issue by using this filter rule:
`lightrun.com##+js(set, gtag, noopFunc)`

Maybe we could modify the resource `googletagmanager_gtm.js` to additionally return `window.gtag`.

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 199
  cosmetic: 2
  scriptlet: 91
  html: 52
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    ublock-filters: null
    ublock-badware: null
    ublock-abuse: null
    ublock-unbreak: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    VIE-1: null
    ublock-quick-fixes: null
  default: 
    ublock-privacy: 344-0, now
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1237 ms (selfie)
  maxAssetCacheWait: 886 ms
```
</details>

**Comment by mapx-** [comment]
> The website turns blank after finish loading.

I cannot reproduce the issue.

Your installation seems to be broken or you deliberately disabled all the lists in uBO ?!

**Comment by ngoclong19** [comment]
Look like a server hiccup. It's working now.
