### ISSUE TITLE
v3rmillion.net: ads

### ISSUE THREAD

**Issue by Banaanae** [uBlockOrigin/uAssets#17557]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://v3rmillion.net/index.php`

### Category

ads

### Description

Account Required
V3rmillion has 1st _and_ 3rd party ads, 3rd are blocked, first aren't
Fixable via 
`v3rmillion.net###sharingPlace`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/83927639/231641765-20f6aac0-6683-4a55-9802-2d081a0f435d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 105348
  cosmetic: 40036
  scriptlet: 18186
  html: 946
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/stephenhawk8054/PrivacyExtended/main/privacy_extended.txt: 17326-12, 5h.35m
  default: 
    user-filters: 14-0, never
    ublock-filters: 34524-339, 1d.12h.29m
    ublock-badware: 6542-2, 1d.12h.36m
    ublock-privacy: 344-0, 1d.12h.35m
    ublock-abuse: 78-0, 1d.12h.34m
    ublock-unbreak: 1980-2, 1d.12h.33m
    ublock-quick-fixes: 371-0, 5h.36m
    easylist: 64250-575, 1d.12h.32m
    easyprivacy: 30803-1782, 1d.12h.30m
    urlhaus-1: 7420-1, 5h.37m
    plowe-0: 3750-1, 1h.32m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2871 ms (selfie)
  maxAssetCacheWait: 307 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    v3rmillion.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
