### ISSUE TITLE
hostingsgratis.com: detection

### ISSUE THREAD

**Issue by Warden20** [uBlockOrigin/uAssets#17554]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hostingsgratis.com/`

### Category

detection

### Description

this site detects ad blockers and doesn't promise to get access to any content on site.
https://user-images.githubusercontent.com/64172827/231565997-79194f1a-4e32-458c-9716-3746b302f939.jpg

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89108
  cosmetic: 39792
  scriptlet: 17673
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64394-47, 11m
    easyprivacy: 30812-1177, 11m
    plowe-0: 3750-937, 11m
    ublock-abuse: 78-0, 11m
    ublock-badware: 6589-117, 11m
    ublock-filters: 33713-111, 11m
    ublock-privacy: 294-2, 11m
    ublock-quick-fixes: 371-219, 11m
    ublock-unbreak: 1976-42, 11m
    urlhaus-1: 7420-1, 11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1907 ms
  maxAssetCacheWait: 197 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    exoclick.com: 1
```
</details>

**Comment by gorhill** [comment]
Your screenshot shows your are use Brave Shield: disable it and use uBO only. I can't reproduce your issue with only uBO and default settings/lists.

**Comment by Warden20** [comment]
I am using the default list for Ublock and the brave shield is off. I dont use any other extension
1.  Ddl site https://hackstore.re/peliculas/lo-que-el-viento-se-llevo-1939/
2. Use any link from the section in the photo 
![2023-04-12 697 Pelicula_Lo_que_el_viento_se_llevó_(1939)_Completa](https://user-images.githubusercontent.com/64172827/231579038-caaa43c3-1631-4a24-8bc2-b0b01f211f23.jpg)
3. The link redirects itself to this. Click in Haz clic aqui 
![2023-04-12 502 _Protector_de_Enlaces__Link_Protector_-_Brave](https://user-images.githubusercontent.com/64172827/231579221-5d583ff5-4ce7-4d19-a634-979a80bc47b5.jpg)
4. It opens a new tab and this is the one that detecs ublock
![2023-04-12 255 httpshostingsgratis com_-_Brave](https://user-images.githubusercontent.com/64172827/231579436-6bc0b997-afb0-4680-b112-188750c9a5d5.jpg)

**Comment by mapx-** [comment]
duplicate 
https://github.com/uBlockOrigin/uAssets/issues/17552#issuecomment-1505963405
