### ISSUE TITLE
review.firstround.com: nuisance

### ISSUE THREAD

**Issue by tony-bosco** [uBlockOrigin/uAssets#17551]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://review.firstround.com/the-best-interview-questions-weve-ever-published`

### Category

nuisance

### Description

Persistent overlay and email subscription module  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 88589
  cosmetic: 39734
  scriptlet: 17601
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 63860-46, 3d.1h.58m
    easyprivacy: 30808-1177, 1d.11m
    plowe-0: 3750-937, 5d.5h.23m
    ublock-abuse: 78-0, 5d.18h.15m
    ublock-badware: 6465-119, 3d.19h.10m
    ublock-filters: 33419-91, 3d.19h.9m
    ublock-privacy: 302-2, 5d.11h.59m
    ublock-quick-fixes: 365-20, 8h.30m
    ublock-unbreak: 1969-43, 3d.1h.57m
    urlhaus-1: 7520-0, 8h.31m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 35 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 185 ms (selfie)
  maxAssetCacheWait: 68 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    piano.io: 1
```
</details>

**Comment by gorhill** [comment]
Given the nuisance cannot be dismissed, I put the filter in the default lists.

**Comment by stephenhawk8054** [comment]
I think that filter will break the site's sign-in page `https://review.firstround.com/sign-in`?

How about this one?

```adb
firstround.com##+js(aeld, scroll, t(e))
```

**Comment by mapx-** [comment]
or more classic

```
review.firstround.com##.tp-modal
review.firstround.com##.tp-active.tp-backdrop
review.firstround.com##body:style(overflow: auto !important;)
```

**Comment by stephenhawk8054** [comment]
Yeah, I think cosmetic filters are safer in this case.
