### ISSUE TITLE
hints.littlealchemy2.com: detection

### ISSUE THREAD

**Issue by Fighter178** [uBlockOrigin/uAssets#17559]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hints.littlealchemy2.com/personalized-hint`

### Category

detection

### Description

When you click the button, it detects that a "content" blocker is present. 
It does not allow me to continue to use the page for what I need.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 88855
  cosmetic: 39748
  scriptlet: 17632
  html: 946
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    ublock-filters: 34528-254, 2d.2h.7m
    ublock-badware: 6510-0, 2d.2h.10m
    ublock-privacy: 352-0, 9d.20h.27m
    ublock-abuse: 78-0, 9d.4h.59m
    ublock-unbreak: 1980-2, 2d.2h.9m
    ublock-quick-fixes: 365-0, 1d.2h.4m
    easylist: 64100-602, 2d.2h.8m
    easyprivacy: 30796-1769, 3d.3h.59m
    urlhaus-1: 7520-1, 1d.2h.5m
    plowe-0: 3753-2, 7d.1h.9m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 650 ms (selfie)
  maxAssetCacheWait: 238 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    littlealchemy2.com: 1
    4dex.io: 2
    adnxs.com: 6
    amazon-adsystem.com: 1
    casalemedia.com: 1
    doubleclick.net: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    indexww.com: 1
    justpremium.com: 2
    nextmillmedia.com: 4
    openx.net: 2
    quantserve.com: 1
    servenobid.com: 2
    sharethrough.com: 3
```
</details>

**Comment by stephenhawk8054** [comment]
You mean the line `It looks like you're using a content blocker. Make sure to turn it off for this page and try again.` ?

**Comment by krystian3w** [comment]
It shows even disable uBo, but on disabled uBo I see animations on buttons "personalized hints".

So bar is out of scope, but buttons for the future investigation who broke and how fix.

**Comment by mapx-** [comment]
@Fighter178 

test

```
@@||c.amazon-adsystem.com/aax2/apstag.js$script,domain=hints.littlealchemy2.com
@@||doubleclick.net^$script,xhr,domain=hints.littlealchemy2.com
@@||googlesyndication.com^$xhr,frame,script,domain=hints.littlealchemy2.com
hints.littlealchemy2.com###hints-adblock-enabled
@@||hints.littlealchemy2.com^$ghide
```

**Comment by krystian3w** [comment]
This may unlock google crap - vignette ads:

`https://hints.littlealchemy2.com/item/air#google_vignette`

https://user-images.githubusercontent.com/35370833/231767142-faa48664-546a-49fd-94b9-a18c43056170.png - fog from vignette:


```adb
##html > body ~ [id*="gpt"]
!
! really outside of body
```
