### ISSUE TITLE
similarweb.com: ads

### ISSUE THREAD

**Issue by Linxgos** [uBlockOrigin/uAssets#17555]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.similarweb.com/top-websites/`

### Category

ads

### Description

When scrolling down their is a small gap at the top of the screen where contents of the page can be seen through this is not present with cosmetic filtering off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Cosmetic Filtering On
 
![Screenshot 2023-04-12 162201](https://user-images.githubusercontent.com/30780867/231575711-7cabf051-490a-4367-8a1f-2bd85beaf774.png)

Cosmetic Filtering Off

![Screenshot 2023-04-12 162404](https://user-images.githubusercontent.com/30780867/231576066-774b9eba-df6d-4d9a-bd3c-fc7eafa931dd.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 224246
  cosmetic: 245314
  scriptlet: 40261
  html: 1112
listset (total-discarded, last-updated): 
  added: 
    https://github.com/hoshsadiq/adblock-nocoin-list/raw/master/nocoin.txt: 664-0, 2h.18m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2154-0, 2h.18m
    https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1912-0, 2h.18m
    https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4589-45, 2h.18m
    adguard-generic: 69793-5418, 2h.18m
    adguard-mobile: 8758-128, 2h.18m
    adguard-spyware-url: 975-139, 2h.18m
    block-lan: 47-0, 2h.18m
    curben-phishing: 67549-32, 2h.18m
    curben-pup: 192-0, 2h.18m
    adguard-annoyance: 67161-5148, 2h.18m
    adguard-social: 20241-916, 2h.18m
    fanboy-thirdparty_social: 68-0, 2h.18m
    fanboy-annoyance: 80515-69553, 2h.18m
    fanboy-cookiemonster: 46571-240, 2h.18m
    fanboy-social: 21052-21, 2h.18m
    ublock-annoyances: 4899-6, 2h.18m
    dpollock-0: 11354-471, 2h.18m
    CHN-0: 27474-149, 2h.18m
    JPN-1: 10638-33, 2h.18m
  default: 
    user-filters: 10-0, never
    ublock-filters: 34589-309, 2h.18m
    ublock-badware: 6593-0, 2h.18m
    ublock-privacy: 344-3, 2h.18m
    ublock-abuse: 78-3, 2h.18m
    ublock-unbreak: 1987-3, 2h.18m
    ublock-quick-fixes: 371-0, 2h.18m
    easylist: 64394-899, 2h.18m
    easyprivacy: 30812-2153, 2h.18m
    urlhaus-1: 7420-1, 2h.18m
    plowe-0: 3750-4, 2h.18m
filterset (user): [array of 10 redacted]
switchRuleset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 736 ms (selfie)
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    similarweb.com: 2
    go-mpulse.net: 2
    google.com: 1
    googletagmanager.com: 1
    similarweb.io: 2
    visualwebsiteoptimizer.com: 2
```
</details>

**Comment by gorhill** [comment]
Did you test with only default settings/lists as asked?

**Comment by Linxgos** [comment]
Yes I verified that none of my personal filters or other list were causing the issue using the logger

**Comment by Procyon-b** [comment]
Try this:
```
similarweb.com##body.app-banner-parent:style(padding-top: 0px !important)
similarweb.com##body.app-banner-parent .app-header:style(top: 0px !important)
```

**Comment by gorhill** [comment]
I don't see that gap with default lists. Use uBO's DOM inspector to find out which filter from which filter list removes that banner.

**Comment by mapx-** [comment]
this filter is breaking the scrolling 

`similarweb.com##.app-banner`

@ryanbr

**Comment by Procyon-b** [comment]
Apparently there are more to fix.

Try this instead:
```
similarweb.com##+js(rc, app-banner-parent, body, stay)
```

**Comment by Linxgos** [comment]
Seems like fanboy annoyance is the filter with the bad filter

**Comment by Linxgos** [comment]
> Apparently there are more to fix.
> 
> Try this instead:
> 
> ```
> similarweb.com##+js(rc, app-banner-parent, body, stay)
> ```
Fixed
