### ISSUE TITLE
trackers block issue

### ISSUE THREAD

**Issue by ilyak83** [uBlockOrigin/uAssets#17558]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

It looks like uBO doesn't block tracking ads and trackers in "EFF" site (I want to believe that relative only to this site). 

### URL(s) where the issue occurs.

`https://coveryourtracks.eff.org/`

### Screenshot(s)

![01](https://user-images.githubusercontent.com/37582972/231663446-ae1f8d29-52cf-4c71-983f-6656b3aa7fb8.jpg)
![02](https://user-images.githubusercontent.com/37582972/231663456-5fcb8dec-744e-49e0-823e-713ec45f4acd.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 114220
  cosmetic: 158821
  scriptlet: 23549
  html: 960
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 46522-213, 5d.18h.4m
  default: 
    user-filters: 2-0, never
    ublock-filters: 34524-254, 1d.14h.15m
    ublock-badware: 6510-0, 1d.14h.14m
    ublock-privacy: 344-0, 1d.14h.13m
    ublock-abuse: 78-0, 1d.14h.12m
    ublock-unbreak: 1983-3, 1d.14h.1m
    ublock-quick-fixes: 371-0, 16h.33m
    easylist: 64345-622, 1d.14h.1m
    easyprivacy: 30810-1773, 1d.14h.1m
    urlhaus-1: 7420-1, 16h.33m
    plowe-0: 3750-2, 5d.18h.4m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 238 ms (selfie)
  maxAssetCacheWait: 81 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Don't rely on test sites. Those contain connections that might not be used in real cases. If you find tracking resources in real-world cases, report here.
