### ISSUE TITLE
infomania.space: detection

### ISSUE THREAD

**Issue by Warden20** [uBlockOrigin/uAssets#17552]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://infomania.space/`

### Category

detection

### Description

this site detects ad blockers and doesn't promise to get access to any content on site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://user-images.githubusercontent.com/64172827/231565124-9cb4f867-1224-409e-aba4-2f0088b98da9.jpg

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89108
  cosmetic: 39792
  scriptlet: 17673
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64394-47, 6m
    easyprivacy: 30812-1177, 6m
    plowe-0: 3750-937, 6m
    ublock-abuse: 78-0, 6m
    ublock-badware: 6589-117, 6m
    ublock-filters: 33713-111, 6m
    ublock-privacy: 294-2, 6m
    ublock-quick-fixes: 371-219, 6m
    ublock-unbreak: 1976-42, 6m
    urlhaus-1: 7420-1, 6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1907 ms
  maxAssetCacheWait: 197 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    exoclick.com: 1
```
</details>

**Comment by mapx-** [comment]
Provide the exact steps (and links) to reproduce the issue

**Comment by Warden20** [comment]
I am using the default list for Ublock and the brave shield is off
1. Ddl site https://hackstore.re/peliculas/mundo-fantasma-2001/
2. Use any link in the photo. Ised the mediafire link
![2023-04-12 697 Pelicula_Lo_que_el_viento_se_llevó_(1939)_Completa](https://user-images.githubusercontent.com/64172827/231580310-d941a0bf-1ff2-4590-a3ea-0e17a6f33925.jpg)
4. The link redirects itself to this. Click in Haz clic aqui 
![2023-04-12 502 _Protector_de_Enlaces__Link_Protector_-_Brave](https://user-images.githubusercontent.com/64172827/231580451-3445550d-f0d5-40ce-bc8f-55de4eeb5896.jpg)
5. It opens a new tab and this is the one that detecs ublock
![2023-04-12 757 httpsinfomania space_-_Brave](https://user-images.githubusercontent.com/64172827/231580381-d74c248c-82cf-4048-96f6-7f650d83c247.jpg)

**Comment by mapx-** [comment]
test

`@@||exoclick.com^$xhr,domain=hostingsgratis.com|infomania.space`

**Comment by Warden20** [comment]
It worked. Thanks
