### ISSUE TITLE
edeka.de: breakage

### ISSUE THREAD

**Issue by MaierTV** [uBlockOrigin/uAssets#17567]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.edeka.de/`

### Category

detection

### Description

site is not working when ublock is on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 91187
  cosmetic: 44238
  scriptlet: 17631
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    DEU-0: 6754-0, 18h.11m
    easylist: 64250-53, 1d.21h.29m
    easyprivacy: 30799-1186, 2d.17h.56m
    plowe-0: 3750-938, 1d.21h.30m
    ublock-abuse: 78-0, 2d.21h.38m
    ublock-badware: 6579-116, 1d.18h.12m
    ublock-filters: 33454-135, 1d.18h.42m
    ublock-privacy: 302-2, 2d.21h.35m
    ublock-quick-fixes: 371-22, 18h.10m
    ublock-unbreak: 1969-44, 1d.18h.41m
    urlhaus-1: 7420-1, 18h.9m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-extension-scheme
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 226 ms (selfie)
  maxAssetCacheWait: 88 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    aticdn.net: 2
    pinimg.com: 1
    trustcommander.net: 1
```
</details>

**Comment by krystian3w** [comment]
> site is not working when ublock is on

so seems as breakage.

**Comment by gorhill** [comment]
File as _detection_, says _"site broken"_ without pointing out what exactly is broken (seems fine to me), and state:

- [x] I did not answer truthfully to ALL the above checkpoints.

Wish there was more consideration toward volunteers here.

**Comment by krystian3w** [comment]
I have one breakage on:

`https://www.edeka.de/newsletter/anmelden.jsp?person.useremail=a%40a.pl`

@kiboke without accept "cookie policy" I can't close pop-up: 

> Zustimmung erforderlich
>
> Für die Anmeldung zum Newsletter ist Ihre Zustimmung für unseren Formularschutz in Ihren Datenschutzeinstellungen erforderlich. Weitere Informationen finden Sie in unserer 

Bad is your generic `||trustcommander.net/privacy$script,from=~tf1.fr|~tf1info.fr`.

But reporter may deleted EasyList Cookies / I don't care about cookies.

**Comment by JobcenterTycoon** [comment]
Yes.

**Comment by kiboke** [comment]
@krystian3w thanks, it will be fixed in IDCAC.
