### ISSUE TITLE
instagram.com: ads

### ISSUE THREAD

**Issue by zhihwei** [uBlockOrigin/uAssets#17569]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.instagram.com/stories/aayan1120/3079234025295026146/`

### Category

ads

### Description

> 以往IG限動沒有出現贊助商廣告，但近期大量出現，希望能夠修正。

**In the past, there were no sponsor advertisements on IG limited action, but there have been a large number of them recently, and I hope it can be corrected.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 106327
  cosmetic: 50105
  scriptlet: 17814
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 27488-106, 1m
    easylist: 64539-100, 1m
    easyprivacy: 30816-1196, 1m
    plowe-0: 3750-939, 1m
    ublock-abuse: 78-0, 1m
    ublock-badware: 6589-117, 1m
    ublock-filters: 33730-125, 1m
    ublock-privacy: 294-2, 1m
    ublock-quick-fixes: 382-224, 1m
    ublock-unbreak: 1980-43, 1m
    urlhaus-1: 7625-1, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 201 ms (selfie)
  maxAssetCacheWait: 67 ms
popupPanel: 
  blocked: 78
  blockedDetails: 
    instagram.com: 78
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/17415
