### ISSUE TITLE
ipcimeeting.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#17565]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ipcimeeting.com/`

### Category

detection

### Description

Anti AdBlock 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium Mobile: 111
filterset (summary): 
  network: 100990
  cosmetic: 126180
  scriptlet: 23967
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7728-7, 14h.48m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 77-4, 14h.47m
    IDN-0: 5466-344, 14h.50m
    fanboy-annoyance: 81181-380, 7d.15h.39m
    fanboy-cookiemonster: 46503-46503, 7d.15h.37m
    ublock-annoyances: 4993-87, 14h.46m
  default: 
    user-filters: 0-0, never
    adguard-mobile: 8758-18, 14h.49m
    easylist: 64394-75, 14h.45m
    easyprivacy: 30807-1187, 14h.44m
    ublock-abuse: 78-0, 1h.37m
    ublock-badware: 6578-118, 14h.43m
    ublock-filters: 33879-297, 14h.42m
    ublock-privacy: 294-3, 1h.36m
    ublock-quick-fixes: 377-201, 12h.1m
    ublock-unbreak: 1974-49, 14h.41m
    urlhaus-1: 7420-1, 12h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  largeMediaSize: 200
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8790 ms (selfie)
  maxAssetCacheWait: 1705 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    ads-twitter.com: 1
    google.com: 4
    googletagmanager.com: 1
    gstatic.com: 1
    marketo.net: 1
```
</details>

**Comment by krystian3w** [comment]
Try reproduce in Firefox Mobile or on PC/iMac/MacBook Chrome/Edge.

**Comment by mapx-** [comment]
@3xploiton3 do you get the detection exactly here: `https://ipcimeeting.com/` ?

Test using FF mobile, default settings.

**Comment by 3xploiton3** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17589



> @3xploiton3 do you get the detection exactly here: `https://ipcimeeting.com/` ?
> 
> Test using FF mobile, default settings.
