### ISSUE TITLE
haber.eskisehirde.net: detection

### ISSUE THREAD

**Issue by uuqqzz** [uBlockOrigin/uAssets#17563]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://haber.eskisehirde.net/`

### Category

detection

### Description

ad blocker detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/231675467-f49569cb-e0a7-48cc-8fd6-154bac960a01.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 127446
  cosmetic: 160054
  scriptlet: 35964
  html: 948
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38596-14210, 16m
    adguard-generic: 69802-6058, 17m
    adguard-spyware-url: 975-4, 16m
    adguard-annoyance: 67163-1573, 16m
    adguard-social: 20241-31, 16m
  default: 
    user-filters: 63-0, never
    ublock-filters: 34593-301, 17m
    ublock-badware: 6593-0, 17m
    ublock-privacy: 344-0, 17m
    ublock-abuse: 78-0, 17m
    ublock-unbreak: 1987-3, 17m
    ublock-quick-fixes: 380-0, 17m
    easylist: 64539-329, 16m
    easyprivacy: 30814-1192, 16m
    TUR-0: 12219-11, 16m
filterset (user): [array of 65 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 734 ms (selfie)
  maxAssetCacheWait: 274 ms
  unsuspendAfter: 241 ms
popupPanel: 
  blocked: 14
  blockedDetails: 
    eskisehirde.net: 1
    admatic.com.tr: 2
    facebook.net: 1
    googlesyndication.com: 9
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
haber.eskisehirde.net##+js(nostif, show)
```

for Adguard Turkish? @Yuki2718

**Comment by krystian3w** [comment]
Or AG Annoyances if close on every refresh no enough to address as "hard" anti-adblock.

I haven't tested if the site freezes the action when the close button is clicked, if it freezes it is a hard anti-adblock.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/commits/master?branch=master&path%5B%5D=TurkishFilter&path%5B%5D=sections&author=Yuki2718&qualified_name=refs%2Fheads%2Fmaster
