### ISSUE TITLE
short2win.com

### ISSUE THREAD

**Issue by simoconfa** [uBlockOrigin/uAssets#1756]
### URL(s) where the issue occurs
`https://www.short2win.com/KEUQD`

### Describe the issue

Adblock detected

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/8224154/37710252-61342fa8-2d0d-11e8-85c2-f6c53531eee2.png)

### Versions

- Browser/version: FF latest
- uBlock Origin version: 1.0.0.37

### Settings

- I haven't modified nothing

### Notes

This seems similar to cutwin.co

**Comment by SMed79** [comment]
@mapx- would you also block the third party iframes

http://i.imgur.com/qmIXx1m.png
http://i.imgur.com/TJfju96.png

```
$subdocument,third-party,domain=short2win.com
@@||google.com/recaptcha/$subdocument,domain=short2win.com
```

**Comment by mapx-** [comment]
right, scrolling ...at the bottom, thx
