### ISSUE TITLE
Conflict with HTTPS Everywhere

### ISSUE THREAD

**Issue by SRoyPC** [uBlockOrigin/uAssets#1757]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[n/a]`

### Describe the issue

[This extension failed to redirect a network request to https://www.google-analytics.com/ga.js because another extension (uBlock Origin) redirected it to chrome-]

### Screenshot(s)

[n/a]

### Versions

- Browser/version: [Version 65.0.3325.181 (Official Build) (64-bit)]
- uBlock Origin version: [1.15.18]

### Settings

- [All Privacy check-boxes are selected on the 'Settings' tab. Rest all are set to their default settings]

### Notes

[n/a]

**Comment by uBlock-user** [comment]
Just a warning, you can ignore it.

**Comment by mapx-** [comment]
you could also try to disable all the `google-analytics` filters in ublock privacy list using `badfilter` keyword

**Comment by User486375** [comment]
Visiting https://www.google-analytics.com/ga.js and unticking the HTTPS Everywhere rule for **google analytics** seems to fix the issue for me. 

Though this isn't the only conflict I've encountered.
For example:
https://c1.popads.net/pop.js
https://www.googletagmanager.com/gtm.js
https://s7.addthis.com/js/300/addthis_widget.js

I don't know if it's recent changes to ublock filter lists that are causing all these conflicts or if it's something HTTPS Everywhere have added/changed recently. I just don't remember ever getting these errors up until the last few weeks.

**Comment by mapx-** [comment]
All those are normal redirections for privacy or popups reasons, so if you get only warnings just ignore them.

**Comment by Hrxn** [comment]
If you ask me: Simply don't use HTTPS Everywhere, it's pointless anyway..

**Comment by uBlock-user** [comment]
Vast majority of the websites on the Internet have adopted HTTPS, so what HTTPS everywhere began to do has already been achieved, in the next years, the extension will become useless.

**Comment by SRoyPC** [comment]
Thank you everyone.

**Comment by SRoyPC** [comment]
You'll find this interesting though -
https://gist.github.com/Enegnei/6b13b2d5d0bc7adebb66195f807f3f3b

**Comment by Hrxn** [comment]
That list is totally outdated...

And by the way, if the web server does not support HTTPS, no extension can ever change that.
