### ISSUE TITLE
eleconomista.es - detection

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#17577]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://juegos.eleconomista.es/juegos/mahjongg-solitaire`

### Category

anti adblock

### Description

this site detect the adblocker

### Configuration

```
uBlock Origin: 1.48.8
Chromium: 111
filterset (summary): 
  network: 92338
  cosmetic: 46892
  scriptlet: 21199
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ublock-annoyances: 4935-6, 11m
  default: 
    user-filters: 1-0, never
    easylist: 64541-44, 11m
    easyprivacy: 30817-1177, 11m
    plowe-0: 3750-937, 11m
    spa-0: 3601-11, 11m
    spa-1: 5165-199, 11m
    ublock-abuse: 78-0, 11m
    ublock-badware: 6604-117, 11m
    ublock-filters: 33742-148, 11m
    ublock-privacy: 294-2, 11m
    ublock-quick-fixes: 382-224, 11m
    ublock-unbreak: 1980-44, 11m
    urlhaus-1: 7625-1, 11m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 433 ms (selfie)
  maxAssetCacheWait: 83 ms

```

**Comment by mapx-** [comment]
Test

```
@@||eleconomista.es^$ghide
eleconomista.es##[class^="DisplayAd"]
```

**Comment by mapx-** [comment]
```
@@||eleconomista.es^$ghide
eleconomista.es##[class^="DisplayAd"]
@@||imasdk.googleapis.com/js/sdkloader/*$script,domain=juegos.eleconomista.es
juegos.eleconomista.es##+js(nano-stb)
```

**Comment by gorhill** [comment]
@mapx- This seems to work:

    ||imasdk.googleapis.com/js/sdkloader/*$script,redirect-rule=google-ima.js,domain=juegos.eleconomista.es
