### ISSUE TITLE
thecubexguide.com: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#17570]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://thecubexguide.com/caddy-web-server-vs-nginx/`

### Category

detection

### Description

detection

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50231020/231792497-a87058a9-bd5a-46f3-ae83-25c6b61e8ac2.png)
https://thecubexguide.com/caddy-web-server-vs-nginx/

original link :
https://thecubexguide.com/python-web-server-vs-nginx/

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 125730
  cosmetic: 69634
  scriptlet: 19061
  html: 0
listset (total-discarded, last-updated): 
  added: 
    RUS-0: 39619-166, 2m
  default: 
    user-filters: 0-0, never
    FRA-0: 29054-33, 2m
    easylist: 64539-416, 2m
    easyprivacy: 30816-1577, 2m
    plowe-0: 3750-966, 2m
    ublock-abuse: 78-2, 2m
    ublock-badware: 6589-136, 2m
    ublock-filters: 33730-229, 2m
    ublock-privacy: 294-2, 2m
    ublock-quick-fixes: 382-224, 2m
    ublock-unbreak: 1980-46, 2m
    urlhaus-1: 7625-1, 2m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 693 ms (selfie)
  maxAssetCacheWait: 125 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 1
    legra.ph: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Continue discussion here: https://github.com/uBlockOrigin/uAssets/issues/17548
