### ISSUE TITLE
bongcam.tv: ads

### ISSUE THREAD

**Issue by nhanb2004798** [uBlockOrigin/uAssets#17573]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bongcam.tv/`

### Category

ads

### Description

ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89845
  cosmetic: 40995
  scriptlet: 17746
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 9-0, never
    VIE-1: 1896-0, 6h.56m
    easylist: 64250-56, 1d.17h.27m
    easyprivacy: 30808-1179, 1d.17h.26m
    plowe-0: 3753-937, 8d.15h.11m
    ublock-abuse: 78-0, 8d.15h.10m
    ublock-badware: 6506-115, 1d.17h.25m
    ublock-filters: 33652-116, 1d.17h.24m
    ublock-privacy: 302-2, 8d.15h.9m
    ublock-quick-fixes: 365-212, 6h.55m
    ublock-unbreak: 1975-42, 1d.17h.23m
    urlhaus-1: 7823-1, 6h.57m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 7 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 227 ms (selfie)
  maxAssetCacheWait: 75 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    bongcam.tv: 1
    addthis.com: 1
    googletagmanager.com: 1
    imgur.com: 6
```
</details>

**Comment by Procyon-b** [comment]
Try these:
```
bongcam.tv##.mmo-inner, .vbmodal-asd.show, .vbmodal-asd.show ~ .modal-backdrop
bongcam.tv##body.modal-open:style(overflow: auto !important; padding-right: unset !important;)
```

**Comment by mapx-** [comment]
@hoang-rio

@nhanb2004798 
for other VIE issues
https://github.com/abpvn/abpvn/issues
