### ISSUE TITLE
imgur.com: breakage

### ISSUE THREAD

**Issue by Tape-Worm** [uBlockOrigin/uAssets#17581]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://imgur.com/`

### Category

breakage

### Description

Scrolling is broken when EasyList is enabled, when it is off, it works just fine. I think this is a reoccurrence of a previous error, I noticed that there was a closed issue that's pretty much the same. It working just fine earlier today, all the while showing empty <div> blocks (where the ads were I guess), and now those empty blocks are gone and the scrolling is broken.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.8
Chromium: 112
filterset (summary): 
  network: 89445
  cosmetic: 39829
  scriptlet: 17689
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 8-0, never
    easylist: 64566-44, now
    easyprivacy: 30818-1176, 13m
    plowe-0: 3750-938, 12m
    ublock-abuse: 78-0, 12m
    ublock-badware: 6604-118, 12m
    ublock-filters: 33752-110, 12m
    ublock-privacy: 294-2, 12m
    ublock-quick-fixes: 382-224, 12m
    ublock-unbreak: 1981-43, 12m
    urlhaus-1: 7557-1, 12m
filterset (user): [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 169 ms (selfie)
  maxAssetCacheWait: 52 ms
popupPanel: 
  blocked: 88
  blockedDetails: 
    imgur.com: 5
    assemblyexchange.com: 72
    btloader.com: 1
    facebook.net: 1
    google-analytics.com: 1
    media-lab.ai: 1
    scorecardresearch.com: 1
    stretchsquirrel.com: 1
    xeno-soswcrde4a-uc.a.run.app: 5
```
</details>

**Comment by stephenhawk8054** [comment]
It's because of

```adb
imgur.com##div[style^="height:"]:has(.Post-item-external-ad)
```

@ryanbr We should keep the placeholder or infinite scrolling will break

```adb
imgur.com#@#div[style^="height:"]:has(.Post-item-external-ad)
imgur.com##.Post-item:has(.AdHomeContainer)
```

**Comment by krystian3w** [comment]
EL wrong copied filter, used not allowed syntax:

![image](https://user-images.githubusercontent.com/35370833/231994706-12356bfb-c8e2-4aa9-8b0f-1c431231c43b.png)

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/f59f6059422ad0b3301226e14ef0dfa14ca779d8
