### ISSUE TITLE
ipcimeeting.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#17589]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ipcimeeting.com/`

### Category

detection

### Description

Using ff mobile

https://user-images.githubusercontent.com/19517680/232011534-c780d959-d066-4044-b833-e6d04a2959ad.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox Mobile: 111
filterset (summary): 
  network: 93008
  cosmetic: 56819
  scriptlet: 22768
  html: 1150
listset (total-discarded, last-updated): 
  added: 
    fanboy-cookiemonster: 46656-17513, 1m
    ublock-annoyances: 4958-7, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34877-311, 2m
    ublock-badware: 6602-2, 2m
    ublock-privacy: 344-1, 2m
    ublock-abuse: 78-0, 2m
    ublock-unbreak: 1997-3, 2m
    ublock-quick-fixes: 165-0, 1m
    adguard-mobile: 8767-120, 2m
    easylist: 64571-17483, 1m
    easyprivacy: 30818-1780, 1m
    urlhaus-1: 7557-1, 1m
    plowe-0: 3750-1, 1m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7534 ms
  maxAssetCacheWait: 80 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    ads-twitter.com: 2
    google.com: 1
    googletagmanager.com: 1
    marketo.net: 1
```
</details>

**Comment by krystian3w** [comment]
Try disable ETP and try again: https://mzl.la/3BUXdli

**Comment by mapx-** [comment]
Tested in real android, no detection.

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by 3xploiton3** [comment]
i'm using nextdns, in log doesnt blocking ipcimeeting.com

**Comment by mapx-** [comment]
maybe someone else could reproduce your issue, however do not open other new issues about the same page, continue here if you have other comments.

**Comment by krystian3w** [comment]
You can repaste EasyPrivacy breakage login/register actions: https://github.com/uBlockOrigin/uAssets/issues/17565#user-content-a-shame-by-easyprivacy here: https://github.com/easylist/easylist/issues/new

If page don't down tommorow (locking register new account and disallow login by old).

**Comment by stephenhawk8054** [comment]
> i'm using nextdns, in log doesnt blocking ipcimeeting.com

Blocking something else on the page is usually what causes anti-adb, not blocking main domain does not mean anything.

**Comment by krystian3w** [comment]
Maybe they are unsuccessfully trying to detect a blocked tracker: https://github.com/uBlockOrigin/uAssets/issues/17565#user-content-a-shame-by-easyprivacy

* registration button then doesn't open the pop-up - but it should

* the login button crashes the page on the loading animation - there should be a validation of whether we have an account with their service and a more specific error than the circle animation.

**Comment by gorhill** [comment]
I can reproduce what the screenshot shows when I blocked this resource:

    https://d39ion77s0ucuz.cloudfront.net/in-overlay/loader.js

It's not blocked by any of the list selected by OP. If NextDNS blocks `d39ion77s0ucuz.cloudfront.net`, then the issue is with NextDNS.

**Comment by 3xploiton3** [comment]
yeah, found in OISD & HAGEZI Multi Pro


![image](https://user-images.githubusercontent.com/19517680/232099198-f3f795db-1fed-4a73-b55a-b44342bb8455.png)


> I can reproduce what the screenshot shows when I blocked this resource:
> 
> ```
> https://d39ion77s0ucuz.cloudfront.net/in-overlay/loader.js
> ```
> 
> It's not blocked by any of the list selected by OP. If NextDNS blocks `d39ion77s0ucuz.cloudfront.net`, then the issue is with NextDNS. OP said he checked, but I doubt given his later comment (_"doesnt blocking ipcimeeting.com"_ is not the appropriate thing to check):
> 
> * [x]  I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
> 
> I found that `d39ion77s0ucuz.cloudfront.net` is blocked by some lists, for example: https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Tracking.

**Comment by stephenhawk8054** [comment]
Please truthfully do what you have ticked on

> - [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.

Don't blindly tick on that just for submitting the issue. We put the prerequisites there to eliminate external causes that are not related to uBO
