### ISSUE TITLE
us63.dayforcehcm.com: breakage

### ISSUE THREAD

**Issue by RashadAhmed1** [uBlockOrigin/uAssets#17584]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://us63.dayforcehcm.com/CandidatePortal/u/cp/en-US/CBI/CandidateLogin/AccountSettings`

### Category

breakage

### Description

uBO breaks all DayForceHCM job application pages across multiple companies. The page appears empty with only a header and no content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/22065365/231967382-151fe8aa-cc2a-4376-9c9d-d35114aa3e73.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 160737
  cosmetic: 113207
  scriptlet: 22679
  html: 1109
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    curben-phishing: 67929-31, 11h
    curben-pup: 193-0, 10h.59m
    fanboy-annoyance: 80493-67804, 2d.23h.12m
    fanboy-cookiemonster: 46556-239, 2d.23h.12m
    fanboy-social: 21050-2, 2d.23h.12m
    ublock-annoyances: 4887-4, 2d.23h.12m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34528-256, 2d.23h.12m
    ublock-badware: 6542-0, 2d.23h.12m
    ublock-privacy: 344-0, 2d.23h.12m
    ublock-abuse: 78-0, 2d.23h.12m
    ublock-unbreak: 1980-2, 2d.23h.12m
    ublock-quick-fixes: 380-0, 6h.35m
    easylist: 64250-300, 2d.23h.12m
    easyprivacy: 30808-1182, 2d.23h.12m
    urlhaus-1: 7625-1, 11h.1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 209 ms (selfie)
  maxAssetCacheWait: 120 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    dayforcehcm.com: 1
```
</details>

**Comment by mapx-** [comment]
FA issue

@RashadAhmed1 

add & test

```
@@||dayforcehcm.com/*/CookieBanner.js$script,1p
@@||dayforcehcm.com/CandidatePortal/*/CookieBanner.html$xhr,1p
```

@ryanbr

**Comment by RashadAhmed1** [comment]
> FA issue
> 
> @RashadAhmed1
> 
> add & test
> 
> ```
> @@||dayforcehcm.com/*/CookieBanner.js$script,1p
> @@||dayforcehcm.com/CandidatePortal/*/CookieBanner.html$xhr,1p
> ```
> 
> @ryanbr

This fixed the issue, thank you.
