### ISSUE TITLE
portal.energie-graz.at: breakage

### ISSUE THREAD

**Issue by ExteriorCloth20** [uBlockOrigin/uAssets#17580]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://portal.energie-graz.at/kundenportal/`

### Category

breakage

### Description

The breakage is caused by filter: "/cookieconsent.$~stylesheet". Both EasyList Cookie and Fanboy's Annoyances use this filter. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 201863
  cosmetic: 230004
  scriptlet: 39623
  html: 1111
listset (total-discarded, last-updated): 
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 935-0, 23h.9m
    adguard-generic: 69752-5368, 1d.22h.59m
    adguard-mobile: 8754-128, 1d.23h.3m
    adguard-spyware-url: 976-5, 1d.22h.57m
    block-lan: 44-0, 19d.13h.7m
    curben-phishing: 68103-32, 23h.13m
    curben-pup: 199-0, 23h.14m
    adguard-annoyance: 67096-5129, 1d.22h.47m
    adguard-social: 20221-914, 1d.22h.46m
    fanboy-annoyance: 80566-69597, 23h.16m
    fanboy-cookiemonster: 46617-240, 23h.15m
    fanboy-social: 21052-6, 1d.22h.45m
    ublock-annoyances: 4882-4, 1d.22h.44m
    dpollock-0: 11349-470, 8d.8h.34m
    DEU-0: 6753-11, 23h.10m
  default: 
    user-filters: 32-0, never
    ublock-filters: 34574-290, 1d.23h.2m
    ublock-badware: 6542-0, 1d.23h.1m
    ublock-privacy: 352-0, 11d.9h.21m
    ublock-abuse: 78-0, 11d.9h.20m
    ublock-unbreak: 1981-0, 1d.23h
    ublock-quick-fixes: 371-2, 23h.12m
    easylist: 64250-834, 1d.22h.58m
    easyprivacy: 30810-1880, 1d.22h.48m
    urlhaus-1: 7823-1, 23h.11m
    plowe-0: 3750-3, 6d.7h.1m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 543 ms (selfie)
  maxAssetCacheWait: 264 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    energie-graz.at: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||portal.energie-graz.at/kundenportal/js/lib/cookieconsent.js$script,domain=portal.energie-graz.at
```

@ryanbr
