### ISSUE TITLE
linkvertise.com: ads

### ISSUE THREAD

**Issue by Hoangnguyen72628** [uBlockOrigin/uAssets#17587]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/530799/fluxus-android-free2`

### Category

ads

### Description

Please fix UBlock Origin when linkvertise is not appearing free access button again...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium Mobile: 111
filterset (summary): 
  network: 91437
  cosmetic: 31223
  scriptlet: 17870
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    VIE-1: 1898-15, 40m
    adguard-mobile: 8767-33, 40m
    easylist: 64539-16909, 37m
    easyprivacy: 30810-1189, 36m
    plowe-0: 3750-1021, 35m
    ublock-abuse: 78-0, 33m
    ublock-badware: 6598-118, 31m
    ublock-filters: 33965-363, 30m
    ublock-privacy: 294-3, 29m
    ublock-quick-fixes: 386-230, 28m
    ublock-unbreak: 1986-45, 27m
    urlhaus-1: 7557-1, 26m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7392 ms (selfie)
  maxAssetCacheWait: 2764 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    bizseasky.com: 2
    taboola.com: 2
    thinksuggest.org: 2
    typekit.net: 1
```
</details>

**Comment by mapx-** [comment]
>  is not appearing free access button 

![image](https://user-images.githubusercontent.com/10303732/231993288-ecc6e1e4-14ca-43fe-8739-5505fe53ecec.png)
