### ISSUE TITLE
adt598.com: ads

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#17582]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`adt598.com` running on the background of `pcgamingwiki.com`. Seems to be an ad server.

Seems to be related to `adtraction.com`, which is blocked in Peter Lowe's list.

### URL(s) where the issue occurs.

`https://www.pcgamingwiki.com/wiki/Home`

### uBO version

1.48.4

### Browser name and version

Firefox 112.0 (64-bit)

### Settings

<details><spoiler>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 105143
  cosmetic: 170472
  scriptlet: 25531
  html: 1109
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 710-9, 8h.32m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2154-80, 8h.31m
    adguard-spyware-url: 976-169, 2d.5h.29m
    adguard-annoyance: 67096-5989, 2d.5h.25m
    fanboy-thirdparty_social: 69-0, 1d.6h.27m
    fanboy-annoyance: 80517-489, 1d.6h.26m
    ublock-annoyances: 4887-4, 2d.5h.24m
    spa-1: 5164-11, 2d.5h.23m
  default: 
    user-filters: 67-0, never
    ublock-filters: 34342-106, 2d.7h.40m
    ublock-badware: 6542-0, 2d.5h.32m
    ublock-privacy: 352-2, 6d.9h.16m
    ublock-abuse: 78-0, 6d.9h.15m
    ublock-unbreak: 1980-2, 2d.5h.31m
    ublock-quick-fixes: 382-0, 8h.34m
    easylist: 64250-668, 2d.5h.30m
    easyprivacy: 30808-1785, 2d.5h.28m
    urlhaus-1: 7625-1, 8h.33m
    plowe-0: 3750-3, 6d.9h.14m
filterset (user): [array of 67 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 377 ms (selfie)
  maxAssetCacheWait: 119 ms
```

</spoiler></details>

### Notes

Additional resource: `https://sorcerers.net/community/threads/receiving-a-warning-from-my-anti-virus-saying-this-website-is-infected.93694/`

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/26e259f906ea05616092c55b3151001d703c469a

**Comment by DandelionSprout** [comment]
My loose understanding is that it is in some way related to GOG.com's `af.gog.com` affiliate links using Adtraction. But it's a complete mystery to me too why that script is on PCGamingWiki itself despite me holding Senior Editor status there.

**Comment by DandelionSprout** [comment]
I've received some clarification since then, and it appears to be caused by a "Clearlinks" system created by Adtraction, which purportedly allows affiliate links to not need to be redirected through `adtraction.com` when clicked on.

The script also doesn't seem to be crucial to site functionality, nor for Adtraction to consider an affiliate link purchase to be valid, so I have no objections to the blocking of the script.
