### ISSUE TITLE
mapcarta.com: breakage

### ISSUE THREAD

**Issue by ExteriorCloth20** [uBlockOrigin/uAssets#17595]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mapcarta.com/de/Graz`

### Category

breakage

### Description

Breakage is caused by AdGuard Annoyances. The filter blocks the cookie popup but can't click on content.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 202055
  cosmetic: 229937
  scriptlet: 39680
  html: 1112
listset (total-discarded, last-updated): 
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 935-0, 9h.33m
    adguard-generic: 69852-5419, 9h.33m
    adguard-mobile: 8763-136, 9h.33m
    adguard-spyware-url: 976-4, 9h.33m
    block-lan: 47-0, 9h.33m
    curben-phishing: 68125-32, 9h.33m
    curben-pup: 199-0, 9h.33m
    adguard-annoyance: 67226-6816, 9h.33m
    adguard-social: 20256-883, 9h.33m
    fanboy-annoyance: 80221-67547, 9h.33m
    fanboy-cookiemonster: 46654-240, 9h.33m
    fanboy-social: 20672-2, 9h.33m
    ublock-annoyances: 4899-4, 9h.33m
    dpollock-0: 11354-470, 9h.33m
    DEU-0: 6770-3, 9h.33m
  default: 
    user-filters: 32-0, never
    ublock-filters: 34629-295, 9h.33m
    ublock-badware: 6608-2, 9h.33m
    ublock-privacy: 344-0, 9h.33m
    ublock-abuse: 78-0, 9h.33m
    ublock-unbreak: 1992-4, 9h.33m
    ublock-quick-fixes: 382-0, 9h.33m
    easylist: 64566-833, 9h.33m
    easyprivacy: 30818-1881, 9h.33m
    urlhaus-1: 7557-1, 9h.33m
    plowe-0: 3750-1, 9h.33m
filterset (user): [array of 32 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 416 ms (selfie)
  maxAssetCacheWait: 295 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    google-analytics.com: 1
```
</details>

**Comment by Alex-302** [comment]
Fixed in AdGuard Annoyances.
