### ISSUE TITLE
mdn.lol: breakage

### ISSUE THREAD

**Issue by kaiji05** [uBlockOrigin/uAssets#17597]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mdn.lol/2022/12/28/what-is-bounce-rate-how-to-decrease-it/`
or first link
`https://clks.pro/OWfn9v7hnit`

### Category

breakage

### Description

I use uBo origin to open the link, thank you, it doesn't detect adblock. I just want to ask, how do I keep the timer running? and i use chrome in PC
![image](https://user-images.githubusercontent.com/108754068/232120957-4da814ab-d68e-42e1-8a08-5eb944492b2e.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89164
  cosmetic: 39825
  scriptlet: 17701
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 5-0, never
    easylist: 64586-44, 3m
    easyprivacy: 30819-1176, 2m
    plowe-0: 3748-939, 2m
    ublock-abuse: 70-0, 2m
    ublock-badware: 6610-118, 2m
    ublock-filters: 33723-96, 2m
    ublock-privacy: 294-2, 2m
    ublock-quick-fixes: 182-26, 2m
    ublock-unbreak: 1986-46, 2m
    urlhaus-1: 7285-1, 2m
filterset (user): [array of 5 redacted]
trustedset: 
  added: [array of 18 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8450 ms
  maxAssetCacheWait: 5635 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    clickiocdn.com: 3
    doubleclick.net: 1
    googletagmanager.com: 3
    hbagency.it: 2
    pbstck.com: 1
    t.co: 2
    wtg-ads.com: 1
```
</details>

**Comment by mapx-** [comment]
this is the place for these sites
https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by kaiji05** [comment]
> this is the place for these sites #17361

thanks for info, but i not see the solution for that issue.

**Comment by stephenhawk8054** [comment]
> thanks for info, but i not see the solution for that issue.

That is discussion section, anyone willing to help will help you, otherwise you'll have to wait.
