### ISSUE TITLE
namepros.com: ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17590]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.namepros.com/threads/what-happened-with-epik.1299855/`

### Category

ads

### Description

`namepros.com##[href^="/bevt/click/"]`
```
Dynadot, NameSilo, Escrow, Sav, BBOnline ads
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 80333
  cosmetic: 42865
  scriptlet: 21289
  html: 1114
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 22h.1m
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1552-0, 22h.1m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 22h.1m
    ublock-annoyances: 4899-4, 22h.1m
  default: 
    user-filters: 1681-13, never
    ublock-filters: 34627-271, 2h.38m
    ublock-badware: 6593-0, 22h.1m
    ublock-privacy: 344-0, 22h.1m
    ublock-abuse: 70-0, 18m
    ublock-unbreak: 1992-2, 18m
    ublock-quick-fixes: 382-0, 22h.1m
    easylist: 64539-279, 22h.1m
    easyprivacy: 30814-2198, 22h.1m
filterset (user): [array of 710 redacted]
switchRuleset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 335 ms (selfie)
  maxAssetCacheWait: 142 ms
  unsuspendAfter: 132 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    cloudflareinsights.com: 2
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
You should report directly at [easylist repository](https://github.com/easylist/easylist/issues)

@ryanbr

**Comment by Daxy7** [comment]
ad-reinsertion unchecked in EL
```
https://www.namepros.com/threads/domain-investing.1137790/
```
```
namepros.com##.backer
namepros.com##.np--shadow
namepros.com##.np-iu34fdg
namepros.com##[data-np-ga-event="ad"]
namepros.com##a[data-tag="backer"]
||nameproscdn.com/images/backers/
! to
namepros.com##.np-SFj2v
namepros.com##.np--zhvojhc
namepros.com##.np-iu34fdg
namepros.com##[data-xf-init="np-ad"]
namepros.com##a[data-tag="backer2"]
||nameproscdn.com/images/backers2/
! letters in ad dimensions
/2024-01-30_1020x60n5.png
/bevt/click/GritBrokerage20240205n2
```
https://github.com/easylist/easylist/issues/17891

**Comment by Daxy7** [comment]
@JobcenterTycoon Sorry, but what do you think?

**Comment by JobcenterTycoon** [comment]
Its not ad reinsertion, i get the same code even with disabled adblocker.

**Comment by Daxy7** [comment]
i mean they renamed the urls such as `backers` to `backers2` when a year ago it was `backers` as seen in EL

**Comment by JobcenterTycoon** [comment]
Ok i pinged ryanbr lets see if they try to circumvent.

**Comment by Daxy7** [comment]
https://github.com/easylist/easylist/commit/2ca15a42fdf70030b14fd8b82635733418849bd1

**Comment by Daxy7** [comment]
@ryanbr ads are unhidden again with subsequently none of the old cosmetic filters working
`https://www.namepros.com/threads/domain-investing.1137790/`
`||nameproscdn.com/images/backers2/`
`namepros.com##.np--zhvojhc`
