### ISSUE TITLE
esportal.com: breakage

### ISSUE THREAD

**Issue by magnusvmt** [uBlockOrigin/uAssets#17591]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://esportal.com/en/home`

### Category

breakage

### Description

Won't let you into the site if ublock origin is enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 121101
  cosmetic: 203466
  scriptlet: 39638
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2988-10, 6m
    SWE-1: 4380-0, 6m
    adguard-annoyance: 67239-184, 6m
    adguard-generic: 69860-583, 6m
    fanboy-annoyance: 80111-5671, 6m
    fanboy-cookiemonster: 46656-46656, 6m
    fanboy-thirdparty_social: 69-19, 6m
    ublock-annoyances: 4935-258, 6m
  default: 
    user-filters: 0-0, never
    easylist: 64583-897, 6m
    easyprivacy: 30819-1417, 6m
    plowe-0: 3748-954, 6m
    ublock-abuse: 70-0, 6m
    ublock-badware: 6610-338, 5m
    ublock-filters: 33731-4146, 5m
    ublock-privacy: 294-4, 5m
    ublock-quick-fixes: 179-32, 5m
    ublock-unbreak: 1986-97, 5m
    urlhaus-1: 7557-1, 5m
filterset (user): [empty]
trustedset: 
  added: [array of 28 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 749 ms (selfie)
  maxAssetCacheWait: 497 ms
popupPanel: 
  blocked: 12
  no-cosmetic-filtering: true
  blockedDetails: 
    esportal.com: 1
    airbrake.io: 2
    d2v02itv0y9u9t.cloudfront.net: 1
    doubleclick.net: 4
    fuseplatform.net: 1
    googletagmanager.com: 1
    imrworldwide.com: 1
    ttvnw.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||esportal.com/assets/TwitterIcon.*.js$script,1p`

FA issue
@ryanbr

**Comment by magnusvmt** [comment]
Wow, that was quick. Thank you!
