### ISSUE TITLE
m.timesofindia.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#176]
**Anti adb warning** on **http://m.timesofindia.com/**, produced using **Dev Tools**. The fix reported here: https://github.com/uBlockOrigin/uAssets/issues/104 does not work.

**Error URL:** http://m.timesofindia.com/world/china/Seven-killed-94-injured-in-massive-explosion-in-China/articleshow/55034514.cms

**Comment by gorhill** [comment]
No warning here using default settings/lists.

**Comment by gotitbro** [comment]
@gorhill Problem on my side (AdsBypasser script). Sorry for the trouble.

**Comment by gotitbro** [comment]
Still getting the anti adb warning on articles under http://m.photos.timesofindia.com/.

**Error URL:** http://m.photos.timesofindia.com/movies/international/jack-reacher-never-go-back/Untitled-6-jpg/articleshow/54956893.cms

There is no problem on my side, checked thoroughly.

**Comment by ghajini** [comment]
@gorhill moving animations seen at 
http://timesofindia.indiatimes.com/world
see in screenshot
![screenshot 46](https://cloud.githubusercontent.com/assets/20338483/20239728/57528d50-a92d-11e6-9ab5-c07a7452849b.png)

**Comment by gotitbro** [comment]
@ghajini Can be resolved by:
`indiatimes.com##[data-cb="processCtnAds"]`
