### ISSUE TITLE
udemy.com: breakage

### ISSUE THREAD

**Issue by heapifyman** [uBlockOrigin/uAssets#17608]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.udemy.com/join/login-popup/?next=/home/my-courses/learning/`

### Category

breakage

### Description

MFA (multi-factor authentication) is enabled for the account - udemy sends a code via email.

Nothing happens after entering correct email and password and hitting "Log In" button, browser remains on the login page.

But login was successful because I do receive the MFA code via email.

If I *dis*able ublock origin for udemy and then log in with mail and password, I am forwarded to the next page where I can enter the MFA code I received via email, and successfully complete the login.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 161569
  cosmetic: 39889
  scriptlet: 17724
  html: 949
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34687-63, 3m
    ublock-badware: 6655-0, 3m
    ublock-privacy: 345-0, 3m
    ublock-abuse: 70-0, 3m
    ublock-unbreak: 1997-7, 3m
    ublock-quick-fixes: 178-0, 3m
    easylist: 64817-608, 3m
    adguard-spyware-url: 977-5, 3m
    easyprivacy: 30856-1772, 3m
    urlhaus-1: 7012-1, 3m
    curben-phishing: 69413-31, 3m
    plowe-0: 3748-3, 3m
    LegitimateURLShortener: 2175-137, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 300 ms (selfie)
  maxAssetCacheWait: 133 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    udemy.com: 1
    datadoghq-browser-agent.com: 1
    googletagmanager.com: 1
    perimeterx.net: 1
    sift.com: 1
```
</details>

**Comment by peace2000** [comment]
No issues with defaults when using a test account.

The issue is caused by this list:

`LegitimateURLShortener`

By this rule:

`*$removeparam=response_type,from=udemy.com`

@DandelionSprout

**Comment by iam-py-test** [comment]
Fixed, thanks @peace2000 
@heapifyman in the future, issues caused by Legitimate URL Shortener should be reported at https://github.com/DandelionSprout/adfilt/discussions/163. I don't get notifications for issues here (there are just too many and 99% of them aren't relevant to me).

Maybe a note should be made for LibreWolf, [as it customizes the default lists](https://librewolf.net/docs/addons/#ublock-origin-tweaks), making the "use default lists" checkbox unneeded.
