### ISSUE TITLE
darksoftware.net: detection

### ISSUE THREAD

**Issue by Jabahhh** [uBlockOrigin/uAssets#17609]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://darksoftware.net/forums/switch-nsp-xci-roms.50/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.8
Chromium: 112
filterset (summary): 
  network: 90268
  cosmetic: 43202
  scriptlet: 17978
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 22h.59m
  default: 
    user-filters: 75-14, never
    easylist: 64250-47, 3d.6h.10m
    easyprivacy: 30810-1177, 1d.9h.51m
    plowe-0: 3753-937, 9d.5h.4m
    spa-1: 5170-69, 1h.44m
    ublock-abuse: 78-0, 4d.5h.35m
    ublock-badware: 6610-117, 21h.28m
    ublock-filters: 33710-142, 21h.29m
    ublock-privacy: 294-2, 4d.5h.36m
    ublock-quick-fixes: 179-26, 22h.57m
    ublock-unbreak: 1986-46, 1h.45m
    urlhaus-1: 7285-1, 22h.58m
filterset (user): [array of 75 redacted]
trustedset: 
  added: [array of 10 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 310 ms (selfie)
  maxAssetCacheWait: 51 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    add.pics: 1
    d3hv9xfqzxy46o.cloudfront.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
```
</details>

**Comment by gorhill** [comment]
How does the detection looks like? Does it require to be logged in?

Note: remove `anti-adblock-killer-filters.txt`, it's blacklisted by uBO, no filters are loaded from it, this list has ceased to be maintained years ago.

**Comment by mapx-** [comment]
```
<script>
   XV.ad_block = 1;
   XV.ad_text = "Please disable or add a whitelist at the AdBlock extension!";
   window.onload = function() {
   XV.ad_block = 1;
   XV.ad_block && "undefined" == typeof xv_loaded && $('.p-body-main').html('<h1>'+XV.ad_text+'</h1>');
   }
   function xv_read_ad_135879() {
   XV.ad_block = 1;
   }
</script>
```
