### ISSUE TITLE
allprizesforme.com: ads

### ISSUE THREAD

**Issue by vladi-it** [uBlockOrigin/uAssets#17602]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://allprizesforme.com/`

### Category

ads

### Description

asks info

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 95349
  cosmetic: 47616
  scriptlet: 17675
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ITA-0: 13548-0, 1d.19h.25m
    easylist: 64539-50, 1d.11h.24m
    easyprivacy: 30803-1178, 3d.3h.37m
    plowe-0: 3751-938, 13d.21h.12m
    ublock-abuse: 78-0, 2d.3h.29m
    ublock-badware: 6579-116, 2d.11h.33m
    ublock-filters: 33713-120, 2d.11h.32m
    ublock-privacy: 294-2, 2d.3h.28m
    ublock-quick-fixes: 380-225, 1d.19h.27m
    ublock-unbreak: 1976-42, 2d.11h.31m
    urlhaus-1: 7823-1, 1d.19h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 876 ms (selfie)
  maxAssetCacheWait: 352 ms
popupPanel: 
  blocked: 1
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    woudaufe.net: 1
```
</details>

**Comment by mapx-** [comment]
>   no-cosmetic-filtering: true
>   no-large-media: true
>   no-popups: true
>   no-remote-fonts: true
>   no-scripting: true

- You probably landed on that site clicking on some other page, which one ?
- You have strongly personalized settings

**Comment by Daxy7** [comment]
>    You probably landed on that site clicking on some other page

Checking [virustotal](https://www.virustotal.com/gui/url/832406246d213f223b5d4ad0b7442874d0bf677618d7e7cb6df833e40fd743c2/detection) scan it's very likely malicious popup

**Comment by mapx-** [comment]
added to badware, but it would be useful to know the initial navigation page
