### ISSUE TITLE
tvtropes.org: detection

### ISSUE THREAD

**Issue by mjp1050** [uBlockOrigin/uAssets#17601]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tvtropes.org/`

### Category

detection

### Description

The website `https://tvtropes.org` detects Ublock Origin and shows an adblocker banner at the bottom of the page. 

This is a new banner; while TvTropes has had adblock banners in the past, TvTropes has not shown this specific banner previously.

### Screenshot(s)

<details>
<summary>A screenshot of the TvTropes homepage, showing the ad blocker detection at the bottom of the page. </summary>

![image](https://user-images.githubusercontent.com/24399252/232183899-0fe74ec2-d22c-460c-b9fb-e4fdcdecefc2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 110
filterset (summary): 
  network: 88955
  cosmetic: 39780
  scriptlet: 17683
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64387-47, 2d.5h.13m
    easyprivacy: 30807-1177, 2d.5h.14m
    plowe-0: 3748-937, 10h.16m
    ublock-abuse: 70-0, 10h.17m
    ublock-badware: 6589-117, 2d.5h.11m
    ublock-filters: 33713-111, 2d.5h.12m
    ublock-privacy: 294-2, 10h.18m
    ublock-quick-fixes: 179-26, 10h.14m
    ublock-unbreak: 1976-42, 2d.5h.10m
    urlhaus-1: 7285-1, 10h.13m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 11 redacted]
modifiedUserSettings: 
  collapseBlocked: false
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 573 ms (selfie)
  maxAssetCacheWait: 132 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    ad.gt: 1
    doubleclick.net: 1
    google-analytics.com: 1
    google.com: 6
    googletagmanager.com: 1
    htlbid.com: 1
    quantserve.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce

**Comment by gorhill** [comment]
I can reproduce when I enable ABP long uBO, so unfortunately it might be another case of blindly checking and not taking seriously the prerequisite step:

- [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by mjp1050** [comment]
The conflict was caused by user error on my part; I neglected to disable Vivaldi's built-in adblocker. Disabling it resolves the issue. I've unchecked the box above to reflect this.

Thank you all for helping me solve my issue. Your help is appreciated, even though my bug report was made in error.

**Comment by splatana** [comment]
Having a similar issue with this banner. It does appear to randomise its element name so you can't block it via a custom filter
Performed all of the steps that Mapx has commented, still have the issue. Doesn't appear to be caused by other extensions, Firefox's tracking protection, cookies or cache etc etc.
Worth noting that the banner appeared randomly during after I opened a new tvtropes page. I was on one before, clicking on a link to a new page then caused the banner to pop up. So it seems to potentially be a new thing?
This is on Firefox by the way.

Posting this as I think my issue is similar enough that it would be better posting this and not making another post.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/90976c6769266ead2edbbf21bf9a8a1fa535a3f6

**Comment by dartigen** [comment]
I've had a potentially related issue - TVTropes.org still displays the 'please allow ads on our site' splash/banner no matter what I do, including disabling uBlock Origin for the site. However, I've also found several reddit and TVtropes forums posts saying that the site is prone to throwing false positives for adblock detection; I don't think anyone had found exactly what's causing it. If I stop the page from loading the whole way, I can stop it from covering up the page, but I have to be pretty quick on it. 

So, it doesn't seem to be uBlock Origin that's doing it. (The banner has also changed, it now completely blocks the content of the page which makes it super annoying.)

**Comment by stephenhawk8054** [comment]
Continue here: https://github.com/uBlockOrigin/uAssets/issues/30529
