### ISSUE TITLE
it.wallapop.com: breakage

### ISSUE THREAD

**Issue by cesarinik** [uBlockOrigin/uAssets#17606]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://it.wallapop.com/`

### Category

breakage

### Description

Problem with page load and login. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 94689
  cosmetic: 47569
  scriptlet: 17656
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 6-0, never
    ITA-0: 13553-0, 23h.15m
    easylist: 64390-53, 2d.23h.36m
    easyprivacy: 30807-1178, 2d.23h.35m
    plowe-0: 3750-938, 2d.23h.34m
    ublock-abuse: 78-0, 2d.23h.32m
    ublock-badware: 6584-117, 2d.23h.30m
    ublock-filters: 33654-118, 2d.23h.29m
    ublock-privacy: 294-2, 2d.23h.28m
    ublock-quick-fixes: 179-21, 23h.14m
    ublock-unbreak: 1976-42, 2d.23h.26m
    urlhaus-1: 7285-1, 23h.13m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  collapseBlocked: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 701 ms (selfie)
  maxAssetCacheWait: 294 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    mparticle.com: 3
    sentry.io: 1
```
</details>

**Comment by krystian3w** [comment]
Works fine without EL Italy.

**Comment by krystian3w** [comment]
To unlock load `https://it.wallapop.com/app/catalog/list` possible override:

https://github.com/uBlockOrigin/uAssets/blob/0a66336f37fa1293fc728ff3c98ddef3e3014fa9/filters/unbreak.txt#L2992-L2994

Same filter now exist in EP.

**Comment by cesarinik** [comment]
Hi! In fact, I also checked the block list and after whitelisting that domain (mparticle) the Wallapop italian site works normally and does not block with blank page during login. I just wanted to report the issue for other users

**Comment by mapx-** [comment]
Even whitelisting the site I cannot access my account (wrong username / pass)

**Comment by krystian3w** [comment]
So reset password?

**Comment by stephenhawk8054** [comment]
I tried reset password but it still says wrong username or password
