### ISSUE TITLE
luko.eu: breakage

### ISSUE THREAD

**Issue by bagage** [uBlockOrigin/uAssets#17605]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.luko.eu/my-account/`

### Category

breakage

### Description

When uBlockOrigin is enabled, the chat icon on the bottom right is removed preventing me from contacting the support.

As soon as UBO is disabled, the button is displayed and can be used properly.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/1451988/232222911-f3c4a45b-c238-4659-8172-0a842afa1815.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 108686
  cosmetic: 48631
  scriptlet: 17772
  html: 948
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34588-352, 1d.17h.45m
    ublock-badware: 6593-0, 1d.17h.43m
    ublock-privacy: 352-0, 7d.19h.17m
    ublock-abuse: 78-0, 7d.19h.16m
    ublock-unbreak: 1991-2, 1d.17h.44m
    ublock-quick-fixes: 380-0, 1d.17h.40m
    easylist: 64539-973, 1d.17h.42m
    easyprivacy: 30803-1770, 4d.15h.34m
    urlhaus-1: 7625-1, 1d.17h.39m
    plowe-0: 3750-3, 1d.17h.47m
    FRA-0: 29054-389, 1d.17h.46m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 396 ms (selfie)
  maxAssetCacheWait: 109 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    braze.eu: 2
    googletagmanager.com: 1
    sentry.io: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you do these steps:

- Click on ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger) on the [popup user interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface), 
- Reload the page where issue happens,
- Go to the logger again, [click on search bar and choose `blocked`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output),
- Copy the logger via [export/copy button at the right](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output),
- Paste the logs here

**Comment by bagage** [comment]
I'm pretty impressed by your bug report procedure (both issue template and tooling), it's pretty amazing! 

Thanks @stephenhawk8054, Here it is:

<details><summary>Logger output</summary>

```
+22
||braze.eu^
--
www.luko.eu
3
post
xhr
https://sdk.fra-01.braze.eu/api/v3/data/
```
```
+10
||sentry.io^$3p
--
www.luko.eu
3
post
beacon
https://o163378.ingest.sentry.io/api/5246380/envelope/?sentry_key=ee588718489c4593be7c70b268328184&sentry_version=7
```
```
+2
||braze.eu^
--
www.luko.eu
3
post
xhr
https://sdk.fra-01.braze.eu/api/v3/data/
```
```
+1
googletagmanager_gtm.js
<<
www.luko.eu
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-55T493N
```
```
+1
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
www.luko.eu
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-55T493N
```
```
+1
||googletagmanager.com^
--
www.luko.eu
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-55T493N
```
```
+1
||sentry.io^$3p
--
www.luko.eu
3
post
xhr
https://o163378.ingest.sentry.io/api/5246380/envelope/?sentry_key=ee588718489c4593be7c70b268328184&sentry_version=7
```
```
+0
||sentry.io^$3p
--
www.luko.eu
3
post
beacon
https://o163378.ingest.sentry.io/api/5246380/envelope/?sentry_key=ee588718489c4593be7c70b268328184&sentry_version=7
```
```
+0
https://www.luko.eu/my-account/
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters, one-by-one?

```adb
@@||braze.eu/api/v*/data/$xhr,domain=luko.eu
@@||googletagmanager.com/gtm.js$script,domain=luko.eu
```

Add in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click `Apply changes`, go back to the website and press Ctrl + F5 to reload the page and test again.

(Test each line one by one so we can see which one causes the issue)

**Comment by bagage** [comment]
Yes it is this one:

```
@@||googletagmanager.com/gtm.js$script,domain=luko.eu
```

When allowed, the button is shown again.

**Comment by stephenhawk8054** [comment]
Thanks for your feedback. We'll inform EasyList maintainer to fix it.

---

@ryanbr

**Comment by bagage** [comment]
Thanks @stephenhawk8054, that was impressive :+1:
