### ISSUE TITLE
menetrendek.hu: ads

### ISSUE THREAD

**Issue by RozvM** [uBlockOrigin/uAssets#17604]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://menetrendek.hu/`

### Category

ads

### Description

Only removes ads with the [HUN filter](https://github.com/hufilter/hufilter), and if that is enabled it removes the whole footer too.

Related issue: https://github.com/hufilter/hufilter/issues/16

### Screenshot(s)

<details>
<summary>Screenshot(s):</summary>

![image](https://user-images.githubusercontent.com/74600479/232209327-4046af66-0ac2-4ff9-bf87-06970a598550.png)
![image](https://user-images.githubusercontent.com/74600479/232209676-875cf062-30e3-42fd-84ff-a62c00b868d8.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 91681
  cosmetic: 53306
  scriptlet: 17930
  html: 964
listset (total-discarded, last-updated): 
  added: 
    HUN-0: 2185-5, 15h.47m
    JPN-1: 10630-24, 3d.22h.53m
    KOR-1: 4241-42, 15h.48m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34528-259, 3d.22h.56m
    ublock-badware: 6542-0, 3d.22h.55m
    ublock-privacy: 352-0, 9d.14h.12m
    ublock-abuse: 78-0, 9d.14h.14m
    ublock-unbreak: 1980-2, 3d.22h.54m
    easylist: 64100-642, 3d.22h.57m
    easyprivacy: 30808-1811, 3d.22h.58m
    urlhaus-1: 7285-1, 15h.50m
    plowe-0: 3753-3, 9d.14h.13m
    ublock-quick-fixes: 361-0, 15h.49m
filterset (user): [empty]
trustedset: 
  added: [array of 895 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  cloudStorageEnabled: true
  colorBlindFriendly: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 461 ms (selfie)
  maxAssetCacheWait: 246 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    adocean.pl: 3
    gemius.pl: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
You already reported at regional list repository, closing here.
