### ISSUE TITLE
animesrbija.com: ads

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#17617]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.animesrbija.com/epizoda/dragon-ball-epizoda-2`

### Category

ads

### Description

Website shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 88856
  cosmetic: 39805
  scriptlet: 17699
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64539-44, 1d.2h.45m
    easyprivacy: 30823-1177, 1d.2h.44m
    plowe-0: 3748-938, 1h.49m
    ublock-abuse: 70-0, 1h.48m
    ublock-badware: 6604-117, 1d.2h.43m
    ublock-filters: 33723-96, 1d.2h.42m
    ublock-privacy: 294-2, 1h.47m
    ublock-quick-fixes: 179-26, 1h.46m
    ublock-unbreak: 1986-46, 1d.2h.41m
    urlhaus-1: 7012-1, 1h.45m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 410 ms (selfie)
  maxAssetCacheWait: 126 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    antiadblocksystems.com: 1
    d3cod80thn7qnd.cloudfront.net: 1
    google-analytics.com: 2
    googletagmanager.com: 1
    onesignal.com: 1
    taboola.com: 2
```
</details>

**Comment by Procyon-b** [comment]
Try this:
```
animesrbija.com##.horizontal-banners
```

**Comment by mapx-** [comment]
@DandelionSprout 

@GKid94 for croatian / serbian sites enable this list: `HRV, SRB: Dandelion Sprout's Serbo-Croatian filters`
