### ISSUE TITLE
ikea.com.tr: breakage

### ISSUE THREAD

**Issue by M4gn3tic** [uBlockOrigin/uAssets#17615]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ikea.com.tr/yeni-urunler`

### Category

breakage

### Description

I cannot see products at above. i tried with "Chrome" without any ublock extensions and its opens normally.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ekran Alıntısı](https://user-images.githubusercontent.com/130873389/232256315-88fdda2b-7655-41a6-9df4-021f91cb52f1.JPG)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 90403
  cosmetic: 48948
  scriptlet: 18940
  html: 946
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34559-63, 3d.6h.3m
    ublock-badware: 6588-0, 3d.6h.5m
    ublock-privacy: 344-0, 3d.6h.9m
    ublock-abuse: 78-0, 3d.6h.8m
    ublock-unbreak: 1987-0, 3d.6h.2m
    easylist: 64387-642, 3d.6h.7m
    easyprivacy: 30807-1775, 3d.6h.6m
    urlhaus-1: 7012-1, 9h.2m
    plowe-0: 3748-3, 9h.3m
    TUR-0: 12219-12, 3d.6h.4m
    ublock-quick-fixes: 178-2, 9h.1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 628 ms (selfie)
  maxAssetCacheWait: 97 ms
popupPanel: 
  blocked: 12
  no-popups: true
  blockedDetails: 
    criteo.net: 1
    google.com: 2
    googleadservices.com: 4
    googletagmanager.com: 2
    personaclick.com: 3
```
</details>

**Comment by iam-py-test** [comment]
Broken by:
```adblock
||analytics.google.com^$3p
```
Fix:
```adblock
||analytics.google.com/g/collect$redirect-rule=noop.txt
```

**Comment by Procyon-b** [comment]
I think that it's a site issue. I open the page in a private window and the result is inconstant.
I try without ublock and the page loads. I close the window, then try again and it doesn't display the products.

**Comment by gorhill** [comment]
As soon as I disabled uBO it loads fine though.

**Comment by Procyon-b** [comment]
I had that too on my first tests. But then it wouldn't display on opening in a new tab, but worked on reloading the page. Then I tried in private to get rid of cache & cookies, and that's when the site started to behave weird after several tests.

**Comment by gorhill** [comment]
Disabling cache works too (from dev tools), so might be a timing issue.

**Comment by Procyon-b** [comment]
I've tested again with ublock enabled (with regional TUR enabled), and with ublock disabled.
In both cases I have the products hidden (sometimes, once in 10-20 tries it loads properly).

- I then click "Internetten Satilanlar".
- The items appear.
- I click the button "x  Internetten Satilanlar" to clear the display,
- The items stay visible.

**Comment by krystian3w** [comment]
@ikea fyi!

**Comment by peace2000** [comment]
On Firefox, no issues with uBO if I load the site in private browsing mode.

If not, these filters are needed:
```
@@||www.googleadservices.com/pagead/conversion.js$script,domain=ikea.com.tr
@@||www.googletagmanager.com/gtm.js$script,domain=ikea.com.tr
```
To get it work on the first page load. The second page load always works for me.
