### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by rktfier** [uBlockOrigin/uAssets#17616]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/`

### Category

detection

### Description

The site detects the adblocker after waiting the 5 second download timer.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/75695425/232259646-564a56aa-f3e2-47ae-ac7d-dac0852b7af7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 88825
  cosmetic: 39813
  scriptlet: 17688
  html: 948
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34604-62, 2h.58m
    ublock-badware: 6614-2, 2h.57m
    ublock-privacy: 352-0, 6d.26m
    ublock-abuse: 78-0, 6d.25m
    ublock-unbreak: 1997-5, 2h.56m
    ublock-quick-fixes: 178-0, 7h
    easylist: 64539-616, 1d.10h.31m
    easyprivacy: 30780-1769, 4d.1h.13m
    urlhaus-1: 7012-1, 6h.59m
    plowe-0: 3750-1, 4d.11h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1772 ms (selfie)
  maxAssetCacheWait: 314 ms
popupPanel: 
  blocked: 66
  no-scripting: true
  blockedDetails: 
    megaup.net: 57
    a-ads.com: 1
    altowriestwispy.com: 2
    dmmzkfd82wayn.cloudfront.net: 2
    googletagmanager.com: 2
    keydawnawe.com: 2
```
</details>

**Comment by rktfier** [comment]
Just to clarify, i did these steps one by one while the issue window was open, in case the update times don't look new even though "I forced an update of my filter lists." and others are ticked.

**Comment by gorhill** [comment]
> after waiting the 5 second download timer

I don't see a download timer, I see a _"The easiest way to share"_ with an _upload_ button for the URL you provided.

**Comment by gorhill** [comment]
Also, it doesn't look you checked for duplicate: <https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+megaup.net+is%3Aclosed>, and by your own admission:

> - [x] I did not answer truthfully to ALL the above checkpoints.

We ask people to go through these steps to not burden volunteers here.

**Comment by gorhill** [comment]
I can reproduce when using a URL from another megaup issue:

    https://megaup.net/r3jS/Far.Cry.5.Dead.Living.Zombies.part04.rar

**Comment by rktfier** [comment]
> Also, it doesn't look you checked for duplicate: https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+megaup.net+is%3Aclosed, and by your own admission:
> 
> > * [x]  I did not answer truthfully to ALL the above checkpoints.
> 
> We ask people to go through these steps to not burden volunteers here.

I have checked for duplicates using the button located in the report screen, there was no open issues. So it's either another issue got created before i finished filling the form, or the filter provided by the "view duplicates" option was wrong. Either way I'll try to be more considerate in the future, thanks for the heads up.

**Comment by stephenhawk8054** [comment]
You can continue comment on closed issues. All the volunteers will have notifications with new comments on github.

**Comment by rktfier** [comment]
So instead of making a new issue every time a site breaks, i have to comment on the existing site issue?

**Comment by mapx-** [comment]
Exactly.

**Comment by Jorge9811** [comment]
> You can continue comment on closed issues. All the volunteers will have notifications with new comments on github.

this issue is closed so here i go

it's happening again

i already updated my filters and ctrl f5'd but after the timer is done you get the disable adblock warning
