### ISSUE TITLE
atv.com.tr: detection

### ISSUE THREAD

**Issue by pop-dahaka** [uBlockOrigin/uAssets#17613]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.atv.com.tr/canli-yayin`

### Category

detection

### Description

attached screenshot 

![atv](https://user-images.githubusercontent.com/17509547/232241981-3f1cb737-ea28-4981-a6af-2af68b352d25.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![atv](https://user-images.githubusercontent.com/17509547/232241981-3f1cb737-ea28-4981-a6af-2af68b352d25.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89232
  cosmetic: 39842
  scriptlet: 17702
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64681-44, 9h.6m
    easyprivacy: 30855-1176, 9h.5m
    plowe-0: 3750-938, 4d.14h.13m
    ublock-abuse: 78-0, 4d.14h.11m
    ublock-badware: 6610-118, 9h.4m
    ublock-filters: 33725-97, 9h.3m
    ublock-privacy: 294-2, 4d.14h.7m
    ublock-quick-fixes: 179-26, 9h.1m
    ublock-unbreak: 1986-45, 9h.2m
    urlhaus-1: 7236-1, 9h
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 498 ms (selfie)
  maxAssetCacheWait: 273 ms
popupPanel: 
  blocked: 20
  blockedDetails: 
    doubleclick.net: 2
    gemius.pl: 1
    google-analytics.com: 1
    google.com: 7
    googletagmanager.com: 1
    h-cdn.com: 1
    tmgrup.com.tr: 2
    translate.googleapis.com: 4
    unblockia.com: 1
```
</details>

**Comment by gorhill** [comment]
Enable the _TUR: AdGuard Turkish"_ list.

**Comment by pop-dahaka** [comment]
Thank you its work now 💯 👍
