### ISSUE TITLE
daily-tohoku.news: nuisance

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#17624]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.daily-tohoku.news/archives/160926`

### Category

nuisance

### Description

This site seems to disallow right-click and text selection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 121352
  cosmetic: 121754
  scriptlet: 23632
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38615-3361, 1m
    adguard-spyware-url: 977-3, 1m
    block-lan: 47-0, 1m
    fanboy-annoyance: 79299-378, 1m
    ublock-annoyances: 4936-72, 1m
  default: 
    user-filters: 52-0, never
    JPN-1: 10715-29, 1m
    easylist: 64873-94, 1m
    easyprivacy: 30858-11934, 1m
    plowe-0: 3749-1014, 1m
    ublock-abuse: 70-0, 1m
    ublock-badware: 6694-118, now
    ublock-filters: 33819-161, now
    ublock-privacy: 295-64, now
    ublock-quick-fixes: 180-26, now
    ublock-unbreak: 1987-90, now
    urlhaus-1: 7092-1, now
filterset (user): [array of 55 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 261 ms (selfie)
  maxAssetCacheWait: 171 ms
popupPanel: 
  blocked: 35
  blockedDetails: 
    daily-tohoku.news: 2
    addtoany.com: 1
    adingo.jp: 1
    doubleclick.net: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    id5-sync.com: 1
    jsdelivr.net: 1
    m0mentum.net: 2
    popin.cc: 23
    treasuredata.com: 1
```
</details>

**Comment by u-RraaLL** [comment]
daily-tohoku.news##+js(acis, document.oncontextmenu)

Should fix context menu blocking, but I'm not sure about selection blocking (which you didn't ask about).

**Comment by stm-x** [comment]
> Should fix context menu blocking, but I'm not sure about selection blocking (which you didn't ask about).

Oops, it's true.
I'll update the description now.
Thanks for pointing that out.

> daily-tohoku.news##+js(acis, document.oncontextmenu)

Also, this rule seems to work. Thanks.
