### ISSUE TITLE
sofascore.com: ads

### ISSUE THREAD

**Issue by derbederMRP** [uBlockOrigin/uAssets#17621]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sofascore.com/tr/`

### Category

ads

### Description

There are blank areas which are for ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![www sofascore com](https://user-images.githubusercontent.com/23294947/232300216-fe80956e-1423-4e31-89df-a33fb73166a3.jpeg)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.8
Chromium: 114
filterset (summary): 
  network: 90823
  cosmetic: 48999
  scriptlet: 18962
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 5-0, never
    TUR-0: 12249-11, 12h.54m
    easylist: 64539-63, 1d.1h.1m
    easyprivacy: 30818-1182, 1d.1h.2m
    plowe-0: 3753-938, 10d.27m
    ublock-abuse: 70-0, 1d.14h.37m
    ublock-badware: 6604-117, 1d.1h.5m
    ublock-filters: 33724-103, 1d.1h.4m
    ublock-privacy: 294-2, 1d.1h.6m
    ublock-quick-fixes: 361-224, 1d.59m
    ublock-unbreak: 1986-42, 1d.1h.3m
    urlhaus-1: 7236-1, 1d.1h
filterset (user): [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1256 ms
  maxAssetCacheWait: 521 ms
popupPanel: 
  blocked: 8
  blockedDetails: 
    adjust.com: 1
    ads-twitter.com: 1
    doubleclick.net: 1
    facebook.com: 1
    googletagmanager.com: 2
    pubmatic.com: 1
    sc-static.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
sofascore.com##[display^="none,none"]
```

@ryanbr

**Comment by mators** [comment]
> ```
> sofascore.com##[display^="none,none"]
> ```
> 
> @ryanbr

Hello, I noticed some stuff disappearing from the sofascore website when using ad blockers and came across this issue googling. This selector in easyList resulted in some of the non-ad content missing from the site since `display` attribute is present all over the site, not just in the ad parent container. Example:

Without blocker:
![image](https://github.com/uBlockOrigin/uAssets/assets/9774577/28d242d3-13b6-4a8c-a1b6-b184f7aa30fd)

With blocker:
![image](https://github.com/uBlockOrigin/uAssets/assets/9774577/e64ae9a1-0f96-46cc-8414-59e95da572d8)

Logo is missing, bottom navigation is missing, All/Live control and Odds control is missing, some stuff in the footer is also missing etc..

I didn't go through the whole site, there must be some desktop stuff missing too, but this selector doesn't look good.

**Comment by mapx-** [comment]
@mators only mobile ?

**Comment by mators** [comment]
Well I noticed it on mobile because I use it there. I can check desktop a bit now

**Comment by mators** [comment]
@mapx- desktop looks fine as far as I can tell

P.S. noticed the `adUnitBox` class, that could solve the whole thing
