### ISSUE TITLE
etsy.com: ads

### ISSUE THREAD

**Issue by EnokiKit** [uBlockOrigin/uAssets#17628]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.etsy.com/c/jewelry-and-accessories`

### Category

ads

### Description

Sponsored listings are still appearing in search results

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/130936455/232344602-ab866649-a699-4b4f-8784-66d37122d542.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 88936
  cosmetic: 39829
  scriptlet: 17687
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    easylist: 64627-44, 2d.2h.58m
    easyprivacy: 30801-1176, 2d.2h.59m
    plowe-0: 3749-938, 2h.26m
    ublock-abuse: 70-0, 1d.22h.57m
    ublock-badware: 6610-118, 1d.18h.52m
    ublock-filters: 33721-111, 1d.18h.51m
    ublock-privacy: 294-2, 1d.22h.56m
    ublock-quick-fixes: 179-26, 19h.47m
    ublock-unbreak: 1986-46, 1d.18h.53m
    urlhaus-1: 7046-1, 19h.46m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 458 ms (selfie)
  maxAssetCacheWait: 208 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    etsy.com: 7
    googletagmanager.com: 1
    granify.com: 1
    sentry-cdn.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists and test again?

**Comment by krystian3w** [comment]
AdGuard also rejected cut self-promo: https://github.com/AdguardTeam/AdguardFilters/issues/148111#issuecomment-1513134079

https://github.com/AdguardTeam/AdguardFilters/issues/148181

**Comment by gwarser** [comment]
They reinject? Even plain results? User asked to hide some results in search simple filter does not get rid of them

`https://www.etsy.com/pl/search?q=roll`

`www.etsy.com##li:has-text(/\b(?:pencil|hat)\b/i)`

https://www.reddit.com/r/uBlockOrigin/comments/13bdbke/can_i_block_etsy_search_results_with_in_the/

**Comment by stephenhawk8054** [comment]
Maybe need to add `:remove()`?

**Comment by gwarser** [comment]
For me, it works in picker, but does not when added to My filters.

**Comment by krystian3w** [comment]
I would cut out the paid results with such a regional filter:

```adb
##li span:matches-css(display: /inline/) + span[aria-label^="Ze sklepu"]:upward(li):remove()
##li span:matches-css(display: /inline/) + span[aria-label^="From store"]:upward(li):remove()

```

But it does not cut randomly found brushes and hats.

I suspect that at the html code level, brushes and hats are no different from rolls to be able to skip `:has-text`. That is, it is rather already necessary to analyze whether the results are loaded in json and whether it is possible to reject tref there.
