### ISSUE TITLE
Quora.com

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#1762]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.quora.com/What-dirty-business-tactics-do-you-know`

### Describe the issue

Ads bypassed

### Versions

- Browser/version: chrome stable
- uBlock Origin version: latest

### Settings

befault

**Comment by mapx-** [comment]
Did you update ublock filters ?
see https://github.com/uBlockOrigin/uAssets/issues/289#issuecomment-375173083

However when ask for help here provide more info, eventually what type of ads, upload a screenshot.
