### ISSUE TITLE
forum.release-apk.com: detection

### ISSUE THREAD

**Issue by MondayNitro** [uBlockOrigin/uAssets#17626]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

forum.release-apk.com (Balatan Mods) catches ublock origin and compels me to disable the extension. when i use adguard extension instead, the website works fine.

### URL(s) where the issue occurs.

forum.release-apk.com
(main webpage will open fine, the pinned 1dm+ link will open fine, but try opening the links below, they will show ad blocked message)

### Screenshot(s)

![Web capture_16-4-2023_23949_forum release-apk com](https://user-images.githubusercontent.com/87489540/232331248-d3e099d8-b8cd-4b52-b0f9-bbaafb7c1716.jpeg)

### uBO version

1.48.4

### Browser name and version

Microsoft Edge 112.0.1722.48

### Settings

none

### Notes

none

**Comment by gorhill** [comment]
> Settings
> 
> none

Provide troubleshooting information for the site: Visit site => popup panel => chat icon => click _troubleshooting information_ => select all/paste here

**Comment by MondayNitro** [comment]
are you talking about adblock warning popup panel? because unlike other sites, here there is no popup panel, instead the "disable adblock" message is embedded in the site itself. you can open this to check
https://forum.release-apk.com/viewtopic.php?f=6&t=147074&p=175853#p175853

**Comment by MondayNitro** [comment]
im sorry i started using ublock just 3 days ago, so i dont know much about its configuration

**Comment by okiehsch** [comment]
I can reproduce the message with uBO disabled, is that the case on your end too?

**Comment by MondayNitro** [comment]
> I can reproduce the message with uBO disabled, is that the case on your end too?

yes. i checked, it shows the same even if i disable ublock, but if i enable adguard, it gets rid of the message and displays the cintent

**Comment by okiehsch** [comment]
If I add 
```@@||googleads.g.doubleclick.net/pagead/html/*/zrt_lookup.html$domain=forum.release-apk.com
@@||googleads.g.doubleclick.net/pagead/ads$domain=forum.release-apk.com
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=forum.release-apk.com
@@||pagead2.googlesyndication.com/pagead/*/show_ads_impl*_fy*.js$domain=forum.release-apk.com
@@||pagead2.googlesyndication.com/getconfig/sodar$domain=forum.release-apk.com
````
the content shows up after a few seconds on my end. 
This seems to be a site issue in my opinion, I highly doubt that they intend the site to work that way. 😉 

The site loads slowly and uses an enourmous amount of random-access memory on my end as well.

**Comment by mapx-** [comment]
Tested in uBO, the page by default is displaying the anti-adb message, after completely loading the real content will replace the first one

**Comment by mapx-** [comment]
AG is using a javascript filter:

`forum.release-apk.com#%#AG_onLoad(function(){var b=new MutationObserver(function(){try{for(var a,d=function(c){for(var a="",d=0;d<c;d++)a+="0123456789".charAt(Math.floor(10*Math.random()));return a},e=document.querySelectorAll(".adsbygoogle, script[data-ad-client]"),f=0;f<e.length;f++)if(e[f].getAttribute("data-ad-client")){a=e[f].getAttribute("data-ad-client");break}if(a){var g=`<ins class="adsbygoogle" data-adsbygoogle-status="done" style="display: block; height: 200px; width: 200px;" data-ad-status="unfilled"><ins id="aswift_0_expand" style="border: none; height: 0px; width: 0px; margin: 0px; padding: 0px; position: relative; visibility: visible; background-color: transparent; display: inline-table;" tabindex="0" title="Advertisement" aria-label="Advertisement"><ins id="aswift_0_anchor" style="border: none; height: 0px; width: 0px; margin: 0px; padding: 0px; position: relative; visibility: visible; background-color: transparent; display: block;"><iframe id="aswift_0" name="aswift_0" style="left:0;position:absolute;top:0;border:0;width:200px;height:200px;" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" frameborder="0" src="https://googleads.g.doubleclick.net/pagead/ads?client=${a}&amp;output=html&amp;adk=${d(10)}&amp;adf=${d(10)}&amp;lmt=${d(10)}&amp;plat=${d(100)};&amp;format=0x0&amp;url=${encodeURIComponent(document.location.href)}&amp;ea=0&amp;flash=0&amp;pra=5&amp;wgl=1&amp;uach=${d(100)}&amp;bpp=2&amp;bdt=${d(3)}&amp;idt=${d(3)}&amp;shv=r${d(8)}&amp;mjsv=m${d(8)}&amp;ptt=${d(1)}&amp;saldr=aa&amp;abxe=1&amp;nras=1&amp;correlator=${d(8)}&amp;frm=${d(2)}&amp;pv=2&amp;ga_vid=${d(10)}.${d(10)}&amp;ga_sid=${d(10)}&amp;ga_hid=${d(10)}&amp;ga_fc=0&amp;u_tz=${d(3)}&amp;u_his=8&amp;u_java=0&amp;u_h=${d(4)}&amp;u_w=${d(4)}&amp;u_ah=${d(4)}&amp;u_aw=${d(4)}&amp;u_cd=${d(2)}&amp;u_nplug=${d(1)}&amp;u_nmime=${d(1)}&amp;adx=-${d(8)}&amp;ady=-${d(8)}&amp;biw=${d(4)}&amp;bih=${d(4)}&amp;scr_x=0&amp;scr_y=0&amp;eid=${d(30)}&amp;oid=${d(1)}&amp;pvsid=${d(16)}&amp;pem=${d(3)}&amp;eae=${d(1)}&amp;fc=${d(4)}&amp;brdim=${d(20)}&amp;vis=1&amp;rsz=${d(6)}&amp;abl=NS&amp;fu=${d(4)}&amp;bc=${d(2)}&amp;ifi=1&amp;uci=a!1&amp;fsb=1&amp;dtd=128" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" data-google-container-id="a!1" data-load-complete="true"></iframe></ins></ins></ins>`,h=document.querySelector("body > *"),j=document.querySelectorAll(".phpbb-ads-center > .adsbygoogle");h&&j.length&&(!h.querySelector("iframe#aswift_0")&&h.insertAdjacentHTML("afterend",g),j.forEach(a=>{a.querySelector("iframe#aswift_0")||(a.parentNode.style.height="200px",a.parentNode.style.width="200px",a.parentNode.innerHTML=g)}))}var k=document.querySelector(".page-body"),l=document.querySelectorAll(".adsbygoogle, .phpbb-ads-center");k&&!k.innerText.includes("deactivating your Ad-Blocker")&&l.length&&(l.forEach(a=>{a.remove()}),b.disconnect())}catch(a){}});b.observe(document,{childList:!0,subtree:!0}),setTimeout(function(){b.disconnect()},1E4)});`

**Comment by okiehsch** [comment]
Hm, I think your right.
I think the exceptions I posted "work" on my end because the site stops loading much earlier on my end.

**Comment by MondayNitro** [comment]
> If I add
> 
> ```
> @@||googleads.g.doubleclick.net/pagead/ads$domain=forum.release-apk.com
> @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=forum.release-apk.com
> @@||pagead2.googlesyndication.com/pagead/*/show_ads_impl*_fy*.js$domain=forum.release-apk.com
> @@||pagead2.googlesyndication.com/getconfig/sodar$domain=forum.release-apk.com
> ```
> 
> the content shows up after a few seconds on my end. This seems to be a site issue in my opinion, I highly doubt that they intend the site to work that way. 😉
> 
> The site loads slowly and uses an enormous amount of random-access memory on my end as well.

where do i add this sir? i only started using ublock 3 days ago, was using adguard before it.

**Comment by okiehsch** [comment]
In https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters

But like I mentioned in my earlier post, ths content shows up after the site finishes loading on my end, the filters only accelerate it.
It should eventuallya show up even without it, it does on my end.

**Comment by MondayNitro** [comment]
> In https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters
> 
> But like I mentioned in my earlier post, ths content shows up after the site finishes loading on my end, the filters only accelerate it. It should eventuallya show up even without it, it does on my end.

its the same in adguard, the message is initially displayed. but goes away when the site has been loaded

**Comment by MondayNitro** [comment]
> If I add
> 
> ```
> @@||googleads.g.doubleclick.net/pagead/ads$domain=forum.release-apk.com
> @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=forum.release-apk.com
> @@||pagead2.googlesyndication.com/pagead/*/show_ads_impl*_fy*.js$domain=forum.release-apk.com
> @@||pagead2.googlesyndication.com/getconfig/sodar$domain=forum.release-apk.com
> ```
> 
> the content shows up after a few seconds on my end. This seems to be a site issue in my opinion, I highly doubt that they intend the site to work that way. 😉
> 
> The site loads slowly and uses an enormous amount of random-access memory on my end as well.

no luck here, still the same message displayed :(

**Comment by gorhill** [comment]
> no luck here, still the same message displayed :(

That message is always there, until the page finishes loads. It's the same with AdGuard.

**Comment by gorhill** [comment]
I see some CHP code in the source file of the page, I can't tell if this help to load faster:

    forum.release-apk.com##+js(noeval-if, chp_ad)

**Comment by gorhill** [comment]
The number of seconds to complete page load is randomly set by the server. The page will execute a tight loop until the server-set time has elapsed, at which point it will run detection code and I guess load the page once the detection code pass. I don't see how we can avoid the server-set delay and that tight loop (which is why the cpu fans kick in).

**Comment by mapx-** [comment]
@MondayNitro 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
