### ISSUE TITLE
lebigdata.fr: ads

### ISSUE THREAD

**Issue by SwitchToForgejoPlease** [uBlockOrigin/uAssets#17637]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lebigdata.fr/gafam-tout-savoir`

### Category

ads

### Description

The page displays ads in 2 places, one for pCloud, the other for NordVPN. Common point:
class="adv-link"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 202275
  cosmetic: 0
  scriptlet: 18361
  html: 948
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 38618-3652, 5h.51m
    adguard-spyware-url: 977-6, 1d.22h.36m
    curben-phishing: 70042-32, 10h.35m
  default: 
    user-filters: 1-0, never
    ublock-filters: 34623-9302, 3d.8h.51m
    ublock-badware: 6593-670, 3d.8h.50m
    ublock-privacy: 352-69, 12d.21h.43m
    ublock-abuse: 78-1, 12d.21h.42m
    ublock-unbreak: 1997-321, 2d.6h.43m
    easylist: 64539-29859, 3d.21h.45m
    easyprivacy: 30818-11931, 3d.8h.52m
    plowe-0: 3750-1008, 8d.10h.17m
    FRA-0: 28677-9322, 1d.22h.37m
    urlhaus-1: 6809-1, 10h.34m
    ublock-quick-fixes: 185-73, 10h.33m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 16 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  collapseBlocked: false
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2683 ms (selfie)
  maxAssetCacheWait: 387 ms
popupPanel: 
  blocked: 34
  no-cosmetic-filtering: true
  blockedDetails: 
    lebigdata.fr: 14
    cookieless-data.com: 2
    googletagmanager.com: 5
    kaspersky-labs.com: 2
    opti-digital.com: 2
    ownpage.fr: 2
    pushmaster-cdn.xyz: 1
    sddan.com: 1
    sirdata.io: 4
    wpserveur.net: 1
```
</details>

**Comment by mapx-** [comment]
> no-cosmetic-filtering: true

Why did you turn OFF that setting ? turn it ON and don't touch other settings

**Comment by SwitchToForgejoPlease** [comment]
Sorry, I forgot about this setting, I thought it was used to hide empty spaces left by the removal of ads (and I prefer to see that an element has been removed).

Thank you.

**Comment by mapx-** [comment]
You have also
  `parseAllABPHideFilters: false`

reset uBO to default settings, update ALL lists and do not change other settings

**Comment by SwitchToForgejoPlease** [comment]
OK, the default settings have been reset and all lists updated.

"Disable cosmetic filtering" is now unchecked, which hides the ads, but also the empty spaces where they should be displayed (even with the box "Cacher les espaces réservés aux éléments bloqués" unchecked).

How can I get uBO to show me where elements have been blocked on the web pages I visit? (either by leaving a blank space, or grayed out, or with the logo)

**Comment by mapx-** [comment]
@gorhill

**Comment by gorhill** [comment]
These two ads are hidden fine with the following cosmetic filters from _FRA: AdGuard Français_:

    ##a[href^="https://partner.pcloud.com/r/"] > img
    ##a[href*="/aff_c?offer_id="] > img

Unable to reproduce any issue.
