### ISSUE TITLE
hacoos.com: detection

### ISSUE THREAD

**Issue by uuqqzz** [uBlockOrigin/uAssets#17638]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hacoos.com/`

### Category

detection

### Description

adblock detected

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/232543862-ba0ce099-b6a8-4d85-bcbc-dd10fd21e9fe.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 131411
  cosmetic: 160444
  scriptlet: 36069
  html: 947
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 43742-16077, 1m
    adguard-generic: 70143-6227, 1m
    adguard-spyware-url: 984-5, 1m
    adguard-annoyance: 67324-1576, 1m
    adguard-social: 20281-31, 1m
  default: 
    user-filters: 63-0, never
    ublock-filters: 34726-160, 1m
    ublock-badware: 6732-0, 1m
    ublock-privacy: 361-0, 1m
    ublock-abuse: 70-0, 1m
    ublock-unbreak: 1998-5, 1m
    ublock-quick-fixes: 175-0, 1m
    easylist: 64946-255, 1m
    easyprivacy: 30862-1192, 1m
    TUR-0: 12265-11, 1m
filterset (user): [array of 65 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 681 ms (selfie)
  maxAssetCacheWait: 448 ms
  unsuspendAfter: 184 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by tunceray1** [comment]
Anti-adblock rules work with Firefox but not Chrome. Please check back when you have time.

<details>
 <summary>image</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/140217932/d5c55e00-e10b-42ed-847d-ade38acf3fab)

</details>

<details>
 <summary>Settings</summary>

```
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 97733
 cosmetic: 127170
 scriptlet: 26040
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  adguard-cookies: 26473-29, now
  adguard-other-annoyances: 13177-6, now
  adguard-popup-overlays: 23201-52, now
  adguard-social: 21011-896, now
  adguard-spyware-url: 1151-3, now
  adguard-widgets: 2223-3, now
  ublock-annoyances: 5302-172, now
 default:
  user-filters: 47-0, never
  TUR-0: 13597-11, now
  easylist: 69070-86, now
  easyprivacy: 33365-132, now
  ublock-badware: 7621-141, now
  ublock-filters: 34127-521, now
  ublock-privacy: 445-6, now
  ublock-quick-fixes: 307-104, now
  ublock-unbreak: 2106-38, now
filterset (user): [array of 55 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10273 ms (selfie)
 maxAssetCacheWait: 1303 ms
popupPanel:
 blocked: 8
 network:
  googletagmanager.com: 4
  jsdelivr.net: 4
 extended:
  ##+js(abort-current-script, document.createElement, adblock)
  ##+js(abort-on-property-read, detectAdBlock)

```


</details>
