### ISSUE TITLE
osseo.schoo

### ISSUE THREAD

**Issue by onlyfans1** [uBlockOrigin/uAssets#17635]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://osseo.schoology.com/`

### Category

breakage

### Description

for fun

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 89067
  cosmetic: 39837
  scriptlet: 17726
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-1, never
    easylist: 64539-44, 3d.8h.11m
    easyprivacy: 30818-1177, 20h.23m
    plowe-0: 3753-937, 11d.12h.46m
    ublock-abuse: 70-0, 20h.25m
    ublock-badware: 6694-117, 20h.22m
    ublock-filters: 33818-96, 20h.21m
    ublock-privacy: 295-2, 20h.24m
    ublock-quick-fixes: 180-26, 20h.18m
    ublock-unbreak: 1987-45, 20h.20m
    urlhaus-1: 7092-1, 20h.19m
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7123 ms (selfie)
  maxAssetCacheWait: 1205 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    newrelic.com: 1
```
</details>

**Comment by peace2000** [comment]
Hi, what exactly is broken?

**Comment by onlyfans1** [comment]
idk figure it out

**Comment by mapx-** [comment]
It's a school site, maybe OP want to play on some other site ...
