### ISSUE TITLE
discord.com: privacy

### ISSUE THREAD

**Issue by ViaBackwards** [uBlockOrigin/uAssets#17630]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The "discord.com/api/*/science" tracker used to be blocked by ublock origin, recently I noticed it is not blocked anymore. I don't see how it could be causing any breakages, since its literally just for tracking.

### URL(s) where the issue occurs.

discord.com/api/*/science

### uBO version

uBlock Origin 1.48.4

### Browser name and version

Brave 1.50.119 

### Settings

- Make use of context menu where appropriate
- Suspend network activity until all filter lists are loaded

**Comment by gorhill** [comment]
https://github.com/easylist/easylist/commit/c01994f5e9ffb205acf08825984c1e1e17aecfcf

**Comment by ryanbr** [comment]
Not the first time it was added/removed, everytime there is a "you broke discord" people blame this filter for reasons.

**Comment by ryanbr** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4727

**Comment by stephenhawk8054** [comment]
Each `science` connection has different requests: https://user-images.githubusercontent.com/66517106/232377388-d1f17a6e-9b09-443f-b85e-53962d9e178f.png

Some run in background, but some will affect visually that users can notice and complain.

**Comment by D4niloMR** [comment]
This can probably be fixed by `discord.com##+js(trusted-replace-outbound-text, JSON.stringify)`
