### ISSUE TITLE
regex101.com: detection

### ISSUE THREAD

**Issue by Banaanae** [uBlockOrigin/uAssets#17632]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://regex101.com/`

### Category

detection

### Description

Detection in bottom left
Fixable via `regex101.com##.XNbml.jyUE5`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/83927639/232410133-8bc83886-82d3-431a-93d5-2119b637999e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 105641
  cosmetic: 40187
  scriptlet: 18278
  html: 949
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/stephenhawk8054/PrivacyExtended/main/privacy_extended.txt: 17341-12, now
  default: 
    user-filters: 14-0, never
    ublock-filters: 34706-138, now
    ublock-badware: 6716-1, now
    ublock-privacy: 361-0, now
    ublock-abuse: 70-0, now
    ublock-unbreak: 2000-6, now
    ublock-quick-fixes: 185-0, now
    easylist: 64939-553, now
    easyprivacy: 30858-1807, now
    urlhaus-1: 6809-1, now
    plowe-0: 3749-2, now
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    moz-extension-scheme
modifiedUserSettings: 
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 8682 ms (selfie)
  maxAssetCacheWait: 5376 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    regex101.com: 2
    buysellads.com: 1
    sentry.io: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Enable `uBlock filters – Annoyances `
