### ISSUE TITLE
wotinspector.com: detection

### ISSUE THREAD

**Issue by Dragon31337** [uBlockOrigin/uAssets#17639]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wotinspector.com/en/battleassistant?user=AeulpdbcEOP1Tpo4wj3U_Kl5IXwBD6Zy7Ptp6R5mJXH0bHJffSMM1GCazsj7dm9oB4D3FGpbmMTOR4oU51JnRzKz-jzhDMOhR3_C6ZbEdgbTOoAXGRqj60-PRWPCGO_L7XNqUmthb2xCSnlFZmNqY1ZQ`

### Category

detection

### Description

This website detects blocked ads and limit functionality. Here is the message: The free activation period of Battle Assistant is limited to only 3 days when Ad Block is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-04-17 at 10-38-04 WOTInspector mods - Battle Assistant for World of Tanks  Official website](https://user-images.githubusercontent.com/7872570/232566613-23efcd7b-b4a1-43e0-ac0a-9342246ed3d6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 88712
  cosmetic: 39815
  scriptlet: 17717
  html: 949
listset (total-discarded, last-updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 34m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34656-62, 1d.22h.53m
    ublock-badware: 6608-0, 1d.22h.52m
    ublock-privacy: 344-0, 7d.12h.47m
    ublock-abuse: 78-0, 7d.12h.46m
    ublock-unbreak: 1997-5, 1d.22h.51m
    easylist: 64571-605, 1d.22h.54m
    easyprivacy: 30814-1770, 3d.32m
    urlhaus-1: 6809-1, 13h.35m
    plowe-0: 3750-3, 6d.2h.12m
    ublock-quick-fixes: 185-0, 13h.36m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 709 ms (selfie)
  maxAssetCacheWait: 336 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    wotinspector.com: 2
    googlesyndication.com: 1
    googletagmanager.com: 2
```
</details>

**Comment by peace2000** [comment]
@Dragon31337 Can you try that filter whether it works correctly for you? It gets rid of that nag but I'm not sure whether that activation thing works as it should.

**Comment by Dragon31337** [comment]
I've tried the fix above, and now the button "Activate" for free for 10 days is just not active.

**Comment by mapx-** [comment]
I added a commit, remove the filter above, update uBO filters list and test again

**Comment by Dragon31337** [comment]
That is exactly what I did, I was not checking filer from here (https://github.com/uBlockOrigin/uAssets/issues/17639#issuecomment-1511859233). I was checking a fix: https://github.com/uBlockOrigin/uAssets/commit/cb204f50d9e3fe37a44c8a9f21ab5d0dc4d069ca
I do not see a popup anymore, but the button Activate is just disabled
![image](https://user-images.githubusercontent.com/7872570/232597524-462c33b7-f1dc-4064-868e-e5aebdd96a92.png)

**Comment by mapx-** [comment]
It seems to be the normal behaviour of the page => disable uBO for the page and you'll see "activate" still disabled

**Comment by Dragon31337** [comment]
AH, probably it was prolonged by 10 days already during someone's testing. I will report back if it will not work later.
