### ISSUE TITLE
cpc2r.ch: nuisance

### ISSUE THREAD

**Issue by Desmo46** [uBlockOrigin/uAssets#17643]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cpc2r.ch/`

### Category

nuisance

### Description

Overlay appears no way to remove without diabling uBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 113
filterset (summary): 
  network: 94698
  cosmetic: 111612
  scriptlet: 19712
  html: 0
listset (total-discarded, last-updated): 
  added: 
    fanboy-annoyance: 80205-367, 3d.22h.54m
  default: 
    user-filters: 0-0, never
    easylist: 64394-47, 2d.19h.21m
    easyprivacy: 30814-1177, 2d.19h.20m
    plowe-0: 3749-937, 3d.22h.57m
    ublock-abuse: 78-0, 3d.22h.56m
    ublock-badware: 6610-117, 2d.19h.19m
    ublock-filters: 33725-117, 2d.19h.18m
    ublock-privacy: 294-4, 3d.22h.55m
    ublock-quick-fixes: 176-20, 2h.57m
    ublock-unbreak: 1986-48, 2d.17h.56m
    urlhaus-1: 6998-1, 2h.56m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 203 ms (selfie)
  maxAssetCacheWait: 78 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    autoscout24.ch: 1
    googletagmanager.com: 2
```
</details>

**Comment by pancakeexpert** [comment]
related to Fanboy's Annoyances list

@ryanbr

**Comment by gorhill** [comment]
Fanboy Annoyances hides a cookie warning form bottom-right, which needs to be clicked to make the "overlay" go away. This remove the overlay-like visual:

    cpc2r.ch##.cookies-show:style(transform:unset!important;opacity:unset!important)
