### ISSUE TITLE
puromarketing.com: detection

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#17645]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

anti adblocker

whitelisting this filter can bypass anti adblocker.
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=www.puromarketing.com`

But this filter `##.adxs-vertisements`  breaks the site ( no text in articles ) and that filter is hidden the ads. 

### URL(s) where the issue occurs.

Example URL:

`https://www.puromarketing.com/44/211559/francisco-jose-gonzalez-influencers-inutiles-para-construir-cualquier-marca-suya`

### uBO version

1.48.8

### Browser name and version

Opera

### Settings

Default + ESP lists & uBlock filters Annoyances

**Comment by stephenhawk8054** [comment]
```adb
puromarketing.com##+js(no-fetch-if, googlesyndication)
```

@Yuki2718 for Adguard Spanish?

**Comment by Yuki2718** [comment]
`negociosecommerce.com,todostartups.com,puromarketing.com##+js(no-fetch-if, /call-zone-adxs/)` is this required? Not blocked on my end.
