### ISSUE TITLE
tbdailynews.com: detection

### ISSUE THREAD

**Issue by HenryKrinkle3** [uBlockOrigin/uAssets#17642]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tbdailynews.com/`

### Category

detection

### Description

The domain detects uBlockOrigin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot (7)](https://user-images.githubusercontent.com/131054822/232612935-d7d2f033-dc04-44bd-b959-28992623c5d8.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89386
  cosmetic: 39926
  scriptlet: 17748
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64946-44, 12m
    easyprivacy: 30862-1176, 12m
    plowe-0: 3749-940, 12m
    ublock-abuse: 70-0, 12m
    ublock-badware: 6728-117, 12m
    ublock-filters: 33847-101, 12m
    ublock-privacy: 314-3, 12m
    ublock-quick-fixes: 176-20, 12m
    ublock-unbreak: 1987-45, 12m
    urlhaus-1: 6998-1, 12m
filterset (user): [empty]
trustedset: 
  added: [array of 19 redacted]
  removed: 
    chrome-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 434 ms (selfie)
  maxAssetCacheWait: 313 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    tbdailynews.com: 1
    2mdn.net: 1
    google-analytics.com: 1
    google.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    monu.delivery: 1
    rumble.com: 3
    stripe.com: 22
    twitter.com: 1
    wp.com: 2
    youtube.com: 1
```
</details>

**Comment by pancakeexpert** [comment]
```
@@||tbdailynews.com^$ghide
tbdailynews.com##[id^="custom_html"]:has-text(.slots)
```
there probably could be a scriptlet from what I remember

I didn't find any cosmetic filtering in the logger though.. @okiehsch @mapx- is this supposed to happen?

**Comment by HenryKrinkle3** [comment]
This is my first submission and my knowledge of how uBlock works is deep as a puddle but just wanted to thank you all or what you do. Did not expect to see any kind of response (fix or not) this fast.

**Comment by HenryKrinkle3** [comment]
You guys are amazing. I am in awe. Thank you!
