### ISSUE TITLE
feedly.com: breakage

### ISSUE THREAD

**Issue by RashadAhmed1** [uBlockOrigin/uAssets#17644]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://feedly.com/i/saved`

### Category

breakage

### Description

When uBO is enabled, the top toolbar on the article view is hidden. Normally, when clicking an article a popup opens with a toolbar at the top that contains article action buttons. When uBO is enabled, this toolbar is not visible.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBO enabled:
![image](https://user-images.githubusercontent.com/22065365/232636058-aca3c5cc-f235-4896-82f2-a5a6a6940a15.png)

Without uBO enabled:
![image](https://user-images.githubusercontent.com/22065365/232636123-d47bc838-9b99-481a-8448-9d185a1e6ef1.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 163378
  cosmetic: 112267
  scriptlet: 22786
  html: 1113
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    curben-phishing: 70614-31, 1m
    curben-pup: 194-0, 1m
    fanboy-annoyance: 79010-66465, 1m
    fanboy-cookiemonster: 46736-240, 1m
    fanboy-social: 19535-2, 1m
    ublock-annoyances: 4909-4, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34728-59, 1m
    ublock-badware: 6732-0, 1m
    ublock-privacy: 364-0, 1m
    ublock-abuse: 70-0, 1m
    ublock-unbreak: 1998-4, 1m
    ublock-quick-fixes: 175-0, 1m
    easylist: 64983-288, 1m
    easyprivacy: 30863-1182, 1m
    urlhaus-1: 6998-1, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1244 ms (selfie)
  maxAssetCacheWait: 956 ms
popupPanel: 
  blocked: 23
  blockedDetails: 
    buysellads.com: 1
    google-analytics.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 2
    sentry.io: 18
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
fanboy-annoyance: 79010-66465, 1m
fanboy-cookiemonster: 46736-240, 1m
fanboy-social: 19535-2, 1m
```

Test again without any annoyances filter lists

**Comment by stephenhawk8054** [comment]
Caused by `##.ShareBar` in Fanboy Annoyances.

Add

```adb
feedly.com#@#.ShareBar
```

@ryanbr
