### ISSUE TITLE
funds.web.vanguard.com: breakage

### ISSUE THREAD

**Issue by StephanTLavavej** [uBlockOrigin/uAssets#17658]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://funds.web.vanguard.com/c/trade?nonRetirementMode=true&transactionType=BUY`

### Category

breakage

### Description

To get to this page from Vanguard's account overview:

* Click on My Accounts > Transactions > Buy & Sell
* Scroll down and click "Trade Vanguard mutual funds"
* Click "Buy" in the in-page dialog box

This page has a blue link at the bottom, "Use the full purchase page". Clicking it displays another in-page dialog box, with a button "Go to full experience". The issue is that this "Go to full experience" button often doesn't work (clicking it does nothing, instead of navigating to the intended destination which is an old-style page) when uBlock Origin is enabled, but works reliably when uBO is disabled. Strangely, the breakage isn't 100% - it seems that when I navigate to this page (with uBO enabled) and then quickly click the button, it usually doesn't work, but if I wait a while, sometimes it'll work. Based on how it always seems to work with uBO disabled, I think it's a filter issue but I'm not absolutely certain.

A Vanguard account is required to reproduce this issue, but fortunately it involves no actual transactions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1012" alt="vanguard_ubo_issue" src="https://user-images.githubusercontent.com/4231088/232983207-9c291ab0-611b-45d0-aabe-5d3312fd62bd.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 89827
  cosmetic: 39969
  scriptlet: 17759
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65278-44, now
    easyprivacy: 30871-1176, now
    plowe-0: 3749-940, now
    ublock-abuse: 70-0, now
    ublock-badware: 6799-117, now
    ublock-filters: 33866-102, now
    ublock-privacy: 316-3, now
    ublock-quick-fixes: 186-22, now
    ublock-unbreak: 1986-45, now
    urlhaus-1: 7056-0, now
filterset (user): [empty]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 202 ms (selfie)
  maxAssetCacheWait: 66 ms
popupPanel: 
  blocked: 12
  blockedDetails: 
    adsrvr.org: 1
    bugsnag.com: 2
    doubleclick.net: 2
    kampyle.com: 4
    linkedin.com: 1
    vgdynamic.info: 1
    yahoo.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you do these steps:

- Click on ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger) on the [popup user interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface), 
- Reload the page and repeat the steps until issue happens,
- Go to the logger again, [click on search bar and choose `blocked`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output),
- Copy the logger via [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog),
- Paste the logs here

**Comment by mapx-** [comment]
@StephanTLavavej keep commenting here if you have the info requested above
