### ISSUE TITLE
bing.com: breakage

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#17650]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I use the “Bing Chat for All Browsers” or “User-Agent Switcher and Manager” extension on Firefox with uBlock Origin enabled, the Bing Chat feature is not available. Instead, when I disable uBlock Origin, it starts working again.

### URL(s) where the issue occurs.

`https://www.bing.com`

### Screenshot(s)

With uBlock Origin enabled:

![immagine](https://user-images.githubusercontent.com/62190484/232706007-284b8b93-5e80-4002-8fc3-42e9160f491c.png)

With uBlock Origin disabled:

![immagine](https://user-images.githubusercontent.com/62190484/232705920-6725ae38-339b-4ec5-be84-ef5a51e75938.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 95131
  cosmetic: 47695
  scriptlet: 17715
  html: 949
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34653-71, 1d.37m
    ublock-badware: 6698-0, 1d.36m
    ublock-privacy: 361-14, 16h.29m
    ublock-abuse: 70-0, 16h.28m
    ublock-unbreak: 2000-5, 1d.35m
    ublock-quick-fixes: 185-0, 15m
    easylist: 64942-615, 1d.34m
    easyprivacy: 30858-1773, 1d.33m
    urlhaus-1: 7073-1, 14m
    plowe-0: 3750-3, 4d.16h.53m
    ITA-0: 13558-1, 16m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 613 ms (selfie)
  maxAssetCacheWait: 49 ms
```
</details>

**Comment by mapx-** [comment]
clear all cookies, then log IN, it should work, at least on my end testing `Bing Chat for All Browsers`

**Comment by fabriziobagala** [comment]
> clear all cookies, then log IN, it should work, at least on my end testing `Bing Chat for All Browsers`

@mapx- Only by disabling uBlock Origin can I make it work. Clearing cookies with uBlock Origin enabled does not work.

**Comment by fabriziobagala** [comment]
@mapx- I did a test to try to figure out which filter might be causing problems. By disabling uBlock filters, EasyList, EasyPrivacy and ITA: EasyList Italy, the issue does not occur. I assume there is a rule among these filter lists that is causing issues.

**Comment by mapx-** [comment]
- well, it does not help, you practically disabled all the lists
- you should open the logger, repeat the steps to get the issue, go back into the logger and whitelist one by one the filters applied there (then again repeat the steps ...etc) to find the "wrong" one

**Comment by fabriziobagala** [comment]
@mapx- I found a solution. Adding these filters Bing Chat works:

```
@@||www.bing.com/fd/ls/lsp.aspx$domain=www.bing.com
@@||www.bing.com/fd/ls/l$domain=www.bing.com
@@||www.bing.com/geolocation/write$domain=www.bing.com
@@||www.bing.com/rewardsapp/reportActivity$domain=www.bing.com
```

**Comment by mapx-** [comment]
- still cannot reproduce your issue
- keep the last 2 exceptions and test again, see if works

**Comment by fabriziobagala** [comment]
I left only the filters:

```
@@||www.bing.com/geolocation/write$domain=www.bing.com
@@||www.bing.com/rewardsapp/reportActivity$domain=www.bing.com
```

Bing Chat is still working.
