### ISSUE TITLE
fingerprint.com: privacy

### ISSUE THREAD

**Issue by ACK-J** [uBlockOrigin/uAssets#17652]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Telemetry is sent to this domain. `analytics2.dashboard.fingerprint.com`

### URL(s) where the issue occurs.

`https://fingerprint.com/`

### uBO version

1.48.4

### Browser name and version

Firefox 110

### Settings

Add the domain

**Comment by mapx-** [comment]
> Telemetry is sent to this domain.

sent from ... where ?

**Comment by ACK-J** [comment]
My mistake, the domain didn't paste.
https://fingerprint.com/

**Comment by JobcenterTycoon** [comment]
Ok i see what you mean.

EP contains `analytics.dashboard.fingerprint.com` but they circumented with `analytics2.dashboard.fingerprint.com`

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/e0cb2b03

**Comment by ACK-J** [comment]
The analytics server has now changed to be `analytics4.dashboard.fingerprint.com`. I propose we add a regex wildcard for any number that they choose
