### ISSUE TITLE
foodnetwork.com: breakage

### ISSUE THREAD

**Issue by Anthiam** [uBlockOrigin/uAssets#17665]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.foodnetwork.com/sponsored/sweepstakes/hgtv-smart-home-sweepstakes?nl=R-HGTV%3ASH2023_2023-04-18_EnterFood&bid=f732d615-e493-4a0a-84f2-58e3cbc2624b&c32=c50c6516be293db9ed31047553c662611db62512&source&gender=unknown&birth_year=1987&utm_content=smart-home-2023-daily-reminder&bsft_clkid=e63ea7fc-7890-4889-88f4-6317ad9ae0f1&bsft_uid=a7926831-288b-44ec-bba1-0700262daa39&bsft_mid=1f07ac39-6022-425c-8fcb-590657497414&bsft_eid=453a0cb3-aaa2-4fb2-995b-65cb7bb689c9&bsft_mime_type=html&bsft_ek=2023-04-18T14%3A21%3A02Z&bsft_aaid=64454161-11c0-4b54-98e4-428154f59400&bsft_lx=13&bsft_tv=58`

### Category

breakage

### Description

Unable to submit the form when ublock origin is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 89414
  cosmetic: 39919
  scriptlet: 17720
  html: 949
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34696-120, 2d.10h.48m
    ublock-badware: 6716-1, 2d.10h.47m
    ublock-privacy: 352-0, 10d.14h.22m
    ublock-abuse: 78-0, 10d.14h.21m
    ublock-unbreak: 1998-4, 2d.10h.46m
    ublock-quick-fixes: 175-0, 10h.38m
    easylist: 64939-525, 2d.10h.45m
    easyprivacy: 30858-1792, 2d.10h.44m
    urlhaus-1: 7056-0, 10h.37m
    plowe-0: 3750-1, 6d.19h.2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 378 ms (selfie)
  maxAssetCacheWait: 96 ms
popupPanel: 
  blocked: 38
  blockedDetails: 
    foodnetwork.com: 1
    adobedtm.com: 7
    associates-amazon.com: 1
    criteo.net: 1
    demdex.net: 1
    doubleverify.com: 2
    go-mpulse.net: 2
    googlesyndication.com: 4
    googletagmanager.com: 2
    liadm.com: 1
    ngtv.io: 1
    scorecardresearch.com: 1
    serving-sys.com: 3
    skimresources.com: 1
    snidigital.com: 2
    trackonomics.net: 1
    tru.am: 1
    wayin.com: 1
    wmcdp.io: 4
    yimg.com: 1
```
</details>

**Comment by mapx-** [comment]
test this filter

`@@||assets.adobedtm.com/*/satelliteLib$script,domain=wayin.com`

**Comment by Anthiam** [comment]
That did the trick. Thanks
