### ISSUE TITLE
studysmarter.de: ads

### ISSUE THREAD

**Issue by Kevin080408** [uBlockOrigin/uAssets#17663]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.studysmarter.de/schule/geschichte/weimarer-republik/hyperinflation-1923/`

### Category

ads

### Description

Ad of penny not blocked (german ad)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 91790
  cosmetic: 44426
  scriptlet: 17744
  html: 950
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, 22h.58m
    https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 34739-77, 1h.58m
    ublock-badware: 6737-0, 1h.57m
    ublock-privacy: 345-0, 2d.22h.29m
    ublock-abuse: 70-0, 2d.22h.28m
    ublock-unbreak: 1997-0, 1h.59m
    easylist: 65067-617, 1h.56m
    easyprivacy: 30862-1781, 1h.55m
    plowe-0: 3749-3, 22h.59m
    DEU-0: 6772-2, 22h.55m
    urlhaus-1: 7051-1, 22h.57m
    ublock-quick-fixes: 185-5, 22h.56m
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 584 ms (selfie)
  maxAssetCacheWait: 208 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    amplitude.com: 3
    googleoptimize.com: 2
    googletagmanager.com: 1
    sentry.io: 1
```
</details>

**Comment by gorhill** [comment]
studysmarter.de##[data-adv-location]

Fixable in EasyList Germany.
