### ISSUE TITLE
shopee.tw issues

### ISSUE THREAD

**Issue by weijen6** [uBlockOrigin/uAssets#17661]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

shopee.tw blocked the homepage advertisement, but at the same time, it also disabled other normal pop-up functions

### URL(s) where the issue occurs.

shopee.tw/cart

### Screenshot(s)

![image](https://user-images.githubusercontent.com/32688959/233050090-b3517499-e6e0-4cbb-916d-82543a65ff90.png)

### uBO version

uBlock Origin 1.48.4

### Browser name and version

CHROME 112.0.5615.121

### Settings

no

**Comment by stephenhawk8054** [comment]
Can you click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools), scroll to the bottom and copy your `Troubleshooting Information` to here?

**Comment by weijen6** [comment]
Thank you, I have opened a new issue, then I will close this issue
