### ISSUE TITLE
play.tv3.lt: detection

### ISSUE THREAD

**Issue by niauer** [uBlockOrigin/uAssets#17667]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.tv3.lt/`

### Category

detection

### Description

Any video you try to play on this site detects uBlock Origin. Still worked 1 day ago just fine. uBlock Origin 1.49.0 update maybe?
Tried a fresh install on Firefox as well, same issue.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 89636
 cosmetic: 39946
 scriptlet: 17759
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65067-44, 2h.7m
  easyprivacy: 30862-1176, 2h.7m
  plowe-0: 3749-940, 2h.7m
  ublock-abuse: 70-0, 2h.7m
  ublock-badware: 6799-117, 2h.7m
  ublock-filters: 33865-102, 2h.7m
  ublock-privacy: 316-3, 2h.7m
  ublock-quick-fixes: 186-22, 2h.6m
  ublock-unbreak: 1989-45, 2h.6m
  urlhaus-1: 7056-0, 2h.6m
filterset (user): [empty]
trustedset: 
 removed: 
  chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 249 ms
 maxAssetCacheWait: 108 ms
popupPanel: 
 blocked: 29
 network: 
  tv3.lt: 3
  chartbeat.com: 1
  fwmrm.net: 1
  gemius.pl: 2
  go3.tv: 7
  googletagmanager.com: 1
  sentry.io: 11
  stickyadstv.com: 3
 cosmetic: 
  ###AdHeader
  ###AD_Top
  ###homead
  ###ad-lead
```
</details>

**Comment by gorhill** [comment]
Subscribe to _LTU: EasyList Lithuania_ in _Filter lists_.
