### ISSUE TITLE
kicker.de: nuisance

### ISSUE THREAD

**Issue by MrUrf** [uBlockOrigin/uAssets#17668]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kicker.de/jahn-regensburg-gegen-1-fc-kaiserslautern`

### Category

nuisance

### Description

Nuisance through tracking consent overlay. 
Users is forced to consent to tracking on this webpage

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![racking consent overlay](https://user-images.githubusercontent.com/46406187/233097871-03541c4a-6563-411d-b606-8e39e2c537a6.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 91973
  cosmetic: 44378
  scriptlet: 17695
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    DEU-0: 6773-0, now
    easylist: 65257-50, now
    easyprivacy: 30873-1185, now
    plowe-0: 3749-941, now
    ublock-abuse: 70-0, now
    ublock-badware: 6804-117, now
    ublock-filters: 33876-116, now
    ublock-privacy: 316-3, now
    ublock-unbreak: 1989-43, now
    urlhaus-1: 6968-0, now
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 16 redacted]
switchRuleset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 355 ms (selfie)
  maxAssetCacheWait: 162 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    kicker.de: 1
    usercentrics.eu: 1
```
</details>

**Comment by gorhill** [comment]
This works?

    kicker.de###kick__pur__layer

**Comment by okiehsch** [comment]
It's a GDPR modal, we don't add filters for such issues.
The mentioned filter hides the modal and breaks the podcast and `kicker.tv` section..
