### ISSUE TITLE
TomahawkTake anti adblock

### ISSUE THREAD

**Issue by OldChief** [uBlockOrigin/uAssets#1766]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[ https://tomahawktake.com/ ]`

### Describe the issue

The admiral powered anti-adblocker still blocks access to the site with Nano-Defender installed
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]
![image](https://user-images.githubusercontent.com/19169244/37840055-15232f96-2e8a-11e8-9f16-1ec8c3aec522.png)

### Versions

- Browser/version: [Version 65.0.3325.181 (Official Build) (64-bit)]
- uBlock Origin version: [uBlock Origin v1.15.18]

### Settings

- [I followed the instructions on your installation page, nothing more]

### Notes

[here is the log nano- log page for the offending web page on opening]

11:11:30 |   |   |   | xhr | https://gammamaximum.com/c3bc8dc4e59aa89bb6308835b4425e20b0106eb6bf8f2adb29860e75da77efa514c985dd1d5c89dc986e0f4e95f437c6ef8d6ef931a8cc4a9bc3a5a96e4a8a3b84d058ed169ced896d05e05f
-- | -- | -- | -- | -- | --
11:11:30 |   |   |   | image | https://www.timeinc.com/wp-content/uploads/2013/05/fansided.png
11:11:29 |   |   |   | css | https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300
11:11:29 |   |   |   | image | https://fansided.com/wp-content/assets/site_images/fansided/fsadgate_image-2a1.jpg
11:11:29 |   |   |   | script | https://gammamaximum.com/8c00445b950607ea13875fac9cff6c2bfbe55e218e82910d3ea7c3b50f92c761f6d3ebe582930f13cbd3cb9dc0d9466c2c29e68b67027a05da68593dbcf14b7ab6a02bd58bccef96a5bf12bfee
11:11:28 |   |   |   | xhr | https://gammamaximum.com/20d2cb42db64e4083b2afaa37fdc5fd3b32cd7fa3748cee9a4ec596aa88af75e2a3d75fd15a91d5df94576fff237b9e2c6f9ae10ad720165e539b71d10ebe9a115b6edd921e2564bc80c43cf
11:11:28 |   | google-analytics.com/analytics.js | << | script | https://www.google-analytics.com/analytics.js
11:11:28 |   | \|\|google-analytics.com^ | -- | script | https://www.google-analytics.com/analytics.js
11:11:28 |   | googletagmanager.com/gtm.js | << | script | https://www.googletagmanager.com/gtm.js?id=GTM-K8GZZJG&l=dataLayer
11:11:28 |   | \|\|googletagmanager.com/gtm.js?$third-party | -- | script | https://www.googletagmanager.com/gtm.js?id=GTM-K8GZZJG&l=dataLayer
11:11:28 |   | \|\|d1z2jf7jlzjs58.cloudfront.net^ | -- | script | https://d1z2jf7jlzjs58.cloudfront.net/p.js
11:11:27 |   | \|\|doubleclick.net^ | -- | script | https://ad.doubleclick.net/ddm/adj/Buky/Brip
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/rajdhani/v7/LDI2apCSOBg7S-QT7pa8FvOreec.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/rajdhani/v7/LDI2apCSOBg7S-QT7pbYF_Oreec.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/rajdhani/v7/LDIxapCSOBg7S-QT7p4HM-Y.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/nunito/v9/XRXW3I6Li01BKofAjsOUYevI.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/nunito/v9/XRXW3I6Li01BKofA6sKUYevI.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/nunito/v9/XRXV3I6Li01BKofINeaB.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/droidserif/v8/tDbX2oqRg1oM3QBjjcaDkOr4lLz5CwOnSA.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/droidserif/v8/tDbV2oqRg1oM3QBjjcaDkOJGiRD7OwE.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/droidserif/v8/tDbK2oqRg1oM3QBjjcaDkOr4nAfcHg.woff2
11:11:27 |   |   |   | font | https://fonts.gstatic.com/s/droidserif/v8/tDbI2oqRg1oM3QBjjcaDkOr9rAU.woff2
11:11:26 |   | ##.fs_ads |   | dom | https://tomahawktake.com/
11:11:26 |   | ###sidebar_ad_1 |   | dom | https://tomahawktake.com/
11:11:26 |   | \|\|doubleclick.net^ | -- | script | https://ad.doubleclick.net/ddm/adj/Bqgl/Bfhi
11:11:26 |   | \|\|assoc-amazon.com^ | -- | script | https://wms.assoc-amazon.com/20070822/US/js/auto-tagger.js?tag=sportsillustrated0f-20&locale=US&overwrite=1
11:11:26 |   | \|\|segment.io^$third-party | -- | xhr | https://api.segment.io/v1/t
11:11:25 |   |   |   | xhr | https://stats.api.si.com/v1/mlb/tickets?team_abbr=atl
11:11:25 |   |   |   | xhr | https://stats.api.si.com/v1/all_sports/active_leagues?date=2018-03-23
11:11:25 |   |   |   | xhr | https://personalization.api.si.com/status-check
11:11:25 |   | \|\|segment.io^$third-party | -- | xhr | https://api.segment.io/v1/t
11:11:25 |   | \|\|segment.io^$third-party | -- | xhr | https://api.segment.io/v1/p
11:11:25 |   |   |   | script | https://www.si.com/dist/15-15.js
11:11:25 |   |   |   | script | https://www.si.com/dist/1-1.js
11:11:25 |   |   |   | script | https://www.si.com/dist/3-3.js
11:11:25 |   |   |   | script | https://www.si.com/dist/2-2.js
11:11:25 |   |   |   | script | https://www.si.com/dist/6-6.js
11:11:25 |   |   |   | script | https://www.si.com/dist/24-24.js
11:11:25 |   |   |   | script | https://www.si.com/dist/14-14.js
11:11:25 |   |   |   | script | https://www.si.com/dist/7-7.js
11:11:25 |   |   |   | script | https://www.si.com/dist/30-30.js
11:11:25 |   |   |   | script | https://www.si.com/sw.js
11:11:25 |   |   |   | script | https://www.si.com/dist/4-4.js
11:11:25 |   |   |   | script | https://www.si.com/dist/31-31.js
11:11:24 |   | \|\|googlesyndication.com^ | -- | frame | https://tpc.googlesyndication.com/safeframe/1-0-13/html/container.html
11:11:24 |   |   |   | script | https://www.si.com/sw.js
11:11:24 |   |   |   | css | https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i%7CNunito:400,600,700%7CRajdhani:400,600,700
11:11:23 |   | @@\|\|segment.com/analytics.js/*/analytics.min.js$script | ++ | script | https://cdn.segment.com/analytics.js/v1/nS9MXqQP5fFFOZ9X23O4vHExpX9MCNDv/analytics.min.js
11:11:23 |   |   |   | script | https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js
11:11:23 |   | google-analytics.com/analytics.js | << | script | https://www.google-analytics.com/analytics.js
11:11:23 |   | \|\|google-analytics.com^ | -- | script | https://www.google-analytics.com/analytics.js
11:11:23 |   | \|\|d1z2jf7jlzjs58.cloudfront.net^ | -- | script | https://d1z2jf7jlzjs58.cloudfront.net/p.js
11:11:23 |   | googletagmanager.com/gtm.js | << | script | https://www.googletagmanager.com/gtm.js?id=GTM-K8GZZJG&l=dataLayer
11:11:23 |   | \|\|googletagmanager.com/gtm.js?$third-party | -- | script | https://www.googletagmanager.com/gtm.js?id=GTM-K8GZZJG&l=dataLayer
11:11:23 |   |   |   | css | https://www.si.com/dist/style.css
11:11:23 |   | \|\|sharethrough.com^ | -- | script | https://native.sharethrough.com/assets/sfp.js
11:11:23 |   |   |   | script | https://www.si.com/dist/main.js
11:11:23 |   | \|\|tia.timeinc.net^ | -- | script | https://tia.timeinc.net/si/mm.min.js?cb=1
11:11:23 |   |   |   | inline-script | https://www.si.com/embed/vivid-widget/page-team/league-mlb/wsuser-764/wsvar-FSteamwidget/teamAbbr-Atl/isPreGame-true/country-US?json=%7B%22type%22%3A%22vivid-widget%22%2C%22data%22%3A%7B%22page%22%3A%22team%22%2C%22league%22%3A%22mlb%22%2C%22wsuser%22%3A%22764%22%2C%22wsvar%22%3A%22FSteamwidget%22%2C%22teamAbbr%22%3A%22Atl%22%2C%22isPreGame%22%3A%22true%22%2C%22country%22%3A%22US%22%7D%7D
11:11:23 |   |   |   | frame | https://www.si.com/embed/vivid-widget/page-team/league-mlb/wsuser-764/wsvar-FSteamwidget/teamAbbr-Atl/isPreGame-true/country-US?json=%7B%22type%22%3A%22vivid-widget%22%2C%22data%22%3A%7B%22page%22%3A%22team%22%2C%22league%22%3A%22mlb%22%2C%22wsuser%22%3A%22764%22%2C%22wsvar%22%3A%22FSteamwidget%22%2C%22teamAbbr%22%3A%22Atl%22%2C%22isPreGame%22%3A%22true%22%2C%22country%22%3A%22US%22%7D%7D
11:11:23 |   |   |   | frame | https://www.si.com/embed/vivid-widget/page-team/league-mlb/wsuser-764/wsvar-FSteamwidget/teamAbbr-Atl/isPreGame-true/country-US?json=%7B%22type%22%3A%22vivid-widget%22%2C%22data%22%3A%7B%22page%22%3A%22team%22%2C%22league%22%3A%22mlb%22%2C%22wsuser%22%3A%22764%22%2C%22wsvar%22%3A%22FSteamwidget%22%2C%22teamAbbr%22%3A%22Atl%22%2C%22isPreGame%22%3A%22true%22%2C%22country%22%3A%22US%22%7D%7D
11:11:23 |   |   |   | inline-script | https://www.si.com/embed?json=%7B%22type%22%3A%22vivid-widget%22%2C%22data%22%3A%7B%22page%22%3A%22team%22%2C%22league%22%3A%22mlb%22%2C%22wsuser%22%3A%22764%22%2C%22wsvar%22%3A%22FSteamwidget%22%2C%22teamAbbr%22%3A%22Atl%22%2C%22isPreGame%22%3A%22true%22%2C%22country%22%3A%22US%22%7D%7D
11:11:23 |   |   |   | xhr | https://syndication.twitter.com/settings
11:11:23 |   |   |   | inline-script | https://platform.twitter.com/widgets/widget_iframe.f47a2e0b4471326b6fa0f163bda46011.html?origin=https%3A%2F%2Ftomahawktake.com
11:11:23 |   |   |   | frame | https://www.si.com/embed?json=%7B%22type%22%3A%22vivid-widget%22%2C%22data%22%3A%7B%22page%22%3A%22team%22%2C%22league%22%3A%22mlb%22%2C%22wsuser%22%3A%22764%22%2C%22wsvar%22%3A%22FSteamwidget%22%2C%22teamAbbr%22%3A%22Atl%22%2C%22isPreGame%22%3A%22true%22%2C%22country%22%3A%22US%22%7D%7D
11:11:23 |   |   |   | frame | https://platform.twitter.com/widgets/widget_iframe.f47a2e0b4471326b6fa0f163bda46011.html?origin=https%3A%2F%2Ftomahawktake.com
11:11:23 |   |   |   | font | https://fonts.gstatic.com/s/titilliumweb/v4/anMUvcNT0H1YN4FII8wpr0bathaSTBR2c4i13_wzlb0.woff
11:11:23 |   |   |   | font | https://fonts.gstatic.com/s/titilliumweb/v4/anMUvcNT0H1YN4FII8wpr24bNCNEoFTpS2BTjF6FB5E.woff
11:11:23 |   |   |   | font | https://fonts.gstatic.com/s/titilliumweb/v4/7XUFZ5tgS-tD6QamInJTcdGU7DQ8I6RFMlK0vgclk7w.woff
11:11:23 |   |   |   | font | https://fonts.gstatic.com/s/oswald/v10/HqHm7BVC_nzzTui2lzQTDaCWcynf_cDxXwCLxiixG1c.ttf
11:11:23 |   |   |   | font | https://fonts.gstatic.com/s/oswald/v10/bH7276GfdCjMjApa_dkG6aCWcynf_cDxXwCLxiixG1c.ttf
11:11:23 |   |   |   | font | https://fonts.gstatic.com/s/oswald/v10/Y_TKV6o8WovbUd3m_X9aAA.ttf
11:11:23 |   |   |   | font | https://cdn.fansided.com/wp-content/themes/fansided-v5/assets/fonts/FontSided1dot5.woff?v=1.5
11:11:23 |   |   |   | font | https://fonts.gstatic.com/s/titilliumweb/v4/anMUvcNT0H1YN4FII8wprx7IBmrqA5IG9z8WNe77b9o.woff
11:11:23 |   |   |   | image | https://cdn.fansided.com/logos/navigation/si-logo-letters.min.svg
11:11:23 |   |   |   | image | https://imagesvc.timeincapp.com/v3/fan/image?url=https%3A%2F%2Ftomahawktake.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2018%2F03%2F835324050-cincinnati-reds-v-atlanta-braves.jpg.jpg&w=300&h=160&c=sc
11:11:23 |   |   |   | image | https://imagesvc.timeincapp.com/v3/fan/image?url=https%3A%2F%2Ftomahawktake.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2017%2F10%2F853070180-philadelphia-phillies-v-atlanta-braves.jpg.jpg&w=580&h=340&c=sc
11:11:23 |   |   |   | image | https://imagesvc.timeincapp.com/v3/fan/image?url=https%3A%2F%2Ftomahawktake.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2017%2F08%2F687557012-pittsburgh-pirates-v-atlanta-braves.jpg.jpg&w=580&h=480&c=sc
11:11:22 |   | \|\|sharethrough.com^ | -- | script | https://native.sharethrough.com/assets/sfp.js?ver=4.8.2
11:11:22 |   | \|\|bounceexchange.com^ | -- | script | https://tag.bounceexchange.com/1540/i.js
11:11:22 |   |   |   | script | https://gammamaximum.com/ac595b0bd1b1f6e62ce46c2ce57c936ea6f47b8e2936dc2a3876a18eadffd94a289806f2a42865c2057288dd30b30f07490e2c6ae59ea0f801f1a13317ea
11:11:22 |   | \|\|d3ujids68p6xmq.cloudfront.net^ | -- | script | https://d3ujids68p6xmq.cloudfront.net/abw.js
11:11:22 |   |   |   | script | https://platform.twitter.com/widgets.js
11:11:22 |   | scorecardresearch.com/beacon.js | << | script | https://sb.scorecardresearch.com/beacon.js
11:11:22 |   | \|\|scorecardresearch.com^ | -- | script | https://sb.scorecardresearch.com/beacon.js
11:11:22 |   | \|\|segment.io^$third-party | -- | xhr | https://api.segment.io/v1/p
11:11:22 |   | google-analytics.com/analytics.js | << | script | https://www.google-analytics.com/analytics.js
11:11:22 |   | \|\|google-analytics.com^ | -- | script | https://www.google-analytics.com/analytics.js
11:11:22 |   | \|\|vindicosuite.com^$third-party | -- | script | https://mpp.vindicosuite.com/bg/?pid=2020&t=j&tpr=0&spd=1&sg=mlb&rnd=1&page=%20https%3A%2F%2Ftomahawktake.com
11:11:22 |   | \|\|tia.timeinc.net^ | -- | script | https://tia.timeinc.net/timeinc/tia_tgx.min.js
11:11:22 |   | \|\|connect.facebook.net^*/fbevents.js$third-party | -- | script | https://connect.facebook.net/en_US/fbevents.js
11:11:22 |   | @@\|\|segment.com/analytics.js/*/analytics.min.js$script | ++ | script | https://cdn.segment.com/analytics.js/v1/HiODwELLwwwIVn9UHCUh9st6r8sdyoB1/analytics.min.js
11:11:21 |   | \|\|sharethrough.com^ | -- | script | https://native.sharethrough.com/assets/sfp.js?ver=4.8.2
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-includes/js/wp-embed.js?ver=4.8.2
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-content/themes/fansided-v5/network-nav/network-nav.min.js?ver=2.40.1
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-content/themes/fansided-v5/assets/js/main.min.js?ver=2.40.1
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-content/themes/fansided-v5/assets/js/slick.min.js?ver=2.40.1
11:11:21 |   | widgets.outbrain.com/outbrain.js | << | script | https://widgets.outbrain.com/outbrain.js?ver=2.40.1
11:11:21 |   | \|\|outbrain.com^ | -- | script | https://widgets.outbrain.com/outbrain.js?ver=2.40.1
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-content/themes/fansided-v5/assets/js/fs-event-preview.min.js?ver=2.40.1
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-content/themes/fansided-v5/assets/js/longform.min.js?ver=2.40.1
11:11:21 |   | \|\|d3ujids68p6xmq.cloudfront.net^ | -- | script | https://d3ujids68p6xmq.cloudfront.net/abw.js
11:11:21 |   |   |   | image | https://tomahawktake.com/wp-content/themes/fansided-v5/assets/images/android-app.png
11:11:21 |   |   |   | image | https://tomahawktake.com/wp-content/themes/fansided-v5/assets/images/apple-app.png
11:11:21 |   |   |   | image | https://cdn.fansided.com/wp-content/themes/fansided-v5/assets/images/fansided-logo.svg
11:11:21 |   |   |   | image | https://cdn.fansided.com/logos/mlb/braves.png
11:11:21 |   |   |   | image | https://imagesvc.timeincapp.com/v3/fan/image?url=https://fansided.com/wp-content/assets/site_images/braves/logo_tomahawktake-com__150x150.png&w=150&h=150
11:11:21 |   | \|\|vindicosuite.com^$third-party | -- | script | https://mpp.vindicosuite.com/bg/?pid=2020&t=j&tpr=0&spd=1&sg=mlb&rnd=1&page=%20https%3A%2F%2Ftomahawktake.com
11:11:21 |   | \|\|tia.timeinc.net^ | -- | script | https://tia.timeinc.net/timeinc/tia_tgx.min.js
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-content/themes/fansided-v5/assets/js/iframeSizer.min.js?ver=2.40.1
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-includes/js/jquery/jquery.js?ver=1.12.4
11:11:21 |   |   |   | css | https://cdn.fansided.com/wp-content/themes/fansided-v5/network-nav/network-nav.css?ver=2.40.1
11:11:21 |   |   |   | css | https://tomahawktake.com/wp-content/plugins/fansided-shortcodes/dist/styles/recent-posts-web-4243ce7955.css
11:11:21 |   |   |   | css | https://cdn.fansided.com/wp-content/themes/fansided-v5/assets/css/style.css?ver=2.40.1
11:11:21 |   |   |   | css | https://fonts.googleapis.com/css?family=Titillium+Web&ver=2.40.1
11:11:21 |   |   |   | css | https://fonts.googleapis.com/css?family=Oswald&ver=2.40.1
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-includes/js/wp-emoji.js?ver=4.8.2
11:11:21 |   |   |   | script | https://cdn.fansided.com/wp-includes/js/twemoji.js?ver=4.8.2
11:11:21 |   |   |   | inline-script | https://tomahawktake.com/
11:11:21 |   |   |   | doc | https://tomahawktake.com/
  |   | https://tomahawktake.com/
11:11:21 |   |   |   | inline-script | https://www.tomahawktake.com/
11:11:21 |   |   |   | doc | https://www.tomahawktake.com/
  |   | https://www.tomahawktake.com/
11:11:21 |   |   |   | doc | http://www.tomahawktake.com/
  |   | http://www.tomahawktake.com/
11:09:58 |   |   |   | script | https://www.si.com/sw.js
11:09:57 |   |   |   | script | https://www.si.com/sw.js
11:09:56 |   |   |   | script | https://www.si.com/sw.js
11:08:52 |   |   |   | xhr | https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt?_=211364
11:03:52 |   |   |   | xhr | https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt?_=211364
11:03:09 |   |   |   | script | https://www.si.com/sw.js
11:03:09 |   |   |   | script | https://www.si.com/sw.js
11:03:08 |   |   |   | script | https://www.si.com/sw.js
10:58:52 |   |   |   | xhr | https://publicsuffix.org/list/public_suffix_list.dat?_=211363
10:53:52 |   |   |   | xhr | https://raw.githubusercontent.com/NanoAdblocker/NanoCore/master/assets/assets.json?_=211363
10:48:17 |   |   |   | image | https://assets-cdn.github.com/favicon.ico
10:48:17 |   |   |   | image | https://github.com/fluidicon.png
10:48:15 |   |   |   | image | https://outgoing.prod.mozaws.net/favicon.ico
10:47:24 |   |   |   | script | https://www.si.com/sw.js
10:47:23 |   |   |   | script | https://www.si.com/sw.js
10:47:23 |   |   |   | script | https://www.si.com/sw.js

**Comment by mapx-** [comment]
Test this filter (I cannot reproduce the issue)

`tomahawktake.com##script:inject(addEventListener-defuser.js, p5, onpropertychange)`

**Comment by OldChief** [comment]
That seems to have worked. Thanks
