### ISSUE TITLE
seattlepi.com: breakage

### ISSUE THREAD

**Issue by regan-karlewicz** [uBlockOrigin/uAssets#17669]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

SeattlePI has a element class name which is blocked by uBlock origin. The class is `.b-gray300`.

I wasn't able to find the list that uBlock Origin uses, but I think it may be related to this list: https://easylist-downloads.adblockplus.org/easylist-minified.txt

### URL(s) where the issue occurs.

https://www.seattlepi.com
https://www.seattlepi.com/sports
https://www.seattlepi.com/shopping
https://www.seattlepi.com/shopping/article/how-to-organize-outdoor-gear-17864916.php

+ any other page on seattlepi.com

### Screenshot(s)

uBlock enabled (missing masthead, affiliate disclaimer that use `b-gray300` class):
<img width="1728" alt="Screenshot 2023-04-19 at 10 55 58 AM" src="https://user-images.githubusercontent.com/1987265/233160112-a0f6a95f-fff2-4788-a452-f4d3e61b7ad3.png">

uBlock disabled:
<img width="1728" alt="Screenshot 2023-04-19 at 10 56 07 AM" src="https://user-images.githubusercontent.com/1987265/233160133-6c7d70e2-17b0-44b4-a8e3-3dbf5045fe15.png">

### uBO version

1.49.0

### Browser name and version

Chrome 112.0.5615.121

### Settings

None

**Comment by okiehsch** [comment]
@regan-karlewicz add 
`seattlepi.com#@#.b-gray300`
to your filter list until it has been fixwd in `EasyList`.
@ryanbr fyi
