### ISSUE TITLE
[nsfw] netflix.com: [unknown]

### ISSUE THREAD

**Issue by ketch241** [uBlockOrigin/uAssets#17666]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.netflix.com/ph-en/redeem`

### Category

[unknown]

### Description

i want netflix account

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 89460
 cosmetic: 39940
 scriptlet: 17760
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65032-44, 22m
  easyprivacy: 30864-1176, 22m
  plowe-0: 3749-940, 22m
  ublock-abuse: 70-0, 22m
  ublock-badware: 6733-117, 22m
  ublock-filters: 33871-102, 22m
  ublock-privacy: 316-3, 22m
  ublock-quick-fixes: 186-22, 22m
  ublock-unbreak: 1989-45, 22m
  urlhaus-1: 6968-0, 22m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 491 ms (selfie)
 maxAssetCacheWait: 144 ms
popupPanel: 
 blocked: 1
 network: 
  nflximg.net: 1
```
</details>

**Comment by habib-003** [comment]
hvorfor har du blokeret netflix
