### ISSUE TITLE
live.shoot-yalla.tv: nuisance

### ISSUE THREAD

**Issue by Mostafa-Wahied** [uBlockOrigin/uAssets#17673]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://live.shoot-yalla.tv/online/10581/1016058/bayern-munich-vs-manchester-city/`

### Category

nuisance

### Description

The page detects uBlock and has an overaly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 111
filterset (summary): 
  network: 89459
  cosmetic: 39931
  scriptlet: 17755
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64939-44, 1d.3h.13m
    easyprivacy: 30862-1176, 18h.55m
    plowe-0: 3750-938, 9d.14h.20m
    ublock-abuse: 78-0, 13d.12m
    ublock-badware: 6738-117, 1d.3h.10m
    ublock-filters: 33860-101, 1d.3h.11m
    ublock-privacy: 302-2, 13d.13m
    ublock-quick-fixes: 186-22, 10h.54m
    ublock-unbreak: 1989-44, 1d.3h.12m
    urlhaus-1: 7056-0, 10h.53m
filterset (user): [empty]
trustedset: 
  added: [array of 38 redacted]
switchRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1003 ms (selfie)
  maxAssetCacheWait: 201 ms
popupPanel: 
  blocked: 21
  blockedDetails: 
    aniview.com: 1
    demand.supply: 1
    doubleclick.net: 1
    googlesyndication.com: 9
    googletagmanager.com: 1
    greeter.me: 2
    gstatic.com: 5
    modoro360.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It was fixed recently. Force update all your filter lists and test again.

**Comment by Mostafa-Wahied** [comment]
I forced update before and didn't work before, but updated again now and it solved the issue.

**Comment by stephenhawk8054** [comment]
> I forced update before and didn't work before

You should force update and test again right **_before_** submitting the issue to confirm precisely. Your troubleshooting information says that the last update was a day ago.
