### ISSUE TITLE
hacoos.com: detection

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#17677]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hacoos.com/`

### Category

detection

### Description

this https://github.com/uBlockOrigin/uAssets/commit/fd7f513b1b3106656747d40eb147d50d3cec684e commit works in Chrome but not in Firefox.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/233210220-e62fe43b-6eca-4809-8bc1-f460a250bd13.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 91502
  cosmetic: 49157
  scriptlet: 19033
  html: 951
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34758-66, now
    ublock-badware: 6808-1, now
    ublock-privacy: 366-0, now
    ublock-abuse: 70-0, now
    ublock-unbreak: 2001-5, now
    ublock-quick-fixes: 187-0, now
    easylist: 65257-630, now
    easyprivacy: 30873-1777, now
    urlhaus-1: 6968-0, now
    plowe-0: 3748-2, now
    TUR-0: 12275-12, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3161 ms
  maxAssetCacheWait: 51 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    googletagmanager.com: 2
    jsdelivr.net: 2
```
</details>

**Comment by propagandism** [comment]
`@@||cdn.jsdelivr.net/gh/qxxomer/reklam@master/reklam.js` seems to work

---

@Yuki2718 `https://www.hacoos.com/2023/01/kahve-agaci.html` `hacoos.com##.yazicireklam`

**Comment by Yuki2718** [comment]
I now get detection even with blocker disabled.
