### ISSUE TITLE
[nsfw] megaup.net: detection

### ISSUE THREAD

**Issue by MeDVL73** [uBlockOrigin/uAssets#17687]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/1dA4p/Gordon.Streaman.2.rar`

### Category

detection

### Description

still showing ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 90126
 cosmetic: 39969
 scriptlet: 17773
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 9-2, never
  easylist: 65455-44, 1m
  easyprivacy: 30880-1180, now
  plowe-0: 3748-940, now
  ublock-abuse: 70-0, now
  ublock-badware: 6813-120, now
  ublock-filters: 33913-102, now
  ublock-privacy: 321-3, now
  ublock-quick-fixes: 204-34, now
  ublock-unbreak: 1991-45, now
  urlhaus-1: 7107-0, now
filterset (user): [array of 11 redacted]
trustedset: 
 added: [array of 44 redacted]
switchRuleset: 
 added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 360 ms (selfie)
 maxAssetCacheWait: 128 ms
popupPanel: 
 blocked: 10
 network: 
  megaup.net: 2
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 1
  dmmzkfd82wayn.cloudfront.net: 2
  googletagmanager.com: 1
  keydawnawe.com: 1
  s3.amazonaws.com: 1
 cosmetic: 
  ##.download-timer
  ##body:style(overflow-x: hidden !important;)
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
