### ISSUE TITLE
marveloptics.com: breakage

### ISSUE THREAD

**Issue by aguirard** [uBlockOrigin/uAssets#17685]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://marveloptics.com/contact/`

### Category

breakage

### Description

Chat function is disabled by your plugin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/3423159/233399467-0555665a-a409-44c4-acde-a404b912390d.png)

![Screenshot_145](https://user-images.githubusercontent.com/3423159/233398575-b9445375-81cc-43e8-a27f-8bdc1d96e5f5.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.8
Chromium: 112
filterset (summary): 
  network: 89709
  cosmetic: 39933
  scriptlet: 17754
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65032-44, 1d.1h.39m
    easyprivacy: 30873-1176, 1d.1h.38m
    plowe-0: 3748-940, 4d.20h.5m
    ublock-abuse: 70-0, 4d.20h.6m
    ublock-badware: 6733-117, 21h.37m
    ublock-filters: 33865-102, 1d.1h.40m
    ublock-privacy: 294-2, 4d.20h.7m
    ublock-quick-fixes: 182-26, 13h.35m
    ublock-unbreak: 1986-46, 1d.1h.41m
    urlhaus-1: 7239-0, 13h.36m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 933 ms (selfie)
  maxAssetCacheWait: 203 ms
popupPanel: 
  blocked: 7
  no-cosmetic-filtering: true
  blockedDetails: 
    googletagmanager.com: 1
    klaviyo.com: 5
    ping-dot-acp-magento.appspot.com: 1
```
</details>

**Comment by gorhill** [comment]
Chat button does nothing when uBO is disabled. What am I supposed to see happening when I click the chat button?
