### ISSUE TITLE
Add phishing site 4funbox.com to filter list

### ISSUE THREAD

**Issue by akostem** [uBlockOrigin/uAssets#17684]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Add phishing site to filter list. The site portrays itself as terabox, seemingly a file hosting service. 

### URL(s) where the issue occurs.

`https://www.4funbox.com`
`4funbox.com`

### uBO version

1.49.0

### Browser name and version

Vivaldi

### Settings

nothing

**Comment by gorhill** [comment]
Ok reverted. I am going to let others debate the issue.

**Comment by akostem** [comment]
What originally set of the alarm was the insistence that I need to install an app to download a file I received, and then I saw the strange domain. I do not know if that also happens on terabox.com.
A also did a practical test to try and differentiate the sites: uploading a file to share (the intended functionality) on terabox.com works, but fails on 4funbox.com.
