### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by cpamafote** [uBlockOrigin/uAssets#17682]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=oXrfiOG14LE`

### Category

ads

### Description

j'ai de la pub 
alors qu'hier je n'en avais pas
j'utilise ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 108802
 cosmetic: 48754
 scriptlet: 17860
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  FRA-0: 28700-31, 19h.35m
  easylist: 65032-74, 19h.38m
  easyprivacy: 30856-1482, 3d.20h.14m
  plowe-0: 3748-964, 4d.22h.59m
  ublock-abuse: 70-1, 14h.35m
  ublock-badware: 6784-136, 19h.37m
  ublock-filters: 33862-192, 19h.36m
  ublock-privacy: 316-3, 14h.35m
  ublock-quick-fixes: 186-22, 19h.33m
  ublock-unbreak: 1986-49, 19h.34m
  urlhaus-1: 7056-0, 19h.32m
filterset (user): [empty]
trustedset: 
 added: [array of 26 redacted]
 removed: 
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
switchRuleset: 
 added: [array of 2 redacted]
hostRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 12450 ms (selfie)
 maxAssetCacheWait: 5 ms
popupPanel: 
 blocked: 0
 no-popups: true
```
</details>

**Comment by mapx-** [comment]
see https://github.com/easylist/easylist/wiki/Youtube-Issues
duplicate #7636

**Comment by cpamafote** [comment]
thank you
