### ISSUE TITLE
mangaesp.co: detection

### ISSUE THREAD

**Issue by Bernoul** [uBlockOrigin/uAssets#17680]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mangaesp.co/`

### Category

detection

### Description

It was fixed a few hours ago but once again it detected the ad blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/131319710/233270993-b92c542b-fb1f-4e09-aaf8-9e7377448bf2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 112
filterset (summary): 
  network: 92832
  cosmetic: 45694
  scriptlet: 18067
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 109-6, never
    easylist: 65453-44, 6m
    easyprivacy: 30880-1180, 6m
    plowe-0: 3748-940, 6m
    spa-0: 3618-10, 6m
    spa-1: 5186-200, 6m
    ublock-abuse: 70-0, 6m
    ublock-badware: 6804-120, 6m
    ublock-filters: 33879-138, 6m
    ublock-privacy: 316-3, 6m
    ublock-quick-fixes: 188-22, 6m
    ublock-unbreak: 1989-47, 6m
    urlhaus-1: 7239-0, 6m
filterset (user): [array of 111 redacted]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 171 ms (selfie)
  maxAssetCacheWait: 66 ms
popupPanel: 
  blocked: 17
  blockedDetails: 
    a-ads.com: 1
    achcdn.com: 1
    arc.io: 1
    clearonclick.com: 1
    disqus.com: 2
    google-analytics.com: 1
    googlesyndication.com: 3
    googletagmanager.com: 1
    narrative.io: 1
    pippio.com: 1
    rezync.com: 1
    sentry-cdn.com: 1
    viglink.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
You can continue commenting in the old thread. We all get notified with new comments.

**Comment by Bernoul** [comment]
I close this and comment on the past report? or I leave it open, sorry for the inconvenience.

**Comment by stephenhawk8054** [comment]
Just comment on the old report.

**Comment by stephenhawk8054** [comment]
It's fixed btw. You might need to wait for about 10 minutes before force updating the filter lists.
