### ISSUE TITLE
alphaporno.com [NSFW][ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1768]
URL(s) where the issue occurs

`http://www.alphaporno.com/videos/my-favorite-next-door-milfs-from-europe-ria-riona-and-alex5/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.18

Settings

Default

**Comment by mapx-** [comment]
I remember you to report the popups too !
