### ISSUE TITLE
medistore.at: breakage

### ISSUE THREAD

**Issue by ExteriorCloth20** [uBlockOrigin/uAssets#17694]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.medistore.at/`

### Category

breakage

### Description

I believe page breakage is caused by EasyList Cookie and Fanboy’s Annoyance. They both use filter "##.consent_box" which blocks cookie popup but overlay is still there

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 206144
  cosmetic: 225250
  scriptlet: 39287
  html: 1116
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 70420-5509, 5h.10m
    adguard-mobile: 8680-98, 5h.9m
    adguard-spyware-url: 1000-5, 5h.7m
    block-lan: 47-0, 4d.6h.48m
    curben-phishing: 74265-33, 1h.17m
    curben-pup: 194-0, 1h.16m
    adguard-annoyance: 67471-5086, 5h.5m
    adguard-social: 20316-836, 5h.4m
    fanboy-annoyance: 79299-67602, 4d.6h.47m
    fanboy-cookiemonster: 46724-241, 4d.6h.47m
    fanboy-social: 18995-2, 5h.3m
    ublock-annoyances: 4915-4, 5h.2m
    dpollock-0: 11354-499, 4d.6h.47m
  default: 
    user-filters: 1-0, never
    ublock-filters: 34782-79, 5h.15m
    ublock-badware: 6817-0, 5h.14m
    ublock-privacy: 371-0, 5h.13m
    ublock-abuse: 70-0, 5h.12m
    ublock-unbreak: 2000-5, 5h.11m
    ublock-quick-fixes: 187-0, 1h.19m
    easylist: 65257-875, 5h.8m
    easyprivacy: 30873-1871, 5h.6m
    urlhaus-1: 7107-0, 1h.18m
    plowe-0: 3749-4, 4d.6h.47m
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 359 ms (selfie)
  maxAssetCacheWait: 207 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/dbfa27b8f2f81b85ee21fb80252d31f678d37a1c
