### ISSUE TITLE
Twitch video ads aren't blocked.

### ISSUE THREAD

**Issue by darkhog** [uBlockOrigin/uAssets#17691]
### Prerequisites

- [x] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Twitch plays video ads despite the extension being active, enabled and updated.

### URL(s) where the issue occurs.

https://www.twitch.tv/

### uBO version

1.48.4

### Browser name and version

Firefox 112.0.1

### Settings

N/A since it happens with default settings on a brand new browser profile as well.

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
