### ISSUE TITLE
kriptoup.com: detection

### ISSUE THREAD

**Issue by uuqqzz** [uBlockOrigin/uAssets#17699]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [ ] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kriptoup.com/`

### Category

detection

### Description

adblocker detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/233502891-4ba6c6c5-a88a-4a17-895c-02f09f95cc27.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 132097
  cosmetic: 160926
  scriptlet: 36139
  html: 952
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 43760-4890, 12m
    adguard-generic: 70454-6249, 12m
    adguard-spyware-url: 1000-5, 12m
    adguard-annoyance: 67478-1523, 12m
    adguard-social: 20323-33, 12m
  default: 
    user-filters: 63-0, never
    ublock-filters: 34817-112, 12m
    ublock-badware: 6822-0, 12m
    ublock-privacy: 370-0, 12m
    ublock-abuse: 70-0, 12m
    ublock-unbreak: 1999-5, 12m
    ublock-quick-fixes: 203-0, 12m
    easylist: 65455-381, 12m
    easyprivacy: 30880-12382, 12m
    TUR-0: 12277-11, 12m
filterset (user): [array of 65 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1637 ms
  maxAssetCacheWait: 986 ms
  unsuspendAfter: 156 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    coinzillatag.com: 3
    ctengine.io: 2
    googlesyndication.com: 2
    googletagmanager.com: 2
```
</details>

**Comment by gorhill** [comment]
To be added to AdGuard Turkey:

    @@||kriptoup.com^$ghide

cc @Yuki2718

**Comment by stephenhawk8054** [comment]
I think this can be used so we don't need to unhide generic filters

```adb
kriptoup.com##+js(set, tie.ad_blocker_detector, '')
```

This filter is also used for other sites with same behavior in our list.
