### ISSUE TITLE
today.line.me: breakage

### ISSUE THREAD

**Issue by kclonline** [uBlockOrigin/uAssets#17697]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://today.line.me/tw/v2/article/grrvVZ`

### Category

breakage

### Description

video not playing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 107097
 cosmetic: 50281
 scriptlet: 17907
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  CHN-0: 27603-107, now
  easylist: 65455-100, now
  easyprivacy: 30880-1199, now
  plowe-0: 3748-942, now
  ublock-abuse: 70-0, now
  ublock-badware: 6818-120, now
  ublock-filters: 33935-117, now
  ublock-privacy: 320-3, now
  ublock-quick-fixes: 204-34, now
  ublock-unbreak: 1988-46, now
  urlhaus-1: 7107-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1862 ms
 maxAssetCacheWait: 20 ms
popupPanel: 
 blocked: 6
 network: 
  doubleclick.net: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  line-apps.com: 1
  line-scdn.net: 1
```
</details>

**Comment by gorhill** [comment]
I tried with a Hong Kong IP address and there is still a geo block.

**Comment by kclonline** [comment]
Sorry, I didn't expect this to be region-restricted.
This is a website from Taiwan, and it may be necessary to use a Taiwan IP to reproduce the problem.

**Comment by kclonline** [comment]
> I tried with a Hong Kong IP address and there is still a geo block.

Sorry, I didn't expect this to be region-restricted.
This is a website from Taiwan, and it may be necessary to use a Taiwan IP to reproduce the problem.

![2023-04-21_06-58-20](https://user-images.githubusercontent.com/9413950/233504915-d72d5978-3f66-4639-a855-26cbf6198c32.png)
Add screenshots.
After the video is clicked to play, it appears that it keeps spinning and cannot be played.
However, after the entire website is set as an exception filter, it can be played normally.

**Comment by gorhill** [comment]
Can you share the output of the logger when the player is broken?

- Open the logger
- Force a reload of the page
- Filter the logger output by selecting _blocked_ and _allowed_
- Copy the output of the logger by clicking the clipboard icon

It's likely only a single blocked network request is causing this.

**Comment by kclonline** [comment]
This is the blocked list
<details><summary>Logger output</summary>

```
+1
google-analytics_analytics.js
<<
today.line.me
3
get
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics_analytics.js:5
--
today.line.me
3
get
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com^
--
today.line.me
3
get
script
https://www.google-analytics.com/analytics.js
```
```
+1
/torimochi.js
--
today.line.me
3
get
script
https://d.line-scdn.net/n/_4/torimochi.js/public/v1/release/stable/min/torimochi.js
```
```
+0
noop.txt
<<
today.line.me
3
get
xhr
https://securepubads.g.doubleclick.net/pagead/ppub_config?ippd=today.line.me
```
```
+0
||doubleclick.net^$xhr,redirect-rule=noop.txt
--
today.line.me
3
get
xhr
https://securepubads.g.doubleclick.net/pagead/ppub_config?ippd=today.line.me
```
```
+0
||doubleclick.net^
--
today.line.me
3
get
xhr
https://securepubads.g.doubleclick.net/pagead/ppub_config?ippd=today.line.me
```
```
+0
||doubleclick.net^
--
today.line.me
3
get
script
https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202304190101/pubads_impl.js?cb=31074054
```
```
+0
googletagmanager_gtm.js
<<
today.line.me
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-MNP6F8L
```
```
+0
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
today.line.me
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-MNP6F8L
```
```
+0
||googletagmanager.com^
--
today.line.me
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-MNP6F8L
```
```
+0
https://today.line.me/tw/v2/article/grrvVZ
```
</details>

If any of these two are allowed, it can be played normally.

https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202304190101/pubads_impl.js?cb=31074054

https://securepubads.g.doubleclick.net/pagead/ppub_config?ippd=today.line.me

**Comment by kclonline** [comment]
> Can you share the output of the logger when the player is broken?
> 
> * Open the logger
> * Force a reload of the page
> * Filter the logger output by selecting _blocked_ and _allowed_
> * Copy the output of the logger by clicking the clipboard icon
> 
> It's likely only a single blocked network request is causing this.

This is the blocked list
<details><summary>Logger output</summary>

```
+1
google-analytics_analytics.js
<<
today.line.me
3
get
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics_analytics.js:5
--
today.line.me
3
get
script
https://www.google-analytics.com/analytics.js
```
```
+1
||google-analytics.com^
--
today.line.me
3
get
script
https://www.google-analytics.com/analytics.js
```
```
+1
/torimochi.js
--
today.line.me
3
get
script
https://d.line-scdn.net/n/_4/torimochi.js/public/v1/release/stable/min/torimochi.js
```
```
+0
noop.txt
<<
today.line.me
3
get
xhr
https://securepubads.g.doubleclick.net/pagead/ppub_config?ippd=today.line.me
```
```
+0
||doubleclick.net^$xhr,redirect-rule=noop.txt
--
today.line.me
3
get
xhr
https://securepubads.g.doubleclick.net/pagead/ppub_config?ippd=today.line.me
```
```
+0
||doubleclick.net^
--
today.line.me
3
get
xhr
https://securepubads.g.doubleclick.net/pagead/ppub_config?ippd=today.line.me
```
```
+0
||doubleclick.net^
--
today.line.me
3
get
script
https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202304190101/pubads_impl.js?cb=31074054
```
```
+0
googletagmanager_gtm.js
<<
today.line.me
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-MNP6F8L
```
```
+0
||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager_gtm.js:5
--
today.line.me
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-MNP6F8L
```
```
+0
||googletagmanager.com^
--
today.line.me
3
get
script
https://www.googletagmanager.com/gtm.js?id=GTM-MNP6F8L
```
```
+0
https://today.line.me/tw/v2/article/grrvVZ
```
</details>

If any of these two are allowed, it can be played normally.

https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202304190101/pubads_impl.js?cb=31074054

https://securepubads.g.doubleclick.net/pagead/ppub_config?ippd=today.line.me

**Comment by stephenhawk8054** [comment]
Does this filter work?

```adb
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=today.line.me
```

**Comment by kclonline** [comment]
> Does this filter work?
> 
> ```
> @@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=today.line.me
> ```

Yes, after all, it is also possible not to filter this item.
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202304190101/pubads_impl.js?cb=31074054$script,domain=today.line.me

**Comment by stephenhawk8054** [comment]
I can reproduce the issue using Taiwan IP and `@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=today.line.me` works for me.
