### ISSUE TITLE
sosyalbook.com: detection

### ISSUE THREAD

**Issue by uuqqzz** [uBlockOrigin/uAssets#17698]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [ ] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sosyalbook.com/`

### Category

detection

### Description

![resim](https://user-images.githubusercontent.com/110184059/233501195-dbecc93a-abca-4a64-86ab-11c39e08274d.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/233500998-751a1de5-7698-486a-9b6a-1db3a7d3c86f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 131904
  cosmetic: 160791
  scriptlet: 36115
  html: 952
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 43755-4759, 18h.9m
    adguard-generic: 70350-1811, 18h.9m
    adguard-spyware-url: 996-6, 18h.9m
    adguard-annoyance: 67451-317, 18h.9m
    adguard-social: 20306-860, 18h.9m
  default: 
    user-filters: 63-0, never
    ublock-filters: 34760-4201, 18h.9m
    ublock-badware: 6808-0, 18h.9m
    ublock-privacy: 366-59, 18h.9m
    ublock-abuse: 70-0, 18h.9m
    ublock-unbreak: 2001-63, 18h.9m
    ublock-quick-fixes: 187-4, 18h.9m
    easylist: 65313-1070, 18h.9m
    easyprivacy: 30873-12377, 18h.9m
    TUR-0: 12275-21, 18h.9m
filterset (user): [array of 65 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3434 ms
  maxAssetCacheWait: 2407 ms
  unsuspendAfter: 377 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    sosyalbook.com: 3
    googlesyndication.com: 2
```
</details>

**Comment by gorhill** [comment]
Should be fixed in AdGuard Turkey:

    @@||sosyalbook.com^$ghide
    sosyalbook.com##.adsbygoogle:style(max-height:1px!important)

**Comment by stephenhawk8054** [comment]
@Yuki2718

**Comment by gorhill** [comment]
So as per other similar issue, this works:

    sosyalbook.com##+js(set, tie.ad_blocker_detector, '')

**Comment by gorhill** [comment]
I don't see any instance of `ad_blocker_detector` in AdGuard Turkey. Does AdGuard's lists has a policy against bypassing anti-blockers? If so, we will just add the filters to our lists.

**Comment by stephenhawk8054** [comment]
Adguard Turkey has `tgyama.com##+js(set-constant, tie.ad_blocker_disallow_images_placeholder, undefined)`, but I'm not sure about `ad_blocker_detector`. I think we can add to our list first until Yuki can give more insights.

**Comment by gorhill** [comment]
> I think we can add to our list first until Yuki can give more insights.

Ok let's do this. I will let you add these to avoid conflict.

**Comment by stephenhawk8054** [comment]
Ok will do.

**Comment by Yuki2718** [comment]
> I don't see any instance of `ad_blocker_detector` in AdGuard Turkey.

It is in Base filter. They address popular anti-block plugins in Base regardless of language, so we have to add the rule to our own. Same goes to #17699.

**Comment by stephenhawk8054** [comment]
Maybe we can merge these `tie` anti-adb to 1 entry for convenience/bandwidth like chp?
