### ISSUE TITLE
seattlepi.com: breakage

### ISSUE THREAD

**Issue by regan-karlewicz** [uBlockOrigin/uAssets#17696]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello, yesterday I opened #17669. A commit was made to the EasyList and the issue was marked as resolved, but the problem persists with the updates.

I noticed the classes are now changed to what is in this commit: https://github.com/easylist/easylist/commit/33a181a92cbc34ca783b93563c2fee653677fe27

The original issue in #17669 persists with the changes in the above commit.

The targeted class names are border and padding classes (`b-gray300` `pt40` and `bt` which are classes for border color, padding top 40px, and border top respectively). Many elements that are not ads contained on this site could contain these classnames and therefore be blocked. 

A better way to select ad divs on this site may be to select elements with a `data-block-type="ad"` attribute, since all ad containers on the page have this data attribute. 

For example in EasyList syntax:

```
seattlepi.com##div[data-block-type="ad"]
```

### URL(s) where the issue occurs.

`https://www.seattlepi.com/shopping/article/how-to-organize-outdoor-gear-17864916.php`

### Screenshot(s)

uBlock enabled (missing masthead):
https://user-images.githubusercontent.com/1987265/233160112-a0f6a95f-fff2-4788-a452-f4d3e61b7ad3.png

uBlock disabled:
https://user-images.githubusercontent.com/1987265/233160133-6c7d70e2-17b0-44b4-a8e3-3dbf5045fe15.png

### uBO version

1.49.0

### Browser name and version

Chrome 112.0.5615.121

### Settings

All default

**Comment by gorhill** [comment]
What is the breakage? I can't tell. If it's the hamburger menu, I can see it fine with latest filter lists.

**Comment by stephenhawk8054** [comment]
This site was fixed recently in EL if I remember correctly. Force update all your filter lists (click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.

**Comment by regan-karlewicz** [comment]
Hi, I think there might be some confusion here because the home page and section fronts is on a 50/50 A/B test with a legacy stack, which does not have the issue.

However, the article pages are 100% cutover to the new stack, and the problem should always be visible on these pages. See attached video for result of turning uBlock on and off

https://user-images.githubusercontent.com/1987265/233679115-1942b249-ff66-40f3-b94e-fcc98c1a22b6.mov

URL of page in video: https://www.seattlepi.com/news/politics/article/more-say-trump-broke-law-in-ga-case-than-ny-s-17907681.php

I've verified that the updated class selectors from https://github.com/easylist/easylist/commit/33a181a92cbc34ca783b93563c2fee653677fe27 are in use during the video

**Comment by mapx-** [comment]
I tested your page, it's all fine on my end, masthead still visible

- force again updating all the filter lists
- cosmetic filters in action on my side:
![image](https://user-images.githubusercontent.com/10303732/233687187-716f5352-1162-46ee-a634-d45a6c49d1c2.png)

**Comment by regan-karlewicz** [comment]
@mapx- Looks like my cache had old data in it. Clearing the filter list cache resolved the issue. Closing.
