### ISSUE TITLE
gadgets360.com 

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#177]
Anti adb warning on articles on http://hi.gadgets360.com/.

**Error URL:** http://hi.gadgets360.com/news/facebook-now-lets-you-order-food-book-movies-with-friends-help-hindi-news-1477120

Not facing any issue with the English website http://gadgets.ndtv.com/

**Comment by gotitbro** [comment]
**Edit:** Warning is displayed gadgets.ndtv.com too but the warning image gets blocked by this filter `ndtv.com###ndtv-message-users` in **uBlock filters**.

So essentially no content is displayed.

**URL:** http://gadgets.ndtv.com/apps/news/whatsapp-for-android-starts-getting-video-calling-feature-1478751?pfrom=home-indepth (No content in the article will be displayed)

**Comment by gotitbro** [comment]
@gorhill were you able to reproduce this, can this be fixed?

**Comment by IDKwhattoputhere** [comment]
Try `@@||cdn.gadgets360.com/assets/google_zedo__ruby.js$script,first-party` and report back.

**Comment by gotitbro** [comment]
@IDKwhattoputhere That works for  http://hi.gadgets360.com/ but not not on gadgets.ndtv.com

**Comment by IDKwhattoputhere** [comment]
Then use these instead:
```
@@||cdn.gadgets360.com/assets/google_zedo__ruby.js$script
ndtv.com#@##ndtv-message-users
```

**Comment by gotitbro** [comment]
This `ndtv.com#@##ndtv-message-users` just whitelists the anti adb message image, can't access the content beyond this warning.

**Comment by IDKwhattoputhere** [comment]
Did you use both filters? Works fine here.
![](https://cloud.githubusercontent.com/assets/16030872/19739922/0f81d0a8-9bbd-11e6-8a77-1701f21d745f.png)

**Comment by gotitbro** [comment]
@IDKwhattoputhere You're this filter: `@@||cdn.gadgets360.com/assets/google_zedo__ruby.js$script`
works forgot remove the `first-party` type from the filter, no need for `ndtv.com#@##ndtv-message-users` this either.

This works filter: `@@||gadgets360.com/*ad$script` also works (thanks @**intense**)
