### ISSUE TITLE
rockmods.net: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#17709]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.rockmods.net/2022/01/Ninjagram.html`

### Category

detection

### Description

detection

### Screenshot(s)

https://user-images.githubusercontent.com/50231020/233697521-ecebb364-2348-4a15-bf68-5c68f002893a.png

`https://www.rockmods.net/2022/01/Ninjagram.html`

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 128083
 cosmetic: 103928
 scriptlet: 21134
 html: 0
listset (total-discarded, last-updated): 
 added: 
  RUS-0: 39711-154, 4h.18m
  fanboy-cookiemonster: 46797-216, 4h.18m
 default: 
  user-filters: 0-0, never
  FRA-0: 19935-16, 4h.18m
  easylist: 65465-200, 4h.18m
  easyprivacy: 30880-1574, 4h.18m
  plowe-0: 3746-968, 4h.18m
  ublock-abuse: 70-2, 4h.18m
  ublock-badware: 6828-138, 4h.18m
  ublock-filters: 33946-213, 4h.18m
  ublock-privacy: 320-3, 4h.18m
  ublock-quick-fixes: 205-34, 4h.18m
  ublock-unbreak: 1989-46, 4h.18m
  urlhaus-1: 7056-1, 4h.18m
filterset (user): [empty]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 611 ms (selfie)
 maxAssetCacheWait: 116 ms
popupPanel: 
 blocked: 4
 network: 
  rockmods.net: 2
  google.com: 2
 cosmetic: 
  ##ins.adsbygoogle
  ###xx0o-cookie
  ###cookies.cookies
```
</details>

**Comment by peace2000** [comment]
Can't repriduce, please update your all filter lists.

**Comment by gorhill** [comment]
Can't reproduce either.

I could reproduce as soon as I enabled ABP.

@x-R0b0T-x, did you really ensure that you are _"not using uBlock Origin (uBO) along with other content blocker extensions"_?

**Comment by dportvine** [comment]
I have adblock detection on the **Alternate Link**
`https://www.rockmods.net/2021/02/Mimo.html`
[Gif](https://imgur.com/X0kR7di)

**Comment by stephenhawk8054** [comment]
> ` https://www.rockmods.net/2021/02/Mimo.html`

I can't reproduce with alternate link either. Video: https://user-images.githubusercontent.com/66517106/233754348-087740a5-35aa-48af-bf2d-cfe94837745d.mp4

**Comment by dportvine** [comment]
>I can't reproduce with alternate link either.

[Gif](https://imgur.com/CbfyPFi)
<details>
<summary>Screen</summary>

![2023-04-22_091833](https://user-images.githubusercontent.com/111344219/233767315-07e97d5d-9c52-426f-83c9-ea584ac6c594.png)
![2023-04-22_091833](https://user-images.githubusercontent.com/111344219/233767493-0846d715-9070-4d20-8f22-3801cda55319.png)
</details>

On my side, 'adblock detected' with this rule `thecubexguide.com##iframe`.

**Comment by mapx-** [comment]
@dportvine 
test

```
*$frame,domain=thecubexguide.com,redirect=noopframe
thecubexguide.com#@#iframe
thecubexguide.com##iframe:style(height: 10px !important)
```

**Comment by dportvine** [comment]
Works for me.

<details>
<summary>Screen</summary>

![2023-04-22_095709](https://user-images.githubusercontent.com/111344219/233768287-32903a15-5574-40fa-a258-cda9fd4d38e2.png)
</details>

**Comment by dportvine** [comment]
@mapx- 
Works for me without leftovers. [Gif](https://imgur.com/zyfOdZH)

```adb
*$frame,domain=thecubexguide.com,redirect=noopframe
thecubexguide.com#@#iframe
thecubexguide.com##iframe:style(height: 0px !important)
thecubexguide.com##[class^="stickyads"]:remove()
```

**Comment by mapx-** [comment]
> Bunch Of Useless Rules For djxmaza.in

which ones ?

**Comment by mapx-** [comment]
Are you talking about all `+js` (scriptlets) filters ? It's so difficult to indicate exactly which ones ?

**Comment by advertblocker** [comment]
> Are you talking about all `+js` (scriptlets) filters ? It's so difficult to indicate exactly which ones ?

they are on mobile apparently

**Comment by advertblocker** [comment]
anyway @mapx- the site uses cosmetic bait apparently

**Comment by stephenhawk8054** [comment]
`disable-newtab-links` prevents opening the ads when clicking on it. Does it really cause anti-adb on your side?

**Comment by mapx-** [comment]
add

`@@||googlesyndication.com^$xhr,script,domain=thecubexguide.com`

**Comment by mapx-** [comment]
just use it as custom filter

**Comment by stephenhawk8054** [comment]
> Yet, it would be useful to many people, I think...

They will intervene whatever added to the main lists.

**Comment by krystian3w** [comment]
Maybe works address in "RU AdList: Counters" for East Europe/North Asia.

**Comment by mapx-** [comment]
I cannot reproduce that detection
