### ISSUE TITLE
rohlik.cz login modal won't open

### ISSUE THREAD

**Issue by demoklion** [uBlockOrigin/uAssets#17703]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`https://www.rohlik.cz/vitejte`

1. have Arc, open the website
2. click top right green button (Účet, that's Account in Czech). should open modal for login info, it does in Firefox with uBlock. does nothing in Arc.

turning uBlock off in Arc for this website fixes the issue.

### URL(s) where the issue occurs.

`https://www.rohlik.cz/vitejte`

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 89707
 cosmetic: 39947
 scriptlet: 17735
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65033-44, 2d.17h.8m
  easyprivacy: 30863-1176, 2d.17h.4m
  plowe-0: 3750-938, 10d.15h.24m
  ublock-abuse: 78-0, 11d.13h.59m
  ublock-badware: 6727-117, 2d.17h.6m
  ublock-filters: 33829-101, 2d.17h.7m
  ublock-privacy: 302-2, 11d.13h.35m
  ublock-quick-fixes: 204-20, 15m
  ublock-unbreak: 1989-45, 2d.17h.5m
  urlhaus-1: 7230-1, 15m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 149 ms (selfie)
 maxAssetCacheWait: 49 ms
```
</details>

**Comment by mapx-** [comment]
- working in chrome too, ARC is chromium-based
- you have to investigate on your side, I don't even see how to download arc for windows.

**Comment by krystian3w** [comment]
You'd have to hack their servers to make an earlier own compilation, because there probably isn't even a ready-made alpha release for Windows that they would test in their company.
