### ISSUE TITLE
fcportables.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1770]
URL(s) where the issue occurs

`http://www.fcportables.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.18

Settings

Default

**Comment by mapx-** [comment]
`@@||fcportables.com/*ad$script,xmlhttprequest,domain=fcportables.com,first-party`
or
only FF:
`fcportables.com##^script:has-text(ai_debugging)`
or
`||fcportables.com^$inline-script`

**Comment by KiLL4FuNK** [comment]
It works perfect    `||fcportables.com^$inline-script`

**Comment by x-R0b0T-x** [comment]
On this page (and the entire site) https://www.fcportables.com/, an insert appears stating that the site has detected an ad blocker.

<img width="301" height="162" alt="Image" src="https://github.com/user-attachments/assets/515ab18d-754c-434e-a6e3-5092ad60c8e4">

I had to enter rules myself to avoid this overlay.
But I think you are better equipped to fix this more cleanly:

<img width="653" height="329" alt="Image" src="https://github.com/user-attachments/assets/656a5f33-6a7c-4a4a-8c8b-015a84b6541f">

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBOL and its default settings.
