### ISSUE TITLE
tastebuds.fm: breakage

### ISSUE THREAD

**Issue by overtinkering** [uBlockOrigin/uAssets#17705]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tastebuds.fm/users/Litt66`
or any other user. I guess you could write it like this: `https://tastebuds.fm/users/*`

### Category

breakage

### Description

`https://tastebuds.fm/users/Litt66`
or any other user profile page.
The Like button dissappears, rendering the whole site pointless.(you can only chat with users mutually liked)
Disabling cosmetic filtering works as a workaround.
If the problem can't or shouldn't be fixed on uBlock side, I'm happy to make an informed request to Tastebuds developers.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 208947
  cosmetic: 229463
  scriptlet: 39580
  html: 1114
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 70482-5523, 3m
    adguard-mobile: 8686-98, 3m
    adguard-spyware-url: 1000-5, 3m
    block-lan: 47-0, 3m
    curben-phishing: 74766-33, 3m
    curben-pup: 194-0, 3m
    adguard-annoyance: 67469-6826, 3m
    adguard-social: 20326-838, 3m
    fanboy-thirdparty_social: 69-0, 3m
    fanboy-annoyance: 77717-65845, 3m
    fanboy-cookiemonster: 46797-242, 3m
    fanboy-social: 18837-17, 3m
    ublock-annoyances: 4918-4, 3m
    dpollock-0: 11355-500, 3m
    spa-0: 3618-3, 3m
    spa-1: 5188-147, never
  default: 
    user-filters: 0-0, never
    ublock-filters: 34746-110, 2d.6h.8m
    ublock-badware: 6788-0, 2d.6h.7m
    ublock-privacy: 344-0, 10d.9h.36m
    ublock-abuse: 78-0, 10d.9h.35m
    ublock-unbreak: 1997-5, 2d.6h.6m
    ublock-quick-fixes: 203-0, 22h.3m
    easylist: 65067-871, 2d.6h.5m
    easyprivacy: 30862-1885, 2d.6h.4m
    urlhaus-1: 7107-0, 22h.2m
    plowe-0: 3750-2, 10d.9h.29m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1788 ms (selfie)
  maxAssetCacheWait: 133 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    d1l6p2sc9645hc.cloudfront.net: 1
    facebook.net: 1
    google-analytics.com: 1
    googletagservices.com: 1
    pusher.com: 1
```
</details>

**Comment by mapx-** [comment]
Are you talking about buttons bellow or it's other button if you have an account ?

![image](https://user-images.githubusercontent.com/10303732/233643251-62dc1b79-8b37-43c2-aab0-24b2da977742.png)

**Comment by mapx-** [comment]
I guess this should fix the issue, just test it (add it in "my filters", refresh the page)

`tastebuds.fm#@#.likeButton`

 FA issue, @ryanbr
