### ISSUE TITLE
github.com/shopify/tracky: breakage

### ISSUE THREAD

**Issue by winston-yallow** [uBlockOrigin/uAssets#17706]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The button to star a repo does not work. Browser console says the web request is blocked by uBlock Origin.
![20230421_14h29m32s_grim](https://user-images.githubusercontent.com/44872771/233636015-40f22561-04fe-4f71-acd8-8222f6c021be.png)

### URL(s) where the issue occurs.

Click the star button on this page:
`https://github.com/shopify/tracky`
It will trigger the POST request to
`https://github.com/Shopify/tracky/star`
which is blocked

### uBO version

1.48.4

### Browser name and version

Firefox 112.0 (64-bit)

### Settings

none

**Comment by stephenhawk8054** [comment]
It's caused by `/shopify/track` in EP

@ryanbr
