### ISSUE TITLE
thingiverse.com: detection

### ISSUE THREAD

**Issue by Gona2119** [uBlockOrigin/uAssets#17704]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.thingiverse.com/`

### Category

detection

### Description

I am downloading the models slowly beacuse thingiverse detects uBlockOrigin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ababaas](https://user-images.githubusercontent.com/93960734/233543997-d7904d3f-d9bc-4ac6-9533-649f20b40e30.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated): [none]
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 6 redacted]
switchRuleset: 
 added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 84 ms (selfie)
 maxAssetCacheWait: 10 ms
popupPanel: 
 blocked: 0
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
```
</details>

**Comment by stephenhawk8054** [comment]
Your extension is broken. Can you force update all your filter lists (click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

**Comment by Suros** [comment]
Ad detection appears to be back. Probably related to their recent acquisition.

**Comment by stephenhawk8054** [comment]
Please screenshot how the ads look like.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3d6ca0ca5ba914f62e7445c5837aaf4b852a64d3

**Comment by Suros** [comment]
Sorry, I found the default config button and that got it in order. Disregard, and sorry to waste your time.

**Comment by playonevideo** [comment]
On `https://www.thingiverse.com/thing:7338482` there is an ad leftover on top of the page, while using Firefox for Android:

https://github.com/user-attachments/assets/a0e13a59-8ed4-45cd-9dab-b5928aee06c9

**Comment by BlazeFTL** [comment]
```
thingiverse.com##[class^="AdBanner__adBanner--"]
