### ISSUE TITLE
manhwatop.com: popups

### ISSUE THREAD

**Issue by Resubmit6903** [uBlockOrigin/uAssets#17700]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://manhwatop.com/user-settings/`

### Category

popups

### Description

Popups open in a new browser page on Chrome when click on the site, or pressing crtl+f once the site loads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 90125
 cosmetic: 39982
 scriptlet: 17775
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65455-44, 10m
  easyprivacy: 30880-1180, 10m
  plowe-0: 3748-940, 10m
  ublock-abuse: 70-0, 10m
  ublock-badware: 6818-120, 10m
  ublock-filters: 33935-102, 10m
  ublock-privacy: 320-3, 10m
  ublock-quick-fixes: 204-34, 10m
  ublock-unbreak: 1988-45, 10m
  urlhaus-1: 7107-0, 10m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 598 ms
 maxAssetCacheWait: 6 ms
popupPanel: 
 blocked: 9
 network: 
  manhwatop.com: 1
  adsco.re: 1
  blockadsnot.com: 1
  cloudflareinsights.com: 1
  dnhfi5nn2dt67.cloudfront.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  protagcdn.com: 1
 cosmetic: 
  ##.c-ads
  ##.footer-ads
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce.

**Comment by Resubmit6903** [comment]
Have you tried reproducing it from the page https://manhwatop.com/user-settings
If you don't login to the site and browse around, open pages it is normal. It's once you go to the user settings page, the page loads, you click anywhere or do ctrl+f to search the page that you get popup pages.  Some pages open in a new window showing blocked by uOrigin some do not. I have adult website popups not being blocked.

**Comment by gorhill** [comment]
If I understand correctly, you say an account is needed, and being logged in is needed?

**Comment by Resubmit6903** [comment]
Yes that is correct. I did not try logging out to test it, but did after the unable to reproduce label.

**Comment by gorhill** [comment]
Force an update of _uBlock filters_  in ~10 minutes.
