### ISSUE TITLE
nivod4.tv: ads

### ISSUE THREAD

**Issue by ShunAn1231** [uBlockOrigin/uAssets#17716]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nivod4.tv/FOJrlPKD2bhmtEIrnnwzyuUo5L0onyZB-8-0-0-0-play.html?sc=84b781fc72e3a25ab772f40e5b6ceff5`

### Category

ads

### Description

adblocking not working, all ads including ads before video starts, theres a 15 seconds ad. also there are a few window ads below the video.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2023-04-22 at 12 14 32 PM](https://user-images.githubusercontent.com/67151466/233761850-c71f529c-2ea1-48c4-ad54-77b06714439c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 90113
 cosmetic: 39984
 scriptlet: 17783
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65453-44, 3m
  easyprivacy: 30880-1180, 2m
  plowe-0: 3746-940, 2m
  ublock-abuse: 70-0, 2m
  ublock-badware: 6832-120, 2m
  ublock-filters: 33974-131, 2m
  ublock-privacy: 320-3, 2m
  ublock-quick-fixes: 205-34, 2m
  ublock-unbreak: 1991-45, 2m
  urlhaus-1: 7082-1, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3090 ms
 maxAssetCacheWait: 131 ms
popupPanel: 
 blocked: 7
 network: 
  nivod4.tv: 2
  compoundchaise.com: 1
  google-analytics.com: 2
  googletagmanager.com: 2
 cosmetic: 
  ###adDiv
  ##.video-ad
```
</details>

**Comment by mapx-** [comment]
chinese page, enable `CHN: AdGuard Chinese`

**Comment by ShunAn1231** [comment]
> chinese page, enable `CHN: AdGuard Chinese`

i am sorry, but may i ask how should i enable this

**Comment by mapx-** [comment]
click uBO icon, last icon on the right side (at the bottom the gear icon - open the dashboard), "filter lists" tab, 
`Regions, languages` section, enable `CHN: AdGuard Chinese`
