### ISSUE TITLE
home.gamer.com.tw: detection

### ISSUE THREAD

**Issue by R-wild** [uBlockOrigin/uAssets#17719]
Prerequisites

    I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
    I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
    I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
    I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
    I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
    I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
    I am not using uBlock Origin (uBO) along with other content blocker extensions.
    I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
    I did not answer truthfully to ALL the above checkpoints.

URL address of the web page

`https://home.gamer.com.tw/creationDetail.php?sn=5701346`

Category

detection
Description

The website detects adblockers.
Screenshot(s)
Screenshot(s)
Configuration

uBlock Origin: 1.48.4
Firefox: 114
filterset (summary): 
  network: 105201
  cosmetic: 41333
  scriptlet: 17903
  html: 952
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt: 1846-1, 17h.41m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 7d.18h.28m
  default: 
    user-filters: 17-0, never
    ublock-filters: 34820-84, 17h.45m
    ublock-badware: 6827-0, 17h.44m
    ublock-privacy: 344-0, 7d.18h.25m
    ublock-abuse: 78-0, 7d.18h.24m
    ublock-unbreak: 2002-6, 17h.43m
    easylist: 65478-641, 17h.46m
    easyprivacy: 30880-1199, 17h.40m
    CHN-0: 17408-55, 17h.42m
    urlhaus-1: 7056-1, 17h.38m
    ublock-quick-fixes: 203-0, 17h.37m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1038 ms (selfie)
  maxAssetCacheWait: 318 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    google-analytics.com: 1
    google.com: 3
    googletagmanager.com: 1
    googletagservices.com: 1

**Comment by mapx-** [comment]
- reset uBO to default settings / filter lists
- update all your filter lists (after resetting uBO)
- disable any other blocking addons / plugins
- test again
- if still detection => provide a screenshot showing it

**Comment by R-wild** [comment]
problem solved after updating all filters.
