### ISSUE TITLE
the-mafia.net: ads

### ISSUE THREAD

**Issue by POISON2240** [uBlockOrigin/uAssets#17715]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://the-mafia.net/`

### Category

ads

### Description

> Рекламный баннер не блокируется 

**Advertising banner is not blocked**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.1b0
Chromium Mobile: 110
filterset (summary): 
 network: 108848
 cosmetic: 43554
 scriptlet: 19112
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  RUS-0: 39633-885, 1d.12h.56m
  adguard-mobile: 1949-12, 13h.58m
  easylist: 65453-16879, 15h.24m
  easyprivacy: 30880-1297, 13h.57m
  plowe-0: 3750-1028, 7d.17h.44m
  ublock-abuse: 78-1, 12d.5h.1m
  ublock-badware: 6807-121, 13h.56m
  ublock-filters: 34071-362, 3d.12h.58m
  ublock-privacy: 302-3, 7d.20h.12m
  ublock-quick-fixes: 204-22, 22h.59m
  ublock-unbreak: 1994-47, 3d.13h.16m
  urlhaus-1: 7230-1, 23h.51m
filterset (user): [empty]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1153 ms (selfie)
 maxAssetCacheWait: 339 ms
popupPanel: 
 blocked: 2
 network: 
  yandex.net: 2
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@mapx- 
Do you think this banner is a third party advertisement or an annoyance?

**Comment by POISON2240** [comment]
Добрый день. Баннер раздражает и не вписывается в оформление сайта.Good afternoon. The banner is annoying and does not fit into the design of the site. 22.04.2023, 12:09, "dimisa" ***@***.***>***@***.*** you think this banner is a third party advertisement or an annoyance?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>  __________________________ tel: +7-903-502-93-93__________________________С уважением Петрик Олег Игоревич

**Comment by mapx-** [comment]
at the very limit only an annoyance

**Comment by dimisa-RUAdList** [comment]
I added a rule to [BitBlock](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).

https://github.com/easylist/ruadlist/commit/0f547f0753db4a5e6932c3dd8510b53a0fefb2ed
