### ISSUE TITLE
dailymail.co.uk: notification popup

### ISSUE THREAD

**Issue by Procyon-b** [uBlockOrigin/uAssets#17713]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dailymail.co.uk/home/index.html`

### Category

[unknown]

### Description

I've visited this site while solving an issue for a user.
When first connecting (no cookie & local storage) the page displays a misleading notification popup (real notifications are disabled in this profile). It doesn't appear on page refresh, but there is a local storage variable with a timestamp associated with it, so they probably display the dialog again after some time.

Clicking "block" or "x" closes the popup, clicking "allow" starts the download of an external program from their server.

I don't know if this enough to block this in one of the stock lists.

I've tried defusing but it breaks many other things. (blocking inline script: `dailymail.co.uk##+js(acis, decodeURIComponent)`)

There are several possibilities to hide the dialog.

- Hide it regardless of other usage:
```
dailymail.co.uk##body > div:not([id]):not([class]):not([style]) > div:not([id]):not([class]):not([style])
```

- Hide based on the content:
```
dailymail.co.uk##body > div:not([id]):not([class]):not([style]) > div:not([id]):not([class]):not([style]) div[class^="permissions-"]:has-text(Show notifications):upward(div:not([class]))
```
But on my test profile, it still appears for a couple of seconds.

- There is the possibility to combine this filter with another one that hides the dialog while it's in a transitory state when the page loads (after, the previous sibling is not an iframe anymore):
```
dailymail.co.uk##body > iframe + div:not([id]):not([class]):not([style]) > div:not([id]):not([class]):not([style])
dailymail.co.uk##body > div:not([id]):not([class]):not([style]) > div:not([id]):not([class]):not([style]) div[class^="permissions-"]:has-text(Show notifications):upward(div:not([class]))
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![DM-notif](https://user-images.githubusercontent.com/40043075/233746891-1dc165eb-2ff1-473c-9aa0-64a0a9e16a38.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Chromium: 109
filterset (summary): 
  network: 112747
  cosmetic: 35434
  scriptlet: 21123
  html: 0
listset (total-discarded, last-updated): 
  added: 
    FRA-0: 28735-2982, 1h.25m
    NLD-0: 2582-37, 1h.25m
    block-lan: 47-0, 1h.25m
    fanboy-social: 18837-13020, 1h.25m
    ublock-annoyances: 4954-14, 1h.25m
  default: 
    user-filters: 20-0, never
    easylist: 65478-17000, 1h.25m
    easyprivacy: 30881-1487, 1h.25m
    plowe-0: 3746-963, 1h.25m
    ublock-abuse: 70-1, 1h.25m
    ublock-badware: 6832-138, 1h.25m
    ublock-filters: 33952-435, 1h.25m
    ublock-privacy: 320-4, 1h.25m
    ublock-quick-fixes: 205-34, 1h.25m
    ublock-unbreak: 1990-54, 1h.25m
    urlhaus-1: 7056-1, 1h.25m
filterset (user): [array of 20 redacted]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  showIconBadge: false
  suspendUntilListsAreLoaded: true
  tooltipsDisabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  popupFontSize: 13px
supportStats: 
  allReadyAfter: 2183 ms
  maxAssetCacheWait: 1011 ms
popupPanel: 
  blocked: 92
  blockedDetails: 
    dailymail.co.uk: 7
    3lift.com: 3
    adnxs.com: 7
    adsrvr.org: 1
    amazon-adsystem.com: 1
    casalemedia.com: 2
    criteo.com: 1
    criteo.net: 1
    ctfassets.net: 3
    dotmetrics.net: 1
    fireworkadservices1.com: 3
    fireworkapi1.com: 4
    fwpixel.com: 1
    go-mpulse.net: 2
    google.com: 6
    googletagmanager.com: 1
    googletagservices.com: 1
    id5-sync.com: 2
    imasdk.googleapis.com: 2
    indexww.com: 1
    openx.net: 3
    permutive.app: 1
    rubiconproject.com: 3
    sharethrough.com: 7
    skimresources.com: 1
    smartadserver.com: 15
    smartclip.net: 1
    yahoo.com: 11
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the notification. Does this work?

```adb
||hulkprod.anm.co.uk^
```

**Comment by Procyon-b** [comment]
No

![DM-notif-2](https://user-images.githubusercontent.com/40043075/233757841-40c6ae7d-2373-4cd1-9d1b-f041aabef35b.png)

**Comment by mapx-** [comment]
@Procyon-b could you test

`dailymail.co.uk##+js(aopr, Notification)`

**Comment by Procyon-b** [comment]
@mapx- you've nailed it !   :)
