### ISSUE TITLE
nationalreview.com: breakage

### ISSUE THREAD

**Issue by Anoneemouse** [uBlockOrigin/uAssets#17718]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When Ublock Origin is active, the top line of headlines is hidden on all National Review Online pages. When Ublock is turned off, the headline displays properly.

### URL(s) where the issue occurs.

`https://www.nationalreview.com/corner/trumps-pollster-finds-desantis-leading-biden-and-biden-leading-trump/`

### Screenshot(s)

https://user-images.githubusercontent.com/16356703/233764262-32765b5d-78e8-42df-85b0-008a4f7d0bfc.png

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 90162
 cosmetic: 40016
 scriptlet: 17770
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  easylist: 65496-44, 2m
  easyprivacy: 30881-1182, 2m
  plowe-0: 3746-939, 2m
  ublock-abuse: 70-0, 2m
  ublock-badware: 6832-120, 2m
  ublock-filters: 33971-103, 2m
  ublock-privacy: 320-3, 2m
  ublock-quick-fixes: 205-34, 2m
  ublock-unbreak: 1989-45, 2m
  urlhaus-1: 7082-1, 2m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2914 ms (selfie)
 maxAssetCacheWait: 642 ms
```
</details>

**Comment by ghajini** [comment]
can you show marked in.screenshot what is broken when ublock origin is on
without ublock origin how it looks?

**Comment by Anoneemouse** [comment]
I don't have an easy way to mark the page up, but using the same page I gave as an example here are screenshots of the top of the page with first ublock on, and then off.  Notice that with ublock on, the following is missing from the article (very small highlighted text links for "the corner" and "elections" plus the top line of the article headline):

[THE CORNER](https://www.nationalreview.com/corner/)
[ELECTIONS](https://www.nationalreview.com/elections/)
**Trump’s Pollster Finds DeSantis**

Here's the top of the page with ublock ON:

![image](https://user-images.githubusercontent.com/16356703/233766749-c3174333-ae88-4c81-a3ad-cfba9d0d07f8.png)

And here's the top of the same page with ublock turned OFF:

![image](https://user-images.githubusercontent.com/16356703/233766807-520dbf72-0673-4ffe-bde7-5989afb77e7f.png)

**Comment by mapx-** [comment]
add

```
nationalreview.com#@#.header-billboard-wrap
nationalreview.com##.ad-skeleton
```

**Comment by mapx-** [comment]
what is missing - see red arrows

![image](https://user-images.githubusercontent.com/10303732/233767727-540748c5-b76f-43e5-a6ce-9791a9d0f30b.png)

**Comment by Anoneemouse** [comment]
Yes, adding the two lines you suggested to "my filters" fixed it.  Thank you all!
