### ISSUE TITLE
writer tools: ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17711]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

```
https://www.plagiarismchecker.co/
https://plagiarismdetector.net/
https://searchenginereports.net/
```

### Category

ads

### Description

Grammarly ads, alike `https://smallseotools.com/` and `https://www.duplichecker.com/`
(some sites with Grammarly popup on cursor leaves page)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 81531
  cosmetic: 43064
  scriptlet: 21401
  html: 1118
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 18h.1m
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1552-0, 18h.2m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 1d.1h.39m
    ublock-annoyances: 4918-4, 1m
  default: 
    user-filters: 1686-13, never
    ublock-filters: 34862-146, 1m
    ublock-badware: 6837-0, 28m
    ublock-privacy: 370-0, 28m
    ublock-abuse: 70-0, 28m
    ublock-unbreak: 2001-4, 28m
    ublock-quick-fixes: 204-0, 28m
    easylist: 65478-199, 28m
    easyprivacy: 30881-2252, 28m
filterset (user): [array of 715 redacted]
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 343 ms (selfie)
  maxAssetCacheWait: 121 ms
  unsuspendAfter: 179 ms
popupPanel: 
  blocked: 13
  blockedDetails: 
    adpushup.com: 1
    clarity.ms: 1
    google-analytics.com: 1
    googlesyndication.com: 8
    googletagmanager.com: 2
```
</details>

**Comment by Daxy7** [comment]
`plagiarismdetector.net` large placeholders fix
```
plagiarismdetector.net##[id^="second_slot"]
plagiarismdetector.net##[id^="fourth_slot"]
```
ads apparent on 
```
https://smallseotools.com/
https://plagiarismdetector.net/
```

**Comment by Daxy7** [comment]
`https://smallseotools.com`

[grammarly promo](https://github.com/uBlockOrigin/uAssets/assets/91396482/24d667ac-a212-456f-ab49-007b233ef9cb)

```
smallseotools.com##.mxautoo
```

**Comment by mapx-** [comment]
test (for breakage too)

`smallseotools.com##+js(acs, $, _0x)`

**Comment by Daxy7** [comment]
[placeholders remain](https://github.com/uBlockOrigin/uAssets/assets/91396482/f8f0eb78-07f1-4db0-9c18-f27ac78ee098)

**Comment by Daxy7** [comment]
also main 'Check Grammar' button no longer works and displays 'Loading' forever

**Comment by mapx-** [comment]
Provide all the info when you report an issue.
Which page ?

this 1 ? 
`https://smallseotools.com/grammar-checker/`

working fine

**Comment by Daxy7** [comment]
my bad `smallseotools.com##+js(acs, $, _0x)` was already in the default filters. tested `My Filters` turmoiled the script

**Comment by bookarticle** [comment]
ads on `https://smallseotools.com/`

**Comment by Daxy7** [comment]
grammarly ads occurences
```
https://searchenginereports.net/
https://www.plagiarismchecker.co/
```

```
searchenginereports.net##.grammarly-overall
plagiarismchecker.co##.grmly_body
plagiarismchecker.co##.text-center.my-1
plagiarismchecker.co##.text-center.my-3

```

**Comment by Daxy7** [comment]
grammarly ads

```
https://searchenginereports.net/
https://www.plagiarismchecker.co/
```
```
plagiarismchecker.co##.g_body
plagiarismchecker.co##.my-1
plagiarismchecker.co##.my-3
searchenginereports.net##[id^="ee_"]
||searchenginereports.net/gram_images/
```

**Comment by Daxy7** [comment]
grammarly banner ad

```
https://plagiarismdetector.net/
```

```
plagiarismdetector.net##.pointer
! or
plagiarismdetector.net##aside
```

**Comment by Daxy7** [comment]
still see the ad

**Comment by Daxy7** [comment]
the data code is random every page refresh

```
<aside class="my-2" style="min-height:98px">

<a style="cursor: pointer;" data-jkmua="https://www.grammarly.com/?q=grammar&utm_source=placement&utm_medium=cpc&utm_content=72890_3&utm_term=plagiarismdetector_net" onclick="return  window.open($(this).data('jkmua'));" rel="nofollow noopener">
<img class="img-fluid pointer" src="[https://plagiarismdetector.net/pd-imgs/Top_Grammarly_banner.png](view-source:https://plagiarismdetector.net/pd-imgs/Top_Grammarly_banner.png)" alt="img" />
</a>
</aside>
```

**Comment by Daxy7** [comment]
banner ad (grammarly)

```
https://plagiarismdetector.net/
```

network
```
||plagiarismdetector.net/*/Top_Grammarly_banner.png
```

or cosmetic

```
plagiarismdetector.net##ckqrn
```

**Comment by Daxy7** [comment]
although loading from cache (f5) is waiting on dropbox overtime and see ads for 6 seconds


https://github.com/uBlockOrigin/uAssets/assets/91396482/9e88536c-8766-4a76-bff2-6818e692b01c

**Comment by mapx-** [comment]
FF issue, no such problem in chrome

**Comment by Daxy7** [comment]
in FF stable latest, `dropins.js` reported as `1566 ms` in `inspector` but final time is 8 sec.

`https://github.com/uBlockOrigin/uAssets/assets/91396482/f633f5d1-4298-426f-b2a0-b6b5c3c8daee`

**Comment by mapx-** [comment]
even blocking dropins I have the same delay

**Comment by Daxy7** [comment]
```
https://www.duplichecker.com/reverse-image-search.php
```

Edit: this placeholder can be hidden with `##div:nth-of-type(9)`, (11) for main page. It breaks 3 other things with same div. such this FAQ box[[1](https://github.com/uBlockOrigin/uAssets/assets/91396482/476e1342-d0e2-4ea6-ac3f-a923e3c599ba)], and previously (few iterations of domain ago) it used to hide the `baidu.com`  reverse image search div box.

I see this[[2](https://github.com/uBlockOrigin/uAssets/assets/91396482/8e9d51ec-b764-459a-be7f-0b152f8aa25f)] in the inspector so maybe hide with style/by px height?

**Comment by mapx-** [comment]
test

`duplichecker.com##.adsbygoogle:upward([style]):upward([style])`

provide the link - not the pic - for the tested page (FAQ box ?)

**Comment by Daxy7** [comment]
put it as
```
title
```
will look like this
```
https://www.duplichecker.com/reverse-image-search.php
```

**Comment by Daxy7** [comment]
The faq box is 80% down below the page of .php page i mentioned

**Comment by Daxy7** [comment]
> `duplichecker.com##.adsbygoogle:upward([style]):upward([style])`
works

**Comment by Daxy7** [comment]
grammarly [2] native ads

```
https://www.plagiarismchecker.co/grammar-check
```

cosmetic:
```
plagiarismchecker.co##.my-1
plagiarismchecker.co##.my-3
```
network:
`||www.plagiarismchecker.co/design_images/12340.png`
ineffective

**Comment by mapx-** [comment]
test (for FF use the last uBO dev build)

`plagiarismchecker.co##+js(rpnt, script, show(), empty(), condition, adsbygoogle)`

**Comment by Daxy7** [comment]
> `plagiarismchecker.co##+js(rpnt, script, show(), empty(), condition, adsbygoogle)`

works. what will be the approximate time for official stable release?

**Comment by mapx-** [comment]
it depends by the AMO reviewers

**Comment by Daxy7** [comment]
[five grammarly ads](https://github.com/uBlockOrigin/uAssets/assets/91396482/7da71ccd-4436-4440-a71f-1c143717490c)
```
https://smallseotools.com/grammar-checker/
```

```
smallseotools.com##.mxautoo
smallseotools.com##._g_arammarly_carousal_2
```

**Comment by ghajini** [comment]
does **MasterKia** suggested filter works for you
https://github.com/uBlockOrigin/uAssets/issues/17711#issuecomment-1587438991

**Comment by Daxy7** [comment]
1st or 2nd, both [remain `##.mxautoo`](https://github.com/uBlockOrigin/uAssets/assets/91396482/2961f2f7-1cb6-4783-856c-60c0392c766e)

**Comment by mapx-** [comment]
did you update the lists ? now

**Comment by Daxy7** [comment]
yeah looks good. can we use these for placeholders?

```
smallseotools.com##.mxautoo.px107
smallseotools.com##.mxautoo.px307
```

we have alike this for [Line 7371](https://github.com/uBlockOrigin/uAssets/blob/999417abcd625f5d6d9b11ff9dfb0a01b1550adb/filters/filters.txt#LL7371)

**Comment by mapx-** [comment]
too random

**Comment by Daxy7** [comment]
[seven grammarly ads](https://github.com/uBlockOrigin/uAssets/assets/91396482/28d6a6a5-f537-4b4e-97eb-38771091a497)
```
https://smallseotools.com/grammar-checker/
```
```
smallseotools.com##.mxautoo
smallseotools.com##._g_arammarly_carousal_2
```

**Comment by Daxy7** [comment]
these send detection notice to site owner, or just a log test

https://github.com/uBlockOrigin/uAssets/assets/91396482/c10f9924-7aa0-4c58-9327-2b2408973039

**Comment by Daxy7** [comment]
placehold ad, plus smallseotools grammarly ads are back
```
https://www.plagiarismchecker.co/
https://smallseotools.com/grammar-checker/
```
```
plagiarismchecker.co###top-add
smallseotools.com##.new___sa_
```

https://github.com/uBlockOrigin/uAssets/assets/91396482/4a3f92d4-9fe1-4d6f-a411-3f91d32858e7

**Comment by Daxy7** [comment]
smallseotools cpu abuse
```
https://smallseotools.com
```
259 instances of 
```
smallseotools.com##.icon_animation
```
in background, as lazy load placeholders. will leave boxes empty but icons are loaded anyway

**Comment by mapx-** [comment]
does this help ?

`*##*:style(animation: none !important;)`

**Comment by Daxy7** [comment]
works. we could use 
```
duplichecker.com,plagiarismchecker.co,plagiarismdetector.net,searchenginereports.net,smallseotools.com##*:style(animation: none !important;)
```
to match the rest of domains that use text box pulse animation

**Comment by Daxy7** [comment]
What is
```
duplichecker.com,plagiarismchecker.co,plagiarismdetector.net,searchenginereports.net,smallseotools.com##ins.adsbygoogle:style(max-height: 1.23px !important;)
```
filter for? I tried with standard cosmetics and haven't breakages/adblock detection.
google ads dotted artifacting at
```
https://www.plagiarismchecker.co/grammar-check
```
with the default filters. now tested these and no anti-adblock/breakage
```
duplichecker.com,plagiarismchecker.co,plagiarismdetector.net,searchenginereports.net,smallseotools.com#@#ins.adsbygoogle:style(max-height: 1.23px !important;)
duplichecker.com,plagiarismchecker.co,plagiarismdetector.net,searchenginereports.net,smallseotools.com##ins.adsbygoogle
```

**Comment by Daxy7** [comment]
grammarly ads 

```
https://searchenginereports.net/plagiarism-checker
https://smallseotools.com/grammar-checker/
```

```
searchenginereports.net##.showmeads
smallseotools.com##.mxutoo
smallseotools.com##._g_a_mammarle_carousel_2
```
https://github.com/uBlockOrigin/uAssets/assets/91396482/4c4866b5-4125-40ab-bb36-4b071d14eaef

**Comment by Daxy7** [comment]
Network filter blocking several elements (uBlock Filters - Quick Fixes)
```
https://searchenginereports.net/
```

```
||searchenginereports.net/js/*bioep
```

Before: https://github.com/uBlockOrigin/uAssets/assets/91396482/0b1a3927-dab4-405c-855e-c2002594d0d7
After: https://github.com/uBlockOrigin/uAssets/assets/91396482/54529a49-29de-497e-ab9c-2c10f81f2eb3

**Comment by Daxy7** [comment]
More breakage found @ illustrations:
Filters that are now obsolete:

Before:
[Example](https://github.com/uBlockOrigin/uAssets/assets/91396482/ce842fae-ee79-46db-abbd-823859960f13)
```
! uBlock Origin - Quick fixes - Line 188
||searchenginereports.net/js/*bioep
! uBlock Origin - Filters - Line 29052
searchenginereports.net##+js(ra, class, [data-name*="|"], stay)
```


After:
[Example](https://github.com/uBlockOrigin/uAssets/assets/91396482/da398d80-a7d2-46c8-86cb-492831f4f740)
```
||searchenginereports.net/js/*bioep$badfilter
searchenginereports.net#@#+js(ra, class, [data-name*="|"], stay)
```

**Comment by Daxy7** [comment]
grammarly ads
```
https://www.plagiarismchecker.co/
```
```
plagiarismchecker.co##.shshsh
```

**Comment by Daxy7** [comment]
grammarly banner ad
```
https://www.duplichecker.com/reverse-image-search.php
```
```
||duplichecker.com/*.php$image,1p
```

**Comment by Daxy7** [comment]
ad placeholder's back:
```
https://www.duplichecker.com/reverse-image-search.php
```

```
duplichecker.com##.plkane
```
https://github.com/uBlockOrigin/uAssets/assets/91396482/7bbb23f6-3b2d-436e-b4a8-05cf478cd467

**Comment by Yuki2718** [comment]
`##*:style(animation: none !important;)` is now causing "Pricing" disappered on `https://www.duplichecker.com/blog/`. Is the issue still relevant?

**Comment by Daxy7** [comment]
We used this because of lowkey cpu abuse in `smallseotools.com`'s homepage. 

259 instances of `smallseotools.com##.icon_animation` running in the background. 

Emailed them today about it, to solve officially. Let's give it 48 hours. We can remove style filter breakage and use `smallseotools.com##.icon_animation` for resource abuse list meanwhile.

![image](https://github.com/uBlockOrigin/uAssets/assets/91396482/e44be6f7-1e77-4945-967f-c29b2a2fc5e0)

**Comment by Yuki2718** [comment]
Maybe `##.icon_animation samp:style(animation: none !important;)` will be safer.
