### ISSUE TITLE
shesfreaky.com [NSFW] [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1772]
URL(s) where the issue occurs

`https://www.shesfreaky.com/`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.18

Settings

Default

**Comment by WowDude** [comment]
`||shesfreaky.com/pop/script.js` 
or in case it breaks anything
`shesfreaky.com##script:inject(abort-on-property-read.js, popns)`

**Comment by KiLL4FuNK** [comment]
ADS play Video
