### ISSUE TITLE
tv8.com.tr: ads

### ISSUE THREAD

**Issue by hasanozutatli** [uBlockOrigin/uAssets#17727]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tv8.com.tr/canli-yayin`

### Category

ads

### Description

When the site is first opened, there is no advertisement in the video. but after watching for 3 minutes (sometimes 30 seconds, sometimes 1 minutes, sometimes 3 minutes), a 15-second ad appears as I shot in the picture.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![reklam](https://user-images.githubusercontent.com/60298888/233789477-f873b6f6-9f11-416e-895d-acea32b7e076.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 209678
 cosmetic: 216511
 scriptlet: 40760
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67482-96, 23h.38m
  adguard-generic: 70502-568, 23h.37m
  adguard-mobile: 8687-48, 23h.36m
  adguard-spyware-url: 999-3, 23h.35m
  block-lan: 47-0, 5d.53m
  curben-phishing: 75874-2, 16h.58m
  curben-pup: 199-0, 16h.57m
  dpollock-0: 11354-93, 5d.52m
  fanboy-annoyance: 79010-5644, 5d.52m
  fanboy-cookiemonster: 46734-46734, 5d.52m
  fanboy-social: 18837-18814, 23h.32m
  ublock-annoyances: 4951-252, 23h.31m
 default: 
  user-filters: 909-19, never
  TUR-0: 12296-12, 23h.39m
  easylist: 65453-1161, 23h.34m
  easyprivacy: 30880-1492, 23h.33m
  plowe-0: 3749-1390, 5d.52m
  ublock-abuse: 70-0, 5d.52m
  ublock-badware: 6804-369, 23h.30m
  ublock-filters: 33946-4203, 23h.29m
  ublock-privacy: 311-7, 5d.52m
  ublock-quick-fixes: 205-40, 16h.56m
  ublock-unbreak: 1989-97, 23h.28m
  urlhaus-1: 7056-2, 16h.55m
filterset (user): [array of 307 redacted]
trustedset: 
 added: [array of 5 redacted]
 removed: 
  chrome-scheme
hostRuleset: 
 added: [array of 804 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: 
 filterAuthorMode: true
supportStats: 
 allReadyAfter: 535 ms (selfie)
 maxAssetCacheWait: 287 ms
popupPanel: 
 blocked: 38
 network: 
  adsafeprotected.com: 9
  doubleclick.net: 9
  exxen.com: 1
  facebook.net: 1
  google-analytics.com: 1
  google.com: 5
  googlesyndication.com: 6
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 2
  onesignal.com: 1
  tooplay.com: 1
 cosmetic: 
  ##iframe[name=\"googlefcPresent\"]
  ##.footer-social
  ##body #cookie-policy
  ###cookie-policy
  ##.cookie-notification:not(body)
  ##div.cookie-notification
  ##.cookie-message:not(html):not(body)
  ##body:style(overflow: auto !important;)
  ##[id^=\"div-gpt-ad\"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
  ##body:style(overflow: auto !important;)
  ##body:style(overflow: auto !important;)
```
</details>

**Comment by mapx-** [comment]
is that a real live transmission ?

**Comment by hasanozutatli** [comment]
yes.

**Comment by mapx-** [comment]
sometimes I see

![image](https://user-images.githubusercontent.com/10303732/233799468-f426d525-311f-4b77-b941-84e46588687d.png)

but that one is unavoidable
