### ISSUE TITLE
manhuaplus.com: nuisance

### ISSUE THREAD

**Issue by WidgyAinz** [uBlockOrigin/uAssets#17722]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://manhuaplus.com/manga/demon-magic-emperor/chapter-386/`

### Category

nuisance

### Description

Online radio will just start playing while inside an arrow at top left of pages. Annoying to have to hit stop every time.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 111
filterset (summary): 
  network: 299074
  cosmetic: 337469
  scriptlet: 43627
  html: 1193
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 70540-6470, 1m
    adguard-mobile: 8689-98, 2m
    adguard-spyware-url: 999-6, 2m
    block-lan: 47-0, 2m
    curben-phishing: 76116-35, 2m
    curben-pup: 194-0, 2m
    adguard-annoyance: 67504-7246, 2m
    adguard-social: 20326-833, 2m
    fanboy-thirdparty_social: 68-0, 2m
    fanboy-annoyance: 77220-65487, 2m
    fanboy-cookiemonster: 46729-311, 2m
    fanboy-social: 18498-28, 2m
    ublock-annoyances: 4918-4, 2m
    dpollock-0: 11355-512, 2m
    ALB-0: 301-4, 2m
    ara-0: 2778-1, 2m
    BGR-0: 1091-11, 2m
    CHN-0: 27625-168, 2m
    CZE-0: 738-0, 2m
    DEU-0: 6791-11, 2m
    [30 lists not shown]: [too many]
  default: 
    user-filters: 1-0, never
    ublock-filters: 34856-289, 1m
    ublock-badware: 6836-0, 2m
    ublock-privacy: 370-0, 2m
    ublock-abuse: 70-0, 2m
    ublock-unbreak: 2001-0, 1m
    ublock-quick-fixes: 206-4, 2m
    easylist: 65489-1264, 2m
    easyprivacy: 30880-2013, 2m
    urlhaus-1: 7082-1, 2m
    plowe-0: 3746-4, 2m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4395 ms (selfie)
  maxAssetCacheWait: 2142 ms
popupPanel: 
  blocked: 28
  blockedDetails: 
    manhuaplus.com: 2
    360playvid.info: 2
    adnxs.com: 1
    bidgear.com: 1
    disqus.com: 4
    doubleclick.net: 2
    google-analytics.com: 1
    googlesyndication.com: 4
    googletagmanager.com: 1
    narrative.io: 2
    outbrain.com: 2
    pippio.com: 1
    privacymanager.io: 1
    rezync.com: 1
    viglink.com: 2
    web0.eu: 1
```
</details>

**Comment by mapx-** [comment]
just add in "my filters"

`||pariatonet.com/radio$frame,domain=manhuaplus.com`
