### ISSUE TITLE
[nsfw] 52hb.com: popups

### ISSUE THREAD

**Issue by zhangbaida888** [uBlockOrigin/uAssets#17723]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.52hb.com/`
`https://www.baidu.com/`

### Category

popups

### Description

After enabling the rules of AdGuard Chinese, the login window cannot pop up.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 79296
 cosmetic: 50462
 scriptlet: 17956
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  easyprivacy: null
 added: 
  https://gcore.jsdelivr.net/gh/xinggsf/Adblock-Plus-Rule@master/mv.txt: 227-0, 38m
  https://gcore.jsdelivr.net/gh/xinggsf/Adblock-Plus-Rule@master/rule.txt: 1208-2, 38m
 default: 
  user-filters: 69-1, never
  CHN-0: 27625-140, 12m
  easylist: 65489-120, 38m
  plowe-0: 3749-362, 5d.8h.23m
  ublock-abuse: 70-1, 5d.8h.26m
  ublock-badware: 6823-120, 1d.7h.15m
  ublock-filters: 33939-130, 22h.16m
  ublock-privacy: 311-2, 5d.8h.25m
  ublock-quick-fixes: 205-33, 3h.56m
  ublock-unbreak: 1988-16, 1d.7h.14m
  urlhaus-1: 7082-1, 3h.55m
filterset (user): [array of 61 redacted]
trustedset: 
 added: [array of 8 redacted]
 removed: 
  edge-scheme
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 360 ms
 maxAssetCacheWait: 131 ms
popupPanel: 
 blocked: 3
 network: 
  baidu.com: 1
  dingxiang-inc.com: 2
 cosmetic: 
  ##div.a_mu,div.a_h,div.ad_pic,div.wp.a_f,div.wp.a_t,div.a_pb,div.a_pt,div.a_pr,div.a_cn,#ggPar,#preAdContent
```
</details>

**Comment by mapx-** [comment]
No issue on baidu. 
52hb seems to be not reachable

Try using only the default settings / filter lists and test again
