### ISSUE TITLE
sk.rs: ads

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#17720]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sk.rs/clanak/3793/trejler-za-pucacinu-zbunio-internet-unreal-petica-ili-laznjak`

### Category

ads

### Description

Website shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 89715
 cosmetic: 39925
 scriptlet: 17755
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 64939-44, 3d.2h.37m
  easyprivacy: 30862-1176, 3d.2h.36m
  plowe-0: 3748-940, 6d.7h
  ublock-abuse: 70-0, 2d.5h.5m
  ublock-badware: 6799-117, 3d.2h.35m
  ublock-filters: 33865-101, 3d.2h.34m
  ublock-privacy: 316-3, 2d.5h.4m
  ublock-quick-fixes: 204-22, 1d.43m
  ublock-unbreak: 1986-45, 3d.2h.33m
  urlhaus-1: 7230-1, 1d.42m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 957 ms (selfie)
 maxAssetCacheWait: 106 ms
popupPanel: 
 blocked: 6
 network: 
  adocean.pl: 1
  doubleclick.net: 2
  googletagmanager.com: 1
  youtube.com: 2
 cosmetic: 
  ##.ytp-ad-progress-list
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
```
</details>

**Comment by mapx-** [comment]
add

```
sk.rs##.baner
sk.rs##.bnr
```

maybe you @GKid94 could enable also this list `HRV, SRB: Dandelion Sprout's Serbo-Croatian filters`

@DandelionSprout as ex-Jugoslavia country you could add to that list the bosnian pages too

**Comment by DandelionSprout** [comment]
From how I understand uBO language tags, turning it into `HRV, SRB, BIH:` in uBO's settings would've required finding at least one web browser with a Bosnian UI option.
