### ISSUE TITLE
arcadethunder.com: breakage

### ISSUE THREAD

**Issue by kazemail** [uBlockOrigin/uAssets#17729]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://arcadethunder.com/hidden-object-games/daily-difference`

### Category

breakage

### Description

ARcade Thunder specific game "Daily Difference" won't open but other daily game is fine.  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 89888
 cosmetic: 39954
 scriptlet: 17766
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65454-44, 1d.1h.28m
  easyprivacy: 30880-1180, 1d.1h.28m
  plowe-0: 3746-940, 1d.1h.28m
  ublock-abuse: 70-0, 1d.1h.28m
  ublock-badware: 6804-120, 1d.1h.28m
  ublock-filters: 33879-102, 1d.1h.28m
  ublock-privacy: 316-3, 1d.1h.28m
  ublock-quick-fixes: 205-22, 1h.15m
  ublock-unbreak: 1991-45, 1d.1h.27m
  urlhaus-1: 6894-1, 1h.14m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1043 ms (selfie)
 maxAssetCacheWait: 417 ms
popupPanel: 
 blocked: 13
 network: 
  arcadethunder.com: 1
  addthis.com: 1
  flurry.com: 1
  google-analytics.com: 1
  google.com: 6
  googlesyndication.com: 1
  googletagmanager.com: 1
  quantserve.com: 1
 cosmetic: 
  ##ins.adsbygoogle
  ##.modals
  ##.advert_container
```
</details>

**Comment by gorhill** [comment]
Need:

    @@||cdn.flurry.com/js/flurry.js$script,domain=securegames.iwin.com

To counter EasyPrivacy's and uBO's `||flurry.com^$3p`.

**Comment by kazemail** [comment]
I am 80 years old and don't undertand all this but just want to play the game on Arcade Thunder.  Can you help me?

**Comment by gorhill** [comment]
Go to _Filter lists_ pane in uBO's dashboard, click _Purge all caches+, then click _Update now_. Once the update is complete, force a reload of the game page, it should work.
