### ISSUE TITLE
lostfilm.tv: breakage

### ISSUE THREAD

**Issue by GhoSt-1992** [uBlockOrigin/uAssets#17728]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lostfilm.tv/`

### Category

breakage

### Description

"Disable cosmetic filtering on this site" function doesn't work properly and is unstable on LostFilm.tv since the previous week. The only filter is turned on is RUS: RU AdList. The poster in the red frame doesn't load anymore (previously it worked just fine). If I turn uBlock Origin off - the poster will appear. If then I turn uBlock Origin on with disabling cosmetic filtering - poster may appear or may not - 50/50. But if I refresh the page in some time in 30+ min for instance (with Ublock and disabling cosmetic filtering both turned on) - the poster will disappear again... Magick((( It seems like smth is causing unstable work of the "disable cosmetic filtering" feature after RUS: RU AdList filter being updated.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

"Disable cosmetic filtering on this site" function doesn't work properly:
![Lostfilm 01](https://user-images.githubusercontent.com/121423714/233788594-acb40e58-8352-4f2f-8d70-9d5fb19dd9d6.png)
I mean this poster in red frame doesn't load:
![Lostfilm 02](https://user-images.githubusercontent.com/121423714/233788596-70e1e724-b9e6-4e98-af62-8ae566d31715.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 213975
 cosmetic: 244977
 scriptlet: 40702
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67470-495, 1d.22h.40m
  adguard-generic: 70414-721, 1d.22h.40m
  adguard-mobile: 8680-68, 1d.22h.40m
  adguard-social: 20316-865, 1d.22h.40m
  adguard-spyware-url: 1000-3, 1d.22h.40m
  block-lan: 47-0, 1d.22h.40m
  curben-phishing: 75874-2, 22h.5m
  curben-pup: 199-0, 22h.6m
  fanboy-annoyance: 78032-6474, 1d.22h.40m
  fanboy-cookiemonster: 46788-46788, 1d.22h.40m
  fanboy-social: 18995-18995, 1d.22h.40m
  fanboy-thirdparty_social: 68-18, 1d.22h.40m
  ublock-annoyances: 4951-253, 1d.22h.40m
 default: 
  user-filters: 23-0, never
  RUS-0: 39706-12, 1d.22h.40m
  easylist: 65278-917, 1d.22h.40m
  easyprivacy: 30863-1448, 1d.22h.40m
  plowe-0: 3748-1041, 1d.22h.40m
  ublock-abuse: 70-1, 1d.22h.40m
  ublock-badware: 6813-368, 1d.22h.40m
  ublock-filters: 33912-4196, 1d.22h.39m
  ublock-privacy: 321-7, 1d.22h.39m
  ublock-quick-fixes: 205-40, 22h.4m
  ublock-unbreak: 1991-96, 1d.22h.39m
  urlhaus-1: 7056-2, 22h.3m
filterset (user): [array of 23 redacted]
trustedset: 
 added: [array of 29 redacted]
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 contextMenuEnabled: false
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 24583 ms (selfie)
 maxAssetCacheWait: 1368 ms
popupPanel: 
 blocked: 5
 no-cosmetic-filtering: true
 network: 
  lostfilm.tv: 2
  jsdelivr.net: 1
  lostfilm.top: 1
  yandex.ru: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Add

```adb
@@||static.lostfilm.top/ebllbe/*$image,domain=lostfilm.tv
```

@dimisa-RUAdList Sorry, can you check this? Is it an ad?

**Comment by dimisa-RUAdList** [comment]
The banner in the header of the site, depending on the rotation, contains either third-party advertising of games, or duplicates one of its own announcements from the right column. Since it is difficult to separate one from the other, and the announcement is just a duplicate, the banner has been blocked for many years anyway. 

Until recently, only hiding rules were used to block this banner, but recently a rule was added to block images of the target directory.

**Comment by stephenhawk8054** [comment]
@GhoSt-1992 If you want to view the banner, add these filters:

```adb
lostfilm.tv#@#.oi_papa_oi
lostfilm.tv#@#body > span:nth-child(-1n+6)
lostfilm.tv#@#body:style(background-image: none !important; background-color: #1c1e1f !important)
@@||static.lostfilm.top/ebllbe/*$image,domain=lostfilm.tv
```
