### ISSUE TITLE
Proton Mail new ad banner

### ISSUE THREAD

**Issue by Candlemass** [uBlockOrigin/uAssets#17734]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Proton mail now has an annoying ad banner across the top of the inbox while using the web interface on a mobile device.

### URL(s) where the issue occurs.

https://mail.proton.me/u/1/inbox#page=1

### Screenshot(s)

https://i.postimg.cc/KzQkSPNR/20230422-131505.png

### uBO version

1.48.4

### Browser name and version

Firefox mobile 111

### Settings

None.

### Notes

Tried enabling all additional filters.

No change.

**Comment by mapx-** [comment]
the upgrade thing ? it's self-promo

add in your "my filters"
`mail.proton.me##.bg-promotion`

**Comment by Candlemass** [comment]
> the upgrade thing ? it's self-promo
> 
> add in your "my filters" `mail.proton.me##.bg-promotion`

Thanks for the quick reply.

That appears to have taken care of it.

Cheers.
