### ISSUE TITLE
verfutebol.net: nuisance

### ISSUE THREAD

**Issue by Lucas559-noob** [uBlockOrigin/uAssets#17737]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://verfutebol.net/`

### Category

nuisance

### Description

There is a banner and text on player and I wanted to remove those 2.

### Screenshot(s)

<details>
<summary>Screenshot of video player with banner and text</summary>

![image](https://user-images.githubusercontent.com/54007604/233813115-05e7bb6d-311d-4f61-8e39-02e849a5af1c.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 109
filterset (summary): 
 network: 91286
 cosmetic: 43334
 scriptlet: 18059
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65456-44, 1d.23h.48m
  easyprivacy: 30863-1180, 2d.10h.50m
  plowe-0: 3748-940, 2d.4h.1m
  spa-1: 5188-69, 1d.23h.47m
  ublock-abuse: 70-0, 2d.21h.11m
  ublock-badware: 6818-120, 1d.23h.46m
  ublock-filters: 33866-132, 1d.23h.45m
  ublock-privacy: 316-3, 2d.21h.10m
  ublock-quick-fixes: 204-22, 8h.52m
  ublock-unbreak: 1991-46, 1d.23h.44m
  urlhaus-1: 6894-1, 8h.53m
filterset (user): [empty]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 35363 ms (selfie)
 maxAssetCacheWait: 249 ms
popupPanel: 
 blocked: 6
 network: 
  facebook.net: 1
  googletagmanager.com: 2
  ibb.co: 1
  waust.at: 1
  webpushr.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||verfutebol.net/superderbi.php
verfutebol.net###superderbi
```

@Yuki2718 for Adguard Portuguese?

**Comment by Yuki2718** [comment]
The traffic (73k) is marginally not sufficient for AG filter policy, but I guess in this case I can address.
