### ISSUE TITLE
[nsfw] kr1.hasha.in: breakage

### ISSUE THREAD

**Issue by Coder-Iro** [uBlockOrigin/uAssets#17738]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kr1.hasha.in/`

### Category

breakage

### Description

In addition to advertising, normal content seems to be blocked from loading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 91172
 cosmetic: 43070
 scriptlet: 17890
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  KOR-1: 4325-14, 1m
  easylist: 65551-85, 1m
  easyprivacy: 30882-1192, 1m
  plowe-0: 3746-952, 1m
  ublock-abuse: 70-0, 1m
  ublock-badware: 6848-120, 1m
  ublock-filters: 33994-107, 1m
  ublock-privacy: 320-5, 1m
  ublock-quick-fixes: 214-34, 1m
  ublock-unbreak: 1993-45, 1m
  urlhaus-1: 6918-1, 1m
filterset (user): [empty]
trustedset: 
 added: [array of 26 redacted]
 removed: 
  edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1416 ms (selfie)
 maxAssetCacheWait: 491 ms
popupPanel: 
 blocked: 19
 network: 
  hasha.in: 5
  cloudflareinsights.com: 1
  realsrv.com: 13
 cosmetic: 
  ##div[style^=\"min-height:\"][class^=\"bg-hasha-\"] > .max-w-full
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.adsbyexoclick
```
</details>

**Comment by stephenhawk8054** [comment]
It's caused by

```adb
hasha.in##div[style^="min-height:"][class^="bg-hasha-"] > .max-w-full
```

@piquark6046 Sorry can you take a look?

**Comment by piquark6046** [comment]
Fixed,
