### ISSUE TITLE
graphics.c.u-tokyo.ac.jp: breakage

### ISSUE THREAD

**Issue by tasty0tomato** [uBlockOrigin/uAssets#17735]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://graphics.c.u-tokyo.ac.jp/hp/en/`

### Category

breakage

### Description

The News part is not ad actually.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![graphics c u-tokyo ac jp_hp_en_ (1)](https://user-images.githubusercontent.com/48764449/233808353-bb38617c-97c4-4e8e-8064-485238cb7421.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 69512
 cosmetic: 140374
 scriptlet: 20567
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  easyprivacy: null
  plowe-0: null
  ublock-abuse: null
  ublock-badware: null
  ublock-privacy: null
  ublock-quick-fixes: null
  urlhaus-1: null
 added: 
  https://www.i-dont-care-about-cookies.eu/abp/: 25651-4, 1d.10h.29m
  CHN-0: 27617-107, 1d.10h.25m
  adguard-annoyance: 67469-1693, 1d.10h.27m
 default: 
  user-filters: 0-0, never
  JPN-1: 10918-14, 1d.10h.28m
  easylist: 65453-170, 1d.10h.26m
  ublock-filters: 33927-514, 1d.10h.24m
  ublock-unbreak: 1991-13, 1d.10h.23m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 325 ms (selfie)
 maxAssetCacheWait: 199 ms
popupPanel: 
 blocked: 0
 cosmetic: 
  ###main.site-main > div > div > a[href] > img
```
</details>

**Comment by peace2000** [comment]
Adguard China has this rule, which causes the issue:

`###main.site-main > div > div > a[href] > img`

To counter that rule temporarily, please add this filter:

`#@##main.site-main > div > div > a[href] > img`

**Comment by tasty0tomato** [comment]
Sorry for not check Adguard China, maybe opening an issue that place will be better?

**Comment by peace2000** [comment]
That rule seems to be in the Easylist China part (Adguard uses rules from Easylist China). I'll notify the maintainer.

**Comment by peace2000** [comment]
Fixed in the original list, please update your filters.
