### ISSUE TITLE
[NSFW] porcore.com Video issues

### ISSUE THREAD

**Issue by FtkPCV** [uBlockOrigin/uAssets#17736]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

line 4484: of 
![image](https://user-images.githubusercontent.com/131563343/233812905-3bb3f9d4-a918-40f3-a91d-1f95e6dbbc38.png)
  : breakes porcore's videos |   gamcore.com,porcore.com,69games.xxx##+js(aost, Math.random, stackDepth:4)

### URL(s) where the issue occurs.

`https://porcore.com/video/1495/care/`
or any other video i just clicked on whatever the latest one was.

### Screenshot(s)

`https://porcore.com/video/1495/care/`     <--- infinite loading due to line in description. happens on all videos.

### uBO version

1.49.0

### Browser name and version

Chrome  |  Version 112.0.5615.138 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/131563343/233813006-86e0a26c-036b-43f4-a0d6-8e889c28d036.png)
i clicked the #@# button to enable it then reload the page and the video works fine

**Comment by FtkPCV** [comment]
my settings: (because im retarded and didnt put them in the issue)|
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 90160
 cosmetic: 40016
 scriptlet: 17771
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65496-44, 21h.8m
  easyprivacy: 30881-1182, 21h.8m
  plowe-0: 3746-939, 21h.8m
  ublock-abuse: 70-0, 21h.8m
  ublock-badware: 6832-120, 21h.8m
  ublock-filters: 33970-103, 21h.8m
  ublock-privacy: 320-3, 21h.8m
  ublock-quick-fixes: 205-34, 21h.8m
  ublock-unbreak: 1990-45, 21h.8m
  urlhaus-1: 7082-1, 21h.8m
filterset (user): [empty]
modifiedUserSettings: 
 autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 156 ms (selfie)
 maxAssetCacheWait: 90 ms

**Comment by gorhill** [comment]
> my settings: ... didnt put them in the issue

uBO fill them in automatically when you use the _chat_ icon in the popup panel to report site issue.
