### ISSUE TITLE
playhub.com: ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17731]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://www.playhub.com/racing/cars-vs-transformers.html`

### Category

ads

### Description

ads:
```
playhub.com##.ad-title-megaban
playhub.com##.ad-title-pave
playhub.com##.ad-title-sky
playhub.com##.promo-game
play.turbommo.com$3p
```
And breakage with Flash Player content. Works with EasyList disabled. Running with Ruffle extension.
[What it is normally](https://user-images.githubusercontent.com/91396482/233796366-290d3942-fd13-43d6-93eb-39050e507aef.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 81532
  cosmetic: 43073
  scriptlet: 21380
  html: 1118
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 16h.44m
    https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1552-0, 16h.45m
    https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 2d.2h.2m
    ublock-annoyances: 4918-4, 1d.25m
  default: 
    user-filters: 1687-13, never
    ublock-filters: 34850-81, 13h.57m
    ublock-badware: 6837-0, 1d.52m
    ublock-privacy: 370-0, 1d.52m
    ublock-abuse: 70-0, 1d.52m
    ublock-unbreak: 2001-4, 1d.52m
    ublock-quick-fixes: 204-0, 1d.52m
    easylist: 65478-284, 1d.52m
    easyprivacy: 30881-2232, 1d.52m
filterset (user): [array of 716 redacted]
switchRuleset: 
  added: [array of 4 redacted]
hostRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 387 ms (selfie)
  maxAssetCacheWait: 195 ms
  unsuspendAfter: 129 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by mapx-** [comment]
for the breakage add

`@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=playhub.com`

@ryanbr

**Comment by Daxy7** [comment]
Parent domain[s] have breakages and ads:

```
http://www.kissinggames.com/girls/secret-office-kissing.html
http://www.playpink.com/girls/dress-up/my-puppy.html
```

Propose:

```
@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=kissinggames.com|playhub.com|playpink.com
kissinggames.com,playhub.com,playpink.com##.ad-title-megaban
kissinggames.com,playhub.com,playpink.com##.ad-title-pave
kissinggames.com,playhub.com,playpink.com##.ad-title-sky
kissinggames.com,playhub.com,playpink.com##.promo-game
```

**Comment by Daxy7** [comment]
@stephenhawk8054 add the filters to unbreak?
