### ISSUE TITLE
aixiaola.com: ads

### ISSUE THREAD

**Issue by 0x391F** [uBlockOrigin/uAssets#17740]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aixiaola.com/liuxingyu2/344846.html`

### Category

ads

### Description

Here're some residue on the webpage

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 214440
  cosmetic: 215631
  scriptlet: 39473
  html: 1117
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 70541-5530, 5m
    adguard-mobile: 8691-98, 5m
    adguard-spyware-url: 999-5, 4m
    block-lan: 47-0, 4m
    curben-phishing: 76628-36, 4m
    curben-pup: 199-0, 4m
    adguard-annoyance: 67508-6013, 3m
    fanboy-thirdparty_social: 69-0, 3m
    fanboy-annoyance: 77231-46955, 3m
    fanboy-cookiemonster: 46729-239, 3m
    ublock-annoyances: 4920-4, 3m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34878-95, 6m
    ublock-badware: 6857-0, 6m
    ublock-privacy: 370-0, 6m
    ublock-abuse: 70-0, 6m
    ublock-unbreak: 2004-6, 6m
    ublock-quick-fixes: 215-0, 6m
    easylist: 65515-722, 4m
    easyprivacy: 30883-1796, 4m
    urlhaus-1: 6918-1, 4m
    plowe-0: 3746-3, 3m
    CHN-0: 27629-134, 2m
filterset (user): [empty]
modifiedUserSettings: 
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2141 ms
  maxAssetCacheWait: 1274 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    aixiaola.com: 1
    baidu.com: 9
    baidustatic.com: 3
    bdstatic.com: 2
    googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
||aixiaola.com/*&*&*&$frame,1p
aixiaola.com###advert_widget
aixiaola.com##.advert
```

@cjx82630

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/c97584c4c04d6f092f361f02cdb84c2a6aa85bfe
