### ISSUE TITLE
yandex.ru: ads

### ISSUE THREAD

**Issue by ProtogenVX** [uBlockOrigin/uAssets#17746]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yandex.ru/images/search`

### Category

ads

### Description

Is it possible to block the entire Yandex advertising domain (including other sites) if an ad comes from it with a dynamically changing block link?  Or, for example, to block links of the "typical kind" by adding replacement characters in place of changing elements?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (1)](https://user-images.githubusercontent.com/91836705/233847318-49894b25-b598-4a88-ade5-48cd24399834.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 106868
 cosmetic: 61000
 scriptlet: 19041
 html: 0
listset (total-discarded, last-updated): 
 added: 
  RUS-0: 39642-12, 1d.37m
 default: 
  user-filters: 0-0, never
  easylist: 65278-62, 3d.1h.46m
  easyprivacy: 30880-1283, 3d.1h.45m
  plowe-0: 3748-945, 3d.1h.49m
  ublock-abuse: 70-1, 3d.1h.48m
  ublock-badware: 6813-117, 3d.1h.44m
  ublock-filters: 33865-132, 3d.1h.43m
  ublock-privacy: 321-3, 3d.1h.47m
  ublock-quick-fixes: 213-22, 1d.37m
  ublock-unbreak: 1990-45, 3d.1h.41m
  urlhaus-1: 6894-1, 1d.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2565 ms (selfie)
 maxAssetCacheWait: 891 ms
popupPanel: 
 blocked: 1034
 network: 
  yandex.ru: 1030
  adriver.ru: 3
  yastatic.net: 1
 cosmetic: 
  ##.b-page:style(padding-top: 0 !important)
  ##.serp-header:style(margin-top: 0 !important)
```
</details>

**Comment by mapx-** [comment]
subscribe to this this too [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)

from https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

**Comment by gorhill** [comment]
Also: <https://github.com/uBlockOrigin/uBlock-issues/issues/2627#issuecomment-1528886506>
