### ISSUE TITLE
porntube.com [NSFW][ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1774]
URL(s) where the issue occurs

`https://www.porntube.com/videos/gia-paige-interracial-muff-banging_7414233`

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.18

Settings

Default

**Comment by WowDude** [comment]
Enabling `Adguard Base Filters` removes the ads.

**Comment by mapx-** [comment]
Where are the ads ? screenshot ?

**Comment by WowDude** [comment]
(O 51 64bit / F 59.01 64bit & uBO 1.15.18 on Default & Win 7 SP1 64bit):

On Opera ads:

<details>
  <summary>Screenshoots</summary>

![porntube](https://user-images.githubusercontent.com/37474031/37855051-a603df52-2eed-11e8-8fe9-ed545505ca3e.png)

![porntube2](https://user-images.githubusercontent.com/37474031/37855098-d7c74984-2eed-11e8-8099-67afebeb16d5.png)

</details>
.

On Firefox no ads...

**Comment by mapx-** [comment]
no ads in opera 52 + uBo Version 1.15.2

**Comment by Blutgang** [comment]
@mapx- 

https://github.com/uBlockOrigin/uAssets/blob/fda8be76673c01fc3d9883861e6a768915b71493/filters/filters.txt#L3237

`porntube.com##script:inject(abort-on-property-read.js, ExoLoader)` is in the filter list already?

https://github.com/uBlockOrigin/uAssets/blob/fda8be76673c01fc3d9883861e6a768915b71493/filters/filters.txt#L1906

`/mojon.js$script,first-party,domain=4tube.com|fux.com|pornerbros.com|porntube.com` should work for Chromium browsers...

**Comment by WowDude** [comment]
The issue is now fixed with updated uBlock filters.

> @Blutgang : @WowDude does this filter work for you?

Both of them works too.

**Comment by WowDude** [comment]
@mapx- : And why `mojon.js` remained unblocked? Does blocking it breaks anything (what)?

**Comment by mapx-** [comment]
Do you still see ads ?

**Comment by WowDude** [comment]
No, but I see useless `mojon.js` script loaded which unnecessary wastes resources (bandwidth, CPU, memory/ram, electrical energy etc.) and also most probably slows the loading of the webpage, especially that it gets loaded several (6) times:

![mojon](https://user-images.githubusercontent.com/37474031/37901335-2cb328f0-30f1-11e8-9bd5-be30cc5bb293.png)

Though blocking ads is not just about hiding them visually but also as from [Wikipedia  ](https://en.wikipedia.org/wiki/Ad_blocking#Benefits):

> To users, the benefits of ad blocking software include **quicker loading** and cleaner looking web pages with fewer distractions,[5] **lower resource waste (bandwidth, CPU, memory, etc**.), and privacy benefits [6] gained through the exclusion of the tracking and profiling systems of ad delivery platforms. Blocking ads can also **save substantial amounts of electrical energy and lower users' power bills.**[7][8]

Do you see it?

**Comment by gorhill** [comment]
@WowDude OP issue is solved, leave it alone please. If you think the script should be blocked make the case elsewhere with actual specific evidence, do not use unrelated quotes which are not _specifically related_ to what you think is an issue. Also, do not embed pornographic images here, use text-only URLs and mark them clearly as NSFW.
