### ISSUE TITLE
small-games.info: breakage

### ISSUE THREAD

**Issue by LittleWhiteTail** [uBlockOrigin/uAssets#17749]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://small-games.info/?go=genre&c=79&s=4`

### Category

breakage

### Description

can not load main page when use uBlock.  a white page app
![Снимок экрана 2023-04-23 213853](https://user-images.githubusercontent.com/131614417/233858616-b0878689-5825-4020-85e7-fd28299b5ad0.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 107008
  cosmetic: 61144
  scriptlet: 19051
  html: 957
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34851-53, 20h.27m
    ublock-badware: 6836-0, 20h.26m
    ublock-privacy: 361-0, 6d.7h.38m
    ublock-abuse: 70-0, 6d.7h.37m
    ublock-unbreak: 2004-5, 20h.25m
    ublock-quick-fixes: 203-0, 28m
    easylist: 65551-642, 20h.28m
    easyprivacy: 30880-1770, 20h.29m
    urlhaus-1: 6741-1, 26m
    plowe-0: 3749-3, 4d.1h.37m
    RUS-0: 39728-155, 12h.24m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 571 ms (selfie)
  maxAssetCacheWait: 163 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    admitad.com: 1
    google-analytics.com: 1
    yadro.ru: 1
    yandex.ru: 2
```
</details>

**Comment by dimisa-RUAdList** [comment]
That's the way it should be. The site was blocked due to bypassing the blocker in order to promote malware. The site administrations were sent appropriate notifications, both warning and upon blocking.

**Comment by mapx-** [comment]
@LittleWhiteTail  

You can read above the deecision of russian list maintainer.
However if you still trust that site just disable the cosmetic filters for it.
