### ISSUE TITLE
motorsport.com: breakage

### ISSUE THREAD

**Issue by sinenomine2023** [uBlockOrigin/uAssets#17748]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When i use ublock at the website i need to turn it off. Website demand accept the cookies, but i can`t do that. Thanks for help.

### URL(s) where the issue occurs.

```
https://pl.motorsport.com/f1/
https://pl.motorsport.com
```

### Screenshot(s)

![12345](https://user-images.githubusercontent.com/131607673/233851925-106916bb-496c-4608-9501-5304dd8e176c.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 118872
 cosmetic: 206769
 scriptlet: 39653
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67509-98, 2m
  adguard-generic: 70548-793, 2m
  adguard-mobile: 8691-49, 2m
  adguard-social: 20326-857, 2m
  adguard-spyware-url: 999-3, 2m
  fanboy-cookiemonster: 46737-3737, 1m
  fanboy-thirdparty_social: 68-3, 2m
  ublock-annoyances: 4957-238, 2m
 default: 
  user-filters: 4-0, never
  POL-0: 7933-8, 2m
  POL-2: 1275-13, 2m
  easylist: 65636-944, 2m
  easyprivacy: 30891-1385, 2m
  plowe-0: 3746-1040, 2m
  ublock-abuse: 70-0, 2m
  ublock-badware: 6867-342, 2m
  ublock-filters: 33991-4239, 2m
  ublock-privacy: 320-6, 2m
  ublock-quick-fixes: 210-23, 2m
  ublock-unbreak: 1999-95, 2m
  urlhaus-1: 6741-1, 2m
filterset (user): [array of 4 redacted]
trustedset: 
 added: [array of 28 redacted]
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 506 ms (selfie)
 maxAssetCacheWait: 375 ms
```
</details>

**Comment by gorhill** [comment]
I can't reproduce issue when using same set of filter lists and a POL IP address.

Please report troubleshooting information for the webpage which has the issue: popup panel => chat icon => click troubleshooting information => copy/paste here.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
