### ISSUE TITLE
[nsfw] clgt.one: ads

### ISSUE THREAD

**Issue by Jokopentil** [uBlockOrigin/uAssets#17744]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://clgt.one/proxy.php/https://www.xnxx.com/video-12q2prc1/rica_cogida_a_mi_cunada_mientras_pela_tomate_le_entierro_rico_la_verga`

### Category

ads

### Description

Vvvideo ads cant block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

    https://user-images.githubusercontent.com/114223791/233843259-9423c909-7618-406d-b981-9fe6bc46dc26.jpg

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium Mobile: 112
filterset (summary): 
 network: 217821
 cosmetic: 232830
 scriptlet: 40700
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/output/adblockid_plus.txt: 77-0, 1d.10h.18m
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 2m
  https://raw.githubusercontent.com/Hakame-kun/uBlock-Filters-Indonesia/master/uBlock Indo/ubindo.txt: 1632-2, 18d.3h.29m
  https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 8596-20, 2m
  adguard-annoyance: 67451-150, 3d.13h.59m
  adguard-generic: 70349-733, 3d.13h.58m
  adguard-social: 20306-857, 3d.13h.56m
  adguard-spyware-url: 996-3, 3d.13h.55m
  block-lan: 47-0, 18d.3h.32m
  curben-phishing: 78932-2, 2m
  curben-pup: 194-0, 2m
  dpollock-0: 11354-82, 6d.22h.54m
  fanboy-annoyance: 80017-6504, 8d.23h.47m
  fanboy-cookiemonster: 46659-46659, 8d.23h.45m
  fanboy-social: 18491-18447, 1d.10h.19m
  fanboy-thirdparty_social: 68-21, 8d.23h.44m
  ublock-annoyances: 5011-280, 1d.10h.19m
 default: 
  user-filters: 3-1, never
  IDN-0: 5470-373, 3d.14h
  adguard-mobile: 8678-55, 3d.13h.57m
  easylist: 65496-1169, 1d.10h.19m
  easyprivacy: 30880-1502, 1d.10h.19m
  plowe-0: 3748-1388, 3d.14h.1m
  ublock-abuse: 70-1, 7d.8h.37m
  ublock-badware: 6807-372, 1d.10h.19m
  ublock-filters: 34180-4300, 1d.10h.18m
  ublock-privacy: 295-6, 7d.8h.37m
  ublock-quick-fixes: 210-23, 2m
  ublock-unbreak: 1995-98, 1d.10h.18m
  urlhaus-1: 6741-3, 2m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
 ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 9950 ms (selfie)
 maxAssetCacheWait: 1873 ms
popupPanel: 
 blocked: 7
 network: 
  clgt.one: 1
  amung.us: 1
  bowerywill.com: 2
  googletagmanager.com: 1
  qlfqkjluvz.com: 1
  smart2cnjuh34jb.com: 1
 cosmetic: 
  ###ad-header-mobile
  ##.remove-ads
  ##.remove-ads-link
```
</details>

**Comment by Jokopentil** [comment]
![20230422_111611_rmscr.jpg](https://user-images.githubusercontent.com/114223791/233843259-9423c909-7618-406d-b981-9fe6bc46dc26.jpg)

**Comment by mapx-** [comment]
@ryanbr
