### ISSUE TITLE
en.financerites.com: nuisance

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#17753]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://en.financerites.com/eating-healthy-on-a-budget-tips-and-tricks-for-nutritious-affordable-meals/`

### Category

nuisance

### Description

This site is weird, when I turn on uBo it redirects me to another webpage, but if I turn off uBo on the previous site it doesn't redirect me to any other webpage.
Main page:
`https://clks.pro/WBg0G`

Redirect page:
`https://clicksfly.com/st?api=8d992fda29c02dfc6d7521cc0e609477f27b6e36&url=https://mdn.lol/bypass.php`

`https://enit.in/SCn6Gyc`

`https://en.financerites.com/eating-healthy-on-a-budget-tips-and-tricks-for-nutritious-affordable-meals/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/45124799/233902859-132dcf1b-6c1e-4b4b-a083-f5355fe29471.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 207297
 cosmetic: 140837
 scriptlet: 37499
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://easylist.to/easylist/easylist.txt: 65478-16855, 2d.17h.22m
  adguard-annoyance: 67468-1764, 3d.14h.26m
  adguard-generic: 70411-1734, 3d.14h.25m
  adguard-mobile: 8679-92, 3d.14h.24m
  adguard-social: 20315-1985, 3d.14h.23m
  adguard-spyware-url: 1000-3, 2d.17h.22m
  block-lan: 46-0, 20d.11h
  curben-phishing: 76628-2, 21h.56m
  curben-pup: 199-0, 21h.55m
  dpollock-0: 11354-316, 8d.23h.31m
  fanboy-thirdparty_social: 68-4, 21h.57m
  ublock-annoyances: 4954-202, 2d.17h.22m
 default: 
  user-filters: 28-0, never
  IDN-0: 5470-246, 3d.14h.27m
  easylist: 65465-65465, 2d.17h.22m
  easyprivacy: 30880-1495, 2d.17h.22m
  plowe-0: 3749-1388, 7d.8h.47m
  ublock-abuse: 70-0, 7d.16h.40m
  ublock-badware: 6828-372, 2d.17h.21m
  ublock-filters: 33944-4394, 2d.17h.21m
  ublock-privacy: 294-5, 7d.16h.36m
  ublock-quick-fixes: 205-40, 21h.54m
  ublock-unbreak: 1989-96, 2d.17h.21m
  urlhaus-1: 6918-3, 21h.53m
filterset (user): [array of 28 redacted]
trustedset: 
 added: [array of 66 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1355 ms (selfie)
 maxAssetCacheWait: 968 ms
popupPanel: 
 blocked: 16
 no-cosmetic-filtering: true
 network: 
  consensu.org: 1
  histats.com: 1
  netpub.media: 12
  push-sdk.net: 1
  taghaugh.com: 1
```
</details>

**Comment by mapx-** [comment]
report and discuss these kind of shorteners here:
https://github.com/uBlockOrigin/uAssets/discussions/17361
