### ISSUE TITLE
e-cancer.fr: breakage

### ISSUE THREAD

**Issue by lcmtpage** [uBlockOrigin/uAssets#17759]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.e-cancer.fr/`

### Category

breakage

### Description

Impossible to open the site
The error: 503 Service Unavailable
No server is available to handle this request. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.2
Firefox: 94
filterset (summary): 
  network: 109044
  cosmetic: 48857
  scriptlet: 17894
  html: 953
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34893-47, 1h.24m
    ublock-badware: 6866-1, 1h.23m
    ublock-privacy: 370-0, 1h.28m
    ublock-abuse: 70-0, 1h.27m
    ublock-unbreak: 2010-1, 1h.22m
    easylist: 65496-621, 1h.21m
    easyprivacy: 30897-1770, 1h.20m
    urlhaus-1: 6769-1, 1h.18m
    plowe-0: 3746-2, 1h.29m
    FRA-0: 28735-615, 1h.25m
    ublock-quick-fixes: 215-30, 1h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 626 ms (selfie)
  maxAssetCacheWait: 201 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by ghajini** [comment]
> Impossible to open the site The error: 503 Service Unavailable No server is available to handle this request.
  http error,try later

**Comment by mapx-** [comment]
all fine now - chrome / firefox
