### ISSUE TITLE
drikpanchang.com: ads

### ISSUE THREAD

**Issue by nir2594** [uBlockOrigin/uAssets#17758]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.drikpanchang.com/planet/position/planetary-positions-sidereal.html`

### Category

ads

### Description

some remaning ad element is always left on the website. Can't seem to get rid of that ugly rectangular box

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 95157
 cosmetic: 47255
 scriptlet: 17796
 html: 0
listset (total-discarded, last-updated): 
 added: 
  IND-0: 12642-0, 1h.58m
 default: 
  user-filters: 1-0, never
  easylist: 65463-47, 1d.11h.55m
  easyprivacy: 30882-1180, 1d.11h.54m
  plowe-0: 3748-939, 9d.14h.33m
  ublock-abuse: 70-0, 1d.11h.53m
  ublock-badware: 6832-120, 1d.11h.52m
  ublock-filters: 33935-105, 1d.11h.51m
  ublock-privacy: 320-3, 1d.11h.50m
  ublock-quick-fixes: 210-16, 17h.17m
  ublock-unbreak: 1993-44, 1d.11h.49m
  urlhaus-1: 6741-1, 17h.16m
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1154 ms (selfie)
 maxAssetCacheWait: 478 ms
popupPanel: 
 blocked: 11
 network: 
  facebook.com: 1
  google.com: 5
  googlesyndication.com: 1
  googletagmanager.com: 2
  twitter.com: 2
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by ghajini** [comment]
@mediumkreation

`drikpanchang.com##.dpAdSection`

**Comment by ghajini** [comment]
https://github.com/mediumkreation/IndianList/commit/ca08bcbbf2c198ea1b7b8ae71d6fa917c26c6abb

update filter lists

**Comment by nir2594** [comment]
Thanks for such a quick response. Appreciate it <3
