### ISSUE TITLE
digitask.ru: detection

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#17756]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://digitask.ru/`

### Category

detection

### Description

These two rules are bait for me.
`##.AdSense` ~> **EasyList**
`##.advblock` ~> **RU AdList**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-04-24_084800](https://user-images.githubusercontent.com/111344219/233910008-bc72b0ba-bf4b-4d7f-9700-23cf1f22f115.png)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 106029
 cosmetic: 129599
 scriptlet: 24358
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  urlhaus-1: null
  plowe-0: null
 added: 
  https://easylist-downloads.adblockplus.org/bitblock.txt: 28894-20, 2m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1601-25, 2m
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 913-0, 2m
  fanboy-cookiemonster: 46746-388, 4m
  ublock-annoyances: 4957-54, 4m
 default: 
  user-filters: 1-0, never
  ublock-filters: 33992-44, 4m
  ublock-badware: 6867-0, 4m
  ublock-privacy: 322-4, 4m
  ublock-abuse: 70-0, 4m
  ublock-unbreak: 1994-7, 4m
  ublock-quick-fixes: 210-18, 4m
  easylist: 65542-259, 4m
  easyprivacy: 30897-1524, 2m
  RUS-0: 39724-303, 2m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
modifiedHiddenSettings: 
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats: 
 allReadyAfter: 1125 ms (selfie)
 maxAssetCacheWait: 590 ms
popupPanel: 
 blocked: 22
 network: 
  digitask.ru: 1
  a-ads.com: 1
  addthis.com: 1
  arc.io: 2
  cloudflareinsights.com: 1
  coinzillatag.com: 2
  ctengine.io: 1
  doubleclick.net: 2
  googletagmanager.com: 2
  linkslot.ru: 1
  yadro.ru: 1
  youtube.com: 7
```
</details>

**Comment by dportvine** [comment]
This is not a RU site.

**Comment by dimisa-RUAdList** [comment]
Indeed, this is not a Russian site.
