### ISSUE TITLE
lequipe.fr [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1775]
URL(s) where the issue occurs

`https://www.lequipe.fr/Cyclisme-sur-route/Actualites/Niki-terpstra-gagne-a-harelbeke-et-recompense-la-formation-quick-step-floors/886664`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by mapx-** [comment]
try
```
lequipe.fr##.ab-full-wrapper
lequipe.fr##[rel="stylesheet"][type="text/css"] + * + DIV > DIV:first-child
```

**Comment by KiLL4FuNK** [comment]
@mapx- It works perfect

**Comment by mapx-** [comment]
the second filter could be 
`lequipe.fr##STYLE + * > :first-child:matches-css(z-index: 1)`

**Comment by garry-ut99** [comment]
(no AA for me with `ghide` off) Many big ad placeholders caused by `ghide` from "uBlock filters": [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217843540-22139186-6e9e-4468-a35c-65ab91dc596f.png)
