### ISSUE TITLE
gaslicht.com: ads

### ISSUE THREAD

**Issue by gitom2** [uBlockOrigin/uAssets#17760]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gaslicht.com/energievergelijken/resultaten`

### Category

ads

### Description

Top result is an add. Labeled as such.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![Schermafbeelding 2023-04-24 om 13 02 54](https://user-images.githubusercontent.com/105607373/233979484-c4456dc3-7300-4be1-9217-119eaba4f50d.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 90642
  cosmetic: 41853
  scriptlet: 17769
  html: 954
listset (total-discarded, last-updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 34816-74, now
    ublock-badware: 6871-0, now
    ublock-privacy: 372-0, now
    ublock-abuse: 70-0, now
    ublock-unbreak: 2004-5, now
    ublock-quick-fixes: 209-0, now
    easylist: 65542-632, now
    easyprivacy: 30897-1764, now
    urlhaus-1: 6769-1, now
    plowe-0: 3746-3, now
    NLD-0: 2580-21, now
filterset (user): [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1786 ms (selfie)
  maxAssetCacheWait: 735 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
@BPower0036

**Comment by BPower0036** [comment]
Fixed
