### ISSUE TITLE
enlace-protegido.com: detection

### ISSUE THREAD

**Issue by jmtvila** [uBlockOrigin/uAssets#17762]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://enlace-protegido.com/`

### Category

detection

### Description

Mensaje en la página y recargue esta página nuevamente

`https://enlace-protegido.com/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 93884
 cosmetic: 40594
 scriptlet: 34904
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt: 178-6, never
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24147-12, 17h.36m
 default: 
  user-filters: 0-0, never
  easylist: 65496-49, 17h.37m
  easyprivacy: 30882-1182, 17h.37m
  plowe-0: 3746-939, 17h.37m
  ublock-abuse: 70-1, 17h.37m
  ublock-badware: 6853-120, 17h.37m
  ublock-filters: 33996-2708, 17h.37m
  ublock-privacy: 320-3, 17h.37m
  ublock-quick-fixes: 210-16, 17h.37m
  ublock-unbreak: 1999-45, 17h.37m
  urlhaus-1: 6741-1, 17h.37m
filterset (user): [empty]
trustedset: 
 removed: 
  chrome-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4403 ms (selfie)
 maxAssetCacheWait: 439 ms
popupPanel: 
 blocked: 1
 network: 
  googlesyndication.com: 1
```
</details>

**Comment by mapx-** [comment]
invalid: provide the original page where you want to get some download, explain the steps to get the issue.

comment here if you are able to provide the requested info (do not open other issue)
