### ISSUE TITLE
reuters.com anti-adblock

### ISSUE THREAD

**Issue by narcolepticinsomniac** [uBlockOrigin/uAssets#1776]
`https://www.reuters.com/article/us-spotify-advertising/spotify-says-about-two-million-users-blocked-ads-without-paying-idUSKBN1GZ1WK`

Chromium 64.0.3282.140

Tested with just Easylist. All main content is removed. Inline script is the cause, since blocking them reveals hidden content. Blocking them altogether does break some other features, so if someone can make a better filter, that'd be preferable.

**Comment by mapx-** [comment]
I can see other pages, only this 1 is broken. So, it seems to be a page issue.

**Comment by narcolepticinsomniac** [comment]
Hmm, that's so weird that it never even occurred to me. Suppose you can close it if that's the case.

**Comment by mapx-** [comment]
Even disabling uBo I'm not able to see the page.
