### ISSUE TITLE
fingerprint.com: privacy

### ISSUE THREAD

**Issue by ACK-J** [uBlockOrigin/uAssets#17765]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This analytics domain is playing a game of cat and mouse. Each time we add it to a block list https://github.com/uBlockOrigin/uAssets/issues/17652 they increment the number of the subdomain.

The analytics server has now changed again to be `analytics4.dashboard.fingerprint.com`. I propose we add a regex wildcard for any number that they choose 

### URL(s) where the issue occurs.

https://fingerprint.com

### uBO version

1.48.4

### Browser name and version

Firefox 110

### Settings

N/A

**Comment by JobcenterTycoon** [comment]
You can post your comments in the closed issue https://github.com/uBlockOrigin/uAssets/issues/17652

The tracking is blocked by `||fingerprint.com^$strict3p,domain=fingerprint.com` in the uBO quick list. https://github.com/uBlockOrigin/uAssets/commit/034b812eaf45dbc540bc7493ac2602f16b55ddb8
