### ISSUE TITLE
一样的ublock版本在edge和chrome上面效果却不一样

### ISSUE THREAD

**Issue by cattle891240** [uBlockOrigin/uAssets#17773]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

在chrome浏览器使用淘宝的搜索，可以关掉网站带来的广告内容，但是在edge以相同的词条进行搜索，无法阻挡那些广告

### URL(s) where the issue occurs.

`https://s.taobao.com/search?commend=all&ie=utf8&initiative_id=tbindexz_20170306&page=1&q=%E7%A9%BA%E6%B0%94%E7%82%B8%E9%94%85&search_type=item&sourceId=tb.index&spm=a21bo.jianhua.201856-taobao-item.2&ssid=s5-e`

### Screenshot(s)

https://user-images.githubusercontent.com/68153246/234200435-a86b7225-a65c-4a22-88a0-d9042251ddcd.png
https://user-images.githubusercontent.com/68153246/234200541-e6634aeb-73e0-4432-86a2-534d5c75fa23.png

### uBO version

1.49

### Browser name and version

chrome112.0.5615.138     EDGE112.0.1722.58

### Settings

nothing

**Comment by mapx-** [comment]
try reporting here:

https://github.com/cjx82630/cjxlist/issues
