### ISSUE TITLE
ikandy.fun: detection

### ISSUE THREAD

**Issue by Mionx-II** [uBlockOrigin/uAssets#17775]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The advertising blocking function has been detected, and the website prompts that the advertising blocking function needs to be turned off.

### URL(s) where the issue occurs.

```
https://ikandy.fun/vodplay/107964-1-2/
https://ikandy.fun/vodplay/106584-6-1/
```

### Screenshot(s)

https://user-images.githubusercontent.com/49855013/234274763-8720d9fb-9206-4c45-b687-9183b8bad5f5.png

### uBO version

uBlock Origin 1.49.0

### Browser name and version

Google Chrome 111.0.5563.147

### Settings

default setting

**Comment by mapx-** [comment]
```
This site can’t be reachedThe webpage at https://www.ikandy.fun/ might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR
```

**Comment by Mionx-II** [comment]
> This site can’t be reached
> The webpage at https://www.ikandy.fun/ might be temporarily down or it may have moved permanently to a new web address.
> ERR_HTTP2_PROTOCOL_ERROR

This website blocks IP addresses outside Chinese Mainland

**Comment by mapx-** [comment]
Well, in this case you should ask for help here:

https://github.com/cjx82630/cjxlist/issues

**Comment by cjx82630** [comment]
It's fine with ABP using the following rules. Not sure the ADG
> qcheng.cc#@#.google-ad
@@||qcheng.cc/x/statics/js/guanggao.

**Comment by mapx-** [comment]
@Mionx-II 

could you test adding:

```
qcheng.cc#@#.google-ad
@@||qcheng.cc/x/statics/js/guanggao
```

**Comment by Mionx-II** [comment]
@mapx- 
This doesn't work

> @Mionx-II
> 
> could you test adding:
> 
> ```
> qcheng.cc#@#.google-ad
> @@||qcheng.cc/x/statics/js/guanggao.
> ```
> 
> or just updating the regional list

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Mionx-II** [comment]
@mapx- ![image](https://user-images.githubusercontent.com/49855013/234610671-afc0e1a8-fd53-4fed-ae53-a7f0f07e009c.png)
I ensure that I have completed the above steps and added rules, but it has not worked.

> * clear cookies / localStorage/ cache for the tested page
> * reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> * disable any custom filter for that site
> * disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> * if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
> * disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> * are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
> * restart the system, reopen the browser, test again.

**Comment by Mionx-II** [comment]
> Try this `qcheng.cc##+js(aopr,killAdKiller)`

@cjx82630 
It worked. Thank you very much
