### ISSUE TITLE
truyengihotne.com: popups

### ISSUE THREAD

**Issue by tetoksn** [uBlockOrigin/uAssets#17779]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://truyengihotne.com/`

### Category

popups

### Description

After scrolling for around 3-5 minutes, this website has hidden overlays that direct me to other websites although i have turned on popup blocker setting

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium Mobile: 112
filterset (summary): 
 network: 213195
 cosmetic: 224866
 scriptlet: 39617
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67507-94, 2d.23h.29m
  adguard-generic: 70541-588, 2d.23h.29m
  adguard-social: 20326-857, 2d.23h.29m
  adguard-spyware-url: 999-3, 2d.23h.29m
  block-lan: 47-0, 2d.23h.10m
  curben-phishing: 80877-2, 21h.18m
  curben-pup: 199-0, 21h.19m
  dpollock-0: 11355-82, 2d.23h.29m
  fanboy-annoyance: 77226-6434, 2d.23h.29m
  fanboy-cookiemonster: 46730-46730, 2d.23h.29m
  fanboy-social: 18498-18498, 2d.23h.29m
  fanboy-thirdparty_social: 69-18, 2d.23h.29m
  ublock-annoyances: 5014-273, 2d.23h.29m
 default: 
  user-filters: 1-0, never
  VIE-1: 1904-0, 21h.22m
  adguard-mobile: 8689-47, 3d.7h.55m
  easylist: 65465-1155, 3d.7h.54m
  easyprivacy: 30880-1491, 3d.7h.53m
  plowe-0: 3749-1389, 7d.19h.16m
  ublock-abuse: 70-0, 7d.19h.14m
  ublock-badware: 6826-373, 3d.7h.52m
  ublock-filters: 34147-4219, 3d.7h.51m
  ublock-privacy: 295-6, 7d.19h.10m
  ublock-quick-fixes: 215-23, 21h.21m
  ublock-unbreak: 1994-97, 3d.7h.50m
  urlhaus-1: 6786-3, 21h.20m
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 3 redacted]
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: false
 prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 34759 ms (selfie)
 maxAssetCacheWait: 4907 ms
popupPanel: 
 blocked: 6
 no-popups: true
 network: 
  truyengihotne.com: 1
  fagfmabinf.com: 1
  godpvqnszo.com: 1
  laversleopold.guru: 1
  ominateamt.com: 1
  syenitetatler.tech: 1
```
</details>

**Comment by mapx-** [comment]
add

```
truyengihotne.com##+js(nowoif)
*$xhr,domain=truyengihotne.com,3p
```

@hoang-rio

**Comment by tetoksn** [comment]
It works. Thanks a lot =))
