### ISSUE TITLE
wifi4games.com: ads

### ISSUE THREAD

**Issue by Ahmed-md1** [uBlockOrigin/uAssets#17770]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wifi4games.com/`

### Category

ads

### Description

there is an ad when i enter the page i cant click on anything 
when i click it pops-up another page then i can click on the items on the page 
another thing ther is an nsfw ad blocks pop up on the screen in the lower right of the page 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 1
 cosmetic: 1
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated): [none]
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 24 redacted]
switchRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 738 ms (selfie)
 maxAssetCacheWait: 13 ms
popupPanel: 
 blocked: 2
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 network: 
  wifi4games.com: 2
 cosmetic: 
  ##html > iframe
```
</details>

**Comment by peace2000** [comment]
It seems that you don't have filter lists enabled. Please restore the default settings in uBlock.

**Comment by peace2000** [comment]
It seems that your uBlock installation suffers from this bug: https://github.com/uBlockOrigin/uBlock-issues/issues/2604

**Comment by gorhill** [comment]
Click _Purge all caches_ and _Update now_ in _Filter lists_ pane.

**Comment by gorhill** [comment]
Leave `bug` label please, this is a malfunction, not an invalid report.
