### ISSUE TITLE
dwturkce.com: ads

### ISSUE THREAD

**Issue by uuqqzz** [uBlockOrigin/uAssets#17771]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dwturkce.com/en/germany-airport-strikes-hit-berlin-hamburg/a-65415471`

### Category

ads

### Description

`dwturkce.com##.advertisement`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://user-images.githubusercontent.com/110184059/234140995-e30a0a3a-e3ec-4b98-8baa-693d0dd108e9.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 132866
  cosmetic: 161270
  scriptlet: 36191
  html: 953
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 43359-15376, 58m
    adguard-generic: 70614-6227, 58m
    adguard-spyware-url: 999-5, 58m
    adguard-annoyance: 67577-1584, 58m
    adguard-social: 20336-32, 58m
  default: 
    user-filters: 63-0, never
    ublock-filters: 34862-94, 58m
    ublock-badware: 7009-0, 58m
    ublock-privacy: 372-0, 58m
    ublock-abuse: 70-0, 58m
    ublock-unbreak: 2004-5, 58m
    ublock-quick-fixes: 208-0, 58m
    easylist: 65576-335, 58m
    easyprivacy: 30897-1184, 58m
    TUR-0: 12304-12, 58m
filterset (user): [array of 65 redacted]
modifiedUserSettings: 
  contextMenuEnabled: false
  prefetchingDisabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: false
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 705 ms (selfie)
  maxAssetCacheWait: 428 ms
  unsuspendAfter: 190 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
