### ISSUE TITLE
momondo.no: ads

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#17780]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.momondo.no/flight-search/MUC-BER/2023-07-18/2023-07-24?sort=bestflight_a`

### Category

ads

### Description

ads as shown in picture. 

### Screenshot(s)

![Screenshot 2023-04-25 202252](https://user-images.githubusercontent.com/19490515/234367956-5cc47ef8-d6fd-42ff-960d-0f9fe5b46960.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 178122
  cosmetic: 84820
  scriptlet: 19771
  html: 954
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2178-0, 13m
    adguard-spyware-url: 999-140, 17m
    block-lan: 47-0, 11d.19h.38m
    curben-phishing: 81731-36, 11m
    curben-pup: 193-0, 15m
    fanboy-cookiemonster: 46770-215, never
    NOR-0: 3144-9, 12m
  default: 
    user-filters: 3-0, never
    ublock-filters: 34845-55, 22m
    ublock-badware: 6956-0, 21m
    ublock-privacy: 372-2, 20m
    ublock-abuse: 70-0, 19m
    ublock-unbreak: 2004-2, 18m
    ublock-quick-fixes: 203-0, 10m
    easylist: 65576-629, 23m
    easyprivacy: 30897-1761, 16m
    urlhaus-1: 6943-1, 14m
    plowe-0: 3749-3, 11d.19h.37m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5382 ms
  maxAssetCacheWait: 496 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    momondo.no: 3
    google-analytics.com: 1
    googletagmanager.com: 1
    googletagservices.com: 1
    usabilla.com: 1
```
</details>

**Comment by mapx-** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
I can reproduce very similar ads on some other international site versions too, so I think `momondo.*##div[data-resultid$=-sponsored]` should be added to uBlock Filters or to another major list:
```
https://www.momondo.de/flight-search/MUC-BER/2023-07-18/2023-07-24?sort=bestflight_a
https://www.momondo.pt/flight-search/MUC-BER/2023-07-18/2023-07-24?sort=bestflight_a
https://www.momondo.it/flight-search/MUC-BER/2023-07-18/2023-07-24?sort=bestflight_a
```
