### ISSUE TITLE
[nsfw] xhamster.com: breakage

### ISSUE THREAD

**Issue by starsaa** [uBlockOrigin/uAssets#17785]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://xhamster.com/`

### Category

breakage

### Description

When on, most items on page are not clickable, menu, movie thumbs, load more, play, etc. Movie thumbs do not load, just blured squars. When i turn off ublock then everything works, including ads and crap. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox Mobile: 114
filterset (summary): 
  network: 91645
  cosmetic: 30233
  scriptlet: 17872
  html: 991
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 35122-300, 1d.5h.43m
    ublock-badware: 6983-1, 1d.6h.27m
    ublock-privacy: 344-1, 11d.8h.24m
    ublock-abuse: 70-0, 11d.8h.23m
    ublock-unbreak: 2009-5, 1d.5h.42m
    ublock-quick-fixes: 208-0, 22h.56m
    adguard-mobile: 8691-120, 2d.1h.9m
    easylist: 65597-17462, 22h.57m
    easyprivacy: 30897-1779, 1d.6h.28m
    urlhaus-1: 6916-1, 22h.55m
    plowe-0: 3749-1, 6d.10h.19m
filterset (user): [empty]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  colorBlindFriendly: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1291 ms (selfie)
  maxAssetCacheWait: 863 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    forjoiyvidspics.site: 1
    googletagmanager.com: 1
    tsyndicate.com: 2
```
</details>

**Comment by starsaa** [comment]
Update: On Win 10 desktop with Firefox and uBlock running, this site does work as normal. Seems to just be the Android ver. Desktop and Phone are synced and both are up to date.

**Comment by mapx-** [comment]
Update all filter lists and test again

**Comment by ghajini** [comment]
A) its caused by `xhamster.*##^script:has-text(popunder)`
@starsaa ,clear cookie/data then add this in your filters
`xhamster.*#@#^script:has-text(popunder)`

B)such occurance = https://github.com/uBlockOrigin/uAssets/commit/6f103d104909be8058f4a8ae0b5fc1b9c7934f4d

this should be removed = 
`fullxh.com,hamsterix.*,megaxh.com,unlockxh4.com,xhadult2.com,xhadult3.com,xhamster.*,xhamster1.*,xhamster10.*,xhamster11.*,xhamster12.*,xhamster13.*,xhamster14.*,xhamster15.*,xhamster16.*,xhamster17.*,xhamster18.*,xhamster19.*,xhamster2.*,xhamster3.*,xhamster4.*,xhamster46.com,xhamster5.*,xhamster7.*,xhamster8.*,xhday.com,xhday1.com,xhmoon5.com,xhplanet1.com,xhplanet2.com,xhreal2.com,xhtab2.com,xhvictory.com,xhwebsite.com,xhwebsite2.com,xhwide1.com,xhwide8.com##^script:has-text(popunder)`

**Comment by mapx-** [comment]
@ghajini or keep it only for desktop ?

**Comment by ghajini** [comment]
i will test on desktop sooner

**Comment by stephenhawk8054** [comment]
On mobile there's an object for the popunder `initials["yxd-jdpopunder"]`. I forget how to set the value for the objects with `"`. Anyone remember how to do it?

**Comment by mapx-** [comment]
even on FF desktop, that filter is breaking the site

**Comment by stephenhawk8054** [comment]
I think we can replace it with `##+js(set, initials.yxd-jdpopunder, '')`

**Comment by mapx-** [comment]
yes, they continuously changing it

**Comment by stephenhawk8054** [comment]
Yeah, they bundle other information into 1 inline script, so removing it will cause breakages.

**Comment by ghajini** [comment]
can be considered fixed,no new ads as such

**Comment by starsaa** [comment]
Works.. THX

**Comment by 0calsweetener** [comment]
broken video on my side

**Comment by stephenhawk8054** [comment]
> broken video on my side

Can you give an exact link and describe what happens in more details?

**Comment by ghost** [comment]
If you enter a profile, the section showing the newest added videos doesn't show nothing if uBO is on.
https://github.com/user-attachments/assets/6d75b558-2dda-4d43-b87c-8f3b7f811540

If uBO is off, it does show:
https://github.com/user-attachments/assets/7b7ee3e3-6387-40d6-82d1-55b76a76b603

<details>

```yaml
uBlock Origin: 1.66.2
Chromium Mobile: 139
filterset (summary):
 network: 177241
 cosmetic: 98363
 scriptlet: 35015
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 46258-106, 2d.1h.57m
  ublock-cookies-easylist: 5094-47, 2d.1h.57m
  FRA-0: 19316-267, 6h.11m
 default:
  user-filters: 3-0, never
  ublock-filters: 41269-76, 5h.20m Δ
  ublock-badware: 11224-31, 5h.20m Δ
  ublock-privacy: 3471-3, 5h.20m Δ
  ublock-unbreak: 2682-15, 12m Δ
  ublock-quick-fixes: 308-8, 6h
  adguard-mobile: 11344-146, 1d.7h.47m
  easylist: 79785-185, 5h.20m Δ
  easyprivacy: 54489-149, 5h.20m Δ
  urlhaus-1: 33000-5, 49m
  plowe-0: 3418-980, 2d.1h.59m
  ROU-1: 1556-23, 1d.7h.36m
filterset (user): [array of 3 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 520 ms
 maxAssetCacheWait: 287 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 3
 network:
  xhamster.com: 1
  google.com: 1
  googletagmanager.com: 1
 extended:
  ##ul.thumb-list-mobile > :not(.thumb-list-mobile-item--type-vide…
  ##div[data-role="promo-messages-wrapper"]
  ##+js(set-cookie-reload, pShowMob, true)
  ##+js(set-cookie, cookie_accept, 1)
  ##+js(remove-cookie, video_view_count)
  ##+js(addEventListener-defuser, click, [native code], elements, …
  ##+js(trusted-replace-node-text, script, popunder, '', condition…
  ##+js(set-cookie, ts_popunder, true, '', reload, 1)
  ##+js(set-constant, initials.yld-pdpopunder, '')
```

</details>
