### ISSUE TITLE
cbssports.com: breakage

### ISSUE THREAD

**Issue by braves23** [uBlockOrigin/uAssets#17783]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cbssports.com/mlb/video/boomer-and-gio-max-scherzer-is-in-for-another-rude-awakening/`

### Category

breakage

### Description

Having trouble getting the video to load on this page. 

`https://www.cbssports.com/mlb/video/boomer-and-gio-max-scherzer-is-in-for-another-rude-awakening/`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 100
filterset (summary): 
  network: 98064
  cosmetic: 41557
  scriptlet: 17892
  html: 953
listset (total-discarded, last-updated): 
  added: 
    https://curben.gitlab.io/malware-filter/urlhaus-filter-online.txt: 0-0, never
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, 1d.3h.11m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 150d.17h.20m
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt: 8425-1, 1h.50m
  default: 
    user-filters: 364-0, never
    ublock-filters: 34816-73, 1d.7h.16m
    ublock-badware: 6857-0, 1d.7h.15m
    ublock-privacy: 344-0, 10d.1h.54m
    ublock-abuse: 70-0, 10d.1h.53m
    ublock-unbreak: 2010-2, 1d.7h.14m
    ublock-quick-fixes: 208-4, 1h.53m
    easylist: 65515-636, 1d.7h.18m
    easyprivacy: 30891-1181, 1d.7h.19m
    urlhaus-1: 6943-1676, 1h.51m
    plowe-0: 3746-596, 4d.17m
filterset (user): [array of 364 redacted]
trustedset: 
  added: [array of 22 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 230904 ms (selfie)
  maxAssetCacheWait: 2685 ms
popupPanel: 
  blocked: 49
  blockedDetails: 
    cbssports.com: 1
    ads-twitter.com: 1
    agkn.com: 1
    amazon-adsystem.com: 1
    aswpsdkus.com: 1
    cbsaavideo.com: 4
    cbsi.com: 2
    cbsivideo.com: 15
    cedexis.com: 1
    chartbeat.com: 1
    confiant-integrations.net: 1
    doubleclick.net: 1
    getpublica.com: 1
    google-analytics.com: 1
    googletagmanager.com: 1
    imrworldwide.com: 1
    liadm.com: 3
    moatads.com: 1
    mtvnservices.com: 1
    ns1p.net: 3
    optimizely.com: 1
    qualtrics.com: 1
    rum.us-east-1.amazonaws.com: 1
    scorecardresearch.com: 2
    taboola.com: 1
    tealiumiq.com: 1
```
</details>

**Comment by peace2000** [comment]
Hi, you should remove these two lists:

`https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt:`
`https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt`

They are unmaintained, legacy lists that can cause issues.
