### ISSUE TITLE
gayvids.tube: detection

### ISSUE THREAD

**Issue by snobams** [uBlockOrigin/uAssets#17787]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gayvids.tube/the-write-way-trevor-brooks-and-zak-bishop/`

### Category

detection

### Description

adblock detected gayvids.tube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 173781
 cosmetic: 6
 scriptlet: 40553
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://cdn.jsdelivr.net/gh/bmyjacks/adlists@master/filter-registry/AdGuard-Base-filter.txt: 122680-75330, 2h.31m
  adguard-annoyance: 67630-59751, 2h.31m
  adguard-generic: 70660-43929, 2h.31m
  adguard-social: 20352-19741, 2h.31m
  adguard-spyware-url: 999-10, 2h.31m
  dpollock-0: 11355-194, 2h.31m
  fanboy-annoyance: 91134-83976, 2h.31m
  fanboy-thirdparty_social: 68-18, 2h.31m
  ublock-annoyances: 4965-1584, 2h.31m
 default: 
  user-filters: 13-0, never
  RUS-0: 39721-21265, 2h.31m
  easylist: 65830-43312, 2h.31m
  easyprivacy: 30897-1567, 2h.31m
  plowe-0: 3746-1342, 2h.31m
  ublock-abuse: 70-2, 2h.31m
  ublock-badware: 6952-1019, 2h.31m
  ublock-filters: 33641-12355, 2h.31m
  ublock-privacy: 322-8, 2h.31m
  ublock-quick-fixes: 210-80, 2h.31m
  ublock-unbreak: 1999-321, 2h.31m
  urlhaus-1: 7286-1, 2h.31m
filterset (user): [array of 14 redacted]
trustedset: 
 added: [array of 86 redacted]
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 15 redacted]
hostRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3667 ms (selfie)
 maxAssetCacheWait: 276 ms
popupPanel: 
 blocked: 12
 network: 
  appcdn01.xyz: 2
  cloudflare.com: 7
  disqus.com: 1
  facebook.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by ghajini** [comment]
RuAdlist
`||xyz^$script,3p,from=~anidub.com|~anidub.vip|~anidubonline.com|~animedia.pro|~animeheaven.ru|~animevibe.wtf|~app.element.io|~assistir-filme.biz|~auth.magic.link|~avtomaty-i-bonusy.com|~badgirlsdrop.com|~baza.bz|~bdnewszh.com|~capshd.xyz|~cdnmovies.be|~cdnmovies.cc|~cdnmovies.nl|~coomeet.com|~cozy.tv|~crackstreams.com|~crackstreams.ga|~csgoreports.com|~cubeshot.io|~emblix.cc|~espnfree.xyz|~estream.to|~europixhd.io|~films.hds-stream.com|~flowcdn.nl|~fyshare.info|~getvi.tv|~github.io|~gsmware.com|~hanime.tv|~hentaiz.org|~herokuapp.com|~infoua.biz|~jokehd.com|~jokerswidget.com|~jokerswidget.org|~kinoguru.be|~kinoguru.me|~live-nhl.stream|~live94today.com|~lookbase.xyz|~lyra.finance|~mail.google.com|~mangahere.fit|~map-a-date.cc|~mas-stream2021.xyz|~matchat.online|~mikeamigorein.xyz|~milfnut.net|~miranimbus.ru|~my.mail.ru|~nccg.ru|~newdmn.icu|~odysee.com|~onmovies.se|~playjoke.xyz|~playm4u.xyz|~playmuvi.com|~realtime-chart.info|~roadhub.ru|~roblox.com|~rou.video|~sekai-kabuka.com|~sextop.net|~soccer365.ru|~soonwalk.net|~sportsbay.org|~streetbee.io|~streetbee.ru|~telerium.club|~telerium.live|~uacycling.info|~uploadedpremiumlink.net|~vercel.app|~vk-apps.com|~vk.com|~vmeste.tv|~web.app|~webflow.io`

blocking` https://appcdn01.xyz/vast.js`
@snobams disable RUadlist on non-russian site or wait for feedback from russian filter list maintainer

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by ghajini** [comment]
not a good way,when he updates the rule, badfilter will become nonuseful

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/1918c8d23d133b905a7135b9506481a6d766cd82

**Comment by dimisa-RUAdList** [comment]
The problem is that only some of the Russian sites use the .ru domain zone.

Mention of domain zones in RU AdList (classic):
ru - 18156
com - 7651
net - 2297

However, the general blocking of third-party network requests in the xyz domain zone has been contained in the filter for a long time, and advertisers have practically ceased to use it for their own purposes.

I'm going to summarize the hit statistics over the course of the week to see if the current rule makes sense.
