### ISSUE TITLE
steamgifts.com: ads

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#17791]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.steamgifts.com/`

### Category

ads

### Description

An ad at the bottom of the left-hand side menu and between giveaways.

Adding `www.steamgifts.com##div.dont_block_me` seems to block them.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://user-images.githubusercontent.com/22180480/234532154-785e36ad-a583-4ce1-b461-b6a4e5aeefa9.png)
![obraz](https://user-images.githubusercontent.com/22180480/234532262-236202c0-d09f-4155-b324-341e94d47ff6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 92078
  cosmetic: 47654
  scriptlet: 17778
  html: 960
listset (total-discarded, last-updated): 
  default: 
    user-filters: 28-0, never
    ublock-filters: 34560-93, 1h.58m
    ublock-badware: 6956-1, 1h.58m
    ublock-privacy: 373-0, 1h.58m
    ublock-abuse: 70-0, 1h.58m
    ublock-unbreak: 2010-2, 1h.58m
    ublock-quick-fixes: 203-0, 1h.58m
    easylist: 65836-649, 1h.58m
    easyprivacy: 30898-1762, 1h.58m
    urlhaus-1: 7286-1, 1h.58m
    plowe-0: 3746-2, 1h.58m
    POL-0: 7937-24, 1h.57m
    POL-2: 1278-12, 1h.57m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 31 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 776 ms
  maxAssetCacheWait: 310 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    nitropay.com: 2
```
</details>

**Comment by mapx-** [comment]
@ryanbr
