### ISSUE TITLE
japscan.lol: ads

### ISSUE THREAD

**Issue by Ever4engel** [uBlockOrigin/uAssets#17796]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.japscan.lol/lecture-en-ligne/oshi-no-ko/116/`

### Category

ads

### Description

i see some ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/47645041/234602345-c949a565-ce9b-4d89-83fd-44d49a93dd04.png)
![image](https://user-images.githubusercontent.com/47645041/234602416-b208ffba-4c8b-4219-bf84-cf80525f1cb7.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 163615
  cosmetic: 227195
  scriptlet: 56362
  html: 1167
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 43364-4155, now
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2178-0, 14h.10m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24195-49, 18h.11m
    adguard-generic: 70684-7047, now
    adguard-annoyance: 67684-6946, now
    adguard-social: 20357-734, now
    fanboy-thirdparty_social: 69-0, 4d.12m
    fanboy-annoyance: 77226-65009, 4d.12m
    fanboy-cookiemonster: 46730-245, 4d.12m
    fanboy-social: 17992-17, now
    ublock-annoyances: 4930-4, now
    ara-0: 2778-0, 14h.11m
    adguard-spyware-url: 999-141, now
    block-lan: 47-0, 4d.12m
  default: 
    user-filters: 3-0, never
    ublock-filters: 34599-2748, 1m
    ublock-badware: 6956-0, 1m
    ublock-privacy: 373-2, 1m
    ublock-abuse: 70-0, 1m
    ublock-unbreak: 2010-0, 1m
    easylist: 65879-503, now
    easyprivacy: 30899-12393, now
    FRA-0: 28822-389, now
    ublock-quick-fixes: 208-4, 14h.9m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 8 redacted]
switchRuleset: 
  added: [array of 252 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  largeMediaSize: 512
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2848 ms (selfie)
  maxAssetCacheWait: 803 ms
popupPanel: 
  blocked: 5
  blockedDetails: 
    googletagmanager.com: 1
    hagboatdismast.com: 1
    jimjumsalkes.com: 1
    ko-fi.com: 2
```
</details>

**Comment by advertblocker** [comment]
https://github.com/uBlockOrigin/uAssets/blob/96064f678696b428ca5be4b4bf5f39f7af74e26a/filters/filters-2023.txt#L1984

@Yuki2718 does this fit the criteria for `AdGuard French Filter`?
