### ISSUE TITLE
badware - file download assistants - instalki / dobreprogramy

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#1779]
**`http://www.instalki.pl/programy/download/Windows/narzedzia_inne/Free_Alarm_Clock.html`**

<ul>

> ![obraz](https://user-images.githubusercontent.com/35370833/37855507-e311df32-2eef-11e8-98ab-c3d4f9eaa609.png) |
> ---|

> ![obraz](https://user-images.githubusercontent.com/35370833/37855541-01e22c28-2ef0-11e8-9ac3-a0903f00c221.png) |
> ---|

> _"Menadżer pobierania" (Download Assistant)_

```css
www.instalki.pl##option[value$="&dm=1"]
``` 

<ul>

possible better effect will provide remove element "`option`" from select list (no only hide `display: none !important`) - jump atomatic to second position as default and user no must change if no download other version (32 bit installer or portable).</ul></ul>

---

**`https://www.dobreprogramy.pl/Free-Alarm-Clock,Program,Windows,24929.html`**

<ul>

> ![obraz](https://user-images.githubusercontent.com/35370833/37855645-9c191e8c-2ef0-11e8-9db2-5f9d6c1b2f58.png) |
> --- |

> _"przy pomocy Asystenta pobierania" (using the download Assistant)_

> The Assistant can make a decision regarding the download of the offer. Leave action links behind without an assistant (next button). In the case of an unwanted installation of an unwanted user, they recommend this guide.

Right section "Linki do programu, bez Asystenta pobierania" (Links to the program, without Download Assistant) is safety.

```css
www.dobreprogramy.pl##article > .clearfix.grid-margin-px30-bottom
``` 

<ul> if no hide any other important element on website.</ul></ul>

**Comment by mapx-** [comment]
You should report here:
https://github.com/MajkiIT/polish-ads-filter/issues

**Comment by krystian3w** [comment]
Second is blocked [here](https://github.com/MajkiIT/polish-ads-filter/issues/6550) with `#?#article > .clearfix-abp-cointains(...)` (minimal "lag" (DOMContentLoaded) to no broke website - cut only badware button and paragraph). 

First my idea for `instalki` is no enough (select list no jump to safe position if "Menadżer Pobierania" is active).
