### ISSUE TITLE
post.ch: breakage

### ISSUE THREAD

**Issue by Toeoe6204** [uBlockOrigin/uAssets#17798]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.post.ch/de/hilfe-und-kontakt`

### Category

breakage

### Description

With uBO enabled it's no possible to start the chat (below). When I disable uBO there is an automatic forwarding to `https://www.post.ch/de/hilfe-und-kontakt-v1`, where the chat can be started.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.49.1b7: 
 since: 19h.50m
Firefox: 112
filterset (summary): 
 network: 92997
 cosmetic: 44637
 scriptlet: 17591
 html: 953
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34604-70, 3m
  ublock-badware: 6956-1, 3m
  ublock-privacy: 373-0, 3m
  ublock-abuse: 70-0, 3m
  ublock-unbreak: 2010-2, 3m
  ublock-quick-fixes: 209-0, 3m
  easylist: 65879-641, 3m
  easyprivacy: 30899-1771, 3m
  urlhaus-1: 7279-1, 3m
  plowe-0: 3746-2, 3m
  DEU-0: 6806-2, 3m
filterset (user): [empty]
trustedset: 
 added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 301 ms (selfie)
 maxAssetCacheWait: 83 ms
popupPanel: 
 blocked: 4
 network: 
  post.ch: 2
  googleoptimize.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=post.ch`

@ryanbr
