### ISSUE TITLE
applegadgetsbd.com: nuisance

### ISSUE THREAD

**Issue by BangladeshBank** [uBlockOrigin/uAssets#17790]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.applegadgetsbd.com/`

### Category

nuisance

### Description

Opening any page within this domain brings a pop-up. Blocking the pop-up was attempted through the element picker mode. After blocking the pop-up, the page doesn't respond until ESC button is pressed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 90932
 cosmetic: 116252
 scriptlet: 23630
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  urlhaus-1: null
 added: 
  adguard-annoyance: 67630-91, 11h.39m
  fanboy-social: 17991-26, 11h.39m
  ublock-annoyances: 4958-165, 21h.47m
 default: 
  user-filters: 0-0, never
  easylist: 65607-100, 22h.8m
  easyprivacy: 30897-1267, 11h.26m
  plowe-0: 3749-943, 9d.9h.31m
  ublock-abuse: 70-0, 10d.12h.26m
  ublock-badware: 6853-121, 2d.19h.4m
  ublock-filters: 34000-493, 22h.9m
  ublock-privacy: 295-3, 10d.12h.25m
  ublock-quick-fixes: 215-16, 22h.7m
  ublock-unbreak: 1993-45, 22h.10m
filterset (user): [empty]
trustedset: 
 added: [array of 180 redacted]
modifiedUserSettings: 
 hyperlinkAuditingDisabled: false
 largeMediaSize: 70
 prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 308 ms (selfie)
 maxAssetCacheWait: 56 ms
popupPanel: 
 blocked: 2
 network: 
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
remove your filter, add:

```
applegadgetsbd.com##.react-responsive-modal-root:has([src*="Banner"])
applegadgetsbd.com##body:style(overflow: auto !important;)
```

@ryanbr
