### ISSUE TITLE
index.hr News site won't play videos.

### ISSUE THREAD

**Issue by itisljar** [uBlockOrigin/uAssets#17803]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

1.49.0 at the time of writing.
Video news won't play when clicked, play button just greys out. As per previous problems, I've added HU and HR filter lists to default ones and tried with them, nothing happened.

This lasts for about a week now, maybe even longer.

### URL(s) where the issue occurs.

`https://www.index.hr/vijesti/clanak/stari-migovi-cesto-lete-i-probijaju-zvucni-zid-zasto-ako-stizu-rafalei/2458391.aspx?index_ref=naslovnica_vijesti_ostalo_d`

### uBO version

1.49.0

### Browser name and version

Google Chrome 112.0.5615.138

### Settings

Tried adding additional lists, but no help:

HRV, SRB: Dandelion Sprout's Serbo-Croatian filters
HUN: hufilter

**Comment by advertblocker** [comment]
@DandelionSprout

**Comment by Marko-98** [comment]
Video player not shown on the website at all.

URL: https://www.index.hr/vijesti/clanak/keleminec-dado-iz-smogovaca-i-ekipa-vikali-sotone-pogledajte-reakciju-iz-povorke/2799839.aspx

<details>
<summary>Screenshot</summary>

<img width="2559" height="1382" alt="Image" src="https://github.com/user-attachments/assets/2183ae8f-7f90-4098-86e8-a1734a5b0a6a" />

</details>

<details>
<summary>uBlock Origin configuration</summary>

```yaml
uBlock Origin: 1.71.0
Firefox: 151
filterset (summary):
 network: 195677
 cosmetic: 166278
 scriptlet: 65704
 html: 3806
listset (total-discarded, last-updated):
 added:
  adguard-generic: 96250-5809, now
  adguard-spyware-url: 2529-134, now
  block-lan: 91-0, now
  fanboy-cookiemonster: 46557-100, now
  ublock-cookies-easylist: 5673-46, now
  fanboy-social: 17676-16, now
  easylist-annoyances: 5211-64, now
  fanboy-ai-suggestions: 250-0, now
  easylist-newsletters: 9323-37, now
  easylist-notifications: 2506-177, now
  ublock-annoyances: 4931-103, now
  HRV-0: 526-110, now
 default:
  user-filters: 2-0, never
  ublock-filters: 52569-70, now
  ublock-badware: 10346-28, now
  ublock-privacy: 4028-2, now
  ublock-unbreak: 2830-1, now
  ublock-quick-fixes: 440-14, now
  easylist: 92753-1224, now
  easyprivacy: 55820-121, now
  urlhaus-1: 27035-11, now
  plowe-0: 3508-1039, now
filterset (user): [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1229 ms
 maxAssetCacheWait: 13 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  cloudflare.com: 1
  cloudflareinsights.com: 2
  criteo.net: 1
  dotmetrics.net: 1
  facebook.com: 2
  facebook.net: 1
  freshatl.azurewebsites.net: 2
  googlesyndication.com: 1
  permutive.app: 2
  pinterest.com: 3
  privacy-center.org: 1
  rubiconproject.com: 1
 extended:
  ##.facebook-bg
  ##.pin-it-button
  ##.ad-unit-text
  ##.comments-holder > .right-part
  ##[data-css-class="dfp-inarticle"]
  ##a[href^="http://pinterest.com/pin/create/"]
  ##a[href^="https://plus.google.com/share?"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##+js(trusted-set-cookie, euconsent-v2, CP_K6QAP_K6QAAHABBENA1Es…
  ##+js(set-constant, as_retry, 0)
  ##+js(remove-attr, onerror, script[id][onerror], asap stay)
  ##+js(trusted-replace-argument, HTMLScriptElement.prototype.setA…
  ##+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)",…
  ##+js(set-constant, navigator.globalPrivacyControl, false)
  ##+js(set-constant, Navigator.prototype.globalPrivacyControl, fa…
  #@#+js(trusted-replace-xhr-response, '/,"expanded_url":"([^"]+)"…
  #@#+js(json-prune-xhr-response, data.immersiveMedia.timeline.ins…
  #@#+js(json-prune-xhr-response, data.user.result.timeline_v2.tim…
  #@#+js(json-prune-xhr-response, data.threaded_conversation_with_…
  #@#+js(json-prune-xhr-response, data.search_by_raw_query.search_…
  #@#+js(json-prune-xhr-response, data.home.home_timeline_urt.inst…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||sdk.privacy-center.org/*.js$domain=index.hr
```

@ryanbr
