### ISSUE TITLE
player.pl: detection

### ISSUE THREAD

**Issue by andrzej928** [uBlockOrigin/uAssets#17801]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://player.pl/`

### Category

detection

### Description

detection ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 92139
  cosmetic: 68744
  scriptlet: 18167
  html: 1202
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt: 22415-51, 1d.17m
  default: 
    user-filters: 3-0, never
    ublock-filters: 34872-147, 2d.2h.18m
    ublock-badware: 6989-1, 2d.2h.17m
    ublock-privacy: 366-0, 7d.22h.42m
    ublock-abuse: 70-0, 7d.22h.41m
    ublock-unbreak: 2004-31, 2d.2h.19m
    easylist: 65515-556, 2d.2h.20m
    easyprivacy: 30880-1147, 4d.1h.46m
    urlhaus-1: 6943-1, 1d.15m
    plowe-0: 3746-595, 4h.51m
    POL-0: 7937-45, 1d.16m
    POL-2: 1278-12, 1d.18m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 28 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2096 ms (selfie)
  maxAssetCacheWait: 443 ms
popupPanel: 
  blocked: 10
  blockedDetails: 
    adocean.pl: 2
    gemius.pl: 5
    google-analytics.com: 1
    googletagmanager.com: 1
    newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
Did you test the page using only the default settings / filter lists ?
Did you disable all other addons / plugins during the test ?

Can you provide a link to a free show that does not require a subscription?

If there is no free show => if you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by mapx-** [comment]
@krystian3w do you have a `player.pl` account ? if you have one, can you reproduce the issue ?

**Comment by krystian3w** [comment]
Yes.

In Chromium for my side works:

```adb
! redirect anyway, due  I don't know what is bait/advert request/resource:
$xhr,redirect-rule=noopjs,domain=player.pl
!
! detect enabled EL:
!
player.pl#@#.adocean
player.pl#@#.reklama
!
! detect enabled MajkiIT POL-0:
player.pl#@#.reklama-top
player.pl#@#.linkSponsorowany
player.pl#@#.adv_container
player.pl#@#.adsense
player.pl#@#.ads
player.pl#@#.ad
```

Only 2 cosmetic filters are generic, so rest are checked mostly POL-0 filter where are used `pl##`.

cosmetic bait looks that:

```html
<div class="adsbygoogle prebid adocean ado ad ads advert banner reklama linkSponsorowany adsense advertisments reklama-top adv_container" style="position: absolute; top: 0px; left: 0px; opacity: 0; width: 0px; height: 0px;">adsbygoogle prebid adocean ado</div>
```

So possible use AdGuard idea:

```adb
player.pl#$#div.adsbygoogle.prebid.adocean.ado.ad.ads.advert.banner.reklama.linkSponsorowany.adsense.advertisments.reklama-top.adv_container { display: block !important }
```

**Comment by mapx-** [comment]
@krystian3w I didn't understand: **do you get the detection issue in chrome or not ?**

If you get a detection can you propose a fix ?

**Comment by krystian3w** [comment]
Yes, video won't play untill I redirect some xhr request/resources to empty files and disable cosmetic bait by 8 exceptions or CSS overrider in AdGuard style.

It seems to me that the best thing would be to specify what `xhr` we definitely need to redirect to `noopjs` instead all or scriptlet for which I have no idea (I don't feel like messing around with devtools debugger) cover both method detection.

**Comment by mapx-** [comment]
> video won't play untill I redirect some xhr request/resource(s) to empty files and disable cosmetic bait by 8 exceptions or CSS overrider in AdGuard style.

filters ?
the filters AG style will be converted in uBO style if you add them in uBO

**Comment by krystian3w** [comment]
In logger output you have all related redirected xhr after click in blue button "start watching": https://github.com/uBlockOrigin/uAssets/issues/17801#issuecomment-1525613799

Unfortunately, I do not know which resource/request are responsible for detecting the uBo to make the filter compatible with uBOL until willing to write a scriptlet to whip up two detection methods.

**Comment by mapx-** [comment]
are these filters working in uBO ?

```
$xhr,redirect-rule=noopjs,domain=player.pl
player.pl##div.adsbygoogle.prebid.adocean.ado.ad.ads.advert.banner.reklama.linkSponsorowany.adsense.advertisments.reklama-top.adv_container:style(display: block !important)
```

**Comment by krystian3w** [comment]
Yes, it work for me.

**Comment by advertblocker** [comment]
Why was `*` used for such filters before? (redirect-rule)

**Comment by andrzej928** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/1771441/234932998-ca7d0710-a627-4717-b05f-9712dff414af.jpg)

**Comment by advertblocker** [comment]
@andrzej928 

```
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=google-ima.js,domain=player.pl
```

**Comment by mapx-** [comment]
@andrzej928 
Test in chrome too.
I cannot test in firefox or chrome => I have no account / subscription.
You didn't answer to my question above:
https://github.com/uBlockOrigin/uAssets/issues/17801#issuecomment-1524804482

**Comment by andrzej928** [comment]
1. Did you test the page using only the default settings / filter lists ?

> yes, I clear all cookies, data, and other

3. Did you disable all other addons / plugins during the test ?

> I have only ublock

5. Can you provide a link to a free show that does not require a subscription?
6. If there is no free show => if you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

> No, I have one account
> If you register on website this is mayby free video
> https://player.pl/discovery-plus/truckerki-odcinki,27973/odcinek-1,S01E01,176139

Send giff with my settings

![GIF 2023-04-27 20-52-52](https://user-images.githubusercontent.com/1771441/234964410-229dd0c4-93cd-4055-889c-ead5136c334b.gif)

**Comment by mapx-** [comment]
That one isn't free. Still cannot test the site.
Did you try in chrome - after updating the lists ?

**Comment by andrzej928** [comment]
Ok. Icreate account for you and i found free video
https://player.pl/programy-online/prosto-z-japonii-odcinki,40995
log email:  ysm46638@omeie.com
pass:  TW0JAstara

**Comment by advertblocker** [comment]
@mapx- I'm pretty sure someone gave you credentials for this site before? Could you contact them?

**Comment by krystian3w** [comment]
Noopjs still are OK.

**Comment by mapx-** [comment]
@andrzej928 all fine in firefox too

it's something on your side

**Comment by krystian3w** [comment]
Works fine too with Polish Annoyance filters, intead add to bad lists all aliases found guilty and made PR into directory:

https://github.com/FiltersHeroes/PolishAnnoyanceFilters/tree/master/PPB

**Comment by Naala098** [comment]
Welcome friends

I entered this code in my filters and Player.pl came to life ;)
thank you <3

`@@||cdntvn.pl^$script,domain=player.pl
player.pl#@#+js(json-prune, movie.advertising.ad_server)
@@||player.pl^$cname
/ad.xml$xhr,badfilter
$xhr,redirect-rule=noopjs,domain=player.pl
player.pl##div.adsbygoogle.prebid.adocean.ado.ad.ads.advert.banner.reklama.linkSponsorowany.adsense.advertisments.reklama-top.adv_container:style(display: block !important)`

**Comment by krystian3w** [comment]
Further there is no progress with noopjs redirection restriction up to the required domains (like only `googleapis.com`) for xhr request/resource(s).

**Comment by krystian3w** [comment]
Try disable Firefox anti tracking shield 🛡️ in address bar (before padlock 🔒).

**Comment by andrzej928** [comment]
Firefox OK
