### ISSUE TITLE
dailycaller.com anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1780]
### URL(s) where the issue occurs

`http://dailycaller.com/2018/03/22/youtube-firearm-video-policy`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/37865618-924e0290-2f55-11e8-8075-adfa58f0cf38.png)

### Versions

- Browser/version: Chrome 65
- uBlock Origin version: 1.15.18

**Comment by mapx-** [comment]
it was fixed 2-3 days ago, update ublock filters and test again

**Comment by terrorist96** [comment]
@mapx- 
![image](https://user-images.githubusercontent.com/12802056/40794729-039fd272-64ce-11e8-8235-f53e32ff636b.png)

**Comment by okiehsch** [comment]
Already fixed [yesterday](https://github.com/uBlockOrigin/uAssets/commit/3a4300d0944b220feb08d8719392702b0d65fdbe), update your filter list.
