### ISSUE TITLE
busuu.com: breakage

### ISSUE THREAD

**Issue by HowlinVixen** [uBlockOrigin/uAssets#17805]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.busuu.com/dashboard`

### Category

breakage

### Description

Did one lesson and it played the ad, but at least I could do the lesson. Second time around it won't play the ad but also the timer doesn't ever go down from 15 seconds, so it never loads the lesson. <s>I think it might be EasyPrivacy? Unsure, sorry I'm not super knowledgeable in this sector.</s> Not that, issue replicated when EasyPrivacy is also off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/12884744/234713890-2c428403-c447-4f6e-a801-18b23b368598.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 151939
  cosmetic: 189123
  scriptlet: 26298
  html: 1116
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 43778-5427, 3d.23h.17m
    https://gitcdn.xyz/cdn/kbinani/adblock-youtube-ads/b8c6cf8901109188c7334e8ee82ad352d5174b79/signed.txt: 0-0, never
    https://gitlab.com/DandelionSprout/adfilt/raw/master/Sensitive%20lists/TabloidRemover.txt: 842-1, 5d.17h.36m
    https://raw.githubusercontent.com/easylistbrasil/easylistbrasil/filtro/easylistbrasil.txt: 6460-328, 18h.22m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt: 409-0, 3d.22m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 665-67, 6d.4h.2m
    https://winhelp2002.mvps.org/hosts.txt: 8729-4, 3d.21m
    adguard-annoyance: 67507-1685, 3d.23h.20m
    adguard-social: 20326-36, 3d.23h.16m
    fanboy-annoyance: 77225-6441, 3d.23h.22m
    ublock-annoyances: 4919-4, 3d.23h.18m
    dpollock-0: 11353-1648, 7d.21h.24m
  default: 
    user-filters: 53-4, never
    ublock-filters: 34853-124, 3d.23h.15m
    ublock-badware: 6836-4, 3d.23h.14m
    ublock-privacy: 364-0, 8d.16h.49m
    ublock-abuse: 70-2, 8d.16h.48m
    ublock-unbreak: 2000-2, 3d.23h.13m
    ublock-quick-fixes: 203-0, 18h.24m
    easylist: 65496-1079, 2d.20h.19m
    easyprivacy: 30882-13320, 3d.23h.21m
    urlhaus-1: 7286-1, 18h.23m
    plowe-0: 3749-332, 7d.18h.41m
    spa-1: 5189-26, 3d.23h.19m
filterset (user): [array of 53 redacted]
trustedset: 
  added: [array of 103 redacted]
  removed: 
    about-scheme
    edge-scheme
switchRuleset: 
  removed: 
    no-large-media: behind-the-scene false
    no-csp-reports: * true
hostRuleset: 
  added: [array of 22 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 1646 ms (selfie)
  maxAssetCacheWait: 126 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    busuu.com: 2
    appboycdn.com: 1
    googlesyndication.com: 1
    googletagmanager.com: 1
    optimizely.com: 2
    sentry.io: 9
```
</details>

**Comment by gorhill** [comment]
> Not that, issue replicated when EasyPrivacy is also off

You have a lot of extra lists selected, to be sure no time is wasted, did you _really_ test with only default lists?

**Comment by HowlinVixen** [comment]
OH I'm so sorry, I had flicked everything back on before sending the report out of worry. But yes I have done the test, in fact here it is again- 
![image](https://user-images.githubusercontent.com/12884744/234731571-ae61da66-045d-49c2-bba8-fb246b0395aa.png)

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
@@||busuu.com^$ghide
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=www.busuu.com
@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*/show_ads_impl$script,domain=www.busuu.com
||busuu.com/*/busuu_ad$media
*$frame,redirect-rule=noopframe,domain=busuu.com
busuu.com##+js(nano-sib, current-=1)
```

**Comment by HowlinVixen** [comment]
Still the same issue, site breaks when doing a second lesson. Here's another log in case it's needed.

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 90544
 cosmetic: 40170
 scriptlet: 17590
 html: 953
listset (total-discarded, last-updated): 
 removed: 
  user-filters: null
  spa-1: null
 default: 
  ublock-filters: 34566-56, 12m
  ublock-badware: 6956-0, 12m
  ublock-privacy: 373-0, 12m
  ublock-abuse: 70-0, 12m
  ublock-unbreak: 2011-1, 12m
  ublock-quick-fixes: 209-0, 11m
  easylist: 65948-598, 11m
  easyprivacy: 30903-1762, 11m
  urlhaus-1: 7058-1, 11m
  plowe-0: 3746-4, 11m
filterset (user): [array of 59 redacted]
trustedset: 
 added: [array of 103 redacted]
 removed: 
  about-scheme
  edge-scheme
switchRuleset: 
 removed: 
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset: 
 added: [array of 31 redacted]
 removed: 
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 588 ms
 maxAssetCacheWait: 153 ms
popupPanel: 
 blocked: 92
 network: 
  busuu.com: 7
  appboycdn.com: 1
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  optimizely.com: 2
  sentry.io: 79
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by HowlinVixen** [comment]
WAIT NO 😭

Still the same issue, site breaks when doing a second lesson. Here's another log in case it's needed.

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 90544
 cosmetic: 40170
 scriptlet: 17590
 html: 953
listset (total-discarded, last-updated): 
 removed: 
  user-filters: null
  spa-1: null
 default: 
  ublock-filters: 34566-56, 12m
  ublock-badware: 6956-0, 12m
  ublock-privacy: 373-0, 12m
  ublock-abuse: 70-0, 12m
  ublock-unbreak: 2011-1, 12m
  ublock-quick-fixes: 209-0, 11m
  easylist: 65948-598, 11m
  easyprivacy: 30903-1762, 11m
  urlhaus-1: 7058-1, 11m
  plowe-0: 3746-4, 11m
filterset (user): [array of 59 redacted]
trustedset: 
 added: [array of 103 redacted]
 removed: 
  about-scheme
  edge-scheme
switchRuleset: 
 removed: 
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset: 
 added: [array of 31 redacted]
 removed: 
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 588 ms
 maxAssetCacheWait: 153 ms
popupPanel: 
 blocked: 92
 network: 
  busuu.com: 7
  appboycdn.com: 1
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  optimizely.com: 2
  sentry.io: 79
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by HowlinVixen** [comment]
And I cleared cookies, cache, history- everything I could really.

**Comment by stephenhawk8054** [comment]
> user-filters: null

You disabled the custom filters?

**Comment by HowlinVixen** [comment]
I.... Can I just apologize and say I'm embarrassed as hell right now? Because I am, and I did forget to turn them back on after the previous log. I'm so sorry.

The countdown skips through now, thank you so much for the fix and for the patience. I'll close this now 🙇‍♂️

**Comment by Mar7thLover** [comment]
The old method doesn't work for new version of this website. Now it can't skip ad.
