### ISSUE TITLE
zhihu.com: breakage

### ISSUE THREAD

**Issue by Deviant5186** [uBlockOrigin/uAssets#17806]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zhihu.com/question/24772327`

### Category

breakage

### Description

After enabling the uBO, the page cannot be scrolled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 112
filterset (summary): 
  network: 107305
  cosmetic: 50379
  scriptlet: 17921
  html: 953
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 10d.1m
  default: 
    user-filters: 10-0, never
    ublock-filters: 34855-69, 3d.23h.37m
    ublock-badware: 6852-1, 3d.23h.32m
    ublock-privacy: 361-0, 10d.5m
    ublock-abuse: 70-0, 10d.4m
    ublock-unbreak: 2003-6, 3d.23h.40m
    easylist: 65523-997, 3d.23h.35m
    easyprivacy: 30883-1770, 3d.23h.33m
    urlhaus-1: 7058-1, 21m
    plowe-0: 3749-2, 10d.2m
    CHN-0: 27629-124, 3d.23h.41m
    ublock-quick-fixes: 203-0, 20m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 3 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 528 ms (selfie)
  maxAssetCacheWait: 386 ms
popupPanel: 
  blocked: 24
  blockedDetails: 
    zhihu.com: 21
    baidu.com: 2
    bdstatic.com: 1
```
</details>

**Comment by Procyon-b** [comment]
I can't reproduce.
Check in your user filters. Maybe you've tried to hide the dialog (is it a login dialog? - I don't speak chinese).

**Comment by Deviant5186** [comment]
You are right, thank you.

**Comment by gorhill** [comment]
If you want to keep your filter for modal overlay, you can restore scrolling with a `:style` filter:

    zhihu.com##.Modal-wrapper
    zhihu.com##html:style(overflow: unset !important)

**Comment by Deviant5186** [comment]
> zhihu.com##.Modal-wrapper
> zhihu.com##html:style(overflow: unset !important)

Thank you! You are legend
