### ISSUE TITLE
roosterteeth.com: ads

### ISSUE THREAD

**Issue by Pantscada** [uBlockOrigin/uAssets#17807]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://roosterteeth.com/watch/lets-play-2023-4-25`

### Category

ads

### Description

roosterteeth.com new video player, plays ads mid video that cannot be skipped 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 121379
  cosmetic: 204569
  scriptlet: 39342
  html: 1117
listset (total-discarded, last-updated): 
  added: 
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1d.7h.3m
    adguard-generic: 70541-5495, 3d.23h.18m
    adguard-mobile: 8691-98, 3d.23h.20m
    adguard-annoyance: 67508-6012, 3d.23h.19m
    fanboy-thirdparty_social: 69-0, 1d.2h.59m
    fanboy-annoyance: 91198-15312, 1d.3h
    ublock-annoyances: 4920-4, 3d.23h.22m
    adguard-spyware-url: 999-5, 3d.23h.21m
    block-lan: 46-0, 28d.6h.58m
  default: 
    user-filters: 0-0, never
    ublock-filters: 34845-66, 1d.7h.6m
    ublock-badware: 7014-1, 1d.7h.5m
    ublock-privacy: 370-0, 2d.7h.11m
    ublock-abuse: 70-0, 2d.7h.12m
    ublock-unbreak: 2010-3, 1d.7h.4m
    easylist: 65618-652, 1d.7h.7m
    easyprivacy: 30880-1770, 3d.7h.17m
    urlhaus-1: 7279-1, 6h.58m
    plowe-0: 3746-2, 2d.11h.13m
    ublock-quick-fixes: 209-0, 6h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 47 redacted]
  removed: 
    moz-extension-scheme
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1267 ms (selfie)
  maxAssetCacheWait: 479 ms
popupPanel: 
  blocked: 97
  blockedDetails: 
    brightcove.com: 54
    cookielaw.org: 2
    facebook.net: 1
    innovid.com: 1
    ngtv.io: 1
    typekit.net: 1
    wmcdp.io: 37
```
</details>

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054 
@mapx- 

Please add: `||brightcove.com^$xhr,removeparam=ad_config_id,domain=brightcove.net`

Example: `https://www.nhl.com/video/all-of-friday-s-goals-6340934708112`

**Comment by dimisa-RUAdList** [comment]
@gorhill 
May be: `||brightcove.com^$xhr,removeparam=ad_config_id,domain=brightcove.net|roosterteeth.com`?

~> `https://github.com/uBlockOrigin/uAssets/commit/fc2d7bd065b3e79d945fcfdc0da73ff33f6ea089`

**Comment by dimisa-RUAdList** [comment]
The fact is that `brightcove.com` and `brightcove.net` are different domains. In addition, the rule for `roosterteeth.com` has been working for several months stably and without breakdowns.

**Comment by stephenhawk8054** [comment]
I think the issue is `brightcove.net` could be the iframe of many other sites, unlike `roosterteeth.com` which is a 1st-party site and is not (or rarely) meant to be iframe inside others

@gorhill I think an approach for this is the concept of `rootDomain`. We actually already had an anti-adblock case of `imasdk.googleapis.com` iframe in which we have to allow an adserver XHR (`adnxs.com`) inside that iframe and it doesn't contain more specific information in the URL

https://github.com/uBlockOrigin/uAssets/issues/16014#issuecomment-1732295421

**Comment by gorhill** [comment]
Yeah, I thought about this when looking at this case.

**Comment by gorhill** [comment]
> the concept of `rootDomain`

You can start to use `top=` to match against hostname of URL in address bar in latest dev build: https://github.com/gorhill/uBlock/commit/aebc108e36

Syntax is same as what is allowed with `from=` or `to=`.

Keep in mind neither Firefox nor Safari's DNR implementation supports `topDomains`, only Chromium at the moment. Entity- and regex-like values are discarded when converting to DNR, as is currently done with `from=` and `to=`.

**Comment by uBlock-user** [comment]
same as discussed here - https://github.com/uBlockOrigin/uBlock-discussions/discussions/354#discussioncomment-5307255 ?
