### ISSUE TITLE
megaup.net: breakage

### ISSUE THREAD

**Issue by caninanir** [uBlockOrigin/uAssets#17802]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/1Tg43/Rhythm.Doctor.v0.13.0.r28.rar`

### Category

breakage

### Description

aaaaaaa

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 111
filterset (summary): 
 network: 89599
 cosmetic: 39942
 scriptlet: 17754
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65038-74, never
  easyprivacy: 30864-1146, never
  plowe-0: 3749-944, never
  ublock-abuse: 70-0, never
  ublock-badware: 6774-116, never
  ublock-filters: 33859-122, never
  ublock-privacy: 315-1, never
  ublock-quick-fixes: 186-2, never
  ublock-unbreak: 1989-44, never
  urlhaus-1: 7073-1, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1244 ms
 maxAssetCacheWait: 21 ms
popupPanel: 
 blocked: 11
 network: 
  megaup.net: 3
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 1
  dmmzkfd82wayn.cloudfront.net: 2
  googletagmanager.com: 1
  keydawnawe.com: 1
  s3.amazonaws.com: 1
```
</details>

**Comment by mapx-** [comment]
update all your filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by gorhill** [comment]
> aaaaaaa

With that kind of description, best to assume @caninanir didn't really go through the prerequisite steps, which would have saved everybody's time.
