### ISSUE TITLE
zive.cz: detection

### ISSUE THREAD

**Issue by DavidAntonin** [uBlockOrigin/uAssets#17809]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zive.cz/`

### Category

detection

### Description

detection and waiting 5s

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 90580
 cosmetic: 40522
 scriptlet: 17761
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  CZE-0: 737-0, now
  easylist: 65793-47, now
  easyprivacy: 30870-1188, now
  plowe-0: 3746-940, now
  ublock-abuse: 70-0, now
  ublock-badware: 6952-122, now
  ublock-filters: 33688-76, now
  ublock-privacy: 323-3, now
  ublock-quick-fixes: 216-19, now
  ublock-unbreak: 2000-34, now
  urlhaus-1: 7058-1, now
filterset (user): [empty]
trustedset: 
 added: [array of 45 redacted]
 removed: 
  edge-scheme
  wyciwyg-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1022 ms (selfie)
 maxAssetCacheWait: 168 ms
popupPanel: 
 blocked: 7
 network: 
  cpex.cz: 2
  gemius.pl: 1
  google.com: 1
  googlesyndication.com: 1
  idvert.cz: 1
  performax.cz: 1
 cosmetic: 
  ##div.sky-wrapper
  ##.cnc-ads--rectangle_480_1
  ##.rklm
  ##.bx-leaderboard
  ##.cnc-ads
```
</details>

**Comment by mapx-** [comment]
fixed as annoyance, @DavidAntonin enable this list: `uBlock filters – Annoyances`

**Comment by 5ta1da** [comment]
Hello new version of anti-adblock window, filter not working anymore.
Could you fix it please?

**Comment by mapx-** [comment]
Did you enable uBO annoyances list ?

I get detection if I disable
`@@||zive.cz^$ghide` => `@@||zive.cz^$ghide,badfilter`

**Comment by 5ta1da** [comment]
Oops sorry, there are multiple annoyances lists with subcategiroes (EasyList – Annoyances, AdGuard – Annoyances ....)  and I enabled bad filter.

But there really is new version of that pop-up for last few days which no longer have continue button, that confused me.

Thank you for help.

**Comment by mapx-** [comment]
ok, I'll move it to the main list
