### ISSUE TITLE
lookmovie2.to: ads

### ISSUE THREAD

**Issue by MrEzi0** [uBlockOrigin/uAssets#17817]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lookmovie2.to/`

### Category

ads

### Description

Banner ad visible on site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230428-000858](https://user-images.githubusercontent.com/132009514/234967083-db5c28e1-34b5-413e-82d1-b5deb4367a0c.png) 

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium Mobile: 111
filterset (summary): 
 network: 91752
 cosmetic: 30325
 scriptlet: 17880
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  adguard-mobile: 8706-32, 8h.20m
  easylist: 65808-16884, 8h.19m
  easyprivacy: 30880-1193, 3d.10h.2m
  plowe-0: 3748-1024, 7d.8h.32m
  ublock-abuse: 70-0, 12d.1m
  ublock-badware: 6861-123, 3d.10h.3m
  ublock-filters: 34199-357, 2d.5h.30m
  ublock-privacy: 294-3, 12d.2m
  ublock-quick-fixes: 217-16, 1h.57m
  ublock-unbreak: 1998-36, 2d.5h.30m
  urlhaus-1: 7005-1, 1h.56m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3047 ms (selfie)
 maxAssetCacheWait: 406 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by gorhill** [comment]
EasyList's `##div[class^="native-ad-"]` is hiding that banner on my side.

**Comment by mapx-** [comment]
> Chromium Mobile: 111

You should test in firefox mobile

**Comment by advertblocker** [comment]
Use the Brave Browser or Firefox + uBlock Origin on Android

**Comment by gorhill** [comment]
The filter above is generic, so it's a matter of unchecking _"Ignore generic cosmetic filters"_ in _Filter lists_ pane.

But I think we should just add a specific version of the filter.
