### ISSUE TITLE
1075.fm: breakage

### ISSUE THREAD

**Issue by Matrix-sudo** [uBlockOrigin/uAssets#17815]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://1075.fm/item/116234/`

### Category

breakage

### Description

the articles in this site aren't shown 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 88058
 cosmetic: 112165
 scriptlet: 22858
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  plowe-0: null
  ublock-badware: null
 added: 
  ISR-0: 1713-0, 9h.43m
  fanboy-annoyance: 78282-364, 8d.6h.16m
  ublock-annoyances: 4968-72, 9h.46m
 default: 
  user-filters: 0-0, never
  easylist: 65793-45, 7h.42m
  easyprivacy: 30897-1186, 9h.49m
  ublock-abuse: 70-0, 8d.6h.19m
  ublock-filters: 33688-99, 9h.48m
  ublock-privacy: 316-3, 8d.6h.18m
  ublock-quick-fixes: 210-17, 9h.45m
  ublock-unbreak: 2000-36, 9h.47m
  urlhaus-1: 7058-0, 9h.44m
filterset (user): [empty]
trustedset: 
 added: [array of 30 redacted]
 removed: 
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 7976 ms (selfie)
 maxAssetCacheWait: 1393 ms
popupPanel: 
 blocked: 6
 network: 
  addtoany.com: 1
  aniview.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  outbrain.com: 1
 cosmetic: 
  ##.OUTBRAIN
  ##.social-link
  ##.content-share
  ##.addtoany_list
  ##.aplvideo
  ##.ad-main
  ##[id^=\"div-gpt-ad\"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by advertblocker** [comment]
```
1075.fm#@#.content-share
```

or add `~10075.fm` to ` ##.content-share` from "My filters"

**Comment by mapx-** [comment]
@ryanbr

**Comment by advertblocker** [comment]
oh wait, the cosmetic part shows which cosmetic filters were applied, oops

**Comment by Matrix-sudo** [comment]
adding 1075.fm#@#.content-share to my list does solve it. 
which filter caused it?

**Comment by mapx-** [comment]
`##.content-share`  from `fanboy annoyances` list

**Comment by Matrix-sudo** [comment]
> `##.content-share` from `fanboy annoyances` list

should I enable that globally or let it be only for this site?

**Comment by advertblocker** [comment]
`1075.fm#@#.content-share` disables `##.content-share` on `1075.fm`

Generally, such issues are solved after testing (e.g., lists used, filters, viewing the source code, etc.)

**Comment by mapx-** [comment]
@Matrix-sudo the issue will be fixed in that list by his maintainer (which I notified above).
After that you have to update that list.
