### ISSUE TITLE
tempumail.com: detection

### ISSUE THREAD

**Issue by valiantuser** [uBlockOrigin/uAssets#17823]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tempumail.com/`

### Category

detection

### Description

"Ad Blocker Detected
Disable the Ad Blocker to use Temp Mail" screen pops up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-04-27 6 36 27 PM](https://user-images.githubusercontent.com/101596581/235005535-54d745b1-8ead-4b7a-ba3b-6ed457f8717e.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 90244
 cosmetic: 40083
 scriptlet: 17807
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 3-0, never
  easylist: 65638-45, 3d.22h.42m
  easyprivacy: 30880-1183, 3d.22h.43m
  plowe-0: 3748-941, 7d.21h.31m
  ublock-abuse: 70-0, 10d.19h.57m
  ublock-badware: 6862-121, 3d.22h.41m
  ublock-filters: 34000-104, 3d.22h.40m
  ublock-privacy: 295-2, 10d.19h.56m
  ublock-quick-fixes: 216-16, 21h.34m
  ublock-unbreak: 1993-41, 3d.22h.39m
  urlhaus-1: 7058-1, 21h.35m
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 12 redacted]
switchRuleset: 
 added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1260 ms (selfie)
 maxAssetCacheWait: 466 ms
popupPanel: 
 blocked: 7
 network: 
  tempumail.com: 1
  google.com: 4
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by Daxy7** [comment]
allow this in EasyList
`@@/fuckadb.js$domain=~tempumail.com`

**Comment by advertblocker** [comment]
```
tempumail.com##+js(nostif, enable_ad_block_detector)
```

**Comment by valiantuser** [comment]
> ```
> tempumail.com##+js(nostif, enable_ad_block_detector)
> ```
> 
> or
> 
> ```
> @@||tempumail.com/storage/js/fuckadb.js$1p
> ```

worked
