### ISSUE TITLE
servicecentral.trendmicro.com: breakage

### ISSUE THREAD

**Issue by James-SSR** [uBlockOrigin/uAssets#17827]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://servicecentral.trendmicro.com/en-US/ers/ip-lookup/`

### Category

breakage

### Description

With uBO enabled entering IP address and clicking "check" button reports "client ip does not exist".
Wiht uBO disabled it will show another box below with reputation info of IP address and another button.
You can use any IP for test, such as 8.8.8.8

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 90356
 cosmetic: 40176
 scriptlet: 17602
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65793-45, 23h.34m
  easyprivacy: 30870-1183, 23h.34m
  plowe-0: 3746-940, 23h.34m
  ublock-abuse: 70-0, 23h.34m
  ublock-badware: 6952-122, 23h.33m
  ublock-filters: 33688-76, 23h.33m
  ublock-privacy: 323-3, 23h.33m
  ublock-quick-fixes: 216-19, 23h.33m
  ublock-unbreak: 2000-34, 23h.33m
  urlhaus-1: 7058-1, 23h.33m
filterset (user): [empty]
hostRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 223 ms (selfie)
 maxAssetCacheWait: 109 ms
popupPanel: 
 blocked: 3
 network: 
  googletagmanager.com: 1
  jsonip.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||jsonip.com/?callback=jQuery$domain=trendmicro.com`

TPf @Alex-302
EP @ryanbr

**Comment by James-SSR** [comment]
Adding that exception works (obvsly).

By coincidence I found another breakage:
https://www.pochta.ru/tracking
It's post package tracking page (by barcode/track number).
Added @@/api/tracking/*$domain=pochta.ru
(If it needs be separate issue - just say)

**Comment by stephenhawk8054** [comment]
Can you check which filter causes the breakage and what is the URL that it blocks?

**Comment by stephenhawk8054** [comment]
Ah I see

**Comment by mapx-** [comment]
we could badfilter it => not present in AG TPf list, and adding specific ones when is necessary

**Comment by stephenhawk8054** [comment]
Yeah I agree

**Comment by advertblocker** [comment]
Maybe a change to `3p`?

**Comment by stephenhawk8054** [comment]
@mapx- How about change `/js/tracking.js` and `/api/tracking/*` to 3p first, and see how many breakages they could involve in. Although we do have few breakage cases with `/js/tracking.js` in 3p, but overall the number is smaller than 1p, and we might still be able to handle them.

**Comment by mapx-** [comment]
idk, all these generic filters - especially in EP - lead to too much breakages
