### ISSUE TITLE
geeksforgeeks.org: detection

### ISSUE THREAD

**Issue by ferris** [uBlockOrigin/uAssets#17825]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.geeksforgeeks.org/input-output-system-calls-c-create-open-close-read-write/`

### Category

detection

### Description

There is a modal that pops up when ad blocker is detected. When I try to remove it, an annoying log-in box pops up as well. When that is removed, all scrolling functionality on the site is broken.

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 90324
 cosmetic: 40162
 scriptlet: 17762
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65613-45, 2d.9h.57m
  easyprivacy: 30897-1183, 2d.9h.58m
  plowe-0: 3746-941, 1d.11h.10m
  ublock-abuse: 70-0, 2d.10h
  ublock-badware: 7010-121, 2d.6h.47m
  ublock-filters: 33982-106, 2d.9h.56m
  ublock-privacy: 322-3, 2d.9h.59m
  ublock-quick-fixes: 217-16, 4h.42m
  ublock-unbreak: 1993-34, 2d.6h.48m
  urlhaus-1: 7005-1, 4h.22m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 221 ms
 maxAssetCacheWait: 82 ms
popupPanel: 
 blocked: 11
 network: 
  geeksforgeeks.org: 4
  go-mpulse.net: 1
  google.com: 1
  googleoptimize.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  googletagservices.com: 1
 cosmetic: 
  ###text-15
  ###text-16
  ##div[id^=\"GFG_AD_\"]
```
</details>

**Comment by stephenhawk8054** [comment]
It was fixed in `uBlock filters - Annoyances` list. Enable that list at `Annoyances` section in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters).

**Comment by ferris** [comment]
Interesting, didn't know that list existed and could be enabled like that. Thanks for the heads up!
