### ISSUE TITLE
Crypto coin miner on sleeptimer.org

### ISSUE THREAD

**Issue by sometoby** [uBlockOrigin/uAssets#1782]
### URL(s) where the issue occurs

`http://sleeptimer.org`

### Describe the issue

The site serves a crypto coin mining script: `http://sleeptimer.org/playerc.js` in the script `playerc.js`. [(deobfuscated version)](https://gist.github.com/sometoby/7eae7af67c1109ceb42240e3091553ac)

**Comment by SMed79** [comment]
test 
```
sleeptimer.org##script:inject(abort-on-property-read.js, WebAssembly)
```
or
```
||sleeptimer.org^$csp=child-src 'none';frame-src *;worker-src 'none';
```

**Comment by sometoby** [comment]
The first one works, pushed the updated commit.
