### ISSUE TITLE
hyundai-motor.com.tw: breakage

### ISSUE THREAD

**Issue by cmyang2005** [uBlockOrigin/uAssets#17824]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hyundai-motor.com.tw/clicktobuy/custin`

### Category

breakage

### Description

breakage

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 107118
 cosmetic: 50324
 scriptlet: 17924
 html: 953
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34882-67, 3d.23h.58m
  ublock-badware: 6866-0, 3d.23h.57m
  ublock-privacy: 345-0, 12d.32m
  ublock-abuse: 70-0, 12d.31m
  ublock-unbreak: 2010-2, 3d.23h.56m
  ublock-quick-fixes: 203-0, 6m
  easylist: 65496-677, 4d.2m
  easyprivacy: 30891-1789, 4d
  urlhaus-1: 6994-1, 5m
  plowe-0: 3749-2, 12d.29m
  CHN-0: 27641-113, 3d.23h.59m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 924 ms (selfie)
 maxAssetCacheWait: 227 ms
popupPanel: 
 blocked: 9
 network: 
  hyundai-motor.com.tw: 1
  appier.net: 2
  facebook.net: 1
  googletagmanager.com: 1
  line-scdn.net: 1
  scupio.com: 1
  yimg.com: 2
```
</details>

**Comment by gorhill** [comment]
Broken by EasyPrivacy's `/js/tracking.js`. THis fixes it:

    @@||hyundai-motor.com.tw/modules/js/tracking.js$script,1p

**Comment by stephenhawk8054** [comment]
I think `redirect-rule` is enough, no need for allowing?

```adb
||hyundai-motor.com.tw/modules/js/tracking.js$script,redirect-rule=noopjs
```

**Comment by gorhill** [comment]
I forgot to check with `redirect-rule`. Problem is `redirect-rule` are discarded with uBOL because this can't be repsented by a DNR rule, so the site will still be broken with uBOL. From what I see in the JS content of that file, it doesn't seem to be doing much, and also it's first party.

**Comment by gorhill** [comment]
I know about `important`, just not worth.
