### ISSUE TITLE
pinterest.com: ads

### ISSUE THREAD

**Issue by urdeadeyebolt** [uBlockOrigin/uAssets#17822]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.com/`

### Category

ads

### Description

it worked before, making all of the photos either blank or a solid colour. now is not working at all and ads are visible.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![image](https://user-images.githubusercontent.com/132018430/234995476-9ad77bd9-39ab-43cd-824a-f04e66b8520a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93727
 cosmetic: 40185
 scriptlet: 17602
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65966-45, now
  easyprivacy: 32985-40, now
  plowe-0: 3746-934, now
  ublock-abuse: 70-0, now
  ublock-badware: 6952-122, now
  ublock-filters: 33688-78, now
  ublock-privacy: 323-3, now
  ublock-quick-fixes: 217-19, now
  ublock-unbreak: 2000-34, now
  urlhaus-1: 7005-1, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1293 ms
 maxAssetCacheWait: 18 ms
popupPanel: 
 blocked: 7
 network: 
  pinterest.com: 3
  cedexis.com: 1
  flashtalking.com: 1
  googletagmanager.com: 1
  tvpixel.com: 1
```
</details>

**Comment by mapx-** [comment]
still working fine on my end

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by advertblocker** [comment]
@mapx- I haven't tested, but did you test with a Pinterest account? Idk if one's needed to browse anyway

**Comment by gorhill** [comment]
I don't see uBO toolbar icon in your screenshot. Did you take this screenshot while uBO was enabled?
