### ISSUE TITLE
Does not block twtich ads. 

### ISSUE THREAD

**Issue by ShynnSup** [uBlockOrigin/uAssets#17835]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Does not block twtich ads

### A specific URL where the issue occurs.

twitch.tv/

### Steps to Reproduce

Watch twtich until an ad pops up

### Expected behavior

Block ad

### Actual behavior

Not blocking ad

### Configuration

-

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
