### ISSUE TITLE
shop.motorolasolutions.com: breakage

### ISSUE THREAD

**Issue by sseppala** [uBlockOrigin/uAssets#17836]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shop.motorolasolutions.com/`

### Category

breakage

### Description

shop.motorolasolutions.com will not load.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screen Shot 04-28-23 at 09 08 AM](https://user-images.githubusercontent.com/132075814/235171066-a8571c04-ac11-472d-890e-c51e7259bddb.PNG)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 98805
 cosmetic: 100843
 scriptlet: 23381
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  ublock-quick-fixes: null
 added: 
  adguard-annoyance: 67774-92, 1m
  ublock-annoyances: 4968-166, 1m
 default: 
  user-filters: 2-0, never
  easylist: 65808-101, 1m
  easyprivacy: 32985-121, 1m
  plowe-0: 3749-935, 9d.16m
  ublock-abuse: 70-0, 9d.16m
  ublock-badware: 6983-123, 1m
  ublock-filters: 33699-453, 1m
  ublock-privacy: 316-3, 9d.15m
  ublock-unbreak: 2005-36, 1m
  urlhaus-1: 6865-0, 1m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 10 redacted]
modifiedUserSettings: 
 contextMenuEnabled: false
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 700 ms (selfie)
 maxAssetCacheWait: 225 ms
popupPanel: 
 blocked: 2
 network: 
  motorolasolutions.com: 2
```
</details>

**Comment by ghajini** [comment]
update filters & comment back if it's still broken

**Comment by sseppala** [comment]
The issue is resolved.

Thank you

Sandra Seppala, Fiscal Specialist
Waukesha County Radio Services
________________________________
