### ISSUE TITLE
[NSFW] bellesa. co

### ISSUE THREAD

**Issue by advertblocker** [uBlockOrigin/uAssets#17842]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

- pre-roll video ad
- after pausing the video, ad banner

### URL(s) where the issue occurs.

NSFW: 
`https://www.bellesa.co/videos/2820/bellesa-house-episode-7-scarlit-rod`

### uBO version

1.49.0

### Browser name and version

Mullvad Browser 12.0.6 (64-bit)

### Settings

.

**Comment by mapx-** [comment]
test

```
bellesa.co##[href*="preroll"]:upward(2)
||res.cloudinary.com/$image,domain=bellesa.co
```

**Comment by advertblocker** [comment]
> test
> 
> ```
> bellesa.co##[href*="preroll"]:upward(2)
> ||res.cloudinary.com/$image,domain=bellesa.co
> ```

they work, but with a delay
AdGuard also has some filters

**Comment by ad-blocking** [comment]
```
! ads / placeholder
bellesa.co#?#[class^="MediaQuery__Query"]:has([href*="utm_content="])
! didn't find concrete example for this one today
bellesa.co#?#[class*="BlastBar__Bar"]:has([href*="utm_content="])
! "Upgrade to Bellesa Plus"
bellesa.co#?#.lsjZm:has([href*="bplus.co"])
! Sex toys on sale ad
bellesa.co##.eZowPQ[href*="affid"]

! I didn't find a relevant example for this today
bellesa.co##.Structure-sc-122ascm-0.dkAAlx:has([src*="/a.adtng.com/"]):upward(2)
```

NSFW:
`https://www.bellesa.co/`
`https://www.bellesa.co/videos/3104/seduce-me-not`
`https://www.bellesa.co/videos/2406/whatever-you-want`

**Comment by waterinabottle** [comment]
nsfw

`https://www.bellesa.co/` : banner ad, "Spin to win" ad in header bar, "Sex Toys on Sale" in menu
