### ISSUE TITLE
loepeshop.no: breakage

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#17848]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.loepeshop.no/brooks-men-s-levitate-6-110395-1d-312.html`

### Category

breakage

### Description

As shown in the picture. These arrow keys do not work when EasyList Cookie is enabled

### Screenshot(s)

![Untitled1](https://user-images.githubusercontent.com/19490515/235276695-83b75fb7-9960-427f-825c-4e73f75eac06.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 182455
 cosmetic: 42097
 scriptlet: 17626
 html: 953
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2180-0, 12h.10m
  adguard-spyware-url: 999-140, 2d.14h.47m
  block-lan: 47-0, 2d.14h.47m
  curben-phishing: 87815-36, 12h.13m
  curben-pup: 200-0, 12h.12m
  NOR-0: 3144-9, 12h.11m
 default: 
  user-filters: 3-0, never
  ublock-filters: 34582-56, 2d.14h.47m
  ublock-badware: 6956-1, 2d.14h.47m
  ublock-privacy: 373-2, 2d.14h.47m
  ublock-abuse: 70-0, 2d.14h.47m
  ublock-unbreak: 2010-3, 2d.14h.47m
  ublock-quick-fixes: 209-0, 12h.15m
  easylist: 65836-630, 2d.14h.47m
  easyprivacy: 30898-1762, 2d.14h.47m
  urlhaus-1: 6865-0, 12h.14m
  plowe-0: 3746-2, 2d.14h.47m
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 1 redacted]
hostRuleset: 
 added: [array of 17 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 713 ms (selfie)
 maxAssetCacheWait: 221 ms
popupPanel: 
 blocked: 6
 network: 
  clerk.io: 3
  getdrip.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `/cookie-wrapper.js`.

@ryanbr
