### ISSUE TITLE
all3dp.com: detection

### ISSUE THREAD

**Issue by Jamesedward11** [uBlockOrigin/uAssets#17849]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://all3dp.com/1/3d-metal-3d-printer-metal-3d-printing/`

### Category

detection

### Description

When using Ublock Origin on All3DP, well, it does it with other blockers too, but it will leave an annoying bar at the bottom of the screen that on low-res monitors becomes super infuriating because it takes up a literal tenth of the screen and even more if your computer has a bad DPI setting

Here is an image for reference of the scale on my end.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/36340655/235277281-ffe5e675-fa31-4870-859c-cb20b6a7f830.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 114
filterset (summary): 
 network: 93248
 cosmetic: 40181
 scriptlet: 17509
 html: 952
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-1, never
  ublock-filters: 34469-54, 17m
  ublock-badware: 6997-0, 17m
  ublock-privacy: 443-0, 17m
  ublock-abuse: 70-70, 17m
  ublock-unbreak: 2017-3, 17m
  ublock-quick-fixes: 213-0, 17m
  easylist: 66073-607, 17m
  easyprivacy: 32644-609, 17m
  urlhaus-1: 6733-1, 17m
  plowe-0: 3741-3, 17m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 4 redacted]
modifiedUserSettings: 
 colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2783 ms (selfie)
 maxAssetCacheWait: 771 ms
popupPanel: 
 blocked: 13
 network: 
  all3dp.com: 1
  google.com: 6
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  gstatic.com: 1
  iubenda.com: 1
  trackonomics.net: 1
 cosmetic: 
  ##.ad-container
```
</details>

**Comment by Jamesedward11** [comment]
I am using Firefox Nightly V114, not just the standard firefox. your plugin should probably track that in debug info

**Comment by stephenhawk8054** [comment]
Have you checked these yet?

> - [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
> - [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.

**Comment by advertblocker** [comment]
Disable Adblock Plus on that webpage

**Comment by mapx-** [comment]
oh, @Jamesedward11 you habe ABP too. Very bad choice. Remove it.

**Comment by gorhill** [comment]
> - [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.

It would save so much time for everybody, _including_ reporter, if these steps were respected and answered truthfully.

> Disable Adblock Plus on that webpage

ABP or other blockers need to be removed completely, not just disabled on a single webpage, it interferes negatively on countless webpages when used along uBO.

**Comment by advertblocker** [comment]
> ABP or other blockers need to be removed completely, not just disabled on a single webpage, it interferes negatively on countless webpages when used along uBO.

Regarding this, I could recommend this, however, ABP addresses Facebook ads in https://github.com/abp-filters/abp-filters-anti-cv

**Comment by Jamesedward11** [comment]
> Disable Adblock Plus on that webpage

i *did* though
