### ISSUE TITLE
sport.bild.de: breakage

### ISSUE THREAD

**Issue by manuallypure** [uBlockOrigin/uAssets#17841]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

live ticker disappears.

### URL(s) where the issue occurs.

`https://sport.bild.de/fussball/bundesliga/ma9418002/vfl-bochum_borussia-dortmund/liveticker/?dtp=1sa2_1`

### uBO version

1.48.4

### Browser name and version

Firefox 112.0.2

### Settings

no change

**Comment by advertblocker** [comment]
```
bild.de#@#+js(set, __NUXT__.state.advertisement, {})
```
