### ISSUE TITLE
Breakage: Justthenews.com - ublock is blocking site videos in articles

### ISSUE THREAD

**Issue by Anoneemouse** [uBlockOrigin/uAssets#17843]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Videos in articles aren't showing up on Justthenews.com webpage articles.  Also, article tags at the top of the page are missing with uBlock on.  

Note, I'm sorry, but I don't know how to use chrome to check with ublock as the only extension, or in a new unmodified browser profile.  

### URL(s) where the issue occurs.

`https://justthenews.com/accountability/political-ethics/frijames-comer-pointedly-warns-witness-intimidation-too-narrow-doj`

### Screenshot(s)

Top of the page with uBlock ON:

![image](https://user-images.githubusercontent.com/16356703/235244205-1186c4f2-a41e-4fc6-850a-8007664204b4.png)

Top of the page with uBlock OFF (items that should be there with uBlock on circled in red):

![image](https://user-images.githubusercontent.com/16356703/235245055-7a5f3ada-2c19-43bf-8c40-65813bf89b66.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 93330
 cosmetic: 40207
 scriptlet: 17520
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 4-1, never
  easylist: 66018-45, now
  easyprivacy: 32644-40, now
  plowe-0: 3741-934, now
  ublock-abuse: 70-0, now
  ublock-badware: 6993-123, now
  ublock-filters: 33610-79, now
  ublock-privacy: 323-3, now
  ublock-quick-fixes: 220-17, now
  ublock-unbreak: 2008-35, now
  urlhaus-1: 6865-0, now
filterset (user): [array of 4 redacted]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2758 ms (selfie)
 maxAssetCacheWait: 667 ms
```
</details>

**Comment by okiehsch** [comment]
````
justthenews.com#@##aniview--player
justthenews.com#@#.avp-p-wrapper
````
@ryanbr

**Comment by Anoneemouse** [comment]
Thank you!  That fixed those issues.  Is there a way to make the blank space where the ad is being blocked not show up? (circled in red)

![image](https://user-images.githubusercontent.com/16356703/235248223-8415e7c8-d654-4417-ba8d-d50e4501b0a7.png)

**Comment by advertblocker** [comment]
```
justthenews.com##.block-simple-blockad-728-90
```

**Comment by Anoneemouse** [comment]
Thank you!  That did the trick.  By the way, when I submit something like this, and you guys come up with the fixes, should I use the "close" option, or leave closing an item out to you folks?

**Comment by advertblocker** [comment]
Leave it open until an EasyList maintainer addresses the issue

**Comment by Anoneemouse** [comment]
Ok, thank you!
