### ISSUE TITLE
outlook.live.com: breakage

### ISSUE THREAD

**Issue by toastbear** [uBlockOrigin/uAssets#17847]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://outlook.live.com/mail/0/`

### Category

breakage

### Description

Cosmetic filters removes all email list.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 102
filterset (summary): 
  network: 89329
  cosmetic: 39939
  scriptlet: 17570
  html: 939
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt: 213-80, 6m
  default: 
    user-filters: 219-33, never
    ublock-filters: 34071-116, 1h.30m
    ublock-badware: 6221-0, 1h.29m
    ublock-privacy: 352-0, 1d.22h.23m
    ublock-abuse: 78-0, 1d.22h.22m
    ublock-unbreak: 1956-0, 1h.28m
    ublock-quick-fixes: 463-6, 1h.25m
    easylist: 65103-169, 1h.27m
    easyprivacy: 30755-1207, 1h.31m
    urlhaus-1: 7324-0, 1h.26m
    plowe-0: 3751-937, 1h.32m
filterset (user): [array of 219 redacted]
trustedset: 
  added: [array of 37 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 99524 ms (selfie)
  maxAssetCacheWait: 515 ms
popupPanel: 
  blocked: 36
  blockedDetails: 
    live.com: 1
    3lift.com: 3
    adnxs.com: 3
    microsoft.com: 8
    office.net: 19
    taboola.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
> user-filters: 219-33, never

Can you disable `My filters` list and test again?

**Comment by toastbear** [comment]
Already have, I have isolated it down to the Cosmetic Filter on the site and I think specifically related to this code chunk:
<div class="jGEPX"><div class="Qhdyf Nu37o"><div class="Tovoi" style="flex-basis: 333px; width: 333px; max-width: 333px;"><div class="k6ekr"></div><div class="fz7QX wT9Xs gcbCr Rx01o Qhdyf"><div class="r4Jfp"><div class="ms-Persona ms-Persona--size28 root-332"><div role="presentation" class="ms-Persona-coin ms-Persona--size28 coin-275"><div role="presentation" class="ms-Persona-imageArea imageArea-277"><div class="ms-Persona-initials initials-341" aria-hidden="true"><span>MO</span></div><div class="ms-Image ms-Persona-image image-339" style="width: 28px; height: 28px;"><img class="ms-Image-image ms-Image-image--cover ms-Image-image--portrait is-notLoaded is-fadeIn is-error image-340" src="//res-h3.public.cdn.office.net/owamail/20230421002.12/resources/images/ads-olk-icon.png" alt="" vsnfgshsw=""></div></div></div></div></div><div class="Gc3OW"></div></div><div class="joXLs gy2aJ Dc0o9 Ejrkd psgZA"><span>Microsoft Outlook</span></div><div class="JsqZC tPzlR ZInq9"><i data-icon-name="Delete" role="img" aria-label="Remove" class="sOBX8 IBaaM zjbHu Ws8Cj root-274" title="Remove"></i><div class="_2Frh">Ad</div><button type="button" aria-label="Click to see more" class="ms-Button ms-Button--icon ms-Button--hasMenu E3HUE root-318" data-is-focusable="true" aria-expanded="false" aria-haspopup="true"><span class="ms-Button-flexContainer flexContainer-164" data-automationid="splitbuttonprimary"><i data-icon-name="MoreHorizontalRegular" aria-hidden="true" class="ms-Icon root-90 ms-Button-icon icon-262"><span role="presentation" aria-hidden="true" class="FLwLv"><i class="Q0K3G ___198tor0 f14t3ns0 fne0op0 fg4l7m0 fmd4ok8 f1sxfq9t" fill="currentColor" aria-hidden="true"></i></span></i><i data-icon-name="" aria-hidden="true" class="ms-Icon root-90 ms-Icon-placeHolder placeholder-91 ms-Button-menuIcon S082a menuIcon-263"></i></span></button></div></div><div class="Mf4zl"><div class="RB5Xj"><div class="W24qf gy2aJ Ejrkd">Upgrade Your Account</div><div class="t8BB6"><div class="KFR9x"><span class="cE0w3 gy2aJ Ejrkd">Get the latest premium Outlook features</span></div></div></div></div><div class="msVgX"><button class="pIYqh QWinU tdweL"><span class="PxnKn fbAdCallToAction"></span></button></div></div></div>

I went through My Filters and removed all the entries for live.com, but it still remains until I "Click to Disable Cosmetic Filtering on this site."
________________________________

**Comment by stephenhawk8054** [comment]
Can you do these steps?

* Update the extension (current version is 1.49.0), remove your added `https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt` list (the quick fix list is already in default list), disable `My filters` list then force update all the filter lists again.
* Reproduce the issue on that site
* Click on uBO's icon, then click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools), scroll to the bottom, click on `Troubleshooting Information` and copy paste it here?

**Comment by toastbear** [comment]
Okay, looks like the update fixed it. Everything I had blocked in gone and the core of the viewable window is back. It was rather difficult to troubleshoot since I was trying to read your email while the failed to display.
________________________________
