### ISSUE TITLE
assettoworld.com: detection

### ISSUE THREAD

**Issue by posmaka254** [uBlockOrigin/uAssets#17850]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I try to access the site normally and tunneled through VPN and unfortunately Ublock is detected. I talked with other users and reproduction seems to be hit or miss.

### URL(s) where the issue occurs.

`https://www.assettoworld.com/`

### uBO version

1.49.2

### Browser name and version

Microsoft Edge, Version 112.0.1722.58 (Official build) (64-bit)

### Settings

-AdGuard Annoyances
-Fanboy Annoyance
- Ublock Filter Annoyances
- F*ck F*ckAdblock
-Dan Pollock's hosts file

**Comment by stephenhawk8054** [comment]
I can't reproduce

**Comment by posmaka254** [comment]
> I can't reproduce

Yeah most people can't either, but certain few (unfortunately like me) can. Weird eh?

**Comment by stephenhawk8054** [comment]
Are you signing in to the site? Can you give screenshot of the page?

**Comment by Yuki2718** [comment]
@dimisa-RUAdList FYI

**Comment by dimisa-RUAdList** [comment]
@Yuki2718 
I don't see adblock detection either in Adblock Plus or AdBlock, no matter what VPN I use.

**Comment by Yuki2718** [comment]
> I don't see adblock detection 

Neither do I, so just a FYI as a case of `/bens/vinos.js` being bait.

**Comment by dimisa-RUAdList** [comment]
Yes, I understand that, thanks.
