### ISSUE TITLE
maxstars.ir: ads

### ISSUE THREAD

**Issue by jucklinbomlol** [uBlockOrigin/uAssets#17858]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://maxstars.ir/`

### Category

ads

### Description

Four ads are displayed in the four corners of this site
These ads are not detected and blocked by ublock origin
Please check this issue
thank you so much

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 89597
 cosmetic: 39942
 scriptlet: 17746
 html: 950
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34738-123, never
  ublock-badware: 6778-0, never
  ublock-privacy: 365-0, never
  ublock-abuse: 70-0, never
  ublock-unbreak: 2000-0, never
  ublock-quick-fixes: 185-4, never
  easylist: 65038-171, never
  easyprivacy: 30864-1208, never
  urlhaus-1: 7073-1, never
  plowe-0: 3749-944, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4463 ms
 maxAssetCacheWait: 39 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by advertblocker** [comment]
Enable `IRN: PersianBlocker`

```
||maxstars.ir/theme/images/ads$image
maxstars.ir###popuplink
maxstars.ir##[id^="ad-"]
```

@MasterKia
