### ISSUE TITLE
filecr.com: detection

### ISSUE THREAD

**Issue by jakariyab** [uBlockOrigin/uAssets#17852]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://filecr.com/windows/macro-recorder/?id=200364126000`

### Category

detection

### Description

detects uBlock and stops further interaction.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 93022
  cosmetic: 40186
  scriptlet: 17507
  html: 952
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34469-41, 2h.25m
    ublock-badware: 6961-0, 2h.24m
    ublock-privacy: 372-0, 5d.9m
    ublock-abuse: 70-0, 5d.8m
    ublock-unbreak: 2007-2, 2h.23m
    ublock-quick-fixes: 210-14, 2h.22m
    easylist: 66077-577, 2h.27m
    easyprivacy: 32463-638, 2h.28m
    urlhaus-1: 6733-1, 2h.21m
    plowe-0: 3741-3, 2h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1785 ms (selfie)
  maxAssetCacheWait: 239 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    zinlab.com: 1
```
</details>

**Comment by gorhill** [comment]
Maybe another case of <https://github.com/uBlockOrigin/uAssets/issues/17356#issuecomment-1497558437>, given that the prerequesites steps have not been read carefully:

> - [x] I did not answer truthfully to **ALL** the above checkpoints.

**Comment by stephenhawk8054** [comment]
If you click on the `Download` button too fast, it can also cause anti-adb, regardless of using uBO or not. You might need to wait until the `Add to Favorites` button is available, then click on `Download` again.

**Comment by gorhill** [comment]
I tried half a dozen time and did not wait for _Add to Favorites_ to complete, and was unable to trigger an anti-blocker. I have only uBO installed, maybe other extensions add timing issues.

**Comment by stephenhawk8054** [comment]
> I tried half a dozen times and did not wait for _Add to Favorites_ to complete, and was unable to trigger an anti-blocker. I have only uBO installed, maybe other extensions add timing issues.

Ah you're right, the site implements differently this time. Last time I had anti-adb on this site, it was buggy at that part, when it showed the anti-adb when the ads resources have not finished loading yet, even when not using any extensions: https://user-images.githubusercontent.com/66517106/232661213-189362ce-13ad-405e-ac1e-2f9c27d52c45.mp4

**Comment by mapx-** [comment]
@jakariyab 

follow ALL indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
