### ISSUE TITLE
uBlock prevents page loading

### ISSUE THREAD

**Issue by MilosBranko** [uBlockOrigin/uAssets#17868]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The page can't load. See the screenshot for details

### URL(s) where the issue occurs.

`https://click.justwatch.com/`

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/86800613/235310154-ab662898-8874-4e35-8c09-974693dfdbe2.png)

### uBO version

1.49.0

### Browser name and version

FF 112.0.2

### Settings

None. Just added this personal filter suplied by you:
@@||static.chartbeat.com^$script,domain=repubblica.it

### Notes

I don't know any troubleshoot I could perform

**Comment by advertblocker** [comment]
It's for privacy reasons.

you can add

```
||click.justwatch.com^$badfilter
```

to  "My filters" in uBlock Origin to cancel the filter out

**Comment by gorhill** [comment]
On purpose. uBO does not prevent you from navigating to the link, you can just click _Proceed_ if you want to ignore the warning and go ahead.
