### ISSUE TITLE
direktesport.no: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#17861]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.direktesport.no/`

### Category

nuisance

### Description

has cookie notification at the bottom even when I have EasyList Cookie enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 185974
 cosmetic: 85014
 scriptlet: 19488
 html: 951
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2180-0, 1h.13m
  adguard-spyware-url: 1005-140, 1h.13m
  block-lan: 47-0, 1h.13m
  curben-phishing: 86709-35, 1h.13m
  curben-pup: 194-0, 1h.13m
  fanboy-cookiemonster: 61271-14612, 1h.13m
  NOR-0: 3145-9, 1h.13m
 default: 
  user-filters: 3-0, never
  ublock-filters: 34435-96, 1h.13m
  ublock-badware: 6997-1, 1h.13m
  ublock-privacy: 443-2, 1h.13m
  ublock-abuse: 70-70, 1h.13m
  ublock-unbreak: 2009-4, 1h.13m
  ublock-quick-fixes: 214-0, 1h.13m
  easylist: 66079-539, 1h.13m
  easyprivacy: 32463-639, 1h.13m
  urlhaus-1: 6733-1, 1h.13m
  plowe-0: 3741-2, 1h.13m
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 1 redacted]
hostRuleset: 
 added: [array of 17 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 876 ms (selfie)
 maxAssetCacheWait: 299 ms
popupPanel: 
 blocked: 3
 network: 
  getsentry.com: 1
  googletagmanager.com: 1
  optimizely.com: 1
```
</details>

**Comment by mapx-** [comment]
maybe it should be added to the regional list @DandelionSprout 

add

`direktesport.no##[aria-label="Informasjonskapsler"]`

**Comment by DandelionSprout** [comment]
My list generally doesn't do cookie notification blocking; instead I usually recommend I Don't Care About Cookies for when Nordic users need to block such notifications.

**Comment by stephenhawk8054** [comment]
I think it's more suitable for EC.

@ryanbr
