### ISSUE TITLE
cazztv.xyz: detection

### ISSUE THREAD

**Issue by Gythion** [uBlockOrigin/uAssets#17878]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cazztv.xyz/stream.php?id=10`

### Category

detection

### Description

Ublock detected, also on Starlive

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 99328
 cosmetic: 48052
 scriptlet: 17510
 html: 952
listset (total-discarded, last-updated): 
 added: 
  https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
  https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
 default: 
  user-filters: 0-0, never
  ublock-filters: 34491-64, 1d.12h.36m
  ublock-badware: 6997-1, 1d.12h.37m
  ublock-privacy: 373-0, 1d.12h.42m
  ublock-abuse: 70-0, 1d.12h.41m
  ublock-unbreak: 2019-3, 1d.12h.38m
  easylist: 66018-613, 1d.12h.35m
  easyprivacy: 32985-610, 1d.12h.34m
  plowe-0: 3741-2, 1d.12h.40m
  ITA-0: 13601-1, 16m
  urlhaus-1: 6796-1, 16m
  ublock-quick-fixes: 213-0, 16m
filterset (user): [empty]
trustedset: 
 added: [array of 6 redacted]
 removed: 
  moz-extension-scheme
modifiedUserSettings: 
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1244 ms
 maxAssetCacheWait: 471 ms
popupPanel: 
 blocked: 12
 network: 
  amung.us: 2
  asccdn.com: 2
  awstats.cloud: 2
  dilutionavailstoker.com: 2
  googlesyndication.com: 2
  histats.com: 1
  superfastcdn.com: 1
 cosmetic: 
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by mapx-** [comment]
it seems that stream is offline ?

test
`cazztv.xyz##+js(noeval-if, show)`

**Comment by sekko91** [comment]
online rn but impossible to watch bc it detects the adblock

**Comment by mapx-** [comment]
update your filter lists, no detection FF / chrome
