### ISSUE TITLE
supremacy1914.com: ads

### ISSUE THREAD

**Issue by Dripping-Ice** [uBlockOrigin/uAssets#17876]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.supremacy1914.com/game.php?bust=1&uid=51478595`

### Category

ads

### Description

Shows ads in the black bar on the right. Similar post has been closed, so i made a new one.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Screenshot 2023-04-30 130226](https://user-images.githubusercontent.com/88428907/235347371-95a2684a-a59a-4e57-b2e5-7f6f8923b879.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 239709
 cosmetic: 232416
 scriptlet: 39121
 html: 1114
listset (total-discarded, last-updated): 
 removed: 
  user-filters: null
 added: 
  adguard-generic: 70435-4897, 2m
  adguard-mobile: 8711-140, 2m
  adguard-spyware-url: 1005-5, 2m
  block-lan: 47-0, 2m
  curben-phishing: 84241-35, 2m
  curben-pup: 194-0, 2m
  adguard-annoyance: 67783-1562, 2m
  adguard-social: 20380-41, 2m
  fanboy-thirdparty_social: 69-0, 2m
  fanboy-annoyance: 90427-21243, 2m
  ublock-annoyances: 4926-6, 2m
  dpollock-0: 11357-470, 2m
  ara-0: 2782-0, 2m
  FRA-0: 28784-511, 2m
 default: 
  ublock-filters: 34389-54, 3m
  ublock-badware: 7004-0, 3m
  ublock-privacy: 443-0, 2m
  ublock-abuse: 70-70, 2m
  ublock-unbreak: 2009-4, 2m
  ublock-quick-fixes: 214-0, 2m
  easylist: 66260-1818, 2m
  easyprivacy: 32246-701, 2m
  urlhaus-1: 6796-1, 2m
  plowe-0: 3741-3, 2m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 741 ms (selfie)
 maxAssetCacheWait: 479 ms
popupPanel: 
 blocked: 13
 network: 
  bytro.com: 9
  helpshift.com: 1
  rubiconproject.com: 3
```
</details>

**Comment by mapx-** [comment]
report at easylist repository

`||bytro.com^$image,domain=supremacy1914.com`
