### ISSUE TITLE
Pinterest ads not blocked

### ISSUE THREAD

**Issue by Doeke** [uBlockOrigin/uAssets#17877]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Pinterest filters stopped working a while ago. Note the ads don't immediately show up, it seems pinterest starts inserting them after user is browsing for a while. This makes it harder to debug/verify!

I suspect Pinterest made a change to their html and previous selectors/filters dont work. I saw someone else also reported this a few days ago but it was closed because of the way Pinterest inserts the ads only after a while makes it look like the filters are working when they're not.

### URL(s) where the issue occurs.

https://nl.pinterest.com/
https://nl.pinterest.com/pin/850828554622853985/

### Screenshot(s)

![image](https://user-images.githubusercontent.com/240530/235348023-3e9e751a-06db-4f8f-bfa0-3eb7b0fa8780.png)

(The ads in the screenshot are dutch but normally they are just blocked when I enable EasyDutch list)

### uBO version

1.49.0

### Browser name and version

Chrome 112.0.5615.138

### Settings

The only change I made was to enable the EasyDutch list.

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/17822#issuecomment-1526533509

- update uBO to the last version, update all the filter lists
