### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by Necessarycoot72** [uBlockOrigin/uAssets#17875]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/1SXvU/Stars.Arisen.rar`

### Category

detection

### Description

When I went to download a game from mega and when the 5 second countdown finished it said it detected ublock.
https://user-images.githubusercontent.com/21312478/235338287-518e8f04-75b1-4013-afaa-bd5cb82463b6.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 231506
 cosmetic: 204896
 scriptlet: 39579
 html: 1114
listset (total-discarded, last-updated): 
 added: 
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 43377-17570, now
  adguard-generic: 70435-6295, now
  adguard-mobile: 8711-98, now
  adguard-spyware-url: 1005-5, now
  block-lan: 47-0, now
  curben-phishing: 84241-33, now
  curben-pup: 194-0, now
  adguard-annoyance: 67783-6083, now
  fanboy-annoyance: 90426-15320, now
  ublock-annoyances: 4927-4, now
 default: 
  user-filters: 23-4, never
  ublock-filters: 34389-96, now
  ublock-badware: 7002-0, now
  ublock-privacy: 443-0, now
  ublock-abuse: 70-70, now
  ublock-unbreak: 2009-3, now
  ublock-quick-fixes: 214-0, now
  easylist: 66260-706, now
  easyprivacy: 32246-617, now
  urlhaus-1: 6796-1, now
  plowe-0: 3741-4, now
filterset (user): [array of 23 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 482 ms (selfie)
 maxAssetCacheWait: 260 ms
popupPanel: 
 blocked: 9
 network: 
  megaup.net: 2
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 1
  dmmzkfd82wayn.cloudfront.net: 2
  googletagmanager.com: 1
  keydawnawe.com: 1
 cosmetic: 
  ##.socialsider
  ##body .metaRedirectWrapperBottomAds > div > .imgAds > img:style(padding-left: 10000px !important;)
  ##body .metaRedirectWrapperBottomAds:style(pointer-events: none !important;)
  ##body:style(overflow-x: hidden !important;)
  ##.metaRedirectWrapperBottomAds img:style(width: 300px !important;)
  ##.metaRedirectWrapperBottomAds a > img:style(visibility: visible !important;)
  ##.imgAds:style(height: 250px !important;)
  ##.imgAds > img:style(height: 250px !important;)
  ##.metaRedirectWrapperBottomAds > *:style(pointer-events: none !important;)
```
</details>

**Comment by bookarticle** [comment]
anti-adblock

**Comment by TCCB** [comment]
I get the exact same issue, so I don't think it's "resolved" interesting thing is for a while it was intermittent, but now it's permanent

**Comment by mapx-** [comment]
@TCCB disable the stable uBO and install last dev build of uBO
for chrome is here: https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii
