### ISSUE TITLE
walla.co.il - video ads

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#1787]
Default Settings + EasyList Hebrew
We only managed to hide the video ads - audio is still being played.
Do you have any idea how to fix it?

**Comment by mapx-** [comment]
an example of such page /video ?

**Comment by IsraeliAdblocker** [comment]
`https://news.walla.co.il/item/3145435`

New WebRTC.

$webrtc isn't working.

**Comment by mapx-** [comment]
No issue for me - the video is running fine (probably the video ads are pushed only for ISR IPs)

**Comment by IsraeliAdblocker** [comment]
It's true, you can use a VPN like hola or something. can you see the webRTC connection under chrome://webrtc-internals?

**Comment by uBlock-user** [comment]
> $webrtc isn't working.

$webrtc doesn't exist for uBlock Origin.

**Comment by mapx-** [comment]
`Hola VPN does not open websites from Israel`

**Comment by okiehsch** [comment]
>  you see the webRTC connection under chrome://webrtc-internals?

Yes,
![unbenannt](https://user-images.githubusercontent.com/16838044/37933552-e2b3f77e-314b-11e8-8de0-71e3db1e0c6f.PNG)

but I do not get any video ads.

**Comment by okiehsch** [comment]
I can disable all webRTC connections on my end by adding
`walla.co.il##script:inject(abort-on-property-read.js, TextDecoder)`
no clue if this solves your issue, or if this breaks some site functionality.

**Comment by IsraeliAdblocker** [comment]
@okiehsch working like a charm

**Comment by mapx-** [comment]
yeah, it would be better maintaining your own specific uBo filters @IsraeliUser

**Comment by IsraeliUser** [comment]
I don't think it's necessary at this point.
We do have some uBO-specific filters in our list (`$redirect`, `$important`).
We don't use `script:inject` filters because issues with other adblockers.
Please add this filter to uBO's filters.

**Comment by IsraeliUser** [comment]
Ads are back.
Please add:
`walla.co.il##script:inject(abort-current-inline-script.js, btoa, upManager)`
`walla.co.il##script:inject(abort-current-inline-script.js, atob, TextDecoder)`

**Comment by IsraeliUser** [comment]
@okiehsch @mapx-

**Comment by okiehsch** [comment]
What is the issue exactly, if it is still the webRTC connection then I fail to see how your proposed filters
````
walla.co.il##script:inject(abort-current-inline-script.js, btoa, upManager)
walla.co.il##script:inject(abort-current-inline-script.js, atob, TextDecoder)
````
can fix that.

After I add your filters:
![unbenannt](https://user-images.githubusercontent.com/16838044/38176696-dbf7a1ea-35f3-11e8-86d2-cd5e952242e8.PNG)

I can prevent that webRTC connection, without breaking the video player, by adding
`@@||broomhilda.eu-west-1.elasticbeanstalk.com^$xmlhttprequest,domain=walla.co.il`
