### ISSUE TITLE
sport.tvp.pl: detection

### ISSUE THREAD

**Issue by krainaGSM** [uBlockOrigin/uAssets#17871]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sport.tvp.pl/69529305/hokej-na-lodzie-mistrzostwa-swiata-w-dywizji-1a-mezczyzn-polska-litwa-wynik-relacja-strzelcy`

### Category

detection

### Description

It detects ublock as adblock, videos cannot be played.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 137919
  cosmetic: 97547
  scriptlet: 32246
  html: 1166
listset (total-discarded, last-updated): 
  added: 
    https://www.certyficate.it/adblock/adblock_cookies.txt: 9731-15, 2d.7m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 43369-4354, 2d.10h.46m
    adguard-generic: 70438-6459, 18m
    adguard-mobile: 8706-98, 2d.10h.49m
    adguard-spyware-url: 1002-5, 2d.10h.48m
  default: 
    user-filters: 1-0, never
    ublock-filters: 34608-202, 2d.10h.47m
    ublock-badware: 6956-0, 2d.10h.50m
    ublock-privacy: 373-0, 2d.10m
    ublock-abuse: 70-0, 2d.23h.21m
    ublock-unbreak: 2017-4, 19m
    ublock-quick-fixes: 215-0, 15m
    easylist: 65793-577, 2d.10h.45m
    easyprivacy: 30891-12933, 17m
    urlhaus-1: 6776-1, 14m
    plowe-0: 3746-3, 2d.23h.22m
    POL-0: 7940-25, 16m
    POL-2: 1278-13, 2d.8m
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 9 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 480 ms (selfie)
  maxAssetCacheWait: 273 ms
popupPanel: 
  blocked: 16
  blockedDetails: 
    tvp.pl: 3
    gemius.pl: 8
    google-analytics.com: 2
    google.com: 1
    google.pl: 1
    googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
All fine on my end in FF / chrome.

Test again using only the default filters + polish lists.

**Comment by krainaGSM** [comment]
![Schowek03](https://user-images.githubusercontent.com/114491876/235324733-abe25842-635f-41a2-8c79-174ce1072549.jpg)

![Schowek01](https://user-images.githubusercontent.com/114491876/235324702-91a463d1-2a4a-4c9b-ac70-69bc874f7b06.jpg)

![Schowek02](https://user-images.githubusercontent.com/114491876/235324740-fdbf764f-e7ba-4b71-bef6-cb0d340a9f39.jpg)

**Comment by mapx-** [comment]
No. You do not use only the default lists.

Reset uBO to default settings / lists, update then all the lists and test again (and do not use any other addon / extension during the test)

**Comment by gorhill** [comment]
At first I was able to reproduce with default lists. I forced an update of all default lists, and I still could reproduce. I then enabled both POL lists, and I got some error message, but no detection. I used a POL IP address, then the video played fine. So I guess the solution is in one of the POL filter lists.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
