### ISSUE TITLE
spyber.com: ad placeholders

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#17883]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Issue's title pretty much explains it all. The site has placeholders on the right side.
`spyber.com##.menubox:has(ins.adsbygoogle)` can be added to get rid of the placeholders.

### URL(s) where the issue occurs.

`https://www.spyber.com/`

### Screenshot(s)

![Screenshot from 2023-04-30 14-09-38](https://user-images.githubusercontent.com/89158249/235369304-ad446a03-5def-46c8-91fc-ac34b9c7ecf4.png)

### uBO version

v1.49.3b3

### Browser name and version

Firefox 112.0.2

### Settings

- Using all filters listed under Ads, Tracking, and Malware, and use uBlock annoyances and EasyList Cookie
- Check "I am an advanced user"

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
or report directly at easylist repository https://github.com/easylist/easylist/issues
