### ISSUE TITLE
clubs1.bg: breakage

### ISSUE THREAD

**Issue by rado84-github** [uBlockOrigin/uAssets#17884]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://clubs1.bg/`

### Category

breakage

### Description

When you click on an article and scroll down a bit, normally you should see the Disqus platform for commenting on the article. However, without adding disqus.com to trusted sites you won't see it bc it's simply blocked and hidden by uBlock Origin.
Below is an exemplary screenshot with an article from that website and what Disqus looks like when it's not blocked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Picture_created_01-05-2023_01-28-39](https://user-images.githubusercontent.com/41172201/235378965-27bc81c4-3c00-46ff-9655-9f0ebfacc79a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 93793
 cosmetic: 23604
 scriptlet: 17600
 html: 953
listset (total-discarded, last-updated): 
 default: 
  user-filters: 212-4, never
  ublock-filters: 34580-282, 3d.9h.2m
  ublock-badware: 6956-1, 3d.9h.1m
  ublock-privacy: 370-1, 6d.14h.28m
  ublock-abuse: 70-0, 6d.14h.27m
  ublock-unbreak: 2011-2, 3d.9h
  easylist: 65830-17412, 3d.9h.3m
  easyprivacy: 32644-612, 22h.42m
  urlhaus-1: 6726-1, 5h.49m
  plowe-0: 3746-2, 5d.20h.48m
  BGR-0: 1091-19, 1d.10h.13m
  ublock-quick-fixes: 214-0, 12h.13m
filterset (user): [array of 212 redacted]
trustedset: 
 added: [array of 7 redacted]
switchRuleset: 
 added: [array of 4 redacted]
 removed: 
  no-csp-reports: * true
modifiedUserSettings: 
 contextMenuEnabled: false
 ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 240 ms (selfie)
 maxAssetCacheWait: 78 ms
popupPanel: 
 blocked: 11
 network: 
  cloudflareinsights.com: 2
  google.com: 5
  googletagmanager.com: 1
  googletagservices.com: 1
  pxf.io: 2
```
</details>

**Comment by rado84-github** [comment]
That's exactly how I created the logs last night (visiting the page that suffers the problem, then opening the log window), I simply forgot to attach them there.
[disqus-log.txt](https://github.com/uBlockOrigin/uAssets/files/11365606/disqus-log.txt)

**Comment by gorhill** [comment]
Are the disqus comments showing fine if you navigate directly to [the disqus frame](https://disqus.com/embed/comments/?base=default&f=club-s1&t_i=177045%20https%3A%2F%2Fclubs1.bg%2F%3Fp%3D177045&t_u=https%3A%2F%2Fclubs1.bg%2Fnews%2Ffia-sthe-predprieme-merki-za-da-izbegne-povtorenie-na-inczidenta-na-okon-v-boksa%2F&t_e=%D0%A4%D0%98%D0%90%20%D1%89%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D0%B5%D0%BC%D0%B5%20%D0%BC%D0%B5%D1%80%D0%BA%D0%B8%2C%20%D0%B7%D0%B0%20%D0%B4%D0%B0%20%D0%B8%D0%B7%D0%B1%D0%B5%D0%B3%D0%BD%D0%B5%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%B8%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%20%D1%81%20%D0%9E%D0%BA%D0%BE%D0%BD%20%D0%B2%20%D0%B1%D0%BE%D0%BA%D1%81%D0%B0&t_d=%D0%A4%D0%98%D0%90%20%D1%89%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D0%B5%D0%BC%D0%B5%20%D0%BC%D0%B5%D1%80%D0%BA%D0%B8%2C%20%D0%B7%D0%B0%20%D0%B4%D0%B0%20%D0%B8%D0%B7%D0%B1%D0%B5%D0%B3%D0%BD%D0%B5%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%B8%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%20%D1%81%20%D0%9E%D0%BA%D0%BE%D0%BD%20%D0%B2%20%D0%B1%D0%BE%D0%BA%D1%81%D0%B0&t_t=%D0%A4%D0%98%D0%90%20%D1%89%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D0%B5%D0%BC%D0%B5%20%D0%BC%D0%B5%D1%80%D0%BA%D0%B8%2C%20%D0%B7%D0%B0%20%D0%B4%D0%B0%20%D0%B8%D0%B7%D0%B1%D0%B5%D0%B3%D0%BD%D0%B5%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%B8%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%20%D1%81%20%D0%9E%D0%BA%D0%BE%D0%BD%20%D0%B2%20%D0%B1%D0%BE%D0%BA%D1%81%D0%B0&s_o=default#version=93621f724643ecd0f307feb8123718cb)?

**Comment by mapx-** [comment]
> visiting the page that suffers the problem, then opening the log window

Wrong: first open uBO's logger, then visit that page, go back in the logger copy and paste here the blocked requests

gorhill asked you another thing:
`troubleshooting information`
read again how to get it and post it here

**Comment by rado84-github** [comment]
> Are the disqus comments showing fine if you navigate directly to [the disqus frame](https://disqus.com/embed/comments/?base=default&f=club-s1&t_i=177045%20https%3A%2F%2Fclubs1.bg%2F%3Fp%3D177045&t_u=https%3A%2F%2Fclubs1.bg%2Fnews%2Ffia-sthe-predprieme-merki-za-da-izbegne-povtorenie-na-inczidenta-na-okon-v-boksa%2F&t_e=%D0%A4%D0%98%D0%90%20%D1%89%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D0%B5%D0%BC%D0%B5%20%D0%BC%D0%B5%D1%80%D0%BA%D0%B8%2C%20%D0%B7%D0%B0%20%D0%B4%D0%B0%20%D0%B8%D0%B7%D0%B1%D0%B5%D0%B3%D0%BD%D0%B5%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%B8%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%20%D1%81%20%D0%9E%D0%BA%D0%BE%D0%BD%20%D0%B2%20%D0%B1%D0%BE%D0%BA%D1%81%D0%B0&t_d=%D0%A4%D0%98%D0%90%20%D1%89%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D0%B5%D0%BC%D0%B5%20%D0%BC%D0%B5%D1%80%D0%BA%D0%B8%2C%20%D0%B7%D0%B0%20%D0%B4%D0%B0%20%D0%B8%D0%B7%D0%B1%D0%B5%D0%B3%D0%BD%D0%B5%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%B8%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%20%D1%81%20%D0%9E%D0%BA%D0%BE%D0%BD%20%D0%B2%20%D0%B1%D0%BE%D0%BA%D1%81%D0%B0&t_t=%D0%A4%D0%98%D0%90%20%D1%89%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D0%B5%D0%BC%D0%B5%20%D0%BC%D0%B5%D1%80%D0%BA%D0%B8%2C%20%D0%B7%D0%B0%20%D0%B4%D0%B0%20%D0%B8%D0%B7%D0%B1%D0%B5%D0%B3%D0%BD%D0%B5%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%20%D0%B8%D0%BD%D1%86%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%20%D1%81%20%D0%9E%D0%BA%D0%BE%D0%BD%20%D0%B2%20%D0%B1%D0%BE%D0%BA%D1%81%D0%B0&s_o=default#version=93621f724643ecd0f307feb8123718cb)?

Yes.

**Comment by mapx-** [comment]
visit that page = refresh the page

**Comment by mapx-** [comment]
If you installed some other blocking addon, disable it and test again

![image](https://user-images.githubusercontent.com/10303732/235477359-f0a16534-6b35-4995-8b94-284673b5ab00.png)

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
