### ISSUE TITLE
office.org: potential badware

### ISSUE THREAD

**Issue by jhey29** [uBlockOrigin/uAssets#17880]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

office.org, a lookalike domain of a common open source tool, serves a suspiciously small executable pretending to be OpenOffice 4.1.9, and is made by a german company running other adware or malware services like vlc.de. It expresses itself in at least german, english, and french, correctly detecting which country i am in.

### URL(s) where the issue occurs.

`https://office.org/`

### uBO version

1.49.0

### Browser name and version

Firefox 112.0.2 (64-Bit)

### Settings

Factory Reset
Reenter DuckDuckGo personal filters
disable personal filters

### Notes

vlc.de is already filtered by uBO: Badware Risks.
The preview text in ddg shows the affiliated company when searching for "aller media e k"

**Comment by Yuki2718** [comment]
The domain is very old (registered on 1995-06-21), needs more evidence.

**Comment by JobcenterTycoon** [comment]
The file seems to be a installer but i see no VT detections (the file from `vlc.de` has 1 detection).

But i see the "[EULA](https://www.office.org/de/eula/)" from `vlc.de` and `office.org` are the same

>  Die Ausführung der Software erfolgt auf eigenes Risiko des Benutzers. Jegliche Haftung durch den Anbieter ist vollständig ausgeschlossen. Die Software selbst ist kostenlos. Die Software wird Veränderungen an Ihrem PC vornehmen. Insbesondere wird Ihre Startseite des Browsers verändert, es werden Symbole auf dem Desktop abgelegt / verändert sowie ein Updater installiert. Der Updater kann Software nachladen.

So it changing the browser start site and it load more crap. Yes im pretty sure its adware. But to be sure @iam-py-test

**Comment by ghajini** [comment]
.exe yku described here is malicious according to VT
what you expect from crackware sites? there are so many sites offering that

ofc they will be flagged by VT or any antimalware softwares

report such to
``` https://gitlab.com/malware-filter/urlhaus-filter#malicious-url-blocklist
https://urlhaus.abuse.ch/api/#submit
```

**Comment by JobcenterTycoon** [comment]
I get no detection https://www.virustotal.com/gui/file/12dfb311577abf2a3b2ae6dd6610b2e5cb331e520a6c5a09f605f6f8f3c334a4 OpenOffice and LibreOffice are free at all so there is no "crack" needed. `urlhaus.abuse.ch` doesn’t accept adware but i get no malware at the moment from the download page.

**Comment by ghajini** [comment]
`https://www.virustotal.com/gui/file/daf1b619f5eea4f9266293265cd696648142d6c6b6f8669ee9894effc4c21dd7/detection`

**Comment by ghajini** [comment]
there are so many websites offering crackware
its best handled by av softwares
