### ISSUE TITLE
linkvertise.com: ads

### ISSUE THREAD

**Issue by Pradyut1188** [uBlockOrigin/uAssets#17885]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/`

### Category

ads

### Description

Not working 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox Mobile: 112
filterset (summary): 
 network: 94527
 cosmetic: 30335
 scriptlet: 17676
 html: 953
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34793-301, 2d.11h.48m
  ublock-badware: 6981-1, 2d.11h.48m
  ublock-privacy: 373-1, 2d.11h.48m
  ublock-abuse: 70-0, 2d.11h.48m
  ublock-unbreak: 2021-2, 2d.11h.48m
  ublock-quick-fixes: 210-0, 15h.3m
  adguard-mobile: 8711-120, 15h.4m
  easylist: 65793-17437, 2d.11h.48m
  easyprivacy: 32644-618, 2d.11h.48m
  urlhaus-1: 6796-1, 15h.3m
  plowe-0: 3746-2, 2d.5h.14m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1341 ms (selfie)
 maxAssetCacheWait: 120 ms
popupPanel: 
 blocked: 22
 network: 
  bizseasky.com: 2
  go2speed.org: 7
  googletagmanager.com: 1
  media.net: 2
  sentry.io: 1
  taboola.com: 6
  thinksuggest.org: 2
  typekit.net: 1
 cosmetic: 
  ##.advertise
  ##lv-taboola-ctr-ad-dummy
```
</details>

**Comment by mapx-** [comment]
> Not working

> ads

provide a valid explanation, steps to reproduce your issue, screenshot (if you really see ads)

**Comment by mapx-** [comment]
@iSmokeMid69 
- could you explain what are fixing your filters ?
- specific link ?

**Comment by mapx-** [comment]
replace your last filter with

`linkvertise.com##.ng-star-inserted.lv-orange.lv-button-size-mobile.lv-button-size-desktop.lv-button-component`

**Comment by mapx-** [comment]
You replaced that filter using mine above: does it work or not ?

**Comment by mapx-** [comment]
the free access button is completely visible now on my end (FF pc emulation)

**Comment by ghajini** [comment]
This https://github.com/uBlockOrigin/uAssets/commit/12c71df345cd060d1b13d722c64ad49dac5602c0
should fix original issue

firefox android
use different ip to reproduce
