### ISSUE TITLE
skip.li [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1788]
URL(s) where the issue occurs

`https://skip.li/rf9zulz`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.18

Settings

Default

**Comment by mapx-** [comment]
It does not block the functionality, right ? 

However, see if works
`skip.li##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)`

**Comment by KiLL4FuNK** [comment]
@mapx- It works perfect  `skip.li##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)`

**Comment by mapx-** [comment]
yes, but it's only an annoyance, right ?

**Comment by KiLL4FuNK** [comment]
no need to add it

it's just a message
