### ISSUE TITLE
tiktok.com: nuisance

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#17888]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tiktok.com/@jornaldebrasilia/video/7217956317376433414`

### Category

nuisance

### Description

Annoying captcha popping-up in screen. It is not truely required to be solved in order to watch the videos.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 115134
 cosmetic: 120782
 scriptlet: 33662
 html: 952
listset (total-discarded, last-updated): 
 added: 
  https://fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 1h.21m
  https://filters.adtidy.org/extension/ublock/filters/2.txt: 136677-71646, 20h.4m
  https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-1955, 10h.30m
  fanboy-cookiemonster: 46723-214, 8d.21h.38m
 default: 
  user-filters: 63-7, never
  ublock-filters: 34526-126, 20h.12m
  ublock-badware: 6997-1, 20h.11m
  ublock-privacy: 443-0, 20h.10m
  ublock-abuse: 70-70, 20h.9m
  ublock-unbreak: 2009-2, 20h.8m
  ublock-quick-fixes: 210-0, 20h.3m
  easylist: 66260-662, 20h.7m
  easyprivacy: 32644-627, 20h.6m
  urlhaus-1: 6726-1, 8h.29m
  plowe-0: 3746-3, 8d.21h.38m
  spa-1: 5194-12, 20h.5m
filterset (user): [array of 63 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  moz-extension-scheme
switchRuleset: 
 added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 833 ms (selfie)
 maxAssetCacheWait: 411 ms
popupPanel: 
 blocked: 33
 network: 
  tiktok.com: 14
  byteoversea.com: 16
  tiktokv.com: 3
 cosmetic: 
  ##tiktok-cookie-banner
```
</details>

**Comment by mapx-** [comment]
try

```
tiktok.com###tiktok-verify-ele
tiktok.com##body:style(overflow:auto !important)
```

**Comment by Daxy7** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19009#issuecomment-1925218069

> seems that something changed in tiktok code and `##+js(aeld, visibilitychange, pagehide)` no longer keeps the video playing in a new tab. test link:
> ```
> https://www.tiktok.com/@jadafacer/video/82714842335199232
> ```
>
