### ISSUE TITLE
gutefrage.net: detection

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [uBlockOrigin/uAssets#17892]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gutefrage.net/frage/was-tun-um-7-uhr-morgens-in-ingolstadt`

### Category

detection

### Description

shows this: https://ibb.co/JKmD35p

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 107
filterset (summary): 
 network: 95799
 cosmetic: 44710
 scriptlet: 17486
 html: 949
listset (total-discarded, last-updated): 
 default: 
  user-filters: 71-13, never
  ublock-filters: 34415-66, 1d.11h.44m
  ublock-badware: 6997-0, 1d.11h.43m
  ublock-privacy: 443-0, 12h.26m
  ublock-abuse: 70-70, 1h.19m
  ublock-unbreak: 2017-0, 1d.11h.39m
  easylist: 65998-614, 1d.22h.23m
  easyprivacy: 32985-618, 2d.23h.14m
  urlhaus-1: 6726-1, 16h.8m
  plowe-0: 3746-4, 6d.46m
  DEU-0: 6821-2, 16h.7m
  ublock-quick-fixes: 214-2, 1h.18m
filterset (user): [array of 71 redacted]
trustedset: 
 added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 324 ms (selfie)
 maxAssetCacheWait: 99 ms
popupPanel: 
 blocked: 16
 network: 
  gutefrage.net: 12
  eyeota.net: 1
  h5v.eu: 1
  timples.de: 1
  welect.de: 1
 cosmetic: 
  ##.Ad--header
  ##.banner_ad
  ##.full_ad
  ##.Ad
```
</details>

**Comment by JobcenterTycoon** [comment]
The checks and the bait iframe coming from `https://static.wlt-alice.de/p/bundles/18a75627-38d0-4fb1-a9da-0116ac532ff1.js?enabled=false&loggedIn=false#wbss` and after a detection a iframe from this site getting loaded. It looks like a crap only site @mapx- please take a look, maybe `||wlt-alice.de^` is enough.

**Comment by mapx-** [comment]
I'd add 
||wlt-alice.de^

and ghide for all those sites

**Comment by mapx-** [comment]
only the first for now
