### ISSUE TITLE
supremacy1914.fr: ads

### ISSUE THREAD

**Issue by Artos20** [uBlockOrigin/uAssets#17899]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.supremacy1914.fr/game.php?L=11&bust=1`

### Category

ads

### Description

![pub](https://user-images.githubusercontent.com/132318359/235563750-f14c9e13-0485-44a0-9198-dbfc0788686d.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 309696
 cosmetic: 278765
 scriptlet: 43518
 html: 0
listset (total-discarded, last-updated): 
 added: 
  ALB-0: 301-10, 13m
  BGR-0: 1091-19, 13m
  CHN-0: 27158-1371, 13m
  CZE-0: 737-40, 13m
  DEU-0: 6840-388, 13m
  EST-0: 460-11, 13m
  FIN-0: 2163-69, 13m
  GRC-0: 995-19, 13m
  HRV-0: 323-11, 13m
  HUN-0: 2175-82, 13m
  IDN-0: 5500-263, 13m
  IND-0: 12674-0, 13m
  IRN-0: 2872-16, 13m
  ISL-0: 194-2, 12m
  ISR-0: 1713-7, 13m
  ITA-0: 13601-486, 13m
  JPN-1: 11123-120, 13m
  KOR-1: 4357-89, 13m
  LTU-0: 1241-17, 13m
  LVA-0: 396-6, 13m
  [29 lists not shown]: [too many]
 default: 
  user-filters: 1-0, never
  FRA-0: 28283-3029, 13m
  easylist: 66392-18403, 13m
  easyprivacy: 32218-808, 13m
  plowe-0: 3742-1433, 12m
  ublock-abuse: 70-2, 12m
  ublock-badware: 6981-404, 12m
  ublock-filters: 33437-4564, 12m
  ublock-privacy: 393-79, 12m
  ublock-quick-fixes: 222-27, 12m
  ublock-unbreak: 2006-116, 12m
  urlhaus-1: 6656-2, 12m
filterset (user): [array of 1 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 778 ms (selfie)
 maxAssetCacheWait: 624 ms
popupPanel: 
 blocked: 7
 no-cosmetic-filtering: true
 network: 
  bytro.com: 6
  rubiconproject.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test if this works?

```adb
||bytro.com^$image,domain=supremacy1914.*
```

**Comment by mapx-** [comment]
@smed79

**Comment by stephenhawk8054** [comment]
@mapx- Looks like this site has multiple TLDs: https://github.com/uBlockOrigin/uAssets/issues/17876

**Comment by mapx-** [comment]
yes, I notified @ryanbr  .. but maybe we can add it in our list

**Comment by stephenhawk8054** [comment]
Yeah I agree, it needs wildcard domain anyway so might take some time until EL addresses it.

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/8cbd603cf7a10c864fbb0b4f48a379fb96e700b1
