### ISSUE TITLE
wallpapers.com: breakage

### ISSUE THREAD

**Issue by Insane-Owl** [uBlockOrigin/uAssets#17896]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wallpapers.com/wallpapers/black-and-white-pc-d11xysp5kl7mqrwo.html`

### Category

breakage

### Description

Hides the download button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 92956
 cosmetic: 40384
 scriptlet: 17494
 html: 949
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34420-61, now
  ublock-badware: 7015-0, now
  ublock-privacy: 443-0, now
  ublock-abuse: 70-70, now
  ublock-unbreak: 2016-4, now
  ublock-quick-fixes: 215-0, now
  easylist: 66392-610, now
  easyprivacy: 32218-609, now
  urlhaus-1: 6771-1, now
  plowe-0: 3742-3, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 920 ms
 maxAssetCacheWait: 4 ms
popupPanel: 
 blocked: 3
 network: 
  googlesyndication.com: 1
  googletagmanager.com: 2
 cosmetic: 
  ##.ads-marker
  ##ins.adsbygoogle
  ##.ad-holder
  ##.ad-block
  ##.ads-block
  ##.ad_marker
```
</details>

**Comment by mapx-** [comment]
add

`wallpapers.com#@#.ad-holder`

@ryanbr
