### ISSUE TITLE
betterstack.com: breakage

### ISSUE THREAD

**Issue by jonasdk** [uBlockOrigin/uAssets#17890]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://betterstack.com/better-uptime`

### Category

breakage

### Description

It is not possible to login to the site when having ublock enabled

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 112
filterset (summary): 
  network: 90237
  cosmetic: 40126
  scriptlet: 17766
  html: 953
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34845-52, 4d.21h.39m
    ublock-badware: 6956-0, 4d.21h.38m
    ublock-privacy: 372-0, 6d.21h.9m
    ublock-abuse: 70-0, 6d.21h.8m
    ublock-unbreak: 2004-2, 4d.21h.37m
    ublock-quick-fixes: 215-0, 1d.12h.9m
    easylist: 65836-630, 4d.21h.40m
    easyprivacy: 30897-1770, 4d.21h.36m
    urlhaus-1: 6776-1, 1d.12h.8m
    plowe-0: 3746-4, 6d.20h.57m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 6133 ms (selfie)
  maxAssetCacheWait: 120 ms
popupPanel: 
  blocked: 6
  blockedDetails: 
    ads-twitter.com: 1
    bing.com: 1
    facebook.net: 1
    googletagmanager.com: 1
    licdn.com: 1
    plausible.io: 1
```
</details>

**Comment by mapx-** [comment]
if you try to log in using fake user / pass do you still get the issue ?
