### ISSUE TITLE
mangasee123.com: breakage

### ISSUE THREAD

**Issue by devildragon777** [uBlockOrigin/uAssets#17897]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mangasee123.com/read-online/Solo-Leveling-chapter-180.html`

### Category

breakage

### Description

For some reason, Ublock breaks the scroll functionality when going from one chapter to the next or previous. It is most visible when using the bottom bar on long strip mode:
https://user-images.githubusercontent.com/41872899/235527270-80d416fa-15e5-4b59-87ba-c2e990ff5a2c.png

Scrolling works when adding an exception for bidgear.com in the popup panel, but then the remnants of an ad bar are at the top of every page: 
https://user-images.githubusercontent.com/41872899/235527624-510b58aa-b176-4d13-be92-efa912f1e2c1.png

...which is naturally kind of distracting as well.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 92857
 cosmetic: 40361
 scriptlet: 17481
 html: 949
listset (total-discarded, last-updated): 
 removed: 
  user-filters: null
 added: 
  ublock-quick-fixes: 215-3, 19m
 default: 
  ublock-filters: 34316-62, 19m
  ublock-badware: 6985-0, 19m
  ublock-privacy: 443-0, 19m
  ublock-abuse: 70-70, 19m
  ublock-unbreak: 2017-0, 19m
  easylist: 66392-610, 19m
  easyprivacy: 32218-609, 19m
  plowe-0: 3742-4, 19m
  urlhaus-1: 6771-1, 19m
filterset (user): [array of 145 redacted]
trustedset: 
 added: [array of 2 redacted]
 removed: 
  about-scheme
  edge-scheme
switchRuleset: 
 added: [array of 1 redacted]
hostRuleset: 
 added: [array of 44 redacted]
urlRuleset: 
 added: [array of 76 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
modifiedHiddenSettings: 
 autoUpdateAssetFetchPeriod: 120
 autoUpdateDelayAfterLaunch: 180
 autoUpdatePeriod: 7
 selfieAfter: 3
supportStats: 
 allReadyAfter: 521 ms (selfie)
 maxAssetCacheWait: 245 ms
 unsuspendAfter: 174 ms
popupPanel: 
 blocked: 7
 network: 
  bidgear.com: 6
  google-analytics.com: 1
```
</details>

**Comment by Procyon-b** [comment]
Weird. I can't reproduce.
And I've exactly the same stat numbers. But I see that you have rules.

**Comment by devildragon777** [comment]
I turned off "my filters" when I was checking the defaults, so I though that all my filter rules would be disabled as well. Is that not the case?

None of them are for this website, as well, so I'm not sure if they would be affecting it?

**Comment by okiehsch** [comment]
Works fine on my end.

**Comment by devildragon777** [comment]
Is there anything else I should be disabling to test it?

**Comment by Procyon-b** [comment]
> I turned off "my filters" when I was checking the defaults, so I though that all my filter rules would be disabled as well. Is that not the case?

Rules are in the tab "_My rules_" in ublock's dashboard. They are different from your filters which are in "_My filters_" and can be disabled entirely in the "_Filter list"_ tab. You'll have to investigate your rules to see if one can interfere with the site. Don't forget to make a backup copy before removing them.

**Comment by devildragon777** [comment]
Okay, so I tried it after deleting the rules. It works if I scroll up as the page is loading, but otherwise I get thrown back to the bottom of the page. I tried disabling autoscrolling as well, and that didn't seem to do anything...

Config:

<details>
<summary>Details</summary>
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 92857
 cosmetic: 40361
 scriptlet: 17481
 html: 949
listset (total-discarded, last-updated): 
 removed: 
  user-filters: null
 added: 
  ublock-quick-fixes: 215-0, 2m
 default: 
  ublock-filters: 34316-62, 2m
  ublock-badware: 6985-1, 2m
  ublock-privacy: 443-0, 2m
  ublock-abuse: 70-70, 2m
  ublock-unbreak: 2017-4, 2m
  easylist: 66392-610, 2m
  easyprivacy: 32218-609, 2m
  plowe-0: 3742-2, 2m
  urlhaus-1: 6771-1, 2m
filterset (user): [array of 145 redacted]
trustedset: 
 added: [array of 2 redacted]
 removed: 
  about-scheme
  edge-scheme
switchRuleset: 
 removed: 
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset: 
 removed: 
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
modifiedUserSettings: 
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
modifiedHiddenSettings: 
 autoUpdateAssetFetchPeriod: 120
 autoUpdateDelayAfterLaunch: 180
 autoUpdatePeriod: 7
 selfieAfter: 3
supportStats: 
 allReadyAfter: 521 ms (selfie)
 maxAssetCacheWait: 245 ms
 unsuspendAfter: 174 ms
</details>

**Comment by Procyon-b** [comment]
> It works if I scroll up as the page is loading

Whenever I click on "prev" or "next" at the bottom, it loads the other page and the focus is at the top of the page. There is no scrolling up for me.

Do you have other extensions? Are you using userscript(s)?

**Comment by devildragon777** [comment]
> Whenever I click on "prev" or "next" at the bottom, it loads the other page and the focus is at the top of the page. There is no scrolling up for me.
> 
> Do you have other extensions? Are you using userscript(s)?
> 
> Edit: Are you logged in by any chance? It could change the behaviour of the site (speculation - I don't know).

I turned off all other extensions when I was testing the Ublock filters, and even when I was using extensions the only one that fixed it was disabling UBO...

I am logged in, but I checked just now and logging out made no difference?

Having the console open also fixes it, so I think it might actually be a Firefox issue?

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by krystian3w** [comment]
Try also:

```adb
||bidgear.com^$image,redirect-rule=1x1.gif:-1
||bidgear.com^$script,xhr,redirect-rule=noop.js:-1
||bidgear.com^$media,redirect-rule=noop-1s.mp4:-1
||bidgear.com^$other,redirect-rule=noop.txt:-2
```

Maybe page wait in Firefox for any file even is empty or too short.

**Comment by krystian3w** [comment]
Also I see Firefox 113 to download as Relase Candidate: <sup>https://ftp.mozilla.org/pub/firefox/candidates/113.0-candidates/build1/</sup>


https://ftp.mozilla.org/pub/firefox/candidates/113.0-candidates/build1/win64/

**Comment by mapx-** [comment]
@devildragon777 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
