### ISSUE TITLE
Firebase Dashboard 

### ISSUE THREAD

**Issue by tnmendes** [uBlockOrigin/uAssets#17891]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlock is blocking a big part of the Firebase Dashboard website.

### URL(s) where the issue occurs.

https://console.firebase.google.com/

### uBO version

1.48.4

### Browser name and version

Chrome Version 112.0.5615.121 (Official Build) (arm64)

### Settings

NA

**Comment by okiehsch** [comment]
> is blocking a big part of the Firebase Dashboard website.


<details>
<summary>Screenshot(s)</summary>


![Unbenannt](https://user-images.githubusercontent.com/16838044/235433963-0a7063a5-37e9-4509-bca6-42871d35ccb8.PNG)

</details>

Looks fine on my end.

**Comment by mapx-** [comment]
Looks fine on my side too.

@tnmendes 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by tnmendes** [comment]
With Ublock active this is what i get
![Screenshot 2023-05-01 at 10 53 27](https://user-images.githubusercontent.com/9822076/235437501-7dd06866-2386-4bca-a144-ccb570d1d8d2.png)

**Comment by mapx-** [comment]
well, you have some analytics project I guess:

- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by tnmendes** [comment]
Website that on the network show as block:
https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/
https://play.google.com/log?format=json&hasfast=true&authuser=0


![Screenshot 2023-05-01 at 11 00 06](https://user-images.githubusercontent.com/9822076/235438216-ce8567e6-1366-4e63-9dcf-2efc1913f16b.png)

**Comment by mapx-** [comment]
see above, we need the uBO's logger entries

**Comment by tnmendes** [comment]
Okiy i will try out

**Comment by tnmendes** [comment]
![Screenshot 2023-05-01 at 11 09 17](https://user-images.githubusercontent.com/9822076/235438991-28848ef0-aa4f-4cd2-92e7-23147204eeba.png)

**Comment by mapx-** [comment]
test

`@@||firebaselogging-pa.googleapis.com/*/firelog/$xhr,domain=firebase.google.com`

**Comment by tnmendes** [comment]
Firebase still not showing all the screens:

With that filter this is the logger:
![Screenshot 2023-05-01 at 11 15 41](https://user-images.githubusercontent.com/9822076/235439618-2dc51b18-2e5b-42a9-9564-b88a4b6e3ff2.png)

**Comment by mapx-** [comment]
what about 

`@@||google.com/log?format=json$xhr,domain=firebase.google.com`

**Comment by tnmendes** [comment]
Same issue
![Screenshot 2023-05-01 at 11 22 21](https://user-images.githubusercontent.com/9822076/235440353-34578342-84c0-41eb-b584-f2de96fbb92b.png)

**Comment by mapx-** [comment]
try again

`@@||analytics.google.com^$domain=firebase.google.com`

**Comment by tnmendes** [comment]
Yeap now it worked

With this 3 filters added
@@||firebaselogging-pa.googleapis.com/*/firelog/$xhr,domain=firebase.google.com
@@||google.com/log?format=json$xhr,domain=firebase.google.com
@@||analytics.google.com^$domain=firebase.google.com

**Comment by mapx-** [comment]
if you keep only the last 1 does it still work ?

**Comment by tnmendes** [comment]
Yeap, it work using just the last one

**Comment by tnmendes** [comment]
@MasterKia Firebase is also a working tool for a lot of IT developers.
In the same way that I had this problem and I was not understanding what was the issue the first time that this happen many more devs should have the same. 
(P.S. I was already disabling UBlock for this site  but I think this would be better if I did this work out of the box for everyone )

**Comment by gorhill** [comment]
What was the error in the dev console when `analytics.google.com` was blocked?

**Comment by tnmendes** [comment]
@gorhill this was the error that I was getting 

![Screenshot 2023-05-01 at 16 43 56](https://user-images.githubusercontent.com/9822076/235480860-9c04fc54-db2f-4d00-8e49-814061e55b97.png)

And this is what I get after adding the filter that is working correctly:
`@@||analytics.google.com^$domain=firebase.google.com`
![Screenshot 2023-05-01 at 16 47 14](https://user-images.githubusercontent.com/9822076/235481494-747fdf55-c8b8-48bd-9630-e28bb6cc1757.png)
