### ISSUE TITLE
myap.collegeboard.org: breakage

### ISSUE THREAD

**Issue by Hielyr** [uBlockOrigin/uAssets#17895]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://myap.collegeboard.org/login`

### Category

breakage

### Description

When attempting to access this page, there is simply a blank page presented. 

When disabling uBlockOrigin, the page loads as expected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 93045
 cosmetic: 40264
 scriptlet: 17486
 html: 949
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34415-52, 4h.23m
  ublock-badware: 7039-0, 4h.23m
  ublock-privacy: 373-0, 3d.1h.9m
  ublock-abuse: 70-0, 3d.1h.8m
  ublock-unbreak: 2017-5, 4h.23m
  ublock-quick-fixes: 216-0, 4h.23m
  easylist: 66299-608, 4h.23m
  easyprivacy: 32242-609, 4h.23m
  urlhaus-1: 6771-1, 4h.23m
  plowe-0: 3741-3, 4h.23m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 163 ms (selfie)
 maxAssetCacheWait: 40 ms
popupPanel: 
 blocked: 11
 network: 
  adobedtm.com: 10
  appcues.com: 1
```
</details>

**Comment by mapx-** [comment]
see if this filter is enough

`@@||fast.appcues.com^$script,domain=myap.collegeboard.org`
