### ISSUE TITLE
Whitelisting of uploadocean by easylist

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#179]
### URL(s) where the issue occurs

`https://uploadocean.com/gkf3fo7ybt2k`
### Describe the issue

`Uploadocean.com` uses anti-adblock. 

For Adblock plus users the solution is the filterset
`@@/^((?!.*\.(amazonaws|cloudfront|mobicow|puhtml)\W?).)*$/$script,domain=uploadocean.com`
 `@@|http://$image,third-party,domain=uploadocean.com`
 `@@|https://$image,third-party,domain=uploadocean.com`
 `|http://$script,third-party,xmlhttprequest,domain=uploadocean.com`
 `|https://$script,third-party,xmlhttprequest,domain=uploadocean.com`
which was added to Easylist.

The result is nearly wholesale whitelisting of scripts on uploadocean.
![ocean](https://cloud.githubusercontent.com/assets/16838044/19823028/ba84b4a2-9d66-11e6-867d-5ce55456679b.PNG)

This is not necessary for uBlock users.
If you add
`uploadocean.com##script:inject(bab-defuser.js)`
`|http://$script,third-party,xmlhttprequest,domain=uploadocean.com,important`
`|https://$script,third-party,xmlhttprequest,domain=uploadocean.com,important`
you can use uploadocean without whitelisting nearly everything.
### Versions
- Browser/version: Chrome 54
- uBlock Origin version: 1.9.16

**Comment by okiehsch** [comment]
URL is not "live" anymore.

**Comment by gorhill** [comment]
Found one using google search. Your filters work, thanks for investigating (sorry for the delay, I don't remember noticing this issue in my notifications).
