### ISSUE TITLE
watson.de: ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#17901]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.watson.de/sport/bundesliga/271685368-borussia-dortmund-ex-star-koennte-ueberraschend-zum-bvb-zurueckkehren`

### Category

ads

### Description

ads showing

### Screenshot(s)

<details>
https://user-images.githubusercontent.com/81616288/235641815-6287fad1-aa34-4d1d-b36c-87f6fdb4737a.png
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 95034
 cosmetic: 44905
 scriptlet: 17487
 html: 949
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34328-116, 1m
  ublock-badware: 6985-1, 1m
  ublock-privacy: 443-0, 1m
  ublock-abuse: 70-70, 1m
  ublock-unbreak: 2017-4, 1m
  ublock-quick-fixes: 215-0, 1m
  easylist: 66411-546, now
  easyprivacy: 32223-649, now
  urlhaus-1: 6656-1, now
  plowe-0: 3742-2, now
  DEU-0: 6840-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 7412 ms (selfie)
 maxAssetCacheWait: 2367 ms
popupPanel: 
 blocked: 19
 network: 
  watson.de: 2
  adscale.de: 1
  chartbeat.com: 1
  criteo.net: 3
  doubleclick.net: 1
  doubleverify.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  jubbie.de: 1
  m6r.eu: 1
  speedcurve.com: 1
  taboola.com: 1
  theadex.com: 1
  undom.net: 1
  userreport.com: 1
  yieldlove.com: 1
 cosmetic: 
  ##.commercial
  ##.sdgSlotContainer
```
</details>

**Comment by mapx-** [comment]
add & check for breakage

`||cp.watson.de^`

**Comment by JobcenterTycoon** [comment]
@khrin its possible to fix this in EL germany with `||watson.de/addf/addefend.js`
