### ISSUE TITLE
aliexpress.com: popups

### ISSUE THREAD

**Issue by kaithaba** [uBlockOrigin/uAssets#17903]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aliexpress.com/w/wholesale-walking-stick-handle.html?catId=0&initiative_id=SB_20230502055313&SearchText=walking+stick+handle&spm=a2g0o.home.1000002.0`

### Category

popups

### Description

The site keeps opening a new tab `http://ww7.aliamaz.com/banner/` even if I've tried to block it multiple times. When it opens (it's just an empty page), it does try to redirect, and uBlock does detect it and block it:

( uBlock Origin has prevented the following page from loading:
`http://iyfbodn.com/?dn=aliamaz.com&pid=9POT3387I&pbsubid=a207f4dc-1cc6-e1a0-61d7-85737007dea1&noads=http%3A%2F%2Fiyfbodn.com%2F%3Fdn%3Daliamaz.com%26skipskenzo%3Dtrue`

Because of the following filter:
`||iyfbodn.com^`

Found in: [EasyList](moz-extension://3afbc1f5-057c-4767-882b-3a9796f95e98/asset-viewer.html?url=easylist) 

But it doesn't stop the new tab from popping up and taking you away from the item page. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 97
filterset (summary): 
  network: 93001
  cosmetic: 40432
  scriptlet: 17599
  html: 953
listset (total-discarded, last updated): 
  default: 
    user-filters: 18-1, never
    ublock-filters: 34556-53, 4d.5h.46m
    ublock-badware: 6961-0, 4d.5h.45m
    ublock-privacy: 373-0, 5d.16h.13m
    ublock-abuse: 70-0, 4d.20h.49m
    ublock-unbreak: 2014-0, 2h.46m
    ublock-quick-fixes: 211-4, 20h.18m
    easylist: 66459-610, 2h.47m
    easyprivacy: 32243-609, 2d.3h.51m
    urlhaus-1: 6771-1, 20h.19m
    plowe-0: 3746-4, 4d.20h.47m
filterset (user): [array of 18 redacted]
trustedset: 
  added: [array of 15 redacted]
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2290 ms (selfie)
  maxAssetCacheWait: 582 ms
popupPanel: 
  blocked: 19
  no-popups: true
  blockedDetails: 
    facebook.net: 1
    go-mpulse.net: 1
    google-analytics.com: 2
    mmstat.com: 12
    sedoparking.com: 1
    taobao.com: 1
    yandex.ru: 1
```
</details>

**Comment by Yuki2718** [comment]
Neither can I reproduce.

**Comment by mapx-** [comment]
Maybe your system @kaithaba  is infested by some malware.

**Comment by kaithaba** [comment]
> Maybe your system @kaithaba is infested by some malware.

That's what I thought, too, before reporting--but I just ran a check and Malwarebytes didn't find any. 🤷‍♀️ I will see if

**Comment by kaithaba** [comment]
Ah, bugger, sorry; I accidentally closed this thread and submitted my comment too soon. I meant to say I will do further checks tomorrow, but so far I haven't found anything. It's most odd, as I have strict adblocking and malware checks on all the time and haven't visited any dodgy sites. Ho hum.

**Comment by gorhill** [comment]
Latest uBO on Firefox is 1.49.0, you shouldn't be stuck to 1.43.0.
