### ISSUE TITLE
rtl.be: detection

### ISSUE THREAD

**Issue by fwood26** [uBlockOrigin/uAssets#17909]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.rtl.be/people/news/angele-eblouissante-pour-son-1er-met-gala-cest-tellement-fou/2023-05-02/article/548995`

### Category

detection

### Description

Dear Ublock origin team,

Recently rtl.be don't allow videos to be played while Ublock is active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/122359662/235858547-4cd599bc-e91f-4f97-b7fc-6286db34e726.png)

Seem to be the same on any page with a video

![image](https://user-images.githubusercontent.com/122359662/235859366-46ac5c3b-e381-4dfe-bc1e-2a55d4cf4835.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 92824
 cosmetic: 40361
 scriptlet: 17481
 html: 949
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34317-62, 23h.15m
  ublock-badware: 7039-0, 23h.15m
  ublock-privacy: 372-0, 8d.23h.19m
  ublock-abuse: 70-0, 8d.23h.18m
  ublock-unbreak: 2016-0, 23h.15m
  easylist: 66392-609, 23h.15m
  easyprivacy: 32242-609, 23h.15m
  urlhaus-1: 6656-1, 23h.15m
  plowe-0: 3746-4, 8d.23h.17m
  ublock-quick-fixes: 215-3, 11h.12m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1384 ms (selfie)
 maxAssetCacheWait: 471 ms
popupPanel: 
 blocked: 21
 network: 
  rtl.be: 4
  cxense.com: 1
  gemius.pl: 2
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 3
  newrelic.com: 2
  outbrain.com: 1
  ownpage.fr: 1
  pbstck.com: 1
  twitter.com: 4
```
</details>

**Comment by fwood26** [comment]
By the way thanks a lot to all the community for incredible work 😄

**Comment by skal-dB** [comment]
Same issue here : https://www.rtl.be/actu/belgique/politique/pas-de-hausse-des-impots-selon-georges-louis-bouchez-cet-economiste-nest-pas/2026-07-13/article/794432

<img width="794" height="717" alt="Image" src="https://github.com/user-attachments/assets/ce750052-8c47-4b30-932f-1373a50fecfc" /> 

### Plugin Report : 

uBlock Origin: 1.72.2
Firefox: 152
filterset (summary):
 network: 183111
 cosmetic: 43251
 scriptlet: 33633
 html: 3662
listset (total-discarded, last-updated):
 removed:
  FRA-0: null
 default:
  user-filters: 1-0, never
  ublock-filters: 52787-73, now
  ublock-badware: 10287-27, now
  ublock-privacy: 4064-2, now
  ublock-unbreak: 2841-1, now
  ublock-quick-fixes: 489-13, now
  easylist: 87166-140, now
  easyprivacy: 55963-41, now
  urlhaus-1: 48005-11, now
  plowe-0: 3523-1030, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 218 ms (selfie)
 maxAssetCacheWait: 100 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 11
 network:
  rtl.be: 1
  doubleclick.net: 1
  gemius.pl: 2
  googletagmanager.com: 1
  pbstck.com: 2
  privacy-center.org: 2
  taboola.com: 1
  videoadex.com: 1
 extended:
  ###taboola-below-article-thumbnails
