### ISSUE TITLE
timesofindia.com: nuisance

### ISSUE THREAD

**Issue by Malgotra** [uBlockOrigin/uAssets#17905]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.timesofindia.com/business/international-business/in-ai-fight-between-pichais-google-and-nadellas-microsoft-arvind-krishnas-ibm-and-many-others-will-bleed-jobs/articleshow/99941441.cms`

### Category

nuisance

### Description

App install annoyance in middle of the page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230502-220837~2](https://user-images.githubusercontent.com/122884037/235730270-93888e23-5858-4e18-b3be-5f53fdd623af.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox Mobile: 112
filterset (summary): 
 network: 220066
 cosmetic: 223105
 scriptlet: 39075
 html: 1114
listset (total-discarded, last-updated): 
 added: 
  adguard-generic: 70435-5457, 2d.1h.54m
  adguard-spyware-url: 1005-5, 2d.1h.54m
  block-lan: 47-0, 2d.1h.54m
  curben-phishing: 85588-34, 15m
  curben-pup: 192-0, 15m
  adguard-annoyance: 67783-5105, 2d.1h.54m
  adguard-social: 20380-698, 2d.1h.54m
  fanboy-thirdparty_social: 68-0, 2d.1h.54m
  fanboy-annoyance: 90455-80903, 2d.1h.54m
  fanboy-cookiemonster: 46884-251, 2d.1h.54m
  fanboy-social: 17204-17, 2d.1h.54m
  ublock-annoyances: 4987-4, 2d.1h.54m
  dpollock-0: 11357-469, 2d.1h.53m
 default: 
  user-filters: 0-0, never
  ublock-filters: 34660-111, 2d.2h.45m
  ublock-badware: 6998-1, 2d.2h.45m
  ublock-privacy: 443-0, 2d.2h.45m
  ublock-abuse: 70-70, 2d.2h.45m
  ublock-unbreak: 2021-5, 2d.2h.45m
  ublock-quick-fixes: 215-0, 15m
  adguard-mobile: 8711-128, 2d.2h.46m
  easylist: 66279-819, 2d.1h.55m
  easyprivacy: 32241-698, 2d.1h.55m
  urlhaus-1: 6708-1, 15m
  plowe-0: 3741-2, 2d.1h.55m
filterset (user): [empty]
modifiedUserSettings: 
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 9627 ms
 maxAssetCacheWait: 5898 ms
popupPanel: 
 blocked: 26
 network: 
  amazon-adsystem.com: 1
  appsflyer.com: 1
  clmbtech.com: 3
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 1
  growthrx.in: 1
  indiatimes.com: 1
  outbrainimg.com: 3
  pubmatic.com: 4
  rubiconproject.com: 3
  scorecardresearch.com: 1
  toiimg.com: 2
  yahoo.com: 1
 cosmetic: 
  ##.ATF_wrapper
  ##.social_footer
  ##div[class^=\"ATF_wrapper\"]
  ##.ctn-workaround-div
  ##.mob-share-button
  ##div[id^=\"custom_ad\"]
  ##div[class^=\"ATF_container_min_height\"]
  ##.phShimmer
  ##div[id^=\"div-gpt-ad\"]
  ##[id^=\"google_ads_iframe\"]
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##.dfp_ATF_wrapper
  ###colombiaAdBox
  ##[id^=\"div-gpt-ad\"]:style(width:1px!important;height:1px!important;min-width:1px!important;min-height:1px!important;margin:0!important;padding:0!important;overflow:hidden!important;opacity:0!important)
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by mapx-** [comment]
test

`m.timesofindia.com##[href*="app.goo.gl"]`

**Comment by Malgotra** [comment]
Yes. This works
