### ISSUE TITLE
bouyguestelecom.fr: breakage

### ISSUE THREAD

**Issue by piorrro33** [uBlockOrigin/uAssets#17902]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bouyguestelecom.fr/diagnostic/`

### Category

breakage

### Description

The page does not load properly with the default filter lists. The following rule seems to fix the issue, but may not be desirable:
```
! 2023-05-02 https://www.bouyguestelecom.fr
!@@||www.stats.bouyguestelecom.fr/js/rainbow/tc_BouyguesTelecomAnalytics.js$script,domain=www.bouyguestelecom.fr
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 111327
 cosmetic: 49236
 scriptlet: 17598
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  FRA-0: 28283-31, 4h.24m
  easylist: 66410-309, 4h.24m
  easyprivacy: 32242-336, 4h.24m
  plowe-0: 3746-957, 6d.22h.58m
  ublock-abuse: 70-1, 6d.22h.58m
  ublock-badware: 6981-141, 4h.24m
  ublock-filters: 33439-163, 4h.24m
  ublock-privacy: 322-3, 6d.22h.58m
  ublock-quick-fixes: 222-23, 4h.24m
  ublock-unbreak: 2006-41, 4h.24m
  urlhaus-1: 6656-1, 4h.24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 633 ms (selfie)
 maxAssetCacheWait: 305 ms
popupPanel: 
 blocked: 5
 network: 
  bouyguestelecom.fr: 1
  abtasty.com: 1
  facil-iti.com: 1
  trustcommander.net: 2
```
</details>

**Comment by mapx-** [comment]
@ryanbr
