### ISSUE TITLE
meritonsuites.com.au: breakage

### ISSUE THREAD

**Issue by commscheck** [uBlockOrigin/uAssets#17900]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.meritonsuites.com.au/our-hotels/nsw/northern-sydney/chatswood/`

### Category

breakage

### Description

The "book now" buttons in any "check availability" section on this page do nothing when clicked. The same happens on other pages throughout the site. These buttons all seem to have `onclick="prepareHeroBookingWidget(this);"`.

Other "book now" buttons work correctly, such as the ones underneath the descriptions of the room types. These seem to be plain `<a href="https://...">` links.

When uBO is disabled for this domain, clicking the button opens a URL like the below in a new tab where I can view available rooms (whitespace added for readability):
```
https://be.synxis.com/
?__utma=161437345.548836307.1682994001.1682994001.1682994001.1
&__utmb=161437345.1.10.1682994001
&__utmc=161437345
&__utmk=57072810
&__utmv=-
&__utmx=-
&__utmz=161437345.1682994001.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
&_ga=2.96659231.184921438.1682994001-548836307.1682994001
&adult=1
&arrive=2023-05-02
&chain=12196
&child=0
&currency=AUD
&depart=2023-05-03
&hotel=64707
&level=hotel
&locale=en-US
&rooms=1
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1728" alt="Screenshot 2023-05-02 at 12 28 45 pm" src="https://user-images.githubusercontent.com/1658468/235567109-7ce9d948-bcf5-4e0b-98d3-4cb9bd26b5b4.png">
<img width="1728" alt="Screenshot 2023-05-02 at 12 29 36 pm" src="https://user-images.githubusercontent.com/1658468/235567124-1427d8de-e200-44db-b9a8-5101053b255f.png">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 92768
 cosmetic: 40369
 scriptlet: 17491
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66407-46, 1m
  easyprivacy: 32233-42, 1m
  plowe-0: 3741-934, 2d.14h.33m
  ublock-abuse: 70-0, 2d.14h.36m
  ublock-badware: 6981-124, 1m
  ublock-filters: 33437-78, 1m
  ublock-privacy: 393-73, 2d.14h.35m
  ublock-quick-fixes: 222-23, 1m
  ublock-unbreak: 2006-37, 1m
  urlhaus-1: 6656-1, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 135 ms (selfie)
 maxAssetCacheWait: 43 ms
popupPanel: 
 blocked: 9
 network: 
  browser-intake-datadoghq.com: 2
  googletagmanager.com: 2
  hotjar.com: 1
  maps.googleapis.com: 1
  rudderlabs.com: 1
  tacdn.com: 1
  typekit.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=meritonsuites.com.au
@@||google-analytics.com/analytics.js$script,domain=meritonsuites.com.au
@@||ssl.google-analytics.com/ga.js$script,domain=meritonsuites.com.au
```

@ryanbr
