### ISSUE TITLE
[nsfw] stripchat.com: breakage

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#17917]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

transmission stops every moment but when i deactivate the blocker it works fine without stopping

### URL(s) where the issue occurs.

`https://es.stripchat.com/Riskyproject`

### Screenshot(s)

don't have

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Google Chrome Versión 113.0.5672.64 (Build oficial) (64 bits)

### Settings

No change

### Notes

No change

**Comment by mapx-** [comment]
No issue on my end

**Comment by KiLL4FuNK** [comment]
ok

**Comment by realityzero0** [comment]
stripchat seems to be broken with optimal filtering, if i turn off filters it works

<img width="483" height="355" alt="Image" src="https://github.com/user-attachments/assets/dddda1b2-8149-477d-9047-ff0bfa3140d4" />

**Comment by mapx-** [comment]
- provide specific link
- open uBOL settings, `About` tab, copy and paste here `Troubleshooting information`

**Comment by realityzero0** [comment]
`https://stripchat.com/`

name: uBlock Origin Lite
version: 2026.201.1924
browser: Chrome 144 (win)
filtering:
 default: optimal
permission: all
rulesets:
 +adguard-mobile
 +annoyances-cookies
 +annoyances-notifications
 +annoyances-others
 +annoyances-overlays
 +stevenblack-hosts
 easylist
 easyprivacy
 pgl
 ublock-badware
 ublock-filters
 urlhaus-full
scripting:
 ublock-filters.isolated
 ublock-filters.main
 easyprivacy.isolated
 easyprivacy.main
 ublock-badware.main
 adguard-mobile.isolated
 adguard-mobile.main
 annoyances-cookies.isolated
 annoyances-cookies.main
 annoyances-overlays.isolated
 annoyances-overlays.main
 annoyances-others.isolated
 annoyances-others.main
 annoyances-notifications.isolated
 annoyances-notifications.main
 css-user
 css-specific
 css-procedural

**Comment by mapx-** [comment]
yeah, disable that bad list: `Steven Black’s Unified Hosts (adware + malware)`

containing: 
`||stripchat.com^`

@gorhill 
another issue with Steven Black list, like here: https://github.com/uBlockOrigin/uAssets/issues/31670#issuecomment-3818080232

**Comment by stephenhawk8054** [comment]
Yeah, I think this list is more suitable for DNS than etensions.
