### ISSUE TITLE
ya.ru: nuisance

### ISSUE THREAD

**Issue by Stomenick** [uBlockOrigin/uAssets#17918]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ya.ru/`

### Category

nuisance

### Description

Constantly pops up a message from above "Let Yandex be the main search"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Снимок экрана 2023-05-04 010059](https://user-images.githubusercontent.com/132503948/236034743-e3988caa-210c-4b97-afd2-d7acd3ffd0fc.jpg)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 110384
 cosmetic: 61255
 scriptlet: 18787
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 7-0, never
  RUS-0: 39702-11, 1d.9h.53m
  easylist: 66148-66, 3d.9h.22m
  easyprivacy: 32222-151, 1d.7h.52m
  plowe-0: 3741-939, 3d.10h.43m
  ublock-abuse: 70-1, 4d.4h.4m
  ublock-badware: 6957-122, 4d.13h.11m
  ublock-filters: 33439-108, 8h.56m
  ublock-privacy: 323-3, 4d.4h.3m
  ublock-quick-fixes: 222-23, 6h.54m
  ublock-unbreak: 2006-35, 4d.13h.9m
  urlhaus-1: 7217-1, 6h.55m
filterset (user): [array of 7 redacted]
trustedset: 
 removed: 
  chrome-extension-scheme
  chrome-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 contextMenuEnabled: false
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 209 ms (selfie)
 maxAssetCacheWait: 124 ms
popupPanel: 
 blocked: 3
 network: 
  yandex.ru: 3
 cosmetic: 
  ##.link-bro
  ##.ad-card
```
</details>
![Снимок экрана 2023-05-04 010059](https://user-images.githubusercontent.com/132503948/236035200-0a00cdbc-e5d5-4e6a-8094-20519812d6d2.jpg)

**Comment by dimisa-RUAdList** [comment]
In Runet, such announcements are blocked by the [BitBlock filter](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).
