### ISSUE TITLE
jockantv.com: nuisance

### ISSUE THREAD

**Issue by DominikNovosel** [uBlockOrigin/uAssets#17915]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://jockantv.com/sinkronizirani-crtici/bansen-je-zvijer-bunsen-is-a-beast-2017-hr.html`

### Category

nuisance

### Description

Player window and upper right corner have popups (uBO successfully removes content from outside sources).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Firefox Mobile: 112
filterset (summary): 
 network: 94639
 cosmetic: 32019
 scriptlet: 20703
 html: 1117
listset (total-discarded, last-updated): 
 added: 
  ublock-annoyances: 5001-9, 4d.23h.17m
 default: 
  user-filters: 0-0, never
  ublock-filters: 34714-307, 4d.5h.7m
  ublock-badware: 6955-0, 4d.5h.5m
  ublock-privacy: 371-1, 12d.23h.56m
  ublock-abuse: 70-0, 3h.2m
  ublock-unbreak: 2022-4, 1d.5h.38m
  ublock-quick-fixes: 215-0, 3h.1m
  adguard-mobile: 8711-138, 2d.20h.12m
  easylist: 66410-17451, 1d.9h.37m
  easyprivacy: 32242-618, 1d.9h.39m
  urlhaus-1: 6708-1, 18h.23m
  plowe-0: 3746-3, 9d.4h.55m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2060 ms (selfie)
 maxAssetCacheWait: 199 ms
popupPanel: 
 blocked: 22
 network: 
  adskeeper.com: 5
  cpmstar.com: 2
  feistyhelicopter.com: 2
  histats.com: 1
  mordoops.com: 2
  paypalobjects.com: 2
  sharethis.com: 2
  veecheew.xyz: 4
  waufooke.com: 2
 cosmetic: 
  ##div[id*=\"ScriptRoot\"]
  ##div[id*=\"ScriptRoot\"]
```
</details>

**Comment by ghajini** [comment]
iam getting again 
https://user-images.githubusercontent.com/20338483/236010240-aee4cb08-e6c4-46ba-b007-694a95ce89a2.png

chrome ok

**Comment by DominikNovosel** [comment]
> iam getting again 

To be fair, I only reported that this site has overlays (which are now removed successfully), I wasn't sure whether I'm supposed to report pop-up tabs separately.

**Comment by mapx-** [comment]
oes this work in FF ?

`jockantv.com##+js(aopr, open)`

**Comment by DominikNovosel** [comment]
Yes, it seems to have worked for me. I've never added custom filters before and figured it out on the fly, hopefully I did it correctly.

**Comment by ghajini** [comment]
what was the issue ?

**Comment by mapx-** [comment]
the one reported by ghajini above
