### ISSUE TITLE
outlook.live.com: ads

### ISSUE THREAD

**Issue by user460** [uBlockOrigin/uAssets#17929]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

"Upgrade your account" Outlook's ad is back.

### URL(s) where the issue occurs.

`https://outlook.live.com/mail/`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/127345415/236184019-95950850-15ab-4665-8868-98d248dee6bf.png)

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 112
filterset (summary): 
  network: 159606
  cosmetic: 143743
  scriptlet: 34748
  html: 950
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 43547-17429, now
    https://get.letsblock.it/list/4a8d39d8-1edd-470e-a3f7-946a174faeb9.txt: 1302-0, now
    https://raw.githubusercontent.com/robonxt/CleanYourTwitter/master/CleanYourTwitter%20(EXTRAS).txt: 5-0, now
    https://raw.githubusercontent.com/robonxt/CleanYourTwitter/master/CleanYourTwitter.txt: 17-0, now
    adguard-generic: 70576-6389, now
    adguard-annoyance: 67877-764, now
    FRA-0: 28354-408, now
  default: 
    user-filters: 35-0, never
    ublock-filters: 34221-221, now
    ublock-badware: 7102-1, now
    ublock-privacy: 444-0, now
    ublock-abuse: 70-70, now
    ublock-unbreak: 2015-4, now
    ublock-quick-fixes: 220-0, now
    easylist: 66706-541, now
    easyprivacy: 32236-892, now
    urlhaus-1: 7683-2, now
    plowe-0: 3742-2, now
filterset (user): [array of 35 redacted]
trustedset: 
  added: [array of 42 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 312 ms (selfie)
  maxAssetCacheWait: 385 ms
```
</details>

**Comment by Procyon-b** [comment]
This filter seems to work:
```
outlook.live.com##[role="listbox"] .Ogt7j
```

**Comment by gelliss** [comment]
> This filter seems to work:
> 
> ```
> outlook.live.com##[role="listbox"] .Ogt7j
> ```

Worked great here.   Thanks much.

**Comment by stephenhawk8054** [comment]
Other feedbacks:

```
https://www.reddit.com/r/uBlockOrigin/comments/137y4sp/outlook_email_ad/jiwcbzd/?context
```

**Comment by krystian3w** [comment]
#17566

**Comment by krystian3w** [comment]
Tries to cover ads without randomized classes:

> ```adb
> ! mobile but rows are hardcoded by style attr in absolute positioning:
> outlook.live.com###app [role="main"] div[role="group"]:has([role="link"])
> outlook.live.com###app [role="main"] article:has([role="link"])
> outlook.live.com###app [role="main"] [style*="relative"] [style*="absolute"] + div[style*="absolute"]:style(position: static !important;)
> ! so needed is redesign mobile layout to static.
> ```

**Comment by stephenhawk8054** [comment]
Given the feedbacks, I think it's safe to add the filter.

**Comment by peace2000** [comment]
Works fine now with the new filter. @stephenhawk8054, I think this can be closed now.

**Comment by krystian3w** [comment]
Filter down:

![obraz](https://user-images.githubusercontent.com/35370833/236637014-71f0eb61-3f14-4f35-9911-e4f5b99dff1b.png)

**Comment by Procyon-b** [comment]
@krystian3w I had a user this afternoon that complained on reddit. It's a different layout triggered by the setting in "General / Advertising preferences" at the bottom when you select "Banner ads" in "Choose your Outlook layout".

I think that we can simplify the filter and use
```
outlook.live.com##.Ogt7j
```
The `[role]` part was only a safeguard in case there was the possibility of another usage. Which I couldn't find in my tests (with 2 accounts).

**Comment by peace2000** [comment]
Works on my end still but let's wait a while. Maybe they are rolling changes currently.

**Comment by gorhill** [comment]
This is self-promotion, we don't block these.

**Comment by gorhill** [comment]
> Duplicate of https://github.com/uBlockOrigin/uAssets/discussions/17566

**Comment by Procyon-b** [comment]
@gorhill This is more an ad placeholder filled with a default MSO ad when ublock has correctly blocked their ad network.

with a real ad in @krystian3w layout:
![olc-ad2](https://user-images.githubusercontent.com/40043075/236688589-f3e81fcd-d128-42dc-b5e0-c8debdf13564.png)

and here in the default layout as a fake message:
![olc-ad3](https://user-images.githubusercontent.com/40043075/236688593-7c01ab35-ecb9-424f-9494-41ca30c615da.png)

**Comment by gorhill** [comment]
> This is more an ad placeholder filled with a default MSO

Ok. Still a duplicate of #17566, where @mapx- said:

>  I'll convert the issue to a discussion where the .. discussion & filter ideas can continue.

Best to keep the discussion ongoing at that other issue.
