### ISSUE TITLE
[nsfw] sexvideos.host: popups

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#17922]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sexvideos.host/en/x-videos/desi-cute-girl-showing-her-boobs.html`

### Category

popups

### Description

Click the play button and video will open in a new tab. Tab redirects to a new site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://user-images.githubusercontent.com/111344219/236115962-8a5bc819-2435-43d1-9c06-fa9157022f5b.gif)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 108857
 cosmetic: 129390
 scriptlet: 24077
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  plowe-0: null
  urlhaus-1: null
 added: 
  https://easylist-downloads.adblockplus.org/bitblock.txt: 27730-18, now
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1602-25, now
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 1055-0, now
  fanboy-cookiemonster: 46946-408, now
  ublock-annoyances: 4970-55, now
 default: 
  user-filters: 1-0, never
  RUS-0: 39712-143, now
  easylist: 66599-82, now
  easyprivacy: 32235-456, now
  ublock-abuse: 70-1, now
  ublock-badware: 7094-124, now
  ublock-filters: 33352-130, now
  ublock-privacy: 394-75, now
  ublock-quick-fixes: 229-23, now
  ublock-unbreak: 2005-39, now
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
modifiedHiddenSettings: 
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats: 
 allReadyAfter: 513 ms (selfie)
 maxAssetCacheWait: 321 ms
popupPanel: 
 blocked: 3
 network: 
  frap.site: 3
```
</details>

**Comment by stephenhawk8054** [comment]
I can't see the red play button. On my side I only see the text `Click to open video in new window. This page will redirect to another free porn site.`

**Comment by dportvine** [comment]
These rules work for me. The problem is solved.
