### ISSUE TITLE
linkz.fun: ads

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#17924]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkz.fun/JwOWa`

### Category

ads

### Description

I'm assuming #17361 is for shortener-related detection only, hence this issue (if correct, changing the dicussion's title to `Detection by various shortener` might not be a bad idea for clarity).

The site shows 3 ad banners, all loaded from `fullmatchzone.com`.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.47.3b3
Firefox: 112
filterset (summary): 
  network: 94103
  cosmetic: 40385
  scriptlet: 17486
  html: 950
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 34236-41, now
    ublock-badware: 7098-0, now
    ublock-privacy: 444-0, now
    ublock-abuse: 70-70, now
    ublock-unbreak: 2018-0, now
    ublock-quick-fixes: 222-24, now
    easylist: 66696-222, now
    easyprivacy: 32235-68, now
    urlhaus-1: 7683-2, now
    plowe-0: 3742-939, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 208 ms (selfie)
  maxAssetCacheWait: 300 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    googletagmanager.com: 2
```
</details>

**Comment by ghajini** [comment]
report such issues to easylist repository 
`https://github.com/easylist/easylist/issues`
