### ISSUE TITLE
parentcircle.com: ad placeholder

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#17939]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On the site, there is an ad placeholder which seems like it can only be truly removed when editing the CSS elements itself. I'm not sure if this is a problem that can be fixed with EasyList, so I'm reporting here. I used these filters, and they would great:
`parentcircle.com##.ads_top_card`
`parentcircle.com##.top_ads_add header:style(top: unset !important;)`
`parentcircle.com##.top_ads_add .hpc_empty_card:style(height: 69px !important;)`

### URL(s) where the issue occurs.

`https://www.parentcircle.com/`

### Screenshot(s)

![Screenshot from 2023-05-04 16-32-19](https://user-images.githubusercontent.com/89158249/236323033-e01097c0-e03c-4ff7-99de-5f2001362f2e.png)

### uBO version

uBlock Origin v1.49.3b4

### Browser name and version

Firefox 112.0.2

### Settings

- Using custom filter lists, having "I am an advanced user" checked (Problem was also tested with default settings)

**Comment by peace2000** [comment]
@Sonic5435325 Thanks for good suggestion, though I'm a little worried how well a fixed css value would behave on different sized screens and resolutions. E.g. on my monitor 66px seems to be the best value. Though on smaller screen, a slight gap appears also between `.hpc_empty_card` and `.hpc_ypc_card`.

Can you test these filters?

```
parentcircle.com##body:remove-class(top_ads_add)
parentcircle.com##+js(aeld, scroll, function(e))
```

**Comment by stephenhawk8054** [comment]
@peace2000 Those work for me

**Comment by Sonic5435325** [comment]
@peace2000 Those work well! Thank you for suggesting better filters.

**Comment by peace2000** [comment]
Great! Those filters are now added to the list: https://github.com/uBlockOrigin/uAssets/commit/e5a8fbd8232f3d64901171b52801061aebab6349
