### ISSUE TITLE
slate.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1793]
URL(s) where the issue occurs

`http://www.slate.com/articles/life/dear_prudence/2017/12/dating_a_high_school_senior_in_this_week_s_dear_prudie_extra.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.15.18

Settings

Default

**Comment by mapx-** [comment]
I cannot reproduce your issue.

@KiLL4FuNK  you should update your browser (last stable version: 65)

**Comment by KiLL4FuNK** [comment]
I use the latest version of the browser I forgot to update the data

![](https://pbs.twimg.com/media/DZE-9Z6VQAET3R3.jpg)

**Comment by KiLL4FuNK** [comment]
it's not an Anti-Adblock it's just a message that can be closed
