### ISSUE TITLE
codedosa.com: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#17934]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

contextmenu, mouse selection

### URL(s) where the issue occurs.

`https://codedosa.com/13317`

### uBO version

1.49.2

### Browser name and version

Mullvad Browser 12.0.4 (64-bit)

### Settings

- enabled `uBlock filters – Annoyances`

**Comment by Procyon-b** [comment]
Try these filters:
```
codedosa.com##+js(aopw, document.oncontextmenu)
codedosa.com##+js(aopw, document.ondragstart)
codedosa.com##.unselectable:style(user-select: unset !important; cursor: default;)
codedosa.com##html:style(-webkit-touch-callout: unset !important; user-select: unset !important;)
codedosa.com##+js(set, disable_copy, noopFunc)
codedosa.com##+js(set, disable_copy_ie, noopFunc)
```
