### ISSUE TITLE
wooseotools.com: detection

### ISSUE THREAD

**Issue by danielrzad** [uBlockOrigin/uAssets#17938]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wooseotools.com/`

### Category

detection

### Description

Site detects that uBlock is turned on and displays a popup which ask to turn off the adblocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![print_screen 2023-05-04 220849](https://user-images.githubusercontent.com/45539133/236318016-2661ca8b-0e2d-488e-ac01-d42bcf2d55d2.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95746
 cosmetic: 47898
 scriptlet: 17709
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  POL-0: 7936-8, 1m
  POL-2: 1275-13, 1m
  easylist: 66776-73, 1m
  easyprivacy: 32237-43, 1m
  plowe-0: 3743-944, now
  ublock-abuse: 70-0, now
  ublock-badware: 7111-125, now
  ublock-filters: 33366-120, now
  ublock-privacy: 394-74, now
  ublock-quick-fixes: 228-23, now
  ublock-unbreak: 2007-37, now
  urlhaus-1: 7828-2, now
filterset (user): [empty]
trustedset: 
 added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 512 ms (selfie)
 maxAssetCacheWait: 104 ms
popupPanel: 
 blocked: 4
 network: 
  criteo.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
 cosmetic: 
  ##[id^=\"aswift_\"]
  ##ins.adsbygoogle
```
</details>

**Comment by Procyon-b** [comment]
Can you give the url that led you to this site?

**Comment by danielrzad** [comment]
https://mirrorace.org/m/3b9Nz?__cf_chl_rt_tk=bMUqukDCivmwK4LTggoy.FYHG.ySpt1_njxotVaCLyE-1683232634-0-gaNycGzNC5A

Any of download links on that site.

**Comment by Procyon-b** [comment]
@okiehsch this syntax works to:
```
||criteo.net^$xhr,redirect-rule=noop.txt,domain=wooseotools.com
```

**Comment by okiehsch** [comment]
With Firefox too?

Anyway, I can't commit right now.
I will take another look tomorrow.

**Comment by Procyon-b** [comment]
I've tested only on chrome.
Anyway for this type of page it's not important.  :)
