### ISSUE TITLE
jonesbarbershop.ca: breakage

### ISSUE THREAD

**Issue by BP211** [uBlockOrigin/uAssets#17937]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://jonesbarbershop.ca/contact`

### Category

breakage

### Description

Cannot even access the login page (Squarespace based)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 112
filterset (summary): 
 network: 95399
 cosmetic: 30602
 scriptlet: 17565
 html: 950
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34564-336, 2d.22h.55m
  ublock-badware: 6979-0, 2d.22h.54m
  ublock-privacy: 443-1, 4d.6h
  ublock-abuse: 70-70, 4d.5h.59m
  ublock-unbreak: 2021-3, 2d.22h.53m
  ublock-quick-fixes: 222-0, 1h.54m
  adguard-mobile: 8711-120, 2d.22h.56m
  easylist: 66603-17452, 2d.2h.32m
  easyprivacy: 32236-618, 1h.55m
  urlhaus-1: 7683-1, 16h.11m
  plowe-0: 3742-3, 2d.16h.6m
filterset (user): [empty]
modifiedUserSettings: 
 webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3126 ms (selfie)
 maxAssetCacheWait: 2445 ms
popupPanel: 
 blocked: 16
 network: 
  jonesbarbershop.ca: 1
  cloudflareinsights.com: 6
  datadoghq-browser-agent.com: 1
  facebook.net: 2
  googletagmanager.com: 1
  squarespace.com: 2
  squareup.com: 2
  typekit.net: 1
```
</details>

**Comment by gorhill** [comment]
When I click _Sign in_, I am presented with a form to enter a phone number. At which point does it fail on your side?

**Comment by peace2000** [comment]
I can get to the login page as well. Please try to update your filterlists and see if the issue still persists.

**Comment by BP211** [comment]
It now seems to be working.  With the original issue, it made it as far as getting the confirmation code request sent off, but failed when entering the code. Now it seems to be working, so I will thank you for your time and close the issue.
