### ISSUE TITLE
kissanime.com.ru: breakage

### ISSUE THREAD

**Issue by trashlxrd** [uBlockOrigin/uAssets#17948]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kissanime.com.ru/Anime/chainsaw-man.68802/Episode-001?id=180296`

### Category

breakage

### Description

Use of uBO on kissanime blocks access to the 2 of the 4 file servers i've come across so far.

Using the NS Server will cause it to load for a while before giving a network error, the O Server doesn't work regardless of uBO, the H Server will get stuck in an infinite loading loop, and while the MP Server does function only a few titles are actually hosted on the MP Server which leaves a majority of the content inaccessible with uBO enabled.

I've tested attempting to use all three servers with uBO disabled and of the three the only one that remained broken was the O Server.

I'd also like to note that up until a few days ago the H Server worked perfectly fine with uBO enabled but suddenly stopped and has not worked since.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 111
filterset (summary): 
 network: 94351
 cosmetic: 40406
 scriptlet: 17488
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66774-46, now
  easyprivacy: 32241-43, now
  plowe-0: 3743-936, now
  ublock-abuse: 70-0, now
  ublock-badware: 7129-128, now
  ublock-filters: 33342-78, now
  ublock-privacy: 394-74, now
  ublock-quick-fixes: 234-23, now
  ublock-unbreak: 2008-36, now
  urlhaus-1: 7828-2, now
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2542 ms (selfie)
 maxAssetCacheWait: 494 ms
popupPanel: 
 blocked: 15
 network: 
  kissanime.com.ru: 7
  bebi.com: 1
  disqus.com: 3
  doubleclick.net: 1
  facebook.com: 1
  googletagmanager.com: 1
  rezync.com: 1
 cosmetic: 
  ###upgrade_pop
```
</details>

**Comment by okiehsch** [comment]
In regards to "H-Server", does adding
````
player-cdn.com##+js(aost, String.prototype.charAt, $0)
player-cdn.com#@#+js(set, detectAdBlockAll, noopFunc)
player-cdn.com#@##playback-fake
````
to your filters work for you?

**Comment by stephenhawk8054** [comment]
I found a link that has NS server, however, it doesn't work even when disabling uBO: `https://kissanime.com.ru/Anime/chainsaw-man.68802/Episode-001?id=180296`

**Comment by okiehsch** [comment]
Thx,  it's the same for me.
