### ISSUE TITLE
washingtonpost.com: breakage

### ISSUE THREAD

**Issue by arthurh3535** [uBlockOrigin/uAssets#17942]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.washingtonpost.com/politics/2023/04/21/texas-bill-ten-commandments-public-schools-religion/?utm_campaign=wp_the_5_minute_fix&utm_medium=email&utm_source=newsletter&wpisrc=nl_fix&carta-url=https%3A%2F%2Fs2.washingtonpost.com%2Fcar-ln-tr%2F39c9de6%2F64542e1ba61bab12f751ec67%2F5a0b002cade4e230f7f37b7d%2F24%2F51%2F64542e1ba61bab12f751ec67`

### Category

breakage

### Description

Unable to click on any link in page and unable to scroll down.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 98443
 cosmetic: 99723
 scriptlet: 20197
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67786-92, 2d.23h.37m
 default: 
  user-filters: 0-0, never
  easylist: 66392-101, 2d.23h.38m
  easyprivacy: 32233-126, 2d.23h.38m
  plowe-0: 3742-936, 2d.23h.38m
  ublock-abuse: 70-0, 2d.23h.38m
  ublock-badware: 6981-124, 2d.23h.38m
  ublock-filters: 33438-449, 2d.23h.38m
  ublock-privacy: 393-73, 2d.23h.38m
  ublock-quick-fixes: 229-23, 11h.22m
  ublock-unbreak: 2006-39, 2d.23h.38m
  urlhaus-1: 7217-1, 23h.24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 463 ms (selfie)
 maxAssetCacheWait: 233 ms
popupPanel: 
 blocked: 19
 network: 
  3gl.net: 1
  amazon-adsystem.com: 1
  criteo.net: 1
  doubleclick.net: 1
  google.com: 4
  googleoptimize.com: 1
  googletagmanager.com: 1
  nile.works: 1
  permutive.app: 1
  sentry-cdn.com: 1
  unpkg.com: 1
  webcontentassessor.com: 1
  zeustechnology.com: 4
 cosmetic: 
  ##div[data-qa=\"newsletter\"]
  ##.grid-body > .hide-for-print:has(> div[data-qa=\"newsletter\"])
  ##.paywall-overlay
  ##div[data-qa=\"subscribe-promo\"]
  ##[data-qa=\"right-rail-ad\"]
  ##[data-testid=\"placeholder-box\"]
  ##.outbrain-wrapper
  ##[data-ad-module]:not([style$=\"left: -10000px !important; top: -1000px !important;\"]):not(div.adsbygoogle)
  #@#[data-ad-module]
```
</details>

**Comment by gothic-bum** [comment]
>  * [x] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)  
  
The configuration information that you provided shows that many of your filter lists are over 2 days old.  
  
Test again after you force update all filter lists:  
Click the [*"Purge all caches"*](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button and then click the [*"Update now"*](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button).

----  
  
>  * [x] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.

The configuration information that you provided shows that you enabled the "AdGuard Annoyances" filter list.  
  
Disable this list and test again using only the default uBO filter lists.

**Comment by gorhill** [comment]
I get a case where AdGuard Annoyances is hiding a paywall (`##.paywall-overlay`), which prevent scrolling.

See if you get the same issue without AdGuard Annoyances. If so, this needs to be fixed by maintainers of AdGuard Annoyances.

**Comment by stephenhawk8054** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
> Unable to click on any link in page

Still not reproduced
