### ISSUE TITLE
search.brave.com: ads

### ISSUE THREAD

**Issue by craciu25yt** [uBlockOrigin/uAssets#17949]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://search.brave.com/search?spellcheck=0&q=js+change+element+colors`

### Category

ads

### Description

it shows the premium subscription ad to remove ads.
Fix:
```adb
! 2023-05-05 https://search.brave.com
search.brave.com###premium-promo-wrapper
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/48807342/236467386-4b367701-1f9a-42db-a336-2a676e6b3655.png)

</details>

### Configuration

<details>
<summary>Settings</summary>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 224737
 cosmetic: 228815
 scriptlet: 39519
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67838-92, 2d.2h.43m
  adguard-generic: 70506-512, 2d.2h.41m
  adguard-mobile: 8713-46, 2d.2h.46m
  adguard-social: 20396-860, 2d.2h.42m
  adguard-spyware-url: 1004-3, 2d.2h.44m
  block-lan: 47-0, 5d.23h.2m
  curben-phishing: 86729-2, 28m
  curben-pup: 190-0, 29m
  dpollock-0: 11357-82, 1d.3h.46m
  fanboy-annoyance: 90375-21141, 7d.3h.9m
  fanboy-cookiemonster: 61256-61256, 7d.3h.8m
  fanboy-social: 17210-17186, 2d.2h.45m
  fanboy-thirdparty_social: 68-18, 7d.3h.10m
  ublock-annoyances: 4971-259, 6d.4h.4m
 default: 
  user-filters: 2-0, never
  easylist: 66561-1175, 2d.2h.40m
  easyprivacy: 32233-338, 2d.2h.39m
  plowe-0: 3746-1383, 8d.5h.29m
  spa-0: 3624-37, 30m
  spa-1: 5195-214, 2d.2h.47m
  ublock-abuse: 70-0, 8d.5h.28m
  ublock-badware: 7094-375, 1d.3h.45m
  ublock-filters: 33357-4129, 1d.3h.45m
  ublock-privacy: 323-7, 8d.5h.27m
  ublock-quick-fixes: 228-26, 6h.11m
  ublock-unbreak: 2007-97, 1d.3h.45m
  urlhaus-1: 7542-5, 27m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 973 ms (selfie)
 maxAssetCacheWait: 714 ms
popupPanel: 
 blocked: 5
 network: 
  brave.com: 5
 cosmetic: 
  ##div[data-advertiser-id]
  ##[data-type=\"ad\"]
  ###usage-metrics
```
</details>

**Comment by krystian3w** [comment]
Compatible with EasyList, and what was done on sending report, so that broke harmony in sections under "Fix:" (...?).

**Comment by peace2000** [comment]
Hi, as this is fixable by Easylist, please file your report here: https://github.com/easylist/easylist/issues/

(Just copy your message there).

**Comment by iam-py-test** [comment]
> it shows the premium subscription ad to remove ads.

Isn't that self-promo, which is out of scope of EasyList and uAssets? Or am I an idiot and misread this?

**Comment by krystian3w** [comment]
Can be addresed in EasyList Annoyances or legacy "Fanboy Annoyances".

For the time being, I do not track whether gorhill has activated the merging of the cookie list and social media in its mirror.

---

Theoretically, it minimally resembles a widget on Reddit, which is only suitable for addressing as an annoyance (aside from the fact that an interface based on something similar to react has no readable class/id).

**Comment by peace2000** [comment]
> > it shows the premium subscription ad to remove ads.
> 
> Isn't that self-promo, which is out of scope of EasyList and uAssets? Or am I an idiot and misread this?

Outlook "ads" or "self-promo" is also handled in uAssets. Personally I think that if self-promo is annoying, it should be handled.

**Comment by krystian3w** [comment]
So made PR.

**Comment by luftra** [comment]
Brave Sponsored Ads aren't getting blocked, even with EasyList Annoyances.

![Screenshot 2024-12-21 205328](https://github.com/user-attachments/assets/7f2d41e5-c0b7-4113-8429-800205ba787e)

**Comment by luftra** [comment]
Any ETA, if I may ask?

**Comment by stephenhawk8054** [comment]
Which browser are you using?

**Comment by ryanbr** [comment]
I can't repo, but if you want to block Brave search ads with Brave shields, use Aggresive mode in shields on search.brave.com

**Comment by luftra** [comment]
> I can't repo, but if you want to block Brave search ads with Brave shields, use Aggresive mode in shields on search.brave.com

Thanks

**Comment by DimitrisKalaboukas** [comment]
@ryanbr What about blocking AI summaries on Brave Search results by EasyList Annoyances – AI widgets (see https://github.com/easylist/easylist/issues/24190)?
