### ISSUE TITLE
kaas.am: ads

### ISSUE THREAD

**Issue by Netanel-Asraf** [uBlockOrigin/uAssets#17943]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kaas.am/`

### Category

ads

### Description

Has a lot of ads... 
[](url)
<img width="1270" alt="Screenshot 2023-05-05 043706" src="https://user-images.githubusercontent.com/98565146/236361840-95dd584e-ca2e-487d-98b9-a22943cbe728.png">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 94047
 cosmetic: 40227
 scriptlet: 17490
 html: 949
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34414-41, 4d.2h.6m
  ublock-badware: 7014-1, 4d.2h.6m
  ublock-privacy: 370-0, 12d.13h.22m
  ublock-abuse: 70-0, 12d.13h.21m
  ublock-unbreak: 2009-2, 4d.2h.6m
  ublock-quick-fixes: 215-20, 1m
  easylist: 66260-607, 4d.2h.6m
  easyprivacy: 32231-609, 1m
  urlhaus-1: 7828-1, 1m
  plowe-0: 3746-2, 8d.6h.52m
filterset (user): [empty]
trustedset: 
 removed: 
  about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 329 ms (selfie)
 maxAssetCacheWait: 129 ms
popupPanel: 
 blocked: 2
 network: 
  googletagmanager.com: 1
  notorietynoblemanproposition.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Please follow what you ticked truthfully

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
