### ISSUE TITLE
adweek.com: ad placeholders

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#17955]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Same as #17940
`adweek.com##.widget-adweek-sticky-next:has(.htl-ad-wrapper)`
`adweek.com##.widget-adweek-sticky-next:style(height: 400px !important;)`

### URL(s) where the issue occurs.

https://www.adweek.com/brand-marketing/petsmart-charities-dana-carvey-king-charles-pet-adoptions/

### Screenshot(s)

![Screenshot from 2023-05-05 20-11-49](https://user-images.githubusercontent.com/89158249/236587653-2278ded1-67c3-479f-904f-0f11561c7d98.png)

### uBO version

v1.49.3b4

### Browser name and version

Firefox 112.0.2

### Settings

- Using custom filters, having "I am an advanced user" checked

**Comment by stephenhawk8054** [comment]
For the 2nd filter, it's more like their design choice I guess (scrolling and section appearing)? So I think better not to craft more filters involving style
