### ISSUE TITLE
coincodex.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1795]
`https://coincodex.com/`

ad in down bar

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.47
 Chr 65.0.3325.181
</details>

**Comment by mapx-** [comment]
add as custom filters
```
||apps7.space/bnr/
coincodex.com##.hidden-xs.hidden-sm.a-top
```

**Comment by SMed79** [comment]
@ryanbr https://forums.lanik.us/viewtopic.php?f=62&t=40036
