### ISSUE TITLE
lovetoknow.com

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#17957]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Small ad placeholder at the top of the page

### URL(s) where the issue occurs.

https://www.lovetoknow.com/

### Screenshot(s)

![Screenshot from 2023-05-05 20-44-34](https://user-images.githubusercontent.com/89158249/236589172-82fa1c37-c911-4503-8718-1d994bfcd66c.png)

### uBO version

v1.49.3b4

### Browser name and version

Firefox 112.0.2

### Settings

- Custom filters, checked "I am an advanced user"

**Comment by Sonic5435325** [comment]
@stephenhawk8054 The placeholder still shows on PC after force updating

**Comment by stephenhawk8054** [comment]
I can't see the placeholder after updating: https://user-images.githubusercontent.com/66517106/236590022-e63b8c11-13c3-47c5-855f-1775f4a8a241.png

Maybe you forced update too early? Can you test manually?

```adb
!#if !env_mobile
lovetoknow.com##.below-ad-wrapper:style(margin-top: 51px !important;)
!#endif
lovetoknow.com##.ad
```

**Comment by Sonic5435325** [comment]
Nvm, now it seems to work. Thanks as always!
