### ISSUE TITLE
mp4upload.com: breakage

### ISSUE THREAD

**Issue by Jasj420** [uBlockOrigin/uAssets#17954]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mp4upload.com/`

### Category

breakage

### Description

The entire page is white, disabling cosmetic filtering fixes this but still doesn't allow you to download from the site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 206494
 cosmetic: 141884
 scriptlet: 37302
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://gitlab.com/Sorrow-San/9anime-adblock-filters/raw/master/9Anime%20filter%20list: 148-3, 45m
  adguard-annoyance: 67913-92, 55m
  adguard-generic: 70552-519, 55m
  adguard-mobile: 8728-47, 55m
  adguard-spyware-url: 1010-3, 55m
  block-lan: 47-0, 55m
  curben-phishing: 86729-2, 55m
  curben-pup: 190-0, 55m
  ublock-annoyances: 4975-210, 55m
 default: 
  user-filters: 43-25, never
  easylist: 66912-973, 5m
  easyprivacy: 32241-248, 55m
  plowe-0: 3743-1034, 55m
  ublock-abuse: 70-0, 55m
  ublock-badware: 7129-378, 55m
  ublock-filters: 33231-4105, 55m
  ublock-privacy: 394-76, 55m
  ublock-quick-fixes: 229-22, 55m
  ublock-unbreak: 2008-93, 55m
  urlhaus-1: 7542-5, 55m
filterset (user): [array of 41 redacted]
trustedset: 
 added: [array of 8 redacted]
 removed: 
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 17111 ms (selfie)
 maxAssetCacheWait: 1975 ms
popupPanel: 
 blocked: 15
 no-cosmetic-filtering: true
 network: 
  cloudflare.com: 3
  cloudflareinsights.com: 2
  d18kg2zy9x3t96.cloudfront.net: 4
  exdynsrv.com: 2
  s3.us-east-1.amazonaws.com: 2
  thongsalhagi.com: 1
  upsweephalms.com: 1
 cosmetic: 
  ###overlay,div.container
  ##.adsbyexoclick
  ##.adsbyexoclick
  ##.vjs-logo
  ###overlay,div.container
  ###overlay
```
</details>

**Comment by iam-py-test** [comment]
Have you tried testing with your custom filters disabled? _9Anime Filter-list: No Banner Ads_ looks like it has rules for that website?

**Comment by iam-py-test** [comment]
Ok, that doesn't seem to be the problem, sorry for being rude.

**Comment by krystian3w** [comment]
Also you broke trusted list:

> ```yml
> trustedset: 
>  added: [array of 8 redacted]
>  removed: 
>   about-scheme
>   chrome-extension-scheme
>   chrome-scheme
>   edge-scheme
>   moz-extension-scheme
>   opera-scheme
>   vivaldi-scheme
>   wyciwyg-scheme
> ```
