### ISSUE TITLE
megantorrents.com.br: ad placeholder

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#17952]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ad is blocked but the ad space isnt removed.

### URL(s) where the issue occurs.

`https://www.megantorrents.com.br/animacao-torrent/page/2/index.html`

### uBO version

1.49

### Browser name and version

Waterfox

### Settings

Added fanboy's annoyances list.

**Comment by okiehsch** [comment]
`megantorrents.com.br##.afc_popup`

@Yuki2718 for `AdGuard Spanish/Portuguese`.

**Comment by Yuki2718** [comment]
@Alex-302 No traffic data, up to you.

**Comment by Felipefpl** [comment]
Thanks for the fix.

**Comment by Alex-302** [comment]
@Yuki2718 Just new site

<details>
<summary>Details</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/8361299/a01a1dc0-2a4f-46f4-87ac-5753e5d0ccfe)


</details>

**Comment by Yuki2718** [comment]
So should fix or not?
