### ISSUE TITLE
now.gg: detection

### ISSUE THREAD

**Issue by MyFavGameIsRoblox** [uBlockOrigin/uAssets#17953]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://now.gg/play/roblox-corporation/5349/roblox`

### Category

detection

### Description

i was trying to play now.gg it kept saying it was my internet but when i deleted ublock orgin to see if it will work it worked so i dowloaded ublock origin again and im gonna be testing if i can play each day.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/132698743/236526478-72b4c282-b813-4b4d-a3cc-1d85acfe9907.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 94059
 cosmetic: 40401
 scriptlet: 17492
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66774-46, 1m
  easyprivacy: 32236-43, 1m
  plowe-0: 3743-936, now
  ublock-abuse: 70-0, now
  ublock-badware: 7129-128, now
  ublock-filters: 33340-78, now
  ublock-privacy: 394-74, now
  ublock-quick-fixes: 234-23, now
  ublock-unbreak: 2008-36, now
  urlhaus-1: 7542-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4838 ms
 maxAssetCacheWait: 104 ms
popupPanel: 
 blocked: 15
 network: 
  now.gg: 1
  bugsnag.com: 3
  dn0qt3r0xannq.cloudfront.net: 2
  google.com: 6
  googletagmanager.com: 1
  googletagservices.com: 1
  quantserve.com: 1
```
</details>

**Comment by okiehsch** [comment]
I am geoblocked, so I can't tell if the video plays without issue.
Does it work if you add
`@@||now.gg/*/startSession$xhr,1p`
to your filter list?

**Comment by gorhill** [comment]
I can reproduce. @MyFavGameIsRoblox, can you confirm the filter below solves your issue?

    @@||now.gg/*&pagereferrer=$1p,xhr

**Comment by dportvine** [comment]
`https://selfstudybrain.com/play/roblox-corporation/5349/roblox`

<details>
<summary>Screen</summary>

![2023-05-05_212212](https://user-images.githubusercontent.com/111344219/236538112-48a86258-d645-4a9d-ac68-ca5a5478d613.png)
![2023-05-05_212212](https://user-images.githubusercontent.com/111344219/236537999-ebeb7260-1e7d-4041-88b9-e98ce1eb67d2.png)
</details>

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/4a1e71da21598cde704cdd38cb37ffbb4793fcf0
