### ISSUE TITLE
decathlon.in does not load with ublock origin enabled

### ISSUE THREAD

**Issue by Shaurya-Kalia** [uBlockOrigin/uAssets#17951]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The page flashes and goes blank

### URL(s) where the issue occurs.

https://www.decathlon.in/

### uBO version

1.49.2

### Browser name and version

114.0a1 (2023-05-05) (64-bit)

### Settings

- Ticked 'I am an advance user'
- Unticked 'Disable pre-fetching (to prevent any connection for blocked network requests'
- Error occurs with default config also

**Comment by stephenhawk8054** [comment]
It was fixed few hours ago. Can you force update all your filter lists (click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

**Comment by Shaurya-Kalia** [comment]
> It was fixed few hours ago. Can you force update all your filter lists (click the ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then click the ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

After updating the filter lists, the site works
