### ISSUE TITLE
broken: openloadmovies.live server 3 mirror

### ISSUE THREAD

**Issue by F1reP0wer12345** [uBlockOrigin/uAssets#17966]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I don't really know if this is the right place to ask support for a web page being broken while using the default filters, so correct me if I'm not postin the issue right. I recently discovered that one of the filters in the original uBlock filters list (not Badware or any others) contains a rule that somehow breaks the third server for each movie on openloadmovies.live (and probably others). I did some research and found out that if you remove/comment out two lines from the filterlist (i will post the lines below) it fixes the problem and the third server is accesable again. The third server is forwards to another website called membed1.com which seems to only be blocked from openloadmovies.live. If you get the url from network inspector and open it in a new tab, membed1.com on it's own is **not** blocked.
Here are the steps to reproduce the issue:

1. Go to openloadmovies.live and click on any movie. (for demonsrational purpose here's the one i clicked, but this issue occurs on each and every one of them: https://openloadmovies.live/inferno-3/)
2. In the right panel click watch now. (Fun fact they used to have a watch now button for a german spoken version the movie.)
3. Click Server 3 (aparrently with a lot of ads 😜)
4. Click on the top right on mirror server.
5. Watch as the video gets blocked.

Here's what i removed from the filterlist to fix the issue:
```
123films.cc,123moviefree4u.com,123movies.*,123moviesfree4u.com,123moviesla.*,123movieweb.*,194.163.183.129,1xhd.com,720pstream.*,2embed.*,4hiidude.*,6movies.net,9xmovies.*,adsh.cc,adshort.*,afilmyhouse.blogspot.com,allmovieshub.*,animefenix.com,animefrenzy.net,animeshouse.info,animesultra.com,api.webs.moe,apkmody.io,asianplay.*,atishmkv.*,atomixhq.*,attvideo.com,avimobilemovies.net,bdnewszh.com,ccurl.net,cinema.cimatna.com,cloudvideo.tv,cloudvideotv.*,crackstreams.*,crazyblog.in,crictime.*,daddylive.*,databasegdriveplayer.*,dembed1.com,dembed2.com,dloader.*,dood.*,dvdplay.*,easylinks.*,egynow.cam,embed.meomeo.pw,embedstream.me,extralinks.*,extramovies.*,fanproj.net,faselhd.*,filemoon.*,filmovi.ws,filmy.*,filmyhit.*,filmywap.*,filmyzilla.*,filmyzilla.filmywap2021ganduworld.com,filmyzilla.filmywap2021ganduworld.com,filmyzilla2021.xyz,filmyzilla2022.com,filmyzillafullmovie.waystohunt.info,flexyhit.com,fmovies.*,footyhunter3.xyz,foreverwallpapers.com,foreverwallpapers.com,fsapi.*,gameshdlive.xyz,gdplayer.*,gdriveplayer.*,gdrivez.xyz,goload.*,gomoviefree.*,gomovies.*,gowatchseries.*,hackiee.mobi,hdmoviesfair.*,hdmoviz.*,hindilinks4u.*,hindimovies.to,hinatasoul.com,hitmovies4u.com,hotstar.news,hurawatch.*,hwnaturkya.com,hxfile.co,isaidub.*,isaidub1.com,isaidubhd.*,jalshamoviezhd.*,jiorockers.*,linkshub.*,linksme.*,livecricket.*,madrasdub.*,membed.net,membed1.com,mgnetu.com,mkvcinemas.*,mobilemovies.*,mobilemovieshd.me,movies2watch.*,moviesda1.*,moviesdanet.com,moviesmeta.*,moviespapa.*,moviewatch.com.pk,moviewatchonline.com.pk,mp3juice.info,mp3juices.cc,mp4moviez.*,mydownloadtube.*,neomovies.net,newsrade.com,nolive.me,nollyverse.com,novelssites.com,nsw2u.*,nuroflix.*,oii.io,pctfenix.*,pctnew.*,pepperlive.info,poscitech.*,pirlotv.*,primewire.*,putlocker68.com,s.to,serienstream.*,sflix.*,shahed4u.*,shaheed4u.*,sharkfish.xyz,skidrowcodex.net,speedostream.*,sports-stream.site,sportcast.*,sportskart.*,stream4free.live,streamadblocker.*,streamingcommunity.*,tamilarasan.*,tamilfreemp3songs.*,tamilmobilemovies.in,tamilprinthd.*,tgo-tv.co,thewatchseries.live,tnmusic.in,torrentdosfilmes.eu,travelplanspro.com,tusfiles.com,unlimitmovies.com,uploadflix.org,uploadrar.*,uqload.*,userscloud.com,vidcloud9.*,vidoo.*,vidsaver.net,vidspeeds.com,vidsrc.*,vipbox.*,vipboxtv.*,viprow.*,viralitytoday.com,voiranime.stream,vudeo.*,vumoo.*,watchdoctorwhoonline.com,watchomovies.*,webhostingpost.com,webseriesclub.com,yesmovies.*,ylink.bid,ytix.xyz,ytix.xyz,zoro.to,zoto.to##^script:has-text(break;case $.)
0123moviesfree4u.com,0123movie.*,190.115.18.20,123chill.to,123movies.*,123movies-free.*,123moviesfree.*,123movieshub.*,123movieweb.*,123movies-org.*,1xhd.com,1todaypk.*,4movierulz.*,5movies.*,9kmovies.*,a8ix.*,acn.vin,aflizmovies.com,ak4eg.*,anihdplay.com,animixplay.*,asianhdplay.*,atishmkv.*,crackstreams.*,crackstreamshd.click,daddylivehd.*,direct-cloud.*,dood.*,dvdplay.*,embedstream.me,exee.app,f123movies.com,faselhd.*,filmyzilla2022.com,freelivetvon.com,footyhunter.lol,gameshdlive.xyz,gdflix.*,gdtot.*,gembedhd.com,gocast2.com,gogohd.*,goku.to,gomovies.*,hdfriday.*,iflixmovies.*,kickassanime.*,mangaraw.*,megadb.net,megaupto.com,membed1.com,mkvcinemas.*,movembed.cc,moviesmeta.*,mp4upload.com,mreader.co,mydownloadtube.*,naijachoice.com.ng,naijanowell.com,netfilmes.org,nflstreams.me,nolive.me,oii.io,olympicstreams.me,playgo1.cc,putlocker.*,s.to,send.cm,series2watch.*,serienstream.*,seriestv.org,shadowrangers.live,shahed4u.*,shaheed4u.*,streamadblocker.*,streamcloud.best,streamhub.to,streamonsport.*,strtapewithadblock.*,taxielcima.live,tnhitsda.net,tvpclive.com,upbaam.com,uproxy.*,vadbam.net,vavada5com.com,vidcloud9.*,videoplayer.*,vidspeed.cc,vidsrc.*,viidshar.com,vikistream.com,watch-free.tv,watchcartoononline.*,watchomovies.*,watchonlinemoviespk.*,watchseries1.*,watchtvchh.xyz,wecast.to,worldstreams.click,yesmovies4u.*,zoro.to##+js(acs, document.documentElement, break;case $.)
```

### URL(s) where the issue occurs.

membed1.com on openloadmovies.live

### uBO version

1.49.2

### Browser name and version

Chrome 113.0.5672.63

### Settings

To fix the issue on my end i just removed the original file filters list (again not badware and others) and uploaded a modififed version without the lines provided above.
I don't know what you mean by fixing some issue in firefox, but it certainly breaks things on chrome. (see the lines above that in the filterlist)

### Notes

I just want this issue fixed globally, not just on my end.

**Comment by okiehsch** [comment]
Hm, I only need to add
````
*$frame,3p,denyallow=gdriveplayer.io|isostech.com|jwcdn.com|membed.net|m.media-amazon.com|subscene.gdriveplayer.me|themoviedb.org|tmdb.org,from=databasegdriveplayer.*,badfilter
*$frame,3p,denyallow=gdriveplayer.io|isostech.com|jwcdn.com|membed.net|membed1.com|m.media-amazon.com|subscene.gdriveplayer.me|themoviedb.org|tmdb.org|vidcloud9.com|vidnode.net,from=databasegdriveplayer.*
````
for the video to play on my end.
Can you test if these filters work for you too?

**Comment by F1reP0wer12345** [comment]
Really quick reply. Thank you! Are you sure you tried every server? With these in place i still can't get the third server to work. And I must've done somthing wrong in my exmaple because i just checked my trusted website page and it seems i accidentally added openloadmoevies.live in there. Whoops!
Here's the link on its own:
https://membed1.com/streaming.php?id=NzIwNjY=&title=Inferno+%282016%29+HD-720p&typesub=SUB&sub=L2luZmVybm8tMjAxNi1oZC03MjBwL2luZmVybm8tMjAxNi1oZC03MjBwLnZ0dA==&cover=Y292ZXIvaW5mZXJuby0yMDE2LWxhcmdlLnBuZw==

**Comment by F1reP0wer12345** [comment]
Nevermind you're right those filters do work. I just had my page inspector open in the background, and it seemed like it loaded after that was closed. Thank you!

**Comment by okiehsch** [comment]
Update your filter lists in a few minutes, should work fine after that.

**Comment by F1reP0wer12345** [comment]
It works now. Thanks to you my issue was solved in less then 30 minutes. That's record time to me. Thank you so much!

**Comment by ghajini** [comment]
@okiehsch you can remove that denyallow, it was added for propeller stuff, now other filters take care of them

**Comment by okiehsch** [comment]
Ok.
