### ISSUE TITLE
apkmody.io: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#17962]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://apkmody.io/apps/vpn-unlimited`

### Category

ads

### Description

banner

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/19517680/236631321-f5da2bfc-d481-425e-bfa6-fc160c6cf96f.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 102196
 cosmetic: 91646
 scriptlet: 23778
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@main/dist/adblockid.adfl.txt: 9193-4, 6h.21m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@main/dist/adblockid_plus.adfl.txt: 77-4, 11h.21m
  IDN-0: 5500-367, 11h.22m
  fanboy-cookiemonster: 46919-222, 4d.12h.39m
  ublock-annoyances: 4965-55, 4d.12h.39m
 default: 
  user-filters: 40-0, never
  easylist: 66392-56, 4d.12h.39m
  easyprivacy: 32218-44, 4d.12h.39m
  plowe-0: 3742-934, 4d.12h.39m
  ublock-abuse: 70-0, 4d.12h.39m
  ublock-badware: 6981-126, 4d.12h.39m
  ublock-filters: 33437-237, 4d.12h.38m
  ublock-privacy: 393-73, 4d.12h.38m
  ublock-quick-fixes: 231-15, 11h.20m
  ublock-unbreak: 2006-38, 4d.12h.38m
  urlhaus-1: 7795-1, 6h.20m
filterset (user): [array of 40 redacted]
trustedset: 
 added: [array of 41 redacted]
 removed: 
  chrome-extension-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3191 ms (selfie)
 maxAssetCacheWait: 326 ms
popupPanel: 
 blocked: 9
 network: 
  1558334541.rsc.cdn77.org: 1
  cabioredtop.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 2
  googletagmanager.com: 1
  push-sdk.net: 1
  rebakeassets.com: 1
  yandex.ru: 1
 cosmetic: 
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##.ad-unit:not(.text-ad):not(:empty)
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
  #@#.ad-unit
```
</details>

**Comment by krystian3w** [comment]
Compatible with EasyList:

```adb
###body-fixed-footer
##.body-fixed-footer
```

**Comment by okiehsch** [comment]
@ryanbr 
`apkmody.io##.body-fixed-footer`
