### ISSUE TITLE
minecraft-france.fr: breakage

### ISSUE THREAD

**Issue by saphir88** [uBlockOrigin/uAssets#17969]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.minecraft-france.fr/`

### Category

breakage

### Description

Many images don't show properly the first time I visited a page of this website.
But, when I press F5 to reload the page, all image are showed properly.
I have discussed about this issue with the webmaster of the website, he doesn't know why some image but not other do that ...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

At the 2nd page of the website : https://i.imgur.com/YaFn0cP.png
In a random article : https://i.imgur.com/NxCshLi.png

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 112446
 cosmetic: 49139
 scriptlet: 17581
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  FRA-0: 28347-31, 1d.14h.11m
  easylist: 66299-300, 5d.4h.8m
  easyprivacy: 32231-337, 3d.3h.37m
  plowe-0: 3741-957, 6d.7h.21m
  ublock-abuse: 70-1, 7d.13h.9m
  ublock-badware: 7111-141, 14h.41m
  ublock-filters: 33231-162, 12h.39m
  ublock-privacy: 393-73, 7d.13h.8m
  ublock-quick-fixes: 217-20, 1h.25m
  ublock-unbreak: 2008-40, 12h.38m
  urlhaus-1: 7795-1, 9h.20m
filterset (user): [empty]
trustedset: 
 added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 168 ms (selfie)
 maxAssetCacheWait: 72 ms
popupPanel: 
 blocked: 12
 network: 
  minecraft-france.fr: 1
  cloudflareinsights.com: 1
  google.com: 1
  googlesyndication.com: 7
  googletagmanager.com: 2
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by u-RraaLL** [comment]
Did you check that the issue does not occur when you disable uBO?

I'm unable to reproduce on my side. Can you make a new browser profile, install and update uBO there, test with default settings and report back?

Btw - your Troubleshooting info says you didn't update filter lists.

**Comment by saphir88** [comment]
Hmmm, sry, it's not uBO ... I have tried this without it and still have this issue (but I didn't have this issue in private browsing).

**Comment by saphir88** [comment]
Hmmm, sry, it's not uBO ... I have tried this without it and still have this issue (but I didn't have this issue in private browsing).
