### ISSUE TITLE
ww8.0123movie.net: breakage

### ISSUE THREAD

**Issue by zdaddy612** [uBlockOrigin/uAssets#17961]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ww8.0123movie.net/movie/bupkis-season-1-1630855139.html`

### Category

breakage

### Description

video doesn't load

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93957
 cosmetic: 40140
 scriptlet: 17419
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  easylist: 66260-45, 5d.13h.28m
  easyprivacy: 32242-40, 3d.23h.56m
  plowe-0: 3746-934, 7d.22h.58m
  ublock-abuse: 70-0, 4d.15h.59m
  ublock-badware: 7111-123, 12h.51m
  ublock-filters: 33377-76, 12h.49m
  ublock-privacy: 393-73, 4d.16h
  ublock-unbreak: 2007-34, 12h.50m
  urlhaus-1: 7795-1, 48m
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 62 redacted]
switchRuleset: 
 added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3120 ms (selfie)
 maxAssetCacheWait: 1683 ms
popupPanel: 
 blocked: 4
 network: 
  0123movie.net: 1
  begantotireo.xyz: 1
  dmz3nd5oywtsw.cloudfront.net: 1
  google-analytics.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Video loads normally for me.

**Comment by krystian3w** [comment]
> -[x] I did not answer truthfully to ALL the above checkpoints.

So do it twice / triple:


> -[x] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

> ```yml
>  easylist: 66260-45, 5d.13h.28m
>  easyprivacy: 32242-40, 3d.23h.56m

Both should be update in same time like list "uBO filters.txt-filters-2023.txt".
