### ISSUE TITLE
digitalocean.com: breakage

### ISSUE THREAD

**Issue by lrnbrad** [uBlockOrigin/uAssets#17964]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.digitalocean.com/community/tutorials/spring-ioc-bean-example-tutorial`

### Category

breakage

### Description

The hyperlink is working after googletagmanager.com is not filtered by uBlock.
(By adding !googletagmanager.com in My filters)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 93909
 cosmetic: 40251
 scriptlet: 17475
 html: 951
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34165-63, 9h.35m
  ublock-badware: 7136-0, 9h.34m
  ublock-privacy: 443-0, 5d.11h.30m
  ublock-abuse: 70-70, 5d.11h.30m
  ublock-unbreak: 2019-2, 9h.33m
  ublock-quick-fixes: 228-0, 9h.32m
  easylist: 66260-605, 5d.11h.30m
  easyprivacy: 32242-609, 5d.11h.30m
  urlhaus-1: 7795-1, 14h.4m
  plowe-0: 3741-4, 5d.11h.30m
filterset (user): [empty]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1055 ms (selfie)
 maxAssetCacheWait: 262 ms
popupPanel: 
 blocked: 2
 network: 
  digitalocean.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by krystian3w** [comment]
Added `!googletagmanager.com` to My filers panel works as comment, so you have placebo:

```adb
!googletagmanager.com
```

Highlithed like comment.

**Comment by gorhill** [comment]
Which "hyperlink" is not working? I tried a couple of them at the mentioned page, and no issue.

> By adding `!googletagmanager.com` in My filters

This does nothing, any line starting with `!` is a comment and ignored by uBO.

**Comment by lrnbrad** [comment]
Yes, like @krystian3w mentioned above, sorry for not placing the link highlighted.

**Comment by stephenhawk8054** [comment]
Can you screenshot which hyperlink you are implying to?

**Comment by lrnbrad** [comment]
Okay, here are the links
![Screenshot_2023-05-07_11-58-58](https://user-images.githubusercontent.com/60065304/236656921-406046d4-c951-48b9-9abd-bd8316c94751.png)

**Comment by stephenhawk8054** [comment]
The `2` and `5` links don't work even when I disable uBO. Video recording: https://user-images.githubusercontent.com/66517106/236657544-26009b92-06e5-45ad-9596-834230185c84.mp4

**Comment by okiehsch** [comment]
> The `2` and `5` links don't work even when I disable uBO.

Yes, same on my end seems to be a site issue.

**Comment by gorhill** [comment]
Yes, a site issue, it's misnaming the anchor. For example, number 2 tries to send you to `#sping-bean`, while the section is named `#spring-bean`.

> The hyperlink is working after googletagmanager.com is not filtered by uBlock

Since it's a site issue, above is not true.
