### ISSUE TITLE
cellmapper.net: detection

### ISSUE THREAD

**Issue by VorpalBlade** [uBlockOrigin/uAssets#17968]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cellmapper.net/`

### Category

detection

### Description

Website shows the following message:

> We've detected that you are currently using an ad blocker.
> This site relies on advertising in order to provide this free service.

> Please turn off your ad blocker. You can find instructions on how to do so [at the following link](https://www.wikihow.com/Disable-AdBlock)
> Alternatively, you can sign up to be a [Premium Member](https://www.cellmapper.net/subscribe) to remove ads from both the website and mobile app. More information is available [here.](https://www.cellmapper.net/subscribe)If you are a premium member, you can [log in here](https://www.cellmapper.net/login)

There is an old bug #2454, but I tried the suggestion from it, which gives me a syntax error if I add it to my custom filters. Maybe I'm doing it wrong. Or I assume that they have changed their detection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/3315306/236645194-fe0bd774-1c4b-4cad-9f76-deca30bf20a0.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 93589
 cosmetic: 40354
 scriptlet: 17475
 html: 950
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  ublock-filters: 34219-62, 4d.1h.10m
  ublock-badware: 6985-0, 4d.1h.9m
  ublock-privacy: 373-0, 8d.8h.9m
  ublock-abuse: 70-0, 8d.8h.8m
  ublock-unbreak: 2018-0, 4d.1h.8m
  easylist: 66411-608, 4d.1h.11m
  easyprivacy: 32233-609, 4d.1h.12m
  urlhaus-1: 7542-1, 23h.8m
  plowe-0: 3742-4, 5d.10m
  ublock-quick-fixes: 222-2, 10h.8m
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 322 ms (selfie)
 maxAssetCacheWait: 65 ms
popupPanel: 
 blocked: 10
 network: 
  cellmapper.net: 1
  google-analytics.com: 1
  google.com: 7
  googlesyndication.com: 1
 cosmetic: 
  ###myAd:not(:empty)
  ###bottomad
  ##ins.adsbygoogle
```
</details>

**Comment by gorhill** [comment]
I can't reproduce.

One way I can reproduce is by preventing the redirect of `pagead2.googlesyndication.com` to a local resource. This suggests something else (another extension) in your browser is interfering negatively with uBO.

**Comment by peace2000** [comment]
I can't reproduce that either but there is a left-over "Ads" bar that should be handled by Easylist.

https://user-images.githubusercontent.com/17256841/236649815-01af5305-eeda-472e-9b3e-a732f27aa4fd.png

@ryanbr

**Comment by okiehsch** [comment]
`cellmapper.net###modal_av_details`
for the left-over.
