### ISSUE TITLE
templatesearch.org: badware

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#17960]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Posted on Reddit but not currently answered:
https://www.reddit.com/r/uBlockOrigin/comments/1368ekl/template_search_badware/

### URL(s) where the issue occurs.

`https://templatesearch.org/`

### Screenshot(s)

![Screenshot from 2023-05-05 22-34-33](https://user-images.githubusercontent.com/89158249/236594146-b281f8b1-35f2-4742-8090-0be219e62e41.png)

### uBO version

v1.49.3b4

### Browser name and version

Firefox 112.0.2

### Settings

- Using custom filters/filter lists, checking "I am an advanced user"

**Comment by stephenhawk8054** [comment]
This is its XPI: [e36a82a384dd41e3bdea-1.22.1006.zip](https://github.com/uBlockOrigin/uAssets/files/11412000/e36a82a384dd41e3bdea-1.22.1006.zip)

I can't find any scanning results with it to decide. Reading the code, looks like it changes default search engine to `https://search.yahoo.com/yhs/search?hspart=trp&hsimp=yhs-001&grd=1&type=Y167_F163_202037_102020*`. Not a good link<sup>1</sup> <sup>2</sup> . I think it should be added to badware but I'm not totally sure.

@gorhill Do you have any observations with this add-on's code?

[1] https://malwaretips.com/blogs/remove-search-yahoo-com/
[2] https://www.pcrisk.com/removal-guides/8835-search-yahoo-com-redirect

**Comment by gorhill** [comment]
> Do you have any observations with this add-on's code?

I can't start to review extension code each time someone reports something without much details about why this should be blocked. The onus of making the case why something should be blocked is on the reporter, if there is not detailed rationale of why this should be blocked, we close as invalid.

**Comment by gorhill** [comment]
When clicking _"Add to Firefox"_, Firefox warns _"Make sure you trust this site before continuing"_, that is not for uBO to decide whether the extension is legitimate. If you have evidence of serious issue of malice with the extension, document here with all the technical details. Closing as _invalid_ given there is no detailed explanation of why this should be blocked.

**Comment by Sonic5435325** [comment]
@gorhill Well, there is this:
https://www.pcrisk.com/removal-guides/21353-template-search-browser-hijacker
https://malwaretips.com/blogs/remove-template-search-newtab/

Also says: "Additionally, Template Search has data tracking abilities, which are employed to spy on users' browsing activity. Since most users inadvertently download/install browser hijackers, they are also classified as PUAs (Potentially Unwanted Applications)"

There are some more articles on it too, like this one:
https://malwarefixes.com/template-search-newtab/

"Following the successful installation of questionable freeware, it drops a browser extension which aims to control internet applications such as Google Chrome, Mozilla Firefox, or Edge. Template Search Newtab will be the new look and feel of the home page and new tab window. All user search entries are redirected to Template Search Newtab for malicious intent. Generally, individuals behind Template Search Newtab can gather online information from computer users through this unlawful transmission of data."

Plus, even the site itself looks suspicious, immediately prompting you to download the extension and basically nothing else.

**Comment by gorhill** [comment]
In that case we can add the site, along with the two links to document the reason why it was added.
