### ISSUE TITLE
kaas.am - ads

### ISSUE THREAD

**Issue by 5o6** [uBlockOrigin/uAssets#17979]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ads not being blocked on kaas.am, may be local hosted or from a new source? Currently using element zapper to circumvent the issue.

### URL(s) where the issue occurs.

'kaas.am' Mild NSFW

### uBO version

1.49.2

### Browser name and version

Chrome 112.0.5615.138

### Settings

n/a

**Comment by u-RraaLL** [comment]
Duplicate #17971
