### ISSUE TITLE
findmystreet.co.uk: breakage

### ISSUE THREAD

**Issue by Scarlet-Dragon** [uBlockOrigin/uAssets#17976]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.findmystreet.co.uk/map`

### Category

breakage

### Description

When I have uBlock enabled and visit the webpage https://www.findmystreet.co.uk/map the page does not display a red "Report Feedback" tab that displays on the right hand side of the screen.

When I have uBlock disabled and visit the webpage https://www.findmystreet.co.uk/map the page correctly displays the "Report Feedback" tab on the right hand side of the screen.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://user-images.githubusercontent.com/54205922/236668057-84834dac-8a0d-4466-b213-1b6345a2dd3b.jpg)

Screenshot showing uBlock enabled and uBlock disabled
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 94301
 cosmetic: 40381
 scriptlet: 17499
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66774-46, 1d.1h.21m
  easyprivacy: 32241-43, 1d.1h.22m
  plowe-0: 3746-936, 10d.13h.44m
  ublock-abuse: 70-0, 10d.13h.47m
  ublock-badware: 7111-128, 2d.35m
  ublock-filters: 33358-95, 2d.34m
  ublock-privacy: 323-4, 10d.13h.46m
  ublock-quick-fixes: 217-15, 12h.29m
  ublock-unbreak: 2007-36, 2d.33m
  urlhaus-1: 7795-1, 1d.1h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2297 ms (selfie)
 maxAssetCacheWait: 221 ms
popupPanel: 
 blocked: 6
 network: 
  doll8tune.com: 1
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 1
  youtube.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=findmystreet.co.uk
@@||deploy.mopinion.com^$script,xhr,domain=findmystreet.co.uk
@@||collect.mopinion.com/assets/surveys/*/js/survey.min.js$script,domain=findmystreet.co.uk
@@||cacheorcheck.mopinion.com/survey/public/json-config$xhr,domain=findmystreet.co.uk
```

@ryanbr

**Comment by okiehsch** [comment]
Pretty sure every site using `mopinion` as a feedback source will have the same issue.

**Comment by stephenhawk8054** [comment]
Yeah I'm afraid so

**Comment by ryanbr** [comment]
Won't fix, googletagmanager tracker, and mopinion.com tracks/fingerprints. Bad for privacy.

**Comment by okiehsch** [comment]
I checked a few and all of them use `googletagmanager.com/gtm.js`  to trigger `mopinion` requests, so even removing it from `EasyPrivacy` would not work.

**Comment by okiehsch** [comment]
@stephenhawk8054 The one I found used the feedback only as a survey, so I will not fix that.
This issue uses the feedback for the purpose of reporting a site pronblem too, so fixing is is OK imo.

**Comment by stephenhawk8054** [comment]
I agree.
