### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by Nandan-Gamer** [uBlockOrigin/uAssets#17975]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aternos.org/addons/list/1/continunity`

### Category

detection

### Description

![image](https://user-images.githubusercontent.com/110408822/236667302-af7ed1cb-403d-4e04-949f-e2b3dd23bdc1.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 93641
 cosmetic: 40478
 scriptlet: 17475
 html: 951
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34108-41, 7m
  ublock-badware: 7099-1, 6m
  ublock-privacy: 372-0, 12d.16h.37m
  ublock-abuse: 70-0, 10d.17h.21m
  ublock-unbreak: 2021-3, 5m
  ublock-quick-fixes: 214-22, 2m
  easylist: 67019-625, 4m
  easyprivacy: 32226-609, 3m
  urlhaus-1: 7132-1, 2m
  plowe-0: 3742-2, 5d.25m
filterset (user): [empty]
trustedset: 
 added: [array of 5 redacted]
 removed: 
  about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1500 ms
 maxAssetCacheWait: 432 ms
popupPanel: 
 blocked: 12
 network: 
  aternos.org: 1
  4dex.io: 1
  ad-delivery.net: 1
  amazon-adsystem.com: 1
  aniview.com: 1
  cloudflareinsights.com: 2
  cpx.to: 1
  d1oykxszdrgjgl.cloudfront.net: 1
  doubleclick.net: 1
  google-analytics.com: 1
  quantserve.com: 1
 cosmetic: 
  #@#.sidebar:style(width: 0px !important;)
```
</details>

**Comment by Daxy7** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/13144
