### ISSUE TITLE
magesy.blog: nuisance

### ISSUE THREAD

**Issue by ishikawamaako** [uBlockOrigin/uAssets#17974]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.magesy.blog/pages/2/`

### Category

nuisance

### Description

Detects adblocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93650
 cosmetic: 40488
 scriptlet: 17483
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 67020-46, now
  easyprivacy: 32231-46, now
  plowe-0: 3743-936, now
  ublock-abuse: 70-0, now
  ublock-badware: 7095-128, now
  ublock-filters: 33230-82, now
  ublock-privacy: 394-74, now
  ublock-quick-fixes: 217-20, now
  ublock-unbreak: 2010-36, now
  urlhaus-1: 7132-1, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1069 ms
 maxAssetCacheWait: 445 ms
popupPanel: 
 blocked: 8
 network: 
  magesy.blog: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
  maagesy.com: 2
  magesy.news: 1
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by okiehsch** [comment]
The fix in `ublock-quick-fixes` still works on my end.
