### ISSUE TITLE
canales.online: popups

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#17970]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

abusive popups

### URL(s) where the issue occurs.

`https://canales.online/`

### Screenshot(s)

xd

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Google Chrome Versión 113.0.5672.64 (Build oficial) (64 bits)

### Settings

No change

### Notes

No change

**Comment by stephenhawk8054** [comment]
Can you force update all the filter lists and test again?
