### ISSUE TITLE
kaas.am: ads

### ISSUE THREAD

**Issue by Necessarycoot72** [uBlockOrigin/uAssets#17971]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kaas.am/`

### Category

ads

### Description

Ads are shown on site, even with easylist enabled and updated.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 236268
 cosmetic: 205127
 scriptlet: 39634
 html: 1116
listset (total-discarded, last-updated): 
 added: 
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 43542-4138, 2d.23h.4m
  adguard-generic: 70546-6246, 2d.23h.8m
  adguard-mobile: 8721-13, 2d.23h.7m
  adguard-spyware-url: 1005-5, 2d.23h.6m
  block-lan: 47-0, 6d.23h.48m
  curben-phishing: 87289-33, 1d.1h.8m
  curben-pup: 190-0, 1d.1h.7m
  adguard-annoyance: 67866-918, 2d.23h.5m
  fanboy-annoyance: 90426-20562, 6d.23h.48m
  ublock-annoyances: 4927-4, 6d.23h.48m
 default: 
  user-filters: 30-5, never
  ublock-filters: 34236-99, 1d.23h
  ublock-badware: 7115-0, 1d.22h.59m
  ublock-privacy: 443-0, 6d.23h.48m
  ublock-abuse: 70-70, 6d.23h.48m
  ublock-unbreak: 2018-3, 1d.22h.58m
  ublock-quick-fixes: 214-0, 11h.7m
  easylist: 66774-690, 23h.6m
  easyprivacy: 32226-13875, 23h.5m
  urlhaus-1: 7795-1, 1d.1h.9m
  plowe-0: 3741-89, 6d.23h.48m
filterset (user): [array of 30 redacted]
trustedset: 
 removed: 
  about-scheme
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 761 ms (selfie)
 maxAssetCacheWait: 522 ms
popupPanel: 
 blocked: 2
 network: 
  googletagmanager.com: 1
  notorietynoblemanproposition.com: 1
 cosmetic: 
  ##iframe[width=\"300\"][height=\"250\"]
  ##.mdi-twitter
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||kaas.am^$subdocument,1p
||wixstatic.com/media/*.gif$image,domain=kaas.am
```
@ryanbr
