### ISSUE TITLE
shemalez.com [NSFW] [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1798]
URL(s) where the issue occurs

`https://shemalez.com/videos/2621/hot-cd-playing-with-a-toy/?fr=2621`

Describe the issue

ADS

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by mapx-** [comment]
try

```
shemalez.com##.adv
shemalez.com##.adv__item
shemalez.com##.adv__buy
```

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by huyszn** [comment]
Ad placeholder when you pause a video, ad placeholders to the right of the video, and two sections of ad placeholders when you scroll below the video.
