### ISSUE TITLE
play.anghami.com: ads

### ISSUE THREAD

**Issue by hellwalker1** [uBlockOrigin/uAssets#17986]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.anghami.com`

### Category

ads

### Description

ads still visible 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (1045)](https://user-images.githubusercontent.com/132847154/236698631-b74b8998-0049-44c7-816d-54589b06b4a8.png)

</details>

### Configuration

uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93582
 cosmetic: 40470
 scriptlet: 17439
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 67024-46, 19m
  easyprivacy: 32226-46, 19m
  plowe-0: 3743-936, 19m
  ublock-abuse: 70-0, 18m
  ublock-badware: 7140-129, 18m
  ublock-filters: 33143-82, 18m
  ublock-privacy: 394-74, 18m
  ublock-quick-fixes: 220-20, 18m
  ublock-unbreak: 2010-36, 18m
  urlhaus-1: 7073-1, 18m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1067 ms
 maxAssetCacheWait: 7 ms
popupPanel: 
 blocked: 5
 network: 
  reddit.com: 3
  redditstatic.com: 2
 cosmetic: 
  ##.promotedlink
  ##.AdHeader
  ##.AdUnit
  ##.adsense-ads
  ##.HeaderAd
  ##.SidebarAd
  ##.VerticalAd
  ##._has-ads
  ##.ad--content
  ##.ad-adsense
  ##.googads
  ##.ad-banner-content
  ##.googleAd
  ##.googlead
  ##.hasads
  ##.leftAd
  ##.native-ad
  ##.ADBAR
  ##.ad-medium
  ##.post-ad
  ##.promoad
  ##.rectad
  ##.sidebar-ad:not(div.adsbygoogle)
  ##.small-ad
  ##.sponsorAd
  ##.sponsorPost
  #@#.sidebar-ad

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce the issue?

**Comment by hellwalker1** [comment]
can you explain more sorry im new, is there a setting or filter to block these pop ups on this site

> Can you describe the steps to reproduce the issue?

**Comment by stephenhawk8054** [comment]
I mean, can you describe how you get the ads step-by-step? Because when I log in, I don't see any ads and I don't know how to make the ads appear.

**Comment by stephenhawk8054** [comment]
I tried to listen about 20 songs but could not reproduce the ads.

**Comment by hellwalker1** [comment]
> I tried to listen about 20 songs but could not reproduce the ads.


https://github.com/uBlockOrigin/uAssets/assets/132847154/eecacfbc-a8a4-4cd9-8b07-252f1526275b

pop up example

**Comment by stephenhawk8054** [comment]
Yeah I saw the screenshot, however I'm unable to reproduce the ads while letting the site play many songs.

**Comment by hellwalker1** [comment]
> Yeah I saw the screenshot, however I'm unable to reproduce the ads while letting the site play many songs.

Can you share your settings/filters and any other modification I will try copying them

**Comment by stephenhawk8054** [comment]
Maybe it's geo-related. Which country are you when accessing the site?

**Comment by hellwalker1** [comment]
> Maybe it's geo-related. Which country are you when accessing the site?

Saudi Arabia. I tried using vpn tho same thing

**Comment by stephenhawk8054** [comment]
Then it might be related to account I guess. I don't know how to investigate any more.

**Comment by hellwalker1** [comment]
> Then it might be related to account I guess. I don't know how to investigate any more.

Ads appears if you sign/up with mail and password "other log in option" and not the above facebook or google please try they should appear I just tried
