### ISSUE TITLE
kbb.com: detection

### ISSUE THREAD

**Issue by Cypheriel** [uBlockOrigin/uAssets#17987]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kbb.com/`

### Category

detection

### Description

The Kelley Blue Book page detects that I have an ad blocker. This prevents me from normally accessing the page, and I must disable uBlock Origin before using this website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://user-images.githubusercontent.com/61402923/236706108-a7e5deaf-e919-439c-ba0c-a72a343e64ae.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 93578
 cosmetic: 40467
 scriptlet: 17428
 html: 946
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34018-61, 3m
  ublock-badware: 7099-1, 2m
  ublock-privacy: 444-0, 2m
  ublock-abuse: 70-70, 2m
  ublock-unbreak: 2026-3, 2m
  ublock-quick-fixes: 216-0, 2m
  easylist: 67024-626, 2m
  easyprivacy: 32233-609, 2m
  urlhaus-1: 7073-1, 2m
  plowe-0: 3743-2, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 750 ms (selfie)
 maxAssetCacheWait: 248 ms
popupPanel: 
 blocked: 11
 network: 
  kbb.com: 2
  amazon-adsystem.com: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  googletagmanager.com: 1
  moatads.com: 1
  newrelic.com: 2
  pubmatic.com: 1
 cosmetic: 
  ##[id^=\"kbbAds\"]
```
</details>

**Comment by stephenhawk8054** [comment]
It was fixed a few hours ago: https://github.com/uBlockOrigin/uAssets/commit/4e294e8bf58e7ec821703effbc819c6cadb428b7

Currently I cannot see the anti-adb. Can you force update the filter lists and test again?

**Comment by Cypheriel** [comment]
> It was fixed a few hours ago: [4e294e8](https://github.com/uBlockOrigin/uAssets/commit/4e294e8bf58e7ec821703effbc819c6cadb428b7)
> 
> Currently I cannot see the anti-adb. Can you force update the filter lists and test again?

I just did so. However, the message still pops up.

**Comment by stephenhawk8054** [comment]
Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

Since I cannot reproduce the issue, I cannot help more.

**Comment by Cypheriel** [comment]
> Check if you are using any:
> 
>     * Other extensions,
> 
>     * Browser's built-in blocker,
> 
>     * DNS / VPN / Pi-hole blocking methods,
> 
>     * Blocking apps/softwares outside browser,
> 
>     * OS' hosts file to block domains.
> 
> 
> Since I cannot reproduce the issue, I cannot help more.

I tested on a fresh installation of Google Chrome, and the issue does not appear to be present there. So, I decided to simply uninstall uBlock Origin and reinstall it. The issue seemed to vanish for a little bit immediately after reinstalling. However, after a short amount of time, the pop-up came back. I feel like it's once again important to note that the issue doesn't exist with uBlock Origin disabled for [kbb.com](https://kbb.com/).

<details>
<summary>Installed extensions</summary>
<ul>
  <li>1Password</li>
  <li>Amazon Link Shortener</li>
  <li>Capital One Shopping</li>
  <li>ClearURLs</li>
  <li>Firefox Multi-Account Containers</li>
  <li>LanguageTool</li>
  <li>JetBrains Toolbox</li>
  <li>RetailMeNot</li>
  <li>Return YouTube Dislike</li>
  <li>uBlock Origin</li>
</ul>
</details>

**Comment by stephenhawk8054** [comment]
> So, I decided to simply uninstall uBlock Origin and reinstall it. The issue seemed to vanish for a little bit immediately after reinstalling. However, after a short amount of time, the pop-up came back.

Which browser was it when you did this? Is it the same `fresh installation of Google Chrome` above?

**Comment by Cypheriel** [comment]
> > So, I decided to simply uninstall uBlock Origin and reinstall it. The issue seemed to vanish for a little bit immediately after reinstalling. However, after a short amount of time, the pop-up came back.
> 
> Which browser was it when you did this? Is it the same `fresh installation of Google Chrome` above?

Apologies. The browser I'm having issues with is Firefox (which is what I submitted this issue with). After forcing an update of the filters, I still encounter this issue. The fresh installation of Google Chrome is still fresh, and I still do not encounter that popup. However, I still do on Firefox, even after reinstalling uBlock Origin.

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
@@||kbb.com^$ghide
kbb.com#@#+js(no-setTimeout-if, nrWrapper)
```

Click on uBO's icon, then click on ["gear" icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) to go to the dashboard, then add the filters in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click `Apply changes`, go back to the website and press Ctrl + F5 to reload the page and test again.

**Comment by Cypheriel** [comment]
> Can you test these filters?
> 
> ```
> @@||kbb.com^$ghide
> kbb.com#@#+js(no-setTimeout-if, nrWrapper)
> ```
> 
> Click on uBO's icon, then click on ["gear" icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) to go to the dashboard, then add the filters in ["My filters" pane in the settings](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), click `Apply changes`, go back to the website and press `Ctrl + Shift + R` to reload the page and test again.

That does indeed appear to work. I no longer get the annoying popup with that filter added. Interestingly, all I needed for it to stop popping up was adding `@@||kbb.com^$ghide` to my filters. Removing it causes it to pop up again.

**Comment by stephenhawk8054** [comment]
The 2nd filter is just because with previous filter I see some images not able to load, so I disable it.
