### ISSUE TITLE
chilican.com subdomains: breakage

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#17989]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

```
http://www.grattez.fr/
http://www.hackedgames.com/action/earn-to-die.html
http://www.jeux.com/jeux-sociaux/rami-11822.html
http://www.jeux.com/reflexion/candy-crush/candy-match-3.html
http://www.jouer.fr/racing/trials-ride-2.html
http://www.kissinggames.com/girls/secret-office-kissing.html
http://www.pintgames.com/girls/mario-island.html
http://www.playpink.com/girls/dress-up/my-puppy.html
http://www.prehackshub.com/action/raft-wars.html
```

### Category

breakage

### Description

breakage w/ ads
[continuing from issue 17731](https://github.com/uBlockOrigin/uAssets/issues/17731)

```
@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=hackedgames.com|jouer.fr|kissinggames.com|pintgames.com|playpink.com|prehackshub.com|playhub.com
grattez.fr##.footer-megaban
hackedgames.com,jeux.com,jouer.fr,kissinggames.com,pintgames.com,playhub.com,playpink.com,prehackshub.com##.ad-title-megaban
hackedgames.com,jouer.fr,prehackshub.com,pintgames.com##.ad-game-600
hackedgames.com,jouer.fr,prehackshub.com,pintgames.com##.ad-megaban-game-300
jeux.com###msg_abk
jeux.com###rev-promoted-games
jeux.com##.ad-image-pave
jeux.com##.skyscraper_fixed_right
jeux.com,playhub.com,playpink.com##.ad-title-pave
playhub.com##.promo-game
playhub.com,playpink.com##.ad-title-sky
||jeux.com/js/pu_ad.js$script,1p
||play.turbommo.com^$3p
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 85073
 cosmetic: 42615
 scriptlet: 21101
 html: 1118
listset (total-discarded, last-updated): 
 removed: 
  urlhaus-1: null
  plowe-0: null
 added: 
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 23h.35m
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1672-0, 5h.39m
  https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 5h.39m
  ublock-annoyances: 4937-4, 3d.9h.30m
 default: 
  user-filters: 789-13, never
  ublock-filters: 34164-73, 1d.13h.15m
  ublock-badware: 7115-0, 2d.17h.57m
  ublock-privacy: 444-0, 2d.17h.57m
  ublock-abuse: 70-70, 2d.17h.57m
  ublock-unbreak: 2018-2, 2d.17h.57m
  ublock-quick-fixes: 214-0, 1h.26m
  easylist: 66937-282, 1d.13h.26m
  easyprivacy: 32217-1104, 1d.13h.26m
filterset (user): [array of 738 redacted]
trustedset: 
 added: [array of 1 redacted]
switchRuleset: 
 added: [array of 3 redacted]
hostRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 304 ms (selfie)
 maxAssetCacheWait: 109 ms
 unsuspendAfter: 141 ms
popupPanel: 
 blocked: 6
 network: 
  2mdn.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  googletagservices.com: 2
 cosmetic: 
  ##.ad-game-600
  ##.ad-title-megaban
  ##.ad-megaban-game-300
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by gorhill** [comment]
Does this work for all cases?

    ||2mdn.net/instream/html5/ima3.js$script,redirect-rule=google-ima.js

**Comment by Daxy7** [comment]
Redirect no response
[[Image]](https://user-images.githubusercontent.com/91396482/236807683-5f9d78c6-e98f-4193-977c-f2ccdd1b5fc7.png)
```
http://www.prehackshub.com/action/raft-wars.html
```

**Comment by gorhill** [comment]
> Redirect no response

What does that mean? I don't have Flash installed (and rather not install it). Without the redirect filter, I don't get the screen asking me to install Flash. With the redirect filter, I get to the screen asking me to install Flash. I use default settings/lists, be sur eyou test this way, I don't see you using default lists in troubleshooting information.

**Comment by Daxy7** [comment]
![image](https://user-images.githubusercontent.com/91396482/236810447-514b4a3e-c37a-447f-a427-bb63ed10ade8.png)
tried without custom filters in chrome. getting infinite loading. here's the full logger. I am using ruffle extension to play it
Flash player warning is from a different url `nimrod.gcm-corp.com/games_front_iframe`

**Comment by krystian3w** [comment]
Installing the plug-in to see if there's a difference isn't possible anyway, because you'd have to use as much as Firefox 84 when tomorrow/week will probably see the release of the 113th stable version on macOS and Windows (GNU/Linux as usual depends on the repositories' thymes) (Chromium has been blocked since release 88 and now stable is 113).
