### ISSUE TITLE
realclearpolitics.com: breakage

### ISSUE THREAD

**Issue by Anoneemouse** [uBlockOrigin/uAssets#17997]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On my android 12 phone, using the latest version of firefox, the controls for "latest news" (shifts page to the left), "recommended" (shifts page to the right), the three bars for a menu, and the mid page left and right arrows (also to shift page to the left, or the right), don't work at all with ublock origin on, but work fine with it off. 

On the same phone, all of the controls work fine if I use Chrome rather than Firefox.  

Note, I don't have a clue how to take screenshots on the phone, or use a new unmodified browser profile on an android phone.  It is the only extension I've got on the phone, however.  I'm using my computer - NOT the phone - to write submit this report (in case any troubleshooting info is attached, it's for the wrong device).  I did use the ublock filter update button - but don't know how to clear the cache first on a phone like you do using the shift button on the computer.  

### URL(s) where the issue occurs.

`https://www.realclearpolitics.com/`

(and all of it's pages)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93477
 cosmetic: 40403
 scriptlet: 17509
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 8-0, never
  easylist: 66934-50, 2d.20h.44m
  easyprivacy: 32242-46, 2d.20h.43m
  plowe-0: 3741-936, 8d.21h.36m
  ublock-abuse: 70-0, 1d.20h.37m
  ublock-badware: 7098-129, 3d.20h.36m
  ublock-filters: 33366-96, 3d.20h.35m
  ublock-privacy: 394-74, 1d.20h.36m
  ublock-quick-fixes: 216-5, 48m
  ublock-unbreak: 2007-36, 3d.20h.34m
  urlhaus-1: 6872-0, 12h.51m
filterset (user): [array of 8 redacted]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4429 ms (selfie)
 maxAssetCacheWait: 131 ms
```
</details>

**Comment by gorhill** [comment]
Broken by EasyPrivacy's generic filters `/gaanalytics.` and `/chartbeat.js`. A single exception fixes the site:

    @@||realclearpolitics.com/esm/assets/js/analytics/$1p,xhr

**Comment by krystian3w** [comment]
This is not secret knowledge:

https://www.google.com/search?q=how+to+create+screenshot+on+android

`https://support.google.com/android/answer/9075928?hl=en` tutorial by Google

**Comment by Anoneemouse** [comment]
Thanks to Gorhill for figuring the problem out!  I added his filter, and the page controls seem to work fine now.  Thank you!!

Thanks also for the info, Krystian3w.  I admit, I didn't search for it (but would have used DDG rather than any other search engine if I had).  In part because even if I had a screenshot, I don't know of any way to easily edit the image on the phone either, and didn't want to take the time to try to look that up also so I could circle things and put arrows on it and so on.  And I don't have anything like GIMP or even IrfanView on the phone, and didn't want to go thru finding, loading, and so on to get one of those just for this.  Seems like Gorhill was able to figure out the problem without an edited screen shot anyhow - and I think the items I noted were pretty obvious to anyone looking at the site on an android device.

**Comment by krystian3w** [comment]
Some kind of editor as preinstalled to paint an arrow maybe there is, I would have to check it on some Motorola at home, since I don't have a cleaner Android called stock (Xiaomi, Oppo and Google Photos have an option to paint arrows or even text on those Full HD screenshots).

Since there is no PM/DM on this platfrom it is rather impossible to continue the discussion without locking this thread due to excess off-topic.
