### ISSUE TITLE
askaair.com: breakage

### ISSUE THREAD

**Issue by bikrrr** [uBlockOrigin/uAssets#17995]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

With uBlock Origin enabled and signed in to Alaska Airlines and on the **Account** › **Profile and settings** page, there are two elements missing: 

- **Travel documents**
- **Seats** 

These elements are shown once uBlock Origin is disabled and the page refreshed. See attached screenshot. 

![uBlock and Alaska Airlines](https://user-images.githubusercontent.com/2607653/236889247-f971396d-d5b6-468e-968a-f72d296488b6.png)

### A specific URL where the issue occurs.

`https://www.alaskaair.com/betaaccount/profile-settings`

### Steps to Reproduce

Prerequisite: Need an Alaska Airlines account.

With uBlock Origin enabled…
1. Sign in at: `https://www.alaskaair.com](https://www.alaskaair.com/`
2. Click on the **Hi, [username]** profile menu in upper right.
3. Click on **Overview and elite status**
4. In the **View** dropdown, click **Profile and settings**

### Expected behavior

Notice the items under **About you** and **Travel preferences**.

### Actual behavior

Disable uBlock Origin and refresh the page. Notice…

-  **About you** now has a **Travel documents** item 
- **Travel preferences** now has a **Seats** item

### Configuration

uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 93336
 cosmetic: 40485
 scriptlet: 17432
 html: 946
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34019-52, 7m
  ublock-badware: 7099-0, 7m
  ublock-privacy: 444-0, 7m
  ublock-abuse: 70-70, 7m
  ublock-unbreak: 2027-2, 7m
  ublock-quick-fixes: 212-0, 7m
  easylist: 67105-633, 7m
  easyprivacy: 32237-609, 7m
  urlhaus-1: 6768-1, 7m
  plowe-0: 3743-4, 7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 218 ms
 maxAssetCacheWait: 82 ms

**Comment by stephenhawk8054** [comment]
Add

```adb
@@||cdn.optimizely.com/datafiles/*.json$xhr,domain=alaskaair.com
```

@ryanbr
