### ISSUE TITLE
123pan.com: ads

### ISSUE THREAD

**Issue by lwd-temp** [uBlockOrigin/uAssets#17993]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.123pan.com/`

### Category

ads

### Description

Please append this rule:
```
www.123pan.com##.VipBanner
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 109558
 cosmetic: 50745
 scriptlet: 17632
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  CHN-0: 26517-112, 2d.46m
  easylist: 67082-104, 1h.11m
  easyprivacy: 32241-65, 2d.47m
  plowe-0: 3742-938, 4d.1h.57m
  ublock-abuse: 70-0, 5d.1h.45m
  ublock-badware: 7129-129, 1d.27m
  ublock-filters: 33228-101, 1d.26m
  ublock-privacy: 393-74, 5d.1h.44m
  ublock-quick-fixes: 217-20, 8h.16m
  ublock-unbreak: 2010-37, 1d.25m
  urlhaus-1: 7073-1, 22h.24m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 548 ms (selfie)
 maxAssetCacheWait: 94 ms
popupPanel: 
 blocked: 2
 network: 
  baidu.com: 1
  cnzz.com: 1
 cosmetic: 
  ##.VipBanner
```
</details>

**Comment by okiehsch** [comment]
That hides a banner leading to `https://www.123pan.com/MemberIntroduction`
We eon't fix that.

**Comment by lwd-temp** [comment]
> That hides a banner leading to `https://www.123pan.com/MemberIntroduction` We won't fix that.

Why this won't be fixed? It's common that an AD has a link to somewhere.

Or I'm creating issues at a wrong repo?

**Comment by lwd-temp** [comment]
> https://www.123pan.com/

![image](https://user-images.githubusercontent.com/26019675/236835781-1b780e2b-ace9-443e-a5e4-8db96baf6b17.png)

"Membership benefit (VIP of the cloud storage service) comes with extra storage capacity" (The big characters)
"No change to free user benefits when VIP feature goes live" (The small characters)

**Comment by okiehsch** [comment]
We don't block self-advertisement, no main adblocking list does, see `https://easylist.to/pages/policy.html` for example.

**Comment by lwd-temp** [comment]
Thanks. Got it.
