### ISSUE TITLE
play.tv3.ee: detection

### ISSUE THREAD

**Issue by nata1993** [uBlockOrigin/uAssets#17994]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.tv3.ee/series/saatuslik-valik,serial-5137484/osa-37,episode-5137543`

### Category

detection

### Description

Site detects uBlock Origin and does not allow playing videos.
![Screenshot 2023-05-08 at 20 37 40](https://user-images.githubusercontent.com/6074645/236892432-102cb1de-c784-460a-86f5-f5eadb321134.png)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93544
 cosmetic: 40428
 scriptlet: 17460
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66957-46, 1d.28m
  easyprivacy: 32226-46, 1d.28m
  plowe-0: 3741-936, 8d.48m
  ublock-abuse: 70-0, 1d.28m
  ublock-badware: 7095-128, 1d.28m
  ublock-filters: 33166-82, 1d.28m
  ublock-privacy: 393-74, 8d.48m
  ublock-quick-fixes: 217-20, 6h.26m
  ublock-unbreak: 2015-36, 1d.28m
  urlhaus-1: 7073-1, 1d.28m
filterset (user): [empty]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1810 ms
 maxAssetCacheWait: 556 ms
popupPanel: 
 blocked: 7
 network: 
  tv3.ee: 1
  bepolite.eu: 1
  chartbeat.com: 1
  fwmrm.net: 1
  gemius.pl: 1
  googletagmanager.com: 1
  sentry.io: 1
 cosmetic: 
  ###AdHeader
  ###AD_Top
  ###homead
  ###ad-lead
```
</details>

**Comment by dimisa-RUAdList** [comment]
Similarly: https://github.com/easylist/ruadlist/commit/484c92e31ca71e62be55609cafc00d8a7c5de335
```
play.tv3.ee##+js(set-constant, Object.prototype.isNoAds, {})
play.tv3.ee#@##AD_Top
play.tv3.ee#@##AdHeader
play.tv3.ee#@##ad-lead
play.tv3.ee#@##homead
```

**Comment by okiehsch** [comment]
`@@||play.tv3.ee^$ghide`
seems to work on my end, the detection isgone but I am ger-blocked.

**Comment by dimisa-RUAdList** [comment]
@okiehsch
Yes, it will work, but without the scriptlet, the video will start with a delay.

**Comment by nata1993** [comment]
Didn't work for me but when applied custom filter using dimisa-RUAdList filter tags, everything perfectly fine now. Zero adds at the beginning and zero adds during the playback. Many thanks and kisses from my SO!

**Comment by nata1993** [comment]
Are those tags already added to some filterlist? If not, maybe possible to add?

**Comment by okiehsch** [comment]
I just added a fix, including the scriptlet, just update your filter lists.
