### ISSUE TITLE
weatherwx.com: ad placeholder

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#17999]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad placeholders on the page. Also a hidden "News Headlines" button.
Filters I've used so far:
`weatherwx.com##.adhere4`
`weatherwx.com##div.whileprint.col-md-12 > .text-center.card.entry`
`weatherwx.com##.card-row > .noprint.card-row > .text-center.card.entry`
`weatherwx.com##.col-md-3:has(ins.adsbygoogle)`

Network filters:
`||weatherwx.com/250x600.php`
`||weatherwx.com/728x90a.php`

For the News Headlines button:
`weatherwx.com#@#.adbutton`

Worth noting:
https://github.com/easylist/easylist/issues/15520

### URL(s) where the issue occurs.

https://www.weatherwx.com/forecast.php?config=&forecast=pass&pass=currentwx&usecountry=australia
https://www.weatherwx.com/forecast.php?forecast=pass&pass=airports&icao=keet

### Screenshot(s)

![Screenshot from 2023-05-08 18-13-41](https://user-images.githubusercontent.com/89158249/236950458-3a1854c8-8979-46f7-a4f3-9a6dbdeaf482.png)
![Screenshot from 2023-05-08 18-18-46](https://user-images.githubusercontent.com/89158249/236950464-fa58d8f8-d289-4002-b92d-f887daafe1de.png)
![Screenshot from 2023-05-08 18-18-53](https://user-images.githubusercontent.com/89158249/236950472-b8965560-f103-4867-a816-0c362c60d2b0.png)

### uBO version

v1.49.3b7

### Browser name and version

Firefox 112.0.2

### Settings

- Using custom filter lists

**Comment by Sonic5435325** [comment]
@stephenhawk8054 Could `weatherwx.com##.adhere4` also be added?
![Screenshot from 2023-05-08 22-23-19](https://user-images.githubusercontent.com/89158249/236977921-37b92e2f-c219-4560-b6be-c2bf131b17ab.png)

**Comment by stephenhawk8054** [comment]
`##.adhere4` does not match any thing on my side: https://user-images.githubusercontent.com/66517106/236981536-63c7e4fc-da69-49e3-a916-c73b208ac48e.png

**Comment by Sonic5435325** [comment]
https://www.weatherwx.com/forecast.php?forecast=pass&pass=airports&icao=keet
This is the link I used

**Comment by Sonic5435325** [comment]
Also this on https://www.weatherwx.com/forecast.php?config=&forecast=pass&pass=currentwx&usecountry=australia
![Screenshot from 2023-05-08 23-00-09](https://user-images.githubusercontent.com/89158249/236982955-75989cbc-7c5a-4513-8beb-ebaa681d8eba.png)
