### ISSUE TITLE
UBO not loading at FF startup

### ISSUE THREAD

**Issue by fedorvinogradov** [uBlockOrigin/uAssets#18]
### One or more specific URLs where the issue occurs

The problem isn't connected to any particular web site.

### Describe the issue

Just as said in the subject - uBlock Origin doesn't load itself when I start Firefox. It's going this way for about a month or more. So I have to enter Addons Manager, click Disable and then Enable and it starts to work.

### Screenshot(s)

No need of screenshot.

### Your settings

- Browser/version: 45.0.2
- uBlock Origin version: 1.6.8

**Comment by Hrxn** [comment]
Does this also happen with a new Firefox profile? Or after you tried a Firefox reset?

https://support.mozilla.org/en-US/kb/reset-preferences-fix-problems

**Comment by gorhill** [comment]
Here is for filter issues, not issue with [uBlock Origin](https://github.com/gorhill/uBlock) itself. In any case, you will need to do some investigations into your issue, it appears to be specific to you, there is no other such reported issue.
