### ISSUE TITLE
Popads circumvents again

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#180]
### URL(s) where the issue occurs

[NSFW] `http://jizzman.com/`
`https://theproxy.tech/` (fixed in EasyList though)
### Describe the issue

It seems like the Popads popups from https://github.com/gorhill/uBlock/issues/1879 are back. I can only reproduce on a few websites though, namely the ones above. Maybe this is due to an error on my site but it might just be that not all the sites are running the new code yet.
### Screenshot(s)

![](https://cloud.githubusercontent.com/assets/16030872/19841090/a1ce4348-9f04-11e6-879a-21ce3d5f8fb1.png)
### Versions
- Browser/version: Chrome 53.0.2785.116
- uBlock Origin version: 1.9.16

### Settings
- Default

**Comment by Hrxn** [comment]
NB: Chrome 53 is outdated, Chrome stable is 54.x.x.x now..

**Comment by IDKwhattoputhere** [comment]
Sure, I update manually from time to time. Can you reproduce?

**Comment by okiehsch** [comment]
I can reproduce, also occurring on
`www.multiup.org`

![multi](https://cloud.githubusercontent.com/assets/16838044/19842571/7ace9e4e-9f1a-11e6-8d83-9200a9b4c37e.PNG)

**Comment by gorhill** [comment]
@okiehsch You have a specific link for `www.multiup.org`?

**Comment by okiehsch** [comment]
`https://www.multiup.org/download/72301d9035fb97e47f70ce25ee6defc1`

You may have to clear cookies to reproduce.
![multi1](https://cloud.githubusercontent.com/assets/16838044/19861680/c7e0f52e-9f8d-11e6-9951-4c392de5d7b2.PNG)

**Comment by IDKwhattoputhere** [comment]
Another example: [NSFW] `http://watchxxxfree.com/`

**Comment by IDKwhattoputhere** [comment]
This one spawns them as popunders: `skidrowreloaded.com`

**Comment by er4a1** [comment]
on http://www.exrapidleech.info
not only popads circumvents ublock, but also google-analytics.com circumvents ublock

**Comment by gorhill** [comment]
@er4a1 Please, no disinformation -- there is no instance of `google-analytics.com` on this site. If you want to make extraordinary claim, substantiate it, or edit to correct yourself.

**Comment by er4a1** [comment]
My error, the url is http://www.exrapidleech.info/gateway.html
Here is the screenshot where you can see also google-analytics.com
![ex](https://cloud.githubusercontent.com/assets/23292441/20041432/eb3b88a4-a460-11e6-8e19-d2294def9aeb.png)

**Comment by IDKwhattoputhere** [comment]
What we can't see is that uBO is being circumvented by GA. How do you come to that conclusion? The script appears properly blocked and redirected.

**Comment by er4a1** [comment]
Maybe i'm wrong. But also if i had "* google-analytics.com * block", i can't see block, so i think circumvent. Screenshot:
![ex2](https://cloud.githubusercontent.com/assets/23292441/20041591/bda6e368-a463-11e6-8ced-66438e5646c6.png)
If i'm wrong sorry for my error.

**Comment by IDKwhattoputhere** [comment]
Everything seems to be working as intended.
> Red: The request for the resource was canceled because of a block filter/rule.

- https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by gorhill** [comment]
`google-analytics.com` is properly blocked by your rule in your logger screenshot. The yellow line just above is uBO redirecting the request to an internal, neutered version of the script, to minimize likelihood of page breakage. The token identifying the neutered script is `google-analytics.com/analytics.js`. Using the token, you can find the neutered script in there: <https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt>.

**Comment by uBlock-user** [comment]
flixanity.* have also started using popads circumventing scripts and swapping various random domains to circumvent daily. Instead of playing cat and mouse game with them, I'm blocking all 3rd party requests and only putting some exceptions rules for some necessary resources to let in. That's the best way to deal with them.

**Comment by okiehsch** [comment]
Popads can be fixed by adding
`example.com##script:inject(popads.net.js)` or 
`example.com##script:inject(abort-on-property-write.js, _pop)`
