### ISSUE TITLE
[nsfw] myvidster.com: detection

### ISSUE THREAD

**Issue by mertandmarcus** [uBlockOrigin/uAssets#18003]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.myvidster.com/`

### Category

detection

### Description

Whenever you're trying to see a video, this is the response 

"We notice that you like our web site and you are also running Adblock :(

We 100% understand why you are running Adblock, but we still need ad revenue to keep the servers running. Please disable Adblock (or add myvidster.com to your whitelist) to continue using our wonderful service. You can also upgrade to [MyVidster PRO](https://www.myvidster.com/get_pro.php) which includes ad removal for popular bookmarked tube sites and you are allow to use your Adblock!"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 95496
 cosmetic: 84039
 scriptlet: 19447
 html: 0
listset (total-discarded, last-updated): 
 added: 
  fanboy-cookiemonster: 61513-14709, 20h.50m
 default: 
  user-filters: 101-2, never
  GRC-0: 995-0, 22h.52m
  easylist: 66789-51, 3d.14h.48m
  easyprivacy: 32237-43, 3d.14h.49m
  plowe-0: 3746-938, 12d.21h.37m
  ublock-abuse: 70-0, 1d.20h.57m
  ublock-badware: 7132-125, 2d.15h.4m
  ublock-filters: 33259-92, 2d.15h.3m
  ublock-privacy: 394-74, 1d.20h.58m
  ublock-quick-fixes: 222-27, 29m
  ublock-unbreak: 2008-38, 2d.15h.1m
  urlhaus-1: 6768-1, 16h.49m
filterset (user): [array of 101 redacted]
trustedset: 
 added: [array of 32 redacted]
 removed: 
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 537 ms (selfie)
 maxAssetCacheWait: 301 ms
popupPanel: 
 blocked: 11
 network: 
  myvidster.com: 1
  addthis.com: 1
  disqus.com: 2
  exosrv.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  traffichaus.com: 2
  viglink.com: 2
 cosmetic: 
  ##.comment-policy-refresh
```
</details>

**Comment by okiehsch** [comment]
TRied a few videos and they all play without issue on my end.

**Comment by mertandmarcus** [comment]
> Ttied a few videos and they all play without issue on my end.

Tried on my phone (I use a different adblock there) and it's ok but on my laptop I continue seeing this popup. Do you, maybe, have an idea why it's detecting the adblock?

**Comment by okiehsch** [comment]
I tested on my laptop, so that's not it. 😉 

Are you logged in when you see the detection? I don't have an account.

**Comment by mertandmarcus** [comment]
Yes I am logged in, however, I did try watching a video while logged out and it still gave me this message. It usually takes a second and the message replaces the video.
I, also, tried using Microsoft Edge instead of Chrome to see if I still get it, and I do. So, it's not the browser.

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by mertandmarcus** [comment]
Greece, I managed to fix it somehow. I changed my DNS to the AdGuard one and enabled AdGuard - Ads, AdGuard - Annoyances and Fanboy - Annoyances inside the uBlock settings.

**Comment by stephenhawk8054** [comment]
I could not reproduce the issue with default lists either.
