### ISSUE TITLE
seznam.cz: breakage

### ISSUE THREAD

**Issue by RobertBobby007** [uBlockOrigin/uAssets#18002]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

The web `https://www.seznam.cz/profil/robert-knobloch-0ab8678974e2723a54d8c3ce44cb9d7ec0a77e4fac2d5c1268ed` isn't working.

### A specific URL where the issue occurs.

`https://www.seznam.cz/profil/robert-knobloch-0ab8678974e2723a54d8c3ce44cb9d7ec0a77e4fac2d5c1268ed`

### Steps to Reproduce

1. I turn off the extension 
2. Reload the web
3. And it works

### Expected behavior

To work normal

### Actual behavior

The pictures doesn't show up

### Configuration

.

**Comment by gwarser** [comment]
`@@||h.imedia.cz/js/cmp2/scmp.js$script,domain=www.seznam.cz`?

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/labels/broken%20by%20EasyPrivacy

**Comment by okiehsch** [comment]
@ryanbr 
`@@||h.imedia.cz/js/cmp2/scmp.js$script,domain=seznam.cz`
fixes the issue.

**Comment by RobertBobby007** [comment]
Still not working

**Comment by mapx-** [comment]
update all filter lists

**Comment by krystian3w** [comment]
Even twice.

**Comment by RobertBobby007** [comment]
still not working 
<img width="65" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/72411188/df81bd00-716e-404d-a951-e8443aa686fd">

**Comment by RobertBobby007** [comment]
I update it but still not working

**Comment by stephenhawk8054** [comment]
What doesn't work? It looks normal for me. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/fde1dc72-16d9-4680-8978-bb6726bdcad9
