### ISSUE TITLE
exxen.com: detection

### ISSUE THREAD

**Issue by uuqqzz** [uBlockOrigin/uAssets#18005]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.exxen.com/tr/watch-movie/son-savasci-midilli/22606`

### Category

detection

### Description

This requires a subscription
I have created a temporary account for you to check. Please give me an email address to send you the account details.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/110184059/6daf735c-8735-4471-a1ec-2642128af6c7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 134535
 cosmetic: 162281
 scriptlet: 35943
 html: 947
listset (total-discarded, last-updated): 
 removed: 
  urlhaus-1: null
  plowe-0: null
 added: 
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 43871-17485, 3m
  adguard-generic: 70824-6204, 3m
  adguard-spyware-url: 1017-5, 3m
  adguard-annoyance: 67973-1578, 3m
  adguard-social: 20428-32, 3m
 default: 
  user-filters: 63-0, never
  ublock-filters: 33988-94, 3m
  ublock-badware: 7121-0, 3m
  ublock-privacy: 444-0, 3m
  ublock-abuse: 70-70, 3m
  ublock-unbreak: 2027-3, 3m
  ublock-quick-fixes: 248-0, 3m
  easylist: 67176-336, 3m
  easyprivacy: 32240-38, 3m
  TUR-0: 12324-11, 3m
filterset (user): [array of 65 redacted]
modifiedUserSettings: 
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 suspendUntilListsAreLoaded: false
 tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2665 ms (selfie)
 maxAssetCacheWait: 1971 ms
 unsuspendAfter: 436 ms
popupPanel: 
 blocked: 6
 network: 
  criteo.com: 2
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  tiktok.com: 1
 cosmetic: 
  ##.cc-window[aria-label=\"cookieconsent\"]
  ##.cc-banner
  ##.ad-placeholder:not(#filter_ads_by_classname):not(#detect_ad_empire):not(#detect):not(.adsbox)
  ##.adclass
  ##.adloaded
  ##.a-ad
  ##[id^=\"google_ads_iframe\"]
  ##div[id^=\"adspot-\"]
  ##div[id^=\"lazyad-\"]
  ##div[id^=\"sticky_ad_\"]
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by stephenhawk8054** [comment]
The website shows server not responding: https://user-images.githubusercontent.com/66517106/237258630-1e73894a-0ed9-4d07-8c35-0ecc93957ffe.png

**Comment by ghajini** [comment]
i used vpn then account then it ask subscription
so an account is required to reproduce

**Comment by stephenhawk8054** [comment]
You can send account details to this email: `stephenhawk8054@protonmail.com`

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
exxen.com##+js(set, eyeOfErstream.detectedBloke, falseFunc)
@@||exxen.com^$ghide
```

---

@Yuki2718 For Adguard Turkey? Any of 2 filters above work on my side. I just used both to prevent in the future since this issue needs a subscription account to reproduce.

**Comment by Yuki2718** [comment]
Okay, will add them.

**Comment by muhasturk** [comment]
AdGuard filters hide this cookie modal, but uBlock probably continues to display the cookie warning after this error. @Yuki2718 

https://github.com/user-attachments/assets/80bc18f0-7093-4e70-976f-02c485e6512c
