### ISSUE TITLE
myedenred.pt: breakage

### ISSUE THREAD

**Issue by taduo** [uBlockOrigin/uAssets#18007]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.myedenred.pt/`

### Category

breakage

### Description

Dose not work with it active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Active
![image](https://github.com/uBlockOrigin/uAssets/assets/65782880/eeb76130-ca72-49b4-b03d-00e094866a5d)

Disabled
![image](https://github.com/uBlockOrigin/uAssets/assets/65782880/24c056da-529f-4f9c-bed7-836fb95326c8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95070
 cosmetic: 83374
 scriptlet: 19445
 html: 0
listset (total-discarded, last-updated): 
 added: 
  fanboy-cookiemonster: 46984-224, 3d.22h.35m
 default: 
  user-filters: 0-0, never
  easylist: 66934-46, 3d.22h.35m
  easyprivacy: 32241-46, 3d.22h.35m
  plowe-0: 3743-936, 3d.22h.36m
  ublock-abuse: 70-0, 3d.22h.36m
  ublock-badware: 7111-129, 3d.22h.35m
  ublock-filters: 33231-93, 3d.22h.35m
  ublock-privacy: 394-74, 3d.22h.35m
  ublock-quick-fixes: 246-10, 10m
  ublock-unbreak: 2007-37, 3d.22h.35m
  urlhaus-1: 6711-1, 10m
filterset (user): [empty]
trustedset: 
 added: [array of 41 redacted]
 removed: 
  edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 506 ms (selfie)
 maxAssetCacheWait: 156 ms
popupPanel: 
 blocked: 3
 network: 
  myedenred.pt: 1
  google-analytics.com: 1
  maps.googleapis.com: 1
```
</details>

**Comment by okiehsch** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/c46110b0-4368-4af7-a40e-28d9f0a4f251)
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/bc039a33-e9f1-4d42-be92-ea5a9e643be9)

It would help if you answer truthfully....


`@@||myedenred.pt/scripts/views/footer/privacyPolicy.js$script,1p`
@ryanbr
