### ISSUE TITLE
phineypet.com: detection

### ISSUE THREAD

**Issue by natandna** [uBlockOrigin/uAssets#18011]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

adblock detect

### URL(s) where the issue occurs.

`https://phineypet.com/adblock.html`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/112774782/44eae872-f8b8-4b89-aa94-58f3d2d2412e

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Version 113.0.5672.92

### Settings

already update ublock

### Notes

only update

**Comment by stephenhawk8054** [comment]
Can you click on uBO's icon, then click on [Report button (chat icon)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools), scroll to the bottom, click on `Troubleshooting Information` and copy paste it here?

**Comment by natandna** [comment]
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 112688
 cosmetic: 81268
 scriptlet: 31566
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-generic: 70640-1133, 51m
  adguard-mobile: 8732-43, 51m
 default: 
  user-filters: 4195-253, never
  easylist: 67207-952, 51m
  easyprivacy: 32240-159, 51m
  plowe-0: 3742-1029, 51m
  ublock-abuse: 70-0, 51m
  ublock-badware: 7119-348, 51m
  ublock-filters: 33071-6542, 51m
  ublock-privacy: 394-74, 51m
  ublock-quick-fixes: 245-19, 51m
  ublock-unbreak: 2012-92, 51m
  urlhaus-1: 6820-1, 51m
filterset (user): [array of 2860 redacted]
trustedset: 
 added: [array of 74 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1392 ms (selfie)
 maxAssetCacheWait: 558 ms
popupPanel: 
 blocked: 0

**Comment by stephenhawk8054** [comment]
> user-filters: 4195-253, never
> filterset (user): [array of 2860 redacted]

You are using a heavily modified settings (too many custom filters and rules). Please test it again in another profile with only uBO and default settings.

**Comment by natandna** [comment]
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93462
 cosmetic: 40507
 scriptlet: 17398
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 67207-46, 2m
  easyprivacy: 32240-45, 2m
  plowe-0: 3742-936, 2m
  ublock-abuse: 70-0, 2m
  ublock-badware: 7112-128, 2m
  ublock-filters: 33071-91, 2m
  ublock-privacy: 394-74, 2m
  ublock-quick-fixes: 216-11, 2m
  ublock-unbreak: 2015-36, 2m
  urlhaus-1: 6820-1, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3569 ms
 maxAssetCacheWait: 47 ms
popupPanel: 
 blocked: 0

**Comment by stephenhawk8054** [comment]
Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

As I can't reproduce the issue, I cannot help more.

**Comment by natandna** [comment]
My friend have this problem to, i think different country than me

**Comment by gorhill** [comment]
@natandna Be sure you clear cookies after you reset settings, the site might remember that it detected you. Also, be sur eto not navigate to the URL you mention, navigate only to the front page of the site.

**Comment by blade-close** [comment]
yes it's a link shortener, this is the original link `linksfly.me/demo` but just info it has several variant domains, one of which is `phineypet.com` full domain (`allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net,batmanfactor.com,phineypet.com` ). so maybe you can not find or also find the domain. only the `phineypet.com` domain is detected by adb. the other domains are already in the asset filter.

**Comment by mapx-** [comment]
@blade-close you should test yourself the existent filters for `phineypet` and report back.

You should have warned us that this is an old issue (https://github.com/uBlockOrigin/uAssets/issues/14929) avoiding wasting volunteers' time.

**Comment by king-iskan** [comment]
> 

yup, my explanation above.  meant to explain the old problem.  I just help explain.  I have added the new domain.  it doesn't work.  sorry, if I explained wrong

**Comment by waeemo** [comment]
the same problem 
If anyone solved the problem tell me how you solved it 
thaks

**Comment by waeemo** [comment]
these site mybe use https://cdnjs.cloudflare.com/ajax/libs/blockadblock/3.2.1/blockadblock.js
https://github.com/sitexw/BlockAdBlock
