### ISSUE TITLE
click.allkeyshop.com: breakage

### ISSUE THREAD

**Issue by denpxc** [uBlockOrigin/uAssets#18014]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.allkeyshop.com/blog/buy-call-of-duty-modern-warfare-2-cd-key-compare-prices/`
 any link to stores, example:
`https://click.allkeyshop.com/offer/eur/134782734?locale=en&merchant=1&source=www.allkeyshop.com`

### Category

breakage

### Description

**Affected site:**
`https://www.allkeyshop.com/`

**Issue:**
All redirect link to stores are blocked.

**Example:**
`https://www.allkeyshop.com/blog/buy-call-of-duty-modern-warfare-2-cd-key-compare-prices/`
 any link to stores, example:
`https://click.allkeyshop.com/offer/eur/134782734?locale=en&merchant=1&source=www.allkeyshop.com`

**Problem filter:**
Peter Lowe's Ad and tracking server list

**Reply from Peter Lowe (after reporting the issue to him):**
"file an issue with the uBlock Origin developers, who might consider adding an "unbreak" rule"

**Discussion**
We would appreciate reconsidering the block, our links are just direct links only counted by Google Analytics Goals/Conversion, 
It's not going to a secondary server/website.
Following Peter's advice we will also try some technical solutions but it will take a bit of time to develop. (Implement tracking directly on same domain/site. Script under a subdirectory. Pass a URL parameter which would track the source.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Sans titre](https://github.com/uBlockOrigin/uAssets/assets/14055459/692e68e2-5cac-49fe-b2dc-48471ec8f351)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.49.3b8:
 since: 1d.13h.24m
Firefox: 115
filterset (summary):
 network: 111842
 cosmetic: 49441
 scriptlet: 17537
 html: 947
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 34017-41, 19h.40m
  ublock-badware: 7116-1, 19h.40m
  ublock-privacy: 444-0, 19h.40m
  ublock-unbreak: 2027-3, 19h.39m
  ublock-quick-fixes: 247-11, 7h.37m
  easylist: 67145-925, 19h.39m
  easyprivacy: 32240-867, 19h.39m
  urlhaus-1: 6711-1, 19h.39m
  plowe-0: 3742-2, 19h.39m
  FRA-0: 28348-208, 19h.39m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 27 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 193 ms (selfie)
 maxAssetCacheWait: 88 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by krystian3w** [comment]
It would be best not to track and maybe run attribute `data-href` with steam link so that in the future you can use `##+js(href-sanitizer, a[href*=?"][data-href], [data-href])`.

**Comment by stephenhawk8054** [comment]
> counted by Google Analytics Goals/Conversion

I mean, that's why it's blocked in PL's list. We also block trackers and click tracker is one of them.

**Comment by Sirlefou1** [comment]
> I mean, that's why it's blocked in PL's list. We also block trackers and click tracker is one of them.

I understand the blocking of GA resources, but the sub-domain click.allkeyshop.com is just a redirect domain

**Comment by krystian3w** [comment]
At the server level, you can collect the log of who opened the link or the provider already does it without the option to disable it.

**Comment by Sirlefou1** [comment]
> At the server level, you can collect the log of who opened the link or the provider already does it without the option to disable it.

OK, so if we follow your logic we should block all websites

**Comment by krystian3w** [comment]
Talking to me won't do anything.

This stays on the issue of the latest uAssets guidelines whether the filter can be deactivated, e.g. qualitatively similar to the once blocked Twitter short links.

> https://github.com/uBlockOrigin/uAssets/blob/2db618b8809ef8a96e52bfb804657150aee4011d/filters/unbreak.txt#L3880-L3881

Also, you can not refer to old unlocks, they are in the process of reverification, however, does not disoponate data what who and how quickly check, for example, the potential progression with the withdrawal of approvals somewhere around 2030.

**Comment by gorhill** [comment]
How about:

    @@||click.allkeyshop.com/*&source=www.allkeyshop.com$doc
    ||click.allkeyshop.com^$inline-script
