### ISSUE TITLE
[nsfw] beta.character.ai: detection

### ISSUE THREAD

**Issue by kenji012345** [uBlockOrigin/uAssets#18015]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://beta.character.ai/`

### Category

detection

### Description

..

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93310
 cosmetic: 45843
 scriptlet: 17902
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65879-213, never
  easyprivacy: 30899-1169, never
  plowe-0: 3746-946, never
  spa-0: 3640-154, never
  spa-1: 5209-67, never
  ublock-abuse: 70-0, never
  ublock-badware: 6952-1, never
  ublock-filters: 33716-166, never
  ublock-privacy: 323-1, never
  ublock-quick-fixes: 216-0, never
  ublock-unbreak: 1999-1, never
  urlhaus-1: 7286-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1042 ms
 maxAssetCacheWait: 15 ms
popupPanel: 
 blocked: 23
 network: 
  cloudflareinsights.com: 2
  sentry.io: 1
  statsigapi.net: 20
```
</details>

**Comment by okiehsch** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/b16b9c3a-ab4a-4ef7-9a73-60a1ff491bbf)

Good to know.
