### ISSUE TITLE
redditstatic.com

### ISSUE THREAD

**Issue by 2u841r** [uBlockOrigin/uAssets#18018]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I think (sure) this url should be blocked redditstatic.com

### URL(s) where the issue occurs.

reddit.com

### uBO version

1.49.2

### Browser name and version

Chrome Version 112.0.5615.140 (Official Build) (64-bit)

### Settings

no change

**Comment by okiehsch** [comment]
I disagree.

**Comment by gorhill** [comment]
> I think (sure) this url should be blocked redditstatic.com

This makes no sense, that would break the whole site. Hard to believe this is an issue made in good faith.
