### ISSUE TITLE
fredmeyer.com: nuisance

### ISSUE THREAD

**Issue by brynnb** [uBlockOrigin/uAssets#18019]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fredmeyer.com/signin`

### Category

nuisance

### Description

Popup modal with "Save Up to $1,000 per year with Boost**" title asking user to start a free trial when trying to log in

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1423" alt="Screenshot 2023-05-10 at 7 13 35 AM" src="https://github.com/uBlockOrigin/uAssets/assets/1271817/2f155910-d7ac-43a5-9c41-4418a5dd1169">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 104296
 cosmetic: 183308
 scriptlet: 25137
 html: 1117
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 68016-5095, 4m
  adguard-social: 20436-700, 4m
  fanboy-thirdparty_social: 68-0, 4m
  fanboy-annoyance: 90881-81206, 4m
  fanboy-cookiemonster: 47050-266, 4m
  fanboy-social: 17189-17, 4m
  ublock-annoyances: 4942-4, 4m
 default: 
  user-filters: 70-3, never
  ublock-filters: 33980-61, 4m
  ublock-badware: 7122-0, 4m
  ublock-privacy: 444-0, 4m
  ublock-abuse: 70-70, 4m
  ublock-unbreak: 2019-0, 4m
  easylist: 67244-660, 4m
  easyprivacy: 32254-619, 4m
  urlhaus-1: 6939-1, 4m
  plowe-0: 3742-4, 4m
  ublock-quick-fixes: 255-2, 4m
filterset (user): [array of 71 redacted]
trustedset: 
 added: [array of 72 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3028 ms (selfie)
 maxAssetCacheWait: 61 ms
popupPanel: 
 blocked: 8
 network: 
  fredmeyer.com: 1
  adobedtm.com: 1
  cookielaw.org: 1
  demdex.net: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
maintainers notified on slack
