### ISSUE TITLE
Analytics India Magazine doesn't show article content when uBlock is enabled

### ISSUE THREAD

**Issue by shamilsherhan** [uBlockOrigin/uAssets#1801]
### URL(s) where the issue occurs

Any article page of `https://analyticsindiamag.com/`

## Specific links
`https://analyticsindiamag.com/if-alexa-rules-the-smart-home-market-ibms-watson-assistant-is-set-to-rival-the-seattle-giant-in-b2b-space/`

`https://analyticsindiamag.com/google-maps-api-is-the-new-imperative-to-mobile-gaming/`
and many more.

### Describe the issue

The article contents of the posts are hidden whenever uBlock is enabled.

### Screenshot(s)

When uBlock is disabled:
![When uBlock is disabled](https://user-images.githubusercontent.com/20861048/37892831-cfe79254-30f6-11e8-8295-00d1c7205b14.PNG)

When uBlock is enabled:
![When uBlock is disabled](https://user-images.githubusercontent.com/20861048/37892851-e0d7b0c6-30f6-11e8-97c4-c2068f7c1ac2.PNG)

### Versions

- Browser/version: Firefox 59.0.1
- uBlock Origin version: 1.15.18

### Settings

- Enabled all 3rd party filters except regional filters.

**Comment by mapx-** [comment]
add in your custom filters
```
analyticsindiamag.com#@#.share-container
||analyticsindiamag.com/*.gif$image
```

@ryanbr
