### ISSUE TITLE
news.ifeng.com: ads

### ISSUE THREAD

**Issue by light-nian** [uBlockOrigin/uAssets#18012]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://news.ifeng.com/`

### Category

ads

### Description

以前可以屏蔽，最近几天突然屏蔽不了了

**It could be blocked before, but suddenly it can't be blocked in the past few days**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 108800
 cosmetic: 50661
 scriptlet: 17570
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  CHN-0: 26529-112, 2d.21h.50m
  easylist: 66561-102, 5d.19h.19m
  easyprivacy: 32233-60, 1d.18h.3m
  plowe-0: 3743-936, 3d.5h.34m
  ublock-abuse: 70-0, 4d.3h.57m
  ublock-badware: 7112-124, 21h.29m
  ublock-filters: 33106-92, 21h.28m
  ublock-privacy: 394-73, 4d.3h.56m
  ublock-quick-fixes: 245-10, 3h.19m
  ublock-unbreak: 2016-37, 21h.27m
  urlhaus-1: 6720-1, 23h.31m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 3 redacted]
 removed: 
  edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 609 ms (selfie)
 maxAssetCacheWait: 181 ms
popupPanel: 
 blocked: 39
 network: 
  ifeng.com: 23
  5hte21mz.com: 13
  baidustatic.com: 1
  ifengimg.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I don't see any ads. Can you force update all the filter lists and test again?
