### ISSUE TITLE
goplay.be: breakage

### ISSUE THREAD

**Issue by ThomasVanWaeyenberge** [uBlockOrigin/uAssets#18013]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.goplay.be/video/blind-gekocht/blind-gekocht-s4/blind-gekocht-s4-aflevering-7`

### Category

breakage

### Description

The website says that there is something wrong and won't play the video, only when I disable ublock, the video will play. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 86623
 cosmetic: 31242
 scriptlet: 312
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1m
 default: 
  user-filters: 0-0, never
  easylist: 67081-46, 1d.20h.1m
  easyprivacy: 32233-46, 1d.20h
  plowe-0: 3743-936, 2d.10h.1m
  ublock-abuse: 70-0, 2d.10h.1m
  ublock-badware: 7095-128, 18h.33m
  ublock-filters: 0-0, never
  ublock-privacy: 394-74, 2d.10h.1m
  ublock-quick-fixes: 245-1, 8h.30m
  ublock-unbreak: 2010-36, 2d.10h.1m
  urlhaus-1: 6711-1, 8h.31m
filterset (user): [empty]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 229 ms (selfie)
 maxAssetCacheWait: 78 ms
popupPanel: 
 blocked: 13
 network: 
  goplay.be: 1
  cxense.com: 1
  doubleclick.net: 4
  gemius.pl: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  onthe.io: 1
  pbstck.com: 1
  summerhamster.com: 1
```
</details>

**Comment by mapx-** [comment]
yes, working fine enabling `NLD: EasyDutch`

preroll ads again, test:

`goplay.be##+js(json-prune, ads)`

@BPower0036

**Comment by Procyon-b** [comment]
The site works for me with the NLD list.
@mapx- I don't need this filter to avoid preroll. OP's case may differ.

**Comment by mapx-** [comment]
I got preroll stuff on the video above, let's see if @BPower0036 can reproduce it

**Comment by BPower0036** [comment]
@mapx- Sorry for the delay. I had to do a lot of work past days, so I wasn't on Github. 
I didn't get any ads, but it solved a problem we had in https://github.com/EasyDutch-uBO/EasyDutch/issues/39
