### ISSUE TITLE
coles.com.au: breakage

### ISSUE THREAD

**Issue by notalwaysweak** [uBlockOrigin/uAssets#18027]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.coles.com.au/`

### Category

breakage

### Description

When I try to open this site in Firefox with uBlockOrigin on, the site returns an error that is not present if I try to open the site in Chrome without uBlockOrigin on.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 93502
 cosmetic: 40544
 scriptlet: 17480
 html: 951
listset (total-discarded, last-updated): 
 default: 
  user-filters: 8-0, never
  ublock-filters: 34109-41, 2d.20h.48m
  ublock-badware: 7099-1, 2d.20h.48m
  ublock-privacy: 444-0, 2d.20h.48m
  ublock-abuse: 70-70, 2d.20h.48m
  ublock-unbreak: 2026-3, 2d.20h.48m
  ublock-quick-fixes: 254-11, 6h.52m
  easylist: 67082-631, 2d.20h.48m
  easyprivacy: 32226-609, 2d.20h.48m
  urlhaus-1: 6939-1, 6h.53m
  plowe-0: 3743-2, 2d.20h.48m
filterset (user): [array of 8 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 578 ms (selfie)
 maxAssetCacheWait: 173 ms
popupPanel: 
 blocked: 27
 network: 
  adobedtm.com: 6
  adsrvr.org: 1
  bazaarvoice.com: 1
  bing.com: 1
  decibelinsight.net: 1
  demdex.net: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  kampyle.com: 1
  launchdarkly.com: 2
  omtrdc.net: 1
  oracleinfinity.io: 1
  sentry.io: 7
  visualstudio.com: 1
```
</details>

**Comment by mapx-** [comment]
no issue using an australian ip

**Comment by notalwaysweak** [comment]
> no issue using an australian ip

Thanks for checking!

**Comment by notalwaysweak** [comment]
Issue resolved; turns out it was another extension that was in fact affecting privacy settings without me realising.

**Comment by notalwaysweak** [comment]
DuckDuckGo, I was unaware it was affecting privacy settings.
