### ISSUE TITLE
adonisfansub.com: detection

### ISSUE THREAD

**Issue by Kuroiteiken** [uBlockOrigin/uAssets#18020]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://adonisfansub.com/`

### Category

detection

### Description

It detects and display an alert window. I had to use document.getElementById("pfsarjdw-blanket").style='display:none' each time to hide window. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/882130/686e8a4b-0f2d-4f35-b6c0-cb987c0fecfb)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 100673
 cosmetic: 110689
 scriptlet: 24649
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67935-95, 3d.21h.33m
  ublock-annoyances: 4970-172, 6d.6h.31m
 default: 
  user-filters: 0-0, never
  TUR-0: 12324-11, 3d.21h.35m
  easylist: 67145-121, 1d.6h.38m
  easyprivacy: 32231-134, 2d.5h.17m
  plowe-0: 3742-939, 7d.6h.52m
  ublock-abuse: 70-0, 1d.20h.20m
  ublock-badware: 7107-128, 6h.28m
  ublock-filters: 33366-480, 4d.16h.51m
  ublock-privacy: 394-74, 1d.20h.19m
  ublock-quick-fixes: 245-6, 8h.29m
  ublock-unbreak: 2014-38, 19m
  urlhaus-1: 6820-1, 8h.30m
filterset (user): [empty]
trustedset: 
 added: [array of 11 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2326 ms (selfie)
 maxAssetCacheWait: 216 ms
popupPanel: 
 blocked: 2
 network: 
  googlesyndication.com: 2
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce.

I can reproduce as soon as I enable Adblock Plus. Please tell me you took these steps seriously:

>  - [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.
> - [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
