### ISSUE TITLE
vipsearch.top: possible malicious download/search engine

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18024]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

For starters:
https://www.pcrisk.com/removal-guides/20394-vipsearch-pro-browser-hijacker
https://www.virustotal.com/gui/url/d4801ddf419c22d251482ba0f2a98440741a3b14b80a91db32a9043576ada7d0 (Flagged as "suspicious" from one source)
https://malwaretips.com/blogs/remove-vipsearch-guru/

Seems to be another fake search engine which tricks you into downloading its extension. (And probably redirects you to it's own search engine, judging from the GIF's shown on the linked articles)

### URL(s) where the issue occurs.

`http://vipsearch.top/`
`https://vipsearch.guru/v2/index.php?q=`

### uBO version

uBlock Origin v1.49.3b9

### Browser name and version

Firefox 112.0.2

### Settings

- Checked "I am an advanced user", using custom filters

**Comment by gorhill** [comment]
> tricks you into downloading its extension

There is no trick, the page describes that the extension can be installed from the Chrome Web Store. If you think it should not be in the Chrome Web Store, report it to them.
