### ISSUE TITLE
jpopsingles.eu [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1802]
URL(s) where the issue occurs

`https://jpopsingles.eu/single-monari-wakita-take-it-lucky/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by yuukiAme** [comment]
Now they added a blurry to the website as a whole. Can't really catch it with Ublock filter for some reasons.

**Comment by yuukiAme** [comment]
did you get pass the blurry filter?

**Comment by Yuki2718** [comment]
I don't get blur at all with default setting on Firefox.

**Comment by yuukiAme** [comment]
jpopsingles.eu detected my firefox default settings and ublock origin which is why I get the blur effect because their script detected adblock. 

Try having the adblocker on see if the blur effect is there.
