### ISSUE TITLE
small-games.info: breakage

### ISSUE THREAD

**Issue by Setoko** [uBlockOrigin/uAssets#18021]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://small-games.info/?go=game&c=13&i=27048`

### Category

breakage

### Description

white page with active uBlock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 110
filterset (summary): 
 network: 110677
 cosmetic: 61598
 scriptlet: 18802
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 17-2, never
  RUS-0: 39724-11, 1d.10h.41m
  easylist: 67151-67, 1d.14h.42m
  easyprivacy: 32231-152, 3d.11h.45m
  plowe-0: 3741-941, 9d.14h.4m
  ublock-abuse: 70-1, 12d.14h.8m
  ublock-badware: 7111-129, 5d.10h.26m
  ublock-filters: 33366-132, 5d.10h.25m
  ublock-privacy: 323-4, 12d.14h.7m
  ublock-quick-fixes: 245-6, 1d.2h.40m
  ublock-unbreak: 2007-36, 5d.10h.24m
  urlhaus-1: 6768-1, 1d.14h.42m
filterset (user): [array of 17 redacted]
trustedset: 
 added: [array of 8 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4209 ms (selfie)
 maxAssetCacheWait: 745 ms
popupPanel: 
 blocked: 8
 network: 
  admitad.com: 1
  google-analytics.com: 1
  mail.ru: 2
  mp3bars.com: 1
  stvkr.com: 1
  yadro.ru: 1
  yandex.ru: 1
 cosmetic: 
  ##:not(this-site-promotes-malware)
  ###system_msg
  ###system_msg
```
</details>

**Comment by mapx-** [comment]
**this-site-promotes-malware**

duplicate

https://github.com/uBlockOrigin/uAssets/issues/17749#issuecomment-1519130549

**Comment by dimisa-RUAdList** [comment]
The solution to the problem is expected within 2 days.
https://github.com/easylist/ruadlist/issues/167
https://forums.lanik.us/viewtopic.php?t=48087-small-games-info
