### ISSUE TITLE
youtube.com: nuisance

### ISSUE THREAD

**Issue by maxtraxv3** [uBlockOrigin/uAssets#18025]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=lxRwEPvL-mQ&list=RDLHCob76kigA&index=3`

### Category

nuisance

### Description

deteck ad block and this poopup on every video.

i tryed the element picker, but now it just pause every video and can longer scroll down, even on play lists.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/12743527/4149a806-f9f9-4d80-a46a-4c28a6f72564)

https://ibb.co/1Ttw09k
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93472
 cosmetic: 40475
 scriptlet: 17398
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 3-0, never
  easylist: 67081-46, 2d.18h.57m
  easyprivacy: 32236-46, 4d.20h.16m
  plowe-0: 3742-936, 43m
  ublock-abuse: 70-0, 2d.18h.59m
  ublock-badware: 7095-128, 1d.19h.46m
  ublock-filters: 33071-87, 20h.42m
  ublock-privacy: 394-74, 2d.18h.58m
  ublock-quick-fixes: 216-11, 10h.53m
  ublock-unbreak: 2015-36, 2d.18h.56m
  urlhaus-1: 6939-1, 42m
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 17 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 239 ms (selfie)
 maxAssetCacheWait: 68 ms
popupPanel: 
 blocked: 120
 network: 
  youtube.com: 80
  doubleclick.net: 4
  google.com: 25
  google.com.au: 1
  googlevideo.com: 2
  sentry.io: 7
  ytimg.com: 1
 cosmetic: 
  ###player-ads
  ##tp-yt-paper-dialog.ytd-popup-container.style-scope
  ##.opened
  ###masthead-ad
  ###merch-shelf
  ##.ytd-in-feed-ad-layout-renderer
  ##.ytp-ad-progress-list
  ##[layout*=\"display-ad-\"]
  ##ytd-ad-slot-renderer
  ##ytd-display-ad-renderer
  ##ytd-rich-item-renderer.style-scope.ytd-rich-grid-row:has(ytd-display-ad-renderer)
  ##a[href^=\"https://www.googleadservices.com/pagead/aclk?\"]
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
```
</details>

**Comment by Xenoamor** [comment]
Can't replicate this on my end, hopefully someone else here can. They must only be rolling it out to a few users

**Comment by stephenhawk8054** [comment]
Please comment in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by maxtraxv3** [comment]
> 

not the same issue, please check pic, and read the description.

**Comment by stephenhawk8054** [comment]
That thread's title is `ALL youtube.com issues`

**Comment by Daxy7** [comment]
> not the same issue, please check pic, and read the description.

What does the block element tool show when right clicking on the empty part of the nag box?
Send a screenshot
