### ISSUE TITLE
techhelpbd.com: detection

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#18035]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://techhelpbd.com/en/nordvpn/`

### Category

detection

### Description

You need to wait 30 sec at least to trigger detection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94176
 cosmetic: 38815
 scriptlet: 17436
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65531-46, 11m
  easyprivacy: 32255-45, 11m
  plowe-0: 3742-937, 11m
  ublock-abuse: 70-0, 11m
  ublock-badware: 7120-128, 11m
  ublock-filters: 33139-95, 11m
  ublock-privacy: 394-74, 11m
  ublock-quick-fixes: 244-12, 11m
  ublock-unbreak: 2012-40, 11m
  urlhaus-1: 7449-1, 11m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 17242 ms
 maxAssetCacheWait: 217 ms
popupPanel: 
 blocked: 4
 network: 
  google.com: 2
  googlesyndication.com: 1
  www.googleapis.com: 1
 cosmetic: 
  ##ins.adsbygoogle
  ##.stream-item-widget
  ##.THBD-Ads
```
</details>

**Comment by huyszn** [comment]
The site displays detection alert after waiting 8 seconds on a page
