### ISSUE TITLE
dgdrive.xyz / dropgalaxy.com: detection

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#18036]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] #18172

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

After timer expires, the UbO is detected. 

### URL(s) where the issue occurs.

`https://dgdrive.xyz/y70zhbufjd6q`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/80951522/759b8a96-030f-475a-bf9f-2d5075c44684)

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Chrom 104.xx

### Settings

All defaults

### Notes

Updated the filters but doesn't work.

**Comment by dgowner** [comment]
> @dgowner Nehi Hora Kya..Aja Ping Pong Khelle [Screenshot_20230515-072538_Ortus Launcher](https://github.com/uBlockOrigin/uAssets/assets/112684643/3f3c258b-6b57-40cc-b3b8-25049739cf90)
bngali bund ko gandu no1 banana bahot asaan hai example ss me dekhle tati k bache-
![Screenshot 2023-05-15 at 07-29-06 DropGalaxy - Free file upload service](https://github.com/uBlockOrigin/uAssets/assets/103483912/94bbe0e8-55db-4076-b439-cb311540cd40)

**Comment by dgowner** [comment]
> 

daily itne adblock kaise detect hore yaha bngali bund ki jalgyi :-) dekhta ja abhi or detect honge. or muje test krne ki jarurat nhi countrywise set hai :-)

**Comment by dgowner** [comment]
@iSmokeMid69 
![bngali bund](https://github.com/uBlockOrigin/uAssets/assets/103483912/a43949db-2704-4bb6-8dfd-56db35830309)

**Comment by ghajini** [comment]
@iSmokeMid69 you are spamming here, using bad words
stop it commenting here 
this is not your personal forum or chat forum
it will result in banning here
