### ISSUE TITLE
gktech.uk: detection

### ISSUE THREAD

**Issue by deadboy18** [uBlockOrigin/uAssets#18030]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gktech.uk/`

### Category

detection

### Description

detects adblock and greys the page out

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/53135082/8f1a483d-8f60-4bb5-b3e7-dccc76d7a133)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 272633
 cosmetic: 226060
 scriptlet: 56469
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 43560-3861, 3d.8h.5m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7250-0, 1d.8h.2m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24156-12, 5h.57m
  https://winhelp2002.mvps.org/hosts.txt: 8729-332, 3d.8h.5m
  IDN-0: 5500-10, 3d.8h.5m
  adguard-annoyance: 67946-319, 3d.8h.5m
  adguard-generic: 70555-2216, 3d.8h.5m
  adguard-mobile: 8730-103, 3d.8h.4m
  adguard-social: 20432-871, 3d.8h.5m
  adguard-spyware-url: 1010-3, 3d.8h.4m
  block-lan: 47-0, 16d.7h.59m
  curben-phishing: 91250-3, 5h.58m
  curben-pup: 199-0, 5h.59m
  dpollock-0: 11357-1468, 3d.6h.2m
  fanboy-annoyance: 90831-21391, 3d.8h.5m
  fanboy-cookiemonster: 47019-47019, 3d.6h.1m
  fanboy-social: 17213-17213, 3d.8h.4m
  fanboy-thirdparty_social: 68-18, 3d.8h.5m
  ublock-annoyances: 4975-287, 2d.7h.59m
 default: 
  user-filters: 6-0, never
  easylist: 66957-1330, 3d.6h
  easyprivacy: 32233-13691, 3d.5h.59m
  plowe-0: 3743-1590, 3d.6h.3m
  ublock-abuse: 70-1, 9d.8h.2m
  ublock-badware: 7095-384, 3d.8h.5m
  ublock-filters: 33243-6378, 3d.8h.5m
  ublock-privacy: 393-139, 9d.8h.2m
  ublock-quick-fixes: 251-12, 8h
  ublock-unbreak: 2010-137, 3d.8h.4m
  urlhaus-1: 7449-4, 6h
filterset (user): [array of 6 redacted]
trustedset: 
 added: [array of 29 redacted]
 removed: 
  about-scheme
  chrome-extension-scheme
  chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1972 ms (selfie)
 maxAssetCacheWait: 1351 ms
popupPanel: 
 blocked: 3
 network: 
  gktech.uk: 1
  doubleclick.net: 1
  googletagmanager.com: 1
 cosmetic: 
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ###cookie-law-info-bar
  ###cookie-law-info-bar ~ .cli-modal-backdrop
  ###cookie-law-info-again
  ###cookie_hdr_showagain
  ###cliSettingsPopup
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by JobcenterTycoon** [comment]
Please give us the shortened link you used to get to this site. I can’t reproduce when i open the site directly.
