### ISSUE TITLE
web.snapchat.com: breakage

### ISSUE THREAD

**Issue by Teddybear123455287598347298** [uBlockOrigin/uAssets#18049]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://web.snapchat.com/`

### Category

popups

### Description

Its blocked and won't let me in!!!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 94413
 cosmetic: 38805
 scriptlet: 17416
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  easylist: 65584-46, 1h.33m
  easyprivacy: 32263-46, 1h.33m
  plowe-0: 3742-937, 8d.14h.26m
  ublock-abuse: 70-0, 1h.33m
  ublock-badware: 7120-128, 1h.33m
  ublock-filters: 33099-95, 1h.33m
  ublock-privacy: 394-74, 1h.33m
  ublock-quick-fixes: 250-15, 1h.33m
  ublock-unbreak: 2014-45, 1h.33m
  urlhaus-1: 7635-1, 1h.33m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  about-scheme
switchRuleset: 
 added: [array of 14 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
 colorBlindFriendly: true
 largeMediaSize: 0
 tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 250 ms (selfie)
 maxAssetCacheWait: 109 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
> blocked: 0

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
