### ISSUE TITLE
posturi.live: detection

### ISSUE THREAD

**Issue by claudiu64** [uBlockOrigin/uAssets#18042]
### Prerequisites

- [ ] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On this site, with the extension enabled, the video detects the Ublock Origin extension.

### URL(s) where the issue occurs.

`https://posturi.live/tv/film-now/1/`

### Screenshot(s)

![Screenshot_20230512-014636_Firefox Nightly](https://github.com/uBlockOrigin/uAssets/assets/114283947/508739ce-c96e-4dff-b17b-80dc4334fc85)

### uBO version

1.49.2

### Browser name and version

Firefox browser 113

### Settings

No change, new profile.

**Comment by grassfedtallow** [comment]
@mapx- road-block?
