### ISSUE TITLE
mrchadd.nl: nuisance

### ISSUE THREAD

**Issue by Snowpop** [uBlockOrigin/uAssets#18041]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mrchadd.nl/academy/vakken/wiskunde/wat-zijn-asymptoten`

### Category

nuisance

### Description

When scrolling through articles on the website, it shows a big popup advertising it's own subscription.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[Screenshot](https://github.com/uBlockOrigin/uAssets/assets/88103045/dfd9b117-cf60-425a-847e-27b75a57486a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93957
 cosmetic: 40441
 scriptlet: 17480
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66942-46, 4d.12h.35m
  easyprivacy: 32226-46, 4d.12h.34m
  plowe-0: 3743-936, 6d.5h.4m
  ublock-abuse: 70-0, 6d.5h.3m
  ublock-badware: 7111-129, 5d.6h.29m
  ublock-filters: 33231-81, 5d.6h.28m
  ublock-privacy: 394-74, 6d.5h.2m
  ublock-quick-fixes: 251-10, 10h.22m
  ublock-unbreak: 2007-36, 5d.6h.27m
  urlhaus-1: 7449-1, 10h.23m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-extension-scheme
modifiedUserSettings: 
 cloudStorageEnabled: true
 collapseBlocked: false
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 6250 ms (selfie)
 maxAssetCacheWait: 2357 ms
popupPanel: 
 blocked: 7
 network: 
  facebook.net: 1
  google.com: 3
  googletagmanager.com: 2
  youtube.com: 1
```
</details>

**Comment by Snowpop** [comment]
Can also repro using the `NLD: Easydutch` list.

**Comment by okiehsch** [comment]
Add
````
mrchadd.nl##.c-modal__backdrop
mrchadd.nl##.c-modal
````
to your filter lists.

We don't block self advertisement in our lists.

**Comment by JohnyP36** [comment]
> We don't block self advertisement in our lists.

As one of the maintainers of `NLD: Easydutch` list we indeed don't block self advertisements.
