### ISSUE TITLE
app.neilpatel.com site broken

### ISSUE THREAD

**Issue by aswinbennyofficial** [uBlockOrigin/uAssets#18048]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

app.neilpatel.com is detecting ublock orgin and blocking the loading of content.  While opening the website the following loader screen appears and doesnt change.

### URL(s) where the issue occurs.

`https://app.neilpatel.com`
`https://app.neilpatel.com/en/dashboard`
`https://app.neilpatel.com/en/position_tracking/recent`
`https://app.neilpatel.com/en/seo_analyzer/site_audit`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/110408942/699957df-b23a-4de8-8a34-2d2d6b031707)
![image](https://github.com/uBlockOrigin/uAssets/assets/110408942/94bed224-a157-4fbf-b642-a5cbe9775f06)

### uBO version

1.49.2

### Browser name and version

Firefox 113.0

### Settings

- no changes made

**Comment by JobcenterTycoon** [comment]
The anti adblock got fixed in the annoyance list.

**Comment by stephenhawk8054** [comment]
Does `neilpatel.com##+js(no-xhr-if, ip-api)` work?
