### ISSUE TITLE
onlinetools.com: ads

### ISSUE THREAD

**Issue by Anonymous-cat1** [uBlockOrigin/uAssets#18040]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://onlinetools.com/unicode/spoof-unicode-text`

### Category

ads

### Description

A prompt to buy premium will show up when clicking the "copy text to clipboard" button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/105524203/e79b25cd-4ae0-4f8c-8c73-79360222ef82)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93582
 cosmetic: 40553
 scriptlet: 17428
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, never
 default: 
  user-filters: 0-0, never
  easylist: 67244-46, never
  easyprivacy: 32233-45, never
  plowe-0: 3742-936, never
  ublock-abuse: 70-0, never
  ublock-badware: 7132-129, never
  ublock-filters: 33105-93, never
  ublock-privacy: 394-74, never
  ublock-quick-fixes: 252-11, never
  ublock-unbreak: 2010-36, never
  urlhaus-1: 6939-1, never
filterset (user): [empty]
trustedset: 
 added: [array of 21 redacted]
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1140 ms (selfie)
 maxAssetCacheWait: 529 ms
popupPanel: 
 blocked: 3
 network: 
  googletagmanager.com: 1
  statcounter.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
It looks like paywall than ads?

**Comment by mapx-** [comment]
yes

**Comment by Daxy7** [comment]
timer is still 10 seconds `##+js(nano-sib, downloadTimer)` invalid
group domains
```
https://onlinegiftools.com/play-gif
https://onlinejpgtools.com/jpg-color-picker
https://onlinepngtools.com/create-transparent-png
https://onlinestringtools.com/url-encode-string
https://onlinetexttools.com/split-text
https://onlinetools.com/ascii/convert-ascii-to-binary
```
fixed filters
```
onlinegiftools.com,onlinejpgtools.com,onlinepngtools.com,onlinestringtools.com,onlinetexttools.com,onlinetools.com##+js(nano-sib)
```

**Comment by pkrumins** [comment]
Peter here - creator of Online Tools. Just wanted to let you know this change breaks many of the tools that use setTimeout internally. Can you please limit this to just the ads dialogs? Thanks!
