### ISSUE TITLE
instagram.com: ads

### ISSUE THREAD

**Issue by YoshiasHZ** [uBlockOrigin/uAssets#18058]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [ ] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.instagram.com/`

### Category

ads

### Description

> Uns dois dias mais ou menos, o site instagram passou a exibir anúncios novamente, alguns locais e outros anúncios internacionais.

**A couple of days or so, the instagram site started showing ads again, some local and other international ads.**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ADS](https://github.com/uBlockOrigin/uAssets/assets/133400678/66becfe4-bba1-4db4-a489-48a36105bb0a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95697
 cosmetic: 42210
 scriptlet: 17709
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65530-46, 19h.19m
  easyprivacy: 32240-45, 3d.3h.16m
  plowe-0: 3743-937, 5d.18h.7m
  spa-1: 5213-69, 23h.20m
  ublock-abuse: 70-0, 7d.22h.38m
  ublock-badware: 7095-128, 3d.3h.15m
  ublock-filters: 33074-121, 1d.22h.32m
  ublock-privacy: 394-74, 7d.22h.37m
  ublock-quick-fixes: 261-12, 1h.46m
  ublock-unbreak: 2015-37, 3d.3h.14m
  urlhaus-1: 7605-1, 11m
filterset (user): [empty]
trustedset: 
 added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 364 ms (selfie)
 maxAssetCacheWait: 128 ms
popupPanel: 
 blocked: 28
 network: 
  instagram.com: 25
  facebook.com: 3
```
</details>

**Comment by peace2000** [comment]
Please update your filter lists and that should ad should go away.
