### ISSUE TITLE
flightsim.to: detection

### ISSUE THREAD

**Issue by GrantCrackers18** [uBlockOrigin/uAssets#18053]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://flightsim.to/file/29066/eddf-frankfurt-main-international-beta-experimental`

### Category

detection

### Description

Won't let you download files because it detects ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/28992240/011b3c63-f437-4b62-a9a8-3ba18059f984)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94163
 cosmetic: 40493
 scriptlet: 17420
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 67082-46, 3d.14h.8m
  easyprivacy: 32226-46, 4d.21h.9m
  plowe-0: 3743-936, 4d.21h.9m
  ublock-abuse: 70-0, 6d.22h.56m
  ublock-badware: 7120-128, 20h.9m
  ublock-filters: 33092-88, 20h.10m
  ublock-privacy: 394-74, 6d.22h.55m
  ublock-quick-fixes: 252-12, 8m
  ublock-unbreak: 2012-36, 18h.7m
  urlhaus-1: 7605-1, 9m
filterset (user): [empty]
trustedset: 
 added: [array of 3 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 364 ms (selfie)
 maxAssetCacheWait: 82 ms
popupPanel: 
 blocked: 40
 network: 
  cloudflareinsights.com: 2
  doubleclick.net: 4
  google.com: 2
  googletagmanager.com: 1
  primis.tech: 1
  pub.network: 3
  quantserve.com: 1
  sharethis.com: 3
  youtube.com: 23
 cosmetic: 
  ##.sidebar-ad:not(div.adsbygoogle)
  ##[data-freestar-ad]
  ##.ytp-ad-progress-list
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
  ##.ytp-ad-progress-list
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
```
</details>

**Comment by Archer374** [comment]
Confirmed. Only happens with uploads that are newer than May 10th.

**Comment by mapx-** [comment]
provide such an example

**Comment by Archer374** [comment]
https://flightsim.to/file/33166/animated-humans-library

![grafik](https://github.com/uBlockOrigin/uAssets/assets/128901668/38ba6e4e-a4d8-4665-855b-cfb2423afbea)

**Comment by stephenhawk8054** [comment]
I still can't see any anti-adblock, and I can download normally. Video recording: https://github.com/uBlockOrigin/uAssets/assets/66517106/9b9c0b8b-6974-4ca3-8f33-0e59bc492f7d

**Comment by Archer374** [comment]
Very strange. Had this behaviour for about two days including today. Tried with and without VPN and I only have this one adblocker installed and the behaviour was totally consistent.

Ever since you posted your video it again works without a hitch. 
Well thanks ... you seem to have inadvertendly solved it 😂

**Comment by mapx-** [comment]
yeah, all fine on my end too

**Comment by nosar77** [comment]
I'm reopening , this issue persists on latest Brave. I tried disabling built I'm brave shield and still doesn't work. Please reopen

**Comment by mapx-** [comment]
- working fine in brave too

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Archer374** [comment]
I'm also still having problems with this site. Especially when NOT using a VPN. With a VPN it usually works well

**Comment by mapx-** [comment]
@Archer374 follow all the indications above

**Comment by GrantCrackers18** [comment]
I've ran through those steps above and I'm now getting the adblock popup again. It comes and goes randomly...

**Comment by Archer374** [comment]
Same here.

**Comment by okiehsch** [comment]
I can reproduce, does adding
`@@||pub.network/flightsim-to/pubfig.min.js$script,xhr,domain=flightsim.to`
work on your end?

**Comment by GrantCrackers18** [comment]
That does work for me - we shall see for how long lol

**Comment by nosar77** [comment]
> 

This works for me as well!

**Comment by Archer374** [comment]
> @@||pub.network/flightsim-to/pubfig.min.js$script,xhr,domain=flightsim.to

where do I have to add that?

**Comment by Tinh1000000** [comment]
I have only seen the anti-adblock attempt to activate when downloading files that exceed a file size threshold (e.g. >150 MB). Otherwise, for users' convenience, it will not activate on small files.

I also recommend adding `@@||pub.network^$xhr,domain=flightsim.to` if you have enabled **Peter Lowe’s Ad and tracking server list** and **EasyList** as those two lists still break the site without the exception.

**Comment by stephenhawk8054** [comment]
@Tinh1000000 Can you test if this filter works?

```adb
flightsim.to##+js(no-xhr-if, pub.network)
```

**Comment by Tinh1000000** [comment]
> @Tinh1000000 Can you test if this filter works?
> 
> ```
> flightsim.to##+js(no-xhr-if, pub.network)
> ```

The filter you gave works for me!
