### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Ningthem-Singh** [uBlockOrigin/uAssets#18057]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=85GsizmZ6pA`

### Category

ads

### Description

Poco f5 ad pops up in incognito mode
![poco f5](https://github.com/uBlockOrigin/uAssets/assets/107441727/bc96f553-1527-42c8-9882-a5bec933aca9)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94274
 cosmetic: 40542
 scriptlet: 17391
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 3-0, never
  easylist: 67207-46, 2d.4h.16m
  easyprivacy: 32226-45, 4d.9h.58m
  plowe-0: 3742-936, 3d.11h.4m
  ublock-abuse: 70-0, 3d.9h.2m
  ublock-badware: 7118-128, 2d.12h.36m
  ublock-filters: 33070-91, 2d.12h.35m
  ublock-privacy: 394-74, 7d.23h.14m
  ublock-quick-fixes: 250-11, 7h.14m
  ublock-unbreak: 2012-36, 2d.12h.34m
  urlhaus-1: 7635-1, 9h.15m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 270 ms (selfie)
 maxAssetCacheWait: 144 ms
popupPanel: 
 blocked: 45
 network: 
  youtube.com: 35
  doubleclick.net: 2
  google.co.in: 1
  google.com: 3
  googlesyndication.com: 1
  googlevideo.com: 2
  ytimg.com: 1
 cosmetic: 
  ###player-ads
  ###merch-shelf
  ##.ytd-companion-slot-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##ytd-companion-slot-renderer
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
