### ISSUE TITLE
satkurier.pl: detection

### ISSUE THREAD

**Issue by janekiwan** [uBlockOrigin/uAssets#18051]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://satkurier.pl/`

### Category

detection

### Description

popup with detection, text cutted with info to not block ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="625" alt="satkurier2" src="https://github.com/uBlockOrigin/uAssets/assets/133378584/49ce59fb-e97b-4587-98fa-53e316db2880">

<img width="809" alt="satkurier" src="https://github.com/uBlockOrigin/uAssets/assets/133378584/9c7b034f-ff24-432f-8fa5-fe035aa208ea">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95722
 cosmetic: 48077
 scriptlet: 17642
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  POL-0: 7943-11, 17h.57m
  POL-2: 1275-13, 2d.1h.21m
  easylist: 67244-73, 2d.1h.25m
  easyprivacy: 32253-45, 2d.1h.24m
  plowe-0: 3741-944, 13d.14m
  ublock-abuse: 70-0, 13d.14m
  ublock-badware: 7112-128, 2d.1h.22m
  ublock-filters: 33127-132, 1d.17h.38m
  ublock-privacy: 323-4, 13d.14m
  ublock-quick-fixes: 252-12, 1h.39m
  ublock-unbreak: 2012-44, 2d.1h.23m
  urlhaus-1: 7651-1, 17h.57m
filterset (user): [empty]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 447 ms (selfie)
 maxAssetCacheWait: 141 ms
popupPanel: 
 blocked: 18
 network: 
  satkurier.pl: 6
  doubleclick.net: 1
  gemius.pl: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  idmnet.pl: 3
  spolecznosci.net: 1
  twitter.com: 1
  vidoomy.com: 1
 cosmetic: 
  ###SATKurierNews_top_750x100_r
  ##[id^=\"idmnet_\"]
  ##[id^=\"pasek_hollex\"]
  ###side_bottom_m
  ##[id^=\"banner_\"]
  ##[id^=\"google\"]
  ###sky_left_container,.wmeri-widget.widget
  ##[id^=\"banner_900x\"]
  ##[id^=\"aswift_\"]
  ##ins.adsbygoogle
```
</details>

**Comment by krystian3w** [comment]
Looks back or sticky: https://github.com/MajkiIT/polish-ads-filter/issues/23311#issuecomment-4604296130 / https://github.com/MajkiIT/polish-ads-filter/issues/23311#issuecomment-4633236284

**Comment by playonevideo** [comment]
Detection, again.

**Comment by krystian3w** [comment]
However, it does not guarantee that 4 days ago someone edited the uAssets filters for this website or even MajkiIT.

If the webmaster is rude, they may even block fan-made ideas for fixing the problem, so that they would have to be sent in private/direct messages (aka PM/DM) outside of GitHub (Because probably no one will create a private GitHub group for the solution to work for more than 24 hours).
