### ISSUE TITLE
pnc.com: breakage

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#18050]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On the first link, where it asks `Do you have a PNC Online Banking User ID?` selecting either radio option does not trigger the next action flow.
On the second link, page does not load.

### URL(s) where the issue occurs.

`https://www.pnc.com/en/apps/appointment-setting/schedule-appointment.html`
`https://apps.pnc.com/locator/search`

### uBO version

1.49.2

### Browser name and version

Chrome 113

### Settings

N/A

### Notes

First link: `@@||assets.adobedtm.com^$script,domain=pnc.com`
Second link: `@@||mboxedge34.tt.omtrdc.net/m2/pncnationalbank/mbox/json$xhr,domain=apps.pnc.com`

**Comment by mapx-** [comment]
@ryanbr
