### ISSUE TITLE
delfi.ee: nuisance

### ISSUE THREAD

**Issue by kennu290** [uBlockOrigin/uAssets#18067]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.delfi.ee/`

### Category

nuisance

### Description

an anti adblock popup is there

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/73755588/fb0e1933-abe7-4d25-80f5-82824dc5210c

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93770
 cosmetic: 40505
 scriptlet: 17451
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 67082-46, 4d.20h.6m
  easyprivacy: 32258-46, 10h.10m
  plowe-0: 3742-936, 10d.21h.58m
  ublock-abuse: 70-0, 3d.21h.44m
  ublock-badware: 7120-128, 19h.25m
  ublock-filters: 33132-88, 19h.24m
  ublock-privacy: 394-74, 3d.21h.43m
  ublock-quick-fixes: 265-15, 6h.8m
  ublock-unbreak: 2013-38, 19h.23m
  urlhaus-1: 7175-1, 6h.9m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 691 ms (selfie)
 maxAssetCacheWait: 114 ms
popupPanel: 
 blocked: 41
 network: 
  adform.net: 2
  adnet.lt: 14
  adnetmedia.lt: 14
  clarity.ms: 1
  cxense.com: 3
  delfi.net: 1
  facebook.net: 1
  gemius.pl: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  onesignal.com: 1
```
</details>

**Comment by mapx-** [comment]
Enable the regional list
`EST: Eesti saitidele kohandatud filter`
