### ISSUE TITLE
proddigital.com.br: ads

### ISSUE THREAD

**Issue by jo5d** [uBlockOrigin/uAssets#18064]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://proddigital.com.br/`

### Category

ads

### Description

Show an ad at the end of the page after clicking on a article.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 229208
 cosmetic: 218645
 scriptlet: 39649
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 68119-91, 20m
  adguard-generic: 70636-461, 20m
  adguard-social: 20450-868, 20m
  adguard-spyware-url: 1026-3, 20m
  block-lan: 47-0, 20m
  curben-phishing: 93462-2, 20m
  curben-pup: 199-0, 20m
  dpollock-0: 11357-29, 20m
  fanboy-annoyance: 90878-21382, 20m
  fanboy-cookiemonster: 47104-47104, 20m
  fanboy-social: 17064-17064, 20m
  fanboy-thirdparty_social: 68-18, 20m
  spa-1: 5213-80, 20m
  ublock-annoyances: 4979-268, 20m
 default: 
  user-filters: 7-1, never
  easylist: 65639-1072, 20m
  easyprivacy: 32263-332, 20m
  plowe-0: 3737-1324, 20m
  ublock-abuse: 70-0, 20m
  ublock-badware: 7120-381, 20m
  ublock-filters: 33135-4128, 20m
  ublock-privacy: 394-78, 20m
  ublock-quick-fixes: 265-21, 20m
  ublock-unbreak: 2013-99, 20m
  urlhaus-1: 7394-4, 20m
filterset (user): [array of 7 redacted]
trustedset: 
 added: [array of 1 redacted]
switchRuleset: 
 added: [array of 1 redacted]
hostRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 947 ms (selfie)
 maxAssetCacheWait: 551 ms
popupPanel: 
 blocked: 8
 network: 
  proddigital.com.br: 2
  facebook.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
  stats.wpmucdn.com: 1
 cosmetic: 
  ###fb-root:not(body):not(html)
  ##.td-scroll-up
  ##.td-a-rec
  ##ins.adsbygoogle
  ##.td-post-sharing-top
  ##.td-post-sharing
  ##.td-social-sharing-button
  ##.td-icon-facebook
  ##.td-icon-twitter
  ##.td-post-sharing-bottom
  ##.wc_social_plugin_wrapper
  ##.wpd-sbs-title
  ##.wpdiscuz-subscribe-bar
  ##.dialog-lightbox-message.dialog-message
  ##a[href^=\"https://twitter.com/intent/tweet?\"]
  ##a[href^=\"https://pinterest.com/pin/create/\"]
  ##a[href^=\"https://api.whatsapp.com/send?text=\"]
  ##a[href^=\"https://telegram.me/share/url?\"]
  ##a[href*=\"pinterest.com/pin/create/button\"]
  ##a[href^=\"https://www.tumblr.com/share\"]
  ##a[href^=\"https://www.facebook.com/sharer.php\"]
  ##a[href^=\"https://www.linkedin.com/shareArticle\"]
  ##a[href^=\"https://www.facebook.com/sharer.php?\"]
  ##a[href^=\"https://www.linkedin.com/shareArticle?\"]
```
</details>

**Comment by mapx-** [comment]
add

`proddigital.com.br##.gofollow`

report here:
https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by Alex-302** [comment]
@jo5d Fixed.
