### ISSUE TITLE
app.neilpatel.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18065]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.neilpatel.com/en/ubersuggest/overview?lang=en&locId=2840&keyword=raw+crackers`

### Category

detection

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/a3a72eca-388d-49c7-8361-f6ab395f07f2)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 115
filterset (summary): 
 network: 102679
 cosmetic: 90371
 scriptlet: 23748
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@main/dist/adblockid.adfl.txt: 8521-5, 23h.34m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@main/dist/adblockid_plus.adfl.txt: 925-4, 2d.3h.6m
  IDN-0: 5500-368, 2d.3h.6m
  fanboy-cookiemonster: 47051-226, 2d.3h.6m
  ublock-annoyances: 4975-55, 2d.3h.6m
 default: 
  user-filters: 43-0, never
  easylist: 65531-57, 2d.3h.6m
  easyprivacy: 32255-47, 2d.3h.6m
  plowe-0: 3742-937, 2d.3h.6m
  ublock-abuse: 70-0, 2d.3h.6m
  ublock-badware: 7120-130, 2d.3h.6m
  ublock-filters: 33134-248, 2d.3h.6m
  ublock-privacy: 394-74, 2d.3h.6m
  ublock-quick-fixes: 250-12, 11h.37m
  ublock-unbreak: 2012-42, 2d.3h.6m
  urlhaus-1: 7635-1, 1d.1h.35m
filterset (user): [array of 43 redacted]
trustedset: 
 added: [array of 43 redacted]
 removed: 
  chrome-extension-scheme
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 5080 ms (selfie)
 maxAssetCacheWait: 540 ms
popupPanel: 
 blocked: 8
 network: 
  amplitude.com: 1
  googletagmanager.com: 2
  hotjar.com: 2
  ip-api.com: 1
  kissmetrics.io: 2
 cosmetic: 
  ##.grecaptcha-badge
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

Please do what you ticked on.

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/commit/919c8e4f03cec0a41aeaa146e80b109e2dcdd279

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3d706470c24cfd79c92b7b9d774dd6be8e46fc78
