### ISSUE TITLE
Errors In Filter Lists

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#18062]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The following Filter Lists have errors when you open them up in uBlock Origin:
AdGuard – Ads (22 errors)
EasyList - (8 errors)
Phishing URL Blocklist (1 error)
AdGuard – Annoyances (6 errors)
AdGuard Tracking Protection filter (5 errors)

I have purged all caches and got the latest updates before posting the issue.
If the errors can be detected, can't they be removed?

Thanks all.

### URL(s) where the issue occurs.

N/A

### Screenshot(s)

N/A

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Google Chrome 113.0.5672.64 (x64)

### Settings

N/A

### Notes

N/A

**Comment by TesterMan247** [comment]
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 316094
 cosmetic: 215441
 scriptlet: 39930
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  urlhaus-1: null
 added: 
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 40533-127, 21m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 72733-0, 21m
  adguard-annoyance: 68120-252, 21m
  adguard-generic: 70636-1305, 21m
  adguard-social: 20450-870, 21m
  block-lan: 47-0, 21m
  curben-phishing: 92583-20, 21m
  curben-pup: 199-0, 21m
  dpollock-0: 11357-192, 21m
  fanboy-annoyance: 90856-21393, 21m
  fanboy-thirdparty_social: 68-18, 21m
  ublock-annoyances: 4979-268, 21m
 default: 
  user-filters: 10-0, never
  easylist: 65608-1112, 21m
  easyprivacy: 32261-13631, 21m
  plowe-0: 3737-1384, 21m
  ublock-abuse: 70-0, 21m
  ublock-badware: 7120-382, 21m
  ublock-filters: 33130-4130, 21m
  ublock-privacy: 394-137, 21m
  ublock-quick-fixes: 267-22, 21m
  ublock-unbreak: 2013-137, 21m
filterset (user): [array of 10 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1032 ms (selfie)
 maxAssetCacheWait: 522 ms

**Comment by mapx-** [comment]
- implemented in other ways
$webrtc => nowebrtc.js

not supported (uBO has its own weapons)
-abp-properties

plain js
`giga.de#@%#(function(o){function a(a){return{get:function(){return a},set:b}}function b(){}function c(){throw ....`

etc etc
