### ISSUE TITLE
pornshare.org [Anti-Adblock] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1806]
URL(s) where the issue occurs

`http://pornshare.org/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by WowDude** [comment]
Enabling `Adguard Base Filters` fixes the Anti-Adblock.
