### ISSUE TITLE
lightnovelpub.com: detection

### ISSUE THREAD

**Issue by SpenceSal** [uBlockOrigin/uAssets#18060]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lightnovelpub.com/novel/sword-god-in-a-world-of-magic-1377/chapter-283`

### Category

detection

### Description

Red box saying to turn off ad blocker will appear while cutting off the rest of the webpage, i cleared cashes and updated filters, this worked for a few hours then it appeared again. Was not an issue yesterday.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/100597498/ba1d0064-c509-4f3a-a2df-e3eda4389ba3)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94380
 cosmetic: 38838
 scriptlet: 17438
 html: 945
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34006-57, 2h.17m
  ublock-badware: 7124-1, 2h.17m
  ublock-privacy: 444-0, 2h.17m
  ublock-abuse: 70-70, 2h.17m
  ublock-unbreak: 2024-3, 2h.17m
  ublock-quick-fixes: 264-0, 2h.17m
  easylist: 65608-605, 2h.17m
  easyprivacy: 32261-648, 2h.17m
  urlhaus-1: 7605-1, 2h.17m
  plowe-0: 3737-2, 2h.17m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 192 ms (selfie)
 maxAssetCacheWait: 74 ms
popupPanel: 
 blocked: 4
 network: 
  googlesyndication.com: 1
  googletagmanager.com: 1
  translate.googleapis.com: 2
 cosmetic: 
  ##div[class] > ins.adsbygoogle:upward(div[class])
  ##.adsbygoogle:upward(1)
  #@#.lnadcontainer
```
</details>

**Comment by joshua1672** [comment]
has this been fixed? still not working for me

**Comment by joshua1672** [comment]
> 

nvm works now

**Comment by SpenceSal** [comment]
> has this been fixed? still not working for me

Yes it has, go into settings, clear cache, then reload all the filters
