### ISSUE TITLE
tv.nova.cz: detection

### ISSUE THREAD

**Issue by FranzFerdiand** [uBlockOrigin/uAssets#18061]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tv.nova.cz/porad/survivor/epizoda/359499-29-dil`

### Category

detection

### Description

u block origin gets detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94294
 cosmetic: 40527
 scriptlet: 17416
 html: 945
listset (total-discarded, last-updated): 
 removed: 
  DEU-0: null
 default: 
  user-filters: 0-0, never
  ublock-filters: 33976-54, 5h.30m
  ublock-badware: 7124-0, 5h.32m
  ublock-privacy: 443-0, 10d.6h.5m
  ublock-abuse: 70-70, 10d.6h.5m
  ublock-unbreak: 2023-0, 5h.31m
  easylist: 67207-634, 3d.1h.45m
  easyprivacy: 32237-609, 3d.1h.45m
  urlhaus-1: 7635-1, 11h.34m
  plowe-0: 3742-4, 10d.6h.5m
  ublock-quick-fixes: 254-2, 11h.33m
filterset (user): [empty]
trustedset: 
 added: [array of 21 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 5185 ms (selfie)
 maxAssetCacheWait: 2167 ms
popupPanel: 
 blocked: 24
 network: 
  caroda.io: 1
  cloudflareinsights.com: 2
  gemius.pl: 4
  google.com: 2
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 6
  imrworldwide.com: 1
  insurads.com: 2
  seznam.cz: 2
  trackad.cz: 1
  upscore.com: 1
 cosmetic: 
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by mapx-** [comment]
Czech page, enable `CZE, 🇸🇰 SVK: EasyList Czech and Slovak`
