### ISSUE TITLE
toramemoblog.com: detection

### ISSUE THREAD

**Issue by kain123999** [uBlockOrigin/uAssets#18071]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://toramemoblog.com/`

### Category

detection

### Description

<img width="584" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/112050208/45fb09bd-b007-43d2-855d-cf018e79d0a8">
Anti-advertisement blocker is activated and the homepage becomes unviewable.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 99311
 cosmetic: 50360
 scriptlet: 34820
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24188-2516, never
 default: 
  user-filters: 0-0, never
  JPN-1: 11217-5, 3d.13h.26m
  easylist: 67081-57, 5d.1h.27m
  easyprivacy: 32237-69, 5d.1h.27m
  plowe-0: 3742-941, 2d.17h
  ublock-abuse: 70-0, 5d.1h.27m
  ublock-badware: 7120-128, 18h.51m
  ublock-filters: 33071-97, 3d.23h.18m
  ublock-privacy: 394-74, 5d.1h.27m
  ublock-quick-fixes: 273-14, 6h.28m
  ublock-unbreak: 2013-35, 18h.51m
  urlhaus-1: 7175-1, 18h.51m
filterset (user): [empty]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 314 ms (selfie)
 maxAssetCacheWait: 106 ms
popupPanel: 
 blocked: 22
 no-popups: true
 network: 
  toramemoblog.com: 3
  amazon-adsystem.com: 1
  doubleclick.net: 1
  google.com: 1
  googlesyndication.com: 2
  themoneytizer.com: 12
  valuecommerce.com: 1
  www.googleapis.com: 1
 cosmetic: 
  ##.diver_widget_adarea
  ##.bottom_ad
  ##.header_message
```
</details>

**Comment by mapx-** [comment]
disable / remove fuckfuckadblock list and test again

**Comment by gorhill** [comment]
I was unable to reproduce. I could reproduce once I enabled Privacy Badger.

> - [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.

Did you truthfully answer that step?

**Comment by kain123999** [comment]
Sorry for the delay. To be more specific, the ad blocker works when I hit
the back button on chrome.
And I've disabled fuckfuckadblock and I don't use any other content
blockers.
I'd be happy to look into it when I have time.
Best regards.

A reproduction scenario is described below.
◆Access.
https://toramemoblog.com/
[image: image.png]
↓
◆Go to the next page on any page.
[image: image.png]
↓
◆Press the Back button
[image: image.png]
↓
◆Content is blocked.※Pressing the reload button or F5 will release the
content blocker.
[image: image.png]

2023年5月15日(月) 15:18 mapx ***@***.***>:

**Comment by mapx-** [comment]
it should work now

**Comment by kain123999** [comment]
Thanks for your quick response.
But unfortunately it wasn't an improvement. Is it possible that other
add-ons are affecting it?
If you have any other information you need, I would be happy to help.
Best regards

2023年5月15日(月) 22:03 mapx ***@***.***>:

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by kain123999** [comment]
Oh. I did the following actions and the symptoms are no longer present.
Thank you.

   - reset uBO, don't modify any uBO setting, update all the filter lists,
   don't add any other list (other than your regional list)→OK

Thank you for your help. Please close this ticket.
I know I keep saying this, but thank you.

2023年5月16日(火) 12:17 mapx ***@***.***>:

**Comment by kain123999** [comment]
I'm getting blocked again. Help!
https://toramemoblog.com/

2023年5月16日(火) 15:49 甲斐直幸 ***@***.***>:

**Comment by Yuki2718** [comment]
> ◆Go to the next page on any page. ↓ ◆Press the Back button ↓ ◆Content is blocked.

I observed this behavior on some other ai_adb sites too, bit problematic when we assess issues or cleanup obsolete rules.

**Comment by kain123999** [comment]
I observed this behavior on some other ai_adb sites too, bit problematic
when we assess issues or cleanup obsolete rules.I understand the situation.
The URL I was inquiring about has been unblocked, which is very convenient.
Thanks for taking care of it.
Regards

2023年5月23日(火) 23:22 Yuki2718 ***@***.***>:
