### ISSUE TITLE
maxstream.video: detection

### ISSUE THREAD

**Issue by SkateIV** [uBlockOrigin/uAssets#18079]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://maxstream.video/videostream/yqrollrikhdb/jli903qvx1gr/OE41OXc5eU9iRmE4ZnRKOFlIYXpOa2JybW5OcklRVk5VQnNCK0tuV09hUVNUN0NubXFWMlNOSmdVbjg0elBNWQ==`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 99296
 cosmetic: 46622
 scriptlet: 17430
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ITA-0: 13476-0, 8h.34m
  easylist: 65629-53, 4h.31m
  easyprivacy: 32263-47, 4h.30m
  plowe-0: 3742-938, 3d.1h.13m
  ublock-abuse: 70-0, 3d.1h.13m
  ublock-badware: 7120-128, 2d.2h.30m
  ublock-filters: 33099-104, 2d.2h.29m
  ublock-privacy: 394-74, 3d.1h.13m
  ublock-quick-fixes: 261-15, 8h.33m
  ublock-unbreak: 2013-40, 2d.2h.28m
  urlhaus-1: 6834-1, 6h.32m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 409 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel: 
 blocked: 5
 network: 
  googletagmanager.com: 1
  host-cdn.net: 1
  intellipopup.com: 1
  programmeframeworkpractically.com: 2
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
