### ISSUE TITLE
lofter.com: nuisance

### ISSUE THREAD

**Issue by contextnerror** [uBlockOrigin/uAssets#18077]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Context menu is blocked when clicking over an image in the post

### URL(s) where the issue occurs.

`https://jundao88362.lofter.com/post/32163161_2b738247e`

### Notes

Technically did not test with default lists because default lists does not include annoyances

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93945
 cosmetic: 40129
 scriptlet: 20507
 html: 1115
listset (total-discarded, last-updated): 
 added: 
  ublock-annoyances: 4949-4, now
 default: 
  user-filters: 0-0, never
  ublock-filters: 33902-73, now
  ublock-badware: 7123-0, now
  ublock-privacy: 444-0, now
  ublock-abuse: 70-70, now
  ublock-unbreak: 2027-1, now
  ublock-quick-fixes: 275-0, now
  easylist: 65635-644, now
  easyprivacy: 32268-613, now
  urlhaus-1: 6834-1, now
  plowe-0: 3737-4, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1821 ms
 maxAssetCacheWait: 14 ms
```
</details>

**Comment by gorhill** [comment]
@mapx- Just clicking the picture also redirect to login page, I think we should also defuse `mousedown`:

    lofter.com##+js(aeld, /contextmenu|mousedown/)

**Comment by gorhill** [comment]
Duh never mind, forgot to enable _"uBlock filters -- Annoyances"_.
