### ISSUE TITLE
serienstream.to: breakage

### ISSUE THREAD

**Issue by danielrzad** [uBlockOrigin/uAssets#18070]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://serienstream.to/redirect/12233518?token=03AL8dmw8eCSs3mDHMX7JUVLZ3n7Dp3_pyuc_pr_SR1vY5P1YZi9zBp7JtFQENwFMRxtngdXjZIwMwjIWITmIBJzZJFrDogWVXm2WmQb3E9LLUIGSCwILuqlGbtJ-A-2T4JdyImQ0SW8X5zkWadc0NSKOUCgBTuzz2sXnpTkQqMVfFTIjVuFjFdtotgBANAUth-nYFHtK743JJGTxaGlLcpIzr4g7_P-weEpX1X-gy6u9mbmQrxhnVACsJ-OV5JsGX-owxrLtICj7337ga60jbxM3InD4MYypEnTXRilMshK6PiBSD6hyNf6bJMqFAXkiff51BMvp2HWYirL_t4iwIJvPdStdbyrILN5xsi2HARCmXLcGW7y13EhSXq0IBzjcnFHyrxjImvmre7ug6FhIwnmi0ynDgUISuSlQYbNYRgEACQExh8P6JW2wR-PUHaCnfhTBk1EHfD7SU98NWnEAN5nqnHR6Q1QRUv9GC8BWtDw2EmxF1ygBSIRaYdl1E6-l3AqtYMObz6cdMKkYjEjxFvr8kmxcOuG6cUV3IbwpyeKTL7nlrIpRw8C7nKWyBvXv74iCk0g2OgyBc0dfYVhCJDxkiJ0VqdsLR-RUrt-qhcBUVZKtfuHLZzvMVLkkYJMP3WrKuAWrpwxT_&original=`

### Category

breakage

### Description

Site is not properly redirecting. Usually it stops on the bouncing ball (80% of attempts). Sometimes it displays captcha, but even after solving the captcha site is stuck on the bouncing ball (20% of attempts). What I've tried:
- whitelisting didn't help,
- I've tried opening the same URL on another chrome profile without the uBlock installed and site redirected me immediately.

Here's a videos showing a difference:
- on the first attempt I'm using a profile with the uBlock installed,
- on the second attempt I'm using a profile without the uBlock installed.
`https://clipchamp.com/watch/ACekbBYNZXL`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-05-14 103412](https://github.com/uBlockOrigin/uAssets/assets/45539133/ac4c1267-8b30-44cf-8317-b2d60034ad99)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95360
 cosmetic: 46348
 scriptlet: 17654
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  POL-0: 7943-11, 10h.49m
  POL-2: 1275-13, 1d.12h.9m
  easylist: 65608-71, 1d.12h.9m
  easyprivacy: 32261-46, 1d.12h.9m
  plowe-0: 3737-945, 1d.12h.9m
  ublock-abuse: 70-0, 1d.12h.9m
  ublock-badware: 7120-128, 1d.12h.9m
  ublock-filters: 33131-133, 1d.12h.9m
  ublock-privacy: 394-74, 1d.12h.9m
  ublock-quick-fixes: 273-20, 10h.48m
  ublock-unbreak: 2013-39, 1d.12h.9m
  urlhaus-1: 7175-1, 10h.47m
filterset (user): [empty]
trustedset: 
 added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 374 ms (selfie)
 maxAssetCacheWait: 133 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
redirected to `https://dood.la/e/daqv9c94zlgr` => `video you are looking for is not found.`

**Comment by danielrzad** [comment]
> redirected to `https://dood.la/e/daqv9c94zlgr` => `video you are looking for is not found.`

Hmm, don't know then why I'm getting stuck and you don't. I've also tried changing IP and clearing cookies, but that didn't help. Here's a videos showing a difference:
- on the first attempt I'm using a profile with the uBlock installed,
- on the second attempt I'm using a profile without the uBlock installed.
https://clipchamp.com/watch/ACekbBYNZXL

**Comment by stephenhawk8054** [comment]
I can't reproduce the issue either. Video recording: https://github.com/uBlockOrigin/uAssets/assets/66517106/7cfed856-dc2d-4bb1-be15-7cdc369cbdec

```yaml
popupPanel: 
 blocked: 0
```
And based on your troubleshooting information, uBO is not blocking anything.

**Comment by danielrzad** [comment]
> And based on your troubleshooting information, uBO is not blocking anything.
I know and that's what's most weird here.

**Comment by danielrzad** [comment]
> And based on your troubleshooting information, uBO is not blocking anything.

Yes and that's most interesting here.

**Comment by stephenhawk8054** [comment]
When I test in another profile in normal mode, it still works correctly for me: https://github.com/uBlockOrigin/uAssets/assets/66517106/7bdff5e8-1751-45d1-8932-a9241e3955cc

I think it might be just a coincidence of the network with captcha.

**Comment by gorhill** [comment]
> based on your troubleshooting information, uBO is not blocking anything

There are scriptlets being injected though.
