### ISSUE TITLE
thecubexguide.com: detection

### ISSUE THREAD

**Issue by Malgotra** [uBlockOrigin/uAssets#18083]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://thecubexguide.com/litespeed-web-server-vs-nginx/`

### Category

detection

### Description

Ad blocker detection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20230515-221842](https://github.com/uBlockOrigin/uAssets/assets/122884037/a59f6187-f0ac-44db-a55c-0fd6c8d7dceb)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 113
filterset (summary): 
 network: 124060
 cosmetic: 204205
 scriptlet: 39815
 html: 1115
listset (total-discarded, last-updated): 
 added: 
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 947-0, 1m
  adguard-generic: 70616-5244, 3d.1h.17m
  adguard-spyware-url: 1025-5, 3d.1h.16m
  block-lan: 47-0, 3d.1h.16m
  adguard-annoyance: 68101-807, 3d.1h.16m
  fanboy-annoyance: 90856-20834, 3d.1h.16m
  ublock-annoyances: 5004-4, 3d.1h.16m
 default: 
  user-filters: 2-0, never
  ublock-filters: 34227-110, 3d.1h.17m
  ublock-badware: 7118-1, 3d.1h.17m
  ublock-privacy: 444-0, 3d.1h.17m
  ublock-abuse: 70-70, 3d.1h.17m
  ublock-unbreak: 2029-2, 3d.1h.17m
  ublock-quick-fixes: 275-0, 1m
  adguard-mobile: 8744-98, 3d.1h.16m
  easylist: 65585-663, 3d.1h.16m
  easyprivacy: 32263-621, 3d.1h.16m
  urlhaus-1: 6892-1, 1m
  plowe-0: 3737-2, 3d.1h.16m
filterset (user): [array of 2 redacted]
modifiedUserSettings: 
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3079 ms (selfie)
 maxAssetCacheWait: 1000 ms
popupPanel: 
 blocked: 2
 network: 
  googletagmanager.com: 1
  jsdelivr.net: 1
```
</details>

**Comment by Malgotra** [comment]
Duplicate #17570 & #17548

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17709#issuecomment-1548478432
