### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by WoodpeckerBaby** [uBlockOrigin/uAssets#18080]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=UENzvvpi1Hs`

### Category

ads

### Description

side panel ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="568" alt="Screenshot 2023-05-14 at 5 30 24 PM" src="https://github.com/uBlockOrigin/uAssets/assets/14303318/31c62075-9cfc-4258-989f-a21181bcbea4">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 119902
 cosmetic: 115941
 scriptlet: 38018
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  easylist: null
  plowe-0: null
 added: 
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 40534-127, 2m
  CHN-0: 26638-124, 2m
  adguard-annoyance: 68132-260, 2m
  adguard-generic: 70641-1328, 2m
  adguard-spyware-url: 1026-3, 2m
  block-lan: 47-0, 2m
  ublock-annoyances: 4983-209, 2m
 default: 
  user-filters: 78-0, never
  easyprivacy: 32271-13556, 2m
  ublock-abuse: 70-0, 2m
  ublock-badware: 7119-248, 2m
  ublock-filters: 33029-4027, 2m
  ublock-privacy: 394-135, 2m
  ublock-quick-fixes: 273-31, 2m
  ublock-unbreak: 2016-126, 2m
  urlhaus-1: 6834-1, 2m
filterset (user): [array of 78 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1250 ms (selfie)
 maxAssetCacheWait: 251 ms

```
</details>

**Comment by WoodpeckerBaby** [comment]
fixed upon forced update

**Comment by WoodpeckerBaby** [comment]
Why is it not updating automatically for 3 days though?

**Comment by stephenhawk8054** [comment]
The current auto-update interval is 5 days.

**Comment by iam-py-test** [comment]
> ```yml
>   easylist: null
>   plowe-0: null
> ```

You also have two default filters disabled (EasyList and Peter Lowe).

**Comment by WoodpeckerBaby** [comment]
Auto update interval should be every 6 hours. Is there an override for this setting?

**Comment by stephenhawk8054** [comment]
EasyList and Peter Lowe list are not included in uBO's built-in lists. The built-in lists are for issues that need uBO's syntaxes.

---

I don't think you can override uBO's auto update interval, but I'm not sure. @gwarser Sorry do you remember if we can override the update interval of all lists in advanced settings?

**Comment by gwarser** [comment]
> I thought this is included in the base filter already.

uBO version of AdGuard base list does not have Easylist included.

> can override the update interval of all lists in advanced settings?

Not possible by advanced settings.

**Comment by WoodpeckerBaby** [comment]
AdGuard supports up to hourly filter updates. Their filter lists are updated very frequently. I'm not sure if uBO's fork is updated as frequently, but the current 5-day update interval is certainly showing cracks in ad blocking. 

I think a 6 hour pull is optimal at the user end, filter lists should release hourly, and merging PRs should happen in real time.

**Comment by iam-py-test** [comment]
> I think a 6 hour pull is optimal at the user end, filter lists should release hourly, and merging PRs should happen in real time.

I agree that with frequent updates, lowering the time period is nice.
The problem with this is server load. 6 hours/1 day has far more load on the servers than 5 days.

**Comment by WoodpeckerBaby** [comment]
Why not use GitHub directly?

If they don't allow it, use a free CDN service like cloudflare. Use something like `statics.example.com/list123.txt` then mark that subdomain for caching and control the TTL from there.

**Comment by iam-py-test** [comment]
I don't know, I could be wrong. Personally, I'm against using Cloudflare if possible.

**Comment by WoodpeckerBaby** [comment]
What's wrong with Cloudflare?

**Comment by stephenhawk8054** [comment]
> Why not use GitHub directly?
> 
> If they don't allow it, use a free CDN service like cloudflare. Use something like `statics.example.com/list123.txt` then mark that subdomain for caching and control the TTL from there. 

In case you don't know, github pages set the limit 100GB bandwidth per month for each free project.

uBO is already use 4 sources/CDNs to distribute content: github pages, cloudflare, jsdelivr, statically.io

This is the bandwidth statistics from jsdelivr: https://www.jsdelivr.com/package/gh/uBlockOrigin/uAssetsCDN?tab=stats which is 100TB per month. And this is just one of the 4 CDNs so easy to do the math here. It's already exceed 100 times what github allows for free project.

uBO is a non-profit, FOSS project with no servers, unlike a business like Adguard, so we want to use fair and don't want to abuse the server loads for the CDNs that allow us to use free.

**Comment by iam-py-test** [comment]
> What's wrong with Cloudflare?

Long list of reasons (privacy, blocking of Tor users, etc), but that's off topic.

**Comment by WoodpeckerBaby** [comment]
Welp, I think GitHub allows open source repositories to host small files directly for applications with practically no quota.

**Comment by stephenhawk8054** [comment]
Quota of what? Bandwidth or storage?

**Comment by garry-ut99** [comment]
"quicker interval of filter lists update in uBO" requests have been already declined several times in the past: 
- https://github.com/gorhill/uBlock/issues/1333#issuecomment-178706420
- https://github.com/gorhill/uBlock/issues/3117
- https://github.com/uBlockOrigin/uAssets/issues/6526#issuecomment-551524711
- https://github.com/uBlockOrigin/uBlock-issues/issues/2199#issuecomment-1205490004
- https://github.com/uBlockOrigin/uBlock-issues/issues/1165

**Comment by WoodpeckerBaby** [comment]
Is there a fork of uBO that updates more frequently?

If not, I will dig in myself.

**Comment by WoodpeckerBaby** [comment]
https://raw.githubusercontent.com/WoodpeckerBaby/uBO-Fast-Refresh/master/uBO-fast-refresh-1-day.txt 

I made this. Fell free to use.

**Comment by WoodpeckerBaby** [comment]
> @WoodpeckerBaby There's a workaround to get 1 day update frequency.
> 
> Create a custom filter list with `Expires` set to the lowest possible value: `! Expires: 12h`
> 
> [uBlockOrigin/uBlock-issues#1165 (comment)](https://github.com/uBlockOrigin/uBlock-issues/issues/1165#issuecomment-1484306375)


Sorry, this doesn't work because what if the costom list is correctly updated by itself? Also, the default quick fix list is updated every 12 hours as well. 

As long as this is updated correctly, it will not trigger uBO to override the TTL for other filters.

**Comment by WoodpeckerBaby** [comment]
Of course it would. Same with anyother filter lists. I'm gonna keep it there, but this approach doesn't work.

**Comment by WoodpeckerBaby** [comment]
Good point, I will make it private so it will fail to update and see what happens.

**Comment by WoodpeckerBaby** [comment]
> > Of course it would
> 
> Failing to update means it will stay outdated, right?

I don't think it's working. The 12h filter is outdated by 1d.18h, yet some filters are still not refreshed and showing 5 days +.

```
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 250111
 cosmetic: 225723
 scriptlet: 39664
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/WoodpeckerBaby/uBO-Fast-Refresh/master/uBO-fast-refresh-1-day.txt: 1-0, 1d.18h.20m
  CHN-0: 26720-112, 1d.18h.24m
  adguard-annoyance: 68361-101, 1d.18h.23m
  adguard-generic: 71121-486, 1d.18h.22m
  adguard-social: 20514-871, 22h.38m
  adguard-spyware-url: 1031-3, 1d.18h.21m
  block-lan: 47-0, 5d.21h.6m
  curben-phishing: 99852-2, 14m
  curben-pup: 189-0, 14m
  dpollock-0: 11357-38, 5d.1h.43m
  fanboy-annoyance: 90535-21420, 5d.1h.43m
  fanboy-cookiemonster: 47130-47130, 5d.1h.43m
  fanboy-social: 16642-16642, 5d.1h.43m
  fanboy-thirdparty_social: 68-18, 5d.1h.43m
  ublock-annoyances: 4983-268, 5d.21h.6m
 default: 
  user-filters: 78-0, never
  easylist: 65712-1134, 5d.1h.43m
  easyprivacy: 32271-346, 5d.21h.6m
  plowe-0: 3737-1325, 5d.1h.43m
  ublock-abuse: 70-0, 5d.21h.6m
  ublock-badware: 7098-390, 20h.34m
  ublock-filters: 33038-4050, 20h.36m
  ublock-privacy: 394-78, 5d.21h.6m
  ublock-quick-fixes: 350-39, 14m
  ublock-unbreak: 2020-103, 20h.35m
  urlhaus-1: 7065-3, 14m
filterset (user): [array of 78 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2503 ms (selfie)
 maxAssetCacheWait: 444 ms

```
