### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Sourour2002** [uBlockOrigin/uAssets#18081]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Description

Some ads can get through but only youtube premium ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 114180
 cosmetic: 48486
 scriptlet: 17543
 html: 0
listset (total-discarded, last-updated): 
 added: 
  FRA-0: 28350-31, 3d.9h.16m
  ara-0: 2783-5, 5h.39m
 default: 
  user-filters: 0-0, never
  easylist: 65639-357, 1d.9h.27m
  easyprivacy: 32263-347, 1d.9h.26m
  plowe-0: 3737-960, 5h.41m
  ublock-abuse: 70-1, 5d.19h.30m
  ublock-badware: 7120-145, 2d.9h.1m
  ublock-filters: 33102-180, 2d.9h.1m
  ublock-privacy: 394-74, 5d.19h.29m
  ublock-quick-fixes: 273-15, 3h.38m
  ublock-unbreak: 2013-42, 2d.9h.1m
  urlhaus-1: 6834-1, 5h.40m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 310 ms (selfie)
 maxAssetCacheWait: 164 ms
popupPanel: 
 blocked: 31
 network: 
  youtube.com: 20
  doubleclick.net: 3
  google.com: 4
  google.com.eg: 1
  googlevideo.com: 2
  ytimg.com: 1
 cosmetic: 
  ###player-ads
  ###offer-module
  ###merch-shelf
  ##.ytp-ad-progress-list
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
```
</details>

**Comment by krystian3w** [comment]
all = all -> #7636
