### ISSUE TITLE
rosenheim24.de: popups

### ISSUE THREAD

**Issue by hackgrid** [uBlockOrigin/uAssets#18085]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

As of #17085 the popups get removed correctly, e.g.

`https://www.rosenheim24.de/rosenheim/inntal/nussdorf-am-inn-ort47622/dann-setzt-der-jagdtrieb-ein-wie-eine-gams-von-zwei-hunden-zu-tode-gejagt-wurde-92279809.html`

works totally fine!

But on some sites like

`https://www.rosenheim24.de/rosenheim/rosenheim-land/rosenheim-schon-wieder-streiken-die-zuege-das-sagen-die-pendler-in-rosenheim-dazu-92280125.html`

it does not work and the popup appears again!

I also noticed, that it used to work correctly on `ovb-online.de` (same platform), but now it does not again, e.g.:

`https://www.ovb-online.de/rosenheim/rosenheim-land/dann-setzt-der-jagdtrieb-ein-wie-eine-gams-von-zwei-hunden-zu-tode-gejagt-wurde-92279809.html`

(the upper one works on rosenheim24.de)

`https://www.ovb-online.de/rosenheim/rosenheim-stadt/rosenheim-das-passiert-mit-dem-45-jahre-alten-fiat-wrack-92279222.html`

### URL(s) where the issue occurs.

```
https://www.rosenheim24.de/rosenheim/rosenheim-land/rosenheim-schon-wieder-streiken-die-zuege-das-sagen-die-pendler-in-rosenheim-dazu-92280125.html

https://www.ovb-online.de/rosenheim/rosenheim-stadt/rosenheim-das-passiert-mit-dem-45-jahre-alten-fiat-wrack-92279222.html

https://www.ovb-online.de/rosenheim/rosenheim-land/dann-setzt-der-jagdtrieb-ein-wie-eine-gams-von-zwei-hunden-zu-tode-gejagt-wurde-92279809.html
```

### uBO version

1.49.2

### Browser name and version

Firefox 113.0.1

### Settings

None

**Comment by gorhill** [comment]
> the popups get removed correctly

What do you call "the popups"? Provide screenshots, it's not clear what you are referring to.

Also, go to the webpage you say the issue occurs, then popup panel => _chat_ icon => click _troubleshooting information_ => copy/paste content here, in code form.

**Comment by mapx-** [comment]
@hackgrid I can not reproduce for rosenheim24

for `ovb-online.de` use this custom filter
`pc-offer$script,domain=ovb-online.de`

I'll remove from the lists the other similar filters, in the end it's still a paywall

**Comment by hackgrid** [comment]
Thanks, but oh no, please do not remove :D
Since you "considered it still a false / poor paywall" in the last issue :)
