### ISSUE TITLE
estrenos10.com [Anti-Adblock] [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1809]
URL(s) where the issue occurs

`https://estrenos10.com`

Describe the issue

Anti-Adblock
![](https://i.imgur.com/K1BAJVo.png)

Ads
![](https://i.imgur.com/m1gsabL.png)

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
I should really stop solving anti adblockers with cosmetic filters, this appears to fix it
```
||piguiqproxy.com^$xmlhttprequest,domain=estrenos10.com,redirect=nooptext
estrenos10.com##.in.modal-backdrop
estrenos10.com##.modal-dialog
estrenos10.com##body:style(overflow: scroll !important;)
estrenos10.com###myModalForMoney
estrenos10.com###noticiaviral
```

**Comment by lain566** [comment]
There's a popup when I try to play the video.
`https://estrenos10.com/pelicula/2932/father-of-the-year.html`

**Comment by lain566** [comment]
There's a popup when you click anywhere on the player, the video can only be played if you click on the play button in the center. A popup also opens when the video is paused.
`https://estrenos10.com/peliculas/cadaver-xsts`

**Comment by okiehsch** [comment]
`||r.mail.ru^$popup`

**Comment by lain566** [comment]
@okiehsch And why not? `my.mail.ru##+js(window.open-defuser.js)`

It only affects this section
`https://my.mail.ru/video`

**Comment by okiehsch** [comment]
Because I have no clue if this breaks something for anybody using `my.mail.ru`.
I also would be hesitant to add `facebook.com##+js(window.open-defuser.js)` if some facebook videos had popups.

**Comment by lain566** [comment]
`window.open-defuser.js` This scriptlet, can't be used to a specific script?
