### ISSUE TITLE
secure.blackbull.com: detection

### ISSUE THREAD

**Issue by HeyZeus1232** [uBlockOrigin/uAssets#18090]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://secure.blackbull.com/`

### Category

detection

### Description

Detects an adblocker is installed. Must have been recently, because it was fine before.

`https://secure.blackbull.com/`
`https://secure.blackbull.com/dashboard/trading-accounts/live?lang=en`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 102
filterset (summary): 
 network: 93625
 cosmetic: 38838
 scriptlet: 17444
 html: 945
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34006-42, 3d.53m
  ublock-badware: 7124-1, 3d.52m
  ublock-privacy: 444-0, 2d.7h.53m
  ublock-abuse: 70-70, 2d.7h.52m
  ublock-unbreak: 2027-2, 22h.59m
  ublock-quick-fixes: 279-14, 12h.12m
  easylist: 65608-640, 3d.54m
  easyprivacy: 32271-613, 1d.29m
  urlhaus-1: 6828-1, 18h.13m
  plowe-0: 3737-2, 21h.8m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 630 ms (selfie)
 maxAssetCacheWait: 304 ms
popupPanel: 
 blocked: 5
 network: 
  adroll.com: 1
  googletagmanager.com: 1
  icanhazip.com: 1
  omappapi.com: 1
  userguiding.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need an account to reproduce?

**Comment by HeyZeus1232** [comment]
> Do you need an account to reproduce?

sorry, i didn't even think of that. Yeah pretty sure you need an account, but don't have to supply any documents or anything, should be able to create a dummy account with a dummy email. Just press skip if it asks you to submit documents

**Comment by stephenhawk8054** [comment]
I signed up with `demo` options but I can't see any detections. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/7f9b68a6-b6a7-43c5-b7a6-706528c5984b

**Comment by HeyZeus1232** [comment]
> I signed up with `demo` options but I can't see any detections. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/7f9b68a6-b6a7-43c5-b7a6-706528c5984b

This is what comes up for me

![adblockblock](https://github.com/uBlockOrigin/uAssets/assets/111616953/a6ead6d3-4610-484a-9967-27e749e7acfe)

**Comment by stephenhawk8054** [comment]
Disable all other extensions and test again.

**Comment by HeyZeus1232** [comment]
> Disable all other extensions and test again.

i tried without extensions, except for dark reader, and did same thing, got rid of that and it worked fine. Put dark reader back on, and it still worked fine. put all my other extensions back too and it still works fine. No idea what happened. Seems to be solved?

**Comment by stephenhawk8054** [comment]
You are using multiple blockers at the same time (Privacy Badgers, uBO...), and that can easily cause unexpected anti-adb. Just choose 1 to use.

That's why we have these prerequisites for users to check _**truthfully**_ before submitting issue:

> - [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
> - [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
