### ISSUE TITLE
unian.ua: detection

### ISSUE THREAD

**Issue by ad-helper** [uBlockOrigin/uAssets#18093]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.unian.ua/war/boji-za-bahmut-zsu-dronami-znishchili-vorozhi-ustanovki-zmiy-gorinich-ta-ponad-tonnu-trotilu-12258468.html`

### Category

detection

### Description

message "you are using ad blocker. turn it off to see a video" (in ukrainian) in video frame in middle part of article

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![unian-ad-block](https://github.com/uBlockOrigin/uAssets/assets/133770027/c322d070-15cd-49f8-b52f-321a420485d1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 109
filterset (summary): 
 network: 121122
 cosmetic: 202601
 scriptlet: 26630
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 17h.6m
  RUS-0: 39709-10, 17h.8m
  adguard-annoyance: 68187-494, 17h.9m
  adguard-social: 20460-873, 17h.10m
  fanboy-annoyance: 90911-21393, 4d.18h.35m
  ublock-annoyances: 4975-233, 6d.19h.23m
 default: 
  user-filters: 17-0, never
  easylist: 65626-124, 1d.18h.51m
  easyprivacy: 32139-209, 17h.11m
  plowe-0: 3737-945, 15h.4m
  ublock-abuse: 70-1, 15h.3m
  ublock-badware: 7120-128, 3d.16h.39m
  ublock-filters: 33102-519, 3d.16h.38m
  ublock-privacy: 394-76, 17h.14m
  ublock-quick-fixes: 283-14, 3h.46m
  ublock-unbreak: 2013-41, 3d.16h.37m
  urlhaus-1: 6828-1, 17h.7m
filterset (user): [array of 17 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 17940 ms (selfie)
 maxAssetCacheWait: 2589 ms
popupPanel: 
 blocked: 13
 network: 
  unian.ua: 2
  cloudflareinsights.com: 2
  gemius.pl: 1
  googletagmanager.com: 4
  googletagservices.com: 1
  idealmedia.io: 1
  membrana.media: 1
  unian.net: 1
 cosmetic: 
  ###return-to-top
  ##.article-shares
  ##.social-likes
  ##.nts-video-wrapper
  ##.read-also-slider
  ##.footer-menu__app
  ##.support-unian
  ##.tools
  ##.views.article__info-item
  ##.banner-container
  ##.bnr-block__bnr
  ##.newsfeed__banner
  ##.partner-news
  ##[data-ad]
  ##div[style*=\"height\"][style*=\"250px\"]
  ##.cookies:not(html,body)
  ##.social-btn-bottom
  ##.support-post
  ##.banner-fb
  ##.cookies
  ##a[href^=\"https://twitter.com/share\"]
  ##a[href^=\"viber://forward?text=\"]
  ##a[href^=\"https://telegram.me/share/url?\"]
  ##a[href^=\"http://www.facebook.com/sharer.php?\"]
  ##div[id*=\"ScriptRoot\"]
  ##a[href^=\"http://www.facebook.com/sharer.php\"]
```
</details>

**Comment by dimisa-RUAdList** [comment]
The problem is not reproduced. It is likely that the triggering of the detector causes some kind of third-party blocking tool.
