### ISSUE TITLE
thetimes.co.uk: breakage

### ISSUE THREAD

**Issue by Desmo46** [uBlockOrigin/uAssets#18094]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

In an apparent slight regression of https://github.com/uBlockOrigin/uAssets/issues/15463

Images in the live blog of thetimes.co.uk are loading in low quality.
Pausing uBlock restores them to normal quality, I believe the related issue was a filter preventing the high quality assets from being shown.

### URL(s) where the issue occurs.

`https://www.thetimes.co.uk/article/rishi-sunak-iceland-speech-migrants-eu-ukraine-war-2023-xg2kgkqfr`

### Screenshot(s)

https://snipboard.io/dsBCxp.jpg

### Notes

Pausing/turning off uBlock lets the images load in full quality

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 99513
 cosmetic: 107124
 scriptlet: 19525
 html: 0
listset (total-discarded, last-updated): 
 added: 
  fanboy-annoyance: 90882-15459, 5d.13h.55m
 default: 
  user-filters: 0-0, never
  easylist: 65608-46, 2d.11h.4m
  easyprivacy: 32261-46, 2d.11h.3m
  plowe-0: 3742-937, 5d.16h
  ublock-abuse: 70-0, 5d.15h.59m
  ublock-badware: 7120-128, 3d.16h.48m
  ublock-filters: 33132-117, 3d.16h.48m
  ublock-privacy: 394-76, 5d.15h.58m
  ublock-quick-fixes: 287-14, 5m
  ublock-unbreak: 2012-41, 3d.16h.48m
  urlhaus-1: 7673-1, 6m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-extension-scheme
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 366 ms (selfie)
 maxAssetCacheWait: 79 ms
```
</details>

**Comment by gorhill** [comment]
I get a paywall, but the image shown at the top of articles seem to be a good resolution. I can see in the DOM that the `img` tag has a `srcset` attribute for multiple resolutions, up to `1500w`, which means the source image is natively picked by the browser.

Which exact browser vendor are you using?

**Comment by Desmo46** [comment]
That's correct, the image at the top of the page is in high quality but any after that within the timeline itself are much lower.

Another example, here; https://www.thetimes.co.uk/article/cameron-norrie-smashes-ball-at-angry-novak-djokovic-in-defeat-6kx52r68s

Screenshot: https://snipboard.io/wSk6WH.jpg

Using Chrome Beta on macOS

**Comment by gorhill** [comment]
I won't be able to investigate further since this requires an account.

**Comment by mapx-** [comment]
adding 
`thetimes.co.uk##+js(nostif, /^/)`

I'll have the page "stable" and indeed the small images are low quality

**Comment by gorhill** [comment]
Not sure, but after I allow `newrelic.com` and `nr-data.net`, the images look fine when I remove the overlay paywall using the zapper.

**Comment by gorhill** [comment]
Does this work?

    thetimes.co.uk##+js(aopw, NREUM)

**Comment by gorhill** [comment]
@Desmo46 Please report whether the following filter fixes your issue, and that it does not cause breakage elsewhere on the site:

    thetimes.co.uk##+js(aopw, NREUM)

**Comment by Desmo46** [comment]
Apologies been away from my computer; it does seem to fix it on initial page load i.e all images in high quality, so an improvement over the previous behaviour.

However if you subsequently refresh the page the images will be low quality again even with filter enabled. 
Turning off uBlock and replicating this behaviour it still continues so this must be something to do with the site; I would say leave this marked as closed for now and i'll report to them directly.
Thanks for investigating
