### ISSUE TITLE
games.metv.com: detection

### ISSUE THREAD

**Issue by tymime** [uBlockOrigin/uAssets#18096]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://games.metv.com/games/crystal-collapse?fbclid=IwAR1TwiW_TEaXDbwe_CBU6k0rw4CL81nHXsT6SWFUVKQiFHEU7h6kbkSxE9c`

### Category

detection

### Description

Anti-adblock message

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 103
filterset (summary): 
 network: 99831
 cosmetic: 99083
 scriptlet: 20178
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 68249-91, now
 default: 
  user-filters: 789-13, never
  easylist: 65802-103, now
  easyprivacy: 32146-127, now
  plowe-0: 3737-940, now
  ublock-abuse: 70-0, now
  ublock-badware: 7069-127, now
  ublock-filters: 33038-481, now
  ublock-privacy: 393-73, now
  ublock-quick-fixes: 287-30, now
  ublock-unbreak: 2015-42, now
  urlhaus-1: 7673-1, now
filterset (user): [array of 793 redacted]
trustedset: 
 added: [array of 104 redacted]
 removed: 
  about-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset: 
 added: [array of 25 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 38924 ms (selfie)
 maxAssetCacheWait: 12234 ms
popupPanel: 
 blocked: 56
 network: 
  33across.com: 5
  360yield.com: 11
  3lift.com: 2
  a-mo.net: 1
  adlightning.com: 1
  adnxs.com: 2
  amazon-adsystem.com: 1
  casalemedia.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  id5-sync.com: 1
  imasdk.googleapis.com: 1
  indexww.com: 2
  lijit.com: 2
  media.net: 1
  minutemedia-prebid.com: 1
  msecnd.net: 1
  openx.net: 2
  pubmatic.com: 3
  pushengage.com: 2
  quantcast.com: 1
  quantserve.com: 1
  rubiconproject.com: 5
  smartadserver.com: 4
  teads.tv: 2
  yellowblue.io: 1
 cosmetic: 
  ##display-ad-component
  ##[class^=\"DisplayAd\"]
  ##div[class*=\"displayAdRight\"]
  ##.display-ad
```
</details>

**Comment by gorhill** [comment]
Maybe someone else has a better solution:

    @@||games.metv.com^$ghide
    games.metv.com##[class*="__displayAd"]

**Comment by okiehsch** [comment]
````
@@||games.metv.com^$ghide
games.metv.com##[class*="DisplayAd__c@@||games.metv.com^$ghide
games.metv.com##[class*="DisplayAd__container"]
games.metv.com##+js(nano-sib)
ontainer"]
games.metv.com##+js(nano-sib)
````
