### ISSUE TITLE
newegg.com: breakage

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#18098]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.newegg.com/msi-geforce-rtx-3060-rtx-3060-ventus-2x-12g-oc/p/14-137-632?Item=14-137-632&cm_sp=homepage-_-newegglive-802-_-product-14-137-632`

### Category

breakage

### Description

The financing section as indicated ( yellow cirle) in the image is not shown when UBo is enabled, these are not ads bud financing options.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![newegg](https://github.com/uBlockOrigin/uAssets/assets/24624945/06b2cac1-c7f0-4dd8-a40e-e2dac86128c9)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.49.3b10:
 since: 2d.5h
Firefox: 113
filterset (summary):
 network: 101099
 cosmetic: 108563
 scriptlet: 22578
 html: 1124
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/adblock.txt: 3770-0, 4h.34m
  https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 439-0, 2d.3h.47m
  https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 490-0, 2d.3h.47m
  fanboy-cookiemonster: 47140-163, now
  fanboy-social: 16542-7, now
  ublock-annoyances: 4948-15, now
  easylist-annoyances: 3995-92, now
  easylist-newsletters: 5148-20, now
  easylist-notifications: 2604-3, now
 default:
  user-filters: 0-0, never
  ublock-filters: 33907-95, now
  ublock-badware: 7073-1, now
  ublock-privacy: 443-0, now
  ublock-unbreak: 2026-4, now
  ublock-quick-fixes: 299-0, now
  easylist: 65802-372, now
  easyprivacy: 32146-229, now
  urlhaus-1: 7673-1, 1h.44m
filterset (user): [empty]
trustedset:
 added: [array of 59 redacted]
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings:
 autoCommentFilterTemplate: none
 extensionUpdateForceReload: true
 filterAuthorMode: true
 filterOnHeaders: true
 updateAssetBypassBrowserCache: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 751 ms (selfie)
 maxAssetCacheWait: 75 ms
popupPanel:
 blocked: 18
 network:
  newegg.com: 10
  attn.tv: 1
  flix360.io: 1
  flixcar.com: 2
  google-analytics.com: 1
  google.com: 1
  narrativ.com: 1
  osano.com: 1
 extended:
  ##a[href^="https://www.pinterest.com/pin/create/button/"]
  ##.product-ads
  ##.product-ad
  ##.product-share
  ###ot-sdk-btn:not(button)
  ##.ot-sdk-show-settings
  ##.popover-share
```
</details>

**Comment by mapx-** [comment]
test

`@@||ec-apis.newegg.com^$xhr,1p`

**Comment by troysjanda** [comment]
I'll try in like 30 minutes had to get kids from school...

**Comment by troysjanda** [comment]
Fixed
