### ISSUE TITLE
yavli

### ISSUE THREAD

**Issue by jo2dan23** [uBlockOrigin/uAssets#181]
http://allenwestrepublic.com/allen-west-with-tomi-lahren-comey-clintons-email-anthony-weiner-trump-and-wikileaks-video/ they changed the code. script is no longer being injected

**Comment by uBlock-user** [comment]
`yavli-defuser.js` no longer works. Nasty ads are loading again - https://i.gyazo.com/039dcea04538e5bc2469d7df3ff4dc5f.png

I'm using `(setTimeout-defuser)` and it works fine. Same case with `barbwire.com` and `aplus.com` Haven't tested the rest of the lot using `yavli-defuser`, but probably will be the same case with them too.

**Comment by LikesHisComputer** [comment]
`https://www.go4games.ro/reviews/call-of-duty-vanguard-review-19295998/` - ads
