### ISSUE TITLE
pelisplus.tv [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1810]
URL(s) where the issue occurs

`https://www.pelisplus.tv/`

Describe the issue

Pop-up

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`pelisplus.tv##script:inject(abort-current-inline-script.js,smrtSP)`

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
