### ISSUE TITLE
romhustler.org: badware

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18104]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Download is flagged as malicious, as well as the site itself.
https://www.virustotal.com/gui/url/12cf10bf584b5c06d91822e940a94d6701cb844b31210bcad9ab751c27cf9145
https://www.virustotal.com/gui/url/b11109a5ee964b1703e4fe9bc2eb7df3ca249e73a6e3b795d3b884f5340bd896

### URL(s) where the issue occurs.

`https://romhustler.org/rom/genesis/sonic-the-hedgehog-2`

### uBO version

v1.49.3b10

### Browser name and version

Firefox 113.0.1

### Settings

-Using custom filters, checking "I am an advanced user"

**Comment by stephenhawk8054** [comment]
The file downloaded contains a bunch of `.BIN` file in which I don't see any detections when scanning via virustotal and the URL is flagged by too few vendors (1).
