### ISSUE TITLE
smdyy1.cc: ads

### ISSUE THREAD

**Issue by Iovenoname** [uBlockOrigin/uAssets#18105]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.smdyy1.cc/`

### Category

ads

### Description

I am sorry to see that the obvious gambling site of this site is not blocked, I am worried that some people will fall into the trap of induced gambling and cannot extricate themselves, I hope to get a response

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 110320
 cosmetic: 49016
 scriptlet: 17545
 html: 945
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 33901-40, 1d.18h.18m
  ublock-badware: 7124-0, 1d.18h.18m
  ublock-privacy: 444-0, 1d.18h.18m
  ublock-abuse: 70-70, 1d.18h.18m
  ublock-unbreak: 2027-0, 1d.18h.18m
  ublock-quick-fixes: 290-31, 49m
  easylist: 65629-242, 1d.18h.18m
  easyprivacy: 32265-74, 1d.18h.17m
  urlhaus-1: 7455-1, 16h.42m
  plowe-0: 3737-941, 1d.18h.17m
  CHN-0: 26647-206, 1d.18h.19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1616 ms (selfie)
 maxAssetCacheWait: 231 ms
popupPanel: 
 blocked: 2
 network: 
  baidu.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@cjx82630 Sorry, can you take a look?

**Comment by cjx82630** [comment]
https://github.com/easylist/easylistchina/commit/5a92d11af339158e0dc18740d4b2d04db0664e03

**Comment by Iovenoname** [comment]
But I'm very happy to get a response, thank you
