### ISSUE TITLE
maxstream.video: detection

### ISSUE THREAD

**Issue by bunnytwotwo** [uBlockOrigin/uAssets#18101]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://maxstream.video/videostream/wafk1cavvg7h/062itp8aoa5n/amU3YXUyUWtNeDdnQmxmSkxqQVI3QT09`

### Category

detection

### Description

uBlock Origin deteced

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 100101
 cosmetic: 46564
 scriptlet: 17419
 html: 943
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 33908-78, 4m
  ublock-badware: 7073-1, 4m
  ublock-privacy: 443-0, 4m
  ublock-abuse: 70-70, 4m
  ublock-unbreak: 2026-2, 4m
  ublock-quick-fixes: 299-0, 4m
  easylist: 65802-652, 4m
  easyprivacy: 32146-614, 4m
  urlhaus-1: 7673-1, 4m
  plowe-0: 3737-2, 4m
  ITA-0: 13421-1, 4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 704 ms
 maxAssetCacheWait: 373 ms
popupPanel: 
 blocked: 8
 network: 
  googletagmanager.com: 2
  host-cdn.net: 1
  intellipopup.com: 1
  sonsbrunette.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the anti-adblock. Video appears and plays normally for me.
