### ISSUE TITLE
nopay.info: detection

### ISSUE THREAD

**Issue by Gythion** [uBlockOrigin/uAssets#18113]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nopay.info/`

### Category

detection

### Description

UBlock detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 100658
 cosmetic: 46496
 scriptlet: 17392
 html: 943
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 33887-78, 2d.24m
  ublock-badware: 7123-0, 2d.23m
  ublock-privacy: 444-0, 5d.14m
  ublock-abuse: 70-70, 5d.13m
  ublock-unbreak: 2026-1, 2d.22m
  ublock-quick-fixes: 299-0, 7h.45m
  easylist: 65530-644, 5d.7h.55m
  easyprivacy: 32121-615, 1d.22m
  urlhaus-1: 8396-1, 7h.45m
  plowe-0: 3737-4, 5d.15m
  ITA-0: 13421-1, 7h.45m
filterset (user): [empty]
trustedset: 
 added: [array of 20 redacted]
modifiedUserSettings: 
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1409 ms (selfie)
 maxAssetCacheWait: 868 ms
popupPanel: 
 blocked: 48
 network: 
  acacdn.com: 2
  addresseepaper.com: 2
  adsco.re: 1
  adsilo.net: 5
  amung.us: 3
  awstats.cloud: 2
  befirstcdn.com: 1
  blockadsnot.com: 1
  chpadblock.com: 2
  contentango.com: 12
  dismantlepenantiterrorist.com: 2
  dnhfi5nn2dt67.cloudfront.net: 1
  googlesyndication.com: 2
  histats.com: 1
  keidweneth.com: 1
  kingrecommendation.com: 3
  mckensecuryr.info: 1
  neitherpennylack.com: 2
  simplewebanalysis.com: 3
  zapprecisionadmire.com: 1
 cosmetic: 
  ##div[id][style^=\"position: fixed; inset: 0px; z-index: 2147483647; background: black\"][style*=\"opacity: 0.01\"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  ##[style=\"position:absolute;top:0;left:0;width: 100%;height: 100%;z-index:2147483647\"]
```
</details>

**Comment by mapx-** [comment]
- already fixed days ago
- update all your filter lists + disable other blocking addons / extensions
