### ISSUE TITLE
maxstream.video: detection

### ISSUE THREAD

**Issue by bunnytwotwo** [uBlockOrigin/uAssets#18115]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://maxstream.video/videostream/5zpo0zvmezzg/593j4aq3nnv7/cWhaeGpqZWh0Sk1waVhlMVZGQmNLUT09`

### Category

detection

### Description

Hi,
I'm using Firefox (the leatest version) and uBlock Origin. 
When I'm on maxstream the video appears, but a few seconds leater, the page shows a popup "disable your adblock please", then I must click "ok" and then the video disappears. 

Have you any solution?

I link you a screen recorder:
https://www.dropbox.com/s/3jrmnfqsfpcynsp/firefox.mp4?dl=0

Thanks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 100098
 cosmetic: 46564
 scriptlet: 17412
 html: 943
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 33908-78, 22h.37m
  ublock-badware: 7073-0, 22h.37m
  ublock-privacy: 443-0, 22h.37m
  ublock-abuse: 70-70, 22h.37m
  ublock-unbreak: 2026-2, 22h.37m
  ublock-quick-fixes: 289-0, 52m
  easylist: 65802-652, 22h.37m
  easyprivacy: 32146-614, 22h.37m
  urlhaus-1: 7673-1, 22h.37m
  plowe-0: 3737-3, 22h.37m
  ITA-0: 13421-1, 22h.37m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3584 ms (selfie)
 maxAssetCacheWait: 463 ms
popupPanel: 
 blocked: 8
 network: 
  ezcgojaamg.com: 1
  googletagmanager.com: 1
  host-cdn.net: 1
  intellipopup.com: 1
  sonsbrunette.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the anti adblock. The whole video plays fine for me.

**Comment by bunnytwotwo** [comment]
> I can't reproduce the anti adblock. The whole video plays fine for me.

Hi,
😟
what can I say: in maxstream allways was fine. But now the popup, for me, appears, but nothing I have changed. I really don't know.

**Comment by peace2000** [comment]
@stephenhawk8054 I can't access the site by default because this filter blocks it:

https://github.com/uBlockOrigin/uAssets/blob/f74450cf909c4dd760e18ad928b4bdd3665f2f8f/filters/filters-2021.txt#L3370

It has to be allowed in order to access it:

![kuva](https://github.com/uBlockOrigin/uAssets/assets/17256841/e1e47665-d083-4409-a7d2-c62c3881132b)

**Comment by stephenhawk8054** [comment]
@peace2000 It was added due to redirection to malicious site previously: https://github.com/uBlockOrigin/uAssets/issues/17542

Does it redirect you to the right link?

**Comment by peace2000** [comment]
Doesn't seem to. When I click continue... :

![kuva](https://github.com/uBlockOrigin/uAssets/assets/17256841/7b4f8f76-c1bb-43ef-aa91-4306359f9ac8)

**Comment by peace2000** [comment]
I guess what I'm trying to say is that if that site has malicious redirects, why this site isn't blocked as a badware in the first place?

**Comment by peace2000** [comment]
Ok now my IP got banned :)....

**Comment by stephenhawk8054** [comment]
As far as I understand, this site is used when clicking from other website to access (looks like it uses cookies). If you access from that link directly, sometimes it will redirect to the `getfile` page, depending on region/IP. Not everytime or every link has that.

And sorry I forgot to warn you that if you access that `getfile` page twice, they will ban your IP.

**Comment by peace2000** [comment]
Ok, well FInnish IP's don't seem to be welcome. Changed IP few times and they got banned.

**Comment by Porders** [comment]
Hi,
I gone to options, and I flagged advanced settings, and I cliccked to the gears icon near the option, and I set filterAuthorMode to true. Then I used the dynamic filtering like that:

https://www.dropbox.com/s/osu3ibdd2ca2toc/ojjHegIKNe.png?dl=0

and, for now, the popup is disappeard

**Comment by stephenhawk8054** [comment]
Don't use that in the left column. What is the original site that you use to access `maxstream.video`?

**Comment by Porders** [comment]
> Don't use that in the left column, you are allowing that ads domain to run on all of the other sites. What is the original site that you use to access `maxstream.video`?

Hi,
uprot.net

**Comment by stephenhawk8054** [comment]
It's an encrypt URL site for me. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/b1ff4dd4-be20-4b48-8cc7-b3d3409058a9

What should I do next?

**Comment by Porders** [comment]
> It's an URL encrypter site for me. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/b1ff4dd4-be20-4b48-8cc7-b3d3409058a9
> 
> What should I do next?

I don't if this link can help you:

https://maxstream.video/videostream/495ercnsdvor/qve86z6t9kkv/eFJOOEhZN0JHdzNkdlI0UndYT2tsZz09

**Comment by Porders** [comment]
> > It's an URL encrypter site for me. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/b1ff4dd4-be20-4b48-8cc7-b3d3409058a9
> > What should I do next?
> 
> I don't if this link can help you:
> 
> https://maxstream.video/videostream/495ercnsdvor/qve86z6t9kkv/eFJOOEhZN0JHdzNkdlI0UndYT2tsZz09

Sorry, this link:

https://uprot.net/msfi/QlBheEdvcUtuZ3FseDNxZm1rUkhJQT09

**Comment by stephenhawk8054** [comment]
Remove the dynamic filtering rules. Can you test this filter?

```adb
@@||host-cdn.net^$image,domain=maxstream.video
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > Click &#10003; `Apply changes` > Go back to the website > Press `Ctrl + Shift + R` to reload the page and test again.

**Comment by Porders** [comment]
> Remove the dynamic filtering rules. Can you test this filter?
> 
> ```
> @@||host-cdn.net^$image,domain=maxstream.video
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > Click ✓ `Apply changes` > Go back to the website > Press `Ctrl + Shift + R` to reload the page and test again.

So,
If I use your suggestion: 

@@||host-cdn.net^$image,domain=maxstream.video

in my filers and I reload the page, the popup reappears 

But if I use only:

maxstream.video ads.host-cdn.net * allow

in temporary rules, the popup does't show, if I reload the page

**Comment by Porders** [comment]
> Can you do these steps:
> 
>     * Click on ▤ ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger) on the [popup user interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface),
> 
>     * Reload the page and repeat the steps until issue happens,
> 
>     * Copy the logger via 📋 [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog),
> 
>     * Paste the logs here

Your filter:

@@||host-cdn.net^$domain=maxstream.video

works.

But you allow cdn.net in maxstream.

Can I post you the log in private, is it possible? And in which format, list, table, simple, markdown ?

**Comment by stephenhawk8054** [comment]
The log just contains what are being loaded, what are being blocked in that website. There's no personal information in there.

You can choose table and markdown.

**Comment by Porders** [comment]
> The log just contains what are being loaded, what are being blocked in that website. There's no personal information in there.
> 
> You can choose table and markdown.

Ok I post you the log here:




<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | ://ads.$~image,from=~ads.8designers.com\|~ads.ac.uk\|~ads.adstream.com.ro\|~ads.allegro.pl\|~ads.am\|~ads.amazon\|~ads.apple.com\|~ads.atmosphere.copernicus.eu\|~ads.band\|~ads.bestprints.biz\|~ads.bikepump.com\|~ads.brave.com\|~ads.buscaempresas.co\|~ads.colombiaonline.com\|~ads.comeon.com\|~ads.cs.washington.edu\|~ads.cvut.cz\|~ads.doordash.com\|~ads.elevateplatform.co.uk\|~ads.finance\|~ads.google.com\|~ads.gree.net\|~ads.gurkerl.at\|~ads.harvard.edu\|~ads.instacart.com\|~ads.jiosaavn.com\|~ads.kaipoke.biz\|~ads.kazakh-zerno.net\|~ads.kifli.hu\|~ads.knuspr.de\|~ads.lapalingo.com\|~ads.listonic.com\|~ads.lollipod.de\|~ads.magalu.com\|~ads.mba\|~ads.mercadolivre.com.br\|~ads.mgid.com\|~ads.microsoft.com\|~ads.midwayusa.com\|~ads.mobilebet.com\|~ads.msstate.edu\|~ads.mst.dk\|~ads.nc\|~ads.nimses.com\|~ads.nipr.ac.jp\|~ads.odesbuild.com\|~ads.olx.pl\|~ads.pinterest.com\|~ads.quasaraffiliates.com\|~ads.red\|~ads.rohlik.cz\|~ads.route.cc\|~ads.safi-gmbh.ch\|~ads.scotiabank.com\|~ads.selfip.com\|~ads.shopee.cn\|~ads.shopee.co.th\|~ads.shopee.com.br\|~ads.shopee.com.mx\|~ads.shopee.com.my\|~ads.shopee.kr\|~ads.shopee.ph\|~ads.shopee.pl\|~ads.shopee.sg\|~ads.shopee.tw\|~ads.shopee.vn\|~ads.smartnews.com\|~ads.snapchat.com\|~ads.socialtheater.com\|~ads.spotify.com\|~ads.studyplus.co.jp\|~ads.taboola.com\|~ads.tiktok.com\|~ads.typepad.jp\|~ads.us.tiktok.com\|~ads.viksaffiliates.com\|~ads.vk.com\|~ads.watson.ch\|~badassembly.com\|~caravansforsale.co.uk\|~fusac.fr\|~memo2.nl\|~reempresa.org\|~satmetrix.com\|~seriouswheels.com | -- | maxstream.video | 3 | get | script | `https://ads.host-cdn.net/stats.js` |
| +0 | noopjs | << | maxstream.video | 3 | get | script | `https://www.intellipopup.com/bootstrap-datetimepicker.min.js` |
| +0 | \|\|intellipopup.com^$script,redirect-rule=noopjs | -- | maxstream.video | 3 | get | script | `https://www.intellipopup.com/bootstrap-datetimepicker.min.js` |
| +0 | \|\|intellipopup.com^ | -- | maxstream.video | 3 | get | script | `https://www.intellipopup.com/bootstrap-datetimepicker.min.js` |
| +0 | \|\|sonsbrunette.com^ | -- | maxstream.video | 3 | get | script | `https://sonsbrunette.com/1d/d0/14/1dd0146c4a4882d691461eb0cbf00642.js` |
| +0 | \|\|sonsbrunette.com^ | -- | maxstream.video | 3 | get | script | `https://sonsbrunette.com/fa/2e/06/fa2e06205a3cace69875afa21901c178.js` |
| +0 | googletagmanager_gtm.js | << | maxstream.video | 3 | get | script | `https://www.googletagmanager.com/gtag/js?id=G-PXCHK654EC` |
| +0 | \|\|googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5 | -- | maxstream.video | 3 | get | script | `https://www.googletagmanager.com/gtag/js?id=G-PXCHK654EC` |
| +0 | \|\|googletagmanager.com^ | -- | maxstream.video | 3 | get | script | `https://www.googletagmanager.com/gtag/js?id=G-PXCHK654EC` |
| +0 | \|\|sonsbrunette.com^ | -- | maxstream.video | 3 | get | script | `https://sonsbrunette.com/1d/d0/14/1dd0146c4a4882d691461eb0cbf00642.js` |
| +0 | \|\|sonsbrunette.com^ | -- | maxstream.video | 3 | get | script | `https://sonsbrunette.com/fa/2e/06/fa2e06205a3cace69875afa21901c178.js` |
| +0 | ##+js(remove-attr, style, div[style="display: none;"]) |  | maxstream.video |  | get | dom | `https://maxstream.video/videostream/8ry9vxviw2am/qve86z6t9kkv/eFJOOEhZN0JHdzNkdlI0UndYT2tsZz09` |
| +0 | ##+js(window.open-defuser) |  | maxstream.video |  | get | dom | `https://maxstream.video/videostream/8ry9vxviw2am/qve86z6t9kkv/eFJOOEhZN0JHdzNkdlI0UndYT2tsZz09` |
| +0 | ##+js(nano-setTimeout-booster, .fadeIn(), 3000) |  | maxstream.video |  | get | dom | `https://maxstream.video/videostream/8ry9vxviw2am/qve86z6t9kkv/eFJOOEhZN0JHdzNkdlI0UndYT2tsZz09` |
| +0 | @@\|\|maxstream.video^$generichide | ++ | maxstream.video | 1 | get | generichide | `https://maxstream.video/videostream/8ry9vxviw2am/qve86z6t9kkv/eFJOOEhZN0JHdzNkdlI0UndYT2tsZz09` |
</details>

**Comment by stephenhawk8054** [comment]
Test

```adb
*$script,3p,redirect-rule=noopjs,domain=maxstream.video
```

If it doesn't work, the only way is allowing the `https://ads.host-cdn.net/stats.js`

```adb
@@||ads.host-cdn.net/stats.js$script,domain=maxstream.video
```

**Comment by Porders** [comment]
> Test
> 
> ```
> *$script,3p,redirect-rule=noopjs,domain=maxstream.video
> ```
> 
> If it doesn't work, the only way is allowing the `https://ads.host-cdn.net/stats.js`
> 
> ```
> @@||ads.host-cdn.net/stats.js$script,domain=maxstream.video
> ```



*$script,3p,redirect-rule=noopjs,domain=maxstream.video

doesn't work

But:

@@||ads.host-cdn.net/stats.js$script,domain=maxstream.video

works. In this way you enable the java script from cdn.net only for maxstream.video, right?

**Comment by stephenhawk8054** [comment]
Yes, it's for allowing that script only on `maxstream.video`. These might work without allowing that script

```adb
maxstream.video##+js(set, eerree, true)
maxstream.video##+js(set, e2e2e2e2, true)
maxstream.video##+js(set, e3e3e3e3, true)
```

But given that they likely use random variable, better way is to allow that script.

**Comment by Porders** [comment]
> ```
> maxstream.video##+js(set, eerree, true)
> maxstream.video##+js(set, e2e2e2e2, true)
> maxstream.video##+js(set, e3e3e3e3, true)
> ```




maxstream.video##+js(set, eerree, true)
maxstream.video##+js(set, e2e2e2e2, true)
maxstream.video##+js(set, e3e3e3e3, true)

works too. I don't know the syntax, but I understand variables "(set, xxxxxx, true)" (taken from the log?) are set to true, but also these may change in the future. So the better way is to allow the specific java script, as from log, for now

**Comment by Porders** [comment]
Thank you stephenhawk8054! And thank to all!
