### ISSUE TITLE
adblock detect on userstyles.org

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#18117]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

adblock detect on userstyles.org

### URL(s) where the issue occurs.

https://userstyles.org/

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/24896778/b70eeec7-da05-4527-b354-ca689bd08bad)

### uBO version

1.48.4

### Browser name and version

Cent Browser Version 5.0.1002.295 (Official Build) (64-bit) (Portable) (Chromium 102.0.5005.167)

### Settings

n/a

**Comment by krystian3w** [comment]
Maybe `@@||userstyles.org^$ghide`:

> 
> 
> ```js
> 'use strict';
> (self.webpackChunk_N_E = self.webpackChunk_N_E || [
> ]).push([[435],
> {
>   435: function (e, t) {
>     Object.defineProperty(t, '__esModule', {
>       value: !0
>     }),
>     t.AdblockDetector = void 0;
>     class n {
>       constructor() {
>         this.bannerIds = [
>           'AdHeader',
>           'AdContainer',
>           'AD_Top',
>           'homead',
>           'ad-lead'
>         ],
>         this.init()
>       }
>       init() {
>         let e = document.createElement('div');
>         e.innerHTML = this.generatesBannersString(),
>         document.body.appendChild(e)
>       }
>       detect() {
>         return !this.bannerIds.every(e=>this.checkVisibility(e))
>       }
>       generatesBannersString() {
>         return this.bannerIds.map(e=>`<div id="${ e }"></div>`).join('')
>       }
>       checkVisibility(e) {
>         let t = document.querySelector(`#${ e }`);
>         return t ? t.offsetParent : null
>       }
>     }
>     t.AdblockDetector = n,
>     t.default = new n
>   }
> }
> ]);
> ```
