### ISSUE TITLE
welovemanga.one: popups

### ISSUE THREAD

**Issue by frjoethesecond** [uBlockOrigin/uAssets#18116]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://welovemanga.one/`

### Category

popups

### Description

Blocked page is replacing the original page when a link is clicked in addition to opening a new tab which is also blocked.

Site was recently updated.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 95263
 cosmetic: 38790
 scriptlet: 17403
 html: 945
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 33921-71, 2d.10h.39m
  ublock-badware: 7124-1, 2d.10h.20m
  ublock-privacy: 444-0, 10d.22h.39m
  ublock-abuse: 70-70, 10d.17h.11m
  ublock-unbreak: 2023-2, 2d.14h.33m
  ublock-quick-fixes: 347-0, 2h.12m
  easylist: 65772-613, 1d.18h.55m
  easyprivacy: 32122-649, 1d.23h.34m
  urlhaus-1: 8396-1, 18h.14m
  plowe-0: 3742-2, 8d.9h.35m
filterset (user): [empty]
trustedset: 
 added: [array of 13 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 783 ms (selfie)
 maxAssetCacheWait: 350 ms
popupPanel: 
 blocked: 10
 network: 
  welovemanga.one: 1
  diclotrans.com: 2
  googletagmanager.com: 1
  highcpmrevenuenetwork.com: 1
  pubfuture.com: 2
  skiddyteapots.com: 1
  wpadmngr.com: 2
 cosmetic: 
  ##a[href^=\"https://www.highcpmrevenuenetwork.com/\"]
```
</details>

**Comment by frjoethesecond** [comment]
Can this be improved further? The website is replaced by a blocked ad notification when a link is clicked?

**Comment by stephenhawk8054** [comment]
I don't see any notification on the website. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/c8cb105f-4a30-4ea2-ab4c-b9a876e00a6c

**Comment by frjoethesecond** [comment]
> I don't see any notification on the website. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/c8cb105f-4a30-4ea2-ab4c-b9a876e00a6c

It doesn't look like you clicked on any links. You're still on the home page.

**Comment by stephenhawk8054** [comment]
I clicked on the links but nothing happens either. Video recording: https://github.com/uBlockOrigin/uAssets/assets/66517106/8ab544af-312d-4eea-a659-0dd3ad3a01be

**Comment by frjoethesecond** [comment]
Oh ok. Sorry to bother you about this so much. If I figure out what's causing this, I'll let you know. Have a good day.

**Comment by stephenhawk8054** [comment]
Have you forced update the filter lists yet?

**Comment by frjoethesecond** [comment]
Oh my god, how could I be so stupid? I thought I did, but apparently I didn't.

I'm so sorry for wasting your time.
