### ISSUE TITLE
gamestar.de: breakage

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#18118]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gamestar.de/videos/lego-2k-drive-ein-komplettes-rennen-im-herrlich-durchgeknallten-arcade-racer,124717.html`

### Category

breakage

### Description

While uBlock is active with default options / lists (only uBlock lists), the video won't play. With uBLock disabled the video will play (including the video ad at the beginning).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBlock:
![image](https://github.com/uBlockOrigin/uAssets/assets/14368203/c92a1d99-1688-430b-bda8-d0506a320d2c)

With uBlock disabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/14368203/19855c4b-b496-4e23-900e-30e2ad371c3b)

With uBlock disabled and after video ad, the actual video plays fine
![image](https://github.com/uBlockOrigin/uAssets/assets/14368203/677c2101-3f92-42fd-89b6-9f7554f09345)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 115
filterset (summary): 
 network: 15131
 cosmetic: 10249
 scriptlet: 17409
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  DEU-0: null
  easylist: null
  easyprivacy: null
  plowe-0: null
  urlhaus-1: null
 default: 
  user-filters: 0-0, never
  ublock-abuse: 70-0, now
  ublock-badware: 7094-0, now
  ublock-filters: 33016-36, 2d.13h.5m
  ublock-privacy: 392-70, now
  ublock-quick-fixes: 345-29, now
  ublock-unbreak: 2016-1, now
filterset (user): [empty]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 366 ms (selfie)
 maxAssetCacheWait: 196 ms
popupPanel: 
 blocked: 7
 network: 
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  outbrain.com: 1
  scorecardresearch.com: 1
  smartadserver.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=gamestar.de
```

I guess it can fixed in EL Germany, but I'm not sure who to cc?

**Comment by JobcenterTycoon** [comment]
@khrin
