### ISSUE TITLE
adventuresro.com: badware

### ISSUE THREAD

**Issue by AdventuresRO** [uBlockOrigin/uAssets#18111]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I am writing to you on behalf of the Adventures RO Staff (`www.adventuresro.com`) because we have noticed that for at least one day our website is on your list of potentially dangerous sites, which is why many of our visitors are receiving security warnings.

Before recommending to our user base to uninstall your widget, I would like to request that you please provide me with the reasons why our website has been listed. We believe that it is an erroneous inclusion, but if not, please provide us with details of the security protocols that our website is not complying with.

### URL(s) where the issue occurs.

`http://adventuresro.com/`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/95154880/7add7787-0fe6-4ac9-ba3a-89572e0cf515)

![image](https://github.com/uBlockOrigin/uAssets/assets/95154880/46d03995-84a0-496c-af81-18992a6781d0)

### uBO version

1.49.2

### Browser name and version

Version 113.0.5672.93 

### Settings

NONE

**Comment by JobcenterTycoon** [comment]
See here: https://urlhaus.abuse.ch/url/2634722/

**Comment by AdventuresRO** [comment]
That was a WordPress file in to **https://adventuresro.com/am/?1** I removed it, how can request a re-scan?

**Comment by stephenhawk8054** [comment]
You should contact URLhaus, as seen in the link @JobcenterTycoon gave above. uBO just blocks based on what the list has.

(And from urlhaus results, looks like you should contact with other vendors too: spamhaus, quad9, cloudflare... are all categorize your site as malicious).

**Comment by JobcenterTycoon** [comment]
URLhaus should mark this as offline in the next 10 minutes. If not you can contact them.

Important: The website need to be secured to prevent a new infection.

**Comment by AdventuresRO** [comment]
now is already offline, does can be enough ? 
![image](https://github.com/uBlockOrigin/uAssets/assets/95154880/972ee1d5-5ac5-46c5-9fcf-adfd4808d2d0)

**Comment by stephenhawk8054** [comment]
You can force update the filter lists and test again.
