### ISSUE TITLE
dwindly.io [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1811]
URL(s) where the issue occurs

`https://dwindly.io/9mpaz`

Describe the issue

Pop-up

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
Pop-up

**Comment by mapx-** [comment]
Test
```
dwindly.io##+js(abort-on-property-write.js, Fingerprint2)
dwindly.io###frme1
*$subdocument,domain=dwindly.io
```
