### ISSUE TITLE
vlr.gg: ads

### ISSUE THREAD

**Issue by cptlewenko** [uBlockOrigin/uAssets#18127]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.vlr.gg/`

### Category

ads

### Description

GG bet advertisement visible on home page, clicking sends you off site
![2023-05-19_10-32-11](https://github.com/uBlockOrigin/uAssets/assets/133869360/3de6251d-6ef7-4c63-8316-150252fc8f1b)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 102409
 cosmetic: 108240
 scriptlet: 23200
 html: 1113
listset (total-discarded, last-updated): 
 added: 
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 952-0, 1h.17m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2186-0, 1h.17m
  fanboy-annoyance: 90546-15615, 1h.17m
  ublock-annoyances: 5033-4, 1h.17m
 default: 
  user-filters: 37-0, never
  ublock-filters: 33880-78, 1h.17m
  ublock-badware: 7103-0, 1h.17m
  ublock-privacy: 442-2, 1h.17m
  ublock-abuse: 70-70, 1h.17m
  ublock-unbreak: 2031-1, 1h.17m
  ublock-quick-fixes: 353-0, 1h.17m
  easylist: 65956-653, 1h.17m
  easyprivacy: 31822-616, 1h.17m
  urlhaus-1: 8009-1, 1h.17m
  plowe-0: 3737-4, 1h.17m
filterset (user): [array of 36 redacted]
hostRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2151 ms
 maxAssetCacheWait: 15 ms
popupPanel: 
 blocked: 2
 network: 
  googletagmanager.com: 1
  nitropay.com: 1
 cosmetic: 
  ##.mod-twitter
```
</details>

**Comment by cptlewenko** [comment]
This ad has returned again. Is it best to post here so that it references the correct filter list URL or create a new "issue"?

**Comment by mapx-** [comment]
It's enough commenting here, no need to open a new issue.

**Comment by casualsam** [comment]
<img width="1160" height="689" alt="Image" src="https://github.com/user-attachments/assets/f93098b7-61df-4869-a98e-56d8fb2a9cdd" />

Ads for gambling are back, and labeled as "Advertisement". Element Remover is able to disable, but does not persist on uBO-lite
