### ISSUE TITLE
azlyrics.com: ad placeholders

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18128]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad placeholders, already fixed by AdGuard Base.
`azlyrics.com##.lboard-wrap`
`azlyrics.com##.ringtone`
`azlyrics.com##.noprint:has(> span[id^="cf_async_"])`
Original issue:
https://github.com/easylist/easylist/issues/15488

### URL(s) where the issue occurs.

`https://www.azlyrics.com/lyrics/elliegoulding/gunsandhorses.html`

### Screenshot(s)

![Screenshot from 2023-05-18 18-48-24](https://github.com/uBlockOrigin/uAssets/assets/89158249/f869f29b-7ba6-4879-a2d8-b2cf8e30782f)
![Screenshot from 2023-05-18 18-48-29](https://github.com/uBlockOrigin/uAssets/assets/89158249/678bd1a4-f69f-41f8-8f34-00239845aedf)

### uBO version

v1.49.3b12

### Browser name and version

Firefox 113.0.1

### Settings

- Use custom filters/filter lists, checking "I am an advanced user"

**Comment by mapx-** [comment]
Any filters included in uBO's filter lists must use the [extended syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#extended-syntax).

**Comment by krystian3w** [comment]
Vs:

> uAssets will fix the following exceptions even if they do not require using the extended syntax
