### ISSUE TITLE
Navigation buttons disappeared from forums

### ISSUE THREAD

**Issue by MaximusPanin** [uBlockOrigin/uAssets#18126]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hi.
Navigation buttons disappeared from forums. What parameter is responsible for this ?

![2023-5-18 22-26-12](https://github.com/uBlockOrigin/uBlock-issues/assets/24373505/a49e6984-78fc-4ea6-8d7c-081e9967d7f0)

![2023-5-18 22-37-13](https://github.com/uBlockOrigin/uBlock-issues/assets/24373505/7e774782-c720-4240-98ff-a2693035055b)

### A specific URL where the issue occurs.

https://forum.doctorhead.ru

### Steps to Reproduce

Many forums don't have navigation buttons.

### Expected behavior

Normal navigation display

### Actual behavior

Many forums don't have navigation buttons.

### Configuration

uBlock Origin: 1.49.2
Chromium: 102
filterset (summary): 
 network: 25462
 cosmetic: 17482
 scriptlet: 18388
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  easylist: null
  easyprivacy: null
  plowe-0: null
  ublock-abuse: null
  ublock-badware: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
  urlhaus-1: null
 default: 
  user-filters: 18925-21, never
  RUS-0: 39772-21129, 2h.7m
  ublock-filters: 33008-9208, 1h.47m
filterset (user): [array of 16428 redacted]
trustedset: 
 added: [array of 51 redacted]
switchRuleset: 
 added: [array of 35 redacted]
hostRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 contextMenuEnabled: false
 largeMediaSize: 1
 parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 12373 ms (selfie)
 maxAssetCacheWait: 3198 ms

**Comment by mapx-** [comment]
`user-filters: 18925-21, never`
all default lists removed ?!

- your uBO configuration is a very personalized one
- reset / reinstall uBO
