### ISSUE TITLE
firstonetv.net [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1812]
URL(s) where the issue occurs

`https://www.firstonetv.net/Live/Spain/Antena-3-30`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by lain566** [comment]
Anti adblock
`https://www.firstonetv.live/Live/Germany/Das-Erste-1`

**Comment by mapx-** [comment]
Even disabling uBo I get ad after ad, no real channel for me. Could be a scam site now ?!

**Comment by lain566** [comment]
Yes, that seems, I had not checked it with uBO disabled
