### ISSUE TITLE
finviz.com: ads

### ISSUE THREAD

**Issue by kingcong1** [uBlockOrigin/uAssets#18137]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://finviz.com/`

### Category

ads

### Description

Finviz has internal ads showing up as banner ads on top of the website as well as throughout any filtered lists

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70293657/647b0540-50f1-4238-b931-68b58fc2a430)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94438
 cosmetic: 38771
 scriptlet: 17399
 html: 945
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  ublock-filters: 33921-71, 4d.2h.8m
  ublock-badware: 7083-0, 2d.2h.5m
  ublock-privacy: 444-0, 4d.2h.8m
  ublock-abuse: 70-70, 4d.2h.8m
  ublock-unbreak: 2027-2, 2d.2h.6m
  ublock-quick-fixes: 306-0, 2h
  easylist: 65652-644, 4d.2h.8m
  easyprivacy: 31825-616, 2h.1m
  urlhaus-1: 8043-1, 15h.24m
  plowe-0: 3737-3, 2d.3m
filterset (user): [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2521 ms
 maxAssetCacheWait: 549 ms
popupPanel: 
 blocked: 4
 network: 
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  investingchannel.com: 1
```
</details>

**Comment by mapx-** [comment]
It's self-promotion.
Use the element picker ig you still use to hide it.
