### ISSUE TITLE
works.do: badware

### ISSUE THREAD

**Issue by catrius** [uBlockOrigin/uAssets#18133]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`works.do` is considered as a Badware. May I know the reason?
Ublock recognizes `works.do` as a badware. AFAIN, this is a domain from Line Work. I don't think it has any problem.

### URL(s) where the issue occurs.

`https://works.do`

### uBO version

1.49.2

### Browser name and version

Google Chrome Version 113.0.5672.126 (Official Build) (x86_64)

### Settings

None

**Comment by okiehsch** [comment]
Looks fine on my end.
@Yuki2718 what was the reason for the block?

**Comment by Yuki2718** [comment]
Some of urls e.g. `https://works[.]do/R/ti/p/yukarin_kokko@partybell`, `https://works[.]do/R/ti/p/aaa_ka@slow-r` are used to lure user to fake dating sites, but I should have checked legitimate use.
