### ISSUE TITLE
linkneverdie.net: detection

### ISSUE THREAD

**Issue by nakhoacool** [uBlockOrigin/uAssets#18130]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkneverdie.net/`

### Category

detection

### Description

The site detects ad block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94066
 cosmetic: 38738
 scriptlet: 17432
 html: 942
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 33883-76, 1m
  ublock-badware: 7103-1, 1m
  ublock-privacy: 442-0, 1m
  ublock-abuse: 70-70, 1m
  ublock-unbreak: 2031-2, now
  ublock-quick-fixes: 353-0, now
  easylist: 65960-652, now
  easyprivacy: 31825-615, now
  urlhaus-1: 7343-1, now
  plowe-0: 3737-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1182 ms
 maxAssetCacheWait: 7 ms
popupPanel: 
 blocked: 7
 network: 
  addthis.com: 1
  dooloust.net: 1
  facebook.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  optad360.io: 1
  quantumdex.io: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `VIE: ABPVN List` in "Filter Lists" pane and test again?

**Comment by nakhoacool** [comment]
> Can you enable `VIE: ABPVN List` in "Region" section of "Filter Lists" pane and test again?

When I enable the filter, it shows a gray overlay instead of the warning "Please disable ad block"
![Screenshot 2023-05-19 130608](https://github.com/uBlockOrigin/uAssets/assets/77623180/f84e9a1b-5be4-431d-baf8-a1cf67101674)

**Comment by stephenhawk8054** [comment]
@hoang-rio Sorry, can you take a look?

**Comment by mapx-** [comment]
add

```
linkneverdie.net##.show.fade.modal-backdrop
linkneverdie.net##body:style(overflow: auto !important;)
```
