### ISSUE TITLE
amazon.com: ads

### ISSUE THREAD

**Issue by liaffeb** [uBlockOrigin/uAssets#18132]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.amazon.com/Smoke-Gets-in-Your-Eyes/dp/B001A5HBAG/ref=sr_1_1?crid=3VUM6TW3890P8&keywords=mad+men&qid=1684483660&s=instant-video&sprefix=mad+men%2Cinstant-video%2C86&sr=1-1`

### Category

ads

### Description

plays mid show ads on prime video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94989
 cosmetic: 38773
 scriptlet: 17438
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  easylist: 65772-47, 23h.45m
  easyprivacy: 32263-46, 5d.2h.58m
  plowe-0: 3742-937, 8d.4h.6m
  ublock-abuse: 70-0, 23h.45m
  ublock-badware: 7069-127, 2d.1h.42m
  ublock-filters: 33036-96, 2d.1h.40m
  ublock-privacy: 392-73, 23h.45m
  ublock-quick-fixes: 351-31, 8m
  ublock-unbreak: 2015-41, 2d.1h.39m
  urlhaus-1: 8043-1, 23h.45m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 165 ms (selfie)
 maxAssetCacheWait: 83 ms
popupPanel: 
 blocked: 633
 network: 
  amazon.com: 552
  aiv-delivery.net: 76
  amazon-adsystem.com: 3
  d2ef20sk9hi1u3.cloudfront.net: 1
  dr3fr5q4g2ul9.cloudfront.net: 1
 cosmetic: 
  ###nav-swmslot
```
</details>

**Comment by mapx-** [comment]
duplicate, one of them: https://github.com/uBlockOrigin/uAssets/issues/14512

@okiehsch maybe you still have such an account for prime ?

**Comment by okiehsch** [comment]
I have a prime account, but they are country specific, meaning I can't watch and check the video of the OP.
I ddi not notice any mid roll ads on my account lately.

**Comment by Yuki2718** [comment]
@liaffeb Does enabling AdGuard  - Ads fix that without side effect?

**Comment by mapx-** [comment]
or @liaffeb you could test

```
amazon.com##+js(xml-prune, Period:\has([value="Ad"]), , .mpd)
amazon.com##+js(json-prune, cuepointPlaylist)
```
