### ISSUE TITLE
thestar.com.my: Overlay pop-up

### ISSUE THREAD

**Issue by pubct** [uBlockOrigin/uAssets#18134]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There's an overlay that comes up once the cursor went outside of the webpage.

### URL(s) where the issue occurs.

Example article link
`https://www.thestar.com.my/business/business-news/2023/05/19/dollar-gains-as-debt-deal-hopes-rekindle-hawkish-fed-bets`

### uBO version

1.49.2

### Browser name and version

Chrome 113

### Settings

-

### Notes

Disclosure: I did not do the reproduction steps above.
Thanks.

**Comment by pubct** [comment]
A pop-up shows up when you reach the end of the article. Below is the troubleshooting information in Incognito Window. Thanks.
<details>
<summary>Troubleshooting information</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 106920
 cosmetic: 44177
 scriptlet: 19738
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 76133-16, now
  easyprivacy: 33135-65, now
  plowe-0: 3782-1151, now
  ublock-badware: 7643-138, now
  ublock-filters: 36467-345, now
  ublock-privacy: 951-12, now
  ublock-quick-fixes: 103-5, now
  ublock-unbreak: 2176-32, now
  urlhaus-1: 12355-0, now
filterset (user): [array of 146 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 535 ms
 maxAssetCacheWait: 235 ms
popupPanel:
 blocked: 12
 network:
  adbro.me: 2
  addthis.com: 1
  cxense.com: 2
  doubleclick.net: 1
  googletagmanager.com: 1
  netcore.co.in: 1
  outbrain.com: 1
  pubmatic.com: 1
  scorecardresearch.com: 1
  sharethis.com: 1
 extended:
  ##.ads
  ##.leaderboard
  ##.med-rec
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.Ads-slot
  ##.inlineAd
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by pubct** [comment]
Lemme try pinging one more time before attempting to create a new issue.

**Comment by mapx-** [comment]
> A pop-up shows up when you reach the end of the article.

provide screenshot

**Comment by pubct** [comment]
<details>
<Summary>Here's the screenshot.</summary>

![popup](https://github.com/uBlockOrigin/uAssets/assets/132225622/e556938e-eb49-4a39-b748-2fa1d7d68be0)
</details>

Thanks ya.

**Comment by mapx-** [comment]
add

`thestar.com.my##.freeModal`

@ryanbr @Alex-302

**Comment by pubct** [comment]
Works. Tyvm.
