### ISSUE TITLE
navigator.gmx.net: breakage

### ISSUE THREAD

**Issue by zinalili** [uBlockOrigin/uAssets#18145]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://navigator.gmx.net/mail?sid=fa603bcb7c9bd4f6d09539fab6f2fce01a3fd4e603c77fb0e266cf75d2abcbb767ff76f12d0b1be402bf099f84bd0d38`

### Category

breakage

### Description

Every time I click on any of my mail folders an error occures
**"Es ist ein technischer Fehler aufgetreten.
Id: db0d362f-2c89-55d7-7bdc-181f5a588e39"**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 113
filterset (summary): 
  network: 94410
  cosmetic: 59095
  scriptlet: 18469
  html: 902
listset (total-discarded, last-updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    urlhaus-1: null
    plowe-0: null
  added: 
    RUS-0: 39780-148, 8m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33921-41, 4d.19h.51m
    ublock-unbreak: 2027-0, 2d.15h.32m
    easylist: 65796-189, 2d.15h.31m
    easyprivacy: 31841-27, 2d.15h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  collapseBlocked: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1163 ms (selfie)
  maxAssetCacheWait: 648 ms
popupPanel: 
  blocked: 144
  blockedDetails: 
    gmx.net: 34
    360yield.com: 3
    3lift.com: 3
    adform.net: 4
    adition.com: 5
    adnxs.com: 6
    adsrvr.org: 3
    amazon-adsystem.com: 5
    casalemedia.com: 3
    criteo.com: 5
    criteo.net: 2
    g-ha-1und1.de: 23
    indexww.com: 5
    openx.net: 3
    otto.de: 3
    pbstck.com: 5
    pubmatic.com: 3
    rubiconproject.com: 3
    smartadserver.com: 3
    tifbs.net: 1
    ui-portal.de: 2
    uicdn.com: 2
    uimserv.net: 5
    yieldlab.net: 13
```
</details>

**Comment by zinalili** [comment]
no such problem in Vivaldi (Chromium)

**Comment by mapx-** [comment]
@zinalili follow ALL these steps:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by zinalili** [comment]
I will use a browser other than Firefox to open this site. That'll do it. Thank you.
