### ISSUE TITLE
watch.spectrum.net: ads

### ISSUE THREAD

**Issue by beansuss** [uBlockOrigin/uAssets#18142]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://watch.spectrum.net/ondemand/play/comedycentral.com::XPMV0000000002907607`

### Category

ads

### Description

still forces ads in middle of video

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 94616
 cosmetic: 38782
 scriptlet: 17411
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65792-47, 2d.6h.41m
  easyprivacy: 31822-46, 1d.21m
  plowe-0: 3737-938, 3d.1h.34m
  ublock-abuse: 70-0, 2d.48m
  ublock-badware: 7119-128, 4d.4h
  ublock-filters: 33015-97, 4d.3h.59m
  ublock-privacy: 392-74, 2d.47m
  ublock-quick-fixes: 352-32, 6h.57m
  ublock-unbreak: 2020-41, 13m
  urlhaus-1: 8043-1, 22h.20m
filterset (user): [empty]
trustedset: 
 added: [array of 24 redacted]
 removed: 
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 16541 ms (selfie)
 maxAssetCacheWait: 2299 ms
popupPanel: 
 blocked: 186
 network: 
  spectrum.net: 185
  imrworldwide.com: 1
 cosmetic: 
  ##.ad-break
```
</details>

**Comment by mapx-** [comment]
@beansuss 

Can you provide a link to a free show that does not require a subscription?

otherwise:
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)
