### ISSUE TITLE
ynet.co.il: ads

### ISSUE THREAD

**Issue by shaked6540** [uBlockOrigin/uAssets#18140]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ynet.co.il/vacation/israeltrips/article/h1l5rnhfrn`

### Category

ads

### Description

Started seeing ads on the side of the page, the ads are not clickable and I couldn't find them in element picker. I suspect its a background image

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://github.com/uBlockOrigin/uAssets/assets/13851815/f3db6e4d-1dbf-4f8e-b6d9-d8e52bfd7c00)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 177996
 cosmetic: 224985
 scriptlet: 40088
 html: 1125
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7250-0, 1d.6h.39m
  https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, 13m
  https://winhelp2002.mvps.org/hosts.txt: 8729-315, 14m
  https://www.fanboy.co.nz/enhancedstats.txt: 2988-11, 15m
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 40822-830, 3d.6h.58m
  adguard-generic: 70983-6150, 3d.6h.59m
  adguard-mobile: 8754-154, 3d.6h.59m
  adguard-spyware-url: 1027-5, 3d.6h.59m
  block-lan: 47-0, 3d.6h.59m
  adguard-annoyance: 68205-5312, 3d.6h.59m
  adguard-social: 20462-691, 3d.6h.58m
  fanboy-thirdparty_social: 69-0, 2d.6h.53m
  fanboy-annoyance: 90878-80595, 6d.5h.14m
  fanboy-cookiemonster: 47146-266, 22h.47m
  fanboy-social: 16542-20, 2d.16h.58m
  ublock-annoyances: 4948-9, 2d.16h.57m
  dpollock-0: 11357-1738, 9d.22h
  ISR-0: 1719-2, 11m
 default: 
  user-filters: 153-6, never
  ublock-filters: 33901-143, 3d.6h.59m
  ublock-badware: 7103-5, 22h.46m
  ublock-privacy: 444-0, 3d.6h.59m
  ublock-abuse: 70-70, 3d.6h.59m
  ublock-unbreak: 2031-2, 22h.45m
  easylist: 65772-1019, 2d.2h.53m
  easyprivacy: 31825-13853, 16m
  urlhaus-1: 7413-1, 12m
  plowe-0: 3737-1747, 3d.6h.59m
  ublock-quick-fixes: 354-1, 10m
filterset (user): [array of 153 redacted]
trustedset: 
 added: [array of 15 redacted]
 removed: 
  chrome-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset: 
 added: [array of 10 redacted]
hostRuleset: 
 added: [array of 4 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
modifiedHiddenSettings: 
 autoUpdatePeriod: 7
 cloudStorageCompression: false
 selfieAfter: 11
supportStats: 
 allReadyAfter: 469 ms (selfie)
 maxAssetCacheWait: 177 ms
popupPanel: 
 blocked: 51
 network: 
  ynet.co.il: 5
  brandmetrics.com: 1
  browsiprod.com: 1
  chartbeat.com: 1
  cloudflareinsights.com: 2
  d1clufhfw8sswh.cloudfront.net: 2
  datadoghq.com: 1
  doubleclick.net: 1
  exelator.com: 1
  exposebox.com: 6
  firstimpression.io: 1
  flowplayer.com: 2
  google.com: 1
  googletagmanager.com: 2
  gstatic.com: 1
  infogram.com: 1
  npttech.com: 1
  permutive.com: 1
  spot.im: 10
  taboola.com: 2
  tinypass.com: 1
  upapi.net: 2
  valuad.cloud: 1
  yit.co.il: 4
 cosmetic: 
  ##.top-ad
  ##.followUsLinks
  ##.followUs
  ##.taboola-general
  ###fbShare
  ###twShare
  ##.google-adsense
  ##.grecaptcha-badge
  ##iframe
  ###ads\\.top
  ##.banner.layoutItem
  ##button[class^=\"shareIcon\"]
  ###blanket:empty
```
</details>

**Comment by shaked6540** [comment]
Upon inspecting the page I found this div, which seems to have some sort of a property for ad-block detection:
![image](https://github.com/uBlockOrigin/uAssets/assets/13851815/88609402-1bdc-4a14-b71a-7723014847ac)


So it might be detecting it somehow

**Comment by shaked6540** [comment]
Sorry for all the comments, but it looks like it is a background image. Here is the link to it: https://ynet-pic1.yit.co.il/picserver5/wcm_upload/2023/05/17/rkC0000BzSn/___.png

For now I manually added the domain to block list

**Comment by mapx-** [comment]
Report here 
https://github.com/easylist/EasyListHebrew/issues
