### ISSUE TITLE
scarysymptoms.com

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18146]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There is an anti-right click script on the site

### URL(s) where the issue occurs.

`https://scarysymptoms.com/2014/08/6-reasons-for-tall-women-to-date-shor/`

### uBO version

v1.49.3b12

### Browser name and version

Firefox 113.0.1

### Settings

- Using custom filter lists, checking "I am an advanced user"

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`
