### ISSUE TITLE
jiocinema.com: ads

### ISSUE THREAD

**Issue by gourab21** [uBlockOrigin/uAssets#18149]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jiocinema.com/sports/dc-vs-csk/3748624`

### Category

ads

### Description

This website shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93993
 cosmetic: 38780
 scriptlet: 17421
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65792-47, 2d.1h.43m
  easyprivacy: 31825-46, 21h.46m
  plowe-0: 3742-938, 11d.3h.31m
  ublock-abuse: 70-0, 11d.3h.29m
  ublock-badware: 7120-128, 4d.2h.25m
  ublock-filters: 33025-97, 4d.2h.20m
  ublock-privacy: 394-75, 11d.3h.30m
  ublock-quick-fixes: 351-32, 8m
  ublock-unbreak: 2015-41, 4d.2h.21m
  urlhaus-1: 7413-1, 23h.47m
filterset (user): [empty]
trustedset: 
 added: [array of 8 redacted]
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 680 ms (selfie)
 maxAssetCacheWait: 324 ms
popupPanel: 
 blocked: 54
 network: 
  go-mpulse.net: 2
  googletagmanager.com: 2
  impression.link: 1
  litix.io: 1
  mercury.akamaized.net: 2
  mparticle.com: 45
  serving-sys.com: 1
```
</details>

**Comment by mapx-** [comment]
Every link / page seems broken even disabling uBO

`Oops! Failed to play content.`

**Comment by ghajini** [comment]
@gourab21 
update filters in 5-10 mins & if you still see ads ,report here

**Comment by mapx-** [comment]
Indian ip necessary.

**Comment by ghajini** [comment]
how's `/jioads/*$script,domain=jiocinema.com`

`https://mercury.akamaized.net/jioads/websdk/default/spot_ads/1_15_16/jioAds.js`
