### ISSUE TITLE
arkadium.com: detection

### ISSUE THREAD

**Issue by kigomakid** [uBlockOrigin/uAssets#18144]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.arkadium.com/games/price-is-right-plinko/?playAgain=`

### Category

detection

### Description

Video game website that now recognizes ad blocker and wont allow playing without agreeing to remove the blocker when signed in.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2023-05-19 at 6 40 40 PM](https://github.com/uBlockOrigin/uAssets/assets/134111269/e01905e8-9d76-4f1b-b621-4ac06479fa20)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94165
 cosmetic: 38747
 scriptlet: 17451
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-1, never
  easylist: 65983-47, 2m
  easyprivacy: 31825-46, 2m
  plowe-0: 3735-938, 2m
  ublock-abuse: 70-0, 2m
  ublock-badware: 7098-127, 2m
  ublock-filters: 33038-103, 2m
  ublock-privacy: 392-74, 2m
  ublock-quick-fixes: 352-38, 2m
  ublock-unbreak: 2020-41, 2m
  urlhaus-1: 7413-1, 2m
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 129 redacted]
 removed: 
  edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 218 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel: 
 blocked: 84
 network: 
  1rx.io: 1
  33across.com: 5
  360yield.com: 11
  3lift.com: 4
  a-ads.com: 1
  a-mo.net: 1
  adlightning.com: 1
  adnxs.com: 4
  amazon-adsystem.com: 1
  appsflyer.com: 1
  casalemedia.com: 2
  doubleclick.net: 1
  facebook.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  hotjar.com: 1
  id5-sync.com: 1
  indexww.com: 3
  lijit.com: 2
  media.net: 2
  minutemedia-prebid.com: 1
  msecnd.net: 1
  openx.net: 4
  pubmatic.com: 5
  pushengage.com: 2
  quantserve.com: 1
  rubiconproject.com: 7
  smartadserver.com: 5
  spot.im: 5
  teads.tv: 2
  unrulymedia.com: 1
  visualstudio.com: 1
  yellowblue.io: 2
 cosmetic: 
  ##.display-ad
  ##div[class^=\"Ad-adContainer\"]
  ##div[class^=\"GameTemplate-gameAreaTopAdContainer\"]
  ##[class^=\"DisplayAd\"]
  #@#display-ad-component
```
</details>

**Comment by awholemystery** [comment]
adguard has fixed that:
```
arkadium.com#%#//scriptlet('set-constant', '__INITIAL_STATE__.gameLists.gamesNoPrerollIds.indexOf', 'trueFunc')
```
