### ISSUE TITLE
skytils.net, skyblockmaniacs.net, fragbots.net: badware

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [uBlockOrigin/uAssets#18141]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Phishing domains of `skytils.gg`, `sbm.gg` ,and `fragbots.xyz` 
[skytils[dot]net URLScan](https://urlscan.io/result/bff466d4-bb69-4304-9c47-3d349be15ede/) 
[skyblockmaniacs[dot]net URLScan](https://urlscan.io/result/75996add-3407-4c18-9ba9-77cc4469a97a/)
[fragbots[dot]net URLScan](https://urlscan.io/result/f083fe38-18d3-470d-8ed3-412f175f185b)

The `/verify` path on all these domains leads to a Microsoft OAuth2 page which requests the user grant access to their Minecraft account access token. 

URL is distributed through Discord userbots that DM on join.

### URL(s) where the issue occurs.

`https://skytils.net/verify`
`https://skyblockmaniacs.net/verify`
`https://fragbots.net/verify`

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Brave 1.51.118, Chromium 113.0.5672.126

### Settings

- Custom Filter Lists

**Comment by gorhill** [comment]
You should submit these to <https://urlhaus.abuse.ch/browse/>.

**Comment by iam-py-test** [comment]
> You should submit these to https://urlhaus.abuse.ch/browse/.

FYI:
> URLhaus is currently only collecting websites (URLs) that are directly being used to distribute malware.

**Comment by gorhill** [comment]
For phishing [Phishing URL Blocklist](https://gitlab.com/malware-filter/phishing-filter#issues) says:

> Please report new phishing URL to [PhishTank](https://www.phishtank.com/add_web_phish.php) or [OpenPhish](https://openphish.com/faq.html).
