### ISSUE TITLE
mobile01.com: popups

### ISSUE THREAD

**Issue by pupuwan** [uBlockOrigin/uAssets#18157]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.mobile01.com/hottopics.php`

### Category

App link popups

### Description

Add this filter list below still popup...

```
m.mobile01.com##.app-btn
m.mobile01.com##.app-close-btn
m.mobile01.com##[href^="https://mobile01app.page.link/"] > span
||attach2.mobile01.com/images/app/app_icon_android.png$image
m.mobile01.com##[href^="https://mobile01app.page.link/"]
```

https://github.com/uBlockOrigin/uAssets/assets/134182836/4267a823-37cc-4007-b38d-ec4121dda198

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 113
filterset (summary): 
 network: 111040
 cosmetic: 38091
 scriptlet: 17669
 html: 942
listset (total-discarded, last-updated): 
 default: 
  user-filters: 20-0, never
  ublock-filters: 34221-373, 2h.39m
  ublock-badware: 7137-0, 2h.39m
  ublock-privacy: 442-1, 2h.39m
  ublock-abuse: 70-70, 2h.39m
  ublock-unbreak: 2036-1, 2h.39m
  ublock-quick-fixes: 352-1, 2h.39m
  adguard-mobile: 8777-121, 2h.39m
  easylist: 65907-17519, 2h.39m
  easyprivacy: 31844-623, 2h.39m
  urlhaus-1: 6712-1, 2h.39m
  plowe-0: 3735-4, 2h.39m
  CHN-0: 26770-1416, 2h.39m
filterset (user): [array of 20 redacted]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1159 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel: 
 blocked: 9
 network: 
  mobile01.com: 5
  app.link: 3
  doubleclick.net: 1
 cosmetic: 
  ##body:style(overflow: visible!important;)
  ##body:style(overflow: visible!important;)
```
</details>

**Comment by mapx-** [comment]
report here:
https://github.com/cjx82630/cjxlist/issues
