### ISSUE TITLE
https://movies2watch.ru/

### ISSUE THREAD

**Issue by Eriklinuxuser** [uBlockOrigin/uAssets#18158]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [x] using a new, unmodified browser profile.

### Description

This script from the default ubo filter: **uBlock filters – Ads**, breaks the website: **`https://movies2watch.ru/`**

`adblockstreamtape.*,adblockstrtape.*,adblockstrtech.*,cablegratis.online,extralinks.*,filmypur.*,kmo.to,**movies2watch.***,nuroflix.*,onifile.com,oxanime.com,pelis28.*,pelisplusgo.*,pelisplusxd.*,pewgame.com,piraproxy.app,repelisgoo.*,repelisgooo.*,repelisgt.*,repelisxd.*,sexphimhd.net,stapadblockuser.*,stape.fun,strcloud.*,streamadblockplus.*,streamtapeadblockuser.*,streamta.*,streamtape.*,streamtapeadblock.*,strtape.*,strtapeadblock.*,strtapeadblocker.*,strtpe.*,theproxy.*,tvply.*,updatesmovie.xyz,vidlox.*,voirseries.io,watchfree.*##+js(aost, Math.random, /\st\.[a-zA-Z]*\s/)`

### URL(s) where the issue occurs.

`https://movies2watch.ru/series/the-big-door-prize-nkxjk/1-10`

### uBO version

latest

### Browser name and version

brave (latest)

### Settings

none

### Notes

When i go to this website and wanne watch a movie the filter that comes from ubo has bug in it, i tracked the part of the code (see above) which does it.
And what it does is that you are unable to watch a movie and with series the links that should apear below the movie of other episodes are also deleted.
When i disable this filter it starts to work again but i also get all popups and ads back since it is a mayor default filter from ubo that blocks all of the crap on this site.
Please fix this small part of the code so i can use the site again.

**Comment by mapx-** [comment]
I removed the filter above and still getting no popup
