### ISSUE TITLE
foxnews.com: breakage

### ISSUE THREAD

**Issue by mfgrimes** [uBlockOrigin/uAssets#18151]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.foxnews.com/health/dianne-feinstein-sicker-public-knew-shingles-caused-brain-inflammation`

### Category

breakage

### Description

Comments section is getting blocked. This just started for me today. Yesterday it was ok. If I turn off uBlock I can see comments. I am using Firefox private browsing mode. Disabling Enhanced Tracking Protection for the site does not help. I also had Privacy Badger enabled but removing that did not help either. I had both of them disabled with no help to the issue. The issue also occurs when not using Firefox private browsing mode.

After investigating this a little I found that the issue is caused by the default enabled EasyList filter. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 113
filterset (summary): 
 network: 95247
 cosmetic: 29070
 scriptlet: 17482
 html: 942
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34174-359, 2m
  ublock-badware: 7137-1, 2m
  ublock-privacy: 442-1, 2m
  ublock-abuse: 70-70, 2m
  ublock-unbreak: 2036-2, 2m
  ublock-quick-fixes: 352-1, 2m
  adguard-mobile: 8776-121, 3m
  easylist: 65907-17466, 2m
  easyprivacy: 31844-623, 2m
  urlhaus-1: 7065-1, 2m
  plowe-0: 3735-2, 2m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2764 ms
 maxAssetCacheWait: 17 ms
popupPanel: 
 blocked: 40
 network: 
  foxnews.com: 1
  amazon-adsystem.com: 1
  appsflyer.com: 1
  aswpsdkus.com: 1
  bing.com: 1
  chartbeat.com: 1
  connatix.com: 2
  criteo.net: 1
  datadoghq-browser-agent.com: 1
  datadoghq.com: 1
  demdex.net: 1
  doubleclick.net: 1
  flipboard.com: 1
  google.com: 5
  googletagmanager.com: 2
  h-cdn.com: 1
  imrworldwide.com: 1
  knotch-cdn.com: 1
  outbrain.com: 1
  pix.pub: 1
  rlcdn.com: 1
  scorecardresearch.com: 1
  spot.im: 8
  taplytics.com: 1
  yahoo.com: 2
  yimg.com: 1
 cosmetic: 
  ##.ad
  ##.ad-container
  ##.vendor-unit
```
</details>

**Comment by mapx-** [comment]
Test

`||static-cdn.spot.im^*/ad-container-bundle.js$badfilter`

@ryanbr
