### ISSUE TITLE
olhardigital.com.br: breakage

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#18156]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://olhardigital.com.br/2023/05/19/pro/moderadores-do-facebook-pedem-aumento-pelos-horrores-que-sao-obrigados-a-assistir/`

### Category

breakage

### Description

Comments are being "removed" when enabling adblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/129367686/ec8ee7db-182f-4a30-9f6a-f7b77833c4ad)
![image](https://github.com/uBlockOrigin/uAssets/assets/129367686/861d33fc-69f7-4566-980c-e7cbee5b8714)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 97026
 cosmetic: 85358
 scriptlet: 19754
 html: 942
listset (total-discarded, last-updated): 
 added: 
  fanboy-cookiemonster: 47170-219, 1m
 default: 
  user-filters: 63-7, never
  ublock-filters: 33935-108, 1m
  ublock-badware: 7143-0, 1m
  ublock-privacy: 442-0, 1m
  ublock-abuse: 70-70, 1m
  ublock-unbreak: 2031-2, 1m
  ublock-quick-fixes: 352-0, 1m
  easylist: 65907-705, 1m
  easyprivacy: 31844-629, 1m
  urlhaus-1: 7065-1, 1m
  plowe-0: 3735-3, 1m
  spa-1: 5229-10, 1m
filterset (user): [array of 63 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  moz-extension-scheme
switchRuleset: 
 added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1865 ms (selfie)
 maxAssetCacheWait: 810 ms
popupPanel: 
 blocked: 30
 network: 
  olhardigital.com.br: 2
  adnxs.com: 1
  advertising.com: 1
  denakop.com: 1
  doubleclick.net: 1
  dwin2.com: 2
  geoedge.be: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  jsuol.com.br: 1
  mgid.com: 1
  newsroom.bi: 2
  onesignal.com: 1
  pubmatic.com: 1
  rlcdn.com: 1
  spot.im: 7
  spotxchange.com: 2
  teads.tv: 2
 cosmetic: 
  ##.ad
  ##.diagonal-strip
  ##div[style^=\"max-width:100%;width:300px;height:250px;\"]
  ##.intext-denakop
  ##div[id*=\"ScriptRoot\"]
  ##AMP-AD
  ###lgpd_optall
  ##.quads-location
  ##.publicidade
  ##.google-ads
  ##.banner-ad
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr 

Same breakage as https://github.com/uBlockOrigin/uAssets/issues/18151

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/bcb952d87b4e62a2d768a2006f6222746ab5963d
