### ISSUE TITLE
dzen.ru: ads

### ISSUE THREAD

**Issue by Sannyasin** [uBlockOrigin/uAssets#18154]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dzen.ru/a/XXjr-G9fbwEnfPgg`

### Category

ads

### Description

It is not possible to enter the item selection mode on the page, to block ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/80720601/83452688-4723-4183-aefb-40484f22b043)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 110
filterset (summary): 
 network: 274059
 cosmetic: 243658
 scriptlet: 41507
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 68437-6438, never
  adguard-generic: 71158-6252, never
  adguard-mobile: 8777-215, never
  adguard-social: 20514-1528, never
  adguard-spyware-url: 1034-6, never
  block-lan: 47-0, never
  curben-phishing: 96369-36, never
  curben-pup: 199-1, never
  dpollock-0: 11357-814, never
  fanboy-annoyance: 90686-79175, never
  fanboy-cookiemonster: 47170-240, never
  fanboy-social: 16595-24, never
  fanboy-thirdparty_social: 69-0, never
  ublock-annoyances: 5073-55, never
  adguard-spyware: 40854-13642, never
 default: 
  user-filters: 0-0, never
  RUS-0: 39721-10, 1h.45m
  easylist: 65907-69, 1h.45m
  easyprivacy: 31843-153, 1h.45m
  plowe-0: 3735-944, 1h.44m
  ublock-abuse: 70-1, 1h.44m
  ublock-badware: 7113-128, 1h.44m
  ublock-filters: 33028-145, 1h.44m
  ublock-privacy: 392-75, 1h.44m
  ublock-quick-fixes: 350-36, 1h.44m
  ublock-unbreak: 2020-39, 1h.44m
  urlhaus-1: 7065-1, 1h.44m
filterset (user): [empty]
modifiedUserSettings: 
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3578 ms
 maxAssetCacheWait: 79 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
go to https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

and subscribe this list too:
`RU AdList: Counters`

test again, see if helps

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dportvine** [comment]
@Sannyasin 
For **Yandex Group** you need [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)

<details>
<summary>Screen</summary>


![2023-05-21_090656](https://github.com/uBlockOrigin/uAssets/assets/111344219/fd6bf189-d7a7-4f50-bb61-12bca160e84a)
</details>

Item selection mode - works for me.

**Comment by Sannyasin** [comment]
**On Dzen.ru I was able to block ads with this instruction:**

1. Installed — [uBlock Origin development build
](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii)

2. I added custom filters:
- [RU AdList: BitBlock + Fanboy's General](https://easylist-downloads.adblockplus.org/bitblock.txt)

- [RU AdList: Counters](https://easylist-downloads.adblockplus.org/cntblock.txt)

- [ NoCoin Filter List - against miners.](https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt)

***

**На Dzen.ru мне помогло заблокировать рекламу вот такая [инструкция](https://pikabu.ru/story/udalyaem_reklamu_v_yandeks_brauzere_na_androidsmartfonakh_i_pk_dazhe_na_stranitsakh_yandeksa_8440686):**

1. Установил — [uBlock Origin development build
](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii)

2. Добавил пользовательские фильтры:
- [RU AdList: BitBlock + Fanboy's General](https://easylist-downloads.adblockplus.org/bitblock.txt)

- [RU AdList: Counters](https://easylist-downloads.adblockplus.org/cntblock.txt)

- [ NoCoin Filter List - против майнеров.](https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt)

**Comment by Sannyasin** [comment]
> @Sannyasin For **Yandex Group** you need [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)
> 
> Item selection mode - works for me.

Strangely enough, my [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) — doesn't have item selection mode on the page [dzen.ru](https://dzen.ru/a/XXjr-G9fbwEnfPgg).

Ah, in the [uBlock Origin development build](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) — the item selection mode on the page [dzen.ru](https://dzen.ru/a/XXjr-G9fbwEnfPgg) works.

**Comment by dportvine** [comment]
>Strangely enough, my [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) — the item selection mode does not work on the page [dzen.ru](https://dzen.ru/a/XXjr-G9fbwEnfPgg)

Yandex browser? The problem is in it. Google Chrome - [see](https://imgur.com/c4lE6xh).
