### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by strikestna** [uBlockOrigin/uAssets#18152]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/collection/tracks`

### Category

breakage

### Description

New Spotify web UI, uBO no longer works on the site as it freezes a site after each song (ad). There is an ad popup on the bottom left corner as well.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/134153368/f053b2d3-2351-427d-8649-14597c69f78d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94278
 cosmetic: 38785
 scriptlet: 17424
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 65792-47, 3d.8h.37m
  easyprivacy: 32121-46, 4d.9h.31m
  plowe-0: 3737-938, 4d.9h.32m
  ublock-abuse: 70-0, 4d.9h.30m
  ublock-badware: 7119-128, 4d.9h.28m
  ublock-filters: 33027-98, 4d.9h.27m
  ublock-privacy: 394-74, 4d.9h.29m
  ublock-quick-fixes: 352-31, 11h.50m
  ublock-unbreak: 2015-41, 4d.9h.26m
  urlhaus-1: 7413-1, 21h.51m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 275 ms (selfie)
 maxAssetCacheWait: 105 ms
popupPanel: 
 blocked: 5
 network: 
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 2
  spotifycdn.com: 1
```
</details>

**Comment by krystian3w** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/18148

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/18148

duplicate
