### ISSUE TITLE
twitch.tv: ads

### ISSUE THREAD

**Issue by Titwanism** [uBlockOrigin/uAssets#18153]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitch.tv/allysee`

### Category

ads

### Description

Please fix the twitch ads 
thanks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 112740
 cosmetic: 47684
 scriptlet: 17515
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  FRA-0: 28446-31, 3d.19h.26m
  easylist: 65956-397, 1d.23h.51m
  easyprivacy: 31841-339, 1d.17h.48m
  plowe-0: 3737-961, 5d.18h.50m
  ublock-abuse: 70-1, 4h.23m
  ublock-badware: 7119-145, 4d.21h.26m
  ublock-filters: 33015-184, 4d.21h.25m
  ublock-privacy: 392-73, 4h.22m
  ublock-quick-fixes: 347-30, 4h.21m
  ublock-unbreak: 2016-45, 4d.21h.24m
  urlhaus-1: 7413-1, 20h.35m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 719 ms (selfie)
 maxAssetCacheWait: 175 ms
popupPanel: 
 blocked: 44
 no-cosmetic-filtering: true
 network: 
  amazon-adsystem.com: 3
  d2v02itv0y9u9t.cloudfront.net: 1
  google-analytics.com: 1
  imrworldwide.com: 1
  scorecardresearch.com: 34
  sentry.io: 4
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184

see also what you can try / experiment with
https://www.reddit.com/r/uBlockOrigin/comments/tq6gfi/excessive_use_of_ads_on_twitch_alternative/
https://github.com/pixeltris/TwitchAdSolutions#scripts
