### ISSUE TITLE
fileoops.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1815]
URL(s) where the issue occurs

`http://www.fileoops.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by ghajini** [comment]
Antiadblock

`http://fileoops.com/`
![image](https://user-images.githubusercontent.com/20338483/112644164-1df25e00-8e6b-11eb-8085-53d51d3b5382.png)
