### ISSUE TITLE
ikorektor.pl: detection

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#18169]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ikorektor.pl/`

### Category

detection

### Description

soft anti-adblock under header:

> We try to make sure that the ads displayed on our site are not intrusive.
>
> Ads help to maintain the free functionality of iCorrector.
>
> Thank you for considering disabling AdBlock / uBlock on our site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/MajkiIT/polish-ads-filter/assets/35370833/260ff706-1e64-4a6d-8b5e-533b38c1494f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95301
 cosmetic: 47758
 scriptlet: 21041
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  user-filters: null
 added: 
  ublock-annoyances: 5077-9, now
 default: 
  POL-0: 7943-11, now
  POL-2: 1275-13, now
  easylist: 66101-74, now
  easyprivacy: 31838-49, now
  plowe-0: 3735-952, now
  ublock-abuse: 70-0, now
  ublock-badware: 7144-129, now
  ublock-filters: 33080-140, now
  ublock-privacy: 392-75, now
  ublock-quick-fixes: 360-36, now
  ublock-unbreak: 2020-40, now
  urlhaus-1: 6747-1, now
filterset (user): [array of 4 redacted]
modifiedUserSettings: 
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 505 ms (selfie)
 maxAssetCacheWait: 282 ms
popupPanel: 
 blocked: 2
 network: 
  google-analytics.com: 1
  googlesyndication.com: 1
 cosmetic: 
  ##[id^=\"aswift_\"]
  ##ins.adsbygoogle
```
</details>

### Notes

https://github.com/MajkiIT/polish-ads-filter/issues/21801

**Comment by mapx-** [comment]
added as annoyance, ok @krystian3w ?

**Comment by krystian3w** [comment]
OK.
