### ISSUE TITLE
hardsextube.com incorrect blocking ? [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1816]
URL(s) where the issue occurs

`https://www.hardsextube.com/video/video-47398`

Describe the issue

![](https://i.imgur.com/PolJ1dq.png)
![](https://i.imgur.com/OIIaSoq.png)

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by WowDude** [comment]
Much trash here:

```
hardsextube.com##script:inject(abort-on-property-read.js, ExoLoader)
hardsextube.com##script:inject(abort-on-property-read.js, hsCtrl)
hardsextube.com##.featured-wrap
||hardsextube.com/hsCtrl.js
||awentw.com^$third-party
```

**Comment by WowDude** [comment]
@mapx- I see that `||fwbntw.com^$third-party` on EasyList is duplicated (lines 30062, 41645) I guess the [30062 one](https://github.com/easylist/easylist/blob/459aeabcae1b29000ed2faca880f6b4b229a8219/easylist/easylist_adservers.txt#L2112) should be removed, while leaving [the 41645 one](https://github.com/easylist/easylist/blob/459aeabcae1b29000ed2faca880f6b4b229a8219/easylist_adult/adult_adservers.txt#L361), as it is adult adserver.

**Comment by mapx-** [comment]
@ryanbr

duplicate filter in easylist
`||fwbntw.com^$third-party`

**Comment by mapx-** [comment]
@WowDude  for easylist issues report here:
https://github.com/easylist/easylist/issues

**Comment by WowDude** [comment]
@mapx- : Yea I know and am fully aware of it, was thinking about to report it to EasyList, but I intentionally choose to comment here because:
- found the duplicate while checking `https://www.hardsextube.com/video/video-47398`, as the filter shows up in the logger
- just didn't want to create a new topic on EasyList for such small issue

So it was just BTW.

**Comment by KiLL4FuNK** [comment]
show this back

![](https://i.imgur.com/PolJ1dq.png)
![](https://i.imgur.com/OIIaSoq.png)
