### ISSUE TITLE
cgaa.org: detection

### ISSUE THREAD

**Issue by Aldous-Huxley** [uBlockOrigin/uAssets#18168]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cgaa.org`

### Category

detection

### Description

Cannot get past adblocking detection.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 214364
 cosmetic: 139826
 scriptlet: 34388
 html: 943
listset (total-discarded, last-updated): 
 added: 
  adguard-generic: 71158-5169, 10h.45m
  adguard-mobile: 8777-110, 10h.47m
  block-lan: 47-0, 4d.13h.14m
  curben-phishing: 96369-35, 10h.43m
  adguard-annoyance: 68438-618, 10h.46m
 default: 
  user-filters: 0-0, never
  ublock-filters: 33908-39, 4d.13h.14m
  ublock-badware: 7073-1, 4d.13h.14m
  ublock-privacy: 443-0, 4d.13h.14m
  ublock-abuse: 70-70, 4d.13h.14m
  ublock-unbreak: 2026-2, 4d.13h.13m
  ublock-quick-fixes: 352-30, 10h.41m
  easylist: 65960-671, 10h.44m
  easyprivacy: 32139-620, 4d.13h.11m
  urlhaus-1: 6712-1, 10h.42m
  plowe-0: 3737-2, 4d.13h.11m
filterset (user): [empty]
trustedset: 
 added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 503 ms (selfie)
 maxAssetCacheWait: 232 ms
popupPanel: 
 blocked: 29
 network: 
  cgaa.org: 17
  connatix.com: 1
  doubleclick.net: 6
  ezodn.com: 1
  google.com: 3
  googlesyndication.com: 1
```
</details>

**Comment by bookarticle** [comment]
```
cgaa.org##+js(aopr, checkEzAdBlck)
```
