### ISSUE TITLE
AdBlock Detected 

### ISSUE THREAD

**Issue by Sandbox5093** [uBlockOrigin/uAssets#18162]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Site:   Nopay.info

AdBlock Detected

### URL(s) where the issue occurs.

Nopay.info

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium Mobile: 112
filterset (summary): 
 network: 100401
 cosmetic: 36289
 scriptlet: 17530
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 9m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, 9m
 default: 
  user-filters: 0-0, never
  ITA-0: 12985-411, 9m
  adguard-mobile: 8777-34, 9m
  easylist: 66036-16869, 9m
  easyprivacy: 31838-59, 9m
  plowe-0: 3735-1027, 9m
  ublock-abuse: 70-0, 9m
  ublock-badware: 7133-129, 9m
  ublock-filters: 33349-395, 9m
  ublock-privacy: 392-76, 9m
  ublock-quick-fixes: 360-36, 9m
  ublock-unbreak: 2025-41, 9m
  urlhaus-1: 6747-1, 9m
filterset (user): [empty]
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 504 ms (selfie)
 maxAssetCacheWait: 230 ms
```
</details>

**Comment by mapx-** [comment]
update all your lists

https://github.com/uBlockOrigin/uAssets/commit/70abfe20348fa1fc0e8e597a431c9fe2b5fa2d71
