### ISSUE TITLE
projectlive.info: detection

### ISSUE THREAD

**Issue by marcofetahu** [uBlockOrigin/uAssets#18163]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://projectlive.info/sports.php?id=ch16`

### Category

detection

### Description

can't access the page as that's the only thing that appears:
" Ads Blocker Detected!!!
We have detected that you are using extensions to block ads.
Please support us by disabling these ads blocker. "

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 83806
 cosmetic: 87473
 scriptlet: 31689
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  easyprivacy: null
  plowe-0: null
 added: 
  adguard-generic: 71158-480, 5m
  adguard-mobile: 8777-45, 5m
  ublock-quick-fixes: 360-36, 4m
 default: 
  user-filters: 0-0, never
  ITA-0: 12985-0, 5m
  easylist: 66036-834, 5m
  ublock-abuse: 70-0, 5m
  ublock-badware: 7139-358, 4m
  ublock-filters: 33063-3664, 4m
  ublock-privacy: 392-72, 4m
  ublock-unbreak: 2020-67, 4m
  urlhaus-1: 6747-1, 4m
filterset (user): [empty]
trustedset: 
 added: [array of 9 redacted]
switchRuleset: 
 added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1848 ms (selfie)
 maxAssetCacheWait: 446 ms
popupPanel: 
 blocked: 14
 no-popups: true
 network: 
  addresseepaper.com: 2
  asacdn.com: 1
  dismantlepenantiterrorist.com: 2
  histats.com: 1
  intellipopup.com: 1
  kingrecommendation.com: 1
  simplewebanalysis.com: 3
  superfastcdn.com: 1
  swarm.video: 1
  zapprecisionadmire.com: 1
```
</details>

**Comment by mapx-** [comment]
update all your lists

https://github.com/uBlockOrigin/uAssets/commit/70abfe20348fa1fc0e8e597a431c9fe2b5fa2d71
