### ISSUE TITLE
filehippo.com: badware

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18166]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A seemingly very dangerous site with a TON of malicious shit in it.
VirusTotal has 7 scans which all show up as malicious because of the file!!!
https://www.virustotal.com/gui/file/0660f98c19304253007b0e79950857185a5ebbc40d8529709d2789f3dd76b90b

### URL(s) where the issue occurs.

`https://filehippo.com/download_jre-32/6.0.0.105.0/`

### uBO version

v1.49.3b14

### Browser name and version

Firefox 113.0.1

### Settings

- Using custom settings, checking "I am an advanced user"

**Comment by mapx-** [comment]
- `filehippo` is too famous, you should ask an opinion on specialized sites / forums

**Comment by Sonic5435325** [comment]
@mapx- It just looks like another third party installer (Just like CNet and Softonic) site to me. I don't see why this should be left out of the Badware risks list, especially with proof that the file has malware.

**Comment by mapx-** [comment]
Try reporting the single malicious files here:

Online Malicious URL Blocklist
https://gitlab.com/malware-filter/urlhaus-filter#malicious-url-blocklist
