### ISSUE TITLE
fifa.com: detection

### ISSUE THREAD

**Issue by IlyaFirsov** [uBlockOrigin/uAssets#18164]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Detects uBlock and blocks video playback

### URL(s) where the issue occurs.

`https://www.plus.fifa.com/en/content/live-streaming-fifa-u-20-world-cup-argentina-2023-guatemala-v-new-zealand/952c9d6f-bad5-4eba-b7c7-abc26c9a50b2` (may be geoblocked)
`https://www.plus.fifa.com/en/content/bravas-de-juarez/fac6685c-a900-4e78-b5cd-192af5131ffe`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/26841983/1d761204-f8ab-4ede-8a95-4beae43157d2)

### uBO version

1.49.2

### Browser name and version

Chrome 113.0.5672.127

### Settings

default settings

**Comment by stephenhawk8054** [comment]
@mapx- Looks like these filters will cause midroll video ads 

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,from=fifa.com
@@||pubads.g.doubleclick.net/*fifa.com$xhr,domain=imasdk.googleapis.com
```

Does replacing them with these work on your side?

```adb
||imasdk.googleapis.com/js/sdkloader/ima3.js$redirect-rule=google-ima.js,domain=fifa.com
||fifa.com/api/v*/ad-manager/$redirect=nooptext
```
