### ISSUE TITLE
[nsfw] t66y.com: breakage

### ISSUE THREAD

**Issue by Greyh4t** [uBlockOrigin/uAssets#18160]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.t66y.com/htm_data/2304/21/5647843.html`

### Category

breakage

### Description

These rules of "CHN: AdGuard Chinese" cause the page to display abnormally, unable to display pictures and links in the content
```
t66y.com##+js(abort-current-script, $, adhtml)
t66y.com##.tpc_content.do_not_catch > a[target="_blank"]
t66y.com##.tpc_content.do_not_catch > br
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 109578
 cosmetic: 49036
 scriptlet: 17633
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 11-0, never
  CHN-0: 26776-116, 2m
  easylist: 65907-107, 2m
  easyprivacy: 31844-64, 2m
  plowe-0: 3735-941, 2m
  ublock-abuse: 70-0, 2m
  ublock-badware: 7139-128, 2m
  ublock-filters: 33063-114, 1m
  ublock-privacy: 392-75, 1m
  ublock-quick-fixes: 350-36, 1m
  ublock-unbreak: 2020-40, 1m
  urlhaus-1: 6712-1, 1m
filterset (user): [array of 11 redacted]
trustedset: 
 added: [array of 4 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
 contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 635 ms
 maxAssetCacheWait: 7 ms
popupPanel: 
 blocked: 0
 cosmetic: 
  ##.tpc_content.do_not_catch > a[target=\"_blank\"]
  ##.tpc_content.do_not_catch > br
  ##.sptable_do_not_remove
  ##.tips
  ##.sptable_do_not_remove:style(display: block !important; visibility: hidden !important;)
```
</details>

**Comment by mapx-** [comment]
report here
https://github.com/cjx82630/cjxlist/issues

and at  AdGuard
https://github.com/AdguardTeam/AdguardFilters/issues

@Alex-302
@cjx82630

**Comment by Alex-302** [comment]
Fixed.

**Comment by Alex-302** [comment]
@Greyh4t removed.
