### ISSUE TITLE
techtobo.com: detection

### ISSUE THREAD

**Issue by Gamkutopolowk** [uBlockOrigin/uAssets#18171]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.techtobo.com/`

### Category

detection

### Description

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 108283
 cosmetic: 72784
 scriptlet: 31641
 html: 942
listset (total-discarded, last-updated): 
 removed: 
  plowe-0: null
 added: 
  adguard-generic: 71158-5133, 1d.1h.12m
 default: 
  user-filters: 10-0, never
  ublock-filters: 33935-39, 1d.2h.39m
  ublock-badware: 7102-0, 2d.3h.44m
  ublock-privacy: 442-0, 2d.1h.3m
  ublock-abuse: 70-70, 2d.1h.4m
  ublock-unbreak: 2031-1, 2d.3h.43m
  easylist: 65798-292, 4d.12m
  easyprivacy: 31838-29, 1h.35m
  urlhaus-1: 6747-1, 10h.31m
  ublock-quick-fixes: 362-34, 9h.24m
filterset (user): [array of 10 redacted]
trustedset: 
 added: [array of 8 redacted]
switchRuleset: 
 added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 200 ms (selfie)
 maxAssetCacheWait: 82 ms
popupPanel: 
 blocked: 16
 network: 
  techtobo.com: 2
  google-analytics.com: 1
  google.com: 7
  googlesyndication.com: 5
  googletagmanager.com: 1
 cosmetic: 
  ##ins.adsbygoogle
  ##.banner_728x90
  ##.overlay > .overlay-title
  ##.blockMessage
  ##.is-active.samSupportUsOverlay.overlay-container
```
</details>

**Comment by dportvine** [comment]
`https://www.techtobo.com/#microsoft-portal.11`

<details>
<summary>Screen</summary>

![2023-11-13_092338](https://github.com/uBlockOrigin/uAssets/assets/111344219/eabee545-c5f3-4770-9de9-e1b05edd3740)
</details>

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 123893
 cosmetic: 91290
 scriptlet: 25248
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28030-39, 18m
  ublock-annoyances: 5824-24, 18m
 default:
  user-filters: 3-0, never
  ublock-filters: 35295-44, 18m
  ublock-badware: 7459-5, 18m
  ublock-privacy: 668-0, 18m
  ublock-unbreak: 2148-1, 18m
  ublock-quick-fixes: 184-110, 18m
  easylist: 75291-268, 18m
  easyprivacy: 32874-83, 18m
  urlhaus-1: 10830-0, 2m
  plowe-0: 3723-1076, 2m
  RUS-0: 40079-172, 18m
filterset (user): [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1051 ms (selfie)
 maxAssetCacheWait: 602 ms
popupPanel:
 blocked: 9
 network:
  techtobo.com: 1
  google.com: 6
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##.banner_728x90
  ##body:style(overflow: auto !important;)
  ##+js(abort-current-script, $, samInitDetection)
```
</details>
