### ISSUE TITLE
gamegenie.com: ad placeholders

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18173]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There are ad placeholders on the site.
These are the filters I came up with:
`gamegenie.com##div[style="border-top: 3px solid;"]:has(ins.adsbygoogle)`
`gamegenie.com##th[width="728"]`
![Screenshot from 2023-05-21 22-54-39](https://github.com/uBlockOrigin/uAssets/assets/89158249/ff189899-9134-4150-8036-753f2a570b65)

Only problem is that the design gets a bit messed up if you decide to hide it. Example:
![Screenshot from 2023-05-21 22-54-35](https://github.com/uBlockOrigin/uAssets/assets/89158249/ceb15cea-34f3-4115-9211-0b111ecd3303)
Maybe there's some way uBlock Origin can fix it that something like EasyList can't? Just thought I'd report here just in case.

### URL(s) where the issue occurs.

`https://www.gamegenie.com/`

### uBO version

v1.49.3b16

### Browser name and version

Firefox 113.0.1

### Settings

- Use custom filters, check "I am an advanced user"

**Comment by mapx-** [comment]
you could reporting the above stuff at easylist repository
