### ISSUE TITLE
linkneverdie.net: detection

### ISSUE THREAD

**Issue by nakhoacool** [uBlockOrigin/uAssets#18175]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkneverdie.net/signin`

### Category

detection

### Description

The site won't let you sign in. It should have the username and password input box

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-05-22 105135](https://github.com/uBlockOrigin/uAssets/assets/77623180/fed0740d-bb43-4210-91bf-384aaea9c040)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94177
 cosmetic: 40028
 scriptlet: 17591
 html: 944
listset (total-discarded, last-updated): 
 added: 
  VIE-1: 1923-6, 3m
 default: 
  user-filters: 0-0, never
  ublock-filters: 33956-144, 3m
  ublock-badware: 7148-1, 3m
  ublock-privacy: 442-0, 3m
  ublock-abuse: 70-70, 3m
  ublock-unbreak: 2031-2, 3m
  ublock-quick-fixes: 362-0, 3m
  easylist: 66101-572, 3m
  easyprivacy: 31838-655, 3m
  urlhaus-1: 6737-1, 3m
  plowe-0: 3735-2, 3m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 330 ms (selfie)
 maxAssetCacheWait: 181 ms
popupPanel: 
 blocked: 6
 network: 
  addthis.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  openfpcdn.io: 1
  optad360.io: 1
  quantumdex.io: 1
 cosmetic: 
  ##.quangcao
  ##ins.adsbygoogle
  ##.info-footer:nth-child(4)
  ###adsqc
  ##.show.fade.modal-backdrop
```
</details>

**Comment by mapx-** [comment]
Test

```
linkneverdie.net#@#+js(nostif, t)
@@||pagead2.googlesyndication.com^$script,domain=linkneverdie.net
@@||quantumdex.io^$script,domain=linkneverdie.net
```

@hoang-rio

**Comment by hoang-rio** [comment]
This site update their anti adblock script frequency. so this rule may help in short time
