### ISSUE TITLE
infomania.space: detection

### ISSUE THREAD

**Issue by Warden20** [uBlockOrigin/uAssets#18174]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://infomania.space/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 199354
 cosmetic: 138631
 scriptlet: 22156
 html: 942
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 68437-4120, 1d.10h.51m
  fanboy-cookiemonster: 47170-218, 1d.10h.51m
 default: 
  user-filters: 11-0, never
  ublock-filters: 33899-40, 1d.10h.51m
  ublock-badware: 7102-0, 1d.10h.51m
  ublock-privacy: 442-0, 7h.19m
  ublock-abuse: 70-70, 7h.19m
  ublock-unbreak: 2031-2, 1d.10h.51m
  ublock-quick-fixes: 352-34, 7h.19m
  easylist: 65767-666, 5d.9h.41m
  adguard-spyware-url: 1034-5, 1d.10h.51m
  easyprivacy: 31825-29, 1d.10h.51m
  urlhaus-1: 6747-1, 7h.19m
  curben-phishing: 96369-35, 7h.19m
  plowe-0: 3742-590, 13d.1h.27m
  LegitimateURLShortener: 2186-138, 7h.19m
filterset (user): [array of 11 redacted]
trustedset: 
 added: [array of 44 redacted]
switchRuleset: 
 added: [array of 109 redacted]
hostRuleset: 
 added: [array of 57 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 6817 ms (selfie)
 maxAssetCacheWait: 1600 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
screenshot ?
