### ISSUE TITLE
mayoclinic.org: ads

### ISSUE THREAD

**Issue by Banaanae** [uBlockOrigin/uAssets#18176]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mayoclinic.org/first-aid/first-aid-corneal-abrasion/basics/art-20056659`

### Category

ads

### Description

Ad bar leftover and mayo press
`##.mayoad` to block the entire bar
or
`##.policy.contentbox` and `##.mayoad > h2` to just block the top bit about ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/83927639/d788e0c4-8168-48db-b09a-315e95322873)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93892
 cosmetic: 40196
 scriptlet: 20692
 html: 1115
listset (total-discarded, last-updated): 
 added: 
  ublock-annoyances: 5045-4, 1m
 default: 
  user-filters: 16-0, never
  ublock-filters: 33956-75, 1m
  ublock-badware: 7148-0, 1m
  ublock-privacy: 442-0, 1m
  ublock-abuse: 70-70, 1m
  ublock-unbreak: 2031-1, 1m
  ublock-quick-fixes: 362-0, 1m
  easylist: 66101-665, 1m
  easyprivacy: 31838-615, 1m
  urlhaus-1: 6737-1, 1m
  plowe-0: 3735-4, 1m
filterset (user): [array of 16 redacted]
trustedset: 
 added: [array of 11 redacted]
 removed: 
  moz-extension-scheme
modifiedUserSettings: 
 colorBlindFriendly: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2270 ms
 maxAssetCacheWait: 929 ms
popupPanel: 
 blocked: 5
 network: 
  mayoclinic.org: 1
  ensighten.com: 2
  go-mpulse.net: 2
 cosmetic: 
  ###top-advertisement
```
</details>

**Comment by mapx-** [comment]
@ryanbr
