### ISSUE TITLE
intensedebate.com

### ISSUE THREAD

**Issue by joe940** [uBlockOrigin/uAssets#18186]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

EasyList is blocking `https://www.intensedebate.com`, a blog commenting platform. Maybe there's a good reason. Or maybe it's a misfire. Thanks

### URL(s) where the issue occurs.

`https://www.intensedebate.com/`

### uBO version

1.49.2

### Browser name and version

Firefox 113.0.1

### Settings

Additional filters, but this is clearly identified as an EasyList issue.

**Comment by bookarticle** [comment]
yeah, it looks like that

@ryanbr
