### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by S-Salomon** [uBlockOrigin/uAssets#18182]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/`

### Category

breakage

### Description

Stop playing when publicity appears between songs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 97641
 cosmetic: 44545
 scriptlet: 17792
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 3-2, never
  easylist: 65907-47, 1d.11h.17m
  easyprivacy: 31838-46, 1d.11h.17m
  plowe-0: 3735-939, 1d.11h.17m
  spa-0: 3680-11, 1h.15m
  spa-1: 5229-211, 1d.11h.18m
  ublock-abuse: 70-0, 1d.11h.17m
  ublock-badware: 7098-128, 1d.11h.17m
  ublock-filters: 33064-129, 1d.11h.17m
  ublock-privacy: 392-75, 1d.11h.17m
  ublock-quick-fixes: 365-36, 1h.13m
  ublock-unbreak: 2020-41, 1d.11h.17m
  urlhaus-1: 8396-1, 1h.14m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3148 ms (selfie)
 maxAssetCacheWait: 261 ms
popupPanel: 
 blocked: 38
 network: 
  doubleclick.net: 9
  googleoptimize.com: 1
  googletagmanager.com: 1
  scdn.co: 3
  sentry.io: 23
  spotifycdn.com: 1
 cosmetic: 
  ##[href^=\"https://adclick.g.doubleclick.net/\"]
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/18148

update all your filter lists
