### ISSUE TITLE
theonegenerator.com: detection

### ISSUE THREAD

**Issue by Snowpop** [uBlockOrigin/uAssets#18180]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://theonegenerator.com/generators/date/birthday-generator`

### Category

detection

### Description

Website claims to have detected adblock software.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-05-22 12 28 42](https://github.com/uBlockOrigin/uAssets/assets/88103045/07e83eee-7189-46ab-a6ec-72260c033d3c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 222026
 cosmetic: 176288
 scriptlet: 39512
 html: 0
listset (total-discarded, last-updated): 
 added: 
  NLD-0: 2838-12, 16h.11m
  adguard-annoyance: 68635-97, 16h.11m
  adguard-generic: 71158-471, 16h.11m
  adguard-spyware-url: 1035-3, 16h.11m
  block-lan: 47-0, 10d.2h.22m
  curben-phishing: 100400-2, 16h.11m
  curben-pup: 189-0, 16h.11m
  fanboy-cookiemonster: 47180-3724, 16h.11m
  fanboy-thirdparty_social: 69-0, 16h.11m
  ublock-annoyances: 5073-257, 16h.11m
 default: 
  user-filters: 2-0, never
  easylist: 65867-856, 16h.11m
  easyprivacy: 31838-231, 16h.11m
  plowe-0: 3742-952, 10d.2h.22m
  ublock-abuse: 70-0, 16h.11m
  ublock-badware: 7079-384, 5d.44m
  ublock-filters: 33018-4051, 5d.43m
  ublock-privacy: 392-77, 16h.11m
  ublock-quick-fixes: 360-34, 1h.28m
  ublock-unbreak: 2016-103, 5d.42m
  urlhaus-1: 8396-5, 16h.11m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-extension-scheme
modifiedUserSettings: 
 cloudStorageEnabled: true
 collapseBlocked: false
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 36481 ms (selfie)
 maxAssetCacheWait: 6267 ms
popupPanel: 
 blocked: 10
 network: 
  theonegenerator.com: 2
  google.com: 5
  googlesyndication.com: 2
  googletagmanager.com: 1
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
is this only an annoyance or some functionality of the site is broken / unusable ?

**Comment by Snowpop** [comment]
As far as I can see it's only an annoyance
