### ISSUE TITLE
best-shopme.com: breakage

### ISSUE THREAD

**Issue by monkeyde98** [uBlockOrigin/uAssets#18195]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://best-shopme.com/`

### Category

breakage

### Description

website functions do not work if ublock is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 96667
 cosmetic: 25185
 scriptlet: 18010
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 635-162, never
  easylist: 65983-16844, 3d.2h.28m
  easyprivacy: 31825-48, 3d.2h.28m
  plowe-0: 3735-938, 3d.2h.28m
  spa-1: 5229-139, 3d.2h.28m
  ublock-abuse: 70-0, 3d.2h.28m
  ublock-badware: 7098-127, 3d.2h.28m
  ublock-filters: 33038-356, 3d.2h.28m
  ublock-privacy: 392-75, 3d.2h.28m
  ublock-quick-fixes: 360-36, 7h.51m
  ublock-unbreak: 2020-42, 3d.2h.28m
  urlhaus-1: 8396-1, 22h.18m
filterset (user): [array of 665 redacted]
trustedset: 
 added: [array of 32 redacted]
switchRuleset: 
 added: [array of 6 redacted]
hostRuleset: 
 added: [array of 174 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 408 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel: 
 blocked: 8
 network: 
  coinzillatag.com: 1
  cpx-research.com: 1
  google-analytics.com: 2
  googletagmanager.com: 2
  trustpilot.com: 2
 cosmetic: 
  ##.modal-content
```
</details>

**Comment by mapx-** [comment]
> website functions do not work if ublock is enabled.

Explain what's broken and how to reproduce the issue

**Comment by krystian3w** [comment]
Also remove "uBlock LLC" from Chromium.

<details> <summary> remove via Chrome Web Store: </summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/35370833/9e192019-9d3d-435e-9888-514793b99694)

</details>
<details> <summary> remove via Edge Store: </summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/35370833/b4592d81-1a3e-4375-9c25-ca701e7bff69)

</details>

**Comment by monkeyde98** [comment]
> > website functions do not work if ublock is enabled.
> 
> Explain what's broken and how to reproduce the issue

the site buttons loads a pop up. I click the login button on the main screen and the pop up does not load to put the data to log in.

**Comment by krystian3w** [comment]
Test too in Firefox 102/113 due works Fine on Chrome 109, so could be bug in Chromium 110+ release.

https://github.com/uBlockOrigin/uAssets/assets/35370833/076b2fd6-10c0-4053-83bc-84dce845255d

**Comment by monkeyde98** [comment]
> Test too in Firefox 102/113 due works Fine on Chrome 109, so could be bug in Chromium 110+ release.
> 
> https://github.com/uBlockOrigin/uAssets/assets/35370833/076b2fd6-10c0-4053-83bc-84dce845255d
> 
> Also your filters are outdated (have ~72+ h):
> 
> > ```yaml
> >   easylist: 65983-16844, 3d.2h.28m
> >   easyprivacy: 31825-48, 3d.2h.28m
> >   plowe-0: 3735-938, 3d.2h.28m
> >   spa-1: 5229-139, 3d.2h.28m
> >   ublock-abuse: 70-0, 3d.2h.28m
> >   ublock-badware: 7098-127, 3d.2h.28m
> >   ublock-filters: 33038-356, 3d.2h.28m
> >   ublock-privacy: 392-75, 3d.2h.28m
> >   ublock-quick-fixes: 360-36, 7h.51m
> >   ublock-unbreak: 2020-42, 3d.2h.28m
> > ```
> 
> So failed step:
> 
> > * [x]  I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
> 
> Or you didn't reopen report form to share more fresh update dates.
> 
> It seems doubtful that SPA-1 would spoil the site, sooner any of the 655-797 custom filters: `user-filters: 635-162, never` like log said:
> 
> > ```yaml
> >  cosmetic: 
> >   ##.modal-content
> > ```
> 
> https://github.com/uBlockOrigin/uAssets/assets/35370833/3c1874ca-2b1b-44b7-90dd-1a3f3a8f8c3f - form disappears.
> 
> Rather, I rule out that the database has mishandled and a network error that the `:has` / `:has-text` check was missing from the filter.

I found the error. I had a filter preventing it from working.
