### ISSUE TITLE
bilibili.com: ads

### ISSUE THREAD

**Issue by Axiqy** [uBlockOrigin/uAssets#18199]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bilibili.com/video/BV1uo4y1A7Gs/?spm_id_from=333.1007.tianma.1-3-3.click&vd_source=a16e16bd263794e70e422110d367c574`

### Category

ads

### Description

There are still some ads on this page.
![屏幕截图 2023-05-23 154444](https://github.com/uBlockOrigin/uAssets/assets/116355440/9891bb37-16f4-4448-9568-cf7e6d454fba)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 108187
 cosmetic: 48980
 scriptlet: 17590
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  CHN-0: 26521-112, 17d.18h.35m
  easylist: 65828-105, 4d.19h.6m
  easyprivacy: 31839-64, 16h.52m
  plowe-0: 3737-940, 9d.16h.22m
  ublock-abuse: 70-0, 9d.16h.25m
  ublock-badware: 7098-127, 2d.15h.50m
  ublock-filters: 33028-112, 2d.15h.47m
  ublock-privacy: 394-75, 9d.16h.26m
  ublock-quick-fixes: 326-36, 3h.14m
  ublock-unbreak: 2020-41, 2d.15h.48m
  urlhaus-1: 5659-0, 18h.56m
filterset (user): [empty]
trustedset: 
 added: [array of 2 redacted]
 removed: 
  chrome-extension-scheme
  edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 309 ms (selfie)
 maxAssetCacheWait: 66 ms
popupPanel: 
 blocked: 116
 network: 
  bilibili.com: 115
  hdslb.com: 1
 cosmetic: 
  ###slide_ad
  ##.ad-icon
  ###slide_ad + .ad-report
```
</details>

**Comment by mapx-** [comment]
report here
https://github.com/cjx82630/cjxlist/issues

and at AdGuard
https://github.com/AdguardTeam/AdguardFilters/issues

@Alex-302
@cjx82630

**Comment by Alex-302** [comment]
Not reproduced.
