### ISSUE TITLE
otakustream.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#1819]
![2018-03-27-osomatsu-san 2 episode 25 - watch anime online english subbed](https://user-images.githubusercontent.com/5884000/37936432-cf7725a0-3155-11e8-9a3a-5f7010596263.png)
`https://otakustream.tv/anime/osomatsu-san-2/episode-25/`

"close ads" button

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/80eb960ea3acab0a5135e233353cc87b

 uBO 1.15.18
 ND 13.47
 Chr 65.0.3325.181
</details>

**Comment by okiehsch** [comment]
`otakustream.tv###outer`
should work without hidding anything else.

To find this filter you have to use your browsers developer console, because `uBO-picker/logger` does not work inside iframes, see https://github.com/gorhill/uBlock/issues/3036

**Comment by uBlock-user** [comment]
for unblocked popunders - 

`otakustream.tv##script:inject(addEventListener-defuser.js, /^mouseup|mousedown/, 0x)`

**Comment by KonoromiHimaries** [comment]
broken scroll
![2018-04-10-otakustream - watch anime online english subbed hd](https://user-images.githubusercontent.com/5884000/38552253-dae1c96a-3cbb-11e8-9fe1-69b53bbeb385.png)

**Comment by uBlock-user** [comment]
Add

```
otakustream.tv##body:style(overflow: visible !important;)
otakustream.tv##.modal-backdrop
```

**Comment by KonoromiHimaries** [comment]
@okiehsch right click on the player do not work

**Comment by okiehsch** [comment]
`rapidvideo.com##script:inject(addEventListener-defuser.js, contextmenu, preventDefault)`
will be added to `uBO-annoyances`.

**Comment by KonoromiHimaries** [comment]
@okiehsch right click still do not work on openload player

**Comment by okiehsch** [comment]
`openload.co,streamango.com##script:inject(abort-current-inline-script.js, $, contextmenu)`

**Comment by uBlock-user** [comment]
I use `rapidvideo.com,streamango.com,openload.co,oload.*##script:inject(addEventListener-defuser.js, contextmenu)`
