### ISSUE TITLE
maia.crimew.gay: privacy

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#18193]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://maia.crimew.gay/`

### Category

privacy

### Description

umami is loaded, via `https://umami.crimew.gay/script.js` and `https://umami.crimew.gay/api/send
announcement`: `https://nyancrimew.tumblr.com/post/717770199337680896/in-the-interest-of-transparency`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 109665
 cosmetic: 108812
 scriptlet: 20239
 html: 953
listset (total-discarded, last-updated): 
 added: 
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 953-2, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2187-138, now
  adguard-spyware-url: 1035-6, now
  fanboy-annoyance: 91194-15605, now
  dpollock-0: 11357-725, now
 default: 
  user-filters: 13-0, never
  ublock-filters: 34598-130, now
  ublock-badware: 6956-0, now
  ublock-privacy: 373-0, now
  ublock-abuse: 70-0, now
  ublock-unbreak: 2010-0, now
  ublock-quick-fixes: 209-1, now
  easylist: 65879-176, now
  easyprivacy: 30899-1207, now
  urlhaus-1: 7286-1, now
  plowe-0: 3746-944, now
filterset (user): [array of 13 redacted]
switchRuleset: 
 added: [array of 8 redacted]
hostRuleset: 
 added: [array of 178 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 1
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 44618 ms (selfie)
 maxAssetCacheWait: 5917 ms
popupPanel: 
 blocked: 2
 network: 
  lavender.software: 1
  sleepy.zone: 1
```
</details>

**Comment by stephenhawk8054** [comment]
The link `https://umami.crimew.gay/script.js` returns `503 Service Unavailable` for me, and I don't see any `https://umami.crimew.gay/api/send` connections.

**Comment by peace2000** [comment]
No issues with default configuration.
