### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by AndroidUSBR** [uBlockOrigin/uAssets#18198]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/`

### Category

ads

### Description

Lot of ads banners and song interruptions ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 92952
 cosmetic: 40287
 scriptlet: 20871
 html: 0
listset (total-discarded, last-updated): 
 added: 
  ublock-annoyances: 5083-8, never
 default: 
  user-filters: 6-0, never
  easylist: 66276-49, 16m
  easyprivacy: 31840-51, 16m
  plowe-0: 3735-944, 16m
  ublock-abuse: 70-0, 16m
  ublock-badware: 7160-129, 16m
  ublock-filters: 33142-103, 16m
  ublock-privacy: 382-75, 16m
  ublock-quick-fixes: 326-41, 16m
  ublock-unbreak: 2021-39, 16m
  urlhaus-1: 5659-0, 16m
filterset (user): [array of 6 redacted]
trustedset: 
 removed: 
  chrome-extension-scheme
  chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 170 ms (selfie)
 maxAssetCacheWait: 48 ms
popupPanel: 
 blocked: 11
 network: 
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 8
  spotifycdn.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists in about 10 minutes (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

**Comment by DavidSalomonDev** [comment]
> 

I had the same issue, I can confirm that the "Purge all caches" button works, I did a quick test, but for now it's working right
