### ISSUE TITLE
act-on.com: detection

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#18196]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://act-on.com/`

### Category

detection

### Description

detection `||success.act-on.com^` in EasyPrivacy
exception
```
@@||success.act-on.com/acton/content/aoAdDetect.js$script,~third-party
```
resolves the issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/91396482/db38b025-d34a-4607-b6ee-42be85e2a964)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 85396
 cosmetic: 40942
 scriptlet: 21254
 html: 1115
listset (total-discarded, last-updated): 
 removed: 
  urlhaus-1: null
  plowe-0: null
 added: 
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 6h
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1694-0, 12h.1m
  https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 4d.3h.38m
  ublock-annoyances: 5042-4, 1d.10h.36m
 default: 
  user-filters: 817-13, never
  ublock-filters: 34000-102, 12h.1m
  ublock-badware: 7143-0, 1d.10h.36m
  ublock-privacy: 442-0, 1d.10h.36m
  ublock-abuse: 70-70, 1d.10h.36m
  ublock-unbreak: 2031-0, 1d.10h.36m
  ublock-quick-fixes: 329-0, 14m
  easylist: 66036-312, 1d.10h.36m
  easyprivacy: 31838-1119, 1d.10h.36m
filterset (user): [array of 750 redacted]
switchRuleset: 
 added: [array of 3 redacted]
hostRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 349 ms (selfie)
 maxAssetCacheWait: 188 ms
 unsuspendAfter: 113 ms
popupPanel: 
 blocked: 3
 network: 
  act-on.com: 2
  googletagmanager.com: 1
 cosmetic: 
  ##*:style(border-radius:0px !important;)
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr What do you think?

**Comment by krystian3w** [comment]
Test:

```adb
act-on.com##+js(set, aoAdBlockDetected, false)
```

if fails, then maybe needed aost?
