### ISSUE TITLE
AllMusic has implemented a new anti-adblock

### ISSUE THREAD

**Issue by donwiss** [uBlockOrigin/uAssets#182]
http://allmusic.com/

### Describe the issue

Ad blocking software is detected and you cannot reach the site.

### Versions

- Firefox 49.0.2
- uBlock Origin version: v1.9.16

### Settings

Default settings

**Comment by Atavic** [comment]
There's a GoogleAnalytics object located at: `http://zt.allmusic.com/allmusic/header` 
that activates the popup regarding adblock use. Try blocking it, or just block _Javascript_.

**Comment by nfdisco** [comment]
This solution here works for me but it requires disabling a whole bunch of filters unrelated to AllMusic:
https://github.com/reek/anti-adblock-killer/issues/1941#issuecomment-255449358

**Comment by gorhill** [comment]
> it requires disabling a whole bunch of filters unrelated to AllMusic

It's almost equivalent to disabling your blocker, i.e. doing what the site is asking.

**Comment by Atavic** [comment]
I'm going to ask here some questions: Ia Allmusic a trusted site for the user?
If so, you should whitelist it. Moreover, if you login to a site you probably have to enable most of its page code. However I have an hardened setup with no cookies or javascript and can look at bands or do searches there.

**Comment by IDKwhattoputhere** [comment]
> Ia Allmusic a trusted site for the user?

The site loads a ton of third-party scripts. So the question should be: Can you trust every request to every party on that site and the requests to additional parties that will result out of them?

**Comment by Atavic** [comment]
It has spotify as streaming option and then amazon links.

**Comment by IDKwhattoputhere** [comment]
??
![](https://cloud.githubusercontent.com/assets/16030872/20022902/0bf142ee-a2dd-11e6-9e0f-680546fc55f4.png)

**Comment by okiehsch** [comment]
Maybe I am not getting something, but the only thing I have to do to access this site,
is to disable cookies.
I can read the articles, listen to the streams, watch the videos etc.
The only thing I can´t do is logging in for obvious reasons.

**Comment by uBlock-user** [comment]
It's back at it. Happening again.
