### ISSUE TITLE
youtube vanced fake sites

### ISSUE THREAD

**Issue by bookarticle** [uBlockOrigin/uAssets#18207]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

vanced is discontinued

### URL(s) where the issue occurs.

`https://vanced.me/`

### uBO version

N/A

### Browser name and version

N/A

### Settings

N/A

**Comment by bookarticle** [comment]
`https://vancedapp.io/`

**Comment by JobcenterTycoon** [comment]
`https://www.vanced-official.com/` -> https://www.virustotal.com/gui/file/cc2ec69d71c0127683771317609f9d1e0fa86099f36b9322005fc38d549ad8a1?nocache=1

All other are clean (0 VT detections)

**Comment by Yuki2718** [comment]
We never block sites only because they're not official. Provide enough and clear evidence for each site to be malicious.

**Comment by mapx-** [comment]
When you'll be able to provide clear information, steps to reproduce come back here, otherwise for 
malicious stuff report here: https://gitlab.com/malware-filter/urlhaus-filter#malicious-url-blocklist
