### ISSUE TITLE
fitgirl.cc

### ISSUE THREAD

**Issue by bookarticle** [uBlockOrigin/uAssets#18206]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I believe it's not the "real" fitgirl-repacks site

### URL(s) where the issue occurs.

`https://fitgirl.cc/`

### uBO version

N/A

### Browser name and version

N/A

### Settings

N/A

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/issues/18207#issuecomment-1559493733

**Comment by JobcenterTycoon** [comment]
The downloads just open `https://brightadnetwork.com/jump/next.php?r=6777522` on my end.

**Comment by Yuki2718** [comment]
Was there a problem for `/jump/next.php?r=$doc`? I occaisonally see this pattern.
