### ISSUE TITLE
[NSFW] 173.249.8.3: detection

### ISSUE THREAD

**Issue by Jokopentil** [uBlockOrigin/uAssets#18202]
URL: `https://173.249.8.3/doggy-pacar-di-balkon-hotel/`

<details><summary>Screenshot</summary>

![20230523_160243_rmscr.jpg](https://github.com/uBlockOrigin/uBOL-issues/assets/114223791/c30152ea-e4a5-40ed-9afa-d24dd942eb95)

</details>

**Comment by bookarticle** [comment]
nsfw tag

**Comment by bookarticle** [comment]
```
*$script,redirect-rule=noopjs,domain=vgembed.com
```
