### ISSUE TITLE
fitgirlrepacksite.com

### ISSUE THREAD

**Issue by bookarticle** [uBlockOrigin/uAssets#18205]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

looks like a fake fitgirl-repacks site to me

### URL(s) where the issue occurs.

`https://fitgirlrepacksite.com/`

### uBO version

N/A

### Browser name and version

N/A

### Settings

.

**Comment by mapx-** [comment]
@bookarticle report directly such sites to specialized lists, foe example the enabled one in uBO:
https://gitlab.com/malware-filter/urlhaus-filter#malicious-url-blocklist
