### ISSUE TITLE
New Video ad @ www.chip.de

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uAssets#1820]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.chip.de/artikel/iOS-11.3-kurz-vor-Release_136585896.html`

### Describe the issue

Video Ad after 2 sec playback

### Screenshot(s)

-
### Versions

- Browser/version: [Firefox 60beta7]
- uBlock Origin version: [1.15.19beta4]

### Settings

uBO's default settings

### Notes

-

**Comment by mapx-** [comment]
test these filters:
```
||damoh.curloc.com/*$media,redirect=noopmp3-0.1s,domain=chip.de
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=chip.de
```

**Comment by akks1981** [comment]
first it works, but after after i close firefox clear the cache and look the viedeo again the video stops and goes away!

**Comment by akks1981** [comment]
i dont know why but now it seems to work! Thx for the help!

**Comment by okiehsch** [comment]
Does
`||damoh.curloc.com^$media,domain=chip.de`
work for you?

You have to remove
`||damoh.curloc.com/*$media,redirect=noopmp3-0.1s,domain=chip.de`
The filter
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=chip.de`
is already part of `EasyList Germany`.

**Comment by okiehsch** [comment]
I can fix the issue in Chrome by adding
`||damoh.chip.de^$xmlhttprequest,redirect=nooptext,domain=chip.de`
but I can not add this line to `uBO-filters`, because it will break the video player for all Firefox users.

**Comment by okiehsch** [comment]
`chip.de##script:inject(setInterval-defuser.js, fireEvent, 500)`
works on my end with Chrome and Firefox.

**Comment by zaphodbeebblebrox** [comment]
Works for me on Firefox and Chrome.
