### ISSUE TITLE
personality-database.com: nuisance

### ISSUE THREAD

**Issue by natsume-shokogami** [uBlockOrigin/uAssets#18216]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.personality-database.com/profile/311006/touhou-fandom-if-you-like--mbti-personality-type`

### Category

nuisance

### Description

It uses a pop up that block you from scrolling to see to content of the page and ask to login to see the content in 50% of the times when you're not logging in (sometimes it block, sometimes not, if not refresh the page).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 113
filterset (summary): 
 network: 95598
 cosmetic: 30267
 scriptlet: 17584
 html: 942
listset (total-discarded, last-updated): 
 added: 
  VIE-1: 1918-17, 4h.20m
 default: 
  user-filters: 10-0, never
  ublock-filters: 34174-365, 2d.6h.19m
  ublock-badware: 7137-0, 2d.6h.14m
  ublock-privacy: 442-1, 6d.13h.26m
  ublock-abuse: 70-70, 6d.13h.25m
  ublock-unbreak: 2036-1, 2d.6h.13m
  ublock-quick-fixes: 367-1, 26m
  adguard-mobile: 8779-122, 2d.4h.53m
  easylist: 65958-17476, 4d.15h.25m
  easyprivacy: 31822-625, 5d.13h.25m
  urlhaus-1: 6774-1, 4h.19m
  plowe-0: 3737-4, 5d.17h.20m
filterset (user): [array of 10 redacted]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 largeMediaSize: 54
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1285 ms (selfie)
 maxAssetCacheWait: 330 ms
popupPanel: 
 blocked: 3
 network: 
  personality-database.com: 1
  ezojs.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by dportvine** [comment]
Сannot log in to account because of this rule.

<details>
<summary>Video</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/86ef64b8-68e0-4875-a2fc-adf964fb2456
</details>
