### ISSUE TITLE
tf1.fr: ads

### ISSUE THREAD

**Issue by Soulivan71** [uBlockOrigin/uAssets#18211]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tf1.fr/tf1/koh-lanta/videos/koh-lanta-le-feu-sacre-du-16-mai-2023-partie-1-67160961.html`

### Category

ads

### Description

Im having ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 112628
 cosmetic: 47806
 scriptlet: 17638
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  FRA-0: 28502-31, 2m
  easylist: 66279-395, 2m
  easyprivacy: 31839-338, 2m
  plowe-0: 3735-967, 2m
  ublock-abuse: 70-1, 2m
  ublock-badware: 7165-145, 2m
  ublock-filters: 33128-189, 2m
  ublock-privacy: 382-75, 2m
  ublock-quick-fixes: 326-36, 1m
  ublock-unbreak: 2020-42, 1m
  urlhaus-1: 7053-1, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 5388 ms
 maxAssetCacheWait: 39 ms
popupPanel: 
 blocked: 54
 network: 
  abtasty.com: 1
  estat.com: 1
  facebook.net: 1
  facil-iti.app: 1
  fwmrm.net: 1
  googletagmanager.com: 5
  mediarithmics.com: 1
  mmtro.com: 6
  sentry-cdn.com: 1
  stickyadstv.com: 31
  trustcommander.net: 1
  usabilla.com: 1
  xiti.com: 3
```
</details>

**Comment by mapx-** [comment]
@Soulivan71 ads, what ads ? video ads ? when ? at the beginning, in the middle, any x minutes ?

**Comment by Soulivan71** [comment]
@gorhill Im connect to my account already

**Comment by Soulivan71** [comment]
> @Soulivan71 ads, what ads ? video ads ? when ? at the beginning, in the middle, any x minutes ?beggining and middle

**Comment by mapx-** [comment]
@Alex-302 are you able to reproduce the ads ?

**Comment by mapx-** [comment]
@Procyon-b could you test too ?

**Comment by Procyon-b** [comment]
I don't see the ads.
I live in Belgium. They may only have ads to serve in France. If they are geo-locating.

**Comment by mapx-** [comment]
I used a Marseille ip, no ads too.

**Comment by Alex-302** [comment]
@mapx- I don't see ads with ad blocker (AdGuard Base + French filters).

**Comment by Soulivan71** [comment]
Maybe this can help u idk 
![image](https://github.com/uBlockOrigin/uAssets/assets/36502190/7ee1fc50-a114-4097-a8c0-b4658196cd11)

**Comment by mapx-** [comment]
@Soulivan71 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Soulivan71** [comment]
I already tri this

**Comment by mapx-** [comment]
I watched again 5 minutes from
`https://www.tf1.fr/tf1/koh-lanta/videos/koh-lanta-le-feu-sacre-du-23-mai-2023-partie-1-18280919.html`

no ad

If you really followed **ALL the indications** above, I cannot help anymore, you have to investigate on your side.
