### ISSUE TITLE
truyenbanquyen.com: nuisance

### ISSUE THREAD

**Issue by jesse-tong** [uBlockOrigin/uAssets#18217]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://truyenbanquyen.com/`

### Category

nuisance

### Description

This website has an anti-copy/cut/paste overlay when you trying to copy or select a text, or right click on any image or element on this page; an popup in Vietnamese language will show up, saying "Warning: Please don't copy" for a few seconds. Disabliing Javascript will work, some elements will break but the content still mostly retain. Trying to screenshot through PrntScr will show a popup not allow you to screenshot, using screenshot software will work but it's very difficult to edit it out and the popup fades out fast enough to make you not be able to screenshot them without preparation.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93936
 cosmetic: 38767
 scriptlet: 17479
 html: 943
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 33935-75, 2d.12h.53m
  ublock-badware: 7143-0, 2d.12h.53m
  ublock-privacy: 442-0, 2d.12h.53m
  ublock-abuse: 70-70, 2d.12h.53m
  ublock-unbreak: 2031-1, 2d.12h.53m
  ublock-quick-fixes: 339-0, 5h.39m
  easylist: 66101-663, 2d.12h.53m
  easyprivacy: 31838-615, 2d.12h.53m
  urlhaus-1: 7071-1, 20h.8m
  plowe-0: 3735-3, 2d.12h.53m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 682 ms (selfie)
 maxAssetCacheWait: 171 ms
popupPanel: 
 blocked: 22
 network: 
  truyenbanquyen.com: 5
  amazon-adsystem.com: 1
  google-analytics.com: 1
  googlesyndication.com: 10
  googletagmanager.com: 3
  media.net: 1
  quantserve.com: 1
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `uBlock filters – Annoyances` list and test again?

**Comment by natsume-shokogami** [comment]
I forget that it exists, I turned it on and update it and now I can copy in that site. Anyways, thank you.
