### ISSUE TITLE
player.eska.pl: detection

### ISSUE THREAD

**Issue by andrzej928** [uBlockOrigin/uAssets#18218]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://player.eska.pl/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_7](https://github.com/uBlockOrigin/uAssets/assets/1771441/b2c6eee2-beb6-4d68-bfed-693ed77d8dff)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 97198
 cosmetic: 68083
 scriptlet: 17891
 html: 1192
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 22968-50, 1d.23h.35m
 default: 
  user-filters: 0-0, never
  ublock-filters: 33884-40, 3d.21h.21m
  ublock-badware: 7117-1, 3d.21h.20m
  ublock-privacy: 442-0, 1d.19h.29m
  ublock-abuse: 70-70, 1d.21h.30m
  ublock-unbreak: 2031-2, 3d.21h.19m
  ublock-quick-fixes: 362-34, 22h.16m
  easylist: 66035-692, 22h.19m
  easyprivacy: 31838-617, 1d.23h.36m
  urlhaus-1: 8396-1, 22h.18m
  plowe-0: 3737-2, 8d.45m
  POL-0: 7947-32, 22h.17m
  POL-2: 1278-45, 1d.23h.34m
filterset (user): [empty]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 379 ms (selfie)
 maxAssetCacheWait: 72 ms
popupPanel: 
 blocked: 44
 network: 
  eska.pl: 2
  3lift.com: 2
  adform.net: 1
  adnxs.com: 6
  casalemedia.com: 1
  connectad.io: 2
  criteo.com: 3
  criteo.net: 3
  doubleclick.net: 1
  facebook.com: 1
  gemius.pl: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  indexww.com: 1
  lijit.com: 1
  openx.net: 2
  pollster.pl: 1
  pubmatic.com: 2
  rubiconproject.com: 2
  smartadserver.com: 3
  teads.tv: 2
  upscore.com: 1
  visx.net: 2
  wp.pl: 1
 cosmetic: 
  ##.zpr_top_1,#placement2,.center.t2.color13,.banner-750.fontregular,.active.zpr_box,.zpr_combo
  ##.fb-customerchat
  ##[id*=\"-ad-container\"]
  ##.fb_reset
  ##.cookies:not(body):not(html):not(#page):not(#container):not(.wrapper):not(.popup-newsletter):not(.js-cookies)
  ##body:style(overflow: auto !important)
  #@#html, html > body:style(overflow: auto !important;)
```
</details>

**Comment by krystian3w** [comment]
"Hard", can pause autoplay:

```html
      <script>
         setTimeout(detectAdblock, 3000);

         function detectAdblock() {
            if (typeof adblockBait === "undefined") {
               if (document.getElementById('radio-stream') && typeof(videojs) !== "undefined") {
                  videojs('radio-stream').pause()
               }
               const adblockDetectedImgUrl = "https://cdn.files.smcloud.net/t/eska-adblock-desktop.png";
               const infoUrl = "";
               showAdblockDetectedBanner(adblockDetectedImgUrl, infoUrl);
               document.body.classList.add("noscroll");
            }
         }

      </script>
```

**Comment by krystian3w** [comment]
Same family:

`https://player.voxfm.pl/`

**Comment by andrzej928** [comment]
it's work!
Thank you :)
