### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by alphaaurigae** [uBlockOrigin/uAssets#18210]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/playlist/37i9dQZF1E36MRmIo47YsA`

### Category

ads

### Description

spotify is playing ads for 2 days, always worked fine till now,

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 92460
 cosmetic: 38761
 scriptlet: 17493
 html: 944
listset (total-discarded, last-updated): 
 default: 
  user-filters: 5-0, never
  ublock-filters: 33958-39, 1d.5h.27m
  ublock-badware: 7148-0, 1d.5h.26m
  ublock-privacy: 442-0, 3d.11h.37m
  ublock-abuse: 70-70, 3d.11h.36m
  ublock-unbreak: 2031-0, 1d.5h.25m
  easylist: 65983-249, 3d.13h.38m
  easyprivacy: 31822-74, 3d.15h.39m
  urlhaus-1: 5659-0, 11h.22m
  plowe-0: 3735-942, 17h.23m
  ublock-quick-fixes: 367-38, 11h.21m
filterset (user): [array of 5 redacted]
trustedset: 
 added: [array of 5 redacted]
 removed: 
  about-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 326 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel: 
 blocked: 14
 network: 
  doubleclick.net: 5
  googleoptimize.com: 1
  googletagmanager.com: 1
  scdn.co: 2
  sentry.io: 4
  spotifycdn.com: 1
 cosmetic: 
  ##.bYHWD_eQ1jAh3sAKTHtr.deomraqfhIAoSB3SgXpu
  ##.W0TACB7OY0iXtKVOtEhY.H0HbpIM3UrcupWIAjLWu
```
</details>

**Comment by mapx-** [comment]
update your filter lists
