### ISSUE TITLE
ldjam.com: breakage

### ISSUE THREAD

**Issue by 0xE0D59** [uBlockOrigin/uAssets#18220]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ldjam.com/`

### Category

breakage

### Description

While browsing the website using Chrome and uBlock Origin and clicking between the website logo and My Game button at the top, the following elements keep getting duplicated:

![image](https://github.com/uBlockOrigin/uAssets/assets/45870990/9c59290f-2980-4e5b-91f1-8ebf4c667907)

This is not the case when uBlock Origin is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95209
 cosmetic: 46226
 scriptlet: 17655
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  POL-0: 7943-11, 20h.38m
  POL-2: 1275-13, 1d.2h.40m
  easylist: 65960-72, 5d.5h.26m
  easyprivacy: 31822-46, 4d.21h.20m
  plowe-0: 3737-946, 11d.1h.47m
  ublock-abuse: 70-0, 10d.23h.44m
  ublock-badware: 7113-127, 3d.19h.33m
  ublock-filters: 33028-139, 3d.3h.32m
  ublock-privacy: 394-75, 10d.23h.45m
  ublock-quick-fixes: 337-37, 5h.41m
  ublock-unbreak: 2020-41, 3d.19h.34m
  urlhaus-1: 7053-1, 22h.39m
filterset (user): [empty]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 645 ms (selfie)
 maxAssetCacheWait: 77 ms
popupPanel: 
 blocked: 5
 network: 
  google.com: 2
  translate.googleapis.com: 3
 cosmetic: 
  ##.sidebar-sponsor
```
</details>

**Comment by mapx-** [comment]
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/fa022814-29d3-4a59-b635-1bf938e234bb)
