### ISSUE TITLE
tech20.pcreview.me: detection

### ISSUE THREAD

**Issue by superislam** [uBlockOrigin/uAssets#18229]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tech20.pcreview.me/apple-iphone-14-improvements/?se=4e54417a4e7a5131&dlisting=aHR0cHM6Ly9tMjUucmV2aWV3aHViLnZpcA==HhZ35wNXMr,cnn6CEMc97DPQxMpbBKY7I_OPgL69P0fp7bnwlOgFrAvyxrVQPXcFv6mTc1bv2jYr86QgKvyje6Ect0Hp80AncqhY-uYRWTJ596wF2PvX-nIROXc974Smv3HTyCBT772BDXY8EZvUi-ZHHNoqGic_6KYAYuhQNIsHXoxtdUgtFpjmbyeEoBDWNqDzQPlmlC1zjkoH5hlyFXupQ75QgBVIf3ni5DXdQzU_mPvfUHPtbc4fenap4ZeO96PKZm2f1yCcvX5uxQQZTZWIXw-zxt_xNuaSdn5VgsJpQkD1GzPRbCdItnczblCRzhNCOLnPWnxAR_XXyYMnSdlJALEfX7B4NanGFPXqpmqGjtFEes0oUoAbQ7IcCXjYIzMfqwHIcICUsdf57d5iGkNtlrfL78ESzPgmOnUmXn1ZNQgPcI_wclRuhLLQirH1guXKrwq5tzb0t1m31cL5MWu1lWLz4iQRO21eCXGIdd5LFZqw6aowFXog0fUW_WFU0--BG1U08NYSdO99DVLxSNRhKr6NGUFkhhMl4_2mnVzAGXcxMI8gATApg3kJwP2wa9YJ9C6M_aOfRU9DL3hXXh3iAWiw1UkoQlDaP3aP2scwNr1SSJrERqzWd6SnCLp2YL4c_Y33299dfd5r_vgH0lZ4KuUTSKlEXglLYjMJlX0rDjXVQC3PK0jKDfofOfbzPgX16MNFxoz0UAN5bmHSdj7ukPLjSgBCrZhf9DlV3lpuRVXEFqVeGYDPGYyosQl-lhUADnutcltqNe`

### Category

detection

### Description

this page detects ublock and forces me to disable it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/26907307/786250c7-83c3-4184-9161-5a4d50b4a7ae)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 322872
 cosmetic: 39466
 scriptlet: 17468
 html: 933
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts: 232157-4649, 2d.14h.32m
  ara-0: 2783-0, 23h.10m
 default: 
  user-filters: 7-0, never
  ublock-filters: 33934-75, 2d.14h.32m
  ublock-badware: 7159-0, 2d.14h.32m
  ublock-privacy: 422-0, 2d.14h.32m
  ublock-abuse: 70-70, 2d.14h.32m
  ublock-unbreak: 2031-1, 2d.14h.32m
  ublock-quick-fixes: 339-0, 23m
  easylist: 65983-1141, 5d.11h.3m
  easyprivacy: 31822-621, 5d.11h.3m
  urlhaus-1: 7012-1, 23h.10m
  plowe-0: 3735-3, 5d.11h.3m
filterset (user): [array of 7 redacted]
switchRuleset: 
 removed: 
  no-csp-reports: * true
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1111 ms (selfie)
 maxAssetCacheWait: 577 ms
popupPanel: 
 blocked: 9
 network: 
  demand.supply: 3
  googlesyndication.com: 1
  googletagmanager.com: 2
  greeter.me: 2
  jsdelivr.net: 1
```
</details>

**Comment by mapx-** [comment]
provide your orginal starting link
