### ISSUE TITLE
Resource Abuse - Coinhive

### ISSUE THREAD

**Issue by publicarray** [uBlockOrigin/uAssets#1822]
Not sure if these should be added since it is trivial for the bad guys to create new urls

>The “classic” one makes a clear reference to coinhive[.]com, which can easily be detected and blocked. The second one is similar in syntax but instead uses a different hostname (npcdn1[.]now[.]sh). While it may not seem like a big difference, it’s enough to bypass the majority of blacklists.
>[...]
>mxcdn1[.]now.sh
>mxcdn2[.]now.sh
>npcdn1[.]now.sh
>sxcdn02[.]now.sh
>sxcdn3[.]now.sh
>sxcdn4[.]now.sh
>sxcdn6[.]now.sh

Source: https://blog.malwarebytes.com/threat-analysis/2018/03/malicious-cryptomining-and-the-blacklist-conundrum/

>jqcdn01.herokuapp[.]com/jquery.js
    jqcdn2.herokuapp[.]com/jquery.js
    jqcdn03.herokuapp[.]com/jquery.js
    mxcdn1.now[.]sh/jquery.js
    npcdn1.now[.]sh/jquery.js
    sxcdn1.herokuapp[.]com/jquery.js
    sxcdn02.now[.]sh/jquery.js
    sxcdn4.now[.]sh/jquery.js
    sxcdn5.herokuapp[.]com/jquery.js
    sxcdn6.now[.]sh/jquery.js
    wpcdn1.herokuapp[.]com/jquery.js
    mxcdn2.now[.]sh/jquery.js

Source: https://blog.sucuri.net/2018/01/malicious-cryptominers-from-github-part-2.html

I originally got informed from https://www.bleepingcomputer.com/news/security/in-browser-cryptojacking-is-getting-harder-to-detect/

**Comment by okiehsch** [comment]
Well, the minning script bypasses the blocklists, but the actual mining **is blocked**, atleast at the domains I looked at.
For example
![unbenannt](https://user-images.githubusercontent.com/16838044/37999203-1dd8dc8a-3222-11e8-8bae-f4865a39eea2.PNG)

**Comment by publicarray** [comment]
Ah that's a relief. Now I'm just worried that the scripts could be bundled together. 
Anyway thanks for looking in to this.
