### ISSUE TITLE
thecubexguide.com: ads

### ISSUE THREAD

**Issue by 0x6900** [uBlockOrigin/uAssets#18228]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://thecubexguide.com/domain-vs-server-name/`

### Category

ads

### Description

ads left overs and Anti adblocker is also not working

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94007
 cosmetic: 38964
 scriptlet: 17564
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 40-0, never
  easylist: 66522-49, 27m
  easyprivacy: 31812-52, 27m
  plowe-0: 3735-944, 27m
  ublock-abuse: 70-0, 27m
  ublock-badware: 7131-129, 5m
  ublock-filters: 33202-104, 4m
  ublock-privacy: 381-75, 4m
  ublock-quick-fixes: 343-48, 4m
  ublock-unbreak: 2014-35, 4m
  urlhaus-1: 6874-1, 4m
filterset (user): [array of 40 redacted]
trustedset: 
 added: [array of 49 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4267 ms (selfie)
 maxAssetCacheWait: 181 ms
popupPanel: 
 blocked: 39
 network: 
  adoto.net: 2
  ampproject.org: 12
  doubleclick.net: 4
  google.co.in: 1
  google.com: 3
  googlesyndication.com: 14
  googletagmanager.com: 1
  jsdelivr.net: 2
```
</details>

**Comment by krystian3w** [comment]
`##.stickyads_Desktop_Only`?

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17548

provide real starting link as in issue #17548

**Comment by krystian3w** [comment]
If we don't have a working starting link then we won't reproduce, we don't have a glass/crystal ball 🔮 that will help us set correct fake cookies, local/sessionStorage or referrer (as the starting link is confidential/lost).

You yourself can open a sent link with a junk article and then there is no anti-adblock or too much advertising residue.

**Comment by krystian3w** [comment]
This is your starting link rather than the link the submission author clicked.

In addition, these "proxies" were deemed to be writing workarounds (for ad restoration/modal anti-adblock) too quickly to fix.

**Comment by djo5296** [comment]
being detected

**Comment by mapx-** [comment]
to be discussed here: https://github.com/uBlockOrigin/uAssets/discussions/17361
