### ISSUE TITLE
yandex.ru: ads placeholders

### ISSUE THREAD

**Issue by vehlwn** [uBlockOrigin/uAssets#18226]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yandex.ru/pogoda`

### Category

ads

### Description

Yandex recently redesigned /pogoda page and added banners at the bottom. For now they are partly blocked and I can see empty rectangles.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot](https://github.com/uBlockOrigin/uAssets/assets/36479428/b967d4c4-577b-4487-bb66-13d4393ffeb0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 331612
 cosmetic: 244925
 scriptlet: 41694
 html: 1132
listset (total-discarded, last-updated): 
 added: 
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1636-0, now
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7250-0, now
  https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt: 42535-714, now
  adguard-generic: 71106-6328, 3m
  adguard-mobile: 8799-17, 3m
  adguard-spyware-url: 1037-20, 2m
  block-lan: 47-0, 2m
  curben-phishing: 103856-41, 1m
  curben-pup: 199-0, now
  adguard-annoyance: 68756-5575, now
  adguard-social: 20542-681, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-annoyance: 90656-80435, now
  fanboy-cookiemonster: 47234-267, now
  fanboy-social: 16369-17, now
  ublock-annoyances: 5038-4, now
  dpollock-0: 11517-1224, now
  RUS-0: 39552-347, now
  adguard-spyware: 41144-1222, never
 default: 
  user-filters: 38-0, never
  ublock-filters: 34073-135, 3m
  ublock-badware: 7133-4, 3m
  ublock-privacy: 421-0, 3m
  ublock-abuse: 70-70, 3m
  ublock-unbreak: 2025-7, 3m
  ublock-quick-fixes: 341-2, 3m
  easylist: 66500-1052, 2m
  easyprivacy: 31807-13920, 2m
  urlhaus-1: 8396-1, 2m
  plowe-0: 3735-97, now
filterset (user): [array of 38 redacted]
switchRuleset: 
 added: [array of 48 redacted]
 removed: 
  no-csp-reports: * true
modifiedUserSettings: 
 cnameUncloakEnabled: false
 contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 567 ms (selfie)
 maxAssetCacheWait: 406 ms
popupPanel: 
 blocked: 47
 network: 
  yandex.ru: 47
 cosmetic: 
  ##.b-statcounter + div[class] > div[id][class]
  ##[class*=\"segment__container\"] > div > [class^=\"card \"][class*=\"_\"]
  ##.meteum-promo
  ##body[data-bem*=\"/weather/\"]:style(overflow: auto !important; position: unset !important;)
```
</details>

**Comment by dportvine** [comment]
I can't reproduce, [screen](https://i.imgur.com/QPBuH86.png).

<details>

```yaml
uBlock Origin 1.49.3rc4:
 since: 42m
Firefox: 113
filterset (summary):
 network: 117552
 cosmetic: 127240
 scriptlet: 24106
 html: 1133
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26374-49, 41m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1636-0, 7m
  fanboy-cookiemonster: 47234-437, 1m
  ublock-annoyances: 5038-4, 41m
  RUS-0: 39552-285, 41m
 default:
  user-filters: 0-0, never
  ublock-filters: 34075-92, 41m
  ublock-badware: 7133-1, 41m
  ublock-privacy: 421-0, 41m
  ublock-unbreak: 2025-7, 41m
  ublock-quick-fixes: 315-2, 41m
  easylist: 66500-717, 41m
  easyprivacy: 31807-920, 41m
  urlhaus-1: 6874-1, 41m
  plowe-0: 3735-9, 41m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 528 ms (selfie)
 maxAssetCacheWait: 322 ms
popupPanel:
 blocked: 10
 network:
  yandex.ru: 2
  yastatic.net: 8
 extended:
  ##.adv_pos_popup
  ##.b-page__container .footer__links > .links-section:last-of-typ…
  ##.meteum-promo
  ##[class*="header"] > .yaplus
  ##div[id^="R-I-"]
  ##.adv
  ##[class*="segment__container"] > div > [class^="card "][class*=…
  ##.forecast-details > .card:has(> [class*="adv"])
  ##.b-page:style(padding-top: 0 !important)
  ##+js(cookie-remover, /^bltsr$|^JPIqApiY$|^specific$|^substantia…
  ##+js(json-prune, direct rtb seatbid)
  ##+js(remove-attr, data-counter, .serp-list a)
  ##+js(no-setTimeout-if, Ya.Rum.getSetting, 15)
  ##+js(abort-on-property-read, Ya.loaderVer)
  ##+js(cookie-remover, tvoid)
  ##+js(set-constant, __AAB__, false)
  ##+js(set-constant, Object.prototype._getAdConfig, noopFunc)
  ##+js(set-constant, Object.prototype.getHoneypot, null)
  ##+js(set-constant, Object.prototype.isOpenImageUnauthPopupEnabl…
  ##+js(set-constant, Object.prototype.los, null)
```
</details>

**Comment by vehlwn** [comment]
Try to refresh it a few times.

**Comment by dportvine** [comment]
>Try to refresh it a few times.

[Gif](https://imgur.com/WsIw2r5)

@dimisa-RUAdList

**Comment by vehlwn** [comment]
Yeah. I can see now. They are randomly disappearing. https://youtu.be/lV2cg2rfkZ0
(Sorry, gihub doesn't accept files bigger than 10 MB, and imgur - longer than 1 min.)

**Comment by dimisa-RUAdList** [comment]
Apparently, the work of uBlock Origin is broken either by using conflicting filters, or by third-party blocking tools, be it programs, extensions, or DNS filtering.

However, the work of the Counters was conceived in such a way as to at least partially neutralize the consequences of such conflicts.

Fix: https://github.com/easylist/ruadlist/commit/e97c6c1c8769b4663e3b198fb556cdb556cd25f2

**Comment by vehlwn** [comment]
> be it programs, extensions, or DNS filtering

I think you are right. I used filtering Adguard DNS server all the time. When I switched to ISP's default server the issue's gone. Turned out this was not an issue with Ublock filters.

**Comment by dimisa-RUAdList** [comment]
This is a known issue. You can find more information here:
[Known bugs 1](https://forum.ru-board.com/topic.cgi?forum=5&topic=51141&start=0&limit=1&m=12#1) 
[Known bugs 2](https://forum.ru-board.com/topic.cgi?forum=5&topic=51141&start=0&limit=1&m=13#1)
[Recommendations](https://forum.ru-board.com/topic.cgi?forum=5&topic=51141&start=0&limit=1&m=3#1)

**Comment by vehlwn** [comment]
> You should read and follow the prerequisites instead of just ticking them.

You are right! Sorry for bothering.
