### ISSUE TITLE
beta.bitmask.app: breakage

### ISSUE THREAD

**Issue by cryptoquick** [uBlockOrigin/uAssets#18223]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When a page makes a request to this URL, it's blocked:
`https://mempool.space/testnet/api/scripthash/e99630eb1ecca50046c5c53a3aa59e0cbb41520d80751bf623ec9d182e4f982e/txs`

Note, URLs that aren't to testnet are fine, for example, this works fine:
`https://mempool.space/api/scripthash/6b54547536c4af7e12b6fd4981dc7260a811a809ac76ccdaa785cba1669df692/txs`

It's only when the URL contains testnet that it fails.

### URL(s) where the issue occurs.

This breaks applications like the one here:
`https://beta.bitmask.app`

### Screenshot(s)

![Screenshot from 2023-05-24 17-31-54](https://github.com/uBlockOrigin/uAssets/assets/285690/06c2b590-b614-4d49-8713-7da5a2e6e421)

### uBO version

1.49.2

### Browser name and version

Vivaldi 6.0.2979.22

### Settings

None

**Comment by gorhill** [comment]
> `/^https?:\/\/[0-9a-z]{5,}\.(digital|website|life|guru|space)\/[a-z0-9]{6,}\//$script,third-party,xmlhttprequest,domain=~bitrix24.life|~mempool.space|~scribble.ninja|~scribble.website|~traineast.co.uk`

That filter is from EasyList, report to EasyList maintainers: <https://github.com/easylist/easylist/issues>

cc @ryanbr, @Khrin

**Comment by krystian3w** [comment]
Maybe good practise will be close after github actions cover commits?

https://github.com/uBlockOrigin/uAssets/actions/workflows/update-easylist.yml

![image](https://github.com/uBlockOrigin/uAssets/assets/35370833/d02b49d7-11e6-490f-b5df-6749668ff514)

vs

![image](https://github.com/uBlockOrigin/uAssets/assets/35370833/4e9b2c26-4f25-4b20-b5b5-f7c27000afe6)

**Comment by cryptoquick** [comment]
This seems to be an issue that's dragging on and affecting more users, see:
https://github.com/easylist/easylist/issues/16552
How can I get more eyes on this?

**Comment by krystian3w** [comment]
Fixed long time ago, no possible better: https://github.com/uBlockOrigin/uAssets/commit/3e9d060cf43d2c35e75dc9e04423e4a5130168c8
