### ISSUE TITLE
userstyles.org: breakage

### ISSUE THREAD

**Issue by sacred-mercy** [uBlockOrigin/uAssets#18234]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://userstyles.org/`

### Category

breakage

### Description

Site don't even load

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/71167081/c1da7148-c190-4028-a357-0f174ab3f4f5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 115
filterset (summary): 
 network: 59664
 cosmetic: 105713
 scriptlet: 25501
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  easyprivacy: null
  plowe-0: null
  urlhaus-1: null
 added: 
  adguard-annoyance: 68718-1713, 1d.12h.30m
  fanboy-cookiemonster: 47146-19517, 6d.13h.1m
  ublock-annoyances: 5070-214, 5d.4h.6m
 default: 
  user-filters: 60-0, never
  easylist: 66210-16899, 1d.12h.31m
  ublock-abuse: 70-0, 2d.2m
  ublock-badware: 7144-128, 3d.14h.49m
  ublock-filters: 33079-710, 3d.14h.48m
  ublock-privacy: 382-73, 1d.12h.32m
  ublock-quick-fixes: 337-37, 13h.2m
  ublock-unbreak: 2020-12, 3d.7h.12m
filterset (user): [array of 59 redacted]
trustedset: 
 added: [array of 5 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1846 ms (selfie)
 maxAssetCacheWait: 268 ms
popupPanel: 
 blocked: 6
 network: 
  google-analytics.com: 1
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
```
</details>

**Comment by krystian3w** [comment]
Backup uBo configuration and back to stock with Enabled:

> ```yml
>  removed: 
>   easyprivacy: null
>   plowe-0: null
>   urlhaus-1: null
> ```

And disabled:

> ```yml
>  added: 
>   adguard-annoyance: 68718-1713, 1d.12h.30m
>   fanboy-cookiemonster: 47146-19517, 6d.13h.1m
>   ublock-annoyances: 5070-214, 5d.4h.6m
> ```

**Comment by gorhill** [comment]
Clear the browser cache, or force a reload while bypassing the browse cache by holding the shift key. Not a uBO-related issue.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
