### ISSUE TITLE
app.kidkare.com: breakage

### ISSUE THREAD

**Issue by sproid-i** [uBlockOrigin/uAssets#18230]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.kidkare.com/`

### Category

breakage

### Description

Website breaks. I suspect is `az416426.vo.msecnd.net`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94048
 cosmetic: 38919
 scriptlet: 17529
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34069-79, 17h.12m
  ublock-badware: 7119-0, 17h.11m
  ublock-privacy: 422-0, 1d.20h.52m
  ublock-abuse: 70-70, 1d.20h.51m
  ublock-unbreak: 2032-2, 17h.13m
  ublock-quick-fixes: 329-0, 9h.10m
  easylist: 66390-668, 20h.44m
  easyprivacy: 31839-615, 3d.9h.45m
  urlhaus-1: 7012-1, 20h.43m
  plowe-0: 3737-3, 10d.21h.59m
filterset (user): [empty]
trustedset: 
 added: [array of 3 redacted]
 removed: 
  about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 178 ms (selfie)
 maxAssetCacheWait: 54 ms
popupPanel: 
 blocked: 8
 network: 
  appcues.com: 4
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  msecnd.net: 1
```
</details>

**Comment by mapx-** [comment]
add

`||fast.appcues.com^$script,3p,badfilter`

@ryanbr
