### ISSUE TITLE
Jellynote using Anti-Adblocker

### ISSUE THREAD

**Issue by sirjabberwock** [uBlockOrigin/uAssets#1823]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

1. https://www.jellynote.com/en/artist/cage-the-elephant/530516/albums
(and more general)
2. https://www.jellynote.com/

### Describe the issue

This site is successfully using anti-adblocker. I was directed to this site to report the issue.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/37855205/38004441-42f83b86-320a-11e8-8009-0315c8199154.png)

### Versions

- Browser/version: Chromium version 63.0.3239.108
- uBlock Origin version: 1.15.18

### Settings

- I have a list of 3rd party filters for disabling ads and bitcoin miners.

### Notes

I looked into AAK but found out it is discontinued and was told that issues with Anti-Adblockers should reported to uAssests.

**Comment by okiehsch** [comment]
Update your `uBO-filter` list.
