### ISSUE TITLE
samehadaku.day: ads

### ISSUE THREAD

**Issue by fikryysans** [uBlockOrigin/uAssets#18235]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://samehadaku.day/`

### Category

ads

### Description

ads with the type of sponsorship or gambling website promotion from the website provider, ads still appear even though they have used the Element Zapper Mode feature

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/134638103/e2bb9bae-28f7-4a7b-ac3b-7d90ff9f54a4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 115956
 cosmetic: 78046
 scriptlet: 31724
 html: 0
listset (total-discarded, last-updated): 
 added: 
  IDN-0: 9493-0, 6m
  adguard-generic: 71107-5248, never
 default: 
  user-filters: 3-0, never
  easylist: 66525-55, 8m
  easyprivacy: 31812-54, 8m
  plowe-0: 3735-944, 8m
  ublock-abuse: 69-0, 8m
  ublock-badware: 7151-129, 8m
  ublock-filters: 33211-124, 8m
  ublock-privacy: 380-74, 8m
  ublock-quick-fixes: 342-47, 8m
  ublock-unbreak: 2017-36, 8m
  urlhaus-1: 6912-1, 8m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1543 ms (selfie)
 maxAssetCacheWait: 432 ms
popupPanel: 
 blocked: 7
 network: 
  samehadaku.day: 4
  googletagmanager.com: 1
  histats.com: 1
  ibb.co: 1
 cosmetic: 
  ##.ads_area
  ###floatcenter
  ###floatbottom
```
</details>

**Comment by mapx-** [comment]
add

```
*.gif$domain=samehadaku.day,image
samehadaku.day##.ads
samehadaku.day###floatcenter
```

report here to have those filters added to the regkional list:
https://github.com/ABPindo/indonesianadblockrules/issues

@gmarcher
