### ISSUE TITLE
sport1.de: breakage

### ISSUE THREAD

**Issue by me1337me** [uBlockOrigin/uAssets#18236]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sport1.de/`

### Category

breakage

### Description

There was an issue with that website some years ago, but was fixed back than.
Now, I again get the note that I'm using an adblocker and can't access the site.

Firefox 113.0.2 (64-Bit)
Windows 10

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 96288
 cosmetic: 43477
 scriptlet: 17557
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 6-0, never
  ublock-filters: 34073-39, 5h.27m
  ublock-badware: 7133-1, 5h.27m
  ublock-privacy: 421-0, 5h.27m
  ublock-abuse: 70-70, 5h.27m
  ublock-unbreak: 2028-2, 5h.27m
  ublock-quick-fixes: 345-43, 5h.27m
  easylist: 66522-676, 5h.27m
  easyprivacy: 31812-621, 5h.27m
  urlhaus-1: 6874-1, 5h.27m
  plowe-0: 3735-2, 5h.27m
  DEU-0: 6863-17, 5h.27m
filterset (user): [array of 6 redacted]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 597 ms (selfie)
 maxAssetCacheWait: 145 ms
popupPanel: 
 blocked: 17
 network: 
  sport1.de: 2
  71i.de: 1
  abtasty.com: 1
  adnxs.com: 1
  asadcdn.com: 2
  aticdn.net: 2
  hotjar.com: 1
  jwpcdn.com: 1
  sensic.net: 1
  taboola.com: 5
 cosmetic: 
  ##.eqpGQM.sc-bdfBQB
  ##.s1-ad
```
</details>

**Comment by krystian3w** [comment]
I reproduced.

https://github.com/uBlockOrigin/uAssets/assets/35370833/5d2433bc-df35-4b8f-8001-3240d4052689
