### ISSUE TITLE
mc-tr.com: ads

### ISSUE THREAD

**Issue by tlostshadow01** [uBlockOrigin/uAssets#18246]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mc-tr.com/neleryeni/`

### Category

ads

### Description

Minecraft ad. Im using Kiwi Browser+ ublockorigin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230526-081400_3](https://github.com/uBlockOrigin/uAssets/assets/101035482/a0d760d1-aeb9-4c40-b4e2-da64961b4f73)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium Mobile: 112
filterset (summary): 
 network: 214843
 cosmetic: 64040
 scriptlet: 20796
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 42-0, 7d.23h.5m
  adguard-spyware-url: 1035-3, 3d.22h.47m
  block-lan: 47-0, 3d.20h.19m
  curben-phishing: 104342-2, 14h.15m
  curben-pup: 189-0, 11h.14m
  dpollock-0: 11357-65, 10d.20h.22m
  fanboy-cookiemonster: 47231-17488, 18m
 default: 
  user-filters: 6-1, never
  TUR-0: 12340-203, 3d.22h.48m
  adguard-mobile: 8779-35, 3d.22h.9m
  easylist: 65867-17118, 3d.22h.49m
  easyprivacy: 31805-152, 17h.9m
  plowe-0: 3737-1377, 6d.22h.51m
  ublock-abuse: 70-0, 6d.22h.50m
  ublock-badware: 7133-161, 4d.12h
  ublock-filters: 33350-404, 4d.12h.2m
  ublock-privacy: 392-78, 6d.22h.49m
  ublock-quick-fixes: 342-35, 17m
  ublock-unbreak: 2025-43, 4d.12h.1m
  urlhaus-1: 6912-4, 14h.14m
filterset (user): [array of 6 redacted]
trustedset: 
 added: [array of 3 redacted]
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3461 ms (selfie)
 maxAssetCacheWait: 568 ms
popupPanel: 
 blocked: 2
 network: 
  cloudflareinsights.com: 1
  googletagmanager.com: 1
 cosmetic: 
  ##.reklam-kutu
```
</details>

**Comment by tlostshadow01** [comment]
![Screenshot_20230526-081400_3](https://github.com/uBlockOrigin/uAssets/assets/101035482/a0d760d1-aeb9-4c40-b4e2-da64961b4f73)

**Comment by mapx-** [comment]
add

`mc-tr.com##[class*="reklam"]`

@Alex-302
