### ISSUE TITLE
themezon.net: nuisance

### ISSUE THREAD

**Issue by Sandor-Helper** [uBlockOrigin/uAssets#18248]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Is it possible to get off the notification about cookies agreement?

### URL(s) where the issue occurs.

`https://themezon.net/` 

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Mozilla FireFox 91.1.0esr

### Settings

No changes

**Comment by mapx-** [comment]
There are 2 notifications.
For the first one just enable `EasyList – Annoyances`

The second one you have to click ok button.

**Comment by Sandor-Helper** [comment]
> For the first one just enable `EasyList – Annoyances`

I have "uBlock filters – Annoyances" and "EasyList – Cookie Notices" and both of them are turned on.

> The second one you have to click ok button.

This is what I'm asking for, is it possible to remove it by filters so I haven't click it every time?

**Comment by mapx-** [comment]
maybe you have delete cookies on browser exit + delete history etc, otherwise it's not every time to open that page

**Comment by Sandor-Helper** [comment]
Yes, I do delete cookies frequently. But I'm asking to remove this annoying pane by filter. In my point of view it is one of its purposes in it.

**Comment by mapx-** [comment]
to have the content on page you have to click it, uBo has no auto-clicking scriptlet
