### ISSUE TITLE
google.it: ads

### ISSUE THREAD

**Issue by BrunaPitanga** [uBlockOrigin/uAssets#18242]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.google.it/search?q=asus+laptop&gbv=1`

### Category

ads

### Description

* Disable JavaScript on Google Search 
* Search for "ASUS laptop"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f3145556a76394a2e706e67](https://github.com/uBlockOrigin/uAssets/assets/115604365/0e4b701b-f80c-4a2e-904a-e4d5bbecdd5b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93983
 cosmetic: 38935
 scriptlet: 17568
 html: 933
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34105-82, 21h.12m
  ublock-badware: 7119-0, 21h.12m
  ublock-privacy: 421-0, 21h.12m
  ublock-abuse: 70-70, 21h.12m
  ublock-unbreak: 2025-2, 21h.12m
  ublock-quick-fixes: 345-0, 9h.6m
  easylist: 66500-669, 21h.12m
  easyprivacy: 31817-610, 21h.12m
  urlhaus-1: 6874-1, 21h.12m
  plowe-0: 3735-3, 21h.12m
filterset (user): [empty]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1941 ms (selfie)
 maxAssetCacheWait: 295 ms
popupPanel: 
 blocked: 0
 no-scripting: true
```
</details>

**Comment by mapx-** [comment]
use the default settings / filter lists

**Comment by BrunaPitanga** [comment]
@gorhill  These ads appear when JavaScript is turned off, but your volunteers would rather have users be exposed to all kinds of unnecessary bloated scripts instead of hiding the ads.

**Comment by MicrowaveSnacks** [comment]
some sites require javascript to function as intended

**Comment by gorhill** [comment]
Does this work?

    google.*##[href^="/settings/ads/"]:upward(div)
