### ISSUE TITLE
indeed.com: breakage

### ISSUE THREAD

**Issue by UriF** [uBlockOrigin/uAssets#18253]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

During last couple day I am not able to browse job search.  I see that something messed.  I am not able to click to link to job because something blocked.  For example (see a link below).  If I remove a your ad blocker everything works as expected

### A specific URL where the issue occurs.

`https://www.indeed.com/jobs?q=SQL+Developer&hl=en&from=ja&l=New+York%2C+NY&radius=25&alid=5c368ed02e7c8af20d203bb3&tmtk=1h1b7at76jg5u800&utm_campaign=job_alerts&utm_medium=email&utm_source=jobseeker_emails&of=1&fr=b&fromage=1&vjk=e4f2b3d5d1855c01`

### Steps to Reproduce

Browse to to link above mentioned @ Firefox.  Site is not working properly.

Turn off uBlock Origin. Everythind works

### Expected behavior

Explained above

### Actual behavior

Explained above

### uBO version

1.49.2

### Browser name and version

Firexox 113.0.2

### Operating System and version

Win 10 x64

**Comment by stephenhawk8054** [comment]
It was fixed few hours ago. Can you force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; ["Purge all caches" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 ["Update now" button](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?
