### ISSUE TITLE
devuploads.com: detection, nuisance

### ISSUE THREAD

**Issue by git-Hmmm** [uBlockOrigin/uAssets#18251]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

> Quick Note: This website uses random domains and redirect.

Clicking on generate link then proceeding, reloads the page and ad-blocker is being detected and you can't complete the download, check screenshot for details.

I would also like to request the removal of generating link wait time as I've seen this feature in some other websites, can't recall now.

### URL(s) where the issue occurs.

`https://devuploads.com/rvov7blkmvq1`

as I said it redirects to random domains:
so for me it used this one:
`https://dev.miuiflash.com/what-is-supabase-new-tech/`

edit, when I retried the same first link, this time it redirected to 
`https://thecubexguide.com/virtualization-security-management-in-cloud-computing-explained/`
and shown one banner ad also, check second screenshot.

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/102938585/316841c1-7c63-4bf1-886d-f5955a7d226d
https://github.com/uBlockOrigin/uAssets/assets/102938585/7491885f-8c9f-4e0e-9ea0-a3e4dc41ba43

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 207349
 cosmetic: 138929
 scriptlet: 22292
 html: 934
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 68826-4123, 11m
  fanboy-cookiemonster: 47180-218, 4d.20h.57m
 default: 
  user-filters: 9-0, never
  ublock-filters: 33934-59, 4d.20h.57m
  ublock-badware: 7143-0, 4d.20h.57m
  ublock-privacy: 421-0, 12m
  ublock-abuse: 70-70, 4d.20h.57m
  ublock-unbreak: 2031-2, 4d.20h.57m
  ublock-quick-fixes: 318-0, 11m
  easylist: 66036-666, 4d.20h.58m
  adguard-spyware-url: 1040-5, 11m
  easyprivacy: 31844-607, 4d.20h.57m
  urlhaus-1: 6851-1, 11m
  curben-phishing: 103971-36, 11m
  plowe-0: 3724-3, 11m
  LegitimateURLShortener: 2188-138, 11m
filterset (user): [array of 9 redacted]
trustedset: 
 added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2164 ms
 maxAssetCacheWait: 1150 ms
```
</details>

**Comment by git-Hmmm** [comment]
I've edited the first post, as it includes banner ads on some domains.

**Comment by mapx-** [comment]
add

```
@@*$script,xhr,domain=djxmaza.in|miuiflash.com
@@*$ehide,domain=djxmaza.in|miuiflash.com
*$frame,redirect-rule=noopframe,from=djxmaza.in|thecubexguide.com|miuiflash.com
```

duplicate

**Comment by AdishSagarawat** [comment]
@mapx- Tried this, still adblock getting detected and the big banner ads are there.

**Comment by mapx-** [comment]
@AdishSagarawat 
first, folow ALL these steps

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
