### ISSUE TITLE
mail.ru: ads

### ISSUE THREAD

**Issue by omonim2007** [uBlockOrigin/uAssets#18252]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mail.ru/`

### Category

ads

### Description

ADS IS SHOWING

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://github.com/uBlockOrigin/uAssets/assets/33754489/88595ef3-528f-4cc6-bcc5-41bd3884b536)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 297445
 cosmetic: 243295
 scriptlet: 41743
 html: 1117
listset (total-discarded, last-updated): 
 added: 
  https://multiup.org/list_adblock.txt: 10-0, 10m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7250-0, 10m
  https://winhelp2002.mvps.org/hosts.txt: 8729-2, 10m
  https://www.fanboy.co.nz/enhancedstats.txt: 2988-11, 10m
  adguard-generic: 71136-6378, 13m
  adguard-mobile: 8323-128, 13m
  adguard-spyware-url: 1040-5, 13m
  block-lan: 47-0, 13m
  curben-phishing: 104066-39, 12m
  curben-pup: 189-0, 11m
  adguard-annoyance: 67206-5607, 11m
  adguard-social: 20383-693, 11m
  fanboy-thirdparty_social: 69-0, 11m
  fanboy-annoyance: 90722-80534, 11m
  fanboy-cookiemonster: 47256-267, 11m
  fanboy-social: 16072-20, 11m
  ublock-annoyances: 5040-9, 11m
  dpollock-0: 11517-1661, 10m
  adguard-spyware: 41148-13825, 10m
 default: 
  user-filters: 97-18, never
  ublock-filters: 34121-105, 13m
  ublock-badware: 7158-5, 13m
  ublock-privacy: 420-0, 13m
  ublock-abuse: 69-69, 13m
  ublock-unbreak: 2028-3, 13m
  ublock-quick-fixes: 317-0, 13m
  easylist: 66571-1009, 13m
  easyprivacy: 31807-911, 13m
  urlhaus-1: 6851-1, 12m
  plowe-0: 3724-332, 10m
  RUS-0: 39563-350, 10m
filterset (user): [array of 97 redacted]
trustedset: 
 added: [array of 21 redacted]
 removed: 
  about-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 5480 ms
 maxAssetCacheWait: 3125 ms
popupPanel: 
 blocked: 65
 network: 
  mail.ru: 50
  criteo.com: 1
  dzen.ru: 1
  imgsmail.ru: 2
  tns-counter.ru: 1
  yadro.ru: 1
  yandex.ru: 9
 cosmetic: 
  ##.kgcbllo__cw9381.body_flex.body
  ##.kgcbllo__cw9381.cover
  ##.kgcbllo__cw9381.adchoise_full.adchoise_flex.adchoise
  ###asteroid-cloud
  ##.tabs-content .news-item_regular::after
  ##.tabs-content .news-item_regular > a:style(white-space: pre-line !important)
  ##.tabs-content > :first-child > a > .news-main__img:style(max-width: unset !important; min-width: unset !important; height: 5em !important; width: 6.66em !important)
  ##.tabs-content > :first-child > a > .news-main__text-wrapper:style(max-height: 5em !important; white-space: pre-line !important)
  ##.tabs-content > :first-child > a:style(max-height: 5em !important; position: static !important)
  ##.tabs-content > :first-child ~ li:style(max-width: 660px !important)
  ##.tabs-content > :first-child:style(max-width: 750px !important)
  ##[data-testid=\"grid-left-col\"] > .logo:style(margin-top: 4px !important; margin-bottom: 4px !important)
  ##body:not(.js-module) .tabs + div[class] > :first-child:style(width: 100% !important)
  ##body:not(.js-module) .tabs + div[class]:style(min-width: fit-content !important)
  ##body:not(.js-module) .tabs > .tabs__item:style(padding: 0 7px !important)
  ##div[slot=\"main-column\"] .search-container:style(margin-top: 4px !important; margin-bottom: 4px !important)
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/47acfd111610cab50b251f5677de99a3fb34af9f

**Comment by Sonic5435325** [comment]
@MasterKia Seems like a site-specific whitelist which allows random domains, maybe that should be put in the blacklisted filters in uBlock Origin.
No real reason to use that filter list instead of just reporting to filter list maintainers.
