### ISSUE TITLE
newscon.org: ads

### ISSUE THREAD

**Issue by runebalot** [uBlockOrigin/uAssets#18256]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.newscon.org/d1/`

### Category

ads

### Description

![test](https://github.com/uBlockOrigin/uAssets/assets/47264880/e9b74d1f-02b6-47c4-8436-51ca314f6a80)
ad sometimes pop up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 112
filterset (summary): 
 network: 110246
 cosmetic: 49179
 scriptlet: 17752
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34129-79, 1h.1m
  ublock-badware: 7158-0, 1h.1m
  ublock-privacy: 420-0, 1h.1m
  ublock-abuse: 69-69, 1h.1m
  ublock-unbreak: 2028-1, 1h.1m
  ublock-quick-fixes: 320-0, 1h.1m
  easylist: 66500-726, 1d.20h.55m
  easyprivacy: 31840-628, 3d.15h.20m
  urlhaus-1: 6851-1, 14h.37m
  plowe-0: 3737-4, 12d.21h.15m
  CHN-0: 26844-121, 1d.18h.53m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 346 ms (selfie)
 maxAssetCacheWait: 77 ms
popupPanel: 
 blocked: 702
 network: 
  adcanvas.com: 1
  adnxs.com: 255
  adsrvr.org: 4
  arc.io: 1
  azureedge.net: 106
  bing.com: 2
  btloader.com: 1
  criteo.com: 1
  dotomi.com: 2
  doubleclick.net: 3
  doubleverify.com: 3
  fuseplatform.net: 2
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
  googletagservices.com: 9
  js7k.com: 12
  media.net: 131
  moatads.com: 11
  qbk1.com: 1
  qsearch-a.akamaihd.net: 60
  quantcount.com: 35
  quantserve.com: 12
  rubiconproject.com: 35
  sentry-cdn.com: 1
  trustarc.com: 2
  yimg.com: 7
```
</details>

**Comment by mapx-** [comment]
test

```
newscon.org##+js(aopw, pbjs)
newscon.org##+js(ra, srcdoc, iframe)
```

**Comment by runebalot** [comment]
> 

sorry,could you please teach me how to use the code?

**Comment by mapx-** [comment]
- open uBO dashboard (click uBO icon, click the last icon at the right bottom - the gear one)
- click "my filters" tab
- add the filters above, click "apply changes"
- test the page

**Comment by runebalot** [comment]
> * open uBO dashboard (click uBO icon, click the last icon at the right bottom - the gear one)
> 
>     * click "my filters" tab
> 
>     * add the filters above, click "apply changes"
> 
>     * test the page

thank you,it works.
