### ISSUE TITLE
Smartlook.com completely blocked

### ISSUE THREAD

**Issue by amertak** [uBlockOrigin/uAssets#1825]
### URL(s) where the issue occurs

```https://www.smartlook.com```

### Describe the issue

Lately, some users have been complaining that they cant access Smartlook.com
Smartlook is being included in EasyList privacy list.

### Screenshot(s)

```https://prnt.sc/ixee2w```

### Versions

- Browser/version: Chrome 65
- uBlock Origin version: 1.15.18

### Settings

- None

### Notes

Adding ```@@||smartlook.com^$first-party``` enables the site but still blocks the recording on other sites as intended.

**Comment by mapx-** [comment]
> still blocks the recording on other pages

What do you mean ?

The filter which breaks the site is in Peter Lowe's list @pgl

**Comment by amertak** [comment]
That the filter works as intended (blocking tracking script on other domains) after adding the fix ```@@||smartlook.com^$first-party``` to uBlock filters - Unbreak rules.

Did I put it into the bad section?
Sorry If so.

**Comment by SMed79** [comment]
@pgl add `0.0.0.0 rec.smartlook.com`

**Comment by pgl** [comment]
@SMed79 `smartlook.com` is already on my list: https://pgl.yoyo.org/adservers/details.php?hostname=smartlook.com

**Comment by mapx-** [comment]
and your rule is breaking the site, see above

**Comment by mapx-** [comment]
probably smed want to say remove the current rule and add that 1 ( rec. ...)

**Comment by pgl** [comment]
@mapx- This is intentional, as noted by @amertak . `smartlook.com` is a tracker.

**Comment by mapx-** [comment]
yes, smartlook is already blocked by easyprivacy using
`||smartlook.com^$third-party`

Your rule just breaks the site itself.

**Comment by amertak** [comment]
I prefer leaving the whole domain blocking as the subdomain for the tracker might change. The solution did by @mapx- is ok.

**Comment by pgl** [comment]
@mapx- My list isn't just used by uBlock Origin. And my policy is to include the highest level domain appropriate: http://pgl.yoyo.org/adservers/policy.php.

**Comment by okiehsch** [comment]
If a `first-party` site is broken by a filter in `Peter Lowe’s List` the preferred fix for that site is
`@@||example.com^$first-party`, see `pagefair` or `qualtrics`.
If the filter leads to site breakage on a number of `third-party` sites a `badfilter` solution may be appropriate.

**Comment by gorhill** [comment]
Actually @okiehsch, I think @mapx- solution is better, because an exception filter could always cause an actual valid narrower filter for the site to be bypassed -- include th. The case of `pagefair` is because `badfilter` was not available back then (should be revisited to use `badfilter`).

Also I think it's best if the `badfilter` is always accompanied by the `third-party` version of the block filter, just to be sure in case the `third-party` filter is removed from the other list.

**Comment by okiehsch** [comment]
OK, so the solution for such issues is to add 
````
||example.com^$badfilter
||example.com^$third-party
````
to `uBO-unbreak`.

**Comment by gorhill** [comment]
I think it's best -- this way no more specialized filters which could apply would be bypassed.

**Comment by SMed79** [comment]
@mapx- 
> probably smed want to say remove the current rule and add that 1 ( rec. ...)

Yes, that what i mean.

@pgl 
> smartlook.com is already on my list

`127.0.0.1 smartlook.com` has no effect...

add
```
127.0.0.1 rec.smartlook.com
127.0.0.1 rec1.smartlook.com
127.0.0.1 rec2.smartlook.com
127.0.0.1 rec-dev.smartlook.com
127.0.0.1 rec-src.smartlook.com
127.0.0.1 rec-beta.smartlook.com
127.0.0.1 rec-server-dev.smartlook.com
```
0.0.0.0 analytics-writer.smartlook.com

**Comment by okiehsch** [comment]
I changed 
 `@@||example.com^$first-party` to
````
||example.com^$badfilter
||example.com^$third-party
````
if applicable.
