### ISSUE TITLE
povwideo.net [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1826]
URL(s) where the issue occurs

`https://povwideo.net/aspsnr2hl8mn`

Describe the issue

Pop-up

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
continue video

**Comment by lain566** [comment]
There's a miner and popup when the video player is displayed
`https://powvideo.net/p3m6jjno46xr`

**Comment by lain566** [comment]
New address `povvideo.net`
`https://povvideo.net/embed-pdgto5ikvuwv-920x360.html`


Suggested filters
```
povvideo.*##+js(abort-on-property-write.js, Fingerprint2)
povvideo.*##+js(window.open-defuser.js)
povvideo.*##.close
*$csp=worker-src 'none',domain=povvideo.net

||zontent.powvideo.net^
||povvideo.*/jquery.notify.js$script,1p
povvideo.*##+js(set-constant.js, isAdb, false)
```

**Comment by okiehsch** [comment]
Your filters break the video, specifically `povvideo.*##+js(window.open-defuser.js)`.

**Comment by okiehsch** [comment]
Well, this is a weird site.
````
https://povvideo.net/embed-pdgto5ikvuwv-920x360.html
````
Adding
````
povvideo.*##+js(abort-on-property-write.js, Fingerprint2)
povvideo.*##+js(set-constant.js, isAdb, false)
povvideo.*##+js(setInterval-defuser.js, typeof, 500)
*$csp=worker-src 'none',domain=povvideo.net
||povvideo.*/jquery.notify.js$script,1p
||zontent.powvideo.net^
povvideo.net##[src^="data:image/png;base64,"]
````
works on my end, you have to click the "player" 3 or 4 times before the video loads, that is the amount of popups the site expects.

**Comment by lain566** [comment]
@okiehsch Actually you just have to do two clicks, and wait for the video to load.
I still get popups on Firefox

`povvideo.*##+js(window.open-defuser.js)` it works fine and does not seem to break anything, there was already a filter like that for the site https://github.com/uBlockOrigin/uAssets/commit/1e48c5f3acf4e739252e5197fbb886be9af0742a

`povvideo.*##.close` hide an element that is superimposed on the video when playing, had already been added before https://github.com/uBlockOrigin/uAssets/commit/bc2f7dfcd003dd14005031c7f3a3c4bf28646ffd

**Comment by okiehsch** [comment]
`povvideo.*##+js(window.open-defuser.js)`
You are right now it works when I tested earlier adding that filter resulted in the video never loading no matter how often I clicked, I will add it.

`povvideo.*##.close` if I add that filter the full screen button will not work on my endusiing Chromium.

**Comment by okiehsch** [comment]
> I still get popups on Firefox

Do you still get them if you add `povvideo.*##+js(window.open-defuser.js)`?

**Comment by lain566** [comment]
> povvideo.*##+js(window.open-defuser.js)
> You are right now it works when I tested earlier adding that filter resulted in the video never loading no matter how often I clicked, I will add it.

You need this filter to work `povvideo.*##+js(abort-on-property-write.js, Fingerprint2)`
if you add this filter `povvideo.*#@#+js(abort-on-property-write.js, Fingerprint2)` then the video can not be played
> Do you still get them if you add povvideo.*##+js(window.open-defuser.js)?

Yes, works for me on Firefox

> povvideo.*##.close if I add that filter the full screen button will not work on my end using Chromium.

You're right, it does not work on the URL of the embedded video, but it works here for example.
`https://hdfull.me/serie/betty-en-ny/temporada-1/episodio-37`

**Comment by okiehsch** [comment]
Well, it is pretty trivial to close the "X" by clicking on it, so let's leave it at that and not break the embedded video for such a minor issue.

**Comment by lain566** [comment]
The site has changed, there's a popup when the player is loaded, and a transparent iframe appears intermittently.
`https://povvideo.net/orsaazs67z70`

Suggested filters
```
povvideo.*##+js(abort-current-inline-script.js, $, test)
povvideo.*##+js(abort-on-property-write.js, Fingerprent2)
povvideo.*##+js(nowebrtc.js)
```

**Comment by okiehsch** [comment]
Thanks.

**Comment by lain566** [comment]
New adress again `powvldeo.net`
Same rules `povvideo` to `powvldeo` works
```
powvldeo.*##+js(abort-current-inline-script.js, $, test)
powvldeo.*##+js(abort-on-property-write.js, Fingerprent2)
powvldeo.*##+js(abort-on-property-write.js, Fingerprint2)
powvldeo.*##+js(nowebrtc.js)
powvldeo.*##+js(set-constant.js, isAdb, false)
powvldeo.*##+js(window.open-defuser.js)
||powvldeo.*/jquery.notify.js$script,1p
powvldeo.*##[src^="/ben/mgnat.html?"]
```


Suggested filters, there is a miner, and an element superimposed when the video is played.
```
powvldeo.*###embed
powvldeo.*##+js(abort-on-property-write.js, CoinNebula)
```



Test link
`https://powvldeo.net/embed-2t0jnektu3tm-954x562.html`
`https://powvldeo.net/2t0jnektu3tm`

**Comment by mapx-** [comment]
thx

**Comment by yourduskquibbles** [comment]
`streamp1ay.me` has this CoinNebula shit too - want me to open a issue or fixable via this comment?

Test link `https://streamp1ay.me/lq5yh168rygy`

**Comment by mapx-** [comment]
it's already blocked by
`||streamp1ay.me^$csp=worker-src 'none';`

**Comment by KiLL4FuNK** [comment]
captcha error

`https://powvldeo.net/tpb76h8gfj6q`

**Comment by mapx-** [comment]
no issue for me

**Comment by ZaphodBeebblebrox** [comment]
I can trigger with chrome. The problem is caused by `*$csp=worker-src 'none',domain=povvideo.net|povwideo.cc|powvideo.cc|povw1deo.com|povwideo.net|powvideo.net|powvldeo.net`. ReCaptchas often require web workers in chromium based browsers for me.

**Comment by KiLL4FuNK** [comment]
Pop-up

`https://powv1deo.net/mi0p75xbtpz0`

**Comment by ghajini** [comment]
`powvldeo.co/3si4yvc6pmea`
Not able to play video

**Comment by mapx-** [comment]
FF / chrome ok, opera ko => even disabling a lot of filters (getting lots of popups), nothing to do.
Maybe opera is doing a bad job with the old flash

**Comment by ghajini** [comment]
`https://powvldeo.cc/0ou11dewavl1`
Clicking Continue to video just reloads the page and no video thus appears

**Comment by ghajini** [comment]
`powv1deo.cc/z6g90jpojw2c`
Block push notifications

`||powv1deo.cc/jquery.notify.js$script,1p`

**Comment by ghajini** [comment]
`https://powv1deo.cc/6udljzxspgc9`
3rd party requests
 
can be blocked using `*ntent.powv1deo.*^`

**Comment by KiLL4FuNK** [comment]
ADS
`https://pouvideo.cc/ufiwye92tm8i`

**Comment by ghajini** [comment]
Pls revise filters
video doesn't start over here
`https://pouvideo.cc/2odtsgx3at7w`

**Comment by mapx-** [comment]
I cannot reproduce the issue

**Comment by ghajini** [comment]
firefox a, ubo stable
`https://pouvideo.cc/2odtsgx3at7w`
infinite loading of video, video never start

with ubo disabled, video start

**Comment by mapx-** [comment]
tested in FF A too, no issue

**Comment by KiLL4FuNK** [comment]
Fake Button

`https://powvibeo.cc/kleojxjpngcb`

**Comment by KiLL4FuNK** [comment]
Fake Button

`https://powvibeo.cc/kleojxjpngcb`

**Comment by KiLL4FuNK** [comment]
Fake Button

`https://powvibeo.cc/kleojxjpngcb`

@okiehsch

**Comment by KiLL4FuNK** [comment]
Fake Button

`https://povvldeo.lol/aaa2iabwl7qd`

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
Pop-up  

start video

`https://povvldeo.lol/pq7iuzvtrne1`

**Comment by ludmila3333** [comment]
Fake Button

`https://powvdeo.lol/2hxxrnyx8616`

**Comment by huyszn** [comment]
New URL with fake button and pop-ups

`https://povvvideo.cc/lami52svcx64`

**Comment by ludmila3333** [comment]
Fake Button

`https://powlideo.cc/k04fmcgbk4re`
