### ISSUE TITLE
chineseanime.org: detection

### ISSUE THREAD

**Issue by Reny125** [uBlockOrigin/uAssets#18265]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.chineseanime.org/`

### Category

detection

### Description

it detects uBlock and wont let you accesses the site  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93848
 cosmetic: 38768
 scriptlet: 17544
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66210-49, 4d.2h.9m
  easyprivacy: 31808-51, 13h.9m
  plowe-0: 3735-944, 2d.8h.50m
  ublock-abuse: 70-0, 4d.20h.14m
  ublock-badware: 7117-129, 3d.13h.53m
  ublock-filters: 33197-102, 3d.13h.55m
  ublock-privacy: 382-75, 4d.20h.15m
  ublock-quick-fixes: 317-25, 17h.9m
  ublock-unbreak: 2021-39, 3d.13h.54m
  urlhaus-1: 6868-0, 17h.9m
filterset (user): [empty]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1176 ms (selfie)
 maxAssetCacheWait: 714 ms
popupPanel: 
 blocked: 10
 no-popups: true
 network: 
  disqus.com: 2
  googlesyndication.com: 4
  googletagmanager.com: 1
  onesignal.com: 1
  viglink.com: 2
 cosmetic: 
  ##ins.adsbygoogle
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists and test again?
