### ISSUE TITLE
sbbrisk.com: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18264]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Can't right click on video

### URL(s) where the issue occurs.

`https://sbbrisk.com/za0vd5wb4h94.html`

### uBO version

v1.49.3rc5

### Browser name and version

Firefox 113.0.2

### Settings

- Use custom filters, check "I am an advanced user"

**Comment by stephenhawk8054** [comment]
I don't think there's any way to disable anti right click on this site.
