### ISSUE TITLE
wooseotools.com: detection

### ISSUE THREAD

**Issue by danielrzad** [uBlockOrigin/uAssets#18267]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wooseotools.com/`

### Category

detection

### Description

Detecs uBlock and displays a popup shown in screenshot section. This site is a proxy for many others sites. To reproduce:
1) Click Download button at: `https://mirrorace.org/m/19s0v`
2) Download button should redirect to `https://wooseotools.com/` and popup should be displayed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![popup_example](https://github.com/uBlockOrigin/uAssets/assets/45539133/14c1ab5d-f5f1-4ba7-8641-cbb7f6800657)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95352
 cosmetic: 46528
 scriptlet: 17836
 html: 0
listset (total-discarded, last-updated): 
 added: 
  POL-0: 7943-11, 1m
  POL-2: 1275-13, 1m
 default: 
  user-filters: 0-0, never
  easylist: 66625-74, 1m
  easyprivacy: 31785-52, 1m
  plowe-0: 3724-944, 1m
  ublock-abuse: 69-0, 1m
  ublock-badware: 7167-129, 1m
  ublock-filters: 33294-141, 1m
  ublock-privacy: 380-74, 1m
  ublock-quick-fixes: 321-31, 1m
  ublock-unbreak: 2017-36, 1m
  urlhaus-1: 6776-0, 1m
filterset (user): [empty]
trustedset: 
 added: [array of 7 redacted]
switchRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 340 ms (selfie)
 maxAssetCacheWait: 118 ms
popupPanel: 
 blocked: 1
 network: 
  googletagmanager.com: 1
 cosmetic: 
  ##[id^=\"aswift_\"]
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
