### ISSUE TITLE
nivod4.tv: ads

### ISSUE THREAD

**Issue by DerrickPang96** [uBlockOrigin/uAssets#18278]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.nivod4.tv/play.html?showIdCode=fMX1j9RjDGvI1TzIt1qoVBCBFBGhX03D`

### Category

ads

### Description

Desktop page website all ads are blocked but in mobile page still force to watch 20 secs ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230529_010530](https://github.com/uBlockOrigin/uAssets/assets/134865819/1a11ca61-20fe-4a5e-b9f2-730f1c3a1c58)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 113
filterset (summary): 
 network: 283162
 cosmetic: 232119
 scriptlet: 40580
 html: 1104
listset (total-discarded, last-updated): 
 added: 
  adguard-generic: 71202-6211, 7m
  adguard-spyware-url: 1040-5, 7m
  block-lan: 47-0, 7m
  curben-phishing: 106105-37, 7m
  curben-pup: 199-0, 7m
  adguard-annoyance: 67226-5321, 7m
  adguard-social: 20387-670, 7m
  fanboy-thirdparty_social: 68-0, 7m
  fanboy-annoyance: 90757-80549, 7m
  fanboy-cookiemonster: 47264-273, 7m
  fanboy-social: 16090-17, 7m
  ublock-annoyances: 5107-6, 7m
  dpollock-0: 11517-468, 8m
  adguard-spyware: 41148-13651, 7m
 default: 
  user-filters: 0-0, never
  ublock-filters: 34443-129, 8m
  ublock-badware: 7163-1, 8m
  ublock-privacy: 420-0, 8m
  ublock-abuse: 69-69, 8m
  ublock-unbreak: 2034-3, 8m
  ublock-quick-fixes: 331-0, 8m
  adguard-mobile: 8328-128, 7m
  easylist: 66625-960, 7m
  easyprivacy: 31785-708, 7m
  urlhaus-1: 6700-0, 7m
  plowe-0: 3724-2, 7m
  CHN-0: 26869-148, 7m
filterset (user): [empty]
modifiedUserSettings: 
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2587 ms
 maxAssetCacheWait: 8 ms
popupPanel: 
 blocked: 2
 network: 
  googletagmanager.com: 1
  nivodz.com: 1
 cosmetic: 
  ##.v-ad
  ##.ad-text
  ##.share-bottom
  ##.share-btn
  ###video-container + ul[style^=\"width:\"] > li > img
  ##.install-tip-bar
```
</details>

**Comment by mapx-** [comment]
@Alex-302

**Comment by mapx-** [comment]
ok, I'll take a look, thanks

**Comment by gorhill** [comment]
I think I would prefer to add your code as a trusted scriptlet.
