### ISSUE TITLE
latex-tables.com: breakage

### ISSUE THREAD

**Issue by Gabrysse** [uBlockOrigin/uAssets#18270]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.latex-tables.com/`

### Category

breakage

### Description

There is no possibility to edit the generated table. When uBlock is deactivated everything works fine.

Steps to reproduce the issue:

1. Open latex-tables.com with uBlock Origin activated
2. On the web page loaded, there is the possibility to generate table and use it in latex. To do so, there is a pre-generated empty table in which you can write whatever you want.
3. Double-click on a cell to write something but nothing happens

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 99305
 cosmetic: 46504
 scriptlet: 17614
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34158-68, 17h.57m
  ublock-badware: 7169-0, 17h.56m
  ublock-privacy: 421-0, 2d.18h.57m
  ublock-abuse: 70-70, 2d.18h.57m
  ublock-unbreak: 2028-2, 17h.55m
  ublock-quick-fixes: 324-0, 2h.56m
  easylist: 66574-671, 1d.21h.2m
  easyprivacy: 31838-604, 5d.21h.21m
  urlhaus-1: 6902-0, 15h.53m
  plowe-0: 3724-3, 1d.21h.3m
  ITA-0: 12734-10, 15h.54m
filterset (user): [empty]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 157 ms (selfie)
 maxAssetCacheWait: 52 ms
popupPanel: 
 blocked: 25
 network: 
  latex-tables.com: 19
  doubleclick.net: 1
  ezodn.com: 4
  google-analytics.com: 1
 cosmetic: 
  ##.ezoic-ad
  ##.adtester-container
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ##[data-ez-name]
  ##span[id^=\"ezoic-pub-ad-placeholder-\"]
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
```
</details>

**Comment by mapx-** [comment]
provide all the steps, info, in ordfer to reproduce the issue

**Comment by Gabrysse** [comment]
1. Open latex-tables.com with ublock origin activated
2. On the web page loaded, there is the possibility to generate table and use it in latex. To do so, there is a pre-generated empty table in which you can write whatever you want.
3. Double-click on a cell to write something but nothing happens
