### ISSUE TITLE
bingfeng.tw: detection

### ISSUE THREAD

**Issue by weijen6** [uBlockOrigin/uAssets#18279]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bingfeng.tw/hideshowad-bb.html?p=guest&tid=1732337&fid=202&fgpid=200`

### Category

detection

### Description

ublock detection

### Screenshot(s)

https://i.imgur.com/jqtwUo8.png

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 160985
 cosmetic: 168935
 scriptlet: 38667
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67226-105, 3h.28m
  adguard-generic: 71161-487, 3h.28m
  adguard-mobile: 8328-67, 3h.28m
  adguard-social: 20387-879, 3h.28m
  ublock-annoyances: 5082-218, 3h.28m
  adguard-spyware: 41147-14558, never
 default: 
  user-filters: 3-0, never
  CHN-0: 26866-116, 3h.28m
  easylist: 66604-1005, 3h.28m
  easyprivacy: 31785-258, 3h.28m
  plowe-0: 3724-1032, 3h.28m
  ublock-abuse: 69-0, 3h.28m
  ublock-badware: 7156-360, 3h.28m
  ublock-filters: 33288-4058, 3h.28m
  ublock-privacy: 380-75, 3h.28m
  ublock-quick-fixes: 328-32, 3h.28m
  ublock-unbreak: 2017-92, 3h.28m
  urlhaus-1: 6700-0, 3h.28m
filterset (user): [array of 3 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 644 ms (selfie)
 maxAssetCacheWait: 384 ms
popupPanel: 
 blocked: 38
 network: 
  bingfeng.tw: 2
  adsinstant.com: 2
  appier.net: 4
  creativecdn.com: 4
  criteo.net: 4
  facebook.com: 1
  googletagmanager.com: 1
  hinet.net: 7
  holmesmind.com: 7
  scupio.com: 4
  sitemaji.com: 1
  yimg.com: 1
 cosmetic: 
  ###fb-root:not(body):not(html)
  ##.wp.a_f
  ##.wp.a_t
  ##.a_mu
  ##.clickforceads
```
</details>

**Comment by okiehsch** [comment]
It's fixed by 
`bingfeng.tw##+js(acs, setTimeout, COOKIE_NAME)`
in the regional chinese list on my end.
