### ISSUE TITLE
wuxia.blog: detection

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#18273]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

aa cointener

### URL(s) where the issue occurs.

`https://www.wuxia.blog/`

### uBO version

latest

### Browser name and version

ff 102.0.1

### Settings

- all english lists are on

**Comment by mapx-** [comment]
- even disabling uBO I get that warning, site issue
- add in your custom filters

`wuxia.blog##.jumbotron`
