### ISSUE TITLE
tii.la: detection

### ISSUE THREAD

**Issue by ghosttemp9** [uBlockOrigin/uAssets#18283]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tii.la/b19zZnpp2OU`

### Category

detection

### Description

help

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95645
 cosmetic: 49693
 scriptlet: 19031
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  TUR-0: 14037-11, 31m
  easylist: 66500-68, 3d.23h.37m
  easyprivacy: 31840-57, 4d.4h.7m
  plowe-0: 3724-937, 1d.5h.48m
  ublock-abuse: 69-0, 1d.10h.13m
  ublock-badware: 7117-129, 4d.4h.8m
  ublock-filters: 33187-111, 4d.4h.8m
  ublock-privacy: 380-74, 1d.10h.13m
  ublock-quick-fixes: 321-23, 11h.29m
  ublock-unbreak: 2021-39, 4d.4h.7m
  urlhaus-1: 6776-0, 9h.28m
filterset (user): [empty]
trustedset: 
 added: [array of 9 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 369 ms (selfie)
 maxAssetCacheWait: 174 ms
popupPanel: 
 blocked: 6
 network: 
  googletagmanager.com: 1
  inklinkor.com: 2
  ophoacit.com: 1
  shrinkearn.com: 1
  trustbummler.com: 1
```
</details>

**Comment by mapx-** [comment]
update all your filter lists

duplicate https://github.com/uBlockOrigin/uAssets/issues/18268
