### ISSUE TITLE
minecraftraffle.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1828]
URL(s) where the issue occurs

`minecraftraffle.com`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by Omega-6** [comment]
Should we just block the site?

**Comment by Omega-6** [comment]
we already have a filter for the site
