### ISSUE TITLE
globalwaterintel.com: ads

### ISSUE THREAD

**Issue by Overengined** [uBlockOrigin/uAssets#18281]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.globalwaterintel.com/`

### Category

ads

### Description

on the top of the main page, one ad seems to remain

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 112651
 cosmetic: 47913
 scriptlet: 17708
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34123-39, 20h.4m
  ublock-badware: 7169-0, 20h.3m
  ublock-privacy: 420-0, 1d.1h.16m
  ublock-abuse: 69-69, 1d.1h.15m
  ublock-unbreak: 2028-0, 20h.2m
  ublock-quick-fixes: 321-27, 6h.45m
  easylist: 66576-257, 1d.22h.10m
  easyprivacy: 31813-78, 1d.22h.9m
  urlhaus-1: 6902-0, 20h.1m
  plowe-0: 3735-948, 8d.1h.33m
  FRA-0: 28510-832, 11m
filterset (user): [empty]
trustedset: 
 removed: 
  about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 213 ms (selfie)
 maxAssetCacheWait: 118 ms
popupPanel: 
 blocked: 7
 network: 
  globalwaterintel.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  hs-analytics.net: 1
  hs-banner.com: 1
  licdn.com: 1
  segment.com: 1
```
</details>

**Comment by okiehsch** [comment]
`globalwaterintel.com##[href="https://www.water.toray"]`
@ryanbr
