### ISSUE TITLE
isls.zcu.cz: breakage

### ISSUE THREAD

**Issue by stanekpa** [uBlockOrigin/uAssets#18282]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://isls.zcu.cz/prihlaska-dite-do-16ti-let-cech-2020/`

### Category

breakage

### Description

Above text "Create your own user feedback survey" missing iframe that contains important content of this page - registration.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/12082500/e677415c-d1d0-45c0-8c75-0e81cb0d74bd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93921
 cosmetic: 39269
 scriptlet: 17700
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  CZE-0: 740-0, 1h.29m
  easylist: 66390-51, 4d.10m
  easyprivacy: 31840-56, 4d.9m
  plowe-0: 3737-944, 10d.1h.23m
  ublock-abuse: 70-0, 3d.26m
  ublock-badware: 7117-129, 5d.1m
  ublock-filters: 33147-104, 5d
  ublock-privacy: 381-75, 3d.25m
  ublock-quick-fixes: 321-23, 9h.31m
  ublock-unbreak: 2021-39, 4d.23h.59m
  urlhaus-1: 6700-0, 1h.30m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 393 ms (selfie)
 maxAssetCacheWait: 196 ms
popupPanel: 
 blocked: 2
 network: 
  zcu.cz: 1
  surveymonkey.com: 1
```
</details>

**Comment by mapx-** [comment]
test

`||surveymonkey.com/collect/$3p,badfilter`

@ryanbr
