### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by Trum00thay** [uBlockOrigin/uAssets#18287]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/1U46m/Dont.Starve.Together.v556225.rar`

### Category

detection

### Description

![Uploading image.png…]()

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/94278690/28473b4f-2d90-48d8-aa68-dbc6f6d25dfb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93967
 cosmetic: 39001
 scriptlet: 17551
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66609-49, 3h.13m
  easyprivacy: 31840-52, 5d.19h.29m
  plowe-0: 3737-944, 12d.20m
  ublock-abuse: 70-0, 3d.11h.15m
  ublock-badware: 7131-129, 3d.13h.27m
  ublock-filters: 33197-104, 3d.13h.26m
  ublock-privacy: 381-75, 3d.11h.14m
  ublock-quick-fixes: 331-23, 3h.12m
  ublock-unbreak: 2014-35, 3d.13h.25m
  urlhaus-1: 6776-0, 22h.43m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 506 ms (selfie)
 maxAssetCacheWait: 98 ms
popupPanel: 
 blocked: 10
 network: 
  megaup.net: 2
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 1
  dmmzkfd82wayn.cloudfront.net: 2
  googletagmanager.com: 1
  keydawnawe.com: 1
  s3.amazonaws.com: 1
```
</details>

**Comment by ghajini** [comment]
try https://github.com/uBlockOrigin/uAssets/issues/18261#issuecomment-1565403781

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/commit/843d081df7cf3f711e126b0228fb1e28977b4b81
