### ISSUE TITLE
music.youtube.com: ads

### ISSUE THREAD

**Issue by KennedyCordeiro** [uBlockOrigin/uAssets#18295]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://music.youtube.com/`

### Category

ads

### Description

Youtube Music ads 
![image](https://github.com/uBlockOrigin/uAssets/assets/44453311/f4404938-ec6d-44d8-8e04-58fa7ee8f9cd)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 95246
 cosmetic: 42414
 scriptlet: 17959
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66552-49, 3d.3h.35m
  easyprivacy: 31742-52, 3h.48m
  plowe-0: 3724-936, 3h.48m
  spa-1: 5245-68, 3h.48m
  ublock-abuse: 70-0, 6d.1h.48m
  ublock-badware: 7167-129, 3h.48m
  ublock-filters: 33314-130, 3h.48m
  ublock-privacy: 392-75, 6d.1h.47m
  ublock-quick-fixes: 321-31, 3h.48m
  ublock-unbreak: 2020-35, 3h.48m
  urlhaus-1: 6731-0, 3h.48m
filterset (user): [empty]
trustedset: 
 added: [array of 21 redacted]
switchRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 818 ms (selfie)
 maxAssetCacheWait: 499 ms
popupPanel: 
 blocked: 584
 network: 
  youtube.com: 347
  doubleclick.net: 9
  google.com: 189
  googleadservices.com: 4
  googlesyndication.com: 34
  googletagmanager.com: 1
 cosmetic: 
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
```
</details>

**Comment by Yuki2718** [comment]
Please use this existing issue https://github.com/uBlockOrigin/uAssets/issues/7636
