### ISSUE TITLE
homedepot.com: breakage

### ISSUE THREAD

**Issue by ebonweaver** [uBlockOrigin/uAssets#18296]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Multiple lists cripple the homedepot site in various ways:

EasyPrivacy - blocks the Live Chat button AND prevents checkout (causes recaptcha/ payment processing failure for some reason)
AdGuard Tracking Protection - blocks the Feedback button
Peter Lowe'd Ad and tracking server list - blocks feedback button

### URL(s) where the issue occurs.

homedepot.com

### uBO version

1.49.2

### Browser name and version

Chrome 113.0.5672.127

### Settings

none other than unchecking/checking the above to verify the issues

**Comment by mapx-** [comment]
test

```
@@||homedepot.com/$script,xhr,1p
||paypal.com/xoplatform/logger/api/logger$badfilter
@@||pixel.mathtag.com/sync/^$frame,domain=homedepot.com
@@||btttag.com/analytics.rcv$xhr,domain=homedepot.com
@@||siteintercept.qualtrics.com^$domain=homedepot.com
@@||thdstatic.com^$domain=homedepot.com
```

**Comment by ebonweaver** [comment]
I'm not sure what is expected here.
If the commits noted were supposed to fix the issue, they did not, assuming said commits were actually committed to the filters.  I purged all caches and updated filters to be sure.  No change.
I applied the items in the test post above to "my filters" and while the Feedback banner is restored, the chat button is not.
I wouldn't consider this closed as no fix has been released?

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||siteintercept.qualtrics.com^$badfilter
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > Click &#10003; `Apply changes` > Go back to the website > Press `Ctrl + Shift + R` to reload the page and test again.

**Comment by ebonweaver** [comment]
That changes nothing and seems to conflict with
@@||siteintercept.qualtrics.com^$domain=homedepot.com
Or at least I think it might, I'm not clear on the filter syntax and have been unable to find clear documentation on the subject.

**Comment by stephenhawk8054** [comment]
That filter won't conflict with `@@||siteintercept.qualtrics.com^$domain=homedepot.com`.

I added that filter and opened this link 

```
https://www.homedepot.com/p/RYOBI-ONE-18V-Lithium-Ion-4-0-Ah-Battery-2-Pack-and-Charger-Kit-PSK006/315424283
```

and the `Feedback` and `Live chat` at the border right appears normally for me. But you'll need to wait a bit for them to appear, screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/1404486a-8895-4a44-916d-051f8245f8ec
