### ISSUE TITLE
viso.ai: ads

### ISSUE THREAD

**Issue by karynaur** [uBlockOrigin/uAssets#18291]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://viso.ai/deep-learning/vision-transformer-vit/`

### Category

ads

### Description

Can still see an ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/25678782/4b7a998b-847b-42a1-b809-6cd516864fb3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93862
 cosmetic: 38938
 scriptlet: 17605
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34133-62, 2h.30m
  ublock-badware: 7153-0, 3d.11h.58m
  ublock-privacy: 421-0, 4d.12h.5m
  ublock-abuse: 70-70, 4d.14h.7m
  ublock-unbreak: 2031-2, 4d.14h.6m
  ublock-quick-fixes: 327-0, 2h.29m
  easylist: 66525-667, 3d.11h.57m
  easyprivacy: 31812-612, 2d.23h.12m
  urlhaus-1: 6700-0, 17h.53m
  plowe-0: 3737-3, 11d.15h.5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 462 ms (selfie)
 maxAssetCacheWait: 168 ms
popupPanel: 
 blocked: 4
 network: 
  googletagmanager.com: 1
  licdn.com: 1
  pagesense.io: 1
  zoho.eu: 1
```
</details>

**Comment by okiehsch** [comment]
That's self advertisement, no mainstream filter list will add a filter for it.

Adding 
`viso.ai##.dialog-lightbox-message`
to your own filter list should work.
