### ISSUE TITLE
true-gaming.net: detection

### ISSUE THREAD

**Issue by rxxs1** [uBlockOrigin/uAssets#18293]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.true-gaming.net/home/538168/metal-gear-solid-delta-snake-eater-%d8%b3%d8%aa%d9%82%d8%af%d9%91%d9%85-%d8%aa%d8%ac%d8%b1%d8%a8%d8%a9-%d8%ba%d8%a7%d9%85%d8%b1%d8%a9-%d8%aa%d8%b3%d8%aa%d9%81%d9%8a%d8%af-%d9%85%d9%86-%d9%82%d8%af/`

### Category

detection

### Description

detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 126681
 cosmetic: 197751
 scriptlet: 56535
 html: 1154
listset (total-discarded, last-updated): 
 added: 
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 67226-26838, 15h.13m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=3: 24294-55, 15h.10m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 90757-15987, 15h.13m
  adguard-generic: 71202-5844, 15h.13m
  ublock-annoyances: 5050-64, 15h.13m
  ara-0: 2382-0, 15h.13m
 default: 
  user-filters: 21552-37, never
  ublock-filters: 34188-2582, 15h.13m
  ublock-badware: 7169-1, 15h.13m
  ublock-privacy: 420-0, 15h.13m
  ublock-unbreak: 2031-2, 15h.13m
  easylist: 66625-739, 15h.13m
  easyprivacy: 31785-835, 15h.13m
  urlhaus-1: 6700-0, 15h.13m
  plowe-0: 3724-2, 15h.13m
  ublock-quick-fixes: 327-0, 14m
filterset (user): [array of 15285 redacted]
trustedset: 
 added: [array of 5 redacted]
 removed: 
  about-scheme
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1128 ms (selfie)
 maxAssetCacheWait: 295 ms
popupPanel: 
 blocked: 18
 network: 
  disqus.com: 2
  doubleclick.net: 1
  effectivemeasure.net: 1
  google.com: 1
  googletagmanager.com: 1
  instant.page: 2
  narrative.io: 1
  onesignal.com: 2
  pippio.com: 1
  rezync.com: 1
  statcounter.com: 2
  viglink.com: 3
 cosmetic: 
  ##.ads_header
  ##.ads_sidebar
  ##.ads_footer
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
  ##html:style(overflow: auto !important; padding-right: 0 !important; overscroll-behavior-y: auto !important; position: static !important;)
  ##html:style(overflow:auto!important)
  ##.comment__share
  ##.comment-share__buttons
  ##.share__button-container
  ##.share__button
  ##.icon-facebook-circle
  ##.share-icons-wrapper
  ###email-signup
  ###placement-top
```
</details>

**Comment by mapx-** [comment]
- remove first `fuckfuckadblock` list
- test again

**Comment by okiehsch** [comment]
I can reproduce with a default setup.

**Comment by rxxs1** [comment]
it's working fine now thanks
