### ISSUE TITLE
ctc.ru: detection

### ISSUE THREAD

**Issue by Hikutos** [uBlockOrigin/uAssets#18294]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ctc.ru/online/`

### Category

detection

### Description

the site detects a blocker and prohibits the use of video quality enhancement

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 110865
 cosmetic: 59809
 scriptlet: 18868
 html: 946
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34095-156, 2d.22h.55m
  ublock-badware: 7153-0, 2d.22h.54m
  ublock-privacy: 420-0, 7h.10m
  ublock-abuse: 69-69, 7h.10m
  ublock-unbreak: 2028-2, 2d.22h.53m
  ublock-quick-fixes: 327-0, 7h.10m
  easylist: 66276-558, 6d.22m
  easyprivacy: 31839-757, 6d.23m
  urlhaus-1: 6731-0, 7h.10m
  plowe-0: 3735-3, 7d.32m
  RUS-0: 39564-38, 20h.19m
filterset (user): [empty]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1691 ms (selfie)
 maxAssetCacheWait: 210 ms
popupPanel: 
 blocked: 24
 network: 
  criteo.net: 1
  d1tracker.ru: 1
  digitaltarget.ru: 1
  getshop.tv: 1
  google-analytics.com: 1
  mediahills.ru: 1
  mindbox.ru: 1
  more.tv: 2
  relap.io: 1
  tns-counter.ru: 7
  vk.com: 1
  yadro.ru: 1
  yandex.ru: 5
 cosmetic: 
  ##a[href*=\"//zen.yandex.ru/\"]
  ##.eump-com-linktxt
```
</details>

**Comment by Yuki2718** [comment]
@dimisa-RUAdList (IDK how to reproduce)

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/abffeecca297cf734d66c8f0affbdb5c108739d8
