### ISSUE TITLE
Site detects ublock and block you

### ISSUE THREAD

**Issue by er4a1** [uBlockOrigin/uAssets#183]
### URL(s) where the issue occurs
http://www.exrapidleech.info/index.php

### Steps for anyone to reproduce the issue
1. Go to http://www.exrapidleech.info/index.php
2. enter link you want to download
3. check term of service
4. click on transload file.

### Describe the issue
Download don't start but you go on a blank page 
http://www.exrapidleech.info/verify.php?2a894645d566456
where there is written:
For support us maintain the service please disable ads blocking on our site, turn on popup on our site
Contact support@exrapidleech.info if you need more help
REF: 31555a7c618ad
I've disabled my ad blocker. Let's get on with it!
Contact us with this screenshot if you had problem

### Versions
- Browser/version: Firefox 45.4.0
- uBlock Origin version: 1.9.16

### Settings
From default settings, add this lists:
Fanboy’s Enhanced Tracking List‎
Dan Pollock’s hosts file‎
hpHosts’ Ad and tracking servers‎
MVPS HOSTS

### Notes
If i disable ublock when i load the page all work, i think because popup work (but i'm not sure).

**Comment by gorhill** [comment]
> enter link you want to download

What exactly needs to be done for that step? What "link"?

**Comment by er4a1** [comment]
For example youtube video
https://www.youtube.com/watch?v=1oa6VziZH78

**Comment by er4a1** [comment]
Screenshot of what you see after the block:
![i](https://cloud.githubusercontent.com/assets/23292441/20603127/0529be34-b258-11e6-91d5-9230cdfb3a0e.png)

**Comment by er4a1** [comment]
Screenshot of the log:
![i2](https://cloud.githubusercontent.com/assets/23292441/20604462/68bfc2bc-b25e-11e6-8986-1f704b64453c.png)

**Comment by er4a1** [comment]
I found the cause of the block, at the end of the source page there is:
>
        $(document).ready(function () {
            setTimeout(function () {
                if (typeof PopAds === "undefined") {
                    document.location = 'http://www.exrapidleech.info/verify.php?8f0063d4ff0a5f03147dfa84952a79c9';
                    //console.log("TEST");
                }
                if ($('iframe[id*=bdvi]').length == 1) {
                    document.location = 'http://www.exrapidleech.info/verify.php?a84505805e47b178e9a41b4bc2dad9f1';
                }
            }, 1414);

How can i neutralize this script?

**Comment by gorhill** [comment]
Does `exrapidleech.info##script:inject(setTimeout-defuser.js, PopAds, 1414)` works?

**Comment by er4a1** [comment]
No, don't work (i have uBO 1.10.0).

**Comment by er4a1** [comment]
If can help, here is the reek anti adblock:

1) Filter:
`@@||bdfrm.bidvertiser.com/BidVertiser.dbm$subdocument,domain=exrapidleech.info`

2) Script:
```
      exrapidleech_info : {
        // by: Alexander255, Reek, Giwayume
        // patch: http://pastebin.com/Q664diQ2
        // issue: https://github.com/reek/anti-adblock-killer/issues?q=exrapidleech
        // source: http://pastebin.com/5e27syjA
        host : ['exrapidleech.info'],
        onStart : function () {

          var tomorrow = new Date();
          tomorrow.setDate(tomorrow.getDate() + 1);

          // prevent popup
          Aak.setCookie('popcashpuCap', 1);
          Aak.setCookie('popcashpu', 1);
          Aak.setCookie('nopopatall', tomorrow.getTime().toString());
          Aak.setCookie('noadvtday', 0);
          //Aak.setCookie('bv_DSKskdck_s1d', 'bvDSKskdcks1d');

          // hide notice
          Aak.addStyle('div.alert.alert-danger.lead {opacity:0;}');
          
          // prevent redirect to verify page
          Aak.setReadOnly('bdvbnr_pid', []);
          Aak.setReadOnly('PopAds', 1);

          Aak.addScript(function () {
            (function () {
              // prevent popup
              window.open = function () {};

              // prevent redirect to verify page
              var frame1 = document.createElement('iframe');
              frame1.src = 'http://bdfrm.bidvertiser.com/BidVertiser.dbm?pid=383865&bid=1737418&RD=';
              frame1.id = 'bdvi';
              frame1.style = 'display:none';
              document.documentElement.appendChild(frame1);
            })();
          });
        }
      }
```

**Comment by ghajini** [comment]
any progress on this thing @gorhill or @

**Comment by bup4gr** [comment]
In these days, exrapidleech.info change anti adblock system of the site, also reek anti adblock don't work.

Anyone can help?

**Comment by gorhill** [comment]
Also, see: https://github.com/jspenguin2017/AdBlockProtector/issues/167

**Comment by ghajini** [comment]
@gorhill ,filters for this site

`exrapidleech.info#%#if (document.location.href.indexOf('index.php') > 0) { window.eval = function() {}; }`
`exrapidleech.info#%#document.cookie = 'popcashpuCap=1';`
`exrapidleech.info#%#document.cookie = 'popcashpu=1';`
`exrapidleech.info#%#window.PopAds = "hi!";`

**Comment by lain566** [comment]
@ghajini Is there a filter to create cookies?

**Comment by ghajini** [comment]
its back..........
example link to transload=
`http://www.exrapidleech.info/index.html`

**Comment by jspenguin2017** [comment]
@ghajini Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/51577298-9e296d00-1e76-11e9-9078-41a49947ec17.png)

**Comment by ghajini** [comment]
@jspenguin2017, you have to use that link at `exrapidleech.info` to download and notice antiadblock at exrapidleech

**Comment by jspenguin2017** [comment]
Ah, I misread your post. 

The website (`exrapidleech.info`) doesn't work on a browser without extensions, so it's likely a problem on their side.

**Comment by ghajini** [comment]
`www.exrapidleech.info/index.html` is accessible

**Comment by ghajini** [comment]
Repro steps are pretty much explained in thread....
1.
after you go to site `http://www.exrapidleech.info/index.html`
,  enter this link
`https://userscloud.com/mlb2m4p68wm5`
And 
2. Click transload
3.verify captcha
4.in next page click `public rapidleech`
5.next page again enter `https://userscloud.com/mlb2m4p68wm5` link and click transload
6.next page will be of classic antiadblock
`For support us maintain the service please disable ads blocking on our site, turn on popup on our site
Contact support@exrapidleech.info if you need more help
REF: 31555a7c618ad
I've disabled my ad blocker. Let's get on with it!
Contact us with this screenshot if you had problem`

**Comment by jspenguin2017** [comment]
I get stuck on step 3 if I disable all extensions.

**Comment by jspenguin2017** [comment]
Sure, but that does not show that the site works fine with no adblocker enabled.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4703
