### ISSUE TITLE
canadapost-postescanada.ca: breakage

### ISSUE THREAD

**Issue by muchqs** [uBlockOrigin/uAssets#18304]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.canadapost-postescanada.ca/track-reperage/en`

### Category

breakage

### Description

On Canada Post tracking page, there is an option to select a "Delivery preference".
URL is `https://www.canadapost-postescanada.ca/track-reperage/en#/details/[tracking number]`
Screenshot: https://i.imgur.com/wVTCf9x.jpg

With uBo on, clicking on the button does nothing. With uBo turned off, it works correctly and loads 
`https://www.canadapost-postescanada.ca/track-reperage/en#/deliveryInstructions/[tracking number]/form`
Screenshot: https://i.imgur.com/jrOIlcg.jpg

After a bit testing I found it's blocked by EasyPrivacy. And have to allow `assets.adobedtm.com` for the button to work correctly.
Screenshot: https://i.imgur.com/gJxadoM.jpg
Screenshot: https://i.imgur.com/KHAYnkS.jpg

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 98
filterset (summary): 
 network: 116642
 cosmetic: 109255
 scriptlet: 23878
 html: 0
listset (total-discarded, last-updated): 
 added: 
  CHN-0: 26900-116, 3h.58m
  adguard-annoyance: 67288-105, 14m
  adguard-spyware-url: 1044-3, 3h.57m
  block-lan: 47-0, 5d.10h.15m
  ublock-annoyances: 5084-176, 1d.2h.50m
 default: 
  user-filters: 20-0, never
  easylist: 66536-164, 3d.22h.32m
  easyprivacy: 31805-150, 4d.2h.37m
  plowe-0: 3735-948, 8d.2h.27m
  ublock-abuse: 69-0, 1d.8h.50m
  ublock-badware: 7151-129, 4d.2h.36m
  ublock-filters: 33218-498, 4d.2h.35m
  ublock-privacy: 380-76, 1d.8h.50m
  ublock-quick-fixes: 320-9, 7h.58m
  ublock-unbreak: 2017-38, 4d.2h.34m
  urlhaus-1: 6732-0, 1h.56m
filterset (user): [array of 20 redacted]
switchRuleset: 
 added: [array of 1 redacted]
hostRuleset: 
 added: [array of 6 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 6655 ms (selfie)
 maxAssetCacheWait: 1922 ms
popupPanel: 
 blocked: 12
 network: 
  adobedtm.com: 1
  ads-twitter.com: 1
  canadapost.ca: 1
  demdex.net: 2
  facebook.net: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  licdn.com: 1
  omtrdc.net: 1
  qualtrics.com: 1
  scorecardresearch.com: 1
```
</details>

**Comment by peace2000** [comment]
Hi, does this filter help?

`||assets.adobedtm.com^$script,redirect-rule=noopjs,domain=canadapost-postescanada.ca`

**Comment by stephenhawk8054** [comment]
@ryanbr
