### ISSUE TITLE
apollo.lv: detection

### ISSUE THREAD

**Issue by mbolsteins** [uBlockOrigin/uAssets#18309]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.apollo.lv/`

### Category

detection

### Description

uBlock Origin is detected, site asks to disable it or subscribe to paid service

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/14817214/64b030e0-b843-4b50-bd19-10dd3409b3d4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93870
 cosmetic: 38969
 scriptlet: 17572
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66576-49, 2d.15h.9m
  easyprivacy: 31807-52, 2d.15h.8m
  plowe-0: 3724-936, 1d.20h.8m
  ublock-abuse: 69-0, 17h.15m
  ublock-badware: 7131-129, 4d.23h.35m
  ublock-filters: 33201-104, 4d.23h.34m
  ublock-privacy: 380-74, 17h.14m
  ublock-quick-fixes: 321-11, 6h.35m
  ublock-unbreak: 2014-35, 4d.23h.33m
  urlhaus-1: 6732-0, 5h.27m
filterset (user): [empty]
trustedset: 
 added: [array of 5 redacted]
switchRuleset: 
 added: [array of 1 redacted]
 removed: 
  no-large-media: behind-the-scene false
hostRuleset: 
 removed: 
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 305 ms (selfie)
 maxAssetCacheWait: 137 ms
popupPanel: 
 blocked: 16
 network: 
  chartbeat.com: 3
  cxense.com: 1
  doubleclick.net: 1
  gemius.pl: 1
  google-analytics.com: 1
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  npttech.com: 1
  postimees.ee: 2
  quantserve.com: 1
 cosmetic: 
  ##.dfp-ad
```
</details>

**Comment by mapx-** [comment]
Enable the regional list: `lv: Latvian List`
