### ISSUE TITLE
tr.investing.com: detection

### ISSUE THREAD

**Issue by erolborek** [uBlockOrigin/uAssets#18308]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tr.investing.com/indices/ise-100-commentary`

### Category

detection

### Description

website detects blocking

### Screenshot(s)

<details>

<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/135021975/59fc1bd6-0300-4d83-a980-82008655a862)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 95666
 cosmetic: 49745
 scriptlet: 19034
 html: 933
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34069-55, 4d.16h.2m
  ublock-badware: 7169-1, 2d.16h.10m
  ublock-privacy: 422-0, 5d.18h.42m
  ublock-abuse: 69-69, 16h.33m
  ublock-unbreak: 2028-1, 2d.16h.9m
  easylist: 66584-686, 3d.14h.41m
  easyprivacy: 31808-617, 2d.18h.12m
  plowe-0: 3737-2, 11d.19h.37m
  TUR-0: 14037-12, 3d.14h.40m
  urlhaus-1: 6732-0, 2h.2m
  ublock-quick-fixes: 323-1, 2h.1m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  edge-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 687 ms (selfie)
 maxAssetCacheWait: 201 ms
popupPanel: 
 blocked: 12
 network: 
  investing.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 2
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  hotjar.com: 1
  httpschecker.net: 1
  pbxai.com: 1
  primis.tech: 1
 cosmetic: 
  ##[class*=\"overlay_overlay\"]
  ##.midHeader
  ##div[data-test=\"ad-slot-visible\"]
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/107c57aedc537e5dbd4d8b8cd849c4d35da47077
