### ISSUE TITLE
aternos.org: detection

### ISSUE THREAD

**Issue by QuentB989** [uBlockOrigin/uAssets#18300]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aternos.org/server/`

### Category

detection

### Description

Pop a detect modal on every click to change page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 141481
 cosmetic: 223961
 scriptlet: 39845
 html: 1104
listset (total-discarded, last-updated): 
 added: 
  adguard-generic: 71155-5504, 1d.11h.16m
  adguard-spyware-url: 1040-5, 2h.46m
  block-lan: 47-0, 20d.47m
  adguard-annoyance: 67282-5174, 2h.45m
  adguard-social: 20404-672, 2h.38m
  fanboy-thirdparty_social: 68-0, 3d.2h.28m
  fanboy-annoyance: 90722-80423, 3d.2h.27m
  fanboy-cookiemonster: 47264-267, 19h.14m
  fanboy-social: 16599-17, 6d.13h.42m
  ublock-annoyances: 5050-6, 12h.25m
  FRA-0: 28538-378, 2d.20h.8m
 default: 
  user-filters: 22-8, never
  ublock-filters: 34098-151, 3d.2h.24m
  ublock-badware: 7153-1, 3d.2h.23m
  ublock-privacy: 420-0, 3d.2h.26m
  ublock-abuse: 69-69, 3d.2h.25m
  ublock-unbreak: 2028-3, 3d.2h.22m
  ublock-quick-fixes: 327-0, 10h.22m
  easylist: 66666-1055, 10h.23m
  easyprivacy: 31736-618, 12h.24m
  urlhaus-1: 6700-0, 23h.16m
  plowe-0: 3737-2, 10d.19h.52m
filterset (user): [array of 22 redacted]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4048 ms
 maxAssetCacheWait: 2258 ms
popupPanel: 
 blocked: 9
 network: 
  ad-delivery.net: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 2
  d1oykxszdrgjgl.cloudfront.net: 1
  google-analytics.com: 1
  quantcast.com: 1
  upapi.net: 1
  venatusmedia.com: 1
 cosmetic: 
  ##.ad-dfp:remove()
  ##.sidebar:style(width: 1.71px !important; padding: 0px !important;)
  ##.header-link-exaroton-link:style(max-height: 0.117px !important; padding: 0.017px !important; pointer-events: none !important;)
  #@#.header-link-exaroton:style(filter: opacity(0) !important;)
```
</details>

**Comment by JobcenterTycoon** [comment]
Known issue https://github.com/uBlockOrigin/uAssets/issues/13144 The site using a very aggressive anti adblock script.
