### ISSUE TITLE
superprof.ru: ads

### ISSUE THREAD

**Issue by nodecspro** [uBlockOrigin/uAssets#18311]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.superprof.ru/blog/kak-sozdat-sajt/`

### Category

ads

### Description

When you start the site, a large window with ads appears.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/102751009/f85d1aad-9b43-4456-b3e8-94f4263b00ba)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 102
filterset (summary): 
 network: 110885
 cosmetic: 59921
 scriptlet: 18944
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 7-1, never
  RUS-0: 39539-10, 1d.6h.32m
  easylist: 66390-71, 6d.1h.35m
  easyprivacy: 31805-158, 6d.1h.35m
  plowe-0: 3735-949, 6d.1h.34m
  ublock-abuse: 70-1, 6d.1h.34m
  ublock-badware: 7167-129, 1d.48m
  ublock-filters: 33470-135, 7h.22m
  ublock-privacy: 382-75, 6d.1h.34m
  ublock-quick-fixes: 321-162, 7h.20m
  ublock-unbreak: 2023-34, 7h.21m
  urlhaus-1: 6731-0, 1d.6h.32m
filterset (user): [array of 7 redacted]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 12069 ms (selfie)
 maxAssetCacheWait: 592 ms
popupPanel: 
 blocked: 1
 network: 
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
it seems to be self-promotion

add
`superprof.ru##.cta-online-wrapper`

@dimisa-RUAdList
