### ISSUE TITLE
androidpolice.com: ads

### ISSUE THREAD

**Issue by Snowpop** [uBlockOrigin/uAssets#18318]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.androidpolice.com/matter-smart-home-standard-explained/`

### Category

ads

### Description

Site still shows 

> video of the day Android Police
and/or
> AD and a box

multiple times

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-05-30 23 49 18](https://github.com/uBlockOrigin/uAssets/assets/88103045/4622894a-78dd-4fb1-9cb8-d30dd70ea242)
![Screenshot 2023-05-30 23 49 21](https://github.com/uBlockOrigin/uAssets/assets/88103045/e5857deb-12e5-472b-9b28-8225a41758a5)
![Screenshot 2023-05-30 23 49 27](https://github.com/uBlockOrigin/uAssets/assets/88103045/2c5b5e80-c961-42bb-a037-c9d1514e028d)
![Screenshot 2023-05-30 23 49 29](https://github.com/uBlockOrigin/uAssets/assets/88103045/adc6ccd9-899c-4f5b-abca-f87005a78255)
![Screenshot 2023-05-30 23 49 31](https://github.com/uBlockOrigin/uAssets/assets/88103045/21bb3d28-3545-43b4-be69-596c8c547894)
![Screenshot 2023-05-30 23 49 34](https://github.com/uBlockOrigin/uAssets/assets/88103045/07859793-07c2-48e6-ab85-e60aef08103e)
![Screenshot 2023-05-30 23 49 36](https://github.com/uBlockOrigin/uAssets/assets/88103045/ef40a70a-100b-49f6-bc5b-c93ad28685c5)
![Screenshot 2023-05-30 23 49 39](https://github.com/uBlockOrigin/uAssets/assets/88103045/74c7435c-e9a3-445e-ab53-a7228f449e97)
![Screenshot 2023-05-30 23 49 42](https://github.com/uBlockOrigin/uAssets/assets/88103045/8aa2e453-4909-42be-b881-04724c3a0e96)
![Screenshot 2023-05-30 23 49 49](https://github.com/uBlockOrigin/uAssets/assets/88103045/8774be43-8711-4f32-b292-7c642c5a976b)
![Screenshot 2023-05-30 23 49 49](https://github.com/uBlockOrigin/uAssets/assets/88103045/eb4b9b06-1aa6-48d1-bec3-6da9a3ad860c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 202693
 cosmetic: 136421
 scriptlet: 26426
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  easylist: null
  plowe-0: null
 added: 
  NLD-0: 2883-12, now
  adguard-annoyance: 67346-101, now
  adguard-spyware: 42183-295, now
  adguard-spyware-url: 1045-3, now
  block-lan: 47-0, now
  curben-phishing: 109787-7, now
  curben-pup: 199-0, now
  fanboy-annoyance: 90877-20885, now
  fanboy-cookiemonster: 47278-47278, now
  ublock-annoyances: 5084-241, now
 default: 
  user-filters: 3-0, never
  easyprivacy: 31617-13189, now
  ublock-abuse: 69-0, now
  ublock-badware: 7180-29, now
  ublock-filters: 33487-500, now
  ublock-privacy: 380-131, now
  ublock-quick-fixes: 322-165, now
  ublock-unbreak: 2023-73, now
  urlhaus-1: 6681-1, now
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-extension-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
 collapseBlocked: false
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 11778 ms (selfie)
 maxAssetCacheWait: 1737 ms
popupPanel: 
 blocked: 33
 network: 
  androidpolice.com: 1
  33across.com: 1
  ad.gt: 3
  adsrvr.org: 1
  casalemedia.com: 2
  crwdcntrl.net: 2
  dotomi.com: 1
  doubleclick.net: 2
  dyv1bugovvq1g.cloudfront.net: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  googletagservices.com: 1
  id5-sync.com: 2
  indexww.com: 1
  optmn.cloud: 1
  parsely.com: 1
  privacymanager.io: 2
  rubiconproject.com: 1
  scorecardresearch.com: 1
  skimresources.com: 1
  unpkg.com: 1
  youtube.com: 3
 cosmetic: 
  ##.nav-right > div.nav-elements
  ##.article-footer-newsletter
  ##.btn-flipboard
  ##.btn-mail
  ##.btn-twitter
  ##.btn-whatsapp
  ##.copy-link-button
  ##a[href^=\"https://www.facebook.com/sharer/sharer.php\"]
  ##a[href^=\"https://www.linkedin.com/shareArticle?\"]
  ##a[href^=\"https://www.reddit.com/submit?\"]
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##.ad-zone:not(:empty):not(.textads)
  ##.sharing-btn:not(.btn-comments):not(.btn-copy-url):not(.btn-mail)
  ##.sharing-option
  ##.bio-social
  ###shareBtn
  ###twitterBtn
  ###shareTxt
  ##body:style(overflow-y: auto !important;)
  ##.ytp-cards-teaser
  ##.ytp-pause-overlay
  ##.ytp-paid-content-overlay
  ##.ytp-title-channel
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
  ##body:style(overflow-y: auto !important;)
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
removed: 
  easylist: null
  plowe-0: null
```

You have removed EasyList and Peter Lowe's list. Enable these 2 and test again.
