### ISSUE TITLE
autofaucet.dutchycorp.space: breakage

### ISSUE THREAD

**Issue by WeissHell** [uBlockOrigin/uAssets#18316]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://autofaucet.dutchycorp.space/coin_roll.php`

### Category

breakage

### Description

> A extensão bloqueia o ReCaptcha e o botão ROLL

**Extension blocks ReCaptcha and ROLL button**

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 112815
 cosmetic: 76504
 scriptlet: 32168
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  user-filters: null
 added: 
  adguard-generic: 71297-454, 15m
 default: 
  easylist: 66683-874, 12m
  easyprivacy: 31617-155, 12m
  plowe-0: 3724-948, 11m
  spa-1: 5252-74, 16m
  ublock-abuse: 69-0, 3m
  ublock-badware: 7180-359, 3m
  ublock-filters: 33462-3688, 14m
  ublock-privacy: 380-74, 3m
  ublock-quick-fixes: 322-166, 3m
  ublock-unbreak: 2023-91, 3m
  urlhaus-1: 6681-0, 12m
filterset (user): [empty]
switchRuleset: 
 removed: 
  no-large-media: behind-the-scene false
hostRuleset: 
 removed: 
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
modifiedUserSettings: 
 autoUpdate: false
 prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 401 ms (selfie)
 maxAssetCacheWait: 175 ms
popupPanel: 
 blocked: 21
 network: 
  dutchycorp.space: 4
  a-ads.com: 2
  bmcdn4.com: 4
  bmfads.com: 1
  cloudflare.com: 1
  cpx-research.com: 1
  d3plnp2f9sfye5.cloudfront.net: 1
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
  pubfuture-ad.com: 1
  surfe.pro: 1
  tradingview.com: 1
  vlitag.com: 1
 cosmetic: 
  ##.hide-on-med-and-down > div[style=\"text-align:center\"] > a[onmousedown^=\"$(this).attr('href',\"]
  ##.show-on-medium
  ##[href*=\"banner\"]
  ##center > .hide-on-med-and-down
  ##.nav-ad
  ##[style*=\"width:300px;height:250px\"]
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by lyubomyrhv** [comment]
Adblocker detected!
Browser: Mozila Firefox (for Android)
113.2.0 (Build #2015952075), 88ca8c80c8+
GV: 113.0.2-20230522134052
AS: 97.4.1
