### ISSUE TITLE
so.gd

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#1831]
### URL(s) where the issue occurs

`http://so.gd/M2M0Zm`

### Describe the issue

Timer skipping..

**Comment by SMed79** [comment]
@mapx- Would you block the [thirdparty iframe](https://forums.lanik.us/viewtopic.php?f=62&t=40331) too.
- http://i.imgur.com/5f4oPfI.png
- http://i.imgur.com/x6TDv75.png
