### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by RC-Invest6040** [uBlockOrigin/uAssets#18310]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.investing.com/equities/teqnion`

### Category

detection

### Description

![QmlGocJ1VI](https://github.com/uBlockOrigin/uAssets/assets/135030014/42b193fe-8c74-49cc-b441-1767be141032)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 129920
 cosmetic: 100625
 scriptlet: 33154
 html: 946
listset (total-discarded, last-updated): 
 added: 
  adguard-generic: 71285-5405, 44m
  adguard-mobile: 8342-98, 44m
 default: 
  user-filters: 3-0, never
  ublock-filters: 34329-213, 44m
  ublock-badware: 7182-0, 44m
  ublock-privacy: 420-0, 44m
  ublock-abuse: 69-69, 44m
  ublock-unbreak: 2034-1, 44m
  easylist: 66656-691, 44m
  easyprivacy: 31617-612, 44m
  urlhaus-1: 6732-0, 44m
  plowe-0: 3724-3, 44m
  RUS-0: 39546-197, 44m
  ublock-quick-fixes: 324-0, 44m
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 17 redacted]
 removed: 
  about-scheme
  moz-extension-scheme
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 15197 ms (selfie)
 maxAssetCacheWait: 6952 ms
popupPanel: 
 blocked: 13
 network: 
  investing.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  datadoghq.eu: 1
  dggaenaawxe8z.cloudfront.net: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  hotjar.com: 1
  httpschecker.net: 1
  pbxai.com: 1
  primis.tech: 1
 cosmetic: 
  ##[class*=\"overlay_overlay\"]
  ##.midHeader
  ##div[data-test=\"ad-slot-visible\"]
  ##body:style(overflow: auto !important)
```
</details>

**Comment by peace2000** [comment]
Can't reproduce with default settings & updated lists. What custom filters do you have?

**Comment by RC-Invest6040** [comment]
> Can't find how to translate add-on to English. I took a screenshot of the filters section. thanks for quick response!

![V1M8s0WPjP](https://github.com/uBlockOrigin/uAssets/assets/135030014/6985f189-ebe5-497e-bd0b-46e341ee3576)

**Comment by RC-Invest6040** [comment]
When I tried to shut off this pop-up banner (on first screenshot) with u-block puppet tool (for handly shut off elements), after a refresh on page  I can't use graphs,Charts and other functions, all tools of investing.com becomes frozen, until I completely disable u block origin, or won't remove it from my manual filter list.

**Comment by mapx-** [comment]
Does it happen only using an account ?

**Comment by mapx-** [comment]
- tested with european, us, Azerbaijan ip => all fine on my end, no detection
- if you have other blocking extensions disable them and test again

**Comment by dportvine** [comment]
@mapx- 
https://github.com/uBlockOrigin/uAssets/commit/80cfffb53795cae90739a5b4b68cbbf9643808da#diff-03b955eebef8886aa0f1ef70b305e9b7996de9a9e0adc9fe002db5a21d301c9fR6994

**Comment by dimisa-RUAdList** [comment]
`investing.com###__next > .fixed`

**Comment by RC-Invest6040** [comment]
> `investing.com###__next > .fixed`
> Screenshot(s)

This version resolved the pop-up issue, its gone away. Now every chart is usable on site. Thank you so much guys! Appreciate your time and knowledge!!! God bless you all!
