### ISSUE TITLE
[nsfw] myhentaigallery.com: ads

### ISSUE THREAD

**Issue by Snowpop** [uBlockOrigin/uAssets#18320]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://myhentaigallery.com/`

### Category

ads

### Description

Website still shows ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[nsfw warning] https://imgur.com/a/4X87HXf

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 202693
 cosmetic: 136421
 scriptlet: 26426
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  easylist: null
  plowe-0: null
 added: 
  NLD-0: 2883-12, 42m
  adguard-annoyance: 67346-101, 42m
  adguard-spyware: 42183-295, 42m
  adguard-spyware-url: 1045-3, 42m
  block-lan: 47-0, 42m
  curben-phishing: 109787-7, 42m
  curben-pup: 199-0, 42m
  fanboy-annoyance: 90877-20885, 42m
  fanboy-cookiemonster: 47278-47278, 42m
  ublock-annoyances: 5084-241, 42m
 default: 
  user-filters: 3-0, never
  easyprivacy: 31617-13189, 42m
  ublock-abuse: 69-0, 42m
  ublock-badware: 7180-29, 42m
  ublock-filters: 33487-500, 42m
  ublock-privacy: 380-131, 42m
  ublock-quick-fixes: 322-165, 42m
  ublock-unbreak: 2023-73, 42m
  urlhaus-1: 6681-1, 42m
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-extension-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
 collapseBlocked: false
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 11778 ms (selfie)
 maxAssetCacheWait: 1737 ms
popupPanel: 
 blocked: 3
 network: 
  myhentaigallery.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Same as https://github.com/uBlockOrigin/uAssets/issues/18318#issuecomment-1569341752
