### ISSUE TITLE
mediaite.com: detection

### ISSUE THREAD

**Issue by foxger1** [uBlockOrigin/uAssets#18321]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mediaite.com/tv/foxs-kennedy-says-theres-a-special-place-in-hell-for-people-like-sunny-hostin-who-dont-support-other-women/`

### Category

detection

### Description

Video is gone when enabled. video appears when disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-05-30 212615](https://github.com/uBlockOrigin/uAssets/assets/83351609/f8106e6c-fb4a-4255-bde1-3c570d739b1e)
![Screenshot 2023-05-30 212644](https://github.com/uBlockOrigin/uAssets/assets/83351609/1816766b-0a0a-402d-ab3e-f19c5031ec19)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94498
 cosmetic: 39015
 scriptlet: 17660
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  easylist: 66610-49, 3d.8h.55m
  easyprivacy: 31742-52, 1d.10h.5m
  plowe-0: 3735-944, 10d.19h.9m
  ublock-abuse: 70-0, 6d.15h.45m
  ublock-badware: 7180-129, 7h.38m
  ublock-filters: 33462-105, 7h.37m
  ublock-privacy: 382-75, 6d.15h.44m
  ublock-quick-fixes: 322-164, 1h.35m
  ublock-unbreak: 2020-34, 1d.8h.4m
  urlhaus-1: 7354-0, 3h.36m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 19 redacted]
 removed: 
  edge-scheme
switchRuleset: 
 added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 139 ms (selfie)
 maxAssetCacheWait: 63 ms
popupPanel: 
 blocked: 27
 network: 
  mediaite.com: 1
  ads-twitter.com: 1
  adthrive.com: 1
  bounceexchange.com: 1
  facebook.net: 1
  google-analytics.com: 3
  googlesyndication.com: 8
  jwpltx.com: 1
  ntv.io: 1
  onesignal.com: 1
  powerad.ai: 1
  profusesupport.com: 1
  quantserve.com: 1
  scorecardresearch.com: 1
  simple-cdn.s3.amazonaws.com: 1
  taboola.com: 1
  trustarc.com: 1
  twitter.com: 1
 cosmetic: 
  ###taboola-below-article-thumbnails
  ##.o-promo-unit
  ##.sidebar-hook
  ##.o-jw-sub-promo
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists and test again?

**Comment by foxger1** [comment]
I am unsure how.



[image: image.png]


Best Regards,
Levi Stringfellow

Systems Electronics Technician

He / Him
(206) 759-1083 <(425)+492-4574>
***@***.***
Seattle, Washington

**Comment by stephenhawk8054** [comment]
You have ticked on the prerequisites, which describes how to do it:

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by foxger1** [comment]
It seems they are updated?


Best Regards,
Levi Stringfellow

Systems Electronics Technician

He / Him
(206) 759-1083 <(425)+492-4574>
***@***.***
Seattle, Washington

**Comment by stephenhawk8054** [comment]
Have you tested the site again after force updating?

**Comment by foxger1** [comment]
Yes, as shown in the screenshot there are not updates to force....

[image: image.png]
Best Regards,
Levi Stringfellow

Systems Electronics Technician

He / Him
(206) 759-1083 <(425)+492-4574>
***@***.***
Seattle, Washington

**Comment by foxger1** [comment]
This website is fighting adblock in my estimation... or maybe I'm crazy. It
seems like they do it every other day when you fix it.


Best Regards,
Levi Stringfellow

Systems Electronics Technician

He / Him
(206) 759-1083 <(425)+492-4574>
***@***.***
Seattle, Washington

**Comment by stephenhawk8054** [comment]
Please don't reply by email, github cannot display your images via email. Have you clicked on the "Purge all caches" first yet?

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

**Comment by foxger1** [comment]
Just ban me lol.

**Comment by foxger1** [comment]
Thank you.
