### ISSUE TITLE
g37.com.br: Shows ads or ad leftovers

### ISSUE THREAD

**Issue by blaster182** [uBlockOrigin/uAssets#18329]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://g37.com.br/politica/8-vereadores-rejeitam-denuncia-contra-prefeito-de-divinopolis-gleidson-azevedo/`

### Category

Shows ads or ad leftovers

### Description

Can't copy and paste or select text on this website. There are a lot of ads. The filters I applied detect uBlockOrigin.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-05-31 111016](https://github.com/uBlockOrigin/uAssets/assets/33488501/abe98d96-a82b-44bb-ab9a-c3d601c7e6fc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93920
 cosmetic: 39145
 scriptlet: 17628
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 138-4, never
  easylist: 66656-49, 23h.46m
  easyprivacy: 31807-53, 4d.14h.16m
  plowe-0: 3736-946, 5d.3h.34m
  ublock-abuse: 69-0, 5d.3h.36m
  ublock-badware: 7167-130, 1d.12h.49m
  ublock-filters: 33288-105, 2d.23h.24m
  ublock-privacy: 381-74, 5d.3h.35m
  ublock-quick-fixes: 322-20, 3h.26m
  ublock-unbreak: 2017-35, 2d.23h.23m
  urlhaus-1: 6681-0, 19h.44m
filterset (user): [array of 138 redacted]
trustedset: 
 added: [array of 22 redacted]
switchRuleset: 
 added: [array of 2 redacted]
urlRuleset: 
 added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 962 ms (selfie)
 maxAssetCacheWait: 102 ms
popupPanel: 
 blocked: 23
 no-scripting: true
 network: 
  g37.com.br: 11
  admasters.media: 1
  ajax.googleapis.com: 1
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 3
  mgid.com: 2
  wp.com: 2
 cosmetic: 
  ##.is-fixed-popup.tie-popup
  ##div#tie-popup-adblock.tie-popup.is-fixed-popup
  ##div#tie-popup-adblock.tie-popup.is-fixed-popup > div.tie-popup-container
  ##div#tie-popup-adblock.tie-popup.is-fixed-popup > div.tie-popup-container > div.container-wrapper
  ##div#tie-popup-adblock.tie-popup.is-fixed-popup > div.tie-popup-container > div.container-wrapper > span.tie-adblock-icon.tie-icon-ban
  ##div#tie-popup-adblock.tie-popup.is-fixed-popup > div.tie-popup-container > div.container-wrapper > h2
  ##div#tie-popup-adblock.tie-popup.is-fixed-popup > div.tie-popup-container > div.container-wrapper > div.adblock-message
  ##div#tie-wrapper > div.adsbygoogle.Ad-Container.sidebar-ad.ad-slot
  ###cookie-law-info-bar
  ##div[id*=\"ScriptRoot\"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by gorhill** [comment]
Enable _AdGuard Spanish/Portuguese_ in _Filter lists_ pane.

**Comment by mapx-** [comment]
for the top ad test

`g37.com.br##.code-block:has([href]):not(*:has([href*="g37.com.br"]))`

**Comment by mapx-** [comment]
@blaster182 update the regional list in 5- 10 min

**Comment by blaster182** [comment]
> 

Both really

**Comment by blaster182** [comment]
> for the top ad test
> 
> `g37.com.br##.code-block:has([href]):not(*:has([href*="g37.com.br"]))`

This works. Thanks. I'm blocking the ads and It's not detecting the uBlock with a blur wall.

**Comment by stephenhawk8054** [comment]
> Ads I can probably block, but can't select text. I don't know if it's uBlock related though.

You can enable `uBlock filters - Annoyances` list and test again.

**Comment by blaster182** [comment]
> > Ads I can probably block, but can't select text. I don't know if it's uBlock related though.
> 
> You can enable `uBlock filters - Annoyances` list and test again.

Solved! Thanks everyone, this website was a pain! I need to work with this website everyday. I do need to learn uBlockOrigin better, sorry for lacking the knowledge, it was simpler than I thought. We have a very good community here.
