### ISSUE TITLE
new.uwufufu.com: breakage

### ISSUE THREAD

**Issue by Anthony1Nguyen1** [uBlockOrigin/uAssets#18322]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://new.uwufufu.com/quizzes`

### Category

breakage

### Description

Website is all gray, initial load shows menu then all gray

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93652
 cosmetic: 39028
 scriptlet: 17607
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 0-0, never
 default: 
  user-filters: 2-0, never
  easylist: 66682-49, 14h.4m
  easyprivacy: 31617-52, 14h.4m
  plowe-0: 3724-937, 14h.4m
  ublock-abuse: 69-0, 14h.4m
  ublock-badware: 7180-130, 14h.4m
  ublock-filters: 33461-106, 14h.4m
  ublock-privacy: 380-74, 14h.4m
  ublock-unbreak: 2023-34, 14h.4m
  urlhaus-1: 6681-0, 14h.4m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 34 redacted]
 removed: 
  chrome-extension-scheme
  edge-scheme
switchRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 379 ms (selfie)
 maxAssetCacheWait: 145 ms
popupPanel: 
 blocked: 4
 network: 
  uwufufu.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  vntsm.com: 1
```
</details>

**Comment by mapx-** [comment]
add
`/mixpanel.$domain=~mixpanel.com,badfilter`

@ryanbr
