### ISSUE TITLE
devuploads.com : detection

### ISSUE THREAD

**Issue by AdishSagarawat** [uBlockOrigin/uAssets#18324]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

AdBlock getting detected

### URL(s) where the issue occurs.

`https://devuploads.com/7c5903ab6viu`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/69076256/e3eb9102-c38a-452d-84c8-95d646791645)

### uBO version

1.49.2

### Browser name and version

Chrome : 111.0.5563.147 (Official Build) (64-bit)

### Settings

*

**Comment by mapx-** [comment]
add the filters here:
https://github.com/uBlockOrigin/uAssets/issues/18251#issuecomment-1566039578

**Comment by AdishSagarawat** [comment]
@Potatoaim360 Tried, still ad blocker getting detected and the big banner ads are present.

**Comment by AdishSagarawat** [comment]
Still, same

**Comment by mapx-** [comment]
@AdishSagarawat reset uBO to default settings / lists, do not enable any other blocking extension
