### ISSUE TITLE
gqdm.net: ads

### ISSUE THREAD

**Issue by naynayeux123** [uBlockOrigin/uAssets#18325]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gqdm.net/`

### Category

ads

### Description

Ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 113
filterset (summary): 
 network: 112276
 cosmetic: 37884
 scriptlet: 17800
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 16-0, never
  ublock-filters: 34413-348, 3d.22h.52m
  ublock-badware: 7176-0, 1d.2h.5m
  ublock-privacy: 420-1, 3d.6h.10m
  ublock-abuse: 69-69, 3d.6h.9m
  ublock-unbreak: 2033-2, 3d.4h.15m
  ublock-quick-fixes: 323-0, 10h.13m
  adguard-mobile: 8325-120, 3d.22h.51m
  easylist: 66625-17533, 2d.3h.6m
  easyprivacy: 31813-632, 4d.1h.36m
  urlhaus-1: 7354-0, 3h.27m
  plowe-0: 3724-3, 1d.16h.31m
  CHN-0: 26851-1385, 3d.22h.50m
filterset (user): [array of 17 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 271 ms (selfie)
 maxAssetCacheWait: 138 ms
popupPanel: 
 blocked: 4
 network: 
  chushoushijian.cn: 4
```
</details>

**Comment by gorhill** [comment]
With generic cosmetic filters disabled, I can see a banner ad at the top. Need a specific filter for `##.ads_all > .ads_w`. Maybe the following in mobile list:

    *##.ads_all > .ads_w
