### ISSUE TITLE
meati.com: breakage

### ISSUE THREAD

**Issue by mikegreen** [uBlockOrigin/uAssets#18328]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://meati.com/where-is-meati/`

### Category

breakage

### Description

When ublock is enabled, map pin data is not allowed thru, thus map breaks. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

W/ ublock enabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/772413/cbe36a65-cfc2-46ff-a1f7-596a80f13eba)

Disabled ublock (working):
![image](https://github.com/uBlockOrigin/uAssets/assets/772413/71fa0582-8c93-4467-8cc8-8b1651268de1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94604
 cosmetic: 38947
 scriptlet: 17587
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34098-116, 4d.19h.3m
  ublock-badware: 7153-0, 4d.19h.5m
  ublock-privacy: 420-0, 3d.11h.11m
  ublock-abuse: 69-69, 3d.11h.10m
  ublock-unbreak: 2028-1, 4d.19h.4m
  ublock-quick-fixes: 324-0, 9h.51m
  easylist: 66536-556, 3d.11h.7m
  easyprivacy: 31805-645, 5d.22h.14m
  urlhaus-1: 7463-0, 8m
  plowe-0: 3724-4, 3d.11h.8m
filterset (user): [empty]
trustedset: 
 added: [array of 63 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 5647 ms (selfie)
 maxAssetCacheWait: 220 ms
popupPanel: 
 blocked: 15
 network: 
  bing.com: 1
  google.com: 1
  googletagmanager.com: 1
  ipdata.co: 1
  klaviyo.com: 9
  maps.googleapis.com: 2
```
</details>

**Comment by gorhill** [comment]
Broken by `||ipdata.co^$3p` in EasyPrivacy.

cc @ryanbr

**Comment by mikegreen** [comment]
tested today - works. thanks folks!
