### ISSUE TITLE
getgoods.com: breakage

### ISSUE THREAD

**Issue by Agavery** [uBlockOrigin/uAssets#18336]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.getgoods.com/at-de/`

### Category

breakage

### Description

Pictures on the front page load only in very low resolution and actions, e.g. opening the basket or loading more products, is blocked by the filter list EasyPrivacy. Ordering is not possible when the filter list EasyPrivacy is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![getgoods](https://github.com/uBlockOrigin/uAssets/assets/61167742/8a072509-3171-4027-b50f-d631cb2f602e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94216
 cosmetic: 39064
 scriptlet: 17679
 html: 0
listset (total-discarded, last-updated): 
 removed: 
  user-filters: null
 default: 
  easylist: 66797-49, 1m
  easyprivacy: 31569-55, 1m
  plowe-0: 3724-938, 1m
  ublock-abuse: 69-0, 1m
  ublock-badware: 7200-131, 1m
  ublock-filters: 33516-106, 1m
  ublock-privacy: 380-74, 1m
  ublock-quick-fixes: 184-21, 1m
  ublock-unbreak: 2024-35, 1m
  urlhaus-1: 7057-0, 1m
filterset (user): [array of 62 redacted]
trustedset: 
 added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 664 ms (selfie)
 maxAssetCacheWait: 312 ms
popupPanel: 
 blocked: 3
 network: 
  getgoods.com: 1
  googletagmanager.com: 1
  newrelic.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`/webtracking.$from=~webtracking.girard-agediss.com,badfilter`

@ryanbr
