### ISSUE TITLE
comscore.polarisio.com: breakage

### ISSUE THREAD

**Issue by erbelair** [uBlockOrigin/uAssets#18330]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://comscore.polarisio.com/`

### Category

breakage

### Description

When uBlock Origin extension is enabled, the web application hosted at `https://comscore.polarisio.com` does not load. 

From my brief research, it looks like this may be caused by this line in the EasyPrivacy filter (which is enabled by default):
> `/comscore.`

The issue does not occur on Firefox, but it is verified on Chrome. Perhaps the URL scheme (https://) is not being used in the compare on Firefox.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1677" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/13005030/6e693f7a-1cc4-47fc-88c9-2e870e0cd5ad">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94504
 cosmetic: 39060
 scriptlet: 17676
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66687-49, 48m
  easyprivacy: 31573-52, 48m
  plowe-0: 3724-937, 48m
  ublock-abuse: 69-0, 48m
  ublock-badware: 7183-130, 48m
  ublock-filters: 33508-104, 48m
  ublock-privacy: 380-74, 48m
  ublock-quick-fixes: 184-21, 48m
  ublock-unbreak: 2023-35, 48m
  urlhaus-1: 7463-0, 48m
filterset (user): [empty]
trustedset: 
 added: [array of 2 redacted]
 removed: 
  chrome-extension-scheme
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 645 ms
 maxAssetCacheWait: 8 ms
popupPanel: 
 blocked: 6
 network: 
  polarisio.com: 6
```
</details>

**Comment by gorhill** [comment]
Broken by `/comscore.` in EasyPrivacy.

cc @ryanbr
