### ISSUE TITLE
[nsfw] kbjfree.com: detection

### ISSUE THREAD

**Issue by hotgirlsftw** [uBlockOrigin/uAssets#18334]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kbjfree.com/`

### Category

detection

### Description

Get a message saying "Please disable your ad blocker to continue using our website OR consider to purchase preimum to remove ads If you already got premium account: sing in here

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 99943
 cosmetic: 98925
 scriptlet: 23652
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67287-97, 1d.23h.12m
  ublock-annoyances: 5073-175, 6d.23m
 default: 
  user-filters: 0-0, never
  easylist: 66545-104, 5d.10h.25m
  easyprivacy: 31738-132, 1d.23h.13m
  plowe-0: 3735-946, 8d.14m
  ublock-abuse: 69-0, 22h.52m
  ublock-badware: 7151-129, 4d.22h.5m
  ublock-filters: 33222-485, 4d.20h.3m
  ublock-privacy: 380-74, 22h.51m
  ublock-quick-fixes: 184-11, 6h.2m
  ublock-unbreak: 2017-36, 4d.20h.2m
  urlhaus-1: 7463-0, 5h.38m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  chrome-extension-scheme
switchRuleset: 
 added: [array of 5 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 138 ms (selfie)
 maxAssetCacheWait: 98 ms
popupPanel: 
 blocked: 22
 network: 
  kbjfree.com: 4
  chaturbate.com: 2
  cloudflareinsights.com: 1
  d2o03z2xnyxlz5.cloudfront.net: 1
  d2qnx6y010m4rt.cloudfront.net: 2
  doubleclick.net: 1
  tapioni.com: 3
  tsyndicate.com: 2
  wbilvnmool.com: 2
  wpadmngr.com: 2
  wyhifdpatl.com: 2
 cosmetic: 
  ##.w-\\[728px\\]
  ##[href^=\"https://go.xlrdr.com\"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists and test again?

**Comment by hotgirlsftw** [comment]
The issue resurfaced. I updated all filter lists just now before writing this comment.

Would someone please help assist? Thanks in advance.
