### ISSUE TITLE
metastats.net: breakage

### ISSUE THREAD

**Issue by Sedrs** [uBlockOrigin/uAssets#18345]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://metastats.net/hearthstone/deck/39589/`

### Category

breakage

### Description

when you hover bottom cards, because there is not below add loaded, then you cannot see full mouseover tooltip

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94865
 cosmetic: 39360
 scriptlet: 17806
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 6-0, never
  CZE-0: 741-0, 22h.30m
  easylist: 66604-51, 3d.18h.33m
  easyprivacy: 31785-57, 3d.18h.33m
  plowe-0: 3735-944, 11d.16h.6m
  ublock-abuse: 69-0, 3d.18h.33m
  ublock-badware: 7167-129, 3d.18h.33m
  ublock-filters: 33311-105, 3d.18h.33m
  ublock-privacy: 380-74, 3d.18h.33m
  ublock-quick-fixes: 322-20, 4h.35m
  ublock-unbreak: 2017-35, 3d.18h.33m
  urlhaus-1: 7463-0, 22h.31m
filterset (user): [array of 6 redacted]
trustedset: 
 added: [array of 8 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1235 ms (selfie)
 maxAssetCacheWait: 518 ms
popupPanel: 
 blocked: 7
 network: 
  google-analytics.com: 2
  googlesyndication.com: 5
 cosmetic: 
  ##ins.adsbygoogle
  ##[id^=\"aswift\"]
```
</details>

**Comment by okiehsch** [comment]
Can you test
````
metastats.net##.col-md-6:style(height: 150px !important;)
metastats.net###page-wrapper > div.row:nth-of-type(1)
````
It could lead to large white spaces on other parts of the website.

**Comment by okiehsch** [comment]
By the way 
`http://metastats.net/hearthstone/class/decks/Hunter/`
has the same issue on my end, i.e. hovering over the cards at the bottom of the page won't show the tootips because of spacing issues.
That specific case is not caused by uBO, it's caused by a bad site layout.

**Comment by Sedrs** [comment]
@okiehsch 
Ah yeah, I have tested your custom white spice fix and it works, thanks a lot.
