### ISSUE TITLE
spanishdict.com: nuisance

### ISSUE THREAD

**Issue by brynnb** [uBlockOrigin/uAssets#18342]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.spanishdict.com/conjugate/ser`

### Category

nuisance

### Description

Shows modal popup/ad for free trial. May need to be logged in to replica. I will provide login details on this ticket for testing. Also including screenshot of DOM if that helps. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1974" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/1271817/8b942bd8-f284-4c04-9340-753db0404c45">

<img width="1974" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/1271817/d4eae51b-8ec4-48b8-9b22-6f56125ebd12">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 104786
 cosmetic: 181302
 scriptlet: 25703
 html: 1104
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67441-6905, 13m
  adguard-social: 20423-671, 13m
  fanboy-thirdparty_social: 68-0, 13m
  fanboy-annoyance: 90929-78917, 13m
  fanboy-cookiemonster: 47301-266, 13m
  fanboy-social: 16157-17, 13m
  ublock-annoyances: 5052-6, 13m
 default: 
  user-filters: 66-3, never
  ublock-filters: 34400-65, 14m
  ublock-badware: 7202-0, 14m
  ublock-privacy: 420-0, 14m
  ublock-abuse: 69-69, 14m
  ublock-unbreak: 2037-4, 14m
  easylist: 66797-686, 14m
  easyprivacy: 31573-613, 13m
  urlhaus-1: 7428-0, 13m
  plowe-0: 3724-3, 13m
  ublock-quick-fixes: 189-0, 13m
filterset (user): [array of 67 redacted]
trustedset: 
 added: [array of 72 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3292 ms (selfie)
 maxAssetCacheWait: 71 ms
popupPanel: 
 blocked: 13
 network: 
  spanishdict.com: 1
  amazon-adsystem.com: 1
  d1q4kshf6f0axi.cloudfront.net: 2
  d325guje460pxh.cloudfront.net: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  loggly.com: 1
  mxpnl.com: 1
  quantserve.com: 1
 cosmetic: 
  ###removeAdsSidebar
  ##.ad-wrapper,#adTopLarge,[id^=\"adSide\"],[id^=\"adMiddle\"]
```
</details>

**Comment by brynnb** [comment]
Should be resolved with `spanishdict.com##.ReactModal__Overlay--after-open:has-text(Try 7 days)`

**Comment by techmetx11** [comment]
Reproduced aswell, apparently it's associated with a localStorage variable it checks (`pageviews_since_vocab_modal_launch_desktop_v3`)
If it's set to 10, the modal appears

**Comment by mapx-** [comment]
I got another one (Let's do it .. Premium etc)

`spanishdict.com##.ReactModal__Overlay--after-open:has-text(Premium)`
