### ISSUE TITLE
spanishdict.com: nuisance

### ISSUE THREAD

**Issue by brynnb** [uBlockOrigin/uAssets#18341]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.spanishdict.com/`

### Category

nuisance

### Description

Shows nag to log in/make account on home page and also word-specific pages. Doesn't always happen a second time on a refresh. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1390" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/1271817/bf5023de-21ce-4386-96c0-43c11397cac6">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 104786
 cosmetic: 181302
 scriptlet: 25703
 html: 1104
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67441-6905, now
  adguard-social: 20423-671, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-annoyance: 90929-78917, now
  fanboy-cookiemonster: 47301-266, now
  fanboy-social: 16157-17, now
  ublock-annoyances: 5052-6, now
 default: 
  user-filters: 66-3, never
  ublock-filters: 34400-65, now
  ublock-badware: 7202-0, now
  ublock-privacy: 420-0, now
  ublock-abuse: 69-69, now
  ublock-unbreak: 2037-4, now
  easylist: 66797-686, now
  easyprivacy: 31573-613, now
  urlhaus-1: 7428-0, now
  plowe-0: 3724-3, now
  ublock-quick-fixes: 189-0, now
filterset (user): [array of 67 redacted]
trustedset: 
 added: [array of 72 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3292 ms (selfie)
 maxAssetCacheWait: 71 ms
popupPanel: 
 blocked: 9
 network: 
  spanishdict.com: 1
  facebook.net: 1
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 1
  loggly.com: 1
  mxpnl.com: 1
  pub.network: 1
  quantserve.com: 1
 cosmetic: 
  ##.ad-wrapper,#adTopLarge,[id^=\"adSide\"],[id^=\"adMiddle\"]
```
</details>

**Comment by mapx-** [comment]
breaking sign in

**Comment by brynnb** [comment]
@MasterKia that works for the original modal, but not for the second one with the person in a yoga position.

**Comment by brynnb** [comment]
@MasterKia Doesn't work for yoga one since it doesn't appear to have iframe. Works for cat keyboard one. 

<img width="1974" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/1271817/888f8d36-cdd0-4bc2-9658-e6ad3a361ba0">

Took me a minute of clicking around to make the yoga one appear again, I got it on `https://www.spanishdict.com/wordoftheday` and using private window of course.

**Comment by brynnb** [comment]
Yet another one. This site really hates blockers. 

<img width="1974" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/1271817/a6c093d9-d96d-4b5f-b54b-9e5a2e2f557a">

`##.ReactModal__Overlay--after-open:has(iframe[srcdoc*="catTyping.mp4"], iframe[srcdoc*="conversation.mp4"], img[src*="juggling"]):has-text(signing up)`

seems to capture this third one too. I can't make the yoga one appear now, maybe they just now changed it? Maybe it's based on time of day? Who knows. 

It does seem like it'd be more robust to block any with an image or iframe, since they seem to change these often, and the actual sign-in modal doesn't include either.
