### ISSUE TITLE
innovamax.life: privacy

### ISSUE THREAD

**Issue by Saturnix** [uBlockOrigin/uAssets#18340]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This fingerprinting library does not get blocked. It is sometimes loaded from the URL provided below, and sometimes loaded from the URL being visited.

The library is loosely based on `https://www.npmjs.com/package/fingerprintjs2` which is already blocked.

```
Static filter /fingerprint2.js found in:
EasyPrivacy
```

This one should be blocked as well.

### URL(s) where the issue occurs.

`https://innovamax.life/fingerprintai20.js`

### Configuration

uBlock Origin latest version

**Comment by stephenhawk8054** [comment]
Any sample links using that script? I opened `https://innovamax.life/` but can't see that script.
