### ISSUE TITLE
levels.fyi: ads

### ISSUE THREAD

**Issue by N0B0dy99** [uBlockOrigin/uAssets#18359]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.levels.fyi/t/software-engineer/locations/united-states?yoeChoice=custom&minYoe=0&maxYoe=1&yacChoice=custom&gender=male&sortBy=total_compensation&sortOrder=ASC`

### Category

ads

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/120306516/cc4b3e75-4a94-45a1-b113-4a3e85ddcad5)

Check the image showing 
![image](https://github.com/uBlockOrigin/uAssets/assets/120306516/a066f179-2a5d-4e70-ac0c-bcfe9c67152a)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/120306516/ef0f055f-df9e-490e-af25-3ec093b2a344)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94269
 cosmetic: 39042
 scriptlet: 17685
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 40-2, never
  ublock-filters: 34405-58, 55m
  ublock-badware: 7210-0, 57m
  ublock-privacy: 420-0, 6d.23h.12m
  ublock-abuse: 70-69, 6d.23h.13m
  ublock-unbreak: 2035-1, 56m
  ublock-quick-fixes: 186-0, 12h.35m
  easylist: 66536-663, 5d.1h.10m
  easyprivacy: 31807-606, 5d.1h.9m
  urlhaus-1: 7057-0, 16h.11m
  plowe-0: 3724-3, 22h.52m
filterset (user): [array of 43 redacted]
trustedset: 
 added: [array of 84 redacted]
switchRuleset: 
 added: [array of 1 redacted]
hostRuleset: 
 added: [array of 22 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1130 ms (selfie)
 maxAssetCacheWait: 427 ms
popupPanel: 
 blocked: 14
 network: 
  fpnpmcdn.net: 12
  googletagmanager.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
levels.fyi##[class*="submissions-table-promo_promoContainer"]
```

@ryanbr

**Comment by mapx-** [comment]
@N0B0dy99 
report directly at [easylist repository](https://github.com/easylist/easylist/issues)
