### ISSUE TITLE
marktplaats.nl: breakage

### ISSUE THREAD

**Issue by TimHeiszwolf** [uBlockOrigin/uAssets#18354]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.marktplaats.nl/messages/33wf:4hn9v2m:2k28wc3qj/action/send-payment-proposal`

### Category

breakage

### Description

When trying to send a payment request via Marktplaats messages the pop-up for it is blocked (see screenshots).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

How it looks with uBlock on:
<img width="1920" alt="2023-06-02_02 14 06_firefox" src="https://github.com/uBlockOrigin/uAssets/assets/32781879/67720d05-da9c-47ef-bb7c-310f7629374d">

How it looks with uBlock off:
<img width="1920" alt="2023-06-02_02 14 21_firefox" src="https://github.com/uBlockOrigin/uAssets/assets/32781879/35dd66fe-35d8-450a-8006-d18dce33e735">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 95272
 cosmetic: 41097
 scriptlet: 17684
 html: 933
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34324-79, 3d.36m
  ublock-badware: 7169-0, 3d.39m
  ublock-privacy: 421-0, 6d.21h.39m
  ublock-abuse: 69-69, 6d.21h.40m
  ublock-unbreak: 2031-0, 3d.38m
  easylist: 66604-670, 4d.7h.2m
  easyprivacy: 31742-613, 3d.2h.40m
  urlhaus-1: 7428-0, 5h.15m
  plowe-0: 3735-3, 11d.20h.30m
  NLD-0: 2887-18, 1d.5h.20m
  ublock-quick-fixes: 186-1, 7h.17m
filterset (user): [empty]
trustedset: 
 added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 479 ms (selfie)
 maxAssetCacheWait: 51 ms
popupPanel: 
 blocked: 7
 network: 
  datadoghq-browser-agent.com: 1
  ebayclassifieds.net: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  maps.googleapis.com: 1
  marktplaats.net: 1
```
</details>

**Comment by gorhill** [comment]
If you add the following filter in your _My filters_ pane, does this fix the issue?

    @@||marktplaats.net/identity/mid.js$script,domain=marktplaats.nl

**Comment by TimHeiszwolf** [comment]
I just tried that but sadly the issue still is there. I have also tried it as "@@||marktplaats.nl/identity/mid.js$script,domain=marktplaats.nl".

**Comment by stephenhawk8054** [comment]
Can you do these steps (follow strictly the step order, don't mix the steps orders or skip any steps):

1. Click on uBO icon > &#9636; ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Reload the page and repeat the steps until issue happens
3. Switch to the logger window that was opened in step 1
4. Copy the logger via &#128203; [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here

**Comment by mapx-** [comment]
@TimHeiszwolf closing for now, just comment here if you follow the indications above
