### ISSUE TITLE
[nsfw] boards.4channel.org: breakage

### ISSUE THREAD

**Issue by nose-gnome** [uBlockOrigin/uAssets#18357]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://boards.4channel.org/`

### Category

breakage

### Description

On both Firefox desktop and Firefox Android with uBlock Origin, when trying to expand images on 4chan/4channel by clicking on it, a message appears saying "404 file no longer exists" unless I disable uBlock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93998
 cosmetic: 39074
 scriptlet: 17685
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 4-0, never
  ublock-filters: 34405-58, 4m
  ublock-badware: 7210-1, 4m
  ublock-privacy: 420-0, 4m
  ublock-abuse: 69-69, 4m
  ublock-unbreak: 2040-4, 4m
  ublock-quick-fixes: 189-0, 4m
  easylist: 66811-658, 4m
  easyprivacy: 31575-601, 4m
  urlhaus-1: 7152-0, 4m
  plowe-0: 3359-2, 4m
filterset (user): [array of 4 redacted]
trustedset: 
 added: [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4463 ms (selfie)
 maxAssetCacheWait: 839 ms
popupPanel: 
 blocked: 5
 network: 
  danbo.org: 2
  google-analytics.com: 1
  pubfuture-ad.com: 2
 cosmetic: 
  ##.adl
  ##.danbo-slot
```
</details>

**Comment by stephenhawk8054** [comment]
I use an example link `https://boards.4channel.org/v/thread/639170810` and clicking on the image works normally for me, video recording: https://github.com/uBlockOrigin/uAssets/assets/66517106/02ecfe7c-c967-40a5-8ec6-85f949ba0dcd

**Comment by nose-gnome** [comment]
> I use an example link `https://boards.4channel.org/v/thread/639170810` and clicking on the image works normally for me, video recording: https://github.com/uBlockOrigin/uAssets/assets/66517106/02ecfe7c-c967-40a5-8ec6-85f949ba0dcd


It seems to only happen on the advice board, Here's an example link: https://boards.4channel.org/adv/thread/29054834

**Comment by mapx-** [comment]
@ryanbr
