### ISSUE TITLE
play.max.com: ads

### ISSUE THREAD

**Issue by amyyhh** [uBlockOrigin/uAssets#18352]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hbo Max, well now known as MAX, has ads.... the Ad blocker isnt blocking the ads

### URL(s) where the issue occurs.

`www.max.com`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/135279595/1d63e0b4-7014-4306-890c-ed699b6aea36

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94609
 cosmetic: 39064
 scriptlet: 17677
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  easylist: 66811-49, 32m
  easyprivacy: 31575-55, 32m
  plowe-0: 3724-938, 32m
  ublock-abuse: 69-0, 32m
  ublock-badware: 7208-131, 32m
  ublock-filters: 33509-106, 32m
  ublock-privacy: 380-74, 32m
  ublock-quick-fixes: 184-21, 32m
  ublock-unbreak: 2023-35, 32m
  urlhaus-1: 7428-0, 32m
filterset (user): [array of 1 redacted]
hostRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4424 ms
 maxAssetCacheWait: 37 ms
```
</details>

**Comment by gorhill** [comment]
You should use the _chat_ icon in the popup panel to report issue, this will give us more insight of what uBO on the site. Currently missing information under _Configuration_.

**Comment by stephenhawk8054** [comment]
Can you install [uBO's dev version](https://chrome.google.com/webstore/detail/ublock-origin-dev-build/cgbcahbpdhpcegmbfconppldiemgcoii), force update all your filter lists and test again?

(Don't use both normal and dev version at the same time)

**Comment by gorhill** [comment]
@stephenhawk8054 Given the screenshot and that it's a Chromium-based browser, couldn't this just be a case of uBO not being ready at launch?

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 Given the screenshot and that it's a Chromium-based browser, couldn't this just be a case of uBO not being ready at launch?

I don't think so, since [current fix for this site is set to dev build](https://github.com/uBlockOrigin/uAssets/blob/7c49bd7d8d50b6ffa4e539b02ec22748b2ec0153/filters/filters-2022.txt#L4743-L4746) thanks to the latest updates of `xml-prune`
