### ISSUE TITLE
pinterest.com: ads

### ISSUE THREAD

**Issue by yellowhoneybees** [uBlockOrigin/uAssets#18369]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.com/search/pins/`

### Category

ads

### Description

I just noticed today, but I'm still being shown ads within the Pinterest search page. An image is attached. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/108999221/2cca114b-2a1b-441b-b95f-178d4e231056)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94083
 cosmetic: 39041
 scriptlet: 17649
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 9-0, never
  ublock-filters: 34329-58, 3d.10h.8m
  ublock-badware: 7185-0, 2d.5h.33m
  ublock-privacy: 420-0, 23h.25m
  ublock-abuse: 69-69, 22h.59m
  ublock-unbreak: 2034-0, 3d.10h.8m
  ublock-quick-fixes: 186-1, 9h.56m
  easylist: 66625-667, 5d.6h.4m
  easyprivacy: 31738-26, 3d.10h.8m
  urlhaus-1: 6942-0, 5h.17m
  plowe-0: 3735-589, 8d.13m
filterset (user): [array of 9 redacted]
switchRuleset: 
 added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 279461 ms (selfie)
 maxAssetCacheWait: 2607 ms
popupPanel: 
 blocked: 5
 no-large-media: true
 network: 
  pinterest.com: 2
  flashtalking.com: 1
  googletagmanager.com: 1
  tvpixel.com: 1
 cosmetic: 
  ##a[href^=\"https://ad.doubleclick.net/\"]
```
</details>

**Comment by stephenhawk8054** [comment]
This will hide the ads but cannot fill the blank spaces since their positions are hard-coded to the HTML

```adb
pinterest.com##[role="listitem"] [data-test-id="otpp"]:upward([role="listitem"])
```
