### ISSUE TITLE
3dmodelshare.org: detection

### ISSUE THREAD

**Issue by Niverion** [uBlockOrigin/uAssets#18365]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://3dmodelshare.org/`

### Category

detection

### Description

adblock detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/116345345/07c86416-aa61-4d2e-b675-5f51a0d52d84)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93710
 cosmetic: 39084
 scriptlet: 17703
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34429-58, 8m
  ublock-badware: 7215-0, 8m
  ublock-privacy: 420-0, 8m
  ublock-abuse: 69-69, 8m
  ublock-unbreak: 2041-4, 8m
  ublock-quick-fixes: 195-0, 8m
  easylist: 66820-658, 8m
  easyprivacy: 31483-605, 8m
  urlhaus-1: 6942-0, 8m
  plowe-0: 3368-3, 8m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2827 ms
 maxAssetCacheWait: 6 ms
popupPanel: 
 blocked: 8
 network: 
  facebook.com: 4
  googlesyndication.com: 2
  googletagmanager.com: 1
  onesignal.com: 1
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by huyszn** [comment]
The site displays an "Adblock Enabled" overlay (https://github.com/uBlockOrigin/uAssets/assets/46979193/c02b6667-2f42-421f-964e-f23f0efdb2f2).

The filter `3dmodelshare.org##+js(rmnt, script, mdp)` seems to remove this overlay.
