### ISSUE TITLE
play.max.com: ads

### ISSUE THREAD

**Issue by NickyTheCat** [uBlockOrigin/uAssets#18368]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.max.com/video/watch/efbdc72a-7541-4eaf-83aa-f11727881bdc/5e350f0e-9060-4491-aeb6-7cceffde961a`

### Category

ads

### Description

ads appear on hbo max/max

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 93972
 cosmetic: 39058
 scriptlet: 17664
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 12-2, never
  easylist: 66654-49, 2d.20h.27m
  easyprivacy: 31617-52, 2d.20h.28m
  plowe-0: 3724-937, 5d.1h.18m
  ublock-abuse: 69-0, 22h.8m
  ublock-badware: 7180-130, 2d.4h.5m
  ublock-filters: 33459-106, 2d.4h.4m
  ublock-privacy: 380-74, 22h.7m
  ublock-quick-fixes: 193-21, 2h.56m
  ublock-unbreak: 2023-35, 2d.4h.3m
  urlhaus-1: 6942-0, 2h.56m
filterset (user): [array of 12 redacted]
trustedset: 
 added: [array of 2 redacted]
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 404 ms (selfie)
 maxAssetCacheWait: 117 ms
popupPanel: 
 blocked: 31
 network: 
  max.com: 18
  app.link: 3
  brightline.tv: 2
  demdex.net: 1
  discomax.com: 1
  googletagmanager.com: 1
  litix.io: 5
 cosmetic: 
  ##.jlanAo.hnfmgp.AdLabelText-Beam-Web-Ent__sc-syhkxt-2.badge-Beam-Web-Ent__sc-fxwqre-18
```
</details>

**Comment by mapx-** [comment]
duplicate

follow the instructions here:
https://github.com/uBlockOrigin/uAssets/issues/18352#issuecomment-1572914699
