### ISSUE TITLE
usps.com: breakage

### ISSUE THREAD

**Issue by vernistage** [uBlockOrigin/uAssets#18362]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I went to update my contact information using the form on the USPS website. My request did not go through. I got stuck on the submission and just saw the "loading" page until I gave up. I then disabled this extension, hard-refreshed the form, and it immediately saved  and submitted my input information.

### URL(s) where the issue occurs.

`https://reg.usps.com/entreg/secure/EditProfilePersonalAction_input`

### Notes

I do have other extensions and use Mozilla Firefox basic protections, but because the only thing I disabled to get this to work was this extension, I have to think it was this extension that prevented the request.

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 94446
 cosmetic: 38943
 scriptlet: 17569
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34184-58, 4d.15h.5m
  ublock-badware: 7169-0, 4d.15h.3m
  ublock-privacy: 420-0, 3d.17h.34m
  ublock-abuse: 69-69, 3d.17h.35m
  ublock-unbreak: 2031-2, 4d.15h.4m
  ublock-quick-fixes: 186-0, 21h.5m
  easylist: 66609-665, 3d.17h.33m
  easyprivacy: 31629-606, 1d.15h.24m
  urlhaus-1: 7428-0, 14h.14m
  plowe-0: 3724-3, 5d.14h.36m
filterset (user): [empty]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1808 ms (selfie)
 maxAssetCacheWait: 147 ms
```
</details>

**Comment by mapx-** [comment]
@vernistage just comment here if you tested the filter above
