### ISSUE TITLE
pinterest.com: [unknown]

### ISSUE THREAD

**Issue by revinblackwell** [uBlockOrigin/uAssets#18378]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.com/`

### Category

[unknown]

### Description

The promoted ads are still a problem on pinterest.com (at least on mobile) I've run though all the other solutions provided and nothing has worked.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<!
![Screenshot_20230603_125749_Firefox](https://github.com/uBlockOrigin/uAssets/assets/135456604/28467206-7c2f-4a04-82ab-c09fa94a065d)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 113
filterset (summary): 
 network: 95211
 cosmetic: 28990
 scriptlet: 17730
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34663-309, 1d.15h.56m
  ublock-badware: 7196-1, 1d.15h.55m
  ublock-privacy: 420-1, 4d.6h.12m
  ublock-abuse: 69-69, 4d.6h.11m
  ublock-unbreak: 2045-5, 1d.15h.57m
  ublock-quick-fixes: 195-0, now
  adguard-mobile: 8353-120, 3d.22h.26m
  easylist: 66687-17447, 2d.13h.20m
  easyprivacy: 31293-615, now
  urlhaus-1: 6942-0, 21h
  plowe-0: 3724-2, 6d.9h.9m
filterset (user): [empty]
modifiedUserSettings: 
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4285 ms (selfie)
 maxAssetCacheWait: 2266 ms
popupPanel: 
 blocked: 25
 network: 
  pinterest.com: 21
  facebook.net: 1
  flashtalking.com: 1
  googletagmanager.com: 1
  tvpixel.com: 1
```
</details>

**Comment by mapx-** [comment]
update all your filter lists

**Comment by revinblackwell** [comment]
I did

**Comment by mapx-** [comment]
Be sure the cosmetic filters are enabled
