### ISSUE TITLE
[nsfw] poki.se: detection

### ISSUE THREAD

**Issue by Nerdfox** [uBlockOrigin/uAssets#18376]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://poki.se/spela/roper.html`

### Category

detection

### Description

edwdc

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93700
 cosmetic: 39052
 scriptlet: 17665
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  easylist: 66654-49, 3d.19h.24m
  easyprivacy: 31617-52, 2d.2h.3m
  plowe-0: 3359-915, 1d.14h.25m
  ublock-abuse: 69-0, 2h.55m
  ublock-badware: 7180-130, 3d.19h.21m
  ublock-filters: 33470-106, 3d.19h.23m
  ublock-privacy: 380-74, 2h.55m
  ublock-quick-fixes: 193-21, 2h.55m
  ublock-unbreak: 2023-35, 3d.19h.22m
  urlhaus-1: 7002-0, 2h.55m
filterset (user): [array of 1 redacted]
trustedset: 
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 5931 ms (selfie)
 maxAssetCacheWait: 798 ms
popupPanel: 
 blocked: 60
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network: 
  poki.com: 60
```
</details>

**Comment by mapx-** [comment]
```
no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
```

reset uBO, update all filter lists, do not use any other blocking extensions, do not touch any parameters in uBO
