### ISSUE TITLE
coursedrive.org: ad placeholder

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18379]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There's a small ad placeholder gap in between some of the articles. I fixed it with this:
`coursedrive.org##[class*="is-gap-"] > .block-inner > *:style(padding-left: unset !important; padding-right: unset !important;)`

The ad element itself has already been hidden by EasyList:
https://github.com/easylist/easylist/issues/16183

### URL(s) where the issue occurs.

`https://coursedrive.org/`

### Screenshot(s)

![Screenshot from 2023-06-03 14-12-53](https://github.com/uBlockOrigin/uAssets/assets/89158249/ad8f2d79-1ef2-4449-bc2c-a54fd64e61e4)

### uBO version

v1.49.3rc15

### Browser name and version

Firefox 113.0.2

### Settings

- Use custom filter lists, checked "I am an advanced user"

**Comment by stephenhawk8054** [comment]
It's minor so I think users can use a custom filter for it.
