### ISSUE TITLE
[NSFW] pornhub.com: ads

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#18375]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

advertising on the main page, as well as at the very bottom of the site

### URL(s) where the issue occurs.

`https://pornhub.com`

### Screenshot(s)
`https://fastpic.org/view/122/2023/0603/_1041410119ce91e5f451e773132d6932.png.html https://fastpic.org/view/122/2023/0603/_2bd9d128fb8204c18a3a7f0ec439b5d1.png.html`

### uBO version

1.49.2

### Browser name and version

google chrome 114.0.5735.91

### Settings

default ubo settings list

**Comment by mapx-** [comment]
@electrifying  Do not use such horrible image hosting servers as `fastpic.org` (ads blocked by russian list only)

maybe you can reproduce the ads @dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Yes, I see this ad. For her blocking is enough: `pornhub.*##+js(nostif, adsbytrafficjunkycontext)`

**Comment by 0calsweetener** [comment]
anti-adblock notice

**Comment by stephenhawk8054** [comment]
> anti-adblock notice

Can you give an exact link and describe what happens in more details?
