### ISSUE TITLE
insider.com: detection

### ISSUE THREAD

**Issue by natsume-shokogami** [uBlockOrigin/uAssets#18370]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.insider.com/doctors-dismissed-29-year-old-anxiety-stage-4-kidney-cancer-2022-5`

### Category

detection

### Description

A popup blocking me from reading the page and tell me to turn off my adblocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230603_075512](https://github.com/uBlockOrigin/uAssets/assets/106172204/acdf9ee7-a962-4515-85bd-a8472c9c2a41)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 113825
 cosmetic: 62580
 scriptlet: 21156
 html: 1104
listset (total-discarded, last-updated): 
 removed: 
  plowe-0: null
 added: 
  ublock-annoyances: 5050-6, 4d.23h.58m
  FRA-0: 28610-411, 21h.54m
  JPN-1: 11515-7, 21h.53m
  spa-0: 3682-1, 11h.51m
  VIE-1: 1938-1, 11h.52m
 default: 
  user-filters: 0-0, never
  ublock-filters: 34187-165, 4d.23h.58m
  ublock-badware: 7169-0, 4d.23h.58m
  ublock-privacy: 420-0, 4d.23h.58m
  ublock-abuse: 69-69, 4d.23h.58m
  ublock-unbreak: 2031-0, 4d.23h.58m
  ublock-quick-fixes: 195-1, 9h.50m
  easylist: 66652-722, 4d.23h.58m
  easyprivacy: 31785-53, 4d.23h.58m
  urlhaus-1: 6942-0, 11h.53m
filterset (user): [empty]
modifiedUserSettings: 
 cloudStorageEnabled: true
 largeMediaSize: 500
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 20806 ms (selfie)
 maxAssetCacheWait: 736 ms
popupPanel: 
 blocked: 23
 network: 
  amazon-adsystem.com: 1
  businessinsider.com: 1
  chartbeat.com: 2
  confiant-integrations.net: 1
  cxense.com: 2
  doubleclick.net: 1
  doubleverify.com: 1
  extractobservation.com: 1
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
  onesignal.com: 1
  parsely.com: 1
  permutive.app: 1
  rubiconproject.com: 1
  scorecardresearch.com: 1
  snapkit.com: 1
  speedcurve.com: 1
  tinypass.com: 2
  trackonomics.net: 1
 cosmetic: 
  ##.ad
  ##.in-post-sticky
  ##div[data-adunit]
  ##.l-ad
  ##.subnav-ad-layout
  ##.subnav-ad-wrapper
  ##.ad-wrapper
  ##.sticky-footer-ad
  ##.sticky-rail-ad-container
  ##.video-ad
  ##.in-post-sticky > .ad-wrapper:upward(1)
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
removed: 
  plowe-0: null
```

You have removed Peter Lowe's list. Enable that list and test again.

**Comment by natsume-shokogami** [comment]
Sorry for bothering you, I have multiple Firefox instances in my Windows, Linux and Android devices and I don't use Mozilla account to sync the lists (due to concern of Mozilla's recent decisions on Firefox, and I don't want to just log in and log out again just to sync something), I didn't check all my devices thoroughly and after turn that filter on my Linux device it now work without detection again.
