### ISSUE TITLE
telecinco.es: breakage

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#18386]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.telecinco.es/socialite/20230604/shakira-barcelona-maletas-entrado-viviendo_18_09705108.html`

### Category

breakage

### Description

Video doesn't play when uBlock Origin is enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2023-06-04 163942](https://github.com/uBlockOrigin/uAssets/assets/43375046/90fc62a0-bb8c-4433-b250-6c08cbd45f29)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 236087
 cosmetic: 209464
 scriptlet: 40443
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67495-97, 1h.31m
  adguard-generic: 71250-464, 3h.2m
  adguard-mobile: 8371-47, 2h.58m
  adguard-spyware-url: 1051-3, 2h.57m
  block-lan: 47-0, 8d.2h.59m
  curben-phishing: 109372-7, 22h.41m
  curben-pup: 199-0, 1d.44m
  fanboy-annoyance: 91010-21003, 1d.46m
  fanboy-cookiemonster: 47275-47269, 5d.43m
  ublock-annoyances: 5086-275, 3d.8m
 default: 
  user-filters: 5-0, never
  easylist: 66810-920, 2d.22h.5m
  easyprivacy: 31575-245, 2d.18h.2m
  plowe-0: 3735-1040, 11d.2h.31m
  spa-0: 3682-38, 22h.42m
  spa-1: 5259-222, 2h.56m
  ublock-abuse: 69-0, 3d.9m
  ublock-badware: 7200-390, 2d.22h.4m
  ublock-filters: 33564-4115, 16h.26m
  ublock-privacy: 380-78, 3d.20h.18m
  ublock-quick-fixes: 193-22, 2h.55m
  ublock-unbreak: 2023-96, 2d.22h.3m
  urlhaus-1: 7002-2, 1d.45m
filterset (user): [array of 5 redacted]
trustedset: 
 added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1102 ms (selfie)
 maxAssetCacheWait: 807 ms
popupPanel: 
 blocked: 36
 network: 
  adform.net: 2
  amazon-adsystem.com: 1
  bannerflow.net: 2
  bkrtx.com: 1
  chartbeat.com: 2
  criteo.net: 2
  doubleclick.net: 1
  go-mpulse.net: 1
  googlesyndication.com: 8
  googletagmanager.com: 1
  gstatic.com: 2
  mediaset.es: 7
  omtrdc.net: 1
  privacy-center.org: 1
  sensic.net: 3
  smartmeapp.com: 1
 cosmetic: 
  ##.alertTop
  ###megaSuperior_multisite
  ##div[class^=\"adsGroupTop\"]
  ##div[class^=\"ads__ad_\"]
  ##div[class^=\"ads__\"]
```
</details>

**Comment by mapx-** [comment]
add

`||mab.mediaset.es^$xhr,badfilter`

@ryanbr FA breakage
