### ISSUE TITLE
pixlr.com: breakage

### ISSUE THREAD

**Issue by Tobias-Auer** [uBlockOrigin/uAssets#18384]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pixlr.com/`

### Category

breakage

### Description

On the right site is an overlay, so I cannot press any button on the panel. I have to “zap” it twice to remove all overlays.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93731
 cosmetic: 39090
 scriptlet: 17693
 html: 935
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34415-58, 1d.20h.16m
  ublock-badware: 7202-0, 1d.20h.16m
  ublock-privacy: 420-0, 6d.3h.12m
  ublock-abuse: 69-69, 6d.3h.11m
  ublock-unbreak: 2035-1, 1d.20h.16m
  ublock-quick-fixes: 195-0, 1h.48m
  easylist: 66653-665, 5d.15h.16m
  easyprivacy: 31293-607, 15h.37m
  urlhaus-1: 7002-0, 15h.37m
  plowe-0: 3724-3, 7d.15h.51m
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
switchRuleset: 
 removed: 
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset: 
 removed: 
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 933 ms (selfie)
 maxAssetCacheWait: 350 ms
popupPanel: 
 blocked: 5
 network: 
  googletagmanager.com: 1
  uniconsent.com: 4
 cosmetic: 
  ###workspace:style(right: 0px !important;)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists and test again?

**Comment by Tobias-Auer** [comment]
Still the same issue

**Comment by gorhill** [comment]
> On the right site is an overlay

What exact URL must we go to reproduce the issue? I went to `https://pixlr.com/` and I don't see anything as described.

**Comment by mapx-** [comment]
from the other issue `https://pixlr.com/e/`

**Comment by Tobias-Auer** [comment]
Now it's working. I don't know why, but it's working. Thanks for your time.
The link was https://pixlr.com/e/ then click on create new and select any option. In the editor on the right side was a problem, but now it's gone.
