### ISSUE TITLE
torrentlocura.com [Pop-up] [redirect]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1838]
URL(s) where the issue occurs

`http://torrentlocura.com/`

Describe the issue

Pop-up

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by SMed79** [comment]
```
torrentlocura.com##a[href$=".html"][rel="nofollow norefferer noopener"]
||liveadoptimizer.com^$popup
```
(https://forums.lanik.us/viewtopic.php?f=103&t=40336)
