### ISSUE TITLE
distrowatch.com: ads

### ISSUE THREAD

**Issue by Nekosis** [uBlockOrigin/uAssets#18382]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://distrowatch.com/table.php?distribution=mx`

### Category

ads

### Description

Shows multiple ads in the website almost as if there was no ad blocker. Applies for all distribution pages on DistroWatch.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/37462865/c44714b2-3874-44e4-9e64-1776f23f8fd0)
Screenshot taken using built in Screenshot Full Page feature in Firefox. You can clearly see multiple ads towards the top of the page.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93738
 cosmetic: 39071
 scriptlet: 17687
 html: 932
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34402-58, 2d.2h.24m
  ublock-badware: 7210-1, 2d.2h.24m
  ublock-privacy: 420-0, 2d.2h.24m
  ublock-abuse: 69-69, 2d.2h.24m
  ublock-unbreak: 2035-1, 2d.2h.24m
  ublock-quick-fixes: 195-0, 9h.17m
  easylist: 66811-658, 2d.2h.24m
  easyprivacy: 31573-601, 2d.2h.24m
  urlhaus-1: 6896-0, 3m
  plowe-0: 3359-2, 2d.2h.24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1317 ms (selfie)
 maxAssetCacheWait: 80 ms
popupPanel: 
 blocked: 5
 network: 
  googlesyndication.com: 1
  media.net: 2
  s-onetag.com: 1
  unblockia.com: 1
 cosmetic: 
  ##a[href*=\"3cx.com\"]
```
</details>

**Comment by mapx-** [comment]
@aaronliu0130

test

    distrowatch.com#@#table .Invert:has-text(/3cx|sponsor|tuxedo|star lab|free tech guides|malibal|advertisement|shells|purism/i):upward(table)
    distrowatch.com##table .Invert:has-text(/3cx|sponsor|tuxedo|star lab|free tech guides|malibal|advertisement|shells|purism/i):upward(table):upward([style="width: 20%; border: 0; margin: 0; padding: 0; vertical-align: top"])

**Comment by aaronliu0130** [comment]
@mapx- That seems to fix the original issue, but now homepage ads have leftovers that weren't there before:

![image](https://github.com/uBlockOrigin/uAssets/assets/11874211/7a50d9c0-457d-4a35-8acf-c4a2c1e1f165)

**Comment by mapx-** [comment]
add only the second filter, test again

**Comment by aaronliu0130** [comment]
seems to work fine now!
