### ISSUE TITLE
lgpc.bestextensionegde.com: ads

### ISSUE THREAD

**Issue by akhi07rx** [uBlockOrigin/uAssets#18387]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lgpc.bestextensionegde.com/plpb/prtk/IS_browserupdate/?s=f0b39168a928dd6b3c253b994612bef9-40706-0604&offer=https://gpc.bestextensionegde.com/offer&pr_key=cf3dab44fbac1726935f66b529a36e7f$YzI4YWVjYWI0YzBjYWUxOQ--egpfSpfJHlo5XtnKsbooMNHqGuNLWYmDw0NLcA3HtAgFlKECDjx.FZixQ30Y8xwOb2Lx.gjPH8oMfCYrDqypP2WHvF5t4qzy.5QYszgpV0hJcV1.x2W3DE1Afr1_nIc.9GHB7ETd3r9SJjPWCWwC3EMPjok4TLn5eKSwL.r6D1zDD_rNywjblOalZeDBJe3qvu.epFiTzpRRsqxjcogxZO3S6i3y4odvMCZDGd6IoEtlbhQHqB.Zxw4cKL_7mrYe4u406IANj5RFZdPHHyps1EdN6rvpyRG1tqkwlXiQzty8I4rQAJPfaWjFmLlWGXHu`

### Category

ads

### Description

The page is displaying an important Edge update and provides an option to install the update for the Edge browser. However, it is  adware.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/89210430/661f4498-163a-488c-a670-bc451f4ad10d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94046
 cosmetic: 39070
 scriptlet: 17687
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 6-1, never
  easylist: 66687-49, 2d.23h.59m
  easyprivacy: 31575-52, 2d.23h.58m
  plowe-0: 3724-937, 2d.19h.56m
  ublock-abuse: 69-0, 2d.23h.59m
  ublock-badware: 7180-130, 2d.23h.57m
  ublock-filters: 33520-104, 2d.23h.58m
  ublock-privacy: 380-74, 2d.19h.55m
  ublock-quick-fixes: 193-21, 5h.5m
  ublock-unbreak: 2023-35, 2d.23h.58m
  urlhaus-1: 7002-0, 19h.20m
filterset (user): [array of 6 redacted]
trustedset: 
 added: [array of 5 redacted]
 removed: 
  edge-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 528 ms (selfie)
 maxAssetCacheWait: 229 ms
popupPanel: 
 blocked: 2
 network: 
  facebook.net: 1
  theonlins.com: 1
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/18380

However, tell us the original page (from which you navigated to that `bestextensionegde` page)

**Comment by iam-py-test** [comment]
IMO should be in badware risks not uBo ad filters
