### ISSUE TITLE
lgpc.bestextensionegde.com: popups

### ISSUE THREAD

**Issue by cr1s5** [uBlockOrigin/uAssets#18380]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lgpc.bestextensionegde.com/plpb/prtk/IS_browserupdate/?s=6618e79fc94738c4695ae62bdd7f1786-40706-0603&offer=https://gpc.bestextensionegde.com/offer&pr_key=cdbcb3c973ed8a9e5a56ca0219a4b196$YzI4YWVjYWI0YzBjYWUxOQ--egpfSpfJHlo5XtnKsbooMBJkUWy1I7ZhCzJL8t.y2nZvJ8J4eC2F69CwxOPlxVj6IzTESZN32RypSZFojKmYbd6gurMWhgPbIQuXhvWYhxDHmIcflEkyvKIkOlBy6ZqyTShtvBXWFEsynAf4PzAykY_YlyJt2N1sPyLYh_D4MNUOh8Mrthmjn4zMsO4I_i7urvk9l6mhJHFbVwVbKuBUhIYjS08F.ZmWH997KcwP6e71Ns7xxCQBKfLu9MWeCr149o18vGEX.34_DjHOrjz.RA--`

### Category

popups

### Description

annoying popup, seems virus, fake extension request...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 94310
 cosmetic: 40875
 scriptlet: 17716
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 665-0, 4d.21h.54m
 default: 
  user-filters: 40-7, never
  HUN-0: 2177-0, 5h.19m
  easylist: 66653-54, 4d.39m
  easyprivacy: 31483-283, 5h.22m
  plowe-0: 3368-922, 1d.40m
  ublock-abuse: 69-2, 4d.23h.43m
  ublock-badware: 7167-130, 3d.26m
  ublock-filters: 33462-108, 2d.22h.25m
  ublock-privacy: 380-74, 4d.21h.55m
  ublock-quick-fixes: 193-21, 5h.18m
  ublock-unbreak: 2030-37, 5h.21m
  urlhaus-1: 7002-0, 5h.20m
filterset (user): [array of 40 redacted]
trustedset: 
 added: [array of 5 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 738 ms (selfie)
 maxAssetCacheWait: 231 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
How did you land on that page ? Give us the original page.

**Comment by cr1s5** [comment]
www.footybite.com

**Comment by akhi07rx** [comment]
> How did you land on that page ? Give us the original page.

Yts torrent site

**Comment by mapx-** [comment]
`yts.mx` ? getting no popups / redirections

**Comment by iam-py-test** [comment]
> Yts torrent site

A *full* url would be helpful. Thanks

**Comment by cr1s5** [comment]
https://streams.footybite.com/home
After clicking an event, then select mntlive13 stream.

**Comment by cr1s5** [comment]
I just came across it on the elixx.xyz stream page too, if that's relevant. (https://gpc.bestextensionegde.com/15GXkw?source=[source]&external_id=1685916165100010THUTV413709433124V5)
uBlock₀ filters succesfully blocked it.
