### ISSUE TITLE
gurufocus.com: nuisance

### ISSUE THREAD

**Issue by RC-Invest6040** [uBlockOrigin/uAssets#18394]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gurufocus.com/stock/BJ/summary`

### Category

nuisance

### Description

Hello guys. Can I avoid this pop-up for normal use of this site? Half of the page is closed by it, it becomes difficult to use the site's tools. If I remove this banner with a pipette from U block origin itself, all the tools of the site become inactive, frozen.Using Default Filters, Default Options, Filters updated, İP adress from Azerbaijan. Thanks for solution in advance, even if it doesn't resolve. 
![bpNoevtc1z](https://github.com/uBlockOrigin/uAssets/assets/135030014/8ce2fb4c-aba6-4c0d-a322-928a5910145d)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 130206
 cosmetic: 100690
 scriptlet: 33240
 html: 950
listset (total-discarded, last-updated): 
 added: 
  adguard-generic: 71263-5410, 5h.8m
  adguard-mobile: 8371-98, 5h.8m
 default: 
  user-filters: 4-0, never
  ublock-filters: 34485-71, 5h.8m
  ublock-badware: 7240-0, 5h.8m
  ublock-privacy: 420-0, 6d.6m
  ublock-abuse: 69-69, 6d.6m
  ublock-unbreak: 2041-0, 5h.8m
  easylist: 66656-711, 6d.6m
  easyprivacy: 31617-719, 6d.6m
  urlhaus-1: 6921-0, 5h.8m
  plowe-0: 3724-3, 6d.6m
  RUS-0: 39564-68, 5h.8m
  ublock-quick-fixes: 195-4, 5h.8m
filterset (user): [array of 4 redacted]
trustedset: 
 added: [array of 17 redacted]
 removed: 
  about-scheme
  moz-extension-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 7078 ms (selfie)
 maxAssetCacheWait: 2380 ms
popupPanel: 
 blocked: 3
 network: 
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
- it's a paywall and we do not address such "issues"
- try as custom filters

```
gurufocus.com##.paywall-shadow
gurufocus.com##body:style(overflow: auto !important;)
```
