### ISSUE TITLE
vegamovies.tips: nuisance

### ISSUE THREAD

**Issue by Potatoaim360** [uBlockOrigin/uAssets#18390]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.vegamovies.tips/download-spider-man-across-the-spider-verse-2023-hdcamrip-hindi-english-full-movie-480p-720p-1080p/`

### Category

nuisance

### Description

1080p Download Button Doesn't Support Long Press..I Wanna Copy Link
For Some Weird Reason There Is A Lot Of Xhr(8000+) Request Only If You Have Online Video Player.. Another Browser Same Site Doesn't Have Online Video Player & Only 5 Request In UBo Icon..Maybe MyFilters Has Some Wrong Thing
[Screenshot_20230605-021057_Firefox Nightly](https://github.com/uBlockOrigin/uAssets/assets/40642163/48e99fbd-9989-4aac-acd0-d48c26dacfa0)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 115
filterset (summary): 
 network: 100697
 cosmetic: 107573
 scriptlet: 24477
 html: 1110
listset (total-discarded, last-updated): 
 added: 
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 959-0, 6h.4m
  adguard-annoyance: 67495-811, 5h.59m
  ublock-annoyances: 5115-6, 6h.4m
 default: 
  user-filters: 1418-18, never
  ublock-filters: 34737-166, 6h.5m
  ublock-badware: 7214-0, 6h.5m
  ublock-privacy: 421-0, 6h.5m
  ublock-abuse: 69-69, 6h.5m
  ublock-unbreak: 2046-4, 6h.5m
  ublock-quick-fixes: 201-4, 6h.5m
  adguard-mobile: 8371-95, 6h.5m
  easylist: 66851-683, 6h.5m
  easyprivacy: 31200-613, 6h.4m
  urlhaus-1: 7022-0, 6h.4m
  plowe-0: 3364-3, 6h.4m
filterset (user): [array of 1118 redacted]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1311 ms
 maxAssetCacheWait: 522 ms
popupPanel: 
 blocked: 875
 network: 
  1024tera.com: 30
  aagmaal.work: 18
  ads2550.bid: 2
  aiplex.com: 12
  aiplexads.com: 6
  aiplexdigital.com: 6
  aiplexorm.com: 6
  anandmarket.in: 6
  anydebrid.com: 12
  apkmagic.com.ar: 24
  apkmb.com: 6
  babarapparel.com: 6
  badisoch.in: 6
  bharatjobresult.com: 6
  bhaskarkhabar.in: 12
  biharfeed.com: 6
  blockxtech.com: 6
  brand-monitor.com: 6
  cloudsek.com: 12
  cscdigitalsevasolutions.com: 24
  dailynews24.in: 66
  delevit.com: 6
  desi49.life: 6
  desisex.site: 6
  dlandroid.com: 6
  dlupload.com: 24
  dmca.com: 24
  dropmms.live: 18
  equalleaks.com: 6
  fortra.com: 24
  fraudwatch.com: 24
  fullnovafilz.click: 6
  gadgetstouse.com: 12
  godigitalzone.in: 6
  googletagmanager.com: 1
  gstcalculatoraustralia.com.au: 6
  holemanwasco.com: 2
  hotuncut.com: 6
  iitmjanakpuri.com: 6
  indianporngirl2.com: 6
  installusd.com: 6
  internetremovals.com: 6
  izoologic.com: 12
  jansoochnaportal.in: 6
  jobrasta.com: 6
  karnatakastateopenuniversity.in: 6
  leechpremium.net: 6
  link-busters.com: 6
  liveinformations.in: 6
  m4u.skin: 6
  mahadbtmahait.in: 6
  masahub.top: 12
  mmsbee24.com: 30
  mmsmasala.com: 24
  modder.me: 12
  moddroid.com: 18
  modlinkz.xyz: 6
  modmentor.com: 6
  modyolo.com: 6
  moneyjacks.com: 6
  moralhindi.com: 6
  mzonews.com: 6
  news10am.com: 12
  onhike.com: 12
  onlinesalah.in: 6
  ottmaza.in: 18
  pdfdays.com: 6
  phishlabs.com: 12
  primeleech.com: 6
  publicholidays.in: 12
  satpudahalchal.in: 6
  shayari.guru: 6
  sociallykeeda.com: 6
  studynumberone.com: 6
  techmny.com: 6
  terabox.com: 12
  urlflix.xyz: 6
  vegamovies.group: 18
  vijaysolution.com: 36
  viralgujju.in: 6
  w3techpanel.com: 6
 cosmetic: 
  ##div.alerrt
  ##.font-size-12.site__col
  ##.comment-respond
  ##.comments-area
  ##.sidebar-content-inner-control.sidebar-content-inner
  ##.footer-copyright
  ##.alerrt
  ###header-social
  ##.nav-breadcrumbs-elm.site__row
  ##.top-ad
  ##p:has-text(/This Movie Is |\\Thank You|\\is the best/)
  ##span:has-text(/Winding|\\~ Vegamovies/)
```
</details>

**Comment by mapx-** [comment]
for xhr 

add
`||tmp.isavetube.com/js/vegamovies.js$script,domain=m.vegamovies.tips`

> Download Button Doesn't Support Long Press

Test without uBO => does it work ?
