### ISSUE TITLE
vermangasporno.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1839]
URL(s) where the issue occurs

`http://vermangasporno.com/doujin/7676.html`

Describe the issue

ADS

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by SMed79** [comment]
```
-920x180.gif
##a[href^="http://gamingadult.biz/"]
```

**Comment by lain566** [comment]
There are pop-ups.
