### ISSUE TITLE
[nsfw] archivebate.com: detection

### ISSUE THREAD

**Issue by keizixo** [uBlockOrigin/uAssets#18393]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://archivebate.com/watch/8498529`

### Category

detection

### Description

Detected 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.49.3rc15:
 since: 2d.15h.54m
Chromium Mobile: 112
filterset (summary):
 network: 185155
 cosmetic: 139767
 scriptlet: 22405
 html: 0
listset (total-discarded, last-updated):
 added:
  ALB-0: 301-10, 5h.54m
  BGR-0: 1091-19, 10h.20m
  CHN-0: 26978-1365, 1d.8h.2m
  CZE-0: 741-40, 5h.53m
  DEU-0: 6884-388, 5h.52m
  EST-0: 460-11, 5h.51m
  FIN-0: 2213-68, 1d.8h.1m
  FRA-0: 28611-3014, 1d.8h
  GRC-0: 995-19, 1d.6h.24m
  HRV-0: 334-12, 9h.1m
  HUN-0: 2177-82, 5h.50m
  IDN-0: 9510-3823, 1d.7h.59m
  [23 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  RUS-0: 39531-1068, 1d.6h.25m
  adguard-mobile: 8371-151, 1d.6h.28m
  easylist: 66844-17581, 1d.6h.27m
  easyprivacy: 31738-589, 5d.11h.24m
  plowe-0: 3724-1083, 5d.11h.24m
  ublock-badware: 7212-163, 8h.50m
  ublock-filters: 33807-641, 8h.49m
  ublock-privacy: 380-10, 5d.11h.24m
  ublock-quick-fixes: 176-25, 3h.37m
  ublock-unbreak: 2035-64, 8h.48m
  urlhaus-1: 6921-0, 20m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3062 ms (selfie)
 maxAssetCacheWait: 614 ms
popupPanel:
 blocked: 3
 network:
  linkvertise.com: 1
  occurclaimed.com: 1
  xpornium.net: 1
 extended:
  ##+js(abort-current-script, decodeURI, decodeURIComponent)
  ##+js(abort-current-script, document.createElement, window.open)
  ##+js(abort-on-property-write, _pop)
```
</details>

**Comment by stephenhawk8054** [comment]
Test again using only uBO's default settings. Don't enable all filter lists including all regions. Do you usually visit sites from all the countries there?
