### ISSUE TITLE
[nsfw] kbjfree.com: nuisance

### ISSUE THREAD

**Issue by zxc1dai** [uBlockOrigin/uAssets#18395]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kbjfree.com/`

### Category

nuisance

### Description

Can't figure out how to bypass adblock detection on this site.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 109874
 cosmetic: 49365
 scriptlet: 17876
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  CHN-0: 27001-118, 6h.14m
  easylist: 66856-109, 6h.14m
  easyprivacy: 31201-73, 6h.14m
  plowe-0: 3364-922, 6h.14m
  ublock-abuse: 69-0, 6h.14m
  ublock-badware: 7238-131, 6h.14m
  ublock-filters: 33612-120, 6h.13m
  ublock-privacy: 381-74, 6h.13m
  ublock-quick-fixes: 182-5, 6h.13m
  ublock-unbreak: 2030-38, 6h.13m
  urlhaus-1: 6921-0, 6h.13m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 1 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4371 ms (selfie)
 maxAssetCacheWait: 689 ms
popupPanel: 
 blocked: 15
 no-popups: true
 network: 
  kbjfree.com: 3
  ccmiocw.com: 1
  cloudflareinsights.com: 1
  d2o03z2xnyxlz5.cloudfront.net: 1
  d2qnx6y010m4rt.cloudfront.net: 2
  tapioni.com: 1
  wbilvnmool.com: 2
  wpadmngr.com: 2
  wyhifdpatl.com: 2
 cosmetic: 
  ##.mantine-18kvxv6.mantine-Overlay-root
  ##.text-center.text-2xl.text-white.font-bold.w-full.top-\\[40\\%\\].z-\\[100000\\].absolute
  ##[href^=\"https://go.xlrdr.com\"]
```
</details>

**Comment by stephenhawk8054** [comment]
There was an update few hours ago. Can you force update all your filter lists and test again?

**Comment by zxc1dai** [comment]
I had forced update all my filter lists yesterday and it had worked, but now maybe the website changed something and it doesn't work again.

**Comment by iam-py-test** [comment]
Update them again. There's a new update

**Comment by zxc1dai** [comment]
OK

**Comment by iam-py-test** [comment]
In the future, please update your filterlists before reporting an issue. uBo's lists are updated many times an hour,
