### ISSUE TITLE
dl-protect.net: breakage

### ISSUE THREAD

**Issue by danielrzad** [uBlockOrigin/uAssets#18399]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dl-protect.net/e1f5c614`

### Category

breakage

### Description

Hi.
The website is displayed differently when uBlock is on and also sometimes it's impossible to get to the destination URL. I will attach a screenshots with uBlock on and off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock_on](https://github.com/uBlockOrigin/uAssets/assets/45539133/dcb49c64-46d7-487b-9966-878a167b7aa7)
![ublock_off](https://github.com/uBlockOrigin/uAssets/assets/45539133/56f683a1-cb6a-412d-99eb-bcff81af55cd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 95136
 cosmetic: 46610
 scriptlet: 17915
 html: 0
listset (total-discarded, last-updated): 
 added: 
  POL-0: 7943-11, 3m
  POL-2: 1275-13, 4m
 default: 
  user-filters: 0-0, never
  easylist: 66683-74, 5d.19h.18m
  easyprivacy: 31573-52, 3d.5h.41m
  plowe-0: 3735-953, 10d.21h.11m
  ublock-abuse: 69-0, 2d.9h.35m
  ublock-badware: 7208-130, 3d.5h.45m
  ublock-filters: 33543-141, 3d.5h.44m
  ublock-privacy: 380-74, 2d.9h.34m
  ublock-quick-fixes: 182-5, 9h.25m
  ublock-unbreak: 2029-38, 3d.5h.43m
  urlhaus-1: 6689-0, 2m
filterset (user): [empty]
trustedset: 
 added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 659 ms
 maxAssetCacheWait: 170 ms
popupPanel: 
 blocked: 11
 network: 
  dl-protect.net: 11
 cosmetic: 
  ##a[href^=\"https://affcpatrk.com/\"]
```
</details>

**Comment by okiehsch** [comment]
Add
`||dl-protect.net^$badfilter`
to your filter list.

**Comment by okiehsch** [comment]
@ryanbr I assume this filter was added by mistake?
