### ISSUE TITLE
golem.de anti adblocker

### ISSUE THREAD

**Issue by alexara** [uBlockOrigin/uAssets#184]
### URL where the issue occurs

`http://www.golem.de/news/sicherheitsluecke-alle-android-geraete-koennen-durch-dirty-cow-gerootet-werden-1611-124326.html`

### Describe the issue

There's an anti ad-blocker bait on the website: The big banner you can see in the screenshot.
When the banner gets blocked by  ` www.golem.de###screen > div:nth-of-type(1)` the adblocker is detected and the page content blurs.

It would be convenient to hide this banner somehow without triggering the anti adblock measurements.

### Screenshot(s)

![bildschirmfoto_2016-11-08_12-51-06](https://cloud.githubusercontent.com/assets/13819719/20098070/216f37d4-a5b2-11e6-82e4-f00a9d92f000.png)

### Versions

- Browser/version: FF49
- uBlock Origin version: 1.9.16

### Settings

Default + EasyList Germany + all anti adblocker filter list
Own rule: www.golem.de###screen > div:nth-of-type(1)

**Comment by gorhill** [comment]
It's self-promotion, not an ad.

**Comment by jjohns71** [comment]
@alexara You can block just the cosmetic element with the following filter (leaves an empty white box in place) without the page content blurring by using an [xpath filter](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#xpath), this seems to work for me:

`golem.de##:xpath(.//*[@class="golem-accountpromo squeeze"])`

**Comment by gorhill** [comment]
> It would be convenient to hide this banner somehow without triggering the anti adblock measurements.

Sorry, I missed that part.

**Comment by gorhill** [comment]
How about:

    golem.de###screen > div:has(:scope > [data-google-query-id])
    golem.de##article:style(filter: none !important; pointer-events: initial !important; position: relative !important;)
    golem.de##article ~ .formatted

**Comment by gorhill** [comment]
This is an excellent case to motivate me to go ahead with a more generic solution in uBO I have thought more and more about lately.

**Comment by gorhill** [comment]
Custom filter for this case: `golem.de##script:inject(abort-on-property-write.js, _sp_)` (need 1.9.17b7).

**Comment by alexara** [comment]
Thank you very much @gorhill, you don't know how much I and surely many others are grateful for your (free!) work.

**Comment by fhamborg** [comment]
thanks a lot :-)
