### ISSUE TITLE
deviantart.com: resource abuse, interactive background in 404 page

### ISSUE THREAD

**Issue by techmetx11** [uBlockOrigin/uAssets#18400]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

DeviantArt has a new 404 page that has an interactive background, This background causes an unnecessary amount of CPU load for handling game logic and rendering

### URL(s) where the issue occurs.

`https://deviantart.com/any-404-page-works-ublock`

### Screenshot(s)

![deviantart](https://github.com/uBlockOrigin/uAssets/assets/114311037/fccb6962-8de2-4dda-a9b9-07abaf637693)

### uBO version

1.49.2

### Browser name and version

LibreWolf (Firefox fork) 111.0.1

### Settings

- Added annoyance filter

**Comment by iam-py-test** [comment]
Not that my opinion matters, but I don't think an annoying/unwanted background game counts as:
> sites potentially abusing CPU/bandwidth resources without informed consent

Thanks
