### ISSUE TITLE
[nsfw] gosexpod.com: ads

### ISSUE THREAD

**Issue by claudiu64** [uBlockOrigin/uAssets#18402]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gosexpod.com`

### Category

ads

### Description

Ad borders appear. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 114
filterset (summary): 
 network: 96093
 cosmetic: 29789
 scriptlet: 17756
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34674-301, 20h.53m
  ublock-badware: 7214-1, 20h.52m
  ublock-privacy: 420-1, 4d.5h.47m
  ublock-abuse: 69-69, 4d.5h.40m
  ublock-unbreak: 2046-5, 20h.51m
  ublock-quick-fixes: 186-1, 1h.57m
  adguard-mobile: 8371-121, 2d.2h.19m
  easylist: 66650-17461, 4d.8h.55m
  easyprivacy: 31573-624, 3d.1h.11m
  urlhaus-1: 7022-0, 6h.27m
  plowe-0: 3724-2, 5d.5h.56m
  ROU-1: 1400-32, 6h.28m
filterset (user): [empty]
trustedset: 
 added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1242 ms (selfie)
 maxAssetCacheWait: 547 ms
popupPanel: 
 blocked: 10
 network: 
  exoclick.com: 3
  googletagmanager.com: 1
  realsrv.com: 2
  tsyndicate.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
The popup is also fixed already. Wait about 10 minutes and force update again.

**Comment by stephenhawk8054** [comment]
Please don't embed NSFW images directly to github, put them as links.
