### ISSUE TITLE
[nsfw] vk.com: breakage

### ISSUE THREAD

**Issue by AxelXadv** [uBlockOrigin/uAssets#18409]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.vk.com/mail`

### Category

breakage

### Description

On load this page not loading hyperlinks, and other function, when site in mobile mode 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 108
filterset (summary): 
 network: 111790
 cosmetic: 49113
 scriptlet: 18801
 html: 950
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34524-298, 57m
  ublock-badware: 7234-1, 56m
  ublock-privacy: 421-1, 1d.7h.13m
  ublock-abuse: 69-69, 1d.7h.12m
  ublock-unbreak: 2047-4, 4h.20m
  ublock-quick-fixes: 184-0, 11h.17m
  adguard-mobile: 8370-114, 3d.1h.24m
  easylist: 66797-17460, 3d.22h.48m
  easyprivacy: 31200-611, 13h.4m
  urlhaus-1: 6653-0, 13h.3m
  plowe-0: 3364-2, 1d.19h.33m
  RUS-0: 39563-1050, 1d.23h.9m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3356 ms (selfie)
 maxAssetCacheWait: 580 ms
popupPanel: 
 blocked: 2
 network: 
  mail.ru: 1
  scorecardresearch.com: 1
```
</details>

**Comment by dimisa-RUAdList** [comment]
@techmetx11 
The problem could not be reproduced. Try turning off filters one at a time to find out which one is causing this behavior.

**Comment by techmetx11** [comment]
> @techmetx11 The problem could not be reproduced. Try turning off filters one at a time to find out which one is causing this behavior.
@dimisa-RUAdList I am not the OP of this issue
