### ISSUE TITLE
spiegel.de: ads

### ISSUE THREAD

**Issue by GittaHuber** [uBlockOrigin/uAssets#18406]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://github.com/uBlockOrigin/uAssets/assets/129629937/776041fb-8a27-4e8a-9461-8d35e58008dd

This is the front ad on spiegel.de. Every other ad is filtered, this one not. I tried to block it, but the ad changes always its name. 

for instance "##.GqvLOgGxk". Next time it is different.  

### URL(s) where the issue occurs.

spiegel.de

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/129629937/dda5a0af-ae71-451c-bc2a-785196a05b4c

### Notes

This central ad shows up and is not to be blocked (everything else is). It changes its name every time: 

##.GqvLOgGxk 

for instance.  Next time different.

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 98320
 cosmetic: 44866
 scriptlet: 17867
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, 21h.27m
  https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 21h.24m
  https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 2d.1h.22m
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 21h.21m
  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 21h.22m
  https://cdn.rawgit.com/NanoMeow/MDLMirror/master/hosts.txt: 1104-0, 20h.13m
 default: 
  user-filters: 100-14, never
  DEU-0: 6884-1, 21h.20m
  easylist: 66687-69, 5d.16h.9m
  easyprivacy: 31483-67, 3d.15h.38m
  plowe-0: 3364-919, 1d.1h.31m
  ublock-abuse: 70-0, 38m
  ublock-badware: 7218-130, 1d.18h.25m
  ublock-filters: 33603-129, 1d.18h.24m
  ublock-privacy: 381-74, 39m
  ublock-quick-fixes: 184-5, 37m
  ublock-unbreak: 2030-39, 2d.13h.16m
  urlhaus-1: 6921-0, 21h.23m
filterset (user): [array of 103 redacted]
trustedset: 
 added: [array of 30 redacted]
 removed: 
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset: 
 added: [array of 6 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 1154 ms (selfie)
 maxAssetCacheWait: 475 ms
```
</details>

**Comment by iam-py-test** [comment]
> ```yml
>  https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, 21h.27m
>  https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 21h.24m
>  https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-1, 2d.1h.22m
>  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 21h.21m
>  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 21h.22m
>  https://cdn.rawgit.com/NanoMeow/MDLMirror/master/hosts.txt: 1104-0, 20h.13m
>```

Remove all of these. None of them have been updated in years, and they will cause more problems than they solve.
