### ISSUE TITLE
[nsfw] manga18sx.com: ads

### ISSUE THREAD

**Issue by Flwk** [uBlockOrigin/uAssets#18408]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://manga18sx.com/`

### Category

ads

### Description

There are some ads that are showing. Before, there weren't any ads, but it's began today.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Here is the screen : https://img001.prntscr.com/file/img001/4EelGdsMQzm4HzJsAZpnJg.png
This NSFW !

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 164122
 cosmetic: 147918
 scriptlet: 35369
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67547-120, 3m
  adguard-generic: 71375-707, 3m
  adguard-mobile: 8374-48, 2m
  adguard-spyware: 43626-1220, 2m
  ublock-quick-fixes: 198-10, 2m
 default: 
  user-filters: 22-1, never
  FRA-0: 28203-33, 3m
  easylist: 66906-992, 2m
  easyprivacy: 31107-13649, 2m
  plowe-0: 3364-1108, 2m
  ublock-abuse: 70-1, 2m
  ublock-badware: 7252-375, 2m
  ublock-filters: 33384-4171, 2m
  ublock-privacy: 383-133, 2m
  ublock-unbreak: 2031-137, 2m
  urlhaus-1: 6653-0, 2m
filterset (user): [array of 22 redacted]
trustedset: 
 added: [array of 36 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 2009 ms (selfie)
 maxAssetCacheWait: 279 ms
popupPanel: 
 blocked: 7
 network: 
  googletagmanager.com: 1
  histats.com: 1
  realsrv.com: 4
  vitrealmandola.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
You can force update all your filter lists in about 10 minutes.

**Comment by Flwk** [comment]
Thank you very much ! :)
