### ISSUE TITLE
No Video Ads, but all videos disappear after a sec @chip.de

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uAssets#1841]
### URL(s) where the issue occurs

```
http://www.chip.de/test/Sony-Xperia-XZ2-Compact-im-Test_136380289.html

http://www.chip.de/news/Supermaerkte-Warum-Milch-immer-ganz-hinten-steht_136702878.html

http://www.chip.de/news/CHIP-Oster-Special-Software-Vollversionen-gratis-abstauben_91273121.html
```

and all other

### Describe the issue

No Video Ads, but all videos disappear after a sec

### Screenshot(s)

![chip de](https://user-images.githubusercontent.com/12896716/38133696-9bca6f24-3410-11e8-9136-8309b1cb67fd.png)

### Versions

- Browser/version: [Firefox 60 beta 8]
- uBlock Origin version: [1.15.19 beta 8]

### Settings

uBO's default settings

**Comment by mapx-** [comment]
don't post clickable links.

**Comment by gorhill** [comment]
For the time being I have to remove all the filters added lately, they keep being bypassed within hours of being added -- they clearly are having their eyes on the repo. Other approaches will have to be investigated -- whoever is welcome to contribute.

**Comment by v-plaza** [comment]
:eyes:
