### ISSUE TITLE
abcya.com: breakage

### ISSUE THREAD

**Issue by Wolfhound905** [uBlockOrigin/uAssets#18410]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.abcya.com/games/create_and_build_car`

### Category

breakage

### Description

The game appears to not load. It looks like the game HTML is actually being cancled. I also tried whitelisting media.abcya.com, but it had no effect.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/58155937/772db916-5deb-40bb-8fe8-dc27cfe3c169)
![image](https://github.com/uBlockOrigin/uAssets/assets/58155937/b38bb074-46a6-4019-89b1-b873138bf575)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93190
 cosmetic: 39125
 scriptlet: 17724
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 66876-49, 1d.4h.36m
  easyprivacy: 31152-56, 1d.4h.35m
  plowe-0: 3364-920, 1d.6h.41m
  ublock-abuse: 69-0, 6d.23h.54m
  ublock-badware: 7238-131, 1d.21h.9m
  ublock-filters: 33608-106, 1d.21h.11m
  ublock-privacy: 380-74, 6d.23h.53m
  ublock-quick-fixes: 182-5, 11h.54m
  ublock-unbreak: 2030-37, 1d.21h.10m
  urlhaus-1: 6668-0, 3h.22m
filterset (user): [empty]
trustedset: 
 added: [array of 9 redacted]
 removed: 
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1221 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel: 
 blocked: 5
 no-cosmetic-filtering: true
 network: 
  admetricspro.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 1
 cosmetic: 
  ##.adfree
  ##.a-skyscraper
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
```
</details>

**Comment by Wolfhound905** [comment]
I don't know what else to do. What should I try?

**Comment by iam-py-test** [comment]
Update your filterlists and retest

**Comment by Wolfhound905** [comment]
Thank you very much @okiehsch!
