### ISSUE TITLE
[nsfw] txxx.com: ads

### ISSUE THREAD

**Issue by claudiu64** [uBlockOrigin/uAssets#18416]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://txxx.com/videos/1835332/riko-miyase-uncensored-hardcore-video3/`

### Category

ads

### Description

Remnants of advertisements (tables) appear. It appears with the text: AD.  

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 115
filterset (summary): 
 network: 95739
 cosmetic: 29789
 scriptlet: 17756
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34674-301, 2d.8h.21m
  ublock-badware: 7214-0, 2d.8h.20m
  ublock-privacy: 420-1, 5d.17h.15m
  ublock-abuse: 69-69, 5d.17h.9m
  ublock-unbreak: 2046-4, 2d.8h.19m
  ublock-quick-fixes: 186-1, 36m
  adguard-mobile: 8371-121, 3d.13h.47m
  easylist: 66650-17461, 5d.20h.23m
  easyprivacy: 31573-624, 4d.12h.39m
  urlhaus-1: 6668-0, 17h.46m
  plowe-0: 3724-3, 6d.17h.24m
  ROU-1: 1400-33, 1d.17h.56m
filterset (user): [empty]
trustedset: 
 added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1698 ms (selfie)
 maxAssetCacheWait: 521 ms
popupPanel: 
 blocked: 12
 network: 
  txxx.com: 5
  googletagmanager.com: 2
  realsrv.com: 2
  yandex.ru: 3
 cosmetic: 
  ##.video-videos-slider
  ##.page-video > div.video-videos-slider ~ div[class]:matches-css(justify-content: center)
  ##.content.page.page-video .video-content > div[class] > div > div[class] > div[class][style^=\"background-image:\"]:style(background-image: none !important;)
```
</details>

**Comment by mapx-** [comment]
see if helps

`txxx.com##span:has-text(AD):upward(2)`

**Comment by claudiu64** [comment]
> see if helps
> 
> `txxx.com##span:has-text(AD):upward(2)`

Yes, it worked, now only a small bar appears. Can you add it to the filter list? 
![Screenshot_20230607-124134_Firefox Nightly](https://github.com/uBlockOrigin/uAssets/assets/114283947/135230a5-a3ab-487c-9259-849e287dd898)

**Comment by claudiu64** [comment]
> see if helps
> 
> `txxx.com##span:has-text(AD):upward(2)`

Yes, it worked, now only a small bar appears. Can you add it to the filter list? 
![Screenshot_20230607-124134_Firefox Nightly](https://github.com/uBlockOrigin/uAssets/assets/114283947/6241b8e6-73e4-40b2-b0ec-2219258ad013)

**Comment by mapx-** [comment]
I cannot reproduce, however let's not exaggerate, such filters has a high breaking potential.

**Comment by dportvine** [comment]
`https://txxx.com/videos/1845061/erotic-pulsion-melisa-mendiny/`

<details>
<summary>Screen</summary>

![2023-06-30_120820](https://github.com/uBlockOrigin/uAssets/assets/111344219/58550067-dd5f-452e-8529-6803fcd1dec3)
</details>
