### ISSUE TITLE
[nsfw] freepublicporn.com: ads

### ISSUE THREAD

**Issue by claudiu64** [uBlockOrigin/uAssets#18423]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://freepublicporn.com/84261-outside-quickie-on-our-walk-to-coast/`

### Category

ads

### Description

Ad remnants appear with white color and large border sizes. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 115
filterset (summary): 
 network: 95276
 cosmetic: 30015
 scriptlet: 17558
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34561-369, 3h.10m
  ublock-badware: 7312-0, 3h.9m
  ublock-privacy: 434-1, 3h.9m
  ublock-unbreak: 2049-2, 3h.9m
  ublock-quick-fixes: 191-1, 3h.9m
  adguard-mobile: 8342-115, 3h.9m
  easylist: 67052-17353, 3h.9m
  easyprivacy: 31090-668, 3h.9m
  urlhaus-1: 6687-0, 3h.9m
  plowe-0: 3364-3, 3h.9m
  ROU-1: 1400-31, 3h.9m
filterset (user): [empty]
trustedset: 
 added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1705 ms (selfie)
 maxAssetCacheWait: 534 ms
popupPanel: 
 blocked: 5
 network: 
  googletagmanager.com: 1
  realsrv.com: 4
 cosmetic: 
  ##div[class^=\"beside-video\"]
  ##div[class^=\"native-boxes\"]
  ##div[class^=\"related-boxes-footer\"]
  ##div[class^=\"textovka\"]
```
</details>

**Comment by mapx-** [comment]
I added thr filters to our list just because we already have a uBO specific filter, otherwise such issues / filters have to be reported at easylist repository.
