### ISSUE TITLE
optiklink.com: detection

### ISSUE THREAD

**Issue by unkowman5** [uBlockOrigin/uAssets#18427]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://optiklink.com/`

### Category

detection

### Description

adblock detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/69849204/6534861e-74f8-4aa1-87ee-24cc8ea7cde9

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium Mobile: 112
filterset (summary): 
 network: 96434
 cosmetic: 39807
 scriptlet: 19042
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  TUR-0: 14122-204, 1d.2h.44m
  adguard-mobile: 8377-34, 1d.2h.44m
  easylist: 67048-16861, 1d.2h.44m
  easyprivacy: 31089-70, 1d.2h.44m
  plowe-0: 3364-998, 1d.2h.44m
  ublock-abuse: 70-0, 1d.2h.44m
  ublock-badware: 7251-132, 1d.2h.44m
  ublock-filters: 33635-362, 1d.2h.44m
  ublock-privacy: 383-76, 1d.2h.44m
  ublock-quick-fixes: 190-7, 5h.23m
  ublock-unbreak: 2038-37, 1d.2h.44m
  urlhaus-1: 6649-0, 2h.27m
filterset (user): [empty]
trustedset: 
 added: [array of 4 redacted]
switchRuleset: 
 added: [array of 2 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2006 ms (selfie)
 maxAssetCacheWait: 326 ms
popupPanel: 
 blocked: 6
 network: 
  googlesyndication.com: 4
  googletagmanager.com: 1
  translate.googleapis.com: 1
 cosmetic: 
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need sign in to create server?

**Comment by unkowman5** [comment]
> 

working
