### ISSUE TITLE
movilzona.es: breakage

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#18420]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.movilzona.es/noticias/problemas/google-maps-elimina-resenas-error/`

### Category

breakage

### Description

Comments section doesn't load when uBlock Origin is enabled (clicking on the button to comment does nothing).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 236618
 cosmetic: 209516
 scriptlet: 40456
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-annoyance: 67495-97, 3d.4h.4m
  adguard-generic: 71250-464, 3d.5h.35m
  adguard-mobile: 8371-47, 3d.5h.31m
  adguard-spyware-url: 1051-3, 3d.5h.30m
  block-lan: 47-0, 11d.5h.32m
  curben-phishing: 110941-7, 22h.49m
  curben-pup: 189-0, 22h.51m
  fanboy-annoyance: 91010-21003, 4d.3h.19m
  fanboy-cookiemonster: 47349-47326, 1d.2h.55m
  ublock-annoyances: 5086-275, 6d.2h.41m
 default: 
  user-filters: 5-0, never
  easylist: 66856-922, 1d.22h.52m
  easyprivacy: 31152-246, 1d.18h.18m
  plowe-0: 3364-1008, 1d.4h.57m
  spa-0: 3682-39, 22h.50m
  spa-1: 5259-221, 3d.5h.29m
  ublock-abuse: 69-0, 6d.2h.42m
  ublock-badware: 7252-392, 22h.54m
  ublock-filters: 33564-4115, 3d.18h.59m
  ublock-privacy: 380-78, 6d.22h.51m
  ublock-quick-fixes: 199-9, 7h.28m
  ublock-unbreak: 2031-98, 22h.53m
  urlhaus-1: 6668-3, 22h.52m
filterset (user): [array of 6 redacted]
trustedset: 
 added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2202 ms (selfie)
 maxAssetCacheWait: 576 ms
popupPanel: 
 blocked: 24
 network: 
  adform.net: 4
  bannerflow.net: 4
  criteo.net: 1
  google-analytics.com: 1
  googlesyndication.com: 10
  googletagmanager.com: 1
  privacy-center.org: 1
  sascdn.com: 1
  scorecardresearch.com: 1
 cosmetic: 
  ##.ad-block
```
</details>

**Comment by mapx-** [comment]
add

`@@||sdk.privacy-center.org^$script,domain=movilzona.es`

@ryanbr @Alex-302

**Comment by Alex-302** [comment]
Fixed https://github.com/AdguardTeam/AdguardFilters/commit/7a91e7ffc38a10fdd3897589cfa46b14350d20fe
