### ISSUE TITLE
antena3.ro: ads

### ISSUE THREAD

**Issue by claudiu64** [uBlockOrigin/uAssets#18429]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.antena3.ro/externe/inceput-contraofensiva-ucraineana-razboi-ucraina-8-iunie-2023-676695.html`

### Category

ads

### Description

Table from the ad, also shows the X button.  Remnants of advertisements. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox Mobile: 115
filterset (summary): 
 network: 95293
 cosmetic: 30036
 scriptlet: 17562
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34575-301, 3h.10m
  ublock-badware: 7322-1, 3h.10m
  ublock-privacy: 435-1, 3h.10m
  ublock-unbreak: 2049-2, 3h.10m
  ublock-quick-fixes: 193-1, 3h.10m
  adguard-mobile: 8344-115, 3h.10m
  easylist: 67103-17469, 3h.10m
  easyprivacy: 31093-625, 3h.10m
  urlhaus-1: 6649-0, 3h.10m
  plowe-0: 3366-2, 3h.10m
  ROU-1: 1400-31, 3h.10m
filterset (user): [empty]
trustedset: 
 added: [array of 11 redacted]
modifiedUserSettings: 
 autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1005 ms (selfie)
 maxAssetCacheWait: 345 ms
popupPanel: 
 blocked: 0
 cosmetic: 
  ##.DAGInScrollContainer
  ##body > .bannerGrey
  ##.bannerBox
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
```
</details>

**Comment by mapx-** [comment]
However for romanian sites just report at [romanian repository](https://github.com/tcptomato/ROad-Block/issues) for the next issues.

**Comment by claudiu64** [comment]
> does this work ?
> 
> `antena3.ro##.close`

With this filter, only the X button disappears, but the border remains.

**Comment by mapx-** [comment]
upload a screenshot indicating that "border"

**Comment by claudiu64** [comment]
> does this work ?
> 
> `antena3.ro##.close`

![Screenshot_20230608-154153_Firefox Beta](https://github.com/uBlockOrigin/uAssets/assets/114283947/650731bc-0b62-4fe8-8cc6-cdd6cda07de4)
![Screenshot_20230608-154313_Firefox Beta](https://github.com/uBlockOrigin/uAssets/assets/114283947/e7562430-ac4d-4d30-aa8c-1d2d951598bf)

**Comment by mapx-** [comment]
@claudiu64 

try
`antena3.ro###ribbon`

**Comment by claudiu64** [comment]
> @claudiu64
> 
> try `antena3.ro###ribbon`

It works with this one, can you update it in the filters?

**Comment by claudiu64** [comment]
@mapx- I updated the filters and I notice that the X button has disappeared again in the video, it shouldn't disappear in the video. 
![Screenshot_20230608-195118_Firefox Beta](https://github.com/uBlockOrigin/uAssets/assets/114283947/be212dc2-560e-4459-8b66-c519457abee8)
