### ISSUE TITLE
daysoftheyear.com: detection

### ISSUE THREAD

**Issue by Lubrsi** [uBlockOrigin/uAssets#18421]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.daysoftheyear.com/`

### Category

detection

### Description

Admiral anti-adblock. `<https://freezingbuilding.com/>`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/25595356/d44df8f7-9a90-427e-8c46-6ca8beda0247)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 114
filterset (summary): 
 network: 103276
 cosmetic: 181978
 scriptlet: 25570
 html: 1108
listset (total-discarded, last-updated): 
 added: 
  adguard-social: 20477-677, 2m
  fanboy-thirdparty_social: 68-0, 2m
  fanboy-cookiemonster: 47386-3782, 2m
  fanboy-social: 16038-17, 2m
  ublock-annoyances: 5058-7, 2m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 67623-1596, never
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91114-80685, never
 default: 
  user-filters: 1-0, never
  ublock-filters: 34296-52, 2m
  ublock-badware: 7318-0, 2m
  ublock-privacy: 434-0, 2m
  ublock-unbreak: 2044-0, 2m
  easylist: 67052-728, 2m
  easyprivacy: 31090-608, 2m
  urlhaus-1: 6687-0, 2m
  plowe-0: 3364-3, 2m
  ublock-quick-fixes: 191-0, 2m
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 9 redacted]
 removed: 
  about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 3770 ms (selfie)
 maxAssetCacheWait: 116 ms
popupPanel: 
 blocked: 9
 network: 
  daysoftheyear.com: 2
  adsafeprotected.com: 2
  advertising.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  pub.network: 1
 cosmetic: 
  ##.footer__social
  ###cmplz-cookiebanner-container
  ##.cookie-statement
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ea639c2def015c2dddb1e2b6a6d78b0ef770cc86
