### ISSUE TITLE
wiki.fextralife.com: ads

### ISSUE THREAD

**Issue by NogrTL** [uBlockOrigin/uAssets#18424]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://diablo4.wiki.fextralife.com/`

### Category

ads

### Description

1. Removing sidebar with single video-ad*(Twitch embedded with "Join VIP to remove all ads and videos" text) from all  `.wiki.fextralife.com` site. Supposedly
2. Adjusting main content to fill side-bar space

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

without filter
![image](https://github.com/uBlockOrigin/uAssets/assets/12021449/28acc3ae-956c-4af5-b197-f826ecdf74e1)

with filters
![image](https://github.com/uBlockOrigin/uAssets/assets/12021449/444f99f8-5195-4dc9-a44e-08e4d4e1486b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 111723
 cosmetic: 61680
 scriptlet: 22465
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1623-0, 9h.20m
  RUS-0: 39487-20, 13h.22m
  ublock-annoyances: 5090-10, 2d.14h.25m
 default: 
  user-filters: 7-0, never
  easylist: 66835-77, 2d.14h.24m
  easyprivacy: 31288-385, 2d.14h.24m
  plowe-0: 3364-926, 2d.14h.24m
  ublock-abuse: 69-1, 2d.14h.24m
  ublock-badware: 7238-131, 2d.14h.24m
  ublock-filters: 33612-139, 2d.14h.24m
  ublock-privacy: 381-74, 2d.14h.24m
  ublock-quick-fixes: 322-165, 13h.21m
  ublock-unbreak: 2030-35, 2d.14h.23m
  urlhaus-1: 6644-0, 9h.19m
filterset (user): [array of 7 redacted]
trustedset: 
 added: [array of 3 redacted]
modifiedUserSettings: 
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 643 ms (selfie)
 maxAssetCacheWait: 241 ms
popupPanel: 
 blocked: 9
 network: 
  addthis.com: 1
  cloudflareinsights.com: 1
  d2v02itv0y9u9t.cloudfront.net: 1
  enthusiastgaming.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  imrworldwide.com: 1
  ttvnw.net: 1
 cosmetic: 
  ###sidebar-wrapper
  ###content-add-a
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##.ad-flex
  ##.mobile-ad
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
  #@#.ad-sidebar
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like self-promotion.

**Comment by NogrTL** [comment]
It's kinda 50/50.

He clearly removes it with VIP subscription.

The possible options is to include it into Annoyance list, because it's not social widget that isn't directly linked to main content.
________________________________

**Comment by stephenhawk8054** [comment]
The link is `https://fextralife.com/be-a-vip/` and the twitch video is the page's channel, so it's a self-promotion.

@okiehsch @mapx- I don't think we address self-promotion in ublock annoyances list?

**Comment by okiehsch** [comment]
Generally we don't, if I remember correctly we did on one or two occasions because they were "more than annoying", so if it is the usual self advertisement stuff we don't.
