### ISSUE TITLE
bluemediafile.sbs: detection

### ISSUE THREAD

**Issue by JoaquinSuez** [uBlockOrigin/uAssets#18434]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bluemediafile.sbs/url-generator-1.php?url=XWWUCOrsJWk+kpqcqmf3WdM9Go8Wvqx2/f0U12F7Gg0XIG1FBQoftZXLFiAA9n37aq72Op0Udd8Tx8FYxO5dhPMEk5suhPiSTRwVp3C2zuQ=`

### Category

detection

### Description

The website detects the ad blocker. I tried uninstalling and reinstalling different filters and userscripts.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
AdNauseam: 3.16.2b0
Chromium: 114
filterset (summary): 
  network: 95676
  cosmetic: 40005
  scriptlet: 35071
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, never
  default: 
    user-filters: 24247-12, never
    adnauseam-filters: 506-3, 4d.9h.20m
    easylist: 66864-73, 2d.17h.18m
    easyprivacy: 31288-58, 3d.9h.18m
    eff-dnt-whitelist: 695-0, 4d.9h.20m
    ublock-abuse: 69-1, 9d.13h.2m
    ublock-badware: 7213-130, 4d.9h.19m
    ublock-filters: 33581-2537, 4d.9h.19m
    ublock-privacy: 380-72, 9d.13h.2m
    ublock-quick-fixes: 216-14, 19h.35m
    ublock-unbreak: 2027-38, 4d.9h.19m
    urlhaus-1: 6687-0, 19h.35m
filterset (user): [array of 1044 redacted]
trustedset: 
  added: [array of 2 redacted]
untrustedset: 
  added: [array of 2 redacted]
modifiedUserSettings: 
  admap: [redacted]
  eventLogging: true
  firstInstall: false
  hidingAds: true
  clickingAds: true
  blockingMalware: true
  disableClickingForDNT: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4643 ms (selfie)
  maxAssetCacheWait: 188 ms
popupPanel: 
  blocked: 0
  enabled: false
```
</details>

**Comment by mapx-** [comment]
> AdNauseam

in uBO no issue, report at adnauseam or remove it + install uBO

**Comment by gorhill** [comment]
Adnauseam should definitely change the URL used to report filter issues: <https://github.com/gorhill/uBlock/blob/1.50.0/src/js/support.js#L232>. cc @dhowe

**Comment by krystian3w** [comment]
more @mneunomne https://github.com/dhowe/AdNauseam/pulls?q=is%3Apr+author%3Amneunomne+is%3Aclosed + https://github.com/dhowe/AdNauseam/commits?author=mneunomne

**Comment by SpectreKelevra** [comment]
So should I re-report this in the AdNauseam link?

**Comment by mneunomne** [comment]
@SpectreKelevra I added it myself here: https://github.com/dhowe/AdNauseam/issues/2366
