### ISSUE TITLE
okmagazine.com: breakage

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18435]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Tried to report this problem around 2 weeks ago and it still isn't solved yet. Caused by `okmagazine.com##.sc-oefIU` in EasyList.
https://github.com/easylist/easylist/issues/15650

### URL(s) where the issue occurs.

`https://okmagazine.com`

### Screenshot(s)

![Screenshot from 2023-06-08 20-52-45](https://github.com/uBlockOrigin/uAssets/assets/89158249/831324fb-3bd7-4b59-9497-b301174f34b0)
![Screenshot from 2023-06-08 20-55-51](https://github.com/uBlockOrigin/uAssets/assets/89158249/0e1bfe9b-0ff3-4a67-a4a8-ff4c96d6abcd)

### uBO version

v1.49.3rc16

### Browser name and version

Firefox 114.0

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by Sonic5435325** [comment]
@ryanbr Seems like there's another huge ad placeholder gap on the site by the class name of `##.sc-jcwofb`
