### ISSUE TITLE
virginatlantic.com: breakage

### ISSUE THREAD

**Issue by brianWreaves** [uBlockOrigin/uAssets#18436]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.virginatlantic.com/flight-search/book-a-flight?cacheKeySuffix=4c7bf972-0e6e-4da2-8224-3f4ef7425ad2`

### Category

breakage

### Description

When performing a search for flights, it appears to be searching but the same flight search form reloads without flights, warnings, alerts, notifications or modals.
 
After disabling uBO extension there are still no flights but there is an informative alert stating: 

> Uh-oh! We're sorry, but no results were found for your search. We have adjusted our flight schedules and some of our flights only operate seasonally or on select days of the week. Try changing your cities or dates for additional results.#101763R
 
Whether with or without Firefox's v113+ _Enhanced Tracking Protection_ enabled, I have the same result.
 
Granted, the airline's system is unable to locate any flights regardless but that is not apparent due to uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
 
![Virgin Airlines Flight Search 230609 with uBO Filter without Alert](https://github.com/uBlockOrigin/uAssets/assets/2764169/3a2b2fc6-dfd9-4814-99cb-27270f83c73a)
 
 
![Virgin Airlines Flight Search 230609 without uBO Filter with Alert](https://github.com/uBlockOrigin/uAssets/assets/2764169/15995151-0bb0-41c9-9154-5de6b103b882)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93472
 cosmetic: 39141
 scriptlet: 17706
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 3-0, never
  ublock-filters: 34470-40, 4d.17h.42m
  ublock-badware: 7240-1, 2d.19h.46m
  ublock-privacy: 423-0, 1d.4h.46m
  ublock-unbreak: 2042-0, 2d.19h.45m
  ublock-quick-fixes: 199-8, 11m
  easylist: 66902-262, 3d.3h.49m
  easyprivacy: 31093-81, 22h.43m
  urlhaus-1: 6649-0, 20h.42m
  plowe-0: 3724-941, 9d.3h.4m
filterset (user): [array of 3 redacted]
trustedset: 
 added: [array of 3 redacted]
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 collapseBlocked: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 147 ms (selfie)
 maxAssetCacheWait: 87 ms
popupPanel: 
 blocked: 31
 network: 
  virginatlantic.com: 7
  demdex.net: 1
  doubleclick.net: 2
  facebook.com: 2
  flashtalking.com: 2
  go-mpulse.net: 1
  kampyle.com: 2
  levexis.com: 2
  newrelic.com: 2
  quantummetric.com: 2
  techlab-cdn.com: 4
  trackjs.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
Which flight locations and which date did you use to search in order to reproduce the same result?

**Comment by brianWreaves** [comment]
Depart:  BNE on 29th June
Arrive:  PNS
Return: 13th July
 
Other fields set to default.
 
Cheers,
Brian

**Comment by stephenhawk8054** [comment]
The site cannot find any `PNS` location on my side: https://github.com/uBlockOrigin/uAssets/assets/66517106/fe6b0565-a11a-4cca-aaab-d44c7b5fc680

**Comment by brianWreaves** [comment]
Try entering "Pensacola".

**Comment by stephenhawk8054** [comment]
Ok I can see it when using US IP. However, the message appears normally for me: https://github.com/uBlockOrigin/uAssets/assets/66517106/7f882694-dcbe-4dfe-997b-70f17911150e

**Comment by brianWreaves** [comment]
@stephenhawk8054 That's for looking into this one.  It may have been an issue with the Virgin website as it is work as expected from both Australia & USA.
Sorry to both you guys!
