### ISSUE TITLE
porcore.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1843]
URL(s) where the issue occurs

`https://porcore.com/video/512/marge-and-homer-having-fun/`

Describe the issue

ADS

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
`https://69games.xxx/`
`http://gamcore.com/`

**Comment by KiLL4FuNK** [comment]
ADS
`https://porcore.com/video/512/marge-and-homer-having-fun/`

ADS
`https://69games.xxx/games/business_angels_7_so_many_things_to_do`

ADS
`https://gamcore.com/games/the_corruption_of_emma`

**Comment by prokr** [comment]
there is some problem, adblock blocks all the content on website in subject
