### ISSUE TITLE
disney.pl: breakage

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#18445]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.disney.pl/`

### Category

breakage

### Description

“Most” of the links and buttons on the site don't work with uBlock Origin enabled (the only button that works is “Zarządzaj ustawieniami” in the footer). You can still open the pages that those buttons and links lead to by opening them in a new tab (for example, by pressing the middle mouse button – pressing LPM doesn't do anything).

EasyPrivacy filter seems to be a problem here.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 114
filterset (summary): 
 network: 94601
 cosmetic: 46759
 scriptlet: 17764
 html: 947
listset (total-discarded, last-updated): 
 default: 
  user-filters: 35-0, never
  ublock-filters: 34365-83, 9h.10m
  ublock-badware: 7331-1, 9h.10m
  ublock-privacy: 437-0, 9h.10m
  ublock-unbreak: 2044-0, 9h.10m
  ublock-quick-fixes: 199-0, 9h.10m
  easylist: 67017-697, 9h.10m
  easyprivacy: 30999-610, 9h.10m
  urlhaus-1: 6270-0, 9h.10m
  plowe-0: 3735-1, 9h.10m
  POL-0: 7951-27, 9h.10m
  POL-2: 1278-12, 9h.10m
filterset (user): [array of 36 redacted]
trustedset: 
 added: [array of 31 redacted]
modifiedUserSettings: 
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 468 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel: 
 blocked: 3
 network: 
  espn.com: 2
  go.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`/twdc-dtci/prod/servercomponent.php?$badfilter`

@ryanbr

**Comment by mapx-** [comment]
@Alex-302 broken by TPf too

`@@||dcf.espn.com/TWDC-DTCI/prod/$script,domain=disney.pl`
