### ISSUE TITLE
pinterest.ca: ads

### ISSUE THREAD

**Issue by AkiraE00** [uBlockOrigin/uAssets#18444]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.ca/`

### Category

ads

### Description

The site is able to sneak in ads as pins. (Attached a screenshot (C&A is a brazilian brand))

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (67)](https://github.com/uBlockOrigin/uAssets/assets/136095725/834d5ef8-3ca6-4d45-ab35-6aa7aee7f9fb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 113
filterset (summary): 
 network: 93840
 cosmetic: 39213
 scriptlet: 17552
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 29-0, never
  ublock-filters: 34367-45, 4m
  ublock-badware: 7331-0, 3m
  ublock-privacy: 421-0, 4d.12h.23m
  ublock-abuse: 69-69, 4d.12h.22m
  ublock-unbreak: 2044-0, 2m
  ublock-quick-fixes: 199-0, 11h.46m
  easylist: 66906-632, 2d.14h.9m
  easyprivacy: 31293-649, 5d.7h.20m
  urlhaus-1: 6712-0, 17h.47m
  plowe-0: 3724-3, 9d.17h.44m
filterset (user): [array of 29 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  moz-extension-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 199 ms (selfie)
 maxAssetCacheWait: 75 ms
popupPanel: 
 blocked: 23
 network: 
  pinterest.ca: 18
  cedexis.com: 1
  pinimg.com: 1
  pinterest.com: 3
```
</details>

**Comment by mapx-** [comment]
> The site is able to sneak in ads as pins

meaning they are not marked as "promoted" ? How can you distinguish between normal pins and promo ones in this case ?
