### ISSUE TITLE
cutly.win [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1844]
URL(s) where the issue occurs

`http://cutly.win/Ckvf`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/87990443f4ea080eb676b6d8c286fff6f2558526
