### ISSUE TITLE
[nsfw] deltabit.co: breakage

### ISSUE THREAD

**Issue by danielrzad** [uBlockOrigin/uAssets#18448]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://deltabit.co/i6hb2gazn9kb`

### Category

breakage

### Description

Cloudflare verification is unpassable on deltabit.co with uBlock turned on. Turning uBlock off immediately resolves problems with verification and site loads its content. Please be careful, when uBlock is off site might display some NSFW ads.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock_on](https://github.com/uBlockOrigin/uAssets/assets/45539133/42a5df79-cce3-4de4-81d3-9456a6b0c874)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 94104
 cosmetic: 46660
 scriptlet: 17709
 html: 0
listset (total-discarded, last-updated): 
 added: 
  POL-0: 7947-11, 17h.46m
  POL-2: 1275-13, 11h.39m
 default: 
  user-filters: 0-0, never
  easylist: 66904-74, 3d.23h.9m
  easyprivacy: 30994-57, 17h.46m
  plowe-0: 3364-928, 2d.12h
  ublock-abuse: 69-0, 7d.29m
  ublock-badware: 7252-131, 2d.19h.28m
  ublock-filters: 33386-143, 2d.19h.27m
  ublock-privacy: 380-74, 7d.28m
  ublock-quick-fixes: 197-7, 54m
  ublock-unbreak: 2031-35, 2d.19h.26m
  urlhaus-1: 6301-0, 17h.45m
filterset (user): [empty]
trustedset: 
 added: [array of 6 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 472 ms (selfie)
 maxAssetCacheWait: 201 ms
popupPanel: 
 blocked: 8
 network: 
  adskeeper.co.uk: 2
  cilsammwcblcv.com: 1
  d3mzokty951c5w.cloudfront.net: 1
  displayvertising.com: 1
  google-analytics.com: 2
  sbkuuzozlm.com: 1
 cosmetic: 
  ##div[id*=\"ScriptRoot\"]
```
</details>

**Comment by okiehsch** [comment]
Does it work if oyu add
````
*$document,csp=worker-src 'none',from=alltube.pl|alltube.tv|assia1.tv|assia2.tv|centrum-dramy.pl|cmovies.ac|coinfaucet.eu|crictime.com|crictime.is|deltabit.co|doodcdn.com|estream.to|extreme-down.tv|flashx.co|flashx.to|flashx.tv|gomo.to|hdvid.fun|hdvid.tv|hitomi.la|kinox.to|lewd.ninja|nflbite.com|pirateproxy.live|plytv.me|potomy.ru|powvideo.cc|powvideo.net|putlocker.to|reactor.cc|rojadirecta.watch|sickrage.ca|streamtape.com|thehiddenbay.com|thepiratebay.org|thepiratebay10.org|torlock.com|tpb.party|uptomega.me|ustream.to|vidoza.co|vidoza.net|wallpoper.com|wearesaudis.net|yazilir.com,badfilter
*$frame,csp=worker-src 'none',from=alltube.pl|alltube.tv|assia1.tv|assia2.tv|centrum-dramy.pl|cmovies.ac|coinfaucet.eu|crictime.com|crictime.is|deltabit.co|doodcdn.com|estream.to|extreme-down.tv|flashx.co|flashx.to|flashx.tv|gomo.to|hdvid.fun|hdvid.tv|hitomi.la|kinox.to|lewd.ninja|nflbite.com|pirateproxy.live|plytv.me|potomy.ru|powvideo.cc|powvideo.net|putlocker.to|reactor.cc|rojadirecta.watch|sickrage.ca|streamtape.com|thehiddenbay.com|thepiratebay.org|thepiratebay10.org|torlock.com|tpb.party|uptomega.me|ustream.to|vidoza.co|vidoza.net|wallpoper.com|wearesaudis.net|yazilir.com,badfilter
*$document,csp=worker-src 'none',from=alltube.pl|alltube.tv|assia1.tv|assia2.tv|centrum-dramy.pl|cmovies.ac|coinfaucet.eu|crictime.com|crictime.is|doodcdn.com|estream.to|extreme-down.tv|flashx.co|flashx.to|flashx.tv|gomo.to|hdvid.fun|hdvid.tv|hitomi.la|kinox.to|lewd.ninja|nflbite.com|pirateproxy.live|plytv.me|potomy.ru|powvideo.cc|powvideo.net|putlocker.to|reactor.cc|rojadirecta.watch|sickrage.ca|streamtape.com|thehiddenbay.com|thepiratebay.org|thepiratebay10.org|torlock.com|tpb.party|uptomega.me|ustream.to|vidoza.co|vidoza.net|wallpoper.com|wearesaudis.net|yazilir.com
*$frame,csp=worker-src 'none',from=alltube.pl|alltube.tv|assia1.tv|assia2.tv|centrum-dramy.pl|cmovies.ac|coinfaucet.eu|crictime.com|crictime.is|doodcdn.com|estream.to|extreme-down.tv|flashx.co|flashx.to|flashx.tv|gomo.to|hdvid.fun|hdvid.tv|hitomi.la|kinox.to|lewd.ninja|nflbite.com|pirateproxy.live|plytv.me|potomy.ru|powvideo.cc|powvideo.net|putlocker.to|reactor.cc|rojadirecta.watch|sickrage.ca|streamtape.com|thehiddenbay.com|thepiratebay.org|thepiratebay10.org|torlock.com|tpb.party|uptomega.me|ustream.to|vidoza.co|vidoza.net|wallpoper.com|wearesaudis.net|yazilir.com
````
to your filter list?
