### ISSUE TITLE
nautil.us: detection

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#18440]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nautil.us/the-world-is-full-of-sleeping-beauties-304237/`

### Category

detection

### Description

`||tangyamount.com^` is a `getadmiral.com` domain currently unblocked. block variants with

`nautil.us##+js(acs, document.createElement, admiral)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 114
filterset (summary): 
 network: 86646
 cosmetic: 42667
 scriptlet: 21417
 html: 1124
listset (total-discarded, last-updated): 
 removed: 
  urlhaus-1: null
  plowe-0: null
 added: 
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1640-0, 20h.8m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 20h.8m
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1736-0, 20h.8m
  https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 20h.8m
  ublock-annoyances: 5059-7, 20h.8m
 default: 
  user-filters: 1754-13, never
  ublock-filters: 34365-140, 5h.10m
  ublock-badware: 7328-0, 20h.8m
  ublock-privacy: 435-0, 20h.8m
  ublock-unbreak: 2044-5, 20h.8m
  ublock-quick-fixes: 199-0, 7h.39m
  easylist: 67109-266, 20h.8m
  easyprivacy: 31093-1358, 20h.8m
filterset (user): [array of 767 redacted]
switchRuleset: 
 added: [array of 4 redacted]
hostRuleset: 
 added: [array of 3 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 757 ms (selfie)
 maxAssetCacheWait: 145 ms
 unsuspendAfter: 556 ms
popupPanel: 
 blocked: 20
 network: 
  nautil.us: 6
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  quantserve.com: 1
  redditstatic.com: 1
  speedcurve.com: 2
  spot.im: 5
  tangyamount.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I don't get any anti-adb, screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/4060c0c2-893a-4215-89dd-c79a61c84111

`||tangyamount.com^` is blocked by Peter Lowe's list. You have removed default lists:

```yaml
removed: 
  urlhaus-1: null
  plowe-0: null
```

Even when PL list is disabled. The domain is blocked by the filter

```adb
/^https:\/\/[0-9a-z]{7,25}\.com\/v2(?:\/0\/)?(?=[-_0-9a-z]{0,84}[A-Z])(?=[-_a-zA-Z]{0,84}[0-9])[-_0-9a-zA-Z]{54,85}(#\?v=[0-9a-f]{32})?$/$script,3p,match-case
```

Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/4dcd1da4-963c-4fe7-a456-e4f637a4a7e9

```yaml
removed: 
  urlhaus-1: null
  plowe-0: null
 added: 
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1640-0, 20h.8m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, 20h.8m
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1736-0, 20h.8m
  https://raw.githubusercontent.com/nuchi/gmail-inbox-high-contrast-restoration/master/gmail-high-contrast-restoration.txt: 61-0, 20h.8m
  ublock-annoyances: 5059-7, 20h.8m
 default: 
  user-filters: 1754-13, never
```

You are using a heavily modified settings.

**Comment by Daxy7** [comment]
sometimes, even after feb 14, on one of a news sites, admiral anti-adblock was present. they might have change their chars, or it was actually before feb 14, either way this should be closed if regex works well
