### ISSUE TITLE
geminifond.com: privacy

### ISSUE THREAD

**Issue by discord3324** [uBlockOrigin/uAssets#18452]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://geminifond.com/gemini-transaction/`

### Category

cryptoscam

### Description
Its scams you it says this: To verify your address, just send from 0.02 to 10 BTC to the address below and get from .20 to 100 BTC back!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.20h.31m
Chromium: 114
filterset (summary):
 network: 92837
 cosmetic: 39245
 scriptlet: 17508
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67048-49, 2d.17h.2m
  easyprivacy: 31090-56, 2d.17h.1m
  plowe-0: 3364-920, 5d.6h.44m
  ublock-abuse: 70-0, 1d.16h.46m
  ublock-badware: 7257-131, 3d.16h.48m
  ublock-filters: 33365-106, 3d.16h.47m
  ublock-privacy: 396-75, 1d.16h.45m
  ublock-quick-fixes: 197-7, 11h.30m
  ublock-unbreak: 2031-34, 3d.16h.46m
  urlhaus-1: 6301-0, 23h.41m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 758 ms (selfie)
 maxAssetCacheWait: 94 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by gorhill** [comment]
It's already blocked by the browsers, both by Chromium and Firefox.

**Comment by Sonic5435325** [comment]
@gorhill I can view it on Firefox even with "Block dangerous and deceptive content" turned on
