### ISSUE TITLE
motorsport.com: detection

### ISSUE THREAD

**Issue by mannyrak** [uBlockOrigin/uAssets#18450]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.motorsport.com/lemans/news/imsa-drivers-defend-americanised-le-mans-safety-car-changes/10480729/?fbclid=IwAR2QamAZcV34oRbmZMKKStCTWqNAAno7ILyorULD8URPF7JTDyE1Gt99r58`

### Category

detection

### Description

Motorsport is detecting Ublock again. It was fixed a while ago but I guess they are hands on on trying to prevent adblockers

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.16h.35m
Chromium: 114
filterset (summary):
 network: 93477
 cosmetic: 40652
 scriptlet: 20881
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5061-7, 20m
 default:
  user-filters: 3-0, never
  easylist: 66968-49, 20m
  easyprivacy: 31000-56, 20m
  plowe-0: 3734-942, 20m
  ublock-badware: 7345-131, 20m
  ublock-filters: 33458-110, 20m
  ublock-privacy: 395-2, 20m
  ublock-quick-fixes: 196-7, 20m
  ublock-unbreak: 2034-35, 20m
  urlhaus-1: 6309-0, 20m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings:
 prefetchingDisabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 778 ms (selfie)
 maxAssetCacheWait: 441 ms
popupPanel:
 blocked: 19
 network:
  motorsport.com: 7
  adgrid.io: 1
  adsafeprotected.com: 1
  amazon-adsystem.com: 2
  chartbeat.com: 1
  cxense.com: 1
  googletagmanager.com: 1
  id5-sync.com: 1
  imasdk.googleapis.com: 1
  minute.ly: 1
  ntv.io: 1
  outbrain.com: 1
 extended:
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
  ###adContainer
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot the detection?

**Comment by mannyrak** [comment]
Sure, here's the screenshot
![Screenshot (93)](https://github.com/uBlockOrigin/uAssets/assets/57325791/02ed33d2-66cc-4837-9cc3-1469baa0002e)

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
motorsport.*##+js(aeld, gtmloaderror)
```

**Comment by mannyrak** [comment]
> Can you test this filter?
> 
> ```
> motorsport.*##+js(aeld, gtmloaderror)
> ```

Awesome, that worked straight out of the gate!!

**Comment by stephenhawk8054** [comment]
@okiehsch There's one thing I'm not sure how to deal with. This page when in first load and reject all non-necessary cookies, it will show an overlay like this: https://github.com/uBlockOrigin/uAssets/assets/66517106/8093004a-eee2-45b6-b17b-4087ba64c180 regardless of using uBO or not.

It can be blocked by `motorsport.*##+js(noeval-if, interactionCount)`. However I'm not sure if this counts as a GDPR thing?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/assets/16838044/ceff888e-d52e-463d-8d35-7bff42449e17

Is the GDPR modal. Your overlay seems to me to be some sort if subscription option unrelated to it.

**Comment by stephenhawk8054** [comment]
Since there's an option of second try to get cookies from users after the true GDPR modal, I think we can address this.
