### ISSUE TITLE
www2.yapo.cl: ads

### ISSUE THREAD

**Issue by Residentcl** [uBlockOrigin/uAssets#18459]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www2.yapo.cl/dashboard` and `https://www2.yapo.cl/`

### Category

[unknown]

### Description

top and side banner advertising.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![yapo](https://github.com/uBlockOrigin/uAssets/assets/1659401/7b65a016-5881-4f76-9011-67d506321a79)
![yapo 1](https://github.com/uBlockOrigin/uAssets/assets/1659401/d5e35a73-8bea-4b0a-8069-727a213aad06)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.13h.29m
Chromium: 114
filterset (summary):
 network: 95644
 cosmetic: 45007
 scriptlet: 17834
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 67015-49, 2d.12h.41m
  easyprivacy: 30994-56, 2d.12h.41m
  plowe-0: 3735-944, 2d.12h.41m
  spa-0: 3684-12, 10h.30m
  spa-1: 5267-212, 2d.12h.41m
  ublock-badware: 7323-131, 2d.12h.41m
  ublock-filters: 33446-137, 2d.12h.41m
  ublock-privacy: 395-5, 2d.12h.41m
  ublock-quick-fixes: 196-7, 27m
  ublock-unbreak: 2033-36, 2d.12h.41m
  urlhaus-1: 6142-0, 10h.29m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 22 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 128 ms (selfie)
 maxAssetCacheWait: 50 ms
popupPanel:
 blocked: 16
 network:
  yapo.cl: 1
  adnxs.com: 2
  appboycdn.com: 1
  ati-host.net: 1
  cloudflare.com: 1
  d31qbv1cthcecs.cloudfront.net: 1
  facebook.net: 1
  googletagmanager.com: 3
  insurads.com: 1
  mpianalytics.com: 2
  scorecardresearch.com: 2
```
</details>

**Comment by mapx-** [comment]
- a chilean ip is required

- for the main page add

`yapo.cl##app-banner`

- for the dashboard an account is required (phone number etc), so maybe only with your account we'd be able to reproduce the ads
- use element picker to craft other filters for dashboard

**Comment by Residentcl** [comment]
Ok, add: ##.banners-dashboard-right

**Comment by mapx-** [comment]
```
yapo.cl##app-banner
yapo.cl##.banners-dashboard-right
```

@Yuki2718  for AG spanish list ?

**Comment by Residentcl** [comment]
add: ##.py-lg-7.pb-4.pt-4 > .ng-star-inserted.d-md-block.d-none > .ng-star-inserted.banner-container.justify-content-center.align-content-center.d-flex
##home-promotional

**Comment by mapx-** [comment]
@Residentcl what are doing the new filters ? We cannot add or ask other maintainer to add such filters

**Comment by Residentcl** [comment]
![1](https://github.com/uBlockOrigin/uAssets/assets/1659401/bd6de05a-304d-4368-ae89-b4c9d7e90ded)
![2](https://github.com/uBlockOrigin/uAssets/assets/1659401/d4d7c96d-7fa1-449b-abac-ae84d92907ed)
![3](https://github.com/uBlockOrigin/uAssets/assets/1659401/506be993-290a-44ba-aab0-8d3815edd6e6)

**Comment by mapx-** [comment]
I added above a new filter.
`##home-promotional`  is hiding self-promotion

**Comment by Yuki2718** [comment]
I removed `yapo.cl##.banners-dashboard-right` given the subsequent conversation and that we can't really check the dashboard. We distinguish self-promotion from ads and do not block them in default lists, it may fit to Annoyances lists though.

**Comment by Residentcl** [comment]
Here are some photos, it doesn't always come out the same, it changes.
![Captura de pantalla (390)](https://github.com/uBlockOrigin/uAssets/assets/1659401/ba63dcee-0a43-4d54-9cff-d135499bbe93)
![Captura de pantalla (391)](https://github.com/uBlockOrigin/uAssets/assets/1659401/6dc4552c-75a2-4cf3-b8cc-424d90056339)

**Comment by Yuki2718** [comment]
@Residentcl Right-click on the ad and choose "Inspect", which should open developer tools. Take screenshots of this and upload them.

**Comment by Residentcl** [comment]
![Captura de pantalla (392)](https://github.com/uBlockOrigin/uAssets/assets/1659401/703f9de8-0afc-480d-bee9-eb4e19c8147a)
![Captura de pantalla (393)](https://github.com/uBlockOrigin/uAssets/assets/1659401/cc605cfc-b330-4d89-a4f3-f98e1ed645f9)

**Comment by Yuki2718** [comment]
I guess something is wrong on your system/uBO. They should be blocked by default setup both cosmetically (`###ad_unit`) and by blocking (`||2mdn.net^`).

**Comment by Residentcl** [comment]
Clear browser cache and uBlock Origin and now it works fine, no weird blank banner.
