### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by metbic** [uBlockOrigin/uAssets#18455]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I tried reporting this from within the adding but the link won't work.
The three-dots-menu button pop-up on Twitter posts breaks with cosmetic filtering enabled. No matter what type of filtering is checked. Same with the re-tweet button popup.
I hope my report is filed correctly. Otherwise I apologize. 

### URL(s) where the issue occurs.

Any Twitter post address will do. 

### uBO version

Current Firefox nightly android version

### Browser name and version

FF nightly 

### Settings

Not sure if any 

### Notes

Couldn't establish any troubleshooting, sorry.

**Comment by gorhill** [comment]
> breaks with cosmetic filtering enabled

Sounds like you misconfigured uBO. You will have to provide troubleshooting information.

> tried reporting this from within the adding but the link won't work.

What do you mean _"link won't work"_? What happens? Navigate to Twitter, then Firefox's three-dot menu => Add-ons => uBlock Origin => click _chat_ icon => click _Troubleshooting information_ => copy/paste content here.
