### ISSUE TITLE
leak.sx: detection

### ISSUE THREAD

**Issue by mazksr** [uBlockOrigin/uAssets#18453]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://leak.sx/`

### Category

detection

### Description

adblock detected message pops up

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 93144
 cosmetic: 39210
 scriptlet: 17541
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  easylist: 67018-49, 1d.8h.5m
  easyprivacy: 31093-56, 2d.7h.4m
  plowe-0: 3724-938, 9d.1h.25m
  ublock-abuse: 70-0, 3d.7h.59m
  ublock-badware: 7329-131, 1d.1h.47m
  ublock-filters: 33458-108, 3h.56m
  ublock-privacy: 381-74, 3d.7h.58m
  ublock-quick-fixes: 196-7, 11h.59m
  ublock-unbreak: 2033-34, 1d.1h.46m
  urlhaus-1: 6142-0, 5h.57m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 3 redacted]
 removed: 
  edge-scheme
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 482 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel: 
 blocked: 16
 network: 
  leak.sx: 1
  cdn4ads.com: 1
  cloudflareinsights.com: 1
  d3g5ovfngjw9bw.cloudfront.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  iogjhbnoypg.com: 1
  makethebusiness.com: 1
  notionsshrivelcustomer.com: 7
  resalag.com: 1
 cosmetic: 
  ##.tw_float_ads_main_Wrap_Both
```
</details>

**Comment by mapx-** [comment]
update uBO to the last version

**Comment by mazksr** [comment]
> update uBO to the last version
Still detected

**Comment by mazksr** [comment]
> update uBO to the last version

Still detected

**Comment by mapx-** [comment]
Did you update all filter lists ?

**Comment by mazksr** [comment]
Turns out i have to update filter list again after updating the extension, it's working now thank you.
