### ISSUE TITLE
fllwers.com: badware/typosquatting

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18454]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Typo of `fllwrs.com`, very misleading URL, easy mistake to make, and dangerous redirect

### URL(s) where the issue occurs.

`fllwers.com`

### uBO version

v1.49.3rc16

### Browser name and version

Firefox 114.0.1

### Settings

- Use custom filters, check "I am an advanced user"

**Comment by iam-py-test** [comment]
Looks parked.

**Comment by Sonic5435325** [comment]
@mapx- Can you please try the URL again? I can reproduce a redirect at least one time when visiting the site.

**Comment by mapx-** [comment]
tried, always parked
