### ISSUE TITLE
filehorse.com: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18469]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.filehorse.com/`

### Category

nuisance

### Description

Using Vialdi 6.1 on Windows 11. Get this pop-up overlay even if I enable all the annoyances filters.

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19490515/0058bbcc-9440-4451-a3a0-f51d69ff7857)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.19h.25m
Chromium: 114
filterset (summary):
 network: 252975
 cosmetic: 143021
 scriptlet: 37775
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2222-0, 3m
  NOR-0: 3206-8, 5h.54m
  adguard-generic: 71564-541, 2m
  adguard-spyware: 43636-999, 1d.19h.24m
  adguard-spyware-url: 1065-141, 1d.19h.24m
  curben-phishing: 104824-7, 5h.54m
  curben-pup: 199-0, 5h.54m
  easylist-newsletters: 6086-13, 1d.19h.24m
  easylist-notifications: 2629-16, 3m
  fanboy-cookiemonster: 47409-218, 1d.19h.24m
  fanboy-social: 16069-13, 1d.19h.24m
  fanboy-thirdparty_social: 68-15, 1d.19h.24m
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 67018-894, 1d.19h.25m
  easyprivacy: 31000-13432, 1d.19h.25m
  plowe-0: 3733-1034, 1d.19h.25m
  ublock-badware: 7329-388, 1d.19h.25m
  ublock-filters: 33471-3752, 1d.19h.25m
  ublock-privacy: 395-65, 1d.19h.25m
  ublock-quick-fixes: 196-8, 5h.54m
  ublock-unbreak: 2034-135, 1d.19h.25m
  urlhaus-1: 6673-3, 5h.54m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1954 ms
 maxAssetCacheWait: 1120 ms
popupPanel:
 blocked: 5
 network:
  adpushup.com: 1
  adrecover.com: 1
  googletagmanager.com: 1
  quantcast.com: 1
  quantserve.com: 1
 extended:
  ##.dx-sb-1
  ##div[id^="td-"]
  ##._ap_apex_ad
  ###newsletter1
  ##.followus_net
  ##.twitter_net
  ##+js(set-constant, isAdBlockActive, false)
```
</details>

**Comment by mapx-** [comment]
Enable `AdGuard – Annoyances`
