### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by alienfxfiend** [uBlockOrigin/uAssets#18464]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/playlist/37i9dQZF1E36AA8KHmnvRw`

### Category

breakage

### Description

uBlock Origins prevents Spotify browser-based from playing any songs, even the player is disabled. I was forced to use a third-party Open Spotify blocking tool. I hope this gets addressed, it appears that Open Spotify is taking measures to circumvent browser adblockers. Ghostery, which I had previously disabled, works in tandem /w this new Open Spotify adblocker on Chrome Store called SpotiAds. I would love to go back to using uBlock Origins on this site. Maybe an Anti-Adblocker Detection tool would be nice ?!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.16h.4m
Chromium: 114
filterset (summary):
 network: 296456
 cosmetic: 224661
 scriptlet: 40700
 html: 0
listset (total-discarded, last-updated):
 added:
  https://curben.gitlab.io/malware-filter/phishing-filter.txt: 14533-0, 386d.22h.16m
  https://curben.gitlab.io/malware-filter/pup-filter.txt: 266-0, 386d.22h.22m
  https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt: 43-0, 843d.13h.45m
  https://gist.githubusercontent.com/opus-x/3e673a9d5db2a214df05929a4eee6a57/raw: 624-65, never
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, 35d.5m
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 0-0, 224d.18h.9m
  https://raw.githubusercontent.com/RedDragonWebDesign/block-everything/master/block-everything.txt: 522-1, 5h.51m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7249-0, 1d.3h.46m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, 5h.47m
  https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_ads.txt: 799-0, 3d.14h.6m
  https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-52, 5h.49m
  https://winhelp2002.mvps.org/hosts.txt: 8729-502, 5h.55m
  [16 lists not shown]: [too many]
 default:
  user-filters: 132-11, never
  easylist: 66899-1467, 5d.10h.39m
  easyprivacy: 30976-13593, 13h.16m
  plowe-0: 3724-2561, 12d.3h.43m
  ublock-abuse: 70-0, 5d.20h.39m
  ublock-badware: 7257-395, 2d.8h.50m
  ublock-filters: 33370-4135, 3d.14h.2m
  ublock-privacy: 382-136, 5d.20h.39m
  ublock-quick-fixes: 195-7, 5h.45m
  ublock-unbreak: 2033-138, 3d.14h.4m
  urlhaus-1: 6179-4, 13h.12m
filterset (user): [array of 136 redacted]
trustedset:
 added: [array of 51 redacted]
 removed:
  edge-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 15 redacted]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
 suspendUntilListsAreLoaded: true
 webrtcIPAddressHidden: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 120
 autoUpdateDelayAfterLaunch: 180
 autoUpdatePeriod: 7
 selfieAfter: 3
supportStats:
 allReadyAfter: 282776 ms (selfie)
 maxAssetCacheWait: 16459 ms
popupPanel:
 blocked: 50
 network:
  spotify.com: 44
  cookielaw.org: 1
  googleoptimize.com: 1
  sentry.io: 3
  spotifycdn.com: 1
 extended:
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by okiehsch** [comment]
> I hope this gets addressed, it appears that Open Spotify is taking measures to circumvent browser adblockers. 

Or you have manually enbaled 28 lists besides the default setup for some reason and that causes the breakage.
The site - and the songs - work fine on my end.

**Comment by alienfxfiend** [comment]
I disabled some Custom Filter Lists, in the process lost a lot of filters, but they are dead now. Open Spotify is working again though.
