### ISSUE TITLE
company blog mistakenly filtered

### ISSUE THREAD

**Issue by arianyazdanshad** [uBlockOrigin/uAssets#18461]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi. 
we have a company website to introduce our services called "[ads.cafebazaar.ir](ads.cafebazaar.ir)" . simply because of having word "ads" in our domain name, the adblocker is blocking main components of the site like stylesheets. could you please whitelist this domain? 

### URL(s) where the issue occurs.

ads.cafebazaar.ir

### uBO version

uBlock Origin 1.50.0

### Browser name and version

Chrome Version 113.0.5672.126 (Official Build) (x86_64)

### Settings

nothing

**Comment by mapx-** [comment]
@MasterKia @ryanbr
