### ISSUE TITLE
barefootuniverse.com: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18466]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://barefootuniverse.com/best-barefoot-shoes-for-wide-and-extra-wide-feet/`

### Category

nuisance

### Description

when scrolling far down the page. This newsletter pop-up show on screen.

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19490515/f587f311-a0cc-4635-b252-4117ce19bb25)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 114
filterset (summary): 
 network: 147811
 cosmetic: 142917
 scriptlet: 37708
 html: 1108
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2221-0, 4h.2m
  adguard-generic: 71497-6240, never
  adguard-spyware-url: 1065-143, 4h.3m
  fanboy-thirdparty_social: 69-0, 4h.2m
  fanboy-cookiemonster: 47417-268, 4h.2m
  fanboy-social: 16069-19, 4h.2m
  ublock-annoyances: 5030-13, 4h.2m
  NOR-0: 3210-11, 4h.2m
  adguard-spyware: 43639-13595, never
  easylist-newsletters: 6089-14, 4h.2m
  easylist-notifications: 2629-3, 4h.2m
 default: 
  user-filters: 0-0, never
  ublock-filters: 34424-53, 4h.3m
  ublock-badware: 7347-1, 4h.3m
  ublock-privacy: 436-2, 4h.3m
  ublock-unbreak: 2045-1, 4h.3m
  ublock-quick-fixes: 203-0, 4h.3m
  easylist: 66971-695, 4h.3m
  easyprivacy: 30856-692, 4h.3m
  urlhaus-1: 6673-0, 4h.3m
  plowe-0: 3734-1, 4h.3m
filterset (user): [empty]
modifiedUserSettings: 
 advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 503 ms (selfie)
 maxAssetCacheWait: 147 ms
popupPanel: 
 blocked: 12
 network: 
  barefootuniverse.com: 1
  facebook.net: 1
  google.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  mediavine.com: 2
  pinterest.com: 1
  typekit.net: 3
 cosmetic: 
  ##a[href^=\"https://plus.google.com/share?\"]
  ##a[href^=\"https://www.facebook.com/sharer/sharer.php\"]
  ##[href^=\"https://www.avantlink.com/click.php\"] img
  ###sb_instagram
  ###BorlabsCookieBox
  ##.BorlabsCookie
  ##div.show-cookie-box
  ##.cookie-box
```
</details>

**Comment by mapx-** [comment]
add

`barefootuniverse.com##.fd-is-open.fd-modal`

@ryanbr @Alex-302
