### ISSUE TITLE
google.com: ads

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#18460]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.google.com/search?q=makaron+ziemniaczany`

### Category

ads

### Description

Ads as first row, on any refresh, https://github.com/uBlockOrigin/uAssets/labels/account%20required unfortunately.

DOM tree: https://gist.github.com/krystian3w/4974720e7c3db309da4ee9cf017e10c0
https://gist.github.com/krystian3w/4974720e7c3db309da4ee9cf017e10c0/raw/First-row.html (https://gist.githubusercontent.com/krystian3w/4974720e7c3db309da4ee9cf017e10c0/raw/First-row.html)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/66a54c0e-69fa-450c-bf3d-47babf734281) |
--- |
Ads with hidden links used as title |

<table><tr><td>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/1e414029-7058-44a8-bf7a-7bef7cec3535)

</td></tr><tr><td>

Bad filter from EL:

```adb
www.google.*##div[jsaction^="mouseover:"]:has(a[href^="/aclk?sa="][href$="&adurl="])
```

</td></tr></table>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.49.3rc16:
 since: 1m
Firefox: 114
filterset (summary):
 network: 94293
 cosmetic: 46730
 scriptlet: 17850
 html: 947
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34431-83, 1m
  ublock-badware: 7347-1, 1m
  ublock-privacy: 436-0, 1m
  ublock-unbreak: 2045-0, 1m
  ublock-quick-fixes: 180-4, 1m
  easylist: 66971-693, 1m
  easyprivacy: 30856-610, 1m
  urlhaus-1: 6179-0, 1m
  plowe-0: 3734-1, 1m
  POL-0: 7951-27, 1m
  POL-2: 1278-12, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2552 ms
 maxAssetCacheWait: 17 ms
popupPanel:
 blocked: 42
 network:
  google.com: 42
 extended*:
  ##div[jsaction^="mouseover:"]:has(a[href^="/aclk?sa="][href$="&a…
```

\* - ##div[jsaction^="mouseover:"]:has(a[href^="/aclk?sa="][href$="&adurl="])

IDK what malfrom to `$="&a…`

</details>

### Notes 

To test maybe:
```adb
##style+div[id]:has(div[jsaction^="mouseover:"] a[href^="/aclk?sa="][href$="&adurl="])
```

**Comment by mapx-** [comment]
`google.com##.main > [class] > div:has([href$="&adurl="])`

@ryanbr

**Comment by dimisa-RUAdList** [comment]
@ryanbr 
@mapx- 

I've been getting a lot of complaints about this rule. It completely hides the search results.

Example: `https://www.google.com/search?q=типы+индивидуальных+дозиметров`

<details>
<summary>Screenshot(s)</summary>

![google](https://github.com/uBlockOrigin/uAssets/assets/20126984/6eef6ec0-cb7f-4d2d-bfa6-2b2a6263567d)

</details>
