### ISSUE TITLE
bazadecrypto.com: detection

### ISSUE THREAD

**Issue by mild787** [uBlockOrigin/uAssets#18467]
for site `bazadecrypto.com` need update for filter. owner already update to for adb. so now condition detection again. 
just info, detection notif after click signin or maybe after login.
maybe any one can help for this issue. 
thanks
![image](https://github.com/uBlockOrigin/uAssets/assets/121563747/f1b20a25-c40c-414d-b42e-4a959bc36435)

_Originally posted by @mild787 in https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-6134687_

**Comment by mapx-** [comment]
original link ?

**Comment by ghajini** [comment]
looks like thier login page detects it
`https://bazadecrypto.com/login`

filters=

`||banner.infoey.com^$image,redirect-rule=1x1.gif,domain=bazadecrypto.com`
`*$frame,redirect-rule=noop.txt,domain=bazadecrypto.com`

or

`bazadecrypto.com##+js(nostif, myinfoey)`

**Comment by mild787** [comment]
> this one is not working
> 
> ```
> ||banner.infoey.com^$image,redirect-rule=1x1.gif,domain=bazadecrypto.com
> *$frame,redirect-rule=noop.txt,domain=bazadecrypto.com
> ```
> 
> and the one underneath 'water is blank screen after logging in.!

yup, need update filter for this site. i think owner already update. 
@ghajini maybe any idea for reproduce? thanks

**Comment by ghajini** [comment]
try
```
bazadecrypto.com##+js(nostif, myinfoey, 1500)
bazadecrypto.com##body:style(display: block !important)
```

**Comment by mild787** [comment]
> try
> 
> ```
> bazadecrypto.com##+js(nostif, myinfoey, 1500)
> bazadecrypto.com##body:style(display: block !important)
> ```

done, work better. thanks
