### ISSUE TITLE
google.com: breakage

### ISSUE THREAD

**Issue by OPStellar** [uBlockOrigin/uAssets#18468]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.google.com/search?q=rog+fusion+ii+300&source=lmns&bih=968&biw=1722&client=opera-gx&hs=Glp&hl=en&sa=X&ved=2ahUKEwjuhIfQ-7v_AhW1l4QIHRb1C70Q0pQJKAB6BAgBEAI`

### Category

breakage

### Description

The page indicates that results load but they do not show unless uBO is disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1661" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/49218413/b3964256-34be-4a81-ab70-d1657154299e">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 289968
 cosmetic: 156055
 scriptlet: 22772
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7249-0, 1d.8h.45m
  https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5768-1, 11d.17h.10m
  BGR-0: 1091-11, 1d.10h.53m
  CHN-0: 25934-115, 3d.21h.7m
  CZE-0: 744-1, 42m
  DEU-0: 6899-0, 41m
  EST-0: 460-5, 40m
  FIN-0: 2204-0, 3d.20h.33m
  FRA-0: 28203-84, 3d.20h.32m
  GRC-0: 995-1, 1d.8h.48m
  HUN-0: 2177-3, 39m
  IDN-0: 9510-21, 3d.20h.9m
  IRN-0: 2919-1, 3d.20h.8m
  ISL-0: 194-1, 1d.10h.52m
  ISR-0: 1725-2, 38m
  ITA-0: 11933-118, 36m
  JPN-1: 11581-17, 3d.20h.6m
  KOR-1: 4443-24, 29m
  LTU-0: 1244-8, 5d.16h.7m
  LVA-0: 396-4, 3d.20h.5m
  [18 lists not shown]: [too many]
 default: 
  user-filters: 101-2, never
  easylist: 67172-587, 48m
  easyprivacy: 31089-595, 2d.8h.41m
  plowe-0: 3724-1043, 12d.16h.43m
  ublock-abuse: 70-49, 5d.16h.9m
  ublock-badware: 7345-200, 1d.10h.51m
  ublock-filters: 33472-417, 1d.10h.50m
  ublock-privacy: 381-108, 5d.16h.8m
  ublock-quick-fixes: 195-8, 30m
  ublock-unbreak: 2033-57, 1d.10h.49m
  urlhaus-1: 6673-3, 43m
filterset (user): [array of 101 redacted]
trustedset: 
 added: [array of 26 redacted]
 removed: 
  chrome-extension-scheme
  chrome-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 4802 ms (selfie)
 maxAssetCacheWait: 413 ms
popupPanel: 
 blocked: 15
 network: 
  google.com: 13
  doubleclick.net: 2
 cosmetic: 
  ###tads
  ###atvcap
  ##.cu-container > div[class*=\"commercial-unit\"]
  ###taw
  ###tads[aria-label]
  ##a[href^=\"https://www.googleadservices.com/pagead/aclk?\"]
  ##.main > [class] > div:has([href$=\"&adurl=\"])
  ##.ytp-ad-progress-list
  ###player [class*=\"suggested-action-badge-icon\"]:upward(.ytp-suggested-action)
```
</details>

**Comment by OPStellar** [comment]
ok that seems to have worked, but now this happened:
<img width="440" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/49218413/35f2ee3e-b870-4a96-b8ee-264529335f6f">

**Comment by Pacban123** [comment]
I am still having this problem. Google searches, flashes up search results for a split second, then shows no results. Only happens with Ublock turned on

**Comment by stephenhawk8054** [comment]
@Pacban123 Can you force update all your filter lists and test again?

**Comment by stephenhawk8054** [comment]
> ok that seems to have worked, but now this happened: <img alt="image" width="440" src="https://user-images.githubusercontent.com/49218413/244966490-35f2ee3e-b870-4a96-b8ee-264529335f6f.png">

Resource abuse list is already merged to `ublock filters - privacy`, you can click on the trash icon to remove it.

**Comment by dportvine** [comment]
If the dark theme is enabled in Windows settings, does Google automatically switch to the dark theme? If you turn uBo off, it will switch.

`https://www.google.com/search?q=a`

<details>
<summary>video</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/a45ac78d-3a1b-4556-9983-bc2cf239a56c
</details>

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 114873
 cosmetic: 128810
 scriptlet: 26185
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26352-18, 50m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1646-26, 50m
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 765-0, 50m
  fanboy-cookiemonster: 48420-413, 50m
  ublock-annoyances: 5453-59, 50m
  ublock-cookies-easylist: 282-282, 50m
 default:
  user-filters: 0-0, never
  ublock-filters: 34541-45, 51m
  ublock-badware: 7955-0, 50m
  ublock-privacy: 545-7, 50m
  ublock-unbreak: 2131-7, 50m
  ublock-quick-fixes: 263-53, 50m
  easylist: 70376-287, 50m
  easyprivacy: 33208-403, 50m
  RUS-0: 39910-288, 50m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 932 ms (selfie)
 maxAssetCacheWait: 535 ms
popupPanel:
 blocked: 20
 network:
  google.com: 20
 extended:
  ###atvcap
  ##+js(remove-node-text, script, cookieUpdateConsentUrl)
  ##+js(remove-attr, jsaction, #islsp c-wiz a[href^="http"][data-v…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
```
</details>

**Comment by dportvine** [comment]
@stephenhawk8054 
Can you check?

**Comment by stephenhawk8054** [comment]
@dportvine I can't reproduce: https://github.com/uBlockOrigin/uAssets/assets/66517106/442f26a5-98b5-4e38-8948-04c206aa7cbb

**Comment by dportvine** [comment]
Sorry please i have a problem with **RU AdList: Counters**.

@dimisa-RUAdList Can you check? If I exclude this rule, the problem is solved.

`||google.*/client_204?` ~> **RU AdList: Counters**
