### ISSUE TITLE
cinedetodo.com [Pop-up] [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1846]
URL(s) where the issue occurs

`http://www.cinedetodo.com/drama/ver-megan-leavey-online/ [Pop-up] [ADS]`

Describe the issue

ADS

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by lain566** [comment]
There's a popup when you play the video.
`https://www.cinedetodo.com/episode/final-space-temporada-1x9/`

**Comment by lain566** [comment]
The domain has changed, and there is an antiadblock warning.

**Comment by okiehsch** [comment]
`https://www.pelisrex.com/episode/final-space-temporada-1x9`

I tried all streaming options and can't reproduce an antiadblock warning.

**Comment by okiehsch** [comment]
I missed **mapx-'s** commit and pushed mine over it, removed duplicates in https://github.com/uBlockOrigin/uAssets/commit/777754d0b117d48ab32be6c834d57d4f79121d84
