### ISSUE TITLE
Microsoft Edge new tab page: ads

### ISSUE THREAD

**Issue by user31415192** [uBlockOrigin/uAssets#18475]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Apparently, ads show up on Microsoft Edge's new tab page, even though uBO is supposed to block them.
This may be caused by it falling under the `edge-scheme` trusted site directive, allowing ads to show up.

### URL(s) where the issue occurs.

`edge://newtab`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/108060704/0e5dd0a0-8a51-4af5-b9a5-ad60cb8b6f41

Orange boxes indicate **ads**.

### uBO version

1.50.0

### Browser name and version

Microsoft Edge version 114.0.1823.43 (64-bit)

### Settings

- Enabled all filter lists, including regional ones _(yet the ads show up anyway)_

**Comment by iam-py-test** [comment]
I don't think browser extensions can access the new tab page, thus ads/trackers on it are not blocked by uBo.

**Comment by Daxy7** [comment]
> click the gear icon 

yeah firefox has a similar page where sponsors/sponsored shortcuts can be turned off

**Comment by user31415192** [comment]
damnit... 
![Screenshot 2023-06-18 223706](https://github.com/uBlockOrigin/uAssets/assets/108060704/ce686b34-ce12-44be-94ea-f0f14dec0cfd)

**Comment by iam-py-test** [comment]
Nothing the unlock Origin team can do: https://github.com/gorhill/uBlock/wiki/Privileged-Pages
Complaining to them will not change that 
There was a way to allow browser extensions to access to internal browser pages (at the cost of security), but I think that doesn't work anymore.
My comment above explains how to configure the edge homepage 
Thanks
