### ISSUE TITLE
financeyogi.net: detection

### ISSUE THREAD

**Issue by Signup-pawan** [uBlockOrigin/uAssets#18477]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://financeyogi.net/why-does-india-have-two-stock-exchanges-bse-and-nse/`

### Category

detection

### Description

`https://link.tnlink.in/SfELJaHS `

Opened this link, it has showed ad-block detected. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[https://prnt.sc/-VZ6Kjoe4J5H](url)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 114
filterset (summary): 
 network: 92985
 cosmetic: 39349
 scriptlet: 17535
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34328-40, 2h.32m
  ublock-badware: 7348-1, 2h.32m
  ublock-privacy: 423-0, 5d.23h.50m
  ublock-abuse: 70-70, 5d.23h.49m
  ublock-unbreak: 2051-0, 2h.32m
  ublock-quick-fixes: 237-5, 2h.32m
  easylist: 67172-683, 2h.32m
  easyprivacy: 30860-604, 32m
  urlhaus-1: 6151-0, 2h.32m
  plowe-0: 3724-2, 13d.8m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 7007 ms (selfie)
 maxAssetCacheWait: 3386 ms
popupPanel: 
 blocked: 25
 network: 
  chpadblock.com: 2
  demand.supply: 3
  doubleclick.net: 13
  googlesyndication.com: 2
  googletagmanager.com: 3
  playstream.media: 2
 cosmetic: 
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by huyszn** [comment]
The site is also related to `tnshort.net` link shortener (`https://link.tnshort.net/grammarly`). I used the filters

```
financeyogi.net,finclub.in###btn2, .tp-blue:style(display: block !important;)
financeyogi.net,finclub.in###btn2, .tp-blue:others()
```
to bypass timers but there might be a better solution since it still shows verify and please wait buttons
