### ISSUE TITLE
cinemahd.co [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1847]
URL(s) where the issue occurs

`http://www.cinemahd.co/episode/ver-homeland-temporada-7-capitulo-7/`

Describe the issue

Pop-up

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by lain566** [comment]
There's a pop-up.

**Comment by lain566** [comment]
@okiehsch There's still a popup when click anywhere.

**Comment by okiehsch** [comment]
Should be fixed now.

**Comment by lain566** [comment]
Fake buttons and popup again
`https://www.cinemahd.co/peliculas/ver-deadpool-2-hd-online/`

![ver_deadpool_2_hd_online_descargar_gratis_hd_1080p_2018-08-04_01-48-33](https://user-images.githubusercontent.com/27441315/43670116-ce1b6862-9788-11e8-82cf-b30fba8fc401.png)

**Comment by lain566** [comment]
@okiehsch What do you think about this filter?
`cinemahd.co##script:inject(abort-on-property-write.js, document.currentScript)`

 Instead of a cosmetic filter `##a[href^="https://bj1110.online/"]`
