### ISSUE TITLE
reichelt.de: breakage

### ISSUE THREAD

**Issue by goltmanns** [uBlockOrigin/uAssets#18474]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reichelt.de/`

### Category

breakage

### Description

Product images on top of each entry are missing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230612_110637](https://github.com/uBlockOrigin/uAssets/assets/94743207/912582cc-5a65-4273-aab9-0ce1ba111c4c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 114
filterset (summary): 
 network: 95804
 cosmetic: 43923
 scriptlet: 17639
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34424-40, 16h.41m
  ublock-badware: 7348-1, 16h.41m
  ublock-privacy: 436-0, 16h.41m
  ublock-unbreak: 2045-0, 16h.41m
  ublock-quick-fixes: 237-5, 1h.57m
  easylist: 67172-686, 16h.41m
  easyprivacy: 30859-619, 16h.41m
  urlhaus-1: 6673-0, 16h.41m
  plowe-0: 3734-1, 16h.41m
  DEU-0: 6899-17, 16h.41m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 222 ms (selfie)
 maxAssetCacheWait: 109 ms
popupPanel: 
 blocked: 4
 network: 
  reichelt.de: 2
  reichelt.com: 2
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce.

@goltmanns Have you verified that uBO is really the issue?
