### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by GeorgeMixas** [uBlockOrigin/uAssets#18470]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/2AF8h/Amnesia_The_Bunker-FLT.part1.rar`

### Category

detection

### Description

Website detects ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 93324
 cosmetic: 39294
 scriptlet: 17526
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 67048-49, 3d.2h.59m
  easyprivacy: 30856-56, 6h.17m
  plowe-0: 3734-942, 4h.16m
  ublock-badware: 7257-131, 3d.5h.3m
  ublock-filters: 33445-106, 3d.5h.2m
  ublock-privacy: 381-5, 6d.5h.44m
  ublock-quick-fixes: 201-7, 6h.17m
  ublock-unbreak: 2033-34, 3d.5h
  urlhaus-1: 6673-0, 4h.15m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 346 ms (selfie)
 maxAssetCacheWait: 128 ms
popupPanel: 
 blocked: 11
 network: 
  megaup.net: 2
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 1
  dmmzkfd82wayn.cloudfront.net: 2
  googletagmanager.com: 1
  kaspersky-labs.com: 1
  keydawnawe.com: 1
  s3.amazonaws.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you check if you can update your extensions in chromium settings?

**Comment by JobcenterTycoon** [comment]
I fixed now for users without the latest version https://github.com/uBlockOrigin/uAssets/commit/b9c4c5e44c195e4e09ff6409118570885cfdc6d3

**Comment by rrrcabral** [comment]
i have same problem now. im on tha last version 1.50.0

**Comment by JobcenterTycoon** [comment]
Force update the filterlists it got fixed 6 hours ago https://github.com/uBlockOrigin/uAssets/commit/ae74246c232be716d84d2ad208cecccdceccd4dd
