### ISSUE TITLE
go.freetrx.fun: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18483]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://go.freetrx.fun/post/instant-payout-no-mn-wd`

### Category

detection

### Description

Detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://github.com/uBlockOrigin/uAssets/assets/75168867/caa56296-1e30-43b3-9699-fc4072378d07

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.6h.46m
Chromium: 114
filterset (summary):
 network: 92933
 cosmetic: 39315
 scriptlet: 17667
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 21-2, never
  easylist: 67175-49, 49m
  easyprivacy: 30860-59, 49m
  plowe-0: 3734-943, 49m
  ublock-abuse: 70-0, 49m
  ublock-badware: 7348-132, 49m
  ublock-filters: 33575-112, 49m
  ublock-privacy: 396-72, 49m
  ublock-quick-fixes: 238-11, 49m
  ublock-unbreak: 2041-34, 49m
  urlhaus-1: 6023-0, 49m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11814 ms (selfie)
 maxAssetCacheWait: 589 ms
popupPanel:
 blocked: 29
 network:
  a-ads.com: 1
  adskeeper.com: 4
  cryptocoinsad.com: 1
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 1
  googletagservices.com: 1
  orquideassp.com: 18
  surfe.pro: 1
  waust.at: 1
 extended:
  ##+js(nano-setInterval-booster, timer)
```
</details>

**Comment by JobcenterTycoon** [comment]
Why you reporting it twice? The issue got fixed already https://github.com/uBlockOrigin/uAssets/commit/7cdab7f68d3dd3438358433c91317a4fa960f5dd

**Comment by JobcenterTycoon** [comment]
Force update the filterlists and test again.

**Comment by JobcenterTycoon** [comment]
When you got redirected from a link shortener please pass us the shortened link because i get no anti adblock when i open `https://go.freetrx.fun/post/instant-payout-no-mn-wd` directly.

**Comment by JobcenterTycoon** [comment]
Test the filter from here: https://github.com/uBlockOrigin/uAssets/discussions/18449#discussioncomment-6240664
