### ISSUE TITLE
acortaenlace.com: detection

### ISSUE THREAD

**Issue by ragg102** [uBlockOrigin/uAssets#18484]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://acortaenlace.com/`

### Category

detection

### Description

its detect the uorigin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 114
filterset (summary): 
 network: 95261
 cosmetic: 45074
 scriptlet: 17832
 html: 936
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  ublock-filters: 34317-145, 3d.23h.25m
  ublock-badware: 7328-1, 3d.23h.24m
  ublock-privacy: 435-0, 1d.22h.54m
  ublock-abuse: 70-70, 1d.22h.53m
  ublock-unbreak: 2044-0, 3d.23h.23m
  ublock-quick-fixes: 236-0, 1h.9m
  easylist: 67015-598, 2d.18h.27m
  easyprivacy: 31107-662, 4d.20h.25m
  urlhaus-1: 6023-0, 1h.10m
  plowe-0: 3364-1, 9d.36m
  spa-0: 3684-1, 1h.11m
  spa-1: 5269-156, 20h.20m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 228 ms (selfie)
 maxAssetCacheWait: 81 ms
popupPanel: 
 blocked: 2
 network: 
  exoclick.com: 2
```
</details>

**Comment by okiehsch** [comment]
We need a link that works...
