### ISSUE TITLE
[NSFW] pixhost.to: popups

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#18480]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A pop-under occurs when using the navigation arrows in the top right section of the web page to navigate to the previous or next image in the collection.

Steps To Reproduce:

1. Visit URL.
2. Click on a thumbnail.
3. Let image fully load.
4. Click on either the back or front navigation arrow in the top right section of the web page to navigate to the previous or next image in the collection.
5. Notice the pop-under.

### URL(s) where the issue occurs.

[NSFW] `https://pixhost.to/gallery/IeJeG` [NSFW]

### Screenshot(s)

`https://github.com/uBlockOrigin/uAssets/assets/136285419/136cb82e-016e-4fea-a6b6-93d6023015bd`

### uBO version

uBO 1.49.3rc16

### Browser name and version

Firefox 114.0.1

### Settings

N/A

**Comment by mapx-** [comment]
test

`pixhost.to##+js(rmnt, script, exdynsrv)`
