### ISSUE TITLE
shorterall.com: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18489]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shorterall.com/ENjzmK`

### Category

detection

### Description

Need to uninstall adblocker visit this site?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/75168867/991c2caa-850d-4a80-a4a0-0567aaaf7b26)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.17h.27m
Chromium: 114
filterset (summary):
 network: 92940
 cosmetic: 39302
 scriptlet: 17666
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3006-3006, never
  easylist: 67181-49, 29m
  easyprivacy: 30860-59, 29m
  plowe-0: 3734-943, 29m
  ublock-abuse: 70-0, 29m
  ublock-badware: 7353-132, 29m
  ublock-filters: 33575-112, 29m
  ublock-privacy: 396-72, 29m
  ublock-quick-fixes: 238-11, 29m
  ublock-unbreak: 2042-34, 29m
  urlhaus-1: 6023-0, 28m
filterset (user): [array of 1655 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9279 ms (selfie)
 maxAssetCacheWait: 769 ms
popupPanel:
 blocked: 38
 network:
  shorterall.com: 1
  3lift.com: 1
  4dex.io: 2
  a-mo.net: 1
  adleadevent.com: 1
  cdnspace.io: 1
  cpx.to: 1
  criteo.com: 3
  criteo.net: 1
  diclotrans.com: 1
  e-planning.net: 1
  googletagmanager.com: 1
  goomaphy.com: 1
  hoojique.xyz: 4
  id5-sync.com: 1
  onetag-sys.com: 2
  quantserve.com: 1
  sascdn.com: 1
  sddan.com: 1
  tapioni.com: 1
  themoneytizer.com: 9
  unblockia.com: 1
  zeotap.com: 1
 extended:
  ##+js(set-constant, blurred, false)
  ##+js(no-setTimeout-if, alert)
  ##+js(abort-current-script, decodeURI, decodeURIComponent)
  ##+js(abort-on-property-write, atOptions)
  ##+js(window.open-defuser)
  ##+js(abort-current-script, parseInt, break;case $.)
```
</details>

**Comment by stephenhawk8054** [comment]
Please discuss here: https://github.com/uBlockOrigin/uAssets/discussions/17361
