### ISSUE TITLE
istotne.pl: ads (placeholders)

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#18495]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad placeholders due to `generichide` in polish filters, not fixed due to inactivity / lack of time of the maintentainer of PL lists:
- https://github.com/MajkiIT/polish-ads-filter/issues/21550

### URL(s) where the issue occurs.

`https://istotne.pl/boleslawiec/wiadomosc/frT/zlodziej-strzelil-do-ochroniarza-w-biedronce-przed-policja-uciekal-przez-okno-doznal-urazu-nogi`

### uBO version

1.49.3rc16

### Browser name and version

Firefox 114.0.1 + Opera 109

### Settings

Def + PL, also tried EasyList Polish & AdGuard Base, but it didn't help either

**Comment by okiehsch** [comment]
````
istotne.pl##.adsbygoogle
istotne.pl##.advert
istotne.pl##.advert_right
````
