### ISSUE TITLE
ohionowcast.info: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18491]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ohionowcast.info/blog/bitcoin-wealth-is-transferring-from-old-to-new-hands-why-this-is-positive`

### Category

detection

### Description

detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/75168867/eddc087e-6bdb-4c70-80e1-008fc4c1b6df)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.17h.53m
Chromium: 114
filterset (summary):
 network: 92940
 cosmetic: 39302
 scriptlet: 17666
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3006-3006, never
  easylist: 67181-49, 55m
  easyprivacy: 30860-59, 55m
  plowe-0: 3734-943, 55m
  ublock-abuse: 70-0, 55m
  ublock-badware: 7353-132, 55m
  ublock-filters: 33575-112, 55m
  ublock-privacy: 396-72, 55m
  ublock-quick-fixes: 238-11, 55m
  ublock-unbreak: 2042-34, 55m
  urlhaus-1: 6023-0, 55m
filterset (user): [array of 1655 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9279 ms (selfie)
 maxAssetCacheWait: 769 ms
popupPanel:
 blocked: 3
 network:
  cryptocoinsad.com: 1
  googlesyndication.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/18490#issuecomment-1588475479
