### ISSUE TITLE
uBlock "bypassed" by Uponit blank iframes

### ISSUE THREAD

**Issue by GlassGruber** [uBlockOrigin/uAssets#185]
### URL(s) where the issue occurs

[datpiff.com](http://datpiff.com)
[datpiff.com/Ace-Hood-Body-Bag-4-mixtape.811082.html](http://www.datpiff.com/Ace-Hood-Body-Bag-4-mixtape.811082.html)

### Describe the issue

Stumbling upon [this page](http://www.datpiff.com/Ace-Hood-Body-Bag-4-mixtape.811082.html) I was baffled by the amount of ads present in the page and that for the very first time uBO "failed" me. At first I thought that maybe I had some outdated list or something like that, but tinkering a bit with the page source code (but I say I'm no expert in this stuff) confirmed that simply put uBO was completely blind and not recognizing the ads on the page. A bit more details in the notes.

### Versions

- Browser/version: Google Chrome  54.0.2840.87 m & Firefox 49.0.2
- uBlock Origin version: 1.9.16

### Settings

In chrome I've implemented the advancedd user check, and added all lists from ads, privacy, malware and social categories, but basically its a beefed easy mode.

In firefox the above is done + medium mode block (all 3rd party scripts and frames) + remote fonts block

### Notes

The page source present an inline script around line `:89` with some heavy obfuscation that inserts `<iframe>` elements with a `src="about:blank"`. Luckily, this create a nice target for a filter rule like `##iframe[src="about:blank"]`, and I'm wondering if this can be safely applied for a global rule too. 

A quick google search for the comment annotation `<!-- uponit -->` points to this site https://uponit.com/

I'm quite curious how an iframe with `src="about:blank"` can even work in the first place! This looks quite interesting in respect of the current common "AdBlock Alert" mechanism telling to remove adblock addons to see the content (by the way are there any docs/wiki to counter this anti-block standard procedure? In particular the anti AB redirect to a page/manifest asking to remove the extension). 

I take this chance also to thank you for all the work on this amazing project! Cheers!  😄

**Comment by gorhill** [comment]
`datpiff.com##script:inject(abort-on-property-write.js, upManager)` works, but the syntax for that filter is supported only on uBO 1.9.17b7+.

**Comment by GlassGruber** [comment]
Oh that's nice! Is there any practical difference compared to `##iframe[src="about:blank"]`? 
I'm asking so that I know if it's better to wait for the stable release of 1.9.17 or just get the beta already and go with it!
Thank you!

**Comment by gorhill** [comment]
It prevents the javascript code behind these ads from running at all -- such that those `iframe[src="about:blank"]` are not even created in the 1st place.

**Comment by gorhill** [comment]
However, spending more time on investigating, this also seems to work:

    ||forkitz.com^
