### ISSUE TITLE
pinterest.com: ads

### ISSUE THREAD

**Issue by bagginshieldandphan** [uBlockOrigin/uAssets#18505]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [ ] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.com/`

### Category

ads

### Description

ads are being shown on my pinterest feed. before they were just blank spaces but now the ads are there. 
<img width="1431" alt="Screenshot 2023-06-13 at 7 47 08 PM" src="https://github.com/uBlockOrigin/uAssets/assets/136533905/256ece9e-ccd4-43ad-a1a0-3d90aec90ce3">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.12m
Firefox: 114
filterset (summary):
 network: 92944
 cosmetic: 39279
 scriptlet: 17660
 html: 940
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34449-50, now
  ublock-badware: 7357-0, now
  ublock-privacy: 439-0, now
  ublock-abuse: 70-70, now
  ublock-unbreak: 2064-0, now
  ublock-quick-fixes: 253-0, 1h.16m
  easylist: 66608-692, now
  easyprivacy: 30866-610, now
  urlhaus-1: 6560-0, 1h.16m
  plowe-0: 3735-2, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 81 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
```yaml
popupPanel:
 blocked: 0
```

Hmmm... The configuration looks normal but there's nothing blocked.

**Comment by dportvine** [comment]
I have white space with this filter  `pinterest.*##body:style(overflow-y: scroll !important;)` ~> **[uBlock filters – Annoyances](chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=ublock-annoyances)**

<details>
<summary>Screen</summary>

![2023-06-15_084446](https://github.com/uBlockOrigin/uAssets/assets/111344219/f0c3b30b-763b-4b94-84fc-5a3ed54518f8)
![2023-06-15_084554](https://github.com/uBlockOrigin/uAssets/assets/111344219/2f94eed7-eb86-402e-8a9c-893aca882a4f)
</details>

**Comment by krystian3w** [comment]
Normal for not logged in users, scroll action works in JS.

You should analysis DOM tree vs logged user and specific viewed tag/category/search result as guest.
