### ISSUE TITLE
20min.ch: breakage

### ISSUE THREAD

**Issue by Fixu69** [uBlockOrigin/uAssets#18500]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.20min.ch/video/mehrere-notrufe-baer-rennt-mitten-durch-die-stadt-841049721039`

### Category

breakage

### Description

videos does not play unless ublock is disabled at www.20min.ch

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 3h.32m
Firefox: 114
filterset (summary):
 network: 95231
 cosmetic: 43848
 scriptlet: 17654
 html: 940
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 34441-64, now
  ublock-badware: 7356-0, now
  ublock-privacy: 439-0, now
  ublock-unbreak: 2065-0, now
  easylist: 66596-699, now
  easyprivacy: 30866-619, now
  plowe-0: 3735-2, now
  DEU-0: 6902-3, now
  urlhaus-1: 6560-0, now
  ublock-quick-fixes: 251-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 309 redacted]
 removed:
  about-scheme
  edge-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1130 ms (selfie)
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 16
 network:
  20min.ch: 2
  cpstatic.ch: 2
  da-services.ch: 3
  doubleclick.net: 3
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  tda.link: 3
  visualwebsiteoptimizer.com: 1
 extended:
  ##+js(abort-on-property-read, _sp_._networkListenerData)
```
</details>

**Comment by mapx-** [comment]
add

`@@||tdn.da-services.ch/current/20min_durable.js$script,domain=20min.ch`

@khrin
