### ISSUE TITLE
connatix.com: privacy

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18502]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I found possible trackers loaded when you visit the site directly. Not sure if these should be added or if `connatix.com` should be blocked even when visiting it directly.
`||connatix.com/scripts/facebook-pixel-script.js`
`||connatix.com/scripts/gaconnector.js`
`||connatix.com/scripts/microsoft-ad-script.js`
`||connatix.com/scripts/munchkin-script.js`
`||connatix.com/scripts/hotjar.js`

### URL(s) where the issue occurs.

`https://connatix.com`

### uBO version

v1.49.3rc16

### Browser name and version

Firefox 114.0.1

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by iam-py-test** [comment]
This should be reported to EasyPrivacy: https://github.com/easylist/easylist/issues/new

**Comment by Sonic5435325** [comment]
@iam-py-test uBlock Unbreak has `||connatix.com^$badfilter` and `||connatix.com^$3p` to make it viewable when you directly view the page, so I'm reporting it here.

**Comment by Sonic5435325** [comment]
But for the tracker part, I decided to also make an EasyPrivacy report like you suggested: https://github.com/easylist/easylist/issues/16298
