### ISSUE TITLE
mcrypto.club: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18514]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mcrypto.club/women-arrested-for-scamming-rs-7-8-lakh-for-crypto-investment/`

### Category

detection

### Description

Ads blocked. but next step buttons not working..

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/75168867/5aa28116-5ca9-4eef-a962-ca07c5700234)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 6d.19h.4m
Chromium: 114
filterset (summary):
 network: 93868
 cosmetic: 39168
 scriptlet: 17695
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3008-1, never
  easylist: 66453-60, 26m
  easyprivacy: 30867-59, 26m
  plowe-0: 3735-948, 25m
  ublock-badware: 7372-133, 25m
  ublock-filters: 33630-3121, 25m
  ublock-privacy: 396-2, 25m
  ublock-quick-fixes: 265-18, 1h.18m
  ublock-unbreak: 2046-35, 25m
  urlhaus-1: 7488-0, 25m
filterset (user): [array of 1657 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 15959 ms (selfie)
 maxAssetCacheWait: 1871 ms
popupPanel:
 blocked: 15
 network:
  adschill.com: 1
  bmcdn5.com: 1
  chpadblock.com: 2
  doubleclick.net: 1
  flyersquare.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  mndsrv.com: 1
  pixfuture.com: 3
  quantcast.com: 1
  quantserve.com: 1
 extended:
  ##table
  ##.safelink-recatpcha:upward(div):style(display: block !importan…
  ###wpsafe-generate, #wpsafe-link:style(display: block !important…
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
  ##+js(abort-on-stack-trace, Object, /(?=^(?!.*(https)))/)
  ##+js(nano-setTimeout-booster, countdown, 10000)
  ##+js(no-xhr-if, wpadmngr)
  ##+js(no-fetch-if, ad)
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/17361
