### ISSUE TITLE
doroni.me: detection

### ISSUE THREAD

**Issue by FLAV1N** [uBlockOrigin/uAssets#18518]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://doroni.me/anime/aktivitas-dewa-di-dunia-tanpa-dewa/episode-10`

### Category

detection

### Description

Hello,

I would like to report an issue I encountered with the uBlock Origin plugin. for the past few months, I found that this website using a clever trick to hide the "download links" elements by putting an ads in between. My current solution to this is to disable cosmetic filtering in the settings, but the drawbacks are there's an unloaded image icon.

Steps to reproduce the issue:

1. Open the `https://doroni.me/anime/aktivitas-dewa-di-dunia-tanpa-dewa/episode-10` website.
2. Observe that the download elements are missing.
3. Disabling Cosmetic filtering.
4. Observe that the download elements are there.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Before disabling cosmetic filtering
![image](https://github.com/uBlockOrigin/uAssets/assets/122433506/a5f22f65-6941-45fa-8a83-7de6fdbe5530)
After
![image](https://github.com/uBlockOrigin/uAssets/assets/122433506/2bd3d865-0641-451b-b99a-814660e1ecb4)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.9h.51m
Chromium: 114
filterset (summary):
 network: 117265
 cosmetic: 85219
 scriptlet: 32033
 html: 0
listset (total-discarded, last-updated):
 added:
  IDN-0: 9510-2, now
  adguard-generic: 71681-500, now
  adguard-mobile: 8278-49, now
 default:
  user-filters: 11-1, never
  easylist: 66453-904, 5m
  easyprivacy: 30872-170, now
  plowe-0: 3735-1038, now
  ublock-abuse: 70-0, now
  ublock-badware: 7372-363, now
  ublock-filters: 33626-3758, now
  ublock-privacy: 396-72, now
  ublock-quick-fixes: 259-14, 4m
  ublock-unbreak: 2046-91, now
  urlhaus-1: 7488-0, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 464 ms (selfie)
 maxAssetCacheWait: 206 ms
popupPanel:
 blocked: 12
 network:
  arc.io: 1
  disqus.com: 2
  facebook.com: 1
  google-analytics.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  sentry-cdn.com: 1
  taboola.com: 1
  viglink.com: 2
 extended:
  ##a[href^="https://m.do.co/c/"] > img
  ##ins.adsbygoogle
  ##.ad-box
  ###placement-top
```
</details>

**Comment by JobcenterTycoon** [comment]
@gmarcher there are also ads on this site, a filter could be `||doroni.me/images/promo/`

**Comment by mapx-** [comment]
add

`@@||doroni.me^$ghide`

**Comment by JobcenterTycoon** [comment]
```
@@||doroni.me^$ghide
doroni.me##ins.adsbygoogle
```

**Comment by mapx-** [comment]
however these ads are self-promotion (their discord channel)

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/1661c4af-dcfc-42fd-a218-b3d9e079310f)

**Comment by FLAV1N** [comment]
I have tested the steps that previously caused the issue, and I'm happy to report that everything is functioning correctly. The problem seems to be fixed. Thank you so much.

**Comment by partingscientist** [comment]
Some of these can be removed perhaps after https://github.com/ABPindo/indonesianadblockrules/pull/428?

https://github.com/uBlockOrigin/uAssets/blob/254b9dbc84f758f93ec4ef91de8ad84fbd9f583d/filters/filters-2023.txt#L3080-L3084
