### ISSUE TITLE
linkvertise.com: breakage

### ISSUE THREAD

**Issue by Livable8209** [uBlockOrigin/uAssets#18523]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/42709/DownloadElectron/1`

### Category

breakage

### Description

Site makes the user do a captcha infinitely, tested with default settings and a clean profile in Firefox. Solving a captcha causes the console to spit out an error, screenshot provided.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_xRP2EUAFlI](https://github.com/uBlockOrigin/uAssets/assets/136758278/b7d64f1f-77eb-4838-b37f-88719c6c6185)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1m
Firefox: 114
filterset (summary):
 network: 94264
 cosmetic: 39165
 scriptlet: 17668
 html: 943
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34473-156, now
  ublock-badware: 7460-1, now
  ublock-privacy: 436-0, now
  ublock-unbreak: 2063-0, now
  ublock-quick-fixes: 280-0, now
  easylist: 66538-581, now
  easyprivacy: 30889-658, now
  urlhaus-1: 7714-0, now
  plowe-0: 3738-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1514 ms
 maxAssetCacheWait: 9 ms
popupPanel:
 blocked: 10
 network:
  bizseasky.com: 2
  googletagmanager.com: 1
  media.net: 2
  sentry.io: 1
  taboola.com: 1
  thinksuggest.org: 2
  typekit.net: 1
 extended:
  ##+js(abort-current-script, addEventListener, DOMNodeRemoved)
  ##+js(abort-current-script, document.dispatchEvent, CustomEvent)
  ##+js(abort-current-script, onload, adsbygoogle)
  ##+js(addEventListener-defuser, load, nextFunction)
  ##+js(json-prune, data.meta.require_addon data.meta.require_capt…
  ##+js(nano-setInterval-booster)
  ##+js(set-constant, isAdBlockActive, false)
```
</details>

**Comment by gorhill** [comment]
Need:

    @@||bizseasky.com^$3p,script,domain=linkvertise.com

To counter `||bizseasky.com^$3p` from EasyPrivacy.

cc @ryanbr
