### ISSUE TITLE
sport24.gr a couple of ad boxes

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#18529]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

a couple of ad boxes on sport24.gr

### URL(s) where the issue occurs.

`https://www.sport24.gr/media/pethane-o-gios-toy-athlitikografoy-giorgoy-georgioy.8502287.html`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/24896778/4ecf681f-3d97-4acf-8bb5-9329ea3570e0
https://github.com/uBlockOrigin/uAssets/assets/24896778/d5d46aa7-2351-4860-a5ff-77fe5775eaf9

### uBO version

1.50

### Browser name and version

cent browser Version 5.0.1002.295 (Official Build) (64-bit) (Portable) (Chromium 102.0.5005.167)

### Settings

n/a

**Comment by mapx-** [comment]
add

```
sport24.gr##.premium_banner
sport24.gr##[id^="ros"]
```

and report here (to be added to regional list)
https://github.com/kargig/greek-adblockplus-filter/issues

**Comment by patrickdrd** [comment]
I don't think Greek regional is maintained anymore, a lot of open issues since ages, I added the filter in my list anyway, thanks

**Comment by kargig** [comment]
Always feel free to send a pull request in https://github.com/kargig/greek-adblockplus-filter/pulls :)
