### ISSUE TITLE
independent.co.uk: nuisance

### ISSUE THREAD

**Issue by g-k-m** [uBlockOrigin/uAssets#18521]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.independent.co.uk/`

### Category

nuisance

### Description

cookie notice still showing up even tho i have easylist cookie notices and adguard cookie notices filter lists enabled

### Other extensions used

localcdn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.22h.16m
Chromium: 114
filterset (summary):
 network: 259080
 cosmetic: 138115
 scriptlet: 34783
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances-cookies.txt: 4-0, 7m
  BGR-0: 1091-11, 7m
  adguard-cookies: 25916-30, now
  adguard-generic: 71693-457, 7m
  adguard-spyware: 44830-1031, 7m
  adguard-spyware-url: 1086-3, 7m
  block-lan: 47-0, 7m
  curben-phishing: 101799-7, 7m
  dpollock-0: 11522-200, 7m
  fanboy-cookiemonster: 47450-3717, 7m
  fanboy-thirdparty_social: 68-0, 7m
 default:
  user-filters: 84-0, never
  easylist: 66538-1167, 7m
  easyprivacy: 30890-13521, 7m
  plowe-0: 3738-1399, 7m
  ublock-badware: 7458-396, 7m
  ublock-filters: 33598-3789, 7m
  ublock-privacy: 396-64, 7m
  ublock-quick-fixes: 282-21, 7m
  ublock-unbreak: 2046-136, 7m
  urlhaus-1: 7714-2, 7m
filterset (user): [array of 84 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 21 redacted]
urlRuleset:
 added: [array of 25 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4353 ms
 maxAssetCacheWait: 931 ms
popupPanel:
 blocked: 3
 network:
  doubleclick.net: 1
  ml314.com: 1
  tinypass.com: 1
 extended:
  ###stickyFooterRoot
  ###top-banner-wrapper
  ##+js(set-constant, google_tag_manager.dataLayer.gtmDom, true)
  ##+js(no-fetch-if, doubleclick)
```
</details>

**Comment by okiehsch** [comment]
> cookie notice still showing up even tho i have easylist cookie notices and adguard cookie notices filter lists enabled

Opena an issue about it at https://github.com/AdguardTeam/AdguardFilters or https://github.com/easylist/easylist

**Comment by mapx-** [comment]
I added a filter to unbreak the videos, however without interacting with the cookie dialogue the videos are broken
https://github.com/uBlockOrigin/uAssets/commit/05a2a700d239c03e117b70e3e55e20125eca366a

maybe using the new set-cookie scriptlet we'll be able to find a fix

**Comment by okiehsch** [comment]
With your filter it's only broken if you block the modal, and the modal is not blocked in EasyList Cookies or AdguardAnnoyances or am I missing somethng?

**Comment by mapx-** [comment]
yes, I wanna say AG / EL cannot fix the "issue" in their lists

same thing for the spanish one
`https://www.independentespanol.com/noticias/cocodrilo-virgen-costa-rica-inmaculada-concepcion-b2358537.html`

**Comment by okiehsch** [comment]
> yes, I wanna say AG / EL cannot fix the "issue" in their lists

Ok, I agree blocking the modal in EasylistCookies is not possible without breaking the videos on the site.

> We'd need AG trusted scriptlet in uBO too (which is able to set whatever value for the cookies)

Well, we don't fix GDPR modals, so...
Not saying that having the possibility to set cookies could not be helpful in other cases.

**Comment by ghost** [comment]
Can this one be hidden or falls under self-promotion?
![Image](https://github.com/user-attachments/assets/957cdb4e-1f47-47df-9006-b7d08e49bdf6)

**Comment by stephenhawk8054** [comment]
We don't fix newsletter annoyances issues. Try `EasyList – Newsletter Notices` or `AdGuard – Popup Overlays` lists. If it's not fixed yet, report to EasyList or Adguard:

- https://github.com/easylist/easylist/issues
- https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by ghost** [comment]
The first filter fixed it.
