### ISSUE TITLE
together.com: breakage

### ISSUE THREAD

**Issue by glimpse23** [uBlockOrigin/uAssets#18527]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

We have noticed that our brand Together.com has been put into "uBlock filters – Badware risks" - `||together.com^$doc`. However, we were not able to find any pages containing any badware on it.

We would like to request you to provide us with any instructions on how to remove our brand from this uBlock filter.
We provide legitimate services to our clients, therefore, we consider those bans irrelevant and unnecessary.

Best Regards,
Together.com Support Team

### URL(s) where the issue occurs.

`https://www.together.com/`

### uBO version

1.50.0

### Browser name and version

Google Chrome 114.0.5735.110

### Settings

No changes were made to default settings

**Comment by okiehsch** [comment]
Added with  https://github.com/uBlockOrigin/uAssets/commit/0c8341492cf6417ba19299a707b0fbea7afa36e1

@Yuki2718

**Comment by okiehsch** [comment]
@glimpse23 looking thorugh your PrivacyPolicy you forgot to answer the rather important point 
"WHO WE ARE" 
According to your privacy policy you are: General company  Office 1 and reside in "general country", now I never heard of that country,
Thankfully under point 13 you provided a telephone number: 1(800)961-9835
That number belongs to MatureDating https://www.trustpilot.com/review/maturedating.com

That could be the reason for the filter.

**Comment by glimpse23** [comment]
Thank you for your response. We will try our best to change the missing points according to your comments.

**Comment by mapx-** [comment]
The Trustpilot reviews are quite clear: the site is not trustworthy at all.

**Comment by Yuki2718** [comment]
Was based on this review: `https://sakuradot.com/article/70720.html`. The name "Badware" may be misleadidng, we block all sorts of dubious sites. As with the past similar cases, I limited to `$doc` which means user will be prompted when they visit the site, the same manner we prompt for tracking links, but can proceed if he is sure he want to visit. In contrast, for malware or such staff we use `$all` so that the site will be unavailable even if user proceeded.
