### ISSUE TITLE
mcrypto.club: detection

### ISSUE THREAD

**Issue by monkeyde98** [uBlockOrigin/uAssets#18525]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

~~`https://mcrypto.club/israel-confiscated-binance-accounts-to-thwart-isis-document-reveals/`~~ `https://myhealths.icu/5SWh3`

### Category

detection

### Description

this site opens this code
<div id="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmtupntmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt" class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmtupntmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmwruymmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"><div class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmouuxpuxmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmqnppbuskfjhsjkdfhuyummskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmxuppqruppmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt" id="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmouuxpuxmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"><div class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmoupzmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt" id="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmoupzmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"><div class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmxrptpmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmxrptpVmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"><div class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmoupzmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"><div class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmtnrumouuxpuxmywnvvpwmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"> <div class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmywnvvpwmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"> <img class="img skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmrouummskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt" src="https://chpadblock.com/wp-content/uploads/2022/08/icon-1.png" alt="CHP Adblock Icon" n6txht32g=""> </div> <div class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmtnrumouuxpuxmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"> <h4 class="adblock_title">Ads Blocker Detected!!!</h4> <div class="adblock_subtitle"><p>We have detected that you are using extensions to block ads. Please support us by disabling these ads blocker.</p></div> </div> </div><div class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmnoxruummskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt"><a class="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmnoxruuToxuTusmmskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt" id="skfjhsjkdfhiqcuskfjhsjkdfhepiwwacxtmmwptunpoxummskfjhsjkdfhiqcuskfjhsjkdfhepiwwacxt">I've disable Adblock</a></div></div></div></div></div></div>

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.22h.35m
Chromium: 114
filterset (summary):
 network: 95764
 cosmetic: 42757
 scriptlet: 18370
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 887-143, never
  easylist: 66510-50, 1d.13h.21m
  easyprivacy: 30867-59, 1d.13h.21m
  plowe-0: 3735-948, 1d.13h.21m
  spa-1: 5276-69, 1d.13h.21m
  ublock-badware: 7355-133, 1d.13h.21m
  ublock-filters: 33590-154, 1d.13h.21m
  ublock-privacy: 399-2, 1d.13h.21m
  ublock-quick-fixes: 277-16, 20m
  ublock-unbreak: 2044-35, 1d.13h.21m
  urlhaus-1: 7714-0, 13h
filterset (user): [array of 935 redacted]
trustedset:
 added: [array of 33 redacted]
hostRuleset:
 added: [array of 12 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1790 ms
 maxAssetCacheWait: 204 ms
popupPanel:
 blocked: 27
 network:
  adschill.com: 2
  bmcdn5.com: 1
  chpadblock.com: 2
  doubleclick.net: 2
  flyersquare.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 2
  mndsrv.com: 2
  orquideassp.com: 10
  quantserve.com: 2
 extended:
  ##table
  ##.safelink-recatpcha:upward(div):style(display: block !importan…
  ###wpsafe-generate, #wpsafe-link:style(display: block !important…
  ##div[style="display: none;"]:style(display: block !important;)
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  ##+js(abort-on-stack-trace, Object, /(?=^(?!.*(https)))/)
  ##+js(nano-setTimeout-booster, countdown, 10000)
  ##+js(no-xhr-if, wpadmngr)
  ##+js(no-fetch-if, ad)
```
</details>

**Comment by gorhill** [comment]
> - [x] I forced an update of my filter lists.

You did not:

> `1d.13h.21m`

This casts doubts that you also properly answered the other points.

**Comment by monkeyde98** [comment]
I'll try to find the original link!

**Comment by monkeyde98** [comment]
here https://myhealths.icu/5SWh3
