### ISSUE TITLE
burbuja.info: detection

### ISSUE THREAD

**Issue by flst32** [uBlockOrigin/uAssets#18534]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.burbuja.info/inmobiliaria/forums/`

### Category

detection

### Description

Until now uBlock Origin was able to cancel all the pop ups, banners and ads from this Spanish Internet forum `www.burbuja.info`

But since yesterday this has changed, from time to time it appears the attached banner where it appears a message in Spanish that says "We have removed a lot of the ads and now doesn't disturbs, please deactivate your block ads app".

Which is also not true of course, can you please check if you can fix it? Thanks in advance.
Joan

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![imagen](https://github.com/uBlockOrigin/uAssets/assets/136828284/fa8d8ec3-20c0-4844-a89d-8a009267ae28)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.7h.23m
Firefox: 114
filterset (summary):
 network: 95768
 cosmetic: 44989
 scriptlet: 17928
 html: 945
listset (total-discarded, last-updated):
 default:
  user-filters: 29-2, never
  ublock-filters: 34408-83, now
  ublock-badware: 7470-1, now
  ublock-privacy: 436-0, now
  ublock-abuse: 70-70, now
  ublock-unbreak: 2066-0, now
  ublock-quick-fixes: 283-0, now
  easylist: 66602-782, now
  easyprivacy: 30895-625, now
  urlhaus-1: 6551-1, now
  plowe-0: 3736-1, now
  spa-0: 3684-1, now
  spa-1: 5280-157, now
filterset (user): [array of 29 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5229 ms (selfie)
 maxAssetCacheWait: 1523 ms
popupPanel:
 blocked: 8
 network:
  burbuja.info: 3
  googlesyndication.com: 1
  googletagmanager.com: 1
  s3wfg.com: 1
  scorecardresearch.com: 1
  sunmedia.tv: 1
 extended:
  ##.fa-2x
  ##p:nth-of-type(1)
  ##+js(abort-on-property-read, adBlockDetected)
```
</details>

**Comment by Kaktus5511** [comment]
Hello, 

You should read through your upper "prerequisites" and think again if it really corresponds to what you have clicked on. 

I have tested the website and it works fine with uBlock only activated and brave shield disabled. 

Do you happen to use the "Brave - Browser" if so disable the "Brave - Shield" and report this to the "Brave - DevTeam".
