### ISSUE TITLE
[NSFW] xcitypass.com: ads

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18539]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I don't really know if this fits EasyList's rules so I'm gonna report it here.
Some ad domains which load:
`isbnrs.com`
`lksbnrs.com`

### URL(s) where the issue occurs.

`http://www.xcitypass.com/`

### Screenshot(s)

![Screenshot from 2023-06-16 17-22-16](https://github.com/uBlockOrigin/uAssets/assets/89158249/6d2a29d7-def1-4dda-bf26-6a7a924e258d)

Without cosmetic filtering, you can see these:
`https://files.catbox.moe/6nfqo8.png`
`https://files.catbox.moe/osyznk.png`

### uBO version

v1.50.1b0

### Browser name and version

Firefox 114.0.1

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by mapx-** [comment]
yes, to be reported at easylist repo

@ryanbr
