### ISSUE TITLE
allcryptoz.net: detection

### ISSUE THREAD

**Issue by monkeyde98** [uBlockOrigin/uAssets#18536]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://allcryptoz.net/adblock.html`

### Category

detection

### Description

this one and the real link `https://t.co/W5QcbwMmbp`

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 8d.14h.54m
Chromium: 114
filterset (summary):
 network: 94845
 cosmetic: 42744
 scriptlet: 18367
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/a88198374e001ac2872e556f7a774535ab15c31c/filters/filters-2022.txt: 4533-8, 13h.17m
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/d51664014f668ecac8b461fb7d5f95fd90afea3e/filters/filters-2023.txt: 3011-10, 13h.17m
 default:
  user-filters: 865-143, never
  easylist: 66538-106, 13h.17m
  easyprivacy: 30889-62, 13h.17m
  plowe-0: 3738-951, 13h.17m
  spa-1: 5278-73, 13h.17m
  ublock-badware: 7458-135, 13h.17m
  ublock-filters: 33600-7644, 13h.17m
  ublock-privacy: 396-2, 13h.17m
  ublock-quick-fixes: 283-19, 14m
  ublock-unbreak: 2047-35, 13h.17m
  urlhaus-1: 6663-1, 13h.17m
filterset (user): [array of 913 redacted]
trustedset:
 added: [array of 31 redacted]
hostRuleset:
 added: [array of 12 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1102 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(set-constant, blurred, false)
  ##+js(abort-current-script, document.getElementById, /\$\('body'…
  ##+js(abort-current-script, addEventListener, document.getElemen…
  ##+js(abort-current-script, eval, replace)
  ##+js(abort-current-script, onload, jQuery)
  ##+js(abort-on-property-read, alert)
  ##+js(no-fetch-if, wpadmngr)
  ##+js(no-setTimeout-if, redURL)
  ##+js(no-setInterval-if, console)
```
</details>

**Comment by stephenhawk8054** [comment]
Is it a shortener link? If yes, please don't open new issues about these, we have a discussion section for it: https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by monkeyde98** [comment]
yes is it a shortener link.

**Comment by monkeyde98** [comment]
Sorry I didn't know about the section
