### ISSUE TITLE
anonfiles.com: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#18537]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://anonfiles.com/`

### Category

ads

### Description

Reporting unwanted crypto ad on the site. Requesting uBO intervention to remove it promptly.

### Other extensions used

No other adBlocker.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Full page of anonfiles.com with the crypto ad](https://github.com/uBlockOrigin/uAssets/assets/50150516/a3949f38-1205-4179-bda5-239b6191ac74)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 8d.21h.29m
Chromium: 114
filterset (summary):
 network: 93176
 cosmetic: 39166
 scriptlet: 17632
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 66607-50, now
  easyprivacy: 30895-62, now
  plowe-0: 3736-951, now
  ublock-badware: 7478-135, now
  ublock-filters: 33527-141, now
  ublock-privacy: 396-2, now
  ublock-quick-fixes: 283-19, now
  ublock-unbreak: 2048-34, now
  urlhaus-1: 6551-1, now
filterset (user): [empty]
trustedset:
 added: [array of 36 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 442 ms (selfie)
 maxAssetCacheWait: 83 ms
popupPanel:
 blocked: 4
 network:
  anonfiles.com: 2
  djv99sxoqpv11.cloudfront.net: 1
  google-analytics.com: 1
```
</details>

**Comment by okiehsch** [comment]
I don't see any ads even if I disable uBO.

**Comment by LightAndy1** [comment]
Sorry, I meant the amazon thing. I thought it was some crypto stuff.. It's in the middle of the page

**Comment by okiehsch** [comment]
Ok, that's not visible on the homepage, so a download link is needed to reproduce.
`https://anonfiles.com/ccc9lcwbza`
for eample.

`anonfiles.com##[href^="https://www.encrouter.com/"]`
fixes the issue.
@ryanbr

**Comment by LightAndy1** [comment]
Yes, sorry. Here is a download link: `https://anonfiles.com/U3R4O8v5z9`. I hope you can fix it 😀

**Comment by stephenhawk8054** [comment]
@ryanbr
