### ISSUE TITLE
fr.motorsport.com: detection

### ISSUE THREAD

**Issue by WindBurst** [uBlockOrigin/uAssets#18543]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fr.motorsport.com/f1/news/williams-fascination-intimidant-plancher-red-bull/10482933/`

### Category

detection

### Description

The site detect that I have a publicity adblock

### Other extensions used

I use the original Ublock with default setting

### Screenshot(s)

![Capture](https://github.com/uBlockOrigin/uAssets/assets/120932966/cb8bda1b-59d9-4fdc-b49e-b55a76dd1269)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 8d.23h.13m
Chromium: 114
filterset (summary):
 network: 111583
 cosmetic: 48058
 scriptlet: 17656
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 8-0, never
  FRA-0: 28291-33, 23h.59m
  easylist: 66510-168, 1d.23h.1m
  easyprivacy: 30861-339, 4d.13h.43m
  plowe-0: 3735-970, 1d.22h.58m
  ublock-badware: 7257-149, 4d.22h.15m
  ublock-filters: 33458-198, 4d.22h.14m
  ublock-privacy: 396-3, 11h.44m
  ublock-quick-fixes: 201-7, 11m
  ublock-unbreak: 2034-38, 4d.22h.13m
  urlhaus-1: 6663-0, 22h.57m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 49 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 828 ms (selfie)
 maxAssetCacheWait: 210 ms
popupPanel:
 blocked: 17
 network:
  motorsport.com: 5
  adgrid.io: 1
  dailymotion.com: 2
  dm-event.net: 5
  id5-sync.com: 1
  imasdk.googleapis.com: 2
  ntv.io: 1
 extended:
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
```
</details>

**Comment by WindBurst** [comment]
It's available for all the pages in the site

**Comment by stephenhawk8054** [comment]
I can't see the anti-adb.

```yaml
extended:
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
```

There should be more scriptlets injection in this site. Here's how mine looks like:

```yaml
extended:
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
  ##+js(addEventListener-defuser, gtmloaderror)
  ##+js(noeval-if, interactionCount)
  ##+js(abort-current-script, vardom)
```

Can you force update all your filter lists and test again?

**Comment by WindBurst** [comment]
Hello,

I forced the update and it works.

Thank you for your help and sorry for the disagreement.

See you soon

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WindBurst** [comment]
Thank you for your help

**Comment by WindBurst** [comment]
Hello.

OK.

Sorry.

Thank you for your help.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
