### ISSUE TITLE
tapatalk.com: ads

### ISSUE THREAD

**Issue by Emalcat** [uBlockOrigin/uAssets#18545]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Apparently Taptalk manages to put ads at the bottom of the page in a section called "Around the Internet"
Any topic works

### URL(s) where the issue occurs.

`https://www.tapatalk.com/groups/thetreadmill/the-chicken-and-the-egg-which-came-first-solved-t34908.html`

`https://kerrydalestreet.co.uk/summer-transfer-window-2023-non-celtic-t140629.html`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/88663610/c7372049-b25b-433f-ade8-2ff04ea73d52

### uBO version

uBlock Origin 1.50.0

### Browser name and version

vivaldi 6.1.3035.84

### Settings

It's a vanilla install

**Comment by mapx-** [comment]
add

`tapatalk.com###relatedblogbar`

@ryanbr
