### ISSUE TITLE
[nsfw] hubaidigitalsoft.com: badware

### ISSUE THREAD

**Issue by BadBoy1190** [uBlockOrigin/uAssets#18548]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hubaidigitalsoft.com/Internet_Download_Manager_%28IDM%29_v6.41_Build_11___Fix.zip?c=AF7gjWQmRAUAWlsCAFNBFwASAG3rLqEA`

### Category

[unknown]

### Description

its has malware Ahui 

### Other extensions used

i dont use any of these things 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.3h.54m
Chromium: 114
filterset (summary):
 network: 93161
 cosmetic: 39180
 scriptlet: 17647
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 66657-50, now
  easyprivacy: 30798-62, now
  plowe-0: 3736-952, now
  ublock-badware: 7494-135, now
  ublock-filters: 33535-142, now
  ublock-privacy: 407-2, now
  ublock-quick-fixes: 287-19, now
  ublock-unbreak: 2048-34, now
  urlhaus-1: 6574-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 671 ms (selfie)
 maxAssetCacheWait: 149 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
How did you land on that page ?

**Comment by iam-py-test** [comment]
I get not found, so I assume this requires a specific IP address/referer.
Where did you find this? Please share the original link
