### ISSUE TITLE
viprow.nu: popups

### ISSUE THREAD

**Issue by usernamaewa** [uBlockOrigin/uAssets#18546]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.viprow.nu/motogp-germany-gp-motogp-qualifying-1-online-stream-1`

### Category

popups

### Description

It sometimes opens unwanted tabs

### Other extensions used

_none_

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b1
Firefox: 116
filterset (summary):
 network: 353776
 cosmetic: 344290
 scriptlet: 45280
 html: 1206
listset (total-discarded, last-updated):
 added:
  adguard-generic: 71694-7292, 1d.19h.49m
  adguard-mobile: 8282-129, 1d.19h.49m
  adguard-spyware-url: 1073-5, 1d.19h.49m
  block-lan: 47-0, 5d.20h.14m
  curben-phishing: 102541-40, 21m
  curben-pup: 199-0, 21m
  adguard-social: 20540-827, 1d.19h.49m
  fanboy-thirdparty_social: 68-0, 5d.20h.13m
  fanboy-cookiemonster: 47417-3831, 5d.20h.13m
  fanboy-social: 16069-32, 5d.20h.12m
  ublock-annoyances: 5030-7, 5d.20h.12m
  dpollock-0: 11521-476, 5d.20h.12m
  [46 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 34477-664, 21m
  ublock-badware: 7347-0, 21m
  ublock-privacy: 436-0, 5d.20h.16m
  ublock-unbreak: 2066-1, 21m
  ublock-quick-fixes: 285-0, 20m
  easylist: 66971-1367, 5d.20h.14m
  easyprivacy: 30856-898, 5d.20h.14m
  urlhaus-1: 6598-0, 21m
  plowe-0: 3734-2, 5d.20h.12m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2444 ms
 maxAssetCacheWait: 1463 ms
popupPanel:
 blocked: 15
 network:
  addedfearinglestpe.com: 2
  chatango.com: 1
  dlem1deojpcg7.cloudfront.net: 1
  easkedasensibl.com: 2
  googletagmanager.com: 1
  hubty.network: 3
  pogothere.xyz: 4
  twinedabider.guru: 1
 extended:
  ##.position-absolute
  ##button[data-openuri="|BTN_URL|"]
  ##+js(abort-current-script, document.createElement, break;case $…
  ##+js(window.open-defuser, affelseaeinera.org)
  ##+js(set-constant, path, '')
  ##+js(abort-current-script, setTimeout, admc)
  ##+js(abort-on-property-write, _pop)
  ##+js(window.open-defuser, |)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-current-script, Promise, delete window)
  ##+js(set-constant, attachEvent, trueFunc)
  ##+js(no-setInterval-if, debug)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(window.open-defuser)
  ##+js(abort-current-script, JSON, break;case)
```
</details>

**Comment by mapx-** [comment]
> [46 lists not shown]: [too many]

**reset uBO to default**, keep only the default lists (do not add all the lists possible), **update then ALL the lists**, disable other blocking addons, test again

**Comment by usernamaewa** [comment]
Ubo as the only addons active on firefox, purge, reset to default, update, and restart firefox, delete cache cookies.
Same results, it opens new tabs, https://addedfearinglestpe.com/ZXdMVWQEFSEh
It only happens sometimes, when clicking the play button on the video player, https://www.viprow.nu/motogp-main-race-motogp-qualifying-online-stream-2

**Comment by mapx-** [comment]
test

```
viprow.*#@#+js(window.open-defuser, |)
viprow.*##+js(nowoif, //)
```

**Comment by usernamaewa** [comment]
Ok, it works now, I test more than 40 times, and now everything is back to normal. Thank you very much.
