### ISSUE TITLE
waka.com, abccolumbia.com: livestream broken

### ISSUE THREAD

**Issue by liamengland1** [uBlockOrigin/uAssets#18541]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

news livestream broken

### URL(s) where the issue occurs.

`https://www.waka.com/watch-live/`
`https://www.abccolumbia.com/watch-live/`

### Notes

suggested filter: `@@||doubleclick.net/ssai/*/streams$xhr,domain=snippet.univtec.com`

possibly geolocked

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 25m
Firefox: 114
filterset (summary):
 network: 93225
 cosmetic: 39167
 scriptlet: 17621
 html: 945
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 34404-55, 25m
  ublock-badware: 7480-1, 25m
  ublock-privacy: 436-0, 25m
  ublock-unbreak: 2067-0, 25m
  ublock-quick-fixes: 285-0, 25m
  easylist: 66607-729, 25m
  easyprivacy: 30895-610, 25m
  urlhaus-1: 6598-1, 25m
  plowe-0: 3736-1, 25m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5146 ms
 maxAssetCacheWait: 17 ms
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||pubads.g.doubleclick.net/ssai/event/*/streams$xhr,domain=snippet.univtec.com
```

@ryanbr
