### ISSUE TITLE
xasiat.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1854]
URL(s) where the issue occurs

`https://xasiat.com/tube/asian-takes-big-cock-interracial-fucking-cumshot/`

Describe the issue

ADS

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by mapx-** [comment]
add
`xasiat.com##.gofollow`

**Comment by kulfoon** [comment]
Ads again, on mainpage and  subpages like: `https://xasiat.com/tube/ekdv-537-big-brother-and-little-sister-play-a-forbidden-game/`.
