### ISSUE TITLE
ignboards.com: breakage

### ISSUE THREAD

**Issue by psychodinae** [uBlockOrigin/uAssets#18547]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ignboards.com/`

### Category

breakage

### Description

page is completely messed up

### Other extensions used

Offline Google Docs
metamask

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bug](https://github.com/uBlockOrigin/uAssets/assets/67171012/cd8b7203-d6d1-44e4-a595-bc82b18e62b0)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2m
Chromium: 114
filterset (summary):
 network: 94542
 cosmetic: 42651
 scriptlet: 18001
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 66617-50, 1m
  easyprivacy: 30798-62, 1m
  plowe-0: 3736-951, 1m
  spa-1: 5281-69, 2m
  ublock-badware: 7478-135, 1m
  ublock-filters: 33600-166, 1m
  ublock-privacy: 396-2, 1m
  ublock-quick-fixes: 285-19, 1m
  ublock-unbreak: 2048-35, 1m
  urlhaus-1: 6598-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1410 ms
 maxAssetCacheWait: 17 ms
popupPanel:
 blocked: 14
 network:
  chartbeat.com: 1
  doubleclick.net: 3
  googletagmanager.com: 2
  scorecardresearch.com: 1
  youtube.com: 4
  ziffstatic.com: 3
 extended:
  ###zdcFloatingBtn
  ###adchoicesBtn
  ##+js(abort-current-script, JSON.stringify)
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
I added 

`@@||ignboards.com^$ghide`

@ryanbr 

not all the cosmetic filters are reported in the logger
