### ISSUE TITLE
tv.lk21official.shop: popups

### ISSUE THREAD

**Issue by tetz88** [uBlockOrigin/uAssets#18557]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tv.lk21official.shop/`

### Category

popups

### Description

popup when click play button

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 8d.5h.43m
Chromium: 114
filterset (summary):
 network: 98071
 cosmetic: 45680
 scriptlet: 17746
 html: 0
listset (total-discarded, last-updated):
 added:
  IDN-0: 9510-2, 11h.49m
  VIE-1: 1954-0, 11h.49m
 default:
  user-filters: 67-1, never
  easylist: 66657-72, 11h.49m
  easyprivacy: 30798-66, 11h.49m
  plowe-0: 3735-952, 11h.49m
  ublock-badware: 7506-135, 11h.48m
  ublock-filters: 33539-168, 11h.48m
  ublock-privacy: 406-2, 11h.48m
  ublock-quick-fixes: 289-20, 11h.48m
  ublock-unbreak: 2048-35, 11h.48m
  urlhaus-1: 6593-1, 11h.48m
filterset (user): [array of 67 redacted]
trustedset:
 added: [array of 21 redacted]
switchRuleset:
 added: [array of 13 redacted]
hostRuleset:
 added: [array of 17 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 281 ms (selfie)
 maxAssetCacheWait: 110 ms
popupPanel:
 blocked: 8
 no-popups: true
 network:
  amung.us: 1
  googletagmanager.com: 1
  makimbo.xyz: 5
  scriptcdn.net: 1
 extended:
  ##.alert-dismissible.alert-success.alert
  ##.social-block
  ##.theiaStickySidebar > ul > li:nth-of-type(1)
```
</details>

**Comment by iam-py-test** [comment]
Seems to be restricted to Asian countries.
