### ISSUE TITLE
imagecolorpicker.com: popups, nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#18559]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Pop-up with locked scroll after page lost focus in JS.

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/ff71a9c1-1271-49be-a7cf-665e8fea33cd)

### URL(s) where the issue occurs.

`https://imagecolorpicker.com/`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/35370833/5272a71d-e2b7-46c9-8566-75a150da9984

### uBO version

1.50.0

### Browser name and version

Firefox 114.0.1

### Settings

- POL-0
- POL-2
- uBO Annoyances

**Comment by mapx-** [comment]
The scrolling is blocked on my end only when I delete directly the localStorage item `w3ride_leave_dialog`

```
imagecolorpicker.com###geist-ui-modal
imagecolorpicker.com##.ezoic-ad
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Ad? .ezoic-ad  or annoyance. If annoyance, what type of annoyance ? Self promo? etc.  I'm unable to reproduce.

**Comment by stephenhawk8054** [comment]
Looks like `.ezoic-ad` (and other placeholders) are caused by `ghide` in our annoyance list. Not sure if it's still needed.

**Comment by mapx-** [comment]
@ryanbr  did you delete from localStorage `w3ride_leave_dialog` ?

**Comment by mapx-** [comment]
replaced ghide filter https://github.com/uBlockOrigin/uAssets/commit/3d972d93ef87454a1a31f560344e1ad41445f153

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/8563fda0392d050dbe816b6c1ef97d79e04065b4
