### ISSUE TITLE
arenavision2018.tk [Pop-up] [Redirect]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1855]
URL(s) where the issue occurs

`http://arenavision2018.tk/25?dasikjsa#acskmmx`

Describe the issue

Anti-Adblock Pop-up ADS

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
`http://npob.arenavision.link/05?donsxm#iwptv`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
`http://cdn.arenavision.biz/01?odlkasxklm`

**Comment by mapx-** [comment]
already fixed, update your filters, test again

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://cdn.arenavision.biz/`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://cdn5.arenavision.link/01?odlkasxklm`

**Comment by mapx-** [comment]
I cannot reproduce the issue

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://cdn5.arenavision.link/09?sacasdcawsqs`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://arenavision.in/`
