### ISSUE TITLE
77.105.142.75: detection

### ISSUE THREAD

**Issue by mjelloDev** [uBlockOrigin/uAssets#18552]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://77.105.142.75/episode/poong-the-joseon-psychiatrist-season-1-episode-2/`

### Category

detection

### Description

When uBlock is active, it prevents user from viewing the video and a message saying we need to turn off adblock appear.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>
Screenshot(s)
</summary>

![Screenshot from 2023-06-18 12-34-15](https://github.com/uBlockOrigin/uAssets/assets/81378285/a035adeb-ab6e-40dd-9084-ed54b419cd5a)
</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 6d.15h.55m
Chromium: 114
filterset (summary):
 network: 107495
 cosmetic: 187904
 scriptlet: 25869
 html: 0
listset (total-discarded, last-updated):
 added:
  IDN-0: 9510-2, now
  adguard-annoyance: 68142-100, now
  adguard-social: 20552-877, now
  fanboy-annoyance: 91400-21688, now
  fanboy-cookiemonster: 47462-47462, now
  fanboy-social: 16083-16083, now
  fanboy-thirdparty_social: 68-18, now
  ublock-annoyances: 5077-241, now
 default:
  user-filters: 6-1, never
  easylist: 66657-114, now
  easyprivacy: 30798-145, now
  plowe-0: 3735-954, now
  ublock-abuse: 75-0, now
  ublock-badware: 7506-135, now
  ublock-filters: 33539-568, now
  ublock-privacy: 406-79, now
  ublock-quick-fixes: 289-19, 9m
  ublock-unbreak: 2048-39, now
  urlhaus-1: 6593-1, now
filterset (user): [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5883 ms (selfie)
 maxAssetCacheWait: 1777 ms
popupPanel:
 blocked: 11
 network:
  disqus.com: 2
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
  jwpcdn.com: 1
  jwpltx.com: 1
 extended:
  ##.module_home_ads
  ##.module_single_ads
  ##.dt_social_single
  ##img[alt="QQ101" i]
  ##img[alt="QQ188" i]
  ##img[alt="QQ724" i]
  ##img[alt="QQ801" i]
  ##img[alt="QQ820" i]
  ##img[alt="QQ828" i]
  ##img[alt="QQ882" i]
  ##img[alt="qq1x2" i]
  ##img[alt="qq808" i]
  ##img[alt="qq8889" i]
  ##a[href^="whatsapp://send"]
  ##.share-btn
  ##.icon-facebook-circle
  ##.share-icons-wrapper
  ###thread-share-bar
  ###email-signup
```
</details>

**Comment by grassfedtallow** [comment]
```
tv.idlixprime.com##.swal-overlay
```
