### ISSUE TITLE
hadew-yes.com: breakage

### ISSUE THREAD

**Issue by xGriinch** [uBlockOrigin/uAssets#18551]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://hadew-yes.com/zcvisitor/abe0d2fa-0d8a-11ee-b36f-12b11897cf37/85aefdc2-9ed0-48aa-922d-60f9f9fc0f2d?campaignid=863d5df0-f662-11ed-9df1-0a918cbcbb97`

### Category

breakage

### Description

When ever I try to access 9anime.com, this always keeps popping up

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1m
Chromium: 114
filterset (summary):
 network: 93226
 cosmetic: 39092
 scriptlet: 17625
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 66657-50, now
  easyprivacy: 30798-62, now
  plowe-0: 3735-952, now
  ublock-badware: 7478-135, now
  ublock-filters: 33539-142, now
  ublock-privacy: 406-2, now
  ublock-quick-fixes: 193-7, never
  ublock-unbreak: 2033-37, never
  urlhaus-1: 6644-1, never
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 308 ms
 maxAssetCacheWait: 130 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
The site (`9anime.com`) is .. gone.
