### ISSUE TITLE
jiocinema.com: ads

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#18558]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jiocinema.com/videos/puneet-ka-bigg-drama/3762189`

### Category

ads

### Description

There us ad in video

### Other extensions used

Violentmonkey
Libredirect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.19h.55m
Firefox Mobile: 114
filterset (summary):
 network: 94831
 cosmetic: 29237
 scriptlet: 17674
 html: 945
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34677-307, 22h.1m
  ublock-badware: 7474-1, 1d.11h.5m
  ublock-privacy: 436-1, 1d.4h.14m
  ublock-unbreak: 2071-1, 1d.11h.6m
  ublock-quick-fixes: 289-1, 5h.52m
  adguard-mobile: 8278-121, 3d.13h.23m
  easylist: 66972-17488, 5d.19h.37m
  easyprivacy: 30860-618, 5d.10h.36m
  urlhaus-1: 6588-1, 1h.41m
  plowe-0: 3736-1, 1d.11h.7m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10686 ms (selfie)
 maxAssetCacheWait: 604 ms
popupPanel:
 blocked: 42
 network:
  go-mpulse.net: 2
  googletagmanager.com: 2
  litix.io: 14
  mercury.akamaized.net: 1
  mparticle.com: 1
  sentry.io: 20
  voot.com: 2
```
</details>

**Comment by ghajini** [comment]
can't reproduce
ensure to have clear cookie+data & disable other extensions

**Comment by aicynide** [comment]
@ghajini there is ad in the video url i shared. It is Video ad

**Comment by aicynide** [comment]
Play full video to reproduce

**Comment by mapx-** [comment]
`Oops! Content unavailable. Try again later`

You should indicate at what point in the video you see advertising

**Comment by ghajini** [comment]
still can't reproduce.....watched full video yesterday.
how do you used violentmonkey/libredirect on firefox mobile?

@mapx- that was live video, see today 9pm IST live big boss if there's an ad?

**Comment by mapx-** [comment]
However, I guess we can only block ads for registered shows not for live ones

**Comment by ghajini** [comment]
also checked regular shows, no ad seen

**Comment by aicynide** [comment]
@ghajini I downloaded full video.https://drive.google.com/open?id=1v9VMHYDFsoFAm5DWYiJ6hxcxdlkflNt6&authuser=0

There is ad within video

**Comment by Malgotra** [comment]
Ad leftover
![Screenshot_20230704-192407~2](https://github.com/uBlockOrigin/uAssets/assets/122884037/98e39d03-a3b8-48cb-b023-ca8ebc4cbcad)
