### ISSUE TITLE
modland.net: detection

### ISSUE THREAD

**Issue by AnEht** [uBlockOrigin/uAssets#18553]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.modland.net/beamng.drive-mods/cars/tesla-model-x-2017.html`

### Category

detection

### Description

an issue

### Other extensions used

an issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.18h.57m
Chromium: 114
filterset (summary):
 network: 108535
 cosmetic: 49458
 scriptlet: 17829
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-1, never
  CHN-0: 26043-118, 3d.19h.33m
  easylist: 66657-108, 10h.22m
  easyprivacy: 30890-79, 2d.17h.36m
  plowe-0: 3735-956, 8d.18h.11m
  ublock-badware: 7346-135, 4d.20h.41m
  ublock-filters: 33575-139, 4d.20h.41m
  ublock-privacy: 407-2, 10h.23m
  ublock-quick-fixes: 289-16, 10h.19m
  ublock-unbreak: 2042-35, 4d.20h.41m
  urlhaus-1: 6574-0, 10h.21m
filterset (user): [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1353 ms (selfie)
 maxAssetCacheWait: 274 ms
popupPanel:
 blocked: 8
 network:
  google.com: 6
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by okiehsch** [comment]
That's already fixed by blocking `fundingchoicesmessages.google.com` in `uBO-filters` on my end.
I don't see that request blocked in the configuration of the OP.
