### ISSUE TITLE
bikesales.com.au: breakage

### ISSUE THREAD

**Issue by EDSTOR** [uBlockOrigin/uAssets#18562]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bikesales.com.au/bikes/details/2013-ktm-450-exc/SSE-AD-15247528/?Cr=4`

### Category

breakage

### Description

When opening pages on Bikesales there is a banner that drops down with a picture of the bike, make model and contact seller that blocks a section of the page. 

Without ublock this banner only shows when scrolling down the page. With ublock its always there and blocks some information on the page.

personal information redacted from screenshot

### Other extensions used

Consent-o-matic
Lastpass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/7483916/90e57eee-ec7f-4379-b4ef-8fd1f09c8a83)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 5d.17h.10m
Firefox: 114
filterset (summary):
 network: 92961
 cosmetic: 39157
 scriptlet: 17616
 html: 949
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34426-57, 4m
  ublock-badware: 7508-0, 2m
  ublock-privacy: 446-0, now
  ublock-unbreak: 2069-0, 1m
  ublock-quick-fixes: 235-0, now
  easylist: 66617-721, now
  easyprivacy: 30600-609, now
  urlhaus-1: 6588-1, now
  plowe-0: 3735-2, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3039 ms (selfie)
 maxAssetCacheWait: 75 ms
popupPanel:
 blocked: 26
 network:
  carsales.com.au: 2
  csnstatic.com: 2
  datadome.co: 2
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 3
  hotjar.com: 1
  imrworldwide.com: 4
  krxd.net: 1
  omtrdc.net: 3
  optimizely.com: 4
  pubmatic.com: 1
 extended:
  ##.menu-ad
  ##.AdSense
  ##.banner-ad
  ##.advert-banner
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=bikesales.com.au
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=bikesales.com.au
```

@ryanbr

**Comment by ryanbr** [comment]
Works for me, no exceptions needed

**Comment by stephenhawk8054** [comment]
Wait a while and scrolling up and down for some times? It looks working for me at first, but after a while it's just stuck. Video recording: https://github.com/uBlockOrigin/uAssets/assets/66517106/e50d7923-5f4c-4650-b088-91d2195b485d

**Comment by mapx-** [comment]
@stephenhawk8054 I tested in chrome, I need only:

`@@||cdn.optimizely.com/js/$script,domain=bikesales.com.au`

**Comment by stephenhawk8054** [comment]
```adb
@@||cdn.optimizely.com/js/$script,domain=bikesales.com.au
```

Ah yeah, that works for me too
