### ISSUE TITLE
mybib.com: ads

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#18567]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mybib.com/`

### Category

ads

### Description

After closing the modal that appears upon entering the site, there will be an ad banner on the bottom left.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/115052854/d51b85d8-be2c-41d7-a021-dfcac475c0c3)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 22m
Firefox: 114
filterset (summary):
 network: 93047
 cosmetic: 39184
 scriptlet: 17618
 html: 949
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 34428-39, now
  ublock-badware: 7518-0, now
  ublock-privacy: 446-0, now
  ublock-unbreak: 2069-0, now
  ublock-quick-fixes: 235-18, now
  easylist: 66727-305, now
  easyprivacy: 30598-78, now
  urlhaus-1: 6586-1, now
  plowe-0: 3735-953, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 217 ms (selfie)
 maxAssetCacheWait: 115 ms
popupPanel:
 blocked: 3
 network:
  bugsnag.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`mybib.com###footer > div`

report at easylist repository
@ryanbr
