### ISSUE TITLE
tv4play.se: breakage

### ISSUE THREAD

**Issue by Priskvark** [uBlockOrigin/uAssets#18561]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tv4play.se/`

### Category

breakage

### Description

The option in page footer "Cookie-inställningar" (Cookie settings) is not be available when uBlock is enabled. You see the text but there is no action when clicking on it.

(The same issue appears independent of uBlock when Firefox enhanced tracking is enabled. So, of course, I did disable that option before testing uBlock.)

I have checked my user-filters and they are not active for `https://www.tv4play.se/`

To the best of my knowledge I think this is an issue for you to investigate.

### Other extensions used

None that is relevant for blocking elements. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 5d.2h.10m
Firefox: 114
filterset (summary):
 network: 99698
 cosmetic: 101155
 scriptlet: 20857
 html: 959
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/CodyMcCodington/AutoCookieOptout/main/compatibilityList.txt: 1-0, 90d.5h.58m
  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 14h.51m
  adguard-annoyance: 68142-656, 14h.23m
 default:
  user-filters: 54-0, never
  ublock-filters: 34473-157, 2d.17h.36m
  ublock-badware: 7460-0, 2d.17h.36m
  ublock-privacy: 436-0, 5d.23h.52m
  ublock-abuse: 70-70, 5d.22h.6m
  ublock-unbreak: 2063-0, 2d.17h.36m
  easylist: 66657-577, 1d.8h.33m
  easyprivacy: 30874-658, 2d.17h.36m
  urlhaus-1: 6593-1, 14h.51m
  plowe-0: 3366-2, 10d.20h.5m
  SWE-1: 4466-2, 14h.23m
  ublock-quick-fixes: 287-0, 6h.36m
filterset (user): [array of 54 redacted]
trustedset:
 added: [array of 161 redacted]
 removed:
  about-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 12 redacted]
hostRuleset:
 added: [array of 24 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 autoUpdatePeriod: 7
supportStats:
 allReadyAfter: 813 ms (selfie)
 maxAssetCacheWait: 243 ms
popupPanel:
 blocked: 3
 network:
  tv4play.se: 1
  bugsnag.com: 1
  cookielaw.org: 1
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Sopor** [comment]
`https://www.tv4play.se/video/f9d4c3c6ea29de6436b8/avsnitt-1`

![image](https://github.com/uBlockOrigin/uAssets/assets/5789283/7897f4e5-a4fc-43ad-8094-cb52d94bd570)

uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 106096
 cosmetic: 42515
 scriptlet: 18962
 html: 1071
listset (total-discarded, last-updated):
 added:
  SWE-1: 4677-2, 2d.3h
 default:
  user-filters: 0-0, never
  ublock-filters: 35825-70, 2d.3h
  ublock-badware: 7150-0, 2d.3h
  ublock-privacy: 587-0, 2d.3h
  ublock-unbreak: 2180-0, 2d.3h
  ublock-quick-fixes: 178-0, 3m
  easylist: 71546-702, 2d.3h
  easyprivacy: 33209-717, 2d.3h
  urlhaus-1: 11210-0, 3m
  plowe-0: 3720-1, 2d.3h
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 160 ms (selfie)
 maxAssetCacheWait: 66 ms

No other extensions installed ...

![image](https://github.com/uBlockOrigin/uAssets/assets/5789283/b3ef1ed1-9017-41dd-8584-75c9adfc7dbe)

**Comment by mapx-** [comment]
I cannot reproduce the detection. Tested in FF / chrome (using a vpn)

@lassekongo83

**Comment by Sopor** [comment]
I have also made a `Purge all caches` and `Update now`, empty cookies and cleared cache (it will get cleared when i restart FF), but i still get a detection.

**Comment by mapx-** [comment]
Did you disable ETP (Enhanced Tracking Protection) ? => custom => unselect all entries

**Comment by Sopor** [comment]
Are you kidding me... Is that also an issue... Yes, now it is working, no detection anymore! 😤
