### ISSUE TITLE
tokuzilla.net: detection

### ISSUE THREAD

**Issue by Ziko577** [uBlockOrigin/uAssets#18565]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

As of yesterday, Tokuzilla is detecting uBO adblock and refuses to load the videos up if it's enabled. The only way around it was to disable and re-enable it to avoid the message. 

### URL(s) where the issue occurs.

`https://tokuzilla.net/`

### uBO version

1.50.0

### Browser name and version

Brave Browser Version 1.47.186

### Settings

N/A

**Comment by stephenhawk8054** [comment]
Can you give exact link where issue occurs?

**Comment by Ziko577** [comment]
Yes, I can. It's:
https://tokuzilla.net/watch/kamen-rider-geats-extra-kamen-rider-tycoon-meets-kamen-rider-shinobi.html

**Comment by Ziko577** [comment]
I also reported the detection to Brave as it also exhibits this behavior on
my phone as well. It's likely that'll probably be dealt with soon. The
workaround of disabling and re-enabling the shield makes the message go
away for as long as the tab is open.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
