### ISSUE TITLE
pronhubb.com: badware/typosquatting

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18563]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

misspelling of `pornhub.com`, just another typosquatting redirect

### URL(s) where the issue occurs.

`https://pronhubb.com`

### uBO version

v1.50.1b2

### Browser name and version

Firefox 114.0.1

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by mapx-** [comment]
It will land in another already blocked page.
We cannot burden badware list with all such domains.
