### ISSUE TITLE
talkforfitness.com: detection

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#18586]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://talkforfitness.com/adblock.html`

### Category

detection

### Description

Just another stupid anti-adblock nag screen.

### Other extensions used

Nothing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/129367686/887ba70d-7a83-44f4-bc76-3d39c7ab63a1)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.14m
Firefox: 114
filterset (summary):
 network: 96284
 cosmetic: 86045
 scriptlet: 19970
 html: 942
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 62104-14861, 2d.57m
 default:
  user-filters: 66-7, never
  ublock-filters: 34441-79, 4d.22h.53m
  ublock-badware: 7374-0, 4d.22h.52m
  ublock-privacy: 436-0, 2d.58m
  ublock-unbreak: 2056-0, 4d.22h.51m
  ublock-quick-fixes: 240-0, 8h.23m
  easylist: 66617-772, 2d.56m
  easyprivacy: 30797-624, 1d.22h.55m
  urlhaus-1: 6601-1, 5h.48m
  plowe-0: 3738-2, 4d.3h.28m
  spa-1: 5282-10, 1d.6h.9m
filterset (user): [array of 66 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 778 ms (selfie)
 maxAssetCacheWait: 280 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
shortener ?

**Comment by BRR34L0RD** [comment]
Probably this is it: https://clks.pro/LxvXCPA

**Comment by mapx-** [comment]
shorteners only here: https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by BRR34L0RD** [comment]
I posted wrong link. Corrected now.

**Comment by mapx-** [comment]
I get no detection. It seems to be a page used by the same shorteners.
