### ISSUE TITLE
mdn.lol: detection

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#18587]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mdn.lol/2023/01/16/40-seo-myths-you-may-have-fallen-for/`

### Category

detection

### Description

Annoying anti-adblock message?

### Other extensions used

Nothing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/129367686/4aa37768-f9be-4acd-80f2-374ea3643cbc)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.17m
Firefox: 114
filterset (summary):
 network: 96284
 cosmetic: 86045
 scriptlet: 19970
 html: 942
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 62104-14861, 2d.1h.1m
 default:
  user-filters: 66-7, never
  ublock-filters: 34441-79, 4d.22h.56m
  ublock-badware: 7374-0, 4d.22h.55m
  ublock-privacy: 436-0, 2d.1h.2m
  ublock-unbreak: 2056-0, 4d.22h.54m
  ublock-quick-fixes: 240-0, 8h.26m
  easylist: 66617-772, 2d.1h
  easyprivacy: 30797-624, 1d.22h.59m
  urlhaus-1: 6601-1, 5h.51m
  plowe-0: 3738-2, 4d.3h.31m
  spa-1: 5282-10, 1d.6h.12m
filterset (user): [array of 66 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 778 ms (selfie)
 maxAssetCacheWait: 280 ms
popupPanel:
 blocked: 6
 network:
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 1
  googletagmanager.com: 3
  wtg-ads.com: 1
 extended:
  ##+js(addEventListener-defuser, DOMContentLoaded, adsBlocked)
  ##+js(no-setTimeout-if, show)
  ##+js(abort-current-script, onload, adblock)
  ##+js(window.open-defuser)
  ##+js(abort-on-property-read, pbjs)
  ##+js(no-fetch-if, wpadmngr)
  ##+js(abort-current-script, document.createElement, adsBlocked)
  ##+js(set-constant, document.hasFocus, trueFunc)
```
</details>

**Comment by mapx-** [comment]
shorteners => https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by BRR34L0RD** [comment]
https://talkforfitness.com/best-elliptical-under-500/ 

Original link if you need it.
