### ISSUE TITLE
btcleets.xyz [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1858]
URL(s) where the issue occurs

`http://btcleets.xyz/Px0XG8WZ`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by SMed79** [comment]
@mapx- check here the anti adb `http://btcleets.xyz/btc/` (http://i.imgur.com/qs5VCTk.png)
