### ISSUE TITLE
Investing.com is blocking again adblock!

### ISSUE THREAD

**Issue by ghostrider72** [uBlockOrigin/uAssets#18581]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Like a couple of weeks ago, the issue is back again and it's impossible to browse investing.com. As soon as I try, a popup comes up saying I have an adblock!

### URL(s) where the issue occurs.

www.investing.com

### Screenshot(s)

nothing

### uBO version

1.50.0

### Browser name and version

Chrome 114.0.5735.133

### Settings

nothing

### Notes

nothing

**Comment by mapx-** [comment]
update all your lists
