### ISSUE TITLE
kr.investing.com: detection

### ISSUE THREAD

**Issue by sysgen1** [uBlockOrigin/uAssets#18583]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://investing.com/`

### Category

detection

### Description

It looks like you're using an ad-blocker
Investing.com is an advertising-supported site. Here are three ways you can keep browsing our site:

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98539130/cf063b2a-0368-463d-81e0-8ff271dad271)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.1h.13m
Chromium: 114
filterset (summary):
 network: 94388
 cosmetic: 42256
 scriptlet: 17747
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  KOR-1: 4463-15, 17m
  easylist: 66617-92, 1d.1h.9m
  easyprivacy: 30891-72, 1d.18h.58m
  plowe-0: 3735-963, 17m
  ublock-badware: 7506-135, 1d.18h.58m
  ublock-filters: 33539-144, 1d.18h.58m
  ublock-privacy: 396-4, 6d.1h.15m
  ublock-quick-fixes: 238-16, 17m
  ublock-unbreak: 2048-35, 1d.18h.58m
  urlhaus-1: 6586-1, 17h.8m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 166 ms (selfie)
 maxAssetCacheWait: 78 ms
popupPanel:
 blocked: 13
 network:
  investing.com: 2
  adnxs.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  outbrain.com: 3
  scorecardresearch.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

Did you?
