### ISSUE TITLE
adflow.adstandards.ca: breakage

### ISSUE THREAD

**Issue by mobinet-ca** [uBlockOrigin/uAssets#18582]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://adflow.adstandards.ca/`

### Category

breakage

### Description

The scripts on this site are failing to load when uBlock Origin is enabled due to them being blocked. This is not a website that provides advertisements, rather a site that advertising agency use to ensure they stay compliant with advertising standards in Canada.

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/13296420/4793afde-8bce-43c0-8fb2-56e57b0a9572)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.6h.24m
Firefox: 114
filterset (summary):
 network: 93132
 cosmetic: 39176
 scriptlet: 17678
 html: 943
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34499-155, 4d.2h.18m
  ublock-badware: 7374-0, 4d.2h.20m
  ublock-privacy: 436-0, 6d.16h.43m
  ublock-unbreak: 2060-0, 4d.2h.19m
  easylist: 66674-582, 1d.6h.10m
  easyprivacy: 30866-656, 5d.14h.29m
  plowe-0: 3733-2, 10d.7h.13m
  urlhaus-1: 6601-1, 4h.6m
  ublock-quick-fixes: 235-0, 4h.5m
filterset (user): [empty]
trustedset:
 added: [array of 18 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 572 ms (selfie)
 maxAssetCacheWait: 145 ms
popupPanel:
 blocked: 20
 network:
  adstandards.ca: 20
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
````
/adflow.$from=~adflow.com.au|~adflow.genoudsa.ch|~adflow.io|~adflow.marketing|~adflow.pl,badfilter
/adflow.$from=~adflow.adstandards.ca|~adflow.com.au|~adflow.genoudsa.ch|~adflow.io|~adflow.marketing|~adflow.pl
````
