### ISSUE TITLE
oqee.tv: detection

### ISSUE THREAD

**Issue by user460** [uBlockOrigin/uAssets#18592]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://oqee.tv/home`

### Category

detection

### Description

"You're using an ad blocker that prevents you from taking full advantage of OQEE by Free.
To continue the experience, allow the application on your ad blocker or disable it."

This website requires a Free account (French ISP account)

### Other extensions used

Skip redirect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[screenshot](https://github.com/uBlockOrigin/uAssets/assets/127345415/1df1e962-cbe5-4dcd-a0de-2945308e198b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.2
Firefox: 114
filterset (summary): 
  network: 163877
  cosmetic: 143381
  scriptlet: 35567
  html: 948
listset (total-discarded, last updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/14.txt: 68200-789, 2m
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 44857-13674, 2m
    https://get.letsblock.it/list/4a8d39d8-1edd-470e-a3f7-946a174faeb9.txt: 1310-0, 2m
    https://raw.githubusercontent.com/robonxt/CleanYourTwitter/master/CleanYourTwitter%20(EXTRAS).txt: 5-0, 2m
    https://raw.githubusercontent.com/robonxt/CleanYourTwitter/master/CleanYourTwitter.txt: 17-0, 2m
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 2m
    adguard-generic: 71718-6355, 2m
    FRA-0: 28328-419, 2m
  default: 
    user-filters: 43-0, never
    ublock-filters: 34409-60, 2m
    ublock-badware: 7531-1, 2m
    ublock-privacy: 448-75, 2m
    ublock-unbreak: 2065-0, 2m
    ublock-quick-fixes: 220-0, 2m
    easylist: 66864-929, 2m
    easyprivacy: 30598-610, 2m
    urlhaus-1: 6644-1, 2m
    plowe-0: 3735-1, 2m
filterset (user): [array of 44 redacted]
trustedset: 
  added: [array of 49 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 308 ms (selfie)
  maxAssetCacheWait: 405 ms
popupPanel: 
  blocked: 3
  blockedDetails: 
    googletagmanager.com: 1
    imasdk.googleapis.com: 1
    privacy-center.org: 1
```
</details>

**Comment by user460** [comment]
> @user460 If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

I would If I could. Unfortunately I'm not using my personal account so I can't share it, sorry.

**Comment by mapx-** [comment]
We cannot investigate the issue without an account. Closing.

**Comment by SuperPat45** [comment]
Il suffit d'ajouter se filtre dans ublock pour qu'il ne soit plus détecté:
Simply add this filter to ublock and it will no longer be detected:

@@||imasdk.googleapis.com^$script,domain=oqee.tv

**Comment by mapx-** [comment]
Which is the complete address for `imasdk.googleapis.com` ?

**Comment by SuperPat45** [comment]
Due to last update, a new filter link is required for the replay and VOD services:

@@||sdk.privacy-center.org^$script,domain=oqee.tv

Complete links for the two domains are:
https://imasdk.googleapis.com/js/sdkloader/ima3.js
https://imasdk.googleapis.com/js/core/bridge3.605.0_fr.html
https://sdk.privacy-center.org/596c2a3d-7ded-452c-a54f-c290c5face33/loader.js?target_type=notice&target=b32Lkcwh
https://sdk.privacy-center.org/sdk/1ce50874cc0bcdb12ea4dfc5c47b2b4b6f6e3b9a/modern/sdk.1ce50874cc0bcdb12ea4dfc5c47b2b4b6f6e3b9a.js
https://sdk.privacy-center.org/sdk/1ce50874cc0bcdb12ea4dfc5c47b2b4b6f6e3b9a/modern/src_sdk_regulations_gdpr_tcf_v2_2_vendors_iab-core_js.1ce50874cc0bcdb12ea4dfc5c47b2b4b6f6e3b9a.js
https://sdk.privacy-center.org/sdk/1ce50874cc0bcdb12ea4dfc5c47b2b4b6f6e3b9a/modern/src_sdk_regulations_gdpr_tcf_v2_2_purposes_index_js.1ce50874cc0bcdb12ea4dfc5c47b2b4b6f6e3b9a.js
https://sdk.privacy-center.org/sdk/1ce50874cc0bcdb12ea4dfc5c47b2b4b6f6e3b9a/modern/tcf-service-2-2.1ce50874cc0bcdb12ea4dfc5c47b2b4b6f6e3b9a.js

**Comment by mapx-** [comment]
@SuperPat45 are you using AG annoyances ?

**Comment by SuperPat45** [comment]
I enabled all filter lists

**Comment by mapx-** [comment]
@Yuki2718 for AG `sdk.privacy-center.org`

**Comment by Thomas-D-C** [comment]
Hi :-)

I can't watch videos when uBlock Origin is enabled because it stops when ads start playing.

The best thing would be for you to have a knowledgeable volunteer who uses the French ISP Free.
Otherwise, I need you to tell me what to do step by step, please. :-)

**Comment by stephenhawk8054** [comment]
We need accounts to investigate directly. It's not possible to investigate these issues via comments on github.

If there's no volunteers who can access these sites, there's nothing we can do.

**Comment by SuperPat45** [comment]
Ads stop playing, and the replay videos are paused at the start, but after many seconds (the time of the ad), the videos finally play.
