### ISSUE TITLE
polsatgo.pl: detection

### ISSUE THREAD

**Issue by waaldiigam** [uBlockOrigin/uAssets#18593]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://polsatgo.pl/wideo/programy/stop-drogowka/5024658/stop-drogowka-odcinek-310/e7e3f7c638d469872920fe1602bb3508/ogladaj?next=https%253A%252F%252Fpolsatgo.pl%252Fwideo%252Fprogramy%252Fstop-drogowka%252F5024658%252Fstop-drogowka-odcinek-310%252Fe7e3f7c638d469872920fe1602bb3508`

### Category

detection

### Description

Site asks for disabling adblock. Site has polish programs that are showed in public television. Content is free, but like always they ask us to disable adblock to be able to watch the show.

### Other extensions used

Lastpass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Detection](https://github.com/uBlockOrigin/uAssets/assets/55682846/97260049-2ef1-4929-83f1-399dbe6dbe26)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 6d.4h.18m
Chromium: 114
filterset (summary):
 network: 93255
 cosmetic: 39152
 scriptlet: 17649
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 66856-50, now
  easyprivacy: 30599-54, now
  plowe-0: 3735-952, now
  ublock-badware: 7529-136, now
  ublock-filters: 33557-142, now
  ublock-privacy: 410-3, now
  ublock-quick-fixes: 223-24, now
  ublock-unbreak: 2049-34, now
  urlhaus-1: 6644-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 256 ms (selfie)
 maxAssetCacheWait: 120 ms
popupPanel:
 blocked: 5
 network:
  gemius.pl: 3
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
@waaldiigam enable the 2 polish lists, it's ok on my end, no detection

**Comment by waaldiigam** [comment]
Where can I find those?

**Comment by waaldiigam** [comment]
Ok found it under settings. This is working. Thanks
