### ISSUE TITLE
[nsfw] skyrim-beautification-project.com: ads

### ISSUE THREAD

**Issue by Gabrierz** [uBlockOrigin/uAssets#18595]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://www.skyrim-beautification-project.com/oblivion/faq/index.htm`

### Category

ads

### Description

NSFW ads still remaining as banner on the website

### Other extensions used

- Dark Reader
- Webtime Tracker
- MetMask
- BetterTTV
- Enhancer for YouTube
- nightTab
- Return YouTube Dislike
-  Social Blade
- YouTube Full Title For Videos

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Oblivion Beautification Project - F A Q  - Google Chrome 20_06_2023 16_14_13](https://github.com/uBlockOrigin/uAssets/assets/92695404/6a34d798-6471-47cd-8054-ef96fab6a20e)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.5h.51m
Chromium: 114
filterset (summary):
 network: 95706
 cosmetic: 43737
 scriptlet: 17650
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 6915-0, now
  easylist: 66858-57, now
  easyprivacy: 30599-63, now
  plowe-0: 3735-953, now
  ublock-badware: 7529-136, now
  ublock-filters: 33558-156, now
  ublock-privacy: 410-3, now
  ublock-quick-fixes: 223-24, 40m
  ublock-unbreak: 2049-36, now
  urlhaus-1: 6798-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 463 ms
 maxAssetCacheWait: 160 ms
popupPanel:
 blocked: 1
 network:
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
to be reported at easylist repository

add

`skyrim-beautification-project.com##[src*="/aff/"]`

or

`skyrim-beautification-project.com##[href^="https://adultfriendfinder.com/go/"]`

@ryanbr
