### ISSUE TITLE
zoho.com: breakage

### ISSUE THREAD

**Issue by szotsaki** [uBlockOrigin/uAssets#18597]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`https://mail.zoho.com/zm/#mail/` doesn't load after logging in.

### URL(s) where the issue occurs.

`https://js.zohocdn.com/zmail/zm/372.4/js/main.js`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/4254450/9372d7a5-a5d0-4689-ad39-e47ad3befa45)

### uBO version

1.50

### Browser name and version

Vivaldi 6.1

### Settings

-

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by szotsaki** [comment]
All:
<details><summary>Logger output</summary>

```
+2
mail.zoho.com
0,1
get
script
https://mail.zoho.com/zm/sw.js
```
```
+1
||js.zohocdn.com^$3p
--
mail.zoho.com
3
get
image
https://js.zohocdn.com/zmail/zm/app/pwaicons/icon-192x192.png
```
```
+1
mail.zoho.com
3
get
image
https://img.zohostatic.com/zmail/zm/372.4/images/favicon.ico
```
```
+1
mail.zoho.com
1
get
other
https://mail.zoho.com/zm/pwamanifest.json
```
```
+1
||js.zohocdn.com^$3p
--
mail.zoho.com
3
get
script
https://js.zohocdn.com/zmail/zm/372.4/js/main.js
```
```
+0
mail.zoho.com
0,1
get
xhr
https://mail.zoho.com/zm/#mail/folder/inbox/p/1687265067609170001
```
</details>

Blocked:
- https://js.zohocdn.com/zmail/zm/app/pwaicons/icon-192x192.png
- https://js.zohocdn.com/zmail/zm/372.4/js/main.js

Both come from EasyList – Chat Widgets.

**Comment by mapx-** [comment]
@ryanbr

**Comment by harry-dickson** [comment]
FYI: the quick fix doesn't work for zoho's other top-level domains - in my case zoho.eu - as it is explicitly set to zoho.com

**Comment by harry-dickson** [comment]
With these in latest quickfixes:
```
||js.zohocdn.com^$third-party,badfilter
||js.zohocdn.com^$third-party,domain=~zoho.com,badfilter
```
it works for me  (via mail.zoho.eu) so nothing to report :)
