### ISSUE TITLE
wired.com - Anti adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#186]
Anti adb warning is displayed on articles on `wired.com`, the warning is not displayed the first time you visit an article.

**To reproduce:** Visit https://www.wired.com/2016/11/nasa-will-choose-first-mars-faring-astronauts/ and after the page loads completely visit ~~https://www.wired.com/2016/11/2016-election-exposes-dark-side-tech/ and scroll down~~ and click on any article in the "**MOST POPULAR**" and scroll down (directly visiting an article does not trigger the anti adb warning it is trigerred if links are clicked internally).

The **uBlock filters** fix is not working anymore.

_Using Chrome 54 without any other extensions, tested using latest default uBlock filters._

**Comment by ghajini** [comment]
Antiadblock annoyance
`https://www.wired.co.uk/article/porn-ransomware-reveton`
