### ISSUE TITLE
mail.zoho.eu: breakage

### ISSUE THREAD

**Issue by Zosoworld** [uBlockOrigin/uAssets#18609]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mail.zoho.eu/zm/`

### Category

breakage

### Description

uBlock is blocking `js.zohocdn.com` as of very recently, causing the mail window in Zoho to stay loading forever.

### Other extensions used

`I still don't care about cookies`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2023-06-21 09-45-33](https://github.com/uBlockOrigin/uAssets/assets/5672022/a345497f-b066-4776-b499-0a30769e54d6)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.14h.9m
Firefox: 114
filterset (summary):
 network: 93480
 cosmetic: 39190
 scriptlet: 17642
 html: 952
listset (total-discarded, last-updated):
 default:
  user-filters: 8-0, never
  ublock-filters: 34432-59, 2m
  ublock-badware: 7540-1, 2m
  ublock-privacy: 451-0, 1h.36m
  ublock-unbreak: 2082-0, 2m
  easylist: 67023-727, 1h.35m
  easyprivacy: 30602-610, 2m
  urlhaus-1: 6685-1, 1h.35m
  plowe-0: 3737-1, 2m
  ublock-quick-fixes: 255-0, 1h.35m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 365 ms (selfie)
 maxAssetCacheWait: 99 ms
popupPanel:
 blocked: 2
 network:
  zohocdn.com: 2
```
</details>

**Comment by dportvine** [comment]
Try it
```
||js.zohocdn.com^$third-party,domain=~zoho.com,badfilter
||js.zohocdn.com^$third-party,domain=~zoho.*
```

<details>
<summary>Screen</summary>

![2023-06-21_220544](https://github.com/uBlockOrigin/uAssets/assets/111344219/86dc05c2-b506-45b9-b892-9344ef14d7e6)
</details>

**Comment by Zosoworld** [comment]
> Try it
> 
> ```
> ||js.zohocdn.com^$third-party,domain=~zoho.com,badfilter
> ||js.zohocdn.com^$third-party,domain=~zoho.*
> ```
> 
> Screen
> 
> ![2023-06-21_220544](https://user-images.githubusercontent.com/111344219/247700207-86dc05c2-b506-45b9-b892-9344ef14d7e6.png) ![2023-06-21_220813](https://user-images.githubusercontent.com/111344219/247700751-f7d91c49-91ae-46bc-976f-a8706d2bb75b.png)

Can confirm it works properly with the user-defined rules. Thank you!

**Comment by krystian3w** [comment]
Who list have that filter?

**Comment by camelCaseNick** [comment]
@mapx- As far as I can tell, this was neither fixed in Quick fix nor upstream in easylist – only #18597 was addressed, i.e. zoho.com works, zoho.eu does not. (What) am I missing?

**Comment by stephenhawk8054** [comment]
The filter is in `EasyList - Chat Widgets`, I mistakenly think it's in EasyPrivacy. The filter is removed in quick fix list now: https://github.com/uBlockOrigin/uAssets/commit/46440317f5b1f82fb46bd31bd3f552bb35fcd22b

**Comment by stephenhawk8054** [comment]
@GnaniSankaran I have removed the filter in the quick fix list. You can force update all the filter lists and test again. The list should be updated to everyone in a few hours.

**Comment by GnaniSankaran** [comment]
Hi @stephenhawk8054 Looks like uBlock Origin is again blocking Zoho Mail. One of the mail JavaScript resource https://js.zohocdn.com/zmail/zm/377.8/js/main.js isn't loading.Logger says the rule is "||js.zohocdn.com^$3p,from=~zoho.com|~zoho.eu" under EasyList Chat Widgets.

**Comment by stephenhawk8054** [comment]
@GnaniSankaran Please report to this repo: https://github.com/easylist/easylist/issues
