### ISSUE TITLE
eskago.pl [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1860]
URL(s) where the issue occurs

`http://www.eskago.pl/radio/eska-rock`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by okiehsch** [comment]
Already fixed in the regional polish list.
