### ISSUE TITLE
plagiarismdetector.net: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18607]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://plagiarismdetector.net/`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/254acddf-1b8f-415f-9dfa-0ea8970fd575)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.6h.58m
Chromium: 114
filterset (summary):
 network: 127009
 cosmetic: 135226
 scriptlet: 24486
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9062-4, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 523-4, now
  DEU-0: 6917-0, now
  FRA-0: 28328-65, now
  IDN-0: 9514-372, now
  ara-0: 2396-8, now
  easylist-annoyances: 3868-43, now
  easylist-chat: 126-0, now
  easylist-newsletters: 6119-15, now
  easylist-notifications: 2629-84, now
  fanboy-cookiemonster: 47623-222, now
  fanboy-social: 16092-16, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  easylist: 67023-249, now
  easyprivacy: 30602-419, now
  plowe-0: 3737-975, now
  ublock-badware: 7538-155, now
  ublock-filters: 33559-405, now
  ublock-privacy: 410-6, now
  ublock-quick-fixes: 255-25, now
  ublock-unbreak: 2059-45, now
  urlhaus-1: 6685-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 668 ms (selfie)
 maxAssetCacheWait: 348 ms
popupPanel:
 blocked: 17
 network:
  plagiarismdetector.net: 7
  adpushup.com: 1
  cloudflareinsights.com: 1
  google-analytics.com: 1
  google.com: 5
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##a[href^="https://www.grammarly.com/"]
  ##[href*="grammarly.com"]
  ##[style]:has([onclick*="open"])
  ##aside :is(ins, ._ap_apex_ad):upward(aside)
  ##*:style(animation: none !important;)
  ##ins.adsbygoogle:style(max-height: 1.23px !important;)
  ##+js(no-fetch-if, /googlesyndication|adpushup|adrecover/)
  ##+js(no-requestAnimationFrame-if, _0x)
  ##+js(no-setInterval-if, ads)
  ##+js(no-setTimeout-if, /ads|showPopup/)
  ##+js(abort-on-stack-trace, adblock)
  ##+js(no-xhr-if, /googlesyndication|adpushup|adrecover/)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Daxy7** [comment]
`###cookiebar` in [line 3549 of fanboy's cookiemonster](https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_general_hide.txt#L3549) should hide this, no?

**Comment by Daxy7** [comment]
Found `smallseotools.com###cookie-bar` and 
```
###cookie-bar-2019
###cookie-bar-ardanta
###cookie-bar-bottom
###cookie-bar-fixed
###cookie-bar-main
###cookie-bar-message
###cookie-bar-mob
###cookie-bar-module
###cookie-bar-warning
###cookie-bar-wrapper
###cookie-bar2
###cookie-barBe
###cookie-bar__wrapper
###cookie-barbody
```
No generic `###cookie-bar` though
maybe we could use
```
plagiarismdetector.net,smallseotools.com###cookie-bar
plagiarismchecker.co###cookies
```
