### ISSUE TITLE
Dynamically imported module blocked "..../assets/Analytics-cb927175.js"

### ISSUE THREAD

**Issue by NickPelov** [uBlockOrigin/uAssets#18605]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Our development team noticed an issue after one of our releases. The website has a react component called Analytics (shows some analytics graphs for the product performance) which gets bundled into "..../assets/Analytics-cb927175.js" as a dynamically imported component/module. 

uBlock Origin picks up the component blocks the request and crashes the website.

It's not a public page, but I can assist whoever wants to look into this issue and show the behavior.

### A specific URL where the issue occurs.

It's not a public page, but I can assist whoever wants to look into this issue and show the behavior.

### Steps to Reproduce

Simply going to the page which requires the dynamic import crashesh the website.

### Expected behavior

We expect functional components of websites to not get blocked simply based on their name.

### Actual behavior

As soon as the webpage is visited the resource is requested and blocked by uBlock. Screenshot attached:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/17296943/dbe13768-7175-42a4-bf7d-95aacdf878fa)

### uBO version

1.50.0

### Browser name and version

Chrome 114

### Operating System and version

Windows 10

**Comment by krystian3w** [comment]
You can test in my filters tab:

```adb
@@/assets/Analytics-$domain=app
```

if public suffix of private web app is ".app".

**Comment by mapx-** [comment]
- without a test link we cannot investigate
- at least from the logger which is the blocking filter ?

@ryanbr

**Comment by ryanbr** [comment]
We're not blocking assets/Analytics-

**Comment by NickPelov** [comment]
We were also really confused why this was happening and traced it back to the uBlock logs where the "assets/Analytics-" was highlighted in red. 
Yesterday we simply changed our rollup options to not output the names of the components in the end build to prevent this from happening. I tried spinning up a preview build today with the old setup to check which filter is blocking the asset (did not think to write it down yesterday). 
But sadly as it happens I can't reproduce the issue again even though we experienced it on 3 different devices and verified it was being blocked.

**Comment by gorhill** [comment]
> But sadly as it happens I can't reproduce the issue again even though we experienced it on 3 different devices and verified it was being blocked.

It's blocked if you install uBO 1.50.0 and immediately try to reproduce your issue. But after a few minutes, your new installation of uBO will have updated the filter lists and you won't be able to reproduce anymore because the filter causing your issue was [removed 4 days ago](https://github.com/easylist/easylist/commit/b8cdca2b858de0d9c65468319f1b94ca4f676883#diff-b17c8b1c6dcc6a4f4dd2fef00625e42aa5e25ff1850baed7027a2ae59200bdc9).
