### ISSUE TITLE
[nsfw] wan.xingga.com: ads

### ISSUE THREAD

**Issue by MQqiu** [uBlockOrigin/uAssets#18603]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wan.xingga.com/tg/tui.html?lyid=2dK0bK1ZyRok`

### Category

ads

### Description

> 这个网址是非常烦人的广告而且像狗皮膏药一样

**this url is very annoying ad and like a dog skin plaster**

### Other extensions used

> 无

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/137256510/b1adaea6-c5bf-4dd8-9d29-9db8316d4cff)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 6m
Chromium: 114
filterset (summary):
 network: 109014
 cosmetic: 49435
 scriptlet: 17824
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CHN-0: 26183-118, 6m
  easylist: 67023-110, 5m
  easyprivacy: 30599-71, 5m
  plowe-0: 3737-954, 5m
  ublock-badware: 7533-137, 5m
  ublock-filters: 33558-156, 4m
  ublock-privacy: 410-3, 4m
  ublock-quick-fixes: 257-24, 4m
  ublock-unbreak: 2049-35, 4m
  urlhaus-1: 6684-1, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1902 ms
 maxAssetCacheWait: 10 ms
popupPanel:
 blocked: 1
 network:
  baidu.com: 1
```
</details>

**Comment by mapx-** [comment]
report here:
https://github.com/cjx82630/cjxlist/issues
