### ISSUE TITLE
9now.com.au detection

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#18606]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlock Origin is deteced.

### URL(s) where the issue occurs.

`https://www.9now.com.au/live/channel-9`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/20948631/4991bdec-1e3d-46a7-b287-595cbe9fc416

### uBO version

1.50.0

### Browser name and version

Google Chrome x64 114.0.5735.134

### Settings

```yaml
uBlock Origin 1.50.0:
 since: 10d.8h.38m
Chromium: 114
filterset (summary):
 network: 331724
 cosmetic: 224033
 scriptlet: 40816
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68287-97, 11h.30m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 67482-0, 6m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91391-20864, 4d.11h.58m
  adguard-cookies: 26008-26008, 11h.39m
  adguard-generic: 71807-509, 11h.38m
  adguard-mobile: 8284-57, 11h.37m
  adguard-mobile-app-banners: 4336-4336, 11h.36m
  adguard-other-annoyances: 13049-13049, 11h.35m
  adguard-popup-overlays: 22717-22717, 11h.34m
  adguard-social: 20591-1531, 11h.33m
  adguard-spyware: 45653-1249, 11h.32m
  adguard-widgets: 2177-2177, 11h.31m
  [12 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  easylist: 66607-1276, 4d.11h.58m
  easyprivacy: 30895-13726, 4d.11h.58m
  plowe-0: 3736-1455, 4d.11h.58m
  ublock-badware: 7478-398, 4d.11h.58m
  ublock-filters: 33531-4156, 4d.11h.58m
  ublock-privacy: 396-60, 4d.11h.58m
  ublock-quick-fixes: 289-21, 11h.29m
  ublock-unbreak: 2049-138, 4d.11h.58m
filterset (user): [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 961 ms (selfie)
 maxAssetCacheWait: 512 ms
```

**Comment by mapx-** [comment]
only annoyance, could be enough

`9now.com.au##[id="toggle_notification_notification-ad-blocker"]:upward(1)`
