### ISSUE TITLE
nsongs.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1861]
URL(s) where the issue occurs

`https://nsongs.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by okiehsch** [comment]
Can't reproduce.

**Comment by mapx-** [comment]
same here, no anti adb message on page

**Comment by KiLL4FuNK** [comment]
how weird now do not show anything can close the topic
