### ISSUE TITLE
natgeotv.com: nuisance

### ISSUE THREAD

**Issue by qzcz** [uBlockOrigin/uAssets#18617]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.natgeotv.com/`

### Category

nuisance

### Description

###onetrust-consent-sdk

### Other extensions used

Bitwarden, Simple Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/110184059/bf720c65-d7f0-4d2c-b542-cd004194e488)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.9h.22m
Firefox: 114
filterset (summary):
 network: 142906
 cosmetic: 51815
 scriptlet: 22984
 html: 1124
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  adguard-spyware-url: 1093-5, 1m
  adguard-spyware: 70121-13616, 1m
  ublock-annoyances: 5220-7, 1m
 default:
  user-filters: 48-0, never
  ublock-filters: 34434-61, 1m
  ublock-badware: 7540-0, 1m
  ublock-privacy: 451-0, 1m
  ublock-unbreak: 2084-1, 1m
  ublock-quick-fixes: 243-0, 1m
  easylist: 67058-419, 1m
  easyprivacy: 30603-31, 1m
  TUR-0: 14174-13, 1m
filterset (user): [array of 54 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 suspendUntilListsAreLoaded: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4121 ms (selfie)
 maxAssetCacheWait: 2258 ms
 unsuspendAfter: 1207 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by krystian3w** [comment]
If e.g. "video"s are fine without accept, then you can ask to force add to Easylist Cookies.

![image](https://github.com/uBlockOrigin/uAssets/assets/35370833/2b89823a-a86d-4816-8aa7-c6a416b1d9e6)

Many pages badly use OneTrust/Optanon - I mean to show only pop-up without block use players with any content (1p/3p).
