### ISSUE TITLE
wetteronline.de: breakage

### ISSUE THREAD

**Issue by Carltoffel** [uBlockOrigin/uAssets#18616]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wetteronline.de/wetterticker/unwetter-am-donnerstag-gefaehrliche-wetterlage--b89dd302-3f95-4c2a-928b-66174ea55780`

### Category

breakage

### Description

Video content gets blocked.

This is the innermost `div` uBO allows. Inside should be a `div class="theo-player-wrapper"` which is missing:
```
<wo-social-media-container _ngcontent-ng-c1353573404="" _nghost-ng-c3110603446=""><div _ngcontent-ng-c1353573404="" class="player-container video-js theoplayer-skin" style="padding-top: 56.25%;"></div><!----><!----></wo-social-media-container>
```

### Other extensions used

Many (privacy badger, decentraleyes, i don't care about cookies, cookie auto delete, ...), but enabling/disabling uBO is enough to toggle the issue. I even tried disabling some of my extensions, but the cause seems to be uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Site with uBO enabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/33249047/efba22b9-e9b7-4c81-b828-c49bc41b7b59)
Site with uBO disabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/33249047/e96c1bdb-581a-4c0c-aa5f-fb161f0c2064)

The upper is content while the lower is an ad.
</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 8d.19h.20m
Firefox: 114
filterset (summary):
 network: 93104
 cosmetic: 39162
 scriptlet: 17644
 html: 948
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 34427-50, 3d.36m
  ublock-badware: 7518-1, 3d.36m
  ublock-privacy: 451-0, 1d.18h.8m
  ublock-unbreak: 2069-0, 3d.36m
  easylist: 66665-722, 3d.36m
  easyprivacy: 30598-609, 2d.19h.20m
  urlhaus-1: 6684-1, 22h.25m
  plowe-0: 3735-1, 2d.23h.52m
  ublock-quick-fixes: 243-0, 20m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 506 ms (selfie)
 maxAssetCacheWait: 157 ms
popupPanel:
 blocked: 11
 network:
  wetteronline.de: 6
  cleverpush.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  indexww.com: 1
 extended:
  ##.adplace
  ###topcontainer
  ##[id^="google_ads_iframe"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ###BannerAd
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(abort-on-property-read, __eiPb)
```
</details>

**Comment by mapx-** [comment]
german page, enable the regional list EasyList Germany

**Comment by Carltoffel** [comment]
Ah, thanks! Works! :)
