### ISSUE TITLE
yuri.website: breakage

### ISSUE THREAD

**Issue by Tauschii** [uBlockOrigin/uAssets#18619]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yuri.website/`

### Category

breakage

### Description

The search bar is missing.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 3d.22h.22m
Firefox: 116
filterset (summary):
 network: 301656
 cosmetic: 227874
 scriptlet: 40907
 html: 1124
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68342-1809, 1h.2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91597-37311, 59m
  adguard-generic: 71865-6239, 1h.2m
  adguard-spyware-url: 1093-5, 1h.2m
  adguard-spyware: 70121-13743, 1h.2m
  curben-phishing: 109135-39, 1h.2m
  curben-pup: 199-0, 1h.2m
  adguard-social: 20667-683, 1h.2m
  fanboy-thirdparty_social: 68-0, 1h
  fanboy-social: 16092-17, 1h.2m
  ublock-annoyances: 5219-7, 1h.2m
 default:
  user-filters: 3-0, never
  ublock-filters: 34444-73, 24m
  ublock-badware: 7540-0, 24m
  ublock-privacy: 451-0, 24m
  ublock-unbreak: 2084-1, 24m
  ublock-quick-fixes: 243-0, 24m
  easylist: 67058-789, 1h
  easyprivacy: 30603-615, 1h
  urlhaus-1: 6597-1, 1h
  plowe-0: 3737-2, 59m
  CHN-0: 26202-138, 1h.2m
filterset (user): [array of 3 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 42723 ms
 maxAssetCacheWait: 39 ms
popupPanel:
 blocked: 3
 network:
  yuri.website: 2
  cloudflareinsights.com: 1
 extended:
  ##.social-top:not(html):not(body)
  ##.adtitle
```
</details>

**Comment by krystian3w** [comment]
bad is:

```adb
##.social-top:not(html):not(body)
```

from Fanboy Social.

Hotfix:

`yuri.website#@#.social-top:not(html):not(body)`

Future Fanboy Social breakges can you report in official place:

https://github.com/easylist/easylist/issues
