### ISSUE TITLE
8hysw.com: ads

### ISSUE THREAD

**Issue by npljy** [uBlockOrigin/uAssets#18615]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://www.8hysw.com/play/40318-0-2.html`

### Category

ads

### Description

ads

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 13d.23h.37m
Chromium Mobile: 110
filterset (summary):
 network: 110210
 cosmetic: 38284
 scriptlet: 17842
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  CHN-0: 26136-1335, 2d.12h.42m
  adguard-mobile: 8280-53, 2d.12h.43m
  easylist: 66665-16783, 3d.19h.54m
  easyprivacy: 30891-86, 5d.16h.2m
  plowe-0: 3735-1032, 3d.14h.47m
  ublock-badware: 7472-136, 4d.19h.45m
  ublock-filters: 33827-405, 1d.7h.33m
  ublock-privacy: 406-3, 3d.8h.16m
  ublock-quick-fixes: 229-19, 3h.18m
  ublock-unbreak: 2054-38, 4d.13h.52m
  urlhaus-1: 6684-1, 21h.58m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 colorBlindFriendly: true
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 871 ms (selfie)
 maxAssetCacheWait: 131 ms
popupPanel:
 blocked: 1
 network:
  baidu.com: 1
```
</details>

**Comment by mapx-** [comment]
report here:
https://github.com/cjx82630/cjxlist/issues
