### ISSUE TITLE
Updated Pinterest rule is too broad

### ISSUE THREAD

**Issue by amuhav** [uBlockOrigin/uAssets#18612]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The latest Pinterest filter is catching any pin with a capital "P", "b" and "y" in it's caption, probably because it was written to catch "Promoted by". checked the code and it does appear to be written for those three letters.

### URL(s) where the issue occurs.

https://www.pinterest.co.uk

### Ublock off:
![Pby](https://github.com/uBlockOrigin/uAssets/assets/95963549/2af39c0f-33a0-4276-9be7-d072eff3eb33)
### Ublock on:
![PbyPinsGone](https://github.com/uBlockOrigin/uAssets/assets/95963549/0adfa0b0-cb35-4d94-9ecf-ec4afa91f874)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.11h.36m
Chromium: 114
filterset (summary):
 network: 93626
 cosmetic: 39176
 scriptlet: 17662
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67057-50, 3m
  easyprivacy: 30602-54, 3m
  plowe-0: 3737-952, 3m
  ublock-badware: 7538-137, 1m
  ublock-filters: 33560-142, 1m
  ublock-privacy: 410-3, 1m
  ublock-quick-fixes: 243-17, 1m
  ublock-unbreak: 2059-34, now
  urlhaus-1: 6798-1, 22h.37m
filterset (user): [empty]
trustedset:
 added: [array of 24 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 402 ms (selfie)
 maxAssetCacheWait: 66 ms
```
</details>

**Comment by amuhav** [comment]
this doesn't solve the problem, too many false positives still getting blocked.

**Comment by amuhav** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/95963549/0f113772-1a64-4a47-bff3-30d502c7040f)

just from the sample I sent earlier, one is still blocked incorrectly. checking all my boards, there are still gaps on most of them. Without the rule going for _only_ the term "Promoted by" with the letters in that order, I think it's going to be too broad.

**Comment by amuhav** [comment]
Sorry, I should have mentioned that I tested that myself not long after my last reply. It still catches too many non-ad pins. On the board from my example, it had at least 8 missing pins, now I think it's still about 6, including the one from the example image still lol. A lot of normal pins are going to have that combination of 9 letters in it somewhere.

**Comment by mapx-** [comment]
A lot of normal pins are going to have that combination of 9 letters in it somewhere

examples ?
what board ?

**Comment by amuhav** [comment]
any board? if I go to any of my own saved boards, almost all of them are missing at least one pin when this filter is enabled. The pin I screenshotted previously is still blocked, for example. Same if I go to other people's boards, there are missing pins blocked by this rule that shouldn't be (you don't get ads on boards themselves, so any gap is a falsely blocked pin)

The specific board I was using as an example is this one, where you can scroll to see at least 6 missing pins:
https://www.pinterest.co.uk/AmunaRaikaida/aesthetics-categories/black-+-white/

but as I said, I can see it on a lot of other boards. With some captions on pins being quite long, and just by sheer coincidence, there are going to be enough that have that combination of 9 letters.

**Comment by gorhill** [comment]
> examples ?

Using the provided link, I see pages which show the issue without having to scroll -- toggle cosmetic filtering switch to see. I can get an actual link to the pages, but you can click on one of these entries:

- Yellooooow
- Dusty Pinks/Purples
- Rainbow
- Light Words

**Comment by mapx-** [comment]
with the current filter I cannot reproduce the issue.

Are you sure you updated to the last filters ?

**Comment by gorhill** [comment]
Yes, filter lists updated. I use a UK IP address. For example at the top of the _Yellooooow_ page, one of the image is captioned as:

> 62 Best Ideas she is art #quotes tattoo #tattoo #quotes #art Pinned by: www.smithgoldsmith.com

There is no "Promoted" in there, but it ends up matching your xpath conditions.

**Comment by mapx-** [comment]
still didnt find a test case but yeah I understand it (even using a uk ip)

however, could you test:

`pinterest.co.uk##[data-test-id="gestalt-avatar-svg"]:xpath('//*[(contains(text(),"P") and contains(text(),"r") and contains(text(),"o") and contains(text(),"m") and contains(text(),"o") and contains(text(),"t") and contains(text(),"e") and contains(text(),"d") and contains(text(),"b") and contains(text(),"y")) ]'):upward([data-grid-item])`

**Comment by gorhill** [comment]
Still see an issue, it's now a gray box instead of a white one:

![Screenshot from 2023-06-22 17-35-49](https://github.com/uBlockOrigin/uAssets/assets/585534/7b96bda6-646a-4346-a60a-2c9f2500b5ae)

Note that I could try investigate a solution on my side if I knew how to **get** ads, I don't see any so far. I do browse the site without an account, maybe that is why?

Also, note that you test twice for `contains(text(),"o")` in your xpath expression.

**Comment by mapx-** [comment]
I guess you need an account

**Comment by gorhill** [comment]
Note that your leading `//` means "from root DOM regardless of scope", while `/` means "from current scope".

**Comment by gorhill** [comment]
I have been trying to create an account for this site, and it just doesn't work, each time I try to fill in the required details, I click "Continue" and then I am thrown back to the home page and no account created.

**Comment by amuhav** [comment]
just tested, and this does now appear to only be blocking "Promoted By" pins. AND the images/videos of the promoted pins now seem to be cut out completely, meaning only a narrow white gap the size of the caption is left behind, rather than the large white space that used to be left when ublock blocked a promoted pin. big improvement, thank you! (I almost didn't see the gaps at first and thought pinterest just wasn't serving me ads lol)

**Comment by mapx-** [comment]
even disabling uBO I get no "promoted by" items

**Comment by amuhav** [comment]
are you in the EU by any chance? it seems the UK site is overrun by them, my friend living in the EU, however, gets none at all on the desktop or in the app, but when she visited the US she was getting the same crazy amount as me. 

You _only_ get "promoted by" pins on the home page and in searches, there are none on saved boards themselves. I don't know if you can even use the homepage or searches without an account, I think it does the same thing as facebook or twitter where it prompts you to signup/login if you try to scroll?

(side note, gorhill, are you trying to sign up whilst using Brave as your browser by any chance? I've been having a lot of problems getting through _any_ sign-up processes using it recently and have to open up Chrome every single time I want to create an account on any site. it either errors out in some way or does as you said, throws me back to the homepage or sign-up page)
