### ISSUE TITLE
work.ink: detection

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#18611]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

detection of ublock origin

### URL(s) where the issue occurs.

`https://work.ink/1P7/lins9ma6`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/57501353/bbd5d15f-439e-4366-b908-32c172cbb860)

### uBO version

1,50

### Browser name and version

chrome 116

### Settings

uBlock Origin 1.50.0:
 since: 2m
Chromium: 116
filterset (summary):
 network: 93513
 cosmetic: 39175
 scriptlet: 17662
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67057-50, now
  easyprivacy: 30602-54, now
  plowe-0: 3737-952, now
  ublock-badware: 7538-137, now
  ublock-filters: 33560-142, now
  ublock-privacy: 410-3, now
  ublock-quick-fixes: 242-17, now
  ublock-unbreak: 2059-34, now
  urlhaus-1: 6685-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 575 ms (selfie)
 maxAssetCacheWait: 320 ms

**Comment by dportvine** [comment]
Also, promo ads

<details>
<summary>Screen</summary>

![2023-06-21_215436](https://github.com/uBlockOrigin/uAssets/assets/111344219/f4061212-218d-4956-a3fc-723b347b5cb7)
</details>

**Comment by JobcenterTycoon** [comment]
Yes and steps which i can’t bypass. I don’t know if they are bypassable.

**Comment by erik9012** [comment]
Is uassets also doing bypasses for shortlink steps?

**Comment by stephenhawk8054** [comment]
> Is uassets also doing bypasses for shortlink steps?

If it's possible by using filters. If it requires complicated methods, we can't. As the anti-adb is solved now, I think we can close the issue.
