### ISSUE TITLE
thehindu.com: nuisance

### ISSUE THREAD

**Issue by Malgotra** [uBlockOrigin/uAssets#18626]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.thehindu.com/`

### Category

nuisance

### Description

Something is blocking website. Grey area.(But grey area disappear when tap on anywhere in screen).

### Other extensions used

None 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230622-204200](https://github.com/uBlockOrigin/uAssets/assets/122884037/386b182b-42d6-42ea-8d6c-e6950e64a1ea)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 18m
Firefox Mobile: 114
filterset (summary):
 network: 100533
 cosmetic: 117123
 scriptlet: 23656
 html: 1125
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 3868-89, 14m
  easylist-chat: 126-0, 14m
  fanboy-cookiemonster: 47568-280, 14m
  easylist-newsletters: 6119-13, 14m
  easylist-notifications: 2629-4, 14m
  fanboy-social: 16092-6, 14m
  ublock-annoyances: 5196-39, 14m
 default:
  user-filters: 3-0, never
  ublock-filters: 34714-112, 17m
  ublock-badware: 7529-1, 17m
  ublock-privacy: 452-0, 17m
  ublock-unbreak: 2089-0, 17m
  ublock-quick-fixes: 253-0, 17m
  adguard-mobile: 8287-108, 18m
  easylist: 67135-784, 17m
  easyprivacy: 30603-709, 17m
  urlhaus-1: 7381-1, 17m
  plowe-0: 3737-1, 17m
filterset (user): [array of 3 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4199 ms
 maxAssetCacheWait: 2279 ms
popupPanel:
 blocked: 16
 network:
  cloudflareinsights.com: 2
  cxense.com: 3
  google-analytics.com: 1
  google.com: 4
  googletagmanager.com: 1
  npttech.com: 1
  piano.io: 2
  scorecardresearch.com: 1
  site24x7rum.in: 1
 extended:
  ##.share-article
  ##.dfp-ad
  ###teconsent
  ##.back-to-top:not(body):not(html)
  ###consent_blackbar
  ##.flooting-ad
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, window.Adblock, false)
  ##+js(set-constant, window.isNonSubcribed, false)
  ##+js(set-constant, Adblock, false)
```
</details>

**Comment by mapx-** [comment]
add

`thehindu.com###gsi_overlay`

(mobile) @ryanbr

**Comment by ghajini** [comment]
It occurs with default settings, firefox android
