### ISSUE TITLE
various shorteners

### ISSUE THREAD

**Issue by mild787** [uBlockOrigin/uAssets#18621]
I have issue for this,  for phineypet domain. not detected, but for other domains `allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net,batmanfactor.com,talkforfitness.com,` the current condition is detected. Maybe the DEV has updated. any ideas for the problem?

_Originally posted by @mild787 in https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-6176475_

**Comment by mapx-** [comment]
continue only on https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by mild787** [comment]
continuing in the column discuss varioust shortener will solve the problem? and anyone help solve it? It's been a week, no one has helped solve it. Please help. Thank You.
