### ISSUE TITLE
google.com: ads

### ISSUE THREAD

**Issue by RealMrBacon** [uBlockOrigin/uAssets#18628]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.google.com/search`

### Category

Sponsored Ads

### Description

When searching anything up, there are still sponsored ads even with all filter lists updated and turned on.

### Other extensions used

none

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/74677387/9680fba7-7fe4-4309-8af4-7cd16ba2798f

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 299833
 cosmetic: 224324
 scriptlet: 41014
 html: 0
listset (total-discarded, last-updated): 
 added: 
  adguard-cookies: 26037-29, 43m
  adguard-generic: 71891-454, 43m
  adguard-mobile: 8287-44, 43m
  adguard-mobile-app-banners: 4349-5, 43m
  adguard-other-annoyances: 13057-7, 43m
  adguard-popup-overlays: 22748-68, 43m
  adguard-social: 20681-878, 43m
  adguard-spyware: 70128-1217, 43m
  adguard-spyware-url: 1094-3, 43m
  adguard-widgets: 2181-6, 43m
  block-lan: 47-0, 43m
  curben-phishing: 109830-7, 43m
  curben-pup: 189-0, 43m
  dpollock-0: 11524-250, 43m
  easylist-annoyances: 3868-239, 43m
  easylist-chat: 126-9, 43m
  easylist-newsletters: 6119-350, 43m
  easylist-notifications: 2629-1426, 43m
  fanboy-cookiemonster: 47568-3768, 43m
  fanboy-social: 16092-686, 43m
  [2 lists not shown]: [too many]
 default: 
  user-filters: 0-0, never
  easylist: 67135-1255, 43m
  easyprivacy: 30603-13635, 43m
  plowe-0: 3737-1457, 43m
  ublock-badware: 7543-399, 43m
  ublock-filters: 33572-4163, 43m
  ublock-privacy: 411-63, 43m
  ublock-quick-fixes: 251-19, 43m
  ublock-unbreak: 2061-140, 43m
  urlhaus-1: 7381-3, 43m
filterset (user): [empty]
trustedset: 
 removed: 
  chrome-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1788 ms
 maxAssetCacheWait: 550 ms
popupPanel: 
 blocked: 10
 network: 
  google.com: 1
  doubleclick.net: 1
  youtube.com: 8
```
</details>

**Comment by mapx-** [comment]
> uBlock Origin: 1.49.2

- update uBO to the last version (`1.50.0`)
- force update all the lists
- disable any other extension
- test again

**Comment by krystian3w** [comment]
Bardware in first row under input:

```adb
google.*##a[href^="/search?q="][href*="&uds="]
```
