### ISSUE TITLE
truckinginfo.com: ads

### ISSUE THREAD

**Issue by jsmorada** [uBlockOrigin/uAssets#18622]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.truckinginfo.com/10200970/rand-mcnally-publishes-43rd-edition-of-the-motor-carriers-road-atlas?utm_source=newsletter&utm_medium=email&utm_campaign=20230622_1705:649360cc8ce10057230ead6c:ot_NL-HDT-Thursday-20230622&omid=1009550462&cid=63466229565ddfa6d00d88f9`

### Category

ads

### Description

There is an ad video that, although it won't play, still shows on the screen. Additionally, there is a floating element on the right that can be blocked using the element picker mode but reappears after reloading the page.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.23h.12m
Firefox: 114
filterset (summary):
 network: 214207
 cosmetic: 183290
 scriptlet: 25835
 html: 1124
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68364-68364, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91602-91596, now
  curben-phishing: 109830-40, now
  adguard-social: 20671-816, now
  fanboy-cookiemonster: 47563-3808, now
  fanboy-social: 16092-8, now
  ublock-annoyances: 5204-16, now
  adguard-cookies: 26035-57, now
  adguard-popup-overlays: 22744-1436, now
  adguard-mobile-app-banners: 4347-1049, now
  adguard-other-annoyances: 13057-296, now
  adguard-widgets: 2181-0, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 174-8, never
  ublock-filters: 34445-449, now
  ublock-badware: 7545-0, now
  ublock-privacy: 452-0, now
  ublock-unbreak: 2084-0, now
  ublock-quick-fixes: 253-0, now
  easylist: 67135-814, now
  easyprivacy: 30603-706, now
  urlhaus-1: 7381-1, now
  plowe-0: 3737-2, now
filterset (user): [array of 174 redacted]
trustedset:
 added: [array of 17 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 120
 autoUpdateDelayAfterLaunch: 180
 autoUpdatePeriod: 7
 selfieAfter: 3
supportStats:
 allReadyAfter: 5314 ms (selfie)
 maxAssetCacheWait: 1147 ms
popupPanel:
 blocked: 22
 no-cosmetic-filtering: true
 network:
  truckinginfo.com: 7
  addthis.com: 1
  cloudflareinsights.com: 2
  facebook.net: 1
  google-analytics.com: 2
  googlesyndication.com: 6
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`truckinginfo.com##.incontent02Ad`

floating element ? meaning the newsletter ?

@ryanbr
