### ISSUE TITLE
economist.co.kr: ads

### ISSUE THREAD

**Issue by sofhvofw** [uBlockOrigin/uAssets#18627]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad not blocked

### URL(s) where the issue occurs.

`https://economist.co.kr/article/view/ecn202303300057?s=31`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/137440189/2a47c84b-ab69-4c6e-932d-2a47d0c0e052

Note: yes, the ad is partially cut off

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.6h.7m
Firefox: 112
filterset (summary):
 network: 191478
 cosmetic: 285814
 scriptlet: 30542
 html: 1210
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68287-4788, 1d.22h.3m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91744-65016, 18h.38m
  fanboy-cookiemonster: 47469-335, 3d.21h.28m
  ublock-annoyances: 5073-16, 5h.5m
  ara-0: 2396-6, 4h.54m
  BGR-0: 1091-11, 2d.23h.21m
  CHN-0: 26136-146, 2d.23h.16m
  CZE-0: 746-6, 4h.56m
  DEU-0: 6917-15, 4h.59m
  EST-0: 461-35, 4h.51m
  FIN-0: 2212-1, 1d.22h.1m
  FRA-0: 28328-542, 2d.5h.58m
  [28 lists not shown]: [too many]
 default:
  user-filters: 18-0, never
  ublock-filters: 34437-318, 2d.23h.19m
  ublock-badware: 7518-1, 2d.23h.18m
  ublock-privacy: 451-0, 18h.37m
  ublock-unbreak: 2069-23, 2d.23h.17m
  easylist: 66657-1203, 4d.14h.3m
  easyprivacy: 30798-1, 4d.14h.2m
  urlhaus-1: 7381-1, 4h.53m
  plowe-0: 3734-587, 10d.18h.54m
  ublock-quick-fixes: 253-1, 2m
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1683 ms (selfie)
 maxAssetCacheWait: 276 ms
```
</details>

**Comment by JobcenterTycoon** [comment]
The issue got fixed, force update the filterlists to get the fix directly.

PS: The best would be to only activate the regional filterlists of languages that you actually speak. Activating to many filterlists can result in undefined issues or performance issues.
