### ISSUE TITLE
indiadesire.com: breakage

### ISSUE THREAD

**Issue by mikeje** [uBlockOrigin/uAssets#18623]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://indiadesire.com/Redirect?redirectpid1=INVFT7QPHPGHK7PE&store=flipkart`

### Category

breakage

### Description

This tab closes automatically without actually redirecting to the main site. and when i turnoff Ublock origin, the redirection works perfectly.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 8d.10h.9m
Chromium: 113
filterset (summary):
 network: 98334
 cosmetic: 110171
 scriptlet: 23117
 html: 0
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91597-15551, 3h.20m
  fanboy-cookiemonster: 47452-47437, 6d.1h.23m
  ublock-annoyances: 5068-83, 6d.1h.22m
 default:
  user-filters: 544-9, never
  easylist: 67023-82, 1h.20m
  easyprivacy: 30603-241, 1h.19m
  plowe-0: 3736-952, 6d.1h.23m
  ublock-badware: 7533-137, 23h.55m
  ublock-filters: 33559-173, 23h.54m
  ublock-privacy: 396-4, 6d.1h.22m
  ublock-quick-fixes: 243-17, 9h.22m
  ublock-unbreak: 2059-38, 23h.53m
  urlhaus-1: 6685-1, 19h.51m
filterset (user): [array of 547 redacted]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 102064 ms (selfie)
 maxAssetCacheWait: 517 ms
popupPanel:
 blocked: 1
 network:
  scriptcdn.net: 1
```
</details>

**Comment by gorhill** [comment]
When I paste your link `https://indiadesire.com/Redirect?redirectpid1=INVFT7QPHPGHK7PE&store=flipkart` in the address bar, I am properly redirected to `https://www.flipkart.com/aquire-extra-large-pvc-vinyl-sticker/p/...`, using default settings and default lists + the annoyance-related lists you enabled.

You have 547 custom filters, you will have to investigate on your side what is causing your issue, use the logger to help you investigate, it's going to show you which filter is causing the tab to be closed.

**Comment by mapx-** [comment]
To get the popup (and the closed page) put the link in some google search page, right click that link and you'll reproduce the issue.

that link redirects to 
    https://www.flipkart.com/aquire-extra-large-pvc-vinyl-sticker/p/itme4vr5zgpgyfud?pid=INVFT7QPHPGHK7PE&linkCode=sl2&ie=UTF8&keywords=indiadesire&qihd=1566472976&s=dealfromindiadesire&zerotag=flipkartindia&ascutog=indiadesire&affid=admitad&affExtParam1=397306&affExtParam2=c415b5bd97a514a5102ce9766dcb4fbb

containing 
`&affid=admitad`

this filter seems working fine

`||flipkart.com/*affid$removeparam=affid`

**Comment by gorhill** [comment]
> put the link in some google search page

I see, actually just right-clicking here on `https://indiadesire.com/Redirect?redirectpid1=INVFT7QPHPGHK7PE&store=flipkart` also reproduce the issue.

**Comment by mapx-** [comment]
mmhmm, right

**Comment by gorhill** [comment]
Maybe if we knew where the link was hosted we could figure another angle for a solution. It's probably [in there somewhere](https://indiadesire.com/), but where exactly?

**Comment by mapx-** [comment]
`https://indiadesire.com/Redirect?redirectpid1=INVFT7QPHPGHK7PE&store=flipkart` 

goes directly to

`https://ad.admitad.com/g/rb1qie435beabd7c8628a80d05f527/?ulp=https%3a%2f%2fwww.flipkart.com%2faquire-extra-large-pvc-vinyl-sticker%2fp%2fitme4vr5zgpgyfud%3fpid%3dINVFT7QPHPGHK7PE%26linkCode%3dsl2%26ie%3dUTF8%26keywords%3dindiadesire%26qihd%3d1566472976%26s%3ddealfromindiadesire%26zerotag%3dflipkartindia%26ascutog%3dindiadesire%26`

and - when opened normally - redirects to 
`https://www.flipkart.com/aquire-extra-large-pvc-vinyl-sticker/p/itme4vr5zgpgyfud`

**Comment by gorhill** [comment]
How about:

    indiadesire.com##+js(href-sanitizer, a[href^="https://indiadesire.com/Redirect?redirect="], ?redirect)

**Comment by gorhill** [comment]
Looks like this is the only solution:

    @@||ad.admitad.com^$popup,domain=indiadesire.com

**Comment by mapx-** [comment]
at least in chrome does not work your exception

working one
`@@||ad.admitad.com/*?ulp=*.flipkart.com$popup`

**Comment by gorhill** [comment]
I did test in Chromium. I used the site itself to test since this is where the links are going to be clicked.

**Comment by mapx-** [comment]
I cannot see how could work your filter above.

I copied the indiadesire link in google, right click:

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/a9251c1c-1d64-47bc-9c90-4a4e244cbea0)

**Comment by gorhill** [comment]
I don't think we should try to fix the (artificial) Google case, my understanding is that OP was browsing items on `indiadesire.com`, clicked en entry, and the newly opened tab was closed. We should fix only that one case otherwise we open the door for `ad.admitad.com` popups to no longer be blocked everywhere as intended by EasyList.

I could reproduce the popup issue while clicking items at `indiadesire.com`, so this is certainly what is being reported.

**Comment by mapx-** [comment]
ok, replaced
