### ISSUE TITLE
panflix.com.br: breakage

### ISSUE THREAD

**Issue by ssteel3** [uBlockOrigin/uAssets#18625]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.panflix.com.br/ao_vivo`

### Category

breakage

### Description

youtube video stream wont display

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 10d.15h.5m
Chromium: 112
filterset (summary):
 network: 95701
 cosmetic: 42675
 scriptlet: 17983
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 11-3, never
  easylist: 67135-50, now
  easyprivacy: 30603-54, now
  plowe-0: 3737-953, now
  spa-1: 5294-69, now
  ublock-badware: 7543-137, now
  ublock-filters: 33572-166, now
  ublock-privacy: 411-3, now
  ublock-quick-fixes: 253-17, now
  ublock-unbreak: 2061-36, now
  urlhaus-1: 7381-1, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 22 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 367 ms (selfie)
 maxAssetCacheWait: 110 ms
popupPanel:
 blocked: 10
 network:
  doubleclick.net: 1
  googleads.github.io: 6
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
```
</details>

**Comment by ssteel3** [comment]
Hi.
Adding this filter didn't solve the issue for me.

**Comment by gorhill** [comment]
How about:

    @@||imasdk.googleapis.com/js/sdkloader/ima3.js$3p,script,domain=panflix.com.br

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtag/js$script,domain=panflix.com.br`

@Alex-302

**Comment by ssteel3** [comment]
> add
> 
> `@@||googletagmanager.com/gtag/js$script,domain=panflix.com.br`
> 
> @Alex-302

That did it, thanks!

**Comment by gorhill** [comment]
@ssteel3 Just to be sure, could you try with this filter instead (I don't have an account with the site, can't test this myself) -- replace the filter above with:

    ||googletagmanager.com/gtag/js$script,redirect-rule,domain=panflix.com.br

**Comment by ssteel3** [comment]
> @ssteel3 Just to be sure, could you try with this filter instead (I don't have an account with the site, can't test this myself) -- replace the filter above with:
> 
> ```
> ||googletagmanager.com/gtag/js$script,redirect-rule,domain=panflix.com.br
> ```

This one didn't work.
