### ISSUE TITLE
nytimes.com: ads

### ISSUE THREAD

**Issue by Jimmy59601** [uBlockOrigin/uAssets#18632]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nytimes.com/2023/06/22/nyregion/george-santos-bail.html`

### Category

ads

### Description

Although I successfully blocked the ads at the bottom of the page with the element picker, a blank box  still appears at the bottom of the page. I tried using the element picker on the box, but it doesn't prevent it from opening. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/uBlockOrigin/uAssets/assets/56486676/db4ad30a-0d89-48cf-ab7e-0ea54e530240)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.3h
Chromium: 114
filterset (summary):
 network: 94305
 cosmetic: 39209
 scriptlet: 17673
 html: 0
listset (total-discarded, last-updated):
 added:
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, now
 default:
  user-filters: 33-0, never
  easylist: 67135-50, now
  easyprivacy: 30603-54, now
  plowe-0: 3737-953, now
  ublock-badware: 7543-137, now
  ublock-filters: 33576-143, now
  ublock-privacy: 411-3, now
  ublock-quick-fixes: 251-17, now
  ublock-unbreak: 2061-35, now
  urlhaus-1: 7381-1, now
filterset (user): [array of 33 redacted]
trustedset:
 added: [array of 31 redacted]
switchRuleset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 662 ms (selfie)
 maxAssetCacheWait: 214 ms
popupPanel:
 blocked: 11
 network:
  nytimes.com: 7
  amazon-adsystem.com: 1
  geoedge.be: 1
  googletagmanager.com: 1
  nyt.com: 1
 extended:
  ###story-ad-1-wrapper
  ###story-ad-2-wrapper
  ###story-ad-3-wrapper
  ##div.e1ejehf01.css-tb7453:nth-of-type(2)
  ##div.e1ejehf01.css-tb7453:nth-of-type(1)
  ##.css-1qw5f1g
  ##.css-13321i0
  ##.e1ejehf00.css-18mm7rz
  ##.standardDockLayout
  ##[id^="story-ad"][id$="wrapper"]
  ###bottom-wrapper
  ###top-wrapper
  ##.ad
```
</details>

**Comment by mapx-** [comment]
test for breakage

`nytimes.com##[data-testid="site-index"]`

**Comment by Jimmy59601** [comment]
Works great! Thank you.
Jimmy
    On Thursday, June 22, 2023 at 12:59:55 PM PDT, mapx ***@***.***> wrote:  
 
 


test for breakage

nytimes.com##[data-testid="site-index"]

**Comment by Jimmy59601** [comment]
Thanks!
    On Thursday, December 12, 2024 at 11:06:10 AM PST, MasterKia ***@***.***> wrote:  
 
 

nytimes.com##div[class^="Ad-module_adContainer"]
https://www.nytimes.com/games/wordle/index.html

@ryanbr
