### ISSUE TITLE
forums.guru3d.com: breakage

### ISSUE THREAD

**Issue by PlaceboPRS** [uBlockOrigin/uAssets#18639]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://forums.guru3d.com/forums/`

### Category

breakage

### Description

For some reason in the last one or two days an issue arose whereby when the page is fully loaded keyboard shortcuts to jump up/down the page with page up/page down and go to the top with Home stop working, still works fine on other websites/forums it's just with guru3d as far as I can see :(

### Other extensions used

Autofill–11.6.1
Bing–1.5
Bing Chat for All Browsers–1.0.7
Bitwarden - Free Password Manager–2023.5.0
Dark Reader–4.9.63
Download Manager (S3)–5.12
DuckDuckGo–1.4
eBay–1.4
F.B Purity - Cleans up Facebook–36.8.0.0
Google–1.4
Greasemonkey–4.11
IDM Integration Module–6.41.12
Keepa - Amazon Price Tracker–4.1
MyJDownloader Browser –3.3.20
Network Sniffer–1.0.9
New Tab Override–15.1.1
Notifier for Gmail™–1.0.5
Open With–7.2.6
PureVPN: VPN Proxy to Unblock Internet Privately–3.14.0
Read Aloud: A Text to Speech Voice Reader–1.63.0
RevEye Reverse Image Search–1.4.8
S3.Translator–6.19
Snap Links–3.1.11
Tampermonkey–4.18.1
The Stream Detector–2.11.4
uBlock Origin–1.50.0
Undo Closed Tabs Button–0.1.9
Universal Bypass–13.15.2.1
Video DownloadHelper–7.6.6
Video Quality Settings for YouTube (HD/4K)–2.0.0
WebChatGPT: ChatGPT with internet access–3.3.0
Wikipedia (en)–1.3

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.18h.7m
Firefox: 114
filterset (summary):
 network: 81061
 cosmetic: 203150
 scriptlet: 36745
 html: 889
listset (total-discarded, last-updated):
 removed:
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  easyprivacy: null
  plowe-0: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68250-5928, 6m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91625-15665, 6m
  adguard-generic: 71896-488, 6m
  adguard-mobile: 8287-10, 6m
 default:
  user-filters: 66-9, never
  ublock-filters: 34435-3652, 6m
  easylist: 67156-997, 6m
  urlhaus-1: 7069-0, 6m
filterset (user): [array of 68 redacted]
trustedset:
 added: [array of 245 redacted]
 removed:
  about-scheme
  edge-scheme
switchRuleset:
 added: [array of 14 redacted]
urlRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 732 ms
 maxAssetCacheWait: 326 ms
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
  googletagservices.com: 1
 extended:
  ##ins.adsbygoogle
  ##body:style(overflow: auto !important;)
```
</details>

**Comment by mapx-** [comment]
```
removed:
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  easyprivacy: null
  plowe-0: null
```

- reinstall uBO and force update all lists
- do not disable important lists in uBO
- disable any other addon
- test again

**Comment by PlaceboPRS** [comment]
A reinstall seems to have fixed it right up, thank you.
