### ISSUE TITLE
suttonquebec.com: breakage

### ISSUE THREAD

**Issue by mikhoul** [uBlockOrigin/uAssets#18644]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.suttonquebec.com/fr/inscription/appartement-a-vendre-5690-rue-donais-app-6-trois-rivieres.html?noInscription=24677955&centris=1&typeInscription=1`

### Category

breakage

### Description

The image carousel viewer don't pop up when you click on images if UBO is enabled.

Regards.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 14d.15h.15m
Chromium: 112
filterset (summary):
 network: 140783
 cosmetic: 214259
 scriptlet: 40329
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68250-97, 11h.2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91411-20877, 4d.12h.5m
  FRA-0: 28328-70, 1d.23h.2m
  adguard-generic: 71839-757, 1d.20h.56m
  adguard-mobile: 8286-58, 1d.23h.1m
  fanboy-cookiemonster: 47463-47459, 3d.17h.22m
  ublock-annoyances: 5098-279, 3d.17h.21m
 default:
  user-filters: 5-0, never
  easylist: 66617-1119, 4d.12h.8m
  easyprivacy: 30600-626, 3d.17h.20m
  plowe-0: 3736-1062, 6d.9h.10m
  ublock-badware: 7529-379, 1d.20h.57m
  ublock-filters: 33560-4183, 15h.59m
  ublock-privacy: 406-5, 3d.17h.23m
  ublock-quick-fixes: 283-20, 2h.25m
  ublock-unbreak: 2049-98, 1d.20h.58m
  urlhaus-1: 7381-1, 21h.15m
filterset (user): [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7516 ms (selfie)
 maxAssetCacheWait: 1475 ms
popupPanel:
 blocked: 48
 network:
  1rx.io: 2
  audrte.com: 2
  clarity.ms: 4
  contextweb.com: 2
  criteo.com: 2
  doubleclick.net: 3
  doubleverify.com: 2
  everesttech.net: 2
  google.com: 1
  googlesyndication.com: 6
  googletagservices.com: 1
  id5-sync.com: 2
  loopme.me: 2
  omnitagjs.com: 2
  quantserve.com: 2
  rlcdn.com: 2
  rqtrk.eu: 2
  scorecardresearch.com: 1
  sharethrough.com: 2
  smaato.net: 2
  tidaltv.com: 2
  zemanta.com: 2
```
</details>

**Comment by gorhill** [comment]
Broken by the filter `||static.addtoany.com^$3p` in _AdGuard – Social Media_, need:

    @@||static.addtoany.com/menu/page.js$script,domain=suttonquebec.com

**Comment by gorhill** [comment]
cc @ryanbr

**Comment by stephenhawk8054** [comment]
@Alex-302
