### ISSUE TITLE
[nsfw] view345.com: detection

### ISSUE THREAD

**Issue by xeunha** [uBlockOrigin/uAssets#18646]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://view345.com/imdeyxoe2do3.html`

### Category

detection

### Description

The video player detects uBlock Origin. the detection banner is contained within the video player.

### Other extensions used

Thunder Download Manager
CocoCut Video Downloader
LiveCat
Popup Blocker (Strict)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 18h.5m
Chromium: 115
filterset (summary):
 network: 299596
 cosmetic: 224353
 scriptlet: 41034
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26081-29, 3m
  adguard-generic: 71916-454, 3m
  adguard-mobile: 8289-44, 3m
  adguard-mobile-app-banners: 4355-5, 3m
  adguard-other-annoyances: 12941-7, 3m
  adguard-popup-overlays: 22752-68, 3m
  adguard-social: 20688-878, 3m
  adguard-spyware: 70136-1217, 3m
  adguard-spyware-url: 1095-3, 3m
  adguard-widgets: 2182-6, 3m
  block-lan: 47-0, 3m
  curben-phishing: 110196-7, 3m
  [10 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 67240-1262, 3m
  easyprivacy: 30603-13637, 3m
  plowe-0: 3737-1458, 3m
  ublock-badware: 7570-399, 3m
  ublock-filters: 33571-4155, 3m
  ublock-privacy: 411-63, 3m
  ublock-quick-fixes: 268-21, 3m
  ublock-unbreak: 2061-140, 3m
  urlhaus-1: 6634-2, 3m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1759 ms (selfie)
 maxAssetCacheWait: 267 ms
popupPanel:
 blocked: 4
 network:
  dalyai.com: 1
  googletagmanager.com: 1
  rinserbefore.com: 1
  yandex.ru: 1
 extended:
  ##+js(abort-on-property-read, __Y)
  ##+js(abort-on-property-read, mm)
  ##+js(abort-on-property-read, DoodPop)
```
</details>

**Comment by mapx-** [comment]
- reset uBO to default settings / lists, update the nall the lists, do not add other lists
- disable all other extensions
- test again
