### ISSUE TITLE
[nsfw] javnow.com: popups

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#18640]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.javnow.com/abba-355/`

### Category

popups

### Description

Video not playing and pop-ups

### Other extensions used

Violentmonkey 
Libredirect 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.9h.39m
Firefox Mobile: 114
filterset (summary):
 network: 95613
 cosmetic: 29240
 scriptlet: 17685
 html: 947
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34670-297, 4d.13h.17m
  ublock-badware: 7502-0, 4d.13h.16m
  ublock-privacy: 446-1, 4d.13h.15m
  ublock-unbreak: 2074-1, 4d.13h.14m
  ublock-quick-fixes: 253-0, 10h.29m
  adguard-mobile: 8287-121, 12h.34m
  easylist: 67135-17409, 12h.32m
  easyprivacy: 30603-618, 12h.31m
  urlhaus-1: 7381-1, 12h.30m
  plowe-0: 3735-2, 4d.13h.8m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10845 ms (selfie)
 maxAssetCacheWait: 634 ms
popupPanel:
 blocked: 1
 network:
  cloudflareinsights.com: 1
```
</details>

**Comment by ghajini** [comment]
site issue,there is no real player there

**Comment by mapx-** [comment]
add
`javnow.com##[href="https://www.javnow.com/visit/stripchat/"]`

`href="https://www.javnow.com/visit/stripchat/` redirect to `stripchat`

**Comment by mapx-** [comment]
@ryanbr
