### ISSUE TITLE
sdrplay.com: breakage

### ISSUE THREAD

**Issue by RubenKelevra** [uBlockOrigin/uAssets#18645]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sdrplay.com/sdruno/`

### Category

breakage

### Description

Download link does nothing

### Other extensions used

No factor

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.20h.39m
Firefox: 114
filterset (summary):
 network: 244605
 cosmetic: 189528
 scriptlet: 27025
 html: 1137
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68287-6472, 2d.18h.55m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91376-63016, 6d.18h.59m
  adguard-spyware-url: 1094-5, 20h.28m
  block-lan: 47-0, 3d.20h.12m
  curben-phishing: 109830-41, 18h.4m
  curben-pup: 189-0, 18h.5m
  fanboy-cookiemonster: 47468-263, 4d.17m
  ublock-annoyances: 5065-7, 4d.18m
  dpollock-0: 11522-470, 6d.19h.2m
  RUS-0: 39483-175, 16h.3m
 default:
  user-filters: 1-0, never
  ublock-filters: 34433-70, 22h.31m
  ublock-badware: 7545-0, 22h.30m
  ublock-privacy: 446-0, 4d.6h.20m
  ublock-unbreak: 2084-1, 22h.29m
  ublock-quick-fixes: 242-0, 2h.31m
  easylist: 66858-935, 2d.16h.54m
  easyprivacy: 30602-688, 2d.1h.14m
  urlhaus-1: 7381-1, 18h.6m
  plowe-0: 3736-2, 6d.19h.4m
  DEU-0: 6920-4, 18h.7m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
hostRuleset:
 added: [array of 10 redacted]
userSettings:
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 hyperlinkAuditingDisabled: false
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2252 ms (selfie)
 maxAssetCacheWait: 760 ms
popupPanel:
 blocked: 2
 network:
  sdrplay.com: 2
 extended:
  ##.social-widget
  ##.social-link-item
  ##.grecaptcha-badge
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by gorhill** [comment]
Broken by `/pum-site-scripts.` in _EasyList – Cookie Notices_, need:

    @@||sdrplay.com^*/pum-site-scripts.js$script,1p

**Comment by gorhill** [comment]
cc @ryanbr
