### ISSUE TITLE
techcyan.com: detection

### ISSUE THREAD

**Issue by ShubhamtheSRL** [uBlockOrigin/uAssets#18647]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://techcyan.com/prosimo-multicloud-networking/`

### Category

detection

### Description

Detect as ad blocker and says to disable it

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 5h.54m
Firefox Mobile: 114
filterset (summary):
 network: 94940
 cosmetic: 29259
 scriptlet: 17696
 html: 955
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34703-305, 35m
  ublock-badware: 7539-0, 35m
  ublock-privacy: 452-1, 35m
  ublock-unbreak: 2091-1, 35m
  ublock-quick-fixes: 262-0, 35m
  adguard-mobile: 8286-121, 5h.54m
  easylist: 67156-17409, 35m
  easyprivacy: 30603-620, 35m
  urlhaus-1: 6634-0, 35m
  plowe-0: 3737-2, 35m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 901 ms
 maxAssetCacheWait: 338 ms
popupPanel:
 blocked: 10
 network:
  doubleclick.net: 7
  googletagmanager.com: 1
  wp.com: 2
 extended:
  ##a[href*=".click"]
  ##.disadb
  ##body:style(overflow: visible !important;)
```
</details>

**Comment by gorhill** [comment]
Can't see detection, using default settings/lists. If we can't reproduce, we can't fix, so you will have to tell us how to reproduce.

**Comment by mapx-** [comment]
@ShubhamtheSRL you didn't provide the shortener link.
