### ISSUE TITLE
proshop.no: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18643]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.proshop.no/Mobiltelefoner/Xiaomi-POCO-F5-5G-256GB12GB-Blue/3156675`

### Category

nuisance

### Description

In the bottom left corner it pop-up an ad to win prices. I have adguard - ads and easyList - ads enabled. I also see ads about buying Sony products on both left and right side.

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19490515/ef126f26-ced4-4522-bab3-b32fb6e75e69)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.12h.47m
Firefox: 114
filterset (summary):
 network: 120827
 cosmetic: 154311
 scriptlet: 38042
 html: 1121
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2226-0, 20h.3m
  adguard-generic: 71860-5413, 1d.17h.31m
  block-lan: 47-0, 1d.17h.36m
  fanboy-cookiemonster: 62354-15086, 2d.23h.16m
  fanboy-social: 16084-2, 2d.23h.15m
  ublock-annoyances: 5065-7, 2d.23h.14m
  NOR-0: 3212-11, 20h.4m
  adguard-popup-overlays: 22737-248, 1d.17h.37m
 default:
  user-filters: 3-0, never
  ublock-filters: 34430-129, 2d.23h.28m
  ublock-badware: 7531-1, 2d.23h.26m
  ublock-privacy: 447-2, 2d.23h.25m
  ublock-unbreak: 2069-0, 2d.23h.24m
  ublock-quick-fixes: 262-0, 7h.53m
  easylist: 66856-760, 2d.23h.21m
  easyprivacy: 30598-613, 2d.23h.19m
  urlhaus-1: 7381-1, 20h.5m
  plowe-0: 3735-1, 2d.23h.13m
filterset (user): [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 648 ms (selfie)
 maxAssetCacheWait: 223 ms
popupPanel:
 blocked: 24
 network:
  proshop.no: 2
  1worldsync.com: 2
  cloudflareinsights.com: 2
  facebook.net: 1
  flix360.com: 2
  flix360.io: 1
  flixcar.com: 2
  googletagmanager.com: 1
  klaviyo.com: 2
  leadfamly.com: 6
  msecnd.net: 1
  sentry.io: 2
 extended:
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by gorhill** [comment]
It's self-promotion, the _DELTA HER_ link leads to `https://game.proshop.no/proshop-sommer-2023-no`, and [as per policy](https://easylist.to/pages/policy.html):

> Self-promotion (any type of advertising that promotes goods or services that are owned or operated by the domain owner and doesn’t get commercially compensated for by third parties (examples can include new features, new posts, newsletters, subscriptions to printed media products, merchandise etc.)) won't be targeted directly.
