### ISSUE TITLE
neoseeker.com: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18641]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Anti-AdBlock message annoyance
Originally reported here: https://github.com/easylist/easylist/issues/16410

I think `##.ads-box` could be causing this.

I fixed it with these filters:
`@@||neoseeker.com^$generichide`
`neoseeker.com##ins.adsbygoogle`
`neoseeker.com##.section-ad`

### URL(s) where the issue occurs.

`https://www.neoseeker.com/star-wars-jedi-survivor/walkthrough`

### Screenshot(s)

![Screenshot from 2023-06-23 03-26-38](https://github.com/uBlockOrigin/uAssets/assets/89158249/7c72cc7c-c0f8-4457-b0de-ccc52a557fd6)

### uBO version

v1.50.1b5

### Browser name and version

Firefox 114.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by dportvine** [comment]
Soft anti-adblock, why not `neoseeker.com##+js(nostif, 100)` or `neoseeker.com##+js(acs, $, whetherdo)`?
