### ISSUE TITLE
viprow.nu: breakage

### ISSUE THREAD

**Issue by usernamaewa** [uBlockOrigin/uAssets#18652]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.viprow.nu/motogp-netherlands-gp-motoe-race-2-online-stream-2`

### Category

breakage

### Description

Link 1 to 8 as shown in the screenshot is not working when clicked when UBO (purged, restored to default settings, and updated) active.

### Other extensions used

_none_

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</detail
![Screenshot link](https://github.com/uBlockOrigin/uAssets/assets/11241668/35505da5-fa21-46a7-a068-6b9bc18a23ea)

![Screenshot (636)](https://github.com/uBlockOrigin/uAssets/assets/11241668/3de7b3ee-c143-4c1c-98dc-d69d271ceb5f)
s>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b5
Firefox: 116
filterset (summary):
 network: 93802
 cosmetic: 39180
 scriptlet: 17679
 html: 955
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34450-55, now
  ublock-badware: 7572-0, now
  ublock-privacy: 452-0, now
  ublock-unbreak: 2086-0, now
  ublock-quick-fixes: 267-0, now
  easylist: 67306-684, now
  easyprivacy: 30603-653, now
  urlhaus-1: 6691-0, now
  plowe-0: 3737-2, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2470 ms
 maxAssetCacheWait: 20 ms
popupPanel:
 blocked: 15
 network:
  alwhichhereallyw.com: 4
  dlem1deojpcg7.cloudfront.net: 1
  glyphsmahajan.com: 1
  googletagmanager.com: 1
  hubty.network: 3
  meoneinthew.com: 1
  pogothere.xyz: 4
 extended:
  ##.position-absolute
  ##+js(set-constant, path, '')
  ##+js(abort-current-script, setTimeout, admc)
  ##+js(abort-on-property-write, _pop)
  ##+js(no-window-open-if, //)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(set-constant, attachEvent, trueFunc)
  ##+js(no-setInterval-if, debug)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(no-window-open-if)
  ##+js(abort-current-script, JSON, break;case)
```
</details>

**Comment by mapx-** [comment]
No issue on my end, tested firefox / chrome.

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by usernamaewa** [comment]
Ok, sorry for the trouble, and thanks, solved now.
