### ISSUE TITLE
epson.ca: breakage

### ISSUE THREAD

**Issue by Linxgos** [uBlockOrigin/uAssets#18658]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://epson.ca/Support/Printers/All-In-Ones/WorkForce-Series/Epson-WorkForce-WF-7620/s/SPT_C11CC97201`

### Category

breakage

### Description

Page should show menu containing drivers and does when uBO is off but does not when uBO is on

### Other extensions used

I use localCDN but verified that it was not causing the issue by turning it off

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 12d.1h.24m
Firefox: 114
filterset (summary):
 network: 358258
 cosmetic: 249686
 scriptlet: 44138
 html: 1143
listset (total-discarded, last-updated):
 added:
  https://github.com/hoshsadiq/adblock-nocoin-list/raw/master/nocoin.txt: 665-0, 5m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 962-0, 4m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2227-0, 5m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1917-15, 5m
  adguard-generic: 71916-6669, 5m
  adguard-mobile: 8290-160, 5m
  adguard-spyware-url: 1095-145, 5m
  block-lan: 47-0, 5m
  curben-phishing: 111976-42, 5m
  curben-pup: 189-0, 5m
  fanboy-thirdparty_social: 68-0, 5m
  fanboy-cookiemonster: 47601-3812, 5m
  [18 lists not shown]: [too many]
 default:
  user-filters: 23-0, never
  ublock-filters: 34457-592, 5m
  ublock-badware: 7587-1, 5m
  ublock-privacy: 452-5, 5m
  ublock-unbreak: 2086-1, 5m
  ublock-quick-fixes: 267-0, 5m
  easylist: 67435-1312, 5m
  easyprivacy: 30605-998, 5m
  urlhaus-1: 6685-1, 5m
  plowe-0: 3737-2, 5m
filterset (user): [array of 27 redacted]
switchRuleset:
 added: [array of 9 redacted]
hostRuleset:
 added: [array of 15 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 669 ms (selfie)
 maxAssetCacheWait: 389 ms
popupPanel:
 blocked: 3
 network:
  fonts.net: 1
  tiqcdn.com: 2
```
</details>

**Comment by mapx-** [comment]
- Reset uBO to default settings / lists
- update all your lists (and do not add any other list)
- test again

**Comment by gorhill** [comment]
Unable to reproduce, I see drivers listed at this link: `https://epson.ca/Support/Printers/All-In-Ones/WorkForce-Series/Epson-WorkForce-WF-7620/s/SPT_C11CC97201?review-filter=Windows+11`, when using default settings and default lists.

You have heavily customized settings/lists, so it falls on you to figure the filter(s) causing the issue on your side.
