### ISSUE TITLE
google.com/maps: breakage

### ISSUE THREAD

**Issue by dailytabs** [uBlockOrigin/uAssets#18657]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.google.com/maps/dir//Buffalo+Wild+Wings/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x8824d93c8b333d7f:0x89e54e6742eea863?sa=X&ved=2ahUKEwjPmKT17Nz_AhWFpokEHaZcAYYQ9Rd6BAheEAQ`

### Category

breakage

### Description

Page loads blank from google.com search results. Clicking the Maps category also loads a blank page. Seems to be curben-phishing - only that has red rows in the logger, and adguard-spyware & ublock-annoyances have yellow rows.

### Other extensions used

lastpass

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 10d.5h.40m
Firefox: 114
filterset (summary):
 network: 389014
 cosmetic: 344661
 scriptlet: 45443
 html: 1219
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68312-5300, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91673-81129, now
  adguard-generic: 71916-6429, now
  adguard-mobile: 8290-13, now
  adguard-spyware-url: 1095-6, now
  block-lan: 47-0, now
  curben-phishing: 111976-42, 24m
  curben-pup: 189-0, 23m
  adguard-social: 20691-696, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 47601-339, now
  fanboy-social: 16095-20, now
  [39 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 34457-88, now
  ublock-badware: 7587-0, now
  ublock-privacy: 452-0, now
  ublock-unbreak: 2086-0, now
  ublock-quick-fixes: 267-0, now
  easylist: 67435-1411, now
  easyprivacy: 30605-771, now
  urlhaus-1: 6685-1, 25m
  plowe-0: 3737-529, now
filterset (user): [array of 3 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 437 ms (selfie)
 maxAssetCacheWait: 346 ms
popupPanel:
 blocked: 2
 network:
  google.com: 2
 extended:
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by dailytabs** [comment]
Navigating to maps.google.com is also "broken":

<img width="662" alt="googlemaps" src="https://github.com/uBlockOrigin/uAssets/assets/1219653/e0a69077-f693-433c-b5bd-195b996fad4f">

**Comment by dailytabs** [comment]
Accepting that gives:

<img width="597" alt="googlemaps2" src="https://github.com/uBlockOrigin/uAssets/assets/1219653/11752fd5-8df4-4b92-a82b-6eff74240621">

And, accepting that results in another blank page.

**Comment by peace2000** [comment]
https://gitlab.com/malware-filter/phishing-filter/-/issues/69
