### ISSUE TITLE
sms24.me: detection

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uAssets#18654]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

AdBlock detection 

### URL(s) where the issue occurs.

`https://sms24.me/en/countries/au`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/98148960/73e0b98d-d5df-41b6-8176-d76679abde51

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.6h.20m
Firefox Mobile: 114
filterset (summary):
 network: 103955
 cosmetic: 132166
 scriptlet: 24974
 html: 1125
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 9075-13, 10h.56m
  adguard-spyware-url: 1093-5, 2d.6h.6m
  adguard-social: 20667-163, 2d.6h.19m
  adguard-cookies: 26029-45, 2d.6h.19m
  adguard-popup-overlays: 22737-958, 2d.6h.19m
  adguard-mobile-app-banners: 4343-4, 2d.6h.19m
  adguard-other-annoyances: 13051-100, 2d.6h.19m
  adguard-widgets: 2181-0, 2d.6h.19m
  ublock-annoyances: 5192-14, 2d.6h.19m
 default:
  user-filters: 0-0, never
  ublock-filters: 34702-572, 2d.6h.19m
  ublock-badware: 7534-1, 2d.6h.19m
  ublock-privacy: 451-0, 2d.6h.19m
  ublock-unbreak: 2087-1, 2d.6h.19m
  ublock-quick-fixes: 268-0, 5h.37m
  adguard-mobile: 8289-105, 10h.58m
  easylist: 67058-810, 2d.6h.19m
  easyprivacy: 30603-622, 2d.6h.19m
  urlhaus-1: 6691-0, now
  plowe-0: 3737-1, 2d.6h.19m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 663 ms (selfie)
 maxAssetCacheWait: 219 ms
```
</details>

**Comment by mapx-** [comment]
keep only the default lists, disable other blocking addons
