### ISSUE TITLE
weatherbug.com: breakage

### ISSUE THREAD

**Issue by jlaine3333** [uBlockOrigin/uAssets#18651]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.weatherbug.com/weather-videos/extreme/20230623-Tropical-Storm-Conditions-in-Barbados`

### Category

breakage

### Description

Disables the video supposed to be playing

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 14d.8h.21m
Chromium: 114
filterset (summary):
 network: 93290
 cosmetic: 39325
 scriptlet: 17569
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 350-6, never
  easylist: 66858-50, 2d.20h.45m
  easyprivacy: 30603-54, 23h.25m
  plowe-0: 3738-952, 8d.2h.57m
  ublock-badware: 7516-136, 4d.6h.51m
  ublock-filters: 33558-144, 4d.6h.50m
  ublock-privacy: 406-3, 5d.8h.55m
  ublock-unbreak: 2049-34, 1d.6h.38m
  urlhaus-1: 6634-0, 8h.9m
filterset (user): [array of 350 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 166 ms (selfie)
 maxAssetCacheWait: 82 ms
popupPanel:
 blocked: 14
 network:
  weatherbug.com: 5
  adnxs.com: 1
  googletagmanager.com: 1
  kochava.com: 1
  resonate.com: 1
  rhetoricalloss.com: 1
  rubiconproject.com: 1
  taboola.com: 1
  weatherbug.net: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||web-ads.pulse.weatherbug.net/api/ads/targeting/v1/parameters$xhr,domain=weatherbug.com
```

Also placeholder

```adb
weatherbug.com##display-ad-widget
```

@ryanbr
