### ISSUE TITLE
xeiaso.net: detection

### ISSUE THREAD

**Issue by libreom** [uBlockOrigin/uAssets#18667]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://xeiaso.net/blog/anything-message-queue`

### Category

detection

### Description

detects ublock origin and orders to disable adblockers

### Other extensions used

BItwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/111110599/76b2ce11-0a2b-495a-8923-1d59a185a066)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.1h.1m
Chromium: 109
filterset (summary):
 network: 93995
 cosmetic: 39168
 scriptlet: 17684
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67511-50, 12m
  easyprivacy: 30608-56, 11m
  plowe-0: 3737-955, 10m
  ublock-badware: 7585-138, 9m
  ublock-filters: 33592-140, 8m
  ublock-privacy: 411-3, 7m
  ublock-quick-fixes: 205-24, 1h.10m
  ublock-unbreak: 2060-35, 6m
  urlhaus-1: 6693-1, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2183 ms (selfie)
 maxAssetCacheWait: 181 ms
popupPanel:
 blocked: 1
 network:
  ethicalads.io: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
It got fixed in the `uBlock filters – Annoyances` list which is disabled by default. To enable the list: Click on the uBO logo -> gears -> Filterlists -> Annoyances -> enable `uBlock filters – Annoyances` -> Update now.
