### ISSUE TITLE
apkmirror.com: detection

### ISSUE THREAD

**Issue by libreom** [uBlockOrigin/uAssets#18666]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.apkmirror.com/apk/google-inc/youtube/youtube-18-19-35-release/youtube-18-19-35-android-apk-download/`

### Category

detection

### Description

It detects ublock origin and adds 15 second waittime for downloading. I am not 100% sure if this qualifies for a issue but I saw similar issue of same site getting fixed which is now broken

### Other extensions used

Bitwarden

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/111110599/c15d6f2b-f4c0-4719-9aaf-b3cb322afdda)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.55m
Chromium: 109
filterset (summary):
 network: 93876
 cosmetic: 39167
 scriptlet: 17669
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67408-50, 22h.3m
  easyprivacy: 30605-56, 22h.3m
  plowe-0: 3737-955, 22h.3m
  ublock-badware: 7570-138, 22h.3m
  ublock-filters: 33577-139, 22h.3m
  ublock-privacy: 411-3, 22h.3m
  ublock-quick-fixes: 205-24, 1h.3m
  ublock-unbreak: 2060-35, 22h.3m
  urlhaus-1: 6691-0, 22h.3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2183 ms (selfie)
 maxAssetCacheWait: 181 ms
popupPanel:
 blocked: 15
 network:
  cloudflareinsights.com: 1
  crsspxl.com: 1
  google.com: 5
  googlesyndication.com: 1
  googletagmanager.com: 1
  instant.page: 1
  outbrain.com: 1
  pro-market.net: 1
  quantserve.com: 1
  scorecardresearch.com: 1
  wp.com: 1
 extended:
  ##.ai_widget
  ##.ains-apkm_outbrain_ad
  ##.advertisement-text
  ##.OUTBRAIN
  ##.ains
  #@#.google-ad-leaderboard
  ##+js(abort-on-stack-trace, document.querySelectorAll, /onload i…
  ##+js(remove-node-text, script, secondsLeft)
```
</details>

**Comment by krystian3w** [comment]
@stephenhawk8054  maybe back again in Firefox: https://github.com/DandelionSprout/adfilt/discussions/779#discussioncomment-6674655

`https://www.apkmirror.com/apk/klinker-apps-inc/evolvesms/evolvesms-4-2-0-release/evolvesms-4-2-0-android-apk-download/`

**Comment by stephenhawk8054** [comment]
@krystian3w I have updated few hours ago: https://github.com/uBlockOrigin/uAssets/commit/bb7dcbe0aa9e52d54f53ffb4607f37e2d8ef7455
