### ISSUE TITLE
aliexpress.com: breakage

### ISSUE THREAD

**Issue by sylverstream** [uBlockOrigin/uAssets#18662]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aliexpress.com/w/wholesale-port-usb-wall-charger-au.html?catId=0&initiative_id=SB_20230624184353&SearchText=port+usb+wall+charger+au&spm=a2g0o.home.1000002.0`

### Category

breakage

### Description

search results no longer show up.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/137029240/3f79bd07-7128-44dd-ae16-da94e15144a7)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 11d.20h.14m
Chromium: 114
filterset (summary):
 network: 93887
 cosmetic: 39197
 scriptlet: 17674
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 10-0, never
  easylist: 67435-50, 5h.13m
  easyprivacy: 30602-56, 2d.19h.58m
  plowe-0: 3735-954, 6d.22h.27m
  ublock-badware: 7538-138, 3d.7h.3m
  ublock-filters: 33568-142, 3d.5h
  ublock-privacy: 406-3, 6d.4h.30m
  ublock-quick-fixes: 267-16, 5h.12m
  ublock-unbreak: 2049-34, 3d.7h.2m
  urlhaus-1: 6691-0, 22h.46m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 335 ms (selfie)
 maxAssetCacheWait: 105 ms
popupPanel:
 blocked: 24
 network:
  alicdn.com: 1
  criteo.net: 1
  facebook.net: 1
  go-mpulse.net: 1
  google-analytics.com: 1
  mmstat.com: 17
  taobao.com: 2
 extended:
  ##a.search-card-item[href*="&aem_p4p_detail="]
  ##div[data-spm="main"] > a[class*="--container--"] span[class*="…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test if this filter works?

```adb
aliexpress.com#@#div[data-spm="main"] > a[class*="--container--"] span[class*="--ad--"]:upward(div[data-spm="main"] > a[class*="--container--"])
```

**Comment by sylverstream** [comment]
> ```
> aliexpress.com#@#div[data-spm="main"] > a[class*="--container--"] span[class*="--ad--"]:upward(div[data-spm="main"] > a[class*="--container--"])
> ```

Unfortunately not, the result is still the same.

**Comment by stephenhawk8054** [comment]
How about this?

```adb
aliexpress.com#@#a.search-card-item[href*="&aem_p4p_detail="]
```

**Comment by sylverstream** [comment]
> ```
> aliexpress.com#@#a.search-card-item[href*="&aem_p4p_detail="]
> ```
I deleted the previous filter, and added that one, and that results in a weird behaviour. I see very short flashes with lists of products, and then they disappear. If I count correctly it's 7 times, the number of pages in my results.

When I include both filters, it works as expected:

```
aliexpress.com#@#a.search-card-item[href*="&aem_p4p_detail="]
aliexpress.com#@#div[data-spm="main"] > a[class*="--container--"] span[class*="--ad--"]:upward(div[data-spm="main"] > a[class*="--container--"])
```
Thanks for the prompt response!

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
@sylverstream Sorry for pinging you, can you test if this filter can hide ads without breakages?

```adb
aliexpress.com##a.search-card-item[href*="&aem_p4p_detail="]:has-text(/^AD/)
```

**Comment by Schanzation** [comment]
I didn't try it, but this issue seems to have been fixed for me :)

**Comment by stephenhawk8054** [comment]
> I didn't try it, but this issue seems to have been fixed for me :)

Yeah, I mean the previous filters are disabled already, but some users have asked about the ads in search results again so I want to test if the new filter would cause issue or not.

**Comment by sylverstream** [comment]
@stephenhawk8054 doesn't make any difference. Even if I remove the previously added filter, the Aliexpress still works, not showing any ads. Perhaps the plugin was updated or Aliexpress has updated their UI.

**Comment by stephenhawk8054** [comment]
So in general, this filter does not cause any breakages for you?

```adb
aliexpress.com##a.search-card-item[href*="&aem_p4p_detail="]:has-text(/^AD/)
```

**Comment by sylverstream** [comment]
No, it doesn't make any difference if I have the filter or not. In both cases the search results load fine @stephenhawk8054

**Comment by stephenhawk8054** [comment]
Thanks for your feedback.
