### ISSUE TITLE
blog.cryptowidgets.net: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18669]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.cryptowidgets.net/post/what-is-ethereum-classic-etc--live-pr`

### Category

detection

### Description

Ad blocker detected..

### Other extensions used

TeaserFast

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.5h.47m
Chromium: 114
filterset (summary):
 network: 93971
 cosmetic: 39196
 scriptlet: 17723
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67511-50, 6m
  easyprivacy: 30608-56, 6m
  plowe-0: 3737-955, 6m
  ublock-badware: 7585-138, 6m
  ublock-filters: 33598-140, 6m
  ublock-privacy: 416-3, 6m
  ublock-quick-fixes: 277-18, 6m
  ublock-unbreak: 2060-35, 6m
  urlhaus-1: 6647-1, 59m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11810 ms (selfie)
 maxAssetCacheWait: 902 ms
popupPanel:
 blocked: 43
 network:
  360yield.com: 3
  3lift.com: 4
  4dex.io: 5
  a-mo.net: 5
  adform.net: 5
  google.com: 2
  onetag-sys.com: 4
  sharethrough.com: 4
  smartadserver.com: 2
  unrulymedia.com: 5
  yahoo.com: 4
```
</details>

**Comment by mapx-** [comment]
@Lahiru2002 **when will you learn finally to provide the REAL link to test** ?

`http://earnow.online/8e6lQK2`

**Comment by monkeyde98** [comment]
these ones are similar to this one earnow

this one even blocks advertising but the continue button is not showing!
http://shortano.link/C0b0

this one is detected in the first step.
http://shortino.link/RHT4Zggt
