### ISSUE TITLE
cnet.com [Anti-Adblock]

### ISSUE THREAD

**Issue by WowDude** [uBlockOrigin/uAssets#1866]
### Describe the issue

Anti-Adblock

### Screenshoot

![capture_023_02042018_124226](https://user-images.githubusercontent.com/37474031/38193640-4da4df36-3673-11e8-9098-4805f313b9d5.png)

### URL(s) where the issue occurs

`https://www.cnet.com/forums/discussions/are-hosts-file-still-a-good-idea-619415/`

### Steps to reproduce

1. Visit the page

### Settings
Win 7 SP1 [64bit]
Chrome 65.0.3325.181 [64bit]
Opera 52.0.2871.30 [64bit]
Firefox 59.0.2 [64bit]
uBlock Origin 1.15.18

### Filters
Nano Defender 13.49 (on Firefox 13.48)
Nano Defender filter
Nano Base filter
Nano Whitelist filter
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adguard Base Filters
Adguard Spyware Filters
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Cookiemonster List
I don't care about cookies
Peter Lowe’s Ad and tracking server list

### Additional info

Enabling `Fanboy’s Enhanced Tracking List` fixes the issue.

**Comment by okiehsch** [comment]
Already fixed in `uBlock-annoyances`
https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt#L138

**Comment by WowDude** [comment]
@okiehsch ok, anyway just as some feedback (don't bother about it, I'll either consider enabling uBlock Anoyances list as it's a small list or copy the filter to My Filters):
- generally don't use any annoyances filters, and I keep them disabled all the time, so that's why I had uBlock Annoyances disabled
- didn't  considered some of Anti-Adblock filters can land onto Annoyances list as all I saw last several last days in Assets repo landed onto uBlock filters main list
- since now I'll enable uBlock Annoyances before reporting an issue
