### ISSUE TITLE
[NSFW] family-simulators.io: badware

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18664]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Just a cartoon-based hentai site which has nothing of value and leads you to another fake dating site if you click the button on the main page. "TRY NOT TO CUM"
Also/or `bangready.b-cdn.net`

### URL(s) where the issue occurs.

`https://family-simulators.io`
`https://family-simulators.io/t16/index3.php?t=default` (Memorial Day Winner browser message or other redirects)
2nd link also leads to this after answering all questions:
`https://familyfornicate.com/t13/index-green.php?t=default|rtcnf:32-114-1`

### uBO version

v1.50.1b6

### Browser name and version

Firefox 114.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by JobcenterTycoon** [comment]
Can you tell us the source of this domain (like a popup from a other site)? So we can get more data which give us more ways to block this crap.

**Comment by Sonic5435325** [comment]
It's been a while but I remember I was trying to fetch bad domains from sites like `amputee-girl.blogspot.com` and `putlocker.style`. Though, their popup ads should be blocked directly in uBlock Origin.

**Comment by JobcenterTycoon** [comment]
I get no popups. I added the 2 domains to the badware now.
