### ISSUE TITLE
nekogram.org: badware

### ISSUE THREAD

**Issue by cyberboh** [uBlockOrigin/uAssets#18678]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

phising site, the actual site is `nekogram.app`.
the site is providing fake nekogram app (telegram client)
the APK from that site will upload all the messages and files you sent, your gallery photos and monitor your clipboard.

### URL(s) where the issue occurs.

```
nekogram.org
t188telegram.xyz
websocket40001.hgspz.com
netkefu.hgspz.com
imganalyze.hgspz.com
www.tellegrom.xyz
```

### Screenshot(s)

more infos see here:
https://t.me/NekoUpdates/386
https://t.me/NekoUpdates/387

### uBO version

1.50.1b6

### Browser name and version

Firefox 114.0.2

### Settings

default

### Notes

VirusTotal link: https://www.virustotal.com/gui/file/94d0d74dab514e50d1b198325154d963bbcf6521020bdfcb76e30041a749d4ad

**Comment by gorhill** [comment]
I added `nekogram.org` to badware list, but for the other domain name I get 404 or no valid response.

**Comment by Sonic5435325** [comment]
`nekogram.org` seems to be down now. I don't get any result when directly going to the site.

**Comment by iam-py-test** [comment]
`nekogram.org` seems to have been suspended by the registrar
