### ISSUE TITLE
blog.freeoseocheck.com: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18670]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://t.co/05mUz7Qkj3`

### Category

detection

### Description

I think this url is correct.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.8h.40m
Chromium: 114
filterset (summary):
 network: 93973
 cosmetic: 39205
 scriptlet: 17731
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67512-50, 34m
  easyprivacy: 30608-56, 34m
  plowe-0: 3737-955, 34m
  ublock-badware: 7585-138, 34m
  ublock-filters: 33616-140, 34m
  ublock-privacy: 416-3, 34m
  ublock-quick-fixes: 277-18, 34m
  ublock-unbreak: 2060-35, 34m
  urlhaus-1: 6647-1, 34m
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 21933 ms (selfie)
 maxAssetCacheWait: 760 ms
popupPanel:
 blocked: 71
 network:
  360yield.com: 6
  3lift.com: 6
  4dex.io: 6
  a-mo.net: 6
  adform.net: 5
  doubleclick.net: 1
  onetag-sys.com: 6
  pbstck.com: 1
  rubiconproject.com: 6
  sharethrough.com: 6
  smartadserver.com: 4
  smilewanted.com: 5
  surfe.pro: 1
  unrulymedia.com: 6
  yahoo.com: 6
```
</details>

**Comment by gorhill** [comment]
> from `https://t.co/05mUz7Qkj3`
> I think this url is correct.

Why guess? You don't have to guess, just try it for yourself in a new tab, you will see immediately that you can not reproduce the issue yourself. Not providing all the information up front is a time waste for volunteers.

**Comment by stephenhawk8054** [comment]
The source is a shortener link. The `t.co` link is just an intermediate URL. We already told you many times that shortener issues should be discussed here: https://github.com/uBlockOrigin/uAssets/discussions/17361
