### ISSUE TITLE
[nsfw] zh.moegirl.org.cn: ads

### ISSUE THREAD

**Issue by InfiniteSynthesis** [uBlockOrigin/uAssets#18679]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://zh.moegirl.org.cn/Mainpage`

### Category

ads

### Description

There are ads at the top and background of the page, and a floating ad at the bottom of the page. The sidebar of the wiki item pages also contain ads. Details see my screenshot.

### Other extensions used

None, uBlockOrigin only

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Mainpage:
https://sm.ms/image/FVyNPD2cGRqAt7g

Sub item page:
https://sm.ms/image/umecz1QSPW4NLqk

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.5b14
Chromium: 114
filterset (summary): 
  network: 93976
  cosmetic: 39213
  scriptlet: 17733
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 19m
  default: 
    user-filters: 0-0, never
    easylist: 67558-76, 19m
    easyprivacy: 30608-56, 19m
    plowe-0: 3737-955, 19m
    ublock-badware: 7588-138, 19m
    ublock-filters: 33614-140, 19m
    ublock-privacy: 416-78, 19m
    ublock-quick-fixes: 272-17, 19m
    ublock-unbreak: 2057-35, 19m
    urlhaus-1: 6647-1, 19m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 256 ms (selfie)
  maxAssetCacheWait: 171 ms
popupPanel: 
  blocked: 9
  blockedDetails: 
    ezojs.com: 1
    google.com: 5
    googlesyndication.com: 1
    googletagmanager.com: 1
    tasterscaltha.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable "AdGuard Chinese" list in "Filter lists" pane and test again?

**Comment by gorhill** [comment]
Also, upgrade to latest uBO stable which is currently version 1.50.0. There is no guarantee older versions will fully work with current filter lists.

**Comment by mapx-** [comment]
@InfiniteSynthesis 

- as said already, enable AG chinese list
- if you still get "classic" ads (not popups or detection) report directly here: https://github.com/cjx82630/cjxlist/issues
