### ISSUE TITLE
rocketnews24.com: breakage

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18676]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Wasn't sure what to label this in the title so I just made it blank. uBlock Origin makes the share sidebar higher than it needs to be.
These filters fixed it:
`rocketnews24.com#@#div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"])`
`rocketnews24.com#@#[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"])`
Maybe as a replacement
`rocketnews24.com##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"]):not(#div-gpt-ad-billboard)`

Also an Anti-AdBlock:
![Screenshot from 2023-06-25 18-57-40](https://github.com/uBlockOrigin/uAssets/assets/89158249/b4b4374f-cca2-40b8-a796-9a3c5f3f3932)

### URL(s) where the issue occurs.

`https://rocketnews24.com/2023/06/26/1899559/`

### Screenshot(s)

By default:
![Screenshot from 2023-06-25 18-48-08](https://github.com/uBlockOrigin/uAssets/assets/89158249/97f30ae4-cd83-4def-acab-8074cc97c74d)

With exception filters:
![Screenshot from 2023-06-25 18-50-45](https://github.com/uBlockOrigin/uAssets/assets/89158249/6a5b24b2-f646-4c8a-a82f-5fa6177fcc6f)

### uBO version

1.50.1b6

### Browser name and version

Firefox 114.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by krystian3w** [comment]
On page bad works these:
https://github.com/uBlockOrigin/uAssets/blob/742427950c578caca75cdabfab5479731202e79f/filters/filters.txt#L14458-L14459

Second is obvious duplicate ignored by mapx-.

Pages may need specific:

```adb
rocketnews24.com#@#[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"])
rocketnews24.com#@#div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"])
rocketnews24.com##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"]):style(width: 1px !important; height: 1px !important; visiblity: hidden !important;)
rocketnews24.com##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"]):style(width: 1px !important; height: 1px !important; visiblity: hidden !important;)
```

As long prompt anti-adblock resistant to use `spoof-css` (e.g. page stolen logic from `:matches-css`).

**Comment by Sonic5435325** [comment]
I'm not a big fan of block social counters compared to things like cookie notices, newsletters, or sticky headers.

**Comment by mapx-** [comment]
maybe @Yuki2718 could help here

**Comment by Yuki2718** [comment]
Japanese filters include `@@||rocketnews24.com^$generichide` so I'm not sure if we have to add the suggested exception.
