### ISSUE TITLE
toolbaz.com: breakage

### ISSUE THREAD

**Issue by Spectral-Dreams** [uBlockOrigin/uAssets#18672]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://toolbaz.com/writer/ai-story-generator`

### Category

breakage

### Description

It's the various AI-writer sections on the website and the annoying pop-up. Strange thing is this problem started just a few hours ago. Before that, I was using the site just fine with UBlock running. Even if I disable UBlock, the annoying pop-up still shows.

### Other extensions used

Old Reddit Redirect
Windscribe

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/132994032/a324ff97-853b-42bd-ac12-19baaeb8af1c)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 6d.22h.12m
Chromium: 114
filterset (summary):
 network: 93973
 cosmetic: 39197
 scriptlet: 17723
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67512-50, 2h.44m
  easyprivacy: 30608-56, 2h.44m
  plowe-0: 3737-955, 2h.44m
  ublock-badware: 7585-138, 2h.44m
  ublock-filters: 33600-140, 2h.44m
  ublock-privacy: 416-3, 2h.44m
  ublock-quick-fixes: 277-18, 2h.44m
  ublock-unbreak: 2060-35, 2h.44m
  urlhaus-1: 6647-1, 2h.44m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 139 ms (selfie)
 maxAssetCacheWait: 70 ms
popupPanel:
 blocked: 25
 network:
  toolbaz.com: 13
  amazon-adsystem.com: 1
  connatix.com: 5
  doubleclick.net: 1
  ezodn.com: 2
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  quantserve.com: 1
 extended:
  ##.ezoic-adpicker-ad
  ##.ezoic-ad
  ##.adtester-container
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ##[data-ez-name]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ez-video-wrap
  #@#[id^="div-gpt-ad"]
```
</details>

**Comment by mapx-** [comment]
> Even if I disable UBlock, the annoying pop-up still shows.

Disable Windscribe extension and the desktop part, test again

**Comment by Spectral-Dreams** [comment]
> > Even if I disable UBlock, the annoying pop-up still shows.
> 
> Disable Windscribe extension and the desktop part, test again


Oh, wow. That actually worked. But I need both Windscribe and uBlock running. Do I have to block Windscribe from accessing the site mentioned above? Thank you.

**Comment by mapx-** [comment]
> Do I have to block Windscribe from accessing the site mentioned above?

IDK. See its settings.

btw, why do you still need windscribe if you use uBO ?

**Comment by Spectral-Dreams** [comment]
figured out how to get both working on that site. Go to your Windscribe extension and disable the "Ad Crusher" option.
![image](https://github.com/uBlockOrigin/uAssets/assets/132994032/11feb2bc-9113-4283-8c72-3fac2df0de5e)

**Comment by gorhill** [comment]
See <https://twitter.com/gorhill/status/1409911991154757634>, and worse they are currently embedding an old dated version of uBO from around April 2022.

**Comment by Spectral-Dreams** [comment]
> 

Sorry, I don't have twitter. What did that tweet say?

**Comment by gorhill** [comment]
Not really important. Looks like Twitter requires logging in now to see tweets, so I will have to stop using it as reference.
