### ISSUE TITLE
lepalacesaumur.fr: breakage

### ISSUE THREAD

**Issue by Coeur-Noir** [uBlockOrigin/uAssets#18673]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lepalacesaumur.fr/`

### Category

breakage

### Description

legitimate pictures coming from the site [ from path containing …/public/images/… ] are blocked.

### Other extensions used

Decentraleyes

on or off, same situation.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock_lepalacesaumur_fr](https://github.com/uBlockOrigin/uAssets/assets/1895947/cd30d0b2-2741-429e-9cd2-bce51aa711cc)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 11d.23h.32m
Firefox: 114
filterset (summary):
 network: 112564
 cosmetic: 48176
 scriptlet: 17816
 html: 956
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 34473-139, 3h.46m
  ublock-badware: 7587-1, 3h.46m
  ublock-privacy: 457-0, 3h.46m
  ublock-unbreak: 2087-0, 3h.46m
  ublock-quick-fixes: 278-0, 3h.46m
  easylist: 67512-905, 3h.46m
  easyprivacy: 30608-612, 3h.46m
  urlhaus-1: 6647-1, 3h.46m
  plowe-0: 3737-1, 3h.46m
  FRA-0: 28340-342, 3h.46m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 530 ms (selfie)
 maxAssetCacheWait: 212 ms
popupPanel:
 blocked: 33
 network:
  lepalacesaumur.fr: 30
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
> user-filters: 2-0, never

check your custom filters

**Comment by Coeur-Noir** [comment]
Well…

there is a filter somewhere that blocks …/public/images/aff-* and this is not in my « personal filters » I've already removed or reset them.

So avoiding names beginning with aff-* in the pictures I need to upload to the site fixed the issue.

An issue that's not really an ublock issue but more something / somewhere about « default » filters for my region / localisation.

Sorry for late feedback - you're fast !
