### ISSUE TITLE
uBlock suddenly blocks all videos on Joyn

### ISSUE THREAD

**Issue by Ealendil** [uBlockOrigin/uAssets#18684]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlock blocks all videos including the series you want to watch. Sound works, you just don't have an image anymore. Last week everything worked fine with exactly the same settings.The problem also only appears if uBlock blocked one ad beforehand. Through reloading it works again until there is an add that was blocked.

### URL(s) where the issue occurs.

`https://www.joyn.de/play/serien/the-taste/11-5-englische-vibes-mit-gastjuror-johannes-nuding?from=%2F`

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 13d.3h.59m
Firefox: 114
filterset (summary):
 network: 96227
 cosmetic: 43813
 scriptlet: 17726
 html: 962
listset (total-discarded, last-updated):
 default:
  user-filters: 21-1, never
  ublock-filters: 34540-41, 1m
  ublock-badware: 7611-0, 1m
  ublock-privacy: 457-0, 1m
  ublock-unbreak: 2087-0, 1m
  easylist: 67532-735, 1m
  easyprivacy: 30611-622, 1m
  urlhaus-1: 6555-1, 1m
  plowe-0: 3739-2, 1m
  DEU-0: 6922-17, 1m
  ublock-quick-fixes: 276-46, 1m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4568 ms (selfie)
 maxAssetCacheWait: 4223 ms
```
</details>

**Comment by mapx-** [comment]
I can reproduce only adding

```
@@*$xhr,domain=joyn.de
||hybrid-prd.ad-prd.s.joyn.de^$important
```

**Comment by okiehsch** [comment]
> I can reproduce only adding

You mean the site works unless you add those fiilters or the site is broken and those filters fix it on your end?

**Comment by mapx-** [comment]
The site is working fine, only adding those filters I'm getting 
`hybrid-prd.ad-prd.s.joyn.de`
which is blocked by EL Germany

**Comment by okiehsch** [comment]
I see, is this an older issue? Just wondering how you ended up testing those specific filters.

**Comment by mapx-** [comment]
yes, this 1 https://github.com/uBlockOrigin/uAssets/issues/17050

**Comment by mapx-** [comment]
2 days ago https://github.com/uBlockOrigin/uAssets/issues/17050#issuecomment-1605551548

**Comment by mapx-** [comment]
I guess different code is used for some users

We could whitelisting the xhr requests for that path and block the video ads using xml-prune

```
@@||hybrid-prd.ad-prd.s.joyn.de^$xhr
joyn.de##+js(xml-prune, Period[id^="adId"], , .mpd)
```

**Comment by Ealendil** [comment]
||sqrt-5041.de^$xhr,domain=joyn.de

i am testing this one right now and so far its looking good

**Comment by Ealendil** [comment]
Thank you for pointing out the other issue, didnt see it! :)

**Comment by Remus76** [comment]
@mapx- Using your filters instead of mine the player works but at the beginning of some videos I get a single ad.
> Me and someone else were able to do so. I did some testing today and applying the following filter solved the issue for both of us: `||sqrt-5041.de^$xhr,domain=joyn.de` So I no longer have any problems. Now the player works fine (and of course also without ads).
works for me like I stated in other issue.

**Comment by mapx-** [comment]
so, adding only
`||sqrt-5041.de^$xhr,domain=joyn.de`

fixes the breakage ?

**Comment by Ealendil** [comment]
apparently yes :) thank you all for the help!
