### ISSUE TITLE
earnow.online: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18680]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://earnow.online/OW7bj7oxjz2`

### Category

detection

### Description

`https://earnow.online/OW7bj7oxjz2`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.18h.21m
Chromium: 114
filterset (summary):
 network: 93921
 cosmetic: 39204
 scriptlet: 17730
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67515-50, 1h.1m
  easyprivacy: 30608-56, 1h.1m
  plowe-0: 3737-955, 1h.1m
  ublock-badware: 7588-138, 1h.1m
  ublock-filters: 33616-140, 1h
  ublock-privacy: 416-3, 1h
  ublock-quick-fixes: 274-18, 1h
  ublock-unbreak: 2060-35, 1h
  urlhaus-1: 6591-1, 1h
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1928 ms (selfie)
 maxAssetCacheWait: 823 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
already fixed
