### ISSUE TITLE
kat.am: breakage

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18685]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Dropdown button on sidebar. Caused by:
`*$script,1p,from=~kat.at|~kat.ec|~kat.eu|~kat.mn|~kat.rip|~kat.tv|~kickass.codes|~kickass.website|bigkickass.*|kat.*|kat2.*|katbay.*|katfreak.*|kathydra.*|katkickass.*|katkickass.*|kattracker.*|kick4ss.*|kickass-usa.*|kickass.*|kickass2.*|kickassaustralia.*|kickassbay.*|kickassdb.*|kickassfull.*|kickassgo.*|kickasshydra.*|kickassindia.*|kickasskat.*|kickassminds.*|kickassmovies.*|kickasspk.*|kickasst.*|kickasstorrents.*|kickasstorrents2.*|kickasstracker.*|kickasstrusty.*|kickassuk.*|kickassunlocked.*|kickassz.*|kkat.*|kkickass.*|thekat.*|thekickass.*|topkickass.*|torrentkat.*|torrentskickass.*`

### URL(s) where the issue occurs.

`https://kat.am/top-100-television`

### Screenshot(s)

![Screenshot from 2023-06-26 15-13-08](https://github.com/uBlockOrigin/uAssets/assets/89158249/485f3abd-d582-4182-8eed-195eefa6bf4d)

### uBO version

v1.50.1b6

### Browser name and version

Firefox 114.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by Sonic5435325** [comment]
@mapx- `kat.at`, `kat.mn`, `kat.eu`, `kat.ec`, `kat.tv`, `kickass.codes`, and `kickass.website` are all invalid too. Please remove them.

**Comment by Sonic5435325** [comment]
There's also an ad placeholder on `kat.rip`:
https://kat.rip/usearch/test/
![Screenshot from 2023-06-26 17-04-14](https://github.com/uBlockOrigin/uAssets/assets/89158249/389b66ca-29b6-407c-8aa0-ff5eb6059f2e)

**Comment by capJavert** [comment]
@mapx- `kickass.codes` and `kickass.website` are my sites and are definitely not torrent related, please remove them from block list 🙏
