### ISSUE TITLE
blic.rs: ads

### ISSUE THREAD

**Issue by stearless** [uBlockOrigin/uAssets#18687]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.blic.rs/`

### Category

ads

### Description

There are add placeholders leftover on blic.rs and telegraf.rs.

### Other extensions used

BitWarden
Google Translate
Pushbullet
NordVPN (disabled)
Session save
night reader
return youtube dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 13d.10h
Firefox: 114
filterset (summary):
 network: 100694
 cosmetic: 139124
 scriptlet: 22641
 html: 962
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68361-4175, now
  fanboy-cookiemonster: 47618-219, now
 default:
  user-filters: 24-1, never
  ublock-filters: 34540-87, now
  ublock-badware: 7611-1, now
  ublock-privacy: 457-0, now
  ublock-unbreak: 2088-0, now
  ublock-quick-fixes: 276-0, now
  easylist: 67532-737, now
  easyprivacy: 30611-613, now
  urlhaus-1: 6555-1, now
  plowe-0: 3739-1, now
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 21 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 colorBlindFriendly: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 328 ms (selfie)
 maxAssetCacheWait: 97 ms
popupPanel:
 blocked: 20
 network:
  adxbid.info: 2
  aklamator.com: 1
  consentmanager.net: 2
  doubleclick.net: 2
  facebook.net: 1
  gemius.pl: 1
  googletagmanager.com: 3
  ocdn.eu: 3
  onesignal.com: 1
  onet.pl: 3
  performax.cz: 1
 extended:
  ##.banner--darker.banner--top.banner
  ##.banner--sticky.banner
  ###Sticky
```
</details>

**Comment by mapx-** [comment]
enable the regional list Dandelion Sprout's Serbo-Croatian filters
