### ISSUE TITLE
[NSFW] gofile.io: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#18689]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gofile.io/d/FzCJW3`

### Category

nuisance

### Description

Unable to view content due to panel.

### Other extensions used

none

### Screenshot(s)

link : `https://gofile.io/d/FzCJW3`

![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/ba4221ff-6be5-42c9-b1fe-c6a3beb4b118)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.11h.45m
Chromium: 114
filterset (summary):
 network: 129513
 cosmetic: 69055
 scriptlet: 19153
 html: 0
listset (total-discarded, last-updated):
 added:
  RUS-0: 39479-160, now
 default:
  user-filters: 0-0, never
  FRA-0: 28340-33, now
  easylist: 67532-255, now
  easyprivacy: 30611-411, now
  plowe-0: 3739-983, now
  ublock-badware: 7609-154, now
  ublock-filters: 33666-251, now
  ublock-privacy: 416-5, now
  ublock-quick-fixes: 275-47, now
  ublock-unbreak: 2061-39, now
  urlhaus-1: 6555-1, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 408 ms (selfie)
 maxAssetCacheWait: 65 ms
popupPanel:
 blocked: 2
 network:
  gofile.io: 1
  doubleclick.net: 1
```
</details>

**Comment by mapx-** [comment]
I was able to reproduce only once - even clearing cookies / localStorage

add

```
gofile.io##.show.modal
gofile.io##.show.modal-backdrop
```

**Comment by SakhJack** [comment]
^this^ works, but disables scrolling (so need proper fix)
<details><summary>Screenshots</summary>

Filters enabled (scroll bar gone)
![image](https://github.com/uBlockOrigin/uAssets/assets/10335530/0bb76bcd-4a53-4af4-8b70-63b175e80664)


Filters disabled (scroll bar present and functional
![image](https://github.com/uBlockOrigin/uAssets/assets/10335530/d8b4226a-d24d-45d1-b0cd-dafb44e95bd1)

</details>

**Comment by mapx-** [comment]
provide your test link

**Comment by SakhJack** [comment]
[there you go](https://gofile.io/d/s9N8BG)
btw adblock popup seems to only appear for frequent users, changing container/browser removes it

**Comment by mapx-** [comment]
ok, I 'll add the filters in the annoyances list (soft anti adblock => clicking "watch an ad" will fix it)

**Comment by mapx-** [comment]
commented out, since we cannot reproduce the original issue and only an annoyance
