### ISSUE TITLE
danganronpa.fandom.com: breakage

### ISSUE THREAD

**Issue by LittleEgg255** [uBlockOrigin/uAssets#18688]
### Prerequisites

- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://danganronpa.fandom.com/`

### Category

breakage

### Description

Clicking on an image just refreshes the page. This only started happening today.
This also seems to be the case on other Fandom wikis, such as the DDLC wiki or FNF wiki just to name 2.

### Other extensions used

none

### Screenshot(s)

I can't really screenshot the page refreshing, but it's in any sprite/image gallery
https://github.com/uBlockOrigin/uAssets/assets/137831957/88b2219f-cd11-448a-b724-149b100b62f1
Take this one for example.

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 13d.14m
Chromium: 114
filterset (summary):
 network: 93922
 cosmetic: 39210
 scriptlet: 17752
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67532-50, 4m
  easyprivacy: 30611-56, 4m
  plowe-0: 3739-956, 4m
  ublock-badware: 7609-138, 4m
  ublock-filters: 33666-140, 4m
  ublock-privacy: 416-3, 4m
  ublock-quick-fixes: 275-47, 4m
  ublock-unbreak: 2061-35, 4m
  urlhaus-1: 6555-1, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 454 ms (selfie)
 maxAssetCacheWait: 304 ms
popupPanel:
 blocked: 51
 network:
  ad.gt: 2
  adsafeprotected.com: 1
  amazon-adsystem.com: 1
  cpx.to: 1
  doubleclick.net: 1
  durationmedia.net: 1
  eyeota.net: 1
  fastly-insights.com: 1
  google-analytics.com: 2
  googlesyndication.com: 7
  googletagmanager.com: 1
  imrworldwide.com: 1
  liadm.com: 1
  nocookie.net: 1
  quantserve.com: 1
  rlcdn.com: 1
  scorecardresearch.com: 1
  wikia-services.com: 26
 extended:
  ##.top-ads-container
  ##.ad-slot-placeholder
  ##.bottom-ads-container
  ##.sponsored-content
  ##.gpt-ad
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ###featured-video__player-container
  ##+js(set-constant, wgAffiliateEnabled, false)
```
</details>

**Comment by mapx-** [comment]
even disabling uBO or opening in a new tab the image's link
`https://danganronpa.fandom.com/wiki/File:Danganronpa_1_Monokuma_Rui_Komatzusaki_Illustration.png`

it will have the same behavior (like refresjing the page)

**Comment by LittleEgg255** [comment]
I'm not sure if it's just me, but I got it to work fine by disabling uBO.

**Comment by mapx-** [comment]
Tested again => same result
