### ISSUE TITLE
linkshub.to: breakage

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#18683]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkshub.to/`

### Category

breakage

### Description

I have to click the "Show Links" button twice to be able to see the links. Here's a link to an actual page with available links on it: `https://linkshub.to/11307/`.

### Other extensions used

Not any other adblocker extension.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Linkshub page](https://github.com/uBlockOrigin/uAssets/assets/50150516/e767f7fe-45fd-4bb4-b884-5958bab8b4cf)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 18d.13h.52m
Chromium: 114
filterset (summary):
 network: 93924
 cosmetic: 39208
 scriptlet: 17746
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67523-50, now
  easyprivacy: 30609-56, now
  plowe-0: 3738-956, now
  ublock-badware: 7588-138, now
  ublock-filters: 33629-140, now
  ublock-privacy: 416-3, now
  ublock-quick-fixes: 275-18, now
  ublock-unbreak: 2060-35, now
  urlhaus-1: 6591-1, 1h.29m
filterset (user): [empty]
trustedset:
 added: [array of 44 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 227 ms (selfie)
 maxAssetCacheWait: 107 ms
popupPanel:
 blocked: 7
 network:
  acdcdn.com: 1
  fusoidactuate.com: 1
  google-analytics.com: 2
  googletagmanager.com: 1
  highcpmrevenuenetwork.com: 1
  push-sdk.net: 1
 extended:
  ##[href*="ad setup "]
  ##[href="https://crack-status.com/"]
  ##+js(window.open-defuser)
  ##+js(abort-current-script, JSON.parse, break;case $.)
```
</details>

**Comment by okiehsch** [comment]
>I  have to click the "Show Links" button twice to be able to see the links.

Why do you think that is caused by uBO?

**Comment by gorhill** [comment]
It's a site issue, it assumes the element `display` style is set to either `none` or `block`, while it's not until the visitor clicks on the button.
