### ISSUE TITLE
duplichecker.com: breakage

### ISSUE THREAD

**Issue by jawad53** [uBlockOrigin/uAssets#18682]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ublock Origin Extension blocking tools and captchas on site. So, unable to use tools on the website.
`https://www.duplichecker.com/article-rewriter.php`

### A specific URL where the issue occurs.

`https://www.duplichecker.com/article-rewriter.php`

### Steps to Reproduce

open site with the extension on
`https://www.duplichecker.com/article-rewriter.php`
Add content and click on the Rewrite Article button
Tool not works and shown error message Captcha not filled and captcha is blocked by the extension

### Expected behavior

Catcha should be shown and I can be able to fill the captcha when the extension is ON and can generate the results for the tool.

### Actual behavior

Captcha should not be block on the webpage

### uBO version

1.50.0

### Browser name and version

Chrome 114.0.5735.134 (Official Build) (64-bit) all version 

### Operating System and version

windows 11

**Comment by JobcenterTycoon** [comment]
Works all fine for me.

**Comment by jawad53** [comment]
https://www.duplichecker.com/backlink-checker.php
Hi please have alook on issue on this TOol




    On Monday, June 26, 2023 at 02:17:13 PM GMT+5, JobcenterTycoon ***@***.***> wrote:  
 
 


Works all fine for me.

**Comment by JobcenterTycoon** [comment]
Reproduced and fixed. Force update the filterlists to get the fix directly.

**Comment by jawad53** [comment]
Yes Fixed Now Thanks
    On Monday, June 26, 2023 at 03:24:38 PM GMT+5, JobcenterTycoon ***@***.***> wrote:  
 
 


Reproduced and fixed. Force update the filterlists to get the fix directly.
