### ISSUE TITLE
kat.*, kickass.*: outdated filters, ad placeholder

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18690]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`kat.at`, `kat.mn`, `kat.eu`, `kat.ec`, `kat.tv`, `kickass.codes`, and `kickass.website` from uBlock filters - Ads are all invalid. Please remove them.
There's also an ad placeholder on `kat.rip`.

### URL(s) where the issue occurs.

`https://kat.rip/usearch/test/`

### Screenshot(s)

![248937100-389b66ca-29b6-407c-8aa0-ff5eb6059f2e](https://github.com/uBlockOrigin/uAssets/assets/89158249/3727df61-d0e7-4323-a165-165f57441c18)

### uBO version

v1.50.1b6

### Browser name and version

Firefox 114.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by Sonic5435325** [comment]
@mapx- I don't get why neither were answered, will there at least be a removal for the invalid domains?
`https://www.kat.at/` for example:
![Screenshot from 2023-06-27 00-09-16](https://github.com/uBlockOrigin/uAssets/assets/89158249/e09c9b66-119c-4671-bb2f-ab11a40146b7)

**Comment by Sonic5435325** [comment]
Or `https://kat.tv`, which is parked....
![Screenshot from 2023-06-27 00-11-14](https://github.com/uBlockOrigin/uAssets/assets/89158249/19804b70-029e-476f-838a-134c6e23c62e)

**Comment by mapx-** [comment]
do not open other issues, just comment in the old ones
