### ISSUE TITLE
woowebtools.com: detection

### ISSUE THREAD

**Issue by danielrzad** [uBlockOrigin/uAssets#18697]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://woowebtools.com/`

### Category

detection

### Description

Hi guys. 
This site is just a proxy. For example it opens up every time u click on any DOWNLOAD button on: `https://mirrorace.org/m/3QoaS`, another site known for me is doodrive verification every 24h `https://doodrive.com/f/pn2v3x`.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![popup_2023-06-27 102758](https://github.com/uBlockOrigin/uAssets/assets/45539133/c149edba-1cce-4ac1-9aad-138c7d9cdd13)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: now
Chromium: 114
filterset (summary):
 network: 93890
 cosmetic: 39207
 scriptlet: 17752
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67523-50, now
  easyprivacy: 30611-56, now
  plowe-0: 3738-956, now
  ublock-badware: 7588-138, now
  ublock-filters: 33666-140, now
  ublock-privacy: 416-3, now
  ublock-quick-fixes: 275-47, now
  ublock-unbreak: 2060-35, now
  urlhaus-1: 6551-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 983 ms
 maxAssetCacheWait: 13 ms
popupPanel:
 blocked: 6
 network:
  criteo.net: 1
  doubleclick.net: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
```
@@||static.doubleclick.net/instream/ad_status.js$xhr,domain=woowebtools.com
@@||static.criteo.net^$xhr,domain=woowebtools.com
@@||pagead2.googlesyndication.com^$xhr,script,domain=woowebtools.com
||woowebtools.com/*.png$image
```

**Comment by mapx-** [comment]
You are right.
