### ISSUE TITLE
zdnet.com: nuisance

### ISSUE THREAD

**Issue by ctison** [uBlockOrigin/uAssets#18696]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zdnet.com/article/these-400-xr-glasses-gave-my-macbook-a-120-inch-screen-to-work-with/`

### Category

nuisance

### Description

I've created the following filter:
```
www.zdnet.com###onetrust-consent-sdk
```
But it doesn't work, maybe because the `div#onetrust-consent-sdk` is dynamically inserted into the DOM.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/17789536/41f0836c-fe18-43a5-a6d8-338d9733f2b1)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 12d.8h.9m
Firefox: 114
filterset (summary):
 network: 252781
 cosmetic: 224237
 scriptlet: 40460
 html: 1135
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68361-6977, 1h.47m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91727-79377, now
  adguard-generic: 71993-5398, now
  adguard-mobile: 8298-124, now
  adguard-spyware-url: 1097-5, now
  block-lan: 47-0, now
  curben-phishing: 117597-40, 1h.44m
  curben-pup: 199-0, 1h.45m
  adguard-social: 20716-685, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 47623-267, now
  fanboy-social: 16097-17, now
  [2 lists not shown]: [too many]
 default:
  user-filters: 2-1, never
  ublock-filters: 34540-106, now
  ublock-badware: 7611-0, now
  ublock-privacy: 457-0, now
  ublock-unbreak: 2088-1, now
  ublock-quick-fixes: 276-0, 1h.43m
  easylist: 67550-932, now
  easyprivacy: 30611-692, now
  urlhaus-1: 6551-0, 1h.46m
  plowe-0: 3738-2, now
filterset (user): [array of 2 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 556 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel:
 blocked: 2
 network:
  sentry.io: 2
 extended:
  ##.c-adSkyBox
  ##.c-adDisplay_container
  ##.c-adDisplay
  ##.c-socialSharebar_container
  ##.ot-sdk-show-settings
  ##div.c-newsletterSignup
  ##.onetrust-pc-dark-filter
  ##.c-contentHeader > div.c-socialSharebar
  ###ot-sdk-btn
  ##body #ot-sdk-btn
  #@##onetrust-consent-sdk
```
</details>

**Comment by krystian3w** [comment]
For uBo shouldn't problem hide dynamic injected elements.

As if this were a big problem, many ads would suddenly have to be addressed with network filters or scriptlets.

**Comment by dportvine** [comment]
@ctison 
>I've created the following filter: `www.zdnet.com###onetrust-consent-sdk` But it doesn't work, maybe because:

This exception `zdnet.com#@##onetrust-consent-sdk` from **fanboy-cookiemonster**

**Comment by gorhill** [comment]
AdGuard Cookies `@@||cdn.cookielaw.org^$from=zdnet.com` cancels EasyList Cookies `/otbannersdk.js`. Using either lists work, using both prevent the proper filters from working. I don't know which one is right.

cc @ryanbr, @Yuki2718

**Comment by ctison** [comment]
Thank you all, I disabled `AdGuard Annoyances filter` and now it works.
Much love.

**Comment by gorhill** [comment]
The issue is going to come back, we need to find a solution for this as this is a high traffic site.

I lean toward EasyList Cookies being right because `#onetrust-banner-sdk` is not necessary when applying `/otbannersdk.js`. For now I will add `/otbannersdk.js$important,script,domain=zdnet.com` in uBO Cookies.

**Comment by krystian3w** [comment]
I would be more inclined in checking whether both methods spoil embedded videos in articles, if they spoil it is more likely that someone will complain about spoiling the site even if the video is of the self-promo kind and loosely related to a particular open news item.

That's why it was better not to address such problems, because the site is afraid of being fined for banning Google services or 25 million euros for not complying with "GDPR."

**Comment by gorhill** [comment]
The only videos I found were Youtube ones and they played fine.

**Comment by peace2000** [comment]
I think it's not a good idea to block GDPR scripts on sites that say they have "necessary cookies" because they might not get activated and breakages might occur. It's very laborious task to test a website thoroughly to make sure no breakages occur.

It's ok to block GDPR scripts if you manually set necessary / functional cookies for the page... But unless that is done, it's not a good idea to block the script.

I think that even functional cookies should be allowed because they are not used for tracking but website functions (save settings the user might set).

**Comment by peace2000** [comment]
To be on the safe side, I'd go with these:

```
zdnet.com##+js(trusted-set-cookie, OptanonAlertBoxClosed, $currentDate$, 1year)

zdnet.com##+js(trusted-set-cookie, OptanonConsent, groups=C0001%3A1%2CC0002%3A0%2CC0003%3A1%2CC0004%3A0%2CC0005%3A0, 1year)
```

Those will set necessay and functional cookies activated. We already have filters for Optanon, and I'm not comfortable blocking their scripts because that has caused issues on many websites.

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/commit/665aa51c7a59509dada06136334b9bd743f29302 adjusted the current filters in order to make sure no breakages happen.

**Comment by Yuki2718** [comment]
The exception was based on an old issue https://github.com/AdguardTeam/AdguardFilters/issues/48848 I can't reproduce any more. A similar one was https://github.com/AdguardTeam/AdguardFilters/issues/58146 and not reproduced either. So I guess removeing the exception is an option. @BlazDT @Alex-302

**Comment by peace2000** [comment]
![kuva](https://github.com/uBlockOrigin/uAssets/assets/17256841/f15103c4-9291-4b50-9711-98961c517ae3)

![kuva](https://github.com/uBlockOrigin/uAssets/assets/17256841/079a9eee-e262-4f0c-80ef-0c353c891333)

The way how the page describes their necessary and functional cookies, I'm not comfortable disabling GDPR scripts. Issues might surface later that might not become visible during short period of testing.

**Comment by gorhill** [comment]
> how the page describes their necessary and functional cookies

What websites say about themselves shouldn't get priority over our findings. If we do not see breakage, then there is no need to use a `trusted-` scriptlet over a more mainstream solution.

**Comment by Alex-302** [comment]
On my end with US IP Youtube works, but embed tweens - no (partially loaded, and fully - after accept cosial cookies).

<details>
<summary>Details</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/8361299/cb2ead89-8241-4bd1-98aa-22dce403b198)


</details>

https://www.zdnet.com/article/samsung-blu-ray-players-are-rebooting-in-a-loop-and-nobody-knows-why/

**Comment by peace2000** [comment]
I checked old issues concerning the page on EL repo.

Found this link https://www.zdnet.com/article/new-wi-fi-attack-cracks-wpawpa2-passwords-with-ease/

On my end, videos are not working without setting those cookies.

**Comment by peace2000** [comment]
@Alex-302 I can repro that too from Finnish IP.

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b607cd4435889fdb25b9a8bf35121c8fdae31633

Changed to current filter this way.

Added example links with a comment saying what's broken.

The filter sets mandatory, functional and social media cookies accepted.

**Comment by Alex-302** [comment]
@peace2000 Can I remove an exclusion for uBO?
```adblock
!+ PLATFORM(ios, ext_android_cb, ext_safari, ext_ublock)
zdnet.com#@##onetrust-consent-sdk
```

**Comment by peace2000** [comment]
@Alex-302 Can you do that later? These set cookie filters are still not in use in stable version of uBO, only in dev build.

**Comment by Alex-302** [comment]
Ok.
