### ISSUE TITLE
gamicsoft.com: ads

### ISSUE THREAD

**Issue by JOJOforshaun** [uBlockOrigin/uAssets#18694]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gamicsoft.com/zh/article/GpWMeN7CmWae/%E5%85%A8%E6%96%B0%E6%B8%B8%E6%88%8F%E6%A8%A1%E5%BC%8F%E5%8D%B3%E5%B0%86%E7%99%BB%E9%99%86-macos-14-sonoma%E6%8F%90%E5%8D%87%E8%8B%B9%E6%9E%9C%E8%AE%BE%E5%A4%87%E4%B8%8A%E7%9A%84aaa%E6%B8%B8%E6%88%8F%E4%BD%93%E9%AA%8C`

### Category

ads

### Description

The page is surrounded by advertising content
<img width="1280" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/63553362/48f2ba5d-dc0e-427f-a795-6c3281f47557">
<img width="271" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/63553362/6adf3c26-d6a7-463e-afe6-7abc0213636d">

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.21m
Chromium: 114
filterset (summary):
 network: 94195
 cosmetic: 40666
 scriptlet: 21311
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
 added:
  ublock-annoyances: 5301-7, 2h.37m
 default:
  user-filters: 1-0, never
  easylist: 67532-50, 2h.37m
  easyprivacy: 30611-56, 2h.37m
  plowe-0: 3738-956, 2h.37m
  ublock-badware: 7609-138, 2h.37m
  ublock-filters: 33666-141, 2h.37m
  ublock-privacy: 416-3, 2h.37m
  ublock-quick-fixes: 275-47, 2h.37m
  ublock-unbreak: 2061-36, 2h.37m
  urlhaus-1: 6551-0, 2h.37m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1987 ms (selfie)
 maxAssetCacheWait: 266 ms
popupPanel:
 blocked: 26
 network:
  doubleclick.net: 3
  facebook.net: 1
  google.com: 5
  googletagmanager.com: 1
  youtube.com: 16
 extended:
  ##.mobile-ads
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
1. chinese site, enable the regional list
2. add

`gamicsoft.com##.hidden:has([onclick*="gtag"])`

report here for chinese sites
https://github.com/cjx82630/cjxlist/issues

@cjx82630

**Comment by JOJOforshaun** [comment]
学习

> 1. 中文站点，启用区域列表
> 2. 添加
> 
> `gamicsoft.com##.hidden:has([onclick*="gtag"])`
> 
> 在这里报告中国网站 https://github.com/cjx82630/cjxlist/issues
> 
> @cjx82630

实际上这是一个英文/中文站点，我还漏了首页还有两个广告没去掉，我也尝试使用了中文列表，和你的规则，但是没用
https://gamicsoft.com/
<img width="1267" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/63553362/2c324c82-3279-4380-8cf6-feb146694540">
<img width="1157" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/63553362/0baada41-8b5b-48c2-8364-6f5ff6a5978c">

**Comment by mapx-** [comment]
- see above, I added another filter
- if english too report at easylist repository @ryanbr
