### ISSUE TITLE
byjus.com: nuisance

### ISSUE THREAD

**Issue by libreom** [uBlockOrigin/uAssets#18699]
ر### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://byjus.com/question-answer/a-point-charge-q-is-placed-on-the-axis-of-a-ring-of-radius-r/`

### Category

nuisance

### Description

After scrolling little bit or waiting for some seconds this popup appears on both default lists and with all annoyances list. Please fix on whichever list ypu see fit

### Other extensions used

Bitwarden

### Screenshot(s)

<details>

<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/111110599/d7000ec7-8dbe-4aea-ad9f-d47e48b1934e)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.23h.40m
Chromium: 109
filterset (summary):
 network: 104048
 cosmetic: 183299
 scriptlet: 26215
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26103-29, 7m
  adguard-mobile-app-banners: 4361-5, 7m
  adguard-other-annoyances: 12955-6, 7m
  adguard-popup-overlays: 22763-58, 7m
  adguard-social: 20718-876, 7m
  adguard-widgets: 2186-3, 7m
  easylist-annoyances: 3874-181, 7m
  easylist-chat: 126-9, 7m
  easylist-newsletters: 6137-348, 7m
  easylist-notifications: 2633-1421, 7m
  fanboy-cookiemonster: 47624-3776, 7m
  fanboy-social: 16097-683, 7m
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 67554-106, 7m
  easyprivacy: 30611-187, 7m
  plowe-0: 3738-958, 7m
  ublock-badware: 7624-138, 7m
  ublock-filters: 33671-550, 7m
  ublock-privacy: 416-5, 7m
  ublock-quick-fixes: 281-47, 7m
  ublock-unbreak: 2061-39, 7m
  urlhaus-1: 6551-0, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8592 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel:
 blocked: 10
 network:
  boldchat.com: 1
  byjusweb.com: 4
  cloudflareinsights.com: 1
  google-analytics.com: 1
  googletagmanager.com: 3
 extended:
  ##body:style(overflow: visible !important; padding-right: 0 !imp…
```
</details>

**Comment by mapx-** [comment]
report at one of the annoyances lists
