### ISSUE TITLE
abcya.com: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18692]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Cookie notice being hidden from the EasyList/AdGuard Cookie Notices lists leaves a gap at the top of the page.

### URL(s) where the issue occurs.

`https://www.abcya.com/`

### Screenshot(s)

![Screenshot from 2023-06-27 00-37-09](https://github.com/uBlockOrigin/uAssets/assets/89158249/2408eab4-8d6d-456d-822a-e0a3cbad5c89)
![Screenshot from 2023-06-27 00-37-13](https://github.com/uBlockOrigin/uAssets/assets/89158249/3cdf5809-7d4a-4950-ae5f-aff91be99358)

### uBO version

v1.50.1b6

### Browser name and version

Firefox 114.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by mapx-** [comment]
> Cookie notice being hidden from the EasyList/AdGuard Cookie Notices lists leaves a gap at the top of the page.

report exactly at their repositories

**Comment by marbens-arch** [comment]
easylist/easylist#23899

**Comment by mapx-** [comment]
fixed https://github.com/uBlockOrigin/uAssets/commit/e85e9d8e70bba4e1529b596ec9bd447aca29925e

**Comment by Sonic5435325** [comment]
Thanks!
