### ISSUE TITLE
doubtnut.com: detection

### ISSUE THREAD

**Issue by libreom** [uBlockOrigin/uAssets#18698]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.doubtnut.com/question-answer/how-to-ask-question-on-doubtnut-what-should-i-do-to-get-better-search-results-what-is-the-best-way-t-1679708`

### Category

detection

### Description

It detects ublock origin and tells to purchase premium subscription, I have enabled annoyances filter It still didnt go away. Add new filters in whichever list you see fit

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/111110599/df395d4c-296a-4ba8-8498-68e2c0e81524)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.23h.33m
Chromium: 109
filterset (summary):
 network: 104048
 cosmetic: 183299
 scriptlet: 26215
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26103-29, now
  adguard-mobile-app-banners: 4361-5, now
  adguard-other-annoyances: 12955-6, now
  adguard-popup-overlays: 22763-58, now
  adguard-social: 20718-876, now
  adguard-widgets: 2186-3, now
  easylist-annoyances: 3874-181, now
  easylist-chat: 126-9, now
  easylist-newsletters: 6137-348, now
  easylist-notifications: 2633-1421, now
  fanboy-cookiemonster: 47624-3776, now
  fanboy-social: 16097-683, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 67554-106, now
  easyprivacy: 30611-187, now
  plowe-0: 3738-958, now
  ublock-badware: 7624-138, now
  ublock-filters: 33671-550, now
  ublock-privacy: 416-5, now
  ublock-quick-fixes: 281-47, now
  ublock-unbreak: 2061-39, now
  urlhaus-1: 6551-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8592 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel:
 blocked: 10
 network:
  doubtnut.com: 3
  datadoghq-browser-agent.com: 1
  doubleclick.net: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
 extended:
  ###Desktop_VideoPage_Side_Banner_1-container
  ###Web_VideoPage_Banner_Resposive_1-container
  ##.ima-ad-container
```
</details>

**Comment by gorhill** [comment]
This works:

    doubtnut.com##img[alt="adfree_icon_web_accordion"]:upward(.px-2)

**Comment by mapx-** [comment]
@ryanbr @Alex-302

**Comment by Alex-302** [comment]
Not detection. Added to `AdGuard Other Annoyances filter`
