### ISSUE TITLE
YouTube advert not blocked

### ISSUE THREAD

**Issue by ethus3h** [uBlockOrigin/uAssets#187]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=v6IAJOOmDMg`

### Describe the issue

When opening that page in Firefox ESR with uBlock Origin with all but "experimental" and EasyList w/o element hiding, an advert is loaded (for a movie I think).

### Screenshot(s)

![screenshot_2016 11 10_18 09 24](https://cloud.githubusercontent.com/assets/10457522/20198106/ddfc18d0-a770-11e6-89eb-7b57d154ec0e.png)

### Versions

- Browser/version: Firefox 45.4.0
- uBlock Origin version: 1.9.16

### Settings

- See attached settings file: [my-ublock-backup_2016-11-10_18.10.49.txt](https://github.com/uBlockOrigin/uAssets/files/584644/my-ublock-backup_2016-11-10_18.10.49.txt)

### Notes

The advert can be blocked with the filter rule `extremereach.io`.

**Comment by gorhill** [comment]
Whoever can reproduce will have to figure a solution. You have so many filter lists selected that it could be one of them causing an issue. Try with default filter lists only.

**Comment by ethus3h** [comment]
Unfortunately the ad being shown on that video is a different one now, so I can't work on debugging this issue. On the upside, the default filters work for the one that is there now. Sorry for the bother. Thanks. :)
