### ISSUE TITLE
earn.hostadviser.net: ads, privacy

### ISSUE THREAD

**Issue by libreom** [uBlockOrigin/uAssets#18702]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://earn.hostadviser.net/`

### Category

ads

### Description

There are leftover ads which point to scammy site screenshot provided, also there are some bad for privacy scripts left like pubscale.com

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/111110599/26b4b9e8-aa88-4d25-8b4f-43320abbe131)</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.22m
Chromium: 109
filterset (summary):
 network: 93935
 cosmetic: 39237
 scriptlet: 17756
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67554-50, 48m
  easyprivacy: 30611-56, 48m
  plowe-0: 3738-956, 48m
  ublock-badware: 7624-138, 48m
  ublock-filters: 33671-140, 48m
  ublock-privacy: 416-3, 48m
  ublock-quick-fixes: 281-47, 48m
  ublock-unbreak: 2061-35, 48m
  urlhaus-1: 6551-0, 48m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8592 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel:
 blocked: 4
 network:
  clarity.ms: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  jsdelivr.net: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.blogAd
  ###horizontal-ad
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
- shortener crap
- the place for such things => https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by libreom** [comment]
It is in middle of a shortener but it is not a detection issue

**Comment by mapx-** [comment]
it's an ad on a useless shortener page, so still No.
