### ISSUE TITLE
embibe.com: nuisance

### ISSUE THREAD

**Issue by libreom** [uBlockOrigin/uAssets#18701]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.embibe.com/questions/The-figure-shows-a-charge-q-placed-inside-a-cavity-in-an-uncharged-conductor.-Now-if-an-external-electric-field-is-switched-on%0A%0A/EM7076460`

### Category

nuisance

### Description

After clicking on blue solution button, answer appears but it is behind overlay and popups which asks to signup and provides no way to close it and view answer without creating an account. I tried with annoyances enabled and disabled, it still appears. I think it should be on main lists but put it where you see fit

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/111110599/f5f42916-67b3-4e3e-9f62-2ed30fe2cc4e)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 2d.1m
Chromium: 109
filterset (summary):
 network: 93935
 cosmetic: 39237
 scriptlet: 17756
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67554-50, 28m
  easyprivacy: 30611-56, 28m
  plowe-0: 3738-956, 28m
  ublock-badware: 7624-138, 28m
  ublock-filters: 33671-140, 28m
  ublock-privacy: 416-3, 27m
  ublock-quick-fixes: 281-47, 27m
  ublock-unbreak: 2061-35, 27m
  urlhaus-1: 6551-0, 27m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8592 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
Tt seems to be a kind of paywall.
Even if we could hide the "popup" I doubt you can continue without an account

**Comment by libreom** [comment]
Its not a paywall answer does appear and can be seen dark in screenshot. After deleting overlay and popup with inspect element, answer is there

**Comment by gorhill** [comment]
So `embibe.com##.ReactModalPortal` then?

**Comment by mapx-** [comment]
or to avoid breakages

`embibe.com##.ReactModalPortal:has-text(mobile)`

**Comment by mapx-** [comment]
added in annoyances list

**Comment by libreom** [comment]
Thanks It works, there is blink of some elements for a split second which I don't mind
