### ISSUE TITLE
vedantu.com: nuisance

### ISSUE THREAD

**Issue by libreom** [uBlockOrigin/uAssets#18700]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.vedantu.com/question-answer/on-the-set-n-of-all-natural-numbers-define-the-class-12-maths-cbse-5f0c6312bc589953e415aeda`

### Category

nuisance

### Description

After some seconds and scrolling, a popup appears for signup which is distracting for study. I have tried with both annoyances disabled and enabled. Please add to whichever list it is applicable

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/111110599/80de6cc5-28ab-40a2-8189-dbb6bd17c20c)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.23h.48m
Chromium: 109
filterset (summary):
 network: 104048
 cosmetic: 183299
 scriptlet: 26215
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26103-29, 15m
  adguard-mobile-app-banners: 4361-5, 15m
  adguard-other-annoyances: 12955-6, 15m
  adguard-popup-overlays: 22763-58, 15m
  adguard-social: 20718-876, 15m
  adguard-widgets: 2186-3, 15m
  easylist-annoyances: 3874-181, 15m
  easylist-chat: 126-9, 15m
  easylist-newsletters: 6137-348, 15m
  easylist-notifications: 2633-1421, 15m
  fanboy-cookiemonster: 47624-3776, 15m
  fanboy-social: 16097-683, 15m
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 67554-106, 15m
  easyprivacy: 30611-187, 15m
  plowe-0: 3738-958, 15m
  ublock-badware: 7624-138, 15m
  ublock-filters: 33671-550, 15m
  ublock-privacy: 416-5, 15m
  ublock-quick-fixes: 281-47, 15m
  ublock-unbreak: 2061-39, 15m
  urlhaus-1: 6551-0, 15m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8592 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel:
 blocked: 24
 network:
  vedantu.com: 15
  algolia.io: 1
  amplitude.com: 1
  datadoghq.com: 4
  google-analytics.com: 1
  googletagmanager.com: 1
  moengage.com: 1
 extended:
  ##div[class^="Main_automatedSideBar"] > div[class^="AutomatedMod…
  ##+js(addEventListener-defuser, contextmenu, preventDefault)
```
</details>

**Comment by mapx-** [comment]
report at one of the annoyances lists
