### ISSUE TITLE
github.com: breakage

### ISSUE THREAD

**Issue by timmwille** [uBlockOrigin/uAssets#18703]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://github.com/opencultureagency/defyhatenow/blob/master/CAMEROON/SocialMedia-FieldGuide/counter%20hate%20speech.pdf`

### Category

breakage

### Description

GitHub embedded binary files seem not to work as preview when activated

### Other extensions used

yes, but narrowed it down to uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/8081055/7c45ff08-7175-4499-83f8-4a120d80026f)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.22h.39m
Firefox: 114
filterset (summary):
 network: 93898
 cosmetic: 39240
 scriptlet: 17730
 html: 962
listset (total-discarded, last-updated):
 removed:
  DEU-0: null
 default:
  user-filters: 3-0, never
  ublock-filters: 34545-87, now
  ublock-badware: 7626-0, now
  ublock-privacy: 457-0, now
  ublock-unbreak: 2088-0, now
  easylist: 67554-728, now
  easyprivacy: 30611-613, now
  urlhaus-1: 6511-0, now
  plowe-0: 3738-2, now
  ublock-quick-fixes: 283-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 18417 ms (selfie)
 maxAssetCacheWait: 2930 ms
popupPanel:
 blocked: 6
 network:
  github.com: 6
```
</details>

**Comment by dportvine** [comment]
Unable to reproduce

<details>
<summary>Screen</summary>

![2023-06-27_163218](https://github.com/uBlockOrigin/uAssets/assets/111344219/1a8a1735-d054-4882-8272-9fc361b885a7)
</details>

**Comment by iam-py-test** [comment]
Reset uBlock Origin to default settings, disable *all* other browser extensions (except Multi Account Containers, if installe), and retest.

**Comment by gorhill** [comment]
> Other extensions used
> 
> yes, but narrowed it down to uBlock

Sometimes other extensions can cause negative interferences with uBO,  since nobody can reporoduce verifying that the issue still exists after wholly disabling other extensions is important.
