### ISSUE TITLE
loadurl.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1871]
URL(s) where the issue occurs

`http://loadurl.com/qdrWjkK1`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
Bad Request

**Comment by KiLL4FuNK** [comment]
`https://loadurl.net/qdrWjkK1`

Anti-Adblock

**Comment by IThinkIAmCool** [comment]
are the websites down?

**Comment by IThinkIAmCool** [comment]
Are the websites inactive?
