### ISSUE TITLE
fandom.com: breakage

### ISSUE THREAD

**Issue by nardello** [uBlockOrigin/uAssets#18715]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Recently gallery image links on Fandom sites started breaking, refreshing the page when clicked instead of opening a preview.

### URL(s) where the issue occurs.

`https://capcom.fandom.com/wiki/Gallery:Bishamon` (used for demonstration)
any fandom wikia

### Screenshot(s)

[2023-06-27 22-09-08.webm](https://github.com/uBlockOrigin/uAssets/assets/127932903/4ed2a79b-1ca5-4d04-9aa1-2c1bcdb38412)

### uBO version

1.50.0

### Browser name and version

Firefox 114.0.2

### Settings

None.

### Notes

tested with a fresh, default install of both firefox and ubo, no user rules or filters used. i used a random page on the capcom wikia for the example, but it occurs on any wikia site i tired

**Comment by krystian3w** [comment]
First of all, it seems that the cookie/gdpr shutdown scriptlets are not working well enough there.

---

Once we embrace manually closing cookies/gdpr to consent to all their machlokes (hustling) then some script is blocked by one of the lists:



EasyList

EasyPrivacy

Peter Lower Ads/Trackers

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=fandom.com
@@||cdn.optimizely.com/js/$script,domain=fandom.com
```

@ryanbr

**Comment by krystian3w** [comment]
But still break with these:

https://github.com/uBlockOrigin/uAssets/blob/deffd40ec9c51c690e8e8998fc9414f7c30df5ce/filters/annoyances-cookies.txt#L61-L64

**Comment by krystian3w** [comment]
Too fastly (https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted), that was not fixed by peace2000:

https://github.com/uBlockOrigin/uAssets/issues/18715#issuecomment-1610842153

**Comment by peace2000** [comment]
> First of all, it seems that the cookie/gdpr shutdown scriptlets are not working well enough there.
> 
> Once we embrace manually closing cookies/gdpr to consent to all their machlokes (hustling) then some script is blocked by one of the lists:
> 
> EasyList
> 
> EasyPrivacy
> 
> Peter Lower Ads/Trackers

@krystian3w Those set cookie filters don't work on the stable version of uBO so they weren't causing this issue.

**Comment by krystian3w** [comment]
But I tested in uBo test, you should too if these can still bad: https://github.com/uBlockOrigin/uAssets/commit/df5417a8a480aa03db99e01f4e9d3ab312b87fed
