### ISSUE TITLE
midwestgunworks.com: detection

### ISSUE THREAD

**Issue by Resilient9696** [uBlockOrigin/uAssets#18710]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.midwestgunworks.com/`

### Category

detection

### Description

Blocks access to website, says adblocker detected

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.1h.57m
Chromium: 114
filterset (summary):
 network: 103544
 cosmetic: 183128
 scriptlet: 26079
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68312-97, 3d.55m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91673-20978, 3d.54m
  adguard-social: 20691-1529, 3d.46m
  fanboy-social: 16095-16095, 3d.57m
  fanboy-thirdparty_social: 69-18, 3d.56m
  ublock-annoyances: 5208-244, 3d.52m
  ublock-quick-fixes: 282-13, 2h.21m
 default:
  user-filters: 0-0, never
  easylist: 67156-135, 3d.20h.25m
  easyprivacy: 30603-284, 3d.58m
  plowe-0: 3737-956, 3d.53m
  ublock-badware: 7585-137, 3d.51m
  ublock-filters: 33584-545, 3d.50m
  ublock-privacy: 411-5, 3d.49m
  ublock-unbreak: 2061-39, 3d.47m
  urlhaus-1: 6511-0, 2h.22m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 582 ms (selfie)
 maxAssetCacheWait: 271 ms
popupPanel:
 blocked: 4
 network:
  google-analytics.com: 1
  googletagmanager.com: 2
  livechatinc.com: 1
 extended:
  ##.newsletter-input
  ##.socialConnect
  ##.footer-social
  ##.back-to-top:not(body):not(html)
  ##[title="Back to Top"]
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/a79e065fc423c0163834438cb5a8075b56232b4c

**Comment by okiehsch** [comment]
@stephenhawk8054 can this be closed?
I can't reproduce either way, i.e. even if I manually add the removed filter ni detection on my end.

**Comment by stephenhawk8054** [comment]
@okiehsch Yes, I think it can be closed. Besides that, it looks like an age consent, do you think we should leave the banner for gun sites?

**Comment by okiehsch** [comment]
>  age consent

We should not fix a consent banner in the default lists, it's an annoyance at best.

**Comment by stephenhawk8054** [comment]
Yeah, I mean for annoyance list.

**Comment by okiehsch** [comment]
I really have no opinion on the matter, if you think it's an annoyance I am fine with that.
I don't think we it matters  if the consent is for guns, porn, drugs. etc.

**Comment by stephenhawk8054** [comment]
I see, I personally want to leave the consent for these types of sites, but I'm also not sure about my decision either. If more people complains about the annoyance, I think I'll address them in annoyance lists.
