### ISSUE TITLE
indie.onstove.com: ads

### ISSUE THREAD

**Issue by comiluv** [uBlockOrigin/uAssets#18712]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://indie.onstove.com/ko/store/recommend`

### Category

ads

### Description

A blocking ad in the middle of the web page. Only disappears if the user clicks the button next to the checkbox or the 닫기 button.
Adding a custom filter `indie.onstove.com###common-popup-wrapper` removes the ad but also disables the scroll bar from the web page.

### Other extensions used

Better Histor
CustomBlocker
Ghostery
Mute Tabs by Url
Picture-in-Picture Extension (by Google)
Save Page WE
Simple mass downloader
Skip Redirect
SuperCopy
Superior allow copy
Vimium
Web Developer
YouTube - Pause with Space Properly
YouTube Auto HD

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1900" alt="스크린샷 2023-06-28 120146" src="https://github.com/uBlockOrigin/uAssets/assets/19642705/f50cb3d7-5012-4eda-906a-f3070d0c4b12">
</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 26m
Chromium: 114
filterset (summary):
 network: 95161
 cosmetic: 42423
 scriptlet: 17869
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  KOR-1: 4570-15, 2m
  easylist: 67575-92, 2m
  easyprivacy: 30615-66, 2m
  plowe-0: 3739-969, 2m
  ublock-badware: 7629-138, 2m
  ublock-filters: 33636-143, 2m
  ublock-privacy: 416-5, 2m
  ublock-quick-fixes: 282-47, 2m
  ublock-unbreak: 2052-36, 2m
  urlhaus-1: 6604-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 598 ms
 maxAssetCacheWait: 8 ms
popupPanel:
 blocked: 97
 network:
  81plug.com: 16
  doubleclick.net: 10
  google.com: 12
  googletagmanager.com: 3
  youtube.com: 56
 extended:
  ##.ytp-ad-progress-list
  ##.ytp-title-channel
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||static-cdn.onstove.com/*/stove-common-popup/$1p
```

I'm not sure which list should fix it? It's a Korean site, but has an English version

**Comment by krystian3w** [comment]
Maybe enough is override generic locking scroll:

```adb
!#if ext_abp
||static-cdn.onstove.com/*/stove-common-popup/$1p
!#endif
||static-cdn.onstove.com/*/stove-common-popup/$1p,badfilter
indie.onstove.com##body[style*="hidden"]:style(overflow: visible !important; position: static !important)
indie.onstove.com###common-popup-wrapper
```

as other pop-ups have the same method blocked scrolling then only procedural filtering or CSS4 will allow it not to be affected.


---

I do not know if the site aggressively docks the style attribute to the html code, then you can check such a thing too:

```adb
indie.onstove.com##body[style*="hidden"]:remove-attr([style])
```

```adb
! only for less agressive reinjection
indie.onstove.com##body[style*="hidden"]:remove-attr([style])
! agressive can forces jumping of layout at vertical edge or whole of page
```

**Comment by krystian3w** [comment]
piquark6046 marked as self-promo: https://github.com/AdguardTeam/AdguardFilters/commit/085bc5c1d68004f97fb90573d4824b24ea24f1ed

**Comment by mapx-** [comment]
@ryanbr for FA

already fixed by AA
