### ISSUE TITLE
merlininkazani.com: detection

### ISSUE THREAD

**Issue by qzcz** [uBlockOrigin/uAssets#18716]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.merlininkazani.com/`

### Category

detection

### Description

"disable adblock" notice

### Other extensions used

Bitwarden, Simple Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/110184059/356d75b6-89d1-4435-ab9a-ba1c76634f0c)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 15d.8h.24m
Firefox: 114
filterset (summary):
 network: 141026
 cosmetic: 130072
 scriptlet: 25937
 html: 1136
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  adguard-spyware-url: 1097-5, now
  adguard-spyware: 61824-13594, now
  adguard-social: 20721-164, now
  adguard-cookies: 26107-38, now
  adguard-popup-overlays: 22768-964, now
  adguard-mobile-app-banners: 4365-4, now
  adguard-other-annoyances: 12999-59, now
  adguard-widgets: 2187-1, now
  ublock-annoyances: 5259-12, now
 default:
  user-filters: 48-0, never
  ublock-filters: 34510-476, now
  ublock-badware: 7631-0, now
  ublock-privacy: 457-0, now
  ublock-unbreak: 2081-1, now
  ublock-quick-fixes: 283-0, now
  easylist: 67585-477, now
  easyprivacy: 30615-35, now
  TUR-0: 13564-11, now
filterset (user): [array of 54 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 suspendUntilListsAreLoaded: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1050 ms (selfie)
 maxAssetCacheWait: 455 ms
 unsuspendAfter: 509 ms
popupPanel:
 blocked: 12
 network:
  doubleclick.net: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
  jsdelivr.net: 2
  publisher-network.com: 2
  yandex.ru: 1
  youtube.com: 2
 extended:
  ##ins.adsbygoogle
  ##.adsbygoogle
  ##.ytp-share-button
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##html:style(overflow:auto!important)
  ##html:style(overflow: auto !important; padding-right: 0 !import…
```
</details>

**Comment by okiehsch** [comment]
`merlininkazani.com##+js(nostif, onDetected)`
@Yuki2718 for the regional adguard turkish list.

**Comment by stephenhawk8054** [comment]
I think it's a generic anti-adb, so Adguard will fix in main list instead of regional.

**Comment by okiehsch** [comment]
Ok, I will add the fix to our list.

**Comment by Yuki2718** [comment]
I'm not sure, but guess `||merlininkazani.com/js/abdetector.script.min.js` can be added to Turkish list.
