### ISSUE TITLE
get.mtraffics.com/cINaiNM: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18719]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://techacode.com/good-designers-redesign-nice-designers-realign-a-listing-aside/`

### Category

detection

### Description

this shortlink site ads blocked. but get link button not working. (below screenshot)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/75168867/6a704a78-1354-4198-8971-5dd3d5965197)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.1h.27m
Chromium: 114
filterset (summary):
 network: 93958
 cosmetic: 39229
 scriptlet: 17749
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67533-50, 34m
  easyprivacy: 30616-56, 34m
  plowe-0: 3739-957, 34m
  ublock-badware: 7629-138, 34m
  ublock-filters: 33642-140, 34m
  ublock-privacy: 416-3, 34m
  ublock-quick-fixes: 282-47, 34m
  ublock-unbreak: 2055-35, 34m
  urlhaus-1: 6604-0, 34m
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14326 ms (selfie)
 maxAssetCacheWait: 1066 ms
popupPanel:
 blocked: 8
 network:
  adverbrequire.com: 2
  canastagruff.com: 1
  doubleclick.net: 1
  exmarketplace.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  vidcrunch.com: 1
 extended:
  ##.gptslot
  ##ins.adsbygoogle
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(no-setTimeout-if, nextFunction, 250)
  ##+js(nobab)
  ##+js(window.open-defuser)
  ##+js(noeval-if, adb)
```
</details>

**Comment by krystian3w** [comment]
more breakage

**Comment by okiehsch** [comment]
It's nroken by our filter
`techacode.com##+js(nowoif)`
