### ISSUE TITLE
ancientrom.xyz: detection

### ISSUE THREAD

**Issue by NathNLM** [uBlockOrigin/uAssets#18714]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ancientrom.xyz/`

### Category

detection

### Description

anti-adblocker page redirection even after turning off ublock (maybe it checks if it's installed?)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 14d.23h.27m
Firefox Mobile: 114
filterset (summary):
 network: 113058
 cosmetic: 35274
 scriptlet: 17867
 html: 957
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34734-381, 1d.28m
  ublock-badware: 7605-1, 16h.42m
  ublock-privacy: 457-1, 1d.29m
  ublock-unbreak: 2092-1, 1d.5h.31m
  adguard-mobile: 8289-121, 3d.16h.11m
  easylist: 66538-17506, 5d.17h.7m
  easyprivacy: 30609-619, 1h.29m
  urlhaus-1: 6604-0, 1h.28m
  plowe-0: 3735-1, 9d.4h.57m
  FRA-0: 28340-3281, 16h.41m
  ublock-quick-fixes: 283-0, 1h.27m
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 13799 ms (selfie)
 maxAssetCacheWait: 657 ms
popupPanel:
 blocked: 1
 network:
  googlesyndication.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> anti-adblocker page redirection even after turning off ublock (maybe it checks if it's installed?)

It means you are using some other methods of blocking, and it's not related to uBO any more. Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

---

Anyway, I cannot reproduce the issue with uBO's default settings.
