### ISSUE TITLE
uqload.com: breakage

### ISSUE THREAD

**Issue by AlexIs387** [uBlockOrigin/uAssets#18725]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBO it's blocking embedded videos from uqload.com

### A specific URL where the issue occurs.

uqload.com

### Steps to Reproduce

1. Trying to watch uqload.com embedded videos
2. Cannot see uqload.com embedded videos

### Expected behavior

Watch uqload.com embedded videos on external webpages

### Actual behavior

Cannot see uqload.com embedded videos

### uBO version

1.50.0

### Browser name and version

Microsoft Edge

### Operating System and version

Windows 10

**Comment by mapx-** [comment]
> Trying to watch uqload.com embedded videos

- provide page link with such embedded videos
- go into uBO dashboard, support tab, copy & paste here: Troubleshooting Information

**Comment by mapx-** [comment]
I tested the page you provided (and then removed ?!), no issue on my end.

`https://www.simpsonizados.cyou/08x14-el-espectaculo-de-tomy-daly-y-poochie/`

Provide the other info requested.

**Comment by AlexIs387** [comment]
> * provide page link with such embedded videos

https://www.simpsonizados.cyou/08x14-el-espectaculo-de-tomy-daly-y-poochie/

> * go into uBO dashboard, support tab, copy & paste here: Troubleshooting Information

uBlock Origin 1.50.0:
 since: 16d.14h.53m
Chromium: 114
filterset (summary):
 network: 124956
 cosmetic: 211485
 scriptlet: 40736
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68459-100, 6h.5m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91607-20952, 5d.21h.43m
  adguard-generic: 71916-509, 3d.22h.30m
  adguard-mobile: 8290-57, 3d.22h.30m
  ublock-annoyances: 5101-279, 6d.21h.35m
 default:
  user-filters: 4-0, never
  easylist: 67533-1023, 6h.5m
  easyprivacy: 30616-394, 6h.6m
  plowe-0: 3739-1045, 6h.11m
  spa-0: 3724-39, 6h.5m
  spa-1: 5311-222, 3d.22h.30m
  ublock-badware: 7629-368, 6h.5m
  ublock-filters: 33640-4138, 6h.5m
  ublock-privacy: 410-5, 6d.21h.36m
  ublock-quick-fixes: 284-49, 6h.5m
  ublock-unbreak: 2055-97, 6h.5m
  urlhaus-1: 6463-0, 6h.5m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3647 ms (selfie)
 maxAssetCacheWait: 1369 ms

**Comment by mapx-** [comment]
- still cannot reproduce using the same browser / lists
- follow ALL the indications bellow:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by gorhill** [comment]
I can reproduce, the issue is AdGuard Ads's `uqload.co##+js(abort-current-script, document.createElement, break;case $.)`.

**Comment by mapx-** [comment]
oh, 

> uBO uses default lists and settings.


@AlexIs387 add
`uqload.co#@#+js(abort-current-script, document.createElement, break;case $.)`

**Comment by mapx-** [comment]
@Alex-302

**Comment by AlexIs387** [comment]
Worked, thanks

**Comment by gorhill** [comment]
The scriptlet works fine in AdGuard. The site is using `RegExp.$1` as parameter to `createElement()`, but then uBO clobbers `RegExp.$1` when using its own internal regex because [`RegExp.$1`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n) is a (deprecated) static property.

**Comment by mapx-** [comment]
Well, we could add the exception above in unbreak list

**Comment by gorhill** [comment]
We probably should given AdGuard Base is a stock list. I am looking at ways to avoid clobbering `RegExp.$1`.

**Comment by mapx-** [comment]
Waiting for a fix I 'll add the exception.
