### ISSUE TITLE
criptologico.com: detection

### ISSUE THREAD

**Issue by monkeyde98** [uBlockOrigin/uAssets#18727]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://criptologico.com/tools/cc`

### Category

detection

### Description

This site is detecting ublock origin. I am using edge browser.

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 14d.6h.40m
Chromium: 114
filterset (summary):
 network: 95480
 cosmetic: 25870
 scriptlet: 18495
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt: 4549-39, 2d.22h.15m
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2023.txt: 3109-28, 2d.22h.15m
  spa-1: 5311-144, 2d.22h.15m
 default:
  user-filters: 957-151, never
  easylist: 67515-16764, 2d.22h.15m
  easyprivacy: 30608-58, 2d.22h.15m
  plowe-0: 3737-955, 2d.22h.15m
  ublock-badware: 7588-138, 2d.22h.15m
  ublock-filters: 33616-7927, 2d.22h.15m
  ublock-privacy: 416-4, 2d.22h.14m
  ublock-quick-fixes: 284-17, 4h.30m
  ublock-unbreak: 2061-37, 2d.22h.14m
  urlhaus-1: 6511-0, 23h.27m
filterset (user): [array of 1016 redacted]
trustedset:
 added: [array of 30 redacted]
switchRuleset:
 added: [array of 6 redacted]
hostRuleset:
 added: [array of 187 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 388 ms (selfie)
 maxAssetCacheWait: 127 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(abort-on-stack-trace, Object, /(?=^(?!.*(https)))/)
```
</details>

**Comment by gorhill** [comment]
Please remove the two custom lists (click _trashcan_ then _Apply changes_):

- https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt
- https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2023.txt

These are already included in _uBlock filters -- Ads_, you don't need to load them twice, this pointlessly waste computer resources and server bandwidth, all the filters in these lists are duplicates of what is already present in stock lists.

**Comment by monkeyde98** [comment]
It reappeared after going down and up the page around 10 seconds the ublock warning appears!

**Comment by lyubomyrhv** [comment]
Detection)
