### ISSUE TITLE
eksisozluk1923.com: breakage

### ISSUE THREAD

**Issue by zikembe** [uBlockOrigin/uAssets#18722]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://eksisozluk1923.com/basliklar/m/bugun`

### Category

breakage

### Description

Some links on the website not useable when UBO turned on.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 15d.10h.14m
Firefox Mobile: 116
filterset (summary):
 network: 97144
 cosmetic: 40886
 scriptlet: 22603
 html: 1140
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5320-10, now
 default:
  user-filters: 0-0, never
  ublock-filters: 34784-346, now
  ublock-badware: 7631-1, now
  ublock-privacy: 459-1, now
  ublock-unbreak: 2091-1, now
  ublock-quick-fixes: 285-0, now
  adguard-mobile: 8306-121, now
  easylist: 67433-17448, now
  easyprivacy: 30616-627, now
  urlhaus-1: 6463-0, now
  plowe-0: 3739-1, now
  TUR-0: 13564-205, now
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1293 ms
 maxAssetCacheWait: 453 ms
popupPanel:
 blocked: 14
 network:
  adpushup.com: 1
  adrecover.com: 1
  criteo.net: 2
  doubleclick.net: 3
  gelirartisi.com: 2
  googleadservices.com: 2
  googletagmanager.com: 1
  nativespot.com: 2
 extended:
  ##.ads
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ###interstitial-close-link-source:remove()
  ##+js(no-setTimeout-if, wt(), 100)
  ##+js(remove-attr, placeholder, input[id="search-textbox"])
```
</details>

**Comment by mapx-** [comment]
> aradığınız sayfa aslında yoktu
> 
ya da vardı ama artık yok. varsa bile ben bulamadım.
> 
[ana sayfa](https://eksisozluk1923.com/)

after providing a valid link

> Some links on the website not useable when UBO turned on.

indicate exactly what link is broken

**Comment by gorhill** [comment]
I can reproduce on home page. Click events are eaten the first click, then second click works.

Does this work?

    eksisozluk1923.com##.ad-banner:remove()

**Comment by zikembe** [comment]
The problem occurs when using a mobile browser (Firefox, in my case). I have been facing this issue for a long time with older versions of UBO as well. I have tried again and can reproduce the issue with almost all click events, as gorhill explained. However, the second click actions also don't trigger any response when i try.

**Comment by mapx-** [comment]
@zikembe 

answer the questions above testing the filter too

**Comment by zikembe** [comment]
@mapx- 

Sorry just was it.

Yes, with the custom filter 'eksisozluk1923.com##.ad-banner:remove()' applied, the website is no longer broken and now works. Thanks.

**Comment by mapx-** [comment]
@Yuki2718 maybe you could add it to turkish list ?

**Comment by krystian3w** [comment]
Page "fastly" change numbers, so maybe better address by regex in uBo?

https://github.com/AdguardTeam/AdguardFilters/commit/86cb66f1f0ef5c4fc63e6350371e133573e9bd8a

```adb
/eksisozluk[0-9]{0,4}\.com/##.ad-banner:remove()
```

And it doesn't appear that AdGuard has added translation of their regex into a version for uBo: https://github.com/AdguardTeam/tsurlfilter/issues/41

```adb
[$domain=//eksisozluk[0-9]{0,4}\.com/]##.ad-banner:remove()
```

**Comment by Yuki2718** [comment]
In fact, I can't access any more even with Turkish VPN.
