### ISSUE TITLE
app.recruitee.com: breakage

### ISSUE THREAD

**Issue by Fibs7000** [uBlockOrigin/uAssets#18723]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://learningsuite.io/karriere#job-positions`

### Category

breakage

### Description

The Job Widget of recruitee cannot be loaded since `d10zminp1cyta8.cloudfront.net/widget.js` gets blocked by uBlock.

You can also verify this on 

`https://learningsuite.io/karriere#job-positions` 

There should be the jobs listed under this heading.

If I disable uBlock then it works.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

# How it is with uBlock enabled

<img width="1482" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/16261713/e33c4b11-47d8-43b9-a44e-423933b2aea5">

# How it should be
<img width="1509" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/16261713/2aafd67d-1d6a-4083-a7e9-3d27f45fa786">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93915
 cosmetic: 39201
 scriptlet: 17714
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 67521-50, 2d.8h.46m
  easyprivacy: 30605-56, 2d.8h.45m
  plowe-0: 3737-954, 6d.8h.36m
  ublock-badware: 7570-138, 4d.4h.40m
  ublock-filters: 33577-140, 4d.4h.38m
  ublock-privacy: 416-3, 8h.58m
  ublock-quick-fixes: 282-14, 8h.56m
  ublock-unbreak: 2060-35, 4d.4h.39m
  urlhaus-1: 6604-0, 8h.57m
filterset (user): [empty]
trustedset: 
 added: [array of 12 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 565 ms (selfie)
 maxAssetCacheWait: 109 ms
popupPanel: 
 blocked: 37
 network: 
  d10zminp1cyta8.cloudfront.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  mxpnl.com: 1
  segment.io: 9
  sentry.io: 15
  stripe.com: 9
```
</details>

**Comment by mapx-** [comment]
@ryanbr
