### ISSUE TITLE
Unnessecary AdGuard Whitelists

### ISSUE THREAD

**Issue by alastortenebris** [uBlockOrigin/uAssets#18726]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fireemblem.fandom.com/wiki/Fire_Emblem_Wiki`

### Category

privacy

### Description

AdGuard Ads has its own whitelist. Unfortunately, this whitelist bypasses things that uBlock can fix via redirects.

For example, AdGuard Ads has the following filter: `@@||c.amazon-adsystem.com/aax2/apstag.js$from=fandom.com`. This filter overrides `||amazon-adsystem.com/*/apstag.js$script,redirect-rule=amazon_apstag.js:5`, despite the site in question (fandom) functioning perfectly fine without the whitelist.

This is one example, but there's probably more.

### Other extensions used

None. This is a fresh profile.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b6
Firefox: 114
filterset (summary):
 network: 111581
 cosmetic: 73613
 scriptlet: 32131
 html: 966
listset (total-discarded, last-updated):
 added:
  adguard-generic: 72038-5269, now
 default:
  user-filters: 0-0, never
  ublock-filters: 34520-87, now
  ublock-badware: 7653-1, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2088-1, now
  ublock-quick-fixes: 287-0, now
  easylist: 67454-731, now
  easyprivacy: 30617-614, now
  urlhaus-1: 6463-0, now
  plowe-0: 3739-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 973 ms
 maxAssetCacheWait: 415 ms
popupPanel:
 blocked: 25
 network:
  ad.gt: 2
  adsafeprotected.com: 1
  cpx.to: 1
  doubleclick.net: 1
  durationmedia.net: 1
  eyeota.net: 1
  fastly-insights.com: 3
  google-analytics.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  liadm.com: 1
  nocookie.net: 1
  quantserve.com: 1
  rlcdn.com: 1
  scorecardresearch.com: 1
  wikia-services.com: 7
 extended:
  ##.top-ads-container
  ##.ad-slot-placeholder
  ##.gpt-ad
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.bottom-ads-container
  ##[id^="google_ads_iframe"]
  ##+js(set-cookie, tracking_session_id, OK, , reload, 1)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
  ##+js(set-constant, wgAffiliateEnabled, false)
```
</details>

**Comment by gorhill** [comment]
Report to AdGuard repo please, we can't edit their lists from here.
