### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by sysgen1** [uBlockOrigin/uAssets#18731]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.investing.com/`

### Category

detection

### Description

It looks like you're using an ad-blocker

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-06-29 180543](https://github.com/uBlockOrigin/uAssets/assets/98539130/3d877611-af49-4c52-95b9-45c85b911546)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 16d.10h.42m
Chromium: 114
filterset (summary):
 network: 93813
 cosmetic: 42394
 scriptlet: 17885
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  KOR-1: 4522-12, 9m
  easylist: 67448-92, 9m
  easyprivacy: 30621-66, 9m
  plowe-0: 3739-973, 9m
  ublock-badware: 7651-139, 9m
  ublock-filters: 33648-145, 9m
  ublock-privacy: 418-5, 9m
  ublock-quick-fixes: 294-48, 9m
  ublock-unbreak: 2062-39, 9m
  urlhaus-1: 5362-0, 9m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 228 ms (selfie)
 maxAssetCacheWait: 101 ms
popupPanel:
 blocked: 18
 network:
  investing.com: 2
  ad-score.com: 4
  adnxs.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  dggaenaawxe8z.cloudfront.net: 1
  doubleclick.net: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  outbrain.com: 3
  scorecardresearch.com: 1
 extended:
  ##.dfpAdUnitContainer
  ###hpAdVideo
  ##.rightColumnAd
  ###ad1
  ###ad2
  ###ad3
  ###findABroker
  ##.generalOverlay
  ##.midHeader
  ##.sponsoredArticle
  ##+js(no-fetch-if, ads)
  ##+js(replace-node-text, script, /adb/i, xxx)
```
</details>

**Comment by stephenhawk8054** [comment]
> how can it get added to the AdBlockFilterList

Report to that repo: https://github.com/easylist/antiadblockfilters ?

**Comment by jmgv098** [comment]
Thanks for the commint @stephenhawk8054!
