### ISSUE TITLE
dailymail.co.uk: breakage

### ISSUE THREAD

**Issue by 101ron** [uBlockOrigin/uAssets#18737]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dailymail.co.uk/home/index.html`

### Category

breakage

### Description

i used to go on the site press the button and there gone. Now i just can't get rid of them. Ipress the button and then a scene come up saying will you get your blue circle back, so we can get add again. We never had that before, what's going on?

### Other extensions used

ABP that all. and uBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 16d.2h.53m
Firefox: 114
filterset (summary):
 network: 92547
 cosmetic: 39240
 scriptlet: 17729
 html: 968
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34524-54, now
  ublock-badware: 7668-0, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2095-3, now
  ublock-quick-fixes: 240-0, now
  easylist: 67455-735, now
  easyprivacy: 30606-615, now
  urlhaus-1: 5263-0, now
  plowe-0: 3739-2, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2480 ms (selfie)
 maxAssetCacheWait: 2204 ms
popupPanel:
 blocked: 105
 network:
  dailymail.co.uk: 7
  360yield.com: 1
  3lift.com: 1
  adnami.io: 1
  adnxs.com: 5
  akstat.io: 1
  amazon-adsystem.com: 1
  casalemedia.com: 1
  cdnopw.com: 1
  criteo.com: 1
  dotmetrics.net: 2
  edkt.io: 1
  fwpixel.com: 4
  go-mpulse.net: 2
  google.com: 6
  googletagmanager.com: 1
  googletagservices.com: 1
  id5-sync.com: 1
  imasdk.googleapis.com: 3
  kargo.com: 2
  omnitagjs.com: 1
  openx.net: 1
  permutive.app: 1
  pubmatic.com: 1
  quantummetric.com: 1
  rubiconproject.com: 2
  sharethrough.com: 11
  skimresources.com: 1
  smartadserver.com: 13
  spot.im: 3
  teads.tv: 1
  the-ozone-project.com: 2
  unrulymedia.com: 13
  yahoo.com: 11
 extended:
  ##.banner-adverts
  ##.puff-ad
  ###sky-left
  ###sky-right
  ##.mol-ads-label-container
  ##.mol-fe-vouchercodes-redesign
  ##.mpu_puff_wrapper
  ##.watermark
  ##.pufftext > .sponsored:upward(3)
  ##+js(abort-on-property-read, Notification)
  ##+js(abort-current-script, document.addEventListener, adverts)
```
</details>

**Comment by mapx-** [comment]
> ABP that all. and uBO

using ABP ? remove it completely (it's only source of conflicts, nothing else), update all filter lists in uBO and test again.

**Comment by okiehsch** [comment]
Reading the description I am not sure what the issue is exactly. 
I don't see any breakage on my end.

**Comment by gorhill** [comment]
The description is incomprehensible:

> press the button and there gone

What button?

> can't get rid of them

What is _them_?

> Ipress the button

What button?

> a scene come up

By a _scene_, you mean the site pops up a dialog box?

> get your blue circle back

What is that _circle_?

Provide screenshot(s) to show us what exactly is broken.

Also, as @mapx- already told you, you need to remove ABP as ta first step, you checked the box:

> - [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.

See <https://twitter.com/gorhill/status/1033706103782170625>.

**Comment by dportvine** [comment]
I only have this. Google Chrome 114.0.5735.199 [Gif](https://imgur.com/uf4CKO4)
```
https://www.dailymail.co.uk/femail/article-12165553/Amazon-shoppers-swear-citronella-candles-bugs-away-outdoor-dining.html
```
