### ISSUE TITLE
chip.de: ads

### ISSUE THREAD

**Issue by amaru7** [uBlockOrigin/uAssets#18739]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ublock doesn't remove these intrusive ads from "Web companion" and even adding a manual filter didn't work. Please add filter.

### URL(s) where the issue occurs.

`https://www.chip.de/download/`

### Screenshot(s)

![grafik](https://github.com/uBlockOrigin/uAssets/assets/14934650/507e443a-4930-422e-aa39-b7a470878e65)

### uBO version

1.50.0

### Browser name and version

Firefox 114

### Settings

Standard settings

**Comment by gorhill** [comment]
@JobcenterTycoon I had come up with:

    chip.de##a[target][href^="https://x.chip.de/"]:upward(div[id])

 `[name="randomString"][value]` is the element which contains the content of the page, I fear just picking the first `div` could cause legit stuff to be removed.

**Comment by JobcenterTycoon** [comment]
Okey i will check

**Comment by JobcenterTycoon** [comment]
A few ads doesn’t contain a `target` attribute and are different from site to site. Im ending up in this:

```
chip.de##a[target][href^="https://x.chip.de/"]:upward(div[id])
chip.de##div[id][style^="min-height:"][style*="min-width:"]:has(> a[href^="https://x.chip.de/"] > img[src^="https://im.chip.de/"])
chip.de###A.A[style="display: block;"]
```
It will cover all banner ads and the `Gesponserte Empfehlung` ad without high risk filter.

**Comment by amaru7** [comment]
@JobcenterTycoon That seemed to have worked, wonderful, kudos to you excellent!

Will that be added to the regular ublock filterlists too in the coming update?

**Comment by JobcenterTycoon** [comment]
I added these filter to the quick list now because the site is a known circumventor (see: https://github.com/easylist/easylistgermany/issues/216)

When there are no changes since weeks the filter will be moved to the regular filterlist.

**Comment by amaru7** [comment]
@JobcenterTycoon The same ads have returned unfortunately. They are quite stubborn.

**Comment by amaru7** [comment]
Unfortunately it has returned once again, this might be the most stubborn ad I had in a long long time.

**Comment by amaru7** [comment]
That sh*t ad returned again. Very subborn.

**Comment by JobcenterTycoon** [comment]
Works fine for me, also EL germany pushed a update https://github.com/easylist/easylistgermany/commit/67cff8e3fc41d12439b9ce8b6d6c840f96f10ab3 but to be sure https://github.com/uBlockOrigin/uAssets/commit/ec364e19c29cbb1a89d64674048f0a0d1d01e657
