### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by Nastromiud** [uBlockOrigin/uAssets#1873]
text ads:
`http://www.finanztreff.de/news/rohstoffe/`
Anzeige
Voll- oder Teilkasko gegen Kursverluste
In Deutschland herrscht ein ausgeprägtes Sicherheitsbewusstsein und viele Verbraucher sichern sich und ihr Eigentum gegen möglichst alle Eventualitäten ab. Nur der Schutz des eigenen Depots wird oft nicht bedacht, obwohl eine Absicherung der Wertpapiere schnell und einfach selbst erledigt werden kann. ...mehr
powered by finative

`http://www.finanztreff.de/news/deutschland-umsatz-im-einzelhandel-ueberraschend-gefallen/12929995`
`http://www.finanztreff.de/news/verbraucherschuetzer-keine-werbung-fuer-bitcoin-und-co/12926633`
Anzeige
ICO-Festival in München bringt Licht in den ICO-Markt

Am 11. April 2018 findet das erste ICO-Festival statt. Besucher aus Wirtschaft, Politik und Presse dürfen sich über spannende Vorträge und Workshops rund um die Themen Initial Coin Offerings (ICOs), Blockchain, Smart Contracts sowie Kryptowährungen freuen. Darüber hinaus präsentieren zahlreiche innovative Unternehmen ihre ICOs. ...mehr
powered by finative

**Comment by mapx-** [comment]
add
```
finanztreff.de###nativendo-infeed
finanztreff.de###nativendo-artikel
finanztreff.de##.contentBox_plista
```

@monzta

**Comment by mapx-** [comment]
I notified @monzta - the maintainer of easylist Germany (it's about classic filters - not uBo specific)

**Comment by monzta** [comment]
Added https://github.com/easylist/easylistgermany/commit/211ebf9 

The Plista container doesn't show ads for me though.

**Comment by mapx-** [comment]
yes, only remaining space

**Comment by monzta** [comment]
It's showing first-party content recommendations for me.

**Comment by Nastromiud** [comment]
more:
1. on every site on page start
![a](https://user-images.githubusercontent.com/38029975/38374080-54da04d6-38e2-11e8-996a-32536d910202.png)

2. also on evry site on page page
![b](https://user-images.githubusercontent.com/38029975/38374135-705feaea-38e2-11e8-8349-c7db6f245585.png)

3. homepage 
![c](https://user-images.githubusercontent.com/38029975/38374183-8de5b220-38e2-11e8-8a6b-e3ff41323d2b.png)

4. info popup that comes when move mouse about small "i" ads Börse Stuttgart...always in these popups in many page
![d](https://user-images.githubusercontent.com/38029975/38374190-928879d4-38e2-11e8-998f-7b6279a42742.png)

5. http://index.finanztreff.de/
![e](https://user-images.githubusercontent.com/38029975/38374282-c9799dce-38e2-11e8-8c80-b0f56d56bc71.png)

6.http://www.finanztreff.de/news/rohstoffe/ and http://rohstoffe.finanztreff.de/
![i](https://user-images.githubusercontent.com/38029975/38374398-09ac09c2-38e3-11e8-8576-c0201b790a2a.png)

7. http://rohstoffe.finanztreff.de/rohstoffe_einzelkurs_uebersicht.htn?i=2323869
![h](https://user-images.githubusercontent.com/38029975/38374407-10af4a36-38e3-11e8-8bd5-72bd084a10e7.png)

8. http://www.finanztreff.de/news/vorbereitung-auf-mega-ico-telegram-sammelt-bei-investoren-17-milliarden-dollar-ein/12926870 and every site where quelle: handelsblatt
![f](https://user-images.githubusercontent.com/38029975/38374462-33e9d7a0-38e3-11e8-868b-0472c407fbd9.png)

**Comment by mapx-** [comment]
report directly here
https://github.com/easylist/easylistgermany/issues
