### ISSUE TITLE
youmath.it: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18743]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There's a cookie message on the site, caused by `@@||youmath.it/$script,1p`.
Using `||youmath.it/media/cmp-v2/$xhr,1p,important` seems to fix it.

### URL(s) where the issue occurs.

`https://www.youmath.it/`

### Screenshot(s)

![Screenshot from 2023-06-29 22-24-49](https://github.com/uBlockOrigin/uAssets/assets/89158249/13552624-51de-440d-b3f4-a81ed69f5dd6)

### uBO version

v1.50.1b7

### Browser name and version

Firefox 114.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by stephenhawk8054** [comment]
The cookie is blocked by `/cmp-v2/*` in EasyList Cookie for me

**Comment by dportvine** [comment]
Unable to reproduce. 

<details>
<summary>Screen</summary>

![2023-06-30_081444](https://github.com/uBlockOrigin/uAssets/assets/111344219/d6ed0510-d53e-4eb9-b34b-f4334e1d2101)
![2023-06-30_080950](https://github.com/uBlockOrigin/uAssets/assets/111344219/e1f9ff8f-bba8-4c60-b961-048ca70b3b3e)
</details>

**Comment by Sonic5435325** [comment]
My bad, guess AdGuard is the _only_ one causing the problem, not just uBlock's filters.

**Comment by dportvine** [comment]
Yep

<details>
<summary>Screen</summary>

![2023-06-30_085755](https://github.com/uBlockOrigin/uAssets/assets/111344219/0e034fa2-0838-4773-9d78-4843b21d8a48)
![2023-06-30_085755](https://github.com/uBlockOrigin/uAssets/assets/111344219/37c92f6c-e0e5-4365-b08a-42bd47de3764)
</details>
