### ISSUE TITLE
bukalapak.com: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#18744]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bukalapak.com/`

### Category

privacy

### Description

I found several domains used for impressions and logging services. At the very least, they log user's page view impression, OS, viewport size, and timezone.

`https://t.bukalapak.com/e`
`https://collectorsvc.apac.vesta.io:8443/DataCollectorProxy/Service/InsertUserData`

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-06-30 101817](https://github.com/uBlockOrigin/uAssets/assets/115052854/2e2dae67-e7b1-4406-a217-140a5e2c8b7b)
![Screenshot 2023-06-30 101946](https://github.com/uBlockOrigin/uAssets/assets/115052854/baf77609-be01-4361-b7ab-0cae2835139f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b6
Firefox: 114
filterset (summary):
 network: 90562
 cosmetic: 39247
 scriptlet: 17735
 html: 968
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 34529-41, now
  ublock-badware: 7671-0, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2096-0, now
  ublock-quick-fixes: 247-16, 1m
  easylist: 67489-306, now
  easyprivacy: 30607-83, now
  urlhaus-1: 3240-0, 1m
  plowe-0: 3739-964, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 313 ms (selfie)
 maxAssetCacheWait: 110 ms
popupPanel:
 blocked: 11
 network:
  fpapi.io: 10
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||collectorsvc.apac.vesta.io^
||t.bukalapak.com^
||bukalapak.com/banner-redirector/impression$xhr
```

@ryanbr
