### ISSUE TITLE
soap2day.rs: popups

### ISSUE THREAD

**Issue by smeowthie** [uBlockOrigin/uAssets#18742]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://soap2day.rs/watch-tv/watch-clone-high-full-96937.9633610`

### Category

popups

### Description

clicking in specific spots in the website redirects you to scam websites by default, these are not removed

### Other extensions used

deadname blocker
shazam
custom cursor for chrome
scan translator
roblox+
youtube auto pause blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.7h.3m
Chromium: 113
filterset (summary):
 network: 92607
 cosmetic: 39186
 scriptlet: 17747
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67515-50, 3d.5h.35m
  easyprivacy: 30603-56, 5d.22h.10m
  plowe-0: 3737-954, 6d.18h.14m
  ublock-badware: 7609-138, 2d.21h.59m
  ublock-filters: 33640-140, 21h.51m
  ublock-privacy: 411-3, 5d.16h.7m
  ublock-quick-fixes: 246-14, 2h.18m
  ublock-unbreak: 2061-35, 2d.21h.58m
  urlhaus-1: 5263-0, 2h.19m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 27061 ms (selfie)
 maxAssetCacheWait: 299 ms
popupPanel:
 blocked: 2
 no-popups: true
 network:
  googletagmanager.com: 2
 extended:
  ###hgiks-middle
  ###hgiks-top
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ##+js(abort-current-script, navigator, FingerprintJS)
  ###overlay-center
```
</details>

**Comment by ghajini** [comment]
update the ublock origin filters
