### ISSUE TITLE
[nsfw] suaurl.com: detection

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#18747]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://suaurl.com/880fb9`

### Category

detection

### Description

Stupid anti-adblock hides captcha verification and button to proceed in next step.

### Other extensions used

Nothing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<![image](https://github.com/uBlockOrigin/uAssets/assets/129367686/4a7027da-fa83-41f4-80ea-52e413885e3f)>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.1h
Firefox: 114
filterset (summary):
 network: 95007
 cosmetic: 88578
 scriptlet: 20082
 html: 955
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 7m
  fanboy-cookiemonster: 47623-229, 2d.22h.31m
  spa-0: 3724-1, 10m
 default:
  user-filters: 68-7, never
  ublock-filters: 34457-188, 4d.22h.30m
  ublock-badware: 7587-1, 4d.22h.29m
  ublock-privacy: 457-0, 2d.22h.32m
  ublock-unbreak: 2086-0, 4d.22h.28m
  ublock-quick-fixes: 250-0, 10m
  easylist: 67515-634, 3d.10h.21m
  easyprivacy: 30611-668, 3d.10h.20m
  urlhaus-1: 3240-0, 1h.26m
  plowe-0: 3735-1, 9d.22h.55m
  spa-1: 5314-158, 1d.4h.33m
filterset (user): [array of 68 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 916 ms (selfie)
 maxAssetCacheWait: 286 ms
popupPanel:
 blocked: 24
 network:
  a-ads.com: 1
  cleverwebserver.com: 2
  googletagmanager.com: 2
  nobeta.com.br: 2
  optad360.io: 4
  quantcast.com: 1
  suaads.com: 2
  themoneytizer.com: 8
  zunsoach.com: 2
 extended:
  ##.showads
  ##div[id][onclick$="();"][style^="position: fixed; z-index:"]
  ##+js(set-constant, cdo, 1)
  ##+js(no-setTimeout-if, Por favor, desative)
  ##+js(no-setInterval-if, /adblock|Por favor, desative|adsbygoogl…
  ##+js(set-constant, acdl, undefined)
  ##+js(no-setTimeout-if, window.location.href)
  ##+js(abort-current-script, $, notficationAd)
  ##+js(abort-current-script, open, document.getElementById)
```
</details>

**Comment by BRR34L0RD** [comment]
Didn't work. New anti-adblock stupid countermeasure?

**Comment by mapx-** [comment]
- still working, getting `mega.nz` link
- update all filter lists, use default lists, no other blocking addons

**Comment by stephenhawk8054** [comment]
Working for me too

**Comment by BRR34L0RD** [comment]
Too strange. I don't use any other adblock than Ublock Origin.

**Comment by stephenhawk8054** [comment]
Can you click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by BRR34L0RD** [comment]
Yes: 

`uBlock Origin 1.50.0:
 since: 2m
Firefox: 114
filterset (summary):
 network: 94087
 cosmetic: 42756
 scriptlet: 18074
 html: 972
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34562-83, 1m
  ublock-badware: 7672-1, 1m
  ublock-privacy: 459-0, 1m
  ublock-unbreak: 2094-3, 1m
  ublock-quick-fixes: 252-0, 1m
  easylist: 67634-781, 1m
  easyprivacy: 30610-632, 1m
  urlhaus-1: 5224-0, 1m
  plowe-0: 3738-1, 1m
  spa-1: 5314-10, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3336 ms
 maxAssetCacheWait: 17 ms
popupPanel:
 blocked: 1
 network:
  github.com: 1`

**Comment by BRR34L0RD** [comment]
That is from "suaurl" itself: 

`uBlock Origin 1.50.0:
 since: 5m
Firefox: 114
filterset (summary):
 network: 94087
 cosmetic: 42756
 scriptlet: 18074
 html: 972
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34562-83, 4m
  ublock-badware: 7672-1, 4m
  ublock-privacy: 459-0, 4m
  ublock-unbreak: 2094-3, 4m
  ublock-quick-fixes: 252-0, 4m
  easylist: 67634-781, 4m
  easyprivacy: 30610-632, 4m
  urlhaus-1: 5224-0, 4m
  plowe-0: 3738-1, 4m
  spa-1: 5314-10, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3336 ms
 maxAssetCacheWait: 17 ms
popupPanel:
 blocked: 23
 network:
  a-ads.com: 1
  cleverwebserver.com: 2
  googletagmanager.com: 2
  nobeta.com.br: 2
  optad360.io: 4
  suaads.com: 2
  themoneytizer.com: 8
  zunsoach.com: 2
 extended:
  ##.showads
  ##+js(set-constant, cdo, 1)
  ##+js(no-setTimeout-if, Por favor, desative)
  ##+js(no-setInterval-if, /adblock|Por favor, desative|adsbygoogl…
  ##+js(set-constant, acdl, undefined)
  ##+js(no-setTimeout-if, window.location.href)
  ##+js(abort-current-script, $, notficationAd)
  ##+js(abort-current-script, open, document.getElementById)
  ##+js(remove-node-text, script, /window\.open|window\.location\.…
  ##+js(abort-on-property-read, document.oncontextmenu)
  ##+js(abort-on-property-read, shortcut)`

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
suaurl.com##^script:has-text(/window\.open|window\.location\.href|\$\(document\)\.ready.*show/)
```

**Comment by BRR34L0RD** [comment]
Tested. Didn't work. Anyways I gave up about the link. I will never disable my adblock, the one who rules my browser is myself, not site owners. 

Thanks for your support.
