### ISSUE TITLE
tokopedia.com: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#18746]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tokopedia.com/`

### Category

privacy

### Description

I found some kind of tracking pixel on the site (at least I think so, I mean why would a website request a 1x1 image?), screenshot below.

`https://accounts.tokopedia.com/upkie`

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-06-30 121518](https://github.com/uBlockOrigin/uAssets/assets/115052854/e6e728b5-39d5-4b52-a20d-7864821c77eb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b6
Firefox: 114
filterset (summary):
 network: 90563
 cosmetic: 39251
 scriptlet: 17738
 html: 968
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 34531-41, now
  ublock-badware: 7671-0, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2096-0, now
  ublock-quick-fixes: 250-21, now
  easylist: 67491-306, now
  easyprivacy: 30612-83, now
  urlhaus-1: 3240-0, now
  plowe-0: 3739-964, now
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 446 ms
 maxAssetCacheWait: 271 ms
popupPanel:
 blocked: 9
 network:
  tokopedia.com: 1
  app.link: 3
  googletagmanager.com: 1
  newrelic.com: 4
```
</details>

**Comment by stephenhawk8054** [comment]
> why would a website request a 1x1 image?

In some cases it can be used to check if there's internet connection or not.

**Comment by mapx-** [comment]
@partingscientist investigate on your side, block that request, log in / log off, test the pages, it could trigger breakages.

Finally, If you are sure just report at easyprivacy repository
