### ISSUE TITLE
sltrib.com anti-adblock

### ISSUE THREAD

**Issue by austynmahoney** [uBlockOrigin/uAssets#1874]
### URL(s) where the issue occurs

`https://www.sltrib.com/`

### Describe the issue

Anti-adblock

### Screenshot(s)

![Screenshot](https://user-images.githubusercontent.com/1133292/38239454-a095b094-36e1-11e8-8fd2-c032519e6e4e.PNG)

### Versions

- Browser/version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- uBlock Origin version:  v1.15.18

### Settings

- Default

### Notes

A quick search with the overlay ID (`##.tp-modal`) brings up #157, the same technology may be used here.

The following filter removes the anti-adblocker `||tinypass.com`

**Comment by okiehsch** [comment]
Blocking tinypass will break the ability to sign in or subscribe.
