### ISSUE TITLE
pinterest.ca: breakage

### ISSUE THREAD

**Issue by Badgerconda** [uBlockOrigin/uAssets#18748]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.ca/`

### Category

breakage

### Description

with ublock enabled, the page header (search bar and all buttons) disappears. disabling ublock on that page rectifies the issue completely.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 16d.16h.16m
Firefox: 114
filterset (summary):
 network: 90513
 cosmetic: 39172
 scriptlet: 17648
 html: 966
listset (total-discarded, last-updated):
 default:
  user-filters: 13-1, never
  ublock-filters: 34527-41, now
  ublock-badware: 7671-1, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2096-0, now
  easylist: 67491-735, now
  easyprivacy: 30612-614, now
  urlhaus-1: 3240-0, now
  plowe-0: 3739-1, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 174 ms (selfie)
 maxAssetCacheWait: 67 ms
popupPanel:
 blocked: 5
 network:
  pinterest.ca: 2
  cedexis.com: 1
  pinterest.com: 2
 extended:
  ##a[href*="&epik="]
  ##a[href*="&epik="]:upward([data-grid-item])
  ##+js(replace-node-text, script, /web_hide_epik_param_in_promote…
```
</details>

**Comment by mapx-** [comment]
FF / chrome, no issue on my end.

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Maxbroforce** [comment]
This issue also JUST occurred for me on pinterest.ca in the past few hours. It was happening in Firefox. After updating all filters, ensuring it wasn't any other extensions, excluding custom filters, disabling Firefox built in blockers, and clearing my browser cache there was no change. 

Manually went through all filters and the issue _only_ occurs when the 'uBlock filters – Ads' list is enabled. I noticed when comparing it to Chrome before updating my Chrome's uBO there's these two new pinterest filter lines
pinterest.*##+js(rpnt, script, /web_hide_epik_param_in_promoted_urls.*?enabled"/, web_hide_epik_param_in_promoted_urls":"disabled")
pinterest.*##a[href*="&epik="]:upward([data-grid-item])

So maybe one of them isn't playing nicely with Firefox for some reason? I'm not technically savvy enough to figure out how to test if it is one of those specific new lines or why it's seemingly FF specific. I do briefly see the search bar and top buttons when refreshing pinterest (with the 'uBlock filters - Ads' list turned on) but then it blanks out, which makes me feel like it's getting caught by a filter? 

For now I just turned off the Ads list and used element picker to filter out the remaining visible ad clutter, which seems to be doing the job but I'd prefer to have the full filter on.

**Comment by mapx-** [comment]
Enable back the uBO list

add and test
`pinterest.*#@#a[href*="&epik="]:upward([data-grid-item])`

**Comment by peace2000** [comment]
My wife complained to me about this issue today, I didn't have time to investigate it at that moment and just told her to update all the filter lists - which fixed the issue. She was logged in.

I don't have a Pinterest account, but I noticed that I can login there with a Google account. The header is different for logged in users compared to non-logged in users.

@mapx- Did you login to the page earlier?

**Comment by mapx-** [comment]
yes, I'm using an account.

**Comment by Maxbroforce** [comment]
Thanks for such a quick reply mapx! 
Fortunately the issue seems to have resolved for me now! 
I saw there were some updates to the filters when I went to refresh uBO/enable the uBO ad filter after coming back to check this after work. 
Many thanks to everyone working hard to keep the filters working and the ads thoroughly blocked
