### ISSUE TITLE
[nsfw] kissasian.mx: popups

### ISSUE THREAD

**Issue by LookingAtChu** [uBlockOrigin/uAssets#18754]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kissasian.mx/`

### Category

popups

### Description

when playing a video a nsfw tab opens

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 22d.14h.37m
Chromium: 114
filterset (summary):
 network: 91320
 cosmetic: 39258
 scriptlet: 17777
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67618-50, now
  easyprivacy: 30604-56, now
  plowe-0: 3738-963, now
  ublock-badware: 7669-139, now
  ublock-filters: 33678-144, now
  ublock-privacy: 418-3, now
  ublock-quick-fixes: 246-15, 1h.37m
  ublock-unbreak: 2065-38, now
  urlhaus-1: 3882-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 561 ms (selfie)
 maxAssetCacheWait: 148 ms
popupPanel:
 blocked: 5
 network:
  bidgear.com: 4
  googletagmanager.com: 1
 extended:
  ##+js(addEventListener-defuser, /^(?:click|mousedown)$/, _0x)
  ##+js(abort-on-property-read, mm)
  ##+js(no-setTimeout-if, (), 45000)
  ##+js(set-constant, check_adblock, true)
```
</details>

**Comment by mapx-** [comment]
provide example page / video + the server you are using to play the movie

**Comment by mapx-** [comment]
update all your filter lists
