### ISSUE TITLE
moviesjoy.to: popups

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#18758]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://moviesjoy.to/watch-tv/maid-72697.4821667`

### Category

popups

### Description

Clicking random spaces on pages cause phishing sites to open in new tabs

### Other extensions used

WebRTC Leak Shield
Firefox Color

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 16d.19h.19m
Firefox: 114
filterset (summary):
 network: 91331
 cosmetic: 39263
 scriptlet: 17747
 html: 971
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 34557-167, now
  ublock-badware: 7672-1, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2094-3, now
  ublock-quick-fixes: 250-0, now
  easylist: 67625-586, now
  easyprivacy: 30609-660, now
  urlhaus-1: 3882-0, now
  plowe-0: 3738-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 23 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 184 ms (selfie)
 maxAssetCacheWait: 77 ms
popupPanel:
 blocked: 12
 network:
  addthis.com: 1
  aqwmbwybzwvbj.top: 1
  briareddollier.com: 1
  cloudflareinsights.com: 2
  googletagmanager.com: 2
  gulsachpyrexia.uno: 1
  sharethis.com: 2
  valueclick.cc: 2
 extended:
  ###hgiks-middle
  ###hgiks-top
  ##.premodal.modal
  ##.show.modal-backdrop
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(abort-current-script, document.createElement, /l\.parentNo…
  ##+js(abort-on-property-read, mm)
  ###overlay-center
```
</details>

**Comment by mapx-** [comment]
Force update all filter lists.
