### ISSUE TITLE
pythonthree.com: ads

### ISSUE THREAD

**Issue by Linisdjxm** [uBlockOrigin/uAssets#18751]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pythonthree.com/redirect-link/`

### Category

ads

### Description

Some ads are left.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 12d.2h.34m
Firefox: 116
filterset (summary):
 network: 291845
 cosmetic: 184902
 scriptlet: 39169
 html: 1145
listset (total-discarded, last-updated):
 added:
  adguard-generic: 72062-6261, 6m
  adguard-spyware-url: 1104-6, 3m
  adguard-spyware: 61790-13724, 3m
  curben-phishing: 111667-38, 2m
  curben-pup: 189-0, 2m
  adguard-social: 20761-824, 2m
  adguard-cookies: 26146-58, now
  adguard-popup-overlays: 22805-1502, now
  adguard-other-annoyances: 13022-291, now
  adguard-widgets: 2188-1, now
  fanboy-thirdparty_social: 68-0, 2m
  easylist-annoyances: 3872-106, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 34543-388, 6m
  ublock-badware: 7671-0, 6m
  ublock-privacy: 459-0, 6m
  ublock-unbreak: 2093-0, 6m
  ublock-quick-fixes: 250-3, 6m
  easylist: 67537-871, 3m
  easyprivacy: 30613-713, 2m
  urlhaus-1: 3240-0, 2m
  plowe-0: 3737-2, now
  CHN-0: 26348-158, now
filterset (user): [array of 3 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 26352 ms
 maxAssetCacheWait: 20 ms
popupPanel:
 blocked: 7
 network:
  pythonthree.com: 3
  google-analytics.com: 1
  googlesyndication.com: 3
 extended:
  ##ins.adsbygoogle
  ###ast-scroll-top
```
</details>

**Comment by mapx-** [comment]
report here:
https://github.com/cjx82630/cjxlist/issues

@cjx82630
