### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by jagoff412** [uBlockOrigin/uAssets#18755]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reddit.com/r/DronedOrc/comments/142rrd3/cope_cage_idiots_hit_by_fpv_drone/`

### Category

breakage

### Description

Mobile ublock Firefox won't allow scrolling shows no overlay visible 

### Other extensions used

None, disabled for test 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.16h.15m
Firefox Mobile: 106
filterset (summary):
 network: 290616
 cosmetic: 225192
 scriptlet: 41141
 html: 1147
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68549-68547, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91825-91825, now
  adguard-generic: 72066-6306, 1m
  adguard-spyware-url: 1104-5, 1m
  block-lan: 47-0, 1m
  curben-phishing: 111771-39, 1m
  curben-pup: 189-0, 1m
  adguard-social: 20761-823, 1m
  fanboy-thirdparty_social: 68-0, 1m
  fanboy-cookiemonster: 47685-3829, 1m
  fanboy-social: 16078-23, 1m
  ublock-annoyances: 5322-16, 1m
  [10 lists not shown]: [too many]
 default:
  user-filters: 188-1, never
  ublock-filters: 34822-504, 1m
  ublock-badware: 7665-1, 1m
  ublock-privacy: 459-0, 1m
  ublock-unbreak: 2099-4, 1m
  ublock-quick-fixes: 250-0, 1m
  adguard-mobile: 8320-136, 1m
  easylist: 67625-1051, 1m
  easyprivacy: 30609-788, 1m
  urlhaus-1: 3882-0, 1m
  plowe-0: 3738-1, now
filterset (user): [array of 188 redacted]
trustedset:
 added: [array of 27 redacted]
 removed:
  about-scheme
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5106 ms (selfie)
 maxAssetCacheWait: 2747 ms
popupPanel:
 blocked: 4
 network:
  reddit.com: 2
  google.com: 1
  sentry.io: 1
 extended:
  ##.AdHeader
  ##.AdUnit
  ##.adsense-ads
  ##.HeaderAd
  ##.VerticalAd
  ##._has-ads
  ##.ad--content
  ##.ad-adsense
  ##.googads
  ##.ad-banner-content
  ##.hasads
  ##.native-ad
  ##.ad-medium
  ##.post-ad
  ##.promoad
  ##.rectad
  ##.sidebar-ad:not(.adsbygoogle)
  ##.small-ad
  ##.sponsorAd
  ##.sponsorPost
  ##[slot="use-app"]
  ##xpromo-top-button
  ##shreddit-experience-tree
  ##xpromo-nsfw-blocking-modal
  ##.promotedlink
  ##body,html.scroll-is-blocked:style(overflow: auto !important;)
  ##body:style(pointer-events:auto !important;)
  ##body[style$="overflow: hidden;"]:style(overflow: auto !importa…
  ##shreddit-app > div.sidebar-grid.pdp:style(filter: unset !impor…
  ##body:style(pointer-events: auto !important; overflow: auto !im…
  ###acceptabletest:style(display: block !important;)
  ###adblocktest:style(display: block !important;)
  ##[style^="filter:"]:style(filter: none !important;)
  ##+js(no-fetch-if, url:/^https:\/\/www\.reddit\.com$/ method:pos…
  ##+js(no-xhr-if, method:POST url:/^https:\/\/www\.reddit\.com$/)
  ##+js(replace-node-text, script, "outboundUrl", "outbound")
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(addEventListener-defuser, block-body-scrolling)
  ##+js(remove-class, m-blurred, .m-blurred)
  ##+js(remove-class, scroll-disabled, body)
  ##+js(set-constant, Notification.requestPermission, noopFunc)
  ##+js(set-constant, navigator.sendBeacon, noopFunc)
```
</details>

**Comment by jagoff412** [comment]
![Screenshot_20230630_133348_Firefox](https://github.com/uBlockOrigin/uAssets/assets/48819253/75b98e46-da65-4f10-8856-8956e53d23d3)

Seems to be the forced app popup. Impossible to click through on mobile with ublock disabled

**Comment by mapx-** [comment]
adding

```
reddit.com##xpromo-nsfw-blocking-modal
reddit.com##*:style(filter: none !important)
```

you can partially see the page (not all the comments, page unclickable)

**Comment by jagoff412** [comment]
Thank you I assume there is no way to fix this
I refuse to have a reddit account but information there remains unfortunately valuable and often not posted elsewhere

**Comment by mapx-** [comment]
yeah, no issue with an account.
