### ISSUE TITLE
instagram.com: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18766]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

To reproduce: log on to an Instagram account and have some people followed.
When you try to right click some images, it won't let you save or open the image in a new tab, though adding `instagram.com##._aagw` will allow you to. It doesn't seem to have any functionality besides trying to prevent downloading/saving of Instagram images on your feed.

### URL(s) where the issue occurs.

`https://www.instagram.com`

### uBO version

v1.50.1b10

### Browser name and version

Firefox 114.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by mapx-** [comment]
maybe

`instagram.com##[role] > [class]:matches-css(bottom: /0/):matches-css(left: /0/):matches-css(position: /absolute/):matches-css(right: /0/):matches-css(top: /0/)`

**Comment by Sonic5435325** [comment]
That filter doesn't seem to work.

**Comment by mapx-** [comment]
```
instagram.com##[role] > [class]:matches-css(bottom: /0/):matches-css(left: /0/):matches-css(position: /absolute/):matches-css(right: /0/):matches-css(top: /0/)
instagram.com##[role] > div > [class]> [class]:matches-css(bottom: /0/):matches-css(left: /0/):matches-css(position: /absolute/):matches-css(right: /0/):matches-css(top: /0/)
```

**Comment by mapx-** [comment]
However, it's a form of protection of the photos on instagram, better not circumvent it.

**Comment by krystian3w** [comment]
So we should revert unlocked copy any text on Insta.

**Comment by llebout** [comment]
@mapx- Hi, I also want to block this popup because I do not want to create a Facebook or Instagram account for obvious reasons but sometimes other people post information only on instagram and I am expected to access it. This is not about stealing/downloading images just browsing without an account, is there a chance you can revisit your decision? Thanks

**Comment by stephenhawk8054** [comment]
You can add as custom filters.
