### ISSUE TITLE
in.tradingview.com: nuisance

### ISSUE THREAD

**Issue by kanekikun1717** [uBlockOrigin/uAssets#18765]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://in.tradingview.com/chart/xjWroocF/`

### Category

nuisance

### Description

my other functions on this site are gone. when ever i use other browsers they are okay and no problem in those.
https://github.com/uBlockOrigin/uAssets/assets/138274068/30d021a5-887b-4710-ba28-f022ad75c859

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2023-06-30 210827](https://github.com/uBlockOrigin/uAssets/assets/138274068/2223976a-0717-483d-9e80-0788c4069b09)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.12h.26m
Firefox: 114
filterset (summary):
 network: 92512
 cosmetic: 39256
 scriptlet: 17737
 html: 969
listset (total-discarded, last-updated):
 default:
  user-filters: 14-2, never
  ublock-filters: 34542-59, 14h.36m
  ublock-badware: 7671-0, 16h.37m
  ublock-privacy: 457-0, 2d.16h.4m
  ublock-unbreak: 2088-0, 4d.57m
  ublock-quick-fixes: 250-0, 12h.41m
  easylist: 67451-735, 1d.1h.42m
  easyprivacy: 30608-611, 5d.13h.48m
  urlhaus-1: 5224-0, 1h.13m
  plowe-0: 3735-2, 11d.1h.24m
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 366 ms (selfie)
 maxAssetCacheWait: 145 ms
popupPanel:
 blocked: 5
 no-cosmetic-filtering: true
 no-large-media: true
 network:
  tradingview.com: 4
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
You have to clearly explain - step by step - what is is about, how to reproduce, what exactly is broken, what to click, if an account is required etc etc

**Comment by kanekikun1717** [comment]
> You have to clearly explain - step by step - what is this about, how to reproduce, what exactly is broken, what to click, if an account is required etc etc 

heres's a screenshot of before and after glitch or bug
![2023-06-06 (1)](https://github.com/uBlockOrigin/uAssets/assets/138274068/e1c867f4-6631-4d97-a780-665089393cf1)


![Screenshot 2023-06-30 210827](https://github.com/uBlockOrigin/uAssets/assets/138274068/088ce9eb-c695-4eb5-851c-a591ab3fa6c7)

now i leave the things rest on you to think whats the matter and no matter how many time i sign out or reload refresh it just doesn't work only on firefox.on other browsers it works fine

**Comment by stephenhawk8054** [comment]
```yaml
default:
  user-filters: 14-2, never
```

Can copy your custom filters to here?

**Comment by mapx-** [comment]
@kanekikun1717 

follow these indications for firefox

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
