### ISSUE TITLE
xda-developers.com: ad leftovers

### ISSUE THREAD

**Issue by schipht** [uBlockOrigin/uAssets#18767]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.xda-developers.com/meta-facebook-app-store-eu/`

### Category

ads

### Description

ad leftovers

solution is block this filter: www.xda-developers.com##.ad-current

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/62606788/b2f6669c-1468-416b-992b-28a521a74b51)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 15d.17h.6m
Firefox: 114
filterset (summary):
 network: 456230
 cosmetic: 166497
 scriptlet: 41895
 html: 1136
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://www.usom.gov.tr/url-list.txt: 224388-145, 4d.11h.39m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68424-6361, 3d.14h.40m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91673-47963, 6d.16h.21m
  adguard-generic: 72009-5499, 3d.14h.43m
  adguard-mobile: 8300-37, 3d.14h.42m
  adguard-spyware-url: 1097-5, 3d.14h.41m
  curben-phishing: 111771-38, 12h.14m
  curben-pup: 199-0, 12h.13m
  fanboy-cookiemonster: 47661-47588, 18h.15m
  ublock-annoyances: 5260-10, 18h.16m
  TUR-0: 13574-204, 3d.14h.44m
 default:
  user-filters: 8-0, never
  ublock-filters: 34502-284, 4d.15h.39m
  ublock-badware: 7587-0, 4d.15h.39m
  ublock-privacy: 452-1, 6d.22h.18m
  ublock-unbreak: 2087-2, 4d.15h.39m
  easylist: 67554-17102, 3d.16h.45m
  easyprivacy: 30616-40, 1d.18h.21m
  urlhaus-1: 3882-0, 12h.12m
  ublock-quick-fixes: 250-0, 12h.11m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 39 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 341 ms (selfie)
 maxAssetCacheWait: 210 ms
popupPanel:
 blocked: 30
 network:
  xda-developers.com: 7
  ad.gt: 1
  adlightning.com: 2
  adsninja.ca: 4
  amazon-adsystem.com: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  googletagservices.com: 1
  imasdk.googleapis.com: 2
  parsely.com: 2
  primis.tech: 1
  privacymanager.io: 3
  unpkg.com: 1
 extended:
  ##.btn-mail
  ##.copy-link-button
  ##.article-footer-newsletter
  ##.ad-current
  ##+js(remove-class, twig-body)
  ##+js(abort-current-script, document.createElement, admiral)
```
</details>

**Comment by mapx-** [comment]
> ignoreGenericCosmeticFilters: true

unselect the option
