### ISSUE TITLE
walmart.ca: ads

### ISSUE THREAD

**Issue by Dantasstic** [uBlockOrigin/uAssets#18761]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.walmart.ca/cp/grocery`

### Category

ads

### Description

Ad in upper right corner, comes back even with using the picker.

### Other extensions used

none

### Screenshot(s)

![2023-06-30 - 1844-26](https://github.com/uBlockOrigin/uAssets/assets/48727187/ce2e059f-0dc7-4a02-aa8f-e38e6abe3e4f)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.16h.55m
Firefox: 114
filterset (summary):
 network: 283151
 cosmetic: 207135
 scriptlet: 41257
 html: 1146
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68549-5029, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2230-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91825-70967, now
  https://www.fanboy.co.nz/enhancedstats.txt: 2988-10, now
  ublock-annoyances: 5263-11, now
  adguard-generic: 72068-4644, now
  adguard-mobile: 8321-97, now
  fanboy-cookiemonster: 47685-3818, now
  adguard-spyware-url: 1104-147, now
  block-lan: 47-0, now
  curben-phishing: 111771-38, now
  curben-pup: 189-0, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 96-0, never
  ublock-filters: 34558-475, now
  ublock-badware: 7672-0, now
  ublock-privacy: 459-2, now
  ublock-unbreak: 2094-1, now
  easylist: 67634-1652, now
  easyprivacy: 30610-733, now
  plowe-0: 3738-3, now
  urlhaus-1: 3882-0, now
  ublock-quick-fixes: 250-3, 18m
filterset (user): [array of 96 redacted]
trustedset:
 added: [array of 74 redacted]
 removed:
  edge-scheme
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 502 ms (selfie)
 maxAssetCacheWait: 325 ms
popupPanel:
 blocked: 26
 network:
  walmart.ca: 4
  adobedc.net: 1
  adobedtm.com: 8
  agkn.com: 1
  contentsquare.net: 1
  criteo.net: 2
  demdex.net: 1
  foresee.com: 1
  google-analytics.com: 1
  google.ca: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 2
  scorecardresearch.com: 1
 extended:
  ##div[data-automation="privacy-banner-wrapper"]
```
</details>

**Comment by gorhill** [comment]
Works?

    walmart.ca##[data-automation="flipkartDisplayAds"]

**Comment by Dantasstic** [comment]
> Works?
> 
> ```
> walmart.ca##[data-automation="flipkartDisplayAds"]
> ```
> 
> Note that when I click the image, this causes navigation within the site, so this might qualify as self-promo.

Yes, adding that to my custom filters removes it, thank you!
