### ISSUE TITLE
ko.aliexpress.com: ads

### ISSUE THREAD

**Issue by comiluv** [uBlockOrigin/uAssets#18768]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A blocking ad in the middle of the screen which requires the user to press "X" button in the top right to go away

### URL(s) where the issue occurs.

`https://ko.aliexpress.com/`

### Screenshot(s)

<img width="1892" alt="스크린샷 2023-07-01 205022" src="https://github.com/uBlockOrigin/uAssets/assets/19642705/66cda9af-ec2c-4412-94b4-84ab77200f4c">

### Notes

Adding a user filter `ko.aliexpress.com##.image-poplayer-modal` seems to help

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 3d.9h.12m
Chromium: 114
filterset (summary):
 network: 93720
 cosmetic: 42349
 scriptlet: 17884
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  KOR-1: 4438-11, now
  easylist: 67506-92, now
  easyprivacy: 30717-69, now
  plowe-0: 3738-1080, now
  ublock-badware: 7675-138, now
  ublock-filters: 33674-148, now
  ublock-privacy: 418-5, now
  ublock-quick-fixes: 251-20, now
  ublock-unbreak: 2069-39, now
  urlhaus-1: 5224-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 100 ms (selfie)
 maxAssetCacheWait: 62 ms
```
</details>

**Comment by mapx-** [comment]
enable one of the annoyances lists

`AdGuard – Annoyances`
`EasyList – Annoyances`

see if helps

if does not help report here:
https://github.com/List-KR/List-KR/issues

**Comment by piquark6046** [comment]
It is not an advertisement. It fits annoyances category.
