### ISSUE TITLE
praxistipps.chip.de: breakage

### ISSUE THREAD

**Issue by NBA2K1** [uBlockOrigin/uAssets#18763]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://praxistipps.chip.de/was-ist-ein-podcast-einfach-und-verstaendlich-erklaert_41343`

### Category

breakage

### Description

shows only the header and footer of the website

### Other extensions used

Bitwarden; Dark Reader; Enhancer for YouTube; FastForward; Firefox Translations; Simple Tab Groups; Simple Translate; SponsorBlock for YouTube; User-Agent Switcher and Manager
Disabling Dark Reader and User-Agent Switcher doesn't change anything.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-07-01 045136](https://github.com/uBlockOrigin/uAssets/assets/78034913/87c6bf98-f7df-499a-96c4-496c8d235384)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.7h.33m
Firefox: 102
filterset (summary):
 network: 104534
 cosmetic: 169377
 scriptlet: 26108
 html: 1148
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68549-744, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91828-65197, now
  fanboy-thirdparty_social: 69-0, now
  fanboy-cookiemonster: 47688-3814, now
  ublock-annoyances: 5264-7, now
 default:
  user-filters: 15-0, never
  ublock-filters: 34562-74, now
  ublock-badware: 7672-1, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2095-3, now
  ublock-quick-fixes: 252-0, now
  easylist: 67649-809, now
  easyprivacy: 30611-627, now
  urlhaus-1: 5224-0, now
  plowe-0: 3738-1, now
  DEU-0: 6932-3, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 54 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 568 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 954 ms (selfie)
 maxAssetCacheWait: 72 ms
popupPanel:
 blocked: 42
 network:
  chip.de: 3
  2mdn.net: 1
  adnxs.com: 4
  bf-ad.net: 2
  conunity.io: 2
  dl8.me: 22
  googlesyndication.com: 4
  green-ads.net: 1
  iocnt.net: 1
  outbrain.com: 2
 extended:
  ##.Article__Promo
  ###R1C1
  ###R1C2
  ###R1C3
  ##.Ad
  ##.FC.mt-md-so[role="complementary"]
  ##.app_nexus_banners_common
  ##a[target][href^="https://x.chip.de/"]:upward(div[id])
  ##:root:style(--topbanner-height-min:unset!important;--topbanner…
  ##+js(json-prune, enabled, force_disabled)
  ##+js(set-constant, TfmediaExtFolEngineLoaded, true)
```
</details>

**Comment by JobcenterTycoon** [comment]
Replaced the filter with a safer one https://github.com/uBlockOrigin/uAssets/commit/e0ca6a98e5e1104437fdca169df9ab5086f44588
