### ISSUE TITLE
isekaipalace.com: detection

### ISSUE THREAD

**Issue by T-Baniza** [uBlockOrigin/uAssets#18760]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

AdBlock detected.

### URL(s) where the issue occurs.

`https://www.isekaipalace.com/2023/05/oda-mengatakan-bahwa-live-action.html?m=1#?o=f0ae6c09d7e2a46898200f2a362a46630ced3773ad85047bc94d78d0a9cea683af57e7eb21ebd529eaf6103d93a01666c57fc82bd3ca87304c35fb2337bf5ac77752fe9828e0c618791f3e62d448bb5c136f7bd2467c9bd45244b70c229e901727c02fc62b9053e5`

### Screenshot(s)

![IMG_20230701_061752](https://github.com/uBlockOrigin/uAssets/assets/79722529/9d98e9bc-41e6-4075-90e8-b7f83b6dadfd)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4m
Firefox Mobile: 114
filterset (summary):
 network: 92713
 cosmetic: 29350
 scriptlet: 17794
 html: 972
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34828-311, 3m
  ublock-badware: 7666-1, 3m
  ublock-privacy: 459-1, 3m
  ublock-unbreak: 2099-4, 3m
  ublock-quick-fixes: 250-0, 2m
  adguard-mobile: 8321-121, 4m
  easylist: 67634-17436, 1m
  easyprivacy: 30610-626, 1m
  urlhaus-1: 3882-0, 1m
  plowe-0: 3738-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2453 ms
 maxAssetCacheWait: 11 ms
```
</details>

**Comment by techmetx11** [comment]
This filter should work:
`isekaipalace.com##+js(set, window.showAds, true)`

**Comment by T-Baniza** [comment]
thank you.

**Comment by luminiatus2** [comment]
wow
