### ISSUE TITLE
virpe.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1876]
URL(s) where the issue occurs

`https://virpe.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by mapx-** [comment]
You should report here:
https://github.com/MajkiIT/polish-ads-filter/issues

**Comment by mapx-** [comment]
@MajkiIT

**Comment by MajkiIT** [comment]
@mapx- Thanks
