### ISSUE TITLE
dnaindia.com: ads

### ISSUE THREAD

**Issue by Malgotra** [uBlockOrigin/uAssets#18770]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dnaindia.com/`

`https://www.dnaindia.com/india/report-tomato-prices-to-stabilise-in-next-15-days-says-centre-3049945`

### Category

ads

### Description

A lot of ads leftovers in website and sub pages.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230701-203913](https://github.com/uBlockOrigin/uAssets/assets/122884037/1948846b-3e40-49fe-b6d6-c6b5f7e255b8)

![Screenshot_20230701-203918](https://github.com/uBlockOrigin/uAssets/assets/122884037/3b1ce02a-4447-434c-9153-e22823754afe)

![Screenshot_20230701-203923](https://github.com/uBlockOrigin/uAssets/assets/122884037/c1f3a0f6-f3ea-436b-bf46-2ef2d4c51e94)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.17m
Firefox Mobile: 114
filterset (summary):
 network: 98905
 cosmetic: 117405
 scriptlet: 23916
 html: 1155
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 959-0, now
  easylist-annoyances: 3879-90, now
  easylist-chat: 126-0, now
  fanboy-cookiemonster: 47695-281, now
  easylist-newsletters: 6223-13, now
  easylist-notifications: 2637-4, now
  fanboy-social: 16078-6, now
  ublock-annoyances: 5324-39, now
 default:
  user-filters: 3-0, never
  ublock-filters: 34825-122, 1m
  ublock-badware: 7671-1, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2109-3, now
  ublock-quick-fixes: 252-0, now
  adguard-mobile: 8321-108, now
  easylist: 67526-797, now
  easyprivacy: 30702-823, now
  urlhaus-1: 5301-0, now
  plowe-0: 3738-1, now
filterset (user): [array of 3 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2181 ms (selfie)
 maxAssetCacheWait: 722 ms
popupPanel:
 blocked: 9
 network:
  amazon-adsystem.com: 1
  crwdcntrl.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  googletagservices.com: 1
  pubmatic.com: 1
  scorecardresearch.com: 1
  skimresources.com: 1
 extended:
  ##.ad_container
  ##[id^="google_ads_iframe"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ###adscontainer
  ##.adunitContainer
  ##.taboola
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by Malgotra** [comment]
https://www.dnaindia.com/india/report-tomato-prices-to-stabilise-in-next-15-days-says-centre-3049945

**Comment by Malgotra** [comment]
Ads leftovers in sub pages too.

**Comment by mapx-** [comment]
add

`dnaindia.com##[class^="ads-"]`

@ryanbr
