### ISSUE TITLE
fedex.com: breakage

### ISSUE THREAD

**Issue by username-dot-com** [uBlockOrigin/uAssets#18775]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fedex.com/profile/`

### Category

breakage

### Description

The toggle buttons for enabling 2fa don't work. Whenever I click on one of the toggles, I get a cors blocked message going to a url with host "dpm.demdex.net". I'm not sure if it's related since its cors related, but ubo says that host is being filtered by it.
In addition to the toggles not working, the form below it where you can choose your default verification method only shows up if I disable ubo.

### Other extensions used

I run several extensions but I disabled all but my password manager and ubo and the problem persisted.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With ubo
![With ubo](https://github.com/uBlockOrigin/uAssets/assets/3682122/263233ab-bbf6-406a-ac3b-4f64e5654c36)

Without ubo
![Without ubo](https://github.com/uBlockOrigin/uAssets/assets/3682122/c32ff3f3-41e8-4414-a0cb-5269a8021097)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4m
Firefox: 111
filterset (summary):
 network: 105290
 cosmetic: 63336
 scriptlet: 17970
 html: 979
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, now
  dpollock-0: 11525-469, now
  ublock-quick-fixes: 252-3, now
  adguard-cookies: 26152-36, now
 default:
  user-filters: 0-0, never
  ublock-filters: 34559-173, now
  ublock-badware: 7680-0, now
  ublock-privacy: 459-75, now
  ublock-unbreak: 2104-0, now
  easylist: 67532-753, now
  easyprivacy: 30702-836, now
  plowe-0: 3738-2, now
  urlhaus-1: 5301-0, now
filterset (user): [empty]
trustedset:
 added: [array of 27 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 364 ms (selfie)
 maxAssetCacheWait: 78 ms
popupPanel:
 blocked: 14
 network:
  demdex.net: 3
  eum-appdynamics.com: 3
  googletagmanager.com: 1
  nuance.com: 1
  optimizely.com: 1
  qualtrics.com: 1
  techlab-cdn.com: 4
```
</details>

**Comment by krystian3w** [comment]
Backup uBo settings, reset to stock and force update all filters (twice)?

https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings/ec06839b404eee929bac06d7abcef9cae2b1dfb7#backuprestore-section

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches + https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now (both twice)

**Comment by mapx-** [comment]
@username-dot-com 

add & test
`@@||cdn.optimizely.com/datafiles/*.json$xhr,domain=fedex.com`

@ryanbr

**Comment by krystian3w** [comment]
Wy my comment about bug with:

```adb
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 252-3, now
```

Was deleted?

**Comment by mapx-** [comment]
open a discussion about it
