### ISSUE TITLE
adv.kompas.id: breakage

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#18779]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://adv.kompas.id/`

### Category

breakage

### Description

Site's assets and styles does not load.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b6
Firefox: 114
filterset (summary):
 network: 93356
 cosmetic: 39277
 scriptlet: 17753
 html: 978
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 34562-41, now
  ublock-badware: 7680-0, now
  ublock-privacy: 459-0, now
  ublock-unbreak: 2091-0, now
  ublock-quick-fixes: 250-19, now
  easylist: 67610-308, now
  easyprivacy: 30710-85, now
  urlhaus-1: 5943-0, now
  plowe-0: 3738-1070, now
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 238 ms (selfie)
 maxAssetCacheWait: 141 ms
popupPanel:
 blocked: 72
 network:
  kompas.id: 61
  chartbeat.com: 1
  doubleclick.net: 3
  google-analytics.com: 1
  google.com: 3
  googletagmanager.com: 1
  youtube.com: 2
 extended:
  ##[id^="google_ads_iframe"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.ads-desktop
  ##.ads-mobile
  ##.category-advertorial
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/bd1a11615150efac9c0327c333a93108ec3d9a84
