### ISSUE TITLE
wellaware.eu: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18778]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wellaware.eu/products/artprotein-naturell`

### Category

nuisance

### Description

cookie notice bottom right corner

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19490515/0f6ecaef-9eaf-4c07-af7a-8faa08ee6329)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 18d.7h.50m
Firefox: 114
filterset (summary):
 network: 120639
 cosmetic: 160307
 scriptlet: 38381
 html: 1144
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2230-0, 14h.2m
  adguard-generic: 72026-5413, 3d.19h.39m
  adguard-spyware-url: 1101-147, 1d.22h.5m
  block-lan: 47-0, 7d.19h.49m
  fanboy-cookiemonster: 62472-15076, 18h.7m
  fanboy-social: 16103-4, 18h.6m
  ublock-annoyances: 5265-7, 18h.5m
  NOR-0: 3218-11, 14h.3m
  adguard-popup-overlays: 22774-569, 3d.19h.38m
  easylist-newsletters: 6221-11, 18h.9m
 default:
  user-filters: 5-0, never
  ublock-filters: 34521-135, 2d.18h.38m
  ublock-badware: 7653-0, 2d.18h.37m
  ublock-privacy: 459-2, 18h.8m
  ublock-unbreak: 2090-0, 2d.18h.36m
  ublock-quick-fixes: 252-3, 6h.15m
  easylist: 67489-774, 1d.18h.2m
  easyprivacy: 30604-617, 1d.18h.1m
  urlhaus-1: 5301-0, 14h.4m
  plowe-0: 3737-2, 7d.19h.49m
filterset (user): [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 818 ms (selfie)
 maxAssetCacheWait: 254 ms
popupPanel:
 blocked: 41
 network:
  wellaware.eu: 10
  bugsnag.com: 2
  google.com: 8
  klaviyo.com: 2
  shopify.com: 1
  shopifycloud.com: 10
  shopifysvc.com: 6
  yotpo.com: 2
```
</details>

**Comment by mapx-** [comment]
test for breakages

`wellaware.eu##.popup--cookies`

@ryanbr @Alex-302

However, the cookies have to be reported to the specialized lists (EasyList – Cookie Notices / AdGuard/uBO – Cookie Notices)

**Comment by Schanzation** [comment]
It works, thank you!
