### ISSUE TITLE
optyczne.pl [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1877]
URL(s) where the issue occurs

`https://www.optyczne.pl/620.1-artyku%C5%82-Irix_15_mm_f_2.4_Blackstone_i_fotografia_nocna_Rozdzia%C5%82_1.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`www.optyczne.pl###warning` Can't tell how much of the sidebar is ads.

**Comment by mapx-** [comment]
@MajkiIT
