### ISSUE TITLE
delete this

### ISSUE THREAD

**Issue by pigster117** [uBlockOrigin/uAssets#18774]

**Comment by pigster117** [comment]
delete this

**Comment by krystian3w** [comment]
You can delete account, nobody click in delete issue.

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/3079ec1c-e697-4c67-beef-5639e8046a8d)


---

Optionally, change the plugged-in email address to one forbidden by the platform and your account will get a global shadowban and no one will see this request anymore (it will redirect to a 404-type error).

**Comment by pigster117** [comment]
Delete this issue or I will encourage you to.
