### ISSUE TITLE
mathaeser.de: detection

### ISSUE THREAD

**Issue by marvinKaster** [uBlockOrigin/uAssets#18781]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mathaeser.de/mm`

### Category

detection

### Description

Website detects adblocker. 
Reproduce:
1) Visit 

`https://www.mathaeser.de/mm#dayprogram-1-1` 

Results in error message (see first screenshot) but website still usable.

2) Click on "Heute im Mathäser - München". Results in the second screenshot which completely blocks the website.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bildschirmfoto vom 2023-07-02 13-09-45](https://github.com/uBlockOrigin/uAssets/assets/51746304/0045817e-a36c-4cb7-92ac-cb39b9e651c8)
![Bildschirmfoto vom 2023-07-02 13-09-55](https://github.com/uBlockOrigin/uAssets/assets/51746304/03cc1d31-afc7-4152-bb75-20e047aac8e0)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1h.13m
Firefox: 114
filterset (summary):
 network: 95672
 cosmetic: 43870
 scriptlet: 17751
 html: 979
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 34559-71, 14m
  ublock-badware: 7685-1, 14m
  ublock-privacy: 459-0, 14m
  ublock-unbreak: 2093-3, 14m
  ublock-quick-fixes: 256-0, 14m
  easylist: 67610-743, 14m
  easyprivacy: 30710-733, 14m
  urlhaus-1: 5943-0, 14m
  plowe-0: 3738-1, 14m
  DEU-0: 6932-3, 14m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 173 ms (selfie)
 maxAssetCacheWait: 77 ms
popupPanel:
 blocked: 4
 network:
  adspirit.de: 3
  kinopolis.de: 1
```
</details>

**Comment by mapx-** [comment]
test

`mathaeser.de##+js(nostif, adb)`

**Comment by marvinKaster** [comment]
Thank you. That works
