### ISSUE TITLE
filmweb.pl: breakage

### ISSUE THREAD

**Issue by OLOPOLON** [uBlockOrigin/uAssets#18784]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.filmweb.pl/`

### Category

breakage

### Description

All videos on that site doesn't work anymore since yesterday. When I turned off uBlock Origin they work again. Firefox 113.0.2.

### Other extensions used

https://drive.google.com/file/d/1OR3N2IczIIo8HV9ThWlzcQliNRIEDh87/view?usp=sharing
https://drive.google.com/file/d/1ZaPeyDOoo89wWQvF2bt_plbJA0YtpP6Q/view?usp=sharing

### Screenshot(s)

https://drive.google.com/file/d/1OR3N2IczIIo8HV9ThWlzcQliNRIEDh87/view?usp=sharing
https://drive.google.com/file/d/1ZaPeyDOoo89wWQvF2bt_plbJA0YtpP6Q/view?usp=sharing

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 19d.6h.20m
Firefox: 113
filterset (summary):
 network: 98457
 cosmetic: 106505
 scriptlet: 20144
 html: 990
listset (total-discarded, last-updated):
 added:
  fanboy-thirdparty_social: 68-0, 9m
  fanboy-cookiemonster: 47789-223, 9m
  fanboy-social: 16086-17, 9m
 default:
  user-filters: 1581-44, never
  ublock-filters: 34563-95, 9m
  ublock-badware: 7685-0, 9m
  ublock-privacy: 459-0, 9m
  ublock-unbreak: 2093-3, 9m
  easylist: 67642-765, 9m
  easyprivacy: 30704-727, 9m
  urlhaus-1: 6260-0, 9m
  plowe-0: 3738-2, 9m
  POL-0: 7968-27, 9m
  POL-2: 1278-12, 9m
  ublock-quick-fixes: 257-0, 9m
filterset (user): [array of 1583 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  about-scheme
  moz-extension-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
 removed:
  no-csp-reports: * true
userSettings:
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 120
 autoUpdateDelayAfterLaunch: 180
 autoUpdatePeriod: 7
 selfieAfter: 3
supportStats:
 allReadyAfter: 904 ms
 maxAssetCacheWait: 231 ms
popupPanel:
 blocked: 9
 no-cosmetic-filtering: true
 network:
  filmweb.pl: 3
  gemius.pl: 2
  googletagmanager.com: 1
  nsaudience.pl: 1
  pushpushgo.com: 1
  sascdn.com: 1
```
</details>

**Comment by iam-py-test** [comment]
> Firefox 103.0.2

Your Firefox install is out of date. The latest version is 114.0.2

**Comment by OLOPOLON** [comment]
Firefox 113.03. That was a typo.

**Comment by ghajini** [comment]
occurs when **easylist cookie notices** is enabled
@ryanbr

**Comment by ryanbr** [comment]
Fixable with trusted cookies?

**Comment by OLOPOLON** [comment]
@ ryanbr "added a commit to easylist/easylist that referenced this issue Jul 3, 2023 "
I'm total github grennhorn. What does it mean? Should I wait for filters update or something?

**Comment by mapx-** [comment]
open uBO dashboard, filter lists tab, purge all caches, updare now

**Comment by OLOPOLON** [comment]
So I did. Nothing hasn't change. Still, all videos aren't working.

**Comment by mapx-** [comment]
1. Disable all other extensions, test again
2. If still does not work provide a specific page / movie / where does happen.

**Comment by OLOPOLON** [comment]
1. I did that. Failure once again.
2. Example page:  https://www.filmweb.pl/video/Zwiastun/Indiana+Jones+i+artefakt+przeznaczenia+Zwiastun+nr+2+polskie+napisy-64884

**Comment by mapx-** [comment]
add (in `my filters` tab - then click `apply changes`) & test

```
@@||ced.sascdn.com/tag/*/smart.js$script,domain=filmweb.pl
@@||smartadserver.com/genericpost$xhr,domain=filmweb.pl
```

**Comment by OLOPOLON** [comment]
Still nothing.

**Comment by ryanbr** [comment]
Not having issues, other than cookie messages.  (purge and update lists)

https://gif.fanboy.co.nz/gif/filmweb.gif

**Comment by OLOPOLON** [comment]
You don' have issues. I am still having them. Easy List filters and these filters  [https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard](url) are causing problems

**Comment by stephenhawk8054** [comment]
@OLOPOLON Do you have an issue after clicking on the cookie banner, or the issue occurs when refreshing after that?

**Comment by ryanbr** [comment]
Any other extensions installed? I removed the cookie message cosmetic. Disabling each list in uBO which one fixes it?

**Comment by mapx-** [comment]
Without my filters I get the video only bypassing the cache

**Comment by dportvine** [comment]
```
@@||ced.sascdn.com/tag/*/smart.js$script,domain=filmweb.pl
@@||smartadserver.com/genericpost$xhr,domain=filmweb.pl
```
This works for me.

<details>
<summary>Video</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/7246dffc-22f3-46d7-98b2-2f21096268ae
</details>

**Comment by dportvine** [comment]
`https://www.filmweb.pl/video/Zwiastun/Indiana+Jones+i+artefakt+przeznaczenia+Zwiastun+nr+2+polskie+napisy-64884`

<details>
<summary>Screen</summary>

![2023-07-04_162048](https://github.com/uBlockOrigin/uAssets/assets/111344219/8ab2c045-d644-48a5-a43c-4b7fe68d29a5)
</details>

<details>

```yaml
uBlock Origin 1.50.0:
 since: 25d.21h.12m
Chromium: 114
filterset (summary):
 network: 112311
 cosmetic: 135416
 scriptlet: 25197
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26149-18, 4m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1623-25, 4m
  fanboy-cookiemonster: 47799-407, 4m
  ublock-annoyances: 5300-56, 4m
  POL-0: 7964-45, 1m
  POL-2: 1275-48, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 33752-42, 4m
  ublock-badware: 7480-0, 4m
  ublock-privacy: 423-2, 4m
  ublock-unbreak: 2065-6, 4m
  ublock-quick-fixes: 267-19, 4m
  easylist: 67761-324, 4m
  easyprivacy: 33394-401, 4m
  RUS-0: 39449-289, 4m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 1320 ms
 maxAssetCacheWait: 679 ms
popupPanel:
 blocked: 20
 network:
  filmweb.pl: 2
  doubleclick.net: 3
  fwcdn.pl: 1
  gemius.pl: 1
  google.com: 3
  googlesyndication.com: 3
  googletagmanager.com: 1
  id5-sync.com: 1
  nsaudience.pl: 1
  pushpushgo.com: 1
  smartadserver.com: 3
 extended:
  ##+js(abort-current-script, addEventListener, /faBar[\s\S]*?inse…
  ##+js(nano-remove-elements-onready, #skyBanner)
  ##+js(abort-current-script, IRI, Adblock)
  #@#+js(abort-current-script, decodeURIComponent, newAdblockBoard…
  #@#+js(no-setTimeout-if, notDetected)
```
</details>

**Comment by rafx85** [comment]
For me, this website for example does not show videos:
https://www.filmweb.pl/video/Zwiastun/Pan+Idealny+Zwiastun+nr+1+polski-39425
Looks like this:
https://i.postimg.cc/Y0LNC5Xw/screenshot-453.png
Disabling all filters make the videos work:
https://i.postimg.cc/pyNSWYJq/screenshot-454.png
https://i.postimg.cc/Mpt8DNDw/screenshot-455.png

**Comment by peace2000** [comment]
@dportvine Yeah, added: https://github.com/uBlockOrigin/uAssets/commit/91080575bd3d55572e7774a7e9ebadd020ba11e8

**Comment by OLOPOLON** [comment]
OK. I wasn't here cause my job. I did some tests, and I have one conclusion. Problem is only happening when I'm logged in an then I see  same what rafx85 described. When I'm not I can watch all videos I want.

**Comment by ghajini** [comment]
on my side video loads sometimes even with no blocker
