### ISSUE TITLE
tek.no: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18783]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tek.no/`

### Category

nuisance

### Description

This pop-up in the middle of the screen come up every day I go in to this website. Any way I can block it?

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19490515/977e922c-7ab8-4e9e-a968-f06fa4409f63)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 18d.11h.51m
Firefox: 114
filterset (summary):
 network: 121423
 cosmetic: 160397
 scriptlet: 38494
 html: 1154
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2230-0, 3h.11m
  adguard-generic: 72071-5422, 3h.11m
  adguard-spyware-url: 1104-147, 3h.11m
  block-lan: 47-0, 3h.11m
  fanboy-cookiemonster: 47787-291, 3h.11m
  fanboy-social: 16086-4, 3h.11m
  ublock-annoyances: 5265-7, 3h.11m
  NOR-0: 3218-11, 3h.11m
  adguard-popup-overlays: 22815-550, 3h.11m
  easylist-newsletters: 6223-11, 3h.11m
 default:
  user-filters: 6-0, never
  ublock-filters: 34558-133, 3h.11m
  ublock-badware: 7680-0, 3h.11m
  ublock-privacy: 459-2, 3h.11m
  ublock-unbreak: 2091-3, 3h.11m
  ublock-quick-fixes: 250-0, 3h.11m
  easylist: 67610-784, 3h.11m
  easyprivacy: 30710-728, 3h.11m
  urlhaus-1: 5943-0, 3h.11m
  plowe-0: 3738-2, 3h.11m
filterset (user): [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1015 ms (selfie)
 maxAssetCacheWait: 243 ms
popupPanel:
 blocked: 8
 network:
  tek.no: 1
  adnxs.com: 1
  datadoghq-browser-agent.com: 2
  googletagmanager.com: 1
  medietall.no: 1
  schibsted.com: 2
 extended:
  ##main > div > section + div:last-of-type
  ##body::before
  ##.adSpace
  ##.sch-datacontroller
  ##main:style(min-height: unset !important)
  ##+js(abort-on-property-write, __AB__)
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by mapx-** [comment]
add

```
tek.no##.cf-container-wrapper
tek.no##body:style(overflow: auto !important;)
```

@ryanbr

**Comment by mapx-** [comment]
@Schanzation already blocked by [EasyList – Notifications](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=easylist-notifications)

just enable it
