### ISSUE TITLE
kitakerjaremote.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18789]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kitakerjaremote.com/`

### Category

ads

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/5a7f5873-8a60-474b-b9e9-b01064abfa94)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 15d.22h.2m
Chromium: 114
filterset (summary):
 network: 129979
 cosmetic: 135683
 scriptlet: 24870
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9166-3, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, now
  DEU-0: 6933-0, 34m
  FRA-0: 28352-65, now
  IDN-0: 9527-376, now
  ara-0: 2326-9, now
  easylist-annoyances: 3881-42, now
  easylist-chat: 127-0, now
  easylist-newsletters: 6224-15, now
  easylist-notifications: 2639-85, now
  fanboy-cookiemonster: 47790-223, now
  fanboy-social: 16086-16, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 67686-314, now
  easyprivacy: 33436-443, now
  plowe-0: 3738-1080, now
  ublock-badware: 7683-155, now
  ublock-filters: 33690-413, now
  ublock-privacy: 419-6, now
  ublock-quick-fixes: 258-19, now
  ublock-unbreak: 2059-46, now
  urlhaus-1: 6306-1, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1601 ms (selfie)
 maxAssetCacheWait: 469 ms
popupPanel:
 blocked: 11
 network:
  doubleclick.net: 4
  youtube.com: 7
 extended:
  ##.elementor-widget-social-icons
  ##.elementor-social-icons-wrapper
  ##.elementor-social-icon
  ##.ytp-ad-progress-list
  ##.ytp-title-channel
  ##.ytp-share-button
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
```
</details>

**Comment by mapx-** [comment]
add

```
kitakerjaremote.com##.wpr-popup-open
kitakerjaremote.com##body:style(overflow: auto !important;)
```

@ryanbr
