### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by TheRobbebas** [uBlockOrigin/uAssets#18785]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reddit.com/r/NoStupidQuestions/comments/14orngy/my_husband_is_40_and_has_been_in_university_for/`

### Category

breakage

### Description

Reddit launched a slightly new UI when viewing posts. Using the searchbar with uBlock Origin does not work as expected, pressing enter does not launch a search but does nothing, removing the subreddit filter also doesn't work. Disabling EasyPrivacy (which has shreddit) resolves the issue.

### Other extensions used

PrivacyBadger (issue persists when PrivacyBadger is turned off)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 113
filterset (summary): 
 network: 93727
 cosmetic: 39303
 scriptlet: 17791
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  easylist: 67687-50, 4m
  easyprivacy: 30703-59, 4m
  plowe-0: 3738-1068, 11m
  ublock-badware: 7683-138, 11m
  ublock-filters: 33689-146, 11m
  ublock-privacy: 418-3, 11m
  ublock-quick-fixes: 257-19, 11m
  ublock-unbreak: 2059-35, 10m
  urlhaus-1: 6260-0, 10m
filterset (user): [empty]
trustedset: 
 added: [array of 2 redacted]
modifiedUserSettings: 
 showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 216 ms (selfie)
 maxAssetCacheWait: 111 ms
popupPanel: 
 blocked: 11
 network: 
  reddit.com: 7
  datadome.co: 1
  redditstatic.com: 2
  sentry.io: 1
 cosmetic: 
  ##.AdHeader
  ##.AdUnit
  ##.adsense-ads
  ##.HeaderAd
  ##.SidebarAd
  ##.VerticalAd
  ##._has-ads
  ##.ad--content
  ##.ad-adsense
  ##.googads
  ##.ad-banner-content
  ##.googleAd
  ##.googlead
  ##.hasads
  ##.leftAd
  ##.native-ad
  ##.ADBAR
  ##.ad-medium
  ##.post-ad
  ##.promoad
  ##.rectad
  ##.sidebar-ad:not(.adsbygoogle)
  ##.small-ad
  ##.sponsorAd
  ##.sponsorPost
  ##.promotedlink
```
</details>

**Comment by iam-py-test** [comment]
Seems to be caused by 
```adblock
||redditstatic.com/shreddit/*/ad-event-
```
@ryanbr

**Comment by ryanbr** [comment]
`easyprivacy/easyprivacy_specific.txt:||redditstatic.com/shreddit/*/ad-event-`

**Comment by ryanbr** [comment]
Sorry, what is the fault?

**Comment by stephenhawk8054** [comment]
> `||www.redditstatic.com/shreddit/en-US/ad-event*.js$script,redirect=noopjs,domain=reddit.com`
> 
> works,any breakages?

Confirm

```adb
||redditstatic.com/shreddit/$script,redirect-rule=noopjs,domain=reddit.com
```

works for me

**Comment by ghajini** [comment]
op said **search function(search suggestions etc)** doesn't work due to `||redditstatic.com/shreddit/*/ad-event-`

on my said when i add `||www.redditstatic.com/shreddit/en-US/ad-event*.js$script,redirect=noopjs,domain=reddit.com`
it works but i want to know if any other breakage occurs or not
