### ISSUE TITLE
bible-history.com: detection

### ISSUE THREAD

**Issue by IDLC-BT** [uBlockOrigin/uAssets#18788]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bible-history.com/jewishtemple/court-of-the-gentiles`

### Category

detection

### Description

detects adblock and does not allow access to web site

### Other extensions used

dark reader
read aloud
awesome screenshot
privacybadger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 14d.21h.41m
Firefox: 114
filterset (summary):
 network: 93723
 cosmetic: 39280
 scriptlet: 17748
 html: 971
listset (total-discarded, last-updated):
 default:
  user-filters: 6-1, never
  ublock-filters: 34557-57, 2d.7h
  ublock-badware: 7671-0, 2d.6h.59m
  ublock-privacy: 457-0, 4d.18h.15m
  ublock-unbreak: 2094-0, 2d.12h.18m
  easylist: 67642-736, 4h.21m
  easyprivacy: 30611-612, 4d.9h
  urlhaus-1: 6260-0, 13h.14m
  plowe-0: 3737-2, 8d.20h.9m
  ublock-quick-fixes: 256-3, 6h.22m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 179 ms (selfie)
 maxAssetCacheWait: 59 ms
popupPanel:
 blocked: 11
 network:
  addthis.com: 2
  clarity.ms: 1
  googlesyndication.com: 6
  googletagmanager.com: 1
  yandex.ru: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by ghajini** [comment]
can't reproduce the detection...tell us steps to reproduce the detection

also disable the other extensions & see if that works
