### ISSUE TITLE
nicomanga.com: popups

### ISSUE THREAD

**Issue by pubct** [uBlockOrigin/uAssets#18797]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A popup for ad placement. The ad is successfully blocked, but the popup remains.

### URL(s) where the issue occurs.

`https://nicomanga.com/read-yuusha-party-o-oida-sareta-kiyou-binbou-chapter-1.1.html`

### uBO version

1.50.0

### Browser name and version

Chrome 114.0.5735.199

### Settings

.

### Notes

After I closed the first popup on first visit and refresh, the popup appears again.
However, after I closed the popup the second time then refresh, the popup doesn't appear anymore.
So, not sure if there are 2 elements that needs to be blocked.

**Comment by mapx-** [comment]
add

```
nicomanga.com##.show.fade.modal
nicomanga.com##.show.fade.modal-backdrop
nicomanga.com##body:style(overflow: auto !important;)
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Given its an advert, should be in uAssets?

**Comment by stephenhawk8054** [comment]
There's popup too, so I think we can address it
