### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by hauhui** [uBlockOrigin/uAssets#18791]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.investing.com/currencies/zar-cny`

### Category

detection

### Description

Ublock origin detection

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 23d.22h.38m
Chromium: 114
filterset (summary):
 network: 109325
 cosmetic: 49482
 scriptlet: 17911
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  CHN-0: 26334-118, 3d.18h.15m
  easylist: 67521-110, 5d.18h.41m
  easyprivacy: 30717-75, 1d.14h.51m
  plowe-0: 3737-1063, 10d.22h.31m
  ublock-badware: 7651-138, 3d.16h.14m
  ublock-filters: 33640-154, 3d.18h.17m
  ublock-privacy: 418-3, 2d.20h.27m
  ublock-quick-fixes: 251-19, 20h.36m
  ublock-unbreak: 2061-39, 3d.18h.16m
  urlhaus-1: 6260-0, 18h.35m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 448 ms (selfie)
 maxAssetCacheWait: 271 ms
popupPanel:
 blocked: 11
 network:
  investing.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  dggaenaawxe8z.cloudfront.net: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  hotjar.com: 1
  pbxai.com: 1
  primis.tech: 1
 extended:
  ##.py-10.px-12
  ##.midHeader
  ##div[data-test="ad-slot-visible"]
  ##[class*="overlay_overlay"]
  ###__next > .fixed
  ##+js(no-fetch-if, ads)
  ##+js(replace-node-text, script, /adb/i, xxx)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists and test again?

**Comment by hauhui** [comment]
Good Morning,
thank you, it's fixed after updated the lists.


















At 2023-07-03 15:17:57, "stephenhawk8054" ***@***.***> wrote:

Can you force update all your filter lists and test again?
