### ISSUE TITLE
sueddeutsche.de: ads

### ISSUE THREAD

**Issue by felix-1-1-1** [uBlockOrigin/uAssets#18794]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sueddeutsche.de/muenchen/freising/moosburg-regenbogenflagge-jaehrliche-aktion-aufgeschlossenheit-toleranz-1.5981296`

### Category

ads

### Description

Ads still being displayed

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/82533359/92bc088e-6841-47c1-a519-c96732fdf6d2)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 24d.21h.48m
Chromium: 114
filterset (summary):
 network: 100783
 cosmetic: 87402
 scriptlet: 19982
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist.to/easylist/easylist.txt: 67744-50, 2m
  fanboy-cookiemonster: 47793-215, 2m
 default:
  user-filters: 2-0, never
  DEU-0: 6933-6, 42m
  easylist: 67746-67744, now
  easyprivacy: 33437-71, 42m
  plowe-0: 3738-1068, 42m
  ublock-badware: 7740-138, now
  ublock-filters: 33673-172, now
  ublock-privacy: 421-3, now
  ublock-quick-fixes: 255-17, 42m
  ublock-unbreak: 2058-38, now
  urlhaus-1: 6306-1, 42m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 330 ms (selfie)
 maxAssetCacheWait: 96 ms
popupPanel:
 blocked: 9
 network:
  sueddeutsche.de: 5
  google.com: 2
  googletagmanager.com: 1
  vgwort.de: 1
 extended:
  ##+js(abort-on-property-read, _sp_._networkListenerData)
  ##+js(abort-on-property-write, SZAdBlockDetection)
  ##+js(set-constant, _sp_.config, undefined)
```
</details>

**Comment by mapx-** [comment]
`sueddeutsche.de##+js(nostif, .call(null), 10)`
