### ISSUE TITLE
namecheckr.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18790]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.namecheckr.com/`

### Category

breakage

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/8251e9bf-7ad2-42d0-a969-23081c0ed91d)

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/f9cf26c4-eba5-42d7-8429-5d8409455e2f)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 15d.23h.31m
Chromium: 114
filterset (summary):
 network: 129979
 cosmetic: 135683
 scriptlet: 24870
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9166-3, 1h.29m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 1h.29m
  DEU-0: 6933-0, now
  FRA-0: 28352-65, 1h.29m
  IDN-0: 9527-376, 1h.29m
  ara-0: 2326-9, 1h.29m
  easylist-annoyances: 3881-42, 1h.29m
  easylist-chat: 127-0, 1h.29m
  easylist-newsletters: 6224-15, 1h.29m
  easylist-notifications: 2639-85, 1h.29m
  fanboy-cookiemonster: 47790-223, 1h.29m
  fanboy-social: 16086-16, 1h.29m
  [1 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 67686-314, 1h.29m
  easyprivacy: 33436-443, 1h.29m
  plowe-0: 3738-1080, 1h.29m
  ublock-badware: 7683-155, 1h.29m
  ublock-filters: 33690-413, 1h.29m
  ublock-privacy: 419-6, 1h.29m
  ublock-quick-fixes: 258-19, 1h.29m
  ublock-unbreak: 2059-46, 1h.29m
  urlhaus-1: 6306-1, 1h.29m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1601 ms (selfie)
 maxAssetCacheWait: 469 ms
popupPanel:
 blocked: 4
 network:
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##.socialbox
  ##.grecaptcha-badge
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by ghajini** [comment]
caused by `##.socialbox` in **easylist-social widgets**
