### ISSUE TITLE
signup.grasshopper.com: breakage

### ISSUE THREAD

**Issue by strangerwithaname** [uBlockOrigin/uAssets#18795]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://signup.grasshopper.com/plans`

### Category

breakage

### Description

The pricing places don't show up. Error message "oops something went wrong"

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 19d.20h.14m
Chromium: 114
filterset (summary):
 network: 96363
 cosmetic: 39267
 scriptlet: 17791
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67506-50, 2h.2m
  easyprivacy: 33437-62, 2h.1m
  plowe-0: 3737-1064, 11d.16h.5m
  ublock-badware: 7683-138, 2h.1m
  ublock-filters: 33689-145, 2h.1m
  ublock-privacy: 420-3, 2h.1m
  ublock-quick-fixes: 255-18, 2h.1m
  ublock-unbreak: 2059-36, 2h.1m
  urlhaus-1: 6306-1, 2h.1m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2608 ms (selfie)
 maxAssetCacheWait: 1144 ms
popupPanel:
 blocked: 6
 network:
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 3
  trustarc.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
@strangerwithaname force update the filterlists to get the fix directly. I also reported to EasyPrivacy so i will keep this open until it got fixed by EP.
