### ISSUE TITLE
nl.motorsport.com: detection

### ISSUE THREAD

**Issue by marwijn** [uBlockOrigin/uAssets#18808]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nl.motorsport.com/f1/news/toto-wolff-weet-zeker-fia-valsspelers-budgetplafond-aanpakken/10491291/`

### Category

detection

### Description

Show in red : To read the content, please disable your adBlocker or subscribe [here](https://nl.motorsport.com/prime)

Problem persists after Purging caches and updating filter list. 

Had the same problem about a week ago, but then it was solved with clearing caches and updating.

### Other extensions used

Tampermonkey (tried disabling, no effect)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 10d.22h.41m
Chromium: 114
filterset (summary):
 network: 95551
 cosmetic: 41400
 scriptlet: 17939
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  NLD-0: 2907-10, now
  easylist: 67761-54, now
  easyprivacy: 33394-63, now
  plowe-0: 3739-1067, now
  ublock-badware: 7480-138, now
  ublock-filters: 33749-165, now
  ublock-privacy: 423-3, now
  ublock-quick-fixes: 269-16, now
  ublock-unbreak: 2065-42, now
  urlhaus-1: 4816-2, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1107 ms (selfie)
 maxAssetCacheWait: 220 ms
popupPanel:
 blocked: 10
 network:
  motorsport.com: 5
  chartbeat.com: 1
  cxense.com: 1
  mmcdn.nl: 1
  ntv.io: 1
  outbrain.com: 1
 extended:
  ##.ms-hapb
  ##.ms-ap
  ##.ms-apb-dmpu
  ##+js(addEventListener-defuser, load, length)
  ##+js(addEventListener-defuser, gtmloaderror)
  ##+js(noeval-if, interactionCount)
  ##+js(abort-current-script, vardom)
  ##+js(cookie-remover, adbl49DetectNb)
  ##+js(abort-on-stack-trace, $.cookie, mstm)
```
</details>

**Comment by marwijn** [comment]
Sorry to inform you, the patch worked, but the today the same issues has reappeared again. 
Should I create a new issue.
I tried visiting : https://nl.motorsport.com/f1/news/max-verstappen-deelt-lakens-uit-eerste-dag-f1-gp-groot-brittannie/10492708/

**Comment by stephenhawk8054** [comment]
Just continue in the old threads, there are already many duplicated issues. We are all informed with new comments, no need to open another duplicated issue.
