### ISSUE TITLE
en.daciaclub.cz [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1880]
URL(s) where the issue occurs

`http://en.daciaclub.cz/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`@@||en.daciaclub.cz^$generichide`

**Comment by mapx-** [comment]
@tomasko126
