### ISSUE TITLE
djxmaza.in: detection

### ISSUE THREAD

**Issue by UblockAntiAdblock** [uBlockOrigin/uAssets#18801]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://djxmaza.in/how-to-search-available-website-domain-names/`

### Category

detection

### Description

Detected
Apparently the shortener changes the URL every time it is opened.
Attached the link of linkvertise.
`https://linkvertise.com/245167/photomath-v8250-premium/1`
### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.2h.12m
Firefox Mobile: 116
filterset (summary):
 network: 116644
 cosmetic: 86595
 scriptlet: 32554
 html: 981
listset (total-discarded, last-updated):
 added:
  adguard-generic: 72155-5323, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 34817-122, 1m
  ublock-badware: 7461-0, 1m
  ublock-privacy: 463-0, 1m
  ublock-unbreak: 2098-0, 1m
  ublock-quick-fixes: 263-3, 1m
  adguard-mobile: 8347-97, 1m
  easylist: 67751-815, 1m
  easyprivacy: 33415-746, now
  urlhaus-1: 4816-2, now
  plowe-0: 3739-2, now
  spa-0: 3724-4, now
  spa-1: 5324-160, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 tooltipsDisabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 549 ms (selfie)
 maxAssetCacheWait: 222 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ###featuredimage:style(height:250px !important;left:-3000px !imp…
  ##+js(no-fetch-if, /adtrue\.com|eningspon\.com|freychang\.fun|or…
  ##+js(no-xhr-if, /a-mo\.net|adnxs\.com|prebid|creativecdn\.com|e…
  ##+js(nobab)
  ##+js(addEventListener-defuser, DOMContentLoaded, antiAdBlockerH…
  ##+js(no-xhr-if, /adtrue\.com|eningspon\.com|freychang\.fun|orqu…
  ##+js(no-fetch-if, /a-mo\.net|adnxs\.com|prebid|creativecdn\.com…
```
</details>

**Comment by gorhill** [comment]
Try and report if this works:

    @||adoto.net/dashboard/common/js/common.js$3p,script,domain=dev.miuiflash.com|djxmaza.in|thecubexguide.com

**Comment by UblockAntiAdblock** [comment]
> Try and report if this works:
> 
> ```
> @||adoto.net/dashboard/common/js/common.js$3p,script,domain=dev.miuiflash.com|djxmaza.in|thecubexguide.com
> ```

Dont work

**Comment by Daxy7** [comment]
> Dont work

this one? there was a typo on the `@`

```
@@||adoto.net/dashboard/common/js/common.js$3p,script,domain=dev.miuiflash.com|djxmaza.in|thecubexguide.com
```

**Comment by gorhill** [comment]
Oops, yes, typo, should be as @Daxy7 says.

**Comment by UblockAntiAdblock** [comment]
> > Dont work
> 
> this one? there was a typo on the `@`
> 
> ```
> @@||adoto.net/dashboard/common/js/common.js$3p,script,domain=dev.miuiflash.com|djxmaza.in|thecubexguide.com
> ```



> Oops, yes, typo, should be as @Daxy7 says.

sorry for the delay. it worked! thank you so much!
