### ISSUE TITLE
liquidweb.com: ads

### ISSUE THREAD

**Issue by heartlog** [uBlockOrigin/uAssets#18802]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.liquidweb.com/kb/how-to-install-chocolatey-on-windows/`

### Category

ads

### Description

leftover ad

### Other extensions used

adguard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/76758776/224aeec6-ee0c-48c1-a731-cc61b4237c2c)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 6d.11h.9m
Chromium: 114
filterset (summary):
 network: 167899
 cosmetic: 167466
 scriptlet: 35760
 html: 0
listset (total-discarded, last-updated):
 added:
  IND-0: 12818-0, now
  adguard-cookies: 26175-29, now
  adguard-generic: 72155-483, now
  adguard-mobile: 8347-46, now
  adguard-mobile-app-banners: 4390-8, now
  adguard-other-annoyances: 13031-7, now
  adguard-popup-overlays: 22833-70, now
  adguard-social: 20803-880, now
  adguard-spyware: 60323-1243, now
  adguard-spyware-url: 1105-3, now
  adguard-widgets: 2190-7, now
 default:
  user-filters: 82-13, never
  easylist: 67755-1035, 25m
  easyprivacy: 33415-16634, now
  plowe-0: 3739-1233, now
  ublock-badware: 7465-365, now
  ublock-filters: 33677-4141, now
  ublock-privacy: 423-64, now
  ublock-quick-fixes: 260-15, 24m
  ublock-unbreak: 2059-134, now
  urlhaus-1: 4816-2, now
filterset (user): [array of 82 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8831 ms (selfie)
 maxAssetCacheWait: 688 ms
popupPanel:
 blocked: 6
 network:
  force.com: 1
  googletagmanager.com: 1
  hs-scripts.com: 1
  hsforms.com: 3
 extended:
  ##.pre-header-promo-item.dCcBkN.PreHeaderPromo__SPromoItem-sc-17…
  ##.text-xs.z-40.w-full.sticky.esDYHx.global-pre-header__SDiv-sc-…
  ##.p-4
  ##.knowledgeBase + div[class]
  ##.subscribe-sidebar-form
  ##footer + div[class^="FixedButton_"]
  ##a[href*="http://twitter.com/share"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
```
</details>

**Comment by gorhill** [comment]
It's self-promo, not blocked [by policy](https://easylist.to/pages/policy.html):

> Self-promotion (any type of advertising that promotes goods or services that are owned or operated by the domain owner and doesn’t get commercially compensated for by third parties (examples can include new features, new posts, newsletters, subscriptions to printed media products, merchandise etc.)) won't be targeted directly.

**Comment by gorhill** [comment]
> Other extensions used
> 
> adguard

Also, don't use other content blockers along uBO.
