### ISSUE TITLE
iqbroker.com: popups

### ISSUE THREAD

**Issue by romabos69** [uBlockOrigin/uAssets#18804]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://iqbroker.com/land/start-trading/en/?aff=74213&afftrack=iqenpropellercis&clickid=wh610f1jnfhml9tpi79etcg4`

### Category

popups

### Description

every time I launch my browser, otherwise start my computer, as my browser opens on startup, this page appears, with the prompt telling me that ublock origin has prevented me from going to this site.

### Other extensions used

Browse VPN
Google Authenticator
SponsorBlock for YouTube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 18d.17h.20m
Chromium: 114
filterset (summary):
 network: 110903
 cosmetic: 60123
 scriptlet: 19043
 html: 0
listset (total-discarded, last-updated):
 added:
  RUS-0: 39442-9, 13h.36m
 default:
  user-filters: 0-0, never
  easylist: 67610-74, 1d.18h.12m
  easyprivacy: 30704-148, 1d.18h.13m
  plowe-0: 3737-1070, 8d.11h.15m
  ublock-badware: 7678-138, 2d.14h.33m
  ublock-filters: 33651-173, 2d.14h.35m
  ublock-privacy: 418-4, 1d.9h.50m
  ublock-quick-fixes: 260-17, 16h.48m
  ublock-unbreak: 2066-35, 2d.14h.34m
  urlhaus-1: 6335-1, 11h.35m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1300 ms (selfie)
 maxAssetCacheWait: 472 ms
popupPanel:
 blocked: 11
 network:
  iqbroker.com: 1
  iqtrading.asia: 10
```
</details>

**Comment by ghajini** [comment]
there can be 2 scenarios

1. This popup may have arrived from other websites , provide those websites here, so that it can be fixed
 
or

2. you may be infected with some potentially unwanted applications(pup)

scan your system for adwares/
