### ISSUE TITLE
coincodex.com: breakage

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18806]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://coincodex.com/`

### Category

breakage

### Description

This website is missing the top 2 bars on the website with the list "EasyList - Notifications" enabled.

Also. How do I remove the "Free spins" button and the leftover ad on the right side?

### Other extensions used

none

### Screenshot(s)

![UtenAdBlocker](https://github.com/uBlockOrigin/uAssets/assets/19490515/04c32431-51e9-4626-98cc-ba90f3de4c78)
![Med AdBlocker](https://github.com/uBlockOrigin/uAssets/assets/19490515/f0100029-1267-4090-80eb-478de0f15ae2)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 20d.10h.43m
Firefox: 114
filterset (summary):
 network: 239600
 cosmetic: 202226
 scriptlet: 38723
 html: 1155
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2230-0, 21h.55m
  adguard-generic: 72071-5426, 1d.22h.48m
  adguard-spyware-url: 1104-147, 1d.22h.48m
  block-lan: 47-0, 1d.22h.48m
  curben-phishing: 115054-39, 1d.1h.21m
  curben-pup: 199-0, 1d.1h.22m
  adguard-social: 20772-687, 1d.1h.21m
  fanboy-thirdparty_social: 68-0, 1d.1h.10m
  fanboy-cookiemonster: 47787-3815, 1d.22h.48m
  fanboy-social: 16086-19, 1d.22h.48m
  ublock-annoyances: 5265-13, 1d.22h.48m
  NOR-0: 3218-11, 21h.56m
  [5 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 34561-65, 1d.22h.48m
  ublock-badware: 7685-0, 1d.22h.48m
  ublock-privacy: 459-2, 1d.22h.48m
  ublock-unbreak: 2093-0, 1d.22h.48m
  ublock-quick-fixes: 263-3, 7h.53m
  easylist: 67610-791, 1d.22h.48m
  easyprivacy: 30710-804, 1d.22h.48m
  urlhaus-1: 6335-1, 21h.57m
  plowe-0: 3738-2, 1d.22h.48m
filterset (user): [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 771 ms (selfie)
 maxAssetCacheWait: 434 ms
popupPanel:
 blocked: 10
 network:
  coincodex.com: 2
  coinzillatag.com: 6
  googletagmanager.com: 1
  onesignal.com: 1
 extended:
  ##.app
  ##app-header
  ##.subscribe
  ##[class*="clickout-"]
  ##div[class*="_sticky-header"]
```
</details>

**Comment by gorhill** [comment]
Caused by `coincodex.com##app-header` in <https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_notifications_specific_hide.txt>. cc @ryanbr

**Comment by gorhill** [comment]
> How do I remove the "Free spins" button and the leftover ad on the right side?

Use:

    coincodex.com###scroller-wrapper
    coincodex.com##.lower-nav > a[target]

**Comment by Schanzation** [comment]
Thank you

**Comment by Schanzation** [comment]
After a few minutes using the site this button suddenly appear. Though it's not that big of a deal.

![Screenshot 2023-07-04 145052](https://github.com/uBlockOrigin/uAssets/assets/19490515/175b8367-736c-484d-ada6-5b43c5456d83)
