### ISSUE TITLE
totalcsgo.com: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#18816]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://totalcsgo.com/`

### Category

ads

### Description

There is a clash.gg ad there

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ads](https://github.com/uBlockOrigin/uAssets/assets/50150516/a712406e-0da2-4d07-a519-3cd67f96a135)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 26d.18h.5m
Chromium: 114
filterset (summary):
 network: 96469
 cosmetic: 39307
 scriptlet: 17887
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67822-9, now
  easyprivacy: 33394-62, now
  plowe-0: 3739-1068, now
  ublock-badware: 7480-138, now
  ublock-filters: 33753-146, now
  ublock-privacy: 423-3, 39m
  ublock-quick-fixes: 267-16, now
  ublock-unbreak: 2065-37, now
  urlhaus-1: 6356-3, now
filterset (user): [empty]
trustedset:
 added: [array of 51 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3572 ms (selfie)
 maxAssetCacheWait: 646 ms
popupPanel:
 blocked: 11
 network:
  avantisvideo.com: 1
  google-analytics.com: 2
  google.com: 5
  googletagmanager.com: 1
  googletagservices.com: 1
  srvtrck.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr  `totalcsgo.com##[href^="https://clash.gg/"]`

**Comment by dann2g** [comment]
This fix breaks the following pages:
https://totalcsgo.com/crosshair-generator (map images)
https://totalcsgo.com/skin-trading-sites (section images)
...and will break things elsewhere on the site too.

As an alternative, you can just block the image URL (/v2/site-takeover) or background-image style on .body-container.

(I am the site owner)

**Comment by Omega-6** [comment]
placeholder under logo

```
totalcsgo.com##.container[style="height:135px"]
```
