### ISSUE TITLE
sicor.poderjudicialdf.gob.mx: nuisance

### ISSUE THREAD

**Issue by Ehyeh-Aries** [uBlockOrigin/uAssets#18811]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sicor.poderjudicialdf.gob.mx/principal.php`

### Category

nuisance

### Description

there is a pop up that can be removed but when I re enter the page it appears again

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 13m
Chromium: 114
filterset (summary):
 network: 99100
 cosmetic: 45209
 scriptlet: 18128
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67825-9, 12m
  easyprivacy: 33437-62, 12m
  plowe-0: 3739-1068, 12m
  spa-0: 3724-12, 13m
  spa-1: 5327-214, 13m
  ublock-badware: 7480-138, 12m
  ublock-filters: 33689-174, 12m
  ublock-privacy: 418-3, 12m
  ublock-quick-fixes: 267-11, 12m
  ublock-unbreak: 2065-39, 12m
  urlhaus-1: 6356-3, 12m
filterset (user): [empty]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 134 ms (selfie)
 maxAssetCacheWait: 73 ms
popupPanel:
 blocked: 0
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
```
</details>

**Comment by stephenhawk8054** [comment]
Try this filter:

```adb
sicor.poderjudicialdf.gob.mx###popupBackground
```

**Comment by Ehyeh-Aries** [comment]
It worked, but in this case, I want certain popups to be blocked but not
all the popups. There are some files that can only be accessed through a
popup (I know terrible website). May I block only the annoying one from the
login page?

**Comment by stephenhawk8054** [comment]
So, are there any breakages with the above filter? I can't answer unless there's another example page that has breakages.

**Comment by Ehyeh-Aries** [comment]
Sorry, my bad explaining. On the login page there is a popup saying that
the rules of the site whatever.... with this code it was blocked really
cool (sicor.poderjudicialdf.gob.mx###popupBackground). Now, when I access
the website to my account, I need to see my client files, but those files
are not in PDF format, those are hyperlinks that when clicked open as a
popup. Below I will attach the screenshots. What I need is to block pop1
and pop1.1 only, and leave the pop3.1. Hope makes sense with pics.

[image: pop1.png]
POP1


[image: pop1.1.png]
POP1.1


These ones are to be removed!!


And now, the good ones are these ones below:


[image: pop3 and 3.1.png]

**Comment by stephenhawk8054** [comment]
Don't reply via email, github cannot display images when you reply by email. Please comment directly on github.

**Comment by Ehyeh-Aries** [comment]
![pop1 1](https://github.com/uBlockOrigin/uAssets/assets/57068942/f03ddf92-1982-4962-8e9e-31d1c71a795e)

**Comment by Ehyeh-Aries** [comment]
![pop1](https://github.com/uBlockOrigin/uAssets/assets/57068942/aa1682ae-9d06-4edc-ba2f-d30c20f63543)

**Comment by Ehyeh-Aries** [comment]
those two images above are to be blocked, those are before the login to the account

**Comment by Ehyeh-Aries** [comment]
And now, this image below is inside the account, and this one needs to be keept

**Comment by Ehyeh-Aries** [comment]
![pop3 and 3 1](https://github.com/uBlockOrigin/uAssets/assets/57068942/9b3cb573-7400-4f3f-b919-2ec64dbe5845)

**Comment by stephenhawk8054** [comment]
Maybe this?

```adb
sicor.poderjudicialdf.gob.mx###popupBackground:has-text(MANUAL DE USUARIO)
```

**Comment by Ehyeh-Aries** [comment]
That was soooo coool!!! It worked perfect bud, thanks a lot, u r freaking
awesome

**Comment by stephenhawk8054** [comment]
You can use it as a custom filter.
