### ISSUE TITLE
datasciencelearner.com: nuisance

### ISSUE THREAD

**Issue by heartlog** [uBlockOrigin/uAssets#18814]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.datasciencelearner.com/module-json-has-no-attribute-loads-solved/`

### Category

nuisance

## annoyance wildcard 
> ##.widget-social-follower.w-sidebar.widget
> ##.essb-subscribe-from-design6.essb-subscribe-form-content
> ##.tipsy-loaded.tooltips-s.is-bg-icon.social-icons.footer-social

### Other extensions used

adguard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/76758776/3b9d534c-ffe1-4da4-ae80-579e4adf8f34)
![image](https://github.com/uBlockOrigin/uAssets/assets/76758776/88fbe488-cf66-4e79-898e-d5a41a29ec40)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 6d.23h.43m
Chromium: 114
filterset (summary):
 network: 167902
 cosmetic: 167483
 scriptlet: 35760
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gist.githubusercontent.com/heartlog/0350be1d917a99f3cd0ba308018380c3/raw/8ec3889cb1c3f3338ef69875feab9051aaf12ed0/adblock-ublock.txt: 88-88, never
  IND-0: 12818-0, 12h.34m
  adguard-cookies: 26175-29, 12h.34m
  adguard-generic: 72155-483, 12h.34m
  adguard-mobile: 8347-46, 12h.34m
  adguard-mobile-app-banners: 4390-8, 12h.34m
  adguard-other-annoyances: 13031-7, 12h.34m
  adguard-popup-overlays: 22833-70, 12h.34m
  adguard-social: 20803-880, 12h.34m
  adguard-spyware: 60323-1243, 12h.34m
  adguard-spyware-url: 1105-3, 12h.34m
  adguard-widgets: 2190-7, 12h.34m
 default:
  user-filters: 102-13, never
  easylist: 67755-1035, 13h
  easyprivacy: 33415-16634, 12h.34m
  plowe-0: 3739-1233, 12h.34m
  ublock-badware: 7465-365, 12h.34m
  ublock-filters: 33677-4141, 12h.34m
  ublock-privacy: 423-64, 12h.34m
  ublock-quick-fixes: 260-15, 12h.59m
  ublock-unbreak: 2059-134, 12h.34m
  urlhaus-1: 4816-2, 12h.34m
filterset (user): [array of 102 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11583 ms (selfie)
 maxAssetCacheWait: 944 ms
popupPanel:
 blocked: 27
 network:
  datasciencelearner.com: 10
  amazon-adsystem.com: 1
  connatix.com: 2
  doubleclick.net: 1
  ezodn.com: 3
  facebook.com: 1
  google.com: 1
  googletagmanager.com: 2
  linksynergy.com: 2
  pubmatic.com: 1
  quantserve.com: 1
  s-onetag.com: 1
  twitter.com: 1
 extended:
  ##a[href^="whatsapp://send"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[title="Share on LinkedIn"]
  ##[title="Share on LinkedIn"]
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://web.whatsapp.com/send?text="]
  ##a[href*="pinterest.com/pin/create/button"]
  ##a[href^="https://www.facebook.com/sharer.php"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
  ##a[onclick*="//www.facebook.com/"][onclick*="sharer.php"]
  ##a[title="Share on Facebook"]
  ##a[title="Share on Pinterest"]
  ##a[title="Share on Twitter"]
  ##[data-ez-name]
  ##[id^="google_ads_iframe"]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##a[href^="https://click.linksynergy.com/fs-bin/"] > img
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ezoic-adpicker-ad
  ##.ezoic-ad
  ##.adtester-container
  ##.essb_links
  ##.essb_share
  ##.share-icon
  ##.share-facebook
  ##.share-twitter
  ##.share-pinterest
  ##.share-linkedin
  ##.ezoic-ad-adaptive
  ##.widget-ad
  ##.advert-wrap
  ##.fb-like
  ###fb-root:not(body):not(html)
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  #@#[id^="div-gpt-ad"]
  #@#.ad-unit
  #@#.banner-ads
  #@#.banner_ads
  #@#.ad-zone
  #@#.ad-space
  ##html:style(overflow: auto !important; padding-right: 0 !import…
```
</details>

**Comment by heartlog** [comment]
@ gorhill  
You can choose which of these 3 wildcards to be added.

**Comment by okiehsch** [comment]
We don't fix social icons or subscription modals.
