### ISSUE TITLE
ekantipur.com: ads

### ISSUE THREAD

**Issue by cbdyu** [uBlockOrigin/uAssets#18819]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ekantipur.com/news/2023/07/04/168846882242095086.html`

### Category

ads

### Description

Only this page seems immune to ublock origin

### Other extensions used

Adguard adblocker and privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 21d.5h.32m
Firefox Mobile: 114
filterset (summary):
 network: 93678
 cosmetic: 29390
 scriptlet: 17802
 html: 976
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34828-304, 1d.23h.8m
  ublock-badware: 7674-0, 1d.23h.9m
  ublock-privacy: 460-1, 1d.58m
  ublock-unbreak: 2101-4, 3d.10h.15m
  ublock-quick-fixes: 260-0, 9h.17m
  adguard-mobile: 8321-121, 3d.5h.8m
  easylist: 67687-17442, 1d.6h.22m
  easyprivacy: 30616-622, 5d.23h.31m
  urlhaus-1: 4816-1, 5h.8m
  plowe-0: 3739-2, 6d.8h.39m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1322 ms (selfie)
 maxAssetCacheWait: 156 ms
popupPanel:
 blocked: 6
 network:
  google-analytics.com: 1
  googletagmanager.com: 2
  googletagservices.com: 2
  taboola.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by okiehsch** [comment]
`ekantipur.com##[src^="https://assets-cdn.kantipurdaily.com/uploads/source/ads/"]`

Not sure which list fixes such issues, maybe the indonesian one?
Or does  anybody know if  a nepali language list exists?

**Comment by stephenhawk8054** [comment]
@mediumkreation Sorry, can you take a look?

**Comment by ghajini** [comment]
fixed by **indian list**
@cbdyu , add **indian list** from ubo settings=> filter lists
