### ISSUE TITLE
iptvforever.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1881]
URL(s) where the issue occurs

`http://iptvforever.com/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`iptvforever.com###adBlock`

**Comment by SMed79** [comment]
Does this message limit the functionality of the site?
If not it should be added to the [**Adblock Warning Removal List**](https://adblockplus.org/subscriptions#type_anti-adblock) not to uBo filter list.

**Comment by mapx-** [comment]
`Adblock Warning Removal List` is not part of uBo setup, so it was added to the annoyances list

**Comment by SMed79** [comment]
Ok, thanks.

**Comment by Busraaa7666** [comment]
github.com/uBlockOrigin/uAssets/issues/1343
