### ISSUE TITLE
piekielniszefowie.pl: ads

### ISSUE THREAD

**Issue by ofrys** [uBlockOrigin/uAssets#18817]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://piekielniszefowie.pl/kontrowersje-dotyczace-bezpieczenstwa-w-firmie-oceangate-dawna-pracownica-wyjawia-jak-zostala-poproszona-o-zostanie-pilotem-lodzi-podwodnej`

### Category

ads

### Description

Loans Ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230704_200200](https://github.com/uBlockOrigin/uAssets/assets/138614553/6ac8a42d-bf21-4c67-bd09-d1e4f8e99f11)

![Screenshot_20230704_200040](https://github.com/uBlockOrigin/uAssets/assets/138614553/7db73003-2d85-45d8-b3b9-cb6a36ee7e69)

![Screenshot_20230704_201146](https://github.com/uBlockOrigin/uAssets/assets/138614553/8b9df6da-1ce7-41e9-aeac-63bcac204358)
</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 21d.10h.43m
Firefox Mobile: 114
filterset (summary):
 network: 99244
 cosmetic: 36831
 scriptlet: 18103
 html: 994
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 34898-345, now
  ublock-badware: 7476-1, now
  ublock-privacy: 464-1, now
  ublock-unbreak: 2107-6, now
  ublock-quick-fixes: 268-0, now
  easylist: 67822-17423, now
  easyprivacy: 33394-733, now
  urlhaus-1: 6356-3, now
  plowe-0: 3739-1, now
  POL-0: 7968-145, now
  POL-2: 1278-17, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8290 ms (selfie)
 maxAssetCacheWait: 212 ms
popupPanel:
 blocked: 8
 network:
  convertiser.com: 1
  googlesyndication.com: 6
  googletagmanager.com: 1
 extended:
  ##.td-a-rec
  ##ins.adsbygoogle
```
</details>

**Comment by ofrys** [comment]
Elements Added screenshots of items to block.

**Comment by okiehsch** [comment]
Sorry I missed that this is a mobile issue, I can't reproduce on a desktop.

**Comment by ofrys** [comment]
My mistake in the description of the problem.
I will add more details if needed

**Comment by stephenhawk8054** [comment]
Click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > Uncheck "Ignore generic cosmetic filters"

**Comment by ofrys** [comment]
> Click uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > Uncheck "Ignore generic cosmetic filters"

Yes, this was causing the problem.
 It's just going to happen again to others who use the plugin's default settings.
For me closed.

**Comment by ofrys** [comment]
> Click uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > Uncheck "Ignore generic cosmetic filters"

Yes, this was causing the problem.
 It's just going to happen again to others who use the plugin's default settings.
For me closed.
