### ISSUE TITLE
bestofcomicbooks.com, adf.ly: unneeded filters

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18818]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description
I made a report on the uBlock Origin subreddit about `bestofcomicbooks.com` originally 2 years ago:
`https://www.reddit.com/r/uBlockOrigin/comments/nz06ob/site_doesnt_load_images_without_disabling_ublock/`

These exception filters are no longer needed in uBlock unbreak. `Bestofcomicbooks.com` won't load, and `adf.ly` only redirects to Linkvertise.
`Adf.ly` should also be removed in Peter Lowe's list.

### URL(s) where the issue occurs.

`https://bestofcomicbooks.com`
`https://adf.ly`

### uBO version

v1.50.1b11

### Browser name and version

Firefox 115.0

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by okiehsch** [comment]
I don't see any exception filters for bestofcomicbooks in the unbreak list, I removed all other bestofcomicbooks filters.

@pgl fyi
> `Adf.ly` should also be removed in Peter Lowe's list.

**Comment by Sonic5435325** [comment]
In Unbreak, on the 19th/20th line (At the top of the filter list):
```
! override Peter Lowe's filter
||adf.ly^$badfilter
```

**Comment by Sonic5435325** [comment]
That was the filter, thank you a lot.
Will you also unadd the badfilter rule for adf.ly, or are you keeping it?

**Comment by okiehsch** [comment]
Right, the badfilter can go too.

**Comment by pgl** [comment]
The homepage might redirect, but are we sure none of the rest of the domain isn't still being used for tracking or ads?

**Comment by Sonic5435325** [comment]
@pgl Going on any adf.ly link (Example `http://adf.ly/wkwQd`), it still redirects to Linkvertise. I'd say it's safe enough to remove.

**Comment by pgl** [comment]
> @pgl Going on any adf.ly link (Example `http://adf.ly/wkwQd`), it still redirects to Linkvertise. I'd say it's safe enough to remove.

But it's still tracking the redirect, no?

**Comment by Sonic5435325** [comment]
I'm not sure about that one.

**Comment by okiehsch** [comment]
I assume all `adf.ly` links are old ones, so either way from our perspective the badfilter is not necessary anymore even if `pgl` decides to keep the filter.
