### ISSUE TITLE
onlinesaprevodom.net: detection

### ISSUE THREAD

**Issue by Fenivan** [uBlockOrigin/uAssets#18813]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://onlinesaprevodom.net/chicago-fire/`

### Category

detection

### Description

When trying to play episode of that series website embedded player writes "Owner of this video doesnot allow AdBlock. To watch video disable AdBlock and refresh page. Error. Init."

![opera_2023-07-04_17-59-39](https://github.com/uBlockOrigin/uAssets/assets/118318644/e0f5dfac-463c-4d64-b246-4bb44517b92d)

### Other extensions used

BitWarden, 7TV, Better TTV, Return YouTube Dislike, Sponsorblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.2h.50m
Chromium: 113
filterset (summary):
 network: 106618
 cosmetic: 184060
 scriptlet: 26398
 html: 0
listset (total-discarded, last-updated):
 added:
  HRV-0: 356-1, 17h.27m
  adguard-cookies: 26175-29, 17h.27m
  adguard-mobile-app-banners: 4390-8, 17h.27m
  adguard-other-annoyances: 13031-6, 17h.27m
  adguard-popup-overlays: 22833-58, 17h.27m
  adguard-social: 20803-877, 17h.27m
  adguard-widgets: 2190-4, 17h.27m
  easylist-annoyances: 3882-183, 17h.27m
  easylist-chat: 127-9, 17h.27m
  easylist-newsletters: 6225-351, 17h.27m
  easylist-notifications: 2639-1425, 17h.27m
  fanboy-cookiemonster: 47793-3783, 17h.27m
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 67751-106, 17h.28m
  easyprivacy: 33415-174, 17h.28m
  plowe-0: 3739-1068, 17h.27m
  ublock-badware: 7465-138, 17h.28m
  ublock-filters: 33672-554, 17h.28m
  ublock-privacy: 422-5, 17h.28m
  ublock-quick-fixes: 262-13, 4h.56m
  ublock-unbreak: 2058-39, 17h.28m
  urlhaus-1: 6335-1, 17h.27m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2992 ms (selfie)
 maxAssetCacheWait: 555 ms
popupPanel:
 blocked: 14
 network:
  onlinesaprevodom.net: 1
  addtoany.com: 1
  alleviatepracticableaddicted.com: 2
  chatbro.com: 1
  cloudflareinsights.com: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  highrevenuegate.com: 1
  hqq.to: 1
  marazma.com: 1
  profitablegatetocontent.com: 1
  testingmetriksbre.ru: 1
 extended:
  ##+js(abort-on-property-write, _pop)
  ##+js(set-constant, document.oncontextmenu, null)
  ##+js(set-constant, document.onkeydown, trueFunc)
  ##+js(no-setTimeout-if, debugger)
  ##+js(set-constant, console.clear, noopFunc)
  ##+js(abort-on-property-read, adBlockDetected)
  ##+js(abort-on-property-write, smrtSB)
  ##+js(abort-on-property-write, smrtSP)
  ##+js(popads-dummy)
  ##+js(set-constant, sadbl, false)
  ##+js(abort-on-property-read, arrvast)
  ##+js(abort-on-property-read, doSecondPop)
```
</details>

**Comment by okiehsch** [comment]
Already fixed, update your `uBO-filters` list.
