### ISSUE TITLE
[nsfw] suaurl.com: detection

### ISSUE THREAD

**Issue by h1m3r0s** [uBlockOrigin/uAssets#18828]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://suaurl.com/3ca357`

### Category

detection

### Description

Anti-block detection just hides captcha.

### Other extensions used

No other

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture5404-20230704](https://github.com/uBlockOrigin/uAssets/assets/88515387/b17ecf55-7b8e-4455-955e-e27e562d7d11)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.22h.14m
Chromium: 114
filterset (summary):
 network: 123374
 cosmetic: 172813
 scriptlet: 39308
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  adguard-cookies: 26188-29, 4m
  adguard-generic: 72213-451, 4m
  adguard-popup-overlays: 22853-53, 4m
  easylist-newsletters: 6235-349, 4m
  easylist-notifications: 2641-119, 4m
  fanboy-cookiemonster: 47806-3779, 4m
  spa-0: 3724-36, 4m
  ublock-annoyances: 5300-212, 4m
 default:
  user-filters: 0-0, never
  easylist: 67836-892, now
  easyprivacy: 33398-261, now
  plowe-0: 3739-1080, now
  spa-1: 5327-223, now
  ublock-badware: 7480-364, now
  ublock-filters: 33752-3834, now
  ublock-privacy: 423-3, now
  ublock-quick-fixes: 268-16, now
  ublock-unbreak: 2064-98, now
  urlhaus-1: 6372-2, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 733 ms (selfie)
 maxAssetCacheWait: 137 ms
popupPanel:
 blocked: 15
 network:
  a-ads.com: 1
  cleverwebserver.com: 2
  googletagmanager.com: 2
  nobeta.com.br: 1
  optad360.io: 2
  quantcast.com: 1
  suaads.com: 1
  themoneytizer.com: 4
  zunsoach.com: 1
 extended:
  ##div[id][onclick$="();"][style^="position: fixed; z-index:"]
  ##+js(set-constant, cdo, 1)
  ##+js(no-setTimeout-if, Por favor, desative)
  ##+js(no-setInterval-if, /adblock|Por favor, desative|adsbygoogl…
  ##+js(set-constant, acdl, undefined)
  ##+js(no-setTimeout-if, window.location.href)
  ##+js(abort-current-script, $, notficationAd)
  ##+js(abort-current-script, open, document.getElementById)
  ##+js(remove-node-text, script, /window\.open|window\.location\.…
  ##+js(abort-on-property-read, document.oncontextmenu)
  ##+js(abort-on-property-read, shortcut)
```
</details>

**Comment by okiehsch** [comment]
Caused by filters in Adguard Spanish.
````
@@||suaads.com/peel1-ad-300x250.js$script,domain=suaurl.com
suaurl.com#@#+js(set, cdo, 1)
````
fixes the issue on my end.
@Yuki2718

**Comment by ghajini** [comment]
test these filters
```
||get.optad360.io^$xhr,domain=suaurl.com,redirect=nooptext
suaurl.com##+js(nowoif)
suaurl.com##.mt-2.mb-5.text-center
suaurl.com##.mt-5.text-center
```

**Comment by ghajini** [comment]
anybody confirms?

**Comment by okiehsch** [comment]
@ghajini your filters work fine on my end.

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/a9aff638eed684d9246e66b562e72a0439ef5c23
