### ISSUE TITLE
motorsport.com: detection

### ISSUE THREAD

**Issue by pubct** [uBlockOrigin/uAssets#18825]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Yep. It's this site again. The red box.
Some testing in incognito indicates the red box appears after 4/5 articles. I have been able to consistently reproduce it for several times.
To reproduce, go to the provided link below, click next article at the top. Repeat going to next article for 4/5 times.

### URL(s) where the issue occurs.

`https://www.motorsport.com/f1/news/2022-car-development-banned-2020/4775364/`

### uBO version

1.50.0

### Browser name and version

Chrome 114.0.5735.199

### Settings

.

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

**Comment by pubct** [comment]
Force updated and tested again. It's still detected. At the 4th article.

**Comment by stephenhawk8054** [comment]
Can you go to the page that has issue > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by pubct** [comment]
```
uBlock Origin 1.50.0:
 since: 21d.16h.13m
Chromium: 114
filterset (summary):
 network: 96487
 cosmetic: 39307
 scriptlet: 17884
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 67836-10, 10m
  easyprivacy: 33398-62, 10m
  plowe-0: 3739-1068, 10m
  ublock-badware: 7480-138, 10m
  ublock-filters: 33751-147, 10m
  ublock-privacy: 423-3, 10m
  ublock-quick-fixes: 268-16, 10m
  ublock-unbreak: 2064-37, 10m
  urlhaus-1: 6356-3, 10m
filterset (user): [array of 141 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 230 ms (selfie)
 maxAssetCacheWait: 120 ms
popupPanel:
 blocked: 9
 network:
  motorsport.com: 5
  chartbeat.com: 1
  cxense.com: 1
  ntv.io: 1
  outbrain.com: 1
 extended:
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
  ##+js(addEventListener-defuser, gtmloaderror)
  ##+js(noeval-if, interactionCount)
  ##+js(abort-current-script, vardom)
  ##+js(no-setTimeout-if, adb)
```

**Comment by pubct** [comment]
Detection
```
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98400
 cosmetic: 39302
 scriptlet: 18313
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 69615-10, now
  easyprivacy: 33309-63, now
  plowe-0: 3726-1065, now
  ublock-badware: 7777-146, now
  ublock-filters: 34340-122, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 226-44, now
  ublock-unbreak: 2116-32, now
  urlhaus-1: 6007-0, now
filterset (user): [array of 143 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 613 ms
 maxAssetCacheWait: 272 ms
popupPanel:
 blocked: 9
 network:
  motorsport.com: 5
  chartbeat.com: 1
  cxense.com: 1
  ntv.io: 1
  outbrain.com: 1
 extended:
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
  ##+js(addEventListener-defuser, gtmloaderror)
  ##+js(noeval-if, interactionCount)
  ##+js(abort-current-script, vardom)
  ##+js(cookie-remover, 45grw1567)
```

**Comment by stephenhawk8054** [comment]
@pubct Can you give the link that has anti adblock?

**Comment by pubct** [comment]
The link in OP can be used. Just click for next article at the top until you reach the 4th article, the red box blocking the article text will appear.

**Comment by ghajini** [comment]
i can reproduce, just navigate through various links 5-6 times

`motorsport.com##+js(cookie-remover, 4d8L2108)`

**Comment by ghajini** [comment]
yes

**Comment by pubct** [comment]
Detection.
The same link in OP can be used.
Same reproduction step as mentioned in OP, except need to scroll to the end of article to navigate to the next article.
```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 105085
 cosmetic: 43482
 scriptlet: 18880
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 75220-16, 1m
  easyprivacy: 32859-64, 1m
  plowe-0: 3723-1074, 1m
  ublock-badware: 7443-135, 1m
  ublock-filters: 35254-151, 1m
  ublock-privacy: 665-5, 1m
  ublock-quick-fixes: 164-99, 1m
  ublock-unbreak: 2148-32, 1m
  urlhaus-1: 11695-0, 1m
filterset (user): [array of 146 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 465 ms
 maxAssetCacheWait: 215 ms
popupPanel:
 blocked: 9
 network:
  motorsport.com: 5
  chartbeat.com: 1
  cxense.com: 1
  ntv.io: 1
  outbrain.com: 1
 extended:
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
  ##+js(addEventListener-defuser, gtmloaderror)
  ##+js(noeval-if, interactionCount)
  ##+js(abort-current-script, vardom)
  ##+js(cookie-remover, 45grw1567)
  ##+js(set-cookie, 4d8L2108, 1, , reload, 1)
```

**Comment by pubct** [comment]
Hi. It's detection again.
Same link in OP can be used. Same reproduction steps. Thank you.
<details>
<summary>Feb 2nd troubleshooting information</summary>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 116455
 cosmetic: 45401
 scriptlet: 20288
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 80194-14, 1m
  easyprivacy: 43618-48, 1m
  plowe-0: 3784-1178, 1m
  ublock-badware: 7804-136, 1m
  ublock-filters: 36928-210, 1m
  ublock-privacy: 995-6, 1m
  ublock-quick-fixes: 152-8, 1m
  ublock-unbreak: 2206-31, 1m
  urlhaus-1: 8240-0, 1m
filterset (user): [array of 146 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 473 ms
 maxAssetCacheWait: 236 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 6
 network:
  motorsport.com: 2
  cxense.com: 1
  googletagmanager.com: 1
  ntv.io: 1
  taboola.com: 1
 extended:
  ###taboola-below-article-thumbnails
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
  ##+js(addEventListener-defuser, gtmloaderror)
  ##+js(noeval-if, interactionCount)
  ##+js(abort-current-script, vardom)
  ##+js(remove-cookie, 45grw1567)
  ##+js(set-cookie, 4d8L2108, 1, , reload, 1)
  ##+js(abort-current-script, document.querySelector, adblock)
```
</details>

**Comment by xlollomanx** [comment]
Not sure if i should post here or open a new issue, but I noticed that probably recent filters update broke something in the full screen image visualizer. 
Test link: [https://it.motorsport.com/f1/news/gallery-f1-mclaren-mcl38-la-nuova-arma-di-norris-e-piastri/10575657/#gal-1932-mclaren-mcl38-dettaglio-tecnico-68284307](https://it.motorsport.com/f1/news/gallery-f1-mclaren-mcl38-la-nuova-arma-di-norris-e-piastri/10575657/#gal-1932-mclaren-mcl38-dettaglio-tecnico-68284307)
As like the image below if u open the link above and click on the image it should open a full screen(almost) image, but right now it shows just a black screen

<details>
<summary>Main page</summary>
<br>

![image](https://github.com/uBlockOrigin/uAssets/assets/6764804/2cc06bba-6e88-4213-8a21-495ab9b5e154)
</details>



This is how it looks right now. I tried to update the filters and using a base ubo installation (no custom filters).
<details>
<summary>Ubo active:</summary>
 <br>

![image](https://github.com/uBlockOrigin/uAssets/assets/6764804/226c456f-bf7e-4f15-aa12-6df1c77a60c0)

</details>
<details>
<summary>Ubo disabled:</summary>

<br>

![image](https://github.com/uBlockOrigin/uAssets/assets/6764804/f6d59dea-63f1-4bab-a42c-fa73269e6206)

</details>

**Comment by stephenhawk8054** [comment]
Just continue here

**Comment by stephenhawk8054** [comment]
@ItsProfessional I think `autosport.com,motorsport.com##+js(set, DOMTokenList.prototype.contains, trueFunc)` is causing issue

**Comment by xlollomanx** [comment]
seems working fine now. thank you!

**Comment by ItsProfessional** [comment]
@stephenhawk8054 can you reproduce? https://www.reddit.com/r/uBlockOrigin/comments/1aw7voq/motorsportcom_detects_ublock_after_website_update/

**Comment by stephenhawk8054** [comment]
@ItsProfessional I couldn't. Tried refreshing or opening multiple articles but no detection for me. That message looks like from some other tools blocking `mstm.motorsport.com`.

**Comment by pubct** [comment]
Allow me to chime in. I seem to be able to reproduce it.
Same link in OP can be used. Below are the reproduction steps.

1. Scroll down to the lower half/to the bottom of the article. (Won't trigger if staying stationary at the top)

1. Wait for it to load some additional things. (You can see it in action in Logger)

1. Refresh.

**Comment by stephenhawk8054** [comment]
I can only reproduce on chromium.

@pubct Can you reproduce it in Firefox?

**Comment by pubct** [comment]
Can confirm I don't reproduce it in FF. It was on Chrome.

And can confirm manually adding the update fixes it.

**Comment by ItsProfessional** [comment]
Why did you add it manually? Just update the "uBlock filters - Ads"

**Comment by pubct** [comment]
I was just testing it before uBO release the update, as I understand it's not immediately pushed out.

**Comment by ItsProfessional** [comment]
It's pushed out after about 10 minutes.

**Comment by D4niloMR** [comment]
I can reproduce anti-adb on `https://motorsport.uol.com.br/fia-f2/news/f2-maloney-vence-corrida-1-no-bahrein-bortoleto-brilha-no-fim-e-termina-em-6%C2%BA/10581841/`

Both filter works:

```adb
||us-east-1-cdn-ui-k8s.motorsport.com/629/design/dist/js/3619_fa432529226b845b1b7c.js
motorsport.uol.com.br##+js(trusted-replace-argument, document.querySelector, 0, noopFunc, condition, adblock)
```
