### ISSUE TITLE
telegraph.co.uk [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1882]
URL(s) where the issue occurs

`https://www.telegraph.co.uk/news/2018/04/03/teenage-girl-shot-dead-london/`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by gorhill** [comment]
Can't reproduce. If I toggle off cosmetic filtering though, the adblock-wall appears.

**Comment by mapx-** [comment]
it seems already fixed in ublock filters, cannot reproduce

**Comment by KiLL4FuNK** [comment]
how weird now do not show anything can close the topic
