### ISSUE TITLE
cc.com: detection

### ISSUE THREAD

**Issue by loganrosen** [uBlockOrigin/uAssets#18824]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cc.com/episodes/67u4t7/awkwafina-is-nora-from-queens-bad-grandma-season-3-ep-5`

### Category

detection

### Description

After signing in with a TV provider, it displays a message detecting the ad blocker and requiring it to be turned off in order to view content.

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1709" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/512317/e54b2697-e8be-4614-bbe1-d640a36288ad">
</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.20h.56m
Firefox: 114
filterset (summary):
 network: 94879
 cosmetic: 39270
 scriptlet: 17753
 html: 978
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34555-165, 2d.16h.4m
  ublock-badware: 7680-1, 2d.15h.32m
  ublock-privacy: 464-0, 18h.1m
  ublock-unbreak: 2104-0, 2d.15h.31m
  ublock-quick-fixes: 261-3, 18h
  easylist: 67506-587, 1d.18h.10m
  easyprivacy: 33436-764, 1d.18h.9m
  urlhaus-1: 4816-0, 17h.59m
  plowe-0: 3738-2, 7d.20h.56m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 280 ms (selfie)
 maxAssetCacheWait: 76 ms
popupPanel:
 blocked: 37
 network:
  amazon-adsystem.com: 1
  audioeye.com: 1
  cbsaavideo.com: 4
  cbsi.com: 2
  cbsivideo.com: 16
  confiant-integrations.net: 1
  demdex.net: 1
  doubleclick.net: 1
  getpublica.com: 1
  imasdk.googleapis.com: 1
  moatads.com: 1
  mtvnservices.com: 1
  newrelic.com: 1
  ns1p.net: 3
  quizzicalpartner.com: 1
  stickyadstv.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect-rule=google-ima.js,domain=cc.com
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Go back to the website > Press `Ctrl + Shift + R` (`Cmd + Shift + R` on Mac) to reload the page and test again.

**Comment by loganrosen** [comment]
Unfortunately it still happens with that filter added.

**Comment by loganrosen** [comment]
This rule appears to fix it:

```adblock
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$script,domain=cc.com
```

I'm not sure if it's the "right" way to fix it, though.

**Comment by stephenhawk8054** [comment]
So in general, does this work? (remove other custom filters)

```adb
||imasdk.googleapis.com^$redirect-rule=google-ima.js,domain=cc.com
```

**Comment by loganrosen** [comment]
Yep, it does!

**Comment by stephenhawk8054** [comment]
Ah ok, I didn't realize there was a similar issue: https://github.com/uBlockOrigin/uAssets/issues/18360
