### ISSUE TITLE
vod.pl: detection

### ISSUE THREAD

**Issue by MatrajM** [uBlockOrigin/uAssets#18823]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vod.pl/programy-online,2/zony-miami-odcinki,5012639`

### Category

detection

### Description

Detects uBlock and makes player unavailable, Adblock plus still shows this anti adblock popup but lets player play behind it, which is not the case for uBlock

### Other extensions used

Adblock plus (still is detected but allowas player interaction)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/40493741/eab50618-0938-4f41-9b08-ada13954ed6b)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 21d.2h.19m
Firefox: 114
filterset (summary):
 network: 97897
 cosmetic: 46840
 scriptlet: 18054
 html: 993
listset (total-discarded, last-updated):
 added:
  https://gitloaf.com/cdn/olegwukr/polish-privacy-filters/master/anti-adblock-suplement.txt: 197-3, 6m
  POL-0: 7968-27, 6m
  POL-2: 1278-206, 6m
 default:
  user-filters: 17-3, never
  ublock-filters: 34625-93, 6m
  ublock-badware: 7482-0, 6m
  ublock-privacy: 464-0, 6m
  ublock-unbreak: 2101-0, 6m
  easylist: 67835-674, 6m
  easyprivacy: 33397-768, 6m
  plowe-0: 3739-3, 6m
  urlhaus-1: 6356-3, 6m
  ublock-quick-fixes: 268-5, 6m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 718 ms (selfie)
 maxAssetCacheWait: 428 ms
popupPanel:
 blocked: 27
 network:
  adocean.pl: 5
  browser-intake-datadoghq.eu: 2
  cdntvn.pl: 3
  doubleclick.net: 1
  gemius.pl: 10
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  litix.io: 1
  newrelic.com: 1
  redcdn.pl: 1
 extended:
  ##.reklama-top
  ##.adv_container
  #@#.advert
  #@#.ad
  #@#.adsense
  #@#.linkSponsorowany
  #@#.ads
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
vod.pl##+js(set, Object.prototype.adblockDetector, noopFunc)
```

@MajkiIT Sorry can you take a look?

**Comment by krystian3w** [comment]
More @olegwukr

**Comment by ghajini** [comment]
confirm its fixed?

**Comment by krystian3w** [comment]
But not in regional supplements.

https://github.com/olegwukr/polish-privacy-filters/commits/master
