### ISSUE TITLE
merriam-webster.com: nuisance

### ISSUE THREAD

**Issue by pubct** [uBlockOrigin/uAssets#18820]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There's a black bar remnant at the top.
The black bar originally has ad which is successfully blocked by uBO.

### URL(s) where the issue occurs.

`https://www.merriam-webster.com/games/quordle`

### uBO version

1.50.0

### Browser name and version

Chrome 114.0.5735.199

### Settings

.

### Notes

Is nuisance the correct category?

**Comment by okiehsch** [comment]
@ryanbr
`merriam-webster.com##.max-h-\[94px\].min-h-\[94px\].max-w-\[730px\]`

**Comment by pubct** [comment]
Sorry for bothering a closed PR, but there seems to be no fix added into EasyList yet?

**Comment by okiehsch** [comment]
I notified the maintainer.
You can add 
`merriam-webster.com##.max-h-\[94px\].min-h-\[94px\].max-w-\[730px\]`
to your filter list or wait for it to be added to EasyList.

**Comment by pubct** [comment]
Today/recently the black bar remnant at the top has reappeared again. Thank you.

**Comment by mapx-** [comment]
`merriam-webster.com##.animate-banner:upward(1)`

or

`merriam-webster.com##.justify-center:has(.animate-banner)`
