### ISSUE TITLE
momondo.no: ads

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18832]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.momondo.no/flight-search/OSL-BKK/2023-11-16?sort=bestflight_a`

### Category

ads

### Description

ads

### Other extensions used

none

### Screenshot(s)

![Screenshot 2023-07-05 090634](https://github.com/uBlockOrigin/uAssets/assets/19490515/cf021aac-c9b6-4227-9b37-018aee444a62)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 21d.6h.30m
Firefox: 115
filterset (summary):
 network: 245311
 cosmetic: 202387
 scriptlet: 38768
 html: 1158
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2230-0, 19h.26m
  adguard-generic: 72192-5416, 19h.35m
  adguard-spyware-url: 1109-147, 19h.33m
  block-lan: 47-0, 19h.32m
  curben-phishing: 119507-37, 19h.29m
  curben-pup: 199-0, 19h.28m
  adguard-social: 20805-685, 19h.27m
  fanboy-thirdparty_social: 68-0, 19h.26m
  fanboy-cookiemonster: 47799-3819, 19h.26m
  fanboy-social: 16085-19, 19h.26m
  ublock-annoyances: 5266-13, 19h.26m
  NOR-0: 3218-11, 19h.26m
  [5 lists not shown]: [too many]
 default:
  user-filters: 14-0, never
  ublock-filters: 34551-137, 19h.40m
  ublock-badware: 7467-3, 19h.39m
  ublock-privacy: 463-2, 19h.38m
  ublock-unbreak: 2096-4, 19h.37m
  ublock-quick-fixes: 268-0, 6h.45m
  easylist: 67851-794, 19h.34m
  easyprivacy: 33437-807, 19h.31m
  urlhaus-1: 4816-0, 19h.30m
  plowe-0: 3739-1, 19h.26m
filterset (user): [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4544 ms (selfie)
 maxAssetCacheWait: 476 ms
popupPanel:
 blocked: 10
 network:
  momondo.no: 1
  airfrance.fr: 1
  doubleclick.net: 4
  google-analytics.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  usabilla.com: 1
 extended:
  ##div[data-resultid$="-sponsored"]
  ##.rightAd
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by okiehsch** [comment]
@DandelionSprout 
`momondo.no##.yuAt-pres-rounded:has-text(Annonse)`
workd for me.

**Comment by DandelionSprout** [comment]
Momondo is a multi-country site with around 30 country versions, and must be fixed by international lists.

**Comment by okiehsch** [comment]
@DandelionSprout 
Thx.
