### ISSUE TITLE
ikandy.fun: detection

### ISSUE THREAD

**Issue by AnnAngela** [uBlockOrigin/uAssets#18833]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There is a `iframe` linked to `https://api.guailie.com/x/player/index.php?url=https://v.qq.com/x/cover/mzc002004hgpdzm/n0045lqgzig.html` to show the player.

[The content of the `api.guailie.com` link](https://github.com/uBlockOrigin/uAssets/files/11955120/api.guailie.com.zip) needs to be fetched by script, the server blocks any direct request.

The player in this link using a function named `killAdKiller` in an inline script to detect the ublock and destory the player if it detected ublock, and a script `https://api.guailie.com/x/statics/js/fuck-debugger.js` to prevent debugging via devtool.

### URL(s) where the issue occurs.

`https://www.ikandy.fun/vodplay/154204-1-1/`

### uBO version

1.50.0

### Browser name and version

Microsoft Edge 114.0.1823.67 (Stable) (x64)

### Settings

_None_

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
guailie.com##+js(rmnt, script, killAdKiller)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Go back to the website > Press `Ctrl + Shift + R` (`Cmd + Shift + R` on Mac) to reload the page and test again.

**Comment by stephenhawk8054** [comment]
@Yuki2718 I guess it's for Adguard Chinese list? Tho I don't know how to translate it to Adguard's syntax

**Comment by Yuki2718** [comment]
`api.guailie.com##+js(set, killAdKiller, noopFunc)` is working fine.
