### ISSUE TITLE
iotex.io: nuisance

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#18831]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://iotex.io/`

### Category

nuisance

### Description

I have EasyList - newsletters enabled, but still show newsletter pop-up when scrolling down on this website.

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19490515/452aff0f-a1a4-4052-8694-56792fcdc231)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 21d.6h.5m
Firefox: 115
filterset (summary):
 network: 245311
 cosmetic: 202387
 scriptlet: 38768
 html: 1158
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2230-0, 19h.1m
  adguard-generic: 72192-5416, 19h.10m
  adguard-spyware-url: 1109-147, 19h.8m
  block-lan: 47-0, 19h.7m
  curben-phishing: 119507-37, 19h.4m
  curben-pup: 199-0, 19h.3m
  adguard-social: 20805-685, 19h.2m
  fanboy-thirdparty_social: 68-0, 19h.1m
  fanboy-cookiemonster: 47799-3819, 19h.1m
  fanboy-social: 16085-19, 19h.1m
  ublock-annoyances: 5266-13, 19h.1m
  NOR-0: 3218-11, 19h.1m
  [5 lists not shown]: [too many]
 default:
  user-filters: 14-0, never
  ublock-filters: 34551-137, 19h.15m
  ublock-badware: 7467-3, 19h.14m
  ublock-privacy: 463-2, 19h.13m
  ublock-unbreak: 2096-4, 19h.12m
  ublock-quick-fixes: 268-0, 6h.20m
  easylist: 67851-794, 19h.9m
  easyprivacy: 33437-807, 19h.6m
  urlhaus-1: 4816-0, 19h.5m
  plowe-0: 3739-1, 19h.1m
filterset (user): [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4544 ms (selfie)
 maxAssetCacheWait: 476 ms
popupPanel:
 blocked: 3
 network:
  iotex.io: 1
  googletagmanager.com: 1
  hotjar.com: 1
```
</details>

**Comment by okiehsch** [comment]
> I have EasyList - newsletters enabled

Open an issue at https://github.com/easylist/easylist/issues
