### ISSUE TITLE
babbel domains: breakage

### ISSUE THREAD

**Issue by atrzaska** [uBlockOrigin/uAssets#18834]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When uBlock is active, all of the frontend apps from babbel.com and other main domains are unable to communicate with Babbel's central API domain api.babbel.io when using sendBeacon as request method, which is causing many issues with main website/product features.

The point of the current sendBeacon calling system is to allow same domain sendBeacon requests, while blocking requests to third party domains (assuming the latter to be sharing data to 3rd parties, which is understandable). Due to the infrastructure of Babbel, calls are done between domains all self-owned (aka 1st party sendBeacon calls). So could an exception be done, so that it is no more mistakenly preventing any adblocker user to use properly web app and features?

Previously a similar update was applied to fix my.babbel.com domain (aka my.babbel.com whitelisted to call api.babbel.io). https://github.com/uBlockOrigin/uAssets/issues/11649 
 
This is not enough as other pages are also using sendBeacon for core features (e.g. saving user preferences and progress, and performance monitoring to ensure quick page load, track error pages, and more basic functions). In the screenshot you can see calls being blocked to the API domain from one of our language specific domains uk.babbel.com.

Could you please allow any of the following domains (also any subdomains) to call any url from api.babbel.io for ping requests?

babbel.com
babbelforbusiness.com
babbelfuerunternehmen.de
babbel-giftshop.com

### URL(s) where the issue occurs.

`https://uk.babbel.com/`

### Screenshot(s)

<img width="1599" alt="Screenshot 2023-07-05 at 10 22 20" src="https://github.com/uBlockOrigin/uAssets/assets/2529820/bb9a3b8b-47a3-4e32-90cf-8a04af088377">

### uBO version

1.50.0

### Browser name and version

Google Chrome Version 108.0.5359.124 (Official Build) (arm64)

### Settings

default settings

**Comment by ryanbr** [comment]
Given the babbel.com is the user front end, we don't need to excempt "all the babbel domains". Excessive request. Made a fix to apply to the main domain.
