### ISSUE TITLE
rfi.fr: nuisance

### ISSUE THREAD

**Issue by hspzfsc** [uBlockOrigin/uAssets#18842]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description

Adguard Annoyances whitlisted a domain, making the cookie notice on rfi.fr unblocked.

### URL(s) where the issue occurs.

`https://www.rfi.fr/tw/%E4%B8%AD%E5%9C%8B/20230421-100-%E5%85%A5%E7%BD%AA%E7%8E%87%E4%B8%8B%E6%93%AC%E4%BF%AE%E4%BE%8B-%E5%AE%B9%E6%B8%AF%E5%BA%9C%E5%B0%B1%E5%9C%8B%E5%AE%89%E8%84%AB%E7%BD%AA%E6%A1%88%E4%B8%8A%E8%A8%B4-%E8%A9%95%E8%AB%96%E6%8C%87%E6%88%96%E5%B0%87%E8%A7%B8%E5%8F%8A-%E5%AF%A7%E7%B8%B1%E8%8E%AB%E6%9E%89-%E5%8E%9F%E5%89%87`

### Screenshot(s)

![Screenshot_20230705-222550_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/138294540/a29c69f8-e879-4aa4-a494-b1d231936df5)
![Screenshot_20230705-223014_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/138294540/06531941-a924-4ae5-9938-b7c36da320d0)
![Screenshot_20230705-223047_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/138294540/957df74e-e9d1-49b8-b266-b872a5fd18f1)
![Screenshot_20230705-222828_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/138294540/1640d8e3-f511-4f64-b1ac-0311480dc501)

### uBO version

uBlock Origin 1.50.0

### Browser name and version

Kiwi Browser 112.0.5615.137

### Settings

Enabled AdGuard – Annoyances and EasyList – Annoyances

**Comment by stephenhawk8054** [comment]
The cookie notice is required, or twitter embed will break in this page: `https://www.rfi.fr/fr/europe/20230623-l-ue-exige-que-twitter-renforce-ses-moyens-afin-de-respecter-sa-nouvelle-r%C3%A9gulation-du-web`

**Comment by hspzfsc** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/155530 Adguard say they used a way not supported by uBo to block the notice. Could uBo use their own way to remove it too?

**Comment by stephenhawk8054** [comment]
This could work, but only dev build at the moment. You can install dev build in another browser profile and test these:

```adb
rfi.fr##+js(trusted-set-cookie, euconsent-v2, CPubvkAPubvkAAHABBENDMCgAM_AAE7AAAqII7FF_X7eTSPheWp_Y_tUOY0ewVQ_4-AhBgCJA4gBCRpAsJQEkGAIIEDAIAAKAAYEIGJBAAElAAFABEAAYIEBACHMAAAAIRAAIDKAAAAAAgBACABYEwAAAAIAgEBUABUAiAIAABogwMBAEAAgBEAAAAogAIBBAAAAACAAwAAQAAAIAggAAAAAAAAEAAAEAAAAEAAABJKADAAEExQ0AGAAIJiioAMAAQTFKQAYAAgmKOgAwABBMUhABgACCYoSADAAEExREAGAAIJijIAMAAQTFAAA.efgACdgAAAAA, 1year, , reload, 1)
rfi.fr##+js(trusted-set-local-storage-item, didomi_token, eyJ1c2VyX2lkIjoiIiwiY3JlYXRlZCI6IjIwMjMtMDctMDVUMTY6MTI6MzcuMjA5WiIsInVwZGF0ZWQiOiIyMDIzLTA3LTA1VDE2OjEyOjM3LjIwOVoiLCJ2ZW5kb3JzIjp7ImVuYWJsZWQiOlsidHdpdHRlciIsImdvb2dsZSIsImM6YmF0Y2giLCJjOm5vbmxpIiwiYzp0eXBlZm9ybSJdfSwidmVyc2lvbiI6MiwiYWMiOiIifQ==)
```

**Comment by hspzfsc** [comment]
It work. 
![20230706_102223](https://github.com/uBlockOrigin/uAssets/assets/138294540/6670fbad-f608-4568-ab94-c19ca4abbca3)
