### ISSUE TITLE
empire-streaming.app: ads

### ISSUE THREAD

**Issue by Kris-Tofe** [uBlockOrigin/uAssets#18840]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://empire-streaming.app/film/Les-Chevaliers-du-Zodiaque-en-streaming-hd/f962336458815a728447975942779a68`

### Category

ads

### Description

ads are filtered but i must click several times before watch films
i think it's in the script of this website

### Other extensions used

none
i've tried several ad blocker but the same results

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 5d.16h.21m
Chromium: 114
filterset (summary):
 network: 170062
 cosmetic: 0
 scriptlet: 22163
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-spyware: 60328-446, 3m
  adguard-spyware-url: 1114-5, 3m
  curben-pup: 199-1, 3m
  dpollock-0: 11524-188, 21m
  ublock-annoyances: 5304-1464, 21m
 default:
  user-filters: 2-0, never
  FRA-0: 28354-9049, 4m
  easylist: 67864-29535, 3m
  easyprivacy: 33415-16779, 3m
  plowe-0: 3739-1515, 3m
  ublock-badware: 7480-831, 3m
  ublock-filters: 33804-9503, 2m
  ublock-privacy: 423-75, 2m
  ublock-quick-fixes: 267-117, 2m
  ublock-unbreak: 2064-360, 2m
  urlhaus-1: 6431-2, 2m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 parseAllABPHideFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 628 ms (selfie)
 maxAssetCacheWait: 295 ms
popupPanel:
 blocked: 6
 no-remote-fonts: true
 network:
  empire-streaming.app: 3
  cloudflareinsights.com: 2
  thaudray.com: 1
 extended:
  ##[src="/iframe_window"]
  ##+js(no-xhr-if, pagead2.googlesyndication.com)
  ##+js(set-constant, empire.data, []):matches-path(/iframe_ad)
  ##+js(no-xhr-if, googlesyndication.com)
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 I see this filter in Adguard French, looks like due to translating from Adguard syntax to uBO?

```adb
empire-streaming.*##+js(set-constant, empire.data, []):matches-path(/iframe_ad)
```

**Comment by stephenhawk8054** [comment]
Ah I see

**Comment by Yuki2718** [comment]
Maybe add temporal fix if @gorhill is going to fix? Or should it be AG side?

**Comment by stephenhawk8054** [comment]
The filter is to remove popup links in `empire` Object. However, that object is different when loading normal URL (`https://empire-streaming.app/film/Les-Chevaliers-du-Zodiaque-en-streaming-hd/f962336458815a728447975942779a68`) and the embedded iframe (`https://empire-streaming.app/iframe_ad/ad_mov`).

If we use `empire-streaming.*##+js(set-constant, empire.data, [])` then the main page will break.

I tried

```adb
empire-streaming.*##+js(rpnt, script, /data: \[.*\]/, data:[], condition, ads_num, log, 1)
```

but not successful in Firefox (maybe due to cache?)

**Comment by Yuki2718** [comment]
How about maybe non-scriptlet fix? I guess `||empire-streaming.app/iframe_window` can be added to French list, does this cause trouble?

**Comment by stephenhawk8054** [comment]
> How about non-scriptlet fix? I guess `||empire-streaming.app/iframe_window` can be added to French list, does this cause trouble?

Nope, that does not work, the affected iframe is `https://empire-streaming.app/iframe_ad/ad_mov`

---

Steps to reproduce:

1. Load `https://empire-streaming.app/film/Les-Chevaliers-du-Zodiaque-en-streaming-hd/f962336458815a728447975942779a68`
2. Click play
3. Click on option `Vostfr` with Ad at the right
4. Click on `VOSTFR`
5. Click on `E` logo
6. Click on `Continue` will trigger the popup

**Comment by Yuki2718** [comment]
Yeah, I misunderstood the problem and enabled a wrong list.

**Comment by stephenhawk8054** [comment]
The `empire.data` object has about 5 popup links, in which users should click on that button 5 times (with 5 popups, which is OP's original issue).

**Comment by stephenhawk8054** [comment]
> On the other hand, there is another problem that has emerged. If I choose server "E", the movie does not start

Does the movie start if you turn off uBO?

**Comment by Kris-Tofe** [comment]
> Does the movie start if you turn off uBO?

yes, it does.

**Comment by stephenhawk8054** [comment]
On my end, the video does not play even when turning off uBO. It just shows `No route` at the video player. So I don't know how to investigate. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/ffa7d398-c706-4448-af68-9a0f84926f28

**Comment by stephenhawk8054** [comment]
Ok, I can reproduce with Chromium.

**Comment by Yuki2718** [comment]
> In dev build we can use
> 
> ```
> empire-streaming.*##+js(trusted-set-local-storage-item, donationtime, $currentDate$)
> ```

Yeah, I've just found that and about to post.

**Comment by Kris-Tofe** [comment]
ok guys, all is good now. you've done a good Job ;-)
the site **www.empire-streaming.app** is good. (tested on EDGE (chromium) et w11)

Just for your information : 
there is a 2nd website (backup ?) with a little bit different domain name : **www.empire-stream.net**
 you can see it here : https://empire-streaming-officiel.org/
I don't use this snd website but maybe some people use it.

Thanks again for your great job !

**Comment by stephenhawk8054** [comment]
Ok, I guess I can remove these in our list?

```adb
empire-stream.*###msg_ads
empire-stream.*##body:style(overflow: auto !important;)
```

**Comment by Yuki2718** [comment]
@AdamWr Can you check https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2392 ? I guess probably apps won't be affected so the rule can be added, but want confirmation.

**Comment by AdamWr** [comment]
As far as I understand, this rule is not applied, because `.cta-ap` element is in iframe `e-player-stream.app`, not `empire-streaming.app`.
This one:
```adblock
e-player-stream.app##.cta-ap
```
or maybe:
```adblock
e-player-stream.app#%#//scriptlet('set-constant', 'chooseAds', 'undefined')
```
seems to works fine.

By the way, if I'm not wrong, another workaround for issue with video player - https://github.com/uBlockOrigin/uAssets/issues/18840#issuecomment-1623546469 could be something like this:
```adblock
e-player-stream.app#%#//scriptlet('set-constant', 'isSetupAccess', 'true')
```

**Comment by Yuki2718** [comment]
Oh, I didn't realize iframe is a different domain! Can you fix?

**Comment by stephenhawk8054** [comment]
Confirm `set` filter works on my end 👍 So we don't need to use local storage

**Comment by stephenhawk8054** [comment]
@x-R0b0T-x Can you describe the steps to reproduce in more details. There are many options to click in the video player.

**Comment by stephenhawk8054** [comment]
> So you have two buttons, on the left to play without ads, and on the right, with ads. ![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/93663e46-3a2c-4694-8279-e3526190b036)

So which one did you choose? `VOSTFR` or `VF`?

**Comment by stephenhawk8054** [comment]
Can you test in Firefox if the issue still occurs (with only uBO and default settings + `AdGuard Français`)?

**Comment by stephenhawk8054** [comment]
I mean, do you still see the ads waiting panel in Firefox like this?

> ![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/52a6ba57-854b-4346-ba26-944ef53a5698)

**Comment by stephenhawk8054** [comment]
@x-R0b0T-x Let's test in Firefox first, can you test this filter?

```adb
||empire-*/iframe_ad/ad_mov$frame,1p,replace=/data: \[[^\]]+\],/data: [],/
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

Remember to enable `Allow custom filters requiring trust` in "My filters" pane as well.

**Comment by stephenhawk8054** [comment]
> Remember to enable `Allow custom filters requiring trust` in "My filters" pane as well.

**Comment by stephenhawk8054** [comment]
Can you do these steps (follow strictly the step order, don't mix the steps orders, or skip any steps):

1. Click on uBO icon > ▤ ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Open new tab and reproduce the issue
3. Switch to the logger window that was opened in step 1
4. Copy the logger via 📋 [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here

**Comment by stephenhawk8054** [comment]
Oh wait, you click on the **left**. I thought you were clicking on the **right** (play with ads) the whole time

**Comment by stephenhawk8054** [comment]
What checker? Can you screenshot it?

**Comment by stephenhawk8054** [comment]
I have addressed the popup when you choose the left one in https://github.com/uBlockOrigin/uAssets/commit/937d7dea41825938978d658a0ff2bdeff8d8aff7 . The box appearing for you to click cannot be bypassed entirely

The rest I think they're paywalled so we cannot address them. You can use these as custom filters if you don't want to click too many times

```adb
empire-stream.*,empire-streaming.*##+js(set, empire.direct, undefined)
empire-stream.*,empire-streaming.*##+js(set, empire.directHideAds, undefined)

empire-stream.*,empire-streaming.*##+js(set, empire.countpremium.film, 1)
empire-stream.*,empire-streaming.*##+js(set, empire.countpremium.serie, 1)

empire-stream.*,empire-streaming.*##+js(set, empire.countpremiumaccount.film, 1)
empire-stream.*,empire-streaming.*##+js(set, empire.countpremiumaccount.serie, 1)
```

**Comment by stephenhawk8054** [comment]
The first 3 were added to the main list already. The others are not.
