### ISSUE TITLE
panel.kasperhub.com: breakage

### ISSUE THREAD

**Issue by RinnDog** [uBlockOrigin/uAssets#18849]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I am currently in the process of developing the login functionality for my product. However, I'm facing an issue where uBlock Origin is blocking the interaction between our API, which has been properly set up with CORS, and our dashboard. This problem persists even with the default settings, and I have verified that CORS is correctly configured.

Errors in Console:
```
An unsupported feature name "publickey-credentials-get" is being skipped in the Feature Policy. kwift.CHROME.js:2:319785
XHROPTIONS
https://api.kasperhub.com/users/token
CORS Missing Allow Origin

The Same Origin Policy is preventing the retrieval of the remote resource at https://api.kasperhub.com/users/token due to the absence of the CORS header 'Access-Control-Allow-Origin'. Status code: 521.

The Same Origin Policy is blocking the retrieval of the remote resource at https://api.kasperhub.com/users/token. The CORS request did not succeed. Status code: (null).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch the resource.
```

### URL(s) where the issue occurs.

`https://panel.kasperhub.com/login`

### Screenshot(s)

<img width="820" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/90881580/bdabaa70-a1c6-45e9-910c-2bd1266c41db">

### Notes

As we are currently in the process of development, it is not possible to sign up. Please do not attempt to try.

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 21d.8h.55m
Firefox: 114
filterset (summary):
 network: 22045
 cosmetic: 10393
 scriptlet: 17862
 html: 983
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  easylist: null
  easyprivacy: null
  plowe-0: null
 default:
  ublock-filters: 34683-41, 10h.46m
  ublock-badware: 7482-0, 10h.45m
  ublock-privacy: 459-0, 5d.12h.55m
  ublock-unbreak: 2101-2, 10h.44m
  ublock-quick-fixes: 270-14, 10h.43m
  urlhaus-1: 6356-2, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 19 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 641 ms (selfie)
 maxAssetCacheWait: 261 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Doors it occur if you turn off uBO?

**Comment by gorhill** [comment]
> Please do not attempt to try.

If we can't reproduce on our side, we can't investigate, so you will have to find out which filter from which filter lists is causing the issue -- use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) for this.
