### ISSUE TITLE
rockmods.net: detection

### ISSUE THREAD

**Issue by blarns** [uBlockOrigin/uAssets#18847]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.rockmods.net/2023/07/Fing.html?m=1`

### Category

detection

### Description

when I try to load the page a message stating "We Work very hard to Provide you the best and Safest Android Mods, Please Support Us By Either Turning off Your Adblocker or Whitelisting The Domain "*.www.rockmods.net".
Refresh The Page if Already Done. " 

### Other extensions used

privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230705_150046_Firefox](https://github.com/uBlockOrigin/uAssets/assets/62329423/92717676-7e94-41ed-9526-88b58bb91c32)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 23d.12m
Firefox Mobile: 115
filterset (summary):
 network: 97907
 cosmetic: 29501
 scriptlet: 17911
 html: 984
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34966-303, now
  ublock-badware: 7484-1, now
  ublock-privacy: 464-1, now
  ublock-unbreak: 2106-4, now
  ublock-quick-fixes: 256-0, 18m
  adguard-mobile: 8367-121, now
  easylist: 67880-17410, now
  easyprivacy: 33400-733, now
  urlhaus-1: 6372-2, 17m
  plowe-0: 3739-1, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 958 ms
 maxAssetCacheWait: 149 ms
popupPanel:
 blocked: 11
 network:
  blogger.com: 3
  google.com: 3
  googlesyndication.com: 5
 extended:
  ##ins.adsbygoogle
  ##+js(abort-current-script, String.prototype.charCodeAt, protect…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you disable all other add-ons and test again?

**Comment by blarns** [comment]
looks to have resolved.  privacy badger was the issue

.
________________________________

**Comment by stephenhawk8054** [comment]
Please do what you have ticked on truthfully:

> - [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.

**Comment by blarns** [comment]
that is super fucking ableist.. I'm autistic and ADHD sorry for having executive functioning issues and not realizing until it was too late. I didn't lie to you...

.
________________________________

**Comment by ghajini** [comment]
can't reproduce ,be sure not to use another content blocker alongside
