### ISSUE TITLE
vice.com: ads

### ISSUE THREAD

**Issue by johnsmithwilliams** [uBlockOrigin/uAssets#18846]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There is a large black bar at the top

### URL(s) where the issue occurs.

`https://www.vice.com/en/article/bvmqkv/netflix-anime-dog-and-the-boy-ai-generated-art`

### Screenshot(s)

<img width="594" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/138721091/431ca03e-36b3-42aa-8ddd-67cf337ca44b">

### Notes

N/A

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.7h.39m
Firefox: 112
filterset (summary):
 network: 194013
 cosmetic: 286258
 scriptlet: 30801
 html: 1241
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68619-4748, 2d.4m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92109-65419, 3d.1h.30m
  fanboy-cookiemonster: 47789-344, 2d.14h.58m
  ublock-annoyances: 5260-16, 6d.6h.5m
  ara-0: 2326-0, 3h.35m
  BGR-0: 1091-11, 3d.1h.30m
  CHN-0: 26370-146, 3d.1h.30m
  CZE-0: 746-1, 3h.41m
  DEU-0: 6936-6, 3h.51m
  EST-0: 463-2, 3h.29m
  FIN-0: 2215-0, 2d.2m
  FRA-0: 28352-617, 2d.38m
  [28 lists not shown]: [too many]
 default:
  user-filters: 21-0, never
  ublock-filters: 34561-226, 3d.1h.30m
  ublock-badware: 7680-0, 3d.1h.30m
  ublock-privacy: 457-0, 6d.17h.51m
  ublock-unbreak: 2093-9, 3d.1h.30m
  easylist: 67543-1373, 3d.1h.30m
  easyprivacy: 33415-885, 6h.13m
  urlhaus-1: 6372-0, 3h.33m
  plowe-0: 3737-2, 10d.11h.30m
  ublock-quick-fixes: 275-4, 3h.1m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1020 ms (selfie)
 maxAssetCacheWait: 159 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

**Comment by rakleed** [comment]
Ad leftovers on `https://www.vice.com/en/`.

Annoyance leftovers on `https://www.vice.com/en/article/stop-saying-the-tank-is-obsolete-just-because-russia-sucks-at-using-them/`.

<details><summary>Screenshots:</summary>

Ads:
![Image](https://github.com/user-attachments/assets/c295508a-d610-4d14-aa98-68f72ea2b39d)

![Image](https://github.com/user-attachments/assets/78727a69-5d5c-44c4-8726-48051cc2b2ff)

![Image](https://github.com/user-attachments/assets/a70443a8-729d-4472-a859-e712c4a35708)

Annoyances:

![Image](https://github.com/user-attachments/assets/26dafd47-e9af-453c-9ef7-83be59c7680a)

</details>

<details><summary>Details</summary>

```yaml
uBlock Origin: 1.62.0
Chromium: 134
filterset (summary):
 network: 196425
 cosmetic: 275540
 scriptlet: 61555
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-badware: null
 added:
  adguard-generic: 100010-5862, now
  adguard-mobile: 10839-113, now
  adguard-spyware-url: 2023-136, now
  adguard-cookies: 33641-109, now
  ublock-cookies-adguard: 3759-21, now
  fanboy-cookiemonster: 44543-3725, now
  ublock-cookies-easylist: 3759-3759, now
  adguard-social: 23774-826, now
  fanboy-social: 16645-4, now
  adguard-popup-overlays: 28957-3134, now
  adguard-mobile-app-banners: 5932-1137, now
  adguard-other-annoyances: 14747-738, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 40546-118, now
  ublock-privacy: 2757-34, now
  ublock-unbreak: 2573-6, now
  ublock-quick-fixes: 256-9, now
  easylist: 69880-655, now
  easyprivacy: 53415-979, now
  urlhaus-1: 25800-0, now
  plowe-0: 3464-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 407 ms (selfie)
 maxAssetCacheWait: 60 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  beehiiv.com: 2
  facebook.net: 1
  googletagmanager.com: 1
  kargo.com: 1
  lngtd.com: 1
  p-n.io: 1
  parsely.com: 1
  quantserve.com: 1
  scorecardresearch.com: 1
  skimresources.com: 1
  trackonomics.net: 1
  wp.com: 1
 extended:
  ##.wp-block-social-links
  ##.wp-block-savage-platform-beehiiv-form
``` 

</details>

**Comment by stephenhawk8054** [comment]
@rakleed For issues that can be solved by standard filters, please report to https://github.com/easylist/easylist/issues

**Comment by nqlp** [comment]
Videos by Vice is missing: 

https://github.com/user-attachments/assets/f8954d1a-bd12-42e8-b3ae-1f0dd4cc6f05

**Comment by stephenhawk8054** [comment]
It's an ad video disguised as "related" videos. We won't unblock it. You can unblock yourself by adding these as your custom filters

```adb
@@||live.primis.tech^$script,domain=vice.com
vice.com#@#.wp-block-savage-platform-primis-video
```
