### ISSUE TITLE
market-delivery.yandex.ru: breakage

### ISSUE THREAD

**Issue by yabl04** [uBlockOrigin/uAssets#18853]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://market-delivery.yandex.ru/`

### Category

breakage

### Description

Не загружает сайт
![image](https://github.com/uBlockOrigin/uAssets/assets/96691483/d85f83a4-80f2-4d60-9f5b-116c631f8841)

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 24d.13h.22m
Chromium: 114
filterset (summary):
 network: 181191
 cosmetic: 180783
 scriptlet: 37158
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26204-41, 2h.43m
  adguard-generic: 72258-622, 2h.43m
  adguard-mobile: 8367-65, 2h.43m
  adguard-mobile-app-banners: 4399-9, 2h.43m
  adguard-other-annoyances: 13037-43, 2h.43m
  adguard-popup-overlays: 22890-411, 2h.43m
  adguard-social: 20831-887, 2h.42m
  adguard-spyware: 60326-1298, 2h.42m
  adguard-spyware-url: 1114-3, 2h.42m
  adguard-widgets: 2195-18, 2h.42m
 default:
  user-filters: 9-0, never
  RUS-0: 39456-9, 2h.43m
  easylist: 67885-1013, 2h.42m
  easyprivacy: 33403-16679, 2h.42m
  plowe-0: 3740-1241, now
  ublock-badware: 7488-365, 2h.42m
  ublock-filters: 33823-4167, 2h.42m
  ublock-privacy: 425-65, 2h.42m
  ublock-quick-fixes: 280-15, 3h.12m
  ublock-unbreak: 2064-134, 2h.42m
  urlhaus-1: 6356-2, 2h.42m
filterset (user): [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 19643 ms (selfie)
 maxAssetCacheWait: 1013 ms
popupPanel:
 blocked: 3
 network:
  yandex.ru: 3
 extended:
  ##+js(cookie-remover, /^bltsr$|^JPIqApiY$|^specific$|^substantia…
  ##+js(json-prune, seatbid rtb direct):matches-path(/images)
  ##+js(noeval-if, Id":"R-I):matches-path(/\/(?:weather\/|pogoda\/…
  ##+js(abort-on-property-read, Object.prototype.renderDirect):mat…
  ##+js(json-prune, rtb):matches-path(/\/(?:weather\/|pogoda\/|hav…
  ##+js(json-prune, seatbid):matches-path(/video)
  ##+js(json-prune, direct rtb):matches-path(/games)
  ##+js(json-prune, rtb seatbid):matches-path(/sport)
  ##+js(json-prune, direct rtb):matches-path(/q)
  ##+js(remove-attr, data-counter, .serp-list a[href]):matches-pat…
```
</details>

**Comment by stephenhawk8054** [comment]
It's caused by the filter

```adb
yandex.*##+js(aopr, Object.prototype.renderDirect):matches-path(/\/(?:weather\/|pogoda\/|hava\/)/)
```

in `AdGuard – Popup Overlays` list.

@gorhill At first, I thought `matches-path` filters with scriptlets will automatically be discarded, but looks like they're not?

**Comment by gorhill** [comment]
The scriptlet injection syntax parser doesn't know about cosmetic procedural operators syntax, so from the point of view scriptlet injection syntax parser, what follows `aopr` is just a weird argument.

**Comment by stephenhawk8054** [comment]
Ah ok I see now, it sees `Object.prototype.renderDirect):matches-path(/\/(?:weather\/|pogoda\/|hava\/)/` as a whole object.

**Comment by stephenhawk8054** [comment]
Hmmm... so how should we resolve issues with `matches-path` like this? I think we can add

```
yandex.*#@#+js(aopr, Object.prototype.renderDirect):matches-path(/\/(?:weather\/|pogoda\/|hava\/)/)
```

but I'm not sure which list should handle these issues.

**Comment by gorhill** [comment]
https://github.com/AdguardTeam/tsurlfilter/issues/65

**Comment by gorhill** [comment]
It has to be handled by us until the conversion code in AdGuard is fixed.

**Comment by stephenhawk8054** [comment]
Ok, I think we can put it to unbreak.
