### ISSUE TITLE
dash-free.com: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18855]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dash-free.com/ANOp`

### Category

detection

### Description

Only one page has a problem.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.1h.31m
Chromium: 114
filterset (summary):
 network: 96552
 cosmetic: 22492
 scriptlet: 17919
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67861-16698, now
  easyprivacy: 33407-64, now
  plowe-0: 3740-1070, now
  ublock-badware: 7494-138, now
  ublock-filters: 33843-359, now
  ublock-privacy: 426-4, now
  ublock-quick-fixes: 274-15, now
  ublock-unbreak: 2064-34, now
  urlhaus-1: 6387-1, now
filterset (user): [empty]
trustedset:
 added: [array of 16 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6322 ms (selfie)
 maxAssetCacheWait: 990 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(set-constant, go_popup, {})
  ##+js(set-constant, blurred, false)
  ##+js(abort-on-property-read, app_vars.force_disable_adblock)
```
</details>

**Comment by okiehsch** [comment]
Works fine on my end.

**Comment by gorhill** [comment]
I end up on a page asking me to log in: `https://viefaucet.com/login?redirect=/app/link/44da7170333f74ffd367985d9ede33`.

**Comment by gorhill** [comment]
> this shortlink from viefaucet.com

Not sure what that means. Can you clarify whether logging in at the link `https://viefaucet.com/login?redirect=/app/link/44da7170333f74ffd367985d9ede33` is necessary to reproduce the issue you are reporting?
