### ISSUE TITLE
playstore.pw: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18856]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://playstore.pw/`

### Category

detection

### Description

This short link could not be completed. Shows button for next step. But after clicking the button the page reloads.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.1h.55m
Chromium: 114
filterset (summary):
 network: 96552
 cosmetic: 22492
 scriptlet: 17919
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67861-16698, 23m
  easyprivacy: 33407-64, 23m
  plowe-0: 3740-1070, 23m
  ublock-badware: 7494-138, 23m
  ublock-filters: 33843-359, 23m
  ublock-privacy: 426-4, 23m
  ublock-quick-fixes: 274-15, 23m
  ublock-unbreak: 2064-34, 23m
  urlhaus-1: 6387-1, 23m
filterset (user): [empty]
trustedset:
 added: [array of 16 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6322 ms (selfie)
 maxAssetCacheWait: 990 ms
popupPanel:
 blocked: 490
 network:
  360yield.com: 5
  4dex.io: 18
  a-mo.net: 25
  adform.net: 14
  adleadevent.com: 1
  adnxs.com: 29
  adscale.de: 15
  betweendigital.com: 21
  bidswitch.net: 12
  creativecdn.com: 4
  criteo.com: 76
  criteo.net: 9
  d3plnp2f9sfye5.cloudfront.net: 30
  doubleclick.net: 32
  e-planning.net: 4
  googlesyndication.com: 5
  id5-sync.com: 1
  omnitagjs.com: 5
  onetag-sys.com: 20
  pbstck.com: 9
  pubmatic.com: 16
  r2b2.io: 55
  rubiconproject.com: 16
  sddan.com: 4
  smartadserver.com: 33
  smilewanted.com: 6
  themoneytizer.com: 10
  tmyzer.com: 4
  unblockia.com: 1
  yahoo.com: 5
  zemanta.com: 5
 extended:
  ##+js(abort-on-property-read, adsBlocked)
```
</details>

**Comment by okiehsch** [comment]
> This short link could not be completed.

We need the exact link to investigate.
