### ISSUE TITLE
nytimes.com: nuisance

### ISSUE THREAD

**Issue by jo99jo** [uBlockOrigin/uAssets#18858]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nytimes.com/2023/07/06/business/economy/jobs-great-resignation.html`

### Category

nuisance

### Description

A popup from the bottom of the page stating "You’ve reached your limit of free articles."

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/48929420/2eb8beba-76b6-45a1-9794-4a2fa37aeb93)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 28d.23h.1m
Chromium: 114
filterset (summary):
 network: 96579
 cosmetic: 39403
 scriptlet: 17919
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 273-15, now
 default:
  user-filters: 16-1, never
  easylist: 67881-10, now
  easyprivacy: 33407-62, now
  plowe-0: 3740-1070, now
  ublock-badware: 7494-138, now
  ublock-filters: 33843-147, now
  ublock-privacy: 426-3, now
  ublock-unbreak: 2064-33, now
  urlhaus-1: 6387-1, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 469 ms (selfie)
 maxAssetCacheWait: 182 ms
popupPanel:
 blocked: 22
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 network:
  nytimes.com: 7
  amazon-adsystem.com: 1
  dwcdn.net: 1
  geoedge.be: 1
  googletagmanager.com: 1
  nyt.com: 11
```
</details>

**Comment by okiehsch** [comment]
We don't fix paywalls.

**Comment by jo99jo** [comment]
I've bene using the element zapper to remove this nuisance.  Is there a better, permanent way so I don't have to zap it on each article I open?

**Comment by jo99jo** [comment]
> Use the element picker, it's next to the element zapper.

That doesn't seem to work.  The picker does not pick up anything.

**Comment by stephenhawk8054** [comment]
> > Use the element picker, it's next to the element zapper.
> 
> That doesn't seem to work. The picker does not pick up anything.

It does for me: https://github.com/uBlockOrigin/uAssets/assets/66517106/80f73a1d-959a-4d27-88e8-d5650992b984

**Comment by jo99jo** [comment]
It doesn't for me.  This is what I get in Edge.  Area turns gray and all I see a + sign that doesn't grab anything.  I have to hit the Esc button to get out the mode and go back to use the zapper.
![NYT Paywall](https://github.com/uBlockOrigin/uAssets/assets/48929420/9e5f841a-dadb-4477-a9af-90c8c570507c)

**Comment by stephenhawk8054** [comment]
I can't reproduce your screenshot (and I don't know which steps to reproduce it) so can't help you more. You can open a discussion in https://github.com/uBlockOrigin/uAssets/discussions

**Comment by Grand-Cherokee** [comment]
Still there. I believe its at least partially caused by source key "*.sentry". I see a bottom slide-up subscription demand and a timed light dimming of entitre desired page.
