### ISSUE TITLE
reports.adguard.com: nuisance

### ISSUE THREAD

**Issue by heartlog** [uBlockOrigin/uAssets#18854]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did answer truthfully to **ALL** the above checkpoints.LOL

### URL address of the web page

`https://medium.com/mlearning-ai/how-to-write-a-blog-using-chatgpt-69dbeb5868ba`

### Category

nuisance

### Description

leftover overlay ?
##.go.cn.ab.ade.gf.add.adc.ge.adb.ada.gd.acz.v.gc.acy.t.gb.acx

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/76758776/13bd17fc-23e1-4bc3-8cb2-fd2a69aecd05)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 8d.23h.38m
Chromium: 114
filterset (summary):
 network: 169494
 cosmetic: 167620
 scriptlet: 35852
 html: 0
listset (total-discarded, last-updated):
 added:
  
  adguard-cookies: 26184-29, 1d.23h.37m
  adguard-generic: 72213-483, 1d.23h.36m
  adguard-mobile: 8353-46, 1d.23h.35m
  adguard-mobile-app-banners: 4396-8, 1d.23h.34m
  adguard-other-annoyances: 13035-7, 1d.23h.33m
  adguard-popup-overlays: 22852-70, 1d.23h.32m
  adguard-social: 20814-880, 1d.23h.31m
  adguard-spyware: 60323-1244, 1d.23h.30m
  adguard-spyware-url: 1114-3, 1d.23h.29m
  adguard-widgets: 2193-7, 1d.23h.27m
 default:
  user-filters: 142-88, never
  easylist: 67688-1034, 1d.23h.26m
  easyprivacy: 33397-16634, 1d.23h.25m
  plowe-0: 3739-1233, 1d.23h.23m
  ublock-badware: 7480-365, 1d.23h.22m
  ublock-filters: 33752-4142, 1d.23h.21m
  ublock-privacy: 423-64, 1d.23h.20m
  ublock-quick-fixes: 280-15, 4h.25m
  ublock-unbreak: 2059-133, 1d.23h.18m
  urlhaus-1: 6431-2, 22h.11m
filterset (user): [array of 142 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10096 ms (selfie)
 maxAssetCacheWait: 957 ms
popupPanel:
 blocked: 4
 network:
  adguard.com: 4
```
</details>

**Comment by okiehsch** [comment]
Looks like sekf advertisement, we don't fix that.

**Comment by stephenhawk8054** [comment]
Hmmm... Looks like Adguard does address it in `Adguard - Popup Overlays` list: https://github.com/AdguardTeam/AdguardFilters/commit/49bcd13c2c87c1da88170a3212a64810ac95e945

However, as a trusted scriptlet, it won't appear in uBO version.

**Comment by stephenhawk8054** [comment]
I think we can address this specific issue given that the filter in other annoyance lists can't reach the users (due to trusted scriptlets)
