### ISSUE TITLE
rapidsave.com: ads

### ISSUE THREAD

**Issue by falseuniversefacts** [uBlockOrigin/uAssets#18850]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rapidsave.com/info?url=/r/okbuddytrailblazer/comments/14rmcek/next_level_i_did_not_make_this/`

### Category

ads

### Description

This shows up at the top: `[Write content, emails etc with AI - Try our AI copywriter for free - CopyPhrase.com](https://copyphrase.com/?utm_source=rs)`

Link: `https://rapidsave.com/info?url=/r/okbuddytrailblazer/comments/14rmcek/next_level_i_did_not_make_this/`

### Other extensions used

Privacy Badger
ClearURLs
Decentraleyes
Grammarly
(many others but they are just dev-related or don't effect this site)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 22d.22h.59m
Firefox: 115
filterset (summary):
 network: 394128
 cosmetic: 345550
 scriptlet: 45825
 html: 1243
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68562-68562, 3d.11h.10m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92109-92108, 3d.11h.10m
  adguard-generic: 72072-7325, 3d.11h.11m
  adguard-mobile: 8335-128, 3d.11h.11m
  adguard-spyware-url: 1104-6, 3d.11h.11m
  block-lan: 47-0, 3d.11h.11m
  curben-phishing: 125117-43, 4h.14m
  curben-pup: 199-0, 4h.13m
  adguard-social: 20763-832, 3d.11h.11m
  fanboy-thirdparty_social: 68-0, 3d.11h.11m
  fanboy-cookiemonster: 47789-3865, 3d.11h.11m
  fanboy-social: 16086-34, 3d.11h.11m
  [48 lists not shown]: [too many]
 default:
  user-filters: 13-0, never
  ublock-filters: 34563-726, 3d.11h.11m
  ublock-badware: 7685-0, 3d.11h.11m
  ublock-privacy: 459-0, 3d.11h.11m
  ublock-unbreak: 2093-0, 3d.11h.11m
  ublock-quick-fixes: 275-3, 11h.55m
  easylist: 67642-1574, 3d.11h.11m
  easyprivacy: 30704-1031, 3d.11h.11m
  urlhaus-1: 6356-0, 4h.15m
  plowe-0: 3738-2, 3d.11h.11m
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 489 ms (selfie)
 maxAssetCacheWait: 340 ms
popupPanel:
 blocked: 10
 network:
  aniview.com: 2
  googletagmanager.com: 2
  redditsave.com: 2
  snigelweb.com: 2
  videoplayerhub.com: 2
 extended:
  ##div[id^="adngin-"]
```
</details>

**Comment by okiehsch** [comment]
`rapidsave.com##.alert-info:has-text(CopyPhrase)`
@ryanbr
