### ISSUE TITLE
ytstv.me: detection

### ISSUE THREAD

**Issue by mrblake213** [uBlockOrigin/uAssets#18868]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ytstv.me/`

### Category

detection

### Description

I cannot access the website's content because it is detecting uBlock.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock detected](https://github.com/uBlockOrigin/uAssets/assets/138506863/8c53f8b3-6236-4b8b-8e8c-32e007a9c9c9)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 26m
Chromium: 114
filterset (summary):
 network: 96652
 cosmetic: 39406
 scriptlet: 17931
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 67971-10, 26m
  easyprivacy: 33407-62, 26m
  plowe-0: 3740-1072, 26m
  ublock-badware: 7508-138, 26m
  ublock-filters: 33850-147, 26m
  ublock-privacy: 426-3, 26m
  ublock-quick-fixes: 278-15, 26m
  ublock-unbreak: 2065-33, 26m
  urlhaus-1: 6373-1, 26m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1340 ms
 maxAssetCacheWait: 12 ms
popupPanel:
 blocked: 18
 no-scripting: true
 network:
  ytstv.me: 13
  addthis.com: 1
  ajax.googleapis.com: 1
  asacdn.com: 1
  google.com: 1
  googletagmanager.com: 1
 extended:
  ##.jt.ml-mask
  ##+js(abort-on-property-write, _pop)
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by mrblake213** [comment]
Philippines

**Comment by mrblake213** [comment]
It works now! Thank you.

**Comment by Naashkyr** [comment]
This is happening to me.  I just installed uBlock Origin plugin on Chrome yesterday.  Just went through the list of checkpoints at the top (using shift-click on "Purge all caches" and clicked on "Update now" as well as double-checked all of the default filter lists) but I'm still getting this issue:

![image](https://github.com/uBlockOrigin/uAssets/assets/118468527/00606b67-6d4d-492a-81b7-b20777458ac5)

I have everything enabled in the Filter Lists tab except "Ignore generic cosmetic filters", "Dan Pollock’s hosts file" and "Fanboy – Anti-Facebook".  I am accessing from Canada.

I did not want to create a duplicate issue but please let me know if you need more information.

**Comment by stephenhawk8054** [comment]
> I have everything enabled in the Filter Lists tab except "Ignore generic cosmetic filters", "Dan Pollock’s hosts file" and "Fanboy – Anti-Facebook".

Please test in another browser profile with only uBO and its default settings.
