### ISSUE TITLE
diagram.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18863]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://diagram.com/`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/6716082b-0ebc-4083-a8f8-971cd7a51d60)

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 19d.19h.51m
Chromium: 114
filterset (summary):
 network: 130019
 cosmetic: 135822
 scriptlet: 24991
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9190-3, 11h.35m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 1d.11h.52m
  DEU-0: 6936-0, 11h.37m
  FRA-0: 28354-65, 1d.11h.53m
  IDN-0: 9527-376, 1d.11h.53m
  ara-0: 2326-9, 11h.36m
  easylist-annoyances: 3888-42, 1d.11h.52m
  easylist-chat: 128-0, 1d.11h.52m
  easylist-newsletters: 6244-15, 1d.11h.52m
  easylist-notifications: 2641-85, 1d.11h.52m
  fanboy-cookiemonster: 47813-223, 1d.11h.52m
  fanboy-social: 16086-16, 1d.11h.52m
  [1 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 67876-277, 1d.11h.52m
  easyprivacy: 33399-441, 1d.11h.52m
  plowe-0: 3739-1081, 1d.11h.52m
  ublock-badware: 7480-155, 1d.11h.52m
  ublock-filters: 33809-414, 1d.11h.52m
  ublock-privacy: 423-6, 1d.11h.52m
  ublock-quick-fixes: 274-16, 11h.33m
  ublock-unbreak: 2064-48, 1d.11h.52m
  urlhaus-1: 6387-1, 11h.34m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1365 ms (selfie)
 maxAssetCacheWait: 610 ms
popupPanel:
 blocked: 10
 network:
  googletagmanager.com: 2
  sentry.io: 3
  vercel-insights.com: 5
 extended:
  ##.share-heading
  ##.reddit-icon
  ##.social-icon-link
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/416a7609e00db94b9d247136ca96792e5cb85f81
