### ISSUE TITLE
trecetv.es [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1886]
URL(s) where the issue occurs

`http://trecetv.es/video/?videoId=e-32897`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`@@||trecetv.es^$generichide`

**Comment by mapx-** [comment]
```
@@||player.enetres.net/js/videojs-plugins/videojs-ads-contrib/videojs.ads.js$script,domain=trecetv.es
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=trecetv.es
@@||trecetv.es^$generichide
```

@diaux

**Comment by KiLL4FuNK** [comment]
you can not see the video

`http://www.trecetv.es/noticias/nacional/aparece-en-barcelona-una-soga-amarilla-con-un-lema-antimonarquico`
