### ISSUE TITLE
wetransfer.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18865]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wetransfer.com/downloads/ece1d8b5d5141617f2bddb2a1aa0372f20230704060648/b4858e`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/ff1e949c-b24a-4b91-a87d-d66350e32a63)

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 19d.23h.42m
Chromium: 114
filterset (summary):
 network: 129980
 cosmetic: 135765
 scriptlet: 25039
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9242-3, 3h.50m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 3h.50m
  DEU-0: 6937-0, 3h.50m
  FRA-0: 28276-65, 3h.50m
  IDN-0: 9527-376, 3h.50m
  ara-0: 2326-9, 3h.50m
  easylist-annoyances: 3888-42, 3h.50m
  easylist-chat: 129-0, 3h.50m
  easylist-newsletters: 6253-15, 3h.50m
  easylist-notifications: 2642-85, 3h.50m
  fanboy-cookiemonster: 47688-221, 3h.50m
  fanboy-social: 16087-16, 3h.50m
  [1 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 67885-279, 3h.50m
  easyprivacy: 33407-441, 3h.50m
  plowe-0: 3740-1083, 3h.50m
  ublock-badware: 7509-156, 3h.50m
  ublock-filters: 33845-413, 3h.50m
  ublock-privacy: 426-6, 3h.50m
  ublock-quick-fixes: 272-15, 3h.50m
  ublock-unbreak: 2066-44, 3h.50m
  urlhaus-1: 6373-1, 3h.50m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 3388 ms (selfie)
 maxAssetCacheWait: 729 ms
popupPanel:
 blocked: 11
 network:
  wetransfer.com: 1
  amplitude.com: 8
  cloudflare.com: 1
  googletagmanager.com: 1
 extended:
  #@#.welcome--cookies
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
wetransfer.com##.welcome--cookies
wetransfer.com##.transfer__cookie-wall-active:remove-class(transfer__cookie-wall-active)
```

@ryanbr
