### ISSUE TITLE
adsbtc.fun: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#18866]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://adsbtc.fun/`

### Category

detection

### Description

ad blocker disable pop-up coming.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/75168867/9eeefb73-9a80-490c-b206-5187f1611a24)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.16h.16m
Chromium: 114
filterset (summary):
 network: 96652
 cosmetic: 22497
 scriptlet: 17924
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67971-16698, 1h.46m
  easyprivacy: 33407-64, 1h.46m
  plowe-0: 3740-1072, 1h.46m
  ublock-badware: 7508-138, 1h.46m
  ublock-filters: 33846-359, 1h.46m
  ublock-privacy: 426-4, 1h.46m
  ublock-quick-fixes: 272-15, 1h.46m
  ublock-unbreak: 2065-34, 1h.46m
  urlhaus-1: 6373-1, 1h.46m
filterset (user): [empty]
trustedset:
 added: [array of 16 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 15066 ms (selfie)
 maxAssetCacheWait: 502 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by ghajini** [comment]
steps to reproduce antadb?

**Comment by gorhill** [comment]
We can't fix what we can't reproduce.
