### ISSUE TITLE
outlook.com: breakage

### ISSUE THREAD

**Issue by StraggleCraft** [uBlockOrigin/uAssets#18874]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When ubo is enabled, I'm not able to see search results while filtering in specific folders. for example, `from:no-reply@email.gog.com` restricting to Inbox only will return no results (results return for an instant, but are hidden from view).

However, with ubo disabled, results are returned correctly.   The search ***does work correctly*** if the search is set to "all folders".

Please see screenshots.  I'm unsure how to isolate this to a specific filter list.

### URL(s) where the issue occurs.

`https://outlook.live.com/mail/0/`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/10663364/d744103d-1746-4b7a-9a57-7260b851d023)
![image](https://github.com/uBlockOrigin/uAssets/assets/10663364/75701ec4-3020-4af9-8b1a-217156514f2b)
![image](https://github.com/uBlockOrigin/uAssets/assets/10663364/f5aad526-a3f9-405c-bcad-10561d152deb)

### Notes

"Search Scope" set to "current folder" is not the default outlook.com setting, and may be why this was missed in testing.
![image](https://github.com/uBlockOrigin/uAssets/assets/10663364/05cc93c2-aeeb-4064-aa5f-0626ebba02e5)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 14d.12m
Firefox: 115
filterset (summary):
 network: 148644
 cosmetic: 164130
 scriptlet: 23668
 html: 986
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68790-4342, 2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91943-65166, 2m
  fanboy-thirdparty_social: 69-0, 2m
  fanboy-cookiemonster: 47692-217, 2m
  adguard-spyware: 60309-16773, 2m
 default:
  user-filters: 21-1, never
  ublock-filters: 34730-55, 2m
  ublock-badware: 7516-1, 2m
  ublock-privacy: 468-0, 2m
  ublock-unbreak: 2104-2, 2m
  easylist: 67976-746, 2m
  easyprivacy: 33409-725, 2m
  plowe-0: 3739-1, 2m
  urlhaus-1: 6568-0, 2m
  ublock-quick-fixes: 279-0, 2m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 89 redacted]
 removed:
  edge-scheme
  moz-extension-scheme
  wyciwyg-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 7359 ms (selfie)
 maxAssetCacheWait: 232 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test in another Firefox profile with uBO only and its default settings?

**Comment by StraggleCraft** [comment]
Here is a screenshot after installing firefox portable and installing ubo, updating the default filters and changing no other settings... 
![image](https://github.com/uBlockOrigin/uAssets/assets/10663364/e7cb2e8b-44b6-44ef-b0ea-d38b00ba8996)

**Comment by stephenhawk8054** [comment]
So, does the issue still occur in that new profile with default settings?

**Comment by StraggleCraft** [comment]
No, search is working correctly, however, the ad elements are now being shown, so "upgrade to microsoft 365" and "you're using an ad blocker" on the right

**Comment by gorhill** [comment]
Please use the [_chat_ icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website) to report troubleshooting information for the specific site, this way we can see what uBO is doing on the specific page. This is the optimal way to report filter issues.

**Comment by StraggleCraft** [comment]
It looks like its the "AdGuard - Other Annoyances" list... I see there [is a link](https://agrd.io/report) in the wiki to report an issue, so I'll try over there.  Thank you, i think this can be closed here.
