### ISSUE TITLE
multiple: ad placeholders

### ISSUE THREAD

**Issue by Nojuuu** [uBlockOrigin/uAssets#18871]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Leftover ad placeholders caused by

https://github.com/uBlockOrigin/uAssets/blob/453d4f42a915d7090e6efb1d6a91db99e71f94a9/filters/filters-2021.txt#L6215

### URL(s) where the issue occurs.

`https://www.5gradar.com`
`https://www.gamesradar.com`
`https://www.guitarworld.com`
`https://www.laptopmag.com`
`https://www.marieclaire.co.uk`
`https://www.musicradar.com`

Mobile:
`https://www.androidcentral.com/`
`https://www.imore.com/`
`https://www.windowscentral.com/`

### Screenshot(s)

<img width="43%" src="https://github.com/uBlockOrigin/uAssets/assets/84513173/57d3eda8-8cb3-4a39-ac46-6912382f18bb">
<img width="43%" src="https://github.com/uBlockOrigin/uAssets/assets/84513173/37e3f3c6-5c00-463f-a404-f79a0d0b26a7">

<img width="43%" src="https://github.com/uBlockOrigin/uAssets/assets/84513173/085cbe44-53ec-4e78-9fa2-f193df0a8c99">
<img width="43%" src="https://github.com/uBlockOrigin/uAssets/assets/84513173/7428de6a-bd36-4447-b520-b71101512c66">

### uBO version

1.50.0

### Browser name and version

Firefox 115.0

### Settings

-

### Notes

Maybe add here:
https://github.com/uBlockOrigin/uAssets/blob/453d4f42a915d7090e6efb1d6a91db99e71f94a9/filters/filters-2021.txt#L6251

All these sites are owned by Future US/Future plc

**Comment by stephenhawk8054** [comment]
@Yuki2718 Looks like it's for old CHP? Should we fine-tune it in some ways?

**Comment by Yuki2718** [comment]
It seems most of those placeholder are caused by `:empty` and it's added by your commit: https://github.com/uBlockOrigin/uAssets/commit/3c726142fdc42265d2d1f9d68553514e14e0cc40
Removing `:not(:empty)` will resolve them but will also bring some anti-adb back, I guess.
