### ISSUE TITLE
10corp.com: breakage

### ISSUE THREAD

**Issue by 10corp** [uBlockOrigin/uAssets#18879]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Why not showing SiteLock trust seal?

### URL(s) where the issue occurs.

`https://www.10corp.com/`

### uBO version

uBlock Origin 1.50.0

### Browser name and version

google chrome version

### Settings

uBO's default setting

**Comment by AdblockReporters** [comment]
Its a easyprivacy list. 

<img width="667" alt="Screenshot 2023-07-07 at 22 07 15" src="https://github.com/uBlockOrigin/uAssets/assets/138932214/991dc824-cf7f-4db2-9b44-dd9203a10317">

https://github.com/easylist/easylist/commit/be833de37054fec8a3a8a0d3a26329822c9aecdb

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Intentional. https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_thirdparty.txt#L2569

We block many, they use tracker scripts/pixels.
