### ISSUE TITLE
kinoking.cc: popups 

### ISSUE THREAD

**Issue by erik9012** [uBlockOrigin/uAssets#18870]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Try pressing in the website and encounter referall popips

### URL(s) where the issue occurs.

`https://kinoking.cc/episodes/deadloch-1x8/`

### uBO version

1.50

### Browser name and version

Chrome browser 114

### Settings

uBlock Origin 1.50.0:
 since: 25d.17h.36m
Chromium Mobile: 107
filterset (summary):
 network: 98743
 cosmetic: 31636
 scriptlet: 18030
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 9-0, never
  NLD-0: 2912-26, 1h.38m
  adguard-mobile: 8366-35, 1h.38m
  easylist: 67971-16731, 1h.38m
  easyprivacy: 33407-72, 1h.38m
  plowe-0: 3740-1147, 1h.38m
  ublock-badware: 7502-139, 1h.38m
  ublock-filters: 34132-416, 1h.38m
  ublock-privacy: 426-4, 1h.38m
  ublock-quick-fixes: 278-15, 1h.38m
  ublock-unbreak: 2070-41, 1h.38m
  urlhaus-1: 6373-1, 1h.38m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1515 ms (selfie)
 maxAssetCacheWait: 903 ms

**Comment by stephenhawk8054** [comment]
Please use "Report" button next time: https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website
