### ISSUE TITLE
oe24.at: breakage

### ISSUE THREAD

**Issue by Esokrates** [uBlockOrigin/uAssets#18873]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Example article: `https://www.oe24.at/sport/tennis/medwedew-verzichtet-fuer-wimbledon-aufstieg-auf-haarpflege/562030447`

Head down to the image gallery: 
![image](https://github.com/uBlockOrigin/uAssets/assets/17780185/c7a255a2-fac4-44d1-93e2-f1bc9a0517ff)

Try to press the right arrow to get to the next image and see that it doesn't work. When disabling ublock origin, the image sliding works.

### URL(s) where the issue occurs.

`https://www.oe24.at/sport/tennis/medwedew-verzichtet-fuer-wimbledon-aufstieg-auf-haarpflege/562030447`

### uBO version

1.50.0

### Browser name and version

Firefox 114.0.2

### Settings

Default settings

**Comment by Esokrates** [comment]
It seems dragging the images seems to work with ublock origin enabled, only the arrow button is dysfunctional.

**Comment by okiehsch** [comment]
`@@||script-at.iocnt.net/iam.js$script,domain=oe24.at`
fixes the issue.

**Comment by stephenhawk8054** [comment]
@okiehsch Do these work on your side?

```adb
oe24.at##+js(set, iom, {})
oe24.at##+js(set, iom.c, noopFunc)
```

**Comment by okiehsch** [comment]
Yes.
