### ISSUE TITLE
analyticsvidhya.com: nuisance

### ISSUE THREAD

**Issue by skanskan** [uBlockOrigin/uAssets#18888]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.analyticsvidhya.com/blog/2021/08/decision-tree-algorithm/`

### Category

nuisance

### Description

This web page is dimmed or greyed out when I use ublock origin.
And I can't click on the page.

### Other extensions used

None

### Filters
`! 2023-05-18 https://www.analyticsvidhya.com
www.analyticsvidhya.com###loginModal > .av-modal-dialog.modal-dialog-centered.modal-dialog > .modal-content
`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[https://i.imgur.com/346BloG.png](url)
</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 23d.20h.27m
Chromium: 114
filterset (summary):
 network: 102591
 cosmetic: 112384
 scriptlet: 20574
 html: 0
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91945-15606, now
  fanboy-thirdparty_social: 68-15, now
  spa-1: 5327-70, now
 default:
  user-filters: 22-3, never
  easylist: 68110-42, now
  easyprivacy: 33415-246, now
  plowe-0: 3739-1073, now
  ublock-badware: 7514-138, now
  ublock-filters: 33873-206, now
  ublock-privacy: 430-6, now
  ublock-quick-fixes: 280-15, 1h
  ublock-unbreak: 2068-38, now
  urlhaus-1: 6369-1, now
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 99 redacted]
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 444 ms (selfie)
 maxAssetCacheWait: 233 ms
popupPanel:
 blocked: 44
 network:
  analyticsvidhya.com: 1
  cloudflareinsights.com: 2
  doubleclick.net: 4
  google.com: 23
  googlesyndication.com: 1
  googletagmanager.com: 1
  webengage.com: 1
  wp.com: 1
  youtube.com: 10
 extended:
  ###loginModal > .av-modal-dialog.modal-dialog-centered.modal-dia…
  ##a[href^="http://www.facebook.com/sharer.php"]
  ##a[href^="http://www.linkedin.com/shareArticle?"]
  ###SocialShare
  ##ins.adsbygoogle
  ###cookie-law-info-bar ~ .cli-modal-backdrop
  ###cookie-law-info-bar[style*="bottom:"]
  ###cookie-law-info-again
  ###cookie_hdr_showagain
  ###cliSettingsPopup
  ###credential_picker_container
  ##.ytp-share-button
  ##.ytp-title-channel
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ###gdpr-message
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
default:
  user-filters: 22-3, never
```

Can you copy your custom filters to here?

**Comment by skanskan** [comment]
Oh, yes, I have deleted all custom filters except this:

! 2023-05-18 https://www.analyticsvidhya.com
www.analyticsvidhya.com###loginModal > .av-modal-dialog.modal-dialog-centered.modal-dialog > .modal-content

Which was automatically created when I removed the popup.

**Comment by stephenhawk8054** [comment]
```adb
analyticsvidhya.com##.login-pop-up
analyticsvidhya.com##.modal-backdrop
```

@ryanbr

**Comment by skanskan** [comment]
OK, thanks, it works.
