### ISSUE TITLE
apkmirror.com: detection

### ISSUE THREAD

**Issue by SkullCrusher7** [uBlockOrigin/uAssets#18884]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.apkmirror.com/apk/xiaomi-inc/miui-notes/miui-notes-6-0-0-release/xiaomi-notes-6-0-0-android-apk-download/`

### Category

detection

### Description

15 seconds timer and askme to disable adblock

### Other extensions used

translate web page

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.23h
Chromium Mobile: 110
filterset (summary):
 network: 104194
 cosmetic: 128366
 scriptlet: 24519
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26195-29, 19h.42m
  adguard-mobile-app-banners: 4401-8, 19h.40m
  adguard-other-annoyances: 13039-13, 19h.38m
  adguard-popup-overlays: 22899-60, 19h.38m
  adguard-social: 20848-882, 19h.38m
  adguard-widgets: 2195-4, 19h.38m
  ublock-annoyances: 5373-201, 19h.38m
 default:
  user-filters: 0-0, never
  adguard-mobile: 8366-13, 19h.41m
  easylist: 67971-102, 19h.38m
  easyprivacy: 33407-133, 19h.38m
  plowe-0: 3740-1148, 19h.38m
  ublock-badware: 7482-139, 19h.38m
  ublock-filters: 34098-638, 19h.38m
  ublock-privacy: 426-4, 19h.38m
  ublock-quick-fixes: 280-19, 20h.30m
  ublock-unbreak: 2070-37, 19h.38m
  urlhaus-1: 6356-2, 20h.31m
filterset (user): [array of 0 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3341 ms (selfie)
 maxAssetCacheWait: 745 ms
popupPanel:
 blocked: 15
 network:
  cloudflareinsights.com: 1
  crsspxl.com: 1
  google.com: 5
  googlesyndication.com: 1
  googletagmanager.com: 1
  instant.page: 1
  outbrain.com: 1
  pro-market.net: 1
  quantserve.com: 1
  scorecardresearch.com: 1
  wp.com: 1
 extended:
  ##.OUTBRAIN
  ###bottom-slider
  ##.pushbullet-subscribe-widget
  ###shareDropdown
  ##.ai_widget
  ##.ains-apkm_outbrain_ad
  ##.advertisement-text
  ##.ains
  ###sidebar > div.listWidget:has(> h5:contains(Follow APK Mirror)…
  ##body:style(overflow: auto !important;)
  ##body:style(padding-top: 0 !important;)
  ##.gooWidget:style(opacity: 0 !important; visibility: collapse !…
  ##.google-ad-leaderboard:style(opacity: 0 !important;)
  ##[id^="adtester-container"]:style(position: absolute !important…
  #@#.google-ad-leaderboard
  ##+js(remove-node-text, script, .adslot:empty)
```
</details>

**Comment by okiehsch** [comment]
Works fine with a default setup.

**Comment by SkullCrusher7** [comment]
![Screenshot_20230708-133749_Firefox Nightly](https://github.com/uBlockOrigin/uAssets/assets/138861116/832ef659-fece-435d-8e73-009f7a0517ed)
No detection in kiwi but i reset everything still detection in firefox

**Comment by SkullCrusher7** [comment]
After download apk if i press back button then adblock detected now i think issue can be closed

**Comment by stephenhawk8054** [comment]
On firefox mobile, can you test this filter?

```adb
apkmirror.com##^script:has-text(.adslot:empty)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Test again.

**Comment by SkullCrusher7** [comment]
Hi its fixed
Thank you
