### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by user31415192** [uBlockOrigin/uAssets#18883]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When you attempt to download a file from MegaUp while uBO is enabled, you'll be told to disable your adblocker (uBO in this case). But as you guessed it, this page is LADEN with ads.

### URL(s) where the issue occurs.

General form: `megaup.net/<ID>/<filename>`
Example: `megaup.net/1G90e/Moncage-PLAZA.rar`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/108060704/1174d307-969e-4425-877d-1254a22fdd2d)

### uBO version

1.50.0

### Browser name and version

Microsoft Edge version 114.0.1823.67 (64-bit)

### Settings

- All filter lists enabled.

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

**Comment by user31415192** [comment]
It worked.
