### ISSUE TITLE
nick.com: detection

### ISSUE THREAD

**Issue by b4r3b0n3s** [uBlockOrigin/uAssets#18885]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nick.com/episodes/uqtaaq/rise-of-the-teenage-mutant-ninja-turtles-many-unhappy-returns-season-2-ep-2`

### Category

detection

### Description

I am not a programmer but the adblock detection is unable to be avoided though disabling javascript as it seems its necessary to the pages function. 
 

### Other extensions used

Simple Tab Groups
Tree Style Tab

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/138968070/ed7df73e-2b6c-4d32-b80b-5d475ae8d1f0)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 24d.2h.45m
Firefox: 114
filterset (summary):
 network: 96554
 cosmetic: 39399
 scriptlet: 17893
 html: 984
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34730-55, 59m
  ublock-badware: 7490-0, 2d.2h.26m
  ublock-privacy: 467-0, 1d.2h.1m
  ublock-unbreak: 2096-0, 2d.2h.25m
  ublock-quick-fixes: 277-0, 59m
  easylist: 67885-700, 59m
  easyprivacy: 33415-725, 2d.2h.27m
  urlhaus-1: 6369-0, 1h
  plowe-0: 3739-2, 59m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 554 ms
 maxAssetCacheWait: 170 ms
popupPanel:
 blocked: 6
 network:
  cbsi.com: 1
  doubleclick.net: 1
  imasdk.googleapis.com: 1
  mtvnservices.com: 1
  newrelic.com: 1
  parsely.com: 1
```
</details>

**Comment by b4r3b0n3s** [comment]
sorry i cant be more helpful but i cant figure out how to get around this issue and the ads are infuriatingly long. unfortunately having programmers in the family didn't result in me understanding how any of this works

**Comment by okiehsch** [comment]
Add
`||imasdk.googleapis.com/js/sdkloader/ima3$script,redirect-rule=google-ima.js,domain=nick.com`
to your filter list or wait a few minutes and then update the `uBO-filters` list.
Should work fine after that.
