### ISSUE TITLE
nrk.no: privacy

### ISSUE THREAD

**Issue by AdblockReporters** [uBlockOrigin/uAssets#18889]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nrk.no/`

### Category

privacy

### Description

Context: NRK is the #2 largest norwegian newspaper. It's government owned radio, tv and newspaper

NRK does some view tracking that sends a bunch of context information to build data on what your viewing 
Known proxy service that then sends data to google analytics

Example filters
```
! Block the ping and xhr call, as sometimes there are scripts/widgets that do fetch calls to endpoint directly
||data.nrk.no/nrk/wd6$xhr,ping
! Blocks the tracking script from ever starting collection / posting to the above endpoint
||static.nrk.no/nrkno-snowplow/*$script
! Blocks their script that calls google analytics 
||static.nrk.no/core-analytics/*$script
! Blocks their analytics loader
||static.nrk.no/dh/module/nrkno-eksperimenter/assets/analytics-context.*.js$script
```

Ps: I normally use the report button in the extension popup itself, let me know if its better to report directly to the easylist repo

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="922" alt="Screenshot 2023-07-08 at 13 46 06" src="https://github.com/uBlockOrigin/uAssets/assets/138932214/1a378733-2575-4013-8bff-c00876962e99">
<img width="922" alt="Screenshot 2023-07-08 at 13 46 35" src="https://github.com/uBlockOrigin/uAssets/assets/138932214/8ef65470-0753-4d40-afb7-94d43c99246d">
<img width="932" alt="Screenshot 2023-07-08 at 13 46 24" src="https://github.com/uBlockOrigin/uAssets/assets/138932214/de1151df-f5bf-4b36-8295-98a7b7337c76">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b14
Chromium: 114
filterset (summary):
 network: 298591
 cosmetic: 227777
 scriptlet: 41883
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68799-103, 1h.20m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 351-9, 1h.20m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2236-2, 1h.20m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 42-0, 1h.20m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91945-21043, 1h.20m
  NOR-0: 3241-12, 1h.20m
  adguard-cookies: 26238-26238, 1h.20m
  adguard-generic: 72324-600, 1h.20m
  adguard-mobile: 8372-57, 1h.20m
  adguard-mobile-app-banners: 4403-4403, 1h.20m
  adguard-other-annoyances: 13052-13052, 1h.20m
  adguard-popup-overlays: 22911-22911, 1h.20m
  [17 lists not shown]: [too many]
 default:
  user-filters: 16-0, never
  easylist: 68110-1269, 1h.20m
  easyprivacy: 33415-16796, 1h.20m
  plowe-0: 3739-1572, 1h.20m
  ublock-badware: 7514-396, 1h.20m
  ublock-filters: 33875-3983, 1h.20m
  ublock-privacy: 430-67, 1h.20m
  ublock-quick-fixes: 280-19, 1h.20m
  ublock-unbreak: 2068-138, 1h.20m
  urlhaus-1: 6369-3, 1h.20m
filterset (user): [array of 15 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1961 ms (selfie)
 maxAssetCacheWait: 247 ms
popupPanel:
 blocked: 7
 network:
  nrk.no: 3
  google-analytics.com: 1
  k5a.io: 1
  medietall.no: 1
  tns-cs.net: 1
 extended:
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by stephenhawk8054** [comment]
> I normally use the report button in the extension popup itself, let me know if its better to report directly to the easylist repo

Yes, for normal filters, please report to EasyList repo
