### ISSUE TITLE
gaiakodi.com

### ISSUE THREAD

**Issue by gzenio22** [uBlockOrigin/uAssets#1888]
I have the impression that on this page smells a crypto miner could someone do a test? I warn you yesterday I entered this page and this morning my defender detected me bitcoinminner malwarebytes extra 2 XD

**Comment by WowDude** [comment]
I just forgot to tell him that he must fill the form: https://github.com/MajkiIT/polish-ads-filter/issues/6808#issuecomment-378642206

**Comment by okiehsch** [comment]
The high CPU usage is caused by the sites CSS as far as I can see, adding 
`||gaiakodi.com/resources/styles/*$stylesheet,first-party` fixes the high CPU usage.
It obviously also breaks the layout ;)

**Comment by gzenio22** [comment]
so is there any excavator script or I was wrong? because I do not know myself anymore

and I'm sorry I did not send in a list of filters
