### ISSUE TITLE
dagbladet.no: privacy

### ISSUE THREAD

**Issue by AdblockReporters** [uBlockOrigin/uAssets#18880]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dagbladet.no/`

### Category

privacy

### Description

Aller Media is a Norwegian company that runs a bunch of online newspapers. 
All who use an excessive and aggressive tracking and collection script

It is worth noting, if the tracking fails to post, it will fallback to the domain `aas.medialaben.no` and post all failed responses to a path on that subdomain. So that subdomain should also be blocked
```
const REPLAY_INTEVRAL_TIME = 180000 // three minutes, in milliseconds
const AAS_URL = 'https://aas.medialaben.no/a/'
```

Below is a list of domains they own that uses the aas tracker URL.

[Dagbladet](https://www.dagbladet.no/) - https://www.seher.no/app/aas/a
[Se og hør](https://www.seher.no/) - https://www.seher.no/app/aas/a
[kk](https://www.kk.no/) - https://www.kk.no/app/aas/a
[vi.no ](https://www.vi.no/) - https://www.vi.no/app/aas/a
[DinSide](https://dinside.dagbladet.no/) - https://dinside.dagbladet.no/app/aas/a
[SOL](https://sol.no/) - https://sol.no/app/aas/a
[kode24](https://www.kode24.no/) - https://www.kode24.no/app/aas/
[elbil24](https://www.elbil24.no/) - https://www.elbil24.no/app/aas/a
[børsen](https://borsen.dagbladet.no/) - https://borsen.dagbladet.no/app/aas/a
[lommelegen](https://www.lommelegen.no/) - https://www.lommelegen.no/app/aas/a

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="891" alt="Screenshot 2023-07-07 at 22 56 53" src="https://github.com/uBlockOrigin/uAssets/assets/138932214/d008b695-6f34-4efd-a721-2cd3ee247f88">
<img width="894" alt="Screenshot 2023-07-07 at 22 56 47" src="https://github.com/uBlockOrigin/uAssets/assets/138932214/7d397644-f07e-4830-a263-af7717a12d3f">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b14
Chromium: 114
filterset (summary):
 network: 298170
 cosmetic: 227764
 scriptlet: 41874
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68798-103, 7m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 351-9, 7m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2236-2, 7m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/RickrollLinkIdentifier.txt: 42-0, 7m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91943-21042, 7m
  NOR-0: 3236-12, 4m
  adguard-cookies: 26237-26237, 7m
  adguard-generic: 72317-600, 7m
  adguard-mobile: 8371-57, 7m
  adguard-mobile-app-banners: 4403-4403, 7m
  adguard-other-annoyances: 13052-13052, 7m
  adguard-popup-overlays: 22911-22911, 7m
  [17 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 67976-1262, 7m
  easyprivacy: 33411-16794, 7m
  plowe-0: 3739-1572, 7m
  ublock-badware: 7514-396, 7m
  ublock-filters: 33860-3976, 7m
  ublock-privacy: 427-67, 7m
  ublock-quick-fixes: 277-15, 7m
  ublock-unbreak: 2065-137, 7m
  urlhaus-1: 6568-2, 7m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1961 ms (selfie)
 maxAssetCacheWait: 247 ms
popupPanel:
 blocked: 7
 network:
  dagbladet.no: 3
  doubleclick.net: 1
  k5a.io: 1
  medietall.no: 1
  sentry-cdn.com: 1
 extended:
  ##.css-pp-box
  ##div[itemtype$="WPAdBlock"]
  ##.adunit-wrapper
  ##.adunit
  ##.native-advertisement:not(html,body)
  ##.adunit:upward(1)
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by AdblockReporters** [comment]
`https://www.dagbladet.no/blink-sw.js`, `https://borsen.dagbladet.no/blink-sw.js`, etc
has the code that offloads the tracking to a service workers. But the main .js file has code that falls back to not use a sw. So won't do much blocking the sw other than performance

**Comment by stephenhawk8054** [comment]
@DandelionSprout Sorry can you take a look? Does `Dandelion Sprouts nordiske filtre` list have tracker-blocking filters?

**Comment by DandelionSprout** [comment]
Not normally, although there is one precedence of me adding a tracker entry on request (https://github.com/DandelionSprout/adfilt/pull/699). I suppose I can try adding something like `.no/app/aas^` if I understand the OP correctly.

**Comment by stephenhawk8054** [comment]
Thanks. Looks like those are all beacons

```adb
/app/aas/a$beacon
```

@ryanbr

**Comment by AdblockReporters** [comment]
> Not normally, although there is one precedence of me adding a tracker entry on request ([DandelionSprout/adfilt#699](https://github.com/DandelionSprout/adfilt/pull/699)). I suppose I can try adding something like `.no/app/aas^` if I understand the OP correctly.

Hey! Yeah `.no/app/aas^` would work, also blocking the subdomain `aas.medialaben.no` could be smart to catch their fallback system

One could argue about blocking their blink script (blink is the name of the tracker) `no/blink-sw.js`, as that would prevent a useless tracking service worker sitting in the background

**Comment by stephenhawk8054** [comment]
In `https://www.lommelegen.no/`, the ping comes from `https://www.lommelegen.no/am-assets/scripts/app.min.js` so blocking `.no/blink-sw.js` does not stop it.

**Comment by AdblockReporters** [comment]
> In `https://www.lommelegen.no/`, the ping comes from `https://www.lommelegen.no/am-assets/scripts/app.min.js` so blocking `.no/blink-sw.js` does not stop it.

From my testing it does both.
On first time visiting the site it starts downloading `https://www.lommelegen.no/blink-sw.js` and registers a background service workers
That service worker sends a ping, while the app.min.js also sends a ping. in other words, 2x the network calls.
So if we could prevent the blink-sw script from being loaded on first visit we could half the blocked network traffick

Its worth to know to test it, you need to unregister the service worker, as when its first registered it wont call to download the blink-sw script again

<img width="903" alt="Screenshot 2023-07-08 at 12 03 58" src="https://github.com/uBlockOrigin/uAssets/assets/138932214/ce83df3a-52c3-46cc-9259-50e3fec4d191">
<img width="904" alt="Screenshot 2023-07-08 at 12 04 29" src="https://github.com/uBlockOrigin/uAssets/assets/138932214/6f8b5e1f-815c-47f9-8daa-67bcd23ac0dd">

**Comment by stephenhawk8054** [comment]
Yes, I did unregister service workers and block the service worker scripts, and I found it still comes from `app.min.js`
