### ISSUE TITLE
shop.mango.com: nuisance

### ISSUE THREAD

**Issue by xqtp** [uBlockOrigin/uAssets#18886]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shop.mango.com/gr`

### Category

nuisance

### Description

cookie notice

### Other extensions used

Bitwarden, Simple Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/103899764/6f4a64a6-644f-4c74-b7da-a63b4147d72d)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 29d.8h.19m
Chromium: 114
filterset (summary):
 network: 97320
 cosmetic: 131134
 scriptlet: 25745
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  GRC-0: 1018-0, now
  adguard-cookies: 26238-29, now
  adguard-mobile-app-banners: 4403-8, now
  adguard-other-annoyances: 13052-7, now
  adguard-popup-overlays: 22911-61, now
  adguard-social: 20862-877, now
  adguard-spyware-url: 1115-3, now
  adguard-widgets: 2195-3, now
  ublock-annoyances: 5315-182, now
 default:
  user-filters: 43-1, never
  TUR-0: 13586-11, now
  easylist: 68110-92, now
  easyprivacy: 33415-132, now
  ublock-badware: 7514-137, now
  ublock-filters: 33868-535, now
  ublock-privacy: 427-6, now
  ublock-quick-fixes: 278-17, now
  ublock-unbreak: 2068-38, now
filterset (user): [array of 52 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10762 ms (selfie)
 maxAssetCacheWait: 757 ms
popupPanel:
 blocked: 4
 network:
  mango.com: 2
  go-mpulse.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||shop.mango.com/st-cookies/$xhr,1p
```

@ryanbr @Alex-302
