### ISSUE TITLE
play.tv2.dk: detection

### ISSUE THREAD

**Issue by 69XBoXKid420** [uBlockOrigin/uAssets#18894]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.tv2.dk/`

### Category

detection

### Description

Website detects ublock, refuses to stream. No other plugins installed, firefox settings custom set to allow all kinds of tracking, cookies etc. Site is a Danish subscription based tv-network, might be hard to reproduce without an account?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 3d.19h.9m
Firefox: 115
filterset (summary):
 network: 96841
 cosmetic: 39386
 scriptlet: 17763
 html: 985
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 6d.4h.21m
 default:
  user-filters: 1-0, never
  ublock-filters: 34559-161, 19h.37m
  ublock-badware: 7516-0, 19h.37m
  ublock-privacy: 459-75, 6d.4h.21m
  ublock-unbreak: 2104-2, 19h.37m
  easylist: 67971-548, 3h.46m
  easyprivacy: 33415-768, 3h.45m
  urlhaus-1: 6568-0, 19h.37m
  plowe-0: 3738-2, 6d.4h.21m
  ublock-quick-fixes: 278-0, 3h.44m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4110 ms (selfie)
 maxAssetCacheWait: 3168 ms
popupPanel:
 blocked: 526
 network:
  tv2.dk: 1
  adobedtm.com: 3
  conviva.com: 519
  doubleclick.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by gorhill** [comment]
Did you try to see if enabling _Dandelion Sprouts nordiske filtre_ list makes a difference?

**Comment by 69XBoXKid420** [comment]
Sadly it doesn't :/

**Comment by stephenhawk8054** [comment]
Can you do these steps (follow strictly the step order, don't mix the steps orders, or skip any steps):

1. Click on uBO icon > &#9636; ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Go back to the site, press `Ctrl + Shift + R` (or `Cmd + Shift + R` on Mac) and repeat the steps until issue happens
3. Switch to the logger window that was opened in step 1
4. Copy the logger via &#128203; [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here

**Comment by mapx-** [comment]
@DandelionSprout are you able to test the page ?

@69XBoXKid420 If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by DandelionSprout** [comment]
TV 2 Play seems to be a paid service, so I likely can't help look into it either.

**Comment by stephenhawk8054** [comment]
```yml
imasdk.googleapis.com: 1
```

I suspect it could be

```adb
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect-rule=google-ima.js,domain=tv2.dk
```

but we need OP's feedback either way.

**Comment by 69XBoXKid420** [comment]
Hey, sorry for the late reply, been away for a couple of days. I sadly can't give the credentials, since it's a friends account I'm using and theres credit card details and stuff there :/

**Logs:** 

+5
play.tv2.dk
1
post
xhr
https://cl.play.tv2.dk/

+5
play.tv2.dk
3
get
image
https://sni.star.tv2i.dk.c.footprint.net/
aliasURL=https://cdn-play.tv2i.dk/769d3141-82dd-4e97-8c58-196d4b86e8e5.png?rect=0%2C0%2C3840%2C2160&ar=21%3A9&auto=format%2Ccompress&fit=crop&crop=top&w=768&dpr=1

+5
play.tv2.dk
3
get
image
https://cdn-play.tv2i.dk/769d3141-82dd-4e97-8c58-196d4b86e8e5.png?rect=0%2C0%2C3840%2C2160&ar=21%3A9&auto=format%2Ccompress&fit=crop&crop=top&w=768&dpr=1

+5
play.tv2.dk
3
get
image
https://sni.star.tv2i.dk.c.footprint.net/
aliasURL=https://cdn-play.tv2i.dk/5fa63839-b892-4a3b-8a2a-85713980a499.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+5
play.tv2.dk
3
get
image
https://cdn-play.tv2i.dk/5fa63839-b892-4a3b-8a2a-85713980a499.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://sni.star.tv2i.dk.c.footprint.net/
aliasURL=https://cdn-play.tv2i.dk/322502dd-56f9-42ab-aea0-a7af0720fb54.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://cdn-play.tv2i.dk/322502dd-56f9-42ab-aea0-a7af0720fb54.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://sni.star.tv2i.dk.c.footprint.net/
aliasURL=https://cdn-play.tv2i.dk/7287bad1-fc62-4f07-b133-6e50ebc00d73.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://cdn-play.tv2i.dk/7287bad1-fc62-4f07-b133-6e50ebc00d73.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://sni.star.tv2i.dk.c.footprint.net/
aliasURL=https://cdn-play.tv2i.dk/2f6beebf-0af2-4f03-9a1a-bc96b1ca696a.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://cdn-play.tv2i.dk/2f6beebf-0af2-4f03-9a1a-bc96b1ca696a.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://sni.star.tv2i.dk.c.footprint.net/
aliasURL=https://cdn-play.tv2i.dk/97b9a9f5-a35d-4641-86b2-ceaf5614efa6.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://cdn-play.tv2i.dk/97b9a9f5-a35d-4641-86b2-ceaf5614efa6.png?rect=0%2C0%2C3840%2C2160&auto=format%2Ccompress&w=375&dpr=1

+4
play.tv2.dk
3
get
image
https://sni.star.tv2i.dk.c.footprint.net/
aliasURL=https://cdn-play.tv2i.dk/97b9a9f5-a35d-4641-86b2-ceaf5614efa6.png?rect=0,0,3840,2160

+4
play.tv2.dk
3
get
image
https://cdn-play.tv2i.dk/97b9a9f5-a35d-4641-86b2-ceaf5614efa6.png?rect=0,0,3840,2160

+4
play.tv2.dk
3
post
xhr
https://license.theoplayer.com/

+4
||cws.conviva.com^
--
play.tv2.dk
3
post
xhr
https://912e694510fc7e9e8178ec27b8699a82d2689c3e.cws.conviva.com/0/wsg

+4
play.tv2.dk
1
get
image
https://play.tv2.dk/_next/static/media/icon_28_play_big.04abf611.svg

+4
play.tv2.dk
3
post
xhr
https://concurrency.play.tv2api.dk/concurrency

+4
noop.js
<<
imasdk.googleapis.com
3,3
get
xhr
https://pagead2.googlesyndication.com/gampad/ads?sz=640x360&iu=%2F19784602%2Ftv2-addressabletv%2FHVOD%2FBrowser&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&ad_rule=1&ppid=dba5b46fccb44ba5a8788ddb61668e8b&cust_params=guid%3D12815360%26title%3DHj%C3%A6lperytter%20i%20verdensklasse%26seriesGuid%3Dnull%26category%3DSport%26genre%3DCykling%26contentProvider%3DTV2SPORT%26platform%3DPLAY_WEB%26trace-id%3Ddba5b46fccb44ba5a8788ddb61668e8b%26ltd%3D1%26t2aid%3D&description_url=https%3A%2F%2Fplay.tv2.dk%2Fafspil%2Fbdadb917-0b0e-4c9d-9433-bffc2187509d%3Finittype%3DWatch%2Bnewest&ltd=1&vpa=auto&vpmute=0&sdkv=h.3.580.0&osd=2&frm=0&vis=1&sdr=1&hl=en&afvsz=200x200%2C250x250%2C300x250%2C336x280%2C450x50%2C468x60%2C480x70%2C728x90&is_amp=0&u_so=l&ctv=0&mpt=THEOplayer&mpv=2.87.0&sdki=445&ptt=20&adk=3769793789&sdk_apis=2%2C7%2C8&omid_p=Google1%2Fh.3.580.0&sid=0674FA54-1E84-47DE-843A-4F1BF2201911&nel=0&eid=44765701%2C44772139%2C44777649%2C44781409%2C44781753%2C44782991%2C44788275&url=https%3A%2F%2Fplay.tv2.dk%2Fafspil%2Fbdadb917-0b0e-4c9d-9433-bffc2187509d%3Finittype%3DWatch%2Bnewest&dlt=1689234065125&idt=2311&dt=1689234068785&correlator=2968537772355979&scor=1839289533344422&ged=ve4_td4_er0.0.150.300_vi0.0.681.1366_vp100_eb24168

+4
||pagead2.googlesyndication.com^$xhr,redirect-rule=noop.js
--
imasdk.googleapis.com
3,3
get
xhr
https://pagead2.googlesyndication.com/gampad/ads?sz=640x360&iu=%2F19784602%2Ftv2-addressabletv%2FHVOD%2FBrowser&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&ad_rule=1&ppid=dba5b46fccb44ba5a8788ddb61668e8b&cust_params=guid%3D12815360%26title%3DHj%C3%A6lperytter%20i%20verdensklasse%26seriesGuid%3Dnull%26category%3DSport%26genre%3DCykling%26contentProvider%3DTV2SPORT%26platform%3DPLAY_WEB%26trace-id%3Ddba5b46fccb44ba5a8788ddb61668e8b%26ltd%3D1%26t2aid%3D&description_url=https%3A%2F%2Fplay.tv2.dk%2Fafspil%2Fbdadb917-0b0e-4c9d-9433-bffc2187509d%3Finittype%3DWatch%2Bnewest&ltd=1&vpa=auto&vpmute=0&sdkv=h.3.580.0&osd=2&frm=0&vis=1&sdr=1&hl=en&afvsz=200x200%2C250x250%2C300x250%2C336x280%2C450x50%2C468x60%2C480x70%2C728x90&is_amp=0&u_so=l&ctv=0&mpt=THEOplayer&mpv=2.87.0&sdki=445&ptt=20&adk=3769793789&sdk_apis=2%2C7%2C8&omid_p=Google1%2Fh.3.580.0&sid=0674FA54-1E84-47DE-843A-4F1BF2201911&nel=0&eid=44765701%2C44772139%2C44777649%2C44781409%2C44781753%2C44782991%2C44788275&url=https%3A%2F%2Fplay.tv2.dk%2Fafspil%2Fbdadb917-0b0e-4c9d-9433-bffc2187509d%3Finittype%3DWatch%2Bnewest&dlt=1689234065125&idt=2311&dt=1689234068785&correlator=2968537772355979&scor=1839289533344422&ged=ve4_td4_er0.0.150.300_vi0.0.681.1366_vp100_eb24168

+4
||googlesyndication.com^
--
imasdk.googleapis.com
3,3
get
xhr
https://pagead2.googlesyndication.com/gampad/ads?sz=640x360&iu=%2F19784602%2Ftv2-addressabletv%2FHVOD%2FBrowser&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&ad_rule=1&ppid=dba5b46fccb44ba5a8788ddb61668e8b&cust_params=guid%3D12815360%26title%3DHj%C3%A6lperytter%20i%20verdensklasse%26seriesGuid%3Dnull%26category%3DSport%26genre%3DCykling%26contentProvider%3DTV2SPORT%26platform%3DPLAY_WEB%26trace-id%3Ddba5b46fccb44ba5a8788ddb61668e8b%26ltd%3D1%26t2aid%3D&description_url=https%3A%2F%2Fplay.tv2.dk%2Fafspil%2Fbdadb917-0b0e-4c9d-9433-bffc2187509d%3Finittype%3DWatch%2Bnewest&ltd=1&vpa=auto&vpmute=0&sdkv=h.3.580.0&osd=2&frm=0&vis=1&sdr=1&hl=en&afvsz=200x200%2C250x250%2C300x250%2C336x280%2C450x50%2C468x60%2C480x70%2C728x90&is_amp=0&u_so=l&ctv=0&mpt=THEOplayer&mpv=2.87.0&sdki=445&ptt=20&adk=3769793789&sdk_apis=2%2C7%2C8&omid_p=Google1%2Fh.3.580.0&sid=0674FA54-1E84-47DE-843A-4F1BF2201911&nel=0&eid=44765701%2C44772139%2C44777649%2C44781409%2C44781753%2C44782991%2C44788275&url=https%3A%2F%2Fplay.tv2.dk%2Fafspil%2Fbdadb917-0b0e-4c9d-9433-bffc2187509d%3Finittype%3DWatch%2Bnewest&dlt=1689234065125&idt=2311&dt=1689234068785&correlator=2968537772355979&scor=1839289533344422&ged=ve4_td4_er0.0.150.300_vi0.0.681.1366_vp100_eb24168

+4
play.tv2.dk
3
get
xhr
https://a1939.v.akamai.net/
aliasURL=https://tv2-play-vod-ew-aws-arn-dash.akamaized.net/__cl/s:s3storage/__c/video-origin/10193869/202307121931129tJtKv/720p-576/__op/cenc/__f/video_h264_600kbps/init.cmfv

+4
play.tv2.dk
3
get
xhr
https://tv2-play-vod-ew-aws-arn-dash.akamaized.net/__cl/s:s3storage/__c/video-origin/10193869/202307121931129tJtKv/720p-576/__op/cenc/__f/video_h264_600kbps/init.cmfv

+4
play.tv2.dk
3
get
xhr
https://a1939.v.akamai.net/
aliasURL=https://tv2-play-vod-ew-aws-arn-dash.akamaized.net/__cl/s:s3storage/__c/video-origin/10193869/202307121931129tJtKv/720p-576/__op/cenc/__f/audio_aac_eng_192kbps/init.cmfa

+4
play.tv2.dk
3
get
xhr
https://tv2-play-vod-ew-aws-arn-dash.akamaized.net/__cl/s:s3storage/__c/video-origin/10193869/202307121931129tJtKv/720p-576/__op/cenc/__f/audio_aac_eng_192kbps/init.cmfa

+4
||cws.conviva.com^
--
play.tv2.dk
3
post
xhr
https://912e694510fc7e9e8178ec27b8699a82d2689c3e.cws.conviva.com/0/wsg

+3
play.tv2.dk
1
get
image
https://play.tv2.dk/_next/static/media/pause_18x18.151b78a5.svg

+3
play.tv2.dk
3
get
xhr
https://static-konstrukt.prod.streaming.tv2net.dk/content/10193869/101304409-thumbnails-lb5TtQ/timeline.vtt

+3
#@#div[id^="div-gpt-"]
play.tv2.dk
post
dom
https://play.tv2.dk/afspil/bdadb917-0b0e-4c9d-9433-bffc2187509d?inittype=Watch+newest

+3
#@#[id^="div-gpt-ad"]
play.tv2.dk
post
dom
https://play.tv2.dk/afspil/bdadb917-0b0e-4c9d-9433-bffc2187509d?inittype=Watch+newest

+3
##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"])
play.tv2.dk
post
dom
https://play.tv2.dk/afspil/bdadb917-0b0e-4c9d-9433-bffc2187509d?inittype=Watch+newest

+3
##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"])
play.tv2.dk
post
dom
https://play.tv2.dk/afspil/bdadb917-0b0e-4c9d-9433-bffc2187509d?inittype=Watch+newest

+3
play.tv2.dk
1
options
xhr
https://cl.play.tv2.dk/

+3
play.tv2.dk
3
get
xhr
https://a1939.v.akamai.net/
aliasURL=https://tv2-play-vod-ew-aws-arn-dash.akamaized.net/__cl/s:s3storage/__c/video-origin/10193869/202307121931129tJtKv/720p-576/__op/cenc/__f/single.mpd

+3
play.tv2.dk
3
get
xhr
https://tv2-play-vod-ew-aws-arn-dash.akamaized.net/__cl/s:s3storage/__c/video-origin/10193869/202307121931129tJtKv/720p-576/__op/cenc/__f/single.mpd

+3
play.tv2.dk
1
post
xhr
https://cl.play.tv2.dk/

+3
play.tv2.dk
3
get
image
https://sni.star.tv2i.dk.c.footprint.net/
aliasURL=https://cdn-play.tv2i.dk/97b9a9f5-a35d-4641-86b2-ceaf5614efa6.png?rect=0,0,3840,2160?auto=format

+3
play.tv2.dk
3
get
image
https://cdn-play.tv2i.dk/97b9a9f5-a35d-4641-86b2-ceaf5614efa6.png?rect=0,0,3840,2160?auto=format

+3
play.tv2.dk
3
post
xhr
https://play.tv2api.dk/

+3
play.tv2.dk
3
options
xhr
https://play.tv2api.dk/

+3
play.tv2.dk
3
post
xhr
https://play.tv2api.dk/

+2
||googlesyndication.com^
--
play.tv2.dk
3
get
script
https://pagead2.googlesyndication.com/omsdk/releases/live/omweb-v1.js

+2
play.tv2.dk
1
get
image
https://play.tv2.dk/_next/static/media/icon_16_episodes.0a9e4f2e.svg

+2
play.tv2.dk
1
get
image
https://play.tv2.dk/_next/static/media/icon_16_forward.f4b571b6.svg

+2
play.tv2.dk
1
get
image
https://play.tv2.dk/_next/static/media/icon_16_rewind.7a2827af.svg

+2
play.tv2.dk
1
get
image
https://play.tv2.dk/_next/static/media/icon_16_fullscreen.11e53c48.svg

+2
play.tv2.dk
1
get
image
https://play.tv2.dk/_next/static/media/icon_16_volumefull.53ec7469.svg

+2
play.tv2.dk
1
get
image
https://play.tv2.dk/_next/static/media/play_18x18.391db280.svg

+2
@@||imasdk.googleapis.com/js/core/bridge*.html$frame,from=~spotify.com
++
play.tv2.dk
3
get
frame
https://imasdk.googleapis.com/js/core/bridge3.580.0_da.html#goog_1705758624

+2
@@||imasdk.googleapis.com/js/core/bridge*.html$frame,from=~spotify.com
++
play.tv2.dk
3
get
frame
https://imasdk.googleapis.com/js/core/bridge3.580.0_da.html#goog_1705758624

+2
||2mdn.net^
--
play.tv2.dk
3
get
script
https://s0.2mdn.net/instream/video/client.js

+2
@@||imasdk.googleapis.com/js/core/bridge*.html$frame,from=~spotify.com
++
play.tv2.dk
3
get
frame
https://imasdk.googleapis.com/js/core/bridge3.580.0_da.html#goog_1705758624

+2
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/450.af1f650f4954db00.js

+2
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/797.e565a029eeaf2250.js

+2
play.tv2.dk
1
get
css
https://play.tv2.dk/_next/static/css/56aab47d55c7518a.css

+2
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/779.5800bf7602dd9bc4.js

+2
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/102.b79a3c08c7bebf6b.js

+1
play.tv2.dk
3
post
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/assets/yospace/yo-ad-management.min.js

+1
@@://imasdk.googleapis.com/js/sdkloader/ima3.js^$from=tv2.dk
++
play.tv2.dk
3
get
script
https://imasdk.googleapis.com/js/sdkloader/ima3.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/assets/adobe/3.0.2/MediaSDK.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/assets/streamroot/theoplayer-dna-wrapper.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/assets/theoplayer/2.87/THEOplayer.js

+1
play.tv2.dk
1
get
css
https://play.tv2.dk/assets/theoplayer/2.87/ui.css

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/834.a3107d5210d346be.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/15-81651a8427cc3a3f.js

+1
play.tv2.dk
1
get
css
https://play.tv2.dk/_next/static/css/bda0c611bdc89661.css

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/332-dc44f1fbe832d124.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/811-559e604f4751c88f.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/404-e71fbe8ae692a982.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/687-d6fcdd9ff1deacef.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/117-f7d82c83995d8b02.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/780-1ad01eb87ae16b90.js

+1
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/325-72ef705b7dfbbf36.js

+1
play.tv2.dk
3
options
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
options
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
options
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
options
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
options
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
post
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
post
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
post
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
post
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
3
post
xhr
https://play.tv2api.dk/

+1
play.tv2.dk
1
get
image
https://play.tv2.dk/favicon.ico

+1
||adobedtm.com^$3p,from=~adobe.com
--
play.tv2.dk
3
get
script
https://assets.adobedtm.com/fd32014b2e72/9232b216e6cb/88fd9af238fc/RCfa1786a325914a729b607606ee9d2ca6-source.min.js

+1
play.tv2.dk
3
get
font
https://assets.play.tv2a.dk/fonts/TV2.woff2

+1
play.tv2.dk
1
get
xhr
https://play.tv2.dk/api/user

+1
play.tv2.dk
1
get
xhr
https://status.ovp.tv2.dk/status/open/play_web

+1
googletagmanager_gtm.js
<<
play.tv2.dk
3
get
script
https://www.googletagmanager.com/gtag/js?id=AW-865971020&l=gtm_datalayer

+1
||googletagmanager.com/gtag/js$script,redirect-rule=googletagmanager_gtm.js:5
--
play.tv2.dk
3
get
script
https://www.googletagmanager.com/gtag/js?id=AW-865971020&l=gtm_datalayer

+1
||googletagmanager.com^
--
play.tv2.dk
3
get
script
https://www.googletagmanager.com/gtag/js?id=AW-865971020&l=gtm_datalayer

+0
||adobedtm.com^$3p,from=~adobe.com
--
play.tv2.dk
3
get
script
https://assets.adobedtm.com/extensions/EPbf7b42aa08bc4f10879b1484195e80d1/AppMeasurement_Module_ActivityMap.min.js

+0
||adobedtm.com^$3p,from=~adobe.com
--
play.tv2.dk
3
get
script
https://assets.adobedtm.com/extensions/EPbf7b42aa08bc4f10879b1484195e80d1/AppMeasurement.min.js

+0
/nielsen.js
--
play.tv2.dk
1
get
script
https://play.tv2.dk/assets/nielsen.js

+0
@@||adobedtm.com/launch-$script
++
play.tv2.dk
3
get
script
https://assets.adobedtm.com/launch-EN40f12c6683a24d59bb7d82e23518c280.min.js

+0
/nielsen.js
--
play.tv2.dk
1
get
script
https://play.tv2.dk/assets/nielsen.js

+0
googletagservices_gpt.js
<<
play.tv2.dk
3
get
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js

+0
||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect-rule=googletagservices_gpt.js:5
--
play.tv2.dk
3
get
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js

+0
||doubleclick.net^
--
play.tv2.dk
3
get
script
https://securepubads.g.doubleclick.net/tag/js/gpt.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/2023.7.712115/_ssgManifest.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/2023.7.712115/_buildManifest.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/pages/PlayerPage-613af79f39ff16c8.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/574-009a68ec815cc086.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/498-66e919f0eafec1db.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/pages/_app-4e8a44c39e95b17f.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/main-90598bb0a8b621d7.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/framework-2ea7724c2b33e43b.js

+0
play.tv2.dk
1
get
script
https://play.tv2.dk/_next/static/chunks/webpack-6c451407e388a91a.js

+0
play.tv2.dk
1
get
css
https://play.tv2.dk/_next/static/css/440d60b57864bfe0.css

+0
play.tv2.dk
1
get
doc
https://play.tv2.dk/afspil/bdadb917-0b0e-4c9d-9433-bffc2187509d?inittype=Watch+newest

+0
https://play.tv2.dk/afspil/bdadb917-0b0e-4c9d-9433-bffc2187509d?inittype=Watch+newest

**Comment by 69XBoXKid420** [comment]
Sorry that the log is so insanely long, just loaded the page one single time, so idk :/

**Comment by mapx-** [comment]
@stephenhawk8054 

dk list already has
`@@://imasdk.googleapis.com/js/sdkloader/ima3.js^$domain=tv2.dk`

@69XBoXKid420 sadly .. we cannot investigate further

**Comment by mapx-** [comment]
@69XBoXKid420 
if you get your friend's consent to provide the necessary information (I guess a temp account branch / guest stuff could be created in the main account)  just add a new comment here. 

Closing for now.
