### ISSUE TITLE
A like button bug 

### ISSUE THREAD

**Issue by RobertBobby007** [uBlockOrigin/uAssets#18890]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The like ikon doesn't show.

### URL(s) where the issue occurs.

https://search.seznam.cz/?q=Emma+Smetana&aq=3&ctx=sypLiBJqLL3IVIT1njoiB0ef-zfTvN8r7-tXsdWQeYNjY_sS2qSPk1IYq3B07L0Lio0vXD7kgHzrPjSIkAaRGw&sourceid=szn-HP&thru=search-promo

www.seznam.cz

### Screenshot(s)

<img width="471" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/72411188/da4c2b1a-6afd-4607-b82b-a9bcc533b055">
<img width="65" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/72411188/180cf22c-38f5-422c-bc3a-6db636f88acf">

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 3m
Chromium: 114
filterset (summary):
 network: 97053
 cosmetic: 39782
 scriptlet: 18100
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CZE-0: 744-1, 1m
  easylist: 68113-12, 1m
  easyprivacy: 33417-68, 1m
  plowe-0: 3739-1073, 1m
  ublock-badware: 7514-138, now
  ublock-filters: 33880-148, now
  ublock-privacy: 428-4, now
  ublock-quick-fixes: 278-19, now
  ublock-unbreak: 2068-34, now
  urlhaus-1: 6403-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 926 ms
 maxAssetCacheWait: 12 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue in the old issue thread. We are all informed with new comments.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e6d7040e214aa42e5f936f30f76f315bc558b4f7
