### ISSUE TITLE
serialy.io: unneeded filters

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18895]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

These are the filters which I think aren't needed in uBlock filters anymore:
`@@||serialy.io^$script,1p`
`serialy.io#@#[id^="etarget"]`
`ignobleinnovationcollateral.com##+js(window-close-if, /^/)`
`serialy.io##+js(set, currentAd, 3)`
`serialy.io` redirects to a different site, while `ignobleinnovationcollateral.com` just redirects to Google. (Likely an ad server judging by that alone.)

### URL(s) where the issue occurs.

`https://serialy.io`
`https://ignobleinnovationcollateral.com`

### uBO version

v1.50.1b15

### Browser name and version

Firefox 115.0.1

### Settings

- Use custom filters, checked "I am an advanced user".

**Comment by stephenhawk8054** [comment]
The original issue is this: https://github.com/uBlockOrigin/uAssets/issues/15091

Can you access the link in that thread?

**Comment by Sonic5435325** [comment]
The link seems to once again redirect. This time, to `https://sledujhentai.com/episode/harem-in-the-labyrinth-of-another-world-s01e12`.
