### ISSUE TITLE
[NSFW] startpage.com: ads

### ISSUE THREAD

**Issue by SakhJack** [uBlockOrigin/uAssets#18897]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

making NSFW related search shows AD for `totaladblock.com` as first result

### URL(s) where the issue occurs.

`https://www.startpage.com/sp/search?query=pornhub`

### Screenshot(s)

<details><summary>Screenshots</summary>
  
![image](https://github.com/uBlockOrigin/uAssets/assets/10335530/ab36560a-ab53-4515-9597-aab23bdb656d)
</details>

### uBO version

1.50.0

### Browser name and version

Firefox 115.0.1 (x64)

### Settings

default settings

### Notes

resolved by making  filter 
`startpage.com###total-adblock-adult`

**Comment by Sonic5435325** [comment]
Or:
`startpage.com##.rc-qi`

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site? 

Also, can you go to the page that has issue > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by JobcenterTycoon** [comment]
@stephenhawk8054 can confirm from germany. It can only be reproduced after safe search got disabled because its enabled by default.

**Comment by iam-py-test** [comment]
I can confirm in Firefox from the US. Blocking that TotalAdBlock script seems to get rid of the ad
