### ISSUE TITLE
uploadhaven.com: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18896]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

15 second wait on download.

### URL(s) where the issue occurs.

`https://uploadhaven.com/download/da1eae036c02a5094e3da87fa76adf6c`

### uBO version

v1.50.1b15

### Browser name and version

Firefox 115.0.1

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by Sonic5435325** [comment]
`https://steamunlocked.net/sonic-adventure-2-free-download/`
It'll bring you to the site once you click the green download button.

**Comment by okiehsch** [comment]
> Session expired, please try again

That means that the timer is validated on the server site.
We can't fix that.
