### ISSUE TITLE
Block GitHub's hydro_browser_events enpoint

### ISSUE THREAD

**Issue by brodock** [uBlockOrigin/uAssets#1889]
### URL(s) where the issue occurs

* `https://github.com/uBlockOrigin/uAssets/issues/new` (any github issue/PR comment page)

### Describe the issue

`https://github.com/hydro_browser_events?timestamp=000&hmac=XYZ`

When hovering the mouse over avatars in GitHub they are sending usage pings to internal analytics endpoint: `https://github.com/hydro_browser_events`. There is probably other places where this is being used, judging by how generic the endpoint and the payload is.

For this particular example they send an unique `HMAC` + `timestamp` as querystring and other information as json post data:

event_type | user-hovercard-hover
-- | --
payload | {…}
client_id | 00000.00000
originating_request_id | xxxx:xxxx:xxxxxxx:xxxxxxx:xxxxxxxx (HEX)
subject |  
user_id | 00000
userId | 000000

### Versions

- Browser/version: Firefox Quantum 59.0.2 (64-bit)
- uBlock Origin version: v1.15.24

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by brodock** [comment]
:point_up added manually to my blocklist, working fine!

**Comment by WowDude** [comment]
@brodock 

Read [the Readme of this repo](https://github.com/uBlockOrigin/uAssets), in short: 
- easy to block things that can be blocked by ADP syntax goes into EasyList / EasyPrivacy
- harder to block things that can be only blocked by uBO filters goes into uBlock filters

And as for now (writing this comment), the filter: `||github.com/hydro_browser_events` has been already added to EasyPrivacy.

**Comment by brodock** [comment]
@WowDude yeah I sent there, sorry for the noise here.
