### ISSUE TITLE
new youtube ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#189]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

1. every youtube video
2. eg 
`https://www.youtube.com/watch?v=TkYx5-CKFDg`
## Describe the issue

1. go to above url

2. go to end of video i.e last 4-5 seconds you will see ads (other unrelated videos)

3. youtube doesn't give option to cancel these ads

### Screenshot(s)

![screenshot 49](https://cloud.githubusercontent.com/assets/20338483/20245137/9b43f18c-a9c0-11e6-97e9-0d6641b1ec85.png)

### Versions

- Browser/version: Version 54.0.2840.99 m (64-bit)

- uBlock Origin version: 1.9.16

### Settings

- uBO's default settings + antiadblock killer +adblock warning removal list + youtube pure video experience

### Notes

unrelated videos pushed in original video at the end

**Comment by gotitbro** [comment]
They are not ads, this is a new feature by **YouTube** which lets **_uploaders/creators_** embed other videos in their own video, it is called **End Screens**.

**Read more:**
> https://youtube-creators.googleblog.com/2016/10/keep-em-watching-with-end-screens.html
> https://support.google.com/youtube/answer/6388789?hl=en
> https://techcrunch.com/2016/10/26/youtube-launches-mobile-friendly-end-screens-feature-to-keep-viewers-watching-more-video/

In this case the videos were put there by **SET India** when they uploaded the video. This is how you add them https://www.youtube.com/watch?v=Q4dYiyCg6q8.

@gorhill Invalid issue, please close.

**Comment by gorhill** [comment]
Self-promotion, and at the end of the video, and last for 5 seconds, and as per @gotitbro comment, this must be considered part of the video.

**Comment by ghajini** [comment]
Sorry guys

**Comment by ghajini** [comment]
anyone suggest filter so that i can add them as manual filter

**Comment by mapx-** [comment]
test
`||youtube.com/*/endscreen.js$script`
or
`youtube.com##.ytp-endscreen-content`

**Comment by ghajini** [comment]
not work sir

**Comment by mapx-** [comment]
weird, working for me

**Comment by smed79** [comment]
```
||youtube.com/*/endscreen.js
```
Is working for me too.

@ghajini test again with
```
||youtube.com/get_endscreen?
||youtube.com/yts/*/endscreen.js
```
(https://forums.lanik.us/viewtopic.php?p=109737#p109737)

**Comment by ghajini** [comment]
Link=
`https://youtu.be/6wNFJlbTxNk`

@mapx- 
What is latest filter working for end-screens?

**Comment by mapx-** [comment]
still working on my end
`youtube.com##.ytp-endscreen-content`

**Comment by ghajini** [comment]
youtube.com##.ytp-endscreen-content filter not work on my side, I still see end-screens

https://user-images.githubusercontent.com/20338483/96496805-5613c600-1267-11eb-8ec9-bca49560d99d.jpg

https://user-images.githubusercontent.com/20338483/96496821-5b711080-1267-11eb-932c-6fb8279cfeda.jpg

**Comment by uBlock-user** [comment]
`||youtube.com^*/annotations_module.js$script`

or

`||youtube.com^*/endscreen.js$script`

**Comment by ghajini** [comment]
I'll go with
`||youtube.com^*/annotations_module.js$script`
👍

**Comment by ghajini** [comment]
Both filters not work,
`www.youtube.com/watch?v=HP0LUYgJQEI`

**Comment by uBlock-user** [comment]
I use both and they work on every video including the one you posted above, look what's overriding them via the logger.

**Comment by smed79** [comment]
**End Screen**

```
||s.ytimg.com^*/endscreen.js
||youtube.com^*/endscreen.js
||youtube-nocookie.com^*/endscreen.js
```
or
```
/endscreen.js$domain=youtube.com|youtube-nocookie.com
```

**Annotations**

```
||s.ytimg.com/yts/*/annotations_module.js
||youtube.com/yts/*/annotations_module.js
||youtube-nocookie.com/yts/*/annotations_module.js
```
or
```
/annotations_module.js$domain=youtube.com|youtube-nocookie.com
```
