### ISSUE TITLE
verasoul.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18907]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://verasoul.com/`

### Category

Detection

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/afba6c1a-4ca1-4f59-81bf-dc98079e040b)

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 22d.9h.25m
Chromium: 114
filterset (summary):
 network: 130049
 cosmetic: 135845
 scriptlet: 25075
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9300-4, 6h.17m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 6h.17m
  DEU-0: 6937-0, 6h.17m
  FRA-0: 28277-65, 6h.17m
  IDN-0: 9527-375, 6h.17m
  ara-0: 2326-9, 6h.17m
  easylist-annoyances: 3892-42, 6h.17m
  easylist-chat: 129-0, 6h.17m
  easylist-newsletters: 6256-15, 6h.17m
  easylist-notifications: 2634-85, 6h.17m
  fanboy-cookiemonster: 47703-221, 6h.17m
  fanboy-social: 16091-16, 6h.17m
  [1 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 67969-289, 6h.17m
  easyprivacy: 33417-442, 6h.17m
  plowe-0: 3739-1087, 6h.17m
  ublock-badware: 7525-157, 6h.17m
  ublock-filters: 33869-413, 6h.17m
  ublock-privacy: 428-7, 6h.17m
  ublock-quick-fixes: 278-19, 6h.17m
  ublock-unbreak: 2068-45, 6h.17m
  urlhaus-1: 6355-1, 6h.17m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1768 ms (selfie)
 maxAssetCacheWait: 466 ms
popupPanel:
 blocked: 8
 network:
  google.com: 3
  googlesyndication.com: 1
  googletagmanager.com: 2
  optimole.com: 2
 extended:
  ##.fa-cookie
  ##.header-social-list
  ##.social-link-facebook
  ##.social-link-twitter
  ##.social-link-pinterest
  ##.sponsor-inner
  ##.sponsor-link
  ##.newsletter-inner
  ###cmplz-cookiebanner-container
  ##.cookie-statement
  ###back-top
  ##[id^="google_ads_iframe"]
```
</details>

**Comment by okiehsch** [comment]
@Yuki2718 
`verasoul.com##+js(nostif, placebo)`
for the regional spanish list.

**Comment by stephenhawk8054** [comment]
I think this would be fixed in Adguard's Base list like https://github.com/AdguardTeam/AdguardFilters/issues/153189 instead of regional.

**Comment by Yuki2718** [comment]
Is this a popular anti-adb? Anyway, it seems this anti-adb is fixed individually in AG repo, so I can fix in Spanish list.

**Comment by stephenhawk8054** [comment]
Ah I see, you can fix in the region list, and I'll remove the fix in our list.

**Comment by Yuki2718** [comment]
I don't know how popular they are, but generic fix is possible:
```
#@#[id^="google_ads_iframe"]
##[id^="google_ads_iframe"]:not(.rb-adbanner)
```
