### ISSUE TITLE
ladbrokes.com.au: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#18905]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When uBlock Origin is enabled, some images on the page do not load.
I've included screenshots and the logs for when uBlock is enabled and disabled also.

### URL(s) where the issue occurs.

`https://www.ladbrokes.com.au/promotions`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/20948631/6f6f7283-8239-40b1-bb05-021a4d64d6af

https://github.com/uBlockOrigin/uAssets/assets/20948631/eecfc7d8-c1f7-4214-a60d-73c0298a5a93

[Filtered.txt](https://github.com/uBlockOrigin/uAssets/files/11995199/Filtered.txt)

[Unfiltered.txt](https://github.com/uBlockOrigin/uAssets/files/11995200/Unfiltered.txt)

### uBO version

uBlock Origin 1.50.0

### Browser name and version

Google Chrome 114.0.5735.199 (x64)

### Settings

```yaml
uBlock Origin 1.50.0:
 since: 28d.9h.21m
Chromium: 114
filterset (summary):
 network: 347841
 cosmetic: 218744
 scriptlet: 41618
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68801-103, 8m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 59314-0, 8m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91955-21042, 8m
  adguard-cookies: 26238-26238, never
  adguard-generic: 72334-6317, never
  adguard-mobile-app-banners: 4403-4403, never
  adguard-other-annoyances: 13053-13053, 8m
  adguard-popup-overlays: 22911-22911, 8m
  adguard-social: 20862-1535, 8m
  adguard-spyware: 60310-348, 8m
  adguard-widgets: 2196-2196, 8m
  block-lan: 47-0, 8m
  [11 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  easylist: 67969-379, 8m
  easyprivacy: 33417-16699, 8m
  plowe-0: 3739-1511, 8m
  ublock-badware: 7521-173, 8m
  ublock-filters: 33879-591, 8m
  ublock-privacy: 428-63, 8m
  ublock-quick-fixes: 291-19, 8m
  ublock-unbreak: 2070-81, 8m
filterset (user): [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2408 ms
 maxAssetCacheWait: 1326 ms
```

**Comment by stephenhawk8054** [comment]
```adb
@@||cdn.evergage.com/promotions/$image,domain=ladbrokes.com.au
```

@ryanbr

**Comment by TesterMan247** [comment]
I just updated all my lists and the issue remains.
Will the lists be updated soon?

**Comment by TesterMan247** [comment]
I just did so again. Still no good.

**Comment by stephenhawk8054** [comment]
Ah, I didn't realize the blocked domain is in Peter Lowe's list too

**Comment by stephenhawk8054** [comment]
You can force update all your filter lists in about 10 minutes again.

**Comment by TesterMan247** [comment]
I really don't know what's going on. I just updated all again and still no good.....

**Comment by stephenhawk8054** [comment]
I just updated all the lists again and all the images appear correctly for me. Screenshot: https://github.com/uBlockOrigin/uAssets/assets/66517106/e2d1dcab-7a67-49d1-9813-26d9df5cf2a6

Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

As I cannot reproduce the issue this time, I can't help you more.

**Comment by TesterMan247** [comment]
The issue is in other filters also.
For example, when I enable AdGuard Tracking Protection filter, it comes with that. However, if I then disable then, and then it moves to EasyPrivacy.
Its obvious the entry evergage.com is in other filters and since several filters contain the same entry, it moves from list to list because the same entry from several lists is only picked up once, if you guys can understand what I'm saying....
See screenshot here: 
![list](https://github.com/uBlockOrigin/uAssets/assets/20948631/d054d4e4-6069-4cce-be4a-4e13d302d25a)

**Comment by TesterMan247** [comment]
After enabling and disabling each filter and updating individually and checking, I found the entry "evergage.com" in the following filter lists in multiple spots:
AdGuard Tracking Protection
EasyPrivacy
Peter Lowe’s Ad and tracking server list

**Comment by stephenhawk8054** [comment]
My fix above in unbreak list is to disable the filter in Peter Lowe list. Did you force update the filter lists yet? `evergage.com` is no longer blocked by Peter Lowe list

EasyPrivacy already fixes it above: https://github.com/easylist/easylist/commit/0fef0ecad00b8086c5cd0aa1ff208baeddf1bbb5

So the issue is fixed with default settings (including EasyPrivacy already).

If it's any other lists than default lists, please report to their corresponding repository. For example, for Adguard Tracking Protection: https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by TesterMan247** [comment]
Thanks for that.
I disabled the Adguard Tracking Protection filter altogether.
That's just for tracers right?
It doesn't block any ads and won't really be missed right?
