### ISSUE TITLE
south-park-tv.biz: detection

### ISSUE THREAD

**Issue by Shley5804** [uBlockOrigin/uAssets#18906]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.south-park-tv.biz/`

### Category

detection

### Description

ublock origin est détecté sur le site

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1271" alt="Capture d’écran 2023-07-09 114205" src="https://github.com/uBlockOrigin/uAssets/assets/139063963/9be06e26-a057-45da-a441-fd5027f9b5bb">

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 24d.16h.15m
Chromium: 114
filterset (summary):
 network: 114640
 cosmetic: 48424
 scriptlet: 18062
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 28277-33, 4m
  easylist: 68017-262, 4m
  easyprivacy: 33417-341, 4m
  plowe-0: 3739-1086, 4m
  ublock-badware: 7521-155, 4m
  ublock-filters: 33881-225, 4m
  ublock-privacy: 428-5, 4m
  ublock-quick-fixes: 292-19, 4m
  ublock-unbreak: 2070-38, 4m
  urlhaus-1: 5855-1, 4m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 347 ms (selfie)
 maxAssetCacheWait: 149 ms
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 4
```
</details>

**Comment by JobcenterTycoon** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
CHP fix will go Base, we need our own fix.
