### ISSUE TITLE
investing.com: ads

### ISSUE THREAD

**Issue by ebaydan777** [uBlockOrigin/uAssets#18909]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

investing.com pop-up is showing due to ad blocked

### URL(s) where the issue occurs.

https://i.imgur.com/8ps32PF.png

### Screenshot(s)

https://i.imgur.com/8ps32PF.png

### Configuration

config

**Comment by gorhill** [comment]
Use the _chat_ icon in the popup panel to report issues, we are missing way to much information in this report to be actionable.
