### ISSUE TITLE
[nsfw] fap-nation.org: detection

### ISSUE THREAD

**Issue by BreathHolder** [uBlockOrigin/uAssets#18914]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fap-nation.org/`

### Category

detection

### Description

Overlay appears with the following note:

Ads Blocker Detected!!!

We have detected that you are using extensions to block ads. Please support us by disabling these ads blocker.

### Other extensions used

None. All other disabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
[https://i.imgur.com/dgljFUc.png](https://i.imgur.com/dgljFUc.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 26d.9h.55m
Firefox: 115
filterset (summary):
 network: 93636
 cosmetic: 39330
 scriptlet: 17881
 html: 986
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 34717-55, 2d.21h.33m
  ublock-badware: 7527-0, 17h.58m
  ublock-privacy: 460-0, 6d.9h.48m
  ublock-unbreak: 2102-0, 2d.21h.32m
  easylist: 67610-739, 5d.19h.44m
  easyprivacy: 30710-719, 5d.19h.46m
  urlhaus-1: 6355-1, 13h.56m
  plowe-0: 3739-2, 9d.10h
  ublock-quick-fixes: 280-2, 5h.55m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1442 ms (selfie)
 maxAssetCacheWait: 374 ms
popupPanel:
 blocked: 14
 network:
  adshrink.it: 1
  d3mzokty951c5w.cloudfront.net: 1
  displayvertising.com: 1
  ggxyyalrj.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  lvnmzhhod.com: 1
  wesmallproclaim.com: 4
  wp.com: 2
 extended:
  ##.td-a-ad
  ##.td-adspot-title
```
</details>

**Comment by rakleed** [comment]
Fake download buttons on `https://fap-nation.org/long-story-short-free-download/`, see https://github.com/uBlockOrigin/uAssets/issues/27445
