### ISSUE TITLE
tonanmedia.my.id: detection

### ISSUE THREAD

**Issue by T-Baniza** [uBlockOrigin/uAssets#18915]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tonanmedia.my.id/2023/06/novel-visual-terkenal-dari-key-summer.html?m=1`

### Category

detection

### Description

this is shortlink.

detection doesn't happen when I disabled cosmetic filtering.

NB. I checked the 'Ignore generic cosmetic filter'

### Other extensions used

none

### Screenshot(s)

<details><summary>Screenshot(s)</summary>

![IMG_20230710_051841](https://github.com/uBlockOrigin/uAssets/assets/79722529/85f620d5-7241-4e52-baff-19d2d865aa3b)
![Screenshot_2023-07-10-05-20-45-91](https://github.com/uBlockOrigin/uAssets/assets/79722529/3b644cd1-5153-47c2-85b4-47eee243eeae)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4m
Firefox Mobile: 115
filterset (summary):
 network: 101871
 cosmetic: 31051
 scriptlet: 17959
 html: 993
listset (total-discarded, last-updated):
 added:
  IDN-0: 9527-3835, never
 default:
  user-filters: 0-0, never
  ublock-filters: 35051-313, 4m
  ublock-badware: 7532-1, 4m
  ublock-privacy: 469-1, 4m
  ublock-unbreak: 2116-1, 4m
  ublock-quick-fixes: 347-0, 4m
  adguard-mobile: 8372-121, 4m
  easylist: 68094-17488, 4m
  easyprivacy: 33421-735, 4m
  urlhaus-1: 5855-1, 4m
  plowe-0: 3739-1, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4874 ms
 maxAssetCacheWait: 21 ms
popupPanel:
 blocked: 16
 network:
  google.com: 12
  inklinkor.com: 1
  udbaa.com: 3
 extended:
  ##ins.adsbygoogle
  ##+js(set-constant, setTimer, 0)
  ##+js(nano-setInterval-booster)
  ##+js(set-constant, showAds, true)
```
</details>

**Comment by gorhill** [comment]
This can be fixed in ABP Indo, report to them: <https://github.com/ABPindo/indonesianadblockrules>.
