### ISSUE TITLE
pandasnovel.com: detection

### ISSUE THREAD

**Issue by awolhacks** [uBlockOrigin/uAssets#18916]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pandasnovel.com/library`

### Category

detection

### Description

website detects ad blocker

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 26d.12h.8m
Firefox: 115
filterset (summary):
 network: 96804
 cosmetic: 39437
 scriptlet: 17901
 html: 989
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34758-170, 22h.51m
  ublock-badware: 7527-1, 22h.51m
  ublock-privacy: 469-0, 22h.51m
  ublock-unbreak: 2108-2, 22h.51m
  ublock-quick-fixes: 278-0, 22h.51m
  easylist: 68126-549, 22h.51m
  easyprivacy: 33417-770, 22h.51m
  urlhaus-1: 6355-1, 22h.50m
  plowe-0: 3739-1, 22h.50m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 114 ms (selfie)
 maxAssetCacheWait: 41 ms
popupPanel:
 blocked: 6
 network:
  pandasnovel.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 2
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists and test again?

**Comment by awolhacks** [comment]
Working now thanks

**Comment by stephenhawk8054** [comment]
Please follow what you have ticked on truthfully

> - [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
