### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by ebaydan777** [uBlockOrigin/uAssets#18917]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.investing.com/indices/indices-futures`

### Category

detection

### Description

pop-up detects ublock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 12d.10h
Chromium: 114
filterset (summary):
 network: 95226
 cosmetic: 39504
 scriptlet: 17956
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68094-10, 1m
  easyprivacy: 33421-63, 1m
  plowe-0: 3739-1074, 1m
  ublock-badware: 7536-139, 1m
  ublock-filters: 33895-145, 1m
  ublock-privacy: 428-4, 1m
  ublock-quick-fixes: 346-84, 1m
  ublock-unbreak: 2070-32, 1m
  urlhaus-1: 4859-1, 1m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 541 ms (selfie)
 maxAssetCacheWait: 246 ms
popupPanel:
 blocked: 12
 network:
  investing.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  datadoghq.eu: 1
  dggaenaawxe8z.cloudfront.net: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  hotjar.com: 1
  primis.tech: 1
  scriptcdn.net: 1
 extended:
  ##.midHeader
  ##div[class^="ad_"]
  ##div[data-test="ad-slot-visible"]
  ##[class*="overlay_overlay"]
  ###__next > .fixed
  ##+js(no-fetch-if, ads)
  ##+js(replace-node-text, script, /adb/i, xxx)
```
</details>

**Comment by peace2000** [comment]
No detection on my end with defaults. How do you reproduce it?

**Comment by nissimlahav78** [comment]
Same here... still seeing ads...

**Comment by stephenhawk8054** [comment]
Can anyone test this filter

```adb
investing.com##+js(set, Object.prototype.showAdNotificationPopup, noopFunc)
```

**Comment by okiehsch** [comment]
Does not work for me.
I can't reproduce on all subsites though.

**Comment by stephenhawk8054** [comment]
@okiehsch Maybe just hide the notification is enough, can you check the site's DOM?

**Comment by nissimlahav78** [comment]
@stephenhawk8054 

![image](https://github.com/uBlockOrigin/uAssets/assets/50776526/4b58e1b9-a446-44e8-9d5c-306247a38d23)

**Comment by okiehsch** [comment]
Great, now I can't reproduce on `investing.com` anmyore too,...

**Comment by okiehsch** [comment]
@nissimlahav78 
Does it work if you add
`investing.com##.\!z-12.\!justify-center`
to your filter lis?

**Comment by stephenhawk8054** [comment]
@nissimlahav78 Does this filter work?

```adb
investing.com##[class*="notification_notification"]
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; `Apply changes` > Go back to the website > Press `Ctrl + Shift + R` (or `Cmd + Shift + R` on Mac) to reload the page and test again.

---

@okiehsch Yeah, this site is just so random. I can't reproduce at all.

**Comment by stephenhawk8054** [comment]
@nissimlahav78 Can you switch to Console tab in the devtools, then type `adNotificationDetected` and press Enter. Does it show any value?

**Comment by nissimlahav78** [comment]
@stephenhawk8054 true

![image](https://github.com/uBlockOrigin/uAssets/assets/50776526/9ccf7498-c043-40eb-a73f-286766033fc0)

**Comment by okiehsch** [comment]
`investing.com##+js(set, adNotificationDetected, false)`
is in Adguards list, so that should work.

**Comment by tomlinite** [comment]
Works for me as well.

**Comment by okiehsch** [comment]
Can be closed, I would think, the fix works on the canadian and israeli subsite version, so it's fair to assume it works on every version.

**Comment by JuanMiguelGV** [comment]
Hi! As a disclaimer, I'm not using uBO normally, as I have it installed in chrome, but I usually use OperaGx. Its lists update (rarely) from other repositories, where I haven't got any help in the last two weeks. Nonetheless, some help here would be appreciated.

A couple of weeks ago, adding `investing.com##div[id^="adNotificationPopup"]` was enough to solve the popup, but now they updated the site which resulted in two issues:

1. The code that detects the ad-blocker and creates the popup is somewhere in the `https://i-invdn-com.investing.com/js/main-1.17.358.min.js` code. So disabling this .js, also breaks some parts of the page, such as the charts, which was already here discussed.
2. The new ad-block detection creates the popup with a random class name, so trying to disable the popup by blocking the class name is now not possible.

I'm new to this, so I don't understand that much about the syntax for disabling or blocking this kind of messages, but I was able to figure out the problem last time. Now I need some help, as I have not been able to find the part of the code that creates the popup and would like to learn more to be able to contribute further.

I tried manually adding the filters that were committed in [3d806cb](https://github.com/uBlockOrigin/uAssets/commit/3d806cb38d0fb56c37f7982e267284390aba4c01), but these won't work for me in OperaGx.

Any suggestions or ideas? Thanks in advance, I would like to keep using my preferred browser without adding the extension, but this page has been a bit complicated lately

**Comment by stephenhawk8054** [comment]
So, are you using uBO on OperaGX?

**Comment by JuanMiguelGV** [comment]
> @JuanMiguelGV So, are you using uBO on OperaGX?

Not currently, I have it on chrome and there's no problem with the page there.
But after manually adding the filters committed in 3d806cb to OperaGX, the problem persists

**Comment by stephenhawk8054** [comment]
Well, you need to find assist from OperaGX support, we don't know how compatible their blocker to uBO's syntaxes so we can't help more.
