### ISSUE TITLE
gtorrent.ru: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18918]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://gtorrent.ru/programmy/sistema/173439-sumo-pro-51410518-portable-akciya-comss-multi-ru.html`

### Category

breakage

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/f872065a-e72b-40f4-bb7c-156f19318c0e)

when i enabled russian filter breaking google translate function

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/bac7ffd3-ae25-4d81-b6c8-d5d0b0bf9e81)

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 22d.21h.36m
Chromium: 114
filterset (summary):
 network: 110234
 cosmetic: 126999
 scriptlet: 24983
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9344-4, 45m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 45m
  DEU-0: 6937-0, 45m
  IDN-0: 9527-359, 45m
  ara-0: 2326-3, 45m
  easylist-annoyances: 3892-37, 45m
  easylist-chat: 129-0, 45m
  easylist-newsletters: 6257-15, 45m
  easylist-notifications: 2635-78, 45m
  fanboy-cookiemonster: 47704-220, 45m
  fanboy-social: 16091-12, 45m
  ublock-annoyances: 5319-89, 45m
 default:
  user-filters: 6-0, never
  easylist: 68094-37, 45m
  easyprivacy: 33421-167, 45m
  plowe-0: 3739-1075, 45m
  ublock-badware: 7536-141, 45m
  ublock-filters: 33895-335, 45m
  ublock-privacy: 428-6, 45m
  ublock-quick-fixes: 346-84, 45m
  ublock-unbreak: 2070-39, 45m
  urlhaus-1: 4859-1, 45m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 2716 ms (selfie)
 maxAssetCacheWait: 551 ms
popupPanel:
 blocked: 6
 network:
  google.com: 2
  ok.ru: 1
  pinterest.com: 1
  vk.com: 1
  yandex.ru: 1
 extended:
  ##.social-likes
  ##.social-likes__widget
  ##.social-likes__button
  ##.social-likes__icon
  ##.social-likes__counter
```
</details>

**Comment by stephenhawk8054** [comment]
Please report here: https://github.com/easylist/ruadlist/issues
