### ISSUE TITLE
protothema.gr disables text selection

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#18920]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

cannot select text to copy

### URL(s) where the issue occurs.

https://www.protothema.gr/greece/article/1390958/thrinos-gia-ton-thanato-37hronis-sta-suvota-katerreuse-tin-ora-pou-kolubouse-stin-pisina/

### uBO version

1.50

### Browser name and version

Cent Browser Version 5.0.1002.295 (Official Build) (64-bit) (Portable) (Chromium 102.0.5005.167)

### Settings

n/a

**Comment by peace2000** [comment]
No issues on my end. Copied this text:

`Η 37χρονη Κατερίνα ήταν ιδιαίτερα γνωστή και αγαπητή στα Τρίκαλα, καθώς εργάζονταν σε καταστήματα εστίασης της πόλης.`

Are you using the default filters in uBlock?

**Comment by patrickdrd** [comment]
something wrong with adguard filters,
I added this add it worked:

||cmp.quantcast.com/choice/mU8cqPf6UBZHQ/www.protothema.gr/choice.js$script,domain=www.protothema.gr,important

thanks anyway
