### ISSUE TITLE
nacion.com: nuisance

### ISSUE THREAD

**Issue by DasherPack** [uBlockOrigin/uAssets#18921]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nacion.com/viva/farandula/miss-costa-rica-2022-arranca-el-certamen-para/BSNEEQSAQJDKRARU4K4UFEGJMI/story/`

### Category

nuisance

### Description

When the page is accessed, there is a popup urging to sign in (it's not a paywall, since the content itself is free)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/68102434/a214fdef-2b33-4f87-b415-1ef232aa3308)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 9d.23h.5m
Firefox: 117
filterset (summary):
 network: 98591
 cosmetic: 45327
 scriptlet: 18201
 html: 983
listset (total-discarded, last-updated):
 added:
  spa-0: 3727-1, 3h.1m
  spa-1: 5327-161, 1d.21h.1m
 default:
  user-filters: 0-0, never
  ublock-filters: 34681-76, 4d.21h.26m
  ublock-badware: 7482-0, 4d.21h.25m
  ublock-privacy: 467-0, 2d.23h.3m
  ublock-unbreak: 2101-0, 4d.21h.24m
  ublock-quick-fixes: 347-0, 3h
  easylist: 67864-750, 3d.22h
  easyprivacy: 33402-740, 3d.21h.59m
  urlhaus-1: 5855-0, 21h.43m
  plowe-0: 3737-2, 9d.23h.4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2668 ms (selfie)
 maxAssetCacheWait: 167 ms
popupPanel:
 blocked: 39
 network:
  cxense.com: 1
  doubleclick.net: 1
  ebxcdn.com: 2
  go-mpulse.net: 2
  google-analytics.com: 1
  google.com: 10
  googletagmanager.com: 1
  m32.media: 1
  newsroom.bi: 6
  onesignal.com: 1
  tinypass.com: 3
  viafoura.co: 10
 extended:
  ##.ad-top
  ##.ad-box1
  ##.ad-slider
  ##.vf-ad-comments
  ##.ad-box2
```
</details>

**Comment by gorhill** [comment]
nacion.com##.tp-modal,.tp-backdrop
    nacion.com##body:style(overflow:unset!important)

**Comment by stephenhawk8054** [comment]
Not sure if Adguard Spanish would address this? @Yuki2718

**Comment by Yuki2718** [comment]
Isn't this subscription modal i.e. annoyance? However, Tinypass modal has history of various problems - blocking this without caution often blocks legit registration too.
