### ISSUE TITLE
amarujala.com: ads

### ISSUE THREAD

**Issue by Malgotra** [uBlockOrigin/uAssets#18929]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.amarujala.com/`
`https://www.amarujala.com/shimla/rain-havoc-himachal-4-000-crore-loss-in-preliminary-estimate-all-dcs-asked-to-be-alert-for-10-days-2023-07-10?pageId=2`

### Category

ads

### Description

Ads leftover and other annoyances

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230710-203854](https://github.com/uBlockOrigin/uAssets/assets/122884037/e3397d80-3c9b-4dd9-8cf7-a0d1ec3944df)

![Screenshot_20230710-203917](https://github.com/uBlockOrigin/uAssets/assets/122884037/f2e68630-a202-420b-951a-40583633754f)

![Screenshot_20230710-203904~2](https://github.com/uBlockOrigin/uAssets/assets/122884037/d871b5be-586e-4128-94ba-0c2e9f53a6e8)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 18d.16m
Firefox Mobile: 115
filterset (summary):
 network: 108253
 cosmetic: 125256
 scriptlet: 24198
 html: 1170
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 961-0, 32m
  easylist-annoyances: 3892-101, 32m
  easylist-chat: 129-0, 32m
  fanboy-cookiemonster: 47713-288, 32m
  easylist-newsletters: 6268-13, 32m
  easylist-notifications: 2636-4, 32m
  fanboy-social: 16100-6, 32m
  ublock-annoyances: 5344-39, 32m
  IND-0: 12683-8, never
 default:
  user-filters: 3-0, never
  ublock-filters: 35050-124, 33m
  ublock-badware: 7532-2, 33m
  ublock-privacy: 469-0, 33m
  ublock-unbreak: 2117-2, 33m
  ublock-quick-fixes: 350-0, 33m
  adguard-mobile: 8382-10, 33m
  easylist: 68143-821, 33m
  easyprivacy: 33422-824, 33m
  urlhaus-1: 6426-1, 32m
  plowe-0: 3739-85, 32m
filterset (user): [array of 3 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1630 ms (selfie)
 maxAssetCacheWait: 582 ms
popupPanel:
 blocked: 14
 network:
  adpushup.com: 1
  amazon-adsystem.com: 1
  doubleclick.net: 2
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 1
  izooto.com: 3
  scorecardresearch.com: 1
  stpd.cloud: 1
  youtube.com: 2
 extended:
  ##.ad-728
  ##.ad-dt
  ##.ad-mb
  ##.ad-300
  ##.cookie_enable_popup
  ##.rgt-ad
  ##.shareBtm
  ###credential_picker_iframe
  ##[id^="google_ads_iframe"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by gorhill** [comment]
Should be fixed in [regional list](https://github.com/mediumkreation/IndianList):

    amarujala.com##.ad-mb-app

cc @indianfilterlist

**Comment by mediumkreation** [comment]
Fixed: https://github.com/mediumkreation/IndianList/pull/7666
