### ISSUE TITLE
asurascans.com: nuisance

### ISSUE THREAD

**Issue by Algoldir** [uBlockOrigin/uAssets#18922]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.asurascans.com/the-game-that-i-came-from-chapter-193/`

### Category

nuisance

### Description

It forces a nuisance add across the screen that also has a very small close button so you end up going to the site non stop

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![IMG_20230710_142943](https://github.com/uBlockOrigin/uAssets/assets/139129154/23f3edd3-dfa8-41f1-94e0-17dfc1beaee1)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 27d.5h.10m
Firefox Mobile: 115
filterset (summary):
 network: 96406
 cosmetic: 29526
 scriptlet: 17918
 html: 985
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34961-304, 4d.2h.9m
  ublock-badware: 7476-0, 5d.2h.57m
  ublock-privacy: 461-1, 7d.7h.42m
  ublock-unbreak: 2107-1, 3d.23h.9m
  adguard-mobile: 8367-121, 4d.2h
  easylist: 67885-17411, 1d.21h.54m
  easyprivacy: 33415-731, 4d.2h.10m
  urlhaus-1: 4859-0, 2h.14m
  plowe-0: 3740-2, 3d.4h.5m
  ublock-quick-fixes: 291-2, 2h.13m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 566 ms (selfie)
 maxAssetCacheWait: 117 ms
popupPanel:
 blocked: 7
 network:
  cloudflareinsights.com: 2
  disq.us: 1
  disqus.com: 2
  viglink.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
asurascans.com##a[href^="https://bit.ly/"]
```

@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a073b0d0342051156dbfb71d78ad2a2d9ede5f89
