### ISSUE TITLE
equalweb.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18924]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.equalweb.com/`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/25685340-12cb-4661-b742-d95d7a946713)

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 23d.5h.17m
Chromium: 114
filterset (summary):
 network: 110234
 cosmetic: 126999
 scriptlet: 24983
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9344-4, 8h.26m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 8h.26m
  DEU-0: 6937-0, 8h.26m
  IDN-0: 9527-359, 8h.26m
  ara-0: 2326-3, 8h.26m
  easylist-annoyances: 3892-37, 8h.26m
  easylist-chat: 129-0, 8h.26m
  easylist-newsletters: 6257-15, 8h.26m
  easylist-notifications: 2635-78, 8h.26m
  fanboy-cookiemonster: 47704-220, 8h.26m
  fanboy-social: 16091-12, 8h.26m
  ublock-annoyances: 5319-89, 8h.26m
 default:
  user-filters: 6-0, never
  easylist: 68094-37, 8h.26m
  easyprivacy: 33421-167, 8h.26m
  plowe-0: 3739-1075, 8h.26m
  ublock-badware: 7536-141, 8h.26m
  ublock-filters: 33895-335, 8h.25m
  ublock-privacy: 428-6, 8h.25m
  ublock-quick-fixes: 346-84, 8h.25m
  ublock-unbreak: 2070-39, 8h.25m
  urlhaus-1: 4859-1, 8h.25m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1983 ms (selfie)
 maxAssetCacheWait: 549 ms
popupPanel:
 blocked: 31
 network:
  clarity.ms: 1
  clickcease.com: 1
  doubleclick.net: 6
  g2crowd.com: 1
  google.com: 1
  googletagmanager.com: 3
  hs-analytics.net: 1
  hs-banner.com: 1
  hsadspixel.net: 1
  hsforms.com: 1
  hsleadflows.net: 1
  licdn.com: 1
  tiktok.com: 1
  youtube.com: 10
  ywxi.net: 1
 extended:
  ##.ytp-share-button
  ##.ytp-title-channel
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
```
</details>

**Comment by stephenhawk8054** [comment]
For simple cookie banners, please report here: https://github.com/easylist/easylist/issues
