### ISSUE TITLE
mdn.lol: detection

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#18928]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mdn.lol/2023/04/17/is-finance-just-math-the-real-answer/`

### Category

detection

### Description

detection on firefox

### Other extensions used

detection on firefox

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 20d.23h.41m
Firefox: 115
filterset (summary):
 network: 115540
 cosmetic: 64952
 scriptlet: 19179
 html: 1004
listset (total-discarded, last-updated):
 added:
  DEU-0: 6937-3, 14h.45m
 default:
  user-filters: 0-0, never
  ublock-filters: 34742-72, 14h.50m
  ublock-badware: 7527-0, 14h.48m
  ublock-privacy: 464-0, 5d.17h.5m
  ublock-unbreak: 2111-2, 14h.47m
  ublock-quick-fixes: 291-0, 8h.44m
  easylist: 67836-729, 5d.17h.4m
  easyprivacy: 33398-732, 5d.17h.4m
  urlhaus-1: 5855-1, 14h.46m
  plowe-0: 3739-2, 5d.17h.4m
  RUS-0: 39613-135, 1d.14h.58m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2463 ms (selfie)
 maxAssetCacheWait: 513 ms
popupPanel:
 blocked: 18
 network:
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 8
  googlesyndication.com: 1
  googletagmanager.com: 5
  unblockia.com: 1
  wtg-ads.com: 2
 extended:
  ##.fa-xmark
  ###overlay
  ##div[style^="width:305px;height"][style$="display: inline-block…
  ##.g-recaptcha:upward(div):style(display: block !important)
  ##form > div[id][style="display: none;"] .g-recaptcha:upward(div…
  ##input:style(display: block !important)
  ##+js(alert-buster)
  ##+js(no-setTimeout-if, .innerHtml)
  ##+js(addEventListener-defuser, DOMContentLoaded, adsBlocked)
  ##+js(no-setTimeout-if, show)
  ##+js(abort-current-script, onload, adblock)
  ##+js(window.open-defuser)
  ##+js(abort-on-property-read, pbjs)
  ##+js(no-fetch-if, wpadmngr)
  ##+js(abort-current-script, document.createElement, adsBlocked)
  ##+js(set-constant, document.hasFocus, trueFunc)
  ##+js(noeval)
  ##+js(remove-attr, onmouseover, .g-recaptcha)
```
</details>

**Comment by JobcenterTycoon** [comment]
Post shortener issues here: https://github.com/uBlockOrigin/uAssets/discussions/17361
