### ISSUE TITLE
moroccoworldnews.com: nuisance

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uAssets#18923]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Annoying Social Media Buttons 

### URL(s) where the issue occurs.

`https://www.moroccoworldnews.com/2023/07/356336/deadly-israeli-raid-claims-lives-of-two-palestinians-in-nablus`

### Screenshot(s)
https://github.com/uBlockOrigin/uAssets/assets/98148960/be19d9e6-3223-462b-ba6b-5d4a56210d29

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 8h.7m
Firefox Mobile: 115
filterset (summary):
 network: 104354
 cosmetic: 123556
 scriptlet: 24839
 html: 1169
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9344-6, 1m
  adguard-spyware-url: 1116-5, 8h.6m
  easylist-annoyances: 3892-90, 1m
  easylist-chat: 129-0, 1m
  fanboy-cookiemonster: 47712-288, 1m
  easylist-newsletters: 6268-13, 1m
  easylist-notifications: 2636-3, 1m
  fanboy-social: 16099-6, 1m
  ublock-annoyances: 5344-43, 8h.6m
 default:
  user-filters: 0-0, never
  ublock-filters: 35052-347, 8h.7m
  ublock-badware: 7521-2, 8h.7m
  ublock-privacy: 469-0, 8h.7m
  ublock-unbreak: 2116-1, 8h.7m
  ublock-quick-fixes: 347-0, 8h.7m
  adguard-mobile: 8373-115, 8h.7m
  easylist: 68094-675, 8h.6m
  easyprivacy: 33424-866, 8h.6m
  urlhaus-1: 4859-0, 8h.6m
  plowe-0: 3739-1, 8h.6m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 995 ms (selfie)
 maxAssetCacheWait: 423 ms
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
##.socail-share1
```

@ryanbr
