### ISSUE TITLE
shortlinks fly detected adblock

### ISSUE THREAD

**Issue by XShouko** [uBlockOrigin/uAssets#18936]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

shortlinks fly detected adblock, please help me :)

### URL(s) where the issue occurs.

1. https://shinbhu.net/adblock.html
2. https://crewbase.net/adblock.html
3. https://talkforfitness.com/adblock.html

### Screenshot(s)

https://imgur.com/MnjeNpf

### uBO version

1.50.0

### Browser name and version

firefox 116.0

### Settings

nothing

### Notes

please fix this

**Comment by JobcenterTycoon** [comment]
Please pass us the shortened link.

**Comment by XShouko** [comment]
I can't finish it because when I want to finish it I get adblock detected like the screenshot shown along with the link

**Comment by JobcenterTycoon** [comment]
Post the issue here: https://github.com/uBlockOrigin/uAssets/discussions/17361 and post also the shortened link which redirecting you to those pages (example: `https://shorteneddomain.tld/iarvuz`) because no anti adblock appears when i just open `https://shinbhu.net/`
