### ISSUE TITLE
reddit.com: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#18938]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reddit.com/r/worldnews/`

### Category

privacy

### Description

While not logged in, Reddit mobile site tracks outbound navigation using `out.reddit.com`.
The behaviour still exists after testing with Firefox 116.0b3 and default uBlock Origin.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 27d.9h.6m
Firefox Mobile: 113
filterset (summary):
 network: 127068
 cosmetic: 196662
 scriptlet: 27009
 html: 1171
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 961-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2230-0, now
  adguard-spyware-url: 1117-147, 1m
  block-lan: 47-0, now
  curben-pup: 189-0, now
  adguard-social: 20887-822, now
  fanboy-cookiemonster: 47637-3839, now
  fanboy-social: 16098-8, now
  ublock-annoyances: 5344-16, now
  dpollock-0: 11524-468, now
  IDN-0: 9527-4, now
  adguard-cookies: 26293-61, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 25-0, never
  ublock-filters: 35059-525, 1m
  ublock-badware: 7532-1, 1m
  ublock-privacy: 469-2, 1m
  ublock-unbreak: 2117-1, 1m
  ublock-quick-fixes: 350-0, 1h.58m
  adguard-mobile: 8383-141, 1m
  easylist: 68120-1060, 1m
  easyprivacy: 33422-906, now
  urlhaus-1: 6440-1, now
  plowe-0: 3740-1, now
filterset (user): [array of 25 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2482 ms
 maxAssetCacheWait: 1543 ms
popupPanel:
 blocked: 10
 network:
  reddit.com: 1
  amazon-adsystem.com: 1
  googletagservices.com: 1
  redditmedia.com: 5
  redditstatic.com: 2
 extended:
  ##.adsense-ads
  ##.googads
  ##.hasads
  ##.native-ad
  ##.HeaderAd
  ##.NavBarAd
  ##.ad-medium
  ##.post-ad
  ##.promoad
  ##.rectad
  ##.sidebar-ad:not(.adsbygoogle)
  ##.small-ad
  ##.sponsorAd
  ##.sponsorad
  ##.sponsorPost
  ##.PostFooter__share
  ##.XPromoPopupRpl
  ##article[id] > a[href^="https://alb.reddit.com/"] ~ *
  ##.XPromoPopupRpl.m-active
  ##.promotedlink
  ##.PostsList > div article:has(> .Post__header-wrapper .PostHead…
  ##.PostsList > div:not([class]):not([id]) > div:not([class]):not…
  ##.size-compact.Post:has([class*="promoted"])
  ##article.Post:has(a[rel="nofollow noopener sponsored"])
  ##body:style(pointer-events:auto!important;)
  ##body:style(overflow: auto !important;)
  ##body.scroll-disabled:style(overflow: visible!important; positi…
  ##body,html.scroll-is-blocked:style(overflow: auto !important;)
  ##body:style(pointer-events:auto !important;)
  ##body:style(pointer-events: auto !important; overflow: auto !im…
  ##body.scroll-disabled:style(overflow: visible !important; posit…
  ###acceptabletest:style(display: block !important;)
  ###adblocktest:style(display: block !important;)
  ##+js(no-setTimeout-if, /^/)
  ##+js(no-setInterval-if, /^/)
  ##+js(addEventListener-defuser, touchmove)
  ##+js(set-constant, Object.prototype.allowClickTracking, false)
  ##+js(no-fetch-if, url:/^https:\/\/www\.reddit\.com$/ method:pos…
  ##+js(no-xhr-if, method:POST url:/^https:\/\/www\.reddit\.com$/)
  ##+js(replace-node-text, script, "outboundUrl", "outbound")
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(addEventListener-defuser, block-body-scrolling)
  ##+js(remove-class, m-blurred, .m-blurred)
  ##+js(remove-class, scroll-disabled, body)
  ##+js(set-constant, Notification.requestPermission, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this?

```adb
reddit.com,~out.reddit.com##+js(set, Object.prototype.allowClickTracking, false)
```

**Comment by partingscientist** [comment]
I have that on my configuration (as attached above) when testing on my dirty profile and the behaviour still persists. I'll test again to make sure.

**Comment by stephenhawk8054** [comment]
Does it occur on desktop?

**Comment by partingscientist** [comment]
I cannot reproduce on desktop using clean profile and default uBlock Origin, only on mobile.

**Comment by mapx-** [comment]
@partingscientist  are you able to reproduce the issue using FF emulator on desktop ?

How did you note that behaviour on android ? steps ?

**Comment by partingscientist** [comment]
> Are you able to reproduce the issue using FF emulator on desktop ?

Yes.

> How did you note that behaviour on android ? steps ?

Given `https://www.reddit.com/r/worldnews/` as a subreddit example, I just open one of the article links posted while opening the logger.

**Comment by mapx-** [comment]
I cannot reproduce the issue => no `out.reddit.com` in the logger (even disabling the scriptlets on reddit)

**Comment by gorhill** [comment]
I also cannot reproduce on mobile.

**Comment by partingscientist** [comment]
I'm still investigating the reproducibility on my end, as I can confidently reproduce the issue on my end; I'll report my findings soon. Just to make sure, you're not logged in while testing, right?

> **While not logged in**, Reddit mobile site tracks outbound navigation using out.reddit.com.

**Comment by partingscientist** [comment]
Here's what I found (Firefox Mobile 116.0b3 and default stable-release uBlock Origin on Android):

It seems to me that Reddit is currently testing a new user interface for their mobile website (`reddit.com`).

<details>

<summary>Here's the old user interface</summary>

![old](https://github.com/uBlockOrigin/uAssets/assets/115052854/be572610-d1f2-43c3-aabc-6c8634f75bea)

</details>

<details>

<summary>Here's what they are currently testing</summary>

![new](https://github.com/uBlockOrigin/uAssets/assets/115052854/6f6680ac-6459-4c33-929b-12492cdcefab)

</details>

The issue is reproducible on the old interface by interacting with the link bar below the post thumbnail on the right hand side. However, the issue is not reproducible on the new interface. I very rarely get this new interface, perhaps due to geolocation and other factors which also might vary amongst the maintainers here.

**Comment by stephenhawk8054** [comment]
I can reproduce. The key is this

> interacting with the link bar below the post thumbnail on the right hand side

Can you test this filter?

```adb
reddit.com##+js(json-prune, data.children.[].data.outbound_link)
```

**Comment by partingscientist** [comment]
> ```
> reddit.com##+js(json-prune, data.children.[].data.outbound_link)
> ```

This works, both on Firefox Mobile and Firefox Desktop with the emulator.

**Comment by stephenhawk8054** [comment]
You're right. I don't see those connections any more.

**Comment by partingscientist** [comment]
Did you check `old.reddit.com` also? I found an xhr POST request recently sending a json containing pageview info and user agent, but I haven't been able to reproduce it again. Weirdly, I can only find it when I have `reddit.com##+js(no-xhr-if, method:POST url:/^https:\/\/www\.reddit\.com$/)` as a filter.

**Comment by partingscientist** [comment]
> Tracking happening via urls like `https://www.reddit.com/svc/shreddit/b52ae76b` `b52ae76b` is randomised
> 
> filter -- `/^https:\/\/www\.reddit\.com\/svc\/shreddit\/[a-z0-9]{8}$/$xhr,1p,method=post`

@stephenhawk8054 the length of pathname characters is randomised.

<details>

<summary>Source</summary>

`https://www.redditstatic.com/shreddit/en-US/shell-594c01eb.js, line 4477`

```javascript
// Ho() returns a UUID in the form [0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12} 
// (line 2665-2677, line 2734-2742)
const us = `/svc/shreddit/${(()=>{const e=Ho().split("-"),t=1+Math.floor(6*Math.random()),n=`${e[1]+e[2]}`.substring(0,t);return e[0]+n})()}`,
   ms = (e, t) => {
      const n = "function" != typeof navigator.sendBeacon || ps() ? "function" == typeof fetch ? cs : void 0 : ds;
      void 0 !== n && n({
         url: us,
         eventsBuffer: e,
         microapp: _r(),
         shouldNotSendDropEvent: t
      })
   };
```

</details>

`/^https:\/\/www\.reddit\.com\/svc\/shreddit\/[a-z0-9]{8,14}$/$xhr,1p,method=post` should work, I think.

**Comment by partingscientist** [comment]
It cannot be 8 characters actually (my bad), `e[0]` is always 8 characters and `n` is 1-6 characters. I'm assuming you want to keep the 8 in case of partial rollout of the new one. Just letting you know to make sure.

**Comment by stephenhawk8054** [comment]
Keeping 8 is still good as the old ones have 8: `https://www.reddit.com/svc/shreddit/b52ae76b`. This URL hardly has FPs anyway.

**Comment by stephenhawk8054** [comment]
I did see a `shreddit` connection with 10 characters few hours ago, and there's actually a `https://www.redditstatic.com/shreddit/en-US/shell-` script and inside it does contain the code in https://github.com/uBlockOrigin/uAssets/issues/18938#issuecomment-1692983237

<details>

```js
var Co = /^(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000)$/i;

function Ao(e) {
   return "string" == typeof e && Co.test(e)
}

function Oo(e) {
   var t = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : 0,
      n = (Lo[e[t + 0]] + Lo[e[t + 1]] + Lo[e[t + 2]] + Lo[e[t + 3]] + "-" + Lo[e[t + 4]] + Lo[e[t + 5]] + "-" + Lo[e[t + 6]] + Lo[e[t + 7]] + "-" + Lo[e[t + 8]] + Lo[e[t + 9]] + "-" + Lo[e[t + 10]] + Lo[e[t + 11]] + Lo[e[t + 12]] + Lo[e[t + 13]] + Lo[e[t + 14]] + Lo[e[t + 15]]).toLowerCase();
   if (!Ao(n)) throw TypeError("Stringified UUID is invalid");
   return n
}

function Ho(e, t, n) {
   var o = (e = e || {}).random || (e.rng || Io)();
   if (o[6] = 15 & o[6] | 64, o[8] = 63 & o[8] | 128, t) {
      n = n || 0;
      for (var r = 0; r < 16; ++r) t[n + r] = o[r];
      return t
   }
   return Oo(o)
}

const ps = () => ("boolean" == typeof hs || (e => {
      hs = e
   })(document.querySelector("shreddit-app")?.hasAttribute("disable-send-beacon") ?? !1), hs),
   us = `/svc/shreddit/${(()=>{const e=Ho().split("-"),t=1+Math.floor(6*Math.random()),n=`${e[1]+e[2]}`.substring(0,t);return e[0]+n})()}`,
   ms = (e, t) => {
      const n = "function" != typeof navigator.sendBeacon || ps() ? "function" == typeof fetch ? cs : void 0 : ds;
      void 0 !== n && n({
         url: us,
         eventsBuffer: e,
         microapp: _r(),
         shouldNotSendDropEvent: t
      })
   };
```

</details>

The characters indeed only had `[a-f]`, but I forgot to save the scripts and connections there. And now I cannot see those `shreddit` connections any more. Does anyone see any connections slipped through?

**Comment by stephenhawk8054** [comment]
Update: Ah ok I can see it now: `https://www.reddit.com/svc/shreddit/c8cea5df7d8b4`

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/caa9b795-eab8-46b3-9a1f-6e978a59f484)

**Comment by stephenhawk8054** [comment]
I also see the query parameter `rdt` in reddit link, should we add it to our query stripping section?

**Comment by stephenhawk8054** [comment]
Ok: https://github.com/uBlockOrigin/uAssets/commit/eee6fec5647e3014d1da144d0cd9888254fa09a4

**Comment by gorhill** [comment]
> they can change it anytime

Usually we try to be as specific _as needed_ to avoid false positives. Using `a-f` was the proper approach if we are dealing with hex-based names. If we craft according to _"they can change it anytime"_ logic, then why even mind what comes after `.../shreddit/`.

**Comment by stephenhawk8054** [comment]
@partingscientist Does this work?

```adb
||www.reddit.com/|$xhr,1p,method=post
```

**Comment by stephenhawk8054** [comment]
@partingscientist Looks like the above filters cannot load the comments in this link? `https://www.reddit.com/r/meirl/comments/17nyl7a/meirl/`

**Comment by stephenhawk8054** [comment]
@partingscientist Still does not work for me. If I'm not mistaken, it's because reddit is detecting if you block those XHR, it won't load the comments.

Even when using `no-fetch-if`, it still has issue due to this

<details>

```js
fd = async ({
  url: e,
  eventsBuffer: t,
  microapp: n,
  options: o
}) => {
  const r = jo.get("csrf_token") ?? "",
     i = !yd() ? t : {
        csrf_token: r,
        info: t
     },
     a = JSON.stringify(i);
  let s;
  try {
     s = await fetch(e, {
        body: a,
        headers: {
           "Content-Type": "text/PLAIN",
           "x-sh-microapp-route": n || "monolith"
        },
        keepalive: !0,
        method: "post",
        credentials: "same-origin"
     })
  } catch (n) {
     return void(o?.shouldNotRetryIfFail ? o?.shouldNotSendDropEvent || bd({
        eventsBuffer: t,
        errorText: `An error: ${n}`,
        v2EventsRoute: e
     }) : Id({
        eventsBuffer: t,
        v2EventsRoute: e,
        options: {
           shouldNotRetryIfFail: !0
        }
     }))
  }
  if (s?.ok) {
     Array.from(s.headers).length && (vd || (vd = document.querySelector("shreddit-app")), vd)?.resolvePendingRequests();
     const e = s.headers.get("x-set-loid") || void 0,
        t = s.headers.get("x-set-session") || void 0;
     window.dispatchEvent(new CustomEvent("v2-events-sent", {
        detail: {
           loid: e,
           session_tracker: t
        }
     }))
  } else o?.shouldNotSendDropEvent || bd({
     eventsBuffer: t,
     errorText: `HTTP Response Code: ${s?.status}`,
     v2EventsRoute: e
  });
  return s
};
```

</details>

(This is their old code, they might change something already)

**Comment by uBlock-user** [comment]
@gorhill any solution for ongoing issue with reddit ?

**Comment by ghost** [comment]
On mobile, the EasyList/uBO Cookie Notices filter makes the page unscrollable on mobile.

Reddit seems to have changed their cookie notices, probably that's why.

Recording:
https://streamable.com/wfzm9h

**Comment by partingscientist** [comment]
Considering Old Reddit now requires an account, is this issue worth revisiting? I have not followed resources library development for quite some time, so I'm not sure whether a solution is possible at the moment.
