### ISSUE TITLE
asoytube.com: detection

### ISSUE THREAD

**Issue by Jokopentil** [uBlockOrigin/uAssets#18934]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://asoytube.com/hampir-ketahuan-emak-nya-pas-lagi-nenen-nyusuin-pacar-diruang-tamu-endingnya-ceweknya-masih-pengen-cowoknya-deg-degan/`

### Category

detection

### Description

Klik link download appear adblock detect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![20230711_085556_rmscr](https://github.com/uBlockOrigin/uAssets/assets/114223791/cdf285db-4c73-4ec5-a410-ea49dd9df686)
![20230711_095454_rmscr](https://github.com/uBlockOrigin/uAssets/assets/114223791/336aac32-75b5-44c0-a988-df0888702c22)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.7h.37m
Chromium Mobile: 112
filterset (summary):
 network: 303498
 cosmetic: 237736
 scriptlet: 43046
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9344-4, 14h.13m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 14h.13m
  https://raw.githubusercontent.com/Hakame-kun/uBlock-Filters-Indonesia/master/uBlock Indo/ubindo.txt: 1632-16, 5d.7h.59m
  adguard-cookies: 26257-29, 14h.14m
  adguard-generic: 72386-633, 14h.14m
  adguard-mobile-app-banners: 4406-13, 14h.14m
  adguard-other-annoyances: 13061-54, 14h.13m
  adguard-popup-overlays: 22926-75, 14h.13m
  adguard-social: 20872-880, 14h.13m
  adguard-spyware: 60311-1257, 14h.13m
  adguard-spyware-url: 1116-3, 14h.13m
  adguard-widgets: 2196-7, 14h.13m
  [12 lists not shown]: [too many]
 default:
  IDN-0: 9527-373, 14h.13m
  adguard-mobile: 8382-54, 14h.14m
  easylist: 67880-1261, 5d.8h.20m
  easyprivacy: 33400-16726, 5d.8h.20m
  plowe-0: 3739-1568, 5d.8h.20m
  ublock-badware: 7530-398, 5m
  ublock-filters: 34175-4338, 4m
  ublock-privacy: 423-65, 5d.8h.20m
  ublock-quick-fixes: 342-19, 2m
  ublock-unbreak: 2075-137, 3m
  urlhaus-1: 4859-3, 14h.13m
filterset (user): [array of 7 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11855 ms (selfie)
 maxAssetCacheWait: 2557 ms
popupPanel:
 blocked: 1
 network:
  google-analytics.com: 1
 extended:
  ##a[title="Back to top"]
  ###back-top
```
</details>

**Comment by stephenhawk8054** [comment]
Test in Firefox mobile.

**Comment by Jokopentil** [comment]
![20230711_103646_rmscr.jpg](https://github.com/uBlockOrigin/uAssets/assets/114223791/2d892e81-19c9-4023-8737-2577b2bca334)

Ya finaly found cause annoying ads fiture

**Comment by stephenhawk8054** [comment]
> - [X] I did not answer truthfully to **ALL** the above checkpoints.

Please follow what you have ticked on truthfully

> - [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
> - [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
