### ISSUE TITLE
deezer.com: detection

### ISSUE THREAD

**Issue by cesarnovo1971** [uBlockOrigin/uAssets#18932]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.deezer.com/`

### Category

detection

### Description

![Imagem da Área de Transferência](https://github.com/uBlockOrigin/uAssets/assets/65466276/62b9ab6d-bc40-486e-ac0f-8c3f07e3df6c)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 31d.48m
Chromium: 114
filterset (summary):
 network: 98243
 cosmetic: 43041
 scriptlet: 18282
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68168-11, now
  easyprivacy: 33422-63, now
  plowe-0: 3740-1074, now
  spa-1: 5332-68, now
  ublock-badware: 7536-140, 5m
  ublock-filters: 33894-169, 1m
  ublock-privacy: 428-4, now
  ublock-quick-fixes: 349-84, now
  ublock-unbreak: 2069-32, now
  urlhaus-1: 6426-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 363 ms
 maxAssetCacheWait: 147 ms
popupPanel:
 blocked: 1
 network:
  sentry.io: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you describe the steps to reproduce in more details?

**Comment by kandohar** [comment]
> You mean you disable uBO and anti adblock appears? What is the color of your uBO icon on the toolbar.

Yes, I edited my message to be more clear. But the icon is grey.

**Comment by stephenhawk8054** [comment]
> Yes, I edited my message to be more clear. But the icon is grey.

Then it's not related to uBO any more. There's something else on your machine is also blocking things.

Check if you are using any:

- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by Yann-P** [comment]
I had the same problem and was about to open an issue.

However @stephenhawk8054 has pointed the real cause at least for me, I disabled my pi-hole temporarily and it started working again (no more pop-up), even with uBlock enabled.

**Comment by kandohar** [comment]
Ok, My main browser is Firefox, and i can't make it work, even on a private tab without any extensions.
But it works on Chrome.
So it's not my computer nor the network, probably a setting in Firefox I guess.

**Comment by stephenhawk8054** [comment]
> Ok, My main browser is Firefox, and i can't make it work, even on a private tab without any extensions.
> But it works on Chrome.
> So it's not my computer nor the network, probably a setting in Firefox I guess.

Firefox has its own tracking protection blocker. Remember to turn it off on the website too.

**Comment by kandohar** [comment]
Yes thank you, that was Firefox tracking protection on this specific page.
I reported the issue in Firefox.

**Comment by Yann-P** [comment]
I think I narrowed down the domain that needs to be whitelisted: `ced.sascdn.com`. After whitelisting, I enabled back my DNS blocker, and no more popup.

**Comment by Yann-P** [comment]
They indeed make a call to this domain and the `onerror` handler sets a flag on the `window` object. I assume this is what they use to trigger the popup.

Gist with line numbers : https://gist.github.com/Yann-P/a7947422a73399275b25d2914931d706#file-route-naboo-ads-js-L462-L465

which is a copy of https://e-cdn-files.dzcdn.net/cache/js/route-naboo-ads.8e773f8740fa6a75b950.js
