### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by avatheavali** [uBlockOrigin/uAssets#18937]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=buLyy7x2dcQ`

### Category

breakage

### Description

The YouTube comments section completely breaks, with me unable to enter comments as the comment bar disappears upon clicking. I cannot read comments or reply to them either, with them working when uBO is disabled.

### Other extensions used

FastForward
Microsoft Rewards Bot 
Chromebook Recovery Utility 
Deadname Remover 
h264ify
PayPal Honey
Picture-in-Picture Extension (by Google)
PronounDB
Return YouTube Dislike
Shinigami Eyes
SponsorBlock for YouTube
SteamDB
User Agent Switcher and Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/106939391/b1ecc71c-d73e-4e50-97fb-521fdae3ef04)
![image](https://github.com/uBlockOrigin/uAssets/assets/106939391/3663d911-76bd-4ed1-80bb-0cdb4b80a27d)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 29d.7h.6m
Chromium: 114
filterset (summary):
 network: 96633
 cosmetic: 39495
 scriptlet: 17955
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 30-5, never
  easylist: 67864-10, 4d.10h.18m
  easyprivacy: 33398-62, 4d.12h.20m
  plowe-0: 3739-1068, 7d.2h.23m
  ublock-badware: 7525-138, 2d.3h.56m
  ublock-filters: 33893-147, 13h.15m
  ublock-privacy: 423-3, 5d.26m
  ublock-quick-fixes: 349-19, 41m
  ublock-unbreak: 2070-31, 10h.35m
  urlhaus-1: 6426-1, 13h.14m
filterset (user): [array of 30 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1141 ms (selfie)
 maxAssetCacheWait: 623 ms
popupPanel:
 blocked: 18
 network:
  youtube.com: 11
  doubleclick.net: 3
  google.com: 4
 extended:
  ###player-ads
  ###main
  ###merch-shelf
  ##.ytd-companion-slot-renderer
  ##.ytd-merch-shelf-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##ytd-companion-slot-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
default:
  user-filters: 30-5, never
```

You are using 30 custom filters, please check them again.

**Comment by krystian3w** [comment]
All = all #7636

**Comment by avatheavali** [comment]
> ```yaml
> default:
>   user-filters: 30-5, never
> ```
> 
> You are using 30 custom filters, please check them again.

Didn't realize that, thank you! Comment section works now after removing the ones for YouTube

**Comment by stephenhawk8054** [comment]
Please follow what you have ticked on truthfully:

> - [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

**Comment by gorhill** [comment]
Changed to _invalid_ as the breakage was self-inflicted.

**Comment by gorhill** [comment]
> - [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

Changed to _invalid_ as the breakage was self-inflicted not truthfully reported.
