### ISSUE TITLE
AdBlock detection

### ISSUE THREAD

**Issue by LittleTale** [uBlockOrigin/uAssets#18933]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ublock gets detected and get redirected to a page asking you to disable adblock.

### URL(s) where the issue occurs.

https://dgb.lol/

### Screenshot(s)

![Screenshot (91)](https://github.com/uBlockOrigin/uAssets/assets/52611040/7946a89e-4397-4195-af51-9c2b27564320)

### Notes

The redirect only appears once you click on an option in the 4 square at the top left of the website. you then choose an option like for example"image upscaler" and then you get redirected to a disable your adblock extention page.

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 26d.5h.9m
Chromium: 114
filterset (summary):
 network: 138161
 cosmetic: 158455
 scriptlet: 39341
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68910-103, now
  CHN-0: 24479-125, 1m
  adguard-generic: 72473-484, now
  adguard-mobile: 8383-66, now
  spa-0: 3726-39, now
  spa-1: 5332-223, now
  ublock-annoyances: 5319-225, now
 default:
  user-filters: 1-0, never
  easylist: 68168-1017, now
  easyprivacy: 33422-247, now
  plowe-0: 3740-1162, now
  ublock-badware: 7536-366, now
  ublock-filters: 33899-4159, now
  ublock-privacy: 428-4, now
  ublock-quick-fixes: 349-85, now
  ublock-unbreak: 2070-92, now
  urlhaus-1: 6440-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 24 redacted]
 removed:
  chrome-extension-scheme
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1548 ms (selfie)
 maxAssetCacheWait: 1013 ms
```
</details>

**Comment by partingscientist** [comment]
This works for me:
`dgb.lol##+js(spoof-css, .ad-box, display, block)`

**Comment by huyszn** [comment]
`https://dgb.lol/ai-image-upscaler`

"Ad blocker detected, please disable it, and reload the page" message
