### ISSUE TITLE
coinadpro.club detected chpadblock

### ISSUE THREAD

**Issue by XShouko** [uBlockOrigin/uAssets#18935]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

detected chpadblock

### URL(s) where the issue occurs.

coinadpro.club

### uBO version

1.50.0

### Browser name and version

firefox 116.0

### Settings

nothing

### Notes

please help

**Comment by JobcenterTycoon** [comment]
Fixed now. Force update the filterlists to get the fix directly.
