### ISSUE TITLE
rustlabs.com: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#18945]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rustlabs.com/building/wooden-floor`

### Category

ads

### Description

A `skinswap.com` ad for CS:GO skins. It's on all the item pages (only the pages containing items)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Rust Labs page](https://github.com/uBlockOrigin/uAssets/assets/50150516/0c0ec85d-fd3e-4f18-82cd-e1abd135a2b0)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 33d.13h.52m
Chromium: 114
filterset (summary):
 network: 96876
 cosmetic: 39458
 scriptlet: 17882
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68120-11, now
  easyprivacy: 33422-63, now
  plowe-0: 3740-1074, now
  ublock-badware: 7536-140, now
  ublock-filters: 33755-145, now
  ublock-privacy: 425-4, now
  ublock-quick-fixes: 349-84, 1h.45m
  ublock-unbreak: 2070-31, now
  urlhaus-1: 6502-1, now
filterset (user): [empty]
trustedset:
 added: [array of 52 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 440 ms (selfie)
 maxAssetCacheWait: 106 ms
popupPanel:
 blocked: 2
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
rustlabs.com###right-column
```

@ryanbr

**Comment by LightAndy1** [comment]
The right column had some item information that was removed too. It had ID of the item, despawn time and stack size (as seen in the picture below)
![Rust Labs page without uBO showing right column](https://github.com/uBlockOrigin/uAssets/assets/50150516/ff0594c0-7b7e-43aa-b9be-d1416997ccd3)

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/e24b4c170691159fe404ed802ad73530b35cba42
