### ISSUE TITLE
codecanyon.net: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18958]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://codecanyon.net/item/whatsapp-instaorder-contactless-whatsapp-ordering-restaurant-menu-takeaway-delivery-table/30507382`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/98ad6df6-8813-48fc-ae47-189f48225bf4)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 25d.1h.30m
Chromium: 114
filterset (summary):
 network: 128986
 cosmetic: 148092
 scriptlet: 26289
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 9445-3, 37m
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 524-4, 1d.1h
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-524, 1d.20h.10m
  DEU-0: 6940-0, 19h.37m
  IDN-0: 9527-359, 1d.20h.11m
  RUS-0: 39580-50, 1d.20h.10m
  ara-0: 2326-6, 19h.36m
  easylist-annoyances: 3892-47, 1d.20h.11m
  easylist-chat: 129-0, 1d.20h.11m
  easylist-newsletters: 6268-16, 1d.20h.11m
  easylist-notifications: 2636-105, 1d.20h.11m
  fanboy-cookiemonster: 47712-233, 1d.20h.10m
  [2 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 68127-62, 1d.20h.11m
  easyprivacy: 33422-245, 1d.20h.11m
  plowe-0: 3739-1080, 1d.20h.10m
  ublock-badware: 7536-141, 1d.20h.10m
  ublock-filters: 33893-363, 1d.20h.10m
  ublock-privacy: 428-7, 1d.20h.10m
  ublock-quick-fixes: 363-84, 3h.7m
  ublock-unbreak: 2069-38, 1d.20h.10m
  urlhaus-1: 6502-1, 19h.35m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1948 ms (selfie)
 maxAssetCacheWait: 783 ms
popupPanel:
 blocked: 5
 network:
  cookiebot.com: 1
  envato.market: 1
  google-analytics.com: 1
  google.com: 2
 extended:
  ##.global-footer-social
```
</details>

**Comment by mapx-** [comment]
maybe an account is required => use the element picker to craft a filter

**Comment by 3xploiton3** [comment]
###js-customer-satisfaction-popup
or
##.survey-popup

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/3c01f733-8e59-4826-b2d2-53e52b1b1eb7)

**Comment by mapx-** [comment]
report at easylist repository

@ryanbr
