### ISSUE TITLE
asurascans.com: ads

### ISSUE THREAD

**Issue by jykeous** [uBlockOrigin/uAssets#18954]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.asurascans.com/the-novels-extra-chapter-65/`

### Category

ads

### Description

An ad appears at the bottom. This has never happened before, but now reappears every time I open a page on the site.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 96795
 cosmetic: 39504
 scriptlet: 17952
 html: 0
listset (total-discarded, last-updated): 
 added: 
  ublock-quick-fixes: 363-10, 1h.37m
 default: 
  user-filters: 0-0, never
  easylist: 67971-10, 3d.14h.23m
  easyprivacy: 33415-62, 3d.14h.24m
  plowe-0: 3738-1072, 9d.20h.39m
  ublock-badware: 7514-138, 3d.14h.25m
  ublock-filters: 33880-147, 3d.14h.26m
  ublock-privacy: 428-4, 3d.14h.28m
  ublock-unbreak: 2068-32, 3d.14h.27m
  urlhaus-1: 6502-1, 3h.37m
filterset (user): [empty]
trustedset: 
 added: [array of 17 redacted]
 removed: 
  chrome-scheme
  edge-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 429 ms (selfie)
 maxAssetCacheWait: 176 ms
popupPanel: 
 blocked: 10
 network: 
  adnxs.com: 1
  cloudflareinsights.com: 1
  disqus.com: 2
  narrative.io: 2
  pippio.com: 1
  rezync.com: 1
  viglink.com: 2
```
</details>

**Comment by mapx-** [comment]
- reset uBO to default settings / lists
**- update all the lists right now after resetting uBO**
- do not touch any setting / do not add any other list
- disable any other blocking / privacy extension
- test again

**Comment by dportvine** [comment]
@jykeous 

This ad?

<details>
<summary>Screen</summary>

![2023-07-12_120255](https://github.com/uBlockOrigin/uAssets/assets/111344219/4f0f6c7c-35c9-4713-9e51-2fdf812b17d7)
</details>

**Comment by krystian3w** [comment]
Nope, that is self-promo.

So you should check addresing in Annoyances lists.
