### ISSUE TITLE
terraria.fandom.com: ads

### ISSUE THREAD

**Issue by Whremp** [uBlockOrigin/uAssets#18959]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://terraria.fandom.com/wiki/Weapons`

### Category

ads

### Description

There is a pop-up on the bottom left of the screen which keeps reappearing even after manually blocking it each time.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![jfweoijiwghiewu](https://github.com/uBlockOrigin/uAssets/assets/133120770/085eb9af-565e-402c-b15b-1cd8edf3ef7b)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 20d.2h.42m
Chromium: 114
filterset (summary):
 network: 96931
 cosmetic: 39474
 scriptlet: 17886
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  easylist: 68239-11, 2h.18m
  easyprivacy: 33422-63, 2h.17m
  plowe-0: 3739-1073, 8d.10h.3m
  ublock-badware: 7539-140, 2h.19m
  ublock-filters: 33756-146, 2h.22m
  ublock-privacy: 425-4, 2h.20m
  ublock-quick-fixes: 356-84, 2h.15m
  ublock-unbreak: 2070-31, 2h.21m
  urlhaus-1: 6443-1, 2h.16m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 832 ms (selfie)
 maxAssetCacheWait: 372 ms
popupPanel:
 blocked: 27
 network:
  ad.gt: 2
  amazon-adsystem.com: 1
  amplitude.com: 1
  doubleclick.net: 1
  doubleverify.com: 1
  fastly-insights.com: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  imrworldwide.com: 1
  nocookie.net: 1
  quantserve.com: 1
  scorecardresearch.com: 1
  wikia-services.com: 12
 extended:
  ##.global-navigation__links
  ##.top-ads-container
  ##.ad-slot-placeholder
  ##.bottom-ads-container
  ##.gpt-ad
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  #@#.ad-slot
  ##+js(set-constant, wgAffiliateEnabled, false)
  ##+js(set-cookie, tracking_session_id, OK, , reload, 1)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
fandom.com##.marketing-notifications
```

@ryanbr 

Not sure if it counts as a self-promotion?

**Comment by ryanbr** [comment]
seems to be related to its own site functionality

**Comment by stephenhawk8054** [comment]
You can use the above filter as a custom filter.
