### ISSUE TITLE
koenigsegg.com: nuisance

### ISSUE THREAD

**Issue by brynnb** [uBlockOrigin/uAssets#18952]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.koenigsegg.com/`

### Category

nuisance

### Description

Cookie banner at bottom

Fixed with:

##section[data-component="n3-cookie-notice"]

### Other extensions used

privacy badger, clearURLs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1375" alt="Screenshot 2023-07-11 at 11 23 15 AM" src="https://github.com/uBlockOrigin/uAssets/assets/1271817/04423a47-8b03-43c7-b364-c9ac6bf51051">

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 27d.11h.33m
Firefox: 115
filterset (summary):
 network: 107144
 cosmetic: 184140
 scriptlet: 26405
 html: 1169
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68945-68945, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92013-92013, now
  adguard-social: 20898-824, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 47709-3833, now
  fanboy-social: 16099-23, now
  ublock-annoyances: 5259-10, now
  adguard-cookies: 26304-58, now
  adguard-popup-overlays: 22962-1436, now
  adguard-mobile-app-banners: 4409-1055, now
  adguard-other-annoyances: 13074-296, now
  adguard-widgets: 2196-1, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 66-3, never
  ublock-filters: 34628-462, now
  ublock-badware: 7538-0, now
  ublock-privacy: 464-0, now
  ublock-unbreak: 2113-0, now
  easylist: 68138-859, now
  easyprivacy: 33422-822, now
  urlhaus-1: 6502-1, now
  plowe-0: 3740-2, now
  ublock-quick-fixes: 365-0, now
filterset (user): [array of 67 redacted]
trustedset:
 added: [array of 78 redacted]
hostRuleset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 292 ms (selfie)
 maxAssetCacheWait: 74 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
@brynnb For future simple cookie banners, please report here:

* https://github.com/easylist/easylist/issues
* https://github.com/AdguardTeam/AdguardFilters/issues
