### ISSUE TITLE
minecraft.fandom.com: nuisance

### ISSUE THREAD

**Issue by Jodo42** [uBlockOrigin/uAssets#18955]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://minecraft.fandom.com/wiki/Minecraft_Wiki`

### Category

nuisance

### Description

"Personalize your Experience" overlay

### Other extensions used

SponsorBlock 
Bypass Paywalls Clean
Stylus
Dark Reader
Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 33d.9h.47m
Chromium: 114
filterset (summary):
 network: 97166
 cosmetic: 40838
 scriptlet: 21359
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gist.githubusercontent.com/Craftplacer/04089c2c666c89e10818124c92d9c65b/raw/FuckFandom.txt: 10-0, 22m
  ublock-annoyances: 5295-7, 4m
 default:
  user-filters: 58-5, never
  easylist: 68239-11, 1m
  easyprivacy: 33426-63, 1m
  plowe-0: 3740-1074, 24m
  ublock-badware: 7539-140, 1m
  ublock-filters: 33755-149, 1m
  ublock-privacy: 425-4, 1m
  ublock-unbreak: 2070-32, 1m
  urlhaus-1: 6443-1, 1m
filterset (user): [array of 59 redacted]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 167 ms (selfie)
 maxAssetCacheWait: 89 ms
popupPanel:
 blocked: 15
 network:
  fandom.com: 4
  ad.gt: 1
  fastly-insights.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  nocookie.net: 1
  quantserve.com: 1
  scorecardresearch.com: 1
  wikia-services.com: 4
 extended:
  ##.top-ads-container
  ##.ad-slot-placeholder
  ##.bottom-ads-container
  ##.AgeGateDialog-module_overlay__aPtu5.Modal_overlay__7pQwi
  ##.mcf-wrapper
  ##.global-navigation
  ##.main-container:style(width: 100% !important; margin-left: 0 !…
  ##.fandom-sticky-header:style(left:0 !important)
  ##+js(set-constant, wgAffiliateEnabled, false)
  ##+js(set-cookie, tracking_session_id, OK, , reload, 1)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
  ##+js(trusted-set-cookie, euconsent-v2, CPt3fQAPt3fQACNAFAENDLCg…
  ##+js(trusted-set-cookie, tracking-opt-in-status, rejected, 1yea…
  ##+js(trusted-set-cookie, addtl_consent, 1~, 1year)
```
</details>

**Comment by mapx-** [comment]
add

`minecraft.fandom.com###age-gate`

@ryanbr
