### ISSUE TITLE
projectorcentral.com: ads

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#18969]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.projectorcentral.com/Dell-2300MP.htm?add_compare_list=2591`

### Category

ads

### Description

Missing banner ads all over the page and even found in the comparison tab as well. 

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2023-07-12 at 11 10 13 PM](https://github.com/uBlockOrigin/uAssets/assets/69532417/e780c9a9-5f0e-4634-919a-a4af4a84f068)
![Screen Shot 2023-07-12 at 11 10 05 PM](https://github.com/uBlockOrigin/uAssets/assets/69532417/d67cd8ca-549a-4711-9a4e-e28c5961f29b)
![Screen Shot 2023-07-12 at 11 09 59 PM](https://github.com/uBlockOrigin/uAssets/assets/69532417/ea85f128-c3c8-4aa4-98d7-c6d5be467acf)
![Screen Shot 2023-07-12 at 11 09 53 PM](https://github.com/uBlockOrigin/uAssets/assets/69532417/646652d8-fae5-4567-a981-37307de66c50)
![Screen Shot 2023-07-12 at 11 09 50 PM](https://github.com/uBlockOrigin/uAssets/assets/69532417/eb781468-d9db-40f9-b0ad-a3e2a39b9373)
![Screen Shot 2023-07-12 at 11 09 45 PM](https://github.com/uBlockOrigin/uAssets/assets/69532417/da14afc1-b72a-4d98-aaca-a1cd143584e1)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 23d.41m
Chromium: 114
filterset (summary):
 network: 252755
 cosmetic: 206793
 scriptlet: 41160
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68994-103, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92029-21095, now
  adguard-generic: 72580-514, now
  adguard-mobile: 8397-57, now
  adguard-spyware-url: 1125-3, now
  block-lan: 47-0, now
  curben-phishing: 125804-27, 1m
  curben-pup: 189-0, 1m
  fanboy-cookiemonster: 47714-47714, now
  ublock-annoyances: 5296-281, now
 default:
  user-filters: 0-0, never
  easylist: 68100-1006, now
  easyprivacy: 33438-376, now
  plowe-0: 3740-1160, now
  ublock-badware: 7552-397, now
  ublock-filters: 33794-4138, now
  ublock-privacy: 425-8, now
  ublock-quick-fixes: 356-102, 1m
  ublock-unbreak: 2070-92, now
  urlhaus-1: 6453-3, 1m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5076 ms (selfie)
 maxAssetCacheWait: 3272 ms
popupPanel:
 blocked: 7
 network:
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
  infolinks.com: 1
  mouseflow.com: 1
 extended:
  ##.social-share
  ##ins.adsbygoogle
  ##a[href^="https://www.facebook.com/share.php?"]
```
</details>

**Comment by mapx-** [comment]
report the page at easylist repository

@ryanbr
