### ISSUE TITLE
Zero-width non-joiner appears in the file

### ISSUE THREAD

**Issue by monsm** [uBlockOrigin/uAssets#18967]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://[raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt)
Zero-width non-joiner appears in the file：
1337x.*,x1337x.*,1337x.unblock2.xyz,1337x.unblocked.*,1337x.unblockit.*##ul > li:has-text(/‌/i)

### URL(s) where the issue occurs.

none

### uBO version

newer

### Browser name and version

https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt

### Settings

none

**Comment by mapx-** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/5ca55ca8-cacf-446e-810c-02222ad76e19)
