### ISSUE TITLE
ww4.readneverland.com: ads

### ISSUE THREAD

**Issue by ebilthedebil** [uBlockOrigin/uAssets#18962]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ww4.readneverland.com/chapter/the-promised-neverland-chapter-83/`

### Category

ads

### Description

can still see ads or the leftover "boxes" they would be placed in when using ublock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://github.com/uBlockOrigin/uAssets/assets/60547672/caf7b816-ae66-4ae9-a0ea-5e38e2b98ad9)
![cringe ad](https://github.com/uBlockOrigin/uAssets/assets/60547672/771d6942-78e3-4565-8c10-e3ea7da94880)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 34d.13h.12m
Chromium: 114
filterset (summary):
 network: 97129
 cosmetic: 41503
 scriptlet: 17957
 html: 0
listset (total-discarded, last-updated):
 added:
  FIN-0: 2196-0, 2d.23h.56m
 default:
  user-filters: 0-0, never
  easylist: 68239-11, 8h.43m
  easyprivacy: 33407-63, 5d.4h.38m
  plowe-0: 3739-1074, 4d.27m
  ublock-badware: 7536-140, 1d.23h.15m
  ublock-filters: 33869-146, 1d.23h.14m
  ublock-privacy: 428-3, 2d.3h.26m
  ublock-quick-fixes: 363-78, 10h.44m
  ublock-unbreak: 2068-32, 1d.23h.13m
  urlhaus-1: 6443-1, 10h.44m
filterset (user): [empty]
trustedset:
 added: [array of 32 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 736 ms (selfie)
 maxAssetCacheWait: 200 ms
popupPanel:
 blocked: 6
 network:
  bidgear.com: 3
  cloudflareinsights.com: 1
  google-analytics.com: 1
  vlitag.com: 1
 extended:
  ##.adsbyvli
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
readneverland.com##.js-a-container
```

@ryanbr
