### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by ebaydan777** [uBlockOrigin/uAssets#18966]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.investing.com/indices/indices-futures`

### Category

detection

### Description

pop-up shows up detecting ublock

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 15d.9h.52m
Chromium: 114
filterset (summary):
 network: 96979
 cosmetic: 39465
 scriptlet: 17914
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68258-11, now
  easyprivacy: 33436-63, now
  plowe-0: 3740-1074, now
  ublock-badware: 7552-140, now
  ublock-filters: 33790-147, now
  ublock-privacy: 425-4, now
  ublock-quick-fixes: 356-101, now
  ublock-unbreak: 2070-31, now
  urlhaus-1: 6453-1, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 667 ms (selfie)
 maxAssetCacheWait: 140 ms
popupPanel:
 blocked: 11
 network:
  investing.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  dggaenaawxe8z.cloudfront.net: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  hotjar.com: 1
  primis.tech: 1
  scriptcdn.net: 1
 extended:
  ##.midHeader
  ##div[class^="ad_"]
  ##div[data-test="ad-slot-visible"]
  ##[class*="overlay_overlay"]
  ###__next > .fixed
  ##body:style(overflow: auto !important)
  ##+js(no-fetch-if, ads)
  ##+js(replace-node-text, script, /adb/i, xxx)
  ##+js(set-constant, adNotificationDetected, false)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you right click on the anti-adb popup -> Choose inspect element -> Screenshot to here?

**Comment by ebaydan777** [comment]
this https://i.imgur.com/GDO9ryk.png
?

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
investing.com##div[class] > [class*="adNotification"]:upward(1)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; `Apply changes` > Go back to the website > Press `Ctrl + Shift + R` (or `Cmd + Shift + R` on Mac) to reload the page and test again.

**Comment by mapx-** [comment]
it seems ok, we could remove the rpnt filter
