### ISSUE TITLE
fitgirl-repack.com: breakage

### ISSUE THREAD

**Issue by hhuseyinsil** [uBlockOrigin/uAssets#18963]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fitgirl-repack.com/`

### Category

breakage

### Description

Images are lost in the site and the design is broken

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![FitGirl-Repack-The-ONLY-official-site-for-FitGirl-Repacks-Every-single-FG-repack-installer-has-a-link-inside-which-leads-here-Do-not-fall-for-fake-and-scam-sites-which-are-using-my-name-](https://github.com/uBlockOrigin/uAssets/assets/10101438/e6cecc60-07bb-4ade-bc0b-c6dc2e83b38d)

uBlock Origin off;
![FitGirl-Repack-The-ONLY-official-site-for-FitGirl-Repacks-Every-single-FG-repack-installer-has-a-link-inside-which-leads-here-Do-not-fall-for-fake-and-scam-sites-which-are-using-my-name- (1)](https://github.com/uBlockOrigin/uAssets/assets/10101438/b4b07d20-91a0-4cfd-a5dc-6778b5fa15f6)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 54m
Chromium: 114
filterset (summary):
 network: 98736
 cosmetic: 49823
 scriptlet: 19341
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13613-11, 2m
  easylist: 68258-30, 2m
  easyprivacy: 33436-68, 2m
  plowe-0: 3740-1075, 2m
  ublock-badware: 7552-140, 2m
  ublock-filters: 33777-154, 2m
  ublock-privacy: 425-4, 2m
  ublock-quick-fixes: 356-89, 2m
  ublock-unbreak: 2070-32, 2m
  urlhaus-1: 6426-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 345 ms (selfie)
 maxAssetCacheWait: 152 ms
popupPanel:
 blocked: 50
 network:
  fitgirl-repack.com: 40
  cdn-server.top: 2
  googletagmanager.com: 4
  skimresources.com: 2
  wp.com: 2
```
</details>

**Comment by Daxy7** [comment]
this isn't the original website. see warning before visiting
https://github.com/uBlockOrigin/uAssets/assets/91396482/709144d5-5f89-49fa-8154-4e0fee1f647a
official website: 
```
https://fitgirl-repacks.site
```

**Comment by JobcenterTycoon** [comment]
Its blocked by the badware list because its a fake site. The real site is `https://fitgirl-repacks.site/`

If you want to bypass the filter add `||fitgirl-repack.*^$all,domain=~fitgirl-repacks.site,badfilter` as a custom filter (remember: Its NOT the official site)
