### ISSUE TITLE
statcounter homepage css broken

### ISSUE THREAD

**Issue by clark713** [uBlockOrigin/uAssets#18964]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The filter "uBlock filters – Unbreak" is not unblocking statcounter.  This issue only started about 1 or 2 months ago.  It blocks all css, js, etc, making the site unusable.  Before the recent change uBlock would block statcounter file counter.js but not the entire site.

! To counter `statcounter.com` in Peter Lowe's
||statcounter.com^$badfilter
||statcounter.com^$domain=~gs.statcounter.com
||c.statcounter.com^
||statcounter.com/counter/counter.js

### URL(s) where the issue occurs.

https://statcounter.com

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19604521/2e3675f1-e0ce-4730-a001-1969aa79f838)
![image](https://github.com/uBlockOrigin/uAssets/assets/19604521/e25b14e9-e4a5-44a5-a3c0-ac27cae84edb)

### uBO version

uBlock Origin 1.50.0

### Browser name and version

Chromium Version 112.0.5615.165 (Official Build) for Linux Mint (64-bit)

### Settings

Turned off all filters except "uBlock filters – Unbreak" to be sure this is blocking statcounter.

**Comment by Daxy7** [comment]
||statcounter.com^$from=~gs.statcounter.com$badfilter

then

||statcounter.com^$from=~statcounter.com `?`

what's gs parameter for

**Comment by stephenhawk8054** [comment]
The site is a service to collect data. If you still want to use it, you can turn off uBO on that page.

---

> what does the gs subdomain do?

It's for showing their globalstats charts and images: `https://gs.statcounter.com/`

**Comment by clark713** [comment]
Until  approx one month ago it wasn’t acting like this and it did not break
the site, this is a new thing.

**Comment by stephenhawk8054** [comment]
It was added on Apr 30: https://github.com/uBlockOrigin/uAssets/commit/5b5709debd46f0c973550100972f78e690032e41
