### ISSUE TITLE
wpamaze.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#18968]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wpamaze.com/speed-optimization-course/?fbclid=IwAR19MCwZ_l1UTHpq2umWduTBaIbIlpv3Yq6XRmfgZvG-Sf4xj8TuZOA7BhU`

### Category

breakage

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/905f55c8-3257-4722-ad60-2be977fba01f)

what wrong?
![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/41621c10-6359-4f32-968f-da988648d55e)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 25d.20h.50m
Chromium: 114
filterset (summary):
 network: 129102
 cosmetic: 147987
 scriptlet: 26311
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 9485-3, now
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 524-4, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-524, now
  DEU-0: 6940-0, now
  IDN-0: 9535-359, now
  RUS-0: 39592-50, now
  ara-0: 2325-6, now
  easylist-annoyances: 3893-47, now
  easylist-chat: 129-0, now
  easylist-newsletters: 6268-16, now
  easylist-notifications: 2631-104, now
  fanboy-cookiemonster: 47714-234, now
  [2 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 68266-61, now
  easyprivacy: 33438-244, now
  plowe-0: 3740-1080, now
  ublock-badware: 7552-142, now
  ublock-filters: 33790-362, now
  ublock-privacy: 425-7, now
  ublock-quick-fixes: 356-101, now
  ublock-unbreak: 2070-38, now
  urlhaus-1: 6453-1, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1843 ms (selfie)
 maxAssetCacheWait: 411 ms
popupPanel:
 blocked: 0
 extended:
  ##.formkit-form.seva-form
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
extended:
  ##.formkit-form.seva-form
```

You are using EasyList Newsletter list. Please report here: https://github.com/easylist/easylist/issues

**Comment by 3xploiton3** [comment]
i want newsletter form by click button or click some link, but not for popup banner

thx for the suggestion, now i'm disabling EasyList – Newsletter Notices

**Comment by Sonic5435325** [comment]
Personally, I don't see why this should be fixed even in Fanboy's Annoyance. If anything, the popup associated here should also be hidden too, since it seems to be nothing but an annoyance as well.
If you want to see newsletter boxes, don't enable EasyList - Newsletter Notices or AdGuard - Widgets.
