### ISSUE TITLE
Delete all three issues I have opened and stop closing them. I will spam this board if you don't.

### ISSUE THREAD

**Issue by pigster117** [uBlockOrigin/uAssets#18972]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Delete all three issues I have opened and stop closing them. I will spam this board if you don't.

### URL(s) where the issue occurs.

Delete all three issues I have opened and stop closing them. I will spam this board if you don't.

### Screenshot(s)

Delete all three issues I have opened and stop just closing them. I will spam this board if you don't.

### uBO version

Delete all three issues I have opened and stop closing them. I will spam this board if you don't.

### Browser name and version

Delete all three issues I have opened and stop closing them. I will spam this board if you don't.

### Settings

Delete all three issues I have opened and stop closing them. I will spam this board if you don't.

### Notes

Delete all three issues I have opened and stop closing them. I will spam this board if you don't.

**Comment by pigster117** [comment]
Delete all three issues I have opened and stop closing them. I will spam this board if you don't.

**Comment by mapx-** [comment]
@gorhill @okiehsch could you ban this user

**Comment by okiehsch** [comment]
Done.
