### ISSUE TITLE
[nsfw] mitaku.net: popups

### ISSUE THREAD

**Issue by AsianPutin** [uBlockOrigin/uAssets#18971]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mitaku.net/`

### Category

popups, detection

### Description

on desktop it'll automatically delete the tab without problems, but on firefox mobile with the ublock add-on, it'll stay and spamming the back button nothing but refreshes and forces the play store to open.

as for detection, well its the same ol' detection that begs the users to disable it. nothing else

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/67151499/e11ec7ba-53c4-48f8-bcf6-475b90addcfe)

only active tab is the cookies one, the rest are for other sites. not even tamper monkey is used

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 28d.14h.37m
Firefox: 115
filterset (summary):
 network: 96816
 cosmetic: 39481
 scriptlet: 17870
 html: 996
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34670-79, now
  ublock-badware: 7554-0, now
  ublock-privacy: 464-0, now
  ublock-unbreak: 2114-0, now
  ublock-quick-fixes: 358-0, 23m
  easylist: 68100-768, now
  easyprivacy: 33438-726, now
  urlhaus-1: 6453-1, 25m
  plowe-0: 3740-2, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1766 ms (selfie)
 maxAssetCacheWait: 1230 ms
popupPanel:
 blocked: 9
 network:
  godpvqnszo.com: 2
  googletagmanager.com: 1
  limurol.com: 3
  ohfapzvhun.com: 1
  xdiwbc.com: 2
 extended:
  ##+js(noeval-if, /chp_?ad/)
```
</details>

**Comment by mapx-** [comment]
- update all your filter lists, test again
- if does not work disable all other addons and test again
