### ISSUE TITLE
anime-rebornx.blogspot.com.ar [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1898]
URL(s) where the issue occurs

`http://anime-rebornx.blogspot.com.ar/2016/12/god-eater-1313-bd-1080p-1gb-mega.html`

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`@@||anime-rebornx.blogspot.*^$generichide`

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
