### ISSUE TITLE
animeidhentai.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1899]
URL(s) where the issue occurs

`https://animeidhentai.com/18022/do-s-na-seitokaichou-sama-ga-m-note-ni-shihai-saremashita-episode-2-02`

Describe the issue

ADS

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by gorhill** [comment]
Does this work?

    animeidhentai.com##a[target] > img[src$=".gif"]
    animeidhentai.com##.desktopads

**Comment by KiLL4FuNK** [comment]
It works perfect  @gorhill @mapx-

**Comment by KiLL4FuNK** [comment]
ADS
