### ISSUE TITLE
onlineticketing.cineplex.com

### ISSUE THREAD

**Issue by chuckkahn** [uBlockOrigin/uAssets#19]
https://onlineticketing.cineplex.com/TicketCart.aspx?guid=2d8d6ca8-860b-4cdc-a187-8cd281765c5e

I was delayed from completing my movie ticket transaction by the Cineplex "Please wait..." graphic that wouldn't go away.  I disabled uBlockOrigin and reloaded the page and restarted my transaction and was able to buy my tickets, but not the seats I originally wanted.  Is there a way to toggle uBlockOrigin off from the Chrome menu so I can reliably make ticket purchases from this site in future?  
- Browser/version: Chrome Version 49.0.2623.110 (64-bit)
- uBlock Origin version: v1.6.8

**Comment by gorhill** [comment]
> Is there a way to toggle uBlockOrigin off from the Chrome menu

The big blue button: <https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button>.

Unfortunately, if the issue occurs at the point of completing a buy, I won't be able to reproduce on my side. What would have helped is the errors reported in the developer console of the page.

**Comment by c-s-h-i-r** [comment]
I too have encountered this issue multiple times. It's easy enough to restart the whole transaction with ublock origin disabled, but an annoyance.
Browser/version: Chrome 51.0.2704.103 (64 bit)
uBlock Origin version v1.7.2

I have been able to reproduce this by:
1. Going to any movie and selecting a showtime 
https://onlineticketing.cineplex.com/Scene.aspx?guid=96172e94-1deb-492e-9873-8f36999bd995&platform=&platformversion=&appversion=

2. Clicking PROCEED WITHOUT SCENE or PROCEED

Console output: 
Navigated to https://onlineticketing.cineplex.com/Scene.aspx?guid=96172e94-1deb-492e-9873-8f36999bd995&platform=&platformversion=&appversion=
Scene.aspx:23 GET https://onlineticketing.cineplex.com/Styles/ads.css net::ERR_BLOCKED_BY_CLIENT
Scene.aspx:43 GET https://onlineticketing.cineplex.com/scripts/omniture/VisitorAPI.js net::ERR_BLOCKED_BY_CLIENT
Scene.aspx:44 GET https://onlineticketing.cineplex.com/scripts/omniture/AppMeasurement.js net::ERR_BLOCKED_BY_CLIENT
Scene.aspx:561 GET https://onlineticketing.cineplex.com/scripts/ads/googleAdTags.js net::ERR_BLOCKED_BY_CLIENT
csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=apiboot2&e=10_1_0,10_2_0&rt=main.10:1 GET https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=apiboot2&e=10_1_0,10_2_0&rt=main.10 net::ERR_BLOCKED_BY_CLIENT
Cineplex.Omniture.js:128 Uncaught ReferenceError: s is not definedcineplexOmniture.setOmnitureVars @ Cineplex.Omniture.js:128cineplexOmniture.omnitureOnLoad @ Cineplex.Omniture.js:181(anonymous function) @ Cineplex.Omniture.js:194c @ jquery-1.10.2.min.js:4fireWith @ jquery-1.10.2.min.js:4ready @ jquery-1.10.2.min.js:4q @ jquery-1.10.2.min.js:4
csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=apiboot2&e=10_1_0,10_2_0&rt=firstmap.157:1 GET https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=apiboot2&e=10_1_0,10_2_0&rt=firstmap.157 net::ERR_BLOCKED_BY_CLIENT
csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=true&hdpi=…viewport=true&e=10_1_0,10_2_0&rt=staticmap.91,firstpixel.91,allpixels.91:1 GET https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=tr…adviewport=true&e=10_1_0,10_2_0&rt=staticmap.91,firstpixel.91,allpixels.91 net::ERR_BLOCKED_BY_CLIENT
csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=true&hdpi=…aticmap=true&size=214x230&hadviewport=true&e=10_1_0,10_2_0&rt=visreq.199:1 GET https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=tr…staticmap=true&size=214x230&hadviewport=true&e=10_1_0,10_2_0&rt=visreq.199 net::ERR_BLOCKED_BY_CLIENT
maps.googleapis.com/maps/gen_204?target=api&ev=api_viewport&cad=host:online…2x0.01837,size:214x230,relsize:0.05,token:8y78i939ge,src:apiv3,ts:ts34yd:1 GET https://maps.googleapis.com/maps/gen_204?target=api&ev=api_viewport&cad=hos…432x0.01837,size:214x230,relsize:0.05,token:8y78i939ge,src:apiv3,ts:ts34yd net::ERR_BLOCKED_BY_CLIENT
csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=true&hdpi=…aticmap=true&size=214x230&hadviewport=true&e=10_1_0,10_2_0&rt=visres.353:1 GET https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=tr…staticmap=true&size=214x230&hadviewport=true&e=10_1_0,10_2_0&rt=visres.353 net::ERR_BLOCKED_BY_CLIENT
csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=true&hdpi=…cmap=true&size=214x230&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.386:1 GET https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=tr…ticmap=true&size=214x230&hadviewport=true&e=10_1_0,10_2_0&rt=firsttile.386 net::ERR_BLOCKED_BY_CLIENT
csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=true&hdpi=…ap=true&size=214x230&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.388:1 GET https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=25.6&action=map2&firstmap=tr…cmap=true&size=214x230&hadviewport=true&e=10_1_0,10_2_0&rt=tilesloaded.388 net::ERR_BLOCKED_BY_CLIENT
Cineplex.Omniture.js:103 Uncaught ReferenceError: s is not definedfn_submit_track @ Cineplex.Omniture.js:103Page_ClientValidate @ Cineplex.Omniture.js:116Validate @ site-ticketing.js:435onclick @ Scene.aspx?guid=96172e94-1deb-492e-9873-8f36999bd995&platform=&platformversion=&appversion=:280
Cineplex.Omniture.js:103 Uncaught ReferenceError: s is not defined
Here is the console output from this sequence:

I'm unsure of what exactly you need from the console so let me know if you need more.

**Comment by gorhill** [comment]
You need to look at [uBO's own logger](https://github.com/gorhill/uBlock/wiki/The-logger) to know which block filters are involved.

**Comment by c-s-h-i-r** [comment]
Here is the output that's displayed in the uBO log.
[consoleLog.pdf](https://github.com/uBlockOrigin/uAssets/files/331947/consoleLog.pdf)

What is the best way to save the console to a file?

**Comment by mapx-** [comment]
try
```
@@||assets.adobedtm.com/*/satelliteLib-$script,domain=cineplex.com
@@*omniture*$script,domain=cineplex.com
```
