### ISSUE TITLE
tiktok.com: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#19009]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The video will automatically pause itself if you switch tabs while playing it.
Also, an anti-right click on suggestion thumbnails in "You may like".

### URL(s) where the issue occurs.

`https://www.tiktok.com/@coloradopedpatrol/video/7197626481512549674`

### uBO version

v1.50.1b17

### Browser name and version

Firefox 115.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by Daxy7** [comment]
seems that something changed in tiktok code and `##+js(aeld, visibilitychange, pagehide)` no longer keeps the video playing in a new tab. test link:
```
https://www.tiktok.com/@brian..smith/video/7212036071213862150
```
