### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by CarlosEchavez** [uBlockOrigin/uAssets#19008]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Description

ads

### Other extensions used

uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 30d.14h.18m
Chromium: 114
filterset (summary):
 network: 99290
 cosmetic: 45372
 scriptlet: 18213
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 67969-10, 2d.20h.28m
  easyprivacy: 33417-63, 4d.3h.51m
  plowe-0: 3738-1073, 11d.18h.21m
  spa-0: 3736-12, 3h.55m
  spa-1: 5327-215, 3d.23h.49m
  ublock-badware: 7539-139, 1d.3h.37m
  ublock-filters: 33756-172, 1d.3h.38m
  ublock-privacy: 425-4, 3h.57m
  ublock-quick-fixes: 356-16, 3h.54m
  ublock-unbreak: 2070-33, 1d.19h.6m
  urlhaus-1: 6434-0, 3h.56m
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 884 ms (selfie)
 maxAssetCacheWait: 337 ms
popupPanel:
 blocked: 143
 network:
  youtube.com: 91
  doubleclick.net: 14
  google.com: 18
  google.com.co: 1
  googleadservices.com: 2
  googlesyndication.com: 17
 extended:
  ###player-ads
  ###masthead-ad
  ###merch-shelf
  ##.ytd-ad-slot-renderer
  ##.ytd-companion-slot-renderer
  ##.ytd-in-feed-ad-layout-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytd-rich-item-renderer > ytd-ad-slot-renderer
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##ytd-display-ad-renderer
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
