### ISSUE TITLE
hemmakvall.se: breakage

### ISSUE THREAD

**Issue by egonprint** [uBlockOrigin/uAssets#19001]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hemmakvall.se/`

### Category

breakage

### Description

cookie page not showing and thats brakes the page completley

### Other extensions used

DuckDuckGo Privacey Essential
Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1d.22h.58m
Firefox: 115
filterset (summary):
 network: 98449
 cosmetic: 42036
 scriptlet: 18151
 html: 1010
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34675-80, now
  ublock-badware: 7554-0, now
  ublock-privacy: 464-0, now
  ublock-unbreak: 2114-0, now
  ublock-quick-fixes: 364-0, now
  easylist: 68099-776, now
  easyprivacy: 33438-732, now
  urlhaus-1: 6453-1, now
  plowe-0: 3740-2, now
  SWE-1: 4490-2, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 973 ms (selfie)
 maxAssetCacheWait: 130 ms
popupPanel:
 blocked: 0
 extended:
  ###cliSettingsPopup.cli-modal
  ##div.cli-modal-backdrop
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `###cliSettingsPopup.cli-modal` in `Frellwit's Swedish Filter` list

```adb
hemmakvall.se#@##cliSettingsPopup.cli-modal
```

cc @lassekongo83
