### ISSUE TITLE
sa.investing.com: nuisance

### ISSUE THREAD

**Issue by mmibm** [uBlockOrigin/uAssets#19000]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sa.investing.com/currencies/xau-usd-news`

### Category

nuisance

### Description

Overlays on this page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 30d.10h.46m
Chromium: 114
filterset (summary):
 network: 309641
 cosmetic: 226731
 scriptlet: 41694
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 68913-103, 1d.22h.21m
  adguard-cookies: 26320-26291, 2h.41m
  adguard-generic: 72549-462, 1d.1h.34m
  adguard-mobile: 8397-47, 2h.39m
  adguard-mobile-app-banners: 4414-4410, 2h.41m
  adguard-other-annoyances: 13083-13068, 2h.41m
  adguard-popup-overlays: 22978-22929, 2h.41m
  adguard-social: 20912-886, 3h.59m
  adguard-spyware: 63165-1323, 1d.1h.33m
  adguard-spyware-url: 1125-3, 17h.30m
  adguard-widgets: 2199-2195, 2h.41m
  ara-0: 2325-15, 39m
  [12 lists not shown]: [too many]
 default:
  user-filters: 137-5, never
  easylist: 67885-1237, 5d.1h.25m
  easyprivacy: 33424-17075, 3d.1h.31m
  plowe-0: 3739-1572, 4d.9h.19m
  ublock-badware: 7514-396, 3d.21h.6m
  ublock-filters: 33869-4174, 3d.21h.5m
  ublock-privacy: 428-65, 2d.2h.23m
  ublock-quick-fixes: 356-16, 9h.6m
  ublock-unbreak: 2068-136, 3d.21h.4m
  urlhaus-1: 6453-3, 3h.58m
filterset (user): [array of 137 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 collapseBlocked: false
 largeMediaSize: 1024
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 15902 ms (selfie)
 maxAssetCacheWait: 1592 ms
popupPanel:
 blocked: 10
 no-popups: true
 network:
  investing.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  hotjar.com: 1
  pbxai.com: 1
  primis.tech: 1
 extended:
  ##.py-10.px-12
  ##div[data-test="ad-slot-visible"]
  ##.midHeader
  ##[class*="overlay_overlay"]
  ###__next > .fixed
  ##body:style(overflow: auto !important)
  ##+js(set-constant, window.google_ad_status, 1)
  ##+js(remove-class, has-ads-free-promo-header, body)
  ##+js(set-constant, adNotificationDetected, false)
  ##+js(no-setTimeout-if, ===window.getComputedStyle()
  ##+js(no-fetch-if, /pagead2\.googlesyndication\.com|yandex\.ru\/…
  ##+js(no-fetch-if, ads)
  ##+js(replace-node-text, script, /adb/i, xxx)
```
</details>

**Comment by mmibm** [comment]
Thanks

**Comment by stephenhawk8054** [comment]
Please test this: https://github.com/uBlockOrigin/uAssets/issues/18966#issuecomment-1633607204
