### ISSUE TITLE
battlelog.battlefield.com: breakage

### ISSUE THREAD

**Issue by Patrxgt** [uBlockOrigin/uAssets#19005]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://battlelog.battlefield.com/`

### Category

breakage

### Description

When using uBlockOrigin, site stops recognizing Origin/EA App client and doesn't allow to open the game (Affects Battlefield 3, Battlefield 4 (although, this one has been adopted for unified Battlefield launcher, so launching through Battlelog isn't the only option), Battlefield Hardline, Battlefield 1 (same as BF4) and Medal of Honor Warfighter).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bez tytułu](https://github.com/uBlockOrigin/uAssets/assets/62941214/5f02f622-ffd7-468e-beb8-3bb9c01a788c)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 30d.16h.20m
Firefox: 115
filterset (summary):
 network: 305046
 cosmetic: 226447
 scriptlet: 41723
 html: 1183
listset (total-discarded, last-updated):
 added:
  adguard-generic: 72599-6643, now
  adguard-spyware-url: 1125-5, now
  block-lan: 47-0, now
  curben-phishing: 122696-60, now
  curben-pup: 189-0, now
  adguard-social: 20918-825, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 47715-3836, now
  fanboy-social: 16100-23, now
  ublock-annoyances: 5261-18, now
  dpollock-0: 11532-468, now
  adguard-spyware: 63176-17418, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 87-0, never
  ublock-filters: 34691-514, now
  ublock-badware: 7554-0, now
  ublock-privacy: 464-0, now
  ublock-unbreak: 2115-1, now
  ublock-quick-fixes: 358-0, 1h.7m
  easylist: 68099-1074, now
  easyprivacy: 33438-897, now
  urlhaus-1: 6434-0, now
  plowe-0: 3740-2, now
  POL-0: 7968-41, now
  POL-2: 1278-12, now
filterset (user): [array of 87 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1557 ms
 maxAssetCacheWait: 912 ms
popupPanel:
 blocked: 3
 network:
  127.0.0.1: 2
  google-analytics.com: 1
 extended:
  ###footer-share
  ###fb-root:not(body):not(html)
```
</details>

**Comment by Patrxgt** [comment]
> Do you need an account to reproduce the issue?

Yes, you need an EA account and one of the games bought either on EA App/Origin or Steam.

**Comment by Patrxgt** [comment]
> > stops recognizing Origin/EA App client
> 
> > `127.0.0.1: 2`
> 
> Test without `block-lan` list.

I've tested it and now Battlelog functions properly. EA App/Origin is recognized and game launches without any problems.

**Comment by gorhill** [comment]
> game launches without any problems

When you try to login, what are the network request details related to `127.0.0.1` reported in the logger?

**Comment by Patrxgt** [comment]
> > game launches without any problems
> 
> When you try to login, what are the network request details related to `127.0.0.1` reported in the logger?
![obraz](https://github.com/uBlockOrigin/uAssets/assets/62941214/54675177-26ef-44c9-8a10-62b241cd1e82)
![obraz](https://github.com/uBlockOrigin/uAssets/assets/62941214/edbd0542-e6f9-4ddd-b445-a382f1d13e0c)
![obraz](https://github.com/uBlockOrigin/uAssets/assets/62941214/0ed6b22b-db93-4ab1-b9b9-98dcaa7c3c22)
![obraz](https://github.com/uBlockOrigin/uAssets/assets/62941214/cf19db4f-e2f7-4cbe-884f-232ef7d9dc71)
![obraz](https://github.com/uBlockOrigin/uAssets/assets/62941214/dc107b3b-78db-49fa-b888-4d5daad42480)

(I've hidden my port and account ID for safety measures)

**Comment by gorhill** [comment]
@gwarser should we add an exception?

**Comment by gorhill** [comment]
@Patrxgt If you subscribe again to block-lan, and add the following exception filter to your filter, is the issue solved?

    @@||127.0.0.1^$xhr,domain=battlelog.battlefield.com

**Comment by Patrxgt** [comment]
> @Patrxgt If you subscribe again to block-lan, and add the following exception filter to your filter, is the issue solved?
> 
> ```
> @@||127.0.0.1^$xhr,domain=battlelog.battlefield.com
> ```

I'm using this exception filter: @@||127.0.0.1*$domain=battlelog.battlefield.com, but the one, that you've sent me works too.

**Comment by gorhill** [comment]
The exception filter was accidentally committed in <https://github.com/uBlockOrigin/uAssets/commit/d5dbd2a134f8b79a45bdb40bcffc4381057a2f29>, so you can remove your custom filter now.
