### ISSUE TITLE
[nsfw] theporndude.com: breakage

### ISSUE THREAD

**Issue by ugzv** [uBlockOrigin/uAssets#19002]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://theporndude.com/blog/your-pleasure-upgraded-the-top-vr-headsets-for-adult-content-in-2023/`

### Category

breakage

### Description

Description:
I am currently experiencing an issue while using uBlock Origin where I am unable to visit external links on a blog. Specifically, when I try to click on links like `https://porndude.link/virtualrealporn` from the blog, these links are inaccessible. This problem only occurs when uBlock Origin is enabled.

URL address of the web page:
`https://theporndude.com/blog/your-pleasure-upgraded-the-top-vr-headsets-for-adult-content-in-2023/`

### Other extensions used

https://chrome.google.com/webstore/detail/link-redirect-trace/nnpljppamoaalgkieeciijbcccohlpoh

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![V7bueno5B](https://github.com/uBlockOrigin/uAssets/assets/25570106/dbc7e326-21ea-4706-a68b-15399ec7c5d2)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 29d.11h.53m
Chromium: 114
filterset (summary):
 network: 96831
 cosmetic: 39501
 scriptlet: 17945
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  easylist: 68120-11, 4h.4m
  easyprivacy: 33415-63, 3d.3h.49m
  plowe-0: 3739-1074, 4d.1h.51m
  ublock-badware: 7514-140, 4d.3h.57m
  ublock-filters: 33869-145, 4d.3h.56m
  ublock-privacy: 428-4, 2d.3h.45m
  ublock-quick-fixes: 363-78, 4h.3m
  ublock-unbreak: 2068-32, 4d.3h.55m
  urlhaus-1: 6453-1, 4h.3m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 69 redacted]
switchRuleset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 592 ms (selfie)
 maxAssetCacheWait: 192 ms
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  google-analytics.com: 1
  googletagmanager.com: 1
 extended:
  ##body::before
  ##+js(window.open-defuser)
```
</details>

**Comment by okiehsch** [comment]
Those are affiliated links and point to third-party sites.
`theporndude.com#@#+js(nowoif)`
fixes the issue.

**Comment by gorhill** [comment]
Related: <https://github.com/uBlockOrigin/uAssets/commit/fa5025941d0>.

**Comment by gorhill** [comment]
Right-click and open link in new tab works, and so does middle mouse button. Will close for now as I do not know whether the filter which was added above can be safely removed. cc @Yuki2718

**Comment by Yuki2718** [comment]
@gorhill BTW AG Other Annoyances has the same rule, but the logger thinks they are different and `theporndude.com#@#+js(nowoif)` counters only one of them:

![nowoif](https://github.com/uBlockOrigin/uAssets/assets/58900598/254dc8b6-b9b0-4e98-aa8c-83757cb5c6a3)

**Comment by Yuki2718** [comment]
> [`window.open-defuser.js`](https://github.com/gorhill/uBlock/blob/f9bb66461647d2e1bdd110ffd9ef8aef962b90d1/src/web_accessible_resources/window.open-defuser.js) is a different scriptlet than [`no-window-open-if.js`](https://github.com/gorhill/uBlock/blob/f9bb66461647d2e1bdd110ffd9ef8aef962b90d1/assets/resources/scriptlets.js#L1858-L1945).

I remember you announced something about that, but can't find. So they are no more aliases.

**Comment by gorhill** [comment]
`window.open-defuser.js` is to be used as a redirection target, it sits in `web_accessible_resources`. However I don't see it being used this way in all the stock filter lists. Given this, I will remove the `window.open-defuser.js` file, and add the name as an alias for `no-window-open-if`.

**Comment by urosino** [comment]
@gorhill I think the current rule under "uBlock filters – Ads" is also affecting the search function.

<img width="439" alt="Porn Dude - Best Porn Sites   Free Porn Tubes List of 2023!wiFehgNM" src="https://github.com/uBlockOrigin/uAssets/assets/25570106/1c1ae81d-d2ed-4383-84f0-ab43f4d2efbe">

**Comment by Vitalik93** [comment]
Maybe Annoyances?
![Image](https://github.com/user-attachments/assets/58abc857-69e7-45db-8ff7-459b4d9267d2)

**Comment by stephenhawk8054** [comment]
Report at https://github.com/easylist/easylist/issues

**Comment by Vitalik93** [comment]
> Report at https://github.com/easylist/easylist/issues

Waiting there for weeks for an answer? No, thanks.

**Comment by Vitalik93** [comment]
@Yuki2718
