### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by jakubstaszak-com** [uBlockOrigin/uAssets#19011]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch`

### Category

breakage

### Description

Subtitles are invisible on any youtube video. Transcription works flawlessly. When saving subtitle settings within a video, a subtitle-message shows properly, but video subtitles still invisible.

### Other extensions used

none
none
none related

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-07-13 at 23-20-30 Will it work A 50-year old 74151 chip](https://github.com/uBlockOrigin/uAssets/assets/42867129/affe1277-2773-47fb-b6b4-441dcb802080)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 30d.7h.5m
Firefox: 115
filterset (summary):
 network: 98213
 cosmetic: 47071
 scriptlet: 18093
 html: 1009
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 365-0, 6m
 default:
  user-filters: 47-0, never
  ublock-filters: 34703-227, now
  ublock-badware: 7559-0, now
  ublock-privacy: 464-0, now
  ublock-unbreak: 2115-0, now
  easylist: 68099-634, now
  easyprivacy: 33438-768, now
  urlhaus-1: 6434-0, now
  plowe-0: 3741-2, now
  POL-0: 7968-27, 7m
  POL-2: 1278-12, now
filterset (user): [array of 47 redacted]
trustedset:
 added: [array of 48 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 626 ms (selfie)
 maxAssetCacheWait: 291 ms
popupPanel:
 blocked: 9
 network:
  youtube.com: 7
  doubleclick.net: 2
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytd-companion-slot-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##ytd-companion-slot-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
default:
  user-filters: 47-0, never
```

You are using 47 custom filters. Check them first.

If you have issues, please continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636
