### ISSUE TITLE
computerbild.de: breakage

### ISSUE THREAD

**Issue by wedoro** [uBlockOrigin/uAssets#19018]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.computerbild.de/`

### Category

breakage

### Description

Hi, When "uBlock filters – Ads " "on" the blue regions arn`t functonal. ( Firefox 115.0.2 ) 

### Other extensions used

keine

### Screenshot(s)

![Screenshot 2023-07-14 at 13-34-59 COMPUTER BILD Test Download Ratgeber   Kurse Kaufberatung Video](https://github.com/uBlockOrigin/uAssets/assets/118746905/ef6d262b-933e-4f88-8279-8a6d13005dd9)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 22h.48m
Firefox: 115
filterset (summary):
 network: 159238
 cosmetic: 160590
 scriptlet: 38191
 html: 999
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  plowe-0: null
 added:
  https://adguard.com/en/filter-rules.html?id=15: 53050-241, 52m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69044-104, 52m
  https://filters.adtidy.org/extension/ublock/filters/2_optimized.txt: 64038-29824, 52m
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 665-0, 52m
  adguard-spyware: 63179-4057, 52m
  adguard-cookies: 26339-26339, 52m
  fanboy-cookiemonster: 47726-3736, 52m
 default:
  user-filters: 15-0, never
  ublock-filters: 34707-678, 52m
  ublock-badware: 7559-0, 52m
  ublock-privacy: 468-2, 52m
  ublock-unbreak: 2116-1, 52m
  ublock-quick-fixes: 368-0, 52m
  easylist: 68197-26376, 52m
  urlhaus-1: 6231-0, 52m
  DEU-0: 6940-7, 52m
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 35 redacted]
 removed:
  about-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 110 redacted]
 removed:
  no-csp-reports: * true
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cnameUncloakEnabled: false
hiddenSettings:
 autoUpdatePeriod: 7
supportStats:
 allReadyAfter: 505 ms (selfie)
 maxAssetCacheWait: 301 ms
popupPanel:
 blocked: 13
 no-cosmetic-filtering: true
 network:
  computerbild.de: 3
  adnxs.com: 8
  asadcdn.com: 2
```
</details>

**Comment by gorhill** [comment]
Caused by:

    computerbild.de##^script:has-text(===):has-text(/[\w\W]{16000}/)
