### ISSUE TITLE
lapresse.ca: nuisance

### ISSUE THREAD

**Issue by ravertine** [uBlockOrigin/uAssets#19015]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.lapresse.ca/affaires/techno/2023-07-13/intelligence-artificielle/le-robot-de-google-disponible-presque-partout-sauf-au-canada.php`

### Category

nuisance

### Description

website allows 2 free articles / months. After those 2 articles are viewed, a banner at bottom asks to create an account and scroll bar is also disabled.

disabling javascript allows to view more articles, but it breaks some features of the website

### Other extensions used

too many to list

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/97376305/2e97035b-6c47-4dd4-9d0e-fdba58a10975)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 30d.14h.20m
Firefox: 115
filterset (summary):
 network: 115038
 cosmetic: 48516
 scriptlet: 17999
 html: 999
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  ublock-quick-fixes: 365-0, now
 default:
  user-filters: 55-0, never
  ublock-filters: 34703-159, now
  ublock-badware: 7559-1, now
  ublock-privacy: 464-0, now
  ublock-unbreak: 2116-0, now
  easylist: 68104-1012, now
  easyprivacy: 33388-726, now
  urlhaus-1: 6231-0, now
  plowe-0: 3741-1, now
  FRA-0: 28281-347, now
filterset (user): [array of 55 redacted]
trustedset:
 added: [array of 312 redacted]
switchRuleset:
 added: [array of 26 redacted]
hostRuleset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 180
 autoUpdatePeriod: 4
 extensionUpdateForceReload: true
 manualUpdateAssetFetchPeriod: 1
 popupPanelLockedSections: 39
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 487 ms (selfie)
 maxAssetCacheWait: 123 ms
popupPanel:
 blocked: 10
 network:
  lapresse.ca: 1
  google.com: 2
  googletagmanager.com: 1
  googletagservices.com: 1
  optable.co: 2
  rubiconproject.com: 2
  scorecardresearch.com: 1
 extended:
  ##.adsWrapper
  ##+js(set-constant, noBlocker, true)
  ##+js(abort-on-property-write, _sp_)
```
</details>

**Comment by stephenhawk8054** [comment]
Needs dev build:

```adb
lapresse.ca##+js(set-local-storage-item, lp.message.wall.active, $remove$)
lapresse.ca##body > div[style^="position"]:not([class]):not([id])
```

Not sure if it counts as paywall?

**Comment by ravertine** [comment]
it is more an annoyance rather than a real paywall since creating an account if free

updated to 1.50.1beta17; added the filters you mentioned and the banner is gone; thanks !

**Comment by gorhill** [comment]
In any case, if to be fixed, should be fixed in EasyList/AdGuard Annoyances?

**Comment by stephenhawk8054** [comment]
So in general, should we address login wall in uAssets? And should it be in main list, privacy list or annoyance list? I remember there were some instances that we address in main list, but some were in annoyance list.

**Comment by gorhill** [comment]
Definitely in Annoyances, but I thought this could be addressed in EasyList/AdGuard since they support using filter syntax compatible with uBO.

**Comment by stephenhawk8054** [comment]
@Yuki2718 Do you know if Adguard addresses login wall? If so, I'll notify Alex too.

**Comment by Yuki2718** [comment]
No, don't address.

**Comment by Alex-302** [comment]
@Yuki2718 https://github.com/AdguardTeam/Scriptlets/issues/338

**Comment by bi0hazard6** [comment]
The banner is back and I can't get rid of it. In zap mode I can select the correct element but in pick mode, I can't select the right element to enable the scrolling back.
[Just go on lap](https://www.lapresse.ca/actualites/2023-11-29/negociations-du-secteur-public/une-bonne-discussion-entre-les-chefs-syndicaux-et-lebel.php)

**Comment by gorhill** [comment]
Try:

    lapresse.ca##.brz_msg_wall_body
    lapresse.ca##body:style(overflow: auto !important)

**Comment by bi0hazard6** [comment]
Thanks mate, it worked.
I still have that little horizontal bar. I can zap it, and now it looks perfect.
Do you know how to get rid of the bar?
![image](https://github.com/uBlockOrigin/uAssets/assets/33207067/89b79c92-f92b-41e1-997c-009bcfd6300d)

**Comment by bi0hazard6** [comment]
I was able to get it:

www.lapresse.ca##body > div:nth-of-type(6)

**Comment by gorhill** [comment]
> `www.lapresse.ca##body > div:nth-of-type(6)`

Don't use this filter, this is going to cause breakage issues. Use this instead:

    lapresse.ca##body > div[style]:has(.brz_msg_wall_body)

**Comment by nqlp** [comment]
<img width="1440" height="258" alt="Image" src="https://github.com/user-attachments/assets/6aabe8de-d128-43bf-88e0-cdd61c78ab8f" />

They are back.

**Comment by Yuki2718** [comment]
> They are back.

Can't reproduce, the rules are still working.

**Comment by nqlp** [comment]
Ad leftover at the right side on `https://www.lapresse.ca/actualites/grand-montreal/2025-12-10/transport-collectif-a-montreal/une-quatrieme-greve-aux-impacts-plus-limites.php`:

<img width="1917" height="820" alt="Image" src="https://github.com/user-attachments/assets/6d2f888b-af4b-4b32-b798-113720d2ff64" />

<details>

```yaml
uBlock Origin: 1.68.0
Chromium: 143
filterset (summary):
 network: 184129
 cosmetic: 167794
 scriptlet: 43993
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 90361-264, now
  adguard-cookies: 36297-36297, now
  ublock-cookies-adguard: 5089-72, now
  fanboy-cookiemonster: 44867-3661, now
  ublock-cookies-easylist: 5089-5089, now
  fanboy-thirdparty_social: 69-0, now
  adguard-popup-overlays: 29235-29235, now
  adguard-mobile-app-banners: 6534-6533, now
  adguard-other-annoyances: 15301-15301, now
  easylist-annoyances: 4966-506, now
  easylist-notifications: 2435-463, now
  ublock-annoyances: 4717-154, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 22-0, never
  ublock-filters: 41896-269, now
  ublock-badware: 10576-32, now
  ublock-privacy: 3568-3, now
  ublock-unbreak: 2712-3, now
  ublock-quick-fixes: 401-1, 26m Δ
  easylist: 82920-563, now
  easyprivacy: 54963-780, now
  urlhaus-1: 31085-6, now
  plowe-0: 3479-3, now
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 264 ms (selfie)
 maxAssetCacheWait: 60 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 21
 network:
  lapresse.ca: 1
  braze.com: 14
  doubleclick.net: 1
  google.com: 1
  googletagmanager.com: 1
  optable.co: 1
  rubiconproject.com: 1
  scorecardresearch.com: 1
 extended:
  ##.adsWrapper
  ###newsletters-subscription-box-root
  ##+js(abort-on-property-write, _sp_)
  ##+js(set-constant, noBlocker, true)
```

</details>

**Comment by mapx-** [comment]
> Désolé, cette page est introuvable.

**Comment by gorhill** [comment]
I don't see leftover with default lists + AdGuard Français, and it's self promotion:

<img width="615" height="736" alt="Image" src="https://github.com/user-attachments/assets/826968e3-c859-470c-8606-65d0d4135b96" />

**Comment by Alex-302** [comment]
Added `lapresse.ca##.contentCardWithNewsletterFallback` to AdGuard Popups filter.
