### ISSUE TITLE
Disabling ad blocking only works at first.

### ISSUE THREAD

**Issue by jngit23** [uBlockOrigin/uAssets#19021]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I'm facing a problem when disabling uBlock Origin for Youtube, it worked at first, I disabled it, I reloaded the page and it worked normally, soon after, I went to watch another video, Youtube was already complaining about an ad blocker, so I have to enable and disable again and refresh for every new video I go to watch.

### URL(s) where the issue occurs.

https://www.youtube.com/

### Screenshot(s)

![Captura de Tela (24)](https://github.com/uBlockOrigin/uAssets/assets/107755720/2c76e6de-4dc8-478f-8acb-7178ff679308)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 36d.13h.57m
Chromium: 114
filterset (summary):
 network: 98211
 cosmetic: 43045
 scriptlet: 18285
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68127-11, 2d.16h.50m
  easyprivacy: 33422-63, 3d.20h.23m
  plowe-0: 3740-1074, 2d.16h.50m
  spa-1: 5335-68, 2d.16h.50m
  ublock-badware: 7536-139, 4d.11h.37m
  ublock-filters: 33868-169, 4d.11h.37m
  ublock-privacy: 428-4, 4d.11h.37m
  ublock-quick-fixes: 364-70, 1h.9m
  ublock-unbreak: 2070-32, 4d.11h.37m
  urlhaus-1: 6434-0, 13h.53m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 645 ms
 maxAssetCacheWait: 235 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue at this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

Disable all of your other extensions and test these filters: https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1633335281

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; `Apply changes` > Open new tab and test again.
