### ISSUE TITLE
ladbible.com: ads

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#19022]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ladbible.com/entertainment/film/peter-ostrum-willy-wonka-film-career-913766-20230714`

### Category

ads

### Description

fix all placeholders and use one filter:

```
ladbible.com##[class*="Advert"]
ladbible.com#@#span:has-text(Advert)
ladbible.com#@#[data-cypress="sticky-ads"]
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 30d.10h.4m
Firefox: 115
filterset (summary):
 network: 88833
 cosmetic: 42708
 scriptlet: 21850
 html: 1179
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, never
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1736-0, never
  ublock-annoyances: 5253-7, never
 default:
  user-filters: 1970-15, never
  ublock-filters: 34706-211, never
  ublock-badware: 7559-0, never
  ublock-privacy: 466-0, never
  ublock-unbreak: 2116-0, never
  ublock-quick-fixes: 365-0, never
  easylist: 68104-265, never
  easyprivacy: 33388-1418, never
filterset (user): [array of 940 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 6 redacted]
hostRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 515 ms (selfie)
 maxAssetCacheWait: 146 ms
 unsuspendAfter: 314 ms
popupPanel:
 blocked: 36
 network:
  3lift.com: 1
  adnxs.com: 1
  adsafeprotected.com: 2
  amazon-adsystem.com: 1
  ay.delivery: 1
  bidswitch.net: 1
  casalemedia.com: 1
  chartbeat.com: 1
  clouderrorreporting.googleapis.com: 3
  cootlogix.com: 1
  dotmetrics.net: 1
  doubleclick.net: 2
  doubleverify.com: 5
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  jwpcdn.com: 1
  jwpltx.com: 1
  outbrain.com: 1
  pbxai.com: 1
  permutive.com: 1
  pubmatic.com: 1
  quantserve.com: 1
  rubiconproject.com: 3
  scorecardresearch.com: 1
 extended:
  ##.dfp-ad-unit
  ##[class*="Advert"]
  ##*:style(border-radius:0px !important;)
  #@#span:has-text(Advert)
  #@#div[class*="margin-Advert"]
  #@#[data-cypress="sticky-ads"]
```
</details>

**Comment by stephenhawk8054** [comment]
I only see a placeholder at the top. Does this work?

```adb
ladbible.com##[data-cypress="sticky-header"]
```

**Comment by Daxy7** [comment]
yes perfect. no player detection either
