### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Jokopentil** [uBlockOrigin/uAssets#19023]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.youtube.com/watch?v=Om1ngUAYsuY`

### Category

ads

### Description

Notification

### Other extensions used

![20230715_072216_rmscr](https://github.com/uBlockOrigin/uAssets/assets/114223791/a4a73e04-d234-45f1-bfaa-c495d12c7b3d)
Notification youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 11d.5h.9m
Chromium Mobile: 112
filterset (summary):
 network: 312194
 cosmetic: 237765
 scriptlet: 43077
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9344-4, 22h.5m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 3d.14h.38m
  https://raw.githubusercontent.com/Hakame-kun/uBlock-Filters-Indonesia/master/uBlock Indo/ubindo.txt: 1635-20, 3d.14h.30m
  adguard-cookies: 26293-29, 3d.20h.51m
  adguard-generic: 72473-633, 3d.20h.51m
  adguard-mobile-app-banners: 4409-13, 3d.20h.51m
  adguard-other-annoyances: 13068-54, 3d.20h.51m
  adguard-popup-overlays: 22944-75, 3d.20h.50m
  adguard-social: 20887-880, 3d.20h.50m
  adguard-spyware: 63157-1330, 3d.20h.50m
  adguard-spyware-url: 1117-3, 3d.20h.50m
  adguard-widgets: 2196-7, 3d.20h.50m
  [12 lists not shown]: [too many]
 default:
  IDN-0: 9527-373, 3d.20h.51m
  adguard-mobile: 8383-54, 3d.20h.51m
  easylist: 67969-1264, 3d.20h.50m
  easyprivacy: 33422-17075, 3d.20h.49m
  plowe-0: 3740-1575, 3d.14h.38m
  ublock-badware: 7530-398, 3d.21h.38m
  ublock-filters: 34175-4333, 3d.21h.36m
  ublock-privacy: 428-66, 3d.14h.38m
  ublock-quick-fixes: 367-17, 8h.44m
  ublock-unbreak: 2075-138, 3d.21h.35m
  urlhaus-1: 6231-2, 22h.4m
filterset (user): [array of 7 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 13838 ms
 maxAssetCacheWait: 4367 ms
popupPanel:
 blocked: 26
 network:
  google.co.id: 1
  google.com: 25
 hasUnprocessedRequest: true
 extended:
  ##ytm-promoted-sparkles-web-renderer
  ##.ytp-paid-content-overlay
  ##ytm-companion-slot
  ##ytd-video-masthead-ad-advertiser-info-renderer,ytm-promoted-sp…
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, 0.playerResponse.adPlacements 0.playerResponse…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
```
</details>

**Comment by stephenhawk8054** [comment]
Duplicate: https://github.com/uBlockOrigin/uAssets/issues/7636
