### ISSUE TITLE
Google Tag Manager for WordPress is Blocked

### ISSUE THREAD

**Issue by briankelleher** [uBlockOrigin/uAssets#1902]
### URL(s) where the issue occurs

`https://uconn.edu`

### Describe the issue

The Google Tag Manager for WordPress is currently being blocked.  It has over 100,000+ active installations and is extremely helpful for putting GTM on large multisite instances.  [Plugin Page](https://wordpress.org/plugins/duracelltomi-google-tag-manager/)

### Screenshot(s)

<img width="853" alt="screen shot 2018-04-06 at 1 40 42 pm" src="https://user-images.githubusercontent.com/7377399/38435616-2595e064-39a0-11e8-9d13-57bf0b663c45.png">

### Versions

- Browser/version: All Browsers.  Chrome 65.0.3325.181
- uBlock Origin version: 1.15.18

### Settings

No default settings were changed.

### Notes

The scripts are simply being blocked by uBlock.  These scripts should be deemed safe as they facilitate proper Google Tag Manager tracking for Google Analytics and other analytical purposes.  Very widely used.

**Comment by zaphodbeebblebrox** [comment]
Google tag manager is blocked by the lists Easy Privacy and uBlock Filters - Privacy. Both lists follow the [Easy Privacy Policy(https://easylist.to/pages/policy.html), which means that they will block all third party trackers. This is intended behavior.

**Comment by briankelleher** [comment]
Good to know.  Didn't know uBlock followed 100% as most other adblockers don't (: 

Thank you.
