### ISSUE TITLE
get.datapps.org: ads

### ISSUE THREAD

**Issue by jackbdbe** [uBlockOrigin/uAssets#19027]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://get.datapps.org/list.php?name=2ab9e6dc359d4a5e8e89c1736a2ca348`

### Category

ads

### Description

> 点击链接弹出广告网页

**Clicking on a link brings up an advertisement page**

### Other extensions used

> 没有

**No**

### Screenshot(s)

NSFW (Kiwi browser)
https://github.com/uBlockOrigin/uAssets/assets/119105537/bc4a5967-d259-4800-bcc6-e09e4457ac21

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 33d.14h.55m
Chromium Mobile: 112
filterset (summary):
 network: 112113
 cosmetic: 38711
 scriptlet: 18143
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 18-2, never
  CHN-0: 24476-1312, 3d.23h.13m
  adguard-mobile: 8383-53, 3d.23h.9m
  easylist: 68099-16747, 5h.39m
  easyprivacy: 33417-87, 4d.16h.14m
  plowe-0: 3740-1151, 1d.16h
  ublock-badware: 7551-141, 15h.40m
  ublock-filters: 34113-409, 4h.35m
  ublock-privacy: 428-5, 5d.13h.33m
  ublock-quick-fixes: 367-100, 3h.15m
  ublock-unbreak: 2075-36, 3h.18m
  urlhaus-1: 6494-0, 3h.17m
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1047 ms (selfie)
 maxAssetCacheWait: 109 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 For Adguard Chinese?

```adb
datapps.org##+js(rmnt, script, setpos)
datapps.org##+js(set, setpos, noopFunc)
datapps.org##+js(ra, onclick, a[href][onclick^="setpos"])
datapps.org##+js(nowoif)
```

Any of these can work.

**Comment by Yuki2718** [comment]
Hm, no traffic data: https://www.similarweb.com/search/?q=datapps.org
@Alex-302 Looks to be a file hosting service, I'll fix this but please remove and notify if inappropriate.

> Any of these can work.

On my end `datapps.org##+js(set, setpos, noopFunc)` breaks download, so will go with `datapps.org##+js(ra, onclick, a[href][onclick^="setpos"])`.
