### ISSUE TITLE
coinsl.click: breakage

### ISSUE THREAD

**Issue by yohanes4dip** [uBlockOrigin/uAssets#19026]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://coinsl.click/0mRacqMM`

### Category

nuisance

### Description

recaptcha not show

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/45124799/2cbb9c08-7340-40cd-b293-57e160035350)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 36d.13h.20m
Chromium: 114
filterset (summary):
 network: 263027
 cosmetic: 143644
 scriptlet: 38909
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69060-1736, now
  adguard-generic: 72665-736, now
  adguard-mobile: 8414-75, now
  adguard-social: 20910-2025, now
  adguard-spyware-url: 1125-3, now
  block-lan: 47-0, now
  curben-phishing: 124136-27, now
  curben-pup: 199-0, now
  dpollock-0: 11532-80, now
  fanboy-thirdparty_social: 68-4, now
  ublock-annoyances: 5290-228, now
 default:
  user-filters: 61-1, never
  IDN-0: 9535-3814, now
  easylist: 68263-17795, now
  easyprivacy: 33381-331, now
  plowe-0: 3723-1503, now
  ublock-badware: 7560-397, now
  ublock-filters: 33869-4343, now
  ublock-privacy: 429-7, now
  ublock-quick-fixes: 367-101, now
  ublock-unbreak: 2070-95, now
  urlhaus-1: 6494-2, now
filterset (user): [array of 52 redacted]
trustedset:
 added: [array of 91 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1437 ms (selfie)
 maxAssetCacheWait: 1068 ms
popupPanel:
 blocked: 11
 network:
  inklinkor.com: 1
  jsdelivr.net: 3
  ophoacit.com: 1
  ossmightyenar.net: 1
  phicmune.net: 1
  popcash.net: 2
  saptorge.com: 1
  wpadmngr.com: 1
 extended:
  ##+js(addEventListener-defuser, load)
  ##+js(set-constant, blurred, false)
```
</details>

**Comment by Daxy7** [comment]
does this even do anything other than spam you with ads?
can't press the button without 100 million popups

sfw:
https://github.com/uBlockOrigin/uAssets/assets/91396482/a9d0b734-6e13-4b4e-b138-d64e34a2ee58

**Comment by yohanes4dip** [comment]
any solution?

**Comment by Daxy7** [comment]
...report issue to the website owner. that button doesn't work. no redirect to somewhere or something? hcaptcha is broken i guess you could tell,them

**Comment by Daxy7** [comment]
> any solution?

did they respond back yet
