### ISSUE TITLE
[nsfw] avtub.pro: ads

### ISSUE THREAD

**Issue by DarKnight-00** [uBlockOrigin/uAssets#19039]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://avtub.pro/`

### Category

ads

### Description

On Firefox android

### Other extensions used

DR

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 33d.5h
Firefox Mobile: 115
filterset (summary):
 network: 104866
 cosmetic: 31226
 scriptlet: 17977
 html: 1002
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2231-0, now
  IDN-0: 9549-3813, now
 default:
  user-filters: 16-0, never
  ublock-filters: 35064-347, now
  ublock-badware: 7566-2, now
  ublock-privacy: 468-3, now
  ublock-unbreak: 2121-1, now
  ublock-quick-fixes: 371-1, now
  adguard-mobile: 8418-124, now
  easylist: 68236-17393, now
  easyprivacy: 33383-728, now
  urlhaus-1: 6490-0, now
  plowe-0: 3723-1, now
filterset (user): [array of 16 redacted]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1592 ms (selfie)
 maxAssetCacheWait: 265 ms
popupPanel:
 blocked: 15
 network:
  histats.com: 3
  imgavtub.com: 8
  jads.co: 2
  juicyads.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > Untick `Ignore generic cosmetic filters`
