### ISSUE TITLE
wmbusmeters.org: breakage

### ISSUE THREAD

**Issue by jonas240** [uBlockOrigin/uAssets#19035]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wmbusmeters.org/`

### Category

breakage

### Description

The 'Analyze' Button uses a JavaScript, that is needed, but gets blocked by uBlockOrigin. Disabling uBlockOrigin worked to solve the issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 31d.23h.6m
Firefox: 115
filterset (summary):
 network: 99307
 cosmetic: 44084
 scriptlet: 17919
 html: 1001
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34769-205, now
  ublock-badware: 7572-1, now
  ublock-privacy: 468-0, now
  ublock-unbreak: 2116-0, now
  ublock-quick-fixes: 371-0, now
  easylist: 68235-665, now
  easyprivacy: 33383-727, now
  urlhaus-1: 6490-0, now
  plowe-0: 3723-2, now
  DEU-0: 6941-3, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 461 ms (selfie)
 maxAssetCacheWait: 91 ms
popupPanel:
 blocked: 2
 network:
  wmbusmeters.org: 2
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
