### ISSUE TITLE
duplichecker.com: breakage

### ISSUE THREAD

**Issue by 2014MU69** [uBlockOrigin/uAssets#19042]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.duplichecker.com/domain-age-checker.php`

### Category

breakage

### Description

I can't use domain age checker without at least disabling "uBlock filters – Ads"

I am using Lemur browser on Android if that means anything.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

"uBlock filters – Ads" enabled

![Screenshot_2023-07-16-15-29-09-17](https://github.com/uBlockOrigin/uAssets/assets/102027221/3216a754-7e58-4d70-b77e-0e2c73251e60)

"uBlock filters – Ads" disabled

![Screenshot_2023-07-16-15-29-44-03](https://github.com/uBlockOrigin/uAssets/assets/102027221/fd088ef8-7b81-4e0d-ad98-82b788b70967)

</details>
 

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.11h.36m
Chromium Mobile: 110
filterset (summary):
 network: 110988
 cosmetic: 138419
 scriptlet: 23188
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt: 181-0, 15m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, 15m
  IND-0: 12665-0, 16m
  adguard-cookies: 26345-1580, 16m
  adguard-mobile-app-banners: 4421-16, 15m
  adguard-other-annoyances: 13097-15, 15m
  adguard-popup-overlays: 22999-93, 15m
  adguard-social: 20913-2021, 15m
  adguard-widgets: 2207-38, 15m
  fanboy-cookiemonster: 47738-19689, 15m
 default:
  user-filters: 0-0, never
  adguard-mobile: 8418-36, 15m
  easylist: 68161-16697, 15m
  easyprivacy: 33381-137, 15m
  plowe-0: 3723-1143, 15m
  ublock-badware: 7565-142, 1m
  ublock-filters: 34179-791, 2m
  ublock-privacy: 429-7, 1m
  ublock-quick-fixes: 384-111, 1m
  ublock-unbreak: 2075-37, 1m
  urlhaus-1: 6417-0, 15m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3897 ms (selfie)
 maxAssetCacheWait: 750 ms
popupPanel:
 blocked: 12
 network:
  adpushup.com: 1
  adrecover.com: 2
  google-analytics.com: 1
  google.com: 5
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ###cookie_directive_container
  ##.data_inbox > div[class]:has(> script[src^="https://pagead2.go…
  ##.container div > div[style]:has(.ads-pricing)
  ##[href*="grammarly.com"]
  ##div > span[id^="side_bar"] > .adsbygoogle:upward(div)
  ##div:not([id]) > div[class] > ._ap_apex_ad:upward(2)
  ##.adsbygoogle:upward([style]):upward([style])
  ##ins.adsbygoogle:style(max-height: 1.25px !important;)
  ##*:style(animation: none !important;)
  ##+js(no-fetch-if, /google|\/ad.+\.js/)
  ##+js(no-xhr-if, ads)
  ##+js(no-fetch-if, /googlesyndication|adpushup|adrecover/)
  ##+js(no-requestAnimationFrame-if, _0x)
  ##+js(no-setInterval-if, ads)
  ##+js(no-setTimeout-if, showPopup)
```
</details>

**Comment by JobcenterTycoon** [comment]
Reproduced on mobile. Fixed now https://github.com/uBlockOrigin/uAssets/commit/0a458b24bdd5414641f482babf7eaf0ce8ef3b55 to get the fix directly force update the filterlists.
