### ISSUE TITLE
blackhatworld.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#19046]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.blackhatworld.com/seo/people-are-10-years-behind-with-their-seo-knowledge.1513368/?utm_source=sendgrid&utm_medium=16-jul-2023&utm_campaign=1513368`

### Category

ads

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/ec0f5587-bb37-4f15-8ebd-65fda7d087da)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 29d.9h.32m
Chromium: 114
filterset (summary):
 network: 128861
 cosmetic: 142122
 scriptlet: 26309
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 9637-3, 8h.31m
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 524-4, 3d.12h.41m
  DEU-0: 6941-0, 8h.33m
  IDN-0: 9535-359, 3d.12h.41m
  RUS-0: 39592-50, 1d.9h.20m
  ara-0: 2321-6, 8h.32m
  easylist-annoyances: 3893-47, 3d.12h.41m
  easylist-chat: 129-0, 3d.12h.41m
  easylist-notifications: 2631-102, 3d.12h.41m
  fanboy-cookiemonster: 47714-230, 3d.12h.41m
  fanboy-social: 16100-10, 3d.12h.41m
  ublock-annoyances: 5296-85, 3d.12h.41m
 default:
  user-filters: 6-0, never
  easylist: 68266-61, 3d.12h.41m
  easyprivacy: 33438-244, 3d.12h.41m
  plowe-0: 3740-1080, 3d.12h.41m
  ublock-badware: 7552-142, 3d.12h.41m
  ublock-filters: 33790-366, 3d.12h.41m
  ublock-privacy: 425-7, 3d.12h.41m
  ublock-quick-fixes: 379-105, 9h.34m
  ublock-unbreak: 2070-38, 3d.12h.41m
  urlhaus-1: 6417-0, 8h.30m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1697 ms (selfie)
 maxAssetCacheWait: 436 ms
popupPanel:
 blocked: 4
 network:
  advertserve.com: 1
  cloudflareinsights.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##img[width="728"][height="90"]
  ##.js-notice.notice--cookie
  ##.u-scrollButtons
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
blackhatworld.com##.bhw-banners
```

Please report here: https://github.com/easylist/easylist/issues
