### ISSUE TITLE
youdebrid.com: detection

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#19043]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://youdebrid.com/`

### Category

detection

### Description

When click on "GET PREMIUM LINK" , Adblocker Detected is appeared. This warning appears on the following pages as well.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 36d.12h.46m
Chromium: 114
filterset (summary):
 network: 161186
 cosmetic: 177109
 scriptlet: 28101
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, never
  https://easylist.to/easylist/fanboy-annoyance.txt: 60536-110, never
  https://fanboy.co.nz/fanboy-turkish.txt: 725-0, never
  https://filters.adavoid.org/ultimate-privacy-filter.txt: 62378-176, never
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69069-5281, never
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7256-0, never
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 181-0, never
  https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt: 412-8, never
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92081-76337, never
  fanboy-cookiemonster: 47738-47737, never
  fanboy-social: 16105-16105, never
  fanboy-thirdparty_social: 68-15, never
  [2 lists not shown]: [too many]
 default:
  user-filters: 504-3, never
  TUR-0: 13626-106, never
  easylist: 68161-170, never
  easyprivacy: 33381-17013, never
  plowe-0: 3723-1161, never
  ublock-badware: 7571-145, never
  ublock-filters: 33884-604, never
  ublock-privacy: 429-62, never
  ublock-unbreak: 2070-56, never
  urlhaus-1: 6417-0, never
filterset (user): [array of 504 redacted]
trustedset:
 added: [array of 21 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 6 redacted]
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 652 ms (selfie)
 maxAssetCacheWait: 215 ms
popupPanel:
 blocked: 4
 network:
  youdebrid.com: 1
  googleadservices.com: 1
  googlesyndication.com: 1
  yandex.ru: 1
 extended:
  ##.responsive-ad-wrapper
  ##ins.adsbygoogle
```
</details>

**Comment by punisher018** [comment]
Pressing "GET PREMIUM LINK" button now switches to the new page, but when the loading screen is finished on the opened page (%0 to %100) , it gives an error. When Ubo is turned off, it does not give an error.

**Comment by JobcenterTycoon** [comment]
Works fine for me. Maybe its caused by one of the custom/imported filterlists which you have enabled. Disable those lists and test again. If it works, enable one filterlist and test again until you have the filterlist which causing the issue. After you found the list which causing the issue contact the filterlist author.

**Comment by punisher018** [comment]
I don't know why but with Ubo default with no other filter with no other extension tried on edge firefox chrome but still give me same error after %100. The interesting thing is that even if I allow everything blocked that appears in the logger, it still gives this error. With disabled Ubo no problem with downloading from here. 
https://www.hizliresim.com/cba81wx

**Comment by JobcenterTycoon** [comment]
Ok im able to reproduce with the link from the screenshot `https://turbobit.net/jklzno5u4ptu.html`. Updated now https://github.com/uBlockOrigin/uAssets/commit/5d12955909acb0a463c54a3f5e2b9a0c310852c3

**Comment by punisher018** [comment]
It's ok now thanks.
