### ISSUE TITLE
oko.sh: detection

### ISSUE THREAD

**Issue by ragg102** [uBlockOrigin/uAssets#19050]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://oko.sh/tvV97IJH5c`

### Category

detection

### Description

detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 25d.8h.35m
Firefox: 115
filterset (summary):
 network: 99328
 cosmetic: 45371
 scriptlet: 18220
 html: 998
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34640-91, 4d.11h.49m
  ublock-badware: 7543-0, 4d.11h.48m
  ublock-privacy: 464-0, 4d.5h.11m
  ublock-unbreak: 2114-0, 4d.11h.47m
  ublock-quick-fixes: 403-0, 8h.20m
  easylist: 68104-778, 3d.6m
  easyprivacy: 33381-783, 23h.35m
  urlhaus-1: 6441-0, 4h.8m
  plowe-0: 3739-2, 12d.3h.33m
  spa-0: 3719-1, 4h.9m
  spa-1: 5340-161, 1d.4h.28m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 246 ms (selfie)
 maxAssetCacheWait: 80 ms
popupPanel:
 blocked: 7
 network:
  oko.sh: 1
  boabijihum.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  inklinkor.com: 1
  ophoacit.com: 2
 extended:
  ##+js(remove-node-text, script, document.createElement)
  ##+js(abort-on-property-read, AaDetector)
  ##+js(abort-on-property-read, open)
  ##+js(set-constant, blurred, false)
  ##+js(no-setTimeout-if, Adblock)
  ##+js(no-fetch-if, /googlesyndication|inklinkor|ads\/load/)
  ##+js(abort-current-script, XMLHttpRequest, adb)
  ##+js(abort-current-script, Math, zfgloaded)
```
</details>

**Comment by okiehsch** [comment]
I don't see any detection.
Works fine with Firefox on my end, but the captch is broken with Chrome.

`oko.sh#@#+js(rmnt, script, document.createElement)`
fixes the breakage on my end.

@Yuki2718 is that filter still necessary on my end?
It works without it for me.

**Comment by Yuki2718** [comment]
I initially thought the same: https://github.com/uBlockOrigin/uAssets/commit/fd244855d64e6ae61ceda49c3ad27160f8f00cf6
But no, it's reloading the site somehow fixes this. The scriptlet rule is no more necessary as I added a redirect rule in https://github.com/uBlockOrigin/uAssets/commit/902e478f9a64a3c741f3aea5c07e40cd1f41c1e2 but best to have in case redirect doesn't work (e.g. Firefox ETP). The real fix will be `@@||googletagmanager.com/gtag/js$domain=oko.sh` which I can add to EP if it works on your side too.

**Comment by okiehsch** [comment]
> The real fix

Works for me too.

**Comment by Yuki2718** [comment]
@ragg102 Force-update filter lists (Filter lists > Purge cache => Update now)

**Comment by ghajini** [comment]
i don't think exception filter is all that necessary....
`click here to continue` & in next page captcha appears

**Comment by Yuki2718** [comment]
> i don't think exception filter is all that necessary.... `click here to continue` & in next page captcha appears

No, at the first load I get captcha broken if without the exception. It works normally after first visit.

**Comment by ghajini** [comment]
anyway i get captcha in next page without exception filter above
