### ISSUE TITLE
deepl.com: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#19053]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.deepl.com/translator`

### Category

privacy

### Description

The domain `s.deepl.com` is used to log visitor's information. At the very least, the site logs user's language, viewport size, and visit count. I'm not sure if there is any other similar domain being connected when accessing the site.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![deepl](https://github.com/uBlockOrigin/uAssets/assets/115052854/c3728881-54f5-40a2-80e0-a7d48424535a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b17
Firefox: 115
filterset (summary):
 network: 96819
 cosmetic: 39508
 scriptlet: 17947
 html: 1002
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 34786-41, 3m
  ublock-badware: 7574-1, 3m
  ublock-privacy: 468-0, 3m
  ublock-unbreak: 2123-1, 3m
  ublock-quick-fixes: 403-53, 3m
  easylist: 68140-334, 3m
  easyprivacy: 33342-86, 3m
  urlhaus-1: 6452-0, 3m
  plowe-0: 3723-1069, 3m
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 551 ms
 maxAssetCacheWait: 324 ms
popupPanel:
 blocked: 0
 extended:
  ##.ad-separator
```
</details>

**Comment by stephenhawk8054** [comment]
There was breakage in the past when blocking that domain: https://github.com/AdguardTeam/AdguardFilters/issues/129341

**Comment by partingscientist** [comment]
Well that's unfortunate. I would assume we are not able to block request based on payload, no?

**Comment by stephenhawk8054** [comment]
Hmm... Actually I cannot reproduce that issue any more, but I'm not using mac os.

@Yuki2718 Can you reproduce any old breakages when blocking that domain?

**Comment by Yuki2718** [comment]
I don't see the breakage anymore, will add to EP.
