### ISSUE TITLE
asiasentinel.com: nuisance

### ISSUE THREAD

**Issue by pubct** [uBlockOrigin/uAssets#19056]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Scroll down a little, a pop-up asking to subscribe via email appears.

### URL(s) where the issue occurs.

`https://www.asiasentinel.com/p/singapore-transport-ministers-arrest-f1-renewal`

### uBO version

1.50.0

### Browser name and version

Chrome 114.0.5735.199

### Settings

\-

**Comment by stephenhawk8054** [comment]
You can subscribe to `EasyList – Newsletter Notices` list: click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > Scroll down to `Annoyances` section > `EasyList – Annoyances` > `EasyList – Newsletter Notices`

---

Or you can add this filter:

```adb
asiasentinel.com##+js(remove-class, show-intro-popup, .show-intro-popup, stay)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; `Apply changes` > Go back to the website > Press `Ctrl + Shift + R` (or `Cmd + Shift + R` on Mac) to reload the page and test again.

**Comment by pubct** [comment]
Subscribe to the list works. Guess I'll close this then.
