### ISSUE TITLE
irs.gov google analytics

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1906]
### URL(s) where the issue occurs

`https://sa.www4.irs.gov/icce-core/load/gettrans/pages/availableTranscripts.xhtml#`
Need to be logged in

### Describe the issue

Blocking Google Analytics prevents opening pdf docs.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/38459085-5e91b18a-3a73-11e8-89b1-9ecb9c6203a2.png)
`https://sa.www4.irs.gov/icce-core/javax.faces.resource/js/google-analytics.js.xhtml?ln=core`

Edit: confirmed

**Comment by terrorist96** [comment]
Hold on...

**Comment by mapx-** [comment]
You can simply whitelist that script, but could you test this filter:

`*/google-analytics.js$script,redirect=noopjs,domain=irs.gov`

**Comment by terrorist96** [comment]
It doesn't work.

![image](https://user-images.githubusercontent.com/12802056/38460621-78b18cc6-3a8b-11e8-97e8-8299c76dc4c2.png)

**Comment by zaphodbeebblebrox** [comment]
Do either of these work?
```
*/google-analytics.js$script,redirect=google-analytics.com/ga.js,domain=irs.gov
*/google-analytics.js$scriptredirect=google-analytics.com/analytics.js,domain=irs.gov
```

**Comment by terrorist96** [comment]
> `*/google-analytics.js$script,redirect=google-analytics.com/ga.js,domain=irs.gov`

That one works. The other doesn't.

**Comment by gorhill** [comment]
I still would like to understand why the issue arise: the 1st-party script at `google-analytics.js.xhtml?ln=core` creates a new script which `src` is `https://ssl.google-analytics.com/ga.js`. How comes this one is not caught/redirected to the neutered scriptlet by uBO?

**Comment by terrorist96** [comment]
I don't know. Are there any steps I can perform to help?

**Comment by gorhill** [comment]
Never mind, I'm being silly. Of course the 1st-party script being blocked the secondary script from `google-analytics.com` was not being created.

I think the real fix should be what was done here:
https://github.com/uBlockOrigin/uAssets/blob/bb8152d42de0ff5ba01ca0445e66c4cc548a60b9/filters/unbreak.txt#L511

**Comment by okiehsch** [comment]
@terrorist96 does
````
*/google-analytics.js$script,redirect=google-analytics.com/ga.js,domain=irs.gov,badfilter
/google-analytics.$badfilter
/google-analytics.$third-party
````
work for you?

**Comment by terrorist96** [comment]
Yes. However, keeping just the first line (which looks like is supposed to disable the recently merged rule) and not including the second and third lines, will still work, as if the first line isn't successfully disabling the recently merged rule.

**Comment by okiehsch** [comment]
Yes, you are right, sorry my mistake, ok if you disable uBO-unbreak and add
````
/google-analytics.$badfilter
/google-analytics.$third-party
````
does it work?

**Comment by terrorist96** [comment]
Yes.
