### ISSUE TITLE
filmstarts.de: breakage

### ISSUE THREAD

**Issue by hagezi** [uBlockOrigin/uAssets#19067]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.filmstarts.de`

### Category

breakage

### Description

Videos can only be played once; if you then select a second video to play, the video remains black.

Steps to reproduce the behaviour:

- Open filmstarts.de
- Click on Trailer in the menu above
- Select any trailer, the trailer will be played
- Click on Trailer again in the menu at the top
- Select any trailer, video remains black, will not play

Deleting all cookies and website data fixes the problem for a one-time trailer playback.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 1h.11m
Chromium: 114
filterset (summary):
 network: 99076
 cosmetic: 44007
 scriptlet: 17985
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 6942-0, 1h.11m
  easylist: 68037-15, 1h.11m
  easyprivacy: 33381-72, 1h.11m
  plowe-0: 3723-1070, 1h.11m
  ublock-badware: 7574-142, 1h.11m
  ublock-filters: 33886-161, 1h.11m
  ublock-privacy: 429-4, 1h.11m
  ublock-quick-fixes: 402-108, 1h.11m
  ublock-unbreak: 2078-36, 1h.11m
  urlhaus-1: 6375-0, 1h.11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1150 ms
 maxAssetCacheWait: 17 ms
popupPanel:
 blocked: 14
 network:
  filmstarts.de: 1
  2mdn.net: 1
  dailymotion.com: 1
  dm-event.net: 6
  getjad.io: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  outbrain.com: 1
 extended:
  ###ads-outer
  ##.ads-outer
  ###dfp-interstitial
  ##.ad-interstitial
  ##.ad-item
  ###dfp-masthead
  ##.ad-masthead
  ###dfp-atf
  ##.ad-atf
  ##.ad-footer
  ##.ad-skyscraper
  ###dfp-btf
  ##.main-banner
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by okiehsch** [comment]
Scratch that, I can reproduce but not consistently and not always after the second video.

**Comment by gorhill** [comment]
The video plays fine once I disable Peter Lowe's and EasyPrivacy. I am trying to figure which filter(s) from these lists is the culprit.

**Comment by stephenhawk8054** [comment]
These look work for me, but I'm not even sure as the symptom doesn't look like consistent for me as well

```adb
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=www.filmstarts.de
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=www.filmstarts.de
@@||securepubads.g.doubleclick.net/gampad/ads$xhr,domain=www.filmstarts.de
@@||cdn.lib.getjad.io/library/*$script,domain=www.filmstarts.de
@@||cdn.lib.getjad.io/prebid/*$script,domain=www.filmstarts.de
```

**Comment by okiehsch** [comment]
````
@@||amazon-adsystem.com/*/apstag.js$script,domain=filmstarts.de
@@||cdn.lib.getjad.io/library/*Filmstarts$script,domain=filmstarts.de
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=filmstarts.de
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*$script,domain=filmstarts.de
@@||securepubads.g.doubleclick.net/gampad/ads$xhr,domain=filmstarts.de
````
Works for me, intersting, I need  to allow the amazon request for it to work on my end.

@hagezi 
Can you test the proposed filters on your end?

**Comment by gorhill** [comment]
@stephenhawk8054 Your filters work but after a long delay.

@okiehsch Your filters work without delay.

**Comment by okiehsch** [comment]
Hm, I tried that, removing the redirection instead of an exception, with my filters and it didn't work, I will test again.

**Comment by stephenhawk8054** [comment]
@gorhill Do you need this filter?

```adb
@@||cdn.lib.getjad.io/prebid/$script,domain=filmstarts.de
```

@okiehsch version seems like doesn't need it.

**Comment by gorhill** [comment]
This work without excepting amazon on my side:

```
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=filmstarts.de
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=filmstarts.de
@@||securepubads.g.doubleclick.net/gampad/ads$xhr,domain=filmstarts.de
@@||cdn.lib.getjad.io/library/*$script,domain=filmstarts.de
@@||cdn.lib.getjad.io/prebid/*$script,domain=filmstarts.de
@@||amazon-adsystem.com/*/apstag.js$script,redirect-rule
```

**Comment by okiehsch** [comment]
````
@@||cdn.lib.getjad.io/library/*Filmstarts$script,domain=filmstarts.de
@@||cdn.lib.getjad.io/prebid/*$script,domain=filmstarts.de
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=filmstarts.de
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*$script,domain=filmstarts.de
@@||securepubads.g.doubleclick.net/gampad/ads$xhr,domain=filmstarts.de
@@||amazon-adsystem.com/*/apstag.js$script,redirect-rule=amazon_apstag.js:5,domain=fillmstarts.de
````
works fine on my end.

**Comment by stephenhawk8054** [comment]
Ah yep, confirm as @okiehsch said. Any of these versions work for me:

```adb
@@||cdn.lib.getjad.io/prebid/*$script,domain=filmstarts.de
@@||amazon-adsystem.com/*/apstag.js$script,redirect-rule
```

or

```adb
@@||amazon-adsystem.com/*/apstag.js$script,domain=filmstarts.de
```

**Comment by gorhill** [comment]
Should we add `filmstarts.de##.main-banner` to avoid the annoying layout shift?

**Comment by okiehsch** [comment]
> the annoying layout shift?

I don't see any layout shift on my end?

**Comment by stephenhawk8054** [comment]
I don't see any layout shift either but `##.main-banner` does look like containing only ad elements.

**Comment by okiehsch** [comment]
Ok, @hagezi if you update the `uBO-unbreak` list you can remove the filters from your personal list and the videos should play fine.

**Comment by stephenhawk8054** [comment]
I think this issue is obsolete now? I can't reproduce the breakage any more.
