### ISSUE TITLE
emailnator.com: detection

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#19069]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.emailnator.com/`

### Category

detection

### Description

Detecting adblock. Sometimes it's a hit and miss, it might take a while to detect or nothing at all

If no detection, try to generate new email and click "Go"

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/127546925/cc9540b5-7f7e-4d6e-8e05-4df6b4d42fa5)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 33d.20h.6m
Chromium: 114
filterset (summary):
 network: 98190
 cosmetic: 41454
 scriptlet: 18012
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  NOR-0: 3467-1, 26m
  easylist: 68110-10, 26m
  easyprivacy: 33345-63, 26m
  plowe-0: 3723-1070, 26m
  ublock-badware: 7574-142, 26m
  ublock-filters: 33886-150, 26m
  ublock-privacy: 429-4, 26m
  ublock-quick-fixes: 400-108, 26m
  ublock-unbreak: 2078-34, 26m
  urlhaus-1: 6375-0, 26m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 160 ms (selfie)
 maxAssetCacheWait: 92 ms
popupPanel:
 blocked: 5
 network:
  buysellads.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  jsdelivr.net: 1
  paypalobjects.com: 1
```
</details>

**Comment by ghajini** [comment]
this will work
`emailnator.com##+js(nostif, adsbygoogle)`

**Comment by gorhill** [comment]
I could reproduce and @ghajini's filter works on my side.

**Comment by JobcenterTycoon** [comment]
Your filter hiding the whole inbox. Fixed with a other filter https://github.com/uBlockOrigin/uAssets/commit/7d5aefe45fb3beb4cd074b7cc30ae2741ed32f64
