### ISSUE TITLE
maxstream.video: detection

### ISSUE THREAD

**Issue by Salteng** [uBlockOrigin/uAssets#19072]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://maxstream.video/videostream/wzyotp8wuuzg/i8n14xr71jkt/d0syUjdPbmdhU3hDYTE3NXgwQ25pZz09`

### Category

detection

### Description

Site detects ublock and sends a window

### Other extensions used

video speed controller, enhancer for youtube, return YT dislike,, sponsorblock, duck duckgo privacy essentials

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 34d.2h.20m
Firefox: 115
filterset (summary):
 network: 100730
 cosmetic: 46672
 scriptlet: 17938
 html: 1001
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 34768-98, 2d.2h.3m
  ublock-badware: 7573-1, 2d.2h.2m
  ublock-privacy: 468-0, 2d.10h.3m
  ublock-unbreak: 2116-0, 2d.2h.1m
  ublock-quick-fixes: 403-0, 9h.50m
  easylist: 68099-776, 5d.4h.2m
  easyprivacy: 33438-718, 5d.4h.1m
  urlhaus-1: 6375-0, 7h.48m
  plowe-0: 3723-2, 4d.3h.39m
  ITA-0: 11128-4, 7h.49m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1126 ms (selfie)
 maxAssetCacheWait: 450 ms
popupPanel:
 blocked: 7
 network:
  dogcollarfavourbluff.com: 4
  googletagmanager.com: 1
  host-cdn.net: 1
  intellipopup.com: 1
 extended:
  ##+js(nano-setTimeout-booster, .fadeIn(), 3000)
  ##+js(window.open-defuser)
  ##+js(remove-attr, style, div[style="display: none;"])
```
</details>

**Comment by okiehsch** [comment]
> Site detects ublock and sends a window

The adblock warning is shown to everyone, does not matter if one uses an adblocker or not.
