### ISSUE TITLE
7plus.com.au: ads

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#19076]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There was an ad before the main video started. Please look mat screenshot below:
![Ads](https://github.com/uBlockOrigin/uAssets/assets/20948631/129e98a1-d8a5-4001-af7f-8f9cd6d064e4)

### URL(s) where the issue occurs.

`https://7plus.com.au/seven-news-sydney?episode-id=7NNS23-193&autoplay=true`

### uBO version

uBlock Origin 1.50.0

### Browser name and version

Chromium: 114

### Settings

```yaml
uBlock Origin 1.50.0:
 since: 7d.20h.19m
Chromium: 114
filterset (summary):
 network: 309430
 cosmetic: 218951
 scriptlet: 41217
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69069-104, 2d.20h.32m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 56607-0, 7h.51m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92081-21114, 2d.20h.32m
  adguard-cookies: 26345-26345, 2d.20h.32m
  adguard-generic: 72727-519, 2d.20h.32m
  adguard-mobile-app-banners: 4421-4421, 2d.20h.32m
  adguard-other-annoyances: 13097-13097, 2d.20h.32m
  adguard-popup-overlays: 22999-22999, 2d.20h.32m
  adguard-social: 20913-1547, 2d.20h.32m
  adguard-widgets: 2207-2207, 2d.20h.32m
  block-lan: 48-0, 2d.20h.32m
  curben-phishing: 123226-46, 7h.51m
  [10 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  easylist: 68131-1220, 2d.20h.32m
  easyprivacy: 33381-464, 2d.20h.32m
  plowe-0: 3723-1451, 2d.20h.32m
  ublock-badware: 7571-398, 2d.20h.32m
  ublock-filters: 33884-4167, 2d.20h.32m
  ublock-privacy: 429-6, 2d.20h.32m
  ublock-quick-fixes: 402-110, 7h.51m
  ublock-unbreak: 2072-93, 2d.20h.31m
filterset (user): [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5761 ms (selfie)
 maxAssetCacheWait: 485 ms
```

**Comment by TesterMan247** [comment]
Its free to set up an account.
Also, ads are shown in between the man video as well....

**Comment by stephenhawk8054** [comment]
I can't see any ads.

However, can you test these filters?

```adb
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,from=7plus.com.au,badfilter
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect-rule=google-ima.js,domain=7plus.com.au
```

**Comment by gorhill** [comment]
I have an account but videos are not playing on my side, they time out -- with or without uBO (using `.au` VPN of course).

**Comment by OilVsButter** [comment]
Could you send a us a screenshot of the blocked elements from uBlock Origin's [logger](https://github.com/gorhill/ublock/wiki/The-logger)?
![image](https://github.com/uBlockOrigin/uAssets/assets/139990339/ed805e48-e1a9-4881-80fb-cc5d1479f30f)

**Comment by TesterMan247** [comment]
Here you go....
![blocked](https://github.com/uBlockOrigin/uAssets/assets/20948631/cd490e73-5ac6-459b-8e5c-3e4f570e5676)

**Comment by stephenhawk8054** [comment]
@TesterMan247 Can you test this? https://github.com/uBlockOrigin/uAssets/issues/19076#issuecomment-1641526730

**Comment by stvev1337** [comment]
> I can't see any ads.
> 
> However, can you test these filters?
> 
> ```
> @@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,from=7plus.com.au,badfilter
> ||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect-rule=google-ima.js,domain=7plus.com.au
> ```

Had a friend of mine test this out (I do not have an account). He said it works.

**Comment by TesterMan247** [comment]
> > I can't see any ads.
> > However, can you test these filters?
> > ```
> > @@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,from=7plus.com.au,badfilter
> > ||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect-rule=google-ima.js,domain=7plus.com.au
> > ```
> 
> Had a friend of mine test this out (I do not have an account). He said it works.

It seems to work. Thanks a lot.
Can I remove these from my filters because you've added it to the default lists?

**Comment by stephenhawk8054** [comment]
@TesterMan247 You can remove your custom filters now, then force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.
