### ISSUE TITLE
[nsfw] comoquitarr.club: detection

### ISSUE THREAD

**Issue by ragg102** [uBlockOrigin/uAssets#19074]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://comoquitarr.club/6-mejores-purificadores-de-aire-y-como-elegir/`

### Category

detection

### Description

detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 27d.6h.25m
Firefox: 115
filterset (summary):
 network: 99421
 cosmetic: 45287
 scriptlet: 18272
 html: 1002
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34769-41, now
  ublock-badware: 7561-2, now
  ublock-privacy: 468-0, now
  ublock-unbreak: 2133-3, now
  ublock-quick-fixes: 402-44, now
  easylist: 68124-782, now
  easyprivacy: 33345-774, now
  urlhaus-1: 6395-0, now
  plowe-0: 3723-1, now
  spa-0: 3700-6, now
  spa-1: 5356-187, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 271 ms (selfie)
 maxAssetCacheWait: 108 ms
popupPanel:
 blocked: 16
 network:
  doubleclick.net: 2
  google.com: 9
  googlesyndication.com: 2
  googletagmanager.com: 1
  youtube.com: 2
 extended:
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(json-prune, playerResponse.adPlacements playerResponse.pl…
  #@#+js(json-prune, [].playerResponse.adPlacements [].playerRespo…
```
</details>

**Comment by gorhill** [comment]
I can't reproduce when using uBO default settings/lists, and no other extensions.

> - [x] I did not answer truthfully to ALL the above checkpoints.

Please go through all the steps again and answer truthfully this time.

> - [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.

 The only way I can reproduce detection is by enabling Adblock Plus along uBO.

**Comment by gorhill** [comment]
Given your [history of opening invalid issues](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+author%3Aragg102+is%3Aclosed), I will assume that it's yet another invalid issue.
