### ISSUE TITLE
sport.cz detection

### ISSUE THREAD

**Issue by Yota8888** [uBlockOrigin/uAssets#19073]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

filter not working at all

### URL(s) where the issue occurs.

sport.cz

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/118998546/38ce764d-1ae0-4a34-b152-457e1281867c)

### uBO version

1.50

### Browser name and version

FF 115.0.2

### Settings

none

**Comment by stephenhawk8054** [comment]
Can you enable `EasyList Czech and Slovak` list and test again? (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > Scroll to `Regions, languages` section)

**Comment by gorhill** [comment]
We need more information than what you provide.

Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information", paste content here.

Next time use the _chat_ icon to report filter issues on specific sites.

**Comment by Yota8888** [comment]
enabled and updated the czech and slovak list, still was getting ads on top of the page. Used the picker tool and now it seems to be working fine 
![image](https://github.com/uBlockOrigin/uAssets/assets/118998546/90df9292-ef39-49da-bb75-b2a08dc28ca4)
![image](https://github.com/uBlockOrigin/uAssets/assets/118998546/470af9c8-e562-48c0-bbc5-2404d30e9191)
