### ISSUE TITLE
mealcold.com: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#19079]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mealcold.com/`

### Category

detection

### Description

Detects adblocker

### Other extensions used

Violentmonkey
Libredirect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 35d.16h.6m
Firefox Mobile: 115
filterset (summary):
 network: 98188
 cosmetic: 29813
 scriptlet: 17990
 html: 1002
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35064-330, 2d.17h.34m
  ublock-badware: 7567-1, 2d.17h.33m
  ublock-privacy: 468-1, 4d.2h.3m
  ublock-unbreak: 2128-3, 2d.17h.32m
  ublock-quick-fixes: 403-1, 3h.39m
  adguard-mobile: 8427-121, 1d.21h.26m
  easylist: 67986-17278, 1d.16h.15m
  easyprivacy: 33436-734, 5d.16h.25m
  urlhaus-1: 6395-0, 14h.42m
  plowe-0: 3741-2, 5d.2h.53m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14386 ms (selfie)
 maxAssetCacheWait: 883 ms
popupPanel:
 blocked: 21
 network:
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 15
  googlesyndication.com: 1
  googletagmanager.com: 1
  holid.io: 3
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by okiehsch** [comment]
Pretty sure you used a shortener link to arrive at that site.
We need that link to be able to reproduce.

**Comment by BlazeFTL** [comment]
Similar Site `https://fartechy.com/?go=8717eddb`
Add Domain To https://github.com/uBlockOrigin/uAssets/blob/f0aa70db389a9f97955c2e8ab2512435f3c22287/filters/filters-2022.txt#L2095
```
fartechy.com###wpsafe-link:style(display: block !important;)
fartechy.com###wpsafe-link:others()
