### ISSUE TITLE
komikdewasa.lat: breakage

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uAssets#19075]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The site display is broken

### URL(s) where the issue occurs.

https://komikdewasa.lat/

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 42m
Firefox Mobile: 115
filterset (summary):
 network: 107418
 cosmetic: 134165
 scriptlet: 25466
 html: 1183
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 9811-4, 3m
  adguard-spyware-url: 1132-6, 41m
  adguard-social: 20936-164, 41m
  adguard-cookies: 26391-46, 41m
  adguard-popup-overlays: 23027-988, 41m
  adguard-mobile-app-banners: 4429-12, 41m
  adguard-other-annoyances: 13119-102, 41m
  adguard-widgets: 2211-1, 41m
  ublock-annoyances: 5311-18, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 35067-712, 42m
  ublock-badware: 7570-1, 42m
  ublock-privacy: 468-0, 42m
  ublock-unbreak: 2128-0, 41m
  ublock-quick-fixes: 404-2, 41m
  adguard-mobile: 8431-104, 42m
  easylist: 68124-683, 6m
  easyprivacy: 33345-772, 41m
  urlhaus-1: 6375-0, 41m
  plowe-0: 3723-2, 41m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1506 ms
 maxAssetCacheWait: 793 ms
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/c6144046ce39b07828c1af737fb1923a21f32d42
