### ISSUE TITLE
anisearch.de: breakage

### ISSUE THREAD

**Issue by nanderer** [uBlockOrigin/uAssets#19077]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.anisearch.de/anime/16618,reincarnated-as-a-sword/screenshots`

### Category

breakage

### Description

screenshots are not shown

### Other extensions used

dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2023-07-19 10-14-52](https://github.com/uBlockOrigin/uAssets/assets/45161625/01a18450-3ea1-4a23-ab3f-e4acb4f6b854)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 36d.3h.57m
Firefox: 102
filterset (summary):
 network: 101127
 cosmetic: 108909
 scriptlet: 20305
 html: 1000
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92032-79495, 5d.19h.14m
  fanboy-cookiemonster: 47732-220, 2d.20h.58m
  fanboy-social: 16105-2, 1d.4h.13m
 default:
  user-filters: 10-0, never
  ublock-filters: 34706-75, 4d.21h.10m
  ublock-badware: 7559-1, 4d.21h.9m
  ublock-privacy: 468-0, 3d.19h.2m
  ublock-unbreak: 2116-0, 4d.21h.8m
  ublock-quick-fixes: 404-0, 8m
  easylist: 68131-780, 1d.8h.15m
  easyprivacy: 33389-721, 4d.19h.6m
  urlhaus-1: 6413-0, 2h.9m
  plowe-0: 3723-1, 4d.19h.7m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1289 ms (selfie)
 maxAssetCacheWait: 686 ms
popupPanel:
 blocked: 4
 network:
  anisearch.com: 1
  cdntrf.com: 2
  opencmp.net: 1
 extended:
  ###footer-socials
  ###share-buttons
  ###share-facebook
  ###share-twitter
  ###share-reddit
  ##a[href^="https://reddit.com/submit?"]
  ##a[href^="https://www.facebook.com/share.php?"]
  ##.ad-square
  ##.ads-300
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||anisearch.de^$generichide
anisearch.de##.responsive_image[rel="sponsored"]
```

Maybe for `EasyList Germany`? But I don't know who to cc

**Comment by stephenhawk8054** [comment]
@Khrin Looks like we still need `generichide` for the anti-adblock?

**Comment by okiehsch** [comment]
Does EasyList fix anti-adblock isssues nowadays?

**Comment by okiehsch** [comment]
No, they apparently still don't.

For example.
https://github.com/easylist/easylist/issues/16724
Closed as invalid
