### ISSUE TITLE
investing.com: detection

### ISSUE THREAD

**Issue by aileia** [uBlockOrigin/uAssets#19085]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.investing.com/`

### Category

detection

### Description

they are changing the name code of the layer, so I cannot put a filter to override it. the layer prevents me from seeing the content 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1399" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/5088461/d0123da7-257b-4edc-8b43-bf10d3228cd1">

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 35d.23h.47m
Chromium: 114
filterset (summary):
 network: 98655
 cosmetic: 49711
 scriptlet: 19311
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 19-0, never
  TUR-0: 13633-11, 5m
  easylist: 68204-28, 5m
  easyprivacy: 33352-67, 5m
  plowe-0: 3723-1070, 5m
  ublock-badware: 7560-142, 5m
  ublock-filters: 33908-157, 5m
  ublock-privacy: 429-4, 5m
  ublock-unbreak: 2085-33, 5m
  urlhaus-1: 6425-0, 5m
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 507 ms (selfie)
 maxAssetCacheWait: 220 ms
popupPanel:
 blocked: 18
 network:
  investing.com: 2
  ad-score.com: 4
  adnxs.com: 1
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  dggaenaawxe8z.cloudfront.net: 1
  doubleclick.net: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  outbrain.com: 2
  pbxai.com: 1
  scorecardresearch.com: 1
 extended:
  ##.intro
  ###ad1
  ###ad2
  ###ad3
  ###findABroker
  ##.generalOverlay
  ##.midHeader
  ##.sponsoredArticle
  ##.dfpAdUnitContainer
  ###hpAdVideo
  ##.rightColumnAd
  ##.b9a4d02449647fe973974fea0b875d59
  ##body:style(overflow: auto !important)
  ##+js(no-fetch-if, ads)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you right click on the layer > Click on "Inspect element" and screenshot the devtools here?

**Comment by aileia** [comment]
<img width="1343" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/5088461/8ba8c7da-2a40-4ca7-9bec-bd74a34487d2">

**Comment by aileia** [comment]
<img width="408" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/5088461/c7a49e6a-1592-4bed-9e7e-32f1b698b02f">

**Comment by stephenhawk8054** [comment]
I mean the browser's "Inspect" option, not uBO's option.

**Comment by aileia** [comment]
<img width="414" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/5088461/8cb142aa-aa92-44a3-a5b4-32394257b72b">

**Comment by stephenhawk8054** [comment]
Can you click on this arrow and screenshot the expanded below to here?

https://github.com/uBlockOrigin/uAssets/assets/66517106/c38ac5ea-19bb-4610-9172-f6e2f8d6639d

**Comment by aileia** [comment]
<img width="423" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/5088461/8efb33af-2c1e-418e-9a95-a647529879e4">

**Comment by aileia** [comment]
<img width="888" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/5088461/f5f75418-76bd-4374-9926-c4eb6aa9a764">
I reinstalled ublock origin, the problem continues. I am seing this for a few days now. I was manually filtering it with unlock origin, but it keeps coming.

**Comment by stephenhawk8054** [comment]
@aileia Can you reproduce the issue > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by aileia** [comment]
<img width="584" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/5088461/40c09944-f844-4982-87f3-759e9164d98e">

**Comment by stephenhawk8054** [comment]
Ok, can you repeat this step this time?

> Can you right click on the layer > Click on "Inspect element" and screenshot the devtools here?

**Comment by aileia** [comment]
<img width="407" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/5088461/1f84d811-9526-4f0f-abde-c286a1e290aa">

**Comment by stephenhawk8054** [comment]
`investing.com##div[class] > :is(.ad-blockers-section, [class*="adNotification"]):upward(1)` should cover that, weird.

Can you add the above filter to "My filters" and test again?

**Comment by aileia** [comment]
it is working, thank you

**Comment by stephenhawk8054** [comment]
Hmmm... I literally just copied the filter from `quick fix` list to here. Don't know why it doesn't work for you at first.

**Comment by aileia** [comment]
I don't know, if I reexperience it, I try to post again.

**Comment by dportvine** [comment]
`https://www.investing.com/indices/us-30`

<details>
<summary>Screen</summary>

![2023-07-20_133402](https://github.com/uBlockOrigin/uAssets/assets/111344219/c8199b6c-2d86-40b8-9764-d385f000fb69)
</details>

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 112229
 cosmetic: 128153
 scriptlet: 25209
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26269-18, 12m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1634-25, 12m
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 704-0, 12m
  fanboy-cookiemonster: 47750-409, 12m
  ublock-annoyances: 5293-57, 12m
 default:
  user-filters: 0-0, never
  ublock-filters: 33906-42, 12m
  ublock-badware: 7560-1, 12m
  ublock-privacy: 431-2, 12m
  ublock-unbreak: 2085-7, 12m
  ublock-quick-fixes: 413-33, 12m
  easylist: 68304-351, 12m
  easyprivacy: 33339-400, 12m
  RUS-0: 39622-285, 12m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 1253 ms
 maxAssetCacheWait: 609 ms
popupPanel:
 blocked: 16
 network:
  investing.com: 1
  ad-score.com: 4
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  dggaenaawxe8z.cloudfront.net: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 2
  hotjar.com: 1
  outbrain.com: 1
  pbxai.com: 1
  primis.tech: 1
 extended:
  ##.OUTBRAIN
  ##[class^="outbrain_outbrain-wrapper"]
  ##[class*="overlay_overlay"]
  ###__next > .fixed
  ##div[data-test="ad-slot-visible"]
  ##div[class^="outbrain_outbrain-wrapper_"]
  ##body:style(overflow: auto !important)
  ##+js(no-fetch-if, ads)
  ##+js(set-constant, adNotificationDetected, false)
```
</details>

**Comment by stephenhawk8054** [comment]
@aileia Just to be sure, can you go to uBO's "Filter lists" tab and check if the quick fix list is checked or not?

**Comment by Stone2080** [comment]
I have same problem - "It looks like you're using an ad blocker". Refreshing filters doesn’t help

**Comment by Stone2080** [comment]
uBlock Origin: 1.70.0
Firefox: 149
filterset (summary):
 network: 192383
 cosmetic: 0
 scriptlet: 34572
 html: 3007
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 51186-11079, now
  ublock-badware: 10648-637, now
  ublock-privacy: 3924-24, now
  ublock-unbreak: 2808-411, now
  easylist: 98512-30534, now
  easyprivacy: 55618-37, now
  plowe-0: 3521-1022, now
  RUS-0: 41753-21275, now
  urlhaus-1: 26855-10, now
  ublock-quick-fixes: 427-124, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 24 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 parseAllABPHideFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 379 ms (selfie)
 maxAssetCacheWait: 178 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  investing.com: 3
  cloudflareinsights.com: 2
  doubleclick.net: 1
  facebook.net: 1
  hotjar.com: 1
  invmed.co: 2
  pbxai.com: 2
 extended:
  ##+js(trusted-set-cookie, smd, '', 0, '', domain, .investing.com…
  ##+js(trusted-set-cookie, udid, '', 0, '', domain, .investing.co…
  ##+js(trusted-set-cookie, inudid, '', 0, '', domain, .investing.…
  ##+js(set-constant, adNotificationDetected, false)
  ##+js(prevent-fetch, ads)

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.
