### ISSUE TITLE
haberturk.com: ads

### ISSUE THREAD

**Issue by mta009** [uBlockOrigin/uAssets#19080]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.haberturk.com/`

### Category

ads

### Description

link:
https://adsp.haberturk.com/advertpro/servlet/click/media?mid=24897&pid=0&lookup=true&position=1&date=(date)&uuid=(email)

### Other extensions used

Adblock Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ekran görüntüsü 2023-07-19 162754](https://github.com/uBlockOrigin/uAssets/assets/125624292/4b26f934-d872-4032-90b5-36c73bc9582f)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 41d.59m
Chromium: 114
filterset (summary):
 network: 96938
 cosmetic: 39594
 scriptlet: 17994
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 175-8, never
  easylist: 68204-9, now
  easyprivacy: 33352-62, now
  plowe-0: 3723-1069, now
  ublock-badware: 7560-142, now
  ublock-filters: 33895-147, now
  ublock-privacy: 429-4, 29m
  ublock-quick-fixes: 401-99, now
  ublock-unbreak: 2085-34, now
  urlhaus-1: 6425-0, now
filterset (user): [array of 175 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 931 ms (selfie)
 maxAssetCacheWait: 98 ms
popupPanel:
 blocked: 4
 network:
  haberturk.com: 1
  gemius.pl: 2
  googletagmanager.com: 1
 extended:
  ##.ads-zone
```
</details>

**Comment by stephenhawk8054** [comment]
Can you turn on `AdGuard Turkish` filter list in the settings and test again?

**Comment by mta009** [comment]
Thanks that worked, but now there is a white space.
![Ekran görüntüsü 2023-07-19 163615](https://github.com/uBlockOrigin/uAssets/assets/125624292/d6874fbc-9567-4d4c-890c-f71deab50e82)

**Comment by stephenhawk8054** [comment]
I don't see any placeholders on the page.

> ### Other extensions used
>
> Adblock Plus

Can you turn off other extensions and test again?

**Comment by mta009** [comment]
There is still that blank space.
