### ISSUE TITLE
intelcom.ca: breakage

### ISSUE THREAD

**Issue by muchqs** [uBlockOrigin/uAssets#19093]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://intelcom.ca/en/track-your-package/?tracking-id=[TRACKING NUMBER]`

### Category

breakage

### Description

Intelcom is a courier frequently used by Amazon Canada, especially for non-Prime users. This is their package tracking page. The page returns `An error has occurred. Please try again in a few moments.` with uBO on.

Logger shows URL is matching filter `/v2/tracking/*` from EasyPrivacy.
URL: `https://intelcom.ca/cfworker/v2/tracking/TRACKING NUMBER/`

When I click the @@ from the Logger and refresh the page, the tracking page loads properly.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Page error: https://i.imgur.com/vfeilkj.png
Page works: https://i.imgur.com/IAdnfbA.png
Log 1: https://i.imgur.com/5SSlMfw.jpg
Log 2: https://i.imgur.com/tletkSK.jpg

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 36d.6h.56m
Chromium: 98
filterset (summary):
 network: 118187
 cosmetic: 130974
 scriptlet: 24558
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 24619-128, 17m
  adguard-cookies: 26427-29, 17m
  adguard-mobile-app-banners: 4438-10, 17m
  adguard-other-annoyances: 13130-10, 17m
  adguard-popup-overlays: 23043-63, 17m
  adguard-social: 20953-887, 17m
  adguard-spyware-url: 1134-3, 17m
  adguard-widgets: 2211-3, 17m
  block-lan: 48-0, 17m
  ublock-annoyances: 5293-182, 17m
 default:
  user-filters: 26-0, never
  easylist: 68207-124, 17m
  easyprivacy: 33352-142, 17m
  plowe-0: 3723-1072, 17m
  ublock-badware: 7560-142, 17m
  ublock-filters: 33904-535, 17m
  ublock-privacy: 429-7, 17m
  ublock-quick-fixes: 407-96, 17m
  ublock-unbreak: 2085-38, 17m
  urlhaus-1: 6352-0, 56m
filterset (user): [array of 26 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 6490 ms (selfie)
 maxAssetCacheWait: 581 ms
popupPanel:
 blocked: 2
 network:
  intelcom.ca: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/aab1a24910aef8fd676f10cee7d57b7072b107ba
