### ISSUE TITLE
nyaa.iss.ink: popups

### ISSUE THREAD

**Issue by Ichigo27** [uBlockOrigin/uAssets#19098]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nyaa.iss.ink/view/1692772`

### Category

popups

### Description

popups opens on click on this websites

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 36d.7h.50m
Firefox: 115
filterset (summary):
 network: 96709
 cosmetic: 39399
 scriptlet: 17953
 html: 1003
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34776-77, 1d.2h.58m
  ublock-badware: 7562-1, 6h.40m
  ublock-privacy: 464-0, 6d.6h.25m
  ublock-unbreak: 2134-2, 1d.2h.57m
  ublock-quick-fixes: 403-0, 11h.35m
  easylist: 68018-768, 3d.6h
  easyprivacy: 33352-719, 11h.36m
  urlhaus-1: 6352-0, 9h.29m
  plowe-0: 3723-2, 3d.10h.11m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 485 ms (selfie)
 maxAssetCacheWait: 144 ms
popupPanel:
 blocked: 14
 network:
  arc.io: 3
  cloudflareinsights.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
  iss.one: 1
  profitabledisplayformat.com: 5
```
</details>

**Comment by Daxy7** [comment]
https://github.com/uBlockOrigin/uAssets/assets/91396482/6027a41a-fb80-4767-8c99-54cf9d35ee91
can't access any thread but the homepage (error code 520 unknown error)
```
https://nyaa.iss.ink/
```

**Comment by ghajini** [comment]
@ryanbr 

`||dawirax.com^`
