### ISSUE TITLE
another cutwin domain

### ISSUE THREAD

**Issue by simoconfa** [uBlockOrigin/uAssets#1909]
### URL(s) where the issue occurs

`http://cutl.in/2b97`

### Describe the issue

adblock detected

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/8224154/38467587-31f3b98e-3b3b-11e8-9ea9-8c2e79db961f.png)

### Versions

- Browser/version: FF latest
- uBlock Origin version: latest + easylist

### Settings

I don't have custom filters which affect the domain

### Notes

It is another cutwin.com. The same script changed for this domain I think it would work.

**Comment by mapx-** [comment]
update ublock filters
