### ISSUE TITLE
pikabu.ru: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#19094]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pikabu.ru/`

### Category

privacy

### Description

The domain `a.pikabu.ru` is used to log visitor's information and fingerprints user. The logging is triggered by the following script: `https://cs.pikabu.ru/apps/ub/5.1.0/desktop/analytics.js`. At the very least, the site logs user's time zone, browser, OS, whether the user uses ad blocker, and some kind of fingerprint id.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![pikabu](https://github.com/uBlockOrigin/uAssets/assets/115052854/c8a41179-3f25-4ec2-9e9f-63b21f038f80)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.50.1b17
Firefox: 115
filterset (summary):
 network: 101326
 cosmetic: 108889
 scriptlet: 20363
 html: 1003
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 3895-54, now
  easylist-chat: 129-0, now
  fanboy-cookiemonster: 47750-229, now
  easylist-newsletters: 6282-21, now
  easylist-notifications: 2633-160, now
  fanboy-social: 16106-13, now
 default:
  user-filters: 2-0, never
  ublock-filters: 34782-41, now
  ublock-badware: 7562-1, now
  ublock-privacy: 468-0, now
  ublock-unbreak: 2134-1, now
  ublock-quick-fixes: 403-34, 19m
  easylist: 68207-336, now
  easyprivacy: 33352-86, now
  urlhaus-1: 6352-0, now
  plowe-0: 3723-1071, now
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 316 ms (selfie)
 maxAssetCacheWait: 179 ms
popupPanel:
 blocked: 10
 network:
  pikabu.ru: 4
  googletagmanager.com: 1
  tns-counter.ru: 1
  yandex.ru: 4
 extended:
  ##.scroll-up-button
  ##.grecaptcha-badge
  ###credential_picker_container
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||pikabu.ru/*/analytics.
||a.pikabu.ru^
```

@ryanbr
