### ISSUE TITLE
viefaucet.com: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#19103]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://viefaucet.com/app/faucet`

### Category

detection

### Description

Adblocker detected...

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/75168867/aa857bbf-de83-46af-95a6-fa172f5c7c02)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 18d.12h.4m
Chromium: 114
filterset (summary):
 network: 97141
 cosmetic: 22750
 scriptlet: 18008
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 68403-16495, now
  easyprivacy: 33356-64, now
  plowe-0: 3723-1070, now
  ublock-badware: 7562-142, now
  ublock-filters: 34057-360, now
  ublock-privacy: 431-5, now
  ublock-quick-fixes: 341-181, 5m
  ublock-unbreak: 2086-35, now
  urlhaus-1: 6440-0, 5m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 26 redacted]
switchRuleset:
 added: [array of 6 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 18743 ms (selfie)
 maxAssetCacheWait: 470 ms
popupPanel:
 blocked: 8
 network:
  bmcdn5.com: 3
  coinzillatag.com: 1
  czilladx.com: 3
  googletagmanager.com: 1
 extended:
  ##.ads
  ##.is-guttered > .ads:upward(.is-guttered)
```
</details>

**Comment by okiehsch** [comment]
I tagged the issue so every maintainer can easily see that an account is needed, maybe someone already has one.
