### ISSUE TITLE
my.plaid.com: breakage

### ISSUE THREAD

**Issue by raxod502** [uBlockOrigin/uAssets#19101]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://my.plaid.com/sign-in`

### Category

breakage

### Description

When logging into the Plaid consumer portal, if `metrics.plaid.com` is blocked, then login may fail with an "Error" popup that contains no further details.

I filed a support ticket to ask about it, and they said that it was their security/fraud mechanism, and that they recommended disabling ad-blockers. By trial and error I found that the domain which had to be unblocked was `metrics.plaid.com` for login to work.

I tried my best to follow the contributing instructions, but I wasn't 100% sure whether this was the right place for issues in all filter lists that are shipped with uBlock Origin by default, or only the ones that are _enabled_ by default. The filter list that blocks this domain is AdGuard Tracking Protection.

### Other extensions used

ClearURLs

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/6559064/87aeb786-b19c-4902-a763-3a6cb8caa3b1)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 33d.2h.9m
Firefox: 112
filterset (summary):
 network: 310293
 cosmetic: 226218
 scriptlet: 41743
 html: 1184
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69276-67096, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92059-92050, now
  adguard-generic: 72797-6483, now
  adguard-mobile: 8449-96, now
  adguard-spyware-url: 1135-5, now
  block-lan: 48-0, now
  curben-phishing: 127974-59, now
  curben-pup: 189-0, now
  adguard-social: 20936-826, now
  fanboy-thirdparty_social: 69-0, now
  fanboy-cookiemonster: 47752-3845, now
  fanboy-social: 16107-21, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 34931-615, 1h.56m
  ublock-badware: 7564-1, 1h.56m
  ublock-privacy: 470-0, now
  ublock-unbreak: 2134-3, 1h.56m
  ublock-quick-fixes: 342-0, 1h.56m
  easylist: 68385-994, now
  easyprivacy: 33348-893, now
  urlhaus-1: 6440-0, now
  plowe-0: 3723-2, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 showIconBadge: false
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 410 ms (selfie)
 maxAssetCacheWait: 249 ms
 unsuspendAfter: 68 ms
popupPanel:
 blocked: 20
 network:
  plaid.com: 14
  optimizely.com: 4
  solvvy.com: 1
  zdassets.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you do these steps (follow strictly the step order, don't mix the steps orders, or skip any steps):

1. Click on uBO icon > &#9636; ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger), it will open a logger window
2. Load the website again and reproduce the issue
3. Switch to the logger window that was opened in step 1, [click on search bar, choose `blocked` and `allowed`](https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output)
4. Copy the logger via &#128203; [export/copy button at the top right](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog)
5. Paste the logs here

**Comment by raxod502** [comment]
I'm sorry for the delay! Here are the requested logs:

<details><summary>Logger output</summary>

```
+39
||analytics.plaid.com^
--
my.plaid.com
1
post
xhr
https://analytics.plaid.com/sentry/api/596/store/?sentry_key=0601c41a8f8a4253a3a813390e19601f&sentry_version=7
```
```
+39
||analytics.plaid.com^
--
my.plaid.com
1
post
xhr
https://analytics.plaid.com/sentry/api/596/store/?sentry_key=0601c41a8f8a4253a3a813390e19601f&sentry_version=7
```
```
+39
||analytics.plaid.com^
--
my.plaid.com
1
post
xhr
https://analytics.plaid.com/sentry/api/596/store/?sentry_key=0601c41a8f8a4253a3a813390e19601f&sentry_version=7
```
```
+39
||metrics.plaid.com^
--
my.plaid.com
1
get
xhr
https://metrics.plaid.com/init
```
```
+21
||optimizely.com^$3p
--
my.plaid.com
3
get
xhr
https://cdn.optimizely.com/datafiles/KSVSSpuYiqQDU92RCDfsU.json
```
```
+1
||optimizely.com^$3p
--
my.plaid.com
3
get
xhr
https://cdn.optimizely.com/datafiles/KSVSSpuYiqQDU92RCDfsU.json
```
```
+1
||analytics.plaid.com^
--
my.plaid.com
1
get
script
https://analytics.plaid.com/analytics.js/v1/3suyIsByHgREJk251fg4ZJMdyAcpnheR/analytics.min.js
```
```
+1
||api.solvvy.com/v1/pixels/track
--
my.plaid.com
3
get
xhr
https://api.solvvy.com/v1/pixels/track?org_id=1466&api_key=12daddaf-8a8a-47df-b88f-4259edd698aa~q8G37b5AIjXX1Odn4HBkqrRROBHLAT9QKqgGwWEp2wzNsp2jvYAc5EE94eDt7JDV&user_identifier=407943a5-086a-4ed9-b610-87d33c52f2f3&session_identifier=3e7640ea-e83e-4fd9-b212-ec945a33c0f7&event=page_visit&channel=ticket&environment=prod&metadata=eyJ1cmwiOiJodHRwczovL215LnBsYWlkLmNvbS8iLCJicm93c2VyX3N1cHBvcnRlZCI6dHJ1ZSwidXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChYMTE7IExpbnV4IHg4Nl82NDsgcnY6MTA5LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTEyLjAiLCJldmVudF9pZCI6ImFhMzYxNmIyLTBhZDAtNGI4ZC05YTQ2LWNjZDUyMmNmYWNhMCJ9
```
```
+1
||optimizely.com^$3p
--
my.plaid.com
3
get
xhr
https://cdn.optimizely.com/datafiles/KSVSSpuYiqQDU92RCDfsU.json
```
```
+1
||optimizely.com^$3p
--
my.plaid.com
3
get
xhr
https://cdn.optimizely.com/datafiles/KSVSSpuYiqQDU92RCDfsU.json
```
```
+1
||analytics.plaid.com^
--
my.plaid.com
1
post
xhr
https://analytics.plaid.com/sentry/api/596/store/?sentry_key=0601c41a8f8a4253a3a813390e19601f&sentry_version=7
```
```
+1
||zdassets.com/ekr/snippet.js
--
my.plaid.com
3
get
script
https://static.zdassets.com/ekr/snippet.js?key=91e676c2-94ed-4ea0-9559-b752013bfe30
```
```
+1
@@||cdn.segment.com/v1/projects/
++
my.plaid.com
3
get
xhr
https://cdn.segment.com/v1/projects/3suyIsByHgREJk251fg4ZJMdyAcpnheR/integrations
```
```
+1
||optimizely.com^$3p
--
my.plaid.com
3
get
xhr
https://cdn.optimizely.com/datafiles/KSVSSpuYiqQDU92RCDfsU.json
```
```
+0
/beacon.js
--
my.plaid.com
1
get
script
https://cdn.plaid.com/beacon/stable/beacon.js
```
```
+0
no-csp-reports: * true
--
my.plaid.com
1
post
csp_report
https://analytics.plaid.com/sentry/api/596/security/?sentry_key=0601c41a8f8a4253a3a813390e19601f
```
```
+0
https://my.plaid.com/
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
@@||metrics.plaid.com/init$xhr,domain=plaid.com
```

**Comment by stephenhawk8054** [comment]
Since this is caused by Adguard Tracking Filter List, please report here: https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by raxod502** [comment]
I apologize for reporting to the wrong place, I have followed up at https://github.com/AdguardTeam/AdguardFilters/issues/157984. Thanks.
