### ISSUE TITLE
huya.com: nuisance

### ISSUE THREAD

**Issue by Iovenoname** [uBlockOrigin/uAssets#19108]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.huya.com/lpl`

### Category

nuisance

### Description

Hello developer, I found that it does not have the ability to block a very annoying pop-up window in the process of using uBlockOrigin. As shown in the picture, I deliberately marked it in the picture. This annoying pop-up window exists in any link under the domain name www.huya.com, such as www.huya.com/l  This is a very frustrating pop-up window behavior because it is not short-lived, but always exists.

This kind of intrusive pop-up window is really very annoying and seriously affects the browsing experience of the Internet. I believe that uBlock Origin appeared to solve this kind of trouble, which is why I have always loved uBlock Origin. In addition, popular websites with such intrusive pop-up windows include www.zhihu.com (https://zhuanlan.zhihu.com/p/463964971), www.bilibili.com
I hope the developer can help to solve this problem, thank you very much.

### Other extensions used

I don't use any other extensions in my Firefox browser except uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![螢幕擷取畫面 2023-07-21 183357](https://github.com/uBlockOrigin/uAssets/assets/124352494/cc8d3172-877a-4e3e-a23e-e6f8f63e8f23)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Firefox: 115
filterset (summary): 
 network: 197345
 cosmetic: 236592
 scriptlet: 41916
 html: 1184
listset (total-discarded, last-updated): 
 added: 
  adguard-generic: 72818-6499, 1h.34m
  adguard-mobile: 8448-98, 1h.34m
  adguard-spyware-url: 1135-5, 1h.34m
  block-lan: 48-0, 1h.34m
  adguard-social: 20937-828, 1h.32m
  fanboy-thirdparty_social: 69-0, 1h.32m
  fanboy-cookiemonster: 47751-3845, 1h.32m
  fanboy-social: 16108-23, 1h.32m
  ublock-annoyances: 5257-16, 1h.32m
  dpollock-0: 11534-494, 1h.32m
  adguard-spyware: 62920-17424, 1h.34m
  adguard-cookies: 26441-58, 1h.32m
  adguard-popup-overlays: 23058-1457, 1h.32m
  adguard-mobile-app-banners: 4440-1057, 1h.32m
  adguard-other-annoyances: 13134-299, 1h.32m
  adguard-widgets: 2211-1, 1h.32m
  easylist-annoyances: 3871-139, 1h.32m
  easylist-chat: 130-9, 1h.32m
  easylist-newsletters: 6287-20, 1h.32m
  easylist-notifications: 2633-3, 1h.32m
 default: 
  user-filters: 1228-6, never
  ublock-filters: 34931-629, 5h.25m
  ublock-badware: 7564-1, 5h.25m
  ublock-privacy: 470-0, 5h.25m
  ublock-unbreak: 2135-3, 5h.25m
  ublock-quick-fixes: 342-0, 5h.24m
  easylist: 68385-1061, 5h.24m
  easyprivacy: 33356-900, 5h.23m
  urlhaus-1: 6440-0, 5h.23m
  plowe-0: 3723-4, 5h.23m
  CHN-0: 24635-197, 5h.26m
filterset (user): [array of 1210 redacted]
trustedset: 
 added: [array of 1 redacted]
 removed: 
  moz-extension-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 7193 ms
 maxAssetCacheWait: 21 ms
popupPanel: 
 blocked: 326
 network: 
  huya.com: 314
  baidu.com: 1
  kunluncan.com: 1
  msstatic.com: 10
 cosmetic: 
  ##.sidebar-banner
  ###huya-ab
  ###huya-ab-fixed
```
</details>

**Comment by stephenhawk8054** [comment]
Can you check annoyance lists in this repo: https://github.com/cjx82630/cjxlist ?
