### ISSUE TITLE
funkysextube.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1910]
URL(s) where the issue occurs

`http://www.funkysextube.com/2285843/Teen_girl_Beata_plays_with_her_fresh_and_plump`

Describe the issue

ADS

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`||tds.sersh.com^$subdocument,domain=funkysextube.com|noworrytube.com` gets the ads. I have no idea what should be done about the rest of the garbage those sites have.

**Comment by zaphodbeebblebrox** [comment]
The `#sss` filter breaks many videos, including the first example

**Comment by KiLL4FuNK** [comment]
||sersh.com^
noworrytube.com###sss
funkysextube.com###sss
||befuck.com^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.google.com *.gstatic.com *.google-analytics.com
befuck.com##script:inject(window.open-defuser.js)
befuck.com##.dnl


the video player does not work

**Comment by KiLL4FuNK** [comment]
but just blocking the advertising is fine
