### ISSUE TITLE
amazon.de: breakage

### ISSUE THREAD

**Issue by darkza** [uBlockOrigin/uAssets#19109]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.amazon.de/ap/signin?dplnkId=2fcae354-9466-4f4c-b57a-ba93975633e5`

### Category

breakage

### Description

site shows after login this site is missing

### Other extensions used

deaktivated temp all of it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 12d.22h.35m
Firefox Mobile: 115
filterset (summary):
 network: 102320
 cosmetic: 60126
 scriptlet: 20282
 html: 1000
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 62527-32289, 3d.21h.26m
 default:
  user-filters: 0-0, never
  ublock-filters: 35069-334, 3d.21h.26m
  ublock-badware: 7568-1, 3d.21h.26m
  ublock-privacy: 468-1, 3d.21h.26m
  ublock-unbreak: 2128-1, 3d.21h.26m
  ublock-quick-fixes: 342-2, 9h.8m
  adguard-mobile: 8427-121, 3d.21h.26m
  easylist: 68015-17226, 3d.21h.26m
  easyprivacy: 33343-744, 3d.21h.26m
  urlhaus-1: 6417-0, 20h.8m
  plowe-0: 3739-2, 12d.22h.35m
  DEU-0: 6962-403, 20h.9m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 952 ms (selfie)
 maxAssetCacheWait: 226 ms
popupPanel:
 blocked: 5
 network:
  amazon.de: 2
  amazon.com: 3
```
</details>

**Comment by okiehsch** [comment]
Have you tried disabling the `fanboy-cookiemonster` list?

**Comment by darkza** [comment]
after reinstalling Firefox, every wired site i had acts again normal. not ublicks fault!
