### ISSUE TITLE
thapcam.net: breakage

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#19115]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Some images are mistakenly blocked. `.gif$domain=thapcam.net` causes it, which is a pretty broad filter.

### URL(s) where the issue occurs.

`https://live3.thapcam.net/`

### Screenshot(s)

![Screenshot from 2023-07-21 21-23-19](https://github.com/uBlockOrigin/uAssets/assets/89158249/bcea10c6-dc49-4408-ba9f-53c9bd0c0929)

### uBO version

v1.51.1b0

### Browser name and version

Firefox 115.0.2

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by stephenhawk8054** [comment]
The only images being blocked on the home page are `https://live3.thapcam.net/1.gif` which is a 1x1 pixel gif.
