### ISSUE TITLE
radyohome.com: ads

### ISSUE THREAD

**Issue by tunceray1** [uBlockOrigin/uAssets#19113]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://radyohome.com/radyolar/world-hits`

### Category

ads

### Description

Plays a pre-roll ad after pressing the play button. Each ad is about 10 seconds long.
Can uBO block this ad without breaking the stream?

### Other extensions used

Only uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/140217932/db61fed2-4132-4f86-8b43-9d0ff1ed6149)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 39d.3h.8m
Firefox: 115
filterset (summary):
 network: 228966
 cosmetic: 51244
 scriptlet: 22816
 html: 1188
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1135-5, 4m
  curben-phishing: 128569-58, 4m
  curben-pup: 199-0, 4m
  ublock-annoyances: 5258-7, 4m
 default:
  user-filters: 49-0, never
  ublock-filters: 34964-238, 4m
  ublock-badware: 7570-1, 4m
  ublock-privacy: 470-0, 4m
  ublock-unbreak: 2135-3, 4m
  ublock-quick-fixes: 322-0, 4m
  easylist: 68379-727, 4m
  easyprivacy: 33360-727, 4m
  urlhaus-1: 6373-0, 4m
  plowe-0: 3720-2, 4m
  TUR-0: 13644-13, 4m
filterset (user): [array of 55 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 suspendUntilListsAreLoaded: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1126 ms (selfie)
 maxAssetCacheWait: 493 ms
 unsuspendAfter: 290 ms
popupPanel:
 blocked: 3
 network:
  addthis.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
I can't hear the ads, even when using VPN to Turkey.

---

```yml
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 suspendUntilListsAreLoaded: false
 tooltipsDisabled: true
default:
  user-filters: 49-0, never
```

You are using some modified settings. Can you test the site in another Firefox profile with only uBO and its default settings?

**Comment by tunceray1** [comment]
@stephenhawk8054 

I don't know how to create a new Firefox profile, but I reinstalled uBO and tested Firefox in incognito mode and I still get ads.

I also get the same ads in Chrome.

**Comment by stephenhawk8054** [comment]
Are you using any other extensions?

**Comment by tunceray1** [comment]
@stephenhawk8054 I don't have any other extensions. Only uBO.

You can close this ticket if you cannot reproduce it. I tried to hide ad by blocking some scripts but it didn't work.

**Comment by dportvine** [comment]
You try block this `||radyotvonline.net/audionfr_newEnco/ad_`? Can you add logger screenshot after pressing the play button.

**Comment by stephenhawk8054** [comment]
Ok, I can hear the ads now.

---

@gorhill There are m3u8 files with links that have `ad` in the URLs. However, I can't use `m3u-prune` on this site using this filter

```adb
radyohome.com##+js(m3u-prune, ad, .m3u8, log, 1)
```

Can you use any `m3u-prune` on this?

**Comment by gorhill** [comment]
`log, 1` doesn't work for non-multiline pattern argument. I will address this.

**Comment by stephenhawk8054** [comment]
Actually without `log, 1`, I can't seem to use `m3u-prune` on this site either:

```adb
radyohome.com##+js(m3u-prune, ad, .m3u8)
```

**Comment by gorhill** [comment]
How long do I have to wait to hear an ad?

**Comment by stephenhawk8054** [comment]
It's at beginning. You might need to use VPN to Turkey if needed.

At beginning there's some normal talk appear (that does not look like a song, the language is in Turkish so quite difficult here). 

If there are connections with `/ad_0` appearing in the logger, they are the ads.

**Comment by stephenhawk8054** [comment]
Yeah, confirm you need to use VPN to Turkey to hear the ads. If I use my network (without VPN), there's no ads

**Comment by dportvine** [comment]
I'm using **Urban VPN proxy** and I can hear Nissan Qashqai ads.

<details>
<summary>Video</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/a1e72088-9803-44cc-8799-b819907399a2
</details>

**Comment by mapx-** [comment]
test

`radyohome.com##+js(set, FSBase.ad_initialize, noopFunc)`

**Comment by tunceray1** [comment]
> test
> 
> `radyohome.com##+js(set, FSBase.ad_initialize, noopFunc)`

This didn't work. I'm getting the same ad on the radios below.

```
https://radyohome.com/radyolar/90lar
https://radyohome.com/radyolar/popland
```

**Comment by punisher018** [comment]
First of all, let me state that I connected from Turkey IP. I wrote this explanation to help those who write filters. Because the advertisement appears very rarely and it may be difficult to perceive the advertisement in Turkish.

[Log output.docx](https://github.com/uBlockOrigin/uAssets/files/12464990/Log.output.docx)

https://cdn.radyotvonline.net/moondigital_newEnco/ad*
I added it to my filters and the bolded places in the log are the ones blocked because of the filter I added. If there is an ad on the radio, the radio does not play because of this filter. Ads on the site appear when the radio is first turned on and very rarely.
 
Although I'm not sure, it seems to me that the possibility of advertising on the radio in this link are higher.
https://radyohome.com/radyolar/pal-station

@mapx I tried it before with your filter and again there were ads.

**Comment by punisher018** [comment]
@ghajini it doesn't work. Ad still there.

**Comment by mapx-** [comment]
"install" `xhrp` scriptlet from 
https://github.com/mapx-/test/blob/master/xhrp5.js

(using userResourcesLocation in [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings))

add & test:

```
radyohome.com##+js(set, FSBase.ad_initialize, noopFunc)
radyohome.com##+js(xhrp, /m3u8/, /#EXTINF.*https.*\/ad_.*aac/, )
```

**Comment by punisher018** [comment]
@mapx it doesn't work too.

**Comment by tunceray1** [comment]
@mapx- 
This method doesn't work either. I still get preroll ads on some radios.

---

I'm closing it so it doesn't take any more time. This increases the workload of developers.
I will ignore this ad. Thanks for help

**Comment by stephenhawk8054** [comment]
> "install" `xhrp` scriptlet from https://github.com/mapx-/test/blob/master/xhrp5.js
> 
> (using userResourcesLocation in [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings))
> 
> add & test:
> 
> ```
> radyohome.com##+js(set, FSBase.ad_initialize, noopFunc)
> radyohome.com##+js(xhrp, /m3u8/, /#EXTINF.*https.*\/ad_.*aac/, )
> ```

In order to use this method, you'll need to force update at least one of your filter lists again before using the new filter.
