### ISSUE TITLE
nofilmschool.com: ads

### ISSUE THREAD

**Issue by abunker3d** [uBlockOrigin/uAssets#19114]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nofilmschool.com/`

### Category

ads

### Description

There is a large ad banner at the top of the website leltover.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="986" alt="Screenshot 2023-07-21 180433" src="https://github.com/uBlockOrigin/uAssets/assets/43965805/70acf837-16c3-4bab-a656-9f945d0d067f">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 96974
 cosmetic: 39451
 scriptlet: 18030
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68381-10, now
  easyprivacy: 33360-62, now
  plowe-0: 3720-1068, now
  ublock-badware: 7568-142, now
  ublock-filters: 34087-148, now
  ublock-privacy: 433-4, now
  ublock-quick-fixes: 321-187, now
  ublock-unbreak: 2086-34, now
  urlhaus-1: 6303-0, now
filterset (user): [empty]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 106 ms (selfie)
 maxAssetCacheWait: 46 ms
popupPanel:
 blocked: 12
 network:
  aniview.com: 1
  convertkit.com: 1
  googletagmanager.com: 2
  htlbid.com: 1
  rbl.ms: 6
  rebelmouse.com: 1
 extended:
  ##.horizontal_ad
  ##.stickyad
```
</details>

**Comment by abunker3d** [comment]
Also, pages such as https://nofilmschool.com/davinci-resolve-18-5 have large advertisement leftovers throughout the articles.
<img width="985" alt="Screenshot 2023-07-21 180923" src="https://github.com/uBlockOrigin/uAssets/assets/43965805/011a466a-c34c-4baa-8a3d-be6935095e34">

**Comment by stephenhawk8054** [comment]
```adb
nofilmschool.com##.maintop_ad
nofilmschool.com##[class^="rblad-nfs_content"]
```

@ryanbr
