### ISSUE TITLE
cgpress.org: ads

### ISSUE THREAD

**Issue by abunker3d** [uBlockOrigin/uAssets#19116]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cgpress.org/`

### Category

ads

### Description

There is a leftover ad banner near the top of the webpage.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="988" alt="Screenshot 2023-07-21 221842" src="https://github.com/uBlockOrigin/uAssets/assets/43965805/eb333832-4aeb-4852-bd44-1d5a09d9abfa">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 96971
 cosmetic: 39454
 scriptlet: 18031
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68384-10, 9m
  easyprivacy: 33357-62, 9m
  plowe-0: 3720-1068, 9m
  ublock-badware: 7568-142, 9m
  ublock-filters: 34088-148, 9m
  ublock-privacy: 433-4, 9m
  ublock-quick-fixes: 321-187, 9m
  ublock-unbreak: 2086-34, 9m
  urlhaus-1: 6303-0, 9m
filterset (user): [empty]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 183 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 29
 network:
  cgpress.org: 19
  doubleclick.net: 1
  ezodn.com: 2
  googlesyndication.com: 3
  googletagmanager.com: 2
  pubmatic.com: 1
  quantserve.com: 1
 extended:
  ##.ezoic-adpicker-ad
  ##.ezoic-ad
  ##.adtester-container
  ##.ezoic-ad-adaptive
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ##[data-ez-name]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
```
</details>

**Comment by stephenhawk8054** [comment]
Please report here: https://github.com/easylist/easylist/issues
