### ISSUE TITLE
apkmirror.com: ads

### ISSUE THREAD

**Issue by Noone143** [uBlockOrigin/uAssets#19110]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.apkmirror.com/`

### Category

ads

### Description

They are ad leftovers and banners that "I nEEd to pAy PrEmiUm foR DaRk ModE, etc.. "
Which are not there before, since the 3-4ish months..

and also I'm using the kiwibrowser that enables extensions on your device

### Other extensions used

None

### Screenshot(s)

https://mega.nz/file/9IFSHBhY#l-L9YI87yrq92mOaQeBs8WxgAsS21IlmDVTSIsJfyCc

This is the link of the screenshot..
(sry if I post it mega, because I am on mobile and clipboard somehow doesn't copy pictures on it) n

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 42d.15m
Chromium: 105
filterset (summary):
 network: 310858
 cosmetic: 0
 scriptlet: 41979
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69302-60735, 1m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92059-85547, 1m
  adguard-cookies: 26447-26447, 1m
  adguard-generic: 72831-37036, 1m
  adguard-mobile: 8456-6955, 1m
  adguard-mobile-app-banners: 4440-4440, 1m
  adguard-other-annoyances: 13138-13138, 1m
  adguard-popup-overlays: 23065-23065, 1m
  adguard-social: 20939-20369, 1m
  adguard-spyware: 62924-1641, 1m
  adguard-spyware-url: 1135-6, 1m
  adguard-widgets: 2212-2212, 1m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 68363-29798, 1m
  easyprivacy: 33360-17099, 1m
  plowe-0: 3720-1566, 1m
  ublock-badware: 7562-1064, 1m
  ublock-filters: 34083-12158, 1m
  ublock-privacy: 431-76, 1m
  ublock-quick-fixes: 321-222, 1m
  ublock-unbreak: 2086-384, 1m
  urlhaus-1: 6373-2, 1m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: true
 parseAllABPHideFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5607 ms
 maxAssetCacheWait: 2008 ms
popupPanel:
 blocked: 2
 network:
  outbrain.com: 1
  quantcast.com: 1
 extended:
  ##+js(remove-class, disabled, a.downloadButton.disabled)
  ##+js(abort-on-stack-trace, document.querySelectorAll, /Object\.…
  ##+js(remove-node-text, script, document.body.insertAdjacentHTML…
```
</details>

**Comment by Noone143** [comment]
Hi, please ignore that I'm downloading things on this website because I'm on Huawei and I don't trust their App Gallery, because maybe it has too much spyware

**Comment by okiehsch** [comment]
Those are self advertisement, we don't fix that.

Adding
`apkmirror.com##.f-nowrap.d-flex.p-relative`
to your filter list should work.
