### ISSUE TITLE
cgdirector.com: ads

### ISSUE THREAD

**Issue by abunker3d** [uBlockOrigin/uAssets#19117]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cgdirector.com/power-limit-throttling-and-how-prevent-it/`

### Category

ads

### Description

Large section of leftover ad space at top right corner of all articles on [cgdirector.com](https://www.cgdirector.com/)

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="987" alt="Screenshot 2023-07-21 222521" src="https://github.com/uBlockOrigin/uAssets/assets/43965805/986d4f94-563a-44bc-8f78-df2d4c56c875">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 96971
 cosmetic: 39454
 scriptlet: 18031
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68384-10, 15m
  easyprivacy: 33357-62, 15m
  plowe-0: 3720-1068, 15m
  ublock-badware: 7568-142, 15m
  ublock-filters: 34088-148, 15m
  ublock-privacy: 433-4, 15m
  ublock-quick-fixes: 321-187, 15m
  ublock-unbreak: 2086-34, 15m
  urlhaus-1: 6303-0, 15m
filterset (user): [empty]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 183 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 37
 network:
  cgdirector.com: 2
  adthrive.com: 2
  cloudflareinsights.com: 1
  doubleclick.net: 2
  google.com: 2
  googlesyndication.com: 3
  googletagmanager.com: 1
  gstatic.com: 1
  jwpltx.com: 1
  videoplayerhub.com: 1
  youtube.com: 21
 extended:
  ##.adthrive
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19116#issuecomment-1646495575
