### ISSUE TITLE
redecanais.la: breakage

### ISSUE THREAD

**Issue by jubscleyson** [uBlockOrigin/uAssets#19125]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://redecanais.la/a-verdade-da-mentira-uma-nova-missao-1a-temporada-episodio-01-piloto_3ed090137.html`

### Category

breakage

### Description

when I turn on ublock it does not play the videos

### Other extensions used

only the ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4d.13h.20m
Chromium: 114
filterset (summary):
 network: 98539
 cosmetic: 43093
 scriptlet: 18371
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 91-0, never
  easylist: 68576-10, 4m
  easyprivacy: 33339-62, 4m
  plowe-0: 3720-1067, 4m
  spa-1: 5376-68, 4m
  ublock-badware: 7568-142, 4m
  ublock-filters: 34098-249, 4m
  ublock-privacy: 431-4, 4m
  ublock-quick-fixes: 345-184, 4m
  ublock-unbreak: 2086-35, 4m
  urlhaus-1: 6345-0, 3m
filterset (user): [array of 91 redacted]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 489 ms
 maxAssetCacheWait: 191 ms
popupPanel:
 blocked: 17
 network:
  amung.us: 3
  cleverwebserver.com: 1
  disqus.com: 5
  encrypted-encrypted-encrypted-encrypted-encrypted-encrypted.link: 1
  imasdk.googleapis.com: 1
  openwebtorrent.com: 1
  servetraff.com: 1
  viglink.com: 2
  whookroo.com: 2
 extended:
  ##.pm-ads-banner
  ##+js(abort-on-property-read, zfgformats)
  ##.ima-ad-container
```
</details>

**Comment by okiehsch** [comment]
I can't access the site, evene if I try the homepage I get automatically redirected to a dodgy site.

**Comment by okiehsch** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/d5c9ceee-396f-49d7-a948-482c985fa4a4)

**Comment by jubscleyson** [comment]
1
https://redecanais.la
2 
https://redecanais.la/invasao-secreta-dublado-legendado-lista-de-episodios_a36319670.html
3
https://redecanais.la/invasao-secreta-1a-temporada-episodio-01-ressurreicao_ed76f94df.html
![1](https://github.com/uBlockOrigin/uAssets/assets/139658928/ff678e15-b450-4687-a73a-78dacb241252)
![2](https://github.com/uBlockOrigin/uAssets/assets/139658928/67548780-7530-44ab-bbb2-0e5ee56773a5)
![3](https://github.com/uBlockOrigin/uAssets/assets/139658928/a71009c2-164f-450b-afb0-ab19dca9e0c0)

**Comment by stephenhawk8054** [comment]
@jubscleyson Did you access those sites by clicking on any links or you enter the URL to URL bar to access?

**Comment by okiehsch** [comment]
Well, I still get automatically redirected to a malware site and if I try to check the sites availibilty online I still get the request denied message.
Probably geo specific, which means that the site deliberrately redirects users from some locations to badware sites!
Which is even worse imo.

**Comment by jubscleyson** [comment]
https://www.google.com/search?q=rede+canais&sxsrf=AB5stBj9_3uiwqMJayujTxwi5mJeNZfkRg%3A1690047529237&source=hp&ei=KRS8ZKG9DNrT1sQPwaqZuAw&iflsig=AD69kcEAAAAAZLwiOXKlSRZuervS7xHC_EuWxY17PkEp&ved=0ahUKEwjh9YbV7aKAAxXaqZUCHUFVBscQ4dUDCAk&uact=5&oq=rede+canais&gs_lp=Egdnd3Mtd2l6IgtyZWRlIGNhbmFpc0jvLFCpBljvInABeACQAQCYAagBoAHVCqoBBDAuMTG4AQPIAQD4AQGoAgLCAgcQIxjqAhgnwgILEC4YgAQYsQMYgwHCAgsQABiABBixAxiDAcICCBAuGIAEGLEDwgIOEC4YgAQYsQMYxwEY0QPCAgUQABiABMICCxAuGIoFGLEDGIMBwgIIEAAYgAQYsQPCAgsQLhiABBjHARjRA8ICCBAAGIoFGLEDwgIREC4YgAQYsQMYgwEYxwEY0QPCAgsQABiABBixAxjJA8ICCBAAGIoFGJIDwgIKEAAYgAQYyQMYCsICCxAAGIoFGLEDGIMBwgILEC4YgAQYxwEYrwE&sclient=gws-wiz
click on the link will go to the google search and then click on the first
link in the search

Em sáb., 22 de jul. de 2023 às 14:03, okiehsch ***@***.***>
escreveu:

**Comment by jubscleyson** [comment]
only from Brazil try testing with a vpn

Em sáb., 22 de jul. de 2023 às 14:40, Jubs Cleyson ***@***.***>
escreveu:

**Comment by ghajini** [comment]
no brazilian vpn usefull
when you on site, click ctrl+U ,select all then copy that `pastebin.com`, share that here link
or tell us good vpn usefull

**Comment by jubscleyson** [comment]
I don't use vpn I'm saying that I live in Brazil

**Comment by jubscleyson** [comment]
I would like to send a video of what I'm talking about

**Comment by jubscleyson** [comment]
Desktop 2023.07.22 - 20.16.31.05.mp4
<https://drive.google.com/file/d/1kyzWnMDf3UcA88264iqoRMIj2O4Y_RAK/view?usp=drive_web>


Em sáb., 22 de jul. de 2023 às 16:58, ghajini ***@***.***>
escreveu:

**Comment by stephenhawk8054** [comment]
@jubscleyson This is what appears for us when using VPN to Brazil and access the above site (video recording): 

https://github.com/uBlockOrigin/uAssets/assets/66517106/4b06a871-822e-4c49-9809-dcffc9d725db

As you can see, it redirects to a malware site. So we cannot investigate any more.

**Comment by jubscleyson** [comment]
thank you for at least trying thank you very much, and if you are the ones who will make the uBlock Origin, you will send it very well, I loved it 100 out of 100

**Comment by ghajini** [comment]
i didn't see breakages ,but i do see popups ,update filters
