### ISSUE TITLE
waterfall.money: detection

### ISSUE THREAD

**Issue by monkeyde98** [uBlockOrigin/uAssets#19124]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://waterfall.money/`

### Category

detection

### Description

as soon as I enter the chrome browser opens the dialog!

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 114
filterset (summary):
 network: 98703
 cosmetic: 26346
 scriptlet: 18829
 html: 0
listset (total-discarded, last-updated):
 added:
  spa-1: 5377-139, 2m
 default:
  user-filters: 1007-187, never
  easylist: 68521-16495, 2m
  easyprivacy: 33336-64, 2m
  plowe-0: 3720-1068, 2m
  ublock-badware: 7568-142, 2m
  ublock-filters: 34098-462, 2m
  ublock-privacy: 433-5, 2m
  ublock-quick-fixes: 325-187, 2m
  ublock-unbreak: 2086-36, 2m
  urlhaus-1: 6345-0, 2m
filterset (user): [array of 1069 redacted]
trustedset:
 added: [array of 31 redacted]
switchRuleset:
 added: [array of 7 redacted]
hostRuleset:
 added: [array of 187 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 23906 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##+js(remove-attr, disabled, input)
  ##+js(abort-current-script, eval, decodeURIComponent)
  ##+js(set-constant, blurred, false)
  ##+js(no-xhr-if, czilladx)
```
</details>

**Comment by grassfedtallow** [comment]
`https://waterfall.money/login` => `waterfall.money##+js(aeld, load, ads)`
