### ISSUE TITLE
medium.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#19120]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://medium.com/teamresellerclub/how-to-protect-your-vps-hosted-website-from-ddos-threats-119e121b430b`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/3aa87ac1-f324-48d9-8689-b02bedc0bdab)

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 35d.50m
Chromium: 114
filterset (summary):
 network: 128948
 cosmetic: 142368
 scriptlet: 26458
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 9882-4, 22h.35m
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 524-4, 1d.22h.38m
  DEU-0: 6962-0, 22h.37m
  IDN-0: 9560-368, 1d.22h.39m
  RUS-0: 39622-50, 1d.22h.39m
  ara-0: 2321-6, 22h.36m
  easylist-annoyances: 3895-47, 1d.22h.38m
  easylist-chat: 130-0, 1d.22h.38m
  easylist-notifications: 2633-102, 1d.22h.38m
  fanboy-cookiemonster: 47750-230, 1d.22h.38m
  fanboy-social: 16106-10, 1d.22h.38m
  ublock-annoyances: 5293-80, 1d.22h.38m
 default:
  user-filters: 8-0, never
  easylist: 68304-62, 1d.22h.38m
  easyprivacy: 33339-244, 1d.22h.38m
  plowe-0: 3723-1075, 1d.22h.38m
  ublock-badware: 7560-144, 1d.22h.38m
  ublock-filters: 33904-354, 1d.22h.38m
  ublock-privacy: 429-7, 1d.22h.38m
  ublock-quick-fixes: 321-25, 25m
  ublock-unbreak: 2085-41, 1d.22h.38m
  urlhaus-1: 6440-0, 22h.34m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 2111 ms (selfie)
 maxAssetCacheWait: 564 ms
popupPanel:
 blocked: 12
 network:
  medium.com: 6
  cloudflareinsights.com: 1
  datadoghq.com: 1
  google.com: 2
  googletagmanager.com: 1
  youtube.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@gorhill This banner can be hidden by setting local storage item to `"2023-07-22T08:10:04.697Z"`. Could there be any ways to convert `$currentDate$` to this format?

**Comment by gorhill** [comment]
I will add `$currentISODate$`.

**Comment by stephenhawk8054** [comment]
@gorhill Looks like the site needs to put the date inside `""`. Is it possible to put date values (`$now$`, `$currentDate$`, `$currentISODate$`) inside `""`?

If it complicates the code, then I think it's fine.

**Comment by gorhill** [comment]
> Is it possible to put date values (`$now$`, `$currentDate$`, `$currentISODate$`) inside quotations?

Doing this potentially breaks other cases using these variables, i.e. other sites may not expect quotes. The reason this site might need quotes is because it's serializing through JSON, so a better solution would be to maybe offer a serialization type using optional extra parameters:

    edium.com##+js(trusted-set-local-storage-item, 'lo-non-moc-membership-upsell|dismissed-at', 2023-07-20T00:00:00.000Z, serialize, json)

**Comment by stephenhawk8054** [comment]
I see. That's indeed a better approach.

**Comment by stephenhawk8054** [comment]
I didn't realize the same issue was declined already: https://github.com/uBlockOrigin/uAssets/issues/18854 and it's indeed self-promotion so I'm gonna remove the filters
