### ISSUE TITLE
[nsfw] gplinks.co: detection

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#19122]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gplinks.co/N2WNTsF/?vid=176783011`

### Category

detection

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/98657967/27efd720-c904-4bb8-9c3f-6dae613a3c47)

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 17d.8h.40m
Chromium: 115
filterset (summary):
 network: 105177
 cosmetic: 122019
 scriptlet: 25170
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 9811-4, 9m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 9m
  IDN-0: 9589-370, 9m
  easylist-annoyances: 3871-34, 10m
  easylist-chat: 130-0, 9m
  easylist-newsletters: 6287-15, 9m
  easylist-notifications: 2633-78, 9m
  fanboy-cookiemonster: 47752-222, 9m
  fanboy-social: 16106-12, 9m
  ublock-annoyances: 5300-84, 9m
 default:
  user-filters: 10-0, never
  easylist: 68018-26, 5d
  easyprivacy: 33339-151, 10m
  ublock-badware: 7571-142, 5d
  ublock-filters: 33893-307, 5d
  ublock-privacy: 431-5, 10m
  ublock-quick-fixes: 321-25, 9m
  ublock-unbreak: 2077-39, 5d
  urlhaus-1: 6303-0, 9m
filterset (user): [array of 10 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1504 ms (selfie)
 maxAssetCacheWait: 443 ms
popupPanel:
 blocked: 10
 network:
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 2
  nannieslamaic.com: 1
  tawk.to: 1
  themesinfo.com: 1
  trustpilot.com: 1
  unpkg.com: 1
 extended:
  ##.social.nav
  ##.trustpilot-widget
  ##+js(addEventListener-defuser, contextmenu)
  ##+js(abort-on-property-read, app_vars.force_disable_adblock)
  ##+js(disable-newtab-links)
  ##+js(no-setInterval-if, href)
  ##+js(set-constant, blurred, false)
  ##+js(abort-on-property-read, clickCount)
  ##+js(abort-current-script, String.fromCharCode, /btoa|break/)
```
</details>

**Comment by okiehsch** [comment]
Already fixed. https://github.com/uBlockOrigin/uAssets/commit/0790460e00ecde596bcc33d551e53e8d9ac9ac69
Update your `uBO-filters` list.
