### ISSUE TITLE
katmoviehd.ma: ads

### ISSUE THREAD

**Issue by adsdestroyer** [uBlockOrigin/uAssets#19133]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://katmoviehd.ma/oppenheimer-2023-hindi/`

### Category

ads

### Description

inplayer skipable ads are playing before movie starts. check screenshot below

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1042" alt="Screenshot 2023-07-23 at 11 12 55 AM" src="https://github.com/uBlockOrigin/uAssets/assets/109018577/43c94c9f-745d-4dca-bab1-ac509c32ce4d">

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 39d.20h.51m
Firefox: 115
filterset (summary):
 network: 96642
 cosmetic: 39402
 scriptlet: 17968
 html: 1002
listset (total-discarded, last-updated):
 default:
  user-filters: 12-3, never
  ublock-filters: 34767-68, 3d.16h.38m
  ublock-badware: 7562-1, 3d.16h.37m
  ublock-privacy: 468-0, 3d.16h.36m
  ublock-unbreak: 2134-2, 3d.16h.35m
  ublock-quick-fixes: 322-0, 25m
  easylist: 67986-707, 3d.16h.33m
  easyprivacy: 33349-719, 3d.16h.32m
  urlhaus-1: 6345-0, 13h.27m
  plowe-0: 3723-2, 3d.16h.30m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 169 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1826 ms
 maxAssetCacheWait: 460 ms
popupPanel:
 blocked: 9
 network:
  ads2550.bid: 2
  aj1907.online: 3
  google-analytics.com: 2
  googletagmanager.com: 2
 extended:
  ###sidebar > #custom_html-6
  ##+js(abort-current-script, Math.imul)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||ssindserving.com^
```

@ryanbr
