### ISSUE TITLE
ublar.katerionews.com: detection

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [uBlockOrigin/uAssets#19134]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ublar.katerionews.com/hot-news/?data=def50200600fd898968bb56425d8b1b1b1b53feae4549f0db2d5358f24425b371c7f04065017a9e440ea625d0dcb49bdef4ecf92e9ae6f1c9d9cf27e63cf97b268c0450b2261acd09a46072c065443a099b8d9eadd30ce046fb2de9ff7ddf7aa46bc0c83b9630ab469298b87171b5bc9c9ff6ea297e5c83db7405861ee6e727a11c4456a2e2ec1d192eea5d5de5c21668a435730008d6b004169f710e1415a80a41ccc64fa17578917706a3568a30d243931fe3588b4315297e26d8a63515264c978232fa385f361fc53281081707b0b2cfcdbeca1181236665933c3f0cbd070c9b8c54786fee26d9b72fb9c5074433457bd73f196e1f6275a179b5935f3e52dc377523dcadca6268816919944f9f522c26ea5310495416f41188e08342d08574e9118198ecbd214ded452101aacbf10762611c6e09adebaff39d7cbdd186a8b8ddf9967fbebbb705b663b32d8c9731e7b53fa154b4f76eaa6d668947e6ebb94b52f07b4a5a8359f9bd15c18d5c71125679ea593e2c3fe9e5e26fe45ed52ef16105a869c1f20f57a6058b5dc216187b18d0823728b6fa39009dd1cf7e87c598561e5fee6`

### Category

detection

### Description

"Please disable AdBlock."

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 97417
 cosmetic: 39828
 scriptlet: 18210
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  CZE-0: 745-1, now
  easylist: 68670-11, now
  easyprivacy: 33341-67, now
  plowe-0: 3720-1071, now
  ublock-badware: 7568-142, now
  ublock-filters: 34097-220, now
  ublock-privacy: 431-5, now
  ublock-quick-fixes: 321-183, now
  ublock-unbreak: 2086-34, now
  urlhaus-1: 6360-0, now
filterset (user): [empty]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2181 ms (selfie)
 maxAssetCacheWait: 158 ms
popupPanel: 
 blocked: 9
 network: 
  aaa111.site: 1
  adipolosolutions.com: 1
  googletagmanager.com: 1
  greeter.me: 3
  marazma.com: 1
  testingmetriksbre.ru: 1
  vdo.ai: 1
 cosmetic: 
  ##.aplvideo
  ##.aplvideo
  ##.ad-1
  ##[id^=\"div-gpt-ad\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  ##div[id^=\"div-gpt-\"]:not([style^=\"width: 1px; height: 1px; position: absolute; left: -10000px; top: -\"])
  #@#[id^=\"div-gpt-ad\"]
  #@#div[id^=\"div-gpt-\"]
  #@#[id^=\"etarget\"]
```
</details>

**Comment by stephenhawk8054** [comment]
Where do you get this link from?

**Comment by ghajini** [comment]
i get one at `https://1.multiup.us/f/HlreeNziIhOX` ,it always says vpn detected even no vpn used

`||katerionews.com/hot-news/addon.php$frame,1p`

**Comment by Sh3r1ffCZ** [comment]
There if you want to watch
"https://4.sledujserialy.io/episode/boys-the-s01e01"

**Comment by ghajini** [comment]
> There if you want to watch `https://4.sledujserialy.io/episode/boys-the-s01e01`

where to click?

meanwhile add `||katerionews.com/hot-news/addon.php$frame,1p` in my filters ,now do you get antiadblock /play the video

**Comment by stephenhawk8054** [comment]
I can access via `https://1.multiup.us/f/HlreeNziIhOX`; ` https://4.sledujserialy.io/episode/boys-the-s01e01` does not let me access.

These filters work for me

```adb
||katerionews.com/hot-news/addon.php$frame,1p
katerionews.com##div[style] > iframe[src^="/hot-news/addon.php"]:upward(1)
```
