### ISSUE TITLE
animesgratis.org: popups

### ISSUE THREAD

**Issue by Theluga** [uBlockOrigin/uAssets#19136]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animesgratis.org/episodio/liar-liar-episodio-2/`

### Category

popups

### Description

when clicking in the player, new tab with blocked content opens.

### Other extensions used

Decentraleyes, gnome shell extension, open subtitles, cleanurl, disable page visibility api, netflix 1080p.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 33d.13h.20m
Firefox: 115
filterset (summary):
 network: 99210
 cosmetic: 84165
 scriptlet: 23542
 html: 1184
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 47748-264, 2d.16h.46m
  ublock-annoyances: 5253-7, 2d.16h.46m
 default:
  user-filters: 35-0, never
  ublock-filters: 34778-65, 2d.16h.45m
  ublock-badware: 7562-2, 2d.16h.45m
  ublock-privacy: 468-0, 2d.16h.46m
  ublock-unbreak: 2134-2, 2d.16h.45m
  ublock-quick-fixes: 223-0, 38m
  easylist: 68385-718, 2d.16h.45m
  easyprivacy: 33351-727, 2d.16h.46m
  urlhaus-1: 6363-0, 38m
  plowe-0: 3740-1, 10d.54m
filterset (user): [array of 35 redacted]
trustedset:
 added: [array of 18 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 152 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 666 ms (selfie)
 maxAssetCacheWait: 328 ms
popupPanel:
 blocked: 8
 no-popups: true
 network:
  disqus.com: 4
  viglink.com: 2
  waust.at: 2
```
</details>

**Comment by huyszn** [comment]
`animesgratis.org` redirects to `animesonline.nz/mudanca/` and it detects uBO. The detection is fixed in AdGuard Portuguese list https://github.com/AdguardTeam/AdguardFilters/issues/159624

**Comment by JobcenterTycoon** [comment]
When a regional site with a anti adblock is fixed in the regional list its fine.
