### ISSUE TITLE
tirto.id: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#19149]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tirto.id/`

### Category

privacy

### Description

The domain `aurum.tirto.id` is used to perform ad reinsertion and load pixel tracker into the desktop and mobile version of the site.

The domain `trk.tirto.id` is used to load impression script and act as an endpoint for page impression beacons on their mobile site. At the very least, they log an encoded form of the current location window and the view time in unix epoch, assuming I'm not mistaken.

Some screenshots are attached below.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![tirto-desktop](https://github.com/uBlockOrigin/uAssets/assets/115052854/fc61d414-594b-4ec6-9754-125ce3c7f5e8)

![tirto-mobile](https://github.com/uBlockOrigin/uAssets/assets/115052854/f96d009f-f68e-49b6-9596-15623501beb9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1b1
Firefox: 115
filterset (summary):
 network: 106060
 cosmetic: 114237
 scriptlet: 20420
 html: 1005
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 3870-48, now
  easylist-chat: 130-0, now
  fanboy-cookiemonster: 47765-229, now
  easylist-newsletters: 6296-21, now
  easylist-notifications: 2633-160, now
  fanboy-social: 16107-13, now
  IDN-0: 9598-34, now
 default:
  user-filters: 2-0, never
  ublock-filters: 34976-41, now
  ublock-badware: 7573-1, now
  ublock-privacy: 475-0, now
  ublock-unbreak: 2139-1, now
  ublock-quick-fixes: 232-68, now
  easylist: 68853-343, now
  easyprivacy: 33344-86, now
  urlhaus-1: 6279-0, now
  plowe-0: 3720-1073, now
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 720 ms
 maxAssetCacheWait: 502 ms
popupPanel:
 blocked: 7
 network:
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
  scorecardresearch.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
