### ISSUE TITLE
geeksforgeeks.org: detection

### ISSUE THREAD

**Issue by asdf23** [uBlockOrigin/uAssets#19142]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.geeksforgeeks.org/how-to-create-an-array-containing-1-n-numbers-in-javascript/`

### Category

detection

### Description

ad blocker is detected nag screen appears

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 7d.4h.27m
Firefox: 114
filterset (summary):
 network: 97300
 cosmetic: 39473
 scriptlet: 18017
 html: 1007
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34961-105, now
  ublock-badware: 7573-2, now
  ublock-privacy: 472-0, 5m
  ublock-unbreak: 2137-0, now
  ublock-quick-fixes: 232-0, 5m
  easylist: 68757-779, 5m
  easyprivacy: 33341-721, 5m
  urlhaus-1: 6363-0, 5m
  plowe-0: 3720-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 174 ms (selfie)
 maxAssetCacheWait: 65 ms
popupPanel:
 blocked: 14
 network:
  geeksforgeeks.org: 4
  6sc.co: 1
  go-mpulse.net: 1
  google.com: 3
  googleoptimize.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  googletagservices.com: 1
 extended:
  ###text-15
  ###text-16
  ##div[id^="GFG_AD_"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable "ublock filters - annoyances" list and test again?

**Comment by JohnyP36** [comment]
> Can you enable `ublock filters - annoyances` list and test again?

In that list is the rule `geeksforgeeks.org##+js(abort-current-script, showAdblockerModal)` which still works fine. 
So, if you don't want to enable a whole filter list, just copy the given rule.

**Comment by asdf23** [comment]
Yes this works, sorry to get back to you late.
