### ISSUE TITLE
ddwloclawek.pl: detection

### ISSUE THREAD

**Issue by xparadoxical** [uBlockOrigin/uAssets#19143]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ddwloclawek.pl/pl/11_wiadomosci/58604_pociag-zablokowal-pol-dzielnicy-we-wloclawku-sprawa-juz-glosna-w-polsce-.html`

### Category

detection

### Description

After a moment, all `body` content gets replaced with an unreadable `canvas` and an "adblock detected" message.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 98386
 cosmetic: 46984
 scriptlet: 18242
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 2-0, never
  POL-0: 7964-11, 3h.19m
  POL-2: 1275-13, 1d.4h.47m
  easylist: 68304-34, 3d.5h.22m
  easyprivacy: 33343-62, 6d.43m
  plowe-0: 3740-1084, 11d.5m
  ublock-badware: 7562-142, 2d.6h.14m
  ublock-filters: 34089-184, 2d.6h.13m
  ublock-privacy: 429-4, 7d.1h.9m
  ublock-quick-fixes: 222-45, 10h.26m
  ublock-unbreak: 2086-35, 2d.6h.12m
  urlhaus-1: 6363-0, 1h.18m
filterset (user): [array of 2 redacted]
trustedset: 
 added: [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 2210 ms (selfie)
 maxAssetCacheWait: 449 ms
popupPanel: 
 blocked: 10
 network: 
  ddwloclawek.pl: 6
  doubleclick.net: 1
  googletagmanager.com: 1
  optad360.io: 1
  qwtag.com: 1
```
</details>

**Comment by ghajini** [comment]
@krystian3w @MajkiIT

**Comment by krystian3w** [comment]
Maybe similar:

```adb
https://iszczecinek.pl/pl/696_o-tym-sie-mowi/32970_zaostrzenie-przepisow-dot-handlu-w-niedziele-co-zmieni-sie-od-1-sierpnia.html
```

**Comment by krystian3w** [comment]
Fyi @olegwukr

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25686

**Comment by stephenhawk8054** [comment]
This works for me

```adb
/banery_foto/*$image,1p,redirect=1x1.gif,domain=ddtorun.pl|ddwloclawek.pl|faktypilskie.pl|ki24.info|koronowo.net.pl|portalplock.pl|zyciesiedleckie.pl
```

cc @MajkiIT Sorry, can you check this?
