### ISSUE TITLE
discord.com: nuisance 

### ISSUE THREAD

**Issue by bizso09** [uBlockOrigin/uAssets#19141]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://discord.com/channels/847767926286319646/854065998088634378`

### Category

nuisance

### Description

I appply the following custom filters, yet the banner asset in the top left corner is not blocked in discord channels. All other assets are blocked, but not the banner, even though it should be matched by the filters.

||cdn.discordapp.com/
||cdn.discordapp.com/banners/$image
||cdn.discordapp.com/banners/847767926286319646/5855851e586d15bb8e737076dfecdc10.webp$image

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-07-24 010704](https://github.com/uBlockOrigin/uAssets/assets/1904536/6d67bfb5-865f-49bb-bcfa-5c8e2ca9c65a)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 38d.17h.6m
Firefox: 115
filterset (summary):
 network: 96807
 cosmetic: 39465
 scriptlet: 17976
 html: 1002
listset (total-discarded, last-updated):
 default:
  user-filters: 74-5, never
  ublock-filters: 34931-82, never
  ublock-badware: 7562-2, never
  ublock-privacy: 468-0, never
  ublock-unbreak: 2134-2, never
  easylist: 68110-704, never
  easyprivacy: 33336-721, never
  urlhaus-1: 6360-0, never
  plowe-0: 3720-1, never
  ublock-quick-fixes: 223-0, never
filterset (user): [array of 74 redacted]
trustedset:
 added: [array of 62 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 hyperlinkAuditingDisabled: false
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7336 ms (selfie)
 maxAssetCacheWait: 580 ms
popupPanel:
 blocked: 6
 network:
  discordapp.net: 6
```
</details>

**Comment by stephenhawk8054** [comment]
Are you sure it's not cache? Can you refresh while bypassing the cache and test again?
