### ISSUE TITLE
northerntool.com: breakage

### ISSUE THREAD

**Issue by bottleblue** [uBlockOrigin/uAssets#19144]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.northerntool.com/products/red-mountain-valley-patio-mat-6ft-x-9ft-palm-leaf-pattern-model-2a-pm013-104586`

### Category

breakage

### Description

Page won't load when ublock is enabled. Disabling ublock fixes it

### Other extensions used

Imagus Mod
Context search
Violent Monkey
Stylus
Decentraleyes
FrankerFaceZ
scrollanywhere
zoompageWE

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 40d.23h.23m
Firefox: 114
filterset (summary):
 network: 142058
 cosmetic: 48482
 scriptlet: 22105
 html: 1190
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-spyware-url: 1138-5, now
  block-lan: 48-0, now
  fanboy-thirdparty_social: 69-0, now
  ublock-annoyances: 5265-7, now
  adguard-spyware: 62918-16965, now
  adguard-mobile-app-banners: 4441-9, now
  easylist-annoyances: 3871-42, now
 default:
  user-filters: 15-0, never
  ublock-filters: 34961-153, now
  ublock-badware: 7573-1, now
  ublock-privacy: 472-0, now
  ublock-unbreak: 2137-1, now
  easylist: 68757-457, now
  easyprivacy: 33341-38, now
  urlhaus-1: 6363-0, now
  ublock-quick-fixes: 232-0, 1h.22m
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 138 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 6614 ms (selfie)
 maxAssetCacheWait: 3910 ms
 unsuspendAfter: 2191 ms
popupPanel:
 blocked: 15
 network:
  bazaarvoice.com: 1
  bc0a.com: 2
  bing.com: 1
  criteo.net: 1
  d35u1vg1q28b3w.cloudfront.net: 1
  forter.com: 3
  google-analytics.com: 1
  google.com: 1
  luckyorange.com: 1
  visitors.live: 2
  yottaa.net: 1
 extended:
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by ghajini** [comment]
Caused by one of your nondefault list **AdGuard Tracking Protection**
`||qoe-*.yottaa.net/*/configure.rapid.js`
report here `https://github.com/AdguardTeam/AdguardFilters/issues`

**Comment by bottleblue** [comment]
> Caused by one of your nondefault list **AdGuard Tracking Protection** `||qoe-*.yottaa.net/*/configure.rapid.js` report here `https://github.com/AdguardTeam/AdguardFilters/issues`

How is it a nondefault list? It was included in the Filters List by default.

**Comment by bottleblue** [comment]
> > * [x]  I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
> 
> You enabled it as an external filter list.

I'm sry I misunderstood it. I thought an external filter list was one that you imported into Ublock. I didn't know the Adguard, Easy Privacy, Fanboy, etc. lists that were there by default were considered external.
