### ISSUE TITLE
aitextpromptgenerator.com: ads

### ISSUE THREAD

**Issue by JetVarimax** [uBlockOrigin/uAssets#19155]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aitextpromptgenerator.com/`

### Category

ads

### Description

Not sure if this really counts as they are ads from the website operator itself.

### Other extensions used

SponsorBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 41d.46m
Chromium: 114
filterset (summary):
 network: 117396
 cosmetic: 175145
 scriptlet: 26709
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69395-101, now
  adguard-social: 20959-893, now
  dpollock-0: 11537-1, now
  fanboy-cookiemonster: 47765-3800, now
  fanboy-social: 16107-688, now
  fanboy-thirdparty_social: 68-18, now
  ublock-annoyances: 5305-217, now
 default:
  user-filters: 4-0, never
  easylist: 68946-307, now
  easyprivacy: 33350-221, now
  plowe-0: 3720-1446, now
  ublock-badware: 7571-143, now
  ublock-filters: 34107-605, now
  ublock-privacy: 440-6, now
  ublock-quick-fixes: 226-55, 12m
  ublock-unbreak: 2088-36, now
  urlhaus-1: 6349-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 340 ms (selfie)
 maxAssetCacheWait: 195 ms
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  youtube.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by ghajini** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
For the top banner:

```adb
aitextpromptgenerator.com##a[href*="getsitepop.com"]
```

The ones on the side are self-promotion, so it depends on EasyList's decision.
