### ISSUE TITLE
downloaddevtools.com: ads

### ISSUE THREAD

**Issue by 365360171** [uBlockOrigin/uAssets#19163]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://downloaddevtools.com/en/product/1816/free-download-sisulizer-enterprise-edition`

### Category

ads

### Description

There are ads in the lower left corner.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 102
filterset (summary):
 network: 111536
 cosmetic: 49750
 scriptlet: 18234
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CHN-0: 24712-128, now
  easylist: 68969-65, now
  easyprivacy: 33351-77, now
  plowe-0: 3720-1073, now
  ublock-badware: 7557-142, now
  ublock-filters: 34111-233, now
  ublock-privacy: 442-5, now
  ublock-quick-fixes: 321-192, 7m
  ublock-unbreak: 2088-35, now
  urlhaus-1: 6349-0, now
filterset (user): [empty]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1476 ms (selfie)
 maxAssetCacheWait: 298 ms
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
It's self-promotion. You can use this as a custom filter:

```adb
downloaddevtools.com##.alert-warning
```
