### ISSUE TITLE
wikihow.com: breakage

### ISSUE THREAD

**Issue by YourOrdinaryCat** [uBlockOrigin/uAssets#19168]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wikihow.com/What-Is-My-Aesthetic-Quiz`

### Category

breakage

### Description

Some wikiHow quizzes, despite being possible to start, do not work properly. This is due to the next button - used to go to the next question in the quiz - causing an uncaught `TypeError` within `function aa(a)` when trying to access `u[b]` (obfuscated code from the page), which presumably updates the page's advertisements:

```JavaScript
for(var b=a.adTargetId,c=u[b].getAdUnitPath(),f=u[b].getSizes(),e=[],d=0;d<f.length;d++)
```

```
Uncaught TypeError: u[b] is undefined
    aa https://www.wikihow.com/What-Is-My-Aesthetic-Quiz:232
    refresh https://www.wikihow.com/What-Is-My-Aesthetic-Quiz:245
    Ia https://www.wikihow.com/What-Is-My-Aesthetic-Quiz:258
    jQuery 4
        nextSlide
        addHandlers
        dispatch
        handle
```

This doesn't just affect the "What Is My Aesthetic?" quiz - many of the quizzes within https://www.wikihow.com/Quizzes are affected as well. However, not every quiz is affected - I found the ["Which Diet Is Right for Me?" quiz](https://www.wikihow.com/Which-diet-is-right-for-me-quiz), where the next button works correctly and you can complete it without hiccups.

Tested on Windows 10 21H2 with Microsoft Edge 115.0.1901.183 and Mozilla Firefox 115.0.2 (downloaded from the Microsoft Store).

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 97553
 cosmetic: 39528
 scriptlet: 18057
 html: 1006
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34986-41, now
  ublock-badware: 7528-2, now
  ublock-privacy: 479-0, 1h.42m
  ublock-unbreak: 2144-1, now
  ublock-quick-fixes: 253-50, 1h.42m
  easylist: 69100-780, now
  easyprivacy: 33352-722, now
  urlhaus-1: 6330-0, 1h.42m
  plowe-0: 3720-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4367 ms
 maxAssetCacheWait: 2832 ms
popupPanel:
 blocked: 14
 network:
  wikihow.com: 6
  amazon-adsystem.com: 1
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  videoplayerhub.com: 1
 extended:
  ##.wh_ad_inner
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
wikihow.com##+js(set, Object.prototype.getTargetingMap, noopFunc)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by YourOrdinaryCat** [comment]
> wikihow.com##+js(set, Object.prototype.getTargetingMap, noopFunc)

Doesn't make a difference on my end - for what it's worth, the Edge dev tools seem to give more verbose output. This is with the above filter applied:

```JavaScript
Uncaught TypeError: u[b].getSizes is not a function
    at aa (What-Is-My-Aesthetic-Quiz:232:108)
    at service.slot.refresh (What-Is-My-Aesthetic-Quiz:245:617)
    at Object.Ia [as refreshQuizAds] (What-Is-My-Aesthetic-Quiz:258:766)
    at Object.nextSlide (<anonymous>:355:979)
    at HTMLButtonElement.<anonymous> (<anonymous>:351:558)
    at HTMLDocument.dispatch (load.php?debug=false&lang=en&modules=jquery&siterev=sOn7V&skin=wh&version=00rdyep:69:95)
    at elemData.handle (load.php?debug=false&lang=en&modules=jquery&siterev=sOn7V&skin=wh&version=00rdyep:65:775)
aa @ What-Is-My-Aesthetic-Quiz:232
service.slot.refresh @ What-Is-My-Aesthetic-Quiz:245
Ia @ What-Is-My-Aesthetic-Quiz:258
nextSlide @ VM63:355
(anonymous) @ VM63:351
dispatch @ load.php?debug=false&lang=en&modules=jquery&siterev=sOn7V&skin=wh&version=00rdyep:69
elemData.handle @ load.php?debug=false&lang=en&modules=jquery&siterev=sOn7V&skin=wh&version=00rdyep:65
```

**Comment by stephenhawk8054** [comment]
Even when I don't use any extensions on Microsoft Edge, I cannot click the button to continue either: https://github.com/uBlockOrigin/uAssets/assets/66517106/30be744f-ef2b-4589-a5fc-b0fe9818a8e3

**Comment by YourOrdinaryCat** [comment]
That's interesting - the next button fails if ads don't load. The diet quiz (the one that doesn't fail) has an ad, but not provided by Google - seems like some sort of wikiHow sponsor. Looking at it from my phone, there are no Google ads on the diet quiz.

![image](https://github.com/uBlockOrigin/uAssets/assets/49221554/f25946d7-ca78-49a5-92d6-883ae3f38c36)

Will check on my PC in a bit, I don't remember if uBlock blocks the diet ad, could be a separate addition.

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
@@||wikihow.com^$ghide
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=www.wikihow.com
@@||securepubads.g.doubleclick.net/pagead/managed/js/gpt/*/pubads_impl.js$script,domain=www.wikihow.com
wikihow.com##ins.adsbygoogle
wikihow.com##.wh_ad_active:style(margin: 0 !important; visibility: collapse !important;)
```

**Comment by YourOrdinaryCat** [comment]
Works great! I was able to finish the quiz, results page shows up correctly after answering every question. I tested a few other quizzes, they seem to work too.

![image](https://github.com/uBlockOrigin/uAssets/assets/49221554/4f983b99-a51d-461a-8fc8-a3b7fa89882b)
