### ISSUE TITLE
southparkstudios.com: detection

### ISSUE THREAD

**Issue by HTM-freedom** [uBlockOrigin/uAssets#19167]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.southparkstudios.com/episodes`

### Category

detection

### Description

The video player for the episodes has recently started to detect ublock. The video does not play until the page is loaded with ublock disabled. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 98976
 cosmetic: 29869
 scriptlet: 18103
 html: 1007
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35285-351, now
  ublock-badware: 7522-2, now
  ublock-privacy: 479-1, 9m
  ublock-unbreak: 2149-1, now
  adguard-mobile: 8366-120, 8m
  easylist: 69100-17298, now
  easyprivacy: 33352-730, now
  urlhaus-1: 6378-0, now
  plowe-0: 3720-1, now
  ublock-quick-fixes: 259-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 235674 ms
 maxAssetCacheWait: 5767 ms
popupPanel:
 blocked: 4
 network:
  imasdk.googleapis.com: 1
  mtvnservices.com: 1
  newrelic.com: 1
  omtrdc.net: 1
```
</details>

**Comment by ghajini** [comment]
does the videos play here?

`https://southpark.cc.com/episodes/ohj8pg/south-park-back-to-the-cold-war-season-25-ep-4`

**Comment by HTM-freedom** [comment]
Yes the video now plays with ublock enabled. Thank you for rapidly fixing
the issue.

**Comment by 71256988** [comment]
Having an identical issue on the southparkstudios.nu domain, likely this is also affecting other regional domains aside from the North American and northern European domains.
