### ISSUE TITLE
account.adobe.com: breakage

### ISSUE THREAD

**Issue by msmolkin** [uBlockOrigin/uAssets#19164]
### Prerequisites

- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://account.adobe.com/?lang=en`

### Category

breakage

### Description

`https://account.adobe.com/?lang=en` does not load.

I tried Windows 11 + Chrome and MacOS 13 + Firefox. Disabling blocking for the site allows the site to load and allows payment to go through. Unsure whether UBO was what caused the problem on the Windows computer, as I never verified it worked on Windows.

Only needed to make one small change: update credit card information.

On Windows: The JS "submit" call to update the card didn't load.
On Mac: the site didn't load at all. Once blocking was disabled, site loaded and payment went through without issues.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 27d.5h.13m
Firefox: 115
filterset (summary):
 network: 97249
 cosmetic: 39465
 scriptlet: 18016
 html: 1008
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34957-105, 3m
  ublock-badware: 7574-1, 3m
  ublock-privacy: 479-0, 3m
  ublock-unbreak: 2139-0, 3m
  ublock-quick-fixes: 232-0, 3m
  easylist: 68694-782, 3m
  easyprivacy: 33351-719, 3m
  urlhaus-1: 6349-0, 3m
  plowe-0: 3723-2, 4d.18h.57m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 565 ms
 maxAssetCacheWait: 213 ms
popupPanel:
 blocked: 20
 network:
  adobe.com: 2
  clicktale.net: 7
  forter.com: 6
  nr-data.net: 4
  omtrdc.net: 1
```
</details>

### Severity

Low

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||adobe.com/newrelic.js$script,redirect-rule=noopjs,1p
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by Wh00T** [comment]
> Can you test this filter?
> 
> ```
> ||adobe.com/newrelic.js$script,redirect-rule=noopjs,1p
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

In my case, your code solved the issue, thanks a lot 👍
