### ISSUE TITLE
iszczecinek.pl: detection

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#19160]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hard anti-adblock modal

### URL(s) where the issue occurs.

`https://iszczecinek.pl/pl/696_o-tym-sie-mowi/32970_zaostrzenie-przepisow-dot-handlu-w-niedziele-co-zmieni-sie-od-1-sierpnia.html`

### Screenshot(s)

<details> <summary> screen </summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/f5c21809-696a-4b2e-a08c-0b5e7883cff4)

</details>

### uBO version

1.51.1b1

### Browser name and version

Firefox 115.0.2

### Settings

- POL-0
- POL-2

### Notes

Rest of family to test in future: 

`https://siecportali.pl/realizacje`

99 of 102: https://pastebin.com/raw/6aRePuCW (Come can be not removed by webmaster from map of "siecportali". Nor could all of them activate a pop-up to scare you into watching ads or they would shut down the blog for good.)

**Comment by ghajini** [comment]
@MajkiIT
For polish list

`/pl/js/detect-adblock/*$script,redirect-rule=noopjs`
