### ISSUE TITLE
intl.startrek.com: breakage

### ISSUE THREAD

**Issue by donnchawp** [uBlockOrigin/uAssets#19169]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://intl.startrek.com/videos/ready-room-strange-new-worlds-quaid-newsome-frakes`

### Category

breakage

### Description

The video that is embedded on this page does not appear when uBO is enabled on this site. When disabled, the video displays.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 42d.2h.23m
Firefox: 115
filterset (summary):
 network: 97263
 cosmetic: 39417
 scriptlet: 17939
 html: 1001
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 34778-52, 4d.6h.15m
  ublock-badware: 7564-1, 4d.6h.14m
  ublock-privacy: 479-0, 13h.58m
  ublock-unbreak: 2135-0, 4d.6h.13m
  ublock-quick-fixes: 236-0, 5h.57m
  easylist: 68694-739, 1d.14h.2m
  easyprivacy: 33338-760, 3d.10h.9m
  urlhaus-1: 6378-0, 18h
  plowe-0: 3723-2, 10d.17h.47m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1081 ms (selfie)
 maxAssetCacheWait: 422 ms
popupPanel:
 blocked: 6
 network:
  confiant-integrations.net: 1
  doubleclick.net: 1
  i-amlg-prod.appspot.com: 1
  imasdk.googleapis.com: 2
  moatads.com: 1
```
</details>

**Comment by donnchawp** [comment]
I updated to uBO 1.51.0 and the video was still blocked.

**Comment by okiehsch** [comment]
Update, the `uBO-unbreak` list, the video should play fine after that.

**Comment by donnchawp** [comment]
Thank you @okiehsch! That worked!
