### ISSUE TITLE
skill4ltu.eu: detection

### ISSUE THREAD

**Issue by seegge** [uBlockOrigin/uAssets#19176]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://skill4ltu.eu/`

### Category

detection

### Description

Gives popup about adblocker detected which cant be bypassed.

### Other extensions used

Sponsorblock & I still dont care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 183405
 cosmetic: 228549
 scriptlet: 41868
 html: 1197
listset (total-discarded, last-updated):
 added:
  adguard-generic: 72874-4434, 3m
  adguard-mobile: 8419-49, 3m
  adguard-spyware-url: 1148-6, 1m
  adguard-spyware: 63179-1353, 1m
  block-lan: 48-0, 1m
  adguard-social: 21011-47, 3m
  adguard-cookies: 26463-45, 3m
  adguard-popup-overlays: 23168-1106, 3m
  adguard-mobile-app-banners: 4449-18, 3m
  adguard-other-annoyances: 13155-464, 3m
  adguard-widgets: 2215-13, 3m
  fanboy-thirdparty_social: 69-3, 3m
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35019-41, 3m
  ublock-badware: 7596-1, 3m
  ublock-privacy: 480-0, 3m
  ublock-unbreak: 2147-1, 3m
  ublock-quick-fixes: 283-86, 3m
  easylist: 69072-1232, 3m
  easyprivacy: 33349-16883, 3m
  urlhaus-1: 6406-0, 3m
  plowe-0: 3720-1570, 3m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2339 ms (selfie)
 maxAssetCacheWait: 479 ms
popupPanel:
 blocked: 6
 network:
  skill4ltu.eu: 4
  cloudflareinsights.com: 1
  googlesyndication.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
`skill4ltu.eu##+js(no-fetch-if, googlesyndication)`
