### ISSUE TITLE
hexupload.net: breakage

### ISSUE THREAD

**Issue by systox** [uBlockOrigin/uAssets#19174]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hexupload.net/65hw3m3lyaf4`

### Category

breakage

### Description

LInk is a sample, do not download.    The green download button at the above URL does nothing. Its supposed to lead to the next page for download. Disabling UB and dodging virus pop-ups the old fashioned way eventually works. 

### Other extensions used

Sponsor block for youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1642" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/50300640/007527e8-cb13-42ae-833b-d11583edc04e">
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 107269
 cosmetic: 165974
 scriptlet: 26859
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69450-102, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92180-21153, now
  fanboy-cookiemonster: 47820-47820, now
  ublock-annoyances: 5294-237, now
 default:
  user-filters: 35-2, never
  easylist: 69072-96, now
  easyprivacy: 33349-268, now
  plowe-0: 3720-1072, now
  ublock-badware: 7594-142, now
  ublock-filters: 34143-606, now
  ublock-privacy: 443-8, now
  ublock-quick-fixes: 277-87, now
  ublock-unbreak: 2100-38, now
  urlhaus-1: 6406-0, now
filterset (user): [array of 35 redacted]
trustedset:
 added: [array of 21 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 633 ms (selfie)
 maxAssetCacheWait: 122 ms
popupPanel:
 blocked: 11
 network:
  akazginhapping.com: 1
  booster-vax.com: 1
  brunchcreatesenses.com: 1
  googletagmanager.com: 2
  histats.com: 1
  push-sdk.com: 1
  spotscenered.info: 1
  tawk.to: 1
  waisheph.com: 2
 extended:
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by ghajini** [comment]
does this work for you
`hexupload.net##+js(acs, $, preventDefault)`

**Comment by pubct** [comment]
Same reakage.
```
uBlock Origin: 1.51.0
Chromium: 114
filterset (summary):
 network: 97663
 cosmetic: 39505
 scriptlet: 18121
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 69092-9, now
  easyprivacy: 33354-62, now
  plowe-0: 3720-1071, now
  ublock-badware: 7586-142, now
  ublock-filters: 34151-219, now
  ublock-privacy: 443-7, now
  ublock-quick-fixes: 270-87, now
  ublock-unbreak: 2100-34, now
  urlhaus-1: 6353-0, now
filterset (user): [array of 143 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8727 ms (selfie)
 maxAssetCacheWait: 1206 ms
popupPanel:
 blocked: 7
 network:
  akazginhapping.com: 1
  brunchcreatesenses.com: 1
  googletagmanager.com: 2
  histats.com: 1
  push-sdk.com: 1
  tawk.to: 1
 extended:
  ##+js(abort-current-script, $, preventDefault)
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(addEventListener-defuser, , break;case $.)
```

**Comment by ghajini** [comment]
provide the link where it occurs

**Comment by okiehsch** [comment]
I can reproduce.
It's caused by `hexupload.net##+js(acs, $, preventDefault)`
If I overwrite that filter the download works fine on my end.
The filter was added to fix the issue by the OP but I can't reproduce that original issue.

**Comment by ghajini** [comment]
yeah i don't reproduce previous issue now but i see sometimes popups on mobile

`hexupload.net##+js(acs, document.createElement, rAb)`

**Comment by okiehsch** [comment]
I can't test on mobile, if it works for you add it, it does not break anything on my end.

**Comment by ghajini** [comment]
i added for mobile https://github.com/uBlockOrigin/uAssets/commit/3df9d280443cc24556637504f5b582ecd9677954
the website is weired
