### ISSUE TITLE
megaup.net: detection

### ISSUE THREAD

**Issue by vikkatsu** [uBlockOrigin/uAssets#19188]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/`

### Category

detection

### Description

The website detects uBlock origin and blocks access to downloads until it's disabled

### Other extensions used

Violentmonkey
Tree Style Tab
Simple Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 97671
 cosmetic: 39505
 scriptlet: 18074
 html: 1006
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35026-127, 2m
  ublock-badware: 7588-1, 2m
  ublock-privacy: 480-0, 2m
  ublock-unbreak: 2147-1, 2m
  ublock-quick-fixes: 282-0, 2m
  easylist: 69092-781, 2m
  easyprivacy: 33354-723, 2m
  urlhaus-1: 6353-0, 2m
  plowe-0: 3720-2, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 237 ms (selfie)
 maxAssetCacheWait: 117 ms
popupPanel:
 blocked: 12
 network:
  megaup.net: 2
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 2
  dmmzkfd82wayn.cloudfront.net: 3
  googletagmanager.com: 1
  keydawnawe.com: 1
  s3.amazonaws.com: 1
 extended:
  ##body .metaRedirectWrapperBottomAds:style(width: 12006px !impor…
  ##body:style(overflow-x: hidden !important;)
  ##+js(replace-node-text, script, /;\$.*:\(/, ;()
  ##+js(abort-current-script, Math, break;case $.)
```
</details>

**Comment by JobcenterTycoon** [comment]
@stephenhawk8054

**Comment by okiehsch** [comment]
Is my filter not working for you?

**Comment by vikkatsu** [comment]
It's working again now.

**Comment by JobcenterTycoon** [comment]
It working fine.

**Comment by pubct** [comment]
Detection
```
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 98032
 cosmetic: 39630
 scriptlet: 18206
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 69777-10, now
  easyprivacy: 33265-64, now
  plowe-0: 3715-1068, now
  ublock-badware: 7675-146, now
  ublock-filters: 34187-177, now
  ublock-privacy: 446-6, now
  ublock-quick-fixes: 271-27, now
  ublock-unbreak: 2105-33, now
  urlhaus-1: 6108-0, now
filterset (user): [array of 143 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 502 ms
 maxAssetCacheWait: 225 ms
popupPanel:
 blocked: 10
 network:
  megaup.net: 2
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 1
  dmmzkfd82wayn.cloudfront.net: 2
  googletagmanager.com: 1
  keydawnawe.com: 1
  s3.amazonaws.com: 1
 extended:
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(replace-node-text, script, /;}\$\S+?:/, ;})
```
