### ISSUE TITLE
softwarekeep.com: nuisance

### ISSUE THREAD

**Issue by SpectreKelevra** [uBlockOrigin/uAssets#19183]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://softwarekeep.com/help-center/slow-internet-on-windows-10`

### Category

ads

### Description

Ad still visible

### Other extensions used

decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
AdNauseam: 3.17.0
Firefox: 115
filterset (summary): 
  network: 88244
  cosmetic: 40057
  scriptlet: 18052
  html: 1008
listset (total-discarded, last-updated): 
  default: 
    user-filters: 2-0, never
    adnauseam-filters: 503-2, 2d.11h.8m
    eff-dnt-whitelist: 678-0, 2d.11h.8m
    ublock-filters: 34989-69, 2d.11h.8m
    ublock-badware: 4049-1, 1d.1h.59m
    ublock-privacy: 468-0, 8d.8h.7m
    ublock-abuse: 76-76, 4d.8h.54m
    ublock-unbreak: 2134-0, 2d.11h.7m
    ublock-quick-fixes: 235-0, 8h.23m
    easylist: 64996-242, 1h.16m
    easyprivacy: 33356-28, 4d.3h.25m
    urlhaus-1: 6378-0, 1d.46m
filterset (user): [array of 2 redacted]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  admap: [redacted]
  firstInstall: false
  hidingAds: true
  clickingAds: true
  blockingMalware: true
  disableClickingForDNT: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 177 ms (selfie)
  maxAssetCacheWait: 74 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    facebook.net: 1
    googletagmanager.com: 3
    klaviyo.com: 2
    symantec.com: 1
```
</details>

**Comment by dportvine** [comment]
Self-promotion

```adb
softwarekeep.com##body > div > .needsclick
softwarekeep.com##[alt="Banner"]
```

**Comment by okiehsch** [comment]
We don't fix self advertisement, though I don't know if EasyList is interested in this case because of the promo codes.
@ryanbr

**Comment by SpectreKelevra** [comment]
Right, Understood.

**Comment by Yuki2718** [comment]
@SpectreKelevra Enable either `AdGuard – Popup Overlays` + `AdGuard – Other Annoyances` (included in `AdGuard – Annoyances`) or `EasyList – Newsletter Notices` + `EasyList – Other Annoyances` (included in `EasyList – Annoyances`)

**Comment by SpectreKelevra** [comment]
I'm sorry I understood none of that, are those still in the extension or is that something else?

**Comment by stephenhawk8054** [comment]
@SpectreKelevra You are using AdNauseam, not uBO, please report at their repository: https://github.com/dhowe/AdNauseam/issues

**Comment by SpectreKelevra** [comment]
@stephenhawk8054 I just used the "Report" button on the extension itself, I did not seek out this page or know it was separate.

**Comment by Yuki2718** [comment]
If AdNauseam is the same, e.g.:

![filterlists](https://github.com/uBlockOrigin/uAssets/assets/58900598/ed539bae-4aea-44a3-9e59-4ca3be8a1d82)
