### ISSUE TITLE
tutv-gratis.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1918]
URL(s) where the issue occurs

`http://www.tutv-gratis.com/2017/09/tnt-sports-en-vivo-por-internet.html`

Describe the issue

![](https://i.imgur.com/NSA7gt3.png)

Versions

Browser/version: Chrome 65.0.3325.181 (Official Build) (64-bit)
uBlock Origin version: 1.15.18

Settings

Default

**Comment by KiLL4FuNK** [comment]
ADS

`http://www.tutv-gratis.com/2017/11/fox-sports-en-vivo-por-internet.html`

**Comment by mapx-** [comment]
Where are the ads ? screenshot ?
