### ISSUE TITLE
baseball.fantasysports.yahoo.com: breakage

### ISSUE THREAD

**Issue by woymfsu03** [uBlockOrigin/uAssets#19182]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://baseball.fantasysports.yahoo.com/b1/124785/matchup?week=16&mid1=10&mid2=8`

### Category

breakage

### Description

When clicking on a player profile tab it will open fine. (Little gray or blue notepad next to a player) However when you try to switch tabs on that it will just go blank. Turning off uBlock Origin will make it work fine. 

### Other extensions used

Rakuten
Enhancer for Youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screenshot 2023-07-26 at 7 02 36 PM" src="https://github.com/uBlockOrigin/uAssets/assets/140667430/41fae08f-676d-45e7-a384-3ffd60390ced">

<img width="1440" alt="Screenshot 2023-07-26 at 7 02 44 PM" src="https://github.com/uBlockOrigin/uAssets/assets/140667430/3a50548f-e2f9-4618-9b8e-7dfb9a926aba">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 97572
 cosmetic: 39509
 scriptlet: 18110
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69089-9, now
  easyprivacy: 33352-62, now
  plowe-0: 3720-1071, now
  ublock-badware: 7526-142, now
  ublock-filters: 34145-219, now
  ublock-privacy: 443-5, now
  ublock-quick-fixes: 260-76, now
  ublock-unbreak: 2092-33, now
  urlhaus-1: 6330-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 505 ms
 maxAssetCacheWait: 5 ms
popupPanel:
 blocked: 20
 network:
  yahoo.com: 15
  doubleclick.net: 1
  scorecardresearch.com: 1
  yahoo.net: 1
  yimg.com: 2
```
</details>

**Comment by okiehsch** [comment]
After clicking on the first player "H. Davis" what do you mean by "switch tabs"?

**Comment by woymfsu03** [comment]
Sorry about that, When you click on the little white or blue icon player info it should pop up with a window that has Game log stats and news. Not the actual players name but it’s a notepad icon is the easiest way to explain it. Hopefully this helps and the screenshot if you can receive them this way. 

￼

**Comment by okiehsch** [comment]
Hm, it looks differnet on my end.
If I click the blue button I see.
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/a09ab2b5-96b0-4176-b6d8-2f4464a37d6d)

**Comment by woymfsu03** [comment]
If you click on the player history tab does it load or just show a white
box that's what it does for me for some reason.

**Comment by okiehsch** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/380bcf7a-95a1-48c0-889b-dac5c81691fa)

**Comment by okiehsch** [comment]
Have you tried after diabling all other extensions?

**Comment by woymfsu03** [comment]
Just tried and same thing with nothing but uBlockOrigin enabled. They updated the player cards (white/blue box you click on) last year and that’s the old version. But it’s never done this before. Not sure how I can get you to see what I see of if you even want to bother trying. If I go into an incognito window and without logging in I get the old version too and it works same as yours. But the new version seems to be the issue somehow. Is there anything I can do to help if you want to try? If not I completely understand.

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by okiehsch** [comment]
Let's wait and see if someone else here get's the new version.

**Comment by woymfsu03** [comment]
USA

**Comment by woymfsu03** [comment]
Probably will be released for everyone at the start of football season (August/September). It’s bee in their beta since last October. I can click on the player card and it opens ok. It’s just when changing tabs inside the player card. Thanks for taking the time at least though.

**Comment by okiehsch** [comment]
OK, with a US IP I get your version.
I still can't reproduce though.
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/a5ffd560-04ca-4894-84cf-45154c5abd78)

**Comment by woymfsu03** [comment]
Well crap lol. I’ve reset the add-on. Any other recommendations?

**Comment by okiehsch** [comment]
Not really, I tried to deliberately get a blank tab by blocking requests but I can't get it even if I try, 😉

**Comment by woymfsu03** [comment]
Does it help that it does it on Microsoft Edge too lol?

**Comment by woymfsu03** [comment]
Quick update if this helps any…Using a VPN from any country besides US it works fine. VPN in the US doesn’t work. No VPN from my ISP doesn’t work. No VPN from mobile data and hotspot doesn’t work. So basically it’s somehow just the US that doesn’t seem to be working. Not sure if this helps any but just thought I’d send it to you.
