### ISSUE TITLE
1337x.to: ads

### ISSUE THREAD

**Issue by SpectreKelevra** [uBlockOrigin/uAssets#19192]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.1337x.to/search/detroit+become+human/1/`

### Category

ads

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/26509155/2a1324cf-c013-4d26-a10b-7b090dd5e51c)

### Other extensions used

decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
AdNauseam: 3.17.0
Firefox: 115
filterset (summary): 
  network: 95250
  cosmetic: 39845
  scriptlet: 18072
  html: 1006
listset (total-discarded, last-updated): 
  removed: 
    eff-dnt-whitelist: null
  default: 
    user-filters: 0-0, never
    adnauseam-filters: 504-2, 18h.39m
    ublock-filters: 35021-126, 18h.39m
    ublock-badware: 7588-1, 18h.39m
    ublock-privacy: 480-0, 18h.39m
    ublock-abuse: 76-76, 18h.39m
    ublock-unbreak: 2142-1, 18h.39m
    ublock-quick-fixes: 282-0, 18h.39m
    easylist: 69097-421, 18h.39m
    easyprivacy: 33349-30, 18h.39m
    urlhaus-1: 6372-0, 18h.39m
filterset (user): [empty]
hostRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  admap: [redacted]
  firstInstall: false
  hidingAds: true
  clickingAds: true
  blockingMalware: true
  disableClickingForDNT: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 198 ms (selfie)
  maxAssetCacheWait: 99 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by BlazeFTL** [comment]
Report At AdNauseam Git

**Comment by ghajini** [comment]
@dhowe

**Comment by dhowe** [comment]
https://github.com/dhowe/AdNauseam/issues/2359

**Comment by dhowe** [comment]
thanks @MasterKia 
see https://github.com/dhowe/AdNauseam/issues/2361

**Comment by mneunomne** [comment]
Thank you for heads-up, I've changed the URL our application. Sorry for the trouble.
