### ISSUE TITLE
metager.org, metager.de: ads

### ISSUE THREAD

**Issue by flux77** [uBlockOrigin/uAssets#19193]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ads are still shown in metager.org and metager.de search results.

### URL(s) where the issue occurs.

`https://metager.org/meta/meta.ger3?eingabe=java%20programming%20books`

### Screenshot(s)

* The first and second ads have URL of the form `https://metager.org/r/metager/...`
* The third ad has URL `https://metager.org/spende`

![metager org](https://github.com/uBlockOrigin/uAssets/assets/44834611/03276f1c-da2f-464c-871c-8cd8627e99be)

### uBO version

1.51.0

### Browser name and version

Firefox 102.13.0esr

### Settings

...

### Notes

Suggested filters:

```
metager.org,metager.de##.result:has(.result-open-key)
metager.org,metager.de##.result:has(img[alt="Mark"])

metager.org##.result:has(a[href="https://metager.org/keys"])
metager.org##.result:has(a[href="https://metager.org/partnershops"])
metager.org##.result:has(a:has-text(REMOVE ADVERTISING))

metager.de##.result:has(a[href="https://metager.de/keys"])
metager.de##.result:has(a[href="https://metager.de/partnershops"])
metager.de##.result:has(a:has-text(WERBUNG ENTFERNEN))
```

**Comment by stephenhawk8054** [comment]
Can you copy your troubleshooting information to here?
