### ISSUE TITLE
[nsfw] lxmanga.net: popups

### ISSUE THREAD

**Issue by bui-lang** [uBlockOrigin/uAssets#19195]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lxmanga.net/truyen/kagiana`

### Category

popups

### Description

pop-up appears when tap the "X" button

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![X-button](https://github.com/uBlockOrigin/uAssets/assets/74956696/79867b4e-2a0b-472d-bbf6-8d2ec2e17e01)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 4m
Chromium Mobile: 116
filterset (summary):
 network: 99670
 cosmetic: 31197
 scriptlet: 18269
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  VIE-1: 1964-16, 4m
  adguard-mobile: 8435-35, 4m
  easylist: 69105-16528, 4m
  easyprivacy: 33354-73, 4m
  plowe-0: 3720-1144, 4m
  ublock-badware: 7580-143, 4m
  ublock-filters: 34449-479, 4m
  ublock-privacy: 442-8, 4m
  ublock-quick-fixes: 274-88, 4m
  ublock-unbreak: 2104-37, 4m
  urlhaus-1: 6409-0, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1636 ms
 maxAssetCacheWait: 412 ms
popupPanel:
 blocked: 1
 network:
  adconnect.vn: 1
 extended:
  ##.ads-wrapper
```
</details>

**Comment by ghajini** [comment]
@hoang-rio ,**ABPVN** list
