### ISSUE TITLE
bombuj.si: popups

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [uBlockOrigin/uAssets#19190]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello, I started using the filters, but here it always opens a new site, is it possible to block it somehow? Or how?
I use these filters:

```adb
! 2023-07-27 https://www.bombuj.si
||waaw.ac/player/embed_player.php?vid=jpvImPa0VByz$subdocument
||waaw.ac/player/embed_player.php$subdocument
||www.bombuj.si/images/tlacitkosk.gif$image
||www.bombuj.si/images/anim_3.gif$image
||www.bombuj.si/images/tlacitkosk.gif$image
www.bombuj.si###zatvorit-rekllamu-popup2
www.bombuj.si##.reklaama-casino2
www.bombuj.si###rekllamacasino2
```

### URL(s) where the issue occurs.

`https://www.bombuj.si/online-film-flash-2023`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/68572049/50e00bdb-088d-4833-9ac6-b4ff7a4c72ce)

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 97905
 cosmetic: 39860
 scriptlet: 18280
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 17-5, never
  CZE-0: 745-1, 2m
  easylist: 69092-11, 2m
  easyprivacy: 33354-67, 2m
  plowe-0: 3720-1071, 2m
  ublock-badware: 7586-142, 2m
  ublock-filters: 34150-219, 2m
  ublock-privacy: 441-7, 2m
  ublock-quick-fixes: 282-86, 2m
  ublock-unbreak: 2098-34, 2m
  urlhaus-1: 6353-0, 1m
filterset (user): [array of 17 redacted]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1180 ms
 maxAssetCacheWait: 267 ms
```
</details>

**Comment by stephenhawk8054** [comment]
What happens if you remove all your custom filters?

This appear when I access your link: https://github.com/uBlockOrigin/uAssets/assets/66517106/529fde15-2b72-4c42-905c-6105af7f78bf

What should I do next?

**Comment by okiehsch** [comment]
Try clicking zavorit, it means §close the ad".

I am geoblocked.

**Comment by ghajini** [comment]
add this in **my filters** for test
```
bombuj.si###rekllamacasino2
bombuj.si###zatvorit-rekllamu-popup2
bombuj.si###ad_banner2
bombuj.si###ad_banner3
||wurfl.io/wurfl.js$script
waaaw.*##+js(aopr, doSecondPop)
waaaw.*,waaw.*##+js(aopr, BetterJsPop)
/cdn-cgi/trace$xhr,domain=waaw.*|waaaw.*
```

@tomasko126 ,easylistczechandslovak

**Comment by Sh3r1ffCZ** [comment]
> add this in **my filters** for test
> 
> ```
> bombuj.si###rekllamacasino2
> bombuj.si###zatvorit-rekllamu-popup2
> bombuj.*##[id*="ad_banner"]
> ||wurfl.io/wurfl.js$script
> waaaw.*##+js(aopr, doSecondPop)
> waaaw.*,waaw.*##+js(aopr, BetterJsPop)
> /cdn-cgi/trace$xhr,domain=waaw.*|waaaw.*
> ```
> 
> @tomasko126 ,easylistczechandslovak

OMG thanks :D
