### ISSUE TITLE
rus.bongacams21.com: popups

### ISSUE THREAD

**Issue by Aliothis** [uBlockOrigin/uAssets#19197]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rus.bongacams21.com/?bcs=cmlvZDkxYTc1NmU1OGY1MmZiMDk0OGFiMzFhYjU0MDA5MDE3OjoxOTE4MDA6Ojo6OjpFRURONEdCMFU6OjM5OTU1MTo6MDo6MTo6MTo6OjowOjpkZWZhdWx0Ojow`

### Category

popups

### Description

porno site

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<![image](https://github.com/uBlockOrigin/uAssets/assets/140795834/126e872a-d6d0-47dd-b55e-d47fb4a656e8) -->

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 114917
 cosmetic: 60481
 scriptlet: 19415
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  RUS-0: 39613-9, now
  easylist: 69105-33, now
  easyprivacy: 33354-152, now
  plowe-0: 3720-1076, now
  ublock-badware: 7586-142, now
  ublock-filters: 34153-248, now
  ublock-privacy: 445-8, now
  ublock-quick-fixes: 253-68, 7m
  ublock-unbreak: 2101-33, now
  urlhaus-1: 6409-0, 8m
filterset (user): [empty]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 677 ms (selfie)
 maxAssetCacheWait: 275 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce popups.
@dimisa-RUAdList can you reproduce?

**Comment by dimisa-RUAdList** [comment]
It is not clear what kind of pop-up we are talking about, and what steps need to be taken in order for the declared event to occur. I haven't been able to reproduce the issue.

**Comment by Yuki2718** [comment]
If it means `##.__give_away.bc_popalert`, hiding it causes clicking the green button does not responde. Maybe this is why it's not hidden in AG Annoyances.
