### ISSUE TITLE
Kisscartoon.ac

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#1919]
### URL(s) where the issue occurs

`kisscartoon.ac`

### Describe the issue

Popup ads.

### Settings

- Default settings

### Notes

`||kisscartoon.ac^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.onesignal.com *.google.com *.facebook.com *.facebook.net *.fbcdn.net *.google-analytics.com *.gstatic.com` fixes it. It probably allows too much, but I didn't want to risk breaking login functions.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/91925d17debc6f3d454c4fbfa0eae44041042fd2 already fixes the issue, atleast on my end, have you updated `uBO-filters`?

**Comment by zaphodbeebblebrox** [comment]
Sorry, I did not realize that that had been added.

**Comment by KiLL4FuNK** [comment]
I can not see the video

`https://kisscartoon.su/Cartoon/Bob-s-Burgers-Season-9/Episode-004-Nightmare-on-Ocean-Avenue-Street?id=81737`
