### ISSUE TITLE
serial.kukaj.io: ads

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [uBlockOrigin/uAssets#19191]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://serial.kukaj.io/modra-planeta-ii/S01E01`

### Category

ads

### Description

Can i remove this ad? Thanks

### Other extensions used

nope

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/68572049/0392d2c8-33e0-4d9a-8bac-14336665e3ef)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 97904
 cosmetic: 39860
 scriptlet: 18280
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 14-3, never
  CZE-0: 745-1, 8m
  easylist: 69092-11, 8m
  easyprivacy: 33354-67, 7m
  plowe-0: 3720-1071, 7m
  ublock-badware: 7586-142, 7m
  ublock-filters: 34150-219, 7m
  ublock-privacy: 441-7, 7m
  ublock-quick-fixes: 282-86, 7m
  ublock-unbreak: 2098-34, 7m
  urlhaus-1: 6353-0, 7m
filterset (user): [array of 14 redacted]
trustedset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1180 ms
 maxAssetCacheWait: 267 ms
popupPanel: 
 blocked: 5
 network: 
  coinblocktyrusmiram.com: 1
  etargetnet.com: 1
  googlesyndication.com: 1
  kukaj.to: 2
```
</details>

**Comment by dportvine** [comment]
I only see the YouTube player, account required?

**Comment by stephenhawk8054** [comment]
Needs Czech IP
