### ISSUE TITLE
animexin.vip: detection

### ISSUE THREAD

**Issue by nk70424** [uBlockOrigin/uAssets#19198]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animexin.vip/`

### Category

detection

### Description

A big pop up with ad blocker detected

### Other extensions used

grammarly
facebook container
dark background and light text
firefox translations

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (153)](https://github.com/uBlockOrigin/uAssets/assets/113443121/8671ccad-69a2-4378-95a8-e8a498171f9a)

</details>
![Screenshot (152)](https://github.com/uBlockOrigin/uAssets/assets/113443121/31540a80-c84a-4cfc-b5aa-8ae787fc35d9)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 97747
 cosmetic: 39526
 scriptlet: 18077
 html: 1006
listset (total-discarded, last-updated):
 default:
  user-filters: 25-3, never
  ublock-filters: 35029-125, now
  ublock-badware: 7588-2, now
  ublock-privacy: 482-0, now
  ublock-unbreak: 2148-1, now
  easylist: 69105-781, now
  easyprivacy: 33354-723, now
  urlhaus-1: 6409-0, now
  plowe-0: 3720-1, now
  ublock-quick-fixes: 283-0, 15m
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1470 ms
 maxAssetCacheWait: 159 ms
popupPanel:
 blocked: 13
 network:
  cestibegster.com: 2
  googlesyndication.com: 5
  googletagmanager.com: 1
  histats.com: 1
  onesignal.com: 1
  patreon.com: 1
  vooodkabelochkaa.com: 2
 extended:
  ##ins.adsbygoogle
  ##.wrapper > .announ
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by nk70424** [comment]
I didn't get that what I am supposed to do?

**Comment by JobcenterTycoon** [comment]
Force update the filterlists. (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
