### ISSUE TITLE
cbuch.de: privacy

### ISSUE THREAD

**Issue by delkant03** [uBlockOrigin/uAssets#19206]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cbuch.de/macarthur-die-lebendige-gemeinde.html`

### Category

privacy

### Description

Please block the requests by adding it to the Easyprivacy filter.
`https://assets.yumpu.com/release/b5WnlPWbBX/v4/js/modules/tracking/tracking.js`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 100151
 cosmetic: 44144
 scriptlet: 18126
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7003-0, 16m
  easylist: 69075-15, 16m
  easyprivacy: 33350-71, 16m
  plowe-0: 3717-1072, 16m
  ublock-badware: 7586-142, 16m
  ublock-filters: 34155-233, 16m
  ublock-privacy: 445-7, 16m
  ublock-quick-fixes: 282-88, 15m
  ublock-unbreak: 2102-36, 15m
  urlhaus-1: 6521-0, 15m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 575 ms
 maxAssetCacheWait: 228 ms
popupPanel:
 blocked: 4
 network:
  cbuch.de: 1
  advertserve.com: 1
  paypal.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/issues
