### ISSUE TITLE
twitter.com: ads

### ISSUE THREAD

**Issue by dumbuz** [uBlockOrigin/uAssets#19208]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://twitter.com/`

### Category

ads

### Description

twitter/x verified program has an ad above the "What's happening" and "Who to follow" panel

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/44739965/08bbcc63-1ec0-4f69-80be-bd3e8bb05111)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 114
filterset (summary):
 network: 235765
 cosmetic: 39526
 scriptlet: 18099
 html: 1006
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35040-129, now
  ublock-badware: 7602-1, now
  ublock-privacy: 483-0, 39m
  ublock-unbreak: 2150-2, now
  ublock-quick-fixes: 277-0, 34m
  easylist: 69128-780, now
  adguard-spyware-url: 1150-5, 38m
  easyprivacy: 33356-723, now
  urlhaus-1: 6521-0, 35m
  curben-phishing: 134718-58, 36m
  plowe-0: 3717-2, now
  LegitimateURLShortener: 2248-143, 37m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 422 ms (selfie)
 maxAssetCacheWait: 241 ms
popupPanel:
 blocked: 15
 network:
  twitter.com: 14
  google-analytics.com: 1
 extended:
  ##[data-testid="trend"]:has-text(/Promoted|Gesponsert|Promociona…
  ##div[data-testid="trend"]:has(path[d$="10H8.996V8h7v7z"])
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like self-promotion?

**Comment by dumbuz** [comment]
> Looks like self-promotion?

I didn't realize self promotion wasn't supposed to be blocked. Closed.
