### ISSUE TITLE
autofaucet.dutchycorp.space: breakage

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#19209]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://autofaucet.dutchycorp.space/coin_roll.php`
`https://autofaucet.dutchycorp.space/roll.php`

### Category

breakage

### Description

by the link `https://autofaucet.dutchycorp.space/roll.php` and by the link `https://autofaucet.dutchycorp.space/coin_roll.php` if you go through the captcha and click on the button "BOSSTED ROLL" pops up "Something blocks the video script, be sure to disable AdBlock, Shield and Trackers Blockers." If you turn off uBlockorigin, then everything is fine, there are no errors and the reward is collected after watching the video. A big request to finish this. Thank you in advance.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 117380
 cosmetic: 65149
 scriptlet: 19386
 html: 1021
listset (total-discarded, last-updated):
 added:
  DEU-0: 7003-7, 56m
 default:
  user-filters: 0-0, never
  ublock-filters: 35040-325, 56m
  ublock-badware: 7602-2, 56m
  ublock-privacy: 483-0, 56m
  ublock-unbreak: 2150-1, 56m
  ublock-quick-fixes: 277-0, 1h.5m
  easylist: 69128-563, 56m
  easyprivacy: 33356-773, 56m
  urlhaus-1: 6521-0, 56m
  plowe-0: 3717-1, 56m
  RUS-0: 39651-158, 1h.41m
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 714 ms (selfie)
 maxAssetCacheWait: 386 ms
popupPanel:
 blocked: 30
 network:
  dutchycorp.space: 8
  a-ads.com: 3
  admediatex.net: 1
  bmcdn4.com: 4
  bmfads.com: 1
  cloudflare.com: 2
  cpx-research.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  pubfuture-ad.com: 1
  tradingview.com: 1
  vliplatform.com: 2
  vlitag.com: 3
 extended:
  ##.show-on-medium
  ##[href*="banner"]
  ##center > .hide-on-med-and-down
  ##.nav-ad
  ##[style*="width:300px;height:250px"]
  ##+js(abort-current-script, eval, replace)
  ##+js(abort-on-property-read, NoAdBlock)
  ##+js(abort-on-property-read, adBlockDetected)
  ##+js(nano-setInterval-booster, time.html, 1000)
  ##+js(set-constant, blurred, false)
  ##+js(abort-current-script, console.log, blockAdBlock)
```
</details>

**Comment by mapx-** [comment]
Test

```
@@||googletagmanager.com/gtag/js$script,domain=autofaucet.dutchycorp.space
@@||cdnjs.cloudflare.com^$script,domain=autofaucet.dutchycorp.space
@@||imasdk.googleapis.com^$script,domain=autofaucet.dutchycorp.space
```
