### ISSUE TITLE
vk.com: breakage

### ISSUE THREAD

**Issue by e-shebanov** [uBlockOrigin/uAssets#19213]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vk.com/im?sel=`

### Category

breakage

### Description

Hides the element responsible for link preview in the dialog

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 114960
 cosmetic: 60499
 scriptlet: 19444
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  RUS-0: 39622-9, now
  easylist: 69101-33, now
  easyprivacy: 33357-152, now
  plowe-0: 3717-1076, now
  ublock-badware: 7600-142, now
  ublock-filters: 34172-247, now
  ublock-privacy: 446-8, now
  ublock-quick-fixes: 286-88, now
  ublock-unbreak: 2103-34, now
  urlhaus-1: 6447-0, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1937 ms
 maxAssetCacheWait: 15 ms
popupPanel:
 blocked: 5
 network:
  mail.ru: 3
  tns-counter.ru: 1
  vk-portal.net: 1
 extended:
  ###ads_left
  ###system_msg
  ##a[href*="&utm_medium=cpa"][target="_blank"]
  #@#div[id$="notifiers_wrap"]
  ##+js(abort-on-property-read, Groups.showDisclaimer)
  ##+js(abort-on-property-read, PageBottomBanners)
  ##+js(abort-on-property-read, Unauthorized2)
  ##+js(href-sanitizer, a[href*="/away.php?to="], ?to)
  ##+js(set-constant, noAdsAtAll, {})
```
</details>

**Comment by dimisa-RUAdList** [comment]
It's better to discuss it here: https://forums.lanik.us/viewtopic.php?t=28751

Or here: https://github.com/easylist/ruadlist/issues/new
