### ISSUE TITLE
bcbstx.com: breakage

### ISSUE THREAD

**Issue by xoverride** [uBlockOrigin/uAssets#19211]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bcbstx.com/`

### Category

breakage

### Description

Login/Register and Make a payment button not working with block on.

### Other extensions used

tampermonkey - no script running on this web
Adobe Acrobat
Grammarly

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/13634432/871df687-408f-4447-8c06-f83d7ea97b8d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 111932
 cosmetic: 49801
 scriptlet: 18301
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CHN-0: 24785-128, now
  easylist: 69128-65, now
  easyprivacy: 33356-77, now
  plowe-0: 3717-1073, now
  ublock-badware: 7600-142, now
  ublock-filters: 34164-232, now
  ublock-privacy: 446-7, now
  ublock-quick-fixes: 286-88, now
  ublock-unbreak: 2103-35, now
  urlhaus-1: 6447-0, now
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1594 ms (selfie)
 maxAssetCacheWait: 84 ms
popupPanel:
 blocked: 11
 network:
  adobedtm.com: 2
  bcbsil.com: 1
  decibelinsight.net: 1
  demdex.net: 1
  dynatrace.com: 2
  googletagmanager.com: 1
  kampyle.com: 1
  walkme.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||dynatrace.com^$script,redirect-rule=noopjs,domain=bcbstx.com
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.
