### ISSUE TITLE
football.fantasysports.yahoo.com: breakage

### ISSUE THREAD

**Issue by lemonbrady** [uBlockOrigin/uAssets#19218]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://football.fantasysports.yahoo.com/f1/11310/players?status=ALL&pos=O&cut_type=9&stat1=S_S_2022&myteam=0&sort=OR&sdir=1&pspid=782200994&activity=players_sort_click`

### Category

breakage

### Description

When clicking on a player note, it will not open while UBO is active

<img width="1088" alt="Screenshot 2023-07-29 at 10 14 19 AM" src="https://github.com/uBlockOrigin/uAssets/assets/140911081/bb9e6777-3a95-454d-8ef7-eba3331120ce">

(player note is the small box with 3 lines to the right of a players name)

when UBO is off the box will open like this
<img width="1495" alt="Screenshot 2023-07-29 at 10 15 19 AM" src="https://github.com/uBlockOrigin/uAssets/assets/140911081/118640e4-37fc-4a36-acca-80f3a4d59a0d">

when UBO is on, the screen will freeze unless escape button is pressed. seems like the window is open but not shown and not sure what is being blocked

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 40d.19h.32m
Chromium: 115
filterset (summary):
 network: 137020
 cosmetic: 260448
 scriptlet: 41598
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42453-42, 14m
  https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt: 0-0, 15m
  adguard-cookies: 26472-225, now
  adguard-generic: 72885-500, now
  adguard-mobile-app-banners: 4453-13, now
  adguard-other-annoyances: 13175-19, now
  adguard-popup-overlays: 23200-200, now
  adguard-social: 21011-1126, now
  adguard-widgets: 2223-3, now
  dpollock-0: 11540-28, now
  easylist-annoyances: 3878-256, now
  easylist-chat: 131-9, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 45-5, never
  easylist: 69141-1309, now
  easyprivacy: 33360-370, now
  plowe-0: 3717-1454, now
  ublock-badware: 7600-363, now
  ublock-filters: 34193-4220, now
  ublock-privacy: 444-9, now
  ublock-quick-fixes: 299-102, now
  ublock-unbreak: 2101-97, now
  urlhaus-1: 6436-0, now
filterset (user): [array of 49 redacted]
trustedset:
 added: [array of 83 redacted]
 removed:
  chrome-scheme
  edge-scheme
switchRuleset:
 added: [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 250
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 298 ms (selfie)
 maxAssetCacheWait: 184 ms
popupPanel:
 blocked: 17
 network:
  yahoo.com: 11
  oath.com: 2
  scorecardresearch.com: 1
  yimg.com: 3
 extended:
  ###community-bar,#yucs-top-bar,.canvas-community-bar,.cover-comm…
  ###atomic, #UH-0-Header, #UH-1-NavLite, #UH, #UH-0-SportsUH-0-He…
  ##+js(remove-class, vp-docked, , stay)
  ##+js(remove-class, vp-docked-mode, , stay)
```
</details>

**Comment by okiehsch** [comment]
You added a whole bunch of additional lists.
````
 added:
  https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42453-42, 14m
  https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt: 0-0, 15m
  adguard-cookies: 26472-225, now
  adguard-generic: 72885-500, now
  adguard-mobile-app-banners: 4453-13, now
  adguard-other-annoyances: 13175-19, now
  adguard-popup-overlays: 23200-200, now
  adguard-social: 21011-1126, now
  adguard-widgets: 2223-3, now
  dpollock-0: 11540-28, now
  easylist-annoyances: 3878-256, now
  easylist-chat: 131-9, now
  [6 lists not shown]: [too many]
````

Disable them and try again.

**Comment by lemonbrady** [comment]
thanks, that solved it

**Comment by lemonbrady** [comment]
Thanks asshole
