### ISSUE TITLE
trendencias.com,  3djuegospc.com: ads; xataka.com: breakage

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#19221]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

this websites of the same "family"

ads in the images in `trendencias.com`
ads in stories of:  `3djuegospc.com`

in `xataka.com` and other similar sites the recomendation posts are broken ( can't click )

### URL(s) where the issue occurs.

`https://www.trendencias.com/sneakers/vuelven-zapatillas-madre-asi-como-deportivas-retro-lona-vuelven-a-ser-tendencia-2023`

`https://stories.3djuegospc.com/media/24777/?frame=71d1f11d58085409c4cf`

`https://www.xataka.com/magnet/reino-unido-tiene-enorme-problema-refugiados-su-solucion-instalarlos-enorme-barcaza-prision`

### Screenshot(s)

trendencias ads: https://github.com/uBlockOrigin/uAssets/assets/33556647/2ca4f7a9-e695-4b6e-b9a9-abf4defbdf27

ads in stories 3djuegospc: https://github.com/uBlockOrigin/uAssets/assets/33556647/a2bc8ad1-e494-4ccd-b833-bf4dfb317695

### uBO version

1.51.0

### Browser name and version

Chrome

### Settings

```
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 100552
 cosmetic: 46881
 scriptlet: 22056
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5299-7, 21m
 default:
  user-filters: 0-0, never
  easylist: 69141-9, 21m
  easyprivacy: 33360-62, 21m
  plowe-0: 3717-1071, 21m
  spa-0: 3577-15, 21m
  spa-1: 5383-211, 21m
  ublock-badware: 7600-142, 21m
  ublock-filters: 34193-250, 21m
  ublock-privacy: 446-7, 21m
  ublock-quick-fixes: 299-100, 21m
  ublock-unbreak: 2103-37, 21m
  urlhaus-1: 6436-0, 21m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 278 ms (selfie)
 maxAssetCacheWait: 120 ms
```

**Comment by Yuki2718** [comment]
What is broken?
