### ISSUE TITLE
makeuseof.com: ads

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#19224]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.makeuseof.com/free-microsoft-office-alternatives-android/`

### Category

ads

### Description

Ad leftover space

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-07-30 at 10-30-09 The 7 Best Free Microsoft Office Alternatives for Android](https://github.com/uBlockOrigin/uAssets/assets/101707608/b6a97ebb-4473-44a0-918d-ae464413a432)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 410842
 cosmetic: 246419
 scriptlet: 42062
 html: 1198
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 54198-5943, 1h.2m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 74679-1920, 1h.1m
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 665-0, 1h.2m
  https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1955-7, 1h.1m
  https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 108-0, 1h.1m
  https://www.i-dont-care-about-cookies.eu/abp/: 25741-19, 1h.1m
  adguard-generic: 72889-7253, 1h.1m
  adguard-mobile: 8440-134, 1h.1m
  adguard-spyware-url: 1151-5, 1h.1m
  block-lan: 48-0, now
  curben-phishing: 136730-61, 1h.1m
  curben-pup: 199-0, 1h.1m
  [16 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35073-717, 1h.2m
  ublock-badware: 7602-1, 1h.2m
  ublock-privacy: 483-2, 1h.2m
  ublock-unbreak: 2150-1, 1h.2m
  ublock-quick-fixes: 232-0, 1h.1m
  easylist: 69037-27553, 1h.2m
  easyprivacy: 33357-1020, 1h.2m
  urlhaus-1: 6416-0, 1h.1m
  plowe-0: 3717-3, 1h.2m
  GRC-0: 1042-2, 1h.1m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 24591 ms
 maxAssetCacheWait: 12698 ms
popupPanel:
 blocked: 112
 network:
  makeuseof.com: 3
  ad.gt: 2
  adlightning.com: 2
  adsninja.ca: 4
  aloofvest.com: 2
  amazon-adsystem.com: 1
  doubleclick.net: 7
  google-analytics.com: 1
  google.com: 33
  googlesyndication.com: 1
  googletagmanager.com: 2
  googletagservices.com: 1
  imasdk.googleapis.com: 2
  marfeelrev.com: 1
  primis.tech: 1
  privacymanager.io: 3
  unpkg.com: 1
  viglink.com: 1
  youtube.com: 44
 extended:
  ##.btn-mail
  ##.copy-link-button
  ##.sharing-btn:not(.btn-comments)
  ##.article-footer-newsletter
  ##body:style(overflow-y: auto !important;)
  ##+js(no-setTimeout-if, document.body.classList.add, 100)
  ##.ytp-share-button
  ##div[class$="-gradient-bottom"]
  ##.ytp-pause-overlay
  ##.ytp-title-channel
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(set-constant, google_ad_status, 1)
```
</details>

**Comment by okiehsch** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/1b6c14f2-d2e5-4e7b-8b0f-e5a8a88d0ff0)
You have enabled more than 20 additional lists...

Try again after removing them.
I can't reproduce.

**Comment by Nojuuu** [comment]
`https://secure.fanboy.co.nz/fanboy-problematic-sites.txt`

causes it
