### ISSUE TITLE
apkupload.in: detection

### ISSUE THREAD

**Issue by QedirAbiyev** [uBlockOrigin/uAssets#19235]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://link.vipurl.in/ruG0o`
`https://apkupload.in/`

### Category

detection

### Description

This website shows "please disable adblock" warning.

### Other extensions used

Adguard. (But still warn me when I disable adguard)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-07-31-12-10-21-406_org mozilla firefox](https://github.com/uBlockOrigin/uAssets/assets/56096861/5f11ac11-2430-412e-909e-22de2ad31a8f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 115
filterset (summary):
 network: 99101
 cosmetic: 29999
 scriptlet: 18182
 html: 1014
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35317-397, now
  ublock-badware: 7617-2, now
  ublock-privacy: 482-1, now
  ublock-unbreak: 2158-2, now
  ublock-quick-fixes: 310-0, now
  adguard-mobile: 8442-120, now
  easylist: 69046-17207, now
  easyprivacy: 33375-728, now
  urlhaus-1: 6441-0, now
  plowe-0: 3717-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1889 ms (selfie)
 maxAssetCacheWait: 783 ms
popupPanel:
 blocked: 10
 network:
  doubleclick.net: 5
  googlesyndication.com: 2
  googletagmanager.com: 1
  wp.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by ghajini** [comment]
iam sure you land on this page from other site, tell us originating site for this

**Comment by QedirAbiyev** [comment]
This is a redirected intermediary site from a telegram channel to download an app.

**Comment by ghajini** [comment]
which telegram channel, a link?

**Comment by QedirAbiyev** [comment]
> which telegram channel, a link?

https://t.me/c/1615367489/1169

**Comment by QedirAbiyev** [comment]
> That channel is private, the link is useless.

The channel does not belong to me. The link is not useless, just the channel is private.

**Comment by QedirAbiyev** [comment]
> Send the message from the channel containing that download link.

https://link.vipurl.in/ruG0o
The download link is this

**Comment by BlazeFTL** [comment]
Test URL - `https://indianshortner.in/h88DG3PE`
Only Detection Fix - 
```
apkupload.in##+js(rmnt, script, ai_adb)
apkupload.in##+js(no-fetch-if, /doubleclick|googlesyndication/)
```

**Comment by QedirAbiyev** [comment]
> Test URL - `https://indianshortner.in/h88DG3PE`
> Only Detection Fix - 
> ```
> apkupload.in##+js(rmnt, script, ai_adb)
> apkupload.in##+js(no-fetch-if, /doubleclick|googlesyndication/)
> ```
> 
> Domain Changing Geeks Uses Domains For 2-3 Days Then Discarded..
> ```
> awuyro.com,apkupload.in###wpsafe-link:style(display: block !important;)
> awuyro.com,apkupload.in###wpsafe-link:others()
Continue to "inspect" then.😂

**Comment by Sopor** [comment]
This site seems to have been changed because i get a detection.

![image](https://github.com/uBlockOrigin/uAssets/assets/5789283/1ca7d2d3-c879-4195-b0a7-bfa53fb27a29)

This is not the original site but it get stuck here:
`https://ezeviral.com/2022/12/24/top-5-cloud-based-hosting-for-wordpress-know-about-them`

This is the original URL:
`https://link.vipurl.in/cKkoqHx`
