### ISSUE TITLE
koylinks.win [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1923]
URL(s) where the issue occurs

`http://koylinks.win/dJA6m4`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
```
koylinks.win##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)
koylinks.win##script:inject(nano-setInterval-booster.js)
```

**Comment by KiLL4FuNK** [comment]
![](https://i.imgur.com/MOAsqxg.png)
