### ISSUE TITLE
omegle.com: [unknown]

### ISSUE THREAD

**Issue by abbie1122** [uBlockOrigin/uAssets#19234]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.omegle.com/`

### Category

[unknown]

### Description

im banned

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 114
filterset (summary):
 network: 97760
 cosmetic: 39561
 scriptlet: 18173
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69074-9, 2m
  easyprivacy: 33374-62, 1m
  plowe-0: 3717-1070, 1m
  ublock-badware: 7621-142, 1m
  ublock-filters: 34127-145, 1m
  ublock-privacy: 445-4, 1m
  ublock-quick-fixes: 307-102, 1m
  ublock-unbreak: 2106-34, 1m
  urlhaus-1: 6441-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5213 ms
 maxAssetCacheWait: 42 ms
popupPanel:
 blocked: 2
 network:
  google-analytics.com: 1
  translate.googleapis.com: 1
```
</details>

**Comment by abbie1122** [comment]
thanks

**Comment by abbie1122** [comment]
ok

**Comment by abbie1122** [comment]
ok

**Comment by abbie1122** [comment]
ok

**Comment by ghajini** [comment]
don't spam,come with exact issue description
