### ISSUE TITLE
lordchannel.com: popups

### ISSUE THREAD

**Issue by fabio1999ita** [uBlockOrigin/uAssets#19237]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lordchannel.com/`

### Category

nuisance

### Description

i get sometimes popup also that need to close for use site

### Other extensions used

minerblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 101630
 cosmetic: 46507
 scriptlet: 18165
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 300-99, 5m
 default:
  user-filters: 0-0, never
  ITA-0: 10620-10, now
  easylist: 69069-18, now
  easyprivacy: 33375-63, now
  plowe-0: 3717-1071, now
  ublock-badware: 7621-142, now
  ublock-filters: 34132-155, now
  ublock-privacy: 443-4, 5m
  ublock-unbreak: 2106-34, now
  urlhaus-1: 6664-0, now
filterset (user): [empty]
trustedset:
 added: [array of 34 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 227 ms (selfie)
 maxAssetCacheWait: 86 ms
popupPanel:
 blocked: 21
 network:
  lordchannel.com: 1
  d2bxxk33t58v29.cloudfront.net: 1
  google.com: 5
  inklinkor.com: 1
  kamost.com: 5
  loaire.com: 1
  postaffiliatepro.com: 1
  starcasino.it: 1
  uptimecdn.com: 1
  youradexchange.com: 4
```
</details>

**Comment by ghajini** [comment]
we can fix these as these adservers are random
