### ISSUE TITLE
bflix.io: ads

### ISSUE THREAD

**Issue by meeanderson** [uBlockOrigin/uAssets#19244]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bflix.io/tv/this-is-us-pmwlx/5-16`

### Category

nuisance

### Description

Square in the middle of the screen. must click the X to remove. Ublock does not recognize the square. 

### Other extensions used

Adguard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://prnt.sc/BA9Zj45xptu0

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 98050
 cosmetic: 22891
 scriptlet: 18141
 html: 1013
listset (total-discarded, last-updated):
 default:
  user-filters: 26-8, never
  ublock-filters: 35008-465, 1h.56m
  ublock-badware: 7625-1, 1h.55m
  ublock-privacy: 482-1, now
  ublock-unbreak: 2153-2, 1h.54m
  ublock-quick-fixes: 326-0, now
  easylist: 69114-17026, now
  easyprivacy: 33363-763, 1h.57m
  urlhaus-1: 6700-0, now
  plowe-0: 3717-2, now
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 86 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4878 ms (selfie)
 maxAssetCacheWait: 1930 ms
popupPanel:
 blocked: 5
 network:
  amung.us: 1
  bidgear.com: 1
  bunnycdn.ru: 1
  disqus.com: 1
  google.com: 1
 extended:
  ##+js(abort-on-property-read, AaDetector)
  ##+js(abort-on-property-read, zfgstorage)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, mm)
  ##+js(no-setInterval-if, break)
  ##+js(no-window-open-if, !api?call=, 10, obj)
```
</details>

**Comment by ghajini** [comment]
update filters in 10-15 mins
