### ISSUE TITLE
shrinkcash.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1924]
URL(s) where the issue occurs

`http://shrinkcash.com/MhYbhni`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
```
shrinkcash.com##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)
shrinkcash.com##script:inject(addEventListener-defuser.js,load, function g)
shrinkcash.com##script:inject(nano-setInterval-booster.js)
```

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
