### ISSUE TITLE
aniworld.to: breakage

### ISSUE THREAD

**Issue by haast09** [uBlockOrigin/uAssets#19243]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aniworld.to/anime/stream/rent-a-girlfriend/staffel-3/episode-4`

### Category

breakage

### Description

the streamtape video does not start yesterday it worked fine this problem was solved months ago but seems like its back again 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 302049
 cosmetic: 122665
 scriptlet: 35728
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 72817-467, 4m
  adguard-spyware: 62217-1130, 4m
  adguard-spyware-url: 1152-3, 4m
  block-lan: 48-0, 4m
  curben-phishing: 137284-27, 4m
  curben-pup: 189-0, 4m
  fanboy-cookiemonster: 47895-217, 4m
 default:
  user-filters: 2-0, never
  DEU-0: 7008-0, 4m
  easylist: 69114-990, 4m
  easyprivacy: 33375-16843, 4m
  plowe-0: 3717-1163, 4m
  ublock-badware: 7628-392, 4m
  ublock-filters: 34134-3815, 4m
  ublock-privacy: 447-64, 4m
  ublock-quick-fixes: 325-108, 4m
  ublock-unbreak: 2108-142, 4m
  urlhaus-1: 6664-2, 4m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 111 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1155 ms (selfie)
 maxAssetCacheWait: 501 ms
popupPanel:
 blocked: 24
 no-popups: true
 network:
  adforcast.com: 4
  ads-twitter.com: 2
  d3m8nzcefuqu7h.cloudfront.net: 2
  imasdk.googleapis.com: 2
  limosiwooable.com: 2
  punkfigured.com: 2
  scriptcdn.net: 1
  streamtape.com: 2
  witnessremovalsoccer.com: 2
  yandex.ru: 3
  zimpolo.com: 2
 extended:
  ##+js(abort-current-script, document.createElement, delete windo…
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
  ##+js(abort-current-script, document.createElement, adblock)
  ##+js(no-setInterval-if, adblock, 700)
  ##+js(set-constant, googleAd, true)
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-current-script, Math, /emZnbG9hZGVk|break;case \$\./…
  ##+js(no-window-open-if)
  ##+js(no-setInterval-if, adblock)
  ##+js(remove-attr, target, #downloadvideo)
  ##+js(nano-setTimeout-booster, counter)
  ##+js(abort-current-script, JSON.parse, Promise)
```
</details>

**Comment by okiehsch** [comment]
Works on my end, you have to click three times times.

**Comment by haast09** [comment]
> Works on my end, you have to click three times times.

okay weird works for me now too i could have clicked a 100 times nothing happened. for example i clicked 2 times then it flashed and after that nothing happened when i clicked again it didnt start but somehow now it works dont know why xD i tryd it for like half an hour ago and still had this issue now you answered and it works finaly

**Comment by okiehsch** [comment]
Maybe an issue with streamtape itself, if it happens again just post in this issue, no need to open a new one.
