### ISSUE TITLE
elespanol.com: detection

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#19247]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.elespanol.com/reportajes/20180802/miembro-manada-angel-boza-prision-intentar-gafas/327218135_0.html`

### Category

detection

### Description

Window shows up asking to disable uBlock Origin or to subscribe.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![FireShot Capture 006 - El miembro de La Manada Ángel Boza, a prisión tras intentar robar una_ - www elespanol com](https://github.com/uBlockOrigin/uAssets/assets/43375046/281e578d-c14c-40af-a4d8-9eb8f7cea984)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 100534
 cosmetic: 45486
 scriptlet: 18523
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69114-9, now
  easyprivacy: 33375-62, now
  plowe-0: 3717-1070, now
  spa-0: 3578-17, now
  spa-1: 5386-211, now
  ublock-badware: 7628-143, now
  ublock-filters: 34146-174, now
  ublock-privacy: 447-4, now
  ublock-quick-fixes: 325-103, now
  ublock-unbreak: 2108-36, now
  urlhaus-1: 6700-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1546 ms
 maxAssetCacheWait: 25 ms
popupPanel:
 blocked: 665
 network:
  1rx.io: 1
  2mdn.net: 8
  360yield.com: 9
  4dex.io: 4
  a-mo.net: 1
  adform.net: 3
  adgrx.com: 1
  adipolo.com: 6
  admanmedia.com: 1
  adnxs.com: 9
  adroll.com: 1
  adtelligent.com: 1
  amazon-adsystem.com: 19
  aniview.com: 18
  bidr.io: 2
  bidswitch.net: 1
  bidtheatre.com: 1
  bluekai.com: 3
  brainlyads.com: 2
  casalemedia.com: 6
  citiservi.es: 1
  creative-serving.com: 1
  creativecdn.com: 1
  criteo.com: 3
  criteo.net: 4
  crwdcntrl.net: 1
  cxense.com: 3
  demdex.net: 4
  doubleclick.net: 68
  eestatic.com: 1
  elasticad.net: 3
  everesttech.net: 2
  facebook.com: 2
  facebook.net: 2
  google-analytics.com: 22
  google.com: 31
  google.es: 3
  googleadservices.com: 2
  googlesyndication.com: 85
  googletagmanager.com: 5
  googletagservices.com: 14
  greeter.me: 2
  imasdk.googleapis.com: 19
  indexww.com: 2
  indigitall.com: 4
  insurads.com: 20
  jnxm2.com: 1
  lijit.com: 3
  loopme.me: 1
  melia.com: 1
  modoro360.com: 9
  newsroom.bi: 9
  npttech.com: 1
  omnitagjs.com: 1
  onetag-sys.com: 2
  openx.net: 2
  outbrain.com: 32
  outbrainimg.com: 14
  pghub.io: 3
  pubmatic.com: 7
  quantcount.com: 1
  quantserve.com: 3
  richaudience.com: 18
  rubiconproject.com: 10
  sascdn.com: 1
  scorecardresearch.com: 2
  seedtag.com: 17
  sensic.net: 10
  servg1.net: 5
  serving-sys.com: 31
  sharethrough.com: 1
  simpli.fi: 4
  smartadserver.com: 15
  smilewanted.com: 2
  spotxchange.com: 6
  sunmedia.tv: 17
  taboola.com: 1
  tiktok.com: 4
  tremorhub.com: 8
  unrulymedia.com: 1
  vidazoo.com: 6
  videoplaza.tv: 5
  yahoo.com: 2
  zemanta.com: 7
 extended:
  ###taboola-below-article-thumbnails
  ##.adv
  ##.adv_inline
  ##.article-adv
  ##.container__outbrain
  ##div[class^="article-inline"]
  ##.article-body__adv
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##[name^="google_ads_iframe"]
  ##div[data-google-query-id]
  #@#[id^="google_ads_iframe"]
  ##+js(set-constant, tieneAdblock, 0)
  ##a[href^="https://googleads.g.doubleclick.net/pcs/click"]
  ##.img_ad
  ##a[href^="https://adclick.g.doubleclick.net/"]
  ##.dcmads
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce.
With a non spanish IP the site works without issue on my end.
With a spanish IP I get a paywall.

<details>
<summary>Screenshot(s)</summary>


![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/68214c19-0eb7-497e-b6ff-d0f2f5d6bc30)

</details>

**Comment by gorhill** [comment]
Which exact browser are you using?

**Comment by okiehsch** [comment]
With a spanish IP?

**Comment by rodrigosambadesaa** [comment]
Yes, I'm Spanish.

**Comment by gorhill** [comment]
I see the same anomaly as the one [you reported here](https://github.com/uBlockOrigin/uAssets/issues/19138#issuecomment-1648028864), that is there is way more 3rd parties being blocked than what I would expect from using default settings/lists -- something which typically occurs when not blocking scripts which cause more 3rd-party scripts to be loaded.

I can't reproduce the issue and the behavior reported in troubleshooting information.
