### ISSUE TITLE
turkceyamaci.com: badware

### ISSUE THREAD

**Issue by tunceray1** [uBlockOrigin/uAssets#19242]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.turkceyamaci.com/`

### Category

ads- badware

### Description

This website distributes malware to users by placing viruses in Turkish language patch files. There are a lot of complaints about this website in various forums. A report sent to [AdGuard](https://github.com/AdguardTeam/AdguardFilters/issues/128762) 10 months ago resulted in the site being blacklisted by AdGuard. Please add it to the badware list.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 97788
 cosmetic: 127199
 scriptlet: 25796
 html: 1200
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  adguard-spyware-url: 1152-5, now
  adguard-social: 21035-160, now
  adguard-cookies: 26494-40, now
  adguard-popup-overlays: 23161-982, now
  adguard-other-annoyances: 13180-59, now
  adguard-widgets: 2227-1, now
  ublock-annoyances: 5277-10, now
 default:
  user-filters: 45-0, never
  ublock-filters: 35015-624, now
  ublock-badware: 7630-1, now
  ublock-privacy: 482-0, now
  ublock-unbreak: 2155-2, now
  ublock-quick-fixes: 326-0, now
  easylist: 69114-209, now
  easyprivacy: 33375-97, now
  TUR-0: 13598-12, now
filterset (user): [array of 54 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1173 ms (selfie)
 maxAssetCacheWait: 413 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by okiehsch** [comment]
In what list is it blocked by Adguard?

**Comment by iam-py-test** [comment]
Looks like malware to me:
https://tria.ge/230801-rxwkgagd45/behavioral1
https://www.virustotal.com/gui/file/6006d9cff2c3f472eeb4ca93ecf66a5e77014079508b6b0e75e1d58a0335ff62
Drops these:
https://www.virustotal.com/gui/file/44ea5818829a2a9c69274cfdcde623466f0734dd907dd2e2273256c48d27e761
https://www.virustotal.com/gui/file/3d71f4dd329a115945231bc5abf38a0171b2561181e92eb0bf465db4589e45ca

**Comment by iam-py-test** [comment]
Still behaves weird for cracked software, i.e. disabling Windows Defender

**Comment by okiehsch** [comment]
I am hesitant to block the site because if you look for cracked software you will get some malware infected files.
Should we block all of them?

**Comment by tunceray1** [comment]
@okiehsch I do not know this. AdGuard's malware filter is not public, so you won't find the list on Github. But if you visit this website with the AdGuard extension, you will see a warning like the one below.

`https://www.technopat.net/sosyal/konu/turkceyamaci-comu-sikayet-ettim-uzak-durun.1053241/post-16931054`

<details>

 <summary>Screen</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/140217932/9a3a2afb-386a-48c4-b355-9a62b2980d9d)


</details>


Additionally, reports on this site do not look like false positives. There are so many complaints that it actually contains viruses and malware. For proof, search using the `turkceyamaci.com site:technopat.net` cheat and see the results.

Apart from this, the site owner does not make any explanations to users for virus claims.

If you don't want to add it to the badware list, no problem.
