### ISSUE TITLE
[nsfw] scrolller.com: breakage

### ISSUE THREAD

**Issue by Pomptime** [uBlockOrigin/uAssets#19255]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Whenever certain filter rule is executed, after starting scrolling in NSFW mode, site page turns grey and it stops working. This seems to be related to certain filter rule found in Easylist and Adguard lists. 

`||a.a3ion.com/ad-provider.js$script,domain=scrolller.com`

It works as intended without it.

### URL(s) where the issue occurs.

`https://scrolller.com/`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/80183432/e183e95d-e780-47ac-8268-dd54206d4577)

![image](https://github.com/uBlockOrigin/uAssets/assets/80183432/e8df03b4-6360-4e06-89c1-6f48b3496a37)

### Notes

Disabling Adguard and Easylist filter lists containing `||a.a3ion.com/ad-provider.js$script,domain=scrolller.com` rule fixes the issue.

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 84043
 cosmetic: 74364
 scriptlet: 19961
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  urlhaus-1: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/1.txt: 25620-77, 2m
  RUS-0: 39685-3290, 2m
 default:
  user-filters: 97-2, never
  easylist: 69139-197, 2m
  plowe-0: 3717-401, 2m
  ublock-badware: 7645-143, 2m
  ublock-filters: 34147-186, 2m
  ublock-privacy: 447-4, 2m
  ublock-quick-fixes: 260-51, 2m
  ublock-unbreak: 2108-13, 2m
filterset (user): [array of 101 redacted]
trustedset:
 added: [array of 20 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 495 ms (selfie)
 maxAssetCacheWait: 201 ms
```
</details>

**Comment by okiehsch** [comment]
> starting scrolling in NSFW mode

How do I enable that mode?

**Comment by Pomptime** [comment]
Scroll down, then scroll up to make the bottom panel show up. Press "Filters" and check NSFW mode.

**Comment by okiehsch** [comment]
Thx.

**Comment by okiehsch** [comment]
@ryanbr 
`@@||a.a3ion.com/ad-provider.js$script,domain=scrolller.com`
works and I don't see any obvious ads on my end.

**Comment by Pomptime** [comment]
Thank you very much.

**Comment by ryanbr** [comment]
Page loads fine here, am I missing something?

**Comment by okiehsch** [comment]
It's only broken in NSFW mode.

> Scroll down, then scroll up to make the bottom panel show up. Press "Filters" and check NSFW mode.

**Comment by okiehsch** [comment]
Hm, I tested agiaain and now it works on my end without the exception.
@ryanbr seems like it was a site issue, my bad.
