### ISSUE TITLE
myanimelist.net: nuisance

### ISSUE THREAD

**Issue by CookieUndercover1212** [uBlockOrigin/uAssets#19258]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://myanimelist.net/anime.php?cat=0&q=&type=6&score=0&status=0&p=0&r=0&sm=0&sd=0&sy=0&em=0&ed=0&ey=0&c=&show=150`

### Category

nuisance

### Description

There's an overlay in the MAl anime search that I've tried to get rid of using the zapper and the element picker, however it doesn't work. Even if it works for one entry, I hover over another and it pops up again. Sometimes, the text or bubble will still appear, sometimes if it's completely gone, the title for the entry will disappear with it, too. I tried applying this to the plugin [https://userstyles.world/api/style/8477.user.css](url), but it flags the empty curly brackets as invalid filters. I don't think the code was meant to be used as a filter, but I tried it anyway. I've verified that this happens in default.

### Other extensions used

I tried using Dark Reader to fix the issue, but that also didn't work.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/133927839/634b0820-9ff1-4194-8547-98ea6cde2ca5)

</details>

Sorry, idk how to drag and drop the image, this is what the overlay looks like

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 49d.16h.53m
Firefox: 115
filterset (summary):
 network: 98213
 cosmetic: 39550
 scriptlet: 18148
 html: 1013
listset (total-discarded, last-updated):
 default:
  user-filters: 23-1, never
  ublock-filters: 35027-144, 28m
  ublock-badware: 7630-1, 26m
  ublock-privacy: 482-0, 3d.21h.40m
  ublock-unbreak: 2153-1, 27m
  easylist: 69126-704, 3d.2m
  easyprivacy: 33363-723, 16h.37m
  urlhaus-1: 6801-0, 4h.29m
  plowe-0: 3717-2, 4d.1h.41m
  ublock-quick-fixes: 331-0, 6h.30m
filterset (user): [array of 105 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2288 ms (selfie)
 maxAssetCacheWait: 345 ms
popupPanel:
 blocked: 7
 network:
  myanimelist.net: 2
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagservices.com: 1
  unblockia.com: 2
 extended:
  ##[data-koukoku-width]:remove()
```
</details>

**Comment by okiehsch** [comment]
You can use `myanimelist.net##+js(aeld, mouseover, void)`
We won't fix that in a list, it's part of the website functionality.
