### ISSUE TITLE
oldbotprotect.pages.dev: popups

### ISSUE THREAD

**Issue by Magikfred** [uBlockOrigin/uAssets#19254]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://oldbotprotect.pages.dev/`

### Category

popups

### Description

A website which redirects you to malicious 'winner' pages

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 98196
 cosmetic: 39576
 scriptlet: 18132
 html: 1013
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35027-199, 1m
  ublock-badware: 7647-2, now
  ublock-privacy: 482-0, now
  ublock-unbreak: 2155-0, now
  ublock-quick-fixes: 260-0, now
  easylist: 69139-560, now
  easyprivacy: 33363-760, 1h.53m
  urlhaus-1: 6801-0, now
  plowe-0: 3717-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4403 ms (selfie)
 maxAssetCacheWait: 189 ms
popupPanel:
 blocked: 1
 network:
  jsdelivr.net: 1
```
</details>

**Comment by okiehsch** [comment]
We need the site that redirected you to `oldbotprotect.pages.dev`, i.e. where did you encounter the popup?
