### ISSUE TITLE
tvnow.de changed to plus.rtl.de

### ISSUE THREAD

**Issue by Acursen** [uBlockOrigin/uAssets#19256]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I just wanted to let you know that the URL for RTL's streaming service has changed. It used to be `tvnow.de` and is now `plus.rtl.de`. If you enter the former, you will be redirected.

There seem to be special filters for rtl.de, but I don't know if they will interfere now. At least filters for `tvnow.de` should be obsolete. The link below is a series that is free for everyone if you want to verify existing filters (after you interact with the consent banner).

### URL(s) where the issue occurs.

`https://plus.rtl.de/video-tv/serien/naruto-740021/staffel-1-740022/episode-1-wer-ist-naruto-740031`

### uBO version

1.51.0

### Browser name and version

Firefox 116.0

### Settings

Default settings

**Comment by okiehsch** [comment]
Thx for the heads up, I will remove all `tvnow.de` filters.

I don't see any ads on the link you provided, so I don't think any additional filters are necessary.
