### ISSUE TITLE
paylaterin.com: nuisance

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#19251]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.paylaterin.com/bni-mobile-banking-error-304/`

### Category

nuisance

### Description

1. Opening the developer tools will trigger a debugger statement.
2. Scrolling is locked on the page, seems related to the non-dismissable ad banner leftover.
3. The page manipulates browsing history by inserting referral links using `history.pushState()`, observable by navigating back from the site.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1b6
Firefox: 115
filterset (summary):
 network: 98154
 cosmetic: 39575
 scriptlet: 18143
 html: 1013
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35012-41, 2m
  ublock-badware: 7632-1, 2m
  ublock-privacy: 482-0, 2m
  ublock-unbreak: 2155-1, 2m
  ublock-quick-fixes: 325-97, 2m
  easylist: 69139-275, 2m
  easyprivacy: 33346-85, 2m
  urlhaus-1: 6801-0, 2m
  plowe-0: 3717-1072, 1m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 708 ms
 maxAssetCacheWait: 479 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test if this filter works and does it break anything on that site?

```adb
paylaterin.com##+js(aost, decodeURIComponent, autoptimize)
```

**Comment by partingscientist** [comment]
The filters seems to solve all three issues. I cannot find any obvious breakage with the site while browsing on it.
