### ISSUE TITLE
beacon.paloaltonetworks.com: breakage

### ISSUE THREAD

**Issue by theLegalPirate** [uBlockOrigin/uAssets#19253]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://beacon.paloaltonetworks.com/student/collection/666206/path/1858532`

### Category

breakage

### Description

All the course web pages inside the palo alto beacon website do not load into the final course content webpage. It gets stuck at the loading screen where I see a loading icon rolling forever.

### Other extensions used

privacy badger, but it is not causing the issue. If I turn off the Ublock origin adblocker, the web page loads as normal .

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

![image](https://github.com/uBlockOrigin/uAssets/assets/141173767/f6d414ee-1738-4318-b10f-b8fa01c4d78b)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 114
filterset (summary):
 network: 313127
 cosmetic: 226918
 scriptlet: 42061
 html: 1199
listset (total-discarded, last-updated):
 added:
  https://fanboy.co.nz/fanboy-annoyance.txt: 76513-76512, now
  https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt: 39612-39612, now
  adguard-generic: 72861-6489, now
  adguard-mobile: 8450-107, now
  adguard-spyware: 62223-17255, now
  block-lan: 48-0, now
  curben-pup: 199-0, now
  adguard-social: 21047-833, now
  adguard-cookies: 26508-57, now
  adguard-popup-overlays: 23188-1462, now
  adguard-mobile-app-banners: 4464-1056, now
  adguard-other-annoyances: 13187-298, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35027-470, now
  ublock-badware: 7647-1, now
  ublock-privacy: 482-0, now
  ublock-unbreak: 2155-1, now
  ublock-quick-fixes: 260-0, now
  easylist: 69139-871, now
  adguard-spyware-url: 1154-5, now
  easyprivacy: 33346-822, now
  urlhaus-1: 6801-0, now
  curben-phishing: 138848-58, now
  plowe-0: 3717-2, now
  LegitimateURLShortener: 2248-145, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 519 ms (selfie)
 maxAssetCacheWait: 296 ms
popupPanel:
 blocked: 8
 network:
  paloaltonetworks.com: 1
  adobedtm.com: 2
  demandbase.com: 1
  demdex.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
```
</details>

**Comment by okiehsch** [comment]
You have 21 additional filter lists enabled but ticked 
` I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.`
why?

**Comment by theLegalPirate** [comment]
> You have 21 additional filter lists enabled but ticked ` I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.` why?

ahh, to be honest, I didn't know I had additional filters. Just wanted to figure this issue and be helpful.

**Comment by okiehsch** [comment]
>  I didn't know I had additional filters. Just wanted to figure this issue and be helpful.

OK, can you check if the site is still broken after you disabled all additional filter lists?
I can't access the site.

**Comment by theLegalPirate** [comment]
> OK, can you check if the site is still broken after you disabled all additional filter lists?
I am so sorry. I am a noob. How do I disable all the additional filter lists that I have added ? I cannot find an option in my uBlock settings.

> I can't access the site.
Its a free to register and use site. You can just sign up for a new customer registration and start using the website within 2 mins.

> By the way why did you enable so many lists, did somebody tell you to?
Months ago, I was reading through r/piracy and their megathread suggested to have some optimized settings for uBlock and I followed that...

**Comment by stephenhawk8054** [comment]
I accessed your link and it shows this without any error: https://github.com/uBlockOrigin/uAssets/assets/66517106/26f669e8-29de-4f9d-a3d0-c315e1cf6a43

What should I do next?

---

> privacy badger, but it is not causing the issue. If I turn off the Ublock origin adblocker, the web page loads as normal .

Please don't test extensions conflict by turning off the target extension. The correct way is turning off all other extensions and only let 1 to run.

**Comment by okiehsch** [comment]
> How do I disable all the additional filter lists that I have added ? I cannot find an option in my uBlock settings.


Read https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists

If you don't know how to disable them, how did you enable them?
