### ISSUE TITLE
Endless loop at facebook.com

### ISSUE THREAD

**Issue by Maryse47** [uBlockOrigin/uAssets#19269]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When _uBlock filters – Annoyances_ is enabled the www.facebook.com enters in endless loop (site refreshes forever without showing any content).

This is caused by `facebook.com##+js(trusted-set-cookie, datr, __GMZCgwVF5BbyvAtfJojQwg, 1year, , reload, 1)` rule

### URL(s) where the issue occurs.

`www.facebook.com`

### uBO version

1.51.0

### Browser name and version

Firefox 116

### Settings

Subscribe to _uBlock filters – Annoyances_

**Comment by JobcenterTycoon** [comment]
Works fine for me. Are you logged in?

**Comment by Maryse47** [comment]
No, I'm not.

**Comment by Maryse47** [comment]
It somehow fixed itself.
