### ISSUE TITLE
benjaminphamchannel.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1926]
URL(s) where the issue occurs

`https://www.benjaminphamchannel.com/`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9dd2aef2963241205fc44cbeb756bc5cbe53dddc
