### ISSUE TITLE
5min.at: ads

### ISSUE THREAD

**Issue by haansn08** [uBlockOrigin/uAssets#19265]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.5min.at/202308689136/kompletter-busverkehr-in-klagenfurt-wird-umgestellt/`

### Category

ads

### Description

the website shows ads

### Other extensions used

none.
your checklist above is very difficult to verify on a mobile Firedox btw.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 115
filterset (summary):
 network: 103707
 cosmetic: 44982
 scriptlet: 18364
 html: 1015
listset (total-discarded, last-updated):
 added:
  DEU-0: 7014-404, now
  JPN-1: 12928-161, now
 default:
  user-filters: 2-0, never
  ublock-filters: 35335-358, now
  ublock-badware: 7647-2, now
  ublock-privacy: 482-1, now
  ublock-unbreak: 2158-1, now
  adguard-mobile: 8465-120, now
  easylist: 69243-17239, now
  easyprivacy: 33319-760, now
  urlhaus-1: 6695-0, now
  plowe-0: 3717-1, now
  ublock-quick-fixes: 264-0, now
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 983 ms (selfie)
 maxAssetCacheWait: 359 ms
popupPanel:
 blocked: 11
 network:
  cloudflareinsights.com: 2
  facebook.net: 1
  googleadservices.com: 2
  googlesyndication.com: 4
  googletagmanager.com: 1
  taboola.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by ghajini** [comment]
try unchecking **ignore generic cosmetic filters** from filter list settings

**Comment by haansn08** [comment]
If I uncheck "ignore generic cosmetic filters" and reload the page, the ads disappear.
