### ISSUE TITLE
animesuge.to: nuisance

### ISSUE THREAD

**Issue by monark1234567894** [uBlockOrigin/uAssets#19260]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animesuge.to/`

### Category

nuisance

### Description

This pop up ad keeps coming up whenever I try to pause or play. This issue started this week only

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="960" alt="Screenshot 2023-08-02 190755" src="https://github.com/uBlockOrigin/uAssets/assets/110911113/3ae952fa-6feb-4344-b173-3632f8de8602">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 98045
 cosmetic: 39584
 scriptlet: 18181
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69141-9, now
  easyprivacy: 33318-62, now
  plowe-0: 3717-1070, now
  ublock-badware: 7648-143, now
  ublock-filters: 34147-145, now
  ublock-privacy: 447-4, now
  ublock-quick-fixes: 257-50, now
  ublock-unbreak: 2106-33, now
  urlhaus-1: 6695-0, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 476 ms (selfie)
 maxAssetCacheWait: 212 ms
popupPanel:
 blocked: 11
 network:
  amung.us: 1
  bidgear.com: 5
  disqus.com: 1
  rezync.com: 1
  sharethis.com: 2
  wistfulcomet.com: 1
 extended:
  ##.adx
  ##+js(abort-on-stack-trace, document.createElement, _0x)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, mm)
  ##+js(no-setInterval-if, break)
  ##+js(no-window-open-if, !api?call=, 10, obj)
```
</details>

**Comment by ghajini** [comment]
ok i got that ad on mycloud player too, fixed that
