### ISSUE TITLE
nationaltoday.com: nuisance

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#19274]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Some content will be unloaded until you scroll because of a Cloudflare JavaScript code.
`||cdnjs.cloudflare.com/ajax/libs/ScrollMagic/`

### URL(s) where the issue occurs.

`https://nationaltoday.com/birthday/satoru-iwata/`

### uBO version

v1.51.1b7

### Browser name and version

Firefox 116.0

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by okiehsch** [comment]
> Some content will be unloaded until you scroll 

We don't fix that kind of issues.
