### ISSUE TITLE
indiatoday.in: ads

### ISSUE THREAD

**Issue by sheikh-azharuddin** [uBlockOrigin/uAssets#19275]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.indiatoday.in/binge-watch/reviews/story/dayaa-review-jd-chekravarthy-is-the-star-of-this-thriller-thats-stretched-in-parts-2416213-2023-08-04`

### Category

ads

### Description

Cosmetic filtering is not working not only in the page but other webpages ..it always shows the ads placeholder

Device: Android
App: firefox

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_2023-08-05-08-57-08-022_org mozilla firefox_beta-edit](https://github.com/uBlockOrigin/uAssets/assets/58127841/87c073db-a31e-411f-a994-7f0ef9ff97ce)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 117
filterset (summary):
 network: 101734
 cosmetic: 52926
 scriptlet: 18429
 html: 1014
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 26523-1589, now
 default:
  user-filters: 0-0, never
  ublock-filters: 35334-333, now
  ublock-badware: 7686-2, now
  ublock-privacy: 482-1, now
  ublock-unbreak: 2159-1, now
  ublock-quick-fixes: 290-0, now
  adguard-mobile: 8483-119, now
  easylist: 69440-17227, now
  easyprivacy: 33320-726, now
  urlhaus-1: 6821-0, now
  plowe-0: 3716-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 731 ms (selfie)
 maxAssetCacheWait: 171 ms
popupPanel:
 blocked: 23
 network:
  adblock-tester.com: 1
  chartbeat.com: 1
  crazyegg.com: 1
  doubleclick.net: 3
  facebook.net: 1
  google-analytics.com: 1
  google.com: 2
  googleoptimize.com: 1
  googletagmanager.com: 3
  hotjar.com: 1
  izooto.com: 2
  pubmatic.com: 1
  scorecardresearch.com: 1
  tosshub.com: 2
  youtube.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(json-prune, playerResponse.adPlacements playerResponse.pl…
```
</details>

**Comment by ghajini** [comment]
go to ublock origin settings=> filter lists=> untick **ignore generic cosmetic filters**

**Comment by sheikh-azharuddin** [comment]
> go to ublock origin settings=> filter lists=> untick **ignore generic cosmetic filters**

Thanks it worked but when reloading the page for a brief sec I see that advertisement element..in other adbblocker like adblock plus and adblocker ultimate, I don't see it i.e. while page loads itself it is getting blocked
