### ISSUE TITLE
eurosport.com: ads

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#19272]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

the websites tries to load ads in the "ad-spaces", replacing with images after a few seconds

### URL(s) where the issue occurs.

```
https://www.eurosport.com/
https://www.eurosport.de/
https://www.eurosport.nl/
https://www.eurosport.es/
https://www.eurosport.fr/
https://www.eurosport.it/
https://www.tntsports.co.uk/
https://www.eurosport.hu/
https://www.eurosport.no/
https://eurosport.tvn24.pl/
https://www.eurosport.ro/
https://www.eurosport.com.tr/
```

### uBO version

1.51.0

### Browser name and version

Chrome

### Settings

```
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 101129
 cosmetic: 46984
 scriptlet: 22088
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5319-7, 2h.15m
 default:
  user-filters: 1-0, never
  easylist: 69271-9, 2h.15m
  easyprivacy: 33319-62, 2h.15m
  plowe-0: 3717-1070, 2h.15m
  spa-0: 3641-18, 2h.15m
  spa-1: 5388-219, 2h.15m
  ublock-badware: 7679-143, 2h.15m
  ublock-filters: 34140-176, 2h.15m
  ublock-privacy: 447-4, 2h.15m
  ublock-quick-fixes: 260-32, 2h.15m
  ublock-unbreak: 2106-36, 2h.15m
  urlhaus-1: 6843-0, 2h.15m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 256 ms (selfie)
 maxAssetCacheWait: 104 ms
```

**Comment by okiehsch** [comment]
Does
`eurosport.*##.banner-sponsorship`
work for all domains?

**Comment by okiehsch** [comment]
@ryanbr 
````
eurosport.*##.ad
eurosport.*##.banner-sponsorship
````
