### ISSUE TITLE
connect.garmin.com: breakage

### ISSUE THREAD

**Issue by geieraffe** [uBlockOrigin/uAssets#19270]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://connect.garmin.com/`

### Category

breakage

### Description

website doesn't load the side panels for navigation

### Other extensions used

all other extensions deactivated

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 101706
 cosmetic: 44244
 scriptlet: 18139
 html: 1015
listset (total-discarded, last-updated):
 added:
  https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 1104-0, never
  https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
 default:
  user-filters: 3-0, never
  ublock-filters: 35022-190, now
  ublock-badware: 7681-2, now
  ublock-privacy: 482-0, now
  ublock-unbreak: 2153-0, now
  easylist: 69281-569, 2m
  easyprivacy: 33319-769, 2m
  plowe-0: 3717-1, now
  DEU-0: 7014-3, 2m
  urlhaus-1: 6741-0, 2m
  ublock-quick-fixes: 275-0, 2m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 10 redacted]
 removed:
  about-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2666 ms
 maxAssetCacheWait: 308 ms
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  sentry.io: 2
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need to sign in?

**Comment by geieraffe** [comment]
holy moly you are fast. 2 days with no feedback => closing?

Yes it is a webpage where you need to sign in, but due to cookies I already was signed in.
Still signed in, but not seeing the sidebars with activated uBlock.

**Comment by stephenhawk8054** [comment]
Hmmm... I created an account with it and I see this when logged in: https://github.com/uBlockOrigin/uAssets/assets/66517106/bd6f64d0-58b1-4796-b2b6-83df1b82247d

Which exactly is missing here in the screenshot? I don't see any differences when turning on and turning off uBO.

---

```yml
added:
  https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 1104-0, never
```

Can you remove this list and test again?
