### ISSUE TITLE
animesaga.in: popups

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#19271]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.animesaga.in/`

### Category

popups

### Description

Video not playing

### Other extensions used

Violentmonkey 
Libredirect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 115
filterset (summary):
 network: 99743
 cosmetic: 30042
 scriptlet: 18173
 html: 1016
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35324-324, 1h.2m
  ublock-badware: 7675-2, 1h
  ublock-privacy: 482-1, now
  ublock-unbreak: 2158-1, 59m
  ublock-quick-fixes: 261-0, now
  adguard-mobile: 8472-120, now
  easylist: 69271-17220, now
  easyprivacy: 33319-727, now
  urlhaus-1: 6843-0, now
  plowe-0: 3717-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14220 ms
 maxAssetCacheWait: 1195 ms
popupPanel:
 blocked: 7
 network:
  a-ads.com: 2
  gmxvmvptfm.com: 1
  googletagmanager.com: 2
  rkgwzfwjgk.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can only reproduce the popup, videos play fine for me

**Comment by dportvine** [comment]
Blocked `devdevtools` & `right-click`

`https://161.97.70.5/movie/spider-man-into-the-spider-verse`

<details>
<summary>Screen</summary>

![2023-08-04_072537](https://github.com/uBlockOrigin/uAssets/assets/111344219/d48738d8-48f2-42c5-b379-21d1399a4031)
</details>

**Comment by ghajini** [comment]
try 
```
161.97.70.5##+js(acs, check, debugger)
161.97.70.5##+js(aeld, contextmenu, preventDefault)
161.97.70.5##+js(aeld, keydown, disabledEvent)
```

**Comment by stephenhawk8054** [comment]
I think

```adb
161.97.70.5##+js(rmnt, script, isadb)
```

is enough?

**Comment by dportvine** [comment]
> I think
> 
> ```
> 161.97.70.5##+js(rmnt, script, isadb)
> ```
> 
> is enough?

Yes, it works.

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/commit/72352a71e617870a7b3baf09e559d71c801c9cdc
