### ISSUE TITLE
[nsfw] best.aliexpress.com: popups

### ISSUE THREAD

**Issue by ddark2** [uBlockOrigin/uAssets#19276]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://best.aliexpress.com/?af=8eawk23ouh5u&dp=des&aff_fcid=cfb8be2ecd6041e7b4ccb3da094580f9-1691243027225-08672-_Dn48ngz&tt=CPS_NORMAL&aff_fsk=_Dn48ngz&aff_platform=portals-tool&sk=_Dn48ngz&aff_trace_key=cfb8be2ecd6041e7b4ccb3da094580f9-1691243027225-08672-_Dn48ngz&terminal_id=0e0d43454ddc42038d9fd26ffc647d04`

### Category

popups

### Description

> Esse filtro/site é uma porcaria e aparece sozinho incomodando as pessoas 

**This filter/site sucks and just pops up and bothers people**

### Other extensions used

adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 99871
 cosmetic: 43170
 scriptlet: 18540
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 69383-9, 1h.17m
  easyprivacy: 33320-62, 1h.17m
  plowe-0: 3716-1069, 1h.16m
  spa-1: 5404-68, 1h.17m
  ublock-badware: 7690-143, 1h.16m
  ublock-filters: 34154-174, 1h.16m
  ublock-privacy: 447-4, 1h.16m
  ublock-quick-fixes: 288-36, 1h.16m
  ublock-unbreak: 2107-34, 1h.16m
  urlhaus-1: 6821-0, 1h.16m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2963 ms
 maxAssetCacheWait: 49 ms
popupPanel:
 blocked: 0
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
```
</details>

**Comment by gorhill** [comment]
> popups

Please better explain what is the issue, it's not clear what you want us to look at.

> adblock

Don't use other content blocker along uBO.

**Comment by gorhill** [comment]
Closing as _invalid_ for now until better report is provided along with proper prerequisite steps.
