### ISSUE TITLE
w.atwiki.jp: nuisance

### ISSUE THREAD

**Issue by D25SK** [uBlockOrigin/uAssets#19285]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

> 日本語での回答お願いします。

**Please answer in Japanese.**
Japanese reply please.

> フリーズして閲覧不能になる。(CPU使用率が100に張り付く)
uboをオフにすると見える。

**Freezes and becomes unreadable. (CPU usage stuck at 100)
You can see it when ubo is turned off.**

### URL(s) where the issue occurs.

`https://w.atwiki.jp/gtav/pages/2717.html`

### uBO version

1.51.0

### Browser name and version

Chrome 115

### Settings

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 84937
 cosmetic: 119107
 scriptlet: 39349
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69672-101, 1d.18h.51m
  adguard-generic: 72969-481, 1d.18h.51m
  ublock-annoyances: 5318-204, 3d.19h.10m
 default:
  user-filters: 217-6, never
  JPN-1: 12943-13, 1d.18h.51m
  easyprivacy: 33320-196, 1d.19h.17m
  plowe-0: 3717-714, 4d.19h.15m
  ublock-badware: 7679-264, 1d.18h.51m
  ublock-filters: 34144-4045, 1d.18h.51m
  ublock-privacy: 447-2, 3d.19h.10m
  ublock-quick-fixes: 277-13, 3h.19m
  ublock-unbreak: 2106-85, 1d.18h.51m
  urlhaus-1: 6821-0, 17h.34m
filterset (user): [array of 207 redacted]
trustedset:
 added: [array of 16 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings:
 autoUpdateAssetFetchPeriod: 180
 autoUpdatePeriod: 4
 extensionUpdateForceReload: true
 manualUpdateAssetFetchPeriod: 1
 popupPanelLockedSections: 39
supportStats:
 allReadyAfter: 1150 ms (selfie)
 maxAssetCacheWait: 543 ms
```

**Comment by krystian3w** [comment]
Check on disabled `adguard-generic` to disable glitches in JS scriptlet injections or redirects or any other by block something in diffrent method incompatible with uBo for now.

**Comment by Yuki2718** [comment]
Yeah, please narrow down the cause by disabling filter lists one by one, although I can't reproduce with AdGuard - Ads enabled.

**Comment by gorhill** [comment]
We can't reproduce and as per OP's troubleshooting, the configuration is heavily customized, including _EasyList_ being disabled.

**Comment by D25SK** [comment]
adguard Japaneseが起因でした。
w.atwiki.jp##.atwiki-ads-pc-overlay
(広告枠の残骸)
をブロックしているとフリーズを引き起こすようです。
一時的にオフにします。

> Yeah, please narrow down the cause by disabling filter lists one by one, although I can't reproduce with AdGuard - Ads enabled.
> 
> > 日本語での回答お願いします。
> 
> フィルターリストを一つずつ無効にして、その都度現象を確認し原因を絞り込むことは可能ですか?

**Comment by D25SK** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/158054
Here's a adguard's issue report of that element filter.
（that blocks DIV's class. But also can block on DIV's ID "atwiki-ads-overlay")

adguardのレポートURLです。
classでブロックするアプローチですが、IDでもブロック可能かと思われます。

**Comment by krystian3w** [comment]
Check these:

```adb
w.atwiki.jp#@#.atwiki-ads-pc-overlay
w.atwiki.jp#@#.atwiki-ads-overlay
w.atwiki.jp##.atwiki-ads-pc-overlay:remove()
w.atwiki.jp##.atwiki-ads-overlay:remove()
```

later:

```adb
w.atwiki.jp#@#.atwiki-ads-pc-overlay
w.atwiki.jp#@#.atwiki-ads-overlay
w.atwiki.jp##.atwiki-ads-pc-overlay:style(visibility: hidden !important;)
w.atwiki.jp##.atwiki-ads-overlay:style(visibility: hidden !important;)
```

**Comment by D25SK** [comment]
Disable adguard JP filter + this works!
Thank you!!
(and restored to default settings. sorry gorhill.)

> Check these:
> 
> ```
> w.atwiki.jp#@#.atwiki-ads-pc-overlay
> w.atwiki.jp#@#.atwiki-ads-overlay
> w.atwiki.jp##.atwiki-ads-pc-overlay:remove()
> w.atwiki.jp##.atwiki-ads-overlay:remove()
> ```
> 
> later:
> 
> ```
> w.atwiki.jp#@#.atwiki-ads-pc-overlay
> w.atwiki.jp#@#.atwiki-ads-overlay
> w.atwiki.jp##.atwiki-ads-pc-overlay:style(visibility: hidden !important;)
> w.atwiki.jp##.atwiki-ads-overlay:style(visibility: hidden !important;)
> ```

**Comment by krystian3w** [comment]
Deactivating the well-developed Japanese list when frequently browsing from that region is a rather bad solution.



If a simple deactivation of the filter works:

```adb
w.atwiki.jp#@#.atwiki-ads-pc-overlay
w.atwiki.jp#@#.atwiki-ads-overlay
```


then it is better to leave the regional filters enabled.

Until someone figures out how to gently cut out the ad/remainder or inactivate a bug in the site's code to keep it running smoothly.

**Comment by D25SK** [comment]
Not needed disabling adguard.
ADG+below:

w.atwiki.jp#@#.atwiki-ads-pc-overlay
w.atwiki.jp#@#.atwiki-ads-overlay
w.atwiki.jp##.atwiki-ads-pc-overlay:remove()
w.atwiki.jp##.atwiki-ads-overlay:remove()
w.atwiki.jp#@#.atwiki-ads-pc-overlay
w.atwiki.jp#@#.atwiki-ads-overlay
w.atwiki.jp##.atwiki-ads-pc-overlay:style(visibility: hidden !important;)
w.atwiki.jp##.atwiki-ads-overlay:style(visibility: hidden !important;)

That's work fine. Thanks!

**Comment by krystian3w** [comment]
Since deleting an item works then you can deactivate the last two filters with another method of hiding items.

**Comment by Yuki2718** [comment]
> Check these:
> 

I only see `###atwiki-ads-overlay` in Japanese filters and still unable to reproduce, not even see relatively high-CPU usage.

@D25SK 以下だけで試していただけますか？また、念のためそれを削除すると減少が再発することの確認もお願いいたします。
```
w.atwiki.jp#@##atwiki-ads-overlay
w.atwiki.jp###atwiki-ads-overlay:remove()
```

**Comment by D25SK** [comment]
@Yuki2718 その2行でも問題ないことを確認しました。
逆にその2行削除するとやはり再発します。

なお、症状としては「リクエストを処理しています…」もしくは「w.atwiki.jpを待機しています…」のまま固まり、テキストの選択・コピーができず、最終的にページが応答していませんのダイアログが出ます(約1分ほど?かかります。)
