### ISSUE TITLE
plenterfarm.com / bmupdate.servehalflife.com : Scam

### ISSUE THREAD

**Issue by davidebangelista** [uBlockOrigin/uAssets#19281]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [x] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Some phishing URLs used to gain credentials was recently found on SMS.

Currently not being filtered out by Pi-Hole and UBO.

### URL(s) where the issue occurs.

`https://plenterfarm.com`
`http://bmupdate.servehalflife.com`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/50121702/357b9201-1aa8-4644-ba52-056394e3d6a3)
![image](https://github.com/uBlockOrigin/uAssets/assets/50121702/25146ea8-2e39-4724-b604-ad23b331b5f4)

### uBO version

1.51.0

### Browser name and version

Firefox (ESR) / 102.14.0esr-1~deb12u1 [Debian 12]

### Settings

- None

**Comment by stephenhawk8054** [comment]
`plenterfarm.com` shows 404 error for me: https://github.com/uBlockOrigin/uAssets/assets/66517106/06764361-1558-4347-8bff-6934bde4ef45

**Comment by davidebangelista** [comment]
> `plenterfarm.com` shows 404 error for me: https://github.com/uBlockOrigin/uAssets/assets/66517106/06764361-1558-4347-8bff-6934bde4ef45
> 
> 

Looks like it's also down on my end, closing.
