### ISSUE TITLE
August 2023: YouTube Video Player Issues

### ISSUE THREAD

**Issue by Herobrine100x** [uBlockOrigin/uAssets#19294]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

YouTube has been blocking Ad Blockers lately, and uBlock Origin seems to be one of their latest victims. Between YouTube Revanced's video player breaking again and this, it makes it impossible to watch videos w/o ads without giving YouTube money.

### URL(s) where the issue occurs.

https://youtube.com

### uBO version

1.51.0

### Browser name and version

Firefox Mobile v116.0

### Settings

None

**Comment by stephenhawk8054** [comment]
Are you using any extensions or apps that can affect browsers?

**Comment by stephenhawk8054** [comment]
But anyway, please continue here: https://github.com/uBlockOrigin/uAssets/issues/7636
