### ISSUE TITLE
turkishaudiocenter.com: detection

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#19291]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.turkishaudiocenter.com/categories/t%C3%BCrk%C3%A7e-ses-dosyalar%C4%B1-platformu.1/`

### Category

detection

### Description

aab

### Other extensions used

dark reader, fastforward, violentmonkey w/adguard popup blocker installed in it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScre22enshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/02e42311-1061-4d57-a05c-3bbd4996e9be)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 157116
 cosmetic: 136413
 scriptlet: 26804
 html: 1200
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  plowe-0: null
 added:
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_1_Russian/filter.txt: 25684-107, 1h.20m
  https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt: 1051-0, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/fake.txt: 15887-975, now
  adguard-spyware-url: 1155-5, now
  adguard-spyware: 62182-360, now
  block-lan: 48-0, now
  easylist-annoyances: 3884-91, 1m
  easylist-chat: 132-0, 1m
  fanboy-cookiemonster: 48032-184, 1m
  easylist-newsletters: 6317-13, 1m
  easylist-notifications: 2637-3, 1m
  fanboy-social: 16135-6, 1m
  [2 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35037-111, now
  ublock-badware: 7628-7, now
  ublock-privacy: 482-0, now
  ublock-unbreak: 2154-1, now
  ublock-quick-fixes: 285-0, now
  easylist: 69480-543, now
  urlhaus-1: 6858-0, now
  TUR-0: 13667-12, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 657 ms
 maxAssetCacheWait: 393 ms
popupPanel:
 blocked: 2
 network:
  turkishaudiocenter.com: 2
 extended:
  ##.shareButtons
  ##.shareButtons-buttons
  ##.shareButtons-button
  ##.p-footer-rssLink
  ##.js-notice.notice--cookie
  ##.u-scrollButtons
```
</details>

**Comment by Yuki2718** [comment]
They fixed the site in Base so we need our own.
