### ISSUE TITLE
cliver.tv [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1929]
URL(s) where the issue occurs

`http://www.cliver.tv/pelicula/jigsaw/`

Describe the issue

![](https://i.imgur.com/Vrv3ujq.png)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by KiLL4FuNK** [comment]
Pop-up

**Comment by lain566** [comment]
Popup when click anywhere.

**Comment by lain566** [comment]
Popup and FB again
`http://www.cliver.tv/pelicula/shazam/`

**Comment by lain566** [comment]
That fixed the fake button here `http://www.cliver.tv/pelicula/shazam/`

but it still appears here `http://www.cliver.tv/pelicula/jigsaw/`

There is still a popup.

**Comment by lain566** [comment]
The website has changed domain to `cliver.to`
