### ISSUE TITLE
twitterperlen.de: breakage

### ISSUE THREAD

**Issue by ASDBigmac** [uBlockOrigin/uAssets#19299]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.twitterperlen.de/die-twitterperlen-des-tages-vom-7-august-2023/`

### Category

breakage

### Description

No scrolling possible on the full site starting today -> everything was working yesterday

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 101156
 cosmetic: 44264
 scriptlet: 18214
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 20-1, never
  DEU-0: 7014-0, now
  easylist: 69810-16, now
  easyprivacy: 33280-73, now
  plowe-0: 3716-1070, now
  ublock-badware: 7670-146, now
  ublock-filters: 34170-189, now
  ublock-privacy: 447-4, now
  ublock-quick-fixes: 269-33, 55m
  ublock-unbreak: 2105-35, now
  urlhaus-1: 6852-0, now
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 39 redacted]
 removed:
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2810 ms
 maxAssetCacheWait: 1366 ms
popupPanel:
 blocked: 6
 network:
  cdntrf.com: 2
  cleverpush.com: 1
  d2wu036mkcz52n.cloudfront.net: 2
  googletagmanager.com: 1
 extended:
  ##.needsclick
```
</details>

**Comment by okiehsch** [comment]
>everything was working yesterday

Maybe because you added
`##.needsclick`
to your personal filter list?

**Comment by gorhill** [comment]
> Maybe because you added
> `##.needsclick`

Confirmed, self-inflicted issue which would have spotted had the following step been answered truthfully:

> - [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
