### ISSUE TITLE
health.harvard.edu: nuisance

### ISSUE THREAD

**Issue by dis-guisekaylee** [uBlockOrigin/uAssets#19292]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.health.harvard.edu/topics/depression/all?page=2`

### Category

nuisance

### Description

There's a popup that says something like "Thanks for visiting, claim your free offer" that shows up frequently, though not with every page change or refresh.

There's a bottom popup banner for signing up for their newsletter. It comes back whenever the page changes or refreshes.

I would imagine this occurs on all the health topic/article pages.

In addition to the above checklist I tried:
- using the element zapper; when the page changes or changes enough times the popups will reappear
- additional, optional annoyance filters (AdGuard, EasyList, and uBlock) however I left the social media filters for AdGuard and EasyList and the chat widget filter for EasyList toggled off 
- toggling the "Block all popups" and "Block large media elements" options

### Other extensions used

Accessibility Insights for Web
Bitmoji
Chrome Web Store Launcher (by Google)
Clozoom
ColorZilla
Dark Reader
Deadname-B-Gon
File Converter - By Online-Convert.com
Free Screen Recorder for Chrome
GIPHY for Gmail
Google Dictionary (by Google)
Google Docs Offline
Google Input Tools
Google Translate
Google Voice (by Google)
IBA Opt-out (by Google)
InteractiveFics
Mindful Break
Office Editing for Docs, Sheets, & Slides
PayPal Honey: Automatic Coupons & Cash Back
Picture-in-Picture Extension (by Google)
Pinterest Save Button
React Developer Tools
Save to Google Drive
Save to Pocket
SimpRead - Reader View
Tampermonkey
Text Reader (Text to Speech) TTS by Read me
Twitch Chat pronouns
Volume Master
YouTube Channel Whitelist for uBlock Origin
Zoom Chrome Extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 95932
 cosmetic: 39616
 scriptlet: 18206
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 default:
  user-filters: 0-0, never
  easylist: 69480-9, now
  easyprivacy: 33321-62, 1h.16m
  ublock-badware: 7626-141, now
  ublock-filters: 34158-150, now
  ublock-privacy: 447-3, now
  ublock-quick-fixes: 277-43, 1h.15m
  ublock-unbreak: 2107-33, now
  urlhaus-1: 6858-0, now
filterset (user): [empty]
trustedset:
 added: [array of 17 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 948 ms (selfie)
 maxAssetCacheWait: 137 ms
popupPanel:
 blocked: 3
 no-popups: true
 network:
  delivra.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
You should report to EasyList and/or Adguard here:

- https://github.com/easylist/easylist/issues
- https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by dportvine** [comment]
>There's a popup that says something like "Thanks for visiting, claim your free offer" 

`health.harvard.edu##.welcome-popup` ~> **EasyList – Newsletter Notices**

>There's a bottom popup banner for signing up for their newsletter.

@ryanbr

**Comment by ryanbr** [comment]
Already in Newsletters; https://github.com/easylist/easylist/commit/64411de8148955f323d5623377f56893155171aa

**Comment by dportvine** [comment]
<details>
<summary>Screen</summary>

![2023-08-10_070828](https://github.com/uBlockOrigin/uAssets/assets/111344219/a9454e53-081b-4428-9b7e-2f302df6f9be)
</details>
