### ISSUE TITLE
netshoes.com.br: breakage

### ISSUE THREAD

**Issue by Lucas559-noob** [uBlockOrigin/uAssets#19293]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.netshoes.com.br/`

### Category

breakage

### Description

You can't log in, after placing everything and click to log in, it will show a loading icon and not complete.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 109
filterset (summary):
 network: 99909
 cosmetic: 43186
 scriptlet: 18547
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69480-9, now
  easyprivacy: 33321-62, now
  plowe-0: 3716-1069, now
  spa-1: 5404-68, now
  ublock-badware: 7626-142, now
  ublock-filters: 34158-176, now
  ublock-privacy: 447-4, now
  ublock-quick-fixes: 284-43, now
  ublock-unbreak: 2107-34, now
  urlhaus-1: 6858-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 39605 ms (selfie)
 maxAssetCacheWait: 241 ms
popupPanel:
 blocked: 23
 network:
  bing.com: 2
  clearsale.com.br: 1
  google-analytics.com: 4
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 6
  googletagservices.com: 1
  hotjar.com: 4
  instana.io: 2
```
</details>

**Comment by gorhill** [comment]
I don't have an account but when I try to login using made up info, I see an exception being thrown because of EasyPrivacy's `/webanalytics/*`,  I suspect this is the issue.

Can you try this filter?

    @@||netshoes.com.br/webanalytics/*$xhr,1p
