### ISSUE TITLE
vtmgo.be: detection

### ISSUE THREAD

**Issue by MysticDAssassin** [uBlockOrigin/uAssets#19295]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When starting a video it says '"can't play video when adblocker is active". It worked till yesterday. 

### URL(s) where the issue occurs.

`https://www.vtmgo.be/vtmgo/afspelen/016d8d63-5e65-4663-a64a-071e00e23c07`

### uBO version

uBlock Origin 1.51.0

### Browser name and version

Brave Version 1.56.20 Chromium: 115.0.5790.171

### Settings

```adb
@@||v.fwmrm.net/ad/*&caid$xhr,domain=vtm.be
```

**Comment by ghajini** [comment]
does this work

```
||v.fwmrm.net^$xhr,domain=vtmgo.be,redirect=nooptext
||gabe.hit.gemius.pl/gplayer.js$script,domain=vtmgo.be,redirect=noopjs,important
||mssl.fwmrm.net/*/AdManager.js$script,domain=vtmgo.be,redirect=noopjs,important
```

**Comment by MysticDAssassin** [comment]
Yes it works. Thank you.

**Comment by MysticDAssassin** [comment]
Stopped working. I guess VTM really wants people to pay for no ads

**Comment by BPower0036** [comment]
@ghajini Added to local list https://github.com/EasyDutch-uBO/EasyDutch/commit/c0107a6bdaac3c942ca391ecf97adf5403ab5a9e

**Comment by brecht6** [comment]
This doesn't work anymore, seems like VTM patched it.
