### ISSUE TITLE
colombiaonline.com - Anti adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#193]
Anti adb message on `https://www.colombiaonline.com/`, they are testing through multiple scripts.

**SS:** https://i.imgur.com/7mpBIZr.png
**Error URL:** `https://www.colombiaonline.com/`

_Using Chrome 54 with uBO 1.9.16._

**Comment by toshiya44** [comment]
Post your filter lists and custom filters please.

**Comment by gotitbro** [comment]
I am using:
> uBlock filters‎,  uBlock filters – Badware risks‎,  uBlock filters – Privacy‎, uBlock filters – Unbreak, Adblock Warning Removal List‎,  EasyList‎,  Peter Lowe’s Ad server list‎ 

I get the the warning even when using no custom filters.

**Comment by okiehsch** [comment]
Try `#@#.afs_ads`.

**Comment by gotitbro** [comment]
That works, should be refined as `colombiaonline.com#@#.afs_ads`
Or disable cosmetic filtering on the website or use `@@||colombiaonline.com^$generichide`

I will report this to **EasyList** maintainers.
