### ISSUE TITLE
odapedia.org: breakage

### ISSUE THREAD

**Issue by Ogateru** [uBlockOrigin/uAssets#19300]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://odapedia.org/`

### Category

breakage

### Description

Images in web pages are not displayed correctly

### Other extensions used

Advanced Font Settings
Gesturefy
Privacy Badger
Stylebot(disabled on odapedia.org)
TWP

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/96802150/c59631df-05be-40ba-90b0-bc1a827e96c0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 115
filterset (summary):
 network: 100669
 cosmetic: 50476
 scriptlet: 18342
 html: 1013
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35049-224, now
  ublock-badware: 7667-1, now
  ublock-privacy: 482-0, now
  ublock-unbreak: 2152-0, now
  ublock-quick-fixes: 266-0, now
  easylist: 69810-580, now
  easyprivacy: 33280-785, now
  urlhaus-1: 6852-0, now
  plowe-0: 3716-1, now
  JPN-1: 12990-21, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 537 ms (selfie)
 maxAssetCacheWait: 198 ms
popupPanel:
 blocked: 10
 network:
  odapedia.org: 2
  googlesyndication.com: 3
  googletagmanager.com: 3
  livedoor.jp: 2
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by krystian3w** [comment]
Also check in Firefox instead in "Floorp Browser" (https://floorp.app/ / https://github.com/floorp-Projects/floorp/#readme)
