### ISSUE TITLE
peliculasio.com [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1930]
URL(s) where the issue occurs

`https://peliculasio.com/the-hitmans-bodyguard`

Describe the issue

![](https://i.imgur.com/fycQqQJ.png)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`peliculasio.com##script:inject(abort-current-inline-script.js,smrtSB,true)`. True was added to not kill video player.

**Comment by okiehsch** [comment]
I think that is a fake video player,so 
`peliculasio.com##script:inject(abort-on-property-write.js, smrtSB)` killing it is actually a good thing 😉

**Comment by zaphodbeebblebrox** [comment]
Missing closing paretheses

**Comment by okiehsch** [comment]
Ups, thx.
