### ISSUE TITLE
tumblr.com: breakage

### ISSUE THREAD

**Issue by umbralOptimatum** [uBlockOrigin/uAssets#19304]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The Tumblr filter `tumblr.com##.posts:style(margin-bottom: 0px !important)` as created in #5911 causes issues on some custom blog themes, which are designed with a bottom margin in mind. Limiting this filter to only `www.tumblr.com` would solve the issue. (Though I'm not sure it even has any effect anymore.)

### URL(s) where the issue occurs.

`https://iconicpreview.tumblr.com/`

### Screenshot(s)

With filter active, scrollable box is cut off:

<img width="528" alt="Screen Shot 2023-08-08 at 2 45 10 AM" src="https://github.com/uBlockOrigin/uAssets/assets/12092270/cf9bf53e-0391-4cf1-8334-eb54eb4dd8ce">

Without filter active, entire scrollable height is visible:

<img width="529" alt="Screen Shot 2023-08-08 at 2 45 45 AM" src="https://github.com/uBlockOrigin/uAssets/assets/12092270/40f1e323-d613-4849-af69-5516410c4aaf">

### uBO version

1.51.0

### Browser name and version

Firefox 115.1.0

### Settings

Tested with none

**Comment by krystian3w** [comment]
workarounds:

```adb
! global
tumblr.com#@#.posts:style(margin-bottom: 0px !important)
! at subdomain only
tumblr.com,~iconicpreview.tumblr.com##.posts:style(margin-bottom: 0px !important)
```
