### ISSUE TITLE
hancinema.net: ads

### ISSUE THREAD

**Issue by TatianaPink** [uBlockOrigin/uAssets#19309]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hancinema.net/korean_drama_Revenant.php`

### Category

ads

### Description

Leftovers.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://github.com/uBlockOrigin/uAssets/assets/135860000/6369483d-c43e-41ed-9716-cb8e2e2c50d7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 165515
 cosmetic: 160147
 scriptlet: 39889
 html: 1202
listset (total-discarded, last-updated):
 added:
  adguard-generic: 72980-6691, now
  adguard-spyware-url: 1169-6, 4m
  adguard-spyware: 59035-17131, 4m
  block-lan: 48-0, now
  adguard-social: 21120-162, now
  adguard-cookies: 26545-41, 4m
  adguard-popup-overlays: 23270-1020, 4m
  adguard-mobile-app-banners: 4486-7, 4m
  adguard-other-annoyances: 13216-59, 4m
  adguard-widgets: 2262-1, now
  ublock-annoyances: 5318-12, now
  spa-1: 5408-11, now
 default:
  user-filters: 1-0, never
  ublock-filters: 35062-402, 1m
  ublock-badware: 7677-0, 4m
  ublock-privacy: 482-0, 1m
  ublock-unbreak: 2152-0, 4m
  ublock-quick-fixes: 252-0, 4m
  easylist: 69801-849, now
  easyprivacy: 33284-739, now
  urlhaus-1: 6927-0, 4m
  plowe-0: 3715-2, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4012 ms
 maxAssetCacheWait: 2569 ms
popupPanel:
 blocked: 14
 network:
  360playvid.info: 1
  bidgx.com: 1
  cloudflareinsights.com: 2
  criteo.net: 1
  doubleclick.net: 4
  exponential.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##.footer + div[style^="position:fixed;padding"]
  ##.ad_300x600_300x250
  ##+js(abort-current-script, document.createElement, admiral)
  ##+js(set-constant, dable, {})
```
</details>

**Comment by gorhill** [comment]
This should be fixed in either EasyList or List KR:

    hancinema.net##[class*="ad_"]

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by JobcenterTycoon** [comment]
Fixed now.

**Comment by JobcenterTycoon** [comment]
Fixed.

For the best results try [microShield](https://github.com/List-KR/microShield) the setup need below 2 minutes.
