### ISSUE TITLE
britannica.com: ads

### ISSUE THREAD

**Issue by pubct** [uBlockOrigin/uAssets#19315]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Border remnant at the top that's used for ad placement.

### URL(s) where the issue occurs.

`https://www.britannica.com/games/octordle/`

### uBO version

1.51.0

### Browser name and version

Chrome 115.0.5790.171

### Settings

x

**Comment by stephenhawk8054** [comment]
```adb
##.ad-banner
```
or
```adb
##.ad-banner--header
```

@ryanbr
