### ISSUE TITLE
9gag.com: breakage

### ISSUE THREAD

**Issue by St0RM53** [uBlockOrigin/uAssets#19317]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://9gag.com/gag/avQDWMZ`

### Category

breakage

### Description

It looks like some javascript essential to functionality is broken, example if you click "View X replies" in the comments, and when you click the 3 vertical dots up and right of the post to open the sub-menu for example to download the post.

Disabling uBlock on the site fixes the issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 97988
 cosmetic: 39639
 scriptlet: 18156
 html: 1016
listset (total-discarded, last-updated):
 default:
  user-filters: 22-0, never
  ublock-filters: 35066-67, now
  ublock-badware: 7677-0, now
  ublock-privacy: 481-0, now
  ublock-unbreak: 2152-0, now
  ublock-quick-fixes: 253-0, 48m
  easylist: 69759-746, now
  easyprivacy: 33265-718, now
  urlhaus-1: 6095-0, now
  plowe-0: 3715-2, now
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 26 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 21986 ms (selfie)
 maxAssetCacheWait: 10011 ms
popupPanel:
 blocked: 37
 network:
  9gag.com: 5
  amazon-adsystem.com: 1
  btloader.com: 5
  d2fucu4fhozx2v.cloudfront.net: 5
  doubleclick.net: 1
  facebook.net: 5
  googletagmanager.com: 1
  permutive.app: 2
  pubmatic.com: 5
  quantcast.com: 1
  quantserve.com: 6
```
</details>

**Comment by St0RM53** [comment]
cookie issue

**Comment by krystian3w** [comment]
Maybe enough will be block translation:

```adb
||cmp.quantcast.com/choice/*.com/choice.$script,domain=9gag.com
```
