### ISSUE TITLE
zonarutoppuden.com [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1931]
URL(s) where the issue occurs

`http://www.zonarutoppuden.com/2014/09/naruto-shippuden-pelicula-6-el-camino-ninja.html`

Describe the issue

![](https://i.imgur.com/wcmKOSQ.png)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`||piguiqproxy.com^$xmlhttprequest,domain=zonarutoppuden.com,redirect=nooptext`
