### ISSUE TITLE
thetvdb.com: breakage

### ISSUE THREAD

**Issue by Dalarialus** [uBlockOrigin/uAssets#19311]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The front page and all images on TheTVDB are broken. This has only started happening recently, so I can only assume this an an anti-adblock countermeasure on their end?

### URL(s) where the issue occurs.

`https://thetvdb.com/`

### uBO version

1.51.0

### Browser name and version

Google Chrome Version 115.0.5790.171 (Official Build) (64-bit)

### Settings

None.

**Comment by stephenhawk8054** [comment]
I can reproduce. It's caused by

```adb
||com/banners/$image,from=~pingdom.com|~tooltrucks.com
```

in EL.

@ryanbr
