### ISSUE TITLE
youtube.com: Ad still appearing, audio only

### ISSUE THREAD

**Issue by ThisGreenDingo** [uBlockOrigin/uAssets#19323]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=NK7m4ipYfBk`

### Category

ads

### Description

Ad still appears on video, audio only with ad icon in bottom left corner. No visuals however.

### Other extensions used

AHA Music, YouTube Nonstop, SponsorBlock, Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2023-08-11 141513](https://github.com/uBlockOrigin/uAssets/assets/74699902/cd324e81-2dc4-4ced-8675-e4ba1f7c8ec1)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 98019
 cosmetic: 39650
 scriptlet: 18219
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69859-10, now
  easyprivacy: 33269-64, now
  plowe-0: 3717-1068, now
  ublock-badware: 7677-146, now
  ublock-filters: 34196-176, now
  ublock-privacy: 450-6, now
  ublock-quick-fixes: 272-31, now
  ublock-unbreak: 2105-33, now
  urlhaus-1: 6027-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 189 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 72
 network:
  youtube.com: 60
  doubleclick.net: 3
  google.com: 7
  google.com.au: 1
  googlesyndication.com: 1
 extended:
  ###player-ads
  ###merch-shelf
  ##.ad-showing > .html5-video-container
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-button
  ##.ytp-ad-player-overlay-flyout-cta
  ##.ytp-ad-progress-list
  ##ytd-companion-slot-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  #@##masthead-ad
  #@#.ytd-companion-slot-renderer
  #@#.video-ads
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(json-prune, playerResponse.adPlacements playerResponse.pl…
```
</details>

**Comment by stephenhawk8054** [comment]
> AHA Music, YouTube Nonstop, SponsorBlock, Return YouTube Dislike

Please turn off all other extensions, browser's built-in blocker and test again. Then please continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636 , don't continue here.
