### ISSUE TITLE
music.youtube.com: ads

### ISSUE THREAD

**Issue by noirraven** [uBlockOrigin/uAssets#19329]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://music.youtube.com/watch?v=BVbm31ybqlU&list=RDAMVMBVbm31ybqlU`

### Category

ads

### Description

Ads are still playing) showing on YouTube music when they never have before. I can't troubleshoot all of this by myself; I don't know any of this

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 99413
 cosmetic: 30154
 scriptlet: 18236
 html: 1018
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35391-330, now
  ublock-badware: 7673-1, now
  ublock-privacy: 488-1, now
  ublock-unbreak: 2157-1, now
  ublock-quick-fixes: 280-0, now
  adguard-mobile: 8512-119, now
  easylist: 69882-17246, now
  easyprivacy: 33272-726, now
  urlhaus-1: 6027-0, now
  plowe-0: 3717-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1101 ms (selfie)
 maxAssetCacheWait: 175 ms
popupPanel:
 blocked: 121
 network:
  youtube.com: 67
  doubleclick.net: 8
  google.com: 30
  googlesyndication.com: 15
  googletagmanager.com: 1
 extended:
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(json-prune, playerResponse.adPlacements playerResponse.pl…
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Please continue here: https://github.com/uBlockOrigin/uAssets/issues/7636
