### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by MathiasBoi6** [uBlockOrigin/uAssets#19327]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=OpOu9rchRI4&list=RDCZNgM3PI1Y4&index=5`

### Category

ads

### Description

The extension has been working, but starting today i have been getting video ads on youtube. ublock blocks the video of the ad, but i am still forced to wait through the video's audio and a black (empty) video player.

### Other extensions used

Popup blocker (strict)
Youtube windowed fullscreen
获取B站视频封面图

The chinese one can't read or change data on youtube.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://github.com/uBlockOrigin/uAssets/assets/79922317/b6f201fa-055e-43e6-9f00-73573b51cba4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98033
 cosmetic: 39654
 scriptlet: 18182
 html: 1017
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35084-215, now
  ublock-badware: 7679-0, now
  ublock-privacy: 488-0, now
  ublock-unbreak: 2152-0, now
  ublock-quick-fixes: 280-0, now
  easylist: 69882-564, now
  easyprivacy: 33272-761, now
  urlhaus-1: 6027-0, now
  plowe-0: 3717-2, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 175 ms (selfie)
 maxAssetCacheWait: 39 ms
popupPanel:
 blocked: 25
 network:
  youtube.com: 15
  doubleclick.net: 3
  google.com: 4
  googlesyndication.com: 3
 extended:
  ###merch-shelf
  ###player-ads
  ##.ad-showing > .html5-video-container
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-button
  ##.ytp-ad-player-overlay-flyout-cta
  ##.ytp-ad-progress-list
  ##ytd-companion-slot-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  #@#.ytd-companion-slot-renderer
  #@#.video-ads
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19323#issuecomment-1674195027
