### ISSUE TITLE
megawarez.org [Fake Button] [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1932]
URL(s) where the issue occurs

`https://www.megawarez.org/mayhem-dvdrip-720p-1080p-latino/`

Describe the issue

![](https://i.imgur.com/6yGEVub.png)
![](https://i.imgur.com/UkL4Xpz.png)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
```
@@||solowarez.org^$generichide
solowarez.org##.theiaStickySidebar
solowarez.org##.e3lan-below_header.e3lan
```

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by lain566** [comment]
Website Redirects, click on `Ir al Enlace`

`https://www.megawarez.org/mirillis-action-full-con-crack-serial/`

![25023675-bbc3-4526-ab21-a36dea98aa59](https://user-images.githubusercontent.com/27441315/51778979-e3fb6500-2104-11e9-8668-e33f3a21902c.png)

![36755e50-a49a-46b9-b9f5-9a7c347b47da](https://user-images.githubusercontent.com/27441315/51778974-dd6ced80-2104-11e9-9e5d-0d5ed9e02166.png)

**Comment by lain566** [comment]
@okiehsch Your filter has broken, and can't continue if you have enabled Easylist spanish
`acortalo.net##+js(setTimeout-defuser.js, s=void)`

**Comment by okiehsch** [comment]
Does
````
acortalo.net#@#+js(setTimeout-defuser.js, s=void)
||acortar.net^$third-party,popup,badfilter
````
work for you?

**Comment by lain566** [comment]
Yeah, that works, this filter also.
`||acortar.net^$popunder`

**Comment by okiehsch** [comment]
You mean remove that filter?

**Comment by lain566** [comment]
Yes, it seems that they have not activated their anti-adblock system
