### ISSUE TITLE
ipsaya.com: detection

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#19328]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ipsaya.com/speedtest.php`

### Category

detection

### Description

anti-adblock show up after 5 minute

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/7771037b-0314-4778-811f-763cef92acee)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 130016
 cosmetic: 143264
 scriptlet: 27097
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 10417-9, now
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 524-4, now
  DEU-0: 7015-0, now
  IDN-0: 9663-371, now
  RUS-0: 39683-50, now
  ara-0: 2321-6, now
  easylist-annoyances: 3892-47, now
  easylist-chat: 132-0, now
  easylist-notifications: 2642-103, now
  fanboy-cookiemonster: 48046-229, now
  fanboy-social: 16136-10, now
  ublock-annoyances: 5351-80, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 12-0, never
  easylist: 69882-60, now
  easyprivacy: 33272-246, now
  plowe-0: 3717-1074, now
  ublock-badware: 7677-148, now
  ublock-filters: 34209-391, now
  ublock-privacy: 453-9, now
  ublock-quick-fixes: 276-34, now
  ublock-unbreak: 2105-40, now
  urlhaus-1: 6027-0, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 18 redacted]
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 803 ms (selfie)
 maxAssetCacheWait: 508 ms
popupPanel:
 blocked: 17
 network:
  google-analytics.com: 1
  google.com: 14
  googlesyndication.com: 1
  sharethis.com: 1
 extended:
  ##.sharethis-inline-share-buttons
  ##ins.adsbygoogle
  ###IP-ads
  ##iframe[name="googlefcPresent"]
```
</details>

**Comment by okiehsch** [comment]
Have you tried after disabling all of your manually added filter lists?

**Comment by 3xploiton3** [comment]
> Have you tried after disabling all of your manually added filter lists?

i tried disable my personal filter, anti-adblock still show up, you need wait 5-10 minute use their service

**Comment by ghajini** [comment]
still can't reproduce, waited more than 10 mins
try installing ublock origin on new browser profile with default settings
