### ISSUE TITLE
flipkart.com: ads

### ISSUE THREAD

**Issue by webvijayi** [uBlockOrigin/uAssets#19326]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.flipkart.com/grocery/pr?sid=73z&marketplace=GROCERY&sort=discount&page=10`

### Category

ads

### Description

Sponsored tagged products are being shown

### Other extensions used

Adblock plus

### Screenshot(s)

[nimbus screenshot.pdf](https://github.com/uBlockOrigin/uAssets/files/12320338/nimbus.screenshot.pdf)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 97989
 cosmetic: 39637
 scriptlet: 18170
 html: 1017
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35078-59, 1m
  ublock-badware: 7679-0, now
  ublock-privacy: 485-0, now
  ublock-unbreak: 2152-0, now
  ublock-quick-fixes: 251-0, now
  easylist: 69830-703, now
  easyprivacy: 33272-761, now
  urlhaus-1: 6027-0, now
  plowe-0: 3717-2, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3192 ms
 maxAssetCacheWait: 48 ms
popupPanel:
 blocked: 14
 network:
  domdog.io: 1
  doubleclick.net: 3
  facebook.com: 1
  flixcart.com: 1
  googleadservices.com: 1
  googletagmanager.com: 1
  newrelic.com: 4
  omtrdc.net: 2
```
</details>

**Comment by krystian3w** [comment]
Looks https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+label%3A%22geo+specific%22, can you share fake working zip code?

**Comment by webvijayi** [comment]
> Looks [ geo specific](https://github.com/uBlockOrigin/uAssets/labels/geo%20specific) , can you share fake working zip code?

Yes you can see the local zip code 313001 in the screenshot too. Try that.

**Comment by krystian3w** [comment]
```adb
##div[data-id][style*="width"]:has(> div span:has-text(Sponsored))
```

Check in picker. Can generate placeholder at right in rows now (2 cells with products instead 4 cells).


Maybe works scriptlets arsenal: https://github.com/gorhill/uBlock/wiki/Resources-Library#available-general-purpose-scriptlets to avoid restyle "rows" to inline objects.

**Comment by webvijayi** [comment]
> ```
> ##div[data-id][style*="width"]:has(> div span:has-text(Sponsored))
> ```
> 
> Check in picker. Can generate placeholder at right in rows now (2 cells with products instead 4 cells).
> 
> Maybe works scriptlets arsenal: https://github.com/gorhill/uBlock/wiki/Resources-Library#available-general-purpose-scriptlets to avoid restyle "rows" to inline objects.

Tried that but it didn't work unfortunately. Would like to completely hide all sponsored products. It was working well before in last couple of days sponsored products started showing i wonder if flipkart changed something to bypass adblockers.

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
flipkart.com##div[data-tkid^="ADVIEW"]:upward(div[data-id])
```

**Comment by krystian3w** [comment]
>  hide all sponsored products

For me is visible product without sponsored label:

![image](https://github.com/uBlockOrigin/uAssets/assets/35370833/c931374f-ebda-419f-9113-062f72813ebd)

**Comment by webvijayi** [comment]
> Does this work?
> 
> ```
> flipkart.com##div[data-tkid^="ADVIEW"]:upward(div[data-id])
> ```

This worked :) Thanks a lot 👍

**Comment by webvijayi** [comment]
Such a great community. Thanks a lot @krystian3w @stephenhawk8054 and wishing you a great weekend ahead.

**Comment by krystian3w** [comment]
> **Other extensions used**
>
> Adblock plus

You should disable ABP  on `about:addons`, if uBo is turned on.

**Comment by webvijayi** [comment]
Unfortunately seems like flipkart changed something again i am again seeing sponsored products even after the previous fix. Any hope for a potential fix  ?

**Comment by stephenhawk8054** [comment]
Still works fine for me: https://github.com/uBlockOrigin/uAssets/assets/66517106/abc64a56-c2be-4123-8353-c5b847f8388b
