### ISSUE TITLE
bandcamp.com: breakage

### ISSUE THREAD

**Issue by TatianaPink** [uBlockOrigin/uAssets#19320]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://merregnonrecords.bandcamp.com/album/final-symphony-ii-music-from-final-fantasy-v-viii-ix-and-xiii?from=hp`

### Category

breakage

### Description

`AdGuard Social Media` incorrectly hides the `Embed` link, which is the necessary for generating and customizing iframe codes. It's not a social media sharing button. The AdGuard maintainers refused to fix this.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![68747470733a2f2f63646e2e616467756172642e696e666f2f736974657265706f7274732f31396d7a31386e3375643867386777306f6f77676f6f387373343430637734646732713438736566766b2e706e673f6e633d31](https://github.com/uBlockOrigin/uAssets/assets/135860000/77271672-ba80-43f7-8f5d-d2a183512d69)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 164692
 cosmetic: 160280
 scriptlet: 39921
 html: 1204
listset (total-discarded, last-updated):
 added:
  adguard-generic: 73038-6691, 1m
  adguard-spyware-url: 1175-6, 1m
  adguard-spyware: 59029-17090, now
  block-lan: 48-0, now
  adguard-social: 21134-908, now
  adguard-cookies: 26565-45, now
  adguard-popup-overlays: 23292-157, now
  adguard-mobile-app-banners: 4489-7, now
  adguard-other-annoyances: 13222-59, now
  adguard-widgets: 2266-1, now
  ublock-annoyances: 5311-263, now
  spa-1: 5431-11, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 35077-458, 2m
  ublock-badware: 7679-0, 2m
  ublock-privacy: 481-0, 2m
  ublock-unbreak: 2152-0, 2m
  ublock-quick-fixes: 261-0, 3m
  easylist: 69814-885, 1m
  easyprivacy: 33270-792, now
  urlhaus-1: 6095-0, 3m
  plowe-0: 3715-2, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 13000 ms (selfie)
 maxAssetCacheWait: 7441 ms
popupPanel:
 blocked: 2
 network:
  bcbits.com: 2
 extended:
  ##.tos-update
  ##.share-embed
```
</details>

**Comment by okiehsch** [comment]
Issues caused by Adguard filters are best opened at https://github.com/AdguardTeam/AdguardFilters

@Yuki2718 
Hidden by
`bandcamp.com##.share-embed`

**Comment by Yuki2718** [comment]
The problem is if we remove, someone will report it as missed social button again. Will comment out.

**Comment by okiehsch** [comment]
My bad, I should have noticed that but it does not change the fact that we only fix issues caused by a default stup in this repo.
We are not a "super-repo" that fixes issues caused by all available filter lists.

**Comment by stephenhawk8054** [comment]
If the specialized filter lists declined the requests, we won't do more. If we override it, what should we do if someone else come here to complain about the button not being hidden when enabling that list?

**Comment by Yuki2718** [comment]
> The AdGuard maintainers refused to fix this.

TBH I'm also curious why it was declined. @TatianaPink Can you post the link of the refusal? The only chance it can be addressed will be by re-arguing with @Alex-302 and I'm pro for that, the button is just ignorable in my eyes and not a social media sharing.
