### ISSUE TITLE
solowarez.org [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1933]
URL(s) where the issue occurs

`http://solowarez.org/`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
```
@@||solowarez.org^$generichide
solowarez.org##.theiaStickySidebar
solowarez.org##.e3lan-below_header.e3lan
```
