### ISSUE TITLE
fmhy.net: breakage

### ISSUE THREAD

**Issue by ave9858** [uBlockOrigin/uAssets#19337]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

fmhy.net is blocked by the default EasyPrivacy filter list. The page is not used for tracking and I don't believe there are any privacy issues with the site.

### URL(s) where the issue occurs.

`https://fmhy.net/`

### uBO version

1.51.0

### Browser name and version

Firefox 116.0.2

### Settings

- I updated the default filter lists by clicking "Purge all caches" and then "Update now". Tests were done with a fresh install of Firefox.

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/1240bc7f528c438555045ad0ca60326e79682e0a
