### ISSUE TITLE
economictimes.indiatimes.com: nuisance

### ISSUE THREAD

**Issue by kookieman12** [uBlockOrigin/uAssets#19331]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://economictimes.indiatimes.com/`

### Category

nuisance

### Description

Bar appears at the bottom for selling ETPrime

### Other extensions used

Bitwarden, youtube related, bypass paywalls

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98034
 cosmetic: 39655
 scriptlet: 18183
 html: 1017
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35088-215, 9m
  ublock-badware: 7679-1, 9m
  ublock-privacy: 488-0, 9m
  ublock-unbreak: 2152-0, 9m
  ublock-quick-fixes: 280-0, 9m
  easylist: 69882-607, 9m
  easyprivacy: 33272-712, 9m
  urlhaus-1: 6027-0, 9m
  plowe-0: 3710-1, 9m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1412 ms
 maxAssetCacheWait: 5 ms
popupPanel:
 blocked: 22
 network:
  indiatimes.com: 2
  clmbtech.com: 2
  doubleclick.net: 1
  go-mpulse.net: 2
  google-analytics.com: 2
  googletagmanager.com: 2
  growthrx.in: 1
  imasdk.googleapis.com: 2
  mouseflow.com: 1
  rubiconproject.com: 2
  scorecardresearch.com: 1
  survicate.com: 1
  tvid.in: 3
 extended:
  ###topAd
  ##.custom_ad
  ##.colombiaAd
  ##.adsbg300
  ##.ad_block
  ##.colombia
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(no-setTimeout-if, objSubPromo)
  ##+js(set-constant, objVc.interstitial_web, )
```
</details>

**Comment by ghajini** [comment]
A paywall ,we don't address that
