### ISSUE TITLE
mail.yahoo.com: ads

### ISSUE THREAD

**Issue by dobbelina** [uBlockOrigin/uAssets#19333]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mail.yahoo.com/d/folders/1`

### Category

ads

### Description

Ad in screenshot below is persistent when opening the inbox folder.
Reloading the webpage makes is disappear most of the times but not always,
kinda random.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/46063764/4b997179-d084-481b-9228-374d94535c90)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 99851
 cosmetic: 42222
 scriptlet: 18465
 html: 1032
listset (total-discarded, last-updated):
 added:
  SWE-1: 4539-2, now
 default:
  user-filters: 0-0, never
  ublock-filters: 35080-223, now
  ublock-badware: 7679-1, now
  ublock-privacy: 488-0, now
  ublock-unbreak: 2152-0, now
  easylist: 69914-613, now
  easyprivacy: 33276-717, now
  urlhaus-1: 6155-0, now
  plowe-0: 3710-1, now
  ublock-quick-fixes: 287-0, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1001 ms
 maxAssetCacheWait: 390 ms
popupPanel:
 blocked: 31
 network:
  yahoo.com: 22
  scorecardresearch.com: 3
  taboola.com: 1
  yimg.com: 5
 extended:
  ##[data-test-id="right-rail-ad"]
  ##+js(no-setTimeout-if, ADB)
```
</details>

**Comment by u-RraaLL** [comment]
When you next see the ad: Right-click > Inspect element (browser tool) > Hover over the lines until you find the top line before the highlight moves to something else (/more) than just the ad > Select it > Expand the Inspector window a bit so we can see the code > Screenshot it and share.

**Comment by dobbelina** [comment]
Below 2 screenshots of 2 example ads:
![image](https://github.com/uBlockOrigin/uAssets/assets/46063764/8e1c8634-9199-4340-89f8-cec06834c63f)
And another one:
![image](https://github.com/uBlockOrigin/uAssets/assets/46063764/5cb909b9-87da-4da4-b1bd-dbd595149fbc)

**Comment by u-RraaLL** [comment]
Okay, test:

    mail.yahoo.com##[aria-labelledby^="bottom-sticky-pencil-ad-brand-name"]

**Comment by dobbelina** [comment]
I used the eyedropper Element Picker Mode and added below, ad is now gone.
```
! 2023-08-15 https://mail.yahoo.com
mail.yahoo.com##.j_tW8fK.I_Z1sGJ76.ab_C.gl_CI.ek_EZ.D_F.k_w.P_Zs0VV7.H_7GHz.o_h
```

**Comment by u-RraaLL** [comment]
Okay, but if you test the one above we can add it to lists for the potential benefit of others.

**Comment by dobbelina** [comment]
I removed my filter and added yours, it works as intended, no ads.
Thanks for the help.
