### ISSUE TITLE
adshnk.com: breakage

### ISSUE THREAD

**Issue by Kaito273** [uBlockOrigin/uAssets#19338]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Annoyance Anti Adblock

### URL(s) where the issue occurs.

`https://adshnk.com/OTIzNjc=/https://ouo.io/PBaA24`

### Screenshot(s)

![Screenshot 2023-08-12 164838](https://github.com/uBlockOrigin/uAssets/assets/140431949/56d4d1e8-ca93-4520-b2b1-a570c27d8c20)

### uBO version

1.51.0

### Browser name and version

Edge

### Settings

```
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 383484
 cosmetic: 136033
 scriptlet: 40411
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 967-0, 3m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt: 87007-1155, 3m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt: 48937-2, 3m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 214-12, 3m
  adguard-cookies: 26586-46, 4m
  adguard-generic: 73069-1521, 4m
  adguard-mobile: 8520-493, 4m
  adguard-mobile-app-banners: 4493-9, 4m
  adguard-other-annoyances: 13230-11, 4m
  adguard-popup-overlays: 23310-106, 4m
  adguard-social: 21164-908, 4m
  adguard-spyware: 59047-7563, 4m
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-badware: 7677-978, 4m
  ublock-filters: 34200-4199, 3m
  ublock-privacy: 453-86, 3m
  ublock-quick-fixes: 286-42, 3m
  ublock-unbreak: 2105-124, 3m
  urlhaus-1: 6040-21, 3m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4002 ms
 maxAssetCacheWait: 1393 ms
```

**Comment by okiehsch** [comment]
Disable all of your manually added filter lists and try again.

**Comment by BlazeFTL** [comment]
I Can Reproduce Infinite Loading In Firefox Android Only

**Comment by okiehsch** [comment]
So, it's broken no anti adblock detection?

**Comment by BlazeFTL** [comment]
Only On FireFox Android Works Fine On Chrome Based Browsers

**Comment by BlazeFTL** [comment]
Infinite Loading Issue Exist Even After Disabling Ubo So Not Ubo Problem...

Only 2nd Page Breakage No Continue Button For Me

**Comment by okiehsch** [comment]
> Only 2nd Page Breakage No Continue Button For Me

That's fixed if you diable uBO?

**Comment by BlazeFTL** [comment]
Yes

**Comment by okiehsch** [comment]
OK. I will take a look.

**Comment by BlazeFTL** [comment]
FireFox Cant Load Page
Chrome - Loads But No Continue Button

**Comment by okiehsch** [comment]
Deos adding 
`@@||wurfl.io/wurfl.js$script,domain=adshnk.com`
fix the issues for you?

**Comment by BlazeFTL** [comment]
Yes Fixed

**Comment by okiehsch** [comment]
Thx for testing the issue, I will add the exception.

**Comment by BlazeFTL** [comment]
However There Is Problem In 2 Click Continue> Second Step>Try To Complete Task
[Screenshot_20230813-001400_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/139938337/9f068856-768e-4276-a2c3-4346f8bf005f)

**Comment by okiehsch** [comment]
Seems to be a Kiwi specific problem, I can't reproduce with Firfox or Chrome.
