### ISSUE TITLE
empire-stream.net: detection

### ISSUE THREAD

**Issue by Kris-Tofe** [uBlockOrigin/uAssets#19339]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This problem appeared a few days ago.

uBO is detected and the movie does not play. Only on server "E", the site-specific server. on the "VOE" server, the movie starts.

but most recent films or series are on the "E" site server.
The link that I send you has the 2 servor available: you can compare the 2.
the problem is for all movies ans series with the "E" site server.

Thanks for your help
i use Edge (chromium) on Windows 11

### URL(s) where the issue occurs.

`https://empire-stream.net/film/Dark-Cloud-en-streaming-hd/396461057538d1646a89896741133996`

### Screenshot(s)

![Capture d'écran 2023-08-12 135840](https://github.com/uBlockOrigin/uAssets/assets/138688963/3bd6987f-e3d4-4c97-9a87-42cea341722e)

### Notes

uBO detected on Empire-Stream.net or on Empire-streaming.app and blocks media

choose a movie
with Ads
Choose a version (VO or other)
choose a server ("E" for reproduce the problem)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 116704
 cosmetic: 48671
 scriptlet: 18347
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  FRA-0: 28140-35, 15h.37m
  easylist: 69914-41, 15h.37m
  easyprivacy: 33276-335, 15h.37m
  plowe-0: 3710-1074, 15h.37m
  ublock-badware: 7677-161, 15h.37m
  ublock-filters: 34200-250, 15h.37m
  ublock-privacy: 453-7, 15h.37m
  ublock-quick-fixes: 285-41, 1h.53m
  ublock-unbreak: 2105-37, 15h.37m
  urlhaus-1: 6155-0, 15h.37m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 546 ms (selfie)
 maxAssetCacheWait: 240 ms
```
</details>

**Comment by okiehsch** [comment]
@Yuki2718 
````
empire-stream.net##+js(nowoif)
@@||e-player-stream.app/player/assets/js/ads.js?v=1$script,1p
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=e-player-stream.app
````
for the regional french list.

**Comment by ghajini** [comment]
iam late
```
e-player-stream.app##+js(aost, document.getElementById, adsBlocked)
empire-streaming.*,empire-stream.net##+js(nowoif)
empire-stream.net,empire-streaming.*##.hide-ads
e-player-stream.*##+js(set, adsConfig, [])
```

**Comment by okiehsch** [comment]
Works fine on my end.
@Yuki2718 
The exceptions can be avoided with the alternative filters.

**Comment by Yuki2718** [comment]
Okay, some rules are already in French list though.

**Comment by Yuki2718** [comment]
Is this deblocker?

**Comment by okiehsch** [comment]
So  should we add all of
````
e-player-stream.app##+js(aost, document.getElementById, adsBlocked)
empire-streaming.*,empire-stream.net##+js(nowoif)
empire-stream.net,empire-streaming.*##.hide-ads
e-player-stream.*##+js(set, adsConfig, [])
````
to our list or only parts of it?

**Comment by Yuki2718** [comment]
Only `e-player-stream.app##+js(aost, document.getElementById, adsBlocked)`, I think.

**Comment by okiehsch** [comment]
Ok, I will add it.

**Comment by Yuki2718** [comment]
Do anyone see any side effect of `e-player-stream.*##+js(set, adsConfig, [])`? As previous rules are limited to `/iframe_ad` path.

```
[$path=/iframe_ad]empire-stream.net#%#//scriptlet('set-constant', 'empire.data', 'emptyArr')
[$path=/iframe_ad]empire-streaming.*#%#//scriptlet('set-constant', 'empire.data', 'emptyArr')
```

**Comment by okiehsch** [comment]
I let it play in the background for a while and it seems to work without issue on my end.

**Comment by ghajini** [comment]
It was small popup at initial,regex blocks but iam annoyed by popup
