### ISSUE TITLE
Consider extending uBlock Privacy with join-ad-interest-group and run-ad-auction permission policy

### ISSUE THREAD

**Issue by bershanskiy** [uBlockOrigin/uAssets#19343]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

[`ublock-privacy`](https://github.com/uBlockOrigin/uAssets/blob/master/filters/privacy.txt) list already has directives for `browsing-topics` and `idle-detection` permissions. I propose adding `join-ad-interest-group` and `run-ad-auction` directives.

These directives control (deprecated but still working ) FLEDGE API [(docs)](https://developer.chrome.com/blog/fledge-api/) and the new rebrand of FLEDGE API called "Protected Audience".

### URL(s) where the issue occurs.

 - ("deprecated" after rebranding) FLEDGE demo:
   - docs at `https://fledge-demo.glitch.me/`
   - advertisers:
      - `https://shopping-fledge-demo.glitch.me/advertiser/shopping.html`
      - `https://travel-fledge-demo.glitch.me/advertiser/travel.html`
   - publisher:
      - `https://publisher-fledge-demo.glitch.me/publisher/index.html`
      - `https://publisher-fledge-demo.glitch.me/publisher/index.html?fencedframe`

 - (new name) Protected Audience demo:
   - docs at `https://protected-audience-demo.web.app/`
   - advertiser `https://protected-audience-demo-advertiser.web.app/`
   - publisher `https://protected-audience-demo-publisher.web.app/`

### uBO version

1.51.0

### Browser name and version

Google Chrome 115.0.5790.170

### Settings

Default settings.

**Comment by bershanskiy** [comment]
The following patch adds these rules:
```diff
diff --git a/filters/privacy.txt b/filters/privacy.txt
index e0fb4389a..382fae247 100644
--- a/filters/privacy.txt
+++ b/filters/privacy.txt
@@ -651,6 +651,8 @@ lite.duckduckgo.com##+js(href-sanitizer, a[href^="//duckduckgo.com/l/?uddg="], ?
 !#if env_chromium
 *$permissions=browsing-topics=(),from=~localhost
 *$permissions=idle-detection=(),from=~localhost
+*$permissions=join-ad-interest-group=(),from=~localhost
+*$permissions=run-ad-auction=(),from=~localhost
 !#endif
 
 ! https://github.com/uBlockOrigin/uAssets/issues/19100
```

**Comment by gorhill** [comment]
Confirmed this is a thing after enabling _Privacy Sandbox Ads APIs_ in `chrome://flags`
