### ISSUE TITLE
space.com: nuisance

### ISSUE THREAD

**Issue by xparadoxical** [uBlockOrigin/uAssets#19341]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.space.com/mars-spinning-fast-slowing-days-mystery`

### Category

nuisance

### Description

After clicking through the cookie popup, when your cursor leaves the page area, a newsletter popup appears.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 114
filterset (summary):
 network: 99477
 cosmetic: 47194
 scriptlet: 18426
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  POL-0: 7966-11, 12m
  POL-2: 1276-13, now
  easylist: 69949-34, now
  easyprivacy: 33269-64, now
  plowe-0: 3716-1069, now
  ublock-badware: 7683-146, now
  ublock-filters: 34175-213, now
  ublock-privacy: 453-6, now
  ublock-quick-fixes: 286-41, 10m
  ublock-unbreak: 2106-34, now
  urlhaus-1: 6001-0, 11m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2635 ms (selfie)
 maxAssetCacheWait: 302 ms
popupPanel:
 blocked: 5
 network:
  futurecdn.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  jwpcdn.com: 1
 extended:
  ##.dfp-leaderboard-container
  ##.ad-unit:not(.text-ad):not(.textads)
  ###taboola-below-article-thumbnails
  ##.van_taboola
  ##.adunit
  ###hawkMagWidget
  ##.related-articles-block
```
</details>

**Comment by okiehsch** [comment]
Add
`space.com##.slice-container-newsletterForm`
we don't fix newsletters in our list.
@ryanbr

**Comment by stephenhawk8054** [comment]
It's already hidden by

```adb
###slice-container-newsletterForm-exitIntent
###slice-container-newsletterForm-articleInbodyContent
```

in `EasyList – Newsletter Notices` list.

@xparadoxical You can enable that list or add the filters above to `My filters`

**Comment by okiehsch** [comment]
> It's already hidden

Oh my mistake, I checked the site with the wrong list.
