### ISSUE TITLE
txori.com: detection

### ISSUE THREAD

**Issue by AceKyt** [uBlockOrigin/uAssets#19342]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.txori.com/dbdevolution`

### Category

detection

### Description

I enter the page I play for a while and after a few minutes it redirects me to another page where it tells me not to use AdBlocks (`https://www.txori.com/adblock`)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<
![Captura de pantalla 2023-08-12 212714](https://github.com/uBlockOrigin/uAssets/assets/135560205/4f7ef66e-7e95-42f6-b550-5a516faf636c)
>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 114
filterset (summary):
 network: 100565
 cosmetic: 45728
 scriptlet: 18564
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69949-10, 9m
  easyprivacy: 33269-64, 9m
  plowe-0: 3716-1062, 9m
  spa-0: 3748-19, 9m
  spa-1: 5437-223, 9m
  ublock-badware: 7683-146, 9m
  ublock-filters: 34175-205, 9m
  ublock-privacy: 453-6, 9m
  ublock-quick-fixes: 285-41, 9m
  ublock-unbreak: 2106-35, 9m
  urlhaus-1: 6001-0, 9m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11128 ms (selfie)
 maxAssetCacheWait: 486 ms
popupPanel:
 blocked: 2
 network:
  w3counter.com: 1
  yollamedia.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Already countered by `||doubleclick.net^$xhr,redirect=noop.txt` on my end.

Try `txori.com##+js(nostif, adblock)`

**Comment by gorhill** [comment]
> Try `txori.com##+js(nostif, adblock)`

I can reproduce and your filter works fine.
