### ISSUE TITLE
oracle.com: breakage

### ISSUE THREAD

**Issue by penalvch** [uBlockOrigin/uAssets#19346]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When one navigates to `https://www.oracle.com/cloud/free/#` and clicks the checkbox 'Always free' the tiles immediatley assort to show only those tiles that are associated with the 'Always Free' tier.

What happens instead is the checkbox is shown as checked by the tiles do not move.

The only thing that was noticed that fixed the issue is whitelist the rule:
||go-mpulse.net^

This was found in two default UBO filter lists:
EasyPrivacy
Peter Lowe's Ad and tracking server list

Reproduced in:
Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (arm64)

### URL(s) where the issue occurs.

`https://www.oracle.com/cloud/free/#`

### Screenshot(s)

N/A as visual issue easily described.

### Notes

N/A

### Configuration

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 96538
 cosmetic: 39324
 scriptlet: 18103
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-unbreak: null
 default:
  user-filters: 0-0, never
  easylist: 69810-10, 5d.15h.17m
  easyprivacy: 33280-64, 5d.15h.17m
  plowe-0: 3716-1069, 5d.15h.17m
  ublock-badware: 7665-146, 4d.23h.55m
  ublock-filters: 34208-174, 14h
  ublock-privacy: 453-4, 15m
  ublock-quick-fixes: 285-33, 4h.33m
  urlhaus-1: 6074-0, 13h.59m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 54 ms (selfie)
 maxAssetCacheWait: 7 ms
```

**Comment by okiehsch** [comment]
`||tms.oracle.com/main/prod/utag.sync.js$script,1p,redirect-rule=noop.js`
works for me but only after reloading one time, same with an exception.
@stephenhawk8054 can you check if it is the same on your end?

@penalvch 
This will be fixed in `uBO-unbreak` and you have disabled that list, so you can either enable that list or add the filter to your personal filter list.

**Comment by stephenhawk8054** [comment]
@okiehsch Hmmm... `redirect` does not work for me, only exceptions work. I don't need to reload one time tho.

**Comment by okiehsch** [comment]
Ok.

@ryanbr
`@@||tms.oracle.com/main/prod/utag.sync.js$script,1p`
fixes the issue.
