### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by LogoManSeva** [uBlockOrigin/uAssets#19350]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [ ] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=2ZizRQMVITs`

### Category

detection

### Description

I have recently experienced an issue. When attempting to watch videos on YouTube with uBlock Origin enabled, I am faced with a message stating:

**Ad blockers are not allowed on YouTube**

- It looks like you may be using an ad blocker. Video playback will be blocked unless YouTube is allowlisted or the ad blocker is disabled.
- Ads allow YouTube to be used by billions worldwide at no charge.
- You can go ad-free with YouTube Premium, and creators can still get paid from your subscription.

This message means that I need to disable the ad blocker to continue watching YouTube. This behavior started recently and seems to be a new measure implemented by YouTube to prevent ad blockers from functioning properly on their platform.

### Other extensions used

AdBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Evidence](https://github.com/uBlockOrigin/uAssets/assets/136836907/97fce1e0-c848-405e-821b-e9b2d08c5254)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 98326
 cosmetic: 39518
 scriptlet: 18210
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 69953-10, now
  easyprivacy: 33273-64, now
  plowe-0: 3718-1062, now
  ublock-badware: 7685-146, now
  ublock-filters: 34186-173, now
  ublock-privacy: 461-6, now
  ublock-quick-fixes: 263-37, now
  ublock-unbreak: 2109-32, now
  urlhaus-1: 6082-0, now
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1762 ms (selfie)
 maxAssetCacheWait: 621 ms
popupPanel:
 blocked: 357
 network:
  youtube.com: 80
  doubleclick.net: 11
  google.com: 266
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytd-ad-slot-renderer
  ##.ytd-in-feed-ad-layout-renderer
  ##.ytd-promoted-video-renderer
  ##.ytd-search-pyv-renderer
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ##+js(set-constant, yt.config_.openPopupConfig.supportedPopups.a…
  ##+js(set-constant, Object.prototype.adBlocksFound, 0)
  ##+js(set-constant, ytplayer.config.args.raw_player_response.adP…
  ##+js(set-constant, Object.prototype.hasAllowedInstreamAd, true)
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
> AdBlock

> - [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.

Please follow the prerequisites truthfully and test again, not filling them to submit the issue then untick them. Can you turn off all other extensions and browser's built-in blocker and test again?

---

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Anyway, please continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636 . Don't continue here.
