### ISSUE TITLE
[nsfw] bestadvise4u.com: ads

### ISSUE THREAD

**Issue by Tasibul** [uBlockOrigin/uAssets#19352]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bestadvise4u.com/`

### Category

ads

### Description

They have timer on the website, I have to wait 10 seconds for 2 or 3 times then the download button appears 

### Other extensions used

There is no other extension 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 99655
 cosmetic: 30203
 scriptlet: 18221
 html: 1019
listset (total-discarded, last-updated):
 default:
  user-filters: 9-0, never
  ublock-filters: 35369-333, now
  ublock-badware: 7681-1, now
  ublock-privacy: 492-1, now
  ublock-unbreak: 2161-1, now
  ublock-quick-fixes: 279-0, 23m
  adguard-mobile: 8526-119, now
  easylist: 69911-17078, now
  easyprivacy: 33275-719, now
  urlhaus-1: 6082-0, now
  plowe-0: 3718-1, now
filterset (user): [array of 8 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2993 ms (selfie)
 maxAssetCacheWait: 164 ms
popupPanel:
 blocked: 5
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
  stpd.cloud: 3
```
</details>

**Comment by BlazeFTL** [comment]
As Much As I Remember The Timer Cant Be ByPassed...My Personal Collection

Test URL hdhub4u,vegamovies
```
technorozen.com,hubdrive.me,bestadvise4u.com,newztalkies.com,10desires.org,theapknews.shop,aiotechnical.com,cryptonewzhub.com,trendzguruji.me,techvybes.com,wizitales.com,101desires.com###top_nav, .rd_btn, .soractrl, .large:others()
technorozen.com,hubdrive.me,bestadvise4u.com,newztalkies.com,10desires.org,theapknews.shop,aiotechnical.com,cryptonewzhub.com,trendzguruji.me,techvybes.com,wizitales.com,101desires.com###top_nav, .rd_btn, .soractrl:style(display: block !important;)
```

**Comment by gorhill** [comment]
You used a shortener link to arrive at that site? What's the site which led you there?

**Comment by Tasibul** [comment]
hdhub4u.fan/

**Comment by BlazeFTL** [comment]
`https://hdhub4u.fan/waltair-veerayya-2023-web-dl-hindi/` > 1080p Links

**Comment by Tasibul** [comment]
Its a movie downloading website but it makes you wait 10 seconds for 3 times, its annoying

**Comment by okiehsch** [comment]
Not possible, the timer is validated server side.
To test add
`bestadvise4u.com##+js(nano-stb, , 1200)`
you will get an "Invalid Request :T<30" message after completing all countdowns.
