### ISSUE TITLE
phimmoibb.net: ads

### ISSUE THREAD

**Issue by sweetyoru** [uBlockOrigin/uAssets#19351]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The site can show ads as normal, and element pick is useless with this site.

### URL(s) where the issue occurs.

`https://phimmoibb.net/phim/xu-so-cac-nguyen-to`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/86972944/368d98a4-18e8-4bce-b9cc-d625537349dc

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 377317
 cosmetic: 349521
 scriptlet: 46519
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69895-102, 22h.51m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92604-21297, 7d.19h.32m
  ALB-0: 301-9, 18h.23m
  BGR-0: 1067-11, 3d.22h.53m
  CHN-0: 25805-142, 22h.46m
  CZE-0: 745-1, 18h.22m
  DEU-0: 7037-7, 18h.21m
  EST-0: 462-9, 18h.14m
  FIN-0: 2198-0, 22h.42m
  FRA-0: 28147-115, 22h.43m
  GRC-0: 1042-0, 22h.34m
  HRV-0: 358-3, 3d.22h.52m
  [38 lists not shown]: [too many]
 default:
  user-filters: 11-0, never
  easylist: 69903-1893, 2d.22h.41m
  easyprivacy: 33269-898, 2d.22h.40m
  plowe-0: 3715-1540, 6d.1h
  ublock-badware: 7677-417, 3d.22h.50m
  ublock-filters: 34187-4384, 3d.22h.49m
  ublock-privacy: 453-14, 2d.11m
  ublock-quick-fixes: 293-25, 10h.13m
  ublock-unbreak: 2105-122, 3d.22h.48m
  urlhaus-1: 5979-2, 18h.27m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2274 ms (selfie)
 maxAssetCacheWait: 1859 ms
```
</details>

**Comment by stephenhawk8054** [comment]
I don't see any ads on the site with uBO's default settings + `ABPVN` list

```yml
added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69895-102, 22h.51m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92604-21297, 7d.19h.32m
  ALB-0: 301-9, 18h.23m
  BGR-0: 1067-11, 3d.22h.53m
  CHN-0: 25805-142, 22h.46m
  CZE-0: 745-1, 18h.22m
  DEU-0: 7037-7, 18h.21m
  EST-0: 462-9, 18h.14m
  FIN-0: 2198-0, 22h.42m
  FRA-0: 28147-115, 22h.43m
  GRC-0: 1042-0, 22h.34m
  HRV-0: 358-3, 3d.22h.52m
  [38 lists not shown]: [too many]
```

Please don't enable all regional filter lists, just enable the ones you usually visit. This site is Vietnamese site, so just enable `ABPVN list`.

---

> trustedset:
> added: [array of 1 redacted]

Are you sure you are not whitelisting this website in uBO? What is the color of your uBO icon in the toolbar?

**Comment by sweetyoru** [comment]
I enabled all region lists because just remember which country i'll visit and enable them manually seem daunting to me. Is there any drawback by doing that?
I didn't whitelist the site on my settings, the uBO's icon is red as usual, as you can see in the screenshot.

**Comment by stephenhawk8054** [comment]
> I enabled all region lists because just remember which country i'll visit and enable them manually seem daunting to me. Is there any drawback by doing that?

> just enable the ones you **usually** visit

It can cause unexpected breakages or exeptions.

---

I still cannot see the ads: https://github.com/uBlockOrigin/uAssets/assets/66517106/8201875a-96b5-4dbc-a022-1ebec7340e09

@hoang-rio Sorry, can you reproduce the issue?

**Comment by hoang-rio** [comment]
This page does not contains ads like the screenshot. I trying turn off adblocker and no ads displayed like that.
@sweetyoru You should take a extentions and browser plugin check. Ads may come from adware or software extention

**Comment by sweetyoru** [comment]
I followed these steps but still can see it:
1. Restore to default settings by clicking 'Restore to default settings..' button
2. Enable ABPVN filter list

It's weird to me that a browser plugin only show ads on just that site, other sites work normally.

**Comment by sweetyoru** [comment]
As for a plugin that may put the ads in, i tried to open the site in Incognito mode, but it's still there
![2023-08-15T14:37:56,257049363+07:00](https://github.com/uBlockOrigin/uAssets/assets/86972944/14563cfc-5678-4436-9a61-f530926c96b7)

**Comment by stephenhawk8054** [comment]
@sweetyoru Can you right click on the ads -> click "Inspect (element)" and screenshot it here?

**Comment by hoang-rio** [comment]
I can't reproduce this but I try to block this via ads domain `vipads.live`
@sweetyoru Please update ABPVN List and retry

**Comment by sweetyoru** [comment]
Here is the screenshot of Inspect
![2023-08-15T15:46:31,863953790+07:00](https://github.com/uBlockOrigin/uAssets/assets/86972944/d3dceb3a-a7cb-47a9-9156-0cb85794afd7)

**Comment by sweetyoru** [comment]
I forced an update of the ABPVN filter list and the ads completely gone now.

Thank you for your support @hoang-rio @stephenhawk8054
