### ISSUE TITLE
2dehands.be: ads

### ISSUE THREAD

**Issue by ThatGuyOliver** [uBlockOrigin/uAssets#19355]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.2dehands.be/q/computer/`

### Category

ads

### Description

This is the biggest reselling site in Belgium and there are a lot of annoying ads showing up. This is a site-wide issue. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot](https://github.com/uBlockOrigin/uAssets/assets/104093092/8d5351b0-85e0-428d-a002-8e85399296e5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98989
 cosmetic: 41577
 scriptlet: 18212
 html: 1019
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35069-100, 3m
  ublock-badware: 7687-0, 3m
  ublock-privacy: 492-0, 3m
  ublock-unbreak: 2157-0, 3m
  ublock-quick-fixes: 277-0, 3m
  easylist: 69879-704, 3m
  easyprivacy: 33276-755, 3m
  urlhaus-1: 6070-0, 3m
  plowe-0: 3718-2, 3m
  NLD-0: 2900-16, 3m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1671 ms (selfie)
 maxAssetCacheWait: 121 ms
popupPanel:
 blocked: 9
 network:
  datadoghq-browser-agent.com: 1
  ebayclassifieds.net: 4
  google-analytics.com: 1
  googletagmanager.com: 1
  marktplaats.net: 2
 extended:
  ###adsense-container
  ###banner-top-dt
  ##.hz-Banner
  ##.hz-Page-content:style(max-width: 1300px!important;)
```
</details>

**Comment by gorhill** [comment]
Please report to <https://github.com/EasyDutch-uBO/EasyDutch/>.

**Comment by ThatGuyOliver** [comment]
> Please report to https://github.com/EasyDutch-uBO/EasyDutch/.

How do I report this issue?

This is not only a Dutch site but also a French site. "https://www.2ememain.be/" It's the same site but in another language.

**Comment by gorhill** [comment]
> How do I report this issue?

Just like you did here, open an issue on [EasyDutch issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues), they are best place to make a determination of what should be blocked or not on the reported site.

> This is not only a Dutch site but also a French site

Either way, this has to be fixed in a regional list. The link you provided shows a page in Dutch on my side, so this should be fixed in EasyDutch.

**Comment by okiehsch** [comment]
If you click "FR" it will change to french.

@BPower0036 
`2dehands.be##.hz-Listing-item-wrapper:has-text(Topadvertentie)`
for the regional dutch list.
@Yuki2718 pretty sure the same filter with whatever means "Topadvertisement" in french will work for the regional french list. 😁

**Comment by Yuki2718** [comment]
Apparently not. `##.hz-Banner` appears in French `https://www.2ememain.be/q/compte+fortnite/`

**Comment by Yuki2718** [comment]
I think actually it's better than having two `:has-text()` rules in separate lists. @BPower0036 can add the same rule to avoid redundancy.

**Comment by BPower0036** [comment]
@ThatGuyOliver, @okiehsch, @Yuki2718 In my opinion those "Top advertisements" are not advertisements. Everything on this reselling website are advertisements of people trying to sell their products. "Top advertisements" are advertisements of people of people who paid to be higher up in the rankings, or am I wrong @ThatGuyOliver?

**Comment by Yuki2718** [comment]
@BPower0036 Actually that's what I suspected, so probably they should be addressed in Annoyance lists as promotion, right?

**Comment by BPower0036** [comment]
@Yuki2718 Yes, you are right.

**Comment by samve000** [comment]
2dehands started showing ads again, they also duplicate the same ad, one of them they label as an advertisement and the other they don't label as an advertisement and then shuffles them between non-sponsored products. They do share the same title. I already made a dutch userscript that could block this, but 2dehands.be has an adblock detector.

<details><summary>userscript</summary>
<p>

```javascript
// ==UserScript==
// @name         Remove Ads, Duplicates, and Empty Space
// @namespace    http://tampermonkey.net/
// @version      1.1
// @description  Removes Topadvertentie listings, duplicate products, and leftover empty banner containers
// @match        *://*/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Remove banner containers and empty space elements
    function removeEmptySpace() {
        document.querySelectorAll('li.bannerContainerLoading, div.hz-Banner.hz-Banner--fluid').forEach(el => el.remove());
    }

    // Remove ads and duplicate listings
    function removeAdsAndDuplicates() {
        const listings = document.querySelectorAll('li.hz-Listing.hz-Listing--list-item');
        const titleMap = new Map();

        listings.forEach(listing => {
            const titleElement = listing.querySelector('strong.hz-Text.hz-Text--bodyLarge');
            const isTopAd = listing.querySelector('span')?.textContent?.includes('Topadvertentie');
            const title = titleElement ? titleElement.textContent.trim() : null;

            if (!title) return;

            if (!titleMap.has(title)) {
                titleMap.set(title, []);
            }
            titleMap.get(title).push({ listing, isTopAd });
        });

        titleMap.forEach(entries => {
            if (entries.length > 1) {
                // Remove all duplicates of the same product title
                entries.forEach(entry => entry.listing.remove());
            } else {
                // Remove single entry only if it is a Topadvertentie
                if (entries[0].isTopAd) {
                    entries[0].listing.remove();
                }
            }
        });
    }

    // Combined cleanup function
    function cleanup() {
        removeEmptySpace();
        removeAdsAndDuplicates();
    }

    // Run cleanup on page load
    cleanup();

    // Observe DOM changes and clean dynamically added elements
    const observer = new MutationObserver(cleanup);
    observer.observe(document.body, { childList: true, subtree: true });
})();
``` 
</p>
</details> 

<img width="1060" height="1354" alt="Image" src="https://github.com/user-attachments/assets/93153fdb-6bbc-4f7c-b04f-17aa69140fda" />
