### ISSUE TITLE
[Anti-adblock] buffalonews.com

### ISSUE THREAD

**Issue by chelseaislan** [uBlockOrigin/uAssets#1936]
### URL(s) where the issue occurs
```
http://buffalonews.com/section/sports/high-schools/
http://buffalonews.com/section/gusto/tv/
```
etc.

### Describe the issue
Every page redirects automatically to http://buffalonews.com/adblock/

### Screenshot(s)
![screenshot 15](https://user-images.githubusercontent.com/30471081/38599762-f46d3628-3d8b-11e8-98f6-653cd02efdab.png)
![screenshot 16](https://user-images.githubusercontent.com/30471081/38599765-f4a7c162-3d8b-11e8-9611-d64c77c7a34a.png)

### Versions
- Browser/version: Chrome 65
- uBlock Origin version: Nano Adblocker (Based on uBlock Origin Version/1.15.24 Commit/98df44c Sidebar/disabled)

### Settings
Default + ABPindo

**Comment by okiehsch** [comment]
I can't reproduce, the site has been fixed a week ago and the fix still works on my end.
https://github.com/uBlockOrigin/uAssets/blob/d861232b7e535b3097531b702c70d90f65fdfaf0/filters/filters.txt#L6366

The only way I can reproduce, is to disable that filter, or to block `api.bntech.io/metrics/v2/js`
That request is not blocked with the default setup or with `ABPindo`.

**Comment by KiLL4FuNK** [comment]
I can't reproduce
