### ISSUE TITLE
tcbk.com: breakage

### ISSUE THREAD

**Issue by spektred** [uBlockOrigin/uAssets#19369]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tcbk.com/personal/accounts/certificates-of-deposit`

### Category

breakage

### Description

Why is the CD image at the bottom of this page hidden?  The alt text contains the word "kissing", might that be the issue?

### Other extensions used

none, fresh install of firefox

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98246
 cosmetic: 39472
 scriptlet: 18171
 html: 1020
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35095-88, 18m
  ublock-badware: 7693-0, 18m
  ublock-privacy: 492-0, 17m
  ublock-unbreak: 2157-0, 17m
  ublock-quick-fixes: 288-0, 17m
  easylist: 69861-746, 17m
  easyprivacy: 33279-713, 17m
  urlhaus-1: 6026-0, 17m
  plowe-0: 3719-2, 17m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 804 ms
 maxAssetCacheWait: 325 ms
popupPanel:
 blocked: 8
 no-cosmetic-filtering: true
 network:
  tcbk.com: 4
  exacttarget.com: 1
  googletagmanager.com: 2
  levelaccess.net: 1
```
</details>

**Comment by spektred** [comment]
I disabled cosmetic filters only temporarily to see if that caused this. It had no effect.

**Comment by ghajini** [comment]
fixed in easylist ,update filters
