### ISSUE TITLE
xda-developers.com: detection

### ISSUE THREAD

**Issue by kookieman12** [uBlockOrigin/uAssets#19366]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.xda-developers.com/nokia-g310-5g-replaceable-display-battery/`

### Category

detection

### Description

Ublock origin is detected and banner is shown which you have to click on every time

### Other extensions used

Bypass paywalls 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium Mobile: 116
filterset (summary):
 network: 230591
 cosmetic: 94902
 scriptlet: 24634
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  ublock-privacy: null
 added:
  IND-0: 12507-8, never
  adguard-cookies: 26620-3803, never
  curben-phishing: 153910-70, never
  easylist-annoyances: 3894-915, never
  easylist-newsletters: 6335-1850, never
  easylist-notifications: 2643-335, never
  fanboy-cookiemonster: 48119-17446, never
  ublock-annoyances: 5428-382, never
  ublock-cookies-adguard: 299-0, never
  ublock-cookies-easylist: 299-299, never
 default:
  user-filters: 0-0, never
  adguard-mobile: 8530-33, 4m
  easylist: 69861-16291, 3m
  plowe-0: 3719-467, 3m
  ublock-badware: 7680-147, 3m
  ublock-filters: 34520-427, 3m
  ublock-quick-fixes: 286-49, 3m
  ublock-unbreak: 2114-16, 3m
  urlhaus-1: 6026-0, 2m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1007 ms
 maxAssetCacheWait: 408 ms
popupPanel:
 blocked: 22
 network:
  ad.gt: 1
  adlightning.com: 1
  adsafeprotected.com: 2
  adsninja.ca: 2
  advertising.com: 1
  amazon-adsystem.com: 1
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 2
  googletagservices.com: 1
  imasdk.googleapis.com: 1
  parsely.com: 1
  primis.tech: 1
  privacymanager.io: 2
  unblockia.com: 1
  viglink.com: 1
 extended:
  ##.adsninja-ad-zone
  ##.ad-current
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##+js(remove-class, twig-body)
```
</details>

**Comment by ghajini** [comment]
enable easyprivacy & ublock privacy filter lists
