### ISSUE TITLE
calculator-online.net: detection

### ISSUE THREAD

**Issue by Happypig375** [uBlockOrigin/uAssets#19361]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

1. Open `https://calculator-online.net/quartile-calculator/`
2. Wait 10 seconds
3. Adblock detection

### URL(s) where the issue occurs.

`https://calculator-online.net/quartile-calculator/`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19922066/0f2cce05-5ec3-456a-9416-2938a3f4c641)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98317
 cosmetic: 39464
 scriptlet: 18169
 html: 1018
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35085-75, 11m
  ublock-badware: 7693-1, 11m
  ublock-privacy: 493-0, 11m
  ublock-unbreak: 2157-0, 11m
  ublock-quick-fixes: 283-0, 11m
  easylist: 69850-745, 11m
  easyprivacy: 33277-712, 11m
  urlhaus-1: 6098-0, 11m
  plowe-0: 3718-1, 11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1664 ms
 maxAssetCacheWait: 804 ms
```
</details>

**Comment by stephenhawk8054** [comment]
I can reproduce

**Comment by Happypig375** [comment]
@MasterKia 
![image](https://github.com/uBlockOrigin/uAssets/assets/19922066/8c8fa09b-d07f-45ba-9ae6-2d02aa3a6c6b)
Fresh Firefox with only uBlock Origin.

**Comment by Happypig375** [comment]
@stephenhawk8054 Thanks!

**Comment by stephenhawk8054** [comment]
@Yuki2718 I see the script `https://stomachscience.com/0/cae5e2f7/a01c86f07bad31ac477f6602b23b7ba234c1a0c10fb1`

so we might need to include `[0-9]` in the regex?

**Comment by Yuki2718** [comment]
@pgl Admiral

**Comment by pgl** [comment]
> stomachscience.com

Thanks, added!
