### ISSUE TITLE
startribune.com: nuisance

### ISSUE THREAD

**Issue by akaase** [uBlockOrigin/uAssets#19378]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.startribune.com/`

### Category

nuisance

### Description

Site landing popup now appears even with Javascript on the site disabled. Using the zapper I can delete the overlay (clicking the lightning bolt on the margins of the site) and scrolling the page is successful.

If I instead click the picker tool in the same spot as the zapper tool, the overlay gets deleted but the site then becomes locked and no longer scrollable.

### Other extensions used

iCloud Bookmarks

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1010" alt="popup" src="https://github.com/uBlockOrigin/uAssets/assets/46581015/cc68d1e8-a282-4afb-af9b-5fe1c7e6cb8f">

</details>
<img width="1010" alt="popup" src="https://github.com/uBlockOrigin/uAssets/assets/46581015/cc68d1e8-a282-4afb-af9b-5fe1c7e6cb8f">

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 108468
 cosmetic: 185373
 scriptlet: 27144
 html: 1205
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 69917-7053, 15m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92715-80098, 15m
  adguard-social: 21192-700, 17m
  fanboy-thirdparty_social: 68-0, 16m
  fanboy-cookiemonster: 48119-280, 16m
  fanboy-social: 16142-17, 16m
  ublock-annoyances: 5326-7, 16m
 default:
  user-filters: 0-0, never
  ublock-filters: 35067-206, 25m
  ublock-badware: 7693-0, 24m
  ublock-privacy: 492-0, 23m
  ublock-unbreak: 2157-0, 22m
  ublock-quick-fixes: 281-0, 21m
  easylist: 69861-612, 20m
  easyprivacy: 33279-719, 19m
  urlhaus-1: 6009-0, 18m
  plowe-0: 3719-2, 16m
filterset (user): [empty]
trustedset:
 added: [array of 19 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 547 ms
 maxAssetCacheWait: 403 ms
popupPanel:
 blocked: 45
 network:
  startribune.com: 6
  bugsnag.com: 6
  chartbeat.com: 3
  cloudflareinsights.com: 4
  dc8xl0ndzn2cb.cloudfront.net: 2
  dk98ddgl0znzm.cloudfront.net: 2
  googletagmanager.com: 2
  htlbid.com: 1
  jwpcdn.com: 1
  ntv.io: 1
  optimizely.com: 13
  outbrain.com: 1
  quantserve.com: 2
  scorecardresearch.com: 1
 extended:
  ##.needsclick[aria-label][style]
  ##.dfp-ad-container
  ##.ad-mod
  ##.leaderboard-ad-container
  ##.ad-placeholder:not(#filter_ads_by_classname):not(#detect_ad_e…
  ##.share-label
  ##.footer-social-links
  ##.vertical-ad
  ##.most-shared
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
startribune.com##.modal-backdrop
startribune.com##body,html:style(overflow: auto !important;)
```

@ryanbr

**Comment by akaase** [comment]
That worked... Why doesn't the picker tool include that second line of filter?
________________________________

**Comment by stephenhawk8054** [comment]
Picker tool is just an assistant tool to help you craft the filter. For more complicated one (like the 2nd filter), you'll need to investigate webpage's HTML DOM and a bit CSS knowledge.

**Comment by stephenhawk8054** [comment]
Looks like it's a paywall, so we won't address the issue. You can use the filters above as your custom filters.
