### ISSUE TITLE
cnn.com: detection

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#19370]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

adblocker warning, detection

### URL(s) where the issue occurs.

`https://edition.cnn.com/videos`

### Screenshot(s)

![asd](https://github.com/uBlockOrigin/uAssets/assets/33556647/77e5926f-d021-4d0e-a245-532d1f855b79)

### uBO version

1.51.0

### Browser name and version

Chrome

### Settings

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 101000
 cosmetic: 47047
 scriptlet: 22198
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5359-7, 1d.1h.28m
 default:
  user-filters: 0-0, never
  easylist: 69879-10, 1d.1h.28m
  easyprivacy: 33276-64, 1d.1h.28m
  plowe-0: 3718-1062, 1d.1h.28m
  spa-0: 3749-19, 1h.4m
  spa-1: 5466-223, 1d.1h.28m
  ublock-badware: 7685-146, 1d.1h.28m
  ublock-filters: 34191-203, 1d.1h.28m
  ublock-privacy: 464-7, 16m
  ublock-quick-fixes: 281-29, 9h.5m
  ublock-unbreak: 2110-35, 1d.1h.28m
  urlhaus-1: 6026-0, 1h.3m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 296 ms (selfie)
 maxAssetCacheWait: 149 ms
```

### Notes

the warning shows the first time the site is visited. necessary delete cookies to reproduce it again

**Comment by gorhill** [comment]
Also unable to reproduce.

Please use the _chat_ icon in the popup panel to report filter issue, this will give us more useful troubleshooting information, and will ask you to check more things on your side before reporting.

**Comment by stephenhawk8054** [comment]
This looks difficult to reproduce. I browsed the website above with the above steps (the steps don't look stable so can't replicate 100%) but still could not see the anti-adb.

**Comment by okiehsch** [comment]
It's a sourcepoint modal but I can't reproduce.
I see some sourcepoint requests. all  the ones originating from `mms.cnn.com`.

**Comment by dportvine** [comment]
I can't reproduce but I can see this script.

<details>
<summary>Screen</summary>

![2023-08-18_064325](https://github.com/uBlockOrigin/uAssets/assets/111344219/dad6285c-f729-4a55-a468-35a59e96c531)
![2023-08-18_064051](https://github.com/uBlockOrigin/uAssets/assets/111344219/aba39006-c6c4-4472-b2e2-33a3d702acdc)
</details>

**Comment by stephenhawk8054** [comment]
Looks like blocking the whole domain doesn't cause any breakages?

```adb
||mms.cnn.com^
```

**Comment by dportvine** [comment]
>||mms.cnn.com^

The site works fine for me.

**Comment by Omega-6** [comment]
https://github.com/easylist/easylist/issues/17937
