### ISSUE TITLE
thecydia.com: ad placeholder

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#19374]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Has the same problem as https://github.com/uBlockOrigin/uAssets/issues/19036.

### URL(s) where the issue occurs.

`https://www.thecydia.com/`

### uBO version

v1.51.1b19

### Browser name and version

Firefox 116.0.3

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by gorhill** [comment]
I don't see ad placeholders. Where are they? How do they look?

**Comment by Yuki2718** [comment]
Maybe the bottom space? Personally I don't care though.

**Comment by Sonic5435325** [comment]
It's at the bottom of the page, which was fixed as well on the other site.

**Comment by stephenhawk8054** [comment]
"The other site" had other placeholders throughout the page. That's why I addressed it.

**Comment by Sonic5435325** [comment]
So, this won't be fixed?

**Comment by gorhill** [comment]
No, I wouldn't know it's an ad placeholder, maintainers' time and filter list estate should be reserved for cases with obvious benefits.
