### ISSUE TITLE
notion.so: breakage

### ISSUE THREAD

**Issue by Xioverze** [uBlockOrigin/uAssets#19381]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.notion.so/`

### Category

breakage

### Description

blocks the API notion.so uses, which breaks the site specifically when trying to edit a note or search templates.

### Other extensions used

lastpass
google translate
gopher buddy

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-08-17 1 05 35 PM](https://github.com/uBlockOrigin/uAssets/assets/83839464/aa93afd4-a63d-4a66-891f-e137d1763d21)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 108
filterset (summary):
 network: 98463
 cosmetic: 39435
 scriptlet: 18245
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 69941-10, now
  easyprivacy: 33289-64, now
  plowe-0: 3720-1063, now
  ublock-badware: 7701-146, now
  ublock-filters: 34249-181, now
  ublock-privacy: 464-6, now
  ublock-quick-fixes: 288-45, now
  ublock-unbreak: 2110-34, now
  urlhaus-1: 6078-0, 7m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 22198 ms (selfie)
 maxAssetCacheWait: 3428 ms
popupPanel:
 blocked: 19
 network:
  notion.so: 13
  customer.io: 1
  sentry.io: 3
  splunkcloud.com: 2
 extended:
  ##.notion-default-overlay-container.notion-overlay-container > d…
```
</details>

**Comment by gorhill** [comment]
Does the following filter fix the issue?

    @@||telemetry.transcend.io/collect$3p,xhr,domain=notion.so

**Comment by stephenhawk8054** [comment]
Hmmm... OP's troubleshooting information does not show `transcend.io` connections?

**Comment by dportvine** [comment]
From which filter is this rule??
`##.notion-default-overlay-container.notion-overlay-container > d…`

<details>
<summary>Video</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/40fb9df3-20ee-4f62-b399-2317b0ebb612
</details>

@gorhill 
Is it possible to make long rules not cut off?

**Comment by gorhill** [comment]
> does not show `transcend.io` connections

Right, I just went with uncaught exception in console on my side, I do not have an account.

> Is it possible to make long rules not cut off?

No, otherwise this kind of issue will come back: <https://github.com/uBlockOrigin/uBlock-issues/issues/1852>
