### ISSUE TITLE
iphoneitalia.com: placeholder

### ISSUE THREAD

**Issue by enzor00** [uBlockOrigin/uAssets#19387]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.iphoneitalia.com/`

### Category

[unknown]

### Description

A black square appears within each news item below the photo

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/138575369/c2019271-a02c-4b92-b742-8baed1e79fa0
>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 109137
 cosmetic: 127073
 scriptlet: 21156
 html: 1020
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1189-5, 7m
  adguard-social: 21211-163, 7m
  adguard-cookies: 26638-35, 7m
  adguard-popup-overlays: 23296-857, 7m
  adguard-mobile-app-banners: 4500-7, 7m
  adguard-other-annoyances: 13271-9, 7m
  adguard-widgets: 2278-1, 7m
 default:
  user-filters: 0-0, never
  ublock-filters: 35144-457, 7m
  ublock-badware: 7718-0, 7m
  ublock-privacy: 494-0, 7m
  ublock-unbreak: 2160-1, 7m
  ublock-quick-fixes: 291-0, 7m
  easylist: 69936-820, 7m
  easyprivacy: 33292-721, 7m
  urlhaus-1: 6044-0, 7m
  plowe-0: 3720-2, 7m
  ITA-0: 10448-13, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 653 ms
 maxAssetCacheWait: 389 ms
popupPanel:
 blocked: 20
 network:
  iphoneitalia.com: 1
  googlesyndication.com: 1
  iubenda.com: 6
  sascdn.com: 2
  seedtag.com: 2
  skimresources.com: 2
  smartadserver.com: 2
  vidverto.io: 2
  viralize.tv: 2
 extended:
  ##.single-deals
  ##a[href*="//www.amazon."][href*="tag="]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
  ##.ad-space:not(.textads)
  ##ins.adsbygoogle
  ##.social-sharing
  #@#.ad-space
```
</details>

**Comment by JobcenterTycoon** [comment]
@khrin (filter suggestion: `iphoneitalia.com##.block_vidverto`)
