### ISSUE TITLE
jshosting.co.uk: breakage

### ISSUE THREAD

**Issue by justsimplehosting** [uBlockOrigin/uAssets#19383]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Privacy filter ||jshosting.*^ blocks genuine business website https://jshosting.co.uk/

### URL(s) where the issue occurs.

https://jshosting.co.uk
https://multicraft.jshosting.co.uk 
https://billing.jshosting.co.uk 
and with any sub derivative of jshosting.co.uk

### Screenshot(s)

([Multicraft Image](https://share.jshosting.co.uk/images/uzy1g92dzm8m6p37zlgvjg7xd.png))
([Billing image](https://share.jshosting.co.uk/images/nohvrw35dvfaqnnu47ke0qszf.png))
([Main domain](https://share.jshosting.co.uk/images/r287dth60byoayc5q7n420m1f.png ))

### Notes

This has been tested across various systems and platforms and always causes a block for our domain jshosting.co.uk.

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 98480
 cosmetic: 39433
 scriptlet: 18248
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69941-10, 55m
  easyprivacy: 33289-64, 55m
  plowe-0: 3720-1063, 55m
  ublock-badware: 7716-146, 1m
  ublock-filters: 34252-181, 1m
  ublock-privacy: 464-6, 55m
  ublock-quick-fixes: 288-45, 1m
  ublock-unbreak: 2112-34, 1m
  urlhaus-1: 6078-0, 55m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 786 ms
 maxAssetCacheWait: 5 ms
```
</details>

**Comment by okiehsch** [comment]
I will remove the filter, it's 5 years old and very likely obsolete anyway.
