### ISSUE TITLE
putlockernew.vc: nuisance

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#19388]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://putlockernew.vc/`

### Category

nuisance

### Description

The site prevents user from accessing developer console.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1b19
Firefox: 116
filterset (summary):
 network: 97186
 cosmetic: 39452
 scriptlet: 18231
 html: 1021
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35213-40, 2m
  ublock-badware: 7718-0, 2m
  ublock-privacy: 494-0, 2m
  ublock-unbreak: 2160-1, 2m
  ublock-quick-fixes: 333-109, 2m
  easylist: 69936-319, 2m
  easyprivacy: 33292-86, 2m
  urlhaus-1: 4798-0, 2m
  plowe-0: 3721-1068, 2m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 469 ms (selfie)
 maxAssetCacheWait: 250 ms
popupPanel:
 blocked: 1
 network:
  amung.us: 1
```
</details>

**Comment by ghajini** [comment]
these will work

```
movies2watch.ru,putlockernew.vc##+js(nostif, 0x)
movies2watch.ru,putlockernew.vc##+js(aost, console.clear)
movies2watch.ru,putlockernew.vc##+js(nostif, ||null)
```
