### ISSUE TITLE
gktech.uk: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#19391]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gktech.uk/`

### Category

detection

### Description

Ad-blocker detected

### Other extensions used

Violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 98564
 cosmetic: 30256
 scriptlet: 18250
 html: 1022
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35462-339, 8m
  ublock-badware: 7712-1, 8m
  ublock-privacy: 494-1, 8m
  ublock-unbreak: 2165-1, 8m
  ublock-quick-fixes: 291-0, 8m
  adguard-mobile: 8544-120, 8m
  easylist: 69936-16984, 8m
  easyprivacy: 33292-724, 8m
  urlhaus-1: 4798-0, 8m
  plowe-0: 3721-1, 8m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 20851 ms (selfie)
 maxAssetCacheWait: 2045 ms
popupPanel:
 blocked: 33
 network:
  doubleclick.net: 31
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by ghajini** [comment]
what is initiating site that led to this site?

**Comment by aicynide** [comment]
@ghajini https://gktech.uk/?adlinkfly=nq91folam
I can provide you other links needed also
