### ISSUE TITLE
mgnetu.com: ads

### ISSUE THREAD

**Issue by leonkennedy35** [uBlockOrigin/uAssets#19390]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mgnetu.com/T1ts`

### Category

ads

### Description

It shows ad whatever you do.

### Other extensions used

idm, chatgpt for google, some youtube extensions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98972
 cosmetic: 49893
 scriptlet: 19704
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13712-11, now
  easylist: 69936-29, now
  easyprivacy: 33292-69, now
  plowe-0: 3721-1067, now
  ublock-badware: 7716-146, now
  ublock-filters: 34276-188, now
  ublock-privacy: 463-6, now
  ublock-quick-fixes: 289-46, now
  ublock-unbreak: 2113-35, now
  urlhaus-1: 4798-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 461 ms (selfie)
 maxAssetCacheWait: 73 ms
popupPanel:
 blocked: 7
 network:
  a-ads.com: 3
  definedbootnervous.com: 1
  grunoaph.net: 2
  profitabledisplaynetwork.com: 1
 extended:
  ##.banner-728x90
  ##.banner-468x60
  ##.myTestAd
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(noeval-if, fairAdblock)
```
</details>

**Comment by ghajini** [comment]
@ryanbr

**Comment by theinstantmatrix** [comment]
Dead domain: Seized by government
