### ISSUE TITLE
[nsfw] freepasses.org: detection

### ISSUE THREAD

**Issue by BisArg** [uBlockOrigin/uAssets#19396]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://freepasses.org/`

### Category

detection

### Description

This website detects ublock origin and doesn't let browse. Site is filled with malicious pop-ups. Tried Element picker but that was of use. Element Zapper also could not help.

### Other extensions used

Buster: Captcha Solver for Humans - 2.0.1
Bitwarden - Free Password Manager - 2023.7.0
Canvas Fingerprint Defender - 0.2.1
Cookie-Editor - 1.11.0
Enhancer for YouTube - 2.0.119.2
FastForward - 0.2279
GoFullPage - Full Page Screen Capture - 7.12
IDM Integration Module - 6.41.16.2
Return YouTube Dislike - 3.0.0.10
SingleFile - 1.21.57
SponsorBlock for YouTube - Skip Sponsorships - 5.4.15
TWP - Translate Web Pages - 9.8.2.0
Violentmonkey - 2.15.0
WebRTC Network Limiter - 0.2.1.3

### Screenshot(s)

https://freepasses.org/

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 357353
 cosmetic: 256169
 scriptlet: 43776
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 181-0, 47m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=3: 0-0, 47m
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4827-115, now
  IND-0: 12520-0, 46m
  RUS-0: 39712-9, 47m
  adguard-cookies: 26645-41, now
  adguard-generic: 73214-662, now
  adguard-mobile: 8546-66, now
  adguard-mobile-app-banners: 4506-10, now
  adguard-other-annoyances: 13275-44, now
  adguard-popup-overlays: 23307-413, now
  adguard-social: 21215-915, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 8-0, never
  easylist: 69929-1639, now
  easyprivacy: 33292-16847, now
  plowe-0: 3721-1569, now
  ublock-badware: 7716-392, 47m
  ublock-filters: 34281-4269, 47m
  ublock-privacy: 463-69, now
  ublock-quick-fixes: 289-49, 46m
  ublock-unbreak: 2113-145, 47m
  urlhaus-1: 4798-1, 46m
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1485 ms (selfie)
 maxAssetCacheWait: 462 ms
popupPanel:
 blocked: 8
 network:
  freepasses.org: 1
  d2klx87bgzngce.cloudfront.net: 1
  doubleclick.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  intelligenceadx.com: 1
  wp.com: 1
```
</details>

**Comment by BisArg** [comment]
Why has this issue been closed?
That website still detects ublock.

**Comment by okiehsch** [comment]
Read the closing message, it says 
"closed this as completed in" and then links to the commit that fixed the issue https://github.com/uBlockOrigin/uAssets/commit/d80c695768528784a529486a8ecbee47e63ff8a1

If you update the `uBO-filters` list the site should work fine

**Comment by BisArg** [comment]
Very sorry, my bad. The issue has been resolved. 
Thank you for your speedy reply. You guys are great!
