### ISSUE TITLE
peliculasgoogledrive.info [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1939]
URL(s) where the issue occurs

`http://peliculasgoogledrive.info/jumanji-welcome-to-the-jungle-2017-hd-1080p-latino-googledrive/`

Describe the issue

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock  just show up when you enter for the second time

`http://peliculasgoogledrive.info/no-game-no-life-zero-2017-hd-1080p-latino-googledrive-silvestrehd/`

![2018-11-24_10h07_22](https://user-images.githubusercontent.com/36675858/48968638-24d5e100-efd1-11e8-815c-1483a731c118.png)
![2018-11-24_10h05_04](https://user-images.githubusercontent.com/36675858/48968639-28696800-efd1-11e8-8648-6591a237a4e2.png)
![2018-11-24_10h06_58](https://user-images.githubusercontent.com/36675858/48968641-2acbc200-efd1-11e8-9373-ae941abea412.png)

**Comment by mapx-** [comment]
add
`||escondeme.com^`

and test again

**Comment by lain566** [comment]
Same as https://github.com/uBlockOrigin/uAssets/issues/4713
```
acortar.live##+js(set-constant.js, v, true)
acortar.live^$popunder
```

Test link
`http://peliculasgoogledrive.info/el-reino-de-los-supermanes-2019-4k-remux-2160p-uhd-hdr-latino-googledrive-teslavohd/`

![114939c4-783e-4d9c-a1bb-295c0bb343f2](https://user-images.githubusercontent.com/27441315/52173861-726a8900-278c-11e9-8d0b-60dc6e8d3204.png)
