### ISSUE TITLE
cloud.mail.ru: ads

### ISSUE THREAD

**Issue by loxdogs** [uBlockOrigin/uAssets#19398]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cloud.mail.ru/public/MxRQ/GNav4ALXq`

### Category

ads

### Description

ads on the left, on the top, below

### Other extensions used

Alternate Player for Twitch.tv
Firefox Multi-Account Containers
Phind Search Engine
Search by Image
uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![uBlockOriginScreenshot](https://github.com/uBlockOrigin/uAssets/assets/90613854/c7a69eb3-c4c6-4ab6-9385-b9a25c4ccd97)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98419
 cosmetic: 39443
 scriptlet: 18213
 html: 1021
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35169-84, now
  ublock-badware: 7719-1, now
  ublock-privacy: 494-0, now
  ublock-unbreak: 2160-0, now
  ublock-quick-fixes: 292-0, now
  easylist: 69930-755, now
  easyprivacy: 33292-716, now
  urlhaus-1: 6027-0, now
  plowe-0: 3721-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 188 ms (selfie)
 maxAssetCacheWait: 76 ms
popupPanel:
 blocked: 126
 network:
  mail.ru: 117
  adlooxtracking.ru: 1
  adriver.ru: 1
  imgsmail.ru: 1
  tns-counter.ru: 2
  weborama-tech.ru: 1
  yadro.ru: 1
  yandex.ru: 2
 extended:
  ##div[id^="yandex_ad"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you enable `RU AdList` filter list and test again?

**Comment by loxdogs** [comment]
Yes, this fixed my issue! Didn't know you could do that
