### ISSUE TITLE
[nsfw] selcuksportshd663.xyz: ads

### ISSUE THREAD

**Issue by hakiyaka** [uBlockOrigin/uAssets#19406]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.selcuksportshd663.xyz/`

### Category

ads

### Description

In the mentioned website, it is not possible to block the advertisements on the livestreaming page.

This sentence conveys that on the website being referred to, there is an issue where the advertisements on the livestreaming page cannot be successfully blocked or prevented from appearing. This implies that despite attempts to block or disable the ads, they still show up on the livestreaming page, potentially causing inconvenience or frustration for users who want an ad-free experience.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://www.hizliresim.com/d9pn4e4
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 100255
 cosmetic: 49805
 scriptlet: 19717
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13715-11, now
  easylist: 69869-29, now
  easyprivacy: 33293-69, now
  plowe-0: 3721-1067, now
  ublock-badware: 7717-146, now
  ublock-filters: 34230-134, now
  ublock-privacy: 463-6, now
  ublock-quick-fixes: 286-46, now
  ublock-unbreak: 2113-35, now
  urlhaus-1: 6066-0, now
filterset (user): [empty]
trustedset:
 added: [array of 92 redacted]
switchRuleset:
 added: [array of 10 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 453 ms
 maxAssetCacheWait: 93 ms
popupPanel:
 blocked: 10
 network:
  selcuksportshd663.xyz: 5
  fout.jp: 1
  google-analytics.com: 1
  googletagmanager.com: 3
```
</details>

**Comment by ghajini** [comment]
@Alex-302
Adguard -Turkish

`selcuksportshd664.xyz##+js(set, adsConfig, [])`

**Comment by stephenhawk8054** [comment]
uBO supports regex for scriptlets

```adb
/(^\|.+\.)selcuksportshd\d+\.xyz/##+js(set, adsConfig, [])
```

But I don't know if Adguard translates it to uBO's syntax or not. @Yuki2718 Do you know? If not, we can add those filters to ours temporarily

**Comment by Yuki2718** [comment]
I don't know, let's wait for @Alex-302 's reply. If not, I can open an issue in Filterscompiler.

**Comment by ghajini** [comment]
> uBO supports regex for scriptlets
> 
> ```adb
> /(^\|.+\.)selcuksportshd\d+\.xyz/##+js(set, adsConfig, [])
> ```
> 
> But I don't know if Adguard translates it to uBO's syntax or not. @Yuki2718 Do you know? If the conversion is not there yet, I think we can add those filters to ours temporarily.

i guess for now this can be added?
can you?

**Comment by ghajini** [comment]
which alternative links?

**Comment by ghajini** [comment]
That happens without ubo also, not related to extensions

**Comment by kodiakhub** [comment]
These filters don’t work as a filter list in uBO, but they work if added to `My Filters`

`https://www.selcuksportshd0fa6d0b304.xyz/`

https://github.com/AdguardTeam/AdguardFilters/blob/e956a65699057ed497d416b09dfa7a54b5c6ebd9/TurkishFilter/sections/specific.txt#L4631-L4632
https://github.com/AdguardTeam/AdguardFilters/blob/e956a65699057ed497d416b09dfa7a54b5c6ebd9/TurkishFilter/sections/specific.txt#L4638-L4660

Can these filters be added to the uBO filter list like this? 🤔 

```adb
/selcuksportshd[a-z0-9-]+\.xyz/##.banner
/selcuksportshd[a-z0-9-]+\.xyz/##.banners
/selcuksportshd[a-z0-9-]+\.xyz/##.container > aside.sidebar:has(> .banner)
/selcuksportshd[a-z0-9-]+\.xyz/##.footer
/selcuksportshd[a-z0-9-]+\.xyz/##.socials a:is(.meritroyal, .iptv, .streamradar)
||blogger.googleusercontent.com/img/$domain=/main\.uxsyplayer[a-z0-9-]+\.click/
```
