### ISSUE TITLE
wetter.de: ads

### ISSUE THREAD

**Issue by Chriwro** [uBlockOrigin/uAssets#19401]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wetter.de/`

### Category

ads

### Description

Ads are not blocked

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 100745
 cosmetic: 44120
 scriptlet: 18208
 html: 1021
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35170-98, 8m
  ublock-badware: 7719-0, 8m
  ublock-privacy: 494-0, 8m
  ublock-unbreak: 2160-0, 8m
  easylist: 69930-761, 8m
  easyprivacy: 33292-725, 8m
  urlhaus-1: 6027-0, 8m
  plowe-0: 3721-2, 8m
  DEU-0: 7038-3, 8m
  ublock-quick-fixes: 288-0, 8m
filterset (user): [empty]
trustedset:
 added: [array of 35 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 571 ms (selfie)
 maxAssetCacheWait: 121 ms
popupPanel:
 blocked: 13
 network:
  wetter.de: 4
  adnxs-simple.com: 3
  criteo.net: 3
  googletagmanager.com: 1
  jubbie.de: 1
  opecloud.com: 1
 extended:
  ##.guj-ad-slot
  ##.gujAd
  #@#.outbrain-ad-slot
  #@#.base-ad-slot
  ##+js(no-xhr-if, homad-global-configs)
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by Chriwro** [comment]
Sorry, I forgot that there are no ads on the main page. But if you want to look at the weather of a city you get ads

**Comment by okiehsch** [comment]
I did not close the issue because I  did not see any ads, I actually get ads on the homepage.
If you read the closing message it says
"closed this as completed in" and then links to the commit that fixed your issue https://github.com/uBlockOrigin/uAssets/commit/668964f034676f6ca565449515c95faa4b859d74

If you update the uBO-filters list the site should work fine, i.e. no ads.
