### ISSUE TITLE
stfly.xyz: breakage

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#19400]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://stfly.xyz/x6hyqolam`

### Category

breakage

### Description

This website doesn't give final download link, it goes into a loop when ublock enabled 

### Other extensions used

Violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 99798
 cosmetic: 30270
 scriptlet: 18264
 html: 1022
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35483-339, now
  ublock-badware: 7713-1, now
  ublock-privacy: 494-1, now
  ublock-unbreak: 2165-1, now
  ublock-quick-fixes: 291-0, 22m
  adguard-mobile: 8546-120, now
  easylist: 69838-16876, now
  easyprivacy: 33292-724, now
  urlhaus-1: 6027-0, now
  plowe-0: 3721-1, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11508 ms (selfie)
 maxAssetCacheWait: 831 ms
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 2
  indelphoxom.com: 2
```
</details>

**Comment by ghajini** [comment]
all ok on mobile too
