### ISSUE TITLE
tomshardware.com: ads

### ISSUE THREAD

**Issue by nonBinaryTree** [uBlockOrigin/uAssets#19408]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tomshardware.com/best-picks/best-pc-speakers`

### Category

ads

### Description

Ad sidebar still appears, though blank

### Other extensions used

SteamDb, return YouTube dislikes, Roboform, IDM

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 98469
 cosmetic: 39441
 scriptlet: 18265
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69930-10, 1m
  easyprivacy: 33293-64, 1m
  plowe-0: 3721-1066, 1m
  ublock-badware: 7717-146, 1m
  ublock-filters: 34291-181, 1m
  ublock-privacy: 463-6, 1m
  ublock-quick-fixes: 286-46, 1m
  ublock-unbreak: 2113-34, 1m
  urlhaus-1: 6066-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 789 ms
 maxAssetCacheWait: 5 ms
popupPanel:
 blocked: 131
 network:
  3lift.com: 9
  adnxs.com: 9
  adsafeprotected.com: 12
  amazon-adsystem.com: 9
  bidswitch.net: 9
  btloader.com: 9
  casalemedia.com: 9
  contextweb.com: 4
  doubleclick.net: 5
  google-analytics.com: 3
  google.com: 2
  onetag-sys.com: 4
  permutive.com: 2
  pubmatic.com: 9
  rubiconproject.com: 10
  servebom.com: 5
  smartadserver.com: 5
  taboola.com: 7
  yieldmo.com: 9
```
</details>

**Comment by stephenhawk8054** [comment]
Hmmm... Weird that I don't see any cosmetic filters in OP's configuration?

**Comment by okiehsch** [comment]
Well. even if I disable cosmetic filtering no ad-sidebar appears on my end.

**Comment by gorhill** [comment]
> Weird that I don't see any cosmetic filters in OP's configuration

Not only that but the block count is way higher than what it should be.

**Comment by gorhill** [comment]
> Chromium: 115

Which exact browser/version is this?
