### ISSUE TITLE
myfxbook.com: detection

### ISSUE THREAD

**Issue by confeden** [uBlockOrigin/uAssets#19419]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.myfxbook.com/ru/forex-economic-calendar`

### Category

detection

### Description

"You have an Ad Blocker!" message banner

### Other extensions used

Checker Plus for Gmail
Url Shortener

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 115687
 cosmetic: 60415
 scriptlet: 19590
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 13-0, never
  RUS-0: 39721-9, now
  easylist: 69904-33, 58m
  easyprivacy: 33301-155, now
  plowe-0: 3721-1069, now
  ublock-badware: 7717-146, now
  ublock-filters: 34315-158, now
  ublock-privacy: 463-7, now
  ublock-quick-fixes: 286-101, now
  ublock-unbreak: 2113-34, now
  urlhaus-1: 6010-0, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 323 ms (selfie)
 maxAssetCacheWait: 89 ms
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##.ad-content:not(:empty)
  ##.ads-margin
  ##a[href^="https://pubads.g.doubleclick.net/"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/b8e16c0f5c133a1f182e806d1f201d0a379e5af2
