### ISSUE TITLE
divicast.com: popups

### ISSUE THREAD

**Issue by RajdeepG7000** [uBlockOrigin/uAssets#19417]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.divicast.com/movie`

### Category

popups

### Description

When pointing cursor over a search bar for example, it doesnt turn into the typing symbol, and when i click it it opens a new tab to redirect to spam. Almost like the entire page has become a transparent popup.

### Other extensions used

Some Email extensions. None related to content blockers

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-08-20 222041](https://github.com/uBlockOrigin/uAssets/assets/112893778/25b8e36b-9650-4d5d-892b-26f0a867d915)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 98440
 cosmetic: 39347
 scriptlet: 18274
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69901-10, now
  easyprivacy: 33300-64, now
  plowe-0: 3721-1066, now
  ublock-badware: 7717-146, now
  ublock-filters: 34240-127, now
  ublock-privacy: 463-6, now
  ublock-quick-fixes: 287-47, now
  ublock-unbreak: 2113-34, now
  urlhaus-1: 5972-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 115 ms (selfie)
 maxAssetCacheWait: 59 ms
popupPanel:
 blocked: 9
 network:
  addthis.com: 1
  rtmark.net: 4
  sharethis.com: 1
  tzegilo.com: 1
  woafoame.net: 2
 extended:
  ##+js(abort-current-script, parseInt, break;case $.)
```
</details>

**Comment by ghajini** [comment]
@Yuki2718 
pp regex filter need update to catch `chuxuwem.tv`

/^https?:\/\/[a-z]{8,15}\.(?:com|net|tv|xyz)\/5\/\d{6,7}(?:\?_=\d+)?$/$script,3p

**Comment by Yuki2718** [comment]
Maybe the time to switch to `[a-z]{2,3}`.
