### ISSUE TITLE
homedepot.com: breakage

### ISSUE THREAD

**Issue by JDWCOM** [uBlockOrigin/uAssets#19410]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.homedepot.com/s/wirerack?NCNI-5`

### Category

breakage

### Description

Ublock does not seem to block ads when I select them.   It works on other websites like yahoo.com

### Other extensions used

Privacy Badger, pihole, pfBlockerNG

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98366
 cosmetic: 39465
 scriptlet: 18212
 html: 1020
listset (total-discarded, last-updated):
 default:
  user-filters: 23-0, never
  ublock-filters: 35107-85, 3m
  ublock-badware: 7719-0, 2m
  ublock-privacy: 494-0, now
  ublock-unbreak: 2160-0, 2m
  ublock-quick-fixes: 288-0, 2m
  easylist: 69943-704, 3m
  easyprivacy: 33292-713, 2m
  urlhaus-1: 5972-0, 2m
  plowe-0: 3724-2, never
filterset (user): [array of 23 redacted]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 243 ms (selfie)
 maxAssetCacheWait: 76 ms
popupPanel:
 blocked: 50
 network:
  homedepot.com: 6
  btttag.com: 1
  d1wix2gc2cgqis.cloudfront.net: 1
  demdex.net: 9
  forter.com: 1
  go-mpulse.net: 2
  newrelic.com: 2
  px-cdn.net: 9
  px-cloud.net: 8
  pxchk.net: 10
  quantummetric.com: 1
 extended:
  ###sponsored-carousel-nucleus
```
</details>

**Comment by stephenhawk8054** [comment]
Can you screenshot which ads you are referring to?
