### ISSUE TITLE
porn.es [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1941]
URL(s) where the issue occurs

`https://porn.es/videos/1838/una-mujer-madura-le-ensena-los-placeres-del-sexo-a-una-joven.html`

https://i.imgur.com/8pn1H0x.png

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by KiLL4FuNK** [comment]
stop playback

**Comment by mapx-** [comment]
add
`||adn.porn.es/zone/`

**Comment by KiLL4FuNK** [comment]
the filter does not work
you can create a new filter and add it
diaux did not show up months ago

**Comment by KiLL4FuNK** [comment]
works well this

`||porn.es/zone/`
