### ISSUE TITLE
app.listening.io: breakage

### ISSUE THREAD

**Issue by 5wHN28Dg** [uBlockOrigin/uAssets#19415]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.listening.io/login`

### Category

breakage

### Description

I can't enter my email or password

### Other extensions used

Dark reader, clear URLs and web archive

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 100082
 cosmetic: 48055
 scriptlet: 21743
 html: 1209
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5401-8, now
 default:
  user-filters: 1-0, never
  ublock-filters: 35421-128, now
  ublock-badware: 7713-0, now
  ublock-privacy: 494-0, now
  ublock-unbreak: 2165-0, now
  ublock-quick-fixes: 288-0, now
  adguard-mobile: 8548-95, now
  easylist: 69919-741, now
  easyprivacy: 33298-722, now
  urlhaus-1: 5972-0, now
  plowe-0: 3721-2, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3106 ms (selfie)
 maxAssetCacheWait: 384 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by ghajini** [comment]
https://github.com/webcompat/web-bugs/issues/126096

firefox android browser issue , it is not caused by ublock origin....
To use this site in firefox android, click `desktop site` UA feature in browser
