### ISSUE TITLE
myaccounts.capitalone.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#19411]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://myaccounts.capitalone.com/`

### Category

breakage

### Description

It I attempt to open a dispute with the following options, I will get an error message telling me something went wrong when disabling uBlock will tell me that I need to call a certain phone number. To recreate it, just select report a problem on any transaction, say you are familiar with it and authorized the transaction then you will get to a question saying if you were overcharged or not. Select overcharged then the error box comes up, 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="795" alt="Screenshot 2023-08-19 172519" src="https://github.com/uBlockOrigin/uAssets/assets/69532417/b61ceb8b-a66b-41bb-8cf6-f2f2ca123488">
<img width="339" alt="Screenshot 2023-08-19 172602" src="https://github.com/uBlockOrigin/uAssets/assets/69532417/ff0ed42e-12fa-47eb-a34c-23ddbaa1bbff">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 286058
 cosmetic: 208437
 scriptlet: 41908
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 70022-101, 24m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 92776-21328, now
  adguard-generic: 72944-502, 24m
  adguard-mobile: 8548-52, 24m
  adguard-spyware-url: 1189-3, 24m
  block-lan: 48-0, now
  curben-phishing: 157486-42, 23m
  curben-pup: 189-0, 23m
  fanboy-cookiemonster: 48155-48154, 24m
  ublock-annoyances: 5379-272, 24m
 default:
  user-filters: 0-0, never
  easylist: 69869-1105, now
  easyprivacy: 33293-375, now
  plowe-0: 3721-1151, now
  ublock-badware: 7717-392, 24m
  ublock-filters: 34297-4203, 24m
  ublock-privacy: 463-11, 24m
  ublock-quick-fixes: 286-46, 23m
  ublock-unbreak: 2113-98, 24m
  urlhaus-1: 6066-2, 23m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1220 ms (selfie)
 maxAssetCacheWait: 902 ms
popupPanel:
 blocked: 15
 network:
  capitalone.com: 6
  d1af033869koo7.cloudfront.net: 1
  googletagmanager.com: 1
  newrelic.com: 1
  nr-data.net: 3
  omtrdc.net: 3
```
</details>

**Comment by stephenhawk8054** [comment]
Can you reset uBO to default settings and test again?

**Comment by jimmysofat6864** [comment]
Need more time for more transactions to show up on my account as there is only one and the only way to get it to work is if it is a transaction I haven't disputed.

**Comment by stephenhawk8054** [comment]
Then I will close the issue. You can continue here when you find more information.
