### ISSUE TITLE
iconmonstr.com: detection

### ISSUE THREAD

**Issue by PyXiion** [uBlockOrigin/uAssets#19425]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Detection
![Image](https://github.com/uBlockOrigin/uAssets/assets/59997570/6bffbdbf-deb8-45e2-b771-6da930871023)

### URL(s) where the issue occurs.

`https://iconmonstr.com/github-1-svg/` and at any icon page

### uBO version

1.51.0

### Browser name and version

Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0

### Settings

Default settings

**Comment by dportvine** [comment]
<details>
<summary>Screen</summary>

![2023-08-22_074538](https://github.com/uBlockOrigin/uAssets/assets/111344219/6ca309e6-cbbe-4d83-a20b-18185d311f7f)
</details>

```
https://cdns.iconmonstr.com/wp-content/plugins/kU7e4w0qiGsT)af-rvuHEJjC0YMG5y/wpdSja419+A3pJPMZFWxiJrc6C.js
```

**Comment by stephenhawk8054** [comment]
I can reproduce in chromium
