### ISSUE TITLE
[nsfw] nicekkk.com: popups

### ISSUE THREAD

**Issue by Forberg21** [uBlockOrigin/uAssets#19422]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nicekkk.com/mij/korean-tv-girl`

### Category

popups

### Description

Showing unwanted Ads(pop-ups)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 99835
 cosmetic: 42362
 scriptlet: 18411
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  KOR-1: 4486-10, now
  easylist: 69909-49, now
  easyprivacy: 33307-74, now
  plowe-0: 3723-1080, now
  ublock-badware: 7749-146, now
  ublock-filters: 34324-131, now
  ublock-privacy: 534-8, now
  ublock-quick-fixes: 284-107, now
  ublock-unbreak: 2107-33, now
  urlhaus-1: 5976-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 772 ms (selfie)
 maxAssetCacheWait: 282 ms
popupPanel:
 blocked: 4
 network:
  adsco.re: 1
  d3mzokty951c5w.cloudfront.net: 1
  displayvertising.com: 1
  juicyads.com: 1
```
</details>

**Comment by Forberg21** [comment]
Purge and update 202308220200(KST)

**Comment by Forberg21** [comment]
Purge and update 202308230200(KST)

Still have unwanted popups. Can u check again?

Not all time but sometimes popups come up

**Comment by stephenhawk8054** [comment]
I can't reproduce the popup even after browsing the site for a while.

**Comment by Forberg21** [comment]
Seems ok now. If happens again I'll report again. THX
