### ISSUE TITLE
bypass.city: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#19421]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bypass.city/bypass?bypass=https://linkvertise.com/555984/outr/1`

### Category

[unknown]

### Description

The site detects the ad blocker and prevents the page from being read.

### Other extensions used

none 

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/0cc21bb3-3b32-4721-9156-c2d3fb96ce9e)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 139258
 cosmetic: 113031
 scriptlet: 22428
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1637-0, 5m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2255-10, 7m
  RUS-0: 39720-170, now
  fanboy-cookiemonster: 48177-232, now
 default:
  FRA-0: 28160-35, now
  easylist: 69836-72, now
  easyprivacy: 33303-635, now
  plowe-0: 3721-1082, now
  ublock-badware: 7717-161, now
  ublock-filters: 34317-244, now
  ublock-privacy: 534-52, now
  ublock-quick-fixes: 281-107, now
  ublock-unbreak: 2113-39, now
  urlhaus-1: 6010-0, 6m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 539 ms (selfie)
 maxAssetCacheWait: 87 ms
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 1
  googlesyndication.com: 1
```
</details>

**Comment by Rust1667** [comment]
Please add their new alt domain `adbypass.org` to the filter

**Comment by amirhmhosin-lgtm** [comment]
Use the bypass.city
Go to key for that 
Can't need ads on this
You only need VPN
