### ISSUE TITLE
unian.ua: breakage

### ISSUE THREAD

**Issue by boomsya** [uBlockOrigin/uAssets#19437]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.unian.ua/war/povitryani-sili-rozpovili-skilki-rosiyskih-droniv-vdalosya-zbiti-vnochi-12368811.html`

### Category

breakage

### Description

wrong filter to .article-text
news content is hidden :(

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-08-23 at 10-52-37 Мости Криму непоправно пошкоджені у РФ залишилася одна дорога - британська розвідка](https://github.com/uBlockOrigin/uAssets/assets/8008462/2565d947-7e29-4e14-b20a-dccca94b95b7)
![Screenshot 2023-08-23 at 10-52-51 Мости Криму непоправно пошкоджені у РФ залишилася одна дорога - британська розвідка](https://github.com/uBlockOrigin/uAssets/assets/8008462/d1de1826-ac89-47bf-a59f-f65ed2ef3a0c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 117986
 cosmetic: 84759
 scriptlet: 20336
 html: 1047
listset (total-discarded, last-updated):
 added:
  adguard-popup-overlays: 23338-42, 4m
  adguard-mobile-app-banners: 4516-7, 4m
  easylist-chat: 132-0, 4m
 default:
  user-filters: 90-0, never
  ublock-filters: 35229-215, now
  ublock-badware: 7771-0, now
  ublock-privacy: 566-0, now
  ublock-unbreak: 2162-0, now
  ublock-quick-fixes: 288-0, 1h.57m
  easylist: 69685-737, now
  easyprivacy: 33308-771, now
  urlhaus-1: 5981-0, now
  plowe-0: 3726-2, now
  RUS-0: 39768-496, now
filterset (user): [array of 91 redacted]
trustedset:
 added: [array of 86 redacted]
 removed:
  about-scheme
  edge-scheme
switchRuleset:
 added: [array of 10 redacted]
urlRuleset:
 added: [array of 3 redacted]
userSettings:
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 447 ms (selfie)
 maxAssetCacheWait: 248 ms
popupPanel:
 blocked: 11
 no-cosmetic-filtering: true
 network:
  adtcdn.com: 2
  cloudflareinsights.com: 2
  doubleclick.net: 1
  gemius.pl: 1
  googletagmanager.com: 2
  idealmedia.io: 1
  membrana.media: 1
  unian.net: 1
 extended:
  ##.support-post
  ##.article-bottom
  ##.read-also-slider
  ##.article-text > ul
  ##.social-btn-bottom
  ##.banner-container
  ##.bnr-block__bnr
  ##.newsfeed__banner
  ##.partner-news
  ##[data-ad]
  ##div[style*="height"][style*="250px"]
  ##div[id*="ScriptRoot"]
  ##a[href*="www.unian.ua/lite/"]:xpath(../..)
  ##a[href*="sport.unian.ua/football/"]:xpath(../..)
  ##a[href*="sport.unian.ua/boxing/"]:xpath(../..)
  ##a[href*="www.unian.ua/curiosities/"]:xpath(../..)
```
</details>

**Comment by mapx-** [comment]
without the RUAdList the video stuff is blocked (but maybe is an ad ?!) and I need

```
@@||cdn.membrana.media^$script,xhr,domain=unian.ua
.ads.css$badfilter
```

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Yes, this is advertising, and `membrana.media` is an adserver.

**Comment by boomsya** [comment]
yesterday all be fine - ad video was not showing.
but today at morning all news text is hidden :(

at now I refresh filters - all OK. thanks.
