### ISSUE TITLE
tcbscans.com: ads

### ISSUE THREAD

**Issue by mysterious1001** [uBlockOrigin/uAssets#19436]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Most of the ads are blocked but there's still an ad left near the top of the page.

### URL(s) where the issue occurs.

`https://tcbscans.com/?date=22-8-2023-22`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/142955977/4431a318-212b-4258-9a82-208779e00301)

### uBO version

1.51.0

### Browser name and version

Firefox Version 116.0.3 (64-bit)

### Settings

No changes from default

### Notes

Uninstalled and reinstalled uBlock Origin. Tried it in incognito mode. Installed uBlock Origin in Chrome and tried it in Chrome incognito mode too.

**Comment by stephenhawk8054** [comment]
```adb
tcbscans.com##[href^="https://readcbr.com/"]
```

@ryanbr

**Comment by Saidiislam** [comment]
Happens regardless 
<hr/>
![image](https://github.com/uBlockOrigin/uAssets/assets/44663342/ecf37341-140a-4095-98fd-3d6596cbe9ac)

**Comment by mapx-** [comment]
add
`tcbscans.com##[href="https://ignread.com/"]`

@ryanbr
