### ISSUE TITLE
play.max.com: breakage

### ISSUE THREAD

**Issue by Michaellsterk** [uBlockOrigin/uAssets#19433]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.max.com/video/watch/3264f5f2-82ba-4275-a5f2-43e84ac0e852/f795e2e7-5fa3-4058-af05-3aeca03f88ca`

### Category

breakage

### Description

Every "Japanese Audio" version of the Studio Ghibli movies is broken by uBlock. The English audio versions do not have this issue. It seems to be some problem of uBlock over blocking necessary parts of the video player by default.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/34323970/0a0a80af-3984-49d3-a0f7-fe7bf4388236)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98459
 cosmetic: 39307
 scriptlet: 18241
 html: 1025
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35223-148, now
  ublock-badware: 7751-0, now
  ublock-privacy: 565-0, now
  ublock-unbreak: 2162-0, now
  ublock-quick-fixes: 286-0, 20m
  easylist: 69700-658, now
  easyprivacy: 33308-757, now
  urlhaus-1: 6033-0, 21m
  plowe-0: 3723-2, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 396 ms (selfie)
 maxAssetCacheWait: 173 ms
popupPanel:
 blocked: 20
 network:
  max.com: 7
  app.link: 3
  branch.io: 3
  brightline.tv: 2
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  litix.io: 3
 extended:
  ##+js(json-prune, ssaiInfo fallback.ssaiInfo)
  ##+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="Seg…
```
</details>

**Comment by stephenhawk8054** [comment]
We cannot investigate without an account. If you are williing to share the account credentials, I will give email to you.

**Comment by Michaellsterk** [comment]
I apologize as I am not comfortable with sharing the login credentials of my account. But at least this issue thread exists so someone else who is having the same issue and is comfortable with doing so is able to more easily

**Comment by stephenhawk8054** [comment]
The most I can investigate is looking at the dash .mpd file. If possible, can you do these steps?

1. Open new browser tab -> Press F12 to open browser's devtools -> Switch to `Networks` tab inside the devtools
2. In the same browser tab, load the website and reproduce the issue
3. In the devtools' `Networks` tab, there's a search/`Filter URLs` bar, type `.mpd` in that bar -> There will be 1 or multiple URLs in it
4. In each URL at step 3, click on it -> right click -> `Copy Value` -> `Copy Response`
5. Paste the response copied in step 4 to https://www.logpasta.com, click "Submit" -> click "View raw" at top right and copy the link here.

Since there can be multiple `.mpd` URLs, you can copy multiple `logpasta.com` here. If you can specify the order of the responses corresponding to the order of the URLs in step 3, it would be better.

**Comment by Michaellsterk** [comment]
https://www.logpasta.com/paste/raw/c5a3c182-e784-4098-81d1-d28b327662ba.txt

https://www.logpasta.com/paste/raw/a09dca75-8f9b-4986-bf4b-d120ff7bfd88.txt

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
play.max.com#@#+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="SegmentTimeline"])]), , .mpd)
play.max.com##+js(xml-prune, xpath(//*[name()="Period"][not(.//*[name()="SegmentTimeline"])][not(.//*[name()="ContentProtection"])]), , .mpd)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by Michaellsterk** [comment]
Yes this has appeared to have solved the issue. I don't know the filter formatting but I do notice the top one has a "#@#" and the other a "##" just want to make sure that is intended and not a type before this is possibly built into the main branch

**Comment by stephenhawk8054** [comment]
Yes, the first one is to disable the current filter, and the 2nd one is a new one.
