### ISSUE TITLE
simracingsetup.com: ads

### ISSUE THREAD

**Issue by stearless** [uBlockOrigin/uAssets#19434]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://simracingsetup.com/setups/acc-setups/audi-r8-lms-evo-ii/`

### Category

ads

### Description

There is a leftover floating banner at the bottom of the page, as well as bunch of fanatec ads for steering wheels popping up all over the place.

### Other extensions used

Bitwarden, NordVPN, Pushbullet, Dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 103860
 cosmetic: 100777
 scriptlet: 21207
 html: 1025
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 70085-536, 1m
  HRV-0: 358-1, 1m
 default:
  user-filters: 26-2, never
  ublock-filters: 35225-149, 1m
  ublock-badware: 7771-1, 1m
  ublock-privacy: 566-0, 1m
  ublock-unbreak: 2162-0, 1m
  ublock-quick-fixes: 288-0, 1m
  easylist: 69706-763, 1m
  easyprivacy: 33308-715, 1m
  urlhaus-1: 5972-0, 2m
  plowe-0: 3723-1, 1m
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 26 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 colorBlindFriendly: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 317 ms (selfie)
 maxAssetCacheWait: 147 ms
popupPanel:
 blocked: 4
 network:
  simracingsetup.com: 2
  googletagmanager.com: 2
 extended:
  ##.ad-fixed-bottom
  ##div.mySlides > [href="https://simracingsetup.com/links/moza-ra…
  ##[href="https://simracingsetup.com/links/podium-racing-wheel-fo…
  ###cookie-law-info-bar
  ###cliSettingsPopup
  ##.advert-container
```
</details>

**Comment by ad-blocking** [comment]
@ryanbr

```
simracingsetup.com##.ad-fixed-bottom
simracingsetup.com##.cta-box
```

**Comment by stephenhawk8054** [comment]
```adb
simracingsetup.com##.ad-fixed-bottom
simracingsetup.com##.cta-box
```

@ryanbr
