### ISSUE TITLE
blog.csdn.net: ads

### ISSUE THREAD

**Issue by felixesintot** [uBlockOrigin/uAssets#19431]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.csdn.net/partitioning/article/details/97632860`

### Category

ads

### Description

Unable to remove the ad

### Other extensions used

null

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98651799/5b5dc3fe-124c-4d89-9a94-226d98247025)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 113566
 cosmetic: 49623
 scriptlet: 18463
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  CHN-0: 25945-138, now
  easylist: 69618-63, now
  easyprivacy: 33307-77, now
  plowe-0: 3723-1067, now
  ublock-badware: 7749-146, now
  ublock-filters: 34341-144, now
  ublock-privacy: 534-6, now
  ublock-quick-fixes: 280-107, 1h.16m
  ublock-unbreak: 2115-33, now
  urlhaus-1: 5972-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1545 ms (selfie)
 maxAssetCacheWait: 555 ms
popupPanel:
 blocked: 5
 network:
  baidu.com: 1
  baidustatic.com: 1
  bdstatic.com: 1
  csdnimg.cn: 1
  toutiao.com: 1
 extended:
  ##div[style="min-height:250px;"]
```
</details>

**Comment by Yuki2718** [comment]
That's not an ad.
