### ISSUE TITLE
pricebefore.com: nuisance

### ISSUE THREAD

**Issue by sample081992** [uBlockOrigin/uAssets#19430]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pricebefore.com/nivea-men-oil-control-charcoal-100ml-pack-3-face-wash-m116619.html`

### Category

nuisance

### Description

the webpage loads properly. But after 5 seconds a skip button overlay comes up blocking the entire screen. i tried using element picker mode to remove the overlay by selecting the items. after reloading it still comes up 

### Other extensions used

idm internet download manager, search by image

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 331542
 cosmetic: 235392
 scriptlet: 42329
 html: 1212
listset (total-discarded, last-updated):
 added:
  adguard-generic: 73052-6584, 3m
  adguard-mobile: 8560-95, 3m
  adguard-spyware-url: 1191-67, 2m
  block-lan: 48-0, 2m
  curben-phishing: 160528-76, 2m
  curben-pup: 189-0, 2m
  adguard-social: 21229-839, 2m
  fanboy-thirdparty_social: 69-0, 2m
  fanboy-cookiemonster: 48190-3895, 2m
  fanboy-social: 16151-23, 2m
  ublock-annoyances: 5345-11, 2m
  IND-0: 12524-2, 2m
  [10 lists not shown]: [too many]
 default:
  user-filters: 5-1, never
  ublock-filters: 35220-476, 3m
  ublock-badware: 7751-0, 3m
  ublock-privacy: 565-0, 3m
  ublock-unbreak: 2162-1, 3m
  ublock-quick-fixes: 288-0, 3m
  easylist: 69618-869, 3m
  easyprivacy: 33307-819, 2m
  urlhaus-1: 5972-0, 2m
  plowe-0: 3723-2, 2m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 554 ms (selfie)
 maxAssetCacheWait: 405 ms
popupPanel:
 blocked: 3
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
 extended:
  ##.social-follow
  ##.grecaptcha-badge
  ##.mainAdContainer
  ##.companionAd
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://www.facebook.com/share.php?"]
  ##a[href*="//www.facebook.com/share.php"]
  ##a[href^="https://twitter.com/share"]
  ##a[title="Share on Facebook"]
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[id^="google_ads_iframe"]
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by mapx-** [comment]
Do we need an account to reproduce the issue ?

**Comment by sample081992** [comment]
No.

Account is not needed

**Comment by mapx-** [comment]
> [10 lists not shown]: [too many]

You have enabled a lot of lists.
Reset uBO to default settings and test again. Also => Disable any other extension before testing again.

**Comment by okiehsch** [comment]
>  I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

No offence but why is it so hard for many users to answer this question correctly?
You have enabled 22 additonal list are you not aware of the fact or did you not understand the question?

I ask out of curiosity, you are hardly the only one who does it, in fact I would say the majority of users opening an issue here do the same thing.

**Comment by okiehsch** [comment]
Wouldn't change a thing imo, they would tick or untick whatever sounds better, presuming they have the necessary language slills

**Comment by gorhill** [comment]
Another way is that I force a step before reporting to see if the issue exists with default settings/lists, but that would be a lot of work, this would require to save current configs, restore to default settings/lists, ask to check, confirm whether the issue is still present, then restore customizations.
