### ISSUE TITLE
aniwave.to: nuisance

### ISSUE THREAD

**Issue by 1Syeds786** [uBlockOrigin/uAssets#19448]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aniwave.to/watch/summer-time-rendering.yyjx/ep-24`

### Category

nuisance

### Description

the issue is that playing any video on this site works fine but when you pause the video. it shows its promotional banner (their ad about their other website) in the middle of the video. It disappears when you unpause the video but is slightly annoying. And this ad can't be permanently filtered or temporarily zapped by block origin tools.

I have attached a screenshot.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Web capture_24-8-2023_19161_aniwave to](https://github.com/uBlockOrigin/uAssets/assets/126792646/ccaff24d-e9ee-4ea0-acb8-7cbec8c79803)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98401
 cosmetic: 39287
 scriptlet: 18310
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 69599-10, now
  easyprivacy: 33308-63, now
  plowe-0: 3726-1065, now
  ublock-badware: 7776-146, now
  ublock-filters: 34343-122, now
  ublock-privacy: 535-6, now
  ublock-quick-fixes: 226-44, now
  ublock-unbreak: 2116-32, now
  urlhaus-1: 6007-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 15921 ms
 maxAssetCacheWait: 995 ms
popupPanel:
 blocked: 10
 network:
  amung.us: 1
  banquetunarmedgrater.com: 1
  bidgear.com: 5
  disqus.com: 1
  sharethis.com: 2
 extended:
  ##.adx
  ##+js(abort-on-property-read, AaDetector)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, mm)
  ##+js(abort-on-property-read, zfgstorage)
  ##+js(no-setInterval-if, break)
  ##+js(remove-attr, data-img|data-target, , stay)
  ##+js(no-window-open-if, !api?call=, 10, obj)
```
</details>

**Comment by ghajini** [comment]
Was fixed https://github.com/uBlockOrigin/uAssets/commit/a69c183407e5a0c0f941520fd8717555eb366a11
update filters
