### ISSUE TITLE
suaurl.com: detection

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#19442]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://suaurl.com/Pobreflixtitiorick`

### Category

detection

### Description

Annoying anti-adblock measure.

### Other extensions used

1. Absolute Enable Right Click & Copy 
2. Voltar Dislikes do Youtube 
3. Free Download Manager 
4. Enhancer for Youtube 
5. F.B Purity - Cleans up Facebook

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<[image](https://github.com/uBlockOrigin/uAssets/assets/129367686/0f26b9d9-bd24-4882-9ef2-3f9ab57e1900)>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 99794
 cosmetic: 42909
 scriptlet: 18594
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ublock-filters: 35238-271, now
  ublock-badware: 7767-1, now
  ublock-privacy: 566-0, now
  ublock-unbreak: 2164-0, now
  ublock-quick-fixes: 285-0, now
  easylist: 69640-606, now
  easyprivacy: 33308-771, now
  urlhaus-1: 5966-0, 19m
  plowe-0: 3726-1, now
  spa-1: 5474-13, now
filterset (user): [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 702 ms (selfie)
 maxAssetCacheWait: 299 ms
popupPanel:
 blocked: 21
 network:
  cleverwebserver.com: 2
  criticaltriggerweather.com: 2
  googletagmanager.com: 2
  nobeta.com.br: 2
  optad360.io: 4
  themoneytizer.com: 8
  xiti.com: 1
 extended:
  ##+js(remove-node-text, script, /window\.open|window\.location\.…
  ##+js(abort-on-property-read, document.oncontextmenu)
  ##+js(abort-on-property-read, shortcut)
  ##+js(no-window-open-if)
  ##+js(no-fetch-if, method:HEAD)
  ##+js(no-setTimeout-if, Por favor\, desative)
  ##+js(no-setInterval-if, /adblock|Por favor\, desative|adsbygoog…
  ##+js(set-constant, acdl, undefined)
  ##+js(no-setTimeout-if, window.location.href)
  ##+js(abort-current-script, $, notficationAd)
  ##+js(abort-current-script, open, document.getElementById)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by BRR34L0RD** [comment]
Initial URL is: https://suaads.com/Pobreflixtitiorick

**Comment by BlazeFTL** [comment]
`suaurl.com##+js(nostif, , 2000)
@@||suaurl.com^$ghide`

**Comment by dportvine** [comment]
Just block this `||suaads.com/peel1-ad-300x250.js$script`

**Comment by BRR34L0RD** [comment]
Nothing worked.

**Comment by ghajini** [comment]
yes because website is known circumventor

**Comment by BlazeFTL** [comment]
@BRR34L0RD 
```
suaurl.com##+js(nostif, , 2000)
suaurl.com##+js(nano-sib, cont, *)
suaurl.com##+js(aopr, suaadscheck2)
@@||suaurl.com^$ghide
suaurl.com##+js(nostif, /rtikgt|\b/)
```

**Comment by BRR34L0RD** [comment]
> 

Tested your filter, returns a little different response. Look at my new screenshot. 

![image](https://github.com/uBlockOrigin/uAssets/assets/129367686/a3fd7ba7-2b0b-48cf-b4c4-4321d6515042)

**Comment by BlazeFTL** [comment]
@BRR34L0RD You Are Testing When I Give Filters? SUS

```
suaurl.com##+js(nostif, , 1900)
suaurl.com##+js(nano-sib, cont, *)
suaurl.com##+js(aopr, suaadscheck2)
@@||suaurl.com^$ghide
suaurl.com##+js(acis, /gtu8|\fnc|\init|\suaadscheck|\suaadscheck2/)
suaurl.com##+js(nostif, /gtu8|\b/)
!suaurl.com##^script:has-text(divactioncheck)
suaurl.com##^script:has-text(themoneytizer|\googletagmanager/)
suaurl.com##+js(rpnt, script, div.textads.banner-ads.banner_ads.ad-unit.ad-zone.ad-space.adsbox, #btn-capcha)
suaurl.com##+js(rpnt, script, undefined', nop')
@@||ads.themoneytizer.com^$script,domain=suaurl.com
```

**Comment by BRR34L0RD** [comment]
> ```
> suaurl.com##+js(nostif, , 2000)
> suaurl.com##+js(nano-sib, cont, *)
> suaurl.com##+js(aopr, suaadscheck2)
> @@||suaurl.com^$ghide
> ```

Those ones, worked fine for me. Thanks a lot!!!

**Comment by BRR34L0RD** [comment]
BlazeFTL, Those lastest ones, worked fine for me. Thanks a lot!!!
