### ISSUE TITLE
com.nicovideo.jp: breakage

### ISSUE THREAD

**Issue by YukiseSora** [uBlockOrigin/uAssets#19447]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://com.nicovideo.jp/?cmnhd_ref=device%3Dpc%26site%3Dcommunity%26pos%3Dheader_servicelink`

### Category

breakage

### Description

真っ白になるが、uBlockを切ったら正常になる。

It becomes pure white, but it becomes normal when uBlock is turned off.

### Other extensions used

ニコニ貢献のキャンペーンの動画の問題だが、これらを加えたら改善になった。
It's another problem, but adding these made it better.

api.nicoad.nicovideo.jp
nicoad.nicovideo.jp

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![タイトルなし](https://github.com/uBlockOrigin/uAssets/assets/143085602/ace261e3-0ba3-41b6-99d6-aa70185623f3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 113614
 cosmetic: 49608
 scriptlet: 18406
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35221-97, 4m
  ublock-badware: 7778-1, 4m
  ublock-privacy: 566-0, 4m
  ublock-unbreak: 2164-0, 4m
  ublock-quick-fixes: 226-0, 4m
  easylist: 69599-746, 3m
  easyprivacy: 33308-729, 3m
  urlhaus-1: 5966-0, 3m
  plowe-0: 3726-1, 3m
  CHN-0: 25968-141, 3m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 235 ms
 maxAssetCacheWait: 96 ms
popupPanel:
 blocked: 4
 network:
  nicovideo.jp: 3
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||ads.nicovideo.jp/assets/js/ads2.js$script,domain=com.nicovideo.jp
```

@Yuki2718 For AG JP?

**Comment by Yuki2718** [comment]
The rule is already there. @YukiseSora Please enable AdGuard Japanese as this is a Japanese site.

**Comment by YukiseSora** [comment]
FirefoxもChromeも治ったの確認しました。ありがとうございます。

I've confirmed that both Firefox and Chrome are fixed.thank you.
