### ISSUE TITLE
my.petinsurance.com: breakage

### ISSUE THREAD

**Issue by adampk17** [uBlockOrigin/uAssets#19459]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://my.petinsurance.com/login`

### Category

breakage

### Description

Page fails to load using Edge and uBlock Origin

### Other extensions used

Lastpass, Rakuten

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-08-24 163024](https://github.com/uBlockOrigin/uAssets/assets/61219368/843126a7-8ba3-44cb-a32d-a5bc9372897f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98416
 cosmetic: 39302
 scriptlet: 18319
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69633-10, 1m
  easyprivacy: 33310-63, 1m
  plowe-0: 3726-1065, 1m
  ublock-badware: 7777-146, 1m
  ublock-filters: 34342-122, 1m
  ublock-privacy: 538-6, 1m
  ublock-quick-fixes: 232-49, 1m
  ublock-unbreak: 2116-32, 1m
  urlhaus-1: 6007-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 273 ms
 maxAssetCacheWait: 100 ms
popupPanel:
 blocked: 4
 network:
  petinsurance.com: 1
  bing.com: 1
  googletagmanager.com: 1
  typekit.net: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by

```adb
/new-relic.$~stylesheet
```

in EasyPrivacy.

@ryanbr
