### ISSUE TITLE
di.fm: detection

### ISSUE THREAD

**Issue by Jetsyanksdevils9** [uBlockOrigin/uAssets#19455]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.di.fm/`

### Category

detection

### Description

To recreate the issue, go to `www.di.fm` and create a free account. Then play one of "Today's Free Channels" on the front page.  After a few minutes of playing, maybe 10 at most, it will display the page in the screenshot.  Disabling the adblocker results in constant annoying ads that interrupt the music.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![difm](https://github.com/uBlockOrigin/uAssets/assets/143128910/f5832711-19a6-43c3-8a1a-63dac2fe3385)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98419
 cosmetic: 39306
 scriptlet: 18316
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 69633-10, now
  easyprivacy: 33310-63, now
  plowe-0: 3726-1065, now
  ublock-badware: 7777-146, now
  ublock-filters: 34341-122, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 226-44, now
  ublock-unbreak: 2116-32, now
  urlhaus-1: 6007-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 812 ms
 maxAssetCacheWait: 302 ms
popupPanel:
 blocked: 7
 network:
  adswizz.com: 2
  cookielaw.org: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  pub.network: 2
 extended:
  #@##panel-ad
  #@#+js(set-constant, di.VAST.XHRURLHandler, noopFunc)
```
</details>

**Comment by Jetsyanksdevils9** [comment]
Thank you all for looking into this, however the above fix [8449a9a](https://github.com/uBlockOrigin/uAssets/commit/8449a9aec8934b279a7b2f2a7b787af80269c8d3) did not work.

**Comment by Jetsyanksdevils9** [comment]
Issue #19455 was closed however the issue is not fixed.  The attached screenshot appears when UBO is detected.  To recreate the issue, go to the below url and create a free account.  Then play one of "Today's Free Channels" on the front page. The detection occurs specifically at the end of a song, but not at the end of every song.  It seems fix [8449a9a](https://github.com/uBlockOrigin/uAssets/commit/8449a9aec8934b279a7b2f2a7b787af80269c8d3) is preventing mid-song detection but detection still occurs at the end of a song. Thank you in advance :)

**Comment by stephenhawk8054** [comment]
@Jetsyanksdevils9 Can you test these filters?

```adb
di.fm##+js(set, di.app.WebplayerApp.Ads.Supervisor.eligibleForPreroll, trueFunc)
di.fm##+js(set, di.app.WebplayerApp.Ads.Supervisor.eligibleForMidroll, trueFunc)
```

**Comment by Jetsyanksdevils9** [comment]
> @Jetsyanksdevils9 Can you test these filters?
> 
> ```
> di.fm##+js(set, di.app.WebplayerApp.Ads.Supervisor.eligibleForPreroll, trueFunc)
> di.fm##+js(set, di.app.WebplayerApp.Ads.Supervisor.eligibleForMidroll, trueFunc)
> ```

Working beautifully! No detection for a full 30 minutes. Thank you so much for your time!
