### ISSUE TITLE
di.fm: detection

### ISSUE THREAD

**Issue by Jetsyanksdevils9** [uBlockOrigin/uAssets#19465]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Issue #19455 was closed however the issue is not fixed.  The attached screenshot appears when UBO is detected.  To recreate the issue, go to the below url and create a free account.  Then play one of "Today's Free Channels" on the front page. The detection occurs specifically at the end of a song, but not at the end of every song.  It seems fix [8449a9a](https://github.com/uBlockOrigin/uAssets/commit/8449a9aec8934b279a7b2f2a7b787af80269c8d3) is preventing mid-song detection but detection still occurs at the end of a song. Thank you in advance :)

### URL(s) where the issue occurs.

`www.di.fm`

### Screenshot(s)

![difm](https://github.com/uBlockOrigin/uAssets/assets/143128910/98a39fb9-174e-4552-b008-e5d10fc0aa92)

### Notes

I made sure I updated the extension after fix [8449a9a](https://github.com/uBlockOrigin/uAssets/commit/8449a9aec8934b279a7b2f2a7b787af80269c8d3) and I also tried pasting lines 4181 and 4183 from this fix into my filters.  I also tried installing a fresh firefox (I am a chrome user) and installing a fresh UBO; the detection occurred within 10 minutes.

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98366
 cosmetic: 39283
 scriptlet: 18325
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69587-10, 1m
  easyprivacy: 33311-63, 1m
  plowe-0: 3724-1065, 1m
  ublock-badware: 7777-146, 1m
  ublock-filters: 34344-122, 1m
  ublock-privacy: 538-6, 1m
  ublock-quick-fixes: 247-40, 1m
  ublock-unbreak: 2116-32, 1m
  urlhaus-1: 5964-0, 1m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 11 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 382 ms (selfie)
 maxAssetCacheWait: 139 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue in the old thread. We are all notified with new comments, no need to open duplicated issue.

When I go to your comment again, it's deleted so I cannot know what you said.
