### ISSUE TITLE
Animeland.tv

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#1946]
### URL(s) where the issue occurs

`http://ww4.animeland.tv/dagashi-kashi-2nd-season-episode-11-english-dubbed`

### Describe the issue

Ads

### Settings

Default settings.

### Notes

A large portion of the ads appear to be chrome only. The chrome only ones can be stopped with `animeland.tv##script:inject(abort-current-inline-script.js,String.fromCharCode,parseInt)`, put that appears to kill the video player as well. I used `/animeland\.tv\/[0-9a-f]{32}\/[0-9a-f\-]{36}\.jpg/$domain=animeland.tv,image` for the sidebar ads, but there is probably a better non-regex way to do it.

**Comment by okiehsch** [comment]
Just fyi, if you see `amgload` or `piguiqproxy` requests, the easiest fix is to redirect those requests, which fixes Chrome and to use `##^script:has-text()` to disable the inline-script causing those requests in Firefox.

**Comment by uBlock-user** [comment]
`animeland.tv##script:inject(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)` works fine here, no need to `redirect` requests for this case.
