### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by aphroditebeast** [uBlockOrigin/uAssets#19460]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=hpli9XAMYks`

### Category

detection

### Description

I am using uBlock Origin on Microsoft Edge to block ads on YouTube. However, I am now getting the following popup when I try to watch a video:

Ad blockers violate YouTube's Terms of Service
It looks like you may be using an ad blocker. Video playback is blocked unless YouTube is allowlisted or the ad blocker is disabled.
Ads allow YouTube to be used by billions worldwide at no charge.
You can go ad-free with YouTube Premium, and creators can still get paid from your subscription.

I have tried the following to fix this issue:
I have refreshed my browser.
I have cleared my browser's cache and cookies.
I have updated uBlock Origin to the latest version.
However, the issue still persists.

I would appreciate it if you could help me fix this issue.

Thank you for your time.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2023-08-25 055552](https://github.com/uBlockOrigin/uAssets/assets/143143932/7b1d01f3-c49b-4706-ad90-4726ce72879e)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98373
 cosmetic: 39302
 scriptlet: 18319
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69633-10, now
  easyprivacy: 33310-63, now
  plowe-0: 3726-1065, now
  ublock-badware: 7777-146, now
  ublock-filters: 34342-122, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 232-49, now
  ublock-unbreak: 2116-32, now
  urlhaus-1: 5964-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 364 ms (selfie)
 maxAssetCacheWait: 115 ms
popupPanel:
 blocked: 9
 network:
  youtube.com: 5
  doubleclick.net: 2
  google.co.in: 1
  google.com: 1
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
Please follow the prerequisites truthfully:

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

and continue here: https://github.com/uBlockOrigin/uAssets/issues/7636
