### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by JackRabbitDJ** [uBlockOrigin/uAssets#19462]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=Cl16ZUNCm64`

### Category

ads and youtube premium Bs.

### Description

Youtube is forcing users to pay for premium to not watch ads.

### Other extensions used

STANDS ad blocker, AdBlock Plus, Sponsor Block, and Return Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screen Shot 2023-08-25 at 1 52 24 AM](https://github.com/uBlockOrigin/uAssets/assets/142070008/2718e8af-ac54-41fd-a71e-3b7515916a2a)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 106
filterset (summary):
 network: 98353
 cosmetic: 39281
 scriptlet: 18320
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-1, never
  easylist: 69587-10, 8m
  easyprivacy: 33311-63, 8m
  plowe-0: 3726-1065, 8m
  ublock-badware: 7777-146, 8m
  ublock-filters: 34346-122, 8m
  ublock-privacy: 538-6, 8m
  ublock-quick-fixes: 232-49, 8m
  ublock-unbreak: 2116-32, 8m
  urlhaus-1: 5964-0, 8m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 253295 ms (selfie)
 maxAssetCacheWait: 1370 ms
popupPanel:
 blocked: 11
 network:
  youtube.com: 6
  doubleclick.net: 3
  google.com: 1
  livewwwfine.com: 1
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytd-merch-shelf-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##ytd-companion-slot-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by JackRabbitDJ** [comment]
Btw, love your blocker, its very nice.

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Please continue here: https://github.com/uBlockOrigin/uAssets/issues/7636
