### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by wiznia** [uBlockOrigin/uAssets#19467]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://twitter.com/home`

### Category

breakage

### Description

Tweets disappear and reappear again as I scroll down or up on my feed.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[https://imgur.com/a/5GqDhyi](url)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98383
 cosmetic: 39234
 scriptlet: 18237
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 16-0, never
  easylist: 69616-10, now
  easyprivacy: 33311-63, now
  plowe-0: 3724-1065, now
  ublock-badware: 7786-146, now
  ublock-filters: 34351-122, now
  ublock-privacy: 539-6, now
  ublock-unbreak: 2115-32, now
  urlhaus-1: 5991-0, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 68 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 216 ms (selfie)
 maxAssetCacheWait: 119 ms
popupPanel:
 blocked: 18
 network:
  twitter.com: 17
  google-analytics.com: 1
 extended:
  ##div:nth-of-type(7)
  ##div[data-testid="cellInnerDiv"] > div.css-1dbjc4n > div[class=…
  ##div[data-testid="trend"]:has(path[d$="10H8.996V8h7v7z"])
  ##[data-testid="trend"]:has-text(/Promoted|Gesponsert|Promociona…
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
extended:
  ##div:nth-of-type(7)
```

This filter does not belong to any uBO's default lists. Can you check your custom filters again?

**Comment by wiznia** [comment]
You are absolutely right, thank you. I never realized I had a custom filter applied.
