### ISSUE TITLE
shareus.io: ads

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#19471]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shareus.io/IHCL33`

### Category

ads

### Description

theres many ads and countdown

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1rc2
Chromium Mobile: 110
filterset (summary):
 network: 106024
 cosmetic: 128929
 scriptlet: 25934
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-cookies: 27412-29, now
  adguard-mobile-app-banners: 4576-8, now
  adguard-other-annoyances: 13323-8, now
  adguard-popup-overlays: 23517-58, now
  adguard-social: 21261-908, now
  adguard-widgets: 2288-4, now
  ublock-annoyances: 5489-186, now
  ublock-cookies-adguard: 304-304, now
 default:
  adguard-mobile: 8579-8, now
  easylist: 69583-120, now
  easyprivacy: 33312-137, now
  plowe-0: 3724-1140, now
  ublock-badware: 7780-147, now
  ublock-filters: 34668-537, now
  ublock-privacy: 539-8, now
  ublock-quick-fixes: 298-64, now
  ublock-unbreak: 2120-36, now
  urlhaus-1: 5968-0, now
filterset (user): [array of 0 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1807 ms (selfie)
 maxAssetCacheWait: 371 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
You Can Try These -
```
shareus.io,shrs.link##.purple
shareus.io,shrs.link##.free.payment-button > .space-between.align-center.flex, .button-texts.space-between.align-center.flex:others()
nregajobcard.in,cookar.net,cookoz.net,shramikcard.in,cookad.net,jobform.in##+js(aopr, ai_wait_for_jquery)
nregajobcard.in,cookar.net,cookoz.net,shramikcard.in,jobform.in,cookad.net###topButton, #bottomButton, #topText, .shrs_btn, #topClickButton, #bottomClickButton, #topTimer, #bottomTimer, #lottie-player, #scanURL:others()
shareus.io,shrs.link##+js(set-cookie, local_history, false)
shareus.io,shrs.link##.ads.action-button:others()
```
However Timer Bypass Isnt Possible Or Would Give Blank Page In Final Destination

If SomeOne ByPass That

**Comment by Fatcavill** [comment]
thank you sir but how do i use it ?

**Comment by BlazeFTL** [comment]
@Fatcavill Just Goto Settings>My Filters

**Comment by Fatcavill** [comment]
But there is so many timers
thanks🙏

**Comment by ghajini** [comment]
@ryanbr
