### ISSUE TITLE
keran.co: detection

### ISSUE THREAD

**Issue by lyubomyrhv** [uBlockOrigin/uAssets#19478]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://keran.co/ADA/index.php`

### Category

detection

### Description

Detection

### Other extensions used

Detection

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 117868
 cosmetic: 65080
 scriptlet: 19584
 html: 1048
listset (total-discarded, last-updated):
 added:
  DEU-0: 7064-3, now
 default:
  user-filters: 3-0, never
  ublock-filters: 35232-124, now
  ublock-badware: 7788-0, now
  ublock-privacy: 570-0, now
  ublock-unbreak: 2164-1, now
  ublock-quick-fixes: 248-0, now
  easylist: 69511-721, now
  easyprivacy: 33324-815, now
  urlhaus-1: 6000-0, now
  plowe-0: 3724-2, now
  RUS-0: 39795-14, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 908 ms (selfie)
 maxAssetCacheWait: 404 ms
popupPanel:
 blocked: 12
 network:
  keran.co: 2
  bmcdn5.com: 1
  bmcdn6.com: 2
  cloudflareinsights.com: 2
  coinzillatag.com: 1
  ctengine.io: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by ghajini** [comment]
proxy got restricted ,hence i don't get antiadb
force update filters that might help
