### ISSUE TITLE
guildstats.eu: detection

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#19472]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

placeholder/leftover - adblock detected (see screenshot documentation)

### URL(s) where the issue occurs.
```
https://guildstats.eu/index.php?lang=en
https://guildstats.eu/index.php?lang=nl
https://guildstats.eu/index.php?lang=pt
https://guildstats.eu/index.php?lang=es
```
### Screenshot(s)

<details>

When ads is loaded (wait 10-30 sec after page was fully loaded):

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/e0ecf5c4-c93a-495d-a87c-ac811395b6ea)

When I block ads:

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/2b4c09ef-a123-41cd-973f-5df290b5515a)

</details>

### uBO version

1.51.1rc2

### Browser name and version

Firefox 117.0 RC 2

### Settings

- uBo Annoyances
- POL 0
- POL 2

### Notes

```adb
##.gDiv:matches-css(background: /bad\.gif/):has(> *:not(script):matches-css(display: none))
```

**Comment by ghajini** [comment]
its just a small warning i guess

**Comment by okiehsch** [comment]
Yes, fixing it in annoyances is fine.
