### ISSUE TITLE
Can you help me,Thanks

### ISSUE THREAD

**Issue by lcqlcq5** [uBlockOrigin/uAssets#1947]
1.The website was attacked and has been inserted script,But we have cleared the script.
2.As long as the buyer's browser has installed Adblock,then he cannot go shopping normally
3.We find that [resource-abuse.txt](https://github.com/uBlockOrigin/uAssets/blob/a692750cd2d8f1455e79a509625dbd9912cca6e1/filters/resource-abuse.txt) has put our website tomtop.com into the blacklist
4. Really hope you can help us to solve this problem,we want to appeal for this,if you need any information just feel free to ask us,we will reply you asap.
Best Regards

@okiehsch

**Comment by Hrxn** [comment]
But you did check the site, right? Just to be sure...

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/0a87abc2d178b91e9ca403c9bf3b9bb2de479858#commitcomment-28169209 I did check and after three weeks I think it is safe to say that their cleanup was thorough.
