### ISSUE TITLE
old.reddit.com: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#19473]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://old.reddit.com/`

### Category

privacy

### Description

The following is a (potentially non-exhaustive) list of POST endpoints used by `old.reddit.com` for event collections. So far, I have not met any new one.

```
www.reddit.com/api/comment
www.reddit.com/api/vote
www.reddit.com/api/login
www.reddit.com/api/register
www.reddit.com/api/friend
www.reddit.com/api/share
www.reddit.com/api/submit
```

Note that each line can also be suffixed with `.json`, adding the total to 14 combination, chosen at random for each navigation.

Some findings from my non-exhaustive testing:
1. Testing registration, logging in, and voting both on `www.reddit.com` and `old.reddit.com`, blocking the three endpoint does not interfere with the functionality of its namesake. I have not tested the functionality related to the namesake of the other four.
2. The `www` subdomain must be included, at the very least with `vote` because not doing so will break voting on `www.reddit.com`.
3. The specific path after `/api/` must be included because not doing so will break registration, at the very least.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1rc2
Firefox: 116
filterset (summary):
 network: 98444
 cosmetic: 39304
 scriptlet: 18303
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35241-40, now
  ublock-badware: 7788-0, now
  ublock-privacy: 570-0, now
  ublock-unbreak: 2163-1, now
  ublock-quick-fixes: 298-62, now
  easylist: 69578-258, now
  easyprivacy: 33323-84, now
  urlhaus-1: 6056-0, now
  plowe-0: 3724-1067, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 531 ms
 maxAssetCacheWait: 298 ms
popupPanel:
 blocked: 3
 network:
  reddit.com: 2
  redditmedia.com: 1
 extended:
  ##.promotedlink
  ##.adsense-ads
  ##.googads
  ##.googleAd
  ##.hasads
  ##.native-ad
  ##.HeaderAd
  ##.NavBarAd
  ##.ad-medium
  ##.post-ad
  ##.promoad
  ##.rectad
  ##.sidebar-ad:not(.adsbygoogle)
  ##.small-ad
  ##.sponsorAd
  ##.sponsorPost
  ##a.outbound[data-outbound-url]:remove-attr(data-outbound-url)
  #@#.sidebar-ad
  #@#+js(replace-node-text, script, outboundUrl, outbound)
  #@#+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  #@#+js(json-prune, data.children.[].data.outbound_link)
```
</details>

**Comment by krystian3w** [comment]
Can you rewrite this into filters?

My draft:

```adb
||www.reddit.com/api/comment
||www.reddit.com/api/vote$domain=~www.reddit.com
||www.reddit.com/api/login
||www.reddit.com/api/register
||www.reddit.com/api/friend
||www.reddit.com/api/share
||www.reddit.com/api/submit
```

**Comment by partingscientist** [comment]
The non-trivial part is ensuring no functionality is broken. I do not use and also not familiar with Reddit, so I cannot test this exhaustively.

**Comment by mapx-** [comment]
> I do not use and also not familiar with Reddit, so I cannot test this exhaustively

high probability of breaking functionalities

**Comment by stephenhawk8054** [comment]
I'm not too confident if the fixes need to block error URL. Reddit is known for constantly circumventing privacy filters, and it might cause breakages for many users if they change something again.
