### ISSUE TITLE
delta.com: breakage

### ISSUE THREAD

**Issue by HandMeBacon** [uBlockOrigin/uAssets#19486]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.delta.com/change-trip/`

### Category

breakage

### Description

When attempting to change a trip on delta.com I am redirected to delta.com/change-trip/ and presented with a blank white screen. 

Steps I took to troubleshoot:
1. Reset uBO to default settings
2. Disabled all other extensions
3. Performed a search for the filter(s) that break the site:
    a. Disabled approximately half of the filters (leaving all uBlock filters enabled) - the site worked
    b. Enabled half of the previously disabled filters (leaving only EasyList and EasyPrivacy disabled) - the site worked
    c. Enabled EasyPrivacy - the site broke
    d. Disabled EasyPrivacy and enabled EasyList - the site worked
4. Conclusion is that EasyPrivacy breaks the site

### Other extensions used

I troubleshot with all other extensions disabled.

### Screenshot(s)

<details>
<summary>Broken vs Working Screenshots</summary>

![Broken](https://github.com/uBlockOrigin/uAssets/assets/6731408/6cbcd08f-c032-4237-bec1-33d208c3135a)
![Working](https://github.com/uBlockOrigin/uAssets/assets/6731408/4292f73a-c852-4a7e-9c08-e2aa358def4e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 343646
 cosmetic: 227813
 scriptlet: 43451
 html: 1213
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 7m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 71121-7333, 7m
  https://secure.fanboy.co.nz/fanboy-annoyance.txt: 77019-64710, 7m
  adguard-generic: 73263-6597, 8m
  adguard-mobile: 8579-122, 8m
  adguard-spyware-url: 1192-67, 8m
  block-lan: 48-0, 8m
  curben-phishing: 166881-77, 8m
  curben-pup: 189-0, 8m
  adguard-social: 21261-708, 8m
  fanboy-thirdparty_social: 69-0, 8m
  fanboy-cookiemonster: 48280-275, 8m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35259-125, 8m
  ublock-badware: 7798-1, 8m
  ublock-privacy: 567-75, 8m
  ublock-unbreak: 2164-2, 8m
  ublock-quick-fixes: 274-0, 8m
  easylist: 69550-946, 8m
  easyprivacy: 33329-803, 8m
  urlhaus-1: 6000-0, 8m
  plowe-0: 3724-1, 7m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1693 ms
 maxAssetCacheWait: 1002 ms
popupPanel:
 blocked: 14
 network:
  delta.com: 4
  go-mpulse.net: 1
  techlab-cdn.com: 4
  trackjs.com: 5
```
</details>

**Comment by okiehsch** [comment]
Thx for the extensive troubleshooting on your end, makes it easier for us. 👍 

`@@||cdn.trackjs.com/agent/*/latest/t.js$script,domain=delta.com`
fiyes the issue on my end.
@ryanbr

**Comment by HandMeBacon** [comment]
Thank you okiehsch! I can confirm that fixes it on my end as well.

**Comment by stephenhawk8054** [comment]
Do these work?

```adb
delta.com##+js(set, TrackJS, {})
delta.com##+js(set, TrackJS.isInstalled, noopFunc)
delta.com##+js(set, TrackJS.install, noopFunc)
```
