### ISSUE TITLE
wolframalpha.com: ads

### ISSUE THREAD

**Issue by MoonPhoenix83** [uBlockOrigin/uAssets#19483]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wolframalpha.com/input?i2d=true&i=Power%5B%5C%2840%294-x%5C%2841%29%2C6%5D`

### Category

ads

### Description

Ads for the Wolfram alpha pro subscription still appear on the site

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1436" alt="Screenshot 2023-08-27 at 17 35 50" src="https://github.com/uBlockOrigin/uAssets/assets/57860887/ea529a66-66e9-4941-9bbf-74686e180080">

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98325
 cosmetic: 39322
 scriptlet: 18269
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ublock-filters: 35247-98, now
  ublock-badware: 7793-0, now
  ublock-privacy: 570-0, 1h.59m
  ublock-unbreak: 2164-0, now
  easylist: 69523-691, now
  easyprivacy: 33326-715, now
  urlhaus-1: 6000-0, now
  plowe-0: 3724-2, now
  ublock-quick-fixes: 247-0, 1h.58m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3027 ms (selfie)
 maxAssetCacheWait: 973 ms
popupPanel:
 blocked: 1
 network:
  wolfram.com: 1
```
</details>

**Comment by ghajini** [comment]
They are 1st party subscriptions ,not ads. we don't address that
