### ISSUE TITLE
[nsfw] trendyporn.com: ads

### ISSUE THREAD

**Issue by Malgotra** [uBlockOrigin/uAssets#19480]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.trendyporn.com/`
`https://www.trendyporn.com/video/bima-babu-hindi-season-01-episodes-1-3-web-series-23-8-2023-95817.html/`

### Category

ads

### Description

Ads leftover

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230827-161311](https://github.com/uBlockOrigin/uAssets/assets/122884037/cb5c23d9-7795-431a-b746-e6ede654955b)
![Screenshot_20230827-161335](https://github.com/uBlockOrigin/uAssets/assets/122884037/37a7a33e-9e02-414d-ad8f-d19200ed2944)
![Screenshot_20230827-161358](https://github.com/uBlockOrigin/uAssets/assets/122884037/7c891e52-20ba-4fd7-9392-bd7ed61d5065)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 127179
 cosmetic: 160559
 scriptlet: 39069
 html: 1214
listset (total-discarded, last-updated):
 added:
  adguard-generic: 73261-5612, 11m
  easylist-annoyances: 3916-91, 11m
  easylist-chat: 133-0, 11m
  fanboy-cookiemonster: 48265-291, 11m
  easylist-newsletters: 6351-13, 11m
  easylist-notifications: 2648-3, 11m
  fanboy-social: 16156-6, 11m
  ublock-annoyances: 5450-338, 11m
  IND-0: 12528-2, 11m
  ublock-cookies-easylist: 304-0, 10m
 default:
  user-filters: 0-0, never
  ublock-filters: 35539-134, 12m
  ublock-badware: 7782-1, 11m
  ublock-privacy: 570-0, 11m
  ublock-unbreak: 2168-0, 11m
  ublock-quick-fixes: 247-0, 11m
  adguard-mobile: 8579-106, 12m
  easylist: 69578-769, 11m
  easyprivacy: 33323-812, 11m
  urlhaus-1: 6000-0, 11m
  plowe-0: 3724-1, 11m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6234 ms
 maxAssetCacheWait: 3247 ms
popupPanel:
 blocked: 9
 network:
  bestzba.com: 4
  googletagmanager.com: 1
  lby2kd27c.com: 4
 extended:
  ##.container > div.row:has(> div.well h4:contains(LIVE MODELS))
  ##.container > div.row:has(> div a[href^="//ptosrd.com/"])
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`trendyporn.com##center > div:has-text(Advertisement)`

**Comment by mapx-** [comment]
@Malgotra report at [easylist repository](https://github.com/easylist/easylist/issues)
