### ISSUE TITLE
snaptik.app

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#19485]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`snaptik.app` has a new button called "Download HD". It does not work since it is supposed to show an ad.

I would suggest to block/hide this button.

### URL(s) where the issue occurs.

Go to `https://snaptik.app/` and insert a TikTok link (e.g. `https://www.tiktok.com/@mrbeast/video/7029781410701626671`), then see the "Download HD" button.

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/30274161/e36c24ff-6f3e-425e-a2c8-2faf252c0103)

### uBO version

1.51.0

### Browser name and version

Firefox 116.0.3 (64-bit)

### Settings

<details><spoiler>

```
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 114172
 cosmetic: 189237
 scriptlet: 28529
 html: 1213
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 712-9, 17h.15m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2256-78, 17h.14m
  adguard-spyware-url: 1192-179, 57m
  adguard-social: 21261-838, 57m
  fanboy-thirdparty_social: 68-0, 3d.3h.33m
  fanboy-cookiemonster: 48190-3938, 5d.3h.34m
  fanboy-social: 16147-23, 6d.22h.7m
  ublock-annoyances: 5340-283, 6d.22h.6m
  spa-1: 5498-11, 57m
  adguard-cookies: 27412-60, 57m
  adguard-popup-overlays: 23517-1536, 56m
  adguard-mobile-app-banners: 4578-1058, 56m
  [8 lists not shown]: [too many]
 default:
  user-filters: 159-1, never
  ublock-filters: 35230-422, 1d.4h.16m
  ublock-badware: 7788-0, 1d.4h.15m
  ublock-privacy: 494-2, 6d.22h.8m
  ublock-unbreak: 2164-1, 1d.4h.14m
  ublock-quick-fixes: 247-0, 56m
  easylist: 69628-824, 3d.3h.31m
  easyprivacy: 33308-827, 3d.3h.30m
  urlhaus-1: 6056-0, 17h.16m
  plowe-0: 3721-2, 8d.2h.9m
filterset (user): [array of 151 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 422 ms (selfie)
 maxAssetCacheWait: 183 ms
```
</spoiler></details>

### Notes

Filter `snaptik.app##.btn-download-hd.button` seems to resolve the issue.

**Comment by ghajini** [comment]
@ryanbr

**Comment by dhi184759-source** [comment]
https://vt.tiktok.com/ZS56xXbXM/

**Comment by dhi184759-source** [comment]
https://vt.tiktok.com/ZS56xXbXM/
