### ISSUE TITLE
lightrun.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#19482]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lightrun.com/answers/puppeteer-puppeteer-save-screenshots-as-avif-images`

### Category

breakage

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/85698031-cc9a-4223-9c17-c35b043f26ee)

disable ublock origin
![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/2561ab87-faa4-4848-803f-c1f3af2e6bbd)

### Other extensions used

no, using incognito

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98396
 cosmetic: 39303
 scriptlet: 18329
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69578-10, 2m
  easyprivacy: 33323-63, 2m
  plowe-0: 3724-1065, 2m
  ublock-badware: 7786-146, 2m
  ublock-filters: 34351-122, 2m
  ublock-privacy: 539-6, 2m
  ublock-quick-fixes: 247-40, 2m
  ublock-unbreak: 2115-32, 2m
  urlhaus-1: 6000-0, 2m
filterset (user): [empty]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 495 ms
 maxAssetCacheWait: 228 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
```
</details>

**Comment by ghajini** [comment]
This happens without ublock origin or without extensions

**Comment by 3xploiton3** [comment]
> https://lightrun.com/answers/puppeteer-puppeteer-save-screenshots-as-avif-images

without extension except ublock origin
![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/4093f45f-2166-498f-a589-2225e489ca95)

**Comment by 3xploiton3** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/81fa975a-975b-4f4a-93e3-2f41ea4fe394)

**Comment by Jmennius** [comment]
Happens to me as well. Disabling ublock origin for this website (by pressing the 'power' button in the extension and refreshing makes the issue go away). Also the website works fine in a private session without extensions.
