### ISSUE TITLE
offidocs.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#1949]
### URL(s) where the issue occurs

`https://www.offidocs.com/osessionx01/`

### Describe the issue

anti adblock

### Screenshot(s)

https://vgy.me/5ohEIO.png

### Versions

- Browser/version: chromium 65
- uBlock Origin version: 1.15.24

### Settings

- default settings

**Comment by SMed79** [comment]
Thank you.

**Comment by uBlock-user** [comment]
`offidocs.com##body > div:has-text(Adblock)` works just fine.
