### ISSUE TITLE
cricfree.org: ads

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#19493]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cricfree.org/basketball/ivory-coast-iran-cfdamh12`

& `https://livebri.net/vok4.php` and many other similar domains

### Category

ads

### Description

Possible solution:
```
###micast_ads
##body > #overover[style*="silver;"]
##body > #overover[style*="silver;"] ~ #obrazek
```

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cree](https://github.com/uBlockOrigin/uAssets/assets/20126984/e9a828f7-aaa7-4ba0-9c7f-1018a5b357de)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1rc2
Firefox: 115
filterset (summary):
 network: 115450
 cosmetic: 60421
 scriptlet: 19642
 html: 1048
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35280-115, 5m
  ublock-badware: 7798-1, 5m
  ublock-privacy: 567-0, 5m
  ublock-unbreak: 2164-1, 5m
  ublock-quick-fixes: 331-18, 5m
  easylist: 69478-716, 5m
  easyprivacy: 33332-715, 5m
  urlhaus-1: 5957-0, 5m
  plowe-0: 3724-1, 5m
  RUS-0: 39794-136, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3658 ms
 maxAssetCacheWait: 13 ms
popupPanel:
 blocked: 32
 network:
  cricfree.org: 2
  adsco.re: 1
  betteradsystem.com: 1
  blockertv.xyz: 2
  d2kk0o3fr7ed01.cloudfront.net: 1
  google-analytics.com: 1
  googletagmanager.com: 5
  jsdelivr.net: 3
  movemeforward.co: 1
  peppaping.xyz: 4
  stolenforensicssausage.com: 1
  tumblebit.org: 8
  twitter.com: 2
 extended:
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, afScript)
  ##div[style="position: fixed; display: block; width: 100%; heigh…
```
</details>

**Comment by dimisa-RUAdList** [comment]
For me, this content is still available. Try: `https://livebri.net/vok4.php` or any other stream from the main page `https://cricfree.org/`

**Comment by dportvine** [comment]
>###micast_ads
>##body > #overover[style*="silver;"]
>##body > #overover[style*="silver;"] ~ #obrazek

I still see ads.

<details>
<summary>Screen</summary>

![2023-08-28_162800](https://github.com/uBlockOrigin/uAssets/assets/111344219/0ccf4d20-53e4-4df3-86da-1373d241a30a)
</details>

**Comment by dimisa-RUAdList** [comment]
Most likely, depending on the geolocation, different ads work there.

**Comment by dportvine** [comment]
This stream works. `https://cricfree.org/baseball/los-angeles-dodgers-arizona-diamondbacks-cfdamhlb?l=3270666195`

**Comment by stephenhawk8054** [comment]
I too can only access `https://livebri.net/vok4.php`. I can't access the links on the home page `https://cricfree.org/` either.

**Comment by dportvine** [comment]
For me, need more rules.

`https://livebri.net/vok4.php`

<details>
<summary>Screen</summary>

![2023-08-29_103913](https://github.com/uBlockOrigin/uAssets/assets/111344219/ecf52d26-34ff-4fcd-8e3a-d12c2ad3a160)
![2023-08-29_103947](https://github.com/uBlockOrigin/uAssets/assets/111344219/50701673-15aa-4c04-a666-0204359a496a)
</details>

```adb
darsalam.net##body > #overover[style*="silver;"]
darsalam.net##body > #overover[style*="silver;"] ~ #obrazek
darsalam.net##.clappr-banner
```

`https://cricfree.org/tennis/mertens-elise-bjorklund-mirjam-cfdamhf7?l=3270666195`

<details>
<summary>Screen</summary>

![2023-08-29_103015](https://github.com/uBlockOrigin/uAssets/assets/111344219/c0d3f057-9edb-4a2f-821d-38477b54ca58)
![2023-08-29_103058](https://github.com/uBlockOrigin/uAssets/assets/111344219/7a7465c3-2656-497f-b1c5-e65ddcdd506f)
</details>

```adb
iseeyouandyouseeme.me###floatLayer1
darsalam.net##.clappr-banner
```

`https://cricfree.org/`

<details>
<summary>Screen</summary>

![2023-08-29_103226](https://github.com/uBlockOrigin/uAssets/assets/111344219/727a64b9-0b98-4b33-b421-671f9dd603bc)
![2023-08-29_103304](https://github.com/uBlockOrigin/uAssets/assets/111344219/9311b996-0112-4fa6-9700-8bef290a492b)
![2023-08-29_105109](https://github.com/uBlockOrigin/uAssets/assets/111344219/a1c93916-67d0-40f0-a131-09d0ce708567)
</details>

**Comment by dportvine** [comment]
@stephenhawk8054 

Can you also hide this banner on the main page? There are also advertising links.

<details>
<summary>Screen</summary>

![2023-08-29_135915](https://github.com/uBlockOrigin/uAssets/assets/111344219/27334265-ca08-4e7d-9f04-a2e15a53cee9)
</details>

`https://lgbtqirights.xyz/view/ip1s59uz83si6k9?l=3270666195`
`https://bovinae.xyz/2/sm9ayzx5au/10vke200bi511s80?safe_links=true?l=3270666195`

**Comment by dportvine** [comment]
@mapx- 
banner on the main page `https://cricfree.org/`

<details>
<summary>Screen</summary>

![2023-08-30_170702](https://github.com/uBlockOrigin/uAssets/assets/111344219/b789f8ed-b24d-460a-87d4-81a0f2cb0849)
</details>

**Comment by mapx-** [comment]
I get that banner only disabling uBO

**Comment by dportvine** [comment]
Ok.

**Comment by mapx-** [comment]
I tested using an Ukraine IP Address too, still blocked

**Comment by dportvine** [comment]
>I tested using an Ukraine IP Address too, still blocked

Then why am I seeing this banner?

<details>
<summary>Screen</summary>

![2023-08-30_215838](https://github.com/uBlockOrigin/uAssets/assets/111344219/0e7fe031-ebbe-4539-8be9-681a756f3d7e)
![2023-08-30_220009](https://github.com/uBlockOrigin/uAssets/assets/111344219/4cc063e9-f4ee-4a53-adf4-3f2b252326b2)
</details>

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 122725
 cosmetic: 128622
 scriptlet: 26051
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26474-18, 7m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1642-25, 7m
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 783-0, 7m
  fanboy-cookiemonster: 48335-416, 7m
  ublock-annoyances: 5440-61, 7m
  ublock-cookies-easylist: 271-271, 7m
 default:
  user-filters: 0-0, never
  ublock-filters: 34457-44, 7m
  ublock-badware: 7870-0, 7m
  ublock-privacy: 538-7, 7m
  ublock-unbreak: 2120-7, 7m
  ublock-quick-fixes: 214-40, 7m
  easylist: 69561-285, 7m
  easyprivacy: 33283-403, 7m
  urlhaus-1: 5919-0, now
  plowe-0: 3724-1069, now
  RUS-0: 39866-290, 7m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 1056 ms (selfie)
 maxAssetCacheWait: 549 ms
popupPanel:
 blocked: 7
 network:
  cricfree.org: 1
  facebook.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  tumblebit.org: 2
  twitter.com: 1
 extended:
  ##a[href^="https://twitter.com/share"]
  ##body .twitter-share-button
  ##.twitter-share-button
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, afScript)
  ##html:style(overflow:auto!important)
```
</details>

**Comment by mapx-** [comment]
Test

`*.gif$image,domain=cricfree.org`

or

`||peppaping.xyz^`

**Comment by dportvine** [comment]
They both works.
