### ISSUE TITLE
cryptofun.space: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#19494]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cryptofun.space/`

### Category

detection

### Description

Ad blocker detected. Showing pop-up notification for disable adblocker.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cry](https://github.com/uBlockOrigin/uAssets/assets/75168867/07bece0b-94ab-4b84-98f5-2ca254b07bc0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98244
 cosmetic: 39366
 scriptlet: 18397
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 65-0, never
  easylist: 69478-10, now
  easyprivacy: 33332-63, now
  plowe-0: 3724-1064, now
  ublock-badware: 7796-146, now
  ublock-filters: 34391-126, now
  ublock-privacy: 536-6, now
  ublock-quick-fixes: 277-66, now
  ublock-unbreak: 2116-33, now
  urlhaus-1: 5957-0, now
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 24 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11501 ms
 maxAssetCacheWait: 4131 ms
popupPanel:
 blocked: 11
 network:
  a-ads.com: 1
  adaround.net: 1
  adbit.biz: 1
  bmcdn2.com: 3
  coinzillatag.com: 3
  dlvideo.pro: 1
  freehostedscripts.net: 1
 extended:
  ###ad728
```
</details>

**Comment by BlazeFTL** [comment]
@Lahiru2002 
```
@@||dlvideo.pro/prebid.js$script,domain=cryptofun.space
cryptofun.space##div.grid_2
cryptofun.space##.\35 95221f76d4b2a002038c42d

**Comment by BlazeFTL** [comment]
@Lahiru2002 I Cant Reproduce..
