### ISSUE TITLE
[nsfw] rontymobile.in: detection

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#19507]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rontymobile.in/?pid=690986&lid=ylEMaB&vid=194270855`

### Category

detection

### Description

Detect ublock

https://hanalist.blogspot.com/p/kiki-delivery-hindi-dub-triple-audio.html?m=1

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-08-29-12-19-41-264_us spotco fennec_dos](https://github.com/uBlockOrigin/uAssets/assets/96541364/73a817de-3f37-449d-9892-16d9ae7bca03)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 94479
 cosmetic: 111008
 scriptlet: 24508
 html: 1216
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
  urlhaus-1: null
  plowe-0: null
 added:
  easylist-annoyances: 3932-91, 19m
  easylist-chat: 133-0, 19m
  fanboy-cookiemonster: 48323-291, 19m
  easylist-newsletters: 6376-13, 19m
  easylist-notifications: 2652-3, 19m
  fanboy-social: 16220-6, 19m
  ublock-annoyances: 5461-342, 19m
  ublock-cookies-easylist: 308-0, 19m
 default:
  user-filters: 0-0, never
  ublock-filters: 35598-117, 19m
  ublock-badware: 7797-0, 19m
  ublock-privacy: 567-0, 19m
  ublock-unbreak: 2169-1, 19m
  ublock-quick-fixes: 283-0, 36m
  easylist: 69471-354, 19m
  easyprivacy: 33338-115, 19m
filterset (user): [empty]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 821 ms (selfie)
 maxAssetCacheWait: 301 ms
popupPanel:
 blocked: 11
 network:
  rontymobile.in: 1
  arglingpistole.com: 2
  doubleclick.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 3
 extended:
  ##.td-scroll-up
  ##.tdm_block_socials
  ##.tdm-social-wrapper
  ##.tds-social1
  ##.tdm-social-item-wrap
  ##.td-icon-facebook
  ##.td-icon-instagram
  ##.td-icon-twitter
  ##.td-icon-youtube
  ##.td-social-list
  ##.td_social_type
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[id^="google_ads_iframe"]
```
</details>

**Comment by ghajini** [comment]
fix here needs revise

```
rontymobile.in#@#+js(abort-on-property-read, AdbModel) rontymobile.in##+js(no-fetch-if, googlesyndication) @@||gplinks.in/track/js/main.js$script,domain=rontymobile.in @@||gplinks.in/track/data.php$xhr,domain=rontymobile.in rontymobile.in##+js(set, count, 0) rontymobile.in##.adb-overlay 
```

but in the end `gplinks.co` doesn't show the link, can anyone reproduce?

**Comment by okiehsch** [comment]
> in the end gplinks.co doesn't show the link, can anyone reproduce?


Yes, it's the same on my end, if I whitelist gplinks I get an anti ablock message...

**Comment by MayaBi7** [comment]
> fix here needs revise
> 
> ```
> rontymobile.in#@#+js(abort-on-property-read, AdbModel)
> rontymobile.in##+js(no-fetch-if, googlesyndication)
> @@||gplinks.in/track/js/main.js$script,domain=rontymobile.in
> @@||gplinks.in/track/data.php$xhr,domain=rontymobile.in
> rontymobile.in##+js(set, count, 0)
> rontymobile.in##.adb-overlay 
> ```
> 
> but in the end `gplinks.co` doesn't show the link, can anyone reproduce?

Don't know what you're saying !! but it's working... thanks 👍

**Comment by okiehsch** [comment]
@MayaBi7 so you can download the file at the end?

**Comment by MayaBi7** [comment]
> @MayaBi7 so you can download the file at the end?

Yup..!👍

**Comment by ghajini** [comment]
In the end did you get link button?

**Comment by okiehsch** [comment]
Ok, Iupdated the fix it should work now after updating the `uBO-filters` list.

**Comment by ghajini** [comment]
> Ok, I updated the fix it should work now after updating the `uBO-filters` list.

so you also get => get link button in end?

**Comment by MayaBi7** [comment]
> In the end did you get link button? a screenshot?

Open in new tab and it worked👍
![Screenshot_2023-08-29-17-13-13-673_us spotco fennec_dos](https://github.com/uBlockOrigin/uAssets/assets/96541364/6632e650-2141-4f41-a4e0-d5e3211dc6e6)

**Comment by BlazeFTL** [comment]
There Is A Timer Check/How Long It Takes To Click In The Buttons..Then It Shows Error At Last Page Or Blank Page

**Comment by MayaBi7** [comment]
> There Is A Timer Check/How Long It Takes To Click In The Buttons..Then It Shows Error At Last Page Or Blank Page

Just click..u need not to wait..
