### ISSUE TITLE
converter-btc.world: ads

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#19505]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://converter-btc.world/faucet`

### Category

ads

### Description

ads left

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/75168867/a4476a8e-5a5a-4f8b-9d0f-3b977166c00b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98163
 cosmetic: 39384
 scriptlet: 18411
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 67-0, never
  easylist: 69476-10, 41m
  easyprivacy: 33338-63, 41m
  plowe-0: 3724-1064, 41m
  ublock-badware: 7801-146, 41m
  ublock-filters: 34411-125, 41m
  ublock-privacy: 536-6, 41m
  ublock-quick-fixes: 283-66, 41m
  ublock-unbreak: 2116-33, 41m
  urlhaus-1: 5870-0, 41m
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 17039 ms (selfie)
 maxAssetCacheWait: 1408 ms
popupPanel:
 blocked: 12
 network:
  a-ads.com: 2
  bmcdn6.com: 4
  cpx-research.com: 1
  cryptocoinsad.com: 3
  ctengine.io: 1
  surfe.pro: 1
 extended:
  ##+js(abort-current-script, eval, replace)
  ##+js(no-setTimeout-if, offsetHeight, 100)
```
</details>

**Comment by BlazeFTL** [comment]
@Lahiru2002 Use Element Picker Or Learn To Use
Would Help You To Remove Those Things

**Comment by okiehsch** [comment]
Isee no leftover on my end.

**Comment by BlazeFTL** [comment]
@Lahiru2002 You Have To Select Better Element..Sometimes The Numbers Would Get Randomized
