### ISSUE TITLE
kinoheld.de Anti-Adblock

### ISSUE THREAD

**Issue by thetommes** [uBlockOrigin/uAssets#1951]
### URL(s) where the issue occurs
All kinoheld ticket-sites, for example: (Reload if it doesn't appear the first time visiting)
`https://www.kinoheld.de/kino-solingen/das-lumen-filmtheater-solingen/vorstellung/51409#panel-seats`

### Describe the issue

Site shows an error-message "Please disable AdBlock or uBlock an try again". Access for booking tickets is being denied.

### Screenshot(s)

https://imgur.com/a/s4Efh

### Versions

- Browser/version: Chrome version 65.0.3325.181 (64-Bit)
- uBlock Origin version: 1.15.24

### Settings

My filterlists: https://i.imgur.com/9tg1e6C.png

### Notes

Tested on multiple PC's, message still appears

**Comment by mapx-** [comment]
test this filter
`||googletagmanager.com/gtm.js$script,redirect=noopjs,domain=kinoheld.de`

What other `kinoheld ticket-sites`  do you know using same method ?

**Comment by KiLL4FuNK** [comment]
update the filters @thetommes

**Comment by thetommes** [comment]
`||googletagmanager.com/gtm.js$script,redirect=noopjs,domain=kinoheld.de` works! Is uAssets the right place to add this filter or should I report it to EasyList?
kinoheld is a german website which offers a back and frontend for booking cinema-tickets almost everywhere in Germany. Often, local cinemas implement their widget, but this should be no problem for this filter. Thanks

**Comment by mapx-** [comment]
The filter was already added to ublock filters (easylist cannot include such filters - as is a general list for all adblockers, ABP for example does not understand redirect filters)
