### ISSUE TITLE
pasazer.com: detection

### ISSUE THREAD

**Issue by Amongus6969** [uBlockOrigin/uAssets#19513]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pasazer.com/news/463834/nowa,strategie,lot,u,poznamy,za,kilka,tygodni,najpewniej,po,wyborach.html`

### Category

detection

### Description

You can't read the article unless you disable uBlock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/113198536/4fb941b3-c314-4e6e-8b0d-a60202746675)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 99531
 cosmetic: 46939
 scriptlet: 18528
 html: 1038
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35324-128, now
  ublock-badware: 7803-1, now
  ublock-privacy: 567-0, now
  ublock-unbreak: 2164-1, now
  ublock-quick-fixes: 250-0, now
  easylist: 69467-706, now
  easyprivacy: 33340-715, now
  urlhaus-1: 5870-0, now
  plowe-0: 3724-1, now
  POL-0: 7995-27, now
  POL-2: 1279-12, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 207 ms (selfie)
 maxAssetCacheWait: 65 ms
popupPanel:
 blocked: 11
 network:
  pasazer.com: 4
  google-analytics.com: 1
  googlesyndication.com: 5
  rentalcars.com: 1
 extended:
  ##ins.adsbygoogle
  ##.ads_footer
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Amongus6969** [comment]
Please make sure you visit this article (or any other), and not the main page: https://www.pasazer.com/news/463834/nowa,strategie,lot,u,poznamy,za,kilka,tygodni,najpewniej,po,wyborach.html

**Comment by okiehsch** [comment]
I did, I can't read the article but I can see it.
![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/c2a8146f-7037-4bd9-aef8-5097df947589)
