### ISSUE TITLE
[NSFW] vsex.in: breakage

### ISSUE THREAD

**Issue by arifyilmaz-hb** [uBlockOrigin/uAssets#19517]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I try to open videos uploaded to the netu.tv player on the vsex.in site, first a circle appears on a holding screen. Then, when you click on the circle that appears anywhere on the player screen, the actual player start screen appears. Clicking on the circle opens a pop-up screen window. These pop-up websites appear randomly when you open the video for the first time, fast-forward the video, maximise the screen, stop the video and resume it again. In short, when you click anywhere on the player, a pop up site opens. 

uBlock does not show the content of these pop-up websites, but it does not close them automatically or prevent them from opening at all. 

* Apart from these problems, netu.tv gives a warning that VPN is detected if Opera VPN is open. 

### URL(s) where the issue occurs.

All links are NSFW 

`https://vsex.in/79370-cunnilingus-spices-her-morning-coffee.html`

`https://vsex.in/8225-dirty-tricks.html`

### Screenshot(s)

**Video Start Process:**

https://github.com/uBlockOrigin/uAssets/assets/137331002/0ebdd4e3-b188-47ce-8210-62b155eda523

https://github.com/uBlockOrigin/uAssets/assets/137331002/df3e63d1-0cc4-4207-85aa-6dad48360ddb

https://github.com/uBlockOrigin/uAssets/assets/137331002/6aee50a9-5bab-41ff-8662-70f5d1412c63

### Notes

I use Tunnel Bear extension to access the site because the site is blocked in my country. Greece and Argentina are not detected as VPN detection. 

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 122984
 cosmetic: 76574
 scriptlet: 21288
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1642-0, 1h.25m
  https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt: 651-1, 1d.20h.19m
  IDN-0: 9680-3, 3d.4h.18m
  RUS-0: 39758-25, 1d.2h.54m
 default:
  user-filters: 0-0, never
  TUR-0: 13726-20, 1d.20h.19m
  easylist: 69553-101, 1d.18h.19m
  easyprivacy: 33325-399, 22h.33m
  plowe-0: 3726-1075, 5d.3h.53m
  ublock-badware: 7796-146, 1d.20h.19m
  ublock-filters: 34382-181, 1d.20h.19m
  ublock-privacy: 536-12, 1h.25m
  ublock-quick-fixes: 250-20, 1h.25m
  ublock-unbreak: 2116-35, 1d.20h.19m
  urlhaus-1: 5882-0, 1h.25m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 472 ms (selfie)
 maxAssetCacheWait: 277 ms
```
</details>

**Comment by arifyilmaz-hb** [comment]
Thanks for fixing the ad pop up part. Is there any chance that you can also remove the circle CAPTCHA part that appears in the opening of this video? @ghajini

**Comment by arifyilmaz-hb** [comment]
As it is now, a small pop-up window pops up again and the video is paused to show an ad. Any chance you can update the solution to the problem?

**Comment by arifyilmaz-hb** [comment]
After updating it gives detection error saying "Owner of this video doesnot allow AdBIock. To watch video disable AdBIock". Any chance to fix that?

**Comment by arifyilmaz-hb** [comment]
> As it is now, a small pop-up window pops up again and the video is paused to show an ad. Any chance you can update the solution to the problem?

Same ad pop-up problem occure `https://tabuporns.com/crystal-clark-helping-my-stepmom-with-her-skincare` any chance to fix that?

**Comment by arifyilmaz-hb** [comment]
A small pop-up window pops up again with netu tv player on vsex.in. Any chance to update?

**Comment by stephenhawk8054** [comment]
@arifyilmaz-hb Give the exact URL

**Comment by arifyilmaz-hb** [comment]
This time, another video player is experiencing pop-up issues. For example, with this link:
`https://vsex.in/87641-facefuck-friend-request.html`
