### ISSUE TITLE
gtxgamer.fr: ads

### ISSUE THREAD

**Issue by marechalsamuel** [uBlockOrigin/uAssets#19510]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gtxgamer.fr/ordinateurs-et-accessoires/nvidia-geforce-rtx-3060-ti/`

### Category

ads

### Description

Ad for AVG on the upper right side

### Other extensions used

- Dark Reader
- SponsorBlock
- VideoSpeedController

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/20586745/b7170388-34a5-44d9-be6b-db762ccb3cbd)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 116628
 cosmetic: 48403
 scriptlet: 18443
 html: 1027
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35312-174, now
  ublock-badware: 7803-0, now
  ublock-privacy: 567-0, now
  ublock-unbreak: 2164-1, now
  ublock-quick-fixes: 274-0, 22m
  easylist: 69467-731, now
  easyprivacy: 33340-715, now
  urlhaus-1: 5870-0, now
  plowe-0: 3724-2, now
  FRA-0: 28158-338, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1044 ms (selfie)
 maxAssetCacheWait: 120 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by Yuki2718** [comment]
Too few visitors by [AdGuard filter policy](https://adguard.com/kb/general/ad-filtering/filter-policy/): https://www.similarweb.com/website/gtxgamer.fr/
