### ISSUE TITLE
gutefrage.net: detection

### ISSUE THREAD

**Issue by MaierTV** [uBlockOrigin/uAssets#19511]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gutefrage.net/`

### Category

detection

### Description

the website recognizes ublock origin

### Other extensions used

privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 100474
 cosmetic: 44079
 scriptlet: 18378
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7065-0, 4m
  easylist: 69467-16, 4m
  easyprivacy: 33340-72, 4m
  plowe-0: 3724-1065, 4m
  ublock-badware: 7801-146, 4m
  ublock-filters: 34437-139, 4m
  ublock-privacy: 536-6, 4m
  ublock-quick-fixes: 267-60, 43m
  ublock-unbreak: 2116-35, 4m
  urlhaus-1: 5870-0, 4m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-extension-scheme
  edge-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 352 ms (selfie)
 maxAssetCacheWait: 69 ms
popupPanel:
 blocked: 10
 network:
  gutefrage.net: 8
  h5v.eu: 1
  wlt-jupiter.de: 1
 extended:
  ##.Ad
```
</details>

**Comment by MaierTV** [comment]
yes

**Comment by mapx-** [comment]
I get no detection even using an account.

Try disabling privacy badger and test again.
