### ISSUE TITLE
ozulscansen.com: ads

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#19518]
### Prerequisites

- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ozulscansen.com/comics/start-by-signing-in-and-obtaining-the-ancient-divine-body/`

### Category

ads leftovers

### Description

fix: ||3.bp.blogspot.com^$domain=ozulscansen.com 

### Other extensions used

Buster: Captcha Solver for Humans, Chromium Web Store, ClearURLs, Cookie AutoDelet, Dark Mode, DeArrow, FastForward, Font Fingerprint Defender, LocalCDN, Modern scrollbar, PocketTub, Return YouTube Dislike, Search by Image, SponsorBlock, SuperCopy, Tampermonkey, TTV LOL, Unpaywall, User-Agent Switcher, WebNowPlaying

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-08-29 205234](https://github.com/uBlockOrigin/uAssets/assets/100969549/346f1df5-fc09-4d36-ac69-f88d0d7f507c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 407313
 cosmetic: 261264
 scriptlet: 44836
 html: 0
listset (total-discarded, last-updated):
 added:
  https://pfblockerlists.smallbusinesstech.net/hackerlist.txt: 4286-4, now
  https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, now
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-0, now
  https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 5812-4, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 666-5, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 30-0, now
  https://raw.githubusercontent.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/master/ips.list: 1361-5, now
  https://raw.githubusercontent.com/nabble/semalt-blocker/master/domains/blocked: 2433-2, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93155-15903, now
  https://winhelp2002.mvps.org/hosts.txt: 8729-62, now
  CHN-0: 25950-138, now
  JPN-1: 13255-14, now
  [25 lists not shown]: [too many]
 default:
  user-filters: 38-0, never
  DEU-0: 7065-3, now
  easylist: 69504-1718, now
  easyprivacy: 33333-17084, now
  plowe-0: 3724-1736, now
  ublock-badware: 7864-403, now
  ublock-filters: 34450-4259, now
  ublock-privacy: 536-195, now
  ublock-quick-fixes: 256-53, now
  ublock-unbreak: 2116-154, now
  urlhaus-1: 5882-3, now
filterset (user): [array of 39 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
switchRuleset:
 added: [array of 59 redacted]
hostRuleset:
 added: [array of 94 redacted]
urlRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 896 ms (selfie)
 maxAssetCacheWait: 450 ms
popupPanel:
 blocked: 7
 network:
  ozulscansen.com: 1
  disqus.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  viglink.com: 2
 extended:
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="whatsapp://send"]
  ##a[href^="https://www.twitter.com/intent/tweet?"]
  ##a[href*="pinterest.com/pin/create/button"]
  ##.adsbygoogle
  ##ins.adsbygoogle
  ##.socialbutton
  ##.socialbutton:not(.dropdown-menu.pull-right)
  ##.scrollToTop
  ##.comment-policy-refresh
  ###email-signup
  ###placement-top
  ###thread-share-bar
  ##.reaction-items
  ##.nav-primary.nav
  ##.disqus-footer
  ##.postbox > div > div > div
  ##.compose-wrapper
  ##.publisher-anchor-color.comment-policy-refresh
  ###badges-message__container
  ##.thread-likes > div
  ##.spacing-bottom-small.align--center.align.text-bold
```
</details>

**Comment by okiehsch** [comment]
`ozulscansen.com###close-teaser`

**Comment by mapx-** [comment]
@big-cat-loaf report here: https://github.com/easylist/easylist/issues
