### ISSUE TITLE
[nsfw] businesssoftwarehere.com: detection

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#19515]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://businesssoftwarehere.com/integrated-software-solutions/`

### Category

detection

### Description

`​https://goo.st/FZIM` 
from this link it goes to  `https://businesssoftwarehere.com/integrated-software-solutions/ or https://softwaresolutionshere.com/business-software-solutions-2023/`  this link. 

The second link is fine. But on the site in the first link, when the counter reaches zero, it gives the warning "Please disable Adblock to proceed to the destination page." when you click.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 156505
 cosmetic: 178838
 scriptlet: 30745
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, now
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1642-0, now
  https://easylist.to/easylist/fanboy-annoyance.txt: 61174-113, now
  https://fanboy.co.nz/fanboy-turkish.txt: 725-0, now
  https://filters.adavoid.org/ultimate-privacy-filter.txt: 55629-469, now
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 71200-5405, now
  https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/Soft98/Soft98NoAds.txt: 18-0, now
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7256-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 181-0, now
  https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt: 412-8, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93155-77232, now
  fanboy-cookiemonster: 48328-48328, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 644-4, never
  TUR-0: 13729-107, now
  easylist: 69462-174, now
  easyprivacy: 33332-16792, now
  plowe-0: 3724-1159, now
  ublock-badware: 7843-150, now
  ublock-filters: 34444-565, now
  ublock-privacy: 536-65, now
  ublock-unbreak: 2116-80, now
  urlhaus-1: 5882-0, now
filterset (user): [array of 631 redacted]
trustedset:
 added: [array of 17 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 7 redacted]
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 373 ms (selfie)
 maxAssetCacheWait: 252 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##.share-post
  ##.share-text
  ##.social-linkedin
  ##.social-pinterest
  ###leaderboard.ad
  ###topcontrol
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
```
</details>

**Comment by punisher018** [comment]
website 1 : https://businesssoftwarehere.com/integrated-software-solutions/
website 2 : https://softwaresolutionshere.com/business-software-solutions-2023/

https://goo.st/FZIM/    from this website click "click here to continue"
One of them opens. Website 1 is causing trouble. Since it is an url shortener, it does not work when you try to open the site directly.

**Comment by okiehsch** [comment]
`businesssoftwarehere.com##+js(set, adblockstatus, false)`

**Comment by punisher018** [comment]
@okiehsch Thanks it's working.
