### ISSUE TITLE
mylearn.vmware.com: breakage

### ISSUE THREAD

**Issue by VMW-NickF** [uBlockOrigin/uAssets#19527]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mylearn.vmware.com/gw/mylearn/course/search`

### Category

breakage

### Description

Memory buffer overrun on firefox when searching for training sessions. Browser tab will go not responding and will continue to eat up ram. Disabling ublock origin is the only fix.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98116
 cosmetic: 39391
 scriptlet: 18313
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 14-2, never
  ublock-filters: 35302-94, now
  ublock-badware: 7866-0, 54m
  ublock-privacy: 567-0, 54m
  ublock-unbreak: 2164-0, 54m
  easylist: 69467-693, 54m
  easyprivacy: 33333-715, 54m
  urlhaus-1: 5793-0, 54m
  plowe-0: 3724-2, now
  ublock-quick-fixes: 277-1, 54m
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 101 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 187 ms (selfie)
 maxAssetCacheWait: 81 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
provide more details on how to reproduce the issue, how many searches, how long do you have to wait for the issue etc

**Comment by VMW-NickF** [comment]
Issues happens when you disable ublock for the website (click the ublock button to disable it for the site, not disabling it for firefox) then try searching any thing or hitting back/refresh.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
