### ISSUE TITLE
podtail.com, onlineradiobox.com: ads

### ISSUE THREAD

**Issue by Hebrew-uBO-User** [uBlockOrigin/uAssets#19521]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`podtail.com##li.advert`
(episode lists)

`onlineradiobox.com##.banner--vertical`
`onlineradiobox.com##.banner--header`

### URL(s) where the issue occurs.

see description

### uBO version

latest stable (1.51.0)

### Browser name and version

lastest Firefox / Chromium

### Settings

default settings

**Comment by stephenhawk8054** [comment]
Please give exact URLs next time to not waste everyone's time:

```
https://podtail.com/podcast/over-my-dead-body/
```

I don't know which URL you are implying to by

```
onlineradiobox.com##.banner--vertical
onlineradiobox.com##.banner--header
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by Hebrew-uBO-User** [comment]
@Yuki2718 
@ryanbr

**Comment by Hebrew-uBO-User** [comment]
@ryanbr 
what about
`podtail.com##li.advert`
?
