### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by MA62CNB** [uBlockOrigin/uAssets#19524]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=rS_t2Qgmii4`

### Category

ads

### Description

The website displays a timed ads (2) before the start of the actual video.

### Other extensions used

Simple translate, web eid, fireshot.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 99914
 cosmetic: 49833
 scriptlet: 19777
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 4-2, never
  ublock-filters: 35294-101, now
  ublock-badware: 7866-1, now
  ublock-privacy: 567-0, now
  ublock-unbreak: 2165-1, now
  ublock-quick-fixes: 283-0, 7m
  easylist: 69511-713, now
  easyprivacy: 33319-720, now
  urlhaus-1: 5793-0, now
  plowe-0: 3724-1, now
  TUR-0: 13729-13, now
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 454 ms (selfie)
 maxAssetCacheWait: 220 ms
popupPanel:
 blocked: 44
 network:
  youtube.com: 34
  doubleclick.net: 6
  google.com: 2
  google.com.tr: 1
  googlesyndication.com: 1
 extended:
  ###merch-shelf
  ###player-ads
  ##.ad-showing > .html5-video-container
  ##.ytd-action-companion-ad-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-button
  ##.ytp-ad-player-overlay-flyout-cta
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  #@#.video-ads
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(json-prune, playerResponse.adPlacements playerResponse.pl…
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
default:
  user-filters: 4-2, never
```

Can you remove all your current custom filters, force update all your filter lists and test again?

Then please continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

Don't open duplicated issue

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
> 
> - [X] I did not answer truthfully to **ALL** the above checkpoints.
