### ISSUE TITLE
yhteishyva.fi: ads

### ISSUE THREAD

**Issue by Amiolia** [uBlockOrigin/uAssets#19526]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://yhteishyva.fi/listaus/reseptit?page=1`

### Category

ads

### Description

A pop up with no ad but a simple close button appears everytime the page or other pages on the site are loaded. On other pages there is also a wide space that says mainos (ad) but there is no actual ad in the space.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230830_151242_Firefox](https://github.com/uBlockOrigin/uAssets/assets/129485365/98e53e03-05ec-44d2-a936-dc1420fff1d1)
![Screenshot_20230830_151242_Firefox](https://github.com/uBlockOrigin/uAssets/assets/129485365/354ec8a7-d3e8-4f05-819d-6f1f6c6a434e)

</details>
/

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 117
filterset (summary):
 network: 99693
 cosmetic: 32451
 scriptlet: 18368
 html: 1032
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35612-477, now
  ublock-badware: 7865-1, now
  ublock-privacy: 569-1, now
  ublock-unbreak: 2173-2, now
  ublock-quick-fixes: 288-0, 1h.32m
  adguard-mobile: 8600-121, now
  easylist: 69527-16522, now
  easyprivacy: 33299-765, now
  urlhaus-1: 5793-0, now
  plowe-0: 3724-1, now
  FIN-0: 2206-68, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2439 ms (selfie)
 maxAssetCacheWait: 284 ms
popupPanel:
 blocked: 4
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
  usercentrics.eu: 1
  visualwebsiteoptimizer.com: 1
 extended:
  ##.ad-wrapper
```
</details>

**Comment by Amiolia** [comment]
Screenshot of the other type of ad remnant
![Screenshot_20230830_151258_Firefox](https://github.com/uBlockOrigin/uAssets/assets/129485365/4aee8cea-7ea6-4e12-ba5c-aa89d3624f82)

**Comment by peace2000** [comment]
added https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/5badf5a9b09edc6d5fd57d66408113c8c3e892a7
