### ISSUE TITLE
appnee.com: nuisance

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#19534]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://appnee.com/?s=cisco+packet+tracer`

### Category

nuisance

### Description

It always gives throws this notification

![image](https://github.com/uBlockOrigin/uAssets/assets/32187927/61040750-4f50-421d-bed9-26f6761b4071)

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98136
 cosmetic: 39417
 scriptlet: 18355
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69561-10, now
  easyprivacy: 33283-63, now
  plowe-0: 3724-1065, now
  ublock-badware: 7870-146, now
  ublock-filters: 34456-125, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 198-35, 10m
  ublock-unbreak: 2120-33, now
  urlhaus-1: 5793-0, 11m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 307 ms (selfie)
 maxAssetCacheWait: 87 ms
popupPanel:
 blocked: 12
 network:
  appnee.com: 1
  rambleconcernedscar.com: 11
 extended:
  ###babasbmsgx
```
</details>

**Comment by BlazeFTL** [comment]
`@@||appnee.com/clever_ads.js$script,1p`
