### ISSUE TITLE
apkmirror.com: detection

### ISSUE THREAD

**Issue by privacyonly** [uBlockOrigin/uAssets#19531]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

apkmirror.com##[id^="adtester-container"]:style(position: absolute !important;)
edit1: now that I think again it is the one below creating all the detections.

apkmirror.com##.ains

as its name says it is an ad tester
disabling this line avoid the 15 seconds detection, actually the script does not scan for adtester but .ains

### URL(s) where the issue occurs.

apkmirror.com 

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/issues/18666
https://github.com/uBlockOrigin/uAssets/issues/18517
https://github.com/uBlockOrigin/uAssets/issues/16648

### uBO version

latest

### Browser name and version

fennec fdroid, kiwi browser

### Settings

default

**Comment by privacyonly** [comment]
here is the script, the fyM, Yaf, gZu, nLB, YYi are all random.

function xla() {
    APKM.qs('style:last-of-type').appendChild(document.createTextNode(' .aWR:empty {display: none !important;}'));
    if ( APKM.vE('.ains', 21) < 2) {
        !function(){let s=APKM.qs(".gZu"),e=APKM.qs(".nLB"),n=APKM.qs(".YYi");APKM.rT(function(d){0==d?(s.classList.remove("fyM"),e.classList.add("hidden")):n.innerHTML=d+" more sec"},15),APKM.qa(".Yaf").forEach(d=>{d.classList.remove("hidden")}),s.classList.add("fyM")}();;
    }
}

**Comment by privacyonly** [comment]
@ghajini do you use android, fennec fdroid with ublock origin?

**Comment by stephenhawk8054** [comment]
I can't see the anti-adblock on Firefox mobile either.
