### ISSUE TITLE
mundowebtoon.com: nuisance

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#19539]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mundowebtoon.com/mangabr/sword-fanatic-wanders-through-the-night-br-gm`

### Category

nuisance

### Description

has popups annoying as hell, this domain have the sames: `goldenmanga.top`

blocking these 2 sites worked well for me with no apparently problems.

`||www.mapbovdpdy.com^`
`||www.voxmrcdgzuwb.com^`

note: earlier the domains were different, strange.

`||www.xswhbitplhase.com^`
`||avwwphtnquacgd.com^`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 167911
 cosmetic: 225664
 scriptlet: 44680
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 972-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2256-0, now
  adguard-cookies: 27414-29, now
  adguard-generic: 73400-467, now
  adguard-mobile-app-banners: 4583-9, now
  adguard-other-annoyances: 13346-7, now
  adguard-popup-overlays: 23752-71, now
  adguard-social: 21297-909, now
  adguard-spyware: 55767-1328, now
  adguard-spyware-url: 1192-145, now
  adguard-widgets: 2294-6, now
  easylist-annoyances: 3934-232, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 110-0, never
  easylist: 69475-1111, now
  easyprivacy: 33289-16725, now
  plowe-0: 3726-1159, now
  spa-1: 5514-78, now
  ublock-badware: 7870-363, now
  ublock-filters: 34461-4239, now
  ublock-privacy: 538-137, now
  ublock-quick-fixes: 215-52, now
  ublock-unbreak: 2120-150, now
  urlhaus-1: 5797-0, now
filterset (user): [array of 65 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 4883 ms (selfie)
 maxAssetCacheWait: 395 ms
popupPanel:
 blocked: 6
 network:
  adsco.re: 1
  cloudflare.com: 1
  d2j042cj1421wi.cloudfront.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  premiumvertising.com: 1
 extended:
  ##a[href*="//www.facebook.com/share.php"]
  ##a[href^="https://api.whatsapp.com/send?text="]
  ##a[href^="https://twitter.com/home?"]
  ##a[href^="https://www.facebook.com/share.php?"]
  ##ins.adsbygoogle
```
</details>

**Comment by D4niloMR** [comment]
i'm not sure if this is a good filter but it works:

`/rrssb.min.js$script,domain=mundowebtoon.com|goldenmanga.top`
`/jquery.mapael.min.js$script,domain=mundowebtoon.com|goldenmanga.top`

**Comment by ghajini** [comment]
test
`mundowebtoon.com##+js(aost, atob, )`

**Comment by D4niloMR** [comment]
Worked

**Comment by D4niloMR** [comment]
@ghajini sorry but, can you add `goldenmanga.top` too?

**Comment by D4niloMR** [comment]
@ghajini 

`mundowebtoon.com##+js(aost, atob)` is breaking cloudfare, i'm stuck in the cloudfare page
<details>
<summary>Screenshot</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/17b8f4c0-56fd-4da2-98f0-78c7bbc070ff)

</details>

**Comment by D4niloMR** [comment]
dead sites
