### ISSUE TITLE
pressdemocrat.com: breakage

### ISSUE THREAD

**Issue by sergneri** [uBlockOrigin/uAssets#19533]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pressdemocrat.com/`

### Category

detection

### Description

We are not "logged in" at this site if origin is on. If it is off, we can log in and suffer the ads. Turn origin back on and we are no longer logged in.

### Other extensions used

https everywhere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98250
 cosmetic: 23280
 scriptlet: 18291
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35313-277, 10m
  ublock-badware: 7871-0, 10m
  ublock-privacy: 569-1, 10m
  ublock-unbreak: 2168-2, 10m
  ublock-quick-fixes: 216-0, 10m
  easylist: 69549-16611, 10m
  easyprivacy: 33282-717, 10m
  urlhaus-1: 5919-0, 10m
  plowe-0: 3724-2, 10m
filterset (user): [empty]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1491 ms
 maxAssetCacheWait: 7 ms
popupPanel:
 blocked: 11
 network:
  amazon-adsystem.com: 1
  azureedge.net: 1
  chartbeat.com: 1
  doubleclick.net: 1
  googletagmanager.com: 2
  matheranalytics.com: 1
  ntv.io: 1
  onesignal.com: 1
  tru.am: 1
  viafoura.co: 1
```
</details>

**Comment by ghajini** [comment]
@ryanbr 

```
@@||loader-cdn.azureedge.net/prod/smi/loader.min.js$script,domain=pressdemocrat.com
/smi/fp.min.js^$3p
||cdn.pranmcpkx.com^
```

**Comment by sergneri** [comment]
Thank you, this appears to have fixed our problem with this site. We
added the script on two Windows 11 PCs with 115.02 Firefox and 1.5.1.0
UBLOCK and it appears to have fixed the detection problem, we can log
in, post/read comments and don't get logged out while UBLOCK runs. 

!!

On 2023-08-30 11:29, ghajini wrote:

> @ryanbr [1]
> 
> @@||loader-cdn.azureedge.net/prod/smi/loader.min.js$script,domain=pressdemocrat.com
> /smi/fp.min.js^$3p
> ||cdn.pranmcpkx.com^
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/ryanbr
[2]
https://github.com/uBlockOrigin/uAssets/issues/19533#issuecomment-1699650722
[3]
