### ISSUE TITLE
pinsystem.co.uk: detection

### ISSUE THREAD

**Issue by AimTo** [uBlockOrigin/uAssets#19536]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pinsystem.co.uk/`

### Category

detection

### Description

Ad blockers detected since today. Turning them off doesn't make the site work 

### Other extensions used

Privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 116
filterset (summary):
 network: 118123
 cosmetic: 36636
 scriptlet: 18476
 html: 1027
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35645-489, now
  ublock-badware: 7866-1, now
  ublock-privacy: 569-1, now
  ublock-unbreak: 2173-2, now
  ublock-quick-fixes: 214-0, now
  adguard-mobile: 8602-121, now
  easylist: 69561-16615, now
  easyprivacy: 33283-723, now
  urlhaus-1: 5919-0, now
  plowe-0: 3724-1, now
  FRA-0: 28158-3281, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3436 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel:
 blocked: 9
 network:
  doubleclick.net: 1
  googlesyndication.com: 7
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##+js(addEventListener-defuser, /^(?:click|mousedown)$/, _0x)
  ##+js(no-xhr-if, adsbygoogle)
  ##+js(abort-current-script, eval, replace)
```
</details>

**Comment by huyszn** [comment]
The site detects uBO again (https://github.com/uBlockOrigin/uAssets/assets/46979193/4fe86b13-727f-4d15-892a-9943eb33383a)

This filter seems to work to remove the detection:
```
!#if cap_html_filtering
pinsystem.co.uk##^script:has-text(AdBlocker)
!#else
pinsystem.co.uk##+js(rmnt, script, AdBlocker)
!#endif
```
