### ISSUE TITLE
citethisforme.com: ads

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#19530]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.citethisforme.com/`

### Category

ads

### Description

There are several big ad leftovers on the page. This issue is first reported in https://github.com/easylist/easylist/issues/15949.

Either 
`citethisforme.com##.fhlzSd:remove-class(fhlzSd)` 
or 
`citethisforme.com##[class^="styled__AdMarginWrapper"]:style(margin-right: auto !important;)` 
works on my end.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1rc2
Firefox: 116
filterset (summary):
 network: 98251
 cosmetic: 39415
 scriptlet: 18354
 html: 1026
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35314-42, 12m
  ublock-badware: 7871-0, 12m
  ublock-privacy: 569-0, 12m
  ublock-unbreak: 2168-1, 12m
  ublock-quick-fixes: 288-32, 12m
  easylist: 69549-258, 12m
  easyprivacy: 33282-84, 12m
  urlhaus-1: 5919-0, 12m
  plowe-0: 3724-1067, 11m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 306 ms (selfie)
 maxAssetCacheWait: 194 ms
popupPanel:
 blocked: 64
 network:
  3lift.com: 2
  adnxs.com: 2
  adsrvr.org: 1
  bidswitch.net: 2
  casalemedia.com: 1
  chegg.com: 32
  confiant-integrations.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  gumgum.com: 1
  id5-sync.com: 1
  indexww.com: 1
  newrelic.com: 2
  openx.net: 2
  pubmatic.com: 2
  rightfulfall.com: 2
  rubiconproject.com: 5
  sonobi.com: 1
  yahoo.com: 4
 extended:
  ##+js(abort-on-property-read, SBMGlobal.run.gramCallback)
```
</details>

**Comment by mapx-** [comment]
`citethisforme.com##.adds-wrapper`

@ryanbr

**Comment by partingscientist** [comment]
Would uAssets fix the right-hand side placeholders?
