### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by KonaloboStudio** [uBlockOrigin/uAssets#19537]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Description

Perhaps the problem is with some recent update. The site does not load with the ublock enabled

### Other extensions used

I checked that Violentmonkey, Stylus and their scripts are not related to the ublock error

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![chrome_x7UfIixkAQ](https://github.com/uBlockOrigin/uAssets/assets/71982930/5c6d0a80-4368-4b1c-886e-bda495c15864)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 61d.4h.46m
Chromium: 114
filterset (summary):
 network: 115480
 cosmetic: 60441
 scriptlet: 19694
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  RUS-0: 39757-9, 2d.37m
  easylist: 69521-33, 1d.1h.52m
  easyprivacy: 33310-154, 5d.32m
  plowe-0: 3723-1068, 8d.7h.42m
  ublock-badware: 7864-146, 2h.37m
  ublock-filters: 34457-156, 2h.36m
  ublock-privacy: 531-7, 4d.7h.10m
  ublock-quick-fixes: 247-67, 12h.39m
  ublock-unbreak: 2118-32, 2h.35m
  urlhaus-1: 5919-0, 8h.38m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 945 ms (selfie)
 maxAssetCacheWait: 431 ms
popupPanel:
 blocked: 9
 network:
  youtube.com: 6
  doubleclick.net: 3
 extended:
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(replace-node-text, script, (function serverContract(), 'co…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you update to latest version (1.51.0), force update all your filter lists and test again?

And please, continue here: https://github.com/uBlockOrigin/uAssets/issues/7636

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
