### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by TheWoodsy** [uBlockOrigin/uAssets#19548]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection

### Description

If either "uBlock filters – Ads" or "uBlock filters – Quick fixes" filters are enabled, youtube is entirely broken.

Pages only display outlines. Images and videos are blank frames.

See https://i.imgur.com/gzPx8Sm.png

### Other extensions used

https://i.imgur.com/NXw0Nfg.png

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![YoloMouse_YIGwjxhigC](https://github.com/uBlockOrigin/uAssets/assets/390113/2b185981-4744-42d3-a4e9-16d85317f649)

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 77d.16h.41m
Firefox: 117
filterset (summary):
 network: 324183
 cosmetic: 220717
 scriptlet: 27538
 html: 276
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
  ublock-quick-fixes: null
 added:
  adguard-generic: 73487-2979, 4m
  adguard-mobile: 8606-12, 4m
  adguard-social: 21302-842, 3m
  fanboy-cookiemonster: 48354-3949, 2m
  fanboy-social: 16226-8, 2m
  ublock-annoyances: 5400-288, 2m
  adguard-spyware-url: 1197-68, 4m
  block-lan: 48-0, 4m
  curben-phishing: 164634-76, 3m
  curben-pup: 189-0, 3m
  adguard-spyware: 55765-17046, 4m
  adguard-cookies: 27430-60, 3m
  [10 lists not shown]: [too many]
 default:
  user-filters: 106-52, never
  ublock-badware: 7872-0, 6m
  ublock-privacy: 569-0, 6m
  ublock-unbreak: 2166-0, 6m
  easylist: 69478-735, 6m
  easyprivacy: 33277-819, 6m
  urlhaus-1: 5874-0, 3m
  plowe-0: 3726-86, 6m
filterset (user): [array of 106 redacted]
trustedset:
 added: [array of 25 redacted]
 removed:
  about-scheme
hostRuleset:
 added: [array of 5 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5174 ms (selfie)
 maxAssetCacheWait: 620 ms
popupPanel:
 blocked: 8
 network:
  youtube.com: 4
  doubleclick.net: 1
  google.com: 1
  google.com.au: 1
  sentry.io: 1
 extended:
  ###player-ads
  ##.ytp-share-button
  ###ticker.ytd-masthead
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ###offer-module
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ###contents > ytd-rich-item-renderer:has(> #content > ytd-ad-slo…
  ##ytd-rich-grid-renderer ytd-rich-item-renderer div > ytd-displa…
  ##ytd-thumbnail.ytd-rich-grid-media.style-scope > .ytd-thumbnail…
  ##.yt-spec-button-shape-next--size-m:style(border-radius: 3px !i…
  ##ytd-thumbnail[size="large"] a.ytd-thumbnail, ytd-thumbnail[siz…
  ##*:not(.ytp-scrubber-button):style(border-radius: 3px !importan…
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19537#issuecomment-1700013544

**Comment by TheWoodsy** [comment]
No updates found. Firefox dev edition 117.0b9 (64-bit)

**Comment by stephenhawk8054** [comment]
Can you uninstall and re-install uBO from Firefox add-on store, then force update all the filter lists again?

**Comment by TheWoodsy** [comment]
Updated FF to 118.0b2 (64-bit) still No updates found for extension.
Saved settings to file > removed ublock > re-added via ff store > running 1.51
Will test youtube and report back.

Kinda concerned why it would not auto-update. Have another PC that is also stuck on 1.50.

**Comment by stephenhawk8054** [comment]
Where did you check the update?

**Comment by TheWoodsy** [comment]
The option at top right of screenshot.
https://i.imgur.com/qgdYoKU.png
Always says 'No updates available'.

**Comment by TheWoodsy** [comment]
Running 1.51 > Re-enabled suspect filters "uBlock filters – Ads" or "uBlock filters – Quick fixes".

Youtube works fine now.

**Comment by TheWoodsy** [comment]
Still have another PC with ff dev edition that is stuck at 1.50. It's youtube page is broken still. Let me know if you'd like me to test anything further. If not ill update that PC to 1.51 and fade into obscurity. ;]

**Comment by stephenhawk8054** [comment]
Yes, please update uBO to latest version (1.51.0)

**Comment by TheWoodsy** [comment]
Roger. Cheers for the assistance. ♥
