### ISSUE TITLE
[nsfw] czechvideo.co: detection

### ISSUE THREAD

**Issue by JohnnyReds** [uBlockOrigin/uAssets#19540]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://czechvideo.co/8091-0770-czech-streets-61.html`

### Category

detection

### Description

Whenever you try to play a video it states "Owner of this video doesnot allow AdBlock. To watch video disable AdBlock and refresh page. Error: init." and stops the video from even starting. 

### Other extensions used

Google translate, bitWarden, 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://czechvideo.co/8091-0770-czech-streets-61.html

![chrome_VahMYCZHbd](https://github.com/uBlockOrigin/uAssets/assets/70429817/288b1279-c99a-472e-bd34-5d9645519dd2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 98061
 cosmetic: 39419
 scriptlet: 18359
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69475-10, 1m
  easyprivacy: 33289-63, 1m
  plowe-0: 3726-1065, 1m
  ublock-badware: 7870-146, 1m
  ublock-filters: 34461-125, 1m
  ublock-privacy: 538-6, 1m
  ublock-quick-fixes: 215-52, 1m
  ublock-unbreak: 2120-33, 1m
  urlhaus-1: 5797-0, 1m
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 923 ms (selfie)
 maxAssetCacheWait: 124 ms
popupPanel:
 blocked: 13
 network:
  alleviatepracticableaddicted.com: 1
  chaturbate.com: 1
  czxxx.org: 2
  googletagmanager.com: 1
  marazma.com: 1
  sadjklq.com: 1
  slipheirphysician.com: 3
  xlirdr.com: 2
  yadro.ru: 1
 extended:
  ##.block-ads1
  ##.block-ads2
  ##+js(abort-on-property-read, adBlockDetected)
  ##+js(no-window-open-if)
```
</details>

**Comment by BlazeFTL** [comment]
```
czxxx.org##+js(set, adblockcheck, false)
czxxx.org##+js(nosiif, funcpeer)
