### ISSUE TITLE
work.ink: detection

### ISSUE THREAD

**Issue by smiRaphi** [uBlockOrigin/uAssets#19545]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://work.ink/3S5/WiiBackupManager_Build78`

### Category

detection

### Description

it get's detected

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://github.com/uBlockOrigin/uAssets/assets/87574679/a666a379-90e0-4da6-b421-34aed6af746e)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 114
filterset (summary):
 network: 356253
 cosmetic: 155426
 scriptlet: 38816
 html: 0
listset (total-discarded, last-updated):
 added:
  JPN-1: 13279-4, 5m
  RUS-0: 39869-10, 5m
  adguard-generic: 73433-652, 5m
  adguard-mobile: 8602-98, 5m
  adguard-social: 21297-63, 5m
  adguard-spyware: 55768-1333, 5m
  adguard-spyware-url: 1192-3, 5m
  block-lan: 48-0, 5m
  curben-phishing: 166457-47, 5m
  curben-pup: 189-0, 5m
  dpollock-0: 11550-249, 5m
  fanboy-social: 16223-681, 5m
  [2 lists not shown]: [too many]
 default:
  user-filters: 396-4, never
  DEU-0: 7065-0, 5m
  easylist: 69475-1371, 5m
  easyprivacy: 33276-16753, 5m
  plowe-0: 3726-1573, 5m
  ublock-badware: 7870-401, 5m
  ublock-filters: 34462-3892, 5m
  ublock-privacy: 538-128, 5m
  ublock-quick-fixes: 223-53, 5m
  ublock-unbreak: 2120-151, 5m
  urlhaus-1: 5797-3, 5m
filterset (user): [array of 396 redacted]
trustedset:
 added: [array of 30 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 15170 ms (selfie)
 maxAssetCacheWait: 1645 ms
popupPanel:
 blocked: 6
 network:
  work.ink: 1
  googletagmanager.com: 2
  ohbayersbur.pro: 1
  outbrain.com: 1
  quantcast.com: 1
 extended:
  ##+js(no-fetch-if, doubleverify.com)
  ##+js(remove-attr, href, [href*="jump"], stay)
  ##+js(no-setInterval-if, a0b)
  ##+js(no-fetch-if, /outbrain|criteo|thisiswaldo|media\.net/)
```
</details>

**Comment by huyszn** [comment]
`https://work.ink/3S5/WiiBackupManager_Build78`

"Adblocker Was Detected" message after waiting on page for a few seconds.
