### ISSUE TITLE
howtogeek.com: detection

### ISSUE THREAD

**Issue by glitsj16** [uBlockOrigin/uAssets#19543]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Articles are blocked from view:

```
Something went wrong. Please disable your blocker on How-To Geek
```

### URL(s) where the issue occurs.

`https://www.howtogeek.com`

### uBO version

uBlock Origin 1.51.1rc2

### Browser name and version

Firefox 117.0

### Settings

- disabled tooltips

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by dportvine** [comment]
Can this be fixed?

`https://www.howtogeek.com/android-browsers-that-support-extensions/#firefox`

<details>
<summary>Screenshot(s)</summary>

![2023-10-05_125928](https://github.com/uBlockOrigin/uAssets/assets/111344219/ae1eedd3-b2b0-407d-bf08-ae6b551d6026)
![2023-10-05_125944](https://github.com/uBlockOrigin/uAssets/assets/111344219/743e9da2-5bf6-43ee-9ae0-2eff066d360a)
</details>

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 123656
 cosmetic: 106250
 scriptlet: 26465
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 48478-229, now
  ublock-annoyances: 5507-59, now
  ublock-cookies-easylist: 319-319, now
 default:
  user-filters: 1-0, never
  RUS-0: 39958-9, now
  easylist: 71545-40, now
  easyprivacy: 33209-154, now
  plowe-0: 3720-1067, now
  ublock-badware: 7138-133, now
  ublock-filters: 34935-185, now
  ublock-privacy: 557-7, now
  ublock-quick-fixes: 156-20, now
  ublock-unbreak: 2133-35, now
  urlhaus-1: 11125-0, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 894 ms (selfie)
 maxAssetCacheWait: 521 ms
popupPanel:
 blocked: 16
 network:
  howtogeek.com: 2
  ad.gt: 1
  adlightning.com: 1
  adsninja.ca: 2
  amazon-adsystem.com: 1
  google-analytics.com: 1
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 1
  privacymanager.io: 2
  unpkg.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adsninja-ad-zone
  ##.ad-current
  ##.ad-zone-container
  ##.ad-zone:not(.textads)
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.ad-zone
  ##+js(remove-node-text, script, /typeof [a-z]\.cmd\.unshift/, co…
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by rd1** [comment]
same problem, i can't read the entire article, only a few lines then the rest is inaccessible. Screenshot:

![htg](https://github.com/uBlockOrigin/uAssets/assets/1567489/6e287b99-6a52-42df-adb6-cfc5855d7ebc)

**Comment by mapx-** [comment]
example link ?

Are you using uBO default lists + uBlock filters – Annoyances ?

**Comment by rd1** [comment]
yes defaults.

When you get tothe site, a nag screen blocks the whole page to force you to login.
worst is there's no closing it.


https://www.howtogeek.com/why-do-laptops-still-have-usb-2-ports/?utm_campaign=HTG-202310081200&utm_source=HTG-NL-DN&utm_medium=newsletter

And they wonder why ad revenue is down. jerks!

**Comment by mapx-** [comment]
I cannot reproduce any issue, no force login, no overlay

Desktop or android ?

Force update all your lists

**Comment by rd1** [comment]
firefox 118 on win10 x64

**Comment by mapx-** [comment]
still ok on my end, disable all other addons in firefox and test again

**Comment by rd1** [comment]
dang , it must be something else.

I checked with FF, Chrome & Edge; logged out of every profiles, cleared all cookies histories, settings and other tidbits. 

no extensions just ubo freshly reinstalled from each of the stores.

and I'm confused and confounded why it was wonky before.

Having only instapaper & lastpass extensions, I'll have to do some testing.

Anyhoo looks like ubo is ok, 

Thank you for taking the time to check this out.
