### ISSUE TITLE
ncjrs.gov

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1954]
### URL(s) where the issue occurs

`https://www.ncjrs.gov/App/Publications/abstract.aspx?ID=82679`

### Describe the issue

Clicking `FIND IN A LIBRARY` button doesn't work

### Notes

`@@fsrscripts` fixes it.

**Comment by zaphodbeebblebrox** [comment]
`@@||ncjrs.gov/fsrscripts/$first-party`.  Its just jquerry+plugins and css.
