### ISSUE TITLE
ondemandkorea.com: detection

### ISSUE THREAD

**Issue by mayakgyeran** [uBlockOrigin/uAssets#19551]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ondemandkorea.com/player/vod/tunnel-movie?contentId=367290`

### Category

detection

### Description

Adblock is detected by the website. Unable to stream content without disabling adblock. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 104724
 cosmetic: 104012
 scriptlet: 22415
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 71417-102, 7m
  KOR-1: 4509-12, 4m
 default:
  user-filters: 4-1, never
  easylist: 69530-108, 7m
  easyprivacy: 33281-138, 7m
  plowe-0: 3726-1081, 7m
  ublock-badware: 7870-146, 7m
  ublock-filters: 34467-500, 7m
  ublock-privacy: 538-8, 7m
  ublock-quick-fixes: 223-53, 7m
  ublock-unbreak: 2120-35, 7m
  urlhaus-1: 5802-0, 7m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 59 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1818 ms
 maxAssetCacheWait: 1010 ms
popupPanel:
 blocked: 6
 network:
  ondemandkorea.com: 1
  adrecover.com: 1
  amazon-adsystem.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  pubmatic.com: 1
 extended:
  ##[href="/membership"]
  ##+js(abort-on-property-read, pbjs.libLoaded)
```
</details>

**Comment by liamengland1** [comment]
probably a better solution but this works

`@@||ads.pubmatic.com/AdServer/*/pwt.js$script,domain=www.ondemandkorea.com`
