### ISSUE TITLE
rus.delfi.lv breakage

### ISSUE THREAD

**Issue by wadx** [uBlockOrigin/uAssets#19553]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Empty pages, probably detection

### URL(s) where the issue occurs.

```
https://rus.delfi.lv/
https://rus.delfi.lv/57860/latvia/55901872/rinkevich-obyasnil-pochemu-ne-daet-intervyu-po-russki
```

### Configuration

uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98097
 cosmetic: 39393
 scriptlet: 18365
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 69527-10, 8h
  easyprivacy: 33332-63, 3d.22h.44m
  plowe-0: 3726-1065, 7d.15h.1m
  ublock-badware: 7786-146, 4d.22h.59m
  ublock-filters: 34447-125, 2d.17h.18m
  ublock-privacy: 538-6, 15h.57m
  ublock-quick-fixes: 198-16, 10h.16m
  ublock-unbreak: 2116-33, 3d.12h.26m
  urlhaus-1: 5797-0, 18h.6m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 685 ms
 maxAssetCacheWait: 206 ms

**Comment by mapx-** [comment]
fixed 2 days ago, update all your filter lists
