### ISSUE TITLE
grabify.link: detection

### ISSUE THREAD

**Issue by RozvM** [uBlockOrigin/uAssets#19557]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://grabify.link/`

### Category

detection

### Description

Shows the mentioned pop-up in screenshots, also hides some of the details of grabbed IPs (like country and provider) when uBlock is enabled.

### Other extensions used

- Dark Reader
- SponsorBlock
- Enhancer for YouTube
- Return YouTube Dislike
- Bypass Paywalls
- DeArrow

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBlock enabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/74600479/6429add2-cd48-4f6e-80bc-31956a5284fe)
![image](https://github.com/uBlockOrigin/uAssets/assets/74600479/674b22a1-9cc5-4741-979d-068603fb609d)

uBlock disabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/74600479/6093d2a1-35d9-4a65-ad37-c3866a14a018)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 100344
 cosmetic: 55371
 scriptlet: 18293
 html: 1019
listset (total-discarded, last-updated):
 added:
  HUN-0: 2070-14, now
  JPN-1: 13287-70, now
  KOR-1: 4508-80, now
 default:
  user-filters: 0-0, never
  ublock-filters: 34783-77, now
  ublock-badware: 7562-1, now
  ublock-privacy: 468-0, now
  ublock-unbreak: 2134-0, now
  easylist: 68211-335, now
  easyprivacy: 33352-86, now
  urlhaus-1: 6413-0, now
  plowe-0: 3723-1071, now
  ublock-quick-fixes: 403-2, now
filterset (user): [empty]
trustedset:
 added: [array of 1122 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 cloudStorageEnabled: true
 colorBlindFriendly: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 182 ms (selfie)
 maxAssetCacheWait: 96 ms
popupPanel:
 blocked: 9
 network:
  cloudflareinsights.com: 2
  fuseplatform.net: 2
  glookup.info: 3
  googletagmanager.com: 1
  tawk.to: 1
 extended:
  ##.ad_container
  ##.myTestAd
```
</details>

**Comment by JobcenterTycoon** [comment]
The anti adblock is already fixed in the `uBlock filters – Annoyances` filterlist. You can enable the filterlist in the filterlist panel.

**Comment by JobcenterTycoon** [comment]
`@@||glookup.info^$xhr,domain=grabify.link` will fix the breakage.

**Comment by RozvM** [comment]
> The anti adblock is already fixed in the `uBlock filters – Annoyances` filterlist. You can enable the filterlist in the filterlist panel.

The pop-up is fixed with it but the other mentioned issues (some of the details of grabbed IPs, like country and provider/ISP) are still not appearing.

**Comment by JobcenterTycoon** [comment]
Works fine for me. @mapx- can you reproduce?

**Comment by RozvM** [comment]
Ok, the problem is in my computer. Fired up Chrome and it's displaying correctly, haven't even forced a filter update or anything else.

Comparing the 2 browsers, the "-" isn't a good sign next to glookup.info, isn't it?
![image](https://github.com/uBlockOrigin/uAssets/assets/74600479/52193dfb-5666-4305-9ced-2e30bd9f511f)
(Chrome on the left, Firefox on the right.)

**Comment by RozvM** [comment]
Ok, so it was the `EasyPrivacy` list.

For some reason it is always loading in a 13th July dated version in Firefox, despite disabling and enabling or purging the cache:
![image](https://github.com/uBlockOrigin/uAssets/assets/74600479/de1b6046-0725-4364-a2f4-bc40d814e82f)

Do you guys have any tickets about a phenomenon like this?

**Comment by JobcenterTycoon** [comment]
Does a reinstall help?

**Comment by RozvM** [comment]
A PC restart worked. Many thanks for spending time on me because of this issue! 😄

**Comment by Malostoq** [comment]
Again adblock detected. @JobcenterTycoon

**Comment by JobcenterTycoon** [comment]
Works fine for me.
