### ISSUE TITLE
discogs.com: ads

### ISSUE THREAD

**Issue by Pookeyblow** [uBlockOrigin/uAssets#19550]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.discogs.com/release/2083801-Mary-J-Blige-Love-Is-All-We-Need`

### Category

ads

### Description

The URL is just an example. Seems like it's happening on all embedded YouTube videos on Discogs.

I never had this issue before, but recently ads on embedded YouTube videos on Discogs.com are playing and they are also blank (black color). 

It doesn't happen on other sites with embedded YouTube videos. I use the Arc browser.

### Other extensions used

I turned off all other extensions and still have the issue

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="407" alt="Screenshot 2023-08-31 at 21 40 55" src="https://github.com/uBlockOrigin/uAssets/assets/46134534/c08221c8-33f1-4015-a1d4-c80bcb41e7ec">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98127
 cosmetic: 39427
 scriptlet: 18363
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69478-10, now
  easyprivacy: 33277-63, now
  plowe-0: 3726-1065, now
  ublock-badware: 7870-146, now
  ublock-filters: 34464-125, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 223-53, now
  ublock-unbreak: 2120-33, now
  urlhaus-1: 5874-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 157 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 56
 network:
  doubleclick.net: 5
  google.com: 12
  googlesyndication.com: 1
  googletagmanager.com: 1
  youtube.com: 37
 extended:
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(replace-node-text, script, (function serverContract(), con…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by DanNJ316** [comment]
Same thing is happening to me when I play YouTube videos through the Last.FM music website. Getting ads playing before videos where I never got them before. And not the usual 15-30 second ads, either. Ads that are over 2 minutes long in some cases, with no option to skip after a few seconds. Extremely annoying.

**Comment by stephenhawk8054** [comment]
@DanNJ316 Can you test these filters?

```adb
youtube.com,youtubekids.com,youtube-nocookie.com#@#+js(rpnt, script, (function serverContract(), 'const pruner=text=>{const json=JSON.parse(text);for(k of["playerAds","adPlacements","adSlots"]){json[k]=[];}return JSON.stringify(json);};const urlFromArg=arg=>{if(typeof arg==="string"){return arg;}if(arg instanceof Request){return arg.url;}return String(arg);};const realFetch=window.fetch;window.fetch=new Proxy(window.fetch,{apply:function(target,thisArg,args){if(!(urlFromArg(args[0]).includes("player?key="))){return Reflect.apply(target,thisArg,args);}return realFetch(...args).then(realResponse=>realResponse.text().then(text=>new Response(pruner(text),{status:realResponse.status,statusText:realResponse.statusText,headers:realResponse.headers,})));}}); (function serverContract()')

youtube.com,youtubekids.com,youtube-nocookie.com##+js(rpnt, script, /(\(function serverContract\(\)|writeEmbed|var _F_cssRowKey)/, 'const pruner=text=>{let json=JSON.parse(text);for(k of["playerAds","adPlacements","adSlots"]){json[k]=[];}return JSON.stringify(json);};const urlFromArg=arg=>{if(typeof arg==="string"){return arg;}if(arg instanceof Request){return arg.url;}return String(arg);};const realFetch=window.fetch;window.fetch=new Proxy(window.fetch,{apply:function(target,thisArg,args){if(!(urlFromArg(args[0]).includes("player?key="))){return Reflect.apply(target,thisArg,args);}return realFetch(...args).then(realResponse=>realResponse.text().then(text=>new Response(pruner(text),{status:realResponse.status,statusText:realResponse.statusText,headers:realResponse.headers,})));}});window.XMLHttpRequest.prototype.open=new Proxy(window.XMLHttpRequest.prototype.open,{apply:async(target,thisArg,args)=>{if(!(urlFromArg(args[1]).includes("player?key="))){return Reflect.apply(target,thisArg,args);}thisArg.addEventListener("readystatechange",function(){if(thisArg.readyState!==4){return;}const type=thisArg.responseType;if(type!==""&&type!=="text"){return;}const textin=thisArg.responseText;const textout=pruner(textin);if(textout===textin){return;}Object.defineProperty(thisArg,"response",{value:textout});Object.defineProperty(thisArg,"responseText",{value:textout});});return Reflect.apply(target,thisArg,args);}}); $1')
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by DanNJ316** [comment]
Added those filters, did not fix the issue, unfortunately.

**Comment by DanNJ316** [comment]
Re-started Firefox and now it does appear to be working, no ads playing before YouTube videos. Thank you very much!!

**Comment by stephenhawk8054** [comment]
@DanNJ316 Can you confirm if you remove those 2 filters, the ads come back? It could be that the embed video didn't load ads last time you check. As I see, ads in embed videos are quite unstable (sometimes occur, sometimes not).

**Comment by DanNJ316** [comment]
Yes, the ads did return when I removed those filters.

And you are right, there were a few videos where ads didn't play, but I'd say about 98% of them did. 

This was apparently a recent change somewhere along the way, not sure if with YouTube or Last.FM, because I did not start getting ads when I played music on that site until yesterday 8/31. And yet I would play the same video on the actual YouTube site, and no ads.

Thank you for your help! I would have never been able to resolve this issue on my own.

**Comment by stephenhawk8054** [comment]
Thanks for your feedback.

**Comment by DanNJ316** [comment]
I'd like to add after further experience:

The new filters work to eliminate ads when playing the embedded YouTube videos if you re-start your browser before watching the videos. The ads return if you start playing the videos during a current browsing session. At least that was my experience on Firefox. 

Not sure whar re-starting the browser has to do with anything, but it works. Been playing YouTube music videos through the Last.FM site for 2 hours now without any ads.

**Comment by stephenhawk8054** [comment]
Hmmm... I can reproduce that with the old filter, but with the new one, it should work. 

It would take time to test that again.
