### ISSUE TITLE
globlenews.in: detection

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#19554]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://globlenews.in/?pid=764875&lid=2cTb&vid=195470223`

### Category

detection

### Description

ask me to disable adblock

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1rc2
Chromium Mobile: 110
filterset (summary):
 network: 105818
 cosmetic: 130657
 scriptlet: 26207
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27431-30, 1m
  adguard-mobile-app-banners: 4584-8, 1m
  adguard-other-annoyances: 13341-14, 1m
  adguard-popup-overlays: 23765-58, now
  adguard-social: 21308-912, now
  adguard-widgets: 2297-4, now
  ublock-annoyances: 5502-188, now
  ublock-cookies-adguard: 308-308, now
 default:
  user-filters: 3-0, never
  adguard-mobile: 8606-12, 1m
  easylist: 69520-119, now
  easyprivacy: 33268-137, now
  plowe-0: 3727-1143, now
  ublock-badware: 7864-147, now
  ublock-filters: 34788-600, now
  ublock-privacy: 538-8, now
  ublock-quick-fixes: 274-69, 27m
  ublock-unbreak: 2125-37, now
  urlhaus-1: 5802-0, now
filterset (user): [array of 1231 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2041 ms (selfie)
 maxAssetCacheWait: 352 ms
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 1
  googletagmanager.com: 3
  gplinks.in: 2
 extended:
  ##.td_block_social_counter
  ##+js(no-fetch-if, googlesyndication)
```
</details>

**Comment by BlazeFTL** [comment]
@mapx- Issue Is From `https://gplinks.co/2cTb`
I See Breakage With That Rule
https://github.com/uBlockOrigin/uAssets/issues/19507

**Comment by mapx-** [comment]
provide more details about the breakage you are talking about

**Comment by BlazeFTL** [comment]
I Personally Use This -
```
globlenews.in,rontymobile.in,mynewsmedia.co,revadvert.com###VerifyBtn, #myTimerDiv, .MagicBtn, .nxBtn, #myNextInst, #NextBtn, #NextInfo, iframe:others()
@@||gplinks.in/track/*$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in
@@||googlesyndication.com^$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in
@@||doubleclick.net^$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in
@@||gplinks.co/cdn-cgi/challenge-platform/*$xhr,1p
@@||embed.tawk.to^$script,domain=gplinks.co
@@||challenges.cloudflare.com/cdn-cgi/challenge-platform/*$subdocument,domain=gplinks.co
@@*$ghide,domain=gplinks.co|rontymobile.in|globlenews.in
*$frame,redirect=noopframe,domain=rontymobile.in|globlenews.in,important
*$image,redirect-rule=1x1.gif,domain=mynewsmedia.co|revadvert.com|gplinks.co|rontymobile.in|globlenews.in
globlenews.in,rontymobile.in##+js(set, count, 0)
!globlenews.in,rontymobile.in##center, iframe:others()
globlenews.in,rontymobile.in##[id*="iframe"]:style(height: 1px !important; visibility: hidden !important;)
gplinks.co##.bg-soft-primary, a.exclude-pop.smartlink
gplinks.co#@##AdbModel
rontymobile.in#@#.adb-overlay
gplinks.co##+js(aopr, clickCount)
gplinks.co#@#+js(no-setInterval-if, href)
```
None Of Fix Works On My Side By Other Peps

**Comment by mapx-** [comment]
test

```
@@||gplinks.in^$xhr,script,domain=globlenews.in
globlenews.in#@#+js(rmnt, script, fetch)
```

however, when I whitelist gplinks I get detection on the last page

**Comment by mapx-** [comment]
I have to disable 
`globlenews.in,rontymobile.in##[id*="iframe"]:style(height: 1px !important; visibility: hidden !important;)`

otherwise I get blank page

**Comment by BlazeFTL** [comment]
Does Adding This Work On Your Side ?
`:style(opacity: 0 !important; pointer-events: none !important;)`
Big Fat Gaps Tho

**Comment by mapx-** [comment]
who cares, only used to download stuff

**Comment by Fatcavill** [comment]
its not working for me https://jomeramankahe.in/online-second-hand-phone-kha-se-kharide/#google_vignette

**Comment by BlazeFTL** [comment]
Updated Rules - New Domain
```
@@||gplinks.in/track/*$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in|jomeramankahe.in
@@||googlesyndication.com^$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in|jomeramankahe.in
@@||doubleclick.net^$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in|jomeramankahe.in
@@*$ghide,domain=gplinks.co|rontymobile.in|globlenews.in|jomeramankahe.in
*$frame,redirect=noopframe,important,domain=rontymobile.in|globlenews.in
*$image,redirect-rule=1x1.gif,domain=mynewsmedia.co|revadvert.com|gplinks.co|rontymobile.in|globlenews.in|jomeramankahe.in
jomeramankahe.in,globlenews.in,rontymobile.in##+js(set, count, 0)
jomeramankahe.in,globlenews.in,rontymobile.in##center, iframe:others()
jomeramankahe.in,globlenews.in,rontymobile.in##[id*="iframe"], [id*="gpt_unit"]:style(height: 0px !important; visibility: collapse;)
gplinks.co##.bg-soft-primary, a.exclude-pop.smartlink
gplinks.co#@##AdbModel
rontymobile.in#@#.adb-overlay
gplinks.co##+js(aopr, clickCount)
gplinks.co#@#+js(no-setInterval-if, href)

**Comment by Fatcavill** [comment]
working tnx🙏
