### ISSUE TITLE
multiup.org

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#19566]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

After clicking the Download buttons, it's supposed to open a link in a new tab but it doesn't.

### URL(s) where the issue occurs.

`https://multiup.org/en/mirror/ffb331d29164b4885647553c3634613c/Bald3ursGa3te-Update4.1.1.3686210-elamigos.part1.rar`

### Screenshot(s)

![c](https://github.com/uBlockOrigin/uAssets/assets/29574622/0daae844-8286-43bb-8db8-e44936cf449f)

### uBO version

1.51.0

### Browser name and version

Chrome Latest

### Settings

Default

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7897

Do not click download, just select the real link ( for example `https://gofile.io/d/o4vsrt` just bellow `valid 1 day ago`), right click it and open in a new tab

**Comment by SeriousHoax** [comment]
> duplicate #7897
> 
> Do not click download, just select the real link ( for example `https://gofile.io/d/o4vsrt` just bellow `valid 1 day ago`), right click it and click `go to that link` to open it in a new tab

Thanks. I thought since uBO now supports scriptlets and the issue doesn't happen with Adguard extension, I thought it might be fixable now.

**Comment by mapx-** [comment]
you could try (are you sure AG fix is working 100% ?) => it's uBO's equivalent filter:


```
multiup.eu,multiup.org#@#+js(ra, type, [type="hidden"], stay)
multiup.eu,multiup.org#@#+js(ra, action, [action*="multinews"], stay)
multiup.org,multiup.eu#@#+js(ra, class, [class="hidden"], stay)
multiup.*##+js(rpnt, script, /.*createElement.*/, function(){var e=document.querySelectorAll(".panel-footer > form[action] > button[link]")\,b=document.querySelectorAll(".panel-footer > form[action]")\,c=new RegExp(/mega\./);if(e.length===b.length)for(var f\,g=0;g<b.length;g++)f=e[g].getAttribute("link")\,b[g].setAttribute("action"\,f)\,b[g].setAttribute("target"\,"_blank")\,b[g].querySelector("input[name=\"link\"]").remove()\,c.test(f)||b[g].setAttribute("method"\,"GET");const h=a=>{a.preventDefault();var b=a?.currentTarget?.getAttribute("link");b?window.open(b):a.currentTarget.removeEventListener("click"\,h)};var i=document.querySelectorAll("button[link^=\"https://drive.google.com/\"]");i.forEach(a=>{a.addEventListener("click"\,h)})})
```

**Comment by SeriousHoax** [comment]
> you could try (are you sure AG fix is working 100% ?) => it's uBO's equivalent filter:
> 
> ```
> multiup.eu,multiup.org#@#+js(ra, type, [type="hidden"], stay)
> multiup.eu,multiup.org#@#+js(ra, action, [action*="multinews"], stay)
> multiup.org,multiup.eu#@#+js(ra, class, [class="hidden"], stay)
> multiup.*##+js(rpnt, script, /.*createElement.*/, function(){var e=document.querySelectorAll(".panel-footer > form[action] > button[link]")\,b=document.querySelectorAll(".panel-footer > form[action]")\,c=new RegExp(/mega\./);if(e.length===b.length)for(var f\,g=0;g<b.length;g++)f=e[g].getAttribute("link")\,b[g].setAttribute("action"\,f)\,b[g].setAttribute("target"\,"_blank")\,b[g].querySelector("input[name=\"link\"]").remove()\,c.test(f)||b[g].setAttribute("method"\,"GET");const h=a=>{a.preventDefault();var b=a?.currentTarget?.getAttribute("link");b?window.open(b):a.currentTarget.removeEventListener("click"\,h)};var i=document.querySelectorAll("button[link^=\"https://drive.google.com/\"]");i.forEach(a=>{a.addEventListener("click"\,h)})})
> ```

Hi! I'm not really an expert but what I meant to say is that instead of uBO if I use ADG extension with their own filters like ADG Base, Tracking, Annoyance, Social then clicking the download button takes me to the desired page. If you check it you should understand it better than me which ADG filter is making it work. 

Regarding your suggested scriptlet for uBO, it doesn't work. It's opening `multinews.me` which might be related to some ads. It's blocked by my Hagezi Multi Pro++ filter set in my Adguard Home.

**Comment by mapx-** [comment]
I modified the last filter above, test again
