### ISSUE TITLE
stockx.com: breakage

### ISSUE THREAD

**Issue by casi-casi** [uBlockOrigin/uAssets#19563]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://stockx.com/adidas-yeezy-foam-rnr-desert-sand`

### Category

breakage

### Description

Pricing information  and Related Items do not load properly. Areas are stuck loading. Immediately upon disabling UBO and reloading products load correctly. 

Error.
https://github.com/uBlockOrigin/uAssets/assets/130874965/8c643ede-1853-48d4-83de-ae9a8e52d483

Normal usage.
https://github.com/uBlockOrigin/uAssets/assets/130874965/1edab9bf-7278-43ba-9873-22d99bce6f06

https://github.com/uBlockOrigin/uAssets/assets/130874965/9b384458-9596-4339-9ffa-c0a2b079d4e4

### Other extensions used

1Password for Chrome.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/130874965/8933919f-cd51-45bc-8f9f-feb12c6fb5d7)
![image](https://github.com/uBlockOrigin/uAssets/assets/130874965/ce8faeee-8147-46ed-8ef9-b63c200df3e8)
![image](https://github.com/uBlockOrigin/uAssets/assets/130874965/de199eb8-b0b0-43e9-8458-09efc555cb3a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98205
 cosmetic: 39475
 scriptlet: 18369
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 16-0, never
  easylist: 69558-10, now
  easyprivacy: 33271-63, now
  plowe-0: 3724-1067, now
  ublock-badware: 7906-146, now
  ublock-filters: 34497-128, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 223-50, 1h.4m
  ublock-unbreak: 2120-33, now
  urlhaus-1: 5851-0, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 90 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 160 ms (selfie)
 maxAssetCacheWait: 56 ms
popupPanel:
 blocked: 21
 no-popups: true
 network:
  stockx.com: 6
  cloudflareinsights.com: 1
  cookielaw.org: 1
  d1wix2gc2cgqis.cloudfront.net: 1
  forter.com: 3
  google-analytics.com: 1
  googletagmanager.com: 1
  px-cloud.net: 2
  quantummetric.com: 3
  riskified.com: 1
  sift.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`||stockx.com/api/p/e$badfilter`


@ryanbr
