### ISSUE TITLE
security.nl: ads

### ISSUE THREAD

**Issue by ijuliank** [uBlockOrigin/uAssets#19562]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [-] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.security.nl/`

### Category

ads

### Description

ads 

### Other extensions used

none for adblocking

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/64658680/d4b960aa-6169-4cdb-9ef0-0ac2ba98c4fe)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98919
 cosmetic: 41546
 scriptlet: 18354
 html: 1028
listset (total-discarded, last-updated):
 added:
  NLD-0: 2906-16, now
 default:
  user-filters: 3-2, never
  ublock-filters: 35374-192, now
  ublock-badware: 7907-0, now
  ublock-privacy: 569-0, now
  ublock-unbreak: 2168-1, now
  ublock-quick-fixes: 223-0, now
  easylist: 69558-621, now
  easyprivacy: 33271-719, now
  urlhaus-1: 5851-0, now
  plowe-0: 3724-2, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1090 ms (selfie)
 maxAssetCacheWait: 255 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
report to the [regional list](https://github.com/EasyDutch-uBO/EasyDutch/issues)

@BPower0036

**Comment by BPower0036** [comment]
@mapx- fixed.

**Comment by ghost** [comment]
More ads are found in the sidebar which can be blocked with `div.sidebar_block.posting` . I am using uBlock Origin Lite in Trivalent by the way.

**Comment by mapx-** [comment]
report directly here: https://github.com/AdguardTeam/AdguardFilters#adguard-filters

**Comment by ghost** [comment]
It has been resolved
