### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by Noldorinn** [uBlockOrigin/uAssets#19567]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Description

Nothing loaded without search bar and left up 3dot button

### Other extensions used

deepl translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Ekran görüntüsü 2023-09-02 012707](https://github.com/uBlockOrigin/uAssets/assets/88163536/bfce0912-ba5e-49d3-a92a-dd023c893fa6)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 100
filterset (summary):
 network: 157557
 cosmetic: 94895
 scriptlet: 38786
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 73507-496, now
  adguard-mobile: 8609-45, now
  adguard-spyware: 55774-1161, now
  ublock-annoyances: 5442-42, now
 default:
  user-filters: 2198-9, never
  TUR-0: 13678-11, now
  easylist: 69475-1148, 59m
  easyprivacy: 33271-16631, now
  plowe-0: 3724-1235, now
  ublock-badware: 7905-364, 59m
  ublock-filters: 34498-3852, 59m
  ublock-privacy: 538-62, now
  ublock-quick-fixes: 223-50, 59m
  ublock-unbreak: 2120-147, 59m
  urlhaus-1: 5851-0, now
filterset (user): [array of 1996 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-extension-scheme
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3798 ms (selfie)
 maxAssetCacheWait: 549 ms
popupPanel:
 blocked: 6
 network:
  youtube.com: 5
  doubleclick.net: 1
 extended:
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(replace-node-text, script, (function serverContract(), con…
```
</details>

**Comment by Mobious** [comment]
Can confirm, having the same issue youtube no longer loading properly with uBlock enabled. Started within the past hour or so.

**Comment by redagito** [comment]
Can confirm

**Comment by Noldorinn** [comment]
Fixed now. No problem

**Comment by redagito** [comment]
Works for me now

**Comment by stephenhawk8054** [comment]
Please discuss in the pinned thread: https://github.com/uBlockOrigin/uAssets/issues/7636
