### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by PasAntinomiques** [uBlockOrigin/uAssets#19561]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=P3uF1dXbLI8`

### Category

breakage

### Description

No video description and recommended tab on the right when ublock origin is active.

### Other extensions used

Tried with None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/35699701/bf7d1996-9470-404f-ba0e-e8be54053b86)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 116698
 cosmetic: 48444
 scriptlet: 18429
 html: 1027
listset (total-discarded, last-updated):
 added:
  FRA-0: 28159-338, now
  ublock-quick-fixes: 214-1, 1h.16m
 default:
  user-filters: 1-0, never
  ublock-filters: 35374-155, 1h.16m
  ublock-badware: 7907-0, 1h.16m
  ublock-privacy: 569-0, now
  ublock-unbreak: 2168-0, 1h.16m
  easylist: 69527-733, 1h.16m
  easyprivacy: 33269-717, 1h.16m
  urlhaus-1: 5851-0, 1h.16m
  plowe-0: 3724-2, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 28 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 116 ms (selfie)
 maxAssetCacheWait: 59 ms
popupPanel:
 blocked: 27
 network:
  youtube.com: 9
  doubleclick.net: 4
  google.com: 14
 extended:
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(replace-node-text, script, (function serverContract(), con…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you force update all your filter lists and test again?

Then please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636
