### ISSUE TITLE
realestate.com.au: breakage

### ISSUE THREAD

**Issue by itsguan** [uBlockOrigin/uAssets#19569]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.realestate.com.au/buy/with-2-bedrooms-between-0-800000/map-1?numParkingSpaces=1&numBaths=2&misc=ex-under-contract&boundingBox=-4.9915804286481595,92.98828515624996,-48.187481679483874,173.80371484374996&source=refinement&sourcePage=map&sourceElement=location-tile-search`

### Category

breakage

### Description

The map doesnt load properly showing locations of available properties. When UBlock is disabled, it works normally

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19380441/1f264b75-f9bb-49d8-8c71-74f7163dc52f)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 98203
 cosmetic: 39458
 scriptlet: 18298
 html: 1027
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35366-174, now
  ublock-badware: 7908-1, now
  ublock-privacy: 569-0, now
  ublock-unbreak: 2168-1, now
  easylist: 69606-617, now
  easyprivacy: 33271-718, now
  urlhaus-1: 5817-0, now
  plowe-0: 3724-1, now
  ublock-quick-fixes: 223-0, 1h.51m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 108 ms (selfie)
 maxAssetCacheWait: 53 ms
popupPanel:
 blocked: 11
 network:
  realestate.com.au: 5
  maps.googleapis.com: 2
  newrelic.com: 4
```
</details>

**Comment by liamengland1** [comment]
caused by `||lexa.realestate.com.au^` in EP, map won't load without fingerprinting/doing "quality" checks - site is heavily protected by Kasada's anti-bot platform (`https://www.kasada.io/bot-mitigation/`)

**Comment by itsguan** [comment]
Thanks all
