### ISSUE TITLE
work.ink: nuisance

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#19579]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://work.ink/1QUd/llzzeroh`

### Category

nuisance

### Description

cant go past this. tried with fanboy annoyance filter too.

### Other extensions used

global speed, fastforward, violentmonkey w/adguard popup blocker script. disabled all of the ext. and tried, same result.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/3746b6a3-9bae-4f9f-bdd2-c6a47b77fd93)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98423
 cosmetic: 39473
 scriptlet: 18308
 html: 1028
listset (total-discarded, last-updated):
 removed:
  TUR-0: null
 default:
  user-filters: 0-0, never
  ublock-filters: 35389-97, now
  ublock-badware: 7908-0, now
  ublock-privacy: 569-0, now
  ublock-unbreak: 2168-1, now
  ublock-quick-fixes: 235-3, now
  easylist: 69843-706, now
  easyprivacy: 33258-718, now
  urlhaus-1: 5817-0, now
  plowe-0: 3724-2, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 313 ms
 maxAssetCacheWait: 118 ms
popupPanel:
 blocked: 9
 network:
  work.ink: 1
  adligature.com: 2
  googletagmanager.com: 3
  outbrain.com: 1
  quantserve.com: 2
 extended:
  ##.no-overlay
  ##.opera-container:style(visibility: collapse !important;)
  ##img[alt="Buff Banner"]:style(visibility: collapse !important;)
  ##+js(remove-attr, href, [href*="jump"], stay)
  ##+js(no-setInterval-if, a0b)
  ##+js(no-fetch-if, /outbrain|criteo|thisiswaldo|media\.net|ohbay…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
Which is the real destination ?

**Comment by erik9012** [comment]
https://qiwi.gg/folder/64f147842575c1e4c663f831

**Comment by mapx-** [comment]
without any new filter I'll land on destination page just clicking all "go to .."

proceed => go to destination => go to destination => countdown => go to destination => first page => click "go to destination" 4 times

**Comment by BlazeFTL** [comment]
I Only Got 2 Popup In The Last Page But Due To My Skill Issues I Cant Seem To Find The Source Of The Popup🥹
