### ISSUE TITLE
megatorrentshd.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1957]
URL(s) where the issue occurs

`http://www.megatorrentshd.com/rampage-destruicao-total-2018-hd-bluray-720p-e-1080p-dublado-legendado/`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`sharecool.us##script:inject(addEventListener-defuser.js,load)`
