### ISSUE TITLE
brother.pl: breakage

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uAssets#19574]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.brother.pl/support/dcpt520w/faqs/how-to-trouble-shooting/faq00100556_000`

### Category

breakage

### Description

Click the blue "Pokaż odpowiedź" (Show the answer) button - content does not load.

Exception for `||googletagmanager.com^` helps.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/886325/498e4c33-1787-4665-8386-e820f186296d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98371
 cosmetic: 39466
 scriptlet: 18301
 html: 1027
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35374-89, now
  ublock-badware: 7908-1, now
  ublock-privacy: 569-0, now
  ublock-unbreak: 2168-1, now
  ublock-quick-fixes: 226-3, now
  easylist: 69791-706, now
  easyprivacy: 33261-718, now
  urlhaus-1: 5817-0, now
  plowe-0: 3724-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 820 ms
 maxAssetCacheWait: 4 ms
popupPanel:
 blocked: 7
 network:
  brother.pl: 2
  brother.com: 2
  googletagmanager.com: 3
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`@@||googletagmanager.com/gtm.js$script,domain=support.brother.com`
