### ISSUE TITLE
sinnerclownceviri.com: detection

### ISSUE THREAD

**Issue by Darktowertr** [uBlockOrigin/uAssets#19576]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sinnerclownceviri.com/`

### Category

detection

### Description

It detects that it is an ad blocking extension and displays a warning on the screen as in the image. 

https://github.com/uBlockOrigin/uAssets/assets/39637917/46222edb-f4f0-49ae-baf4-113cca5dc9b3

### Other extensions used

Dark Reader, Mue(Newtab), Norton Safe Web, h264ify, h265ify, SimpleExtManager

https://github.com/uBlockOrigin/uAssets/assets/39637917/8e7ba46d-d9c0-40b5-819c-26f067fb8096

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 100149
 cosmetic: 49885
 scriptlet: 19824
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13678-11, 1m
  easylist: 69791-29, now
  easyprivacy: 33269-68, now
  plowe-0: 3724-1068, now
  ublock-badware: 7906-146, now
  ublock-filters: 34499-137, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 227-61, now
  ublock-unbreak: 2120-34, now
  urlhaus-1: 5817-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4267 ms
 maxAssetCacheWait: 47 ms
popupPanel:
 blocked: 2
 network:
  google.com: 1
  googlesyndication.com: 1
 extended:
  ##.reklam
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
keep only uBO enabled, disable all other extensions, test again

**Comment by Darktowertr** [comment]
![2023-09-02_18-48](https://github.com/uBlockOrigin/uAssets/assets/39637917/9655b72f-559e-46b4-a3ad-848f33398fb7)

**Comment by mapx-** [comment]
Do you get the detection only logging in the site ?

**Comment by Darktowertr** [comment]
It doesn't happen on the first visit to the site. It happens if you refresh the page while browsing or entering the site.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
