### ISSUE TITLE
mastercomfig.com: ads, breakage

### ISSUE THREAD

**Issue by Viceroyy** [uBlockOrigin/uAssets#19578]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mastercomfig.com/`
`https://mastercomfig.com/app/`
`https://mastercomfig.com/huds/1/`
`https://mastercomfig.com/hits/hs/1/`

### Category

ads

### Description

there is an ad lol

### Other extensions used

![Screenshot 2023-09-02 224059](https://github.com/uBlockOrigin/uAssets/assets/97338859/e95b9d26-dbfe-4243-9766-2acfc7e34581)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-09-02 223625](https://github.com/uBlockOrigin/uAssets/assets/97338859/982dcb78-ba3a-4825-aa9c-cb8d7f60b59d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 426904
 cosmetic: 366179
 scriptlet: 48603
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 712-8, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2256-78, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=3: 0-0, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4827-115, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25810-4, now
  ALB-0: 301-5, 1h.3m
  BGR-0: 1067-11, 1m
  CHN-0: 24857-136, 1m
  CZE-0: 745-1, 1m
  DEU-0: 7065-0, 1m
  EST-0: 463-2, 1m
  FIN-0: 2196-0, 1m
  [53 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  easylist: 69585-1686, now
  easyprivacy: 33258-17103, now
  plowe-0: 3724-1603, now
  ublock-badware: 7906-415, now
  ublock-filters: 34512-4479, now
  ublock-privacy: 538-140, now
  ublock-quick-fixes: 235-68, now
  ublock-unbreak: 2120-174, now
  urlhaus-1: 5817-2, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2877 ms (selfie)
 maxAssetCacheWait: 1335 ms
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 2
 extended:
  ##.align-items-center.row > a
```
</details>

**Comment by mapx-** [comment]
`mastercomfig.com##.card:has-text(S):has-text(p):has-text(o)`

**Comment by Daxy7** [comment]
Hardcoded ad:

```
https://mastercomfig.com/_astro/Sponsor.astro_astro_type_script_index_0_lang.14e81c0e.js
```

`TF2 Coaching Central Sponsor` with random divs `##.w222f824.card`. For the placeholder:

```
mastercomfig.com##.card:has-text(Sponsored by)
```

**Comment by stephenhawk8054** [comment]
@Daxy7 Does this work?

```adb
mastercomfig.com##div[class^="card "]
```

**Comment by Daxy7** [comment]
works

**Comment by mastercoms** [comment]
For the love of god, please stop breaking my site for tens of thousands of users with these incompetent rules. These comically broad rules only serve to destroy the user experience. Your lack of familiarity with the site has completely destroyed functionality on many different pages of the application and is only ruining your own reputation and user trust in ad block.

The only "ad" on the site is a first party outgoing link to an unpaid TF2 community project I am working with. There are no paid links, the ongoing project is domain specific and I am involved with it. It's completely asinine to week over week keep breaking and reverting these pointless, reckless and negligent rules.

**Comment by HurricanePootis** [comment]
Y'all have completely broken mastercomfig.com with these rules, please stop

**Comment by mapx-** [comment]
@mastercoms 

provide exact info: page, issue (what's broken), open the logger and tell us what filter and from list

**Comment by mastercoms** [comment]
You want to take my website hostage and break the user experience until I do free debugging work for you?

**Comment by mapx-** [comment]
just tell us the page and the issue

**Comment by HurricanePootis** [comment]
https://mastercomfig.com/app/ is broken.
## Comparison
This is how it currently is with the ublock origin.
![Screenshot_20230915_143005](https://github.com/uBlockOrigin/uAssets/assets/53066639/1b153e91-feba-4981-8c26-9678e8b8ea6e)
This is how it is without ublock origin
![Screenshot_20230915_143049](https://github.com/uBlockOrigin/uAssets/assets/53066639/bbe50b0a-e1f2-430c-9ddc-0d4c503fe02d)
## What filter
Disabling both EasyPrivacy and Pete's Lowes Ad whatever separately does not fix the bug. Disabling EasyList does fix the bug. Easylist is the filter that is ruining the site.
![image](https://github.com/uBlockOrigin/uAssets/assets/53066639/364e952c-dcdc-45bf-b9bf-86eecffc6004)

**Comment by ReplayCoding** [comment]
@mapx- Site is in the title: mastercomfig.com.
https://github.com/uBlockOrigin/uAssets/commit/299406c818ecae22c58682d69562ef82aeea95a6 should be reverted

**Comment by HurricanePootis** [comment]
> @mapx- Site is in the title: mastercomfig.com. [299406c](https://github.com/uBlockOrigin/uAssets/commit/299406c818ecae22c58682d69562ef82aeea95a6) should be reverted

I believe since mastercomfig uses a lot of cards, blindly getting rid of all cards ruined the site. So, I agree with replaycoding

**Comment by mapx-** [comment]
Home page or specific page ?

I asked for a specific page where we can see the breakage

**Comment by mapx-** [comment]
I disabled that filter, but **I'm waiting a page where I can see the breakage**.

**Comment by ReplayCoding** [comment]
Sorry, the broken page is https://mastercomfig.com/huds/1/

#### with rule:
![20230915_12h42m08s_grim](https://github.com/uBlockOrigin/uAssets/assets/25805985/20d5744e-d510-4fcd-be97-e1ec8af9a151)
#### without rule:
![20230915_12h42m36s_grim](https://github.com/uBlockOrigin/uAssets/assets/25805985/e4ca247f-507d-400e-a128-02408cd88188)
#### logger view
![20230915_12h43m53s_grim](https://github.com/uBlockOrigin/uAssets/assets/25805985/3216a8e5-a545-428b-9ca1-ada46d235269)

**Comment by HurricanePootis** [comment]
https://mastercomfig.com/huds/1/ is broken
## Comparison
This is what it looks like (all my filters are updated now)
![image](https://github.com/uBlockOrigin/uAssets/assets/53066639/6044906b-119c-4d52-bc42-c01e0a9cadad)
This is what it looks like with ublock off
![Screenshot_20230915_144312](https://github.com/uBlockOrigin/uAssets/assets/53066639/42321549-0285-4320-82a2-f40591da5a87)
## Filter?
I have tracked it down to `Ublock filters - Ads`. The specific filter is `mastercomfig.com##div[class^="card "]` at https://github.com/uBlockOrigin/uAssets/blob/86ea39ff7c3b35b24e8770c40272dd26dd869a41/filters/filters-2023.txt#L4511

**Comment by mapx-** [comment]
@ReplayCoding thanks, finally an answer

**Comment by mapx-** [comment]
wait 5-10 min then update again, the filter is disabled

**Comment by wgetJane** [comment]
question: do these filters get tested before being merged? it doesn't appear to be the case, so is there a reason for merging prior to checking if the filters actually do what is intended first? i'm curious about the process here
