### ISSUE TITLE
[nsfw] zz567.net: nuisance

### ISSUE THREAD

**Issue by Iss-in** [uBlockOrigin/uAssets#19570]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zz567.net/lastxs97868/`

### Category

nuisance

### Description

Site on opening is automatically redirected to a nsfw page, 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 108721
 cosmetic: 186322
 scriptlet: 28293
 html: 1215
listset (total-discarded, last-updated):
 added:
  adguard-social: 21312-841, 7m
  fanboy-cookiemonster: 48351-3957, 7m
  fanboy-social: 16237-8, 7m
  ublock-annoyances: 5402-289, 7m
  adguard-cookies: 27432-60, 7m
  adguard-popup-overlays: 23775-1489, 7m
  adguard-mobile-app-banners: 4588-1060, 7m
  adguard-other-annoyances: 13347-306, 7m
  adguard-widgets: 2296-1, 7m
  easylist-annoyances: 3945-129, 7m
  easylist-chat: 134-9, 7m
  easylist-newsletters: 6408-20, 7m
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35374-463, 50m
  ublock-badware: 7908-1, 52m
  ublock-privacy: 569-0, now
  ublock-unbreak: 2168-1, 51m
  ublock-quick-fixes: 226-3, 49m
  easylist: 69760-796, now
  easyprivacy: 33260-816, now
  urlhaus-1: 5817-0, now
  plowe-0: 3724-1, now
filterset (user): [empty]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1146 ms (selfie)
 maxAssetCacheWait: 372 ms
popupPanel:
 blocked: 2
 network:
  baidu.com: 1
  bdstatic.com: 1
```
</details>

**Comment by ghajini** [comment]
enable _adguard chinese_ regional list from ublock filter settings
