### ISSUE TITLE
jomeramankahe.in: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#19573]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://jomeramankahe.in/?pid=44684&lid=B8p6HYH&vid=195965427`

### Category

[Detection]

### Description

Anti-adblock

### Other extensions used

Violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 117
filterset (summary):
 network: 99719
 cosmetic: 30602
 scriptlet: 18360
 html: 1028
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35681-336, now
  ublock-badware: 7902-1, now
  ublock-privacy: 569-1, now
  ublock-unbreak: 2173-2, now
  ublock-quick-fixes: 223-0, 46m
  adguard-mobile: 8609-123, now
  easylist: 69760-16666, now
  easyprivacy: 33260-725, now
  urlhaus-1: 5817-0, now
  plowe-0: 3724-1, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 32549 ms (selfie)
 maxAssetCacheWait: 2204 ms
popupPanel:
 blocked: 10
 network:
  arglingpistole.com: 2
  doubleclick.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 3
```
</details>

**Comment by BlazeFTL** [comment]
@aicynide Adding This In My Filters Doesn't Work ?
```
@@||gplinks.in/track/*$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in|jomeramankahe.in
@@||googlesyndication.com^$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in|jomeramankahe.in
@@||doubleclick.net^$script,xhr,domain=rontymobile.in|gplinks.co|globlenews.in|jomeramankahe.in
@@*$ghide,domain=gplinks.co|rontymobile.in|globlenews.in|jomeramankahe.in
*$frame,redirect=noopframe,important,domain=rontymobile.in|globlenews.in|jomeramankahe.in
*$image,redirect-rule=1x1.gif,domain=mynewsmedia.co|revadvert.com|gplinks.co|rontymobile.in|globlenews.in|jomeramankahe.in
jomeramankahe.in,globlenews.in,rontymobile.in##+js(no-fetch-if, googlesyndication)
jomeramankahe.in,globlenews.in,rontymobile.in##+js(set, count, 0)
jomeramankahe.in,globlenews.in,rontymobile.in##center:others()
jomeramankahe.in,globlenews.in,rontymobile.in##[id*="iframe"], [id*="gpt_unit"]:style(opacity: 0 !important; pointer-events: none !important;)
gplinks.co##.bg-soft-primary, a.exclude-pop.smartlink

**Comment by aicynide** [comment]
@BlazeFTL no idea. I'll check soon

**Comment by aicynide** [comment]
Is it fixed? Please.don't close without fixing. Thanks

**Comment by mapx-** [comment]
> no idea. I'll check soon

Provide feedback.
