### ISSUE TITLE
[NSFW] vid1.kimcilonly.site: popups

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#19581]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Clicking anywhere on the site will cause a blocked ad site to pop up.

### URL(s) where the issue occurs.

`https://vid1.kimcilonly.site/`

### uBO version

v1.51.1rc2

### Browser name and version

Firefox 117.0

### Settings

- Use custom filters, checked "I am an advanced user"

**Comment by ghajini** [comment]
@gmarcher
`kimcilonly.site##+js(nowoif)`
