### ISSUE TITLE
androidescomplicado.blogspot.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1958]
URL(s) where the issue occurs

`http://androidescomplicado.blogspot.com/2017/03/mega-filmes-series-hd-v0-3-8-apk-download.html`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`androidescomplicado.*##script:inject(bab-defuser.js)`
