### ISSUE TITLE
voe.sx: detection

### ISSUE THREAD

**Issue by hdloader11** [uBlockOrigin/uAssets#19582]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Getting the below error when trying to play a video:

Disable your adblock to use VOE.

Servers cost money. No advertising = no video

Seems like it happened in the last 2 hours, as it was fine beforehand

### URL(s) where the issue occurs.

voe.sx/b78j20fhpxv1

### uBO version

Version 1.51.0

### Browser name and version

Firefox 117.0

### Settings

None

**Comment by liamengland1** [comment]
redirects to `yodelswartlike.com` ... i guess this new domain needs to be added here https://github.com/uBlockOrigin/uAssets/blob/1657c8b483b0513acfb4acb4e6dcadf18262edf5/filters/filters-2020.txt#L2797-L2802
