### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by JpCg22** [uBlockOrigin/uAssets#19584]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Description

It is not filtering YouTube ads, although they are the ones that are less than 20 seconds long.

### Other extensions used

Only MEGA

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 284496
 cosmetic: 185237
 scriptlet: 43562
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27432-1586, 34m
  adguard-generic: 73468-700, 34m
  adguard-mobile: 8612-67, 34m
  adguard-mobile-app-banners: 4588-17, 34m
  adguard-other-annoyances: 13347-14, 34m
  adguard-popup-overlays: 23776-105, 34m
  adguard-social: 21312-2050, 34m
  adguard-widgets: 2296-38, 34m
  curben-phishing: 153990-47, 34m
  curben-pup: 189-0, 34m
  easylist-annoyances: 3945-1089, 34m
  easylist-chat: 134-17, 34m
  [8 lists not shown]: [too many]
 default:
  user-filters: 5-1, never
  easylist: 69807-16936, 34m
  easyprivacy: 33260-284, 34m
  plowe-0: 3724-1153, 34m
  spa-0: 3770-296, 34m
  spa-1: 5531-302, 34m
  ublock-badware: 7906-388, 34m
  ublock-filters: 34515-4420, 34m
  ublock-privacy: 538-9, 34m
  ublock-unbreak: 2120-101, 34m
  urlhaus-1: 5770-1, 34m
filterset (user): [array of 5 redacted]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings:
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
 largeMediaSize: 60
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2347 ms (selfie)
 maxAssetCacheWait: 1830 ms
popupPanel:
 blocked: 9
 network:
  youtube.com: 8
  doubleclick.net: 1
 extended:
  ###contents > ytd-rich-item-renderer:has(> #content > ytd-ad-slo…
  ###offer-module
  ###ticker.ytd-masthead
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-set-cookie, SOCS, CAESEwgDEgk1MjE4NjcxMTIaAmVuIAEa…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue in this: https://github.com/uBlockOrigin/uAssets/issues/7636 and give exact links where you see the ads.

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
