### ISSUE TITLE
gaz.com.br: nuisance

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#19588]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gaz.com.br/`

### Category

nuisance

### Description

`www.gaz.com.br##+js(aeld, contextmenu)`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 168397
 cosmetic: 225921
 scriptlet: 44726
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 981-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2256-0, now
  adguard-cookies: 27432-29, now
  adguard-generic: 73468-468, now
  adguard-mobile-app-banners: 4588-9, now
  adguard-other-annoyances: 13347-7, now
  adguard-popup-overlays: 23776-71, now
  adguard-social: 21312-909, now
  adguard-spyware: 55775-1328, now
  adguard-spyware-url: 1197-145, now
  adguard-widgets: 2296-6, now
  easylist-annoyances: 3946-235, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 106-0, never
  easylist: 69965-1100, now
  easyprivacy: 33264-16726, now
  plowe-0: 3724-1161, now
  spa-1: 5531-78, now
  ublock-badware: 7906-363, now
  ublock-filters: 34519-4255, now
  ublock-privacy: 538-137, now
  ublock-quick-fixes: 223-58, 35m
  ublock-unbreak: 2122-150, now
  urlhaus-1: 5770-0, now
filterset (user): [array of 58 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 4883 ms (selfie)
 maxAssetCacheWait: 395 ms
popupPanel:
 blocked: 6
 network:
  addthis.com: 1
  alright.network: 1
  googletagmanager.com: 2
  newrelic.com: 2
 extended:
  ##.social-menu
```
</details>

**Comment by mapx-** [comment]
@D4niloMR you have to always provide an explanation on the reported issue

@Yuki2718 
for portuguese list
`gaz.com.br##.ads`
