### ISSUE TITLE
info.vebma.com: detection

### ISSUE THREAD

**Issue by Fahmi283** [uBlockOrigin/uAssets#19585]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://info.vebma.com/unveiling-the-hidden-gem-of-indonesia-wisata-kaliadem`

### Category

detection

### Description

adsblock detected

### Other extensions used

fast forward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/56343596/da3544f6-c246-4915-94ee-5c50bd9027cb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98087
 cosmetic: 39460
 scriptlet: 18370
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 69532-10, 31m
  easyprivacy: 33258-63, 31m
  plowe-0: 3724-1067, 31m
  ublock-badware: 7906-146, 30m
  ublock-filters: 34499-127, 30m
  ublock-privacy: 538-6, 30m
  ublock-quick-fixes: 235-62, 30m
  ublock-unbreak: 2120-33, 30m
  urlhaus-1: 5770-0, 30m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 863 ms
 maxAssetCacheWait: 323 ms
popupPanel:
 blocked: 3
 network:
  dundeesmemo.com: 1
  pubfuture-ad.com: 1
  trvdp.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by Fahmi283** [comment]
https://wts.pw/WFlXvgMSNR

Pada tanggal Min, 3 Sep 2023 pukul 10.51 MasterKia ***@***.***>
menulis:

**Comment by ghajini** [comment]
Enable regional _**ABPIndo**_ list

**Comment by Fahmi283** [comment]
fixed
