### ISSUE TITLE
filmesonlinegratis.com [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1959]
URL(s) where the issue occurs

`http://www.filmesonlinegratis.com/rei-arthur.html`

Describe the issue

![](https://i.imgur.com/nBnaKYL.png)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`filmesonlinegratis.com##script:inject(abort-on-property-write.js,smrtSB)`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7bb7a3565385cf580ab412e6cfe716454a061316
