### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Camadams1179** [uBlockOrigin/uAssets#19595]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=Mt_2IWjb8wc&ab_channel=Toni`

### Category

detection

### Description

Ad Blocking banner displays on newly loaded videos.

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/109619090/8b6ec4fd-492d-4bc7-8ba4-e4b653262194)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/109619090/d71d6434-3b77-4ae3-b74f-def64a953222)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98585
 cosmetic: 39490
 scriptlet: 18325
 html: 1028
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35398-97, 11m
  ublock-badware: 7908-0, 10m
  ublock-privacy: 570-0, 10m
  ublock-unbreak: 2170-0, 10m
  ublock-quick-fixes: 243-4, 10m
  easylist: 70023-706, 10m
  easyprivacy: 33266-718, 10m
  urlhaus-1: 5806-0, 10m
  plowe-0: 3724-2, 10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 226 ms
 maxAssetCacheWait: 89 ms
popupPanel:
 blocked: 48
 network:
  youtube.com: 26
  doubleclick.net: 6
  google.com: 16
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
duplicate

see the indications here: https://github.com/uBlockOrigin/uAssets/issues/7636
