### ISSUE TITLE
nl.gymshark.com: breakage

### ISSUE THREAD

**Issue by Struisvogel93** [uBlockOrigin/uAssets#19591]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nl.gymshark.com/`

### Category

breakage

### Description

country selection confirm button does not work with ublock enabled

### Other extensions used

privacybadger
1password

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98585
 cosmetic: 39492
 scriptlet: 18323
 html: 1028
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35398-97, now
  ublock-badware: 7908-0, now
  ublock-privacy: 570-0, now
  ublock-unbreak: 2170-1, now
  ublock-quick-fixes: 243-3, now
  easylist: 70023-706, now
  easyprivacy: 33266-718, now
  urlhaus-1: 5806-0, now
  plowe-0: 3724-2, now
filterset (user): [empty]
trustedset:
 added: [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 191 ms (selfie)
 maxAssetCacheWait: 104 ms
popupPanel:
 blocked: 5
 network:
  browser-intake-datadoghq.eu: 2
  cookielaw.org: 1
  googletagmanager.com: 1
  mparticle.com: 1
```
</details>

**Comment by mapx-** [comment]
test this filter

`@@||jssdkcdns.mparticle.com/js/*/mparticle.js?env=0$script,domain=gymshark.com`
