### ISSUE TITLE
athletic.net: nuisance

### ISSUE THREAD

**Issue by Jap2-0** [uBlockOrigin/uAssets#19592]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Previously: #4877, #13830.

When looking at the profile of an athlete (with annoyances lists enabled), some of the information from past years is unblurred (although not all anymore), but the times are replaced with 22:22.2.  (I think this was previously stopped by hooking a function or something.)

This obfuscation occurs client side, which appears to be currently in the file `https://angular.athletic.net/app/site-app/athletic-web_src_web_modules_team-header_team-header_component_ts.73b769cb5303316a.js`, with this code:

```
let Ne = (() => {
   class n {
      transform(t, o = !0) {
         var s;
         return t = null === (s = t) || void 0 === s ? void 0 : s.toString(), o && t ? t.replace(/[a-z]/g, "x").replace(/[A-Z]/g, "X").replace(/\d/g, "2") : t
      }
   }
   return n.\u0275fac = function(t) {
      return new(t || n)
   }, n.\u0275pipe = e.Yjl({
      name: "blurText",
      type: n,
      pure: !0,
      standalone: !0
   }), n
})();
```

### URL(s) where the issue occurs.

`https://www.athletic.net/athlete/15781948/cross-country/high-school`

### uBO version

1.51.1rc2

### Browser name and version

Firefox 119

### Settings

(I have also tested this with a default install; this is not relevant to a uBO without annoyances lists)

**Comment by mapx-** [comment]
- disable uBO for the page above
- right click and inspect the time (you see as `22:22.2`)
=> it's really `22:22.2` in the code

**Comment by Jap2-0** [comment]
@mapx- it's replaced in the DOM by JS, the times for all meets are returned in `https://www.athletic.net/api/v1/AthleteBio/GetAthleteBioData?athleteId=15781948&sport=xc&level=4`

**Comment by mapx-** [comment]
On my side I cannot find `blurText` in the script above

**Comment by Jap2-0** [comment]
It appears I somehow copied the wrong URL - it should be `https://angular.athletic.net/app/site-app/athletic-web_src_web_modules_athlete-bio_athlete-bio_routes_ts-node_modules_lodash_clone_js-n-1d5947.cdacd63564f1834f.js`.  Sorry.

**Comment by mapx-** [comment]
I doubt we can fix such a thing. In the end a free account is necessary to see the stats.
