### ISSUE TITLE
torrentmac.net: nuisance

### ISSUE THREAD

**Issue by patdiddy** [uBlockOrigin/uAssets#19598]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.torrentmac.net/`

### Category

nuisance

### Description

Even after multiple attempts to fix this issue, the creators of the website always seem to manage to create new ways to get around the uBlock Origins filters. No matter what I do, I think these guys will at some point have either clickbait, hidden site ads that get triggered the minute you click on something, or some form of trickery that will eventually foil uBlock Origins' filters, because some days it works, and others, it just stops working all together.

If there was a better alternative to this site, I would've been using it by now, but, since most of the other sites out there are a lot less reputable than this one, it's rather imperative that the filters should work properly on that site. I already see that it's been marked as solved, but it's a never ending cycle to be completely honest.

### Other extensions used

Dark Reader, Last Pass, Rakuten, Paypal Honey, Similarsites, Bitwarden, and Web of Trust.

### Screenshot(s)

<details>

[Site with the issue](https://www.torrentmac.net/?s=recover)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 117
filterset (summary):
 network: 98632
 cosmetic: 39515
 scriptlet: 18390
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 39-1, never
  easylist: 70049-10, now
  easyprivacy: 33265-63, now
  plowe-0: 3724-1067, now
  ublock-badware: 7905-146, now
  ublock-filters: 34521-130, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 243-68, now
  ublock-unbreak: 2122-33, now
  urlhaus-1: 5806-0, now
filterset (user): [array of 39 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1323 ms (selfie)
 maxAssetCacheWait: 263 ms
popupPanel:
 blocked: 18
 network:
  accidentallyrussian.com: 1
  d1tt3ye7u0e0ql.cloudfront.net: 4
  doubleclick.net: 1
  google-analytics.com: 2
  googlesyndication.com: 3
  nothiermonicg.com: 4
  profitstefukhatex.info: 2
  s3.us-east-1.amazonaws.com: 1
 extended:
  ##+js(abort-current-script, JSON, break;case)
  ##+js(addEventListener-defuser, , Math)
  ##+js(no-setTimeout-if, show)
```
</details>

**Comment by mapx-** [comment]
which is your issue ? provide exact steps to get it

**Comment by krystian3w** [comment]
Try wait ~10 minutes after Chromium 117 started and then open that page.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
