### ISSUE TITLE
cryptoearns.com: detection

### ISSUE THREAD

**Issue by Lahiru2002** [uBlockOrigin/uAssets#19599]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cryptoearns.com/`

### Category

detection

### Description

Adblocker detected brave browser.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/75168867/0fe33a64-bfc3-4359-becd-81231a59cbd6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98569
 cosmetic: 23434
 scriptlet: 18419
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 121-4, never
  easylist: 69988-15940, 54m
  easyprivacy: 33267-65, 54m
  plowe-0: 3724-1067, 54m
  ublock-badware: 7905-146, 54m
  ublock-filters: 34524-341, 54m
  ublock-privacy: 538-7, 54m
  ublock-quick-fixes: 243-65, 1h.17m
  ublock-unbreak: 2122-34, 54m
  urlhaus-1: 5809-0, 54m
filterset (user): [array of 40 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 9 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 12398 ms
 maxAssetCacheWait: 1974 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
@Lahiru2002 keep in mind you have to provide all the necessary details (such as **an account is needed to reproduce the issue**)

**Comment by huyszn** [comment]
The site now detects on other browsers like firefox and chrome with "ADBLOCK DETECTED" message without an account.

**Comment by ItsProfessional** [comment]
fixed.
also, account no longer needed to reproduce detection
