### ISSUE TITLE
ivg.it: detection

### ISSUE THREAD

**Issue by m4nd312** [uBlockOrigin/uAssets#19596]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ivg.it/`

### Category

detection

### Description

anti adblocker, https://cdn.cookielaw.org/consent/eb7322bc-5066-4f9b-9a43-4130fdeb474c/OtAutoBlock.js

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 116
filterset (summary):
 network: 102134
 cosmetic: 46423
 scriptlet: 18325
 html: 1028
listset (total-discarded, last-updated):
 default:
  user-filters: 17-1, never
  ublock-filters: 35398-107, 58m
  ublock-badware: 7908-0, 58m
  ublock-privacy: 570-0, 58m
  ublock-unbreak: 2170-0, 58m
  easylist: 70023-713, 58m
  easyprivacy: 33266-719, 58m
  urlhaus-1: 5806-0, 58m
  plowe-0: 3724-2, 58m
  ITA-0: 10503-19, 58m
  ublock-quick-fixes: 243-4, 58m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2027 ms
 maxAssetCacheWait: 204 ms
popupPanel:
 blocked: 8
 network:
  cookielaw.org: 2
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 4
 extended:
  ##.adunit
  ##.pubblicita
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
already blocked by Easyprivacy list

**Comment by m4nd312** [comment]
I do not argue, but the adblock is detected.

**Comment by mapx-** [comment]
Do I need an account to reproduce the detection ? or visit a specific page ?
Could you upload a screenshot with that detection ?

**Comment by m4nd312** [comment]
![screen](https://github.com/uBlockOrigin/uAssets/assets/8605934/b91962e7-f782-4cd4-8df2-762ab0c766b6)

**Comment by m4nd312** [comment]
these are the activated filters
![filters](https://github.com/uBlockOrigin/uAssets/assets/8605934/f8e9005b-42a4-41f0-95f3-af0a83699839)

**Comment by mapx-** [comment]
does this filter help ?

`||ivg.it/wp-content/plugins/edinet_giornali_swg_plugin/js/ackdet.js`

**Comment by m4nd312** [comment]
Yes. 
I was so close, but so far away, thank you very much!
