### ISSUE TITLE
vatera.hu blocked script

### ISSUE THREAD

**Issue by kovacsattila-hun** [uBlockOrigin/uAssets#196]
### URL(s) where the issue occurs

`http://auto-motor.vatera.hu/motor_robogo_quad_alkatresz_felszereles/eroatviteli_alkatresz/fek_fekrendszer/fektarcsa/fektarcsa_renault_clio_2db_uj_2388837974.html`

### Describe the issue

Page operational issues, no work "Licitálj" orange button on all website.

### Screenshot(s)

http://i.imgur.com/v15igp4.png

### Versions

- Browser/version: Google Chrome (Windows) 54.0.2840.99 64 bit
- uBlock Origin version: v1.9.16

### Settings

- All default settings.

### Notes

Recommended add filter to uBlock Unbreak filterlist: @@||google-analytics.com/ga.js$domain=vatera.hu

**Comment by gorhill** [comment]
Ensure all your filter lists are up to date, this was [fixed yesterday](https://github.com/uBlockOrigin/uAssets/commit/2dfeece7cfe671e93573db6d176901cf2df37623) (without the need for an exception filter).
