### ISSUE TITLE
shimano tourney

### ISSUE THREAD

**Issue by DarkPhoinix** [uBlockOrigin/uAssets#19603]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=AfsnHVaScjg`

### Category

ads

### Description

i cant see video of ads(black screen) but i need wait and ear sound 

### Other extensions used

Audio Downloader Prime
Bookmarks clean up
Chrome extension source viewer
Documenti Google offline
DuckDuckGo Privacy Essentials
EditThisCookie
Free Download Manager
Keepa - Amazon Price Tracker
MEGA
New Tab Redirect
Photo Downloader
Tampermonkey
uBlock Origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/21277109/e08aad4d-392f-427c-98bf-ad4b6c98a7ac)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 102149
 cosmetic: 46450
 scriptlet: 18401
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ITA-0: 10528-18, now
  easylist: 70058-17, now
  easyprivacy: 33239-64, now
  plowe-0: 3724-1068, now
  ublock-badware: 7946-146, now
  ublock-filters: 34529-138, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 237-56, now
  ublock-unbreak: 2122-33, now
  urlhaus-1: 5776-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 864 ms (selfie)
 maxAssetCacheWait: 320 ms
popupPanel:
 blocked: 94
 network:
  youtube.com: 69
  doubleclick.net: 8
  google.com: 6
  googlesyndication.com: 11
 extended:
  ###merch-shelf
  ###player-ads
  ##.ad-showing > .html5-video-container
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-button
  ##.ytp-ad-player-overlay-flyout-cta
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  #@#.video-ads
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
YT issues => https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by DarkPhoinix** [comment]
no is not youtube video problem is ADS not full blocked!

**Comment by DarkPhoinix** [comment]
and Tampermonkey®Local YouTube Downloader script enable.
I have Local YouTube Downloader  enabled from years and this problem is started Yesterday.
If disable Local YouTube Downloader or change youtube account the problem is solved. 
But, WHY?

**Comment by stephenhawk8054** [comment]
The thread is "ALL Youtube.com" issue.
