### ISSUE TITLE
chordelectronics.co.uk: breakage

### ISSUE THREAD

**Issue by miltonjsvidal** [uBlockOrigin/uAssets#19606]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chordelectronics.co.uk/es/product/hugo-2`

### Category

breakage

### Description

none

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 169431
 cosmetic: 200609
 scriptlet: 27745
 html: 1241
listset (total-discarded, last-updated):
 added:
  https://gist.githubusercontent.com/Rust1667/df78d493cf3c00340c535d93e303c4f9/raw: 189-1, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdRemovalListForUnusualAds.txt: 224-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 420-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2257-2, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt: 50721-9005, now
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 214-0, now
  https://raw.githubusercontent.com/stephenhawk8054/PrivacyExtended/main/privacy_extended.txt: 17440-39, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1031-3, now
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 94-0, now
  https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42453-230, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93309-77752, now
  block-lan: 48-0, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 23-0, never
  ublock-filters: 35411-349, now
  ublock-badware: 7948-29, now
  ublock-privacy: 570-44, now
  ublock-unbreak: 2170-1, now
  ublock-quick-fixes: 237-0, now
  easylist: 70058-14643, now
  easyprivacy: 33239-3872, now
  urlhaus-1: 5776-0, now
  plowe-0: 3724-1, now
  spa-0: 3771-3, now
  spa-1: 5563-175, now
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings:
 autoUpdatePeriod: 1
 cnameMaxTTL: 1080
supportStats:
 allReadyAfter: 3190 ms (selfie)
 maxAssetCacheWait: 1826 ms
popupPanel:
 blocked: 15
 network:
  chordelectronics.co.uk: 2
  ads-twitter.com: 1
  d10lpsik1i8c69.cloudfront.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  hs-scripts.com: 4
  maps.googleapis.com: 1
  youtube.com: 3
 extended:
  ##.social-icons
  ##.fa-facebook-official
  ##.fa-twitter-square
  ##.fa-instagram
  ##.fa-youtube-square
  ##.social-icons-small
  ##.share-buttons
  ##a[href^="https://twitter.com/intent/tweet"]
  ##a[href^="http://www.linkedin.com/shareArticle?"]
  ##a[href^="http://www.reddit.com/submit"]
  ##a[href^="https://plus.google.com/share?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##[href*="facebook.com/sharer/sharer.php?"]
  ##[href*="linkedin.com/shareArticle"]
  ##[href*="reddit.com/submit?url="]
  ##[href*="twitter.com/intent/tweet"]
```
</details>

**Comment by mapx-** [comment]
- reset uBO to default settings / lists
- force update all lists
- test again
- if still breakage **explain** what are you talking about, provide steps to reproduce it, add screenshot etc
