### ISSUE TITLE
xe.com: breakage

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#19600]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.xe.com/`

### Category

breakage

### Description

The “Allow optional cookies?” pop-up doesn't close when you click on the blue “Accept” button with uBlock Origin enabled.

### Other extensions used

Tampermonkey
Auto Refresh Plus | Page Monitor
Disable automatic tab discarding
Disable Google Lens

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![www xe com_](https://github.com/uBlockOrigin/uAssets/assets/22180480/854f34fc-e77a-407c-9452-d88cdbc5c23d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 99938
 cosmetic: 47047
 scriptlet: 18606
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  POL-0: 7991-11, 1m
  POL-2: 1276-13, 1m
  easylist: 69985-33, now
  easyprivacy: 33240-63, now
  plowe-0: 3724-1074, now
  ublock-badware: 7905-146, now
  ublock-filters: 34516-166, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 236-55, now
  ublock-unbreak: 2122-34, now
  urlhaus-1: 5809-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 891 ms
 maxAssetCacheWait: 408 ms
popupPanel:
 blocked: 2
 network:
  amplitude.com: 1
  googletagmanager.com: 1
 extended:
  ##.advertSlot
```
</details>

**Comment by mapx-** [comment]
add

`@@||cdn.amplitude.com/libs/amplitude-7.2.1-min.gz.js$script,domain=xe.com`

@ryanbr
