### ISSUE TITLE
feedar.net: breakage

### ISSUE THREAD

**Issue by bioengineered** [uBlockOrigin/uAssets#19605]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://feedar.net/?pid=864676&lid=ANpPZ&vid=197127262`

### Category

breakage

### Description

When uBlock is on, there is no countdown to continue to download.
The page just displays the "ad" or content it is paying to show.

Without uBlock, the page is covered in ads as well as aforementioned content and also contains a countdown at the top of the page where one must click "verify" at the top of the page and "continue" at the bottom of the page.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Before and After uBlock Screenshot(s)</summary>

<img width="1440" alt="Screenshot 2023-09-04 at 12 22 55 PM" src="https://github.com/uBlockOrigin/uAssets/assets/95315697/5867e406-1008-4c3e-898d-3bd906465f67">

<img width="1440" alt="Screenshot 2023-09-04 at 12 23 23 PM" src="https://github.com/uBlockOrigin/uAssets/assets/95315697/fed4d31a-eb59-4afd-9060-88b22029b3ca">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98596
 cosmetic: 39504
 scriptlet: 18337
 html: 1028
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 35407-43, 3m
  ublock-badware: 7948-1, 3m
  ublock-privacy: 570-0, 3m
  ublock-unbreak: 2170-2, 3m
  ublock-quick-fixes: 237-41, 2m
  easylist: 70058-707, 2m
  easyprivacy: 33239-718, 2m
  urlhaus-1: 5776-0, 2m
  plowe-0: 3724-1, 2m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 937 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 2
  googletagmanager.com: 2
  gplinks.in: 2
 extended:
  ##+js(remove-node-text, script, fetch)
```
</details>

**Comment by mapx-** [comment]
do not open new issues for the same page and report ALL the issues for the page
