### ISSUE TITLE
galaxyos.net: ads

### ISSUE THREAD

**Issue by Trum00thay** [uBlockOrigin/uAssets#19608]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://galaxyos.net/resources/vietmap-s2-crack-full-dan-duong-o-to-chuyen-dung.251/updates`

### Category

ads

### Description

ads detected

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 317619
 cosmetic: 80293
 scriptlet: 34324
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 2260-0, 19m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 981-2, never
  https://raw.githubusercontent.com/ethan-xd/ethan-xd.github.io/master/fb.txt: 143-0, never
  https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/all_search_engines/global.txt: 7000-8, never
  adguard-generic: 73552-490, 20m
  adguard-spyware: 55995-1136, 20m
  adguard-spyware-url: 1198-145, 20m
  block-lan: 48-0, 20m
  curben-phishing: 145632-32, 20m
  curben-pup: 189-0, 20m
  dpollock-0: 11552-195, 19m
 default:
  user-filters: 2-0, never
  VIE-1: 1935-0, 20m
  easylist: 70058-1297, 19m
  easyprivacy: 33239-16654, 19m
  plowe-0: 3724-1514, 19m
  ublock-badware: 7946-383, 19m
  ublock-filters: 34534-3846, 19m
  ublock-privacy: 538-135, 19m
  ublock-quick-fixes: 237-56, 19m
  ublock-unbreak: 2122-146, 19m
  urlhaus-1: 5711-2, 19m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 362 ms (selfie)
 maxAssetCacheWait: 238 ms
popupPanel:
 blocked: 3
 network:
  galaxyos.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by FanOfRootBeer** [comment]
@hoang-rio 
```
galaxyos.net##+js(nostif, show)
```
