### ISSUE TITLE
kimcartoon.co [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1960]
URL(s) where the issue occurs

`https://kimcartoon.co/Cartoon/Power-Rangers-Super-Ninja-Steel-Season-25/Episode-008-Caught-Red-Handed?id=78637`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`kimcartoon.co##script:inject(set-constant.js,check_adblock,true)`

**Comment by KiLL4FuNK** [comment]
you can not see the video

`https://kimcartoon.ac/Cartoon/Haunted-Transylvania-2/Episode-Movie?id=81429`
