### ISSUE TITLE
eltucumano.com: ads

### ISSUE THREAD

**Issue by DiazFernandito** [uBlockOrigin/uAssets#19619]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.eltucumano.com/`

### Category

ads

### Description

The site Shows ads

### Other extensions used

Privacy Badget

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Captura de pantalla 2023-09-05 202928](https://github.com/uBlockOrigin/uAssets/assets/128551914/e26b04c5-9c89-4b5b-9f8e-5c72a334d4a1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 101103
 cosmetic: 45678
 scriptlet: 18781
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 70090-10, now
  easyprivacy: 33245-63, now
  plowe-0: 3725-1067, now
  spa-0: 3771-19, now
  spa-1: 5565-224, now
  ublock-badware: 7954-146, now
  ublock-filters: 34541-158, now
  ublock-privacy: 538-6, now
  ublock-quick-fixes: 249-55, now
  ublock-unbreak: 2125-35, now
  urlhaus-1: 5694-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 14 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 430 ms (selfie)
 maxAssetCacheWait: 128 ms
popupPanel:
 blocked: 7
 network:
  cloudflareinsights.com: 1
  d31qbv1cthcecs.cloudfront.net: 1
  doubleclick.net: 1
  ebxcdn.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##ins.adsbygoogle
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
report here: https://github.com/AdguardTeam/AdguardFilters/issues
