### ISSUE TITLE
tabs.ultimate-guitar.com: ads

### ISSUE THREAD

**Issue by SatchQ** [uBlockOrigin/uAssets#19611]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tabs.ultimate-guitar.com/tab/pink-floyd/money-bass-57984`

### Category

ads

### Description

Full height banner ads are displayed in iframes in the left and right columns. They can be temporarily hidden via right click -> block this element, or Ublock Origin button -> element zapper, but they return when the page is refreshed.

Have tried several custom filters but none of them seem to rectify the issue.

```
tabs.ultimate-guitar.com##iframe
tabs.ultimate-guitar.com##.js-global-wrapper.js-page iframe
$important,frame,domain=www.ultimate-guitar.com|ultimate-guitar.com|tabs.ultimate-guitar.com
||www.ultimate-guitar.com/send?*
||ultimate-guitar.com/send?*
||tabs.ultimate-guitar.com/send?*
tabs.ultimate-guitar.com##body iframe
```

I wonder if there's some kind of delay in the rendering of the banners which means that Ublock has already finished evaluating before the banners appear? No idea if that's possible 🤷‍♂️

### Other extensions used

Decentraleyes, HTTPS Everywhere, Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1596" alt="elixir" src="https://github.com/uBlockOrigin/uAssets/assets/96746431/aa8dfa06-bb5f-4d9d-872f-949d30fa9689">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98663
 cosmetic: 39988
 scriptlet: 18344
 html: 1028
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/fb_annoyances_newsfeed.txt: 26-0, never
 default:
  user-filters: 602-17, never
  ublock-filters: 35415-174, now
  ublock-badware: 7948-1, now
  ublock-privacy: 570-0, now
  ublock-unbreak: 2173-1, now
  easylist: 70063-577, now
  easyprivacy: 33245-760, now
  plowe-0: 3725-1, now
  urlhaus-1: 5694-0, now
  ublock-quick-fixes: 245-0, now
filterset (user): [array of 602 redacted]
trustedset:
 added: [array of 23 redacted]
 removed:
  about-scheme
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 120
 autoUpdatePeriod: 7
supportStats:
 allReadyAfter: 752 ms (selfie)
 maxAssetCacheWait: 506 ms
popupPanel:
 blocked: 8
 network:
  ultimate-guitar.com: 5
  googletagmanager.com: 1
  yandex.com: 2
 extended:
  ##button:has-text(/autoscroll/i):nth-ancestor(4)
  ##span:has-text(/made by UG professional guitarists/):nth-ancest…
  ##section > :has(header:has-text(/Shots/i))
```
</details>

**Comment by mapx-** [comment]
add
`ultimate-guitar.com##[href^="https://www.ultimate-guitar.com/send?ug_from=redirect"]`

(us ip)
@ryanbr

**Comment by SatchQ** [comment]
> add `ultimate-guitar.com##[href^="https://www.ultimate-guitar.com/send?ug_from=redirect"]`
> 
> (us ip) @ryanbr

Thanks for the suggestion but that doesn't seem to work either 🤔

**Comment by mapx-** [comment]
You have a lot of user filters.
Disable `user-filters` and test again

**Comment by BellaBytes10** [comment]
There are still ads, and the website detects uBlock

**Comment by mapx-** [comment]
- provide all the details (uBO / uBOL, browser), screenshot indicating the ads, how to trigger the detection
- did you test using only the default settings / filter lists ?

**Comment by BellaBytes10** [comment]
It's uBO, and yes I tested it with default settings

![Image](https://github.com/user-attachments/assets/31106054-257f-4e0c-9828-a77b601b3bd8)

**Comment by mapx-** [comment]
the ad is a self-promotion one which we do not block.
still no detection.
