### ISSUE TITLE
watchcartoonsonline.me [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1961]
URL(s) where the issue occurs

`https://watchcartoonsonline.me/Cartoon/The-Powerpuff-Girls-2016-Season-2.35692/Episode-040-Deb-ONair?id=79008`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`watchcartoonsonline.me##script:inject(set-constant.js,check_adblock,true)`

**Comment by ghajini** [comment]
pop ads
`https://watchcartoonsonline.la/how-the-toys-saved-christmas-1996/`
