### ISSUE TITLE
1412.live: detection

### ISSUE THREAD

**Issue by pololoduck** [uBlockOrigin/uAssets#19620]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://1412.live/ff/37365873`

### Category

detection

### Description

There is a popup that appears on the page when adblock is detected and prevents viewing the content.

### Other extensions used

google translate, enable right click, go back with backspace, marvellous tab suspender

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
https://github.com/uBlockOrigin/uAssets/assets/121998563/cc677521-7dd9-425c-b3a4-26fd7b98fc6f

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 144790
 cosmetic: 101518
 scriptlet: 33536
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 24871-137, 3m
  FIN-0: 2196-0, 3m
  JPN-1: 13346-12, 3m
  KOR-1: 4519-12, 3m
  adguard-generic: 73600-513, 3m
  dpollock-0: 11552-54, 3m
 default:
  user-filters: 9-1, never
  easylist: 70090-1334, 3m
  easyprivacy: 33245-299, 3m
  plowe-0: 3725-1468, 3m
  ublock-badware: 7954-374, 3m
  ublock-filters: 34541-3824, 3m
  ublock-privacy: 538-8, 3m
  ublock-quick-fixes: 249-55, 3m
  ublock-unbreak: 2125-100, 3m
  urlhaus-1: 5791-0, 3m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 432 ms (selfie)
 maxAssetCacheWait: 289 ms
popupPanel:
 blocked: 0
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by piquark6046** [comment]
I will handle this issue.

**Comment by piquark6046** [comment]
The website redirects a visitor to `bera.world`.
