### ISSUE TITLE
concoursultimesousmaringourmiam.ca: breakage

### ISSUE THREAD

**Issue by ravertine** [uBlockOrigin/uAssets#19622]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://concoursultimesousmaringourmiam.ca/`

### Category

breakage

### Description

main contest form is blocked when ublock is active

### Other extensions used

Canadian English Dictionary	dictionary	3.1.3	true	en-CA@dictionaries.addons.mozilla.org
Add-ons Search Detection	extension	2.0.0	true	addons-search-detection@mozilla.com
Amazon.co.uk	extension	1.12	true	amazon@search.mozilla.org
Bing	extension	1.6	true	bing@search.mozilla.org
DuckDuckGo	extension	1.4	true	ddg@search.mozilla.org
eBay	extension	1.4	true	ebay@search.mozilla.org
Gestionnaire de mots de passe RoboForm	extension	9.5.1.0	true	rf-firefox@siber.com
Google	extension	1.4	true	google@search.mozilla.org
Honey	extension	12.8.4	true	jid1-93CWPmRbVPjRQA@jetpack
hotfix-update-xpi-intermediate	extension	1.0.6	true	hotfix-update-xpi-intermediate@mozilla.com
Qwant	extension	1.4	true	qwant@search.mozilla.org
Reddit Enhancement Suite	extension	5.22.17	true	jid1-xUfzOsOFlzSOXg@jetpack
Remove Cookies Button	extension	1.7.1	true	{8a3715dc-7333-46d9-a133-a378fa5625bd}
Return YouTube Dislike	extension	3.0.0.10	true	{762f9885-5a13-4abd-9c77-433dcd38b8fd}
SponsorBlock pour YouTube - Supprime les publicités intégrées	extension	5.4.17	true	sponsorBlocker@ajay.app
uBlock Origin	extension	1.51.1.103	true	uBlock0@raymondhill.net
Unofficial The Great Suspender	extension	6.21	true	{6c3cb285-48cf-43e2-878f-adf577bb4de2}
Wikipédia (fr)	extension	1.3	true	wikipedia@search.mozilla.org
YesScript2	extension	4.3	true	yesscript202@example.org
Space Fantasy Redux	theme	4.0	true	{f5453979-a039-4066-8aee-cb64fc98f936}
MEGA	extension	4.2.1	false	firefox@mega.co.nz
Panorama View	extension	0.9.7	false	{60e27487-c779-464c-8698-ad481b718d5f}
Tampermonkey	extension	4.19.0	false	firefox@tampermonkey.net
YouTube Speed Controller	extension	1.3	false	{1ab2bf16-a321-4512-8690-924989617ac4}
Clair	theme	1.2	false	firefox-compact-light@mozilla.org
Firefox Alpenglow	theme	1.4	false	firefox-alpenglow@mozilla.org
Google Chrome Light	theme	3.0	false	{1fd1213e-dcb2-48d9-806f-c0a8a7d0a8e7}
Sombre	theme	1.2	false	firefox-compact-dark@mozilla.org
Thème système — auto	theme	1.3	false	default-theme@mozilla.org

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1rc3
Firefox: 117
filterset (summary):
 network: 118531
 cosmetic: 63679
 scriptlet: 24057
 html: 1216
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
  ublock-annoyances: 5407-8, now
  ublock-quick-fixes: 291-0, 1h.54m
  adguard-other-annoyances: 13342-104, now
  easylist-annoyances: 3957-33, now
 default:
  user-filters: 29-0, never
  ublock-filters: 35427-469, now
  ublock-badware: 7956-1, now
  ublock-privacy: 570-0, now
  ublock-unbreak: 2177-1, now
  easylist: 70099-788, now
  easyprivacy: 33245-729, now
  urlhaus-1: 5791-0, now
  plowe-0: 3725-1, now
  FRA-0: 28165-346, now
filterset (user): [array of 29 redacted]
trustedset:
 added: [array of 321 redacted]
switchRuleset:
 added: [array of 26 redacted]
hostRuleset:
 added: [array of 17 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 180
 autoUpdatePeriod: 4
 extensionUpdateForceReload: true
 manualUpdateAssetFetchPeriod: 1
 popupPanelLockedSections: 39
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 501 ms (selfie)
 maxAssetCacheWait: 92 ms
popupPanel:
 blocked: 6
 network:
  activehosted.com: 4
  app-us1.com: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||mikesca.activehosted.com/f/embed.php$script,domain=concoursultimesousmaringourmiam.ca`

@Alex-302 @ryanbr
