### ISSUE TITLE
mealboxomaha.com: breakage

### ISSUE THREAD

**Issue by midnightcomm** [uBlockOrigin/uAssets#19621]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mealboxomaha.com/menu-2/`

### Category

breakage

### Description

Just sits there

### Other extensions used

Decentraleyes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 117
filterset (summary):
 network: 100067
 cosmetic: 30635
 scriptlet: 18406
 html: 1029
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35730-338, now
  ublock-badware: 7950-1, now
  ublock-privacy: 570-1, now
  ublock-unbreak: 2182-2, now
  ublock-quick-fixes: 249-0, now
  adguard-mobile: 8617-123, now
  easylist: 70099-16676, now
  easyprivacy: 33245-726, now
  urlhaus-1: 5791-0, now
  plowe-0: 3725-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3138 ms (selfie)
 maxAssetCacheWait: 138 ms
popupPanel:
 blocked: 6
 network:
  wp.com: 6
```
</details>

**Comment by midnightcomm** [comment]
![Screenshot_20230905-220030](https://github.com/uBlockOrigin/uAssets/assets/5687236/3c2ad8c8-e447-4ea7-96ef-46f32841930a)

**Comment by mapx-** [comment]
it seems to be a site issue => FF desktop => ctrl-F5 => page partially loaded => F5 => ok

No such issue in chrome
