### ISSUE TITLE
understat.com: breakage

### ISSUE THREAD

**Issue by CennoxX** [uBlockOrigin/uAssets#19627]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://understat.com/league/Bundesliga`

### Category

breakage

### Description

The tables of the page are not shown, if I remove "uBlock filters – Ads" I see them again.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 101302
 cosmetic: 44479
 scriptlet: 18910
 html: 1028
listset (total-discarded, last-updated):
 added:
 default:
  user-filters: 24-0, never
  ublock-filters: 35418-99, now
  ublock-badware: 7956-1, now
  ublock-privacy: 570-0, now
  ublock-unbreak: 2177-1, now
  ublock-quick-fixes: 256-0, now
  easylist: 70218-712, now
  easyprivacy: 33233-728, now
  urlhaus-1: 5791-0, now
  plowe-0: 3725-1, now
  DEU-0: 7068-3, now
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 398 ms (selfie)
 maxAssetCacheWait: 124 ms
popupPanel:
 blocked: 4
 network:
  understat.com: 2
  google-analytics.com: 1
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
add

`@@||understat.com/js/jquery.iframetracker.min.js$script,1p`

@ryanbr

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
understat.com##+js(set, Object.prototype.iframeTracker, noopFunc)
```

**Comment by ryanbr** [comment]
Was a recent filter, easier to remove than create new exceptions or filter specifics tbh
