### ISSUE TITLE
tb.no: breakage

### ISSUE THREAD

**Issue by master3395** [uBlockOrigin/uAssets#19626]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tb.no/reagerer-pa-rakjoring-pa-e18-etter-ulykke-tenker-kun-pa-seg-selv/s/5-76-2149600`

### Category

breakage

### Description

Video view does not load while uBlock is activated.
Even if I try and whitelist the video player
"cdn.flowplayer.com"

### Other extensions used

Google Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

When uBlock is active:
![bilde](https://github.com/uBlockOrigin/uAssets/assets/4199669/66b9b406-2df7-4cb5-aba1-fd62e6e82bc3)

When uBlock is deactivated:
![bilde](https://github.com/uBlockOrigin/uAssets/assets/4199669/f5ae3577-88b6-4f7d-a639-495e52a06d13)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 100174
 cosmetic: 41552
 scriptlet: 18380
 html: 1029
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35419-87, now
  ublock-badware: 7956-1, now
  ublock-privacy: 570-0, now
  ublock-unbreak: 2177-1, now
  ublock-quick-fixes: 249-0, now
  easylist: 70196-707, now
  easyprivacy: 33233-718, now
  urlhaus-1: 5791-0, now
  plowe-0: 3725-1, now
  NOR-0: 3489-3, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2452 ms (selfie)
 maxAssetCacheWait: 848 ms
popupPanel:
 blocked: 8
 network:
  api.no: 4
  brandmetrics.com: 1
  doubleclick.net: 1
  imasdk.googleapis.com: 2
 extended:
  ##.am-bazaar-ad
  ##.skyscraper-ads-container:not(html,body)
  ##bazaar-ad
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by FanOfRootBeer** [comment]
@DandelionSprout Do you have a subscription / account?

**Comment by mapx-** [comment]
@DandelionSprout

**Comment by master3395** [comment]
Not sure what could cause it.

1. i sometimes deactivate uBlock, then refresh the page, then re-activate uBlock, then refresh the page.
Then it works fine when uBlock is active for a while.
2. I deactivated "My filters", all it had was "outlook.com" ad xD
3. I have no other content blocker, uBlock takes it all :)

**Comment by FanOfRootBeer** [comment]
Maybe give it like 5-10 seconds

**Comment by okiehsch** [comment]
It works with the regional list enabled.
If I disable the regional list the video does not play because of a paywall.
I assume you are a subscriber, does the video play if you disable the regionals `DandelionSprout's Nordic list`?

**Comment by master3395** [comment]
I can check.
I am a subscriber.
But the problem is, if I disable uBlock, and re-enable it, it won't block the video for a while, on any videos on the site.

**Comment by stephenhawk8054** [comment]
> does the video play if you disable the regional `DandelionSprout's Nordic list`

**Comment by master3395** [comment]
> > does the video play if you disable the regional `DandelionSprout's Nordic list`

It does not show up even if it's disabled.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by DandelionSprout** [comment]
I caught COVID a couple days ago and feel at considerably worse health than usual, and need somewhere between 3hrs and 3 days to assist the situation. However, I don't *think* I'm a TB+ subscriber either way.

**Comment by FanOfRootBeer** [comment]
reproduced by:
1. Visiting the page without DandelionSprout's Nordic list
2. Enabling the list
3. Refreshing the page
However upon refresh, it worked


@master3395 
=> does adding `||imasdk.googleapis.com/js/sdkloader/ima3.js$redirect-rule=google-ima.js,domain=tb.no` fix it?
if not => does adding (and removing the previous rule) => `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=tb.no` fix it ?

**Comment by DandelionSprout** [comment]
My stamina improved sharply overnight to the point I could look relatively quickly into this case, found a free-of-charge video at `https://www.tb.no/svomte-over-lagen-etter-ulykke-ble-til-slutt-blast-over-ende-av-politiet-som-a-vare-i-en-film/s/5-36-1239572`, but could not spot any breakage in Chrome.

I suspected `||s.api.no/mittari/c/article/*/sectionid/*.gif^` in Nordic Filters could be a problem, but I debunked that thought after a minute.

**Comment by master3395** [comment]
> reproduced by:
> 
>     1. Visiting the page without DandelionSprout's Nordic list
> 
>     2. Enabling the list
> 
>     3. Refreshing the page
> 
> 
> However upon refresh, it worked
> 
> @master3395 => does adding `||imasdk.googleapis.com/js/sdkloader/ima3.js$redirect-rule=google-ima.js,domain=tb.no` fix it? if not => does adding (and removing the previous rule) => `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=tb.no` fix it ?
> 
> Could you also try disabling Firefox's Tracking Protection? (Shield near address bar) / any difference with it disable along with uBO disabled/enabled?

I added it here and refreshed the page.
Then the video showed up.
![bilde](https://github.com/uBlockOrigin/uAssets/assets/4199669/b1448596-cb57-4c54-a768-486a977dded0)
![bilde](https://github.com/uBlockOrigin/uAssets/assets/4199669/474f8b08-c3f0-427e-9bbe-21249620b018)
