### ISSUE TITLE
reuters.com: detection

### ISSUE THREAD

**Issue by IlyaFirsov** [uBlockOrigin/uAssets#19625]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reuters.com/`

### Category

detection

### Description

Site detects UBO and shows warning

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/26841983/af6949ed-5361-476b-8678-05c7a4d37e33)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 77016
 cosmetic: 70119
 scriptlet: 23643
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  plowe-0: null
  ublock-privacy: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1645-0, 13h.11m
  POL-0: 7991-11, 13h.12m
  POL-2: 1276-13, 1d.15h.3m
  ublock-annoyances: 5451-14, 1d.15h.5m
  ublock-quick-fixes: 249-47, 11h.10m
 default:
  user-filters: 339-4, never
  RUS-0: 39884-23, 1d.15h.2m
  easylist: 69983-61, 1d.15h.4m
  ublock-badware: 7905-145, 23h.15m
  ublock-filters: 34538-200, 21h.13m
  ublock-unbreak: 2122-20, 23h.16m
filterset (user): [array of 342 redacted]
trustedset:
 added: [array of 56 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 20 redacted]
hostRuleset:
 added: [array of 5 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 prefetchingDisabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 647 ms (selfie)
 maxAssetCacheWait: 269 ms
popupPanel:
 blocked: 25
 network:
  abtasty.com: 2
  ads-twitter.com: 1
  adsafeprotected.com: 4
  advertising.com: 1
  chartbeat.com: 2
  doubleclick.net: 2
  eloqua.com: 2
  facebook.net: 1
  go-mpulse.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
  jwpcdn.com: 1
  permutive.com: 1
  pub.network: 1
  scorecardresearch.com: 1
  wsod.com: 1
 extended:
  ##[data-testid="ResponsiveAdSlot"]
  ##div[class^="ad-slot__"]
```
</details>

**Comment by FanOfRootBeer** [comment]
not encountered on my side

@IlyaFirsov Does adding `reuters.com##+js(acs, document.createElement, admiral)` to "My filters" work?

**Comment by mapx-** [comment]
@IlyaFirsov 

> easyprivacy: null
> plowe-0: null
> ublock-privacy: null
> 

don't touch the default lists (re-enable them)
