### ISSUE TITLE
newscon.org: detection

### ISSUE THREAD

**Issue by Hazuki-san** [uBlockOrigin/uAssets#19634]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Script was updated to prevent adblockers. The anti-adblock activates after 3~6 seconds.

### URL(s) where the issue occurs.

`https://www.newscon.org/download/`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/27200811/c2ba8113-e3c9-46eb-b199-9fedb9b14274)

### uBO version

1.51.0

### Browser name and version

Microsoft Edge Version 116.0.1938.69 (Official build) (64-bit)

### Settings

default/stock settings, didn't do any changes.

**Comment by FanOfRootBeer** [comment]
please update your lists

**Comment by Hazuki-san** [comment]
okay, that solves it. somehow i thought i updated quite sometime ago.

**Comment by FanOfRootBeer** [comment]
there was an update for this site 3 days ago
