### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by ChimChamp** [uBlockOrigin/uAssets#19643]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

ads

### Description

ads on youtube homepage are visually getting blocked but they are embedded as youtube videos which still autoplay with sound

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98812
 cosmetic: 39526
 scriptlet: 18407
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 268-61, now
 default:
  user-filters: 10-0, never
  easylist: 70284-10, now
  easyprivacy: 33220-63, now
  plowe-0: 3725-1067, now
  ublock-badware: 7954-146, now
  ublock-filters: 34513-127, now
  ublock-privacy: 538-6, now
  ublock-unbreak: 2129-32, now
  urlhaus-1: 5767-0, now
filterset (user): [array of 10 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 339 ms (selfie)
 maxAssetCacheWait: 161 ms
popupPanel:
 blocked: 14
 network:
  youtube.com: 5
  google.com: 9
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

Reproduce the issue > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it to the above thread.
