### ISSUE TITLE
fbdown.net

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1964]
### URL(s) where the issue occurs

`https://www.fbdown.net/down.php`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/38770862-5466b074-3fe7-11e8-8bd9-812bfbc6c881.png)

### Notes

Here's an example link you can use:
`https://www.facebook.com/d10e.events/videos/1055356931296519/`

**Comment by zaphodbeebblebrox** [comment]
`fbdown.net##script:inject(set-constant.js,harshblock,false)`

**Comment by terrorist96** [comment]
Still getting that warning.
![image](https://user-images.githubusercontent.com/12802056/38771925-cafcbb54-3ff9-11e8-9ffe-66abaeb5392f.png)

**Comment by mapx-** [comment]
try
`@@||fbdown.net^$script,first-party`

**Comment by terrorist96** [comment]
That seems to work.

**Comment by terrorist96** [comment]
Ugh, now I can't get it to appear without that filter. But I caught this in one of the page refreshes:
![image](https://user-images.githubusercontent.com/12802056/38772155-3f03cf02-3ffe-11e8-9306-a8a718430396.png)

**Comment by okiehsch** [comment]
You have to bypass the cache to make it "appear" again.
`fbdown.net##script:inject(set-constant.js, harshblock, false)`
works consistently on my end.
An alternative would be
````
fbdown.net##script:inject(abort-current-inline-script.js, document.getElementById, harshblock)
fbdown.net###harshblock
````
