### ISSUE TITLE
biopills.net: detection

### ISSUE THREAD

**Issue by llol09** [uBlockOrigin/uAssets#19646]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

UbO get's immediately spotted on BioPills.net

### URL(s) where the issue occurs.

`https://www.biopills.net/`

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/35606338/95efc857-a2b2-4b6c-8b18-c1e48e5c0206)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98370
 cosmetic: 39514
 scriptlet: 18338
 html: 1028
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35397-73, 3d.19h
  ublock-badware: 7798-0, 3d.19h
  ublock-privacy: 570-0, 3d.3h.19m
  ublock-unbreak: 2170-0, 3d.19h
  ublock-quick-fixes: 268-0, 1h.58m
  easylist: 69996-708, 2d.3h.12m
  easyprivacy: 33211-717, now
  urlhaus-1: 5767-0, 1h.58m
  plowe-0: 3726-2, 6d.19h.29m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 295 ms (selfie)
 maxAssetCacheWait: 81 ms
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
