### ISSUE TITLE
colamanga.com: detection

### ISSUE THREAD

**Issue by Kaiko77456** [uBlockOrigin/uAssets#19649]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.colamanga.com/manga-um87515/`

### Category

detection

### Description

The previewer blocks the display of important components

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox Mobile: 117
filterset (summary):
 network: 114176
 cosmetic: 39758
 scriptlet: 18576
 html: 1029
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35730-344, 2m
  ublock-badware: 7942-1, 2m
  ublock-privacy: 577-1, 2m
  ublock-unbreak: 2182-1, 2m
  ublock-quick-fixes: 254-0, 2m
  adguard-mobile: 8618-124, 3m
  easylist: 70056-16726, 2m
  easyprivacy: 33217-739, 2m
  urlhaus-1: 5761-0, 2m
  plowe-0: 3725-1, 2m
  CHN-0: 24888-1320, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1191 ms
 maxAssetCacheWait: 276 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
- detection ? provide screenshot

> The previewer blocks the display of important components

provide all the details on what previewer, what components, steps to reproduce the issue

**Comment by stephenhawk8054** [comment]
Fixed in regional list already: https://github.com/AdguardTeam/AdguardFilters/commit/f7d6d0907d898baadc0b816463f502fbcf75dcee
