### ISSUE TITLE
animeshouse.net: breakage

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#19641]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animeshouse.net/episodio/undead-murder-farce-s1-episodio-10-legendado-hd/`

### Category

breakage

### Description

When you click in the video player, the new tab closes immediately, but it goes to the video player

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/f0e6d050-7955-4dc7-ad16-b4d7b819ee22)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 233213
 cosmetic: 226251
 scriptlet: 44827
 html: 0
listset (total-discarded, last-updated):
 added:
  https://github.com/AdroitAdorKhan/antipopads-re/raw/master/formats/filter.txt: 89984-0, 4m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 982-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2261-0, now
  adguard-cookies: 27492-30, now
  adguard-generic: 73608-967, now
  adguard-mobile-app-banners: 4597-9, now
  adguard-other-annoyances: 13347-7, now
  adguard-popup-overlays: 23789-89, now
  adguard-social: 21361-909, now
  adguard-spyware: 55948-1342, now
  adguard-spyware-url: 1199-145, now
  adguard-widgets: 2300-6, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 106-0, never
  easylist: 70284-25932, now
  easyprivacy: 33220-16804, now
  plowe-0: 3725-1207, now
  spa-1: 5564-80, now
  ublock-badware: 7954-389, now
  ublock-filters: 34513-4289, now
  ublock-privacy: 538-138, now
  ublock-quick-fixes: 268-61, now
  ublock-unbreak: 2129-149, now
  urlhaus-1: 5767-0, now
filterset (user): [array of 62 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 6152 ms (selfie)
 maxAssetCacheWait: 451 ms
popupPanel:
 blocked: 5
 network:
  disqus.com: 3
  inklinkor.com: 1
  privacymanager.io: 1
 extended:
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
  ##+js(abort-current-script, document.addEventListener, /;return …
  ##+js(addEventListener-defuser, /^(contextmenu|keydown)$/)
  ##+js(abort-on-property-read, thumbad)
  ###placement-top
  ###thread-share-bar
  ##.comment__share
  ###email-signup
  ##.share-icons-wrapper
```
</details>

**Comment by mapx-** [comment]
add

```
/^https?:\/\/[a-z]{7,16}\.org\/(?=[\/a-zA-Z]*[+0-9])(?=[+\/0-9a-z]*[A-Z])[+\/0-9a-zA-Z]{400,}$/$popup,3p,match-case,from=~edu|~gov,badfilter
/^https?:\/\/[a-z]{7,16}\.org\/(?=[\/a-zA-Z]*[+0-9])(?=[+\/0-9a-z]*[A-Z])[+\/0-9a-zA-Z]{400,}$/$popup,3p,match-case,from=~edu|~gov|~animeshouse.net
```

**Comment by mapx-** [comment]
@Yuki2718

**Comment by D4niloMR** [comment]
embed player only loads with adblock off, it only have to load once, its not cookie from what I can see, any fix?

**Comment by mapx-** [comment]
Are you talking about the player in the new tab ?

Even disabling uBO I get:
`realme-ah.shop refused to connect.`

**Comment by D4niloMR** [comment]
yes, maybe it has geo restrictions, in my loads normally with uBO disabled


<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/f9214a96-c5ec-4c55-9644-6b1c3a737627)

</details>

**Comment by mapx-** [comment]
I don't understand this:

> embed player only loads with adblock off

I get this page (using a brazilian ip) in a new tab:

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/b4757ca7-af67-47bc-87ea-0095f5f8231e)

**Comment by D4niloMR** [comment]
> embed player only loads with adblock off

Sorry, I didn't see I misspelled, you have to turn off uBO, ads load and after that you can re-enable yet it still load the embed



> I get this page (using a brazilian ip) in a new tab:

Strange, for me it loads

**Comment by mapx-** [comment]
if you do not turn OFF uBO what to you get in the new page ? screenshot ?

**Comment by D4niloMR** [comment]
I had to reload the browser to get this:
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/7e1f0ae4-7c65-402f-a7ac-4ee6a8d2840a)
i

**Comment by mapx-** [comment]
No such issue on my end, use only the default lists, no other extension enabled

**Comment by D4niloMR** [comment]
i'm using a new profile with default ubo, if it's too time consuming I can give you my anydesk or whatever that can help

**Comment by D4niloMR** [comment]
I think this fix(idk why, but worked):
```adb
@@||edifier-ah.shop/_banner_ads.js$script,domain=realme-ah.shop
```

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/286af1ed-0973-4096-afc2-d14493812e25)

**Comment by mapx-** [comment]
disable that filter, try this 1:
`||edifier-ah.shop^$script,domain=realme-ah.shop,redirect-rule=noopjs`

**Comment by D4niloMR** [comment]
Thank you!!

**Comment by ghajini** [comment]
which ip is required to see the video? as i see only " refused to connect"

**Comment by D4niloMR** [comment]
> which ip is required to see the video? as i see only " refused to connect"

Brazil

`https://animeshouse.net/episodio/ousama-ranking-episodio-1-legendado-hd/`

other video player:
```adb
@@||edifier-ah.shop/_banner_ads.js$script,domain=clp-new.reign-ah.online
```

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/9fe3676c-baff-4fd3-aa47-703492e4b5fb)

**Comment by stephenhawk8054** [comment]
@D4niloMR Does this work?

```adb
@@||edifier-ah.shop/*.js|$script,domain=animeshouse.net|feralhosting.com
```

**Comment by D4niloMR** [comment]
> @D4niloMR Does this work?

No

**Comment by stephenhawk8054** [comment]
@D4niloMR Can you check the logger to see which domain it is used for that?

**Comment by D4niloMR** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/aa24b943-1e8b-477c-9509-00107f542a84)

**Comment by stephenhawk8054** [comment]
@D4niloMR I have edited the filter, can you test that one?

**Comment by D4niloMR** [comment]
Worked, but in `https://animeshouse.net/episodio/undead-murder-farce-s1-episodio-10-legendado-hd/` is only `reign-ah.online`
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/3361fce7-6a5e-4052-a554-35edd8a06675)

**Comment by D4niloMR** [comment]
Broked again
```adb
@@||-ah.shop/*.js$script,domain=reign-ah.online
```
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/fba17c38-25d0-446f-8f67-0e9879fdfd24)

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/7bdd28fd-90fb-4822-8925-dc00797bc392)

**Comment by D4niloMR** [comment]
`@@*/_banner_ads.js$script,domain=reign-ah.online`

add this too, soon they will be using that

**Comment by D4niloMR** [comment]
https://github.com/uBlockOrigin/uAssets/assets/70459964/167f45f5-f54b-4fc2-a725-14d751d70d8b


suggestion:

> ```
> @@||-ah.shop/*.js$script,domain=reign-ah.online
> ```

**Comment by D4niloMR** [comment]
`https://animeshouse.net/episodio/toaru-ossan-no-vrmmo-katsudouki-s1-episodio-7-legendado-hd/`

Broken again
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/da4d78a6-3dff-47da-a6bc-9342e1b94d67)

`@@||-ah.shop/*.js$script,domain=reign-ah.online|corsair-ah.shop`

or

`@@||logitech-ah.shop/*.js$script`

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/commit/e29e34d4983daa104fafd096cda3efc6cef17ce0

**Comment by D4niloMR** [comment]
`https://animeshouse.net/episodio/mf-ghost-s1-episodio-8-legendado-hd/`

Not working again.
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/2e567537-af94-4428-bd72-ef32dd3a0dec)

`@@/*.js$script,3p,domain=reign-ah.online|corsair-ah.shop`

This may keep it working for a good time...
