### ISSUE TITLE
revistaempleo.com: detection

### ISSUE THREAD

**Issue by bmEXR** [uBlockOrigin/uAssets#19657]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://revistaempleo.com/`

### Category

detection

### Description

"Adblock detected" in Spanish

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 316575
 cosmetic: 221116
 scriptlet: 44312
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27511-30, now
  adguard-generic: 73506-467, now
  adguard-mobile: 8622-43, now
  adguard-mobile-app-banners: 4599-9, now
  adguard-other-annoyances: 13353-8, now
  adguard-popup-overlays: 23803-69, now
  adguard-social: 21378-910, now
  adguard-spyware: 55931-1342, now
  adguard-spyware-url: 1203-3, now
  adguard-widgets: 2301-6, now
  block-lan: 48-0, now
  curben-phishing: 137847-22, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 70314-1391, now
  easyprivacy: 33219-16760, now
  plowe-0: 3725-1568, now
  ublock-badware: 7955-383, now
  ublock-filters: 34540-4271, now
  ublock-privacy: 545-130, now
  ublock-quick-fixes: 254-62, 1h.54m
  ublock-unbreak: 2129-151, now
  urlhaus-1: 5761-2, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2026 ms (selfie)
 maxAssetCacheWait: 1422 ms
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  latinon.com: 1
  vidoomy.com: 1
 extended:
  ##[data-revive-zoneid]
```
</details>

**Comment by FanOfRootBeer** [comment]
- go to `chrome://extensions/` => any other ad / tracker blocker?
- are you using a ad blocking DNS Server?
