### ISSUE TITLE
animexhd.com: breakage

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#19658]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animexhd.com/14025/`

### Category

breakage

### Description

When you click in the redirect, the new tab closes immediately, but it goes to the video player

This filter causes it:
`/^https?:\/\/[a-z]{7,16}\.xyz\/[+\/0-9a-zA-Z]{400,}$/$frame,popup,3p,match-case`

it's possible to use `nano-stb` ?
<details>
<summary>Screenshot</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/cd81fa04-f4ae-44b3-8a41-d6d10a06bce5)

</details>

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/794c8230-7fa1-4589-894b-54d9303e5fe3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 233413
 cosmetic: 226181
 scriptlet: 44867
 html: 0
listset (total-discarded, last-updated):
 added:
  https://github.com/AdroitAdorKhan/antipopads-re/raw/master/formats/filter.txt: 90132-0, now
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 983-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2261-0, now
  adguard-cookies: 27511-30, now
  adguard-generic: 73506-968, now
  adguard-mobile-app-banners: 4599-9, now
  adguard-other-annoyances: 13353-7, now
  adguard-popup-overlays: 23803-89, now
  adguard-social: 21378-909, now
  adguard-spyware: 55931-1342, now
  adguard-spyware-url: 1203-145, now
  adguard-widgets: 2301-6, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 105-0, never
  easylist: 70314-25950, now
  easyprivacy: 33219-16805, now
  plowe-0: 3725-1207, now
  spa-1: 5565-80, now
  ublock-badware: 7955-389, now
  ublock-filters: 34540-4295, now
  ublock-privacy: 545-141, now
  ublock-quick-fixes: 254-62, now
  ublock-unbreak: 2129-149, now
  urlhaus-1: 5824-0, now
filterset (user): [array of 61 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 6152 ms (selfie)
 maxAssetCacheWait: 451 ms
popupPanel:
 blocked: 17
 network:
  animexhd.com: 1
  a-ads.com: 2
  aj2550.bid: 1
  arc.io: 1
  chatbro.com: 1
  disqus.com: 3
  google-analytics.com: 1
  histats.com: 1
  onesignal.com: 1
  privacymanager.io: 1
  viglink.com: 2
  vimeocdn.com: 1
  waust.at: 1
 extended:
  ##iframe[src^="//ad.a-ads.com/"]
  ###placement-top
  ###thread-share-bar
  ###email-signup
  ##.share-icons-wrapper
  ##button[data-share-button]
  ##.share-icon
```
</details>

**Comment by mapx-** [comment]
@Yuki2718

**Comment by D4niloMR** [comment]
@mapx-  one question, I have some sites that require the cookies to be set to work, should I open an issue for each of them or open one but put them all together?

**Comment by mapx-** [comment]
> require the cookies to be set to work

maybe because you are using annoyances lists which remove those cookies ?

ok, open 1 issue with all these cases, explaining how to reproduce the issue - testing them only with default list and then adding the annoyanes lists

**Comment by D4niloMR** [comment]
> maybe because you are using annoyances lists which remove those cookies ?

I will try to be more consice when writing issues, I don't explain well.

no, this is not what I mean't, i have somes site that you need to `set-cookie` to `Ads, 2` or `visited, yes` (because this cookie make the video player load and they only create this cookie if the ads are displaying, if the owner desires)

So I asked if I should make one or several reports

**Comment by mapx-** [comment]
> open 1 issue with all these cases
