### ISSUE TITLE
freepornvideo.sex [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1965]
URL(s) where the issue occurs

`http://www.freepornvideo.sex/xxx/1089/limber-rubdown/?pqr=26:ca02e299655209f5097abfd1528e3e5b:0:1089:1:`

Describe the issue

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by KiLL4FuNK** [comment]
clone
`http://www.teenpornvideo.xxx/videos/5017/youthfull-maddy-s-very-first-gang-bang/`

**Comment by zaphodbeebblebrox** [comment]
```
||freepornvideo.sex/fpv.js$script,first-party
||teenpornvideo.xxx/tpv.js$script,first-party
freepornvideo.sex##.table
```
