### ISSUE TITLE
Fix for NSFW site

### ISSUE THREAD

**Issue by blankman99** [uBlockOrigin/uAssets#1966]
### URL(s) where the issue occurs

`https://www.porndish.com` (NSFW) 

### Describe the issue

Just a request to add `porndish.com##script:inject(bab-defuser.js)` to uBlock Filter List. I know generichide fixes this issue but I have it disabled because other sites have elements that I can't hide when I leave generichide alone (i.e. menshealth.com)

### Versions

- Browser/version: Version 65.0.3325.181 (Official Build) (64-bit)
- uBlock Origin version: 1.15.24

**Comment by mapx-** [comment]
`porndish` is already fixed, so you better explain your real issue with those `other sites`

**Comment by blankman99** [comment]
No need to get hostile, I am just trying to find a solution. `menshealth.com` seems to work fine...the other site that was an issue was `earnthenecklace.com`. Basically I am unable to remove the empty space that says "Advertisement" if `@@||earnthenecklace.com^$generichide` is active in Easy List. I have a similar problem with a few other sites. So I used a broad filter which was `$important,generichide` which works great with some exceptions. I just figured adding another filter would not be that problematic.

**Comment by SMed79** [comment]
> I am unable to remove the empty space that says "Advertisement" if @@||earnthenecklace.com^$generichide is active in Easy List.

You still can add a specific hide filter for e.g. `earnthenecklace.com##.etn-ad-text`
or the `badfilter` option in uBo https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter

**Comment by okiehsch** [comment]
You can use `*$generichide,important,domain=~porndish.com` to fix `porndish.com` while still using your broad filter.
You can use that filter and add the sites you have issues with
`*$generichide,important,domain=~porndish.com|~example.com|~example1.com`
