### ISSUE TITLE
streamingcommunity.bet: popups

### ISSUE THREAD

**Issue by X-onimous** [uBlockOrigin/uAssets#19665]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://streamingcommunity.bet/`

### Category

popups

### Description

When you open the page for the first time, it automatically opens the clicked object in a new a pop-up tab, and switches the current page you were into an ADs page. Fortunately this happens only twice ( at least to me ) when you visit the page for the first time. But it's very annoying.

I use uBlock Origin (updated to last version)+ Opera GX native adblock, and all the settings (both in Opera GX and uBlock Origin ) to block popups, I use that site everyday since years, and this is the first time that's happening. Can you help me? 

### Other extensions used

Privacy Badger, Google Translator, Dark Mode, enable right click 2.0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 102532
 cosmetic: 46472
 scriptlet: 18434
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ITA-0: 10540-17, now
  easylist: 70374-17, now
  easyprivacy: 33208-64, now
  plowe-0: 3723-1068, now
  ublock-badware: 7955-146, now
  ublock-filters: 34549-139, now
  ublock-privacy: 545-6, now
  ublock-quick-fixes: 263-65, now
  ublock-unbreak: 2129-32, now
  urlhaus-1: 5849-0, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2572 ms (selfie)
 maxAssetCacheWait: 474 ms
popupPanel:
 blocked: 1
 no-popups: true
 network:
  streamingcommunity.bet: 1
 extended:
  ##.banner
  ##.close-banner > svg > path
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by ghajini** [comment]
> I use uBlock Origin (updated to last version)+ Opera GX native adblock

Don't use 2 adblocking at same the time , this was source of your problem (https://twitter.com/gorhill/status/1033706103782170625)

Kindly disable opera native adblock if you want full experience of ublock origin capabilities

**Comment by X-onimous** [comment]
Ohh Thanks for responding so quickly! Privacy Badger could also be a problem for uBO?  I've  disabled it too, and the problem seems to no longer to occur.

Thank you again.

**Comment by ghajini** [comment]
yes any similar purposed adblocking/content blocking solutions

**Comment by X-onimous** [comment]
Awoook! Thank you very much!

**Comment by X-onimous** [comment]
LOL! you got me! I didn't read all that stuff sorry hahaha
