### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by NotSainrLunar** [uBlockOrigin/uAssets#19661]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

https://www.youtube.com/watch?v=jpw2ebhTSKs

### Category

detection

### Description

they patched adblocks lol

### Other extensions used

absolutely none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 114
filterset (summary):
 network: 98883
 cosmetic: 39524
 scriptlet: 18425
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 15-0, never
  easylist: 70314-10, 7m
  easyprivacy: 33209-63, 7m
  plowe-0: 3725-1067, 7m
  ublock-badware: 7955-146, 7m
  ublock-filters: 34515-127, 7m
  ublock-privacy: 545-6, 7m
  ublock-quick-fixes: 254-52, 7m
  ublock-unbreak: 2129-32, 7m
  urlhaus-1: 5824-0, 7m
filterset (user): [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1940 ms
 maxAssetCacheWait: 19 ms
popupPanel:
 blocked: 7
 network:
  youtube.com: 4
  doubleclick.net: 3
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

Please only continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

---

```yml
default:
  user-filters: 15-0, never
```

Remove all your custom filters and test again.
