### ISSUE TITLE
haberiniz.com.tr: ads

### ISSUE THREAD

**Issue by Yefusy** [uBlockOrigin/uAssets#19663]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://haberiniz.com.tr/`

### Category

ads

### Description

Two sticky banner ads.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98059187/27d0191d-e861-4616-9767-991572d05096)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 124489
 cosmetic: 166646
 scriptlet: 38781
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27512-30, now
  adguard-generic: 73525-478, now
  adguard-mobile-app-banners: 4600-9, now
  adguard-other-annoyances: 13360-7, now
  adguard-popup-overlays: 23808-71, now
  adguard-social: 21376-909, now
  adguard-widgets: 2301-3, now
  ublock-cookies-adguard: 281-4, now
 default:
  user-filters: 21-0, never
  TUR-0: 13607-10, now
  easylist: 70243-1081, now
  easyprivacy: 33210-233, now
  plowe-0: 3723-1080, now
  ublock-badware: 7955-363, now
  ublock-filters: 34549-4178, now
  ublock-privacy: 545-7, now
  ublock-quick-fixes: 254-59, 55m
  ublock-unbreak: 2129-95, now
  urlhaus-1: 5849-0, now
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1058 ms
 maxAssetCacheWait: 775 ms
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
add
`haberiniz.com.tr##.kanews-banner`

@Yuki2718 for turkish list

**Comment by Yuki2718** [comment]
But these banners are not clickable, what they're advertising? I see that they are annoying though.

**Comment by Yefusy** [comment]
A political party.

**Comment by Yuki2718** [comment]
Fixed in Annoyances lists but not in AdGuard Annoyances as per [AdGuard Filter Policy](https://adguard.com/en/blog/adguard-filter-policy.html) (too few visitors).
