### ISSUE TITLE
afly.pro: detection

### ISSUE THREAD

**Issue by ArgX11** [uBlockOrigin/uAssets#19660]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://afly.pro/`

### Category

detection

### Description

This website Detects uBlock. 
Here is an example URL `https://i.afly.pro/7cq6i`

### Other extensions used

Violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-09-08 092213](https://github.com/uBlockOrigin/uAssets/assets/22514844/25b5c268-cdd2-420f-b9bc-de76ff9ef34f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 340529
 cosmetic: 257675
 scriptlet: 45255
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 181-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=3: 0-0, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4827-115, now
  IND-0: 12556-0, now
  RUS-0: 39897-9, now
  adguard-cookies: 27511-42, now
  adguard-generic: 73506-668, now
  adguard-mobile: 8622-70, now
  adguard-mobile-app-banners: 4599-10, now
  adguard-other-annoyances: 13353-43, now
  adguard-popup-overlays: 23803-421, now
  adguard-social: 21378-917, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 70275-1414, now
  easyprivacy: 33209-16798, now
  plowe-0: 3725-1573, now
  ublock-badware: 7955-382, now
  ublock-filters: 34539-4267, now
  ublock-privacy: 545-131, now
  ublock-quick-fixes: 254-62, now
  ublock-unbreak: 2129-149, now
  urlhaus-1: 5824-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1051 ms (selfie)
 maxAssetCacheWait: 794 ms
popupPanel:
 blocked: 9
 network:
  adapex.io: 1
  adtcdn.com: 2
  doubleclick.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  greeter.me: 1
  modoro360.com: 1
 extended:
  ##.aplvideo
  ##.generate-back-to-top
  ###id-custom_banner
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  ##+js(nobab)
  ##+js(set-constant, app_vars.force_disable_adblock, undefined)
  ##+js(set-constant, blurred, false)
```
</details>

**Comment by dportvine** [comment]
Leftover

<details>
<summary>Screenshot(s)</summary>

![2023-09-08_093302](https://github.com/uBlockOrigin/uAssets/assets/111344219/cacf8d74-e959-4e08-9c09-1ddb7345272f)
</details>

**Comment by mapx-** [comment]
it's a trash page only for downloading

**Comment by ArgX11** [comment]
Yeah, it's indeed a junk page, one of the intermediate pages of a URL redirection. 

Thank you for fulfilling the request.

**Comment by BlazeFTL** [comment]
LeftOver & Timer Boost
```
afly.pro##center:others()
afly.pro##+js(nano-sib, /timer|timer2/, *, 0.02)
```
