### ISSUE TITLE
blog.pmsarkarijob.com: detection

### ISSUE THREAD

**Issue by HK-Srivastava** [uBlockOrigin/uAssets#19669]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.pmsarkarijob.com/?lid=TWo7H1n&pid=785543&plid=1&vid=198977338`

### Category

detection

### Description

site gets disabled on detecting ad block

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98988
 cosmetic: 39505
 scriptlet: 18431
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70376-10, now
  easyprivacy: 33208-63, now
  plowe-0: 3723-1067, now
  ublock-badware: 7955-146, now
  ublock-filters: 34541-129, now
  ublock-privacy: 545-6, now
  ublock-quick-fixes: 263-65, now
  ublock-unbreak: 2132-32, now
  urlhaus-1: 5849-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 279 ms (selfie)
 maxAssetCacheWait: 78 ms
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 2
```
</details>

**Comment by mapx-** [comment]
fixed today
