### ISSUE TITLE
clk.wiki: popups

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#19664]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://clk.wiki/UjJOzg?token=9ff3eab81da12bbe29ab1da805ba0b62668fdb29d2a47430fc6f1c4fdd671f21`

### Category

popups

### Description

open new window

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1rc5
Chromium Mobile: 110
filterset (summary):
 network: 106725
 cosmetic: 130967
 scriptlet: 26292
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27514-31, now
  adguard-mobile-app-banners: 4601-8, now
  adguard-other-annoyances: 13361-16, now
  adguard-popup-overlays: 23811-58, now
  adguard-social: 21377-912, now
  adguard-widgets: 2301-4, now
  ublock-annoyances: 5514-188, now
  ublock-cookies-adguard: 319-319, now
 default:
  user-filters: 7-1, never
  adguard-mobile: 8624-14, now
  easylist: 70374-119, now
  easyprivacy: 33208-137, now
  plowe-0: 3723-1143, now
  ublock-badware: 7949-147, now
  ublock-filters: 34869-622, now
  ublock-privacy: 545-7, now
  ublock-quick-fixes: 302-79, now
  ublock-unbreak: 2134-36, now
  urlhaus-1: 5849-0, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1940 ms
 maxAssetCacheWait: 656 ms
popupPanel:
 blocked: 3
 network:
  clk.wiki: 1
  go2speed.org: 1
  googletagmanager.com: 1
 extended:
  ##.banner-728x90
  ##.myTestAd
```
</details>

**Comment by Fatcavill** [comment]
[Screenshot_20230908-203018_Lemur Browser](https://github.com/uBlockOrigin/uAssets/assets/139833732/243bf13f-510f-4b0a-bb35-027b7912b8f7)
In this page

**Comment by ankarakata** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/131877079/cf794e9a-40ab-4edc-b3cd-554561ea37d6)
clk.wiki website still have delay time for reveal the link
