### ISSUE TITLE
filmize.tv: breakage

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#19670]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://filmize.tv/filmes/barbie`

### Category

breakage

### Description

Tested with uBO default + uBO Annoyances

I'll list here some websites that the video player needs a specific `cookie` to load, and the cookie is created when the ad load. 

Also on this list: `devtools detector`, `anti-rightclick`, `anti-adblock` and `timeout/interval-booster`.

`https://filmize.tv/filmes/barbie`
`https://guiacripto.online/assets/js/funcs.min.js?v=1.0.2`
```adb
guiacripto.online##+js(set-cookie, visited, yes)
guiacripto.online##+js(nano-stb, player, *, 0.02)
guiacripto.online##+js(set, adBlockDetected, false, 2)
```

### ---------------------------------------------------------------------------------------------------------

`https://filmesmega.co/abominavel-dublado/`
```adb
guiasaude.info##+js(set-cookie, Ads, 2)
guiasaude.info##+js(aeld, contextmenu)
guiasaude.info##+js(acs, document.onkeydown, preventDefault)
```

### ---------------------------------------------------------------------------------------------------------

`https://pobreflix.io/filmes-online-hd/john-wick-3-parabellum/`
```adb
cozinhandofitness.com#@##ads2
```

### ---------------------------------------------------------------------------------------------------------

`https://super-animes.net/serie/supernatural/episodio-1x1`
`https://playerflix.com/assets/js/js.js?ver=708327985`
```adb
1i1.in##+js(set-cookie, clicked_ads, 2)
1i1.in##+js(acs, disable_developer_mode)
playerflix.com##+js(nano-sib, myInterval, *, 0.02)
```

### ---------------------------------------------------------------------------------------------------------

`https://meusanimesbr.com/episodio/81942/`
```adb
financasdeouro.com##+js(set-cookie, visited, yes)
```

### ---------------------------------------------------------------------------------------------------------

`https://megaflix.co/filme/guardioes-da-galaxia-vol-3-2023-assistir-online-1692479237/`
`https://bolsadevalores.club/wp-content/plugins/taims/js/fake22.js`
```adb
bolsadevalores.club##+js(set-cookie, Ads, 2)
bolsadevalores.club##+js(nano-stb, document.link.submit, *, 0.02)
felizemforma.com##+js(set-cookie, Ads, 2)
felizemforma.com##+js(aeld, contextmenu)
felizemforma.com##+js(acs, document.onkeydown)
||mflix.vip/front/js/devtools-detector.js$script
```

### ---------------------------------------------------------------------------------------------------------

`https://filmesmp4.com/homem-aranha-atraves-do-aranhaverso-2023-720p-dublado/`
`https://sabornutritivo.com/assets/js/funcs.js`
```adb
sabornutritivo.com##+js(set-cookie, visited, yes)
sabornutritivo.com##+js(rmnt, script, hasAdblock)
~blog.sabornutritivo.com,sabornutritivo.com##+js(nano-stb, "", *, 0.02)
```

### ---------------------------------------------------------------------------------------------------------

`https://ondebaixar.org/b-o-1a-temporada-completa`
```adb
usandoapp.com##+js(set-cookie, LiberaFunctionAd, 1)
usandoapp.com##+js(nano-stb, atualizar, *, 0.02)
usandoapp.com##+js(rmnt, script, /adshow/ad)
fazercurriculo.online##+js(set-cookie, LiberaFunctionAd, 1)
fazercurriculo.online##+js(nano-stb, atualizar, *, 0.02)
fazercurriculo.online##+js(rmnt, script, /adshow/ad)
```

### ---------------------------------------------------------------------------------------------------------

`https://www.hidrafilmes.com/megatubarao-2-download-1/`
```adb
obaianinho.com##+js(nano-sib, atualizarCronometro, *, 0.02)
```

### ---------------------------------------------------------------------------------------------------------

(The redirect goes to the same site, site issue. even with uBO turned off it does the same thing)
`https://utorrentfilmes.com.br/transformers-o-despertar-das-feras/`
```adb
boxmodelo.shop##+js(nano-stb, atualizar, *, 0.02)
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/3e3cc92d-2e98-4b88-b54b-9cf2660e27ef)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 100677
 cosmetic: 44571
 scriptlet: 22307
 html: 1226
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5413-9, 1h.24m
 default:
  user-filters: 28-0, never
  ublock-filters: 35422-43, 1h.37m
  ublock-badware: 7957-0, 1h.37m
  ublock-privacy: 577-0, 1h.37m
  ublock-unbreak: 2179-1, 1h.37m
  ublock-quick-fixes: 263-53, 1h.37m
  easylist: 70376-272, 1h.37m
  easyprivacy: 33208-84, 1h.37m
  urlhaus-1: 5849-0, 1h.37m
  plowe-0: 3723-1069, 1h.37m
  spa-1: 5565-93, 1h.37m
filterset (user): [array of 27 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 220 ms (selfie)
 maxAssetCacheWait: 123 ms
popupPanel:
 blocked: 5
 network:
  disqus.com: 2
  googletagmanager.com: 1
  viglink.com: 2
```
</details>

**Comment by mapx-** [comment]
only for filmize the filters don't work

**Comment by ghajini** [comment]
something wrong with chrome, even ubo disabled /incognito i do get antiadb

In firefox 
`||ad.a-ads.com^$frame,redirect-rule=noopframe,from=guiacripto.online`

**Comment by mapx-** [comment]
working FF / chrome

```
guiacripto.online##+js(set-cookie, visited, yes)
guiacripto.online##+js(nano-stb, player, *, 0.02)
||ad.a-ads.com^$frame,redirect-rule=noopframe,from=guiacripto.online
```
