### ISSUE TITLE
oxforddictionaries.com

### ISSUE THREAD

**Issue by jwinnie** [uBlockOrigin/uAssets#1967]
### URL(s) where the issue occurs
Occurs in all Oxford Dictionary entries. For example:
`https://en.oxforddictionaries.com/definition/hello`

### Describe the issue
The "Word of The Day" panel is above where it should be and overlaps with the search bar.

### Screenshot(s)
![oxfordublock](https://user-images.githubusercontent.com/20506149/38771629-557a9ce8-3fdb-11e8-9523-014f5559f11a.png)

### Versions

- Browser/version: Google Chrome
- uBlock Origin version: Newest

### Settings
Default settings, fresh install

### Notes
Could not find a specific DOM element that was being blocked. I think blocking the ad above the definition is causing the entire page to be pushed up.

**Comment by jwinnie** [comment]
@mapx- That sort of works.
![oxfordublock](https://user-images.githubusercontent.com/20506149/38772334-d22ac97c-3fe8-11e8-95c7-730c2725964e.png)

**Comment by mapx-** [comment]
You could add also:
`oxforddictionaries.com#@#.banner`

but then you'll get an empty box on the right side

**Comment by jwinnie** [comment]
These three rules seem to fix it:
```
oxforddictionaries.com#@#.banner
oxforddictionaries.com#@#.banbox
oxforddictionaries.com##.banbox-mini
```

**Comment by ryanbr** [comment]
Seems just to be a layout issue, if resize the window it'll overlap, then back again.

**Comment by gotitbro** [comment]
@mapx- Don't really see the benefit of whitelisting the element filters. With the whitelist you have a big unhidden blank space right below the header; better a little layout issue than a jarring blank banner.

**Comment by mapx-** [comment]
add
`oxforddictionaries.com##.content-ban.container > .banner`

**Comment by gotitbro** [comment]
@mapx- Does not seem to work for me.
