### ISSUE TITLE
prokerala.com: ads

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#19674]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.prokerala.com/downloads/ringtones/download.php?id=45135`

### Category

ads

### Description

click play song and bottom ad appears

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.1rc5
Chromium Mobile: 110
filterset (summary):
 network: 106694
 cosmetic: 130971
 scriptlet: 26326
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27514-31, now
  adguard-mobile-app-banners: 4601-8, now
  adguard-other-annoyances: 13362-16, now
  adguard-popup-overlays: 23815-58, now
  adguard-social: 21378-912, now
  adguard-widgets: 2301-4, now
  ublock-annoyances: 5519-188, now
  ublock-cookies-adguard: 324-324, now
 default:
  user-filters: 7-1, never
  adguard-mobile: 8624-14, now
  easylist: 70350-119, now
  easyprivacy: 33192-137, now
  plowe-0: 3723-1143, now
  ublock-badware: 7949-147, now
  ublock-filters: 34895-620, now
  ublock-privacy: 544-7, now
  ublock-quick-fixes: 303-79, now
  ublock-unbreak: 2136-36, now
  urlhaus-1: 5856-0, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6474 ms (selfie)
 maxAssetCacheWait: 405 ms
popupPanel:
 blocked: 6
 network:
  clmbtech.com: 1
  go-mpulse.net: 2
  googletagmanager.com: 1
  nxstatic.com: 1
  scorecardresearch.com: 1
 extended:
  ##.adm-unit
```
</details>

**Comment by ghajini** [comment]
That's not an ad, can you share the screenshot?

**Comment by mapx-** [comment]
it's self-stories-promotion

add
`prokerala.com##.top-stories-articles-float`
