### ISSUE TITLE
reddit.com: ads

### ISSUE THREAD

**Issue by Verox-** [uBlockOrigin/uAssets#19675]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://old.reddit.com/r/DotA2/`

### Category

ads

### Description

The old.reddit.com web-page displays ads. Attempting to pick and block the element does not work after page reload.

Picking the element displays `##.promotedlink.controversial.gilded.promoted.link.id-t3_13jve3a.thing`

### Other extensions used

None affecting this webpage.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/6207925/8dc979b2-a035-48ba-919a-744c2f7ef831)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 108520
 cosmetic: 167476
 scriptlet: 28442
 html: 1226
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 71595-337, 33m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93349-21795, now
  ublock-annoyances: 5418-7, now
 default:
  user-filters: 8-0, never
  ublock-filters: 35456-470, now
  ublock-badware: 7957-0, now
  ublock-privacy: 577-0, now
  ublock-unbreak: 2179-0, now
  ublock-quick-fixes: 264-0, 32m
  easylist: 70350-794, now
  easyprivacy: 33192-717, now
  urlhaus-1: 5872-0, now
  plowe-0: 3723-2, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 421 ms (selfie)
 maxAssetCacheWait: 57 ms
popupPanel:
 blocked: 16
 network:
  reddit.com: 13
  redditmedia.com: 1
  redditstatic.com: 2
 extended:
  ##.premium-banner-outer
  ##.premium-banner
  ##.adsense-ads
  ##.googads
  ##.hasads
  ##.native-ad
  ##.HeaderAd
  ##.NavBarAd
  ##.ad-medium
  ##.post-ad
  ##.promoad
  ##.rectad
  ##.sidebar-ad:not(.adsbygoogle)
  ##.small-ad
  ##.sponsorAd
  ##.sponsorPost
  ##body:style(pointer-events: auto !important; overflow: auto !im…
  ##body:not(.with-listing-chooser):style(overflow: visible !impor…
  ##body > .footer-parent:style(height: calc(100%)!important; padd…
  ##body,html.scroll-is-blocked:style(overflow: auto !important;)
  ##body:style(pointer-events:auto !important;)
  #@#.promotedlink
  #@#.googleAd
  #@#.sidebar-ad
  ##+js(replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(set-constant, Notification.requestPermission, noopFunc)
  ##+js(addEventListener-defuser, block-body-scrolling)
  ##+js(remove-class, m-blurred, .m-blurred)
  ##+js(remove-class, scroll-disabled, body)
```
</details>

**Comment by stephenhawk8054** [comment]
Try turning off `AdGuard Annoyances filter` list

**Comment by Verox-** [comment]
This resolved the issue, thank you.
