### ISSUE TITLE
blackhatworld.com: detection

### ISSUE THREAD

**Issue by iluvatoq** [uBlockOrigin/uAssets#19683]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Adblock detected.

### URL(s) where the issue occurs.

`https://www.blackhatworld.com`

### Screenshot(s)

![Screenshot - 2023-09-10T105115 067](https://github.com/uBlockOrigin/uAssets/assets/81825037/4eefde3c-9730-4750-8a68-e379223c766d)

### Notes

Adblock getting detected.

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 99654
 cosmetic: 41617
 scriptlet: 18480
 html: 0
listset (total-discarded, last-updated):
 added:
  NLD-0: 2900-10, 2d.13h.2m
 default:
  user-filters: 0-0, never
  easylist: 70282-14, 2d.13h.2m
  easyprivacy: 33211-64, 2d.13h.2m
  plowe-0: 3725-1067, 2d.13h.2m
  ublock-badware: 7955-146, 2d.13h.2m
  ublock-filters: 34541-146, 2d.13h.2m
  ublock-privacy: 538-6, 2d.13h.2m
  ublock-quick-fixes: 263-43, 1h.18m
  ublock-unbreak: 2129-37, 2d.13h.2m
  urlhaus-1: 5891-0, 1h.19m
filterset (user): [empty]
trustedset:
 added: [array of 34 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 454 ms (selfie)
 maxAssetCacheWait: 99 ms
```
</details>

**Comment by mapx-** [comment]
I can reproduce only disabling 

`blackhatworld.com##+js(nostif, show)`

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
