### ISSUE TITLE
rotter.net: ads

### ISSUE THREAD

**Issue by Kintarorulez** [uBlockOrigin/uAssets#19681]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rotter.net/scoopscache.html`

### Category

ads

### Description

This is a news site, but a clear ad appears in between the news items

### Other extensions used

Grammarly
backspace to go back
copytables
lastpass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/105242560/4e2019dc-bf81-41fe-a31f-b9154271b7e2)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98985
 cosmetic: 39481
 scriptlet: 18454
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 70328-10, now
  easyprivacy: 33193-63, now
  plowe-0: 3723-1067, now
  ublock-badware: 7956-146, now
  ublock-filters: 34555-130, now
  ublock-privacy: 545-6, now
  ublock-quick-fixes: 264-67, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 5891-0, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 263 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 449 ms (selfie)
 maxAssetCacheWait: 177 ms
popupPanel:
 blocked: 22
 network:
  bstatic.com: 1
  chartbeat.com: 2
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 2
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 5
  googletagservices.com: 1
  perfdrive.com: 2
  permutive.com: 1
  smartlook.com: 1
  taboola.com: 2
  upapi.net: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##ins.adsbygoogle
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by ghajini** [comment]
add regional filter list _**Easylist Hebrew**_ from ublock origin settings

**Comment by Kintarorulez** [comment]
This indeed fixed it , thank you!

**Comment by XxfireBall7767** [comment]
> add regional filter list _**Easylist Hebrew**_ from ublock origin settings
hey, there is still ads in this website

**Comment by stephenhawk8054** [comment]
Please screenshot how the ads look like.

**Comment by XxfireBall7767** [comment]
<details>

<img width="2560" height="1212" alt="Image" src="https://github.com/user-attachments/assets/43c36ee3-a3ce-43c8-a82b-2f4d3c8cf709" />

<img width="2560" height="1071" alt="Image" src="https://github.com/user-attachments/assets/ad2acf96-242c-45fa-9f01-582921dedf29" />

<img width="2560" height="1194" alt="Image" src="https://github.com/user-attachments/assets/b08aa4e4-2755-45cb-beed-4d2832d1d973" />

</details>

also on IOS safari

<details>

<img width="591" height="1280" alt="Image" src="https://github.com/user-attachments/assets/ab85f9db-6fbc-455c-80a1-6a453572e6f0" />

<img width="591" height="1280" alt="Image" src="https://github.com/user-attachments/assets/7b26a3cf-a303-4b5a-a8b9-3c2417fcd62e" />

</details>

**Comment by XxfireBall7767** [comment]
> Please screenshot how the ads look like.

hey. added above

**Comment by stephenhawk8054** [comment]
I can't reproduce after adding EasyList Hebrew list:

<details>

<img width="2520" height="1607" alt="Image" src="https://github.com/user-attachments/assets/7d29e318-8609-410a-9858-b209e989ea42" />

</details>

Do we need to log in to the site to reproduce?

**Comment by XxfireBall7767** [comment]
> I can't reproduce after adding EasyList Hebrew list:
> 
> Details
> <img alt="Image" width="2000" height="1275" src="https://private-user-images.githubusercontent.com/66517106/611268588-7d29e318-8609-410a-9858-b209e989ea42.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODIxNTE1NTcsIm5iZiI6MTc4MjE1MTI1NywicGF0aCI6Ii82NjUxNzEwNi82MTEyNjg1ODgtN2QyOWUzMTgtODYwOS00MTBhLTk4NTgtYjIwOWU5ODllYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjIyVDE4MDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZDFjZDgzZGJjMjAxOWI3ZDc3MTgyMWQ2MDdjM2M2YmE1ZDg0ZmE5ZTllZGUwMzI0OTY3NTIxZDM2YjEyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.1wqSUNiO1Zzt3Vz-ITdtTgfq0aGHJmUFpn-8UMC61Yo">
> Do we need to log in to the site to reproduce?

No, logging in is not required. The ads are displayed across two different browsers and on iOS.
i'm using this btw 
 https://chromewebstore.google.com/detail/ublock-origin-lite/ddkjiahejlhfcafbddmgiahcphecmpfh?pli=1

**Comment by XxfireBall7767** [comment]
> I can't reproduce after adding EasyList Hebrew list:
> 
> Details
> <img alt="Image" width="2000" height="1275" src="https://private-user-images.githubusercontent.com/66517106/611268588-7d29e318-8609-410a-9858-b209e989ea42.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODIzMDYzMTYsIm5iZiI6MTc4MjMwNjAxNiwicGF0aCI6Ii82NjUxNzEwNi82MTEyNjg1ODgtN2QyOWUzMTgtODYwOS00MTBhLTk4NTgtYjIwOWU5ODllYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjI0VDEzMDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYTM0MWY2OWU3ZTk1YTAzYzQ2MjY0Yzc4YmUwZTdlNTI1NjI3YTU3ZDg2ODYxYjM1ZWY4MWQyMTUzODE3MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.fxiWUEXKn0lwQJAz7hXwgbhoovxtnUno9aiajJ_lOb8">
> Do we need to log in to the site to reproduce?

There is any fix ?

**Comment by stephenhawk8054** [comment]
I don't understand what you mean. I can't reproduce the issue so I can't investigate further.

**Comment by XxfireBall7767** [comment]
> I don't understand what you mean. I can't reproduce the issue so I can't investigate further.

Are you using uBlock Origin Lite?
i'm on chrome. So i don't have the uBlock Origin, only lite version.

**Comment by stephenhawk8054** [comment]
Yes, I tested with uBOL version `2026.622.2316`. Which version are you using?
