### ISSUE TITLE
github.com: ads on You Tube keep showing, I cannot purge the cache on ubo Filter list 

### ISSUE THREAD

**Issue by NBspaceCadet360** [uBlockOrigin/uAssets#19682]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://github.com/uBlockOrigin/uAssets/issues/7636`

### Category

ads

### Description

I am trying to stop ads from you tube following advice from the top of this page (I have Crome browser) https://github.com/easylist/easylist/wiki/Youtube-Issues.

On uBlock Origin section, Step 2, Click on Purge all cache, it does not purge the cache. It updates for a moment then shows all the same numbers.
I had done Step 3, My filterlists Tab thing.

[stephenhawk8054](https://github.com/stephenhawk8054)  suggested I file a report here.
I do not use a VPN.  Ads were blocked on you tube until last week.

### Other extensions used

||music.youtube.com^$csp=worker-src 'none'
||www.youtube.com^$csp=worker-src 'none'
youtube.com##+js(json-prune, 2.playerResponse.adPlacements playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds)
youtube.com##+js(json-prune, 2.playerResponse.adPlacements)
youtube.com##+js(json-prune, playerResponse.adPlacements)
youtube.com##+js(json-prune, playerResponse.playerAds)
youtube.com##+js(set, ytInitialPlayerResponse.adPlacements, null)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![ubo](https://github.com/uBlockOrigin/uAssets/assets/28228292/8581beea-040e-426b-9922-5fc9182c2325)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 98996
 cosmetic: 39469
 scriptlet: 18429
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 12-0, never
  easylist: 70328-10, now
  easyprivacy: 33213-63, now
  plowe-0: 3723-1068, now
  ublock-badware: 7956-146, now
  ublock-filters: 34504-130, now
  ublock-privacy: 545-6, now
  ublock-quick-fixes: 264-67, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 5891-0, now
filterset (user): [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 801 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel:
 blocked: 13
 network:
  github.com: 13
```
</details>

**Comment by stephenhawk8054** [comment]
You are commenting on the right thread, no need to open duplicated issue

**Comment by stephenhawk8054** [comment]
I didn't tell you open the issue. Sigh.

**Comment by NBspaceCadet360** [comment]
well, heck.  Maybe this issue will get fixed over time. 

OK to delete my duplicate thread.
