### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by rahulc0dy** [uBlockOrigin/uAssets#19680]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=6-Lxyi53HJI&list=PLC36xJgs4dxEErKQZ7xFxat8oh4OepU34&index=81`

### Category

ads

### Description

Youtube shows ads before videos and some are even unskippable

### Other extensions used

wappalyzer, speedtest by ookla, dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 118201
 cosmetic: 81822
 scriptlet: 33201
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 73552-467, now
  adguard-mobile: 8624-43, now
 default:
  user-filters: 0-0, never
  easylist: 70328-1057, now
  easyprivacy: 33193-168, now
  plowe-0: 3723-1152, now
  ublock-badware: 7956-364, now
  ublock-filters: 34555-3808, now
  ublock-privacy: 545-6, now
  ublock-quick-fixes: 267-67, now
  ublock-unbreak: 2131-93, now
  urlhaus-1: 5891-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 412 ms (selfie)
 maxAssetCacheWait: 183 ms
popupPanel:
 blocked: 54
 network:
  youtube.com: 31
  doubleclick.net: 3
  google.co.in: 1
  google.com: 18
  googlesyndication.com: 1
 hasUnprocessedRequest: true
 extended:
  ###offer-module
  ###merch-shelf
  ###player-ads
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##ytd-companion-slot-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  #@#.video-ads
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these steps?

1. Add `||youtube.com^$csp=worker-src 'none'` as a custom filter
2. Open `chrome://serviceworker-internals/`
3. Find youtube service worker > Stop and unregister it.

Then please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

**Comment by stephenhawk8054** [comment]
Also please test again without other extensions.
