### ISSUE TITLE
Snopes.com

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#1968]
### URL(s) where the issue occurs

`https://www.snopes.com/fact-check/census-bureau-japanese-americans/`

### Describe the issue

ADS

### Settings

Default settings

### Notes

`snopes.com##script:inject(noeval.js)`

**Comment by mapx-** [comment]
and to unbreak the "more from snopes" section at the bottom:
`@@||cdn.boomtrain.com/analyticstrain/snopes/analyticstrain.min.js$script,domain=snopes.com`

**Comment by mapx-** [comment]
@ryanbr
