### ISSUE TITLE
jornaldigital.org: breakage

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#19693]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://jornaldigital.org/post.php?token=aHR0cHM6Ly9zdXBlcmVtYmVkcy5jb20vZW1iZWQyLzY2NzMyLTEtMQ==`

### Category

breakage

### Description

first link:
`https://www.megahdfilme.com/episodios/stranger-things-1x1/`

```adb
jornaldigital.org##+js(set-cookie, Ads, 2)
||cdn.jsdelivr.net/npm/devtools-detector$script
||media.toxtren.com^$all,3p
superembeds.com##+js(nowoif)
superembeds.com###adStop
```
`media.toxtren.com` has popups and ad as the videoplayer stop.
Site need `cookie: ads, 2` to load the video player
`superembeds` open new tab

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 100844
 cosmetic: 44538
 scriptlet: 22299
 html: 1224
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5418-9, 1h.5m
 default:
  user-filters: 15-0, never
  ublock-filters: 35376-42, 1h.5m
  ublock-badware: 7958-0, 1h.5m
  ublock-privacy: 588-0, 1h.5m
  ublock-unbreak: 2179-1, 1h.5m
  ublock-quick-fixes: 254-40, 1h.5m
  easylist: 70506-274, 1h.5m
  easyprivacy: 33248-84, 1h.5m
  urlhaus-1: 5844-0, 1h.5m
  plowe-0: 3723-1070, 1h.5m
  spa-1: 5565-93, 1h.5m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3068 ms (selfie)
 maxAssetCacheWait: 1088 ms
popupPanel:
 blocked: 29
 network:
  aj2204.online: 3
  cleverwebserver.com: 1
  d3u598arehftfk.cloudfront.net: 1
  googlesyndication.com: 1
  histats.com: 1
  jsdelivr.net: 1
  jwpcdn.com: 1
  mahimeta.com: 8
  servetraff.com: 3
  toxtren.com: 8
  waust.at: 1
 extended:
  ##.adcenter
  ###ads2
  ##+js(set-cookie, Ads, 2)
  ##+js(no-window-open-if)
```
</details>

**Comment by stephenhawk8054** [comment]
@mapx- If I remember correctly, `||cdn.jsdelivr.net/npm/devtools-detector$script` can cause breakages in some video sites. I think we should make it domain-specific to be safe.

**Comment by ghajini** [comment]
`||media.toxtren.com^$all,3p` => `||media.toxtren.com^$all`

**Comment by mapx-** [comment]
done
