### ISSUE TITLE
80.lv: ads

### ISSUE THREAD

**Issue by AliceVie** [uBlockOrigin/uAssets#19690]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://80.lv/articles/creating-marble-in-substance-designer/`

### Category

ads

### Description

Ads are appearing on this site. They seem to be provided by the site itself, rather than a third-party ad service, based on a quick glance at the source. 

### Other extensions used

Dark Reader
Volume Booster
The Stream Detector
Flag Cookies
Tab Reloader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/91287560/ed4c09ef-fb9b-411e-89e3-f7be0f75cd4e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 99110
 cosmetic: 39472
 scriptlet: 18365
 html: 1036
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35376-84, now
  ublock-badware: 7958-1, now
  ublock-privacy: 577-0, now
  ublock-unbreak: 2179-0, now
  ublock-quick-fixes: 255-0, now
  easylist: 70506-708, now
  easyprivacy: 33215-718, 1h.8m
  urlhaus-1: 5859-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 142 ms (selfie)
 maxAssetCacheWait: 58 ms
popupPanel:
 blocked: 15
 network:
  google.com: 1
  googletagmanager.com: 1
  xsolla.com: 9
  youtube.com: 4
```
</details>

**Comment by mapx-** [comment]
report at easylist repository

add
```
80.lv###Big_Image_Banner
80.lv##.BrandingPromo_skeleton
80.lv##[id^="Image_Banner"]
80.lv##.ImagePromo_default
```

@ryanbr

**Comment by taiwithers** [comment]
Seeing ads on this site as well: https://80.lv/articles/disco-elysium-writer-believes-this-industry-is-finished

**Comment by stephenhawk8054** [comment]
Report at https://github.com/easylist/easylist/issues/
