### ISSUE TITLE
bypass.city: nuisance

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#19691]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bypass.city/`

### Category

nuisance

### Description

cookie warning. 

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScsadasfasfreenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/e1cec762-827a-416b-add7-4d72638b6740)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 105477
 cosmetic: 121474
 scriptlet: 26313
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/mchangrh/yt-neuter/master/filters/sponsorblock.txt: 30-0, 1h.55m
  easylist-annoyances: 3966-33, 1h.42m
  easylist-chat: 134-0, 1h.42m
  easylist-newsletters: 6446-15, 1h.42m
  easylist-notifications: 2659-79, 1h.42m
  fanboy-cookiemonster: 48397-222, 1h.42m
  fanboy-social: 16137-12, 1h.42m
  ublock-annoyances: 5458-82, 1h.42m
  ublock-cookies-easylist: 288-288, 1h.42m
 default:
  user-filters: 0-0, never
  TUR-0: 13607-10, now
  easylist: 70506-31, now
  easyprivacy: 33215-155, now
  plowe-0: 3723-1069, now
  ublock-badware: 7956-146, now
  ublock-filters: 34503-157, now
  ublock-privacy: 545-8, now
  ublock-quick-fixes: 261-60, now
  ublock-unbreak: 2131-37, now
  urlhaus-1: 5859-0, now
filterset (user): [empty]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 241 ms (selfie)
 maxAssetCacheWait: 123 ms
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 2
 extended:
  ##+js(no-fetch-if, googlesyndication)
```
</details>

**Comment by mapx-** [comment]
add

`bypass.city##.mantine-Dialog-root`

@ryanbr

**Comment by ave9858** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/01c96292-bfb5-4658-a5b7-4be53243c65b)
On the first visit, when bypassing your first link, it will show this notice and then open a another tab. In my testing that page is prevented from loading by the uBO badware risk.

I was able to disable the popup completely with either `bypass.city##+js(nowoif, "jump/next.php")` or
`bypass.city##+js(set-local-storage-item, ads_enabled, false)`
