### ISSUE TITLE
blitz.gg: ads

### ISSUE THREAD

**Issue by iammodev** [uBlockOrigin/uAssets#19699]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blitz.gg/lol/tierlist`

### Category

ads

### Description

Ads are being shown on the right side of the page.

### Other extensions used

"Dark Reader",
"I don't care about cookies"

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/89686923/49794e70-21b3-4930-9601-5134a2db3cb2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 99066
 cosmetic: 39479
 scriptlet: 18450
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70433-10, now
  easyprivacy: 33248-63, now
  plowe-0: 3723-1068, now
  ublock-badware: 7962-146, now
  ublock-filters: 34519-129, now
  ublock-privacy: 558-6, now
  ublock-quick-fixes: 261-57, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 5821-0, 32m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2210 ms (selfie)
 maxAssetCacheWait: 790 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##.display-ad
```
</details>

**Comment by mapx-** [comment]
add

`blitz.gg##.aside-content-column:has(.display-ad)`

@ryanbr
