### ISSUE TITLE
english-trainer.net: popups

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#19694]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.english-trainer.net/index.html`

### Category

popups

### Description

pops up every few months

### Other extensions used

annoying ad

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 101665
 cosmetic: 45655
 scriptlet: 18811
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70506-10, now
  easyprivacy: 33248-63, now
  plowe-0: 3723-1068, now
  spa-0: 3781-19, now
  spa-1: 5565-226, now
  ublock-badware: 7956-146, now
  ublock-filters: 34503-159, now
  ublock-privacy: 558-6, now
  ublock-quick-fixes: 260-59, now
  ublock-unbreak: 2131-34, now
  urlhaus-1: 5844-0, now
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 427 ms
 maxAssetCacheWait: 138 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
I get no "popups"
Screenshot ?
Does it happen only on some specific page ? Do we need an account ?

**Comment by okiehsch** [comment]
Well, the OP says that it "pops up every few months" and has deleted his/her account, so not much we can do here.
