### ISSUE TITLE
clarin.com: ads

### ISSUE THREAD

**Issue by Kelvin318** [uBlockOrigin/uAssets#19703]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.clarin.com/deportes/agenda-deportiva`

### Category

ads

### Description

There is a windows of Google in this page and others, inviting access to Google account. 
![Windows of Google](https://github.com/uBlockOrigin/uAssets/assets/67394595/68667f6e-bc78-406e-be66-3482ea50d48a)

### Other extensions used

Ghostery

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 99078
 cosmetic: 39505
 scriptlet: 18371
 html: 1036
listset (total-discarded, last-updated):
 default:
  user-filters: 31-0, never
  ublock-filters: 35390-42, now
  ublock-badware: 7964-0, now
  ublock-privacy: 588-0, now
  ublock-unbreak: 2179-1, now
  ublock-quick-fixes: 255-38, now
  easylist: 70453-274, now
  easyprivacy: 33248-84, now
  urlhaus-1: 5821-0, now
  plowe-0: 3723-1070, now
filterset (user): [array of 31 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 61 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 430 ms (selfie)
 maxAssetCacheWait: 293 ms
popupPanel:
 blocked: 18
 network:
  cloudflareinsights.com: 4
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 4
  googletagmanager.com: 1
  newrelic.com: 2
  newsroom.bi: 4
  permutive.app: 1
 extended:
  ##.bannerTopHeader
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[id^="google_ads_iframe"]
```
</details>

**Comment by mapx-** [comment]
```
clarin.com###credential_picker_container
clarin.com##.bannerTopHeader
clarin.com##.sticky-banner
clarin.com###div-gpt-ad-horizontal3:upward(1)
```

**Comment by mapx-** [comment]
@Yuki2718 for the last 3 filters in the spanish list ?
