### ISSUE TITLE
cbr.com: detection

### ISSUE THREAD

**Issue by jcfgonc** [uBlockOrigin/uAssets#19707]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cbr.com/best-nes-rpgs/`

### Category

detection

### Description

webpage detects uBlock Origin

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Opera Snapshot_2023-09-12_114222_www cbr com](https://github.com/uBlockOrigin/uAssets/assets/43711104/ed20b113-46bc-4c0c-bc2d-86a63ea8f804)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 115
filterset (summary):
 network: 99106
 cosmetic: 39510
 scriptlet: 18458
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70468-10, now
  easyprivacy: 33251-63, now
  plowe-0: 3723-1068, now
  ublock-badware: 7962-146, now
  ublock-filters: 34670-129, now
  ublock-privacy: 558-6, now
  ublock-quick-fixes: 261-195, 38m
  ublock-unbreak: 2131-32, now
  urlhaus-1: 5849-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 743 ms (selfie)
 maxAssetCacheWait: 74 ms
popupPanel:
 blocked: 11
 network:
  cbr.com: 2
  aloofvest.com: 3
  google-analytics.com: 1
  googletagmanager.com: 2
  scorecardresearch.com: 1
  tru.am: 1
  unpkg.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adsninja-ad-zone
  ##.ad-current
  ##.ad-zone-container
  ##.ad-zone:not(.textads)
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.ad-zone
```
</details>

**Comment by mapx-** [comment]
Did you arrive on that page from other link ? which one ?
