### ISSUE TITLE
getemoji.com: ads

### ISSUE THREAD

**Issue by farrers** [uBlockOrigin/uAssets#19705]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://getemoji.com/`

### Category

ads

### Description

Been using this web site for more than a year and ads just started showing through uBlock Origin

### Other extensions used

Enpass Password Manager
6.8.6

Fakespot Fake Amazon Reviews 

Unhook - Remove YouTube Recommended

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screen Shot 2023-09-11 at 7 29 16 PM](https://github.com/uBlockOrigin/uAssets/assets/144751275/ece86fb8-9445-48ce-a990-46cccef851fa)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 106
filterset (summary):
 network: 99114
 cosmetic: 39480
 scriptlet: 18447
 html: 0
listset (total-discarded, last-updated):
 added:
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, now
 default:
  user-filters: 1-0, never
  easylist: 70453-10, now
  easyprivacy: 33248-63, now
  plowe-0: 3723-1068, now
  ublock-badware: 7962-146, now
  ublock-filters: 34517-129, now
  ublock-privacy: 558-6, now
  ublock-quick-fixes: 261-57, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 5849-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2948 ms (selfie)
 maxAssetCacheWait: 875 ms
popupPanel:
 blocked: 11
 network:
  apester.com: 6
  googletagmanager.com: 1
  hotjar.com: 1
  pub.network: 2
  twitter.com: 1
 extended:
  ##[data-freestar-ad]
```
</details>

**Comment by mapx-** [comment]
it's GetEmoji stuff, if you do not want it add:
`getemoji.com##.apester-unit.apester-media`
