### ISSUE TITLE
accounts.intuit.com: breakage

### ISSUE THREAD

**Issue by KimmytheTechnician** [uBlockOrigin/uAssets#19700]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://accounts.intuit.com/index.html?redirect_url=https%3A%2F%2Faccounts.intuit.com%2Fapp%2Faccount-manager%2Foverview%3FpiuInFlyout%3Dtrue%26openBlueDot%3Dtrue%26accountSwitcherInFlyout%3Dtrue%26rgn%3DUS%26prgn%3DUS&appfabric=true`

### Category

breakage

### Description

The webpage doesn't load until UBlock is disabled and refreshed. This was happening for one of my helpdesk clients, and verified it happens for me too on my computer.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 99066
 cosmetic: 39479
 scriptlet: 18450
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70433-10, now
  easyprivacy: 33248-63, now
  plowe-0: 3723-1068, now
  ublock-badware: 7962-146, now
  ublock-filters: 34519-129, now
  ublock-privacy: 558-6, now
  ublock-quick-fixes: 261-57, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 5821-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 489 ms (selfie)
 maxAssetCacheWait: 199 ms
popupPanel:
 blocked: 4
 network:
  intuit.com: 1
  go-mpulse.net: 2
  intuitcdn.net: 1
```
</details>

**Comment by mapx-** [comment]
add & test

`||intuitcdn.net/analytics/$badfilter`

@ryanbr

**Comment by KimmytheTechnician** [comment]
That worked! You're the best.


Kimmy Deatherage

Technician

Sterling Computer Services

(806) 722-0770
www.sterlingcomputerservices.com

________________________________
