### ISSUE TITLE
torrentgalaxy.to: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#19711]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://torrentgalaxy.to/`

### Category

ads

### Description

i've seen the last issue but it's still there for me in default reset settings.

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScrasdfasdfaqwwweenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/cdb8512e-45bb-4b6c-8036-ef6fb5e4caf2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 101004
 cosmetic: 49894
 scriptlet: 19921
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13617-10, now
  easylist: 70574-29, now
  easyprivacy: 33252-68, now
  plowe-0: 3723-1069, now
  ublock-badware: 7975-146, now
  ublock-filters: 34693-136, now
  ublock-privacy: 558-6, now
  ublock-quick-fixes: 270-199, now
  ublock-unbreak: 2133-33, now
  urlhaus-1: 5870-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 901 ms
 maxAssetCacheWait: 15 ms
popupPanel:
 blocked: 2
 network:
  fidelitybearer.com: 1
  tstats-13fkh44r.com: 1
 extended:
  ##+js(abort-on-stack-trace, String.prototype.charCodeAt, $)
```
</details>

**Comment by gototheskinny** [comment]
wow that was fast! thank you!

**Comment by ave9858** [comment]
URL: `https://torrentgalaxy.to/torrents.php`

Netflix Premium ads: 
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/7922b297-5366-4434-b738-aaa261a0fb42)
