### ISSUE TITLE
numerama.com: breakage

### ISSUE THREAD

**Issue by momala454** [uBlockOrigin/uAssets#19718]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.numerama.com/pop-culture/1500666-unity-une-nouvelle-taxe-seme-la-panique-dans-les-studios-de-jeux-video.html`

### Category

breakage

### Description

Cannot accept cookies to view content from twitter

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/83005/2f8e9d35-22b6-4ae1-b4c6-1ab2a26e6cae)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 117654
 cosmetic: 93756
 scriptlet: 24655
 html: 1238
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  fanboy-cookiemonster: 48373-278, now
  ublock-annoyances: 5420-7, now
  ublock-quick-fixes: 256-0, now
 default:
  user-filters: 315-28, never
  ublock-filters: 35541-214, now
  ublock-badware: 7977-0, now
  ublock-privacy: 587-1, now
  ublock-unbreak: 2173-0, now
  easylist: 70698-377, now
  easyprivacy: 33253-24, now
  FRA-0: 28311-404, now
  urlhaus-1: 5880-0, now
filterset (user): [array of 323 redacted]
trustedset:
 added: [array of 162 redacted]
 removed:
  about-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 15 redacted]
hostRuleset:
 added: [array of 13 redacted]
urlRuleset:
 added: [array of 47 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 737 ms (selfie)
 maxAssetCacheWait: 148 ms
popupPanel:
 blocked: 11
 network:
  numerama.com: 2
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  humanoid.fr: 2
  opti-digital.com: 1
  parsely.com: 2
  privacy-center.org: 1
 extended:
  ##.dailymotion-cpe[data-ad-slot]
  ##.is-hidden-mobile.container > .is-hidden-mobile
  ##div[id^="optidigital-adslot-"]
  ##div[id^="optidigital-adslot"]
  ##.hb__ad
  ##.post-card:has(span:has-text(sponso))
```
</details>

**Comment by mapx-** [comment]
add

`@@||sdk.privacy-center.org^$script,domain=numerama.com`

@ryanbr
