### ISSUE TITLE
southpark.de: detection

### ISSUE THREAD

**Issue by m64b** [uBlockOrigin/uAssets#19710]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.southpark.de/en/episodes/ndszwn/south-park-douche-and-turd-season-8-ep-8?isRandom=true`

### Category

detection

### Description

This was temporarily fixed after issue https://github.com/uBlockOrigin/uAssets/issues/19207 and popped back up again today.

### Other extensions used

deactivated all others for testing purposes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Firefox_Screenshot_2023-09-12T20-03-04 628Z](https://github.com/uBlockOrigin/uAssets/assets/144655543/d9018352-3545-4b9b-adf8-9c6438b3f44d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 101539
 cosmetic: 44205
 scriptlet: 18376
 html: 1038
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35570-149, 5m
  ublock-badware: 7977-0, 5m
  ublock-privacy: 588-0, 5m
  ublock-unbreak: 2181-0, 5m
  easylist: 70574-610, 5m
  easyprivacy: 33252-727, 5m
  urlhaus-1: 5870-0, 5m
  plowe-0: 3723-2, 5m
  DEU-0: 7068-3, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5032 ms (selfie)
 maxAssetCacheWait: 138 ms
popupPanel:
 blocked: 34
 network:
  cbsaavideo.com: 3
  cbsivideo.com: 14
  demdex.net: 1
  imasdk.googleapis.com: 1
  mtvnservices.com: 3
  newrelic.com: 4
  ns1p.net: 4
  paramount.tech: 4
```
</details>

**Comment by mapx-** [comment]
FF / chrome => all fine on my end

**Comment by m64b** [comment]
A complete Firefox restart later, and the german page is working again. I don't get it, but thanks for looking into it.

**Comment by mapx-** [comment]
tested using DE ip (to stay as `southpark.de`), still no detection
