### ISSUE TITLE
starfiles.co: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#19712]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://starfiles.co/file/2JSLVmHjgXdW/SpotifyDeluxev-8-8-8`

### Category

ads

### Description

ad on "download" button page

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreensdfaswshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/9454f096-970d-49b6-81e2-541b487cfe70)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 105619
 cosmetic: 121592
 scriptlet: 26344
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 3967-32, 16m
  easylist-chat: 134-0, 16m
  easylist-newsletters: 6459-15, 16m
  easylist-notifications: 2666-79, 16m
  fanboy-cookiemonster: 48378-222, 16m
  fanboy-social: 16161-12, 16m
  fanboy-thirdparty_social: 68-15, 16m
  ublock-annoyances: 5460-82, 16m
  ublock-cookies-easylist: 289-289, 16m
 default:
  user-filters: 0-0, never
  TUR-0: 13617-10, 16m
  easylist: 70593-29, 16m
  easyprivacy: 33248-155, 16m
  plowe-0: 3723-1069, 16m
  ublock-badware: 7975-146, 16m
  ublock-filters: 34694-157, 16m
  ublock-privacy: 558-8, 16m
  ublock-quick-fixes: 271-199, 16m
  ublock-unbreak: 2133-37, 16m
  urlhaus-1: 5870-0, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1411 ms
 maxAssetCacheWait: 10 ms
popupPanel:
 blocked: 13
 network:
  starfiles.co: 1
  clarity.ms: 1
  cloudflareinsights.com: 1
  facebook.net: 1
  google.com: 6
  googlesyndication.com: 1
  googletagmanager.com: 1
  media.net: 1
 extended:
  ##iframe[name="googlefcPresent"]
  ###share_button
```
</details>

**Comment by mapx-** [comment]
add

`starfiles.co##a[href*="?ref"]`

to be reported at easylist repository
@ryanbr
