### ISSUE TITLE
[nsfw] viralvideotube.pro/mangoporn.co: ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#19724]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ads/popups

### URL(s) where the issue occurs.

**nsfw**
`https://viralvideotube.pro/maili-chadar-s01-ep3-4-wow-entertainment-webseries-2023/`
`https://mangoporn.co/adult/movies/mird-226/`

### uBO version

1.52

### Browser name and version

firefox/chrome

### Settings

uBO's default settings

**Comment by dimisa-RUAdList** [comment]
Check, please: `https://lulustream.com/phcr8mq4yf7o`

>Disable Adblock and Click Allow Pop-up Always to watch this video !

**Comment by ghajini** [comment]
can't reproduce with uBO/uBOL stable

**Comment by stephenhawk8054** [comment]
I can reproduce.
