### ISSUE TITLE
cmspweb.ip.tv: nuisance

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#19723]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cmspweb.ip.tv/`

### Category

nuisance

### Description

Don't allow paste.

Need login, where I share and give the steps to reproduce?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 115
filterset (summary):
 network: 218783
 cosmetic: 191485
 scriptlet: 30278
 html: 0
listset (total-discarded, last-updated):
 added:
  https://github.com/AdroitAdorKhan/antipopads-re/raw/master/formats/filter.txt: 91624-0, now
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 929-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2262-0, now
  adguard-cookies: 27547-30, now
  adguard-mobile-app-banners: 4614-8, now
  adguard-other-annoyances: 13510-7, now
  adguard-popup-overlays: 24018-78, now
  adguard-social: 21398-907, now
  adguard-spyware: 56669-340, now
  adguard-spyware-url: 1208-144, now
  adguard-widgets: 2304-6, now
  easylist-annoyances: 3970-217, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 105-0, never
  easylist: 70746-25828, now
  easyprivacy: 33255-16734, now
  plowe-0: 3723-1198, now
  spa-1: 5594-72, now
  ublock-badware: 7986-173, now
  ublock-filters: 34666-635, now
  ublock-privacy: 557-150, now
  ublock-quick-fixes: 265-184, 51m
  ublock-unbreak: 2125-88, now
  urlhaus-1: 5854-0, now
filterset (user): [array of 61 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 3253 ms (selfie)
 maxAssetCacheWait: 453 ms
popupPanel:
 blocked: 3
 network:
  bugsnag.com: 2
  googletagmanager.com: 1
 extended:
  ##+js(addEventListener-defuser, copy)
```
</details>

**Comment by mapx-** [comment]
contact me on reddit => `u/ajaxmix`
