### ISSUE TITLE
torrentgalaxy.to: breakage

### ISSUE THREAD

**Issue by Minherre** [uBlockOrigin/uAssets#19729]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://torrentgalaxy.to/torrents.php?c9=1&c9=1&c41=1&c41=1&c5=1&c5=1&c6=1&c6=1&sort=id&order=desc&page=0`

### Category

breakage

### Description

With 'Cosmetic Filtering' ON the Torrentnames are no longer visable, when Cosmetic Filtering is OFF the page again shows the Torrent-Filenames.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 99230
 cosmetic: 39569
 scriptlet: 18467
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70710-11, now
  easyprivacy: 33257-63, now
  plowe-0: 3723-1068, now
  ublock-badware: 7986-146, now
  ublock-filters: 34687-129, now
  ublock-privacy: 557-6, now
  ublock-quick-fixes: 282-201, now
  ublock-unbreak: 2128-32, now
  urlhaus-1: 5743-0, now
filterset (user): [empty]
trustedset:
 added: [array of 31 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 777 ms (selfie)
 maxAssetCacheWait: 265 ms
popupPanel:
 blocked: 2
 no-cosmetic-filtering: true
 network:
  freakishmartyr.com: 1
  tstats-13fkh44r.com: 1
```
</details>

**Comment by Sikas00** [comment]
Closed my previous issue request as this one is more accurate, but to clarify it's the "Parse and enforce cosmetic filters" option that borks the site as mentioned in OP.

![image](https://github.com/uBlockOrigin/uAssets/assets/23747911/3538aef6-9999-45f4-a24f-db8cf0f08be8)

**Comment by wefalltomorrow** [comment]
Not sure why it was closed when the fix doesn't work and the site is still broken.

**Comment by mapx-** [comment]
they quickly broke their own site.

**Comment by wefalltomorrow** [comment]
> they quickly broke their own site.

Fair enough, I retract my previous statement then.
