### ISSUE TITLE
service-public.fr: breakage

### ISSUE THREAD

**Issue by walrus543** [uBlockOrigin/uAssets#19722]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.service-public.fr/particuliers/vosdroits/F17578`

### Category

breakage

### Description

Scroll to "3. Remplir la déclaration préalable de travaux" and enter the postal code e.g "74000"
A list should appear to select a city but it doesn't happen.

Thanks to the logs, there's only one blocked source:

```
Filtre: /eulerian.js
Liste de filtres: 
[EasyPrivacy](moz-extension://471e22b9-1cb8-4cc9-b209-7f705fba15dd/asset-viewer.html?url=easyprivacy)
 
Contexte: www.service-public.fr
Niveau de partie: (1) service-public.fr ⇒ service-public.fr
Type: script
Lien: https://www.service-public.fr/resources/v-6b4f7bc758/assets/js/eulerian/eulerian.js
```
Once allowed, the list of cities is displayed.

### Other extensions used

Not relevant

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock](https://github.com/uBlockOrigin/uAssets/assets/5938828/8014dfc4-bdc5-44d1-af16-13ecc7089f02)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 119829
 cosmetic: 92280
 scriptlet: 21431
 html: 1039
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 48376-232, now
  ublock-cookies-easylist: 290-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 35548-223, now
  ublock-badware: 7988-1, now
  ublock-privacy: 587-0, now
  ublock-unbreak: 2173-0, now
  ublock-quick-fixes: 274-0, now
  easylist: 70746-740, now
  easyprivacy: 33255-718, now
  urlhaus-1: 5854-0, now
  plowe-0: 3723-1, now
  FRA-0: 28312-415, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1261 ms (selfie)
 maxAssetCacheWait: 378 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`/eulerian.js$badfilter`
