### ISSUE TITLE
vimeo.com: breakage

### ISSUE THREAD

**Issue by F1ngon** [uBlockOrigin/uAssets#19727]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vimeo.com/644703999`

### Category

breakage

### Description

When entering the page (and all other Vimeo pages with "unrated videos") the Vimeo error message "Video is not rated. Please log in to watch" shows instead of the video, even when I am already logged in. See first printscreen below. 

If I disable uBO and reload the page, the error message dissappear and the video shows, see the second printscreen below. I can now re-activate uOB, the current video will continue to be shown. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230913_232832_org mozilla firefox_beta](https://github.com/uBlockOrigin/uAssets/assets/144960332/8a647e14-d73a-4e3f-a568-9a72bad7eeb8)

![Screenshot_20230913_232846_org mozilla firefox_beta](https://github.com/uBlockOrigin/uAssets/assets/144960332/1e29170f-470e-4a7c-94c0-0234307c2b2c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox Mobile: 118
filterset (summary):
 network: 104240
 cosmetic: 59403
 scriptlet: 21404
 html: 1057
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 48376-17519, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 35874-476, 3m
  ublock-badware: 7982-0, 3m
  ublock-privacy: 587-1, 3m
  ublock-unbreak: 2178-1, 3m
  ublock-quick-fixes: 274-0, 3m
  adguard-mobile: 8631-124, 2m
  easylist: 70763-16694, 2m
  easyprivacy: 33255-731, 2m
  urlhaus-1: 5854-0, 2m
  plowe-0: 3723-2, 2m
  SWE-1: 4628-320, 2m
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 903 ms
 maxAssetCacheWait: 483 ms
popupPanel:
 blocked: 7
 network:
  vimeo.com: 2
  app.link: 1
  googletagmanager.com: 1
  vimeocdn.com: 3
```
</details>

**Comment by mapx-** [comment]
> even when I am already logged in

I cannot reproduce the issue
