### ISSUE TITLE
3bmeteo.com: nuisance

### ISSUE THREAD

**Issue by enzor00** [uBlockOrigin/uAssets#19728]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.3bmeteo.com/`

### Category

[unknown]

### Description

Cookie warning comes out

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/138575369/bbc9d673-d31a-4330-896a-cab32600fd31

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 105474
 cosmetic: 91877
 scriptlet: 19352
 html: 1040
listset (total-discarded, last-updated):
 added:
  adguard-social: 21400-36, now
  adguard-cookies: 27550-35, now
 default:
  user-filters: 0-0, never
  ublock-filters: 35562-242, now
  ublock-badware: 7988-0, now
  ublock-privacy: 587-0, now
  ublock-unbreak: 2173-0, now
  ublock-quick-fixes: 274-0, now
  easylist: 70763-721, now
  easyprivacy: 33255-719, now
  urlhaus-1: 5854-0, now
  plowe-0: 3723-2, now
  ITA-0: 10540-18, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 184 ms (selfie)
 maxAssetCacheWait: 85 ms
popupPanel:
 blocked: 16
 network:
  3bmeteo.com: 2
  amazon-adsystem.com: 1
  cloudflareinsights.com: 4
  doubleclick.net: 1
  googletagmanager.com: 1
  imrworldwide.com: 2
  insurads.com: 1
  iubenda.com: 3
  outbrain.com: 1
 extended:
  ##.gpt_top
  ###adwallpaper
  ###admasthead
  ###adv_nativ_sopracartina
  ###adv_outbrain_AR_1_sottocartina
  ###ads_container
  ###admputop
  ###fb-root:not(body):not(html)
```
</details>

**Comment by stephenhawk8054** [comment]
Enable `uBlock filters – Cookie Notices` sublist under `AdGuard/uBO – Cookie Notices`
