### ISSUE TITLE
instagram.com: ads

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#19731]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.instagram.com/`

### Category

ads

### Description

Seeing ads on instagram, tested in Firefox and Opera GX with default lists

this rule from adguard work:

`instagram.com#$?#main > div div[style*="flex-direction: column;"] > article > div:has(span:contains(/(Sponsored|Gesponsert|Sponsorlu|Sponsorowane|Ispoonsara godhameera|Geborg|Bersponsor|Ditaja|Disponsori|Giisponsoran|Sponzorováno|Sponsoreret|Publicidad|May Sponsor|Sponsorisée|Oipytyvôva|Ɗaukar Nayin|Sponzorirano|Uterwa inkunga|Sponsorizzato|Imedhaminiwa|Hirdetés|Misy Mpiantoka|Gesponsord|Sponset|Patrocinado|Patrocinado|Sponsorizat|Sponzorované|Sponsoroitu|Sponsrat|Được tài trợ|Χορηγούμενη|Спонсорирано|Спонзорирано|Ивээн тэтгэсэн|Реклама|Спонзорисано|במימון|سپانسرڈ|دارای پشتیبانی مالی|ስፖንሰር የተደረገ|प्रायोजित|ተደረገ|प|प्रायोजित|স্পনসর্ড|ਪ੍ਰਯੋਜਿਤ|પ્રાયોજિત|ପ୍ରାୟୋଜିତ|செய்யப்பட்ட செய்யப்பட்ட|చేయబడినది చేయబడినది|ಪ್ರಾಯೋಜಿಸಲಾಗಿದೆ|ചെയ്‌തത് ചെയ്‌തത്|ලද ලද ලද|สนับสนุน สนับสนุน รับ สนับสนุน สนับสนุน|ကငြာ ကငြာ|ឧបត្ថម្ភ ឧបត្ថម្ភ ឧបត្ថម្ភ|광고|贊助|内容 内容|贊助|告 告|広告|സ്‌പോൺസർ ചെയ്‌തത്)/)) { height: 1px !important; visibility: hidden !important; }`

but it also remove any post that contains the word in the description

DOM; `https://appp.me/DjXGKx`

### Other extensions used

cookie editor

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/4d27e75c-c0a6-44e6-aeea-41adbbba1626)
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/f047ff88-7123-465b-abbc-286665da0d87)
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/bde4693e-835b-4f0a-a2dc-1be253bbb2d1)
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/8f8e651f-9afc-4072-817e-56d8e738fce7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 115
filterset (summary):
 network: 218743
 cosmetic: 191519
 scriptlet: 30290
 html: 0
listset (total-discarded, last-updated):
 added:
  https://github.com/AdroitAdorKhan/antipopads-re/raw/master/formats/filter.txt: 91730-0, 36m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 929-0, 36m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2262-0, 36m
  adguard-cookies: 27551-30, 36m
  adguard-mobile-app-banners: 4614-8, 36m
  adguard-other-annoyances: 13510-7, 36m
  adguard-popup-overlays: 24022-78, 36m
  adguard-social: 21400-907, 36m
  adguard-spyware: 56669-340, 36m
  adguard-spyware-url: 1208-144, 36m
  adguard-widgets: 2304-6, 36m
  easylist-annoyances: 3970-217, 36m
  [8 lists not shown]: [too many]
 default:
  user-filters: 104-0, never
  easylist: 70710-25821, 36m
  easyprivacy: 33257-16734, 36m
  plowe-0: 3723-1198, 36m
  spa-1: 5594-72, 36m
  ublock-badware: 7986-173, 36m
  ublock-filters: 34687-635, 36m
  ublock-privacy: 557-150, 35m
  ublock-quick-fixes: 282-201, 35m
  ublock-unbreak: 2128-88, 35m
  urlhaus-1: 5743-0, 35m
filterset (user): [array of 60 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 3253 ms (selfie)
 maxAssetCacheWait: 453 ms
popupPanel:
 blocked: 372
 network:
  instagram.com: 369
  facebook.com: 3
 extended:
  ###fb-root:not(body):not(html)
  ##._aagw:empty
  ##body:style(overflow: visible!important;)
  ##div[class]:has(> div[class]:first-child > a[href="/explore/peo…
  ##[class]:style(-webkit-touch-callout: default !important; -webk…
  ##+js(set-session-storage-item, loggedOutAppSheetIsMinimized, 1)
  ##+js(set-constant, _sharedData.is_whitelisted_crawl_bot, true)
  ##+js(trusted-set-cookie, ig_did, 0C826C21-17C3-444A-ABB7-EBABD3…
  ##+js(remove-class, _31e, body > ._li)
  ##+js(addEventListener-defuser, scroll, showPopup)
  ##+js(trusted-set-cookie, datr, __GMZCgwVF5BbyvAtfJojQwg, 1year,…
```
</details>

**Comment by mapx-** [comment]
I get no ads on instagram (maybe because I use it only for test)
If you have any idea how to avoid removing legit posts just comment here, otherwise I can add AG filter

**Comment by designspg** [comment]
I am also seeing ads on Firefox.

**Comment by D4niloMR** [comment]
> I get no ads on instagram

Try: `https://www.instagram.com/?variant=past_posts`

> If you have any idea how to avoid removing legit posts just comment here, otherwise I can add AG filter

All ads that show for me has a href `facebook.com/ads`, a filter can be made with this

`instagram.com#?#main > div div[style*="flex-direction: column;"] > article > div:has(a[href^="https://www.facebook.com/ads/ig_redirect/"][target="_blank"]):style(height: 1px !important; visibility: hidden !important;)`

the filter above is efficient but I don't know why it wasn't added before, I looked in the old issues and didn't see anyone mention it, maybe it's a bad selector?

`instagram.com#?#main > div div[style*="flex-direction: column;"] > article > div:has(> div:first-child:has(span:has-text(/Sponsored|Gesponsert|Sponsorlu|Sponsorowane|Ispoonsara godhameera|Geborg|Bersponsor|Ditaja|Disponsori|Giisponsoran|Sponzorováno|Sponsoreret|Publicidad|May Sponsor|Sponsorisée|Oipytyvôva|Ɗaukar Nayin|Sponzorirano|Uterwa inkunga|Sponsorizzato|Imedhaminiwa|Hirdetés|Misy Mpiantoka|Gesponsord|Sponset|Patrocinado|Patrocinado|Sponsorizat|Sponzorované|Sponsoroitu|Sponsrat|Được tài trợ|Χορηγούμενη|Спонсорирано|Спонзорирано|Ивээн тэтгэсэн|Реклама|Спонзорисано|במימון|سپانسرڈ|دارای پشتیبانی مالی|ስፖንሰር የተደረገ|प्रायोजित|ተደረገ|प|प्रायोजित|স্পনসর্ড|ਪ੍ਰਯੋਜਿਤ|પ્રાયોજિત|ପ୍ରାୟୋଜିତ|செய்யப்பட்ட செய்யப்பட்ட|చేయబడినది చేయబడినది|ಪ್ರಾಯೋಜಿಸಲಾಗಿದೆ|ചെയ്‌തത് ചെയ്‌തത്|ලද ලද ලද|สนับสนุน สนับสนุน รับ สนับสนุน สนับสนุน|ကြော်ငြာ ကြော်ငြာ|ឧបត្ថម្ភ ឧបត្ថម្ភ ឧបត្ថម្ភ|광고|贊助|内容 内容|贊助|告 告|広告|സ്‌പോൺസർ ചെയ്‌തത്/))):style(height: 1px !important; visibility: hidden !important;)`

This filter also works without removing the post with "Sponsored'" in the description, but idk if it's too heavy, and the current uBO filter does the same thing (remove the post that has the specified filter word in the description)

<details>
<summary>Screenshots</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/5aec757d-0cb6-4f77-9875-f1faf1522c75)
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/be46784a-4560-4eae-a365-7fff8deb3fb8)
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/55cf2ed9-5ea3-4dec-98b0-f4d2b6d299bd)


</details>

**Comment by mapx-** [comment]
I was able to get the ads now and your filter is working fine

**Comment by D4niloMR** [comment]
thank you

**Comment by mapx-** [comment]
try

`||scontent.cdninstagram.com/v/t50$xhr`

**Comment by mapx-** [comment]
it seems to be ok

**Comment by designspg** [comment]
I am seeing ads on instagram again.
https://www.instagram.com/
![Screen Shot 2023-11-16 at 10 40 23 PM](https://github.com/uBlockOrigin/uAssets/assets/111537648/bb9f9246-5d33-4563-b2b5-7fe9f600a310)

**Comment by D4niloMR** [comment]
Me too.

<details>
<summary>Sponsored:</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/328c6c35-ee03-4991-9887-95a9858eb041)

</details>

<details>
<summary>Normal post:</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/82cc8d5f-7ba5-4c4f-a984-8a388fd43eba)

</details>

After `span[style="line-height: var(--base-line-clamp-line-height); --base-line-clamp-line-height: 16px;"]` on normal posts, it has a `[href]` or just nothing after: 
<details>
<summary>Screenshot</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/faf1720b-b799-4085-9fe0-dc5a6f8e09c6)

</details>

But in sponsored posts, it has this sequence: `span[style="line-height: var(--base-line-clamp-line-height); --base-line-clamp-line-height: 16px;"] > div > span > svg > use` 


This filter works to me:

```
instagram.com#?#main > div div[style*="flex-direction: column;"] > article > div:has(>div:first-child span[style="line-height: var(--base-line-clamp-line-height); --base-line-clamp-line-height: 16px;"] > div > span > svg > use):remove()
```

Can be this also:
`instagram.com#?#main > div div[style*="flex-direction: column;"] > article > div:has(>div:first-child a[href*="/?enable_persistent_cta="]):remove()`


This filter no longer seems to be working:

`instagram.com#?#main > div > section div[style*="flex-direction: column;"] > article > div:has(span:has-text(/Anzeige|Gesponsert|Sponsored|Geborg|Maksettu kumppanuus|Sponzorováno|Sponsoreret|Χορηγούμενη|Publicidad|Sponsoroitu|Sponsorisé|Bersponsor|Sponsorizzato|広告|광고|Ditaja|Sponset|Gesponsord|Sponsorowane|Patrocinado|Реклама|Sponsrad|ได้รับการสนับสนุน|May Sponsor|Sponsorlu|赞助内容|贊助|প্রযোজিত|પ્રાયોજિત|स्पॉन्सर्ड|Sponzorirano|ಪ್ರಾಯೋಜಿತ|സ്‌പോൺസർ ചെയ്‌തത്|पुरस्‍कृत|प्रायोजित|ਪ੍ਰਾਯੋਜਿਤ|මුදල් ගෙවා ප්‍රචාරය කරන ලදි|Sponzorované|விளம்பரதாரர்கள்|స్పాన్సర్ చేసింది|Được tài trợ|Спонсорирано|Commandité|Sponsorizat|Спонзорисано/)):style(height: 1px !important; visibility: hidden !important;)`

**Comment by D4niloMR** [comment]
@designspg Can you test this filter?

`instagram.com#?#main > div div[style*="flex-direction: column;"] > article > div:has(>div:first-child span[style="line-height: var(--base-line-clamp-line-height); --base-line-clamp-line-height: 16px;"] > div > span > svg > use):style(border: 2px dotted red !important;)`

**Comment by designspg** [comment]
It put a red dotted line around the "sponsored post" which looks to be your intent?


     On Friday, November 17, 2023 at 01:47:18 PM CST, D4niloMR ***@***.***> wrote:  
 
 


@designspg Can you test this filter?

instagram.com#?#main > div div[style*="flex-direction: column;"] > article > div:has(>div:first-child span[style="line-height: var(--base-line-clamp-line-height); --base-line-clamp-line-height: 16px;"] > div > span > svg > use):style(border: 2px dotted red !important;)

**Comment by D4niloMR** [comment]
`instagram.com#?#main > div div[style*="flex-direction: column;"] > article > div:has(>div:first-child a[href*="/?enable_persistent_cta="]):remove()`

`instagram.com#?#main > div div[style*="flex-direction: column;"] > article > div:has(>div:first-child span[style="line-height: var(--base-line-clamp-line-height); --base-line-clamp-line-height: 16px;"] > div > span > svg > use):remove()`

I still can see some ads. Will any of these or a better filter be implemented? sorry but this is a high traffic site so the sooner the better.

**Comment by mapx-** [comment]
if you use instagram and getting ads .. you could propose a PR
