### ISSUE TITLE
[nsfw] vofomovies.info: nuisance

### ISSUE THREAD

**Issue by RedXFlawless** [uBlockOrigin/uAssets#19737]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vofomovies.info/Watch?id=21341HD264x7s/Jawan/`

### Category

nuisance

### Description

There are some images that are NSFW on the webpage that are not not being blocked

### Other extensions used

no other extensions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 99298
 cosmetic: 39548
 scriptlet: 18354
 html: 1040
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35491-230, now
  ublock-badware: 7988-0, now
  ublock-privacy: 588-0, now
  ublock-unbreak: 2179-0, now
  ublock-quick-fixes: 284-0, 2m
  easylist: 70799-710, now
  easyprivacy: 33258-718, now
  urlhaus-1: 5743-0, now
  plowe-0: 3723-2, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3184 ms (selfie)
 maxAssetCacheWait: 1205 ms
popupPanel:
 blocked: 10
 network:
  deductionkeepingbabysitter.com: 1
  effectivecreativeformat.com: 1
  googletagmanager.com: 1
  highcpmrevenuegate.com: 2
  highrevenuegate.com: 4
  profitabledisplayformat.com: 1
 extended:
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-on-property-write, DoodPop)
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

**Comment by mapx-** [comment]
add

```
vofomovies.info##a13:has-text( Ad)
vofomovies.info##a[href="https://futaonfemale.com"]
```
