### ISSUE TITLE
play.pokemonshowdown.com: detection

### ISSUE THREAD

**Issue by spooky08** [uBlockOrigin/uAssets#19738]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.pokemonshowdown.com/`

### Category

detection

### Description

i cannot connect to the game servers because every time i try to connect ot kicks me off and says ive been disconected

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

https://github.com/uBlockOrigin/uAssets/assets/145023397/65367b98-c7cd-4ce7-a678-2201f3eaff23

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 92d.22h.21m
Chromium: 112
filterset (summary):
 network: 99030
 cosmetic: 39512
 scriptlet: 18472
 html: 0
listset (total-discarded, last-updated):
 added:
  https://04f11f8a-4b35-4d7c-963b-958380b6d250.id.repl.co/microwavium/main: 129-18, 3d.32m
 default:
  user-filters: 3-0, never
  easylist: 70414-13, 3d.31m
  easyprivacy: 33248-63, 3d.33m
  plowe-0: 3725-1071, 8d.1h.23m
  ublock-badware: 7956-146, 3d.30m
  ublock-filters: 34505-129, 3d.29m
  ublock-privacy: 547-6, 1h.7m
  ublock-quick-fixes: 284-39, 1h.6m
  ublock-unbreak: 2129-32, 3d.28m
  urlhaus-1: 5743-0, 1h.5m
filterset (user): [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 10420 ms
 maxAssetCacheWait: 2405 ms
popupPanel:
 blocked: 3
 network:
  enthusiastgaming.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(pin)
```
</details>

**Comment by peace2000** [comment]
How did you figure out that this issue is caused by uBO? How that issue can be reproduced?

Does it work if you disable this?

`https://04f11f8a-4b35-4d7c-963b-958380b6d250.id.repl.co/microwavium/main`

Works normally on my end.

**Comment by mapx-** [comment]
> `##+js(pin)`

reset to default settings and test again
