### ISSUE TITLE
The :if function not working with :style filter

### ISSUE THREAD

**Issue by ddddanil** [uBlockOrigin/uAssets#1973]
### URL where the issue occurs

9anime.tv [Probably NSFW]
Though this issue is not site specific, rather than this site is an example where this issue could be found.
Examples of specific pages are given later.

### Describe the issue

The `:if` function does not work with `:style` to make a conditional injection, or rather I couldn't at all find a way to make them work either via manuals, googling or trying different combinations myself.
My best bet would be this:
```9anime.*###main:if-not(:xpath(//div[@id="sidebar"]/div[@class="widget simple-film-list"]):style(padding-right:0px!important;)```
A lot of explanation is done in Notes.

### Versions

- Browser/version: Vivaldi 1.14.1077.60 (Stable channel) (64-bit)
- uBlock Origin version: v1.15.24

### Settings

- `Hide placeholders for blocked elements`

### Notes

Firstly, I did not find any aid regarding usage of the `:if` function with other functions. My intention was to apply a `:style` if a condition is met. 
To give you some clues, `#main` and `#sidebar` are two columns, separated by the sidebar using a fixed width, and main compensating for it with padding-right. The unresponsiveness of this design leads to some complications in rendering. The sidebar contains either [only ads](https://www.9anime.tv/watch/is-the-order-a-rabbit-dear-my-sister.rkvo) or [ads + content](https://www4.9anime.is/watch/seitokai-yakuindomo.nknn), so my intention was to either completely block it and cancel the padding so the content would be centered, or just block the ads and leave everything as it is.
The filters were:
```
9anime.*###main:if-not(:xpath(//div[@id="sidebar"]/div[@class="widget simple-film-list"]):style(padding-right:0px!important;)  // This one forces padding if content inside the sidebar wasn't found
9anime.*##.widget.crop  // This one block the ads, making the sidebar an empty element
```

But no matter how I try to form the first line, the `:style` either always applies (forward posititon) or does not take any effect (trailing position). I would expect it to work either way, along the logic of 1) trying to select the `:style` function with an `:if` in `_element_:style(...):if(...)` configuration, or 2) trying to select the element with an `:if` and attempt to apply the `:style` in `_element_:if(...):style(...)` configuration.
I recon this issue lies in indetailed documentation for less common use cases and somebody could find a mishap in my filter, or point out that this is impossible.

**Comment by ddddanil** [comment]
@gorhill 
Ok, nothing to argue about there.
Still wondering how could I resolve this problem.

**Comment by gorhill** [comment]
Note that I am opened to support this, but this will have to be to solve actual filter issues. I chose to not go as far in the current implementation in order to not over-complicate the code unless there are good reasons to do so.

**Comment by ddddanil** [comment]
As I now see it, the `:if` function blocks the element right away, rather than returning a particular selector or nil. The latter would enable filters to have full-fledged conditionals in them, but filter syntax is no programming language and shouldn't be.
I see that one of the goals is to keep this extension lightweight and simple, so you wouldn't make any substantial changes at this point, especially just for one use case.
Sorry for the stupid problem I brought up.
