### ISSUE TITLE
footoks.online: detection

### ISSUE THREAD

**Issue by pubct** [uBlockOrigin/uAssets#19748]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Detection

### URL(s) where the issue occurs.

`https://footoks.online/`
`https://footoks.online/formula-1-2023-singapore-gp/`

### uBO version

1.52.0

### Browser name and version

Chrome 117.0.5938.63

### Settings

x

**Comment by BlazeFTL** [comment]
`footoks.online##+js(acis, eval, replace)`

**Comment by pubct** [comment]
That's some username you have there, Supreme Leader.
Doesn't seem to work after I pasted that line into My Filters though.

**Comment by BlazeFTL** [comment]
@pubct NVM Fixed Update Your Filters
My Fix Still Works For Me...
