### ISSUE TITLE
spanishdict.com: detection

### ISSUE THREAD

**Issue by tforman** [uBlockOrigin/uAssets#19744]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

spandict.com creates a pop up that either tells you to allow ads or subscribe to premium, or 3 free web pages to browse. 

### URL(s) where the issue occurs.

`https://www.spanishdict.com/`

### Screenshot(s)

<img width="1812" alt="Screen Shot 2023-09-14 at 6 55 06 PM" src="https://github.com/uBlockOrigin/uAssets/assets/26236712/f1bad9d1-fa39-49fa-bde6-98bfe9d494f0">

### uBO version

1.52.0

### Browser name and version

Mozilla firefox 117.0.1

### Settings

none

**Comment by stephenhawk8054** [comment]
Can you test if this causes any breakages?

```adb
spanishdict.com##+js(set-local-storage-item, sd_total_pageviews, $remove$)
```

**Comment by dportvine** [comment]
`spanishdict.com##.ReactModal__Overlay--after-open:has-text(/Premium|Try 7 days/)`  ~> **uBlock filters – Annoyances**
`spanishdict.com##.ReactModal__Overlay--after-open:has(iframe[srcdoc], img):has-text(signing up)`  ~> **uBlock filters – Annoyances**


>`spanishdict.com##+js(set-local-storage-item, sd_total_pageviews, $remove$)`

Works for me.

**Comment by stephenhawk8054** [comment]
How about this?

```adb
spanishdict.com##+js(set, SD_IS_BLOCKING, false)
```
