### ISSUE TITLE
teltarif.de: ads

### ISSUE THREAD

**Issue by kaechele** [uBlockOrigin/uAssets#19745]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.teltarif.de/`

### Category

ads

### Description

Page delivers some JS disguised as an image URL (`https://www.teltarif.de/img/smartphone/apple/iphone.jpg`) which then goes ahead and injects ads served as first-party images and other HTML subdocuments embedded in the regular page folder structure. Seems to be an AdDefend feature.
Example URL loaded: `https://www.teltarif.de/img/arch/kw26/rampe-office-tackle-deliciousIp77r.jpg`
These URLs may present to the browser as HTML subdocuments, 2x2 png pixels or actual JPEG ads.

Confirmed that the suggested filter of
`||www.teltarif.de/img/smartphone/apple/iphone.jpg$script,domain=www.teltarif.de`
blocks the ads for me.

### Other extensions used

This issue doesn't interact with any of my other extensions.

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/454490/9ee8b203-d086-41f9-94e8-b19e585a276d)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 126295
 cosmetic: 147815
 scriptlet: 41658
 html: 1228
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_6_German/filter.txt: 14040-288, 21m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72054-769, 21m
  adguard-generic: 74158-5591, 21m
  ublock-annoyances: 5422-7, 21m
  DEU-0: 7068-7066, 21m
 default:
  user-filters: 1-0, never
  ublock-filters: 35500-166, 21m
  ublock-badware: 7986-0, 21m
  ublock-privacy: 588-0, 21m
  ublock-unbreak: 2179-0, 21m
  ublock-quick-fixes: 161-1, 21m
  easylist: 70843-723, 21m
  easyprivacy: 33260-731, 21m
  urlhaus-1: 5677-0, 21m
  plowe-0: 3723-2, 21m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11093 ms (selfie)
 maxAssetCacheWait: 929 ms
popupPanel:
 blocked: 13
 network:
  teltarif.de: 11
  consentmanager.net: 2
 extended:
  ##.tgtLink
  ###LxShop
  ###SpaceRectangle
  ###SpaceTgtLink
  ###ttParallaxcontainer
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##.adSide
  #@#[id^="google_ads_iframe"]
```
</details>

**Comment by JobcenterTycoon** [comment]
@khrin `teltarif.de/img/smartphone/apple/iphone.jpg` could be blocked by EL germany.

**Comment by mapx-** [comment]
yavli crap
