### ISSUE TITLE
primewire.is

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#1974]
### URL(s) where the issue occurs

https://www.reddit.com/r/Piracy/comments/88fkx3/is_anyone_experiencing_weird_redirects_with/?st=jfwo1gjt&sh=100679da

### Describe the issue

> All the links redirect to garbage pages. For example the page for this episode of Harrow loads fine,
> 
> `http://www.primewire.is/tv-2810784-Harrow/season-1-episode-4`
> 
> but when I click the link for openload or any other website, it takes me to an obvious fake page through a string of redirects.

(Potentially malicious?) redirects

**Comment by mapx-** [comment]
`WARNING: DO NOT USE THE SITE RIGHT NOW!`
https://www.facebook.com/Primewire/

**Comment by terrorist96** [comment]
https://www.facebook.com/notes/primewire/primewire-facebook/670716773132259

```
This is a private page. We have no affiliation with the staff or owner of primewire.
I have no contact with them or the ability to contact the owner. 
this page was created to help those in need with some technical issues which pop up on the site.
we have been running strong since 2013. this page has remained while primewire has
gone through 4 personal facebook pages. 
```

**Comment by mapx-** [comment]
However, every link is pointing out to some fake page

**Comment by uBlock-user** [comment]
Hmmm, all video links are linking to potentially malicious domains. Avoid the entire domain or block it for good.

**Comment by uBlock-user** [comment]
Would it work if you whitelist `CoinHive` ? I think they integrated CH.

**Comment by ghajini** [comment]
`https://www.primewire.li/tv/12/watch-homeland-season-4-episode-10`

Clicking on `direct` (**1st visit**)under `upstream.to` link results in ads and not the actual page by upstream

**Comment by ghajini** [comment]
Does it work firefox desktop browser /opera?

**Comment by mapx-** [comment]
yep, chrome is ok, FF + opera other behaviour

try
```
primewire.*#@#+js(window.open-defuser)
*$popunder,domain=primewire.li
```

**Comment by ghajini** [comment]
Can we know exact reason why it doesn't work on firefox. ..is it browser limitation? Can we ping gorhill?

**Comment by mapx-** [comment]
maybe chrome activated other protections against redirections (even disabling it in settings it seems chrome is protecting against such crap)

**Comment by ghajini** [comment]
Would you give userscript version for me for such sites ?, 
I don't like exception of window open defuser scriptlet for such sites

**Comment by mapx-** [comment]
I'll replace open-defuser with popunder

**Comment by mapx-** [comment]
maybe this 1 will fix the issue for all browsers and the popunder will be killed
test
`primewire.*##+js(aeld, , exoJsPop101)`

**Comment by ghajini** [comment]
Great fix @mapx-

**Comment by ghost** [comment]
On `https://primewire.mov/movie/1505905-predator-badlands` clicking on the player will open a pop-under.

<img width="1919" height="492" alt="Image" src="https://github.com/user-attachments/assets/8cdb8dad-b2cd-452b-8988-324a8f2d6f50" />

**Comment by playonevideo** [comment]
On `https://primewire.mov/movie/1445002-avatar-aang-the-last-airbender` when you first click the play button, it wants to open a popup, and then, after the player loaded, it asks you to click for 3 ads, each time when you click, it tries again to open popups.

<img width="840" height="502" alt="Image" src="https://github.com/user-attachments/assets/8bc4e0e1-a0e0-4021-9702-a9131b1fd41b" />

**Comment by playonevideo** [comment]
On `https://primewire.mov/tv/83675/the-oprah-winfrey-show-season-1-episode-2` if I click the play button, it opens a popup.

**Comment by playonevideo** [comment]
> On `https://primewire.mov/tv/83675/the-oprah-winfrey-show-season-1-episode-2` if I click the play button, it opens a popup.

Popups again.

**Comment by stephenhawk8054** [comment]
I can't reproduce.

**Comment by playonevideo** [comment]
Popups on `https://primewire.mov/tv/46472/masterchef-australia-season-1-episode-1` if you click the play button for two times.

**Comment by playonevideo** [comment]
I  don't know if that's intended, but the page from the popup somehow still covers the player after the first click:

<img width="1257" height="404" alt="Image" src="https://github.com/user-attachments/assets/917b18c2-2b17-4b31-ba92-0d1ef571d9b5" />
<img width="1181" height="802" alt="Image" src="https://github.com/user-attachments/assets/1297ec4c-7bd8-4e8e-82b2-158730fac1f2" />
