### ISSUE TITLE
empire-streaming.app: breakage

### ISSUE THREAD

**Issue by Kris-Tofe** [uBlockOrigin/uAssets#19749]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://empire-streaming.app/film/Sentinelle-en-streaming-hd/694909257471b4178d6d1489681e67f6`

### Category

breakage

### Description

A message tells me that my connection is not recognized and the movie won't start.
This movie launches correctly if uBO is not activated.
I use uBO with edge on W11

- choose with ads
- choose version 
- choose the server

Thanks for your help

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d'écran 2023-09-15 102956](https://github.com/uBlockOrigin/uAssets/assets/138688963/4a91e82c-42fc-4f6d-a9c9-5b63748f7c8d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 117916
 cosmetic: 48598
 scriptlet: 18558
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 28319-38, now
  easylist: 70826-44, now
  easyprivacy: 33258-334, now
  plowe-0: 3723-1080, now
  ublock-badware: 7984-161, now
  ublock-filters: 34620-205, now
  ublock-privacy: 558-7, now
  ublock-quick-fixes: 161-66, now
  ublock-unbreak: 2131-36, now
  urlhaus-1: 5677-0, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 624 ms (selfie)
 maxAssetCacheWait: 309 ms
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  ptaupsom.com: 1
  seeip.org: 1
 extended:
  ###donation
  ###msg_ads
  ##+js(set-constant, navigator.brave, undefined)
  ##+js(no-xhr-if, pagead2.googlesyndication.com)
  ##+js(no-window-open-if)
  ##+js(replace-node-text, script, /data: \[.*\]\,/, data: []\,, c…
  ##+js(nano-setTimeout-booster, (!1), *)
```
</details>

**Comment by stephenhawk8054** [comment]
Caused by `||seeip.org^$third-party` in EP

```adb
@@||ipv4.seeip.org/jsonip$xhr,domain=empire-streaming.app
```

@ryanbr
