### ISSUE TITLE
amazon.com.tr: ads

### ISSUE THREAD

**Issue by xqtp** [uBlockOrigin/uAssets#19750]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.amazon.com.tr/s?k=metal+kalemlik&crid=2LQA9INEZ1TKY&sprefix=%2Caps%2C190&ref=nb_sb_ss_recent_1_0_recent`

### Category

ads

### Description

Steps to reproduce:

Do a search using the term `Metal kalemlik`

### Other extensions used

Bitwarden
Simple Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/103899764/3bd98ec0-c552-48f4-9139-e13c7c166956)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 117
filterset (summary):
 network: 101033
 cosmetic: 49959
 scriptlet: 19882
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13650-10, 2m
  easylist: 70827-30, 1m
  easyprivacy: 33258-68, 1m
  plowe-0: 3723-1069, 1m
  ublock-badware: 7986-146, 1m
  ublock-filters: 34618-137, 1m
  ublock-privacy: 558-6, 1m
  ublock-quick-fixes: 161-66, 1m
  ublock-unbreak: 2131-33, now
  urlhaus-1: 5677-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1382 ms
 maxAssetCacheWait: 287 ms
popupPanel:
 blocked: 41
 network:
  amazon.com.tr: 25
  amazon-adsystem.com: 1
  amazon.com: 13
  d1lxz4vuik53pc.cloudfront.net: 2
 extended:
  ##.AdHolder
  ###nav-swmslot
  ##.amzn-safe-frame-container
  ##div[cel_widget_id^="LEFT-SAFE_FRAME-"]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
amazon.com.tr##.s-result-list > .a-section:has(.sbv-ad-content-container)
```

@ryanbr
