### ISSUE TITLE
thegatewaypundit.com: breakage

### ISSUE THREAD

**Issue by PlayThatMusic** [uBlockOrigin/uAssets#19759]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.thegatewaypundit.com/2023/09/gop-rep-keith-self-warns-looming-government-shutdown/`

### Category

breakage

### Description

Affected Website:  **https://www.thegatewaypundit.com/**

1) The twitter Video/Post frames do not load in the articles on this webpage when uBlock Origin is activated for this site.  It just shows the link to that Twitter Video/Post.  The Video/Post frames do load when uBlock Origin is disabled for this site.

2) The Commenting section at the bottom of each article does does not load/show when uBlock Origin is activated for this site, but the Commenting section does load/show when uBlock Origin is disabled for this site.

**Thanks for your time and efforts in looking into this issue, which I believe started a couple of weeks ago.**

### Other extensions used

Take Webpage Screenshots Entirely - FireShot
Save as Shortcut 4.65.1945
Read Aloud: A Text to Speech Voice Reader 2.4.0
Google Translate 2.0.13
Blank New Tab Page 1.0.5

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

**Web Address:** https://www.thegatewaypundit.com/2023/09/update-dangerous-fugitive-danelo-cavalcante-captured-after-two/

**With uBlock Origin disabled for this site:**
![image](https://github.com/uBlockOrigin/uAssets/assets/7770435/4007e209-c3d4-4320-a7a3-05fb5c533be5)
![image](https://github.com/uBlockOrigin/uAssets/assets/7770435/417a5b07-a799-41ba-9ac8-a7a752ea3a4b)

**With uBlock Origin enabled for this site:**
![image](https://github.com/uBlockOrigin/uAssets/assets/7770435/b36da149-3f52-433e-af90-46a4e21bb5b8)
![image](https://github.com/uBlockOrigin/uAssets/assets/7770435/8728f139-fd0a-4934-894d-4f03e3acf886)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 99273
 cosmetic: 39593
 scriptlet: 18422
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 70910-11, 1m
  easyprivacy: 33242-63, 1m
  plowe-0: 3720-1068, 1m
  ublock-badware: 7984-146, 1m
  ublock-filters: 34589-131, 1m
  ublock-privacy: 559-6, 1m
  ublock-quick-fixes: 160-62, 26m
  ublock-unbreak: 2131-32, 1m
  urlhaus-1: 5659-0, 1m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 11 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1233 ms (selfie)
 maxAssetCacheWait: 610 ms
popupPanel:
 blocked: 14
 network:
  thegatewaypundit.com: 5
  freedomadnetwork.com: 1
  googleoptimize.com: 1
  mixi.media: 1
  revcontent.com: 2
  ruamupr.com: 1
  scribblestring.com: 1
  stakingsmile.com: 1
  statcounter.com: 1
 extended:
  ##.adcovery
  ##.adcovery-postbelow-01
  ##.code-block
  ##[data-rc-widget]
  ##div[id^="rc-widget-"]
  ##+js(abort-on-stack-trace, Math.random, injectedScript)
  ##+js(abort-on-property-read, adtoniq)
```
</details>

**Comment by PlayThatMusic** [comment]
Hello,

At the bottom of the page of my Issue (19759) I found this: [mapx-](https://github.com/mapx-) closed this as [completed](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/uBlockOrigin/uAssets/commit/38a66f5dc3c43a0b9b9218fa287f140d18a9ed3e [6 hours ago](https://github.com/uBlockOrigin/uAssets/issues/19759#event-10390275032).

I clicked on the **38a66f5** link, click 'View file' and then downloaded filters.txt file.

I then went to uBlock Origin settings.  Clicked on the 'My filters' tab, clicked 'Import and append' and imported the filters.txt file I had just downloaded.  I restarted thegatewaypundit.com website, but it seems to still have the same issues. 

Is there something I missed?

Thanks,
David.

**Comment by stephenhawk8054** [comment]
@PlayThatMusic You don't need to import anything. Force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.

**Comment by PlayThatMusic** [comment]
Wow, Perfect!  
Thank You Very Much mapx and stephenhawk8054!  
You guys are the Awesome!
