### ISSUE TITLE
naver.com: ads

### ISSUE THREAD

**Issue by harmonicon** [uBlockOrigin/uAssets#19756]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.naver.com/`

### Category

ads

### Description

It's Korean site.
I couldn't delete the news section(blue box) and ads section(red box) using uBO's "thunder-shaped button" function for a few months.
When I refresh the site, they appear again.

Expectation:
The news & ads sections not appearing again "only" when selecting them with the "thunder-shaped button" function.
(because some might still want to keep them undeleted)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshot](https://github.com/uBlockOrigin/uAssets/assets/142132926/236f0797-bf7d-4429-9dcd-7444ef184b52)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 100381
 cosmetic: 42702
 scriptlet: 18545
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  KOR-1: 4541-10, 1m
  easylist: 70878-50, 1m
  easyprivacy: 33256-73, 1m
  plowe-0: 3720-1083, 1m
  ublock-badware: 7984-146, 1m
  ublock-filters: 34581-134, 1m
  ublock-privacy: 558-8, 1m
  ublock-quick-fixes: 160-61, 1m
  ublock-unbreak: 2131-33, 1m
  urlhaus-1: 5567-0, 1m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2133 ms
 maxAssetCacheWait: 905 ms
popupPanel:
 blocked: 5
 network:
  naver.com: 2
  pstatic.net: 3
 extended:
  ##.ad_area
  ##a[class*="_banner_"]
  ##div[class*="_banner_"]
  ##div[id^="veta_"]
  ###root div[class^="Layout-module__content_"]:has(iframe[src^="h…
  ##div[class^="Layout-module__content_area_"]:has(> div[class*="_…
  ##+js(set-constant, getAdcrUrl, )
```
</details>

**Comment by mapx-** [comment]
what if you add

`naver.com###newsstand`

**Comment by harmonicon** [comment]
News section disappeared. Thanks.
And, How do I delete the red box below?

**Comment by mapx-** [comment]
I do not see that section, however better reporting / asking help at List-KR repository

https://github.com/List-KR/List-KR/issues
