### ISSUE TITLE
ikea.com: breakage

### ISSUE THREAD

**Issue by edelberry** [uBlockOrigin/uAssets#19751]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ikea.com/us/en/order/delivery/`

### Category

breakage

### Description

Page flashes then turns mostly blank. Turning off EasyPrivacy solves the issue. 

Why is this a required question, if I'm reporting a filter issue? "I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists. *"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/109927474/0d40f61a-e09a-4ee0-90d2-ec31e56a7bd7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 108815
 cosmetic: 168136
 scriptlet: 28461
 html: 1228
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72054-764, 2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93374-21797, 2m
  ublock-annoyances: 5422-7, 2m
 default:
  user-filters: 30-0, never
  ublock-filters: 35506-92, 2m
  ublock-badware: 7986-1, 2m
  ublock-privacy: 588-0, 2m
  ublock-unbreak: 2179-0, 2m
  easylist: 70872-713, now
  easyprivacy: 33255-718, now
  urlhaus-1: 5742-0, 43m
  plowe-0: 3720-3, 2m
  ublock-quick-fixes: 161-1, 42m
filterset (user): [array of 30 redacted]
trustedset:
 added: [array of 9 redacted]
 removed:
  about-scheme
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 732 ms
 maxAssetCacheWait: 356 ms
popupPanel:
 blocked: 15
 network:
  ikea.com: 11
  optimizely.com: 2
  sentry.io: 2
```
</details>

**Comment by mapx-** [comment]
Can you reproduce the issue only logged in ? or even logged off ?

**Comment by edelberry** [comment]
Only tested checking out as guest

------- Original Message -------

**Comment by mapx-** [comment]
I cannot reproduce the issue

uBO on / off:

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/42be0f9e-ef7b-4b94-9e5e-0e93a697e705)

**Comment by edelberry** [comment]
ok, must be other setting that when combined with uBO causes the issue. I'll just temporarily turn off EasyPrivacy

**Comment by mapx-** [comment]
well, no steps were provided to get the issue
