### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by tembhub** [uBlockOrigin/uAssets#19757]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

breakage

### Description

only shows grey boxes when uBO is enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1920" alt="YT_uBO_fail" src="https://github.com/uBlockOrigin/uAssets/assets/145199174/5bc798fd-c0fc-4473-9561-bebe614faec1">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 99127
 cosmetic: 39550
 scriptlet: 18393
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70878-11, 11m
  easyprivacy: 33256-63, 11m
  plowe-0: 3720-1068, 11m
  ublock-badware: 7984-146, 11m
  ublock-filters: 34583-131, 11m
  ublock-privacy: 558-6, 11m
  ublock-unbreak: 2131-32, 11m
  urlhaus-1: 5567-0, 11m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 333 ms (selfie)
 maxAssetCacheWait: 60 ms
popupPanel:
 blocked: 2
 network:
  youtube.com: 2
 extended:
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
Are you the user here: https://www.reddit.com/r/uBlockOrigin/comments/16fmkkv/youtube_antiadblock_and_ads_september_11_2023/k0tkdlc/ ?

**Comment by tembhub** [comment]
yes, i misread your post and made a bug report first. sorry.

**Comment by stephenhawk8054** [comment]
Please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

Are you using any other extensions?
