### ISSUE TITLE
economictimes.indiatimes.com: detection

### ISSUE THREAD

**Issue by mayankleoboy** [uBlockOrigin/uAssets#19766]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://economictimes.indiatimes.com/news/new-updates/female-reporter-groped-during-live-tv-coverage-in-madrid/articleshow/103708511.cms`

### Category

detection
<img width="948" alt="Screenshot 2023-09-18 080631" src="https://github.com/uBlockOrigin/uAssets/assets/12293006/4bec2341-7faf-480e-8062-c075c273532b">

### Description

ublock detected on the page

### Other extensions used

none that block ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 119
filterset (summary):
 network: 354779
 cosmetic: 239138
 scriptlet: 44080
 html: 1230
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72059-72059, 26m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 37705-5677, 19m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt: 56309-3214, 2m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7256-0, 2m
  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 22m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93346-93335, 2m
  https://winhelp2002.mvps.org/hosts.txt: 8729-3, 2m
  https://www.fanboy.co.nz/enhancedstats.txt: 2771-7, 2m
  adguard-generic: 74212-7195, 25m
  adguard-mobile: 8634-153, 28m
  adguard-spyware-url: 1209-80, 33m
  adguard-spyware: 56673-19589, 27m
  [21 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  ublock-filters: 35510-575, 38m
  ublock-badware: 7986-5, 35m
  ublock-privacy: 589-0, 2m
  ublock-unbreak: 2179-2, 34m
  ublock-quick-fixes: 160-0, 16m
  easylist: 70919-30754, 2m
  easyprivacy: 33247-4173, 39m
  urlhaus-1: 5676-0, 17m
  plowe-0: 3720-327, 2m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 79 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5377 ms
 maxAssetCacheWait: 1017 ms
 unsuspendAfter: 3793 ms
popupPanel:
 blocked: 41
 network:
  indiatimes.com: 4
  clmbtech.com: 1
  doubleclick.net: 1
  facebook.net: 1
  go-mpulse.net: 2
  google-analytics.com: 1
  googletagmanager.com: 2
  growthrx.in: 1
  indexww.com: 1
  mouseflow.com: 1
  scorecardresearch.com: 1
  survicate.com: 1
  tvid.in: 24
 extended:
  ###topAd
  ##.topArtAd
  ##.topAd
  ##.artShare
  ##.socialShare
  ##.share_block
  ##.shareSprite
  ##.adBox
  ##.custom_ad
  ##.colombiaAd
  ##.adsbg300
  ##.ad_block
  ##.artData > div.disclamerText
  ###scrollTop
  ##.colombia
  ##div[id*="ScriptRoot"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adsbg300:style(position: absolute!important; left: -3000px!im…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(addEventListener-defuser, mouseout)
  ##+js(abort-on-property-read, intsFequencyCap)
  ##+js(addEventListener-defuser, contextmenu)
  ##+js(no-setTimeout-if, /nltrShow30minFlag|js_primetargeting_pop…
  ##+js(no-setTimeout-if, objSubPromo)
  ##+js(set-constant, objVc.interstitial_web, )
  ##+js(set-cookie, et_interstitial_active, true)
  ##+js(nano-setTimeout-booster, updateCounter();, , 0.02)
  ##+js(addEventListener-defuser, copy)
```
</details>

**Comment by mapx-** [comment]
alternative:

```
economictimes.indiatimes.com##.adblocker_popup
economictimes.indiatimes.com##.popupbgLayer
economictimes.indiatimes.com##body:style(overflow: auto !important;)
```
