### ISSUE TITLE
agf1880fodbold.dk: ads

### ISSUE THREAD

**Issue by AenderErSeje** [uBlockOrigin/uAssets#19769]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.agf1880fodbold.dk/`

### Category

ads

### Description

there are ads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 99206
 cosmetic: 39620
 scriptlet: 18498
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70878-11, now
  easyprivacy: 33255-63, now
  plowe-0: 3720-1068, now
  ublock-badware: 7984-146, now
  ublock-filters: 34636-134, now
  ublock-privacy: 559-6, now
  ublock-quick-fixes: 152-60, 53m
  ublock-unbreak: 2132-32, now
  urlhaus-1: 5676-0, 52m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 493 ms (selfie)
 maxAssetCacheWait: 264 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
- you didn't provide any indication on the ads (screenshot, specific page etc)
- you didn't enable the regional dk list (`Dandelion Sprouts nordiske filtre`)
- add the regional list, test again
- if you still getting ads report directly at the regional list repository => https://github.com/DandelionSprout/adfilt/issues
