### ISSUE TITLE
goodreads.com: breakage

### ISSUE THREAD

**Issue by maxnersting** [uBlockOrigin/uAssets#19765]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.goodreads.com/book/show/1166599.The_Gathering_Storm`

### Category

breakage

### Description

I am not able to view the written reviews of any title on Goodreads. I have deactivated all my other add-ons, so I am somewhat confident that uBlock Origin is causing the issue.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![billede](https://github.com/uBlockOrigin/uAssets/assets/142060788/a7bd53c8-b1d7-4b8e-8c42-0ed212ea827f)
![billede](https://github.com/uBlockOrigin/uAssets/assets/142060788/ff8c14a0-87ab-4f90-aea7-46225b9bbd2b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 100802
 cosmetic: 41711
 scriptlet: 18451
 html: 1043
listset (total-discarded, last-updated):
 default:
  user-filters: 58-7, never
  ublock-filters: 35510-94, now
  ublock-badware: 7986-1, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2181-0, now
  ublock-quick-fixes: 152-0, now
  easylist: 70919-715, now
  easyprivacy: 33252-718, now
  urlhaus-1: 5721-0, now
  plowe-0: 3720-1, now
  NOR-0: 3608-3, now
filterset (user): [array of 60 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 228 ms (selfie)
 maxAssetCacheWait: 48 ms
popupPanel:
 blocked: 43
 network:
  goodreads.com: 33
  amazon-adsystem.com: 1
  amazon.com: 7
  doubleclick.net: 1
  gr-assets.com: 1
 extended:
  ##article
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#div[id^="div-gpt-"]
  #@#[id^="google_ads_iframe"]
```
</details>

**Comment by u-RraaLL** [comment]
> ```yaml
>  extended:
>   ##article
> ```

This is the filter causing this. It's not in filter lists. Must be your personal filter. Check "My filters" and remove it.

![image](https://github.com/uBlockOrigin/uAssets/assets/92610420/7ab42f71-eaa6-485b-8005-1d5856752f83)
