### ISSUE TITLE
deezer.com: breakage

### ISSUE THREAD

**Issue by Quinss271** [uBlockOrigin/uAssets#19764]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.deezer.com/ru/`

### Category

breakage

### Description

after couple of songs it appears pop-up with error message but after close it all ok and error message from time to time appear

### Other extensions used

FoxyProxy
Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![изображение](https://github.com/uBlockOrigin/uAssets/assets/22166165/a2f6d3f1-ed4d-4e76-b887-20cb9bd170f5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 126262
 cosmetic: 206975
 scriptlet: 26628
 html: 1100
listset (total-discarded, last-updated):
 added:
  adguard-social: 21382-851, now
  adguard-cookies: 27566-58, now
  adguard-popup-overlays: 24043-1467, now
  adguard-mobile-app-banners: 4620-1062, now
  adguard-other-annoyances: 13523-256, now
  adguard-widgets: 2306-1, now
  easylist-annoyances: 3972-116, 1h.8m
  easylist-chat: 134-9, 1h.8m
  fanboy-cookiemonster: 48309-3869, 1h.8m
  easylist-newsletters: 6481-13, 1h.8m
  easylist-notifications: 2669-3, 1h.8m
  fanboy-social: 16199-11, 1h.8m
  [2 lists not shown]: [too many]
 default:
  user-filters: 18-1, never
  ublock-filters: 35437-404, now
  ublock-badware: 7986-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2181-0, now
  ublock-quick-fixes: 152-0, now
  easylist: 70888-792, now
  easyprivacy: 33252-816, now
  urlhaus-1: 5721-0, now
  plowe-0: 3720-2, now
  RUS-0: 40008-592, now
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 31 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 140 ms
popupPanel:
 blocked: 11
 network:
  deezer.com: 2
  dzcdn.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  hubvisor.io: 1
  sascdn.com: 1
  sentry.io: 4
 extended:
  ##.conversion-banner
  ##.ads-bottom
  ##.ads-top
  ##.page-ads
  ##.modal:has(> div.modal-wrapper > div.modal-dialog > div#modal_…
  ##+js(set-constant, smartLoaded, true)
  ##+js(no-setTimeout-if, Ads)
```
</details>

**Comment by mapx-** [comment]
reset uBO to default settings / lists, update then all the lists, test again
