### ISSUE TITLE
traceparts.com: breakage

### ISSUE THREAD

**Issue by risfutile** [uBlockOrigin/uAssets#19768]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.traceparts.com/de/product/marco-basicvalve?CatalogPath=TRACEPARTS%3ATP01&Product=90-30072023-063466&PartNumber=mtv%2Fdsm%2Fe`

### Category

breakage

### Description

3D Model will not load unless uBO is disabled.

### Other extensions used

Reddit Enhancement Suite :)

### Screenshot(s)

Vivaldi with uBO enabled:
https://github.com/uBlockOrigin/uAssets/assets/11488738/2777e4ef-4c12-41d6-8c97-cb377b35bd61

Vivaldi with uBO disabled:
https://github.com/uBlockOrigin/uAssets/assets/11488738/2d8dbbbb-ead4-4ad1-bf01-ba9b1fc69708

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 98
filterset (summary):
 network: 101540
 cosmetic: 44323
 scriptlet: 18498
 html: 0
listset (total-discarded, last-updated):
 added:
  DEU-0: 7070-0, now
 default:
  user-filters: 1-0, never
  easylist: 70878-17, now
  easyprivacy: 33255-72, now
  plowe-0: 3720-1069, now
  ublock-badware: 7984-146, now
  ublock-filters: 34636-148, now
  ublock-privacy: 559-6, now
  ublock-quick-fixes: 152-60, now
  ublock-unbreak: 2132-34, now
  urlhaus-1: 5676-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings:
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1035 ms (selfie)
 maxAssetCacheWait: 132 ms
popupPanel:
 blocked: 18
 network:
  traceparts.com: 7
  aticdn.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  hs-analytics.net: 1
  hs-banner.com: 1
  hsforms.com: 3
  hsleadflows.net: 1
  ioam.de: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||traceparts.com/lib/piano-analytics/piano-analytics.js$script,1p`

@ryanbr

**Comment by risfutile** [comment]
Hot damn, thank you very much!
