### ISSUE TITLE
darkino.online: detection

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#19770]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www2.darkino.online/download/12766931`

### Category

[unknown]

### Description

Accès aux liens impossible.

_Access to links impossible_

### Other extensions used

Aucune sui interfère avec le blocage de pubs.

_None that interfere with ad blocking._

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/f4d1917d-cc65-4228-8885-a4dab19e19b3)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 117
filterset (summary):
 network: 140007
 cosmetic: 113681
 scriptlet: 22755
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1649-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2263-10, now
  RUS-0: 39935-169, now
  fanboy-cookiemonster: 48313-228, now
 default:
  FRA-0: 28320-38, now
  easylist: 70878-76, now
  easyprivacy: 33255-637, now
  plowe-0: 3720-1084, now
  ublock-badware: 7984-161, now
  ublock-filters: 34636-253, now
  ublock-privacy: 559-54, now
  ublock-quick-fixes: 156-65, now
  ublock-unbreak: 2132-37, now
  urlhaus-1: 5676-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 210 ms (selfie)
 maxAssetCacheWait: 98 ms
popupPanel:
 blocked: 3
 network:
  alwingulla.com: 2
  googletagmanager.com: 1
 extended:
  ##.grecaptcha-badge
  ##+js(remove-attr, jsaction, #islsp c-wiz a[href^="http"][data-v…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
still working on my side FF / chrome, update again all the lists

**Comment by Skip75** [comment]
Same issue on my side, even after clearing cache and updating all filters again

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
