### ISSUE TITLE
virginmedia.com: breakage

### ISSUE THREAD

**Issue by CommanderLake** [uBlockOrigin/uAssets#19774]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.virginmedia.com/my-virgin-media/home`

### Category

breakage

### Description

The live chat does now show

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 115
filterset (summary):
 network: 99213
 cosmetic: 39709
 scriptlet: 18430
 html: 1042
listset (total-discarded, last-updated):
 default:
  user-filters: 110-7, never
  ublock-filters: 35524-97, now
  ublock-badware: 7986-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2180-0, now
  easylist: 70878-711, now
  easyprivacy: 33257-718, now
  plowe-0: 3720-2, now
  urlhaus-1: 5676-0, now
  ublock-quick-fixes: 158-0, now
filterset (user): [array of 110 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 197 ms (selfie)
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 11
 network:
  googletagmanager.com: 1
  optimizely.com: 10
```
</details>

**Comment by stephenhawk8054** [comment]
Do you need an account to reproduce the issue?

**Comment by CommanderLake** [comment]
No.

**Comment by stephenhawk8054** [comment]
I turned off all extensions and agreed all to the cookie consent, but I can't see where the live chat is?

https://github.com/uBlockOrigin/uAssets/assets/66517106/5eb5c882-b920-46bb-aafd-bd94549f8b9a

**Comment by mapx-** [comment]
@stephenhawk8054 I guess it's about feeback button (left side)

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/366aa606-998a-4099-a3d5-e0fd1ca5c746)

I can see it if I enable a bunch of exceptions:

```
@@||google-analytics.com/j/collect$xhr,domain=virginmedia.com
@@||googletagmanager.com/gtm.js$script,domain=virginmedia.com
@@||googletagmanager.com/gtag/js$script,domain=virginmedia.com
@@||qualtrics.com/SIE/$script,domain=virginmedia.com
```

**Comment by mapx-** [comment]
No chat button on my side too even disabling completely uBO / clearing the cookies / other storage
Maybe you didn't provide all the steps to reproduce the issue or it's a site issue.
Closing for now.

**Comment by CommanderLake** [comment]
Here try this page its a blue button that appears on the right: https://www.virginmedia.com/help/live-chat
You should see something like this when you click it...
![VM](https://github.com/uBlockOrigin/uAssets/assets/55424861/009f5372-f89d-43ad-8b4d-51cf2a95bcff)

**Comment by mapx-** [comment]
test

```
@@||googletagmanager.com/gtm.js$script,domain=virginmedia.com
@@||googletagmanager.com/gtag/js$script,domain=virginmedia.com
```

**Comment by CommanderLake** [comment]
> test
> 
> ```
> @@||googletagmanager.com/gtm.js$script,domain=virginmedia.com
> @@||googletagmanager.com/gtag/js$script,domain=virginmedia.com
> ```

That fixed it.
