### ISSUE TITLE
investmap.pl: detection

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#19777]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Soft anti-adblock in placerholder/leftover under "ad"/"ads".

### URL(s) where the issue occurs.

`https://investmap.pl/w-galerii-katowickiej-powstalo-nietypowe-miejsce-pierwsze-tego-typu-w-polsce.a303021`

### Screenshot(s)

<details>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/7c080522-8ad5-4a13-9cc2-d45b2c6fbb8b)

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/e0a3dedc-4562-4944-a3d5-82678d449ebf)

</details>

### uBO version

1.52.0

### Browser name and version

Firefox 117.0.1

### Settings

enabled uBo Annoyances and POL-0 + POL-2.

### Notes

`investmap.pl##div[class][height="300px"]`
`investmap.pl##div[class][height="250px"]`

https://github.com/MajkiIT/polish-ads-filter/issues/21991

**Comment by mapx-** [comment]
You already reported at regional list repository. Simple /classic filters.

**Comment by krystian3w** [comment]
But can by rejected by bot or fixed in 2024.

**Comment by mapx-** [comment]
If both lists are dead you could maintain a new one.
