### ISSUE TITLE
inspiredminds.de: ads

### ISSUE THREAD

**Issue by Yefusy** [uBlockOrigin/uAssets#19771]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.inspiredminds.de/tr/mehmet-%C5%9Fim%C5%9Fekin-100-g%C3%BCn%C3%BC-ekonomiye-g%C3%BCven-sa%C4%9Fland%C4%B1-m%C4%B1/a-66756779`

### Category

ads

### Description

Ad borders that didn't blocked.

`##.advertisement`

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98059187/fa02dce9-783d-42ab-9a64-750ac1d687f0)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 117
filterset (summary):
 network: 124810
 cosmetic: 167482
 scriptlet: 39011
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27573-30, now
  adguard-generic: 74262-484, now
  adguard-mobile-app-banners: 4620-9, now
  adguard-other-annoyances: 13525-7, now
  adguard-popup-overlays: 24045-71, now
  adguard-social: 21367-910, now
  adguard-widgets: 2306-3, now
  ublock-cookies-adguard: 291-4, now
 default:
  user-filters: 57-0, never
  TUR-0: 13224-9, now
  easylist: 70878-1109, now
  easyprivacy: 33255-232, now
  plowe-0: 3720-1081, now
  ublock-badware: 7984-363, now
  ublock-filters: 34636-4171, now
  ublock-privacy: 559-7, now
  ublock-quick-fixes: 156-65, now
  ublock-unbreak: 2132-95, now
  urlhaus-1: 5676-0, now
filterset (user): [array of 57 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 582 ms (selfie)
 maxAssetCacheWait: 410 ms
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##a[href^="whatsapp://send"]
  ##a[href^="fb-messenger://share"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
```
</details>

**Comment by JobcenterTycoon** [comment]
Its a multi language site so its more a case for the EasyList

**Comment by ryanbr** [comment]
I don't see an english site here, its turkish site with a .de domain.

**Comment by stephenhawk8054** [comment]
@ryanbr They have EN version. An example link: `https://www.inspiredminds.de/en/ahead-of-uns-sdg-summit-germany-calls-for-sustainable-finance/a-66738083`

**Comment by JobcenterTycoon** [comment]
Its possible to set the language: Click the hamburger menu -> Select language.

**Comment by ryanbr** [comment]
I guess so.
