### ISSUE TITLE
aniwave.to / aniwave.se: ads

### ISSUE THREAD

**Issue by GoatQuote** [uBlockOrigin/uAssets#19779]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aniwave.to/watch/bleach.6j9/ep-283`

### Category

ads

### Description

ad appears when pausing, updated filter lists and it's still appearing. can't use the element selection tool either as it seems to be a part of the video player element.

### Other extensions used

none

### Screenshot(s)

https://i.imgur.com/Pvb3hS9.png

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 117
filterset (summary):
 network: 99199
 cosmetic: 39641
 scriptlet: 18507
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 70932-11, 14m
  easyprivacy: 33259-63, 14m
  plowe-0: 3720-1068, 14m
  ublock-badware: 7984-146, 14m
  ublock-filters: 34660-134, 1h.43m
  ublock-privacy: 559-6, 14m
  ublock-quick-fixes: 172-65, 22m
  ublock-unbreak: 2132-32, 1h.42m
  urlhaus-1: 5601-0, 14m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 375 ms
 maxAssetCacheWait: 173 ms
popupPanel:
 blocked: 11
 network:
  amung.us: 1
  bidgear.com: 4
  coldvain.com: 1
  disqus.com: 1
  googletagmanager.com: 1
  sharethis.com: 2
  superherosnout.com: 1
 extended:
  ##.adx
  ##+js(abort-on-property-read, AaDetector)
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
```
</details>

**Comment by Approveo** [comment]
I'm also having the same issue. there is a add when i pause.
![Screenshot 2023-09-19 135513](https://github.com/uBlockOrigin/uAssets/assets/145434337/26a9339d-f05c-4fc4-a28e-68324eceff57)
![Screenshot 2023-09-19 135513](https://github.com/uBlockOrigin/uAssets/assets/145434337/fd3d9917-d26c-43c4-8ef6-e1bfaf7a2cd1)

**Comment by mapx-** [comment]
TRY

`vidplay.site##[href="https://flixwave.to"]:upward(3)`

**Comment by Approveo** [comment]
Not fixed for me yet. What to do?

**Comment by stephenhawk8054** [comment]
@Approveo Force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.

**Comment by Approveo** [comment]
@stephenhawk8054 thank you very much sir. It really worked for me. Thank you❤️

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/24439

**Comment by stephenhawk8054** [comment]
@RandomPersonUMet I can't reproduce the ads placeholders. Which country are you when accessing the site?

Test again in a new browser profile with only uBO and its default settings.

**Comment by RandomPersonUMet** [comment]
> @RandomPersonUMet I can't reproduce the ads placeholders. Which country are you when accessing the site?
> 
> Test again in a new browser profile with only uBO and its default settings.

@stephenhawk8054 I've tested it out in a new chrome profile with uBO (default) and in a guest profile without any extensions and the problem persists, it just may take some time to occur as the ads placeholder doesn't always appear on every page refresh and if it does there may be a 10 second delay.

Also I'm in the UK (England).

![image](https://github.com/user-attachments/assets/d12f2d08-bef3-4876-89e6-e1fec50c6bf7)

**Comment by stephenhawk8054** [comment]
@RandomPersonUMet There's no uBO in your screenshot

**Comment by biogenik** [comment]
Can confirm that when this site was hosted on .to, had no ads. But now that it's on .se, they are back. Wasn't sure if it would count as a duplicate, as it was a new domain.

**Comment by mapx-** [comment]
@biogenik I get no ad / popup on .se 

reset uBO to defaults and test again

**Comment by stephenhawk8054** [comment]
I can't reproduce either.
