### ISSUE TITLE
webstick.blog: ads

### ISSUE THREAD

**Issue by Cold-Wind1** [uBlockOrigin/uAssets#19782]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ads appearing.

### URL(s) where the issue occurs.

https://webstick.blog/gmail-vs-aol

### Screenshot(s)

![brave_screenshot_webstick blog (1)](https://github.com/uBlockOrigin/uAssets/assets/145432904/dd767afe-0d76-4c4e-b652-0f94187314dc)

### uBO version

1.52.0

### Browser name and version

Brave Browser latest version.

### Settings

I am using ublock origin with default settings.

**Comment by stephenhawk8054** [comment]
```adb
||webstick.blog/images/images-ads/
```

@ryanbr
