### ISSUE TITLE
markanthonywineandspirits.ca: breakage

### ISSUE THREAD

**Issue by ravertine** [uBlockOrigin/uAssets#19783]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.markanthonywineandspirits.ca/concoursgabbiano/`

### Category

breakage

### Description

block contest entry form

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.1b3
Firefox: 117
filterset (summary):
 network: 119124
 cosmetic: 63984
 scriptlet: 24168
 html: 1231
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 7m
  ublock-annoyances: 5420-7, 7m
  ublock-quick-fixes: 150-0, 7m
  adguard-other-annoyances: 13528-104, 7m
  easylist-annoyances: 3972-33, 7m
 default:
  ublock-filters: 35551-457, 7m
  ublock-badware: 7986-1, 7m
  ublock-privacy: 589-0, 7m
  ublock-unbreak: 2180-0, 7m
  easylist: 70921-784, 7m
  easyprivacy: 33230-729, 7m
  urlhaus-1: 5601-0, 7m
  plowe-0: 3720-1, 7m
  FRA-0: 28335-347, 7m
filterset (user): [array of 30 redacted]
trustedset:
 added: [array of 326 redacted]
switchRuleset:
 added: [array of 26 redacted]
hostRuleset:
 added: [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 180
 autoUpdatePeriod: 4
 extensionUpdateForceReload: true
 manualUpdateAssetFetchPeriod: 1
 popupPanelLockedSections: 39
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 806 ms (selfie)
 maxAssetCacheWait: 85 ms
popupPanel:
 blocked: 16
 network:
  googletagmanager.com: 1
  pinterest.com: 1
  wishpond.com: 14
 extended:
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
```
</details>

**Comment by okiehsch** [comment]
It's broken by a combination of EasyList-annoyances and Adguard-annoyances filters.
````
@@||embedded.wishpondpages.com^$subdocument,domain=markanthonywineandspirits.ca
||wishpond.com^$3p,badfilter
````
fixes the issue on my end.

The first filter is an exception for 
`||embedded.wishpondpages.com/*/?parent_url`
in `adguard-popup-overlays`
The second filter is badiltering an EasyList-annoyances filter.
@Yuki2718 
@ryanbr
