### ISSUE TITLE
gmx.com: ads

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#19784]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

blank frame of blocked ads on the right side of the gmx mail page not removing.

### URL(s) where the issue occurs.

gmx.com

### Screenshot(s)

![gmx mail](https://github.com/uBlockOrigin/uAssets/assets/145432904/70611c9c-1bc0-4e58-992e-b8f263caaae9)

### uBO version

1.52.0

### Browser name and version

Brave Browser latest version.

### Settings

default ublock settings

**Comment by stephenhawk8054** [comment]
The label is to mark the issue needs an account to reproduce.
