### ISSUE TITLE
theguardian.com: nuisance

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#19781]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Cookie notice appearing

### URL(s) where the issue occurs.

`https://www.theguardian.com/international`

### Screenshot(s)

![brave_screenshot_www theguardian com](https://github.com/uBlockOrigin/uAssets/assets/145432904/af91e614-e59c-4ca7-ac0d-ef39ca9b5895)

### uBO version

1.52.0

### Browser name and version

Brave Browser latest version

### Settings

using Ublock Annoyance filter with default settings

**Comment by stephenhawk8054** [comment]
Can you enable `EasyList – Cookie Notices` list and test again?
