### ISSUE TITLE
surfline.com: detection

### ISSUE THREAD

**Issue by mrtonimendes** [uBlockOrigin/uAssets#19787]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.surfline.com/`

### Category

detection

### Description

The website displays a an anti-adblocker

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot from 2023-09-19 14-51-16](https://github.com/uBlockOrigin/uAssets/assets/92183254/11c94d0e-ce6e-42c9-aaff-d6a668164d2b)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 100571
 cosmetic: 43334
 scriptlet: 18820
 html: 1043
listset (total-discarded, last-updated):
 added:
  spa-1: 5599-10, now
 default:
  user-filters: 1-0, never
  ublock-filters: 35545-109, now
  ublock-badware: 7992-1, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2180-0, now
  ublock-quick-fixes: 147-0, now
  easylist: 70921-754, now
  easyprivacy: 33230-732, now
  urlhaus-1: 5601-0, 1h.45m
  plowe-0: 3720-1, now
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 221 ms (selfie)
 maxAssetCacheWait: 86 ms
popupPanel:
 blocked: 14
 no-popups: true
 network:
  appsflyer.com: 1
  blogherads.com: 3
  cloudflareinsights.com: 2
  duckduckgo.com: 2
  googletagmanager.com: 2
  lr-in-prod.com: 1
  newrelic.com: 2
  segment.com: 1
 extended:
  ##.quiver-google-dfp
  ##+js(set-constant, __BACKPLANE_API__.renderOptions.showAdBlock,…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
surfline.com##+js(nostif, nrWrapper)
```

For me the video/animation at home page can't play.

**Comment by mrtonimendes** [comment]
> surfline.com##+js(nostif, nrWrapper)

No difference, still blocked

**Comment by stephenhawk8054** [comment]
```adb
surfline.com#@#.ad-box:not(#ad-banner)
```

This works for me. If you still see anti-adb, check if you are using any:

- Custom filters / filter lists,
- Other extensions,
- Browser's built-in blocker,
- DNS / VPN / Pi-hole blocking methods,
- Blocking apps/softwares outside browser,
- OS' hosts file to block domains.

**Comment by mrtonimendes** [comment]
> ```
> surfline.com#@#.ad-box:not(#ad-banner)
> ```
> 
> This works for me. If you still see anti-adb, check if you are using any:
> 
>     * Custom filters / filter lists,
> 
>     * Other extensions,
> 
>     * Browser's built-in blocker,
> 
>     * DNS / VPN / Pi-hole blocking methods,
> 
>     * Blocking apps/softwares outside browser,
> 
>     * OS' hosts file to block domains.

I believe I don't have any filters; and no other extensions enables. I'm using Firefox, so no browser blocker, no DNS/VPN/pi-hole, or any of the others.

**Comment by stephenhawk8054** [comment]
Are you logged in to the page?

**Comment by mrtonimendes** [comment]
> Are you logged in to the page?

yes

**Comment by stephenhawk8054** [comment]
Well, I still can't reproduce the anti-adblock with the above filter, logged in or logged out.

If I disable that filter, the anti-adblock comes back.
