### ISSUE TITLE
publico.pt [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1978]
URL(s) where the issue occurs

`https://www.publico.pt/`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by mapx-** [comment]
Is it only an annoyance ? (and you can close the warning popup) or some functionalities are broken / missing ?

**Comment by KiLL4FuNK** [comment]
an annoyance

![](https://i.imgur.com/E8FPn7R.png)

**Comment by adranger** [comment]
@mapx- your fix disables generic rules that hide cookie notices. Please add an explicit rule to hide this: `<div class="site-message site-message--notice site-message--cookies">` .
