### ISSUE TITLE
larazon.es breakage

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#19792]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

video breakage when click on him ( hidden when is clicked )
it seems `atresmedia.com` inserted videos ( the logs of **uBlock Origin** no showing nothing blocked of **atresmedia.com**  in **larazon.es**

This appears in console when i click in any video:

![1](https://github.com/uBlockOrigin/uAssets/assets/33556647/1e011c7c-9a85-4eb3-81bd-e0ddeaa17508)

### URL(s) where the issue occurs.

- `https://www.larazon.es/espana/vox-rebelan-uso-pinganillos-congreso_2023091965097a0b98383a0001268352.html`

- `https://www.larazon.es/espana/puigdemont-agradece-gobierno-intento-oficializar-catalan-aunque-califica-insuficiente_202309196509dd711fb4a600013e6f03.html`

### uBO version

1.52.0

### Browser name and version

Chrome 

### Settings

```
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 102051
 cosmetic: 47302
 scriptlet: 22619
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5465-7, 43m
 default:
  user-filters: 0-0, never
  easylist: 70932-11, 43m
  easyprivacy: 33220-63, 43m
  plowe-0: 3720-1068, 43m
  spa-0: 3716-19, 43m
  spa-1: 5599-224, 43m
  ublock-badware: 8023-146, 43m
  ublock-filters: 34674-165, 43m
  ublock-privacy: 559-6, 43m
  ublock-quick-fixes: 156-53, 43m
  ublock-unbreak: 2132-35, 43m
  urlhaus-1: 5723-0, 43m
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 214 ms (selfie)
 maxAssetCacheWait: 86 ms
```

**Comment by liamengland1** [comment]
I have to click play twice but this works for me. Please test these filters and let me know if it works for you.

```
larazon.es##+js(set, gfkS2sExtension, {})
larazon.es##+js(set, gfkS2sExtension.HTML5VODExtension, noopFunc)
```
