### ISSUE TITLE
timesnownews.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#19798]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.timesnownews.com/education/teachers-of-india-story-of-rakesh-and-how-he-effectively-used-ai-tools-to-teach-visually-impaired-children-article-103388570`

### Category

nuisance

### Description

Popup prompt to connect to web app with Google account.

The issue occurs from Greece.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![268438520-85034c2e-043b-445b-83f3-a52bf64824bd](https://github.com/uBlockOrigin/uAssets/assets/101707608/b5c4dd99-1871-4f88-94ef-2ce510a6a437)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 115
filterset (summary):
 network: 399995
 cosmetic: 249716
 scriptlet: 44094
 html: 1233
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 56426-6086, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 94508-1933, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 134-0, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25811-19, now
  adguard-generic: 74374-7181, now
  adguard-mobile: 8645-138, now
  adguard-spyware-url: 1224-80, now
  block-lan: 53-0, now
  curben-phishing: 112279-34, now
  curben-pup: 189-0, now
  adguard-social: 21382-856, now
  [15 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35567-543, now
  ublock-badware: 8025-5, now
  ublock-privacy: 589-2, now
  ublock-unbreak: 2182-1, now
  ublock-quick-fixes: 156-0, 22m
  easylist: 70966-30813, now
  easyprivacy: 33225-1013, now
  urlhaus-1: 5679-0, now
  plowe-0: 3720-2, now
  GRC-0: 1042-2, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 30189 ms (selfie)
 maxAssetCacheWait: 2905 ms
popupPanel:
 blocked: 11
 network:
  timesnownews.com: 2
  amazon-adsystem.com: 1
  chartbeat.com: 2
  doubleclick.net: 1
  googletagmanager.com: 2
  indiatimes.com: 1
  pubmatic.com: 1
  scorecardresearch.com: 1
 extended:
  ###app > div[class] > div:not([class], [id]) > div[class]:empty
  ##div[class$="AdContainer"]
  ##.ad-600-h
  ###atf103388570
  ##.atfAdContainer
  ##div:has(> .bggrayAd)
  ##+js(set-constant, ga, noopFunc)
  ##+js(set-constant, player.adm.destroy, noopFunc)
  ##+js(set-constant, SlikePlayer.prototype.playAd, noopFunc)
  ##+js(json-prune, ads breaks)
  ##+js(no-setTimeout-if, Adblock)
```
</details>

**Comment by krystian3w** [comment]
Check annoyance lists:

- [ ] AdGuard annoyances
- [ ] EasyList (Fanboy) Annoyances
- [ ] Dandelion Sprout's Annoyances
   - [ ] Browse websites without logging in

Also on Reddit someone shared solutions to "My Filters" tab/panel.

**Comment by DimitrisKalaboukas** [comment]
@krystian3w Yeah, the filter:

||accounts.google.*/gsi/*$xhr,script,3p

works fine, but none of the annoyances lists covers it.

**Comment by DandelionSprout** [comment]
I can only presume such an entry would raise eyebrows on the (few?) sites where blocking that prompt would make people unable to log in with Google whatsoever.

**Comment by mapx-** [comment]
enable uBlock filters – Annoyances
