### ISSUE TITLE
mhdtvworld.me: detection

### ISSUE THREAD

**Issue by tailscale7** [uBlockOrigin/uAssets#19799]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

adblocker detected

### URL(s) where the issue occurs.

https://mhdtvworld.me

### Screenshot(s)

![267772553-85380c21-2ae4-47e5-9e76-9fb869e8233a](https://github.com/uBlockOrigin/uAssets/assets/110523519/f6e43f13-d364-4718-8797-35551a0ca1d1)

### uBO version

1.52.0

### Browser name and version

Chrome 109.0.5414.120

### Settings

none

**Comment by stephenhawk8054** [comment]
I have pushed a fix already: https://github.com/uBlockOrigin/uAssets/issues/19725. Please don't open duplicated issue.

**Comment by tailscale7** [comment]
Apologies and appreciated.

**Comment by tailscale7** [comment]
How long does it usually take to fix?
