### ISSUE TITLE
black frame

### ISSUE THREAD

**Issue by Cold-Wind1** [uBlockOrigin/uAssets#19795]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A black frame preventing website access.

### URL(s) where the issue occurs.

https://www.zeebiz.com/

### Screenshot(s)

![brave_screenshot_www zeebiz com](https://github.com/uBlockOrigin/uAssets/assets/145432904/095d1735-229a-48eb-aacd-845a8b07a52c)

### uBO version

1.52.0

### Browser name and version

Brave Browser

### Settings

Default setting of ublock

**Comment by stephenhawk8054** [comment]
Are you using Brave Shield?

**Comment by stephenhawk8054** [comment]
Can you turn off it and test again?

**Comment by stephenhawk8054** [comment]
I mean please test if the issue is still there if you turn off Brave Shield. If it's caused by Brave Shield, please report to them.

**Comment by gwarser** [comment]
For me, Brave Shield is hiding cookie dialog at the bottom.

**Comment by stephenhawk8054** [comment]
I only see cookie banner with uBO default settings: https://github.com/uBlockOrigin/uAssets/assets/66517106/c8f4c78c-12d6-48c5-83ef-783e227c2422

**Comment by stephenhawk8054** [comment]
Then why do you said this:

> Default setting of ublock

**Comment by stephenhawk8054** [comment]
> I think you know that Brave Shields also use same default filters list of ublock. so, if you update filter lists of ublock then brave shields also get update.

Brave enables annoyance list by default

**Comment by stephenhawk8054** [comment]
Adguard annoyance list is NOT in default settings of uBO. You have to enable it manually.

These are the default lists of uBO: https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png

Next time please use report button of uBO and follow the prerequisites carefully. Don't open issue manually.
