### ISSUE TITLE
video not playing

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#198]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.voot.com/movie/airlift/439578`

### Describe the issue

go to above url video ...video doesn't start playing
no error is thrown by browser or logger in ublock origin

### Screenshot(s)

![screenshot 54](https://cloud.githubusercontent.com/assets/20338483/20436274/9a9ac148-add5-11e6-990c-a77ce31b68c5.png)

### Versions

- Browser/version: mozilla firefox 50.0
- uBlock Origin version: 1.9.16

### Settings

-  uBO's default settings + antiadblock killer + adblock warning removal list

### Notes
1. when disabled ublock origin browser starts playing video
2. i kept all plugins uptodate
3. installed latest adobe flash player 23.0.0.207 and enabled...

**Comment by gorhill** [comment]
I can't investigate:

> Until then, we're only available in India

Someone else will have to investigate and come up with a solution.

**Comment by ghajini** [comment]
refreshed the firefox, even created new firefox profile,,,no luck

**Comment by mapx-** [comment]
tested in chrome + your lists + ubo 1.9.16 
no issues here, the video is running fine
try disabling all other your extensions and keep only ubo enabled. Disable also all your custom filters.

(to test I used "modify headers" extension, X-Forwarded-For = 183.82.56.201 )

**Comment by ghajini** [comment]
@mapx- bro ...
Here in chrome it works fine, I opened issue with Mozilla Firefox 50.0 originally
No custom filters added

**Comment by mapx-** [comment]
right .. it's an easyprivacy issue but only in firefox.

add
`@@||analytics.edgesuite.net$script,domain=voot.com`

**Comment by gorhill** [comment]
Clsoing as per @mapx- comment: report to EasyPrivacy maintainers.
