### ISSUE TITLE
cameracanada.com: breakage

### ISSUE THREAD

**Issue by ravertine** [uBlockOrigin/uAssets#19804]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cameracanada.com/fall-2023-contest/`

### Category

breakage

### Description

contest entry form is not showing with ublock origin enabled

### Other extensions used

too many to list

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.1b4
Firefox: 117
filterset (summary):
 network: 119374
 cosmetic: 64039
 scriptlet: 24200
 html: 1233
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  ublock-annoyances: 5427-7, now
  ublock-quick-fixes: 170-0, now
  adguard-other-annoyances: 13535-104, now
  easylist-annoyances: 3978-34, now
 default:
  ublock-filters: 35587-463, now
  ublock-badware: 8033-6, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2182-0, now
  easylist: 70992-782, now
  easyprivacy: 33201-729, now
  urlhaus-1: 5783-0, now
  plowe-0: 3720-1, now
  FRA-0: 28335-347, now
filterset (user): [array of 30 redacted]
trustedset:
 added: [array of 327 redacted]
switchRuleset:
 added: [array of 26 redacted]
hostRuleset:
 added: [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 180
 autoUpdatePeriod: 4
 extensionUpdateForceReload: true
 manualUpdateAssetFetchPeriod: 1
 popupPanelLockedSections: 39
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 992 ms (selfie)
 maxAssetCacheWait: 101 ms
popupPanel:
 blocked: 6
 network:
  ctctcdn.com: 2
  facebook.net: 1
  googletagmanager.com: 3
```
</details>

**Comment by ravertine** [comment]
I had to whitelist `||ctctcdn.com/js/signup-form-widget/$3p` from [EasyList – Other Annoyances] in order to get the form to appear

**Comment by mapx-** [comment]
maintainers notified, however you should disable `EasyList – Other Annoyances`
