### ISSUE TITLE
dezeen.com: breakage

### ISSUE THREAD

**Issue by sdalmonte** [uBlockOrigin/uAssets#19800]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dezeen.com/2023/09/18/zeller-moye-and-katie-paterson-align-hundreds-of-glass-cylinders-for-apple-campus-sculpture/`

### Category

breakage

### Description

Disqus comments don't load on dezeen.com pages.

### Other extensions used

Are.na, Control Panel for Twitter, Display Image List, Eight Dollars, Fontanello, Instapaper, Minimal Theme for Twitter, Raindrop.io, Right-Click Borescope, Wayback Machine, WhatFont, Window Resizer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="954" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/1361737/41d3fe42-1aa9-48e5-8876-91648199c6a9">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 99408
 cosmetic: 39669
 scriptlet: 18516
 html: 0
listset (total-discarded, last-updated):
 added:
  https://wesleyac.com/youtube/filter.txt: 10-0, 21m
 default:
  user-filters: 0-0, never
  easylist: 70966-11, 1m
  easyprivacy: 33225-63, 1m
  plowe-0: 3720-1068, 1m
  ublock-badware: 8023-146, 24m
  ublock-filters: 34679-134, 23m
  ublock-privacy: 559-6, 1m
  ublock-quick-fixes: 156-54, 19m
  ublock-unbreak: 2132-32, 22m
  urlhaus-1: 5783-0, 20m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 112 ms (selfie)
 maxAssetCacheWait: 42 ms
popupPanel:
 blocked: 12
 network:
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  d31qbv1cthcecs.cloudfront.net: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  myfonts.net: 1
  parsely.com: 1
  petametrics.com: 3
 extended:
  ##.leader-ad
  ##.ad--300
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by D4niloMR** [comment]
Need to accept all cookies:
```adb
dezeen.com##+js(set-cookie, CookieConsent, {necessary:true%2Cpreferences:true%2Cstatistics:true%2Cmarketing:true})

**Comment by mapx-** [comment]
The first access at the page => accept cookies => still no comments.
Any other next access => the comments are visible.

Even disabling uBO => same behaviour.
