### ISSUE TITLE
diep.io: detection

### ISSUE THREAD

**Issue by Fuddung** [uBlockOrigin/uAssets#19809]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Adblock detection on diep.io

### URL(s) where the issue occurs.

`https://diep.io/`

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 293248
 cosmetic: 241014
 scriptlet: 44476
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72210-103, 2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93348-21500, 2m
  CHN-0: 25291-144, 2m
  adguard-cookies: 27623-27623, 2m
  adguard-generic: 74411-544, 2m
  adguard-mobile: 8654-74, 2m
  adguard-mobile-app-banners: 4630-4630, 2m
  adguard-other-annoyances: 13539-13539, 2m
  adguard-popup-overlays: 24109-24109, 2m
  adguard-social: 21386-1599, 2m
  adguard-spyware: 56889-1409, 2m
  adguard-spyware-url: 1227-3, 2m
  [14 lists not shown]: [too many]
 default:
  user-filters: 10-1, never
  easylist: 71004-1227, 2m
  easyprivacy: 33192-16753, 2m
  plowe-0: 3720-1239, 2m
  ublock-badware: 8031-376, 2m
  ublock-filters: 34698-4249, 2m
  ublock-privacy: 559-139, 2m
  ublock-quick-fixes: 170-58, 2m
  ublock-unbreak: 2134-149, 2m
  urlhaus-1: 3714-2, 1m
filterset (user): [array of 10 redacted]
hostRuleset:
 added: [array of 11 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1854 ms (selfie)
 maxAssetCacheWait: 1423 ms
```
</details>

**Comment by okiehsch** [comment]
You are not using default lists and settings, you have enabled 25 additional lists.
