### ISSUE TITLE
[nsfw] chan.sankakucomplex.com: detection

### ISSUE THREAD

**Issue by sakerfalcon** [uBlockOrigin/uAssets#19806]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chan.sankakucomplex.com/`

### Category

detection

### Description

A blur filter + popup appears when uBlock is on. Site generates a new div id so the picker function is nullified.

### Other extensions used

BetterTTV
Bitwarden
Bypass Paywalls
Checker Plus for Gmail
Control Panel for Twitter
Facebook Container
Honey
Image Data
Image Search Options
NAS Download Manager for Synology
Reddit Comment Highlights
RES
Save In...
Tab Auto Refresh
Tampermonkey
Transparent Standalone Images
Yahoo Mail Alterter
Youtube Nonstop

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="705" alt="firefox_vOxfTcULo8" src="https://github.com/uBlockOrigin/uAssets/assets/5834208/c85a1841-06f4-4db0-990a-00322410356f">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 278371
 cosmetic: 230685
 scriptlet: 44072
 html: 1233
listset (total-discarded, last-updated):
 added:
  adguard-generic: 74396-6665, now
  adguard-mobile: 8654-16, now
  adguard-spyware-url: 1227-81, now
  adguard-spyware: 56889-17012, now
  curben-phishing: 112384-30, now
  adguard-social: 21386-856, now
  adguard-cookies: 27619-61, now
  ublock-cookies-adguard: 292-0, now
  adguard-popup-overlays: 24105-1571, now
  adguard-mobile-app-banners: 4630-7, now
  adguard-other-annoyances: 13535-308, now
  adguard-widgets: 2309-1, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 48-12, never
  ublock-filters: 35578-413, now
  ublock-badware: 8033-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2182-0, now
  ublock-quick-fixes: 170-5, now
  easylist: 70992-876, now
  easyprivacy: 33201-822, now
  urlhaus-1: 3714-0, now
  plowe-0: 3720-86, now
filterset (user): [array of 48 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 2 redacted]
urlRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4179 ms
 maxAssetCacheWait: 1844 ms
popupPanel:
 blocked: 13
 network:
  sankakucomplex.com: 4
  otaserve.net: 9
 extended:
  ##div#has-mail-notice.has-mail:nth-of-type(5)
  ##div#has-mail-notice.has-mail:nth-of-type(6)
  ###headerthumbs
  ##div[align="center"][class^="scad"]
  ###news-ticker
  ##.scad
  ##+js(abort-on-property-read, sankAdCurrentScript)
  ##+js(addEventListener-defuser, DOMContentLoaded, prestitialData…
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
  ##+js(nobab)
```
</details>

**Comment by D4niloMR** [comment]
```adb
chan.sankakucomplex.com##+js(set, checkForADiscoParty, noopFunc)
```

**Comment by sakerfalcon** [comment]
thanks

**Comment by D4niloMR** [comment]
it's better to not close the issue until the rule is added to the filter list

**Comment by sakerfalcon** [comment]
got it.

**Comment by pucktheincredible** [comment]
> ```
> chan.sankakucomplex.com##+js(set, checkForADiscoParty, noopFunc)
> ```

you're a real one man thanks.

**Comment by MonfGeiger** [comment]
> ```
> chan.sankakucomplex.com##+js(set, checkForADiscoParty, noopFunc)
> ```

dude.....you are a life saver. i hope this works for as long as it can. maybe it could also be incorperated into the unbreak filter list?

**Comment by acoolrocket** [comment]
> ```
> chan.sankakucomplex.com##+js(set, checkForADiscoParty, noopFunc)
> ```

Newbie here, where do I put this line into, Filters?

**Comment by stephenhawk8054** [comment]
@acoolrocket Force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.

**Comment by acoolrocket** [comment]
> @acoolrocket Go to uBO settings, then do this:
> 
> > * [x]  I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)

Didn't work for some reason.

**Comment by tacoy2** [comment]
It seems like auto paging is slightly broken as a result of this change, where some image previews don't load
Disabling javascript disabled pagination so it's got something to do with that

![Screenshot 2023-09-22 014152](https://github.com/uBlockOrigin/uAssets/assets/88209326/fc1892ce-18c1-4fc8-8705-afb4acf91cdb)

(but regardless thanks for fixing this in the first place)
