### ISSUE TITLE
symbio.agency: breakage

### ISSUE THREAD

**Issue by Huge** [uBlockOrigin/uAssets#19802]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On `https://symbio.agency/subscription` the newsletter issues only show in private mode.

The links hidden have href like `https://us6.campaign-archive.com/?u=f39bfe1184c5053999bf02e1b&id=1b7c243454`

### URL(s) where the issue occurs.

`https://symbio.agency/subscription`

### uBO version

1.52

### Browser name and version

Chrome  Version 115.0.5790.182 (Official Build) (64-bit)

### Settings

-

**Comment by mapx-** [comment]
- open uBO dashboard, support tab, copy & paste here the `Troubleshooting Information`
- disable any other blocking extension
- add a screenshot with what exactly is broken
