### ISSUE TITLE
cumhuriyet.com.tr: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#19815]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions. (**AG EXTRA + POPUP BLOCKER**)
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cumhuriyet.com.tr/yasam/farah-zeynep-abdullahtan-yilmaz-guneye-saldirinin-sebebi-kurt-olmasi-diyen-nagehan-alciya-yanit-2120412`

### Category

ads

### Description

vid. default reseted w turkish filter enabled by default settings. 
edit: it's like this on ungoogled chromium too.

### Other extensions used

**fastforward**, **ag extra**, **violantmonkey w/adguard popup blocker beta**, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![dasffas](https://github.com/uBlockOrigin/uAssets/assets/51786709/4f522dac-2b6a-4953-9ef1-33123e979839)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 99060
 cosmetic: 49808
 scriptlet: 19890
 html: 1047
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35605-109, 1m
  ublock-badware: 8033-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2184-0, now
  ublock-quick-fixes: 153-5, now
  easylist: 71004-729, now
  easyprivacy: 33193-723, now
  urlhaus-1: 3817-0, now
  plowe-0: 3720-2, now
  TUR-0: 13233-11, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 304 ms
 maxAssetCacheWait: 115 ms
popupPanel:
 blocked: 100
 network:
  2mdn.net: 1
  bik.gov.tr: 1
  casalemedia.com: 2
  creativecdn.com: 2
  criteo.com: 2
  criteo.net: 1
  dailymotion.com: 16
  dm-event.net: 34
  dmcdn.net: 2
  doubleclick.net: 1
  gemius.pl: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  idealmedia.io: 4
  indexww.com: 1
  lijit.com: 2
  mrf.io: 1
  netmera-web.com: 2
  pubmatic.com: 4
  scorecardresearch.com: 8
  smartadserver.com: 11
  yandex.ru: 2
 extended:
  ##.page-right-ad
  ##div[class^="page-"][class*="fixed-ad"]
  ##div[id*="ScriptRoot"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.container-ads
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
add

```
cumhuriyet.com.tr###sticky-player
cumhuriyet.com.tr##.row .row:has(style:has-text(dailymotion))
```

@Yuki2718
