### ISSUE TITLE
maps.google.com: breakage

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#19816]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

breakage in google maps,  ( black screen sidebar )

works well whit the adblocker OFF

### URL(s) where the issue occurs.

`https://www.google.com/maps/search/momias+mexico/@22.4454412,-106.1431254,5z`

### Screenshot(s)

![ex](https://github.com/uBlockOrigin/uAssets/assets/33556647/0d21ccaf-63d5-4a8a-b08b-f7af34e19ee9)

### uBO version

1.52.0

### Browser name and version

Chrome

### Settings

```
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 100179
 cosmetic: 47341
 scriptlet: 22657
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5467-7, 2m
 default:
  user-filters: 0-0, never
  easylist: 71022-11, 2m
  easyprivacy: 33193-63, 2m
  plowe-0: 3720-1068, 2m
  spa-0: 3720-19, 2m
  spa-1: 5601-224, 2m
  ublock-badware: 8031-146, 2m
  ublock-filters: 34723-165, 2m
  ublock-privacy: 559-6, 2m
  ublock-quick-fixes: 153-72, 2m
  ublock-unbreak: 2136-35, 2m
  urlhaus-1: 3817-0, 2m
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 266 ms (selfie)
 maxAssetCacheWait: 86 ms
```

**Comment by ryanbr** [comment]
Unable to reproduce, will wait on another person who could see it before possibly removing it. 

references:
https://github.com/easylist/easylist/pull/15761
https://github.com/easylist/easylist/commit/d528cd8350d104c438b711fd4277ba0b2450bdd3

**Comment by stephenhawk8054** [comment]
@pizza90 Can you remove your current custom filters, then click on uBO icon > &#9636; ["The logger" icon](https://github.com/gorhill/uBlock/wiki/The-logger) > Reload the page where issue happens > `</>` ["DOM Inspector" button](https://github.com/gorhill/uBlock/wiki/The-logger#dom-inspector) and screenshot both the web pages and the logger here.

**Comment by stephenhawk8054** [comment]
> if i have OFF the personalized ads.. in: `myadcenter.google.com` that's when the problem happens

@ryanbr I can reproduce with the above steps: https://github.com/uBlockOrigin/uAssets/assets/66517106/9a23dad2-6bae-43bf-934a-78c8bb3082de

**Comment by D4niloMR** [comment]
> anyother whit similar issues using opera?

I use Opera GX and I can't reproduce

**Comment by gwarser** [comment]
In Opera enable access to search pages in add-on manager.

I can repro the issue on Firefox.
