### ISSUE TITLE
tv.idlixplus.net: detection

### ISSUE THREAD

**Issue by davidsetyawan** [uBlockOrigin/uAssets#19819]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

when first load the page, it show like this
<img width="960" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/45872505/de8f13b0-953c-4b7d-991b-af622448cc3c">
and I used Zapper mode, like 3 or 4 times to remove the announcement, remove something i dont know, remove red layers, and then page become blurred. But on blurred page I can play the video and enter fullscreen mode, like nothing happened but this page blurred. blurred page like this 
<img width="960" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/45872505/930492a3-7054-4a32-9c74-0300a6816515">

### URL(s) where the issue occurs.

tv.idlixplus.net
`https://tv.idlixplus.net/episode/moving-season-1-episode-15/`

### Screenshot(s)

<img width="960" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/45872505/65bebdeb-d3b4-4ba1-8c55-4f3b59f953df">

<img width="960" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/45872505/8aacb154-6870-4748-9c86-51d7321429a5">

### Notes

- Zapper mode 3-4 times

- try to open inspect element, but they block it

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 153838
 cosmetic: 199080
 scriptlet: 27257
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 11035-6, 2h.57m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid_plus.adfl.txt: 527-4, 2d.1m
  IDN-0: 9650-402, 1d.3h.1m
  adguard-cookies: 27609-30, 2d.2m
  adguard-mobile-app-banners: 4626-13, 2d.9m
  adguard-other-annoyances: 13537-40, 2d.8m
  adguard-popup-overlays: 24095-63, 2d.7m
  adguard-social: 21382-909, 2d.6m
  adguard-spyware: 56887-327, 2d.5m
  adguard-spyware-url: 1224-3, 2d.4m
  adguard-widgets: 2309-5, 2d.3m
  block-lan: 48-0, 28d.7h.48m
  [6 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  easylist: 70892-128, 4d.18h.36m
  easyprivacy: 33255-16590, 5d.19h.13m
  plowe-0: 3720-1152, 4d.18h.37m
  ublock-badware: 7984-148, 4d.18h.37m
  ublock-filters: 34589-701, 4d.18h.37m
  ublock-privacy: 559-139, 4h.59m
  ublock-quick-fixes: 153-36, 7h.53m
  ublock-unbreak: 2131-87, 4d.18h.37m
  urlhaus-1: 3792-0, 2h.56m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-extension-scheme
  edge-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2940 ms (selfie)
 maxAssetCacheWait: 2128 ms
```
</details>

**Comment by stephenhawk8054** [comment]
It was fixed yesterday. Can you force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again?

**Comment by davidsetyawan** [comment]
aah its work. my bad open duplicated issue. I've tried search but can't find same issue.
