### ISSUE TITLE
strikeout.nu [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1982]
URL(s) where the issue occurs

`http://www.strikeout.nu/soccer/565554/2/independiente-vs-boca-juniors`

Describe the issue

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by P0Rtvine** [comment]
`https://www.strikeout.nu/espn-stream-1`

Timer in player + popup, when click on background

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-03-14_214023](https://user-images.githubusercontent.com/57287308/111081880-14cdcc80-850e-11eb-9b70-9aca719d3552.png)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version: 1.34.0

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by P0Rtvine** [comment]
@okiehsch
Overlay is still here.

**Comment by okiehsch** [comment]
Sorry, overlooked that part of your report.

**Comment by stephenhawk8054** [comment]
There's a popup when clicking on the expandable sections.

URL: `https://www.strikeout.cc/soccer`

Firefox 93, ublock 1.38.6 default

**Comment by LikesHisComputer** [comment]
https://github.com/uBlockOrigin/uAssets/pull/10812
