### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by samuelmoch** [uBlockOrigin/uAssets#19820]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=Sx4xVyXHl60`

### Category

ads

### Description

Youtube ads still show before video loads

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/145766678/5901224e-61d1-4175-81d5-f1ecce1a72aa)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 101
filterset (summary):
 network: 97398
 cosmetic: 39682
 scriptlet: 18476
 html: 1047
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35602-196, 3m
  ublock-badware: 8033-5, 3m
  ublock-privacy: 589-0, 3m
  ublock-unbreak: 2178-0, 3m
  ublock-quick-fixes: 153-0, 3m
  easylist: 71034-618, 3m
  easyprivacy: 33186-717, 3m
  urlhaus-1: 3792-0, 3m
  plowe-0: 3720-2, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 555 ms
 maxAssetCacheWait: 294 ms
popupPanel:
 blocked: 67
 network:
  youtube.com: 48
  doubleclick.net: 3
  google.com: 14
  google.com.bh: 1
  googlesyndication.com: 1
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytd-action-companion-ad-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  #@#.video-ads
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
> Firefox: 101

Can you update firefox to latest version and test again?

Then, please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
