### ISSUE TITLE
imgur.com: ads

### ISSUE THREAD

**Issue by jon-joy-1999** [uBlockOrigin/uAssets#19821]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://imgur.com/`

### Category

ads

### Description

Ads show up inline with the picture gallery, marked with an AD⬈

### Other extensions used

Tab Mix Plus
Disabled for testing purposes:
Absolute Enable Right Click & Copy
Behind  The Overlay
Cookie Manager
DownThemAll
Facebook Container
Image Max URL
Privacy Pass
Pull Tabs
RECAP
Redirector
Return YouTube Dislike
SponsorBlock for Youtube - Skip Sponsorships
SteamDB
Tampermonkey
Video DownloadHelper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Imgur McDonalds Ads](https://github.com/uBlockOrigin/uAssets/assets/6797323/ffde1cda-cd82-48fb-aaa5-a0506ae8f3c6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 101438
 cosmetic: 110037
 scriptlet: 21287
 html: 1047
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93378-70744, now
  fanboy-cookiemonster: 48316-224, now
  easylist-newsletters: 6491-4, now
 default:
  user-filters: 18-0, never
  ublock-filters: 35605-105, now
  ublock-badware: 8033-6, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2175-0, now
  ublock-quick-fixes: 162-0, now
  easylist: 71034-744, now
  easyprivacy: 33186-717, now
  urlhaus-1: 3792-0, now
  plowe-0: 3720-1, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9110 ms (selfie)
 maxAssetCacheWait: 240 ms
popupPanel:
 blocked: 26
 network:
  imgur.com: 4
  assemblyexchange.com: 2
  braze.com: 3
  btloader.com: 2
  ccgateway.net: 1
  d3c8j8snkzfr1n.cloudfront.net: 2
  facebook.net: 1
  google-analytics.com: 1
  media-lab.ai: 1
  placed.com: 1
  sascdn.com: 4
  scorecardresearch.com: 1
  stretchsquirrel.com: 1
  xeno-soswcrde4a-uc.a.run.app: 2
 extended:
  ##.ButtonBackToTop
  ##+js(set-constant, ADBLOCKED, false)
  ##+js(set-cookie, WHITELISTED_CLOSED, 1)
```
</details>

**Comment by dportvine** [comment]
Test this rule. 
```adb
imgur.com#?#.Grid-column > div[style^="height:"]:-abp-has([href^="http://smart.link/"])
```

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
imgur.com#?#.Grid-column > div[style^="height:"]:-abp-has(.Post-item-external-ad)
```

**Comment by jon-joy-1999** [comment]
> Does this work?
> 
> ```
> imgur.com#?#.Grid-column > div[style^="height:"]:-abp-has(.Post-item-external-ad)
> ```
This one does work

**Comment by krystian3w** [comment]
Try scroll page few minutes, if broke loading then we can't hide by CSS.

**Comment by stephenhawk8054** [comment]
> Try scroll page a few minutes, if broke loading then we can't hide by CSS.

I remember that issue. But I've just tested again and I don't see that issue any more even when scrolling for some minutes now.

**Comment by Piplup7575** [comment]
Also having this issue

**Comment by krystian3w** [comment]
In my case after hiding posts jump terribly after a while of scrolling, even filter is forced as CSS4 (instead by procedural/ExtendedCSS fallback in JS).

**Comment by mapx-** [comment]
same here https://github.com/uBlockOrigin/uAssets/issues/17581

**Comment by jon-joy-1999** [comment]
I guess this is the first, and the last issue I report to uBlockOrigin. From my point of view the contributors in this thread are not actually interested in resolving my issue. Back when the issue was fixed for me, I did ask how does it get reported to EasyList get fixed, and I was given a thumbs down for my effort. Thanks💩

**Comment by stephenhawk8054** [comment]
@krystian3w Then how about this?

```adb
imgur.com#?#.Post-item:-abp-has(.Post-item-external-ad)
```

**Comment by stephenhawk8054** [comment]
@jon-joy-1999 Previously there was breakage by hiding the ads: https://github.com/uBlockOrigin/uAssets/issues/17581 so I'm waiting for more information. For example

> In my case after hiding posts jump terribly after a while of scrolling, even filter is forced as CSS4 (instead by procedural/ExtendedCSS fallback in JS).

If that's the case, we can hide the ads (but not collapse it). But in any case, we can notify it to EasyList, but we'll need more feedbacks before doing it.

**Comment by krystian3w** [comment]
Still jumping.

I guess EL added now something like: `imgur.com##.Grid-column > div[style^="height:"]:has(.AdHomeContainer)` but break page even watch page in Chromium 105+.

**Comment by stephenhawk8054** [comment]
@krystian3w Hmm... I don't see jumping with these

```adb
imgur.com#@#.Grid-column > div[style^="height:"]:has(.AdHomeContainer)
imgur.com##.Post-item:has(.AdHomeContainer)
```

Can you record how it looks like with the above filters?

**Comment by krystian3w** [comment]
Such can be, posts do not jump when scrolling lightly.

As jon-joy-1999 doesn't hint at it (prefers the effect with complete coverage of the advertising gaps), probably with having millions of computers, he will have to run his filter list what he will subscribe to once per browser instead of editing the "My Filters" panel a million times.

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by ryanbr** [comment]
`imgur.com##.Post-item:has(.AdHomeContainer)` doesn't collapse the spaces on the imgur homepage, is there a better filter?

**Comment by stephenhawk8054** [comment]
@ryanbr Imgur has a record of breakage if collapsing the ads: https://github.com/uBlockOrigin/uAssets/issues/17581 . I think better to remain the spaces.

**Comment by ryanbr** [comment]
I loaded imgur.com in Brave and Firefox, and seems fine here, as you scroll down imgur will dynamicly load images. 

Want proof of actual breakage, since removing said filter would show ad spaces and ruin the experience for everyone.

**Comment by stephenhawk8054** [comment]
The issue is not about loading dynamically or not.

The issue is the posts jumping up and down.

Here, can you see the 2 posts in the left jumping up and down? https://x0.at/yc1m.mp4

**Comment by ryanbr** [comment]
Maybe?

```
imgur.com##.Grid-column.hasMargin > div[style^="height: 250px;"]:has(.AdHomeContainer)
imgur.com##.Grid-column.hasMargin > div[style^="height: 230px;"]:has(.AdHomeContainer)
```

 Its only "jumpy" because of the ads being inserted forwards or backwards scrolling

**Comment by stephenhawk8054** [comment]
The posts are still jumping for me.

**Comment by ryanbr** [comment]
> Its only "jumpy" because of the ads being inserted forwards or backwards scrolling

Seems to be ignored ^ . I think it should be left, it doesn't break the site and its just asthetic. A non-perfect solution is better than having empty blank squares all over the place.

**Comment by stephenhawk8054** [comment]
I don't think it's aesthetic. It's a worse experience for me than the placeholders, but ok whatever.

**Comment by jon-joy-1999** [comment]
I just checked with the fix that [stephenhawk8054](https://github.com/stephenhawk8054) gave and it does have the images jumping while scrolling issue, but before I saw the video of the issue I didn't even notice the problem.

**Comment by stephenhawk8054** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/196pd5o/make_ubo_easylist_and_imgurcom_play_nice/
