### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by pencilcheck** [uBlockOrigin/uAssets#19827]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=gLvOT2AldwM&t=35s`

### Category

ads

### Description

I'm on latest chrome on m1 mac. ublock stops working all of a sudden, purging the cache multiple times doesn't do anything, hard refresh youtube videos doesn't do anything it seems.

But once I installed this extension the ads got blocked:

https://chrome.google.com/webstore/detail/adblock-for-youtube/ijelnahiojlfbmiihbmgkaldffppfelp/related

### Other extensions used

Auto Quality for YouTube™
Clickbait Remover for Youtube
Youtube Chat in Fullscreen
YouTube NonStop

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 114
filterset (summary):
 network: 97424
 cosmetic: 39701
 scriptlet: 18558
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 7m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, 7m
 default:
  user-filters: 6-0, never
  easylist: 71074-13, 7m
  easyprivacy: 33169-63, 7m
  plowe-0: 3719-1066, 7m
  ublock-badware: 8031-146, 7m
  ublock-filters: 34724-136, 7m
  ublock-privacy: 559-6, 7m
  ublock-quick-fixes: 171-76, 7m
  ublock-unbreak: 2119-31, 7m
  urlhaus-1: 3792-0, 7m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 23 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 359 ms (selfie)
 maxAssetCacheWait: 85 ms
popupPanel:
 blocked: 59
 network:
  youtube.com: 42
  doubleclick.net: 5
  google.com: 6
  googlesyndication.com: 6
 extended:
  ###player-ads
  ###merch-shelf
  ##.ad-showing > .html5-video-container
  ##.ytd-action-companion-ad-renderer
  ##.ytd-compact-promoted-video-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-button
  ##.ytp-ad-player-overlay-flyout-cta
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-compact-promoted-video-renderer
  ##ytd-companion-slot-renderer
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
I didn't mean you to open new issue. On reddit I said:

> scroll to the bottom > click on Troubleshooting Information and copy paste it here?

---

```
Auto Quality for YouTube™
Clickbait Remover for Youtube
Youtube Chat in Fullscreen
YouTube NonStop
```

Can you turn off all other extensions and test again?

Then please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
