### ISSUE TITLE
nbc / peacock: breakage

### ISSUE THREAD

**Issue by williamsjamal** [uBlockOrigin/uAssets#19822]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.espn.com/watch/player/_/id/be26ff9d-bd1a-44fd-9791-e8790d137132`

### Category

breakage

### Description

Espn's player will not load with ublock enabled. when disabled the videos play fine. Similar issue on NBC sports as well.

### Other extensions used

google scholar, zotero connector, 1password

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 97504
 cosmetic: 39699
 scriptlet: 18490
 html: 1047
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 35615-112, 2m
  ublock-badware: 8033-6, 2m
  ublock-privacy: 589-0, 2m
  ublock-unbreak: 2175-0, 2m
  ublock-quick-fixes: 177-0, 2m
  easylist: 71057-713, 2m
  easyprivacy: 33168-716, 2m
  urlhaus-1: 3899-0, 2m
  plowe-0: 3718-1, 2m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 215 ms (selfie)
 maxAssetCacheWait: 107 ms
popupPanel:
 blocked: 20
 network:
  espn.com: 6
  chartbeat.com: 1
  espncdn.com: 1
  facebook.net: 1
  fn-pz.com: 4
  go.com: 2
  impactradius-event.com: 1
  imrworldwide.com: 1
  omtrdc.net: 1
  scorecardresearch.com: 1
  webcontentassessor.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
- needing us ip
- I'm able to play a free video on FF /chrome:
`https://www.espn.com/watch/player/_/id/38461357#bucketId=3434`

if the breakage is not on free stuff then we need a provider / paid account I guess

**Comment by mapx-** [comment]
@williamsjamal can you provide free videos for nbc sports (exact links) too ?

**Comment by williamsjamal** [comment]
Hey, it seems like the problem with espn—at least this time—was that the video wasn't available. Sorry for not double checking. here's a link to peacock content that won't play without ublock disabled: https://www.peacocktv.com/watch/asset/movies/tucker-and-dale-vs-evil/453c2e5b-ecf6-346a-b95a-ccd75691d42b

the content is free but I think you do need a free peacock account. I tested this link right now so should still have the same problem.

**Comment by stephenhawk8054** [comment]
> you do need a free peacock account

I accessed `https://www.peacocktv.com/` but I don't know how to create a free account with it.

**Comment by mapx-** [comment]
`NBC Peacock’s free accounts are no longer available to new users`

@williamsjamal did you check the free video on espn (above) ?

**Comment by williamsjamal** [comment]
@mapx- Yeah, this video works and other espn content works for me as well. I think it was not a ublock problem and might have been with another extension that i didn't realize was active (a sound mixer extension)

**Comment by williamsjamal** [comment]
@stephenhawk8054 It looks like peacock/nbc removed their free accoutn a few months ago: https://www.reddit.com/r/Roku/comments/12jktrr/is_peacock_tv_really_free/

**Comment by williamsjamal** [comment]
Is there anything I can do to replicate the problem for you with my account? Activate logs or something? Thanks

**Comment by stephenhawk8054** [comment]
@williamsjamal Can you turn off all other extensions and test again? Also specify which link did you use to test.

**Comment by williamsjamal** [comment]
I used the link mapx provided and I've used other espn content that worsk fine now with the other extension disabled. Peacock/nbc still has problems but it seems it's behind a paywall, hoping there are other ways to replicate or provide logs?

**Comment by mapx-** [comment]
You are talking above about nbc sports, then provided this link 

`https://www.peacocktv.com/watch/asset/movies/tucker-and-dale-vs-evil/453c2e5b-ecf6-346a-b95a-ccd75691d42b`

first of all:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by williamsjamal** [comment]
Yeah, as I said, nbc uses peacock to broadcast much of the live sports. But, you can try to you follow this link: https://www.nbc.com/live?brand=nbc-news and attempt to click on any of the live sports going on (below the main player which does start and play normally). all other extensions are turned off and turning ublock off will allow the content to appear.

**Comment by mapx-** [comment]
working fine

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/3fbcc65a-b649-4614-b24c-c522932fb147)

did you follow all the indications above ?

**Comment by williamsjamal** [comment]
Which browser are you using? Doesn't work for me after following the instructions on firefox. Does work on Chrome, though.
![Screenshot 2023-09-23 at 8 27 38 AM](https://github.com/uBlockOrigin/uAssets/assets/24947809/bb988e73-e092-433c-b18a-686607ccad8d)

**Comment by mapx-** [comment]
tested firefox / chrome, all fine on my side

Did you disable Enhanced Tracking Protection in firefox ? => custom => then unselect all entries

**Comment by williamsjamal** [comment]
Yeah, I had the settings like this and selected the shield and turned off enhanced tracking. Didn't change anything. restarted the computer, cleared cache again and retried with no change. Not sure what else to do but glad it's working for you. Thanks for looking into it, I suppose i'll just use chrome when watching those videos, thanks again. ![Screenshot 2023-09-23 at 8 58 11 AM](https://github.com/uBlockOrigin/uAssets/assets/24947809/21a87343-eceb-466d-8c31-c4813db17966)
