### ISSUE TITLE
redir.minhareceita.xyz: detection

### ISSUE THREAD

**Issue by x-Raiden-x** [uBlockOrigin/uAssets#19834]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://redir.minhareceita.xyz/campanha/?token=bWFnbmV0Oj94dD11cm46YnRpaDpkNDA1ZDIwMDEzZDA0ZDUwODI2Y2Q2ZTVjZWJiY2YzNGRiZTczNWE5JmRuPVJvdW5kLjYuUzAxLjEwODBwLldFQi1ETC5ERDUuMS5ILjI2NC5EVUFMJnRyPXVkcCUzYSUyZiUyZnRyYWNrZXIub3BlbmJpdHRvcnJlbnQuY29tJTNhODAlMmZhbm5vdW5jZSZ0cj11ZHAlM2ElMmYlMmZ0cmFja2VyLnB1YmxpY2J0LmNvbSUzYTgwJTJmYW5ub3VuY2U=`

### Category

[unknown]

### Description

site detects adblock

### Other extensions used

Privacy Badger

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 98997
 cosmetic: 27093
 scriptlet: 18921
 html: 1048
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35676-353, now
  ublock-badware: 8033-5, now
  ublock-privacy: 586-1, now
  ublock-unbreak: 2170-1, now
  ublock-quick-fixes: 179-0, now
  easylist: 71031-16694, now
  easyprivacy: 33176-732, now
  urlhaus-1: 3913-0, now
  plowe-0: 3719-2, now
  spa-1: 5606-94, now
filterset (user): [empty]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 200 ms (selfie)
 maxAssetCacheWait: 76 ms
popupPanel:
 blocked: 37
 network:
  minhareceita.xyz: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  themoneytizer.com: 32
  unblockia.com: 1
```
</details>

**Comment by mapx-** [comment]
- even disabling uBO I get a small notice at the top about dusabling the adblock
- I can click the button above (2 different pages) and then the torrent can be started (in your p2p client)

add 
`fitnessbr.click,minhareceita.xyz###banner`

**Comment by D4niloMR** [comment]
Works well:
```adb
||redir.minhareceita.xyz^$image,subdocument,script
||fitnessbr.click/up/show-promote.min.js$script,1p
minhareceita.xyz,fitnessbr.click##+js(set, segundos, 0)
```

I don't see any anti-adblock popup. but i think that these scripts are the responsible for detecting: `https://fitnessbr.click/js/antiad.js`
`https://minhareceita.xyz/js/antiads.js`
