### ISSUE TITLE
[nsfw] linkvertise.com: breakage

### ISSUE THREAD

**Issue by AutinTMoore** [uBlockOrigin/uAssets#19835]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/`

### Category

breakage

### Description

Constant white screen for some reason, can't figure it out, I've reset it to default, used some filter lists and it just continues to break.
![image](https://github.com/uBlockOrigin/uAssets/assets/30959980/bd1a35f5-bb39-4fae-bac0-9bcc308daf1d)
(Sorry for the blindness btw..)

### Other extensions used

Fast Forward, if that counts?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 118
filterset (summary):
 network: 275029
 cosmetic: 230955
 scriptlet: 44221
 html: 1236
listset (total-discarded, last-updated):
 added:
  adguard-generic: 74670-490, 29m
  adguard-mobile: 8654-158, 28m
  adguard-spyware-url: 1232-81, 28m
  adguard-spyware: 57351-18141, 28m
  block-lan: 54-0, 29m
  curben-phishing: 97372-19, 29m
  curben-pup: 189-0, 28m
  adguard-social: 21411-36, 28m
  adguard-cookies: 27647-32, 28m
  ublock-cookies-adguard: 294-4, 29m
  adguard-popup-overlays: 24194-812, 29m
  adguard-mobile-app-banners: 4635-18, 29m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35676-4209, now
  ublock-badware: 8033-254, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2170-62, now
  ublock-quick-fixes: 179-0, now
  easylist: 71031-1979, now
  easyprivacy: 33176-1104, now
  urlhaus-1: 3913-0, now
  plowe-0: 3719-478, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6830 ms (selfie)
 maxAssetCacheWait: 5542 ms
popupPanel:
 blocked: 19
 network:
  linkvertise.com: 12
  bizseasky.com: 1
  clarity.ms: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  media.net: 2
  sentry.io: 1
 extended:
  ##+js(json-prune, data.meta.require_addon data.meta.require_vide…
  ##+js(abort-current-script, addEventListener, DOMNodeRemoved)
  ##+js(abort-current-script, document.dispatchEvent, CustomEvent)
  ##+js(abort-current-script, onload, adsbygoogle)
  ##+js(addEventListener-defuser, load, nextFunction)
  ##+js(json-prune, data.meta.require_addon data.meta.require_capt…
  ##+js(nano-setInterval-booster)
  ##+js(set-constant, isAdBlockActive, false)
  ##+js(abort-current-script, document.addEventListener, /google_a…
```
</details>

**Comment by mapx-** [comment]
add

`||linkvertise.com^$badfilter`

**Comment by mapx-** [comment]
@pgl

**Comment by pgl** [comment]
> @pgl

Thanks. This was reported to me as the new version of adf.ly (and adf.ly does redirect there). Seems it's just an ad sites, so unless anyone shows it otherwise I'll leave it on my list.
