### ISSUE TITLE
chan.sankakucomplex.com: nuisance

### ISSUE THREAD

**Issue by tenjouina** [uBlockOrigin/uAssets#19833]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chan.sankakucomplex.com/ja/`

### Category

nuisance

### Description

ポップアップが毎回出てくる

### Other extensions used

オートページ

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 99433
 cosmetic: 50896
 scriptlet: 18711
 html: 1047
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35674-220, now
  ublock-badware: 8033-0, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2170-0, now
  ublock-quick-fixes: 180-5, 11m
  easylist: 71000-575, now
  easyprivacy: 33176-758, now
  urlhaus-1: 3913-0, 11m
  plowe-0: 3719-2, 11m
  JPN-1: 13405-64, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7085 ms (selfie)
 maxAssetCacheWait: 2749 ms
popupPanel:
 blocked: 25
 network:
  sankakucomplex.com: 3
  otaserve.net: 22
 extended:
  ##.scad
  ##div:nth-of-type(12)
  ##[data-revive-zoneid]
  ##a[href^="https://s.zlinkc.com/"]
  ##+js(abort-on-property-read, sankAdCurrentScript)
  ##+js(addEventListener-defuser, DOMContentLoaded, prestitialData…
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
```
</details>

**Comment by mapx-** [comment]
force update all filter lists
