### ISSUE TITLE
a-o.ninja [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1983]
URL(s) where the issue occurs

`https://a-o.ninja/anime/black-bullet/1`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by okiehsch** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/3ede54f92aa4d381235bfc4a36b7c19a12add815#commitcomment-28592178

**Comment by okiehsch** [comment]
Fixed in the polish list.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by okiehsch** [comment]
Still fixed in the polish list ....

**Comment by mapx-** [comment]
hmm.. testing in FF still needing `generichide`

**Comment by okiehsch** [comment]
I tested only with Chromium/Chrome.
