### ISSUE TITLE
blackmod.net: nuisance

### ISSUE THREAD

**Issue by Yehh22** [uBlockOrigin/uAssets#19832]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blackmod.net/forum/`

### Category

nuisance

### Description

The website auto refreshes every 10 min in order to 'abuse' the ads. It is quite annoying for me. Can it be stopped via filter? 

This is what I found in html source
`<meta http-equiv="refresh" content="600">`

### Other extensions used

None

### Screenshot(s)

N/A

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 99068
 cosmetic: 41699
 scriptlet: 18637
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  NOR-0: 3616-1, 1m
  easylist: 71000-14, 1m
  easyprivacy: 33176-64, 1m
  plowe-0: 3719-1067, 1m
  ublock-badware: 8031-146, 1m
  ublock-filters: 34789-140, 1m
  ublock-privacy: 556-6, 1m
  ublock-quick-fixes: 179-85, 1m
  ublock-unbreak: 2123-31, 1m
  urlhaus-1: 3913-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 553 ms (selfie)
 maxAssetCacheWait: 263 ms
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 1
  googlesyndication.com: 1
 extended:
  ##.js-notices.notices--bottom_fixer.notices
```
</details>

**Comment by mapx-** [comment]
test

`blackmod.net##^meta[http-equiv="refresh"]`
