### ISSUE TITLE
3djuegos.com: breakage

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#19849]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

dailymotion videos no load ( black screen )

### URL(s) where the issue occurs.

`https://www.3djuegos.com/ps5/noticias/dispositivo-portatil-ps5-tiene-nombre-oficial-precio-nuevos-detalles-asi-playstation-portal`

### uBO version

1.52.2

### Browser name and version

Chrome

### Settings

```
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 100242
 cosmetic: 47302
 scriptlet: 22736
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5467-7, 1m
 default:
  user-filters: 0-0, never
  easylist: 71035-13, 1m
  easyprivacy: 33179-63, 1m
  plowe-0: 3719-1066, 1m
  spa-0: 3720-19, 1m
  spa-1: 5606-224, 1m
  ublock-badware: 7879-142, 1m
  ublock-filters: 34817-172, 1m
  ublock-privacy: 556-6, 1m
  ublock-quick-fixes: 165-64, 1m
  ublock-unbreak: 2124-34, 1m
  urlhaus-1: 3972-0, 1m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 212 ms (selfie)
 maxAssetCacheWait: 84 ms
```

**Comment by stephenhawk8054** [comment]
I don't see any `adsocy.com` connections appear

**Comment by mapx-** [comment]
I can reproduce using a spanish (valencia) ip

`||adsocy.com^`

**Comment by stephenhawk8054** [comment]
@Yuki2718 So maybe for AG Spanish or EL?

**Comment by Yuki2718** [comment]
I don't see `adsocy.com` even with Spanish VPN, but will add. But on my end dailymotion still doesn't play.

**Comment by Yuki2718** [comment]
@stephenhawk8054 I think https://github.com/uBlockOrigin/uAssets/commit/cf64185dd2de9c051d9bad65ab950b5dc7374374 re-broke the video. Can you reproduce?

**Comment by stephenhawk8054** [comment]
@Yuki2718 Hmmm... yeah, it behaves differently when I use VPN to Spain. But looks like it's not related to that domain.

Does this work on your side?

```adb
@@||3djuegos.com^$ghide
```

**Comment by mapx-** [comment]
if I add

`||adsocy.com^$3p,badfilter`

I get the ads back

**Comment by Yuki2718** [comment]
> @Yuki2718 Hmmm... yeah, it behaves differently when I use VPN to Spain. But looks like it's not related to that domain.
> 
> Does this work on your side?
> 
> ```
> @@||3djuegos.com^$ghide
> ```

Yes. These two
```
3djuegos.com#@#.ad-box:not(#ad-banner)
3djuegos.com#@#div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; position: absolute; left: -10000px; top: -"])
```

**Comment by stephenhawk8054** [comment]
@Yuki2718 Looks like those are not enough for me if I use browser that auto-clears site's data after closing. I have to add these:

```adb
3djuegos.com#@#.ad-lat2
3djuegos.com##.ad-lat2:style(height: 0 !important; min-height: 0 !important; margin: 0 !important; padding: 0 !important; visibility: collapse !important;)
```

(accept all the cookies)

**Comment by Yuki2718** [comment]
What is `3djuegos.com##+js(nano-stb, jad['timeline'], *)` for?

**Comment by stephenhawk8054** [comment]
When I tested yesterday, the video takes quite long to start. I thought it's because of ads blocking, but looks like it's the same without uBO, so maybe not needed any more.

**Comment by Yuki2718** [comment]
@pizza90 Can you narrow down which cosmetic filters are the culprit?
