### ISSUE TITLE
discogs.com: ads

### ISSUE THREAD

**Issue by tordenflesk** [uBlockOrigin/uAssets#19847]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Had to upgrade uBO to combat recent ads on YouTube. Now Discogs ads aren't being filtered properly.
uBO ipdates haven't been functional, so the last working version i had was 1.43.0. Downgrading restored normal function, but YouTube ads then started reappearing.

WaterFox Classic 2022.11 x64.

### A specific URL where the issue occurs.

https://www.discogs.com/release/649970-Various-Work-Five

### Steps to Reproduce

Open ant discogs release page.

### Expected behavior

ads to be removed.
Luckily the actual ads are blocked at DNS level.

### Actual behavior

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/2136727/0bf9496b-b965-49d1-8e72-ab91acdd5152)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 56
filterset (summary):
 network: 293679
 cosmetic: 271008
 scriptlet: 45483
 html: 1256
listset (total-discarded, last-updated):
 removed:
  ublock-privacy: null
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdRemovalListForUnusualAds.txt: 224-0, 2h.14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion Sprout's Website Stretcher.txt: 435-0, 2h.14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/DeviantARTQualityArtMagnifier.txt: 1617-1, 2h.14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ImgurPureImageryExperience.txt: 19-0, 2h.14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/KnowYourMemePureBrowsingExperience.txt: 19-0, 2h.14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2264-0, 2h.14m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/WikiaPureBrowsingExperience.txt: 63-0, 2h.14m
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 2h.14m
  https://www.i-dont-care-about-cookies.eu/abp/: 25821-4, 2h.14m
  adguard-generic: 74778-4512, 2h.14m
  adguard-mobile: 8655-55, 2h.14m
  adguard-spyware-url: 1231-146, 2h.14m
  [22 lists not shown]: [too many]
 default:
  user-filters: 23-1, never
  ublock-filters: 35684-44, 2h.14m
  ublock-badware: 7881-0, 2h.14m
  ublock-unbreak: 2171-1, 2h.14m
  ublock-quick-fixes: 165-53, 2h.14m
  easylist: 71035-1299, 2h.14m
  easyprivacy: 33179-16571, 2h.14m
  urlhaus-1: 3983-0, 2h.14m
  plowe-0: 3719-1565, 2h.14m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 1 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 prefetchingDisabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8678 ms
 maxAssetCacheWait: 109 ms
```
</details>

**Comment by stephenhawk8054** [comment]
> Downgrading restored normal function, but YouTube ads then started reappearing.

Downgrade to uBO version 1.32.4 and below and force update all your filter lists again (do it twice). YouTube fix was added for those versions yesterday.

**Comment by tordenflesk** [comment]
> YouTube fix was added for those versions yesterday.

From where?

**Comment by stephenhawk8054** [comment]
> > YouTube fix was added for those versions yesterday.
> 
> From where?

In the main list, have you forced update all your filter lists yet?

**Comment by tordenflesk** [comment]
> > > YouTube fix was added for those versions yesterday.
> > 
> > 
> > From where?
> 
> In the main list, have you forced update all your filter lists yet?

I'm asking you from where does this old version magically pull this fix from.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/commit/44e4319d90e770949d1393a89bfe0c87624d2425
