### ISSUE TITLE
loveflix.tv: breakage

### ISSUE THREAD

**Issue by daveox** [uBlockOrigin/uAssets#19844]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.loveflix.tv/filme-fear-the-night/`

### Category

breakage

### Description

To watch a movie/series, after clicking on the play button,  it goes through a couple of redirects on linkshort.fun, then It requires clicking on one ad, but there are no visible ads since the default filters are enabled.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 114
filterset (summary):
 network: 97510
 cosmetic: 39652
 scriptlet: 18622
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  spa-1: null
 default:
  easylist: 71035-13, now
  easyprivacy: 33179-63, now
  plowe-0: 3719-1066, now
  ublock-badware: 7879-142, now
  ublock-filters: 34815-141, now
  ublock-privacy: 556-6, now
  ublock-quick-fixes: 165-64, now
  ublock-unbreak: 2124-31, now
  urlhaus-1: 3983-0, now
filterset (user): [array of 178 redacted]
trustedset:
 added: [array of 10 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 482 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 718 ms (selfie)
 maxAssetCacheWait: 278 ms
popupPanel:
 blocked: 6
 network:
  aj2550.bid: 1
  doruffleton.com: 2
  walkerllaw.org: 1
  whuhough.xyz: 2
```
</details>

**Comment by okiehsch** [comment]
I end up at 
`https://olhonaviagem.com/machu-picchu-saiba-mais`
and the video play without issue on my end.

<details>
<summary>Screenshot(s)</summary>


![image](https://github.com/uBlockOrigin/uAssets/assets/16838044/95627d58-b826-430b-8e90-28acfa65568a)

</details>
