### ISSUE TITLE
jansatta.com: breakage

### ISSUE THREAD

**Issue by frosty911** [uBlockOrigin/uAssets#19846]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jansatta.com/national/shared-intel-behind-justin-trudeau-statement-on-nijjar-killing-said-us-envoy/3017364/`

### Category

breakage

### Description

The page does not show the main content when uBlock is enabled. I tried blocking and allowing particilar elements but nothing seems to work. It only works when I disable uBlock. 

### Other extensions used

I only use one "Bypass Paywalls" extension.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2](https://github.com/uBlockOrigin/uAssets/assets/31382254/59b1c204-1dbb-4123-867a-e2051172bb53)
![1](https://github.com/uBlockOrigin/uAssets/assets/31382254/4bbdd526-5f5f-4685-833f-d3412e3c3341)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 97486
 cosmetic: 39645
 scriptlet: 18622
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71014-13, 50m
  easyprivacy: 33168-63, 50m
  plowe-0: 3719-1066, 51m
  ublock-badware: 7879-142, 50m
  ublock-filters: 34811-136, 50m
  ublock-privacy: 556-6, 50m
  ublock-quick-fixes: 165-64, 50m
  ublock-unbreak: 2124-31, 50m
  urlhaus-1: 3983-0, 50m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 497 ms (selfie)
 maxAssetCacheWait: 204 ms
popupPanel:
 blocked: 18
 network:
  jansatta.com: 6
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 3
  izooto.com: 2
  parsely.com: 1
  pubmatic.com: 1
  scorecardresearch.com: 1
  wp.com: 1
 extended:
  ##.newspack_global_ad
  ##.adcode728x90
  ##.adcode300x250
  ##.adcodetextwrap300x250
  ###taboola-below-article-1
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
jansatta.com#@##taboola-below-article-1
```

@ryanbr
