### ISSUE TITLE
vandal.elespanol.com: breakage

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#19848]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

forum post-titles and images breakage

this rare filter breaking the titles I think 🤔:

`/^https:\/\/www\.(?!instagram)[a-z]{8,16}\.com\/(?:[a-z]{2,10}[-.])?[a-z]{2,10}\.(?:min\.)?js$/$script,3p,match-case,from=~edu|~gov`

### URL(s) where the issue occurs.

forum: `https://vandal.elespanol.com/foro/cgi-bin/foro.cgi?accion=vermensajesnuevos`

images: `https://vandal.elespanol.com/trucos/videojuegos`

### uBO version

1.52.0

### Browser name and version

Chrome

### Settings

```
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 100253
 cosmetic: 47302
 scriptlet: 22736
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5467-7, 5h.55m
 default:
  user-filters: 1-1, never
  easylist: 71035-13, 5h.55m
  easyprivacy: 33179-63, 5h.55m
  plowe-0: 3719-1066, 5h.55m
  spa-0: 3720-19, 5h.55m
  spa-1: 5606-224, 5h.55m
  ublock-badware: 7879-142, 5h.55m
  ublock-filters: 34817-172, 5h.55m
  ublock-privacy: 556-6, 5h.55m
  ublock-quick-fixes: 165-64, 5h.55m
  ublock-unbreak: 2124-34, 5h.55m
  urlhaus-1: 3983-0, 5h.55m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 212 ms (selfie)
 maxAssetCacheWait: 84 ms
```

**Comment by stephenhawk8054** [comment]
@Yuki2718 The blocked URL is `https://www.vandalimg.com/jquery.min.js`

**Comment by Yuki2718** [comment]
I'll comment the rule out now.
