### ISSUE TITLE
uBlockOrigin detected and browser is redirected

### ISSUE THREAD

**Issue by mrslvd** [uBlockOrigin/uAssets#19855]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlockOrigin detected and browser is redirected

### URL(s) where the issue occurs.

news.bg
Webcafe.bg

### uBO version

last

### Browser name and version

firefox

### Settings

No changes

**Comment by mrslvd** [comment]
Still not resolved.

**Comment by mrslvd** [comment]
Thanks

**Comment by mrslvd** [comment]
There is an issue with pointed sites again.
Main page is opening as expected but when any article is opened then instead of article the message containing warning that I am using "malicious" software (ad-blocker) is shown, asking me to deactivate uBO and reload.

**Comment by mrslvd** [comment]
Unfortunately the articles in news.bg, webcafe.bg; money.bg are not reachable again.

**Comment by stephenhawk8054** [comment]
Force update your filter lists again.

**Comment by mrslvd** [comment]
It doesn't help... on both android and win version...

**Comment by mrslvd** [comment]
Hi, the same problem with: news.bg; money.bg; webcafe.bg; lifestyle.bg
appears again.

Best regards,
Miro

**Comment by stephenhawk8054** [comment]
@mrslvd Can you force update the filter lists again?

**Comment by mrslvd** [comment]
Thanks!

**Comment by mrslvd** [comment]
Hi, the same problem with: news.bg; money.bg; webcafe.bg; lifestyle.bg
appears again.

Best regards,
Miro

**Comment by stephenhawk8054** [comment]
@mrslvd I can't reproduce the issue. The article appears normal for me. Can you force update the filter lists again?

**Comment by mrslvd** [comment]
I did a filter list update and now it works fine. Thanks!
Every time before I write an email I am doing a filter list update, because
I don't want to raise false events and in that way bring unnecessary effort.

Best regards

**Comment by mapx-** [comment]
@mrslvd update always your lists before reporting
