### ISSUE TITLE
kimcartoon.li: detection

### ISSUE THREAD

**Issue by asyrel** [uBlockOrigin/uAssets#19854]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kimcartoon.li/Cartoon/Futurama-Season-08/Episode-1?id=108914`

### Category

detection

### Description

When i load up an episode it stops and says adblock detected

### Other extensions used

Microsoft autofill
modheader 
Absolute enable right click
video download helper
twitch lurker
volume master 
save image as
twitch adblocker 
7tv and BTTV

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/20913139/43f517f9-8546-47ec-b35f-05a7d1b3eec5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 97470
 cosmetic: 39648
 scriptlet: 18621
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71023-13, 1m
  easyprivacy: 33169-63, 1m
  plowe-0: 3719-1066, 1m
  ublock-badware: 7879-142, 1m
  ublock-filters: 34809-141, 1m
  ublock-privacy: 556-6, 1m
  ublock-quick-fixes: 163-64, 1m
  ublock-unbreak: 2135-31, 1m
  urlhaus-1: 3957-0, 1m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1263 ms (selfie)
 maxAssetCacheWait: 99 ms
popupPanel:
 blocked: 17
 network:
  kimcartoon.li: 2
  googlesyndication.com: 2
  googletagmanager.com: 2
  jsdelivr.net: 1
  jwpcdn.com: 1
  staticmoly.me: 6
  vidmoly.to: 1
  vstats.me: 1
  yandex.ru: 1
 extended:
  ##+js(no-window-open-if)
  ##+js(abort-current-script, $, adbWarn)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(remove-node-text, script, Number.isSafeInteger)
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
