### ISSUE TITLE
reevown.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1985]
URL(s) where the issue occurs

`https://reevown.com/`

Describe the issue

Anti-Adblock

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`reevown.com##script:inject(set-constant.js, m6er_mav, false)`. They just incremented the number by 1.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/43f3610e5a390b4ef61adfd6a4c9f6864b32a107

**Comment by version365** [comment]
it's showing anti-adblock warning again!

**Comment by uBlock-user** [comment]
`(reevown.com##script:inject(bab-defuser.js)`

**Comment by uBlock-user** [comment]
`reevown.com##script:inject(bab-defuser.js)`

**Comment by eXPerience83** [comment]
Fails again:
allow https://reevown.com/ad/banner/_adsense_/_adserver/_adview_.ad.json to disable ublock detection

**Comment by uBlock-user** [comment]
`reevown.com##script:inject(abort-on-property-read.js, adBlockDetected)`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
