### ISSUE TITLE
vandal.elespanol.com: breakage

### ISSUE THREAD

**Issue by macaelero** [uBlockOrigin/uAssets#19853]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vandal.elespanol.com/`

### Category

breakage

### Description

Images don't load

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="996" alt="Captura de pantalla 2023-09-25 a las 9 32 48" src="https://github.com/uBlockOrigin/uAssets/assets/60180110/2a40b84e-308d-4f6d-af3e-45b66459ad6a">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 117
filterset (summary):
 network: 112867
 cosmetic: 89029
 scriptlet: 33956
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  adguard-generic: 74786-484, now
  adguard-mobile: 8662-44, now
 default:
  user-filters: 48-5, never
  easylist: 71023-1100, now
  easyprivacy: 33168-168, now
  spa-0: 3720-40, now
  spa-1: 5610-229, now
  ublock-badware: 7879-360, now
  ublock-filters: 34815-3870, now
  ublock-privacy: 556-5, now
  ublock-quick-fixes: 165-66, now
  ublock-unbreak: 2130-93, now
filterset (user): [array of 48 redacted]
trustedset:
 added: [array of 112 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 9 redacted]
userSettings:
 cloudStorageEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 628 ms (selfie)
 maxAssetCacheWait: 419 ms
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  revenuemakerdata.com: 1
  scorecardresearch.com: 1
  sensic.net: 1
  vandalimg.com: 1
 extended:
  ###publifooter
  ###publi400
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, tieneAdblock, 0)
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/19848
