### ISSUE TITLE
mail.com: ads

### ISSUE THREAD

**Issue by Cold-Wind1** [uBlockOrigin/uAssets#19850]
https://user-images.githubusercontent.com/145432904/270243199-6a0be77f-c50a-423d-9d9e-b1c1045e15e2.png

Brave browser.
Ubo 1.52.2 default filter

**Comment by mapx-** [comment]
I'm able to reproduce the frame only disabling the cosmetic filters and whitelisting adition images

```
@@||mail.com^$ehide
@@||adition.com^$image
```

reset uBO to default settings / lists, disable the shields in brave for this site

**Comment by mapx-** [comment]
> reset uBO to default settings / lists, disable the shields in brave for this site

**Comment by mapx-** [comment]
even keeping the shields for `mail.com` => still cannot reproduce your issue.

**Comment by mapx-** [comment]
You'll have to investigate on your side why that issue happens (even using AG base I cannot reproduce any issue) or open an issue at AG repository.

**Comment by mapx-** [comment]
We do not "fix" issues we cannot reproduce or triggered by some custom configurations.
