### ISSUE TITLE
youtube.com: breakage

### ISSUE THREAD

**Issue by pigeonfaith** [uBlockOrigin/uAssets#19859]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=jeJKnofNBNs&t=945s`

### Category

breakage

### Description

no youtube videos will load while ubo is enabled. turning it off on the page is the only way to get the video to load. turning it back on will eventually stop the video again.

### Other extensions used

none relevant

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 97457
 cosmetic: 39648
 scriptlet: 18544
 html: 1052
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35696-189, now
  ublock-badware: 7881-0, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2182-0, now
  ublock-quick-fixes: 156-5, now
  easylist: 71025-614, now
  easyprivacy: 33171-716, now
  urlhaus-1: 3957-0, now
  plowe-0: 3719-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1749 ms
 maxAssetCacheWait: 169 ms
popupPanel:
 blocked: 21
 network:
  youtube.com: 7
  googlevideo.com: 14
```
</details>

**Comment by stephenhawk8054** [comment]
Can you turn off all other extensions, restart the browser and test again?

Then please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
