### ISSUE TITLE
sojo1049.com: breakage

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#19852]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sojo1049.com/`

### Category

breakage

### Description

Click **listen now** radio not working. Turn off the uBO and check again, now the radio is working.

or **test directly**
`https://sojo1049.com/listen-live/`

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-09-25_102428](https://github.com/uBlockOrigin/uAssets/assets/111344219/8e603d97-76da-4ff8-bb3b-630b5fb852d6)
![2023-09-25_102509](https://github.com/uBlockOrigin/uAssets/assets/111344219/2c05a8ea-adae-4e3d-b89c-9649e365995a)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 114806
 cosmetic: 60763
 scriptlet: 19954
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  RUS-0: 39936-9, now
  easylist: 71023-40, now
  easyprivacy: 33168-153, now
  plowe-0: 3719-1070, now
  ublock-badware: 7879-142, now
  ublock-filters: 34815-172, now
  ublock-privacy: 556-7, now
  ublock-quick-fixes: 165-64, now
  ublock-unbreak: 2130-31, now
  urlhaus-1: 3972-0, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 941 ms (selfie)
 maxAssetCacheWait: 560 ms
popupPanel:
 blocked: 16
 network:
  amazon-adsystem.com: 1
  btloader.com: 1
  doubleclick.net: 1
  dstillery.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  indexww.com: 1
  p-n.io: 1
  pinterest.com: 1
  revcontent.com: 1
  script.ac: 1
  solutionshindsight.net: 1
  teads.tv: 1
  townsquareblogs.com: 1
  twitter.com: 1
 extended:
  ##.tsm-ad
  ###top-not-ads
  ##.google-ads-widget
  ###bottom-not-ads
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/, …
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
add
`@@||yield-op-idsync.live.streamtheworld.com/partnerIds$xhr,domain=player.amperwave.net`

@ryanbr 
due to EL:
`||yield-op-idsync.live.streamtheworld.com^`
