### ISSUE TITLE
21vek.by: cookie

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#19860]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.21vek.by/ebooks/booxfaust5_onyx.html`

### Category

cookie

### Description

Cookie banner. Can this be fixed?

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-09-25_202416](https://github.com/uBlockOrigin/uAssets/assets/111344219/c148a205-eb15-4fad-b4e2-ce8ace21837f)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 116811
 cosmetic: 105949
 scriptlet: 26336
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 48379-227, now
  ublock-annoyances: 5467-59, now
  ublock-cookies-easylist: 297-297, now
 default:
  user-filters: 1-0, never
  RUS-0: 39937-9, now
  easylist: 71058-40, now
  easyprivacy: 33171-153, now
  plowe-0: 3719-1070, now
  ublock-badware: 7879-142, now
  ublock-filters: 34820-184, now
  ublock-privacy: 556-7, now
  ublock-quick-fixes: 156-61, now
  ublock-unbreak: 2135-33, now
  urlhaus-1: 3957-0, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 984 ms (selfie)
 maxAssetCacheWait: 568 ms
popupPanel:
 blocked: 5
 network:
  21vek.by: 1
  flix360.com: 1
  flix360.io: 1
  flixcar.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
test for breakage

```
21vek.by###modal-cookie
21vek.by##body:style(overflow: auto !important;)
```

**Comment by dportvine** [comment]
@ryanbr
