### ISSUE TITLE
computingforgeeks.com: breakage

### ISSUE THREAD

**Issue by shagall512** [uBlockOrigin/uAssets#19865]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://computingforgeeks.com/perform-proper-rsyslog-logs-rotation-using-logrotate/?expand_article=1`

### Category

breakage

### Description

A button "Expand to Show a Full Article" appears if the uBlockOrigin is enabled.  The button  prevents viewing of the full article.  The button does not appear if the uBlockOrigin is not enabled.

### Other extensions used

HTTPS Everywhere
Dark Reader
Video Maximizer
Auto Tab Discard
Wayback Machine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![uBlockOrigin_bugReport_20230925](https://github.com/uBlockOrigin/uAssets/assets/146050329/4342cced-a9f0-4d57-88ca-0f2f5a36a1d0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 124798
 cosmetic: 208780
 scriptlet: 30273
 html: 0
listset (total-discarded, last-updated):
 added:
  RUS-0: 39934-9, 18m
  adguard-cookies: 27669-42, 24m
  adguard-mobile-app-banners: 4639-9, 23m
  adguard-other-annoyances: 13580-42, 22m
  adguard-popup-overlays: 24211-420, 21m
  adguard-social: 21425-919, 19m
  adguard-widgets: 2311-14, 20m
  easylist-annoyances: 3980-212, now
  easylist-chat: 139-11, now
  easylist-newsletters: 6497-414, now
  easylist-notifications: 2674-1451, now
  fanboy-cookiemonster: 48386-3826, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 71029-99, now
  easyprivacy: 33177-253, now
  plowe-0: 3719-1071, now
  ublock-badware: 7874-141, now
  ublock-filters: 34820-557, now
  ublock-privacy: 556-9, now
  ublock-quick-fixes: 157-61, 16m
  ublock-unbreak: 2126-35, now
  urlhaus-1: 3921-0, 17m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 22977 ms (selfie)
 maxAssetCacheWait: 2964 ms
popupPanel:
 blocked: 59
 network:
  computingforgeeks.com: 23
  amazon-adsystem.com: 1
  doubleclick.net: 1
  ezodn.com: 8
  ezoic.net: 21
  googletagmanager.com: 1
  outbrain.com: 1
  pubmatic.com: 1
  quantserve.com: 1
  s-onetag.com: 1
 extended:
  ##.td-scroll-up
  ##.td-social-icon-wrap
  ##.td-icon-facebook
  ##.td-icon-twitter
  ###td-ad-placeholder
  ##.ezoic-adpicker-ad
  ##.ezoic-ad
  ##.adtester-container
  ##.td-icon-instagram
  ##.ezoic-ad-adaptive
  ##.OUTBRAIN
  ##.footer-email-wrap
  ###ezmobfooter
  ##.ezmob-footer
  ##div.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ###ez-sidebar-wall-left
  ##.ez-sidebar-wall-ad
  ##[data-ez-name]
  ##span[data-ez-ph-id]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
/detroitchicago/gateway.js
/detroitchicago/stickyfix.js
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by stephenhawk8054** [comment]
@Yuki2718 I think for ezoic ads?

**Comment by Yuki2718** [comment]
> ```
> /detroitchicago/gateway.js
> /detroitchicago/stickyfix.js
> ```
> 

I don't see them, but see "Expand to Show a Full Article" and other ezoic scripts blocked. BUT I can see full articles if I click the button.
