### ISSUE TITLE
[nsfw] smutty.com: popups

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#19862]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://smutty.com/`

### Category

popups

### Description

adware cookie popups (left click empty space after 3 seconds have passed):
```
https://pastebin.com/raw/9ujHgxgf
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 115
filterset (summary):
 network: 92010
 cosmetic: 42816
 scriptlet: 22678
 html: 1240
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, now
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1739-0, now
  ublock-annoyances: 5427-8, now
 default:
  user-filters: 1946-15, never
  ublock-filters: 35707-214, now
  ublock-badware: 7881-5, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2182-0, now
  ublock-quick-fixes: 163-0, 1h.15m
  easylist: 71058-260, now
  easyprivacy: 33171-1440, now
filterset (user): [array of 923 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 8 redacted]
hostRuleset:
 added: [array of 5 redacted]
 removed:
  behind-the-scene * * noop
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 583 ms (selfie)
 maxAssetCacheWait: 152 ms
 unsuspendAfter: 216 ms
popupPanel:
 blocked: 15
 network:
  aj2218.online: 6
  cdn-static3.com: 2
  cloudflare.com: 4
  googletagmanager.com: 1
  metatrckpixel.com: 2
 extended:
  ##iframe[scrolling="no"]
  ##+js(no-window-open-if)
```
</details>

**Comment by mapx-** [comment]
does this work:

`smutty.com##+js(ra, href, [href^="https://aj2218.online/"], stay)`

**Comment by Daxy7** [comment]
no difference. still popups

**Comment by mapx-** [comment]
I added another filter above
