### ISSUE TITLE
xilften.net [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1986]
URL(s) where the issue occurs

`https://www.xilften.net/filmes/um-lugar-silencioso/`

Describe the issue

![](https://i.imgur.com/FATCc7O.png)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`xilften.net##script:inject(abort-on-property-read.js,smrtSB)`

**Comment by KiLL4FuNK** [comment]
Pop-up
