### ISSUE TITLE
youtube giving blank unskippable ads now

### ISSUE THREAD

**Issue by nanabug412** [uBlockOrigin/uAssets#19866]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I try to use YouTube today all of a sudden I am getting blank ads when I've never gotten an ad on YouTube before. I don't know if it's sensing the ad blocker but either way, the ad is still showing.

### URL(s) where the issue occurs.

https://www.youtube.com/watch?v=oRJQ7wDM5FM
https://www.youtube.com/watch?v=FUwzGGvdTuY

### uBO version

1.51.0

### Browser name and version

Chrome 116.0.5845.140 

### Settings

n/a

**Comment by stephenhawk8054** [comment]
> 1.51.0

Please update uBO to newest version (1.52.0), restart the browser and test again.

Then please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

> - [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
