### ISSUE TITLE
keybr.com: detection

### ISSUE THREAD

**Issue by paulwalker-dev** [uBlockOrigin/uAssets#19870]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.keybr.com/`

### Category

detection

### Description

It detects uBO a couple seconds after loading the page

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2023-09-26 08-15-27](https://github.com/uBlockOrigin/uAssets/assets/61366387/e5b048c1-f0a2-4102-8eff-34173cfa1894)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 117
filterset (summary):
 network: 97438
 cosmetic: 39660
 scriptlet: 18563
 html: 1052
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35716-99, now
  ublock-badware: 7876-0, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2172-1, now
  ublock-quick-fixes: 168-0, now
  easylist: 71052-710, now
  easyprivacy: 33178-716, now
  urlhaus-1: 3921-0, now
  plowe-0: 3719-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 351 ms (selfie)
 maxAssetCacheWait: 88 ms
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  pub.network: 1
```
</details>

**Comment by paulwalker-dev** [comment]
![Screenshot from 2023-09-26 08-15-27](https://github.com/uBlockOrigin/uAssets/assets/61366387/4b1ca71b-3c66-48c5-bfdf-69d0ec58294d)

**Comment by stephenhawk8054** [comment]
You can enable `uBlock filters – Annoyances` list in uBO settings or add these filters as custom filters:

```adb
keybr.com##+js(nostif, , 5000)
keybr.com##+js(nostif, [native code])
keybr.com###keybr_728x90_970x90_ATF:upward(2)
keybr.com###keybr_160x600_Left:upward(2)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.
