### ISSUE TITLE
Problem with design today mail.ru

### ISSUE THREAD

**Issue by Tw9ne** [uBlockOrigin/uAssets#19879]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Today I got underline in my mail page in mail. I mean i have broken design site.

### URL(s) where the issue occurs.

https://e.mail.ru/inbox/

### Screenshot(s)

![Screenshot_1](https://github.com/uBlockOrigin/uAssets/assets/146151524/5192af87-efbd-45dc-a0ec-07c6942a1375)

### Notes

Just fix please

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 114905
 cosmetic: 60771
 scriptlet: 19964
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  RUS-0: 39941-9, 47m
  easylist: 71074-40, 47m
  easyprivacy: 33171-153, 47m
  plowe-0: 3720-1070, 27m
  ublock-badware: 7874-141, 27m
  ublock-filters: 34815-172, 27m
  ublock-privacy: 556-7, 27m
  ublock-quick-fixes: 172-69, 27m
  ublock-unbreak: 2126-31, 27m
  urlhaus-1: 4035-0, 27m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 504 ms (selfie)
 maxAssetCacheWait: 94 ms
```
</details>

**Comment by stephenhawk8054** [comment]
@dimisa-RUAdList Sorry, can you check this?

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/4ad8b2c060f2e4dd42b9e9562356786d2b57fffb
