### ISSUE TITLE
kreator.funnycase.pl: breakage

### ISSUE THREAD

**Issue by quazar-omega** [uBlockOrigin/uAssets#19877]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kreator.funnycase.pl/`

### Category

breakage

### Description

This website has a form to upload images, but the uploading process can't be completed if you don't confirm that you have the rights to the usage of the image. _See screenshot 1_

But the cosmetic filters active on this page prevent you to act on the modal so you can't finish the uploading process. _See screenshot 2_

### Other extensions used

none (tested without them the result is he same, e.g. on Mullvad browser)

### Screenshot(s)

<details>
<summary>Screenshots</summary>

(website as it should look)
![funnycase.pl upload cosmetic filter issue fix](https://github.com/uBlockOrigin/uAssets/assets/56311398/8c1d53c6-2367-47ff-b5ee-39b07682196a)

(website broken by cosmetic filtering)
![funnycase.pl upload cosmetic filter issue](https://github.com/uBlockOrigin/uAssets/assets/56311398/fd023598-7f67-4239-8370-3028f20a41de)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 117
filterset (summary):
 network: 151291
 cosmetic: 186824
 scriptlet: 25930
 html: 1052
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1231-80, now
  adguard-spyware: 60529-17027, now
  adguard-social: 21439-857, now
  adguard-cookies: 27690-55, now
  adguard-popup-overlays: 24237-1443, now
  adguard-mobile-app-banners: 4639-1062, now
  adguard-other-annoyances: 13594-256, now
  adguard-widgets: 2311-1, now
  fanboy-thirdparty_social: 69-0, now
  easylist-annoyances: 3979-117, now
  easylist-chat: 139-11, now
  fanboy-cookiemonster: 48391-3826, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 17-0, never
  ublock-filters: 35724-497, now
  ublock-badware: 7876-0, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2166-2, now
  ublock-quick-fixes: 201-0, now
  easylist: 71074-834, now
  easyprivacy: 33177-811, now
  urlhaus-1: 3997-0, now
  plowe-0: 3719-1, now
filterset (user): [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1275 ms (selfie)
 maxAssetCacheWait: 106 ms
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  hotjar.com: 1
  yandex.ru: 1
 extended:
  ##.consent-container
```
</details>

**Comment by mapx-** [comment]
add

`funnycase.pl#@#.consent-container`

@Alex-302 @ryanbr  (AA / FA)

**Comment by quazar-omega** [comment]
Thank you
