### ISSUE TITLE
uBlock blocks PDF preview on gmail.com

### ISSUE THREAD

**Issue by neuronix** [uBlockOrigin/uAssets#1987]
### Description

PDF preview appears, then disappears after about 1second. Disabling uBlock solves the issue.

### A specific URL where the issue occurs

gmail.com

### Steps to Reproduce

1. Open email with pdf attachment
2. Open pdf preview
3. PDF preview disappears after 1s or so

### Expected behavior:

PDF preview displays permanently like previously.

### Actual behavior:

PDF preview disappears after 1s or so

### Your environment

* uBlock Origin version: 1.15.24
* Browser Name and version: Chrome   65.0.3325.181
* Operating System and version: Win 8.1

**Comment by mapx-** [comment]
- Did you try using only the default setup of uBo ? (no other filter list)
- What filters are triggered in uBo logger ?

**Comment by neuronix** [comment]
So resetting default params and restoring my filters solved the issue. Sorry for the false alarm guys.
