### ISSUE TITLE
strawberriesporail.com: detection

### ISSUE THREAD

**Issue by trashbag9** [uBlockOrigin/uAssets#19876]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://strawberriesporail.com/`
Edit:
`https://strawberriesporail.com/8h6wdixwseuv`

### Category

detection

### Description

Hello, the URL is a domain of voe.sx, they are making new domains ever so often because of ad blockers. The content is not available if it detects an ad blocker, usually updating uBO fixes this but it seems this URL hasn't been added to filterlists.

### Other extensions used

Buster: Captcha Solver for Humans
Dark Reader
KellyC Show YouTube Dislikes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 260621
 cosmetic: 80886
 scriptlet: 34249
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 75046-482, 1m
  adguard-spyware: 60529-1150, 1m
  adguard-spyware-url: 1231-3, 1m
  block-lan: 54-0, 1m
  curben-phishing: 99536-6, 1m
  curben-pup: 189-0, 1m
 default:
  user-filters: 0-0, never
  DEU-0: 7093-0, 1m
  easylist: 71074-1101, 1m
  easyprivacy: 33178-16604, 1m
  plowe-0: 3719-1161, 1m
  ublock-badware: 7874-370, 1m
  ublock-filters: 34832-3900, 1m
  ublock-privacy: 556-138, 1m
  ublock-quick-fixes: 200-89, 1m
  ublock-unbreak: 2119-145, 1m
  urlhaus-1: 3997-2, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 248 ms (selfie)
 maxAssetCacheWait: 129 ms
popupPanel:
 blocked: 2
 network:
  foldingclassified.com: 1
  imasdk.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
provide an example link, we cannot read your display

**Comment by trashbag9** [comment]
> provide an example link, we cannot read your display

my bad, here you go

https://strawberriesporail.com/8h6wdixwseuv
