### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by ShunAn1231** [uBlockOrigin/uAssets#19871]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=7GIXtim-GKU`

### Category

ads

### Description

ads still showing in black screen

### Other extensions used

adobe acrobat(pdf edit)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2023-09-26 at 8 27 51 PM](https://github.com/uBlockOrigin/uAssets/assets/67151466/35ff6600-5f19-4196-b8f7-2a30ab36da5d)

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 140200
 cosmetic: 233012
 scriptlet: 40814
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 25364-135, now
  adguard-cookies: 27680-30, 20m
  adguard-generic: 74998-509, 19m
  adguard-mobile-app-banners: 4639-12, 20m
  adguard-other-annoyances: 13585-9, 20m
  adguard-popup-overlays: 24225-84, 19m
  adguard-social: 21431-914, 19m
  adguard-widgets: 2311-3, 19m
  easylist-annoyances: 3979-226, 19m
  easylist-chat: 139-11, 20m
  easylist-newsletters: 6502-421, 19m
  easylist-notifications: 2674-1444, 20m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 71052-1119, now
  easyprivacy: 33178-286, now
  plowe-0: 3719-1080, now
  ublock-badware: 7874-359, now
  ublock-filters: 34829-4227, now
  ublock-privacy: 556-8, now
  ublock-quick-fixes: 168-64, now
  ublock-unbreak: 2125-96, now
  urlhaus-1: 3997-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1350 ms (selfie)
 maxAssetCacheWait: 719 ms
popupPanel:
 blocked: 437
 network:
  youtube.com: 282
  doubleclick.net: 19
  google.com: 124
  google.com.my: 1
  googlesyndication.com: 11
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytd-action-companion-ad-renderer
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  #@#.video-ads
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/, …
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, google_ad_status, 1)
```
</details>

**Comment by stephenhawk8054** [comment]
> uBlock Origin: 1.51.0

Please update uBO to newest version (1.52.0), restart the browser and test again.

Then please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/7636

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
