### ISSUE TITLE
cashat.net [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1988]
URL(s) where the issue occurs

`https://cashat.net/oVMX7`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`cashat.net##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)`. Timer checked server side.
