### ISSUE TITLE
smallarmsreview.com: breakage

### ISSUE THREAD

**Issue by pierow2k** [uBlockOrigin/uAssets#19887]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://smallarmsreview.com`

### Category

breakage

### Description

Pages will not render.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
N/A - Not a hand-to-describe visual issue
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 96730
 cosmetic: 83446
 scriptlet: 21367
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  fanboy-cookiemonster: 48399-214, now
 default:
  user-filters: 5-0, never
  easylist: 71111-13, now
  easyprivacy: 33181-63, now
  ublock-badware: 7874-141, now
  ublock-filters: 34857-153, now
  ublock-privacy: 556-5, now
  ublock-quick-fixes: 200-85, 1h.18m
  ublock-unbreak: 2119-33, now
  urlhaus-1: 4025-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 35 redacted]
switchRuleset:
 added: [array of 1 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 548 ms (selfie)
 maxAssetCacheWait: 166 ms
popupPanel:
 blocked: 5
 network:
  smallarmsreview.com: 5
 extended:
  ##.jeg_ad
  ##.jeg_ad_top
  ##.jnews_header_top_ads
  ##.ads-wrapper
  ##.jnews-cookie-law-policy
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
smallarmsreview.com#@#.jeg_ad
smallarmsreview.com#@#.jeg_ad_top
smallarmsreview.com#@#.jnews_header_top_ads
```

@ryanbr
