### ISSUE TITLE
linkvertise.com: detection

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#19883]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/865873/fivem-loadingscreen/1`

### Category

detection

### Description

It shows a pop-up saying "Invalid Visit Detected", I tried everything. Switching on another browser, going on a Incognito tab and still not working

### Other extensions used

None related to blocking ads and stuff

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Linkvertise "Invalid Visit Detected"](https://github.com/uBlockOrigin/uAssets/assets/50150516/abb268d0-cb18-4d5a-9109-21f84fdde36d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 97562
 cosmetic: 39740
 scriptlet: 18651
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 75-2, never
  easylist: 71055-13, 6m
  easyprivacy: 33179-63, 6m
  plowe-0: 3720-1066, 6m
  ublock-badware: 7874-141, 6m
  ublock-filters: 34841-141, 6m
  ublock-privacy: 556-6, 6m
  ublock-quick-fixes: 202-94, 1h.23m
  ublock-unbreak: 2119-32, 6m
  urlhaus-1: 4035-0, 6m
filterset (user): [array of 75 redacted]
trustedset:
 added: [array of 106 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 302 ms (selfie)
 maxAssetCacheWait: 157 ms
popupPanel:
 blocked: 15
 network:
  bizseasky.com: 3
  clarity.ms: 1
  criteo.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  media.net: 1
  quantserve.com: 1
  taboola.com: 2
  thinksuggest.org: 2
  typekit.net: 1
 extended:
  ##+js(abort-current-script, addEventListener, DOMNodeRemoved)
  ##+js(abort-current-script, document.dispatchEvent, CustomEvent)
  ##+js(abort-current-script, onload, adsbygoogle)
  ##+js(addEventListener-defuser, load, nextFunction)
  ##+js(json-prune, data.meta.require_addon data.meta.require_capt…
  ##+js(nano-setInterval-booster)
  ##+js(set-constant, isAdBlockActive, false)
```
</details>

**Comment by RazorVA69** [comment]
`https://linkvertise.com/939795/xGsIOtiaMHMg`
Click get link > watch ad > popup and waiting timer before getting success

**Comment by ghost** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/27472
