### ISSUE TITLE
yhmgo.com: ads

### ISSUE THREAD

**Issue by ShunAn1231** [uBlockOrigin/uAssets#19889]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.yhmgo.com/vp/14112-1-12.html`

### Category

ads

### Description

can these ads that are in the video gets block?(photo as refrence)

### Other extensions used

adobe acrobat pdf reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-09-28 at 2 42 24 PM](https://github.com/uBlockOrigin/uAssets/assets/67151466/cfd9d1bb-4b85-4db5-a063-0d3d73dcde8d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 112268
 cosmetic: 49997
 scriptlet: 18816
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 25392-136, now
 default:
  user-filters: 0-0, never
  easylist: 71106-22, now
  easyprivacy: 33183-77, now
  plowe-0: 3720-1069, now
  ublock-badware: 7874-141, now
  ublock-filters: 34851-156, now
  ublock-privacy: 556-6, now
  ublock-quick-fixes: 213-93, now
  ublock-unbreak: 2119-33, now
  urlhaus-1: 3946-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4007 ms
 maxAssetCacheWait: 779 ms
popupPanel:
 blocked: 1
 network:
  bdstatic.com: 1
```
</details>

**Comment by mapx-** [comment]
- I get no ad using a Taiwan ip
- force update all the filter lists, test again

**Comment by liamengland1** [comment]
There is an ad directly embedded in the video manifest at this time. Cannot be blocked

![image](https://github.com/uBlockOrigin/uAssets/assets/16567977/bd94bdc2-c1c8-4b7a-a68e-79ca05e0edb0)

**Comment by stephenhawk8054** [comment]
Yeah, this is the m3u8 content: https://logpasta.com/paste/raw/e03eb340-a56a-4865-a74a-e74c48909395.txt . I don't see anything that can distinguish the ads.

**Comment by mapx-** [comment]
@stephenhawk8054 
test
`yhmgo.com##+js(m3u-prune, /fc997a5dd6101o.*\.ts/, .m3u8)`

it's some pattern:

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/09a9e74c-0270-4e3f-a8c2-741e1341850c)

**Comment by stephenhawk8054** [comment]
Ah I see, they use `o` instead of `0`, tricky. I'll test it.

**Comment by stephenhawk8054** [comment]
@mapx- It works for me

**Comment by mapx-** [comment]
Idk how to test on other shows, maybe this could be more general

`yhmgo.com##+js(m3u-prune, /[a-z0-9]{13}o.*\.ts/, .m3u8)`

**Comment by stephenhawk8054** [comment]
That looks good enough, I think we can adjust it if there are other reports

**Comment by mapx-** [comment]
another one, totally different
`https://www.yhmgo.com/vp/23272-1-1.html`

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/2ca865f8-de60-4e93-a087-f07450405666)

**Comment by mapx-** [comment]
weird, idk why this does not work (regex101 it's ok)

`yhmgo.com##+js(m3u-prune, /[a-z0-9]{13}o.*\.ts|.*[0-9]{15,}\.ts/, .m3u8)`

```
#EXTINF:3,
0001157.ts
#EXTINF:3,
0001158.ts
#EXTINF:1.64,
0001159.ts
#EXT-X-DISCONTINUITY
#EXTINF:3,
/video/adjump/time/16958325720490000000.ts
#EXTINF:3,
/video/adjump/time/16958325720500000001.ts
#EXTINF:3,
/video/adjump/time/16958325720500000002.ts
#EXTINF:3,
/video/adjump/time/16958325720500000003.ts
#EXT-X-DISCONTINUITY
#EXTINF:3,
0001160.ts
#EXTINF:3,
0001161.ts
```

**Comment by stephenhawk8054** [comment]
@mapx- Does this work?

```adb
yhmgo.com##+js(m3u-prune, /[a-z0-9]{13}o.*\.ts|adjump/, .m3u8)
```

**Comment by mapx-** [comment]
yes .. I don't understand why my filter does not work

**Comment by stephenhawk8054** [comment]
Hmm... Yeah, weird, it should match

**Comment by mapx-** [comment]
@gorhill 

could you clarify why

`.*[0-9]{15,}\.ts` does not work
`yhmgo.com##+js(m3u-prune, /[a-z0-9]{13}o.*\.ts|.*[0-9]{15,}\.ts/, .m3u8)`

and `adjump` works
`yhmgo.com##+js(m3u-prune, /[a-z0-9]{13}o.*\.ts|adjump/, .m3u8)`

test case: `https://www.yhmgo.com/vp/23272-1-1.html`

**Comment by stephenhawk8054** [comment]
@mapx- Oh wait, looks like we forgot to escape `,` again

**Comment by mapx-** [comment]
oh god ...

**Comment by mapx-** [comment]
however, it's ok with adjump too ;)

**Comment by ShunAn1231** [comment]
so guys, are there any way to block this type of ads?

**Comment by stephenhawk8054** [comment]
@ShunAn1231 Force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again

**Comment by ShunAn1231** [comment]
ok, no need to click any filters right
