### ISSUE TITLE
seznamzpravy.cz: ads

### ISSUE THREAD

**Issue by LitleLily** [uBlockOrigin/uAssets#19882]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.seznamzpravy.cz/`

### Category

ads

### Description

Hello, I'm sorry for not knowing the lingo, I'll just describe it the best I can. 

`https://www.seznamzpravy.cz` still shows very agressive ads even after blocking the element milion times.

Once I block the element through the element selection, new block of ads appear after a few seconds. I found out that deleting whole string in page code resolves the problem (until I try to reload the page). Is there anything I can do in uBlock to block this string automatically? Please find the string below. Thank you very much for your time~

```html
<section aria-labelledby="accessibility-sidebar-bottom-content" class="b_hB b_f7" role="complementary"><h6 id="accessibility-sidebar-bottom-content" class="e_h e_bh">Postranní panel</h6><div class="b_jM" data-utstvwuvrtrtownvttv="tpl-bottomSidebar"><div class="c_jY _608be5c71763ce6e774d9b13"><style>._608be5c71763ce6e774d9b13 { display: flex; height: 100%; }</style><div class="c_fY c_f9"><div class="c_fY c_fZ"><div class="c_eb c_f1" style="top: 82px;"><div class="eceefkkdekchlkccfek inmplikimihpinokpjjh"><div class="g_eb" data-vywrsqqqrpuxxvywpxu="eceefkkdekchlkccfek" data-mpnmsmqjjrjmqlnnrqo="68386" style="max-width: 300px;"><p class="e_bo e_bp e_bt">Rek̀lama</p><div class="d_F"><div class="e_jg" style="padding-top: 200%;"></div><div class="e_N"><div class="g_bF ddlgigickdhgeeicdkhj" style="width: 300px; max-width: 100%;" id="sznssp-68386-2">
		<div class="cbbeegfbbbgbjkihdkck" style="width: 100%; height: 100%; position:relative;">
			<div class="svtwtrwpsowuwovqpuw" data-inqmhhnoolhloijnlonm="ad-content" style="width: 300px; height: 600px;"><ll-vhjh><iframe class="aqbtratpq eoersfbcs wmhggcfrw" width="299.844478381825" height="599.5317404450544" id="sf1" style="
			display: block;
      width: 100%;
			height: 100%;
		" src="https://www.seznamzpravy.cz/aif0bL8v7b_orSrv7C8_7KrS4_lbRCW_Pc/jpf7_b3ibkltr3rzfskl_ik/imp?k=4cf89872-36c5-4821-8f80-7dfcaf14367c&amp;phf7mn3kk3ebr3ruf_pssp1=kE3Czl8XcTUYp3UyUyxFGv6G8_dgnIHjlFDbGnA2SBmtIYfPxyUL" sagmmqmrw=""></iframe></ll-vhjh></div>
			
		</div>
	</div></div></div></div></div></div></div></div></div></div></section>
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/146171791/84a196a7-cd99-4f56-a56a-2aa44807b880)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 97786
 cosmetic: 40027
 scriptlet: 18817
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 13-0, never
  CZE-0: 745-1, now
  easylist: 71053-15, now
  easyprivacy: 33178-69, now
  plowe-0: 3720-1066, now
  ublock-badware: 7874-141, now
  ublock-filters: 34838-141, now
  ublock-privacy: 556-6, now
  ublock-quick-fixes: 200-84, 59m
  ublock-unbreak: 2119-32, now
  urlhaus-1: 4035-0, now
filterset (user): [array of 13 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1563 ms (selfie)
 maxAssetCacheWait: 433 ms
popupPanel:
 blocked: 10
 no-large-media: true
 no-popups: true
 network:
  gemius.pl: 3
  googletagmanager.com: 1
  sdn.cz: 1
  seznam.cz: 5
 extended:
  ##._608bda591f6bec0a182319f3.c_jY > .c_f9.c_fY > div.c_fZ.c_fY >…
  ##div.c_fZ.c_fY:nth-of-type(3)
  ##+js(addEventListener-defuser, message, fishing)
  ##.drtg__shop > [href^="https://www.seznamzpravy.cz/pff0bL_orSrv…
  ##.drtg__shop-wrapper
  ##+js(abort-on-property-write, Fisher)
  ##+js(no-setTimeout-if, 0x)
```
</details>

**Comment by mapx-** [comment]
reset uBO to default settings / filter lists, remove / disable your custom filters, test again

**Comment by mapx-** [comment]
Where do you get the ads ? home page ? specific pages ?

**Comment by LitleLily** [comment]
> Where do you get the ads ? home page ? specific pages ?

All of them - home page and every article I open

**Comment by LitleLily** [comment]
> ||seznamzpravy.cz/$frame,1p

At first this looked well - the page loaded normally and the place where the first ad would be was empty. But when I scrolled down past the point where the ad would previously end, whole page suddenly broke down and only reloading returned it to its intended look (but scrolling down breaks it again). Please see the attached screenshots for reference

![image](https://github.com/uBlockOrigin/uAssets/assets/146171791/1a1ba9ce-4710-4a26-8fe7-d688596e4c09)
![image](https://github.com/uBlockOrigin/uAssets/assets/146171791/cceacece-ad92-42b2-b1f0-3e144978bf51)

**Comment by mapx-** [comment]
open uBO logger, repeat the steps to get the breakage, go into the logger and post here what items (what frames especially) are blocked

**Comment by mapx-** [comment]
test also (disabling the filter above)

`seznamzpravy.cz##+js(rmnt, script, $IMA.Cache)`
