### ISSUE TITLE
[nsfw] legacy.sankakucomplex.com: detection

### ISSUE THREAD

**Issue by Itsalifestyle** [uBlockOrigin/uAssets#19880]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://legacy.sankakucomplex.com/`

### Category

detection

### Description

Detects adblock, then redirects to new webpage encouraging a disabling of adblock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium Mobile: 116
filterset (summary):
 network: 98999
 cosmetic: 30797
 scriptlet: 18672
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  adguard-mobile: 8663-38, 21h.30m
  easylist: 71058-16008, 21h.30m
  easyprivacy: 33174-72, 21h.30m
  plowe-0: 3720-1141, 1h.11m
  ublock-badware: 8025-147, 2d.22h.3m
  ublock-filters: 35101-390, 2d.22h.2m
  ublock-privacy: 559-7, 5d.7h.28m
  ublock-quick-fixes: 172-76, 8h.19m
  ublock-unbreak: 2128-34, 2d.22h.1m
  urlhaus-1: 3921-0, 21h.29m
filterset (user): [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5554 ms (selfie)
 maxAssetCacheWait: 759 ms
popupPanel:
 blocked: 1
 network:
  sankakucomplex.com: 1
 extended:
  ##+js(remove-node-text, script, /Post\..+?display/)
  ##+js(abort-current-script, Post.detect, show)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
  ##+js(replace-node-text, script, /.*_0x.*/, closeThis();)
```
</details>

**Comment by mapx-** [comment]
force update all your filter lists

**Comment by Itsalifestyle** [comment]
> force update all your filter lists

Can't. I'm using the extension on mobile.

**Comment by mapx-** [comment]
It's the same thing as for desktop:

- go into addons section, uBO
- settings
- filter lists 

tap that icon, then the second one
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/cf4906ec-aadb-4f33-9631-cf025de8d029)

**Comment by Itsalifestyle** [comment]
The problem is now solved. It did exist at time of creating this thread. Thanks.
