### ISSUE TITLE
ledevoir.com: breakage

### ISSUE THREAD

**Issue by kingtong** [uBlockOrigin/uAssets#19885]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ledevoir.com/`

### Category

breakage

### Description

Breakage:
- Categories do not show in header
- Login, subscription and donation sections do not show
- Search is broken
<img width="2040" alt="Screenshot 2023-09-27 at 16 42 25" src="https://github.com/uBlockOrigin/uAssets/assets/288015/bfec2ff8-86a1-46cf-a874-4fd1b540d6e6">

After disabling UBO:
<img width="2030" alt="Screenshot 2023-09-27 at 16 42 56" src="https://github.com/uBlockOrigin/uAssets/assets/288015/8002126a-d562-47a4-8a81-66f71f34dfc5">

### Other extensions used

Cookie AutoDelete
1Password
FoxiProxy Standard
Kagi Search

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Firefox: 117
filterset (summary):
 network: 126197
 cosmetic: 195888
 scriptlet: 25453
 html: 1057
listset (total-discarded, last-updated):
 added:
  adguard-social: 21459-855, now
  adguard-cookies: 27701-55, 37m
  adguard-popup-overlays: 24480-1452, now
  adguard-mobile-app-banners: 4640-1062, 40m
  adguard-other-annoyances: 13597-256, 39m
  adguard-widgets: 2311-1, 36m
  easylist-annoyances: 3979-117, now
  easylist-chat: 139-11, now
  fanboy-cookiemonster: 48395-3829, now
  easylist-newsletters: 6503-13, now
  easylist-notifications: 2675-3, now
  fanboy-social: 16219-11, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35743-587, now
  ublock-badware: 7876-0, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2166-1, now
  ublock-quick-fixes: 218-0, now
  easylist: 71092-841, now
  easyprivacy: 33180-812, now
  urlhaus-1: 4025-0, now
  plowe-0: 3720-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 544 ms (selfie)
 maxAssetCacheWait: 321 ms
popupPanel:
 blocked: 23
 network:
  ledevoir.com: 6
  aticdn.net: 2
  cxense.com: 1
  freeskreen.com: 2
  google-analytics.com: 1
  google.com: 1
  googletagmanager.com: 1
  jwpcdn.com: 2
  jwpltx.com: 2
  m32.media: 4
  npttech.com: 1
 extended:
  ##.header-pub
  ##.footer-pub
  ###fb-root:not(body):not(html)
  ##.jw-settings-sharing
  ##.jw-submenu-sharing
```
</details>

**Comment by mapx-** [comment]
add

`@@||ledevoir.com/js/web-push.js$script,1p`

@ryanbr

**Comment by ghost** [comment]
Header moving down, then back to normal after 5 seconds

<details>

![Image](https://github.com/user-attachments/assets/c88d48a2-5cb9-4d19-bff4-54b050da9e71)

```yaml
uBlock Origin: 1.69.0
Chromium: 144
filterset (summary):
 network: 185847
 cosmetic: 132643
 scriptlet: 43817
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-experimental: 6-0, 1h.13m
  adguard-cookies: 36722-78, 5h.34m
  ublock-cookies-adguard: 5390-75, 5h.34m
  fanboy-cookiemonster: 45178-3616, 5h.34m
  ublock-cookies-easylist: 5390-5390, 5h.34m
  easylist-annoyances: 5029-122, 2h
  easylist-chat: 258-0, 2h
  easylist-newsletters: 9010-32, 2h
  easylist-notifications: 2459-8, 2h
  ublock-annoyances: 4737-63, 1d.1h.16m
  FRA-0: 19581-313, never
  fanboy-ai-suggestions: 133-2, 2h
 default:
  user-filters: 66-1, never
  ublock-filters: 44152-88, 1h.13m
  ublock-badware: 10769-31, 1h.13m
  ublock-privacy: 3603-3, 1h.13m
  ublock-unbreak: 2724-1, 1h.13m
  ublock-quick-fixes: 421-0, 1h.13m
  easylist: 91594-507, 5h.35m
  easyprivacy: 55304-768, 5h.35m
  urlhaus-1: 26280-6, 5h.35m
  plowe-0: 3503-3, 5h.34m
  ROU-1: 1680-19, 2h
filterset (user): [array of 61 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 284 ms (selfie)
 maxAssetCacheWait: 101 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 13
 network:
  ledevoir.com: 1
  aticdn.net: 1
  cxense.com: 3
  ebxcdn.com: 1
  googletagmanager.com: 1
  jwpcdn.com: 2
  jwpltx.com: 1
  m32.media: 1
  npttech.com: 1
  privacy-center.org: 1
```
</details>

**Comment by mapx-** [comment]
```adb
###top-publicite-placeholder
```

@smed79

**Comment by nqlp** [comment]
Entering page goes like this: 

<details>

<img width="1440" height="662" alt="Image" src="https://github.com/user-attachments/assets/2b1e2d3a-6abe-4a1b-9248-c8b2f5111146" />

</details>

Scrolling down goes like this:

<details>

<img width="1437" height="660" alt="Image" src="https://github.com/user-attachments/assets/013afb87-f9e8-4266-bb1f-9613c0e74eeb" />

</details>

<details>

```yml

uBlock Origin: 1.71.0
Chromium: 149
filterset (summary):
 network: 179752
 cosmetic: 173759
 scriptlet: 55730
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-experimental: 11-0, now
  adguard-cookies: 38838-108, now
  ublock-cookies-adguard: 5703-80, now
  fanboy-cookiemonster: 46913-3869, now
  ublock-cookies-easylist: 5703-5703, now
  adguard-popup-overlays: 31595-230, now
  adguard-mobile-app-banners: 7490-105, now
  adguard-other-annoyances: 16131-195, now
  easylist-annoyances: 5224-384, now
  easylist-notifications: 2511-613, now
  ublock-annoyances: 5047-163, now
  FRA-0: 16758-263, now
 default:
  user-filters: 2-0, never
  ublock-filters: 51531-85, now
  ublock-badware: 10384-28, now
  ublock-privacy: 4053-4, now
  ublock-unbreak: 2768-1, now
  ublock-quick-fixes: 440-0, 5m Δ
  easylist: 88756-474, now
  easyprivacy: 55838-713, now
  urlhaus-1: 24165-11, 5m
  plowe-0: 3504-1, now
filterset (user): [array of 2 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 492 ms (selfie)
 maxAssetCacheWait: 178 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 833
 network:
  github.com: 833
```

</details>
