### ISSUE TITLE
fluttercampus.com: detection

### ISSUE THREAD

**Issue by grazzi-guzzi** [uBlockOrigin/uAssets#19886]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fluttercampus.com/`

### Category

detection

### Description

Detects and puts a big red notification on usage of  "ad blocker"
also links to  `http://blockadblock.com/ `

### Other extensions used

PrivacyBadger
LocalCDN

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 99053
 cosmetic: 43380
 scriptlet: 19048
 html: 0
listset (total-discarded, last-updated):
 added:
  spa-1: 5626-65, now
 default:
  user-filters: 0-0, never
  easylist: 71111-13, now
  easyprivacy: 33181-63, now
  plowe-0: 3720-1067, now
  ublock-badware: 7874-141, now
  ublock-filters: 34857-170, now
  ublock-privacy: 556-6, now
  ublock-quick-fixes: 216-99, now
  ublock-unbreak: 2119-33, now
  urlhaus-1: 4025-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 64 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 709 ms (selfie)
 maxAssetCacheWait: 162 ms
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
try disabling PrivacyBadger (you can even remove it, useless if you use uBO)
