### ISSUE TITLE
notalwaysright.com: breakage

### ISSUE THREAD

**Issue by fernewelten** [uBlockOrigin/uAssets#19898]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints. ←← nice try 😎

### URL address of the web page

`https://notalwaysright.com/newest/`

### Category

breakage

### Description

For the test, I reverted ublock origin to factory settings.

The website shows a dark grey overlay over all the page, preventing all clicks on anything. 
When I turn ublock origin off and reload, the website shows a “consent” banner, so ublock seems to remove this banner mechanism incompletely when running.

I __usually__ use ublock with the following settings:
[ublock-sicherung_2023-09-28_23.19.25.txt](https://github.com/uBlockOrigin/uAssets/files/12754113/ublock-sicherung_2023-09-28_23.19.25.txt)
When I do, then grey overlay problem does __not__ show up – but the website recognizes that ublock origin has been installed and shows a banner that says as much.

### Other extensions used

(none)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

ublock enabled, factory settings:
![image](https://github.com/uBlockOrigin/uAssets/assets/41213694/191ee50c-1839-46c1-b0a2-096ea6f9263c)

ublock disabled, factory settings:
![image](https://github.com/uBlockOrigin/uAssets/assets/41213694/d86981d8-c8d3-4c3e-914f-74a2f61bff81)

ublock enabled, my usual settings:
![image](https://github.com/uBlockOrigin/uAssets/assets/41213694/d95b75b2-b792-4ded-9a81-c755e40eacf9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 107220
 cosmetic: 44419
 scriptlet: 18668
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7094-0, 2m
  easylist: 71185-19, 2m
  easyprivacy: 33183-72, 2m
  plowe-0: 3721-1068, 2m
  ublock-badware: 7874-141, 2m
  ublock-filters: 34865-155, 2m
  ublock-privacy: 556-6, 2m
  ublock-quick-fixes: 234-102, 2m
  ublock-unbreak: 2123-34, 1m
  urlhaus-1: 11215-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 565 ms
 maxAssetCacheWait: 220 ms
popupPanel:
 blocked: 8
 network:
  gaug.es: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  proper.io: 1
  script.ac: 1
  videoplayerhub.com: 1
  wp.com: 1
 extended:
  ##.proper-ad-unit
  ##.code-block
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by Cygnata** [comment]
Can confirm, it's the entire NAR website.

**Comment by liamengland1** [comment]
I tested on factory settings with VPN to Germany and did not reproduce the issue

**Comment by fernewelten** [comment]
> I tested on factory settings with VPN to Germany and did not reproduce the issue

Can confirm that I'm no longer experiencing the problem either (using my usual settings rather than factory settings). Something they fixed on __their__ end? Some filter changes for other reasons that made __this__ problem go away, too?
