### ISSUE TITLE
mtv.fi: detection

### ISSUE THREAD

**Issue by Castelen** [uBlockOrigin/uAssets#19896]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mtv.fi/sarja/grand-designs-suomi-5055/jakso-1-talo-kuin-bumerangi-20685282`

### Category

detection

### Description

Adblock detector detects uBO

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105033
 cosmetic: 41768
 scriptlet: 18596
 html: 1063
listset (total-discarded, last-updated):
 added:
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, never
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, never
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 0-0, never
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 2m
  https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 2m
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt: 0-0, never
  FIN-0: 2208-0, 2m
  ublock-quick-fixes: 230-1, 2m
 default:
  user-filters: 103-7, never
  ublock-filters: 35746-134, 2m
  ublock-badware: 7876-0, 2m
  ublock-privacy: 586-0, 2m
  ublock-unbreak: 2170-1, 2m
  easylist: 71141-711, 2m
  easyprivacy: 33183-717, 2m
  plowe-0: 3721-2, 2m
  urlhaus-1: 11215-0, 2m
filterset (user): [array of 103 redacted]
trustedset:
 added: [array of 71 redacted]
 removed:
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 13463 ms (selfie)
 maxAssetCacheWait: 206 ms
popupPanel:
 blocked: 13
 network:
  adobedtm.com: 7
  cedexis.com: 1
  demdex.net: 1
  omtrdc.net: 1
  sentry.io: 3
```
</details>

**Comment by mapx-** [comment]
@peace2000

**Comment by peace2000** [comment]
I see no issues. No ads or anti adblock nags.

@Castelen Can you provide a screenshot?

**Comment by Castelen** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/10216493/5a2c9aaf-904a-4fb0-b1ce-0da4a0b7a601)
I did further investigating and found out that the issue is not caused by uBO, there is something else going on.
On Firefox I get the same error using "private browsing" window with ubo & all other addons completely disabled.
With Chrome it works fine with ublock on. Ads are blocked & video plays.

I'll close the issue since it's not caused by uBO.

**Comment by Castelen** [comment]
Found the culprit. It's the Firefox built in "Browser Privacy" settings which I have on a "Strict" setting, they block trackers which mtv.fi doesn't like.

**Comment by D4niloMR** [comment]
I can reproduce without account in `https://www.mtv.fi/uutiset`, though

with uBO:
https://github.com/uBlockOrigin/uAssets/assets/70459964/41259c8f-78db-472e-a27a-866fa048c20a

Without uBO:
https://github.com/uBlockOrigin/uAssets/assets/70459964/fa6e092c-e863-4b3f-9530-3f495041b36b

**Comment by stephenhawk8054** [comment]
@D4niloMR Did you enable `Adblock List for Finland` list?

**Comment by D4niloMR** [comment]
> https://www.mtv.fi/uutiset

No, sorry... just enabled here and it's gone
