### ISSUE TITLE
cbc.ca: breakage

### ISSUE THREAD

**Issue by johnbsirius** [uBlockOrigin/uAssets#19899]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cbc.ca/kids/games`

### Category

breakage

### Description

Trying to click on any of the game links does nothing. However, right-clicking a link, then selecting "Open in new tab" works as intended. I am also able to play the games. 

The only way I have found to make the site work is by disabling uBO for that particular site.

I manage a computer lab that over 320 TK through 3rd grade students use, and would love to not have to apply this setting manually 320 times. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 104888
 cosmetic: 39692
 scriptlet: 18666
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71189-13, 14m
  easyprivacy: 33183-63, 14m
  plowe-0: 3721-1067, 14m
  ublock-badware: 7874-141, 14m
  ublock-filters: 34860-141, 14m
  ublock-privacy: 556-6, 14m
  ublock-quick-fixes: 228-96, 14m
  ublock-unbreak: 2123-32, 13m
  urlhaus-1: 11215-0, 13m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 508 ms
 maxAssetCacheWait: 8 ms
popupPanel:
 blocked: 22
 network:
  cbc.ca: 4
  amplitude.com: 3
  chartbeat.com: 2
  conductrics.com: 1
  cxense.com: 1
  demdex.net: 8
  google-analytics.com: 1
  googletagmanager.com: 1
  scorecardresearch.com: 1
 extended:
  ##+js(abort-on-property-write, xhr.prototype.realSend)
```
</details>

**Comment by liamengland1** [comment]
Ah yes, let's put important site nav functionality in a callback to a third party analytics, what could go wrong
![image](https://github.com/uBlockOrigin/uAssets/assets/16567977/a3cca1a3-5a91-47cb-b026-6739ee22bd68)


`@@||www.googletagmanager.com/gtag/js$script,domain=www.cbc.ca` works for me however
or `cbc.ca##+js(aeld, click, /event_callback=function\(\){window\.location=t\.getAttribute\("href"\)/)`

Could `event_callback` could be implemented in the uBO GTM shim ?

**Comment by stephenhawk8054** [comment]
```adb
cbc.ca##+js(aeld, click, /event_callback=function\(\){window\.location=t\.getAttribute\("href"\)/)
```

It works for me

**Comment by johnbsirius** [comment]
Wow I was not expecting any response so quickly... Thank you so much fellas. While I'm still learning how to program, in the time it took you all to resolve this, I put together a GUI script written in AppleScript that managed to add the URL to the whitelist for each student account. Still manual, but less manual...

So should I remove the website from the whitelist? I’m not familiar with this stuff (nor am I qualified to manage a computer lab but the school needs all the help it can get.) 

Again, I really appreciate your effort. Thank you all.

**Comment by stephenhawk8054** [comment]
@johnbsirius You can enable uBO back, then force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.
