### ISSUE TITLE
gainbtc.click: detection

### ISSUE THREAD

**Issue by nishizawa22** [uBlockOrigin/uAssets#19891]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gainbtc.click/login`

### Category

detection

### Description

detection if allow adb
![image](https://github.com/uBlockOrigin/uAssets/assets/141770991/144994e0-fb60-415a-b7a9-21117c1cc427)

### Other extensions used

just ubo

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 97534
 cosmetic: 39688
 scriptlet: 18663
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71106-13, now
  easyprivacy: 33183-63, now
  plowe-0: 3721-1067, now
  ublock-badware: 7874-141, now
  ublock-filters: 34855-141, now
  ublock-privacy: 556-6, now
  ublock-quick-fixes: 228-96, now
  ublock-unbreak: 2123-32, now
  urlhaus-1: 3943-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1732 ms (selfie)
 maxAssetCacheWait: 759 ms
popupPanel:
 blocked: 3
 network:
  cryptocoinsad.com: 2
  surfe.pro: 1
```
</details>

**Comment by nishizawa22** [comment]
> This req login, someone with account will fix
> 
> please comment in dedicated thread #17361

this not shorrtner, I got information that apart from shortner, it's not there, but it's in assets. so dizzy
![image](https://github.com/uBlockOrigin/uAssets/assets/141770991/7a633b39-c1f8-4453-be29-f080173425d3)
https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-6981176

**Comment by mapx-** [comment]
@nishizawa22 

test this filter

`gainbtc.click##+js(nosiif, innerHTML)`

**Comment by nishizawa22** [comment]
not work, still detection

**Comment by nishizawa22** [comment]
for `gainbtc.click` for now condition, detection again. need update filter
