### ISSUE TITLE
[nsfw] pig69.com: detection

### ISSUE THREAD

**Issue by qupo1** [uBlockOrigin/uAssets#19890]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pig69.com/upload/en/bEPJC4FRm7ZBx1R-ABF-031.jpg`

### Category

detection

### Description

After loading, Blocker detection popup will be showed.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.3b0
Firefox: 120
filterset (summary):
 network: 285388
 cosmetic: 238283
 scriptlet: 45301
 html: 1246
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/Yuki2718/adblock2/main/japanese/jpf-plus.txt: 752-5, now
  adguard-generic: 77491-4517, now
  adguard-spyware-url: 1231-81, now
  adguard-spyware: 60532-1359, now
  block-lan: 54-0, now
  curben-phishing: 96324-21, now
  curben-pup: 189-0, now
  adguard-social: 21541-52, now
  adguard-cookies: 27714-46, now
  ublock-cookies-adguard: 301-4, now
  adguard-popup-overlays: 24484-1137, now
  adguard-mobile-app-banners: 4641-18, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 11-0, never
  ublock-filters: 35747-51, now
  ublock-badware: 7876-1, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2170-1, now
  ublock-quick-fixes: 233-89, now
  easylist: 71106-1268, now
  easyprivacy: 33183-16606, now
  urlhaus-1: 11490-0, now
  plowe-0: 3721-1514, now
  JPN-1: 13433-118, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 73 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 extensionUpdateForceReload: true
supportStats:
 allReadyAfter: 439 ms (selfie)
 maxAssetCacheWait: 374 ms
popupPanel:
 blocked: 13
 network:
  googletagmanager.com: 1
  magsrv.com: 12
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href*="pinterest.com/pin/create/button"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##.social-Facebook
  ##.social-linkedin
  ##.social-pinterest
```
</details>

**Comment by ScarletIce17** [comment]
website is still detecting ublock
