### ISSUE TITLE
blablacar.com.tr: nuisance

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#19894]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.blablacar.com.tr/`

### Category

nuisance

### Description

cookie warning

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedasfasdfgadgadfgScreenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/e9f2ff89-043a-4bca-b55b-d064df901dc0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 110991
 cosmetic: 122074
 scriptlet: 26750
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 3982-32, 31m
  easylist-chat: 139-0, 31m
  easylist-newsletters: 6504-15, 31m
  easylist-notifications: 2676-80, 31m
  fanboy-cookiemonster: 48400-222, 31m
  fanboy-social: 16224-12, 31m
  fanboy-thirdparty_social: 68-15, 31m
  ublock-annoyances: 5476-78, 31m
  ublock-cookies-easylist: 301-301, 31m
 default:
  user-filters: 0-0, never
  TUR-0: 13761-9, 31m
  easylist: 71141-33, 31m
  easyprivacy: 33183-155, 31m
  plowe-0: 3721-1068, 31m
  ublock-badware: 7874-141, 31m
  ublock-filters: 34860-168, 31m
  ublock-privacy: 556-8, 31m
  ublock-quick-fixes: 228-97, 31m
  ublock-unbreak: 2123-37, 31m
  urlhaus-1: 11215-0, 31m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 300 ms (selfie)
 maxAssetCacheWait: 145 ms
popupPanel:
 blocked: 18
 network:
  blablacar.com: 1
  datadome.co: 1
  google.com: 14
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
already fixed by [AdGuard – Cookie Notices](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-cookies)
