### ISSUE TITLE
Consider adding "standard" headers in all the lists hosted here

### ISSUE THREAD

**Issue by BilBg** [uBlockOrigin/uAssets#1990]
### URL(s) where the issue occurs

https://github.com/uBlockOrigin/uAssets/tree/master/filters

### Describe the issue

No "standard" headers in files.
Consider adding some info similar to other popular lists (especially `Last modified` / `TimeUpdated`), e.g. like this:

```
! Version: 201804151950
! Title: EasyList
! Last modified: 15 Apr 2018 19:50 UTC
! Expires: 4 days (update frequency)
! Homepage: https://easylist.to/
! Licence: https://easylist.to/pages/licence.html
!
! Please report any unblocked adverts or problems
! in the forums (https://forums.lanik.us/)
! or via e-mail (easylist.subscription@gmail.com).
```

```
! Title: AdGuard English filter
! Description: Filter list that specifically removes adverts on English language websites. English filter is supposed to work along with EasyList.
! Version: 2.0.5.6
! TimeUpdated: 2018-04-16T06:04:20+00:00
! Expires: 2 days (update frequency)
! Homepage: http://adguard.com/filters.html#english
! License: http://creativecommons.org/licenses/by-sa/3.0/
```

Which tags to include, in what order, exact wording (`Last modified` / `TimeUpdated`), date/time format (I prefer ISO 2018-04-16) have to be discussed/decided.

Also if the header will be unified (looking the "same") in all the files.

### Notes
The file `filters.txt` have inside `# Last updated: 2017-10-10` which I think is not true:
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt

**Comment by WowDude** [comment]
> @BilBg : 
> Notes
> 
> The file filters.txt have inside # Last updated: 2017-10-10 which I think is not true:
> https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt


 I think that the date refers not to the whole filters list but to `google.*` filters block only, coz as seen the fiters in the list are placed in blocks, and each block begins with either `#` or `!` comment line/s.

**Comment by mapx-** [comment]
You should post your considerations here:
https://www.reddit.com/r/uBlockOrigin/

or here:
https://github.com/uBlockOrigin/uBlock-issues/issues

@gorhill
