### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by AydanOM** [uBlockOrigin/uAssets#19909]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=CqV4n2qO3wk`

### Category

ads

### Description

Youtube is still playing ads before videos. The video part of the ad is not visible, but the audio still plays, and the ad banner is visible.

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/146471448/26173262-87f6-4543-a22f-63f15e2d6ab4)

### Configuration

<details>

```yaml
AdNauseam: 3.17.0
Firefox: 118
filterset (summary): 
  network: 94951
  cosmetic: 40036
  scriptlet: 18607
  html: 1054
listset (total-discarded, last-updated): 
  removed: 
    eff-dnt-whitelist: null
  added: 
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-75, never
  default: 
    user-filters: 3-1, never
    adnauseam-filters: 515-2, 5h.20m
    ublock-filters: 35725-126, 2d.3h.26m
    ublock-badware: 7861-0, 2d.3h.26m
    ublock-privacy: 588-0, 8d.14h.18m
    ublock-unbreak: 2161-1, 1d.6h.39m
    ublock-quick-fixes: 241-3, 6h.57m
    easylist: 71063-355, 2d.3h.26m
    easyprivacy: 33178-24, 2d.3h.26m
    urlhaus-1: 3907-1, 6h.56m
filterset (user): [array of 3 redacted]
trustedset: 
  added: [array of 1 redacted]
untrustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  admap: [redacted]
  firstInstall: false
  hidingAds: true
  clickingAds: true
  blockingMalware: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 430 ms (selfie)
  maxAssetCacheWait: 166 ms
popupPanel: 
  blocked: 2
  blockedDetails: 
    youtube.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
You are using Adnauseam, not uBO. Please report to their repo.
