### ISSUE TITLE
multiup.io: redirect to nordvpn

### ISSUE THREAD

**Issue by ave9858** [uBlockOrigin/uAssets#19903]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://multiup.io/en/mirror/7b670e960e2d88a1e586d2235a1395ee/uBlock0_1.52.2.chromium.zip`

### Category

popups

### Description

Sometimes when clicking a link on multiup, I am redirected to a NordVPN ad instead of the file.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/412204b5-8c1b-41cf-8e8c-7ec0bac656b2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 117
filterset (summary):
 network: 104812
 cosmetic: 39693
 scriptlet: 18590
 html: 1053
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35751-48, 1m
  ublock-badware: 7876-0, 1m
  ublock-privacy: 586-0, 1m
  ublock-unbreak: 2170-2, 1m
  ublock-quick-fixes: 234-89, 1m
  easylist: 71185-711, 1m
  easyprivacy: 33183-717, 1m
  urlhaus-1: 11155-0, 1m
  plowe-0: 3721-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2581 ms
 maxAssetCacheWait: 13 ms
popupPanel:
 blocked: 0
 extended:
  ##.text-center.bg-info
  ##.mfp-ready
  ##div.col-md-4:nth-of-type(1):has-text(Usennet)
  ##.panel-featured-success.panel-featured-bottom.panel-featured-t…
  ##div.text-center:has(a[class="btn btn-success"][href^="abp:subs…
  ##+js(replace-node-text, script, /.*createElement.*/, var AG_onL…
  ##+js(abort-current-script, decodeURI, decodeURIComponent)
  ##+js(no-setInterval-if, .submit)
```
</details>

**Comment by mapx-** [comment]
test

    multiup.io##+js(replace-node-text, script, /.*location\.protocol.*/, var AG_onLoad=function(func){if(document.readyState==="complete"||document.readyState==="interactive")func();else if(document.addEventListener)document.addEventListener("DOMContentLoaded"\,func);else if(document.attachEvent)document.attachEvent("DOMContentLoaded"\,func)}; AG_onLoad(function(){var e=document.querySelectorAll(".panel-footer > form[action] > button[link]")\,b=document.querySelectorAll(".panel-footer > form[action]")\,c=new RegExp(/mega\./);if(e.length===b.length)for(var f\,g=0;g<b.length;g++)f=e[g].getAttribute("link")\,b[g].setAttribute("action"\,f)\,b[g].setAttribute("target"\,"_blank")\,b[g].querySelector("input[name=\"link\"]").remove()\,c.test(f)||b[g].setAttribute("method"\,"GET");const h=a=>{a.preventDefault();var b=a?.currentTarget?.getAttribute("link");b?window.open(b):a.currentTarget.removeEventListener("click"\,h)};var i=document.querySelectorAll("button[link^=\"https://drive.google.com/\"]");i.forEach(a=>{a.addEventListener("click"\,h)})}))

**Comment by ave9858** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/01fdc9b1-fe05-4de2-a532-dd4b4b06ed62)

I'm seeing this after adding that filter to "My filters". I also notice multiup takes much longer to load than before, making it hard to test. After the slowdown it seems to work. Removing the filter causes the speed to go back to normal, and the ad returns.

**Comment by mapx-** [comment]
eh, FF is slower, did you test in chrome ?

**Comment by ave9858** [comment]
> eh, FF is slower, did you test in chrome ?

I tested only in firefox, but I've never seen this issue before and it significantly slows down page load.

**Comment by ave9858** [comment]
Thanks, I can see those links now. Only other issue is the popups quickly created by the site and removed during page load by ublock, but I'm not sure if that can be fixed or not.

**Comment by krystian3w** [comment]
We do not need use `AG_onLoad=function(func)` if these fuction do not exist at all.

**Comment by krystian3w** [comment]
Also maybe these can be unlocked #7897, fyi @dhana-exe

**Comment by dimisa-RUAdList** [comment]
infinite loading: https://multiup.io/download/e1237ac9314ec41a8ff2ea613aa383e9/Somerville.part01.rar

**Comment by mapx-** [comment]
maybe

```
multiup.*#@#div.col-md-4:nth-of-type(1):has-text(Usennet)
multiup.*#@#.panel-featured-success.panel-featured-bottom.panel-featured-top.panel.text-center:has([alt="Usennet.nl"]):upward(1)
```

**Comment by mapx-** [comment]
last on chrome for example

however, the link

`https://multiup.io/download-fast/e1237ac9314ec41a8ff2ea613aa383e9/Somerville.part01.rar`

redirects to crap `https://go.bluelinknow.com`

**Comment by mapx-** [comment]
yeah, clicking download leads to 1 download fake usenet item

**Comment by dimisa-RUAdList** [comment]
Google Chrome 117.0.5938.132
Firefox 118.0.1

uBO 1.52.2/1.52.3b2

`https://multiup.io/download-fast/e1237ac9314ec41a8ff2ea613aa383e9/Somerville.part01.rar` ~>
clicking "Download" ~> `https://multiup.io/en/mirror/e1237ac9314ec41a8ff2ea613aa383e9/Somerville.part01.rar` ~>

<details>
<summary>Screenshot(s)</summary>

![Скриншот 2023-10-01 в 13 00 37](https://github.com/uBlockOrigin/uAssets/assets/20126984/02cc595b-6ae4-4c47-bfe6-bc4eb27b4f75)

</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList 

a normal page looks like this 1:
`https://multiup.io/en/mirror/ffb331d29164b4885647553c3634613c/Bald3ursGa3te-Update4.1.1.3686210-elamigos.part1.rar`

yours contains only a fake item (usenet)

**Comment by dimisa-RUAdList** [comment]
@ghajini 
> how does it look when you disable ubo?

`https://multiup.io/en/mirror/e1237ac9314ec41a8ff2ea613aa383e9/Somerville.part01.rar` ~>

<details>
<summary>Screenshot(s)</summary>

![Скриншот 2023-10-01 в 13 32 24](https://github.com/uBlockOrigin/uAssets/assets/20126984/e1624fdc-3830-4665-8390-3940fd50dac7)

</details>

**Comment by dimisa-RUAdList** [comment]
@ghajini 
I get to this page: `https://multiup.io/en/mirror/e1237ac9314ec41a8ff2ea613aa383e9/Somerville.part01.rar`, when I click "Download" here: `https://multiup.io/download/e1237ac9314ec41a8ff2ea613aa383e9/Somerville.part01.rar`

**Comment by mapx-** [comment]
@dimisa-RUAdList you ignored completely the reason, explained twice above

**Comment by dimisa-RUAdList** [comment]
Ok, I didn’t immediately realize that this link doesn’t lead anywhere other than a fake. It seemed to me that there was a way to get the correct link. I reported the review to the person who originally reported the issue, and he confirmed that the other links were fine.

**Comment by ave9858** [comment]
I created a new Firefox profile + new install of uBlock Origin, purged caches and updated, navigated to the URL, disabled firefox tracking protection and was able to reproduce after a few attempts and changing my IP.

**Comment by ave9858** [comment]
With the latest filter updates I'm still sometimes seeing the issue, but its hard to reproduce. With the filters in your comment I haven't seen the issue, but that might be because the issue is not consistently reproducible.

**Comment by ave9858** [comment]
Figured out how to reliable reproduce the error: click the download button icon. The click will be registered to `<i class="fa fa-fw fa-download">` instead of the button, so the script won't intercept. 
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/935fb0eb-881b-47e5-bab3-f877504a78da)

**Comment by ave9858** [comment]
I've uploaded code that should fix the popup when clicking on the icon

**Comment by ave9858** [comment]
Getting two usenet ads, "Download faster and more securely" button on download page (ex `https://multiup.io/27f37c099e359bfc28389b350e213855`) and UseNet.nl option on the mirror list page (ex `https://multiup.io/en/mirror/27f37c099e359bfc28389b350e213855`).
![image](https://github.com/user-attachments/assets/681f46e4-6ea0-4595-976a-3e5693579eb3)

**Comment by rares478** [comment]
Every first click on a download button is opening a popup window to a malware website on both the normal site and the /mirror too. 
Example link: `https://multiup.io/download/8630377c02371fb0ab7096198f87e7fe/output.log`

```adblock-filter-list
uBlock Origin: 1.71.0
Chromium: 149
filterset (summary):
 network: 161706
 cosmetic: 42955
 scriptlet: 36076
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 40-0, never
  ublock-filters: 51390-84, 44m Δ
  ublock-badware: 10367-28, 44m Δ
  ublock-privacy: 4046-3, 44m Δ
  ublock-unbreak: 2768-1, 44m Δ
  ublock-quick-fixes: 440-0, 44m Δ
  easylist: 86986-475, 44m Δ
  easyprivacy: 55815-712, 44m Δ
  urlhaus-1: 26825-11, 44m
  plowe-0: 3505-2, 2m
filterset (user): [array of 40 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1700 ms (selfie)
 maxAssetCacheWait: 323 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  cloudflareinsights.com: 1
 extended:
  ##a[href^="/download-fast/"]
  ##.text-center.bg-info
  ##+js(trusted-replace-node-text, script, setInterval)
  ##+js(prevent-window-open, _blank)
  ##+js(remove-node-text, script, \x)
  ##+js(prevent-setInterval, .submit)
  ##+js(abort-current-script, navigator, FingerprintJS)
  ##+js(multiup)
```

**Comment by ViktorShahter** [comment]
### multiup.io: breakage

URL: `https://multiup.io/en/profile/manage-files`

Description: When on a "Manage files" page I can't drag to select and drag to move files. Folder structure is also visibly broken.

Browser: Firefox 152.0.2

Other extensions: SponsorBlock, Violentmonkey (no userscripts are active there), Bitwarden, Return YouTube Dislikes, SteamDB, Indie Wiki Buddy.
Was tested in temporary FF profile with only uBO, issue still exists.

Screenshots:

<details>

Enabled uBO (dragging selects text, tree view is broken):
<img width="1920" height="920" alt="Image" src="https://github.com/user-attachments/assets/b5089146-015f-4f37-af38-7ef777634fd2" />
Enabled uBO (dragging selects files, tree view is working properly):
<img width="1920" height="922" alt="Image" src="https://github.com/user-attachments/assets/ed89b027-4957-4f65-b51a-710f1d495591" />

</details>

Configuration (from temporary profile with just uBO on default settings):

<details>

```yaml
uBlock Origin: 1.71.0
Firefox: 152
filterset (summary):
 network: 186398
 cosmetic: 43050
 scriptlet: 33411
 html: 3628
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 52421-70, 1m
  ublock-badware: 10390-28, 1m
  ublock-privacy: 4040-2, 1m
  ublock-unbreak: 2831-1, 1m
  ublock-quick-fixes: 459-13, 1m
  easylist: 88977-128, 1m
  easyprivacy: 55856-39, 1m
  urlhaus-1: 49450-11, 1m
  plowe-0: 3509-1025, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2505 ms
 maxAssetCacheWait: 34 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 2
 extended:
  ##+js(trusted-replace-node-text, script, setInterval)
  ##+js(prevent-window-open, _blank)
  ##+js(remove-node-text, script, \x)
  ##+js(prevent-setInterval, .submit)
  ##+js(abort-current-script, navigator, FingerprintJS)
  ##+js(multiup)
  ##+js(set-constant, Document.prototype.createElement.call, noopF…
  ##+js(remove-node-text, script, /"\\|\\[ux]|\+\[\]/)
```
</details>

**Comment by stephenhawk8054** [comment]
@ViktorShahter Can you update the filter lists and test again?

**Comment by ViktorShahter** [comment]
@stephenhawk8054 done on my main profile, nothing changed. Should I create separate FF profile to test with just uBO with default set of filters?

**Comment by SeanCombes** [comment]
Having a similar problem.

<details>

<img width="1080" height="2115" alt="Image" src="https://github.com/user-attachments/assets/afac2a4c-ac9b-4797-a4b5-27e637f0a477" />
<img width="1080" height="2115" alt="Image" src="https://github.com/user-attachments/assets/34bc1967-81f0-43e0-90d8-ed58c89c770d" />

</details>

In image 1 there is supposed to be arrows next to the options that have a drop down menu, but there is no arrows and the drop down menu doesn't appear.
In image 2 the file picker doesn't show any files regardless of what i do. ( no actual link added so not real example but still shows ).
All fixes itself when ubo is disabled.
If I'm missing any necessary details please tell me.
