### ISSUE TITLE
[nsfw] downloadfilm.website: detection

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uAssets#19901]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://downloadfilm.website/film-kurakura21-com/`

### Category

detection

### Description

AdBlock detected when i enter download page

### Other extensions used

Dark reader 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 117
filterset (summary):
 network: 110458
 cosmetic: 138572
 scriptlet: 27726
 html: 1242
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 11149-0, 2m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2262-0, 2m
  adguard-spyware-url: 1231-187, 3m
  adguard-social: 21541-168, 3m
  adguard-cookies: 27719-46, 3m
  ublock-cookies-adguard: 338-0, 3m
  adguard-popup-overlays: 24488-978, 3m
  adguard-mobile-app-banners: 4642-12, 3m
  adguard-other-annoyances: 13603-100, 3m
  adguard-widgets: 2311-1, 3m
  ublock-annoyances: 5495-354, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 36070-674, 3m
  ublock-badware: 7870-0, 3m
  ublock-privacy: 586-46, 3m
  ublock-unbreak: 2175-2, 3m
  ublock-quick-fixes: 234-0, 6m
  adguard-mobile: 8656-107, 3m
  easylist: 71185-817, 3m
  easyprivacy: 33183-728, 3m
  urlhaus-1: 3907-0, 3m
  plowe-0: 3721-1, 2m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2122 ms
 maxAssetCacheWait: 1235 ms
popupPanel:
 blocked: 30
 network:
  35998bf09e.com: 1
  cadrctlnk.com: 2
  gmxvmvptfm.com: 1
  googlesyndication.com: 1
  lby2kd27c.com: 5
  navigablepiercing.com: 2
  terbit2.com: 15
  wpadmngr.com: 1
  wretched-confusion.com: 2
 extended:
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://api.whatsapp.com/send?text="]
  ##a[onclick*="//www.facebook.com/"][onclick*="sharer.php"]
  ##a[onclick*="https://www.facebook.com/sharer/"]
  ##.idmuvi-topbanner
  ##.idmuvi-topbanner-aftermenu
  ##.share-facebook
  ##.share-twitter
  ##.idmuvi-banner-beforecontent
  ##.idmuvi-center-ads
  ##.idmuvi-banner-aftercontent
```
</details>

**Comment by BlazeFTL** [comment]
Add In My Filters
```
||youtube.com^$domain=downloadfilm.website
downloadfilm.website##+js(no-fetch-if, ads)
downloadfilm.website###wpsafe-link:others()
downloadfilm.website###wpsafe-link:style(display: block !important;)
