### ISSUE TITLE
carrot.link: popups

### ISSUE THREAD

**Issue by genepaton** [uBlockOrigin/uAssets#19906]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://carrot.link/gpaton`

### Category

popups

### Description

This site and extension was opening additional windows, going to online retailers, and checking for content in my cart. Even when I tried closing out of the active screen that was showing a list of sites it's checking, it continued this action in the background.

### Other extensions used

Alitools, Windscribe, Extensions Manager 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 97584
 cosmetic: 39694
 scriptlet: 18672
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71189-13, now
  easyprivacy: 33185-63, now
  plowe-0: 3718-1063, now
  ublock-badware: 7874-141, now
  ublock-filters: 34867-141, now
  ublock-privacy: 556-6, now
  ublock-quick-fixes: 236-102, now
  ublock-unbreak: 2124-33, now
  urlhaus-1: 3907-0, now
filterset (user): [empty]
trustedset:
 added: [array of 110 redacted]
switchRuleset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
 collapseBlocked: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1211 ms
 maxAssetCacheWait: 143 ms
popupPanel:
 blocked: 66
 no-popups: true
 network:
  carrot.link: 1
  avantlink.com: 1
  intercom.io: 5
  segment.com: 1
  sentry.io: 43
  split.io: 7
  vercel-insights.com: 8
```
</details>

**Comment by gwarser** [comment]
Isn't this the whole point of this page and add-ons?

**Comment by genepaton** [comment]
Try installing the extension, creating an account and then following through the new set up process. There's some section there about "scanning" for items in your cart. This then starts the process which I describe. A shrunken new browser window opens, goes to the site, retrieves information of anything in your cart and closes itself. Even whilst uBlock is enabled and block new windows or pop-ups.   
  

  

  
  

  

  

        
  
  
>

**Comment by mapx-** [comment]
if that extension opens new windows you should ask them why this behaviour
