### ISSUE TITLE
elsalvadorsurfrealestate.com: nuisance

### ISSUE THREAD

**Issue by planefun2** [uBlockOrigin/uAssets#19919]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://elsalvadorsurfrealestate.com/`

### Category

nuisance

### Description

there's an overlay that appears that I can't seem to pick out or suppress. 

### Other extensions used

Disconnect, Privacy Badger, Proton VPN - happens without them though

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/101938798/f495a3ab-0f40-47ce-9ce0-37d3e217804e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 104729
 cosmetic: 39726
 scriptlet: 18685
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 9-6, never
  easylist: 71296-13, now
  easyprivacy: 33196-63, now
  plowe-0: 3720-1063, now
  ublock-badware: 7884-141, now
  ublock-filters: 34880-141, now
  ublock-privacy: 556-6, now
  ublock-quick-fixes: 241-102, now
  ublock-unbreak: 2125-33, now
  urlhaus-1: 10945-0, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2583 ms (selfie)
 maxAssetCacheWait: 132 ms
popupPanel:
 blocked: 5
 network:
  agentfire.com: 1
  googletagmanager.com: 1
  thesparksite.com: 2
  widgetbe.com: 1
 extended:
  ##.show.animated.fadeIn.middle.modal
```
</details>

**Comment by mapx-** [comment]
- provide exact page / link
- disable ALL other extensions
- disable all your own filters (`user-filters`)
- test again

**Comment by gorhill** [comment]
I get it on this page: `https://elsalvadorsurfrealestate.com/la-ventana-beach-villas/`

<details><summary>Screenshot</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/37a0171b-3e23-4294-9731-da79699fc812)
</details>

These works for me:

    elsalvadorsurfrealestate.com##.show.middle.modal
    elsalvadorsurfrealestate.com##.show.modal-backdrop
    elsalvadorsurfrealestate.com##.aui-modal-open,.modal-open:style(overflow:unset!important)

**Comment by okiehsch** [comment]
The site forces you to register on some of it's listings. The suggestded filters work for me too.
Should we fix it in the main list or in annoyances?

**Comment by ryanbr** [comment]
breaks the buy/sell in the hamburger menu

**Comment by ryanbr** [comment]
maybe a filter block based onevent ?

**Comment by gorhill** [comment]
> breaks the buy/sell in the hamburger menu

Not broken, they also do nothing without the filters or even without uBO enabled. The same buy/sell items in navbar works fine. The ones in hamburger menu do work fine when using mobile version. I don't think the ones in hamburger menu meant to do anything in desktop version.

**Comment by gorhill** [comment]
> breaks the buy/sell in the hamburger menu

I fixed a similar case a few days ago in `annoyances-others`.

**Comment by okiehsch** [comment]
> fixed a similar case a few days ago in annoyances-others.

Let's keep it in the annoyance list to be consistent.
