### ISSUE TITLE
msn ads

### ISSUE THREAD

**Issue by SteveH66** [uBlockOrigin/uAssets#19917]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBO or the filter lists block everything on MSN, EXCEPT advertising

### URL(s) where the issue occurs.

msn.com

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 78
filterset (summary):
 network: 27453
 cosmetic: 11850
 scriptlet: 22187
 html: 1242
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
  plowe-0: null
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 5m
  ublock-annoyances: 5444-10, 5m
 default:
  user-filters: 84-22, never
  ublock-filters: 35770-348, 5m
  ublock-badware: 7886-0, 5m
  ublock-privacy: 586-76, 5m
  ublock-unbreak: 2172-3, 5m
  ublock-quick-fixes: 241-0, 5m
  urlhaus-1: 10945-0, 5m
filterset (user): [array of 84 redacted]
trustedset:
 added: [array of 87 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 7911 redacted]
userSettings:
 advancedUserEnabled: true
 collapseBlocked: false
 ignoreGenericCosmeticFilters: true
hiddenSettings:
 loggerPopupType: normal
supportStats:
 allReadyAfter: 4434 ms
 maxAssetCacheWait: 40 ms
```
</details>

**Comment by mapx-** [comment]
You disabled important lists and modified the default settings.
Reset uBO to defautl settings / lists, don't touch any list / setting.

**Comment by gwarser** [comment]
Firefox 78 is not supported.
