### ISSUE TITLE
csstats.gg: ads

### ISSUE THREAD

**Issue by evandro-gomes** [uBlockOrigin/uAssets#19913]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://csstats.gg/`

### Category

ads

### Description

Every page of this website shows a square containing distracting gif ads.

### Other extensions used

none

### Screenshot(s)

<details>
![Screenshot 2023-09-30 065159](https://github.com/uBlockOrigin/uAssets/assets/56748178/cbbfdc27-3e00-4a39-98b4-d8232475bcc8)
![Screenshot 2023-09-30 071148](https://github.com/uBlockOrigin/uAssets/assets/56748178/601f5270-e222-487a-b04e-8e0c0e7940e6)

<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 113
filterset (summary):
 network: 98984
 cosmetic: 43435
 scriptlet: 18995
 html: 1054
listset (total-discarded, last-updated):
 added:
  spa-1: 5639-11, now
 default:
  user-filters: 20-7, never
  ublock-filters: 35768-264, now
  ublock-badware: 7886-0, now
  ublock-privacy: 586-0, now
  ublock-unbreak: 2172-2, now
  ublock-quick-fixes: 241-0, now
  easylist: 71260-614, now
  easyprivacy: 33195-769, now
  urlhaus-1: 3800-0, now
  plowe-0: 3718-1, now
filterset (user): [array of 20 redacted]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 217 ms (selfie)
 maxAssetCacheWait: 86 ms
popupPanel:
 blocked: 1
 network:
  usercentrics.eu: 1
```
</details>

**Comment by mapx-** [comment]
add

`||csstats.gg/images/banners/$image`

to be reported at [easylist repository](https://github.com/easylist/easylist/issues)

@ryanbr

**Comment by mapx-** [comment]
@evandro-gomes already fixed by easylist, just update that list
