### ISSUE TITLE
webhostingpost.com: detection

### ISSUE THREAD

**Issue by GollumArain** [uBlockOrigin/uAssets#19924]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://webhostingpost.com/greengeeks-july-2022-vps-platform-update/`

### Category

detection

### Description

This is  a redirection site. Until, now they used to send pops of ad blocker detection. But Now, they have got smart.

### Other extensions used

IDM, Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 262340
 cosmetic: 197941
 scriptlet: 45450
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27725-30, now
  adguard-generic: 77844-477, now
  adguard-mobile: 8663-44, now
  adguard-mobile-app-banners: 4644-9, now
  adguard-other-annoyances: 13606-8, now
  adguard-popup-overlays: 24502-72, now
  adguard-spyware: 60537-1358, now
  adguard-spyware-url: 1233-3, now
  block-lan: 54-0, now
  curben-phishing: 83817-6, now
  curben-pup: 189-0, now
  dpollock-0: 11571-253, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 71296-1450, now
  easyprivacy: 33196-16752, now
  plowe-0: 3720-1562, now
  ublock-badware: 7884-371, now
  ublock-filters: 34882-4281, now
  ublock-privacy: 556-138, now
  ublock-quick-fixes: 241-105, 11m
  ublock-unbreak: 2125-149, now
  urlhaus-1: 3869-1, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 56 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3060 ms
 maxAssetCacheWait: 1833 ms
popupPanel:
 blocked: 6
 network:
  achcdn.com: 1
  adapex.io: 1
  aniview.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  nanesbewail.com: 1
 extended:
  ##+js(abort-current-script, document.addEventListener, displayMe…
  ##+js(abort-current-script, document.createElement, delete windo…
  ##+js(no-window-open-if)
  ##+js(nano-setInterval-booster, \,dataType:_, 1000, 0.02)
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ##+js(abort-current-script, $, modal)
```
</details>

**Comment by BlazeFTL** [comment]
```
webhostingpost.com###invisibleCaptchaShortlink[disabled]:remove-attr(disabled)
webhostingpost.com##[id*="ad"], #p, h2.text-center, .row:style(left:-3000px !important;position:absolute !important)
webhostingpost.com##+js(abort-current-script, , nextFunction)
webhostingpost.com#@#+js(nano-setInterval-booster, , dataType:_, 1000, 0.02)
webhostingpost.com##p
webhostingpost.com##+js(nano-sib, , *)

**Comment by mapx-** [comment]
@BlazeFTL provide the requested link

**Comment by BlazeFTL** [comment]
Cant Remember 🤣🙃🙃
I Had This In My Filters

**Comment by BlazeFTL** [comment]
I Think Its From `https://fc-lc.com/82YkvH`

**Comment by okiehsch** [comment]
I get redirected `tophostingapp.com` and see an anti addblock message on that site.
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=tophostingapp.com`

Does `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=webhostingpost.com`
work for you?

**Comment by okiehsch** [comment]
Ok, I will add your filter and change mine.
