### ISSUE TITLE
dizipia.com: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#19921]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dizipia.com/dizi/big-mouth/sezon-5/bolum-1/turkce-dublaj-izle`

### Category

ads

### Description

ads

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedSsafasfasdfcreenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/046c5c5e-ca2a-4a21-9e14-30ba43c11bda)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 112632
 cosmetic: 143594
 scriptlet: 27671
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27725-30, now
  easylist-annoyances: 3985-42, now
  easylist-chat: 139-0, now
  easylist-newsletters: 6508-23, now
  easylist-notifications: 2679-82, now
  fanboy-cookiemonster: 48426-3795, now
  fanboy-social: 16229-12, now
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 5484-80, now
  ublock-cookies-easylist: 303-303, now
 default:
  user-filters: 0-0, never
  TUR-0: 13763-9, now
  easylist: 71296-36, now
  easyprivacy: 33196-158, now
  plowe-0: 3720-1065, now
  ublock-badware: 7884-141, now
  ublock-filters: 34881-170, now
  ublock-privacy: 556-8, now
  ublock-quick-fixes: 241-103, now
  ublock-unbreak: 2125-38, now
  urlhaus-1: 10945-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 293 ms (selfie)
 maxAssetCacheWait: 147 ms
popupPanel:
 blocked: 7
 network:
  ampproject.org: 1
  dizimag.org: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
  refbanners.com: 1
 extended:
  ##ins.adsbygoogle
  ##.social-share
  ##.go-top
  ##.grecaptcha-badge
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
dizipia.com##[data-time]
dizipia.com##.rek-wrap
||dizipia.com/dizip.js
||dizimag.org/uploads/megapari.mp4
||dizipia.com/uploads/*.gif$image
||dizipia.com/uploads/1win1000.jpg
||winaffiliates1.com^
||refpaiozdg.top^
```

@Yuki2718

**Comment by Yuki2718** [comment]
> Last one might fit EL?

Not sure, but `refpaiozdg.top` is a redirector and will fit.
