### ISSUE TITLE
djxmaza.in: detection

### ISSUE THREAD

**Issue by Signup-pawan** [uBlockOrigin/uAssets#19927]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://djxmaza.in/using-a-google-dedicated-server/`

### Category

detection

### Description

Source Links : 

1) `https://thetechnisk.in/ullu-download-page/`

2) `https://devuploads.com/qz8nc7yo2g91`

3) `https://djxmaza.in/cheap-cloud-hosting-providers/`

Issue reported many times and filters updated but still showing same error. 

If I miss something, can someone provide a permanent solution for this site?

Do I need to add any custom fileter code in My filters section?

Please let me know, Thank you!!

### Other extensions used

None

### Screenshot(s)

![Screenshot_20231001_124315_Firefox](https://github.com/uBlockOrigin/uAssets/assets/55138565/85a0f3ca-1073-472b-82cd-f58f68f65883)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 99038
 cosmetic: 30872
 scriptlet: 18665
 html: 1055
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 36082-391, 10m
  ublock-badware: 7880-0, 10m
  ublock-privacy: 586-1, 10m
  ublock-unbreak: 2177-3, 10m
  ublock-quick-fixes: 241-0, 10m
  adguard-mobile: 8663-125, 9m
  easylist: 71296-16696, 9m
  easyprivacy: 33196-721, 9m
  urlhaus-1: 3869-0, 9m
  plowe-0: 3720-1, 9m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 620 ms (selfie)
 maxAssetCacheWait: 107 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##iframe:upward(div)
  ##[id*="iframe"]:style(height:250px !important;left:-3000px !imp…
  ###featuredimage:style(height:250px !important;left:-3000px !imp…
  ##+js(no-fetch-if, /adtrue\.com|eningspon\.com|freychang\.fun|or…
  ##+js(no-xhr-if, /a-mo\.net|adnxs\.com|prebid|creativecdn\.com|e…
```
</details>

**Comment by mapx-** [comment]
working in chrome, not in forefox, however continue here:
https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by BlazeFTL** [comment]
@Signup-pawan Try This 
`@@*$script,xhr,domain=djxmaza.in|miuiflash.com|thecubexguide.com`

**Comment by Signup-pawan** [comment]
> @Signup-pawan Try This `@@*$script,xhr,domain=djxmaza.in|miuiflash.com|thecubexguide.com`

Thanks for the response, do I need to add this my filter section?

**Comment by Signup-pawan** [comment]
> working in chrome, not in firefox, however continue here: #17361

Thanks for the response, please check the configuration details. 

The issue reported for Firefox Android where we have Ublock Origin add-on.

Last time also reported same but no resolution at time also.

**Comment by BlazeFTL** [comment]
> > @Signup-pawan 
> Thanks for the response, do I need to add this my filter section?

Yes

**Comment by Skip75** [comment]
> @Signup-pawan Try This `@@*$script,xhr,domain=djxmaza.in|miuiflash.com|thecubexguide.com`

Still blocked for me even with that filter :(

**Comment by UblockAntiAdblock** [comment]
The problem reappeared again. But I don't know how to report this page why it changes address Randomly

**Comment by UblockAntiAdblock** [comment]
@mapx-
