### ISSUE TITLE
peliculastoday.com [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1992]
URL(s) where the issue occurs

`https://www.peliculastoday.com/zombies/`

Describe the issue

![](https://i.imgur.com/G1YJ6c2.png)

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.15.24

Settings

Default

**Comment by mapx-** [comment]
test these filters (you can click the options and the player will run just fine)

```
peliculastoday.com###pbar_outerdiv
peliculastoday.com##.selected:has-text(Ads)
```

**Comment by KiLL4FuNK** [comment]
It works well
