### ISSUE TITLE
theautopian.com: breakage

### ISSUE THREAD

**Issue by thelazurus** [uBlockOrigin/uAssets#19923]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.theautopian.com/the-autozam-az-1-is-the-very-idea-of-slow-car-fast-in-physical-form/`

### Category

breakage

### Description

Autopian's video player is caught up in the block.

### Other extensions used

Bitwarden, Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 97651
 cosmetic: 39725
 scriptlet: 18686
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71296-13, now
  easyprivacy: 33196-63, now
  plowe-0: 3720-1063, now
  ublock-badware: 7884-141, now
  ublock-filters: 34881-141, now
  ublock-privacy: 556-6, now
  ublock-quick-fixes: 241-102, now
  ublock-unbreak: 2125-33, now
  urlhaus-1: 3869-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 666 ms (selfie)
 maxAssetCacheWait: 311 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
theautopian.com#?#.code-block:-abp-has(.htlad-InContent)
theautopian.com#@#.code-block
theautopian.com#@#.pbs__player
@@||player.ex.co/player/*$script,domain=theautopian.com
@@||cdn.ex.co^$domain=theautopian.com
```

@ryanbr
