### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by V1olette** [uBlockOrigin/uAssets#19934]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/`

### Category

breakage

### Description

Hello.

Recently I have been having this problem with spotify web player. I have seen similar reports but it doesnt match my issue specifically. Lately whenever I enable uBlock, 2 seperate issues occur. The first one is that the audio keeps pausing and it would take several minutes for it to unpause but oddly enough the track is still playing while the audio is paused but the audio cannot be heard. To solve this issue I went to a similar report and made use of this filter `@@||sentry.io/api/$xhr,domain=open.spotify.com` 

It seemed to work for a short while but unfortunately the problem still persisted. I have tried purging cache on the filter lists multiple times and i have cleared cookies and cache on my browser. I also thought I should mention that I switched off easylist under the Ads banner (I hope Im making sense). 

I wanted to leave it unticked in the prerequisites but I wasnt allowed to proceed unless I ticked it. When I turned it off it also seem that everything was working fine until the problem came back once again. When I had easylist on it would still give me the same issue so I thought maybe if I switch it off something might change. I have even updated both of my browsers and still the problem persists. I use Chrome and I use Microsoft Edge. 

Currently I am reporting this issue from Microsoft edge. I even disabled all my other extensions to see if that was the problem. After doing all of that, none of those options worked. The second issue is that the controls on spotify sometimes dont work or dont respond when I click on it. For example I would want to rewind a song and I would have to click the rewind button twice of even thrice just to get the audio to restart or for example while the audio track plays but no audio is heard I will pause the song but when I unpause, the player doesnt respond. I'm really sorry for this long report but I have no idea what to do anymore. I have really tried everything. 

I tried to include a screenshot of what I mean in terms of both issues but it is hard to show it so I apologize if it isnt helpful. I wasnt sure how else to show it but in the screenshot one can see that the audio icon that usually shows when audio is playing on that specific tab isnt shown and the audio is "playing" on its own. Thank you for reading.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot (442)](https://github.com/uBlockOrigin/uAssets/assets/146672348/8d256347-a8f9-46a2-8bdd-3ef17d746999)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 63441
 cosmetic: 10632
 scriptlet: 18692
 html: 0
listset (total-discarded, last-updated):
 removed:
  easylist: null
 default:
  user-filters: 0-0, never
  easyprivacy: 33196-3, 24m
  plowe-0: 3720-689, 24m
  ublock-badware: 7884-0, 24m
  ublock-filters: 34889-44, 24m
  ublock-privacy: 557-2, 23m
  ublock-quick-fixes: 247-90, 23m
  ublock-unbreak: 2127-22, 23m
  urlhaus-1: 11105-0, 23m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1255 ms (selfie)
 maxAssetCacheWait: 404 ms
popupPanel:
 blocked: 8
 network:
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 5
  spotifycdn.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
- do not disable important lists (easylist)
- do your tests in other browsers too (firefox for example - without the tracking protection enabled)

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by V1olette** [comment]
Hii

I will re-enable the important lists. I dont exactly use firefox but i can try it. I have repeatedly cleared cache and cookies on spotify and still the issue persists. May I ask how do i reset uBO?? I am not using a dns or rather I have no clue what a dns is.

I will come back and let you know if the problem is fixed.

**Comment by V1olette** [comment]
So far Spotify works nicely on Firefox. It does pause at the beginning of a song but it quickly plays again. I disabled the tracking prevention as suggested on both browsers. On Microsoft Edge, it also seems to be playing nicely and no pauses, and the controls work as well on both browsers. Thank you so much for your help.
