### ISSUE TITLE
diudemy.com: breakage

### ISSUE THREAD

**Issue by mzl01apq** [uBlockOrigin/uAssets#19931]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.diudemy.com/3-best-times-to-trade-forex`

### Category

breakage

### Description

Page countdown used to be sped up across all websites that use client-side countdowns, but earlier today, I updated the filter lists and uBO stopped speeding up the countdowns. Now, I updated them again and the countdown vanished.
This is a Paid To Click website and the issue is persistent across all articles. The only way of accessing the PTC version of the site is through a crypto faucet and opening an "adlink" shortlink.

### Other extensions used

Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 104
filterset (summary):
 network: 247780
 cosmetic: 124806
 scriptlet: 42240
 html: 1242
listset (total-discarded, last-updated):
 removed:
  LegitimateURLShortener: null
 added:
  adguard-generic: 77844-6857, 35m
  adguard-mobile: 8663-136, 35m
  block-lan: 54-0, 35m
  fanboy-thirdparty_social: 69-1, 35m
  fanboy-cookiemonster: 48428-19754, 35m
  ublock-annoyances: 5444-313, 27m
  adguard-spyware: 60537-16873, 35m
  adguard-cookies: 27725-1618, 35m
  easylist-annoyances: 3985-904, 35m
  easylist-newsletters: 6508-1862, 35m
  ublock-cookies-adguard: 303-0, 35m
  ublock-cookies-easylist: 303-303, 35m
 default:
  user-filters: 36-1, never
  ublock-filters: 35776-365, 35m
  ublock-badware: 7886-0, 35m
  ublock-privacy: 587-1, 35m
  ublock-unbreak: 2172-4, 35m
  ublock-quick-fixes: 247-0, 35m
  easylist: 71299-16754, 35m
  adguard-spyware-url: 1233-80, 35m
  easyprivacy: 33196-732, 35m
  urlhaus-1: 3897-0, 35m
  curben-phishing: 83052-17, 35m
  plowe-0: 3720-1, 35m
filterset (user): [array of 38 redacted]
trustedset:
 added: [array of 60 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 36 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5017 ms (selfie)
 maxAssetCacheWait: 550 ms
popupPanel:
 blocked: 0
 extended:
  ##.banner
  ##body:style(overflow: auto !important;)
  ##+js(nobab)
```
</details>

**Comment by mapx-** [comment]
provide the original link

**Comment by mzl01apq** [comment]
https://www.diudemy.com/secure.php?id=sU93&site=adlink.click
Doesn't deliver the same article to everyone, but regardless the structure of the site is the same across all of them.

**Comment by gorhill** [comment]
You configuration is too heavily customized, including with inadvisable changes. Use default uBO in a new profile and see if the issue is still there, and if so, report troubleshooting information with that default uBO -- we don't/can't investigate cases with such heavily custom settings.

**Comment by mzl01apq** [comment]
I just reset uBO to default settings and the same issue still persists

**Comment by BlazeFTL** [comment]
@mzl01apq Try... Click Both Buttons
```
appsbull.com,diudemy.com,maqal360.com###tristana, #_append, #myDiv, .text-center.start:others()
appsbull.com,diudemy.com,maqal360.com##+js(nano-stb, div_form)
appsbull.com,diudemy.com,maqal360.com###tristana, #_append, #myDiv:style(display: block !important;)
@@*$ghide,domain=appsbull.com|diudemy.com|maqal360.com
appsbull.com,diudemy.com,maqal360.com##+js(no-fetch-if, googlesyndication)
@@||pagead2.googlesyndication.com^$script,domain=appsbull.com|diudemy.com|maqal360.com

**Comment by mzl01apq** [comment]
@BlazeFTL Doesn't work, that "click here" button is an anti-bot link, the actual button replaces it once the countdown ends.

**Comment by BlazeFTL** [comment]
@mzl01apq Is This The End ?..
![Screenshot_20231001-203649_Firefox Nightly_1](https://github.com/uBlockOrigin/uAssets/assets/139938337/f9a5e99b-fb43-407b-a333-7fb0790e1f6b)

**Comment by mzl01apq** [comment]
@BlazeFTL Nope, after 7 pages with countdowns, you are redirected to the last page `https://blog.adlink.click/sU93` which then redirects you to the crypto faucet's shortlinks page.

**Comment by BlazeFTL** [comment]
@mzl01apq Add With My Previous Filters
`@@*$script,domain=appsbull.com|diudemy.com|maqal360.com`

**Comment by BlazeFTL** [comment]
Final
```
appsbull.com,diudemy.com,maqal360.com###tristana, #_append, #myDiv, .text-center.start:others()
appsbull.com,diudemy.com,maqal360.com##+js(nano-stb, div_form)
appsbull.com,diudemy.com,maqal360.com###tristana, #_append, #myDiv:style(display: block !important;)
@@*$ghide,domain=appsbull.com|diudemy.com|maqal360.com
appsbull.com,diudemy.com,maqal360.com##+js(aeld, load, htmls)
appsbull.com,diudemy.com,maqal360.com##+js(rmnt, script, onerror)
appsbull.com,diudemy.com,maqal360.com##+js(aopr, document.write)
@@||cdn.jsdelivr.net^$script,domain=appsbull.com|diudemy.com|maqal360.com
appsbull.com,diudemy.com,maqal360.com##+js(set, private, false)

**Comment by mzl01apq** [comment]
Ok, that does work, but it used to work like that for all websites.
I'm not asking anyone to write me a filter that will work the way it used to. I want someone to show me where I can find the previous versions of the filter lists, so that I can bring back the filter that universally skipped the countdowns.

**Comment by BlazeFTL** [comment]
@mzl01apq What Website?
Maybe They Use More Domains ?
