### ISSUE TITLE
jp.reuters.com: detection

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#19939]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://jp.reuters.com/markets/japan/funds/6XXZOL4MPVP5XBXHVGNX22PAEI-2023-10-02/`

### Category

detection

### Description

Anti-Adblock appears.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![タイトルなし](https://github.com/uBlockOrigin/uAssets/assets/86018494/8f5d0a27-1ebc-48c7-8d5e-1a965f12ebdc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 106856
 cosmetic: 52492
 scriptlet: 22609
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5488-8, never
 default:
  user-filters: 3-0, never
  JPN-1: 13445-4, 2m
  easylist: 71318-29, 2m
  easyprivacy: 33196-90, 2m
  plowe-0: 3720-1068, 2m
  ublock-badware: 7645-148, 2m
  ublock-filters: 34891-150, 2m
  ublock-privacy: 557-6, 2m
  ublock-quick-fixes: 247-102, 2m
  ublock-unbreak: 2127-35, 2m
  urlhaus-1: 11110-5, 2m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1073 ms
 maxAssetCacheWait: 269 ms
popupPanel:
 blocked: 41
 network:
  abtasty.com: 3
  adsafeprotected.com: 2
  advertising.com: 1
  chartbeat.com: 2
  datadoghq-browser-agent.com: 1
  en25.com: 1
  go-mpulse.net: 2
  google-analytics.com: 1
  googlesyndication.com: 1
  logly.co.jp: 1
  merequartz.com: 2
  permutive.com: 1
  pub.network: 1
  qualtrics.com: 1
  scorecardresearch.com: 1
  segment.com: 1
  segment.io: 16
  sophi.io: 1
  tru.am: 1
  wsod.com: 1
 extended:
  ##[data-testid="ResponsiveAdSlot"]
  ##div[class^="ad-slot__"]
  ##div[class^="regular-article-layout__inner_"]:has(> div[data-te…
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by stephenhawk8054** [comment]
Please wait about 10 minutes, then force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.

**Comment by stm-x** [comment]
Looks like it's fixed.
Thank you!
