### ISSUE TITLE
limcasports.xyz: detection

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#19936]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://limcasports.xyz`

### Category

detection

### Description

website detected ublock and pop ups "Ads Blocker Detected!!!" window.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ads Blocker](https://github.com/uBlockOrigin/uAssets/assets/51531027/905d18ce-4ee7-4d3b-a8a1-349ea5efd998)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 170409
 cosmetic: 181241
 scriptlet: 31401
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, 15m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1651-0, 15m
  https://easylist.to/easylist/fanboy-annoyance.txt: 61361-111, 15m
  https://fanboy.co.nz/fanboy-turkish.txt: 725-0, 15m
  https://filters.adavoid.org/ultimate-privacy-filter.txt: 60361-467, 15m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72788-5360, 15m
  https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts: 3242-43, 15m
  https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/Soft98/Soft98NoAds.txt: 18-0, 15m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7256-0, 15m
  https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt: 412-8, 15m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93598-77570, 15m
  fanboy-cookiemonster: 48428-48428, 15m
  [4 lists not shown]: [too many]
 default:
  user-filters: 788-11, never
  TUR-0: 13763-105, 15m
  easylist: 71318-262, 15m
  easyprivacy: 33196-16781, 15m
  plowe-0: 3720-1178, 15m
  ublock-badware: 7640-142, 15m
  ublock-filters: 34889-585, 15m
  ublock-privacy: 557-65, 15m
  ublock-unbreak: 2127-81, 15m
  urlhaus-1: 11105-0, 15m
filterset (user): [array of 778 redacted]
trustedset:
 added: [array of 18 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 7 redacted]
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1031 ms
 maxAssetCacheWait: 577 ms
popupPanel:
 blocked: 32
 network:
  amung.us: 14
  awistats.com: 1
  cusecwhitten.com: 1
  googlesyndication.com: 4
  googletagmanager.com: 1
  greeter.me: 3
  histats.com: 1
  korarea.com: 1
  superfastcdn.com: 2
  swarm.video: 3
  udmserve.net: 1
 extended:
  ##a[id][href="https://chpadblock.com/"][rel^="noopener noreferre…
  ##.aplvideo
  ##ins.adsbygoogle
  ##.go-to-top
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
  ##[style="position:absolute;top:0;left:0;width: 100%;height: 100…
  ###html1
  ##+js(abort-current-script, setTimeout, admc)
```
</details>

**Comment by D4niloMR** [comment]
Add this to your filters:

`limcasports.xyz##+js(noeval-if, /chp_?ad/)`
