### ISSUE TITLE
[nsfw] homemoviestube.com: [unknown]

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#19938]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.homemoviestube.com/videos/454562/husband-helping-and-watching-his-busty-wife-fuck-bbc.html`

### Category

[unknown]

### Description

Les vidéos ne s'affichent pas

### Other extensions used

Aucune qui interfère avec uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 145536
 cosmetic: 113876
 scriptlet: 23001
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1651-0, 1h.49m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2275-10, 1h.48m
  RUS-0: 39938-169, 1m
  fanboy-cookiemonster: 48428-230, 1m
 default:
  FRA-0: 28404-38, 1m
  easylist: 71318-98, 1m
  easyprivacy: 33196-635, 1m
  plowe-0: 3720-1079, 1m
  ublock-badware: 7640-152, 1m
  ublock-filters: 34889-260, 1m
  ublock-privacy: 557-54, 1m
  ublock-quick-fixes: 247-102, 1m
  ublock-unbreak: 2127-38, 1m
  urlhaus-1: 11105-0, 1h.47m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 148 ms (selfie)
 maxAssetCacheWait: 87 ms
popupPanel:
 blocked: 13
 network:
  addthis.com: 1
  aws-itcloud.net: 1
  bulrev.com: 1
  cdngain.com: 1
  dynssp.com: 1
  fvcwqkkqmuv.com: 1
  googletagmanager.com: 1
  gorillatraffic.xyz: 2
  realsrv.com: 3
  songtopbrand.com: 1
 extended:
  ##.ad-block
  ##.addthis_toolbox
  ##.adsbyexoclick
  ##[href^="https://aoflix.com/Home"]
  ##.film-aside-ads
  ##+js(abort-on-property-read, decodeURI)
  ##+js(abort-current-script, document.createElement, /l\.parentNo…
  ##+js(abort-current-script, WebAssembly, _0x)
```
</details>

**Comment by gorhill** [comment]
I can't reproduce with the same set of lists.

Only difference I see is that there are no `aws-itcloud.net` reported on my side.

**Comment by mapx-** [comment]
site issue

certificate issue
GET https://eu.videos.cdn.homemoviestube.com/5/7/2/9/0/572900b5105c2Beautiful%20Haley%20amateur%20blowjob.mp4 net::ERR_CERT_COMMON_NAME_INVALID

[FP_ERROR] Playback error DOMException: The element has no supported sources.
