### ISSUE TITLE
imdb.com: ads

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#19944]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.imdb.com/title/tt0167260/mediaviewer/rm1135116288/`

### Category

ads

### Description

Every four images viewed, the fourth is an ad, which appears as black with the text "Publicidad" (Advertisement).

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 100009
 cosmetic: 45950
 scriptlet: 19094
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 71318-13, now
  easyprivacy: 33196-63, now
  plowe-0: 3720-1063, now
  spa-0: 3722-19, now
  spa-1: 5642-225, now
  ublock-badware: 7645-138, now
  ublock-filters: 34906-172, now
  ublock-privacy: 557-6, now
  ublock-quick-fixes: 247-101, now
  ublock-unbreak: 2127-35, now
  urlhaus-1: 3954-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2196 ms
 maxAssetCacheWait: 415 ms
popupPanel:
 blocked: 39
 network:
  imdb.com: 3
  amazon-adsystem.com: 3
  amazon.com: 30
  media-imdb.com: 1
  scorecardresearch.com: 1
  ssl-images-amazon.com: 1
 extended:
  ##.cornerstone_slot
  ##.slot_wrapper
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||imdb.com/_json/getads/
```

@ryanbr
