### ISSUE TITLE
play.draftstars.com.au: breakage

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#19957]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I lick on Live Chat, nothing happens with uBlock enabled.
With uBlock disabled, the chat initiation page opens where you enter your details to go to the next step.

### URL(s) where the issue occurs.

`https://play.draftstars.com.au/betting/`

### Screenshot(s)

Live chat not working:
https://github.com/uBlockOrigin/uAssets/assets/20948631/311c1155-9fbd-48ae-9477-6af07a8f3022

Live chat working:
https://github.com/uBlockOrigin/uAssets/assets/20948631/8c1af370-7f16-4f9e-910d-df20d3ae3569

### uBO version

1.52.2

### Browser name and version

Chrome

### Settings

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 259461
 cosmetic: 226963
 scriptlet: 44844
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72897-107, 5h.12m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 31283-0, 5h.12m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 5h.12m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93667-21598, 5h.11m
  adguard-cookies: 27792-27792, 5h.12m
  adguard-generic: 78013-520, 5h.12m
  adguard-mobile-app-banners: 4657-4657, 5h.12m
  adguard-other-annoyances: 13617-13617, 5h.12m
  adguard-popup-overlays: 24519-24519, 5h.12m
  adguard-social: 21586-1608, 5h.12m
  adguard-widgets: 2312-2312, 5h.12m
  block-lan: 54-0, 5h.12m
  [12 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  easylist: 71398-1393, 5h.12m
  easyprivacy: 33205-463, 5h.12m
  plowe-0: 3720-1446, 5h.11m
  ublock-badware: 7123-329, 5h.11m
  ublock-filters: 34861-4221, 5h.11m
  ublock-privacy: 557-8, 5h.11m
  ublock-quick-fixes: 179-49, 5h.11m
  ublock-unbreak: 2129-98, 5h.11m
  urlhaus-1: 11365-3924, 5h.11m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 551 ms (selfie)
 maxAssetCacheWait: 430 ms
```

**Comment by mapx-** [comment]
disable 
`https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt`
and test again

**Comment by TesterMan247** [comment]
> disable `https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt` and test again

Yes, you're right.
This fixed the issue.

However, I don't want to disable the whole filter list.

Couldn't you just fix the issue with the exact filter causing issue?

**Comment by mapx-** [comment]
- an account is required

- re-enable that list
- open uBO logger
- repeat the steps to get the issue
- go back in uBO logger
- copy & paste here ALL the blocked items

**Comment by TesterMan247** [comment]
+27			play.draftstars.com.au	3	post	ping	https://analytics.google.com/g/collect?v=2&tid=G-J1W7HPG982&gtm=45je3a20&_p=1184849788&ul=en-gb&sr=1440x900&cid=439315590.1695428951&uaa=x86&uab=64&uafvl=Google%2520Chrome%3B117.0.5938.132%7CNot%253BA%253DBrand%3B8.0.0.0%7CChromium%3B117.0.5938.132&uamb=0&uam=&uap=Windows&uapv=14.0.0&uaw=0&are=1&_eu=ABAI&_s=1&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&dr=https%3A%2F%2Fwww.protopage.com%2F&dt=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&sid=1696417349&sct=5&seg=1&en=page_view&_ee=1
+26			play.draftstars.com.au	3	post	ping	https://analytics.google.com/g/collect?v=2&tid=G-3JYX9968QV&gtm=45je3a20&_p=1184849788&ul=en-gb&sr=1440x900&cid=439315590.1695428951&uaa=x86&uab=64&uafvl=Google%2520Chrome%3B117.0.5938.132%7CNot%253BA%253DBrand%3B8.0.0.0%7CChromium%3B117.0.5938.132&uamb=0&uam=&uap=Windows&uapv=14.0.0&uaw=0&are=1&_eu=ABAI&_s=1&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&dr=https%3A%2F%2Fwww.protopage.com%2F&dt=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&sid=1696417349&sct=4&seg=1&en=page_view&_ee=1&ep.ua_dimension_1=439315590.1695428951&ep.ua_dimension_2=20231004%7C00882615&ep.ua_dimension_3=2023-10-04T22%3A32%3A09.400%2B11%3A00
+26			play.draftstars.com.au	3	post	ping	https://www.google-analytics.com/g/collect?v=2&tid=G-Q20GWQTG5F&gtm=45je3a20&_p=1184849788&cid=439315590.1695428951&ul=en-gb&sr=1440x900&uaa=x86&uab=64&uafvl=Google%2520Chrome%3B117.0.5938.132%7CNot%253BA%253DBrand%3B8.0.0.0%7CChromium%3B117.0.5938.132&uamb=0&uam=&uap=Windows&uapv=14.0.0&uaw=0&are=1&sid=1696417348&sct=5&seg=1&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&dr=https%3A%2F%2Fwww.protopage.com%2F&dt=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&_s=1
+26			play.draftstars.com.au	3	post	ping	https://www.google-analytics.com/g/collect?v=2&tid=G-ZLYKDLY7PG&gtm=45je3a20&_p=1184849788&cid=439315590.1695428951&ul=en-gb&sr=1440x900&uaa=x86&uab=64&uafvl=Google%2520Chrome%3B117.0.5938.132%7CNot%253BA%253DBrand%3B8.0.0.0%7CChromium%3B117.0.5938.132&uamb=0&uam=&uap=Windows&uapv=14.0.0&uaw=0&are=1&_s=1&sid=1696417348&sct=5&seg=1&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&dr=https%3A%2F%2Fwww.protopage.com%2F&dt=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&en=page_view&ep.ga_client_id=439315590.1695428951&ep.ga_session_id=1696419129324.nxnl7fwm&ep.hit_timestamp=2023-10-04T22%3A32%3A09.324%2B11%3A00&up.ga_client_id=439315590.1695428951
+24			play.draftstars.com.au	3	get	script	https://d.la2-c2-hnd.salesforceliveagent.com/chat/rest/Visitor/Settings.jsonp?Settings.prefix=Visitor&Settings.buttonIds=[5735j000000kLah]&Settings.updateBreadcrumb=1&callback=embedded_svc.liveAgentAPI.connection.handlePing&deployment_id=5725j000000kKxx&org_id=00D5j000008blp2&version=48
+24			play.draftstars.com.au	3	get	script	https://d.la2-c2-hnd.salesforceliveagent.com/chat/rest/EmbeddedService/EmbeddedServiceConfig.jsonp?Settings.prefix=EmbeddedService&org_id=00D5j000008blp2&EmbeddedServiceConfig.configName=playup&callback=embedded_svc.liveAgentAPI.handleChatSettings&version=48&EmbeddedServiceConfig.language=en-AU
+24			play.draftstars.com.au	3	get	script	https://service.force.com/embeddedservice/5.0/utils/inert.min.js
+24			play.draftstars.com.au	3	get	script	https://d.la2-c2-ukb.salesforceliveagent.com/chat/rest/Visitor/Settings.jsonp?Settings.prefix=Visitor&Settings.buttonIds=[5735j000000kLah]&Settings.updateBreadcrumb=1&callback=embedded_svc.liveAgentAPI.connection.handlePing&deployment_id=5725j000000kKxx&org_id=00D5j000008blp2&version=48
+24			service.force.com	3,1	get	script	https://service.force.com/embeddedservice/5.0/frame/filetransfer.esw.min.js
+24			play.draftstars.com.au	3	get	script	https://service.force.com/embeddedservice/5.0/client/invite.esw.min.js
+24			play.draftstars.com.au	3	get	script	https://d.la2-c2-ukb.salesforceliveagent.com/chat/rest/EmbeddedService/EmbeddedServiceConfig.jsonp?Settings.prefix=EmbeddedService&org_id=00D5j000008blp2&EmbeddedServiceConfig.configName=playup&callback=embedded_svc.liveAgentAPI.handleChatSettings&version=48&EmbeddedServiceConfig.language=en-AU
+24			play.draftstars.com.au	1	get	image	https://play.draftstars.com.au/favicon.png
+24			service.force.com	3,1	get	script	https://service.force.com/embeddedservice/5.0/frame/chasitor.esw.min.js
+23			service.force.com	3,1	get	script	https://service.force.com/embeddedservice/5.0/frame/broadcast.esw.min.js
+23			service.force.com	3,1	get	script	https://service.force.com/embeddedservice/5.0/frame/session.esw.min.js
+23			service.force.com	3,1	get	script	https://service.force.com/embeddedservice/5.0/eswFrame.min.js
+22			play.draftstars.com.au	3	get	frame	https://service.force.com/embeddedservice/5.0/esw.html?parent=https://play.draftstars.com.au/betting/
+22			play.draftstars.com.au	3	get	script	https://service.force.com/embeddedservice/5.0/client/liveagent.esw.min.js
+22			play.draftstars.com.au	3	get	css	https://service.force.com/embeddedservice/5.0/esw.min.css
+22			play.draftstars.com.au	3	get	image	https://sp.analytics.yahoo.com/sp.pl?a=10000&d=Wed%2C%2004%20Oct%202023%2011%3A32%3A10%20GMT&n=-11d&b=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&.yp=10180779&f=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&e=https%3A%2F%2Fwww.protopage.com%2F&enc=UTF-8&yv=1.15.1&tagmgr=gtm
+21			www.google.com	3,3	get	script	https://www.gstatic.com/recaptcha/releases/pxZcVU8Dk73FyvFvdCgp2MSG/recaptcha__en.js
+21			play.draftstars.com.au	3	get	image	https://pixel.quantserve.com/pixel;r=50831854;source=gtm;event=refresh;labels=_fp.event.Default;rf=0;a=p-NPfW3RWCKsRFm;url=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F;ref=https%3A%2F%2Fwww.protopage.com%2F;uht=2;fpan=0;fpa=P0-1284446454-1695428950723;pbc=;ns=0;ce=1;qjs=1;qv=44310d19-20230908150619;cm=;gdpr=0;d=draftstars.com.au;dst=1;et=1696419130371;tzo=-660;ogl=;ses=a14712cf-3ab7-42c7-8337-1f1cabb400a2;mdl=
+21			play.draftstars.com.au	1	get	other	https://play.draftstars.com.au/manifest.json
+21			play.draftstars.com.au	3	get	script	https://service.force.com/embeddedservice/5.0/utils/common.min.js
+21			play.draftstars.com.au	1	options	xhr	https://api2.draftstars.com.au/v1.1/friendrequests
+21			play.draftstars.com.au	1	get	xhr	https://api2.draftstars.com.au/v1.1/friendrequests
+21			www.google.com	3,1	get	script	https://www.google.com/recaptcha/enterprise/webworker.js?hl=en&v=pxZcVU8Dk73FyvFvdCgp2MSG
+21			play.draftstars.com.au	3	get	xhr	https://s.yimg.com/wi/config/10180779.json
+21			play.draftstars.com.au	3	get	script	https://rules.quantcount.com/rules-p-NPfW3RWCKsRFm.js
+21			www.google.com	3,3	get	font	https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc4.woff2
+21			www.google.com	3,3	get	font	https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2
+21			www.google.com	3,3	get	image	https://www.gstatic.com/recaptcha/api2/logo_48.png
+21			play.draftstars.com.au	1	options	xhr	https://api2.draftstars.com.au/v1.1/banners
+21			play.draftstars.com.au	1	get	xhr	https://api2.draftstars.com.au/v1.1/banners
+21			www.google.com	3,3	get	script	https://www.gstatic.com/recaptcha/releases/pxZcVU8Dk73FyvFvdCgp2MSG/recaptcha__en.js
+21			www.google.com	3,3	get	css	https://www.gstatic.com/recaptcha/releases/pxZcVU8Dk73FyvFvdCgp2MSG/styles__ltr.css
+21			play.draftstars.com.au	1	options	xhr	https://api2.draftstars.com.au/v1.1/users/current?embed=payments,limit
+21			play.draftstars.com.au	1	get	xhr	https://api2.draftstars.com.au/v1.1/users/current?embed=payments,limit
+21			play.draftstars.com.au	3	options	xhr	https://sessions.bugsnag.com/
+21			play.draftstars.com.au	3	post	xhr	https://sessions.bugsnag.com/
+20			play.draftstars.com.au	3	get	image	https://www.facebook.com/tr/?id=1976129659350734&ev=PageView&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&rl=https%3A%2F%2Fwww.protopage.com%2F&if=false&ts=1696419129583&sw=1440&sh=900&v=2.9.132&r=stable&ec=0&o=30&fbp=fb.2.1695428950715.1241355517&ler=other&it=1696419129469&coo=false&exp=a0&rqm=GET
+20			play.draftstars.com.au	3	get	script	https://www.googletagmanager.com/gtag/js?id=G-J1W7HPG982&cx=c&_slc=1
+20			play.draftstars.com.au	3	get	script	https://www.googletagmanager.com/gtag/js?id=G-3JYX9968QV&cx=c&_slc=1
+20			play.draftstars.com.au	3	get	frame	https://www.google.com/recaptcha/enterprise/anchor?ar=1&k=6LewAkMlAAAAABSEZoxndQNEl-TANryXE39xpCSx&co=aHR0cHM6Ly9wbGF5LmRyYWZ0c3RhcnMuY29tLmF1OjQ0Mw..&hl=en&v=pxZcVU8Dk73FyvFvdCgp2MSG&size=invisible&cb=cp4rwc2pbugz
+20			play.draftstars.com.au	3	get	image	https://playup-wagering-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/559.png
+20			play.draftstars.com.au	3	get	image	https://playup-wagering-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/1233.png
+20			play.draftstars.com.au	3	get	image	https://playup-wagering-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/424.png
+20			play.draftstars.com.au	3	get	image	https://playup-wagering-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/1436.png
+20			play.draftstars.com.au	3	get	image	https://playup-wagering-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/1400.png
+20			play.draftstars.com.au	3	get	image	https://playup-wagering-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/496.png
+20			play.draftstars.com.au	3	get	script	https://connect.facebook.net/signals/config/1976129659350734?v=2.9.132&r=stable&domain=play.draftstars.com.au
+20			play.draftstars.com.au	3	get	script	https://script.hotjar.com/modules.b16e4d57f3928457df7a.js
+20			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/broadcasting/auth
+20			play.draftstars.com.au	3	post	xhr	https://wagering-api.playup.io/v1/broadcasting/auth
+20			play.draftstars.com.au	3	post	xhr	https://www.google-analytics.com/j/collect?v=1&_v=j101&a=1184849788&t=pageview&_s=1&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&dr=https%3A%2F%2Fwww.protopage.com%2F&ul=en-gb&de=UTF-8&dt=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&sd=24-bit&sr=1440x900&vp=1423x783&je=0&_u=QACAAEABAAAAACAEK~&jid=&gjid=&cid=439315590.1695428951&tid=UA-62572006-20&_gid=1853644179.1696391686&_slc=1&gtm=45He3a20n81K7NPNX5&z=1802729350
+20			play.draftstars.com.au	3	post	xhr	https://www.google-analytics.com/j/collect?v=1&_v=j101&a=1184849788&t=pageview&_s=1&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&dr=https%3A%2F%2Fwww.protopage.com%2F&ul=en-gb&de=UTF-8&dt=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&sd=24-bit&sr=1440x900&vp=1423x783&je=0&_u=QACAAEABAAAAACAEK~&jid=&gjid=&cid=439315590.1695428951&tid=UA-62572006-22&_gid=1853644179.1696391686&_slc=1&gtm=45He3a20n81K7NPNX5&cd1=439315590.1695428951&cd2=20231004%7C00882615&cd3=2023-10-04T22%3A32%3A09.400%2B11%3A00&z=1505281085
+20			play.draftstars.com.au	3	get	script	https://www.googletagmanager.com/gtag/js?id=G-ZLYKDLY7PG&l=dataLayer&cx=c
+20			play.draftstars.com.au	3	get	script	https://www.googletagmanager.com/gtag/js?id=G-Q20GWQTG5F&l=dataLayer&cx=c
+20			play.draftstars.com.au	3	get	script	https://s.yimg.com/wi/ytc.js
+20			play.draftstars.com.au	3	get	script	https://static.hotjar.com/c/hotjar-2913488.js?sv=7
+20			play.draftstars.com.au	3	get	script	https://secure.quantserve.com/quant.js
+20			play.draftstars.com.au	3	get	script	https://www.google-analytics.com/analytics.js
+20			play.draftstars.com.au	3	get	script	https://connect.facebook.net/en_US/fbevents.js
+20			play.draftstars.com.au	3	get	script	https://www.gstatic.com/recaptcha/releases/pxZcVU8Dk73FyvFvdCgp2MSG/recaptcha__en.js
+20			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlowcondensed/v12/HTx3L3I-JCGChYJ8VI-L6OO_au7B6xHT2g.woff2
+20			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlowcondensed/v12/HTxwL3I-JCGChYJ8VI-L6OO_au7B46r2z3bWuQ.woff2
+20			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/19.svg
+20			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/18.svg
+20			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/7.png
+20			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/6.png
+20			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/5.png
+20			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/4.png
+20			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/2.png
+20			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/links/desktop/1.png
+20			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/user/?include=boosts,bonuses
+20			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/user/?include=boosts,bonuses
+20			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/link_groups/?include=links
+20			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/link_groups/?include=links
+20			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/sports/?include=competitions
+20			play.draftstars.com.au	3	get	websocket	wss://ws1-production.playup.io/app/n3jso7y2rn8t32pnn94s?protocol=7&client=js&version=7.0.6&flash=false
+20			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/sport_events/?include=primary_market_group.markets.selections,participants,primary_market_group.markets.excluded_market_types&filter[start_time][from]=2023-10-04T20%3A32%3A09%2B11%3A00&filter[start_time][to]=2023-10-05T04%3A32%3A09%2B11%3A00&page[size]=100
+20			play.draftstars.com.au	3	get	script	https://playup.my.salesforce.com/embeddedservice/5.0/esw.min.js
+20			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/meetings/?include=races&filter%5Bstart_date%5D%5Bfrom%5D=2023-10-04&filter%5Bstart_date%5D%5Bto%5D=2024-10-04&filter%5Bis_future%5D=1&page%5Bsize%5D=100&page%5Bnumber%5D=1
+20			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/sports/?include=competitions
+20			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/meetings/?include=races&filter%5Bstart_date%5D%5Bfrom%5D=2023-10-04&filter%5Bstart_date%5D%5Bto%5D=2023-10-04&filter%5Bis_future%5D=0&page%5Bsize%5D=100&page%5Bnumber%5D=1
+20			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/sport_events/?include=primary_market_group.markets.selections,participants,primary_market_group.markets.excluded_market_types&filter[start_time][from]=2023-10-04T20%3A32%3A09%2B11%3A00&filter[start_time][to]=2023-10-05T04%3A32%3A09%2B11%3A00&page[size]=100
+20			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/meetings/?include=races&filter%5Bstart_date%5D%5Bfrom%5D=2023-10-04&filter%5Bstart_date%5D%5Bto%5D=2024-10-04&filter%5Bis_future%5D=1&page%5Bsize%5D=100&page%5Bnumber%5D=1
+20			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/meetings/?include=races&filter%5Bstart_date%5D%5Bfrom%5D=2023-10-04&filter%5Bstart_date%5D%5Bto%5D=2023-10-04&filter%5Bis_future%5D=0&page%5Bsize%5D=100&page%5Bnumber%5D=1
+20			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlowcondensed/v12/HTxxL3I-JCGChYJ8VI-L6OO_au7B6xTj2FHz.woff2
+20			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlowcondensed/v12/HTxyL3I-JCGChYJ8VI-L6OO_au7B6xTrY3Tmu4kG.woff2
+20			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlow/v12/7cHsv4kjgoGqM7E_CfOc5mouvTo.woff2
+20			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E3q-0s51os.woff2
+20			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlow/v12/7cHrv4kjgoGqM7E_Cfs7wH8.woff2
+20			play.draftstars.com.au	3	get	font	https://wagering.playup.com.au/static/media/playup-icons.24d10e96.ttf
+20			play.draftstars.com.au	3	options	xhr	https://portal-api.playup.io/broadcasting/auth
+20			play.draftstars.com.au	3	post	xhr	https://portal-api.playup.io/broadcasting/auth
+19			play.draftstars.com.au	3	options	xhr	https://portal-api.playup.io/users/current?embed=user_bank_account,limits,bpay_details,payid_details,user_cards
+19			play.draftstars.com.au	3	options	xhr	https://portal-api.playup.io/link_groups
+19			play.draftstars.com.au	3	get	websocket	wss://ws1-production.playup.io/app/8jtbh2hiubv8ha798hky?protocol=7&client=js&version=7.0.6&flash=false
+19			play.draftstars.com.au	3	get	xhr	https://portal-api.playup.io/users/current?embed=user_bank_account,limits,bpay_details,payid_details,user_cards
+19			play.draftstars.com.au	3	get	script	https://www.google.com/recaptcha/enterprise.js?render=6LewAkMlAAAAABSEZoxndQNEl-TANryXE39xpCSx
+19			play.draftstars.com.au	3	get	xhr	https://portal-api.playup.io/link_groups
+19			play.draftstars.com.au	1	get	script	https://app.draftstars.com.au/main.bundle.js?t=1696419128635
+19			play.draftstars.com.au	1	get	css	https://app.draftstars.com.au/css/site.css?t=1696419128635
+19			play.draftstars.com.au	3	get	script	https://wagering.playup.com.au/static/js/bundle.js?t=1696419128635
+19			play.draftstars.com.au	3	get	css	https://wagering.playup.com.au/static/css/bundle.css?t=1696419128635
+19			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E30-8s51os.woff2
+19			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlow/v12/7cHpv4kjgoGqM7E_DMs5.woff2
+19			play.draftstars.com.au	3	get	font	https://fonts.gstatic.com/s/barlow/v12/7cHqv4kjgoGqM7E3t-4s51os.woff2
+19			play.draftstars.com.au	3	get	image	https://playup-portal-prod.s3.ap-southeast-2.amazonaws.com/avatars/small/fcW2IXwXJsQtLxiH_1626425144.jpg
+19			play.draftstars.com.au	3	options	xhr	https://sessions.bugsnag.com/
+19			play.draftstars.com.au	3	post	xhr	https://sessions.bugsnag.com/
+19			play.draftstars.com.au	3	get	script	https://www.googletagmanager.com/gtm.js?id=GTM-K7NPNX5&gtm_auth=&gtm_preview=&gtm_cookies_win=x
+19			play.draftstars.com.au	3	get	css	https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,400;0,700;1,400;1,700&family=Barlow:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,300;1,400;1,600;1,700;1,800;1,900&display=swap
+19			play.draftstars.com.au	1	get	script	https://play.draftstars.com.au/static/js/main.eb50b8a8.chunk.js
+19			play.draftstars.com.au	1	get	script	https://play.draftstars.com.au/static/js/2.a90c9231.chunk.js
+19			play.draftstars.com.au	1	get	css	https://play.draftstars.com.au/static/css/main.0f15d214.chunk.css
+19			play.draftstars.com.au	1	get	css	https://play.draftstars.com.au/static/css/2.bea2fa31.chunk.css
+19	whitelisted	++	play.draftstars.com.au	1	get	doc	https://play.draftstars.com.au/betting/
+19	https://play.draftstars.com.au/betting/
+19			play.draftstars.com.au	3	get	css	https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,400;0,700;1,400;1,700&family=Barlow:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,300;1,400;1,600;1,700;1,800;1,900&display=swap
+19			play.draftstars.com.au	1	get	script	https://play.draftstars.com.au/static/js/main.eb50b8a8.chunk.js
+19			play.draftstars.com.au	1	get	script	https://play.draftstars.com.au/static/js/2.a90c9231.chunk.js
+19			play.draftstars.com.au	1	get	css	https://play.draftstars.com.au/static/css/main.0f15d214.chunk.css
+19			play.draftstars.com.au	1	get	css	https://play.draftstars.com.au/static/css/2.bea2fa31.chunk.css
+19			play.draftstars.com.au	3	post	ping	https://www.google-analytics.com/g/collect?v=2&tid=G-ZLYKDLY7PG&gtm=45je3a20&_p=1797054443&cid=439315590.1695428951&ul=en-gb&sr=1440x900&uaa=x86&uab=64&uafvl=Google%2520Chrome%3B117.0.5938.132%7CNot%253BA%253DBrand%3B8.0.0.0%7CChromium%3B117.0.5938.132&uamb=0&uam=&uap=Windows&uapv=14.0.0&uaw=0&are=1&_s=2&sid=1696417348&sct=5&seg=1&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&dr=https%3A%2F%2Fwww.protopage.com%2F&dt=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&en=user_engagement&ep.ga_client_id=439315590.1695428951&ep.ga_session_id=1696419079098.kjql19wg&ep.hit_timestamp=2023-10-04T22%3A31%3A19.98%2B11%3A00&_et=9955
+19			play.draftstars.com.au	3	post	ping	https://www.google-analytics.com/g/collect?v=2&tid=G-Q20GWQTG5F&gtm=45je3a20&_p=1797054443&cid=439315590.1695428951&ul=en-gb&sr=1440x900&uaa=x86&uab=64&uafvl=Google%2520Chrome%3B117.0.5938.132%7CNot%253BA%253DBrand%3B8.0.0.0%7CChromium%3B117.0.5938.132&uamb=0&uam=&uap=Windows&uapv=14.0.0&uaw=0&are=1&_s=2&sid=1696417348&sct=5&seg=1&dl=https%3A%2F%2Fplay.draftstars.com.au%2Fbetting%2F&dr=https%3A%2F%2Fwww.protopage.com%2F&dt=PlayUp%20-%20Proudly%20Australian%20%7C%20Home&en=user_engagement&ep.ga_client_id=439315590.1695428951&ep.ga_session_id=1696419079094.1ogprgkb&ep.hit_timestamp=2023-10-04T22%3A31%3A19.94%2B11%3A00&_et=10237
+19	whitelisted	++	play.draftstars.com.au	1	get	doc	https://play.draftstars.com.au/betting/
+19	https://play.draftstars.com.au/betting/
+1			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/user/?include=boosts,bonuses
+1			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/user/?include=boosts,bonuses
+0			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/sports/?include=competitions
+0			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/sport_events/?include=primary_market_group.markets.selections,participants,primary_market_group.markets.excluded_market_types&filter[start_time][from]=2023-10-04T20%3A31%3A49%2B11%3A00&filter[start_time][to]=2023-10-05T04%3A31%3A49%2B11%3A00&page[size]=100
+0			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/meetings/?include=races&filter%5Bstart_date%5D%5Bfrom%5D=2023-10-04&filter%5Bstart_date%5D%5Bto%5D=2024-10-04&filter%5Bis_future%5D=1&page%5Bsize%5D=100&page%5Bnumber%5D=1
+0			play.draftstars.com.au	3	options	xhr	https://wagering-api.playup.io/v1/meetings/?include=races&filter%5Bstart_date%5D%5Bfrom%5D=2023-10-04&filter%5Bstart_date%5D%5Bto%5D=2023-10-04&filter%5Bis_future%5D=0&page%5Bsize%5D=100&page%5Bnumber%5D=1
+0			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/sports/?include=competitions
+0			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/sport_events/?include=primary_market_group.markets.selections,participants,primary_market_group.markets.excluded_market_types&filter[start_time][from]=2023-10-04T20%3A31%3A49%2B11%3A00&filter[start_time][to]=2023-10-05T04%3A31%3A49%2B11%3A00&page[size]=100
+0			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/meetings/?include=races&filter%5Bstart_date%5D%5Bfrom%5D=2023-10-04&filter%5Bstart_date%5D%5Bto%5D=2024-10-04&filter%5Bis_future%5D=1&page%5Bsize%5D=100&page%5Bnumber%5D=1
+0			play.draftstars.com.au	3	get	xhr	https://wagering-api.playup.io/v1/meetings/?include=races&filter%5Bstart_date%5D%5Bfrom%5D=2023-10-04&filter%5Bstart_date%5D%5Bto%5D=2023-10-04&filter%5Bis_future%5D=0&page%5Bsize%5D=100&page%5Bnumber%5D=1

**Comment by mapx-** [comment]
- impossible to work with such log
- select ONLY the blocked items in the logger
- click one by one the blocked items and copy only those from fanboy's list

**Comment by mapx-** [comment]
- remove that list
- go into filter lists section of uBO
- enable easylist annoyances but disable the specific chat widgets section

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/b71a08af-04ec-45ba-91f1-6961e1c4bcb2)
