### ISSUE TITLE
tvtv.us: ads

### ISSUE THREAD

**Issue by gh5496587908** [uBlockOrigin/uAssets#19955]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tvtv.us/ca/los-angeles/luUSA-CA67309-DEFAULT`

### Category

ads

### Description

ad leftover banner at bottom of browser viewport

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.3b3
Firefox: 118
filterset (summary):
 network: 104557
 cosmetic: 39750
 scriptlet: 18593
 html: 1052
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35749-48, 16m
  ublock-badware: 7223-0, 16m
  ublock-privacy: 587-0, 16m
  ublock-unbreak: 2176-1, 16m
  ublock-quick-fixes: 180-36, 16m
  easylist: 71398-273, 16m
  easyprivacy: 33205-84, 16m
  urlhaus-1: 11365-0, 16m
  plowe-0: 3720-1064, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 465 ms
 maxAssetCacheWait: 282 ms
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 1
  powerad.ai: 1
 extended:
  ##.channels > div[class^="MuiBox-root"]
  ##+js(set-constant, paAddUnit, noopFunc)
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by mapx-** [comment]
any new cosmetic filter will break the table, just a minor annoyance

If you turn off uBO (yes, you'll see ads) it seems the white strips are the normal view

So, test
`@@||tvtv.us^$ehide`

**Comment by mapx-** [comment]
In my case the element picker highlights it but will not disappear (firefox / chrome).
