### ISSUE TITLE
flooringsuppliescentre.co.uk: nuisance

### ISSUE THREAD

**Issue by sean-wils** [uBlockOrigin/uAssets#19950]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.flooringsuppliescentre.co.uk/`

### Category

nuisance

### Description

Cookie overlay that does not disappear if you "Manage your privacy settings" then "Save and Exit" without accepting all cookies. The page will reload after hitting Save and Exit, which will cause the same overlay to appear once more.

The overlay takes up the majority of the webpage on a mobile device. 

### Other extensions used

Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231003_083729_Firefox](https://github.com/uBlockOrigin/uAssets/assets/18518299/020de4c1-73ea-4c89-b10e-8a8b9abfd268)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 106427
 cosmetic: 32342
 scriptlet: 22275
 html: 1241
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5520-10, 13m
 default:
  user-filters: 0-0, never
  ublock-filters: 36118-334, 15m
  ublock-badware: 7651-0, 15m
  ublock-privacy: 587-1, 15m
  ublock-unbreak: 2181-3, 15m
  ublock-quick-fixes: 172-0, 15m
  adguard-mobile: 8671-126, 15m
  easylist: 71299-16695, 15m
  easyprivacy: 33203-721, 14m
  urlhaus-1: 11205-5, 14m
  plowe-0: 3720-1, 14m
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4137 ms
 maxAssetCacheWait: 59 ms
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 2
  netswitch.co.uk: 1
  vercel-insights.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
flooringsuppliescentre.co.uk###gdpr_cookie-mainWrapp
```

@ryanbr @Alex-302

**Comment by stephenhawk8054** [comment]
@sean-wils You can enable `EasyList/uBO – Cookie Notices` lists or `AdGuard/uBO – Cookie Notices` lists in uBO settings
