### ISSUE TITLE
androjungle.com: detection

### ISSUE THREAD

**Issue by DiegoCracks** [uBlockOrigin/uAssets#19958]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://androjungle.com/`

### Category

detection

### Description

detects the adblocker

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium Mobile: 116
filterset (summary):
 network: 106174
 cosmetic: 30903
 scriptlet: 18727
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  adguard-mobile: 8673-39, 1m
  easylist: 71323-16005, 1m
  easyprivacy: 33205-72, 1m
  plowe-0: 3720-1138, 1m
  ublock-badware: 7649-139, 1m
  ublock-filters: 35174-395, 1m
  ublock-privacy: 557-7, 1m
  ublock-quick-fixes: 179-46, 1m
  ublock-unbreak: 2134-36, 1m
  urlhaus-1: 11210-0, 1m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2042 ms
 maxAssetCacheWait: 20 ms
popupPanel:
 blocked: 9
 network:
  androjungle.com: 1
  googlesyndication.com: 6
  googletagmanager.com: 2
 extended:
  ##.ads
  ##ins.adsbygoogle
  ##+js(noeval-if, adsBlocked)
```
</details>

**Comment by BlazeFTL** [comment]
```
androjungle.com##+js(rmnt, script, doAction)
androjungle.com##+js(nano-stb, countdown, *)
