### ISSUE TITLE
n-tv.de: ads

### ISSUE THREAD

**Issue by ChristianMayer** [uBlockOrigin/uAssets#19951]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.n-tv.de/leute/Noch-Ehemann-verteidigt-Britney-Spears-gegen-Trump-Sohn-article24436660.html`

### Category

ads

### Description

There's a ad video showing in the middle of the page. It is marked as "Anzeige"

### Other extensions used

none. This happens in private mode with only uBlockOrigin active

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/10218721/44d5b7df-0973-437e-8587-fdd38ce3ce09)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 107174
 cosmetic: 44478
 scriptlet: 18675
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  DEU-0: 7096-0, 2m
  easylist: 71388-19, 2m
  easyprivacy: 33203-72, 2m
  plowe-0: 3720-1064, 2m
  ublock-badware: 7655-138, 2m
  ublock-filters: 34857-156, 2m
  ublock-privacy: 557-6, 2m
  ublock-quick-fixes: 247-92, 58m
  ublock-unbreak: 2129-35, 2m
  urlhaus-1: 11205-5, 2m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 38 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 678 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 105
 network:
  n-tv.de: 2
  adalliance.io: 3
  adnxs.com: 6
  amazon-adsystem.com: 1
  bilder-a.akamaihd.net: 2
  chartbeat.com: 2
  criteo.net: 1
  cwi.re: 2
  doubleclick.net: 1
  dspx.tv: 2
  emsservice.de: 4
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  indexww.com: 2
  instagram.com: 1
  justpremium.com: 4
  kameleoon.eu: 1
  opecloud.com: 6
  openx.net: 2
  otto.de: 24
  outbrain.com: 1
  pghub.io: 1
  smartadserver.com: 4
  stickyadstv.com: 1
  technical-service.net: 1
  vgwort.de: 1
  viralize.tv: 19
  vtracy.de: 2
  yieldlab.net: 5
 extended:
  ##.newcontent-note
  ##.topbanner-mobile
  ##.ems-slot
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(abort-on-property-read, embedAddefend)
  ##+js(set-constant, Object.prototype.adReinsertion, noopFunc)
  ##.ad-element
```
</details>

**Comment by okiehsch** [comment]
Any problems is you add
`||content.viralize.tv/display/*$script,domain=n-tv.de`
to your filter list.
Specifically are all videos showing content working fine with that filter.

**Comment by ChristianMayer** [comment]
Everything looks fine with that filter!

Thanks!

**Comment by okiehsch** [comment]
@monzta
`||content.viralize.tv/display/*$script,domain=n-tv.de`
for the regional german list.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/273b12a01ff4abcfe2ec26760c763fffc1a9b9ac
