### ISSUE TITLE
bkyb.net: ads

### ISSUE THREAD

**Issue by zen010101** [uBlockOrigin/uAssets#19959]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

 Use an Android or iPhone browser to access: `www.bkby.net` , ads will appear at the bottom of the screen

to remove it , need custom rule: `||fv7q2.com^`

### URL(s) where the issue occurs.

`https://www.bkyb.net`

### uBO version

 1.52.2

### Browser name and version

Edge, 117.0.2045.47

### Settings

NONE

**Comment by mapx-** [comment]
report here: 
https://github.com/cjx82630/cjxlist/issues
