### ISSUE TITLE
qiwi.gg: nuisance

### ISSUE THREAD

**Issue by Savanna5264** [uBlockOrigin/uAssets#19956]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://qiwi.gg/file/jaPe3001-FirefoxInstaller`

### Category

nuisance

### Description

Unnecessary "Click here to unlock" needs to be clicked before download button is shown.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/146903904/d84ed31e-5f5b-489e-9688-281ecee758e8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 114603
 cosmetic: 188588
 scriptlet: 28821
 html: 1240
listset (total-discarded, last-updated):
 added:
  adguard-social: 21586-859, 15m
  adguard-cookies: 27792-64, 15m
  ublock-cookies-adguard: 316-0, 15m
  adguard-popup-overlays: 24519-1542, 15m
  adguard-mobile-app-banners: 4657-1062, 15m
  adguard-other-annoyances: 13617-309, 15m
  adguard-widgets: 2312-1, 15m
  fanboy-thirdparty_social: 68-0, 15m
  easylist-annoyances: 3986-117, 15m
  easylist-chat: 141-11, 15m
  fanboy-cookiemonster: 48467-3877, 15m
  ublock-cookies-easylist: 316-316, 15m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35745-458, 15m
  ublock-badware: 7125-0, 15m
  ublock-privacy: 587-0, 15m
  ublock-unbreak: 2176-2, 15m
  ublock-quick-fixes: 180-0, 15m
  easylist: 71398-794, 15m
  easyprivacy: 33205-808, 15m
  urlhaus-1: 11210-0, 15m
  plowe-0: 3720-1, 15m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2893 ms
 maxAssetCacheWait: 1941 ms
popupPanel:
 blocked: 5
 network:
  getclicky.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
report here:
https://github.com/cjx82630/cjxlist/issues

**Comment by Savanna5264** [comment]
> report here: https://github.com/cjx82630/cjxlist/issues

That seems to be a Chinese regional list, is there a reason I should report there specifically? qiwi.gg is in English only AFAIK and is used by many English speaking sites. I can't read Chinese, so I'll have to use a translator to report anything there.

**Comment by mapx-** [comment]
right, copy / paste for another site :)

**Comment by mapx-** [comment]
However, I cannot see a "fix" for such a minor annoyance.

**Comment by Savanna5264** [comment]
> However, I cannot see a "fix" for such a minor annoyance.

Got it, thanks. I only reported here after seeing adguard did include a fix in their list.

**Comment by stephenhawk8054** [comment]
They use auto click: https://github.com/AdguardTeam/AdguardFilters/commit/1cc32af0e7f91b19fd5c9dc238d0441ae2e194f6

**Comment by mapx-** [comment]
I tested something similar .. but does not work

    qiwi.gg##+js(rpnt, script, (self.__next_f=self.__next_f||[]).push([0]), (self.__next_f=self.__next_f||[]).push([0]); var AG_onLoad=function(func){if(document.readyState==="complete"||document.readyState==="interactive")func();else if(document.addEventListener)document.addEventListener("DOMContentLoaded"\,func);else if(document.attachEvent)document.attachEvent("DOMContentLoaded"\,func)}; AG_onLoad(function() { var el=document.querySelector('[class^="DownloadButton_AdButton"]'); if(el) el.click(); }), log, 1)
