### ISSUE TITLE
ojomovies.com [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#1996]
URL(s) where the issue occurs

`https://www.ojomovies.com/pelicula/22579`

Describe the issue

Pop-up

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.15.24

Settings

Default

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by KiLL4FuNK** [comment]
Fake Button

**Comment by ZaphodBeebblebrox** [comment]
Which button is fake? There are too many buttons on the page to tell.

**Comment by lain566** [comment]
There's a popup
`https://www.ojomovies.com/`

**Comment by bogachenko** [comment]
@lain566 `ojomovies.com##+js(abort-current-inline-script.js, decodeURI, decodeURIComponent)`
