### ISSUE TITLE
[nsfw] shrinkforearn.in: breakage

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#19968]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shrinkforearn.in/O2jHVQuK`

### Category

breakage

### Description

cant get link

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/139833732/9b2fb56f-8e34-4966-8bcc-15ecf769cea0

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.3b2
Chromium Mobile: 110
filterset (summary):
 network: 111776
 cosmetic: 130624
 scriptlet: 25453
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-cookies: 27767-30, now
  adguard-mobile-app-banners: 4642-7, now
  adguard-other-annoyances: 13618-8, now
  adguard-popup-overlays: 24529-62, now
  adguard-social: 21598-920, now
  adguard-widgets: 2312-4, now
  ublock-annoyances: 5563-187, now
  ublock-cookies-adguard: 353-353, now
 default:
  adguard-mobile: 8673-12, now
  easylist: 71509-121, now
  easyprivacy: 33208-138, now
  plowe-0: 3720-1139, now
  ublock-badware: 7117-134, now
  ublock-filters: 32821-483, now
  ublock-privacy: 556-7, now
  ublock-quick-fixes: 183-33, 17m
  ublock-unbreak: 2138-37, now
  urlhaus-1: 11360-0, now
filterset (user): [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 568 ms (selfie)
 maxAssetCacheWait: 352 ms
popupPanel:
 blocked: 11
 network:
  a-ads.com: 1
  adswalla.com: 1
  cleverwebserver.com: 1
  cloudflareinsights.com: 1
  d3u598arehftfk.cloudfront.net: 2
  doubleclick.net: 1
  googletagmanager.com: 2
  oaphoace.net: 1
  ophoacit.com: 1
 extended:
  ##.banner-728x90
  ##.banner-468x60
  ##.myTestAd
  ##.cookie-message:not(html):not(body)
  ##.cookie-confirm
  ##.blog-item
  ##.banner
  ##.box-main .blog-item
  ##+js(abort-on-property-read, app_vars.force_disable_adblock)
  ##+js(set-constant, blurred, false)
  ##HTML
  ##.size300x250
  ##a[href^="https://a-ads.com/"]
```
</details>

**Comment by mapx-** [comment]
test in firefox mobile

**Comment by BlazeFTL** [comment]
Try 
```
viralxns.com###timeout, #tp-snp2:others()
viralxns.com###timeout:remove-attr(disabled)
viralxns.com,wp.uploadfiles.in,uploadsoon.com###tp-snp2, #timeout:style(display:block !important; margin-top: 520px !important; height: 100px !important; width: 100px !important)
wp.uploadfiles.in,uploadsoon.com###tp-snp2:others()
viralsbaba1.blogspot.com###btn-gotolink:style(display:block !important; margin-top: 410px !important; margin-left: 200px !important; height: 100px !important; width: 100px !important)
viralsbaba1.blogspot.com###btn-gotolink:remove-attr(disabled)
viralsbaba1.blogspot.com###btn-gotolink:others()
shrinkforearn.in##+js(rpnt, script, counter_value":"5", counter_value":"7")
shrinkforearn.in##.box-main:others()

**Comment by Fatcavill** [comment]
> test in firefox mobile, default settings, default lists

Same with default list bro

**Comment by Fatcavill** [comment]
wokring tnx
