### ISSUE TITLE
kinopoisk.ru: ads

### ISSUE THREAD

**Issue by RedCatGirl** [uBlockOrigin/uAssets#19964]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kinopoisk.ru/film/849/`

### Category

ads

### Description

Advertising appears before the video

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/576196/9a1d218e-8227-44e1-820c-d24939df6cb0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 126682
 cosmetic: 91177
 scriptlet: 19349
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt: 38286-9, 12m
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26436-118, 12m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1654-33, 12m
  https://easylist-downloads.adblockplus.org/easylist.txt: 71509-56, 12m
  POL-0: 7992-36, 12m
  POL-2: 1276-14, 12m
 default:
  user-filters: 32-0, never
  RUS-0: 39959-38310, 12m
  easylist: 71509-71509, 12m
  easyprivacy: 33208-465, 12m
  plowe-0: 3720-1076, 12m
  ublock-badware: 7123-133, 12m
  ublock-filters: 32589-172, 12m
  ublock-privacy: 556-15, 12m
  ublock-quick-fixes: 183-33, 12m
  ublock-unbreak: 2130-35, 12m
  urlhaus-1: 11210-0, 12m
filterset (user): [array of 35 redacted]
trustedset:
 added: [array of 43 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2122 ms
 maxAssetCacheWait: 1053 ms
popupPanel:
 blocked: 55
 network:
  adriver.ru: 1
  tns-counter.ru: 1
  yandex.net: 2
  yandex.ru: 51
 extended:
  ##div[class^="styles_adBlockWarningRoot"]
  ##[class*="footer"] > [class*="social-"]
  ##.ya-share2
  ##[class*="footer"] > [class*="content-links"] + div[class]
  ##a.kinopoisk-header-featured-menu__item ~ a.kinopoisk-header-fe…
  ##a[href^="https://yandex.ru/alice/"][class*="banner"]
  ##div[class*="styles_promoPopover"]
  ##div[class^="styles_plusBadgeCounter"]
  ##div[class^="styles_watchingServices"]
  ##header a[href*="utm_campai"]
  ##header[style*="--header-height:"][style*="150px"] > div > img
  ##div[class*=" styles_basicInfoSection"]:style(padding-top: 40px…
  ##div[class*=" styles_basicMediaSection"]:style(padding-top: 40p…
  ##div[class*="styles_baseContainer"] > div[class]:first-child > …
  ##div[class*="styles_baseContainer"] > div[class]:first-child:st…
  ##div[style="min-width:1px"]:style(min-height: 0 !important)
  ##.header-navigation:style(max-width: 100% !important)
  ##div[class*="styles_headerContainer"] + div[class^="styles_"]:s…
  ##div[class^="styles_footerContainer__"]:style(max-width: 100% !…
  ##header[style*="--header-height:"][style*="150px"] > .header-na…
  ##header[style*="--header-height:"][style*="150px"] div[class^="…
  ##+js(abort-on-property-read, Object.prototype.bannerOptions)
  ##+js(set-constant, Object.prototype.hasPreroll, null)
  ##+js(set-constant, Object.prototype.videoAd, noopFunc)
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
I only see this ad if I add exceptions:
```
widgets.kinopoisk.ru#@#+js(set-constant, Object.prototype.videoAd, noopFunc)
widgets.kinopoisk.ru#@#+js(set-constant, Object.prototype.hasPreroll, null)
```
But I admit that these advertisements could be embedded in an alternative way, and then these rules would be useless. I think, need to look at the logger data here.

**Comment by mapx-** [comment]
> need to look at the logger data here.

@RedCatGirl open the logger, repeat the steps to get the ads, go back in in the logger, post here ALL the items you see there

**Comment by dimisa-RUAdList** [comment]
It seems that when replacing the user agent, they use the frame `www.kinopoisk.ru` for trailers, and not `widgets.kinopoisk.ru`.

Hope this solves the problem: https://github.com/easylist/ruadlist/commit/b12b21e3e1dbb483d3ce705b4e06ca56e1064586

**Comment by RedCatGirl** [comment]
Very large log.
[Log.txt](https://github.com/uBlockOrigin/uAssets/files/12804511/log.txt)

**Comment by dimisa-RUAdList** [comment]
@RedCatGirl 
From your logger data it is clear that the frame `widgets.kinopoisk.ru` is used for trailers. However, for this frame there are already two rules that remove advertising, and they are quite effective even separately. It can be assumed that your uBO is broken, or something is interfering with it.

**Comment by mapx-** [comment]
We can assume it's in "unable to reproduce" category.

@RedCatGirl try reinstalling uBO (reset it), then additionally add only the recommended Russian lists

**Comment by dimisa-RUAdList** [comment]
I have already encountered unblocked video advertisements on `kinopoisk.ru`. One user reported that this happened after their Vivaldi browser was updated to version 6.1.3035.302. He tried reinstalling uBlock Origin and even installed the dev version, but this did not solve anything. As a result, he switched to using Google Chrome.

**Comment by dimisa-RUAdList** [comment]
@RedCatGirl 
Please indicate the exact version number of your browser.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
Apparently, the problem is specific to the Vivaldi browser, and uBlock Origin works differently in it than in other browsers.
<details>
<summary>Screenshot(s)</summary>

![swordfish](https://github.com/uBlockOrigin/uAssets/assets/20126984/942cd639-5c5a-40f9-80b6-4bcff1510f3b)

</details>

**Comment by RedCatGirl** [comment]
@mapx- 
Chrome 117.0.5938.92  (64bit)
Good work UBlockOrigin (v 1.52.2) on page https://www.kinopoisk.ru/film/849/ , not visible ad in video.

**Comment by dportvine** [comment]
@RedCatGirl 
Maybe you need to notify the developers. `https://vivaldi.com/bugreport/`

**Comment by dimisa-RUAdList** [comment]
I doubt that Vivaldi's developers will deal with this problem. Rather, @gorhill will solve it on his side.

And yet, this is not the first time that browser-specific features lead to a long search for a way to reproduce the problem.

Currently, many browsers (Opera, Vivaldi, Yandex, etc.) are listed in issues as Chromium. I find it useful to change the issues template to indicate the browser version more accurately.

**Comment by gorhill** [comment]
>  @gorhill will solve it on his side.

There are so many variants of Chromium out there, I just do not have the time (and interest, stamina) to investigate all their specific issues with uBO. uBO is not officially supported for Vivaldi.

It's cool if it works on a given variant since because it is a Chromium-based browser, but if it does not work, the choice is either to use another browser, or whoever suffer an issue specific to that browser, then contribute to solving the issue by investigating the root cause and proposing a fix. If it is trivial to fix without introducing code path specific to the variant, then I am willing to integrate the fix.
