### ISSUE TITLE
arras.io: detection

### ISSUE THREAD

**Issue by MandiYang** [uBlockOrigin/uAssets#19965]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://arras.io/`

### Category

detection

### Description

https://github.com/uBlockOrigin/uAssets/assets/64307609/8dc685e5-52c4-435e-a50b-24f496e92523

### Other extensions used

Bitwarden, Return youtube dislike, 2fas, Hikaru and GothamChess Tell You to MOVE, Terms of service didn't read.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 193870
 cosmetic: 42499
 scriptlet: 18930
 html: 1071
listset (total-discarded, last-updated):
 added:
  curben-phishing: 87862-16, 19m
  SWE-1: 4677-2, 19m
 default:
  user-filters: 0-0, never
  ublock-filters: 35796-87, 19m
  ublock-badware: 7125-0, 19m
  ublock-privacy: 586-0, 19m
  ublock-unbreak: 2177-2, 19m
  ublock-quick-fixes: 184-0, 19m
  easylist: 71509-713, 19m
  easyprivacy: 33208-718, 19m
  urlhaus-1: 11210-0, 19m
  plowe-0: 3720-1, 19m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1202 ms (selfie)
 maxAssetCacheWait: 457 ms
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  intergient.com: 1
 extended:
  ##a[href*="utm_content=banner"] img
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by ave9858** [comment]
I'm able to reproduce the detection in the screenshot after dying, and I also see the below detection message while in game. Test was done with default filters on a new profile and then again with all annoyance filters on.
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/a43c8043-6320-49d2-b8f9-9097acb1ec0f)

I also see these ads on the main page before starting the game:
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/134f4ea1-5a26-410b-bcca-0d433fdb852f)

**Comment by D4niloMR** [comment]
@ave9858 Try this:

```adb
arras.io##+js(rmnt, script, onerror)
||arras.io/img/server-hunter*.jpg$image,1p
```

**Comment by ave9858** [comment]
That removes the main page server ads, I'm unable to test the game right now due to VPN detection. Not sure why I could access the game previously.

**Comment by D4niloMR** [comment]
Proxy sites:

`arras.cx`
`arras.netlify.app`
`arrax.io`

Not sure if it's possible to filter this:
`sites.google.com/view/arras-io`
