### ISSUE TITLE
heise.de: breakage

### ISSUE THREAD

**Issue by lhpitn** [uBlockOrigin/uAssets#19978]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.heise.de/benachrichtigungen/heise-bot/`

### Category

breakage

### Description

heise bot dose not work with ublock enabled

### Other extensions used

i dont care about cookies, tested disalbed dosnt cause the problem

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/45788285/08b9e20f-fc47-4497-be04-29ac62f159ab)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 117
filterset (summary):
 network: 106650
 cosmetic: 44607
 scriptlet: 18612
 html: 1056
listset (total-discarded, last-updated):
 default:
  user-filters: 6-1, never
  ublock-filters: 35819-48, now
  ublock-badware: 7140-0, now
  ublock-privacy: 587-0, now
  ublock-unbreak: 2180-3, now
  ublock-quick-fixes: 157-18, now
  easylist: 71545-701, now
  easyprivacy: 33209-722, now
  urlhaus-1: 11125-0, now
  plowe-0: 3720-1, now
  DEU-0: 7096-17, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8266 ms (selfie)
 maxAssetCacheWait: 412 ms
popupPanel:
 blocked: 25
 network:
  heise.de: 4
  3lift.com: 2
  adnxs.com: 2
  casalemedia.com: 1
  cleverpush.com: 2
  criteo.com: 1
  doubleclick.net: 1
  googlesyndication.com: 3
  indexww.com: 1
  kameleoon.eu: 1
  pubmatic.com: 2
  rubiconproject.com: 2
  upscore.com: 3
 extended:
  ##.ad--skyscraper
  ##.ad-label
  ##.ad--footer
  ##.ad
  ##.perf-cls-reduc-leaderboard
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by mapx-** [comment]
@lhpitn 

add

```
@@||cleverpush.com/channel/loader/$script,domain=heise.de
@@||cleverpush.com/sdk/$script,domain=heise.de
@@||liveapi.cleverpush.com/websocket$websocket,domain=heise.de
```

@ryanbr EP issue
