### ISSUE TITLE
kauppalehti.fi: nuisance

### ISSUE THREAD

**Issue by JoriHelin** [uBlockOrigin/uAssets#19974]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kauppalehti.fi/`

### Category

nuisance

### Description

Using shared company account, Alma media group websites, like kauppalehti.fi prompt to create personal account for more "features".

List of media group websites can be found
`https://www.almamedia.fi/palvelut/kaikki-palvelut/`

Includes:
```
Tivi.fi
https://www.talouselama.fi/
https://www.uusisuomi.fi/
https://www.tekniikkatalous.fi/
```

And others

##.iQivge.Dialogue__Overlay-tmcl-__sc-1lkk2xh-0

### Other extensions used

None

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/126866563/13bce8e2-8d66-489e-8fac-9e7953c2e91c

https://github.com/uBlockOrigin/uAssets/assets/126866563/b6f6a732-4cb7-4a76-a78e-136225cadea9

https://github.com/uBlockOrigin/uAssets/assets/126866563/11d1bf3d-99d5-49f3-9a08-c0862f3cc9ac

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 105705
 cosmetic: 31016
 scriptlet: 18665
 html: 1056
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36118-321, now
  ublock-badware: 7134-0, now
  ublock-privacy: 586-1, now
  ublock-unbreak: 2185-3, now
  ublock-quick-fixes: 154-0, now
  adguard-mobile: 8674-126, 2m
  easylist: 71537-16681, now
  easyprivacy: 33208-721, now
  urlhaus-1: 11125-0, 1m
  plowe-0: 3720-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2208 ms (selfie)
 maxAssetCacheWait: 104 ms
popupPanel:
 blocked: 3
 network:
  abtasty.com: 1
  adnxs.com: 1
  chartbeat.com: 1
```
</details>

**Comment by mapx-** [comment]
> Using shared company account

You should investigate on your own

@peace2000 what do you think about ?

**Comment by peace2000** [comment]
@JoriHelin What exactly is the context when you get that notification?

I get that dialogs are usually annoying, but one of those features mentioned - "mobiililukuoikeus" - means a right to read on mobile... It sounds important information for someone who is using a mobile phone.

**Comment by JoriHelin** [comment]
Our company is paying a group account for employees to be reading news articles. These websites keep prompting users to create personal accounts, which would lose them that  ability to read paywalled articles. Mobiililukuoikeus, ability to read on mobile does not even make sense, as their website and everything work perfectly fine with mobile browsers. They can mean an app, but i have never seen such.

I will see if i get said popup on computer with access to dev tools so i can grab element info etc. As i dont think this dialog is that easy to repro without said group account.

**Comment by JoriHelin** [comment]
Same dialogue is also opening on PC version. 

HTML of the dialogue:
[dialogue.txt](https://github.com/uBlockOrigin/uAssets/files/12827330/dialogue.txt)


Blocking element with element picker also breaks scrolling on news articles.

**Comment by mapx-** [comment]
test

```
kauppalehti.fi##[class^="Dialogue__Overlay-tmcl"]
kauppalehti.fi##body:style(overflow: auto !important;)
```

**Comment by JoriHelin** [comment]
Looking good on mobile, will test other pages as well as desktop.

**Comment by JoriHelin** [comment]
Same rule was added to annoyances for:
https://www.talouselama.fi/
https://www.uusisuomi.fi/
https://www.tekniikkatalous.fi/
https://www.tivi.fi/
?

as all of the above do have same dialog popup.

**Comment by peace2000** [comment]
@JoriHelin It's updated now.
