### ISSUE TITLE
douyin.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#19972]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.douyin.com/`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/1384709b-5906-4211-8e5a-b9464d45f10f)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 122773
 cosmetic: 115870
 scriptlet: 25356
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 24947-171, never
  easylist-annoyances: 3987-32, now
  easylist-notifications: 2679-79, now
  fanboy-cookiemonster: 48476-217, now
  fanboy-social: 16230-10, now
  ublock-annoyances: 5504-71, now
  ublock-cookies-easylist: 316-316, now
 default:
  user-filters: 0-0, never
  easylist: 71537-13, now
  easyprivacy: 33208-151, now
  plowe-0: 3720-1063, now
  ublock-badware: 7138-133, now
  ublock-filters: 34920-162, now
  ublock-privacy: 556-8, now
  ublock-quick-fixes: 153-21, now
  ublock-unbreak: 2133-37, now
  urlhaus-1: 11125-0, now
filterset (user): [empty]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 782 ms
 maxAssetCacheWait: 219 ms
popupPanel:
 blocked: 2
 network:
  google.com: 2
```
</details>

**Comment by mapx-** [comment]
use it as custom filter:

`douyin.com##[id^="login-full-panel"]`

but you'll not be able to log in anymore
