### ISSUE TITLE
bookszone.in: ads

### ISSUE THREAD

**Issue by MayaBi7** [uBlockOrigin/uAssets#19975]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bookszone.in/?p=2217`

Main link `https://olamovies.rest/generate/?id=101478`

### Category

ads

### Description

Can u make bypass for this site

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium Mobile: 116
filterset (summary):
 network: 101928
 cosmetic: 111541
 scriptlet: 25193
 html: 0
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
  urlhaus-1: null
 added:
  IND-0: 12703-0, 1h.29m
  easylist-annoyances: 3987-32, now
  fanboy-cookiemonster: 48470-216, now
  fanboy-social: 16235-10, now
  ublock-annoyances: 5566-79, now
 default:
  user-filters: 0-0, never
  easylist: 71544-17, now
  easyprivacy: 33208-75, now
  plowe-0: 3720-1063, now
  ublock-badware: 7132-133, now
  ublock-filters: 35248-164, now
  ublock-privacy: 557-8, now
  ublock-quick-fixes: 152-20, now
  ublock-unbreak: 2138-37, now
filterset (user): [empty]
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 hyperlinkAuditingDisabled: false
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1314 ms (selfie)
 maxAssetCacheWait: 246 ms
popupPanel:
 blocked: 4
 network:
  bookszone.in: 1
  360playvid.info: 1
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##.quads-location
  ###ast-scroll-top
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(remove-node-text, script, onerror)
```
</details>

**Comment by mapx-** [comment]
- in my case I get `tii.la` not `bookszone.in`
- however, search for a bypasser on your own

**Comment by BlazeFTL** [comment]
The Problem Is It Randomizes The Shortner Sites....So Its Difficult To Keep Track Of It With Them Changing Domains Every Week...I Will Post Few Fixes If I Can
