### ISSUE TITLE
myanimelist.net: ads

### ISSUE THREAD

**Issue by along02** [uBlockOrigin/uAssets#19971]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://myanimelist.net/`

### Category

ads

### Description

Ads on top, left, and right.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1512" alt="Screenshot 2023-10-04 at 12 31 12 PM" src="https://github.com/uBlockOrigin/uAssets/assets/21041802/b175feb1-8749-4851-9e5c-334c1c2f92fe">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 104556
 cosmetic: 39862
 scriptlet: 18689
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71537-13, 2m
  easyprivacy: 33208-64, 2m
  plowe-0: 3720-1063, 2m
  ublock-badware: 7138-133, 2m
  ublock-filters: 34920-143, 2m
  ublock-privacy: 556-6, 2m
  ublock-quick-fixes: 153-20, 2m
  ublock-unbreak: 2133-33, 2m
  urlhaus-1: 11360-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 201 ms
 maxAssetCacheWait: 83 ms
popupPanel:
 blocked: 5
 network:
  myanimelist.net: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||myanimelist.net/c/img/images/event/
```

@ryanbr

**Comment by stephenhawk8054** [comment]
https://github.com/easylist/easylist/commit/cfa14cdfb47e111f82f86bc032222ec55c182197
