### ISSUE TITLE
finance.yahoo.com: ads

### ISSUE THREAD

**Issue by terp313** [uBlockOrigin/uAssets#19973]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ad placedholders are not being hidden on the desktop site finance.yahoo.com
I know my settings and configuration are not a problem because the issue does not exist if I:
1) Disable ublock
2) Load finance.yahoo.com
3) Enable ublock

If I do the steps above which is basically loading the page while ublock is disabled and then enable ublock the problem does not exist. If I visit the page while ublock is enabled then the problem happens every time.

### URL(s) where the issue occurs.

`https://finance.yahoo.com/`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/147012971/d8b54961-c2ca-4a6e-b7a5-1c333333d438
https://github.com/uBlockOrigin/uAssets/assets/147012971/c463fdcb-ed2c-4145-a776-32f7df0ce744

### uBO version

1.52.2

### Browser name and version

Google Chrome Version 117.0.5938.149 (Official Build) (64-bit)

### Settings

N/A - Issue exists even with a fresh install of ublock

### Notes

I tried removing ublock and re-installing it and  the problem still exists in the same manner. Additionally, the fact that turning ublock off and on again fixing the issue proves that this is not a settings/configuration issue of any kind.

**Comment by stephenhawk8054** [comment]
```adb
finance.yahoo.com###mrt-node-Lead-0-Ad
finance.yahoo.com##[id^="defaultLREC"]
finance.yahoo.com##.ad-lrec3
```

@ryanbr

**Comment by terp313** [comment]
Found more yahoo finance pages that show one ad placeholder at the top.  Seems to be basically any quote page and the URL endings vary based on where the ticker symbol was clicked from.  Some examples are:

https://finance.yahoo.com/quote/AAPL/?p=AAPL
https://finance.yahoo.com/quote/TSLA?p=TSLA&ncid=yahooproperties_peoplealso_km0o32z3jzm
https://finance.yahoo.com/quote/LCID?p=LCID&ncid=yahooproperties_stockrecom_g40boan2td8


Can furnish additional screenshots if needed

**Comment by terp313** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/147012971/31a9ed28-6eb4-4a43-b068-7fe26d254958)
![image](https://github.com/uBlockOrigin/uAssets/assets/147012971/4d596db7-445a-4f61-9c0b-185d4476cce3)
![image](https://github.com/uBlockOrigin/uAssets/assets/147012971/3643380c-32f1-4c27-a754-de0711bd75b4)

**Comment by terp313** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/147012971/79625fb5-99e4-4b93-a30e-dd50a3ded1ac)

**Comment by mapx-** [comment]
Did you force update all filter lists (after the yesterday's fix) ?

**Comment by terp313** [comment]
I hit apply changes after making the change and I see that auto update filters is checked unless there's a separate force option?

![image](https://github.com/uBlockOrigin/uAssets/assets/147012971/6e4c2c6c-8362-4c45-9b43-2d1a1b4f52c2)

**Comment by mapx-** [comment]
You have to click "purge all caches", then "update now"

**Comment by terp313** [comment]
Tried that and the quote pages still are not fixed.  The original yahoo finance home page remains fixed though.

**Comment by terp313** [comment]
Disabled all other extensions, re-installed ublock, inputted the fix, purged all caches and update now.... issue is still not fixed.

One other observation is that if I refresh the page, the ad placement will properly disappear. But it always comes back on a new load of any of those pages.

**Comment by mapx-** [comment]
if I try in android emulation (samsung ultra s20 for example) I get some other PH

see if helps you:

```
finance.yahoo.com##[id*="Ad-Proxy"]
finance.yahoo.com##[id^="defaultWFPAD"]
```

**Comment by terp313** [comment]
That did the trick! Thanks.
