### ISSUE TITLE
moebelix.at: nuisance

### ISSUE THREAD

**Issue by ExteriorCloth20** [uBlockOrigin/uAssets#19980]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.moebelix.at/`

### Category

nuisance

### Description

leftover darkened overlay from cookie pop up. Cookie pop up window is blocked but overlay is not.
Blocking this element fixed it:

! 2023-10-05 https://www.moebelix.at
www.moebelix.at##._1zBP5ruymc38ND7B._SKfiFsiEOCG2lWvx._v-qs6Y5hTXMmFt87

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 111358
 cosmetic: 112961
 scriptlet: 26369
 html: 1244
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 954-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2277-0, now
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1916-15, 1m
  block-lan: 54-0, now
  easylist-annoyances: 3986-95, now
  easylist-chat: 141-0, now
  fanboy-cookiemonster: 48478-279, now
  easylist-newsletters: 6519-14, now
  easylist-notifications: 2679-5, now
  fanboy-social: 16235-7, now
  ublock-annoyances: 5467-350, now
  ublock-cookies-easylist: 319-0, now
 default:
  user-filters: 9-0, never
  ublock-filters: 35821-82, now
  ublock-badware: 7140-0, now
  ublock-privacy: 587-47, now
  ublock-unbreak: 2180-2, now
  ublock-quick-fixes: 157-0, now
  easylist: 71545-732, now
  easyprivacy: 33209-807, now
  urlhaus-1: 11125-0, now
  plowe-0: 3720-2, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 230 ms (selfie)
 maxAssetCacheWait: 98 ms
popupPanel:
 blocked: 10
 network:
  moebelix.at: 1
  googletagmanager.com: 2
  statsigapi.net: 6
  trbo.com: 1
 extended:
  ###scrollToTopButton
  ###cookieBar
  ###jentis_consent
```
</details>

**Comment by mapx-** [comment]
add

`moebelix.at###jentis_consent:upward(2)`

or
`moebelix.at##body > div > div:has(#jentis_consent)`

@ryanbr
