### ISSUE TITLE
manoramamax.com: detection

### ISSUE THREAD

**Issue by cryptoweeknd** [uBlockOrigin/uAssets#19981]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.manoramamax.com/programs/detail/122743/marimayam`

### Category

detection

### Description

detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 96647
 cosmetic: 39873
 scriptlet: 18701
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71546-13, 6m
  easyprivacy: 33209-64, 6m
  plowe-0: 3720-1063, 5m
  ublock-badware: 7148-133, 5m
  ublock-filters: 34941-143, 5m
  ublock-privacy: 557-6, 5m
  ublock-quick-fixes: 156-24, 5m
  ublock-unbreak: 2133-31, 5m
  urlhaus-1: 3432-0, 5m
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 503 ms (selfie)
 maxAssetCacheWait: 189 ms
popupPanel:
 blocked: 12
 network:
  manoramamax.com: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  gsecondscreen.com: 2
  imasdk.googleapis.com: 2
  myplex.com: 4
 extended:
  ##div[id^="dfp-ad-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.ad-section
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
Explain when do you get the detection.
Is an account required ?

**Comment by mapx-** [comment]
I guess a subscription is needed.

@cryptoweeknd just test (simple guess as I have no account):

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=manoramamax.com
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$script,domain=manoramamax.com
```

if does work, remove them and try:
```
||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect-rule=google-ima.js,domain=manoramamax.com
@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js$script,domain=manoramamax.com
```

if does not work or you get video ads => 
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by cryptoweeknd** [comment]
When we try to play a video, it is showing - using an ad blocker tool. (screenshot attached)
https://i.postimg.cc/vHmrJtCx/ad-cleaned.jpg
Yes, need to register. In our case,  no need subscription.
