### ISSUE TITLE
mtv.fi: breakage

### ISSUE THREAD

**Issue by hege666999** [uBlockOrigin/uAssets#19983]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mtv.fi/video/7a834a143f51daf7f4a6/jakso-4471-kadun-varjoisalla-puolella`

### Category

breakage

### Description

i dont know what to say. Ublock didnt work anymore with mtv and youtube. It only says "put it off"

### Other extensions used

only fsecure and malwarebytes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 103424
 cosmetic: 41889
 scriptlet: 18717
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FIN-0: 2203-0, 5m
  easylist: 71546-13, 1m
  easyprivacy: 33211-64, 5m
  plowe-0: 3720-1063, 5m
  ublock-badware: 7148-133, 5m
  ublock-filters: 34958-143, 1m
  ublock-privacy: 557-6, 5m
  ublock-quick-fixes: 156-24, 5m
  ublock-unbreak: 2133-32, 5m
  urlhaus-1: 10020-0, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 608 ms
 maxAssetCacheWait: 234 ms
popupPanel:
 blocked: 12
 network:
  mtv.fi: 1
  adobedtm.com: 2
  bugsnag.com: 4
  demdex.net: 1
  google.com: 2
  videoplaza.tv: 1
  youborafds01.com: 1
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by mapx-** [comment]
What Chromium browser are you using ? chrome, edge, vivaldi, brave etc ?

**Comment by hege666999** [comment]
Just Google Chrome. I tried clear cache and reset ubo, reinstall ubo and
restart the system.  Earlier my antivirus didnt disturb that uBO system but
now something is wrong.

to 5.10.2023 klo 22.36 mapx ***@***.***> kirjoitti:
