### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by CmdOffical** [uBlockOrigin/uAssets#19985]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch`

### Category

detection

### Description

When accessing youtube on google chrome. The message appers "Ad blockers are not allowed on YouTube".

### Other extensions used

Adblock Plus - free ad blocker
Block YouTube™ ads, pop-ups & fight malware!

Chrome extension source viewer
View source code of Chrome extensions, Firefox addons or Opera extensions (crx/nex/xpi) from the Chrome web store and elsewhere.

Dark Reader
Dark mode for every website. Take care of your eyes, use dark theme for night and daily browsing.

Google Docs Offline
Edit, create, and view your documents, spreadsheets, and presentations — all without internet access.

Microsoft Power Automate
Add-on for enabling web automation. This web extension is compatible with Power Automate for desktop version 2.27 or later.

uBlock Origin
Finally, an efficient blocker. Easy on CPU and memory.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 96689
 cosmetic: 39883
 scriptlet: 18709
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71546-13, now
  easyprivacy: 33213-64, now
  plowe-0: 3720-1063, now
  ublock-badware: 7183-133, now
  ublock-filters: 34962-143, now
  ublock-privacy: 557-6, now
  ublock-quick-fixes: 160-28, now
  ublock-unbreak: 2133-31, now
  urlhaus-1: 3432-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 220 ms (selfie)
 maxAssetCacheWait: 81 ms
popupPanel:
 blocked: 32
 network:
  youtube.com: 12
  doubleclick.net: 3
  google.com: 17
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytd-promoted-video-renderer
  ##.ytd-search-pyv-renderer
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/, …
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\…
  #@#+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,…
  #@#+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/,…
```
</details>

**Comment by stephenhawk8054** [comment]
Force update all your filter lists and test again.

Then please just continue in this thread: https://github.com/uBlockOrigin/uAssets/issues/19976

> - [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
