### ISSUE TITLE
kejriwalyojana.com: detection

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uAssets#19987]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kejriwalyojana.com/?lid=NJuwKJU&pid=611556&plid=11&vid=212869455`

### Category

detection

### Description

Adblock detection 

### Other extensions used

Dark reader, Google search fixer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-10-06-10-05-06-42_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/98148960/a41e7204-c9e8-4afa-8527-cb549352880c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 117789
 cosmetic: 139308
 scriptlet: 27783
 html: 1244
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 11228-8, 1m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2274-0, 1m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=raw: 180-0, now
  adguard-spyware-url: 1249-189, now
  adguard-social: 21847-168, now
  adguard-cookies: 27779-50, now
  ublock-cookies-adguard: 356-0, now
  adguard-popup-overlays: 24557-1018, now
  adguard-mobile-app-banners: 4646-7, now
  adguard-other-annoyances: 13627-100, now
  adguard-widgets: 2312-1, now
  ublock-annoyances: 5526-369, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36161-716, now
  ublock-badware: 7179-0, now
  ublock-privacy: 587-46, now
  ublock-unbreak: 2185-1, now
  ublock-quick-fixes: 162-0, now
  adguard-mobile: 8678-107, now
  easylist: 71552-624, now
  easyprivacy: 33213-766, now
  urlhaus-1: 11425-0, 1m
  plowe-0: 3720-2, now
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1974 ms
 maxAssetCacheWait: 1224 ms
popupPanel:
 blocked: 9
 network:
  doubleclick.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 3
  gplinks.in: 3
 extended:
  #@#ins.adsbygoogle
  #@#.adsbygoogle-noablate
```
</details>

**Comment by BlazeFTL** [comment]
@MasterKia From `https://gplinks.co/493S`
They Change Domain Often
https://github.com/uBlockOrigin/uAssets/commit/05805b29479620b7ef10935da29f1fb6e23ff75f
