### ISSUE TITLE
unsplash.com: error on load

### ISSUE THREAD

**Issue by OliverJAsh** [uBlockOrigin/uAssets#19982]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Set window width to 500px and go to `https://unsplash.com`.

### URL(s) where the issue occurs.

`https://unsplash.com`

### Screenshot(s)

<img width="1840" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/921609/fcb01c47-d04f-4095-a77c-e0fe8f82ffcc">

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 103217
 cosmetic: 39877
 scriptlet: 18693
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 71545-13, 7h.10m
  easyprivacy: 33208-64, 7h.9m
  plowe-0: 3721-1067, 6d.8h.59m
  ublock-badware: 7138-133, 7h.13m
  ublock-filters: 34934-143, 7h.12m
  ublock-privacy: 556-6, 3h.53m
  ublock-quick-fixes: 153-20, 9h.15m
  ublock-unbreak: 2133-33, 7h.11m
  urlhaus-1: 10020-0, 2h.45m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 130 ms (selfie)
 maxAssetCacheWait: 48 ms
```
</details>

**Comment by mapx-** [comment]
it should work

```
unsplash.com#@#div[style^="--row-gutter"] > div a[href="/brands"]:upward(div[style^="--row-gutter"] > div):remove()
unsplash.com##div[style^="--row-gutter"] > div a[href="/brands"]:upward(div[style^="--row-gutter"] > div)
```
