### ISSUE TITLE
finance.yahoo.com: ads

### ISSUE THREAD

**Issue by terp313** [uBlockOrigin/uAssets#19986]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This is a branch from Issue #19973 which was fixed but did not address other pages on Yahoo Finance.  The issue I reported there is that ad placement is not properly hidden on the Yahoo Finance homepage.  After that ticket was closed I found that several "quote" pages still have one ad placement on top that isn't hidden.  It's basically any quote page and the end of the URL varies not only on the ticker symbol but what kind of list the symbol was clicked from.  Sample URL's below.

### URL(s) where the issue occurs.

https://finance.yahoo.com/quote/AAPL/?p=AAPL

https://finance.yahoo.com/quote/TSLA?p=TSLA&ncid=yahooproperties_peoplealso_km0o32z3jzm

https://finance.yahoo.com/quote/LCID?p=LCID&ncid=yahooproperties_stockrecom_g40boan2td8

### uBO version

1.52.2

### Browser name and version

Google Chrome Version 117.0.5938.149 (Official Build) (64-bit)

### Settings

N/A - Tested in a fresh install

**Comment by stephenhawk8054** [comment]
Just continue in the old thread. We are all notified with new comments. No need to open duplicated issues.
