### ISSUE TITLE
game3rb.com: breakage

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#19994]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://game3rb.com/`

### Category

breakage

### Description

The search button disappears and can't search anything on the website. Please fix :)

### Other extensions used

None related to ad blocking

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Web page with uBO turned on](https://github.com/uBlockOrigin/uAssets/assets/50150516/1a65f648-d3fa-473e-a2d4-fb0e25ec2396)
![Web page with uBO turned off](https://github.com/uBlockOrigin/uAssets/assets/50150516/8e9daa8b-a659-4ef2-aa8c-00c3f541d060)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 176914
 cosmetic: 228823
 scriptlet: 45499
 html: 0
listset (total-discarded, last-updated):
 added:
  ROU-1: 1442-3, 36m
  adguard-cookies: 27781-30, 36m
  adguard-generic: 78315-487, 36m
  adguard-mobile-app-banners: 4647-8, 36m
  adguard-other-annoyances: 13627-7, 36m
  adguard-popup-overlays: 24558-72, 36m
  adguard-social: 21847-923, 36m
  adguard-spyware: 61394-1383, 36m
  adguard-spyware-url: 1250-4, 36m
  adguard-widgets: 2312-5, 36m
  easylist-annoyances: 3986-239, now
  easylist-chat: 141-11, now
  [7 lists not shown]: [too many]
 default:
  user-filters: 77-4, never
  easylist: 71552-1196, 37m
  easyprivacy: 33213-16717, 37m
  plowe-0: 3717-1168, now
  ublock-badware: 7148-319, 37m
  ublock-filters: 34969-4281, 37m
  ublock-privacy: 557-139, now
  ublock-quick-fixes: 179-50, 36m
  ublock-unbreak: 2132-147, 37m
  urlhaus-1: 11180-0, 36m
filterset (user): [array of 77 redacted]
trustedset:
 added: [array of 110 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 887 ms (selfie)
 maxAssetCacheWait: 652 ms
popupPanel:
 blocked: 19
 network:
  amung.us: 3
  d1eknpz7w55flg.cloudfront.net: 3
  discordapp.com: 1
  googletagmanager.com: 3
  pagespeed-mod.com: 3
  purinediarize.com: 3
  wp.com: 3
 extended:
  ###social-top
  ###return-to-top
  ###overly-noti
  ##.con
  ##a[href*="//www.facebook.com/share.php"]
  ##a[href*="pinterest.com/pin/create/button"]
  ##a[href^="http://www.linkedin.com/shareArticle"]
  ##a[href^="https://plus.google.com/share"]
  ##a[href^="https://twitter.com/home?"]
  ##a[href^="http://www.linkedin.com/shareArticle?"]
  ##a[href^="https://plus.google.com/share?"]
  ##a[href^="https://www.facebook.com/share.php?"]
  ##a[href^="https://www.pinterest.com/pin/create/button?"]
  ##+js(abort-on-property-read, plzdisa)
  ##+js(abort-current-script, loadScript, )]['innerHTML')
  ##+js(no-fetch-if, /pagead2\.googlesyndication\.com|cloudfront\.…
  ##+js(abort-current-script, Math, /emZnbG9hZGVk|break;case \$\./…
  ##+js(no-setTimeout-if, sadbl)
  ##+js(abort-current-script, navigator, FingerprintJS)
  ##+js(abort-current-script, onload, onclick)
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(addEventListener-defuser, DOMContentLoaded, 0x)
  ##+js(no-fetch-if, method:HEAD)
```
</details>

**Comment by mapx-** [comment]
maybe you enabled `EasyList – Social Widgets` too

add

`game3rb.com#@##social-top`

@ryanbr
