### ISSUE TITLE
Adblock Blockers

### ISSUE THREAD

**Issue by q-l-p** [uBlockOrigin/uAssets#200]
### URL(s) where the issue occurs

`http://www.criminalcasetools.com/en/`
`http://blockadblock.com/`

### Describe the issue

Some sites have implemented some sort of adblock blocking mechanism. 

### Screenshot(s)

Usually when I visited `criminalcasetools.com` the site looked like this:
![ss-criminalcasetools-before](https://cloud.githubusercontent.com/assets/19322149/20436384/bde67790-adb8-11e6-9330-78d7f6e84664.jpg)

But today it looked like this:
![ss-criminalcasetools-after](https://cloud.githubusercontent.com/assets/19322149/20436445/f61346e8-adb8-11e6-87fb-734b3300d474.jpg)

### Versions

- Mozilla Firefox 49.0.2
- uBlock Origin v2.3.1

### Settings

- Default settings

### Notes

I have noticed that the addon NoScript solves the issue on `criminalcasetools.com` but has no effect on `http://blockadblock.com/`.

**Comment by gorhill** [comment]
> uBlock Origin v2.3.1

There is no such as version uBlock Origin **2.3.1**.

**Comment by q-l-p** [comment]
@gorhill 
![ublock origin version](https://cloud.githubusercontent.com/assets/19322149/20438359/086a0244-adc0-11e6-9c28-4e2686e5c0f6.jpg)

**Comment by gorhill** [comment]
Not too happy with this, this is completely misleading, "AdNauseam" is **not** "uBlock Origin". uBlock Origin latest stable version is 1.9.16. Also, "uBlock" is also **not** "uBlock Origin".

**Comment by q-l-p** [comment]
I am sorry about all this... As you can see I originally posted this issue here: https://github.com/dhowe/AdNauseam/issues/624
@dhowe sent me here. I don't know what else to do.

**Comment by mapx-** [comment]
as you can see above gorhill added a fix, just update all your filters (especially ublock filters)

**Comment by dhowe** [comment]
Sorry, but where did the image above come from? AdNauseam has no relation with uBlock Origin (or the screenshot above, which is not from out interface) -- we simply credit uBlock and provide a link to https://github.com/gorhill/uBlock...

**Comment by q-l-p** [comment]
The image is in AdNauseam Settings in the About section. I'm just a user...

**Comment by dhowe** [comment]
Our about page looks like this:

![screen shot 2016-11-19 at 1 42 49 am](https://cloud.githubusercontent.com/assets/737638/20440347/b77d5490-adfa-11e6-83f6-3c051d52977d.png)

From where did you download this copy of AdNauseam?

**Comment by IDKwhattoputhere** [comment]
@dhowe Did you mean to link to uBlock Origin's repo?

**Comment by dhowe** [comment]
Sorry, I had the names confused momentarily. AdNauseam is based on Gorhill's uBlock Origin, from repo https://github.com/gorhill/uBlock.

**Comment by IDKwhattoputhere** [comment]
I see. Maybe that should be made clear in the about page then. Otherwise this is seems confusing.

**Comment by dhowe** [comment]
I've updated the link text now in our 'About' page to specify 'uBlock Origin', rather than simply 'uBlock'

However, this still does not explain where @q-i-p's screenshot comes from...

**Comment by q-l-p** [comment]
@dhowe I have installed the addon from Firefox addons: https://addons.mozilla.org/en-US/firefox/search/?q=adnauseam&appver=49.0&platform=windows  some months ago.
![adnauseam](https://cloud.githubusercontent.com/assets/19322149/20441111/c367d0f2-adcb-11e6-9014-54db5bfc865c.jpg)

**Comment by dhowe** [comment]
Thank you @q-l-p. I can now confirm this as a bug in v2.3.1 on Firefox. It has been fixed and verified in v2.4 which should be up on the various stores within the next few days. Apologies to uBlock devs for cluttering up this Issue space...
