### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Sydelle1981** [uBlockOrigin/uAssets#20003]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/'

### Category

detection

### Description

Everytime a new video launches I get the message, youtube doesn't allow pop-up blockers. I did use the find similar reports button and could not see any titles or tags with the detection variable. 

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Untitled](https://github.com/uBlockOrigin/uAssets/assets/147002467/af6bb6f9-d59c-45ca-9584-a8084a6d1366)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 104487
 cosmetic: 39893
 scriptlet: 18644
 html: 1058
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35868-180, 30m
  ublock-badware: 7188-0, 30m
  ublock-privacy: 589-0, 30m
  ublock-unbreak: 2183-0, 30m
  easylist: 71567-553, 30m
  easyprivacy: 33214-756, 30m
  urlhaus-1: 11210-0, 30m
  plowe-0: 3718-1, 30m
  ublock-quick-fixes: 178-0, 30m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 21963 ms (selfie)
 maxAssetCacheWait: 724 ms
popupPanel:
 blocked: 377
 network:
  youtube.com: 208
  doubleclick.net: 7
  google.ca: 1
  google.com: 161
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytd-compact-promoted-video-renderer
  ##.ytd-merch-shelf-renderer
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-compact-promoted-video-renderer
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\}…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/, …
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\…
  #@#+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,…
  #@#+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/,…
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/19976
