### ISSUE TITLE
watch.foxtel.com.au: ads

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#20006]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ads are still shown on the Foxtel website while watching stuff.
Ads are shown at the start, during and at the end of the shows.

### URL(s) where the issue occurs.

`https://watch.foxtel.com.au/app/#/shows/417265/seasons/2/episode/9942434/play`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/20948631/b3927989-3936-4254-99a9-dc943d47dc8b

### uBO version

1.52.2

### Browser name and version

Chrome

### Settings

<details>

```yml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 259800
 cosmetic: 227132
 scriptlet: 44897
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72882-108, 3d.10h.50m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 31033-0, 3h.12m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 3h.11m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93683-21602, 3d.10h.50m
  adguard-cookies: 27768-27768, 3d.10h.50m
  adguard-generic: 78102-533, 3d.10h.50m
  adguard-mobile-app-banners: 4645-4645, 3d.10h.50m
  adguard-other-annoyances: 13620-13620, 3d.10h.50m
  adguard-popup-overlays: 24537-24537, 3d.10h.50m
  adguard-social: 21605-1612, 3d.10h.50m
  adguard-widgets: 2312-2312, 3d.10h.50m
  block-lan: 54-0, 3d.10h.50m
  [11 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  easylist: 71537-1396, 3d.10h.50m
  easyprivacy: 33208-464, 3d.10h.50m
  plowe-0: 3720-1446, 3d.10h.50m
  ublock-badware: 7138-329, 3d.10h.50m
  ublock-filters: 34920-4225, 3d.10h.50m
  ublock-privacy: 556-8, 3d.10h.50m
  ublock-quick-fixes: 178-11, 5h.48m
  ublock-unbreak: 2133-96, 3d.10h.50m
  urlhaus-1: 11145-3911, 3h.10m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 533 ms (selfie)
 maxAssetCacheWait: 405 ms
```

</details>

**Comment by mapx-** [comment]
Without an account we cannot investigate.
Maybe even using an account a vpn is avoided ?!

**Comment by TesterMan247** [comment]
How cod provide a pasßor tóßhaàt

**Comment by mapx-** [comment]
You could give the password to a member of uBO team, we investigate, then you can change it.
If you agree, I'll provide an email address where you could send the pass.

**Comment by TesterMan247** [comment]
I cannot change the password to the site as I'm not the only one using it.
So you can understand my frustration.

**Comment by mapx-** [comment]
Well, if you do not trust us .. nothing to do.

**Comment by TesterMan247** [comment]
How about this: https://github.com/uBlockOrigin/uAssets/issues/20006#issuecomment-1752034069

**Comment by mapx-** [comment]
remote ? it's not a solution.

How do you think we fixed similar issues on paramount, disney, discovery and so on ? Simple: the users trusted us.

**Comment by mapx-** [comment]
@TesterMan247 

if you change your mind just leave a comment here.

closing now.

**Comment by TesterMan247** [comment]
OK. I want this issue to be fixed ASAP.
Please lets get this done.....

**Comment by mapx-** [comment]
send here the credentials: `axis.trivia@gmail.com`

**Comment by TesterMan247** [comment]
OK. Sent.
Thanks.

**Comment by mapx-** [comment]
@TesterMan247 

test this filter

    foxtel.com.au##+js(xml-prune, xpath(//*[name()="Period"][.//*[name()="BaseURL" and contains(text()\,'adease')]]), ,.mpd)
