### ISSUE TITLE
svd.se: breakage

### ISSUE THREAD

**Issue by rj-040** [uBlockOrigin/uAssets#20007]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.svd.se/`

### Category

breakage

### Description

Cannot scroll site. Looks to be related to a cookie acceptance overlay.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 198541
 cosmetic: 116471
 scriptlet: 25347
 html: 1263
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  block-lan: 54-0, now
  curben-phishing: 88974-16, now
  fanboy-thirdparty_social: 68-0, now
  easylist-annoyances: 3987-92, now
  easylist-chat: 141-0, now
  fanboy-cookiemonster: 48498-332, now
  ublock-cookies-easylist: 320-0, now
  easylist-newsletters: 6522-13, now
  easylist-notifications: 2706-4, now
  fanboy-social: 16234-30, now
  ublock-annoyances: 5472-349, now
  NOR-0: 3613-2, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 35785-91, now
  ublock-badware: 7188-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2183-0, now
  ublock-quick-fixes: 178-0, 35m
  easylist: 71572-362, now
  easyprivacy: 33216-117, now
  urlhaus-1: 11145-0, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 collapseBlocked: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 955 ms (selfie)
 maxAssetCacheWait: 180 ms
popupPanel:
 blocked: 15
 network:
  svd.se: 3
  adnxs.com: 3
  codigo.se: 1
  relevant-digital.com: 1
  schibsted.com: 7
 extended:
  ##.Ad
  ###mega-ad-wrapper, div[class*="advertory"], div[data-custom-ad-…
  ##div[id^="sp_message_container_"]
  ###schibsted-data-controller-sticky
  ##.ad-label
  ##.ad-wrapper
  ##.AdContainer
  ##.AdOuterMostContainer
  ##div#schibsted-data-controller-sticky
  ##.sch-datacontroller
  ##div.sch-datacontroller--footer
  ##body:style(visibility:visible!important;)
```
</details>

**Comment by mapx-** [comment]
test for breakage

`svd.se##+js(nostif, appendChild)`

**Comment by rj-040** [comment]
Yes, further testing shows that the problem is related to the list "EasyList – Cookie Notices".
Which I believe isn't managed by you uBO-guys. If so, please go ahead and close issue.

**Comment by mapx-** [comment]
already fixed by EL cookies maintainer, just update your lists
