### ISSUE TITLE
gripgrab.com: breakage

### ISSUE THREAD

**Issue by egonprint** [uBlockOrigin/uAssets#20001]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gripgrab.com/collections/commute/products/windster-2-windproof-winter-gloves`

### Category

breakage

### Description

Cookie information overlay is not showing when uBlock is active and breaks the entire site.

### Other extensions used

EFF Brivacy Badger
DuckDuckGo Privacy Essentials
https://github.com/uBlockOrigin/uAssets/assets/139455668/3196154f-1b5b-4cba-b378-76c00d340d7c

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105815
 cosmetic: 42523
 scriptlet: 18975
 html: 1076
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35868-70, now
  ublock-badware: 7188-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2183-0, now
  ublock-quick-fixes: 154-2, 28m
  easylist: 71567-701, now
  easyprivacy: 33214-719, now
  urlhaus-1: 10870-0, now
  plowe-0: 3717-1, now
  SWE-1: 4677-2, now
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 319 ms (selfie)
 maxAssetCacheWait: 82 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
disable / remove + test again
```
EFF Brivacy Badger
DuckDuckGo Privacy Essentials
```

**Comment by egonprint** [comment]
I have. It's uBlock that is the issue!
________________________________
Från: mapx ***@***.***>
Skickat: den 7 oktober 2023 09:29
Till: uBlockOrigin/uAssets ***@***.***>
Kopia: egonprint ***@***.***>; Author ***@***.***>
Ämne: Re: [uBlockOrigin/uAssets] gripgrab.com: breakage (Issue #20001)


disable / remove + test again

EFF Brivacy Badger
DuckDuckGo Privacy Essentials

**Comment by mapx-** [comment]
> popupPanel:  blocked: 0

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by egonprint** [comment]
OMG!


It's uBlock that is the ISSUE!
________________________________
Från: mapx ***@***.***>
Skickat: den 7 oktober 2023 09:40
Till: uBlockOrigin/uAssets ***@***.***>
Kopia: egonprint ***@***.***>; Author ***@***.***>
Ämne: Re: [uBlockOrigin/uAssets] gripgrab.com: breakage (Issue #20001)


popupPanel: blocked: 0

  *   clear cookies / localStorage/ cache for the tested page
  *   reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
  *   disable any custom filter for that site
  *   disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
  *   if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
  *   disable (if any) the web shields in your antivirus / antimalware software / other blocking software
  *   are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example => IP addresses 8.8.8.8 & 8.8.4.4)
  *   restart the system, reopen the browser, test again.

**Comment by mapx-** [comment]
Did you follow ALL the indications above ?

**Comment by egonprint** [comment]
YES!


________________________________
Från: mapx ***@***.***>
Skickat: den 7 oktober 2023 09:52
Till: uBlockOrigin/uAssets ***@***.***>
Kopia: egonprint ***@***.***>; Author ***@***.***>
Ämne: Re: [uBlockOrigin/uAssets] gripgrab.com: breakage (Issue #20001)


Did you follow ALL the indications above ?

**Comment by mapx-** [comment]
From which country did you access the page?

**Comment by mapx-** [comment]
ok, it's a breakage due to swedish list, add:

`gripgrab.com#@#.cc-window.cc-floating:not(body):not(html)`

@lassekongo83

**Comment by egonprint** [comment]
Sweden.
This is like the 5 or 6 times I report these kinds of issues and I really can't recommend friends and family to use uBlock since they are not tech savvy and have no idea what to do when a website breaks because of it.

//Erik
________________________________
Från: mapx ***@***.***>
Skickat: den 7 oktober 2023 09:56
Till: uBlockOrigin/uAssets ***@***.***>
Kopia: egonprint ***@***.***>; Author ***@***.***>
Ämne: Re: [uBlockOrigin/uAssets] gripgrab.com: breakage (Issue #20001)


From which country did you access the page?
