### ISSUE TITLE
elpais.com

### ISSUE THREAD

**Issue by Alex-Lema** [uBlockOrigin/uAssets#2000]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

All pages from El Pais (`https://elpais.com/`).
Example:
`https://politica.elpais.com/politica/2018/04/17/actualidad/1523968965_851940.html`

### Describe the issue

Page seems to load correctly, but then the anti-adblocker jumps in, the "anti-anti-adblocker" jumps in as well, and the page goes blank.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/38473870/38888923-5817edda-427d-11e8-82a1-cedb8baac84d.png)

### Versions

- Browser/version: Chrome  65.0.3325.181 (64-bit)
- uBlock Origin version: Nano Adblocker v1.0.0.41

### Settings

Nothing, just installed Nano Adblocker and Nano Defender. Didn't change anything from standard setup and updated all filters. 

### Notes

Nothing else to add, sorry.

**Comment by uBlock-user** [comment]
Add

`elpais.com##script:inject(addEventListener-defuser.js, /load|error/, removeChild)`

**Comment by KiLL4FuNK** [comment]
It works well for me what filters do you have? @Alex-Lema
![](https://i.imgur.com/LXmtj2D.png)

**Comment by mapx-** [comment]
I cannot reproduce the issue.

**Comment by Alex-Lema** [comment]
Weird, now it is working for me too. Tried a lot of pages in that domain and they all worked. The only difference is that, when I tried before, I was at work, and now I am at the hotel (work travel).
Well, I think we can close the issue. Really sorry about that.
