### ISSUE TITLE
lrepacks.net: breakage

### ISSUE THREAD

**Issue by helbetmathias** [uBlockOrigin/uAssets#20018]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lrepacks.net/`

### Category

breakage

### Description

So when I try to press on an post there nothing happens try it out

### Other extensions used

Sponsor block, Return Youtube Dislikes, 1Password

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 104066
 cosmetic: 39889
 scriptlet: 18684
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71615-13, now
  easyprivacy: 33222-64, now
  plowe-0: 3718-1065, now
  ublock-badware: 7191-133, 1m
  ublock-filters: 34919-144, 1m
  ublock-privacy: 559-6, now
  ublock-quick-fixes: 191-43, now
  ublock-unbreak: 2138-30, 1m
  urlhaus-1: 10725-0, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 644 ms (selfie)
 maxAssetCacheWait: 319 ms
popupPanel:
 blocked: 5
 network:
  translate.googleapis.com: 2
  yadro.ru: 1
  yandex.com: 1
  yandex.ru: 1
 extended:
  ##+js(abort-current-script, document.createElement, delete windo…
  ##+js(no-window-open-if)
```
</details>

**Comment by mapx-** [comment]
enable the regional list `RU AdList`
