### ISSUE TITLE
salutbonjour.ca: breakage

### ISSUE THREAD

**Issue by ravertine** [uBlockOrigin/uAssets#20012]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.salutbonjour.ca/Concours-Cest-super-avec-Olay`

### Category

breakage

### Description

contest form doesn't load with ublock enabled

`salutbonjour.ca##+js(set-constant, initDetectAdBlock, noopFunc)`
from AdGuard Français (French) seems to be causing the issue

### Other extensions used

too many to list...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.3b4
Chromium: 117
filterset (summary):
 network: 119569
 cosmetic: 85375
 scriptlet: 25548
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-other-annoyances: 13629-7, now
  adguard-popup-overlays: 24560-67, now
  easylist-annoyances: 3987-168, now
  ublock-annoyances: 5518-176, now
 default:
  user-filters: 3-1, never
  FRA-0: 28434-38, now
  easylist: 71590-140, now
  easyprivacy: 33220-399, now
  plowe-0: 3718-1076, now
  ublock-badware: 7191-147, now
  ublock-filters: 34911-587, now
  ublock-privacy: 559-8, now
  ublock-quick-fixes: 195-37, now
  ublock-unbreak: 2138-37, now
  urlhaus-1: 3933-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 810 ms (selfie)
 maxAssetCacheWait: 245 ms
popupPanel:
 blocked: 6
 network:
  cxense.com: 1
  doubleclick.net: 1
  go-mpulse.net: 1
  googletagmanager.com: 1
  quebecormedia.com: 1
  rubiconproject.com: 1
 extended:
  ##+js(set-constant, initDetectAdBlock, noopFunc)
```
</details>

**Comment by stephenhawk8054** [comment]
@Yuki2718 @Alex-302 

I think the filter is obsolete now?

**Comment by mapx-** [comment]
The code is still there (`core.js`), so maybe

```
salutbonjour.ca#@#+js(set, initDetectAdBlock, noopFunc)
salutbonjour.ca##+js(rpnt, script, adBlockerPopup":true, adBlockerPopup":false)
```

**Comment by Alex-302** [comment]
I can't reproduce anti-adblock. https://github.com/AdguardTeam/AdguardFilters/issues/52169

> contest form doesn't load with ublock enabled

Are some site functions broken?

**Comment by gorhill** [comment]
I can't see anti-blocker and site works fine without `salutbonjour.ca##+js(set-constant, initDetectAdBlock, noopFunc)`.

If ever anti-blocker is back, `salutbonjour.ca##+js(set, templateConfig.enable.ads, false)` might work.
