### ISSUE TITLE
agit327.com: ads

### ISSUE THREAD

**Issue by pololoduck** [uBlockOrigin/uAssets#20014]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://agit327.com/`

### Category

ads

### Description

The huge array of ads is still displayed, and there are more ads when you click on any of the webtoon to view a chapter as banners 

### Other extensions used

google translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/121998563/6dde3b90-ffcc-493b-8ea1-623e46dde431)
![image](https://github.com/uBlockOrigin/uAssets/assets/121998563/23b65102-67f1-4a9b-9aac-d9d20a62112b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 161253
 cosmetic: 254518
 scriptlet: 45374
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 25017-132, now
  FIN-0: 2207-0, now
  JPN-1: 13513-10, now
  KOR-1: 4595-12, now
  adguard-cookies: 27782-30, now
  adguard-generic: 78337-521, now
  adguard-mobile-app-banners: 4647-11, now
  adguard-other-annoyances: 13629-18, now
  adguard-popup-overlays: 24560-76, now
  adguard-social: 21849-924, now
  adguard-widgets: 2312-3, now
  dpollock-0: 11577-55, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 9-1, never
  easylist: 71590-1426, now
  easyprivacy: 33220-416, now
  plowe-0: 3718-1465, now
  ublock-badware: 7191-330, now
  ublock-filters: 34907-4238, now
  ublock-privacy: 559-10, now
  ublock-quick-fixes: 195-39, now
  ublock-unbreak: 2138-100, now
  urlhaus-1: 11045-0, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 871 ms (selfie)
 maxAssetCacheWait: 668 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
add

```
||agit327.com/*.gif$image
agit327.com##.banner
```

**Comment by piquark6046** [comment]
Fixed.
