### ISSUE TITLE
komas19.xyz: breakage

### ISSUE THREAD

**Issue by Komas19-new** [uBlockOrigin/uAssets#20019]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://komas19.xyz/games`

### Category

breakage

### Description

uBlock Origin is blocking "cloudflare-app" elements on my website, which is breaking parts of my website, and not showing some.

### Other extensions used

BTRoblox, Dark Reader, Dashlane, Return YouTube Dislikes, RoGold, RoSeal, XML Viewer Plus

This also happens with no extensions except uBO

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

WITH uBO:
![image](https://github.com/uBlockOrigin/uAssets/assets/82937056/9e69cbe5-fdac-4b9a-8b2e-003075dafd1d)
(red rectangles are showing stuff where it should be)

WITHOUT uBO:
![image](https://github.com/uBlockOrigin/uAssets/assets/82937056/d9a41941-7230-49ab-bce4-c0827ad8f4a7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 179390
 cosmetic: 39893
 scriptlet: 18610
 html: 1058
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35805-92, 9m
  ublock-badware: 7193-0, 9m
  ublock-privacy: 589-0, 9m
  ublock-unbreak: 2185-1, 9m
  ublock-quick-fixes: 191-0, 9m
  easylist: 71615-695, 9m
  adguard-spyware-url: 1253-81, 9m
  easyprivacy: 33222-714, 9m
  urlhaus-1: 3873-0, 9m
  curben-phishing: 78707-14, 9m
  plowe-0: 3718-1, 9m
  LegitimateURLShortener: 2495-154, 9m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3543 ms (selfie)
 maxAssetCacheWait: 2342 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
> is breaking parts of my website, and not showing some

Tell us which parts and how to reproduce / see the issue

**Comment by Komas19-new** [comment]
> > is breaking parts of my website, and not showing some
> 
> Tell us which parts and how to reproduce / see the issue

it is deleting the "back to top" arrow at the top right corner of the screen, for example, going down in the [games page](https://www.komas19.xyz/games), shown in this screenshot: 
![image](https://github.com/uBlockOrigin/uAssets/assets/82937056/fa1f3815-4ec0-4dbd-ac8c-ca73f8c7e6ae)

it is also deleting the cookies banner, shown in this screenshot
![image](https://github.com/uBlockOrigin/uAssets/assets/82937056/953b5939-e5d5-4fea-bf04-0215145f888e)


and i know uBlock Origin is deleting "cloudflare-app", because it gets deleted from the html code, shown in these two screenshots:
WITHOUT uBlock Origin:
![image](https://github.com/uBlockOrigin/uAssets/assets/82937056/89482096-1faf-42ef-b751-84da7426824a)

WITH uBlock Origin:
![image](https://github.com/uBlockOrigin/uAssets/assets/82937056/ddeee67f-bc35-4833-b8d3-fbc7c5094678)

**Comment by mapx-** [comment]
@ryanbr 

`@@||komas19.xyz/cdn-cgi/apps/$script,1p`

or

```
@@||komas19.xyz/cdn-cgi/apps/head/$script,1p
@@||komas19.xyz/cdn-cgi/apps/body/$script,1p
```
