### ISSUE TITLE
mtv.fi: detection

### ISSUE THREAD

**Issue by AnttPesonen** [uBlockOrigin/uAssets#20010]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mtv.fi/video/4add020c99b64b11db9e/cha-cha`

### Category

detection

### Description

Detects Ublock (needs a login=

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://gyazo.com/502d88001818f483d3097802add26504
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 104618
 cosmetic: 41888
 scriptlet: 18611
 html: 1063
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 35790-186, now
  ublock-badware: 7188-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2183-1, now
  easylist: 71576-553, now
  easyprivacy: 33219-756, now
  plowe-0: 3718-1, now
  FIN-0: 2213-0, now
  urlhaus-1: 11145-0, now
  ublock-quick-fixes: 195-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 209 ms (selfie)
 maxAssetCacheWait: 63 ms
popupPanel:
 blocked: 4
 network:
  mtv.fi: 1
  bugsnag.com: 1
  videoplaza.tv: 1
  youborafds01.com: 1
```
</details>

**Comment by mapx-** [comment]
@peace2000

**Comment by mapx-** [comment]
@anelder-stripe did you disable ETP (extended tracking protection) in firefox ?

**Comment by mapx-** [comment]
I tested in firefox / chrome, all fine on my end (enabling the regional list  `fi: Adblock List for Finland`)

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by peace2000** [comment]
I fixed this yesterday, few hours before this report was sent. It should work with the current solution. I might still do some fine tuning though.

Longer thread on AG repo: https://github.com/AdguardTeam/AdguardFilters/issues/163249
