### ISSUE TITLE
sattanewss.com detects adblocker

### ISSUE THREAD

**Issue by jsinad** [uBlockOrigin/uAssets#20021]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This website detects the adblocker.

### URL(s) where the issue occurs.

```
https://sattanewss.com/
https://sattanewss.com/insurance-for-the-self-employed-what-freelancers-need-to-know/
```

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 104068
 cosmetic: 39894
 scriptlet: 18684
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 71620-13, 12m
  easyprivacy: 33222-64, 12m
  plowe-0: 3718-1065, 12m
  ublock-badware: 7191-133, 12m
  ublock-filters: 34919-144, 12m
  ublock-privacy: 559-6, 12m
  ublock-quick-fixes: 191-43, 12m
  ublock-unbreak: 2138-30, 12m
  urlhaus-1: 10725-0, 12m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 18 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 996 ms (selfie)
 maxAssetCacheWait: 762 ms
```
</details>

**Comment by mapx-** [comment]
next time provide the real shortener link
