### ISSUE TITLE
[nsfw] xhamster.com: detection

### ISSUE THREAD

**Issue by DarKnight-00** [uBlockOrigin/uAssets#20027]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Pop up warning
Turn off ad blocker for better user experience

### A specific URL where the issue occurs.

`https://xhamster.com/`

### Steps to Reproduce

Go to `https://xhamster.com/`
Accept 18+ warning
Pop up warning appear at the top of page
Tried on laptop n mobile. Same pop up appear

### Expected behavior

No pop up

### Actual behavior

Pop up appear at the top of page

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 112967
 cosmetic: 52842
 scriptlet: 19183
 html: 1059
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 956-0, 2m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2490-0, 2m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds-ublock.txt: 211-0, 2m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 94-0, 2m
  IDN-0: 9660-4, 2m
 default:
  user-filters: 18-0, never
  ublock-filters: 36097-166, 2m
  ublock-badware: 7207-0, 2m
  ublock-privacy: 589-46, 2m
  ublock-unbreak: 2191-0, 2m
  ublock-quick-fixes: 188-0, 2m
  adguard-mobile: 8681-105, 2m
  easylist: 71651-747, 2m
  easyprivacy: 33224-723, 2m
  urlhaus-1: 11010-0, 2m
  plowe-0: 3719-1, 2m
filterset (user): [array of 18 redacted]
userSettings:
 contextMenuEnabled: false
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2664 ms (selfie)
 maxAssetCacheWait: 257 ms
```
</details>

**Comment by mapx-** [comment]
enable `uBlock filters – Annoyances`
