### ISSUE TITLE
imfdb.org: ads

### ISSUE THREAD

**Issue by Bun01294** [uBlockOrigin/uAssets#20026]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.imfdb.org/wiki/Category:Michael_Mann`

### Category

ads

### Description

a video autoplays in the background and persists when scrolling down, i can't remove it with the element picker.

I tried finding a solution but it was only for imdb and tried apply that to the main website but did not work.

i used "||imdb.com/_json/getads/" from a last week known and renamed it to "||imfdb.com/_json/getads/" but the problem is still there.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 117
filterset (summary):
 network: 122778
 cosmetic: 61313
 scriptlet: 20033
 html: 1134
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1672-0, 6m
  RUS-0: 40070-24, 6m
 default:
  user-filters: 29-0, never
  ublock-filters: 35782-135, 7m
  ublock-badware: 7213-0, 7m
  ublock-privacy: 589-6, 7m
  ublock-unbreak: 2186-4, 7m
  ublock-quick-fixes: 188-0, 7m
  easylist: 71651-726, 7m
  easyprivacy: 33224-1021, 7m
  urlhaus-1: 11010-0, 6m
  plowe-0: 3719-8, 6m
filterset (user): [array of 29 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 127 ms (selfie)
 maxAssetCacheWait: 74 ms
popupPanel:
 blocked: 17
 network:
  imfdb.org: 1
  doubleclick.net: 3
  googletagmanager.com: 1
  jwpcdn.com: 1
  jwpltx.com: 11
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
add

`||cdn.jwplayer.com/players/$script,domain=imfdb.org`

@ryanbr

**Comment by Bun01294** [comment]
Nice, thank you. I'll close it now as completed.
