### ISSUE TITLE
insideevs.com: nuisance

### ISSUE THREAD

**Issue by GCustom** [uBlockOrigin/uAssets#20020]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://insideevs.com/news/690407/us-nissan-bev-sales-2023q3/amp/`

### Category

nuisance

### Description

There is the leftovers of a video popup pane at the bottom of pages, sometimes the element picker or zapper can get the frame and the close button, other times it appears as the whole page, and reverts to showing. With UBO off you can select the close button and it goes away. Label with UBO off is "Featured Videos"

### Other extensions used

None for this site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 104992
 cosmetic: 44607
 scriptlet: 22514
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 3988-32, now
  ublock-annoyances: 5525-21, now
 default:
  user-filters: 29-2, never
  easylist: 71615-13, now
  easyprivacy: 33222-75, now
  plowe-0: 3718-1065, now
  ublock-badware: 7191-133, now
  ublock-filters: 34924-146, now
  ublock-privacy: 559-7, now
  ublock-quick-fixes: 192-44, now
  ublock-unbreak: 2138-33, now
  urlhaus-1: 10725-0, now
filterset (user): [array of 29 redacted]
trustedset:
 added: [array of 62 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1513 ms (selfie)
 maxAssetCacheWait: 439 ms
popupPanel:
 blocked: 4
 network:
  ampproject.org: 3
  primis-amp.tech: 1
 extended:
  ##[class^="amp-ad-"]
  ##AMP-AD
  ##amp-ad
```
</details>

**Comment by mapx-** [comment]
test 

`insideevs.com##amp-iframe:has([src^="https://widget.sellwild.com"]):remove()`

**Comment by GCustom** [comment]
Looks like that did the trick, it also automatically added this rule to my installation, I’m guessing you did that?

From: mapx ***@***.***>
Date: Monday, October 9, 2023 at 14:42
To: uBlockOrigin/uAssets ***@***.***>
Cc: GCustom ***@***.***>, Author ***@***.***>
Subject: Re: [uBlockOrigin/uAssets] insideevs.com: nuisance (Issue #20020)

test

insideevs.com##amp-iframe:has([src^="https://widget.sellwild.com"]):remove()

**Comment by GCustom** [comment]
Looks like that did the trick, it also automatically added this rule to my installation, I’m guessing you did that?
