### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by AsianPrince24** [uBlockOrigin/uAssets#20023]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=vciZhSKQfuI&t=194s`

### Category

detection

### Description

Youtube block begin block the video internally

### Other extensions used

I turn off all other extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/138807342/ba6b78e3-266d-4e1d-8e2a-cda5e6bfbefd)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 106
filterset (summary):
 network: 118775
 cosmetic: 50192
 scriptlet: 18871
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 15-0, never
  CHN-0: 25033-133, 1m
  easylist: 71620-22, 1m
  easyprivacy: 33224-77, 1m
  plowe-0: 3718-1067, 1m
  ublock-badware: 7211-133, 1m
  ublock-filters: 34932-159, 1m
  ublock-privacy: 559-6, 1m
  ublock-quick-fixes: 194-46, 1m
  ublock-unbreak: 2139-31, 1m
  urlhaus-1: 11010-0, 1m
filterset (user): [array of 5 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 724 ms (selfie)
 maxAssetCacheWait: 189 ms
popupPanel:
 blocked: 69
 network:
  youtube.com: 59
  doubleclick.net: 3
  google.com: 7
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytd-compact-promoted-video-renderer
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-compact-promoted-video-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ##+js(json-prune, [].playerResponse.adPlacements [].playerRespon…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(json-prune, auxiliaryUi.messageRenderers.enforcementMessag…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?true.*?\}\]\}…
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?ytimg.*?…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\"enabledEn…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_fet_wr_en…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
