### ISSUE TITLE
kidolog.com: nuisance

### ISSUE THREAD

**Issue by xqtp** [uBlockOrigin/uAssets#20022]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [ ] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kidolog.com/en/`

### Category

nuisance

### Description

The following websites also use the same cookie management system.

```
https://www.chakra.com.tr/
https://www.linens.com.tr/
https://www.n11.com/
https://www.tac.com.tr/
```

Please add `||efilli.com^$third-party` to EasyList Cookie or uBO Annoyances.

### Other extensions used

Bitwarden
Simple Translate

### Screenshot(s)

<details>
<summary>Screenshot</summary>

![kidolog](https://github.com/uBlockOrigin/uAssets/assets/103899764/e4340a27-b03e-4d15-ab1c-58c31dcafbae)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 98548
 cosmetic: 137180
 scriptlet: 27642
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  adguard-popup-overlays: 24565-38, now
  adguard-social: 21864-792, now
  adguard-spyware-url: 1253-5, now
  fanboy-cookiemonster: 48507-239, now
  ublock-annoyances: 5526-157, now
 default:
  user-filters: 59-0, never
  TUR-0: 13763-9, now
  easylist: 71620-68, now
  easyprivacy: 33224-128, now
  ublock-badware: 7211-133, now
  ublock-filters: 34930-235, now
  ublock-privacy: 559-83, now
  ublock-quick-fixes: 192-44, now
  ublock-unbreak: 2139-35, now
filterset (user): [array of 68 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 7765 ms (selfie)
 maxAssetCacheWait: 557 ms
popupPanel:
 blocked: 2
 network:
  efilli.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr @Alex-302
