### ISSUE TITLE
mecindo.no: breakage

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#20030]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mecindo.no/marietidsel-hel-100g-no`

### Category

breakage

### Description

The search function on this website doesn't work when uBlock Origin is enabled. I am fairly sure it's the "uBlock filters - Privacy" and "Peter Lowe’s Ad and tracking server list" that is causing the issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 213290
 cosmetic: 189750
 scriptlet: 41639
 html: 1247
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2495-0, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 78384-5714, now
  adguard-spyware-url: 1253-189, now
  block-lan: 54-0, now
  curben-phishing: 78758-14, now
  adguard-social: 21865-724, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 48513-300, now
  fanboy-social: 16240-20, now
  ublock-annoyances: 5486-8, now
  NOR-0: 3613-11, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 15-0, never
  ublock-filters: 35782-180, now
  ublock-badware: 7213-0, now
  ublock-privacy: 589-46, now
  ublock-unbreak: 2185-1, now
  ublock-quick-fixes: 188-0, now
  easylist: 71651-748, now
  easyprivacy: 33224-794, now
  urlhaus-1: 11010-0, now
  plowe-0: 3719-1, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1072 ms (selfie)
 maxAssetCacheWait: 457 ms
popupPanel:
 blocked: 6
 network:
  cookieinformation.com: 3
  google.com: 2
  googletagmanager.com: 1
 extended:
  ###CookieConsent
  ##.pswp__button--share
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
@@||googletagmanager.com/gtm.js$script,domain=mecindo.no
```

@ryanbr
