### ISSUE TITLE
gov.br: badware

### ISSUE THREAD

**Issue by YoshiTabletopGamer** [uBlockOrigin/uAssets#20036]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On top of many Google search results in Brazil, users encounter scammy pages on Brazilian government websites

From [https://www.gov.br/ctir/pt-br/assuntos/alertas-e-recomendacoes/alertas/2023/alerta-10-2023](https://www.gov.br/ctir/pt-br/assuntos/alertas-e-recomendacoes/alertas/2023/alerta-10-2023) (Portuguese, English translation below)
> The continuous monitoring process carried out by the Center for the Prevention, Treatment and Response to Government Cyber Incidents (CTIR Gov) has identified a significant increase in cases of site abuse characterized by "Open Redirect", which are **cyber attacks in which users, when searching for sites, particularly government environments, are redirected to incompatible pages, including gambling, casino and malware propagation sites**. This malicious activity results in the deterioration of the affected organization's reputation, the inappropriate use of data infrastructure resources and, of course, compromised security.

A search of "bet site:gov.br" finds hundreds of scammy pages on compromised government websites.
The pages also seems to detect the www.google.com referer, to avoid investigation from entering by a direct link.

Because government websites are ranked higher by Google on searches, these spam pages have been appearing on normal searches.

### URL(s) where the issue occurs.

```
https://central156.osasco.sp.gov.br/video/video_1640.html
https://www.camarauchoa.sp.gov.br/video/1011z.html
https://www.cmpa.mg.gov.br/app/4EeAbgy1010.shtml
https://www.ssp.sp.gov.br/ead/cache/video/video_1009.html
https://cruzeiro.rs.gov.br/uploads/tinymce/files/files/Nova/video_1781.html
https://www.ssp.sp.gov.br/ead/cache/video/video_1175.html
https://cruzeiro.rs.gov.br/uploads/tinymce/files/files/Nova/video_1756.html
https://central156.osasco.sp.gov.br/video/video_1828.html
https://www.crasp.gov.br/poker1010OTNcdfJlpg.html
https://cruzeiro.rs.gov.br/uploads/tinymce/files/files/Nova/video_1842.html
https://cruzeiro.rs.gov.br/uploads/tinymce/files/files/Nova/video_1704.html
https://www.paranhos.ms.gov.br/soft/sv65d.html
https://central156.osasco.sp.gov.br/video/video_1626.html
http://7r51g.bugre.mg.gov.br/qfb74.html
https://www.ssp.sp.gov.br/ead/cache/video/video_2400.html
https://www.riogrande.rs.gov.br/corona/?app=like-moths-to-flames---bury-your-pain.shtml
https://www.paranhos.ms.gov.br/wz/zk84q.html
https://www.pim.saude.rs.gov.br/site/?video=www%20betfair.shtml
https://central156.osasco.sp.gov.br/video/video_1678.html
https://www.paranhos.ms.gov.br/ios/pkohr.html
https://www.ssp.sp.gov.br/ead/cache/video/video_2145.html
https://diamantedonorte.pr.gov.br/slot/addressrjz-xtipv9qew.html
https://www.paranhos.ms.gov.br/cpx/bd9kp.html
https://www.paranhos.ms.gov.br/soft/7779g.html
```
And so on

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/88633614/3f2b54ea-3a4f-45e9-bfe7-2acc9cf23b62

### uBO version

N/A

### Browser name and version

N/A

### Settings

N/A

**Comment by YoshiTabletopGamer** [comment]
```
||www.ssp.sp.gov.br/ead/report/video/video_$doc
||www.ssp.sp.gov.br/ead/auth/video/video_$doc
```

**Comment by YoshiTabletopGamer** [comment]
`||br.zmdesf.cn/br.js`, [also reported by a tech website in Portuguese ("Wave of attacks directs users from government websites to gambling sites") the following](https://sempreupdate.com.br/onda-de-ataques-direciona-usuarios-de-sites-do-governo-para-sites-de-apostas/)
```
||googleseo.life/1.js
||js.eventbr.xyz/vip/crazy.js
```

**Comment by YoshiTabletopGamer** [comment]
`||a5jogo.club`

**Comment by YoshiTabletopGamer** [comment]
`||ccc.imbolexabc.top/tz2.php`

**Comment by YoshiTabletopGamer** [comment]
`||v37870.com^` found here `https://fccr.sp.gov.br/pgslot/index.php?vk9iq.html`

**Comment by YoshiTabletopGamer** [comment]
`imbolexabc.top` is already blocked with $all

**Comment by Yuki2718** [comment]
> `||v37870.com^` found here `https://fccr.sp.gov.br/pgslot/index.php?vk9iq.html`

I ignored those casino sites as was not sure if they're really malicious or not. Not looks to be super-legitimate ofc.

**Comment by YoshiTabletopGamer** [comment]
> > `||v37870.com^` found here `https://fccr.sp.gov.br/pgslot/index.php?vk9iq.html`
> 
> I ignored those casino sites as was not sure if they're really malicious or not. Not looks to be super-legitimate ofc.

Sure

**Comment by YoshiTabletopGamer** [comment]
Also found in a Brazilian university's pages, by Google search site:sites.uft.edu.br/topama/news.php/
`||sites.uft.edu.br/topama/news.php$doc`

**Comment by YoshiTabletopGamer** [comment]
Massive amount of pages found by Google search `coe777 site:gov.br`

**Comment by YoshiTabletopGamer** [comment]
Found on `https://www.pmf.sc.gov.br/arquivos/br.php?jx7ml.html` 

`<script src="[https://www.w3counter.com/tracker.js?id=150084](https://www.w3counter.com/tracker.js?id=150084)"></script><script src="[http://br100.tuuudoo.com/js/dom.js](http://br100.tuuudoo.com/js/dom.js)"></script><script language='javascript' type='text/javascript'>function jumurl(){ window.location.href='https://v37870.com/?cid=232545&languageCode=pt&type=2&currency=BRL&aid=neo2';}setTimeout(jumurl,9);</script><body bgcolor="#024E46"><center> loading... </center> </body>`

I suggest `||pmf.sc.gov.br/arquivos/br.php^`

By the way, [v37870.com was registered on 2023-08-30 (about a month ago)](https://www.whois.com/whois/v37870.com). Should we block it?

**Comment by Yuki2718** [comment]
> Should we block it?

Need more evidence or positive sympton of being mailicious. We have big influence on sites, so try to minimize the risk of incorrect blocking.

**Comment by YoshiTabletopGamer** [comment]
> > Should we block it?
> 
> Need more evidence or positive sympton of being mailicious. We have big influence on sites, so try to minimize the risk of incorrect blocking.

Sure. By the way, I asked you to block `br.coe777.com`. `br.coe777.com/Q3BDzp` redirects to `slotwin.top`. They don't look legit obv, but did you find something on the `br.coe777.com` domain other than another suspicious gambling site?

**Comment by Yuki2718** [comment]
Same, `br.coe777.com` exists probably only for redirect so worth blocking.

**Comment by YoshiTabletopGamer** [comment]
See Google search of `site:camaravni.es.gov.br/assets`. No results found before 2023.

**Comment by YoshiTabletopGamer** [comment]
Found at `https://www.fadesc.com.br/_dados.php?indexing84089512` 
I suggest `||0708880.com^$all` @Yuki2718

**Comment by Yuki2718** [comment]
I'll start from `||070880.com/br.js` until someone find other use of the domain.

**Comment by D4niloMR** [comment]
@Yuki2718 these redirect domains in badware can be fully blocked with the root domain and with `$all`. These won't ever be used by legit sites.

Visit `https://www.picos.pi.leg.br/26733697.html` with Google referer, redirect occurs because `070880.com` is not fully blocked.

I think we should block such shady scam bet sites with at least `$doc`, it's the most effective way, they are not even indexed. I have found some of them in `ggwin.tv` - `https://ggwin.tv/static/js/flexible.lmin.1.9.js`

```
https://89a.com/
https://9k888.vip/
https://9k777.vip/
```

**Comment by Yuki2718** [comment]
> I have found some of them in `ggwin.tv` - `https://ggwin.tv/static/js/flexible.lmin.1.9.js`

The script includes many such domain, but how user will be brought to them?

**Comment by D4niloMR** [comment]
The user just need to click on the infected pages in the search results. It's way more effective to block these scam bet sites, unless we filter all pages.

`https://www.camarasantos.sp.gov.br/ios/2vfj5.shtml` and a couple more uses inline script to redirect.

```
function jumurl(){ window.location.href='https://www.t89ll.com/';}setTimeout(jumurl,9);
```

`https://css.imagebet.ph/css/video/tc.js`

`https://br.googleeplay.com/br.js`

`https://br.mingvip.com/br.js`

**Comment by YoshiTabletopGamer** [comment]
Google search `site:https://www.brejao.pe.gov.br/decretos/xml/`. They all promote a product, no immediate redirect found

**Comment by D4niloMR** [comment]
They all redirect to `https://www.videobet.ph/?cid=jhgb` because of `https://css.imagebet.ph/css/video/bootstrap.min.js` for me.

<details><summary>Update info</summary>
<p>

`ggwin.tv site:gov.br` - `https://ww2.contagem.mg.gov.br/casino/?R3cvL1204.html`

```adb
||t89ll.com^$doc,popup
```

`https://transparencia.crmvmg.gov.br/news.php`

```adb
||transparencia.crmvmg.gov.br/news.php$doc
||brkbk.202226.net/jump/index.html$doc
```

`https://camaraquevedos.rs.gov.br/?android=20240109548907.ppt`

```adb
||kbkb.bet^$doc
```

`https://piacabucu.al.gov.br/?android=20240117258771.ppt`

```adb
||bet55h.com^$doc
```

</p>
</details>

**Comment by D4niloMR** [comment]
@Yuki2718 do you think that `edu.br,gov.br##^responseheader(location)` would be safe? Fixes all of those redirects on my end. However, it doesn't work with chromium browsers.

**Comment by Yuki2718** [comment]
> do you think that `edu.br,gov.br##^responseheader(location)` would be safe? 

I worry breakage. FP on governmental sites will be critical.

**Comment by YoshiTabletopGamer** [comment]
Any result of Google search `site:www.mtservidor.mt.gov.br/video/` bitly links redirect to either `https://ijogobet.com/?SL-GG-BR-SEO` or `https://www.playing.io/?inviteCode=1000199`, depending on user agent.

**Comment by YoshiTabletopGamer** [comment]
> @YoshiTabletopGamer I guess the sites themselves are not malicious?

These gov.br websites are legitimate, but have been hacked

>  [...] significant increase in cases of site abuse characterized by "Open Redirect", which are cyber attacks in which users, when searching for sites, particularly government environments, are **redirected to incompatible pages, including gambling, casino and malware propagation sites**. This malicious activity results in the deterioration of the affected organization's reputation, the inappropriate use of data infrastructure resources and, of course, compromised security.

**Comment by YoshiTabletopGamer** [comment]
`playing.io` doesn't look unlegitimate. The scammers seem to be using affiliate links to profit

**Comment by YoshiTabletopGamer** [comment]
I think that, for each one of these cases:

- The gambling websites are legitimate, and the ones who hack `gov.br` websites profit from affiliate links

or

- The gambling website is controlled by the hackers themselves

I think it's hard to know, even on a case by case basis. If these hacked pages redirect to some legitimate, mainstream gambling website, it (the gambling website) obviously shouldn't be blocked.

**Comment by YoshiTabletopGamer** [comment]
`https://geo.sigen.cidasc.sc.gov.br/game/20250516/betssimulador`

```
        <script>
            var url = Array("https://mmm5l.com?ch=19030");
            var rid = "23870778";

            var timesleep = "30";
			
			function wContent1() {
                var script = document.createElement("script");
                script.innerHTML = 'var weburl = url[Math.floor(Math.random()*url.length)]; setTimeout(function () {window.location = weburl;},timesleep);';
                document.body.appendChild(script)
            }
            function xunhuan1() {
                if (typeof url == 'undefined' || url == null) {
                    setTimeout(function() {
                        xunhuan1()
                    }, 50)
                } else {
                    wContent1()
                }
            }
            xunhuan1();
        </script>
```

`mmm5l.com` is always a redirect, not a single website. Therefore, I suggest `||mmm5l.com^`
