### ISSUE TITLE
polsatboxgo.pl: detection

### ISSUE THREAD

**Issue by jakubstaszak-com** [uBlockOrigin/uAssets#20034]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://polsatboxgo.pl/wideo/programy/love-island-wyspa-milosci/5027502/sezon-8/5039191/love-island-wyspa-milosci-8-odcinek-30/2f734168ec3fd7920d1e3d3a5a9999de/ogladaj?next=https%253A%252F%252Fpolsatboxgo.pl%252Fwideo%252Fprogramy%252Flove-island-wyspa-milosci%252F5027502%252Fsezon-8%252F5039191%252Flove-island-wyspa-milosci-8-odcinek-30%252F2f734168ec3fd7920d1e3d3a5a9999de`

### Category

detection

### Description

detection

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-10-10 at 17-05-01 Love Island  Wyspa miłości 8 - Odcinek 30 - Polsatboxgo pl](https://github.com/uBlockOrigin/uAssets/assets/42867129/12948c7d-8ba0-405b-b7e5-6ed9e678a9af)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105700
 cosmetic: 47514
 scriptlet: 18762
 html: 1069
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 194-0, now
 default:
  user-filters: 49-0, never
  ublock-filters: 35786-243, now
  ublock-badware: 7213-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2185-0, now
  easylist: 71655-569, now
  easyprivacy: 33224-756, now
  urlhaus-1: 10910-0, now
  plowe-0: 3719-1, now
  POL-0: 7996-27, now
  POL-2: 1279-12, now
filterset (user): [array of 49 redacted]
trustedset:
 added: [array of 49 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 607 ms (selfie)
 maxAssetCacheWait: 111 ms
popupPanel:
 blocked: 5
 network:
  gemius.pl: 3
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
 extended:
  ##.eYbZiA.hvMPsy.nteuc9-15.nteuc9-13
```
</details>

**Comment by jakubstaszak-com** [comment]
I could provide  temporaryn access if need be.

Quick workaround is to disable adblock on checking stage and enable it right when the video starts. No ads during the show and no additional checks.

**Comment by mapx-** [comment]
@jakubstaszak-com ok, send the credentials of your account here: `axis,trivia@gmail.com`

**Comment by krystian3w** [comment]
Works fine for me, maybe due 2 months trial.

**Comment by jakubstaszak-com** [comment]
> Works fine for me, maybe due 2 months trial: https://pomoc.polsatgo.pl/pytanie/faq-zakonczenie-dzialalnosci-polsat-go-i-promocja-na-pakiet-polsat-box-go-start/
> 
> ![obraz](https://user-images.githubusercontent.com/35370833/274031414-72eaca63-5f4d-44e6-87b6-d3a4cc80ecb2.png)
> 
> I can test on sister birthday without new account.

Mine is full 1 year account. So far, uBlock hasn't been detected for over a month. First time today.

**Comment by mapx-** [comment]
You have custom filters like:
`##.eYbZiA.hvMPsy.nteuc9-15.nteuc9-13`

You should disable "my filters", disable also any other addon and test again

**Comment by jakubstaszak-com** [comment]
> You have custom filters like: `##.eYbZiA.hvMPsy.nteuc9-15.nteuc9-13`
> 
> You should disable "my filters", disable also any other addon and test again

Hence "i didn't answer truthfully" but now that I've checked with custom filters removed, the issue still persists.

**Comment by mapx-** [comment]
try whitelisting 

`imasdk.googleapis.com`

**Comment by jakubstaszak-com** [comment]
Do I do that by adding the URL to trusted sites? This hasn't helped.
<img width="680" alt="Zrzut ekranu 2023-10-10 222532" src="https://github.com/uBlockOrigin/uAssets/assets/42867129/3e380e17-501f-4721-a441-9d0341a9d4bd">

**Comment by jakubstaszak-com** [comment]
> try whitelisting
> 
> `imasdk.googleapis.com`
> 
> I didn't receive your credentials. Did you change your mind ?

Just sent the creds to your email. Since our colleagues offered to verify, I thought it may not be necessary.

**Comment by mapx-** [comment]
remove what you added above

add as custom filter
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=polsatboxgo.pl`

**Comment by mapx-** [comment]
Tested FF / chrome , it's ok using that filter

**Comment by jakubstaszak-com** [comment]
> remove what you added above
> 
> add as custom filter `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=polsatboxgo.pl`

Yes, it helped. Thank you!
