### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Soppage** [uBlockOrigin/uAssets#20038]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=eYpy0eTn26Q`

### Category

detection

### Description

Youtube detecting and not playing video, while it worked 1 hour ago/earlier in the day.

### Other extensions used

I am using youtube enhancer and uBO (enhancer with no adblock) to try and get around the adblock detector

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 104309
 cosmetic: 39919
 scriptlet: 18648
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71663-13, 1m
  easyprivacy: 33224-64, 1m
  plowe-0: 3719-1065, 1m
  ublock-badware: 7211-133, 1m
  ublock-filters: 34908-144, 1m
  ublock-privacy: 559-6, 1m
  ublock-quick-fixes: 195-56, 1m
  ublock-unbreak: 2139-30, 1m
  urlhaus-1: 10910-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 517 ms
 maxAssetCacheWait: 135 ms
popupPanel:
 blocked: 15
 network:
  youtube.com: 10
  doubleclick.net: 3
  google.ca: 1
  google.com: 1
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?true.*?\}\]\}…
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?ytimg.*?…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\"enabledEn…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_fet_wr, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
