### ISSUE TITLE
login-ext.identity.oraclecloud.com: breakage

### ISSUE THREAD

**Issue by bimg21** [uBlockOrigin/uAssets#20048]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://login-ext.identity.oraclecloud.com/sso/v1/user/login`

### Category

breakage

### Description

Trying to log in to a Virtualbox forum leads to `https://login.oracle.com/mysso/signon.jsp` which leads to `https://login-ext.identity.oraclecloud.com/sso/v1/user/login` which displays an empty page. Allowing 1-st and 3-rd party everything doesn't help.

### Other extensions used

NoScript with JS allowed.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 190759
 cosmetic: 191717
 scriptlet: 45601
 html: 1272
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72989-72989, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93797-61226, now
  https://secure.fanboy.co.nz/fanboy-antifonts.txt: 58-0, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 78450-6949, 2m
  adguard-mobile: 8686-97, 2m
  adguard-spyware-url: 1258-81, 2m
  block-lan: 54-0, 2m
  adguard-social: 21875-1547, 2m
  fanboy-thirdparty_social: 68-1, 2m
  fanboy-social: 16239-11850, 1m
  ublock-annoyances: 5528-337, 1m
  [18 lists not shown]: [too many]
 default:
  user-filters: 314-81, never
  ublock-filters: 35813-740, 2m
  ublock-badware: 7270-0, 2m
  ublock-privacy: 589-1, 2m
  ublock-unbreak: 2187-8, 2m
  easylist: 71684-16696, 2m
  easyprivacy: 33228-184, 2m
  urlhaus-1: 12110-0, 2m
  ublock-quick-fixes: 210-0, 1m
filterset (user): [array of 374 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 21 redacted]
hostRuleset:
 added: [array of 179 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11177 ms
 maxAssetCacheWait: 2823 ms
popupPanel:
 blocked: 0
 no-remote-fonts: true
```
</details>

**Comment by gorhill** [comment]
Try with default uBO settings in a new browser profile, you have too many customizations, first step is to narrow down.

**Comment by mapx-** [comment]
No issue on my end logging in (and using an oracle account) to `https://forums.virtualbox.org/index.php`

**Comment by gorhill** [comment]
> No issue on my end logging in

Closing as invalid then, given the amount of customizations, and the fact that OP checked _I did not answer truthfully to ALL the above checkpoints_.
