### ISSUE TITLE
aarhustech.dk: breakage

### ISSUE THREAD

**Issue by jolesh** [uBlockOrigin/uAssets#20045]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aarhustech.dk/`

### Category

breakage

### Description

Blocks the popup to change cookie settings to watch video. This pop-up is only needed when first declining all cookies.

### Other extensions used

Used others, but tested it and ublock is the one breaking it

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 117
filterset (summary):
 network: 105527
 cosmetic: 39922
 scriptlet: 18564
 html: 1063
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35798-107, now
  ublock-badware: 7244-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2187-1, now
  ublock-quick-fixes: 195-0, now
  easylist: 71670-695, now
  easyprivacy: 33227-716, now
  urlhaus-1: 12110-0, now
  plowe-0: 3722-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 392 ms (selfie)
 maxAssetCacheWait: 180 ms
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 1
  youtube-nocookie.com: 2
 extended:
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=aarhustech.dk`

@ryanbr
