### ISSUE TITLE
dualshockers.com: detection

### ISSUE THREAD

**Issue by Grissallia** [uBlockOrigin/uAssets#20044]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dualshockers.com/epic-games-store-steam-competitor-ambitions-as-good-as-dead/`

### Category

detection

### Description

Per #20032 and #20039 I'm guessing that Admiral have made some kind of change to their systems as this is the third time I've encountered them today, and the second time I've reported them. This time for DualShockers.

### Other extensions used

1Password, GiftHero, Honey, Dark Reader, Google Translate, Save Image as Type, Fanatical Assistant

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot 2023-10-11 234231](https://github.com/uBlockOrigin/uAssets/assets/792439/d69db4e6-d96f-4d63-9f51-6450ad510325)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 105529
 cosmetic: 39919
 scriptlet: 18652
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71663-13, now
  easyprivacy: 33226-64, now
  plowe-0: 3722-1067, now
  ublock-badware: 7229-133, now
  ublock-filters: 34913-144, now
  ublock-privacy: 559-6, now
  ublock-quick-fixes: 195-58, now
  ublock-unbreak: 2140-31, now
  urlhaus-1: 12110-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 262 ms (selfie)
 maxAssetCacheWait: 46 ms
popupPanel:
 blocked: 21
 network:
  dualshockers.com: 2
  ad.gt: 1
  adlightning.com: 1
  adsafeprotected.com: 2
  adsninja.ca: 2
  advertising.com: 1
  amazon-adsystem.com: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  googletagservices.com: 1
  imasdk.googleapis.com: 1
  merequartz.com: 2
  tru.am: 1
  unblockia.com: 1
  unpkg.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adsninja-ad-zone
  ##.ad-current
  ##.ad-zone-container
  ##.ad-zone:not(.textads)
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.ad-zone
```
</details>

**Comment by stephenhawk8054** [comment]
Looking at the interface, I think they are the same system. You can report them at this thread in the future if you encounter same looking sites.
