### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Tokarin1** [uBlockOrigin/uAssets#20049]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=jyYqys7JSr8`

### Category

detection

### Description

k;j

### Other extensions used

kl

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 105579
 cosmetic: 39922
 scriptlet: 18654
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 71684-13, now
  easyprivacy: 33228-64, now
  plowe-0: 3724-1067, now
  ublock-badware: 7266-134, now
  ublock-filters: 34930-144, now
  ublock-privacy: 559-6, now
  ublock-quick-fixes: 195-79, 11m
  ublock-unbreak: 2140-31, now
  urlhaus-1: 12110-0, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 141 ms (selfie)
 maxAssetCacheWait: 78 ms
popupPanel:
 blocked: 40
 network:
  youtube.com: 18
  doubleclick.net: 4
  google.com: 18
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###container > .yt-playability-error-supported-renderers.style-s…
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-replace-fetch-response, /(youtubei.*?)"adSlots.*?\…
  ##+js(trusted-replace-fetch-response, /(youtubei.*?)"adPlacement…
  ##+js(trusted-replace-fetch-response, /(youtubei.*?)"playerAds.*…
  #@#+js(trusted-replace-fetch-response, /\"adSlots.*?true.*?\}\]\…
  #@#+js(trusted-replace-fetch-response, /\"adPlacements.*?true.*?…
  #@#+js(trusted-replace-fetch-response, /\"playerAds.*?true.*?\}\…
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
