### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by canahmet** [uBlockOrigin/uAssets#20043]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch`

### Category

detection

### Description

website detect ublock origin

### Other extensions used

google translate extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 107192
 cosmetic: 50408
 scriptlet: 20237
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13763-9, now
  easylist: 71663-33, now
  easyprivacy: 33226-69, now
  plowe-0: 3722-1068, now
  ublock-badware: 7222-133, now
  ublock-filters: 34910-151, now
  ublock-privacy: 559-6, now
  ublock-quick-fixes: 197-58, now
  ublock-unbreak: 2140-32, now
  urlhaus-1: 12135-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2017 ms (selfie)
 maxAssetCacheWait: 330 ms
popupPanel:
 blocked: 55
 network:
  youtube.com: 40
  doubleclick.net: 5
  google.com: 9
  google.com.tr: 1
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  #@#.video-ads
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?true.*?\}\]\}…
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?ytimg.*?…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?\"enabledEn…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_fet_wr, f…
  #@#+js(json-prune-fetch-response, [].playerResponse.adPlacements…
  #@#+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\…
  #@#+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,…
  #@#+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/,…
```
</details>

**Comment by mapx-** [comment]
read / report here: https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by stephenhawk8054** [comment]
> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
