### ISSUE TITLE
democracydocket.com: nuisance

### ISSUE THREAD

**Issue by awebeer256** [uBlockOrigin/uAssets#20041]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There's a bottom bar advertising the site's merch store.

### URL(s) where the issue occurs.

`https://www.democracydocket.com/news-alerts/after-unprecedented-defiance-alabama-has-a-fair-congressional-map-for-2024/`

### uBO version

1.52.2

### Browser name and version

Firefox 118.0.1

### Settings

- Enable all of AdGuard – Annoyances
- Enable all of EasyList – Annoyances
- Enable uBlock filters – Annoyances

### Notes

Proposed fix: `democracydocket.com###alert-bar:has(a[href='https://store.democracydocket.com/'])`. I don't want to just hide all `#alert-bar` because they could put something else in the bar that doesn't count as a nuisance.

**Comment by stephenhawk8054** [comment]
@ryanbr @Alex-302
