### ISSUE TITLE
androidpolice.com: detection

### ISSUE THREAD

**Issue by ryanmonson** [uBlockOrigin/uAssets#20059]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.androidpolice.com/`

### Category

detection

### Description

Website uses Admiral to prevent adblockers

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-10-12 093132](https://github.com/uBlockOrigin/uAssets/assets/10967368/cb463c51-55c8-4853-a715-ea52f139ee20)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104837
 cosmetic: 39929
 scriptlet: 18660
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71685-11, now
  easyprivacy: 33231-64, now
  plowe-0: 3726-1068, now
  ublock-badware: 7272-134, now
  ublock-filters: 34919-144, now
  ublock-privacy: 559-6, now
  ublock-quick-fixes: 216-82, 1h.38m
  ublock-unbreak: 2142-31, now
  urlhaus-1: 11360-0, 1h.38m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 687 ms (selfie)
 maxAssetCacheWait: 341 ms
popupPanel:
 blocked: 29
 network:
  androidpolice.com: 2
  ad.gt: 2
  adlightning.com: 1
  adsafeprotected.com: 2
  adsninja.ca: 3
  advertising.com: 1
  amazon-adsystem.com: 1
  d15kdpgjg3unno.cloudfront.net: 1
  ebxcdn.com: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  googletagservices.com: 1
  imasdk.googleapis.com: 2
  marfeelrev.com: 1
  merequartz.com: 2
  parsely.com: 1
  scorecardresearch.com: 1
  unblockia.com: 1
  unpkg.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.adsninja-ad-zone
  ##.ad-current
  ##.ad-zone-container
  ##.ad-zone:not(.textads)
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#.ad-zone
```
</details>

**Comment by Malgotra** [comment]
![Screenshot_20231110-222305](https://github.com/uBlockOrigin/uAssets/assets/122884037/3407d9b6-8e48-4bad-b33d-746640b69aae)

@stephenhawk8054 while scrolling getting this nuisance.

uBlock Origin: 1.53.0
Firefox Mobile: 121
filterset (summary):
 network: 133971
 cosmetic: 170288
 scriptlet: 41681
 html: 1290
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79619-6271, 9m
  easylist-annoyances: 4170-94, 9m
  easylist-chat: 150-0, 9m
  fanboy-cookiemonster: 48828-289, 9m
  ublock-cookies-easylist: 532-0, 9m
  easylist-newsletters: 6635-13, 9m
  easylist-notifications: 2873-4, 9m
  fanboy-social: 16190-7, 9m
  ublock-annoyances: 5788-568, 9m
  IND-0: 12778-2, 9m
 default:
  user-filters: 0-0, never
  ublock-filters: 36431-185, 9m
  ublock-badware: 7426-5, 9m
  ublock-privacy: 657-0, 9m
  ublock-unbreak: 2186-1, 9m
  ublock-quick-fixes: 165-6, 9m
  adguard-mobile: 8850-111, 10m
  easylist: 75167-782, 8m
  easyprivacy: 32855-823, 8m
  urlhaus-1: 11695-0, 8m
  plowe-0: 3722-1, 8m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 12751 ms
 maxAssetCacheWait: 46 ms

**Comment by Malgotra** [comment]
Please also fix https://www.xda-developers.com have same nuisance.
[Screenshot_20231110-224440](https://github.com/uBlockOrigin/uAssets/assets/122884037/c768ce16-10e1-4cc6-b8c4-39099bbe9081)

**Comment by mapx-** [comment]
Test

```
androidpolice.com##+js(cookie-remover, articlesRead)
androidpolice.com##+js(rpnt, script, /.*console.log\(\'viewType.*/, setInterval(() => {document.cookie = 'articlesRead' +'=; Path=/; Expires=Thu\, 01 Jan 1970 00:00:01 GMT;';}\, "50");, stay, 1)
```

**Comment by Malgotra** [comment]
Yes it works.

**Comment by superlex** [comment]
@mapx- 
the rule
`##+js(rpnt, script, /.*console.log\(\'viewType.*/, setInterval(() => {document.cookie = 'articlesRead' +'=; Path=/; Expires=Thu\, 01 Jan 1970 00:00:01 GMT;';}\, "50");, stay, 1)`
works, but page loading is very slow and I get this message:

https://github.com/uBlockOrigin/uAssets/assets/1375223/01b4b35f-22c1-4f89-abc7-6451a4f899e8

Firefox cleaned profile,
uBO configuration:

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 107438
 cosmetic: 51775
 scriptlet: 22574
 html: 1288
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5771-13, 6m
 default:
  user-filters: 0-0, never
  ublock-filters: 36150-151, 6m
  ublock-badware: 7447-5, 6m
  ublock-privacy: 662-0, 6m
  ublock-unbreak: 2195-1, 6m
  ublock-quick-fixes: 173-7, 6m
  easylist: 75229-709, 6m
  easyprivacy: 32866-725, 6m
  urlhaus-1: 10825-0, 6m
  plowe-0: 3723-1, 6m
  ITA-0: 9818-21, 6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 326 ms (selfie)
 maxAssetCacheWait: 180 ms
```
</details>

Let me know if you need any additional information.

**Comment by superlex** [comment]
Try

`##+js(rpnt, script, /console.log\(\'viewType\: direct')\;/, setInterval(() => {document.cookie = 'articlesRead' +'=; Path=/; Expires=Thu\, 01 Jan 1970 00:00:01 GMT;';}\, "50");, stay, 1)`

**Comment by mapx-** [comment]
test again after updating

**Comment by superlex** [comment]
No issues here 😊
Thank you!

**Comment by gorhill** [comment]
Why not just:

    androidpolice.com###article-limit-container

**Comment by mapx-** [comment]
disabling it for `rpnt` injecting abuse, maybe other filters will be added or not.

**Comment by superlex** [comment]
Oh ok, thanks anyway!

**Comment by superlex** [comment]
@mapx- 

It looks like the rule
`##+js(trusted-prune-inbound-object, JSON.stringify, 1, index, max excludeIds)`
causes the web address to be wrong.
No problem removing the rule.

[Example](https://www.androidpolice.com/youtube-premium-ai-app-features-new/):
Ok -> https://github.com/uBlockOrigin/uAssets/assets/1375223/2785504a-85b0-49d1-8c5e-50cc25db8a49
Not Ok -> https://github.com/uBlockOrigin/uAssets/assets/1375223/71567250-f867-4e9f-92ec-74ee71923370

To check, scroll about 2/3 articles.

**Comment by gorhill** [comment]
@superlex In the dev build (and next stable release) of uBO, this should work:

    androidpolice.com##+js(remove-cookie, articlesRead, when, scroll keydown)

**Comment by superlex** [comment]
@gorhill 
Awesome!
Just tried
```
androidpolice.com#@#+js(trusted-prune-inbound-object, JSON.stringify, 1, index, max excludeIds)
androidpolice.com#@#+js(set, maxUnauthenicatedArticleViews, null)
androidpolice.com##+js(remove-cookie, articlesRead, when, scroll keydown)
androidpolice.com##+js(set, articleFetchMaximum, 20)
```
with uBO 1.53.5rc11, no problems!
Thank you very much!

**Comment by gorhill** [comment]
I didn't need the other filters to scroll down fine, are they really needed?

**Comment by superlex** [comment]
Nope, only the 3th is needed. 1 and 2 are to not to use current filters, 4 is to increase the maximum number of items in sequence (I used it for testing).

**Comment by superlex** [comment]
Hello guys, there is another detection.

URL:
`https://www.androidpolice.com/how-to-find-new-old-spotify-wrapped/`

Related AG issue and description:
https://github.com/AdguardTeam/AdguardFilters/issues/167581
https://github.com/AdguardTeam/AdguardFilters/issues/167581#issuecomment-1841098961

AG fix:
https://github.com/AdguardTeam/AdguardFilters/commit/0251ad089d27bb4c94197ef71b3e574416b6bb8c

My uBO setting:
<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 103775
 cosmetic: 44063
 scriptlet: 19279
 html: 1128
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36818-121, 3m
  ublock-badware: 7544-11, 3m
  ublock-privacy: 921-4, 3m
  ublock-unbreak: 2204-1, 3m
  ublock-quick-fixes: 303-67, 3m
  easylist: 75847-701, 3m
  easyprivacy: 33035-791, 3m
  urlhaus-1: 9640-0, 3m
  plowe-0: 3779-1, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2191 ms
 maxAssetCacheWait: 6 ms
popupPanel:
 blocked: 34
 network:
  androidpolice.com: 2
  ad.gt: 2
  adlightning.com: 2
  adsninja.ca: 4
  advoncommerce.com: 2
  amazon-adsystem.com: 1
  d15kdpgjg3unno.cloudfront.net: 2
  ebxcdn.com: 2
  google-analytics.com: 1
  google.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  googletagservices.com: 1
  imasdk.googleapis.com: 2
  kueezrtb.com: 2
  marfeelrev.com: 1
  optmn.cloud: 2
  scorecardresearch.com: 1
  skimresources.com: 2
  unpkg.com: 1
 extended:
  ##.adsninja-ad-zone
  ##.ad-current
  ##.ad-zone-container
  ##.ad-zone:not(.textads)
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(remove-cookie, /articlesRead|previousPage/)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

Let me know if you prefer I open a new issue or you need more details.

**Comment by gorhill** [comment]
The filter in _uBlock filters – Annoyances_ still work for me.

**Comment by Omega-6** [comment]
@gorhill it's about the thumbnail

**Comment by gorhill** [comment]
If you mean the video at the top, it shows properly on my side with _uBlock filters -- Annoyances_. Will need more generous with details about what exactly is not working. The issue here is about "detection", I don't see it.

**Comment by superlex** [comment]
Yep, it's a different detection.
How it is (with uBO default setting):
https://camo.githubusercontent.com/ea0871755fb9ec0c39d90d91e2ab6c6f0d15a7a5a77792a7ec8965f7dbe07b08/68747470733a2f2f63646e2e616467756172642e696e666f2f736974657265706f7274732f706b79737971616b3373676f77387777776b6f67676b77306f633838676330687073646c7837316d39632e706e673f6e633d31

**Comment by Omega-6** [comment]
Is it related to cookie notice (Admiral)?

Could you please test with a EU IP address?

**Comment by Omega-6** [comment]
I encountered this in Brave

```
@@||androidpolice.com^$ghide
@@||cdn.adsninja.ca/adsninja_client$script,css,domain=androidpolice.com
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=androidpolice.com
@@||c.amazon-adsystem.com/aax2/apstag.js$domain=androidpolice.com
```

**Comment by huyszn** [comment]
`https://www.androidpolice.com/pixel-8-screen-protector-detector/`

I am getting "Something went wrong. Please disable your blocker on AndroidPolice.com" admiral detection message. I get the detection on chrome but not on firefox.

**Comment by huyszn** [comment]
I still get the message when I updated the filters. I don't get the message anymore when I use `androidpolice.com##+js(aeld, error, blocker)`

**Comment by superlex** [comment]
@ghajini 

Thank you!
Anyway I guess it's better to check all the group
`androidpolice.com,makeuseof.com,movieweb.com,xda-developers.com,thegamer.com,cbr.com,gamerant.com,screenrant.com,howtogeek.com`

**Comment by superlex** [comment]
> did you reproduce on all of them ? as it rarely occurs

Nope, but I cannot reproduce it on androidpolice either, in fact my suggestion was to check them.

**Comment by superlex** [comment]
Ok, thank you!
