### ISSUE TITLE
player.pl: breakage

### ISSUE THREAD

**Issue by andrzej928** [uBlockOrigin/uAssets#20050]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114/odcinek-6,S27E06,259433`

### Category

breakage

### Description

i see only loading screen...

### Other extensions used

7TV

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 107635
 cosmetic: 69108
 scriptlet: 19038
 html: 1313
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PPB.txt: 22832-47, now
 default:
  user-filters: 6-1, never
  ublock-filters: 35816-172, now
  ublock-badware: 7270-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2187-1, now
  ublock-quick-fixes: 213-0, now
  easylist: 71684-712, now
  easyprivacy: 33228-718, now
  urlhaus-1: 12110-0, 33m
  plowe-0: 3724-1, now
  POL-0: 7996-27, 32m
  POL-2: 1279-12, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 829 ms (selfie)
 maxAssetCacheWait: 137 ms
popupPanel:
 blocked: 43
 network:
  player.pl: 12
  adocean.pl: 3
  browser-intake-datadoghq.eu: 1
  doubleclick.net: 1
  gemius.pl: 8
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  imrworldwide.com: 1
  ipresso.pl: 11
  litix.io: 2
  newrelic.com: 1
 extended:
  ##html:not([style*="overflow:hidden" i]):not([style*="overflow: …
  ##.reklama-top
  ##.ad
  ##.adv_container
  ##.adsense
  ##.linkSponsorowany
  ##.ads
  ##.adocean
  ##.advert__container
  ##.video-ads-container
  ##div.adsbygoogle.prebid.adocean.ado.ad.ads.advert.banner.reklam…
  #@#.advert
  #@#.reklama
  ##+js(remove-attr, style, body[style*="overflow"], stay)
  ##+js(json-prune, movie.advertising.ad_server playlist.movie.adv…
```
</details>

**Comment by mapx-** [comment]
Disable the filters in "my filters" if any for this site.
Disable any other extension / addon and test again.

**Comment by andrzej928** [comment]
problem is
![Screenshot_5](https://github.com/uBlockOrigin/uAssets/assets/1771441/250ba581-233b-4888-b171-5059813e3bf7)

**Comment by mapx-** [comment]
open the uBO logger, refresh the page on player.pl, reproduce again the issue, go back in the logger and see what filters from that list are enabled on page (you have to click one by one the blocked items in order to see the list it comes from)

**Comment by mapx-** [comment]
@Naala098 do your test using only the default lists / settings in uBO and disabling all other extensions

**Comment by Naala098** [comment]
I'm not an advanced user, I don't know how to do it, it happened suddenly today on all TVN.pl websites, which owns player.pl and discoverychanell, 
I'm sorry I'm useless, maybe just show me what to do

**Comment by mapx-** [comment]
- reset to default settings => https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings
- then disable any other addon (firefox) / extension (chromium browsers) / builtin blocker (brave, vivaldi etc) / tracking protection (firefox, edge etc)

**Comment by Naala098** [comment]
I don't have any extensions in firefox except ublock and IDM, I restarted it to the default settings as shown in the manual
it still detects blocking, but when I turn off ublock, an advertisement appears and then you can watch the movie, so it is a reaction to ublock

**Comment by Naala098** [comment]
enter your email, remember to use a VPN for the Polish region

**Comment by Naala098** [comment]
> axis.trivia@gmail.com

done

**Comment by mapx-** [comment]
Test on your side too

`@@||player.pl^$shide`

go into uBO dashboard, "my filters" tab, add the filer, click "apply changes"

**Comment by wu474** [comment]
> Test on your side too
> 
> `@@||player.pl^$shide`
> 
> go into uBO dashboard, "my filters" tab, add the filter, click "apply changes"

Hi, unfortunately this solution does not work. After adding @@||player.pl^$shide, the player continues to detect adblock and shows a message to disable it.

**Comment by mapx-** [comment]
it worked, I fixed it again (you didn't update your lists) and it seems "they" fighted back again
