### ISSUE TITLE
YouTube Ads

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uAssets#20055]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

YouTube is now complaining when it sees adblockers being used.

### URL(s) where the issue occurs.

https://www.youtube.com/watch?v=l_Cc4lZaVg4

### Screenshot(s)

![YouTube_Ads](https://github.com/uBlockOrigin/uAssets/assets/20948631/79a6d3ff-f6e7-4e1a-bc74-b13ed3fa2930)

### uBO version

1.52.2

### Browser name and version

Chromium: 117

### Settings

uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 258983
 cosmetic: 227845
 scriptlet: 44986
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 72931-106, 3d.35m
  https://malware-filter.gitlab.io/malware-filter/urlhaus-filter.txt: 30529-0, 6m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 6m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93683-21604, 7d.13h.40m
  adguard-cookies: 27783-27783, 3d.36m
  adguard-generic: 78337-520, 3d.36m
  adguard-mobile-app-banners: 4647-4647, 3d.36m
  adguard-other-annoyances: 13629-13629, 3d.36m
  adguard-popup-overlays: 24560-24560, 3d.36m
  adguard-social: 21850-1611, 3d.36m
  adguard-widgets: 2312-2312, 3d.36m
  block-lan: 54-0, 7d.13h.41m
  [11 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  easylist: 71663-1399, 1d.10h.31m
  easyprivacy: 33224-464, 1d.10h.30m
  plowe-0: 3720-1446, 7d.13h.40m
  ublock-badware: 7191-329, 2d.13h.18m
  ublock-filters: 34928-4213, 2d.13h.17m
  ublock-privacy: 559-8, 6m
  ublock-quick-fixes: 216-36, 6m
  ublock-unbreak: 2138-95, 2d.13h.16m
  urlhaus-1: 11705-4075, 6m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 599 ms (selfie)
 maxAssetCacheWait: 413 ms

**Comment by stephenhawk8054** [comment]
Follow the instructions here carefully: https://github.com/uBlockOrigin/uAssets/issues/19976

> - [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.

**Comment by TesterMan247** [comment]
OK. What is the solution though?
I can't be bothered reading 500 pages on the other link.

**Comment by stephenhawk8054** [comment]
The instructions is in the first post at the top of that link

`PLEASE READ AND FOLLOW ALL OF THE INSTRUCTIONS FIRST`
