### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by lebaominh12** [uBlockOrigin/uAssets#20069]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/

### Category

detection

### Description

youtube detection 

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 ![image](https://github.com/uBlockOrigin/uAssets/assets/122171007/6f75e5d3-99ab-4da4-8a37-c4d489462206)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 106158
 cosmetic: 41248
 scriptlet: 18803
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 13-1, never
  VIE-1: 2033-0, 1h.26m
  easylist: 71737-32, 1h.26m
  easyprivacy: 33199-66, 1h.26m
  plowe-0: 3726-1069, 1h.32m
  ublock-badware: 7297-134, 1h.26m
  ublock-filters: 34952-153, 1h.26m
  ublock-privacy: 560-6, 1h.26m
  ublock-quick-fixes: 215-84, 1h.26m
  ublock-unbreak: 2142-31, 1h.26m
  urlhaus-1: 12055-0, 1h.26m
filterset (user): [array of 13 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 419 ms (selfie)
 maxAssetCacheWait: 135 ms
popupPanel:
 blocked: 541
 network:
  youtube.com: 209
  doubleclick.net: 6
  google.com: 325
  google.com.vn: 1
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-replace-fetch-response, /"adSlots.*?SLOT_TRIGGER_E…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?AD_PLACEM…
  ##+js(trusted-replace-fetch-response, /"playerAds.*?gutParams":\…
  #@#+js(trusted-replace-fetch-response, /\"adSlots.*?true.*?\}\]\…
  #@#+js(trusted-replace-fetch-response, /\"adPlacements.*?true.*?…
  #@#+js(trusted-replace-fetch-response, /\"playerAds.*?true.*?\}\…
  ##+js(trusted-replace-fetch-response, /(videoplayback.*?)"adSlot…
  ##+js(trusted-replace-fetch-response, /(videoplayback.*?)"adPlac…
  ##+js(trusted-replace-fetch-response, /(videoplayback.*?)"player…
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/19976
