### ISSUE TITLE
[nsfw] sankaku.app: detection

### ISSUE THREAD

**Issue by xXxdan00bxXx** [uBlockOrigin/uAssets#20063]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sankaku.app/`

### Category

detection

### Description

Pop up appears and tells me to disable adblocker to use the site.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105584
 cosmetic: 39938
 scriptlet: 18571
 html: 1064
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35807-142, now
  ublock-badware: 7301-0, now
  ublock-privacy: 589-0, now
  ublock-unbreak: 2189-1, now
  ublock-quick-fixes: 233-0, now
  easylist: 71726-695, now
  easyprivacy: 33234-718, now
  urlhaus-1: 12055-0, now
  plowe-0: 3726-1, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 520 ms
 maxAssetCacheWait: 205 ms
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  sankakucomplex.com: 1
```
</details>

**Comment by D4niloMR** [comment]
`sankaku.app##+js(no-xhr-if, googlesyndication)`

**Comment by dimisa-RUAdList** [comment]
@mapx- 
`https://idol.sankakucomplex.com/`
Pictures do not load when scrolling down. Moreover, this happens for any value (instead of googlesyndication).
`sankaku.app,sankakucomplex.com##+js(no-xhr-if, googlesyndication)`

**Comment by mapx-** [comment]
@gorhill  

```
sankakucomplex.com#@#+js(no-xhr-if, googlesyndication)
sankakucomplex.com##+js(no-xhr-if, blabla)
```

error in console, page broken on scrolling

**Comment by dimisa-RUAdList** [comment]
@mapx- 
What is the idea behind this commit?

**Comment by mapx-** [comment]
typo
https://github.com/uBlockOrigin/uAssets/commit/cc725bbe0a795ea572a50771048a2e15f48f6f5e

**Comment by D4niloMR** [comment]
`beta.sankakucomplex.com##+js(no-xhr-if, googlesyndication)` ?

Btw, I don't see this issue in my end on Firefox, but I see on Opera GX

**Comment by gorhill** [comment]
> error in console, page broken on scrolling

The issue can't be reproduced in Chromium, but it can on Firefox

This is really weird and it seems to be a bug in Firefox's JS, as I can't explain the reason of the weird behavior.

The weird behavior is that there is a Map with one entry, `url` => [url value]`. When matching the call `XMLHttpRequets.open()` against the `no-xhr-if` arguments, which are stored in a `Map`, the scriptlet uses `Array.from([Map variable].keys())`, and this expectedly returns en ampty array, while it should return an array like `[ 'url' ]`. If instead of `[Map variable].keys()` I use the spread operator `...`, it works as expected, I get `[ 'url' ]`.

I can't explain why `[Map variable].keys()` is not return a properly filled array, so at this point I am thinking this is a JS engine bug in Firefox.

I will push a workaround using the spread operator instead.

**Comment by D4niloMR** [comment]
> The issue can't be reproduced in Chromium

I'm able to reproduce this in Opera GX 102.0.4880.90
https://github.com/uBlockOrigin/uAssets/assets/70459964/896294b7-c6e2-42b8-be04-a970cd563639

Idk if this info is relevant anymore, maybe is, so i'll send

**Comment by gorhill** [comment]
It seems to be a site-specific issue though, the following at the console gives the weird result only on `https://idol.sankakucomplex.com/` (so far):

    var map = new Map();
    map.set('url', 'toto');
    Array.from(map.keys()) ;

**Comment by mapx-** [comment]
I can reproduce in chrome too.

**Comment by gorhill** [comment]
> I can reproduce in chrome too

Looks like I fumbled when testing on Chromium.

> Tampered by the page?

Thanks for spotting this, in retrospect I should have looked at `Array.from`.

I will modify the fix accordingly.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
Please look at this too: https://github.com/uBlockOrigin/uAssets/commit/ca9898d42a2c2c1ac9cc44d02bfe77d4d5fb6da0#commitcomment-129977087
