### ISSUE TITLE
[nsfw] streamnoads.com: detection

### ISSUE THREAD

**Issue by a32599** [uBlockOrigin/uAssets#20061]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://streamnoads.com/v/VdlMpZ2xVRHKwQM/4horlover___BOYST0292.mp4`

### Category

detection

### Description

Please disable your adblocker!
The creator of this video does not allow adblock. Please disable and reload!

### Other extensions used

n

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 119619
 cosmetic: 51732
 scriptlet: 22614
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5545-7, 2m
 default:
  user-filters: 0-0, never
  CHN-0: 25101-133, 2m
  easylist: 71726-21, 2m
  easyprivacy: 33234-77, 2m
  plowe-0: 3726-1071, 2m
  ublock-badware: 7297-134, 2m
  ublock-filters: 34924-160, 2m
  ublock-privacy: 559-6, 2m
  ublock-quick-fixes: 235-95, 2m
  ublock-unbreak: 2142-33, 2m
  urlhaus-1: 11360-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 316 ms (selfie)
 maxAssetCacheWait: 142 ms
popupPanel:
 blocked: 4
 network:
  lstonorallantyne.com: 4
 extended:
  ##.skyscraper.ad
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by gorhill** [comment]
At first I couldn't reproduce, ebentually for some reasons the detection started to be triggered.
