### ISSUE TITLE
[nsfw] studentontask.com: popups

### ISSUE THREAD

**Issue by BWA1212** [uBlockOrigin/uAssets#20075]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://studentontask.com/`

### Category

popups

### Description

inipropret

### Other extensions used

non

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 105601
 cosmetic: 39947
 scriptlet: 18685
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 71742-11, now
  easyprivacy: 33200-64, now
  plowe-0: 3724-1067, now
  ublock-badware: 7297-134, now
  ublock-filters: 34946-144, now
  ublock-privacy: 561-6, now
  ublock-quick-fixes: 216-85, now
  ublock-unbreak: 2137-31, now
  urlhaus-1: 12095-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 25 redacted]
 removed:
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 614 ms (selfie)
 maxAssetCacheWait: 243 ms
popupPanel:
 blocked: 0
 extended:
  ##h2
```
</details>

**Comment by mapx-** [comment]
it's again about restrictions on some school network

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/70399f97-9a11-4435-a439-c73706b80208)
