### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by zsak1** [uBlockOrigin/uAssets#20070]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection blocker

### Description

detects the blocker, a window pops up to buy yt premium

### Other extensions used

no 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 292577
 cosmetic: 228353
 scriptlet: 45606
 html: 0
listset (total-discarded, last-updated):
 removed:
  POL-0: null
  POL-2: null
  plowe-0: null
 added:
  https://alleblock.pl/alleblock/alleblock.txt: 94-0, 2m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 73020-110, 2m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt: 57013-39, 2m
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances-others.txt: 5219-141, 2m
  adguard-cookies: 27804-27804, 2m
  adguard-generic: 78493-1482, 2m
  adguard-mobile-app-banners: 4656-4656, 2m
  adguard-other-annoyances: 13648-13648, 2m
  adguard-popup-overlays: 24593-24593, 2m
  adguard-social: 21885-925, 2m
  adguard-spyware: 61459-4663, 2m
  adguard-spyware-url: 1251-4, 2m
  [13 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 71737-31889, 2m
  easyprivacy: 33199-19695, 2m
  ublock-badware: 7297-334, 2m
  ublock-filters: 34953-4288, 1m
  ublock-privacy: 560-140, 1m
  ublock-quick-fixes: 215-89, 1m
  ublock-unbreak: 2142-147, 1m
  urlhaus-1: 12055-0, 1m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1776 ms (selfie)
 maxAssetCacheWait: 1314 ms
popupPanel:
 blocked: 30
 network:
  youtube.com: 20
  doubleclick.net: 2
  google.com: 8
 extended:
  ###ticker.ytd-masthead
  ##.video-annotations
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ###offer-module
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##.ytp-share-button
  ###social-links
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /(videoplayback.*?)"adSlot…
  ##+js(trusted-replace-fetch-response, /(videoplayback.*?)"adPlac…
  ##+js(trusted-replace-fetch-response, /(videoplayback.*?)"player…
```
</details>

**Comment by mapx-** [comment]
read / report here: https://github.com/uBlockOrigin/uAssets/issues/19976
