### ISSUE TITLE
www2.cloud.editorialmanager.com: breakage

### ISSUE THREAD

**Issue by katonagl** [uBlockOrigin/uAssets#20073]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www2.cloud.editorialmanager.com/tsf/default2.aspx`

### Category

breakage

### Description

The site is broken, link are not clickable.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 118
filterset (summary):
 network: 105836
 cosmetic: 41621
 scriptlet: 18624
 html: 1082
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35834-135, 6m
  ublock-badware: 7270-0, 6m
  ublock-privacy: 589-0, 6m
  ublock-unbreak: 2189-0, 6m
  easylist: 71685-694, 7m
  easyprivacy: 33200-726, 6m
  plowe-0: 3724-1, 6m
  HUN-0: 2071-4, 6m
  urlhaus-1: 12095-0, 6m
  ublock-quick-fixes: 212-1, 6m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3356 ms (selfie)
 maxAssetCacheWait: 1437 ms
popupPanel:
 blocked: 22
 no-cosmetic-filtering: true
 network:
  editorialmanager.com: 21
  newrelic.com: 1
```
</details>

**Comment by gorhill** [comment]
The whole page is broken on my side. EasyList filter `.com/tsf/` filter is the culprit.

cc @ryanbr
