### ISSUE TITLE
[nsfw] indojavstream.com: nuisance

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#20079]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://indojavstream.com/watch/rbd00410.html`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/98657967/82d99d98-7360-4d99-ad7e-0e73493e27b3)

something block with play button, need 3 click

![image](https://github.com/uBlockOrigin/uAssets/assets/98657967/46542f61-a97d-4f94-b3fc-416442b07954)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 113732
 cosmetic: 112737
 scriptlet: 26553
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 10154-5, 58m
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, 58m
  easylist-annoyances: 3993-34, 1h.38m
  easylist-notifications: 2712-80, 1h.38m
  fanboy-cookiemonster: 48557-217, 1h.38m
  fanboy-social: 16240-10, 1h.38m
  ublock-annoyances: 5554-75, 1h.38m
  ublock-cookies-easylist: 333-333, 1h.38m
 default:
  user-filters: 12-1, never
  easylist: 71741-23, 1h.38m
  easyprivacy: 33201-151, 1h.38m
  plowe-0: 3729-1069, 1h.38m
  ublock-badware: 7297-136, 1h.38m
  ublock-filters: 34949-279, 1h.38m
  ublock-privacy: 561-8, 1h.38m
  ublock-quick-fixes: 218-89, now
  ublock-unbreak: 2137-35, 1h.38m
  urlhaus-1: 13805-0, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1140 ms (selfie)
 maxAssetCacheWait: 218 ms
popupPanel:
 blocked: 10
 network:
  adforcast.com: 3
  du0pud0sdlmzf.cloudfront.net: 1
  googletagmanager.com: 1
  jads.co: 1
  limosiwooable.com: 1
  yandex.ru: 1
  zimpolo.com: 2
 extended:
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(addEventListener-defuser, contextmenu)
  ##+js(abort-on-property-write, _pop)
  ##+js(no-setInterval-if, adblock)
  ##+js(no-window-open-if)
  ##+js(remove-attr, target, #downloadvideo)
  ##+js(nano-setTimeout-booster, counter)
  ##+js(abort-current-script, JSON.parse, Promise)
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

**Comment by mapx-** [comment]
same, the same server `streamtape`
