### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by deadman616** [uBlockOrigin/uAssets#20071]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection

### Description

YouTube is warning me about me using Adblocker, are you working on a fix for fix problem?

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105492
 cosmetic: 39931
 scriptlet: 18589
 html: 1066
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35834-136, now
  ublock-badware: 7301-0, now
  ublock-privacy: 589-0, 6m
  ublock-unbreak: 2189-1, now
  ublock-quick-fixes: 219-0, 6m
  easylist: 71663-693, 6m
  easyprivacy: 33199-718, now
  urlhaus-1: 12055-0, now
  plowe-0: 3724-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1810 ms (selfie)
 maxAssetCacheWait: 1205 ms
popupPanel:
 blocked: 34
 network:
  youtube.com: 8
  doubleclick.net: 4
  google.com: 21
  google.com.lb: 1
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##div#masthead-ad > .ytd-rich-grid-renderer
  ##ytd-banner-promo-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-fetch-response, /"adSlots.*?SLOT_TRIGGER_E…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?AD_PLACEM…
  ##+js(trusted-replace-fetch-response, /"playerAds.*?gutParams":\…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_fet_wr_en…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(trusted-replace-fetch-response, /\"adSlots.*?true.*?\}\]\…
  #@#+js(trusted-replace-fetch-response, /\"adPlacements.*?ytimg.*…
  #@#+js(trusted-replace-fetch-response, /\"playerAds.*?\"enabledE…
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/19976
