### ISSUE TITLE
[nsfw] sextb.net: nuisance

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#20078]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sextb.net/venu-877-sub`

### Category

nuisance

### Description

something is block play button, need 3 left-click to play

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/98657967/31b7f3eb-a910-4e82-9c8e-7dfa25803ef4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 111442
 cosmetic: 105785
 scriptlet: 25263
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 3993-136, never
  easylist-notifications: 2712-90, never
  fanboy-cookiemonster: 48557-214, 1m
  fanboy-social: 16240-11, never
  ublock-annoyances: 5554-56, 1m
  ublock-cookies-easylist: 333-333, 1m
 default:
  user-filters: 10-0, never
  easylist: 71741-12, 1m
  easyprivacy: 33201-64, 1m
  plowe-0: 3729-1069, 1m
  ublock-badware: 7297-134, 1m
  ublock-filters: 34949-156, 1m
  ublock-privacy: 561-6, 1m
  ublock-quick-fixes: 215-85, 52m
  ublock-unbreak: 2137-33, 1m
  urlhaus-1: 13805-0, 52m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1140 ms (selfie)
 maxAssetCacheWait: 218 ms
popupPanel:
 blocked: 24
 network:
  sextb.net: 1
  adforcast.com: 2
  cloudflareinsights.com: 1
  du0pud0sdlmzf.cloudfront.net: 1
  googletagmanager.com: 1
  histats.com: 1
  limosiwooable.com: 1
  pqaz.xyz: 10
  realsrv.com: 3
  wpnsrv.com: 1
  yandex.ru: 1
  zimpolo.com: 1
 extended:
  ##.button-social
  ##.adsbyexoclick
  ##.sextb_300
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://reddit.com/submit?"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##+js(addEventListener-defuser, contextmenu)
  ##+js(abort-on-property-write, _pop)
  ##+js(no-setInterval-if, adblock)
  ##+js(no-window-open-if)
  ##+js(remove-attr, target, #downloadvideo)
  ##+js(nano-setTimeout-booster, counter)
  ##+js(abort-current-script, JSON.parse, Promise)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
it's the side effect of
`streamtape.*##+js(no-window-open-if)`

whitelisting it will bring back the popups on ST server

**Comment by Bug-Cache** [comment]
> `https://sextb.net/venu-877-sub`

doesn't work, still need 3 click before play video
