### ISSUE TITLE
[nsfw] cpmlink.pro: ads

### ISSUE THREAD

**Issue by umut-nb0** [uBlockOrigin/uAssets#20083]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cpmlink.pro/uc5yS`

### Category

ads

### Description

go to this link: NSFW - `https://utanmazturkler.com/universiteli-turk-kizini-biri-sikiyor-biri-pazarliyor/`
Click on the shortened link below the content.

![image](https://github.com/uBlockOrigin/uAssets/assets/147916475/b3c09e22-1111-4770-9947-3ac18a8a1ec5)

If you click on the go to link button you will get popups.

![image](https://github.com/uBlockOrigin/uAssets/assets/147916475/a6b5022e-9373-4728-9ecc-a973e6420c7d)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 108994
 cosmetic: 50439
 scriptlet: 20275
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  TUR-0: 13769-9, 1m
  easylist: 71743-32, 1m
  easyprivacy: 33231-69, 1m
  plowe-0: 3729-1067, 1m
  ublock-badware: 7297-134, 1m
  ublock-filters: 34949-151, 1m
  ublock-privacy: 559-6, 1m
  ublock-quick-fixes: 218-85, 1m
  ublock-unbreak: 2137-32, 1m
  urlhaus-1: 13805-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1216 ms
 maxAssetCacheWait: 561 ms
popupPanel:
 blocked: 2
 network:
  amung.us: 1
  jsdelivr.net: 1
 extended:
  ##.ad-link:not(.adsbox)
  #@#.ad-link
```
</details>

**Comment by mapx-** [comment]
Which is the final destination ?

**Comment by umut-nb0** [comment]
The final destination is dooood.com

**Comment by mapx-** [comment]
sometimes you have to click twice the "go to .." button

**Comment by umut-nb0** [comment]
There are other problems with this shortened link.

The link above will direct you to bildirim.link and ask for your consent to send you push notifications.

![2023-10-16 04_22_03-Window](https://github.com/uBlockOrigin/uAssets/assets/147916475/ebe770de-2419-4c6a-b3c9-9e2e278b150d)


bildirim.link is the last step before going to the target site. If you do not allow it, you cannot go to the target site. I don't know the real purpose of 'bildirim.link', but it looks like a scam site.

Please write a scriptlet to bypass this
like this
bildirim.link##+js(set-constant, Notification, undefined)


---

Please add ##.alternative-ad rule for ad space. 
![2023-10-16 04_30_10-Window](https://github.com/uBlockOrigin/uAssets/assets/147916475/82b63261-3c2e-46ba-98d7-6cb66aff2489)
![2023-10-16 04_53_34-Window](https://github.com/uBlockOrigin/uAssets/assets/147916475/4eb99e7d-1294-4e9c-b5ef-1ab4476cdd9f)



---

You can also delete the old EasyList ||bildirim.eu^$third-party rule. https://github.com/uBlockOrigin/uAssets/issues/12536

I tried to bypass the site using the ||bildirim.link^$third-party rule but it doesn't work.

---

**Comment by stephenhawk8054** [comment]
@luther09 For shortener links, comment here next time: https://github.com/uBlockOrigin/uAssets/discussions/27472
