### ISSUE TITLE
aniwave.to: breakage

### ISSUE THREAD

**Issue by spaceturtle11** [uBlockOrigin/uAssets#20087]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aniwave.to/watch/sousou-no-frieren.3rp2y/ep-3`

### Category

breakage

### Description

VIDPLAY and MYCLOUD and MP4UPLOAD mirrors broken with UbO turned on. Purged. Updated. Same.
Filemoon works, but very slow and sluggish

Disabled custom filters. Works with uBlockO turned off but causes Ad-Apocalypse wreaking havoc.

### Other extensions used

Gesturefy, Youtube Theater Mode, Translate Web Pages 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 115
filterset (summary):
 network: 107969
 cosmetic: 64701
 scriptlet: 18699
 html: 1083
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifiltrs Extra.txt: 67-0, 1m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 407-39, 1m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/MAL-Sync UI.txt: 38-0, 1m
  https://www.i-dont-care-about-cookies.eu/abp/: 25833-4, 1m
 default:
  user-filters: 12-0, never
  ublock-filters: 35826-143, 1m
  ublock-badware: 7301-0, 1m
  ublock-privacy: 591-0, 1m
  ublock-unbreak: 2183-1, 1m
  ublock-quick-fixes: 225-0, 1m
  easylist: 71776-692, 1m
  easyprivacy: 33201-722, 1m
  urlhaus-1: 13010-0, 1m
  plowe-0: 3729-1, 1m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 443 ms (selfie)
 maxAssetCacheWait: 152 ms
popupPanel:
 blocked: 5
 network:
  disqus.com: 2
  googletagmanager.com: 1
  superherosnout.com: 2
 extended:
  ##+js(abort-on-property-read, AaDetector)
  ##+js(set-constant, console.log, undefined)
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
  ##.jw-preview.jw-reset:style(filter:blur(8px);)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, mm)
  ##+js(remove-attr, data-ad-img|data-ad-target)
  ##+js(abort-current-script, Math, XMLHttpRequest)
  ##+js(no-setInterval-if, break)
  ##+js(abort-on-property-read, open)
  ##+js(abort-on-property-read, zfgstorage)
  ##+js(abort-on-property-read, __Y)
  ##+js(remove-attr, data-id|data-p, [data-id]\,[data-p], stay)
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
added:
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifiltrs Extra.txt: 67-0, 1m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 407-39, 1m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/MAL-Sync UI.txt: 38-0, 1m
  https://www.i-dont-care-about-cookies.eu/abp/: 25833-4, 1m
```

Can you disable your custom filter lists and test again?

**Comment by spaceturtle11** [comment]
The testing was without those filters enabled. Tried it again just now. Same. 

The players are initialized. But they do not start playback and apparently downloading the file. 
Checked the domains in the list to the left, the players' domains seem to be enabled and green also the cloudflare stuff seems not to be blocked. I have no idea why it doesn't load. Checked with ungoogled chromium browser and uB:O and it works.

Firefox Enhanced Tracking Protection is OFF.

**Comment by stephenhawk8054** [comment]
Hmmm... The video plays fine for me with uBO default settings: https://github.com/uBlockOrigin/uAssets/assets/66517106/a8f1deec-27a5-40d1-a781-8f9a22586612

**Comment by spaceturtle11** [comment]
I tried one of the other domains of aniwave (.ws) and it has **resolved the issue.**

Usually that indicates a dns block by the ISP, but then why does it work on non Firefox browsers. I have no idea.
Just wanted to give an update in case someone finds this. Still wish I found out the exact reason, but anyway. This works for now.
