### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Zezuar** [uBlockOrigin/uAssets#20088]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch`

### Category

detection

### Description

youtube adblocker-blockers are detecting it no matter what i do.

### Other extensions used

Sponsorblock, Adnausium , Enhancer for youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 106584
 cosmetic: 39948
 scriptlet: 18595
 html: 1068
listset (total-discarded, last-updated):
 default:
  user-filters: 53-0, never
  ublock-filters: 35826-241, 6m
  ublock-badware: 7301-0, 6m
  ublock-privacy: 591-0, 6m
  ublock-unbreak: 2183-1, 6m
  ublock-quick-fixes: 225-0, 6m
  easylist: 71776-592, 6m
  easyprivacy: 33201-720, 6m
  urlhaus-1: 13010-0, 6m
  plowe-0: 3729-1, 6m
filterset (user): [array of 53 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 430 ms (selfie)
 maxAssetCacheWait: 211 ms
popupPanel:
 blocked: 1
 network:
  youtube.com: 1
 extended:
  ##+js(trusted-replace-fetch-response, /"adSlots.*?SLOT_TYPE_PLAY…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?AD_PLACEM…
  ##+js(trusted-replace-fetch-response, /"playerAds.*?"enabledEnga…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by u-RraaLL** [comment]
> [x] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

**Comment by mapx-** [comment]
read / report here: https://github.com/uBlockOrigin/uAssets/issues/19976
