### ISSUE TITLE
20minutos.es: breakage

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#20081]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.20minutos.es/noticia/3162078/0/fuga-empresas-cataluna-lista-companias-dejan-region-proceso-soberanista/`

### Category

breakage

### Description

After logging in, both with my Google account and with my email and password, I had to disable uBlock Origin so that I could access my account and see that I was logged in, and after re-enabling it, I saw that I was still logged in.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 109797
 cosmetic: 46164
 scriptlet: 19081
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 71743-11, now
  easyprivacy: 33201-64, now
  plowe-0: 3729-1069, now
  spa-0: 3725-19, now
  spa-1: 5643-225, now
  ublock-badware: 7297-134, now
  ublock-filters: 34949-175, now
  ublock-privacy: 561-6, now
  ublock-quick-fixes: 218-85, 1h.24m
  ublock-unbreak: 2137-33, now
  urlhaus-1: 13805-0, 1h.25m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4709 ms (selfie)
 maxAssetCacheWait: 1504 ms
popupPanel:
 blocked: 37
 network:
  criteo.net: 1
  doubleverify.com: 7
  google.com: 1
  googlesyndication.com: 10
  googletagmanager.com: 1
  mrf.io: 1
  newsroom.bi: 2
  scorecardresearch.com: 1
  sunmedia.tv: 8
  taboola.com: 1
  tremorhub.com: 2
  videoplaza.tv: 2
 extended:
  ##.taboola_container
  ##.axds
  ##.module-coupons
  ##.axds > div.henneoHB
  ##.axds-lane
  ##+js(abort-on-property-read, hb_now)
```
</details>

**Comment by mapx-** [comment]
I'm able logging in (google account), I see correctly my user icon.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by rodrigosambadesaa** [comment]
Didn't have to do any of these. Today's morning it worked without doing anything.
