### ISSUE TITLE
open.spotify.com: breakage

### ISSUE THREAD

**Issue by ilovecatsandsims4** [uBlockOrigin/uAssets#20089]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/__noul__?pfhp=2c2ccb58-8a92-4713-a1c0-8b43b3090b49`

### Category

[breakage]

### Description

Spotify not loading when its enabled

### Other extensions used

adless spotify which i removed and didnt fix it either, and ttv

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 106545
 cosmetic: 39944
 scriptlet: 18595
 html: 1068
listset (total-discarded, last-updated):
 default:
  user-filters: 49-0, never
  ublock-filters: 35826-241, 3m
  ublock-badware: 7301-0, 2m
  ublock-privacy: 591-0, 2m
  ublock-unbreak: 2183-1, 2m
  ublock-quick-fixes: 225-0, 2m
  easylist: 71737-592, 2m
  easyprivacy: 33201-720, 2m
  urlhaus-1: 13010-0, 2m
  plowe-0: 3729-1, 2m
filterset (user): [array of 49 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 604 ms
 maxAssetCacheWait: 244 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
- disable any other addon

> user-filters: 49-0
disable "my filters" 

test again
