### ISSUE TITLE
270towin.com: detection

### ISSUE THREAD

**Issue by RedLight-Scratch** [uBlockOrigin/uAssets#20084]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://www.270towin.com/ manages to load the following image when you are blocking ads. 
![Screenshot 2023-10-14 at 06-59-25 270toWin - 2024 Presidential Election Interactive Map](https://github.com/uBlockOrigin/uAssets/assets/76401850/756c24a9-064d-46b1-91bf-b7cbc6cbbf11)

### URL(s) where the issue occurs.

https://www.270towin.com/

### Screenshot(s)

![Screenshot 2023-10-14 at 06-59-25 270toWin - 2024 Presidential Election Interactive Map](https://github.com/uBlockOrigin/uAssets/assets/76401850/bd59d2cf-9a3e-4c57-ba14-fec75a484e3f)

### uBO version

1.52.2

### Browser name and version

Firefox 118.0.2

### Settings

None

**Comment by mapx-** [comment]
enable `uBlock filters – Annoyances`
