### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Overlad11** [uBlockOrigin/uAssets#20097]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=bvHYzxh9m9c`

### Category

detection

### Description

Seeing ads violate YT's TOS Popup

### Other extensions used

enhancer (Disabled)
Ad guard(Disabled)
Lastpass
Sponserblock (Disabled)
Tampermonkey (Disabled)
Group Speeddial

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105467
 cosmetic: 39982
 scriptlet: 18701
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 71828-11, 3m
  easyprivacy: 33189-64, 3m
  plowe-0: 3729-1069, 3m
  ublock-badware: 7263-133, 3m
  ublock-filters: 34960-145, 3m
  ublock-privacy: 561-6, 3m
  ublock-quick-fixes: 223-88, 3m
  ublock-unbreak: 2137-31, 3m
  urlhaus-1: 11950-0, 3m
filterset (user): [empty]
trustedset:
 added: [array of 15 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 989 ms (selfie)
 maxAssetCacheWait: 605 ms
popupPanel:
 blocked: 29
 network:
  youtube.com: 8
  doubleclick.net: 4
  google.com: 17
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /"adSlots.*?SLOT_TYPE_PLAY…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?AD_PLACEM…
  ##+js(trusted-replace-fetch-response, /"playerAds.*?"enabledEnga…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by gwarser** [comment]
> * [x]  This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

**Comment by mapx-** [comment]
first read / follow the indications here (then report if still an issue):
https://github.com/uBlockOrigin/uAssets/issues/19976
