### ISSUE TITLE
weather.com: breakage

### ISSUE THREAD

**Issue by Geyser182** [uBlockOrigin/uAssets#20091]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://weather.com/storms/hurricane/news/2023-10-13-october-invest-tropical-depression-storm`
`https://weather.com/weather-news-alerts`

### Category

breakage

### Description

Weather.com's social media and other web embeds/frames don't work properly and say I have settings that turn them off. They haven't worked properly since May 2023, and another feature on the site that doesn't appear to be working is the web notifications feature they recently added to their site, which is probably in June of 2023. 

I use this site very often, and I would love for these features to work properly again. If they break again or other features break, I will report them here. 

Thank you uBO team for making my Internet experience the best it can be. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (19)](https://github.com/uBlockOrigin/uAssets/assets/147728515/69f87254-4656-4c54-b790-d6223a6662bf)

![Screenshot (20)](https://github.com/uBlockOrigin/uAssets/assets/147728515/33ee088f-15a0-41f1-9021-ba412f86496a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 256101
 cosmetic: 86132
 scriptlet: 35080
 html: 1069
listset (total-discarded, last-updated):
 added:
  adguard-generic: 78522-6627, 3m
  adguard-mobile: 8743-99, 3m
  adguard-spyware-url: 1251-81, 3m
  adguard-spyware: 61463-16839, 3m
  block-lan: 54-0, 3m
  curben-phishing: 86198-14, 2m
 default:
  user-filters: 61-11, never
  ublock-filters: 35824-250, 3m
  ublock-badware: 7308-0, 3m
  ublock-privacy: 591-0, 3m
  ublock-unbreak: 2183-2, 3m
  ublock-quick-fixes: 220-0, 3m
  easylist: 71786-592, 3m
  easyprivacy: 33189-768, 3m
  urlhaus-1: 12865-0, 2m
  plowe-0: 3729-1, 2m
filterset (user): [array of 61 redacted]
userSettings: [none]
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 2709 ms (selfie)
 maxAssetCacheWait: 1225 ms
popupPanel:
 blocked: 22
 network:
  weather.com: 4
  adsafeprotected.com: 2
  appboycdn.com: 1
  braze.com: 1
  confiant-integrations.net: 2
  doubleclick.net: 1
  go-mpulse.net: 2
  google.com: 2
  googlesyndication.com: 1
  indexww.com: 1
  instana.io: 1
  jwpltx.com: 1
  rubiconproject.com: 1
  scorecardresearch.com: 2
 extended:
  ##.adWrapper
  ##.adLabel
  ##.ad_module
  ##.ArticleBody--wrapper--3Jgzk > p > em
  ##div[class*="adWrapper"]
  ##div[id^="Taboola-main-"]
  ##div[id^="Taboola-sidebar"]
  ##+js(set-constant, DprSdk, {})
  ##+js(set-constant, DprSdk.init, noopFunc)
  ##+js(set-constant, DprSdk.setHooks, noopFunc)
  ##+js(xml-prune, VAST, , adnxs)
```
</details>

**Comment by mapx-** [comment]
for the first issue add:

```
weather.com#@#+js(set-constant, DprSdk, {})
weather.com#@#+js(set-constant, DprSdk.init, noopFunc)
weather.com#@#+js(set-constant, DprSdk.setHooks, noopFunc)
||weather.com/api/v*/script/dprsdkscript.js$script,badfilter
```

@Yuki2718 @Alex-302 `AdGuard Tracking Protection`

**Comment by mapx-** [comment]
for the push notifications I cannot reproduce the issue, read:
https://support.mozilla.org/en-US/kb/push-notifications-firefox

**Comment by Yuki2718** [comment]
@AdamWr I will temp disabled the rules. You might have idea not to cause the problem while blocking the tracker.

**Comment by ave9858** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/aa47c507-f308-4073-af75-469e5c4208f4)
Seeing this on https://weather.com in the the EU with all annoyance filters enabled. Should I create a new issue as this isn't breakage?
