### ISSUE TITLE
app.weathercloud.net: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#20104]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.weathercloud.net/d4305893923`

### Category

breakage

### Description

Going into the settings to switch values like from Celsius to Fahrenheit don't save when uBlock is enabled. To recreate, press the settings cog on the top right then select a different unit and watch it fail to save. 

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 255756
 cosmetic: 215769
 scriptlet: 45624
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-quick-fixes: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 73029-109, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93986-21656, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 78530-520, now
  adguard-mobile: 8743-57, now
  adguard-spyware: 61459-1436, now
  adguard-spyware-url: 1252-4, now
  block-lan: 54-0, now
  curben-phishing: 77203-5, now
  fanboy-cookiemonster: 48587-48587, now
  ublock-annoyances: 5539-241, 17m
 default:
  user-filters: 0-0, never
  easylist: 71828-1247, now
  easyprivacy: 33193-16742, now
  plowe-0: 3729-1239, now
  ublock-badware: 7264-328, now
  ublock-filters: 34963-4268, now
  ublock-privacy: 561-139, 16m
  ublock-unbreak: 2137-146, now
  urlhaus-1: 11950-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 224 ms (selfie)
 maxAssetCacheWait: 163 ms
popupPanel:
 blocked: 4
 network:
  weathercloud.net: 1
  googlesyndication.com: 2
  pingdom.net: 1
 extended:
  ##ins.adsbygoogle
  ##.icon-share-alt
  ##.facebook-bg
  ##.twitter-bg
  ###ad-box
  ##.ad-box:not(#ad-banner)
  ##.icon-social-facebook
  ##.icon-social-twitter
  ##.icon-social-youtube
  ##.CookieMonsterBox
  ###disclaimer-box
  ##a[href^="http://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://telegram.me/share/url?"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://www.linkedin.com/sharing/share-offsite/?"]
  ##a[href^="https://www.reddit.com/submit?"]
```
</details>

**Comment by mapx-** [comment]
add

`@@||app.weathercloud.net/assets/*/CookieMonster.min.js$script,1p`

**Comment by mapx-** [comment]
> ublock-quick-fixes: null

bad idea. `Quick-fixes` is one of the most important lists.
