### ISSUE TITLE
[nsfw] apenasmaisumyaoi.com: detection

### ISSUE THREAD

**Issue by Benjigx** [uBlockOrigin/uAssets#20105]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://apenasmaisumyaoi.com/manga/bateecorre/1a-temporada/capitulo-09/`

### Category

detection

### Description

adblock detector does not allow you to use the site with the block turned on.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[
](https://apenasmaisumyaoi.com/manga/bateecorre/1a-temporada/capitulo-09/)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 117058
 cosmetic: 193190
 scriptlet: 29600
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27805-31, 4m
  adguard-mobile-app-banners: 4656-9, 4m
  adguard-other-annoyances: 13651-7, 4m
  adguard-popup-overlays: 24596-61, 4m
  adguard-social: 21886-921, 4m
  adguard-widgets: 2321-3, 4m
  easylist-annoyances: 3995-203, 4m
  easylist-chat: 141-11, 4m
  easylist-newsletters: 6543-424, 4m
  easylist-notifications: 2759-1446, 4m
  fanboy-cookiemonster: 48587-3828, 4m
  fanboy-social: 16247-725, 4m
  [4 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 71828-70, now
  easyprivacy: 33193-178, now
  plowe-0: 3729-1070, now
  spa-1: 5643-71, now
  ublock-badware: 7264-133, now
  ublock-filters: 34963-559, now
  ublock-privacy: 561-8, now
  ublock-quick-fixes: 226-95, now
  ublock-unbreak: 2137-36, now
  urlhaus-1: 11765-0, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4263 ms (selfie)
 maxAssetCacheWait: 172 ms
popupPanel:
 blocked: 23
 network:
  chaursug.xyz: 8
  d2klx87bgzngce.cloudfront.net: 1
  disqus.com: 4
  googlesyndication.com: 3
  inklinkor.com: 1
  intelligenceadx.com: 1
  ophoacit.com: 1
  outoctillerytor.com: 1
  privacymanager.io: 1
  viglink.com: 2
 extended:
  ##.go-to-top
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  ##.comment__share
  ##.comment-share__buttons
  ##.share__button-container
  ##.share__button
  ##.share-icons-wrapper
  ###thread-share-bar
  ##.comment__share > *
  ###email-signup
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
```
</details>

**Comment by D4niloMR** [comment]
Add this to your filters:

`apenasmaisumyaoi.com##+js(noeval-if, /chp_?ad/)`
