### ISSUE TITLE
youtube.com: popups

### ISSUE THREAD

**Issue by markki22** [uBlockOrigin/uAssets#20101]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=OTE59yYMm0Q`

Idk what you mean about this is not "youtube" report, because there was a spesific question to share youtube report.

### Category

popups

### Description

Youtube antiadblock is popping up, did everything as there was in the list.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105639
 cosmetic: 41984
 scriptlet: 18620
 html: 1075
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 35841-137, 2m
  ublock-badware: 7267-0, 2m
  ublock-privacy: 591-0, 2m
  ublock-unbreak: 2183-2, 2m
  ublock-quick-fixes: 220-0, 2m
  easylist: 71828-650, 2m
  easyprivacy: 33189-762, 2m
  urlhaus-1: 11950-0, 2m
  plowe-0: 3729-1, 2m
  FIN-0: 2213-0, 2m
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 491 ms
 maxAssetCacheWait: 175 ms
popupPanel:
 blocked: 10
 network:
  youtube.com: 5
  doubleclick.net: 3
  google.com: 2
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytd-merch-shelf-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-fetch-response, /"adSlots.*?SLOT_TYPE_PLAY…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?AD_PLACEM…
  ##+js(trusted-replace-fetch-response, /"playerAds.*?"enabledEnga…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, yt.config_.openPopupConfig.supportedPopups.a…
  ##+js(set-constant, Object.prototype.adBlocksFound, 0)
  ##+js(set-constant, ytplayer.config.args.raw_player_response.adP…
  ##+js(set-constant, Object.prototype.hasAllowedInstreamAd, true)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by markki22** [comment]
> duplicate #19976

Sorry, I thought you would like me to open a new troubleshooting ticket. I posted this on the #19976 too

**Comment by markki22** [comment]
> > * [x]  This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

You are right, it is just confusing with this
![image](https://github.com/uBlockOrigin/uAssets/assets/148010812/98fe51bb-00e5-412b-8080-adef69fad42f)
