### ISSUE TITLE
deltamath.com: popups

### ISSUE THREAD

**Issue by Heisenburgera** [uBlockOrigin/uAssets#20108]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.deltamath.com/app/student/2642561/20500531/394adf020d8b66de261d7bebfd40cd2d`

### Category

popups

### Description

Ad blocker thing

### Other extensions used

Idk

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  easylist: null
  easyprivacy: null
  plowe-0: null
  ublock-badware: null
  ublock-filters: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
  urlhaus-1: null
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 10 redacted]
userSettings:
 autoUpdate: false
 collapseBlocked: false
 contextMenuEnabled: false
 hyperlinkAuditingDisabled: false
 parseAllABPHideFilters: false
 prefetchingDisabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 258 ms
 maxAssetCacheWait: 88 ms
popupPanel:
 blocked: 0
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
```
</details>

**Comment by mapx-** [comment]
> removed:
  user-filters: null
  easylist: null
  easyprivacy: null
  plowe-0: null
  ublock-badware: null
  ublock-filters: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
  urlhaus-1: null

good job => your installation is completely broken => reinstall uBO and do not touch any setting
