### ISSUE TITLE
opensubtitles.org: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#20109]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.opensubtitles.org/tr/search2/sublanguageid-tur/moviename-the+boys+(2019)`

### Category

ads

### Description

leftovers, its there with easylist annoyance too.

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedScreeadfesdrgenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/3559774a-60ab-4b1d-be20-6256209e55c6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 109200
 cosmetic: 76822
 scriptlet: 25041
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27818-31, 52m
  fanboy-thirdparty_social: 69-0, 52m
  ublock-annoyances: 5541-16, 52m
 default:
  user-filters: 0-0, never
  TUR-0: 13770-9, 52m
  easylist: 71838-35, 52m
  easyprivacy: 33187-72, 52m
  plowe-0: 3729-1071, 52m
  ublock-badware: 7264-133, 52m
  ublock-filters: 34957-154, 51m
  ublock-privacy: 561-6, 51m
  ublock-quick-fixes: 226-95, 51m
  ublock-unbreak: 2137-33, 51m
  urlhaus-1: 11765-0, 51m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 563 ms (selfie)
 maxAssetCacheWait: 158 ms
popupPanel:
 blocked: 7
 network:
  opensubtitles.org: 2
  amazon-adsystem.com: 1
  diluterwearers.com: 1
  googletagmanager.com: 1
  pushmaster-cdn.xyz: 1
  toplist.cz: 1
```
</details>

**Comment by mapx-** [comment]
add

`opensubtitles.org##tr[style]:has([src*="php"])`

report at easylist repository
@ryanbr
