### ISSUE TITLE
star-history.com: ads

### ISSUE THREAD

**Issue by ave9858** [uBlockOrigin/uAssets#20106]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://star-history.com/`

### Category

ads

### Description

Sponsors shown on the right.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/cbddc494-0fab-4925-91ef-b6ed08fc535a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105272
 cosmetic: 39981
 scriptlet: 18603
 html: 1069
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35844-140, now
  ublock-badware: 7268-0, now
  ublock-privacy: 591-0, now
  ublock-unbreak: 2183-1, now
  ublock-quick-fixes: 223-0, now
  easylist: 71828-650, now
  easyprivacy: 33193-762, now
  urlhaus-1: 11765-0, now
  plowe-0: 3729-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1895 ms
 maxAssetCacheWait: 12 ms
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 2
  plausible.io: 1
  segment.com: 1
```
</details>

**Comment by D4niloMR** [comment]
```adb
||star-history.com/sponsors/*/logo.webp$image,1p
star-history.com##.fixed.right-0
```

**Comment by ave9858** [comment]
Works, ty

**Comment by mapx-** [comment]
report at easylist repository

@ryanbr
