### ISSUE TITLE
photopea.com: soft detection

### ISSUE THREAD

**Issue by YoshiTabletopGamer** [uBlockOrigin/uAssets#20113]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.photopea.com/`

### Category

detection

### Description

Just some soft blocker detections. (Really a continuation of previous issues)
When opening photopea, you see `www.photopea.com/img/pp_wide.png` and sometimes `www.photopea.com/img/gms/loudrider_w.jpg` on the right hand side
After exporting an image, you see the screenshot below

### Other extensions used

Used a clean Firefox profile

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/88633614/6bbdbe54-36fd-4498-9854-c87fbc18278d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 189738
 cosmetic: 128376
 scriptlet: 26616
 html: 1257
listset (total-discarded, last-updated):
 added:
  block-lan: 54-0, now
  curben-phishing: 76424-14, now
  adguard-social: 21891-925, now
  ublock-annoyances: 5503-351, now
  adguard-cookies: 27828-51, now
  adguard-popup-overlays: 24611-134, now
  adguard-mobile-app-banners: 4657-10, now
  adguard-other-annoyances: 13657-60, now
  adguard-widgets: 2328-1, now
  ublock-cookies-adguard: 337-0, now
 default:
  user-filters: 89-1, never
  ublock-filters: 35830-540, now
  ublock-badware: 7274-1, now
  ublock-privacy: 591-0, now
  ublock-unbreak: 2183-1, now
  ublock-quick-fixes: 230-0, now
  easylist: 71852-794, now
  easyprivacy: 33185-795, now
  urlhaus-1: 11930-0, now
  plowe-0: 3729-1, now
  spa-1: 5644-12, now
filterset (user): [array of 79 redacted]
hostRuleset:
 added: [array of 453 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 popupFontSize: 12px
supportStats:
 allReadyAfter: 1351 ms
 maxAssetCacheWait: 783 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(set-constant, console.clear, noopFunc)
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed the soft detection and annoyance in the annoyance list and the ad in the base list.

**Comment by YoshiTabletopGamer** [comment]
I just want to point out the Ublock configuration comes from my main browser profile, not the clean one. @JobcenterTycoon. Ok?

**Comment by JobcenterTycoon** [comment]
I was able to reproduce both issues. Force update the filterlists to get the fix.
