### ISSUE TITLE
gsuite.tools: breakage

### ISSUE THREAD

**Issue by Hitman4** [uBlockOrigin/uAssets#20118]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gsuite.tools/de/traceroute`

### Category

breakage

### Description

it dont show me the tracer points plus map

### Other extensions used

onetab,letyshops, payback, lumaly, ultra wide streming, netflix high quality, steam db

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 108050
 cosmetic: 44752
 scriptlet: 18709
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7146-0, now
  easylist: 71854-17, now
  easyprivacy: 33185-73, now
  plowe-0: 3729-1070, now
  ublock-badware: 7271-133, now
  ublock-filters: 34949-159, now
  ublock-privacy: 561-6, now
  ublock-quick-fixes: 236-95, now
  ublock-unbreak: 2137-33, now
  urlhaus-1: 12175-0, now
filterset (user): [empty]
trustedset:
 added: [array of 57 redacted]
 removed:
  chrome-scheme
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 490 ms (selfie)
 maxAssetCacheWait: 73 ms
popupPanel:
 blocked: 47
 network:
  gsuite.tools: 20
  doubleclick.net: 1
  ezodn.com: 4
  ezoic.net: 18
  googletagmanager.com: 1
  maps.googleapis.com: 1
  pubmatic.com: 1
  s-onetag.com: 1
 extended:
  ##.ezoic-ad
  ##.adtester-container
  ##[data-ez-name]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
```
</details>

**Comment by mapx-** [comment]
add

`@@||gsuite.tools/js/gtag.js$script,1p`

@ryanbr
