### ISSUE TITLE
a-o.ninja [Anti-Adblock]

### ISSUE THREAD

**Issue by bartekmad** [uBlockOrigin/uAssets#2012]
`https://a-o.ninja/anime/initial-d-fourth-stage/21`

anti-adblock

https://i.imgur.com/d3d72Mv.png

- Browser/version: Chrome 66.0.3359.117
- uBlock Origin version: 1.15.24

- default

### Notes

installed also nano defender, but doesn't help

**Comment by okiehsch** [comment]
`a-o.ninja##script:inject(set-constant.js, trap_active, false)`
You should report issues with polish websites here: https://github.com/MajkiIT/polish-ads-filter/issues

@MajkiIT

**Comment by MajkiIT** [comment]
@okiehsch thanks

https://github.com/MajkiIT/polish-ads-filter/issues/7118
