### ISSUE TITLE
pks.raenonx.cc: nuisance

### ISSUE THREAD

**Issue by Zexxx** [uBlockOrigin/uAssets#20123]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pks.raenonx.cc/en`

### Category

nuisance

### Description

> Now the website will show a popup for every 5 minutes since page load. Popup can be closed after 3.5 secs from the time when the popup shows up.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![NDyh7gGy](https://github.com/uBlockOrigin/uAssets/assets/21136842/f351c4da-942d-4666-8fad-b2f92070dc47)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105940
 cosmetic: 39991
 scriptlet: 18709
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71855-11, 7m
  easyprivacy: 33186-64, 7m
  plowe-0: 3729-1069, 7m
  ublock-badware: 7271-133, 7m
  ublock-filters: 34953-145, 7m
  ublock-privacy: 561-6, 7m
  ublock-quick-fixes: 223-84, 7m
  ublock-unbreak: 2124-31, 7m
  urlhaus-1: 12425-0, 7m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 378 ms (selfie)
 maxAssetCacheWait: 110 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##+js(no-setTimeout-if, adsFound)
```
</details>

**Comment by mapx-** [comment]
fixed in `uBlock filters – Annoyances` => enable it
