### ISSUE TITLE
Ublock runs out of memory and breaks certain shopify sites with our shopify extension 

### ISSUE THREAD

**Issue by jeff-jacobsen** [uBlockOrigin/uAssets#20128]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ublock is running out of memory and blocking our shopify extension (its a banner that shows up on the top of shopify pages) on certain shopify sites but not all shopify sites. If I go in to the ublock settings and turn off uBlock filters – Ads then the sites work fine. I don't see our site in the filter list at all so I'm not sure why its getting blocked only on certain sites. 

This site: https://trovvve.com/ gets its banner blocked and after a while ublock origin causes an out of memory exception.

This site: https://staq-testing-store.myshopify.com/ with the same shopify extension works fine.

### URL(s) where the issue occurs.

https://trovvve.com/

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/107945141/08b39613-45b0-424e-b4b4-9b72940208dd)

### Notes

Turning off uBlock filters – Ads fixes it for the sites that are crashing. Our site isn't listed in any of the filters. 

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 99160
 cosmetic: 30365
 scriptlet: 421
 html: 0
listset (total-discarded, last-updated):
 removed:
  ublock-filters: null
 default:
  user-filters: 0-0, never
  easylist: 71861-11, 27m
  easyprivacy: 33186-64, 27m
  plowe-0: 3729-1069, 27m
  ublock-badware: 7271-132, 27m
  ublock-privacy: 561-6, 27m
  ublock-quick-fixes: 226-0, 27m
  ublock-unbreak: 2124-30, 27m
  urlhaus-1: 12425-0, 27m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 429 ms (selfie)
 maxAssetCacheWait: 111 ms
```
</details>

**Comment by JobcenterTycoon** [comment]
Its caused by `||googletagmanager.com/gtag/js$script,xhr,redirect=googletagmanager_gtm.js:5` in `uBlock filters – Ads`.

I checked a few other shopify sites, no issues on my end. I added a fix for your site https://github.com/uBlockOrigin/uAssets/commit/aa8298a783ca761a267e04d88947307cad960f6b
