### ISSUE TITLE
Gmail mobile web app banner

### ISSUE THREAD

**Issue by prasetyodedy** [uBlockOrigin/uAssets#20129]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ive noticed gmail asking my phone to use the gmail app (I don't want to).
I've added filter element, but it doesn't work well blocking banner notifications

```
mail.google.com###nav
mail.google.com##.yn
mail.google.com##.xn
mail.google.com###speedbump
```

![Screenshot_20231018-033218](https://github.com/uBlockOrigin/uAssets/assets/88732071/6f8b8b4d-53a5-4217-8f94-75dcec21e760)
![Screenshot_20231018-034529](https://github.com/uBlockOrigin/uAssets/assets/88732071/222ecaca-2f9b-4e7a-808a-ba23606690ea)

### URL(s) where the issue occurs.

mail.google.com

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium Mobile: 116
filterset (summary):
 network: 178699
 cosmetic: 138079
 scriptlet: 40772
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  IDN-0: null
  easylist: null
  easyprivacy: null
  plowe-0: null
  urlhaus-1: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/102.txt: 9659-3872, 2d.16h.31m
  https://filters.adtidy.org/extension/ublock/filters/118.txt: 33186-7, 2d.16h.31m
  https://filters.adtidy.org/extension/ublock/filters/120.txt: 11269-2372, 2d.16h.31m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 73029-1863, 2d.16h.31m
  https://filters.adtidy.org/extension/ublock/filters/2.txt: 150295-18020, 2d.16h.31m
  https://filters.adtidy.org/extension/ublock/filters/208.txt: 12835-0, 2d.16h.31m
  adguard-spyware: 61463-17851, 2d.16h.31m
  adguard-spyware-url: 1251-4, 2d.16h.31m
 default:
  adguard-mobile: 8743-136, 2d.16h.31m
  ublock-badware: 7296-321, 2d.16h.31m
  ublock-filters: 35261-4605, 2d.16h.31m
  ublock-privacy: 561-138, 2d.16h.31m
  ublock-quick-fixes: 226-69, 49m
  ublock-unbreak: 2142-148, 2d.16h.31m
filterset (user): [array of 126 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4121 ms
 maxAssetCacheWait: 1429 ms
```
</details>

**Comment by mapx-** [comment]
heavily customized uBO installation (important lists removed) + not supported mobile browser => invalid

**Comment by prasetyodedy** [comment]
why invalid?

**Comment by 3kh0** [comment]
> heavily customized uBO installation (important lists removed) + not supported mobile browser => invalid

@prasetyodedy
