### ISSUE TITLE
UBO blocks Google Earth website

### ISSUE THREAD

**Issue by SteveH66** [uBlockOrigin/uAssets#20121]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I go directly to https://earth.google.com and the screen just sits there, with this 'progress circle' just endlessly looping around.  I go to www.google.com and then click on the icon with all the squares in a grid, which is the drop-down list of google 'sites' you can get to for the main site.  I go to https://earth.google.com by clicking on the link for Google Earth and I get the same spinning 'progress circle' just endlessly spinning --- no scratch that.  The wheel endlessly spins, but it **also** changes color of the spinning arrow --- green to blue to red to yellow.  But google earth never loads, just sits there at the initial screen with that loop spinning.

The only filters I am using are the uBO lists and Online Malicious URL Blocklist.  But that doesn't matter because even when I click the icon to totally turn off uBO, Google Earth website is still blocked.

### A specific URL where the issue occurs.

https://earth.google.com/web/@0,0,0a,22251752.77375655d,35y,0h,0t,0r

### Steps to Reproduce

1. Go to the website
2. Go to the website
3. Go to the website

### Expected behavior

The website to load.

### Actual behavior

The website just sits there at the splash screen, a colored 'progress circling arrow' endlessly looping around, changing colors --- green to blue to red to yellow black to green, and on and on --- ad nauseum.  You can click each and every single available item on the advanced filtering list to allow, you can click the big blue button to (supposedly) turn uBO off totally, nothing works.

### Configuration

Linux, Waterfox browser

**Comment by mapx-** [comment]
Waterfix is not officially supported, test using uBO in firefox / chrome with the default settings / lists.
also, disable all other extensions in your browser.

**Comment by okiehsch** [comment]
> even when I click the icon to totally turn off uBO, Google Earth website is still blocked.

If that's the case how do you know that uBO causes it?

**Comment by gwarser** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/886325/9017fbc5-1d05-421d-b4ce-66e2967d679a)
