### ISSUE TITLE
calltrk.com scripts should be blocked

### ISSUE THREAD

**Issue by dwolfand** [uBlockOrigin/uAssets#2013]
### URL(s) where the issue occurs
Example script url is `//cdn.calltrk.com/companies/772207126/70865b7a7db397779593/12/swap.js`

### Describe the issue
This is a tracking site that is not currently being blocked

**Comment by mapx-** [comment]
Provide a working page where we can see those scripts i action

**Comment by zaphodbeebblebrox** [comment]
`https://www.northwell.edu/` apparently.

**Comment by dwolfand** [comment]
Also, our website https://unitedincome.com/

**Comment by mapx-** [comment]
`https://cdn.calltrk.com/companies/222850263/6e0155892f15647620b8/12/swap.js`
is the same (already blocked)
`https://cdn.callrail.com/companies/334578073/48dc593fff306a965e15/12/swap.js`

so @ryanbr we could just have:
`||calltrk.com^$third-party`
in easyprivacy
