### ISSUE TITLE
quackr.io: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20131]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://quackr.io/temporary-numbers/united-states/12794992386`

### Category

detection

### Description

The site detects uBlock Origin with a big banner at the bottom to disable adblocker and it blurs the text messages received from phone numbers. I found #19025 from a few months ago, but I am not sure if the site updated its anti-adblocker or if it wasn't fixed.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screen Shot 2023-10-17 at 8 48 38 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/2aa2e7c7-7c21-492c-b532-f8f5b29e1c51">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105747
 cosmetic: 41469
 scriptlet: 22501
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5551-7, now
 default:
  user-filters: 12-2, never
  easylist: 71864-12, now
  easyprivacy: 33186-64, now
  plowe-0: 3729-1069, now
  ublock-badware: 7271-132, now
  ublock-filters: 34957-145, now
  ublock-privacy: 561-6, now
  ublock-quick-fixes: 227-91, now
  ublock-unbreak: 2125-33, now
  urlhaus-1: 11940-0, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 675 ms
 maxAssetCacheWait: 215 ms
popupPanel:
 blocked: 3
 network:
  fuseplatform.net: 2
  googletagmanager.com: 1
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce any issue. You will have to provide more details if you want help. Also be sure another extension or bad customization to uBO settings is not causing your issue.
