### ISSUE TITLE
musicmap.info: breakage

### ISSUE THREAD

**Issue by All3xJ** [uBlockOrigin/uAssets#20136]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://musicmap.info/`

### Category

breakage

### Description

Website forces to accept cookies, so with "annoyances filter" on, website is not usable.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 73850
 cosmetic: 160348
 scriptlet: 28986
 html: 1257
listset (total-discarded, last-updated):
 removed:
  easylist: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 73162-5202, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94015-82843, now
  adguard-social: 21898-723, now
  fanboy-thirdparty_social: 69-0, now
  fanboy-cookiemonster: 48616-271, now
  fanboy-social: 16251-17, now
  ublock-annoyances: 5511-11, now
 default:
  user-filters: 4-0, never
  ublock-filters: 35834-136, now
  ublock-badware: 7275-0, now
  ublock-privacy: 592-0, now
  ublock-unbreak: 2171-1, now
  ublock-quick-fixes: 230-0, 52m
  easyprivacy: 33186-724, now
  urlhaus-1: 11940-0, now
  plowe-0: 3729-1, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 454 ms (selfie)
 maxAssetCacheWait: 77 ms
popupPanel:
 blocked: 9
 network:
  doubleclick.net: 2
  facebook.net: 2
  google.com: 3
  googletagmanager.com: 1
  youtube.com: 1
 extended:
  ###privacy-policy-banner
  ##.social-media-buttons
  ##.icon-share-alt
  ###facebook-share-button
  ##a[href*="http://twitter.com/share"]
  ##.ytp-share-button
  ##.ytp-cards-teaser
  ##.ytp-paid-content-overlay
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /("mimeType":"[^"]{3\,}".*…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(trusted-replace-fetch-response, /(requiressl.*?)"adSlots.…
  #@#+js(trusted-replace-fetch-response, /(requiressl.*?)"adPlacem…
  #@#+js(trusted-replace-fetch-response, /(requiressl.*?)"playerAd…
```
</details>

**Comment by mapx-** [comment]
or 

`musicmap.info###fullscreen-overlay`

?

**Comment by mapx-** [comment]
fixed by adguard
https://github.com/AdguardTeam/AdguardFilters/commit/d2a79fe22c88ac093b7e1f4d437f25db5964d0a3
