### ISSUE TITLE
Adobe Sign SharePoint Integration: breakage

### ISSUE THREAD

**Issue by bevinduplessis** [uBlockOrigin/uAssets#20134]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The SharePoint Adobe Sign integration is being blocked 

### URL(s) where the issue occurs.

adobesign.com
adobesigncdn.com
echocdn.com
echosign.com
microsoftonline.com
sharepointonline.echosign.com

### Notes

When disabling uBlock origin Adobe sign starts working properly or adding the URLs provided to trusted sites resolves the issue.

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105973
 cosmetic: 39981
 scriptlet: 18712
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71839-11, 1d.20h.12m
  easyprivacy: 33224-64, 5d.21h.8m
  plowe-0: 3726-1065, 5d.21h.8m
  ublock-badware: 7265-133, 19h.23m
  ublock-filters: 34951-145, 19h.22m
  ublock-privacy: 559-6, 5d.21h.8m
  ublock-quick-fixes: 215-76, 3h.18m
  ublock-unbreak: 2137-31, 19h.21m
  urlhaus-1: 12425-0, 15h.20m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 414 ms (selfie)
 maxAssetCacheWait: 118 ms
```
</details>

**Comment by mapx-** [comment]
You have to provide step by steps examples for all the broken pages / functionalities.

**Comment by ryanbr** [comment]
We have no new adobe filters here, is there specific urls being blocked?
