### ISSUE TITLE
freereceivesms.com: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20133]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.freereceivesms.com/en/`

### Category

detection

### Description

"AdBlock detected!" window appears on the page and can't exit out of it. I used the filter `@@||freereceivesms.com/clever_ads.js$script,1p` inspired from f25ee4d and it seems to fix the detection.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1440" alt="Screen Shot 2023-10-17 at 11 21 41 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/7ba7d22a-1d66-45df-85fe-98d8408b8fb4">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105755
 cosmetic: 41472
 scriptlet: 22493
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5551-7, 21m
 default:
  user-filters: 13-2, never
  easylist: 71873-12, 21m
  easyprivacy: 33186-64, 21m
  plowe-0: 3729-1069, 21m
  ublock-badware: 7271-132, 21m
  ublock-filters: 34951-145, 21m
  ublock-privacy: 561-6, 21m
  ublock-quick-fixes: 217-82, 21m
  ublock-unbreak: 2125-33, 21m
  urlhaus-1: 11940-0, 21m
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 675 ms
 maxAssetCacheWait: 215 ms
popupPanel:
 blocked: 4
 network:
  freereceivesms.com: 1
  addthis.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##+js(no-setInterval-if, 0x)
```
</details>

**Comment by D4niloMR** [comment]
Try:
`freereceivesms.com##+js(aopw, decodeURIComponent)`

Also remove anti-devtool

**Comment by huyszn** [comment]
> Try: `freereceivesms.com##+js(aopw, decodeURIComponent)`
>
This works.
> Also remove anti-devtool
>
How do I do this?

**Comment by D4niloMR** [comment]
> How do I do this?

Sorry, typo. Updated comment
