### ISSUE TITLE
Upgrading EasyList to v2.0 instead of v1.1

### ISSUE THREAD

**Issue by ddavydenko** [uBlockOrigin/uAssets#2014]
### URL(s) where the issue occurs

This issue is not specific to any particular URL.

### Describe the issue

Currently uBlock seems to be using EasyList v1.1: chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=easyprivacy. While ABP, for example, is using v2.0 of EasyList: https://easylist-downloads.adblockplus.org/easylist.txt. I wonder if it is possible to switch uBlock to use v2.0 of EasyList. There are differences between those versions.

### Screenshot(s)

N/A

### Versions

- Browser/version: Chrome v65.0.3325.181 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.15.24

### Settings

Default settings are used

### Notes

N/A

**Comment by zaphodbeebblebrox** [comment]
You appear to have confused EasyList and EasyPrivacy. EasyList is using 2.0, EasyPrivacy is using version 1.1.

**Comment by ddavydenko** [comment]
Interesting. Is there a way to file a request to modify rules in EasyPrivacy? Is it just via pull requests?

**Comment by mapx-** [comment]
easylist / easyprivacy https://github.com/easylist/easylist/issues
