### ISSUE TITLE
smsonline.cloud: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20146]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.smsonline.cloud/`

### Category

detection

### Description

The site detects uBlock Origin where you have to whitelist the site to use the site or you have to solve a math problem to continue using the site but only 20 times.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
<img width="1440" alt="Screen Shot 2023-10-18 at 4 58 37 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/8fa9dfa3-d850-4eea-a4eb-9110fbf2b5f8">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104204
 cosmetic: 41404
 scriptlet: 22498
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5550-7, now
 default:
  user-filters: 13-2, never
  easylist: 71825-15, now
  easyprivacy: 33186-64, now
  plowe-0: 3729-1069, now
  ublock-badware: 7270-132, now
  ublock-filters: 34966-145, now
  ublock-privacy: 562-6, now
  ublock-quick-fixes: 224-86, now
  ublock-unbreak: 2125-33, now
  urlhaus-1: 10360-0, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 675 ms
 maxAssetCacheWait: 215 ms
popupPanel:
 blocked: 5
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  stpd.cloud: 2
```
</details>

**Comment by gorhill** [comment]
This works:

    @@||pagead2.googlesyndication.com^$3p,xhr,method=head,domain=smsonline.cloud

I couldn't find a way without letting the bait request through.

**Comment by huyszn** [comment]
The site is detecting uBO again.

<img width="1440" alt="Screen Shot 2023-10-29 at 12 05 41 AM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/9c95c862-7358-4ba4-8d58-bdd5457ce198">

**Comment by gorhill** [comment]
Also can't reproduce.

**Comment by huyszn** [comment]
There is new detection.
(https://github.com/uBlockOrigin/uAssets/assets/46979193/dc825afe-6641-4728-9e53-aae8bdc1418b)
