### ISSUE TITLE
thenovbharattimes.com: detection

### ISSUE THREAD

**Issue by firehawkx** [uBlockOrigin/uAssets#20140]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://thenovbharattimes.com/?lid=fYVUUd3&pid=864676&plid=12&vid=220413714`

### Category

detection

### Description

Says "AdBlocker Detected!,

Dear visitor, it seems that you are using an adblocker please take a moment to disable your AdBlocker it helps us pay our publishers and continue to provide free content for everyone.

Please note that the Brave browser is not supported on our website. We kindly request you to open our website using a different browser to ensure the best browsing experience.

Thank you for your understanding and cooperation.
Once, You're Done? Reload page!"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ublock-detected](https://github.com/uBlockOrigin/uAssets/assets/27733682/a7c229b5-d195-479f-823b-eb2802765ea6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 103882
 cosmetic: 40002
 scriptlet: 18606
 html: 1069
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 35841-131, 4m
  ublock-badware: 7275-0, 4m
  ublock-privacy: 592-0, 4m
  ublock-unbreak: 2171-2, 4m
  ublock-quick-fixes: 221-0, 4m
  easylist: 71875-692, 4m
  easyprivacy: 33186-720, 4m
  urlhaus-1: 10360-0, 4m
  plowe-0: 3729-1, 4m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 461 ms (selfie)
 maxAssetCacheWait: 82 ms
popupPanel:
 blocked: 7
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 3
```
</details>

**Comment by firehawkx** [comment]
This was my very first report so i hope i did it right...

was this last checkbox a trick question?
 I did not answer truthfully to ALL the above checkpoints --- by checking that would mean i am dishonest.. which i am not ;)

**Comment by mapx-** [comment]
as you can see from the above commit there are a lot of similar domains, so just added the new one.

**Comment by Omega-6** [comment]
`https://gplinks.co/c6uVB`
`https://github.com/AdguardTeam/AdguardFilters/issues/167937`

**Comment by D4niloMR** [comment]
@mapx- the filter `@@||googlesyndication.com^$script,xhr` is required on your side?

**Comment by mapx-** [comment]
working even without that exception (tested in chrome)
