### ISSUE TITLE
tmearn.com

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#2015]
### URL(s) where the issue occurs

`https://tmearn.com/E9T25`

### Describe the issue

Since tmearn is added to the timer skipping list, the timer is skipped but it's impossible to get to the target link with UBO enabled.
With UBO disabled, it works / the 'Get Link' button appears.

**Comment by adranger** [comment]
@mapx- it now shows a fake download button (try the same link that was already posted).

**Comment by ghajini** [comment]
`tmearn.com/V39V27`
3rd party tracking
