### ISSUE TITLE
businesstech.co.za: breakage

### ISSUE THREAD

**Issue by ivovegter** [uBlockOrigin/uAssets#20157]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On businesstech.co.za, a South African news site, some filter deletes the div containing social shares to the left of the article, but that also deletes the article's metadata (section, byline and date).

It looks to me like the filter deletes <div class="sticky-top">...</div>, but that includes <div class="entry-meta">...</div>, which contains the article metadata and must be retained. The filter should delete only <div class="d-flex justify-content-between mt-3">...</div>, which would delete only the social share buttons.

### URL(s) where the issue occurs.

`https://businesstech.co.za/news/business/725518/pick-n-pay-in-trouble-as-load-shedding-and-increased-competition-tank-profits/`
`https://businesstech.co.za/news/business/311226/government-to-regulate-airbnb-in-south-africa/`

### uBO version

1.52.2

### Browser name and version

Firefox 118.0.2

### Settings

None.

**Comment by 3kh0** [comment]
It is not removing any part of the article, can you provide more proof to where it is being removed?

**Comment by gwarser** [comment]
This?

![image](https://github.com/uBlockOrigin/uAssets/assets/886325/ac026122-93d5-46e5-93e9-3ff4ab155eb9)

**Comment by gwarser** [comment]
```
Filter##.sticky-social-share
Filter list
[EasyList – Social Widgets](moz-extension://df8d2b15-7f04-4b2d-ad2e-9fb1b5e7d0b1/asset-viewer.html?url=fanboy-social)
```

**Comment by ivovegter** [comment]
Filtering sticky-social-share would do it. 

After disabling all extensions, toggling uBlock on and off makes that metadata block disappear and reappear. On a new Firefox profile, however, with only uBlock installed, the page looks fine. I'm going to re-add my extensions to the new profile, and hope it stays that way. Will reopen the issue if it breaks again.

**Comment by ivovegter** [comment]
Filtering sticky-social-share would do it, since it contains that metadata div. 

With all other extensions disabled, toggling uBlock on an off makes that metadata block disappear and reappear. Curiously, on a new profile with only uBlock installed, it does not do that, and the page looks fine. I'll re-add my extensions to the new profile, and hope it stays that way. Sorry for wasting your time.
