### ISSUE TITLE
[nsfw] linkvertise.com: detection

### ISSUE THREAD

**Issue by BRR34L0RD** [uBlockOrigin/uAssets#20153]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkvertise.com/152666/fluxus-windows-check-1/1`

### Category

detection

### Description

Another annoying anti-adblock stupid measure.

### Other extensions used

(none)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/129367686/3da6a99e-473c-4ee8-acf8-5ec891a769a5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 110289
 cosmetic: 86334
 scriptlet: 25696
 html: 1257
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27849-52, 12m
  ublock-cookies-adguard: 339-0, 12m
  adguard-other-annoyances: 13672-301, 12m
  easylist-annoyances: 3997-92, 12m
  easylist-notifications: 2952-4, 12m
  ublock-annoyances: 5510-365, 12m
 default:
  user-filters: 0-0, never
  ublock-filters: 35849-467, 14m
  ublock-badware: 7274-0, 14m
  ublock-privacy: 592-0, 14m
  ublock-unbreak: 2171-2, 14m
  ublock-quick-fixes: 222-0, 14m
  easylist: 71854-775, 14m
  easyprivacy: 33186-824, 13m
  urlhaus-1: 11775-0, 13m
  plowe-0: 3729-1, 13m
  spa-1: 5649-13, 14m
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3123 ms
 maxAssetCacheWait: 1870 ms
popupPanel:
 blocked: 18
 network:
  bizseasky.com: 10
  googletagmanager.com: 1
  media.net: 2
  taboola.com: 2
  thinksuggest.org: 2
  typekit.net: 1
 extended:
  ##+js(json-prune, data.meta.require_addon data.meta.require_vide…
  ##+js(abort-current-script, addEventListener, DOMNodeRemoved)
  ##+js(abort-current-script, document.dispatchEvent, CustomEvent)
  ##+js(abort-current-script, onload, adsbygoogle)
  ##+js(addEventListener-defuser, load, nextFunction)
  ##+js(json-prune, data.meta.require_addon data.meta.require_capt…
  ##+js(nano-setInterval-booster)
  ##+js(set-constant, isAdBlockActive, false)
  ##+js(abort-current-script, document.addEventListener, /google_a…
```
</details>

**Comment by BlazeFTL** [comment]
@BRR34L0RD This Is IP Problem... Contact Your ISP Or Get A VPN That Has Good IP's)

**Comment by BRR34L0RD** [comment]
> @BRR34L0RD This Is IP Problem... Contact Your ISP Or Get A VPN That Has Good IP's)

Thanks, I will do more tests here.

**Comment by BRR34L0RD** [comment]
I tested with NextDNS, AdGuardDNS and PaladinVPN (separately, of course). Nothing worked.

**Comment by BlazeFTL** [comment]
@BRR34L0RD As I Said You Might Need Something Like Nord Or Other Good Paid VPN Who Has Non Flagged IP...But Try Asking Your Internet Service Provider For A Fix

**Comment by BRR34L0RD** [comment]
There is not any chance to pay for a VPN. I am pwned by those morons!!! -_-

**Comment by Windowszin** [comment]
same problem, but im not using a VPN

**Comment by mapx-** [comment]
link ? 
Troubleshooting Information ? (dashboard, support tab)
