### ISSUE TITLE
dumpert.nl: detection

### ISSUE THREAD

**Issue by Waxli** [uBlockOrigin/uAssets#20150]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dumpert.nl/?selectedId=100074481_6b06c880`

### Category

detection

### Description

It shows "JE MAAKT GEBRUIKT VAN EEN PLUGIN DIE DEZE EMBED BLOKKEERT. KLIK[ HIER ](https://twitter.com/user/status/1714702334410846219)OM HET ITEM TE BEKIJKEN."

**YOU ARE USING A PLUGIN THAT BLOCKS THIS EMBED. CLICK HERE TO VIEW ITEM**

### Other extensions used

Ghostery and bitdefender tracker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1663" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/82279449/f624c434-ecdd-4062-b4ac-bbb06f2faaa2">

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 201796
 cosmetic: 142686
 scriptlet: 29296
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1m
  NLD-0: 2701-23, 2m
  adguard-cookies: 27849-1591, 2m
  adguard-mobile-app-banners: 4689-17, 2m
  adguard-other-annoyances: 13672-14, 2m
  adguard-popup-overlays: 24834-103, 2m
  adguard-social: 21898-2064, 2m
  adguard-widgets: 2329-38, 1m
  curben-phishing: 75827-5, 1m
  dpollock-0: 11583-6, 1m
  easylist-annoyances: 3997-1065, 1m
  easylist-chat: 141-20, 1m
  [8 lists not shown]: [too many]
 default:
  user-filters: 7-0, never
  easylist: 71959-16270, 1m
  easyprivacy: 33186-276, 1m
  plowe-0: 3729-1444, 1m
  ublock-badware: 7270-141, 1m
  ublock-filters: 34969-742, 1m
  ublock-privacy: 562-8, 27m
  ublock-quick-fixes: 227-89, 1m
  ublock-unbreak: 2125-38, 1m
  urlhaus-1: 10360-1, 1m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 82 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 10 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1237 ms (selfie)
 maxAssetCacheWait: 665 ms
popupPanel:
 blocked: 10
 network:
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  jwpltx.com: 1
  mediahuis.be: 2
  nu.nl: 1
  pbstck.com: 1
  scorecardresearch.com: 2
 extended:
  ##.grid_ad_container
  ##+js(no-setTimeout-if, AdBlockerCheck)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
> Ghostery and bitdefender tracker

- disable those extensions
- if still does not work reset uBO to default lists / settings, do not add other lists (other then regional NLD list), test again
