### ISSUE TITLE
mathcrave.com: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20156]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mathcrave.com/angle-between-vectors-in-3d-calculator/`

### Category

detection

### Description

This page detects uBlock Origin. You might have to scroll up and down the page for a few seconds for the "AdBlock Detected" message to pop up. The strange thing is that some other pages on this website don't detect uBlock Origin. For example, the website doesn't detect uBlock Origin on`https://mathcrave.com/differential-equations-solver/`, but it does detect it on `https://mathcrave.com/angle-between-vectors-in-3d-calculator/` and `https://mathcrave.com/calculus-worksheets-generator/`

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1437" alt="Screen Shot 2023-10-19 at 5 34 11 AM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/cf9e995b-519d-478d-b534-8752878b3580">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105601
 cosmetic: 41542
 scriptlet: 22503
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5550-7, 1h.25m
 default:
  user-filters: 14-3, never
  easylist: 71968-15, 1h.25m
  easyprivacy: 33158-64, 1h.25m
  plowe-0: 3729-1069, 1h.25m
  ublock-badware: 7270-132, 1h.25m
  ublock-filters: 34976-146, 1h.25m
  ublock-privacy: 562-6, 1h.25m
  ublock-quick-fixes: 227-89, 1h.25m
  ublock-unbreak: 2125-33, 1h.25m
  urlhaus-1: 11775-0, 1h.25m
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 675 ms
 maxAssetCacheWait: 215 ms
popupPanel:
 blocked: 66
 network:
  mathcrave.com: 22
  cloudflareinsights.com: 2
  doubleclick.net: 2
  ezoic.net: 22
  google.com: 12
  googlesyndication.com: 2
  googletagmanager.com: 1
  infolinks.com: 2
  youtube.com: 1
 extended:
  ##ins.adsbygoogle
  ##div[id^="ezoic-pub-ad-"]
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /("lastModified":"[^"]{3}.…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by okiehsch** [comment]
Does adding
`mathcrave.com##+js(nostif, onDetected)`
work for you?

**Comment by JobcenterTycoon** [comment]
Works for me. I also see many annoyances (disabled F-Keys, contextmenu, ...). A other way can be to just block the anti adblock script and the content protector script:

```
||mathcrave.com/core/modules/*/assets/vendor/js/abdetector.script.min.js
||mathcrave.com/core/modules/*/assets/vendor/js/content-protector.min.js
!#if cap_html_filtering
mathcrave.com##^script:has-text(disable_show_error)
!#else
mathcrave.com##+js(rmnt, script, disable_show_error)
!#endif
```

**Comment by huyszn** [comment]
@JobcenterTycoon 's filter works all the time. @okiehsch 's filter sometimes works and sometimes doesn't work when I tried testing each filter separately.

**Comment by JobcenterTycoon** [comment]
Fixed now.
