### ISSUE TITLE
duckprintspress.com: breakage

### ISSUE THREAD

**Issue by DaleStan** [uBlockOrigin/uAssets#20167]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://duckprintspress.com/shop/checkout/`

### Category

breakage

### Description

When clicking the ~~checkout~~ Place Order button, nothing happens, even after clicking the button several times.

After disabling uBO and reloading the page, the checkout button presents a circle-of-dots spinner, I am redirected to a order success page, and I got an order-confirmation email.

### Other extensions used

NoScript: All scripts permitted (stripe.com and stripe.network permanently, others temporarily) on this page.
Privacy Badger: Enabled with the same (default, I believe) configuration both when the checkout button worked and when it did not.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105140
 cosmetic: 40067
 scriptlet: 18609
 html: 1071
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 35870-236, 1m
  ublock-badware: 7259-0, 1m
  ublock-privacy: 582-0, 1m
  ublock-unbreak: 2171-2, 1m
  ublock-quick-fixes: 223-0, 34m
  easylist: 71974-552, 1m
  easyprivacy: 33143-762, 1m
  urlhaus-1: 11630-0, 1m
  plowe-0: 3729-1, 1m
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 156 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel:
 blocked: 73
 network:
  sift.com: 1
  stripe.com: 66
  wp.com: 6
```
</details>

**Comment by gorhill** [comment]
I don't have an account with that site, but when I clicked check out afte radding an item, I was shown the checkout page at `https://duckprintspress.com/shop/checkout/`.

You have custom filters, other extensios, and you said:

> - [x] I did not answer truthfully to ALL the above checkpoints.

So you will have to go through the steps and actually truthfully perform them, otherwise we will be unable to narrow down where exactly it's failing.

**Comment by mapx-** [comment]
@DaleStan you have to completely disable all other extensions / addons.

However, follow all these steps:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

For now closing the issue, just comment here if you need some help.

**Comment by DaleStan** [comment]
>I don't have an account with that site, but when I clicked check out after adding an item, I was shown the checkout page at `https://duckprintspress.com/shop/checkout/`.

The checkout page shows up fine; the nothing-happens breakage doesn't appear until I actually click the checkout button.

I'm willing to go through the full list of steps, but I'll need some guidance on how to click the checkout button without spamming the poor site with a bunch of orders that I'll then have to cancel.

**Comment by mapx-** [comment]
- if you landed on the checkout page you already clicked the `checkout button`
- in the checkput page you can fill out all that info, maybe you are saying nothing happens when you click `place order` button ?

**Comment by DaleStan** [comment]
Augh, yes. Nothing happens when I click the Place Order button, not the checkout button.

**Comment by mapx-** [comment]
if I click place order wihput filling out that info the page is scrolling to the top, do you get the same behaviour ?

once again => **Did you follow all the steps above ?**
