### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by larsgw** [uBlockOrigin/uAssets#20160]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/`

### Category

ads

### Description

Audio-based ads appear as of today, as well as visual ads in the "Playing now" sidebar (where the album cover normally displays).

### Other extensions used

Zotero, ModHeader, EZProxy, WaybackMachine

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Apologies for the Dutch interface.

![Screenshot_20231019_143910](https://github.com/uBlockOrigin/uAssets/assets/14018963/6bf434d8-823f-41d6-96a5-502c959da2e9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105307
 cosmetic: 40065
 scriptlet: 18721
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 71968-15, 19m
  easyprivacy: 33143-64, 19m
  plowe-0: 3729-1069, 19m
  ublock-badware: 7270-132, 19m
  ublock-filters: 34983-146, 19m
  ublock-privacy: 562-6, 19m
  ublock-quick-fixes: 230-88, now
  ublock-unbreak: 2125-32, 19m
  urlhaus-1: 11775-0, 19m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 419 ms (selfie)
 maxAssetCacheWait: 143 ms
popupPanel:
 blocked: 11
 network:
  doubleclick.net: 4
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 5
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by okiehsch** [comment]
On my end the ads are still skipped skipped in a second or two.

**Comment by mapx-** [comment]
The audio ads are blocked on my side

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/7e2ec2aa-2f16-47d8-8ef5-998153777a5f)

Open the uBO logger, reproduce the ads and see in the logger if there are unblocked media items 

As for the ads on the right side they are disappearing quickly (when the audio ads are blocked) so I cannot provide a filter.

**Comment by larsgw** [comment]
I also saw those log entries (same colors) but I still got an ad. The ads on the right side normally also disappear quickly, but not this time. I will reply with logs when I have them again.

**Comment by larsgw** [comment]
![Screenshot_20231019_145821](https://github.com/uBlockOrigin/uAssets/assets/14018963/2ad956f1-20d2-493e-aeda-ea0b38cb317b)

**Comment by larsgw** [comment]
The ad audio already seems to be loaded before the first `doubleclick.net` request.

**Comment by mapx-** [comment]
I said `media` items

It seems on your side you have different `media` items, try this filter:

`||spotifycdn.com/audio/$media,redirect=noop-1s.mp4:10,domain=open.spotify.com`

**Comment by larsgw** [comment]
I will, thank you.

**Comment by Raingram** [comment]
> I said `media` items
> 
> It seems on your side there are different `media` items, try this filter:
> 
> `||spotifycdn.com/audio/$media,redirect=noop-1s.mp4:10,domain=open.spotify.com`

I also started hearing the ads today and this fixed it for me.

**Comment by randomname-1** [comment]
I am having this issue, how do I add that specific filter? New to using special filters

**Comment by Ostainia** [comment]
I've got the same as above, no experience with custom filters

**Comment by bamojamo** [comment]
> I am having this issue, how do I add that specific filter? New to using special filters

Click on the extension in the browser, then the three gears that say "Open the dashboard" when you hover over it.

![Screenshot (21)](https://github.com/uBlockOrigin/uAssets/assets/148517749/19c8f9e5-ec27-48f0-9c9a-971c4675cee8)

![Screenshot (22)](https://github.com/uBlockOrigin/uAssets/assets/148517749/faa3dcc9-008f-468e-a5e1-abe09f160418)

Now that dashboard is open, click on the "My filters" tab, then paste "||spotifycdn.com/audio/$media,redirect=noop-1s.mp4:10,domain=open.spotify.com"

Click "Apply changes."

![Screenshot (23)](https://github.com/uBlockOrigin/uAssets/assets/148517749/90740ba2-69ca-4c23-a775-6b0243a90cbb)

Reload the Spotify page and it should now be working.

**Comment by randomname-1** [comment]
Thank you, will report back if issue persists after this

**Comment by mapx-** [comment]
It was already added to the uBO lists, just update all your lists.

**Comment by THEtomaso** [comment]
@mapx-:

> https://github.com/uBlockOrigin/uAssets/commit/de1a616164d3ac5930a458e6851ed0c20047a58c

**Issue:**
This breaks some embedded Spotify streams.

**Example (scroll down 2/3)**:
`https://shakirabrasil.com/2024/09/descubra-o-possivel-patrocinador-dos-shows-de-shakira-no-brasil/`

**Comment by stephenhawk8054** [comment]
It plays fine for me

**Comment by THEtomaso** [comment]
@stephenhawk8054:
I retested this now, and it seems to be browser dependent.
For me, it does indeed play in Chromium-ungoogled (Chrome), but NOT in LibreWolf (Firefox)!

**Comment by stephenhawk8054** [comment]
Did you test in normal Firefox?

**Comment by THEtomaso** [comment]
No.
I'm using LibreWolf in Standard Protection Mode, so it should behave identically to Firefox anyway.
Badfiltering the problem rule fixes the issue for me, and since I'm not actually using Spotify, or even care about those streams personally, I don't think I'll be troubleshooting this issue any further.

**Comment by stephenhawk8054** [comment]
If I'm not wrong, Librewolf has specific issue with Spotify, and the issue is in their repositories as well. I'm unable to reproduce in Firefox.

**Comment by THEtomaso** [comment]
Hmm..
OK, I'll take another look at it then.

**Comment by THEtomaso** [comment]
OK, so when I badfilter the rule that I mentioned, it plays, but it's actually a different stream than the one that plays in Chromium-ungoogled.
Instead of the music track, there's a dude that talks in Spanish.
Perhaps it's a DRM issue (Google Widevine), in which case; I'm pleased that it's broken! :)

**Comment by stephenhawk8054** [comment]
>  Instead of the music track, there's a dude that talks in Spanish.

I suspect that is the ads itself. I guess there are some issues of redirecting the ads to noop mp4 in Librewolf.

**Comment by stephenhawk8054** [comment]
Anyways, since I can't really reproduce the issue, I'll close for now.

**Comment by xigzagoon** [comment]
Audio ads started playing for me and showing in the sidebar today.
I'm on Firefox Version 136.0.3 (64-bit) and double-checked that my filters are the up-to-date default ones

**Comment by stephenhawk8054** [comment]
@xigzagoon Please continue here: https://github.com/uBlockOrigin/uAssets/issues/22198#issuecomment-2756650740
