### ISSUE TITLE
atresplayer.com: detection

### ISSUE THREAD

**Issue by NormandyEPG** [uBlockOrigin/uAssets#20166]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.atresplayer.com/`

### Category

detection

### Description

entering to the site detecting the adblocker

### Other extensions used

no one

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 107698
 cosmetic: 46318
 scriptlet: 19117
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71983-15, 26m
  easyprivacy: 33186-64, 26m
  plowe-0: 3729-1069, 26m
  spa-0: 3750-19, 26m
  spa-1: 5656-225, 26m
  ublock-badware: 7270-132, 26m
  ublock-filters: 34988-177, 26m
  ublock-privacy: 562-6, 25m
  ublock-quick-fixes: 229-87, 25m
  ublock-unbreak: 2125-34, 25m
  urlhaus-1: 11630-0, 25m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 707 ms
 maxAssetCacheWait: 11 ms
popupPanel:
 blocked: 10
 network:
  adsrvr.org: 1
  amazon-adsystem.com: 1
  atresmedia.com: 1
  doubleclick.net: 1
  everesttech.net: 1
  imasdk.googleapis.com: 1
  mathtag.com: 1
  richaudience.com: 1
  scorecardresearch.com: 1
  spotxchange.com: 1
 extended:
  ###root main[class] > div[class] > section[class] + aside[class]…
  ##+js(nano-setTimeout-booster, [native code], 5000)
  ##+js(no-fetch-if, doubleclick)
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce detection when visiting `https://www.atresplayer.com/`.

**Comment by NormandyEPG** [comment]
My apologies because I thought I had attached a couple of photos.

Last night I got the notice/pop up, with uBlock activated, but now I can't replicate it either... :(

For now, in the first photo I still get the active adBlocker warning, even though it is deactivated and I do not have any other active extension except for those two that appear in the image.

<img width="1920" alt="11" src="https://github.com/uBlockOrigin/uAssets/assets/33192349/304eb712-a75c-4313-96e3-c65150a97a57">


But now with it activated nothing appears directly, the website loads and suddenly all the content is hidden.

<img width="1920" alt="22" src="https://github.com/uBlockOrigin/uAssets/assets/33192349/c4156df3-cd51-48ec-b120-1777de087c92">


I have tried to make a content filter to block but I can't figure out what blocks the content from behind.


```
- ||imagenes.atresplayer.com/atp/clipping/cmsimages02/2023/07/03/CF20B22F-6BA6-4209-ACA6-4C196052EB45//720x540.jpg$image
- www.atresplayer.com##.kTcLan.style__StyledWrapperButtons-sc-172oy2y-10
- www.atresplayer.com##.idGkRr.style__StyledContentAdBlocker-sc-172oy2y-2
- ||imagenes.atresplayer.com/atp/clipping/cmsimages01/2023/09/06/0254317C-059A-4EB3-B5C4-0564D043C547//295x166.jpg$image
- www.atresplayer.com##.jtsvZr.style__StyledAdBlocker-sc-172oy2y-0.ddhVJO.style__StyledModalContent-sc-1wr0y1r-3
- www.atresplayer.com##.modal-enter-done.ihnhgX.style__StyledModalWrapper-sc-1wr0y1r-2
```

**Comment by mapx-** [comment]
@NormandyEPG 

do you still get the detection ? if yes, is an account required ?

**Comment by NormandyEPG** [comment]
With every step it gets worse. I have disabled all extensions and the website, even with private browsing, tells me that I use adblock and I should deactivate it. I have even tried Chrome, Opera and of course, the browser I am using, Mozilla.

Well, for now, if I use uBlock Origin, it blocks ads, pop-ups but again a black screen where I can't navigate or see anything.

I have tested with another adblock and blocking elements like

```
atresplayer.com##.style__StyledContentAdBlocker-sc-172oy2y-2.idGkRr
atresplayer.com##.style__StyledModalContent-sc-1wr0y1r-3.ddhVJO.style__StyledAdBlocker-sc-172oy2y-0.jtsvZr
atresplayer.com##.style__StyledModalWrapper-sc-1wr0y1r-2.ihnhgX.modal-enter-done
```

I can see the content, although in a limited way because the website blocks scrolling. But I don't want to use another adblock, my interest is to give feedback to the one I've been using regularly for years!


@mapx-  yep... Atresplayer is the web/app of a private but public television channel. There are completely free content of broadcast programs that can be accessed even without an account and other content such as television series or programs, which have not yet premiered on the lineal channel.

Until a few days ago I have been watching episodes of an old series without problem.

But I don't know if it is due to geolocation or a detection that is too intrusive, even giving a false positive for adblock, now it is totally impossible to see anything. And when uBlock Origin does its job, it seems to stop loading the web, (the black screen)

I can't give much technical detail but as far as possible I can try or try anything :)

**Comment by mapx-** [comment]
- do you get the detection ONLY when you are watching not-free-content ?

**Comment by gorhill** [comment]
> There are completely free content of broadcast programs that can be accessed even without an account and other content such as television series or programs

You have URLs for these? Whatever I try to play, I don't get detection but a get a overlay telling me it's HAZTE PREMIUM. I am using a VPN for Spain.
