### ISSUE TITLE
lookiero.de: breakage

### ISSUE THREAD

**Issue by theHumaNative** [uBlockOrigin/uAssets#20168]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There's a picture pile where you're supposed to slide over the pics in order to choose. 
Yeay or Nay - similar to the truffls App.
Problem: No pic visible. I can't decide over something invisible. XD

### URL(s) where the issue occurs.

`https://lookiero.de/user/my-lk`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/79917978/c12ed52a-d987-4c0a-a528-fe50b5c625e7

### uBO version

1.52.2

### Browser name and version

Firefox 118.2.0

### Settings

I resetted it - so let's say zero.

### Notes

Reset the Addin, checked if it's the latest version, even switched the app blocker off totally.

**Comment by gorhill** [comment]
Please provide troubleshooting information while on the site:

  Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)
