### ISSUE TITLE
video.gjirafa.com: breakage

### ISSUE THREAD

**Issue by riadasllani** [uBlockOrigin/uAssets#20174]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://video.gjirafa.com/`

### Category

breakage

### Description

When uBlockOrigin is running, I can't load more rows with content to homepage, there are only to sections that are loaded by default, and there is nothing more loaded there.

There is some script from video.gjirafa.com that is being blocked by this rule: video.gjirafa.com##+js(json-prune, 0)

And this script has the code to load more homepage sections?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
![image](https://github.com/uBlockOrigin/uAssets/assets/20195346/0978278d-50af-46b0-ad88-ae97b71bde80)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104511
 cosmetic: 40017
 scriptlet: 18688
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
 default:
  user-filters: 17-0, never
  easylist: 71987-15, now
  easyprivacy: 33148-64, now
  plowe-0: 3729-1070, now
  ublock-badware: 7255-132, now
  ublock-filters: 34994-146, now
  ublock-privacy: 588-6, now
  ublock-unbreak: 2125-30, now
  urlhaus-1: 10980-0, now
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 195 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
switchRuleset:
 added: [array of 20 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 662 ms (selfie)
 maxAssetCacheWait: 166 ms
popupPanel:
 blocked: 6
 network:
  gjirafa.com: 1
  clarity.ms: 1
  facebook.net: 1
  gjirafa.tech: 2
  google-analytics.com: 1
 extended:
  ##[id^="gjc"]
  ##+js(json-prune, 0)
```
</details>

**Comment by okiehsch** [comment]
Caused by `video.gjirafa.com##+js(json-prune, 0)`
Not sure if that filter is still necessary.
For now add
`video.gjirafa.com#@#+js(json-prune, 0)`
to your filter list.
