### ISSUE TITLE
go.tlc.com ads

### ISSUE THREAD

**Issue by fmunim** [uBlockOrigin/uAssets#20172]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I am still seeing ads on go.tlc.com videos. I have checked old issues but they all seemed closed? Any help would be appreciated!

### Debug Info:
```
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 282558
 cosmetic: 236628
 scriptlet: 45570
 html: 1257
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 73081-73081, 2d.23h.50m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 22h.4m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 22h.7m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 93998-93992, 2d.23h.50m
  https://winhelp2002.mvps.org/hosts.txt: 8729-3, 2d.23h.50m
  https://www.fanboy.co.nz/enhancedstats.txt: 2771-7, 2d.23h.50m
  adguard-generic: 78610-6791, 2d.23h.50m
  adguard-mobile: 8746-153, 2d.23h.50m
  adguard-social: 21891-882, 2d.23h.50m
  fanboy-thirdparty_social: 68-0, 2d.23h.50m
  fanboy-cookiemonster: 48600-3881, 2d.23h.50m
  fanboy-social: 16251-27, 2d.23h.50m
  [17 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 35831-523, 2d.23h.50m
  ublock-badware: 7275-5, 2d.23h.50m
  ublock-privacy: 591-0, 2d.23h.50m
  ublock-unbreak: 2183-3, 2d.23h.50m
  easylist: 71852-1116, 2d.23h.50m
  easyprivacy: 33185-1113, 2d.23h.50m
  plowe-0: 3729-326, 2d.23h.50m
  urlhaus-1: 11775-0, 22h.6m
  ublock-quick-fixes: 225-0, 36m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 164 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 428 ms (selfie)
 maxAssetCacheWait: 340 ms
```

### URL(s) where the issue occurs.

`https://go.tlc.com/video/90-day-fiance-tlc-atve-us/dearly-beloved`

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/32178410/090ebb99-5a07-4c1f-9ef4-9821f252d670

### uBO version

1.52.2

### Browser name and version

Firefox 118.0.2

### Settings

N/A

**Comment by playonevideo** [comment]
On `https://go.tlc.com/video/people-magazine-investigates-investigation-discovery/vanished-in-the-heartland` if you click the play button, the video loads but you can't scroll on the player as it plays an "ad", that is the actual episode.

https://github.com/user-attachments/assets/14040611-bad7-49da-9793-445ed1f030d9
https://github.com/user-attachments/assets/9aaafb0c-1f50-4b16-88d0-956b0e631e6f

US IP needed.
