### ISSUE TITLE
[nsfw] 3dporndude.com: popups

### ISSUE THREAD

**Issue by soskamified** [uBlockOrigin/uAssets#20175]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [x] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://3dporndude.com/`

### Category

popups

### Description

Blank popups appear whenever any part of the site is clicked and occasionally also redirects to a different address. The popups appear on every page, including the home page, but the redirect only seems to occur when attempting to play videos, and does not occur on every video.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 114826
 cosmetic: 190094
 scriptlet: 29298
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27877-31, now
  adguard-mobile-app-banners: 4688-9, now
  adguard-other-annoyances: 13678-7, now
  adguard-popup-overlays: 24850-61, now
  adguard-social: 21903-922, now
  adguard-widgets: 2331-3, now
  easylist-annoyances: 4006-205, now
  easylist-chat: 141-11, now
  easylist-newsletters: 6560-428, now
  easylist-notifications: 2954-1638, now
  fanboy-cookiemonster: 48651-3834, now
  fanboy-social: 16276-727, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 68-2, never
  easylist: 71987-74, now
  easyprivacy: 33148-178, now
  plowe-0: 3729-1071, now
  ublock-badware: 7255-132, now
  ublock-filters: 34994-531, now
  ublock-privacy: 588-8, now
  ublock-quick-fixes: 231-96, now
  ublock-unbreak: 2125-36, now
  urlhaus-1: 10980-0, now
filterset (user): [array of 68 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 425 ms (selfie)
 maxAssetCacheWait: 250 ms
popupPanel:
 blocked: 8
 network:
  3dporndude.com: 1
  adsco.re: 2
  ccgzcavzbmztk.com: 1
  d13k7prax1yi04.cloudfront.net: 1
  eclebgjz.com: 1
  googletagmanager.com: 1
  visariomedia.com: 1
```
</details>

**Comment by okiehsch** [comment]
@MasterKia 
We use
`3dporndude.com##+js(aopw, _pop)`
for that generic popup script.
