### ISSUE TITLE
pricempire.com: ads

### ISSUE THREAD

**Issue by 3kh0** [uBlockOrigin/uAssets#20178]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pricempire.com/`

### Category

ads

### Description

There are still promotions for other websites, this can be considered as ads. I got a filter that should fix this

```
! 2023-10-20 https://pricempire.com
pricempire.com##.desktop.promo-box
```

### Other extensions used

Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/58097612/ef023bb0-7dfe-4ce3-b9ab-73ff6e46eb4e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 117
filterset (summary):
 network: 255430
 cosmetic: 86402
 scriptlet: 35179
 html: 1071
listset (total-discarded, last-updated):
 added:
  adguard-generic: 78840-6663, now
  adguard-mobile: 8760-99, now
  adguard-spyware-url: 1262-82, now
  adguard-spyware: 62001-16885, now
 default:
  user-filters: 0-0, never
  ublock-filters: 35883-149, now
  ublock-badware: 7259-0, now
  ublock-privacy: 582-0, now
  ublock-unbreak: 2171-3, now
  ublock-quick-fixes: 225-0, now
  easylist: 71987-944, now
  easyprivacy: 33148-803, now
  urlhaus-1: 10980-0, 31m
  plowe-0: 3724-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1740 ms (selfie)
 maxAssetCacheWait: 827 ms
popupPanel:
 blocked: 7
 network:
  pricempire.com: 1
  cloudflareinsights.com: 4
  googletagmanager.com: 1
  yandex.ru: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
```
</details>

**Comment by mapx-** [comment]
report directly here: https://github.com/easylist/easylist/issues
