### ISSUE TITLE
iqiyi.com: ads

### ISSUE THREAD

**Issue by zxc135781** [uBlockOrigin/uAssets#20171]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.iqiyi.com/v_26sjfdhn0tw.html?vfrm=pcw_home&vfrmblk=B&vfrmrst=fcs_0_p11`

### Category

ads

### Description

ads

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![图片](https://github.com/uBlockOrigin/uAssets/assets/12949090/8a704011-f6af-4a4c-bb1f-4d27cbe31c50)

</details>

### Configuration

<details>

```yaml
uBlock Origin 1.50.0:
 since: 126d.19h.47m
Firefox: 119
filterset (summary):
 network: 120961
 cosmetic: 61803
 scriptlet: 19003
 html: 1071
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 17m
  JPN-1: 13568-27, 18m
 default:
  user-filters: 0-0, never
  ublock-filters: 35883-156, now
  ublock-badware: 7259-0, now
  ublock-privacy: 616-75, now
  ublock-unbreak: 2169-2, now
  ublock-quick-fixes: 228-0, 19m
  easylist: 71984-724, now
  easyprivacy: 33141-761, now
  urlhaus-1: 10980-0, 19m
  plowe-0: 3729-1, now
  CHN-0: 25237-137, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1553 ms
 maxAssetCacheWait: 548 ms
popupPanel:
 blocked: 67
 network:
  iqiyi.com: 4
  bdstatic.com: 1
  miaozhen.com: 1
  qy.net: 57
  reachmax.cn: 1
  xelements.cn: 2
  yoyi.com.cn: 1
 extended:
  ##.cupid-panel + div
  ##.qy-plist-ad
  ##:not(.qy-index-page) > div[id^="100000"]
  ##.black-screen[data-cupid="adblock-blackscreen"]
  ##+js(set-constant, Object.prototype.parseXML, noopFunc)
  ##+js(set-constant, Object.prototype.blackscreenDuration, 1)
```
</details>

**Comment by okiehsch** [comment]
Caused by `video.gjirafa.com##+js(json-prune, 0)`
Not sure if that filter is still necessary.
For now add  
`video.gjirafa.com#@#+js(json-prune, 0)`
to your filter list.

**Comment by gorhill** [comment]
> `https://www.iqiyi.com/v_26sjfdhn0tw.html?vfrm=pcw_home&vfrmblk=B&vfrmrst=fcs_0_p11`

It looks to me you are giving us a direct link to an ad. We need a link to legitimate video content for which an ad occur.
