### ISSUE TITLE
Problematic cookie override for www.google.* 

### ISSUE THREAD

**Issue by no-identd** [uBlockOrigin/uAssets#20182]
Creating this issue from mobile via Fasthub so: sorry for not including the whole checklist header from the issue template. Anyway, the Google cookie override added by this commit here:
https://github.com/uBlockOrigin/uAssets/commit/27e2c23d415df3208feae24a8794b54354972b7e

Appears to break being able to set languages, dark mode, and a whole bunch of other Google search preference settings. And in weird intermittent/transient ways, too, hence why I've yet to figure out a minimal, RELIABLE repro of these issues, but the filter is definitely the cause, so in the meantime I can only summarize the repro as "go to `www.google.com/preferences`, start messing around, Shift+F5/Ctrl+F5 reload, see what if anything sticks/unsticks eventually, because it will.", but I didn't want that to preclude reporting the issue.

[Note:

The Youtube filter from that commit is also a problem, one which got partially raised via https://old.reddit.com/r/uBlockOrigin/comments/1693mka and "addressed" by  https://github.com/uBlockOrigin/uAssets/commit/7d3eea2e4ec157d0e9c123c57a72b5318ab8df7b, but this fix is bad (which people on reddit also pointed out but which got lost in the noise) because now instead of forcing a YouTube setting OFF, it now forces a setting ON.

However, I'll post that particular issue to the Youtube Omnibus issue, I just wanted to raise this one first so I can reference it there.]

**Comment by mapx-** [comment]
- browser ? android ?
- you should provide `Troubleshooting Information` (uBO dashboard, support tab)

**Comment by peace2000** [comment]
I cannot reproduce the issues with Google. I can change language and dark mode without any issues. The setting is saved and the settings stays on despite page refreshes.

**Comment by no-identd** [comment]
@peace2000 interesting, thanks for trying. I'll try to get a reliable repro on Monday, but no promises. IFF it turns out that that filter isn't the only part involved in it, my apologies in advanced. Same for if this turns out to have been some kind of wild goose chase—I wouldn't put it past Google to have inconsistent behavior in this regard (because they seem to have changed their whole code handling of this drastically somewhat recently, soooo…) dependent on which CDN node had ended up hitting :S we'll see
