### ISSUE TITLE
spytm.com: breakage

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20187]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://spytm.com/sms-receive-free-online-usa-phone-number/mobile-5/`

### Category

breakage

### Description

- The loading bar on this page goes on infinitely when uBlock Origin is on. The loading bar goes from 0% to 100% then back to 0% and so on. When uBlock Origin is off, the loading bar goes from 0% to around 60/70% where the table of SMS messages fully loads. 
- The disclaimer collapsible section also doesn't respond when clicking on it. 
- There are also some other minor things that break on the site like on the main page `https://spytm.com/` where the country flags don't load
- the 'LOAD MORE POSTS' button doesn't respond when clicking on it (also in `https://spytm.com/blog/`)
- the disclaimer collapsible section doesn't respond.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screen Shot 2023-10-20 at 1 45 56 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/9bcd7210-bfb3-43af-a6a2-44e74bb267d8">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105502
 cosmetic: 41597
 scriptlet: 22573
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5556-7, 3m
 default:
  user-filters: 12-2, never
  easylist: 71992-15, 3m
  easyprivacy: 33148-64, 3m
  plowe-0: 3724-1070, 3m
  ublock-badware: 7255-132, 3m
  ublock-filters: 35069-145, 3m
  ublock-privacy: 588-6, 3m
  ublock-quick-fixes: 235-98, 3m
  ublock-unbreak: 2125-33, 3m
  urlhaus-1: 11685-0, 3m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 242 ms
 maxAssetCacheWait: 97 ms
popupPanel:
 blocked: 443
 network:
  spytm.com: 215
  cloudflareinsights.com: 1
  doubleclick.net: 1
  ezodn.com: 3
  ezoic.net: 217
  google.com: 1
  googlesyndication.com: 2
  imasdk.googleapis.com: 1
  pubmatic.com: 1
  taboola.com: 1
 extended:
  ##.ezoic-ad
  ##.adtester-container
  ##.ezoic-adpicker-ad
  ###taboola-below-article-thumbnails
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ###ez-sidebar-wall-left
  ##.ez-sidebar-wall-ad
  ##ins.adsbygoogle
  ##[data-ez-name]
  ##div[id^="ezoic-pub-ad-"]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  #@#[id^="div-gpt-ad"]
```
</details>

**Comment by mapx-** [comment]
test this filter:

`@@||spytm.com/tardisrocinante/screx.js$script,1p`

@ryanbr

**Comment by huyszn** [comment]
> test this filter:
> 
> `@@||spytm.com/tardisrocinante/screx.js$script,1p`
> 

This works, but is there any way to remove the around 5-second delay in loading the table, loading the images, and making the buttons responsive?
