### ISSUE TITLE
punkrust.net: nuisance

### ISSUE THREAD

**Issue by rawkon** [uBlockOrigin/uAssets#20183]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://punkrust.net/web/index.php?name=whatsapp&id=60`

### Category

nuisance

### Description

countdown

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 257684
 cosmetic: 246810
 scriptlet: 47469
 html: 0
listset (total-discarded, last-updated):
 added:
  TUR-0: 13747-9, now
  adguard-cookies: 27878-31, now
  adguard-generic: 78844-489, now
  adguard-mobile: 8760-46, now
  adguard-mobile-app-banners: 4688-10, now
  adguard-other-annoyances: 13681-8, 1h.57m
  adguard-popup-overlays: 24857-75, 1h.56m
  adguard-social: 21906-925, 1h.55m
  adguard-spyware: 62002-1402, 1h.54m
  adguard-spyware-url: 1262-5, 1h.53m
  adguard-widgets: 2331-6, 1h.52m
  curben-phishing: 76643-5, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 20-1, never
  easylist: 71992-1244, now
  easyprivacy: 33148-16653, now
  plowe-0: 3724-1241, now
  ublock-badware: 7255-328, now
  ublock-filters: 35069-4288, now
  ublock-privacy: 588-139, now
  ublock-quick-fixes: 229-93, 1h.51m
  ublock-unbreak: 2125-149, now
  urlhaus-1: 11685-0, now
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1095 ms (selfie)
 maxAssetCacheWait: 228 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by Yuki2718** [comment]
@MasterKia AG doesn't address countdown by default (+ the site has too few visitors).
