### ISSUE TITLE
washingtonpost.com: breakage

### ISSUE THREAD

**Issue by rabidk13** [uBlockOrigin/uAssets#20181]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.washingtonpost.com/politics/2023/10/20/house-speaker-vote-live/`

### Category

breakage

### Description

live updates are not populating content correctly with ublock active

### Other extensions used

uMatrix (issue still occurs with uMatrix deactivated)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/148572712/eb375ddc-f1a4-4e15-b0c2-5ebb6a2db50a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105216
 cosmetic: 40071
 scriptlet: 18717
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 27-0, never
  easylist: 71990-15, now
  easyprivacy: 33148-64, now
  plowe-0: 3724-1070, now
  ublock-badware: 7255-132, now
  ublock-filters: 35069-146, now
  ublock-privacy: 588-6, now
  ublock-unbreak: 2125-30, now
  urlhaus-1: 11685-0, now
filterset (user): [array of 27 redacted]
trustedset:
 added: [array of 26 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 661 ms (selfie)
 maxAssetCacheWait: 97 ms
popupPanel:
 blocked: 9
 network:
  3gl.net: 1
  amazon-adsystem.com: 1
  brandmetrics.com: 1
  criteo.net: 1
  doubleclick.net: 1
  googleoptimize.com: 1
  googletagmanager.com: 1
  unpkg.com: 1
  webcontentassessor.com: 1
 extended:
  ##.ad-mobile
  ##.pb-sm.pt-sm.b
  ##[data-qa="article-body-ad"]
  ##[data-qa="right-rail-ad"]
  ##[data-testid="placeholder-box"]
  ##[data-ad-module]:not([style$="left: -10000px !important; top: …
  #@#[data-ad-module]
  ##+js(abort-current-script, Promise, overlay)
  ##+js(abort-current-script, document.createElement, overlay)
  ##+js(remove-node-text, script, adblock)
```
</details>

**Comment by gorhill** [comment]
It's caused by `washingtonpost.com##+js(remove-node-text, script, adblock)` in uBO filters. From what I see, it ends up matching a script with the word `roadblock` in it. I will modify to match `/\badblock\b/` in the hope this was the original intent.
