### ISSUE TITLE
mediathekviewweb.de cookie terror

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#20198]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Obtrusive Cookie modal upon first visit of `https://mediathekviewweb.de/`

### URL(s) where the issue occurs.

`https://mediathekviewweb.de/`

### uBO version

uBO 1.52.2

### Browser name and version

Chrome Stable (118.0.5993.89)

### Settings

- No changes

### Notes

I tried to find out if we now can use these functions (like `trusted-set-cookie`) in our own filter lists etc,
but this is apparently not an answer that is easy to get?

Anyway, because this site did not turn up yet on an issue search here, I hope that someone could add this to `annoyances-cookies.txt`

This should already be enough, I think:
```
! mediathekviewweb.de
mediathekviewweb.de##+js(trusted-set-cookie, allowCookies, true)
```

**Comment by Hrxn** [comment]
Looking at the site code again,
I think `mediathekviewweb.de##+js(trusted-set-cookie, allowCookies, false)` should also work?

**Comment by Hrxn** [comment]
@mapx- Thank you for the quick fix

What is the benefit of using `set-local-storage-item` in this case?

**Comment by mapx-** [comment]
it's that one which fixes the "issue" (removes the cookie dialogue)

**Comment by gwarser** [comment]
Can you guys check something for me? If I whitelist this page, clear cookies and reload, uBO script is applied anyway and set the `allowCookies` value. I see it in browser debugger. In the logger I see only green "whitelisted" line.  1.52.3b17 Firefox 120.0a1

**Comment by mapx-** [comment]
- it does not happen in chrome uBO b16
- FF uBO b17 inconsistent behaviour

**Comment by Hrxn** [comment]
> it's that one which fixes the "issue" (removes the cookie dialogue)

Why would `trusted-set-cookie` not work in this case?
Just curios, I see it in use in `annoyances-cookies.txt` aplenty

Also: Would be really helpful to know when/how we could use those functions/scriptlets in our own filter lists.

**Comment by gwarser** [comment]
@Hrxn the `allowCookies` setting is not saved in cookie but in local storage.

**Comment by Hrxn** [comment]
Ah, you mean like here?
```
var allowCookies = (_b = (_a = window.localStorage) === null || _a === void 0 ? void 0 : _a.getItem) === null || _b === void 0 ? void 0 : _b.call(_a, allowCookiesKey);
```

**Comment by okiehsch** [comment]
> Also: Would be really helpful to know when/how we could use those functions/scriptlets in our own filter lists.

If you mean `trusted-set-cookie` you can only use it in your personal filter list.

""
Trusted sources are:
uBO's own filter lists, which name starts with "uBlock filters – ", and maintained at: https://github.com/uBlockOrigin/uAssets
The user's own filters as seen in "My filters" pane in uBO's dashboard
""

**Comment by Hrxn** [comment]
Not really, I meant a custom filter list, for example written by me, and hosted on GitHub.

The ones that can be imported on the filter list settings page as "Custom".

But does this mean, just for example, that `set-local-storage-item` does not have this same trusted source restriction at the moment?

**Comment by mapx-** [comment]
The trusted one is `trusted-set-local-storage-item` usable only in "my filters"

see https://github.com/gorhill/uBlock/wiki/Resources-Library#trusted-set-local-storage-itemjs-
