### ISSUE TITLE
as.com: breakage

### ISSUE THREAD

**Issue by DefconTwo** [uBlockOrigin/uAssets#20199]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

loads a lot of posts whit uBO on, i whitelisted a lot of filter but no way to find the problematic filter 

### URL(s) where the issue occurs.

`https://as.com/motor/quartararo-marquez-sera-una-pesadilla-con-la-ducati-n/`
`https://as.com/futbol/internacional/sorteado-el-preolimpico-masculino-de-futbol-en-sudamerica-n/`

### uBO version

1.52.2

### Browser name and version

Chrome last version

### Settings

```
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 107710
 cosmetic: 46379
 scriptlet: 19177
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71995-15, 11h.38m
  easyprivacy: 33148-64, 11h.38m
  plowe-0: 3724-1070, 11h.38m
  spa-0: 3765-19, 11h.38m
  spa-1: 5656-225, 11h.38m
  ublock-badware: 7255-132, 11h.38m
  ublock-filters: 35069-176, 11h.38m
  ublock-privacy: 588-6, 11h.38m
  ublock-quick-fixes: 236-93, 11h.16m
  ublock-unbreak: 2126-34, 11h.38m
  urlhaus-1: 11685-0, 11h.38m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 199 ms (selfie)
 maxAssetCacheWait: 97 ms
```

**Comment by mapx-** [comment]
> loads a lot of posts whit uBO on

with uBO off is loading too, what's the issue ?

**Comment by DefconTwo** [comment]
whit uBO on .. loads all posts
whit ubo off scroll down for load the next post ( normal function )

just see the scroll bar of the browser

**Comment by mapx-** [comment]
add

`@@||assets.adobedtm.com^$script,domain=as.com`

@ryanbr

**Comment by mapx-** [comment]
still not fixed completely in EP, maintainer notified

**Comment by stephenhawk8054** [comment]
@mapx- I think this is enough? Does it work on your side?

```adb
as.com##+js(set, DTM.trackAsyncPV, noopFunc)
```
