### ISSUE TITLE
edhrec.com: ads

### ISSUE THREAD

**Issue by idonthaveagithubacc** [uBlockOrigin/uAssets#20195]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://edhrec.com/`

### Category

ads

### Description

Site shows ads at the top of the page

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 106671
 cosmetic: 43838
 scriptlet: 19176
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 71995-15, 5m
  easyprivacy: 33148-64, 5m
  plowe-0: 3727-1073, 5m
  spa-1: 5656-66, 5m
  ublock-badware: 7255-132, 5m
  ublock-filters: 35070-174, 5m
  ublock-privacy: 588-6, 5m
  ublock-quick-fixes: 236-95, 5m
  ublock-unbreak: 2126-33, 5m
  urlhaus-1: 11685-0, 5m
filterset (user): [array of 3 redacted]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 308 ms (selfie)
 maxAssetCacheWait: 97 ms
popupPanel:
 blocked: 9
 network:
  edhrec.com: 1
  doubleclick.net: 2
  google.com: 3
  googletagmanager.com: 1
  mediavine.com: 1
  youtube.com: 1
 extended:
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /(maxAgeSeconds.*?"loggedO…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
add
`edhrec.com##[class^="Ad_"]`

report at easylist repo https://github.com/easylist/easylist/issues
