### ISSUE TITLE
youtube no longer works.

### ISSUE THREAD

**Issue by maxtraxv3** [uBlockOrigin/uAssets#20193]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

purging and update cache does nothing.

yes followed the youtube guide nothing works.

### URL(s) where the issue occurs.

https://www.youtube.com/watch?v=LUEYNuVeA9Y

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/12743527/144e634a-4396-4ccd-80d0-a69cf63923e2)

### Notes

purging and update cache does nothing.

yes followed the youtube guide nothing works.

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 105223
 cosmetic: 40121
 scriptlet: 18781
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 71995-15, now
  easyprivacy: 33148-64, now
  plowe-0: 3724-1070, now
  ublock-badware: 7255-132, now
  ublock-filters: 35069-145, now
  ublock-privacy: 588-6, now
  ublock-quick-fixes: 235-94, now
  ublock-unbreak: 2126-32, now
  urlhaus-1: 11685-0, now
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 289 ms (selfie)
 maxAssetCacheWait: 71 ms
```
</details>

**Comment by gwarser** [comment]
>yes followed the youtube guide nothing works.

Then you know where to report.
