### ISSUE TITLE
Add optional filterlist: Fanboy's Cookiemonster List

### ISSUE THREAD

**Issue by kovacsattila-hun** [uBlockOrigin/uAssets#202]
Please add optional filterlist to uBlock Origin!

**Fanboy's Cookiemonster List**
`https://secure.fanboy.co.nz/fanboy-cookiemonster.txt`

Browser/version: Google Chrome 54 (Windows) 64 bit
uBlock Origin version: 1.9.16

Thanks!

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/issues/1609
