### ISSUE TITLE
epicload.com: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#20206]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://epicload.com/files/hSdWa2Pi`

### Category

[Paywall]

### Description

When you click on the button to display the links, a paywall appears.

### Other extensions used

None that interfere with uBlock

### Screenshot(s)

When you click on the :
![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/d9cd283e-543b-4b4c-a971-8fbe411c3314)

Here's what you get:
![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/06539d08-4257-4d4b-9b5a-800ce255f749)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 146384
 cosmetic: 114517
 scriptlet: 23185
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1660-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2466-10, now
  RUS-0: 40033-168, now
  fanboy-cookiemonster: 48665-230, now
 default:
  FRA-0: 28470-40, now
  easylist: 72013-125, now
  easyprivacy: 33155-636, now
  plowe-0: 3727-1089, now
  ublock-badware: 7263-146, now
  ublock-filters: 35086-260, now
  ublock-privacy: 589-54, now
  ublock-quick-fixes: 239-95, now
  ublock-unbreak: 2127-37, now
  urlhaus-1: 11700-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 183 ms (selfie)
 maxAssetCacheWait: 94 ms
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  mbidadm.com: 1
  owlunimmvn.com: 1
  tsyndicate.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```
epicload.com##.show.modal
epicload.com##.show.modal-backdrop
```
