### ISSUE TITLE
doodstream.com, doods.pro: detection

### ISSUE THREAD

**Issue by HowToRuski** [uBlockOrigin/uAssets#20205]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://doodstream.com/`
`https://doods.pro/`

### Category

detection

### Description

https://github.com/uBlockOrigin/uAssets/assets/49795268/0c324083-9052-4e0b-99ed-e9d0633ee295

### Other extensions used

uBlock and Privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/49795268/b0a56162-96b5-4cc4-9a16-945bb4132df7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 108869
 cosmetic: 40690
 scriptlet: 35531
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw: 23116-15, 3m
 default:
  user-filters: 4-0, never
  easylist: 72013-22, now
  easyprivacy: 33155-64, now
  plowe-0: 3727-1073, now
  ublock-badware: 7255-132, now
  ublock-filters: 35086-2336, now
  ublock-privacy: 589-7, now
  ublock-quick-fixes: 239-95, now
  ublock-unbreak: 2127-33, now
  urlhaus-1: 11700-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 376 ms (selfie)
 maxAssetCacheWait: 70 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
- disable privacy badger
- provide example videos

**Comment by HowToRuski** [comment]
you can go see them on manija.net, all the movies are hosted on doods
disabled privacy badger, no changes.

**Comment by okiehsch** [comment]
Example link
`https://manija.net/watch/the-covenant-2019?back=home`
plays without issue on my end.

**Comment by mycodedoesnotcompile2** [comment]
cf. https://github.com/ytdl-org/youtube-dl/pull/31003#issuecomment-1788919194
