### ISSUE TITLE
phenomenalityuniform.com: detection

### ISSUE THREAD

**Issue by Kenir211** [uBlockOrigin/uAssets#20207]
### Prerequisites

- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://phenomenalityuniform.com/4zbn8fhuuhmx`

### Category

detection

### Description

doesn't let me watch if addblock is activw

### Other extensions used

Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 107603
 cosmetic: 44909
 scriptlet: 18796
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-2, never
  DEU-0: 7158-0, now
  easylist: 72013-21, now
  easyprivacy: 33155-73, now
  plowe-0: 3727-1074, now
  ublock-badware: 7255-132, now
  ublock-filters: 35086-159, now
  ublock-privacy: 589-6, now
  ublock-quick-fixes: 237-95, 2m
  ublock-unbreak: 2127-34, now
  urlhaus-1: 11700-0, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1693 ms (selfie)
 maxAssetCacheWait: 202 ms
popupPanel:
 blocked: 6
 network:
  ads-twitter.com: 1
  imasdk.googleapis.com: 1
  newbornleasetypes.com: 1
  sharethis.com: 2
  voe.sx: 1
```
</details>

**Comment by okiehsch** [comment]
Update your `uBO-filters` list, it should work after that.

**Comment by trashbag9** [comment]
> Update your `uBO-filters` list, it should work after that.

It works, but I get pop-ups. At least the sites don't open up, thanks to dns block.

**Comment by huyszn** [comment]
New domain
`nonesnanking.com`

**Comment by mapx-** [comment]
What exactly is broken ? example link ?

**Comment by OsbornTV** [comment]
https://streamkiste.tv/movie/ride-on-die-zweite-chance-2023-15430628#video and then klick on VOE

![image](https://github.com/uBlockOrigin/uAssets/assets/22799027/db2c4e67-2e0d-4d80-81c3-41e5f963827c)

this externl link `nonesnanking.com` is to blame for it.

**Comment by stephenhawk8054** [comment]
It opens normally for me: https://github.com/uBlockOrigin/uAssets/assets/66517106/64fbe61f-9319-4403-82cb-2bd0cfc60fa7

**Comment by stephenhawk8054** [comment]
I don't know. You gave the link and it plays fine for me on both firefox and [chromium](https://github.com/uBlockOrigin/uAssets/assets/66517106/eb06aa8d-79ff-4894-8eaa-fe644b14aadb) so I don't know how to investigate more.

You might need to investigate yourself.

**Comment by mapx-** [comment]
working fine on my side too

@OsbornTV 

- disable any other blocking extension / builtin blocker
- use only the default filter lists in uBO
-

**Comment by mapx-** [comment]
as I said:
**disable any other blocking extension / builtin blocker**

disable 1 by 1 and test again

**Comment by huyszn** [comment]
New domain
`denisegrowthwide.com`

**Comment by huyszn** [comment]
New domain
`stevenimaginelittle.com`
