### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by keloox966** [uBlockOrigin/uAssets#20204]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=hxHTpEdBmps&ab_channel=HangiOnur`

### Category

detection

### Description

This site is detection ublock and say "we will block your video player after 3 videos/or delete to adblocker"

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 106896
 cosmetic: 50599
 scriptlet: 20388
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  TUR-0: 13747-9, now
  easylist: 72013-36, now
  easyprivacy: 33148-69, 1m
  plowe-0: 3727-1074, now
  ublock-badware: 7255-132, now
  ublock-filters: 35086-152, now
  ublock-privacy: 588-6, now
  ublock-quick-fixes: 229-88, now
  ublock-unbreak: 2127-33, now
  urlhaus-1: 11700-0, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 145 ms (selfie)
 maxAssetCacheWait: 86 ms
popupPanel:
 blocked: 37
 network:
  youtube.com: 25
  doubleclick.net: 6
  google.com: 5
  google.com.tr: 1
 extended:
  ##tp-yt-paper-dialog.ytd-popup-container.style-scope
  ##.opened
  ###merch-shelf
  ###player-ads
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?\/(aclk\?…
  ##+js(set-constant, yt.config_.openPopupConfig.supportedPopups.a…
  ##+js(set-constant, Object.prototype.adBlocksFound, 0)
  ##+js(set-constant, ytplayer.config.args.raw_player_response.adP…
  ##+js(set-constant, Object.prototype.hasAllowedInstreamAd, true)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(trusted-replace-fetch-response, /(source=.*?)"adSlots.*?\…
  #@#+js(trusted-replace-fetch-response, /(source=.*?)"adPlacement…
  #@#+js(trusted-replace-fetch-response, /(source=.*?)"playerAds.*…
```
</details>

**Comment by mapx-** [comment]
read here: https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by TheBSODAndWSODFan** [comment]
@keloox966 i see ab_channel= parameter in the link. meaning are you using ublock with other adblock?

**Comment by keloox966** [comment]
> @keloox966bağlantıda ab_channel= parametresini görüyorum. yani ublock'u diğer reklam bloklarıyla birlikte mi kullanıyorsunuz? ublock'unuzda başka bir adblock yüklüyse, ublock dışındaki diğer adblock uzantılarını kaldırmanız gerekir.

Ohh sorry, yes i forgot this. Ok i removed other adblock. Thx Problem solved.
