### ISSUE TITLE
sharpen.design: breakage

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20202]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sharpen.design/free-generators/design/graphic-design/`

### Category

breakage

### Description

The box always has "Loading Generator" text and never loads the design challenge text when uBlock Origin is enabled on the site.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1437" alt="Screen Shot 2023-10-21 at 8 53 05 AM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/25bc13e2-0c2f-46ef-b0ed-825dfa884f84">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105548
 cosmetic: 41610
 scriptlet: 22602
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5572-7, now
 default:
  user-filters: 16-2, never
  easylist: 72012-15, now
  easyprivacy: 33163-64, now
  plowe-0: 3727-1073, now
  ublock-badware: 7255-132, now
  ublock-filters: 35084-145, now
  ublock-privacy: 588-6, now
  ublock-quick-fixes: 237-99, now
  ublock-unbreak: 2127-33, now
  urlhaus-1: 11700-0, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 111 ms (selfie)
 maxAssetCacheWait: 58 ms
popupPanel:
 blocked: 6
 network:
  carbonads.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  netlify-rum.netlify.app: 1
  servedby-buysellads.com: 1
  usefathom.com: 1
```
</details>

**Comment by mapx-** [comment]
test

`@@||cdn.usefathom.com/script.js$script,domain=sharpen-free-design-generator.netlify.app`

**Comment by okiehsch** [comment]
That works.

**Comment by mapx-** [comment]
@ryanbr

**Comment by huyszn** [comment]
> test
> 
> `@@||cdn.usefathom.com/script.js$script,domain=sharpen-free-design-generator.netlify.app`

The filter works for all the generators.

**Comment by stephenhawk8054** [comment]
Do these work?

```adb
sharpen-free-design-generator.netlify.app##+js(set, fathom, {})
sharpen-free-design-generator.netlify.app##+js(set, fathom.trackGoal, noopFunc)
```
