### ISSUE TITLE
liga.net and many others

### ISSUE THREAD

**Issue by ditra-ua** [uBlockOrigin/uAssets#2021]
### URL(s) where the issue occurs

`http://finance.liga.net/bank/novosti/bank-poroshenko-uvelichil-chistuyu-pribyl-do-78-mln-grn`

### Describe the issue

Styles of the site are broken

### Screenshot(s)

![liga.net](https://preview.ibb.co/g9DN1n/liga.png)

### Versions

- Browser/version: Firefox 59.0.2
- uBlock Origin version: 1.15.24

### Settings

- Default. Ublock filters enabled.

### Notes

The problem is in unsupported syntax of **,redirect=nooptext** in Firefox. 

> ||piguiqproxy.com^$xmlhttprequest,redirect=nooptext,domain=liga.net

works as 

> ||piguiqproxy.com^$xmlhttprequest,domain=liga.net

And this rule breaks any site with piguiqproxy.com code

**Comment by uBlock-user** [comment]
It's FF bug, patched in FF 60. For now add - `liga.net##^script:has-text(3f87b0eaddd)`

**Comment by okiehsch** [comment]
Fixed ads in Chrome.
