### ISSUE TITLE
likemanga.io: ads

### ISSUE THREAD

**Issue by 5n0wL30p4rd** [uBlockOrigin/uAssets#20214]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://likemanga.io/legendary-youngest-son-of-the-marquis-house-2411/chapter-36-162059/`

### Category

ads

### Description

`https://likemanga.io`
`likemanga.io###c7p0sbu`

I tried to create a custom rule to block all content that starts with likemanga.io### but it still shows the popup add while accessing the site. 

### Other extensions used

Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot_20231021-210352_Firefox](https://github.com/uBlockOrigin/uAssets/assets/148668162/4e48a7bf-a28e-4a11-9192-f91789ace56f)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 116875
 cosmetic: 148476
 scriptlet: 29144
 html: 1269
listset (total-discarded, last-updated):
 added:
  https://likemanga.io: 0-0, never
  adguard-social: 21906-1547, 53m
  adguard-cookies: 27878-1627, 52m
  ublock-cookies-adguard: 425-0, 52m
  adguard-popup-overlays: 25050-1740, 52m
  adguard-mobile-app-banners: 4688-1070, 52m
  adguard-other-annoyances: 13682-325, 52m
  adguard-widgets: 2331-36, 52m
  fanboy-thirdparty_social: 69-1, 52m
  easylist-annoyances: 4010-982, 52m
  easylist-chat: 141-20, 52m
  fanboy-cookiemonster: 48665-19806, 52m
  [5 lists not shown]: [too many]
 default:
  user-filters: 9-0, never
  ublock-filters: 36274-766, 3m
  ublock-badware: 7261-0, 3m
  ublock-privacy: 582-1, 3m
  ublock-unbreak: 2179-3, 3m
  ublock-quick-fixes: 229-0, 3m
  adguard-mobile: 8760-138, 3m
  easylist: 71987-16772, 3m
  easyprivacy: 33148-830, 3m
  urlhaus-1: 11580-0, 3m
  plowe-0: 3727-1, 3m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1122 ms (selfie)
 maxAssetCacheWait: 550 ms
popupPanel:
 blocked: 0
 extended:
  ###su12sijr
```
</details>

**Comment by 5n0wL30p4rd** [comment]
Thank you so much for adding it to the filter list. I have it on auto update but I refreshed it just in case. The add didn't pop up when I visited the site just now.

**Comment by stephenhawk8054** [comment]
@5n0wL30p4rd Force update all your filter lists (click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)) and test again.
