### ISSUE TITLE
v2.videoland.com: breakage

### ISSUE THREAD

**Issue by WilcoM** [uBlockOrigin/uAssets#20210]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://v2.videoland.com/welcome`

### Category

breakage

### Description

Page keeps showing "Loading" when uBO is enabled, when disabling uBO on the website, it does load, but also shows ads.

### Other extensions used

```
Improve YouTube!
Ads Link Skipper
Augmented Steam
Automatic Twitch: Drops, Moments and Points
BetterTTV
Chatterino Native Host
ChromeHue for Philips Hue
ClearURLs
Copy Link Text
Dark Reader
Demodal - Block modals and overlays
FrankerFacez
Google Docs Offline
Gyazo - Share new screenshots. Instantly.
Hide YouTube Shorts
ICS to GCal
imgur Uploader
JSON Formatter
Nimbus Screenshot & Screen Video
NopeCHA: CAPTCHA Solver
Office Editing for Docs, Sheets & Slides
Open in VLC™
PayPal Honey
Play HLS M3u8
Reddit Enhancement Suite
Resizing App
Return YouTube Dislike
Save to Google Drive
Screenshot YouTube
ShareX
SponsorBlock for YouTube
Stream Cleaner
Suspicious Site Reporter
Tampermonkey
Tracking Token Stripper
Truffle
Twitter Block Chain
Uncanny Cookie Clicker
User-Agent Switcher for Chrome
View Background Image
Violentmonkey
Web Scrobbler
Yellow highlighter pen for web
YouTube Upload Time
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/1355344/4c450466-df26-4a51-bd85-6e0e6cc4881b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 116291
 cosmetic: 192298
 scriptlet: 29418
 html: 0
listset (total-discarded, last-updated):
 added:
  NLD-0: 2701-10, now
  adguard-cookies: 27878-31, now
  adguard-mobile-app-banners: 4688-9, now
  adguard-other-annoyances: 13682-7, now
  adguard-popup-overlays: 25050-65, now
  adguard-social: 21906-922, now
  adguard-widgets: 2331-3, now
  easylist-annoyances: 4010-205, now
  easylist-chat: 141-11, now
  easylist-newsletters: 6561-428, now
  easylist-notifications: 2955-1638, now
  fanboy-cookiemonster: 48665-3833, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 72062-76, now
  easyprivacy: 33155-179, now
  plowe-0: 3727-1074, now
  ublock-badware: 7263-132, now
  ublock-filters: 35090-532, now
  ublock-privacy: 589-8, now
  ublock-quick-fixes: 239-99, now
  ublock-unbreak: 2128-36, now
  urlhaus-1: 11700-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 20 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 713 ms
 maxAssetCacheWait: 370 ms
popupPanel:
 blocked: 4
 network:
  videoland.com: 1
  cookielaw.org: 1
  newrelic.com: 2
```
</details>

**Comment by mapx-** [comment]
1. reset uBO to default settings / filter lists => do not add any other lists during the test (only your regional list)
2. disable ALL other extensions
3. test again
