### ISSUE TITLE
expertplay.net: detection

### ISSUE THREAD

**Issue by vitordelucca** [uBlockOrigin/uAssets#20211]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://expertplay.net/forum/`

### Category

detection

### Description

When accessing the website, it detects uBlock Origin and shows a popup. You can't close it. Only works again by disabling uBlock.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231021_193156](https://github.com/uBlockOrigin/uAssets/assets/9909446/6070dbe6-94e0-4811-9728-91ebc60c6f99)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105298
 cosmetic: 40133
 scriptlet: 18660
 html: 1078
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35975-137, now
  ublock-badware: 7267-0, now
  ublock-privacy: 583-0, now
  ublock-unbreak: 2174-2, now
  ublock-quick-fixes: 231-0, now
  easylist: 72062-695, now
  easyprivacy: 33155-724, now
  urlhaus-1: 11700-0, now
  plowe-0: 3727-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2812 ms
 maxAssetCacheWait: 16 ms
popupPanel:
 blocked: 0
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by astolfoismywaifu** [comment]
Try adding `expertplay.net##+js(acis, ips.controller.register)` to your filters

**Comment by vitordelucca** [comment]
> Try adding `expertplay.net##+js(acis, ips.controller.register)` to your filters

Worked, thanks!
