### ISSUE TITLE
sayurbox.com: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#20212]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sayurbox.com/product/jamur-kuping-kghjxxzg?touch_point=home_jamur-kuping-kghjxxzg&section_source=home_view_item_Belanja%20Hemat%20di%20Akhir%20Pekan&product_builder=SIAP_Jakarta&item_position=1&view_grid=3`

### Category

breakage

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/b602bc73-93ad-49df-8972-e9eaaf48fa2c)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 109342
 cosmetic: 106344
 scriptlet: 25412
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4010-48, never
  easylist-notifications: 2955-160, never
  fanboy-cookiemonster: 48665-230, never
  fanboy-social: 16295-11, never
  ublock-annoyances: 5572-427, never
  ublock-cookies-easylist: 355-4, never
 default:
  user-filters: 0-0, never
  easylist: 72062-15, 1m
  easyprivacy: 33155-64, 1m
  plowe-0: 3727-1073, 1m
  ublock-badware: 7263-132, 1m
  ublock-filters: 35090-145, 1m
  ublock-privacy: 589-6, now
  ublock-quick-fixes: 239-95, now
  ublock-unbreak: 2128-32, now
  urlhaus-1: 11580-0, now
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1357 ms
 maxAssetCacheWait: 17 ms
popupPanel:
 blocked: 4
 network:
  sayurbox.com: 3
  googletagmanager.com: 1
```
</details>

**Comment by D4niloMR** [comment]
Test without annoyance filters

**Comment by mapx-** [comment]
add

`@@||assets.sayurbox.com/assets/images/icons/$image,1p`

@ryanbr
