### ISSUE TITLE
myaccount.google.com: breakage

### ISSUE THREAD

**Issue by ghaznavipc** [uBlockOrigin/uAssets#20221]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://myaccount.google.com/u/1/signinoptions/two-step-verification/enroll?rapt=AEjHL4NaJau0npvy04f-ekWIb7VBxKnyOGJss3TO-fUAbSK_6sPUWOwAsXJW7lMC5Vfl-9VnEg3UpFlPZOlyDqT6zgT29vhwyQ&flow=phone`

### Category

breakage

### Description

I need gmail to send me sms so my 2-step verification get enabled. but gmail cannot send it. I inspect it in network and saw it blocked by uBlockOrigin

### Other extensions used

Privacy Badger
NoScript (set google to temporary Trusted for doing the operations. and gstatic to Trusted.)
Don't track me Google

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105132
 cosmetic: 40151
 scriptlet: 18682
 html: 1078
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36009-135, now
  ublock-badware: 7267-0, now
  ublock-privacy: 583-0, now
  ublock-unbreak: 2177-3, now
  ublock-quick-fixes: 229-0, now
  easylist: 72071-695, now
  easyprivacy: 33104-724, now
  urlhaus-1: 11580-0, now
  plowe-0: 3727-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1570 ms (selfie)
 maxAssetCacheWait: 241 ms
popupPanel:
 blocked: 20
 network:
  google.com: 20
```
</details>

**Comment by stephenhawk8054** [comment]
Can you check what exact connections are blocked?

**Comment by gorhill** [comment]
> network and saw it blocked by uBlockOrigin

Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out which filter from which filter list is blocking it.

**Comment by krystian3w** [comment]
Check on disabled `Privacy Badger` / `Don't track me Google`. Can interfere with uBo on page.

**Comment by ghaznavipc** [comment]
> Check on disabled `Privacy Badger` / `Don't track me Google`. Can interfere with uBo on page.

As I said in the beginning it clearly mentioned in the inspect > network tab that the requests are "Blocked By uBlock Origin". don't send dislike for no reason. but one day when I gonna try to enable it again I will try your solution if I see disabling ublock alone is not enough to make it work.

> Can you check what exact connections are blocked?
I tried to repeat my issue that time but then google refused to accept my phone numbers since I tried a lot (like a spam) to get sms before I notice the blocking problem.

**Comment by mapx-** [comment]
@ghaznavipc whatever you see in the network tab => **disable those extensions** and try again (when you'll be able to do)
and use uBO logger to see exactly what's reported as blocked items

**Comment by krystian3w** [comment]
You can use VPN to mark PC as untrusted by Google to newest SMS verification.

**Comment by liamengland1** [comment]
Just tested adding a phone number to my account and I can't reproduce
