### ISSUE TITLE
eurogamer.*: nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#20225]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Reddit embedded posts are in txt mode instead in fancy iframe design due cookie laws.

I can not found blocked videos yet by cookie law pop-up.

The pop-up seems to be constantly visible despite fixing the problem about 5 months ago:

https://github.com/uBlockOrigin/uAssets/blob/b8066f635283dc90fb2c6ae568608c3291e2909e/filters/annoyances-cookies.txt#L189
https://github.com/uBlockOrigin/uAssets/blob/b8066f635283dc90fb2c6ae568608c3291e2909e/filters/annoyances-cookies.txt#L271

### URL(s) where the issue occurs.

`https://www.eurogamer.pl/czesc-graczy-nie-moze-zainstalowac-marvels-spider-man-2-z-plyty`

### Screenshot(s)

<details>

Is:

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/bf0a3b84-0ae2-4cec-976e-9c93f85e8bab) |
---- |

Should be:

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/95121cc5-e8a9-4467-a4be-92d2f4584b59) |
---- |
if nobody uses `##+js(rf, https://pl.reddit.com)` aka [`redirect-frontend.js`](https://pastebin.com/t5zwvkKQ). then iframe load all topic due old reddit does not support embedding |

</details>

### uBO version

1.52.2

### Browser name and version

Firefox 119.0 RC2

### Settings

stock + regional POL-0/POL-2 + uBo Annoyances/uBo cookie notices

### Notes

I am open to fix these by `set-constat` instead:

```adb
eurogamer.*##+js(trusted-set-cookie, consentUUID, 7bb276c0-2469-4a2a-8264-61e7edf46065_25, 1year)
```

Then I will paste such a filter with "set-constant" into Polish GDPR-cookies/Polish Annoyances Filters.

**Comment by peace2000** [comment]
If I click "Reject all" setting active, it seems that embeds still work.

@krystian3w Are there any issues if we use "reject all" cookie?

These issues seem to be only related to eurogamer. Rockpapershotgun and vg247.com are still working.

**Comment by peace2000** [comment]
I did update the filters:

https://github.com/uBlockOrigin/uAssets/commit/ffa0c6048a8935c65fa4aa8456ec7ecde13332d1

Do these work for you @krystian3w

**Comment by krystian3w** [comment]
These work for me now - pop-up gone, and iframe was loaded instead raw text with links.
