### ISSUE TITLE
Whatsapp web client

### ISSUE THREAD

**Issue by rvw** [uBlockOrigin/uAssets#2022]
### URL(s) where the issue occurs

`web.whatsapp.com`

### Describe the issue

Images not loading in conversations

### Screenshot(s)

no screenshot

### Versions

- Browser/version: Chrome 65.0.3325.181
- uBlock Origin version 1.15.24

### Settings

- [none]

### Notes

Images in conversations are not shown. The web client of WhatsApp loads images with the html `<img src="blob:https://web.whatsapp.com/..." />` and the `blob` part is blocked by uBlock. Whitelisting `web.whatsapp.com` resolves the issue.

**Comment by gorhill** [comment]
Using the logger, can you share the exact filter and from which filter list it originates?

**Comment by mapx-** [comment]
the filter was removed yesterday
https://forums.lanik.us/viewtopic.php?p=135228#p135228

update easylist, test again

**Comment by rvw** [comment]
removed `web.whatsapp.com` from my personal whitelist, purged and reloaded all filters → problem was solved, images show again.
