### ISSUE TITLE
iprima.cz: ads

### ISSUE THREAD

**Issue by tada123** [uBlockOrigin/uAssets#20220]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.iprima.cz/serialy/modry-kod/modry-kod/166-mit-trochu-stesti`

### Category

ads

### Description

Video ADS are showing even when UBlock is enabled

### Other extensions used

User agent changer
Plasma desktop integration

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105131
 cosmetic: 40149
 scriptlet: 18681
 html: 1078
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36007-135, now
  ublock-badware: 7267-0, now
  ublock-privacy: 583-0, now
  ublock-unbreak: 2177-3, now
  ublock-quick-fixes: 229-0, now
  easylist: 72069-695, now
  easyprivacy: 33104-724, now
  urlhaus-1: 11580-0, now
  plowe-0: 3727-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1112 ms (selfie)
 maxAssetCacheWait: 206 ms
popupPanel:
 blocked: 170
 network:
  adnxs.com: 3
  criteo.com: 1
  doubleclick.net: 3
  facebook.net: 1
  gemius.pl: 1
  google.com: 66
  google.cz: 1
  imrworldwide.com: 4
  litix.io: 21
  mookie1.com: 1
  pghub.io: 1
  primacdn.cz: 1
  seznam.cz: 65
  smartlook.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||www.iprima.cz^$xhr,1p
iprima.cz##.mon3_box
```

Not sure who to ping in regional list?
