### ISSUE TITLE
photopea.com: detection

### ISSUE THREAD

**Issue by ShuitOnDiscord** [uBlockOrigin/uAssets#20232]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.photopea.com/`

### Category

detection

### Description

using ublock on photopea will cause photopea to disable functionality until the adblocker is disabled

### Other extensions used

i used privacy badger and decentraleyes, then disabled both and tried again

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/106796864/1c1a3317-4185-495a-8c0b-974dc553f1d5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 114300
 cosmetic: 175972
 scriptlet: 29449
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27878-31, 1m
  adguard-mobile-app-banners: 4688-9, 1m
  adguard-other-annoyances: 13682-7, 1m
  adguard-popup-overlays: 25050-61, 1m
  adguard-social: 21906-922, 1m
  adguard-widgets: 2331-3, 1m
  easylist-annoyances: 4008-204, 1m
  easylist-newsletters: 6563-428, 1m
  easylist-notifications: 2955-1638, 1m
  fanboy-cookiemonster: 48683-3834, now
  fanboy-thirdparty_social: 68-3, now
  ublock-annoyances: 5609-208, now
 default:
  user-filters: 19-0, never
  easylist: 72119-75, 1m
  easyprivacy: 33105-178, 1m
  plowe-0: 3727-1074, now
  ublock-badware: 7257-132, now
  ublock-filters: 35246-532, now
  ublock-privacy: 589-8, now
  ublock-quick-fixes: 243-208, now
  ublock-unbreak: 2132-37, now
  urlhaus-1: 11600-0, now
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 24 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8574 ms (selfie)
 maxAssetCacheWait: 3584 ms
popupPanel:
 blocked: 1
 network:
  uniconsent.com: 1
 extended:
  ##.app.flexrow > div:nth-of-type(2)
  ##[href*=".ivank.net"]
  ##div[style] > a[href*="photopea.com"][href*="ads"]:upward(1)
  ##+js(set-constant, console.clear, noopFunc)
```
</details>

**Comment by Zaword** [comment]
![newscreenphotopea](https://github.com/uBlockOrigin/uAssets/assets/43016094/71ff3f99-fcb5-4bcf-86a5-d9b8f57af852)

After I've done a clear cache and update filters, ublock still get detected but in a different way, now it opens a browser message. After closing the warning I could continue to use Photopea but the warning shows up after some seconds.

**Comment by gorhill** [comment]
They already changed the code to bypass the fix.

**Comment by gwarser** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/19697
