### ISSUE TITLE
bkmedical.com: breakage

### ISSUE THREAD

**Issue by thulfiqar191** [uBlockOrigin/uAssets#20236]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bkmedical.com/systems/bk5000-robotic-surgery-ultrasound-system/`

### Category

breakage

### Description

when uBO active the website shows only white screen and a scroll bar. after disabling uBO I was able to see the website content

### Other extensions used

other blocking extensions ? none.
extensions in general? 
Torrent Scanner
Rememberry - Translate and Memorize
PayPal Honey
IDM Integration Module
Google Docs Offline
Crop It!
CORS Unblock
Application Launcher For Drive

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/148742791/4fa9ba7e-3cae-4495-b4ce-80eb2c7ba2a1)

![image](https://github.com/uBlockOrigin/uAssets/assets/148742791/f48387ac-3f17-497f-b211-4f5de71fb3b7)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105226
 cosmetic: 40173
 scriptlet: 18842
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72119-15, now
  easyprivacy: 33108-64, now
  plowe-0: 3727-1073, now
  ublock-badware: 7262-132, now
  ublock-filters: 35248-147, now
  ublock-privacy: 589-6, now
  ublock-quick-fixes: 243-204, now
  ublock-unbreak: 2133-33, now
  urlhaus-1: 11630-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 600 ms (selfie)
 maxAssetCacheWait: 103 ms
popupPanel:
 blocked: 12
 network:
  doubleclick.net: 2
  fonts.net: 1
  google.com: 2
  googletagmanager.com: 1
  hs-analytics.net: 1
  hs-banner.com: 1
  hsleadflows.net: 1
  mpeasylink.com: 1
  youtube.com: 2
 extended:
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /(maxAgeSeconds.*?"loggedO…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
add

`@@||fast.fonts.net/jsapi/core/mt.js$script,domain=bkmedical.com`

@ryanbr
