### ISSUE TITLE
deepl.com: nuisance

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#20231]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.deepl.com/`

### Category

nuisance

### Description

(See screenshot)
"To continue translating, create a free account at DeepL."

"Try again later or continue translating now with a DeepL account. Create an account to increase your translation limit and translate texts of up to 5,000 characters."

"Sign up for free" "Sign in"

Fix: `deepl.com##+js(set-local-storage-item, LMT_freeUserUsageBlock, $remove$)`

To reproduce add this `local-storage-item` and type anything: 

`{"data":{"countOfDailyTranslations":303,"timeStamp":1698006752726,"updatedInCurrentSession":{"updated":true,"visitCountAtUpdate":1}}} `

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/0d0f4e70-c95e-411c-a6c7-12745c5969c7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.3b16
Chromium: 116
filterset (summary):
 network: 119532
 cosmetic: 194400
 scriptlet: 30437
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 964-0, 57m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2466-0, 57m
  adguard-cookies: 27878-31, 57m
  adguard-mobile-app-banners: 4688-9, 57m
  adguard-other-annoyances: 13682-7, 57m
  adguard-popup-overlays: 25050-64, 57m
  adguard-social: 21906-922, 57m
  adguard-widgets: 2331-4, 57m
  easylist-annoyances: 4007-204, 57m
  easylist-chat: 142-11, 57m
  easylist-newsletters: 6562-428, 57m
  easylist-notifications: 2955-1639, 57m
  [5 lists not shown]: [too many]
 default:
  user-filters: 105-3, never
  easylist: 72117-74, 57m
  easyprivacy: 33104-179, 57m
  plowe-0: 3727-1074, 57m
  spa-1: 5656-71, 57m
  ublock-badware: 7259-132, 56m
  ublock-filters: 35250-561, 56m
  ublock-privacy: 590-53, 56m
  ublock-quick-fixes: 243-208, 56m
  ublock-unbreak: 2132-38, 56m
  urlhaus-1: 11600-0, 56m
filterset (user): [array of 64 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1966 ms (selfie)
 maxAssetCacheWait: 292 ms
popupPanel:
 blocked: 14
 network:
  deepl.com: 14
 extended:
  ##div[class^="cookieBanner-"]
  ##aside[data-testid="app_banner_content"]
  ##aside[aria-labelledby="customer-quotes-heading"]
  ##div[data-testid="write-promo-banner"]
  ##aside[aria-labelledby="career-banner-heading"]
  ##div[data-testid="dl-cookieBanner"]
  ###cookieBanner
  #@##headlessui-portal-root
  ##+js(set-constant, Object.prototype.getFooterText, undefined)
  ##+js(addEventListener-defuser, copy)
```
</details>

**Comment by stephenhawk8054** [comment]
@ryanbr
