### ISSUE TITLE
buytesmart.com: breakage

### ISSUE THREAD

**Issue by awdavis** [uBlockOrigin/uAssets#20235]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://buytesmart.com/products/dual-monitor-2-port-kvm-hdmi-hdmi-4k-60hz-uhd-audio-output-usb-sharing-4x2`

### Category

breakage

### Description

The page content appears for a split second and then disappears. The `body` tag ends up with `style="display: none;"` when using uBlockOrigin (but not when using AdBlockPlus),

### Other extensions used

uBlockOrigin
Windscribe VPN

I verified that the issue was still reproducible with these other extensions disabled in chrome://extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

The page is entirely white.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105147
 cosmetic: 40137
 scriptlet: 18842
 html: 0
listset (total-discarded, last-updated):
 added:
  https://www.aadvantageeshopping.com/adBlockWhitelist.php: 0-0, now
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, now
 default:
  user-filters: 0-0, never
  easylist: 72012-15, now
  easyprivacy: 33105-64, now
  plowe-0: 3727-1073, now
  ublock-badware: 7257-132, now
  ublock-filters: 35248-146, now
  ublock-privacy: 589-6, now
  ublock-quick-fixes: 243-204, now
  ublock-unbreak: 2132-33, now
  urlhaus-1: 11630-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 258 ms (selfie)
 maxAssetCacheWait: 127 ms
popupPanel:
 blocked: 162
 network:
  buytesmart.com: 13
  adroll.com: 1
  bing.com: 1
  cloudflare.com: 1
  doubleclick.net: 18
  extreme-ip-lookup.com: 1
  facebook.net: 1
  google-analytics.com: 1
  google.com: 109
  googletagmanager.com: 3
  ipinfo.io: 1
  klaviyo.com: 2
  mouseflow.com: 1
  privy.com: 1
  shopifysvc.com: 1
  youtube.com: 6
  zendesk.com: 1
 extended:
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /(maxAgeSeconds.*?"loggedO…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by astolfoismywaifu** [comment]
Dont use the honey whitelist
https://twitter.com/gorhill/status/1352651716265713665
