### ISSUE TITLE
rezka.ag: ads

### ISSUE THREAD

**Issue by Spok1** [uBlockOrigin/uAssets#20249]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rezka.ag/series/fantasy/51874-uenzdey-2022.html`

### Category

ads

### Description

Everything is shown in the picture

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

https://github.com/uBlockOrigin/uAssets/assets/34476664/5fc50c0e-5f90-4e5e-9ead-f4d57ce3b662
https://github.com/uBlockOrigin/uAssets/assets/34476664/86347bd4-9406-4b3d-a8d8-04fe2534b218

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 111038
 cosmetic: 51706
 scriptlet: 20096
 html: 1137
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  adguard-spyware-url: 1271-82, 7m
 default:
  user-filters: 3-0, never
  ublock-filters: 36321-371, 8m
  ublock-badware: 7293-5, 8m
  ublock-privacy: 583-1, 8m
  ublock-unbreak: 2182-4, 8m
  ublock-quick-fixes: 217-0, 8m
  adguard-mobile: 8762-42, 8m
  easylist: 72154-16357, 7m
  easyprivacy: 33104-32, 7m
  RUS-0: 40110-1039, 1m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6449 ms
 maxAssetCacheWait: 25 ms
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  jsdelivr.net: 1
 extended:
  ##+js(abort-current-script, document.getElementsByTagName, AMSP.…
  ##+js(set-constant, Object.prototype.preroll, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
Click on uBO icon -> "Filter lists" pane -> Untick `Ignore generic cosmetic filters`
