### ISSUE TITLE
www2.katmoviehd.id: nuisance

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#20243]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www2.katmoviehd.id/saw-x-2023-eng/`

### Category

nuisance

### Description

after clicking download there is timers and ads and that site makes my browser lag

### Other extensions used

fastforward, buster 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.3b17
Chromium Mobile: 110
filterset (summary):
 network: 113627
 cosmetic: 133633
 scriptlet: 26947
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27892-31, now
  adguard-mobile-app-banners: 4690-9, now
  adguard-other-annoyances: 13680-14, now
  adguard-popup-overlays: 25073-62, now
  adguard-social: 21910-926, now
  adguard-widgets: 2331-4, now
  ublock-annoyances: 5675-164, now
  ublock-cookies-adguard: 432-432, now
 default:
  user-filters: 29-3, never
  adguard-mobile: 8762-12, now
  easylist: 72154-123, now
  easyprivacy: 33094-138, now
  plowe-0: 3727-1149, now
  ublock-badware: 7257-133, now
  ublock-filters: 35586-711, now
  ublock-privacy: 589-7, now
  ublock-quick-fixes: 242-212, now
  ublock-unbreak: 2136-38, now
  urlhaus-1: 12175-0, now
filterset (user): [array of 32 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1834 ms (selfie)
 maxAssetCacheWait: 385 ms
popupPanel:
 blocked: 18
 network:
  adnxs.com: 1
  disq.us: 1
  disqus.com: 2
  google-analytics.com: 1
  histats.com: 1
  kindledownstairsskeleton.com: 2
  linksynergy.com: 1
  narrative.io: 1
  pippio.com: 1
  rfihub.com: 1
  rlcdn.com: 2
  ssindserving.com: 1
  tapad.com: 1
  viglink.com: 2
 extended:
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://facebook.com/sharer.php?"]
  ##a[href^="https://plus.google.com/share"]
  ##.meta-share
  ##+js(abort-current-script, Math.imul)
  ###thread-subscribe-button
  ###thread-share-bar
  ###fb-root:not(body):not(html)
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by mapx-** [comment]
Which one ? I clicked 2 download links and I get 2 different pages
You are using chromium mobile. Test in firefox mobile using the default settings / lists.

**Comment by Fatcavill** [comment]
@mapx- sir i also get 2 pages aren't they same ? Both have timers and ads & takes time to load for me

**Comment by mapx-** [comment]
try

```
cryptokinews.com,techmirror.in##+js(nano-sib)
cryptokinews.com,techmirror.in##center:others()
```

**Comment by Fatcavill** [comment]
works in first page..maybe timers in 2nd page also ?

**Comment by BlazeFTL** [comment]
Timer Cant Be Boosted You Must Wait In First Two Buttons 4+7 Or Overall 10 Seconds
Cant Confirm Other Two Domains If They Are Still Used Or Not.Had This For A Long Time
```
liveinsure.in,cryptokinews.com,techmirror.in,techbumper.info##center, .to, #showlink, #soralink-human-verif-main:style(display: block !important;)
liveinsure.in,cryptokinews.com,techmirror.in,techbumper.info##div.soractrl:others()
liveinsure.in,cryptokinews.com,techmirror.in,techbumper.info##+js(no-fetch-if, /^/)
