### ISSUE TITLE
infographicjournal.com: ads

### ISSUE THREAD

**Issue by RobberyBobbery** [uBlockOrigin/uAssets#20241]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://infographicjournal.com/`

### Category

ads

### Description

The "Partners" section appears, and has ads.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 106034
 cosmetic: 41595
 scriptlet: 22393
 html: 1274
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5575-13, never
 default:
  user-filters: 0-0, never
  ublock-filters: 36159-350, 16m
  ublock-badware: 7265-0, 16m
  ublock-privacy: 583-0, 16m
  ublock-unbreak: 2177-3, 16m
  ublock-quick-fixes: 234-0, 16m
  easylist: 72139-594, 16m
  easyprivacy: 33094-725, 16m
  urlhaus-1: 12175-0, 16m
  plowe-0: 3727-1, 16m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 722 ms (selfie)
 maxAssetCacheWait: 274 ms
popupPanel:
 blocked: 5
 network:
  googlesyndication.com: 2
  googletagmanager.com: 2
  shareasale.com: 1
 extended:
  ##.heateor_sss_vertical_sharing.heateor_sss_sharing_container
  ##ins.adsbygoogle
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
```
</details>

**Comment by mapx-** [comment]
add

```
infographicjournal.com##.et_pb_widget:has-text(Partners)
infographicjournal.com##.et_pb_module:has-text(Partners)
infographicjournal.com##.et_pb_module:has-text(Partners) + .et_pb_module
```

@ryanbr
