### ISSUE TITLE
adshnk.com: detection

### ISSUE THREAD

**Issue by GollumArain** [uBlockOrigin/uAssets#20257]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://adshnk.com/OTIzNjc=/https://ouo.io/M0hnOb`

### Category

detection

### Description

Detections

### Other extensions used

IDM, Bitwarden, Sponsor Block

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 268376
 cosmetic: 200137
 scriptlet: 46085
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 34m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2470-0, 34m
  adguard-cookies: 27904-31, now
  adguard-generic: 78815-477, now
  adguard-mobile: 8767-44, now
  adguard-mobile-app-banners: 4692-10, now
  adguard-other-annoyances: 13680-8, now
  adguard-popup-overlays: 25084-73, now
  adguard-spyware: 62518-1389, now
  adguard-spyware-url: 1272-149, now
  block-lan: 54-0, now
  curben-phishing: 75249-5, 34m
  [7 lists not shown]: [too many]
 default:
  user-filters: 6-0, never
  easylist: 72203-1536, now
  easyprivacy: 33042-16700, now
  plowe-0: 3727-1574, now
  ublock-badware: 7310-334, now
  ublock-filters: 35228-4280, now
  ublock-privacy: 613-173, now
  ublock-quick-fixes: 112-79, 34m
  ublock-unbreak: 2131-147, now
  urlhaus-1: 14020-3, 34m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 60 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1370 ms (selfie)
 maxAssetCacheWait: 1070 ms
popupPanel:
 blocked: 16
 network:
  adshnk.com: 1
  adsco.re: 1
  cloudflare.com: 1
  google-analytics.com: 1
  google.com: 10
  taboola.com: 1
  trackjs.com: 1
 extended:
  ##.cookie-consent
  ##+js(no-window-open-if)
  ##+js(nano-setInterval-booster, count, , 0.02)
  ##+js(set-constant, _adshrink.skiptime, 0)
  ##+js(nano-setInterval-booster, countdown, *, 0.02)
```
</details>

**Comment by BlazeFTL** [comment]
I Get Infinite Loading In FF Even After Disabling UBO But In Chrome Everything Works Fine

**Comment by mapx-** [comment]
all fine in FF desktop on my side

**Comment by mapx-** [comment]
@GollumArain 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
