### ISSUE TITLE
ui.service.belboon.com: breakage

### ISSUE THREAD

**Issue by tanjatanjatanjatanja** [uBlockOrigin/uAssets#20256]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ui.service.belboon.com/`

### Category

breakage

### Description

I can't use the website because every page gets blocked when uBlock is turned on. If i turn UBlock off it works perfectly fine.
I use this website for work and it is trustworthy.
Is there any way, this problem can be fixed?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1520" alt="Bildschirmfoto 2023-10-24 um 17 16 51" src="https://github.com/uBlockOrigin/uAssets/assets/148887736/2720c751-a934-4b20-881d-dd27d6269ce0">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 107638
 cosmetic: 40205
 scriptlet: 18855
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72203-15, now
  easyprivacy: 33042-64, now
  plowe-0: 3727-1073, now
  ublock-badware: 7310-137, now
  ublock-filters: 35225-147, now
  ublock-privacy: 613-6, now
  ublock-quick-fixes: 167-123, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 14020-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 333 ms (selfie)
 maxAssetCacheWait: 107 ms
popupPanel:
 blocked: 22
 network:
  belboon.com: 22
```
</details>

**Comment by mapx-** [comment]
`||ui.service.belboon.com^$badfilter`

@ryanbr

**Comment by ryanbr** [comment]
Is blocked due to CNAME tracking; affex.org. Reach out to the site to remove

```
;; ANSWER SECTION:
ui.service.belboon.com. 3600    IN      CNAME   belboon-com.affex.org.
```
