### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Whitepussicat** [uBlockOrigin/uAssets#20254]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=Ci81Yq80UI8`

### Category

detection

### Description

I get the "Ad blockers violate YouTube's Terms of Service"

### Other extensions used

Malwarebytes browser guard, violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 107621
 cosmetic: 40203
 scriptlet: 18673
 html: 1085
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36098-116, now
  ublock-badware: 7299-5, now
  ublock-privacy: 583-0, now
  ublock-unbreak: 2177-1, now
  ublock-quick-fixes: 104-0, now
  easylist: 72196-655, now
  easyprivacy: 33068-767, now
  urlhaus-1: 14020-0, now
  plowe-0: 3727-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1012 ms (selfie)
 maxAssetCacheWait: 442 ms
popupPanel:
 blocked: 5
 network:
  youtube.com: 1
  doubleclick.net: 3
  google.com: 1
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
> Malwarebytes browser guard, violentmonkey

Remove them

> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
