### ISSUE TITLE
looopings.nl: detection

### ISSUE THREAD

**Issue by SpiderQED** [uBlockOrigin/uAssets#20251]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.looopings.nl/`

### Category

detection

### Description

Welkom!
Je maakt helaas gebruik van software die onze advertenties blokkeert.
Dankzij reclamebanners kan onze website blijven bestaan.
Help Looopings door je advertentieblocker op dit domein uit te schakelen.
De site is dan weer zichtbaar. Bedankt! 

### Other extensions used

 None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 108100
 cosmetic: 40218
 scriptlet: 18697
 html: 1085
listset (total-discarded, last-updated):
 default:
  user-filters: 2-1, never
  ublock-filters: 36150-219, now
  ublock-badware: 7299-5, now
  ublock-privacy: 583-0, now
  ublock-unbreak: 2177-1, now
  ublock-quick-fixes: 201-0, 20m
  easylist: 72196-697, now
  easyprivacy: 33069-725, now
  urlhaus-1: 14490-0, 21m
  plowe-0: 3727-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 205017 ms (selfie)
 maxAssetCacheWait: 346 ms
popupPanel:
 blocked: 8
 network:
  looopings.nl: 2
  facebook.com: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  refinery89.com: 2
 extended:
  ###topad
  ###bottomad
  ##.AdBox
  ##.post-ads
```
</details>

**Comment by mapx-** [comment]
add the regional list `**nl: EasyDutch**`
