### ISSUE TITLE
plink.in: breakage

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#20252]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://plink.in/`

### Category

breakage

### Description

@ryanbr 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 112254
 cosmetic: 106423
 scriptlet: 25474
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4013-62, never
  easylist-notifications: 2958-161, never
  fanboy-cookiemonster: 48662-279, never
  fanboy-social: 16306-9, never
  ublock-annoyances: 5617-7, 2m
  ublock-cookies-easylist: 395-395, never
 default:
  user-filters: 0-0, never
  easylist: 72196-15, 2m
  easyprivacy: 33068-64, 2m
  plowe-0: 3727-1073, 2m
  ublock-badware: 7295-137, 2m
  ublock-filters: 35208-147, 2m
  ublock-privacy: 589-6, 2m
  ublock-quick-fixes: 209-181, 2m
  ublock-unbreak: 2131-33, 2m
  urlhaus-1: 14490-0, 2m
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 751 ms (selfie)
 maxAssetCacheWait: 141 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  rackcdn.com: 1
```
</details>

**Comment by mapx-** [comment]
What exactly is broken ?

**Comment by mapx-** [comment]
well, it seems [EasyList – Social Widgets](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=fanboy-social):

add
`@@||rackcdn.com/*/image/button_facebook.png$image,domain=plink.in`

@ryanbr

**Comment by 3xploiton3** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/c49b04a7-382c-43f3-bdde-b9ba8fcc7f89)

already purge & update filter, stuck at loading
