### ISSUE TITLE
Adblock Warning on manga site

### ISSUE THREAD

**Issue by jnicolak** [uBlockOrigin/uAssets#2025]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://kissmanga.com/`

### Describe the issue

[Forced popup that asks you to turn off your adblocker. Ads on site are not friendly.]

### Screenshot(s)

Simple issue.

### Versions

- Browser/version: [Firefox 59.0.2]
- uBlock Origin version: [1.16.0]

### Settings

- [Enabled adblock warning removal list, issue is with or without enabled]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
Did you update all ublock filters ?
