### ISSUE TITLE
UNABLE TO BLOCK YOUTUBE AD BLOCK DETECTION

### ISSUE THREAD

**Issue by SUNSAT7** [uBlockOrigin/uAssets#20267]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

https://www.youtube.com/watch?v=Iwx66JyVDHkhttps://www.youtube.com/watch?v=Iwx66JyVDHk

### Category

![image](https://github.com/uBlockOrigin/uAssets/assets/148914895/b61ec387-1551-456e-aef8-720cffcde2c3)

### Description

YOUTUBE AD BLOCKER DETECTION NOT WORKING AFTER PURGING CACHE AND UPDATING ubLOCK ORIGIN

### Other extensions used

NONE

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![image](https://github.com/uBlockOrigin/uAssets/assets/148914895/d9d03883-79ab-4fd7-ac6c-00c68d886700)

### Configuration

wiNDOWS 7, USING CHROME

**Comment by mapx-** [comment]
read https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by SUNSAT7** [comment]
THANKS THAT WORKED
    On Tuesday, October 24, 2023 at 04:26:13 PM CDT, mapx ***@***.***> wrote:  
 
 


read #19976
