### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by fallenxx4** [uBlockOrigin/uAssets#20269]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=MKBdmYRbNxU`

### Category

detection

### Description

i have no knowledge when it comes to it and related works, so, i actually didn't understand most of the things up there. I just wanted to report that uBlock was detected by YouTube and i cant afford premium. thank you for your understanding.

### Other extensions used

i have shazam and opera gx adblocker but at that time it wasnt on.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 107636
 cosmetic: 40198
 scriptlet: 18878
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72196-15, now
  easyprivacy: 33046-64, now
  plowe-0: 3727-1073, now
  ublock-badware: 7310-137, now
  ublock-filters: 35218-147, now
  ublock-privacy: 613-6, now
  ublock-quick-fixes: 167-99, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 14020-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 996 ms
 maxAssetCacheWait: 36 ms
popupPanel:
 blocked: 7
 network:
  doubleclick.net: 3
  google.com: 4
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /(maxAgeSeconds.*?"loggedO…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/19976
