### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by squatch406** [uBlockOrigin/uAssets#20268]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=KMOeC-Qqen8`

### Category

detection

### Description

Just downloaded toady. Worked for a few hours, then after closing and reopening a new window Youtube started detecting the adblocker. 

### Other extensions used

honey
BetterTTV
FrankerFaceZ

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screen Shot 2023-10-24 at 3 29 53 PM" src="https://github.com/uBlockOrigin/uAssets/assets/148915282/ed8e25d8-c524-4e71-a68d-232fa27ee28d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 107621
 cosmetic: 40193
 scriptlet: 18872
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72196-15, 3m
  easyprivacy: 33046-64, 3m
  plowe-0: 3727-1073, 3m
  ublock-badware: 7295-137, 2m
  ublock-filters: 35231-147, 2m
  ublock-privacy: 589-6, 2m
  ublock-quick-fixes: 167-99, 2m
  ublock-unbreak: 2131-32, 2m
  urlhaus-1: 14020-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1345 ms
 maxAssetCacheWait: 259 ms
popupPanel:
 blocked: 21
 network:
  youtube.com: 15
  doubleclick.net: 3
  google.com: 1
  sentry.io: 2
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-companion-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /(maxAgeSeconds.*?"loggedO…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.ab_det_gen_re, f…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
read the first post in this thread
https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by squatch406** [comment]
I read and followed the instructions from #19976, and the issue still persists.

**Comment by stephenhawk8054** [comment]
> `report in this thread`

Why did you tick on this?

> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

There's an update already, update the filter lists again.
