### ISSUE TITLE
animetrilogy.in: ads

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20262]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animetrilogy.in/ten-thousand-worlds-season-2-episode-126-176-multi-subtitle/`

### Category

ads

### Description

Red X close button leftovers from ads still appear over the page, including on top of the video frame which you have to click on before playing the video. This also occurs on `luciferdonghua.in`, `luciferdonghua.co.in` and `luciferdonghua.org`, although the close button is not on top of the video frame in `luciferdonghua.org`.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1437" alt="Screen Shot 2023-10-24 at 2 37 02 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/ce0e0429-83a5-4d9f-8f0c-e9145d64c5ed">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 107925
 cosmetic: 41678
 scriptlet: 22723
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5618-7, 7m
 default:
  user-filters: 15-2, never
  easylist: 72203-15, 7m
  easyprivacy: 33046-64, 7m
  plowe-0: 3727-1073, 7m
  ublock-badware: 7310-137, 7m
  ublock-filters: 35231-147, 7m
  ublock-privacy: 613-6, 7m
  ublock-quick-fixes: 167-127, 7m
  ublock-unbreak: 2131-33, 7m
  urlhaus-1: 14020-0, 7m
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 195 ms (selfie)
 maxAssetCacheWait: 74 ms
popupPanel:
 blocked: 32
 network:
  adnxs.com: 1
  agkn.com: 1
  dailymotion.com: 2
  disqus.com: 2
  dm-event.net: 7
  googlesyndication.com: 7
  googletagmanager.com: 1
  gstatic.com: 1
  imasdk.googleapis.com: 2
  lijit.com: 1
  narrative.io: 2
  onesignal.com: 1
  pippio.com: 1
  rezync.com: 1
  viglink.com: 2
 extended:
  ##ins.adsbygoogle
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
  ##+js(trusted-set-cookie, dm-euconsent-v2, CPt6yMAPt6yMABpAGAEND…
```
</details>

**Comment by umut-nb0** [comment]
The `teaser` class is used very often on anime sites. For these sites, the general rule `###div[id^="teaser"]` can be used.

**Comment by mapx-** [comment]
add

```
animetrilogy.in,luciferdonghua.*###overplay
animetrilogy.in,luciferdonghua.*###close-teaser
```

however such issues have to be reported at easylist repository (or some regional list if not an english site)
