### ISSUE TITLE
Radio24 web radio

### ISSUE THREAD

**Issue by diocagna1** [uBlockOrigin/uAssets#20279]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

webradio at `https://www.radio24.ilsole24ore.com/` stop working, giving only black screen.
with ublock disabled or with adblock on, is all ok.

### URL(s) where the issue occurs.

`https://www.radio24.ilsole24ore.com/`

### uBO version

uBlock Origin 1.52.2

### Browser name and version

Chrome Versione 118.0.5993.89 (Build ufficiale) (a 64 bit)

### Settings

no one

**Comment by dportvine** [comment]
`https://www.radio24.ilsole24ore.com/plugins/cordova-plugin-nielsen/www/nielsen.js`

`/nielsen.js` ~> **EasyPrivacy**

@ryanbr

**Comment by stephenhawk8054** [comment]
@gorhill I'm not sure if it could help in this case or not, but looks like Firefox has a shim for `nielsen.js` script

https://searchfox.org/mozilla-central/source/browser/extensions/webcompat/shims/nielsen.js

**Comment by gwarser** [comment]
I think it's outdated. Does not load as module.

    /nielsen.js$script,redirect=nielsen.js,domain=www.radio24.ilsole24ore.com
    https://gist.githubusercontent.com/gwarser/86890310434b6cd65759563c13a4ed96/raw/dc3e522dad2e8172be9ca2818589878161347deb/nielsen.js
