### ISSUE TITLE
uploadbank.com: detection

### ISSUE THREAD

**Issue by ravertine** [uBlockOrigin/uAssets#20275]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.uploadbank.com/672vqj6hhw2a`

### Category

detection

### Description

popup asks to disable ad blocker

### Other extensions used

too many to list

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.3b17
Chromium: 118
filterset (summary):
 network: 129580
 cosmetic: 86276
 scriptlet: 25887
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-other-annoyances: 13683-7, now
  adguard-popup-overlays: 25085-67, now
  easylist-annoyances: 4014-170, now
  ublock-annoyances: 5618-150, now
 default:
  user-filters: 3-1, never
  FRA-0: 28475-39, now
  easylist: 72207-150, now
  easyprivacy: 33046-399, now
  plowe-0: 3727-1084, now
  ublock-badware: 7310-151, now
  ublock-filters: 35223-583, now
  ublock-privacy: 613-8, now
  ublock-quick-fixes: 168-104, now
  ublock-unbreak: 2131-39, now
  urlhaus-1: 13600-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 682 ms (selfie)
 maxAssetCacheWait: 275 ms
popupPanel:
 blocked: 6
 network:
  ewikajs.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  proxycheck.io: 1
  shareaholic.net: 1
 extended:
  ##+js(set-constant, console.clear, noopFunc)
  ##+js(no-window-open-if)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by D4niloMR** [comment]
Add this:
`uploadbank.com##+js(noeval-if, /chp_?ad/)`
