### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by noobtodamax** [uBlockOrigin/uAssets#20273]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When typing in the url manually to get to a user profile on x.com, the page tries to reload tweets under the profile repeatedly in such a way that makes the page jitttery/flashy appearing to be unable to load. Pretty agitating for someone with sensitivity to flashing images I would imagine. --not affiliated with @alexclare22 I looked at his twitter to see who he was get off my case lol--

### URL(s) where the issue occurs.

```
x.com/alexclare22
https://twitter.com/alexclare22
```

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/41933987/ff780282-9115-4ad7-aaa9-f2c33ad1b006

### uBO version

uBlock Origin 1.52.2

### Browser name and version

firefox118.0.2

### Settings

N/A

### Notes

turned off all other extensions, tried in a private browser to recreate for a screenshot.

**Comment by mapx-** [comment]
site issue when logged off ?

**Comment by krystian3w** [comment]
Looks as site issue unrelated what uBo do on page.

JavaScript crazies can see if it's possible to fix Elon Musk's team's bugs with the help of uBo instead of, say, Tampermonkey.
