### ISSUE TITLE
jetpunk.com: detection

### ISSUE THREAD

**Issue by nzkl1828** [uBlockOrigin/uAssets#20270]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jetpunk.com/`

### Category

detection

### Description

Pop up after finishing a quiz requesting user turn off adblock

### Other extensions used

Privacy badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 109032
 cosmetic: 31432
 scriptlet: 18796
 html: 1085
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36424-369, now
  ublock-badware: 7308-5, now
  ublock-privacy: 607-1, now
  ublock-unbreak: 2182-2, now
  ublock-quick-fixes: 159-24, now
  adguard-mobile: 8770-127, now
  easylist: 72207-16698, now
  easyprivacy: 33046-733, now
  urlhaus-1: 14020-0, now
  plowe-0: 3727-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 712 ms (selfie)
 maxAssetCacheWait: 208 ms
popupPanel:
 blocked: 7
 network:
  jetpunk.com: 2
  amazon-adsystem.com: 1
  cloudflare.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  hbwrapper.com: 1
 extended:
  ##+js(no-xhr-if, prebid)
  ##+js(cookie-remover, PageCount)
  ##+js(set-constant, asc, 1)
```
</details>

**Comment by mapx-** [comment]
Disable Privacy badger, test again using only the default settings / lists

**Comment by dhana-exe** [comment]
After checking it
no detection appear before and after doing some quiz


i think the ublock is just not loaded properly on your pc

**Comment by D4niloMR** [comment]
I can reproduce with default lists 
https://github.com/uBlockOrigin/uAssets/assets/70459964/faddd91e-3627-4aa8-babc-e1c03ebb6da1

`jetpunk.com##.support-beg`
