### ISSUE TITLE
web1s.asia: detection

### ISSUE THREAD

**Issue by 2xuhdne** [uBlockOrigin/uAssets#20286]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://web1s.asia/note/6FPbECtwWc/`

### Category

[unknown]

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/148943650/c89b202d-8293-456b-b829-a647c17a40d2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 106643
 cosmetic: 41567
 scriptlet: 18999
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  VIE-1: 2065-0, now
  easylist: 72212-35, now
  easyprivacy: 32971-66, now
  plowe-0: 3727-1073, now
  ublock-badware: 7329-138, now
  ublock-filters: 35253-152, now
  ublock-privacy: 613-6, now
  ublock-quick-fixes: 164-96, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 12490-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 207 ms (selfie)
 maxAssetCacheWait: 108 ms
popupPanel:
 blocked: 6
 network:
  bmcdn6.com: 3
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by BlazeFTL** [comment]
Try
`web1s.asia##+js(acs, eval, replace)`
