### ISSUE TITLE
animefire.vip: detection

### ISSUE THREAD

**Issue by Sabrewulf** [uBlockOrigin/uAssets#20282]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animefire.vip/animes/helck/16`

### Category

detection

### Description

they are using a anti-adblock detector.

### Other extensions used

Also adblock plus is being detected

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 108615
 cosmetic: 43924
 scriptlet: 19135
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36103-249, now
  ublock-badware: 7334-5, now
  ublock-privacy: 607-0, now
  ublock-unbreak: 2177-1, now
  ublock-quick-fixes: 159-24, now
  easylist: 72216-595, now
  easyprivacy: 32991-781, now
  urlhaus-1: 13600-0, now
  plowe-0: 3727-1, now
  spa-1: 5663-11, now
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6726 ms (selfie)
 maxAssetCacheWait: 5419 ms
popupPanel:
 blocked: 5
 network:
  animefire.vip: 2
  grunoaph.net: 1
  onclickalgo.com: 2
```
</details>

**Comment by D4niloMR** [comment]
@mapx- 

`https://www.reddit.com/r/uBlockOrigin/comments/17k6ei6/xhamster_adblock_detected/`

maybe:

```adb
@@/clever_ads.js^
```
?

**Comment by stephenhawk8054** [comment]
@D4niloMR It's fixed in uBlock annoyance list?

**Comment by D4niloMR** [comment]
Oh, sorry. I think this could be used by more sites, so i suggested here
