### ISSUE TITLE
dailymail.co.uk: detection

### ISSUE THREAD

**Issue by ashutoshgoyal** [uBlockOrigin/uAssets#20283]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dailymail.co.uk/home/index.html`

### Category

detection

### Description

detects uBlock and shows a overlay warning at the bottom of the page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/20591484/78d11a77-a706-4a9e-847b-a98474245422)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 108911
 cosmetic: 149612
 scriptlet: 29505
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  IND-0: 12811-0, now
  adguard-cookies: 27910-1591, now
  adguard-mobile-app-banners: 4695-17, now
  adguard-other-annoyances: 13684-14, now
  adguard-popup-overlays: 25092-101, now
  adguard-social: 21921-2064, now
  adguard-widgets: 2332-38, now
  block-lan: 54-0, now
  easylist-annoyances: 4016-1065, now
  easylist-chat: 142-20, now
  easylist-newsletters: 6581-2268, now
  easylist-notifications: 2958-1881, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 469-31, never
  easylist: 72212-16038, now
  easyprivacy: 32984-180, now
  plowe-0: 3727-1074, now
  ublock-badware: 7330-138, now
  ublock-filters: 35210-735, now
  ublock-privacy: 613-8, now
  ublock-quick-fixes: 164-100, now
  ublock-unbreak: 2131-37, now
filterset (user): [array of 469 redacted]
trustedset:
 added: [array of 168 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 10 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 25780 ms (selfie)
 maxAssetCacheWait: 678 ms
popupPanel:
 blocked: 89
 network:
  dailymail.co.uk: 10
  3lift.com: 4
  adnxs.com: 9
  adsrvr.org: 1
  amazon-adsystem.com: 1
  anm.co.uk: 1
  casalemedia.com: 3
  criteo.com: 2
  criteo.net: 1
  dotmetrics.net: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  google.com: 6
  googletagmanager.com: 1
  id5-sync.com: 2
  imasdk.googleapis.com: 2
  indexww.com: 1
  openx.net: 4
  permutive.app: 1
  rubiconproject.com: 5
  sentry.io: 1
  sharethrough.com: 12
  skimresources.com: 1
  smartadserver.com: 17
 extended:
  ##.dms-puff
  ##.article-icon-links .share-link
  ##.article-icon-links > li.facebook
  ###sky-right
  ##.mpu_puff_wrapper
  ##.watermark
  ##.container-3zJLP
  ##ul[class^="linksHolder-"]
  ##.facebook
  ##.mol-ads-label-container
  ##.pufftext > .sponsored:upward(3)
  ##+js(abort-on-property-read, Object.prototype.videoAdvertisingM…
  ##+js(set-constant, PushManager, undefined)
  ##+js(trusted-set-local-storage-item, mol.ads.cmp.tcf.cache, {"g…
  ##+js(abort-on-property-read, Notification)
```
</details>

**Comment by mapx-** [comment]
Disable any other extension, test again **using only the default settings / lists in uBO**
