### ISSUE TITLE
peroz.ro: nuisance

### ISSUE THREAD

**Issue by H80h23h30rj032jr-32rjw-q3** [uBlockOrigin/uAssets#20297]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.peroz.ro/`

### Category

nuisance

### Description

This website has cookie banner that cannot can be blocked. I try to block myself but is imposible to block it.
Any other website can I been block cookie banners but only this website I cannot block this annoying cookie banner.
Please help me. Thanks in advance.

(Sorry for my bad English)

### Other extensions used

Dark Reader; Tampermonkey; video background play fix; TWP - Translate Web Pages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 119
filterset (summary):
 network: 344079
 cosmetic: 293056
 scriptlet: 51994
 html: 1411
listset (total-discarded, last-updated):
 added:
  https://filters.adavoid.org/ultimate-ad-filter.txt: 149325-146162, now
  https://filters.adavoid.org/ultimate-privacy-filter.txt: 62318-17200, now
  https://filters.adavoid.org/ultimate-security-filter.txt: 7324-5, now
  https://raw.githubusercontent.com/H80h23h30rj032jr-32rjw-q3/j3r0j3r-ew-r3r3rfd/main/cleanweb: 16453-5797, 8m
  adguard-generic: 78870-7909, 1m
  adguard-spyware-url: 1272-82, 1m
  adguard-spyware: 62520-62057, 1m
  block-lan: 54-0, 1m
  curben-phishing: 74975-17, 8m
  adguard-social: 21923-1557, 1m
  adguard-cookies: 27934-1884, 1m
  ublock-cookies-adguard: 441-0, 1m
  [44 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36497-941, 1m
  ublock-badware: 7328-7158, 1m
  ublock-privacy: 607-1, 1m
  ublock-unbreak: 2182-3, 1m
  ublock-quick-fixes: 155-24, 1m
  adguard-mobile: 8772-143, 1m
  easylist: 72213-17420, 1m
  easyprivacy: 32934-1038, 1m
  urlhaus-1: 12765-0, 9m
  plowe-0: 3727-1, now
  ROU-1: 1443-35, now
filterset (user): [empty]
userSettings:
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11323 ms
 maxAssetCacheWait: 7910 ms
popupPanel:
 blocked: 50
 network:
  adtlgc.com: 2
  cxense.com: 1
  duckduckgo.com: 2
  googletagservices.com: 1
  iw.ro: 44
```
</details>

**Comment by stephenhawk8054** [comment]
Click on uBO icon -> "Filter lists" pane -> Untick `Ignore generic cosmetic filters`

**Comment by mapx-** [comment]
> [44 lists not shown]: [too many]

terrible choice on android !

You should use only the default lists / settings.
In your case the cookies items are hidden by **EasyList – Cookie Notices** if you enable it in filters lists section but only if you enable the generic cosmetic filters as @stephenhawk8054 told you above
