### ISSUE TITLE
grammarly.com: product feedback blocked

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#20293]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On the **Account Settings** page, click the **three dots** at the bottom and then on **Product Feedback**. By filling in the required fields it is not possible to send feedback and the error message appears:
_NetworkError when attempting to fetch resource_

### URL(s) where the issue occurs.

`https://account.grammarly.com/`

### Screenshot(s)

![immagine](https://github.com/uBlockOrigin/uAssets/assets/62190484/9d88fda7-9df6-4fa3-9c8f-00cf4942f60b)

### Notes

I created this filter and everything seems to work fine:

`@@||gnar.grammarly.com/events$domain=account.grammarly.com`

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 110740
 cosmetic: 47186
 scriptlet: 18748
 html: 1085
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 36150-122, 1d.10h.49m
  ublock-badware: 7299-5, 1d.10h.49m
  ublock-privacy: 583-0, 1d.10h.49m
  ublock-unbreak: 2177-1, 1d.10h.49m
  ublock-quick-fixes: 155-0, 2h.38m
  easylist: 72196-704, 1d.10h.49m
  easyprivacy: 33069-725, 1d.10h.49m
  urlhaus-1: 13600-0, 10h.40m
  plowe-0: 3727-1, 1d.10h.49m
  ITA-0: 10524-18, 10h.39m
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 110 ms (selfie)
 maxAssetCacheWait: 55 ms
```
</details>

**Comment by mapx-** [comment]
I guess due to this EP filter:

`||gnar.grammarly.com^`

**Comment by ryanbr** [comment]
Works fine here.

![grammarly](https://github.com/uBlockOrigin/uAssets/assets/1659004/31eed0ab-51cc-44f8-b86d-99fac9b4aca4)
