### ISSUE TITLE
marinetraffic.com: ads

### ISSUE THREAD

**Issue by leogali45** [uBlockOrigin/uAssets#20294]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.marinetraffic.com/en/ais/home/centerx:3.7/centery:52.0/zoom:11`

### Category

ads

### Description

picker mode does not work
zapper does work ok

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-10-25 at 23-35-54 MarineTraffic Global Ship Tracking Intelligence AIS Marine Traffic](https://github.com/uBlockOrigin/uAssets/assets/149018517/270eb990-40e4-47b5-99ba-ceb8d94a1ef7)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 106040
 cosmetic: 40280
 scriptlet: 18757
 html: 1084
listset (total-discarded, last-updated):
 added:
  https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt: 0-0, never
  https://mirror.cedia.org.ec/malwaredomains/justdomains: 0-0, never
 default:
  user-filters: 21-1, never
  ublock-filters: 36182-216, now
  ublock-badware: 7333-5, now
  ublock-privacy: 607-0, now
  ublock-unbreak: 2177-1, now
  easylist: 72213-595, now
  easyprivacy: 32974-725, now
  plowe-0: 3727-1, now
  urlhaus-1: 12490-0, now
  ublock-quick-fixes: 155-24, now
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2716 ms (selfie)
 maxAssetCacheWait: 1330 ms
popupPanel:
 blocked: 4
 network:
  cloudflareinsights.com: 1
  newrelic.com: 2
  quantcast.com: 1
```
</details>

**Comment by liamengland1** [comment]
`@@||marinetraffic.com^$ghide`

For future reference, their anti-adblock code: `https://gist.github.com/liamengland1/1140e80345c5f250aa45ecc0b59fdf9b`

**Comment by stephenhawk8054** [comment]
```adb
marinetraffic.com###skyscraper_container_front
marinetraffic.com##.under-map-wrapper:upward(1)
```

But it looks like self-promotion?

**Comment by leogali45** [comment]
thank you all
