### ISSUE TITLE
newindianexpress.com: detection

### ISSUE THREAD

**Issue by ashutoshgoyal** [uBlockOrigin/uAssets#20298]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.newindianexpress.com/nation`

### Category

detection

### Description

detects uBlockOrigin and shows a warning at the bottom of the page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 108847
 cosmetic: 149745
 scriptlet: 29537
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  IND-0: 12806-0, now
  adguard-cookies: 27934-1591, now
  adguard-mobile-app-banners: 4697-17, now
  adguard-other-annoyances: 13691-14, now
  adguard-popup-overlays: 25106-101, now
  adguard-social: 21923-2064, now
  adguard-widgets: 2332-38, now
  block-lan: 54-0, now
  easylist-annoyances: 4017-1065, now
  easylist-chat: 143-20, now
  easylist-newsletters: 6583-2268, now
  easylist-notifications: 2959-1882, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 474-33, never
  easylist: 72213-16038, now
  easyprivacy: 32937-180, now
  plowe-0: 3727-1074, now
  ublock-badware: 7330-138, now
  ublock-filters: 35293-729, now
  ublock-privacy: 613-8, now
  ublock-quick-fixes: 164-100, now
  ublock-unbreak: 2131-37, now
filterset (user): [array of 474 redacted]
trustedset:
 added: [array of 168 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 10 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 25780 ms (selfie)
 maxAssetCacheWait: 678 ms
popupPanel:
 blocked: 12
 network:
  amazon-adsystem.com: 1
  ampproject.org: 1
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 5
  googletagmanager.com: 1
  izooto.com: 1
  scorecardresearch.com: 1
 extended:
  ##.scc
  ##.follow
```
</details>

**Comment by mapx-** [comment]
@ashutoshgoyal do not open issues if you do not respond our questions
see again:
https://github.com/uBlockOrigin/uAssets/issues/20080#issuecomment-1762636735
