### ISSUE TITLE
No works inline script blocking rules

### ISSUE THREAD

**Issue by kovacsattila-hun** [uBlockOrigin/uAssets#203]
### Describe the issue

No works inline script blocking...

### One or more specific URLs where the issue occurs

Example:
`openspeedtest.com##script:contains(Adblocker)`
`http://openspeedtest.com`

### Screenshot in which the issue can be seen

http://i.imgur.com/Lul4aew.png

### Steps for anyone to reproduce the issue

1. Trying an inline script block
2. No work inline script block rule(s)

### Your settings

Default settings, default filterlists

- Browser/version: Google Chrome 54 Windows 64 bit
- uBlock Origin version: 1.9.16

##### Your filter lists

Default filterlists -- Badware risks

**Comment by IDKwhattoputhere** [comment]
Try `openspeedtest.com#@#.adsbox` or `@@||openspeedtest.com^$generichide`

**Comment by kovacsattila-hun** [comment]
Other inline scripts block no works too.

Other example:
`hungliaonline.com##script:contains(adblocker)`

Bad format or bug?

**Comment by IDKwhattoputhere** [comment]
https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#caveats
