### ISSUE TITLE
tide.com

### ISSUE THREAD

**Issue by destroyplutarchy** [uBlockOrigin/uAssets#20307]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://tide.com/en-us/shop/type/liquid/tide-hygienic-clean-heavy-duty-10x-liquid-laundry-detergent-free`

### Description

Just wanting to report uBlock Origin is blocking the Find Retailer option on product pages for Tide.com.
i have absolutely no computing expertise so please bear with me.
This was the only option i found for communicating this information toward a solution.
Wish there was an option that wasn't labyrinthine and didn't require background knowledge.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1312" alt="Screenshot 2023-10-26 at 11 59 56 AM" src="https://github.com/uBlockOrigin/uAssets/assets/149093283/bdf3a83c-9531-46bb-a34d-9c518aa6a4a0">

</details>

### Configuration

<details>
<summary>Details</summary>

```
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105976
 cosmetic: 40274
 scriptlet: 18882
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72225-15, 1m
  easyprivacy: 32940-64, 1m
  plowe-0: 3727-1073, 1m
  ublock-badware: 7330-138, 1m
  ublock-filters: 35299-147, 1m
  ublock-privacy: 614-6, 1m
  ublock-quick-fixes: 180-131, 1m
  ublock-unbreak: 2131-32, 1m
  urlhaus-1: 12440-0, 28m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 109 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```

</details>

**Comment by okiehsch** [comment]
Update your `uBO-unbreak` list, the Find Retailer option should show up after that.

**Comment by destroyplutarchy** [comment]
@okiehsch
Solved!  Very much appreciated.

**Comment by okiehsch** [comment]
@ryanbr for EasyPrivacy.
