### ISSUE TITLE
dialin.teams.microsoft.com: breakage

### ISSUE THREAD

**Issue by RobertNaylorMY** [uBlockOrigin/uAssets#20300]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dialin.teams.microsoft.com/usp`

### Category

breakage

### Description

Blocking `https://dialin.teams.microsoft.com/dialin-cdn-root/usp/1.220420.3/assets/js/aria-web-telemetry-2.7.1.min.js` is preventing the page from loading 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 106289
 cosmetic: 40267
 scriptlet: 18898
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72213-15, now
  easyprivacy: 32937-64, now
  plowe-0: 3727-1073, now
  ublock-badware: 7330-138, now
  ublock-filters: 35293-147, now
  ublock-privacy: 613-6, now
  ublock-quick-fixes: 164-96, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 12765-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4638 ms (selfie)
 maxAssetCacheWait: 3697 ms
popupPanel:
 blocked: 1
 network:
  microsoft.com: 1
```
</details>

**Comment by mapx-** [comment]
Test

`@@||dialin.teams.microsoft.com/dialin-cdn-root/$script,1p`

**Comment by RobertNaylorMY** [comment]
Thanks - Both options fix the issue and the page loads fine
