### ISSUE TITLE
wcofun.tv: detection

### ISSUE THREAD

**Issue by 15143226** [uBlockOrigin/uAssets#20317]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wcofun.tv/family-guy-season-21-episode-4-the-munchurian-candidate`

### Category

detection

### Description

website detects adblockers (even if disabled), and disables the media player

### Other extensions used

poperblocker (disabled), and session manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105731
 cosmetic: 40290
 scriptlet: 18894
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 72260-15, 2m
  easyprivacy: 32887-64, 2m
  plowe-0: 3727-1073, 2m
  ublock-badware: 7331-138, 2m
  ublock-filters: 35318-147, 2m
  ublock-privacy: 613-6, 2m
  ublock-quick-fixes: 177-126, 2m
  ublock-unbreak: 2131-32, 2m
  urlhaus-1: 12215-0, 2m
filterset (user): [array of 4 redacted]
trustedset:
 removed:
  chrome-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 167 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 2
  sharethis.com: 1
 extended:
  ##.anti-ad
  ##+js(no-setTimeout-if, AdBlock)
  ##+js(set-constant, isAdBlockActive, false)
```
</details>

**Comment by avotoko** [comment]
reproduced on my end.
following filter works.
`
@@||embed.watchanimesub.net/inc/embed/clever_ads.js$script,domain=embed.watchanimesub.net
`

**Comment by mapx-** [comment]
`clever_ads` has been killed days ago, try updating your lists

**Comment by avotoko** [comment]
Confirmed.
Sorry. I skipped a necessary step.

**Comment by 15143226** [comment]
I n sis update my list be clearing cache and updating an still nothing.
Perhaps I'm missing something simple. Sorry I'm relatively new to all this.
Unlock specifically
