### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Cal157** [uBlockOrigin/uAssets#20312]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=6rEKTZDDYrY`

### Category

detection

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/149128029/8af1a90c-6253-4abb-bda0-0992df3b9a70)

### Other extensions used

This started today.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 105762
 cosmetic: 40281
 scriptlet: 18741
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36190-142, 24m
  ublock-badware: 7334-5, 24m
  ublock-privacy: 607-0, 24m
  ublock-unbreak: 2178-1, 24m
  ublock-quick-fixes: 167-25, 58m
  easylist: 72257-698, 24m
  easyprivacy: 32940-725, 24m
  urlhaus-1: 12215-0, 24m
  plowe-0: 3727-1, 24m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2497 ms
 maxAssetCacheWait: 367 ms
popupPanel:
 blocked: 9
 network:
  youtube.com: 2
  doubleclick.net: 4
  google.com: 1
  googlesyndication.com: 1
  gstatic.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

> - [X] I did not answer truthfully to **ALL** the above checkpoints.
