### ISSUE TITLE
solarmoviefreez.com [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2031]
URL(s) where the issue occurs

`http://solarmoviefreez.com/watch/a-mighty-wind-2003-online-free-solarmovie.html`

Describe the issue

![](https://i.imgur.com/sWyvTW6.png)

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.15.24

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
```
solarmoviefreez.com##script:inject(popads-dummy.js)
solarmoviefreez.com##center
```

**Comment by okiehsch** [comment]
@zaphodbeebblebrox `solarmoviefreez.com##script:inject(popads-dummy.js)` does not work, if you add a filter to test if it really defuses the popup you have to delete cookies, then reload the site, otherwise you might only think that the filter works.

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters

**Comment by ghajini** [comment]
`SolarMovie.cam`
Ads

**Comment by mapx-** [comment]
for popups
`solarmovie.cam##+js(abort-on-property-read.js, Date.prototype.toUTCString)`

but then when I want to play the video I get always a fake one

**Comment by mapx-** [comment]
or 4k is the fake one ?

**Comment by okiehsch** [comment]
`https://solarmovie.cam/2571-mowgli-legend-of-the-jungle-for-free.html`
I think you have to click "click to play"

**Comment by okiehsch** [comment]
`solarmovie.cam##+js(window.open-defuser.js)`
should fix the popup clicking that.

**Comment by ghajini** [comment]
`https://www3.solarmovie.vip/film/crown-and-anchor-28910/watching.html`
Popup ads
