### ISSUE TITLE
biletomat.pl: breakage

### ISSUE THREAD

**Issue by SuchSkill** [uBlockOrigin/uAssets#20322]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.biletomat.pl/en/bilety/zamowienie/bass-astral-2023-warszawa-14557/?event=bass-astral-2023-warszawa-14557&step=2`

### Description

Order of tickets don't work and results into infinite pending. During my checking it seems to come down to "uBlock filters – Ads" list as it's working 

Note: increase number of tickets to at least one for button NEXT button to start spinning

PS: useful detection message is blocked by default in the same "uBlock filters – Ads" 

### Other extensions used

I do use other blocking but verified in incognito mode with refreshed default lists 

### Screenshot(s)

<details>
<summary>spinning button</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/20545718/ab315768-3080-4d86-8baf-1f4f2fac5ee4)

</details>
<details>
<summary>Actually helpful blocking message. I would like to see it</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/20545718/9cbce879-7b5a-4790-a4e6-b97d4444dfe9)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104948
 cosmetic: 40293
 scriptlet: 18892
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 72089-15, 6m
  easyprivacy: 32879-64, 6m
  plowe-0: 3722-1072, 6m
  ublock-badware: 7337-138, 6m
  ublock-filters: 35320-147, 6m
  ublock-privacy: 613-6, 6m
  ublock-quick-fixes: 177-126, 6m
  ublock-unbreak: 2133-32, 6m
  urlhaus-1: 11610-0, 6m
filterset (user): [array of 373 redacted]
trustedset:
 added: [array of 38 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 156 ms (selfie)
 maxAssetCacheWait: 107 ms
popupPanel:
 blocked: 6
 network:
  biletomat.pl: 1
  facebook.net: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
```

</details>

**Comment by gwarser** [comment]
Blocking `pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` shows this for me

![image](https://github.com/uBlockOrigin/uAssets/assets/886325/52d2f095-f2db-4807-9e12-220db0e4ef99)

**Comment by gwarser** [comment]
Works now, thanks.
