### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Koenigsteve** [uBlockOrigin/uAssets#20329]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=h2n9qt58h5I`

### Category

detection

### Description

when I open a video than it says That I should turn off the Adblocker and if I turn it off it still say that I should turn it off.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Screenshot (161)](https://github.com/uBlockOrigin/uAssets/assets/149209327/7758c518-da09-4a7b-97d4-f4cbdf12a4cd)

### Configuration

<details>

```yaml
uBlock Origin: 1.48.4
Firefox: 119
filterset (summary): 
  network: 107584
  cosmetic: 44893
  scriptlet: 18781
  html: 1084
listset (total-discarded, last-updated): 
  added: 
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 1d.7h.5m
  default: 
    user-filters: 0-0, never
    ublock-filters: 36119-241, 2d.5h.59m
    ublock-badware: 7334-5, 2d.5h.58m
    ublock-privacy: 642-75, 1d.7h.6m
    ublock-unbreak: 2175-2, 2d.6h
    easylist: 72013-703, 5d.21h.29m
    easyprivacy: 33163-731, 5d.21h.28m
    urlhaus-1: 11610-0, 3h.8m
    plowe-0: 3724-1, 7d.2h.13m
    DEU-0: 7164-3, 3h.9m
    ublock-quick-fixes: 235-0, 7h.10m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    about-scheme
    moz-extension-scheme
switchRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 624 ms (selfie)
  maxAssetCacheWait: 291 ms
popupPanel: 
  blocked: 18
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
  blockedDetails: 
    youtube.com: 18
```
</details>

**Comment by gwarser** [comment]
> This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
