### ISSUE TITLE
matchendirect.fr: detection

### ISSUE THREAD

**Issue by rougeaden** [uBlockOrigin/uAssets#20324]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.matchendirect.fr/`

### Category

detection

### Description

Ad blocking detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 123669
 cosmetic: 49377
 scriptlet: 18881
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36212-219, now
  ublock-badware: 7359-5, now
  ublock-privacy: 607-0, now
  ublock-unbreak: 2179-1, now
  ublock-quick-fixes: 167-25, 2h
  easylist: 72089-769, now
  easyprivacy: 32879-724, now
  urlhaus-1: 11610-0, now
  plowe-0: 3722-1, now
  FRA-0: 28481-337, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2896 ms (selfie)
 maxAssetCacheWait: 1610 ms
popupPanel:
 blocked: 15
 network:
  adnext.fr: 2
  bkrtx.com: 1
  cloudflare.com: 1
  eacdn.com: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  googletagservices.com: 1
  stickyadstv.com: 3
  sync.tv: 2
 extended:
  ###googleAds
  ##.AdSense
  ##.ad-text
  ##.adSense
  ##.adBlock
  ##.adContent
  ###tux728x90
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
page to test => `https://www.matchendirect.fr/live-score/nice-clermont.html`
or other similar match
