### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by MaierTV** [uBlockOrigin/uAssets#20326]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection

### Description

Youtube detects Ublock

### Other extensions used

Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 107300
 cosmetic: 45074
 scriptlet: 18893
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7164-0, now
  easylist: 72096-21, now
  easyprivacy: 32883-73, now
  plowe-0: 3722-1073, now
  ublock-badware: 7330-138, 1h.48m
  ublock-filters: 35319-161, 1h.47m
  ublock-privacy: 613-6, now
  ublock-quick-fixes: 179-125, now
  ublock-unbreak: 2132-35, 1h.46m
  urlhaus-1: 11610-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-extension-scheme
  edge-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 606 ms (selfie)
 maxAssetCacheWait: 266 ms
popupPanel:
 blocked: 9
 network:
  youtube.com: 5
  csp.withgoogle.com: 1
  doubleclick.net: 3
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?\/(aclk\?…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
go to https://github.com/uBlockOrigin/uAssets/issues/19976
read and then report
