### ISSUE TITLE
fsl-stream.lu: popups

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#20339]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fsl-stream.lu/arsenal-stream/`

### Category

popups

### Description

Clicking on the video player will open a popup window.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.3rc9
Firefox: 119
filterset (summary):
 network: 104886
 cosmetic: 40311
 scriptlet: 18800
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36232-48, 2m
  ublock-badware: 7365-5, 2m
  ublock-privacy: 649-0, 2m
  ublock-unbreak: 2180-1, 2m
  ublock-quick-fixes: 167-116, 2m
  easylist: 72103-266, 1m
  easyprivacy: 32875-84, 1m
  urlhaus-1: 11530-0, 1m
  plowe-0: 3722-1073, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1094 ms
 maxAssetCacheWait: 488 ms
popupPanel:
 blocked: 10
 network:
  acacdn.com: 1
  acscdn.com: 2
  browsobsolete.com: 1
  ewikajs.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  humoralpurline.com: 1
  taboola.com: 1
  yandex.ru: 1
 extended:
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(abort-on-property-write, _pop)
  ##+js(nowebrtc)
  ##+js(no-window-open-if)
  ##+js(abort-current-script, JSON, break;case)
  ##+js(no-setTimeout-if, (), 150)
```
</details>

**Comment by stephenhawk8054** [comment]
Do you know any other live streams that still open?
