### ISSUE TITLE
reminimod.co: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#20337]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://reminimod.co/`

### Category

detection

### Description

Detect

### Other extensions used

Violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 119
filterset (summary):
 network: 106232
 cosmetic: 31561
 scriptlet: 18853
 html: 1085
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36542-390, 1h.36m
  ublock-badware: 7354-5, 1h.36m
  ublock-privacy: 649-1, 1h.36m
  ublock-unbreak: 2185-3, 1h.36m
  ublock-quick-fixes: 167-25, 1h.36m
  adguard-mobile: 8787-127, 1h.36m
  easylist: 72103-16700, 1h.36m
  easyprivacy: 32875-732, 1h.36m
  urlhaus-1: 11480-0, 1h.36m
  plowe-0: 3722-1, 1h.36m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 18316 ms (selfie)
 maxAssetCacheWait: 896 ms
popupPanel:
 blocked: 10
 network:
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 6
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by BlazeFTL** [comment]
```
reminimod.co##+js(no-fetch-if, ads)
reminimod.co###wpsafe-link:style(display: block !important;)
reminimod.co###wpsafe-link:others()

**Comment by mapx-** [comment]
@aicynide when it's about a shortener you have to provide an example link

**Comment by BlazeFTL** [comment]
@mapx- `go.rocklinks.net/52nr0wl`
