### ISSUE TITLE
[nsfw] tapenoads.com: detection

### ISSUE THREAD

**Issue by Bug-Cache** [uBlockOrigin/uAssets#20336]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tapenoads.com/v/9o2D9yq9bKCaeBK/MEYD-851.mp4`

### Category

detection

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/98657967/839d9893-b417-42df-827e-e65190e6b3c1)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 111294
 cosmetic: 113661
 scriptlet: 26933
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt: 10154-5, now
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid_plus.adfl.txt: 524-4, now
  easylist-annoyances: 4149-34, now
  easylist-notifications: 2960-81, now
  fanboy-cookiemonster: 48691-216, now
  fanboy-social: 16309-10, now
  ublock-annoyances: 5658-77, now
  ublock-cookies-easylist: 412-412, now
 default:
  user-filters: 15-2, never
  easylist: 72103-27, now
  easyprivacy: 32875-151, now
  plowe-0: 3722-1072, now
  ublock-badware: 7361-140, now
  ublock-filters: 35338-278, now
  ublock-privacy: 655-8, now
  ublock-quick-fixes: 178-127, now
  ublock-unbreak: 2134-37, now
  urlhaus-1: 11480-0, now
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1243 ms (selfie)
 maxAssetCacheWait: 320 ms
popupPanel:
 blocked: 7
 network:
  adforcast.com: 2
  rkgwzfwjgk.com: 1
  wamarapayor.com: 1
  yandex.ru: 1
  zawavnnukmha.com: 1
  zimpolo.com: 1
 extended:
  ##.skyscraper.ad
  ##.grecaptcha-badge
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
- only popup, no detection
- reset to default lists / settings, test again
