### ISSUE TITLE
play.radiojavan.com: ads

### ISSUE THREAD

**Issue by taktaerfan** [uBlockOrigin/uAssets#20338]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://play.radiojavan.com/`

### Category

ads

### Description

The website plays its ads in the middle of the online listening to the songs.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 104880
 cosmetic: 40311
 scriptlet: 18797
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36228-138, now
  ublock-badware: 7360-5, 1h.59m
  ublock-privacy: 649-0, now
  ublock-unbreak: 2180-2, 1h.58m
  ublock-quick-fixes: 167-25, now
  easylist: 72103-698, now
  easyprivacy: 32875-724, now
  urlhaus-1: 11530-0, now
  plowe-0: 3722-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 301 ms (selfie)
 maxAssetCacheWait: 92 ms
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
I registered an account.

@taktaerfan can you provide some precise steps in reproducing the ads?
I listened some songs in a playlist, some with fast forward etc but no ad

**Comment by mapx-** [comment]
ok, already seen ..
