### ISSUE TITLE
ilil.in: popups

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#20335]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nishankhatri.xyz/`

### Category

popups

### Description

`https://ilil.in/N4BGFsyMT`

### Other extensions used

Violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 119
filterset (summary):
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated): [none]
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: ?
 maxAssetCacheWait: ?
popupPanel:
 blocked: 29
 network:
  doubleclick.net: 22
  googlesyndication.com: 2
  googletagmanager.com: 1
  unibotscdn.com: 4
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##+js(noeval-if, /chp_?ad/)
```
</details>

**Comment by mapx-** [comment]
hacked domain

```
      "https://bitly.pw/applegyaan",
      "https://bitly.pw/wirexs",
      "https://bitly.pw/techwazir",
      "https://bitly.pw/heathygyaan",
      "https://bitly.pw/mycctvcam",
      "https://bitly.pw/moniitors",
      "https://bitly.pw/earpot",
      "https://bitly.pw/awrix",
      "https://bitly.pw/aieeb",
      "https://bitly.pw/ailooz",
      "https://bitly.pw/e-bikewale",
       "https://bitly.pw/aunin",
     "https://bitly.pw/luxery-cars",
      "https://bitly.pw/gptgyan"
    
      
  ];

    var delay = 0; // Delay before opening all URLs (15,000 milliseconds)

  function openAllUrls() {
    urls.forEach(function(url) {
      window.open(url);
    });
  }

  setTimeout(function() {
    openAllUrls();
  }, delay);
```
