### ISSUE TITLE
youtube.com: ads

### ISSUE THREAD

**Issue by Bazooka8416** [uBlockOrigin/uAssets#20332]
### Prerequisites

- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=L_l1iNNAsJw`

### Category

ads

### Description

ads

### Other extensions used

'Improve YouTube!' 
Augmented Steam
Bitwarden - Free Password Manager
DeArrow - Better Titles and Thumbnails
I don't care about cookies
Enhancer for YouTube™
QuillBot
LocalCDN
Return YouTube Dislike
Ruffle - Flash Emulator
Speedtest by Ookla
SponsorBlock for YouTube
uBlock Origin
Violentmonkey
VT4Browsers

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-10-28 170414](https://github.com/uBlockOrigin/uAssets/assets/149220445/c0c3fd92-a349-42f8-914d-5f54c10fbfd9)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 112651
 cosmetic: 141651
 scriptlet: 29566
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-cookies: 27949-1591, 9m
  adguard-mobile-app-banners: 4702-17, 9m
  adguard-other-annoyances: 13696-14, 9m
  adguard-popup-overlays: 25140-101, 9m
  adguard-social: 21938-2065, 9m
  adguard-widgets: 2332-38, 9m
  easylist-annoyances: 4019-1063, 9m
  easylist-chat: 143-20, 9m
  easylist-newsletters: 6591-2267, 9m
  easylist-notifications: 2960-1882, 9m
  fanboy-cookiemonster: 48685-19745, 9m
  fanboy-social: 16309-12101, 9m
  [4 lists not shown]: [too many]
 default:
  user-filters: 74-1, never
  easylist: 72104-16035, 9m
  easyprivacy: 32875-180, 9m
  ublock-badware: 7356-138, 9m
  ublock-filters: 35337-727, 9m
  ublock-privacy: 613-7, 9m
  ublock-quick-fixes: 181-131, 9m
  ublock-unbreak: 2134-38, 9m
  urlhaus-1: 11480-0, 9m
filterset (user): [array of 74 redacted]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 10 redacted]
hostRuleset:
 added: [array of 64 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1488 ms (selfie)
 maxAssetCacheWait: 290 ms
popupPanel:
 blocked: 56
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 network:
  youtube.com: 41
  doubleclick.net: 3
  googlevideo.com: 12
```
</details>

**Comment by stephenhawk8054** [comment]
> ignoreGenericCosmeticFilters: true
> no-cosmetic-filtering: true

You are enabling `Ignore generic cosmetic filters` and disabling cosmetic filtering on youtube page. Reset to default settings and test again.

---

Also

> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
