### ISSUE TITLE
irctc.co.in: ads

### ISSUE THREAD

**Issue by kjambunathan** [uBlockOrigin/uAssets#20346]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.irctc.co.in/nget/train-search`

### Category

ads

### Description

This is an Indian Govt. website for Railway Reservation.  It is a high-volume and trusted website.  I  find it surprising that there are annoying popups on the page which aren't caught by uBlock

If you open the hamburger menu (I am on desktop site), and click login there are annoying ads right near the login captcha .  
I would appreciate if the ads right in train search page, and login hamburger are nuked.

### Other extensions used

I have India-specific filters on

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

The uBlock logger may have  reported my half-baked rules (which weren't obviously working)

For the screenshots below, I have removed all matches to `irctc.co.in` in my rules.

This is what I see when I access https://www.irctc.co.in/nget/train-search

![2023-10-29_04-24](https://github.com/uBlockOrigin/uAssets/assets/19869864/4fad6468-c452-4d65-82c3-05368366cb52)

--------

Visit https://www.irctc.co.in/nget/train-search, click on hamburger menu and click 'Login'.  

- There are annoying ads right above the captcha.
- There are annoying ads where there is whitespace and where I have typed my annotations on screenshot

 (My screenshot doesn't show the ads.  No ads in screenshot may be because of my half-baked rules or  because of 'India'-specific rules.  Will be happy if some one competent could review and update the 'India'-specific rules)

The Chatbot pop-up is very very annoying.  As a naive user, I can't nuke  it at all.  

Thanks in advance.

![2023-10-29_04-35](https://github.com/uBlockOrigin/uAssets/assets/19869864/6c689330-15f3-4b68-81b5-4b41ce130832)

------------

There is a mini-chatbot popup behind the big rectangular chatbot pop up.  Please update your rules to nuke that mini monster.  (The mini monster shows up when I am logged in to the site, and see for example my reserved tickets.  I can't share the screenshots because of privacy reasons.  This is FYI, and heads up  Just in case there is a India-specific volunteer, who is also a frequent Indian Railways user.)

![2023-10-29_04-50](https://github.com/uBlockOrigin/uAssets/assets/19869864/8e865aee-1eee-45f1-966c-15794fc08be9)

![2023-10-29_04-53](https://github.com/uBlockOrigin/uAssets/assets/19869864/36afa152-deb8-43b0-b911-6e17920918d0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 115
filterset (summary):
 network: 109747
 cosmetic: 48261
 scriptlet: 18786
 html: 1083
listset (total-discarded, last-updated):
 removed:
  ublock-quick-fixes: null
 added:
  IND-0: 12782-0, 22m
 default:
  user-filters: 51-1, never
  ublock-filters: 36245-52, 23m
  ublock-badware: 7365-5, 23m
  ublock-privacy: 649-0, 23m
  ublock-unbreak: 2180-0, 23m
  easylist: 72112-702, 23m
  easyprivacy: 32875-724, 23m
  urlhaus-1: 11530-0, 22m
  plowe-0: 3722-1, 22m
filterset (user): [array of 51 redacted]
trustedset:
 added: [array of 111 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 20867 ms (selfie)
 maxAssetCacheWait: 17489 ms
popupPanel:
 blocked: 11
 network:
  irctc.co.in: 1
  corover.ai: 2
  doubleclick.net: 1
  googletagmanager.com: 2
  googletagservices.com: 1
  izooto.com: 1
  nlpcaptcha.in: 1
  unibotscdn.com: 1
  windows.net: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by stephenhawk8054** [comment]
The only ads on the first picture are

```adb
irctc.co.in###dod
irctc.co.in###splash-scrollable
```

The others are self-promotion/chat sections, we don't block that. You might need to report as annoyances on EasyList or Adguard repos.

---

About the 2nd picture, I can't find the hamburger menu to click.

---

@ghajini I guess this should be in `IndianList` ?

**Comment by kjambunathan** [comment]
> The others are self-promotion/chat sections, we don't block that. You might need to report as annoyances on EasyList or Adguard repos.

If you look closely there is a small ribbon in red, that has words 'Ad' on it.  May be those could be blocked.

> About the 2nd picture, I can't find the hamburger menu to click.

The arrow pointing towards top right ... that  is where the hamburger menu is (basically 4-5 horizontal strips, whatever it is called) If you click on that then login prompt will come--but the URL on the address bar remains the same.  The login window is modal, and is overlaid on the main browser page.  You can see that on screenshot.

https://user-images.githubusercontent.com/19869864/278841498-6c689330-15f3-4b68-81b5-4b41ce130832.png

>  EasyList or Adguard repos.

Yes. I will take it up with them.  If @ghajini is an Indian user, he will have better context to evaluate what I am saying.  That chat popup's signature keeps changing ... and it is very adamant.

**Comment by stephenhawk8054** [comment]
> If you look closely there is a small ribbon in red, that has words 'Ad' on it. May be those could be blocked.

The filters I gave above don't work?

```adb
irctc.co.in###dod
irctc.co.in###splash-scrollable
```

**Comment by kjambunathan** [comment]
> > If you look closely there is a small ribbon in red, that has words 'Ad' on it. May be those could be blocked.
> 
> The filters I gave above don't work?
> 
> ```
> irctc.co.in###dod
> irctc.co.in###splash-scrollable
> ```

It **_partly_** works

I didn't realize that was a suggestion that I follow through.  This is what I did.

1. Copied those lines to a text file
2. Under `My filters`->`Import and Append`, and then followed it up with `Append Changes`
3. Refresh browser

### Before Screenshot
![2023-10-29_08-05](https://github.com/uBlockOrigin/uAssets/assets/19869864/1f2066a1-7b51-48f6-8871-f9e11a0d9f3d)


### After Screenshot

![2023-10-29_08-08](https://github.com/uBlockOrigin/uAssets/assets/19869864/3cea15fc-f7cb-46a3-8573-3051a1bc471d)

**Comment by stephenhawk8054** [comment]
What do you mean by `partly works`?

You said

> there is a small ribbon in red, that has words 'Ad' on it

The section you showed as `This is an ad` in the second screenshot does not have `words 'Ad' on it`

**Comment by kjambunathan** [comment]
> The section you showed as `This is an ad` in the second screenshot does not have words 'Ad' on it

It is good to verify if it is an ad or not with other users ... Check with what @ghajini says.  He would concur with me.

Could you please push what you shared it with me.  It improves things drastically.

**Comment by mapx-** [comment]
@kjambunathan 

report directly at the [Indian list repository](https://github.com/mediumkreation/IndianList/issues)

@mediumkreation

**Comment by kjambunathan** [comment]
TATA AIG Insurance is an ad.  (I am sure IRCTC is not in insurance basis)

Just curiois ...  what is the difference between self promotion and an ad.
