### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by TotalImportance8529** [uBlockOrigin/uAssets#20340]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description

Can't scroll on mobile reddit.

### URL(s) where the issue occurs.

`https://www.reddit.com/r/uBlockOrigin/?rdt=48244`

### Notes

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +12 | ##.promotedlink:not([style^="height: 1px;"]) |  | `www.reddit.com` |  | post | dom | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +9 | /shreddit/perfmetrics | -- | `www.reddit.com` | 1 | post | ping | `https://www.reddit.com/svc/shreddit/perfMetrics` |
| +9 | /shreddit/perfmetrics | -- | `www.reddit.com` | 1 | post | ping | `https://www.reddit.com/svc/shreddit/perfMetrics` |
| +9 | \|\|w3-reporting.reddit.com^ | -- | `www.reddit.com` | 1 | post | ping | `https://w3-reporting.reddit.com/reports` |
| +5 | \|\|redditstatic.com/shreddit/sentry-$from=reddit.com | -- | `www.reddit.com` | 3 | get | script | `https://www.redditstatic.com/shreddit/sentry-94f7e90f.js` |
| +5 | /shreddit/perfmetrics | -- | `www.reddit.com` | 1 | post | ping | `https://www.reddit.com/svc/shreddit/perfMetrics` |
| +5 | /shreddit/perfmetrics | -- | `www.reddit.com` | 1 | post | ping | `https://www.reddit.com/svc/shreddit/perfMetrics` |
| +5 | \|\|w3-reporting.reddit.com^ | -- | `www.reddit.com` | 1 | post | ping | `https://w3-reporting.reddit.com/reports` |
| +4 | ##xpromo-top-button |  | `www.reddit.com` |  | post | dom | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +4 | ##shreddit-experience-tree |  | `www.reddit.com` |  | post | dom | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +4 | ##reddit-breadcrumbs |  | `www.reddit.com` |  | post | dom | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +4 | ##body:style(pointer-events:auto !important;) |  | `www.reddit.com` |  | post | dom | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +4 | ##[slot="use-app"] |  | `www.reddit.com` |  | post | dom | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +4 | \|\|w3-reporting.reddit.com^ | -- | `www.reddit.com` | 1 | head | xhr | `https://w3-reporting.reddit.com/policy` |
| +3 | /shreddit/perfmetrics | -- | `www.reddit.com` | 1 | post | ping | `https://www.reddit.com/svc/shreddit/perfMetrics` |
| +3 | \|\|w3-reporting.reddit.com^ | -- | `www.reddit.com` | 1 | post | ping | `https://w3-reporting.reddit.com/reports` |
| +3 | /assets/ads/*$from=~outlook.live.com | -- | `www.reddit.com` | 3 | get | image | `https://www.redditstatic.com/shreddit/assets/ads/1.png` |
| +2 | ##+js(abort-on-property-write, STICKY_CANARY) |  | `www.reddit.com` |  | get | scriptlet | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +2 | ##+js(remove-class, scroll-disabled, body, stay) |  | `www.reddit.com` |  | get | scriptlet | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +2 | ##+js(set-local-storage-item, xpromo-consolidation, 1) |  | `www.reddit.com` |  | get | scriptlet | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +2 | ##+js(addEventListener-defuser, block-body-scrolling) |  | `www.reddit.com` |  | get | scriptlet | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +2 | ##+js(json-prune, data.children.[].data.outbound_link) |  | `www.reddit.com` |  | get | scriptlet | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +2 | ##+js(json-prune, data.*.elements.edges.[].node.outboundLink) |  | `www.reddit.com` |  | get | scriptlet | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +2 | ##+js(replace-node-text, script, outboundUrl, outbound) |  | `www.reddit.com` |  | get | scriptlet | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +1 | *$document,permissions=browsing-topics=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +1 | *$document,permissions=idle-detection=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +1 | *$document,permissions=join-ad-interest-group=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +1 | *$document,permissions=run-ad-auction=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +1 | *$document,permissions=attribution-reporting=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/?rdt=48244` |
| +0 | *$document,permissions=browsing-topics=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/` |
| +0 | *$document,permissions=idle-detection=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/` |
| +0 | *$document,permissions=join-ad-interest-group=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/` |
| +0 | *$document,permissions=run-ad-auction=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/` |
| +0 | *$document,permissions=attribution-reporting=(),from=~localhost | -- | `www.reddit.com` | 1 | get | doc | `https://www.reddit.com/r/uBlockOrigin/` |
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 199808
 cosmetic: 121732
 scriptlet: 25608
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 22383-12, 22h.31m
  adguard-spyware-url: 1291-5, 1d.23h.45m
  block-lan: 54-0, 1d.23h.44m
  curben-phishing: 75498-10, 23h.12m
  easylist-annoyances: 4017-32, 1d.23h.44m
  easylist-chat: 143-0, 1d.23h.44m
  easylist-newsletters: 6584-15, 1d.23h.44m
  easylist-notifications: 2960-82, 7m
  fanboy-cookiemonster: 48656-220, 1d.23h.44m
  fanboy-social: 16303-13, 1d.23h.44m
  ublock-annoyances: 5651-81, 1d.23h.44m
  ublock-cookies-easylist: 408-408, 1d.23h.44m
 default:
  user-filters: 14-0, never
  easylist: 72225-20, 1d.23h.44m
  easyprivacy: 32940-163, 1d.23h.44m
  plowe-0: 3727-1075, 1d.23h.44m
  ublock-badware: 7330-147, 1d.23h.44m
  ublock-filters: 35299-178, 1d.23h.44m
  ublock-privacy: 614-85, 1d.23h.44m
  ublock-quick-fixes: 177-130, 9h.21m
  ublock-unbreak: 2131-37, 1d.23h.44m
  urlhaus-1: 11610-4, 23h.9m
filterset (user): [array of 14 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 autoCommentFilterTemplate: none
supportStats:
 allReadyAfter: 6647 ms
 maxAssetCacheWait: 3590 ms
```
</details>

**Comment by mapx-** [comment]
add

`reddit.com##body:style(overflow: auto !important;)`

**Comment by TotalImportance8529** [comment]
Ok, the rule fixed it.

**Comment by D4niloMR** [comment]
@mapx- This filter is applying to desktop and causes double scrollbar

**Comment by mapx-** [comment]
is it ok now ?

**Comment by D4niloMR** [comment]
Yes, it's fixed now
