### ISSUE TITLE
neko-sama.fr: detection

### ISSUE THREAD

**Issue by The10axe** [uBlockOrigin/uAssets#20345]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.neko-sama.fr/anime/episode/19666-toaru-ossan-no-vrmmo-katsudouki-04_vostfr`

### Category

detection

### Description

The video player says that you need to disable adblocker in order for the video to play, or add "FuseVideo" to the list of whitelisted website.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 123597
 cosmetic: 49399
 scriptlet: 18930
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36228-215, 1h.13m
  ublock-badware: 7360-5, 1h.12m
  ublock-privacy: 649-0, now
  ublock-unbreak: 2180-2, 1h.11m
  ublock-quick-fixes: 173-25, now
  easylist: 72103-769, now
  easyprivacy: 32875-724, now
  urlhaus-1: 11530-0, 1h.10m
  plowe-0: 3722-1, now
  FRA-0: 28481-337, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 158 ms (selfie)
 maxAssetCacheWait: 68 ms
popupPanel:
 blocked: 20
 network:
  akenegappier.com: 4
  betteradsystem.com: 2
  cloudflareinsights.com: 2
  d2kk0o3fr7ed01.cloudfront.net: 2
  fusevideo.io: 8
  rxeosevsso.com: 2
 extended:
  ##body > a
  ##a[href^="https://buqkrzbrucz.com/"]
```
</details>

**Comment by mapx-** [comment]
force update all your filter lists
