### ISSUE TITLE
gozofinder.com: ads

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#20342]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gozofinder.com/cse/ulozto/en?query=test`

### Category

ads

### Description

Ad box (with the “Web advert” heading) on top of the search page and in the middle of search results.

### Other extensions used

- Augmented Steam
- Breakthrough Twitter Login Wall
- F.B Purity - Cleans up Facebook
- Tab Auto Refresh
- ySense Addon

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/22180480/a19a7e55-200c-4f9c-9fce-f42d305eefaa)

![obraz](https://github.com/uBlockOrigin/uAssets/assets/22180480/4ac15094-9bdd-425e-aef4-21ddcd1d9620)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 106574
 cosmetic: 49340
 scriptlet: 22710
 html: 1284
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5619-15, 3m
 default:
  user-filters: 41-0, never
  ublock-filters: 36228-177, 4m
  ublock-badware: 7365-5, 4m
  ublock-privacy: 649-0, 4m
  ublock-unbreak: 2180-2, 4m
  ublock-quick-fixes: 167-25, 4m
  easylist: 72103-715, 3m
  easyprivacy: 32875-724, 3m
  urlhaus-1: 11530-0, 3m
  plowe-0: 3722-1, 3m
  POL-0: 8006-27, 3m
  POL-2: 1279-12, 48m
filterset (user): [array of 42 redacted]
trustedset:
 added: [array of 33 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1342 ms
 maxAssetCacheWait: 584 ms
popupPanel:
 blocked: 4
 network:
  bbelements.com: 3
  sentry.io: 1
```
</details>

**Comment by mapx-** [comment]
add

```
gozofinder.com##.advert-iframe
gozofinder.com##[data-testid="advert"]
```

@ryanbr
