### ISSUE TITLE
emol.com [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2035]
URL(s) where the issue occurs

`http://www.emol.com/noticias/Deportes/2018/04/19/903201/RuizTagle-confirmo-cuanto-le-pagaron-a-Pablo-Guede-por-salir-de-Colo-Colo-y-quien-lo-reemplazara-mientras-buscan-tecnico.html`

Describe the issue

![](https://i.imgur.com/4lz7Idm.png)
![](https://i.imgur.com/QyY29x7.png)

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.15.24

Settings

Default

**Comment by KiLL4FuNK** [comment]
@diaux @Alex-302

**Comment by mapx-** [comment]
or
```
||emol.cl/*/publicidadsetup/
||emol.cl/*/json_banners/
```

**Comment by Alex-302** [comment]
I don't see these ads with our filter.
