### ISSUE TITLE
links.shrinksea.com: breakage

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#20354]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://links.shrinksea.com/gzuM7`

### Category

breakage

### Description

The countdown stops at zero and nothing happens.

### Other extensions used

None that interfere with uBlock.

### Screenshot(s)

No banner displayed
![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/5b1603c0-4a86-4946-8dda-dcefbd3287dc)

The counter stops at zero and nothing happens.
![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/babf6744-4cd5-4856-869a-bd4cdd2afd39)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 146107
 cosmetic: 114742
 scriptlet: 23321
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1666-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2472-10, now
  RUS-0: 40079-168, now
  fanboy-cookiemonster: 48692-229, now
 default:
  FRA-0: 28481-40, now
  easylist: 72117-118, now
  easyprivacy: 32873-632, now
  plowe-0: 3722-1088, now
  ublock-badware: 7391-152, now
  ublock-filters: 35287-261, now
  ublock-privacy: 655-54, now
  ublock-quick-fixes: 184-123, 1h.50m
  ublock-unbreak: 2134-38, now
  urlhaus-1: 11550-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 226 ms (selfie)
 maxAssetCacheWait: 94 ms
popupPanel:
 blocked: 1
 network:
  arvigorothan.com: 1
 extended:
  ##.myTestAd
  ###cookie-pop
  ##div.cookie-message
  ##div.cookie-confirm
```
</details>

**Comment by mapx-** [comment]
Even disabling uBO does not work

**Comment by BlazeFTL** [comment]
@x-R0b0T-x Check `http://shrinksea.com/7oEu`
```
shrinksea.com##+js(set, blurred, false)
shrinksea.com##+js(nostif, checkAdblockUser)
shrinksea.com##+js(aopr, app_vars.force_disable_adblock)
shrinksea.com##+js(rmnt, script, window.open)
updrop.link###humanbutton, #wpsafe-link:style(display: block !important;)
updrop.link###humanbutton, #wpsafe-link:others()
links.shrinksea.com##.animated.zoomIn.wow.text-center.py-5
@@*$ghide,domain=shrinksea.com
links.shrinksea.com##center
