### ISSUE TITLE
amazon.in: breakage

### ISSUE THREAD

**Issue by anuraag488** [uBlockOrigin/uAssets#20351]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.amazon.in/b/?_encoding=UTF8&node=1389401031&ref_=in_cat_halo_mweb_jupiter23_mobiles&pf_rd_p=b838c658-d838-491c-8187-fceb898a927e&pd_rd_wg=iPBvU&pf_rd_r=86BRV3T6E28QKZ3Y06PZ&content-id=amzn1.sym.b838c658-d838-491c-8187-fceb898a927e&pd_rd_w=08T8n&painterId=feature-shortcut-gwm-card&pd_rd_r=1ea3dab0-d23d-48b9-908b-50dfd733cf7f`

### Category

breakage

### Description

There is a pop up appears if i disable uBO. After dismiss of that popup i can scroll that page. But with uBO I can't scroll down that page

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231029-111441_Firefox](https://github.com/uBlockOrigin/uAssets/assets/7353086/9d4fe775-1f3e-4c01-b724-b05c1b97a310)
![Screenshot_20231029-111325_Firefox](https://github.com/uBlockOrigin/uAssets/assets/7353086/fb5a2e08-c3de-4de9-b1d9-b095575392d5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 119
filterset (summary):
 network: 106311
 cosmetic: 31581
 scriptlet: 18862
 html: 1087
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36563-390, 5m
  ublock-badware: 7359-5, 5m
  ublock-privacy: 649-1, 5m
  ublock-unbreak: 2185-3, 5m
  ublock-quick-fixes: 173-25, 5m
  adguard-mobile: 8787-127, 5m
  easylist: 72111-16700, 5m
  easyprivacy: 32875-732, 5m
  urlhaus-1: 11550-0, 5m
  plowe-0: 3722-1, 5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 497 ms (selfie)
 maxAssetCacheWait: 187 ms
popupPanel:
 blocked: 10
 network:
  amazon.in: 5
  amazon-adsystem.com: 2
  amazon.com: 1
  d2ef20sk9hi1u3.cloudfront.net: 1
  dr3fr5q4g2ul9.cloudfront.net: 1
 extended:
  ##div[cel_widget_id*="_ad-placements-"]
  ##div[cel_widget_id^="adplacements:"]
  ##section[class*="csm-placement-id"]
```
</details>

**Comment by mapx-** [comment]
If you keep enabled uBO => do you still have issues ? (without first disabling it, click dismiss, reenabling uBO)

**Comment by mapx-** [comment]
try

`amazon.in##body:style(overflow: auto !important;)`

however it's a weird case of a combinartion uBO on / off, so will not be "fixed" in some list
