### ISSUE TITLE
[nsfw] app.plex.tv: ads

### ISSUE THREAD

**Issue by Anarchnymous** [uBlockOrigin/uAssets#20357]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.plex.tv/desktop/`

### Category

ads

### Description

It used to block the ads on this site before but it is not blocking them now.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 105014
 cosmetic: 40316
 scriptlet: 18752
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36134-46, now
  ublock-badware: 7395-5, now
  ublock-privacy: 649-0, now
  ublock-unbreak: 2179-2, now
  ublock-quick-fixes: 167-108, now
  easylist: 72144-697, now
  easyprivacy: 32873-724, now
  urlhaus-1: 11635-0, now
  plowe-0: 3722-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 972 ms
 maxAssetCacheWait: 5 ms
popupPanel:
 blocked: 4
 network:
  plex.tv: 1
  springserve.com: 2
  tremorhub.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
app.plex.tv##+js(json-prune, MediaContainer.Metadata.[].Ad)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by UserPizza** [comment]
exporadic video-ads in the videos of plex.tv

`https://watch.plex.tv/watch/movie/the-big-short`
