### ISSUE TITLE
open.spotify.com: ads

### ISSUE THREAD

**Issue by karigithub2000** [uBlockOrigin/uAssets#20359]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://open.spotify.com/playlist/1hxRJnJTcix6Qp6v3Rbkx0`

### Category

ads

### Description

Originally, remnants of ads remained on the Spotify web player (the music would pause for about 10 seconds while the ad images showed in the "now playing" section), after updating the filter lists ads are now audibly playing in their entirety.

### Other extensions used

Search by Image, Hide shorts for Youtube, Honey, F-B Hide Recommendations and Reels, SponsorBlock for Youtube - Skip Sponsorships, Firefox Translations, Google Translate, Pinterest Save Button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105025
 cosmetic: 40316
 scriptlet: 18755
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36137-130, now
  ublock-badware: 7400-5, now
  ublock-privacy: 649-0, now
  ublock-unbreak: 2180-2, now
  ublock-quick-fixes: 167-25, now
  easylist: 72144-697, now
  easyprivacy: 32879-724, now
  urlhaus-1: 11635-0, now
  plowe-0: 3722-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 846 ms
 maxAssetCacheWait: 315 ms
popupPanel:
 blocked: 34
 network:
  audio-ak-spotify-com.akamaized.net: 1
  doubleclick.net: 4
  googleoptimize.com: 1
  googletagmanager.com: 1
  sentry.io: 27
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by liamengland1** [comment]
Can't reproduce, ads were skipped on my side by `||akamaized.net/audio/$media,redirect=noop-1s.mp4:10,from=open.spotify.com`

**Comment by mapx-** [comment]
@karigithub2000 

Open uBO logger, refresh spotify page. When you'll get an (audio)ad, go into the logger, see what media requests are there and post here a screenshot

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/1e0d3736-db14-46f8-a378-d6923e8f8701)

**Comment by scannama** [comment]
I am also getting ads, this what the logger shows:

![image](https://github.com/uBlockOrigin/uAssets/assets/73968372/883961ff-2886-426d-9da6-1983cdbd3b3e)

**Comment by mapx-** [comment]
well, that is already blocked ..

**Comment by scannama** [comment]
I found this too: 
![image](https://github.com/uBlockOrigin/uAssets/assets/73968372/183dcd6a-58c0-4dc5-86d6-d2bb9abb7b1c)

**Comment by okiehsch** [comment]
Does adding 
`||amillionads.com^$media,redirect=noop-1s.mp4:10,from=open.spotify.com`
to your filter list fix the issue on your end?

**Comment by mapx-** [comment]
I guess we could add

`*$media,redirect=noop-1s.mp4:10,from=open.spotify.com`

`media` requests are used only for ads

**Comment by okiehsch** [comment]
Hm, I would rather not to be honest as long as they don't start using revolving ad servers we should keep blocking the adservers itself imo.
`amillionads` should bel blocked in `EasyList` anyway. @ryanbr

**Comment by mapx-** [comment]
added to our list

**Comment by mapx-** [comment]
@karigithub2000 just comment here if you find some other media request
