### ISSUE TITLE
[nsfw] redd.tube: ads

### ISSUE THREAD

**Issue by Tornadoalley** [uBlockOrigin/uAssets#20361]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [x] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.redd.tube/video/6aa0188fe727b898389006894afbc48acfb9bf92`

### Category

ads

### Description

Pornographic advertisements are displaying in the bottom right of the page. Still shows up after using zapper tool and refreshing.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/73433060/5a9b28d9-3b32-4d1b-9a47-9e7c61038ab0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 104851
 cosmetic: 40314
 scriptlet: 18748
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 36127-127, now
  ublock-badware: 7405-5, now
  ublock-privacy: 650-0, now
  ublock-unbreak: 2180-2, now
  ublock-quick-fixes: 164-25, now
  easylist: 72145-697, now
  easyprivacy: 32883-724, now
  urlhaus-1: 11450-0, 1h.50m
  plowe-0: 3722-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 29 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 374 ms
 maxAssetCacheWait: 131 ms
popupPanel:
 blocked: 9
 network:
  dynssp.com: 2
  googletagmanager.com: 1
  jads.co: 2
  magsrv.com: 2
  tsyndicate.com: 2
 extended:
  ##.banner728x90
```
</details>

**Comment by D4niloMR** [comment]
Add:

`||redd.tube/t763b93e01e9/$media,1p`
