### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by mrticker** [uBlockOrigin/uAssets#20366]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://twitter.com/`

### Description

When you click "delete" on a tweet, a confirmation dialog appears. With ublock origin, it's not visible.

BTW, this is the most difficult bug report I ever made. Congratulations.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 105006
 cosmetic: 40366
 scriptlet: 18894
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 226-17, never
  easylist: 72148-15, 2m
  easyprivacy: 32887-64, 2m
  plowe-0: 3722-1072, 2m
  ublock-badware: 7401-138, 2m
  ublock-filters: 35246-144, 2m
  ublock-privacy: 657-6, 2m
  ublock-quick-fixes: 187-115, 2m
  ublock-unbreak: 2135-33, 2m
  urlhaus-1: 11410-0, 2m
filterset (user): [array of 226 redacted]
trustedset:
 added: [array of 22 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1090 ms (selfie)
 maxAssetCacheWait: 161 ms
popupPanel:
 blocked: 67
 network:
  twitter.com: 65
  doubleclick.net: 1
  google-analytics.com: 1
```

</details>

**Comment by mapx-** [comment]
follow all these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
