### ISSUE TITLE
[nsfw] file-upload.org: ads

### ISSUE THREAD

**Issue by ManPython** [uBlockOrigin/uAssets#20360]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.file-upload.org`

### Category

ads

### Description

The website have hidden layers when clicking on buttons then opening new cards and this same on private window.

### Other extensions used

This same on adblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 106436
 cosmetic: 47880
 scriptlet: 18956
 html: 1095
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36130-169, now
  ublock-badware: 7405-5, now
  ublock-privacy: 649-0, now
  ublock-unbreak: 2180-2, now
  ublock-quick-fixes: 167-25, now
  easylist: 72144-712, now
  easyprivacy: 32879-724, now
  urlhaus-1: 11635-0, now
  plowe-0: 3722-1, now
  POL-0: 8006-27, now
  POL-2: 1279-12, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11492 ms (selfie)
 maxAssetCacheWait: 111 ms
popupPanel:
 blocked: 5
 network:
  baidu.com: 1
  googletagmanager.com: 3
  qiyukf.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
@ManPython Provide A Test URL To Download A File

Or Try In My Filters
```
file-upload.com##.compare-col, footer
file-upload.com##.text-center.page-wrap > div > .row
file-upload.com##.mnbt1.btn-success.btn-xs.btn
file-upload.com##.default-ttl > .pull-right
file-upload.com##.btn-success.btn-sm.btn:style(display: block !important;)
file-upload.com###download-div:style(display: block !important;)
file-upload.com##.pull-right.col-md-12.col-lg-9
file-upload.com##.news-bar
file-upload.com##.breaking-news

**Comment by ManPython** [comment]
They generating next pages to generate button download, before click there is fake button, and then pop-ups, ads, etc. 
There is many sites like this : )

@BlazeFTL not helped in next steps

**Comment by BlazeFTL** [comment]
@stephenhawk8054 `https://file-upload.org/vp2oszrlddj0`
