### ISSUE TITLE
anhdep24.com: detection

### ISSUE THREAD

**Issue by OOFNOOB123** [uBlockOrigin/uAssets#20362]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://asideway.com/`

### Category

detection

### Description

Ads Blocker Detected!!! A window will pop up

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/66705321/db50917e-217f-4e86-9a0b-3d22fcb1af0f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 106104
 cosmetic: 43581
 scriptlet: 19026
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 13-0, never
  KOR-1: 4705-10, 21m
  easylist: 72145-55, now
  easyprivacy: 32883-74, now
  plowe-0: 3722-1087, now
  ublock-badware: 7401-138, now
  ublock-filters: 35235-147, now
  ublock-privacy: 656-8, now
  ublock-quick-fixes: 178-111, 21m
  ublock-unbreak: 2134-34, now
  urlhaus-1: 11450-0, 21m
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 236 ms (selfie)
 maxAssetCacheWait: 137 ms
popupPanel:
 blocked: 11
 network:
  bmcdn6.com: 3
  googlesyndication.com: 2
  googletagmanager.com: 1
  netpub.media: 4
  vipads.live: 1
 extended:
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
  ##+js(nano-setInterval-booster, counter, *)
  ##+js(no-setInterval-if, visibility, 1000)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by D4niloMR** [comment]
You have to share the initial link

**Comment by JobcenterTycoon** [comment]
We need the shortened link.
