### ISSUE TITLE
zive.cz: detection

### ISSUE THREAD

**Issue by Aeyesx** [uBlockOrigin/uAssets#20369]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zive.cz/`

### Category

detection

### Description

The website probably updated to detect UBO.
The uBlock - Annoyances filter no longer circumvents the script from loading.

I purged UBO to defaults, updated but persists. Tried different computer, same result, running on firefox.

### Other extensions used

SponsorBlock
Return YouTube dislike
DarkMode
DuckDuckGo Essentials

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![popup](https://github.com/uBlockOrigin/uAssets/assets/5220885/b1545859-34f2-476d-98ec-5279a92ad9fb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 115
filterset (summary):
 network: 105100
 cosmetic: 41750
 scriptlet: 22474
 html: 1273
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5630-13, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36135-130, now
  ublock-badware: 7405-5, now
  ublock-privacy: 651-0, now
  ublock-unbreak: 2181-2, now
  ublock-quick-fixes: 180-26, now
  easylist: 72148-657, now
  easyprivacy: 32887-766, now
  urlhaus-1: 11410-0, now
  plowe-0: 3722-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 607 ms
 maxAssetCacheWait: 4 ms
popupPanel:
 blocked: 43
 network:
  4dex.io: 1
  a-mo.net: 1
  adform.net: 4
  adnxs.com: 3
  adocean.pl: 1
  adscale.de: 1
  bbelements.com: 1
  creativecdn.com: 1
  criteo.com: 2
  criteo.net: 3
  cxense.com: 1
  doubleclick.net: 1
  facebook.net: 1
  gemius.pl: 1
  gjirafa.tech: 2
  google.com: 2
  googleoptimize.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  onetag-sys.com: 1
  onthe.io: 1
  performax.cz: 2
  pubmatic.com: 2
  rubiconproject.com: 2
  seznam.cz: 2
  smartadserver.com: 3
  trackad.cz: 1
 extended:
  ##.cnc-ads--rectangle_480_1
  ##.cnc-ads
  ###cnc_branding_creative_wrapper
  ##+js(addEventListener-defuser, DOMContentLoaded, event)
```
</details>

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20502

**Comment by okiehsch** [comment]
Caused by a filter in the rgional list, does adding
`zive.cz#@#div.sky-wrapper`
to your filter list work for you?
