### ISSUE TITLE
shinbhu.net: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#20376]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shinbhu.net/bypass.html` => **bad test link**

`https://linksfly.me/GR8ZgDmHYT3`

### Category

detection

### Description

detection

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-10-31-09-13-25-96_4d38fce200f96aeac5e860e739312e76](https://github.com/uBlockOrigin/uAssets/assets/36397582/6f360a5b-8305-4040-b307-a7d91650d62f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium Mobile: 116
filterset (summary):
 network: 110497
 cosmetic: 33041
 scriptlet: 18970
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  IDN-0: 9670-3872, 14m
  adguard-mobile: 8798-45, 13m
  easylist: 72117-16032, 12m
  easyprivacy: 32887-75, 11m
  plowe-0: 3722-1147, 9m
  ublock-badware: 7395-139, 8m
  ublock-filters: 35554-411, 7m
  ublock-privacy: 657-7, 6m
  ublock-quick-fixes: 188-116, 5m
  ublock-unbreak: 2140-37, 4m
  urlhaus-1: 11410-0, 15m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2395 ms (selfie)
 maxAssetCacheWait: 408 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(abort-current-script, document.getElementById, /\$\('body'…
  ##+js(abort-current-script, addEventListener, document.getElemen…
  ##+js(abort-current-script, eval, replace)
  ##+js(abort-current-script, onload, jQuery)
  ##+js(abort-on-property-read, alert)
  ##+js(no-fetch-if, wpadmngr)
  ##+js(no-setTimeout-if, redURL)
  ##+js(no-setInterval-if, console)
  ##+js(abort-current-script, document.createElement, onerror)
  ##+js(set-constant, document.hasFocus, trueFunc)
```
</details>

**Comment by smaragdina** [comment]
https://firefaucet.win/visitx/256/1/

**Comment by mapx-** [comment]
@smaragdina your link redirects to => `https://firefaucet.win/login`

**Comment by BlazeFTL** [comment]
Test URL
`https://linksfly.me/GR8ZgDmHYT3`

**Comment by mapx-** [comment]
test

```
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(acs, document.getElementById, /\$\('body'\)|\$\("body"\)/)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(acs, addEventListener, document.getElementById)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(acs, eval, replace)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(acs, onload, jQuery)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(aopr, alert)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(no-fetch-if, wpadmngr)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(nostif, redURL)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net##^script:has-text(/fetch|AdBlock|demandSupply/)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(nosiif, console)
allcryptoz.net,crewbase.net,phineypet.com,shinbhu.net,talkforfitness.com#@#+js(acs, document.createElement, onerror)
allcryptoz.net,crewbase.net,phineypet.com,shinbhu.net,talkforfitness.com#@#+js(set, document.hasFocus, trueFunc)
```

**Comment by jadreas** [comment]
> test
> 
> ```
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(acs, document.getElementById, /\$\('body'\)|\$\("body"\)/)
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(acs, addEventListener, document.getElementById)
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(acs, eval, replace)
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(acs, onload, jQuery)
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(aopr, alert)
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(no-fetch-if, wpadmngr)
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(nostif, redURL)
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#^script:has-text(/fetch|AdBlock|demandSupply/)
> allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net#@#+js(nosiif, console)
> allcryptoz.net,crewbase.net,phineypet.com,shinbhu.net,talkforfitness.com#@#+js(acs, document.createElement, onerror)
> allcryptoz.net,crewbase.net,phineypet.com,shinbhu.net,talkforfitness.com#@#+js(set, document.hasFocus, trueFunc)
> ```

OOPS! YOU HAVE BEEN BLOCKED
Sorry, but please make sure that you are not using any third-party scripts or ad blockers. If you believe this is a mistake, kindly clear your browser cache before trying again.
https://allcryptoz.net
crewbase
uniqueten

**Comment by mapx-** [comment]
Disable any other extension, use the default lists, clear cookies / local Storage

**Comment by jadreas** [comment]
> Disable any other extension, use the default lists, clear cookies / local Storage

So opera was the problem maybe? Tried opera normal and private window the same.
Tried Firefox Private window with default filters + my ocustom filters and it works now thank you.

**Comment by smaragdina** [comment]
![Screenshot_2023-11-06-13-10-17-27_4d38fce200f96aeac5e860e739312e76](https://github.com/uBlockOrigin/uAssets/assets/36397582/83b0ef99-c965-4d99-b2c4-108ef296a584)

still not work for me bro,, thank you

**Comment by mapx-** [comment]
- use firefox mobile
- if still does not work ask here: https://github.com/uBlockOrigin/uAssets/discussions/17361
