### ISSUE TITLE
Youtube Adblocker notice

### ISSUE THREAD

**Issue by ClusterDucked** [uBlockOrigin/uAssets#20375]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

you tube ad alert. even after trusting the site.

### URL(s) where the issue occurs.

www.youtube.com/watch?v=

### Screenshot(s)

![Screenshot 2023-10-30 160558](https://github.com/uBlockOrigin/uAssets/assets/149433220/d6e6d532-a9cd-4879-b665-f282132d08c1)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105561
 cosmetic: 46609
 scriptlet: 18889
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-newsletters: 6598-8, 1m
 default:
  user-filters: 0-0, never
  easylist: 72207-15, 5d.21h.38m
  easyprivacy: 33046-64, 5d.21h.38m
  plowe-0: 3727-1073, 5d.21h.38m
  ublock-badware: 7401-138, 20h.7m
  ublock-filters: 35246-145, 20h.6m
  ublock-privacy: 613-6, 5d.21h.38m
  ublock-quick-fixes: 187-104, 4h.51m
  ublock-unbreak: 2134-33, 20h.5m
  urlhaus-1: 11635-0, 20h.4m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 356 ms (selfie)
 maxAssetCacheWait: 66 ms
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/19976
