### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by deadman616** [uBlockOrigin/uAssets#20374]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection

### Description

YouTube has implemented measures to prevent users from bypassing their anti-adblocker system.
Can you fix this problem?

### Other extensions used

No.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 104864
 cosmetic: 40325
 scriptlet: 18752
 html: 1084
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36132-232, now
  ublock-badware: 7410-5, now
  ublock-privacy: 651-0, now
  ublock-unbreak: 2181-2, now
  ublock-quick-fixes: 180-26, now
  easylist: 72188-553, now
  easyprivacy: 32887-766, now
  urlhaus-1: 11410-0, 7m
  plowe-0: 3722-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1779 ms (selfie)
 maxAssetCacheWait: 1378 ms
popupPanel:
 blocked: 5
 network:
  youtube.com: 1
  doubleclick.net: 2
  google.com: 1
  google.com.lb: 1
 extended:
  ###merch-shelf
  ###player-ads
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(set-constant, yt.config_.EXPERIMENT_FLAGS.service_worker_e…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
read and folow the indications here: https://github.com/uBlockOrigin/uAssets/issues/19976
