### ISSUE TITLE
app.axenthost.com: detection

### ISSUE THREAD

**Issue by ScorelessPine** [uBlockOrigin/uAssets#20379]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.axenthost.com/`

### Category

detection

### Description

The Axenthost website seems to load the normal page for a very brief period (<0.25s) before showing the "You are using an Ad Blocker" page, shown in the screenshot below.

### Other extensions used

None. Tested using Chrome's Incognito mode, which loads the site using *only* uBO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Adblocker Detected page
![image](https://github.com/uBlockOrigin/uAssets/assets/28274052/ba9311fd-6385-4ceb-a657-85d98255d583)
Single frame of normal page before Adblocker Detected page shows up
![image](https://github.com/uBlockOrigin/uAssets/assets/28274052/97a80069-a090-48a2-9741-457faec15bc3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104887
 cosmetic: 40318
 scriptlet: 18894
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72195-15, now
  easyprivacy: 32891-64, now
  plowe-0: 3722-1072, now
  ublock-badware: 7406-138, now
  ublock-filters: 35230-144, now
  ublock-privacy: 657-6, now
  ublock-quick-fixes: 188-114, 5m
  ublock-unbreak: 2135-33, now
  urlhaus-1: 11410-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2474 ms (selfie)
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 70
 network:
  axenthost.com: 2
  3lift.com: 5
  adnxs.com: 5
  amazon-adsystem.com: 1
  btloader.com: 1
  clarity.ms: 2
  cloudflareinsights.com: 1
  colossusssp.com: 5
  criteo.com: 10
  doubleclick.net: 1
  google-analytics.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  media.net: 5
  nitropay.com: 12
  rubiconproject.com: 5
  sharethrough.com: 5
  stripe.com: 1
  unrulymedia.com: 5
```
</details>

**Comment by mapx-** [comment]
@ScorelessPine test the filter for breakage

**Comment by ScorelessPine** [comment]
Purging caches and updating the filter list does not seem to change anything, however adding that line from the commit to My Filters does seem to work. Is that what you were asking for?

**Comment by mapx-** [comment]
yes, for updating the lists you should wait 5-10 minutes

**Comment by ScorelessPine** [comment]
Works well for me now then, thanks.

**Comment by LucavaL** [comment]
Sorry for bringing this up again, but it seems that the issue is back.

**Comment by ToIgnore** [comment]
```
@@*$ghide,domain=axenthost.com
@@||nitropay.com^$script,domain=axenthost.com
```

**Comment by mapx-** [comment]
@D4niloMR 

can you test only 

`axenthost.com##+js(set, nitroAds.loaded, true)`

**Comment by ToIgnore** [comment]
@mapx- oops, you're right it's not needed. it looked like they were using dom elements as bait in the code.

**Comment by D4niloMR** [comment]
It works with only that filter.

**Comment by LucavaL** [comment]
> It works with only that filter.

I tried that filter and it is not working for me...

**Comment by ToIgnore** [comment]
@LucavaL 
![image](https://github.com/uBlockOrigin/uAssets/assets/166810747/2ae3356c-edcb-40f9-8bc8-cd7d7ebdcf98)

**Comment by LucavaL** [comment]
> @LucavaL ![image](https://private-user-images.githubusercontent.com/166810747/323352788-2ae3356c-edcb-40f9-8bc8-cd7d7ebdcf98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODIyNTYsIm5iZiI6MTcxMzM4MTk1NiwicGF0aCI6Ii8xNjY4MTA3NDcvMzIzMzUyNzg4LTJhZTMzNTZjLWVkY2ItNDBmOS04YmM4LWNkN2Q3ZWJkY2Y5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxOTI1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzFiYzc2YjNiNmEwN2U3ZWE5NDQ4Nzg5MTQxYjY4NjM1ZWYwNzI3Y2YzYTRiMzc5YWEzMTJmNjE1OWMzMDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UJ_Iz2ZXSdJS04C2QD-OKAByFJgAW4SlfSz4EkP-h6E)

Yes, that's what i did. Still getting detected, I even checked if my own rules were overwriting this one.

**Comment by ToIgnore** [comment]
Make sure it isn't caused by PiHole / AdGuard DNS, other extensions

**Comment by LucavaL** [comment]
> Make sure it isn't caused by PiHole / AdGuard DNS, other extensions, any built-in ad blocker / tracking protection.

Upon further testing, i found out it was the AdGuard - Ads filter. Looks like i have to keep it disabled :(
Thank you.

**Comment by ToIgnore** [comment]
@Alex-302

**Comment by LucavaL** [comment]
@ToIgnore the issue still occurs when activating AdGuard - Ads filters.

**Comment by Alex-302** [comment]
@LucavaL Please test `app.axenthost.com#@#+js(prevent-fetch, stripe.com)`

**Comment by LucavaL** [comment]
> @LucavaL Please test `app.axenthost.com#@#+js(prevent-fetch, stripe.com)`

Properly working

**Comment by Alex-302** [comment]
Disabled that scriptlet for uBO in our filter.

**Comment by LucavaL** [comment]
Issue is back. This time the block appears immediately, unlike before, so it seems that they are keep updating the script.

**Comment by LucavaL** [comment]
Issue back again.
Apparently they keep updating the script, since now the detect screen appears immediately, without even loading the page.
This time they worked around the uBlock Filters.

**Comment by Alex-302** [comment]
> they worked around uBlock

any adblocker
