### ISSUE TITLE
soccersuck.com: ads

### ISSUE THREAD

**Issue by Reportos** [uBlockOrigin/uAssets#20388]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://www.soccersuck.com/`

### Category

ads

### Description

The ads on soccersuck.com, a football news website from Thailand, still showing. I try to block them by putting the ads elements on my filters but it still keeps showing. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![ReportSS01](https://github.com/uBlockOrigin/uAssets/assets/149520082/1ba18ff4-c74e-474e-87d1-a7e0bc2ae07d)
![ReportSS02](https://github.com/uBlockOrigin/uAssets/assets/149520082/6ae1e530-68ff-480f-9e88-94182d010808)
![ReportSS03](https://github.com/uBlockOrigin/uAssets/assets/149520082/e7bc0e16-9714-4703-be06-668ed218ec5a)

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 104880
 cosmetic: 40317
 scriptlet: 18759
 html: 1082
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 36123-229, now
  ublock-badware: 7411-5, now
  ublock-privacy: 653-0, now
  ublock-unbreak: 2180-1, now
  ublock-quick-fixes: 177-28, now
  easylist: 72196-595, now
  easyprivacy: 32891-724, now
  urlhaus-1: 11420-0, now
  plowe-0: 3721-1, now
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 323 ms
 maxAssetCacheWait: 93 ms
popupPanel:
 blocked: 14
 network:
  anymind360.com: 2
  fout.jp: 2
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 3
  googletagservices.com: 2
  smartlook.com: 1
  tiktok.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
- use the regional list `EasyList Thailand`
- whatever ads for thai sites => report here: https://github.com/easylist-thailand/easylist-thailand/issues

@gluons
