### ISSUE TITLE
climateknowledgeportal.worldbank.org: breakage

### ISSUE THREAD

**Issue by reddraegon** [uBlockOrigin/uAssets#20382]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://climateknowledgeportal.worldbank.org/country/poland`

### Category

breakage

### Description

no information shows up about any country if uBlockOrigin is enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 106560
 cosmetic: 49311
 scriptlet: 22686
 html: 1283
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5638-15, now
  POL-0: 8006-27, now
  POL-2: 1279-12, now
 default:
  user-filters: 3-0, never
  ublock-filters: 36123-167, now
  ublock-badware: 7411-5, now
  ublock-privacy: 651-0, now
  ublock-unbreak: 2180-2, now
  ublock-quick-fixes: 178-26, 39m
  easylist: 72196-714, now
  easyprivacy: 32891-724, now
  urlhaus-1: 11410-0, now
  plowe-0: 3722-1, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 189 ms (selfie)
 maxAssetCacheWait: 88 ms
popupPanel:
 blocked: 4
 network:
  worldbank.org: 2
  adobedtm.com: 1
  appdynamics.com: 1
```
</details>

**Comment by JobcenterTycoon** [comment]
Its caused by `/geomap.js` in EasyPrivacy
