### ISSUE TITLE
Youtube video's: no video, just audio with uBlock Origin enabled

### ISSUE THREAD

**Issue by burne101** [uBlockOrigin/uAssets#2038]
### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=zFZMqZEYES4` and any other direct or embedded youtube video.

### Describe the issue

YouTube video's show a black screen with no video. Thumbnails and the preview screen work. This started this morning, 20/04/2018, (morning in the european timezone..)

### Screenshot(s)

screenshot at https://i.imgur.com/q2Qcijk.png

### Versions

- Browser/version: [Safari Version 11.1 (13605.1.33.1.2)]
- uBlock Origin version: [uBlock Origin v1.11.3.1]

### Settings

unmodified default default install 

### Notes

I have no clue how to investigate the cause :(

**Comment by mapx-** [comment]
report here (for safari):
https://github.com/el1t/uBlock-Safari/issues
