### ISSUE TITLE
vrising.fandom.com: nuisance: "element zapper" works (temp) and "element picker" does not.

### ISSUE THREAD

**Issue by Mindus-Amitiel-Debsin** [uBlockOrigin/uAssets#20380]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vrising.fandom.com/wiki/V_Rising`

### Category

nuisance

### Description

Hello!

I am trying to remove the two icon/links "Sign In" and "Register" from the page, as it almost covers up the search button after a tampermonkey restyle + adblocker is enabled for that site.

**While the issue becomes most pressing when the TM script is running, the issue also exists when it is not running.**

To put it simply, trying to remove the buttons with the uBO Element Zapper works, temporarily, but not with the permanent Element Picker.  Using the Element Picker instead removes the background of the page. 

Is it possible to add additional functionality to the element picker to work like the element zapper? Or, to make the Element Zapper changes a rule that I can configure for the entire subdomain site?

Thanks for reading!!

### Other extensions used

Bitwarden
FediAct
GNOME Shell Extension
Google Docs Offline
Keybase
PayPal Honey
Privacy Badger
Redirect to Wiki.gg
SponsorBlock for YouTube - Skip Sponsorships
Tampermonkey
Terms of Service; Didn’t Read
![Screenshot from 2023-10-31 01-31-42](https://github.com/uBlockOrigin/uAssets/assets/8101416/7403cd90-54df-4686-9871-0802c3ccae09)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2023-10-31 00-49-50](https://github.com/uBlockOrigin/uAssets/assets/8101416/a47e18d9-00ae-4931-800f-5ef7954701a6)
![Screenshot from 2023-10-31 00-50-16](https://github.com/uBlockOrigin/uAssets/assets/8101416/d4fee0d6-cbc3-4a40-b8e0-80f1be9b4a4b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104885
 cosmetic: 40336
 scriptlet: 18901
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72195-15, 1m
  easyprivacy: 32891-64, 1m
  plowe-0: 3722-1072, 1m
  ublock-badware: 7406-138, 1m
  ublock-filters: 35243-144, 1m
  ublock-privacy: 657-6, 1m
  ublock-quick-fixes: 185-101, 1m
  ublock-unbreak: 2135-33, 1m
  urlhaus-1: 11410-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 205 ms
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 36
 network:
  ad.gt: 1
  amazon-adsystem.com: 1
  amplitude.com: 1
  btloader.com: 1
  doubleclick.net: 3
  durationmedia.net: 1
  fastly-insights.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  nocookie.net: 1
  ntv.io: 1
  optimizely.com: 1
  quantserve.com: 1
  scorecardresearch.com: 1
  wikia-services.com: 19
 extended:
  ##.top-ads-container
  ##.ad-slot-placeholder
  ##.gpt-ad
  ##.hidead
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.bottom-ads-container
  ###featured-video__player-container
  ##+js(set-constant, wgAffiliateEnabled, false)
  ##+js(set-cookie, tracking_session_id, OK, , reload, 1)
  ##+js(set-cookie, Geo, OK)
  ##+js(set-constant, optimizely, {})
  ##+js(set-constant, optimizely.initialized, true)
```
</details>

**Comment by mapx-** [comment]
use the second proposed filter in the cosmetic filters section (of element picker)

`vrising.fandom.com##.global-registration-buttons`

**Comment by krystian3w** [comment]
@iam-py-test maybe Worth for Nordic Annoyances aka "🚪 Browse websites without logging in".

**Comment by iam-py-test** [comment]
I'm sorry, but I don't think this should be added to browse websites without logging in as the login/register buttons are critical functionality, and this only is a problem if
> after a tampermonkey restyle

(also, I am unsure if I am even authorized to add entries to that list)
Thank you

**Comment by Mindus-Amitiel-Debsin** [comment]
Thank you all for teaching I more about element picker. Please don't
misunderstand what I wrote. I consider the matter be closed. Thanks again.
