### ISSUE TITLE
ruiukp.top: badware

### ISSUE THREAD

**Issue by GeorgeGR21** [uBlockOrigin/uAssets#20389]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`http://ruiukp.top/`

### Description

This link is phishing. It's being sent to Greek users by fake numbers and it's pretending to be an official message from ELTA.

**ELTA is aware of this** and has added a large notice on their website, as you can see in the screenshot below:

![Screenshot from 2023-10-31 19-50-14](https://github.com/uBlockOrigin/uAssets/assets/123986260/7dec16e8-2f98-4640-8341-b12c846713e5)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screenshotphishing](https://github.com/uBlockOrigin/uAssets/assets/123986260/b6167176-9fd0-4ad6-9bc5-dacbb799c242)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/2a5905baf08726c6d2903b54c107aa8787605371
