### ISSUE TITLE
adclicker.io: detection

### ISSUE THREAD

**Issue by vanTheodore** [uBlockOrigin/uAssets#20390]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://adclicker.io/url/#V1ZoQ2NGQlVXVEJaVkdNeFdYcE5NMDlFVW0xUFZFVjRUVzFPYkUxRVZtdE9ha0V6V1hsYU1XTnRkemxqUjBaNldtMDVORXh0VG5aS1ZFcEhXa2RXYWxsWVNtNVpXRWw0VFVNMWQyRklRVzFhYWpFMFRucG9VRkZZVVQwPQ`==

### Description

It detects uBlock.

### Other extensions used

SponsorBlock (shouldn't affect).

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 107389
 cosmetic: 46593
 scriptlet: 19296
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 72197-15, 43m
  easyprivacy: 32891-64, 43m
  plowe-0: 3721-1072, 43m
  spa-0: 3767-19, 43m
  spa-1: 5675-225, 43m
  ublock-badware: 7407-138, 43m
  ublock-filters: 35232-173, 43m
  ublock-privacy: 659-6, 42m
  ublock-quick-fixes: 185-114, 42m
  ublock-unbreak: 2134-34, 42m
  urlhaus-1: 11420-0, 42m
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9516 ms (selfie)
 maxAssetCacheWait: 1809 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(set-constant, global.noobMaxTry, 0)

```
</details>

**Comment by mapx-** [comment]
maybe 

`@@||xd-digital.com^$ghide`

what's the final destination ?!

**Comment by vanTheodore** [comment]
This one in particular reaches here:
`https://adclicker.io/url/go/pasfox.co/decargar10.php/` (broken link for now)

**Comment by BlazeFTL** [comment]
There Are Multiple Domains
```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=cantineoqueteveo.barcelona
@@||cantineoqueteveo.barcelona^$ghide

For This Site Adguard Has A ByPass Filter Maybe Similar Site To `https://desbloquea.me/`
https://github.com/AdguardTeam/AdguardFilters/commit/ebe0ccb96ec4d4a31b13b7889e7cc6b67a8ea0fa
https://github.com/AdguardTeam/AdguardFilters/commit/9d7ee726e70a03413dd1fa6517188c80dd8e2c16

**Comment by mapx-** [comment]
well, very random shorteners => to be discussed here: https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by BlazeFTL** [comment]
@vanTheodore If You Want ByPass Then Try Adguard With Spanish Filter Enabled
