### ISSUE TITLE
pocketfm.com: breakage

### ISSUE THREAD

**Issue by jorge-barroso** [uBlockOrigin/uAssets#20392]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pocketfm.com/us`

### Category

breakage

### Description

The page seems to load fine for a tenth of a second and then something fails and it displays the error attached in the images section.

Also attached is the output from the console, although minimal, but I think the "Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource." must be somewhat related.

### Other extensions used

I'm using nordvpn, nordpass, dark reader progressive web apps for firefox and privacy badger, but I have also tried disabling all of them and what makes the difference is disabling/enabling uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/8150057/70ca1a15-69b2-4192-a92d-cddb25502846)
![image](https://github.com/uBlockOrigin/uAssets/assets/8150057/26328dc3-2a1f-4ae8-81ce-baccf13a552c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 104874
 cosmetic: 40318
 scriptlet: 18756
 html: 1082
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36121-127, 53m
  ublock-badware: 7405-5, 53m
  ublock-privacy: 653-0, 53m
  ublock-unbreak: 2181-1, 53m
  ublock-quick-fixes: 177-28, 53m
  easylist: 72196-697, 53m
  easyprivacy: 32891-724, 53m
  urlhaus-1: 11420-0, 53m
  plowe-0: 3721-1, 53m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 400 ms
 maxAssetCacheWait: 126 ms
popupPanel:
 blocked: 6
 network:
  cloudflare.com: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
```
</details>

**Comment by mapx-** [comment]
for `us` you have to have a US ip (if does not work => clear cookies / local storage)
