### ISSUE TITLE
Anime news network anti blocker

### ISSUE THREAD

**Issue by stealthswor** [uBlockOrigin/uAssets#20391]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.animenewsnetwork.com`

### Description

Implemented a new anti ad-blocker. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![2023-10-31 15 05 21 www animenewsnetwork com 9ba376fd8546](https://github.com/uBlockOrigin/uAssets/assets/121595922/47cbcd1c-718e-4042-8f6a-f5517ef4b90a)

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105076
 cosmetic: 40353
 scriptlet: 18898
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gist.githubusercontent.com/Rust1667/df78d493cf3c00340c535d93e303c4f9/raw: 192-2, never
 default:
  user-filters: 61-1, never
  easylist: 72197-16, 7m
  easyprivacy: 32891-64, 7m
  plowe-0: 3721-1072, 7m
  ublock-badware: 7396-161, 7m
  ublock-filters: 35232-144, 7m
  ublock-privacy: 659-6, 7m
  ublock-quick-fixes: 185-114, 7m
  ublock-unbreak: 2134-32, 7m
  urlhaus-1: 11420-0, 7m
filterset (user): [array of 61 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1080 ms (selfie)
 maxAssetCacheWait: 352 ms
popupPanel:
 blocked: 7
 network:
  animenewsnetwork.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 2
  intergient.com: 2
  kiosked.com: 1
 extended:
  ###Adbanner
  ##div.box:nth-of-type(2)
  ##.gutter
  ##.iab
  ##[href^="/advertorial/"]:upward(2)

```
</details>

**Comment by mapx-** [comment]
enable [uBlock filters – Annoyances](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=ublock-annoyances)
