### ISSUE TITLE
Vipboxtv.sk: breakage

### ISSUE THREAD

**Issue by Web-Entertainment** [uBlockOrigin/uAssets#20399]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.vipboxtv.sk/tennis/1/stream-atp-paris-novak-djokovic-vs-tomas-martin-etcheverry-live`

### Category

breakage

### Description

Hi,
Noticed today, the Player on the Vipbox.sk site doesn't load
Looking into it, disabling the Default **UBlock - Ads** filter shows the Player again.

I'seen 22 entries related to vipbox.* in that list.
Don't know which of them breaks the Player.

Thanks in advandc.

### Other extensions used

Any unrelated since disabling that default list, the Player appears and works again.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/103955779/2ae4f74f-a2a8-4614-9043-82f5c5c533f7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104872
 cosmetic: 40313
 scriptlet: 18829
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72244-15, now
  easyprivacy: 32891-64, now
  plowe-0: 3722-1072, now
  ublock-badware: 7407-138, now
  ublock-filters: 35144-145, now
  ublock-privacy: 668-6, now
  ublock-quick-fixes: 213-128, now
  ublock-unbreak: 2134-32, now
  urlhaus-1: 11340-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1849 ms
 maxAssetCacheWait: 33 ms
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 1
  niaomea.me: 1
  tabbingtremors.life: 1
  xuffojr.com: 1
 extended:
  ##.position-absolute
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(no-window-open-if, //)
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-current-script, navigator, FingerprintJS)
```
</details>

**Comment by mapx-** [comment]
add

`*$script,3p,denyallow=nolive.me|plyjam.me|chatango.com,from=vipboxtv.*,badfilter`
