### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Heughy** [uBlockOrigin/uAssets#20397]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [ ] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=XwUtZMfl0pk`

### Category

detection

### Description

uBLOCK Origin was working the day before, tried updating.. still getting the 'remove adblock' notification on youtube.

### Other extensions used

nothing related to adblockers

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/149596471/26af3002-eb8a-4871-bbe6-d3386d3b1d7d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 104822
 cosmetic: 40308
 scriptlet: 18812
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72237-15, now
  easyprivacy: 32852-64, now
  plowe-0: 3722-1072, now
  ublock-badware: 7407-138, now
  ublock-filters: 35126-145, now
  ublock-privacy: 659-6, now
  ublock-quick-fixes: 190-105, now
  ublock-unbreak: 2134-32, now
  urlhaus-1: 11340-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 356 ms (selfie)
 maxAssetCacheWait: 76 ms
popupPanel:
 blocked: 67
 network:
  youtube.com: 38
  doubleclick.net: 4
  google.com: 25
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?\/(aclk\?…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(trusted-replace-fetch-response, /(trackingParam":"kx_fmPx…
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/19976
