### ISSUE TITLE
ets2.gr: badware

### ISSUE THREAD

**Issue by GeorgeGR21** [uBlockOrigin/uAssets#20400]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://ets2.gr/`

### Description

According to VirusTotal[[1]](https://www.virustotal.com/gui/url/ef7a8a552ce7b0292565926d040f8b34674e2b7d21e43415b5734df2a4f3380f/detection) and ThreatFox[[2]](https://threatfox.abuse.ch/ioc/1152076/), this website is confirmed as malicious, serves as a malware payload delivery host and the domain is used by GOOTLOADER. It is actively being blocked by custom filters like OISD.nl, but not by uBlock's default filters.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by gorhill** [comment]
I don't see the site listed in ThreatFox's hosts file, suggesting it's no longer an issue? It says "Last seen: 2023-08-25".

**Comment by GeorgeGR21** [comment]
I'm not a professional analyst, but according to this second opinion scanner[[Link]](https://sitecheck.sucuri.net/results/https/ets2.gr), there are still some malicious JavaScripts.
