### ISSUE TITLE
nnmclub.to: popups

### ISSUE THREAD

**Issue by sugatasanshiro** [uBlockOrigin/uAssets#20406]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nnmclub.to/`

### Category

popups

### Description

unwanted popups

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 104844
 cosmetic: 40313
 scriptlet: 18831
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72249-15, now
  easyprivacy: 32853-64, now
  plowe-0: 3721-1072, now
  ublock-badware: 7412-138, now
  ublock-filters: 35146-145, now
  ublock-privacy: 668-6, now
  ublock-quick-fixes: 213-128, 1h.15m
  ublock-unbreak: 2135-33, now
  urlhaus-1: 11340-0, now
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 132 ms (selfie)
 maxAssetCacheWait: 66 ms
popupPanel:
 blocked: 11
 network:
  frfetchme.com: 2
  google-analytics.com: 2
  googlesyndication.com: 1
  iqbroker.com: 3
  storader.com: 1
  yadro.ru: 1
  yandex.ru: 1
 extended:
  ###adss
```
</details>

**Comment by gorhill** [comment]
Enable RUAdList in "Filter lists" pane in the dashboard.
