### ISSUE TITLE
dailymail.co.uk: detection

### ISSUE THREAD

**Issue by Boristhemoggy** [uBlockOrigin/uAssets#20403]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dailymail.co.uk/tvshowbiz/article-12695249/Why-Margot-Robbie-getting-slammed-Halloween-costume-breaks-one-important-rule-Shes-treading-line.html`

### Category

detection

### Description

Warning on the age that I am using an ad blocker

### Other extensions used

Edit this cookie, FBP

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 104835
 cosmetic: 40313
 scriptlet: 18831
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72245-15, now
  easyprivacy: 32853-64, now
  plowe-0: 3721-1072, now
  ublock-badware: 7412-138, now
  ublock-filters: 35146-145, now
  ublock-privacy: 668-6, now
  ublock-quick-fixes: 213-128, now
  ublock-unbreak: 2135-33, now
  urlhaus-1: 11340-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 299 ms (selfie)
 maxAssetCacheWait: 142 ms
popupPanel:
 blocked: 28
 network:
  dailymail.co.uk: 6
  adsafeprotected.com: 1
  and.co.uk: 1
  cdnopw.com: 1
  dmgmediaprivacy.co.uk: 5
  dotmetrics.net: 1
  doubleclick.net: 1
  go-mpulse.net: 2
  google.com: 6
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  newzit.com: 1
 extended:
  ##.banner-adverts
  ###taboola-below-article-thumbnails
  ##.googleAds
  ###mpu_top
  ##.puff-ad
  ##.puff-advertorials
  ##.overlay-ads
  ###sky-left
  ###sky-right
  ##.video-ads-container
  ###promo-unit
  ##.mpu_puff_wrapper
  ##.watermark
  ##.mol-ads-label-container
  ##AD-SLOT
  ##.pufftext > .sponsored:upward(3)
  ##+js(abort-on-property-read, Notification)
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce. If you what you are seeing is a yellow ribbon warning at the bottom, it's because something else is interfering negatively with uBO ([example](https://twitter.com/gorhill/status/1652314532822351874), that warning is not there with uBO with default settings and no other extension.

**Comment by mapx-** [comment]
@Boristhemoggy follow all these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Boristhemoggy** [comment]
So essentially, completely open my entire computer with no safety whatsoever so that adblock can work?
No thanks!
I have used the dailymail for many years and have never ever had a problem so clearly adblock is causing the problem. 
If in order to use adbloc I have to disable every piece of security on my machine, then Adblock isn't fit for purpose. 
Sorry, I'll just delete adblock.

**Comment by gorhill** [comment]
> then Adblock isn't fit for purpose

Here is for uBlock Origin, not Adblock.

> Sorry, I'll just delete adblock

No need to be sorry, we don't mind people removing their extension(s), it's none of our business.

**Comment by mapx-** [comment]
@Boristhemoggy the steps above are mainly to help you identify the "bad guy"
