### ISSUE TITLE
forum.ixbt.com - page scrolls to top after watching uploaded image

### ISSUE THREAD

**Issue by lansman** [uBlockOrigin/uAssets#20405]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://forum.ixbt.com/topic.cgi?id=8:26203:3028#3028

### Description

Go to any forum topic.
Find a post with uploaded image, [for example ](https://forum.ixbt.com/topic.cgi?id=8:26203:3028#3028)
Click the image to expand.
After this your web-page scrolls to the top, this is annoying, cause you have to scroll down again to find the post you read. 

If you disable ublock on the web site - issue doesn't occur.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 132450
 cosmetic: 211931
 scriptlet: 30969
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27950-44, 3d.15h.46m
  adguard-mobile-app-banners: 4702-10, 3d.15h.44m
  adguard-other-annoyances: 13696-43, 3d.15h.45m
  adguard-popup-overlays: 25140-415, 3d.13h.41m
  adguard-social: 21938-930, 3d.15h.43m
  adguard-widgets: 2332-15, 3d.15h.47m
  easylist-annoyances: 4150-212, 12h.48m
  easylist-chat: 143-11, 4d.10h.52m
  easylist-newsletters: 6600-428, 14h.54m
  easylist-notifications: 2962-1651, 14h.53m
  fanboy-cookiemonster: 63830-19014, 6d.8h.35m
  fanboy-social: 16303-728, 4d.12h.55m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  RUS-0: 40105-9, 14h.49m
  easylist: 72260-101, 4d.10h.51m
  easyprivacy: 32873-254, 2d.8h.8m
  plowe-0: 3727-1078, 7d.11h.46m
  ublock-badware: 7402-138, 15m
  ublock-filters: 35336-545, 4d.23h.29m
  ublock-privacy: 659-9, 6h.19m
  ublock-quick-fixes: 185-106, 4h.16m
  ublock-unbreak: 2134-36, 6h.18m
  urlhaus-1: 11340-0, 6h.17m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 226 ms (selfie)
 maxAssetCacheWait: 144 ms

```
</details>

**Comment by gorhill** [comment]
> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

It's caused by "AdGuard – Cookie Notices", please report to <https://github.com/AdguardTeam/FiltersCompiler>.
