### ISSUE TITLE
client.pylexnodes.net: detection

### ISSUE THREAD

**Issue by huggywuggybest03** [uBlockOrigin/uAssets#20418]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://client.pylexnodes.net/dashboard`

### Category

detection

### Description

Basicially, when you first load up, you have to say "I disabled my adblocker, now let me in" when you load into the website.

What happens is the anti-adblocker script detects the adblockers until you press the button that says you have disabled the adblocker.

### Other extensions used

AdAway - Free ad blocker,
AdsKiller Adblocker,
TubeBlock - Adblock for Youtube.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104697
 cosmetic: 40312
 scriptlet: 18809
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 72271-15, now
  easyprivacy: 32852-64, now
  plowe-0: 3721-1072, now
  ublock-badware: 7421-138, now
  ublock-filters: 35125-145, now
  ublock-privacy: 640-6, now
  ublock-quick-fixes: 227-133, now
  ublock-unbreak: 2133-32, now
  urlhaus-1: 11180-0, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 14621 ms (selfie)
 maxAssetCacheWait: 1035 ms
popupPanel:
 blocked: 1
 network:
  bannertrack.net: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by stevebot398** [comment]
Jok

**Comment by stevebot398** [comment]
Ok merci
