### ISSUE TITLE
vi.nl: breakage

### ISSUE THREAD

**Issue by Nomes77** [uBlockOrigin/uAssets#20410]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.vi.nl/nieuws/druk-op-ten-hag-groeit-na-volgende-vernedering-op-old-trafford`

### Category

breakage

### Description

`Peter Lowe’s Ad and tracking server list` blocks `||quantcast.com^`.
However this rule blocks the cookie popups and the loading of 3rd-party embeds.

Adding `||quantcast.com^$badfilter` works, but not `||quantcast.com^$badfilter,domain=vi.nl`.
Adding this also works `@@||cmp.quantcast.com` works, but seems to general.
And adding the following, makes no sense, since there are no other `quantcast.com` request made:
```
@@||cmp.quantcast.com/choice/K*/www.vi.nl/choice.js$script,domain=vi.nl
@@||cmp.quantcast.com/*/cmp2$script,domain=vi.nl
@@||cmp.quantcast.com^$xhr,domain=vi.nl
```

### Other extensions used

- LocalCDN
- Bypass Paywalls Clean

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Don't mind the loaction warning. It is because the videos play only in the Netherlands.
![afbeelding](https://github.com/uBlockOrigin/uAssets/assets/80090789/d96c48b2-76bc-43ae-a562-83fb90a3a093)
vs
![afbeelding](https://github.com/uBlockOrigin/uAssets/assets/80090789/7bef2587-c782-4c47-8e8c-ec02a578ced6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 87548
 cosmetic: 41635
 scriptlet: 18746
 html: 1074
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  ublock-badware: null
  urlhaus-1: null
 default:
  ublock-filters: 36037-138, 1m
  ublock-privacy: 667-0, 1m
  ublock-unbreak: 2181-0, 1m
  ublock-quick-fixes: 210-41, 8m
  easylist: 72268-567, 1m
  easyprivacy: 32851-725, 1m
  plowe-0: 3721-1, 1m
  NLD-0: 2697-10, 1m
filterset (user): [array of 520 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  opera-scheme
  vivaldi-scheme
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 prefetchingDisabled: false
hiddenSettings:
 autoCommentFilterTemplate: {{date}} {{url}}
 autoUpdateAssetFetchPeriod: 10
 autoUpdateDelayAfterLaunch: 60
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupFontSize: 12px
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 447 ms (selfie)
 maxAssetCacheWait: 197 ms
popupPanel:
 blocked: 13
 network:
  adnami.io: 1
  botndm.nl: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  jwpcdn.com: 2
  nextday.media: 2
  quantcast.com: 1
  survicate.com: 1
  viafoura.co: 2
 extended:
  ##.c-ad
```
</details>

**Comment by stephenhawk8054** [comment]
Hmm... Is `quantcast.com` added to PL recently? Blocking the whole domain can cause many breakages related to cookie banners

**Comment by Nomes77** [comment]
I don't know.
I was testing our filterlist for breakages and ads, and this problem occured.

**Comment by stephenhawk8054** [comment]
@mapx- @Yuki2718 @okiehsch EP does not block the domain either. It just blocks some paths of it. I think it should be `badfilter`?

**Comment by mapx-** [comment]
maybe EP had a similar filter then removed for too many breakages ?!
5 min ago I added
https://github.com/uBlockOrigin/uAssets/commit/ef601406ed87e5ee2472469c4ef1395f4ec6abd0

for the same `quantcast`

**Comment by stephenhawk8054** [comment]
> maybe EP had a similar filter then removed for too many breakages ?!

Actually I remember vaguely it's due to that but don't remember when

**Comment by stephenhawk8054** [comment]
Ok, I'll badfilter it
