### ISSUE TITLE
bokugents.com: detection

### ISSUE THREAD

**Issue by GlenGs** [uBlockOrigin/uAssets#20417]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bokugents.com/`

### Category

detection

### Description

the page detects the adblock

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/144768077/23953661-461c-4252-8cae-8f7e1a7d498d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 107214
 cosmetic: 46604
 scriptlet: 19232
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72285-15, 17m
  easyprivacy: 32851-64, 17m
  plowe-0: 3721-1072, 17m
  spa-0: 3767-19, 17m
  spa-1: 5690-225, 17m
  ublock-badware: 7412-138, 17m
  ublock-filters: 35155-174, 17m
  ublock-privacy: 668-6, 17m
  ublock-quick-fixes: 212-128, 17m
  ublock-unbreak: 2135-34, 17m
  urlhaus-1: 11180-0, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1288 ms
 maxAssetCacheWait: 9 ms
popupPanel:
 blocked: 14
 network:
  disqus.com: 5
  googlesyndication.com: 3
  googletagmanager.com: 1
  narrative.io: 1
  pippio.com: 1
  rezync.com: 1
  viglink.com: 2
 extended:
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  ##+js(remove-node-text, script, onerror)
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by BlazeFTL** [comment]
CHP
Try `bokugents.com##+js(noeval-if, ads)`
