### ISSUE TITLE
health.aetna.com: nuisance

### ISSUE THREAD

**Issue by crigler** [uBlockOrigin/uAssets#20415]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://health.aetna.com/preferences/privacy-security`
`https://www.aetna.com/AccountManagerAppConfig/commonV3/includes/js/changePassword.js?v=1698937304681`

### Description

`https://www.aetna.com/AccountManagerAppConfig/commonV3/includes/js/changePassword.js?v=1698937304681` includees the following code snippet:

```
$(document).ready(function(){
...
    $('#password, #newPassword, #confirmPassword').on("cut copy paste",function(e) {		
		e.preventDefault();
    });
	
 /*Disable cut copy paste in Android*/
   $('#password, #newPassword, #confirmPassword').bind("input", function(e) {
		var previousValue = $(this).data('old_value') || '',
            newValue = $(this).val();

		if((newValue.length - previousValue.length) > 1) {
			$(this).val(previousValue);
		}

		$(this).data('old_value', $(this).val());
	});	
...
```

which prevents someone from securely pasting in a new password from a password manager, which is hilarious since they ask people to protect their account using a strong password. An account is required, though I tested that `changePassword.js` is directly viewable in a private window.

### Other extensions used

Firefox Multi-Account Containers
Open external links in a container

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/8346145/38d28ba6-6e94-40e5-9327-240b88940f69)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 104685
 cosmetic: 40315
 scriptlet: 18693
 html: 1077
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36029-136, 14h.3m
  ublock-badware: 7416-5, 14h.3m
  ublock-privacy: 667-0, 14h.3m
  ublock-unbreak: 2181-0, 14h.3m
  ublock-quick-fixes: 210-41, 1h.42m
  easylist: 72268-698, 14h.2m
  easyprivacy: 32853-724, 14h.2m
  urlhaus-1: 11180-0, 14h.2m
  plowe-0: 3721-1, 14h.2m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 133 ms (selfie)
 maxAssetCacheWait: 47 ms
```
</details>

**Comment by mapx-** [comment]
try

`aetna.com##+js(aeld, /copy|cut|paste/)`

**Comment by crigler** [comment]
That blocks the first part of the code but not the `bind("input", function(e)` part
Adding `|input` to the regex makes pasting work:

`aetna.com##+js(aeld, /copy|cut|paste|input/)`

Thanks.

**Comment by mapx-** [comment]
However, just use it as custom filter, it's not something to be "fixed"
