### ISSUE TITLE
calmclinic.com: ads

### ISSUE THREAD

**Issue by reflector-finicky** [uBlockOrigin/uAssets#20425]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.calmclinic.com/anxiety/symtoms/body-shaking`

### Category

ads

### Description

Ads are shown in the article and on the side of the article.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/149769509/b74ab858-d8d9-4d4b-9a53-0e6bca17e33b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 105109
 cosmetic: 40315
 scriptlet: 18668
 html: 1078
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36008-139, 10m
  ublock-badware: 7425-5, 10m
  ublock-privacy: 641-0, 10m
  ublock-unbreak: 2178-0, 10m
  ublock-quick-fixes: 226-44, 10m
  easylist: 72320-698, 10m
  easyprivacy: 32858-724, 10m
  urlhaus-1: 11555-0, 10m
  plowe-0: 3721-1, 10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1044 ms
 maxAssetCacheWait: 12 ms
popupPanel:
 blocked: 7
 network:
  googletagmanager.com: 7
```
</details>

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/f4f2763f06fc047937a59d12a8279b915d80461e
