### ISSUE TITLE
bdupload.info [Pop-up]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2042]
URL(s) where the issue occurs

`https://bdupload.info/ch89g6m70b6x`

Describe the issue

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.15.24

Settings

Default

**Comment by KiLL4FuNK** [comment]
Download Link

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7ba7492e9925a2b41df94833676a0480da629f5d

**Comment by ghajini** [comment]
popups
`https://bdupload.info/2657caazod9o`

**Comment by mapx-** [comment]
file not found

however, test these filters and eventually provide another test case

```
bdupload.info##+js(abort-on-property-write.js, decodeURIComponent)
bdupload.info##+js(abort-on-property-write.js, zfgloadedpopup)
bdupload.info##+js(abort-current-inline-script.js, zfgloadedpopup)
bdupload.info##[href="https://bdupload.info/dloadbutton.php"]
```

**Comment by ghajini** [comment]
works,thanks
on real working pages this issue doesn't work but at `file not found` page , popups are fixed by your filters

**Comment by ghajini** [comment]
`https://bdupload.info/dsvulzxqgmxu`
Would you suggest something 
Not a issue but increasing third parties,i wnat minimum scriptlet filters .......

**Comment by mapx-** [comment]
do your tests, see if there is some popup after all

**Comment by ghajini** [comment]
No ads after that, thanks

**Comment by ghajini** [comment]
Unknown third parties appearing....

`||*/r8ZjUhJI1F7LiruMt/*$important`
@ryanbr

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a075c624bf5c981770831d971cbda75dd11a266b

**Comment by ghajini** [comment]
Popup ads on `file not found pages`
`https://bdupload.info/fn4sq04ep470`

**Comment by ghajini** [comment]
Sir how about changing filter to

 ||naustoch.net^$important,document 

from 

||naustoch.net^$third-party

**Comment by mapx-** [comment]
Where do you get that domain ?

**Comment by ghajini** [comment]
here 
 `https://bdupload.info/fn4sq04ep470`
before your fix `bdupload.info##+js(abort-current-inline-script.js, Math, zfgloaded)` , 

`||naustoch.net^$third-party` present in ublock filters

still popup is generated from same domain only...
![Screenshot (13)](https://user-images.githubusercontent.com/20338483/58412373-f4602400-8093-11e9-9569-c28f8acf1527.png)

**Comment by ghajini** [comment]
domain changed
`https://bdupload.asia/kvhbln7e9f6d`
popups/shady xhr's at final download page when clicked anywhere in page

**Comment by ghajini** [comment]
`https://bdupload.asia/575oh1qm6se2`
popup ads
they have inline change from `math.sin` to `math.tan`
this is better fix
`bdupload.*##+js(addEventListener-defuser, DOMContentLoaded)` on my end
