### ISSUE TITLE
[nsfw] onitsukatiger.com: breakage

### ISSUE THREAD

**Issue by haya-ken** [uBlockOrigin/uAssets#20428]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.onitsukatiger.com/jp/ja-jp/product/moage-co/1183b555_001.html`

### Category

breakage

### Description

When "ublock origin" is enabled, the "color" and "size" selection areas are hidden and cannot be shopped on Onitsuka Tiger online store.😫

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 205256
 cosmetic: 203337
 scriptlet: 29790
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27986-31, 5m
  adguard-mobile-app-banners: 4722-9, 5m
  adguard-other-annoyances: 13729-19, 5m
  adguard-popup-overlays: 25022-68, 5m
  adguard-social: 21976-925, 5m
  adguard-widgets: 2335-3, 5m
  curben-phishing: 76992-20, 5m
  dpollock-0: 11583-8, 5m
  easylist-annoyances: 4158-203, 5m
  easylist-chat: 147-11, 5m
  easylist-newsletters: 6613-430, 5m
  easylist-notifications: 2858-1449, 5m
  [6 lists not shown]: [too many]
 default:
  user-filters: 996-7, never
  JPN-1: 13639-6, now
  easylist: 72321-335, 5m
  easyprivacy: 32858-300, 5m
  plowe-0: 3721-1452, 5m
  ublock-badware: 7421-157, 5m
  ublock-filters: 35128-519, 5m
  ublock-privacy: 641-8, 5m
  ublock-quick-fixes: 235-139, 5m
  ublock-unbreak: 2132-39, 5m
  urlhaus-1: 11555-2, 5m
filterset (user): [array of 996 redacted]
trustedset:
 added: [array of 55 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 52 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2300 ms (selfie)
 maxAssetCacheWait: 325 ms
popupPanel:
 blocked: 26
 network:
  onitsukatiger.com: 1
  adobedc.net: 4
  bing.com: 2
  clarity.ms: 1
  d2ibu2ug0mt5qp.cloudfront.net: 1
  doubleclick.net: 3
  facebook.net: 1
  go-mpulse.net: 2
  google.com: 2
  ladsp.com: 1
  line-scdn.net: 1
  newrelic.com: 2
  nr-data.net: 4
  yahoo.co.jp: 1
 extended:
  ##.cookie-status-message
  ##.social-share
  ###back-top
```
</details>

**Comment by mapx-** [comment]
add

`@@||static-ojp.onitsukatiger.com/static/*_Newsletter/js/validation-mixin.min.js$script,1p`

@ryanbr
