### ISSUE TITLE
satyaclub.in: detection

### ISSUE THREAD

**Issue by Armageddon510** [uBlockOrigin/uAssets#20420]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

satyaclub.in

or

`https://satyaclub.in/securing-your-dream-home-the-mortgage-guide-you-need/`

### Description

Using uBlock causes the website to detect an ad-blocker. Disabling javascript or using the element picker gets rid of the warning, but causes the "Please wait 15 Seconds" prompt to freeze.

### Other extensions used

Nano Defender for Firefox was used and didn't help

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-11-02 163334](https://github.com/uBlockOrigin/uAssets/assets/149737331/1f6ae519-8906-4556-b5d2-c3863f24fa6f)
![Screenshot 2023-11-02 163348](https://github.com/uBlockOrigin/uAssets/assets/149737331/6e4cfc80-d17e-4a7f-8af6-efe69a5346ce)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 105056
 cosmetic: 40996
 scriptlet: 18672
 html: 1078
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 1058-7, 30m
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, never
  https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 0-0, never
 default:
  user-filters: 0-0, never
  ublock-filters: 36008-142, 30m
  ublock-badware: 7425-5, 30m
  ublock-privacy: 641-0, 30m
  ublock-unbreak: 2179-0, 30m
  ublock-quick-fixes: 226-44, 30m
  easylist: 72285-700, 30m
  easyprivacy: 32852-724, 30m
  urlhaus-1: 11180-0, 30m
  plowe-0: 3721-1, 30m
filterset (user): [empty]
switchRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 243 ms (selfie)
 maxAssetCacheWait: 48 ms
popupPanel:
 blocked: 27
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  satyaclub.in: 21
  cloudflare.com: 1
  doubleclick.net: 1
  googletagmanager.com: 2
  gplinks.in: 1
  jquery.com: 1

```
</details>

**Comment by gorhill** [comment]
> Nano Defender for Firefox was used and didn't help

Don't use external solutions to bypass anti-blockers, it's done by default in uBO, we add filters as people report these. External tools will interfere negatively with uBO's own ways, and it's even worse with unmaintained, abandoned project -- Nano Defender's last update is over 3 years ago.

**Comment by Armageddon510** [comment]
> > Nano Defender for Firefox was used and didn't help
> 
> Don't use external solutions to bypass anti-blockers, it's done by default in uBO, we add filters as people report these. External tools will interfere negatively with uBO's own ways, and it's even worse with unmaintained, abandoned project -- Nano Defender's last update is over 3 years ago.

I had tried it without Nano Defender before and it didn't work. I only got it after I tried everything else as a last resort.

**Comment by gorhill** [comment]
The first resort is to report the issue here.
