### ISSUE TITLE
instagram.com: breakage

### ISSUE THREAD

**Issue by sanpedro0** [uBlockOrigin/uAssets#20422]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.instagram.com/`

### Category

breakage

### Description

> no se abren las historia porque no puede reproducir publicidad
no deja abrir historias supongo yo que es porque instagram detecta el bloqueador de anuncio y no deja ver historias 
se queda cargando y no abre ninguna histori

**stories won't open because it can't play ads
it won't let you open stories I guess it's because instagram detects the ad blocker and won't let you view stories
it keeps loading and doesn't open any stories.**

### Other extensions used

ninguna extencion

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 107583
 cosmetic: 46594
 scriptlet: 19212
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72285-15, now
  easyprivacy: 32852-64, now
  plowe-0: 3721-1072, now
  spa-0: 3767-19, 18m
  spa-1: 5690-225, now
  ublock-badware: 7421-138, now
  ublock-filters: 35129-174, now
  ublock-privacy: 641-6, now
  ublock-quick-fixes: 229-135, now
  ublock-unbreak: 2133-34, now
  urlhaus-1: 11555-0, 19m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 759 ms (selfie)
 maxAssetCacheWait: 420 ms
popupPanel:
 blocked: 24
 network:
  instagram.com: 23
  facebook.com: 1
```
</details>

**Comment by sanpedro0** [comment]
de resto el bloqueador esta remelo

**Comment by gorhill** [comment]
> `https://www.instagram.com/`

That is Instagram's home page, there is no stories there. Post the exact URL address where you have an issue.
