### ISSUE TITLE
cosenzaduepuntozero.it: ads

### ISSUE THREAD

**Issue by giggios** [uBlockOrigin/uAssets#20427]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cosenzaduepuntozero.it/apre-oggi-nel-cosentino-il-piu-grande-villaggio-di-natale-del-sud-italia/`

### Category

ads

### Description

> Si vede le Ads si vedono delle pubblicità che compaiono

**You see the Ads you see the advertisements that appear**

### Other extensions used

Nessuna

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 115787
 cosmetic: 119291
 scriptlet: 23259
 html: 1079
listset (total-discarded, last-updated):
 added:
  adguard-social: 21976-1311, now
  adguard-cookies: 27985-1605, now
  adguard-popup-overlays: 25021-920, now
  adguard-mobile-app-banners: 4722-17, now
  adguard-other-annoyances: 13727-19, now
  adguard-widgets: 2335-36, now
  ublock-cookies-adguard: 468-0, now
 default:
  user-filters: 12-0, never
  ublock-filters: 36324-751, now
  ublock-badware: 7419-5, now
  ublock-privacy: 641-1, now
  ublock-unbreak: 2183-1, now
  ublock-quick-fixes: 226-44, 1m
  adguard-mobile: 8815-128, now
  easylist: 72271-16767, 1m
  easyprivacy: 32858-737, now
  urlhaus-1: 11555-0, 1m
  plowe-0: 3721-1, 1m
  ITA-0: 10093-442, 1m
filterset (user): [array of 12 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 673 ms (selfie)
 maxAssetCacheWait: 142 ms
popupPanel:
 blocked: 10
 network:
  cosenzaduepuntozero.it: 1
  eadv.it: 6
  facebook.net: 1
  googletagmanager.com: 1
  vaisulweb.cloud: 1
```
</details>

**Comment by mapx-** [comment]
add

```
||cosenzaduepuntozero.it/wp-content/uploads/pum/pum-site-scripts.js
cosenzaduepuntozero.it##.adcontainer
cosenzaduepuntozero.it##[class*="ai-center"]
```
