### ISSUE TITLE
nanoreview.net: ads

### ISSUE THREAD

**Issue by przemo20** [uBlockOrigin/uAssets#20433]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nanoreview.net/en/phone-compare/samsung-galaxy-s23-vs-apple-iphone-13`

### Category

ads

### Description

Leftover ad boxes:
- The “Promotion” text is visible on the right hand side of the page
- Two “Promotion” ad boxes: one under the “Key differences” section, and the second one – below the “Value for money” section.

Other example URL:
`https://nanoreview.net/en/soc/snapdragon-8-plus-gen-1` – only one ad box; under “Smartphones” heading

### Other extensions used

- Augmented Steam
- F.B Purity - Cleans up Facebook
- Tab Auto Refresh
- ySense Addon

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/22180480/0601e9d6-a8fa-4eb4-8c31-840186d6dfeb)

![obraz](https://github.com/uBlockOrigin/uAssets/assets/22180480/cc2332af-ca54-4f82-91a3-654d28637e9f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 106795
 cosmetic: 49356
 scriptlet: 22612
 html: 1279
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5646-15, now
 default:
  user-filters: 42-0, never
  ublock-filters: 36062-223, now
  ublock-badware: 7418-5, now
  ublock-privacy: 642-0, now
  ublock-unbreak: 2178-0, now
  ublock-quick-fixes: 236-44, now
  easylist: 72322-715, now
  easyprivacy: 32858-725, now
  urlhaus-1: 11555-0, now
  plowe-0: 3720-1, now
  POL-0: 8006-27, now
  POL-2: 1279-12, now
filterset (user): [array of 43 redacted]
trustedset:
 added: [array of 33 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 375 ms (selfie)
 maxAssetCacheWait: 127 ms
popupPanel:
 blocked: 3
 network:
  nanostatistics.net: 1
  quantserve.com: 1
  vlitag.com: 1
 extended:
  ##.adsbyvli
```
</details>

**Comment by mapx-** [comment]
add

```
nanoreview.net###nfloat-sb-right
nanoreview.net##.sinad_only_desktop
```

@ryanbr
