### ISSUE TITLE
luciferdonghua.in: detection

### ISSUE THREAD

**Issue by CruschBG** [uBlockOrigin/uAssets#20438]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://luciferdonghua.in/`

### Category

detection

### Description

Ad Blocker Detected overlay

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/114215465/21505b82-94af-497d-8028-7405db9bdf06)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 105423
 cosmetic: 40290
 scriptlet: 18788
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 13-0, never
  easylist: 72337-15, now
  easyprivacy: 32858-64, now
  plowe-0: 3720-1073, now
  ublock-badware: 7414-138, now
  ublock-filters: 35149-145, now
  ublock-privacy: 642-6, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 11860-0, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4776 ms (selfie)
 maxAssetCacheWait: 720 ms
popupPanel:
 blocked: 20
 network:
  bidgear.com: 1
  d3u598arehftfk.cloudfront.net: 1
  demand.supply: 1
  doubleclick.net: 1
  google.com: 5
  googlesyndication.com: 5
  googletagmanager.com: 3
  sophomoreguessingestrange.com: 1
  wp.com: 1
  yandex.ru: 1
 extended:
  ##ins.adsbygoogle
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by D4niloMR** [comment]
Add:

`luciferdonghua.in##+js(noeval-if, /chp_?ad/)`

**Comment by Bikas001** [comment]
its again started detecting
I used this filter to block successfully: `luciferdonghua.in##.afu-overlay, .afu-zp`
