### ISSUE TITLE
genshinlab.com: ads

### ISSUE THREAD

**Issue by dev0T** [uBlockOrigin/uAssets#20435]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://genshinlab.com/`

### Category

ads

### Description

After opening the website there are no ads but a few seconds to a minute they are displayed. I noticed that sometimes the provider of the ads changes. Sometimes the ads are provided by Ad-Shield and sometimes by AdChoices. I also tried reseting my extension to the default settings since I was unsure if I added any extra filters. Please let me know if I can provide any more information.

### Other extensions used

<details>
<summary>Extensions</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/28127196/25d9bfd8-2564-4ecc-87ef-1c69bbfa81d3)
![image](https://github.com/uBlockOrigin/uAssets/assets/28127196/d4e7d350-a590-45ca-84d0-6b360042ea29)
![image](https://github.com/uBlockOrigin/uAssets/assets/28127196/3f6b9fbf-aacf-4695-876f-3286f4e0b233)

</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/28127196/e6083808-bf29-4dc1-8871-6fcd642b06bf)
![image](https://github.com/uBlockOrigin/uAssets/assets/28127196/e59f1b1f-7234-45d7-b170-8d3d584a22de)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 105084
 cosmetic: 40342
 scriptlet: 18680
 html: 1078
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 36041-139, 13m
  ublock-badware: 7425-5, 13m
  ublock-privacy: 641-0, 13m
  ublock-unbreak: 2178-0, 13m
  ublock-quick-fixes: 236-44, 13m
  easylist: 72337-656, 13m
  easyprivacy: 32858-767, 13m
  urlhaus-1: 11510-0, 13m
  plowe-0: 3720-1, 13m
filterset (user): [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1544 ms
 maxAssetCacheWait: 4 ms
popupPanel:
 blocked: 112
 network:
  07c225f3.online: 93
  connatix.com: 2
  criteo.net: 1
  duckduckgo.com: 2
  fonts.googleapis.com: 7
  googlesyndication.com: 2
  googletagmanager.com: 2
  nitropay.com: 2
  steadfastsystem.com: 1
```
</details>

**Comment by D4niloMR** [comment]
Try:

```adb
||07c225f3.online^$domain=genshinlab.com
genshinlab.com##+js(aeld, error)
```

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon Is it ad-shield?

**Comment by JobcenterTycoon** [comment]
Yes, its Ad-Shield.

Seems to be the site has no Ad-Shield PHP part, this is why noeval works here without breaking the page. First time i saw Ad-Shield Ad-Reinsertion done without the PHP part. All other sites before like ygosu using a script tag to embed the Ad-Shield script and the Ad-Shield script loading the page.

I added the noeval filter to the other Ad-Shield filter https://github.com/uBlockOrigin/uAssets/commit/c24e93241e52fa710f9b0325b9fb409a01232657

**Comment by dev0T** [comment]
Vising the webpage without the custom filter provided previously and no ads. Thank you so much!
