### ISSUE TITLE
join.southerncross.co.nz: breakage

### ISSUE THREAD

**Issue by roldengarm** [uBlockOrigin/uAssets#20436]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://join.southerncross.co.nz/quote`

### Category

breakage

### Description

The form for the quote doesn't load. With uBlock disabled, it loads fine.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 105096
 cosmetic: 40326
 scriptlet: 18659
 html: 1077
listset (total-discarded, last-updated):
 default:
  user-filters: 14-0, never
  ublock-filters: 36025-184, now
  ublock-badware: 7418-5, now
  ublock-privacy: 642-0, now
  ublock-unbreak: 2177-0, now
  ublock-quick-fixes: 236-44, 44m
  easylist: 72322-698, now
  easyprivacy: 32858-725, now
  urlhaus-1: 11555-0, now
  plowe-0: 3720-1, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 682 ms (selfie)
 maxAssetCacheWait: 70 ms
popupPanel:
 blocked: 3
 network:
  southerncross.co.nz: 1
  googletagmanager.com: 1
  typekit.net: 1
```
</details>

**Comment by gorhill** [comment]
Broken by `/gtm.js` in EasyPrivacy.

Until fixed in EasyPrivacy, you can use `@@/gtm.js$1p,script,domain=southerncross.co.nz`

cc @ryanbr

**Comment by roldengarm** [comment]
@gorhill thanks, I can confirm that that filter fixes the issue.
