### ISSUE TITLE
tubewolf.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2043]
URL(s) where the issue occurs

`http://www.tubewolf.com/movies/fuck-her-russian-ass-hard/`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.15.24

Settings

Default

**Comment by okiehsch** [comment]
||tubewolf.com/adman_ai/s/s/su.php$subdocument

**Comment by SMed79** [comment]
```
/adman_ai/*
```
@ryanbr https://forums.lanik.us/viewtopic.php?f=62&t=37654

**Comment by KiLL4FuNK** [comment]
I can not start video

**Comment by mapx-** [comment]
test
```
@@||js.helltraffic.com/fluidplayer/$script,stylesheet,domain=tubewolf.com
||js.helltraffic.com/fluidplayer/scripts/webvtt.min.js$script,important,domain=tubewolf.com
tubewolf.com##.bnnrs-player
tubewolf.com##.bnnr
```

**Comment by KiLL4FuNK** [comment]
works well the only thing missing is the pause button disappears

**Comment by mapx-** [comment]
well .. you can click on video to pause it

**Comment by KiLL4FuNK** [comment]
if it works well put it
