### ISSUE TITLE
onvista.de: breakage

### ISSUE THREAD

**Issue by rolandbeck** [uBlockOrigin/uAssets#20432]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.onvista.de/etf/sparplan/iShares-USD-Treasury-Bond-20-years-UCITS-ETF-USD-Dis-ETF-IE00BSKRJZ44`

### Category

breakage

### Description

Only two of the brokers have graphical icons when uBlock is activated.

When I deactivate uBlock that part of the website is displayed correctly.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBlock enabled
![with_uBlock](https://github.com/uBlockOrigin/uAssets/assets/20404789/136a068e-7070-44d0-8e52-d777ec53c149)

uBlock disabled
![without_uBlock](https://github.com/uBlockOrigin/uAssets/assets/20404789/703627e0-a2e0-4fee-950e-24287aa69565)

</details>
/

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 107476
 cosmetic: 45112
 scriptlet: 18817
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7179-0, 11m
  easylist: 72322-21, 11m
  easyprivacy: 32858-73, 11m
  plowe-0: 3720-1074, 11m
  ublock-badware: 7421-138, 11m
  ublock-filters: 35182-159, 11m
  ublock-privacy: 642-6, 11m
  ublock-quick-fixes: 239-189, 11m
  ublock-unbreak: 2132-34, 11m
  urlhaus-1: 11555-0, 11m
filterset (user): [empty]
trustedset:
 added: [array of 43 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 574 ms (selfie)
 maxAssetCacheWait: 268 ms
popupPanel:
 blocked: 9
 network:
  onvista.de: 3
  atf-tagmanager.de: 1
  googletagmanager.com: 1
  vercel-insights.com: 4
 extended:
  ##div[class*="InteractionTypeReference_ov-interaction-slot--fall…
  ##a[href^="https://www.financeads.net/tc.php?"]
  ##atf-ad-slot
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by mapx-** [comment]
add

`onvista.de#@#a[href^="https://www.financeads.net/tc.php?"]`

@khrin @ryanbr
