### ISSUE TITLE
chat.openai.com: privacy

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#20440]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chat.openai.com/auth/login`

### Category

privacy

### Description

The endpoint `https://chat.openai.com/ces/v1/<1-character>` is used to track page and user analytics. At the very least, it logs current page, page referrer, user agent, and user id. The request is observable with or without being logged in. The endpoint is part of the site's implementation of `segment.io`'s `analytics.js`

We cannot use `||chat.openai.com/ces/v1^` because the site's other functionalities interact with the endpoint `https://chat.openai.com/ces/v1/<path>`. I propose the following.
```adblock
/^https:\/\/chat\.openai\.com\/ces\/v1\/[a-z]{1}$/$xhr,1p,method=post,match-case
```

Some examples of the mentioned request can be seen below in the attached screenshots.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![home](https://github.com/uBlockOrigin/uAssets/assets/115052854/79c3c314-64b9-4948-a39c-7d17cd30fed1)

![login](https://github.com/uBlockOrigin/uAssets/assets/115052854/c3bb3785-dc05-4b24-b5f2-f2d7e75f6998)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.1b3
Firefox: 119
filterset (summary):
 network: 105420
 cosmetic: 40327
 scriptlet: 18659
 html: 1077
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36032-46, 29m
  ublock-badware: 7418-5, 30m
  ublock-privacy: 642-0, 30m
  ublock-unbreak: 2177-2, 30m
  ublock-quick-fixes: 236-180, 30m
  easylist: 72365-267, 30m
  easyprivacy: 32843-85, 30m
  urlhaus-1: 11860-0, 30m
  plowe-0: 3720-1074, 30m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 208 ms (selfie)
 maxAssetCacheWait: 106 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Currently addressed here: https://github.com/easylist/easylist/commit/045b20c1371640843a009a24867956d6335d0c21 . We can wait if they would adjust the URL or not.
