### ISSUE TITLE
shrinkme.info: ads

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#20447]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shrinkme.info/6E98F`

### Category

ads

### Description

ads

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 113054
 cosmetic: 145142
 scriptlet: 28142
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27994-31, now
  easylist-annoyances: 4159-42, now
  easylist-chat: 148-0, now
  easylist-newsletters: 6616-23, now
  easylist-notifications: 2861-83, now
  fanboy-cookiemonster: 48805-3808, now
  fanboy-social: 16164-13, now
  fanboy-thirdparty_social: 68-15, now
  ublock-annoyances: 5687-85, now
  ublock-cookies-easylist: 430-430, now
 default:
  user-filters: 0-0, never
  TUR-0: 13864-10, now
  easylist: 72402-39, now
  easyprivacy: 32844-159, now
  plowe-0: 3720-1075, now
  ublock-badware: 7420-138, now
  ublock-filters: 35144-175, now
  ublock-privacy: 651-9, now
  ublock-quick-fixes: 235-182, now
  ublock-unbreak: 2131-37, now
  urlhaus-1: 11500-0, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1198 ms (selfie)
 maxAssetCacheWait: 161 ms
popupPanel:
 blocked: 9
 network:
  clarity.ms: 1
  d34gjfm75zhp78.cloudfront.net: 1
  gloaphoo.net: 1
  googletagmanager.com: 1
  primalredfish.com: 1
  shriftskats.com: 4
```
</details>

**Comment by BlazeFTL** [comment]
No detection On My Side
Others Things To Adress
```
shrinkme.info##.clickbtnt.expop, .blog-item, footer, .col-md-offset-1.col-md-10 > center
shrinkme.info##+js(rmnt, script, window.open)
