### ISSUE TITLE
karaoketexty.cz: ads

### ISSUE THREAD

**Issue by Halila81** [uBlockOrigin/uAssets#20444]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.karaoketexty.cz/`

### Category

ads

### Description

Ublock Origin isn´t blocking any ads at all on this page. I don´t know if there´s even any filter for it, or is it something with my browser? This page is biggest czech site with lyrics for songs and all these ads are really anoying. 

### Other extensions used

Fluff Busting Purity
Ruffle - Flash Emulator

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Bez názvu](https://github.com/uBlockOrigin/uAssets/assets/149873803/2895d16c-e050-42a3-803f-8f0ca6fff2c2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 109
filterset (summary):
 network: 105669
 cosmetic: 40735
 scriptlet: 18967
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 9-0, never
  CZE-0: 798-1, 6m
  easylist: 72372-17, 6m
  easyprivacy: 32844-70, 6m
  plowe-0: 3720-1073, 6m
  ublock-badware: 7415-138, 6m
  ublock-filters: 35155-146, 6m
  ublock-privacy: 643-7, 6m
  ublock-quick-fixes: 241-182, 6m
  ublock-unbreak: 2131-32, 6m
  urlhaus-1: 11860-0, 6m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 12 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5359 ms (selfie)
 maxAssetCacheWait: 250 ms
popupPanel:
 blocked: 19
 network:
  karaoketexty.cz: 1
  bbelements.com: 2
  dopc.cz: 1
  gemius.pl: 1
  google-analytics.com: 1
  google.com: 5
  googletagmanager.com: 1
  m6r.eu: 1
  mookie1.com: 1
  performax.cz: 2
  pubmatic.com: 1
  screechingstove.com: 1
  toplist.cz: 1
 extended:
  ##[class*="ad_"]
  ##+js(addEventListener-defuser, beforeunload, ())
  ##+js(abort-current-script, document.createElement, adbDetect)
  ##+js(cookie-remover, /^_?adb/)
```
</details>

**Comment by mapx-** [comment]
test

```
karaoketexty.cz##+js(nostif, /native|\{n\(\)/)
karaoketexty.cz##+js(ra, style, [style^="background"], stay)
karaoketexty.cz##+js(ra, href, [target^="_"], stay)
```

**Comment by okiehsch** [comment]
Works fine on my end.

**Comment by Halila81** [comment]
> karaoketexty.cz##+js(nostif, /native|\{n\(\)/)
> karaoketexty.cz##+js(ra, style, [style^="background"], stay)
> karaoketexty.cz##+js(ra, href, [target^="_"], stay)

Thank you very very much :) It works perfectly.
