### ISSUE TITLE
omroepbrabant.nl: breakage

### ISSUE THREAD

**Issue by Waxli** [uBlockOrigin/uAssets#20445]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.omroepbrabant.nl/nieuws/4365870/de-bekendste-drugsbaron-van-brabant-is-dit-de-echte-ferry-bouman`

### Category

breakage

### Description

It says it is waiting for privacysettings.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 204339
 cosmetic: 143881
 scriptlet: 29659
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  NLD-0: 2716-22, now
  adguard-cookies: 27993-1591, now
  adguard-mobile-app-banners: 4725-17, now
  adguard-other-annoyances: 13734-15, now
  adguard-popup-overlays: 25037-107, now
  adguard-social: 21994-2065, now
  adguard-widgets: 2338-38, now
  curben-phishing: 77172-20, now
  dpollock-0: 11583-6, now
  easylist-annoyances: 4159-1063, now
  easylist-chat: 147-20, now
  [8 lists not shown]: [too many]
 default:
  user-filters: 104-45, never
  easylist: 72372-16285, now
  easyprivacy: 32844-276, now
  plowe-0: 3720-1448, now
  ublock-badware: 7420-148, now
  ublock-filters: 35141-714, now
  ublock-privacy: 644-9, now
  ublock-quick-fixes: 243-188, now
  ublock-unbreak: 2131-37, now
  urlhaus-1: 11500-2, now
filterset (user): [array of 665 redacted]
trustedset:
 added: [array of 84 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 10 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 862 ms (selfie)
 maxAssetCacheWait: 529 ms
popupPanel:
 blocked: 6
 network:
  aticdn.net: 1
  dimml.io: 1
  googletagmanager.com: 1
  optoutadvertising.com: 1
  outbrain.com: 1
  scorecardresearch.com: 1
 extended:
  ##div[class^="ad_"]
  ##div[class^="consent-manager_pageFiller"]
  ##[class^="consent-manager"]
```
</details>

**Comment by okiehsch** [comment]
@Yuki2718 
Video broken by 
`omroepbrabant.nl##div[class^="consent-manager_pageFille`
in `AdGuard – Cookie Notices)`.

@Waxli add 
`omroepbrabant.nl##div[class^="consent-manager_pageFille`
to your filter list.
Next time if you tick the box
` I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.`
then do as you say. You have enabled 19 additional lists...

**Comment by Yuki2718** [comment]
Hmm, clicking `Accepteer alles en sla op` doesn't change their cookie but adds yt cookie. Is there an alternative solution? @peace2000

**Comment by peace2000** [comment]
@Yuki2718 

This site needs local storage items.

These fix the video and make the dialog go away:

`omroepbrabant.nl##+js(set-local-storage-item, psh:cookies-other, false)`
`omroepbrabant.nl##+js(set-local-storage-item, psh:cookies-seen, true)`
`omroepbrabant.nl##+js(set-local-storage-item, psh:cookies-social, true)`

Can you add those to AG cookie list and to Easylist cookie list?

Also, this needs to be removed from Easylist cookie list:
`omroepbrabant.nl##[class^="consent-manager"]`
