### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by radenwahid** [uBlockOrigin/uAssets#20443]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=73Kl2FRjo0A&t=819s`

### Category

detection

### Description

Can't watch YouTube because a notification was detected using ublock

### Other extensions used

ublock origin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 109703
 cosmetic: 45685
 scriptlet: 18824
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  IDN-0: 9671-3, now
  easylist: 72372-24, now
  easyprivacy: 32844-66, now
  plowe-0: 3720-1073, now
  ublock-badware: 7415-138, now
  ublock-filters: 35155-165, now
  ublock-privacy: 643-7, now
  ublock-quick-fixes: 241-182, now
  ublock-unbreak: 2131-33, now
  urlhaus-1: 11860-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1285 ms
 maxAssetCacheWait: 11 ms
popupPanel:
 blocked: 4
 network:
  doubleclick.net: 1
  google.co.id: 1
  google.com: 2
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytd-player-legacy-desktop-watch-ads-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##ytd-companion-slot-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(json-prune-fetch-response, [].playerResponse.adPlacements …
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
