### ISSUE TITLE
tucinehd.com: detection

### ISSUE THREAD

**Issue by gototheskinny** [uBlockOrigin/uAssets#20448]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tucinehd.com/pelicula/coraline-y-la-puerta-secreta-2009-remux-1080p-latino-espanol-ingles/`

### Category

detection

### Description

aa

### Other extensions used

fastforward, ag extra, violantmonkey w/adguard popup blocker beta, dark reader, video speed controller, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![SharedSsfasfasdgcccreenshot](https://github.com/uBlockOrigin/uAssets/assets/51786709/985cbdb1-93b6-4fbf-95f9-8d2351595b65)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 113054
 cosmetic: 145142
 scriptlet: 28142
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 27994-31, 8m
  easylist-annoyances: 4159-42, 8m
  easylist-chat: 148-0, 8m
  easylist-newsletters: 6616-23, 8m
  easylist-notifications: 2861-83, 8m
  fanboy-cookiemonster: 48805-3808, 8m
  fanboy-social: 16164-13, 8m
  fanboy-thirdparty_social: 68-15, 8m
  ublock-annoyances: 5687-85, 8m
  ublock-cookies-easylist: 430-430, 8m
 default:
  user-filters: 0-0, never
  TUR-0: 13864-10, 8m
  easylist: 72402-39, 8m
  easyprivacy: 32844-159, 8m
  plowe-0: 3720-1075, 8m
  ublock-badware: 7420-138, 8m
  ublock-filters: 35144-175, 8m
  ublock-privacy: 651-9, 8m
  ublock-quick-fixes: 235-182, 8m
  ublock-unbreak: 2131-37, 8m
  urlhaus-1: 11500-0, 8m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1198 ms (selfie)
 maxAssetCacheWait: 161 ms
popupPanel:
 blocked: 18
 network:
  adskeeper.com: 2
  alleviatepracticableaddicted.com: 1
  chatango.com: 2
  disqus.com: 1
  facebook.net: 1
  geniusdexchange.com: 2
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  hqq.to: 1
  sadjklq.com: 1
  viglink.com: 2
  yadro.ru: 1
  yandex.ru: 1
 extended:
  ##.module_single_ads
  ##.dt_social_single
  ###ad-campaign
  ###mpuWrapper
  ###my-ads
  ###single-ad
  ###top_adv
  ##div[id*="ScriptRoot"]
  ##+js(set-constant, document.oncontextmenu, null)
  ##+js(set-constant, document.onkeydown, trueFunc)
  ##+js(no-setTimeout-if, debugger)
  ##+js(set-constant, console.clear, noopFunc)
  ##+js(abort-on-property-read, adBlockDetected)
  ##+js(popads-dummy)
  ##+js(set-constant, sadbl, false)
  ##+js(no-window-open-if)
  ##+js(set-constant, adblockcheck, false)
  ##+js(remove-node-text, script, self == top)
  ##.icon-facebook-circle
  ##.share-icons-wrapper
  ###email-signup
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by okiehsch** [comment]
@Yuki2718 
`tucinehd.com##+js(nostif, nextFunction, 2000)`
for the regional spanish list.

**Comment by Yuki2718** [comment]
This is antiblock .org and will be addressed in Base.

**Comment by detyso** [comment]
ads pop up on this site 
https://pastevip.tucinehd.com/?v=lGZ
