### ISSUE TITLE
keukenatlas.nl: breakage

### ISSUE THREAD

**Issue by christiaan** [uBlockOrigin/uAssets#20449]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.keukenatlas.nl/online-keukenplannerjs/start/r:primokeukens/`

### Category

breakage

### Description

The web application will not load with uBlockOrigin enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 105756
 cosmetic: 42346
 scriptlet: 18845
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  NLD-0: 2716-9, now
  easylist: 72402-17, now
  easyprivacy: 32844-65, now
  plowe-0: 3720-1073, now
  ublock-badware: 7420-138, now
  ublock-filters: 35144-148, now
  ublock-privacy: 651-7, now
  ublock-quick-fixes: 235-178, now
  ublock-unbreak: 2131-32, now
  urlhaus-1: 11500-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 198 ms (selfie)
 maxAssetCacheWait: 100 ms
popupPanel:
 blocked: 3
 network:
  jsdelivr.net: 1
  kuechen-atlas.de: 1
  wurfl.io: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`@@||wurfl.io/wurfl.js$script,domain=keukenatlas.nl`

**Comment by okiehsch** [comment]
@ryanbr my bad, it's actually caused by our own list.
