### ISSUE TITLE
pinterest.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#2044]
**URL(s) where the issue occurs**

e.g. 
`https://www.pinterest.com/pin/434597432784447356/` 
(scroll down).

**Describe the issue**

Annoyance >> No allowed to see content without sign in.

**Screenshot(s)**

* http://i.imgur.com/DJ6GSRJ.png

**Versions**

- Browser/version: any / latest version
- uBlock Origin version: latest stable version

**Settings**

+ default settings/lists 
+ also enabled
  uBlock filters – Annoyances​​​​​​​​​
  Fanboy’s Annoyance List
  Adblock Warning Removal List​​​​​​​​​

**Comment by okiehsch** [comment]
Do you want to use the site without logging in or do you only want to see more content while scrolling down?
I can add a filter that allows you to see more content but if you click on any item you will have to login.

**Comment by okiehsch** [comment]
I can fix the example link given by adding
` pinterest.*##script:inject(addEventListener-defuser.js, scroll, clearTimeout)`

**Comment by mapx-** [comment]
or
```
||smartlock.google.com/client$script,domain=pinterest.com
||pinimg.com/webapp/$script,domain=pinterest.com
```

However the next page (clicking some pic) is still blocked

**Comment by okiehsch** [comment]
That is why I did not add the filter, I can't fix the net page.
The strange thing is if I click any pic I am blocked. If I then copy the address, then paste it and reload the page works on my end.

**Comment by SMed79** [comment]
> pinterest.*##script:inject(addEventListener-defuser.js, scroll, clearTimeout)

next page I get the login nag screen without scrolling the page.
- https://i.imgur.com/rqELjFl.gifv

> ||smartlock.google.com/client$script,domain=pinterest.com
> ||pinimg.com/webapp/$script,domain=pinterest.com

thank you for trying anyway :)

> That is why I did not add the filte

Not matter, you can leave it.

Thanks again.

**Comment by gorhill** [comment]
How about:

    www.pinterest.ca##[data-test-giftwrap]
    www.pinterest.ca##.FullPageModal__scroller
    www.pinterest.ca##div[style$="z-index: 1000;"]

**Comment by uBlock-user** [comment]
Works, however if open any pin in another tab, then that remains without a scrollbar

**Comment by gorhill** [comment]
I added `pinterest.ca###desktopWrapper:style(position: static !important;)`.

**Comment by gorhill** [comment]
I don't know that site much, it still feels broken after I click an image, there are no top bar.

**Comment by SMed79** [comment]
That much better, thank you.

**Comment by krystian3w** [comment]
Now, no open new tab, no load new link (website no correct refresh) and again blocked scroll.

```
pinterest.*##div:nth-of-type(2) > div:nth-of-type(3) > div
pinterest.*##body:style(overflow-y:scroll!important;)
```

Remove "wall" html element end enable scroll, repair refresh it's a hard work caliber for me.

**Comment by adranger** [comment]
It's not possible to edit a pin with the Annoyances list turned on because it hides the edit overlay. Save something to your account, open it and click on this icon:

![ublockorigin](https://user-images.githubusercontent.com/35470489/45241510-27bf1080-b2c3-11e8-8c06-c9d283d204b5.png)

**Comment by adranger** [comment]
@mapx-  `https://pinterest.com/pin-builder/`

1. The user's nickname is hidden:
![username](https://user-images.githubusercontent.com/35470489/53835557-8f9d9d80-3f6c-11e9-8405-2bd625b6902d.png)

2. The list of boards isn't displayed:
![list of boards](https://user-images.githubusercontent.com/35470489/53835612-b9ef5b00-3f6c-11e9-9562-ca6bba3a96f0.png)

**Comment by mapx-** [comment]
test again - update first annoyances list

**Comment by okiehsch** [comment]
@DandelionSprout fyi the filter
`pinterest.*##div:nth-of-type(2) > div > div > div > .Hsu.iyn.zI7 > div.Hsu.iyn.zI7:nth-of-type(2) > div`
hides the user nickname as mentioned by **adranger**.

**Comment by DandelionSprout** [comment]
Ah, okay. Pinterest was (and is) extremely difficult to write entries for, so I'm not sure when I could come up with a better entry for that.
