### ISSUE TITLE
techedubyte.com: detection

### ISSUE THREAD

**Issue by arslanashraf445** [uBlockOrigin/uAssets#20452]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.techedubyte.com/`

### Category

detection

### Description

It detect ublock

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium Mobile: 116
filterset (summary):
 network: 106512
 cosmetic: 31644
 scriptlet: 18853
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 20-0, never
  adguard-mobile: 8823-40, 4m
  easylist: 72402-16033, 3m
  easyprivacy: 32844-73, 3m
  plowe-0: 3720-1148, 3m
  ublock-badware: 7414-139, 3m
  ublock-filters: 35462-396, 3m
  ublock-privacy: 651-8, 3m
  ublock-quick-fixes: 235-178, 3m
  ublock-unbreak: 2137-35, 3m
  urlhaus-1: 11500-0, 1h.2m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1945 ms (selfie)
 maxAssetCacheWait: 270 ms
popupPanel:
 blocked: 8
 network:
  google.com: 1
  googlesyndication.com: 4
  googletagmanager.com: 1
  stpd.cloud: 2
 extended:
  ##[href^="https://betwinnerlive.com/"]
  ##ins.adsbygoogle
  ##+js(set-constant, checkAdsStatus, noopFunc)
```
</details>

**Comment by D4niloMR** [comment]
`techedubyte.com##+js(no-xhr-if, googlesyndication.com)`
