### ISSUE TITLE
datarejestracji.senda.pl: detection, nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#20454]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://datarejestracji.senda.pl/wyszukiwarka`

### Description

Anti-adblock looks back:

> 
> Attention!
> Your browser uses an ad blocking extension (AdBlock). Please disable them or add our site to exceptions to use the search engine for free.
> 
> Remember that the servers are powered by electricity and maintaining the website costs money, so have some mercy 😉

Maybe possible address lower cookie bar, page lament about needed accept to works that web app:

> Attention!
> To use the website you must accept cookies . Some ad blocking extensions (AdBlock) may block the display of the cookie message.
> 
> After accepting cookies, refresh the page.
> If you do not see the cookie notice at the bottom of the page, refresh the page.

### Other extensions used

none

### Screenshot(s)

N/A

### Configuration

uBo:
1.53.1b2

added:
POL-0, POL-2, uBo Annoyances.

Browser&system:
Firefox 119 on Windows 11

### Notes

Cookies maybe are compatible with EL Annoyances:

```adb
senda.pl##+js(set-cookie, cookieConsent3, true)
```

IDK how now fix detection of blocked ads.

**Comment by Daxy7** [comment]
anti detection after accepting cookies

```
@@||www.googletagmanager.com^$domain=senda.pl
```

**Comment by stephenhawk8054** [comment]
```adb
senda.pl##+js(no-fetch-if, googletagmanager)
```

for Polish lists?

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20454#issuecomment-1793633026 if you revive @olegwukr from Ukrainian building rubble, due MajkiIT may still deal with Eyeo lawyers so he can not add anti-adblock filters so as not to break the contract.
