### ISSUE TITLE
news.sky.com: nuisance

### ISSUE THREAD

**Issue by H80h23h30rj032jr-32rjw-q3** [uBlockOrigin/uAssets#20455]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://news.sky.com`

### Description

This website show me cookie banner.
I try to block it but cannot be blocked on Ublock Origin because is whitelisted this element on ublock origin itself: cdn.privacy-mgmt.com
This element show an annoyance cookie banner.
If I enable Advance User and block this element website works whithout annoyance cookie banner.
I am in European country and is affect me so much but I block cookies (if I can alone) but If I cannot I need an help for some websites.
This website has a problem. I also test my own filter for Brave Browser and does work so well.

(Sorry for my Bad English)

### Other extensions used

Dark Reader; Tampermonkey; Video Background Play Fix

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://drive.google.com/file/d/145nUVo5o3A7HkaXC3Z3UE5PGdHRtyqja/view?usp=drivesdk
https://drive.google.com/file/d/141oXWtoGrdhTu2YG5MZijEPs0vyVONOQ/view?usp=drivesdk
https://drive.google.com/file/d/14BtrupOcJ3GTZjnIxYl5y9ZJkXjMMQBa/view?usp=drivesdk

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 120
filterset (summary):
 network: 344377
 cosmetic: 354335
 scriptlet: 52189
 html: 1408
listset (total-discarded, last-updated):
 added:
  https://filters.adavoid.org/ultimate-ad-filter.txt: 149924-146822, 12h.33m
  https://filters.adavoid.org/ultimate-privacy-filter.txt: 62473-17172, 12h.33m
  https://filters.adavoid.org/ultimate-security-filter.txt: 7409-5, 12h.33m
  https://raw.githubusercontent.com/H80h23h30rj032jr-32rjw-q3/j3r0j3r-ew-r3r3rfd/main/cleanweb: 16946-5918, 45m
  adguard-generic: 79295-7815, 12h.34m
  adguard-spyware-url: 1303-82, 12h.34m
  adguard-spyware: 62677-62212, 12h.34m
  block-lan: 54-0, 12h.34m
  curben-phishing: 75639-32, 12h.34m
  adguard-social: 21994-869, 12h.34m
  adguard-cookies: 27993-354, 12h.34m
  ublock-cookies-adguard: 468-0, 12h.34m
  [44 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36349-807, 12h.35m
  ublock-badware: 7413-7240, 12h.35m
  ublock-privacy: 644-0, 12h.34m
  ublock-unbreak: 2182-1, 12h.34m
  ublock-quick-fixes: 231-45, 33m
  adguard-mobile: 8823-142, 12h.34m
  easylist: 72372-1463, 12h.34m
  easyprivacy: 32844-1037, 12h.34m
  urlhaus-1: 11860-0, 12h.34m
  plowe-0: 3720-1, 12h.34m
  ROU-1: 1448-23, 12h.33m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11862 ms
 maxAssetCacheWait: 7670 ms
popupPanel:
 blocked: 7
 network:
  sky.com: 1
  adobedtm.com: 2
  demdex.net: 2
  dotmetrics.net: 1
  indexww.com: 1
 extended:
  ##div.sdc-news-footer__row:nth-of-type(3)
  ##li.sdc-news-footer__list-item:nth-of-type(9)
  ###leaderboard
  ##div[data-ad-format="leaderboard"]
  ##.sdc-site-au[data-ad-format] > div[data-role="ad-container"]
  ##+js(trusted-set-cookie, consents, :4:6:7:8:9:10:11:12:13:19:)

```
</details>

**Comment by mapx-** [comment]
- if you use only the default lists + uBlock annoyances / cookies list => all fine
- if you add `EasyList – Annoyances` too => still ok

> I try to block it but cannot be blocked on Ublock Origin because is whitelisted this element on ublock origin itself: cdn.privacy-mgmt.com

You have enabled adguard lists (adguard-cookies) => where is that exception

Report the issue at AG repository => https://github.com/AdguardTeam/AdguardFilters/issues
or use `EasyList – Annoyances`

You have too many lists => on android use only the default ones + uBO annoyances + only 1 annoyances list (EL or AG)

**Comment by Daxy7** [comment]
ad placeholder [too small for easylist dimension guidelines]
```
https://news.sky.com/story/robert-f-kennedy-jr-apologises-for-super-bowl-advert-resembling-jfk-campaign-13070616
```
```
news.sky.com##[data-label-text="Advertisement"]
```
https://github.com/uBlockOrigin/uAssets/assets/91396482/da9c9ad9-9b96-488b-a744-d6ac8171923a

**Comment by D4niloMR** [comment]
AFAIK `AdGuard – Ads` add these filters.

**Comment by Daxy7** [comment]
by `news.sky.com##.sdc-article-body > .sdc-site-layout-sticky-region[data-format="floated-mpu"]`

**Comment by Marko-98** [comment]
Cookie notice appears.

URL: `https://news.sky.com`

<details>

```yaml
uBlock Origin: 1.68.0
Firefox: 146
filterset (summary):
 network: 325715
 cosmetic: 242747
 scriptlet: 60018
 html: 3082
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-generic: 91535-5657, now
  block-lan: 89-0, now
  curben-phishing: 133619-68, 1h.28m
  adguard-cookies: 36495-81, now
  ublock-cookies-adguard: 5264-75, now
  fanboy-cookiemonster: 44978-3653, now
  ublock-cookies-easylist: 5264-5264, now
  adguard-social: 25495-43, now
  fanboy-thirdparty_social: 69-3, now
  adguard-popup-overlays: 29645-956, now
  adguard-mobile-app-banners: 6672-95, now
  adguard-other-annoyances: 15391-318, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 18-0, never
  ublock-filters: 43806-69, now
  ublock-badware: 10999-32, now
  ublock-privacy: 3557-2, now
  ublock-unbreak: 2777-1, now
  ublock-quick-fixes: 459-14, now
  easylist: 88866-1175, now
  easyprivacy: 55098-119, now
  urlhaus-1: 26825-6, 1h.28m
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 70
 userFiltersTrusted: true
 webrtcIPAddressHidden: true
hiddenSettings:
 cloudStorageCompression: false
supportStats:
 allReadyAfter: 1187 ms
 maxAssetCacheWait: 885 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  adobedtm.com: 2
  brightcove.com: 6
  covatic.io: 1
  dotmetrics.net: 1
  imasdk.googleapis.com: 1
  outbrain.com: 1
 extended:
  ##.sdc-article-strapline
  ##.site-share-wrapper
  ##[data-format="leaderboard"]
  ##.ui-advert
  ##.ad
  ###mpu-1
  ###leaderboard
  ##.sdc-article-body > .sdc-site-layout-sticky-region[data-format…
  ##.sdc-site-layout-sticky-region__ghost[data-format="leaderboard…
  ##div[data-ad-format="leaderboard"]
  ##a[href^="whatsapp://send"]
  ##a[href^="https://x.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[title="Share on Facebook"]
  ##.OUTBRAIN
  ##.vjs-ima3-ad-container
```
</details>

https://github.com/user-attachments/assets/8dd98c18-ea79-4e4e-9d1d-3ba0fa53b6be


Happy New Year! 🎉
