### ISSUE TITLE
novelasflixbr.com: breakage

### ISSUE THREAD

**Issue by TatianaPink** [uBlockOrigin/uAssets#20453]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://novelasflixbr.com/episodios/imperio-de-mentiras-1x1/`

### Category

breakage

### Description

Click on "Opção 1" - "Assistir" to open the player page. The player page says "Click on an ad to see the video."

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://github.com/uBlockOrigin/uAssets/assets/135860000/fa679782-97f3-4720-9d8f-65ca5e36a466)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 173836
 cosmetic: 168808
 scriptlet: 43873
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-cookies: 27994-31, 1m
  adguard-generic: 79278-481, 1m
  adguard-mobile-app-banners: 4725-10, 1m
  adguard-other-annoyances: 13734-8, 1m
  adguard-popup-overlays: 25037-73, 1m
  adguard-social: 21991-925, 1m
  adguard-spyware: 62678-1376, now
  adguard-spyware-url: 1303-5, now
  adguard-widgets: 2338-5, now
  block-lan: 54-0, now
  spa-1: 5696-77, now
  ublock-annoyances: 5740-188, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 72402-1290, now
  easyprivacy: 32844-16563, now
  ublock-badware: 7420-325, now
  ublock-filters: 35147-4253, now
  ublock-privacy: 651-177, now
  ublock-quick-fixes: 235-182, now
  ublock-unbreak: 2132-146, now
  urlhaus-1: 11500-0, now
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2004 ms (selfie)
 maxAssetCacheWait: 1208 ms
popupPanel:
 blocked: 0
 extended:
  ##a[href^="whatsapp://send"]
  ##.dt_social_single
```
</details>

**Comment by D4niloMR** [comment]
Add:
```adb
dicasfinanceirasbr.com##+js(no-fetch-if, googlesyndication.com)
dicasfinanceirasbr.com##+js(set-cookie, visited, yes)
dicasfinanceirasbr.com##+js(nano-stb, PL4YER, *, 0.001)
```

But i think it's better to report to Adguard, they eventually will fix in the regional list and there will be duplicate filters. Except when the anti-adblock is fixed on the Adguard-base list.

**Comment by D4niloMR** [comment]
Ok, to `dicasvalor.net` add:

```adb
dicasdevalor.net##+js(rmnt, script, AdblockDetector)
dicasdevalor.net##+js(rpnt, script, time_unblock_click = '5', time_unblock_click = '0')
```

**Comment by D4niloMR** [comment]
@TatianaPink I reported some of these sites not much time ago.

> Could you start submitting pull requests to AdGuard?

Idk if they will accept. But if you send the report to Adguard, just mention me there and I will try to find a solution.

**Comment by D4niloMR** [comment]
Or just `dicasdefinancas.net###player:style(display: block !important;)` and the `no-fetch-if` 
```adb
dicasdefinancas.net##+js(no-fetch-if, googlesyndication.com)
dicasdefinancas.net##+js(set-cookie, visited, yes)
dicasdefinancas.net##+js(rpnt, script, time_unblock_click = '3', time_unblock_click = '0')
```

With default uBO I'm not detected.

```adb
dicasvalores.com##.content-box:style(display: block !important;)
```

However, this site `olhonaviagem.com` seems too much complicated to me.

**Comment by stephenhawk8054** [comment]
@Yuki2718 For Adguard Portugese?

**Comment by D4niloMR** [comment]
@stephenhawk8054 `nano-stb`/`nano-sib` works in all cases above

**Comment by mapx-** [comment]
I get `dicasfinanceirasbr.com` too

@D4niloMR could you prepare a PR ? better without `rpnt`

**Comment by D4niloMR** [comment]
> @D4niloMR In case you want to help them fix these faster:

I guess that is not necessary, you gave them a reference mentioning these issues here
