### ISSUE TITLE
freemodapp.com: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#20458]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://freemodapp.com/?lid=JpYcEL&pid=206954&plid=1&vid=230638887`

### Category

detection

### Description

https://gplinks.co/JpYcEL

### Other extensions used

temper monkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium Mobile: 116
filterset (summary):
 network: 110501
 cosmetic: 33112
 scriptlet: 18877
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  IDN-0: 9671-3873, 4m
  adguard-mobile: 8823-45, 4m
  easylist: 72408-16041, 4m
  easyprivacy: 32833-75, 4m
  plowe-0: 3721-1148, 4m
  ublock-badware: 7414-139, 4m
  ublock-filters: 35465-411, 4m
  ublock-privacy: 651-8, 4m
  ublock-quick-fixes: 235-178, 4m
  ublock-unbreak: 2137-36, 4m
  urlhaus-1: 11235-0, 4m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2074 ms (selfie)
 maxAssetCacheWait: 402 ms
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 2
```
</details>

**Comment by BlazeFTL** [comment]
PR - https://github.com/uBlockOrigin/uAssets/pull/20456/commits/cdb2bc85de171aef6e8f3f8ae47ebed68e44f7f6

**Comment by smaragdina** [comment]
> PR - [cdb2bc8](https://github.com/uBlockOrigin/uAssets/commit/cdb2bc85de171aef6e8f3f8ae47ebed68e44f7f6)
it's work... thank you bro
