### ISSUE TITLE
online-translator.com: ads

### ISSUE THREAD

**Issue by jambohawk** [uBlockOrigin/uAssets#20465]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.online-translator.com/translation`

### Category

ads

### Description

Ad leftovers on the right side on the page and on the left side of the page near the middle when scrolling down.

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.1b4
Firefox: 121
filterset (summary):
 network: 104561
 cosmetic: 40345
 scriptlet: 18658
 html: 1093
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36010-122, 1m
  ublock-badware: 7429-5, 1m
  ublock-privacy: 651-0, 1m
  ublock-unbreak: 2180-0, 1m
  ublock-quick-fixes: 132-1, 1m
  easylist: 72479-700, 1m
  easyprivacy: 32835-726, 1m
  urlhaus-1: 10925-0, 1m
  plowe-0: 3721-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1526 ms
 maxAssetCacheWait: 8 ms
popupPanel:
 blocked: 9
 network:
  clickiocdn.com: 2
  digitalcaramel.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  googletagservices.com: 1
  protagcdn.com: 1
  yandex.ru: 2
```
</details>

**Comment by FanOfBlockers** [comment]
@ryanbr 
```
online-translator.com###rightAdvBlock
online-translator.com##.mddlAdvBlock
```
