### ISSUE TITLE
ground.news: nuisance

### ISSUE THREAD

**Issue by aaronliu0130** [uBlockOrigin/uAssets#20462]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ground.news/`

### Category

nuisance

### Description

There's a subscription nag on the top (the one with get started) that currently isn't blocked

### Other extensions used

reproduced with none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/11874211/25efef01-c8e8-45e2-8755-33111088f446)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 115
filterset (summary):
 network: 142304
 cosmetic: 136704
 scriptlet: 28021
 html: 1342
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 73831-1138, now
  ublock-annoyances: 5702-13, now
  CHN-0: 25493-151, now
  RUS-0: 40170-134, now
 default:
  user-filters: 2-0, never
  ublock-filters: 36006-171, now
  ublock-badware: 7429-5, now
  ublock-privacy: 651-0, now
  ublock-unbreak: 2180-0, now
  ublock-quick-fixes: 231-45, 30m
  easylist: 72479-739, now
  easyprivacy: 32835-726, now
  urlhaus-1: 10925-0, now
  plowe-0: 3721-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 560 ms (selfie)
 maxAssetCacheWait: 356 ms
popupPanel:
 blocked: 5
 network:
  amplitude.com: 2
  googletagmanager.com: 1
  sentry.io: 2
 extended:
  ###newsroom-blindspot > div.items-center:has(> div.flex button#s…
```
</details>

**Comment by mapx-** [comment]
You could report at easylist repository or adguard repo

However, add

`ground.news##.hideElementSiteWide.sticky`

@ryanbr @Alex-302

**Comment by aaronliu0130** [comment]
I wonder what kind of annoyances can be added into ublock's annoyances list

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets#uassets
