### ISSUE TITLE
pointieststick.com: nuisance

### ISSUE THREAD

**Issue by jambohawk** [uBlockOrigin/uAssets#20467]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pointieststick.com/`

### Category

nuisance

### Description

Small, but annoying translucent bar that appears when you scroll down the page. The bar appears at the bottom of the browser view-port. This bar will not disappear until you scroll all the way back up to the top of the web page,

See screenshot included.

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![pointieststick](https://github.com/uBlockOrigin/uAssets/assets/149954762/76bc108d-ff97-43d8-9926-7aecc3013460)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.1b4
Firefox: 121
filterset (summary):
 network: 104561
 cosmetic: 40345
 scriptlet: 18658
 html: 1093
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36010-122, 16m
  ublock-badware: 7429-5, 16m
  ublock-privacy: 651-0, 16m
  ublock-unbreak: 2180-0, 16m
  ublock-quick-fixes: 132-1, 16m
  easylist: 72479-700, 16m
  easyprivacy: 32835-726, 16m
  urlhaus-1: 10925-0, 16m
  plowe-0: 3721-1, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1526 ms
 maxAssetCacheWait: 8 ms
popupPanel:
 blocked: 27
 network:
  doubleclick.net: 4
  google.com: 18
  wp.com: 3
  youtube.com: 2
 extended:
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(replace-node-text, script, /(\(function serverContract\(\)…
  ##+js(json-prune, playerResponse.adPlacements adPlacements, , /(…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
you should report it at easylist repository

add
`pointieststick.com###infinite-footer`

@ryanbr

**Comment by mapx-** [comment]
@jambohawk read here: https://github.com/uBlockOrigin/uAssets#uassets

**Comment by gorhill** [comment]
> separate company's repository

Neither uBO nor EasyList are a "company" -- just people spending their free time to make the internet better.

**Comment by gorhill** [comment]
No, we don't control other repo, and we wouldn't know whether a report is really to be fixed by another repo. You have to look into the issue then make a determination. If you do not have the technical know-how to make that determination, then we make it and tell you to report to the other repo, as was done here.
