### ISSUE TITLE
ef.co.id: nuisance

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uAssets#20460]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ef.co.id/englishfirst/kids/blog/perbedaan-english-british-dan-english-american/`

### Category

nuisance

### Description

Cookie consent 

### Other extensions used

Dark reader,google search fixer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-11-05-18-41-12-63_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/98148960/4af81c52-920d-4d72-bb14-19c4ef31dc2a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 118010
 cosmetic: 140409
 scriptlet: 27886
 html: 1273
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 10434-5, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2473-0, now
  adguard-spyware-url: 1303-195, now
  adguard-social: 21991-168, now
  adguard-cookies: 27997-48, 1m
  ublock-cookies-adguard: 522-0, 1m
  adguard-popup-overlays: 25037-963, now
  adguard-mobile-app-banners: 4725-9, now
  adguard-other-annoyances: 13734-88, now
  adguard-widgets: 2338-1, now
  ublock-annoyances: 5763-544, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36341-669, now
  ublock-badware: 7423-5, now
  ublock-privacy: 651-47, now
  ublock-unbreak: 2185-1, now
  ublock-quick-fixes: 231-45, now
  adguard-mobile: 8823-109, now
  easylist: 72410-806, now
  easyprivacy: 32834-737, now
  urlhaus-1: 11235-0, now
  plowe-0: 3721-1, now
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 748 ms (selfie)
 maxAssetCacheWait: 308 ms
popupPanel:
 blocked: 3
 network:
  addthis.com: 2
  googletagmanager.com: 1
 extended:
  ##.addthis_inline_share_toolbox
```
</details>

**Comment by mapx-** [comment]
add

`ef.co.id##footer + [class^="css-"] > .ef-container`

@ryanbr

**Comment by mapx-** [comment]
@ChowMein47 you are using adguard lists, you could report directly at [their repository](https://github.com/AdguardTeam/AdguardFilters/issues)
