### ISSUE TITLE
newsweek.com: ads

### ISSUE THREAD

**Issue by freedomspiritJohn** [uBlockOrigin/uAssets#20461]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.newsweek.com/neuroscientists-reveal-snacks-boost-memory-1840796`

### Category

ads

### Description

Placeholder with a white background containing residual advertisements.

### Other extensions used

too many

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/129288685/493577a0-6660-489d-a78b-59e8405e764c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 102
filterset (summary):
 network: 138022
 cosmetic: 72315
 scriptlet: 35054
 html: 0
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/xinggsf/Adblock-Plus-Rule@master/mv.txt: 212-0, now
  https://gitee.com/halflife/list/raw/master/ad.txt: 0-0, never
  adguard-generic: 79282-752, now
 default:
  user-filters: 0-0, never
  CHN-0: 25492-1292, now
  easylist: 72410-17080, now
  easyprivacy: 32834-175, now
  plowe-0: 3721-1089, now
  ublock-badware: 7420-325, 1h.32m
  ublock-filters: 35143-4059, 1h.31m
  ublock-privacy: 651-9, now
  ublock-quick-fixes: 235-178, now
  ublock-unbreak: 2131-94, 1h.30m
  urlhaus-1: 11235-0, now
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 815 ms (selfie)
 maxAssetCacheWait: 115 ms
popupPanel:
 blocked: 35
 network:
  newsweek.com: 3
  6sc.co: 1
  abtasty.com: 1
  adswizz.com: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  doubleverify.com: 1
  flipboard.com: 1
  fqtag.com: 2
  google.com: 3
  googletagmanager.com: 1
  liadm.com: 1
  outbrain.com: 1
  p7cloud.net: 1
  permutive.app: 1
  sail-horizon.com: 1
  script.ac: 1
  spot.im: 9
  streamtheworld.com: 1
  trinitymedia.ai: 3
 extended:
  ###recommended
  ##.block-ibtmedia-dfp
```
</details>

**Comment by mapx-** [comment]
> ignoreGenericCosmeticFilters: true

unselect `Ignore generic cosmetic filters`
