### ISSUE TITLE
newzjunky.com: detection

### ISSUE THREAD

**Issue by wb13646** [uBlockOrigin/uAssets#20464]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

`https://www.newzjunky.com`    

Popup for Ad block detected.  Causes window scroll issue - cannot scroll window

https://github.com/uBlockOrigin/uBlock-issues/assets/149949726/3ac24d1a-81c3-40ea-9304-97b54d340177

### A specific URL where the issue occurs.

`https://www.newzjunky.com`

### Steps to Reproduce

open url
try to add popup element to ublock 
window scroll disabled.

### Expected behavior

block freaking popup without changing window behavior

### Actual behavior

scroll disabled

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105088
 cosmetic: 40331
 scriptlet: 18804
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72367-15, 16h.6m
  easyprivacy: 32844-64, 16h.6m
  plowe-0: 3720-1073, 16h.5m
  ublock-badware: 7420-138, 16h.5m
  ublock-filters: 35153-146, 16h.5m
  ublock-privacy: 651-7, 16h.5m
  ublock-quick-fixes: 235-174, 1h.48m
  ublock-unbreak: 2131-32, 16h.5m
  urlhaus-1: 11500-0, 16h.5m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1006 ms (selfie)
 maxAssetCacheWait: 179 ms
```
</details>

**Comment by mapx-** [comment]
it's considered soft if does not (re)appear refreshing the page
