### ISSUE TITLE
megaup.net: ads

### ISSUE THREAD

**Issue by usernamaewa** [uBlockOrigin/uAssets#20476]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://megaup.net/1Z7hv/STAROCN-TSSTRY-(USA)-NSwTcH-[BASE]-XCI-Ziperto.part2.rar`

### Category

ads

### Description

Has one leftover ad.

### Other extensions used

_none_

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (811)](https://github.com/uBlockOrigin/uAssets/assets/11241668/4da156c1-8952-4d1e-a937-e94886e81a38)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.1b1
Firefox: 121
filterset (summary):
 network: 352809
 cosmetic: 361489
 scriptlet: 51233
 html: 1420
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79288-7891, 30m
  adguard-mobile: 8823-104, 30m
  adguard-spyware-url: 1303-88, 30m
  adguard-spyware: 62679-17198, 30m
  block-lan: 54-0, 30m
  curben-phishing: 76832-34, 30m
  adguard-social: 21991-870, 30m
  adguard-cookies: 27997-103, 30m
  ublock-cookies-adguard: 484-0, 30m
  adguard-popup-overlays: 25037-1589, 30m
  adguard-mobile-app-banners: 4725-1069, 30m
  adguard-other-annoyances: 13734-315, 30m
  [47 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36017-725, 30m
  ublock-badware: 7434-5, 30m
  ublock-privacy: 651-0, 30m
  ublock-unbreak: 2179-0, 30m
  ublock-quick-fixes: 132-1, 30m
  easylist: 72484-1399, 30m
  easyprivacy: 32836-1056, 30m
  urlhaus-1: 10925-0, 30m
  plowe-0: 3721-1, 31m
filterset (user): [empty]
hostRuleset:
 added: [array of 66 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1120 ms (selfie)
 maxAssetCacheWait: 626 ms
popupPanel:
 blocked: 13
 network:
  megaup.net: 5
  a-ads.com: 1
  altowriestwispy.com: 1
  bidgear.com: 2
  dmmzkfd82wayn.cloudfront.net: 2
  googletagmanager.com: 1
  keydawnawe.com: 1
 extended:
  ##.socialsider
  ##body .metaRedirectWrapperBottomAds:style(visibility: hidden !i…
  ##body:style(overflow-x: hidden !important;)
  ##.metaRedirectWrapperBottomAds img:style(width: 300px !importan…
  ##.metaRedirectWrapperBottomAds a > img:style(visibility: visibl…
  ##.imgAds:style(height: 250px !important;)
  ##.imgAds > img:style(height: 250px !important;)
  ##.metaRedirectWrapperBottomAds > *:style(pointer-events: none !…
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(replace-node-text, script, /\$\(_\S+?\):/)
  ##+js(abort-current-script, I833)
  ##+js(abort-on-property-write, Fingerprint2)
```
</details>

**Comment by gorhill** [comment]
You are using too many lists and custom filters/rules, you will have to investigate on your side what is causing this.

Reminder that we do ask:

> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> - [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

**Comment by stephenhawk8054** [comment]
Likely due to this filter somewhere in the additional lists

```adb
##.metaRedirectWrapperBottomAds a > img:style(visibility: visibl…
```

**Comment by mapx-** [comment]
> [47 lists not shown]: [too many]

reset uBO to default settings / lists
