### ISSUE TITLE
psypost.org: ads

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#20474]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.psypost.org/2023/11/womens-sexual-unrestrictedness-tied-to-economic-empowerment-and-reduced-parenting-demands-214350`

### Category

ads (social buttons)

### Description

I have enabled EasyList - Social Widgets and AdGuard - Social Media list, but still the social media sharing buttons are visible. How to hide them?

### Other extensions used

none

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19490515/daa8ef4d-a43d-4990-bbb6-8942c8b91930)

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 210971
 cosmetic: 171516
 scriptlet: 42396
 html: 1285
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2478-0, now
  adguard-generic: 79288-5856, 4m
  adguard-spyware-url: 1303-195, 4m
  block-lan: 54-0, now
  curben-phishing: 76832-32, now
  fanboy-thirdparty_social: 69-0, now
  fanboy-cookiemonster: 48819-301, now
  fanboy-social: 16165-20, now
  ublock-annoyances: 5708-22, now
  NOR-0: 3653-10, now
  adguard-popup-overlays: 25037-671, 4m
  easylist-chat: 148-0, now
  [2 lists not shown]: [too many]
 default:
  user-filters: 16-0, never
  ublock-filters: 36014-197, now
  ublock-badware: 7434-5, now
  ublock-privacy: 651-47, now
  ublock-unbreak: 2179-1, now
  ublock-quick-fixes: 132-1, now
  easylist: 72481-752, now
  easyprivacy: 32836-806, now
  urlhaus-1: 10925-0, now
  plowe-0: 3721-1, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2137 ms (selfie)
 maxAssetCacheWait: 473 ms
popupPanel:
 blocked: 12
 network:
  google-analytics.com: 2
  googlesyndication.com: 5
  googletagmanager.com: 1
  onesignal.com: 2
  outbrain.com: 1
  solutionshindsight.net: 1
 extended:
  ##.jeg_midbar
```
</details>

**Comment by gorhill** [comment]
There are no social buttons when I enable only _"EasyList – Social Widgets"_. You have to many lists enabled, it's best that you narrow down on your side which lists is interfering negatively with _"EasyList – Social Widgets"_

**Comment by gorhill** [comment]
You can bypass the AdGuard filter with:

    ||psypost.org^$ghide,important

Not sure where the fix should be made.

**Comment by stephenhawk8054** [comment]
@Yuki2718 It's in Base?
