### ISSUE TITLE
deezer.com: detection

### ISSUE THREAD

**Issue by KaZantip0** [uBlockOrigin/uAssets#20471]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hello,

When I play music on Deezer I get a popup asking me to deactivate adblock. When I disable ublock origin no problem

https://github.com/uBlockOrigin/uBlock-issues/assets/38734767/03183847-7572-4c0c-aad1-71e76c4c5dfb

### A specific URL where the issue occurs.

`https://www.deezer.com/fr/`

### Steps to Reproduce

Login into free account.
Start a song from specific playlist or "flow"
A popup appear "Adblock detected, please disabled it to use deezer"

### Expected behavior

Music play

### Actual behavior

Popup appear and the music don't play

### Configuration

Windows 10
Firefox 119.0 (64 bits)
uBlock Origin 1.53.0

**Comment by mapx-** [comment]
follow all these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
