### ISSUE TITLE
brokensilenze.net: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20473]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.brokensilenze.net/2023/11/04/love-marriage-huntsville-season-6-episode-23-holt-her-accountable/`

### Category

detection

### Description

The site detects uBO. It also blocks right clicks, selecting, and copying.

These filters seem to fix the detection and annoyances.
```
brokensilenze.net##+js(noeval-if, /chp_?ad/)
brokensilenze.net##+js(aopw, document.oncontextmenu)
brokensilenze.net##+js(aopw, document.ondragstart)
brokensilenze.net##+js(set, disable_copy, noopFunc)
brokensilenze.net##+js(set, disable_copy_ie, noopFunc)
brokensilenze.net##.unselectable:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
```

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screen Shot 2023-11-05 at 3 55 54 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/a4571cc1-6605-45b7-ab04-e73a874bfb79">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104883
 cosmetic: 41873
 scriptlet: 22789
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5749-9, now
 default:
  user-filters: 42-2, never
  easylist: 72481-15, now
  easyprivacy: 32836-64, now
  plowe-0: 3721-1073, now
  ublock-badware: 7430-138, now
  ublock-filters: 35135-146, now
  ublock-privacy: 651-7, now
  ublock-quick-fixes: 235-158, 14m
  ublock-unbreak: 2133-32, now
  urlhaus-1: 10925-0, now
filterset (user): [array of 40 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 195 ms (selfie)
 maxAssetCacheWait: 74 ms
popupPanel:
 blocked: 17
 network:
  adnxs.com: 1
  agkn.com: 1
  disqus.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  lijit.com: 1
  mgid.com: 3
  narrative.io: 2
  onesignal.com: 1
  pippio.com: 1
  rezync.com: 1
  vlitag.com: 1
  wp.com: 1
 extended:
  ##.adsbyvli
  ##.floatads
  ##div[id*="ScriptRoot"]
  ##.adtable
  ##.ad_banner
  ##.article-advert
  ##.ad-336x280
  ##.adtech
  ##.ad_heading
  ##.tile_ad
  ##.inline_ads
  ##.googleafc
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by astolfoismywaifu** [comment]
```brokensilenze.net##+js(rmnt, script, disable_copy)``` seems to fix all annoyances

**Comment by huyszn** [comment]
The filter `brokensilenze.net##.unselectable:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)` makes the text on the  `brokensilenze.net` homepage selectable.

**Comment by gorhill** [comment]
@astolfoismywaifu's filter is much simpler, it's the one which was added to _"uBlock filters -- Annoyances"_

**Comment by huyszn** [comment]
I mean the text on the home page (https://github.com/uBlockOrigin/uAssets/assets/46979193/71970f02-3f98-42fe-815a-ba86d1b1e465). I can select text on each individual post just fine, but on the main page in the screenshot and some other pages like `brokensilenze.net/category/news/`, the text is unsetectable.

**Comment by gorhill** [comment]
brokensilenze.net##*:style(cursor:auto!important;user-select:unset!important)

**Comment by playonevideo** [comment]
On `https://www.brokensilenze.net/2026/04/25/belle-collective-birmingham-season-1-episode-3-the-live-before-the-storm/` if you click on the link I highlighted, it tries to open a popunder:

<img width="942" height="217" alt="Image" src="https://github.com/user-attachments/assets/88771ca3-299e-4a32-8ffb-897ce9f5e7ce" />
<img width="909" height="651" alt="Image" src="https://github.com/user-attachments/assets/2d681a5a-57fb-4e8a-a3a0-1be1c1eb3413" />
