### ISSUE TITLE
aurapol.com: nuisance

### ISSUE THREAD

**Issue by Renohedron** [uBlockOrigin/uAssets#20478]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aurapol.com/`

### Category

nuisance

### Description

There's invisible overlay blocking all scrolling.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 115157
 cosmetic: 191472
 scriptlet: 29863
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 73831-111, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94589-21775, now
  CZE-0: 798-1, now
  adguard-social: 21991-1613, 1h.10m
  fanboy-cookiemonster: 48830-48830, now
  fanboy-social: 16178-16178, now
  fanboy-thirdparty_social: 68-18, now
  ublock-annoyances: 5749-213, now
 default:
  user-filters: 16-0, never
  easylist: 72484-105, now
  easyprivacy: 32836-278, now
  plowe-0: 3721-1074, now
  ublock-badware: 7430-138, now
  ublock-filters: 35135-503, now
  ublock-privacy: 651-9, now
  ublock-quick-fixes: 143-88, now
  ublock-unbreak: 2134-36, 1h.11m
  urlhaus-1: 11030-0, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 314 ms (selfie)
 maxAssetCacheWait: 190 ms
popupPanel:
 blocked: 6
 network:
  facebook.net: 1
  google.com: 1
  googletagmanager.com: 2
  hotjar.com: 1
  seznam.cz: 1
 extended:
  ##.scroll-to-top.btn
  ###cookiesDialog
  ##.show.fade.modal-backdrop
  ##a[href*="pinterest.com/pin/create/button"]
```
</details>

**Comment by gorhill** [comment]
Need the following filters in Easylist Cookies:

    aurapol.com##.show.modal-backdrop
    aurapol.com##.modal-open:style(overflow:auto!important)

@ryanbr
