### ISSUE TITLE
animedekho.com: popups

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#20475]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://animedekho.com/episode/detective-conan-1x84/`

### Category

popups

### Description

Popup

### Other extensions used

Violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 105972
 cosmetic: 31625
 scriptlet: 18719
 html: 1094
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36330-371, now
  ublock-badware: 7428-5, now
  ublock-privacy: 651-1, now
  ublock-unbreak: 2184-1, now
  ublock-quick-fixes: 132-1, 1h.40m
  adguard-mobile: 8823-127, now
  easylist: 72484-16713, now
  easyprivacy: 32836-734, now
  urlhaus-1: 10925-0, 1h.41m
  plowe-0: 3721-1, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 19431 ms (selfie)
 maxAssetCacheWait: 853 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
```
</details>

**Comment by gorhill** [comment]
Can't navigate to the site, I get:

> Sorry, you have been blocked

**Comment by BlazeFTL** [comment]
Its A Indian Site

**Comment by mapx-** [comment]
yes, indian ip, skip ads, then tons of dumb shorteners, the video itself, no popups
