### ISSUE TITLE
autosport.com: detection

### ISSUE THREAD

**Issue by weirdworkshop** [uBlockOrigin/uAssets#20479]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.autosport.com/f1/news/hamilton-suspects-mercedes-f1-cars-floor-not-working-in-brazilian-gp/10543430/`

### Category

detection

### Description

Content not displayed. Replaced by message instructing to disable adblocker

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104672
 cosmetic: 40352
 scriptlet: 18659
 html: 1093
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36014-121, now
  ublock-badware: 7434-5, now
  ublock-privacy: 651-0, now
  ublock-unbreak: 2179-0, now
  ublock-quick-fixes: 132-1, now
  easylist: 72484-700, now
  easyprivacy: 32836-726, now
  urlhaus-1: 11030-0, now
  plowe-0: 3721-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 45 ms
popupPanel:
 blocked: 8
 network:
  autosport.com: 2
  doubleclick.net: 1
  motorsport.com: 2
  motorsportnetwork.com: 1
  ntv.io: 1
  outbrain.com: 1
 extended:
  ##.ms-apb
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
  ##+js(addEventListener-defuser, gtmloaderror)
  ##+js(noeval-if, interactionCount)
  ##+js(abort-current-script, vardom)
  ##+js(cookie-remover, 45grw1567)
  ##+js(set-cookie, 4d8L2108, 1, , reload, 1)
  ##+js(noeval-if, /chp_?ad/)
```
</details>

**Comment by gorhill** [comment]
I can't reproduce, I have the same scriptlet being injected, and especially `##+js(noeval-if, /chp_?ad/)` is the one which should defuse the anti-blocker. I have `googletagmanager.com` blocked 12 times on my side while this is not showing up on your side.

**Comment by mapx-** [comment]
@weirdworkshop 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
