### ISSUE TITLE
720pstream.nu: popups

### ISSUE THREAD

**Issue by ThatAnonymousGuy1** [uBlockOrigin/uAssets#20481]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://720pstream.nu/nhl/live-anaheim-ducks-stream`

### Category

nuisance

### Description

From time to time there is an overlay on the page. Maybe after every 3rd or 4th refresh. It will open a new tab and redirect to another site. I was able to catch a redirect for "||dweatherbe.org^". It's on my list to block, but the nuisance is on the page. 

I have been purging and updating my block lists. It does not solve the dilemma.

This applies to any stream page in the NHL section.

### Other extensions used

Dark Reader. Picture In Picture

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-11-05 220914](https://github.com/uBlockOrigin/uAssets/assets/37353659/cd0c8da6-2285-4a1d-a10b-2c86e9f0151f)

![Screenshot 2023-11-05 220921](https://github.com/uBlockOrigin/uAssets/assets/37353659/ccb42fc4-b412-4121-8680-5255d198bc1b)

![Screenshot 2023-11-05 220956](https://github.com/uBlockOrigin/uAssets/assets/37353659/d3e512b7-6323-4b19-bbb7-a4320cdb70e0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 104288
 cosmetic: 40386
 scriptlet: 18818
 html: 0
listset (total-discarded, last-updated):
 added:
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, now
 default:
  user-filters: 47-0, never
  easylist: 72076-16, now
  easyprivacy: 32836-64, now
  plowe-0: 3721-1073, now
  ublock-badware: 7430-135, now
  ublock-filters: 35136-152, now
  ublock-privacy: 651-7, now
  ublock-quick-fixes: 143-84, 1h.3m
  ublock-unbreak: 2133-31, now
  urlhaus-1: 11030-0, 1h.4m
filterset (user): [array of 48 redacted]
trustedset:
 added: [array of 42 redacted]
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 61 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 258 ms (selfie)
 maxAssetCacheWait: 93 ms
popupPanel:
 blocked: 4
 network:
  acacdn.com: 1
  jsdelivr.net: 1
  tabbingtremors.life: 1
  xhwwcif.com: 1
 extended:
  ##div.text-center.col-12:nth-of-type(1)
  ##.text-left.row.col-12
  ##div.text-center.col-12:nth-of-type(6)
  ##.text-center.text-warning.col-12
  ##.bg-dark.position-absolute
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(no-window-open-if)
  ##+js(no-setTimeout-if, admc)
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(abort-on-property-write, _pop)
  ##+js(nowebrtc)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(abort-current-script, JSON, break;case)
  ##+js(no-setTimeout-if, (), 150)
```
</details>

**Comment by D4niloMR** [comment]
Try: 

```
niaomea.me##+js(nowoif)
||dweatherbe.org^$popup
```
I can reproduce and the same filter works for https://github.com/uBlockOrigin/uAssets/issues/20472
