### ISSUE TITLE
gplinks.co: detection

### ISSUE THREAD

**Issue by Insomnicc** [uBlockOrigin/uAssets#20489]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gplinks.co/4XVRyNBOows9/?pid=864144&vid=231370641`

### Category

detection

### Description

Its detecting UBo,I dont use any other extensions and it was working perfectly this morning

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://prnt.sc/1K-a_gd4Tpvt

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104285
 cosmetic: 40368
 scriptlet: 18671
 html: 1095
listset (total-discarded, last-updated):
 default:
  user-filters: 60-1, never
  ublock-filters: 36021-137, 12h.2m
  ublock-badware: 7434-5, 12h.2m
  ublock-privacy: 651-0, 12h.2m
  ublock-unbreak: 2179-0, 12h.2m
  ublock-quick-fixes: 132-1, 2m
  easylist: 72076-699, 12h.2m
  easyprivacy: 32836-726, 12h.2m
  urlhaus-1: 11030-0, 12h.2m
  plowe-0: 3721-1, 12h.2m
filterset (user): [array of 46 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 403 ms (selfie)
 maxAssetCacheWait: 154 ms
popupPanel:
 blocked: 6
 network:
  googletagmanager.com: 2
  gplinks.in: 1
  tawk.to: 1
  teemooge.net: 1
  trustpilot.com: 1
 extended:
  ##.bg-soft-primary, a.exclude-pop.smartlink, .exclude-pop.quiz-c…
  ##+js(set-constant, blurred, false)
  ##+js(abort-on-property-read, clickCount)
  ##+js(abort-current-script, String.fromCharCode, /btoa|break/)
```
</details>

**Comment by BlazeFTL** [comment]
@Insomnicc Wait 3 Seconds In Every Page...Until That Please Wait 15 Second Text Disappears
