### ISSUE TITLE
Adblock notification pop up appears

### ISSUE THREAD

**Issue by radenwahid** [uBlockOrigin/uAssets#20497]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://www.youtube.com/watch?v=vjrqiR7UuFI&t=1s
https://www.youtube.com/

### Description

Adblock notification pop up appears

### Other extensions used

Adblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Annotation 2023-11-07 062727](https://github.com/uBlockOrigin/uAssets/assets/61126583/237cca4f-d14a-461a-ba2c-9afd43d54aea)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 108869
 cosmetic: 45688
 scriptlet: 18852
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  IDN-0: 9671-3, 2d.13h.5m
  easylist: 72372-24, 2d.13h.5m
  easyprivacy: 32844-66, 2d.13h.5m
  plowe-0: 3720-1073, 2d.13h.5m
  ublock-badware: 7415-138, 2d.13h.5m
  ublock-filters: 35155-165, 2d.13h.5m
  ublock-privacy: 643-7, 2d.13h.5m
  ublock-quick-fixes: 143-57, 9h.44m
  ublock-unbreak: 2131-33, 2d.13h.5m
  urlhaus-1: 11030-0, 11h.45m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 373 ms (selfie)
 maxAssetCacheWait: 131 ms
```
</details>

**Comment by astolfoismywaifu** [comment]
> * [x]  I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
> * [x]  I did not answer truthfully to **ALL** the above checkpoints.

> * [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.
> ### Other extensions used
> Adblock

😐 Report yt issues here: https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
