### ISSUE TITLE
pedestrianobservations.com: breakage

### ISSUE THREAD

**Issue by c933103** [uBlockOrigin/uAssets#20498]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pedestrianobservations.com/2023/11/02/we-gave-a-talk-about-new-york-commuter-rail-modernization/`

### Category

breakage

### Description

The website, being a wordpress site, have a new post/reply notification for logged in users.
That notification cannot open normally with uBO enabled.

Note: despite I am submitting the issue via Firefox Mobile, the same situation also happen on other platforms like Chrome Desktop

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231107-075331](https://github.com/uBlockOrigin/uAssets/assets/1525293/6a15eec2-a790-489d-a72b-0b44fed1dce0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 120378
 cosmetic: 40832
 scriptlet: 18894
 html: 1095
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36352-371, 12m
  ublock-badware: 7428-5, 12m
  ublock-privacy: 651-1, 12m
  ublock-unbreak: 2184-1, 12m
  ublock-quick-fixes: 130-1, 12m
  adguard-mobile: 8824-127, 12m
  easylist: 72077-16723, 12m
  easyprivacy: 32837-734, 11m
  urlhaus-1: 10940-0, 11m
  plowe-0: 3721-1, 11m
  CHN-0: 25503-1331, 12m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 403 ms
 maxAssetCacheWait: 173 ms
popupPanel:
 blocked: 11
 network:
  wp.com: 11
```
</details>

**Comment by mapx-** [comment]
I tried a reply (now awaiting moderation) using a wordpress account, what exactly should I note ?!

**Comment by c933103** [comment]
> I tried a reply (now awaiting moderation) using a wordpress account, what exactly should I note ?!

Click the bell button on top to expand the panel. If any WordPress site or comment chain you follow have update or new comment, then there should be some notifications. But after enabling uBO it only show loading circle.

**Comment by mapx-** [comment]
tested in chrome, no issue on my end, I can see all the (old) notifications

looking in the logger, only these requests are blocked:

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/e3092c46-b43d-4204-9c9b-a3835dff4722)
