### ISSUE TITLE
nba.com: ads

### ISSUE THREAD

**Issue by adamaliens** [uBlockOrigin/uAssets#20499]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.nba.com/game/gsw-vs-det-0022300145%3Fwatch?watchLive=true`

### Category

ads

### Description

Ads are showing in the player on NBA,com *when you use League Pass or watch games.  Thank you.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 105850
 cosmetic: 43370
 scriptlet: 18671
 html: 1094
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36039-128, now
  ublock-badware: 7434-5, now
  ublock-privacy: 652-0, now
  ublock-unbreak: 2179-0, now
  ublock-quick-fixes: 137-1, 14m
  easylist: 75112-700, now
  easyprivacy: 32837-726, now
  urlhaus-1: 12585-0, now
  plowe-0: 3721-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 352 ms (selfie)
 maxAssetCacheWait: 119 ms
popupPanel:
 blocked: 32
 network:
  nba.com: 1
  adobedtm.com: 18
  amazon-adsystem.com: 1
  amplitude.com: 1
  bitmovin.com: 2
  d1z2jf7jlzjs58.cloudfront.net: 1
  doubleclick.net: 4
  newrelic.com: 1
  parsely.com: 1
  summerhamster.com: 1
  ugdturner.com: 1
 extended:
  ##div[class^="DisplayAd_"]
```
</details>

**Comment by stephenhawk8054** [comment]
It needs an account? Do you know any free links that have the same issue?

**Comment by okiehsch** [comment]
I don't see any ads watching game recaps and condensed games or full games need an account.
