### ISSUE TITLE
aniwatch.to: nuisance

### ISSUE THREAD

**Issue by MinePossu** [uBlockOrigin/uAssets#20492]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aniwatch.to/watch/chainsaw-man-17406?ep=94597`

### Category

nuisance

### Description

This site media player on mobile breaks captions in full screen. Also has a pretty nasty habit of redirecting to the homepage. trips breakpoint and clears console

### Other extensions used

Return youtube dislikes

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/27795331/af52dcc3-7eec-4bf0-8442-a41e06fc96df)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 116
filterset (summary):
 network: 115034
 cosmetic: 193035
 scriptlet: 29411
 html: 1290
listset (total-discarded, last-updated):
 added:
  adguard-social: 21994-858, 18m
  adguard-cookies: 28000-64, 18m
  adguard-popup-overlays: 25046-1539, 18m
  adguard-mobile-app-banners: 4726-1069, 18m
  adguard-other-annoyances: 13746-311, 18m
  adguard-widgets: 2340-1, 18m
  easylist-annoyances: 4163-116, 17m
  easylist-chat: 148-11, 19m
  fanboy-cookiemonster: 48834-3895, 17m
  easylist-newsletters: 6621-13, 17m
  easylist-notifications: 2865-4, 17m
  fanboy-social: 16178-12, 18m
  [2 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  ublock-filters: 36027-445, 18m
  ublock-badware: 7434-5, 18m
  ublock-privacy: 652-0, 17m
  ublock-unbreak: 2179-0, 18m
  ublock-quick-fixes: 130-1, 17m
  easylist: 72410-789, 18m
  easyprivacy: 32837-821, 18m
  urlhaus-1: 10940-0, 17m
  plowe-0: 3721-1, 18m
filterset (user): [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6038 ms (selfie)
 maxAssetCacheWait: 355 ms
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 2
  jwpltx.com: 1
  sharethis.com: 2
 extended:
  ##.share-buttons
  ##.share-icon
  ##.sharethis-inline-share-buttons
  ##.grecaptcha-badge
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
```
</details>

**Comment by MinePossu** [comment]
*throws home if devtools opened on firefox

**Comment by D4niloMR** [comment]
Add:
`aniwatch.to,megacloud.tv##+js(set, devtoolsDetector.launch, noopFunc)`

**Comment by MinePossu** [comment]
It's not immediate. Captions dissapear after 5 seconds without user interaction.

**Comment by D4niloMR** [comment]
> It's not immediate. Captions dissapear after 5 seconds without user interaction.

This only happen with uBlock Origin?

**Comment by AsylumOfMind** [comment]
They are implementing anoying anti-adblock measures. It's not ublock's fault. It's coded into the website's javascript along with switching videos during viewing and sending the user back to the homepage when trying to start new videos.

**Comment by nachat-ayoub** [comment]
> Add to anti-devtools: `aniwatch.to,megacloud.tv##+js(set, devtoolsDetector.launch, noopFunc)`
> 
> > This site media player on mobile breaks captions in full screen.
> 
> I can't reproduce this behavior.

Can explain How ? is anti-devtools an extension or a user-script or what?

**Comment by JobcenterTycoon** [comment]
The issue got fixed in the `uBlock filters – Annoyances` filterlist which can be enabled in the filterlist panel.

`aniwatch.to,megacloud.tv##+js(set, devtoolsDetector.launch, noopFunc)` is a filter for uBlock Origin to prevent devtools detection.

**Comment by nachat-ayoub** [comment]
> The issue got fixed in the `uBlock filters – Annoyances` filterlist which can be enabled in the filterlist panel. I tested again, still works fine.
> 
> `aniwatch.to,megacloud.tv##+js(set, devtoolsDetector.launch, noopFunc)` is a filter for uBlock Origin to prevent devtools detection.

Hi, i am having a different problem here, and i don't want to create a new issue since it mentioned here earlier, the problem is opening devtools in the watch episode page, magecloud iframe is the cause i tested it by deleting the iframe an opening devtools it worked fine but trying the method you mentioned and enabling the ` uBlock filters – Annoyances ` is not working. i did find a userscript an it worked: https://greasyfork.org/en/scripts/484789-anti-disable-devtool, but it would be better if it's integrated in uBlockOrigin

**Comment by JobcenterTycoon** [comment]
Works perfectly for me. @stephenhawk8054 please take a look

**Comment by stephenhawk8054** [comment]
It redirects to `hianime.to` for me, so should be

```adb
aniwatch.to,hianime.to,megacloud.tv##+js(set, devtoolsDetector.launch, noopFunc)
```

?

**Comment by nachat-ayoub** [comment]
thanks, to you all, I am new to using uBlockOrigin so i thought adding the filter was in the "Filter Lists", after figuring out and adding it in the "My Filters" page it works fine now. thanks again!

**Comment by nachat-ayoub** [comment]
Hi, i found out that they changed the domain name so i updated the rule to:
aniwatchtv.to,hianime.to,megacloud.tv##+js(set, devtoolsDetector.launch, noopFunc)

And now it works fin, thanks a lot!

**Comment by JobcenterTycoon** [comment]
Ok added the new domain. https://github.com/uBlockOrigin/uAssets/commit/a45ee667a722044376e887a582e3ba25bb2bd802
