### ISSUE TITLE
YouWatch Anti-Adblock

### ISSUE THREAD

**Issue by Buffmutti** [uBlockOrigin/uAssets#205]
### URL(s) where the issue occurs

`[http://ay8ou8ohth.com/08qj8ieoi934]`

### Describe the issue

Whenever i try to watch a videostream on YouWatch i get a message which tells me that the publisher doesn't allow adblock and that you should disable it and reload the page. The message is a lie and disabling adblock on this page is a bit like russian roulette, because besides the usual ads this site tried several times to install adware on my system (don't dare to disable adblock on this site if you don't have a good firewall/ anti-virus program)

### Screenshot(s)

![youwatch](https://cloud.githubusercontent.com/assets/22818031/20583900/291b6712-b1ee-11e6-867a-1e3e477ccd93.JPG)

### Versions

- Browser/version: Chrome Version 54.0.2840.99 m (64-bit)
- uBlock Origin version: uBlock Origin v1.9.16

### Settings

- Activated these Filters:
uBlock Filters,
uBlock Filters - Badware risks,
uBlock Filters - Privacy,
uBlock Filters - Unbreak,
EasyList,
Peter Lowe's Ad Server List,
EasyPrivacy,
Malware Domain List,
Malware domains,
DEU EasyList Germany

Changed nothing else.

### Notes

Many Stream-Hosters use ads and most of the time you can disable adblock to support their sites, but YouWatch is the only one known to me which uses such "aggressive" ads and even attacks on your system. Please be careful if you visit that site.

**Comment by er4a1** [comment]
You can solve with
@@||ay8ou8ohth.com/js/adpop.js$script,first-party

The problem in that youwatch has a lot of domain and you need to allow adpop.js for all

**Comment by Buffmutti** [comment]
Would it be possible to change that filter so that uBO uses it for all domains, no matter what their name is?

**Comment by gorhill** [comment]
This work better (1.9.17rc0+ requried):

    ay8ou8ohth.com##script:inject(abort-on-property-read.js, adsShowPopup1)

Also, be sure to toggle on the [no-popups switch](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups) for that site, I find it launches popups for which there are no filters.

**Comment by er4a1** [comment]
This is another domain of youwatch: ahzahg6ohb.com
