### ISSUE TITLE
sbs.com.au: breakage

### ISSUE THREAD

**Issue by sliceanddice9** [uBlockOrigin/uAssets#20500]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sbs.com.au/ondemand/`

### Category

breakage

### Description

The default built-in **uBlock filters – Ads** succeeds in blocking 100% of the video ads when streaming on: `https://www.sbs.com.au/ondemand/`, however the consequence of the blocked video ads is that the Watch History/Continue Watching function on the website no longer syncs.

Disabling the default built-in **uBlock filters – Ads** & enabling **AdGuard – Ads** makes the Watch History/Continue Watching sync function work perfectly, and the unskippable video ads are bypassed, but the problem is that there are still actual video ads baked into the stream itself.

The video ads via  **AdGuard – Ads**  can be manually skipped using the progress bar and forward seek media button on the web video player itself, but my preference would be for the video ads to be totally eliminated which is what the built-in default **uBlock filters – Ads** achieves.

Can the default built-in **uBlock filters – Ads**  be updated or patched so that the Watch History/Continue Watching sync functionally works when streaming videos on `https://www.sbs.com.au/ondemand/`?

### Other extensions used

Enabled Extensions: 

• Bypass Paywalls (D)
• Reddit Enhancer
• Return YouTube Dislike
• Sponserblock for YouTube - Skip Sponsorships
• Stylus
• Tampermonkey 
• YouTube High Definition 
• YouTube Shorts Block 
   

Disabled Extensions: 

• Dislikes in YouTube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
![image](https://github.com/uBlockOrigin/uAssets/assets/59092472/a6622163-bc4b-4d03-981f-23c76f616d3d)

</details>
The 'Continue Watching' section on the website DOES NOT sync when the  default built-in **uBlock filters – Ads** is enabled. 

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 116237
 cosmetic: 154795
 scriptlet: 42393
 html: 1285
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  urlhaus-1: null
 added:
  adguard-generic: 79344-6147, 6m
  adguard-popup-overlays: 25046-603, 1h.28m
  fanboy-thirdparty_social: 69-0, 1h.28m
  fanboy-cookiemonster: 48834-304, 1h.28m
  ublock-cookies-easylist: 488-0, 1h.28m
  easylist-newsletters: 6621-4, 1h.28m
  ublock-annoyances: 5721-508, 1h.28m
 default:
  ublock-filters: 36039-308, now
  ublock-badware: 7434-5, 1h.28m
  ublock-privacy: 652-0, 1h.28m
  ublock-unbreak: 2179-0, 1h.28m
  ublock-quick-fixes: 136-1, 1h.28m
  easylist: 75112-557, 1h.28m
  easyprivacy: 32842-768, 6m
  plowe-0: 3721-1, 18m
filterset (user): [array of 111 redacted]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1691 ms (selfie)
 maxAssetCacheWait: 1421 ms
popupPanel:
 blocked: 33
 network:
  sbs.com.au: 17
  adnxs.com: 2
  bitmovin.com: 2
  conviva.com: 5
  demdex.net: 1
  doubleclick.net: 1
  googlesyndication.com: 2
  newrelic.com: 2
  tremorhub.com: 1
 extended:
  ##+js(set-constant, adBlockerDetected, false)
  ##+js(m3u-prune, /redirector\.googlevideo\.com\/videoplayback\?[…
  ##+js(no-xhr-if, /redirector\.googlevideo\.com\/videoplayback[\s…
  ##+js(json-prune, ads breaks cuepoints times)
  ##+js(remove-class, ad-controls, .bitmovinplayer-container.ad-co…
```
</details>

**Comment by mapx-** [comment]
- the access is free with an account + australian ip
- however uBO has only this filter `sbs.com.au##+js(no-xhr-if, doubleclick)`
- AG has other filters which could break something ?!

I get no `Watch History/Continue Watching` section

@sliceanddice9 if you whitelist uBO filter, do you get correctly those sections ? (using AG filters too)
`sbs.com.au#@#+js(no-xhr-if, doubleclick)`

**Comment by mapx-** [comment]
add it => `sbs.com.au#@#+js(no-xhr-if, doubleclick)` => already whitelisted

I have an account but I get no such section

**Comment by sliceanddice9** [comment]
> add it => `sbs.com.au#@#+js(no-xhr-if, doubleclick)` => already whitelisted
> 
> I have an account but I get no such section

Oh okay, that's strange because the `Continue Watching` section definitely shows up when I log into my account on: https://www.sbs.com.au/ondemand/ as you can see via the screenshot bellow:

![image](https://github.com/uBlockOrigin/uAssets/assets/59092472/51a1bd38-7dc2-481b-ae82-4f4b95c305c4)

It's just that, as specified, the video content on SBS on Demand that I actually watch _DOES NOT_ sync when  **uBlock filters – Ads** is enabled. The `Continue Watching` section _DOES_ sync when  the default built-in **uBlock filters – Ads** is disabled, but no other filters within uBlock Origin block the video ads quite as effectively as the default built-in **uBlock filters – Ads can.**

**Comment by mapx-** [comment]
Did you test after adding 
`sbs.com.au#@#+js(no-xhr-if, doubleclick)`

and keeping enabled AG filters
?

**Comment by sliceanddice9** [comment]
> Did you test after adding `sbs.com.au#@#+js(no-xhr-if, doubleclick)`
> 
> and keeping enabled AG filters ?

Where and how within uBlock Origin do I add: sbs.com.au#@#+js(no-xhr-if, doubleclick)? I'll try this when I get home.

**Comment by mapx-** [comment]
uBO dashboard, "my filters" tab, add that filter, click "apply changes", test it

**Comment by D4niloMR** [comment]
@mapx- `https://www.reddit.com/r/uBlockOrigin/comments/18jk04r/sbs_on_demand_is_detecting_ublockorigin/`

I can reproduce on FF.

Tomorrow the filter on that post was working, now I need `sbs.com.au##+js(set, adBlockerDetected, undefined)`

**Comment by mapx-** [comment]
yeah, it seems working

**Comment by D4niloMR** [comment]
so i can change to that?

**Comment by mapx-** [comment]
sure, it's your call
