### ISSUE TITLE
nasa.gov: breakage

### ISSUE THREAD

**Issue by AroKol78** [uBlockOrigin/uAssets#20509]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.nasa.gov/nasatv/`
`https://www.nasa.gov/plus/`

### Description

no video - blocked by `||litix.io^` "Peter Lowe’s Ad and tracking server list"
it helped me `@@||src.litix.io/videojs^$script,domain=www.nasa.gov`
(there are also from this "xhr", "beacon" domain (litix.io), but it's probably not necessary)
uBlock-for-firefox-legacy 1.16.4.30

### Other extensions used

--

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by AroKol78** [comment]
shouldn't it be blocked?
`eex-gateway.fr011.ttecfed.com/sites/nasa-gov/production/gateway.min.js` I have this script on `www.nasa.gov`

**Comment by stephenhawk8054** [comment]
What's the issue of the script?

**Comment by AroKol78** [comment]
this script doesn't load completely, so the favicon keeps spinning.
and generally speaking, I suspect tracking or profiling.
