### ISSUE TITLE
zive.cz: detection again

### ISSUE THREAD

**Issue by Aeyesx** [uBlockOrigin/uAssets#20502]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zive.cz/`

### Category

detection

### Description

The crapsite detects ublock again. Tried purge all filters & update, re-enabled ublock - annoyances...

### Other extensions used

SponsorBlock
Return YouTube dislike
DarkMode
DuckDuckGo Essentials

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 106379
 cosmetic: 45223
 scriptlet: 22628
 html: 1286
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5722-15, never
 default:
  user-filters: 0-0, never
  ublock-filters: 36038-121, now
  ublock-badware: 7434-5, now
  ublock-privacy: 653-0, now
  ublock-unbreak: 2179-0, now
  ublock-quick-fixes: 137-1, now
  easylist: 75136-702, now
  easyprivacy: 32843-732, now
  urlhaus-1: 12585-0, now
  plowe-0: 3721-1, now
  CZE-0: 799-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2094 ms
 maxAssetCacheWait: 26 ms
popupPanel:
 blocked: 3
 network:
  cpex.cz: 1
  gemius.pl: 1
  google.com: 1
 extended:
  ##.cnc-ads--rectangle_480_1
  ##div.sky-wrapper
  ##+js(set-constant, window.cpexCMPVersion, 2)
  ##+js(abort-current-script, window.addEventListener, :visible)
  ##+js(addEventListener-defuser, beforeunload, ())
  ##+js(abort-current-script, document.createElement, adbDetect)
  ##+js(cookie-remover, /^_?adb/)
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue in the old thread. We are all notified by new comments. Don't open duplicated issues.
