### ISSUE TITLE
zkk78.com: ads

### ISSUE THREAD

**Issue by naynayeux123** [uBlockOrigin/uAssets#20518]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://www.zkk78.com/type/riman.html`

### Category

ads

### Description

The pop-up ads on this website automatically redirect to other pornographic websites, which is very annoying.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 121335
 cosmetic: 43906
 scriptlet: 18921
 html: 1098
listset (total-discarded, last-updated):
 default:
  user-filters: 18-0, never
  ublock-filters: 36364-397, 2m
  ublock-badware: 7428-5, 2m
  ublock-privacy: 654-1, 2m
  ublock-unbreak: 2185-2, 2m
  ublock-quick-fixes: 143-4, 2m
  adguard-mobile: 8831-127, 2m
  easylist: 75160-16725, 22m
  easyprivacy: 32846-746, 2m
  urlhaus-1: 11855-0, 2m
  plowe-0: 3720-1, 2m
  CHN-0: 25520-1303, 2m
filterset (user): [array of 18 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 320 ms (selfie)
 maxAssetCacheWait: 172 ms
popupPanel:
 blocked: 6
 network:
  baidu.com: 1
  stgowan.com: 4
  xunlei.com: 1
```
</details>

**Comment by Dreamurrrr** [comment]
Someone didn't read.

**Comment by mapx-** [comment]
@cjx82630 do you get such ads/ popups ?

**Comment by cjx82630** [comment]
@mapx- https://github.com/easylist/easylistchina/commit/6b6a0b0b167522e941216485ead35f37b27d520f

**Comment by naynayeux123** [comment]
> @cjx82630 do you get such ads/ popups ?

popups

**Comment by naynayeux123** [comment]
> @cjx82630 do you get such ads/ popups ?

http://www.zkk78.com/dongmanplay/2672-1-1.html


The issue still persists.No matter where you click, it seems to be redirected to another website.

**Comment by naynayeux123** [comment]
> @mapx- [easylist/easylistchina@6b6a0b0](https://github.com/easylist/easylistchina/commit/6b6a0b0b167522e941216485ead35f37b27d520f)


http://www.zkk78.com/dongmanplay/2672-1-1.html


The issue still persists.No matter where you click, it seems to be redirected to another website.

**Comment by mapx-** [comment]
@naynayeux123 no popup here, report directly at https://github.com/cjx82630/cjxlist/issues

**Comment by cjx82630** [comment]
Try these filters

> zkk78.com##+js(abort-current-script,document.write,location.href)
zkk78.com##+js(no-setTimeout-if, location.href)
