### ISSUE TITLE
foxnews.com: nuisance

### ISSUE THREAD

**Issue by AnoyedByAds** [uBlockOrigin/uAssets#20519]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.foxnews.com/politics/youngkin-falls-short-mission-win-total-gop-control-virginia-state-legislature`

### Category

nuisance

### Description

All of Foxnews.com affected. Large empty boxes at the top of every page and some as you go down them. Verified they are ads using an adblocker free browser. 

### Other extensions used

I use Brave normally I think it has built in adblocker.  
I regularly purge and update.  Staring happening about 10PM PST.  
A lot of the things to check off I didn't understand and I guess have to check them all to send report. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 105146
 cosmetic: 43404
 scriptlet: 18855
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 75161-16, now
  easyprivacy: 32846-64, now
  plowe-0: 3720-1073, now
  ublock-badware: 7430-135, now
  ublock-filters: 35162-149, now
  ublock-privacy: 660-6, now
  ublock-quick-fixes: 146-89, now
  ublock-unbreak: 2134-32, now
  urlhaus-1: 11855-0, now
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 377 ms (selfie)
 maxAssetCacheWait: 59 ms
popupPanel:
 blocked: 5
 network:
  foxnews.com: 4
  imasdk.googleapis.com: 1
 extended:
  ##.ad-h-250
  ##.ad-w-970
  ##.ad-w-300
  ##.sticky-ads
  ##.ad
  ##.ad-container
  ##.vendor-unit
  ##[class^="amp-ad-"]
```
</details>

**Comment by mapx-** [comment]
Test

```
foxnews.com##.sticky-pre-header
foxnews.com##.site-header:style(min-height: 90px !important)
```

> some as you go down them

where are placed ? screenshot + link to the page ?

**Comment by DonT54** [comment]
Seeing same thing on Firefox. Main Fox News page is fine but the black box at top appears after clicking on a story.

**Comment by mapx-** [comment]
@DonT54 test the filters above
