### ISSUE TITLE
goodreads.com: ads

### ISSUE THREAD

**Issue by pythonranchers** [uBlockOrigin/uAssets#20510]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.goodreads.com/book/show/32191710-astrophysics-for-people-in-a-hurry`

### Category

ads

### Description

I'm getting a big sponsored ad in the middle of the screen for "Amazon's 4+ star books." It loads a few seconds after the page itself finishes loading. I did not have this problem before recently upgrading to MacOS Monterey 12.7.1, but I'm unsure if that caused the issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1280" alt="Screen Shot 2023-11-07 at 12 39 12 PM" src="https://github.com/uBlockOrigin/uAssets/assets/150176643/b7be969e-2363-48aa-b5d5-c9db86c491b4">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 105658
 cosmetic: 43391
 scriptlet: 18684
 html: 1096
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36040-132, 3m
  ublock-badware: 7434-5, 3m
  ublock-privacy: 654-0, 3m
  ublock-unbreak: 2179-0, 3m
  ublock-quick-fixes: 142-4, 3m
  easylist: 75145-700, 3m
  easyprivacy: 32837-725, 2m
  urlhaus-1: 12395-0, 2m
  plowe-0: 3721-1, 2m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 975 ms (selfie)
 maxAssetCacheWait: 172 ms
popupPanel:
 blocked: 21
 network:
  goodreads.com: 14
  amazon-adsystem.com: 2
  amazon.com: 4
  doubleclick.net: 1
 extended:
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
add

`goodreads.com##.SponsoredProductAdContainer`

@ryanbr

**Comment by pythonranchers** [comment]
Thank you!
