### ISSUE TITLE
qiwi.gg: detection

### ISSUE THREAD

**Issue by SakhJack** [uBlockOrigin/uAssets#20516]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://qiwi.gg/file/1tZb3252-test`

### Description

upon entering any file download page, popup appears asking to disable adblock

### Other extensions used

none (fresh profile)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/10335530/390d9711-fc0c-424b-bb42-150dfcb62088)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 185243
 cosmetic: 43401
 scriptlet: 18701
 html: 1096
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36045-132, 1m
  ublock-badware: 7434-5, 1m
  ublock-privacy: 655-0, 1m
  ublock-unbreak: 2180-2, 1m
  ublock-quick-fixes: 143-4, 1m
  easylist: 75151-700, 1m
  adguard-spyware-url: 1306-87, 1m
  easyprivacy: 32839-725, 1m
  urlhaus-1: 11855-0, 1m
  curben-phishing: 76626-29, 1m
  plowe-0: 3720-1, 1m
  LegitimateURLShortener: 2478-155, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1700 ms
 maxAssetCacheWait: 4 ms
popupPanel:
 blocked: 14
 network:
  adsafeprotected.com: 3
  advertising.com: 2
  d2yeczd6cyyd0z.cloudfront.net: 2
  getclicky.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  hotjar.com: 1
  merequartz.com: 2
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce the anti-adblock but I see the ads though.

**Comment by mapx-** [comment]
alternative

```
*$xhr,3p,domain=qiwi.gg
qiwi.gg#@#+js(rmnt, script, /typeof [a-z]\.cmd\.unshift/, condition, cmd.unshift)
qiwi.gg##+js(nowoif, , 10)
```

**Comment by SakhJack** [comment]
idk if this is relevant but I just noticed that login page `https://qiwi.gg/signin` freezes

<details><summary>Screenshots</summary>

uBO enabled
![image](https://github.com/uBlockOrigin/uAssets/assets/10335530/c22c00f9-c7d4-404e-8362-0806b728a88e)
***
uBO disabled

![image](https://github.com/uBlockOrigin/uAssets/assets/10335530/ed645cbd-26b2-42d0-adff-281790bfb2aa)
</details>

**Comment by mapx-** [comment]
no issue on `signin` page on my end

**Comment by mapx-** [comment]
fixed (cname firefox issue)
