### ISSUE TITLE
blog24.me: nuisance

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#20515]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog24.me/2023/10/09/the-importance-of-healthy-eating-nourishing-your-body-for-optimal-health/`

### Category

nuisance

### Description

`https://v2p.icu/OWsxbyznuv8`

captcha does not appear

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium Mobile: 116
filterset (summary):
 network: 111352
 cosmetic: 36168
 scriptlet: 18934
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 22-0, never
  IDN-0: 9685-3882, 2m
  adguard-mobile: 8831-45, 1m
  easylist: 75151-16046, now
  easyprivacy: 32839-75, now
  plowe-0: 3720-1148, now
  ublock-badware: 7424-136, now
  ublock-filters: 35470-416, now
  ublock-privacy: 661-7, now
  ublock-quick-fixes: 146-89, now
  ublock-unbreak: 2139-36, now
  urlhaus-1: 12395-0, now
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2095 ms (selfie)
 maxAssetCacheWait: 364 ms
popupPanel:
 blocked: 22
 network:
  btc25.org: 1
  cryptocoinsad.com: 2
  d3u598arehftfk.cloudfront.net: 1
  freetrx.fun: 1
  googlesyndication.com: 1
  ltc25.in: 1
  profitsfly.com: 5
  shriftskats.com: 9
  waust.at: 1
 extended:
  ##+js(noeval-if, /chp_?ad/)
  ##+js(addEventListener-defuser, DOMContentLoaded, adsBlocked)
  ##+js(addEventListener-defuser, load, htmls)
  ##+js(no-setTimeout-if, alert)
  ##+js(abort-on-property-read, Swal.fire)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(no-xhr-if, popunder)
  ##+js(abort-current-script, eval, replace)
  ##+js(abort-current-script, addEventListener, google_ad_client)
  ##+js(abort-on-property-write, AdbModel)
  ##+js(addEventListener-defuser, , popMagic)
  ##+js(set-constant, protection, noopFunc)
  ##+js(set-constant, document.hasFocus, trueFunc)
```
</details>

**Comment by BlazeFTL** [comment]
Again Faucet
```
blog24.me##form > [id]:style(display: block !important;)
@@||pagead2.googlesyndication.com^$xhr,domain=blog24.me
blog24.me##.adb-overlay
