### ISSUE TITLE
dev.to: ads

### ISSUE THREAD

**Issue by Murka007** [uBlockOrigin/uAssets#20527]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dev.to/codewithshahan/10-math-concepts-for-every-programmer-31n9`

### Category

ads

### Description

On the dev.to website, advertising banners appear on the side panels as well as between articles. They can be either sponsored or for self-promotion.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/54054900/11428f49-97e2-49ed-b48d-6f5c2e44e22f)
![image](https://github.com/uBlockOrigin/uAssets/assets/54054900/636ccdb0-d5d6-40e1-8c61-6ae62fd8dbe5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 128469
 cosmetic: 148563
 scriptlet: 24807
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/noshorts.txt: 12-0, 32m
  RUS-0: 40095-9, now
  adguard-cookies: 28015-44, now
  adguard-mobile-app-banners: 4731-10, now
  adguard-other-annoyances: 13754-44, now
  adguard-popup-overlays: 25068-416, now
  adguard-social: 22002-933, now
  adguard-widgets: 2340-15, now
  ublock-cookies-adguard: 492-7, now
 default:
  user-filters: 23-2, never
  easylist: 75137-101, now
  easyprivacy: 32851-212, now
  plowe-0: 3720-1078, now
  ublock-badware: 7430-135, now
  ublock-filters: 35184-517, now
  ublock-privacy: 660-8, now
  ublock-quick-fixes: 140-84, now
  ublock-unbreak: 2135-33, now
  urlhaus-1: 11855-0, now
filterset (user): [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1171 ms (selfie)
 maxAssetCacheWait: 216 ms
popupPanel:
 blocked: 5
 no-cosmetic-filtering: true
 network:
  dev.to: 2
  google-analytics.com: 2
  googletagmanager.com: 1
 extended:
  ##.js-billboard-container.break-word.gap-4.grid.crayons-article-…
  ##.js-billboard.billboard.crayons-sponsorship.crayons-card--seco…
  ##.article-wrapper > .crayons-layout__comments-billboard.pb-4
  ###article-show-more-dropdown > web-share-wrapper
  ###article-show-more-dropdown > .Desktop-only > a[target="_blank…
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://news.ycombinator.com/submitlink?"]
  ##a[href^="https://www.reddit.com/submit"]
  ##a[href^="https://www.facebook.com/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle"]
```
</details>

**Comment by mapx-** [comment]
add

`dev.to##.crayons-sponsorship`

@ryanbr

**Comment by robinmetral** [comment]
Hi, I'm seeing these ads using uBlock.

I understand that "It is preferred to fix filter issues in EasyList", which is why I reported it there first: https://github.com/easylist/easylist/issues/21362#issuecomment-2708830108

I was told that this is already fixed in EasyList via `dev.to#?#div[data-display-unit]:-abp-has(span:-abp-contains(Promoted))`. Is it expected that this doesn't work in uBlock? (the block looks ABP-specific)

**Comment by stephenhawk8054** [comment]
@robinmetral Can you test for breakages?

```adb
||dev.to/*/bb-2/$xhr,1p
```

**Comment by robinmetral** [comment]
@stephenhawk8054 that's a clever filter—I assumed that the document was entirely server-side generated and didn't think of looking at network requests!

It seems to work as expected. The filter blocks four requests in my testing:

## `/bb-2/post_comments`

Main column ad, below comments.

<details>
<summary>Screenshot</summary>

![](https://github.com/user-attachments/assets/8feec351-7905-4363-b032-8a8ae2bbd055)

</details>

## `/bb-2/post_sidebar`

Sticky sidebar ad.

<details>
<summary>Screenshot</summary>

![](https://github.com/user-attachments/assets/d38df4f8-45fd-415b-9ae9-13033fc2a771)

</details>

## `/bb-2/post_body_bottom`

Main column sponsored post, above comments. (No external link here, but this still meets the definition of an ad.)

<details>
<summary>Screenshot</summary>

![](https://github.com/user-attachments/assets/43ebc3b9-beb4-4764-a076-ef432e09aadd)

</details>

## `/bb-2/post_fixed_bottom`

Fixed "Leave a :heart:" banner on page load, not an ad but an annoyance. Can we still block it?

<details>
<summary>Screenshot</summary>

![](https://github.com/user-attachments/assets/30d48ed2-cea2-4279-b378-898bf0164f44)

</details>

**Comment by robinmetral** [comment]
Also, should this be addressed in EasyList? We could suggest changing the filter they're currently using (which looks for "Promoted" text).

**Comment by stephenhawk8054** [comment]
> Fixed "Leave a ❤️" banner on page load, not an ad but an annoyance. Can we still block it?

Please report annoyances to https://github.com/easylist/easylist/issues/ or https://github.com/AdguardTeam/AdguardFilters/issues
