### ISSUE TITLE
valid.x86.fr: nuisance

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#20524]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://valid.x86.fr/wk20nz`

### Category

nuisance

### Description

anti adb annoyance, `valid.x86.fr##.widget-advert-300-600` now unused

```
https://pastebin.com/raw/CDF2Cc0y
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 115
filterset (summary):
 network: 91839
 cosmetic: 46614
 scriptlet: 23049
 html: 1288
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, now
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1877-0, now
  ublock-annoyances: 5726-14, now
 default:
  user-filters: 1949-15, never
  ublock-filters: 36052-156, now
  ublock-badware: 7434-5, now
  ublock-privacy: 654-0, now
  ublock-unbreak: 2180-1, now
  ublock-quick-fixes: 143-4, now
  easylist: 75137-346, now
  easyprivacy: 32851-1494, now
filterset (user): [array of 927 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 10 redacted]
hostRuleset:
 added: [array of 7 redacted]
 removed:
  behind-the-scene * * noop
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 533 ms (selfie)
 maxAssetCacheWait: 197 ms
 unsuspendAfter: 188 ms
popupPanel:
 blocked: 4
 network:
  cookiefirst.com: 2
  paypalobjects.com: 2
 extended:
  ##*:style(border-radius:0px !important;)
  #@#ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
Where exactly do you get it ? How to reproduce ? screenshot ?

**Comment by Daxy7** [comment]
under `Submitted by kuahtreiba` and above `Processor (CPU)` is the notice. 
on default profile anti adb appears by just visiting

https://github.com/uBlockOrigin/uAssets/assets/91396482/10709633-fe21-4cfe-bff1-f70b9a2bf4c4

**Comment by mapx-** [comment]
I get only a blank rectangle.

However, is still an annoyance ?

test

`valid.x86.fr##+js(rmnt, script, /setTimeout.*style/)`

**Comment by Daxy7** [comment]
hmm. now i also have a black rectangle. this cosmetic filter blocks it completely though
https://github.com/uBlockOrigin/uAssets/assets/91396482/983ecd13-2ece-47e3-b2e6-8509a53ead68

```
valid.x86.fr##.fullwidth
```

**Comment by Daxy7** [comment]
it's on the homepage as this too
```
valid.x86.fr##.widget-advert
```
https://github.com/uBlockOrigin/uAssets/assets/91396482/2b091119-d392-4be1-83d2-64f8f0e8fade
