### ISSUE TITLE
officedepot.co.cr doesn't show preview images. 

### ISSUE THREAD

**Issue by maikol-solis** [uBlockOrigin/uAssets#20525]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.officedepot.co.cr/officedepotCR/en/search/?text=TARGUS`

### Description

For any product search, uBO blocks all the preview pictures in the list. If you disable uBO, then the site works as expected. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/4078489/15d4a8bc-33bf-4793-910c-781a7a14126b)
</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.52.2
Firefox: 119
filterset (summary):
 network: 261990
 cosmetic: 0
 scriptlet: 39678
 html: 1288
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 12m
  adguard-generic: 79387-45868, 12m
  adguard-mobile: 8832-7368, 12m
  adguard-spyware-url: 1306-90, 12m
  block-lan: 54-0, 12m
  curben-phishing: 76626-31, 12m
  fanboy-social: 16186-15067, 12m
  ublock-annoyances: 5728-1451, 12m
  dpollock-0: 11583-493, 12m
  spa-0: 3767-2695, 12m
  spa-1: 5717-3823, 12m
  adguard-spyware: 63270-17188, 12m
 default:
  user-filters: 0-0, never
  ublock-filters: 36054-9936, 12m
  ublock-badware: 7434-663, 12m
  ublock-privacy: 654-13, 12m
  ublock-unbreak: 2180-294, 12m
  easylist: 75137-33513, 12m
  easyprivacy: 32851-828, 12m
  urlhaus-1: 11855-0, 12m
  plowe-0: 3720-1, 12m
  ublock-quick-fixes: 143-55, 12m
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 removed:
  no-large-media: behind-the-scene false
  no-csp-reports: * true
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: true
 parseAllABPHideFilters: false
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6785 ms (selfie)
 maxAssetCacheWait: 3907 ms


```
</details>

**Comment by maikol-solis** [comment]
Thanks!

**Comment by stephenhawk8054** [comment]
Do these work?

```adb
officedepot.co.cr##+js(set, gbTracker, {})
officedepot.co.cr##+js(set, gbTracker.sendAutoSearchEvent, noopFunc)
```
