### ISSUE TITLE
galinos.gr: detection

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#20528]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.galinos.gr/web/drugs/main/substances/amisulpride/pharmacology`

### Category

detection

### Description

Message prompting to disable the Ad Blocker for this website.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-11-08 at 14-37-52 galinos gr ad leftover space and ad blocker detection · Issue #140 · kargig_greek-adblockplus-filter](https://github.com/uBlockOrigin/uAssets/assets/101707608/8da5418c-7100-4abe-ad85-2524f9d12aaf)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 115
filterset (summary):
 network: 376507
 cosmetic: 259420
 scriptlet: 46271
 html: 1288
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 57497-6279, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 94839-1930, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 178-0, 33m
  https://www.i-dont-care-about-cookies.eu/abp/: 25875-19, now
  adguard-generic: 79397-7880, now
  adguard-mobile: 8835-139, now
  adguard-spyware-url: 1306-87, now
  block-lan: 54-0, now
  curben-phishing: 76626-35, now
  adguard-social: 22002-869, now
  fanboy-thirdparty_social: 68-0, now
  [14 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36072-419, now
  ublock-badware: 7434-5, now
  ublock-privacy: 654-2, now
  ublock-unbreak: 2181-2, now
  ublock-quick-fixes: 137-4, now
  easylist: 75137-31475, now
  easyprivacy: 32851-1015, now
  urlhaus-1: 10900-0, now
  plowe-0: 3720-1, now
  GRC-0: 1056-2, 33m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 23730 ms (selfie)
 maxAssetCacheWait: 5768 ms
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ###header-social-icons
  ##.sharer-0
  ##ins.adsbygoogle
  ###bottomAd
  ###go-to-top
  ##.footer-social
  ##.sb-social
  ##.text-center.neutral.notice
  ##.header-billboard
  ##SHARE-BUTTON
  ##div.white.stripe.row:has-text(Ad Blocker)
```
</details>

**Comment by mapx-** [comment]
Is an account required to reproduce this issue?

**Comment by DimitrisKalaboukas** [comment]
@mapx- No.

**Comment by mapx-** [comment]
I cannot reproduce the issue.
Try using only the default lists / settings and test again.

**Comment by DimitrisKalaboukas** [comment]
@mapx- Very strange. I wonder if it is geo-dependent. I can block the message with the filter:

galinos.gr##div.white.stripe.row:has-text(Ad Blocker)

**Comment by gorhill** [comment]
> - [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.

Did you really verify this step?

>     added:
>       https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 57497-6279, now
>       https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 94839-1930, now
>       https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
>       https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 178-0, 33m
>       https://www.i-dont-care-about-cookies.eu/abp/: 25875-19, now
>       adguard-generic: 79397-7880, now
>       adguard-mobile: 8835-139, now
>       adguard-spyware-url: 1306-87, now
>       block-lan: 54-0, now
>       curben-phishing: 76626-35, now
>       adguard-social: 22002-869, now
>       fanboy-thirdparty_social: 68-0, now
>       [14 lists not shown]: [too many]

You have too many lists, we warn about this in [the documentation](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists):

> The likelihood of page breakage increases with more filter lists added.

**Comment by DimitrisKalaboukas** [comment]
@gorhill From my side, the problem also occurs with the default settings, I have tested it.

**Comment by DimitrisKalaboukas** [comment]
@MasterKia Yes, it works fine.
