### ISSUE TITLE
vk.com: nuisance / breakage

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#20526]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vk.com/wall121562_796`

### Category

nuisance

### Description

If the page is visited by an unauthorized person, the pictures are blurred.

I suggest adding to uBlock filters – Annoyances: `||userapi.com/impf/$image,urltransform=/^\/impf\/+//,domain=vk.com|vk.ru`

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![VK unauth](https://github.com/uBlockOrigin/uAssets/assets/20126984/2969a6ba-fd3b-4feb-a49a-61aa50c01abc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.1rc0
Chromium: 109
filterset (summary):
 network: 122486
 cosmetic: 64621
 scriptlet: 20204
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  RUS-0: 40095-9, now
  easylist: 75137-42, now
  easyprivacy: 32843-174, never
  plowe-0: 3720-1078, never
  ublock-badware: 7430-135, now
  ublock-filters: 35169-176, now
  ublock-privacy: 660-5, now
  ublock-quick-fixes: 146-89, now
  ublock-unbreak: 2134-13, now
  urlhaus-1: 11855-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3173 ms
 maxAssetCacheWait: 6 ms
popupPanel:
 blocked: 5
 network:
  mail.ru: 3
  tns-counter.ru: 1
  vk-portal.net: 1
 extended:
  ###system_msg
  ###ads_left
  #@#div[id$="notifiers_wrap"]
  ##+js(abort-on-property-read, Groups.showDisclaimer)
  ##+js(abort-on-property-read, PageBottomBanners)
  ##+js(abort-on-property-read, Unauthorized2)
  ##+js(href-sanitizer, a[href*="/away.php?"], ?to)
  ##+js(set-constant, noAdsAtAll, {})
```
</details>

**Comment by Neurotoxin001** [comment]
Now you've broken the blur in the pictures for logged in users

https://vk.com/wall-30602036_9630158

https://github.com/uBlockOrigin/uAssets/assets/39812401/f0f4d57a-6e7a-4052-85a9-e3a69460e768
https://github.com/uBlockOrigin/uAssets/assets/39812401/9ee22a5e-9f3c-4bd2-bae1-0f81565f0dd5

**Comment by Neurotoxin001** [comment]
>https://vk.com/wall121562_796

And pics from your example now don't even load  now:
https://github.com/uBlockOrigin/uAssets/assets/39812401/957e7e43-b492-4cbd-9c77-11d85639a0c3

**Comment by dportvine** [comment]
> `https://vk.com/wall121562_796`
> And pics from your example don't even load now without login: 
> https://github.com/uBlockOrigin/uAssets/assets/39812401/957e7e43-b492-4cbd-9c77-11d85639a0c3

I cannot reproduce.

<details>
<summary>Screen</summary>

![2023-11-10_083159](https://github.com/uBlockOrigin/uAssets/assets/111344219/8799c22d-d0aa-4200-9e05-70b5d9401a4b)
</details>

**Comment by mapx-** [comment]
@Neurotoxin001 update uBO to the last version

**Comment by Neurotoxin001** [comment]
I have uBO 1.53.0 and Chrome 119.0.6045.124.

Without uBlock filters – Annoyances:
https://github.com/uBlockOrigin/uAssets/assets/39812401/88e649a9-5be0-4b27-aabe-379e84898695

With uBlock filters – Annoyances:
https://github.com/uBlockOrigin/uAssets/assets/39812401/63b81163-74b7-44d2-8317-9ee2b1b179f9

**Comment by mapx-** [comment]
right, working fine in the last dev build
https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii

but broken in the stable one, I'll comment the filter for now

**Comment by dimisa-RUAdList** [comment]
It appears that an earlier version of the urltransform scriptlet worked differently. Correct operation of the rule became possible only from version 1.53.1b5: https://github.com/gorhill/uBlock/commit/d7c99b46e6

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e0fd4ef13ca963311ac8b90d0ebf1f2200a660b9

**Comment by stephenhawk8054** [comment]
Or we can use `!#if ext_devbuild`?

**Comment by dimisa-RUAdList** [comment]
As far as I understand, after [these changes](https://github.com/gorhill/uBlock/commit/cdc5e89f52), the rule can be safely returned as:
`||userapi.com/impf/$image,uritransform=/^\/impf\/+//,domain=vk.com|vk.ru`
