### ISSUE TITLE
sofa-dreams.com: breakage

### ISSUE THREAD

**Issue by leegarrett** [uBlockOrigin/uAssets#20536]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sofa-dreams.com/sofas-couches/wohnlandschaften/wohnlandschaft-stoff/stoff-wohnlandschaft-positano.html`

### Category

breakage

### Description

When uBlock Origin is enabled, selecting any of the preview pictures does not update the main picture. When UBO is disabled and the page reloaded, the website works as expected.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 115
filterset (summary):
 network: 104200
 cosmetic: 43429
 scriptlet: 18717
 html: 1098
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36124-130, now
  ublock-badware: 7434-5, now
  ublock-privacy: 657-0, now
  ublock-unbreak: 2181-1, now
  ublock-quick-fixes: 140-6, now
  easylist: 75150-700, now
  easyprivacy: 32856-725, now
  urlhaus-1: 10900-0, 1h.7m
  plowe-0: 3720-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 415 ms
 maxAssetCacheWait: 143 ms
popupPanel:
 blocked: 23
 network:
  sofa-dreams.com: 2
  adcell.com: 4
  amazon.com: 3
  doubleclick.net: 1
  facebook.net: 2
  kickbite.io: 1
  paypal.com: 6
  pinimg.com: 1
  s24.com: 2
  trustedshops.com: 1
 extended:
  ##+js(href-sanitizer, a[href^="https://app.adjust.com/"][href*="…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by okiehsch** [comment]
Works fine on my end. Are you logged in?

**Comment by gwarser** [comment]
Firefox. Probably related to cookie dialog.

**Comment by gwarser** [comment]
Is "Automatically refuse cookie banners" Firefox feature available in 115? I have it enabled in Nightly, and it hides the cookie dialog.

**Comment by okiehsch** [comment]
I can reproduce using Firefox if I hide the cookie dialog.

**Comment by okiehsch** [comment]
It works fine using Chromium even if I hide the cookie dialog.

**Comment by leegarrett** [comment]
Yes, it indeed seems to be related to the cookie dialog and Firefox. The site also breaks without ublock origin when visited for the first time, and clicking on something to make the cookie banner go away. Reloading always helps. I guess the reason it "worked" without ublock origin was just the reload event.

I'm closing the bug report as such. Sorry for the noise!

**Comment by leegarrett** [comment]
Also thanks @okiehsch and @gwarser for the swift responses!
