### ISSUE TITLE
skylar.com: breakage

### ISSUE THREAD

**Issue by ZephyraSilentis** [uBlockOrigin/uAssets#20538]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://skylar.com/products/boardwalk-delight-rollerball`

### Category

breakage

### Description

All product pages are blank — bar the header and footer of the page — with uBO enabled. As soon as uBO is turned off and the page is reloaded the page is fully displayed. As far as I can tell all other pages display correctly.

### Other extensions used

Privacy Badger, Dark Reader, Search by Image, and Video Background play fix. Issue persists with all other extensions disabled. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231108-115955](https://github.com/uBlockOrigin/uAssets/assets/24389272/f3ea3fc6-3706-4ee8-a00a-36abc7e14637)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 121
filterset (summary):
 network: 105608
 cosmetic: 34714
 scriptlet: 18776
 html: 1099
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36428-488, now
  ublock-badware: 7428-5, now
  ublock-privacy: 657-1, now
  ublock-unbreak: 2186-2, now
  ublock-quick-fixes: 141-6, now
  adguard-mobile: 8839-127, now
  easylist: 75159-16565, now
  easyprivacy: 32856-776, now
  urlhaus-1: 10900-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 291 ms (selfie)
 maxAssetCacheWait: 83 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by okiehsch** [comment]
Does it work if you add
`@@||googletagmanager.com/gtag/js$script,domain=skylar.com`
?

**Comment by ZephyraSilentis** [comment]
That appears to have fixed
