### ISSUE TITLE
watsons.com.tr: breakage

### ISSUE THREAD

**Issue by punisher018** [uBlockOrigin/uAssets#20531]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.watsons.com.tr/`

### Category

breakage

### Description

When ubo is on, the parts I marked in the screenshot do not appear on the site. Notification, support hotline and notification of extra discounted products sold on their own website. It is caused by content blocked by the EasyPrivacy filter list and uBlock filters - Privacy.

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bbbb1](https://github.com/uBlockOrigin/uAssets/assets/51531027/310c16c2-ed43-401a-acc0-b3eac7cfe26d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 124422
 cosmetic: 186177
 scriptlet: 31568
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt: 0-0, 41m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1668-0, 41m
  https://easylist.to/easylist/fanboy-annoyance.txt: 61917-113, 41m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 73923-5202, 41m
  https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/Soft98/Soft98NoAds.txt: 18-0, 41m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, 41m
  https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt: 412-1, 41m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94556-78249, 41m
  adguard-cookies: 28019-28019, 41m
  fanboy-cookiemonster: 48808-48808, 41m
  fanboy-social: 16189-16189, 41m
  fanboy-thirdparty_social: 69-15, 41m
  [3 lists not shown]: [too many]
 default:
  user-filters: 965-1, never
  TUR-0: 13874-13, 41m
  easylist: 75150-137, 41m
  easyprivacy: 32856-510, 41m
  plowe-0: 3720-1087, 41m
  ublock-badware: 7430-139, 41m
  ublock-filters: 35237-518, 41m
  ublock-privacy: 663-15, 41m
  ublock-unbreak: 2135-37, 41m
  urlhaus-1: 10900-0, 41m
filterset (user): [array of 955 redacted]
trustedset:
 added: [array of 18 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 549 ms (selfie)
 maxAssetCacheWait: 237 ms
popupPanel:
 blocked: 5
 network:
  watsons.com.tr: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  maps.googleapis.com: 1
  personaclick.com: 1
```
</details>

**Comment by liamengland1** [comment]
`@@||www.googletagmanager.com/gtm.js$script,domain=www.watsons.com.tr` for the live chat in the corner. The other elements are promotional and debatable as to whether they are considered ads IMO

**Comment by punisher018** [comment]
I realized this when I had a problem with live chat on this website today. Later, when I turned off ubo, I saw that different products were also on promotion. I think self-promotion posts should be acceptable for a shopping site, especially when they can be easily turned off with one click. Because almost all banners on the homepage are already related to self-promotion and discount campaigns. 
Of course, I respect the final decision of the administrators.

**Comment by mapx-** [comment]
add

```
@@||googletagmanager.com/gtm.js$script,domain=watsons.com.tr
@@||cdn.personaclick.com^$script,css,domain=watsons.com.tr
@@||api.personaclick.com^$xhr,domain=watsons.com.tr
@@||static.personaclick.com/Watsons/*/bell.png$image,domain=watsons.com.tr
```

@ryanbr

**Comment by ryanbr** [comment]
Are all of these these needed? Want to be 100% sure we only add exceptions that are needed.

**Comment by mapx-** [comment]
It's what I found to get visible all those elements.

**Comment by ryanbr** [comment]
@punisher018  can check each of these filters, see which ones we need

**Comment by punisher018** [comment]
@@||googletagmanager.com/gtm.js$script,domain=watsons.com.tr

it's necessary for live chat.

@@||cdn.personaclick.com^$script,css,domain=watsons.com.tr
@@||api.personaclick.com^$xhr,domain=watsons.com.tr
@@||static.personaclick.com/Watsons/*$image,domain=watsons.com.tr

they're necessary for notifications on right and top (bell) and for stories (the round shaped ones in the screenshot)

There seems to be no problem with these filters.

**Comment by ryanbr** [comment]
personaclick? I'm not seeing this.  I am seeing the live chat still `Watsons Alışveriş Asistanı`
