### ISSUE TITLE
app.hellovaia.com: ads

### ISSUE THREAD

**Issue by XxXJEFFXDXxX** [uBlockOrigin/uAssets#20539]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.hellovaia.com/`

### Category

video ads and picture ads

### Description

video ads when entered into flashcard learning area and picture ads on home page.

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Flashcard learning page](https://github.com/uBlockOrigin/uAssets/assets/102808200/aa2fb90f-f959-44c5-9e68-62246ed5e8cb)
![home page](https://github.com/uBlockOrigin/uAssets/assets/102808200/36182201-176a-48c1-8632-9212e5b3082c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 121381
 cosmetic: 58598
 scriptlet: 19037
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  DEU-0: 7183-0, now
 default:
  CHN-0: 25525-135, now
  easylist: 75159-32, now
  easyprivacy: 32856-86, now
  plowe-0: 3723-1077, now
  ublock-badware: 7430-135, now
  ublock-filters: 35227-182, now
  ublock-privacy: 660-6, 1h.54m
  ublock-quick-fixes: 146-89, 1h.53m
  ublock-unbreak: 2135-35, now
  urlhaus-1: 10900-0, 1m
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 850 ms (selfie)
 maxAssetCacheWait: 619 ms
popupPanel:
 blocked: 21
 no-large-media: true
 no-popups: true
 network:
  amplitude.com: 11
  doubleclick.net: 1
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  lr-in.com: 1
  paypal.com: 2
  sentry.io: 2
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by partoftheworlD** [comment]
try this
```
||publicfiles-studysmarter.b-cdn.net/campaigns/*
app.hellovaia.com##app-feed-ads
app.hellovaia.com##app-enigma-media + hide-ads
app.hellovaia.com##app-enigma:has(app-ditch-ads)
app.hellovaia.com##mat-drawer-content:style(margin-right: auto !important;)
app.hellovaia.com##mat-drawer
```

**Comment by partoftheworlD** [comment]
I'm not sure about ##app-company-profiles-carousel, should it be added to the filter list? Or is it basically something useful?
```
app.hellovaia.com##app-company-profiles-carousel
```
![image](https://github.com/uBlockOrigin/uAssets/assets/6013494/e2a9b344-c6ce-49d2-9420-82a7ad30a8aa)
