### ISSUE TITLE
audiobookbay.is: ads

### ISSUE THREAD

**Issue by Lajiii** [uBlockOrigin/uAssets#20532]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://audiobookbay.is/`

### Category

ads

### Description

Ads remaining in the area where it says "AD" in red, and still appear after refreshing using the element picker on it. I will include the screenshot examples although I do not think it's a specially hard to describe issue. Thank you very much to the volunteers working on uBO

### Other extensions used

Bitwarden, Mulvad Privacy Companion

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![firefox_YwV6zpiYon](https://github.com/uBlockOrigin/uAssets/assets/134974317/17a19ca9-1b4b-43ac-85b0-835036b5e863)

![firefox_6bt8JfNTuY](https://github.com/uBlockOrigin/uAssets/assets/134974317/1a771cdd-d388-4a8c-8b4d-03ba919fc83b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 106213
 cosmetic: 115976
 scriptlet: 25491
 html: 1289
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  block-lan: 54-0, 5m
  fanboy-thirdparty_social: 69-0, 5m
  easylist-annoyances: 4168-94, 5m
  easylist-chat: 149-0, 5m
  fanboy-cookiemonster: 48808-276, 5m
  ublock-cookies-easylist: 492-0, 5m
  easylist-newsletters: 6631-13, 5m
  easylist-notifications: 2872-4, 5m
  fanboy-social: 16189-22, 5m
  ublock-annoyances: 5731-527, 5m
 default:
  user-filters: 15-0, never
  ublock-filters: 36124-257, 5m
  ublock-badware: 7434-5, 5m
  ublock-privacy: 657-0, 5m
  ublock-unbreak: 2181-1, 5m
  ublock-quick-fixes: 139-6, 5m
  easylist: 75150-247, 5m
  easyprivacy: 32856-114, 5m
  urlhaus-1: 10900-0, 5m
filterset (user): [array of 15 redacted]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 263 redacted]
hostRuleset:
 added: [array of 1099 redacted]
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 100
hiddenSettings: [none]
supportStats:
 allReadyAfter: 567 ms (selfie)
 maxAssetCacheWait: 281 ms
popupPanel:
 blocked: 14
 no-remote-fonts: true
 network:
  addthis.com: 1
  facebook.net: 1
  google.com: 1
  googletagmanager.com: 1
  ibb.co: 1
  ssl-images-amazon.com: 8
  twitter.com: 1
 extended:
  ##.addthis_toolbox
  ##.addthis_default_style
  ##.addthis_button_facebook
  ##.addthis_button_reddit
  ##.addthis_button_linkedin
  ##.addthis_button_tumblr
  ##.addthis_button_compact
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://wa.me/?text="]
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`audiobookbay.is##[href="/ddldatr"]`
