### ISSUE TITLE
Filters can become stale and are not able to be deleted

### ISSUE THREAD

**Issue by vgturtle127** [uBlockOrigin/uAssets#2053]
### URL(s) where the issue occurs

Doesn't apply on this issue, the issue is with the extension itself not updating the filters, and not removing them properly.

### Describe the issue

Filter lists that are removed from the default main list become stale, and are not able to be deleted or updated. They are then moved to custom lists and fail to update, be deleted, or any other action you can take doesn't go through. This issue also applies to Mozilla and other browsers that support uBlock Origin.

The specific filter is the Malware filter list by Disconnect.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/3183676/39099249-f120baee-463c-11e8-8577-fe3392740d50.png)

![image](https://user-images.githubusercontent.com/3183676/39099240-c0851f24-463c-11e8-9004-89b44893a623.png)

![image](https://user-images.githubusercontent.com/3183676/39099243-daaaf61c-463c-11e8-91bb-ccc82f1825e2.png)

### Versions

- Browser/version: [Version 65.0.3325.181 (Official Build) (64-bit)]
- uBlock Origin version: [v1.15.24]

### Settings

- See screenshots

### Notes

I have tried deleting the filter list, purging it's cache and then deleting it, removing the filter manually, and restarting the browser with extensions disabled to manually delete the filters. No action fixes the issue, besides uninstalling the extension and removing all of it's residual files from the computer.

**Comment by krystian3w** [comment]
Try use new person in Chrome.

https://support.google.com/chrome/answer/2364824&hl=en

Maybe only chrome profile is broken.

**Comment by mapx-** [comment]
You could try reinstall uBo 

However, ublock issues have to be reported here (try first reinstalling uBo):
https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by vgturtle127** [comment]
@krystian3w No, I don't use profiles. Also, the link you provided is for anonymous crash reports. Ha.

@mapx- OK, usually my issues get deleted or closed there and I am told to come here, but I will try again.
