### ISSUE TITLE
terrylove.com: anti-adblock

### ISSUE THREAD

**Issue by ppurplep** [uBlockOrigin/uAssets#20537]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

'https://terrylove.com/forums/index.php'

### Description

This anti-adblock message comes up probabilistically while using the site, maybe 1 in 4 times?  If I open the URL in an Incognito window it always comes up the first time.  Using the Element Picker to stop it doesn't work, as the element name changes each time.   I have a simple custom filter to block the page's banner, but the problem occurs without it.  

### Other extensions used

None (reproduced with all disabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1071" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/150280792/6d616a49-81ce-4763-baf0-f8839643482e">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104218
 cosmetic: 43432
 scriptlet: 18876
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 75150-16, 3m
  easyprivacy: 32856-64, 3m
  plowe-0: 3723-1074, 3m
  ublock-badware: 7430-135, 3m
  ublock-filters: 35237-152, 3m
  ublock-privacy: 663-6, 3m
  ublock-quick-fixes: 143-86, 3m
  ublock-unbreak: 2135-32, 3m
  urlhaus-1: 10900-0, 2m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 731 ms (selfie)
 maxAssetCacheWait: 279 ms
popupPanel:
 blocked: 3
 network:
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##.p-header

```
</details>

**Comment by okiehsch** [comment]
After clicking "No Thanks" the message does not show again.
We deal with such "soft" anti-adblock issues in the `uBO-annoyance` list, you can enable that list or
add
`terrylove.com##+js(nostif, prompt, 1000)`
to your personal filter list.

**Comment by ppurplep** [comment]
So, as I mentioned, the message is probabilistic or intermittent, it does not appear every time you load a page from terrylove.com.  If I click "No Thanks" and then reload (or load a new page from the site), there's no popup on that load.  But if I then reload  4 or 5 times (or after loading 4 or 5 new pages), I will get the message again.  

Are you seeing a different behavior?  Or are you saying having to click "No Thanks" every 4 or 5 page fetches is still a "soft" anti-adblock and so belongs in the uBO-annoyance list?

But thank you for the pointer to uBO-annoyance, enabling that seems to be working great for me!  Sorry not to have sussed that out on my own.

**Comment by okiehsch** [comment]
> But if I then reload 4 or 5 times (or after loading 4 or 5 new pages), I will get the message again.

You are right, my bad.
I could reproduce every reload by simply blocking the cookie the site tried to set and only tested if "no thanks" worked by reloading two or three times, I canreproduce after every fifth reload on my end.
I will add the fix to the main list.

**Comment by ppurplep** [comment]
Thanks for taking a second look!
