### ISSUE TITLE
airtel.in/dth: breakage

### ISSUE THREAD

**Issue by ArgX11** [uBlockOrigin/uAssets#20530]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.airtel.in/dth`

### Category

breakage

### Description

The DTH section of the website freezes and stops working when uBlock is enabled.

### Other extensions used

NA

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![screencapture-airtel-in-dth-Kolkata-2023-11-08-19_09_12](https://github.com/uBlockOrigin/uAssets/assets/22514844/3b2cda6d-0a3f-4926-984b-6ca17f88681f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 294084
 cosmetic: 269126
 scriptlet: 47903
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 180-0, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=3: 0-0, now
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4827-115, now
  IND-0: 12778-0, 1m
  RUS-0: 40095-9, 1m
  adguard-cookies: 28017-44, now
  adguard-generic: 79397-690, now
  adguard-mobile: 8835-73, now
  adguard-mobile-app-banners: 4731-11, now
  adguard-other-annoyances: 13754-45, now
  adguard-popup-overlays: 25074-428, now
  [17 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 75150-1992, now
  easyprivacy: 32856-16717, now
  plowe-0: 3720-1579, now
  ublock-badware: 7430-332, now
  ublock-filters: 35237-4316, now
  ublock-privacy: 663-180, now
  ublock-quick-fixes: 142-90, now
  ublock-unbreak: 2135-147, now
  urlhaus-1: 10900-2, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 957 ms (selfie)
 maxAssetCacheWait: 596 ms
popupPanel:
 blocked: 5
 network:
  airtel.in: 4
  googletagmanager.com: 1
 extended:
  ##.scrollToTop
  ##.icon-back-to-top
```
</details>

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
airtel.in##+js(no-xhr-if, analytics/bulk-pixel)
```

**Comment by okiehsch** [comment]
Yes,the blocking filter has been removed in `EasyPrivacy` anyway, so your filter is kind of moot but you can add it to `uBO-Privacy` if you want.
