### ISSUE TITLE
jalshamoviez.blog: popups

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#20546]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jalshamoviez.blog/movie/488/fright-night-(2011)-dual-audio-hindi-dubbed-movie.html`

### Category

popups

### Description

opens unwanted tabs when clicking anywhere

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 121
filterset (summary):
 network: 105359
 cosmetic: 50925
 scriptlet: 18766
 html: 1099
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36420-174, 3m
  ublock-badware: 7428-5, 3m
  ublock-privacy: 657-0, 3m
  ublock-unbreak: 2186-1, 3m
  ublock-quick-fixes: 143-6, 3m
  adguard-mobile: 8839-100, 4m
  easylist: 75167-745, 3m
  easyprivacy: 32854-732, 3m
  urlhaus-1: 10645-0, 3m
  plowe-0: 3722-1, 3m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4870 ms
 maxAssetCacheWait: 23 ms
popupPanel:
 blocked: 16
 network:
  adserver.live: 9
  bmkkmlajjmjvv.top: 3
  googletagmanager.com: 2
  ssindserving.com: 2
```
</details>

**Comment by BlazeFTL** [comment]
Try 
```
jalshamoviez.*##+js(rmnt, script, localStorage.setItem)
