### ISSUE TITLE
ticketmaster.sg: detection

### ISSUE THREAD

**Issue by laozhabao** [uBlockOrigin/uAssets#20543]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://ticketmaster.sg/ticket/area/23_afasingapore/1325`

### Description

The website detected I'm using adblocker.

### Other extensions used

I only has two extensions (windscribe & ublock) that cause the popup to happen. The popup is gone when I disable both of those. The popup will happen when I enable EITHER one of them, or both.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ticketmaster](https://github.com/uBlockOrigin/uAssets/assets/84159085/d8deb5e6-00e7-47dc-9763-3d16cfac7bbb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 105442
 cosmetic: 40317
 scriptlet: 18841
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 72367-15, 3d.5h.33m
  easyprivacy: 32852-64, 5d.5h.4m
  plowe-0: 3721-1073, 2d.7h.7m
  ublock-badware: 7430-138, 4h.45m
  ublock-filters: 35146-145, 4h.44m
  ublock-privacy: 660-5, 1d.3h.19m
  ublock-quick-fixes: 146-89, 10h.46m
  ublock-unbreak: 2133-31, 4h.43m
  urlhaus-1: 11855-0, 10h.47m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 137 ms (selfie)
 maxAssetCacheWait: 74 ms
```
</details>

**Comment by mapx-** [comment]
Keep only uBO

**Comment by laozhabao** [comment]
> Keep only uBO

negative, it's still available even if I disabled windscribe. I even tried on firefox with no other extension but ublock and the same popup message happens.

**Comment by stephenhawk8054** [comment]
Have you forced update the filter lists yet?

**Comment by laozhabao** [comment]
> Have you forced update the filter lists yet?

not really but I just checked again today and the ticketmaster website does stops detecting adblock currently (5 days later after the report)
Case closed. (Unless ticketmaster decides to beat the adblock once again)

**Comment by stephenhawk8054** [comment]
It's because the filter lists auto-update for you. If you want it to have effects earlier, you need to force update it after fixing on github.
