### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Bugreport33333333333** [uBlockOrigin/uAssets#20544]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=DyhDj3dtYK4`

### Category

detection

### Description

The ad blocker was working fine until i clicked other vid than youtube's ad blocker detected the ad blocker 
idk why it's doing this 
Yes this is a youtube report why i'm i should checkmark 1. in Prerequisites?

### Other extensions used

Didn't use anything else.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/150306597/5f0cc136-f183-4111-97a2-3eeff76daf48)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104190
 cosmetic: 43408
 scriptlet: 18707
 html: 1098
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36105-234, now
  ublock-badware: 7434-5, now
  ublock-privacy: 657-0, now
  ublock-unbreak: 2181-1, now
  ublock-quick-fixes: 139-6, 46m
  easylist: 75136-551, 46m
  easyprivacy: 32843-767, 46m
  urlhaus-1: 10900-0, 46m
  plowe-0: 3722-1, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 734 ms (selfie)
 maxAssetCacheWait: 366 ms
popupPanel:
 blocked: 25
 network:
  youtube.com: 13
  doubleclick.net: 3
  google.com: 9
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?privateDo…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?("getAdBr…
  ##+js(replace-node-text, script, /^(\(function serverContract\(\…
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
