### ISSUE TITLE
f1racing.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#2054]
### URL(s) where the issue occurs

`f1racing.pl`

### Describe the issue
Cookies message

### Screenshot(s)

<img src="https://user-images.githubusercontent.com/36385327/39085229-ffffed5e-457f-11e8-9928-4ac47d9af67d.png">

### Versions

- Browser/version: Vivaldi 1.14.1077.60
- uBlock Origin version: 1.16.0

### Settings

```
- "selectedFilterLists": [
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt",
    "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt",
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt",
    "https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt",
    "https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt",
    "POL-0",
    "plowe-0",
    "fanboy-social",
    "spam404-0",
    "malware-1",
    "malware-0",
    "disconnect-malvertising",
    "easyprivacy",
    "easylist",
    "awrl-0",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-badware",
    "ublock-filters",
    "nano-whitelist",
    "nano-timer",
    "nano-filters",
    "nano-defender",
    "user-filters"
  ],
```

### Notes
https://github.com/MajkiIT/polish-ads-filter/issues/7238
Only this cookie message is here and user must click „Dalej" to go to right page. So probably something new should be added to uBO to make auto click „Dalej" or redirect to `http://f1racing.pl/x-set-cookie/`.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2229

**Comment by krystian3w** [comment]
IMO now possible use `set-cookie`, page don't check value for cookie to cover by trusted-set-cookie for use static or dynamic timestamp (`$now$`):

```adb
f1racing.pl##+JS(set-cookie, x-id-cookies-yes, 1, , reload, 1)
```

Filter worked fine after I reinstalled ubo 1.52.2 (maybe disk corruption).

**Comment by mapx-** [comment]
- it does not work on my side - chrome
- a working filter could be:

`f1racing.pl##+js(trusted-click-element, [href="/x-set-cookie/"], , 500)`

**Comment by krystian3w** [comment]
I see typo in cookie name - sinuglar instead plural.

**Comment by krystian3w** [comment]
@peace2000 / @Nojuuu maybe possible copy to Fanboy Annoyance suplement: https://github.com/uBlockOrigin/uAssets/issues/2054#issuecomment-1779019818 (to cover anti fans of Polish Annoyance Filters / Polish GDPR-Cookie list)

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/commit/519544f83f2dbc56bdac355c5ec0efa602301e88

**Comment by krystian3w** [comment]
Still I prefere global `set-cookie`, I guess webmaster didn't know about bug with too low timestamp 1-15:

Thu Jan 01 1970 00:00:01 - Thu Jan 01 1970 00:00:15 GMT+0000

**Comment by peace2000** [comment]
I couldn't get it to work on my end by setting cookies.
