### ISSUE TITLE
youtube.com: privacy

### ISSUE THREAD

**Issue by ShereeBrown** [uBlockOrigin/uAssets#20545]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=1Rs_KnBIPLo`

### Category

privacy

### Description

  YouTube anti-ads blocker please need help I am sticking to YouTube ads, and your ads blocker does not work 

### Other extensions used

used a lot of time

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 104613
 cosmetic: 64744
 scriptlet: 18870
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-social: 22003-33, 2m
 default:
  user-filters: 0-0, never
  easylist: 75167-17, 2m
  easyprivacy: 32855-67, 2m
  plowe-0: 3722-1074, 2m
  ublock-badware: 7430-135, 2m
  ublock-filters: 35218-159, 2m
  ublock-privacy: 663-7, 2m
  ublock-quick-fixes: 146-87, 2m
  ublock-unbreak: 2135-32, 2m
  urlhaus-1: 10645-0, 2m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 688 ms (selfie)
 maxAssetCacheWait: 477 ms
popupPanel:
 blocked: 0
 no-popups: true
 no-remote-fonts: true
 extended:
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?\"\}\}\}\]\…
  ##+js(trusted-replace-fetch-response, /(hqdefault\.jpg\?sqp=-oay…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?"\}\}\}\]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
> - [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

**Comment by ShereeBrown** [comment]
I tried using ublock origin on Edge I had to give up on Edge and better use Firefox

**Comment by ShereeBrown** [comment]
I wish YouTube would stop anti adblocker This is out of control I am serious

**Comment by stephenhawk8054** [comment]
Did you follow the steps on the post link you **CLICKED** on ??

> - [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.

**Comment by ShereeBrown** [comment]
I tried Firefox is the best  I had to give up Edge I do not use Edge anymore because YouTube's anti-block Ublock origin does not work I have tried to update that adblocker not work

**Comment by mapx-** [comment]
@ShereeBrown go to https://github.com/uBlockOrigin/uAssets/issues/20586
