### ISSUE TITLE
visualcapitalist.com: detection

### ISSUE THREAD

**Issue by number3d** [uBlockOrigin/uAssets#20552]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.visualcapitalist.com/`

### Category

detection

### Description

site detects ublock

### Other extensions used

almost none, nothing interfering to my knowledge

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 126631
 cosmetic: 136017
 scriptlet: 23840
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1668-0, now
  RUS-0: 40097-18, now
  block-lan: 54-0, now
  easylist-annoyances: 4168-42, now
  easylist-chat: 150-0, now
  easylist-newsletters: 6633-16, now
  easylist-notifications: 2872-109, now
  fanboy-cookiemonster: 48819-238, now
  fanboy-social: 16189-13, now
  ublock-cookies-easylist: 493-5, now
 default:
  user-filters: 5-0, never
  easylist: 75165-46, now
  easyprivacy: 32854-455, now
  plowe-0: 3722-1079, now
  ublock-badware: 7430-135, now
  ublock-filters: 35228-199, now
  ublock-privacy: 663-15, now
  ublock-quick-fixes: 146-88, 1h.6m
  ublock-unbreak: 2135-35, now
  urlhaus-1: 10645-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 316 ms (selfie)
 maxAssetCacheWait: 209 ms
popupPanel:
 blocked: 16
 network:
  ads-twitter.com: 1
  adsafeprotected.com: 2
  advertising.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  licdn.com: 2
  merequartz.com: 2
  pubguru.net: 1
  truculentrate.com: 1
  unblockia.com: 1
  wp.com: 2
 extended:
  ##.visua-target
  ##.mvp-widget-home-head
  ##.wpforms-ajax-form
  ###mvp-fly-soc-wrap
  ##.mvp-nav-soc-wrap
  ##.mvp-nav-soc-but
  ##.mvp-feat1-list-ad
  ##.mvp-ad-label
  ###mvp-foot-soc
  ##.mvp-foot-soc-list
  ##.mvp-fly-top
  ##.back-to-top:not(body):not(html)
  ##.grecaptcha-badge
  #@#.ad-unit
  #@#.ad_unit
  ##+js(remove-attr, jsaction, #islsp c-wiz a[href^="http"][data-v…
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by okiehsch** [comment]
Made a mistake testing.

**Comment by okiehsch** [comment]
Should work now.
