### ISSUE TITLE
111.90.141.252: ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#20559]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://111.90.141.252/`

### Category

ads

### Description

ads, also shows ads before videos on page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 121
filterset (summary):
 network: 105670
 cosmetic: 50930
 scriptlet: 18775
 html: 1099
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36431-174, 6m
  ublock-badware: 7433-5, 6m
  ublock-privacy: 657-0, 6m
  ublock-unbreak: 2186-1, 6m
  ublock-quick-fixes: 149-7, 6m
  adguard-mobile: 8839-100, 6m
  easylist: 75166-745, 6m
  easyprivacy: 32854-731, 6m
  urlhaus-1: 10950-0, 6m
  plowe-0: 3722-1, 6m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 612 ms (selfie)
 maxAssetCacheWait: 276 ms
popupPanel:
 blocked: 9
 network:
  cgjnf.com: 8
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
tested in desktop

```
111.90.141.252##.mfp-ready
111.90.141.252##html:style(overflow: auto !important;)
*/dyasds/$media,redirect=noopmp3-0.1s,domain=111.90.141.252
```
