### ISSUE TITLE
tii.la: breakage

### ISSUE THREAD

**Issue by The-Ellimst-17** [uBlockOrigin/uAssets#20553]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tii.la/C6iby`

### Category

breakage

### Description

unable to load captcha for verification

### Other extensions used

popup blocker (strict), fastforward, HTTPs everywhere, privacy badger.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 104284
 cosmetic: 43441
 scriptlet: 18873
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 8-2, never
  easylist: 75165-16, now
  easyprivacy: 32854-64, now
  plowe-0: 3722-1074, now
  ublock-badware: 7435-135, now
  ublock-filters: 35229-151, now
  ublock-privacy: 663-5, now
  ublock-quick-fixes: 152-89, now
  ublock-unbreak: 2135-32, now
  urlhaus-1: 10950-0, now
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 22 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 12 redacted]
hostRuleset:
 added: [array of 17 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 25592 ms (selfie)
 maxAssetCacheWait: 2655 ms
popupPanel:
 blocked: 4
 no-cosmetic-filtering: true
 no-large-media: true
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
 network:
  tii.la: 1
  glursihi.net: 1
  googletagmanager.com: 1
  recaptcha.net: 1
 extended:
  ##.banner-inner:remove()
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(set-constant, blurred, false)
  ##+js(no-window-open-if)
  ##+js(no-fetch-if, /googlesyndication|inklinkor/)
  ##+js(no-xhr-if, /pagead2\.googlesyndication\.com|inklinkor\.com…
  ##+js(no-setTimeout-if, ads)
  ##+js(abort-current-script, XMLHttpRequest, adb)
  ##+js(remove-node-text, script, adb_detected)
```
</details>

**Comment by gorhill** [comment]
> - [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

> `no-scripting: true`
