### ISSUE TITLE
a-z-animals.com: breakage

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20569]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://a-z-animals.com/articles/womans-viral-video-captures-a-monster-crocodile-swimming-right-up-to-shore-on-a-beach/`

### Category

breakage

### Description

The site doesn't load the video when uBO is enabled. When uBO is turned off for this site, the video loads, but you have to watch an ad before you can watch the actual video.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBO enabled
<img width="1436" alt="Screen Shot 2023-11-09 at 3 46 15 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/02ce9550-2081-49b3-873d-0a638c597551">
uBO disabled (after watching ad)
<img width="1440" alt="Screen Shot 2023-11-09 at 3 50 46 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/f7e283f3-70d2-423e-acd8-c6257b9ef9c7">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 104585
 cosmetic: 44968
 scriptlet: 22848
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5767-9, now
 default:
  user-filters: 46-2, never
  easylist: 75175-16, now
  easyprivacy: 32854-64, now
  plowe-0: 3722-1074, now
  ublock-badware: 7435-135, now
  ublock-filters: 35231-151, now
  ublock-privacy: 664-5, now
  ublock-quick-fixes: 153-94, now
  ublock-unbreak: 2135-33, now
  urlhaus-1: 10950-0, now
filterset (user): [array of 44 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 222 ms (selfie)
 maxAssetCacheWait: 101 ms
popupPanel:
 blocked: 7
 network:
  adthrive.com: 1
  anrdoezrs.net: 1
  cloudflareinsights.com: 1
  getlasso.co: 1
  googleoptimize.com: 1
  googletagmanager.com: 1
  videoplayerhub.com: 1
 extended:
  ##.adthrive-video-player
  ##.adthrive
  ##.adthrive-ad
  ##.adthrive-content
  ##.at-sidebar-ad
  ##.ad-unit:not(.text-ad):not(.textads)
```
</details>

**Comment by ghost** [comment]
`https://a-z-animals.com/animals/wolf/wolf-facts/are-wolves-nocturnal-or-diurnal/`
Ad leftover on mobile, using Edge for Android:


https://github.com/user-attachments/assets/91672ce2-3c9d-4120-aa76-c2ab7eeb0e62

**Comment by mapx-** [comment]
for easylist

`a-z-animals.com##.text-center:has-text(Advertisement)`

**Comment by ghost** [comment]
https://github.com/easylist/easylist/issues/22624#issuecomment-3694393281
