### ISSUE TITLE
yandex-direct ads reappear after page is reloaded

### ISSUE THREAD

**Issue by akamaus** [uBlockOrigin/uAssets#2056]
### URL(s) where the issue occurs

`https://news.yandex.ru/index.html`

I'm abserving tons of ads on right side of news.yandex.ru pages.
I tried to manually block it with element picker. Expression `news.yandex.ru##.sticky_visible.sticky_js_inited.i-bem` sort of works, but after page reload ads return (after a pause of a couple of seconds after page load)

If I block the element once again, I got repeating entry in 'my filters'.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/58955/39110548-3ca022d2-46da-11e8-9e69-f01b8198ee12.png)

### Versions

- Browser/version: Chromium-63.0.3239.108
- uBlock Origin version: 1.16.0

### Settings

These are my fiteres:
```
 ! 12/17/2017, 9:52:35 AM https://yandex.ru/maps/213/moscow/?ll=37.620393%2C55.740406&z=10
||avatars.mds.yandex.net/get-bunker$image

! 12/17/2017, 9:53:27 AM https://yandex.ru/maps/213/moscow/?ll=37.620393%2C55.726848&z=10
||avatars.mds.yandex.net/get-bunker/$image

! 12/17/2017, 9:54:54 AM https://yandex.ru/maps/213/moscow/?ll=37.620393%2C55.726848&z=10
yandex.ru##.home-panel-content-view__body > div:nth-of-type(2) > div

! 2/20/2018, 10:18:53 AM http://x-true.info/27056-za-bashara-asada-bez-flaga-bez-rodiny.html
||gorenpe.ru/*$image

news.yandex.ru##.sticky_visible.sticky_js_inited.i-bem
```

**Comment by uBlock-user** [comment]
Does adding `||mc.yandex.ru^` stop the ads ?

**Comment by mapx-** [comment]
Did you try the last chrome 66 ?

**Comment by mapx-** [comment]
@dimisa

**Comment by ghajini** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
https://greasyfork.org/ru/scripts/19993-ru-adlist-js-fixes
