### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by DrStug** [uBlockOrigin/uAssets#20568]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=RdXaY81CY-g`

### Category

detection

### Description

[https://imgur.com/Uzlxk3J](url) the extension gets flagged by Youtube.com as an adblocker and this results in the following result (see screenshot) 

### Other extensions used

Mega Version 5.6.0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 104289
 cosmetic: 43444
 scriptlet: 18871
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75175-16, now
  easyprivacy: 32854-64, now
  plowe-0: 3722-1074, now
  ublock-badware: 7435-135, now
  ublock-filters: 35231-151, now
  ublock-privacy: 663-5, now
  ublock-quick-fixes: 153-90, now
  ublock-unbreak: 2135-32, now
  urlhaus-1: 10950-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1075 ms
 maxAssetCacheWait: 13 ms
popupPanel:
 blocked: 4
 network:
  youtube.com: 1
  doubleclick.net: 3
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ##+js(trusted-replace-xhr-response, /\"adPlacements.*?\"\}\}\}\]…
  ##+js(trusted-replace-fetch-response, /(hqdefault\.jpg\?sqp=-oay…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?"\}\}\}\]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(trusted-replace-fetch-response, /"adPlacements.*?privateD…
  #@#+js(trusted-replace-fetch-response, /"adPlacements.*?"getAdBr…
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/19976
