### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by KobeWinski** [uBlockOrigin/uAssets#20573]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=Itr9lFnilto`

### Category

detection

### Description

Keeps getting detected on a new tab

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 116
filterset (summary):
 network: 104289
 cosmetic: 43444
 scriptlet: 18871
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75175-16, 1h.32m
  easyprivacy: 32854-64, 1h.32m
  plowe-0: 3722-1074, 1h.32m
  ublock-badware: 7435-135, 1h.32m
  ublock-filters: 35231-151, 1h.32m
  ublock-privacy: 663-5, 1h.32m
  ublock-quick-fixes: 153-90, 1h.32m
  ublock-unbreak: 2135-32, 1h.32m
  urlhaus-1: 10950-0, 1h.32m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 511 ms (selfie)
 maxAssetCacheWait: 82 ms
popupPanel:
 blocked: 4
 network:
  youtube.com: 1
  doubleclick.net: 3
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytd-merch-shelf-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?\"\}\}\}\]\…
  ##+js(trusted-replace-fetch-response, /((?:hqdefault\.jpg\?sqp=-…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?"\}\}\}\]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by lambdarobert** [comment]
I can confirm, even with everything up to date it is still not working.

**Comment by Aman122641** [comment]
Me too.

**Comment by mapx-** [comment]
go to https://github.com/uBlockOrigin/uAssets/issues/19976
