### ISSUE TITLE
Issue with /services/analytics/* pattern

### ISSUE THREAD

**Issue by alphabetek** [uBlockOrigin/uAssets#2057]
### URL(s) where the issue occurs

`Not released yet, issue discovered in QA`

### Describe the issue

We have some URLs containing <custom_path>/services/analytics/<custom_path>

### Screenshot(s)

![services-analytics](https://user-images.githubusercontent.com/5899023/39118632-1be2fdde-46ea-11e8-8791-7ed80d02d553.png)

### Versions

- Browser/version: Chrome and FF
- uBlock Origin version: 1.16.0

### Notes

Line to be removed: https://github.com/uBlockOrigin/uAssets/blob/15214cfdef6fb8166cbee25dcfad164f4154b83e/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt#L2611

**Comment by gorhill** [comment]
You will have to contact EasyPrivacy maintainers, I won't mark that filter as `badfilter` for an unstated reason. You always need to provide a URL where the issue occurs, otherwise the issue is completely unactionable. EasyPrivacy maintainers will require the same.
