### ISSUE TITLE
knowledgehub.com: breakage

### ISSUE THREAD

**Issue by bruhdev1290** [uBlockOrigin/uAssets#20575]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

when downloading a test for offline use it fails to download and gives an error message when disabling the adblocker it's no longer an issue

### A specific URL where the issue occurs.

`https://www.knowledgehub.com/offline/qbank/86314459`

### Steps to Reproduce

go to `https://www.knowledgehub.com/education/offeringdashboard/index/c8dcf4ee4a5e9a8984448e416dbcce39`

and then click Exam Simulation 

and then click Access offline

### Expected behavior

it should be able to download even with a adblocker enabledan

### Actual behavior

it fails to download

### uBO version

1.52.2

### Browser name and version

google chrome 119.0.6045.123 

### Operating System and version

windows 11 22H2

**Comment by mapx-** [comment]
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by mapx-** [comment]
@bruhdev1290 => `axis.trivia@gmail.com`

**Comment by bruhdev1290** [comment]
I sent the credentials
