### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by k4d1r3x** [uBlockOrigin/uAssets#20571]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=6pizhpmtXAE`

### Category

detection

### Description

https://www.youtube.com/watch?v=6pizhpmtXAE uzantı Youtube.com tarafından bir reklam engelleyici olarak işaretleniyor ve bu, aşağıdaki sonuçla sonuçlanıyor (ekran görüntüsüne bakın)

### Other extensions used

hiçbiri 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/150393543/bfcc046a-1bb6-4a70-978e-9f78d5bcefae)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 105941
 cosmetic: 53976
 scriptlet: 20494
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  TUR-0: 13849-10, 36m
  easylist: 75175-37, 36m
  easyprivacy: 32854-69, 36m
  plowe-0: 3722-1075, 36m
  ublock-badware: 7435-135, 36m
  ublock-filters: 35231-158, 36m
  ublock-privacy: 663-5, 36m
  ublock-quick-fixes: 153-90, 36m
  ublock-unbreak: 2135-33, 36m
  urlhaus-1: 10950-0, 36m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 979 ms (selfie)
 maxAssetCacheWait: 320 ms
popupPanel:
 blocked: 2
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?\"\}\}\}\]\…
  ##+js(trusted-replace-fetch-response, /((?:hqdefault\.jpg\?sqp=-…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?"\}\}\}\]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19976
