### ISSUE TITLE
kimcartoon.li: ads

### ISSUE THREAD

**Issue by IceNinja2017** [uBlockOrigin/uAssets#20577]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kimcartoon.li/`

### Category

ads

### Description

There is a leftover add that keeps showing up on the bottom left corner of the kimcartoon(dot)li website

### Other extensions used

FIrefox addons used:

- Privacy Badger
- Dark Reader
- Cookie-Editor
- Simple Translator
- Search by Image

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (18)](https://github.com/uBlockOrigin/uAssets/assets/67907944/a42db135-8fa3-45a7-a1e0-60388d0d585f)

</details>
it's at the bottom left part of the webpage

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104851
 cosmetic: 43446
 scriptlet: 18714
 html: 1098
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36118-240, now
  ublock-badware: 7439-5, now
  ublock-privacy: 658-0, now
  ublock-unbreak: 2187-1, now
  ublock-quick-fixes: 151-7, now
  easylist: 75176-593, now
  easyprivacy: 32855-725, now
  urlhaus-1: 11525-0, now
  plowe-0: 3722-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 333 ms (selfie)
 maxAssetCacheWait: 114 ms
popupPanel:
 blocked: 14
 network:
  bidgear.com: 2
  customladvertis.org: 1
  d2er1uyk6qcknh.cloudfront.net: 3
  dthepeoplewhoc.org: 5
  googletagmanager.com: 1
  pogothere.xyz: 2
 extended:
  ##div[style*="width: 300px; height: 250px"]
  ##+js(no-window-open-if)
  ##+js(abort-current-script, $, adbWarn)
  ##+js(abort-on-property-write, Fingerprint2)
  ##+js(remove-node-text, script, Number.isSafeInteger)
```
</details>

**Comment by astolfoismywaifu** [comment]
Fixable with Adguard ad filter
