### ISSUE TITLE
otomoto.pl: breakage

### ISSUE THREAD

**Issue by rkindzierski** [uBlockOrigin/uAssets#20580]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.otomoto.pl/osobowe`

### Category

breakage

### Description

The advanced filter list is not loading on the page (with an error in its place). Whenever advanced filter is loaded, it is not usable (inputs are not usable)

### Other extensions used

- Ghostery
- HTTPS Everywhere
- Return Youtube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Zrzut ekranu 2023-11-10 114144](https://github.com/uBlockOrigin/uAssets/assets/72692634/01b007f1-a213-45b2-bddf-a3681bf11acd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 106266
 cosmetic: 51023
 scriptlet: 18920
 html: 1109
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36131-186, now
  ublock-badware: 7439-5, now
  ublock-privacy: 658-0, now
  ublock-unbreak: 2192-0, now
  easylist: 75176-715, now
  easyprivacy: 32855-725, now
  urlhaus-1: 11525-0, 46m
  plowe-0: 3722-1, now
  POL-0: 8008-27, 45m
  POL-2: 1279-12, now
  ublock-quick-fixes: 165-8, now
filterset (user): [empty]
trustedset:
 added: [array of 24 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 760 ms (selfie)
 maxAssetCacheWait: 155 ms
popupPanel:
 blocked: 6
 network:
  cookielaw.org: 1
  criteo.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  sentry.io: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
Did you try disabling

```
Ghostery
HTTPS Everywhere

```
?

**Comment by rkindzierski** [comment]
I did some additional tests in incognito mode where I enabled one extension per site reload. It seems that problem occur only with HTTPS Everywhere. 
Sorry for raising an issue with uBlock!
