### ISSUE TITLE
rutracker.org: ads

### ISSUE THREAD

**Issue by Windree** [uBlockOrigin/uAssets#20588]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://rutracker.org/forum/index.php`

### Category

ads

### Description

Banner on top and left

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/57554809/494565b6-d695-4ce3-b298-4142fb07330d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 105044
 cosmetic: 43460
 scriptlet: 18717
 html: 1098
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 36139-252, now
  ublock-badware: 7447-5, now
  ublock-privacy: 659-0, now
  ublock-unbreak: 2194-1, now
  easylist: 75176-551, now
  easyprivacy: 32855-767, now
  urlhaus-1: 11695-0, now
  plowe-0: 3722-1, now
  ublock-quick-fixes: 165-7, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 220 ms (selfie)
 maxAssetCacheWait: 77 ms
popupPanel:
 blocked: 6
 network:
  advg.agency: 2
  cloudflareinsights.com: 2
  jsdelivr.net: 1
  yadro.ru: 1
 extended:
  ##a[href^="https://get.surfshark.net/aff_c?"][href*="&aff_id="] …
```
</details>

**Comment by mapx-** [comment]
enable the russian lists:
https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

RU AdList
RU AdList: Counters
