### ISSUE TITLE
[nsfw] watchomovies.beauty: popups

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#20589]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

**NSFW**
`https://watchomovies.beauty/`
`https://watchomovies.beauty/the-bucket-list-2023-season-1-part-1-ullu-originals-Watch-online-on-watchomovies/`

### Category

popups

### Description

opens unwanted tabs

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 121
filterset (summary):
 network: 106452
 cosmetic: 50959
 scriptlet: 18777
 html: 1099
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 36453-190, 1m
  ublock-badware: 7441-5, 1m
  ublock-privacy: 659-0, 1m
  ublock-unbreak: 2199-1, 1m
  ublock-quick-fixes: 165-7, 1m
  adguard-mobile: 8850-100, 1m
  easylist: 75176-745, 1m
  easyprivacy: 32855-731, 1m
  urlhaus-1: 11695-0, 1m
  plowe-0: 3722-1, 1m
filterset (user): [array of 2 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 538 ms (selfie)
 maxAssetCacheWait: 201 ms
popupPanel:
 blocked: 10
 network:
  adsco.re: 1
  betteradsystem.com: 1
  d2kk0o3fr7ed01.cloudfront.net: 1
  google.com: 2
  lsukzeatonsq.com: 1
  sharethis.com: 2
  ssindserving.com: 2
 extended:
  ##.content-kuss-ads
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

### Notes
race condition, following works
`*$script,3p,domain=watchomovies.*,denyallow=googleapis.com|jquery.com|sharethis.com|twitter.com`
or
`watchomovies.*##+js(rmnt, script, onerror)`

**Comment by BlazeFTL** [comment]
Should Fix
```
||houdkovu.com^$script,domain=watchomovies.*
watchomovies.*##+js(aopw, _pop)
