### ISSUE TITLE
apps.quanticfoundry.com: breakage

### ISSUE THREAD

**Issue by spkyalstr** [uBlockOrigin/uAssets#20584]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://apps.quanticfoundry.com/recommendations/gamerprofile/videogame/`

### Category

breakage

### Description

generate button doesn't work with ublock origin enabled

### Other extensions used

dark reader, sponsorblock, fastforward, return youtube dislikes, youtube enhancer, i still don't care about cookies, idm, windscribe plugin

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![su](https://github.com/uBlockOrigin/uAssets/assets/150452150/7437a518-6fcd-4082-8b0d-efbb78d5b0ad)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 354623
 cosmetic: 364502
 scriptlet: 51425
 html: 1425
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79454-8315, 1m
  adguard-mobile: 8850-144, 1m
  adguard-spyware-url: 1310-88, 1m
  adguard-spyware: 62228-17045, 1m
  block-lan: 54-0, 1m
  curben-phishing: 77751-34, 1m
  adguard-social: 22021-871, 1m
  adguard-cookies: 28027-72, 1m
  adguard-popup-overlays: 25981-1601, 1m
  adguard-mobile-app-banners: 4735-1070, 1m
  adguard-other-annoyances: 13768-321, 1m
  adguard-widgets: 2342-1, 1m
  [47 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36128-750, 1m
  ublock-badware: 7447-5, 1m
  ublock-privacy: 659-0, 1m
  ublock-unbreak: 2194-2, 1m
  ublock-quick-fixes: 165-7, 1m
  easylist: 75176-1397, 1m
  easyprivacy: 32855-1055, 4m
  urlhaus-1: 11695-0, 1m
  plowe-0: 3722-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 388 ms (selfie)
 maxAssetCacheWait: 298 ms
popupPanel:
 blocked: 4
 network:
  addtoany.com: 1
  googletagmanager.com: 1
  newrelic.com: 2
 extended:
  ##a[href="https://www.addtoany.com/share"]
  ##.a2a_floating_style
  ##.cc-type-info
```
</details>

**Comment by mapx-** [comment]
try disabling windscribe and test again

**Comment by spkyalstr** [comment]
> try disabling windscribe and test again

already did, i tested with another browser that only had ublock

**Comment by mapx-** [comment]
> [47 lists not shown]: [too many]

reset uBO to default lists / settings, test again.
If does work => add 1 by 1 other lists you want to use and repeat the test => you'll find the "bad" one => report back

**Comment by gorhill** [comment]
Confirmed, unable to reproduce using default settings/lists and with uBO as the only extension.
