### ISSUE TITLE
[nsfw] aylink.co: ads

### ISSUE THREAD

**Issue by umut-nb0** [uBlockOrigin/uAssets#20597]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aylink.co/artere`

### Category

ads

### Description

This short link takes you to `mega.nz`
similar issue: https://github.com/uBlockOrigin/uAssets/issues/20083

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/147916475/a05946b1-465b-46b9-9429-48ab71e0dbd1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 106453
 cosmetic: 53967
 scriptlet: 20348
 html: 1097
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36130-149, now
  ublock-badware: 7447-5, now
  ublock-privacy: 659-0, now
  ublock-unbreak: 2194-1, now
  ublock-quick-fixes: 171-7, now
  easylist: 75225-720, now
  easyprivacy: 32859-730, now
  urlhaus-1: 11425-0, now
  plowe-0: 3723-1, now
  TUR-0: 13807-12, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4022 ms
 maxAssetCacheWait: 162 ms
popupPanel:
 blocked: 2
 network:
  amung.us: 1
  jsdelivr.net: 1
 extended:
  ##.alternative-ad
  ##.ad-link:not(.adsbox)
  #@#.ad-link
  ##+js(abort-on-property-read, xmlhttp)
  ##+js(adjust-setInterval)
  ##+js(remove-attr, data-ppcnt_ads|onclick, #main)
```
</details>

**Comment by punisher018** [comment]
Showing ads and opening pop ups.

**Comment by punisher018** [comment]
@ghajini Not exactly. The pop-up window opens again.

**Comment by punisher018** [comment]
Yes, that's the link destination for the link you mentioned.
There are many links with this shortening address here if needed.  
`https://trendlinkler.com/kategori/oyun-indirme`

**Comment by punisher018** [comment]
@ghajini it's ok now. Thanks. Maybe these can be added.

`trendlinkler.com###toasts`
`trendlinkler.com###esosyal-video`
