### ISSUE TITLE
click-me.today: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20593]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://click-me.today/preschool/coloring-pages`

### Category

detection

### Description

The site detects uBO with an overlay that you cannot close. There is also a red alert box to get a membership to remove ads near the bottom of the page.

These filters seem to work by removing the overlay and alert box.

```
@@||click-me.today^$ghide
click-me.today##.alert-danger.alert
```

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screen Shot 2023-11-10 at 5 17 42 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/57e6e31e-082b-4828-b8c8-d1e07aa14cd5">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 105378
 cosmetic: 45006
 scriptlet: 22854
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5768-9, 3m
 default:
  user-filters: 42-2, never
  easylist: 75220-16, 3m
  easyprivacy: 32859-64, 3m
  plowe-0: 3723-1074, 3m
  ublock-badware: 7443-135, 3m
  ublock-filters: 35252-151, 3m
  ublock-privacy: 665-5, 2m
  ublock-quick-fixes: 164-103, 2m
  ublock-unbreak: 2148-33, 2m
  urlhaus-1: 11695-0, 2m
filterset (user): [array of 40 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 222 ms (selfie)
 maxAssetCacheWait: 101 ms
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  sharethis.com: 2
 extended:
  ##ins.adsbygoogle
  ##.ad-text
  ##.adSense
  ##.adBlock
  ##.adContent
```
</details>

**Comment by Sintayew4** [comment]
#20593
