### ISSUE TITLE
pobreflix.biz: breakage

### ISSUE THREAD

**Issue by daveox** [uBlockOrigin/uAssets#20594]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pobreflix.biz/episodios/assistir-the-last-of-us-1x1-online/`

### Category

breakage

### Description

It requires clicking an ad to watch a movie/series and there are no visible ads since the default filters are enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 114
filterset (summary):
 network: 104819
 cosmetic: 43483
 scriptlet: 18880
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  spa-1: null
 default:
  easylist: 75225-16, 29m
  easyprivacy: 32859-64, 29m
  plowe-0: 3723-1074, 23m
  ublock-badware: 7443-135, 28m
  ublock-filters: 35254-151, 20m
  ublock-privacy: 665-5, 28m
  ublock-quick-fixes: 164-99, 28m
  ublock-unbreak: 2148-32, 28m
  urlhaus-1: 11425-0, 36m
filterset (user): [array of 184 redacted]
trustedset:
 added: [array of 10 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 522 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 483 ms
 maxAssetCacheWait: 208 ms
popupPanel:
 blocked: 3
 network:
  aj2550.bid: 1
  floitcarites.com: 1
  waust.at: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by mapx-** [comment]
@stephenhawk8054 Brazil
