### ISSUE TITLE
ads on geektime.co.il

### ISSUE THREAD

**Issue by almog123** [uBlockOrigin/uAssets#206]
http://chameleonx.com/ ads on geektime.co.il

they say you have the option to "opt-out" but the ads keep coming back after some days.

I hate those ads, please help me with that.

I've downloaded Adblock in order to remove the ads, but they keep coming back.

reported to HebrewList which don't want to help in this case: easylist/EasyListHebrew#208

**Comment by gorhill** [comment]
Can't help you: you do not provide any details about what **exactly** is the issue. Generic, vague "remove ads!" does not help. Provide details, screenshots, etc. and keep in mind most likely people here know nothnig about the site.

**Comment by almog123** [comment]
you are right, I am sorry.
ads are everywhere on http://geektime.co.il both in the homepage and innerpages.

here are some screenshots:
![geek1](https://cloud.githubusercontent.com/assets/17848148/20603825/01120464-b26c-11e6-8020-60a862aa9d4a.png)
![geek2](https://cloud.githubusercontent.com/assets/17848148/20603826/0142b19a-b26c-11e6-8e1a-862416fc5efe.png)

**Comment by almog123** [comment]
ads are coming from random urls such as:
http://www.geektime.co.il/wp-content/uploads/2010/jeiYYvyKYtnElHjFwZzkzkJEwvxx/LIAVwKiwVxUdyZpwkgziQGpBJ/ZuDxxXeAOFCvRU

**Comment by IDKwhattoputhere** [comment]
See if one of these filters works:
```
geektime.co.il##a[href^="/wp-includes/"]
geektime.co.il##a[href^="/wp-content/uploads/"]
```

**Comment by almog123** [comment]
sorry but it didn't help, ads are now back again, it worked for 1 day.

**Comment by IDKwhattoputhere** [comment]
Those filters left half of the ads untouched for me. Are all ads gone on your side?
This worked for me:
`geektime.co.il##a[target="_blank"]`
Can't tell if it's causing false positives though. Please try it and reply here.

**Comment by gorhill** [comment]
@almog123 what browser/version are you using?
