### ISSUE TITLE
9animetv.to: ads

### ISSUE THREAD

**Issue by Xathvik** [uBlockOrigin/uAssets#20602]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://9animetv.to/`

### Category

ads, popups

### Description

Pop-ups to crypto sites

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104810
 cosmetic: 43488
 scriptlet: 18731
 html: 1097
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36143-248, now
  ublock-badware: 7447-5, now
  ublock-privacy: 661-0, now
  ublock-unbreak: 2194-1, now
  ublock-quick-fixes: 171-7, now
  easylist: 75227-551, now
  easyprivacy: 32865-767, now
  urlhaus-1: 11425-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 720 ms (selfie)
 maxAssetCacheWait: 214 ms
popupPanel:
 blocked: 6
 network:
  googletagmanager.com: 1
  outoctillerytor.com: 1
  sentry.io: 3
  zendesk.com: 1
 extended:
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
- anime apk is self promotion
- I get only an overlay, add:

`9animetv.to##[href^="//keefeezo.net/"]`
