### ISSUE TITLE
linkspy.cc: popups

### ISSUE THREAD

**Issue by somethinggm** [uBlockOrigin/uAssets#20605]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://linkspy.cc/tr/aHR0cHM6Ly9zaHJpbmtlYXJuLmNvbS9mdWxsP2FwaT01MTZmZGU0MTg1MGRhYTYyNjZkZjQyMDZjMzg0OWI2MzkyODU5ZjJlJnVybD1hSFIwY0hNNkx5OTNkM2N1Wm1sc1pXTnllWEIwTG1OakwwTnZiblJoYVc1bGNpOUdORVpHUWpreU5qUTVMbWgwYld3PSZ0eXBlPTI=`

### Category

popups

### Description

Doesn't bypass ad page

### Other extensions used

- Sidebery
- Feedbro
- Dark Reader
- SponsorBlock 
- Old Reddit Redirec
- Reddit Enhancement Suite

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 119940
 cosmetic: 176150
 scriptlet: 30400
 html: 1291
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 2480-0, 23m
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 976-0, 26m
  adguard-spyware-url: 1310-195, now
  adguard-social: 22021-167, now
  adguard-cookies: 28030-46, now
  ublock-cookies-adguard: 529-0, now
  adguard-popup-overlays: 25985-973, now
  adguard-mobile-app-banners: 4735-9, now
  adguard-other-annoyances: 13769-63, now
  adguard-widgets: 2342-2, now
  fanboy-cookiemonster: 48842-3891, now
  ublock-cookies-easylist: 529-529, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 36149-512, now
  ublock-badware: 7447-5, now
  ublock-privacy: 661-47, now
  ublock-unbreak: 2195-2, now
  ublock-quick-fixes: 171-7, now
  easylist: 75227-822, now
  easyprivacy: 32865-746, now
  urlhaus-1: 11425-0, 25m
  plowe-0: 3723-1, now
  spa-0: 3767-3, 24m
  spa-1: 5727-175, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 362 ms (selfie)
 maxAssetCacheWait: 107 ms
popupPanel:
 blocked: 3
 network:
  citizenhid.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##+js(set-constant, displayAds, 0)
```
</details>

**Comment by gorhill** [comment]
I am unable to reproduce popups using default lists/settings.

**Comment by dportvine** [comment]
I can't pass Cloudflare verification. `*$frame,domain=shrinkearn.com,3p`

<details>
<summary>Screen</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/d32a4b9c-de01-4da4-b675-836f59618d23
</details>
