### ISSUE TITLE
meetup.com: breakage

### ISSUE THREAD

**Issue by gcristof** [uBlockOrigin/uAssets#20612]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Performing a search on meetup.com fails while logged into my meetup.com account. This is happening even though I specifically excluded meetup.com from uBO. Also, weirdly it only happens when I'm logged into my meetup account, if I log out and perform the search anonymously it works ok. I've reproduced this problem dozens of times for several days. 
It may not have started with the latest uBO update - the issue had been going on for some time but I only just now realized that the problem goes away when I disable the uBO firefox extension. 

### A specific URL where the issue occurs.

`https://www.meetup.com/find/`

### Steps to Reproduce

1. Login to account at `www.meetup.com`
2. Leave the search field blank (when something is entered there, the search works fine)
3. enter a city or zip and select it from dropdown.
4. Click the red search button

https://github.com/uBlockOrigin/uBlock-issues/assets/3662980/557d7884-b666-4b9e-bb66-61b21efc331e

### Expected behavior

The search should return results of nearby meetup events. It does work correctly when uBO extension is disabled.
https://github.com/uBlockOrigin/uBlock-issues/assets/3662980/115bc23d-345d-4a41-91d1-059efed920f

### Actual behavior

Error page. This occurs even when meetup.com is in uBO's exclude list.
https://github.com/uBlockOrigin/uBlock-issues/assets/3662980/b9e36981-bd4c-416a-9d09-a038952bab5b

### uBO version

1.53.0

### Browser name and version

Firefox 119.0.1 (64-bit)

### Operating System and version

Linux Mint 21.2

**Comment by mapx-** [comment]
- go into uBO dashboard, support tab, copy & paste here the `Troubleshooting Information`
