### ISSUE TITLE
kayak.com: ads

### ISSUE THREAD

**Issue by loganrosen** [uBlockOrigin/uAssets#20619]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kayak.com/flights/NYC-LAX/2023-12-25/2023-12-29?sort=bestflight_a&fs=cfc=1`

### Category

ads

### Description

There are ads in the search results.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="942" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/512317/d83edf01-2402-47ae-9a41-847ef4978e1b">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104215
 cosmetic: 43490
 scriptlet: 18733
 html: 1097
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36148-48, now
  ublock-badware: 7447-5, now
  ublock-privacy: 662-0, now
  ublock-unbreak: 2194-2, now
  ublock-quick-fixes: 173-101, now
  easylist: 75229-700, now
  easyprivacy: 32866-725, now
  urlhaus-1: 10825-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 156 ms (selfie)
 maxAssetCacheWait: 47 ms
popupPanel:
 blocked: 18
 network:
  kayak.com: 8
  activemetering.com: 1
  affirm.com: 5
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  usabilla.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
Try In My Filters 
`kayak.com##.SnackerAdWrapper, .InlineAd`

**Comment by huyszn** [comment]
Or try these filters:
```
kayak.com##.resultsList > div > div > div > div.G-5c[role="tab"][tabindex="0"]
kayak.com##.resultsList > div > div > div > div.PzK0[role="button"][tabindex="0"]
```

**Comment by mapx-** [comment]
add

```
kayak.com##[role="tab"]:has([class*="sponsored"])
kayak.com##[role="button"]:has([class*="ad-marking"])
```

@ryanbr
