### ISSUE TITLE
[nsfw] radiolize.com: detection

### ISSUE THREAD

**Issue by shmelvspb** [uBlockOrigin/uAssets#20617]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://radiolize.com/`

### Category

detection

### Description

Hello! The support widget on this site cannot be disabled :( what should I do?

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 121565
 cosmetic: 64695
 scriptlet: 20243
 html: 0
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 76-0, now
 default:
  user-filters: 28-11, never
  RUS-0: 40101-10, 1h.42m
  easylist: 75176-42, 1h.44m
  easyprivacy: 32855-154, 1h.43m
  plowe-0: 3723-1078, now
  ublock-badware: 7443-135, now
  ublock-filters: 35262-178, now
  ublock-privacy: 668-81, now
  ublock-quick-fixes: 176-101, 1h.40m
  ublock-unbreak: 2148-32, now
  urlhaus-1: 10825-0, 1h.41m
filterset (user): [array of 28 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 525 ms (selfie)
 maxAssetCacheWait: 322 ms
popupPanel:
 blocked: 3
 network:
  radiolize.com: 1
  cloudflareinsights.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
Do You Mean The Support Button At Bottom ?
Try In My Filters
`||api.anychat.one^$domain=radiolize.com`

**Comment by mapx-** [comment]
> detection

do we need an account to see the detection ? 

> The support widget on this site cannot be disabled

what does that have to do with the "detection" ?

Screenshot ?

**Comment by dportvine** [comment]
@shmelvspb 

This? It's not detection, it's a nuisance.

<details>
<summary>Screen</summary>

![2023-11-12_173028](https://github.com/uBlockOrigin/uAssets/assets/111344219/b7fd4bb3-5e77-4f08-8cd7-d74b108395f8)
</details>


@ryanbr 

`||anychat.one/widget^` for  **EasyList – Chat Widgets** ?
