### ISSUE TITLE
star-rail-map.appsample.com: detection

### ISSUE THREAD

**Issue by erpmario** [uBlockOrigin/uAssets#20616]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://star-rail-map.appsample.com/`

### Category

detection

### Description

This site loads normally at first, but after a few seconds it completely wipes the screen to white. Investigating the DOM reveals the site is literally just deleting all elements. Disabling uBO allows the ad in the bottom-right corner to be shown and does not result in a blank screen.

### Other extensions used

LastPass
Mendeley Web Importer
Malwarebytes
Google Scholar

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Before Wipe](https://github.com/uBlockOrigin/uAssets/assets/34783705/466ce200-e745-49f9-a945-e3e48edede94)
Site appears normal at first.

![After Wipe](https://github.com/uBlockOrigin/uAssets/assets/34783705/4b1bd5d3-b4b7-4bbf-9f40-68ef38a88c6d)
Then it becomes a fully white screen.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 116
filterset (summary):
 network: 104217
 cosmetic: 43485
 scriptlet: 18884
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 75226-16, 20m
  easyprivacy: 32855-64, 20m
  plowe-0: 3723-1074, 20m
  ublock-badware: 7443-135, 20m
  ublock-filters: 35244-151, 20m
  ublock-privacy: 668-5, 20m
  ublock-quick-fixes: 176-98, 20m
  ublock-unbreak: 2148-32, 20m
  urlhaus-1: 10825-0, 20m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 594 ms
 maxAssetCacheWait: 8 ms
popupPanel:
 blocked: 2
 no-cosmetic-filtering: true
 network:
  googletagmanager.com: 1
  nitropay.com: 1
```
</details>

**Comment by mapx-** [comment]
- try disabling first Malwarebytes, test again
- if still does not work disable all other extensions, reset uBO to default settings / lists

**Comment by erpmario** [comment]
Strangely, yes, disabling Malwarebytes prevents the screen from wiping. Instead, a placeholder image appears in the bottom-right where the ad would normally go (and where the blacked-out rectangle was in my original screenshot).
![image](https://github.com/uBlockOrigin/uAssets/assets/34783705/855582a2-b1aa-4c69-8164-24f9052d4562)
I'm unclear on whether this is an issue with Malwarebytes or uBO. Evidently they're interacting in a weird way, as running either of them in isolation does not cause a screen wipe.

**Comment by mapx-** [comment]
whitelist the page in Malwarebytes
