### ISSUE TITLE
gauchazh.clicrbs.com.br: nuisance

### ISSUE THREAD

**Issue by leomouracp** [uBlockOrigin/uAssets#20615]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gauchazh.clicrbs.com.br/mundo/noticia/2023/11/grupos-estudantis-suspensos-por-guerra-em-gaza-denunciam-censura-de-universidade-nos-eua-clouhd4si003q01j02kf3ltp1.html`

### Category

nuisance

### Description

custom pay window

### Other extensions used

same ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 116934
 cosmetic: 198145
 scriptlet: 30289
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28030-31, 6m
  adguard-mobile-app-banners: 4737-9, 6m
  adguard-other-annoyances: 13771-8, 6m
  adguard-popup-overlays: 25985-68, 6m
  adguard-social: 22021-926, 6m
  adguard-widgets: 2342-3, 6m
  easylist-annoyances: 4170-203, 6m
  easylist-chat: 150-11, 6m
  easylist-newsletters: 6635-431, 6m
  easylist-notifications: 2872-1452, 6m
  fanboy-cookiemonster: 48837-3844, 6m
  fanboy-social: 16190-729, 6m
  [4 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 75229-76, 6m
  easyprivacy: 32866-179, 6m
  plowe-0: 3723-1075, 6m
  spa-1: 5727-71, 6m
  ublock-badware: 7443-135, 7m
  ublock-filters: 35262-533, 7m
  ublock-privacy: 668-10, 7m
  ublock-quick-fixes: 176-105, 7m
  ublock-unbreak: 2148-37, 7m
  urlhaus-1: 10825-0, 6m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 640 ms (selfie)
 maxAssetCacheWait: 283 ms
popupPanel:
 blocked: 15
 network:
  chartbeat.com: 1
  cxense.com: 1
  doubleclick.net: 1
  getsitecontrol.com: 1
  google-analytics.com: 1
  googletagmanager.com: 3
  mrf.io: 1
  navdmp.com: 1
  npttech.com: 1
  onesignal.com: 1
  privacytools.com.br: 1
  solucx.com.br: 1
  taboola.com: 1
 extended:
  ###fb-root:not(body):not(html)
  ##.m-share
  ###taboola-right-rail
  ##.ads-card
  ##.ad-floating
  ##.player-ad
  ##a[href="https://campanha.assinanterbs.com.br/newsletter/"]
  ###privacy-tools-banner
  ##.ads-section-area
  ##.ad-container
  ##.m-advertising
  ##a[href^="whatsapp://send"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
```
</details>

**Comment by mapx-** [comment]
It's a paywall, we do not circumventing it in our lists.
Use this as custom filter
`||cdn.piano.io/api/tinypass.min.js$script,domain=gauchazh.clicrbs.com.br`

**Comment by D4niloMR** [comment]
@leomouracp
https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/issues/107
