### ISSUE TITLE
jornaljoca.com.br: nuisance

### ISSUE THREAD

**Issue by D4niloMR** [uBlockOrigin/uAssets#20618]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jornaljoca.com.br/gatos-interagem-usando-257-expressoes-faciais-diferentes-aponta-estudo/`

### Category

nuisance

### Description

anti right click, anti-selection and modifies copy

```adb
jornaljoca.com.br##style:has-text(unselectable):remove()
jornaljoca.com.br##+js(aopw, nocontext)
jornaljoca.com.br##+js(aopr, disableSelection)
jornaljoca.com.br##+js(aeld, copy)
```

Just for test add this: `jornaljoca.com.br##+js(acs, $, paywall)` 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.1rc0
Chromium: 116
filterset (summary):
 network: 157699
 cosmetic: 131130
 scriptlet: 29560
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 972-0, 1h.21m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2481-0, now
  adguard-other-annoyances: 13771-6, now
  adguard-spyware: 62233-133, now
  easylist-annoyances: 4170-94, now
  easylist-chat: 150-1, now
  easylist-newsletters: 6635-22, now
  easylist-notifications: 2872-281, now
  fanboy-cookiemonster: 48837-231, now
  fanboy-social: 16190-16, now
  ublock-annoyances: 5811-134, now
  ublock-cookies-easylist: 528-528, now
 default:
  user-filters: 88-0, never
  easylist: 75229-82, now
  easyprivacy: 32866-16511, now
  plowe-0: 3723-1158, now
  spa-1: 5727-70, now
  ublock-badware: 7443-135, now
  ublock-filters: 35267-513, now
  ublock-privacy: 668-147, now
  ublock-quick-fixes: 176-105, now
  ublock-unbreak: 2148-87, now
  urlhaus-1: 10825-0, now
filterset (user): [array of 53 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 583 ms (selfie)
 maxAssetCacheWait: 200 ms
popupPanel:
 blocked: 5
 network:
  jornaljoca.com.br: 1
  d335luupugsy2.cloudfront.net: 3
  onesignal.com: 1
 extended:
  ##.zmdi-youtube-play
  ##.zmdi-instagram
  ##.post__share
  ##.email-share
  ###cookie-law-info-bar ~ .cli-modal-backdrop
  ###cookie-law-info-again
  ###cookie_hdr_showagain
  ###cliSettingsPopup
```
</details>

**Comment by mapx-** [comment]
enabling the `print` too

`jornaljoca.com.br##style:has-text(@media print):remove()`
