### ISSUE TITLE
Notion.so: Cookie notification

### ISSUE THREAD

**Issue by Ardub92** [uBlockOrigin/uAssets#20611]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.notion.so`

### Description

Notion.so cookie notification.

Picker:
`##.notion-default-overlay-container.notion-overlay-container > div > div > div`

### Other extensions used

Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![vivaldi_n1uqvYc0mA](https://github.com/uBlockOrigin/uAssets/assets/35745292/0788da76-1ab4-4612-887d-d9837c686841)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 115431
 cosmetic: 194240
 scriptlet: 29834
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-cookies: 28024-31, 1d.22h.28m
  adguard-mobile-app-banners: 4735-9, 1d.22h.30m
  adguard-other-annoyances: 13765-8, 1d.22h.26m
  adguard-popup-overlays: 25976-68, 1d.22h.25m
  adguard-social: 22012-926, 1d.22h.27m
  adguard-widgets: 2342-3, 1d.22h.29m
  easylist-annoyances: 4169-203, 1d.2h.14m
  easylist-chat: 150-11, 1d.2h.14m
  easylist-newsletters: 6633-431, 1d.2h.14m
  easylist-notifications: 2872-1451, 1d.2h.14m
  fanboy-cookiemonster: 48827-3846, 1d.2h.14m
  fanboy-social: 16169-743, 8d.8h.37m
  [4 lists not shown]: [too many]
 default:
  easylist: 75145-76, 3d.6h.22m
  easyprivacy: 32843-180, 4d.28m
  plowe-0: 3721-1073, 8d.6h.33m
  ublock-badware: 7443-135, 8m
  ublock-filters: 35265-506, 8m
  ublock-privacy: 665-7, 3h.33m
  ublock-quick-fixes: 164-103, 7h.34m
  ublock-unbreak: 2149-36, 8m
  urlhaus-1: 10825-0, 1h.32m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 26932 ms (selfie)
 maxAssetCacheWait: 386 ms
popupPanel:
 blocked: 15
 network:
  sentry.io: 12
  splunkcloud.com: 3
 extended:
  ##+js(set-cookie, notion_cookie_consent, 0)
  ##+js(set-cookie, notion_check_cookie_consent, true)
  ##+js(trusted-set-cookie, notion_cookie_consent, {%22id%22:%2282…
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`
