### ISSUE TITLE
cadenaser.com: breakage

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#20628]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cadenaser.com/audio/1689759708501/`

### Category

breakage

### Description

The podcast doesn't play when uBlock Origin is enabled.

### Other extensions used

```
ahfgeienlihckogmohjhadlkjgocpleb : Chrome Web Store : version 0_2
cjpalhdlnbpafiamejdnhcphjbkeiagm : uBlock Origin : version 1_53_0
cnpniohnfphhjihaiiggeabnkjhpaldj : Image Downloader : version 3_4_0
dnhpnfgdlenaccegplpojghhmaamnnfp : Augmented Steam : version 2_6_0
donbcfbmhbcapadipfkeojnmajbakjdc : Ruffle - Flash Emulator : version 0_1_0_1024
efkkjffdefaaioagghcaflicdajfhceo : Web Timer : version 1_4_9
eignhdfgaldabilaaegmdfbajngjmoke : Black Menu for Google™ : version 25_30_2
emehklffcaphknhhfhadkjhpfapcbpco : Strong Password Generator : version 1_6
eokjikchkppnkdipbiggnmlkahcdkikp : Herramienta de selección de color - Geco : version 1_0_6
gddbgllpilhpnjpkdbopahnpealaklle : descargador de videos - CocoCut : version 3_14
gppongmhjkpfnbhagpmjfkannfbllamg : Wappalyzer - Technology profiler : version 6_10_67
hdghceafmahkdiaoenecabpfokplecfi : Black Menu for Wikipedia : version 5_16_3
ibkoenhablealnikeefmjineccmgegmh : Bitdefender Password Manager : version 1_3_0
icncamkooinmbehmkeilcccmoljfkdhp : Wolfram|Alpha (Official) : version 2_0
idmnciiknelklflhdlnkokcoihkidkln : Dark Space : version 2
ifbmcpbgkhlpfcodhjhdbllhiaomkdej : Copiar y pegar de Office Online : version 0_1_11_5
jgjaeacdkonaoafenlfkkkmbaopkbilf : ChatGPT for Google : version 4_3_2
jjicbefpemnphinccgikpdaagjebbnhg : CSFloat Market Checker : version 3_2_0
johejpedmdkeiffkdaodgoipdjodhlld : Chessvision.ai Chess Position Scanner : version 3_4_1
kdbmhfkmnlmbkgbabkdealhhbfhlmmon : SteamDB : version 3_7_6
llimhhconnjiflfimocjggfjdlmlhblm : Reader Mode : version 1_3_3
lpcaedmchfhocbbapmcbpinfpgnhiddi : Extensión de Google Keep para Chrome : version 4_23442_540_1
mcbpblocgmgfnpjjppndjkmgjaogfceg : Captura de página completa - FireShot : version 1_12_18
mfengiknfnndchbhjmgjjffjndklkpcm : Remove YouTube End Cards & End Screen Videos : version 1_0_4
mffmjlddchdccijipncbjhoabgmphjfb : Vimego - Descargador de videos de Vimeo™ : version 1_5_29
mhjfbmdgcfjbbpaeojofohoefgiehjai : Chrome PDF Viewer : version 1
mmioliijnhnoblpgimnlajmefafdfilb : Shazam: identifica música desde tu navegador : version 2_1_1
mmpokgfcmbkfdeibafoafkiijdbfblfg : Merge Windows : version 1_5_0_0
mnjggcdmjocbbbhaepdhchncahnbgone : SponsorBlock para YouTube - Omitir Sponsors : version 5_4_27
neajdppkdcdipfabeoofebfddakdcjhd : Google Network Speech : version 1_0
nkeimhogjdpnpccoofpliimaahmaaome : Google Hangouts : version 1_3_21
nmmhkkegccagdldgiimedpiccmgmieda : Sistema de pagos de Chrome Web Store : version 1_0_0_6
nnpljppamoaalgkieeciijbcccohlpoh : Link Redirect Trace : version 1_0_0_0
oeopbcgkkoapgobdbedcemjljbihmemj : Checker Plus for Gmail™ : version 24_3_4
ponfpcnoihfmfllpaingbgckeeldkhle : Enhancer for YouTube™ : version 2_0_121
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 106651
 cosmetic: 49812
 scriptlet: 19306
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 7-3, never
  easylist: 75238-16, now
  easyprivacy: 32873-64, now
  plowe-0: 3723-1074, now
  spa-0: 3767-19, now
  spa-1: 5727-225, now
  ublock-badware: 7443-135, now
  ublock-filters: 35267-177, now
  ublock-privacy: 668-5, now
  ublock-quick-fixes: 178-102, now
  ublock-unbreak: 2148-34, now
  urlhaus-1: 10735-0, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3778 ms (selfie)
 maxAssetCacheWait: 197 ms
popupPanel:
 blocked: 19
 network:
  cadenaser.com: 1
  amazon-adsystem.com: 1
  criteo.net: 2
  elpais.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  gstatic.com: 2
  imasdk.googleapis.com: 1
  mrf.io: 1
  prisasd.com: 1
  sensic.net: 1
  socy.es: 1
  streamtheworld.com: 1
  taboola.com: 1
  wemass.com: 1
  zeotap.com: 1
 extended:
  ##.cnt-publi
  ###player-ads
  ##.c-s > div
  ##.c-s > div:not([class]):first-child
  ##+js(set-constant, Object.prototype.adblockerEnabled, false)
```
</details>

**Comment by mapx-** [comment]
add

`@@||imasdk.googleapis.com/pal/sdkloader/pal.js$script,domain=cadenaser.com`

@ryanbr

**Comment by rodrigosambadesaa** [comment]
Good night,

In this [page of the site](https://cadenaser.com/usuarios/perfil/) the option to change the profile doesn't load when uBlock Origin is enabled.

**Comment by stephenhawk8054** [comment]
@rodrigosambadesaa Test again in a new browser profile with only uBO and its default settings first.

**Comment by rodrigosambadesaa** [comment]
Performed the required steps I can confirm that the issue is still there.

**Comment by stephenhawk8054** [comment]
In that new profile, can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by rodrigosambadesaa** [comment]
uBlock Origin: 1.57.0
Chromium: 125
filterset (summary):
 network: 137595
 cosmetic: 53455
 scriptlet: 21384
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38273-296, 57m
  ublock-badware: 8620-0, 57m
  ublock-privacy: 913-0, 46m Δ
  ublock-unbreak: 2278-2, 46m Δ
  ublock-quick-fixes: 151-0, 46m Δ
  easylist: 87330-604, 58m
  easyprivacy: 50936-822, 58m
  urlhaus-1: 12565-0, 58m
  plowe-0: 3726-0, 58m
  spa-0: 4063-3, 58m
  spa-1: 5647-187, 58m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 557 ms (selfie)
 maxAssetCacheWait: 54 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 29
 network:
  cadenaser.com: 2
  amazon-adsystem.com: 1
  ctnsnet.com: 2
  doubleclick.net: 2
  elpais.com: 1
  googlesyndication.com: 5
  mrf.io: 1
  omtrdc.net: 2
  prisasd.com: 1
  rlcdn.com: 2
  sensic.net: 1
  socy.es: 1
  streamtheworld.com: 1
  taboola.com: 1
  wemass.com: 1
  youborafds01.com: 4
  zeotap.com: 1
 extended:
  ###player-ads
  ##.c-s > div
  ##.c-s > div:not([class]):first-child
  ##+js(set-constant, Object.prototype.adblockerEnabled, false)

**Comment by stephenhawk8054** [comment]
Can you describe how to reproduce the issue? I accessed `https://cadenaser.com/usuarios/perfil/` and it looks like this

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/c4eecf8a-a162-4ec8-8df5-c7e37c5017cd)

I don't know what to do next.

**Comment by rodrigosambadesaa** [comment]
Opened new tab with that URL while logged in (I used Facebook log in method), clicked report button, copied the troubleshooting information.

**Comment by stephenhawk8054** [comment]
I mean how to reproduce the issue you said here?

> the option to change the profile doesn't load

What is missing in my screenshot above?

**Comment by rodrigosambadesaa** [comment]
I see this
![Captura de pantalla (28)](https://github.com/uBlockOrigin/uAssets/assets/43375046/8e585a69-2b26-4e43-9e65-ae3e8a20f4c7)

**Comment by stephenhawk8054** [comment]
Can you test this filter?

```adb
||elpais.com/pxlctl.gif$3p,image,redirect-rule=1x1.gif,domain=cadenaser.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by rodrigosambadesaa** [comment]
> Can you test this filter?
> 
> ```
> ||elpais.com/pxlctl.gif$3p,image,redirect-rule=1x1.gif,domain=cadenaser.com
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

Yes, will do now, did you see the last update of my last comment?

**Comment by rodrigosambadesaa** [comment]
With that filter the issue is solved. Thank you.

**Comment by stephenhawk8054** [comment]
cc @Yuki2718 For Adguard Spanish?
