### ISSUE TITLE
igg-games.com: breakage

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20623]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://igg-games.com/`

### Description

Image in the center is not shown, searching something on the search box doesn't work and gives a blank window.
It happens if `AdGuard – Ads` is enabled. It only occurs with uBO. It doesn't happen with Adgaurd's extension. That's why I'm reporting it here, hoping that something can be done about it. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/uBlockOrigin/uAssets/assets/29574622/319491ba-0f08-41f6-9972-fc5f200e0a38)
![2](https://github.com/uBlockOrigin/uAssets/assets/29574622/bba4f03c-5739-42bd-8a86-c34bcd65eaaf)
![3](https://github.com/uBlockOrigin/uAssets/assets/29574622/2dd6943b-dbd7-4e82-9a12-fd614608f2a2)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 122475
 cosmetic: 82404
 scriptlet: 34858
 html: 1097
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79676-6131, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 36148-48, 24m
  ublock-badware: 7447-5, 24m
  ublock-privacy: 662-0, 24m
  ublock-unbreak: 2194-2, 24m
  ublock-quick-fixes: 174-101, 24m
  easylist: 75237-700, 24m
  easyprivacy: 32872-725, 24m
  urlhaus-1: 10735-0, 23m
  plowe-0: 3723-1, 23m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1075 ms
 maxAssetCacheWait: 333 ms
popupPanel:
 blocked: 3
 network:
  a-ads.com: 1
  googletagmanager.com: 1
  runative-syndicate.com: 1
 extended:
  ##.widget_advads_ad_widget
  ###tm-sidebar div > a[rel] > img
  ##+js(abort-current-script, navigator, FingerprintJS)
  ##+js(abort-current-script, addEventListener, document.createEle…
  ##+js(abort-on-property-write, btoa)
  ##+js(remove-attr, srcdoc, iframe)
  ##+js(no-setTimeout-if, /divAds|_0x[\s\S]*?getElementsByTagName/…
  ##+js(abort-current-script, $, advads)
  ##+js(abort-current-script, String.fromCharCode, zfgloaded)
  ##+js(abort-on-stack-trace, Date, _0x)
  ##+js(abort-current-script, globalThis, break;case)
  ##+js(set-constant, advanced_ads_ready, noopFunc)
  ##+js(abort-on-property-write, bbHideDiv)

```
</details>

**Comment by okiehsch** [comment]
@SeriousHoax 
Add
`igg-games.com#@#+js(aost, Date, _0x)`
to your filter list.

@Yuki2718 is the filter still needed in AdGuard?

**Comment by Yuki2718** [comment]
Yes, still needed for AG. Will exclude uBO.
