### ISSUE TITLE
music.amazon.com: breakage

### ISSUE THREAD

**Issue by xander465** [uBlockOrigin/uAssets#20620]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://music.amazon.com/`

### Category

breakage

### Description

When i visited amazon just to get the link of the track from the music artist album but the more options or the three dot doesn't work, But when i disable uBlock now it work as it should.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 113085
 cosmetic: 45010
 scriptlet: 22892
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  dpollock-0: 11583-338, never
  ublock-annoyances: 5811-9, 12m
 default:
  user-filters: 10-0, never
  easylist: 75229-16, 12m
  easyprivacy: 32866-64, 12m
  ublock-badware: 7443-135, 12m
  ublock-filters: 35262-151, 12m
  ublock-privacy: 668-4, 12m
  ublock-quick-fixes: 176-105, 12m
  ublock-unbreak: 2148-33, 12m
  urlhaus-1: 10735-0, 12m
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 297 ms (selfie)
 maxAssetCacheWait: 150 ms
popupPanel:
 blocked: 2
 network:
  branch.io: 1
  rum.us-east-1.amazonaws.com: 1
 extended:
  ###overlay
  ##*:style(filter: none !important)
  ##+js(trusted-click-element, #dialogButton1)
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test any of these filters?

```adb
music.amazon.com#@##overlay
```

or/and

```adb
music.amazon.com#@#*:style(filter: none !important)
```

**Comment by xander465** [comment]
> Can you test any of these filters?
> 
> ```
> music.amazon.com#@##overlay
> ```
> 
> or/and
> 
> ```
> music.amazon.com#@#*:style(filter: none !important)
> ```

Okay now it works
Thank you for the help

**Comment by stephenhawk8054** [comment]
You need both filters or just the first/second one?

**Comment by xander465** [comment]
> You need both filters or just the first/second one?

the first one but the second doesn't work on mine

**Comment by xander465** [comment]
does someone has a solution at this new issue?

**Comment by peace2000** [comment]
More options:

![kuva](https://github.com/uBlockOrigin/uAssets/assets/17256841/f72b3baf-e2b8-4817-9898-6ba3416ed543)

These filters cause the issue:

`music.amazon.*###overlay:has(#dialog)`
`music.amazon.*##*:style(filter: none !important)`

So disabling them fixes it:
`music.amazon.*#@#*:style(filter: none !important)`
`music.amazon.*#@##overlay:has(#dialog)`

If I understand the Slack topic concerning this matter correctly, those filters are there because they quickly hide the GDPR dialog that visually appears... Even if it's clicked.

**Comment by peace2000** [comment]
Removed those filters https://github.com/uBlockOrigin/uAssets/commit/20aeeaaf230109ce9a974fcfae3e0f61546fbff4

**Comment by xander465** [comment]
> More options:
> 
> ![kuva](https://user-images.githubusercontent.com/17256841/284618715-f72b3baf-e2b8-4817-9898-6ba3416ed543.png)
> 
> These filters cause the issue:
> 
> `music.amazon.*###overlay:has(#dialog)` `music.amazon.*##*:style(filter: none !important)`
> 
> So disabling them fixes it: `music.amazon.*#@#*:style(filter: none !important)` `music.amazon.*#@##overlay:has(#dialog)`
> 
> If I understand the Slack topic concerning this matter correctly, those filters are there because they quickly hide the GDPR dialog that visually appears... Even if it's clicked.

Okay i romove the old and replace the filter that you create, now it work thank you

**Comment by peace2000** [comment]
Added this filter https://github.com/uBlockOrigin/uAssets/commit/af28faf0426d7852d0f0a5f77706c7a1d439884a

To quickly hide the dialog so that it won't visually appear. This shouldn't target any other dialogs except the GDPR dialog.

**Comment by krystian3w** [comment]
Hi, I see breakage after click play without logon:

`https://music.amazon.com/albums/B0DJHCWXT3`

I see only blur, but should be error messeage:

https://github.com/user-attachments/assets/7297c73f-2f9b-4d0f-abac-108aee89c40f

Bad now seems: `#overlay:has([href*="privacyprefs/"])` - not visible in logger table but in dom inspector exists.

**Comment by D4niloMR** [comment]
This works for me:

```adb
music.amazon.*##+js(trusted-click-element, #overlay > div > #banner:has([href*="privacyprefs/"]) music-button:last-of-type)
music.amazon.*###overlay > div > #banner:has([href*="privacyprefs/"])
```

**Comment by mapx-** [comment]
@krystian3w did you test the filters above ?

**Comment by krystian3w** [comment]
I have no idea, unfortunately, now it is more important for me to treat my kidneys, pancreas and liver, which makes it difficult to work at the computer (attacks of abdominal or back pain, diarrhea, bloating).
