### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by ShereeBrown** [uBlockOrigin/uAssets#20621]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=2le028R3xsE`

### Category

detection

### Description

This is the Real  problem I need help please YouTube put anti blocker this is unfair Please help 

### Other extensions used

I used uBlock Origin has failed

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<!-- ⬆️  

> 
![SharedScreenshot](https://github.com/uBlockOrigin/uAssets/assets/8306345/975910e7-845d-4542-a08b-82e1e5570214)

### Configuration

<details>

```yaml
uBlock Origin: 1.53.2
Chromium: 119
filterset (summary):
 network: 104153
 cosmetic: 43494
 scriptlet: 18892
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75237-16, 2m
  easyprivacy: 32872-64, 2m
  plowe-0: 3723-1074, 2m
  ublock-badware: 7443-135, 2m
  ublock-filters: 35262-151, 2m
  ublock-privacy: 668-5, 2m
  ublock-quick-fixes: 177-101, 2m
  ublock-unbreak: 2148-32, 2m
  urlhaus-1: 10735-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1693 ms
 maxAssetCacheWait: 21 ms
popupPanel:
 blocked: 3
 network:
  doubleclick.net: 1
  google.com: 1
  google.com.au: 1
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-promoted-sparkles-web-renderer
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?\"\}\}\}\]\…
  ##+js(trusted-replace-fetch-response, /(contextParams":"Q0F[A-Z]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by stephenhawk8054** [comment]
Why did you tick on this

> - [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
