### ISSUE TITLE
watch.cricstream.me: ads

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20622]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://watch.cricstream.me/india-vs-netherlands-live/cricket-world-cup/stream-1`

### Description

Clickable advertisement button above the media player.
Happens with Firefox, not Chrome. Seems to be blocked by Chrome's default Intrusive ad blocking feature. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![0](https://github.com/uBlockOrigin/uAssets/assets/29574622/690ade56-5ad2-4ea1-b640-5396dbe1ef03)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104137
 cosmetic: 43493
 scriptlet: 18733
 html: 1097
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36148-48, 7m
  ublock-badware: 7447-5, 7m
  ublock-privacy: 662-0, 7m
  ublock-unbreak: 2194-2, 7m
  ublock-quick-fixes: 174-101, 7m
  easylist: 75237-658, 7m
  easyprivacy: 32872-767, 7m
  urlhaus-1: 10735-0, 7m
  plowe-0: 3723-1, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 536 ms (selfie)
 maxAssetCacheWait: 100 ms
popupPanel:
 blocked: 12
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  ophoacit.com: 2
  perfectlywent.com: 2
  revcontent.com: 1
  starszoom.re: 4
  taboola.com: 1
 extended:
  ##.w-100.position-absolute.h-100
  ##+js(remove-node-text, script, break;case $.)
  ##+js(abort-current-script, document.documentElement, break;case…
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-current-script, JSON, break;case)
  ##+js(no-window-open-if)
  ##[data-rc-widget]
  ##div[id^="rc-widget-"]

```
</details>

**Comment by huyszn** [comment]
It seems that the text in the button changes every time you refresh the page. The text can be `👉 Live Stream in HD`, `🎟 1080p HD Stream Here`, or `🎟 Watch Live Stream`.

**Comment by SeriousHoax** [comment]
> It seems that the text in the button changes every time you refresh the page. The text can be `👉 Live Stream in HD`, `🎟 1080p HD Stream Here`, or `🎟 Watch Live Stream`.
> 
> So `watch.cricstream.*##button:has-text(/Stream|Watch/)` would catch all instances of the different text.

Adguard seems to be using a different rule. You may also check their solution if required in case that's a better approach.

**Comment by huyszn** [comment]
There also is a debugger trap where if you have dev tools open, the video stops playing and it shows paused in debugger.

**Comment by calmvi5ual** [comment]
they've changed to cricstreams.re, lots of present filters aren't matching on this domain

**Comment by calmvi5ual** [comment]
migrated to `cricwatch.io` Also part of vipleague group of sites #30489
