### ISSUE TITLE
gamedrive.org

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20635]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://gamedrive.org/`

### Description

Footer ad-placeholder

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/9d59db29-c10a-4f5b-9ae4-5de25912b611)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 149244
 cosmetic: 45208
 scriptlet: 23221
 html: 1288
listset (total-discarded, last-updated):
 added:
  adguard-spyware: 62233-16777, 4m
  ublock-annoyances: 5779-13, 7m
 default:
  user-filters: 0-0, never
  ublock-filters: 36172-151, 7m
  ublock-badware: 7462-5, 7m
  ublock-privacy: 662-0, 7m
  ublock-unbreak: 2194-1, 7m
  ublock-quick-fixes: 181-7, 7m
  easylist: 75265-740, 7m
  easyprivacy: 32873-725, 7m
  urlhaus-1: 11000-0, 1h.20m
  plowe-0: 3723-1, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 147 ms
popupPanel:
 blocked: 6
 network:
  gamedrive.org: 1
  d3qygewatvuv28.cloudfront.net: 1
  googletagmanager.com: 1
  pesterclinkaltogether.com: 1
  wp.com: 2
 extended:
  ##+js(abort-current-script, eval, replace)

```
</details>

**Comment by BlazeFTL** [comment]
`gamedrive.org###BR-Footer-Ads`
This Seems Like A Better Option
`gamedrive.org##[id*="-Ads"]`
