### ISSUE TITLE
hinatasoul.com: breakage

### ISSUE THREAD

**Issue by Brunototoro** [uBlockOrigin/uAssets#20638]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.hinatasoul.com/`

### Category

breakage

### Description

When I access this website, the RAM increases a lot. And the problem disappears when I disable Ublock origin.

### Other extensions used

Tampermonkey

### Screenshot(s)

![Captura de tela 2023-11-12 144246](https://github.com/uBlockOrigin/uAssets/assets/150613937/22cf3ea6-81ba-4230-a799-c22ed6e8ddaf)>
<summary>Disabled</summary>

<![Captura de tela 2023-11-12 144643](https://github.com/uBlockOrigin/uAssets/assets/150613937/c8432df7-d942-41cb-8a8a-1e455455ff8c)>

!

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 105889
 cosmetic: 47292
 scriptlet: 19318
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75278-16, 1m
  easyprivacy: 32873-64, 1m
  plowe-0: 3723-1074, 1m
  spa-1: 5727-66, 2m
  ublock-badware: 7443-135, 1m
  ublock-filters: 35286-175, 1m
  ublock-privacy: 668-5, 1m
  ublock-quick-fixes: 176-105, 1m
  ublock-unbreak: 2148-33, 1m
  urlhaus-1: 11000-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 418 ms
 maxAssetCacheWait: 162 ms
popupPanel:
 blocked: 11
 network:
  arc.io: 1
  google.com: 6
  googletagmanager.com: 1
  sentry-cdn.com: 1
  soocaips.com: 2
```
</details>

**Comment by Brunototoro** [comment]
Screenshot
![Captura de tela 2023-11-12 144246](https://github.com/uBlockOrigin/uAssets/assets/150613937/14afbc6e-d5b4-4996-8195-05fbc03923c1)

With Disabled Ublock Origin.

![image](https://github.com/uBlockOrigin/uAssets/assets/150613937/c8f54fd0-2d65-4d7f-a81c-7131c0cfb4a8)

**Comment by mapx-** [comment]
add & test

`||arc.io^$domain=hinatasoul.com`

**Comment by Brunototoro** [comment]
> add & test
> 
> `||arc.io^$domain=hinatasoul.com`

it seems that it worked. Thank you!
