### ISSUE TITLE
foxsports.com

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20634]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.foxsports.com/stories/nfl/nfl-midseason-all-pro-list-lamar-jackson-the-top-qb-3-cowboys-represented`

### Description

Ad placeholder.

There's also a tracker script that is blocked by Adguard Tracking: `||statics.foxsports.com/static/orion/js/segment-analytics.js` 

It's not blocked by any of the default Privacy filters of, EasyPrivacy & uBO Privacy.
Create a rule for this if necessary.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![a](https://github.com/uBlockOrigin/uAssets/assets/29574622/1676b3b7-36e5-492d-bdd8-a33d3c2d5da6)

Tracker script:
![b](https://github.com/uBlockOrigin/uAssets/assets/29574622/d0a4b8ea-80af-4fe5-adad-3d8527a2c549)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104708
 cosmetic: 44963
 scriptlet: 22596
 html: 1288
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5779-13, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36172-48, now
  ublock-badware: 7462-5, now
  ublock-privacy: 662-0, now
  ublock-unbreak: 2194-2, now
  ublock-quick-fixes: 181-109, now
  easylist: 75265-660, now
  easyprivacy: 32873-767, now
  urlhaus-1: 11000-0, 1h.13m
  plowe-0: 3723-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 147 ms
popupPanel:
 blocked: 46
 network:
  appsflyer.com: 2
  atp.fox: 4
  b7tp47v2nb3x-a.akamaihd.net: 2
  chartbeat.com: 2
  datadoghq-browser-agent.com: 2
  fwmrm.net: 1
  go-mpulse.net: 4
  imrworldwide.com: 2
  knotch-cdn.com: 2
  minute.ly: 3
  moatads.com: 6
  opecloud.com: 5
  segment.com: 2
  spot.im: 8
  taboola.com: 1
 extended:
  ###taboola-below-article-thumbnails
  ##+js(json-prune, ads)
  ##+js(m3u-prune, /\,ad\n.+?(?=#UPLYNK-SEGMENT)/gm, .m3u8)
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…

```
</details>

**Comment by mapx-** [comment]
for EL list

`foxsports.com##.fwAdContainer`

the tracker for easyprivacy too

`||statics.foxsports.com/static/orion/js/segment-analytics.js`

@ryanbr
