### ISSUE TITLE
fantasyfootballhub.co.uk

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20636]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.fantasyfootballhub.co.uk/what-is-the-fantasy-premier-league-wildcard-and-when-to-use-it`

### Description

Not solved by uBO Annoyances & EasyList Annoyances.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/13046f05-e49c-4858-85db-f43eaef8c5a8)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 108887
 cosmetic: 116137
 scriptlet: 25600
 html: 1288
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4175-96, 2m
  easylist-chat: 153-0, 2m
  fanboy-cookiemonster: 48865-280, 2m
  ublock-cookies-easylist: 528-0, 2m
  easylist-newsletters: 6649-14, 2m
  easylist-notifications: 2872-9, 2m
  fanboy-social: 16194-7, 2m
  ublock-annoyances: 5779-563, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 36172-48, 2m
  ublock-badware: 7462-5, 2m
  ublock-privacy: 662-0, 2m
  ublock-unbreak: 2194-2, 2m
  ublock-quick-fixes: 181-109, 2m
  easylist: 75265-733, 2m
  easyprivacy: 32873-816, 2m
  urlhaus-1: 11000-0, 2m
  plowe-0: 3723-1, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 147 ms
popupPanel:
 blocked: 26
 network:
  doubleclick.net: 3
  facebook.net: 1
  google.com: 9
  googleoptimize.com: 1
  googletagmanager.com: 1
  mxpnl.com: 1
  sentry.io: 2
  sibautomation.com: 1
  snack-media.com: 2
  tiktok.com: 1
  vercel-insights.com: 2
  wdfl.co: 1
  youtube.com: 1
 extended:
  ##.grecaptcha-badge
  ##.ytp-pause-overlay
  ##.ytp-ad-progress-list
  ##.ytp-share-button
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?\"\}\}\}\]\…
  ##+js(trusted-replace-fetch-response, /((?:(?:&|%26)id(?:=|%3D)o…
  ##+js(trusted-replace-fetch-response, /(contextParams":"Q0F[A-Z]…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…

```
</details>

**Comment by gorhill** [comment]
_AdGuard Popup Overlays_ list seems to work for me.

**Comment by mapx-** [comment]
indeed, I'll remove it

**Comment by SeriousHoax** [comment]
> indeed, I'll remove it

Can you tag someone who can fix it for EasyList Annoyance?

**Comment by mapx-** [comment]
@ryanbr 

`fantasyfootballhub.co.uk##+js(set-session-storage-item, modalViewed, true)`
