### ISSUE TITLE
online2pdf.com: detection

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20632]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://online2pdf.com/`

### Description

Adblocker detected

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/ca6dcdc7-6907-4c82-bc3e-1e75f0bb5253)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104708
 cosmetic: 44963
 scriptlet: 22588
 html: 1288
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5771-13, 27m
 default:
  user-filters: 0-0, never
  ublock-filters: 36172-258, 27m
  ublock-badware: 7462-5, 27m
  ublock-privacy: 662-0, 27m
  ublock-unbreak: 2194-1, 27m
  ublock-quick-fixes: 181-7, 27m
  easylist: 75265-553, 27m
  easyprivacy: 32873-767, 27m
  urlhaus-1: 11000-0, 27m
  plowe-0: 3723-1, 27m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 147 ms
popupPanel:
 blocked: 4
 network:
  online2pdf.com: 2
  doubleclick.net: 1
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle
  ##+js(no-setTimeout-if, check)
```
</details>

**Comment by mapx-** [comment]
just an annoyance ?

```
@@||online2pdf.com^$ghide
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=online2pdf.com
```

**Comment by SeriousHoax** [comment]
> just an annoyance ?
> 
> ```
> @@||online2pdf.com^$ghide
> @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=online2pdf.com
> ```

Yeah, annoyance is probably the best way to describe this. Maybe the fix should be included in EasyList.

**Comment by JobcenterTycoon** [comment]
For the placeholder

```
online2pdf.com##div[id][class][style^="position:"] > div:first-child:has-text(/^Werbung$/):upward(1):style(visibility: hidden !important;)
online2pdf.com##div[class="container_box content_box"] > div:only-child > div:first-child:has-text(/^Werbung$/):upward(2)
```

**Comment by JobcenterTycoon** [comment]
For the placeholder:

```
online2pdf.com##div[id][class][style^="position:"] > div:last-child > div:last-child > ins.adsbygoogle:upward(3)
online2pdf.com##div[class="container_box content_box"] > div:only-child > div:last-child > div:last-child > ins.adsbygoogle:upward(4)
```

`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=online2pdf.com` is not needed on my end.

**Comment by BlazeFTL** [comment]
Can Confirm The Whitelist Is Not Needed
```
@@||online2pdf.com^$ghide
online2pdf.com##div[id][class][style^="position:"] > div:last-child > div:last-child > ins.adsbygoogle:upward(3)
online2pdf.com##div[class="container_box content_box"] > div:only-child > div:last-child > div:last-child > ins.adsbygoogle:upward(4)

**Comment by dportvine** [comment]
> Can Confirm The Whitelist Is Not Needed
> 
> ```
> @@||online2pdf.com^$ghide
> online2pdf.com##div[id][class][style^="position:"] > div:last-child > div:last-child > ins.adsbygoogle:upward(3)
> online2pdf.com##div[class="container_box content_box"] > div:only-child > div:last-child > div:last-child > ins.adsbygoogle:upward(4)
> ```

<details>
<summary>Screen</summary>

![2023-11-12_182352](https://github.com/uBlockOrigin/uAssets/assets/111344219/ba76403a-e09a-4424-a746-af2e14a1af3f)
</details>


For me, works one rule: `online2pdf.com##.main > table > tbody > tr > td > div > div[id][class]:has-text(Advertisements)`

<details>
<summary>Screen</summary>

![2023-11-12_182352](https://github.com/uBlockOrigin/uAssets/assets/111344219/308e358a-a177-46be-8772-96ceab9e5c5f)
![2023-11-12_182723](https://github.com/uBlockOrigin/uAssets/assets/111344219/721af5e5-6820-4b41-883a-3145faf56fa3)
</details>

**Comment by JobcenterTycoon** [comment]
`:has-text(Advertisements)` only works for one language. I added a fix for mobile/small screens now https://github.com/uBlockOrigin/uAssets/commit/d799179228480e29d7e34f7457bbbe38a01061dd

**Comment by dportvine** [comment]
Works good! Tnx.

**Comment by LightAndy1** [comment]
Same issue, happening again:

<details>
  <summary>Screenshot</summary>
  
  <img width="315" height="655" alt="Image" src="https://github.com/user-attachments/assets/c290a3f7-26fe-4573-9f50-1d2b7bd848cf" />
</details>
