### ISSUE TITLE
nmgassets.com

### ISSUE THREAD

**Issue by ehudlavin** [uBlockOrigin/uAssets#20633]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://lowes.com`

### Description

`nmgassets.com` **domain is blocked**.

it contains a blocking mechanism to remove 3rd party unwanted ads.
it sends back info to improve the blocking mechanism that doesn't contain any pii (see `namogoo.com` for more info)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1512" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/67254552/b3ee7ec0-25bd-41f2-bad7-81ebed6d9b2a">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by gorhill** [comment]
What's the exact issue here?

**Comment by ryanbr** [comment]
Blocking https://gs.nmgassets.com/LODOWS854.js tracker.
