### ISSUE TITLE
makemytrip.com: nuisance

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20630]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.makemytrip.com/`

### Description

Extra filters added: All EasyList Annoyances, uBO Annoyances.

Issues:
Login popups, missed ads, mobile app banner and others in case I missed something.

Adguard Tracking protection has this rule: `||jsak.mmtcdn.com/*/pwa_commons/pwatracker.js` to block a tracker script, it seems. It's not blocked by the default EasyPrivacy. Create a rule for this also, if necessary. 

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/uBlockOrigin/uAssets/assets/29574622/f18041f1-ecaf-4957-a1be-eab394824943)
![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/1b3a865d-bad0-4440-a5d6-7e8627028828)
![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/e0ade0e0-2dc6-40f0-85d5-8a11cad7ac27)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 108887
 cosmetic: 116137
 scriptlet: 25592
 html: 1288
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4175-94, 21m
  easylist-chat: 153-0, 21m
  fanboy-cookiemonster: 48865-268, 21m
  ublock-cookies-easylist: 528-0, 21m
  easylist-newsletters: 6649-13, 21m
  easylist-notifications: 2872-4, 21m
  fanboy-social: 16194-7, 21m
  ublock-annoyances: 5771-563, 21m
 default:
  user-filters: 0-0, never
  ublock-filters: 36172-171, 21m
  ublock-badware: 7462-5, 21m
  ublock-privacy: 662-0, 21m
  ublock-unbreak: 2194-1, 21m
  ublock-quick-fixes: 181-7, 21m
  easylist: 75265-733, 21m
  easyprivacy: 32873-816, 21m
  urlhaus-1: 11000-0, 21m
  plowe-0: 3723-1, 21m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 286 ms (selfie)
 maxAssetCacheWait: 147 ms
popupPanel:
 blocked: 15
 network:
  makemytrip.com: 10
  demdex.net: 3
  google.com: 1
  webengage.com: 1
 extended:
  ##.socialMediaLinks

```
</details>

**Comment by gorhill** [comment]
This seems to work:

    makemytrip.com##.modalLogin

If so, should probably go in _EasyList – Other Annoyances_ I guess.

**Comment by gorhill** [comment]
For mobile:

    makemytrip.com##.pwa-login
    makemytrip.com##.appDnldOffers
    makemytrip.com##body:style(overflow: unset !important)

**Comment by SeriousHoax** [comment]
These are the rules created by the Adguard team back when I reported this to them. You guys may have a look at this if required and add required rules to appropriate filters:
https://github.com/AdguardTeam/AdguardFilters/commit/a494cc2139279f81b3449b2189e560dad8844445

**Comment by ryanbr** [comment]
`makemytrip.com##.modalLogin` prevent the login window from occuring completely

**Comment by gorhill** [comment]
I would think this should work:

    makemytrip.com##+js(trusted-set-session-storage-item, opd, '"1"')

**Comment by ryanbr** [comment]
Does trusted-session work? the highlight shows up;  (on 1.53.5rc4)

![trusted-session](https://github.com/uBlockOrigin/uAssets/assets/1659004/ffb36e97-5c37-4dd0-bb67-38f8813ca76f)

**Comment by stephenhawk8054** [comment]
I don't think we have trusted version of `set-session`?

**Comment by gorhill** [comment]
I can add it in the current dev cycle, it's a trivial change.

**Comment by gorhill** [comment]
If it's because of the quotes, I think it would make sense to allow quotes around any of the supported values in plain `set-local-storage-item` / `set-session-storage-item` -- it's not like the quotes introduce a security issue.

**Comment by ryanbr** [comment]
Also set-cookie?

**Comment by gorhill** [comment]
I've added support for using quotes around supported values in `set-(local|session)-storage-item` and `set-cookie`, this will be in rc5 build.

**Comment by ryanbr** [comment]
trusted-session would be helpful.  The actual session value used on makemytrip is `"1,4"` to cancel the modal. But `"1"` works also.  If "1" didn't work.. well.
