### ISSUE TITLE
howtoconcepts.com: nuisance

### ISSUE THREAD

**Issue by simiasidhu1** [uBlockOrigin/uAssets#20637]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://howtoconcepts.com/`

### Category

nuisance

### Description

Adblock detected overlay

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 105830
 cosmetic: 34821
 scriptlet: 18811
 html: 1098
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36487-401, now
  ublock-badware: 7456-5, now
  ublock-privacy: 662-1, now
  ublock-unbreak: 2199-2, now
  ublock-quick-fixes: 181-7, now
  adguard-mobile: 8857-127, now
  easylist: 75265-16716, now
  easyprivacy: 32873-733, now
  urlhaus-1: 11000-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 972 ms (selfie)
 maxAssetCacheWait: 185 ms
popupPanel:
 blocked: 18
 network:
  doubleclick.net: 7
  google-analytics.com: 1
  googlesyndication.com: 5
  googletagmanager.com: 1
  mgid.com: 2
  wp.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by BlazeFTL** [comment]
Is This A Shortner Site ?... Provide The Original Link...
