### ISSUE TITLE
finance.yahoo.com: breakage

### ISSUE THREAD

**Issue by dmh1962** [uBlockOrigin/uAssets#20639]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://finance.yahoo.com/`

### Category

breakage

### Description

Going to the Yahoo Finance page, with uBlock active, the page freezes and causes Firefox to hang.  Have to use task manager to close/restart browser.  

This happens with uBlock or Ghostery active (separately of course).  Some feature is causing this.  Seems to be only happening in Firefox.

### Other extensions used

ABP, Trocker, New Tab Homepage, Webmail add blocker.  Switch between Ghostery and uBlock to see if one app works.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104692
 cosmetic: 44927
 scriptlet: 22589
 html: 1288
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5767-13, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36172-151, now
  ublock-badware: 7462-5, now
  ublock-privacy: 662-0, now
  ublock-unbreak: 2194-1, now
  ublock-quick-fixes: 181-7, now
  easylist: 75226-702, now
  easyprivacy: 32865-725, now
  urlhaus-1: 11000-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1281 ms (selfie)
 maxAssetCacheWait: 89 ms
popupPanel:
 blocked: 3
 network:
  yahoo.com: 1
  brightcove.com: 1
  scorecardresearch.com: 1
 extended:
  ###sda-LDRB2
  ###sda-LREC
  ###sda-LREC2
  ###sda-LREC3
  ###sda-LREC4
```
</details>

**Comment by mapx-** [comment]
> ABP

I cannot reproduce the issue, but if you keep always abp enabled could be a serious issue.

**Comment by dmh1962** [comment]
Fastest blow off EVER.  Disabling ABP STILL causes issue.  You should try harder.

**Comment by mapx-** [comment]
reset uBO to default settings / lists, disable all other extensions, addons, test again

**Comment by dillanski** [comment]
Yahoo Finance causing my Firefox to hang also.  Incredible 52,000 blocked on 1 page.  Something's definitely wrong with UBO.

![firefox-ubo-freezing2](https://github.com/uBlockOrigin/uAssets/assets/20270159/1be528cd-275a-421b-a40a-3c7432b4ca1e)
