### ISSUE TITLE
colonist.io: detection

### ISSUE THREAD

**Issue by tjeulink** [uBlockOrigin/uAssets#20649]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

colonist.io

### Description

It stops working after a while, sometimes the play button doesn't work anymore. sometimes it gives an error message that tells you to disable adblock. usually i can play one game fine.
![Screenshot from 2023-11-13 13-43-14](https://github.com/uBlockOrigin/uAssets/assets/30367139/571e6929-7898-4c87-9b0d-108bf45eabfb)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2023-11-13 13-43-14](https://github.com/uBlockOrigin/uAssets/assets/30367139/571e6929-7898-4c87-9b0d-108bf45eabfb)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104519
 cosmetic: 43579
 scriptlet: 18946
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75291-16, 23m
  easyprivacy: 32874-64, 23m
  plowe-0: 3723-1074, 23m
  ublock-badware: 7459-135, 23m
  ublock-filters: 35400-151, 23m
  ublock-privacy: 667-5, 23m
  ublock-quick-fixes: 184-109, 1h.8m
  ublock-unbreak: 2148-32, 23m
  urlhaus-1: 11030-0, 23m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 283 ms (selfie)
 maxAssetCacheWait: 90 ms
popupPanel:
 blocked: 112
 network:
  2mdn.net: 1
  3lift.com: 8
  4dex.io: 8
  a-mo.net: 8
  a-mx.com: 1
  adnxs.com: 8
  amazon-adsystem.com: 1
  aralego.com: 1
  aralego.net: 1
  btloader.com: 1
  criteo.com: 4
  criteo.net: 1
  doubleclick.net: 2
  googleoptimize.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  id5-sync.com: 1
  jsdelivr.net: 1
  pubmatic.com: 8
  quantserve.com: 1
  quantumdex.io: 8
  script.ac: 2
  smartadserver.com: 9
  sonobi.com: 1
  teads.tv: 3
  threetruck.com: 1
  unrulymedia.com: 2
  vliplatform.com: 20
  vlitag.com: 5

```
</details>

**Comment by JobcenterTycoon** [comment]
Works fine for me. When i click the button it just need a few seconds to react but after this it working fine.

**Comment by tjeulink** [comment]
yes, sometimes it works fine, sometimes it doesn't. somtimes it doesn't give an error but doesn't work, sometimes it just works, other times it throws an disable adblock message. i tried doing it in a fresh browser but it yields the same results, regardless of whether im logged in or not or on a different IP or not.

**Comment by JobcenterTycoon** [comment]
@stephenhawk8054 people complaining again about a anti adblock. Can you reproduce?

**Comment by ayush987goyal** [comment]
+1 Purging caches did not help.

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon It requires an account that have played for a while?

**Comment by JobcenterTycoon** [comment]
10 unrankes matches because the anti adblock appear on ranked matches.
