### ISSUE TITLE
thehackernews.com: ads

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20647]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://thehackernews.com/`

### Description

Ads

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/4ade1017-a2e2-473b-a810-158fd248e246)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 113839
 cosmetic: 124182
 scriptlet: 25642
 html: 1288
listset (total-discarded, last-updated):
 added:
  fanboy-thirdparty_social: 69-0, now
  easylist-annoyances: 4176-96, now
  easylist-chat: 153-0, now
  fanboy-cookiemonster: 48882-287, now
  ublock-cookies-easylist: 528-0, now
  easylist-newsletters: 6650-14, now
  easylist-notifications: 2876-9, now
  fanboy-social: 16197-22, now
  ublock-annoyances: 5783-563, now
  IND-0: 12784-3, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36290-48, now
  ublock-badware: 7463-5, now
  ublock-privacy: 661-0, now
  ublock-unbreak: 2194-2, now
  ublock-quick-fixes: 182-109, now
  easylist: 75291-730, now
  easyprivacy: 32874-816, now
  urlhaus-1: 11030-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 677 ms (selfie)
 maxAssetCacheWait: 102 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ###email-outer
  ##.sub-button
  ##.follow-box
  ##.top-follow

```
</details>

**Comment by mapx-** [comment]
`thehackernews.com##[class]:has([src^="data:image/gif;base64,"])`

@ryanbr

**Comment by mapx-** [comment]
@SeriousHoax this is a "classic" for EL repo
