### ISSUE TITLE
idtech.com: breakage

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#20644]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.idtech.com/jobs`

### Category

[breakage]

### Description

Website is all blank unless uBlock Origin is disabled

### Other extensions used

FastFoward

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 213106
 cosmetic: 220773
 scriptlet: 46142
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 74879-117, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94715-21771, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 79707-530, now
  adguard-mobile: 8860-58, now
  adguard-spyware-url: 1310-5, now
  block-lan: 54-0, now
  curben-phishing: 77122-20, now
  fanboy-cookiemonster: 48882-48882, now
  ublock-annoyances: 5824-250, now
 default:
  user-filters: 0-0, never
  easylist: 75291-1728, now
  easyprivacy: 32874-376, now
  plowe-0: 3723-1160, now
  ublock-badware: 7459-330, now
  ublock-filters: 35397-4244, now
  ublock-privacy: 668-90, now
  ublock-quick-fixes: 184-115, now
  ublock-unbreak: 2148-97, now
  urlhaus-1: 10830-1, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 782 ms (selfie)
 maxAssetCacheWait: 571 ms
popupPanel:
 blocked: 5
 network:
  idtech.com: 3
  googletagmanager.com: 1
  optimizely.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
@jimmysofat6864 Try In My Filters
`@@||idtech.com/_nuxt/CookieWarning*.js$script,domain=idtech.com`

**Comment by dportvine** [comment]
@Alex-302, @ryanbr
