### ISSUE TITLE
thehacker.recipes: nuisance

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#20645]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.thehacker.recipes/`

### Description

Cookie notice

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29574622/cedb94bc-611a-4ad5-9eae-b7e7de5c78c6)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 108770
 cosmetic: 116214
 scriptlet: 25639
 html: 1288
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4176-96, now
  easylist-chat: 153-0, now
  fanboy-cookiemonster: 48882-279, now
  ublock-cookies-easylist: 528-0, now
  easylist-newsletters: 6650-14, now
  easylist-notifications: 2876-9, now
  fanboy-social: 16197-7, now
  ublock-annoyances: 5783-563, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36283-51, now
  ublock-badware: 7463-5, now
  ublock-privacy: 662-0, now
  ublock-unbreak: 2194-2, now
  ublock-quick-fixes: 181-109, now
  easylist: 75291-733, now
  easyprivacy: 32874-816, now
  urlhaus-1: 10830-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3827 ms (selfie)
 maxAssetCacheWait: 1128 ms
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 2
  sentry.io: 2

```
</details>

**Comment by BlazeFTL** [comment]
Enable Adguard Cookie Notice

Or 

In My Filters
`thehacker.recipes##+js(set-cookie, __gitbook_cookie_granted, no)`

**Comment by mapx-** [comment]
@ryanbr

**Comment by SeriousHoax** [comment]
> Enable Adguard Cookie Notice
> 
> Or
> 
> In My Filters `thehacker.recipes##+js(set-cookie, __gitbook_cookie_granted, no)`

Should I report things like this in the EasyList repo instead? Or is it okay to report here? The thing is, in my experience, EL Annoyances rules works the best with uBO. ADG rules works the best with ADG extension and cause some incompatibility here and there on uBO. I should also add that reporting issues here in uAssets make things fix very fast, while on EasyList often it takes a long time.

**Comment by mapx-** [comment]
yeah, it's better reporting at EL repo (sometimes needing trusted filters so EL maintainer will ask us to add it to our list)

**Comment by SeriousHoax** [comment]
> yeah, it's better reporting at EL repo (sometimes needing trusted filters so EL maintainer will ask us to add it to our list)

I see, thanks. I'll keep that in my mind while reporting nuisances.
