### ISSUE TITLE
careerkarma.com: nuisance

### ISSUE THREAD

**Issue by Ceddicedced** [uBlockOrigin/uAssets#20655]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://careerkarma.com/`

### Category

nuisance

### Description

Displays pop-up ad.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19432359/9a55b596-c3b3-45a1-9f40-43b1c80c3b9f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 118188
 cosmetic: 199314
 scriptlet: 29968
 html: 0
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 76-0, now
  adguard-cookies: 28037-31, now
  adguard-mobile-app-banners: 4740-9, now
  adguard-other-annoyances: 13787-10, now
  adguard-popup-overlays: 25990-69, now
  adguard-social: 22022-926, now
  adguard-widgets: 2342-6, now
  easylist-annoyances: 4178-207, now
  easylist-chat: 153-11, now
  easylist-newsletters: 6651-431, now
  easylist-notifications: 2876-1452, now
  fanboy-cookiemonster: 48884-3836, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 13-0, never
  DEU-0: 7146-0, now
  easylist: 75299-82, now
  easyprivacy: 32876-188, now
  plowe-0: 3723-1076, now
  ublock-badware: 7494-139, now
  ublock-filters: 35406-524, now
  ublock-privacy: 667-83, now
  ublock-quick-fixes: 186-114, now
  ublock-unbreak: 2148-38, now
  urlhaus-1: 11030-0, now
filterset (user): [array of 47 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3967 ms (selfie)
 maxAssetCacheWait: 3356 ms
popupPanel:
 blocked: 15
 network:
  clarity.ms: 1
  facebook.net: 1
  google.com: 8
  googleoptimize.com: 1
  googletagmanager.com: 1
  hotjar.com: 1
  segment.com: 1
  truevaultcdn.com: 1
 extended:
  ##.ck_box_1
  ###full-sticky-footer-container
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="http://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.linkedin.com/cws/share?"]
  ##a[href^="http://www.facebook.com/sharer.php"]
  ##.share-article-vertical
  ##.share-article
  ##.share-title
  ###scroll_totop
  ##.ad_btn
  ##.ad_message
  ##+js(set-cookie, _Wmpci_Popup, true)
```
</details>

**Comment by mapx-** [comment]
add

`careerkarma.com##.ant-modal-root`

@ryanbr
