### ISSUE TITLE
alfred.camera: detection

### ISSUE THREAD

**Issue by 0x6A7232** [uBlockOrigin/uAssets#20657]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://alfred.camera/webapp/viewer`

### Category

detection

### Description

AlfredCamera site will pop up a nag box after a short delay:
![Alfredcam](https://github.com/uBlockOrigin/uAssets/assets/14183951/7b74a4b1-925c-40db-a4ee-4ad0a2ff821e)

NB: AlfredCam account is free and you don't have to pay to create a session and view -- and you can use an old mobile device or a webcam to set up viewing to test the issue.  Eg I can either use my old Galaxy S4 or the webcam on my desktop or laptop to make an AlfredCam, although they do sell their own cams pretty cheap.  This issue manifests on free accounts using an adblocker regardless.

### Other extensions used

**_Enabled Extensions:_**

Adobe Acrobat: PDF edit, convert, sign tools
uBlock Origin
Volume Booster
Google Docs Offline

**_Disabled Extensions:_**

Free Download Manager
Meta Pixel Helper
ProctorU
Reddit Enhancement Suite
Tailwind – AI marketing content assistant

**_Chrome Apps (still disabled):_**

Cut the Rope
Word Search Puzzle

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104559
 cosmetic: 43590
 scriptlet: 18949
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75304-16, 1m
  easyprivacy: 32876-64, now
  plowe-0: 3723-1074, now
  ublock-badware: 7494-139, now
  ublock-filters: 35408-151, now
  ublock-privacy: 667-5, now
  ublock-quick-fixes: 184-109, 54m
  ublock-unbreak: 2148-32, now
  urlhaus-1: 11030-0, 55m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 191 ms (selfie)
 maxAssetCacheWait: 59 ms
popupPanel:
 blocked: 4
 network:
  amplitude.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`

**Comment by 0x6A7232** [comment]
Oh I see.  Under the "Annoyances" header, I was looking under "Ads" and "Multipurpose".  Tyvm!
