### ISSUE TITLE
npo.nl: ads

### ISSUE THREAD

**Issue by nathanaelbaaij** [uBlockOrigin/uAssets#20659]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://npo.nl/`

### Category

ads

### Description

Ads appear when viewing a video from 

`https://npo.nl/start`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/7000976/9fcf7fee-0fdb-46e3-a3b8-509d0765ec9d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 105202
 cosmetic: 45623
 scriptlet: 19013
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 26-0, never
  NLD-0: 2732-9, now
  easylist: 75304-18, now
  easyprivacy: 32876-65, now
  plowe-0: 3724-1074, now
  ublock-badware: 7494-139, now
  ublock-filters: 35402-153, now
  ublock-privacy: 667-5, now
  ublock-quick-fixes: 186-110, now
  ublock-unbreak: 2148-32, now
  urlhaus-1: 11030-0, now
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 258 ms (selfie)
 maxAssetCacheWait: 103 ms
popupPanel:
 blocked: 22
 network:
  npo.nl: 18
  2cnt.net: 1
  bitmovin.com: 3
 extended:
  ##+js(json-prune, assets.preroll assets.prerollDebug)
```
</details>

**Comment by mapx-** [comment]
test

```
||akamaized.net^$media,domain=npo.nl,redirect=noopmp3-0.1s
npo.nl##.bitmovinplayer-poster
```

**Comment by mapx-** [comment]
@Nomes77 @JohnyP36

**Comment by JohnyP36** [comment]
As per https://github.com/uBlockOrigin/uAssets/commit/cd6c933e2975fcde9bd2da57b802912b7f1d70b4 we added `npo.nl##+js(json-prune, assets.preroll assets.prerollDebug)` which also seems to work. 
Do we still need to test? 
```adblock
||akamaized.net^$media,domain=npo.nl,redirect=noopmp3-0.1s
npo.nl##.bitmovinplayer-poster
```

**Comment by Nomes77** [comment]
@JohnyP36 yes
See: `https://npo.nl/start/serie/boer-zoekt-vrouw`
