### ISSUE TITLE
kaggle.com: breakage

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uAssets#20656]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.kaggle.com/`

### Category

breakage

### Description

The dialog to switch runtime accelerator in a Kaggle notebook (accessible by clicking the highlighted text from the kebab menu as shown in the attached screenshot) will not be shown.

The issue is caused by the following filter in Easylist - Cookie Notices.
```adblock
kaggle.com##.sc-jgAlvE
```

Adding `kaggle.com#@#.sc-jgAlvE` to user's filters resolves the issue.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![kaggle](https://github.com/uBlockOrigin/uAssets/assets/115052854/d8ae4545-8412-4fc0-9c49-813155be1922)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.3rc0
Firefox: 119
filterset (summary):
 network: 108724
 cosmetic: 114800
 scriptlet: 21850
 html: 1097
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4178-48, 7m
  easylist-chat: 150-0, 7m
  fanboy-cookiemonster: 48884-229, 7m
  easylist-newsletters: 6650-21, 7m
  easylist-notifications: 2872-165, 7m
  fanboy-social: 16212-28, 7m
 default:
  user-filters: 0-0, never
  ublock-filters: 36296-48, 7m
  ublock-badware: 7498-9, 7m
  ublock-privacy: 661-0, 7m
  ublock-unbreak: 2194-1, 7m
  ublock-quick-fixes: 183-111, 7m
  easylist: 75299-268, 7m
  easyprivacy: 32876-83, 7m
  urlhaus-1: 11030-0, 7m
  plowe-0: 3723-1075, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 colorBlindFriendly: true
hiddenSettings:
 filterAuthorMode: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 260 ms (selfie)
 maxAssetCacheWait: 169 ms
popupPanel:
 blocked: 8
 network:
  kaggle.io: 7
  typekit.net: 1
 extended:
  ##.grecaptcha-badge
  ##.sc-jgAlvE
  ##+js(set-cookie, ACCEPTED_COOKIES, true)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
I notified the maintainer but in the future report directly at EL repo
