### ISSUE TITLE
en.aston-martin-club.com / cs.aston-martin-club.com: detection

### ISSUE THREAD

**Issue by TorqueDog** [uBlockOrigin/uAssets#20654]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

```
https://en.aston-martin-club.com/
https://cs.aston-martin-club.com/
```

### Description

The site performs a detection upon load that quickly unloads main content and replaces it with a "DISABLE ADBLOCK" graphic and a **This website is free only for people who do not block ads** message.

Happens with and without additional filter-lists and custom rules enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 111940
 cosmetic: 129231
 scriptlet: 27054
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 74900-117, 6m
  adguard-social: 22022-927, 6m
  fanboy-thirdparty_social: 68-3, 6m
  ublock-annoyances: 5824-153, 6m
 default:
  easylist: 75299-76, 6m
  easyprivacy: 32876-132, 6m
  plowe-0: 3723-1075, 6m
  ublock-badware: 7494-139, 7m
  ublock-filters: 35405-493, 7m
  ublock-privacy: 666-6, 7m
  ublock-quick-fixes: 186-114, 7m
  ublock-unbreak: 2148-34, 7m
  urlhaus-1: 11030-0, 5m
filterset (user): [array of 50 redacted]
trustedset:
 added: [array of 120 redacted]
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 220 ms (selfie)
 maxAssetCacheWait: 143 ms
popupPanel:
 blocked: 2
 network:
  toplist.cz: 2
```yaml


```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
