### ISSUE TITLE
chaptercheats.com: detection

### ISSUE THREAD

**Issue by AdamFrack** [uBlockOrigin/uAssets#20653]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.chaptercheats.com/cheat/switch/414797/Go-Vacation/hint/106547/`

### Category

detection

### Description

Detects uBlock Origin, nothing more to sa

### Other extensions used

dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104539
 cosmetic: 43584
 scriptlet: 18788
 html: 1097
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36291-152, now
  ublock-badware: 7498-9, now
  ublock-privacy: 661-0, 2m
  ublock-unbreak: 2194-1, now
  ublock-quick-fixes: 183-7, now
  easylist: 75299-700, now
  easyprivacy: 32872-725, now
  urlhaus-1: 11030-0, now
  plowe-0: 3723-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1270 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel:
 blocked: 10
 network:
  adsafeprotected.com: 2
  advertising.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  intergient.com: 2
  merequartz.com: 2
 extended:
  ##.adright
```
</details>

**Comment by BlazeFTL** [comment]
Try
`chaptercheats.com##^script:has-text(/typeof [a-z]\.cmd\.unshift/)`

**Comment by BlazeFTL** [comment]
```
chaptercheats.com##^script:has-text(/typeof [a-z]\.cmd\.unshift/)
chaptercheats.com##+js(rmnt, script, /typeof [a-z]\.cmd\.unshift/, condition, cmd.unshift)
||radiateprose.com^$xhr,domain=chaptercheats.com
chaptercheats.com##.moredetails.bluebar, .mid_d

**Comment by JobcenterTycoon** [comment]
It got fixed here https://github.com/uBlockOrigin/uAssets/commit/98b8468f8283b20323ba73f67c114916bd1803d4

I also reported `radiateprose.com` upstream so its blocked by `EasyPrivacy` and `Peter Lowe’s Ad and tracking server list` now.
