### ISSUE TITLE
pinterest.com: ads

### ISSUE THREAD

**Issue by karigithub2000** [uBlockOrigin/uAssets#20663]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.com/`

### Category

ads

### Description

Ads are showing in the pinterest feed.

### Other extensions used

Search by Image, Hide shorts for Youtube, Honey, F-B Hide Recommendations and Reels, SponsorBlock for YouTube - Skip Sponsorships, Firefox Translations, To Google Translate, Pinterest Save Button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-11-13 174940](https://github.com/uBlockOrigin/uAssets/assets/134016424/64fc7b5a-afc8-44eb-a195-4255d80c3586)
![Screenshot 2023-11-13 175000](https://github.com/uBlockOrigin/uAssets/assets/134016424/a80dea5d-9f9c-4c75-83d2-2ec090e045a5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104573
 cosmetic: 43638
 scriptlet: 18841
 html: 1100
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36422-152, now
  ublock-badware: 7498-9, now
  ublock-privacy: 661-0, now
  ublock-unbreak: 2194-1, now
  ublock-quick-fixes: 183-7, now
  easylist: 75306-699, now
  easyprivacy: 32876-725, now
  urlhaus-1: 11030-0, now
  plowe-0: 3724-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6417 ms (selfie)
 maxAssetCacheWait: 115 ms
popupPanel:
 blocked: 6
 network:
  pinterest.com: 2
  cedexis.com: 1
  flashtalking.com: 1
  googletagmanager.com: 1
  tvpixel.com: 1
 extended:
  ##+js(replace-node-text, script, /web_hide_epik_param_in_promote…
```
</details>

**Comment by mapx-** [comment]
maybe

`pinterest.*##[data-grid-item]:has([aria-label]:not([aria-label*="pinterest"])[href]:not([href^="/pin"]))`
