### ISSUE TITLE
antlionaudio.com: breakage

### ISSUE THREAD

**Issue by AntlionJoe** [uBlockOrigin/uAssets#20664]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://antlionaudio.com/`

### Category

breakage

### Description

Top nav "Shop" dropdown menu is being blocked by EasyList. I was unable to determine the root cause, but the issue goes away when EasyList is disabled. May also be impacting our mobile menu button from opening.

### Other extensions used

Confirmed this issue is only with uBO and other easylist blockers; but for completeness:

Helium10
Whatfont
Lastpass
AdobePDF Edit

Were all enabled and running during some diagnostic testing.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104544
 cosmetic: 43594
 scriptlet: 18958
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75306-16, 13m
  easyprivacy: 32876-64, 23m
  plowe-0: 3724-1074, 24m
  ublock-badware: 7494-139, 23m
  ublock-filters: 35401-150, 23m
  ublock-privacy: 667-5, 23m
  ublock-quick-fixes: 186-110, 23m
  ublock-unbreak: 2148-32, 23m
  urlhaus-1: 11030-0, 23m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 822 ms
 maxAssetCacheWait: 14 ms
popupPanel:
 blocked: 19
 network:
  antlionaudio.com: 11
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 3
  shopifysvc.com: 1
  tiktok.com: 1
  zendesk.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||antlionaudio.com/cdn/shop/*/assets/fastclick.min.js$script,1p`

@ryanbr
