### ISSUE TITLE
etrodo.de: breakage

### ISSUE THREAD

**Issue by szotsaki** [uBlockOrigin/uAssets#20661]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.etrodo.de/account/login`

### Category

breakage

### Description

The problem that [EasyList – Cookie Notices](chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=fanboy-cookiemonster) filters out the following:
<details><summary>Logger output</summary>

```
+1
##div.privacy-notice
www.etrodo.de
get
dom
https://www.etrodo.de/account/login
```
```
+1
##.privacy-notice:not(body):not(html):not([class*="-input"])
www.etrodo.de
get
dom
https://www.etrodo.de/account/login
```
```
+0
https://www.etrodo.de/account/login
```
</details>

To verify if it's fixed, see if the following element is visible on the bottom of the page:
```
Datenschutz
Ich habe die [Datenschutzbestimmungen](https://www.etrodo.de/widgets/cms/d05b0092a4404e1d9571c6fb4a8fb8bb) zur Kenntnis genommen und die [AGB](https://www.etrodo.de/widgets/cms/d6be6edbc8e3487394327bf328baa70d) gelesen und bin mit ihnen einverstanden. *
```

### Other extensions used

-

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 116
filterset (summary):
 network: 157257
 cosmetic: 181062
 scriptlet: 27156
 html: 0
listset (total-discarded, last-updated):
 added:
  DEU-0: 7146-0, 1h.21m
  adguard-cookies: 28042-33, now
  adguard-mobile-app-banners: 4740-10, now
  adguard-other-annoyances: 13788-10, now
  adguard-popup-overlays: 25991-84, now
  adguard-social: 21965-928, now
  adguard-spyware: 57216-173, now
  adguard-spyware-url: 1310-5, now
  adguard-widgets: 2342-8, now
  block-lan: 54-0, now
  easylist-chat: 153-12, now
  easylist-newsletters: 6651-428, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 73-1, never
  HUN-0: 2078-0, 1h.20m
  easylist: 75304-130, now
  easyprivacy: 32876-16302, now
  plowe-0: 3724-1160, now
  ublock-badware: 7494-139, now
  ublock-filters: 35401-571, now
  ublock-privacy: 667-180, now
  ublock-quick-fixes: 186-110, now
  ublock-unbreak: 2148-87, now
  urlhaus-1: 11030-0, 1h.19m
filterset (user): [array of 73 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 859 ms (selfie)
 maxAssetCacheWait: 213 ms
popupPanel:
 blocked: 2
 network:
  etrodo.de: 1
  trustedshops.com: 1
 extended:
  ##.privacy-notice:not(body):not(html):not([class*="-input"])
  ##div.privacy-notice
  ##.cookie-item
  ##.cookie-description
```
</details>

**Comment by mapx-** [comment]
`etrodo.de#@#div.privacy-notice`

@ryanbr
