### ISSUE TITLE
spotify.com: breakage

### ISSUE THREAD

**Issue by randomname-1** [uBlockOrigin/uAssets#20669]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://open.spotify.com/track/4WUepByoeqcedHoYhSNHRt`

### Description

Whenever I go to spotify on firefox and try to play one song or a playlist, it says "spotify can't play that right now", skips over the songs completely, goes to the ad (doesn't play the ad but goes to it) and repeats this cycle ad naseam.

### Other extensions used

None - I don't have any other extensions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="485" alt="Screenshot 2023-11-13 at 7 26 04 PM" src="https://github.com/uBlockOrigin/uAssets/assets/148517212/1fc1b624-cef7-4613-8435-0de9c256d0c8">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104197
 cosmetic: 43638
 scriptlet: 18842
 html: 1100
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36423-152, 3m
  ublock-badware: 7498-9, 3m
  ublock-privacy: 661-0, 3m
  ublock-unbreak: 2194-1, 3m
  ublock-quick-fixes: 183-7, 3m
  easylist: 75306-699, 3m
  easyprivacy: 32876-725, 3m
  urlhaus-1: 10655-0, 3m
  plowe-0: 3724-1, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 151 ms (selfie)
 maxAssetCacheWait: 48 ms
popupPanel:
 blocked: 22
 network:
  doubleclick.net: 11
  googleoptimize.com: 1
  googletagmanager.com: 1
  ninthdecimal.com: 1
  sentry.io: 5
  spotifycdn.com: 3
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by randomname-1** [comment]
Can add anymore screenshots needed.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by randomname-1** [comment]
Sorry I just logged back in. Try on Firefox, open any playlist. Confirmed it is still not working for me

**Comment by randomname-1** [comment]
No DNS with an adblocker or aguard, i don't have antivirus software. I have disabled all extensions on firefox. This is only happening on firefox btw, I tried on brave and it was working
