### ISSUE TITLE
patreon.com: breakage

### ISSUE THREAD

**Issue by cadef** [uBlockOrigin/uAssets#20660]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.patreon.com/messages?mode=user`

### Category

breakage

### Description

With uBO enabled, I am able to read messages from Patreon creators, but I am unable to send messages to creators. I can type a message, but clicking Send causes the message to be silently swallowed. Disabling uBO for Patreon.com and reloading the page fixes the issue.

### Other extensions used

Instapaper, Smile Always, Password Alert, 1Password

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104544
 cosmetic: 43592
 scriptlet: 18958
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75304-16, now
  easyprivacy: 32876-64, now
  plowe-0: 3724-1074, now
  ublock-badware: 7494-139, now
  ublock-filters: 35401-150, now
  ublock-privacy: 667-5, now
  ublock-quick-fixes: 186-110, now
  ublock-unbreak: 2148-32, now
  urlhaus-1: 11030-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 509 ms (selfie)
 maxAssetCacheWait: 226 ms
popupPanel:
 blocked: 6
 network:
  datadoghq-browser-agent.com: 1
  googletagmanager.com: 2
  pendo.io: 1
  sentry.io: 1
  siftscience.com: 1
```
</details>

**Comment by mapx-** [comment]
- open the uBO's logger: https://github.com/gorhill/uBlock/wiki/The-logger
- repeat the steps to get the issue
- go back into the uBO's logger and then copy and paste here all blocked requests

**Comment by mapx-** [comment]
if still broken add here the info requested

**Comment by mapx-** [comment]
without any useful info we cannot investigate the issue:

- we need the steps to reproduce the issue
- we need an account "to be able to read messages from Patreon creators"
- your `Troubleshooting Information`  (uBO dashboard, support tab)
- Are you willing to share with us your account credentials ? => I'll provide an email in case you confirm it
