### ISSUE TITLE
cignalplay.com: breakage

### ISSUE THREAD

**Issue by Elline312** [uBlockOrigin/uAssets#20670]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cignalplay.com/player/channel/taptv`

### Category

breakage

### Description

The player not shown while enable the site.

### Other extensions used

UBO Lite
Adguard Adblocker MV3

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/118500307/d7ead5ff-f2ba-4dcb-8e79-483325184e7b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104214
 cosmetic: 43640
 scriptlet: 19007
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, now
 default:
  user-filters: 0-0, never
  easylist: 75308-16, now
  easyprivacy: 32877-64, now
  plowe-0: 3724-1075, now
  ublock-badware: 7494-139, now
  ublock-filters: 35538-150, now
  ublock-privacy: 667-5, now
  ublock-quick-fixes: 186-110, now
  ublock-unbreak: 2150-32, now
  urlhaus-1: 10655-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1117 ms (selfie)
 maxAssetCacheWait: 390 ms
popupPanel:
 blocked: 13
 network:
  conviva.com: 3
  imasdk.googleapis.com: 1
  newrelic.com: 1
  sentry.io: 8
```
</details>

**Comment by mapx-** [comment]
- disable the other extensions: UBO Lite, Adguard Adblocker MV3
- test again

If does not work => we need an account => are you willing to give us your credentials in order to be able to investigate the issue ? (I'll provide an email address on your confirm)
