### ISSUE TITLE
[nsfw] hanime.tv: breakage

### ISSUE THREAD

**Issue by Equino-x** [uBlockOrigin/uAssets#20672]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hanime.tv/`

### Category

nuisance

### Description

Is anyone else having a problem with hanime? When I have ublock on or off for some reason the site is barely usable. All video links and nearly most of the pages on this site cannot function properly. I don't want to tinker around with the extension out of worry that I could screw something up with how the extension works on the site. 

### Other extensions used

EditThisCookie, Volume Master, Dark Reader. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/53284512/cc37c986-8676-413a-a010-07031a9a1309)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 110684
 cosmetic: 107667
 scriptlet: 23252
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 74903-117, 5m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 394-1, 5m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/MAL-Sync UI.txt: 39-39, 5m
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 1h.33m
 default:
  user-filters: 37-3, never
  easylist: 75308-75, 5m
  easyprivacy: 32877-130, 5m
  plowe-0: 3724-1076, 5m
  ublock-badware: 7494-139, 5m
  ublock-filters: 35539-495, 5m
  ublock-privacy: 667-5, 5m
  ublock-quick-fixes: 186-110, 5m
  ublock-unbreak: 2150-33, 5m
  urlhaus-1: 10655-0, 5m
filterset (user): [array of 37 redacted]
trustedset:
 added: [array of 32 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1899 ms (selfie)
 maxAssetCacheWait: 1160 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(set-constant, ABLK, false)
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
