### ISSUE TITLE
buscape.com.br: breakage

### ISSUE THREAD

**Issue by joaocqf** [uBlockOrigin/uAssets#20679]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.buscape.com.br/search?q=masterway%20isolado`

### Category

breakage

### Description

the products do not appear in the website

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.2
Chromium: 119
filterset (summary):
 network: 105869
 cosmetic: 47415
 scriptlet: 19423
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75308-16, now
  easyprivacy: 32877-64, now
  plowe-0: 3724-1075, now
  spa-1: 5736-66, now
  ublock-badware: 7494-139, now
  ublock-filters: 35539-176, now
  ublock-privacy: 667-5, now
  ublock-quick-fixes: 187-102, now
  ublock-unbreak: 2150-33, now
  urlhaus-1: 10850-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 994 ms (selfie)
 maxAssetCacheWait: 416 ms
popupPanel:
 blocked: 5
 network:
  buscape.com.br: 1
  googletagmanager.com: 2
  googletagservices.com: 1
  hotjar.com: 1
 extended:
  ##div[class^="Hits_Wrapper__"] > div[aria-labelledby^="product-c…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by JobcenterTycoon** [comment]
Hidden by `buscape.com.br##div[class^="Hits_Wrapper__"] > div[aria-labelledby^="product-card-"]:has(> a[target="_blank"])` in `AdGuard Spanish/Portuguese`

Maybe the filter got added because the links redirect to a 3p site.

@Yuki2718 please take a look.

**Comment by Yuki2718** [comment]
Yes, added for https://github.com/AdguardTeam/AdguardFilters/issues/133228 and looks legitimate blocking. cc: @Alex-302
