### ISSUE TITLE
amcplus.com: ads

### ISSUE THREAD

**Issue by apgiorgio** [uBlockOrigin/uAssets#20685]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.amcplus.com/shows/killing-eve/episodes/season-1-nice-face--1011058`

### Category

ads

### Description

Watching shows on AMC+ with a subscription with ads still shows ads in the middle of episodes.  I've only specifically confirmed this while watching Killing Eve, but I'd imagine this is still an issue with other shows as well.

### Other extensions used

LastPass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 122674
 cosmetic: 82808
 scriptlet: 35011
 html: 1104
listset (total-discarded, last-updated):
 added:
  adguard-generic: 79904-6139, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 36512-111, 9m
  ublock-badware: 7515-10, 9m
  ublock-privacy: 673-0, 9m
  ublock-unbreak: 2196-1, 9m
  ublock-quick-fixes: 157-13, 9m
  easylist: 75313-657, 9m
  easyprivacy: 32878-768, 9m
  urlhaus-1: 10745-0, 9m
  plowe-0: 3724-1, 9m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 572 ms
 maxAssetCacheWait: 246 ms
popupPanel:
 blocked: 278
 network:
  brightcove.com: 19
  googletagmanager.com: 1
  imrworldwide.com: 1
  mparticle.com: 251
  newrelic.com: 2
  youborafds01.com: 4
```
</details>

**Comment by mapx-** [comment]
If you want us to investigate the issue, are you willing to give us the credentials of your account? (I'll provide an email address in case you confirm it)

**Comment by mapx-** [comment]
@apgiorgio add a comment here if you agree to share your account details with us
