### ISSUE TITLE
brokers.bcbst.com: breakage

### ISSUE THREAD

**Issue by caseymcneir** [uBlockOrigin/uAssets#20684]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://brokers.bcbst.com/wps/myportal/broker/home/enroll/!ut/p/z1/04_iUlDg4tKPAFJABpSA0fpReYllmemJJZn5eYk5-hH6kVFm8X6B3haGhs4Gfv6eFiYGgWFOnu7Ols7GBu7m-l76UfgVFGQHKgIAjZDvDg!!/`

### Category

breakage

### Description

Can't click the Let's Enroll button with Ublock Origin active

### Other extensions used

Kaspersky Protection
Kaspersky Password Manager
Adobe Acrobat

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/150851826/061e2281-0d99-49a7-ab75-bd9edacc3682)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104433
 cosmetic: 43724
 scriptlet: 19025
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75313-16, now
  easyprivacy: 32878-64, now
  plowe-0: 3724-1075, now
  ublock-badware: 7511-140, now
  ublock-filters: 35621-150, now
  ublock-privacy: 679-5, now
  ublock-quick-fixes: 160-75, now
  ublock-unbreak: 2150-32, now
  urlhaus-1: 10850-0, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 371 ms (selfie)
 maxAssetCacheWait: 157 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
disable `Kaspersky Protection` and test again
