### ISSUE TITLE
[nsfw] chan.sankakucomplex.com: detection

### ISSUE THREAD

**Issue by dreminh** [uBlockOrigin/uAssets#20682]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chan.sankakucomplex.com/?tags=shexyo`

### Category

detection

### Description

so this is hentai website  NSFW, any way recently ublock does not work by default on this website , there a pop up and less than 5 sec if you do not click the "continue" button  it will redict you to disable block add page which is supper annoying , have have to disable java scrip but it disable all other function such as like and download  
sorry for bad eng

### Other extensions used

deepl translator , youtube dislike button back , duck duck go , Kaspersky anti virus 

### Screenshot(s)
![image](https://github.com/uBlockOrigin/uAssets/assets/23002308/0e6380ae-fb1e-44c3-9fee-c191a0bad10e)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104433
 cosmetic: 43724
 scriptlet: 19025
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75313-16, 1m
  easyprivacy: 32878-64, 1m
  plowe-0: 3724-1075, 1m
  ublock-badware: 7511-140, 1m
  ublock-filters: 35621-150, 1m
  ublock-privacy: 679-5, 1m
  ublock-quick-fixes: 160-75, 1m
  ublock-unbreak: 2150-32, 1m
  urlhaus-1: 10850-0, 1m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 274 ms (selfie)
 maxAssetCacheWait: 78 ms
popupPanel:
 blocked: 12
 no-scripting: true
 network:
  sankakucomplex.com: 5
  kaspersky-labs.com: 1
  otaserve.net: 4
  tsyndicate.com: 2
 extended:
  ##[data-revive-zoneid]
  ##a[href^="https://s.zlinkc.com/"]
  #@#.scad
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
```
</details>

**Comment by mapx-** [comment]
disable all other extensions (especially kaspersky), test again

**Comment by dreminh** [comment]
sadly not work

**Comment by dreminh** [comment]
is there any way to stop the web from doing enter this site : https://chan.sankakucomplex.com/static/disable_adblock

**Comment by gorhill** [comment]
Confirmed can't reproduce. Investigate your other extensions and/or browser settings.
