### ISSUE TITLE
[anti adblock] cityam.com

### ISSUE THREAD

**Issue by ReyCobin** [uBlockOrigin/uAssets#2068]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.cityam.com/260087/overzealous-eu-data-protection-regulations-more-likely-take`

### Describe the issue

Adblock paywall

### Versions

- Browser/version: ff
- uBlock Origin version: latest

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment]
Additonal fix for broken search functionality.
