### ISSUE TITLE
androidpolice.com: nuisance

### ISSUE THREAD

**Issue by kookieman12** [uBlockOrigin/uAssets#20681]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.androidpolice.com/android-teens-problem/`

### Category

nuisance

### Description

A huge overlay appears occupying 80% of the screen:"Create an account to keep reading

Lighter Ad Experience

Free Unlimited Access

Manage Newsletter Preferences

Access To New Features"A

### Other extensions used

bitwarden, bypass paywalls

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104406
 cosmetic: 43724
 scriptlet: 18859
 html: 1104
listset (total-discarded, last-updated):
 default:
  user-filters: 7-1, never
  ublock-filters: 36507-111, now
  ublock-badware: 7503-9, now
  ublock-privacy: 673-0, now
  ublock-unbreak: 2196-1, now
  ublock-quick-fixes: 157-13, now
  easylist: 75308-699, now
  easyprivacy: 32878-726, now
  urlhaus-1: 10850-0, now
  plowe-0: 3724-1, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 13 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 6
 autoUpdateDelayAfterLaunch: 10
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 767 ms (selfie)
 maxAssetCacheWait: 228 ms
popupPanel:
 blocked: 14
 network:
  androidpolice.com: 2
  advoncommerce.com: 2
  ebxcdn.com: 2
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 2
  skimresources.com: 2
  unpkg.com: 1
```
</details>

**Comment by Malgotra** [comment]
![Screenshot_20241109-204557](https://github.com/user-attachments/assets/434e9ba1-22d0-4cf6-a28d-9e0f25f16aa8)
Getting login pop-up.

**Comment by Malgotra** [comment]
Same happening with xda-developers.com

**Comment by stephenhawk8054** [comment]
Enable "uBlock fillets - Annoyances" list and test again.

**Comment by Malgotra** [comment]
Already enabled.

**Comment by stephenhawk8054** [comment]
@Malgotra Please give exact URL where you see the issue

**Comment by Malgotra** [comment]
> @Malgotra Please give exact URL where you see the issue

Hi. After testing issue disappear. Last commit you did resolve the issue. Issue was appearing when opening 2-3 articles in androidpolice.com as well as xda-developers.com then login pop-up appears (there is no exact URL because it appears in any article you read).
