### ISSUE TITLE
[nsfw] id.xhamster.com: breakage

### ISSUE THREAD

**Issue by AmmarToniboster** [uBlockOrigin/uAssets#20689]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://id.xhamster.com/`

### Category

breakage

### Description

Loading blank

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/150884606/e2ee451b-a01e-45e7-a9f1-292ded8d19f4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 108605
 cosmetic: 49096
 scriptlet: 19050
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  IDN-0: 9691-3, 12m
  easylist: 75313-25, 12m
  easyprivacy: 32878-66, 12m
  plowe-0: 3724-1075, 12m
  ublock-badware: 7522-140, 4m
  ublock-filters: 35627-169, 3m
  ublock-privacy: 679-5, 4m
  ublock-quick-fixes: 157-72, 4m
  ublock-unbreak: 2150-33, 4m
  urlhaus-1: 10745-0, 12m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 494 ms
 maxAssetCacheWait: 221 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(addEventListener-defuser, , pop)
  ##+js(set-constant, initials.yld-pdpopunder, )
  ##+js(set-cookie, ts_popunder, true, , reload, 1)
  ##+js(replace-node-text, script, popunder, , condition, popunder…
  ##+js(cookie-remover, video_view_count)
```
</details>

**Comment by BlazeFTL** [comment]
@AmmarToniboster Reset UBO & Remove Inbuilt Adblocker & Dns

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
