### ISSUE TITLE
deviantart.com: breakage

### ISSUE THREAD

**Issue by PinkTypholsion** [uBlockOrigin/uAssets#20686]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.deviantart.com/jacquirebriggs/art/Crystal-Story-2-10th-Anniversary-993254744`

`https://www.deviantart.com/jacquirebriggs/art/Amends-990670842`

### Description

Hi. After Deviantart made another greedy decision about locking promotional banners behind a paywall, ublock fucks up my own deviantart pages. They just nuked the page.

I have to turn it off to browse my own art. I want to know what code I need tfor this not fuck up,

### Other extensions used

none. (adblocker isn't affecting it)

### Screenshot(s)

[https://imgbox.com/QpZnlFJW](https://imgbox.com/QpZnlFJW)

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 115
filterset (summary):
 network: 115490
 cosmetic: 194562
 scriptlet: 29601
 html: 1293
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75133-7176, 4h.50m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94708-81076, 4h.54m
  adguard-social: 21980-724, 4h.51m
  fanboy-thirdparty_social: 68-0, 4h.53m
  fanboy-cookiemonster: 64112-15556, 3d.7h.37m
  fanboy-social: 16190-17, 3d.7h.40m
  ublock-annoyances: 5767-13, 3d.7h.38m
 default:
  user-filters: 0-0, never
  ublock-filters: 36130-115, 4d.12h.22m
  ublock-badware: 7439-5, 4d.12h.21m
  ublock-privacy: 661-0, 3d.7h.39m
  ublock-unbreak: 2194-0, 4d.12h.20m
  easylist: 75229-704, 2d.21h.35m
  easyprivacy: 32878-732, 4h.52m
  urlhaus-1: 10850-0, 4h.49m
  plowe-0: 3722-1, 6d.3h.51m
  ublock-quick-fixes: 157-2, 4h.48m
filterset (user): [empty]
trustedset:
 added: [array of 53 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5795 ms (selfie)
 maxAssetCacheWait: 5178 ms
```
</details>

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/17vptpg/new_deviantart_antiadblock_script/

**Comment by stephenhawk8054** [comment]
> edit: isolated to following 2 lists
>
> AdGuard Annoyances filter
>
> Fanboy's Annoyance List

```yml
added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75133-7176, 4h.50m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94708-81076, 4h.54m
  adguard-social: 21980-724, 4h.51m
  fanboy-thirdparty_social: 68-0, 4h.53m
  fanboy-cookiemonster: 64112-15556, 3d.7h.37m
  fanboy-social: 16190-17, 3d.7h.40m
  ublock-annoyances: 5767-13, 3d.7h.38m
```

Report to https://github.com/easylist/easylist/issues or https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by gorhill** [comment]
Unable to reproduce, works fine with default settings/lists. Also works fine with all stock _Annoyances_ lists enabled.

Investigate your customizations to uBO, other extensions, browser settings.
