### ISSUE TITLE
aagag.com: detection

### ISSUE THREAD

**Issue by qprhvms** [uBlockOrigin/uAssets#20695]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aagag.com/issue/?idx=1301276`

### Category

detection

### Description

comment section dectect ublock orgigin and disabled

### Other extensions used

none

did use with others nothing worked or ublock origin alone

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 125319
 cosmetic: 93172
 scriptlet: 35379
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 12m
  adguard-generic: 79913-492, 12m
  adguard-mobile: 8722-96, 12m
 default:
  user-filters: 32-3, never
  KOR-1: 4743-10, 12m
  easylist: 75313-1677, 12m
  easyprivacy: 32878-177, 12m
  plowe-0: 3724-1167, 12m
  ublock-badware: 7522-328, 12m
  ublock-filters: 35625-3892, 12m
  ublock-privacy: 680-7, 12m
  ublock-quick-fixes: 157-74, 12m
  ublock-unbreak: 2150-93, 12m
  urlhaus-1: 10745-0, 12m
filterset (user): [array of 32 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 383 ms (selfie)
 maxAssetCacheWait: 238 ms
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##.la
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
aagag.com#@#ins.adsbygoogle
aagag.com#@#.la
aagag.com##.la:style(height: 0px !important;)
```

or

```adb
aagag.com##+js(set-cookie, ab, 0)
```

cc @piquark6046

**Comment by piquark6046** [comment]
Resolved.
