### ISSUE TITLE
forvo.com: ads

### ISSUE THREAD

**Issue by tbertels** [uBlockOrigin/uAssets#20699]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://forvo.com/word/dinsdag/`

### Category

ads

### Description

After clicking twice on play buttons, an hover ad is shown.
Remove the cookies or try again the next day to reproduce.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d’écran 2023-11-15 135032](https://github.com/uBlockOrigin/uAssets/assets/3265870/d755c844-1d2f-41f9-b6d8-bbe5ba3d703b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 123645
 cosmetic: 52825
 scriptlet: 18995
 html: 1107
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36518-291, 6m
  ublock-badware: 7526-10, 6m
  ublock-privacy: 661-0, 6m
  ublock-unbreak: 2196-1, 6m
  ublock-quick-fixes: 154-1, 6m
  easylist: 75308-668, 6m
  easyprivacy: 32878-946, 6m
  urlhaus-1: 11300-0, 6m
  plowe-0: 3724-1, 6m
  FRA-0: 28556-116, 6m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2327 ms
 maxAssetCacheWait: 7 ms
popupPanel:
 blocked: 8
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 2
  quantcast.com: 2
  quantserve.com: 1
  ssm.codes: 1
 extended:
  ##.ad
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by tbertels** [comment]
Linked to https://static00.forvo.com/_presentation/assets/js/academy-banner.js

**Comment by gorhill** [comment]
It's self-promo.

> The rationale for including a specific filter in uBO's filter lists is the same as the [EasyList/EasyPrivacy policies](https://easylist.to/pages/policy.html) and also takes into account whether a filter requires uBO's extended filter syntax.

> Self-promotion (any type of advertising that promotes goods or services that are owned or operated by the domain owner and doesn’t get commercially compensated for by third parties (examples can include new features, new posts, newsletters, subscriptions to printed media products, merchandise etc.)) won't be targeted directly.

**Comment by mapx-** [comment]
maybe good for annoyances list

@ryanbr
