### ISSUE TITLE
rbtv77.autos: detection

### ISSUE THREAD

**Issue by AdarshB14** [uBlockOrigin/uAssets#20694]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://doram24t.live-streamfootball.link/others/icc-mens-cricket-world-cup-61543/india-vs-new-zealand.html?icg=SU4%3D&ilang=en`

### Category

detection

### Description

the whole site even to the straming sites can detect the adblocker

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104339
 cosmetic: 43726
 scriptlet: 19028
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75313-16, 2m
  easyprivacy: 32878-64, 2m
  plowe-0: 3724-1075, 2m
  ublock-badware: 7522-140, 2m
  ublock-filters: 35625-150, 2m
  ublock-privacy: 680-5, 2m
  ublock-quick-fixes: 157-72, 2m
  ublock-unbreak: 2150-32, 2m
  urlhaus-1: 10745-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 758 ms
 maxAssetCacheWait: 15 ms
popupPanel:
 blocked: 8
 network:
  acacdn.com: 1
  acdcdn.com: 1
  googletagmanager.com: 1
  precisionnight.com: 4
  yandex.ru: 1
 extended:
  ##+js(no-xhr-if, googlesyndication)
```
</details>

**Comment by stephenhawk8054** [comment]
I can't reproduce

**Comment by gorhill** [comment]
Confirmed unable to reproduce.

Be sure you have been thorough with:

> - [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.
> - [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.

For instance I can reproduce immediately after I enable ABP.
