### ISSUE TITLE
www1.myflixerx.to: ads

### ISSUE THREAD

**Issue by xashujo** [uBlockOrigin/uAssets#20691]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www1.myflixerx.to/home`

### Category

ads

### Description

There is just one leftover ad i keep getting for anime, I dont have this problem in safari using adguard

### Other extensions used

only ublockorigin on mullvad browser

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
<img width="1386" alt="Screenshot 2023-11-15 at 16 26 32" src="https://github.com/uBlockOrigin/uAssets/assets/150894036/c40c129f-5db0-4e32-b4a2-63cb6a1c1532">

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 119
filterset (summary):
 network: 102015
 cosmetic: 43724
 scriptlet: 19028
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75313-16, now
  easyprivacy: 32878-64, now
  plowe-0: 3724-1075, now
  ublock-badware: 7522-140, 1m
  ublock-filters: 35622-150, 1m
  ublock-privacy: 679-5, 1m
  ublock-unbreak: 2150-31, 1m
  urlhaus-1: 8425-1, 1m
  ublock-quick-fixes: 157-73, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5816 ms
 maxAssetCacheWait: 1774 ms
popupPanel:
 blocked: 4
 network:
  amung.us: 1
  coldvain.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by okiehsch** [comment]
@ryanbr 
`myflixerx.to##[href^="https://mangafire.to/"]`
