### ISSUE TITLE
[nsfw] hentaikun.com: ads

### ISSUE THREAD

**Issue by Simiao03** [uBlockOrigin/uAssets#20705]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hentaikun.com/manga/doujins-original-series/the-story-of-how-my-step-sister-and-i-got-closer-14120/`

### Category

ads

### Description

still shows banner ads that are intrusive

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104880
 cosmetic: 43715
 scriptlet: 19022
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75315-16, now
  easyprivacy: 32878-64, now
  plowe-0: 3724-1075, now
  ublock-badware: 7522-140, now
  ublock-filters: 35593-150, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 157-72, 34m
  ublock-unbreak: 2150-32, now
  urlhaus-1: 11300-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 633 ms (selfie)
 maxAssetCacheWait: 215 ms
popupPanel:
 blocked: 6
 network:
  hentaikun.com: 1
  effectivedisplayformats.com: 1
  google.com: 1
  googletagmanager.com: 1
  jads.co: 1
  juicyads.com: 1
```
</details>

**Comment by Simiao03** [comment]
NSFW site.

**Comment by gorhill** [comment]
This can be fixed in EasyList:

    hentaikun.com##.ads

cc @ryanbr
