### ISSUE TITLE
imgur.com: breakage

### ISSUE THREAD

**Issue by lhpitn** [uBlockOrigin/uAssets#20702]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://imgur.com/`

### Category

breakage

### Description

when i upload an image with ublock enabled i get a link with not safe for work warning even if the check is unchecked

### Other extensions used

singlefile 
i dont care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/45788285/a4406f49-a1ee-4af9-a1a7-640e72957aea)
![grafik](https://github.com/uBlockOrigin/uAssets/assets/45788285/f5c22376-9a0b-4224-a540-e3f471bc02d7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 107218
 cosmetic: 48478
 scriptlet: 18850
 html: 1106
listset (total-discarded, last-updated):
 default:
  user-filters: 7-1, never
  ublock-filters: 36475-122, now
  ublock-badware: 7526-10, now
  ublock-privacy: 674-0, now
  ublock-unbreak: 2196-1, now
  ublock-quick-fixes: 154-13, now
  easylist: 75315-705, now
  easyprivacy: 32878-735, now
  urlhaus-1: 11300-0, now
  plowe-0: 3724-1, now
  DEU-0: 7146-3, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2123 ms (selfie)
 maxAssetCacheWait: 431 ms
popupPanel:
 blocked: 6
 network:
  xeno-soswcrde4a-uc.a.run.app: 6
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce. You will need to investigate more on your side, including that it's not caused by something else than uBO. If we can't reproduce with default settings/lists, it's either you modified uBO's config, have other extensions causing the issue, or your customized your browser's config.
