### ISSUE TITLE
betterprogramming.pub: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#20701]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://betterprogramming.pub/the-fastest-way-to-render-the-dom-e3b226b15ca3`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/e2c86965-bb06-4e0c-b028-7647487da21b)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 109700
 cosmetic: 102242
 scriptlet: 27358
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 10454-1, now
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 80-4, now
  easylist-annoyances: 4179-34, now
  easylist-notifications: 2876-82, now
  fanboy-cookiemonster: 48861-217, now
  ublock-annoyances: 5851-79, now
  ublock-cookies-easylist: 553-553, now
 default:
  user-filters: 33-0, never
  easylist: 75315-22, now
  easyprivacy: 32878-151, now
  plowe-0: 3724-1075, now
  ublock-badware: 7522-142, now
  ublock-filters: 35593-279, now
  ublock-privacy: 680-6, now
  ublock-quick-fixes: 157-76, now
  ublock-unbreak: 2150-36, now
  urlhaus-1: 11300-0, now
filterset (user): [array of 33 redacted]
trustedset:
 added: [array of 64 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1221 ms (selfie)
 maxAssetCacheWait: 290 ms
popupPanel:
 blocked: 9
 network:
  betterprogramming.pub: 5
  branch.io: 1
  cloudflareinsights.com: 1
  google.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(set-local-storage-item, 201805-policy|accepted, 1)
```
</details>

**Comment by gorhill** [comment]
Enable _"AdGuard – Popup Overlays"_.
