### ISSUE TITLE
reuters.com: breakage

### ISSUE THREAD

**Issue by Geyser182** [uBlockOrigin/uAssets#20708]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reuters.com/world/europe/storm-ciaran-lashes-northern-europe-with-strong-winds-rain-one-killed-france-2023-11-02/`

### Category

breakage

### Description

Reuters news reports show the videos as a black box, and I have no idea if it is an ad or video, because there is no context behind the black box. I would appreciate any fixes if they can be done. 

Thank you for your time.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (31)](https://github.com/uBlockOrigin/uAssets/assets/147728515/fd3d518a-a46b-442b-831d-fd464558f4de)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 258551
 cosmetic: 90203
 scriptlet: 35701
 html: 1106
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt: 717-8, 17m
  adguard-generic: 80170-7209, 18m
  adguard-mobile: 8726-100, 18m
  adguard-spyware-url: 1310-139, 17m
  adguard-spyware: 69884-16649, 17m
  block-lan: 54-0, 17m
  curben-phishing: 80468-27, 17m
 default:
  user-filters: 61-11, never
  ublock-filters: 36475-229, 18m
  ublock-badware: 7526-10, 18m
  ublock-privacy: 674-21, 18m
  ublock-unbreak: 2197-2, 18m
  ublock-quick-fixes: 154-13, 18m
  easylist: 75358-596, 17m
  easyprivacy: 32882-774, 17m
  urlhaus-1: 11300-0, 17m
  plowe-0: 3725-1, 17m
filterset (user): [array of 61 redacted]
userSettings: [none]
hiddenSettings:
 autoUpdatePeriod: 1
supportStats:
 allReadyAfter: 1371 ms (selfie)
 maxAssetCacheWait: 926 ms
popupPanel:
 blocked: 68
 network:
  abtasty.com: 2
  adnxs.com: 1
  ads-twitter.com: 1
  chartbeat.com: 2
  connatix.com: 1
  datadoghq-browser-agent.com: 1
  datadome.co: 1
  dianomi.com: 1
  doubleclick.net: 2
  en25.com: 1
  facebook.net: 1
  go-mpulse.net: 2
  google-analytics.com: 1
  permutive.com: 5
  pub.network: 1
  qualtrics.com: 1
  scaredsnakes.com: 1
  scorecardresearch.com: 1
  segment.com: 1
  segment.io: 36
  sophi.io: 1
  tru.am: 2
  wsod.com: 1
  yimg.com: 1
 extended:
  ##[data-testid="ResponsiveAdSlot"]
  ##div[class^="ad-slot__"]
  ##[class^="workspace-article-banner"]
  ##div[class^="regular-article-layout__inner_"]:has(> div[data-te…
  ##div[class^="regular-article-layout__refinitiv_workspace"]:has(…
  ##.site-header__show-nav__3po5A .site-header__inner-sticky__1fm3…
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(set-constant, admiral, noopFunc)
  ##+js(set-local-storage-item, ajs_anonymous_id, null)
  ##+js(abort-current-script, navigator, Flags.autoRecov)
  ##+js(abort-on-property-read, Object.prototype.autoRecov)
```

</details>

**Comment by mapx-** [comment]
add

```
||pixel.adsafeprotected.com/services/pub?$removeparam=slot,badfilter
||pixel.adsafeprotected.com/services/pub?$removeparam=anId,badfilter
```

@Alex-302

**Comment by Yuki2718** [comment]
@Alex-302 Seems AG is not affected as `@@||pixel.adsafeprotected.com/services/pub$domain=reuters.com` also exempt removeparam too, but I doubt this is intended behavior. Even with
```
@@||pixel.adsafeprotected.com/services/pub$domain=reuters.com,badfilter
@@||pixel.adsafeprotected.com/services/pub$xmlhttprequest,domain=reuters.com
||pixel.adsafeprotected.com/services/pub?$removeparam=anId,important
```
`anId` is not removed, this means you have to give up removing parameter if there's any sort of exception.

**Comment by Alex-302** [comment]
In AdGuard `removeparam` without modifier is applied only to `document` type.
Added exclusions for uBO.

**Comment by Alex-302** [comment]
With AG it also must be blocked, just rules are old.
Updated https://github.com/AdguardTeam/AdguardFilters/commit/1b5b1498d3464ffc23afef210f0e5b1e2f4f9240
