### ISSUE TITLE
softwareok.com: ads

### ISSUE THREAD

**Issue by Nicol1B13** [uBlockOrigin/uAssets#20709]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.softwareok.com/?`

### Category

ads

### Description

On the right-hand side of the page, and sometimes at the top, ads are displayed that it doesn't seem possible to block.
These ads appear everywhere on every page of the site and on every browser I've tested.

### Other extensions used

Various :
Disconnect
ScriptSafe
Httpseverywhere
Privacybadher
...

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture d'écran 2023-11-15 130648](https://github.com/uBlockOrigin/uAssets/assets/150957803/aecb251a-db53-4a2b-bef6-53f5f576c0da)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 117
filterset (summary):
 network: 129151
 cosmetic: 101160
 scriptlet: 25141
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28067-32, 21m
  adguard-popup-overlays: 26206-66, 21m
  ublock-annoyances: 5847-97, 25m
  ublock-cookies-adguard: 549-549, 21m
 default:
  user-filters: 36-0, never
  FRA-0: 28558-39, 21m
  easylist: 75358-131, 21m
  easyprivacy: 32882-390, 21m
  plowe-0: 3725-1088, 21m
  ublock-badware: 7522-154, 21m
  ublock-filters: 35596-303, 21m
  ublock-privacy: 680-6, 21m
  ublock-quick-fixes: 157-76, now
  ublock-unbreak: 2151-38, 21m
  urlhaus-1: 11300-0, 21m
filterset (user): [array of 36 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 735 ms (selfie)
 maxAssetCacheWait: 219 ms
popupPanel:
 blocked: 3
 network:
  countok.de: 2
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle
  ###cookiebar
  ##div > table > tbody > tr > td > table > tbody > tr > td
```
</details>

**Comment by mapx-** [comment]
Disable all other extensions, use only the default settings in uBO, test again

**Comment by gorhill** [comment]
I get the ad only when I enable Privacy Badger. That's why we ask:

> - [x] I am not using uBlock Origin (uBO) along with other content blocker extensions.

It help to unburden volunteers here when answering truthfully.
