### ISSUE TITLE
dizipub.club: ads

### ISSUE THREAD

**Issue by fadedninna** [uBlockOrigin/uAssets#20700]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dizipub.club/house-m-d-8-sezon-22-bolum-izle?player=0`

### Category

ads

### Description

When I start the video, the ad itself does not appear, but its sound is heard.

### Other extensions used

I dont use any extensions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 106533
 cosmetic: 54210
 scriptlet: 20642
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  TUR-0: 13811-10, now
  easylist: 75315-37, now
  easyprivacy: 32878-69, now
  plowe-0: 3724-1076, now
  ublock-badware: 7522-140, now
  ublock-filters: 35593-157, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 157-72, 1h.44m
  ublock-unbreak: 2150-33, now
  urlhaus-1: 11300-0, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 204 ms (selfie)
 maxAssetCacheWait: 66 ms
popupPanel:
 blocked: 24
 network:
  ampproject.org: 18
  diken.xyz: 1
  filese.me: 1
  jwpcdn.com: 1
  jwpltx.com: 1
  staticmoly.me: 1
  yandex.ru: 1
 extended:
  ###mPlayerFd
  ##+js(set-constant, initOpen, undefined)
```
</details>

**Comment by gorhill** [comment]
> 403
> Üzgünüz, Aradığınız sayfa bulunamadı!
> Sunucu kaynaklı bir sorun oluştu, lütfen daha sonra tekrar deneyiniz.

**Comment by mapx-** [comment]
@fadedninna 

test this filter
`||alabamaimage.online^$websocket,domain=contentx.me`

**Comment by fadedninna** [comment]
> turkish ip required
> 
> @fadedninna
> 
> test this filter
> 
> ```
> ||alabamaimage.online^$websocket,domain=contentx.me
> ```

I don't know how to try this filter. Is there a guide or smt?

**Comment by mapx-** [comment]
update uBO filters list

**Comment by fadedninna** [comment]
> update uBO filters list

I did update, issue still continues but this time if u click twice on the player ad's voice can be heard

**Comment by mapx-** [comment]
update again in 5-10 min

**Comment by fadedninna** [comment]
@mapx- you fixed it, thank you.
