### ISSUE TITLE
azmath.info: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#20711]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://azmath.info/transitivity-and-its-failures-math-with-bad-drawings.html`

### Category

detection

### Description

d

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium Mobile: 116
filterset (summary):
 network: 110611
 cosmetic: 36380
 scriptlet: 19111
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 31-0, never
  IDN-0: 9691-3882, now
  adguard-mobile: 8726-45, now
  easylist: 75358-16054, now
  easyprivacy: 32882-75, now
  plowe-0: 3725-1151, now
  ublock-badware: 7516-141, now
  ublock-filters: 35911-422, now
  ublock-privacy: 680-6, now
  ublock-quick-fixes: 157-72, now
  ublock-unbreak: 2156-36, now
  urlhaus-1: 11300-0, now
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2739 ms (selfie)
 maxAssetCacheWait: 234 ms
popupPanel:
 blocked: 11
 network:
  azmath.info: 3
  doubleclick.net: 2
  exmarketplace.com: 1
  googlesyndication.com: 4
  shriftskats.com: 1
 extended:
  ##+js(set-constant, count, 0)
  ##+js(abort-on-property-read, SMart1)
  ##+js(noeval-if, chp_ad)
```
</details>

**Comment by huyszn** [comment]
Add to My filters:

`azmath.info##+js(rmnt, script, mdp)`

**Comment by smaragdina** [comment]
> Add to My filters:
> 
> `azmath.info##+js(rmnt, script, mdp)`

thank you bro its work now...

**Comment by JobcenterTycoon** [comment]
Does the filter i added in https://github.com/uBlockOrigin/uAssets/commit/64fb424551eda94b5a78238400f788da8b144e85 doesn’t work? The fix works fine for me.
