### ISSUE TITLE
chip.de: breakage

### ISSUE THREAD

**Issue by fel-icks** [uBlockOrigin/uAssets#20710]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.chip.de/download/46949_Web-Apps/`

### Category

breakage

### Description

Icons in list of softwares are grey because of blocking by uBo :-(

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-11-15 230149](https://github.com/uBlockOrigin/uAssets/assets/150970545/44d01c8c-8450-4cc3-98ff-8bfb3c1491e2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 107259
 cosmetic: 48488
 scriptlet: 18850
 html: 1106
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36478-122, 5m
  ublock-badware: 7526-10, 5m
  ublock-privacy: 674-0, 5m
  ublock-unbreak: 2197-1, 5m
  ublock-quick-fixes: 154-13, 5m
  easylist: 75358-709, 5m
  easyprivacy: 32882-735, 5m
  urlhaus-1: 11300-0, 5m
  plowe-0: 3725-1, 5m
  DEU-0: 7154-3, 5m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6014 ms (selfie)
 maxAssetCacheWait: 126 ms
popupPanel:
 blocked: 4
 network:
  chip.de: 1
  cleverpush.com: 1
  hotjar.com: 1
  iocnt.net: 1
 extended:
  ###R1C3[role="complementary"]
  ###R1C1[role="complementary"]
  ###contentad-top-adsense-1
  ##.FC.mt-md-so[role="complementary"]
  ##a[href^="https://campaigns.avira.com/"] > img
  ##a[href^="https://prf.hn/click/"] > img
  ##a[href^="https://www.chip.de/downloads/"][href$=".html"] div >…
  ##span.Button--Clickout[data-submit]
  ##.fb > .Listing > div > h2:has-text(/Gesponsert|Bezahlte Empfeh…
  ##.Listing > div[class]:has(path[d$="92.456,64.241 z"])
  ##:root:style(--topbanner-height-min:unset!important;--topbanner…
  ##+js(json-prune, enabled, force_disabled)
```
</details>

**Comment by JobcenterTycoon** [comment]
Caused by `chip.de##a[href^="https://www.chip.de/downloads/"][href$=".html"] div > figure > img` in EL germany.
