### ISSUE TITLE
prmovies.green: detection

### ISSUE THREAD

**Issue by hamza-510** [uBlockOrigin/uAssets#20716]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://prmovies.green/pippa-2023-Watch-online-full-movie/`

### Category

detection

### Description

Server 1 works fine but server 2 has the better quality videos on it and that detects adblockers and doesn't allow me to play the video. 

 

### Other extensions used

Chrome Remote Desktop
Betternet VPN (disconnected)
Google Keep

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-11-16 142500](https://github.com/uBlockOrigin/uAssets/assets/138299463/1a3b253c-874c-4680-82e8-5dd6482c56b5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 105195
 cosmetic: 43756
 scriptlet: 19025
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75434-16, 1m
  easyprivacy: 32889-64, 1m
  plowe-0: 3725-1076, 1m
  ublock-badware: 7522-140, 1m
  ublock-filters: 35602-153, 1m
  ublock-privacy: 680-5, 1m
  ublock-quick-fixes: 148-67, 1m
  ublock-unbreak: 2151-32, 1m
  urlhaus-1: 11525-0, 1m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 425 ms (selfie)
 maxAssetCacheWait: 101 ms
popupPanel:
 blocked: 16
 network:
  alleviatepracticableaddicted.com: 1
  elemoltwigful.com: 1
  goimeiny.com: 1
  googlesyndication.com: 1
  jwpcdn.com: 1
  marazma.com: 1
  netu.ac: 3
  popmansion.com: 1
  sadjklq.com: 1
  sharethis.com: 2
  ssindserving.com: 1
  thefacux.com: 1
  wraithydecides.com: 1
 extended:
  ##.content-kuss-ads
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-current-script, Math, break;case $.)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, doSecondPop)
```
</details>

**Comment by huyszn** [comment]
Add to My filters:
`netu.ac##+js(set, adblockcheck, false)`

**Comment by hamza-510** [comment]
This worked perfectly, Thank you so much!!
