### ISSUE TITLE
downfile.site: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#20719]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://downfile.site/`

### Category

detection

### Description

d

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium Mobile: 116
filterset (summary):
 network: 110884
 cosmetic: 36416
 scriptlet: 19115
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 31-0, never
  IDN-0: 9691-3882, now
  adguard-mobile: 8729-45, now
  easylist: 75434-16054, now
  easyprivacy: 32889-75, now
  plowe-0: 3725-1151, now
  ublock-badware: 7516-141, now
  ublock-filters: 35918-423, now
  ublock-privacy: 680-6, now
  ublock-quick-fixes: 148-67, 56m
  ublock-unbreak: 2156-36, now
  urlhaus-1: 11525-0, now
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2842 ms (selfie)
 maxAssetCacheWait: 225 ms
popupPanel:
 blocked: 13
 network:
  downfile.site: 4
  doubleclick.net: 1
  googlesyndication.com: 6
  shriftskats.com: 2
 extended:
  ##+js(set-constant, count, 0)
  ##+js(abort-on-property-read, SMart1)
  ##+js(noeval-if, chp_ad)
```
</details>

**Comment by mapx-** [comment]
No detection on my side in FF mobile.
What browser are you using @D4niloMR ?
