### ISSUE TITLE
ielts.idp.com: breakage

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#20718]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [ ] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [ ] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ielts.idp.com/hongkong`

### Category

breakage

### Description

Website doesn't respond, possibly because uBO removed the cookie notice.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 120
filterset (summary):
 network: 201182
 cosmetic: 125419
 scriptlet: 25608
 html: 1293
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  adguard-mobile: null
  plowe-0: null
  CHN-0: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 22601-12, 3d.21h.52m
  adguard-spyware-url: 1310-88, 3d.21h.52m
  block-lan: 54-0, 3d.21h.52m
  curben-phishing: 80250-27, 23h.8m
  easylist-annoyances: 4175-94, 3d.21h.52m
  easylist-chat: 153-0, 3d.21h.52m
  fanboy-cookiemonster: 48865-289, 3d.21h.52m
  ublock-cookies-easylist: 566-0, 3d.21h.52m
  easylist-newsletters: 6649-13, 3d.21h.52m
  easylist-notifications: 2873-4, 3d.21h.52m
  fanboy-social: 16194-7, 3d.21h.52m
  ublock-annoyances: 5832-602, 3d.21h.52m
 default:
  ublock-filters: 36475-117, 3d.21h.51m
  ublock-badware: 7456-5, 3d.21h.51m
  ublock-privacy: 662-0, 3d.21h.51m
  ublock-unbreak: 2199-1, 3d.21h.51m
  ublock-quick-fixes: 145-1, 37m
  easylist: 75265-369, 3d.21h.51m
  easyprivacy: 32873-125, 3d.21h.51m
  urlhaus-1: 10745-0, 23h.8m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings:
 autoCommentFilterTemplate: none
 trustedListPrefixes: ublock- user- https://get.letsblock.it/list/10ed17c7-db36-40f6-86d0-00cad74ab372.txt
supportStats:
 allReadyAfter: 2119 ms (selfie)
 maxAssetCacheWait: 1394 ms
popupPanel:
 blocked: 6
 network:
  googletagmanager.com: 4
  marketo.net: 2
 extended:
  ##.cookie-banner-overlay
  ##div.cookie-wrapper
  ##div.cookie-banner
```
</details>

**Comment by mapx-** [comment]
add

`ielts.idp.com##+js(set-cookie, acceptCookie, true)`

@ryanbr
