### ISSUE TITLE
nypost.com: nuisance can no longer scroll down the webpage

### ISSUE THREAD

**Issue by ojnyc** [uBlockOrigin/uAssets#20725]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nypost.com/`

### Category

nuisance

### Description

Can no longer scroll down the webpage.
An invisible overlay of some sort is freezing the page.
I did block a few elements but I have not been successful in fixing the issue.
Thanks!

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2560" alt="Screen Shot 2023-11-16 at 1 23 53 PM" src="https://github.com/uBlockOrigin/uAssets/assets/151069810/ec04955b-2ee3-4686-abaa-28289b27a4c1">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 116
filterset (summary):
 network: 105233
 cosmetic: 43766
 scriptlet: 19037
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 11-0, never
  easylist: 75448-16, now
  easyprivacy: 32893-64, now
  plowe-0: 3725-1076, now
  ublock-badware: 7522-140, now
  ublock-filters: 35617-154, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 113-46, now
  ublock-unbreak: 2152-32, now
  urlhaus-1: 11555-0, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 4 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1749 ms (selfie)
 maxAssetCacheWait: 144 ms
popupPanel:
 blocked: 35
 no-popups: true
 network:
  nypost.com: 1
  adlightning.com: 1
  adsafeprotected.com: 2
  advertising.com: 1
  amazon-adsystem.com: 1
  bounceexchange.com: 1
  d1z2jf7jlzjs58.cloudfront.net: 1
  doubleclick.net: 1
  google-analytics.com: 1
  googleadservices.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  media.net: 1
  merequartz.com: 2
  p-n.io: 1
  permutive.app: 1
  scorecardresearch.com: 1
  speedcurve.com: 1
  spot.im: 9
  typekit.net: 1
  unrulymedia.com: 1
  videoplayerhub.com: 1
  wp.com: 1
  zqtk.net: 1
 extended:
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.dfp-ad
  ##.ad-wrapper
  ##.ad--container
  ##.ad__wrapper
  ##.ad__placeholder
  ##.ad__label
  ##.widget_nypost_dfp_ad_widget
  ##._8O9Z-ltD
  ##._1U8keQ4i
  ##.d-block-md.d-none.p-bottom-none.site-container
  ##.dgEhJe6g
  ##.fEy1Z2XT
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(abort-on-property-write, _sp_)
  ##+js(json-prune, dataLayer.trackingId user.trackingId)
  ##+js(cookie-remover, blaize_tracking_id)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by D4niloMR** [comment]
https://github.com/uBlockOrigin/uAssets/assets/70459964/c948b33f-2348-4645-929c-96dc1f9f68ee

Anti-adblock

`||meadowlullaby.com^`

You can't scroll because you hided the popup

**Comment by D4niloMR** [comment]
@mapx- 
Also on:
`https://pagesix.com/2023/11/16/entertainment/mauricio-umansky-tells-people-asking-about-his-marriage-to-fk-off/`
`https://decider.com/2023/11/16/mob-wives-star-renee-graziano-checked-rehab-overdosing-bad-batch-drugs/`

Btw, usually admiral domains don't get blocked, is it because of lawsuit?

**Comment by mapx-** [comment]
admiral domains are added by EP and Peter Lowe's lists
