### ISSUE TITLE
aagag.com: detection

### ISSUE THREAD

**Issue by qprhvms** [uBlockOrigin/uAssets#20730]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://aagag.com/issue/?idx=1310716`

### Description

uBlockOrigin disabled by ad block blocker
at comment section

recently i did put in same issue and got msg back with

```
aagag.com#@#ins.adsbygoogle
aagag.com#@#.la
aagag.com##.la:style(height: 0px !important;)
```
or

`aagag.com##+js(set-cookie, ab, 0)`

it did work for 1 day and after that went back to blocked by blocker :(

### Other extensions used

none 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 125564
 cosmetic: 93281
 scriptlet: 35422
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1m
  adguard-generic: 80263-493, 1m
  adguard-mobile: 8733-95, 1m
 default:
  user-filters: 26-2, never
  KOR-1: 4750-10, 1m
  easylist: 75467-1716, 1m
  easyprivacy: 32894-177, 1m
  plowe-0: 3725-1168, 1m
  ublock-badware: 7522-328, 1m
  ublock-filters: 35624-3892, 1m
  ublock-privacy: 680-7, 1m
  ublock-quick-fixes: 113-48, 1m
  ublock-unbreak: 2152-93, 1m
  urlhaus-1: 10665-0, 1m
filterset (user): [array of 26 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 500 ms (selfie)
 maxAssetCacheWait: 121 ms
```
</details>

**Comment by dportvine** [comment]
https://github.com/List-KR/List-KR/issues/769

**Comment by mapx-** [comment]
right, there is a thread at regional list repo
