### ISSUE TITLE
music.apple.com: breakage

### ISSUE THREAD

**Issue by matinlunaire** [uBlockOrigin/uAssets#20735]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://music.apple.com/`

### Category

breakage

### Description

It is impossible to subscribe to Apple Music. Immediately after pressing "Subscribe Now" in the subscription details pop-up, a red warning message saying "An error has occurred. Try again later" appears. The problem is not present without uBlock.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231117-181226](https://github.com/uBlockOrigin/uAssets/assets/109166520/357aaba2-0f98-40af-8c8e-8b1ef8996fc1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 120
filterset (summary):
 network: 123063
 cosmetic: 72325
 scriptlet: 20289
 html: 1166
listset (total-discarded, last-updated):
 added:
  RUS-0: 40143-157, 1h.6m
 default:
  user-filters: 0-0, never
  ublock-filters: 36841-131, 1m
  ublock-badware: 7525-10, 1m
  ublock-privacy: 674-0, 1m
  ublock-unbreak: 2206-1, 1m
  ublock-quick-fixes: 114-13, 1m
  adguard-mobile: 8733-100, 1m
  easylist: 75467-774, 1m
  easyprivacy: 32894-731, 1m
  urlhaus-1: 10605-0, 1m
  plowe-0: 3715-1, 1m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6860 ms
 maxAssetCacheWait: 3444 ms
popupPanel:
 blocked: 32
 network:
  apple.com: 32
```
</details>

**Comment by mapx-** [comment]
@dimisa-RUAdList are you able to reproduce the issue ?

**Comment by dimisa-RUAdList** [comment]
@matinlunaire 
Disabling which filters solves the problem?

**Comment by matinlunaire** [comment]
@dimisa-RUAdList after disabling the default lists one-by-one, I think I have narrowed it down to EasyPrivacy

**Comment by mapx-** [comment]
@matinlunaire 

- open uBO's logger
- keep only EP enabled 
- repeat the steps to get the issue
- copy & paste here all the blocked requests you find in the logger (or a screenshot)

**Comment by matinlunaire** [comment]
<details><summary>Logger output</summary>

```
+13
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_cs_unidentified
```
```
+12
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_cs_unidentified
```
```
+11
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_cs_unidentified
```
```
+11
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_cs_unidentified
```
```
+11
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_cs_unidentified
```
```
+10
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_its_music_main
```
```
+9
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_its_music_main
```
```
+8
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_its_music_main
```
```
+8
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_its_music_main
```
```
+8
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_its_music_main
```
```
+8
||xp.apple.com^$~ping
--
music.apple.com
1
post
xhr
https://xp.apple.com/report/2/xp_amp_web_error_log
```
```
+7
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_perf
```
```
+6
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_perf
```
```
+6
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_perf
```
```
+6
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_perf
```
```
+5
||xp.apple.com^$~ping
--
music.apple.com
1
get
xhr
https://xp.apple.com/config/1/report/xp_amp_music_perf
```
```
+3
||xp.apple.com^$~ping
--
music.apple.com
1
post
xhr
https://xp.apple.com/report/2/xp_amp_music_cs_unidentified
```
```
+3
||xp.apple.com^$~ping
--
music.apple.com
1
post
xhr
https://xp.apple.com/report/2/xp_its_music_main
```
```
+3
||xp.apple.com^$~ping
--
music.apple.com
1
post
xhr
https://xp.apple.com/report/2/xp_its_music_main
```
```
+0
||xp.apple.com^$~ping
--
music.apple.com
1
post
xhr
https://xp.apple.com/report/2/xp_amp_music_perf
```
</details>

**Comment by Yuki2718** [comment]
@matinlunaire Add `||xp.apple.com^$~ping,badfilter` to My filters, refresh the page and see if the problem is solved.

**Comment by matinlunaire** [comment]
@Yuki2718 yes, it is

**Comment by Yuki2718** [comment]
@ryanbr

**Comment by JackerGamer** [comment]
Hi there, I encountered a similar issue when using uBOL: I’m unable to subscribe to plans, as it keeps getting stuck on the payment loading screen. It works normally after switching the mode to “No filtering” or disabling the extension. My browser is Chrome for Windows 140.0.7339.81, and I’m not using any other extensions.

<img width="640" height="303" alt="Image" src="https://github.com/user-attachments/assets/48391e94-fc97-4af5-85f9-2a454f23fcf4" />

**Comment by stephenhawk8054** [comment]
Please share your troubleshooting information in uBOL.
