### ISSUE TITLE
bitshare.link: nuisance

### ISSUE THREAD

**Issue by ItsProfessional** [uBlockOrigin/uAssets#20733]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://bitshare.link/dpl/5l90z6aa4op3tu`

### Description

skip the timer

### Other extensions used

None

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by BlazeFTL** [comment]
The Link Doesn't Work

**Comment by ItsProfessional** [comment]
I guess it automatically expires. Here's a way to generate a fresh link:
Go [here](https://steamcommunity.com/app/431960/workshop/) and copy the link of a wallpaper ([example wallpaper](https://steamcommunity.com/sharedfiles/filedetails/?id=3082427731)). Then, go [here](https://ggntw.com/steam) and paste the link. It'll lead you to the `bitshare.link` shortlink.

**Comment by BlazeFTL** [comment]
Needs Account?...I Dont Get Redirected Anywhere

**Comment by ItsProfessional** [comment]
No account needed. Try pasting [this URL](https://steamcommunity.com/sharedfiles/filedetails/?id=3064596457) on the text field on the ggntw.com page, you should see a download button. After clicking it, you should be on the `bitshare.link` page.

**Comment by BlazeFTL** [comment]
Unfortunately I Dont Get Any Page With Timers...I Click Download & The File Gets Downloaded...Maybe Someone Else Will Fix It

**Comment by dportvine** [comment]
<details>
<summary>Video & Screen</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/bf511a90-596c-4879-8240-bd888f8ea098

![2023-11-17_221158](https://github.com/uBlockOrigin/uAssets/assets/111344219/e3949d53-94b2-4235-ae21-a6d168509a5c)
</details>

It didn't works for me.

```adb
bitshare.link##+js(nano-setInterval-booster)
bitshare.link##+js(nano-setTimeout-booster)
```

@dimisa-ruadlist

Can you chek? Pasting this URL `https://steamcommunity.com/sharedfiles/filedetails/?id=3064596457` ~> on the `https://ggntw.com/steam`, then click `Скачать`.
