### ISSUE TITLE
I have a problem with "cosmetics filtering"

### ISSUE THREAD

**Issue by Dektsuki** [uBlockOrigin/uAssets#20737]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.youtube.com/watch?v=1NJkxVQsSIo`

### Description

When I have the "cosmetics filter" on and when I enter a stream on YouTube, the live chat disappears. I started to think I had manually "deleted" it by accident, but I hadn't. Then I remembered that the last thing I did was turn on "cosmetic filtering" to remove the ghost banners left on the YouTube home page. Is there any way to fix this problem? Note: I have verified that the "aesthetic filtering" is the problem, because when you disable it, the chat reappears, but also the ghost banners on the YouTube home page.

### Other extensions used

1.- Return Youtube Dislike
2.- SponsorBlock para Youtube
3.- TamperMonkey Beta (2 scripts actives : "Youtube Bolder Subtitles" )
4.- Stylish (no active en youtube)
5.- Youtube Short Block 
6.- Google Translate 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 

https://imgur.com/a/KaPTbKo (Filtre cosmetic active : No chat stream)
https://imgur.com/a/Q5twHiQ (Filtre cosmetic no active )
https://imgur.com/a/9qagDnY (Filtre cosmetic no active = Ads)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.4
Chromium: 119
filterset (summary):
 network: 106810
 cosmetic: 50251
 scriptlet: 19471
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 167-2, never
  easylist: 75478-16, 17m
  easyprivacy: 32894-64, 17m
  plowe-0: 3715-1075, 17m
  spa-0: 3767-20, 17m
  spa-1: 5746-225, 17m
  ublock-badware: 7527-140, 17m
  ublock-filters: 35646-182, 17m
  ublock-privacy: 680-5, 17m
  ublock-quick-fixes: 115-51, 17m
  ublock-unbreak: 2155-34, 17m
  urlhaus-1: 10605-0, 17m
filterset (user): [array of 171 redacted]
userSettings: [none]
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 3444 ms
 maxAssetCacheWait: 22 ms
popupPanel:
 blocked: 4
 network:
  github.com: 3
  xeno-soswcrde4a-uc.a.run.app: 1

```
</details>

**Comment by mapx-** [comment]
You have 4 addons impacting YT, disable them and test again.

**Comment by Dektsuki** [comment]
I have disabled all extensions that affect YouTube except Google Translate (as this does not cause problems on any pages), but still the chat in any "live" video still does not appear.
I also have the “cosmetic filter” active, so as I mentioned at the beginning it is a problem with the cosmetic filter. 
Link : ' https://imgur.com/a/3rbrUXc  '

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by Dektsuki** [comment]
It has already been repaired. I just needed to reset the extension to "factory settings". Thank you so much.
