### ISSUE TITLE
niagarathisweek.com: ads

### ISSUE THREAD

**Issue by unbeatable-101** [uBlockOrigin/uAssets#20739]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.niagarathisweek.com/news/rankin-run-closes-in-on-12-million-mark-raised-for-local-cancer-supports-and-services/article_fd308324-0450-5c80-ad15-dfbff7552d09.html`

### Category

ads

### Description

There are many ad leftovers on this site, I confirmed that they still appear after resetting uBo to default settings.

### Other extensions used

LanguageTool, Darkreader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/58151048/a4f1c14a-21b6-4bf3-aef0-cb5438609334)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.5rc5
Firefox: 121
filterset (summary):
 network: 172817
 cosmetic: 196222
 scriptlet: 30444
 html: 1301
listset (total-discarded, last-updated):
 added:
  https://neuter.mchang.xyz/filter: 160-0, 5m
  https://neuter.mchang.xyz/filter/misc: 39-1, now
  https://raw.githubusercontent.com/mchangrh/yt-neuter/main/filters/requests.txt: 5-0, now
  https://raw.githubusercontent.com/paulgb/BarbBlock/master/blacklists/ublock-origin.txt: 550-6, now
  https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/duckduckgo/global.txt: 4206-0, 5m
  adguard-spyware-url: 1326-88, now
  adguard-spyware: 69883-16641, now
  block-lan: 54-0, 20d.19h.48m
  adguard-social: 21998-863, now
  adguard-cookies: 28094-64, now
  ublock-cookies-adguard: 554-0, now
  adguard-popup-overlays: 26237-1554, now
  [12 lists not shown]: [too many]
 default:
  user-filters: 60-0, never
  ublock-filters: 36534-435, 5m
  ublock-badware: 7531-15, 5m
  ublock-privacy: 674-0, 5m
  ublock-unbreak: 2201-2, 5m
  ublock-quick-fixes: 115-13, 5m
  easylist: 75478-834, 5m
  easyprivacy: 32894-912, 5m
  urlhaus-1: 10605-0, 4m
  plowe-0: 3716-358, now
filterset (user): [array of 60 redacted]
trustedset:
 added: [array of 15 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 282 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 886 ms (selfie)
 maxAssetCacheWait: 122 ms
popupPanel:
 blocked: 32
 network:
  niagarathisweek.com: 4
  amazon-adsystem.com: 1
  d1z2jf7jlzjs58.cloudfront.net: 1
  demdex.net: 1
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 3
  gscontxt.net: 1
  permutive.app: 2
  petametrics.com: 11
  scorecardresearch.com: 1
  thestar.com: 2
  townnews.com: 2
  trinitymedia.ai: 1
 extended:
  ##div[data-lpos="headlines-newsletter"]
  ##a[href^="https://wa.me/?text="]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[title="Share on Facebook"]
  ##.tnt-ads-container
  ##.tnt-ads
  ##.dfp-ad
  ##.shareIcons
  ##.social-share-links
  ##.social-share-link
  ##.email-share-link
  ##.footer-social
  ##.photo-share
  ##+js(abort-current-script, jQuery, eventParams.responseVariable…
```
</details>

**Comment by mapx-** [comment]
add

```
niagarathisweek.com##.sticky-parent
niagarathisweek.com##.adLabelWrapper
niagarathisweek.com##.polarBlock:has(.polarAds)
```

@ryanbr
