### ISSUE TITLE
wh40k.lexicanum.com: breakage

### ISSUE THREAD

**Issue by leaperdude** [uBlockOrigin/uAssets#20742]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wh40k.lexicanum.com/wiki/Main_Page`

### Category

breakage

### Description

Some of the text and media of the webpage fail to load when uBO is enabled.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 105989
 cosmetic: 34927
 scriptlet: 18944
 html: 1108
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36843-338, 14m
  ublock-badware: 7525-10, 14m
  ublock-privacy: 674-1, 14m
  ublock-unbreak: 2206-2, 14m
  ublock-quick-fixes: 115-13, 43m
  adguard-mobile: 8722-128, never
  easylist: 75483-16724, 13m
  easyprivacy: 32894-734, 13m
  urlhaus-1: 10890-0, 13m
  plowe-0: 3716-1, 13m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10202 ms
 maxAssetCacheWait: 1273 ms
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 2
  quantserve.com: 1
  vntsm.com: 1
```
</details>

**Comment by gorhill** [comment]
I can reproduce using Firefox Mobile emulator in dev tools. Some text and images are not showing up when scrolling down. They show fine on desktop, or when uBO is disable on mobile.

**Comment by gorhill** [comment]
I feel like it's a site issue, its own CSS is causing this. This works around the issue:

    wh40k.lexicanum.com##.client-js .collapsible-block:style(display: block !important)
