### ISSUE TITLE
cctvwiki.com: detection

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#20741]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cctvwiki.com/en/disk-calculator/`

### Category

detection

### Description

Detect 

### Other extensions used

Violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 119
filterset (summary):
 network: 105706
 cosmetic: 34939
 scriptlet: 18944
 html: 1108
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36844-339, now
  ublock-badware: 7525-10, now
  ublock-privacy: 674-1, now
  ublock-unbreak: 2206-2, now
  ublock-quick-fixes: 115-13, 1h.24m
  adguard-mobile: 8735-128, now
  easylist: 75483-16724, now
  easyprivacy: 32894-734, now
  urlhaus-1: 10605-0, now
  plowe-0: 3716-1, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 36561 ms (selfie)
 maxAssetCacheWait: 1820 ms
popupPanel:
 blocked: 9
 network:
  ampproject.org: 1
  doubleclick.net: 1
  googlesyndication.com: 6
  googletagmanager.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
Try
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=cctvwiki.com`
