### ISSUE TITLE
wetter.com: breakage

### ISSUE THREAD

**Issue by thaliel** [uBlockOrigin/uAssets#20744]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wetter.com/`

### Category

breakage

### Description

UBO is blocking off the quicklinks to previously searched locations, which is located to the right of the search area. As these quicklinks are visible once UBO is turned off, it is clear that UBO is causing this

### Other extensions used

greasemonkey
stylus
tumblr savior
search by image
ImTranslator
F.B Purity
I don't care about cookies
Norton Safe Web
Snap Links

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 81551
 cosmetic: 112943
 scriptlet: 23058
 html: 1107
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75259-528, now
 default:
  user-filters: 587-31, never
  ublock-filters: 36527-101, now
  ublock-badware: 7531-10, now
  ublock-privacy: 674-0, now
  ublock-unbreak: 2201-1, now
  ublock-quick-fixes: 114-13, now
  easylist: 75483-667, now
  urlhaus-1: 10890-0, now
  plowe-0: 3716-1, now
  DEU-0: 7158-4, now
filterset (user): [array of 587 redacted]
trustedset:
 added: [array of 34 redacted]
 removed:
  about-scheme
  edge-scheme
switchRuleset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 833 ms (selfie)
 maxAssetCacheWait: 216 ms
popupPanel:
 blocked: 15
 network:
  wetter.com: 3
  3lift.com: 1
  71i.de: 1
  amazon-adsystem.com: 1
  doubleclick.net: 1
  mookie1.com: 1
  pushwoosh.com: 3
  theadex.com: 1
  usercentrics.eu: 3
 extended:
  ##+js(abort-current-script, $, lobster)
  ##+js(no-setTimeout-if, (null), 10)
```
</details>

**Comment by mapx-** [comment]
add

`@@||config.eu.usercentrics.eu/gvl/v3/en.json$xhr,domain=wetter.com`

@Alex-302
@Yuki2718

**Comment by Yuki2718** [comment]
@peace2000 Can you check this as well? On my end 5000ms dealy is necessary for the rule (AG uses vanilla script with MutationObserver to click). Setting `uc_tcf` local storage also works but it includes encoded timestamp and long `vendors` list which can't be empty for the issue reported here.

**Comment by peace2000** [comment]
@Yuki2718 

That vendorlist in the local storage item is just ridiculously long. Also if the list changes someway, it's possible that the rule would break... So setting the local storage item doesn't sound a long term solution...

Concerning the clicker, I tested various delays for that page.

On my main pc:
`1500` seems to be safe value for clean profile
`2500` is safe for dirty profile

On my older pc:
`2500` is safe for clean profile
`3000` for dirty profile

That `5000` seems quite high.

It's hard  to create a reliable solution for each pc unless the value is set high enough so that it will definetely work for all pc's.

We need an option to keep the scriplet active until the element appears - without any fixed delays. https://github.com/uBlockOrigin/uBlock-issues/issues/2917

**Comment by peace2000** [comment]
But for the time being... How about adding these filters as well:

`wetter.com###cmp-style-reset`
`wetter.com##body:style(overflow: auto !important)`

To hide the dialog so that users of the site don't need to see it. The clicker works for hidden dialogs as well.

**Comment by Yuki2718** [comment]
> The clicker works for hidden dialogs as well.

Oh, didn't know that!

**Comment by D4niloMR** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/199px0v/when_ublock_origin_is_enabled_wettercom_refreshes/

To solve this, the parameter `extraMatch` is needed.

**Comment by gorhill** [comment]
In next dev build, this should work:

    wetter.com##+js(trusted-click-element, #cmp-btn-accept, !cookie:/^gpt_ppid[^=]+=/, 5000)

**Comment by Henning0** [comment]
Hi. I can't scroll the site with list "EasyList/uBO – Cookie Notices" active. Only happen on android phone with Firefox. Desktop Firefox unaffected. Only if I access via a deep link:  [example](https://www.wetter.com/deutschland/berlin/DE0001020.html). Only with clean cookies. Access country is germany.

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.64.0
Firefox Mobile: 139
filterset (summary):
 network: 157099
 cosmetic: 96780
 scriptlet: 31929
 html: 2326
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 45802-141, 1m
  ublock-cookies-easylist: 4622-44, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 41539-116, 1m
  ublock-badware: 11687-17, 1m
  ublock-privacy: 2947-3, 1m
  ublock-unbreak: 2702-1, 1m
  ublock-quick-fixes: 286-29, 1m
  adguard-mobile: 11034-92, 1m
  easylist: 69243-309, 1m
  easyprivacy: 54065-61, 1m
  urlhaus-1: 34740-1, 1m
  plowe-0: 3427-987, 1m
  DEU-0: 8033-47, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 542 ms (selfie)
 maxAssetCacheWait: 251 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 2
 network:
  usercentrics.eu: 2
 extended:
  ##div[class*="app-layout"]:has(> div.ad-label)
  ##div:has(> div#div-gpt-ad-wetter_direct_toolbar)
  ##.mbanner-fixed
  ###content-main > .werbung
  ###cmp-style-reset
  ##.werbung:not(.toolbar-wrapper)
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ad-flex
  ##.ad-label
  #@#div[id^="div-gpt-"]
  #@#[id^="div-gpt-ad"]
  #@#.werbung
  ##+js(abort-current-script, $, lobster)
  ##+js(trusted-click-element, .cmp-scroll-padding .cmp-info[style…
  ##+js(prevent-setTimeout, (null), 10)
``` 
</details>

**Comment by stephenhawk8054** [comment]
Hmm... I can scroll normally.

@JobcenterTycoon Sorry, can you reproduce?

**Comment by JobcenterTycoon** [comment]
No works fine for me.

**Comment by Henning0** [comment]
Well. That is odd. But this got me digging myself a bit.

Found that only on my phone the body tag gets the class `cmp-mobile` added. That class sets `position: fixed;` on body.

Thus I extended the rule from above/the cookie list to `wetter.com##body:style(overflow: auto !important; position: unset !important;)`. Problem solved.

**Comment by stephenhawk8054** [comment]
uBO's cookie list already has `wetter.com##body:style(overflow: auto !important)`

https://github.com/uBlockOrigin/uAssets/blob/12f2e5d88bd15f07a10f3d6a0c6ea940b85ee480/filters/annoyances-cookies.txt#L1038

I can't reproduce with mobile either.

---

Ah you mean the `position` style. I can't reproduce it, but it's not harm to add it.

**Comment by terr72** [comment]
Unfortunately https://github.com/uBlockOrigin/uAssets/commit/511e9940e2d0b783120a06d3d6c31bc5958613d2 didn't fix it.
I ensured my _uBlock filters - Cookie Notices_ is updated and reflecting the commit removing the two lines.
I still need to add `wetter.com#@##cmp-style-reset` to My Filters in order to make it work.

**Comment by stephenhawk8054** [comment]
You need to force update the cookie list.

**Comment by terr72** [comment]
I did update the clock icon next to the list to updated, verified the removed lines are gone in the list viewer and hit the reload button on the wetter.com page, but it seems like manual updating a single list item doesn't have an immediate effect on uBO.
After a browser restart it works now.
Thank you!
