### ISSUE TITLE
blog.bitsrc.io: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#20745]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [ ] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blog.bitsrc.io/top-10-ui-ux-concepts-every-developer-should-know-e9a6b9ae53da`

### Category

nuisance

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/8b357716-030d-49d5-92a5-8a3378421735)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 112580
 cosmetic: 123966
 scriptlet: 28386
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 10463-1, 7m
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 80-4, 7m
  adguard-popup-overlays: 26237-46, 7m
  easylist-annoyances: 4185-124, 7m
  easylist-notifications: 2877-197, 7m
  fanboy-cookiemonster: 48906-247, 7m
  ublock-annoyances: 5856-154, 6m
  ublock-cookies-easylist: 554-554, 6m
 default:
  user-filters: 33-0, never
  easylist: 75483-57, 7m
  easyprivacy: 32894-169, 7m
  plowe-0: 3716-1076, 7m
  ublock-badware: 7527-142, 6m
  ublock-filters: 35645-352, 6m
  ublock-privacy: 680-6, 6m
  ublock-quick-fixes: 114-50, 6m
  ublock-unbreak: 2155-36, 6m
  urlhaus-1: 10890-0, 6m
filterset (user): [array of 33 redacted]
trustedset:
 added: [array of 64 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2592 ms (selfie)
 maxAssetCacheWait: 376 ms
popupPanel:
 blocked: 5
 network:
  bitsrc.io: 3
  branch.io: 1
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
test

```
blog.bitsrc.io##+js(set-local-storage-item, 201805-policy|accepted, 1)
blog.bitsrc.io##+js(aeld, message, data)
```
