### ISSUE TITLE
support.upwork.com: breakage

### ISSUE THREAD

**Issue by antigone23** [uBlockOrigin/uAssets#20743]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://support.upwork.com/hc/en-us/requests/new?ticket_form_id=3964`

All update password links

### Description

All update password button links are blank pages.

All attempts to file a ticket with upworks regarding inability to login result in blank pages.  

There is a 1-2s flash of a standard screen for filing a customer support ticket every time, then it reverts to a blank page.  Most of uBlock looks to be in the grey.  However, lately, there are extremely thin, unlabeled bars on uBlock that show in the red, including on upwork.  I cannot click on or access the bars to see what they are for or to select a go-ahead for them.  

### Other extensions used

Privacy Badger & Dark Reader

Badger has been disabled for this site, to no effect.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![upworkfail](https://github.com/uBlockOrigin/uAssets/assets/151289098/04bc04ee-98d2-4e40-8b00-5f706b23d7df)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 217774
 cosmetic: 240818
 scriptlet: 45955
 html: 1295
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75163-116, 1d.18h.7m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94627-21776, 6d.13h.14m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 32m
  adguard-generic: 80184-4567, 1d.18h.11m
  adguard-mobile: 8726-68, 1d.18h.10m
  adguard-spyware-url: 1310-89, 1d.18h.9m
  block-lan: 54-0, 21d.11h.8m
  curben-phishing: 80995-28, 13h.7m
  adguard-social: 21983-1623, 1d.18h.8m
  fanboy-thirdparty_social: 68-18, 6d.13h.15m
  fanboy-cookiemonster: 48884-48789, 4d.4h.29m
  fanboy-social: 16222-16203, 33m
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36425-407, 3d.14h.25m
  ublock-badware: 7498-9, 3d.14h.24m
  ublock-privacy: 674-2, 2d.2h.14m
  ublock-unbreak: 2196-4, 3d.14h.23m
  ublock-quick-fixes: 115-36, 31m
  easylist: 75291-1941, 4d.16h.32m
  easyprivacy: 32878-395, 2d.12h.17m
  urlhaus-1: 10665-0, 13h.8m
  plowe-0: 3715-1161, 13h.9m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 232 redacted]
hostRuleset:
 added: [array of 615 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 13541 ms (selfie)
 maxAssetCacheWait: 11381 ms
popupPanel:
 blocked: 5
 network:
  upwork.com: 2
  google-analytics.com: 1
  usabilla.com: 1
  zdassets.com: 1
 extended:
  ##.alert-cookies-consent
  ##.footer-nav-social
  ##.social-icon-linkedin
  ##.social-icon-twitter
```
</details>

**Comment by huyszn** [comment]
The page turns blank even when uBO is turned off for me.

**Comment by mapx-** [comment]
I guess you have to be logged in otherwise for privacy matters it's avoided and the page turns blank

in console:
`401 (Unauthorized)`
