### ISSUE TITLE
pressplay.top : nuisance

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#20747]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://pressplay.top/movie-id410545296-the-hunger-games-the-ballad-of-songbirds-and-snakes-online-free`

### Description

there is a popup ad at top of player and the site also had anti devtools please fix that too

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by huyszn** [comment]
Try these filters:
```
pressplay.top###modalshare
pressplay.top##.modal-backdrop
pressplay.top##body.modal-open:style(overflow: auto !important;)
||pressplay.top^$csp=script-src * 'unsafe-inline'
```

**Comment by mapx-** [comment]
enable uBlock filters – Annoyances

**Comment by Fatcavill** [comment]
working tnx
but this still shows

todays sponsor of the day at top of player

**Comment by RazorVA69** [comment]
popup if play from main server
`https://pressplay.top/movie/superman-2`

**Comment by stephenhawk8054** [comment]
I can't reproduce the popups. Are you using uBO or uBOL?

**Comment by RazorVA69** [comment]
ubo latest beta with lemur browser(chrome)
The problem is only with main server

**Comment by stephenhawk8054** [comment]
That browser is not supported. Test again in Firefox mobile.
