### ISSUE TITLE
2kmovie.cc: breakage

### ISSUE THREAD

**Issue by moana24** [uBlockOrigin/uAssets#20748]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://2kmovie.cc/`

### Category

breakage

### Description

I have been using this website to watch movies and TV shows but up until recently i noticed it stopped working. 
So my first thought was that the website was down and it will be back after a few weeks, however after a while it did not change. 
I went on the same website on my phone and the website was perfectly fine. I then decided to use it on microsoft edge and again it was working fine so then i thought maybe it is a chrome thing but when i used it in incognito mode it worked well. I think the issue is with ubo and i don't know any ways to fix this. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104592
 cosmetic: 43777
 scriptlet: 19053
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75485-16, 7m
  easyprivacy: 32894-64, 7m
  plowe-0: 3716-1076, 7m
  ublock-badware: 7527-140, 7m
  ublock-filters: 35645-154, 7m
  ublock-privacy: 680-5, 7m
  ublock-quick-fixes: 114-50, 7m
  ublock-unbreak: 2155-32, 7m
  urlhaus-1: 10890-0, 7m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2822 ms
 maxAssetCacheWait: 45 ms
popupPanel:
 blocked: 3
 network:
  gstatic.com: 2
  valueclick.cc: 1
 extended:
  ###hgiks-top
  ###hgiks-middle
  ##+js(abort-current-script, document.documentElement, break;case…
```
</details>

**Comment by mapx-** [comment]
> it stopped working

What exactly is broken on your side ?

**Comment by moana24** [comment]
> > it stopped working
> 
> What exactly is broken on your side ?

I wish i knew i have done everything like purge cache and reset everything and even deleted ubo and installed it again. Also i genuinely am not sure how to use this sort of stuff so you will probably have to explain this to me like a five year old but thank you for replying

**Comment by mapx-** [comment]
Could you give us the requested details ?

> What exactly is broken on your side ?

**Comment by moana24** [comment]
> Could you give us the requested details ?
> 
> > What exactly is broken on your side ?

I don't know what you are asking of me but this is what shows up when i opened the logger for the site
![ubo](https://github.com/uBlockOrigin/uAssets/assets/151337880/ea1e12e2-00cd-4774-98c6-da00bbbc5eae)

**Comment by mapx-** [comment]
I simply ask you what make you say "it stopped working":
- you want to watch a movie but you get a blank screen ?
- the buttons do not work
- etc etc etc

**Comment by moana24** [comment]
Ohhh okay so it will not let me search anything cuz when i do search it stays on the homepage, also the website has weird formatting i will show a picture below. Essentially it is unusable, i even tried opening a direct link to the movie page via emailing myself through my phone and the formatting was still weird and the video did not work. 
the first pic is what it looks like with ubo and the second is what it normally should look like. Also sorry for being so dense there. 
![2k m](https://github.com/uBlockOrigin/uAssets/assets/151337880/0765cde0-53a9-4b8f-ae3c-a139ad361e2b)
![2k](https://github.com/uBlockOrigin/uAssets/assets/151337880/8ee0a4d9-78b8-45e0-9a9c-f354b53694c4)

**Comment by mapx-** [comment]
I cannot reproduce your issue, the page is still ok and the search is working fine on my side.

However, I found at least a broken video (but it seems a site issue in this case):
`https://2kmovie.cc/tv/watch-thor-and-loki-blood-brothers-free-21852`

**Comment by mapx-** [comment]
Follow all these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by moana24** [comment]
I realised i had privacy badger which i thought i had deleted but i removed it and it worked again but when i redownloaded it, it carried on working. Regardless it has fixed thanks to you. Thank youuu !!!
