### ISSUE TITLE
cimanow.cc: breakage

### ISSUE THREAD

**Issue by midonasser** [uBlockOrigin/uAssets#20750]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cimanow.cc/%d9%85%d8%b3%d9%84%d8%b3%d9%84-%d8%b5%d9%84%d8%a7%d8%ad-%d8%a7%d9%84%d8%af%d9%8a%d9%86-%d8%a7%d9%84%d8%a7%d9%8a%d9%88%d8%a8%d9%8a-%d8%ac1-%d8%ad1-%d9%85%d8%aa%d8%b1%d8%ac%d9%85%d8%a9/watching/`

### Category

breakage

### Description

content is hideen

### Other extensions used

disabled brave sheild

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

[
![screenshot-cimanow cc-2023 11 18-10_25_42](https://github.com/uBlockOrigin/uAssets/assets/84553717/6376a7dd-a016-424b-a19d-0b04ccd648c8)
](url)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 192342
 cosmetic: 70834
 scriptlet: 26174
 html: 0
listset (total-discarded, last-updated):
 added:
  NLD-0: 2737-22, 6m
  ara-0: 2377-250, 8m
  block-lan: 54-0, 6m
  curben-phishing: 80930-20, 6m
  easylist-annoyances: 4185-899, 6m
  easylist-chat: 160-9, 6m
  easylist-newsletters: 6677-1861, 6m
  easylist-notifications: 2877-336, 6m
  fanboy-cookiemonster: 48910-17539, 6m
  fanboy-social: 16208-11754, 6m
  fanboy-thirdparty_social: 68-15, 6m
  ublock-annoyances: 5861-87, 6m
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 75485-16001, 8m
  easyprivacy: 32894-159, 8m
  plowe-0: 3716-1076, 8m
  ublock-badware: 7527-148, 8m
  ublock-filters: 35646-381, 8m
  ublock-privacy: 680-7, 8m
  ublock-quick-fixes: 114-50, 8m
  ublock-unbreak: 2155-37, 8m
  urlhaus-1: 10890-0, 8m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 492 ms
 maxAssetCacheWait: 272 ms
popupPanel:
 blocked: 3
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  keewoach.net: 1
```
</details>

**Comment by mapx-** [comment]
You should have tell us what the red message says:

`Please use another browser to be able to watch and download for free`
