### ISSUE TITLE
Yandex.Browser and Yandex websites

### ISSUE THREAD

**Issue by qazomardok** [uBlockOrigin/uAssets#20759]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

ya.ru
`https://yandex.ru/search`

### Category

leave it alone

### Description

In Yandex.Browser, the "Select an item on the page" button in the popup does not work on the Yandex websites 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![111](https://github.com/uBlockOrigin/uAssets/assets/1916649/2a103b6d-dad2-45cc-b18f-b55ac8dd48e7)

</details>

### Configuration

leave it alone

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by mapx-** [comment]
@qazomardok open uBO dashboard, support tab, copy & paste here Troubleshooting Information

**Comment by dimisa-RUAdList** [comment]
This is a known issue: https://github.com/uBlockOrigin/uBlock-issues/issues/2627#issuecomment-1528886506

**Comment by mapx-** [comment]
ok, @qazomardok ok, trash that browser and install a better one (brave for example)

**Comment by qazomardok** [comment]
Oh.. I see. Thank you for your response. In the end, only helped https://chromewebstore.google.com/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld with css `li.serp-item.serp-item_card[data-fast="2"]`

**Comment by dimisa-RUAdList** [comment]
@qazomardok 
This is a bad rule. Too general. It will either hide unnecessary things or work unstable. Use a ready-made configuration file: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links
