### ISSUE TITLE
ua.sinoptik.ua: ads

### ISSUE THREAD

**Issue by lisovyk** [uBlockOrigin/uAssets#20755]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ua.sinoptik.ua/%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0-%D0%BB%D1%8C%D0%B2%D1%96%D0%B2`

### Category

ads

### Description

first, ads are hidden, then there are shown some text-in-container ads all over, and they are not selectable with the picker mode

.. and the ads are in russian language, on ukrainian weather website – which is super weird

### Other extensions used

selectorGadget, google analytics debugger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1283" alt="Screenshot 2023-11-18 at 17 16 57" src="https://github.com/uBlockOrigin/uAssets/assets/24924432/d8caab2a-b1eb-40e9-93ec-1ce76fb53804">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 104567
 cosmetic: 43783
 scriptlet: 19069
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 75490-16, now
  easyprivacy: 32895-64, now
  plowe-0: 3716-1076, now
  ublock-badware: 7527-140, now
  ublock-filters: 35667-154, now
  ublock-privacy: 679-5, now
  ublock-quick-fixes: 114-50, now
  ublock-unbreak: 2155-32, now
  urlhaus-1: 10860-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 16 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2679 ms (selfie)
 maxAssetCacheWait: 69 ms
popupPanel:
 blocked: 24
 network:
  adpartner.pro: 1
  adtcdn.com: 2
  doubleclick.net: 1
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 2
  mixadvert.com: 1
  rcvlink.com: 5
  rcvlinks.com: 1
  ukr.net: 4
  zfctrack.net: 1
  zhctrack.net: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
enable `RU AdList`
