### ISSUE TITLE
jianshu.com: nuisance

### ISSUE THREAD

**Issue by GCPanic** [uBlockOrigin/uAssets#20752]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.jianshu.com/p/4c798c91a613`
PS.This happened on all the pages on jianshu.com, this is just an example.

### Category

privacy

### Description

When you trying to select some content on page, this website will immediately cancel your select and put some not human readable string on your clipboard.

Note that this only happens when you use phones(i found out this problem on Android/Firefox)

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-11-18-21-38-45-136_org mozilla firefox_beta-edit](https://github.com/uBlockOrigin/uAssets/assets/127860015/5e527091-9f1d-4e14-80ee-ebf4e80a74d8)
![Screenshot_2023-11-18-21-39-05-719_org mozilla firefox_beta-edit](https://github.com/uBlockOrigin/uAssets/assets/127860015/52160728-922f-4721-8c60-bb635ec66215)
I masked that string in the second picture because i think is might contain tracking datas.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 120
filterset (summary):
 network: 120922
 cosmetic: 44172
 scriptlet: 19129
 html: 1107
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 36864-353, now
  ublock-badware: 7525-10, now
  ublock-privacy: 674-1, now
  ublock-unbreak: 2206-2, now
  ublock-quick-fixes: 114-13, now
  adguard-mobile: 8736-128, now
  easylist: 75486-16734, now
  easyprivacy: 32894-747, now
  urlhaus-1: 10860-0, now
  plowe-0: 3716-1, now
  CHN-0: 25703-1309, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 354 ms (selfie)
 maxAssetCacheWait: 165 ms
popupPanel:
 blocked: 29
 network:
  jianshu.com: 1
  baidu.com: 1
  bdstatic.com: 1
  cnzz.com: 18
  ibreader.com: 7
  twlcyc.cn: 1
 extended:
  ##div[aria-label="amc-ad"]
  ##+js(set-constant, NEWS_FEED, noopFunc)
```
</details>

**Comment by mapx-** [comment]
test

`jianshu.com##+js(aeld, copy)`

**Comment by gorhill** [comment]
This works for me:

    jianshu.com##+js(nostif, captureException)
