### ISSUE TITLE
[nsfw] cloudtrck.com: popups

### ISSUE THREAD

**Issue by Neato0** [uBlockOrigin/uAssets#20760]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://cloudtrck.com/click.php?key=ii2583tm30pztjpemg20&visitor_id=749799266146586933&cost=0.003207&campaignid=7654938&zoneid=4923326&device=desktop&browser=firefox&os=windows&osversion=win10&country=US&language=en&isp=att%20internet%20services&user_activity=high`

### Category

popups

### Description

UBlock catches this during Firefox launch, never happened before no changes have been made to my PC.

### Other extensions used

no other extentions

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ublock blocked page at launch](https://github.com/uBlockOrigin/uAssets/assets/116667480/8227a2f2-4adc-4a5b-9f29-ef9b9c50f4fc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 111630
 cosmetic: 128301
 scriptlet: 23612
 html: 1106
listset (total-discarded, last-updated):
 added:
  adguard-social: 21998-167, now
  adguard-cookies: 28095-42, now
  adguard-popup-overlays: 26238-889, now
  adguard-mobile-app-banners: 4777-9, now
  adguard-other-annoyances: 13806-8, now
  adguard-widgets: 2345-1, now
  ublock-cookies-adguard: 558-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36554-432, now
  ublock-badware: 7531-10, now
  ublock-privacy: 674-0, now
  ublock-unbreak: 2201-1, now
  easylist: 75504-763, now
  easyprivacy: 32894-731, now
  urlhaus-1: 10860-0, now
  plowe-0: 3716-1, now
  ublock-quick-fixes: 114-13, now
filterset (user): [empty]
trustedset:
 added: [array of 93 redacted]
 removed:
  about-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 23 redacted]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1646 ms (selfie)
 maxAssetCacheWait: 356 ms
popupPanel:
 blocked: 0
 no-popups: true
 no-remote-fonts: true
 no-scripting: true
```
</details>

**Comment by mapx-** [comment]
- scan your system using some scanner, for example this one:
https://www.eset.com/int/home/online-scanner/

**Comment by Neato0** [comment]
👍

**Comment by Neato0** [comment]
Thanks for the assist, but still there, I ran eset and it found 249
possible malware files, but did not correct this issue, not sure if is an
issue related to the browser, some file got installed somehow, I updated
the UBlock list recently that's about everything I have done to this PC.

**Comment by mapx-** [comment]
249 ? well, pretty infested.
I'd remove firefox and then manually delete all remaining folders, then reinstall it and add uBO.

For further support with malwares you should ask here:
https://forums.malwarebytes.com/forum/7-windows-malware-removal-help-support/

@iam-py-test maybe you can offer some other advice.

**Comment by iam-py-test** [comment]
Try running Adwcleaner: https://support.malwarebytes.com/hc/articles/360038520054-Download-and-install-Malwarebytes-AdwCleaner
Then reset Firefox: https://support.mozilla.org/kb/reset-preferences-fix-problems
Though, 200+ malware infections... if I were you, I'd just reinstall Windows: https://answers.microsoft.com/windows/forum/all/clean-install-windows-10-11-2023/1c426bdf-79b1-4d42-be93-17378d93e587 ([use a local account not a M$ one](https://forums.malwarebytes.com/topic/296613-bypass-microsoft-online-account-creation-during-installation-of-windows-11/))
Thanks

**Comment by Neato0** [comment]
It is still there, I ran the other one too and found no issues as in 0 it
seems like advertisement companies found a way to circumvent how ad
blockers work and are going around to bypass them. Thanks for the assist.

**Comment by iam-py-test** [comment]
> advertisement companies found a way to circumvent how ad blockers work and are going around to bypass them

I highly doubt that is the case since it opens as soon as you open your browser; no legitimate ad can do that. Additionally, cloudtrck[.]com does not appear to be just an innocent ad domain.
This sounds like a malware infection, and given the tool @mapx- recommended found 200+ threats, there is something suspicious going on.

**Comment by D4niloMR** [comment]
maybe `downloadoperagx.com` on badware lists?

I compared the hashes and this site is giving a different file from the official opera site.

**Comment by iam-py-test** [comment]
I don't believe that is relevant to the issue at hand. Would you mind opening a separate issue?
Thanks

**Comment by D4niloMR** [comment]
Sure, but I think it's related because this site is leading to `downloadoperagx.com`

**Comment by iam-py-test** [comment]
Oh, sorry. Didn't realize that.

**Comment by Neato0** [comment]
They were trainers. I keep a collection of trainers with 4 grandkids that
like to game. It helps to manage their time and mines, they are embedding
extra code. You can see it in the uBlock window when it opens I got rid of
firefox and all extensions til they fix this. Chrome is working fine.

**Comment by iam-py-test** [comment]
I'm confused; are you saying these "trainers" are opening malicious websites in Firefox?
This is not a problem with uBlock Origin; it can not control what other applications on your computer.
Removing Firefox solved the problem because Chrome wasn't infected with whatever malware was causing this.
Thanks

**Comment by Neato0** [comment]
No the positives were from trainer files, all of them, Ublock was reporting
catching the attempt to basically redirect the links the browser (firefox)
in this case was trying to open, so ublock was working fine, but is all
over You tube ad companies are embedding, or adding extra code to bypass
how ad blockers work, I'm not a guru on none of these but yeah several
videos on how they are doing this. IMO they are using how ad blockers work
and adding a bypass to redirect the call to their ads. Is what I
understand. I'm surprised you guys are not aware of this?

**Comment by iam-py-test** [comment]
The uBlock Origin team is very well aware of YouTube's attempts to detect/bypass uBlock Origin, and adapt to YouTube's changes.
However, that was not what caused the initial problem (the malicious website opening in Firefox).
Thanks
