### ISSUE TITLE
youmath.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#20763]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.youmath.it/`

### Description

cookie dialog | nuisance

possible rules:
`youmath.it##+js(trusted-click-element, #pubtech-cmp button#pt-accept-all)`
`youmath.it##+js(trusted-click-element, #pt-actions>button#pt-accept-all)`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1246" alt="d" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/64c5a3f2-0e62-471b-8410-257e027aa46c">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 114389
 cosmetic: 136464
 scriptlet: 26895
 html: 1299
listset (total-discarded, last-updated):
 added:
  adguard-social: 21998-169, 2m
  adguard-cookies: 28095-45, 2m
  ublock-cookies-adguard: 559-0, 2m
  adguard-popup-overlays: 26238-966, 2m
  adguard-mobile-app-banners: 4777-9, 2m
  adguard-other-annoyances: 13806-61, 2m
  adguard-widgets: 2345-1, 2m
  ublock-annoyances: 5827-572, 2m
  ITA-0: 9330-35, never
 default:
  user-filters: 0-0, never
  ublock-filters: 36545-432, 3h.21m
  ublock-badware: 7531-10, 3h.21m
  ublock-privacy: 674-0, 3h.21m
  ublock-unbreak: 2201-0, 3h.21m
  ublock-quick-fixes: 114-14, 3h.21m
  easylist: 75504-771, 3h.21m
  easyprivacy: 32894-731, 3h.21m
  urlhaus-1: 10860-0, 3h.20m
  plowe-0: 3716-1, 3h.20m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1675 ms
 maxAssetCacheWait: 829 ms
```
</details>

**Comment by mapx-** [comment]
it seems already fixed using `EasyList – Cookie Notices` list, specifically these filters:

```adblock
/cmp-v2/*
||pubtech.ai^$3p
```

**Comment by superlex** [comment]
@mapx- 
Yes, it looks like you can't add an item to the shopping cart.
Could you try, please?
https://www.youmath.it/ebook-e-libri/prodotto/57-ebook-matematica-quinta-elementare.html
