### ISSUE TITLE
studysmarter.de: nuisance

### ISSUE THREAD

**Issue by TrueJole** [uBlockOrigin/uAssets#20767]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.studysmarter.de/schule/chemie/analytische-chemie/biuret-reaktion/`

### Category

nuisance

### Description

Big Banner takes up entire screen asking to sign up, but it can be clicked away

### Other extensions used

archive.org, Sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://github.com/uBlockOrigin/uAssets/assets/121569485/274784c1-8f19-450c-a4af-24386a15bb38)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 283325
 cosmetic: 246207
 scriptlet: 46696
 html: 1299
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80262-7343, now
  adguard-mobile: 8738-139, now
  adguard-spyware-url: 1326-88, now
  adguard-spyware: 69883-16752, now
  block-lan: 54-0, now
  curben-phishing: 82047-29, now
  adguard-social: 21998-867, now
  adguard-cookies: 28095-64, now
  adguard-popup-overlays: 26238-1558, now
  adguard-mobile-app-banners: 4777-1069, now
  adguard-other-annoyances: 13806-315, now
  adguard-widgets: 2345-1, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36559-462, now
  ublock-badware: 7605-10, now
  ublock-privacy: 674-0, now
  ublock-unbreak: 2201-2, now
  ublock-quick-fixes: 114-13, now
  easylist: 75507-1049, now
  easyprivacy: 32895-912, now
  urlhaus-1: 10585-0, now
  plowe-0: 3717-1, now
  DEU-0: 7158-20, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 212 ms (selfie)
 maxAssetCacheWait: 86 ms
popupPanel:
 blocked: 34
 network:
  amplitude.com: 30
  google.com: 3
  googletagmanager.com: 1
 extended:
  ##.maintopics-banner-wrap
  ##div[data-adv-location]
  ##a[href^="https://track.adform.net/"]
  ###credential_picker_container
```
</details>

**Comment by mapx-** [comment]
add

`studysmarter.de##.ab-feature-popup`

you could report at easylist repo or / and adguard repo to add this filter in their lists

@Yuki2718
