### ISSUE TITLE
physicsandmathstutor.com: breakage

### ISSUE THREAD

**Issue by M338937** [uBlockOrigin/uAssets#20761]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.physicsandmathstutor.com/`

### Category

breakage

### Description

the extension is deleting all elements on the page.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104569
 cosmetic: 43777
 scriptlet: 19056
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 75483-16, 1m
  easyprivacy: 32894-64, 1m
  plowe-0: 3716-1076, 1m
  ublock-badware: 7527-140, 1m
  ublock-filters: 35653-154, 1m
  ublock-privacy: 680-5, 1m
  ublock-quick-fixes: 114-50, 1m
  ublock-unbreak: 2155-32, 1m
  urlhaus-1: 10860-0, 1m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 698 ms (selfie)
 maxAssetCacheWait: 243 ms
popupPanel:
 blocked: 9
 network:
  physicsandmathstutor.com: 2
  amazon-adsystem.com: 1
  cloudflareinsights.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  inmobi.com: 1
  pixfuture.com: 1
  quantserve.com: 1
 extended:
  ###container > .clearfix
  ###PMT_Top
  ##.ad-atf
  ###sidebar_ads
```
</details>

**Comment by mapx-** [comment]
check your custom filters ("my filters")

did you add this filter ?

`###container > .clearfix`

**Comment by M338937** [comment]
Thank you
I removed that filter and it works now.
I don't know how it came to exist in the first place.
Thanks again.
