### ISSUE TITLE
getemoji.com: detection

### ISSUE THREAD

**Issue by adrien-pw** [uBlockOrigin/uAssets#20770]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://getemoji.com/`

### Category

detection

### Description

Popup spawn saying we're using a blocker.

### Other extensions used

Dashlane, nordVPN, Wappalyzer, sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 122574
 cosmetic: 52884
 scriptlet: 19215
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  FRA-0: 28599-39, now
  easylist: 75507-94, now
  easyprivacy: 32895-331, now
  plowe-0: 3717-1088, now
  ublock-badware: 7601-154, now
  ublock-filters: 35678-230, now
  ublock-privacy: 680-6, now
  ublock-quick-fixes: 114-50, 1h.22m
  ublock-unbreak: 2155-36, now
  urlhaus-1: 9965-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1798 ms (selfie)
 maxAssetCacheWait: 974 ms
popupPanel:
 blocked: 14
 network:
  apester.com: 8
  frspecifics.com: 1
  googletagmanager.com: 1
  hotjar.com: 1
  pub.network: 2
  twitter.com: 1
 extended:
  ##._1nq6xnf
  ###_1vxba0d
  ##[data-freestar-ad]
```
</details>

**Comment by mapx-** [comment]
enable `uBlock filters – Annoyances`
