### ISSUE TITLE
ads filter list can't loading from ublock origin

### ISSUE THREAD

**Issue by Apious** [uBlockOrigin/uAssets#20773]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

ads filter list can't loading from ublock origin
it was work until now then this version cound't loaded in v1.53

link : https://raw.githubusercontent.com/Apious/Ads_Filter_Contents/1st/Ads_Block_Contents.txt

another ad block app, program is fine only not work at ublock origin
do you know why?

### A specific URL where the issue occurs.

https://raw.githubusercontent.com/Apious/Ads_Filter_Contents/1st/Ads_Block_Contents.txt

### Steps to Reproduce

1. not show on filter list [ Ads_Block_Contents "1,490개 중 1,462개" 사용 중] the count number is "0"
2. del filter link
3. re added
4. same
5. change the name the filter as like (ex: Ads_Block_Contents.txt >> Ads_Block_Contents_.txt)
6. then work for moment
7. same after 2 days

### Expected behavior

no idea

### Actual behavior

just the filter count number gone

### Configuration

{
  "timeStamp": 1700408540679,
  "version": "1.53.0",
  "userSettings": {
    "cloudStorageEnabled": true,
    "uiAccentCustom0": "#3498d6",
    "externalLists": "https://cdn.jsdelivr.net/gh/adguardteam/HostlistsRegistry@main/assets/filter_25.txt\nhttps://raw.githubusercontent.com/Apious/Ads_Filter_Contents/1st/Ads_Block_Contents.txt\nhttps://raw.githubusercontent.com/Apious/Ads_Filter_DNS/1st/Ads_Block_DNS.txt",
    "importedLists": [
      "https://cdn.jsdelivr.net/gh/adguardteam/HostlistsRegistry@main/assets/filter_25.txt",
      "https://raw.githubusercontent.com/Apious/Ads_Filter_Contents/1st/Ads_Block_Contents.txt",
      "https://raw.githubusercontent.com/Apious/Ads_Filter_DNS/1st/Ads_Block_DNS.txt"
    ],
    "popupPanelSections": 63,
    "webrtcIPAddressHidden": true
  },
  "selectedFilterLists": [
    "user-filters",
    "adguard-generic",
    "adguard-mobile",
    "easylist",
    "easyprivacy",
    "KOR-1",
    "https://raw.githubusercontent.com/Apious/Ads_Filter_Contents/1st/Ads_Block_Contents.txt",
    "https://raw.githubusercontent.com/Apious/Ads_Filter_DNS/1st/Ads_Block_DNS.txt",
    "https://cdn.jsdelivr.net/gh/adguardteam/HostlistsRegistry@main/assets/filter_25.txt"
  ],
  "hiddenSettings": {
    "assetFetchTimeout": 20,
    "autoUpdateAssetFetchPeriod": 30,
    "autoUpdateDelayAfterLaunch": 180,
    "autoUpdatePeriod": 7
  },

**Comment by mapx-** [comment]
@Apious continue here: https://github.com/uBlockOrigin/uAssets/discussions/20627
