### ISSUE TITLE
ignitetv.shaw.ca: breakage

### ISSUE THREAD

**Issue by ScentlessApprentice91** [uBlockOrigin/uAssets#20774]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ignitetv.shaw.ca/`

### Category

breakage

### Description

hangs on screen after loggin in

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103771
 cosmetic: 43784
 scriptlet: 19081
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75516-16, 12m
  easyprivacy: 32895-64, 12m
  plowe-0: 3717-1077, 11m
  ublock-badware: 7601-140, 11m
  ublock-filters: 35678-154, 11m
  ublock-privacy: 680-5, 11m
  ublock-quick-fixes: 114-50, 11m
  ublock-unbreak: 2155-32, 11m
  urlhaus-1: 9965-0, 11m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 330 ms (selfie)
 maxAssetCacheWait: 179 ms
popupPanel:
 blocked: 1
 network:
  shaw.ca: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||ignitetv.shaw.ca/js/api/fingerprint.js$script,1p`

@ryanbr
