### ISSUE TITLE
9animetv.to: breakage

### ISSUE THREAD

**Issue by V31-S01** [uBlockOrigin/uAssets#20775]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://9animetv.to/home`

### Category

breakage

### Description

An element displays over the page, as far as I can tell, this element only prevents the use of the search bar, I know it's an element causing it because if I use the element zapper, I can get rid of the element and use the search bar, though sometimes the element can prevent you from clicking on anything. The element is invisible and so a screenshot or video cannot properly showcase it.

### Other extensions used

Google Docs Offline

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.4
Chromium: 119
filterset (summary):
 network: 103591
 cosmetic: 43773
 scriptlet: 19070
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 75516-16, now
  easyprivacy: 32895-64, now
  plowe-0: 3717-1077, now
  ublock-badware: 7423-137, now
  ublock-filters: 35644-154, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 121-51, now
  ublock-unbreak: 2155-32, now
  urlhaus-1: 9965-0, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 444 ms (selfie)
 maxAssetCacheWait: 246 ms
popupPanel:
 blocked: 4
 network:
  googletagmanager.com: 1
  outoctillerytor.com: 1
  sharethis.com: 2
 extended:
  ##[href^="//keefeezo.net/4/5840725"]
  ##[href^="//keefeezo.net/"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by gorhill** [comment]
I can't reproduce. There was a filter added for this site over a week ago, <https://github.com/uBlockOrigin/uAssets/issues/20602>, and I can see it was applied on your side.

**Comment by gorhill** [comment]
Hmmm I don't see an element covering the search bar but I am unable to place the text cursor in the search field. Does that work for you?

    9animetv.to##+js(rmnt, script, Number)
