### ISSUE TITLE
datacheap.io / bitcrypto.info: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#20776]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vk.com/away.php?to=https://datacheap.io?safelink_redirect=eyJzZWNvbmRfc2FmZWxpbmtfdXJsIjoiaHR0cHM6XC9cL2JpdGNyeXB0by5pbmZvIiwic2FmZWxpbmsiOiJodHRwczpcL1wvdGhhbmtzLndlei5pbmZvXC9PV3kzam9pc3hqbyJ9`

`https://datacheap.io?safelink_redirect=eyJzZWNvbmRfc2FmZWxpbmtfdXJsIjoiaHR0cHM6XC9cL2JpdGNyeXB0by5pbmZvIiwic2FmZWxpbmsiOiJodHRwczpcL1wvdGhhbmtzLndlei5pbmZvXC9PV3kzam9pc3hqbyJ9`

### Category

detection

### Description

dt

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium Mobile: 120
filterset (summary):
 network: 109274
 cosmetic: 36436
 scriptlet: 19154
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 17-6, never
  IDN-0: 9691-3882, now
  adguard-mobile: 8738-46, now
  easylist: 75516-16054, now
  easyprivacy: 32895-75, now
  plowe-0: 3717-1152, now
  ublock-badware: 7417-138, now
  ublock-filters: 35959-419, now
  ublock-privacy: 680-6, now
  ublock-quick-fixes: 121-51, now
  ublock-unbreak: 2160-36, now
  urlhaus-1: 9965-0, now
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1267 ms (selfie)
 maxAssetCacheWait: 608 ms
popupPanel:
 blocked: 43
 network:
  datacheap.io: 1
  arc.io: 28
  bidvance.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  headerbidding.ai: 1
  holid.io: 1
  mgid.com: 5
  pubfuture-ad.com: 1
  sharethis.com: 2
  shriftskats.com: 1
 extended:
  ##AMP-AD
  ##div[id*="ScriptRoot"]
```
</details>

**Comment by BlazeFTL** [comment]
Faucet😒😒😒
```
aduzz.com,bitcrypto.info###wpsafe-link:style(display: block !important;)
aduzz.com,bitcrypto.info###wpsafe-link:others()
aduzz.com,bitcrypto.info##+js(no-fetch-if, ads)
aduzz.com,bitcrypto.info##+js(set, wpsafelinkCount, 0)
