### ISSUE TITLE
racingnews365.com: nuisance

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uAssets#20782]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://racingnews365.com/watch-hot-lap-of-brand-new-las-vegas-gp-track` 

or 

`https://racingnews365.com/watch-nascar-driver-ryan-preece-survives-daytona-barrel-roll-accident`

### Category

nuisance

### Description

Cookies banner. 

### Other extensions used

Keep One Pinned Tab

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-11-20_192018](https://github.com/uBlockOrigin/uAssets/assets/111344219/1c3702a4-6afa-4f50-ba42-58eaab7d94c5)
</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 115983
 cosmetic: 114578
 scriptlet: 25592
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26176-19, 15m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1672-27, 15m
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 1282-0, 15m
  adguard-cookies: 28114-248, 15m
  ublock-annoyances: 5872-22, 15m
 default:
  user-filters: 3-0, never
  ublock-filters: 35652-51, 15m
  ublock-badware: 7423-10, 15m
  ublock-privacy: 680-9, 15m
  ublock-unbreak: 2155-7, 15m
  ublock-quick-fixes: 128-52, 15m
  easylist: 75517-283, 15m
  easyprivacy: 32900-401, 15m
  RUS-0: 40079-283, 15m
filterset (user): [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 997 ms (selfie)
 maxAssetCacheWait: 552 ms
popupPanel:
 blocked: 6
 network:
  racingnews365.com: 1
  amazon-adsystem.com: 1
  consentmanager.net: 2
  doubleclick.net: 1
  googletagmanager.com: 1
 extended:
  ##.header__socials
  ##.ad__wrapper
  ##.footer__socials
  ##.share__item
  ##.share__link
  ##a[href^="whatsapp://send"]
```
</details>

**Comment by mapx-** [comment]
`trusted-click-element` seems cannot click an element included in `shadow.root`

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/a2264036-7179-4457-89d0-8b8839244d29)

**Comment by gorhill** [comment]
It is not possible to `querySelector` elements across shadowdom boundary. We would need a new notation to indicate a shadowdom element, from which a new `querySelector` would take place.

**Comment by peace2000** [comment]
This rule:

`racingnews365.com##+js(trusted-click-element, [href="#allow-cookieconsent"])`

Will load the first embedded element, though not the second. Not a fix but a partial workaround.

**Comment by mapx-** [comment]
it seems working, but who uses EL cookies has to whitelist some stuff

```
@@||delivery.consentmanager.net/delivery/cmp.php$script,domain=racingnews365.com
@@||cdn.consentmanager.net/delivery/$script,domain=racingnews365.com
```

@ryanbr

**Comment by peace2000** [comment]
Added https://github.com/uBlockOrigin/uAssets/commit/b8d78616cd36d2c2ff513ff2a461ac996cca7104

Also added whitelistings, can be removed when ryanbr adds exceptions to EL.
