### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by ComplejoC** [uBlockOrigin/uAssets#20783]
### Prerequisites

- [ ] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=pnu1iIWGZ5w&t=255s`

### Category

detection

### Description

This is a Youtube report: For some reason it wouldn't let me submit the report unless I clicked on that button. I'm so sorry. 

uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 103598
 cosmetic: 43786
 scriptlet: 18910
 html: 1105
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 36537-89, 8m
  ublock-badware: 7427-10, 8m
  ublock-privacy: 674-0, 8m
  ublock-unbreak: 2201-1, 8m
  ublock-quick-fixes: 128-12, 8m
  easylist: 75532-658, 8m
  easyprivacy: 32902-770, 8m
  urlhaus-1: 9970-0, 8m
  plowe-0: 3717-1, 8m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11482 ms (selfie)
 maxAssetCacheWait: 2697 ms
popupPanel:
 blocked: 10
 network:
  youtube.com: 6
  doubleclick.net: 2
  google-analytics.com: 1
  google.com: 1
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-fetch-response, /((?:(?:&|%26)id(?:=|%3D)o…
  ##+js(trusted-replace-fetch-response, /(contextParams":"Q0F[A-Z]…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 103598
 cosmetic: 43786
 scriptlet: 18910
 html: 1105
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  ublock-filters: 36537-89, 8m
  ublock-badware: 7427-10, 8m
  ublock-privacy: 674-0, 8m
  ublock-unbreak: 2201-1, 8m
  ublock-quick-fixes: 128-12, 8m
  easylist: 75532-658, 8m
  easyprivacy: 32902-770, 8m
  urlhaus-1: 9970-0, 8m
  plowe-0: 3717-1, 8m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11482 ms (selfie)
 maxAssetCacheWait: 2697 ms
popupPanel:
 blocked: 10
 network:
  youtube.com: 6
  doubleclick.net: 2
  google-analytics.com: 1
  google.com: 1
 extended:
  ###player-ads
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##a[href^="https://www.googleadservices.com/pagead/aclk?"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-fetch-response, /((?:(?:&|%26)id(?:=|%3D)o…
  ##+js(trusted-replace-fetch-response, /(contextParams":"Q0F[A-Z]…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20586
