### ISSUE TITLE
atresplayer.com: breakage

### ISSUE THREAD

**Issue by helpman** [uBlockOrigin/uAssets#20784]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.atresplayer.com/`

### Category

breakage

### Description

If ublock is enabled, the website just won't load. if I disable it, it shows it detects an ad blocker. Using chrome, built in ad blocker is disabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 106120
 cosmetic: 50107
 scriptlet: 19496
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75532-16, now
  easyprivacy: 32902-64, now
  plowe-0: 3717-1078, now
  spa-0: 3767-20, now
  spa-1: 5755-225, now
  ublock-badware: 7423-137, now
  ublock-filters: 35656-182, now
  ublock-privacy: 679-5, now
  ublock-quick-fixes: 128-51, now
  ublock-unbreak: 2155-34, now
  urlhaus-1: 9970-0, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 710 ms (selfie)
 maxAssetCacheWait: 395 ms
popupPanel:
 blocked: 7
 network:
  adsrvr.org: 1
  amazon-adsystem.com: 1
  everesttech.net: 1
  imasdk.googleapis.com: 1
  mathtag.com: 1
  scorecardresearch.com: 1
  spotxchange.com: 1
 extended:
  ##+js(nano-setTimeout-booster, [native code], 5000)
  ##+js(no-fetch-if, doubleclick)
```
</details>

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
