### ISSUE TITLE
streambuddy.net: nuisance

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20790]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://streambuddy.net/`

### Category

nuisance

### Description

Right-click is disabled and the text is unselectable. There is also an ad placeholder on the right side of the page.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103912
 cosmetic: 45329
 scriptlet: 23140
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5875-9, now
 default:
  user-filters: 57-2, never
  easylist: 75532-16, now
  easyprivacy: 32902-64, now
  plowe-0: 3718-1078, now
  ublock-badware: 7423-137, now
  ublock-filters: 35639-156, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 114-37, now
  ublock-unbreak: 2155-33, now
  urlhaus-1: 9970-0, now
filterset (user): [array of 56 redacted]
trustedset:
 added: [array of 21 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 335 ms
 maxAssetCacheWait: 161 ms
popupPanel:
 blocked: 10
 network:
  google.com: 6
  googlesyndication.com: 2
  googletagmanager.com: 1
  wp.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by gorhill** [comment]
Suggested filters:

    streambuddy.net##+js(rmnt, script, oncontextmenu)
    streambuddy.net## body *:style(user-select: unset !important)
    streambuddy.net##.elementor-top-column h6:has-text(advertisement):upward(.elementor-top-column)

**Comment by huyszn** [comment]
> Suggested filters:
> 
> ```
> streambuddy.net##+js(rmnt, script, oncontextmenu)
> streambuddy.net## body *:style(user-select: unset !important)
> streambuddy.net##.elementor-top-column h6:has-text(advertisement):upward(.elementor-top-column)
> ```

This works.
