### ISSUE TITLE
graphicuv.com: detection

### ISSUE THREAD

**Issue by americanape** [uBlockOrigin/uAssets#20799]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://graphicuv.com/what-is-the-importance-of-branding-and-signature-style-for-company`

### Category

detection

### Description

Detecting ad block and element zapper/picker mode not working

### Other extensions used

no other extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103496
 cosmetic: 43783
 scriptlet: 19066
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 75534-16, now
  easyprivacy: 32903-64, now
  plowe-0: 3718-1079, now
  ublock-badware: 7423-137, now
  ublock-filters: 35634-157, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 111-34, now
  ublock-unbreak: 2155-32, now
  urlhaus-1: 9855-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 300 ms (selfie)
 maxAssetCacheWait: 53 ms
popupPanel:
 blocked: 7
 network:
  graphicuv.com: 1
  doubleclick.net: 2
  googlesyndication.com: 3
  googletagmanager.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
Same `graphicuv.com##+js(aost, setTimeout, adsBlocked)`

**Comment by JobcenterTycoon** [comment]
Example link?

**Comment by americanape** [comment]
it's coming from olamovies.beauty link shortner. When trying to download movies from here, its link generator generate these links. Some of those are perfectly blocked by ublock and some are detected.
PS: As far as i know it uses different link generators, only few of them can detect ublock.

**Comment by JobcenterTycoon** [comment]
@BlazeFTL if you want can you take a look on

```
https://lksfy.com/p6g3jiolam
https://linkx.in/yx5358olam
https://go.owllink.net/klog40olam
https://vlshort.com/gy7oivolam
```

? I don’t get `graphicuv.com` but a lot of other shorteners which need filter and you have the best knowlege for these shorteners.

**Comment by okiehsch** [comment]
I can reproduce the detection at the given link in the post of the OP.
The suggested filter works for me.

**Comment by BlazeFTL** [comment]
PR Will Be Pushed Soon....
`graphicuv` Is From `lksfy.com/p6g3jiolam`
