### ISSUE TITLE
hax.co.id: detection

### ISSUE THREAD

**Issue by nspron** [uBlockOrigin/uAssets#20798]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://hax.co.id/`

### Category

detection

### Description

no

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.4
Chromium: 119
filterset (summary):
 network: 118499
 cosmetic: 54175
 scriptlet: 19241
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CHN-0: 25748-136, now
  easylist: 75534-26, now
  easyprivacy: 32903-77, now
  plowe-0: 3718-1081, now
  ublock-badware: 7423-137, now
  ublock-filters: 35638-173, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 115-38, now
  ublock-unbreak: 2155-33, now
  urlhaus-1: 9855-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 536 ms (selfie)
 maxAssetCacheWait: 217 ms
popupPanel:
 blocked: 5
 network:
  google.com: 1
  googlesyndication.com: 3
  googletagmanager.com: 1
 extended:
  ##+js(no-fetch-if, googlesyndication)
```
</details>

**Comment by BlazeFTL** [comment]
`@@||hax.co.id^$ghide`

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9653a3928c2c58bee0227f85a4596d92e87f945f
