### ISSUE TITLE
twitter.com: ads

### ISSUE THREAD

**Issue by S00pergang** [uBlockOrigin/uAssets#20792]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://twitter.com/`

### Category

ads

### Description

It seems twitter has done something so now ads are appearing in replies along with For You Page and Following.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/112852330/5bc35177-b8d6-428c-a78a-f8d91b625780)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103611
 cosmetic: 43778
 scriptlet: 19072
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 75532-16, now
  easyprivacy: 32902-64, now
  plowe-0: 3718-1078, now
  ublock-badware: 7423-137, now
  ublock-filters: 35634-156, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 114-37, now
  ublock-unbreak: 2155-32, now
  urlhaus-1: 9970-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 337 ms
 maxAssetCacheWait: 148 ms
popupPanel:
 blocked: 15
 network:
  twitter.com: 13
  ads-twitter.com: 1
  google-analytics.com: 1
```
</details>

**Comment by gorhill** [comment]
I can reproduce. Investigating an optimal solution.

**Comment by polymorphicshade** [comment]
I forgot how cancerous the ads are on twitter...

**Comment by gorhill** [comment]
My suggestion (if filter authors agree):

    twitter.com##article path[d^="M13.1"]:upward([data-testid="cellInnerDiv"])

**Comment by Hakkin** [comment]
`path[d^="M13.1"]` seems to match the verified business icon? I'm seeing ads from accounts without that icon. `[data-testid="cellInnerDiv"]:has([data-testid='placementTracking'])` seems to block it for me, though obviously `placementTracking` is some kind of debug tag so Twitter could change it at will.

**Comment by unbeatable-101** [comment]
I added `twitter##[data-testid="cellInnerDiv"] article:has(path[d^="M13.1"])` to my filters and still am seeing ads, from accounts with verified business icons as well.

**Comment by rehashedsalt** [comment]
>I'm seeing ads from accounts without that icon.

Same. I also follow at least one account who has purchased the business verified tier _as a joke_, and would be erroneously blocked by that filter. It'd also catch business accounts that users follow because they're actually interested in them.

@Hakkin's solution seems like a good triage, but I feel there's untapped potential here for something more robust.

This filter works, albeit only for English users. I don't think it's a good solve -- there's really no way to break localization here other than to have one filter for each language twitter supports -- but it works:

```
## article:has(span:has-text(/^Ad$/))
```

Other possible selection opportunities: legitimate posts have a timestamp next to the user handle in the header of the post. Ads by definition can't have that timestamp. Twitter puts a separator character (`·`) in-between the handle and the timestamp if it exists; selecting for that character might be a good starting point. It'd need some finagling since poll ads get that character to display the vote count.

**Comment by SakhJack** [comment]
> `[data-testid='placementTracking']` seems to block it for me

`placementTracking` is used for media in regular tweets

example: `https://twitter.com/AzaelOfficial/status/1726754958480232620`

**Comment by gorhill** [comment]
> `## article:has(span:has-text(/^Ad$/))`

Efficiency-wise, this is a terrible filter, `span` returns hundreds of matching elements, which means `:has-text()` will have to iterate through all those element.

I advise people to not paste into my filters any such suggestion from non-experienced filter list authors. The goal here is to find the minimum set of efficient filters which fulfill the task.

For now I will add `twitter##[data-testid="cellInnerDiv"] article:has(path[d^="M13.1"])` to the list, we can improve on it thereafter.

**Comment by Hakkin** [comment]
`twitter##[data-testid="cellInnerDiv"] article:has(path[d^="M13.1"])` blocks *every* tweet from any verified business account, which has nothing to do with ads.

**Comment by gorhill** [comment]
If you want to report issue with that filter, post your troubleshooting information, this is a necessary step, just saying "it doesn't work" doesn't work:

Go to `twitter.com`, click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

**Comment by gorhill** [comment]
@Hakkin Please post an example of tweets from such "verified business" which is not an ad.

**Comment by Hakkin** [comment]
> @Hakkin Please post examples of tweets from such "verified business" which is not an ad.

All the tweets on https://twitter.com/ibm, for example. There are many other verified business Twitter accounts.

**Comment by gorhill** [comment]
Ok I spotted one such verified business which was not an ad. Reverted.

**Comment by RambIing** [comment]
its worth noting all sponsored tweets have a div with the `data-testid` being `top-impression-pixel`. Could not find it on any other tweets. Not sure if this is reproducible with Twitter in other languages?
![image](https://github.com/uBlockOrigin/uAssets/assets/16966523/ee9eb64a-1d3f-41e5-bdb0-d130fe61e9a9)

**Comment by gorhill** [comment]
@Rambling Good observation.

So about:

    twitter.com##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])

Feedback needed.

**Comment by gorhill** [comment]
Click to force an update of quick-fixes list:

<https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes>

**Comment by DaisukeDaisuke** [comment]
In rare cases, blank spaces or flickering occur. Is this the intended behavior? 
The flickering is, in my opinion, due to reinsertion and is unavoidable


![Desktop Screenshot 2023 11 21 - 13 31 43 67](https://github.com/uBlockOrigin/uAssets/assets/17798680/317369a3-b9e1-4e20-9c5b-39f3ff5bae49)
```
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 172081
 cosmetic: 162815
 scriptlet: 43044
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
 added:
  adguard-generic: 80226-489, 38m
  adguard-social: 22006-36, 38m
  adguard-spyware: 72539-1208, 38m
  adguard-spyware-url: 1327-5, 38m
  block-lan: 55-0, 38m
  fanboy-cookiemonster: 48925-226, 38m
  ublock-annoyances: 5875-97, 38m
  ublock-quick-fixes: 115-40, 38m
 default:
  user-filters: 1388-16, never
  JPN-1: 13788-6, 38m
  easylist: 75532-1693, 38m
  easyprivacy: 32902-16416, 38m
  plowe-0: 3718-1179, 38m
  ublock-badware: 7423-329, 38m
  ublock-filters: 35635-3949, 38m
  ublock-privacy: 680-184, 38m
  ublock-unbreak: 2155-148, 38m
filterset (user): [array of 1393 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 19 redacted]
userSettings:
 largeMediaSize: 1
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1316 ms (selfie)
 maxAssetCacheWait: 444 ms
popupPanel:
 blocked: 12
 network:
  twitter.com: 10
  ads-twitter.com: 1
  google-analytics.com: 1
 extended:
  ##div[data-testid="trend"]:has(path[d$="10H8.996V8h7v7z"])
  ##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"]:has…
  ##[data-testid="trend"]:has-text(/Promoted|Gesponsert|Promociona…
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
```

**Comment by cocona20xx** [comment]
> @rambling Good observation.
> 
> So how about:
> 
> ```
> twitter.com##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])
> ```
> 
> Feedback needed.

Gets rid of sponsored posts/ads but doesn't get rid of the trending sidebar and the such. 
The picker auto-generates the following when manually removing the 'please buy premium we need money' plea, alongside recommended users to follow and the trending sidebar:
```
twitter.com##.r-1f1sjgu.r-ymttw5.r-uaa2di.r-eqz5dr.r-1habvwh.css-175oi2r
twitter.com##div.r-14wv3jr.r-g2wdr4.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.css-175oi2r:nth-of-type(4)
twitter.com##div.r-14wv3jr.r-g2wdr4.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.css-175oi2r:nth-of-type(5)
twitter.com##div.r-14wv3jr.r-g2wdr4.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.css-175oi2r:nth-of-type(3)
twitter.com##.r-14wv3jr.r-g2wdr4.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.css-175oi2r
```

**Comment by RambIing** [comment]
> > @rambling Good observation.
> > So how about:
> > ```
> > twitter.com##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Feedback needed.
> 
> Gets rid of sponsored posts/ads but doesn't get rid of the trending sidebar and the such. The picker auto-generates the following when manually removing the 'please buy premium we need money' plea, alongside recommended users to follow and the trending sidebar:
> 
> ```
> twitter.com##.r-1f1sjgu.r-ymttw5.r-uaa2di.r-eqz5dr.r-1habvwh.css-175oi2r
> twitter.com##div.r-14wv3jr.r-g2wdr4.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.css-175oi2r:nth-of-type(4)
> twitter.com##div.r-14wv3jr.r-g2wdr4.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.css-175oi2r:nth-of-type(5)
> twitter.com##div.r-14wv3jr.r-g2wdr4.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.css-175oi2r:nth-of-type(3)
> twitter.com##.r-14wv3jr.r-g2wdr4.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.r-1867qdf.css-175oi2r
> ```

This isn't very stable of a filter, since the class names will update once they push a new frontend update

**Comment by huyszn** [comment]
@DaisukeDaisuke I get the blank spaces / flickering when I refresh a Twitter page and then immediately scroll down.

**Comment by RambIing** [comment]
@gorhill noticed something that the new filter doesn't block. Ads still show if you open a tweet through the image. 
![image](https://github.com/uBlockOrigin/uAssets/assets/16966523/14da0e63-2c3b-43b0-a4c7-713cfd5591e9)
![image](https://github.com/uBlockOrigin/uAssets/assets/16966523/01de7736-a255-4181-afc8-f90f911757e0)

```##[aria-label="Timeline: Conversation"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])```
or
```##[aria-labelledby="accessible-list-9"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])```
seems to fix this.

**Comment by DaisukeDaisuke** [comment]
@gorhill It also appears that you are unable to block the reply ads that appear with the images
Problematic URL: (Please click on the image)
https://twitter.com/gorhill/status/996016461943574528/photo/1

Ads have `placementTracking`, so in my opinion it would be a good idea to block this
I am a beginner in filters, so please do not add it to My Filters as is
```
##[data-testid="placementTracking"]
```
The html of the ad is as follows. McAfee is inserting html, but it's probably not relevant
[ad.txt](https://github.com/uBlockOrigin/uAssets/files/13424962/ad.txt)


![Desktop Screenshot 2023 11 21 - 19 13 26 16](https://github.com/uBlockOrigin/uAssets/assets/17798680/fddc7fb0-5284-4438-808e-a02e5af99745)

**Comment by huyszn** [comment]
How about this filter for blocking reply ads that appear when you click on images?
`twitter.com##[data-viewportview="true"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])`

**Comment by DaisukeDaisuke** [comment]
I was unable to reproduce the problem after forcefully updating the filter
I'm sorry

**Comment by DaisukeDaisuke** [comment]
Sorry for reposting(i am confused)
I was unable to reproduce the problem after forcefully updating the filter.
I'm sorry

**Comment by Hakkin** [comment]
> Problematic URL: (Please click on the image)
> https://twitter.com/gorhill/status/996016461943574528/photo/1

I was able to reproduce it using this URL using the latest filters, An ad will show in the rightmost column when you click to expand the main image. It's because that column doesn't have the `primaryColumn` testid.

Removing the `[data-testid="primaryColumn"]` selector from the current filter fixes it for me. (ie: `twitter.com##[data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])`)

**Comment by DaisukeDaisuke** [comment]
`AdGuard – Ads` solution seems to remove ads next to images
https://github.com/AdguardTeam/AdguardFilters/issues/166718

https://github.com/AdguardTeam/AdguardFilters/commit/b3a8e2d0d5ec88f90a0c0d2ea079ac87cc7a660c

**Comment by rpodric** [comment]
> I forgot how cancerous the ads are on twitter...

Kinda reminds me how they were done on Instagram, though the fix for that apparently never happened in any permanent way that I've seen.

**Comment by gorhill** [comment]
I don't see the label "Ad" in that tweet:

<details><summary>screenshot</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/dd9463a0-f8fb-4022-b15e-d9178c057866)

</details>

And the 3-dot menu doesn't have an entry like "About this ad", it's a plain tweet on my side.

**Comment by RambIing** [comment]
> I don't see the label "Ad" in that tweet:
> 
> screenshot
> And the 3-dot menu doesn't have an entry like "About this ad", it's a plain tweet on my side.
> 
> Also, the reporter's troubleshooting information doesn't show that the new filter was injected on the page:
> 
> extended: ##[data-testid="trend"]:has-text(/Promoted|Gesponsert|Promociona… ##div[data-testid="trend"]:has(path[d$="10H8.996V8h7v7z"])
> 
> Twitter is a long-lived page, people have to make sure that the page is reloaded after they force an update of filter lists.

Had that as well earlier but in the replies of a tweet with an image:
<details>
<summary> Screenshots</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/16966523/6221eb5a-2f60-44c7-aaa5-68213b9d4d66)
![image](https://github.com/uBlockOrigin/uAssets/assets/16966523/b499cb95-b837-4d09-a88c-3aca98dfe308)
![image](https://github.com/uBlockOrigin/uAssets/assets/16966523/047eb9ae-bd98-4d8b-af6b-786eafe1ccf0)


</details>

Seems to omit the tracking HTML found earlier. Hard to reproduce (took at minimum 20 tries to get the one in the screenshot), but the earliest case I can find is this: https://twitter.com/MattBinder/status/1700227953043337662

First thought is to check graphQL request for the json object `promotedMetadata` since the HTML is indistinguishable from an actual tweet

**Comment by D4niloMR** [comment]
```adb
twitter.com##[aria-label^="Timeline:"] [data-testid="cellInnerDiv"] > div:has([data-testid="top-impression-pixel"]):remove()
```

This filter fix both: https://github.com/uBlockOrigin/uAssets/issues/20792#issuecomment-1820244711 https://github.com/uBlockOrigin/uAssets/issues/20792#issuecomment-1820650175 

Also if they add video ads this will prevent the video playing in the background.

**Comment by stephenhawk8054** [comment]
Anyone with dev build, can you test this filter? This one is to prune the ads post from the request using new update of `json-prune`

```adb
twitter.com##+js(json-prune-xhr-response, data.home.home_timeline_urt.instructions.[].entries.[-].content.itemContent.promotedMetadata, , propsToMatch, url:HomeTimeline)
```

**Comment by gwarser** [comment]
@stephenhawk8054 it targets these?

![image](https://github.com/uBlockOrigin/uAssets/assets/886325/9c228a78-6f60-4ea9-86f6-9415d709f54a)


Then looks like it works.

**Comment by stephenhawk8054** [comment]
Yup, I meant the posts with `Ad` there.

**Comment by Yuki2718** [comment]
Looks working on home timeline and comments, but ofc not on search and promotion in right-side.

**Comment by stephenhawk8054** [comment]
It would be the same idea for search

```adb
twitter.com##+js(json-prune-xhr-response, data.search_by_raw_query.search_timeline.timeline.instructions.[].entries.[-].content.itemContent.promotedMetadata, , propsToMatch, url:/api/graphql)
```

Actually I would think clear separate json paths would be better for performance as they don't need to loop through many (nested) entries

**Comment by Yuki2718** [comment]
As JSONPath is specifically made to search and extract in json, I guess it's good addition anyway.

> I can't reproduce the right side tho, and I don't know how they look like. It just shows "Trends for you" and "Who to follow" on my side.

As with other ads, you have to refresh many times. Sometimes still may not be shown, then just test after a while.

**Comment by stephenhawk8054** [comment]
I think JSONPath-related would take quite some time to implement (if we decide to). 

It's not just this site, but I think the network-related scriptlets are mainly for co-operating with the cosmetic ones, to reduce the number of potential glitches/slipped caused by cosmetic filters, especially for dynamic big sites like this. Raw data are usually not manipulated as much as after they are represented in DOM (once they are in DOM, websites can do whatever they want via js and css), since those data could be used internally by the sites too.

I think having solutions for 2 approaches at the same time would be good.

**Comment by Yuki2718** [comment]
Yeah, it's just if gorhill have time to implement. But Twitter/X has been changing structure and things like `threaded_conversation_with_injections_v2` is likely to change in future, while `promotedMetadata` may still be constant. Similar to entity filters, wildcard or JSONPath will reduce the maintenance cost in the long run.

**Comment by gorhill** [comment]
I wasn't aware of JSONPath, this will require some reading: <https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-03.html>

**Comment by stephenhawk8054** [comment]
I think another aspect of JSONPath would be the select of the values in the objects? Which is not a concept in current `objectPrune` yet.

For example, pruning a branch if the there's an object `{"key": "Ad"}` follows.

**Comment by stephenhawk8054** [comment]
I think we can test the filters in dev build first.

**Comment by Yuki2718** [comment]
Sure, go ahead.

**Comment by Yuki2718** [comment]
I guess https://github.com/AdguardTeam/AdguardFilters/commit/019a78ddf86d2b960a1a712acf11556844a93d69 is not covered?

**Comment by stephenhawk8054** [comment]
I don't think so. Need to be able to reproduce first.

**Comment by stephenhawk8054** [comment]
Ok, I think this works for me:

```adb
x.com##+js(json-prune-xhr-response, data.immersiveMedia.timeline.instructions.[].entries.[-].content.itemContent.promotedMetadata, , propsToMatch, url:/ImmersiveMedia)
```
