### ISSUE TITLE
amazon.com: breakage

### ISSUE THREAD

**Issue by unforgettableid** [uBlockOrigin/uAssets#20795]
# Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

# Category

breakage

# Description

### Steps to reproduce

1.  👉 Please set uBO to [block all remote fonts by default](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-remote-fonts).  Otherwise, you cannot reproduce this breakage.
2.  Visit the URL:
`https://www.amazon.ca/Gut-Inside-Story-Underrated-Revised/dp/1771643765?asin=B0795B7M79&revisionId=78b45cab&format=1&depth=1`
3.  Below the book cover image, click the white button labelled "Read sample".

### Observed

1.  The book cover appears, but no sample.
2.  Perhaps 10 seconds later, Amazon eventually shows an error message:  "Sorry, there was a problem loading this page."

### Expected

I was hoping to view the book sample.

### Notes

I've confirmed that this issue exists on amazon.com and amazon.ca.  I'm not sure about Amazon's other websites.

I wonder if you could please add a rule to unbreak.txt.  This new rule would always allow sufficient remote fonts so that all book samples are viewable.

# Other extensions used

Blocksi Web Filter and [Plucky Filter](https://pluckyfilter.com/).

(Please forgive me for not having disabled them.  For various reasons, I've left them both enabled.  However, I'm pretty sure that I've narrowed the issue down enough to show that the breakage is caused solely by uBO.)

# Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 125595
 cosmetic: 196318
 scriptlet: 30178
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75324-118, 7m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94876-21822, 7m
  adguard-social: 22006-1618, 8m
  dpollock-0: 11584-2, 7m
  fanboy-cookiemonster: 48926-48926, 7m
  fanboy-social: 16210-16210, 7m
  fanboy-thirdparty_social: 68-18, 7m
  ublock-annoyances: 5887-216, 7m
 default:
  user-filters: 1172-1, never
  easylist: 75534-345, 7m
  easyprivacy: 32903-367, 7m
  plowe-0: 3718-1453, 7m
  ublock-badware: 7423-138, 7m
  ublock-filters: 35636-519, 7m
  ublock-privacy: 680-7, 7m
  ublock-quick-fixes: 115-38, 7m
  ublock-unbreak: 2155-36, 7m
  urlhaus-1: 9855-0, 7m
filterset (user): [array of 1080 redacted]
trustedset:
 added: [array of 160 redacted]
 removed:
  chrome-extension-scheme
  edge-scheme
switchRuleset:
 added: [array of 186 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 371461 ms (selfie)
 maxAssetCacheWait: 8312 ms
popupPanel:
 blocked: 147
 no-remote-fonts: true
 network:
  amazon.ca: 102
  amazon-adsystem.com: 1
  amazon.com: 18
  amazonaws.com: 1
  b11v5ewz9l.execute-api.us-east-1.amazonaws.com: 4
  d3fpmv3m8wlug6.cloudfront.net: 4
  del51-p4.cloudfront.net: 1
  media-amazon.com: 12
  ssl-images-amazon.com: 4
 extended:
  ##.author-follow-button
  ###navBackToTop
  ##.reviews-display-ad
  ###rhf
  ##.maple-banner
  ###nav-swmslot
  ##div[cel_widget_id*="_ad-placements-"]
  ##div[cel_widget_id*="desktop-dp-"]
  ##div[cel_widget_id^="adplacements:"]
  ##div[id^="sp_detail"]
  ##[id*="related"]
  ##[class*="related"]
  ##[aria-label="Back to top"]
  ##[id*="sidebar"]
```
</details>

# Conclusion

Thank you!

**Comment by gorhill** [comment]
> Please set uBO to [block all remote fonts by default](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-remote-fonts). Otherwise, you cannot reproduce this breakage.

If blocking remote fonts breaks the site, then don't block remote fonts on that site? This is an opt-in per-site switch, it's up to you to use it and not use it if it breaks a site.

**Comment by gorhill** [comment]
> I wonder if you could please add a rule to unbreak.txt. This new rule would always allow sufficient remote fonts so that all book samples are viewable.

You can't bypass rules with filters, all rules have precedence over filters, and rules are to be used at your own discretion, by default none of them interfere with filters.

**Comment by unforgettableid** [comment]
Dear @gorhill:

I'm already aware that I can create an exception rule so that Amazon can load web fonts no matter what.  Perhaps my main concern is for other users, who might not realize why Amazon book previews aren't loading.

I've proposed two possible solutions, [above](https://github.com/uBlockOrigin/uAssets/issues/20795#issuecomment-1821159847).
