### ISSUE TITLE
daotranslate.com: detection

### ISSUE THREAD

**Issue by ianjchiu** [uBlockOrigin/uAssets#20794]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://daotranslate.com/`

### Category

detection

### Description

Detects Adblock. Red screen + blurred out background. Able to block out the red screen, but unable to block the blurring.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/21212551/9518fb94-5ee5-4337-952a-5959f1120af7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 114812
 cosmetic: 195208
 scriptlet: 30177
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28116-30, 29m
  adguard-mobile-app-banners: 4790-9, 28m
  adguard-other-annoyances: 13815-8, 27m
  adguard-popup-overlays: 26256-69, 26m
  adguard-social: 22006-925, 25m
  adguard-widgets: 2346-3, 24m
  easylist-annoyances: 4186-209, 36m
  easylist-chat: 161-11, 33m
  easylist-newsletters: 6684-435, 35m
  easylist-notifications: 2877-1454, 34m
  fanboy-cookiemonster: 48926-3813, now
  fanboy-social: 16210-731, now
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 75534-76, now
  easyprivacy: 32903-178, now
  plowe-0: 3718-1080, now
  ublock-badware: 7423-137, 32m
  ublock-filters: 35635-516, 31m
  ublock-privacy: 680-7, now
  ublock-quick-fixes: 115-38, 22m
  ublock-unbreak: 2155-36, 30m
  urlhaus-1: 9855-0, 23m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 437 ms (selfie)
 maxAssetCacheWait: 184 ms
popupPanel:
 blocked: 13
 network:
  b-cdn.net: 5
  doubleclick.net: 2
  googlesyndication.com: 4
  histats.com: 1
  pubfuture-ad.com: 1
 extended:
  ##.socialts
  ##a[href^="whatsapp://send"]
  ##a[href^="https://www.twitter.com/intent/tweet?"]
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href*="pinterest.com/pin/create/button"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(abort-current-script, eval, replace)
```
</details>

**Comment by BlazeFTL** [comment]
Theres More Anti Things😑
```
daotranslate.com##+js(rmnt, script, wccp_pro)
daotranslate.com##+js(aopw, document.oncontextmenu)
daotranslate.com##+js(aost, document.getElementsByTagName, adsBlocked)
