### ISSUE TITLE
btnull.org: ads

### ISSUE THREAD

**Issue by UCan927** [uBlockOrigin/uAssets#20793]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.btnull.org/`

### Category

[unknown]

### Description

> 两侧有广告;

**There are advertisements on both sides;**

### Other extensions used

无

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 118499
 cosmetic: 54172
 scriptlet: 19239
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-1, never
  CHN-0: 25746-136, now
  easylist: 75532-26, now
  easyprivacy: 32902-77, now
  plowe-0: 3718-1080, now
  ublock-badware: 7423-137, now
  ublock-filters: 35634-172, now
  ublock-privacy: 680-5, now
  ublock-quick-fixes: 114-37, 43m
  ublock-unbreak: 2155-33, now
  urlhaus-1: 9855-0, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 688 ms (selfie)
 maxAssetCacheWait: 149 ms
popupPanel:
 blocked: 3
 network:
  baidu.com: 1
  stgowan.com: 2
```
</details>

**Comment by mapx-** [comment]
I get those ads only badfiltering

```
||stgowan.com^$badfilter
||stgowan.com^$3p,badfilter
```

**Comment by mapx-** [comment]
@cjx82630
