### ISSUE TITLE
rp-online.de

### ISSUE THREAD

**Issue by okiehsch** [uBlockOrigin/uAssets#208]
### URL(s) where the issue occurs
`http://www.rp-online.de`

### Describe the issue
Self-defacement ads triggered by `https://www.adternal.com/1480113997448/ad-loading.bmp`

### Screenshot(s)

![rp-online](https://cloud.githubusercontent.com/assets/16838044/20636243/9dc7084c-b369-11e6-88b2-24791ee8ec67.JPG)

### Versions

- Browser/version: Chrome 54
- uBlock Origin version: 1.9.16

### Settings

- Default

### Notes

The self-defacement was prevented by
`||adternal.com/*/ad-loading.*$image,redirect=2x2-transparent.png`
in the uBlock filters list. 
This no longer works, atleast for this specific site, because 
`adternal.com/1480113997448/ad-loading.bmp` is now a 3x2-transparent.png image/png;base64.
The new filter `||adternal.com/*/ad-loading.*$image,redirect=3x2-transparent.png`
should solve the issue.

Edit: The simple exception filter `@@||adternal.com/*/ad-loading.bmp$image`
also works.

**Comment by gorhill** [comment]
I am not able to see these ads using default settings + EasyList Gemany + VPN `.de`.

**Comment by okiehsch** [comment]
After a fresh install I can still reproduce on two different computers 
with default settings + Easylist Germany, I have a german IP.
The logger:
![adtern](https://cloud.githubusercontent.com/assets/16838044/20641411/589847f2-b3f7-11e6-8aee-f4aeb33503ad.PNG)

As you can see ad-loading.bmp is a 3x2 image/png
![adternal1](https://cloud.githubusercontent.com/assets/16838044/20641433/e0ee69ec-b3f7-11e6-8f16-21823d1fa75d.PNG)

If I  add `||adternal.com/*/ad-loading.*$image,redirect=3x2-transparent.png`
the issue is solved.
![adr](https://cloud.githubusercontent.com/assets/16838044/20641483/08b8d52e-b3f9-11e6-8f64-a8df0fe8e5f1.PNG)

**Comment by gorhill** [comment]
Forgot to change redirect, it still needs change in case other sites use this, I confirmed the code check for width of 3px.
