### ISSUE TITLE
chatgbt.one: detection

### ISSUE THREAD

**Issue by judemont** [uBlockOrigin/uAssets#20805]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://chatgbt.one/`

### Category

detection

### Description

chagpt.one detect ublock origin and ask for disabled it.

### Other extensions used

None .-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/96385330/cdc32f49-fe60-43ee-96ff-1e4b142c3574)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 122325
 cosmetic: 52869
 scriptlet: 19051
 html: 1106
listset (total-discarded, last-updated):
 added:
  FRA-0: 28614-335, 7m
 default:
  user-filters: 3-1, never
  ublock-filters: 36506-164, now
  ublock-badware: 7427-10, now
  ublock-privacy: 682-0, now
  ublock-unbreak: 2201-1, now
  ublock-quick-fixes: 111-0, 5m
  easylist: 75535-776, now
  easyprivacy: 32903-729, now
  urlhaus-1: 9880-0, 6m
  plowe-0: 3718-1, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 14 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 555 ms (selfie)
 maxAssetCacheWait: 269 ms
popupPanel:
 blocked: 9
 network:
  googlesyndication.com: 5
  googletagmanager.com: 2
  wp.com: 2
 extended:
  ##ins.adsbygoogle
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by ItsProfessional** [comment]
```adb
chatgbt.one##+js(noeval-if, chpadblock)
```
