### ISSUE TITLE
greentumble.com: ads

### ISSUE THREAD

**Issue by Snowpop** [uBlockOrigin/uAssets#20802]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://greentumble.com/5-factors-that-help-to-increase-biodiversity

### Description

Sometimes immediately, sometimes after a couple of minutes, a popup (shown in screenshot) appears on the website. Would appreciate it being blocked (which it isn't, with my current updated filters). 

### Other extensions used

Bitwarden, SCP Reddit by /u/LolDoofus (only active on Reddit), Bypass Paywalls, Power Thesaurus, 2FAS, Terms of Service; Didn't read, Wayback Machine, Nitter Redirect, Reddit Auto Dark Mode

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot](https://github.com/uBlockOrigin/uAssets/assets/88103045/60aa02c7-ea52-4234-8fd5-32290bef8ec2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 313000
 cosmetic: 244761
 scriptlet: 48468
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75344-117, 1m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1m
  https://o0.pages.dev/Lite/adblock.txt: 67173-127, 1m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94875-21956, 1m
  NLD-0: 2740-25, 2m
  RUS-0: 40079-526, 2m
  adguard-cookies: 28123-28123, 2m
  adguard-generic: 80256-4574, 2m
  adguard-mobile: 8750-608, 2m
  adguard-mobile-app-banners: 4792-4792, 2m
  adguard-other-annoyances: 13820-13820, 2m
  adguard-popup-overlays: 26263-26263, 2m
  [11 lists not shown]: [too many]
 default:
  user-filters: 16-0, never
  easylist: 75535-18719, 2m
  easyprivacy: 32903-22424, 2m
  plowe-0: 3718-2645, 1m
  ublock-badware: 7423-390, 1m
  ublock-filters: 35648-4378, 1m
  ublock-privacy: 680-190, 1m
  ublock-quick-fixes: 111-36, 1m
  ublock-unbreak: 2155-147, 1m
  urlhaus-1: 9880-1, 1m
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 14 redacted]
 removed:
  chrome-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 collapseBlocked: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 13450 ms (selfie)
 maxAssetCacheWait: 2529 ms
```
</details>

**Comment by huyszn** [comment]
Add these filters:
```
greentumble.com##.cp-overlay
greentumble.com##body,html:style(overflow: auto !important; position: initial !important;)
```
