### ISSUE TITLE
jornadaperfecta.com

### ISSUE THREAD

**Issue by oxkrprez** [uBlockOrigin/uAssets#20800]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.jornadaperfecta.com/`

### Description

inofrmation pop up at start

### Other extensions used

No

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/113279989/cb7cfcd5-0c2b-43ae-828a-68a1ad411765)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 106120
 cosmetic: 50132
 scriptlet: 19491
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 15-0, never
  easylist: 75534-16, now
  easyprivacy: 32894-64, 4d.33m
  plowe-0: 3723-1074, 8d.4h.42m
  spa-0: 3767-20, 20h.1m
  spa-1: 5746-225, 2d.24m
  ublock-badware: 7423-137, 1d.30m
  ublock-filters: 35664-182, 1d.29m
  ublock-privacy: 680-5, 1h.7m
  ublock-quick-fixes: 115-36, 1h.6m
  ublock-unbreak: 2155-34, 1d.28m
  urlhaus-1: 9970-0, 20h
filterset (user): [array of 15 redacted]
trustedset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 378 ms (selfie)
 maxAssetCacheWait: 155 ms
```
</details>

**Comment by huyszn** [comment]
Try this filter:
`jornadaperfecta.com##+js(rmnt, script, loadScript)`

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0c36990362fc8b0134125c27d049fdc98e4e195b

**Comment by oxkrprez** [comment]
Thanks
