### ISSUE TITLE
Accuweather artificial slow load with adblock

### ISSUE THREAD

**Issue by wooque** [uBlockOrigin/uAssets#20804]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://www.accuweather.com/

### Description

When accuweather.com loads there is few seconds delay before information is shown, but it's not because it takes few seconds to load information, but because it waits to load ads and than after some timeout it shows info.
I fixed it with:
```
accuweather.com##+js(remove-attr, class, .ads-not-loaded, stay)
```
Now accuweather.com loads instantly.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 103565
 cosmetic: 43786
 scriptlet: 18898
 html: 1107
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 36528-81, 3d.16h.5m
  ublock-badware: 7531-10, 3d.16h.5m
  ublock-privacy: 674-0, 3d.16h.5m
  ublock-unbreak: 2201-1, 3d.16h.5m
  ublock-quick-fixes: 115-0, 7h.13m
  easylist: 75483-703, 3d.16h.5m
  easyprivacy: 32894-726, 3d.16h.5m
  urlhaus-1: 9880-0, 2h.57m
  plowe-0: 3716-1, 3d.16h.5m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 476 ms (selfie)
 maxAssetCacheWait: 63 ms
popupPanel:
 blocked: 11
 network:
  3lift.com: 1
  adnxs.com: 1
  casalemedia.com: 1
  doubleclick.net: 2
  go-mpulse.net: 1
  parsely.com: 1
  pubmatic.com: 1
  rubiconproject.com: 1
  scorecardresearch.com: 1
  videoplayerhub.com: 1
 extended:
  ###top
  ##.glacier-ad
  ###connatix

```
</details>

**Comment by ItsProfessional** [comment]
```adb
accuweather.com##body:remove-class(ads-not-loaded)
```
