### ISSUE TITLE
afreecatv.com: ads

### ISSUE THREAD

**Issue by aaswqwdqssd** [uBlockOrigin/uAssets#20816]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [ ] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

(Afreeca TV is Korea’s Twitch) 
When you enter a broadcast, an advertisement plays.

### A specific URL where the issue occurs.

`https://www.afreecatv.com/`

### Steps to Reproduce

1. Access Afreeca TV (`www.afreecatv.com`)
2. Go to any broadcast
3. An advertising video plays.

### Expected behavior

ad blocking

### Actual behavior

Not working

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104786
 cosmetic: 47095
 scriptlet: 19251
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 12-0, never
  KOR-1: 4769-10, 8m
  easylist: 75608-58, 8m
  easyprivacy: 32903-74, 8m
  plowe-0: 3718-1094, 8m
  ublock-badware: 7438-137, 8m
  ublock-filters: 35667-163, 8m
  ublock-privacy: 688-7, 8m
  ublock-quick-fixes: 169-92, 8m
  ublock-unbreak: 2154-33, 8m
  urlhaus-1: 9820-0, 8m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 44 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 503 ms
 maxAssetCacheWait: 223 ms
```
</details>

**Comment by gorhill** [comment]
> Go to any broadcast

Unable to reproduce. For example, I navigated to `https://play.afreecatv.com/boaseforever/249210072`, no ads.
