### ISSUE TITLE
ygosu.com: breakage

### ISSUE THREAD

**Issue by aaswqwdqssd** [uBlockOrigin/uAssets#20815]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ygosu.com/`

### Category

breakage

### Description

site is broken

### Other extensions used

site is broken

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104786
 cosmetic: 47095
 scriptlet: 19251
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 12-0, never
  KOR-1: 4769-10, now
  easylist: 75608-58, now
  easyprivacy: 32903-74, now
  plowe-0: 3718-1094, now
  ublock-badware: 7438-137, now
  ublock-filters: 35667-163, now
  ublock-privacy: 688-7, now
  ublock-quick-fixes: 169-92, now
  ublock-unbreak: 2154-33, now
  urlhaus-1: 9820-0, now
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 43 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 503 ms
 maxAssetCacheWait: 223 ms
popupPanel:
 blocked: 5
 network:
  07c225f3.online: 3
  googletagmanager.com: 1
  vntsm.com: 1
 extended:
  ###contain > div[style*="margin-bottom:"]
  ##+js(no-xhr-if, /static\.criteo\.net|adsbygoogle/)
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(no-xhr-if, /07c225f3\.online|content-loader\.com/)
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/40990817687252b40daf4c952667f4aef56e06eb

Force update the filterlists.

A note: The Website is not "broken", its caused by a anti adblock script called "Ad-Shield" which want to fight content blocker. For the best results try [microShield](https://github.com/List-KR/microShield) because uBlock Origin can’t fully defuse this.
