### ISSUE TITLE
veganab.co: breakage

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#20810]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://veganab.co`

### Description

The filter 
`veganab.co###top-nav,.main-nav,.logo-container,.main-content,.container-wrapper,.site-info,.inst,.banner-inner`
(in uBlock filters - ads) breakes the site.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1333" alt="vegan" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/bbca5254-7b7a-499c-9aae-1b917d6825c1">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 113242
 cosmetic: 136558
 scriptlet: 26950
 html: 1299
listset (total-discarded, last-updated):
 added:
  adguard-social: 22010-169, now
  adguard-cookies: 28129-45, now
  ublock-cookies-adguard: 580-0, now
  adguard-popup-overlays: 26264-967, now
  adguard-mobile-app-banners: 4792-9, now
  adguard-other-annoyances: 13820-64, now
  adguard-widgets: 2346-1, now
  ublock-annoyances: 5853-593, now
  ITA-0: 9201-22, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36546-497, now
  ublock-badware: 7442-10, now
  ublock-privacy: 682-0, now
  ublock-unbreak: 2200-1, now
  ublock-quick-fixes: 169-2, now
  easylist: 75608-770, now
  easyprivacy: 32903-734, now
  urlhaus-1: 9820-0, now
  plowe-0: 3718-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 847 ms (selfie)
 maxAssetCacheWait: 393 ms
```
</details>

**Comment by BlazeFTL** [comment]
@superlex Its. A Shortner Right?
Give Initial Link

**Comment by superlex** [comment]
@BlazeFTL 
Sorry, I wrote wrong website.
https://github.com/uBlockOrigin/uAssets/assets/1375223/88f4063c-62d0-471f-9441-6e6a328f019f

**Comment by BlazeFTL** [comment]
@superlex You Didnt Answer The Question
Is It A News Site Or A Shortner

**Comment by superlex** [comment]
It's a website, not a shortner.
This is the link:
`https://veganab.co`

**Comment by D4niloMR** [comment]
@BlazeFTL 
`https://veganab.co/2022/12/26/explain-the-basics-of-cybersecurity-to-students-in-2023/`
`https://m.easysky.in/MK3KPaX`

**Comment by BlazeFTL** [comment]
https://github.com/uBlockOrigin/uAssets/pull/20821
https://github.com/uBlockOrigin/uAssets/pull/20821/commits/867e299dac51caad85f43b19f3ca9bf9d867645e

**Comment by superlex** [comment]
@BlazeFTL 

Sorry, I didn't know it was a shortner, and I didn't have the initial link.
