### ISSUE TITLE
eporner.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2081]
URL(s) where the issue occurs

`https://www.eporner.com/hd-porn/knsyjD3UrvM/Ass-Filled-With-Cum-After-Anal-Fucking-And-DP/`

Describe the issue

`https://i.imgur.com/MThTjAx.png`

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.0

Settings

Default

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by mapx-** [comment]
I added a filter to remove new popups, did you see ...ads or only popups ?

**Comment by okiehsch** [comment]
I can see ads, add
`eporner.com##script:inject(abort-on-property-read.js, exoDocumentProtocol)`
should also fix the popup.

**Comment by ghajini** [comment]
There's a popup

**Comment by mapx-** [comment]
How could we reproduce it ?

**Comment by ghajini** [comment]
Firefox android .....
Click anywhere In homepage or
NSFW
`https://www.eporner.com/hd-porn/CkybFXscDxb/Roses-With-Thorns/`
Click on `scenes` or `comments`
Popups arise.......

**Comment by ghajini** [comment]
@mapx-

**Comment by mapx-** [comment]
Still cannot reproduce.

try
`eporner.com##+js(abort-on-property-read.js, open)`

**Comment by spirillen** [comment]
Not to be the wise guy here, but I've tested the link above (or rather another as contents was deleted) but for what i noticed is that you get a response from `hf18yg8q.com` which i don't see at all all domains i see is `*.eporner.com`

So here my two questions....
1. Have you checked for any kind of infections that would need penicillin ?
1. Does anybody know what `hf18yg8q.com` is and why @ghajini should receive that queries?

PS. I see no spam, popup's- or under

FF 66.0.5 (64-bit) on ParrotSec
Privacy Badger v. 2017.11.20
uBo v. 1.14.18

**Comment by ghajini** [comment]
(Try on firefox android,iam using that.....)
Not work....also buttons `scenes,comments,info,download` stopped working with ubo enabled. ....

**Comment by okiehsch** [comment]
About the popup, does
`eporner.com##+js(abort-on-property-write.js, EPeventFire)`
work on your end?

**Comment by ghajini** [comment]
Doesn't work

**Comment by okiehsch** [comment]
Can you post all the 1st-party scripts loading on your end right before you get the popup.

**Comment by okiehsch** [comment]
It is important to load the site bypassing the cache if you do it.

**Comment by ghajini** [comment]
Iam on default settings without any filter now.....also I see different logger output at firefox desktop browser vs firefox android browser.....you will net get any popup at firefox desktop browser but you will get on firefox android
I see this whitelist `@@||eporner.com^$first-party,subdocument`
 from adguard mobile filter
![IMG_20190521_080920](https://user-images.githubusercontent.com/20338483/58064520-f09f3f80-7b71-11e9-9976-cb2a8ee30e86.jpg)

**Comment by ghajini** [comment]
> It is important to load the site bypassing the cache if you do it.
> Look for something like `https://www.eporner.com/js/bowser.php`.

What to investigate on that, I have that
`https://www.eporner.com/js/bowser.php?mobile=1`

**Comment by okiehsch** [comment]
Do you still get popups if that request
`https://www.eporner.com/js/bowser.php?mobile=1`
is blocked.

**Comment by ghajini** [comment]
Yes I get popups.....
Page served on my end....
`https://4html.net/PDFViewer/#/source/https%20_www.eporner.com_.pdf`
Try firefox android if you want to reproduce....
@kulfoon

**Comment by ghajini** [comment]
Reproduced with adguard browser extension for firefox android
Fyi @Alex-302

**Comment by ghajini** [comment]
Filing filter issues specific for firefox android,  ublock origin version is pain here, since no one among contributors had android device with them, how to solve? ??????
@gorhill(sorry to bother you, but many issues remain unsolved/take time to solve)

**Comment by ghajini** [comment]
Popups issues are solved.....but buttons  `scenes, comments,info,download` are broken.........
To solve this 
I disable `ublock filters` and add below filters & it solves both popups and unbreaking those buttons...

`||www.eporner.com/dotm/pop2.php$domain=www.eporner.com,important`

`||www.eporner.com/pop_mobile.php$important`

So ublock filters are blocking site

**Comment by ghajini** [comment]
@mapx-, @okiehsch
Here is way mimic firefox android....
1.
change your user agent to firefox android mobile and add `adguard mobile filters`(part of default on firefox android ublock )....

2.
Surf here
nsfw
`https://www.eporner.com/hd-porn/SMtDWUrL5Gq/Extreme-Gang-Bang-With-Hot-Brunette/`
3. `Play` button. And `scenes,comments,info,download` are broken

**Comment by mapx-** [comment]
all working fine for me (emulation builtin FF, other 2 user agent addons)

**Comment by okiehsch** [comment]
I can reproduce with Chromium.
`eporner.com#@#+js(addEventListener-defuser.js, click, trigger)`
fixes it on my end.

**Comment by okiehsch** [comment]
> I don't get any popups on desktop browsers so what ublock scriptlet filters achieve here???

They can easily rename their first-party script, the scriptlet will always prevent that specific script from running, so changing the name won't work.

**Comment by ghajini** [comment]
Also these 

||www.eporner.com/pop_mobile.php$important

||www.eporner.com/dotm/pop2.php$domain=www.eporner.com,important

aren't blocked on firefox android due to unknown reason(may be due to adguard mobile filters) though part of easylist.....

**Comment by dumbusernameidk** [comment]
This filter `eporner.com##+js(addEventListener-defuser, click, trigger)` causes issues on Chrome.  A lot of buttons don't work.

**Comment by mapx-** [comment]
> A lot of buttons don't work.

give us some examples

**Comment by dumbusernameidk** [comment]
For right now when you're watching a video these buttons under the player don't function.

`https://i.gyazo.com/c2e40597ff6b3258762a6627ad2af19f.png` Funny though the only button that does work is the Favorite button.

And this button doesn't work either  `https://i.gyazo.com/732805548d376457b3c738b19c055f83.png`

That's all i have for right now.

**Comment by mapx-** [comment]
Do you get popups whitelisting that filter ?
`eporner.com#@#+js(addEventListener-defuser, click, trigger)`

**Comment by mapx-** [comment]
now popup here, so I removed it

**Comment by dumbusernameidk** [comment]
yeah i couldn't find any popups.

**Comment by ghajini** [comment]
Firefox android
URL =
`https://www.eporner.com/hd-porn/XmdZxnXsW8M/Evening-By-The-Pool/`

Popups, video ad

**Comment by mapx-** [comment]
@ghajini 
this filter is working for me (video ads), give it a try
`*.xml$xhr,3p,domain=eporner.com`
