### ISSUE TITLE
ygosu.com: breakage

### ISSUE THREAD

**Issue by DavidLee3835** [uBlockOrigin/uAssets#20812]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ygosu.com/`

### Category

breakage

### Description

Website is broken when uBO is active.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/99162643/2507481d-2d96-42d0-90bd-059988424677)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 299147
 cosmetic: 43800
 scriptlet: 19107
 html: 0
listset (total-discarded, last-updated):
 removed:
  KOR-1: null
 added:
  https://o0.pages.dev/Xtra/adblock.txt: 231767-0, 4m
 default:
  user-filters: 0-0, never
  easylist: 75608-17268, 4m
  easyprivacy: 32903-16665, 4m
  plowe-0: 3718-2561, 4m
  ublock-badware: 7438-619, 4m
  ublock-filters: 35667-271, 4m
  ublock-privacy: 688-42, 4m
  ublock-quick-fixes: 169-92, 4m
  ublock-unbreak: 2154-32, 4m
  urlhaus-1: 9820-174, 4m
filterset (user): [empty]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 497 ms (selfie)
 maxAssetCacheWait: 98 ms
popupPanel:
 blocked: 8
 network:
  07c225f3.online: 4
  google.com: 2
  googletagmanager.com: 1
  vntsm.com: 1
 extended:
  ##+js(no-xhr-if, /07c225f3\.online|content-loader\.com/)
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/40990817687252b40daf4c952667f4aef56e06eb

Force update the filterlists.
