### ISSUE TITLE
mytxcastle.com: nuisance

### ISSUE THREAD

**Issue by myrajurek** [uBlockOrigin/uAssets#20819]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mytxcastle.com/`

### Category

nuisance

### Description

sign in popup still displayed with annoyance blocklists enabled

### Other extensions used

```
https://chromewebstore.google.com/detail/lazysec/llegephenamkbmnjbjpgkdakkfmgeggp
https://chromewebstore.google.com/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb
https://chromewebstore.google.com/detail/scraper/mbigbapnjcgaffohmbkdlecaccepngjd
https://chromewebstore.google.com/detail/grammarly-grammar-checker/kbfnbcaeplbcioakkpcpgfkobkghlhen
https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh
https://chromewebstore.google.com/detail/hotkeys-for-search/gfmeadbjkfhkeklgaomifcaihbhpeido
https://chromewebstore.google.com/detail/steamdb/kdbmhfkmnlmbkgbabkdealhhbfhlmmon
https://chromewebstore.google.com/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi (not active on the webpage)
https://chromewebstore.google.com/detail/quillbot-ai-writing-and-g/iidnbdjijdkbmajdffnidomddglmieko
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/80414217/a87b092d-61f9-4a70-ace8-a4f7425edadb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 116
filterset (summary):
 network: 125668
 cosmetic: 195305
 scriptlet: 30230
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28130-3623, never
  adguard-mobile-app-banners: 4793-1083, never
  adguard-other-annoyances: 13820-621, never
  adguard-popup-overlays: 26270-40, 3m
  adguard-social: 22015-1623, never
  adguard-widgets: 2346-39, never
  dpollock-0: 11584-712, never
  easylist-annoyances: 4186-125, 2m
  easylist-chat: 162-0, 2m
  easylist-newsletters: 6685-420, 3m
  easylist-notifications: 2877-198, 2m
  fanboy-cookiemonster: 48985-254, 2m
  [5 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 75532-51, 6m
  easyprivacy: 32901-169, 6m
  plowe-0: 3718-1078, 6m
  ublock-badware: 7438-137, 6m
  ublock-filters: 35667-244, 6m
  ublock-privacy: 688-7, 6m
  ublock-quick-fixes: 169-92, 6m
  ublock-unbreak: 2154-36, 6m
  urlhaus-1: 9820-0, 6m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1062 ms
 maxAssetCacheWait: 13 ms
popupPanel:
 blocked: 16
 no-cosmetic-filtering: true
 network:
  addthis.com: 1
  doubleclick.net: 1
  facebook.net: 2
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 2
  maps.googleapis.com: 1
  newrelic.com: 6
```
</details>

**Comment by mapx-** [comment]
add in "my filters"

```
mytxcastle.com###user-action-modal
mytxcastle.com##html:style(overflow: auto !important;)
```

however, to be able to log in you have to disable them.
