### ISSUE TITLE
imgur.com: Breaks if you scroll

### ISSUE THREAD

**Issue by joegreen3** [uBlockOrigin/uAssets#20820]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://imgur.com/EyD7xhk`

### Category

[unknown]

### Description

imgur.com breaks if you scroll. Page goes fully black with nothing in it

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 201111
 cosmetic: 225254
 scriptlet: 46453
 html: 0
listset (total-discarded, last-updated):
 removed:
  easyprivacy: null
  ublock-privacy: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75366-117, 2m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94952-21833, 2m
  FRA-0: 28614-77, 2m
  IRN-0: 2861-3, 2m
  adguard-generic: 80292-757, 2m
  curben-phishing: 80668-20, 2m
  easylist-annoyances: 4186-4186, 2m
  easylist-notifications: 2877-2877, 2m
  fanboy-cookiemonster: 48985-48985, 2m
  ublock-annoyances: 5893-263, 1m
  ublock-cookies-easylist: 578-578, 1m
 default:
  user-filters: 24-5, never
  easylist: 75610-1802, 2m
  plowe-0: 3718-464, 2m
  ublock-badware: 7448-339, 1m
  ublock-filters: 35703-4289, 1m
  ublock-quick-fixes: 186-73, 1m
  ublock-unbreak: 2154-85, 1m
  urlhaus-1: 9820-1, 1m
filterset (user): [array of 24 redacted]
trustedset:
 added: [array of 36 redacted]
switchRuleset:
 added: [array of 7225 redacted]
userSettings:
 advancedUserEnabled: true
 collapseBlocked: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 429 ms (selfie)
 maxAssetCacheWait: 261 ms
popupPanel:
 blocked: 24
 network:
  1rx.io: 1
  ad-delivery.net: 2
  adnxs.com: 1
  amazon-adsystem.com: 1
  assemblyexchange.com: 6
  connatix.com: 1
  d3c8j8snkzfr1n.cloudfront.net: 1
  doubleclick.net: 1
  exelator.com: 1
  facebook.net: 1
  google-analytics.com: 1
  primis.tech: 1
  sascdn.com: 2
  scorecardresearch.com: 1
  sharethrough.com: 1
  stretchsquirrel.com: 1
  yellowblue.io: 1
 extended:
  ##body:style(overflow-y: auto !important;)
  ##+js(set-constant, ADBLOCKED, false)
  ##+js(adjust-setTimeout, /function\(\)\{try\{|adBegan/, 5000, 0.…
  ##+js(set-cookie, WHITELISTED_CLOSED, 1)
```
</details>

**Comment by okiehsch** [comment]
Works fine witth a default setup.

**Comment by joegreen3** [comment]
Thank you for checking. Maybe I have broken something in settings then.

**Comment by joegreen3** [comment]
> > I have broken something in settings
> 
> Why did you tick these then?
> 
> > * [x]  I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
> 
> > * [x]  I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
> 
> > * [x]  I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.

There are settings beside the filter lists
