### ISSUE TITLE
leboncoin.fr: ads

### ISSUE THREAD

**Issue by CDL54** [uBlockOrigin/uAssets#20825]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.leboncoin.fr/voitures/2425147239.htm`

### Category

Cetelem "sponsorised" ad.

### Description

https://i.imgur.com/mTNdQJk.png

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 122385
 cosmetic: 53002
 scriptlet: 19140
 html: 1107
listset (total-discarded, last-updated):
 default:
  user-filters: 36-0, never
  ublock-filters: 36579-123, now
  ublock-badware: 7483-10, now
  ublock-privacy: 729-0, now
  ublock-unbreak: 2200-1, now
  ublock-quick-fixes: 206-2, now
  easylist: 75640-781, now
  easyprivacy: 32912-731, now
  urlhaus-1: 9790-0, now
  plowe-0: 3719-1, now
  FRA-0: 28614-412, now
filterset (user): [array of 36 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 347 ms (selfie)
 maxAssetCacheWait: 108 ms
popupPanel:
 blocked: 45
 network:
  leboncoin.fr: 3
  aticdn.net: 4
  criteo.net: 2
  doubleclick.net: 3
  googlesyndication.com: 3
  hubvisor.io: 3
  pinimg.com: 1
  privacy-center.org: 3
  realytics.io: 6
  realytics.net: 6
  sentry.io: 11
```
</details>

**Comment by mapx-** [comment]
add

    leboncoin.fr##.undefined:has-text(Sponsorisé)


to be reported at [Liste FR repository](https://github.com/easylist/listefr/issues)
@smed79
