### ISSUE TITLE
internationalsexguide.nl: popups

### ISSUE THREAD

**Issue by hj-collab** [uBlockOrigin/uAssets#20829]
Hi. I'm using uBOL on complete filter mode with the ability to read/change content on all websites. A popup appears on the below forum whenever I click on any link on the below site.

`http://www.internationalsexguide.nl/forum/`

**Comment by stephenhawk8054** [comment]
For future uBOL issues, please ask at this page: https://github.com/uBlockOrigin/uBOL-home/issues
