### ISSUE TITLE
gamespot.com [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2083]
URL(s) where the issue occurs

`https://www.gamespot.com/articles/best-buy-4k-ultra-hd-blu-ray-movie-sale-features-w/1100-6458083/`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.0

Settings

Default

**Comment by okiehsch** [comment]
You have to wait for `uBO-extra` version 2.69.
