### ISSUE TITLE
finanzasargy.com: ads

### ISSUE THREAD

**Issue by fernandojconti** [uBlockOrigin/uAssets#20838]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.finanzasargy.com/`

### Category

ads

### Description

Ads reappear after a page refresh.

### Other extensions used

It was tested also in a separate web browser with only the uBlock origin extension enabled. Firefox 120.0 64-bit.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103568
 cosmetic: 43927
 scriptlet: 19166
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 17-4, never
  easylist: 75650-16, now
  easyprivacy: 32973-64, now
  plowe-0: 3719-1082, now
  ublock-badware: 7478-137, now
  ublock-filters: 35721-159, now
  ublock-privacy: 739-8, now
  ublock-quick-fixes: 195-59, 1h.48m
  ublock-unbreak: 2151-32, now
  urlhaus-1: 9725-0, 1h.48m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 326 ms (selfie)
 maxAssetCacheWait: 115 ms
popupPanel:
 blocked: 6
 network:
  finanzasargy.com: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  vercel-insights.com: 2
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
add

    *banner$domain=finanzasargy.com
    finanzasargy.com##[target="_blank"][href*="?ref"]
    finanzasargy.com##[target="_blank"]:not([href*="whatsapp.com"]) > [src*="banner"]

@ryanbr

**Comment by fernandojconti** [comment]
Thanks. Worked fine with the highlighted green ones, but still appearing the lower ones highlighted in red.

![image](https://github.com/uBlockOrigin/uAssets/assets/65995729/13e9f66d-6537-42ed-88b4-1326b4ebf73f)

**Comment by fernandojconti** [comment]
Nevermind. It's working now. TYVM

**Comment by fernandojconti** [comment]
Nevermind. It's working now. TYVM

**Comment by mapx-** [comment]
the last one in green is self promotion (their whatsapp channel)
