### ISSUE TITLE
sportmediaset.mediaset.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#20840]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sportmediaset.mediaset.it/`
`https://www.sportmediaset.mediaset.it/video/altrisport/volandri-su-sinner-ha-alzato-il-livello-facendo-la-differenza-_73325056-202302k.shtml`
`https://www.tgcom24.mediaset.it/2023/video/negli-usa-e-il-thanksgiving-day-il-giorno-del-ringraziamento_73306754-02k.shtml`

### Category

nuisance

### Description

nuisance/cookie dialog.
You can't hide it, otherwise video doesn't start.
Ok adding `euconsent-v2` and `_iub_cs-40600793` cookies  on `mediaset.it`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1103" alt="nui1" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/b90b6750-7d60-4ee8-b661-478fbeaca687">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 208953
 cosmetic: 162649
 scriptlet: 42130
 html: 1302
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 80315-6270, 31m
  curben-phishing: 80090-28, 31m
  easylist-annoyances: 4191-95, 2m
  easylist-chat: 162-0, 2m
  fanboy-cookiemonster: 48997-283, 2m
  ublock-cookies-easylist: 574-0, 2m
  easylist-newsletters: 6685-13, 2m
  easylist-notifications: 2877-4, 2m
  fanboy-social: 16212-7, 2m
  ublock-annoyances: 5848-605, 31m
 default:
  ublock-filters: 36591-146, 31m
  ublock-badware: 7482-10, 31m
  ublock-privacy: 733-2, 31m
  ublock-unbreak: 2197-1, 31m
  ublock-quick-fixes: 206-2, 31m
  easylist: 75651-743, 31m
  easyprivacy: 32973-823, 31m
  urlhaus-1: 9725-0, 31m
  plowe-0: 3719-1, 31m
  ITA-0: 9184-21, 31m
filterset (user): [array of 471 redacted]
userSettings: [none]
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1699 ms
 maxAssetCacheWait: 1121 ms
popupPanel:
 blocked: 17
 network:
  mediaset.it: 1
  admantx.com: 1
  facebook.com: 1
  imrworldwide.com: 1
  mediamond.it: 1
  wt-eu02.net: 12
 extended:
  ###adv-gpt-masthead-skin-container1
  ##.social-media-wrapper
```
</details>

**Comment by mapx-** [comment]
@Yuki2718 

videos above are broken by [AdGuard – Cookie Notices](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=adguard-cookies)
`/cookie_solution/*`

needing:
`@@||mediaset.it/assets/html/cookie_solution/empty.html$frame,1p`

**Comment by superlex** [comment]
@mapx- 
@Yuki2718 
already reported :)
https://github.com/AdguardTeam/AdguardFilters/issues/166940

**Comment by superlex** [comment]
@mapx- 
Sometimes, not always, it doesn't go on:
https://github.com/uBlockOrigin/uAssets/assets/1375223/cb4f91a5-cd22-4eaf-8e78-ada5aaaca88e

Try to increase delay from 1000 to 2000, or try
`mediaset.it##+js(trusted-click-element, 'button#minf-privacy-open-modal-btn-id, button.iubenda-cs-close-btn')`
instead.

**Comment by superlex** [comment]
@mapx- 
Hello,
it looks it doesn't work anymore.
Cookie dialog is hidden, but not clicked, and video doesn't play.

Configuration
<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 120
filterset (summary):
 network: 181614
 cosmetic: 189265
 scriptlet: 48999
 html: 2193
listset (total-discarded, last-updated):
 added:
  adguard-generic: 84850-6681, never
  adguard-social: 23360-50, 6m
  adguard-cookies: 31333-47, 6m
  ublock-cookies-adguard: 1688-28, 6m
  adguard-popup-overlays: 27892-988, 1m
  adguard-mobile-app-banners: 5428-26, 1m
  adguard-other-annoyances: 14923-406, 1m
  adguard-widgets: 2653-14, 1m
  ublock-annoyances: 5925-172, 6m
  ITA-0: 8748-44, 6m
 default:
  user-filters: 0-0, never
  ublock-filters: 39841-126, 6m
  ublock-badware: 10757-6, 6m
  ublock-privacy: 1065-4, 6m
  ublock-unbreak: 2567-23, 6m
  ublock-quick-fixes: 203-4, 6m
  easylist: 85624-179, 6m
  easyprivacy: 53049-64, 6m
  urlhaus-1: 28790-0, 6m
  plowe-0: 3545-994, 6m
filterset (user): [empty]
userSettings:
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1217 ms
 maxAssetCacheWait: 875 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 20
 network:
  mediaset.it: 18
  googletagmanager.com: 1
  imrworldwide.com: 1
 extended:
  ##body #iubenda-cs-banner
```
</details>
