### ISSUE TITLE
info-war.gr: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#20845]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://info-war.gr/`

### Category

nuisance

### Description

Welcome prompt to donate and other similar internal popups

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![284222950-be4faeef-13ba-4a7a-a385-5e6882ea2b91](https://github.com/uBlockOrigin/uAssets/assets/101707608/1abb4c78-7a12-4579-a2e8-77084e0bf265)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 115
filterset (summary):
 network: 389924
 cosmetic: 260923
 scriptlet: 46916
 html: 1303
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 58163-6275, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 95304-1956, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://www.i-dont-care-about-cookies.eu/abp/: 25844-19, now
  adguard-generic: 80338-8051, now
  adguard-mobile: 8762-140, now
  adguard-spyware-url: 1337-88, now
  adguard-spyware: 72620-19264, now
  block-lan: 55-0, now
  curben-phishing: 79928-32, now
  adguard-social: 22031-868, now
  adguard-cookies: 28137-1669, now
  [13 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36576-571, now
  ublock-badware: 7482-10, now
  ublock-privacy: 733-4, now
  ublock-unbreak: 2197-2, now
  ublock-quick-fixes: 213-2, 2m
  easylist: 75665-31738, now
  easyprivacy: 32962-1022, now
  urlhaus-1: 9080-0, now
  plowe-0: 3719-1, now
  GRC-0: 1056-2, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10339 ms (selfie)
 maxAssetCacheWait: 5946 ms
popupPanel:
 blocked: 8
 network:
  googlesyndication.com: 5
  googletagmanager.com: 1
  onesignal.com: 2
 extended:
  ##div[class^="widget-social"]
  ##p:empty:not([class])
  ##p:-moz-only-whitespace
  ##ins.adsbygoogle
  ##.widget-social-icons
  ###mc_embed_signup
  ###mc_embed_signup_scroll
  ##.wp-block-spacer:not(html, body)
  ##.text-ad
  ##.text_ad
  ##.pub_300x250
  #@#.ad-unit
  #@#.ad_unit
```
</details>

**Comment by DimitrisKalaboukas** [comment]
Suggested generic filters:

##.sgpb-popup-dialog-main-div-wrapper
##.sgpb-popup-overlay

They block a lot of relevant annoying popups in the web.

**Comment by mapx-** [comment]
report at adguard filters repository

**Comment by DimitrisKalaboukas** [comment]
@AdamWr ?

**Comment by AdamWr** [comment]
Added to current rules - https://github.com/AdguardTeam/AdguardFilters/commit/e31815c8b0cb522f128392365cd96f2d4c38fdb4
I'm not sure about generic rules, because on some website which use these element scroll is blocked, so it will cause breakage.

**Comment by AdamWr** [comment]
Okay, I have added `political.gr` and `openbook.gr` to current rules, but I cannot reproduce it on `prescouter.com`.

**Comment by DimitrisKalaboukas** [comment]
@AdamWr If you open e.g.:

https://www.prescouter.com/2014/04/malware-infection-rate-for-android-devices-measured-by-researchers/

and stay patient for at least 30 seconds, it will pop-up.

**Comment by krystian3w** [comment]
Still without pop-up.

**Comment by DimitrisKalaboukas** [comment]
@AdamWr Very strange, it may be geo-dependent.
