### ISSUE TITLE
9anime.is openload videos [Anti-adblock]

### ISSUE THREAD

**Issue by zaphodbeebblebrox** [uBlockOrigin/uAssets#2084]
### URL(s) where the issue occurs

`https://www4.9anime.is/watch/yu-gi-oh-vrains.r8mp/wy7nmo`

### Describe the issue

Videos from openload on 9anime have anti-adblock.

### Settings

Default settings

**Comment by SMed79** [comment]
Be sure your filter lists are up to date.

**Comment by okiehsch** [comment]
The waiting part should be fixed by https://github.com/uBlockOrigin/uAssets/commit/b035d8bc0e7af5848e0e82c062c412b164fd33ba

**Comment by KiLL4FuNK** [comment]
ads

**Comment by smed79** [comment]
https://github.com/easylist/easylist/commit/fe7615a55dfa8882e07060c915831a84fc41105d
