### ISSUE TITLE
crypto.news: ads

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#20842]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://crypto.news/`

### Category

ads

### Description

There is an ad banner at the bottom of the site.

This filter seems to work to remove the ad banner.
`||cryptoecom.care$xhr,3p`

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screen Shot 2023-11-23 at 10 02 23 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/f6c2e8b5-eb01-41d7-b3a8-031c836edd68">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103230
 cosmetic: 45466
 scriptlet: 23232
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5892-9, 1m
 default:
  user-filters: 60-4, never
  easylist: 75651-16, 1m
  easyprivacy: 32973-64, 1m
  plowe-0: 3719-1082, 1m
  ublock-badware: 7478-137, 1m
  ublock-filters: 35706-155, 1m
  ublock-privacy: 739-8, 1m
  ublock-quick-fixes: 213-79, 1m
  ublock-unbreak: 2151-33, 1m
  urlhaus-1: 9080-0, 1m
filterset (user): [array of 59 redacted]
trustedset:
 added: [array of 21 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 335 ms
 maxAssetCacheWait: 161 ms
popupPanel:
 blocked: 2
 network:
  cloudflareinsights.com: 1
  googletagmanager.com: 1
 extended:
  ##.b6470de94dc
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
report at easylist repository

@ryanbr
