### ISSUE TITLE
warcraftrumbledeck.com: ads

### ISSUE THREAD

**Issue by NickSakadakis** [uBlockOrigin/uAssets#20857]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://warcraftrumbledeck.com`

### Category

ads

### Description

The website manages to slip ads through the extension, i tried using various Ublock origin tools to target them specifically, such as:
Element zapper: the ads kept loading after reloading the page

Element Picker: Targeting one ad's div, broke the css style of the entire page, targeting the ad itself did nothing because the ads were being loaded by a script that seemingly randomized their id and class

Customer filters: for an add with <div id="divFLRARight" , custom filter 1: warcraftrumbledeck.com##[id="divFLRARight"] or custom filter 2: warcraftrumbledeck.com###divFLRARight, seem to break the entire page's css

### Other extensions used

Adblock Plus - free ad blocker 3.21
BetterTTV 7.5.10
GoFullPage - Full Page Screen Capture 7.12
I still don't care about cookies 1.1.1
Kaspersky Protection 2.6.68.0
MEGA 5.6.3
Pop up blocker for Chrome™ - Poper Blocker 6.6.3
Privacy Badger 2023.10.31
uBlock Origin 1.53.0

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103317
 cosmetic: 43915
 scriptlet: 19267
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 75685-16, 14m
  easyprivacy: 32965-64, 14m
  plowe-0: 3718-1082, 14m
  ublock-badware: 7478-137, 14m
  ublock-filters: 35724-157, 14m
  ublock-privacy: 841-11, 14m
  ublock-quick-fixes: 204-81, 14m
  ublock-unbreak: 2152-32, 14m
  urlhaus-1: 9455-0, 14m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  chrome-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 757 ms (selfie)
 maxAssetCacheWait: 104 ms
popupPanel:
 blocked: 10
 network:
  connatix.com: 2
  criteo.net: 1
  googlesyndication.com: 3
  googletagmanager.com: 3
  nitropay.com: 1
```
</details>

**Comment by krystian3w** [comment]
You can try use `:remove()` for these ad reinsertion:

```adb
warcraftrumbledeck.com###divFLRARight:remove()
```

As long app detect zapping as problem.

**Comment by krystian3w** [comment]
Possible same familly: #20854

**Comment by BlazeFTL** [comment]
```
||css-load.com^$xhr,redirect-rule=nooptext,domain=warcraftrumbledeck.com
||css-load.com^$xhr,domain=warcraftrumbledeck.com

**Comment by NickSakadakis** [comment]
> You can try use `:remove()` for these ad reinsertion:
> 
> ```
> warcraftrumbledeck.com##:is(#divFLRARight, #divFLRALeft) [id]:remove()
> ```
> 
> As long app detect zapping as problem.
> 
> IDK how hide in center.

this worked beautifully for the side ads, is there a contains() function that could remove elements with id or class that have "jizsl_" in them?

**Comment by NickSakadakis** [comment]
> ||css-load.com^$xhr,redirect-rule=nooptext,domain=warcraftrumbledeck.com
> ||css-load.com^$xhr,domain=warcraftrumbledeck.com

inputing those lines in my filters still made the page's css break, if it worked for you what am i doing wrong?

**Comment by BlazeFTL** [comment]
Remove All Rules And Add Only This
```
||css-load.com^$xhr,urltransform=/.js/lol.js/

**Comment by BlazeFTL** [comment]
> inputing those lines in my filters still made the page's css break, if it worked for you what am i doing wrong?

It Seems Like Random Issue..Sometime Works Sometime Doesn't

**Comment by BlazeFTL** [comment]
```adblock-filter-list
Kaka
```

**Comment by NickSakadakis** [comment]
> ||css-load.com^$xhr,urltransform=/.js/lol.js/

error says "invalid filter: filter requires trusted source

**Comment by BlazeFTL** [comment]
Goto Settings> I am an advanced user > trustedListPrefixes > Add = `ublock- user-`

**Comment by NickSakadakis** [comment]
for the top-middle ad i managed to craft these 2 filters
warcraftrumbledeck.com##iframe[title*="3rd party ad content"]
warcraftrumbledeck.com#?#span:-abp-contains(jizsl_)

first one blocks an iframe in which the ad is placed, but once that is detected it loads the ad in a different way so filter 2 comes in and blocks it.

Only issue is that once the ad reinsertion scripts detect the removal, they try activate again, and now the page has ads poping in and out of existence every few seconds

**Comment by NickSakadakis** [comment]
> ||css-load.com^$xhr,urltransform=/.js/lol.js/

it still breaks the site, it seems there is no way out of it

**Comment by mapx-** [comment]
Install microShield (in tampermonkey or violentmonkey)
https://github.com/List-KR/microShield#how-to-install

**Comment by BlazeFTL** [comment]
> it still breaks the site
I Used The Site For A While I Didnt Get Any Problems...
Did You Really Removed All The Previous Filters ? From Krystian Too...

**Comment by mapx-** [comment]
fixed

**Comment by NickSakadakis** [comment]
> honkailab.com,warcraftrumbledeck.com##+js(aost, Promise, computed,  log, 1)
> honkailab.com,warcraftrumbledeck.com##[href^="https://info.error-report.com/"]

i noticed problems with ads in this site the same day i opened this issue, i had been using it Almost everyday before and it was fine.

i commented every other custom filter in "My Filters" i even tried deleting the commented filters entirely so that only that filter existed by itself, still broke even after hard refreshes

**Comment by NickSakadakis** [comment]
> > it still breaks the site
> 
> I Used The Site For A While I Didnt Get Any Problems... Did You Really Removed All The Previous Filters ? From Krystian Too... Even If There Is Breakage Just Reload The Website

i noticed problems with ads in this site the same day i opened this issue, i had been using it Almost everyday before and it was fine.

i commented every other custom filter in "My Filters" i even tried deleting the commented filters entirely so that only that filter existed by itself, still broke even after hard refreshes

**Comment by NickSakadakis** [comment]
> does below filters works & any breakges?
> 
> firefox =>
> 
> `honkailab.com,warcraftrumbledeck.com##+js(aost, Promise, injectedScript, log, 1)`
> 
> chromium=>
> 
> ```
> honkailab.com,warcraftrumbledeck.com##+js(aost, Promise, computed,  log, 1)
> honkailab.com,warcraftrumbledeck.com##[href^="https://info.error-report.com/"]
> ```

your chromium filtesrs Just Work, i dont uinderstand why or how, but they do, cleanly too. thank you very much <3

**Comment by JobcenterTycoon** [comment]
@BlazeFTL if you want to add the filter just fire a pull  but note it will be likely patched withing 1-2 days.

**Comment by BlazeFTL** [comment]
> if you want to add the filter

It's Upto You Bro..I Will Not Touch It
