### ISSUE TITLE
wrosinski.pl: nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#20855]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.wrosinski.pl/kaszaki/`

### Description

Anti right click or long press touch screen at mobile in `alert()`.

I doubt that there has been a revolution in Polish law so that this could be included in Polish public lists such as "Polish Annoyance Filters".

As we are no longer accepting such submissions I will not repost this to projects:
- AG other Annoyances or 
- Fanboy Annoyances.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/35370833/ee2c5f4a-235e-496b-b41d-10663aebd742)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
Config:
 Stock lists
Added:
 uBo Annoyances
 POL-0
 POL-2
Env:
 uBo 1.54.1b0
 Firefox 120 at Windows 11
```
</details>

**Comment by peace2000** [comment]
Fixed

**Comment by krystian3w** [comment]
In bad file, these for annoyances.txt (sic!).

**Comment by peace2000** [comment]
Moved to the correct file
