### ISSUE TITLE
pepper.*: privacy/nuisance

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#20859]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.pepper.pl/promocje/ssd-crucial-x9-750379`

### Description

Bad tracking links in comments/description, sometimes strict blocked so users must skip opening or manually goes to next/final destination.

Demo to improve:

```adb
! genesis
pepper.pl##+js(href-sanitizer, a[href*="https://www.pepper.pl/visit/"][title^="http"], [title])
```

I don't think so worth for Fanboy Annoyances or AdGuard other Annoyances (AdGuard Team still don't forked scriptlet, so server compiler can remove from file these with uBo syntax).

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

```html
<a href="https://www.pepper.pl/visit/threaddesc/750379/1190585"
 target="_blank" class="link" rel="nofollow noopener"
 title="https://www.tomshardware.com/reviews/crucial-x10-pro">recenzji Tom's Hardware</a>
```

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
Config:
 Stock
Added:
 uBo Annoyances
 POL-0
 POL-2
Env:
 uBo 1.54.1b0
 Firefox 120 at Windows 11
```
</details>

**Comment by mapx-** [comment]
@krystian3w could you craft a PR for privacy list ?

**Comment by krystian3w** [comment]
No, I don't feel up to looking for how on foreign languages it is done.
