### ISSUE TITLE
[nsfw] bullchat.com: ads

### ISSUE THREAD

**Issue by bbreddevil69** [uBlockOrigin/uAssets#20856]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bullchat.com/desk/index.html?auth=1746557b-0cd3-432b-8fce-e6a8e64ced35`

### Category

ads

### Description

I keep having to use the element zapper tool to remove ads manually, and have to again every time I log in the site. It also disables functionality of parts of the site when I zap all the ads away making it unusable

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 103317
 cosmetic: 43909
 scriptlet: 19267
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75685-16, now
  easyprivacy: 32965-64, now
  plowe-0: 3718-1082, now
  ublock-badware: 7478-137, 1h.54m
  ublock-filters: 35722-157, 1h.54m
  ublock-privacy: 841-11, now
  ublock-quick-fixes: 204-81, 1h.54m
  ublock-unbreak: 2151-32, 1h.54m
  urlhaus-1: 9455-0, now
filterset (user): [empty]
trustedset:
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5216 ms (selfie)
 maxAssetCacheWait: 1153 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
test

`||bullchat.com/sponsor/`

@ryanbr

**Comment by bbreddevil69** [comment]
I don't understand how this works. What was done? Because there are still all the ads on that site

**Comment by bbreddevil69** [comment]
what easy list? What is all this nonsense any way? Why can't I just report a problem and it gets fixed? Just like adblock does. This isn't user friendly. Maybe I made a mistake switching from adblock to this, though adblock can't block ads on X. Anyone know an ad blocker that actually works without all this nonsense needed to be done?

**Comment by stephenhawk8054** [comment]
It was fixed already: https://github.com/easylist/easylist/commit/c9f8df76d98afe81cac307331c5ecb2830a07461

The list would need to a few days to auto-update. If you want to get the fix manually right now, click uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > ["Filter lists" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists) > &#128344; [Purge all caches](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) > 🔃 [Update now](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now)

**Comment by bbreddevil69** [comment]
then why am I still seeing ads on the site if it was fixed?

**Comment by stephenhawk8054** [comment]
@bbreddevil69 Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by bbreddevil69** [comment]
I wasn't aware it would take days for fix to work or otherwise have to update it myself. Would have been useful if this was mentioned somewhere when reporting an issue. It works now thanks
