### ISSUE TITLE
viki.com detection

### ISSUE THREAD

**Issue by brubsby** [uBlockOrigin/uAssets#20853]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.viki.com/videos/1231728v`

### Description

"Disable adblock" banner showing up again just today, likely filters need to be updated

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/57653502/104e62fe-ee4d-45f6-9377-08caa8f0a8b4)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103677
 cosmetic: 43910
 scriptlet: 19267
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 75685-16, now
  easyprivacy: 32965-64, now
  plowe-0: 3718-1082, now
  ublock-badware: 7478-137, now
  ublock-filters: 35721-157, now
  ublock-privacy: 841-11, now
  ublock-quick-fixes: 204-81, now
  ublock-unbreak: 2152-32, now
  urlhaus-1: 9815-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 45 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 339 ms (selfie)
 maxAssetCacheWait: 154 ms
popupPanel:
 blocked: 46
 network:
  appsflyer.com: 1
  browser-intake-datadoghq.com: 36
  googlesyndication.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  litix.io: 1
  viki.io: 5
 extended:
  ##+js(set-constant, VikiPlayer.prototype.pingAbFactor, noopFunc)
  ##+js(set-constant, player.options.disableAds, true)

```
</details>

**Comment by mapx-** [comment]
I'm able to reproduce the issue only in edge.
@brubsby what browser are you using ?

**Comment by brubsby** [comment]
For the record:
Chrome Version 119.0.6045.160 (Official Build) (64-bit)

However, your inability to reproduce made me realize I hadn't applied the changes to disable the extra filters, so it didn't fix it. It seems like at least EasyList is causing the popup, as when I disable all of them, it goes away.

Thanks for the assist!
