### ISSUE TITLE
honkailab.com: ads

### ISSUE THREAD

**Issue by myurei** [uBlockOrigin/uAssets#20854]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://honkailab.com/`

### Category

ads

### Description

Showing what seems to be 98% of ads. The only other blocking extensions I have are for YouTube, which are not active on this domain.

### Other extensions used

![KbzotW](https://github.com/uBlockOrigin/uAssets/assets/151973406/385bd0e4-f921-4ff3-a2d6-561be699cb17)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![mBKx1q](https://github.com/uBlockOrigin/uAssets/assets/151973406/52cec2c9-d7f1-4a9f-8ebb-d8cdd6792dc1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 103653
 cosmetic: 43911
 scriptlet: 19267
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75665-16, 23m
  easyprivacy: 32964-64, 23m
  plowe-0: 3718-1082, 23m
  ublock-badware: 7478-137, 23m
  ublock-filters: 35721-157, 23m
  ublock-privacy: 841-11, 23m
  ublock-quick-fixes: 204-81, 22m
  ublock-unbreak: 2151-32, 22m
  urlhaus-1: 9815-0, 22m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 16040 ms (selfie)
 maxAssetCacheWait: 115 ms
popupPanel:
 blocked: 5
 network:
  2mdn.net: 1
  creativecdn.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##[data-freestar-ad]
```
</details>

**Comment by krystian3w** [comment]
Same at Firefox 120.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20857

**Comment by BlazeFTL** [comment]
Should Fix 
```
honkailab.com##+js(rmnt, script, advanced_ads_ready)
||css-load.com^$xhr,domain=honkailab.com
||css-load.com^$xhr,redirect-rule=noop.txt,domain=honkailab.com

**Comment by BlazeFTL** [comment]
Should Fix 🐸🤣
`||css-load.com^$xhr,urltransform=/.js/lol.js/`

**Comment by mapx-** [comment]
Install microShield (in tampermonkey or violentmonkey)
https://github.com/List-KR/microShield#how-to-install

**Comment by mapx-** [comment]
fixed

**Comment by Flandre5carlet** [comment]
> fixed

I think the issue has either returned or not been fixed, the domain still displays even after clearing all caches and force updating filters.

**Comment by krystian3w** [comment]
If the site doesn't support Korean, I'd fix it as standard.
