### ISSUE TITLE
5.253.86.213: detection

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uAssets#20864]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://5.253.86.213/`

### Category

detection

### Description

Adblock detection 

### Other extensions used

Dark reader,google search fixer 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 120
filterset (summary):
 network: 115185
 cosmetic: 144621
 scriptlet: 28516
 html: 1307
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 10488-0, now
  adguard-spyware-url: 1338-94, now
  adguard-social: 22041-170, now
  adguard-cookies: 28147-46, now
  ublock-cookies-adguard: 615-0, now
  adguard-popup-overlays: 26306-973, now
  adguard-mobile-app-banners: 4805-14, now
  adguard-other-annoyances: 13826-88, now
  adguard-widgets: 2349-1, now
  ublock-annoyances: 5912-633, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36938-617, now
  ublock-badware: 7476-10, now
  ublock-privacy: 841-4, now
  ublock-unbreak: 2205-3, now
  ublock-quick-fixes: 207-2, now
  adguard-mobile: 8765-111, now
  easylist: 75699-810, now
  easyprivacy: 32968-746, now
  urlhaus-1: 9455-0, now
  plowe-0: 3720-1, now
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 722 ms (selfie)
 maxAssetCacheWait: 259 ms
popupPanel:
 blocked: 7
 network:
  getbutton.io: 1
  googlesyndication.com: 2
  histats.com: 3
  qgxbluhsgad.com: 1
 extended:
  ##img[alt="totobet" i]
  ##[href*="://bl88.xyz/"]
  ##[href*="://dewatks.biz/"]
  ##[href*="://n303.club/"]
  ##a[href^="https://t.me/share/url?"]
  ##a[href^="https://api.whatsapp.com/send?text="]
  ##a[onclick*="//www.facebook.com/"][onclick*="sharer.php"]
  ##a[onclick*="https://www.facebook.com/sharer/"]
  ##.share-facebook
  ##.share-twitter
  ##.idmuvi-topbanner-aftermenu
  ##.idmuvi-floatbanner
  ##.idmuvi-floatbanner-footer
  ###idmuvi-popup
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
```
</details>

**Comment by mapx-** [comment]
Are you sure it will be fixed in ABPIndo ?

**Comment by krystian3w** [comment]
https://github.com/realodix/AdBlockID/issues/1627
