### ISSUE TITLE
player.pl: detection

### ISSUE THREAD

**Issue by swiezaczek** [uBlockOrigin/uAssets#20863]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://player.pl/seriale-online/skazana-odcinki,31908/odcinek-3,S03E03,261399`

### Category

detection

### Description

ublock detected

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.5rc13
Chromium: 119
filterset (summary):
 network: 104735
 cosmetic: 51504
 scriptlet: 19482
 html: 0
listset (total-discarded, last-updated):
 added:
  POL-0: 8011-46, never
  POL-2: 1280-47, never
 default:
  user-filters: 0-0, never
  easylist: 75698-16, now
  easyprivacy: 32968-64, now
  plowe-0: 3719-1082, now
  ublock-badware: 7478-137, now
  ublock-filters: 35736-157, now
  ublock-privacy: 841-11, now
  ublock-quick-fixes: 205-81, now
  ublock-unbreak: 2153-33, now
  urlhaus-1: 9455-0, now
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4404 ms
 maxAssetCacheWait: 16 ms
popupPanel:
 blocked: 18
 network:
  adocean.pl: 4
  doubleclick.net: 1
  gemius.pl: 7
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  imrworldwide.com: 1
  litix.io: 1
  newrelic.com: 1
 extended:
  ##+js(json-prune, movie.advertising.ad_server playlist.movie.adv…
```
</details>

**Comment by swiezaczek** [comment]
why closed?

**Comment by mapx-** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/393db2c3-1332-453a-b879-f788ea8e0293)

I added a fix / commit, wait 5-10 min then update all the filter lists
