### ISSUE TITLE
bing.com: ads

### ISSUE THREAD

**Issue by Damian-11** [uBlockOrigin/uAssets#20867]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.bing.com/`

### Description

Sponsored results appear at the top and side of the search results page when searching for certain terms.

### Other extensions used

- Bing video helper
- Bitwarden
- Dark Reader
- FastForward
- Cookie-Editor
- I still don't care about cookies
- Wayback Machine
- Save to Google Drive
- MyJDownloader Browser Extension

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/73187621/f178a580-3e9a-4070-ac7e-76ddc9e74877)
![image](https://github.com/uBlockOrigin/uAssets/assets/73187621/dff7d544-b50f-42fc-8936-414263724217)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 121
filterset (summary):
 network: 103347
 cosmetic: 43898
 scriptlet: 19260
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75651-16, 1d.37m
  easyprivacy: 32907-64, 2d.22h.2m
  plowe-0: 3716-1077, 7d.1h.51m
  ublock-badware: 7478-137, 1d.37m
  ublock-filters: 35707-155, 1d.37m
  ublock-privacy: 841-9, 40m
  ublock-quick-fixes: 204-79, 40m
  ublock-unbreak: 2151-32, 1d.37m
  urlhaus-1: 9565-0, 36m
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 986 ms
 maxAssetCacheWait: 261 ms
popupPanel:
 blocked: 120
 network:
  bing.com: 120
 extended:
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
```
</details>

**Comment by mapx-** [comment]
Are you using edge browser ?

**Comment by Damian-11** [comment]
Yes, I'm using Edge

**Comment by mapx-** [comment]
Nothing to do for edge (microsoft ads are not blockable)

**Comment by dportvine** [comment]
Can it be hidden with this https://github.com/gorhill/uBlock/commit/52b46eb98bedfa746206e89ac016734cbbed092a?

<details>
<summary>Screen</summary>

![2024-04-01_170646](https://github.com/uBlockOrigin/uAssets/assets/111344219/feb2ee95-325e-43b8-86a5-9f2f58bbb259)
</details>

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 140392
 cosmetic: 116295
 scriptlet: 27797
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25299-46, 21m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1697-7, 21m
  adguard-cookies: 29091-243, 3d.2h.55m
  ublock-annoyances: 6934-46, 21m Δ
 default:
  user-filters: 1-0, never
  ublock-filters: 37511-106, 21m Δ
  ublock-badware: 8093-15, 21m Δ
  ublock-privacy: 781-0, 21m Δ
  ublock-unbreak: 2238-7, 21m Δ
  ublock-quick-fixes: 184-0, 21m
  easylist: 84522-432, 21m Δ
  easyprivacy: 50423-500, 21m Δ
  RUS-0: 39441-238, 21m Δ
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 252 ms (selfie)
 maxAssetCacheWait: 103 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  bing.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
@dportvine Does this work for you?

```adb
||assets.msn.com/service/news/feed/pages/binghp?$xhr,removeparam=wpopageid,domain=www.bing.com
```

**Comment by dportvine** [comment]
> Does this work for you?
> 
> ```
> ||assets.msn.com/service/news/feed/pages/binghp?$xhr,3p,removeparam=wpopageid,domain=www.bing.com
> ```

Yes it works for me.

**Comment by WhyteReal** [comment]
> ||assets.msn.com/service/news/feed/pages/binghp?$xhr,3p,removeparam=wpopageid,domain=www.bing.com

I had three ads before applying this fix, now I’m down to one, but still…

**Comment by stephenhawk8054** [comment]
Please give exact link and describe the steps to reproduce in details with screenshots.

**Comment by WhyteReal** [comment]
> Please give exact link and describe the steps to reproduce in details with screenshots.

<img width="2558" height="1263" alt="Image" src="https://github.com/user-attachments/assets/de3712e8-7858-45a8-8a1d-67501a9d4e99" />




https://www.bing.com/search?pglt=129&FORM=U523MF&PC=U523&q=sedia+girevole&FORM=ANNTA1&adppc=EDGEESS


A simple search on the Edge browser in Windows 11 started from the home page with the query "sedia girevole." The first three results were ads, followed by the relevant search results below.


Edit: After about a minute without doing anything, searching for the exact same thing both by link and through the search bar didn’t show ads, so I guess it’s random?
