### ISSUE TITLE
sinnerclownceviri.com: detection

### ISSUE THREAD

**Issue by yuhanchn01** [uBlockOrigin/uAssets#20860]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [ ] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sinnerclownceviri.com/konu/the-last-faith-tuerkce-yama-yayinlandi-emre.4952/`

### Category

detection

### Description

They do not show the Adblock warning to guest users. You need an account to reproduce.
Use this temporary account for testing:

```
username - erayaltintas
password - hy78*x?254Yh8h<!
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/151660568/63d0f59b-08dd-427a-9f7a-3e4bf043b648)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 104960
 cosmetic: 54405
 scriptlet: 20708
 html: 1112
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36603-246, 1m
  ublock-badware: 7482-10, 1m
  ublock-privacy: 835-4, 1m
  ublock-unbreak: 2197-1, 1m
  ublock-quick-fixes: 204-2, 1m
  easylist: 75685-613, 1m
  easyprivacy: 32973-739, now
  urlhaus-1: 9455-0, now
  plowe-0: 3718-1, now
  TUR-0: 13809-12, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2677 ms
 maxAssetCacheWait: 39 ms
popupPanel:
 blocked: 3
 network:
  google.com: 1
  googlesyndication.com: 2
 extended:
  ##.reklam
  ##ins.adsbygoogle
```
</details>

**Comment by yuhanchn01** [comment]
this is a new account
```
username - erayaltintas
password - hy78*x?254Yh8h<!
```

> > Your account has been rejected.

**Comment by yuhanchn01** [comment]
> > Your account has been rejected.

this is a new account

```
username - erayaltintas
password - hy78*x?254Yh8h<!
```

**Comment by Yuki2718** [comment]
Which rules cause detection? For AG fix on platforms not supporting scriptlet is also required.

**Comment by Yuki2718** [comment]
I only get `Hata! Bazı sorunlarla karşılaştık.`

> Mistake! We encountered some problems....

**Comment by Yuki2718** [comment]
@ItsProfessional Please tell me if `$generichide` can be replaced by individual exception rules.

**Comment by Yuki2718** [comment]
I don't see `###reklam_alani` in EL or AG Turkish.
