### ISSUE TITLE
Downloadmanager at computerbild.de

### ISSUE THREAD

**Issue by stonecrusher** [uBlockOrigin/uAssets#2086]
#645 needs to be updated.

No deeplink. Links require one click on download button:
# Example with downloadmanager
`http://www.computerbild.de/download/PDF24-Creator-423517.html`
![screenshot 123](https://user-images.githubusercontent.com/1388389/39261988-6aebe5f0-48be-11e8-9ed1-3a24b56af15e.png)

# Example without downloadmanager
`http://www.computerbild.de/download/Smart-Defrag-4391414.html`
![screenshot 124](https://user-images.githubusercontent.com/1388389/39261994-6e3602d6-48be-11e8-90d9-9e8d2579ded6.png)

# Issue
In the example without downloadmanager the button currently gets mistakenly removed because they changed something.

# Proposal
Replace the old rule
`computerbild.de##.startdownload:has(a[data-downloader-url$="_CB-DL-Manager.exe"])`
by
`computerbild.de##.startdownload > a[data-is-manager-usable="1"]`

p.s.: Should I have posted in the old issue? Couldn't find rules regarding that. Some handle it like "one issue per site".

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/116b70a57d9488b80899069e0368f2dc5cb5f331

Thanks for investigating and considering that it is the same issue with the same site it would probably be better to just use the original issue.
