### ISSUE TITLE
[nsfw] kimchi.tv: breakage

### ISSUE THREAD

**Issue by kripparian** [uBlockOrigin/uAssets#20862]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kimchi.tv/172062/%EC%B5%9C%EC%B4%88%EA%B3%B5%EA%B0%9C-%EA%B9%80x%EC%97%B0-full-%EC%9D%B8%EC%BD%94%EB%94%A9-%ED%95%A9%EB%B3%B8-1/`

### Category

breakage

### Description

Video player stuck loading after clicking close & play

### Other extensions used

Dark reader
Sponsorblock
Youtube high definition

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 122
filterset (summary):
 network: 157048
 cosmetic: 28262
 scriptlet: 19751
 html: 1113
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  adguard-mobile: null
  plowe-0: null
 added:
  adguard-spyware-url: 1338-88, 2m
  adguard-spyware: 72730-16742, 2m
 default:
  ublock-filters: 36932-336, now
  ublock-badware: 7476-10, 2m
  ublock-privacy: 835-5, 2m
  ublock-unbreak: 2203-3, 2m
  ublock-quick-fixes: 204-2, now
  easylist: 75698-16359, 2m
  easyprivacy: 32968-26, 7m
  urlhaus-1: 9455-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1510 ms (selfie)
 maxAssetCacheWait: 99 ms
popupPanel:
 blocked: 13
 network:
  fvcwqkkqmuv.com: 1
  googletagmanager.com: 1
  magsrv.com: 10
  pemsrv.com: 1
```
</details>

**Comment by BlazeFTL** [comment]
Video Plays Fine On My End... Reset And Use Default List Only
`kimchi.tv###player-advertising-mobile` Is All I Need

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
