### ISSUE TITLE
fontyukle.net: detection

### ISSUE THREAD

**Issue by yuhanchn01** [uBlockOrigin/uAssets#20878]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fontyukle.net/font/Arezzo-Rounded-Demi`

### Category

detection

### Description

-

### Other extensions used

Bitwarden
Simple Translate

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![resim](https://github.com/uBlockOrigin/uAssets/assets/151660568/81f0c604-531c-4604-a7d6-9a6f99fc8bfb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 105105
 cosmetic: 54423
 scriptlet: 20718
 html: 1113
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36625-220, now
  ublock-badware: 7498-10, now
  ublock-privacy: 860-4, now
  ublock-unbreak: 2200-2, now
  ublock-quick-fixes: 171-2, now
  easylist: 75699-571, now
  easyprivacy: 32962-782, now
  urlhaus-1: 9565-0, now
  plowe-0: 3720-1, now
  TUR-0: 13811-12, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2233 ms
 maxAssetCacheWait: 69 ms
popupPanel:
 blocked: 5
 network:
  google.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
  smartlook.com: 1
 extended:
  ##+js(no-setInterval-if, visibility, 1000)
  ##+js(no-setTimeout-if, innerHTML.replace, 1000)
```
</details>

**Comment by huyszn** [comment]
I get the detection when I have the Adguard Turkish Filter enabled.

**Comment by punisher018** [comment]
Detection again
