### ISSUE TITLE
soft98.ir: breakage

### ISSUE THREAD

**Issue by Soheil777** [uBlockOrigin/uAssets#20877]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://soft98.ir/security/firewall/14349-windows-firewall-control-3.html`

### Category

breakage

### Description

detect i have ad blocker and dont show content and want turn off ad blocker

### Other extensions used

WOT, Lastpass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 108
filterset (summary):
 network: 103472
 cosmetic: 43931
 scriptlet: 19276
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 75699-16, now
  easyprivacy: 32962-64, now
  plowe-0: 3720-1082, now
  ublock-badware: 7494-137, 1h.32m
  ublock-filters: 35747-157, 1h.32m
  ublock-privacy: 866-11, 1h.32m
  ublock-quick-fixes: 171-55, 1h.32m
  ublock-unbreak: 2154-33, 1h.32m
  urlhaus-1: 9565-0, 1h.56m
filterset (user): [array of 2 redacted]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 18165 ms (selfie)
 maxAssetCacheWait: 727 ms
popupPanel:
 blocked: 3
 network:
  soft98.ir: 1
  googletagmanager.com: 1
  kaprila.com: 1
 extended:
  ##+js(addEventListener-defuser, click, [native code])
  ##+js(close-window, /link-)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14480
