### ISSUE TITLE
linkvertise.com : nuisance

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#20872]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://linkvertise.com/984770/udemy-premium-cookies?o=sharing`

### Description

these screens are back
https://github.com/uBlockOrigin/uAssets/assets/139833732/2cc9adce-0c6c-47d1-84be-9dd03fa4a47f

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by krystian3w** [comment]
Check in Firefox instead in Lemur/Kiwi/Yandex (this not looks as Firefox or his fork - too fancy).

**Comment by mapx-** [comment]
Where are your details ? (`Troubleshooting Information`)

**Comment by krystian3w** [comment]
At PC maybe EL can add:

`linkvertise.com#?#.more-component__container--item:-abp-has(.lv-chip__text:-abp-contains(Advert))`

I don't see idea with CSS4.

**Comment by BlazeFTL** [comment]
Add In My Filters
```
linkvertise.com##+js(json-prune, data.getDetailPageContent.linkCustomAdOffers)
linkvertise.com##+js(json-prune, data.getTaboolaAds.*)

**Comment by Fatcavill** [comment]
works thank you very much😀

**Comment by Fatcavill** [comment]
There is a lot of ads in the page too

**Comment by BlazeFTL** [comment]
It Would Be Addressed In Ubo..Use In My Filters
```
linkvertise.com##.ng-star-inserted.more-component, .ng-star-inserted.action-box__content-wrapper, #search_input, .adstep--container__content-wrapper, .ng-star-inserted.adStepDetail__wrapper, .lv-orange.lv-button-size-mobile.lv-button-size-desktop.lv-button-component.buttonWrapper__button, .footer

**Comment by krystian3w** [comment]
Scriptlets works bad at PC.
