### ISSUE TITLE
[nsfw] pornleaks.in: detection

### ISSUE THREAD

**Issue by helbetmathias** [uBlockOrigin/uAssets#20870]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pornleaks.in/packs.php`

### Category

detection

### Description

So after you load the page and scroll a little down ublock gets detected and gives a pop up like on yt

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Link because NSFW: https://ibb.co/3kGDjGC

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 103455
 cosmetic: 43928
 scriptlet: 19264
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75699-16, now
  easyprivacy: 32962-64, now
  plowe-0: 3720-1082, now
  ublock-badware: 7478-137, now
  ublock-filters: 35744-157, now
  ublock-privacy: 855-11, now
  ublock-quick-fixes: 171-55, now
  ublock-unbreak: 2154-33, now
  urlhaus-1: 9565-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 241 ms (selfie)
 maxAssetCacheWait: 96 ms
popupPanel:
 blocked: 12
 network:
  pornleaks.in: 1
  cdn4ads.com: 1
  cloudflareinsights.com: 1
  d3g5ovfngjw9bw.cloudfront.net: 1
  fvcwqkkqmuv.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  grantedpigsunborn.com: 2
  makethebusiness.com: 1
  qrofhituzsk.com: 1
 extended:
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  #@#.Ad-Container
  #@#.sidebar-ad
  #@#.ad-slot
  #@#.ad-placeholder
  ##+js(no-setTimeout-if, onDetected)
  ##+js(remove-node-text, script, navigator.brave)
```
</details>

**Comment by BlazeFTL** [comment]
```adblock-filter-list
pornleaks.in##+js(noeval-if, /chp_?ad/)
```

**Comment by helbetmathias** [comment]
What to do with that code?

**Comment by mapx-** [comment]
wait 5-10 min then update the filter lists
