### ISSUE TITLE
bilibili.com: breakage

### ISSUE THREAD

**Issue by Xbaishu** [uBlockOrigin/uAssets#20871]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [x] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The content within the 'biliMainHeader' element on the Bilibili website is being blocked unexpectedly. I kindly request a fix for this issue in the next version. The root cause of this problem is currently unknown.I am aware that the problem lies within the filter.

### A specific URL where the issue occurs.

`https://www.bilibili.com/`

### Steps to Reproduce

https://github.com/uBlockOrigin/uBlock-issues/assets/87755186/d94115f4-f8d7-49ec-92dc-07808ca4edab
This is a screenshot of the page taken when the filter is enabled

Below is a screenshot after turning off the filter.
https://github.com/uBlockOrigin/uBlock-issues/assets/87755186/b5da6b02-def4-427e-a87d-18ff0b734a5a

### Expected behavior

https://github.com/uBlockOrigin/uBlock-issues/assets/87755186/b5da6b02-def4-427e-a87d-18ff0b734a5a

### Actual behavior

https://github.com/uBlockOrigin/uBlock-issues/assets/87755186/d94115f4-f8d7-49ec-92dc-07808ca4edab

### uBO version

1.54.0

### Browser name and version

Edge 117.0.2045.43 (Official version) (64-bit)

### Operating System and version

Windows 11 23H2 22631.2715

**Comment by mapx-** [comment]
- provide the link of the page in your screenshots
- is an account required ?
- go into uBO dashboard, support tab, copy & paste here the `Troubleshooting Information
`

**Comment by Xbaishu** [comment]
1.https://www.bilibili.com/video/BV1bh4y167zS
2. no,can log in using guest mode
3.uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 118527
 cosmetic: 54347
 scriptlet: 19437
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-quick-fixes: 171-55, 1h
 default:
  user-filters: 12-0, never
  CHN-0: 25831-136, 1h.5m
  easylist: 75699-26, 1h.5m
  easyprivacy: 32962-77, 59m
  plowe-0: 3720-1084, 1h.5m
  ublock-badware: 7478-137, 1h
  ublock-filters: 35745-173, 1h
  ublock-privacy: 855-11, 1h
  ublock-unbreak: 2154-34, 1h
  urlhaus-1: 9565-0, 1h.6m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 14 redacted]
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 403 ms (selfie)
 maxAssetCacheWait: 156 ms

**Comment by Xbaishu** [comment]
This website may be inaccessible or slow to load outside China (including Hong Kong, Macao and Taiwan). Please pay attention to the network environment.

**Comment by mapx-** [comment]
add & test

```
bilibili.com#@##slide_ad + .ad-report
bilibili.com#@#.ad-report
```

**Comment by mapx-** [comment]
@cjx82630 could you help here ?

**Comment by Xbaishu** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/87755186/ea09d847-b73e-4374-998c-eea6e2a7c93d)
like this？

**Comment by mapx-** [comment]
mmhmm .. those exceptions are fixing the missing video on the right side.

disable all other custom filters for bilibili you have in "my filters"

**Comment by Xbaishu** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/87755186/c33731e6-63e2-4bdc-9cf0-77f1c29e707d)
emmmm....
After I modified it like this, I saved it and refreshed the web page, but I found that the problem was not fixed.

**Comment by mapx-** [comment]
something else in your browser / system is breaking it

**Comment by Xbaishu** [comment]
But when I close the filter and refresh the webpage again, the content within the biliMainHeader element will reappear.
I'm very troubled by this

**Comment by mapx-** [comment]
> I close the filter

What filter are you talking about ?

**Comment by Xbaishu** [comment]
> > I close the filter
> 
> What filter are you talking about ?

Are you talking about me? I don't remember sending this sentence

**Comment by mapx-** [comment]
You said: `But when I close the filter and refresh the webpage again`

What filter do you close ?

**Comment by Xbaishu** [comment]
> You said: `But when I close the filter and refresh the webpage again`
> 
> What filter do you close ?

uBlock Origin

**Comment by mapx-** [comment]
Well, reset / reinstall uBO

**Comment by Xbaishu** [comment]
uBO has to be reinstalled, I found that resetting doesn't do that

**Comment by Xbaishu** [comment]
This problem seems to have been solved now. Thank you very much for your answer.

**Comment by Xbaishu** [comment]
When I clicked on other pages of the website, I found that this problem occurred again......

**Comment by mapx-** [comment]
Disable any other extension and repeat the test

**Comment by Xbaishu** [comment]
It seems that the situation is not fixed now. Sometimes it still doesn't display, but it seems to load normally most of the time.
