### ISSUE TITLE
wnd.com: breakage

### ISSUE THREAD

**Issue by Lerianis** [uBlockOrigin/uAssets#20885]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wnd.com/2023/11/ice-agent-warns-terror-groups-like-hamas-already-u-s-thanks-open-border/?ff_source=Email&ff_medium=wnd-breaking&ff_campaign=breaking&ff_content=breaking`

### Category

breakage

### Description

Comment section on WND does not appear when uBlock Origin is enabled, reappears when uBlock Origin is disabled.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103220
 cosmetic: 43932
 scriptlet: 19279
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75719-16, now
  easyprivacy: 32962-64, 14m
  plowe-0: 3720-1082, now
  ublock-badware: 7494-137, now
  ublock-filters: 35752-159, now
  ublock-privacy: 866-11, now
  ublock-quick-fixes: 171-55, 13m
  ublock-unbreak: 2154-33, now
  urlhaus-1: 9295-0, now
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
 removed:
  chrome-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1519 ms (selfie)
 maxAssetCacheWait: 508 ms
popupPanel:
 blocked: 35
 network:
  aj2495.online: 1
  amazon-adsystem.com: 1
  contextweb.com: 3
  d3lcz8vpax4lo2.cloudfront.net: 1
  decide.dev: 1
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 2
  googletagmanager.com: 2
  googletagservices.com: 1
  id5-sync.com: 1
  izooto.com: 1
  mgid.com: 5
  pubmatic.com: 1
  quantserve.com: 3
  revcontent.com: 2
  rlcdn.com: 1
  scorecardresearch.com: 3
  script.ac: 1
  sentry.io: 1
  soapps.net: 1
  zergnet.com: 1
 extended:
  ###BB1-ad
  ##.ad-notice
  ###IC1-ad
  ###IC2-ad
  ###IC3-ad
  ###IC4-ad
  ##.insticator-ads
  ##.firefly-sidebar-ad
  ##.persistent-footer
  ##.sponsor
  ##[data-rc-widget]
  ##div[id^="rc-widget-"]
  ##div[id*="ScriptRoot"]
  ##div[id^="zergnet-widget"]
  ##+js(abort-current-script, document.createElement, admiral)
```
</details>

**Comment by mapx-** [comment]
add

`@@||soapps.net/live/loader/bundle.js$script,domain=wnd.com`

@ryanbr
