### ISSUE TITLE
digminecraft.com: nuisance

### ISSUE THREAD

**Issue by ItsProfessional** [uBlockOrigin/uAssets#20886]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.digminecraft.com/generators/give_food.php`

### Description

A banner shows on the page when uBO is used, containing:
```
Oops, something is preventing this web page from loading properly. For the best experience, please consider disabling any content blockers you may have active in your web browser.

Please click here to learn more about us and our policies.
```
See screenshots for an example. It does not disable the usability of the webpage, and is dismissable. So I consider this as a nuisance instead of detection.

Suggested filter:
```adb
digminecraft.com##+js(set, placeAdsHandler, noopFunc)
```

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63961221/e06f736e-f22e-4f41-9a07-6d705c1b4d13)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 201150
 cosmetic: 116791
 scriptlet: 26055
 html: 1306
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4191-95, 21h.34m
  easylist-chat: 165-0, 21h.34m
  fanboy-cookiemonster: 49037-281, 21h.34m
  ublock-cookies-easylist: 577-0, 21h.34m
  easylist-newsletters: 6660-13, 21h.34m
  easylist-notifications: 2877-4, 21h.34m
  fanboy-social: 16161-7, 21h.34m
  ublock-annoyances: 5852-608, 21h.34m
 default:
  user-filters: 0-0, never
  ublock-filters: 36633-112, 15m
  ublock-badware: 7498-10, 15m
  ublock-privacy: 860-4, 15m
  ublock-unbreak: 2200-3, 15m
  ublock-quick-fixes: 172-2, 15m
  easylist: 75665-736, 1d.22h.46m
  adguard-spyware-url: 1338-94, 1d.22h.46m
  easyprivacy: 32964-824, 1d.22h.46m
  urlhaus-1: 9565-0, 21h.45m
  curben-phishing: 89802-28, 21h.46m
  plowe-0: 3719-1, 1d.22h.46m
  LegitimateURLShortener: 2495-157, 21h.47m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 285 ms (selfie)
 maxAssetCacheWait: 198 ms
popupPanel:
 blocked: 23
 network:
  adnxs.com: 3
  casalemedia.com: 2
  criteo.com: 1
  dotomi.com: 1
  exponential.com: 3
  indexww.com: 1
  lijit.com: 2
  media.net: 1
  rubiconproject.com: 6
  sharethrough.com: 3
 extended:
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##.sharepage
  ##div > [id$="_slot"]:upward(div)
```
</details>

**Comment by mapx-** [comment]
fixed, thanks
