### ISSUE TITLE
svgrepo.com: ads

### ISSUE THREAD

**Issue by Zenphia** [uBlockOrigin/uAssets#20887]
### Prerequisites

- [x] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://svgrepo.com`

### Description

page ads

### Other extensions used

none related to ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 103264
 cosmetic: 43946
 scriptlet: 19280
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 14-0, never
  easylist: 75759-15, 3m
  easyprivacy: 32963-64, 3m
  plowe-0: 3720-1082, 3m
  ublock-badware: 7494-137, 3m
  ublock-filters: 35755-159, 3m
  ublock-privacy: 865-11, 3m
  ublock-quick-fixes: 172-55, 3m
  ublock-unbreak: 2154-33, 3m
  urlhaus-1: 9295-0, 3m
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 123 ms (selfie)
 maxAssetCacheWait: 45 ms
popupPanel:
 blocked: 4
 network:
  buysellads.com: 2
  googletagmanager.com: 1
  insightexpressai.com: 1
```
</details>

**Comment by mapx-** [comment]
what ads ? screenshot indicating the ads ?

**Comment by mapx-** [comment]
`svgrepo.com##[class^="style_native"]:has([href*="buysellads.com"])`

@ryanbr
