### ISSUE TITLE
animedigitalnetwork.fr - Anti-adblock

### ISSUE THREAD

**Issue by KaZantip0** [uBlockOrigin/uAssets#2088]
### URL(s) where the issue occurs

`https://animedigitalnetwork.fr/video/boruto-naruto-next-generations/8802-episode-55-l-arme-scientifique-ninja`

### Describe the issue

Impossible to launch the video. When the page is loaded a message say "Please desactivate your ad block to launch the video".

### Screenshot(s)

![sans titre](https://user-images.githubusercontent.com/38734767/39266233-b59d1abe-48c9-11e8-9755-92173f72768a.jpg)

### Versions

- Browser/version: Firefox 59.0.2 (64 bits)
- uBlock Origin version:  1.16.0

### Settings

default settings

**Comment by KaZantip0** [comment]
Thanks. Filters tested but doesn't work.

**Comment by mapx-** [comment]
Using the filters above I get

> Pour des raisons légales, nous ne sommes pas autorisés à diffuser nos vidéos dans ce territoire.
> Votre pays

**Comment by mapx-** [comment]
@SMed79  could you test the filters above ?

**Comment by KaZantip0** [comment]
I couln't see your video.

"For legals reasons, we are not authorized to diffuse our video in your country".

![sans titre](https://user-images.githubusercontent.com/38734767/39269503-4ccab596-48d3-11e8-8da1-6f13600fa2d1.jpg)

**Comment by SMed79** [comment]
> `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=animedigitalnetwork.fr`

already part of **Liste FR**

> `animedigitalnetwork.fr##script:inject(set-constant.js, adblocked, false)`

fix the anti adblock for me 

* https://i.imgur.com/Zli9GBZ.gifv

alternative

`@@||animedigitalnetwork.fr/templates/adnv2/js/advertising.js$script`

* https://i.imgur.com/kuR2Ety.gifv

**Comment by KiLL4FuNK** [comment]
anti adblock
