### ISSUE TITLE
infinityscans.xyz: detection

### ISSUE THREAD

**Issue by AI-Guessr** [uBlockOrigin/uAssets#20881]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://infinityscans.xyz/comic/121/lucky-me-i-secretly-cultivated-for-1-000-years/chapter/52040/546q0dgkht9pgqho94ulila025`

### Category

detection

### Description

Detects blocking, redirects to page asking to disable any adblockers. Tested with and without other extensions/filters enabled/disabled.

### Other extensions used

Attempted with no other extensions enabled.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103481
 cosmetic: 43992
 scriptlet: 19277
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 77-3, never
  easylist: 75699-16, now
  easyprivacy: 32962-64, now
  plowe-0: 3720-1082, now
  ublock-badware: 7494-137, now
  ublock-filters: 35746-157, now
  ublock-privacy: 866-11, now
  ublock-quick-fixes: 171-55, now
  ublock-unbreak: 2154-33, now
  urlhaus-1: 9565-0, now
filterset (user): [array of 77 redacted]
trustedset:
 added: [array of 27 redacted]
 removed:
  chrome-scheme
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 388 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 4
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  h12-media.com: 1
  prplads.com: 1
 extended:
  ##+js(no-fetch-if, ads)
```
</details>

**Comment by BlazeFTL** [comment]
@AI-Guessr Can You Update Filters And Check Again ?

**Comment by AI-Guessr** [comment]
@BlazeFTL Tested. Purged and updated. While I don't get the redirect for the anti-adblock, the main content doesn't load. See: https://i.imgur.com/nw2Ir4T.png

Disabling UBO makes the page load, albeit with ads.
