### ISSUE TITLE
mobalytics.gg: ads

### ISSUE THREAD

**Issue by GG0607** [uBlockOrigin/uAssets#20884]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mobalytics.gg/`

### Category

ads

### Description

page ads

### Other extensions used

none related to ads

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/152061524/75c1ee1e-0c48-4624-8d56-a626d8472d68)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 103207
 cosmetic: 43931
 scriptlet: 19100
 html: 1113
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 36631-104, now
  ublock-badware: 7498-10, now
  ublock-privacy: 860-4, now
  ublock-unbreak: 2200-2, now
  ublock-quick-fixes: 172-2, 1h.23m
  easylist: 75719-703, now
  easyprivacy: 32963-735, now
  urlhaus-1: 9295-0, now
  plowe-0: 3720-1, 1h.24m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8279 ms (selfie)
 maxAssetCacheWait: 67 ms
popupPanel:
 blocked: 7
 network:
  d1l6p2sc9645hc.cloudfront.net: 1
  doubleclick.net: 1
  fuseplatform.net: 1
  googletagmanager.com: 1
  hotjar.com: 1
  mixpanel.com: 1
  riotgames.com: 1
```
</details>

**Comment by mapx-** [comment]
test

    mobalytics.gg##aside > div[class]:has-text(/Remove ads/i)
    mobalytics.gg##[style]:has-text(/Remove ads/i)
