### ISSUE TITLE
viki.com: detection

### ISSUE THREAD

**Issue by ojousan64** [uBlockOrigin/uAssets#20889]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.viki.com/`

### Category

detection

### Description

Google Chrome Version 119.0.6045.160 (64-Bit)
It was working fine just two days ago. Videos would play without any issue. Now the website detects UblockOrigin right after clicking on a video. I've tried to find a solution by my own however most of the reports here where either a year old or older or the ones posted recently used different browsers, and may have been cause by something else or somehow they managed to fix it but I cannot seem to fix it.

I tried to clear caches, cookies, reload, trying to find costum filter, update the filter list, or trying to fiy it by removing and adding the addional filter lists then reload and try again, trying to enable/ disable the Easylist filters > all failed...I'm out of ideas and need help fixing it. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (2)](https://github.com/uBlockOrigin/uAssets/assets/152069580/b6035bc6-3518-4d0c-bb31-ce92e7ff6992)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 136741
 cosmetic: 246645
 scriptlet: 46683
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28148-31, now
  adguard-generic: 80316-487, now
  adguard-mobile: 8765-58, now
  adguard-mobile-app-banners: 4805-10, now
  adguard-other-annoyances: 13827-11, now
  adguard-popup-overlays: 26310-84, now
  adguard-social: 22041-929, now
  adguard-widgets: 2349-7, now
  easylist-annoyances: 4194-243, now
  easylist-chat: 165-11, now
  easylist-newsletters: 6639-444, now
  easylist-notifications: 2878-1456, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  DEU-0: 7174-0, now
  easylist: 75759-1765, now
  easyprivacy: 32963-292, now
  plowe-0: 3720-1169, now
  ublock-badware: 7494-321, now
  ublock-filters: 35754-4243, now
  ublock-privacy: 866-13, now
  ublock-quick-fixes: 172-57, now
  ublock-unbreak: 2154-99, now
  urlhaus-1: 9295-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 297 ms (selfie)
 maxAssetCacheWait: 200 ms
popupPanel:
 blocked: 40
 network:
  appsflyer.com: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  imasdk.googleapis.com: 1
  litix.io: 1
  viki.io: 35
 extended:
  ##+js(set-constant, VikiPlayer.prototype.pingAbFactor, noopFunc)
  ##+js(set-constant, player.options.disableAds, true)
  ##+js(set-constant, VikiMediaPlayer.prototype.executeAdblockBrea…
  ##+js(set-constant, VikiMediaPlayer.prototype.requestAdblockBrea…
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/20853

follow all these indications:

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by gorhill** [comment]
I get an anti-content blocker warning when I enable ABP along uBO, so I used this as yet another example of why using other content blockers along uBO is bad: https://twitter.com/gorhill/status/1729888678850564163
