### ISSUE TITLE
elcorteingles.es: breakage

### ISSUE THREAD

**Issue by UserPizza** [uBlockOrigin/uAssets#20897]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.elcorteingles.es/electronica/`

### Description

accessibility breakage ( bottom left button )

![1](https://github.com/uBlockOrigin/uAssets/assets/146446273/20caf414-df1b-49ed-9f6a-4aedeab0d32d)

### Other extensions used

- 7TV
- Picture-in-Picture

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 105952
 cosmetic: 50273
 scriptlet: 19718
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75775-15, 1m
  easyprivacy: 32967-64, now
  plowe-0: 3720-1082, now
  spa-0: 3769-20, now
  spa-1: 5763-225, now
  ublock-badware: 7509-137, now
  ublock-filters: 35772-187, now
  ublock-privacy: 866-11, now
  ublock-quick-fixes: 180-52, now
  ublock-unbreak: 2154-35, now
  urlhaus-1: 9445-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 164 ms (selfie)
 maxAssetCacheWait: 84 ms

```
</details>

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtm.js$script,domain=elcorteingles.es`

@ryanbr
