### ISSUE TITLE
pinterest.com: breakage

### ISSUE THREAD

**Issue by thinkerthyme** [uBlockOrigin/uAssets#20894]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.com/`

### Category

breakage

### Description

some pins flashing when hovering over them, making them impossible to click on.

### Other extensions used

privacy badger, dark reader, lastpass, ecosia, return youtube dislike, honey, firefox color, leechblock NG, stylus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/152093525/87a51054-c316-46ce-94f0-422b6d97a8e7

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 103427
 cosmetic: 43946
 scriptlet: 19113
 html: 1113
listset (total-discarded, last-updated):
 default:
  user-filters: 4-1, never
  ublock-filters: 36646-212, now
  ublock-badware: 7513-10, now
  ublock-privacy: 860-4, now
  ublock-unbreak: 2200-2, now
  easylist: 75775-549, now
  easyprivacy: 32967-777, now
  urlhaus-1: 9445-0, now
  plowe-0: 3720-1, now
  ublock-quick-fixes: 175-2, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 633 ms (selfie)
 maxAssetCacheWait: 191 ms
popupPanel:
 blocked: 2
 network:
  pinterest.com: 2
 extended:
  ##[data-grid-item]:has([aria-label]:not([aria-label*="pinterest"…
```
</details>

**Comment by mapx-** [comment]
disable all other addons, try using only uBO
