### ISSUE TITLE
aliexpress.us: nuisance

### ISSUE THREAD

**Issue by NotReached** [uBlockOrigin/uAssets#20898]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aliexpress.us/`

### Category

nuisance

### Description

When opening the website, the same thing pops up over and over and I have to exit out of it - but it keeps popping up.

### Other extensions used

darkreader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

/
<img width="1549" alt="aliexpress" src="https://github.com/uBlockOrigin/uAssets/assets/28967078/a9e4f0ae-09d5-4ddd-8815-678d637ccd7d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 117
filterset (summary):
 network: 185736
 cosmetic: 43946
 scriptlet: 19131
 html: 1113
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36651-101, now
  ublock-badware: 7513-10, now
  ublock-privacy: 860-4, now
  ublock-unbreak: 2200-3, now
  ublock-quick-fixes: 180-2, now
  easylist: 75775-702, now
  adguard-spyware-url: 1339-94, now
  easyprivacy: 32967-735, now
  urlhaus-1: 9445-0, now
  curben-phishing: 78764-27, now
  plowe-0: 3720-1, now
  LegitimateURLShortener: 2496-157, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 477 ms (selfie)
 maxAssetCacheWait: 268 ms
popupPanel:
 blocked: 118
 network:
  alicdn.com: 3
  criteo.net: 1
  duckduckgo.com: 2
  facebook.net: 1
  go-mpulse.net: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  mmstat.com: 105
  taobao.com: 2
```
</details>

**Comment by mapx-** [comment]
enable `AdGuard – Annoyances`

or 

add
`aliexpress.us##.image-poplayer-modal`
