### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by UTDDavid** [uBlockOrigin/uAssets#20896]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reddit.com/r/Naruto/comments/184l0pc/sakura_art/`

### Category

breakage

### Description

Reddit image posts have a feature where you can add captions and links under a picture. The links are are not being shown. 

This happens on the new.reddit.com design (change www to new to get the new design, may have to be logged in). Note that this is not new new/newer redesign reddit is rolling out that you seen when not logged in.

If you load the link directly, the link under the image is missing. But if you are in the subreddit feed, and click on the image post, the overlay shows the link under the image.

### Other extensions used

Violentmonkey, Bitwarden, simplemodifyheaders.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/91843300/a294b5ce-469e-4848-80ab-2eb6ea699bf8)

![image](https://github.com/uBlockOrigin/uAssets/assets/91843300/84de53d7-73a0-4928-b5b1-04d19b322b0a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 103447
 cosmetic: 43944
 scriptlet: 19299
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75775-15, 2m
  easyprivacy: 32967-64, 2m
  plowe-0: 3720-1082, 2m
  ublock-badware: 7509-137, 2m
  ublock-filters: 35773-159, 2m
  ublock-privacy: 866-11, 2m
  ublock-quick-fixes: 180-52, 2m
  ublock-unbreak: 2154-33, 2m
  urlhaus-1: 9445-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 691 ms
 maxAssetCacheWait: 10 ms
popupPanel:
 blocked: 10
 network:
  reddit.com: 5
  ad-delivery.net: 1
  redditmedia.com: 1
  redditstatic.com: 3
 extended:
  ##.promotedlink:not([style^="height: 1px;"])
  ##+js(trusted-replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(abort-on-property-write, STICKY_CANARY)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by UTDDavid** [comment]
Cause by extension...

**Comment by UTDDavid** [comment]
How strange. The link appears fine for me when I disable uBO, I can't even get it to hide. I just did this in Windows Sandbox too.
If I uncheck uBlock filters – Privacy, then the link appears for me.

And also it seems that the issue is not reproducible on new.reddit but www.reddit so you just have to have the new (not newer redesign) design on the reddit post link and not force it. I just assumed new.reddit would be the same so that was my bad.

**Comment by Daxy7** [comment]
the url is `sh.reddit.com` if anyone's having trouble accessing the new redesign
