### ISSUE TITLE
decrypt.day: detection

### ISSUE THREAD

**Issue by subby2006** [uBlockOrigin/uAssets#20901]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://decrypt.day/app/id591560124`

### Category

detection

### Description

Anti adblock message prevents download from free download button

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox Mobile: 120
filterset (summary):
 network: 268298
 cosmetic: 75926
 scriptlet: 39914
 html: 1307
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  adguard-generic: 80317-7439, now
  adguard-spyware-url: 1339-94, now
  curben-phishing: 78557-29, 1h.29m
  ublock-annoyances: 5925-12, now
  dpollock-0: 11584-492, now
  adguard-spyware: 72733-16987, now
 default:
  user-filters: 20-0, never
  ublock-filters: 36978-352, now
  ublock-badware: 7507-10, now
  ublock-privacy: 860-5, now
  ublock-unbreak: 2205-4, now
  ublock-quick-fixes: 180-2, now
  adguard-mobile: 8765-129, now
  easylist: 75775-16900, now
  easyprivacy: 32967-819, now
  urlhaus-1: 9430-0, now
  plowe-0: 3720-1, now
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 17 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
hostRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 6601 ms (selfie)
 maxAssetCacheWait: 390 ms
popupPanel:
 blocked: 8
 network:
  google.com: 7
  googletagmanager.com: 1
 extended:
  ##.d3-item
  ##ins.adsbygoogle:style(height: 0px !important;)
  ##ins.adsbygoogle:style(height: 1px !important;)
  #@#ins.adsbygoogle
```
</details>

**Comment by BlazeFTL** [comment]
Reset Ubo To Default Dont Add Too Many External Filters

**Comment by mapx-** [comment]
issue on adguard generic list @Yuki2718 

@subby2006 use default uBO lists 

add for now

`decrypt.day#@#.d3-item`
