### ISSUE TITLE
myfirstname.in: detection

### ISSUE THREAD

**Issue by RidwanXyZ** [uBlockOrigin/uAssets#20900]
### Prerequisites

- [x] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://myfirstname.in/?lid=u6mRh&pid=888901&plid=1&vid=244195252`

### Category

detection

### Description

detected using adblock on this domain

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium Mobile: 120
filterset (summary):
 network: 109028
 cosmetic: 36623
 scriptlet: 19367
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  IDN-0: 9696-3883, 2m
  adguard-mobile: 8765-47, 2m
  easylist: 75699-16060, 1m
  easyprivacy: 32967-75, 1m
  plowe-0: 3720-1157, 1m
  ublock-badware: 7488-138, 1m
  ublock-filters: 36078-423, 1m
  ublock-privacy: 866-12, 1m
  ublock-quick-fixes: 180-52, 1m
  ublock-unbreak: 2159-37, 1m
  urlhaus-1: 9430-0, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1931 ms
 maxAssetCacheWait: 892 ms
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 2
```
</details>

**Comment by BlazeFTL** [comment]
> why closed?

https://github.com/uBlockOrigin/uAssets/pull/20895/commits/b4eb7ecb4462ac26929c98e2853c38f7beac1c11

**Comment by BlazeFTL** [comment]
@RidwanXyZ Update Filters & Try
