### ISSUE TITLE
shrinkforearn.in: breakage

### ISSUE THREAD

**Issue by GollumArain** [uBlockOrigin/uAssets#20904]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://shrinkforearn.in/evrthcolam`

### Category

breakage

### Description

Site does not load properly, when uBlocker enabled.

### Other extensions used

Bitwarden, IDM

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 279131
 cosmetic: 192802
 scriptlet: 47342
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28154-1592, now
  adguard-generic: 80317-730, now
  adguard-mobile: 8765-74, now
  adguard-mobile-app-banners: 4805-18, now
  adguard-other-annoyances: 13827-16, now
  adguard-popup-overlays: 26310-124, now
  adguard-social: 22041-2071, now
  adguard-spyware: 72733-1242, now
  adguard-spyware-url: 1339-5, now
  adguard-widgets: 2349-41, now
  block-lan: 55-0, now
  curben-phishing: 78557-20, now
  [11 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  easylist: 75915-17932, now
  easyprivacy: 32969-16555, now
  plowe-0: 3720-1584, now
  ublock-badware: 7509-329, now
  ublock-filters: 35772-4481, now
  ublock-privacy: 866-344, now
  ublock-quick-fixes: 180-54, now
  ublock-unbreak: 2154-148, now
  urlhaus-1: 9430-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1397 ms (selfie)
 maxAssetCacheWait: 1018 ms
popupPanel:
 blocked: 9
 network:
  cleverwebserver.com: 1
  cloudflareinsights.com: 1
  d3u598arehftfk.cloudfront.net: 1
  google-analytics.com: 4
  goomaphy.com: 1
  mgid.com: 1
 extended:
  ##.box-main > .row
  ##.blog-item
  ##.banner, .banner-page .box-main > .row, .box-main .blog-item, …
  ##+js(set-constant, app_vars.force_disable_adblock, undefined)
  ##+js(no-window-open-if)
  ##+js(abort-on-property-read, app_vars.force_disable_adblock)
  ##+js(set-constant, blurred, false)
  ##+js(replace-node-text, script, counter_value":"5", counter_val…
```
</details>

**Comment by BlazeFTL** [comment]
Well Done
```
added:
  adguard-cookies: 28154-1592, now
  adguard-generic: 80317-730, now
  adguard-mobile: 8765-74, now
  adguard-mobile-app-banners: 4805-18, now
  adguard-other-annoyances: 13827-16, now
  adguard-popup-overlays: 26310-124, now
  adguard-social: 22041-2071, now
  adguard-spyware: 72733-1242, now
  adguard-spyware-url: 1339-5, now
  adguard-widgets: 2349-41, now
  block-lan: 55-0, now
  curben-phishing: 78557-20, now
  [11 lists not shown]: [too many]
```
Reset UBO To Default Dont Add Any Extra List At All If Use Shortner Sites A Lot

**Comment by mapx-** [comment]
yeah, revert to default settings / list, if still broken add a comment here, closing for now
