### ISSUE TITLE
szeged365.hu: ads

### ISSUE THREAD

**Issue by 66Gramms** [uBlockOrigin/uAssets#20908]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://szeged365.hu/`

### Category

ads

### Description

This news website has tons of ad on the landing page and in all their articles

### Other extensions used

- Sponsorblock for Youtube
- KeePassXC-Browser
- CSGO Trader - Steam Trading Enhancer
- Tampermonkey
- Return YouTube Dislike
- Nyan YouTube enhancement
- TWP - Translate Web Pages

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 103558
 cosmetic: 43948
 scriptlet: 19124
 html: 1113
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 36656-101, now
  ublock-badware: 7513-10, now
  ublock-privacy: 860-4, now
  ublock-unbreak: 2200-1, now
  ublock-quick-fixes: 179-2, now
  easylist: 75917-703, now
  easyprivacy: 32969-735, now
  urlhaus-1: 9430-0, now
  plowe-0: 3720-1, now
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 196 ms (selfie)
 maxAssetCacheWait: 78 ms
popupPanel:
 blocked: 9
 network:
  szeged365.hu: 2
  cloudflareinsights.com: 2
  facebook.com: 3
  googletagmanager.com: 2
 extended:
  ###kezdolap-superleaderboard-felso > .stream-title
  ##.logo-row.tie-row
  ##.stream-item-widget
  ##.AdBox
  ##.post-ads
  ##.dfp_unit
```
</details>

**Comment by mapx-** [comment]
enable the regional filter `hu: hufilter`
