### ISSUE TITLE
tv4play.se: detection

### ISSUE THREAD

**Issue by Antjo2000** [uBlockOrigin/uAssets#20914]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tv4play.se/`

### Category

detection

### Description

When pressing on a video it gives a message along the lines: Do you have a adblocker turned on, you need to turn it off.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 105435
 cosmetic: 46541
 scriptlet: 19463
 html: 1130
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36665-101, now
  ublock-badware: 7519-10, now
  ublock-privacy: 860-4, now
  ublock-unbreak: 2200-1, now
  ublock-quick-fixes: 180-2, now
  easylist: 76036-709, now
  easyprivacy: 32970-741, now
  urlhaus-1: 9605-0, now
  plowe-0: 3720-1, now
  SWE-1: 4537-6, now
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4212 ms (selfie)
 maxAssetCacheWait: 201 ms
popupPanel:
 blocked: 4
 network:
  tv4play.se: 1
  bugsnag.com: 1
  duckduckgo.com: 2
 extended:
  ##+js(json-prune-fetch-response, bumpers, , propsToMatch, url:/p…
  ##+js(xml-prune, MediaFile, , se-tv4.videoplaza.tv/proxy/distrib…
```
</details>

**Comment by mapx-** [comment]
@lassekongo83

**Comment by lassekongo83** [comment]
Unable to reproduce. Try to disable all other browser extensions except uBlock Origin. If it works you can then enable each extension one by one until you find the responsible one.

Other causes can be anti-virus blockers, firewalls, DNS (pi-hole too), VPN, etc.

Their anti-ab is mostly triggered if the domain `vidoplaza.tv` is completely blocked by something.
