### ISSUE TITLE
thecollegefix.com: breakage

### ISSUE THREAD

**Issue by TheNightRider12** [uBlockOrigin/uAssets#20916]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.thecollegefix.com/`

### Description

When browsing The College Fix, I cannot click on any article links. I tested in a fresh firefox profile with just uBO installed. I only enabled "AdGuard - Popup Overlays" and the issue occurred. I disabled that filter, refreshed the website and I could click article links as normal.  

### Other extensions used

This issue occurs on a fresh firefox profile with just uBO installed. So in this case, I would say no extensions.  

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 278281
 cosmetic: 221722
 scriptlet: 46056
 html: 1307
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80329-7340, now
  adguard-mobile: 8769-17, now
  adguard-spyware-url: 1344-95, now
  adguard-spyware: 74844-16978, now
  block-lan: 55-0, now
  curben-phishing: 78437-30, now
  adguard-social: 22054-866, now
  adguard-cookies: 28180-64, now
  ublock-cookies-adguard: 581-0, now
  adguard-mobile-app-banners: 4808-9, now
  adguard-other-annoyances: 13831-313, now
  adguard-widgets: 2349-2, now
  [10 lists not shown]: [too many]
 default:
  user-filters: 80-0, never
  ublock-filters: 36666-401, now
  ublock-badware: 7519-10, now
  ublock-privacy: 860-4, now
  ublock-unbreak: 2200-0, now
  ublock-quick-fixes: 188-3, now
  easylist: 76055-971, now
  easyprivacy: 32970-911, now
  urlhaus-1: 9605-0, now
  plowe-0: 3720-85, now
filterset (user): [array of 79 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5262 ms
 maxAssetCacheWait: 25 ms
```
</details>

**Comment by mapx-** [comment]
add

`thecollegefix.com#@#.subscribe`

@Yuki2718 
`AdGuard – Popup Overlays` issue

**Comment by TheNightRider12** [comment]
Thank you for the fix. I applied that fix in My Filters in the meantime.
