### ISSUE TITLE
jp.motorsport.com: detection

### ISSUE THREAD

**Issue by bocchi-rocks** [uBlockOrigin/uAssets#20917]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://jp.motorsport.com/motogp/news/motogp-rejects-rnfs-entry-for-2024-over-repeated-infractions-and-breaches/10552717/`

### Category

detection

### Description

Enabled The article will be detected. Disabled The article is displayed.

### Other extensions used

Adguard 7.15.1 (4386) (build 4386, CL 1.12.87)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.1b0
Firefox: 120
filterset (summary):
 network: 105796
 cosmetic: 55568
 scriptlet: 19306
 html: 1113
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36671-109, 1h.1m
  ublock-badware: 7519-10, 1h.1m
  ublock-privacy: 860-4, 1h.1m
  ublock-unbreak: 2200-1, 1h.1m
  ublock-quick-fixes: 179-2, 1h.1m
  easylist: 76036-722, 1h.1m
  easyprivacy: 32970-762, 1h.1m
  urlhaus-1: 9605-0, now
  plowe-0: 3720-1, now
  JPN-1: 13805-23, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 638 ms (selfie)
 maxAssetCacheWait: 432 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##.ms-ap
  ##.ms-apb-dmpu
  ##.ms-hapb
  ##+js(addEventListener-defuser, load, length)
  ##+js(addEventListener-defuser, gtmloaderror)
  ##+js(noeval-if, interactionCount)
  ##+js(abort-current-script, vardom)
  ##+js(remove-cookie, 45grw1567)
  ##+js(set-cookie, 4d8L2108, 1, , reload, 1)
  ##+js(abort-current-script, document.querySelector, adblock)
```
</details>

**Comment by bocchi-rocks** [comment]
> Are you using the 2 adblockers at the same time? (uBo + AG)

Thank you for your reply.
No, I am not. I checked with the function stopped.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by bocchi-rocks** [comment]
> * clear cookies / localStorage/ cache for the tested page
> 
>     * reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> 
>     * disable any custom filter for that site
> 
>     * disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> 
>     * if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
> 
>     * disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> 
>     * are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
> 
>     * restart the system, reopen the browser, test again.

Thank you very much.
I will test it.

**Comment by stephenhawk8054** [comment]
@mapx- Yeah, I cannot reproduce the issue.

As far as I know, they inject the inline script later in the `https://mstm.motorsport.com/mstm.js?id=GTM-KFM7PTT&l=gtmDataLayer` file. For example this inline script

```html
<script type="text/javascript" id="">(function(){var a=document.createElement("script");a.type="text/javascript";a.charset="utf-8";a.async=!0;a.src=window.location.protocol+"//api.popin.cc/searchbox/motorsport_jp.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();</script>
```

is not in `view-source` but will appear after you load the page (and that script loaded). So I'm not sure if `acs` could work in this case? If I remember correctly, some previous solutions of `acs` also targets this script file.
