### ISSUE TITLE
coralspringstalk.com: ads

### ISSUE THREAD

**Issue by hydroculator** [uBlockOrigin/uAssets#20923]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://coralspringstalk.com/road-rage-gun-in-coral-springs-48985`

### Category

ads

### Description

Banners and interstitial ads everywhere

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 120
filterset (summary):
 network: 105111
 cosmetic: 35151
 scriptlet: 19202
 html: 1116
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36977-351, now
  ublock-badware: 7516-10, now
  ublock-privacy: 860-5, now
  ublock-unbreak: 2205-2, now
  ublock-quick-fixes: 191-2, now
  adguard-mobile: 8771-129, now
  easylist: 75470-16725, now
  easyprivacy: 33016-743, now
  urlhaus-1: 9970-0, now
  plowe-0: 3720-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 445 ms (selfie)
 maxAssetCacheWait: 88 ms
popupPanel:
 blocked: 7
 network:
  coralspringstalk.com: 2
  disqus.com: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
 extended:
  ##ins.adsbygoogle
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by hydroculator** [comment]
![Screenshot_20231128-032119~2](https://github.com/uBlockOrigin/uAssets/assets/59405571/0fff60c3-85ab-45ec-aad9-4b3906432e10)

**Comment by hydroculator** [comment]
If you look closely, you can probably see at least one ad.

**Comment by BlazeFTL** [comment]
```
coralspringstalk.com##a[href] > img[class^="aligncenter"]

**Comment by mapx-** [comment]
add

```
||coralspringstalk.com/*banner$image
coralspringstalk.com##.gofollow
coralspringstalk.com##.wpbdp-listings-widget-list
coralspringstalk.com##.widget_wpbdp_featuredlistingswidget.widget
```

@ryanbr
