### ISSUE TITLE
tekniknot.com: detection

### ISSUE THREAD

**Issue by ItsProfessional** [uBlockOrigin/uAssets#20927]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://tekniknot.com/android-reklam-engelleme/`

### Description

<details>
  <summary>Detection script</summary>
  
  ```js
  function isGecko() {
    var e = document.querySelector('.td-post-content'),
    t = new XMLHttpRequest;
    t.open('GET', '/isGecko', !0),
    t.onreadystatechange = function () {
      4 === t.readyState &&
      200 === t.status &&
      (e.innerHTML = t.responseText)
    },
    t.send()
  }
  window.onload = () => {
    if (jQuery('.adsbygoogle').height() == 0) {
      isGecko()
    }
  }
  ```
  
</details>

I tried `@@||tekniknot.com^$ghide`, but that did not work for some reason.

```adb
tekniknot.com##+js(acs, onload, adsbygoogle)
```

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63961221/773aaf8f-ac60-4b4d-93b5-7a1b991c6dae)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 189838
 cosmetic: 116805
 scriptlet: 26096
 html: 1308
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4191-95, 2d.21h.34m
  easylist-chat: 165-0, 2d.21h.34m
  fanboy-cookiemonster: 49037-281, 2d.21h.34m
  ublock-cookies-easylist: 577-0, 2d.21h.34m
  easylist-newsletters: 6660-13, 2d.21h.34m
  easylist-notifications: 2877-4, 2d.21h.34m
  fanboy-social: 16161-7, 2d.21h.34m
  ublock-annoyances: 5852-608, 2d.21h.34m
 default:
  user-filters: 0-0, never
  ublock-filters: 36650-109, 1h.29m
  ublock-badware: 7522-10, 1h.29m
  ublock-privacy: 860-4, 1h.29m
  ublock-unbreak: 2200-2, 1h.29m
  ublock-quick-fixes: 191-2, 1h.29m
  easylist: 75665-731, 3d.22h.46m
  adguard-spyware-url: 1338-94, 3d.22h.46m
  easyprivacy: 32964-824, 3d.22h.46m
  urlhaus-1: 9605-0, 18h.4m
  curben-phishing: 78437-29, 18h.5m
  plowe-0: 3719-1, 3d.22h.45m
  LegitimateURLShortener: 2497-157, 1h.29m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 3180 ms
 maxAssetCacheWait: 1988 ms
popupPanel:
 blocked: 4
 network:
  cloudflare.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  yandex.ru: 1
 extended:
  ##a[href^="https://pinterest.com/pin/create/"]
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##.td-scroll-up
  ##.td-social-icon-wrap
  ##.td-icon-facebook
  ##.td-icon-instagram
  ##.td-icon-twitter
  ##.td-icon-youtube
  ##ins.adsbygoogle
  ##.td-post-sharing-bottom
  ##.td-post-sharing
  ##.td-social-sharing-button
  ##.wc_social_plugin_wrapper
  ##.wpd-sbs-title
  ##.wpdiscuz-subscribe-bar
  ###wpd-bubble-wrapper
```
</details>

**Comment by BlazeFTL** [comment]
> @@||tekniknot.com^$ghide

Bcz Its Checking .height() == 0

**Comment by slavaleleka** [comment]
@Yuki2718 

> it seems AG's `googlesyndication-adsbygoogle` redirect resource lacks something

would you please file an issue in the [Scriptlets repo](https://github.com/AdguardTeam/Scriptlets/issues/)?

**Comment by Yuki2718** [comment]
@slavaleleka Sorry, I didn't check properly atm. I found the problem is not in the redirect resource but `##.td-a-rec` in Base filter.
