### ISSUE TITLE
gamingdeputy.com: ads

### ISSUE THREAD

**Issue by liolio6** [uBlockOrigin/uAssets#20933]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gamingdeputy.com/`

### Category

ads

### Description

I found another issue for this site https://github.com/uBlockOrigin/uAssets/issues/10466 but in my case it is not a detection issue.
Ads are not blocked at all on the site

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/62901783/df0e0f6a-a201-4acb-9a50-bb07cbe28621)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 144930
 cosmetic: 163721
 scriptlet: 39351
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80361-706, now
  easylist-annoyances: 4194-60, now
  easylist-chat: 166-0, now
  easylist-newsletters: 6651-22, now
  easylist-notifications: 2878-95, now
  fanboy-cookiemonster: 49049-230, now
  fanboy-social: 16099-19, now
  ublock-cookies-easylist: 583-1, now
 default:
  user-filters: 2-0, never
  FRA-0: 28615-39, now
  easylist: 75482-1729, now
  easyprivacy: 33016-490, now
  plowe-0: 3720-1104, now
  ublock-badware: 7518-332, now
  ublock-filters: 35808-3942, now
  ublock-privacy: 876-14, now
  ublock-quick-fixes: 186-56, now
  ublock-unbreak: 2154-99, now
  urlhaus-1: 9965-0, now
filterset (user): [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 180 ms (selfie)
 maxAssetCacheWait: 86 ms
popupPanel:
 blocked: 10
 network:
  adpushup.com: 1
  adrecover.com: 1
  clarity.ms: 1
  criteo.net: 3
  googlesyndication.com: 2
  googletagmanager.com: 2
 extended:
  ##.bottom-sticky-offset
  ##div[class^="ad-wrapper-"]
  ##div[class^="vb-"]
  ##._ap_apex_ad
  ##+js(no-setTimeout-if, ai_adb)
```
</details>

**Comment by mapx-** [comment]
```
*$image,1p,domain=html-load.com
*$image,3p,redirect=1x1.gif,domain=html-load.com
*$doc,ping,font,css,domain=html-load.com
*$frame,redirect-rule=noopframe,domain=gamingdeputy.com
*$script,xhr,redirect-rule=noopjs,domain=gamingdeputy.com
*$image,redirect-rule=1x1.gif,domain=gamingdeputy.com
@@*$ghide,domain=gamingdeputy.com
gamingdeputy.com##+js(no-xhr-if, /static\.criteo\.net|adsbygoogle/)
gamingdeputy.com##[src="about:blank"]
```

@JobcenterTycoon
