### ISSUE TITLE
uploadbank.com: detection

### ISSUE THREAD

**Issue by ravertine** [uBlockOrigin/uAssets#20947]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.uploadbank.com/gu9me7qy5btf`

### Category

detection

### Description

Step 1) Solve the captcha and click on continue
Step 2) Click on download

A new windows will open: Access denied Disable your adblocker

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Capture](https://github.com/uBlockOrigin/uAssets/assets/97376305/4505bfaf-bc64-4735-9d13-ea3a1e506ec8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.5rc13
Chromium: 119
filterset (summary):
 network: 127152
 cosmetic: 90711
 scriptlet: 26705
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-other-annoyances: 13834-8, now
  adguard-popup-overlays: 26352-74, now
  easylist-annoyances: 4194-176, now
  ublock-annoyances: 5902-155, now
 default:
  user-filters: 4-1, never
  FRA-0: 28615-39, now
  easylist: 75499-133, now
  easyprivacy: 33017-399, now
  plowe-0: 3720-1093, now
  ublock-badware: 7518-150, now
  ublock-filters: 35829-574, now
  ublock-privacy: 879-13, now
  ublock-quick-fixes: 217-80, now
  ublock-unbreak: 2154-39, now
  urlhaus-1: 9980-0, 20m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 11 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 707 ms (selfie)
 maxAssetCacheWait: 293 ms
popupPanel:
 blocked: 5
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  gtitcah.com: 1
  proxycheck.io: 1
  shareaholic.net: 1
 extended:
  ##+js(noeval-if, /chp_?ad/)
  ##+js(set-constant, console.clear, noopFunc)
  ##+js(no-window-open-if)
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Fatcavill** [comment]
whenever i touch the screen it opens a new tab.pls fix

**Comment by stephenhawk8054** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/de2c5de860c4333d8c305da2a729a5c9435d0bf8

**Comment by Fatcavill** [comment]
tnx bro but how can i download file ? it says access denied or take me to a ad page to click ads

**Comment by Fatcavill** [comment]
[Screenshot_20240414-153809](https://github.com/uBlockOrigin/uAssets/assets/139833732/2dd55ebc-15e7-48f0-b394-3f497433dae6)

**Comment by stephenhawk8054** [comment]
It will take about some hours for the filter lists to be auto-updated, in the meantime add this as your custom filter

```adb
@@||d1r3ddyrqrmcjv.cloudfront.net^$script,3p,domain=uploadbank.com,badfilter
```

**Comment by dnet890** [comment]
@stephenhawk8054 it looks like it won't allowed granted any access with the extension enabled
![image](https://github.com/user-attachments/assets/4e517016-dedf-47ba-adca-f0f1d03ffc38)

**Comment by BlazeFTL** [comment]
@dnet890 Try
You Might Need To Click Button Twice
```
@@||dcbbwymp1bhlf.cloudfront.net^$script,domain=uploadbank.com
uploadbank.com##body > div:empty
uploadbank.com##+js(nowoif, !uploadbank, 10, obj)
uploadbank.com##div[style*="z-index: 2147483647; cursor: pointer; top: 515.447px; left: 151.592px; position: fixed; display: block;"]
