### ISSUE TITLE
[nsfw] smartkhabrinews.com: detection

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#20949]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://smartkhabrinews.com/indian-government-to-restrict-it-hardware-imports-from-china-and-promote-local-sourcing/`

### Category

detection

### Description

The link 
`https://streama2z.xyz/j2r5w7bh62wb/XXCOLLECTION.mp4` 
redirects to 
`https://smartkhabrinews.com/indian-government-to-restrict-it-hardware-imports-from-china-and-promote-local-sourcing/` 
after that redirects to 
`https://smartkhabrinews.com/adb.html`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/19629778/d1bfb781-46a2-4f1d-b5f4-4af222fef076)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105763
 cosmetic: 89702
 scriptlet: 26031
 html: 1313
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49050-271, now
  ublock-cookies-easylist: 583-0, now
  ublock-annoyances: 5858-593, now
 default:
  user-filters: 192-1, never
  ublock-filters: 36703-128, now
  ublock-badware: 7522-10, now
  ublock-privacy: 873-4, now
  ublock-unbreak: 2200-1, now
  ublock-quick-fixes: 217-3, now
  easylist: 75499-709, now
  easyprivacy: 33017-735, now
  urlhaus-1: 9980-0, now
  plowe-0: 3720-1, now
filterset (user): [array of 193 redacted]
trustedset:
 added: [array of 16 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 353 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 614 ms (selfie)
 maxAssetCacheWait: 242 ms
popupPanel:
 blocked: 0
 extended:
  ##ins.adsbygoogle
  ##+js(no-fetch-if, /freychang|passback|popunder|tag/)
```
</details>

**Comment by mapx-** [comment]
still ok on my side.
You instead are using dynamic filtering (rules), for example `* * 3p-script block`

Reset uBO to default settings / filter lists and do not touch them.

**Comment by JobcenterTycoon** [comment]
The anti adblock appear when a user try to download @BlazeFTL

**Comment by BlazeFTL** [comment]
This Site Also Uses Some Of The Script From DropGalaxy So Be Sure Its Also Might Be Cat Mouse Race😆

**Comment by BlazeFTL** [comment]
Unfortunately Theres Some Region Based Problem As It Doesn't Work For Me On FF/Chrome

**Comment by BlazeFTL** [comment]
@ghajini Could You Take A Look

**Comment by BlazeFTL** [comment]
> edit = i got detected

Try https://github.com/uBlockOrigin/uAssets/issues/20949#issuecomment-1833950617

Dont Consider This Site Anything Less Than DG

**Comment by BlazeFTL** [comment]
Yes This Works Too😊
