### ISSUE TITLE
wral.com: breakage

### ISSUE THREAD

**Issue by Ratfink** [uBlockOrigin/uAssets#20943]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wral.com/weather_map_center/8106570/`

### Category

breakage

### Description

The weather map never loads with uBlock Origin enabled.  Disabling filtering fixes the issue on page reload.  Not caused by Firefox's built-in filtering, as disabling this does not fix the issue.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

Broken page:
![image](https://github.com/uBlockOrigin/uAssets/assets/320472/fa1953ef-a4ca-44e4-982c-946aa0279c77)
After disabling uBO:
![image](https://github.com/uBlockOrigin/uAssets/assets/320472/9a1a8f7e-0206-411f-ba32-382b544c41bc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 103721
 cosmetic: 43978
 scriptlet: 19174
 html: 1116
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36702-128, now
  ublock-badware: 7522-10, now
  ublock-privacy: 874-4, now
  ublock-unbreak: 2200-1, now
  ublock-quick-fixes: 217-3, now
  easylist: 75499-698, now
  easyprivacy: 33017-735, now
  urlhaus-1: 9965-0, now
  plowe-0: 3720-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 192 ms (selfie)
 maxAssetCacheWait: 61 ms
popupPanel:
 blocked: 15
 network:
  wral.com: 2
  chartbeat.com: 2
  googletagmanager.com: 3
  h-cdn.com: 1
  hotjar.com: 1
  htlbid.com: 1
  imasdk.googleapis.com: 1
  maps.googleapis.com: 1
  revcontent.com: 1
  sail-horizon.com: 1
  scorecardresearch.com: 1
 extended:
  ##[data-rc-widget]
  ##div[id^="rc-widget-"]
  ##+js(abort-current-script, document.createElement, admiral)
```
</details>

**Comment by okiehsch** [comment]
@ryanbr broken by `EasyPrivacy`
`@@||wwwcache.wral.com/presentation/v3/scripts/providers/analytics/ga.js$script,domain=legacy.wral.com`
fiyes the issue on my end.

**Comment by stephenhawk8054** [comment]
This works for me

```adb
wral.com##+js(set, wral_ga, {})
```

**Comment by okiehsch** [comment]
> so maybe not necessarily to use scriptlet.

Yeah, we would have to overwrite the exception and add the scriptlet for a 1p script, let's leave it as is.
