### ISSUE TITLE
papers.ssrn.com: breakage

### ISSUE THREAD

**Issue by mothlight** [uBlockOrigin/uAssets#20948]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3896716&download=yes`

### Category

breakage

### Description

It breaks the download without registering. You should be able to select "Download this paper" and if you are not logged in, it takes you to a new page. Instead of having to login, you can select download without registering. When ublock is enabled, you just end up in a loop. 

Once you shut off ublock, the pdf is downloaded.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 119
filterset (summary):
 network: 103735
 cosmetic: 43978
 scriptlet: 19174
 html: 1116
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36703-128, now
  ublock-badware: 7522-10, now
  ublock-privacy: 873-4, now
  ublock-unbreak: 2200-1, now
  ublock-quick-fixes: 217-3, 4m
  easylist: 75499-698, 4m
  easyprivacy: 33017-735, now
  urlhaus-1: 9980-0, now
  plowe-0: 3720-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 717534 ms
 maxAssetCacheWait: 962 ms
popupPanel:
 blocked: 9
 network:
  adobedtm.com: 2
  cloudflareinsights.com: 2
  hotjar.com: 1
  leadboxer.com: 2
  liblynx.com: 1
  pendo.io: 1
```
</details>

**Comment by okiehsch** [comment]
> Once you shut off ublock

How did you shut it off?
On my end the site is in an infinite loop even if I whitelist the site in uBO.

**Comment by mothlight** [comment]
On the Firefox toolbar, you click the ublock icon. It brings up "blocked on this page ..." Click the blue circle power icon (click to disable for this site). Once I did this, the PDF downloaded.

Ok, I'm trying to determine if it was actually being blocked, or if it was just a long delay. It should normally loop back to the previous page but a PDF download will pop up. But sometimes there is a few second delay in the download starting.

**Comment by okiehsch** [comment]
> On the Firefox toolbar, you click the ublock icon. It brings up "blocked on this page ..." Click the blue circle power icon (click to disable for this site).

Ok. that's the way I did it as well and I still get an infinite loop without any download starting.
I asked another maintainer and he sees the same thing, so it looks like a site issue to us.

The download works fine using chromium/chrome.

**Comment by okiehsch** [comment]
>  But sometimes there is a few second delay in the download starting.

Correct, using chrome there is a delay before the download starts.

**Comment by gorhill** [comment]
> Once you shut off ublock, the pdf is downloaded

Same issue exists without uBO installed.
