### ISSUE TITLE
twitter.com: redirect breakage

### ISSUE THREAD

**Issue by Cynnyr** [uBlockOrigin/uAssets#20941]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://twitter.com/i/redirect?url=https%3A%2F%2Ftwitter.com%2Fitsginnydi%2Fstatus%2F1729528627488862231%3Fcn%3DZmxleGlibGVfcmVjcw%253D%253D%26refsrc%3Demail&cn=ZmxleGlibGVfcmVjcw%3D%3D&sig=a748be1c19d8a1c710670d4d4718553d93ea9a15&iid=34024211d2a54c54ae2b90d046b627ae&uid=17049243&nid=244+276893697`

### Category

Redirect breakage

![Screenshot from 2023-11-28 14-59-02](https://github.com/uBlockOrigin/uAssets/assets/22526850/ef2f64b3-351b-492a-8e89-d63a3cc5737e)

### Description

Getting a notification email from twitter and clicking on the link leads to the included screenshot.  If I turn off uBO on twitter it works fine.

Firefox 118.0.2 on Fedora 37

### Other extensions used

1Password, Disable JavaScript, FAcebook Container, To Google Translate, Web Deve
loper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 118
filterset (summary):
 network: 103717
 cosmetic: 43975
 scriptlet: 19171
 html: 1116
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36703-128, 1m
  ublock-badware: 7522-10, 1m
  ublock-privacy: 874-4, 1m
  ublock-unbreak: 2200-1, 1m
  ublock-quick-fixes: 210-3, 1m
  easylist: 75496-698, 1m
  easyprivacy: 33016-735, 1m
  urlhaus-1: 9965-0, 1m
  plowe-0: 3720-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 17010 ms
 maxAssetCacheWait: 4745 ms
popupPanel:
 blocked: 1
 network:
  google-analytics.com: 1
```
</details>

**Comment by D4niloMR** [comment]
@Cynnyr test: 

```adb
*$removeparam=t,from=twitter.com|x.com,badfilter
```

**Comment by Cynnyr** [comment]
That worked.

**Comment by krystian3w** [comment]
Possible undo label and mark as fixed.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/1771eb642e5c6cacb3f9f32930a1498ccbb3ba70

**Comment by fenopa** [comment]
> @Cynnyr test:
> 
> ```
> *$removeparam=t,from=twitter.com|x.com,badfilter
> ```

@D4niloMR I was the one who added that filter to remove "t" parameter, I don't see a "t" parameter in the URL mentioned here, why that filter to remove t parameter causes issue here, and more importantly, how the "t" tracking parameter can be removed without causing this issue? Currently, filter to remove t parameter is disabled but that's not a solution.

**Comment by fenopa** [comment]
@D4niloMR would it be possible to write a filter like "remove t parameter if there is no "redirect" in the URL"?

**Comment by D4niloMR** [comment]
Try this link, with the t parameter removed it won't work.

`https://twitter.com/i/redirect?url=https%3A%2F%2Ftwitter.com%2Fsettings%2Fsecurity&t=1&cn=cGFzc3dvcmRfcmVzZXRfcGluX2Jhc2VkX2VtYWls&sig=acab61fcded9e4747b9e8c743fc610f2b7780ca0&iid=ed27b3bc4e69484785db91588a169f1f&uid=1735853275113566208&nid=296+3`

---

> would it be possible to write a filter like "remove t parameter if there is no "redirect" in the URL"?

Do you have a link that uses this parameter as a tracker?

**Comment by fenopa** [comment]
> Do you have a link that uses this parameter as a tracker?

@D4niloMR yes that's a widely seen tracking parameter in tweet URLs, example: https://twitter.com/GalatasaraySK/status/1698769359919886700?t=OVYLtET1qF0c9C6vijlrfw&s=19

both t and s parameters are tracking parameters. can we make a filter to remove the parameter if there is no "/i/redirect" in the URL?

**Comment by D4niloMR** [comment]
@stephenhawk8054 maybe?

```adb
$removeparam=t,domain=twitter.com|x.com
@@/redirect?url=$removeparam=t,domain=twitter.com|x.com
```

**Comment by stephenhawk8054** [comment]
I think only the `status` link has `t` parameter? So maybe this

```adb
||com/*/status/$removeparam=t,domain=twitter.com|x.com
```

Do we have other links that have `t` parameter?

**Comment by stephenhawk8054** [comment]
I'm just not sure if there are other breakages or not, the `removeparam` section is mostly for the params that are safe to remove and don't have exceptions. For stuff like that, it's better to report at the specialized `AdGuard URL Tracking Protection` list.

**Comment by fenopa** [comment]
@stephenhawk8054 I don't think there would be other breakages but anyway, does the filter @D4niloMR wrote work for "AdGuard URL Tracking Protection"?

**Comment by stephenhawk8054** [comment]
@Alex-302 Sorry can you check this https://github.com/uBlockOrigin/uAssets/issues/20941#issuecomment-1858727690 ?

**Comment by Alex-302** [comment]
@stephenhawk8054 I saw. How to get links with this param? (`twitter.com/i/redirect?url=` and `twitter.com/GalatasaraySK/status/*?t=`) I don't see `t` parameter when I share links.
Maybe it is a tweet ID? Did you compare a link, made by different people for the same tweet?

**Comment by stephenhawk8054** [comment]
@Alex-302 The `t` param appears when you share via mobile app, for example `https://twitter.com/Anime_Frieren/status/1736256718492078196?t=xCRcCmAZ5pwlyIIGV7QHcA&s=19` and no, it's not tweet ID. The tweet ID is after `/status/`

About `redirect` link, you can test using this: https://github.com/uBlockOrigin/uAssets/issues/20941#issuecomment-1858698671 . Looks like it requires email notification so I cannot test yet.

**Comment by Alex-302** [comment]
@stephenhawk8054 What about `/^(?!.*(\/redirect\?url=)).*$/$removeparam=t,domain=twitter.com|x.com`?

**Comment by gorhill** [comment]
`/^(?!.*(\/redirect\?url=)).*$/` is not MV3-compatible though, it will be discarded. Also, no need for trailing `.*$`, this will match anything.

**Comment by Alex-302** [comment]
yes, but you have regexp rules:)

**Comment by gorhill** [comment]
`regexFilter` have to be RE2-compatible, and [RE2](https://github.com/google/re2/wiki/Syntax) does not support look-around assertions.

**Comment by Alex-302** [comment]
Hmm. Ok then. Added these rules https://github.com/uBlockOrigin/uAssets/issues/20941#issuecomment-1858727690

Or maybe better limit blocking rule by `twitter.com/*/status/` part?
@stephenhawk8054 @D4niloMR

**Comment by D4niloMR** [comment]
I think it's better to limit it, there's a link in my email to unsubscribe starting with `twitter.com/i/u?t=1&` 

I don't see any breakage with the parameter removed though.
