### ISSUE TITLE
bezpiecznedane.gov.pl: breakage

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uAssets#20955]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bezpiecznedane.gov.pl/`

### Category

breakage

### Description

Cookie consent hidden by "EasyList – Cookie Notices", overlay is left, blocks content.

Remove

	##div.cookie-popup
	##app-cookie-popup
	##.cookie-popup__content

or add
		
	bezpiecznedane.gov.pl##.cookie-popup-modal
	bezpiecznedane.gov.pl##.modal-backdrop

@ryanbr 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 120
filterset (summary):
 network: 105295
 cosmetic: 88119
 scriptlet: 22771
 html: 1126
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49046-135, never
  ublock-cookies-easylist: 600-0, never
 default:
  user-filters: 0-0, never
  ublock-filters: 36710-122, 1m
  ublock-badware: 7522-10, 1m
  ublock-privacy: 925-4, 1m
  ublock-unbreak: 2201-1, 1m
  ublock-quick-fixes: 272-63, 1m
  easylist: 75511-700, 1m
  easyprivacy: 33018-825, 1m
  urlhaus-1: 9795-0, now
  plowe-0: 3720-1, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 401 ms
 maxAssetCacheWait: 210 ms
popupPanel:
 blocked: 0
 extended:
  ##app-cookie-popup
  ##div.cookie-popup
  ##.cookie-popup__content
```
</details>

**Comment by mapx-** [comment]
already reported here: https://github.com/easylist/easylist/issues/17874

**Comment by krystian3w** [comment]
For me broken is `zaufaneopinie.ceneo.pl` - do not save my review about order processing and evaluation of the ordered equipment.

Unfortunately, I rarely buy at price to indicate the source and method of repair.
