### ISSUE TITLE
v.youku.com: breakage

### ISSUE THREAD

**Issue by 0x391F** [uBlockOrigin/uAssets#20954]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://v.youku.com/v_show/id_XMTU0MDM0MzQ4MA==.html`

### Category

breakage

### Description

Video in this website couldn't load, unless disable uBlock Origin

### Other extensions used

ClearURLs, Decentraleyes,NoScript

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 274635
 cosmetic: 101019
 scriptlet: 36268
 html: 1116
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80382-5686, now
  adguard-mobile: 8774-101, 2m
  adguard-spyware-url: 1344-93, 5m
  adguard-spyware: 74871-628, 5m
  block-lan: 55-0, 6m
  curben-phishing: 78508-33, 7m
 default:
  user-filters: 0-0, never
  ublock-filters: 36704-200, now
  ublock-badware: 7522-10, 1m
  ublock-privacy: 873-4, 1m
  ublock-unbreak: 2200-2, 1m
  ublock-quick-fixes: 213-3, 1m
  easylist: 75511-2375, 3m
  easyprivacy: 33018-16893, 6m
  urlhaus-1: 9980-0, 7m
  plowe-0: 3720-1, 7m
  CHN-0: 25888-165, 7m
filterset (user): [empty]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 702 ms (selfie)
 maxAssetCacheWait: 305 ms
popupPanel:
 blocked: 53
 network:
  youku.com: 3
  alicdn.com: 1
  cibntv.net: 1
  mmstat.com: 47
  taobao.com: 1
 extended:
  ##.advertise-layer
  ##div[data-adext]
  ##.ad-wrap
  ##+js(set-constant, Object.prototype._adData, {})
  ##+js(adjust-setTimeout, e-, , 0.02)
  ##+js(adjust-setTimeout, r--, , 0.02)
  ##+js(adjust-setTimeout, , , 0)
```
</details>

**Comment by 0x391F** [comment]
You may need to click the video element to play after about 15s Ads.

**Comment by gorhill** [comment]
Unable to reproduce with default settings/lists. Please test with only default lists.

**Comment by gorhill** [comment]
I think uBO's filter `||cibntv.net/youku/*$media,redirect=noopmp3-0.1s,domain=youku.com` may interfere negatively. To confirm can you try:

    @@||cibntv.net/youku/$media,redirect-rule=noopmp3-0.1s,from=youku.com

**Comment by mapx-** [comment]
The issue seems to be due to a cosmetic filter, try adding & test:

`v.youku.com#@#.advertise-layer`

**Comment by gorhill** [comment]
On my side, if I badfilter both redirect rules, I just need one click on the player for it to play:

    ||cibntv.net/youku/$media,redirect-rule=noopmp3-0.1s,from=youku.com,badfilter
    ||cibntv.net/youku/*.mp4?$media,important,redirect-rule=noop-1s.mp4,from=v.youku.com,badfilter

If I add only `v.youku.com#@#.advertise-layer` without the bad filters, it won't play, it's just a static image.

**Comment by mapx-** [comment]
click that image, should start the stuff

**Comment by mapx-** [comment]
@AdamWR has no issue, so .. it's a uBO filter or different behaviour

**Comment by gorhill** [comment]
I do click, it doesn't start.

**Comment by gorhill** [comment]
Does it work on your side with just the two badfilters above?

**Comment by gorhill** [comment]
I get an ad layer on my side with AdGuard + Chinese list:

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/b193eace-ed20-4b50-b314-646223a0bc54)

With uBO + Chinese list + the two badfilters, I just need to click once and all is clean.

**Comment by mapx-** [comment]
yes, working

**Comment by mapx-** [comment]
yes, me too, playing fine after clicking that "播 放" (="Play")

**Comment by gorhill** [comment]
Replacing only our filter with the one below I can make it work:

    ||cibntv.net/youku/$media,important,redirect=empty,from=youku.com
