### ISSUE TITLE
fplstatistics.co.uk: detection

### ISSUE THREAD

**Issue by gaowq1994** [uBlockOrigin/uAssets#20958]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.fplstatistics.co.uk/`

### Category

breakage

### Description

FPL price change table cannot be viewed when uBlock Origin is enabled

### Other extensions used

Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-11-30 002444](https://github.com/uBlockOrigin/uAssets/assets/18278289/66d4b382-3d24-4ea2-8dda-73b5f3de4d65)
![Screenshot 2023-11-30 002428](https://github.com/uBlockOrigin/uAssets/assets/18278289/3f1e4e1f-3105-4c40-ba6e-c78d4cc113ef)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 303333
 cosmetic: 252719
 scriptlet: 47728
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75584-120, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 94828-21845, now
  https://winhelp2002.mvps.org/hosts.txt: 8729-0, now
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, now
  CHN-0: 25895-147, now
  adguard-generic: 80404-579, now
  adguard-mobile: 8775-113, now
  adguard-social: 22063-1619, now
  adguard-spyware: 74928-1599, now
  adguard-spyware-url: 1344-5, now
  block-lan: 55-0, now
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 75514-2174, 13m
  easyprivacy: 33018-16717, 13m
  plowe-0: 3720-1729, now
  ublock-badware: 7518-330, 13m
  ublock-filters: 35831-4294, 13m
  ublock-privacy: 931-383, 13m
  ublock-quick-fixes: 271-135, 13m
  ublock-unbreak: 2155-148, 13m
  urlhaus-1: 9795-1, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 610 ms (selfie)
 maxAssetCacheWait: 386 ms
popupPanel:
 blocked: 6
 network:
  googlesyndication.com: 4
  paypalobjects.com: 2
 extended:
  ##ins.adsbygoogle
  ##div[style^="position: relative; TOP:"] a[target="_blank"] > im…
```
</details>

**Comment by mapx-** [comment]
I need too (otherwise clicking "prices" does not work)

`@@||fundingchoicesmessages.google.com^$script,domain=fplstatistics.co.uk`

**Comment by mapx-** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/509f2356-7df3-4ce8-84a8-af8f7ac2f395)

**Comment by gaowq1994** [comment]
Works now, thanks!
![image](https://github.com/uBlockOrigin/uAssets/assets/18278289/3c1fe155-5e6b-4329-b7b5-397ab2a5d452)

**Comment by Omega-6** [comment]
@ryanbr ads in sidebars

```
fplstatistics.co.uk##[href="https://hostinguk.net/web-hosting"]
fplstatistics.co.uk##[href="https://fantasyfootballhub.co.uk/join/"]
fplstatistics.co.uk##[href^="https://betterfpl.com/"]
```
