### ISSUE TITLE
[nsfw] upornia.com: breakage

### ISSUE THREAD

**Issue by taway2023** [uBlockOrigin/uAssets#20968]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://upornia.com/videos/3425889/valerie-kay-wants-your-dick2/`

### Category

breakage

### Description

cannot start/play video when ublock is active, turn off ublock and refresh and video play controls appear and video can be played.

### Other extensions used

Read Aloud: A Text to Speech Voice Reader > not inuse when problem occurs

ExpressVPN: VPN proxy for a better internet (disabled)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 103470
 cosmetic: 43995
 scriptlet: 19216
 html: 1127
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36725-121, 11m
  ublock-badware: 7527-10, 11m
  ublock-privacy: 925-4, 11m
  ublock-unbreak: 2201-1, 12m
  ublock-quick-fixes: 274-63, 12m
  easylist: 75551-698, 12m
  easyprivacy: 33021-735, 12m
  urlhaus-1: 9645-0, 12m
  plowe-0: 3720-1, 12m
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2538 ms
 maxAssetCacheWait: 40 ms
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 2
  nv7s.com: 3
 extended:
  ##.video-videos-slider
  ##a[href^="https://clickadilla.com/"]
  ##+js(abort-current-script, adver)
```
</details>

**Comment by okiehsch** [comment]
Video should work now if you update the `uBO-unbreak` list.

**Comment by BlazeFTL** [comment]
@okiehsch Whitelist Not Really Needed
I Get Big Blank Spaces Too
```
upornia.com##+js(rmnt, script, /popunder|isAdBlock|admvn.src/i)
upornia.com##section:not(:empty)
upornia.com##.underplayer:style(min-height: initial !important;)

**Comment by okiehsch** [comment]
Thx.

**Comment by BlazeFTL** [comment]
Is There A Pre Roll Ads ?
Or Its Just 46 Sec Added With Video

**Comment by okiehsch** [comment]
It's part of the video.
