### ISSUE TITLE
reddit.com: breakage

### ISSUE THREAD

**Issue by Afr0ninjA42** [uBlockOrigin/uAssets#20961]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.reddit.com/r/all/`

### Category

breakage

### Description

When scrolling through reddit, when it gets to where an ad would be, it shows a "something went wrong" message where the ad should be and won't allow you to scroll any further.  

### Other extensions used

1pass, honey, retailmenot

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="994" alt="Screenshot 2023-11-29 141939" src="https://github.com/uBlockOrigin/uAssets/assets/152436542/6edbf6ec-3f25-455f-b250-630226eb7165">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103939
 cosmetic: 45535
 scriptlet: 23503
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-thirdparty_social: 69-0, now
  ublock-annoyances: 5918-9, now
 default:
  user-filters: 0-0, never
  easylist: 75530-16, 10m
  easyprivacy: 33020-64, 10m
  plowe-0: 3720-1082, 10m
  ublock-badware: 7518-137, 10m
  ublock-filters: 35841-154, 10m
  ublock-privacy: 931-11, 10m
  ublock-quick-fixes: 271-133, 10m
  ublock-unbreak: 2150-33, 9m
  urlhaus-1: 9795-0, 9m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 756 ms
 maxAssetCacheWait: 5 ms
popupPanel:
 blocked: 18
 network:
  reddit.com: 7
  ad-delivery.net: 1
  redditmedia.com: 1
  redditstatic.com: 9
 extended:
  ##.promotedlink:not([style^="height: 1px;"])
  ##[id^="t3"].promotedlink:upward(.rpBJOHq2PR60pnwJlUyP0 > div)
  ##+js(replace-node-text, script, outboundUrl, outbound)
  ##+js(json-prune, data.*.elements.edges.[].node.outboundLink)
  ##+js(json-prune, data.children.[].data.outbound_link)
  ##+js(abort-on-property-write, STICKY_CANARY)
```
</details>

**Comment by D4niloMR** [comment]
> I get that error even disabling uBO in chrome.

Same here.

**Comment by Afr0ninjA42** [comment]
If I disable and refresh the page with chrome after uBO refreshes, reddit works as expected.  It shows the adds that are in the feed with the other posts.

**Comment by Afr0ninjA42** [comment]
<img width="986" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/152436542/cf8041a9-97ad-4d46-9e46-18a88ed720fe">

**Comment by JobcenterTycoon** [comment]
I also get a error even with uBO off. Works fine when im logged out.

**Comment by Afr0ninjA42** [comment]
I'm messing with it more...  Looks like /popular works okay...  If I go to /all, now it won't display anything but the error unless I disable uBO completely in chrome.  I'll try logging out and see if that helps.

**Comment by Afr0ninjA42** [comment]
Confirmed.  If I logout of my reddit account, it appears to work without issue.  Will do that as a workaround for time being.

**Comment by mdizo** [comment]
In case anyone else runs into this issue and wants to stay logged in, use https://sh.reddit.com

**Comment by stephenhawk8054** [comment]
> I'm messing with it more...  Looks like /popular works okay...  If I go to /all, now it won't display anything but the error unless I disable uBO completely in chrome.  I'll try logging out and see if that helps.

You mean /all works if you turn off uBO, and when you turn on again, it shows error?

**Comment by Afr0ninjA42** [comment]
> > I'm messing with it more...  Looks like /popular works okay...  If I go to /all, now it won't display anything but the error unless I disable uBO completely in chrome.  I'll try logging out and see if that helps.
> 
> You mean /all works if you turn off uBO, and when you turn on uBO again, it shows error?

I had to actually disable it in Chrome to get it to work again.  Enabling it breaks it.

**Comment by Afr0ninjA42** [comment]
> In case anyone else runs into this issue and wants to stay logged in, use `https://sh.reddit.com`

This appears to work great!

**Comment by stephenhawk8054** [comment]
I turned off all extensions in chromium, and it still shows error

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/d60bad6d-a94a-494f-a38b-f2970cceb859)

**Comment by Afr0ninjA42** [comment]
> @Afr0ninjA42 Can you record how it looks like when you disable and enable uBO?

I'm now seeing the same behavior you posted after this.  But I'm also seeing something new.  If I open a new tab I start off at "home" it's fine, if I click on "all" I get the following.   If I have an existing tab and enable/disable; it appears to just do what you're posting.

<img width="989" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/152436542/8c4e7d19-7a50-4959-9f50-eb19ee5f7858">

**Comment by Afr0ninjA42** [comment]
Refreshing the above post gets me this:

<img width="989" alt="image" src="https://github.com/uBlockOrigin/uAssets/assets/152436542/a9c516cc-a297-446d-b24c-ac42ec8110fb">

**Comment by Afr0ninjA42** [comment]
Using https://sh.reddit.com/r/all/ as suggested earlier appears to be working fine.

**Comment by stephenhawk8054** [comment]
> I'm now seeing the same behavior you posted after this. But I'm also seeing something new. If I open a new tab I start off at "home" it's fine, if I click on "all" I get the following. If I have an existing tab and enable/disable; it appears to just do what you're posting.

Well, same thing happens to me when all extensions are turned off too. So it's reddit issue in general, not related to uBO any more.
