### ISSUE TITLE
twitter.com: breakage

### ISSUE THREAD

**Issue by learn2reid** [uBlockOrigin/uAssets#20963]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://twitter.com/kevinjpowell/status/1564976598734016512?lang=bg`

### Category

breakage

### Description

Embedded YouTube vids will not play

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 287123
 cosmetic: 150930
 scriptlet: 31276
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75695-120, now
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, now
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-0, now
  https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/.input_sources/hacked-malware-websites.txt: 20096-3, now
  adguard-spyware: 74934-177, now
  adguard-spyware-url: 1338-5, now
  curben-phishing: 78686-25, now
  dpollock-0: 11584-190, now
  fanboy-cookiemonster: 49046-3805, now
  ublock-annoyances: 5919-195, now
  ublock-cookies-easylist: 601-601, 4m
 default:
  user-filters: 58-1, never
  easylist: 75551-364, now
  easyprivacy: 33020-16397, now
  plowe-0: 3720-1523, now
  ublock-badware: 7518-149, now
  ublock-filters: 35842-560, now
  ublock-privacy: 931-381, now
  ublock-quick-fixes: 271-133, now
  ublock-unbreak: 2156-85, now
  urlhaus-1: 9795-1, now
filterset (user): [array of 59 redacted]
trustedset:
 added: [array of 176 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2002 ms (selfie)
 maxAssetCacheWait: 586 ms
popupPanel:
 blocked: 44
 network:
  twitter.com: 29
  ads-twitter.com: 1
  doubleclick.net: 2
  google-analytics.com: 1
  google.com: 6
  youtube.com: 5
 extended:
  ##div[data-testid="trend"]:has(path[d$="10H8.996V8h7v7z"])
  ##[data-testid="trend"]:has-text(/Promoted|Gesponsert|Promociona…
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
  ##+js(abort-current-script, eval, replace)
  ##.ytp-cards-teaser
  ##.ytp-pause-overlay
  ##.ytp-paid-content-overlay
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by D4niloMR** [comment]
On chromium the video loads. Firefox don't allow the embed player:
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/89eafcc4-da38-4bca-9692-4f82f47ce7c4)
