### ISSUE TITLE
sports.iqiyi.com: breakage

### ISSUE THREAD

**Issue by lazebird** [uBlockOrigin/uAssets#20976]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sports.iqiyi.com/resource/pcw/play/12bt9ld6iog`

### Category

breakage

### Description

when enable ublock, the video stopped on loading page with black video screen

### Other extensions used

tampermonkey and others, but if i disable ublock, it works

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 118365
 cosmetic: 54413
 scriptlet: 19583
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CHN-0: 25913-138, now
  easylist: 75551-26, now
  easyprivacy: 33031-77, now
  plowe-0: 3784-1138, now
  ublock-badware: 7523-137, now
  ublock-filters: 35865-170, now
  ublock-privacy: 931-11, now
  ublock-quick-fixes: 242-112, now
  ublock-unbreak: 2156-33, now
  urlhaus-1: 9355-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 615 ms (selfie)
 maxAssetCacheWait: 221 ms
popupPanel:
 blocked: 14
 network:
  qy.net: 14
 extended:
  ##+js(set-constant, Object.prototype.parseXML, noopFunc)
  ##+js(set-constant, Object.prototype.blackscreenDuration, 1)
  ##+js(set-constant, QiyiPlayerProphetData.a.data, {})
```
</details>

**Comment by mapx-** [comment]
`Due to copyright restrictions, this video cannot be viewed in your region.`

@cjx82630
could you take a look ?

**Comment by mapx-** [comment]
@lazebird  see if helps

`iqiyi.com#@#+js()`

**Comment by cjx82630** [comment]
After 1 second in black screen, the vid played. No issue.
