### ISSUE TITLE
nyaa.land: ads

### ISSUE THREAD

**Issue by MXX9** [uBlockOrigin/uAssets#20979]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://nyaa.land/`

### Category

ads

### Description

an banner ad is showing

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 103221
 cosmetic: 44014
 scriptlet: 19223
 html: 1126
listset (total-discarded, last-updated):
 default:
  user-filters: 12-0, never
  ublock-filters: 36748-122, now
  ublock-badware: 7535-11, now
  ublock-privacy: 925-4, now
  ublock-unbreak: 2202-1, now
  ublock-quick-fixes: 278-63, 46m
  easylist: 75551-698, now
  easyprivacy: 33031-789, now
  urlhaus-1: 9355-0, 46m
  plowe-0: 3784-1, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 453 ms (selfie)
 maxAssetCacheWait: 270 ms
popupPanel:
 blocked: 1
 network:
  nyaa.land: 1
```
</details>

**Comment by mapx-** [comment]
add

`nyaa.land##[href="https://privateiptvaccess.com"]`

@ryanbr
