### ISSUE TITLE
freemodapp.com: detection

### ISSUE THREAD

**Issue by ItsProfessional** [uBlockOrigin/uAssets#20978]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://freemodapp.com/?lid=fYrPG5&pid=464893&plid=1&vid=230568810`

### Description

Suggested filter:
```adb
freemodapp.com##+js(aopw, AdBDetected)
```

<details>
<summary>Detection script</summary>

```js
var AdbModel = document.getElementById("AdbModel");

(function detectWithFakeAdsDiv() {

    let fakeAd = document.createElement("div");
    fakeAd.className =
        "textads banner-ads banner_ads ad-unit ad-zone ad-space adsbox";
    fakeAd.style.height = "1px";

    document.body.appendChild(fakeAd);
    let x_width = fakeAd.offsetHeight;

    if (x_width) {
        setTimeout(removefakeAd, 300);
    } else {
        AdBDetected();
    }

    function removefakeAd() {
        fakeAd.remove();
    }

})();

(async function () {
    let adBlockEnabled = false;
    const googleAdUrl = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";
    const gplinksjs = "https://gplinks.in/track/js/main.js";

    try {
        await fetch(new Request(googleAdUrl)).catch(
            (_) => (adBlockEnabled = true)
        );
        await fetch(new Request(gplinksjs)).catch(
            (_) => (adBlockEnabled = true)
        );
    } catch (e) {
        adBlockEnabled = true;
    } finally {
        if (adBlockEnabled) {
            AdBDetected();
        }
    }
})();


function isBrave() {
    if (window.navigator.brave != undefined) {
        if (window.navigator.brave.isBrave.name == "isBrave") {
            AdBDetected();
            return true;
        } else {
            return false;
        }
    } else {
        return false;
    }
}
isBrave();


function AdBDetected() {
    AdbModel.style.visibility = "visible";
}

function AdbPageReload() {
    location.reload();
}
```

</details>

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63961221/fb0a684c-e129-4aea-8dea-ba74fc1c9169)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 190235
 cosmetic: 116866
 scriptlet: 26173
 html: 1319
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4191-95, 5d.3h.2m
  easylist-chat: 165-0, 5d.3h.2m
  fanboy-cookiemonster: 49037-281, 5d.3h.2m
  ublock-cookies-easylist: 577-0, 5d.3h.2m
  easylist-newsletters: 6660-13, 5d.3h.2m
  easylist-notifications: 2877-4, 5d.3h.2m
  fanboy-social: 16161-7, 5d.3h.2m
  ublock-annoyances: 5852-608, 5d.3h.2m
 default:
  user-filters: 0-0, never
  ublock-filters: 36746-110, 14m
  ublock-badware: 7527-10, 14m
  ublock-privacy: 925-4, 14m
  ublock-unbreak: 2202-2, 14m
  ublock-quick-fixes: 242-63, 14m
  easylist: 75551-730, 3h.52m
  adguard-spyware-url: 1344-93, 2d.2h.14m
  easyprivacy: 33031-831, 3h.53m
  urlhaus-1: 9795-0, 22h.47m
  curben-phishing: 78686-33, 22h.47m
  plowe-0: 3719-1, 6d.4h.13m
  LegitimateURLShortener: 2498-157, 2h.52m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 254 ms (selfie)
 maxAssetCacheWait: 183 ms
popupPanel:
 blocked: 7
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 3
 extended:
  ##a[title="Back to top"]
  ###back-top
```
</details>

**Comment by mapx-** [comment]
which is the shortener link ?

**Comment by mapx-** [comment]
> which is the shortener link ?
