### ISSUE TITLE
alexsportz.online: detection

### ISSUE THREAD

**Issue by ItsProfessional** [uBlockOrigin/uAssets#20972]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://alexsportz.online/HD/spe-38.php`

### Description

Detection.

Suggested filters:
* anti-adblock (can't use `no-fetch-if`, the script checks if the `url` value of the returned promise is an empty string)
```adb
alexsportz.online##+js(acs, fetch, googlesyndication)
```
* anti-devtools
```adb
alexsportz.online##+js(noeval-if, debugger)
```

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63961221/574d1967-4055-488c-b03c-9a2850c34fec)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 190294
 cosmetic: 116827
 scriptlet: 26179
 html: 1318
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4191-95, 4d.21h.10m
  easylist-chat: 165-0, 4d.21h.10m
  fanboy-cookiemonster: 49037-281, 4d.21h.10m
  ublock-cookies-easylist: 577-0, 4d.21h.10m
  easylist-newsletters: 6660-13, 4d.21h.10m
  easylist-notifications: 2877-4, 4d.21h.10m
  fanboy-social: 16161-7, 4d.21h.10m
  ublock-annoyances: 5852-608, 4d.21h.10m
 default:
  user-filters: 0-0, never
  ublock-filters: 36703-124, 1d.4h.59m
  ublock-badware: 7522-10, 1d.4h.59m
  ublock-privacy: 873-4, 1d.4h.59m
  ublock-unbreak: 2200-2, 1d.4h.59m
  ublock-quick-fixes: 274-6, 1h.10m
  easylist: 75665-731, 5d.22h.21m
  adguard-spyware-url: 1344-93, 1d.20h.22m
  easyprivacy: 32964-824, 5d.22h.21m
  urlhaus-1: 9795-0, 16h.55m
  curben-phishing: 78686-33, 16h.55m
  plowe-0: 3719-1, 5d.22h.21m
  LegitimateURLShortener: 2497-157, 23h.48m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 254 ms (selfie)
 maxAssetCacheWait: 183 ms
popupPanel:
 blocked: 6
 network:
  achcdn.com: 2
  histats.com: 1
  impactcutleryrecollect.com: 2
  waust.at: 1
 extended:
  ##+js(abort-on-property-write, _pop)
```
</details>

**Comment by okiehsch** [comment]
I thought that the playback error is because that stream is not live atm but I did not check if there are any working links.

**Comment by JobcenterTycoon** [comment]
@ghajini do you see `angossa.com` as a redirector to the player site? When i click on links on the start page i get redirected through the unblocked domain `angossa.com` to ads.

**Comment by JobcenterTycoon** [comment]
`angossa.com` is now blocked in `Peter Lowe’s Ad and tracking server list`
