### ISSUE TITLE
sagewater.com: detection

### ISSUE THREAD

**Issue by ItsProfessional** [uBlockOrigin/uAssets#20981]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://sagewater.com/services/services/washerdryer-retrofitting/`

### Description

Detection.

Suggested filter:
```adb
sagewater.com##+js(aeld, load, aoAdBlockDetected)
```

or, by setting the detected global var to false:
```adb
sagewater.com##+js(set, aoAdBlockDetected, false)
```

I'm not sure which filter fits more of uBO's principles.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63961221/cf640b5e-f0b7-457c-965f-dd2a93115146)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 190235
 cosmetic: 116866
 scriptlet: 26173
 html: 1319
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4191-95, 5d.3h.33m
  easylist-chat: 165-0, 5d.3h.33m
  fanboy-cookiemonster: 49037-178, 5d.3h.33m
  ublock-cookies-easylist: 577-0, 5d.3h.33m
  easylist-newsletters: 6660-13, 5d.3h.33m
  easylist-notifications: 2877-4, 5d.3h.33m
  fanboy-social: 16161-7, 5d.3h.33m
  ublock-annoyances: 5852-608, 5d.3h.33m
 default:
  user-filters: 0-0, never
  ublock-filters: 36746-122, 45m
  ublock-badware: 7527-10, 45m
  ublock-privacy: 925-4, 45m
  ublock-unbreak: 2202-2, 45m
  ublock-quick-fixes: 242-63, 45m
  easylist: 75551-730, 4h.23m
  adguard-spyware-url: 1344-93, 2d.2h.45m
  easyprivacy: 33031-922, 4h.24m
  urlhaus-1: 9795-0, 23h.18m
  curben-phishing: 78686-33, 23h.18m
  plowe-0: 3719-1, 6d.4h.44m
  LegitimateURLShortener: 2498-157, 3h.23m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
 trustedListPrefixes: ublock- user-
 updateAssetBypassBrowserCache: true
supportStats:
 allReadyAfter: 254 ms (selfie)
 maxAssetCacheWait: 183 ms
popupPanel:
 blocked: 9
 network:
  sagewater.com: 4
  addtoany.com: 2
  googletagmanager.com: 1
  licdn.com: 1
  oktopost.com: 1
```
</details>

**Comment by okiehsch** [comment]
I can't reproduce but I can see the anti adblock detection code in the source.
@ItsProfessional does the nag screen show up after every refresh?
I ask because if it only occurs once per browser session we fix such an issue in the annoyance list.

**Comment by okiehsch** [comment]
Ok, I can only invite you if your github account has 2FA enabled, is that the case?

**Comment by okiehsch** [comment]
I will send you an invite and if you accept you will have access to [team discussions](https://help.github.com/en/articles/about-team-discussions), so if you have any questions you can ask there.
