### ISSUE TITLE
moviepilot.de: ads

### ISSUE THREAD

**Issue by muellerarmin** [uBlockOrigin/uAssets#20985]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.moviepilot.de/`

### Category

ads

### Description

Multiple ads are inserted into the site despite having uBO on and up-to-date. I guess that the links for the ad-images (or the IDs for the surrounding containers) are randomized strings or hashes. Wildcard-blocking these URLs will also block non-ad-images.

### Other extensions used

'I don't care about cookies'

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105597
 cosmetic: 48794
 scriptlet: 19217
 html: 1126
listset (total-discarded, last-updated):
 default:
  user-filters: 19-1, never
  ublock-filters: 36745-115, 1h.39m
  ublock-badware: 7522-10, 1h.39m
  ublock-privacy: 925-4, now
  ublock-unbreak: 2202-0, 1h.39m
  easylist: 75583-702, now
  easyprivacy: 33031-798, now
  plowe-0: 3784-1, now
  DEU-0: 7174-3, now
  urlhaus-1: 9355-0, now
  ublock-quick-fixes: 242-64, now
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 56 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 938 ms (selfie)
 maxAssetCacheWait: 692 ms
popupPanel:
 blocked: 78
 network:
  moviepilot.de: 24
  360yield.com: 3
  adnxs.com: 4
  adsafeprotected.com: 2
  adscale.de: 2
  amazon-adsystem.com: 5
  criteo.com: 2
  criteo.net: 2
  getjad.io: 3
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  iocnt.net: 2
  lijit.com: 2
  openx.net: 4
  pbstck.com: 1
  pubmatic.com: 4
  relevant-digital.com: 1
  rlcdn.com: 3
  s-onetag.com: 1
  sentry.io: 1
  smartadserver.com: 3
  teads.tv: 3
  userreport.com: 1
  webcontentassessor.com: 1
 extended:
  ###dfp-interstitial
  ###dfp-header
  ###dfp-masthead
  ###dfp-mtf
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##div[data-google-query-id]
  #@#[id^="google_ads_iframe"]
  ##+js(no-setTimeout-if, .call(null), 10)
  ##+js(adjust-setTimeout, _0x, *)
  ##+js(no-xhr-if, doubleclick)
```
</details>

**Comment by okiehsch** [comment]
It's a Firefox only issue on my end, so
`moviepilot.de##^script:has-text(criteo.net/js/ld/publishertag.js)`
works fine for me.

**Comment by mapx-** [comment]
I get the ads in chrome without

`moviepilot.de##+js(rmnt, script, Promise)`

the exceptions were for some apparently video breakage

**Comment by okiehsch** [comment]
> the exceptions were for some apparently video breakage

With Chrome too?

**Comment by muellerarmin** [comment]
> test
> 
> ```
> moviepilot.de##+js(rmnt, script, Promise)
> @@||cdn.lib.getjad.io/library/$script,domain=moviepilot.de
> @@||c.amazon-adsystem.com/aax2/apstag.js$script,domain=moviepilot.de
> @@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=moviepilot.de
> ```

I've tested this and so far it works flawlessly. No broken videos (in Firefox; I didn't test Chrome). Thank you so much.

**Comment by punisher018** [comment]
I need this filter on my side. Otherwise videos stay on black screen.

@@@|cdn.lib.getjad.io^$script,domain=www.moviepilot.de

Also in firefox, if I have enhanced tracking protection turned on (default), I also need this.

www.moviepilot.de#@##dfp-mtf

Can you confirm?

**Comment by okiehsch** [comment]
> I need this filter on my side. Otherwise videos stay on black screen.

Can you give an example link of a broken video or do you mean all videos are broken on your end?

If it's the latter I can't reproduce.

**Comment by punisher018** [comment]
Sorry, i haven't enabled it. It's ok with it.
