### ISSUE TITLE
deezer.com: breakage

### ISSUE THREAD

**Issue by Robotic-Brain** [uBlockOrigin/uAssets#20986]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.deezer.com/en/`

### Description

When listening to music with a free account ads are properly blocked however the UI locks up waiting for the (non existent) ad to load/finish. A page refresh solves the problem and lets you listen to a few more songs until the next ad is scheduled.

When NoScript is enabled, i can see a blocked media element on the page when the ad is supposed to play.

Other deezer related issues talk about the Ad-block popup. This is a different symptom. The Popup does not show up.

### Other extensions used

NoScript

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/4038901/d8e16737-df75-4adc-9950-1e5c688c0de3)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105712
 cosmetic: 48778
 scriptlet: 19221
 html: 1127
listset (total-discarded, last-updated):
 added:
  DEU-0: 7174-3, 13m
 default:
  user-filters: 3-0, never
  ublock-filters: 36748-116, 13m
  ublock-badware: 7535-11, 13m
  ublock-privacy: 925-4, 13m
  ublock-unbreak: 2202-1, 13m
  ublock-quick-fixes: 242-63, 13m
  easylist: 75583-702, 13m
  easyprivacy: 33031-798, 13m
  urlhaus-1: 9460-0, 13m
  plowe-0: 3784-1, 13m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 626 ms (selfie)
 maxAssetCacheWait: 192 ms
popupPanel:
 blocked: 14
 network:
  adswizz.com: 4
  googletagmanager.com: 1
  hubvisor.io: 4
  sentry.io: 5
 extended:
  ##+js(no-setTimeout-if, Ads)
  ##+js(set-constant, smartLoaded, true)
```
</details>

**Comment by mapx-** [comment]
add and see if helps:

`*$media,domain=deezer.com,redirect-rule=noopmp3-0.1s`

**Comment by Robotic-Brain** [comment]
Thank you that works! However NoScript seems to interfere with it.
Is there a way to fix it, or do i have to define an exception in noscript?

**Comment by mapx-** [comment]
add an exception in NoScript

**Comment by Robotic-Brain** [comment]
FYI: whitelisting media from adsrvr.org is enough to fix it.
