### ISSUE TITLE
mediahope.ru: breakage

### ISSUE THREAD

**Issue by dhpro100** [uBlockOrigin/uAssets#20984]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mediahope.ru/video/`

### Category

breakage

### Description

The site has an iframe with `https://vk.com` and a stub in the form of an image, when clicked, an iframe is loaded and displayed on the page after it is fully loaded and the video is played, because autoplay is enabled.
But with the extension - autoplay is blocked and you have to click twice on the video to start the video.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 121110
 cosmetic: 65030
 scriptlet: 20722
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  RUS-0: 39952-9, now
  easylist: 75496-42, now
  easyprivacy: 33016-153, now
  plowe-0: 3720-1086, now
  ublock-badware: 7518-137, now
  ublock-filters: 35823-181, now
  ublock-privacy: 880-12, now
  ublock-quick-fixes: 221-80, now
  ublock-unbreak: 2154-32, now
  urlhaus-1: 9965-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 12 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 614 ms (selfie)
 maxAssetCacheWait: 188 ms
popupPanel:
 blocked: 8
 network:
  mail.ru: 4
  tns-counter.ru: 3
  yandex.ru: 1
 extended:
  ###system_msg
  ##+js(abort-on-property-read, Groups.showDisclaimer)
  ##+js(abort-on-property-read, PageBottomBanners)
  ##+js(abort-on-property-read, Unauthorized2)
  ##+js(href-sanitizer, a[href*="/away.php?"], ?to)
  ##+js(set-constant, noAdsAtAll, {})
```
</details>

**Comment by dhpro100** [comment]
> test
> 
> `||vk.com/video_ext.php?$frame,3p,removeparam=autoplay,badfilter`
> 
> @dimisa-RUAdList

Do I understand correctly that I need to add this code to the src iframe?
It was:
https://vk.com/video_ext.php?oid=124632307&id=456241390&hash=008c8573055e47fc&__ref=vk.admin_android&api_hash=17013799383ea855f01f60b39351_GEZDINRTGIZTANY&autoplay=1&hd=1
I did this:
https://vk.com/video_ext.php?$frame,3p,removeparam=autoplay,badfilter&oid=124632307&id=456241390&hash=008c8573055e47fc&__ref=vk.admin_android&api_hash=17013799383ea855f01f60b39351_GEZDINRTGIZTANY&autoplay=1&hd=1
And unfortunately, it didn't help.. Autoplay does not start..
If you insert it at the end of the link, it's the same, nothing.

**Comment by dhpro100** [comment]
> No .. open uBO dashboard (options), "my filters" tab, add that filter, click "apply changes", test again

Yes, it works for me. But I can also disable the extension on this page - this is not a problem. As the creator of this site, I am worried about the inconvenience for some users who have an extension.
There is no advertising here and there will not be, this is my personal website with a portfolio, and it is for a comfortable demonstration of the portfolio that I would like to turn on autoplay.

**Comment by dimisa-RUAdList** [comment]
I am studying this case. I'll comment a little later.

**Comment by dimisa-RUAdList** [comment]
The fact is that for users, the comfort is precisely turning off autoplay, and not activating it. At least this is true for any resource that is not a video hosting site (like YouTube).

Therefore, the RU AdList filter for uBlock Origin provides for disabling autoplay for all such cases, since uBlock Origin is not an ad blocker, but a blocker of unwanted content. The standard RU AdList filter for AdBlock or AdBlock Plus does not disable autoplay.

As far as I understand, the only reason you have to double-click the play button on your site is if you use a non-standard embedding method. In the vast majority of similar cases, disabling autoplay works correctly, for example: `https://news.mail.ru/economics/58831146/`

I added an exception so that the rule will not work on your site: https://github.com/easylist/ruadlist/commit/2309a3c17eb84b9a9ba740ba47308a8ac273940f

**Comment by dhpro100** [comment]
> The fact is that for users, the comfort is precisely turning off autoplay, and not activating it. At least this is true for any resource that is not a video hosting site (like YouTube).
> 
> Therefore, the RU AdList filter for uBlock Origin provides for disabling autoplay for all such cases, since uBlock Origin is not an ad blocker, but a blocker of unwanted content. The standard RU AdList filter for AdBlock or AdBlock Plus does not disable autoplay.
> 
> As far as I understand, the only reason you have to double-click the play button on your site is if you use a non-standard embedding method. In the vast majority of similar cases, disabling autoplay works correctly, for example: `https://news.mail.ru/economics/58831146/`
> 
> I added an exception so that the rule will not work on your site: [easylist/ruadlist@2309a3c](https://github.com/easylist/ruadlist/commit/2309a3c17eb84b9a9ba740ba47308a8ac273940f)

Thank you very much! Yes, the embedding method is unusual, using a stub, due to the number of iframes on the page and performance problems from loading a large number of iframes.
Thanks for adding an exception!
