### ISSUE TITLE
mouse-sensitivity.com: breakage

### ISSUE THREAD

**Issue by DPIWizard** [uBlockOrigin/uAssets#20993]
### Prerequisites

- [x] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.mouse-sensitivity.com/`

### Description

Clicking the purple share button should bring up a box where you can create a link to share the settings for the calculator, but this is being blocked by both the AdGuard - Social Media and EasyList - Social Widgets, probably because it mistakes it for a social media sharing button.

### Other extensions used

None.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 117
filterset (summary):
 network: 196404
 cosmetic: 195833
 scriptlet: 30405
 html: 1324
listset (total-discarded, last-updated):
 added:
  adguard-social: 22064-1619, never
  adguard-cookies: 28231-62, 21m
  ublock-cookies-adguard: 612-0, 21m
  adguard-popup-overlays: 26485-779, 19m
  adguard-mobile-app-banners: 4807-1069, 26m
  adguard-other-annoyances: 13995-318, 25m
  adguard-widgets: 2352-1, 20m
  fanboy-thirdparty_social: 68-0, 20m
  easylist-annoyances: 4221-120, 19m
  easylist-chat: 166-12, 19m
  fanboy-cookiemonster: 49072-3871, 19m
  ublock-cookies-easylist: 612-612, 19m
  [4 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36749-449, 31m
  ublock-badware: 7535-11, 31m
  ublock-privacy: 925-4, 31m
  ublock-unbreak: 2202-2, 31m
  ublock-quick-fixes: 242-63, 31m
  easylist: 75590-779, 31m
  adguard-spyware-url: 1342-92, 31m
  easyprivacy: 33031-879, 31m
  urlhaus-1: 9460-0, 31m
  curben-phishing: 78340-27, 31m
  plowe-0: 3784-1, 31m
  LegitimateURLShortener: 2498-157, 31m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 987 ms
 maxAssetCacheWait: 593 ms
```
</details>

**Comment by krystian3w** [comment]
Fanboy social media deliberately hiding share button.

**Comment by Alex-302** [comment]
Fixed in AdGuard Social Media filter
