### ISSUE TITLE
totalcsgo.com: ads

### ISSUE THREAD

**Issue by Lordiun** [uBlockOrigin/uAssets#20992]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://totalcsgo.com/`

### Category

ads

### Description

multiple gambling site ads

### Other extensions used

none

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 201171
 cosmetic: 115255
 scriptlet: 28030
 html: 1344
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2498-1, 32m
  https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt: 59522-7617, 32m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1105-1, 31m
  adguard-spyware-url: 1342-200, 31m
  block-lan: 55-0, 31m
  fanboy-cookiemonster: 49072-3898, 31m
  ublock-annoyances: 5901-10, 31m
  adguard-spyware: 74929-20901, 31m
  adguard-cookies: 28230-61, 31m
 default:
  user-filters: 58-0, never
  ublock-filters: 36785-245, 31m
  ublock-badware: 7535-11, 31m
  ublock-privacy: 925-52, 31m
  ublock-unbreak: 2202-2, 31m
  ublock-quick-fixes: 242-63, 31m
  easylist: 75583-16973, 31m
  easyprivacy: 33031-795, 31m
  urlhaus-1: 9460-0, 31m
  plowe-0: 3784-1, 31m
  SWE-1: 4544-6, 31m
filterset (user): [array of 56 redacted]
trustedset:
 added: [array of 5 redacted]
hostRuleset:
 added: [array of 13 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11885 ms (selfie)
 maxAssetCacheWait: 276 ms
popupPanel:
 blocked: 11
 network:
  dantoo.dev: 5
  google.com: 5
  googletagmanager.com: 1
 extended:
  ##iframe[name="googlefcPresent"]
  ##+js(remove-node-text, script, /adconfig/i)
```
</details>

**Comment by mapx-** [comment]
add & test, see if something is broken

```
totalcsgo.com##+js(aeld, , /mechanism/)
totalcsgo.com##[style*="desktop-url"]:remove()
totalcsgo.com##[href^="https://link.totalcsgo.com"][target="_blank"]
```

**Comment by Lordiun** [comment]
Thank you! Looks a lot better, although this rule creates some breakage on the Giveaways page and the Skin Trading Sites page. You also still get redirected to the site if you click anywhere on the sides if that's possible to fix
```
totalcsgo.com##[href^="https://link.totalcsgo.com"][target="_blank"]
```

**Comment by mapx-** [comment]
I need the links for `Giveaways page and the Skin Trading Sites page`

Still redirection ? every page or only some page ?

**Comment by mapx-** [comment]
ok, I removed that filter.

**Comment by Lordiun** [comment]
Links are here https://totalcsgo.com/skins/giveaways and https://totalcsgo.com/skins/skin-trading-sites on the giveaways page the View Details button disappears.

Expected behavior
![bild](https://github.com/uBlockOrigin/uAssets/assets/96659178/d79f6740-8434-40a0-957b-93008984acc1)

Actual behavior
![bild](https://github.com/uBlockOrigin/uAssets/assets/96659178/3e716615-8334-48b5-992a-7e812d72cdbe)


And on the Skin Trading Sites page the different logos for the corresponding sites disappears.

Expected behavior
![bild](https://github.com/uBlockOrigin/uAssets/assets/96659178/3ce0a004-7a3d-46d4-87ee-994067a7fa30)

Actual behavior
![bild](https://github.com/uBlockOrigin/uAssets/assets/96659178/896e72dd-768a-448f-9bd9-520b7c0eff65)

The redirect is on every page whenever you click on the sides

**Comment by mapx-** [comment]
remove the filters above from "my filters", wait 5-10 min then update `uBlock filters – Ads` and test again

**Comment by Lordiun** [comment]
Looks perfect to me now mate, thank you for the help! Doing gods work
