### ISSUE TITLE
github.io: nuisance

### ISSUE THREAD

**Issue by PhoenixFossGR** [uBlockOrigin/uAssets#21006]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://globox1997.github.io/wiki/`
`https://gillian-guide.github.io/` (this one has been patched by EasyList Cookie recently, a filter that's not enabled by default in uBO)

### Description

It appears that there is a cookie notice present on numerous GitHub.io Wiki pages. Is it possible to identify the specific name or identifier associated with this notice? This way, a universal filter could be created to block it across all GitHub.io pages, or any other websites using it, eliminating the need to create individual filters for each website/page. I have added two links with the same cookie notice present.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot from 2023-12-02 01-19-20](https://github.com/uBlockOrigin/uAssets/assets/123986260/23ece1d5-5fb1-4c2c-9d11-3f719c968ddf)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 428211
 cosmetic: 242874
 scriptlet: 47155
 html: 1320
listset (total-discarded, last-updated):
 added:
  https://big.oisd.nl/: 209322-62426, 4h.38m
  adguard-generic: 80388-7367, 2d.12h.14m
  adguard-mobile: 8775-113, 2d.12h.14m
  adguard-spyware-url: 1344-94, 2d.12h.14m
  adguard-spyware: 74874-16994, 2d.12h.15m
  block-lan: 54-0, 19d.3h.44m
  curben-phishing: 78340-28, 13h.2m
  adguard-social: 22064-872, 2d.12h.15m
  adguard-cookies: 28205-64, 2d.12h.15m
  adguard-popup-overlays: 26355-1626, 2d.12h.15m
  adguard-mobile-app-banners: 4807-1069, 2d.12h.16m
  adguard-other-annoyances: 13838-316, 2d.12h.16m
  [13 lists not shown]: [too many]
 default:
  user-filters: 18-0, never
  ublock-filters: 36789-399, 1h.47m
  ublock-badware: 7542-11, 1h.47m
  ublock-privacy: 860-4, 4d.15h.29m
  ublock-unbreak: 2202-2, 1h.47m
  ublock-quick-fixes: 265-7, 1h.47m
  easylist: 75590-1003, 2h.47m
  easyprivacy: 33033-918, 2h.47m
  urlhaus-1: 9460-0, 13h.2m
  plowe-0: 3720-1, 6d.3h.32m
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 3 redacted]
hostRuleset:
 added: [array of 23 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1691 ms (selfie)
 maxAssetCacheWait: 1132 ms
popupPanel:
 blocked: 0

```
</details>

**Comment by mapx-** [comment]
add

`github.io###__consent`

**Comment by SandeMC** [comment]
"It appears that there is a cookie notice present on numerous GitHub.io Wiki pages"
It's coming from Material Mkdocs, not github.io, FYI.

**Comment by SandeMC** [comment]
Material Mkdocs is open source, and so is my website; I don't know other mkdown websites, but you can make yourself a dummy website with nothing but the prompt.
- [Getting started](https://squidfunk.github.io/mkdocs-material/getting-started/)
- [Creating a consent message](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/?h=consent#cookie-consent)

**Comment by SandeMC** [comment]
I suggest to re-open the issue and rename it to something related to Material Mkdocs, also.

**Comment by mapx-** [comment]
Do you know other sites using the same approach ?

**Comment by SandeMC** [comment]
It's affected by anything that includes a Material Mkdocs consent prompt, and I have left links to creating a dummy Material docs site with that said prompt. It's generic and used by a lot of sites, although I do not have any on my hands rn. Would be efficient to detect the prompt itself.

**Comment by mapx-** [comment]
ELC maintainer prefers hiding it only for the domains he can test.

**Comment by SandeMC** [comment]
[mkdocs.zip](https://github.com/uBlockOrigin/uAssets/files/13540297/mkdocs.zip)
Dummy mkdocs material website with nothing but the consent prompt. The actual site contents are in `site`. If needed.
