### ISSUE TITLE
yts.am

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#2100]
`https://yts.am/browse-movies`

When uBlock Origin is enabled, the website doesn't show the caret in any of the text fields like the search bar, and doesn't let you type any text in them. Is there a way to fix that? Thanks.

![yts am](https://user-images.githubusercontent.com/35790889/39333712-df0bdf2e-4979-11e8-857f-279a52a4e2b8.jpg)

Waterfox 56.1.0 (64-bit)
uBlock Origin 1.16.2

**Comment by okiehsch** [comment]
Does
`yts.am##script:inject(abort-current-inline-script.js, atob, tabunder)`
fix your issue?

**Comment by IoanPaleru** [comment]
Yes it does, now everything works properly. uBlock Origin is an excellent program by the way, so keep up the great work! Thanks a lot, and have a good day.
