### ISSUE TITLE
cheersandgears.com: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21005]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cheersandgears.com/`

### Category

detection

### Description

The site site shows an "Ad Block Detected" message.

This filter seems to work to remove the detection.
`cheersandgears.com##+js(acs, jQuery, dismissAdBlock)`

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1440" alt="Screenshot 2023-12-01 at 5 21 33 PM" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/73475521-6556-40dc-aae2-bf1026d5c1c8">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103754
 cosmetic: 45583
 scriptlet: 23548
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5946-10, now
 default:
  user-filters: 56-2, never
  easylist: 75598-16, now
  easyprivacy: 33034-64, now
  plowe-0: 3779-1136, now
  ublock-badware: 7538-138, now
  ublock-filters: 35893-158, now
  ublock-privacy: 931-11, now
  ublock-quick-fixes: 265-116, now
  ublock-unbreak: 2156-33, now
  urlhaus-1: 9520-0, now
filterset (user): [array of 57 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 123 ms (selfie)
 maxAssetCacheWait: 54 ms
popupPanel:
 blocked: 5
 network:
  cloudflareinsights.com: 1
  facebook.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by D4niloMR** [comment]
@mapx- this is a soft anti adblock

**Comment by mapx-** [comment]
Elegant ? I prefer the filters to be more generic: in this case if "they" will replace `googlesyndication` by something else you'll have to modify the filter.
There are no other fetch in the page for now.

**Comment by mapx-** [comment]
In all cases they can circumvent it. When it will happen we can try other fixes.
