### ISSUE TITLE
investigationdiscovery.com: ads

### ISSUE THREAD

**Issue by ChuckStriker** [uBlockOrigin/uAssets#21007]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.investigationdiscovery.com`

### Description

3 minute ads playing several times during show. I have a paid subscription thru my cable company to allow me to watch shows on ID TV (investigation discovery). I still have to suffer thru repetitive ads 4 or 5 times per episode.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 103367
 cosmetic: 43998
 scriptlet: 19225
 html: 1126
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36748-209, 22h.12m
  ublock-badware: 7535-11, 22h.12m
  ublock-privacy: 925-4, 22h.12m
  ublock-unbreak: 2202-1, 22h.12m
  ublock-quick-fixes: 266-65, 47m
  easylist: 75583-590, 22h.12m
  easyprivacy: 33031-789, 22h.12m
  urlhaus-1: 9460-0, 22h.13m
  plowe-0: 3784-1, 22h.13m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 252 ms (selfie)
 maxAssetCacheWait: 58 ms
```
</details>

**Comment by D4niloMR** [comment]
@ChuckStriker do you have a exact link where this happens?

**Comment by mapx-** [comment]
We have filters for other discovery entities, so you could try:

    investigationdiscovery.com##+js(json-prune, data.attributes.ssaiInfo.forecastTimeline data.attributes.ssaiInfo.vendorAttributes.nonLinearAds data.attributes.ssaiInfo.vendorAttributes.videoView data.attributes.ssaiInfo.vendorAttributes.breaks.[].ads.[].adMetadata data.attributes.ssaiInfo.vendorAttributes.breaks.[].ads.[].adParameters data.attributes.ssaiInfo.vendorAttributes.breaks.[].timeOffset)
    investigationdiscovery.com##+js(xml-prune, xpath(//*[name()="MPD"][.//*[name()="BaseURL" and contains(text()\,'dash_clear_fmp4') and contains(text()\,'/a/')]]/@mediaPresentationDuration | //*[name()="Period"][./*[name()="BaseURL" and contains(text()\,'dash_clear_fmp4') and contains(text()\,'/a/')]]), , .mpd)

If does not work, we'll need an account: are you willing to share with us your credentials ? I 'll provide an email address if you confirm it.

**Comment by ChuckStriker** [comment]
It worked!!! Thank you so much for your help!
