### ISSUE TITLE
ezgif.com: nuisance

### ISSUE THREAD

**Issue by Zenphia** [uBlockOrigin/uAssets#21012]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [ ] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ezgif.com/`

### Category

nuisance

### Description

fullscreen cookie notice

### Other extensions used

[I still don't care about cookies](https://chromewebstore.google.com/detail/i-still-dont-care-about-c/edibdbjcniadpccecjdfdjjppcpchdlm)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 103383
 cosmetic: 44028
 scriptlet: 19435
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 18-0, never
  easylist: 75598-16, 57m
  easyprivacy: 33033-64, 56m
  plowe-0: 3779-1136, now
  ublock-badware: 7538-138, now
  ublock-filters: 35902-156, now
  ublock-privacy: 936-11, now
  ublock-quick-fixes: 268-118, now
  ublock-unbreak: 2156-32, now
  urlhaus-1: 9435-0, now
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 156 ms (selfie)
 maxAssetCacheWait: 57 ms
popupPanel:
 blocked: 4
 network:
  btloader.com: 1
  doubleclick.net: 1
  duckduckgo.com: 1
  stpd.cloud: 1
 extended:
  ##div[style$="min-height:90px;display:block"]
  ##.sidebar_ad
```
</details>

**Comment by mapx-** [comment]
enable one of these lists:

`AdGuard – Annoyances`
or
`uBlock filters – Annoyances`

(or only the cookie subList of them)
