### ISSUE TITLE
supercomputingonline.com: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21018]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.supercomputingonline.com/`

### Category

detection

### Description

The site displays a "Turn your Adblock off" box.

These filters remove the detection and Advertisement box.
```
supercomputingonline.com##+js(nostif, ad)
supercomputingonline.com##[class^="ad_prev"]
```

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1439" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/1717b71c-5313-4915-92ea-28651b217254">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104023
 cosmetic: 45595
 scriptlet: 23566
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5958-11, now
 default:
  user-filters: 52-2, never
  easylist: 75620-16, now
  easyprivacy: 33037-64, now
  plowe-0: 3779-1136, now
  ublock-badware: 7533-138, now
  ublock-filters: 35901-156, now
  ublock-privacy: 937-11, now
  ublock-quick-fixes: 268-118, now
  ublock-unbreak: 2156-33, now
  urlhaus-1: 9775-0, now
filterset (user): [array of 54 redacted]
trustedset:
 added: [array of 22 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 721 ms (selfie)
 maxAssetCacheWait: 101 ms
popupPanel:
 blocked: 3
 network:
  doubleclick.net: 1
  googlesyndication.com: 2
 extended:
  ##ins.adsbygoogle
  ##.adsbygoogle-noablate
```
</details>

**Comment by huyszn** [comment]
@mapx- The filter `@@||supercomputingonline.com^$ghide` does not block the site's requests for ads every 10 seconds.
https://github.com/uBlockOrigin/uAssets/assets/46979193/90afce08-f2dc-409e-a0f1-f801ac0045c7

**Comment by okiehsch** [comment]
Me neither.

**Comment by huyszn** [comment]
I tested it on chrome and firefox and it seems to be only happening on chrome.

**Comment by okiehsch** [comment]
I tested on chrome, because your confic shows that you use it and I can't reproduce, only one `googlesyndication.com` request happens on my end.

**Comment by huyszn** [comment]
I rebooted chrome and the behavior stopped.
