### ISSUE TITLE
[nsfw] edziecko.pl: detection

### ISSUE THREAD

**Issue by trzeci** [uBlockOrigin/uAssets#21017]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.edziecko.pl/rodzice/7,79361,30456712,od-kiedy-normalne-dziecinstwo-stalo-sie-niepozadane-psychiatra.html`

### Category

detection

### Description

uBlock menu from right click disappeared after first try

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 105134
 cosmetic: 51591
 scriptlet: 19447
 html: 1139
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 36784-144, 12m
  ublock-badware: 7542-11, 12m
  ublock-privacy: 931-4, 12m
  ublock-unbreak: 2202-1, 12m
  ublock-quick-fixes: 268-67, 12m
  easylist: 75613-711, 12m
  easyprivacy: 33035-790, 12m
  urlhaus-1: 9775-0, now
  plowe-0: 3779-1, now
  POL-0: 8015-27, now
  POL-2: 1283-12, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1263 ms (selfie)
 maxAssetCacheWait: 543 ms
popupPanel:
 blocked: 4
 network:
  gazeta.pl: 2
  gemius.pl: 1
  im-g.pl: 1
 extended:
  ##.adviewDFPBanner
  ##[id^="DFP-011-MIDBOARD_"], #banC99, .ban001_wrapper, #banC1
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
@trzeci 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by trzeci** [comment]
Dnia sobota, 2 grudnia 2023 19:12:03 CET ItsProfesssional pisze:
> Do you get a popup dialog telling you to turn off ad blocker? I don't see any.

No, nothing like this.
Simply: I have a popup menu after right-click with uBlock position: "block this element"
and after this position was chosen:

1. nothing changes on page
2. the menu position disappears

Could they create a special procedure to disable uBlock ?

--
Paweł Susicki

**Comment by trzeci** [comment]
Dnia sobota, 2 grudnia 2023 20:04:34 CET mapx pisze:
> @trzeci 
> 
> - clear cookies / localStorage/ cache for the tested page
> - reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
> - disable any custom filter for that site
> - disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
> - if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
> - disable (if any) the web shields in your antivirus / antimalware software / other blocking software
> - are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
> - restart the system, reopen the browser, test again.
> 
> 

Did everything and problem repeats:

right-click on:

[1]


chose position "block element"
nothing changes on page (window NOT blocked)
there is missing "block element" in the menu

I'm using firefox on Mageia 9
no other add-ons in browser

try page: https://www.plotek.pl/plotek/7,154063,30466494,filmowy-kevin-sam-w-domu-ma-dwoje-dzieci-pierwszy-raz-pokazal.html#s=BoxOpImg6[2]

one info: sometimes it works, but very rarely (once per 50 times)

-- 
--
Paweł Susicki


--------
[1] obraz
[2] https://www.plotek.pl/plotek/7,154063,30466494,filmowy-kevin-sam-w-domu-ma-dwoje-dzieci-pierwszy-raz-pokazal.html#s=BoxOpImg6
