### ISSUE TITLE
techsotta.com: detection

### ISSUE THREAD

**Issue by Andullah-Janjua** [uBlockOrigin/uAssets#21028]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://techsotta.com/?lid=Um1RgrgZ&pid=822902&plid=1&vid=249107039`

### Category

detection

### Description

It works fine when I disable ublock origin.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 118
filterset (summary):
 network: 103682
 cosmetic: 44031
 scriptlet: 19428
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75631-16, 3m
  easyprivacy: 33059-64, 3m
  plowe-0: 3779-1136, 3m
  ublock-badware: 7533-138, 3m
  ublock-filters: 35899-156, 3m
  ublock-privacy: 937-12, 3m
  ublock-quick-fixes: 268-118, 3m
  ublock-unbreak: 2157-32, 3m
  urlhaus-1: 9695-0, 3m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 24321 ms (selfie)
 maxAssetCacheWait: 125 ms
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  gplinks.in: 2
```
</details>

**Comment by mapx-** [comment]
invalid: shortener crap, you always have to provide the initial link

**Comment by huyszn** [comment]
This link shortener is gplinks initially from `gplinks.co/Um1RgrgZ`

**Comment by garry-ut99** [comment]
Shouldn't go here : https://github.com/uBlockOrigin/uAssets/blob/master/filters/ubo-link-shorteners.txt instead of https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2023.txt ?
I'm not saying it should, I'm just asking, because I've noticed the new filter list yesterday, supposed to be dedicated for link shorteners.

**Comment by okiehsch** [comment]
That list is not ready for general use yet.
