### ISSUE TITLE
filmweb.pl: ads

### ISSUE THREAD

**Issue by Bartek16194** [uBlockOrigin/uAssets#21023]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.filmweb.pl/films`

### Category

ads

### Description

jest dużo reklam na stronie
(there are a lot of ads on the site)

### Other extensions used

nie ma (none)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 102502
 cosmetic: 51599
 scriptlet: 19633
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://easylist.to/easylist/easylist.txt: 75630-16, 2m
 default:
  user-filters: 0-0, never
  POL-0: 8011-34, now
  POL-2: 1280-13, now
  easylist: 75620-75619, now
  easyprivacy: 33037-64, now
  ublock-badware: 7533-138, now
  ublock-filters: 35887-194, now
  ublock-privacy: 937-10, now
  ublock-quick-fixes: 268-118, now
  ublock-unbreak: 2157-33, now
  urlhaus-1: 9695-0, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 164 ms (selfie)
 maxAssetCacheWait: 72 ms
popupPanel:
 blocked: 20
 network:
  filmweb.pl: 3
  clarity.ms: 1
  doubleclick.net: 2
  fwcdn.pl: 1
  gemius.pl: 2
  google.com: 2
  googletagmanager.com: 1
  id5-sync.com: 1
  nsaudience.pl: 1
  pushpushgo.com: 1
  sascdn.com: 1
  smartadserver.com: 4
 extended:
  ##body[class]:not(.rodo):style(overflow: auto !important;)
  ##+js(abort-current-script, addEventListener, /faBar[\s\S]*?inse…
  ##+js(nano-remove-elements-onready, #skyBanner)
  ##+js(abort-current-script, IRI, Adblock)
  #@#+js(abort-current-script, decodeURIComponent, newAdblockBoard…
  #@#+js(no-setTimeout-if, notDetected)
```
</details>

**Comment by garry-ut99** [comment]
Related to : https://github.com/MajkiIT/polish-ads-filter/issues/21868

**Comment by garry-ut99** [comment]
Ads : 
`https://www.filmweb.pl/vod` : [screenshot_1](https://github.com/uBlockOrigin/uAssets/assets/72945564/398e127d-d8b4-41cc-9280-41ce1a10874e) - [screenshot_2](https://github.com/uBlockOrigin/uAssets/assets/72945564/ce86c8ba-1786-4fdd-9a12-65c9b8dd6774) - [screenshot_3](https://github.com/uBlockOrigin/uAssets/assets/72945564/2eeb5999-26a1-4448-bfcd-e3630de9b40d) - [screenshot_4](https://github.com/uBlockOrigin/uAssets/assets/72945564/0eff2f95-fcf6-4d2f-ba7a-882adc378023)
`https://www.filmweb.pl/ranking/film` : [screenshot 5](https://github.com/uBlockOrigin/uAssets/assets/72945564/03d64e07-42f1-4d53-bec4-844b3c549268)

**Comment by garry-ut99** [comment]
An ad from screenshoot 2 still here, needs `filmweb.pl##.faBannerPromo`
(by the way I've noticed it appears not only in "Gry" submenu, but also in "Filmy" submenu as well)
