### ISSUE TITLE
[nsfw] wikifeetx.com: ads

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#21033]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wikifeetx.com/Dani_Daniels`

### Category

ads

### Description

There are advertising inserts on the page.
### Other extensions used

None that interfere with uBlock.

### Screenshot(s)

Advertising insert :

![image](https://github.com/uBlockOrigin/uAssets/assets/50231020/045524cb-f6b1-4d13-b7ae-c3a8d8df79e4)

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 145142
 cosmetic: 118548
 scriptlet: 24057
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1677-0, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2498-11, now
  RUS-0: 39958-168, now
  fanboy-cookiemonster: 49106-229, now
 default:
  FRA-0: 28659-40, now
  easylist: 75634-110, now
  easyprivacy: 33059-633, now
  plowe-0: 3779-1152, now
  ublock-badware: 7535-151, now
  ublock-filters: 35885-271, now
  ublock-privacy: 937-63, now
  ublock-quick-fixes: 271-118, now
  ublock-unbreak: 2157-37, now
  urlhaus-1: 9795-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 778 ms (selfie)
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 11
 network:
  adsession.com: 2
  cloudflare.com: 2
  doubleclick.net: 2
  exacdn.com: 1
  google.com: 1
  googletagmanager.com: 1
  youtube.com: 2
 extended:
  ##a[href*="&utm_medium=cpa"][target="_blank"]
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(href-sanitizer, a[href^="https://www.youtube.com/redirect?…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
add

`wikifeetx.com##[href^="https://join.loveherfeet.com/"]`

report at easylist repo
