### ISSUE TITLE
trojmiasto.pl - video player not showing

### ISSUE THREAD

**Issue by h7896v7347** [uBlockOrigin/uAssets#21035]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://tv.trojmiasto.pl/Skutki-wypadku-na-obwodnicy-w-kier-Gdyn-03-12-2023-video-86564.html`
`https://www.trojmiasto.pl/raport/Skutki-wypadku-na-obwodnicy-w-kier-Gdyni-rt334780.html`

### Description

Disable adblock message instead of video player.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/1020390/72794e45-1feb-4d51-b1ba-d1efa55c9632)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.54.0
Firefox: 119
filterset (summary):
 network: 211959
 cosmetic: 136636
 scriptlet: 24344
 html: 1139
listset (total-discarded, last-updated):
 added:
  curben-phishing: 88843-27, 3m
  adguard-social: 22072-167, 3m
  adguard-cookies: 28231-43, 3m
  adguard-popup-overlays: 26489-962, 3m
  adguard-mobile-app-banners: 4808-9, 3m
  adguard-other-annoyances: 13996-10, 3m
  adguard-widgets: 2352-1, 3m
  dpollock-0: 11586-467, 3m
  ublock-cookies-adguard: 630-0, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 36767-426, 2m
  ublock-badware: 7539-11, 3m
  ublock-privacy: 931-4, 3m
  ublock-unbreak: 2203-1, 3m
  ublock-quick-fixes: 273-67, 3m
  easylist: 75634-936, 3m
  easyprivacy: 33059-872, 3m
  urlhaus-1: 9795-0, 3m
  plowe-0: 3779-1, 3m
  POL-0: 8015-40, 3m
  POL-2: 1283-12, 3m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1019 ms
 maxAssetCacheWait: 443 ms

```
</details>

**Comment by garry-ut99** [comment]
Duplicate of https://github.com/MajkiIT/polish-ads-filter/issues/22122

(just as an information, it's all ok, I'm not blaming, neither saying it should be marked as a duplicate and declined, because in this case, due to inactivity of PL regional filter list, it's a common thing recently, to report and fix PL issues in uAssets, also I'm aware the same user reported the both issues).
