### ISSUE TITLE
levelup.gitconnected.com: nuisance

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uAssets#21044]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://levelup.gitconnected.com/a-day-with-vim-tutor-vimtutor-25aa2e6ce52c`

### Category

nuisance

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/19517680/1f1ea951-ac71-462a-afcd-e3bc625db3ff)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 112441
 cosmetic: 135396
 scriptlet: 31118
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 10447-0, now
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 80-4, now
  adguard-other-annoyances: 13997-23, now
  adguard-popup-overlays: 26490-62, now
  easylist-annoyances: 4226-179, now
  easylist-notifications: 2884-394, now
  fanboy-cookiemonster: 49106-245, now
  ublock-annoyances: 5970-209, now
  ublock-cookies-easylist: 633-633, now
 default:
  user-filters: 37-0, never
  easylist: 75725-75, now
  easyprivacy: 33059-170, now
  plowe-0: 3779-1136, now
  ublock-badware: 7540-140, now
  ublock-filters: 35888-616, now
  ublock-privacy: 937-13, now
  ublock-quick-fixes: 272-119, now
  ublock-unbreak: 2157-36, now
  urlhaus-1: 9930-0, now
filterset (user): [array of 37 redacted]
trustedset:
 added: [array of 24 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 872 ms (selfie)
 maxAssetCacheWait: 348 ms
popupPanel:
 blocked: 5
 network:
  gitconnected.com: 3
  branch.io: 1
  googletagmanager.com: 1
 extended:
  ##div.l > .acu.act
  ##+js(set-local-storage-item, 201805-policy|accepted, 1)
```
</details>

**Comment by D4niloMR** [comment]
@mapx- `##+js(aeld, message, data)` causes breakage to me, open `medium.com` and click on an article that goes to medium, I get a blank page.

Same for the other ones I tested.

Can be replaced with `##+js(trusted-set-local-storage-item, lo-non-moc-membership-upsell|dismissed-at, $now$)`
