### ISSUE TITLE
filme2023.online: ads

### ISSUE THREAD

**Issue by claudiu64** [uBlockOrigin/uAssets#21041]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://filme2023.online/load/filme_dublate/komedii/inca_doua_lozuri_2023/9-1-0-368`

### Category

ads

### Description

Advertisements appear on the site. 

### Other extensions used

I do not use. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231203-231639_Firefox Beta](https://github.com/uBlockOrigin/uAssets/assets/114283947/cea5c388-46ff-4d81-9669-861f33433aa2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 105670
 cosmetic: 36061
 scriptlet: 19317
 html: 1129
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37095-360, now
  ublock-badware: 7538-11, now
  ublock-privacy: 931-5, now
  ublock-unbreak: 2208-2, now
  ublock-quick-fixes: 272-67, now
  adguard-mobile: 8781-129, now
  easylist: 75635-16749, now
  easyprivacy: 33059-810, now
  urlhaus-1: 9795-0, now
  plowe-0: 3779-1, now
  ROU-1: 1397-31, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings:
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8471 ms
 maxAssetCacheWait: 3730 ms
 unsuspendAfter: 342 ms
popupPanel:
 blocked: 31
 network:
  acint.net: 2
  alleviatepracticableaddicted.com: 1
  betweendigital.com: 2
  bumlam.com: 1
  buzzoola.com: 2
  cdnfimgs.com: 2
  digitaltarget.ru: 1
  googlesyndication.com: 2
  intellipopup.com: 1
  kimberlite.io: 2
  marazma.com: 1
  mbidadm.com: 2
  new-programmatic.com: 1
  onlyplay.online: 2
  popmansion.com: 1
  sadjklq.com: 1
  uuidksinc.net: 1
  yadro.ru: 4
  yandex.ru: 2
```
</details>

**Comment by Omega-6** [comment]
```
||refpa57118.top^
```

**Comment by Omega-6** [comment]
@Yuki2718 sorry for mentioning, but could you add `||cchdbond.com^` to EasyList?
