### ISSUE TITLE
Earnow, Shortano Redirect

### ISSUE THREAD

**Issue by XShouko** [uBlockOrigin/uAssets#21045]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

```
https://shortano.link/OWnltm0be8l
http://earnow.online/Fx0V
```

### Description

Earnow, Shortano redirected to > clk.wiki > earnhub.net at step 1
```
http://earnow.online/Fx0V
https://shortano.link/OWnltm0be8l
```
Please help :')

### Other extensions used

Violentmonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Uploading Screenshot 2023-12-04 100146.png…]()

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 104065
 cosmetic: 46474
 scriptlet: 19775
 html: 1185
listset (total-discarded, last-updated):
 default:
  user-filters: 3636-79, never
  ublock-filters: 36767-402, 42m
  ublock-badware: 7539-11, 42m
  ublock-privacy: 860-4, 6d.11h.49m
  ublock-unbreak: 2203-1, 42m
  ublock-quick-fixes: 271-7, 42m
  easylist: 75620-709, 41m
  easyprivacy: 33059-743, 41m
  urlhaus-1: 9930-0, 42m
  plowe-0: 3720-1, 6d.11h.49m
filterset (user): [array of 1425 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 25 redacted]
 removed:
  no-csp-reports: * true
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 187 ms (selfie)
 maxAssetCacheWait: 81 ms

```
</details>

**Comment by mapx-** [comment]
dedicated discussion => https://github.com/uBlockOrigin/uAssets/discussions/17361
