### ISSUE TITLE
synergia.librus.pl: ads

### ISSUE THREAD

**Issue by 6vz** [uBlockOrigin/uAssets#21049]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://portal.librus.pl/rodzina`

### Category

ads

### Description

On login pages, and on many other, there are banners that are really pissing of, and are straight up ads served by Librus themselves

### Other extensions used

1password: Password Manager

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![obraz](https://github.com/uBlockOrigin/uAssets/assets/92748380/92d39d69-9ef5-4a86-9e10-8ad4402fb11b)
![obraz](https://github.com/uBlockOrigin/uAssets/assets/92748380/7eb611c6-c1a5-4af9-bdd6-eb924adf207c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105316
 cosmetic: 51597
 scriptlet: 19452
 html: 1139
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 36771-251, 24m
  ublock-badware: 7544-11, 24m
  ublock-privacy: 931-4, now
  ublock-unbreak: 2203-1, 24m
  ublock-quick-fixes: 272-67, 24m
  easylist: 75634-605, 24m
  easyprivacy: 33059-791, 24m
  urlhaus-1: 9930-0, now
  plowe-0: 3779-1, now
  POL-0: 8015-27, now
  POL-2: 1283-12, now
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1474 ms (selfie)
 maxAssetCacheWait: 850 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
maybe

```
portal.librus.pl##[src^="https://files.librus.pl"][src*="_loginR_"]
portal.librus.pl##picture:has(source[srcset*="db"])
```

on the right side seems to be self promotion

however, use the filters as custom ones, try reporting to the polish repositories
