### ISSUE TITLE
qiwi.gg: breakage

### ISSUE THREAD

**Issue by owen2619** [uBlockOrigin/uAssets#21046]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://qiwi.gg/dashboard`

### Category

breakage

### Description

Uploading files from the dashboard fails while uBO is enabled. The file gets stuck on "waiting" and some errors are logged to the console.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/152839169/e52f7afc-a946-4235-b467-86569f7c6dcc)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 103993
 cosmetic: 44027
 scriptlet: 19246
 html: 1128
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36771-106, 2m
  ublock-badware: 7544-11, 2m
  ublock-privacy: 931-4, 2m
  ublock-unbreak: 2203-1, 2m
  ublock-quick-fixes: 272-67, 2m
  easylist: 75731-655, 2m
  easyprivacy: 33059-833, 2m
  urlhaus-1: 9930-0, 2m
  plowe-0: 3779-1, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2718 ms
 maxAssetCacheWait: 7 ms
popupPanel:
 blocked: 4
 network:
  cloudflarestorage.com: 1
  getclicky.com: 2
  googletagmanager.com: 1
 extended:
  ##+js(addEventListener-defuser, , sessionStorage)
  ##+js(no-window-open-if, , 10)
```
</details>

**Comment by ave9858** [comment]
getting a white screen when I click the ... to manage an uploaded file on the dashboard (https://qiwi.gg/dashboard), seems to be caused by `qiwi.gg##+js(aost, document.createElement, /createDecoy|onClick/)`.

Screenshot of what should show:
![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/fef52722-28a5-4025-932a-7787dbf8f2bc)
