### ISSUE TITLE
wkyc.com

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#2104]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

    https://www.wkyc.com/

### Describe the issue

The initial page loads, after all scripts have loaded, the page refreshes and clears the main div to display anti-adblock message or an entirely blank page.

### Screenshot(s)

Can provide if needed.

### Versions

Tested on both Chrome and Firefox with latest uBlock dev builds.

- Browser/version: Chrome 66.0.3359.139 (Official Build) (64-bit) / Firefox 59.0.2
- Chome uBlock Origin version: 1.16.1.104 / Firefox uBlock Origin version: 1.16.1rc5

### Settings

- No changes to default filter lists and settings.

### Notes

Disabling inline-scripts seems to stop the page reload to blank div but the site is neutered with all inline-scripts blocked.

**Comment by gorhill** [comment]
How about:

    wkyc.com##script:inject(abort-current-inline-script.js, btoa)
    wkyc.com##.grid__sticky-column_side_left

**Comment by yourduskquibbles** [comment]
Works great, thank you!
