### ISSUE TITLE
moovitapp.com: nuisance

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uAssets#21051]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://moovitapp.com/athens_%CE%B1%CE%B8%CE%B7%CE%BD%CE%B1-1822/poi/el`

### Category

nuisance

### Description

Popup prompt to install mobile app (site accessed from Greece).

I have reported the issue to EasyList and AdGuard, but they both couldn’t reproduce it, so I suspect that it may be geo-dependent. I saved a full copy of the site, if that helps:

https://www.dropbox.com/scl/fi/pf63um1rxh3pqfjcl3w97/Moovit-Real-Time-Worldwide-Public-Transit-App.zip?rlkey=d1kpmjolc6rsfjgvlbzneb78c&dl=1

The popup is also present on:

https://web.archive.org/web/20231201021418/https://moovitapp.com/

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-04 at 14-07-09 Η Πιο Δημοφιλής Εφαρμογή Αστικής Κινητικότητας στη πόλη Αθήνα](https://github.com/uBlockOrigin/uAssets/assets/101707608/fac1ed0c-96a0-44ee-9458-edd4d05e6304)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 392614
 cosmetic: 261661
 scriptlet: 47558
 html: 1326
listset (total-discarded, last-updated):
 added:
  https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt: 57620-6299, now
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList: 95475-1948, now
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 672-0, now
  https://www.dropbox.com/s/kqbpdbxeeieazhe/Custom%20filters.txt?dl=1: 217-0, 3m
  https://www.i-dont-care-about-cookies.eu/abp/: 25835-19, now
  adguard-generic: 80431-8190, now
  adguard-mobile: 8785-139, now
  adguard-spyware-url: 1352-92, now
  adguard-spyware: 76675-19422, now
  block-lan: 55-0, now
  curben-phishing: 78287-30, now
  adguard-social: 22073-868, now
  [14 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 36775-547, now
  ublock-badware: 7544-11, now
  ublock-privacy: 931-6, now
  ublock-unbreak: 2203-2, now
  ublock-quick-fixes: 276-67, now
  easylist: 75732-31745, now
  easyprivacy: 33045-1080, now
  urlhaus-1: 9930-0, now
  plowe-0: 3779-1, now
  GRC-0: 1045-2, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 16010 ms (selfie)
 maxAssetCacheWait: 1833 ms
popupPanel:
 blocked: 7
 network:
  doubleclick.net: 1
  google-analytics.com: 1
  google.com: 2
  google.gr: 1
  googletagmanager.com: 1
  sentry.io: 1
 extended:
  ##.search-container
  ##.side-menu-desktop
  ##.moovit-banner
  ##mv-side-navigation div[itemtype="http://schema.org/MobileAppli…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
test using only the default settings / filter lists, no other addon enabled

**Comment by mapx-** [comment]
yes, I get the same in android simulator, but ... the op let us think it's about desktop (it's why I thought one of his lists is breaking desktop / android detection)

however, someone could test (filters for the mobile page):

```
m.moovitapp.com##+js(trusted-click-element, [data-automation="continue-to-ads-btn", , 1000])
m.moovitapp.com##+js(rmnt, script, Interstitial)
m.moovitapp.com##.init.open
m.moovitapp.com##.top-banner
```

**Comment by mapx-** [comment]
@ghajini could you test in real android ?

**Comment by DimitrisKalaboukas** [comment]
@mapx- Please, remove the <m.> in front of the domain, because the same issue also occurs on desktop with high zoom rate in the browser (150%). Due to visual impairment, I zoom in websites and I have realized that many servers deliver the mobile version of the page in this case.
