### ISSUE TITLE
1404e472832f4238ab18b6546efda1b1.cleverconnect.app: breakage

### ISSUE THREAD

**Issue by gavelle** [uBlockOrigin/uAssets#21052]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://1404e472832f4238ab18b6546efda1b1.cleverconnect.app/alternanceetstagevotrealternancecleenmain`

### Category

[unknown]

### Description

Onetrust Cookie Consent script is blocked by uBlock.
As a result, cookies are created before the user accepts or rejects cookies.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 122873
 cosmetic: 53117
 scriptlet: 19578
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 28689-39, 10m
  easylist: 75620-53, 10m
  easyprivacy: 33045-333, 10m
  plowe-0: 3779-1147, 10m
  ublock-badware: 7540-151, 10m
  ublock-filters: 35894-232, 10m
  ublock-privacy: 937-13, 10m
  ublock-quick-fixes: 276-119, 10m
  ublock-unbreak: 2157-36, 10m
  urlhaus-1: 9965-0, 10m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1472 ms
 maxAssetCacheWait: 4 ms
popupPanel:
 blocked: 6
 network:
  cookielaw.org: 1
  google.com: 2
  meteojob.com: 1
  youtube.com: 2
```
</details>

**Comment by mapx-** [comment]
see if helps

`/otautoblock.js$badfilter`

@ryanbr

**Comment by krystian3w** [comment]
Pages then create without `/otautoblock.js$badfilter`:

```
    _sp_ses.X11X:*
    _sp_id.X11X:x333xx33-3x3x-33x3-33xx-333333333xx3.3333333333.3.3333333333..x333333x-x3xx-3333-xxxx-33xxx3x3333x..xxxxx3xx-3x3x-3xx3-333x-3x3xx33x3333.3333333333333.3
```

I don't see breakges for that webproxy due I doubt to real address for `sncf.com` family.

**Comment by mapx-** [comment]
I asked you to test a filter ?!
When you'll have a stable address test again and report back here or - better - at easylist repository

**Comment by gavelle** [comment]
OK sorry, that's what I understood. 
We'll check again with the final URL once it's configured.
Thanks for your help.
