### ISSUE TITLE
blockclubchicago.org: breakage

### ISSUE THREAD

**Issue by temporary0211** [uBlockOrigin/uAssets#21054]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://blockclubchicago.org/2023/11/29/uptowns-preston-bradley-center-will-be-revived-as-concert-venue-community-center/`

### Category

breakage

### Description

Site doesn't load if unlock origin is enabled 

### Other extensions used

.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 105431
 cosmetic: 35243
 scriptlet: 19314
 html: 1129
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37107-462, now
  ublock-badware: 7538-11, now
  ublock-privacy: 931-5, now
  ublock-unbreak: 2208-2, now
  ublock-quick-fixes: 276-67, now
  adguard-mobile: 8786-128, now
  easylist: 75746-16587, now
  easyprivacy: 33034-841, now
  urlhaus-1: 9965-0, now
  plowe-0: 3779-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2133 ms (selfie)
 maxAssetCacheWait: 119 ms
popupPanel:
 blocked: 15
 network:
  cxense.com: 1
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  npttech.com: 1
  parsely.com: 2
  wp.com: 4
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
```
</details>

**Comment by Omega-6** [comment]
> [x] I did not answer truthfully to **ALL** the above checkpoints.

Please look into whether you have any other extension enabled (or an ad blocker like AdGuard, Blockada, AdAway)

**Comment by temporary0211** [comment]
My apologies. I thought I had disabled all of them but it looks like I
missed unchecking adguard. Strangely, it will work if EITHER  ublock origin
or adguard are disabled but not if both are enabled.
