### ISSUE TITLE
twinkie.xyz: breakage

### ISSUE THREAD

**Issue by axelawh** [uBlockOrigin/uAssets#21056]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://twinkie.xyz/dashboard`
`https://twinkie.xyz/view/murky-willing-buck.png`

### Category

breakage

### Description

Does not load cloudfalre apps, background image on the login page or the report file button.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 104044
 cosmetic: 44035
 scriptlet: 19448
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75761-16, now
  easyprivacy: 33034-65, now
  plowe-0: 3779-1136, now
  ublock-badware: 7540-138, now
  ublock-filters: 35899-156, now
  ublock-privacy: 937-12, now
  ublock-quick-fixes: 276-119, now
  ublock-unbreak: 2157-32, now
  urlhaus-1: 9965-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 420 ms
 maxAssetCacheWait: 154 ms
popupPanel:
 blocked: 2
 network:
  twinkie.xyz: 1
  cloudflareinsights.com: 1
```
</details>

**Comment by Omega-6** [comment]
@axelawh I haven't reproduce, but could you please test:

```
@@||twinkie.xyz/cdn-cgi/apps/head/*.js|$script,1p
```

?

**Comment by ryanbr** [comment]
Working for me here?

**Comment by ryanbr** [comment]
I don't think its the filter, and just cloudflare having issues.

**Comment by axelawh** [comment]
uBlockOrigin removes the background on the login page. It should be a pink gif background. Also there should be a red report button in the top left corner of a file/image webpage. With the extension disabled both the login background and report button are visible. I have no other extensions.
