### ISSUE TITLE
Sponsored ads in Google Image Search

### ISSUE THREAD

**Issue by itsasooz** [uBlockOrigin/uAssets#21061]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.google.com/search?q=%22ruth+heller%22&tbm=isch&ved=2ahUKEwiQndnnyPaCAxXqlIkEHQH-CDgQ2-cCegQIABAA&oq=%22ruth+heller%22&gs_lcp=CgNpbWcQAzIFCAAQgAQyBAgAEB4yBwgAEIAEEBgyBwgAEIAEEBgyBwgAEIAEEBgyBwgAEIAEEBgyBwgAEIAEEBgyBwgAEIAEEBgyBwgAEIAEEBg6DQgAEIAEEIoFEEMQsQM6CAgAEIAEELEDOgoIABCABBCKBRBDOgsIABCABBCxAxCDAToGCAAQBRAeOgYIABAIEB5QpxhY1iZg1ShoAHAAeACAAYcBiAG6CJIBBDEzLjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=iy9uZdCrDuqpptQPgfyjwAM&bih=920&biw=1162&client=firefox-b-1-d`

### Category

ads

### Description

When using GIS, sponsored ads for purchasing show up.  This does not show on _every_ search, but has on the given URL.

### Other extensions used

Absolute Enable Right Click & Copy, Enhancer for YouTube, Facebook Container, New Tab Tools, Personal Blocklist, View Image, Window Titler. 

(Of all of those, I think only View Image, Personal Blocklist, and Absolute would be active on GIS, and I have confirmed that the issue persists when they are deactivated.)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-04 141654](https://github.com/uBlockOrigin/uAssets/assets/6354474/c7bb0a1c-6d0d-4147-a0ee-c8991960bcde)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 54337
 cosmetic: 111197
 scriptlet: 38825
 html: 1128
listset (total-discarded, last-updated):
 removed:
  easylist: null
  easyprivacy: null
 added:
  adguard-generic: 80436-4520, now
  adguard-social: 22060-38, now
  adguard-popup-overlays: 26508-902, now
  adguard-mobile-app-banners: 4810-9, now
  adguard-other-annoyances: 13999-134, now
  adguard-widgets: 2353-1, now
 default:
  user-filters: 7-0, never
  ublock-filters: 36781-384, now
  ublock-badware: 7544-11, now
  ublock-privacy: 931-4, now
  ublock-unbreak: 2203-1, now
  ublock-quick-fixes: 276-67, now
  urlhaus-1: 9965-0, now
  plowe-0: 3779-1, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 812 ms (selfie)
 maxAssetCacheWait: 146 ms
popupPanel:
 blocked: 0
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Omega-6** [comment]
@itsasooz Please enable EasyList

**Comment by Omega-6** [comment]
@gorhill You probably thought of this, but could you prevent the creation of an issue if core filter lists aren't enabled?

**Comment by gorhill** [comment]
Self-inflicted issue by disabling EasyList/EasyPrivacy, while not being truthful when reporting:

> - [x] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
