### ISSUE TITLE
gamestar.de, mein-mmo.de: ads

### ISSUE THREAD

**Issue by Xamrica** [uBlockOrigin/uAssets#21078]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.
```
https://www.gamestar.de/news/
https://mein-mmo.de/
```
### Description

1. go to `https://www.gamestar.de/news/`
2. Every article with "[Anzeige]" (ad in german) in the name, should not be there
3. go to `https://mein-mmo.de/`
4. Every article where the article-image has "Anzeige" shown at the top right should not be there

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![gamestar](https://github.com/uBlockOrigin/uAssets/assets/68482765/745f600c-616b-4a2b-8792-c2180603b8a2)

![mein-mmo](https://github.com/uBlockOrigin/uAssets/assets/68482765/53955e38-cf20-494e-8166-6c6eb9b427ba)

</details>

### Configuration

<details>
<summary>Details gamestar.de</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 105838
 cosmetic: 48864
 scriptlet: 19476
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7182-0, 13m
  easylist: 75803-22, 13m
  easyprivacy: 33048-74, 13m
  plowe-0: 3779-1137, 13m
  ublock-badware: 7535-138, 13m
  ublock-filters: 35956-171, 13m
  ublock-privacy: 937-12, 13m
  ublock-quick-fixes: 280-119, 13m
  ublock-unbreak: 2158-34, 13m
  urlhaus-1: 9355-0, 13m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 185 ms (selfie)
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 50
 network:
  gamestar.de: 2
  360yield.com: 2
  adnxs.com: 2
  adsafeprotected.com: 3
  adscale.de: 1
  amazon-adsystem.com: 4
  cgames.de: 2
  criteo.com: 1
  criteo.net: 2
  doubleclick.net: 3
  getjad.io: 3
  google-analytics.com: 1
  googlesyndication.com: 3
  googletagservices.com: 1
  lijit.com: 1
  onthe.io: 1
  openx.net: 2
  pbstck.com: 1
  pubmatic.com: 2
  relevant-digital.com: 1
  rlcdn.com: 3
  s-onetag.com: 1
  scorecardresearch.com: 1
  smartadserver.com: 2
  teads.tv: 2
  typekit.net: 1
  userreport.com: 1
  webcontentassessor.com: 1
 extended:
  ###dfp-header
  ###dfp-header-container
  ##.jad-placeholder
  ##.content-item-medium:has(data:has-text(Anzeige))
  ##.content-item-small:has(h3:has-text(Anzeige))
  ##+js(no-setTimeout-if, .call(null), 10)

```
</details>    

<details>
<summary>Details mein-mmo.de</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 105838
 cosmetic: 48864
 scriptlet: 19476
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  DEU-0: 7182-0, 16m
  easylist: 75803-22, 16m
  easyprivacy: 33048-74, 16m
  plowe-0: 3779-1137, 16m
  ublock-badware: 7535-138, 16m
  ublock-filters: 35956-171, 16m
  ublock-privacy: 937-12, 16m
  ublock-quick-fixes: 280-119, 16m
  ublock-unbreak: 2158-34, 16m
  urlhaus-1: 9355-0, 16m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 185 ms (selfie)
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 9
 network:
  mein-mmo.de: 2
  dm-event.net: 2
  getjad.io: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  onthe.io: 1
  webcontentassessor.com: 1
 extended:
  ###dfp-header
  ###dfp-masthead
  ###dfp-atf
  ###dfp-mtf
  ###dfp-btf
  ##+js(no-setTimeout-if, .call(null), 10)
```
</details>

**Comment by D4niloMR** [comment]
`gamestar.de#?#.contentnewsitem-box .box-reload .news-list:-abp-has(span:-abp-contains([Anzeige]))`
`gamestar.de#?#.contentnewsitem-box .box-reload > div:-abp-has(.news-list span:-abp-contains([Anzeige])) + hr`

`mein-mmo.de#?#li.article:-abp-has([data-type="sponsored"])`
`mein-mmo.de#?#section.post:-abp-has([data-type="sponsored"])`
`mein-mmo.de###mmo-promotion-sidebar`

To EL Germany
@Khrin

**Comment by mapx-** [comment]
maybe you could notify it in the adblock-requests on slack
