### ISSUE TITLE
CNN detection

### ISSUE THREAD

**Issue by Oqarshi** [uBlockOrigin/uAssets#21070]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.cnn.com/`
`https://www.cnn.com/browser-blocked`

### Description

CNN detects ublock origin when visiting the site.  If I disable Ublock origin the site loads normally. It looks like there was another issue reported at `https://github.com/uBlockOrigin/uAssets/issues/19370` but since then CNN has changed their adblock detection and instead of a popup its a webpage. Disabling my easycookie list does not fix the issue.

### Other extensions used

SponserBlock : `https://chromewebstore.google.com/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone`
Return Youtube Dislike: `https://chromewebstore.google.com/detail/return-youtube-dislike/gebbhagfogifgggkldgodflihgfeippi`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-04 185313](https://github.com/uBlockOrigin/uAssets/assets/94034118/29603da7-0aba-4883-a82d-a5338230e2dd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 199397
 cosmetic: 321151
 scriptlet: 36207
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  ALB-0: 309-4, 11m
  BGR-0: 1020-1, 12m
  CHN-0: 25083-134, 12m
  CZE-0: 833-1, 12m
  DEU-0: 7182-0, 12m
  EST-0: 465-2, 12m
  FIN-0: 2234-0, 12m
  FRA-0: 28689-68, 12m
  GRC-0: 1045-0, 12m
  HRV-0: 384-2, 12m
  HUN-0: 2082-2, 12m
  IDN-0: 9711-22, 12m
  [40 lists not shown]: [too many]
 default:
  easylist: 75798-413, 13m
  easyprivacy: 33047-652, 13m
  plowe-0: 3779-1197, 13m
  ublock-badware: 7540-162, 13m
  ublock-filters: 35922-783, 13m
  ublock-privacy: 937-18, 13m
  ublock-quick-fixes: 279-120, 13m
  ublock-unbreak: 2158-56, 13m
  urlhaus-1: 9325-0, 13m
filterset (user): [array of 19 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1783 ms (selfie)
 maxAssetCacheWait: 677 ms
```
</details>

**Comment by Wakizashimaster** [comment]
How was this issue resolved?

**Comment by Wakizashimaster** [comment]
Nevermind, its adblockplus causing the issue.

**Comment by Omega-6** [comment]
I'm assuming you use YouTube. Using uBlock Origin along any other ad blocker may result in detection.
