### ISSUE TITLE
bing.com: breakage

### ISSUE THREAD

**Issue by Geyser182** [uBlockOrigin/uAssets#21079]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bing.com/`

### Category

breakage

### Description

Bing.com's autocomplete searching feature does not work when uBO is enabled. Whenever the user searches up anything on their computer, nothing shows up when the user inputs characters into the text field box. The searching itself is not affected, but the search autocomplete does not work. 

I am going to assume this is related to an advertising server that is also associated with the delivery of the autocomplete search terms.

Thanks uBO team for your hard work as always.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (41)](https://github.com/uBlockOrigin/uAssets/assets/147728515/d92e9e30-667b-4833-84ef-ba79e9fe26cf)
![Screenshot (42)](https://github.com/uBlockOrigin/uAssets/assets/147728515/f8f1b950-e000-47f6-9c09-a61a0f0757b0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 261709
 cosmetic: 90729
 scriptlet: 36262
 html: 1128
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt: 718-8, 14m
  adguard-generic: 80462-7277, 14m
  adguard-mobile: 8789-100, 14m
  adguard-spyware-url: 1352-142, 14m
  adguard-spyware: 76689-16887, 14m
  block-lan: 55-0, 14m
  curben-phishing: 78508-27, 14m
 default:
  user-filters: 53-0, never
  ublock-filters: 36836-120, 14m
  ublock-badware: 7539-11, 14m
  ublock-privacy: 931-25, 14m
  ublock-unbreak: 2204-2, 14m
  ublock-quick-fixes: 280-67, 14m
  easylist: 75803-780, 14m
  easyprivacy: 33048-797, 14m
  urlhaus-1: 9355-0, 14m
  plowe-0: 3779-1, 14m
filterset (user): [array of 53 redacted]
userSettings: [none]
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 3539 ms (selfie)
 maxAssetCacheWait: 1370 ms
popupPanel:
 blocked: 87
 network:
  bing.com: 69
  msn.com: 18
 extended:
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
  ##+js(no-setInterval-if, logQueue, 10000)
```
</details>

**Comment by mapx-** [comment]
- you are using an external list (dandelion_something) blocking that feature
- report to that repo

add
`||bing.$removeparam=cvid,badfilter`

**Comment by iam-py-test** [comment]
@mapx- That filter does not exist in Legit URL. cvid is only removed from /search. Additionally, I can not reproduce any breakage. Where is that filter present in Legit URL?
Thanks

**Comment by mapx-** [comment]
it's here:
`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt`

`||bing.*^$removeparam=cvid`

**Comment by iam-py-test** [comment]
Oh, sorry.
I'm a idiot and didn't see that in the OP's troubleshooting info
Sorry for wasting your (finite) time

**Comment by iam-py-test** [comment]
Fixed, sorry.
