### ISSUE TITLE
The built-in Unbreak filter breaks Disqus comments on cyclingnews.com

### ISSUE THREAD

**Issue by biwqn** [uBlockOrigin/uAssets#2107]
### URL(s) where the issue occurs

Any article off of `http://www.cyclingnews.com/`.
For example:
`http://www.cyclingnews.com/races/tour-de-romandie-2018/stage-3/results`
`http://www.cyclingnews.com/features/giro-ditalia-chris-froome-defiant-despite-looming-salbutamol-case`
`http://www.cyclingnews.com/news/richie-porte-shows-improving-form-in-romandie-tt`

### Describe the issue

The built-in Unbreak filter actually breaks Disqus comments on cyclingnews.com. If you go to any of those 3 links above, and have the Unbreak filter enabled, Disqus comments at the very bottom of the article do not load. When the Unbreak filter is disabled, the Disqus comments successfully load.

This has been happening for many weeks, maybe months now, even with latest Ublock origin versions.

### Screenshot(s)

N/A, as very easy to see. Make sure to go to the very bottom of each article page to see the Disqus comments or lack thereof.

### Versions

- Browser/version: Google Chrome/66.0.3359.139 (Official Build)
- uBlock Origin version: 1.16.2

### Settings

- No default changes, easy mode.

### Notes

Turning off/on the Unbreak filter and loading those articles (shift-control/command-r to not use the browser cache).

**Comment by okiehsch** [comment]
The filter breaking the comments was added to fix the navigation bar not responding to click events.
That has the unintended side effect of breaking the comment section I will remove that filter and add
`@@||google-analytics.com/analytics.js$script,domain=cyclingnews.com`
which will also fix the navigation bar.

**Comment by geoffdutton** [comment]
#2108 Is a proposed solution to not whitelisting google-analytics.com. Adding `ga.loaded = true` will probably help in general anyway.

**Comment by gorhill** [comment]
Meanwhile this can be tested with dev build and a dynamic filtering rule to block GA (this will override the exception filter).
