### ISSUE TITLE
toonstream.in: popups

### ISSUE THREAD

**Issue by aicynide** [uBlockOrigin/uAssets#21088]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://toonstream.in/`

### Category

popups

### Description

Superstar

### Other extensions used

violentmonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 120
filterset (summary):
 network: 105067
 cosmetic: 35291
 scriptlet: 19353
 html: 1129
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37194-367, now
  ublock-badware: 7534-11, now
  ublock-privacy: 931-5, now
  ublock-unbreak: 2209-1, now
  ublock-quick-fixes: 297-68, now
  adguard-mobile: 8788-128, now
  easylist: 75826-16737, now
  easyprivacy: 33048-799, now
  urlhaus-1: 9500-0, now
  plowe-0: 3779-1, now
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 22467 ms (selfie)
 maxAssetCacheWait: 279 ms
popupPanel:
 blocked: 8
 network:
  arc.io: 2
  custodycraveretard.com: 3
  googletagmanager.com: 1
  kaurieseluxate.com: 1
  wafflesquaking.com: 1
```
</details>

**Comment by D4niloMR** [comment]
@aicynide this works to you?

`vidstreaming.xyz##+js(set, Div_popup, '')`

**Comment by huyszn** [comment]
`vidstreaming.xyz##+js(aost, console.clear)` to stop the console from clearing.

**Comment by D4niloMR** [comment]
Not reproducible with `EasyList – Other Annoyances` enabled

https://github.com/uBlockOrigin/uAssets/commit/079d03a1dbe7f067b4c77ceb105d9988910f9172 this was just to prevent the site from reloading
