### ISSUE TITLE
omiod.com: popups

### ISSUE THREAD

**Issue by serpsquatch** [uBlockOrigin/uAssets#21087]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.omiod.com/meta-seo-inspector/`

### Category

website opens unprompted

### Description

This website opens unprompted. This occurs almost every day. It is uneccessary. I try to block it from opening, but everyday, there it is again. 
Yes, thank you for the great app. However, I do not need updates every time I open Chrome.
Please stop opening your page, "Meta seo inspector, chrome extension for seo experts" so frequently.
It seems like this happens everyday. Or more. Like every time I open Chrome.
Thanks for the app.
Please stop. 
Thanks again.

### Other extensions used

SEO Pro

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/74578324/ea4d552b-0b35-4c8c-ba29-47a85008fcd7)

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103442
 cosmetic: 44060
 scriptlet: 19487
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75732-16, 2m
  easyprivacy: 33048-65, now
  plowe-0: 3779-1136, now
  ublock-badware: 7536-138, now
  ublock-filters: 35981-157, now
  ublock-privacy: 937-12, 2m
  ublock-quick-fixes: 284-119, 2m
  ublock-unbreak: 2158-32, now
  urlhaus-1: 9355-0, 2m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 706 ms (selfie)
 maxAssetCacheWait: 318 ms
popupPanel:
 blocked: 3
 network:
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by D4niloMR** [comment]
@serpsquatch the issue is that this site opens every time you open the browser?
