### ISSUE TITLE
francoischarron.com: breakage

### ISSUE THREAD

**Issue by ravertine** [uBlockOrigin/uAssets#21091]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://francoischarron.com/concours/nos-concours/gagnez-cet-ensemble-belkin-pour-maximiser-vos-recharges-dappareils/n3vmSvhOc8/`

### Category

breakage

### Description

unable to enter contest unless I watch a video ad

note: a free account is required to see the contest entry button

### Other extensions used

n/a

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Sans titre](https://github.com/uBlockOrigin/uAssets/assets/97376305/99c1bf64-412a-4a9e-ae0d-8bf642d0adc6)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.1b3
Firefox: 120
filterset (summary):
 network: 127406
 cosmetic: 72883
 scriptlet: 26772
 html: 1326
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-popup-overlays: 26518-401, now
  adguard-other-annoyances: 14005-317, now
  easylist-annoyances: 4233-962, now
  easylist-notifications: 2888-263, now
  ublock-annoyances: 6063-29, now
 default:
  ublock-filters: 36869-735, now
  ublock-badware: 7540-11, now
  ublock-privacy: 931-5, now
  ublock-unbreak: 2204-2, now
  ublock-quick-fixes: 297-67, now
  easylist: 75827-16818, now
  easyprivacy: 33040-1097, now
  urlhaus-1: 9500-0, 9m
  plowe-0: 3779-1, now
  FRA-0: 28689-3072, now
filterset (user): [array of 33 redacted]
trustedset:
 added: [array of 337 redacted]
switchRuleset:
 added: [array of 24 redacted]
hostRuleset:
 added: [array of 12 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings:
 autoUpdateAssetFetchPeriod: 180
 autoUpdatePeriod: 4
 extensionUpdateForceReload: true
 manualUpdateAssetFetchPeriod: 1
 popupPanelLockedSections: 39
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 886 ms (selfie)
 maxAssetCacheWait: 95 ms
popupPanel:
 blocked: 10
 network:
  alexametrics.com: 1
  doubleclick.net: 1
  flashb.id: 1
  google.com: 2
  googletagmanager.com: 2
  sparteo.com: 2
  viously.com: 1
```
</details>

**Comment by D4niloMR** [comment]
Anti adb:
`francoischarron.com#@#.google_ads`

Ads:

`francoischarron.com###partipate_video_bottom`
`francoischarron.com#$#.reward-message { display: none !important; }`
`francoischarron.com#$#.reward-btn { display: block !important; }`

**Comment by mapx-** [comment]
maybe @smed79 could help here too

**Comment by Alex-302** [comment]
Hm. I can't reproduce even with one EasyList filter with French VPN.

**Comment by D4niloMR** [comment]
> unable to enter contest unless I watch a video ad
> note: a free account is required to see the contest entry button

```
francoischarron.com#$#.reward-message { display: none !important; }
francoischarron.com#$#.reward-btn { display: block !important; }
```
@Alex-302 These two are the relevant filter for that

**Comment by gorhill** [comment]
I could reproduce the anti-blocker redirection/message, this works for me (I have no account so I didn't see if there is anything else to fix):


    @@||francoischarron.com^$ghide
    francoischarron.com##.ads

**Comment by ravertine** [comment]
Alex-302: you might need a VPN with a Canadian IP address

I've installed firefox with ublock and its default filters on a new virtual machine. 

By default, I was redirected to a page telling me to disable my adblocker.

adding gorhill's filters, the redirect is gone, but I still can't enter the contest: after logging in, it says "you can participate after the ad" and the button is not clickable.

I've created a dummy account on the site if you want to login and see the problem:
```
username: cijib15975@gearstag.com
password: Ublock-test
```

**Comment by Omega-6** [comment]
video loads with `@@||sonar.viously.com/*/js?w^$script,domain=francoischarron.com`

we could hide it so that the button is clickable

**Comment by Alex-302** [comment]
Still can't reproduce with AdGuard or uBO with Canadian or French VPN.
sonar.viously.com is blocked.

<details>
<summary>Page</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/8361299/6a75267a-12f3-4256-bb57-118389ba85c1)


</details>

<details>
<summary>Settongs</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/8361299/5c948442-ca9f-43c8-ae47-d1a41901588c)


</details>

@D4niloMR I don't see these elements https://github.com/uBlockOrigin/uAssets/issues/21091#issuecomment-1843016360

**Comment by D4niloMR** [comment]
For some reason I can't too, now I don't have to watch ads to participate.

---

@ravertine Test and see if the button to participate is visible:

```
francoischarron.com#$#.reward-message { display: none !important; }
francoischarron.com#$#.reward-btn { display: block !important; }
```

**Comment by gorhill** [comment]
> For some reason I can't too, now I don't have to watch ads to participate

Same, unable to reproduce.

**Comment by Omega-6** [comment]
@Alex-302 That is the anti-adblock page. gorhill's filters address that. Please proceed towards a products giveaway to other thing
