### ISSUE TITLE
bilgoraj.com.pl: ads

### ISSUE THREAD

**Issue by zakk87** [uBlockOrigin/uAssets#21092]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [x] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bilgoraj.com.pl/pl/`

### Category

ads

### Description

```
bilgoraj.com.pl##.centered.billboard.container
||bilgoraj.com.pl/banery_foto/*$image
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![bilgorajcompl#1](https://github.com/uBlockOrigin/uAssets/assets/8110481/1296ed51-af0c-4abb-8101-74717be90e5a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 981512
 cosmetic: 181431
 scriptlet: 43837
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 75929-1775, now
  https://hole.cert.pl/domains/domains_adblock.txt: 791460-0, 7m
  adguard-generic: 80477-994, now
  adguard-social: 22065-2076, now
  adguard-spyware: 76699-1232, now
  fanboy-cookiemonster: 49124-19735, now
 default:
  user-filters: 42-2, never
  POL-0: 8011-136, now
  POL-2: 1280-18, now
  easylist: 75825-17735, now
  easyprivacy: 33040-16469, now
  plowe-0: 3779-1240, now
  ublock-badware: 7536-370, now
  ublock-filters: 35983-4501, now
  ublock-privacy: 937-300, now
  ublock-unbreak: 2158-149, now
  urlhaus-1: 9500-0, now
filterset (user): [array of 43 redacted]
trustedset:
 added: [array of 13 redacted]
 removed:
  chrome-scheme
  edge-scheme
switchRuleset:
 added: [array of 10 redacted]
 removed:
  no-large-media: behind-the-scene false
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1363 ms (selfie)
 maxAssetCacheWait: 780 ms
popupPanel:
 blocked: 0
 extended:
  ##.centered.billboard.container
```
</details>

**Comment by mapx-** [comment]
```
bilgoraj.com.pl##.centered.billboard.container
||bilgoraj.com.pl/banery_foto/*$image
bilgoraj.com.pl##.banner--screening
bilgoraj.com.pl##.baner
```

- classic filters which should be managed by the regional polish list(s)
- @krystian3w do you know an active polish maintainer ?

**Comment by krystian3w** [comment]
For hide/block ads its should be @majkiit; if up to 2 weeks can't  address then I recommend create pr there can be merged by [xxcriticxx](https://github.com/xxcriticxx) if both do not have a overpower private schedule or hard illness at the same time.

**Comment by mapx-** [comment]
@xxcriticxx @MajkiIT
