### ISSUE TITLE
TFC.TV Anti adblock

### ISSUE THREAD

**Issue by Markastil** [uBlockOrigin/uAssets#2109]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

TFC.TV

### Describe the issue

Videos will not play with ublock enabled.

### Screenshot(s)

https://imgur.com/a/71yqFoD

### Versions

- Browser/version: Version 66.0.3359.139 (Official Build) (64-bit)
- uBlock Origin version: 1.16.2
### Settings

- [Default]

### Notes

I want to learn how to create an anti adblock for specific websites that prevent videos from playing. Can anyone show me the ropes? 

Is there a filter that I can add to prevent this from happening?

Thank you.

**Comment by geoffdutton** [comment]
Try adding `tfc.tv##script:inject(fuckadblock.js-3.2.0)`

The blockadblock script is normally an internal redirect, but I'm seeing this:
```Access to Script at 'data:application/javascript;base64,KGZ1bmN0aW9....pOyB9Cn0pKCk7' from origin 'null' has been blocked by CORS policy: Invalid response. Origin 'null' is therefore not allowed access.```

So the `fuckadblock-3.2.0` wasn't being evaluated.

**Comment by mapx-** [comment]
@Markastil  probably to fully testing your issue I need an account ?!

Could you test
`tfc.tv##script:inject(abort-on-property-write.js, adBlockDetected)`

**Comment by mapx-** [comment]
What filter lists are enabled in uBo ?

**Comment by Markastil** [comment]
I've tried both default, and all.

**Comment by Markastil** [comment]
@okiehsch Yes I am. Also, fixed that too.
``
@mapx `tfc.tv##script:inject(set-constant.js, blockAdBlock, true)` also does not work.

**Comment by mapx-** [comment]
test these "classic" filters
```
@@||tfc.tv^$generichide
@@||gtcdn.azureedge.net/assets/js/blockadblock.js$script,domain=tfc.tv
```

**Comment by Markastil** [comment]
@mapx- also doesn't work.

Here is a log of 
`@@||tfc.tv^$generichide
@@||gtcdn.azureedge.net/assets/js/blockadblock.js$script,domain=tfc.tv`

https://i.imgur.com/OupayUZ.png

**Comment by mapx-** [comment]
probably we need a full account

**Comment by Markastil** [comment]
@mapx- Darn. Thanks for the help though. I wish I knew more about this. Seems really fun to figure out.

**Comment by geoffdutton** [comment]
@Markastil If you don't add any custom filters and open the Chrome Dev Console, do you see the following error?

```Access to Script at 'data:application/javascript;base64,KGZ1bmN0aW9....pOyB9Cn0pKCk7' from origin 'null' has been blocked by CORS policy: Invalid response. Origin 'null' is therefore not allowed access.```

From the logs in your screen shot (https://imgur.com/a/eiUfxFU), it shows `gtcdn.azureedge.net/assets/js/blockadblock.js` is being internally redirected to `fuckadblock-3.2.0`, and that works in most cases except when the script tag contains the attribute `crossorigin="anonymous"`.

**Comment by geoffdutton** [comment]
@jspenguin2017 With what filter(s)?

**Comment by jspenguin2017** [comment]
Default of Nano.

**Comment by mapx-** [comment]
`tfc.tv##script:inject(abort-on-property-write.js, adBlockDetected)`
working for me as well

**Comment by Markastil** [comment]
Tried
'tfc.tv##script:inject(abort-on-property-write.js, adBlockDetected)'
without logging in, it works. However if you do have an account it doesn't work.

**Comment by mapx-** [comment]
If you'll send me your account ( if you confirm I'll post here an email address) I can test again the issue

**Comment by Markastil** [comment]
@geoffdutton Here is what the console says https://i.imgur.com/YDCHLns.png
@mapx- I'll think about it, not comfortable with that option unless I give up on the problem.

**Comment by mapx-** [comment]
I used a basic account and I was able to start a show using this filter too:
`@@||tfc.tv/Scripts/amp-ads.js`

**Comment by Markastil** [comment]
@mapx got a discord? maybe I can share my screen and you can see what's happening.

**Comment by mapx-** [comment]
Did you test my last filter too ? 

these 2:
```
tfc.tv##script:inject(abort-on-property-write.js, adBlockDetected)
@@||tfc.tv/Scripts/amp-ads.js
```

tested show (using a basic free account):
`http://tfc.tv/episode/details/155090/the-bottomline-with-boy-abunda-april-28-2018`

**Comment by Markastil** [comment]
@mapx-  Yes. Here are the logs and consoles. https://imgur.com/a/98Xzxly

Video if you're curious. https://streamable.com/knv02

**Comment by mapx-** [comment]
use this filter replacing the second 1
`@@||tfc.tv/Scripts/*ads.js`

**Comment by geoffdutton** [comment]
@Markastil You need to also use `@@||tfc.tv/Scripts/amp-full-ads.js`. 

I'd guess they use `tfc.tv/Scripts/amp-full-ads.js` when you have a premium account, and that's the code that needs to evaluate in order for the play button to actually start the video.

So try something like
```tfc.tv##script:inject(abort-on-property-write.js, adBlockDetected)
@@||tfc.tv/Scripts/amp-*.js```

**Comment by Markastil** [comment]
@mapx- For a second I thought it was almost working! However it ends up buffering indefinitely.

https://streamable.com/0yenh

**Comment by Markastil** [comment]
@geoffdutton just like @mapx- 's the player now tries to buffer the ad indefinitely. https://imgur.com/a/k1wPkq1

**Comment by mapx-** [comment]
nothing to do, you have a full (premium) account, cannot help you further

You could try whitelisting the object entry in your logger .. but probably you'll get video ads

**Comment by Markastil** [comment]
The filter does work!
`tfc.tv##script:inject(abort-on-property-write.js, adBlockDetected)
@@||tfc.tv/Scripts/amp-*.js`

I had to to fully reset ublock and tried the filter again, it works! Thank you very much for the help.

**Comment by mapx-** [comment]
all the scriptlets uBo can use:
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt

examine the page (press ctrl-u) and you'll find `adBlockDetected`

the basic account use `tfc.tv/Scripts/amp-ads.js,` the full one `tfc.tv/Scripts/amp-full-ads.js`
