### ISSUE TITLE
laptop88.vn: ads

### ISSUE THREAD

**Issue by nghiabros** [uBlockOrigin/uAssets#21090]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://laptop88.vn/su-khac-biet-giua-lightroom-va-photoshop-tinh-nang-chinh-anh-vuot-troi-tren-lightroom.html`

### Category

ads

### Description

ad show in two sides of page

### Other extensions used

Bitwardens, Proxy Switchy Omega

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/43260081/103dd6d1-5bea-4e33-ab5a-e21000aa3459)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 106888
 cosmetic: 45681
 scriptlet: 20192
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 2507-1, now
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1007-0, now
  VIE-1: 2104-0, now
 default:
  user-filters: 1-0, never
  easylist: 75827-34, now
  easyprivacy: 33040-68, now
  plowe-0: 3779-1136, now
  ublock-badware: 7536-138, now
  ublock-filters: 35983-162, now
  ublock-privacy: 937-60, now
  ublock-quick-fixes: 279-119, 41m
  ublock-unbreak: 2158-32, now
  urlhaus-1: 9500-0, now
filterset (user): [array of 1 redacted]
userSettings:
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 423 ms (selfie)
 maxAssetCacheWait: 212 ms
popupPanel:
 blocked: 4
 network:
  facebook.net: 1
  google.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by D4niloMR** [comment]
This is self-advertisement.

Add as a user filter:

`laptop88.vn##.banner`
`laptop88.vn##a[href^="/ad.php?"]`

Does the Vietnamese list add filters in this case?

@hoang-rio

**Comment by hoang-rio** [comment]
> This is self-advertisement.
> 
> Add as a user filter:
> 
> `laptop88.vn##.banner`
> `laptop88.vn##a[href^="/ad.php?"]`
> 
> Does the Vietnamese list add filters in this case?
> 
> @hoang-rio
> 

No. It doesn't
