### ISSUE TITLE
intro-hd.net: detection

### ISSUE THREAD

**Issue by Roaqe** [uBlockOrigin/uAssets#21093]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://intro-hd.net/pro-shaders-2-backlight-motion-design-2-mac-video-copilot/`

### Category

detection

### Description

the buttons doesn't work on the website

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 103659
 cosmetic: 44077
 scriptlet: 19487
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 75825-16, now
  easyprivacy: 33040-65, now
  plowe-0: 3779-1136, 1h.36m
  ublock-badware: 7536-138, 1h.36m
  ublock-filters: 35982-157, 1h.36m
  ublock-privacy: 937-12, now
  ublock-quick-fixes: 297-130, 1h.36m
  ublock-unbreak: 2158-32, 1h.36m
  urlhaus-1: 9500-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 861 ms (selfie)
 maxAssetCacheWait: 160 ms
popupPanel:
 blocked: 28
 network:
  intro-hd.net: 1
  doubleclick.net: 2
  google-analytics.com: 1
  googlesyndication.com: 11
  googletagmanager.com: 1
  gstatic.com: 11
  wp.com: 1
 extended:
  ##ins.adsbygoogle
  ##.active.mdpDeblocker-the-modal.mdpDeblocker-modal
```
</details>

**Comment by creativrss** [comment]
I'm still facing this issue, how did you fix this?
