### ISSUE TITLE
Pre Video ads

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#211]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

http://video.golem.de/games/17940/quake-1996-golem-retro.html

### Describe the issue

Pre Video Ads

### Versions

- Browser/version: Firefox 50
- uBlock Origin version: 1.9.16

**Comment by gorhill** [comment]
I can't make the video play with Firefox 50:

> Video kann nicht abgespielt werden
> You may download video here.
> You may want to use the latest version of Google Chrome to view this content.

It works with Google Chrome, but I do not see an ad.

**Comment by okiehsch** [comment]
I get PreRoll VideoAds with Google Chrome  pushed by
`https://hgc-cf-cache-1.svonm.com/hd-main.js`
maybe you need a german IP to get them.

**Comment by okiehsch** [comment]
If I simply block
`||hgc-cf-cache-1.svonm.com/hd-main.js$script`
there are no ads but I only get the audio part of the video.
The filter
`||hgc-cf-cache-1.svonm.com/hd-main.js$script,redirect=noopjs,domain=golem.de`
works on my end and solves the issue.

**Comment by gorhill** [comment]
> The filter `||hgc-cf-cache-1.svonm.com/hd-main.js$script,redirect=noopjs,domain=golem.de` works on my end and solves the issue.

If the redirect is `hd-main.js` instead of `noopjs`, does it work?

**Comment by okiehsch** [comment]
`hd-main.js` works as well.
