### ISSUE TITLE
rds.ca: breakage

### ISSUE THREAD

**Issue by manobert** [uBlockOrigin/uAssets#21115]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

The default uBlock Origin filters seem to break some pages on the rds.ca website

This is exactly the same issue than the ticket https://github.com/uBlockOrigin/uAssets/issues/18245, that was created for tsn.ca (we are the French version of tsn.ca, and share the same codebase)

### A specific URL where the issue occurs.

`https://www.rds.ca/hockey/lnh/resultat/rangers-rangers-ny-senateurs-ottawa-20231205/220081`

### Steps to Reproduce

-Download and Install uBlock Origin extension on your browser

-Go to any game page on RDS
(ex. `https://www.rds.ca/hockey/lnh/resultat/rangers-rangers-ny-senateurs-ottawa-20231205/220081`)

-You will only see the Event Status

-Click on uBlock Origin icon to stop the extension and reload the page

-All the widgets will be back

### Expected behavior

https://github.com/uBlockOrigin/uBlock-issues/assets/77703179/fdee8e42-0d5c-4508-a9ac-ed981f292966

### Actual behavior

https://github.com/uBlockOrigin/uBlock-issues/assets/77703179/26187fc6-34dc-4229-9235-74dc690a90f9

### Configuration

.

**Comment by Omega-6** [comment]
```
@@||stats.sports.bellmedia.ca/sports/hockey/leagues/nhl/event/*$xhr,domain=rds.ca
```

**Comment by mapx-** [comment]
add

`@@||stats.sports.bellmedia.ca/*/event$xhr,domain=rds.ca`

@ryanbr

**Comment by nqlp** [comment]
There are a few ads leftovers "Publicité" at the top and right side:

<img width="1905" height="506" alt="Image" src="https://github.com/user-attachments/assets/84c19ecb-2812-4861-8aaf-0fe78dca8c67" />

**Comment by mapx-** [comment]
add

```adb
rds.ca##.b-ads-custom.c-stack
```

report at Liste FR https://github.com/easylist/listefr/issues
