### ISSUE TITLE
nation.co.ke forces pages to reload with ads

### ISSUE THREAD

**Issue by kipyegonmark** [uBlockOrigin/uAssets#2111]
### URL(s) where the issue occurs

`nation.co.ke`

### Describe the issue

With Ublock Origin enabled, after a page completes loading the site forces the page to reload to show ads.

### Versions

- Browser/version: Firefox 60.0b16
- uBlock Origin version: 1.16.2

### Settings

- Default

### Notes

This behaviour seems to be related to the domain `mcjvwce.uzwcfbi.com` that seems to be hosting some JavaScript that forces the pages to reload.

**Comment by mapx-** [comment]
it should work
`nation.co.ke##script:inject(abort-current-inline-script.js, btoa, BOOTLOADER_LOADED)` 
in chrome but is failing

instead seems working
`||uzwcfbi.com/$script`

**Comment by okiehsch** [comment]
There is a race condition, so I can't consistently disable the inline script that causes the issue.

I can kill the process of reloading the site by adding
`nation.co.ke##script:inject(abort-on-property-write.js, $getWin)`.

**Comment by uBlock-user** [comment]
Just block `uzwcfbi.com` the domain doesn't serve any pages when visited.

**Comment by okiehsch** [comment]
I would say 
````
nation.co.ke##^script:has-text(BOOTLOADER_LOADED)
nation.co.ke##script:inject(abort-on-property-write.js, $getWin)
||uzwcfbi.com^
````
The `script:inject`t to make sure tha the fix still works when they change from `uzwcfbi.com` to another random domain.

**Comment by mapx-** [comment]
seems working too
`nation.co.ke##script:inject(abort-on-property-write.js, encodeURIComponent)`

**Comment by mapx-** [comment]
Where did you find `$getWin` ?
