### ISSUE TITLE
deezer.com: nuisance

### ISSUE THREAD

**Issue by farfallosa** [uBlockOrigin/uAssets#21149]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.deezer.com/de/profile/698797291/loved`

### Category

nuisance

### Description

After two songs, sometimes more, the "footer" at the bottom of the page changes. Instead of the tiny cover of the song, there is an "advert". Using U-Block blocks the ad, but stops the music and prevents me from playing another song. I have to reload the page every time. Then it starts all over again.

### Other extensions used

I have Privacy Badger disabled for this site

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![deezer_ad](https://github.com/uBlockOrigin/uAssets/assets/11560452/c33367d9-f02c-440e-83e5-97ec859bbb3a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 106152
 cosmetic: 48858
 scriptlet: 19261
 html: 1128
listset (total-discarded, last-updated):
 default:
  user-filters: 25-2, never
  ublock-filters: 36793-135, 39m
  ublock-badware: 7544-11, 39m
  ublock-privacy: 921-4, 39m
  ublock-unbreak: 2204-1, 39m
  ublock-quick-fixes: 298-67, 40m
  easylist: 75857-707, 40m
  easyprivacy: 33035-800, 40m
  urlhaus-1: 9640-0, 1h.41m
  plowe-0: 3779-1, 40m
  DEU-0: 7185-3, 1h.41m
filterset (user): [array of 30 redacted]
trustedset:
 added: [array of 29 redacted]
hostRuleset:
 added: [array of 12 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3612 ms
 maxAssetCacheWait: 1215 ms
popupPanel:
 blocked: 37
 network:
  adswizz.com: 7
  braze.com: 5
  doubleclick.net: 1
  dzcdn.net: 2
  facebook.net: 1
  googletagmanager.com: 1
  hubvisor.io: 7
  sentry.io: 12
  streamtheworld.com: 1
 extended:
  ##+js(no-setTimeout-if, Ads)
  ##+js(set-constant, smartLoaded, true)
```
</details>

**Comment by mapx-** [comment]
> Using U-Block blocks the ad

You see "Werbung" stuff and then you want to block it ? or you are saying when "werbung" appears deezer does not worl anymore ?

**Comment by mapx-** [comment]
I tested in FF / chrome, the ads are blocked but no interruption on my side.

**Comment by mapx-** [comment]
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
