### ISSUE TITLE
quora.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#2114]
### URL(s) where the issue occurs

`https://www.quora.com/`
`https://www.quora.com/Is-it-true-that-you-cant-jump-without-bending-your-knees`

### Describe the issue

Promoted section.
"Ad by TruthFinder" 

### Screenshot(s)

home screen:
![image](https://user-images.githubusercontent.com/12802056/39397810-4881b96a-4ad3-11e8-87e2-395ec06eb6c6.png)

specific question:
![image](https://user-images.githubusercontent.com/12802056/39397823-60154bd2-4ad3-11e8-9359-6486e5b88877.png)

### Versions

- Browser/version: Chrome 65
- uBlock Origin version: 1.16.2

### Settings

Default

**Comment by terrorist96** [comment]
That works for the ad on question pages, but not the one on the home page.

**Comment by terrorist96** [comment]
Also, on the home page, if you click (Read More) on an answer, at the end you'll see this type of ad:

![image](https://user-images.githubusercontent.com/12802056/39398129-5ce43be0-4ad7-11e8-9e81-c52d190487bf.png)

**Comment by mapx-** [comment]
what about
`quora.com##.AdBundle`

**Comment by terrorist96** [comment]
> what about
quora.com##.AdBundle

Yes, that works for the ads on the home page, but doesn't block ads that appear after clicking (Read More) on an answer.
(seems like you may need an account to see the home page feed)

**Comment by mapx-** [comment]
another 1
`quora.com##.content_rectangle:has(.advertiser_endpoint)`

**Comment by terrorist96** [comment]
Good.
Merge:
`quora.com##.content_rectangle:has-text(ad by)`
`quora.com##.content_rectangle:has(.advertiser_endpoint)`

`quora.com##.AdBundle` isn't needed if `quora.com##.content_rectangle:has(.advertiser_endpoint)` is added.

Thanks!

**Comment by terrorist96** [comment]
@mapx- actually, add `quora.com##.AdBundle` as well as it removes a residual frame where the ad woulda been on the home page. Sorry
