### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by Elemangtr** [uBlockOrigin/uAssets#21148]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=AONMEdy8H_k`

### Category

detection

### Description

Yotube adblock is blocking the video does not open

### Other extensions used

Adblocker Ultimate, Sound Boster, Youtube Dislike Button

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
![Ekran Alıntısı](https://github.com/uBlockOrigin/uAssets/assets/153132487/bc1117d5-b4c4-4e10-a191-d8104be57482)

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 280732
 cosmetic: 166945
 scriptlet: 42859
 html: 1128
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80565-7462, 3m
  adguard-mobile: 8788-156, 3m
  adguard-spyware-url: 1352-92, 3m
  adguard-spyware: 76717-17074, 3m
  block-lan: 55-0, 3m
  curben-phishing: 78359-29, 3m
  adguard-social: 22073-1316, 3m
  adguard-cookies: 28246-1604, 3m
  ublock-cookies-adguard: 637-0, 3m
  adguard-popup-overlays: 26539-938, 3m
  adguard-mobile-app-banners: 4819-17, 3m
  adguard-other-annoyances: 14024-16, 3m
  [2 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 36791-693, 3m
  ublock-badware: 7554-11, 3m
  ublock-privacy: 921-5, 3m
  ublock-unbreak: 2204-3, 3m
  ublock-quick-fixes: 299-67, 3m
  easylist: 75857-16983, 3m
  easyprivacy: 33035-885, 3m
  urlhaus-1: 9640-0, 3m
  plowe-0: 3779-1, 3m
  TUR-0: 13866-234, 3m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3344 ms (selfie)
 maxAssetCacheWait: 424 ms
popupPanel:
 blocked: 103
 no-cosmetic-filtering: true
 network:
  youtube.com: 41
  doubleclick.net: 7
  google.com: 55
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/20586

**Comment by Elemangtr** [comment]
Bro close it,

> duplicate #20586

i solved this problem close it
