### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by autc04** [uBlockOrigin/uAssets#21146]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.derstandard.at/`

### Category

detection

### Description

only detected when logged in to derstandard.at

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/1662219/e56c7911-3d5f-4dc3-8a0a-01e289554e02)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 103775
 cosmetic: 44062
 scriptlet: 19262
 html: 1128
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 36793-121, now
  ublock-badware: 7544-11, now
  ublock-privacy: 921-4, now
  ublock-unbreak: 2204-0, now
  easylist: 75857-701, now
  easyprivacy: 33035-791, now
  plowe-0: 3779-1, now
  urlhaus-1: 9640-0, now
  ublock-quick-fixes: 299-68, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 124 ms (selfie)
 maxAssetCacheWait: 69 ms
popupPanel:
 blocked: 20
 network:
  derstandard.at: 1
  adition.com: 3
  cleverpush.com: 1
  cxense.com: 2
  doubleclick.net: 5
  googletagmanager.com: 1
  iocnt.net: 2
  staticfiles.at: 2
  taboola.com: 1
  youtube.com: 2
 extended:
  ##ad-container
  ##.ytp-ad-progress-list
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by Omega-6** [comment]
ctrl + shift + a -> any other ad blocker?

**Comment by autc04** [comment]
no other ad blockers.
Site did not detect uBlock yesterday.

**Comment by autc04** [comment]
I have configured an exception for derstandard.at (the site started detecting that a while ago).

**Comment by autc04** [comment]
No. I have a non-paid account.

**Comment by Omega-6** [comment]
while on the page, please click on uBlock Origin's Icon🛡️=> 💭 => click on `Troubleshooting Information` => copy and paste here

**Comment by autc04** [comment]
That'sthe same thing as what has been automatically attached to the ticket, right?

```
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 103775
 cosmetic: 44062
 scriptlet: 19262
 html: 1128
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 36793-121, 1h.47m
  ublock-badware: 7544-11, 1h.47m
  ublock-privacy: 921-4, 1h.47m
  ublock-unbreak: 2204-1, 1h.47m
  easylist: 75857-701, 1h.47m
  easyprivacy: 33035-791, 1h.47m
  plowe-0: 3779-1, 1h.47m
  urlhaus-1: 9640-0, 1h.47m
  ublock-quick-fixes: 299-67, 1h.47m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 124 ms (selfie)
 maxAssetCacheWait: 69 ms
popupPanel:
 blocked: 18
 network:
  derstandard.at: 1
  adition.com: 3
  clarity.ms: 1
  cleverpush.com: 1
  cxense.com: 2
  doubleclick.net: 1
  googletagmanager.com: 3
  iocnt.net: 2
  sentry.io: 1
  staticfiles.at: 2
  taboola.com: 1
 extended:
  ##ad-container
  ```

**Comment by mapx-** [comment]
I tested in firefox, using a free account, no detection on my end

**Comment by autc04** [comment]
for me (free account, firefox, linux), detection happens randomly, sometimes after a few seconds, sometimes ater. I am not sure if it happens 100%.

**Comment by DiabeticCrab** [comment]
As of today, derStandard.at seemingly added a script that's loaded via staticfiles.at
The script removes the article and user forum from the website when run. Is this enough to reopen the issue?

**Comment by mapx-** [comment]
Test 

`derStandard.at##+js(nostif, event, 3000)`

**Comment by okiehsch** [comment]
`derStandard.at##+js(nostif, event, 3000)`

works on my end.

**Comment by derLaokrat** [comment]
> `derStandard.at##+js(nostif, event, 3000)`
> 
> works on my end.

Doesn't work for me. Still removing content & forum after a few seconds.

**Comment by DiabeticCrab** [comment]
@mapx-
Works for me, thank you very much! As a disclaimer, I'm also using a piHole, so maybe that's the reason I'm getting different results than Lao.

Additionally blocking "dialog" also removes the "pls giv money" prompt. With the nostif script thingy alone, it's shown for a split second, causing a flicker.

`derstandard.at##.dialog`

**Comment by Esokrates** [comment]
`derStandard.at##+js(nostif, event, 3000)` works here as well.

**Comment by Chron-O-John** [comment]
derStandard.at##+js(nostif, event, 3000)
works for me as well (I am using DNS-Adblock as well if that matters)

**Comment by D4niloMR** [comment]
`derstandard.at##+js(rpnt, script, "adsDisabled":false, "adsDisabled":true)`

This filter also works here without that flicker https://github.com/uBlockOrigin/uAssets/issues/21146#issuecomment-1863624869 

To use this filter in "My filters" is necessary to do this: https://github.com/uBlockOrigin/uAssets/issues/21255#issuecomment-1847499567

@DiabeticCrab can you confirm?

**Comment by DiabeticCrab** [comment]
@D4niloMR Works perfectly. I can now open articles in a new tab again too without getting blocked!

**Comment by okiehsch** [comment]
@rejuce 
Regarding https://github.com/uBlockOrigin/uAssets/issues/21534#issuecomment-1867470101
`derStandard.de##+js(nostif, event, 3000)`
works for me without it "coming back".
I assume you mean it comes back if you click through different articles?

**Comment by rejuce** [comment]
exactly..clicking an article, it pops up briefly and disappears, opening an article with middle mouse button in new tab, it stays and wont go away in that tab

**Comment by okiehsch** [comment]
>  opening an article with middle mouse button in new tab, it stays and wont go away in that tab

I can't reproduce on my end.
