### ISSUE TITLE
[nsfw] saveporn.net: nuisance

### ISSUE THREAD

**Issue by webhunted** [uBlockOrigin/uAssets#21153]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.saveporn.net/`

### Category

nuisance

### Description

Download popup appears

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-06 230024](https://github.com/uBlockOrigin/uAssets/assets/151805876/6cfd6ae1-a1a0-4826-83c0-ce00cba43197)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 104080
 cosmetic: 44053
 scriptlet: 19476
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75847-16, 25m
  easyprivacy: 33036-65, now
  plowe-0: 3779-1136, now
  ublock-badware: 7555-138, 25m
  ublock-filters: 35911-162, 25m
  ublock-privacy: 927-12, now
  ublock-quick-fixes: 299-130, 25m
  ublock-unbreak: 2163-32, 25m
  urlhaus-1: 9930-0, 25m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  chrome-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 206 ms (selfie)
 maxAssetCacheWait: 68 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by huyszn** [comment]
`saveporn.net###itfloater_wd`

**Comment by mapx-** [comment]
report at [easylist repository](https://github.com/easylist/easylist/issues)
