### ISSUE TITLE
fmoviesz.to: ads

### ISSUE THREAD

**Issue by xelleze** [uBlockOrigin/uAssets#21155]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fmoviesz.to/movie/killers-of-the-flower-moon-00pz7/1-1`

### Category

ads

### Description

When clicking on pause a box with ads inside shows up.  

It is inside  `div class="container watch-page"`  -> `div class="player-main"` -> `div id="player"` -> `#document` -> `<html>` -> `body` inside of the body and after `div id="player-wrapper"` . 

It seems that with each refresh the class id of the div box gets randomly generated new id keys

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/21974188/ae4011f0-2bb6-4b3b-895b-d83508bf512f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 104085
 cosmetic: 44071
 scriptlet: 19475
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 20-1, never
  easylist: 75847-16, 4m
  easyprivacy: 33036-65, 4m
  plowe-0: 3779-1136, 4m
  ublock-badware: 7555-138, 4m
  ublock-filters: 35911-162, 4m
  ublock-privacy: 927-12, 4m
  ublock-quick-fixes: 299-128, 4m
  ublock-unbreak: 2163-31, 4m
  urlhaus-1: 9930-0, 4m
filterset (user): [array of 20 redacted]
trustedset:
 removed:
  chrome-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2388 ms
 maxAssetCacheWait: 16 ms
popupPanel:
 blocked: 9
 network:
  amung.us: 1
  bidgear.com: 1
  disposalangrily.com: 2
  disqus.com: 1
  effectslacybulb.com: 1
  googletagmanager.com: 1
  sharethis.com: 2
 extended:
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by CloverCorp** [comment]
Seems to be unfixed/broken still as of 11:14 12/7/23 (purged filters and updated)

**Comment by mapx-** [comment]
update uBO filters

**Comment by nadesco** [comment]
Same issue here, I get the same ad as in the screenshot above but different movie. 
https://fmoviesz.to/movie/the-international-mw0z/1-1

I've gone through the prerequisites including purging and updating filters. I also tried a different browser (with uBO installed) but the ad keeps reappearing whenever I pause it. I noticed it disappeared for a while but it's back again and I'm unable to block it. As per CloverCorp's comment..

**Comment by Omega-6** [comment]
Are you using uBlock Origin Lite?

**Comment by Omega-6** [comment]
we genraly ask of users to test using the default configuration

**Comment by nadesco** [comment]
Ok, I'll make a back up, reset it to default and try again.

**Comment by nadesco** [comment]
Update; I just set uBO back to the default configuration and reloaded the movie but the ad is still there.

**Comment by nadesco** [comment]
Didn't think it was necessary but thought I'd update the filter list again with the default configuration. That got rid of the ad so thanks for the tip.
