### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by mgeshev** [uBlockOrigin/uAssets#21160]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/`

### Category

detection

### Description

On every youtube video, they detect the uBlock

### Other extensions used

Nothing to preview

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 104085
 cosmetic: 44053
 scriptlet: 19474
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75847-16, 1h.26m
  easyprivacy: 33036-65, 51m
  plowe-0: 3779-1136, 51m
  ublock-badware: 7555-138, 51m
  ublock-filters: 35911-162, 51m
  ublock-privacy: 927-12, 1h.26m
  ublock-quick-fixes: 299-128, 1h.26m
  ublock-unbreak: 2163-31, 51m
  urlhaus-1: 9930-0, 51m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 184 ms (selfie)
 maxAssetCacheWait: 75 ms
popupPanel:
 blocked: 5
 network:
  youtube.com: 1
  doubleclick.net: 4
 extended:
  ###related > div#player-ads
  ###ytd-player button.ytp-suggested-action-badge
  ##.ytp-ad-progress-list
  ##[layout*="display-ad-"]
  ##[target-id="engagement-panel-ads"]
  ##div.ytd-ad-slot-renderer
  ##div.ytd-in-feed-ad-layout-renderer
  ##ytd-ad-slot-renderer
  ##ytd-rich-item-renderer:has(> .ytd-rich-item-renderer > ytd-ad-…
  ##ytd-rich-item-renderer:has(ytd-display-ad-renderer)
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mgeshev** [comment]
Again YT detect uBlock

**Comment by stephenhawk8054** [comment]
Follow the steps in this thread: https://github.com/uBlockOrigin/uAssets/issues/20586

Don't tick this box just for the sake of submitting the report

> - [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
