### ISSUE TITLE
nba.com: ads

### ISSUE THREAD

**Issue by koalasama** [uBlockOrigin/uAssets#21165]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.nba.com/game/phi-vs-was-0022301208?watchFullGame`

### Description

On NBA league pass, i get unskippable video ads at start of game then periodically during the games. The ad block the ability to collapse a full screen or mute the ad.

### Other extensions used

Dashlane
old reddit redirect

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-07 111555](https://github.com/uBlockOrigin/uAssets/assets/149536377/0512aee7-aec7-4626-aa08-350598bfca68)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 103806
 cosmetic: 44056
 scriptlet: 19278
 html: 1129
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  ublock-filters: 36791-228, 1h.3m
  ublock-badware: 7559-11, 1h.3m
  ublock-privacy: 921-4, 1h.3m
  ublock-unbreak: 2209-0, 1h.3m
  ublock-quick-fixes: 301-67, 1h.3m
  easylist: 75847-548, 1h.3m
  easyprivacy: 33059-833, 3d.14h.12m
  urlhaus-1: 9640-0, 13h.5m
  plowe-0: 3779-1, 1d.18h.41m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 992 ms (selfie)
 maxAssetCacheWait: 854 ms
```
</details>

**Comment by Omega-6** [comment]
Is a paid subscription required?

**Comment by Omega-6** [comment]
On the NBA webpage, click on uBlock Origin's icon 🛡️ -> 💭 -> `Troubleshooting Information` -> `Select all` -> Copy -> Paste Here please

**Comment by Omega-6** [comment]
please open the logger on the NBA webpage

![image](https://github.com/uBlockOrigin/uAssets/assets/152656980/92b27632-28ce-4c51-8ba4-7335728ea000)

Select blocked

![image](https://github.com/uBlockOrigin/uAssets/assets/152656980/ed81d42c-da47-4e5e-939a-1ed2f0edadb7)

send a screenshot here

**Comment by koalasama** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/149536377/03ba0802-ba0d-458f-9a13-1151da1760d3)

**Comment by mapx-** [comment]
@Omega-6 without an account we cannot do anything - please take a break.

**Comment by Omega-6** [comment]
Oh why'd I ask for blocked? The issue's about ads.. Could you please unselect blocked? Even though I'm not sure if it'll help.

**Comment by koalasama** [comment]
@Omega-6 do you need the logger without the 'blocked' filter ? 
About the account , I believe there is a 7day free trial, but credit card info is required i'm pretty sure.

**Comment by okiehsch** [comment]
No, I only got  accounts for MLB and NFL.

**Comment by mapx-** [comment]
@koalasama in order to investigate, we need an account: are you willing to give us your credentials ? if you confirm I'll provide an email address.

**Comment by mapx-** [comment]
my email address: `axis.trivia@gmail.com`

**Comment by koalasama** [comment]
Hello @stephenhawk8054, I'm from France. 
The filters you gave me seem to work, tried to open different games and no ads!
thanks a lot !
@mapx- I'm changing my password back

Thanks everybody, you are modern day heroes
