### ISSUE TITLE
vtube.network: detection

### ISSUE THREAD

**Issue by swiezaczek** [uBlockOrigin/uAssets#21176]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vtube.network/embed-8mkf1a0rskq6.html`

### Category

detection

### Description

page is not loading if ublock switched on - just white screen shows up

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.1b6
Chromium: 119
filterset (summary):
 network: 105483
 cosmetic: 51627
 scriptlet: 19679
 html: 0
listset (total-discarded, last-updated):
 added:
  POL-0: 8011-11, now
  POL-2: 1280-13, now
 default:
  user-filters: 0-0, never
  easylist: 75847-39, now
  easyprivacy: 33036-65, now
  plowe-0: 3780-1144, now
  ublock-badware: 7555-138, now
  ublock-filters: 35895-200, now
  ublock-privacy: 927-12, now
  ublock-quick-fixes: 297-128, now
  ublock-unbreak: 2163-32, now
  urlhaus-1: 9930-0, now
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3438 ms (selfie)
 maxAssetCacheWait: 1840 ms
popupPanel:
 blocked: 3
 network:
  googletagmanager.com: 3
```
</details>

**Comment by Omega-6** [comment]
Do you have a different URL?
