### ISSUE TITLE
facet.wp.pl

### ISSUE THREAD

**Issue by F4z** [uBlockOrigin/uAssets#212]
Google Chrome 54.0.2840.99 m/Mozilla Firefox 50.0.2
uBlock Origin 1.10.0

Here - `http://facet.wp.pl/technologie` are ads leftovers and it is difficult to hide them, because wp.pl very often changes classes names of these elements.

I noticed that these elements have `background-image: url(data:image/png;base64,...`
![image](https://cloud.githubusercontent.com/assets/11742596/20773795/e86b7750-b753-11e6-89da-0ee2a21701ee.png)

I added this rule:
`facet.wp.pl##div[class^="_"]:matches-css(background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAAtCAMAAADMQ1gEAAACiFBMVEUAAAD///////+qqqq/v7/MzMzV1dXb29u/v7/GxsbMzMzR0dHV1dXExMTIyMjMzMzPz8/S0tLGxsbMzMzR0dHIyMjKysrMzMzOzs7IyMjKysrMzMzOzs7Pz8/Ly8vMzMzPz8/JycnLy8vMzMzNzc3Ozs7KysrLy8vNzc3Ozs7KysrLy8vMzMzNzc3Ozs7KysrLy8vMzMzNzc3Ozs7KysrLy8vMzMzNzc3KysrLy8vMzMzNzc3Ozs7Ly8vLy8vMzMzNzc3Ly8vNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vLy8vMzMzNzc3Nzc3Ly8vLy8vMzMzNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vMzMzMzMzMzMzNzc3MzMzMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzNzc3Ly8vMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzLy8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3MzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3MzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMx9Jm/RAAAA13RSTlMAAQIDBAUGBwgJCgsMDQ4PEBESFBYXGBkaHB0eHyAiIyUmJygpKissLi8wMTIzNDU2Nzg5Ojs8PT9AQUJDREVGR0lMTU5PUVJTVFVWV1hZWltcXV5gYWJjZWZnaGlqa21ucHFydHd4eXp7fH+AgYKDhoeIiYqLjI2Oj5GSk5SVlpeYmZqbnJ2eoKGjpKWmp6ipqqusra6vsbO0tba3uLm7vb6/wMHCw8XGx8jJysvMzc7P0NLT1NXX2Nna29zd3uDh4uPk5ebn6Ozt7vHy8/T19vf5+vv8/oGvxekAAANiSURBVHgB7dLrW1RVFIDxdxiERCkSSIlLUmRlTolFRCZUaiVmSpJFCVoEWWbaGFLRxSYpLVOIzC5aUJZxCQuwEhutwAgxsUTWv9Pae87AYR7Fh+/+PriW8+x34OwD1sxDInK8iInytIm1mbDohS/412RxMbeII4eQub+LsS8NK7P6tedXP7QgcwoRssXxLlb6KQnpSUIl/i2OjlUe3GIHJeQ41jsStge1VEbtGlvuF0c6xh8SNnw18Jy4lOG2RhwrUQkR594Wl9+icEkTx7bRR+6z5xuAz3UO+P01gZ2ndcvDrdMJj6Dut+uBe0UdBTp0dmEs160St03hZ7oKKLNr3bRh80E8mEttwojT7WXccsSxBNhotxp+Db3aWPMFOzFidH0TN2/4Vb0ObLXbOnaYUUqKGdUj3+9njA+csBP4yG7FrDYjwGwznoGYZF+rbo8xxsPhh0yEJrvlc7MZrdxtRlHUF2KdS2WMhLNO+QActsv1RA/qGPQuETU/V0K2E6FRQl61t6guh2/NzCoRlblcrO+nEuEpJ2wzt6gGgCpRyypFxWWc039/KZ9EpAwnPDsl1c6fgQdF+U1+Eu5c7EvifNqdcsEcO/ZD6EU01tk/oAurcMIN99hRi+oRRwsXFv5dm5+0Yz2qThwbGUeHuBWjFklIfwrj2CAuQ9NRnvpQl894Us64wios79qWYPumZMZXISO+jmUCPFuGxfrvlUlMTPYbbf3HPqtM4WIuuSQQCFQXRumsVyVsvhFiqm6lPgNr8q7bgNyA/e/iQAJw+3selFQUrjhUA71FPp8vjd6FENjtQXxYjwx9CJTIFlSXzADqh/IAe+Kufg11gglLmyczEn6z/kyChp19l8G8DhMmnqjZHg5X/egK87qTGQlnDsS1PqFh054VUFtuwqffmn06HpCv6lv6rtWiJxgMJtF7dKCU0fClHaxt1vBg/nfE/5Vuwq4cDj8KSJHvjsatrp9438mskTD6RHVhmVxHyQ+e7lmP107XcN4/Sws/OeCcyD3mCll35MpwuOhPvfSf/JS0U17Tmj1Dw20H9aN/rwmduGnM5Xh2f+l1wr3PAgW9Xg2n9Xeg4dRTNwANL0JQlyu6Z7GvXb1P83yI+7SYdmNuSyrgbZqzbC/4V5IUTCpoQBV8zP9FOJzfMoGB/QAAAABJRU5ErkJggg=="))`
and it works.

There is little information about matches-css rules on wiki - https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#matches-css so I would ask if it is possible to use `matches-css` rules with `*`?
For example this:
`facet.wp.pl##div[class^="_"]:matches-css(background-image: url("data:image/png;base64*)`
It works in element picker, but if I add this rule to "My filters" and then reload website it does not work.
So, is not possible to use `*` with `matches-css` rules, or maybe it is possible, but in other way?

**Comment by gorhill** [comment]
I need to work on the implementation of these cosmetic filter operators to make them chainable and usable inside `:has()` filters (as discussed in <https://github.com/gorhill/uBlock/issues/1930#issuecomment-241997548>).

While doing this, adding support for the option to use regex instead of plain strings should not be a problem.

**Comment by F4z** [comment]
Ok, thank you for your answer.

**Comment by gorhill** [comment]
By the way, if I select the Polish filter list, I see no placeholders.

**Comment by F4z** [comment]
Yes, because this rule is in Polish filter list.

`facet.wp.pl##div[class^="_"]:matches-css(background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADgAAAAtCAMAAADMQ1gEAAACiFBMVEUAAAD///////+qqqq/v7/MzMzV1dXb29u/v7/GxsbMzMzR0dHV1dXExMTIyMjMzMzPz8/S0tLGxsbMzMzR0dHIyMjKysrMzMzOzs7IyMjKysrMzMzOzs7Pz8/Ly8vMzMzPz8/JycnLy8vMzMzNzc3Ozs7KysrLy8vNzc3Ozs7KysrLy8vMzMzNzc3Ozs7KysrLy8vMzMzNzc3Ozs7KysrLy8vMzMzNzc3KysrLy8vMzMzNzc3Ozs7Ly8vLy8vMzMzNzc3Ly8vNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vLy8vMzMzNzc3Nzc3Ly8vLy8vMzMzNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vLy8vNzc3Nzc3Ly8vMzMzMzMzMzMzNzc3MzMzMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzNzc3Ly8vMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzLy8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3MzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3MzMzMzMzMzMzNzc3Ly8vMzMzMzMzNzc3Ly8vMzMzMzMzMzMzNzc3Ly8vMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMx9Jm/RAAAA13RSTlMAAQIDBAUGBwgJCgsMDQ4PEBESFBYXGBkaHB0eHyAiIyUmJygpKissLi8wMTIzNDU2Nzg5Ojs8PT9AQUJDREVGR0lMTU5PUVJTVFVWV1hZWltcXV5gYWJjZWZnaGlqa21ucHFydHd4eXp7fH+AgYKDhoeIiYqLjI2Oj5GSk5SVlpeYmZqbnJ2eoKGjpKWmp6ipqqusra6vsbO0tba3uLm7vb6/wMHCw8XGx8jJysvMzc7P0NLT1NXX2Nna29zd3uDh4uPk5ebn6Ozt7vHy8/T19vf5+vv8/oGvxekAAANiSURBVHgB7dLrW1RVFIDxdxiERCkSSIlLUmRlTolFRCZUaiVmSpJFCVoEWWbaGFLRxSYpLVOIzC5aUJZxCQuwEhutwAgxsUTWv9Pae87AYR7Fh+/+PriW8+x34OwD1sxDInK8iInytIm1mbDohS/412RxMbeII4eQub+LsS8NK7P6tedXP7QgcwoRssXxLlb6KQnpSUIl/i2OjlUe3GIHJeQ41jsStge1VEbtGlvuF0c6xh8SNnw18Jy4lOG2RhwrUQkR594Wl9+icEkTx7bRR+6z5xuAz3UO+P01gZ2ndcvDrdMJj6Dut+uBe0UdBTp0dmEs160St03hZ7oKKLNr3bRh80E8mEttwojT7WXccsSxBNhotxp+Db3aWPMFOzFidH0TN2/4Vb0ObLXbOnaYUUqKGdUj3+9njA+csBP4yG7FrDYjwGwznoGYZF+rbo8xxsPhh0yEJrvlc7MZrdxtRlHUF2KdS2WMhLNO+QActsv1RA/qGPQuETU/V0K2E6FRQl61t6guh2/NzCoRlblcrO+nEuEpJ2wzt6gGgCpRyypFxWWc039/KZ9EpAwnPDsl1c6fgQdF+U1+Eu5c7EvifNqdcsEcO/ZD6EU01tk/oAurcMIN99hRi+oRRwsXFv5dm5+0Yz2qThwbGUeHuBWjFklIfwrj2CAuQ9NRnvpQl894Us64wios79qWYPumZMZXISO+jmUCPFuGxfrvlUlMTPYbbf3HPqtM4WIuuSQQCFQXRumsVyVsvhFiqm6lPgNr8q7bgNyA/e/iQAJw+3selFQUrjhUA71FPp8vjd6FENjtQXxYjwx9CJTIFlSXzADqh/IAe+Kufg11gglLmyczEn6z/kyChp19l8G8DhMmnqjZHg5X/egK87qTGQlnDsS1PqFh054VUFtuwqffmn06HpCv6lv6rtWiJxgMJtF7dKCU0fClHaxt1vBg/nfE/5Vuwq4cDj8KSJHvjsatrp9438mskTD6RHVhmVxHyQ+e7lmP107XcN4/Sws/OeCcyD3mCll35MpwuOhPvfSf/JS0U17Tmj1Dw20H9aN/rwmduGnM5Xh2f+l1wr3PAgW9Xg2n9Xeg4dRTNwANL0JQlyu6Z7GvXb1P83yI+7SYdmNuSyrgbZqzbC/4V5IUTCpoQBV8zP9FOJzfMoGB/QAAAABJRU5ErkJggg=="))`

**Comment by gorhill** [comment]
> Yes, because this rule is in Polish filter list.

Nice to see the new cosmetic filter operators being used by filter list maintainers, that is the whole purpose, to make life of maintainers easier. Given this, I will treat this request as a priority.

**Comment by F4z** [comment]
Thank you.
I really like new cosmetic filter operators and `script:inject`, it is very useful.
Unfortunately `:style` operator breaks Adblock/Adblock Plus, so not all rules are added to main Polish filter list and it is additional filter list (some of rules are experimental) -  https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt

It is also nice that now we can use arguments with `script:inject`, so it easier to block specific advertisements, for example on `facet.wp.pl` and other `wp.pl` websites I think.
(This rule was added to Polish filter list to block these ads - `facet.wp.pl##script:inject(abort-on-property-write.js, gafBodies)` I do not know too much about javascript, so I hope it does not break website functionality)
These websites use random address to load ads and also check if "adblock is enabled" and if they detect "adblock" they block video.
For example here - `http://sportowefakty.wp.pl/pilka-nozna/649628/transferowy-niewypal-ssc-napoli-kosztowal-prawie-15-mln-euro-nie-rozegral-jeszcz`

![image](https://cloud.githubusercontent.com/assets/11742596/20805964/4080a974-b7f9-11e6-9114-a8a6431649d8.png)

Until yesterday, they checked only if addresses/scripts/connections like these are blocked:
`http://fntajkb.wp.pl/cHcxOGZtdF81Y2pxeDI5Z251LDZka3J5M2Fob3YwN2Vsc3o0YmlwdzE4Zm10XzVjanF4MjlnbnUsNmRrcnkzYWhvdjA3ZWxzejRiaXB3MThmbXRfNWNqcXgyOWdudSw2ZGtyeTNhaG92MDdlbHN6NGJpcHcxOGZtdF81Y2ouZ2lmPw==`
`http://owabgxis.wp.pl/c3dfMjZhZWltcXV5MDQ4Y2drb3N3XzI2YWVpbXF1eTAuanM=`
they change these often, but always contains this:
`window.WP.advertisement = 'fntajkb';`
`window.WP.advertisement = 'owabgxis';`
it was also this, but now I can not find it:
`window.WP.advertisement = 'rek.www';`
(usually there were four addresses, but today I found only these two)
but from yesterday, they **probably** check if video advertisement is loaded and if not, video is blocked.

![image](https://cloud.githubusercontent.com/assets/11742596/20806272/8a418546-b7fa-11e6-90ed-4f233f453d19.png)

Link to script which "loads" ads - `http://fntajkb.wp.pl/Z2FmLmpzP3Jlc3BvbnNlVmVyc2lvbj0xJnJla2lkcz0yMzIzMTgmc249c3BvcnRvd2VmYWt0eSZfPTM3Mjg3NzIwMzA2OSZwaHRtbD1zcG9ydG93ZWZha3R5LndwLnBsL3BpbGthLW5vem5hLzY0OTYyOC90cmFuc2Zlcm93eS1uaWV3eXBhbC1zc2MtbmFwb2xpLWtvc3p0b3dhbC1wcmF3aWUtMTUtbWxuLWV1cm8tbmllLXJvemVncmFsLWplc3pjeiZQV0FyZWY9dW5rbm93biZQV0Fzdz0xOTIwJlBXQXNoPTk3NSZmbHN0YXRpZD1kJlBXQV9hZGJkPTEmUkVLdGFnaT1tYXJrb19yb2c7cGlsa2Ffbm96bmFfd2Vfd2xvc3plY2g7cGlsa2Ffd19ldXJvcGllO25lYXBvbDt3bG9jaHk7c2VyaWVfYTtwaWxrYV9ub3puYTtzc2NfbmFwb2xpJnNmX2FydGljbGU9MSZiY3Y9Mg==`

I noticed that if I add this rule:
`||rek.www.wp.pl/vad.xml$xmlhttprequest,redirect=noopframe,important`
I can watch videos and I do not have message about adblock, but it works only in Google Chrome, not in Mozilla Firefox.

**Comment by gorhill** [comment]
Filter like:

    facet.wp.pl##div[class^="_"]:matches-css(background-image: /^url\("data:image/png;base64,/)

Works with 1.10.1b0 and above.

**Comment by F4z** [comment]
Yes, it works, thank you.
