### ISSUE TITLE
vgmlinks.net: popups

### ISSUE THREAD

**Issue by adsdestroyer** [uBlockOrigin/uAssets#21208]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vgmlinks.net/55201/`

### Category

ads

### Description

popup betting ad- `https://baterybet.com`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Snap92](https://github.com/uBlockOrigin/uAssets/assets/109018577/c1df59a4-1996-42a6-a25d-4bc0c187244f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 104643
 cosmetic: 44031
 scriptlet: 19251
 html: 1129
listset (total-discarded, last-updated):
 default:
  user-filters: 10-0, never
  ublock-filters: 36726-106, now
  ublock-badware: 7557-11, now
  ublock-privacy: 921-4, now
  ublock-unbreak: 2200-0, now
  ublock-quick-fixes: 286-67, now
  easylist: 75853-701, now
  easyprivacy: 33072-793, now
  urlhaus-1: 10480-0, now
  plowe-0: 3780-1, now
filterset (user): [array of 10 redacted]
trustedset:
 added: [array of 258 redacted]
 removed:
  about-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 770 ms (selfie)
 maxAssetCacheWait: 404 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  ssindserving.com: 1
```
</details>

**Comment by Omega-6** [comment]
```
vgmlinks.net##+js(nowoif)
```
