### ISSUE TITLE
tiaa.org:‌ breakage

### ISSUE THREAD

**Issue by seb1525** [uBlockOrigin/uAssets#21214]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I login to the tiaa.org website, it no longer recognizes my computer and sends a code to my phone to confirm.  It's supposed to remember the computer I'm on and not do that.  This changed as soon as I installed uBLock origin on my computer. (ANother computer that doesn't have uBLock installed still behaves correctly.)  TIAA support told me that their web site is receiving "browser: Firefox, operating system: unknown" from my login and that's why it's not recognizing my computer.  It looks like this is something uBLock is doing. (I tried disabling it on the tiaa.org page but it made no difference.)
How can I fix this? (Note that I had to check all the boxes in order to submit this, even though some of them are not true, like about disabling UBO making the problem go away - it doesn't.)

### A specific URL where the issue occurs.

`https://tiaa.org`

### Steps to Reproduce

Login to tiaa.org (you must have an account there).  Specify "Remember me" on the login page.

### Expected behavior

SHow the initial TIAA page.

### Actual behavior

Asks me to receive a code via text first.

### uBO version

1.54.0

### Browser name and version

Mozilla Firefox 115.0.3

### Operating System and version

Windows 7

**Comment by mapx-** [comment]
closing for now, @seb1525 add a comment here if you have a feedback for us
