### ISSUE TITLE
prehraj.to: ads and nuisance

### ISSUE THREAD

**Issue by Mrkripl** [uBlockOrigin/uAssets#21219]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://prehraj.to/`

### Category

ads and nuisance

### Description

movie player has about 10 to 30 ads (depends on length of movie) and if you refresh mid movie it says you have to pay to watch again

### Other extensions used

fast forward, dislikes on youtube

### Screenshot(s)

<details><summary>Screenshot(s)</summary>
<p>

![image](https://github.com/uBlockOrigin/uAssets/assets/92227052/fb9c1c41-d07b-405a-8733-cad068786e7c)
![image](https://github.com/uBlockOrigin/uAssets/assets/92227052/0576fcc4-c654-4779-8285-447871156b63)

</p>
</details> 

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 104881
 cosmetic: 44448
 scriptlet: 19612
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  CZE-0: 833-1, now
  easylist: 75853-20, now
  easyprivacy: 33072-71, now
  plowe-0: 3780-1138, now
  ublock-badware: 7553-138, now
  ublock-filters: 35849-162, now
  ublock-privacy: 927-12, now
  ublock-quick-fixes: 171-10, now
  ublock-unbreak: 2154-31, now
  urlhaus-1: 10480-0, now
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 464 ms (selfie)
 maxAssetCacheWait: 161 ms
popupPanel:
 blocked: 8
 network:
  prehraj.to: 5
  googletagmanager.com: 2
  imasdk.googleapis.com: 1
 extended:
  ##.ima-ad-container
```
</details>

**Comment by D4niloMR** [comment]
Please share the link here.

**Comment by Mrkripl** [comment]
sorry for very late feedback
the original one was deleted on the site but allmost all movies on there have the same player
https://prehraj.to/oppenheimer-2023-cz-dabing-fullhd-hevc-1080p-hq/654ca6fc4fb2f

**Comment by D4niloMR** [comment]
I get `404 Not Found` even with Czech IP

**Comment by Mrkripl** [comment]
thats weird the link works for me but with the nuisance since I opened it once already
![image](https://github.com/uBlockOrigin/uAssets/assets/92227052/7e7ddc7a-76e5-4750-a19b-a6cb387fc2ab)
