### ISSUE TITLE
[nsfw] incestflix.com: popups

### ISSUE THREAD

**Issue by nfswissue** [uBlockOrigin/uAssets#21211]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`http://www.incestflix.com/watch/cyndi-sinclair-vivianne-desilva-perv-nana-3`

### Category

popups

### Description

Pop up ads are not blocked 

### Other extensions used

Darkreader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 120
filterset (summary):
 network: 106046
 cosmetic: 35234
 scriptlet: 19311
 html: 1129
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37055-315, 1m
  ublock-badware: 7551-11, 1m
  ublock-privacy: 921-5, 1m
  ublock-unbreak: 2205-1, 1m
  ublock-quick-fixes: 171-2, 1m
  adguard-mobile: 8788-128, 1m
  easylist: 75853-16743, 1m
  easyprivacy: 33072-802, 1m
  urlhaus-1: 10480-0, 1m
  plowe-0: 3780-1, 1m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 902 ms (selfie)
 maxAssetCacheWait: 182 ms
popupPanel:
 blocked: 5
 network:
  adsco.re: 1
  amung.us: 1
  d2klx87bgzngce.cloudfront.net: 1
  google-analytics.com: 1
  intelligenceadx.com: 1
 extended:
  ##+js(abort-on-property-write, _pop)
```
</details>

**Comment by Omega-6** [comment]
`||ogwmubfnjbzyo.com^` @ryanbr
