### ISSUE TITLE
hotcopper.com.au [Anti Ad Block]

### ISSUE THREAD

**Issue by jamesfox1234** [uBlockOrigin/uAssets#2122]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[hotcopper.com.au]`

### Describe the issue

[Anti adblock]

### Screenshot(s)

[N/A]

### Versions

- Browser/version: [Chrome Version 65.0.3325.181]
- uBlock Origin version: [1.16.2]

### Settings

- [Default]

### Notes

[N/A]

**Comment by zaphodbeebblebrox** [comment]
```
hotcopper.com.au###hc-adblock-main-div
hotcopper.com.au###hc-adblock-expose-mask
```
