### ISSUE TITLE
Video tag preventing filtering.

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uAssets#2123]
### URL(s) where the issue occurs

​https://secure.fanboy.co.nz/test/ (NSFW) Used on pornhub. 

### Describe the issue

Unable to filter within `<video>`

### Versions

- Browser/version: Firefox Nightly
- uBlock Origin version: v1.16.2
- Just Easylist, no ublock filters enabled.

### Settings

```
fanboy.co.nz##[href*="data:"]
fanboy.co.nz##[src*="base64"]
fanboy.co.nz##[src*="blob:"]
fanboy.co.nz##[src*="data:"]
fanboy.co.nz##[style*="background-image:"]
fanboy.co.nz##[style*="blob:"]
fanboy.co.nz##[style*="base64"]
fanboy.co.nz##[style*="cursor:pointer"]
fanboy.co.nz##[onclick*="window"]
fanboy.co.nz##[onclick]
fanboy.co.nz##div[onclick]
fanboy.co.nz##div[onclick*="window"]
```

### Notes

Affects ABP also (reported there also). Video tag seems to stop these legit filters from working?

**Comment by ryanbr** [comment]
Seems to affect Firefox, but not Chrome

**Comment by gwarser** [comment]
Do you want to block the image, video or counter?
Source html is malformed, and picker is lost. Manually created filters works fine.

**Comment by ryanbr** [comment]
a csp filter is one way, but I'm trying get a more generic method. 

Is it a limitation where an element can't filter this normally? Seems pretty large loophole, where anything in an 'video' tag would remain open.

**Comment by gwarser** [comment]
It's bit complicated. It's like you want to block javascript by cosmetic filtering.
 
`|data:$domain=fanboy.co.nz` is also working here (by https://github.com/gorhill/uBlock/issues/2757).

**Comment by uBlock-user** [comment]
Seems to be a FF limitation, works fine on Chromium.

**Comment by ryanbr** [comment]
What I'm basically saying, this filters:

```
##[src*="data:"]
##[src*="base64"]
```

Should also filter this; source src=

`<video autoplay="" loop=""><source src="data:video/mp4;base64,..</video>`

**Comment by ryanbr** [comment]
> Seems to be a FF limitation, works fine on Chromium.

For a brief moment i thought so, but the ads still showed (possibly a fall back method?)

**Comment by uBlock-user** [comment]
> but the ads still showed
Ads as in ?

I added the filters you posted in the settings and this is how it appears on Chromium 68 - https://i.gyazo.com/f2e2e46475f36fc4dd0a8fb873435474.png

**Comment by gwarser** [comment]
I see no difference between Firefox Nightly and Chromium 65.

**Comment by gorhill** [comment]
You can't use cosmetic filtering to _block_ resources. Cosmetic filtering is to _hide_ stuff in the DOM, not to prevent the browser from using a resource. The same way a filter such as `iframe[src="https://example.com"]` won't prevent `http://example.com`  from being downloaded by the browser, it will just hide the iframe. Asking to change the semantic of cosmetic filtering for these specific case really not a good idea.

As @gwarser said, use `|data:`, `|blob` filters, they work with uBO.

**Comment by gwarser** [comment]
If you create filter `github.com##head>title`, will this filter prevent browser from showing page title "Video tag preventing filtering. · Issue #2123 · uBlockOrigin/uAssets" on this tab? This tag is already hidden. `source` is just hint/description for `video` element.

**Comment by gorhill** [comment]
For the `fanboy.co.nz##div[onclick]` case, this is uBO's solution:

    fanboy.co.nz##script:inject(remove-attr.js, onclick)
