### ISSUE TITLE
finance.yahoo.com: breakage

### ISSUE THREAD

**Issue by SledgeHammer01** [uBlockOrigin/uAssets#21254]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://finance.yahoo.com/quote/NVDA/community?p=NVDA`

### Description

Yahoo Finance Community started hanging this morning 12/8/23 with uBlock enabled. If I disable ublock it works, but then I get a ton of ads. I just get a spinning cursor where the messages would normally appear. I've cleared my browser cache, etc.

As an example, but all stocks are affected.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104391
 cosmetic: 44032
 scriptlet: 19427
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 14-1, never
  easylist: 75886-16, 15m
  easyprivacy: 33073-65, 15m
  plowe-0: 3776-1137, 15m
  ublock-badware: 7553-138, 15m
  ublock-filters: 35816-161, 15m
  ublock-privacy: 930-12, 15m
  ublock-quick-fixes: 172-10, 15m
  ublock-unbreak: 2156-31, 15m
  urlhaus-1: 10190-0, 15m
filterset (user): [array of 14 redacted]
trustedset:
 added: [array of 12 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 173 ms (selfie)
 maxAssetCacheWait: 102 ms

```
</details>

**Comment by mapx-** [comment]
add

`@@||static-cdn.spot.im/production/launcher/$script,domain=openweb.jac.yahoosandbox.com`

@ryanbr 
due to `/metrics-reporter-bundle.js`
