### ISSUE TITLE
Apester platform is blocked on ublock origin

### ISSUE THREAD

**Issue by avizad** [uBlockOrigin/uAssets#2126]
### URL(s) where the issue occurs

`http://ew.com/tv/2018/04/26/amazon-prime-price/?utm_campaign=entertainmentweekly`

### Describe the issue

uBlock origin is blocking Apester’s platform for its users so they can't view the units even though the units are editorial. 

### Screenshot(s)

 **Here it appears (ublock origin is off):** 
![screen shot 2018-04-29 at 4 20 39 pm](https://user-images.githubusercontent.com/38750445/39407096-8aaecde0-4bc9-11e8-8999-ec8f90a7da39.png)

 **Here it doesn't appears (ublock origin is on, you can also see the apester is marked in red color):** 
![screen shot 2018-04-29 at 4 21 59 pm](https://user-images.githubusercontent.com/38750445/39407094-82101752-4bc9-11e8-983b-813b4e0156ee.png)

### Versions

- Browser/version: Google Chrome Version 66.0.3359.117
- uBlock Origin version: Version 1.16.2

### Settings

- No changes were made to uBO's default settings

### Notes

Apester's platform offers tools such as polls, quizzes, interactive videos, that can be used by publishers to interact with their audience. The company also creates exclusive content tailored for selected publishers. Apester's technology powers interactive content for media groups such as TIME, Penske, CNN, USA Today IDG, The Telegraph, CBS Interactive, and The Independent.

**Comment by gorhill** [comment]
It's blocked by a filter in Peter Lowe's _Ad and tracking server_ list.

Additionally EasyPrivacy also contains some filters related to `apester.com`.

Paging @pgl.

**Comment by avizad** [comment]
@gorhill thanks!

How can we be removed from the lists? 

Appreciate your help!

**Comment by gorhill** [comment]
The filter from Peter Lowe has been canceled using the `badfilter` option.

**Comment by avizad** [comment]
Hi ! 
I just tested it and found out that Apester is still blocked... 

![screen shot 2018-05-02 at 3 40 48 pm](https://user-images.githubusercontent.com/38750445/39523719-3e406f92-4e1f-11e8-852b-98a4c22283a6.png)

**Comment by uBlock-user** [comment]
Did you subscribe to Unbreak list ?

**Comment by avizad** [comment]
No. 

Here's my Filter list (I didn't change anything after downloading the app):

![screen shot 2018-05-02 at 3 50 57 pm](https://user-images.githubusercontent.com/38750445/39524180-cf9d04c2-4e20-11e8-9d6d-6d9f25b0e4dd.png)

**Comment by mapx-** [comment]
Did you force an update of unbreak list ?

**Comment by avizad** [comment]
Hi, 
I did, but the problem isn't with unbreak list but with **Peter Lowe’s Ad and tracking server list**

**Comment by mapx-** [comment]
The filter from Peter Lowe's was disabled by a filter in unbreak (read above)
`||apester.com^$badfilter`

So, click on unbreak list and see if the last filter is that 1 above

**Comment by avizad** [comment]
ohhh makes sense ! 

But I even deleted and download again, and still apester isn't on the unbreak list....

**Comment by gorhill** [comment]
You need to [force an update](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now) of _"uBlock filters -- Unbreak"_. I confirmed the fix works, I can see the Apester widget in the URL you provided in your opening comment. The list auto-update at regular interval, so soon everybody will have the update.

**Comment by avizad** [comment]
Thank you all !! 👍 

You've been really helpfull :-)
