### ISSUE TITLE
transferxl.com: breakage

### ISSUE THREAD

**Issue by SilkArt** [uBlockOrigin/uAssets#21270]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.transferxl.com/subscription/`

### Description

This may be hard to fix because you have to have an active paid subscription on a website with the Chargebee portal.

 To assist with investigating this issue, I can supply my login details to this site through a private communication channel so that you can take a look at how to fix it.

Anyways, the Chargebee portal is a self-serve portal that operates as a popup where you can manage your subscription, such as downloading invoices/receipts, updating/canceling plans, updating payment details, updating billing information, etc.

### Other extensions used

<details>
<summary>Extensions</summary>

Bypass Paywalls
1.8.1
Bypass News Sites' Paywalls
ID: dcpihecpambacapedldabdbpakmachpb
Inspect views
background page

QuillBot Premium Crack
3.0.1
A browser extension to crack QuilBot Premium
ID: jfbdogjbndccgopmpjhmfgohiabhenni

AdDetector
0.0.19
Detect news articles paid for by advertisers.
ID: cmjeonfdjdekpggjkoknhhkcifnaichh

ADS Wallet
0.4.10
Secure identity vault for Adshares network.
ID: algblmhagnobbnmakepomicmfljlbehg
Inspect views
background.html

APK Downloader
1.0.4
Free and safe download Android apps & games from Google Play Store.
ID: glngapejbnmnicniccdcemghaoaopdji
Inspect views
service worker

AudioContext Fingerprint Defender
0.1.8
Defending against AudioContext fingerprinting by reporting a fake value.
ID: pcbjiidheaempljdefbdplebgdgpjcbe
Inspect views
service worker (Inactive)

Auto Link Bypasser
1.6.1
Extension for redirecting your Ad-Link automatically.
ID: doiagnjlaingkmdjlbfalakpnphfmnoh
Inspect views
service worker (Inactive)

Baxter - Email Organizer & Unsubscriber
1.17.2
Unsubscribe, delete, and organize your email in one click. Simple & powerful Gmail add-on
ID: kofcedljghienfpkfmdaadpafepbhifl
Inspect views
service worker

Bookmarker by start.me
4.0.0
This Bookmarker can be used to bookmark webpages to your start.me page while you surf - start.me
ID: obgopghdefjihikoknnjfooahlleabno
Inspect views
service worker (Inactive)

Buster: Captcha Solver for Humans
2.0.1
Save time by asking Buster to solve captchas for you.
ID: mpbjkejclgfgadiemmefgebjfooflfhl
Inspect views
src/background/index.html

Canvas Fingerprint Defender
0.2.1
Defending against Canvas fingerprinting by reporting a fake value.
ID: lanfdkkpgfjfdikkncbnojekcppdebfp
Inspect views
service worker (Inactive)

Chromebook Recovery Utility
0.2.2
Create recovery media for your Chromebook.
ID: pocpnlppkickgojjlmhdmidojbmbodfm
Inspect views
service worker (Inactive)

Cookie-Editor
1.12.2
Simple yet powerful Cookie Editor that allow you to quickly create, edit and delete cookies without leaving your tab.
ID: hlkenndednhfkekhgcdicdfddnkalmdm
Inspect views
service worker

Copyfish 🐟 Free OCR Software
6.0.9
Copy, paste and translate text from any image, video or PDF.
ID: eenjdnjldapjajjofmldgmkjaienebbj
Inspect views
service worker (Inactive)

CRX Extractor/Downloader
1.5.7
 This extension is not trusted by Enhanced Safe Browsing. Learn more
ID: ajkhmmldknmfjnmeedkbkkojgobmljda
Inspect views
background page

CT Access
0.0.17
Secure Connection & Global Access
ID: jedjajddobfbhgoaidfigmlkijbeaene

CTG Plugins
1.7.1
 This extension is not trusted by Enhanced Safe Browsing. Learn more
ID: hjljaklopfcidbbglpbehlgmelokabcp
Inspect views
background page

Dark Reader
4.9.73
Dark mode for every website. Take care of your eyes, use dark theme for night and daily browsing.
ID: eimadpbcbfnmbkopoojfekhnkhdbieeh

Disable Content-Security-Policy
3.0.0
Disable Content-Security-Policy for web application testing. When the icon is colored, CSP headers are disabled.
ID: ieelmcmcagommplceebfedjlakkhpden
Inspect views
background page

Edit Website Extension
1.3
Edit Live Websites Text On The Fly
ID: flaminmoaihaimhjbohfnbkklgonhjej
Inspect views
background page (Inactive)

ExpressVPN: VPN proxy for a better internet
5.2.6.5291
Go online safely with blazing-fast speed. Spoof your location, access content anywhere, and control the ExpressVPN app from Chrome.
ID: fgddmllnllkalaagkghckoinaemmogpe
Inspect views
background page

Font Fingerprint Defender
0.1.5
 This extension is not trusted by Enhanced Safe Browsing. Learn more
ID: fhkphphbadjkepgfljndicmgdlndmoke
Inspect views
service worker

GLaDOS
0.1
GLaDOS Website Connector, Get Latest GLaDOS Website.
ID: dhjjibbeddglobeoapgppnlnmijajfbb
Inspect views
background.html

Gmail Unsubscribe - bulk email unsubscription
3.0.2
Unsubscribe from all unwanted emails in bulk with one click. Take back control of your inbox! From the makers of Baxter.
ID: jljicfihpdcimopabpijdhhjbmenjala
Inspect views
service worker

GMass: Powerful mail merge for Gmail
5.2.3
A powerful mass email and mail merge system for Gmail.
ID: ehomdgjhgmbidokdgicgmdiedadncbgf
Inspect views
background page (Inactive)

Google Docs Offline
1.69.0
Edit, create, and view your documents, spreadsheets, and presentations — all without internet access.
ID: ghbmnnjooekpmoecnnnilnnbdlolhkhi
Inspect views
background page (Inactive)

Google Translate
2.0.13
View translations easily as you browse the web. By the Google Translate team.
ID: aapbdbdomjkkjkaonfhkkikfgjllcleb
Inspect views
background page

Grammarly: Grammar Checker and AI Writing App
14.1145.0
Improve your writing with all-in-one communication assistance—including grammar check, generative AI, and more.
ID: kbfnbcaeplbcioakkpcpgfkobkghlhen
Inspect views
service worker

Guardio Protection for Chrome
23.12.3.1155
Experience a cleaner, safer web.
ID: gjfpmkejnolcfklaaddjnckanhhgegla

HubSpot Sales
2.9.0.14410
Email tracking, CRM for Gmail, and sales productivity tools in your inbox
ID: oiiaigjnkhngdbnoookogelabohpglmd
Inspect views
pages/background.html

Image Downloader
3.4.2
Browse and download images on the web
ID: cnpniohnfphhjihaiiggeabnkjhpaldj
Inspect views
background page

Invitation ← referral & coupon codes
1.0.12
Referral rewards on autopilot.
ID: kmeijfochmidimcngicjabokhkeifmmj
Inspect views
background page (Inactive)

JustBlock Security
2.1.0
Security Pack for Chrome™: block malware, speed up your browser, block Ads and secure your privacy
ID: hiajdlfgbgnnjakkbnpdhmhfhklkbiol

Kijiji Reposter
4.0.15
Easily repost your Kijiji extensions
ID: fdochcinmkmooanbmkmddjcggcecieke
Inspect views
background page

Location Guard
2.5.0
Hide your geographic location from websites.
ID: cfohepagpmnodfdmjliccbbigdkfcgia
Inspect views
background page

Ludwig.guru
2.0.16
ID: mddofjlammcffeigngeniglccdbfgnhh
Inspect views
service worker

Manganum Sidebar with Gmail, ChatGTP and more
23.11.3
Integrated with Google Calendar, Google Drive, Google Tasks, Google Keep, Google Translate, Chrome, Gmail, ChatGPT, Todoist, etc.
ID: jbfeongihppeenfnaofmdeikahaefljd

Math Wallet
3.0.7
The MetaMask Scatter TronLink PolkadotJS Alternative All-in-One Crypto Wallet
ID: afbcbjpbpfadlkmhmclhkeeodmamcflc
Inspect views
background page

MetaClean for Gmail
2.1.8
Removes metadata and hidden data in email attachments preventing the leakage of confidential information.
ID: ifhaebfhlkmamahknibbbpfddoeidimi
Inspect views
service worker (Inactive)

MetaMask
11.6.2
An Ethereum Wallet in your Browser
ID: nkbihfbeogaeaoehlefnkodbefgpgknn
Inspect views
background.html

Netflixy • نتفلكسي
1.2.8
Profitez d’une meilleure expérience NETFLIX
ID: kagddenkmcelpodemgjlanjglbnhdknp
Inspect views
service worker (Inactive)

New tab page by start.me
6.0.0
Replace your New Tab Page with a personal dashboard.
ID: cfmnkhhioonhiehehedmnjibmampjiab
Inspect views
service worker (Inactive)

NopeCHA: CAPTCHA Solver
v0.4.7
Automatically solve reCAPTCHA, hCaptcha, FunCAPTCHA, AWS WAF, and text CAPTCHA using AI.
ID: dknlfmjaanfblgfdfebhijalfmhmjjjo

Omni - Bookmark, History, & Tab Manager
1.4.7
Supercharge Chrome with commands, shortcuts, and more
ID: mapjgeachilmcbbokkgcbgpbakaaeehi
Inspect views
service worker (Inactive)

Onion Browser Button
0.2.4
 This extension is not trusted by Enhanced Safe Browsing. Learn more
ID: fockhhgebmfjljjmjhbdgibcmofjbpca

PayPal Honey: Automatic Coupons & Cash Back
16.3.4
Save money and earn rewards when you shop online.
ID: bmnlcjabgnpnenekpadlanbbkooimhnj
Inspect views
service worker,
 1 more…

Ping Blocker
1.0.0
Stop sites from tracking the links you visit through hyperlink auditing.
ID: jkpocifanmihboebfhigkjcdihgfcdnb
Inspect views
src/background/index.html

PixelBlock
2023.11.11
PixelBlock is a Gmail extension that blocks people from tracking when you open their emails.
ID: jmpmfcjnflbcoidlgapblgpgbilinlem
Inspect views
service worker (Inactive)

Privacy Pass
3.0.6
Client support for Privacy Pass anonymous authorization protocol.
ID: ajhmfdgkijocedmfjonnpjfojldioehi
Inspect views
background page

Proxy SwitchyOmega
2.5.21
Manage and switch between multiple proxies quickly & easily.
ID: padekgcemlokbadohgkifijomclgjgif

Rakuten Button Canada
7.11.0
Rakuten Button Canada provides automatic Cash Back alerts at participating stores. No hassle. No more missed Cash Back!
ID: idpbkophnbfijcnlffdmmppgnncgappc
Inspect views
background page

Rakuten: Get Cash Back For Shopping
5.35.0
The best coupons and the most Cash Back. We do all the work. You just shop and save. Earn Cash Back at 3,700 stores today!
ID: chhjbpecpncaggjpdakmflnfcopglcmi
Inspect views
background page

Reddit: What's New
2.2
 This extension is not trusted by Enhanced Safe Browsing. Learn more
ID: acmnikdadpjghhiphlkneneeflhmiidh
Inspect views
background page

Referer Control
1.35
Control the HTTP Referer on a per-site basis.
ID: hnkcfpcejkafcihlgbojoidoihckciin
Inspect views
chrome/content/background.html

Residential VPN | Tuxler
3.1.24
A revolutionary community-powered VPN network with a HUGE number of worldwide locations available.
ID: jpgljfpmoofbmlieejglhonfofmahini

Return YouTube Dislike
3.0.0.13
Returns ability to see dislikes
ID: gebbhagfogifgggkldgodflihgfeippi
Inspect views
service worker (Inactive)

reveddit linker
0.0.0.9
Switch between viewing content on reddit and reveddit.
ID: jgnigeenijnjlahckhfomimnjadmkmah
Inspect views
service worker (Inactive)

Ruffle - Flash Emulator
0.1.0 nightly 2023-12-07
Puts Flash back on the web where it belongs.
ID: donbcfbmhbcapadipfkeojnmajbakjdc
Inspect views
service worker (Inactive)

Screen Recorder
3.3.0
Record a video from the camera or capture it from the screen (desktop, specific application window or browser tab)
ID: hniebljpgcogalllopnjokppmgbhaden
Inspect views
background page

Screenity - Screen Recorder & Annotation Tool
2.8.6
The most powerful screen recorder for Chrome. Capture, annotate, edit, and more.
ID: kbbdabhdfibnancpjfhlkhafgdilcnji
Inspect views
background page,
 16 more…

Scroll Zoom
2.0.2
Zoom web pages with the left or right mouse button and the scroll wheel.
ID: ccfomhdaagemnbhbpminjoggkbglmcgb
Inspect views
src/background/index.html

Secure Shell
7 Dec 2023 15:08
Terminal emulator and SSH and SFTP client.
ID: algkcnfjnajfhgimadimbjhmpaeohhln
Inspect views
service worker (Inactive)

Secure Shell
0.62
Terminal emulator and SSH and SFTP client.
ID: iodihamcpbpeioajjeobimgagajmlibd
Inspect views
service worker (Inactive)

Simple screenshot
2.0.3
One click is enough!
ID: eggmmlnhnjfadihmbfdkcockbmingemo
Inspect views
service worker (Inactive)

Social Meter
1.2.1
Social media stats in one click!
ID: eelhfeamoijglbkgkkfddgkngokfabde

Social Revealer Plus
1.3.4
Check your Facebook digital footprint
ID: jkaedhaeddmnmeaogfnbgmmmhlbiljme

SponsorBlock for YouTube - Skip Sponsorships
5.4.28
Skip sponsorships, subscription begging and more on YouTube videos. Report sponsors on videos you watch to save others' time.
ID: mnjggcdmjocbbbhaepdhchncahnbgone
Inspect views
background page

Suspicious Site Reporter
1.23
Extension for reporting suspicious sites to Safe Browsing.
ID: jknemblkbdhdcpllfgbfekkdciegfboi
Inspect views
background page

Symantec Endpoint Protection
1.3.0.9
Browser Security by Symantec Endpoint Security Division of Broadcom.
ID: pamolibmfebkknkdmfabpjebifbffbec

Tampermonkey
4.19.0
Change the web at will with userscripts
ID: dhdgffkkebhmkfjojejmpbldmpobfkfo
Inspect views
background.html

Timebox++
1.2.4
Master your time the visual way!
ID: cbgpbhpefmeholmeodlhaalbcjgbafjd
Inspect views
background page

TON Wallet
1.1.47
Set up your own TON Wallet on The Open Network
ID: nphplpgoakhhjchkkhmiggakijnkhfnd
Inspect views
service worker

Trustpilot
1.93.0
We're all about consumer reviews. Get the real inside story from shoppers like you. Read, write and share reviews on Trustpilot.
ID: meagmjlgkihmljnchdjagbcgfclobkho
Inspect views
background page

uBlock Origin
1.53.0
Finally, an efficient blocker. Easy on CPU and memory.
ID: cjpalhdlnbpafiamejdnhcphjbkeiagm
Inspect views
background.html,
 2 more…

UI.Vision RPA
8.3.9
Universal AI-powered task and UI test automation. RPA combines Visual Web Automation, Visual Desktop Automation and Selenium IDE++.
ID: gcbalfbdmfieckjlnblleoemohcganoc
Inspect views
service worker

Urban VPN Proxy
4.2.0
Stay anonymous & secure with VPN - surf through 80 locations with Urban VPN for Chrome
ID: eppiocemhmnlbhjplcgkofciiegomcon

URL Tracking Stripper & Redirect Skipper
5.0.1
Increase the speed & privacy of your browsing. Skip/remove tracking parameters & redirects from URLs to keep them shorter & cleaner.
ID: flnagcobkfofedknnnmofijmmkbgfamf
Inspect views
background page

User-Agent Switcher and Manager
0.5.0
Spoof websites trying to gather information about your web navigation to deliver distinct content you may not want
ID: bhchdcejhohfmigjafbampogmaanbfkg
Inspect views
background page

Volume Master
1.14.4
Up to 600% volume boost
ID: jghecgabfgfdldnmbfkhmffcabddioke
Inspect views
background page

VT4Browsers
4.0.9
VirusTotal Browser Extension.
ID: efbjojhplkelaegfbieplglfidafgoka
Inspect views
background page

WebGL Fingerprint Defender
0.1.7
 This extension is not trusted by Enhanced Safe Browsing. Learn more
ID: olnbjpaejebpnokblkepbphhembdicik
Inspect views
service worker (Inactive)

WebRTC Control
0.3.2
Have control over WebRTC (disable | enable) and protect your IP address.
ID: fjkmabmdepjfammlpliljpnbhleegehm

Wildlink
5.2.4
Never miss out on earning when you share product links to friends and family.
ID: ipldncgiiglfcmcookhlkeicoinpkdni
Inspect views
service worker (Inactive)

</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 527941
 cosmetic: 242637
 scriptlet: 47988
 html: 0
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/malware-filter/botnet-filter.txt: 55-0, 13h.5m
  https://malware-filter.gitlab.io/malware-filter/tracking-filter.txt: 244295-55, 3d.3h.55m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 13h.3m
  https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 22h.31m
  adguard-cookies: 28266-30, 42m
  adguard-generic: 80596-486, 1d.34m
  adguard-mobile: 8788-46, 2d.14h.19m
  adguard-mobile-app-banners: 4810-10, 3d.14h.30m
  adguard-other-annoyances: 14032-9, 40m
  adguard-popup-overlays: 26508-89, 3d.14h.31m
  adguard-social: 22078-928, 1d.33m
  adguard-spyware: 76677-1247, 3d.14h.29m
  [14 lists not shown]: [too many]
 default:
  user-filters: 33-2, never
  easylist: 75620-2088, 5d.13h.44m
  easyprivacy: 33033-16605, 6d.3h.14m
  plowe-0: 3779-1640, 1d.17h.46m
  ublock-badware: 7553-329, 13h.18m
  ublock-filters: 35890-4264, 1d.2h.39m
  ublock-privacy: 937-386, 5d.1h.5m
  ublock-quick-fixes: 172-10, 39m
  ublock-unbreak: 2158-150, 1d.2h.38m
  urlhaus-1: 10295-0, 13h.4m
filterset (user): [array of 34 redacted]
trustedset:
 added: [array of 23 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2192 ms (selfie)
 maxAssetCacheWait: 855 ms
popupPanel:
 blocked: 12
 network:
  chargebee.com: 1
  googletagmanager.com: 4
  visualstudio.com: 7

```
</details>

**Comment by mapx-** [comment]
You didn't explain what exactly is broken and the steps to reproduce it - eventually some screenshot.
First of all: repeat your test using only the default lists and disabling all other extensions.

If still broken I'll provide an email address where you can send the account credentials.

**Comment by mapx-** [comment]
@SilkArt add a comment here with your feedback, closing for now

**Comment by SilkArt** [comment]
![With adblock, the button "open the subscription self-service portal" doesn't work](https://github.com/uBlockOrigin/uAssets/assets/62780210/f9ad3ede-0369-4503-943e-30fa0aa79545)
![Without adblock, it opens properly](https://github.com/uBlockOrigin/uAssets/assets/62780210/6fbcb9f6-b713-4fcd-80bf-885b9838a86d)

To reproduce the issue, try clicking on the button "open the subscription self-service portal".
