### ISSUE TITLE
dumpert.nl: ad placeholders

### ISSUE THREAD

**Issue by jmxd2** [uBlockOrigin/uAssets#21284]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dumpert.nl/`

### Category

ads

### Description

Website was updated with a new design and now shows ad placeholders

### Other extensions used

none that interfere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 115836
 cosmetic: 198067
 scriptlet: 30715
 html: 1328
listset (total-discarded, last-updated):
 added:
  adguard-social: 22079-868, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 49131-3876, now
  fanboy-social: 15962-24, now
  ublock-annoyances: 6073-675, 1h.25m
  NLD-0: 2747-9, now
  adguard-cookies: 28266-64, now
  adguard-popup-overlays: 26548-1638, now
  adguard-mobile-app-banners: 4825-1069, now
  adguard-other-annoyances: 14032-325, now
  adguard-widgets: 2355-1, now
  easylist-annoyances: 4234-122, now
  [5 lists not shown]: [too many]
 default:
  user-filters: 45-0, never
  ublock-filters: 36699-347, 1h.25m
  ublock-badware: 7562-11, 1h.25m
  ublock-privacy: 923-4, 1h.25m
  ublock-unbreak: 2202-0, 1h.25m
  easylist: 75886-785, 1h.25m
  easyprivacy: 33073-888, 1h.25m
  urlhaus-1: 9795-0, now
  plowe-0: 3776-1, now
  ublock-quick-fixes: 173-2, 1h.25m
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 31 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 prefetchingDisabled: false
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1591 ms (selfie)
 maxAssetCacheWait: 223 ms
 unsuspendAfter: 1302 ms
popupPanel:
 blocked: 6
 network:
  doubleclick.net: 1
  googletagmanager.com: 2
  mediahuis.be: 2
  pbstck.com: 1
 extended:
  ##+js(no-setTimeout-if, AdBlockerCheck)
```
</details>

**Comment by huyszn** [comment]
```
dumpert.nl##[id^="ad_"]:upward(2)
dumpert.nl##[id*="leaderboardwallpaper-"]:upward(3)
```

**Comment by D4niloMR** [comment]
> ```
> dumpert.nl##[id^="ad_"]:upward(2)
> dumpert.nl##[id*="leaderboardwallpaper-"]:upward(3)
> ```

@JohnyP36

**Comment by JohnyP36** [comment]
@D4niloMR @huyszn  Fixed
