### ISSUE TITLE
kaoskrew.org: popups

### ISSUE THREAD

**Issue by Mr-Blondie** [uBlockOrigin/uAssets#21282]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kaoskrew.org/home`

### Category

popups

### Description

popups and unwanted sites
![Ekran görüntüsü 2023-12-09 021229](https://github.com/uBlockOrigin/uAssets/assets/46048586/3fd38c60-d0b7-4338-886a-2e576b5bb595)

### Other extensions used

free vpn

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 293738
 cosmetic: 267347
 scriptlet: 67208
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=raw: 23168-15, now
  RUS-0: 39978-111, 1h.6m
  adguard-cookies: 28266-43, now
  adguard-generic: 80657-1409, now
  adguard-mobile-app-banners: 4825-11, now
  adguard-other-annoyances: 14032-43, now
  adguard-popup-overlays: 26548-482, now
  adguard-social: 22079-932, now
  adguard-spyware: 76740-1270, now
  adguard-spyware-url: 1351-5, now
  adguard-widgets: 2355-17, now
  curben-phishing: 78159-20, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  TUR-0: 13865-35, now
  easylist: 75886-1861, 1h.6m
  easyprivacy: 33073-16560, 1h.6m
  plowe-0: 3776-1240, now
  ublock-badware: 7588-327, now
  ublock-filters: 35763-6129, now
  ublock-privacy: 929-382, 1h.6m
  ublock-quick-fixes: 173-10, 1h.6m
  ublock-unbreak: 2156-152, now
  urlhaus-1: 10190-0, now
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1104 ms (selfie)
 maxAssetCacheWait: 470 ms
popupPanel:
 blocked: 3
 network:
  adsco.re: 1
  d2klx87bgzngce.cloudfront.net: 1
  intelligenceadx.com: 1
 extended:
  ##.social_links_footer
  ##.scrollToTop
  ##+js(abort-on-property-write, _pop)
  ##+js(abort-current-script, document.querySelectorAll, popMagic)
```
</details>

**Comment by huyszn** [comment]
`kaoskrew.org##+js(acs, atob, _pop)`

**Comment by D4niloMR** [comment]
`https://www.oehfvrpeleg.com/static/rangular-formly-templates-bootstrap.min.js`
@Yuki2718
