### ISSUE TITLE
chia-anime.tv [ADS]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2128]
URL(s) where the issue occurs

`http://ww2.chia-anime.tv/caligula-episode-4-english-subbed/`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.2

Settings

Default

**Comment by zaphodbeebblebrox** [comment]
```
||piguiqproxy.com^$xmlhttprequest,domain=chia-anime.tv,redirect=nooptext
||chia-anime.tv/thebox.php$subdocument,first-party
chia-anime.tv##script:inject(nano-setTimeout-booster.js)
```

**Comment by uBlock-user** [comment]
Despite race condition, `chia-anime.tv##script:inject(abort-on-property-read.js, document.styleSheets)` works well.

**Comment by gorhill** [comment]
> ||piguiqproxy.com^$xmlhttprequest,domain=chia-anime.tv,redirect=nooptext
> ...

This does not work on Firefox, the page ends up very broken.

**Comment by gorhill** [comment]
A mix of both suggestions work on both and still allow to block connecting to ``:

    ||piguiqproxy.com^$xmlhttprequest,domain=chia-anime.tv
    ||chia-anime.tv/thebox.php$subdocument,first-party
    chia-anime.tv##script:inject(abort-on-property-read.js, document.styleSheets)
    chia-anime.tv##script:inject(nano-setTimeout-booster.js)
