### ISSUE TITLE
fortune.com: breakage

### ISSUE THREAD

**Issue by Omega-6** [uBlockOrigin/uAssets#21280]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://fortune.com/2022/02/15/banks-investors-coal-net-zero-pledges/`

### Description

cookies => broken video

### Other extensions used

none

### Configuration

<details>
<summary>Details</summary>

```yaml

uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 108698
 cosmetic: 116965
 scriptlet: 26796
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4234-32, now
  easylist-chat: 168-0, now
  easylist-newsletters: 6687-15, now
  easylist-notifications: 2888-86, now
  fanboy-cookiemonster: 49131-222, now
  fanboy-social: 15962-13, now
  ublock-annoyances: 6121-78, now
  ublock-cookies-easylist: 637-637, now
 default:
  user-filters: 0-0, never
  easylist: 75895-16, now
  easyprivacy: 33073-151, now
  plowe-0: 3776-1137, now
  ublock-badware: 7588-138, now
  ublock-filters: 35763-181, now
  ublock-privacy: 929-14, now
  ublock-quick-fixes: 173-10, now
  ublock-unbreak: 2156-35, now
  urlhaus-1: 10190-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 464 ms
 maxAssetCacheWait: 271 ms
popupPanel:
 blocked: 10
 network:
  cxense.com: 1
  lightboxcdn.com: 1
  ml314.com: 1
  npttech.com: 1
  p-n.io: 1
  queryly.com: 1
  tinypass.com: 1
  trustarc.com: 3
 extended:
  ###Leaderboard0
  ###teconsent
  #@##consent_blackbar
  #@##truste-consent-track

```
</details>

**Comment by D4niloMR** [comment]
What it's broken? with the same lists as you I don't see any breakage

**Comment by huyszn** [comment]
After clearing cookies on `fortune.com`, the video doesn't load. But the video loads after refreshing the page. It also seems to happen only on chrome and not firefox.
https://github.com/uBlockOrigin/uAssets/assets/46979193/22668cc4-cf4b-4c56-9576-4bea411896c3
