### ISSUE TITLE
viettoons.tv: breakage

### ISSUE THREAD

**Issue by KatsumiKougen** [uBlockOrigin/uAssets#21288]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://viettoons.tv/movie/watch/16/1257`

### Category

breakage

### Description

Video player doesn't appear

### Other extensions used

- Return YouTube Dislike
- Enhancer for YouTube
- Video DownloadHelper

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/77793743/d913302a-7ff2-4f99-860d-c3e97e946f10)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 104026
 cosmetic: 44000
 scriptlet: 19234
 html: 1126
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36674-63, now
  ublock-badware: 7592-11, now
  ublock-privacy: 923-4, now
  ublock-unbreak: 2202-0, now
  ublock-quick-fixes: 174-2, now
  easylist: 75899-700, now
  easyprivacy: 33073-793, now
  urlhaus-1: 9795-0, now
  plowe-0: 3776-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 129 ms (selfie)
 maxAssetCacheWait: 68 ms
popupPanel:
 blocked: 5
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  redirect-ads.com: 1
  z8g0wlq5p0f6jg3k7eh2kyd58hjeskx0w9g5eu7q3m5hyq8l0xwofj3ap2nv.me: 2
```
</details>

**Comment by mapx-** [comment]
Disable all other addons / extensions, test again

**Comment by KatsumiKougen** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/77793743/eaca2ff1-46ff-48c8-a4a6-e72b65762b30)

I tried, it didn't work.

Disabling uBlock makes the player appear. It is possible that there is a hidden anti-adblocker integrated in the player itself.

**Comment by Omega-6** [comment]
@stephenhawk8054

**Comment by mapx-** [comment]
@KatsumiKougen 

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by KatsumiKougen** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/77793743/2fa2b89b-5c90-4c30-b051-798a94898897)
It seems to work.

**Comment by mapx-** [comment]
remove adblocker ultimate
