### ISSUE TITLE
sh.chinanews.com.cn: ads

### ISSUE THREAD

**Issue by 0x391F** [uBlockOrigin/uAssets#21287]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.sh.chinanews.com.cn/yljk/2023-12-08/119501.shtml`

### Category

ads

### Description

Here's still an AD on the top. 

### Other extensions used

Privacy Badger, NoScript, Decentraleyes, ClearURLs. But this issue still happens when others extensions have been disabled. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 120
filterset (summary):
 network: 275994
 cosmetic: 83830
 scriptlet: 36456
 html: 1127
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80669-7428, now
  adguard-spyware-url: 1351-92, now
  adguard-spyware: 76740-16950, now
  block-lan: 55-0, 1m
  curben-phishing: 78322-27, 2m
 default:
  user-filters: 0-0, never
  ublock-filters: 36990-327, now
  ublock-badware: 7586-11, now
  ublock-privacy: 923-5, now
  ublock-unbreak: 2207-2, now
  ublock-quick-fixes: 174-2, 21m
  adguard-mobile: 8790-128, now
  easylist: 75899-16753, now
  easyprivacy: 33073-815, 1m
  urlhaus-1: 9795-0, 2m
  plowe-0: 3776-1, 2m
  CHN-0: 25181-1253, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1103 ms (selfie)
 maxAssetCacheWait: 591 ms
popupPanel:
 blocked: 2
 network:
  baidu.com: 2
```
</details>

**Comment by mapx-** [comment]
add

```
chinanews.com.cn##.adv
chinanews.com.cn##.wap_adv
```

@cjx82630
