### ISSUE TITLE
allocine.fr: breakage

### ISSUE THREAD

**Issue by momala454** [uBlockOrigin/uAssets#21297]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.allocine.fr/video/video-19604544/`

### Category

breakage

### Description

Videos are not playing

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/83005/7455fda0-7c95-4d1b-b578-cd3f4d7d6ac7)

![image](https://github.com/uBlockOrigin/uAssets/assets/83005/7d4c8209-6262-499f-ab7d-f420d501f8af)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 124557
 cosmetic: 98806
 scriptlet: 26883
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49138-215, now
  ublock-annoyances: 6124-58, now
 default:
  user-filters: 0-0, never
  FRA-0: 28757-39, now
  easylist: 75324-73, now
  easyprivacy: 33072-333, now
  plowe-0: 3776-1148, now
  ublock-badware: 7589-151, now
  ublock-filters: 35848-262, now
  ublock-privacy: 929-13, now
  ublock-quick-fixes: 170-9, now
  ublock-unbreak: 2156-37, now
  urlhaus-1: 9915-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 510 ms
 maxAssetCacheWait: 281 ms
popupPanel:
 blocked: 7
 network:
  allocine.fr: 1
  disqus.com: 6
 extended:
  ###dfp-interstitial
  ##.ad-interstitial
  ##.ad-item
  ##.sticky-ad-holder
  ###dfp-btf
  ##.ad-footer
  ##.main-banner
  ###didomi-host
  ##body,html:style(overflow: visible !important; padding-right: 0…
  ##+js(set-constant, AC.config.ads, {})
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by mapx-** [comment]
add

`allocine.fr#@##didomi-host`

@ryanbr

**Comment by Zenphia** [comment]
> * [x] I did not answer truthfully to ALL the above checkpoints.

**Comment by momala454** [comment]
it is still not properly working on firefox
It worked once in private browsing, then after closing and reopening private browsing it stopped working

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 122575
 cosmetic: 98705
 scriptlet: 26535
 html: 1327
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  plowe-0: null
 added:
  fanboy-cookiemonster: 64666-15757, never
  ublock-annoyances: 6082-11, 7m
  ublock-quick-fixes: 172-2, 7m
  ublock-cookies-easylist: 640-640, never
 default:
  ublock-filters: 36732-147, 7m
  ublock-badware: 7603-11, 7m
  ublock-privacy: 923-4, 7m
  ublock-unbreak: 2202-0, 7m
  easylist: 75288-401, 7m
  easyprivacy: 33075-293, 7m
  FRA-0: 28757-59, 7m
  urlhaus-1: 10475-0, 7m
filterset (user): [array of 322 redacted]
trustedset:
 added: [array of 165 redacted]
 removed:
  about-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 15 redacted]
hostRuleset:
 added: [array of 14 redacted]
urlRuleset:
 added: [array of 48 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 416 ms (selfie)
 maxAssetCacheWait: 127 ms
popupPanel:
 blocked: 42
 network:
  allocine.fr: 1
  2mdn.net: 1
  d1g61tw28new6q.cloudfront.net: 6
  dailymotion.com: 6
  disqus.com: 7
  dm-event.net: 15
  estat.com: 1
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  outbrain.com: 1
  privacy-center.org: 1
 extended:
  ###dfp-interstitial
  ##.ad-interstitial
  ##.ad-item
  ##.sticky-ad-holder
  ###dfp-btf
  ##.ad-footer
  ##.main-banner
  ##body,html:style(overflow: visible !important; padding-right: 0…
  #@##didomi-host
  ##+js(set-constant, AC.config.ads, {})
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
  ##+js(trusted-set-cookie, dm-euconsent-v2, CPt6yMAPt6yMABpAGAEND…
  ##+js(set-cookie, cookie_policy_closed, 1, , reload, 1)
  ##+js(xml-prune, VAST, , adnxs)
```
</details>

**Comment by mapx-** [comment]
update unbreak filters list in 5-10 min and test again in firefox

**Comment by momala454** [comment]
it works, thank you!
