### ISSUE TITLE
timesofindia.indiatimes.com  - Anti adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#213]
Anti adb warning displayed on the website http://timesofindia.indiatimes.com/, this is with default uBO filters.

**Error URL:** http://timesofindia.indiatimes.com/world/rest-of-world/Viva-Fidel-Castro-takes-final-voyage-across-Cuba/articleshow/55712725.cms

_Using Chrome 54 & uBO v1.9.16 with latest Ublock filters._

**This can be fixed by:** `@@||timesofindia.indiatimes.com/ad-banner-zedo/photo/27589586.cms$image,domain=timesofindia.indiatimes.com`

**Comment by gorhill** [comment]
I can't reproduce anti-blocker warning with the above URL. I do see a blocked image URL in the logger with the substring `ad-banner`.

**Comment by gotitbro** [comment]
Must be an issue with the uBO cache or memory as soon as I reset **uBO** to default settings (and updating the filters) I didn't get the warning.
