### ISSUE TITLE
anonymousemail.me [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2130]
URL(s) where the issue occurs

`https://anonymousemail.me`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.2

Settings

Default

**Comment by jspenguin2017** [comment]
This broke again... Not sure if we should keep spending time on this...

**Comment by geoffdutton** [comment]
Try this: `anonymousemail.me##script:inject(abort-on-property-write.js, a)`

**Comment by mapx-** [comment]
or
`||ajax.cloudflare.com/cdn-cgi/scripts/*/cloudflare-static/rocket.min.js$script,domain=anonymousemail.me,important`

?

**Comment by okiehsch** [comment]
That breaks the captcha.

**Comment by mapx-** [comment]
```
@@*$script,domain=anonymousemail.me
||pagead2.googlesyndication.com^$script,domain=anonymousemail.me,important
||google-analytics.com^$script,domain=anonymousemail.me,important
```

**Comment by okiehsch** [comment]
Why not just `@@||benkhouya.com/js/ga.js$script,domain=anonymousemail.me`?
Or seeing that they changed the bait script from `benkhouya.com/ads.js` add
`@@||benkhouya.com^$script,domain=anonymousemail.me`

**Comment by mapx-** [comment]
if they change the bait domain, my filters still work

**Comment by KiLL4FuNK** [comment]
![](https://i.imgur.com/IgK01tt.png)
