### ISSUE TITLE
office.mailbox.org: breakage

### ISSUE THREAD

**Issue by kylebarbour** [uBlockOrigin/uAssets#21302]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://office.mailbox.org/appsuite/`

### Category

breakage

### Description

uBlock Origin appears to hide the attachments uploaded when composing email on mailbox.org. This can be confirmed and prevented by disabling cosmetic filtering.

### Other extensions used

I also use Privacy Badger, Shut Up, Zotero, and LeechBlock NG. However, I disabled these and confirmed that uBlock Origin is the cause to the best of my ability.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBlock Origin cosmetic filtering active:
![uBlock Origin cosmetic filtering active](https://github.com/uBlockOrigin/uAssets/assets/4647176/45ad8039-b64d-4097-8a6e-c23b3c7673c6)

uBlock Origin cosmetic filtering disabled:
![uBlock Origin cosmetic filtering disabled](https://github.com/uBlockOrigin/uAssets/assets/4647176/c7193042-025d-4079-bc4a-7c86da5a2650)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 103679
 cosmetic: 86220
 scriptlet: 19297
 html: 1126
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt: 42453-58, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36726-62, now
  ublock-badware: 7593-11, now
  ublock-privacy: 923-4, now
  ublock-unbreak: 2202-0, now
  easylist: 75324-755, now
  easyprivacy: 33072-793, now
  urlhaus-1: 9915-0, now
  plowe-0: 3776-1, now
  ublock-quick-fixes: 172-2, now
filterset (user): [empty]
trustedset:
 added: [array of 10 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 330 ms (selfie)
 maxAssetCacheWait: 87 ms
popupPanel:
 blocked: 0
 extended:
  ##.fa-pencil-square-o
```
</details>

**Comment by Omega-6** [comment]
Would you be willing to send @mapx- (a maintainer) your account?

**Comment by kylebarbour** [comment]
> Would you be willing to send @mapx- (a maintainer) your account?

I'm happy to help troubleshoot but please forgive me, I'm not sure what you mean - can you explain?

**Comment by Omega-6** [comment]
it looks like a paid account is needed to investigate this issue -- would you be willing to send a maintainer your account?

**Comment by mapx-** [comment]
@kylebarbour 

disable ultralist and test again

**Comment by kylebarbour** [comment]
> disable ultralist and test again

I apologize, I forgot I had installed this. You are correct, disabling Ultralist solved the problem. I will take my report to them. Thanks for the help!
