### ISSUE TITLE
arras.io: detection

### ISSUE THREAD

**Issue by Zenphia** [uBlockOrigin/uAssets#21301]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://arras.io/`
`https://arrax.io/`
`https://arras.netlify.app/`

### Category

detection

### Description

Ingame notification when spawning in (which reappears periodically while playing) and on the death screen (to test the last one, press `O` after joining a server)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="448" alt="Screenshot 2023-12-09 at 15 39 21" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/207cce5c-3493-46e0-a6a7-90d6a93df60e">
<img width="752" alt="Screenshot 2023-12-09 at 15 39 41" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/72d56942-a641-4d38-97d9-7fe26712089d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 103573
 cosmetic: 44022
 scriptlet: 19479
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 25-0, never
  easylist: 75324-16, 4m
  easyprivacy: 33072-65, 4m
  plowe-0: 3776-1137, 4m
  ublock-badware: 7589-138, 4m
  ublock-filters: 35847-174, 4m
  ublock-privacy: 928-12, 1h.52m
  ublock-quick-fixes: 170-9, 4m
  ublock-unbreak: 2156-31, 4m
  urlhaus-1: 9915-0, 4m
filterset (user): [array of 25 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 122 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel:
 blocked: 5
 network:
  arras.io: 2
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  intergient.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by Omega-6** [comment]
similar to the anti-adb diep.io had?

**Comment by Omega-6** [comment]
```
arras.io##+js(rmnt, script, intergient.com)
```

**Comment by mapx-** [comment]
@huyszn are you able to reproduce here too ?

**Comment by huyszn** [comment]
I can reproduce both of the messages. `arras.io,arras.netlify.app,arrax.io##+js(rmnt, script, onerror)` seems to work to remove the messages.

https://github.com/uBlockOrigin/uAssets/blob/21bf84b95b3a17e041c0bb1eb27d14c4c598a539/filters/filters-2023.txt#L4937
should also be changed to `/img/server-hunter*.jpg$image,1p,domain=arras.io|arras.netlify.app|arrax.io` since I still see the server hunter ads on the other proxy sites after waiting a few seconds.

**Comment by mapx-** [comment]
thx

**Comment by JobcenterTycoon** [comment]
I get the anti adblock even with disabled adblocker on Firefox.

**Comment by Zenphia** [comment]
> I can reproduce both of the messages. `arras.io,arras.netlify.app,arrax.io##+js(rmnt, script, onerror)` seems to work to remove the messages.
> 
> https://github.com/uBlockOrigin/uAssets/blob/21bf84b95b3a17e041c0bb1eb27d14c4c598a539/filters/filters-2023.txt#L4937
> 
> 
> should also be changed to `/img/server-hunter*.jpg$image,1p,domain=arras.io|arras.netlify.app|arrax.io` since I still see the server hunter ads on the other proxy sites after waiting a few seconds.

Patched.

**Comment by huyszn** [comment]
I get the detected message with uBO disabled on firefox but I don't get the detected message with uBO disabled on chrome.

**Comment by JobcenterTycoon** [comment]
`@@||cdn.intergient.com/*/ramp.js$script,domain=arras.io|arras.netlify.app|arrax.io`

The code i see is 

```
(new Promise(a => {
      let b = document.createElement("script");
      b.async = !0;
      b.src = "https://cdn.intergient.com/1024850/73985/ramp.js";
      b.onload = () => a(5 > Object.keys(window.ramp || {}).length);
      b.onerror = () => a(!0);
      document.body.appendChild(b);
      setTimeout(() => a(!0), 5E3)
   }))
```

**Comment by JobcenterTycoon** [comment]
Ok the final filter

```
!#if cap_html_filtering
/container.js$script,1p,replace=/5\>Object\.keys\(/0>Object.keys(/g,domain=arras.io|arras.netlify.app|arrax.io
!#else
@@||cdn.intergient.com/*/ramp.js$script,domain=arras.io|arras.netlify.app|arrax.io
!#endif
```
@mapx- why are the existing filter in the base list and not in the annoyance list?

**Comment by Zenphia** [comment]
> replace=/5\>Object\.keys\(/0>Object.keys(/g

This gives me an Unsupported filter option error.

**Comment by JobcenterTycoon** [comment]
Because its a trusted filter and trusted filter are untrusted in the `my filter` panel by default. Also `$replace` only works in Firefox.

**Comment by mapx-** [comment]
> why are the existing filter in the base list and not in the annoyance list?

my error

**Comment by huyszn** [comment]
So there was a new update today where you can upgrade a tank but you have to watch an ad first. Not sure if uBO can fix this.
<img width="756" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/dbe22f65-4101-4fd6-b3bc-64664621f435">

**Comment by Zenphia** [comment]
> Ok the final filter
> 
> ```
> !#if cap_html_filtering
> /container.js$script,1p,replace=/5\>Object\.keys\(/0>Object.keys(/g,domain=arras.io|arras.netlify.app|arrax.io
> !#else
> @@||cdn.intergient.com/*/ramp.js$script,domain=arras.io|arras.netlify.app|arrax.io
> !#endif
> ```
> 
> @mapx- why are the existing filter in the base list and not in the annoyance list?

Patched.

**Comment by JobcenterTycoon** [comment]
Looks like a site issue because i get a anti adblock even without adblocker on chrome. For firefox the current filter working fine.

**Comment by Zenphia** [comment]
If I use DDG's extension it removes the ads but doesn't display an anti adblock.

**Comment by JobcenterTycoon** [comment]
> DDG's extension

?

**Comment by Zenphia** [comment]
> > DDG's extension
> 
> ?

DuckDuckGo Privacy Essentials.

**Comment by JobcenterTycoon** [comment]
I tested again and it works fine now on chrome and firefox.

**Comment by Zephiii** [comment]
Update, now detecting me on Firefox. Chromium still seems to be undetected.
