### ISSUE TITLE
earnhub.net: detection

### ISSUE THREAD

**Issue by danjimaru** [uBlockOrigin/uAssets#21306]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://earnhub.net/`

### Category

detection

### Description

detection forwarding

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 113532
 cosmetic: 52675
 scriptlet: 40536
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist.to/easylist/easylist.txt: 75324-24369, now
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 0-0, now
  DEU-0: 7204-7, now
  fanboy-thirdparty_social: 68-0, now
  ublock-annoyances: 6124-48, now
 default:
  user-filters: 52873-24, never
  easylist: 75324-75324, now
  easyprivacy: 33072-75, now
  plowe-0: 3776-1141, now
  ublock-badware: 7589-138, now
  ublock-filters: 35846-2293, now
  ublock-privacy: 929-13, now
  ublock-quick-fixes: 170-9, now
  ublock-unbreak: 2156-35, now
  urlhaus-1: 9915-0, now
filterset (user): [array of 30105 redacted]
trustedset:
 added: [array of 52 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 collapseBlocked: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 735 ms (selfie)
 maxAssetCacheWait: 177 ms
popupPanel:
 blocked: 33
 network:
  bmcdn6.com: 25
  googletagmanager.com: 1
  hbagency.it: 6
  surfe.pro: 1
 extended:
  ##+js(addEventListener-defuser, load, htmls)
```
</details>

**Comment by Omega-6** [comment]
```
@@||static.surfe.pro/js/net.js$script,domain=freeoseocheck.com|makeupguide.net|cryptowidgets.net
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=freeoseocheck.com|makeupguide.net|cryptowidgets.net
@@||pagead2.googlesyndication.com^$xhr,script,domain=freeoseocheck.com|makeupguide.net|cryptowidgets.net
@@*$ghide,domain=freeoseocheck.com|cryptowidgets.net
@@||hbagency.it^$script,domain=freeoseocheck.com
||blog.freeoseocheck.com/post/$document,csp=style-src *,badfilter
@@||securepubads.g.doubleclick.net^$script,domain=freeoseocheck.com|cryptowidgets.net
@@*$script,1p,domain=makeupguide.net|freeoseocheck.com|cryptowidgets.net
@@||googletagmanager.com^$script,domain=freeoseocheck.com|earnhub.net|cryptowidgets.net
@@||tpc.googlesyndication.com^$script,domain=freeoseocheck.com|earnhub.net|makeupguide.net|cryptowidgets.net
@@||cdn.bmcdn6.com^$script,xhr,image,domain=freeoseocheck.com|makeupguide.net|cryptowidgets.net
@@||surfe.pro^$script,xhr,image,domain=earnhub.net|cryptowidgets.net
cryptowidgets.net,freeoseocheck.com,makeupguide.net#@#+js(acs, document.createElement, adsBlocked)
*$frame,csp=style-src *,from=blog.coinscap.info|blog.cryptowidgets.net|blog.insurancegold.in|blog.wiki-topia.com,badfilter
coinscap.info,cryptowidgets.net,insurancegold.in,wiki-topia.com##+js(noeval-if, /chp_?ad/)
```

(bad for privacy)

**Comment by mapx-** [comment]
continue here
https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by Omega-6** [comment]
@ItsProfessional for the same reasons filter lists have them ... but they have a license which "absolves" itself from liability
