### ISSUE TITLE
woomy-site.glitch.me: detection

### ISSUE THREAD

**Issue by Zenphia** [uBlockOrigin/uAssets#21300]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://woomy-site.glitch.me/`

### Category

detection

### Description

Intermittent adblocker detection notice, doesn't appear all the time in testing

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 103573
 cosmetic: 44022
 scriptlet: 19479
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 25-0, never
  easylist: 75324-16, now
  easyprivacy: 33072-65, now
  plowe-0: 3776-1137, now
  ublock-badware: 7589-138, now
  ublock-filters: 35847-174, now
  ublock-privacy: 928-12, 1h.48m
  ublock-quick-fixes: 170-9, now
  ublock-unbreak: 2156-31, now
  urlhaus-1: 9915-0, now
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 122 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel:
 blocked: 9
 network:
  google.com: 6
  googlesyndication.com: 2
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  ##.\31 03jkbiv5cmu
```
</details>

**Comment by Zenphia** [comment]
tested without ISDCAC, still appears

**Comment by Omega-6** [comment]
does it look similar to https://github.com/uBlockOrigin/uAssets/issues/21301#issuecomment-1848445960 ? just a message ?

**Comment by Zenphia** [comment]
> does it look similar to [#21301 (comment)](https://github.com/uBlockOrigin/uAssets/issues/21301#issuecomment-1848445960) ? just a message ?

No. It's a bright yellow box on the bottom that persists in the game and can't be clicked off without manually blocking it.

**Comment by huyszn** [comment]
After I upgraded, I got an adblocker detection message at the top of my screen.
<img width="1249" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/691f03d4-ca79-4165-af40-14573920c702">

**Comment by mapx-** [comment]
@huyszn is that only an annoyance ?

**Comment by huyszn** [comment]
@mapx- It seems to be an annoyance since I get the message when I upgrade for the first time only. I don't get the message when I upgrade for the second time, the third time, etc.

**Comment by mapx-** [comment]
Can you find a simple cosmetic filter (to add it to the annoyances list) ?

**Comment by huyszn** [comment]
Couldn't find a simple cosmetic filter to hide the message. Only found `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=woomy-site.glitch.me` was able to hide the message.


```javascript
// Load ad
const googleAdUrl = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'
try {
    fetch(new Request(googleAdUrl)).catch(_ => window.adBlockEnabled = true)
} catch (e) {
    window.adBlockEnabled = true
}
```

**Comment by mapx-** [comment]
what about:

`woomy-site.glitch.me##+js(rpnt, script, window.adBlockEnabled = true, window.adBlockEnabled = false)`

**Comment by huyszn** [comment]
> what about:
> 
> `woomy-site.glitch.me##+js(rpnt, script, window.adBlockEnabled = true, window.adBlockEnabled = false)`

I still get the message using this filter.

**Comment by mapx-** [comment]
thx

**Comment by Zenphia** [comment]
`woomy-site.glitch.me##.\32:has-text(blocking)`

This gets rid of the bottom popup on the main menu.

**Comment by huyszn** [comment]
@Zenphia I don't get any popup on the main menu.
