### ISSUE TITLE
app.simpleclub.com: ads

### ISSUE THREAD

**Issue by 10Meisterbaelle** [uBlockOrigin/uAssets#21319]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.simpleclub.com/profile`

### Category

ads

### Description

15 second long video ads (self promotion). The website requires login.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-10 at 13-26-45 simpleclub App](https://github.com/uBlockOrigin/uAssets/assets/45918080/b6d7d3c2-a5ad-4885-ad54-c8cba1fa9f1d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 110492
 cosmetic: 120254
 scriptlet: 23071
 html: 1126
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49138-224, now
  fanboy-social: 15962-7, now
  easylist-annoyances: 4233-97, now
  easylist-chat: 168-0, now
  easylist-newsletters: 6688-13, now
  easylist-notifications: 2888-4, now
  ublock-cookies-easylist: 640-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 36736-101, 1h.33m
  ublock-badware: 7593-11, 1h.33m
  ublock-privacy: 923-4, 1h.33m
  ublock-unbreak: 2202-0, 1h.33m
  ublock-quick-fixes: 172-2, 1h.33m
  easylist: 75325-744, 1h.33m
  easyprivacy: 33074-892, 1h.33m
  urlhaus-1: 10475-0, now
  plowe-0: 3777-1, now
  DEU-0: 7204-4, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 709 ms (selfie)
 maxAssetCacheWait: 102 ms
popupPanel:
 blocked: 8
 network:
  simpleclub.com: 2
  algolia.io: 1
  appboycdn.com: 1
  firebaselogging-pa.googleapis.com: 3
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
add

```
||videos-cloudfront.jwpsrv.com^$media,domain=app.simpleclub.com
||cdn.jwplayer.com^$media,domain=app.simpleclub.com
```

then click "x"
