### ISSUE TITLE
yhetil.org: breakage

### ISSUE THREAD

**Issue by maikol-solis** [uBlockOrigin/uAssets#21322]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://yhetil.org/emacs-devel/20230310110747.4hytasakomvdyf7i@Ergus/`

### Description

Every time I open any page of yhetil.org, all the content is deleted. However, If I open the logger, the content stays in the webpage (screenshots below)

### Other extensions used

<details>

```
Diccionario de Español/Chile	dictionary	2.7	true	es_cl@dictionaries.addons.mozilla.org
Diccionario español México	dictionary	1.1.3.2webext	true	es-MX@dictionaries.addons.mozilla.org
Add-ons Search Detection	extension	2.0.0	true	addons-search-detection@mozilla.com
Amazon.com	extension	1.7	true	amazondotcom@search.mozilla.org
Auto Tab Discard	extension	0.6.7	true	{c2c003ee-bd69-42a2-b0e9-6f34222cb046}
Bing	extension	1.6	true	bing@search.mozilla.org
Bitwarden - Free Password Manager	extension	2023.10.2	true	{446900e4-71c2-419f-a6a7-df9c091e268b}
BNB Chain Wallet	extension	2.16.1	true	{0a395005-c941-4030-83c9-018ee43e3414}
Checker Plus for Google Calendar™	extension	33.1.1	true	checkerplusforgooglecalendar@jasonsavard.com
Checker Plus for Google Drive	extension	9.2	true	checkerplusforgoogledrive@jasonsavard.com
DocsAfterDark	extension	0.6.2	true	{e8ffc3db-2875-4c7f-af38-d03e7f7f8ab9}
DuckDuckGo	extension	1.4	true	ddg@search.mozilla.org
Easy Youtube Video Downloader Express	extension	18.5	true	{b9acf540-acba-11e1-8ccb-001fd0e08bd4}
editGPT	extension	1.0.17	true	{8f6943bd-b9fa-4c13-855c-d1423f8bc0f3}
Facebook Container	extension	2.3.11	true	@contain-facebook
GhostText	extension	23.5.16	true	ghosttext@bfred.it
Gmail reverse conversation	extension	0.0.7	true	{10df04ee-bbe3-4748-91e1-681b747a0420}
Google	extension	1.4	true	google@search.mozilla.org
Grammar Checker & Paraphraser – LanguageTool	extension	8.3.0	true	languagetool-webextension@languagetool.org
LeechBlock NG	extension	1.6	true	leechblockng@proginosko.com
Livemarks	extension	3.6	true	{c5867acc-54c9-4074-9574-04d8818d53e8}
Max Tabs (Web Extension)	extension	0.1.0	true	max-tabs@kanru
MetaMask	extension	11.5.1	true	webextension@metamask.io
NXP PKCS11 loader	extension	2.0.0	true	{C4113077-5495-4C77-A629-FFF0648EA6E5}
Org Capture	extension	0.2.1	true	{ddefd400-12ea-4264-8166-481f23abaa87}
Plasma Integration	extension	1.8.1	true	plasma-browser-integration@kde.org
Print Edit WE	extension	29.6	true	printedit-we@DW-dev
ProWritingAid Grammar Checker & Writing Coach	extension	2.4.30521	true	tech@prowritingaid.com
Read Aloud: A Text to Speech Voice Reader	extension	1.66.0	true	{ddc62400-f22d-4dd3-8b4a-05837de53c2e}
RescueTime for Firefox	extension	3.2.10	true	rescuetime_firefox@rescuetime.com
Tabliss Offline Quotes	extension	2.6.2	true	extension@tablissofflinequotes.io
TWP - Translate Web Pages	extension	9.9.0.30	true	{036a55b4-5e72-4d05-a06c-cba2dfcc134a}
uBlock Origin	extension	1.54.0	true	uBlock0@raymondhill.net
Wikipedia (en)	extension	1.3	true	wikipedia@search.mozilla.org
Zotero Connector	extension	5.0.114	true	zotero@chnm.gmu.edu
System theme — auto	theme	1.3	true	default-theme@mozilla.org
```
</details>

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/4078489/47f26a32-3261-475e-b943-a5ba5cc044d2)

![image](https://github.com/uBlockOrigin/uAssets/assets/4078489/d2b247fa-565f-48f7-9a27-6ee05db17392)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 104648
 cosmetic: 30224
 scriptlet: 19272
 html: 1126
listset (total-discarded, last-updated):
 added:
  spa-0: 3773-260, 19h.14m
 default:
  user-filters: 0-0, never
  ublock-filters: 36732-278, 48m
  ublock-badware: 7603-11, 48m
  ublock-privacy: 923-5, 48m
  ublock-unbreak: 2202-1, 48m
  ublock-quick-fixes: 172-2, 48m
  easylist: 75324-16726, 21h.37m
  easyprivacy: 33075-795, 48m
  urlhaus-1: 9915-0, 19h.14m
  plowe-0: 3779-1, 5d.14h.57m
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
 removed:
  moz-extension-scheme
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 8641 ms (selfie)
 maxAssetCacheWait: 6008 ms
```
</details>

**Comment by mapx-** [comment]
Did you test keeping only uBO enabled (disabling all other addons in FF) ?

**Comment by maikol-solis** [comment]
The problem was with 

```
ProWritingAid Grammar Checker & Writing Coach	extension	2.4.30521	true	tech@prowritingaid.com
```

I disabled the add-on and the website works as expected. This is so weird because if I open the logger, the content is shown normally.
