### ISSUE TITLE
ya.ru: ads

### ISSUE THREAD

**Issue by B0mak** [uBlockOrigin/uAssets#21323]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ya.ru/images/search?text=red%20alert%203%20soviet%20background&parent-reqid=1702216609343415-1946370146111090543-balancer-l7leveler-kubr-yp-sas-53-BAL-5349&from=tabbar`

### Category

ads

### Description

Still have ads for some reason.

### Other extensions used

Tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/uBlockOrigin/uAssets/assets/45781131/c1bc734b-3a64-489a-8f24-d38fcd71b4db)
![2](https://github.com/uBlockOrigin/uAssets/assets/45781131/8cb77110-664d-4ee0-b910-b015d816e7d7)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 118
filterset (summary):
 network: 124619
 cosmetic: 87882
 scriptlet: 20840
 html: 0
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25924-19, 1m
 default:
  user-filters: 7-0, never
  RUS-0: 39984-129, 2m
  easylist: 75311-54, 2m
  easyprivacy: 33075-240, 2m
  plowe-0: 3777-1142, 2m
  ublock-badware: 7599-138, 2m
  ublock-filters: 35853-214, 2m
  ublock-privacy: 929-15, 2m
  ublock-quick-fixes: 182-9, 2m
  ublock-unbreak: 2157-32, 2m
  urlhaus-1: 10690-0, 1h.40m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 787 ms
 maxAssetCacheWait: 356 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
report directly at RUAdlist repo
https://github.com/easylist/ruadlist/issues

**Comment by dimisa-RUAdList** [comment]
@mapx- 
It turned out to be not Chromium: 118 at all, but a Yandex browser.
