### ISSUE TITLE
vumoo.to: nuisance

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21320]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://vumoo.to/tv-series/paper-dolls-season-1`

### Category

nuisance

### Description

Anti right click and page automatically closes when dev tools is open.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 104681
 cosmetic: 45582
 scriptlet: 23732
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6126-11, 9m
 default:
  user-filters: 51-3, never
  easylist: 75311-16, 9m
  easyprivacy: 33075-65, 9m
  plowe-0: 3777-1137, 9m
  ublock-badware: 7599-138, 9m
  ublock-filters: 35852-182, 9m
  ublock-privacy: 929-12, 9m
  ublock-quick-fixes: 180-9, 9m
  ublock-unbreak: 2157-32, 9m
  urlhaus-1: 10690-0, 9m
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 132 ms (selfie)
 maxAssetCacheWait: 55 ms
popupPanel:
 blocked: 7
 network:
  aheaptorsos.life: 1
  gloaphoo.net: 1
  googletagmanager.com: 2
  histats.com: 1
  moksoxos.com: 2
 extended:
  ##+js(addEventListener-defuser, , break;case $.)
  ##+js(abort-current-script, Math, break;case $.)
```
</details>

**Comment by mapx-** [comment]
test

    vumoo.to##+js(nosiif, detect)
    vumoo.to##+js(aeld, contextmenu)
    vumoo.to##+js(aeld, , key)

**Comment by huyszn** [comment]
> test
> 
> ```
> vumoo.to##+js(aeld, , key)
> vumoo.to##+js(aeld, contextmenu)
> vumoo.to##+js(nosiif, detect)
> ```

Works. The console also keeps getting cleared.

**Comment by mapx-** [comment]
maybe it's better:

    ||cdn.jsdelivr.net/npm/disable-devtool$script,domain=embed.meomeo.pw|vumoo.to

**Comment by huyszn** [comment]
> maybe it's better:
> 
> ```
> ||cdn.jsdelivr.net/npm/disable-devtool$script,domain=embed.meomeo.pw|vumoo.to
> ```

This works to stop all the annoyances.
