### ISSUE TITLE
youtube.com: detection

### ISSUE THREAD

**Issue by cse-sohel** [uBlockOrigin/uAssets#21325]
### Prerequisites

- [ ] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.youtube.com/watch?v=71LpfNohah4`

### Category

detection

### Description

Ad blockers violate YouTube's Terms of Service
It looks like you may be using an ad blocker. Video playback is blocked unless YouTube is allowlisted or the ad blocker is disabled.
Ads allow YouTube to be used by billions worldwide.
You can go ad-free with YouTube Premium, and creators can still get paid from your subscription.

### Other extensions used

Kaspersky Protection, Surfshark

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/109166659/56923243-7264-4702-82c3-54356d31c0c4)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104390
 cosmetic: 43975
 scriptlet: 19467
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  easylist: 75311-16, now
  easyprivacy: 33075-65, 55m
  plowe-0: 3777-1137, now
  ublock-badware: 7599-138, 55m
  ublock-filters: 35854-182, 55m
  ublock-privacy: 929-12, 55m
  ublock-quick-fixes: 170-9, 55m
  ublock-unbreak: 2156-31, 55m
  urlhaus-1: 10690-0, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 172 ms (selfie)
 maxAssetCacheWait: 71 ms
popupPanel:
 blocked: 5
 network:
  doubleclick.net: 3
  google.com: 1
  google.com.bd: 1
 extended:
  ###related > div#player-ads
  ###ytd-player button.ytp-suggested-action-badge
  ##.ytd-merch-shelf-renderer
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
go to https://github.com/uBlockOrigin/uAssets/issues/20586
