### ISSUE TITLE
bluemediastorage.online: detection

### ISSUE THREAD

**Issue by Gho24** [uBlockOrigin/uAssets#21330]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Tried several browsers (freshly installed), like Avast Privacy Browser, Brave, Chrome, Comodo Dragon, Edge, Firefox, Librewolf, Opera, and Vivaldi.

Without uBlock Origin (or the Lite version), the page doesn't display the "adblock detected" message, but the site is almost unusable due to all the popups, banners, and fake links (you click to download something, but actually just loads a different page).

Adblock is very much essential to navigate thre but this site ( BlueMediaStorage.Online ) is completely immune to uBlock Origin and uBlock Origin Lite.

![BlueMediaStorage_Online](https://github.com/uBlockOrigin/uBlock-issues/assets/153461932/a5eb8048-9373-47df-9731-9f617d53d4ca)

### A specific URL where the issue occurs.

`https://bluemediastorage.online/url-generator-1.php?url=SDUS9bRvhba8BF9dQAj5comiFx0bhxery/96OdCrErTpjYNoQWVLVsmJ+TpCiaDSF9aMAYR/tMlsEyDl874rAw==`

### Steps to Reproduce

Step 1: Just visit the link and, after 5 seconds, it always happens.

### Expected behavior

After the 5 second countdown, a button labelled "Download" should appear. And when clicking said button, the page should redirect to a MegaUp page.

### Actual behavior

The ads still appear (uBlock fails to stop them), and after 5 seconds you get a popup demanding to turn off any adblocking software.

### uBO version

1.53

### Browser name and version

Latest version (freshly installed and fully updated) of Avast Privacy Browser, Brave, Chrome, Comodo Dragon, Edge, Firefox, LibreWolf, Opera, and Vivaldi.

### Operating System and version

Windows 10, fully updated.

**Comment by Gho24** [comment]
Why don't people read before replying?

1 - I'm NOT using ANY other adblocker!

2 - I already tried updating uBO filters, and it doesn't work!

Some people are really quick in closing raised issues, but not in actually fixing/solving them.

Can someone actually help in this issue, please?

**Comment by mapx-** [comment]
` closed` this as [completed](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/uBlockOrigin/uAssets/commit/9e33f1c1bb041e06a4bbeb9c01c067f854cae9b7

You should read carefully: I already fixed your issue and I asked you to update NOW the filters.

**Comment by Gho24** [comment]
It has been over half an hour when I tried it, and it didn't work after all that time, but it's working now.

Thank you.
