### ISSUE TITLE
wetransfer.com: ads

### ISSUE THREAD

**Issue by MaddyMurder** [uBlockOrigin/uAssets#21340]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://wetransfer.com/`

### Category

ads

### Description

While uploading a file, the ads will constantly load and be removed again causing a flashing behavior. Notice how the ads blocked are slowly increasing in the attached video

### Other extensions used

Dark reader (the bug persists when turned off)
Violent monkey (no scripts are active on wetransfer)
Enhancer for Youtube
Sponsorblock for Youtube
Return Youtube dislike
Youtube search filter
Bing chat for all browser
Text translater (not used)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/150319218/3f768371-a9c3-46b7-8b81-5968bc0ab44f

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 104360
 cosmetic: 43967
 scriptlet: 19276
 html: 1128
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 36731-195, 32m
  ublock-badware: 7605-11, 32m
  ublock-privacy: 923-4, 32m
  ublock-unbreak: 2203-0, 32m
  ublock-quick-fixes: 183-2, 32m
  easylist: 75325-547, 32m
  easyprivacy: 33075-835, 32m
  urlhaus-1: 10650-0, 32m
  plowe-0: 3777-1, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 698 ms (selfie)
 maxAssetCacheWait: 60 ms
popupPanel:
 blocked: 259
 network:
  wetransfer.com: 136
  amplitude.com: 12
  brandmetrics.com: 7
  cloudflare.com: 1
  doubleclick.net: 50
  google.com: 1
  googletagmanager.com: 1
  moatads.com: 51
```
</details>

**Comment by mapx-** [comment]
add & test

```
||backgrounds.wetransfer.net/*.mp4$media,1p
||backgrounds.wetransfer.net$image
backgrounds.wetransfer.net##we-wallpaper
wetransfer.com##.wallpaper
wetransfer.com##.DropZone--default.DropZone
```

**Comment by MaddyMurder** [comment]
This fixed the issue, but breaks the drag and drop functionality of the website

**Comment by mapx-** [comment]
I removed the last filter, test again
