### ISSUE TITLE
aiyingshi.tv: ads

### ISSUE THREAD

**Issue by Ei3-kw** [uBlockOrigin/uAssets#21341]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.aiyingshi.tv/play/91074-0-1.html`

### Category

ads

### Description

ublock doesn't seem to detect any ads on the side
<img width="1512" alt="Screenshot 2023-12-11 at 6 50 45 pm" src="https://github.com/uBlockOrigin/uAssets/assets/52182320/491adba5-d654-4a1b-b67c-426bdecab2d5">
<img width="1584" alt="Screenshot 2023-12-11 at 6 54 00 pm" src="https://github.com/uBlockOrigin/uAssets/assets/52182320/70ec29aa-b14d-4b06-9694-29685adf0160">

### Other extensions used

LastPass

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1512" alt="Screenshot 2023-12-11 at 6 50 45 pm" src="https://github.com/uBlockOrigin/uAssets/assets/52182320/491adba5-d654-4a1b-b67c-426bdecab2d5">
<img width="1584" alt="Screenshot 2023-12-11 at 6 54 00 pm" src="https://github.com/uBlockOrigin/uAssets/assets/52182320/70ec29aa-b14d-4b06-9694-29685adf0160">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 104382
 cosmetic: 43983
 scriptlet: 19472
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75331-16, now
  easyprivacy: 33075-65, 1h.17m
  plowe-0: 3777-1137, now
  ublock-badware: 7601-138, now
  ublock-filters: 35870-179, now
  ublock-privacy: 929-12, now
  ublock-quick-fixes: 182-11, 1h.16m
  ublock-unbreak: 2157-31, now
  urlhaus-1: 10650-0, now
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1651 ms
 maxAssetCacheWait: 875 ms
popupPanel:
 blocked: 6
 network:
  google-analytics.com: 1
  googletagmanager.com: 3
  statcounter.com: 1
  taboola.com: 1
```
</details>

**Comment by mapx-** [comment]
enable AdGuard Chinese

**Comment by Ei3-kw** [comment]
after enabling it, the ads still show up, just not marked as 'ads'. It still takes me to sites after clicking on it. Log is still empty.
<img width="1512" alt="Screenshot 2023-12-11 at 7 29 50 pm" src="https://github.com/uBlockOrigin/uAssets/assets/52182320/f31e69b7-327a-417f-9c8c-51bfc85d123b">
<img width="1584" alt="Screenshot 2023-12-11 at 7 33 59 pm" src="https://github.com/uBlockOrigin/uAssets/assets/52182320/e56fa155-5a05-4efa-9ed8-aa430f842a17">

**Comment by Ei3-kw** [comment]
Just did, the results are the same :((

**Comment by mapx-** [comment]
Did you enable back the chinese list ?

I need only this filter (to remove the clickable overlay)

`aiyingshi.tv###ADmask`

@cjx82630

**Comment by Ei3-kw** [comment]
I did, and the video (ad) at the start is still clickable, not sure if it's overlay. I have tried clearing the caches
<img width="1512" alt="Screenshot 2023-12-11 at 8 27 57 pm" src="https://github.com/uBlockOrigin/uAsset
<img width="1512" alt="Screenshot 2023-12-11 at 8 29 07 pm" src="https://github.com/uBlockOrigin/uAssets/assets/52182320/5d5631f4-e99f-4f22-839b-08d0ac5eb52b">
s/assets/52182320/a9816920-8a05-437f-a4c1-7620b0be1310">

**Comment by mapx-** [comment]
Are you using chrome or some other chromium browser ?

**Comment by Ei3-kw** [comment]
I'm using Arc, and yes it's chromium

**Comment by Ei3-kw** [comment]
<img width="1584" alt="Screenshot 2023-12-11 at 8 36 27 pm" src="https://github.com/uBlockOrigin/uAssets/assets/52182320/83c70640-037b-4a73-bb84-848b44532dde">
it doesn't work on firefox either tho, just tried

**Comment by mapx-** [comment]
I notified chinese list maintainer

However, you can report directly here:
https://github.com/cjx82630/cjxlist/issues

**Comment by Ei3-kw** [comment]
thx!!

**Comment by mapx-** [comment]
you could take these steps, maybe will help you:

- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
