### ISSUE TITLE
bever.nl: breakage

### ISSUE THREAD

**Issue by RPiNut** [uBlockOrigin/uAssets#21349]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bever.nl/`

### Category

breakage

### Description

For our dutch friends, I was looking around at bever.nl and sorting on pricing low/high doesn't work with uBO turned on. This is also for the product pages, when selecting the dropdown menu for size, information and so on. Below you can find some screenshots of with uBO turned on and off.

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

uBO turned on:
![image](https://github.com/uBlockOrigin/uAssets/assets/76691078/e4e0ec53-826f-4c24-ad67-b00835c090ad)
![image](https://github.com/uBlockOrigin/uAssets/assets/76691078/d08ed616-43b2-4a3f-811a-8b4ceb4d6834)
![image](https://github.com/uBlockOrigin/uAssets/assets/76691078/5ba75fcf-871b-49f0-ba12-b2be222c9433)

uBO turned off:
![image](https://github.com/uBlockOrigin/uAssets/assets/76691078/ace7aa5d-d2ad-484e-b038-007c7bf9b708)
![image](https://github.com/uBlockOrigin/uAssets/assets/76691078/18a7da7d-832c-46e4-b794-a8ef92c0b95c)
![image](https://github.com/uBlockOrigin/uAssets/assets/76691078/16f3bb32-b7ac-40b6-8d40-9057fa1b0a7c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 115464
 cosmetic: 194608
 scriptlet: 27455
 html: 1132
listset (total-discarded, last-updated):
 added:
  adguard-social: 22080-872, now
  adguard-cookies: 28267-61, now
  adguard-popup-overlays: 26563-1562, now
  adguard-mobile-app-banners: 4831-1069, now
  adguard-other-annoyances: 14035-272, now
  adguard-widgets: 2356-1, now
  fanboy-thirdparty_social: 69-0, now
  easylist-annoyances: 4238-121, now
  easylist-chat: 168-12, now
  fanboy-cookiemonster: 49164-3828, now
  easylist-newsletters: 6721-13, now
  easylist-notifications: 2889-4, now
  [3 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36764-347, 29m
  ublock-badware: 7610-11, 29m
  ublock-privacy: 931-4, 29m
  ublock-unbreak: 2203-0, 29m
  ublock-quick-fixes: 186-2, 29m
  easylist: 75374-798, 29m
  easyprivacy: 33094-898, 29m
  urlhaus-1: 10745-0, 29m
  plowe-0: 3777-1, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 618 ms (selfie)
 maxAssetCacheWait: 157 ms
popupPanel:
 blocked: 1
 network:
  monetate.net: 1
 extended:
  ##div.newsletter-subscribe
```
</details>

**Comment by gorhill** [comment]
Caused by `bever.nl##.as-m-popover` in _EasyList – Cookie Notices_.

cc @ryanbr
