### ISSUE TITLE
thesaurus.net: ads

### ISSUE THREAD

**Issue by Prissy69** [uBlockOrigin/uAssets#21346]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.thesaurus.net/atlas`

### Category

ads

### Description

Pieces of all ads still appear. I didn't finish your list above because I don't understand most of the content, sorry. 72 year old barely computer literate person here, working on a desktop computer. Up to today, UBlock Origin took care of blocking all ads, so this is pretty distressing.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-11 at 10-50-33 Thesaurus Check Thesaurus Online for Free](https://github.com/uBlockOrigin/uAssets/assets/153533132/216f0e34-0a29-4f68-97d5-dc570d2b8d4c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 104476
 cosmetic: 43981
 scriptlet: 19278
 html: 1130
listset (total-discarded, last-updated):
 added:
  https://www.ebates.com/whitelist/ebates-cash-back-shopping.txt: 0-0, now
 default:
  user-filters: 2-0, never
  ublock-filters: 36748-67, 32m
  ublock-badware: 7605-11, 32m
  ublock-privacy: 927-4, 32m
  ublock-unbreak: 2203-0, 32m
  easylist: 75334-673, 32m
  easyprivacy: 33093-846, 32m
  urlhaus-1: 10745-0, now
  plowe-0: 3777-1, now
  ublock-quick-fixes: 183-2, 32m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 8 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1658 ms (selfie)
 maxAssetCacheWait: 1026 ms
popupPanel:
 blocked: 32
 network:
  thesaurus.net: 1
  criteo.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 2
  html-load.com: 20
  infolinks.com: 2
  vuukle.com: 4
 extended:
  ##.header-ads
  ##div[id^="vuukle-ad-"]
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed the issue.

The ads was unblocked because they try to avoid adlocking. Should work fine now.

To get the fix without waiting: Click on the uBO icon -> gears -> filterlists -> purge all cache -> update now.

**Comment by gorhill** [comment]
> To get the fix without waiting [...]

Or [click this link](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-privacy)

**Comment by Prissy69** [comment]
Thank you so much for taking care of this, and so quickly. Much appreciated.
--Prissy69

    On Monday, December 11, 2023 at 11:18:59 AM EST, JobcenterTycoon ***@***.***> wrote:  
 
 


Fixed the issue.

The ads was unblocked because they try to avoid adlocking. Should work fine now.

To get the fix without waiting: Click on the uBO icon -> gears -> filterlists -> purge all cache -> update now.

**Comment by piquark6046** [comment]
Fixed.
