### ISSUE TITLE
zippia.com: nuisance

### ISSUE THREAD

**Issue by bibibirdy** [uBlockOrigin/uAssets#21354]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zippia.com/economic-developer-jobs/education/?src=chatbot_popout_displayed`

### Category

nuisance

### Description

New pop-up window that the site did not previously have on this page. Attempts to force creation of a free account.

### Other extensions used

unpaywall

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-11 143525](https://github.com/uBlockOrigin/uAssets/assets/153561014/7b7a0cea-59d3-4592-9b2d-ea6fa9ae2b2a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 104512
 cosmetic: 43994
 scriptlet: 19294
 html: 1132
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36768-196, now
  ublock-badware: 7610-11, now
  ublock-privacy: 931-4, now
  ublock-unbreak: 2203-0, now
  easylist: 75374-548, now
  easyprivacy: 33094-846, now
  urlhaus-1: 10745-0, now
  plowe-0: 3777-1, now
  ublock-quick-fixes: 186-2, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 585 ms (selfie)
 maxAssetCacheWait: 57 ms
popupPanel:
 blocked: 6
 network:
  clarity.ms: 1
  google.com: 3
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
zippia.com##+js(nosiif, /onGatedSignupPopupTrigger|zippia-popup/)
zippia.com##+js(set-local-storage-item, gatedSignupTimerCounter, $remove$)
```

@ryanbr

**Comment by stephenhawk8054** [comment]
Fixed in `EasyList – Other Annoyances` list. You can enable that list or add the above filters as custom filters (Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again)
