### ISSUE TITLE
tech-latest.com: ads

### ISSUE THREAD

**Issue by ave9858** [uBlockOrigin/uAssets#21355]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tech-latest.com/be-quiet-shadow-base-800-fx-review/`

### Category

ads

### Description

Surfshark ads and ad placeholders shown.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/112294121/8e19ccc8-ac50-41f7-beb7-04c76b148c6d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 104523
 cosmetic: 43996
 scriptlet: 19297
 html: 1132
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36771-67, now
  ublock-badware: 7610-11, now
  ublock-privacy: 931-4, now
  ublock-unbreak: 2203-0, now
  ublock-quick-fixes: 186-2, now
  easylist: 75384-716, now
  easyprivacy: 33094-804, now
  urlhaus-1: 10745-0, now
  plowe-0: 3777-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1030 ms
 maxAssetCacheWait: 345 ms
popupPanel:
 blocked: 18
 network:
  cloudflareinsights.com: 2
  googlesyndication.com: 12
  googletagmanager.com: 1
  nitropay.com: 2
  outbrain.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
add

`tech-latest.com##.code-block:has-text(Advertisement)`

@ryanbr
