### ISSUE TITLE
ip.sb: detection

### ISSUE THREAD

**Issue by Daxy7** [uBlockOrigin/uAssets#21352]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ip.sb/api/`

### Category

detection/nuisance

### Description

shows sticky far bottom of the page stating 
`In order to support the long term operation of this site, please whitelist our website`

`https://ip.sb/assets/js/wwads_blocked.js?var=20210930`

code:
```
https://pastebin.com/raw/qPASs21p
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/91396482/fd601cf2-f39c-4697-a84d-9450649b391e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 92271
 cosmetic: 47294
 scriptlet: 23938
 html: 1333
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/5811c0757dad027282fb82f9c751c79fe4f9306e/bpc-paywall-filter.txt: 905-0, now
  https://raw.githubusercontent.com/Daxy7/webSiteFilters/main/Ublock/getadmiral_bypass_warnings.txt: 1954-0, now
  ublock-annoyances: 6104-12, now
 default:
  user-filters: 1955-15, never
  ublock-filters: 36768-93, now
  ublock-badware: 7610-11, now
  ublock-privacy: 931-4, now
  ublock-unbreak: 2203-0, now
  ublock-quick-fixes: 186-2, now
  easylist: 75374-366, now
  easyprivacy: 33094-1665, now
filterset (user): [array of 933 redacted]
trustedset:
 added: [array of 7 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 10 redacted]
hostRuleset:
 added: [array of 10 redacted]
 removed:
  behind-the-scene * * noop
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 360 ms (selfie)
 maxAssetCacheWait: 116 ms
 unsuspendAfter: 178 ms
popupPanel:
 blocked: 5
 network:
  googlesyndication.com: 1
  wwads.cn: 2
  xtom.com: 2
 extended:
  ##.advert_title
  ##.advert_text
  ##*:style(border-radius:0px !important;)
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed in the annoyance list.
