### ISSUE TITLE
tv3sport.dk: ads

### ISSUE THREAD

**Issue by Mickey182** [uBlockOrigin/uAssets#21364]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tv3sport.dk/sport/fodbold/nyheder/overblik-sadan-gar-fck-videre-i-champions-league`

### Category

ads

### Description

Vidoes on this website show adds at the start

### Other extensions used

Privacy Badger

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (220)](https://github.com/uBlockOrigin/uAssets/assets/58091794/20f4ccf2-e51b-4acf-bfb9-45e5b6dbd723)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 104889
 cosmetic: 43990
 scriptlet: 19314
 html: 1131
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36879-200, now
  ublock-badware: 7610-11, now
  ublock-privacy: 931-4, now
  ublock-unbreak: 2209-0, now
  ublock-quick-fixes: 87-2, now
  easylist: 75532-590, now
  easyprivacy: 33129-804, now
  urlhaus-1: 10930-0, now
  plowe-0: 3777-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1410 ms (selfie)
 maxAssetCacheWait: 995 ms
popupPanel:
 blocked: 10
 network:
  adnuntius.com: 1
  bidswitch.net: 2
  creative-serving.com: 1
  fwmrm.net: 4
  sentry.io: 1
  typekit.net: 1
 extended:
  ##.ad-row
```
</details>

**Comment by mapx-** [comment]
Enable the regional list `Dandelion Sprouts nordiske filtre`
