### ISSUE TITLE
washingtonpost.com: nuisance

### ISSUE THREAD

**Issue by JakSpoon** [uBlockOrigin/uAssets#21368]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.washingtonpost.com/entertainment/video-games/2023/12/12/e3-permanently-canceled/`

### Category

"unlimited access" nuisance

### Description

By accessing the site, viewing the page is blocked!

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Opera Snapshot_2023-12-12_154628_www washingtonpost com](https://github.com/uBlockOrigin/uAssets/assets/63912221/ad8cc115-16e5-46dd-adcb-53fb30cb8be3)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 184990
 cosmetic: 50731
 scriptlet: 19514
 html: 0
listset (total-discarded, last-updated):
 added:
  curben-phishing: 77837-20, now
 default:
  user-filters: 0-0, never
  ITA-0: 8788-20, now
  easylist: 75532-23, now
  easyprivacy: 33129-66, now
  plowe-0: 3777-1148, now
  ublock-badware: 7606-144, now
  ublock-filters: 36004-190, now
  ublock-privacy: 935-12, now
  ublock-quick-fixes: 91-17, now
  ublock-unbreak: 2163-31, now
  urlhaus-1: 11190-0, now
filterset (user): [empty]
trustedset:
 added: [array of 149 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 764 ms (selfie)
 maxAssetCacheWait: 126 ms
popupPanel:
 blocked: 12
 network:
  3gl.net: 1
  amazon-adsystem.com: 1
  brandmetrics.com: 1
  doubleclick.net: 1
  google.com: 3
  googleoptimize.com: 1
  googletagmanager.com: 1
  unpkg.com: 1
  webcontentassessor.com: 1
  zeustechnology.com: 1
 extended:
  ##[data-qa="right-rail-ad"]
  ##[data-testid="placeholder-box"]
  ##.outbrain-wrapper
  ##[data-ad-module]:not([style$="left: -10000px !important; top: …
  #@#[data-ad-module]
  ##+js(acs, Promise, overlay)
  ##+js(acs, document.createElement, overlay)
  ##+js(rmnt, script, /\badblock\b/)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by peace2000** [comment]
Hi, paywalls are out of uAssets scope, as stated here: https://github.com/uBlockOrigin/uAssets

>uAssets will not address the following:
> Paywalls

For bypassing paywalls, use other browser addons. Maybe this tool will work: `https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean`
