### ISSUE TITLE
newsbeast.gr: detection

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#21361]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.newsbeast.gr/lifestyle/arthro/10315101/den-thelo-gamo-tha-tsakothoume-epeidi-den-vazei-plyntirio-eipe-o-giannis-tsimitselis-gia-tin-katerina-geronikolou`

### Description

glomex player adblock detect when pressing play video (see screenshot)

### Other extensions used

not relevant

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/24896778/491a8d15-f49f-4eea-a902-27da51dce10a)

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by mapx-** [comment]
Your config details are missing.
No detection on my side, only some PH

```
newsbeast.gr##.amSlotFeed
newsbeast.gr##.amSlotInReadVideo
newsbeast.gr##.undeMenuAmSlot2
newsbeast.gr##.amunitContainer
```

report at regional list repository: https://github.com/kargig/greek-adblockplus-filter/issues
