### ISSUE TITLE
tomsguide.com: ads

### ISSUE THREAD

**Issue by Sym8** [uBlockOrigin/uAssets#21360]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tomsguide.com/opinion/oneplus-12-is-coming-with-a-feature-all-other-phones-need-to-copy`

### Category

ads

### Description

Cosmetic filtering not clearing the blocked ad place holder

### Other extensions used

Dark reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-12-12-14-25-24-74_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/66876418/8e9c8cc4-7e2c-4148-8bf5-67a6763dec8f)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 120
filterset (summary):
 network: 109117
 cosmetic: 87176
 scriptlet: 24510
 html: 1333
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28274-59, now
  easylist-newsletters: 6723-7, now
  easylist-notifications: 2890-4, now
  ublock-annoyances: 6169-717, now
  ublock-cookies-adguard: 698-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37113-119, now
  ublock-badware: 7604-11, now
  ublock-privacy: 931-4, now
  ublock-unbreak: 2214-0, now
  ublock-quick-fixes: 184-2, now
  adguard-mobile: 8799-100, now
  easylist: 75532-730, now
  easyprivacy: 33130-929, now
  urlhaus-1: 10930-0, now
  plowe-0: 3777-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 353 ms (selfie)
 maxAssetCacheWait: 119 ms
popupPanel:
 blocked: 44
 network:
  tomsguide.com: 1
  33across.com: 1
  3lift.com: 1
  adnxs.com: 1
  adsafeprotected.com: 1
  advertising.com: 1
  amazon-adsystem.com: 1
  bfmio.com: 1
  bidswitch.net: 1
  casalemedia.com: 1
  dotmetrics.net: 1
  dotomi.com: 1
  doubleclick.net: 1
  futurehybrid.tech: 1
  futureplc.com: 1
  google-analytics.com: 1
  googletagmanager.com: 2
  gumgum.com: 1
  liadm.com: 1
  lijit.com: 1
  omnitagjs.com: 1
  openx.net: 1
  parsely.com: 1
  permutive.app: 2
  pubmatic.com: 3
  rubiconproject.com: 1
  scorecardresearch.com: 1
  servebom.com: 7
  sharethrough.com: 1
  sonobi.com: 2
  taboola.com: 1
  tremorhub.com: 1
  yahoo.com: 1
 extended:
  ##.van_vid_carousel
  ##.related-articles-block
  ##.van_taboola
  ##div[class*="ad-unit"]
  ##.vid-present
  ##.ad-unit:not(.text-ad):not(.textads)
  ##.dfp-leaderboard-container
  ###slice-container-newsletterForm-exitIntent
  ##.newsletterForm-exitIntent
  ##.slice-container-newsletterForm
  ###taboola-below-article-thumbnails
  ###hawkMagWidget
  ##.mobile-leaderboard-320-50:upward([style])
  #@#.ad-unit
  ##+js(trusted-set-cookie, consentUUID, 642425b5-b07b-421f-a5dd-a…
  ##+js(abort-on-property-read, _sp_._networkListenerData)
```
</details>

**Comment by mapx-** [comment]
add

`tomsguide.com##.bordeaux-slot`

@ryanbr
