### ISSUE TITLE
zippyupload.com: nuisance

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21378]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.zippyupload.com/`

### Category

nuisance

### Description

Anti right click and anti-adb banners

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 105482
 cosmetic: 45617
 scriptlet: 23764
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6162-11, 17m
 default:
  user-filters: 41-2, never
  easylist: 75554-17, 17m
  easyprivacy: 33127-66, 17m
  plowe-0: 3778-1147, 17m
  ublock-badware: 7611-138, 17m
  ublock-filters: 35968-181, 17m
  ublock-privacy: 937-12, 17m
  ublock-quick-fixes: 93-13, 17m
  ublock-unbreak: 2163-32, 17m
  urlhaus-1: 11195-0, 17m
filterset (user): [array of 38 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 132 ms (selfie)
 maxAssetCacheWait: 55 ms
popupPanel:
 blocked: 8
 network:
  zippyupload.com: 6
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by huyszn** [comment]
@stephenhawk8054 Right-click works initially but if you click on different links on the site a few times and then try to right-click again, the right-click doesn't work. This only happens in chrome.

**Comment by stephenhawk8054** [comment]
Which links did you click on? Can you describe the steps to reproduce in more details?

**Comment by huyszn** [comment]
I refresh the `zippyupload.com` main page and I can right-click. When I click on different links on the page like the `Login` and `Register` pages and try to right-click again, the right-click does not work.
