### ISSUE TITLE
pling.com, store.kde.org, xfce-look.org, gnome-look.org: nuisance

### ISSUE THREAD

**Issue by FakeAdsCollection** [uBlockOrigin/uAssets#21372]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.pling.com/p/1678986` and other pling website (store.kde.org, xfce-look.org, gnome-look.org, etc..)

### Description

need to wait 10 seconds before downloading, can you speed up the countdown in download button?

### Other extensions used

User agent switcher and manager, Absolute enable right click & copy, Tampermonkey, Stylus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/73978235/b497e9ae-7e5a-4e71-8af7-ddf97d01c38d)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.1b9
Chromium: 120
filterset (summary):
 network: 105176
 cosmetic: 43957
 scriptlet: 19441
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 12-0, never
  easylist: 75532-16, 3h.7m Δ
  easyprivacy: 33129-66, 3h.7m Δ
  plowe-0: 3784-1147, 12d.46m
  ublock-badware: 7606-138, 3h.7m Δ
  ublock-filters: 35875-179, 1d.9h.27m
  ublock-privacy: 934-12, 3h.7m Δ
  ublock-quick-fixes: 92-8, 3h.7m Δ
  ublock-unbreak: 2163-31, 3h.7m Δ
  urlhaus-1: 11190-0, 3h.7m
filterset (user): [array of 12 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 688 ms
 maxAssetCacheWait: 187 ms
popupPanel:
 blocked: 3
 network:
  pling.com: 1
  google-analytics.com: 1
  opendesktop.org: 1
```
</details>

**Comment by huyszn** [comment]
@ItsProfessional There are also other related domains: `appimagehub.com`, `opendesktop.org`, `linux-apps.com`

**Comment by 96273** [comment]
Please add `pik.opendesktop.org/pik.js` to the privacy filters. It is a Matomo tracking instance used by the opendesktop.org and pling.com network to monitor user activity.
