### ISSUE TITLE
swisstph.ch: breakage

### ISSUE THREAD

**Issue by saucefrog** [uBlockOrigin/uAssets#21370]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.swisstph.ch/de/reisemedizin/covid-19-impfung`

### Category

breakage

### Description

Webpage stays blank except for a small blue rectangle on the top when uBlock is active. Deactivating uBlock makes the website work.

### Other extensions used

Way too many to list them all.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 199920
 cosmetic: 197815
 scriptlet: 48938
 html: 1332
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76084-7457, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95026-52865, now
  adguard-generic: 81449-5646, now
  adguard-mobile: 8799-128, now
  adguard-social: 22084-1433, now
  fanboy-thirdparty_social: 68-1, now
  fanboy-cookiemonster: 64503-64503, 1h.29m
  fanboy-social: 16000-11637, now
  ublock-annoyances: 6108-14, 1h.29m
  adguard-spyware: 80432-688, now
 default:
  ublock-filters: 36778-373, 1h.29m
  ublock-badware: 7610-11, 1h.29m
  ublock-privacy: 931-5, 1h.29m
  ublock-unbreak: 2209-1, 1h.29m
  easylist: 75532-18599, 1h.29m
  easyprivacy: 33130-16999, 1h.29m
  urlhaus-1: 11190-0, now
  plowe-0: 3777-1, now
  DEU-0: 7212-405, now
  ublock-quick-fixes: 184-2, 1h.29m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 73 redacted]
 removed:
  about-scheme
  edge-scheme
  moz-extension-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 516 ms (selfie)
 maxAssetCacheWait: 154 ms
popupPanel:
 blocked: 6
 network:
  swisstph.ch: 1
  googletagmanager.com: 3
  privacy-center.org: 2
```
</details>

**Comment by mapx-** [comment]
add

`@@||swisstph.ch/*/gdpr.min.js$script,1p`


@ryanbr
