### ISSUE TITLE
techreport.com: ads

### ISSUE THREAD

**Issue by lucinder** [uBlockOrigin/uAssets#21373]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://techreport.com/`

### Category

ads

### Description

Lower banner ad for a bitcoin miner. Same ad every time, so might be built-in to the site.

### Other extensions used

Facebook Container (checked with active and inactive)
Bypass Paywalls (checked with active and inactive)
uBlacklist (checked with active and inactive)
Tampermonkey
Zotero Connector
VTT Enhancement Suite

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-12 111019](https://github.com/uBlockOrigin/uAssets/assets/81818595/73eab51c-c39c-44ff-a5e1-73e44c91fd7d)
![Screenshot 2023-12-12 111047](https://github.com/uBlockOrigin/uAssets/assets/81818595/17eb6b87-c7ee-476b-be2c-b92762b4b8a2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105158
 cosmetic: 43986
 scriptlet: 19316
 html: 1131
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 36879-199, 1h.29m
  ublock-badware: 7610-11, 1h.29m
  ublock-privacy: 931-4, 1h.29m
  ublock-unbreak: 2209-0, 1h.29m
  ublock-quick-fixes: 91-2, 1h.29m
  easylist: 75532-590, 1h.29m
  easyprivacy: 33129-804, 1h.29m
  urlhaus-1: 11190-0, 2m
  plowe-0: 3777-1, 2m
filterset (user): [array of 2 redacted]
trustedset:
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 764 ms (selfie)
 maxAssetCacheWait: 251 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by okiehsch** [comment]
`techreport.com##.clickout-banner-regular_native_box-bottom`

@ryanbr
