### ISSUE TITLE
arras.io: detection

### ISSUE THREAD

**Issue by Zenphia** [uBlockOrigin/uAssets#21374]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://arras.io`
`https://arras.netlify.app`
`https://arrax.io`

### Description

Ingame notification when spawning in (which reappears periodically while playing) and on the death screen (to test the last one, press `O` after joining a server)

Recent fix provided in https://github.com/uBlockOrigin/uAssets/issues/21301 was patched.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="448" alt="Screenshot 2023-12-09 at 15 39 21" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/207cce5c-3493-46e0-a6a7-90d6a93df60e">
<img width="752" alt="Screenshot 2023-12-09 at 15 39 41" src="https://github.com/uBlockOrigin/uAssets/assets/93544652/72d56942-a641-4d38-97d9-7fe26712089d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 107154
 cosmetic: 69267
 scriptlet: 20485
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28274-30, now
 default:
  user-filters: 28-0, never
  easylist: 75531-19, now
  easyprivacy: 33129-69, now
  plowe-0: 3777-1148, now
  ublock-badware: 7606-138, now
  ublock-filters: 35971-186, now
  ublock-privacy: 936-12, now
  ublock-quick-fixes: 93-13, now
  ublock-unbreak: 2163-31, now
  urlhaus-1: 11190-0, now
filterset (user): [array of 24 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 122 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel:
 blocked: 5
 network:
  arras.io: 2
  cloudflareinsights.com: 1
  googletagmanager.com: 1
  intergient.com: 1
 extended:
  ##.referral-fallback
  ##+js(remove-node-text, script, intergient.com)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
do not open new issues, continue there https://github.com/uBlockOrigin/uAssets/issues/21301
