### ISSUE TITLE
ygosu.com: ads

### ISSUE THREAD

**Issue by aaswqwdqssd** [uBlockOrigin/uAssets#21387]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ygosu.com/`

### Category

ads

### Description

Ad blocking does not work properly on this site.

### Other extensions used

none 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 106374
 cosmetic: 47386
 scriptlet: 19629
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 11-0, never
  KOR-1: 4891-10, 4m
  easylist: 75554-60, 4m
  easyprivacy: 33127-76, 4m
  plowe-0: 3778-1162, now
  ublock-badware: 7611-138, 4m
  ublock-filters: 35970-185, 4m
  ublock-privacy: 937-14, 4m
  ublock-quick-fixes: 92-14, 4m
  ublock-unbreak: 2163-31, 4m
  urlhaus-1: 11090-0, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 341 ms (selfie)
 maxAssetCacheWait: 137 ms
popupPanel:
 blocked: 100
 network:
  07c225f3.online: 71
  coupang.com: 20
  criteo.net: 3
  googlesyndication.com: 2
  googletagmanager.com: 3
  vntsm.com: 1
 extended:
  ##table.bd_list tr:has(a[href^="/board/ad/"])
  ##+js(no-xhr-if, /static\.criteo\.net|adsbygoogle/)
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, as_profile_cache, $remove$)
  ##+js(set-local-storage-item, as_accetpable_ads_blocked_cache, $…
  ##+js(set-local-storage-item, as_adblock_cache, $remove$)
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/21385

**Comment by JobcenterTycoon** [comment]
Confirmed.

These ads are hard to block because they are generated by "Ad-Shield", for the best blocking results try this https://github.com/List-KR/microShield
