### ISSUE TITLE
st.com: breakage

### ISSUE THREAD

**Issue by renzenicolai** [uBlockOrigin/uAssets#21380]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.st.com/en/microcontrollers-microprocessors/stm32u595-5a5/documentation.html`

### Category

breakage

### Description

Downloading documents from the ST website breaks, no documents are shown when ublock origin is enabled.

### Other extensions used

SponsorBlock, but that extension is not active on this website.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105181
 cosmetic: 44002
 scriptlet: 19289
 html: 1130
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36853-70, 30m
  ublock-badware: 7615-11, 30m
  ublock-privacy: 933-4, 30m
  ublock-unbreak: 2209-0, 30m
  ublock-quick-fixes: 93-2, 30m
  easylist: 75554-717, 30m
  easyprivacy: 33129-804, 30m
  urlhaus-1: 11195-0, 30m
  plowe-0: 3778-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3269 ms (selfie)
 maxAssetCacheWait: 55 ms
popupPanel:
 blocked: 18
 network:
  st.com: 2
  3gl.net: 1
  adobedtm.com: 8
  company-target.com: 1
  decibelinsight.net: 1
  demandbase.com: 1
  go-mpulse.net: 2
  licdn.com: 1
  marketo.net: 1
```
</details>

**Comment by okiehsch** [comment]
`||munchkin.marketo.net/munchkin.js$script,redirect-rule=noop.js,domain=st.com`
