### ISSUE TITLE
chip.de: breakage

### ISSUE THREAD

**Issue by ONE11111111ONE** [uBlockOrigin/uAssets#21382]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.chip.de/download/9232_Downloads/1/`

### Category

breakage

### Description

since today it doesn't show up when ublock is activated, i even tried reinstalling with default everything and even the new beta. still the same.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Chip_Screenshot](https://github.com/uBlockOrigin/uAssets/assets/150746073/bf541f0d-0ec0-49b2-993c-64d7d1b8685b)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 107547
 cosmetic: 48829
 scriptlet: 19285
 html: 1130
listset (total-discarded, last-updated):
 default:
  user-filters: 11-1, never
  ublock-filters: 36851-85, 8m
  ublock-badware: 7615-11, 8m
  ublock-privacy: 933-4, 8m
  ublock-unbreak: 2211-0, 8m
  ublock-quick-fixes: 92-2, 8m
  easylist: 75555-723, 8m
  easyprivacy: 33127-813, 8m
  urlhaus-1: 11195-0, 8m
  plowe-0: 3778-1, 8m
  DEU-0: 7216-3, 1m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 13 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 422 ms
 maxAssetCacheWait: 181 ms
popupPanel:
 blocked: 6
 network:
  chip.de: 2
  bf-ad.net: 1
  cleverpush.com: 1
  hotjar.com: 1
  iocnt.net: 1
 extended:
  ##.app_nexus_banners_common
  ##body.l-DownloadListing > div:not([class="fb"]) ul:has(> li a[h…
  ##:root:style(--topbanner-height-min:unset!important;--topbanner…
  ##+js(trusted-replace-node-text, script, pmactiveff !== 1, pmact…
  ##+js(trusted-replace-node-text, style, /a:hover\s{0\,}\{\sbackg…
  ##+js(json-prune, enabled, force_disabled)
  ##+js(trusted-replace-node-text, style, /\{\smin-height:\s.*\s\}…
  ##+js(trusted-replace-node-text, style, /\{\smin-height:.*!impor…
```
</details>

**Comment by ONE11111111ONE** [comment]
Works again with reinstalling newest beta, yet not with the official version, so people just need to wait i guess.

**Comment by okiehsch** [comment]
Caused by
````
chip.de##body.l-DownloadListing > div:not([class="fb"]) ul:has(> li a[href^="https://www.chip.de/downloads/"] img[src^="https://im.chip.de/"])
````
