### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by NoNameNeeded5** [uBlockOrigin/uAssets#21381]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.derstandard.at/`

### Category

detection

### Description

The website loads normally. After a few seconds the ad blocker is detected and the site is  no longer usable (everything is blocked by a "turn your adblocker off" banner)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 107581
 cosmetic: 48892
 scriptlet: 19285
 html: 1130
listset (total-discarded, last-updated):
 default:
  user-filters: 128-17, never
  ublock-filters: 36850-211, 17m
  ublock-badware: 7615-11, 17m
  ublock-privacy: 933-4, now
  ublock-unbreak: 2209-0, 17m
  ublock-quick-fixes: 92-2, 17m
  easylist: 75554-555, 17m
  easyprivacy: 33129-857, 17m
  urlhaus-1: 11195-0, 17m
  plowe-0: 3778-1, now
  DEU-0: 7216-3, 17m
filterset (user): [array of 128 redacted]
trustedset:
 added: [array of 7 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 prefetchingDisabled: false
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1815 ms (selfie)
 maxAssetCacheWait: 1086 ms
 unsuspendAfter: 161 ms
popupPanel:
 blocked: 42
 network:
  derstandard.at: 1
  adition.com: 3
  cleverpush.com: 1
  dailymotion.com: 6
  dm-event.net: 13
  doubleclick.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  iocnt.net: 2
  scorecardresearch.com: 3
  staticfiles.at: 2
  taboola.com: 1
  tinypass.com: 1
  twitter.com: 5
 extended:
  ##ad-container
```
</details>

**Comment by mapx-** [comment]
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.

**Comment by berndy2001** [comment]
I had the same issue today with Chrome. The anti-adblock message appeared after about 10 seconds.

The following helped me: Deactivate adblocker, reload website, activate adblocker and reload page.

**Comment by manuelsc** [comment]
You can use the following filter rules to bypass this
```
www.derstandard.at##.tp-modal
www.derstandard.at##.tp-active.tp-backdrop
www.derstandard.at##body:remove-class(tp-modal-open)

```

**Comment by mapx-** [comment]
@berndy2001 @NoNameNeeded5 do the filters above work for you ?

**Comment by kasi13** [comment]
Fix not working for me, can hide the overlay by adding `www.derstandard.at##.dialog-modal` but once the overlay tries to load all links cease to function

**Comment by mapx-** [comment]
use the element picker to find if there is some other overlay upon the page

**Comment by NoNameNeeded5** [comment]
Now it has changed:
With ublock on, the content of the article is removed shortly after loading it.
So the title of the article stays, the rest is removed about 5 seconds after successfully loading it.
