### ISSUE TITLE
sport-tv-guide.live: detection

### ISSUE THREAD

**Issue by IlyaFirsov** [uBlockOrigin/uAssets#21386]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://sport-tv-guide.live/`

### Category

detection

### Description

Same issue as #2770. An anti-adblock warning still appears, to fully load the list of events, you usually need to reload the page several times

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/26841983/9797f57e-9d48-45f2-a1bd-833989481d81)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 105189
 cosmetic: 44004
 scriptlet: 19480
 html: 0
listset (total-discarded, last-updated):
 removed:
  RUS-0: null
 default:
  user-filters: 0-0, never
  easylist: 75560-17, now
  easyprivacy: 33127-66, now
  plowe-0: 3778-1147, now
  ublock-badware: 7606-138, now
  ublock-filters: 35969-182, now
  ublock-privacy: 937-12, now
  ublock-quick-fixes: 91-14, now
  ublock-unbreak: 2163-31, now
  urlhaus-1: 11195-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 670 ms
 maxAssetCacheWait: 199 ms
popupPanel:
 blocked: 3
 network:
  criteo.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
Please just continue in the old thread. Don't open duplicated issues
