### ISSUE TITLE
wsj.com: breakage

### ISSUE THREAD

**Issue by davidcbryant** [uBlockOrigin/uAssets#21391]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wsj.com/finance?mod=nav_top_section`

### Category

breakage

### Description

I first noticed the problem today. This page used to display graphs of  the Dow Jones Industrial Average, the S&P 500, the NASDAQ 100, and the Russell 2000 in the top right quadrant . Starting today, those graphs appear briefly, then are blanked out. If I tuen Ublock Origin off, the graphs appear as expected.

I suspect that the web site has been re-designed to make a server at a different URL supply the graphical data, and that that remote URL is being blocked  by a filter, somehow.

### Other extensions used

DuckDuckGo, ClearURLs, and TorGuard (a VPN). The problem persists when I turn those extensions off.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 105078
 cosmetic: 43999
 scriptlet: 19284
 html: 1130
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36850-71, 35m
  ublock-badware: 7615-11, 35m
  ublock-privacy: 933-4, 35m
  ublock-unbreak: 2209-0, 35m
  easylist: 75554-717, 35m
  easyprivacy: 33127-804, 35m
  urlhaus-1: 11090-0, 1m
  plowe-0: 3778-1, 1m
  ublock-quick-fixes: 92-2, 35m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 254 ms (selfie)
 maxAssetCacheWait: 102 ms
popupPanel:
 blocked: 34
 network:
  wsj.com: 3
  ads-twitter.com: 2
  amazon-adsystem.com: 2
  bing.com: 1
  brandmetrics.com: 1
  d1z2jf7jlzjs58.cloudfront.net: 1
  datadome.co: 1
  demdex.net: 2
  dianomi.com: 1
  doubleclick.net: 1
  dowjoneson.com: 1
  facebook.net: 1
  gbqofs.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  licdn.com: 1
  ml314.com: 1
  moatads.com: 1
  newrelic.com: 2
  newscgp.com: 1
  outbrain.com: 2
  pinimg.com: 1
  redditstatic.com: 1
  sc-static.net: 1
  scorecardresearch.com: 2
  urbanairship.com: 1
 extended:
  ##div[id^="wrapper-AD_"]
  ##.uds-ad-container
  ##.adWrapper
  ##.staticAd
  ##.dianomi_context
  ##main div[class^="css-"] > .adWrapper:upward(1)
```
</details>

**Comment by huyszn** [comment]
Looks like it is caused by `wsj.com##main div[class^="css-"] > .adWrapper:upward(1)` in uBO filters.txt.
