### ISSUE TITLE
colonist.io: detection

### ISSUE THREAD

**Issue by rhiiiiiiiii** [uBlockOrigin/uAssets#21395]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://colonist.io/`

### Category

detection

### Description

Usually a pop up blocking access to play the game is removeable by disabling the reenabling ublock but theyve apparently gotten better at it because it does not work at all anymore. Stupid greedy site has so many ads it slows my comp to a crawl!

Thank you for all that you do!!!!

Here's the bit that I copied

uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105164
 cosmetic: 44013
 scriptlet: 19592
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75626-17, 5m
  easyprivacy: 33127-66, 5m
  plowe-0: 3778-1147, 5m
  ublock-badware: 7611-138, 5m
  ublock-filters: 36097-181, 5m
  ublock-privacy: 937-12, 5m
  ublock-quick-fixes: 113-38, 5m
  ublock-unbreak: 2165-31, 5m
  urlhaus-1: 11090-0, 5m
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1070 ms (selfie)
 maxAssetCacheWait: 262 ms
popupPanel:
 blocked: 13
 network:
  amazon-adsystem.com: 1
  doubleclick.net: 1
  googleoptimize.com: 1
  googletagmanager.com: 2
  jsdelivr.net: 1
  sentry.io: 3
  vlitag.com: 4

### Other extensions used

last pass 
capital one shopping
Onetab
marinara
Todoist
Keepa

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105164
 cosmetic: 44013
 scriptlet: 19592
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75626-17, 5m
  easyprivacy: 33127-66, 5m
  plowe-0: 3778-1147, 5m
  ublock-badware: 7611-138, 5m
  ublock-filters: 36097-181, 5m
  ublock-privacy: 937-12, 5m
  ublock-quick-fixes: 113-38, 5m
  ublock-unbreak: 2165-31, 5m
  urlhaus-1: 11090-0, 5m
filterset (user): [empty]
trustedset:
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1070 ms (selfie)
 maxAssetCacheWait: 262 ms
popupPanel:
 blocked: 13
 network:
  amazon-adsystem.com: 1
  doubleclick.net: 1
  googleoptimize.com: 1
  googletagmanager.com: 2
  jsdelivr.net: 1
  sentry.io: 3
  vlitag.com: 4
```
</details>

**Comment by JobcenterTycoon** [comment]
Duplicate https://github.com/uBlockOrigin/uAssets/issues/20649

**Comment by rhiiiiiiiii** [comment]
> Duplicate #20649

This is not a duplicate as they have now updated their detection so we have to turn off Ublock and we are forced to watch so many ads my comp bricks.
I am not the only one, it is being complained about on social media too for different ad blockers as well not working. 
Thank you.

**Comment by JobcenterTycoon** [comment]
The anti adblock is already known. You can write a comment in a old issue, no need to open a new issue for the same site every time. The contributer getting notified about new comments when they are involved already.

I tried now, i get no anti adblock even on a ranked 1vs1.

**Comment by rhiiiiiiiii** [comment]
Ah thank you! I didnt know that. I am new. Trying to learn!

Do you have different settings that I could implement? I play 1vs1 and
cannot get past the "this popup got an upgrade because we're greedy af"
popup without disabling ublock.
It used to go away with some disable/enable refresh etc magic but not
anymore.

Thank you regardless


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/14/23,
03:55:54 PM
