### ISSUE TITLE
anitube.ninja: nuisance The video play is interrupted

### ISSUE THREAD

**Issue by Theluga** [uBlockOrigin/uAssets#21399]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.anitube.ninja/967746/`

### Category

nuisance

### Description

The video player shows and can be played but in some seconds it's blocked by an image. You don't need to play it, it will also be blocked in some seconds.

### Other extensions used

decentraleyes, gnome shell extensions, popupoff, clearurls, sponsorblock.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 112740
 cosmetic: 154524
 scriptlet: 30676
 html: 1331
listset (total-discarded, last-updated):
 added:
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt: 1055-7, 1m
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1939-0, 1m
  https://www.i-dont-care-about-cookies.eu/abp/: 25816-19, 1m
  adguard-cookies: 28294-1676, 1m
  adguard-mobile-app-banners: 4841-1070, 1m
  adguard-other-annoyances: 14041-328, 1m
  fanboy-thirdparty_social: 68-0, 1m
  easylist-annoyances: 4243-108, 1m
  fanboy-cookiemonster: 49122-12038, 1m
  easylist-newsletters: 6726-14, 1m
  easylist-notifications: 2891-5, 1m
  [3 lists not shown]: [too many]
 default:
  user-filters: 51-1, never
  ublock-filters: 36977-387, now
  ublock-badware: 7615-11, now
  ublock-privacy: 933-5, now
  ublock-unbreak: 2211-0, now
  ublock-quick-fixes: 113-2, now
  easylist: 75626-774, now
  easyprivacy: 33127-894, 1m
  urlhaus-1: 11200-0, 1m
  plowe-0: 3778-2, 1m
filterset (user): [array of 51 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 21 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 508 ms (selfie)
 maxAssetCacheWait: 202 ms
popupPanel:
 blocked: 10
 network:
  googletagmanager.com: 2
  jwpltx.com: 1
  overpetleersia.com: 2
  translate.googleapis.com: 5
 extended:
  ##+js(abort-on-property-read, exoJsPop101)
  ##+js(set-constant, adBlockDetected, noopFunc)
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by huyszn** [comment]
`anitube.ninja##+js(aeld, DOMContentLoaded, btoa)`

**Comment by Theluga** [comment]
It works great! Thank you!

**Comment by D4niloMR** [comment]
You don't need to close the issue like this, wait for the filters to be on the list, then we will close.

**Comment by Theluga** [comment]
Sorry, I didn't know. I shall never do it again! Thank you!
