### ISSUE TITLE
mistergadget.tech: breakage

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#21396]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mistergadget.tech/139192/recensione-video-irobot-roomba-j9-unaltra-categoria/`

### Category

breakage

### Description

No video with default uBO filter lists setting

Ok enabling AdGuard – Ads because of [their fix](https://github.com/AdguardTeam/AdguardFilters/commit/82fe92e3a013a672ad036599ff0e7b4646de4af9).

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

 
<img width="1186" alt="no" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/501402f6-1ee5-479f-b6af-e9545cbe7948">

<img width="1098" alt="ok" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/38a5c87e-7545-4b54-8e62-c3c82b00d713">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 107131
 cosmetic: 50745
 scriptlet: 19395
 html: 1130
listset (total-discarded, last-updated):
 added:
  ITA-0: 8749-27, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 36977-231, now
  ublock-badware: 7615-138, now
  ublock-privacy: 933-4, now
  ublock-unbreak: 2211-11, now
  ublock-quick-fixes: 113-2, now
  easylist: 75626-22, now
  easyprivacy: 33127-847, now
  urlhaus-1: 11090-0, now
  plowe-0: 3778-389, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 932 ms
 maxAssetCacheWait: 404 ms
popupPanel:
 blocked: 470
 network:
  mistergadget.tech: 215
  amazon-adsystem.com: 2
  doubleclick.net: 1
  ezodn.com: 10
  ezoic.net: 225
  facebook.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  humix.com: 10
  imasdk.googleapis.com: 2
  pubmatic.com: 1
 extended:
  ###cellulari
  ##.wp-block-mister-gadget-amazon-list
  ##[data-ez-name]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ezoic-ad
  ##.adtester-container
  ##.ezoic-adpicker-ad
  ##ins.adsbygoogle
  ###ezmobfooter
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ###ez-sidebar-wall-left
  ##.ez-sidebar-wall-ad
  #@#[id^="div-gpt-ad"]
  ##.ez-video-wrap
  #@#.ad-unit
  #@#.banner-ads
  #@#.banner_ads
  #@#.ad-zone
  #@#.ad-space
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

```
humix.com#@#.ez-video-wrap
@@||humix.com/beardeddragon/iguana.js
@@||humix.com/beardeddragon/wyvern.js
@@||go.ezodn.com/beardeddragon/basilisk.js$domain=humix.com
@@||videosvc.ezoic.com/play?videoID=$domain=humix.com
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=humix.com|mistergadget.tech
```

for uBO I'll also
`||imasdk.googleapis.com/js/sdkloader/ima3.js$script,important,redirect=google-ima3,domain=humix.com|mistergadget.tech`
