### ISSUE TITLE
fmoviesz.to: breakage

### ISSUE THREAD

**Issue by Geyser182** [uBlockOrigin/uAssets#21398]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://fmoviesz.to/movie/taylor-swift-the-eras-tour-81kwv/1-1` 
`https://fmoviesz.to/movie/pencils-vs-pixels-2w980/1-1`

### Category

breakage

### Description

F-Movies' comments section part of the page displayed on its watch content pages are not displaying, and I am going to assume this may have to do with an error in cosmetic filtering for something else. The site itself works alright and everything pertaining to functions (e.g playing content, going to new episodic content) still works fine. 

Thank you uBO developers and indirect maintainers for making this extension work for me without much problems at all in the past 2 years and 2 months. It really has been a massive help lately. I am now doing some good work for other people by finding errors in sites I personally use myself, and sites that people may use that I don't find myself, and if I see errors on them, I will report them.

I am not experienced in code or programming but I hope the ensuring of the functionallity of this site is brought back to a few weeks ago. 

Also, in case I missed anything, the comments section is under the video, decription, and files section in the main document. I am typing this to make sure that nothing goes wrong. Thanks as always, uBlock Origin maintainers. I appreciate your stewardship. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (46)](https://github.com/uBlockOrigin/uAssets/assets/147728515/6eea7fab-142d-4262-adce-f016db3baac4)
![Screenshot (47)](https://github.com/uBlockOrigin/uAssets/assets/147728515/a0e7762c-24fa-4605-9f4f-b2f484bc2d16)
![Screenshot (48)](https://github.com/uBlockOrigin/uAssets/assets/147728515/f72aa47b-db33-4470-8e7d-90e411112897)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 266921
 cosmetic: 90830
 scriptlet: 37536
 html: 1130
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs for uBo/clear_urls_uboified.txt: 717-8, now
  adguard-generic: 81599-7216, now
  adguard-mobile: 8804-100, now
  adguard-spyware-url: 1357-142, now
  adguard-spyware: 80446-16891, now
  block-lan: 55-0, now
  curben-phishing: 78276-27, now
 default:
  user-filters: 54-0, never
  ublock-filters: 36977-107, now
  ublock-badware: 7615-11, now
  ublock-privacy: 933-25, now
  ublock-unbreak: 2211-1, now
  ublock-quick-fixes: 113-2, now
  easylist: 75626-802, now
  easyprivacy: 33127-811, now
  urlhaus-1: 11200-0, now
  plowe-0: 3778-1, now
filterset (user): [array of 54 redacted]
userSettings: [none]
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 2808 ms (selfie)
 maxAssetCacheWait: 1224 ms
popupPanel:
 blocked: 12
 network:
  amung.us: 1
  bidgear.com: 1
  bunnycdn.ru: 1
  disposalangrily.com: 2
  google.com: 4
  googletagmanager.com: 1
  sharethis.com: 2
 extended:
  ##div.aside-wrapper > aside.main:has(> div.text-center > a[rel="…
  ###placement-top
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by huyszn** [comment]
Caused by `fmoviesz.to#?#div.aside-wrapper > aside.main:has(> div.text-center > a[rel="nofollow"][target="_blank"])` in AdGuard – Mobile Ads

**Comment by gorhill** [comment]
Don't enable _AdGuard – Mobile Ads_ list on a desktop version of Firefox.
