### ISSUE TITLE
ads not blocked

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#214]
### URL(s) where the issue occurs

`http://www.businessinsider.in/Here-are-the-top-10-Business-Newsmakers-for-2016-according-to-Yahoo/articleshow/55724386.cms`

### Describe the issue

ads not blocked in this page as per screenshot shown as "promoted stories"

### Screenshot(s)

![screenshot 64](https://cloud.githubusercontent.com/assets/20338483/20801216/22390fe6-b80e-11e6-968d-e74b32cfd179.png)

### Versions

- Browser/version: google chrome Version 54.0.2840.99 m (64-bit)
- uBlock Origin version: 1.9.16

### Settings

- uBO's default settings+ antiadblock killer+adblock warning removal list+youtube pure video experience

**Comment by mapx-** [comment]
`businessinsider.in##STYLE[type="text/css"]:first-child + [class]`

**Comment by gorhill** [comment]
> `businessinsider.in##STYLE[type="text/css"]:first-child + [class]`

Works well, takes care of three Columbia containers on that page. This will be added to EasyList?

**Comment by mapx-** [comment]
if @ghajini reports the issue at easylist forum would be a chance ..
http://forums.lanik.us/

**Comment by ghajini** [comment]
I have no account on easylist @mapx- 
Please report there....

**Comment by gorhill** [comment]
@ghajini Since the filter works and uses standard ABP syntax, please report to EasyList maintainers: https://forums.lanik.us/viewforum.php?f=62

**Comment by mapx-** [comment]
done: https://forums.lanik.us/viewtopic.php?f=62&t=34338

**Comment by ghajini** [comment]
Thanx

**Comment by ghajini** [comment]
http://timesofindia.indiatimes.com/business/india-business/New-Rs-100-notes-from-RBI-soon-older-notes-to-continue/articleshow/55837782.cms
![screenshot 65](https://cloud.githubusercontent.com/assets/20338483/20932161/a89c40d2-bbf9-11e6-9291-f1ab81d886fc.png)

these ads are everywhere now
