### ISSUE TITLE
stagecoachbus.com: breakage

### ISSUE THREAD

**Issue by sam892** [uBlockOrigin/uAssets#21405]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.stagecoachbus.com/timetables`

### Category

breakage

### Description

The timetable search doesn't work: nothing happens when I click the search button.

Setting location doesn't work either.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105250
 cosmetic: 44012
 scriptlet: 19398
 html: 1130
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36980-94, 1h.27m
  ublock-badware: 7615-11, 1h.27m
  ublock-privacy: 933-4, 1h.27m
  ublock-unbreak: 2213-0, 1h.27m
  ublock-quick-fixes: 113-2, 1h.27m
  easylist: 75626-718, 1h.27m
  easyprivacy: 33113-805, 1h.27m
  urlhaus-1: 11200-0, 1h.27m
  plowe-0: 3780-1, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1034 ms (selfie)
 maxAssetCacheWait: 80 ms
popupPanel:
 blocked: 3
 network:
  addthis.com: 1
  googletagmanager.com: 1
  maps.googleapis.com: 1
```
</details>

**Comment by mapx-** [comment]
add

`@@||addthis.com/js/*/addthis_widget.js$script,domain=stagecoachbus.com`

@ryanbr
