### ISSUE TITLE
app.tvtime.com: breakage

### ISSUE THREAD

**Issue by Dominiquini** [uBlockOrigin/uAssets#21401]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.tvtime.com/?mode=auth`

### Category

breakage

### Description

Page don't load with uBlock enabled!

### Other extensions used

I have many, but the page loads when I disable uBlock!

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 288191
 cosmetic: 242747
 scriptlet: 49110
 html: 1331
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81599-7323, 4m
  adguard-mobile: 8804-17, 4m
  adguard-spyware-url: 1357-93, 4m
  block-lan: 55-0, 4m
  curben-phishing: 78276-30, 4m
  adguard-social: 22093-875, 4m
  fanboy-thirdparty_social: 68-0, 4m
  fanboy-cookiemonster: 49132-3871, 4m
  fanboy-social: 15986-24, 4m
  ublock-annoyances: 6129-698, 4m
  dpollock-0: 11613-494, 4m
  adguard-spyware: 80446-17070, 4m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36978-388, 4m
  ublock-badware: 7615-11, 4m
  ublock-privacy: 933-4, 4m
  ublock-unbreak: 2211-0, 4m
  ublock-quick-fixes: 113-2, 4m
  easylist: 75626-1013, 4m
  easyprivacy: 33113-981, 4m
  urlhaus-1: 11200-0, 4m
  plowe-0: 3778-84, 4m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6139 ms
 maxAssetCacheWait: 2787 ms
 unsuspendAfter: 2537 ms
popupPanel:
 blocked: 1
 network:
  facebook.net: 1
```
</details>

**Comment by peace2000** [comment]
The page loads fine to me despite I have uBO enabled.

**Comment by stephenhawk8054** [comment]
```yml
added:
  adguard-generic: 81599-7323, 4m
  adguard-mobile: 8804-17, 4m
  adguard-spyware-url: 1357-93, 4m
  block-lan: 55-0, 4m
  curben-phishing: 78276-30, 4m
  adguard-social: 22093-875, 4m
  fanboy-thirdparty_social: 68-0, 4m
  fanboy-cookiemonster: 49132-3871, 4m
  fanboy-social: 15986-24, 4m
  ublock-annoyances: 6129-698, 4m
  dpollock-0: 11613-494, 4m
  adguard-spyware: 80446-17070, 4m
  [11 lists not shown]: [too many]
```

Reset to default settings and test again
