### ISSUE TITLE
dhl.de: nuisance

### ISSUE THREAD

**Issue by B1ack3ye** [uBlockOrigin/uAssets#21403]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dhl.de/de/privatkunden/kundenkonto/willkommen.html`

### Category

nuisance

### Description

Cookie Notice on the website.

### Other extensions used

- Bitwarden 
	- `2023.12.0 | ID: jbkfoedolllekgbhcbcoahefnbanhhlh`
- Dark Reader 
	- `4.9.73 | ID: jbkfoedolllekgbhcbcoahefnbanhhlh`
- LanguageTool 
	- `8.3.2 | ID: hfjadhjooeceemgojogkhlppanjkbobc`
- Postman Interceptor 
	- `3.0.4 | ID: nbjbemmokmdpdokpnbfpdfbikmhgilmc`
- SimpleLogin:Receive & Send emails anonymously 
	- `2.10.2 | ID: diacfpipniklenphgljfkmhinphjlfff`
- SponsorBlock 
	- `5.4.28 | ID: mbmgnelfcpoecdepckhlhegpcehmpmji`
- Violentmonkey 
	- `2.16.0 | ID: eeagobfjdenkkddmbclomhiblgggliao`
- BlockTube 
	- `0.3.38 | ID: bbeaicapbccfllodepmimpkgecanonai`
- FrankerFaceZ 
	- `1.57 | ID: fadndhdgpmmaapbmfcknlfgcflmmmieb`
- Gumbo 
	- `1.18.6 | ID: aalmjfpohaedoddkobnibokclgeefamn`
- OpenAI Translator 
	- `0.2.12 | ID: ogjibjphoadhljaoicdnjnmgokohngcc`
- Refined GitHub 
	- `23.12.1 | ID: hlepfoohegkhhmjieoechaddaejaokhf`
- Return YouTube Dislike 
	- `3.0.0.14 | ID: gebbhagfogifgggkldgodflihgfeippi`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63259739/016a548f-5e48-4e57-9479-12d0d85c7dcd)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 114369
 cosmetic: 121754
 scriptlet: 27152
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2508-1, now
  easylist-annoyances: 4244-33, now
  easylist-chat: 168-0, now
  easylist-newsletters: 6728-15, now
  easylist-notifications: 2891-86, now
  fanboy-cookiemonster: 49132-222, now
  fanboy-social: 15986-13, now
  ublock-annoyances: 6176-79, now
  ublock-cookies-easylist: 663-663, now
 default:
  user-filters: 2-0, never
  DEU-0: 7216-0, now
  easylist: 75626-23, now
  easyprivacy: 33113-161, now
  plowe-0: 3778-1148, now
  ublock-badware: 7611-138, now
  ublock-filters: 36100-215, now
  ublock-privacy: 937-62, now
  ublock-quick-fixes: 113-38, now
  ublock-unbreak: 2167-37, now
  urlhaus-1: 11200-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 303 ms (selfie)
 maxAssetCacheWait: 162 ms
popupPanel:
 blocked: 6
 network:
  dhl.de: 2
  adobedtm.com: 4
 extended:
  ##.onetrust-pc-dark-filter
  #@##onetrust-banner-sdk
  #@##onetrust-consent-sdk
```
</details>

**Comment by mapx-** [comment]
add

`||cdn.cookielaw.org/scripttemplates/otSDKStub.js$script,domain=dhl.de`


@ryanbr
