### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by g0r3** [uBlockOrigin/uAssets#21404]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.derstandard.at`

### Category

detection

### Description

If you wait 10 or so seconds, a full screen popup will appear, and ask you to disable the adblocker. Usually these themselves can be blocked. But this somehow also blocks the UI of Ublock Origin.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105267
 cosmetic: 44054
 scriptlet: 19595
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 49-2, never
  easylist: 75626-17, 28m
  easyprivacy: 33113-66, 28m
  plowe-0: 3778-1147, now
  ublock-badware: 7611-138, 28m
  ublock-filters: 36100-181, 28m
  ublock-privacy: 937-12, 28m
  ublock-quick-fixes: 113-38, 28m
  ublock-unbreak: 2167-31, 28m
  urlhaus-1: 11200-0, now
filterset (user): [array of 50 redacted]
trustedset:
 added: [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 658 ms (selfie)
 maxAssetCacheWait: 328 ms
popupPanel:
 blocked: 12
 no-popups: true
 network:
  derstandard.at: 1
  adition.com: 3
  cleverpush.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  sentry.io: 2
  staticfiles.at: 2
  taboola.com: 1
 extended:
  ###ad-container-4
  ##ad-container
  ##body:remove-class(tp-modal-open)
```
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/21381

**Comment by mapx-** [comment]
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
