### ISSUE TITLE
SimpleFlying.com with Admiral detection running

### ISSUE THREAD

**Issue by BirdmanRS** [uBlockOrigin/uAssets#21400]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://simpleflying.com

### Description

Admiral adblock detection is working on this site

Doesn't seem to pop up until you click on an article most times.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Admiral_SimpleFlying_dot_com](https://github.com/uBlockOrigin/uAssets/assets/34692344/507a7ead-66d8-4e57-95b5-f5522e8d60d0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 183521
 cosmetic: 44013
 scriptlet: 19592
 html: 0
listset (total-discarded, last-updated):
 added:
  curben-phishing: 78276-20, 2m
 default:
  user-filters: 0-0, never
  easylist: 75626-18, 2m
  easyprivacy: 33127-66, 2m
  plowe-0: 3778-1147, 2m
  ublock-badware: 7611-145, 2m
  ublock-filters: 36097-181, 2m
  ublock-privacy: 937-12, 2m
  ublock-quick-fixes: 113-38, 2m
  ublock-unbreak: 2165-31, 2m
  urlhaus-1: 11200-0, 2m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3298 ms
 maxAssetCacheWait: 1699 ms
```
</details>

**Comment by huyszn** [comment]
Site is detecting again. "Something went wrong. Please disable your blocker on SimpleFlying.com"
