### ISSUE TITLE
ilrestodelcarlino.it: breakage

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#21412]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.ilrestodelcarlino.it/video/aeroporto-bologna-piano-di-investimenti-da-216-milioni-in-5-anni-hr8muxqm`

### Category

breakage

### Description

`#pubtech-cmp` hidden by AG Cookie list, but you don't need it, just add
`ilrestodelcarlino.it##+js(trusted-click-element, #pubtech-cmp #pt-close)`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1140" alt="no" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/bee8cd56-b7be-4d39-b82a-c44899158d12">
<img width="1089" alt="ok" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/b387a5c1-25d2-4887-ad6c-de785af7cd8d">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 132975
 cosmetic: 176714
 scriptlet: 45242
 html: 1333
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81253-5874, 4m
  adguard-social: 22100-169, 3m
  adguard-cookies: 28296-46, 4m
  ublock-cookies-adguard: 666-0, 4m
  adguard-popup-overlays: 26613-1037, 3m
  adguard-mobile-app-banners: 4842-9, 3m
  adguard-other-annoyances: 14044-66, 3m
  adguard-widgets: 2361-1, 3m
  ublock-annoyances: 6142-685, 4m
  ITA-0: 8634-22, 4m
 default:
  user-filters: 0-0, never
  ublock-filters: 37027-380, 4m
  ublock-badware: 7615-11, 4m
  ublock-privacy: 945-4, 4m
  ublock-unbreak: 2213-0, 4m
  ublock-quick-fixes: 107-2, 4m
  easylist: 75650-784, 4m
  easyprivacy: 33126-812, 4m
  urlhaus-1: 11070-0, 4m
  plowe-0: 3780-1, 4m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 1385 ms
 maxAssetCacheWait: 878 ms
popupPanel:
 blocked: 14
 network:
  cloudflareinsights.com: 1
  cxense.com: 1
  doubleclick.net: 1
  google.com: 3
  googletagmanager.com: 2
  imrworldwide.com: 2
  k5a.io: 1
  piano.io: 1
  taboola.com: 1
  talkscreativity.com: 1
 extended:
  ##div[class^="Ad_"]
  ##div[class^="ads_"]
  ##div[style^="min-height: 250px;"]
  ##div[class^="SocialShare_"]
  ###pubtech-cmp
  ##div[class^="Newsletter_newsletter__"]
  ##a[href^="https://web.whatsapp.com/send?text="]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ###credential_picker_container
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(abort-current-script, EventTarget.prototype.addEventListen…
```
</details>

**Comment by mapx-** [comment]
@ryanbr 

`@@||cmp.pubtech.ai/*/pubtech-cmp-v2.js$script,from=ilrestodelcarlino.it`

@Alex-302

`ilrestodelcarlino.it##+js(trusted-click-element, #pubtech-cmp #pt-close)`

**Comment by superlex** [comment]
@mapx- @Alex-302
It's due to
```
chimica-online.it,liberoquotidiano.it,ilrestodelcarlino.it,iltempo.it,ilgiorno.it#$#html > body:not(#style_important) { overflow: auto !important; }
chimica-online.it,liberoquotidiano.it,ilrestodelcarlino.it,iltempo.it,ilgiorno.it#$##pubtech-cmp { display: none !important; }
```
They don't have issues because where it's hidden they use `trusted-click-element`, however they could be removed anyway:

```
chimica-online.it,liberoquotidiano.it,iltempo.it#$#html > body:not(#style_important) { overflow: auto !important; }
chimica-online.it,liberoquotidiano.it,iltempo.it#$##pubtech-cmp { display: none !important; }
```

**Comment by Alex-302** [comment]
Removed bad rules.
