### ISSUE TITLE
firstonetv.net [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#2141]
URL(s) where the issue occurs

`https://www.firstonetv.net/Live/Spain/Antena-3-30`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 65.0.3325.181 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.16.2

Settings

Default

**Comment by gorhill** [comment]
Removing the filter `||firstonetv.net/src/*$xmlhttprequest,first-party,important` (added in #1812) seems to get rid of the anti-blocker, however on my side the video doesn't seem to be able to play.

**Comment by zaphodbeebblebrox** [comment]
I can get it to work if I ad that filter and allow flash player on that site.

**Comment by gorhill** [comment]
Actually I can get it to play if I click the viewer.

**Comment by gorhill** [comment]
Re-opening, I would like to know what @okiehsch thinks of the issue here.

**Comment by okiehsch** [comment]
I can't get the video to work on my end, it starts loading and then I get the "Please enable Flash Player" message.

I am not sure what you mean by "clicking the viewer". If I click the video player before the Flash message appears nothing happens.
That video player does play video ads via html5 on my end, if I allow a few requests, but after the ad I again get the "Please enable Flash Player" message.

**Comment by okiehsch** [comment]
`||firstonetv.net/ucount.php$xmlhttprequest,first-party,important` can probably also be removed.
I can see no such requests on my end.
@zaphodbeebblebrox can you play the video without issue, if you also add
`||firstonetv.net/ucount.php$xmlhttprequest,first-party,important,badfilter`

**Comment by zaphodbeebblebrox** [comment]
I can get it to play without issue.

**Comment by gorhill** [comment]
> I can't get the video to work on my end, it starts loading and then I get the "Please enable Flash Player" message.

I got this until I realized I had Flash objects blocked by default in the browser. Allowing Flash I just needed to click on the player to get it to start playing.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://www.firstonetv.net/Live/Vietnam/VTV3-3`
