### ISSUE TITLE
tubitv.com: detection

### ISSUE THREAD

**Issue by liefygreen** [uBlockOrigin/uAssets#21414]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tubitv.com/tv-shows/380963/s01-e09-excalibur`

### Category

detection

### Description

When I go to watch an episode, Tubi detects that I have an ad blocker. It wasn't picking it up at all yesterday. I haven't actually touched my uBlock settings or anything since I installed the extension before this point so I don't think it was anything I did on my end. 

### Other extensions used

I was initially also using ad block plus on top of uBlock. Then I turned that off and still had the issue with Tubi detecting that I had an ad blocker. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105181
 cosmetic: 44056
 scriptlet: 19602
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 8m
 default:
  user-filters: 3-0, never
  easylist: 75650-17, 1m
  easyprivacy: 33126-66, 1m
  plowe-0: 3780-1150, 1m
  ublock-badware: 7616-138, 1m
  ublock-filters: 36146-181, 1m
  ublock-privacy: 949-12, 1m
  ublock-quick-fixes: 107-34, 1m
  ublock-unbreak: 2167-31, 1m
  urlhaus-1: 11070-0, 1m
filterset (user): [array of 3 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 577 ms (selfie)
 maxAssetCacheWait: 176 ms
popupPanel:
 blocked: 31
 network:
  tubitv.com: 7
  google.com: 1
  googletagmanager.com: 1
  sentry.io: 4
  tubi.io: 18
 extended:
  ##+js(set-constant, blockAdBlock, noopFunc)
```
</details>

**Comment by D4niloMR** [comment]
@liefygreen test:

`tubitv.com#@#+js(set, blockAdBlock, noopFunc)`

**Comment by jordansworld** [comment]
seems like *.mp4$media, redirect=noopmp3-0.1s,domain=tubitv.co prevents videos from loading. is it just me?

**Comment by stephenhawk8054** [comment]
Test again in Firefox mobile.

**Comment by jordansworld** [comment]
ok so it seems like it doesnt trigger it every time. but i think it its a bad filter as it does still stop some videos from playing

**Comment by stephenhawk8054** [comment]
Please copy your troubleshooting information while reproducing the issue.

**Comment by jordansworld** [comment]
ok so i figured out why its breaking videos. that filter is blocking legit video files. example:

https://akamai.tubi.video/7aaa76a9-6860-491f-a1f9-c7da714f14ce/9jfn7s1j.mp4

**Comment by godslayer86** [comment]
tubi is showing ad breaks for me starting today. not sure if they updated their anti ad blockers

**Comment by stephenhawk8054** [comment]
Are you signing in to the page? Where does the ads appear: at the start, in the middle or at the end?

**Comment by godslayer86** [comment]
im not signed in to tubi (i dont have an account on there actually) the ads appear 2 times in the middle of the show im watching but not at the start. i refreshed and restarted firefox and the ad breaks still appear

**Comment by stephenhawk8054** [comment]
@godslayer86 Can you give exact link where you see the ads and at which timestamps do you see it?

**Comment by DarkAlchy** [comment]
I just got hit with my first ad on Tubi ever, so something changed.

**Comment by stephenhawk8054** [comment]
@DarkAlchy https://github.com/uBlockOrigin/uAssets/issues/21414#issuecomment-2576538280

**Comment by godslayer86** [comment]
I cant find where the first ad break had happened for me but the second one is at 17:15. However the ad break doesnt happen if i skip directly to or past the timestamp, it only happens when im letting the video play. This is where I'm experiencing the ads, I haven't tried on anything else yet. https://tubitv.com/tv-shows/200029871/s07-e16-the-ambassadors-of-death-pt-5

**Comment by stephenhawk8054** [comment]
@godslayer86 Can you test this filter:

```adb
.mp4$media,redirect=noopmp3-0.1s,domain=tubitv.com
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

**Comment by godslayer86** [comment]
Thank you, this actually fixed it for me for now.

**Comment by DarkAlchy** [comment]
> @DarkAlchy [#21414 (comment)](https://github.com/uBlockOrigin/uAssets/issues/21414#issuecomment-2576538280)

Zulu Dawn and the ad is for a tax service.   https://tubitv.com/movies/493025/zulu-dawn

**Comment by jordansworld** [comment]
how do you guys get the videos to play with the mp4 filter. i have to do $badfilter in order for videos to play
