### ISSUE TITLE
listenwise.com: breakage

### ISSUE THREAD

**Issue by escarlson** [uBlockOrigin/uAssets#21416]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://app.listenwise.com/students/events/632-debate-textbooks-vs-tablets`

### Description

listenwise.com is a site that offers listening assessments and lessons in the education market. When going to [a page for a story](https://app.listenwise.com/students/events/632-debate-textbooks-vs-tablets), an audio player error displays and the browser console shows uBlock blocking that lesson's MP3 file. Those MP3 files are hosted on `d29npqx9an5xu5.cloudfront.net`. It seems the direct URLs for th MP3 files expire, but you should be able to see a current one in the browser console. When opening that MP3 in a new tab, it only loads after disabling uBlock.

### Other extensions used

- Adobe Acrobat
- Bitwarden
- Clever Plus
- React Developer Tools
- WAVE Evaluation Tool
- Mirroring 360
- Silktide Browser Extension
- Chrome Remote Desktop
- Chromebook Recovery Utility
- Google Docs Quick Create
- Keep Awake
- Gopher Buddy

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2560" alt="Screenshot 2023-12-14 at 15 19 28" src="https://github.com/uBlockOrigin/uAssets/assets/10640906/634ada11-f5d6-49f6-bb3e-8e74b47f70a2">

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105185
 cosmetic: 44059
 scriptlet: 19603
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 75652-17, 3m
  easyprivacy: 33130-66, 3m
  plowe-0: 3780-1150, 3m
  ublock-badware: 7616-138, 3m
  ublock-filters: 36150-181, 3m
  ublock-privacy: 949-12, 3m
  ublock-quick-fixes: 107-34, 3m
  ublock-unbreak: 2167-31, 3m
  urlhaus-1: 11070-0, 3m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 834 ms (selfie)
 maxAssetCacheWait: 72 ms
```
</details>

**Comment by stephenhawk8054** [comment]
```adb
||cloudfront.net/events$badfilter
||cloudfront.net/events$~media
```

@ryanbr
