### ISSUE TITLE
ygosu.com: ads

### ISSUE THREAD

**Issue by aaswqwdqssd** [uBlockOrigin/uAssets#21425]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://ygosu.com/`

### Category

ads

### Description

Ad blocking is not possible on this site.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107368
 cosmetic: 47453
 scriptlet: 19769
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 11-0, never
  KOR-1: 4897-10, 49m
  easylist: 75669-60, now
  easyprivacy: 33111-76, now
  plowe-0: 3780-1164, now
  ublock-badware: 7619-138, now
  ublock-filters: 36163-185, now
  ublock-privacy: 949-14, now
  ublock-quick-fixes: 116-34, now
  ublock-unbreak: 2168-31, now
  urlhaus-1: 11965-0, now
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 509 ms (selfie)
 maxAssetCacheWait: 114 ms
popupPanel:
 blocked: 17
 network:
  07c225f3.online: 9
  coupang.com: 2
  criteo.net: 1
  google.com: 1
  googletagmanager.com: 3
  vntsm.com: 1
 extended:
  ###contain > div[style*="margin-bottom:"]
  ##+js(no-xhr-if, /static\.criteo\.net|adsbygoogle/)
  ##+js(no-fetch-if, /static\.criteo\.net|adsbygoogle/)
  ##+js(set-local-storage-item, adshield-analytics-uuid, $remove$)
  ##+js(set-local-storage-item, as_profile_cache, $remove$)
  ##+js(set-local-storage-item, as_accetpable_ads_blocked_cache, $…
  ##+js(set-local-storage-item, as_adblock_cache, $remove$)
```
</details>

**Comment by aaswqwdqssd** [comment]
![3](https://github.com/uBlockOrigin/uAssets/assets/151713582/8a9a5414-0594-4619-9059-cfb8e37ae3ae)
solved by adding this to my filter.

**Comment by JobcenterTycoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/21385

**Comment by JobcenterTycoon** [comment]
These ads are hard to block because they are protected by "Ad-Shield", for the best blocking results try this https://github.com/List-KR/microShield

**Comment by aaswqwdqssd** [comment]
> These ads are hard to block because they are protected by "Ad-Shield", for the best blocking results try this https://github.com/List-KR/microShield

microShield don't work. (The site is broken - picture below)
**uBlock Origin is our only hope.**

![4](https://github.com/uBlockOrigin/uAssets/assets/151713582/e6a751cc-1603-46e4-baff-62e6422486a0)
