### ISSUE TITLE
uploadrar.com: ads

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#21434]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://uploadrar.com/16z4yuvuitri`

### Category

ads

### Description

empty ad placeholder

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.1b9
Chromium Mobile: 110
filterset (summary):
 network: 114243
 cosmetic: 138407
 scriptlet: 28271
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-cookies: 28247-30, now
  adguard-mobile-app-banners: 4846-9, now
  adguard-other-annoyances: 14054-9, now
  adguard-popup-overlays: 26617-76, now
  adguard-social: 22098-925, now
  adguard-widgets: 2368-4, now
  ublock-annoyances: 6291-170, now
  ublock-cookies-adguard: 742-742, now
 default:
  adguard-mobile: 8821-16, now
  easylist: 75689-127, now
  easyprivacy: 33117-142, now
  plowe-0: 3781-1227, now
  ublock-badware: 7613-139, now
  ublock-filters: 36488-578, now
  ublock-privacy: 949-13, now
  ublock-quick-fixes: 112-11, now
  ublock-unbreak: 2173-35, now
  urlhaus-1: 11315-0, now
filterset (user): [array of 32 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2236 ms (selfie)
 maxAssetCacheWait: 407 ms
popupPanel:
 blocked: 11
 network:
  uploadrar.com: 1
  bmcdn6.com: 3
  freeprivacypolicy.com: 1
  github.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  mediapalmtree.com: 1
  pyxiscablese.com: 1
  saltateblit.com: 1
 extended:
  ##[class^="banner"]:not(:has(#commonId))
  ###gdpr-cookie-notice
  ##.socialmedia
  ##+js(adjust-setTimeout, tick, 1000)
  ##+js(abort-current-script, eval, replace)
  ##+js(nobab)
  ##+js(abort-current-script, Math, _0x)
  ##+js(abort-on-property-read, popns)
  ##+js(abort-current-script, parseInt, break;case $.)
```
</details>

**Comment by mapx-** [comment]
do not report such "issues", use element picker on your side

**Comment by Fatcavill** [comment]
can i report fake download button and timer not bypass for this site?

**Comment by Fatcavill** [comment]
sorry i am confused so i should not report such issue ?

**Comment by ItsProfessional** [comment]
> sorry i am confused so i should not report such issue ?

@Fatcavill Create **[discussions](https://github.com/uBlockOrigin/uAssets/discussions/new?category=q-a)**, instead of commenting here. You may be provided with a custom filter to add in your "My filters" page, since issues like fake download buttons aren't consider in the lists, as far as I know. About the timer not being bypassed, I'm pretty sure they have a server sided check, which fundamentally can't be bypassed.

> ok you report, we will connect to concerned filter list authors

@ghajini What do you mean? You mean regional list authors? Why?
