### ISSUE TITLE
tech.hipsonyc.com: nuisance

### ISSUE THREAD

**Issue by Fatcavill** [uBlockOrigin/uAssets#21430]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tech.hipsonyc.com/`

### Category

nuisance

### Description

`https://tech.hipsonyc.com/?token=e2dGX9Go`
there is timer,ads placeholder,popup

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.1b9
Chromium Mobile: 110
filterset (summary):
 network: 114893
 cosmetic: 138406
 scriptlet: 28270
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-cookies: 28247-30, now
  adguard-mobile-app-banners: 4846-9, now
  adguard-other-annoyances: 14054-9, now
  adguard-popup-overlays: 26617-76, now
  adguard-social: 22098-925, now
  adguard-widgets: 2368-4, now
  ublock-annoyances: 6291-170, now
  ublock-cookies-adguard: 742-742, now
 default:
  adguard-mobile: 8821-16, now
  easylist: 75688-127, now
  easyprivacy: 33116-142, now
  plowe-0: 3781-1227, now
  ublock-badware: 7613-139, now
  ublock-filters: 36488-578, now
  ublock-privacy: 949-13, now
  ublock-quick-fixes: 112-11, now
  ublock-unbreak: 2173-35, now
  urlhaus-1: 11965-0, now
filterset (user): [array of 32 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1881 ms (selfie)
 maxAssetCacheWait: 362 ms
popupPanel:
 blocked: 5
 network:
  clarity.ms: 1
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  jsdelivr.net: 1
 extended:
  ##.close-sticky-ad
  ###footer-sticky-ad
  ##+js(trusted-replace-node-text, script, /^window\.location\.hre…
  ##+js(adjust-setInterval, countDown)
  ##+js(no-xhr-if, adsbygoogle)
```
</details>

**Comment by mapx-** [comment]
I addressed - desktop side - the popup, idk if is working for chromium mobile.

ads PH for such crap pages ?

**Comment by BlazeFTL** [comment]
popup gone..but at least timers can be bypassed ?

**Comment by D4niloMR** [comment]
This site is so bloated that is annoying... removed all useless things

**Comment by BlazeFTL** [comment]
Can Anybody Tell Me What gms means https://github.com/uBlockOrigin/uAssets/commit/c342d68fc8579854f193e12370d683fda3de5160 Here ?...I Saw It Getting Used In Replace Too But Couldn't Find Any Documentation...

Also Timer Boost Doesn't Work In FF In This Site

**Comment by BlazeFTL** [comment]
Thanks...I Got Half Of It..I Guess...G Global,M Multi Line,S Single Line😁
