### ISSUE TITLE
overgal.com: detection

### ISSUE THREAD

**Issue by Paced6450** [uBlockOrigin/uAssets#21436]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://br.encurtandourl.com/fMPUTgh`

### Category

detection

### Description

Site detects adblock. can't be used until i turn off ublock

### Other extensions used

bitwarden, 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 189051
 cosmetic: 65387
 scriptlet: 21488
 html: 1194
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2510-1, now
  adguard-spyware-url: 1360-200, now
  adguard-spyware: 80469-16945, now
  RUS-0: 40073-130, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37029-63, now
  ublock-badware: 7623-11, now
  ublock-privacy: 945-52, now
  ublock-unbreak: 2214-1, now
  ublock-quick-fixes: 111-2, 10m
  easylist: 75698-743, now
  easyprivacy: 33117-809, now
  urlhaus-1: 11315-0, now
  plowe-0: 3781-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2234 ms (selfie)
 maxAssetCacheWait: 277 ms
popupPanel:
 blocked: 6
 network:
  demand.supply: 2
  googlesyndication.com: 2
  googletagmanager.com: 1
  quantcast.com: 1
 extended:
  ##.banner-728x90
  ##.myTestAd
  ###ad_728:not([style^="position: absolute; left: -5000px"])
  ###ad_rect
  ###ads-panel
  ###ads_body_3
  ###amazon_ad
  ###bigadspot
  #@##ad_728
```
</details>

**Comment by mapx-** [comment]
Did you visit directly that page or did you land on it from another page ? (shortener ?)

**Comment by Paced6450** [comment]
visit from another page

**Comment by mapx-** [comment]
go on, which one ? exact link

**Comment by Paced6450** [comment]
https://br.encurtandourl.com/fMPUTgh
