### ISSUE TITLE
accuweather.com breakage

### ISSUE THREAD

**Issue by UserPizza** [uBlockOrigin/uAssets#21432]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.accuweather.com/en/videos`

### Description

the videos no load

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107962
 cosmetic: 50396
 scriptlet: 19990
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75688-17, 4m
  easyprivacy: 33116-66, 4m
  plowe-0: 3781-1151, 4m
  spa-0: 3775-20, 4m
  spa-1: 5684-210, 4m
  ublock-badware: 7619-138, 4m
  ublock-filters: 36149-204, 4m
  ublock-privacy: 949-12, 4m
  ublock-quick-fixes: 111-7, 4m
  ublock-unbreak: 2168-33, 4m
  urlhaus-1: 11315-0, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 375 ms (selfie)
 maxAssetCacheWait: 103 ms

```
</details>

**Comment by UserPizza** [comment]
hey.. why i recibed a email after public this post? something "Startup failure" in youtube issue i dont know what is that

**Comment by huyszn** [comment]
Seems to be caused by `##.cnx-player-wrapper` in EasyList

**Comment by UserPizza** [comment]
again breakage and other different site whit samme issue

```
https://www.accuweather.com/en/videos
https://deadline.com/video/america-ferrera-barbie-video-interview-oscars/
```
