### ISSUE TITLE
allocine.fr: breakage

### ISSUE THREAD

**Issue by momala454** [uBlockOrigin/uAssets#21439]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.allocine.fr/article/fichearticle_gen_carticle=1000056029.html`

### Category

breakage

### Description

The quiz is not working

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 120
filterset (summary):
 network: 130200
 cosmetic: 133859
 scriptlet: 27015
 html: 1345
listset (total-discarded, last-updated):
 added:
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95062-65463, 2m
  fanboy-cookiemonster: 49096-225, 2m
  ublock-annoyances: 6301-15, 2m
 default:
  user-filters: 301-28, never
  ublock-filters: 37534-275, 2m
  ublock-badware: 7617-11, 2m
  ublock-privacy: 945-5, 2m
  ublock-unbreak: 2219-0, 2m
  adguard-mobile: 8918-19, 2m
  easylist: 75699-857, 2m
  easyprivacy: 33117-816, 2m
  urlhaus-1: 11305-0, 2m
  plowe-0: 3781-86, 2m
  FRA-0: 28852-417, 2m
  ublock-quick-fixes: 105-0, 2m
filterset (user): [array of 308 redacted]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 2 redacted]
urlRuleset:
 added: [array of 2 redacted]
userSettings:
 cloudStorageEnabled: true
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6131 ms (selfie)
 maxAssetCacheWait: 417 ms
popupPanel:
 blocked: 7
 network:
  criteo.net: 1
  google-analytics.com: 1
  googlesyndication.com: 3
  newsroom.bi: 1
  riddle.com: 1
 extended:
  ###dfp-interstitial
  ##.ad-interstitial
  ##.ad-item
  ###dfp-masthead
  ##.ad-masthead
  ##.js-share-btn
  ##.OUTBRAIN
  ##.sticky-ad-holder
  ###dfp-atf
  ##.ad-atf
  ###dfp-mtf
  ###dfp-btf
  ##.ad-footer
  ##.icon-holder-social
  ##.icon-social-facebook-circle
  ##.icon-social-twitter-circle
  ##.icon-social-instagram-circle
  ##.icon-social-mail-circle
  ###back-top
  ##.back-top
  ##.ad-item.ad-atf.js-atf
  ##.js-sticky-atf.sticky-atf.sticky-ad-holder
  ##.ad-item.ad-mtf.js-mtf
  ##.main-banner
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##body,html:style(overflow: visible !important; padding-right: 0…
  #@##didomi-host
  ##+js(set-constant, AC.config.ads, {})
```
</details>

**Comment by momala454** [comment]
![Screenshot_2023-12-16-17-45-15-270_org mozilla firefox](https://github.com/uBlockOrigin/uAssets/assets/83005/412932c2-6861-4fa2-9f07-876e78adc82a)

**Comment by mapx-** [comment]
add

`@@||riddle.com/embed/$frame,domain=allocine.fr`


@ryanbr  FA issue
