### ISSUE TITLE
resetoff.pl: nuisance/ads

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#21437]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

Example video link:
`https://resetoff.pl/vid/a1w1sz` (video loaded into iframe)
`https://resetoff.pl/embed/video/a1w1sz` (alternatively video loaded as standalone)

### Description

**Problem :** 

The site intentionally hides the video player controls at the bottom of the video and makes video dimmed/darkened and uncontrollable until all timer ads (2x 25s=50s) are viewed and dissappear on it's own or are manually closed by an user, this is considered to be an annoyance to an user if he needs to wait 50sec to be able to control video and to darken/dimmed disappear, because in POL regional list the timer ads are hidden by a cosmetic filter, and only advanced users know how to unhide them and  close manually, which still is an annoyance.

**Steps to reproduce :**

1. Add temporarily `~resetoff.pl##[id$="reklamy"]:not(h1):not(h2):not(h3):not(h4):not(h5):not(h6):not(b):not(strong)` 
to disable a filter from regional POL ad list, what is required to present the problem visually or disable cosmetic filtering using a switch in uBO's Popup pane
2. Visit the first video link
3. Fill the Captcha if required
4. Notice that only big Play button is visible in the middle of the video 
5. Notice that the video player controls at the bottom of the video are intentionally hidden by the site : [SCREENSHOOT 1](https://github.com/uBlockOrigin/uAssets/assets/72945564/11db3ad3-e7e7-4dea-8281-4ce59dbce435) (on the alternative video link, they are visible but still broken/not fully functional) and the video is dimmed/darkened
6. Press big Play button to play video
7. Notice that the video is playing
8. Notice that a timer ad (Nr 1)  appears with 25s clock
9. Let the time pass or click "X" button to close the ad Nr 1
10. Notice that another timer ad (Nr 2)  appears with 25s clock
11. Let the time pass or click "X" button to close the ad Nr 2
12. Notice the video player controls at the bottom of the video are unhidden : [SCREENSHOOT 2](https://github.com/uBlockOrigin/uAssets/assets/72945564/74c93b14-7892-4edd-8a8d-1635185f6978) and the video is undimmed/undarkened.

**Solutions :** 

I was trying to boost the ad timers by using the following scriplets but it didn't work (maybe because it's a server side timer): 
 - https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#nano-settimeout-boosterjs- and / or
 - https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#nano-setinterval-boosterjs-

Then I was trying to close ads by this scriplet but the ads didn't disappear:
 - https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#trusted-click-elementjs-

`resetoff.pl##+js(trusted-click-element, '#btn-reklama-content-1, #btn-reklama-content-2')`
`resetoff.pl##+js(trusted-click-element, '#btn-reklama-content-1, #btn-reklama-content-2', , 1000)`
`resetoff.pl##+js(trusted-click-element, '#btn-reklama-content-1, #btn-reklama-content-2', , 3000)`
`resetoff.pl##+js(trusted-click-element, '#btn-reklama-content-1, #btn-reklama-content-2', , 5000)`
 
Then I separated them but still the ads didn't disappear:
`resetoff.pl##+js(trusted-click-element, #btn-reklama-content-1)`
`resetoff.pl##+js(trusted-click-element, #btn-reklama-content-2)`

This works partially: only if an user clicks Play button & and video begins playing within 5 sec, which is not always the case:
`resetoff.pl##+js(trusted-click-element, #btn-reklama-content-1, , 5000)`
`resetoff.pl##+js(trusted-click-element, #btn-reklama-content-2, , 5000)`

It seems it's another real case to improve `trusted-click-element` scriplet, as already requested by someone else :
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2745#discussioncomment-7330902

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
Firefox/Opera, uBO 1.54.1b12, default config
```
</details>

**Comment by mapx-** [comment]
test

    resetoff.pl##.background-cloud-reseton

**Comment by garry-ut99** [comment]
Excellent, works.

No need to add it to uAssets, as it will be added to `Official Polish Filters for AdBlock, uBlock Origin & AdGuard` soon (few days I think), (and by the way maybe to `EasyList Polish` as well)
