### ISSUE TITLE
dailycaller.com: nuisance

### ISSUE THREAD

**Issue by AzChupacabra** [uBlockOrigin/uAssets#21438]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dailycaller.com/2023/06/12/trans-influencer-topless-white-house-biden-pride-month-celebration/`

### Category

breakage

### Description

Tried to leave a comment on Daily Caller.  The site detects my use of uBlock, and opens a popup requiring me to log in again - even though I've already logged in.
In essence, Daily Caller prevents you from commenting unless you turn off uBlock.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (20)](https://github.com/uBlockOrigin/uAssets/assets/60486089/d4322181-5205-4911-9089-3bc2eef6217c)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105466
 cosmetic: 44062
 scriptlet: 19615
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 75699-17, 4m
  easyprivacy: 33117-66, 4m
  plowe-0: 3781-1151, 4m
  ublock-badware: 7619-138, 4m
  ublock-filters: 36135-181, 4m
  ublock-privacy: 949-12, 4m
  ublock-quick-fixes: 105-5, 4m
  ublock-unbreak: 2168-31, 4m
  urlhaus-1: 11315-0, 4m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 397 ms (selfie)
 maxAssetCacheWait: 66 ms
popupPanel:
 blocked: 269
 no-popups: true
 network:
  bounceexchange.com: 1
  civicscience.com: 1
  cxense.com: 1
  d1z2jf7jlzjs58.cloudfront.net: 1
  dn0qt3r0xannq.cloudfront.net: 1
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  google.com: 3
  googletagmanager.com: 2
  googletagservices.com: 1
  gotchosen.com: 1
  imasdk.googleapis.com: 1
  klaviyo.com: 2
  npttech.com: 1
  onesignal.com: 1
  outbrain.com: 1
  piano.io: 1
  pubmatic.com: 1
  rlcdn.com: 1
  spot.im: 244
  twitter.com: 1
 extended:
  ##.ad
  ##+js(abort-on-property-read, googletag)
  ##.slide-ad
```
</details>

**Comment by krystian3w** [comment]
`/onesignalsdk.js$3p,from=dailycaller.com`

?
