### ISSUE TITLE
dropgalaxy.com: detection

### ISSUE THREAD

**Issue by BluePolarPanda** [uBlockOrigin/uAssets#21445]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dropgalaxy.com/drive/32xpmetzcjq1`

### Category

detection

### Description

detected

### Other extensions used

windscribe

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105371
 cosmetic: 44083
 scriptlet: 19616
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75744-17, now
  easyprivacy: 33114-66, now
  plowe-0: 3781-1150, now
  ublock-badware: 7619-138, now
  ublock-filters: 36287-342, now
  ublock-privacy: 949-12, now
  ublock-quick-fixes: 105-5, now
  ublock-unbreak: 2168-31, now
  urlhaus-1: 11210-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 351 ms (selfie)
 maxAssetCacheWait: 139 ms
popupPanel:
 blocked: 6
 network:
  assets-7pb.pages.dev: 1
  cloudflareinsights.com: 1
  google.com: 3
  googlesyndication.com: 1
 extended:
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(remove-node-text, script, break;case $.)
  ##+js(abort-current-script, document.createElement, /break;case …
  ##+js(addEventListener-defuser, DOMContentLoaded, handler)
  ##+js(addEventListener-defuser, , loadScripts)
  ##+js(set-constant, window.isAdblockActive, false)
  ##+js(trusted-set-constant, document.visibilityState, visible)
  ##+js(trusted-replace-node-text, script, true;, false;)
  ##+js(trusted-replace-node-text, script, /none|hidden/, 0, condi…
  ##+js(trusted-replace-node-text, script, /s.src =|s.src/i)
  ##+js(no-window-open-if)
  ##+js(trusted-replace-node-text, script, /charAt|constructor|_0x…
  ##+js(trusted-replace-node-text, script, /iframe|img|image/, scr…
```
</details>

**Comment by mapx-** [comment]
dedicated thread: https://github.com/uBlockOrigin/uAssets/discussions/17361

**Comment by ItsProfessional** [comment]
This is a link shortener?

This a file hosting service...
