### ISSUE TITLE
king-shoot.io: detection

### ISSUE THREAD

**Issue by afhsh1** [uBlockOrigin/uAssets#21441]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://king-shoot.io/hesgoal/14077/1038117/valencia-vs-barcelona/`

### Category

detection

### Description

Site asks to disable the ad blocker.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105457
 cosmetic: 44087
 scriptlet: 19416
 html: 1135
listset (total-discarded, last-updated):
 default:
  user-filters: 1-1, never
  ublock-filters: 37184-226, 2m
  ublock-badware: 7623-11, 2m
  ublock-privacy: 945-4, 2m
  ublock-unbreak: 2214-1, 2m
  ublock-quick-fixes: 105-4, 2m
  easylist: 75744-674, 2m
  easyprivacy: 33114-851, 2m
  urlhaus-1: 11305-0, 2m
  plowe-0: 3781-1, 2m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 508 ms (selfie)
 maxAssetCacheWait: 63 ms
popupPanel:
 blocked: 16
 network:
  arvigorothan.com: 1
  chuckiepedary.com: 1
  demand.supply: 2
  googletagmanager.com: 1
  greeter.me: 9
  purdasseer.com: 2
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.aplvideo
  ###ads_top
  ###content-left-ad
  ###footer_ad_modules
  ###google_ad_inline
  ###top_wide_ad
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by huyszn** [comment]
`king-shoot.io##+js(nosiif, _0x)` for debugger trap and `king-shoot.io###id-custom_banner` for the banner at the bottom of the page
