### ISSUE TITLE
playdede.us: ads

### ISSUE THREAD

**Issue by rodrigosambadesaa** [uBlockOrigin/uAssets#21444]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://playdede.us/login`

### Category

ads

### Description

An ad is visible at the bottom of the page.

### Other extensions used

```
ahfgeienlihckogmohjhadlkjgocpleb : Chrome Web Store : version 0_2
cjpalhdlnbpafiamejdnhcphjbkeiagm : uBlock Origin : version 1_54_0
cnpniohnfphhjihaiiggeabnkjhpaldj : Image Downloader : version 3_4_2
dnhpnfgdlenaccegplpojghhmaamnnfp : Augmented Steam : version 2_6_0
donbcfbmhbcapadipfkeojnmajbakjdc : Ruffle - Flash Emulator : version 0_1_0_1058
efkkjffdefaaioagghcaflicdajfhceo : Web Timer : version 1_4_9
eignhdfgaldabilaaegmdfbajngjmoke : Black Menu for Google™ : version 25_32_1
emehklffcaphknhhfhadkjhpfapcbpco : Strong Password Generator : version 1_6
eokjikchkppnkdipbiggnmlkahcdkikp : Herramienta de selección de color - Geco : version 1_0_7
gddbgllpilhpnjpkdbopahnpealaklle : descargador de videos - CocoCut : version 3_14
ghbmnnjooekpmoecnnnilnnbdlolhkhi : Documentos de Google sin conexión : version 1_69_0
gppongmhjkpfnbhagpmjfkannfbllamg : Wappalyzer - Technology profiler : version 6_10_67
hdghceafmahkdiaoenecabpfokplecfi : Black Menu for Wikipedia : version 5_16_3
ibkoenhablealnikeefmjineccmgegmh : Bitdefender Password Manager : version 1_3_0
icncamkooinmbehmkeilcccmoljfkdhp : Wolfram|Alpha (Official) : version 2_0
idmnciiknelklflhdlnkokcoihkidkln : Dark Space : version 2
ifbmcpbgkhlpfcodhjhdbllhiaomkdej : Copiar y pegar de Office Online : version 0_1_11_5
jgjaeacdkonaoafenlfkkkmbaopkbilf : ChatGPT for Google : version 4_3_4
jjicbefpemnphinccgikpdaagjebbnhg : CSFloat Market Checker : version 3_2_4
johejpedmdkeiffkdaodgoipdjodhlld : Chessvision.ai Chess Position Scanner : version 3_4_1
kdbmhfkmnlmbkgbabkdealhhbfhlmmon : SteamDB : version 3_7_9
llimhhconnjiflfimocjggfjdlmlhblm : Reader Mode : version 1_3_5
lpcaedmchfhocbbapmcbpinfpgnhiddi : Extensión de Google Keep para Chrome : version 4_23492_600_1
mcbpblocgmgfnpjjppndjkmgjaogfceg : Captura de página completa - FireShot : version 1_12_18
mfengiknfnndchbhjmgjjffjndklkpcm : Remove YouTube End Cards & End Screen Videos : version 1_0_4
mffmjlddchdccijipncbjhoabgmphjfb : Vimego - Descargador de videos de Vimeo™ : version 1_5_32
mhjfbmdgcfjbbpaeojofohoefgiehjai : Chrome PDF Viewer : version 1
mmioliijnhnoblpgimnlajmefafdfilb : Shazam: identifica música desde tu navegador : version 2_1_1
mmpokgfcmbkfdeibafoafkiijdbfblfg : Merge Windows : version 1_5_0_0
mnjggcdmjocbbbhaepdhchncahnbgone : SponsorBlock para YouTube - Omitir Sponsors : version 5_4_28
neajdppkdcdipfabeoofebfddakdcjhd : Google Network Speech : version 1_0
nkeimhogjdpnpccoofpliimaahmaaome : Google Hangouts : version 1_3_21
nmmhkkegccagdldgiimedpiccmgmieda : Sistema de pagos de Chrome Web Store : version 1_0_0_6
nnpljppamoaalgkieeciijbcccohlpoh : Link Redirect Trace : version 1_0_0_0
oeopbcgkkoapgobdbedcemjljbihmemj : Checker Plus for Gmail™ : version 24_4_2
ponfpcnoihfmfllpaingbgckeeldkhle : Enhancer for YouTube™ : version 2_0_121
```

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![4b8fbdb7-9dc5-4d5a-bf8a-55f54f1b4f6a](https://github.com/uBlockOrigin/uAssets/assets/43375046/8f6bee97-125f-479a-b73d-fb669316180d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107968
 cosmetic: 50415
 scriptlet: 19984
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 75744-17, now
  easyprivacy: 33114-66, now
  plowe-0: 3781-1150, now
  spa-0: 3775-20, now
  spa-1: 5684-210, now
  ublock-badware: 7619-138, now
  ublock-filters: 36287-365, now
  ublock-privacy: 949-12, now
  ublock-quick-fixes: 105-5, now
  ublock-unbreak: 2168-33, now
  urlhaus-1: 11305-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2044 ms (selfie)
 maxAssetCacheWait: 178 ms
popupPanel:
 blocked: 9
 network:
  appconsent.io: 1
  bipidoan.com: 2
  knmmynblnmkwj.top: 3
  sportslocalmedia.com: 1
  whoursie.com: 2
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by huyszn** [comment]
I get an "Invalid SSL certificate" error when I go to the site.

**Comment by mapx-** [comment]
yeah, `Invalid SSL certificate` too

@rodrigosambadesaa if the site is still alive you can use the element picker to create a filter and eventually report it at easylist repository
