### ISSUE TITLE
dizipal730.com: ads

### ISSUE THREAD

**Issue by parminn** [uBlockOrigin/uAssets#21443]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://dizipal730.com/`

### Category

ads

### Description

There is ads in video's which there wasnt before

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_1](https://github.com/uBlockOrigin/uAssets/assets/41656407/8a1a67e2-54a7-42e4-9043-f876895cbd81)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107740
 cosmetic: 54618
 scriptlet: 21241
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  TUR-0: 13865-9, 6d.6h.14m
  easylist: 75689-38, 53m
  easyprivacy: 33117-72, 53m
  plowe-0: 3777-1150, 6d.6h.14m
  ublock-badware: 7619-138, 53m
  ublock-filters: 36295-349, 53m
  ublock-privacy: 949-12, 53m
  ublock-quick-fixes: 105-5, 53m
  ublock-unbreak: 2168-32, 53m
  urlhaus-1: 11965-0, 23h.54m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 321 ms (selfie)
 maxAssetCacheWait: 88 ms
popupPanel:
 blocked: 16
 network:
  dizipal730.com: 14
  googletagmanager.com: 1
  waust.at: 1
 extended:
  ###bottomAd
```
</details>

**Comment by huyszn** [comment]
Does this work?
`dizipal730.com##+js(rpnt, script, video_urls.length != activeItem+1, video_urls.length === activeItem+1)`

**Comment by parminn** [comment]
It doesn't

**Comment by stephenhawk8054** [comment]
@huyszn It requires users to turn on trusted list for `My filters`
