### ISSUE TITLE
aws.amazon.com: breakage

### ISSUE THREAD

**Issue by joshtriplett** [uBlockOrigin/uAssets#21446]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://aws.amazon.com/s3/pricing/`

### Category

breakage

### Description

With uBlock Origin enabled, various pages on aws.amazon.com no longer show some dynamic content. Pricing pages (such as `https://aws.amazon.com/s3/pricing/`) no longer load prices, and `https://aws.amazon.com/new/` no longer loads the newsfeed.

Disabling uBlock Origin causes these pages to load this dynamic content as expected.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

With uBlock Origin enabled, pricing information doesn't display:

![image](https://github.com/uBlockOrigin/uAssets/assets/162737/51e9a7d4-5c4e-4ad5-8788-f1aa03bc7dcf)

With uBlock Origin disabled, the pricing information (and the control to switch regions) loads and displays:

![image](https://github.com/uBlockOrigin/uAssets/assets/162737/d8bb4d6e-917f-4392-976f-2b4598c62703)

The link to the reInvent conference isn't something uBlock Origin should block, either; it's a conference for AWS users.

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105359
 cosmetic: 44082
 scriptlet: 19414
 html: 1135
listset (total-discarded, last-updated):
 added:
  plowe-0: 3781-1, 3m
  ublock-quick-fixes: 105-0, 3m
 default:
  user-filters: 0-0, never
  ublock-filters: 37174-231, 3m
  ublock-badware: 7623-11, 3m
  ublock-privacy: 945-4, 3m
  ublock-unbreak: 2214-0, 3m
  easylist: 75744-717, 3m
  easyprivacy: 33114-808, 3m
  urlhaus-1: 11210-0, 3m
filterset (user): [empty]
trustedset:
 added: [array of 17 redacted]
userSettings:
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11597 ms (selfie)
 maxAssetCacheWait: 59 ms
popupPanel:
 blocked: 30
 network:
  amazon.com: 10
  aws.dev: 9
  awsstatic.com: 1
  omtrdc.net: 10
```
</details>

**Comment by joshtriplett** [comment]
In case it helps: it looks like some filter in EasyPrivacy is what's blocking the pricing information, and disabling EasyPrivacy makes it display. The reInvent link is being blocked by some filters in both EasyPrivacy and "Peter Lowe’s Ad and tracking server list"; having either one enabled blocks it, with both disabled it displays.

**Comment by huyszn** [comment]
Add `/web-vitals.$badfilter`

Caused by EasyPrivacy @ryanbr

**Comment by stephenhawk8054** [comment]
Does this work?

```adb
/web-vitals.$script,redirect-rule=noopjs,domain=amazon.com
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

---

@huyszn Sorry, can you check too?

**Comment by huyszn** [comment]
> Does this work?
> 
> ```
> /web-vitals.$script,redirect-rule=noopjs,domain=amazon.com
> ```
> 
> Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.
> 
> @huyszn Sorry, can you check too?

This works for me.

**Comment by joshtriplett** [comment]
Confirming that this works to fix the pricing lists. Doesn't fix the reInvent link though.

**Comment by stephenhawk8054** [comment]
What is `reInvent link`?

**Comment by huyszn** [comment]
Is this the reInvent link? It is blocked by `||omtrdc.net^
`
<img width="1403" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/34c6e820-af0b-40d5-800b-29a22700c855">

**Comment by joshtriplett** [comment]
@huyszn Yes, that's the one I'm talking about. That's not an ad, it's a link from the AWS website to the AWS conference.

**Comment by stephenhawk8054** [comment]
Do these work?

```adb
@@||amazonwebservicesinc.tt.omtrdc.net/m2/amazonwebservicesinc/ubox/raw$xhr,3p,domain=aws.amazon.com
||amazonwebservicesinc.tt.omtrdc.net/m2/amazonwebservicesinc/ubox/raw$xhr,3p,removeparam,domain=aws.amazon.com
```

**Comment by joshtriplett** [comment]
Looks like the update worked. Thank you.
