### ISSUE TITLE
understat.com: breakage 

### ISSUE THREAD

**Issue by CennoxX** [uBlockOrigin/uAssets#21442]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://understat.com/league/Bundesliga`

### Description

The tables of the page are not shown, if I remove "uBlock filters – Ads" I see them again.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 107200
 cosmetic: 88117
 scriptlet: 22607
 html: 1135
listset (total-discarded, last-updated):
 removed:
  DEU-0: null
 added:
  fanboy-cookiemonster: 49096-155, 8m
 default:
  user-filters: 42-3, never
  ublock-filters: 37182-243, 5m
  ublock-badware: 7623-11, 8m
  ublock-privacy: 945-4, 8m
  ublock-unbreak: 2214-0, 8m
  easylist: 75744-719, 8m
  easyprivacy: 33114-808, 8m
  plowe-0: 3781-1, 8m
  urlhaus-1: 11305-0, 8m
  ublock-quick-fixes: 105-0, 8m
filterset (user): [array of 42 redacted]
trustedset:
 added: [array of 40 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2213 ms
 maxAssetCacheWait: 657 ms
popupPanel:
 blocked: 4
 network:
  understat.com: 2
  google-analytics.com: 1
  googlesyndication.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by mapx-** [comment]
add

`/jquery.iframetracker.min.js$badfilter`

@ryanbr
