### ISSUE TITLE
mdn.lol: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#21450]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://mdn.lol/2023/06/01/how-to-start-investing-at-15/`

### Category

detection

### Description

"https://t.co/cmjRckyDt0"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium Mobile: 120
filterset (summary):
 network: 111079
 cosmetic: 36955
 scriptlet: 19710
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 32-0, never
  IDN-0: 9716-3888, now
  adguard-mobile: 8918-49, now
  easylist: 75761-16081, 1h.31m
  easyprivacy: 33114-78, 1h.31m
  plowe-0: 3781-1225, now
  ublock-badware: 7613-139, 1h.31m
  ublock-filters: 36641-614, 1h.32m
  ublock-privacy: 949-13, now
  ublock-quick-fixes: 108-5, 1h.32m
  ublock-unbreak: 2174-35, 1h.32m
  urlhaus-1: 11210-0, now
filterset (user): [array of 21 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2174 ms (selfie)
 maxAssetCacheWait: 368 ms
popupPanel:
 blocked: 9
 network:
  a-ads.com: 1
  collowhypoxis.com: 1
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 2
  googlesyndication.com: 1
  purdasseer.com: 1
  r2b2.io: 1
  wtg-ads.com: 1
 extended:
  ##.hidden.title-item
  ##.form-group > div[style^="width:"]
  ##+js(no-fetch-if, bmcdn6)
  ##+js(no-setTimeout-if, /adblock|isRequestPresent/)
  ##+js(abort-current-script, window.onload, devtools)
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by garry-ut99** [comment]
>  * [x]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)

How : https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+in%3Atitle+%22mdn.lol%3A+detection%22+

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/17361
