### ISSUE TITLE
ctrl.blog (Ads)

### ISSUE THREAD

**Issue by 3bsa** [uBlockOrigin/uAssets#2145]
### URL(s) where the issue occurs

    https://www.ctrl.blog/

### Describe the issue

Ads

### Screenshot(s)

![capture](https://user-images.githubusercontent.com/12448559/39471864-4e78a644-4d4e-11e8-8b1b-8c16cef081da.JPG)

### Versions

- Browser/version: Google Chrome Version 66.0.3359.117
- uBlock Origin version: 1.16.2

### Settings

default settings

**Comment by geoffdutton** [comment]
From #2146, try:
```
ctrl.blog##.abox
||ctrl.blog/ac/rba$subdocument,domain=ctrl.blog
```

**Comment by 3bsa** [comment]
It works . Thanks
