### ISSUE TITLE
vtvcab.vn: detection

### ISSUE THREAD

**Issue by tuankietnguyen** [uBlockOrigin/uAssets#21456]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.vtvcab.vn/channel/vtv1-hd-1,VTV1_HD.html`

### Category

detection

### Description

Detected, prevent video from playback. Site functioning just fine after turning off uBo.

### Other extensions used

Bitwarden 
Violentmonkey
Return YouTube Dislike

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-17 223217](https://github.com/uBlockOrigin/uAssets/assets/80906888/6e24354e-0446-4d94-9672-de459f62cbe3)

Translated Text: Please disable the ad blocking plugin (Ad Block) to continue using!

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105245
 cosmetic: 44107
 scriptlet: 19693
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75822-16, now
  easyprivacy: 33114-65, now
  plowe-0: 3781-1150, now
  ublock-badware: 7619-138, now
  ublock-filters: 36384-346, now
  ublock-privacy: 949-12, now
  ublock-quick-fixes: 115-5, now
  ublock-unbreak: 2171-32, now
  urlhaus-1: 11000-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings:
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 391 ms (selfie)
 maxAssetCacheWait: 203 ms
popupPanel:
 blocked: 8
 network:
  firebaselogging-pa.googleapis.com: 3
  googletagmanager.com: 2
  gviet.vn: 2
  moengage.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
@hoang-rio

**Comment by stephenhawk8054** [comment]
I have to use `google-ima.js` to make it work

**Comment by sadtango289** [comment]
> I have to use `google-ima.js` to make it work

can you show me some steps.  i  dont know how to use

**Comment by sadtango289** [comment]
> I have to use `google-ima.js` to make it work

please check video and guide me .  im not good for set up . 
https://github.com/uBlockOrigin/uAssets/assets/45529026/0becda2a-06a0-4815-a36d-38289aa725bf
