### ISSUE TITLE
tecnomd.com: detection

### ISSUE THREAD

**Issue by Rust1667** [uBlockOrigin/uAssets#21453]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tecnomd.com/`

### Category

detection

### Description

overlay caused by adblock detection

### Other extensions used

-

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 306989
 cosmetic: 263011
 scriptlet: 50955
 html: 1399
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81336-7108, now
  adguard-spyware-url: 1360-92, now
  adguard-spyware: 80469-17084, now
  block-lan: 55-0, now
  curben-phishing: 78886-29, now
  adguard-social: 22098-874, 1m
  adguard-cookies: 28247-62, 1m
  ublock-cookies-adguard: 767-0, 1m
  adguard-popup-overlays: 26618-1587, 1m
  adguard-mobile-app-banners: 4847-9, 1m
  adguard-other-annoyances: 14055-324, 1m
  adguard-widgets: 2370-1, 1m
  [13 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 37268-606, now
  ublock-badware: 7623-11, now
  ublock-privacy: 945-4, now
  ublock-unbreak: 2217-2, now
  ublock-quick-fixes: 109-0, now
  easylist: 75785-1050, now
  easyprivacy: 33114-993, now
  urlhaus-1: 11000-0, now
  plowe-0: 3781-1, never
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 32 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2278 ms
 maxAssetCacheWait: 1428 ms
popupPanel:
 blocked: 42
 network:
  amung.us: 1
  cdn4ads.com: 1
  d2j042cj1421wi.cloudfront.net: 1
  d3g5ovfngjw9bw.cloudfront.net: 1
  d3mzokty951c5w.cloudfront.net: 1
  dailymotion.com: 2
  dalyai.com: 2
  displayvertising.com: 1
  dm-event.net: 7
  googlesyndication.com: 9
  googletagmanager.com: 3
  highwaycpmrevenue.com: 1
  mail.ru: 4
  ok.ru: 2
  premiumvertising.com: 1
  wezmklgd.com: 1
  yandex.ru: 3
  ztnibpbkl.com: 1
 extended:
  ##ins.adsbygoogle
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
  ##+js(json-prune, result.body.direct)
  ##+js(abort-on-property-read, globalAuthLoginPopupCounter)
  ##+js(abort-on-property-write, mailruEnabled)
  ##+js(set-constant, Object.prototype.autoplayScrollHandler, noop…
  ##+js(set-constant, Object.prototype.obfuscate, noopFunc)
  ##+js(trusted-set-cookie, dm-euconsent-v2, CPt6yMAPt6yMABpAGAEND…
  ##+js(set-cookie, cookie_policy_closed, 1, , reload, 1)
  ##+js(no-setTimeout-if, adBlockerDetection)
  ##+js(xml-prune, VAST, , adnxs)
  ##+js(no-setTimeout-if, debugger)
```
</details>

**Comment by JobcenterTycoon** [comment]
@mapx- why not adding this to the `! CHP v3.9.2+` list?
