### ISSUE TITLE
www.spiegel.de: ads 

### ISSUE THREAD

**Issue by cococosr** [uBlockOrigin/uAssets#21454]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.spiegel.de/wissenschaft/medizin/adhs-durch-verhaltenstherapien-lernen-betroffene-ruhiger-zu-werden-a-15f6cb5e-6820-4325-99dd-bc744f3c8101`

### Description

(This is my first ever report/contribution to a project. Please be indulgent.)

On the page mentioned above there are two ads (in German "Anzeige") not blocked. I once tried filtering the upper one with the element picker tool but it came back later / didn't work with similar ads in other news articles.

The other ad is at the bottom of the page (look out for "Gutscheine" or "Anzeige"). I also tried to remove it with the element picker tool but I don't know how to write proper filters.

I highlighted both ads with yellow rectangles.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![1](https://github.com/uBlockOrigin/uAssets/assets/154068585/97c50956-253c-43ea-af96-42efdee03061)

![2](https://github.com/uBlockOrigin/uAssets/assets/154068585/3c777455-dcdf-41eb-b400-26b0eed94941)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 120130
 cosmetic: 201169
 scriptlet: 31138
 html: 1340
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1360-92, 36m
  block-lan: 55-0, 36m
  adguard-social: 22098-875, 36m
  adguard-cookies: 28247-62, 36m
  ublock-cookies-adguard: 767-0, 36m
  adguard-popup-overlays: 26618-1584, 36m
  adguard-mobile-app-banners: 4847-1070, 36m
  adguard-other-annoyances: 14057-330, 36m
  adguard-widgets: 2370-1, 36m
  fanboy-thirdparty_social: 69-0, 36m
  easylist-annoyances: 4245-122, 36m
  easylist-chat: 168-12, 36m
  [7 lists not shown]: [too many]
 default:
  user-filters: 40-0, never
  ublock-filters: 37271-595, 36m
  ublock-badware: 7623-11, 36m
  ublock-privacy: 945-4, 36m
  ublock-unbreak: 2217-2, 36m
  ublock-quick-fixes: 115-0, 36m
  easylist: 75822-808, 36m
  easyprivacy: 33114-911, 36m
  urlhaus-1: 11000-0, 36m
  plowe-0: 3781-1, 36m
filterset (user): [array of 27 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 2 redacted]
hostRuleset:
 added: [array of 137 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 160 ms (selfie)
 maxAssetCacheWait: 74 ms
popupPanel:
 blocked: 3
 network:
  adobedtm.com: 1
  dwcdn.net: 1
  privacy-mgmt.com: 1
 extended:
  ##.border-separator-t > ul.flex:has(> li.pl-24 > a.inline-flex >…
  ##+js(trusted-click-element, button[title^="Consent"])
  ##+js(remove-class, jw-flag-floating, .jwplayer.jw-flag-floating…
  ##+js(no-setTimeout-if, .call(null), 10)

```
</details>

**Comment by mapx-** [comment]
maybe

```
spiegel.de##[data-area="affiliatebox"]
spiegel.de##[data-area="vouchers"]
```
