### ISSUE TITLE
diacritice.ro: ads

### ISSUE THREAD

**Issue by LightAndy1** [uBlockOrigin/uAssets#21467]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://diacritice.ro/`

### Category

ads

### Description

There's a website hosting ad on the right (next to the input box). This is a simple fix: 

```
##.space
```

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot of diacritice.ro](https://github.com/uBlockOrigin/uAssets/assets/50150516/b5d321dc-1f2d-4a2d-95a5-004fbf0e04b0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105336
 cosmetic: 44134
 scriptlet: 19710
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75866-16, now
  easyprivacy: 33117-65, now
  plowe-0: 3781-1150, now
  ublock-badware: 7633-138, now
  ublock-filters: 36430-346, now
  ublock-privacy: 949-12, now
  ublock-quick-fixes: 116-5, now
  ublock-unbreak: 2172-32, now
  urlhaus-1: 11025-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 434 ms (selfie)
 maxAssetCacheWait: 126 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 2
```
</details>

**Comment by mapx-** [comment]
Enable the regional list: `Romanian Ad (ROad) Block List Light`

**Comment by LightAndy1** [comment]
Already enabled, thanks!
