### ISSUE TITLE
readcomicsonline.ru: ads

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#21461]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://readcomicsonline.ru/comic/classic-popeye-2012/48`

### Category

ads

### Description

Leftover caused by built-in filters.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://github.com/uBlockOrigin/uAssets/assets/151783497/96ed8c04-9b60-4345-a425-e3bb80b61638)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 195480
 cosmetic: 174316
 scriptlet: 46746
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28247-30, 3m
  adguard-generic: 81349-487, 3m
  adguard-mobile-app-banners: 4847-10, 3m
  adguard-other-annoyances: 14057-8, 3m
  adguard-popup-overlays: 26618-86, 3m
  adguard-social: 22098-926, 3m
  adguard-spyware: 80469-1208, 3m
  adguard-spyware-url: 1360-5, 3m
  adguard-widgets: 2370-5, 3m
  block-lan: 55-0, 3m
  spa-1: 5684-78, 3m
  ublock-annoyances: 6302-196, 3m
  [1 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  easylist: 75833-1737, 3m
  easyprivacy: 33114-16466, 3m
  plowe-0: 3781-1249, 3m
  ublock-badware: 7619-321, 6m
  ublock-filters: 36149-3961, never
  ublock-privacy: 949-390, 6m
  ublock-quick-fixes: 114-5, 6m
  ublock-unbreak: 2171-149, 3m
  urlhaus-1: 11000-0, 6m
filterset (user): [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2329 ms (selfie)
 maxAssetCacheWait: 1080 ms
popupPanel:
 blocked: 7
 network:
  4dsply.com: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  infolinks.com: 1
  mgid.com: 2
  sunmedia.tv: 1
 extended:
  ##div[id*="ScriptRoot"]
  ##.ads-large
  ##+js(nobab)
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by gorhill** [comment]
Need:

    readcomicsonline.ru##.ads
    readcomicsonline.ru##.ads-large

Can be fixed in Easylist, cc @ryanbr r
