### ISSUE TITLE
junkyponk.com: nuisance 

### ISSUE THREAD

**Issue by yuukiAme** [uBlockOrigin/uAssets#21474]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://junkyponk.com/flatten-your-midsection-the-ultimate-diet-for-age-related-belly-fat/`

### Description

The website gives you a 16-second timer and you have to click Continue in order to take you to the Next button and it takes you to the next page.

You will need the first link in order to reach junkyponk.com nuisance timer page. Otherwise, it will only show a normal page filled with text with no timer.

**First URL here** => `https://clk.wiki/El2YS03#`

### Other extensions used

None. I disabled the rest of extensions before this report.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-12-19 15_14_52-Window](https://github.com/uBlockOrigin/uAssets/assets/45681604/01595538-206f-4c9c-a8a3-18a777c3543e)
![2023-12-19 15_15_15-Window](https://github.com/uBlockOrigin/uAssets/assets/45681604/73a52df5-e03b-40fc-983c-dc4f0847af07)
![2023-12-19 15_15_23-Window](https://github.com/uBlockOrigin/uAssets/assets/45681604/bcad33a9-6790-48dd-8e97-239b0eaf1345)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105926
 cosmetic: 44152
 scriptlet: 19505
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37324-362, now
  ublock-badware: 7637-11, now
  ublock-privacy: 945-4, now
  ublock-unbreak: 2222-1, now
  ublock-quick-fixes: 116-0, now
  easylist: 75885-546, now
  easyprivacy: 33116-850, now
  urlhaus-1: 11620-0, now
  plowe-0: 3781-1, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 121 ms (selfie)
 maxAssetCacheWait: 63 ms
popupPanel:
 blocked: 2
 network:
  a-ads.com: 1
  guitarfelicityraw.com: 1
 extended:
  ##.banner-728x90
  ##.banner-468x60

```
</details>

**Comment by BlazeFTL** [comment]
https://github.com/uBlockOrigin/uAssets/pull/21477
