### ISSUE TITLE
m2o.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#21485]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.m2o.it/on-air/`
`https://www.deejay.it/on-air/`
`https://www.capital.it/on-air/`

### Category

nuisance

### Description

nuisance fixable with
`##+js(trusted-click-element, .iubenda-cs-visible button.iubenda-cs-close-btn)`
cannot hide it otherwise radio doesn't work

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1132" alt="1" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/0edca89f-c97f-48b8-8e6a-34e7f29784de">

<img width="1114" alt="2" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/c6a6d200-52cc-414a-8e20-0a8ab20e10ba">

<img width="1164" alt="3" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/d5a3b515-c4b2-4d2b-92da-00ad6453badf">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 111958
 cosmetic: 123820
 scriptlet: 26967
 html: 1344
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4256-96, 1m
  easylist-chat: 168-0, 1m
  fanboy-cookiemonster: 49156-229, 1m
  ublock-cookies-easylist: 806-0, 1m
  easylist-newsletters: 6732-13, 1m
  easylist-notifications: 2891-4, 1m
  fanboy-social: 16009-11, 1m
  ublock-annoyances: 6305-838, 1m
  ITA-0: 8543-21, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 37319-250, now
  ublock-badware: 7647-11, now
  ublock-privacy: 945-4, now
  ublock-unbreak: 2222-1, now
  ublock-quick-fixes: 102-0, now
  easylist: 75917-749, 1m
  easyprivacy: 33118-894, 1m
  urlhaus-1: 11445-0, 1m
  plowe-0: 3781-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 734 ms
 maxAssetCacheWait: 342 ms
popupPanel:
 blocked: 16
 network:
  admantx.com: 1
  chartbeat.com: 3
  criteo.net: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  imrworldwide.com: 1
  opecloud.com: 1
  taboola.com: 1
  viafoura.co: 4
  wt-safetag.com: 1
 extended:
  ##div[id^="crt-"][style]
  ##.main-header__social
  ###adv-Top
  ###adv-Middle1
  ###adv-Middle2
  ###adv-Piede
  ##.footer-follow
```
</details>

**Comment by peace2000** [comment]
@superlex I think it's better to give clear "reject all" answer rather than just "continue without accepting".

**Comment by D4niloMR** [comment]
Is there a reason to not block `cs.iubenda.com` or `iubenda.com` ? (the domain responsible for the cookie notice)

**Comment by superlex** [comment]
@peace2000 
Is not the same?
Anyway, if you prefer so for me there is no problem.

@D4niloMR 
Nope, in this case if you block `iubenda` or hide the popup radio doesn't work.

**Comment by peace2000** [comment]
I'm not fully sure whether there's a difference in outcome or not. But I think that rejecting is more certain.

Added also a filter to hide the dialog because otherwise it will momentarily appear before the scriptlet clicks it. The clicker works for hidden dialogs as well.

**Comment by superlex** [comment]
Ok, thank you!
