### ISSUE TITLE
huffingtonpost.it: nuisance

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uAssets#21484]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.huffingtonpost.it/video/2023/12/19/video/islanda_laghi_di_lava_dopo_settimane_di_forte_attivita_sismica-14620920/`
+
`https://www.huffingtonpost.it/esteri/2023/12/19/news/non_solo_soldi_e_munizioni_per_zelensky_sapre_anche_il_problema_uomini-14637024/?ref=**`

### Category

nuisance

### Description

Screenshot 1:
nuisance fixable with
`huffingtonpost.it###iubenda-cs-banner`

Screenshot 2:
`huffingtonpost.it###widgetDP`

+

`||huffingtonpost.it^$removeparam=ref`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(1)</summary>

<img width="1140" alt="k" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/0793d533-a2ff-483d-b3d3-6671269c4bba">

</details>

<details>
<summary>Screenshot(2)</summary>

<img width="1140" alt="k" src="https://github.com/uBlockOrigin/uAssets/assets/1375223/95976518-99e0-421a-af22-e5cdfb0470e8">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 107958
 cosmetic: 52408
 scriptlet: 23660
 html: 1344
listset (total-discarded, last-updated):
 added:
  ublock-cookies-adguard: 806-0, 1m
  ublock-annoyances: 6305-817, 1m
  ITA-0: 8543-21, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 37319-242, 1m
  ublock-badware: 7647-11, 1m
  ublock-privacy: 945-4, 1m
  ublock-unbreak: 2222-1, 1m
  ublock-quick-fixes: 102-0, 1m
  easylist: 75917-726, 1m
  easyprivacy: 33118-808, 1m
  urlhaus-1: 11445-0, 1m
  plowe-0: 3781-1, 1m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 529 ms
 maxAssetCacheWait: 223 ms
popupPanel:
 blocked: 24
 network:
  huffingtonpost.it: 1
  2mdn.net: 1
  admantx.com: 1
  brightcove.com: 4
  chartbeat.com: 4
  googlesyndication.com: 1
  googletagmanager.com: 1
  gstatic.com: 1
  imrworldwide.com: 3
  iubenda.com: 1
  opecloud.com: 1
  viafoura.co: 4
  wt-safetag.com: 1
 extended:
  ###adv-Top
  ###adv-TopLeft
  ##.ad-text
  ##.adSense
  ##.adBlock
  ##.adContent
  ##.vjs-ima3-ad-container
  ##+js(xml-prune, VAST, , adnxs)
```
</details>

**Comment by superlex** [comment]
Also
`https://www.huffingtonpost.it/esteri/2023/12/19/news/non_solo_soldi_e_munizioni_per_zelensky_sapre_anche_il_problema_uomini-14637024/?ref=**`
https://github.com/uBlockOrigin/uAssets/assets/1375223/95976518-99e0-421a-af22-e5cdfb0470e8
```
huffingtonpost.it###widgetDP
||huffingtonpost.it^$removeparam=ref
```

**Comment by D4niloMR** [comment]
Enable `EasyList – Cookie Notices` or `AdGuard – Cookie Notices`
