### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by freakedenough** [uBlockOrigin/uAssets#21496]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [x] #21497
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.derstandard.at/consent/tcf/story/3000000200180/leerstand-im-nordbahnviertel-alleingelassen-in-der-bruno-marek-allee`

### Category

detection

### Description

Detects ad blocker and reloads to an empty site instead of showing the article and community comments below. One of the biggest news sites in Austria.

### Other extensions used

Still dont care about Cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2023-12-20 111450](https://github.com/uBlockOrigin/uAssets/assets/93607470/3de0773c-50a0-4879-bb9b-345547eec3db)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 310271
 cosmetic: 130
 scriptlet: 49489
 html: 1345
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76070-76070, now
  https://malware-filter.gitlab.io/malware-filter/phishing-filter.txt: 79545-30, 1h.9m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1h.9m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-138, now
  https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95178-95178, now
  https://winhelp2002.mvps.org/hosts.txt: 8729-315, now
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, now
  fanboy-thirdparty_social: 69-1, now
  fanboy-social: 16023-15068, now
  dpollock-0: 11614-1732, now
  CZE-0: 834-426, 1h.10m
  [21 lists not shown]: [too many]
 default:
  user-filters: 158-8, never
  ublock-filters: 37317-10603, 1h.10m
  ublock-badware: 7647-688, 1h.10m
  ublock-privacy: 945-17, 1h.10m
  ublock-unbreak: 2222-305, 1h.10m
  easylist: 76073-34014, 1h.10m
  easyprivacy: 33118-1189, 1h.10m
  plowe-0: 3781-1705, now
  DEU-0: 7230-4855, 1h.10m
  urlhaus-1: 12725-0, 1h.10m
filterset (user): [array of 159 redacted]
trustedset:
 added: [array of 142 redacted]
 removed:
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
 parseAllABPHideFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 327 ms (selfie)
 maxAssetCacheWait: 188 ms
popupPanel:
 blocked: 2
 network:
  staticfiles.at: 2
```
</details>

**Comment by freakedenough** [comment]
Relates to https://github.com/uBlockOrigin/uAssets/issues/21146 but their warning towards me is different. I assume they implementes several different methods. On Mobile Firefox with uBlock they yet dont bother me.

**Comment by freakedenough** [comment]
at.staticfiles.at/js/derstandard-04cbfa81b7.js
this file seems to cause it.

**Comment by okiehsch** [comment]
> but their warning towards me is different

You enabled 33! aditional filter lists....
Try with a default setup and there is no need to open a second issue about the same site, just post in the first one even if the adblock message is slightly different.
