### ISSUE TITLE
kemiox.com: detection

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21493]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kemiox.com/`

### Category

detection

### Description

DeBlocker site. I removed the anti-adb using `kemiox.com##+js(rmnt, script, deblocker)` but I occasionally see ad leftovers from Yandex after clicking links on the site.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>
Yandex ad leftovers

<img width="1439" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/fec1b44b-4ad9-4008-af31-20422b857369">

<img width="1440" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/b262b84f-faa5-48c4-91de-d3e2a407ef1d">

<img width="1440" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/7a8c8df4-fad6-4a84-899b-5aed7a508603">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107505
 cosmetic: 45899
 scriptlet: 24070
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6360-17, now
 default:
  user-filters: 52-2, never
  easylist: 76073-16, now
  easyprivacy: 33118-65, now
  plowe-0: 3781-1150, now
  ublock-badware: 7643-138, now
  ublock-filters: 36427-345, now
  ublock-privacy: 949-12, now
  ublock-quick-fixes: 100-5, now
  ublock-unbreak: 2176-33, now
  urlhaus-1: 12725-0, now
filterset (user): [array of 42 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 167 ms (selfie)
 maxAssetCacheWait: 54 ms
popupPanel:
 blocked: 13
 network:
  kemiox.com: 1
  doubleclick.net: 1
  googlesyndication.com: 5
  googletagmanager.com: 1
  yandex.ru: 5
```
</details>

**Comment by huyszn** [comment]
@D4niloMR Do you see the Yandex ad leftovers?

**Comment by D4niloMR** [comment]
I can see now, but its an ad, not much easy to reproduce.

<details><summary>Screenshots</summary>
<p>

![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/7a29f3c9-4ff6-4073-8a9d-db79b48b6234)
![image](https://github.com/uBlockOrigin/uAssets/assets/70459964/96c8a37f-53e6-475e-bc59-d1069084677a)


</p>
</details> 

`||yandex.com/ads/system/context.js$script` is enough.

@ryanbr `yandex.ru/ads/system/context.js` is blocked on yandex by `.ru/ads/` so this filter shouldn't cause problems if added to EL?
