### ISSUE TITLE
watch.foxtel.com.au: ads

### ISSUE THREAD

**Issue by Dawnduckie** [uBlockOrigin/uAssets#21494]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://watch.foxtel.com.au/app/`

### Category

ads

### Description

Upon loading certain shows, or while watching others, as of Monday the 18th of December, ads are now appearing in the web app. 

The screen freezes as if an ad popup is triggering, but instead of the ad playing, there is a "learn more" in the top right corner of the screen, the ad does not play and the video of the programme being watched no longer plays as it pauses for the end of the ads. 

Until this date, the site worked perfectly. 

This does require a login, so if one is required it can be provided upon request. 

I have used the previous filter link from a closed thread and it does not seem to be working at this point.

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107074
 cosmetic: 44187
 scriptlet: 19707
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 38-1, never
  easylist: 75919-16, 22m
  easyprivacy: 33118-65, 22m
  plowe-0: 3781-1150, now
  ublock-badware: 7643-138, 22m
  ublock-filters: 36431-347, 22m
  ublock-privacy: 949-12, 22m
  ublock-quick-fixes: 100-5, 22m
  ublock-unbreak: 2176-32, 22m
  urlhaus-1: 12725-0, 1h.22m
filterset (user): [array of 38 redacted]
trustedset:
 added: [array of 48 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 347 ms (selfie)
 maxAssetCacheWait: 135 ms
popupPanel:
 blocked: 1
 network:
  segment.com: 1
 extended:
  ##+js(xml-prune, xpath(//*[name()="Period"][.//*[name()="BaseURL…
```
</details>

**Comment by stephenhawk8054** [comment]
Can you give the exact link of which show did you see the ads?

**Comment by Dawnduckie** [comment]
https://watch.foxtel.com.au/app/#/shows/356038/seasons/11/episode/9882010/play

Was the one giving me the issue, but it occured on

https://watch.foxtel.com.au/app/#/shows/184878/seasons/20/episode/10005605/play

and 

https://watch.foxtel.com.au/app/#/shows/342688/seasons/8/episode/10009284/play


(yes I watch trash on foxtel. LOL)

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
foxtel.com.au#@#+js(xml-prune, xpath(//*[name()="Period"][.//*[name()="BaseURL" and contains(text()\,'adease')]]), ,.mpd)
foxtel.com.au##+js(xml-prune, xpath(//*[name()="MPD"]/@mediaPresentationDuration | //*[name()="Period"]/@start | //*[name()="Period"][.//*[name()="BaseURL" and contains(text()\,'adease')]]), [media^="A_D/"], .mpd)
foxtel.com.au##+js(json-prune, adease adeaseBlob vmap, adease)
```

Click on uBO icon > &#9881; [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > &#10003; Apply changes > Open new tab and test again.

**Comment by Dawnduckie** [comment]
These so far seem to have fixed the issue I had been experiencing. I retried each of the links and each have been annoyance free. 

Thank you so much for the quick help. I will keep you updated, but for now it seems to have repaired the issue.

**Comment by stephenhawk8054** [comment]
Thanks for your testing. The update will come after 5-6 hours. After that you can remove the above custom filters.
