### ISSUE TITLE
forum.meizufans.eu

### ISSUE THREAD

**Issue by zmni** [uBlockOrigin/uAssets#215]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://forum.meizufans.eu/`

### Describe the issue

Full screen element on the site when uBlock enabled.

### Screenshot(s)

![untitled 1](https://cloud.githubusercontent.com/assets/841523/20858248/20855288-b974-11e6-8bd7-1b4fdcb0d6c5.jpg)

### Versions

- Browser/version: Firefox/52.0a2
- uBlock Origin version: 1.10.0

### Settings

[Hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode) & additional filter lists

### Notes

allow, noop or block everything (inline, 1st, 3rd, frame) in dynamic filter doesn't work, the site still displaying full screen element. The site load & work normally when uBlock whitelist the entire site domain.

**Comment by mapx-** [comment]
add
```
@@||meizufans.eu^$generichide
@@.png#$domain=meizufans.eu
```

**Comment by uBlock-user** [comment]
filter - `@@||meizufans.eu^$elemhide
`

**Comment by zmni** [comment]
Works well now. Thanks.
