### ISSUE TITLE
lgcnews.com: detection

### ISSUE THREAD

**Issue by tapetumlucidum** [uBlockOrigin/uAssets#21502]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://lgcnews.com/`

### Category

detection

### Description

Soft adblocker detected popup, happens in both Chrome and Firefox.

### Other extensions used

Tampermonkey, Dark Reader, Google Keep, VideoAdBlockForTwitch, SponsorBlock. Disabling them did not help.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/109995766/9e5025b9-3643-49cd-99e8-feeb9a5e991d)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 195053
 cosmetic: 140854
 scriptlet: 29933
 html: 0
listset (total-discarded, last-updated):
 added:
  TUR-0: 13092-8, now
  adguard-cookies: 28231-30, now
  adguard-mobile-app-banners: 4849-9, now
  adguard-other-annoyances: 13970-8, now
  adguard-popup-overlays: 26652-79, now
  adguard-social: 22107-924, now
  adguard-widgets: 2375-3, now
  curben-phishing: 79563-20, now
  ublock-annoyances: 6360-160, now
  ublock-cookies-adguard: 816-816, now
 default:
  user-filters: 1-0, never
  easylist: 76103-96, now
  easyprivacy: 33123-139, now
  plowe-0: 3782-1153, now
  ublock-badware: 7643-144, now
  ublock-filters: 36444-699, now
  ublock-privacy: 951-13, now
  ublock-quick-fixes: 100-5, now
  ublock-unbreak: 2176-35, now
  urlhaus-1: 11990-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 17 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 270 ms (selfie)
 maxAssetCacheWait: 206 ms
popupPanel:
 blocked: 12
 network:
  lgcnews.com: 1
  googlesyndication.com: 10
  googletagmanager.com: 1
 extended:
  ##ins.adsbygoogle
  #@#[data-ad-module]
  #@#[data-ad-width]
  #@#[data-adblockkey]
  #@#[data-advadstrackid]
  #@#[data-ad-manager-id]
```
</details>

**Comment by BlazeFTL** [comment]
```adblock-filter-list
lgcnews.com##+js(noeval-if, /chp_?ad/)
```
