### ISSUE TITLE
chip.de: ads

### ISSUE THREAD

**Issue by ONE11111111ONE** [uBlockOrigin/uAssets#21504]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://www.chip.de/downloads/Thunderbird-Conversations_46083278.html`

### Description

Almost whereever you download something from chip.de it is full of ads. even you can use cosmetic filters, it will not disappear and come back.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![chip](https://github.com/uBlockOrigin/uAssets/assets/150746073/08f4a2f9-2c61-42e9-9886-0df07e56233b)
![chip](https://github.com/uBlockOrigin/uAssets/assets/150746073/5e3ed628-d2ec-4b68-a135-fcb2ad828786)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by ONE11111111ONE** [comment]
Would be awesome, if anyone of you guys can help the people out. thanks

**Comment by HcKaos** [comment]
no ads on my end. check if you got filters in the list activein the settings.

**Comment by ONE11111111ONE** [comment]
Hi HcKaos,

you see the screenshots right? i just have normal filters active. which come with ublock instalaltion and i use the latest beta version. still the ads. sometimes they appear, sometimes not. thats the strange thing about it.

**Comment by ONE11111111ONE** [comment]
e.g. https://www.chip.de/downloads/Excel-Haushaltsbuch_64973937.html

no ads at all!

**Comment by HcKaos** [comment]
I noticed on some Websites i have to block some ads again from time to time because they show up again somewhow. But it usualy lasts about 2-4 weeks so not a real issue for me. 
Try to block them again by hand and see if its working for a while.

**Comment by ONE11111111ONE** [comment]
@JobcenterTycoon  if it doesn't break ublock origin in any way i will give it a try. Thanks!
Seems to be a complicated case.

**Comment by ONE11111111ONE** [comment]
i haven't tried the script for tampermonkey yet, but the extension breaks e.g. chip.de it makes all article pictures much bigger.

**Comment by JobcenterTycoon** [comment]
I updated the uBO filter 2h ago. I can take a look on the next day. If you want you can open a issue in Adguard Extra.

**Comment by ONE11111111ONE** [comment]
ThankAlright. I am goinfg to do that today. Yet, is this reinsertion not a ublock oirgin issue then which could be dealth with? instead of assets?

**Comment by JobcenterTycoon** [comment]
Technical:

1. The ads are hardcoded into the site. They also use some sort of obfuscation and camouflage to hinder Adblockers.
2. A script checking for a adblocker.
3. If no adblocker got detected the ads getting removed (But sometimes broken/deactivated).

I try to block the ads and i try to prevent the detection already. But they keep updating so the ads coming back until i update the filters. A typical war.

**Comment by ONE11111111ONE** [comment]
i totally understand the Situation. 
Yet, is there no possibility for gorhill to do anything about it? or is it a fight against walls, as said. There is always a solution in my experience.

**Comment by JobcenterTycoon** [comment]
Yes its true. There is always a solution. But it counts for both sides. At the moment the current filter working fine. I also opened a issue in Adguard Extra now but they are pretty slow.

**Comment by ONE11111111ONE** [comment]
Alright. Thanks, so i do not have to do it. Still, what do you think, that it's not just a filter issue but a ublock origin advancement?

**Comment by ONE11111111ONE** [comment]
Since it's not an ad related stuff, i don't know why it got deleted? it is a continuity of https://github.com/uBlockOrigin/uAssets/issues/21382, just for information

**Comment by ONE11111111ONE** [comment]
Sir MasterKia..

**Comment by ONE11111111ONE** [comment]
It should be reopened, since it got fixedm, and now it is broken again. and not related to the ad stuff i was posting in this commit.

Thanks.

**Comment by ONE11111111ONE** [comment]
https://www.chip.de/download/9232_Downloads/1/

same style breakage as last time posting a few days ago.

i don't know what these crazy mf are doing but, since they are part of focus.de a german newspaper, ..you have to figure it out.

Please help again Sir Hartz Vier Tycoon :-)

**Comment by JobcenterTycoon** [comment]
fixed.

**Comment by ONE11111111ONE** [comment]
Hi man, 

sorry it's still going on, i even reinstalled ublock origin 1.54 and it didn't work. then installed the newest beta and it didn't work as well.

so what can this be ?

https://www.chip.de/download/9232_Downloads/1/

**Comment by JobcenterTycoon** [comment]
`1.54.0` is fine, force update the quick list.

**Comment by ONE11111111ONE** [comment]
Thank you!

**Comment by ONE11111111ONE** [comment]
What about this complicated case? i checked your adguard extra commit, well...do you really think they will solve it at any time?
someone has to do something about it, i don't have the knowledge to do it. I do not want to ask gorhill personally if he is busy with other things.

**Comment by ONE11111111ONE** [comment]
@JobcenterTycoon did you close it because there is a permanent solution?

**Comment by JobcenterTycoon** [comment]
I closed because i saw no circumvent attempt since 2 weeks. But im still monitoring this to be sure they don’t bring the ads back without being noticed.

**Comment by ONE11111111ONE** [comment]
Alright! Thank you!

**Comment by ONE11111111ONE** [comment]
I see it too. I guess gorhill has to "invent" something about these issues. Filterlist updating all the time is not the solution.

**Comment by JobcenterTycoon** [comment]
There is no permanent solution.

**Comment by ONE11111111ONE** [comment]
yet... ;-)
man, everything is possible. if they can do what they do, why would someone else not be able to do something against or about it....
reflect about it. i know enough about these things, and also in IT, to know this.

**Comment by JobcenterTycoon** [comment]
Adguard Extra fixed the breakage and the ads one week ago https://github.com/AdguardTeam/AdGuardExtra/issues/484. I tested and Adguard Extra still works fine.

**Comment by ONE11111111ONE** [comment]
Hmm, i tested too and it works. Thanks for that information!  Yet why rely on some 3rd party extra add on (of the competitor with 1 million installations on FF) nobody knows about if everyone wants just to use ublock origin anyway? Just my opinion. If they can do it...why not for ublock origin?

**Comment by garry-ut99** [comment]
> ONE11111111ONE : (AdGuard Extra) why not for ublock origin?

There existed https://github.com/gorhill/uBO-Extra in the past.

**Comment by ONE11111111ONE** [comment]
i saw it, i never used it though. since i didn't need it. time to recover for FF and this..chrome thing. ;-)

**Comment by krystian3w** [comment]
But that add-on was to fight redirection to /c00 with ads, so resurrecting it makes no sense.

**Comment by Dragodraki** [comment]
Hi there, chip.de ads were annoying topic to me to. Seems yesterday devs fixed something so ads get blocked again, like intended.
I recognized that ads were not visible too if no adblocker existed in first place - my first thought was it was the FF own blocker (as if). But its chip.de - they are really nasty: Advertise if you have an adblocker and don't do it if you haven't one?! I am not an expert but that looks like traffic noising to me. 
However, thank you so much uBO team for fixing that continuesly! uBO has much harder job than Adguard - the letter uses AI in their own addon with the result of automation and more false positives, uBlock Origin mostly relies on static filters (blacklist), so it must be very hard to keep it up-to-date. But the result is much more accurate and stable than its green competitor.

**Comment by ONE11111111ONE** [comment]
@krystian3w  i didn't talk about resurrecting, i was talking about something new. the ads on chip are back again. it's not a solution to fight all the time. and this adguard stuff uses AI to block it? are you serious? if nobody contact's gorhill i will do it. finish.
i could ask @JobcenterTycoon if he can fix it again and again. yet this is no permanent solution.

**Comment by JobcenterTycoon** [comment]
I fixed the ads 4 hours ago.

<details>
<summary> but here are some private filter: </summary>


Fastest:

```
www.chip.de##+js(rpnt, script, /if \(window\.gsinit \!\=\= 2\).*?\[\"/s, document.querySelector(".)
www.chip.de##+js(rpnt, script, /"\] \= \{"rep"\:null\,"impr"\:"https\:\/\/im\.chip\.de\/ii\/.*/s, ").remove())
```

Slower:

```
www.chip.de##+js(rpnt, script, !=typeof global?global:this);, !=typeof global?global:this); window.addEventListener("DOMContentLoaded"\,function(){if(!0===window.location.href.startsWith("https://www.chip.de/download")){let t=document.querySelectorAll('[style^="min-height:"]:has(a[href^="https://www.chip.de/downloads/"] img[src^="https://im.chip.de/ii/"])');for(let e=0;e<t.length;e++)t[e].remove()}})\,window.addEventListener("load"\,function(){if(!0===window.location.href.startsWith("https://www.chip.de/download")){let t=document.querySelectorAll('a figure > img[src^="https://im.chip.de/ii/"]');for(let e=0;e<t.length;e++)(250===t[e].naturalHeight&&1e3===t[e].naturalWidth||600===t[e].naturalHeight&&128===t[e].naturalWidth||250===t[e].naturalHeight&&300===t[e].naturalWidth)&&t[e].remove()}});)
```

For both you need to set the [advanced setting](https://github.com/gorhill/uBlock/wiki/Advanced-settings) `trustedListPrefixes` to `ublock- user-`

</details>

**Comment by ONE11111111ONE** [comment]
@JobcenterTycoon  Thanks once more man! I see. Now you understand, why i do not like to rely on the Adguard Extra thing (check the Off-topic comment by Dragodraki), even it solves the issue. I support what i see is the best for the World, and AI is not part of it in any way, i am sorry. If i have been using Programs, Add-ons whatever unconsciously; fine. If i get awareness about it, they(the devs)  can go their way, which is not mine.

**Comment by ItsProfessional** [comment]
@ONE11111111ONE Please don't post off-topic comments about adguard here. When you get ads on the site, notify us here via a comment so that it can be fixed. This is not a place to discuss about AI or about other blocker extensions.

**Comment by ONE11111111ONE** [comment]
@ItsProfessional That's alright.

**Comment by Dani-1-2** [comment]
A bit unrelated but I managed to hide the cookie popup with ||cmp.chip.de/index.html?hasCsp=true&message_id=925148&consentUUID=5b13fb0e-6264-4bfa-bd0c-20f35140a634_26&preload_message=true&version=v1$subdocument . Would be nice if this was included in the annoyances.

**Comment by JobcenterTycoon** [comment]
Blocking the cookie banner breaks videos.

**Comment by ONE11111111ONE** [comment]
> > Alright. Thanks, so i do not have to do it. Still, what do you think, that it's not just a filter issue but a ublock origin enhancement?
> 
> Can you send a screenshot of where the ad appears? I can't find an ad at the moment.

@JobcenterTycoon does his good job blocking aggressive ad banners whenever they appear. yet imo there muste be an enhancement coming like ublock extra? for chrome in the past, now something new for everything. end of the story.

**Comment by JobcenterTycoon** [comment]
"ublock extra" -> the filter from https://github.com/uBlockOrigin/uAssets/issues/21504#issuecomment-1897043200

**Comment by Dani-1-2** [comment]
> Blocking the cookie banner breaks videos.
How about these cosmetic filters:
www.chip.de###sp_message_iframe_925148
www.chip.de###sp_message_container_925148
?

**Comment by JobcenterTycoon** [comment]
Also breaking videos.

**Comment by Dani-1-2** [comment]
> Also breaking videos. 

Can you tell me the link to the video so that I can check for myself when experimenting?

**Comment by JobcenterTycoon** [comment]
Saw no circumventation attempt for weeks. I will still monitor.

**Comment by liamengland1** [comment]
Maybe add "ongoing" label? @JobcenterTycoon

**Comment by JobcenterTycoon** [comment]
When they try to circumvent again i will re add the label.

**Comment by ONE11111111ONE** [comment]
https://www.chip.de/news/Grosse-Plaene-Wird-das-die-wichtigste-Tastenkombination-in-Windows_184968828.html

https://www.chip.de

Please reopen @JobcenterTycoon and people would be grateful if you could fix these issues.

newest ublock origin.

**Comment by JobcenterTycoon** [comment]
Fixed a hour ago already.

**Comment by ONE11111111ONE** [comment]
Please help again Sir @JobcenterTycoon :-)
IF he is not available anymore at the moment, it would be awesome to find a longterm solution, instead of quick fixes.
Cheers

EDIT: longterm ublock origin solutions, not 3rd party AdGuard Extra Plugin...they just use an AI to solve it, guys, you are more intelligent then this f... AI.

**Comment by JobcenterTycoon** [comment]
The private filter from https://github.com/uBlockOrigin/uAssets/issues/21504#issuecomment-1897043200 still working fine.

**Comment by ONE11111111ONE** [comment]
Why not adding them and make them available for everyone?

**Comment by JobcenterTycoon** [comment]
Because the website dev can change the website code. At the moment they only targeting filters which are in the filterlist.

**Comment by ONE11111111ONE** [comment]
To be honest, i would just risk in, in order to push yourself and others to find a permanent solution, if they block it again after some time..

**Comment by ONE11111111ONE** [comment]
![111](https://github.com/uBlockOrigin/uAssets/assets/150746073/f64fa695-75bb-4b72-a5e2-9ce89e3fcc5a)
![222](https://github.com/uBlockOrigin/uAssets/assets/150746073/a5ac01cf-4a15-4001-91df-bf1708702d5f)

**Comment by dimisa-RUAdList** [comment]
**uBlock filters – Quick fixes**

Typo: `www.chip.de###CR[class="Downloads-Getfile"] > #G32 > #M1 > [class="wrapper-safe"] > [class^="fb mt-"] > [class] > div[class]:has(a img[src*="https://im.chip.de/ii/"]`

**Comment by JobcenterTycoon** [comment]
Gor moved to base already, removed the obsolete quick filter now.

**Comment by ONE11111111ONE** [comment]
Sounds good, even it's a risk. I like it. I deleted your solution @JobcenterTycoon and reloaded the whole stuff. now it works also like a charm. thanks a lot Sir @gorhill

**Comment by big-cat-loaf** [comment]
The website is has ads now again link; https://www.chip.de/downloads/Firebug-Web-Developer-Tool_26579619.html.
