### ISSUE TITLE
playlegend.net: cookie notice

### ISSUE THREAD

**Issue by Janmm14** [uBlockOrigin/uAssets#21500]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://playlegend.net/news/`

### Category

nuisance

### Description

The cookie notice is not completely hidden, its visible above the footer of the page. using easylist + ubo cookie notices filters.

### Other extensions used

a bunch, but no other interfering content blocker. i am positive they do not intefere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 174357
 cosmetic: 95306
 scriptlet: 27541
 html: 1344
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  fanboy-cookiemonster: 49156-215, now
  ublock-annoyances: 6316-827, now
  adguard-spyware-url: 1363-92, now
  adguard-spyware: 81711-16812, now
  ublock-cookies-easylist: 816-0, now
 default:
  user-filters: 453-0, never
  ublock-filters: 37324-247, now
  ublock-badware: 7647-11, now
  ublock-privacy: 947-4, now
  ublock-unbreak: 2222-2, now
  easylist: 76103-361, now
  easyprivacy: 33123-34, now
  urlhaus-1: 12725-0, 1h.13m
  DEU-0: 7230-3, 1h.13m
  ublock-quick-fixes: 117-0, now
filterset (user): [array of 453 redacted]
trustedset:
 added: [array of 62 redacted]
 removed:
  about-scheme
  edge-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1082 ms (selfie)
 maxAssetCacheWait: 342 ms
popupPanel:
 blocked: 6
 network:
  playlegend.net: 5
  cloudflareinsights.com: 1
 extended:
  ###cookie-law-info-bar ~ .cli-modal-backdrop
  ###cookie-law-info-again
  ###cookie_hdr_showagain
```
</details>

**Comment by BlazeFTL** [comment]
Enable Adguard Cookie Notice Or Add
```
/cookie-law-info-public.js$script,1p,domain=playlegend.net

**Comment by Janmm14** [comment]
ok i enabled adguard cookie notice and its gone
