### ISSUE TITLE
primagames.com: detection

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#21508]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://primagames.com/tips/how-to-unlock-forbidden-peaks-chapter-3-in-legacy-of-the-moonspell-adventure-in-vampire-survivors`

### Category

detection

### Description

Detects adblock and shows a full size popup

### Other extensions used

Consent-O-Matic
Decentraleyes

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 94621
 cosmetic: 50720
 scriptlet: 24071
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
  urlhaus-1: null
 added:
  ublock-annoyances: 6359-11, 1h.22m
 default:
  user-filters: 16-0, never
  DEU-0: 7230-0, now
  easylist: 76103-23, 1h.22m
  easyprivacy: 33123-74, 1h.22m
  ublock-badware: 7648-138, 1h.22m
  ublock-filters: 36442-359, 1h.22m
  ublock-privacy: 951-11, 1h.22m
  ublock-quick-fixes: 100-5, 1h.22m
  ublock-unbreak: 2176-35, 1h.22m
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 37 redacted]
 removed:
  edge-scheme
hostRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 653 ms (selfie)
 maxAssetCacheWait: 425 ms
popupPanel:
 blocked: 14
 network:
  primagames.com: 1
  cdnral.com: 1
  chartbeat.com: 2
  googletagmanager.com: 2
  hallowedinvention.com: 2
  p-n.io: 1
  pub.network: 2
  scorecardresearch.com: 1
  succeedscene.com: 1
  wp.com: 1
 extended:
  ##.primis-player
  ##[data-freestar-ad]
```
</details>

**Comment by peace2000** [comment]
Hi, there's no detection if you enable Peter Lowe's list. It's a default list uBO uses. Please enable it back.

**Comment by peace2000** [comment]
Sorry my bad, I cleared cache and still reproduced the issue even after enabling back Lowe's list.

**Comment by JobcenterTycoon** [comment]
@Yuki2718 new admiral `||cmpworker.primagames.com^`

**Comment by Yuki2718** [comment]
> new admiral `||cmpworker.primagames.com^`

So far only this? We can use `/?pid=*&inject=true&environment=$script,1p,strict3p` but maybe better to gather examples.
