### ISSUE TITLE
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'

### ISSUE THREAD

**Issue by AndrewPixel** [uBlockOrigin/uAssets#21516]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I've been using uBO with Chrome on Windows 10 for several years now. On my computer I have IIS installed and use it for development

Recently, within the last few weeks, the Chrome Console has been throwing this warning:

`Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.`

I tried many things to address this and the only thing that works is disabling uBO. To me it looks like Chrome broke something.

### A specific URL where the issue occurs.

https://localhost/index.htm

### Steps to Reproduce

Launched web page via local IIS
https://localhost

### Expected behavior

No error to appear in console.

### Actual behavior

Error appears in console.

### uBO version

1.51.0

### Browser name and version

Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)

### Operating System and version

Windows 10 Pro 22H2

**Comment by sergeevabc** [comment]
I see the following errors in a Chromium-based browser console when `uBlock filters – Privacy` list is enabled in uBlock Origin development build 1.54.1rc2.
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
```

**Comment by iam-py-test** [comment]
Those errors indicate these tracking "features" have been disabled; they do not indicate a problem nor do they cause any harm.
However, you can disable the filters responsible. Please add the following to the My Filters tab:
```adblock
*$permissions=browsing-topics=(),from=~localhost,badfilter
*$permissions=join-ad-interest-group=(),from=~localhost,badfilter
*$permissions=run-ad-auction=(),from=~localhost,badfilter
*$permissions=attribution-reporting=(),from=~localhost,badfilter
```

Thank you

**Comment by sergeevabc** [comment]
@iam-py-test, indeed, your efforts helped to get rid of the mentioned messages in the log, but then I decided that privacy is above all. I just hope that companies like @Cloudflare, which offer protection from bots, will not consider disabling these features suspicious, because this has been happening [regularly](https://reddit.com/r/CloudFlare/search?q=loop&restrict_sr=on&sort=new&t=all).

**Comment by stephenhawk8054** [comment]
> Probably @krystian3w solution should be implemented - https://www.reddit.com/r/uBlockOrigin/comments/18mv93p/console_throws_errors_when_using_localhost_with/

I'll update the filters to be same as LAN block list

**Comment by Shnxxx** [comment]
Hi! I know it is already closed. But it just happens that right now, the mentioned issue, is occurring to me.

I have tried the steps above but to no avail.

Currently these lines are in "My Filters" :
```
*$permissions=browsing-topics=(),from=~localhost,badfilter
*$permissions=join-ad-interest-group=(),from=~localhost,badfilter
*$permissions=run-ad-auction=(),from=~localhost,badfilter
*$permissions=attribution-reporting=(),from=~localhost,badfilter
*$permissions=idle-detection=(),from=~localhost,badfilter
```

And this one: https://github.com/uBlockOrigin/uAssets/blob/master/filters/lan-block.txt

I'm still getting these (Already filtered to show "Blocked" only):
![image](https://github.com/uBlockOrigin/uAssets/assets/48496678/e346a30a-bef3-4e95-b0e9-d92aa18d2534)

Btw, I tried other servers, they are working. But this specific streaming server is much faster than the others. 

Any help would be much appreciated! Or am I doing it wrong?

**Comment by stephenhawk8054** [comment]
@Shnxxx Click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) and follow the troubleshoot and report steps there

**Comment by krystian3w** [comment]
Try disable latest version not version before added to domain more local addresses.

**Comment by beigexperience** [comment]
This is what I had to use on Brave Version 1.71.121 Chromium: 130.0.6723.91 

`*$permissions=browsing-topics=(),from=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local,badfilter
*$permissions=idle-detection=(),from=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local,badfilter
*$permissions=join-ad-interest-group=(),from=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local,badfilter
*$permissions=run-ad-auction=(),from=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local,badfilter
*$permissions=attribution-reporting=(),from=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local,badfilter
*$permissions=private-state-token-issuance=(),from=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local,badfilter
*$permissions=private-state-token-redemption=(),from=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local,badfilter`

**Comment by stephenhawk8054** [comment]
@beigexperience What issue are you having?

**Comment by mhidro** [comment]
@stephenhawk8054 I'm getting these warnings in the console on Brave in every site even Example.com, but only when ublock origin is enabled. 

![image](https://github.com/user-attachments/assets/d95c9752-5954-4a74-a913-108c2c39380a)

So far the solution for me was to put those filters up in a custom filters box

**Comment by stephenhawk8054** [comment]
@mhidro So, what are broken in the websites with those warnings?

**Comment by mhidro** [comment]
Nothing, it just spams the console on every page load and with persistant console its a lot of noise, I'm a dev. I don't need my console to be constantly spammed with warnings about some Chrome shit(excuse the langauge) when I'm using brave.

**Comment by stephenhawk8054** [comment]
Yeah, that's unavoidable when disabling these permissions. The issue in this thread is for the sites that have breakages with these filters.
