### ISSUE TITLE
tori.fi: breakage

### ISSUE THREAD

**Issue by kord1e** [uBlockOrigin/uAssets#21519]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tori.fi/`

### Category

breakage

### Description

Login doesn't work if ublock is enabled. (It sort of works but logs out immediately)

### Other extensions used

HTTPS Everywhere

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 120
filterset (summary):
 network: 305114
 cosmetic: 196499
 scriptlet: 49409
 html: 1354
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-136, 1m
  https://winhelp2002.mvps.org/hosts.txt: 8729-2, 1m
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76102-7479, 1m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95254-84591, 1m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1m
  adguard-generic: 81419-7123, 1m
  adguard-social: 22108-1434, 1m
  fanboy-thirdparty_social: 69-1, 1m
  fanboy-cookiemonster: 49185-17547, 1m
  fanboy-social: 16009-11627, 1m
  ublock-annoyances: 6387-14, 1m
  dpollock-0: 11614-1644, 1m
  [4 lists not shown]: [too many]
 default:
  user-filters: 16-0, never
  ublock-filters: 37719-491, 1m
  ublock-badware: 7666-16, 1m
  ublock-privacy: 948-5, 1m
  ublock-unbreak: 2228-5, 1m
  adguard-mobile: 8921-172, 1m
  easylist: 76162-17014, 1m
  easyprivacy: 33137-1089, 1m
  urlhaus-1: 10910-0, 1m
  plowe-0: 3783-329, 1m
  FIN-0: 2263-69, 1m
  ublock-quick-fixes: 132-0, 1m
filterset (user): [array of 16 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4505 ms (selfie)
 maxAssetCacheWait: 1152 ms
popupPanel:
 blocked: 6
 network:
  tori.fi: 1
  abtasty.com: 2
  adnxs.com: 1
  relevant-digital.com: 1
  tiqcdn.com: 1
 extended:
  ##+js(remove-class, sp-message-open, html, stay)
```
</details>

**Comment by mapx-** [comment]
@peace2000

**Comment by peace2000** [comment]
Hi, I cannot reproduce this. I can login and my account stays in. Please try to empty your browser cache. @kord1e

What other lists you have enabled?

`[4 lists not shown]: [too many]`

And how did you verify this?:

`I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.`
