### ISSUE TITLE
olx.com.pk: ads

### ISSUE THREAD

**Issue by creativrss** [uBlockOrigin/uAssets#21524]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.olx.com.pk/`

### Category

ads

### Description

I'm still seeing ads on this site.

### Other extensions used

<img width="1285" alt="Screenshot 2023-12-22 at 00 11 57" src="https://github.com/uBlockOrigin/uAssets/assets/90452541/76db2062-0163-47ef-afcd-3c11c506fc27">

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="2560" alt="Screenshot 2023-12-22 at 00 10 53" src="https://github.com/uBlockOrigin/uAssets/assets/90452541/aae349c9-ded5-475d-a704-6548cce6d5c0">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105566
 cosmetic: 44188
 scriptlet: 19753
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-1, never
  easylist: 76193-16, now
  easyprivacy: 33136-65, now
  plowe-0: 3785-1152, now
  ublock-badware: 7668-138, now
  ublock-filters: 36485-345, now
  ublock-privacy: 952-12, now
  ublock-quick-fixes: 110-5, now
  ublock-unbreak: 2177-33, now
  urlhaus-1: 10910-0, 1h.34m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 677 ms (selfie)
 maxAssetCacheWait: 364 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by mapx-** [comment]
add (to be reported at easylist repository)

`olx.com.pk##.react-swipeable-view-container:has([href*="http://onelink.to"])`

@ryanbr
