### ISSUE TITLE
app.hector.network: nuisance

### ISSUE THREAD

**Issue by GraciousGazelles** [uBlockOrigin/uAssets#21529]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://app.hector.network/`

### Category

nuisance

### Description

Annoying overlay that blocks the content on the site. Also annoying background that blurs content.
Both easily removed with the 'element zapper'.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 121
filterset (summary):
 network: 106624
 cosmetic: 44190
 scriptlet: 19754
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76196-16, now
  easyprivacy: 33136-65, now
  plowe-0: 3785-1152, now
  ublock-badware: 7668-138, now
  ublock-filters: 36487-345, now
  ublock-privacy: 952-12, now
  ublock-quick-fixes: 109-5, now
  ublock-unbreak: 2177-33, now
  urlhaus-1: 11970-0, now
filterset (user): [empty]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 254 ms (selfie)
 maxAssetCacheWait: 81 ms
popupPanel:
 blocked: 3
 network:
  cloudflareinsights.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by peace2000** [comment]
@MasterKia This is an annoyance, I think it should be fixed. Stuff like this would probably be fixed by Easylist - Notifications or Adguard - Popup overlays. But as trusted scriplets only work in our lists, our Annoyance list would be the correct place.

**Comment by peace2000** [comment]
Easylist Annoynce handles them as well: https://github.com/easylist/easylist/commit/a46ecd2ea41d35f3878af5d1fe7aae88ff830d10
