### ISSUE TITLE
pinterest.ca: breakage

### ISSUE THREAD

**Issue by jnnrss** [uBlockOrigin/uAssets#21525]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.pinterest.ca/kellylaufer7257/megans-bachelorette/`

### Category

breakage

### Description

All "pins" on the board, both sponsored and unsponsored, do no appear and page below the header is blank. 

### Other extensions used

Karma, 1pass, userzoom surveys, tampermonkey 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1439" alt="Screenshot 2023-12-21 at 20 35 30" src="https://github.com/uBlockOrigin/uAssets/assets/8398100/422691cf-a8af-4d8a-9b3c-e9df1fdb07e3">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105568
 cosmetic: 44186
 scriptlet: 19545
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37373-232, now
  ublock-badware: 7672-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2223-2, now
  ublock-quick-fixes: 126-0, now
  easylist: 76193-717, now
  easyprivacy: 33136-810, now
  urlhaus-1: 10910-0, now
  plowe-0: 3785-1, now
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 469 ms (selfie)
 maxAssetCacheWait: 283 ms
popupPanel:
 blocked: 1
 network:
  pinterest.com: 1
 extended:
  ##[data-grid-item]:has([aria-label]:not([aria-label*="pinterest"…
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce the issue

Does this work for you ?

`pinterest.*#@#[data-grid-item]:has([aria-label]:not([aria-label*="pinterest"])[href]:not([href^="/pin"]))`
