### ISSUE TITLE
vk.com: nuisance

### ISSUE THREAD

**Issue by sfilkex** [uBlockOrigin/uAssets#21522]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.vk.com/joomrussia`

### Category

nuisance

### Description

Signup/open mobile app in kiwi+ublock origin after scrolling+signup banner in the bottom of page

### Other extensions used

Ubo only

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231221-215213_Kiwi Browser](https://github.com/uBlockOrigin/uAssets/assets/154550872/459d44bb-eaa7-435a-ae72-b9c1375fe279)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium Mobile: 120
filterset (summary):
 network: 82862
 cosmetic: 88858
 scriptlet: 28807
 html: 0
listset (total-discarded, last-updated):
 removed:
  adguard-mobile: null
  easyprivacy: null
  plowe-0: null
  urlhaus-1: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25976-13120, 41m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1688-51, 41m
  https://secure.fanboy.co.nz/fanboy-mobile-notifications.txt: 2087-94, 41m
  fanboy-cookiemonster: 49185-17538, 41m
  ublock-annoyances: 6431-76, 41m
 default:
  user-filters: 1-0, never
  RUS-0: 40027-1027, 41m
  easylist: 76193-16065, 41m
  ublock-badware: 7662-138, 41m
  ublock-filters: 36841-597, 41m
  ublock-privacy: 952-18, 41m
  ublock-quick-fixes: 115-5, 41m
  ublock-unbreak: 2182-23, 41m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1538 ms (selfie)
 maxAssetCacheWait: 251 ms
popupPanel:
 blocked: 0
 extended:
  ##.PageBottomBanner--unauth.PageBottomBanner
  #@#+js(abort-on-property-read, Groups.showDisclaimer)
  #@#+js(abort-on-property-read, PageBottomBanners)
  #@#+js(abort-on-property-read, Unauthorized2)
  #@#+js(href-sanitizer, a[href*="/away.php?"], ?to)
  #@#+js(set-constant, noAdsAtAll, {})
```
</details>

**Comment by dportvine** [comment]
Why did you do this?

```adb
 #@#+js(abort-on-property-read, Groups.showDisclaimer)
 #@#+js(abort-on-property-read, PageBottomBanners)
 #@#+js(abort-on-property-read, Unauthorized2)
 #@#+js(href-sanitizer, a[href*="/away.php?"], ?to)
 #@#+js(set-constant, noAdsAtAll, {})
```

**Comment by dportvine** [comment]
@dimisa-RUAdList

**Comment by sfilkex** [comment]
He do only desktop lists, not mobile

**Comment by dimisa-RUAdList** [comment]
Some time ago, users of desktop versions of Firefox who opened VK mobile pages began sending complaints about breakdowns. As it turned out, using any scriptlet led to them, so I excluded them from working on mobile pages: https://github.com/easylist/ruadlist/commit/878832e557359bf759c240add629f52b771a2945

Perhaps it was a matter of the resource switching to a new design, or some temporary changes, I don’t know.

I returned the disabled rules as an experiment: https://github.com/easylist/ruadlist/commit/4ebba6e185f0d801b22c79b8c31e0b804d242baf
