### ISSUE TITLE
tek.no: ads

### ISSUE THREAD

**Issue by Schanzation** [uBlockOrigin/uAssets#21523]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tek.no/nyheter/nyhet/i/xgqbW8/tesla-skyldte-paa-kunder-for-feil-som-skyldtes-oedelagte-deler`

### Category

ads

### Description

ads. Where it say "Last ned Elton" is an ad

### Other extensions used

CanvasBlocker

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/19490515/f15bede8-4632-405d-82ca-d64a13372e4e)

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 215692
 cosmetic: 176841
 scriptlet: 45560
 html: 1348
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2516-1, now
  adguard-generic: 81414-6049, now
  adguard-spyware-url: 1365-200, now
  block-lan: 55-0, now
  curben-phishing: 79463-30, now
  fanboy-thirdparty_social: 69-0, now
  fanboy-cookiemonster: 49185-246, now
  fanboy-social: 16009-21, now
  ublock-annoyances: 6326-19, now
  NOR-0: 3805-11, now
  adguard-popup-overlays: 26665-712, now
  easylist-chat: 172-0, now
  [2 lists not shown]: [too many]
 default:
  user-filters: 18-0, never
  ublock-filters: 37376-308, 12m
  ublock-badware: 7667-11, 12m
  ublock-privacy: 948-52, now
  ublock-unbreak: 2223-3, 12m
  ublock-quick-fixes: 127-0, 12m
  easylist: 76193-762, now
  easyprivacy: 33136-889, now
  urlhaus-1: 10910-0, now
  plowe-0: 3785-1, now
filterset (user): [array of 18 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 798 ms (selfie)
 maxAssetCacheWait: 306 ms
popupPanel:
 blocked: 31
 network:
  tek.no: 1
  adnxs.com: 3
  confirmit.com: 2
  datadoghq-browser-agent.com: 1
  googletagmanager.com: 3
  medietall.no: 1
  schibsted.com: 13
  schibsted.io: 7
 extended:
  ##.adSpace
  ##main > div > section + div:last-of-type
  ##header ~ div > div:empty
  ##body::before
  ##main:style(min-height: unset !important)
  ##+js(abort-on-property-write, __AB__)
  ##+js(remove-attr, class, .dfp-loaded)
  ##body:style(overflow: auto !important;)
```
</details>

**Comment by mapx-** [comment]
report at regional repo
https://github.com/DandelionSprout/adfilt/issues
