### ISSUE TITLE
eatbook.sg: ads

### ISSUE THREAD

**Issue by extrange** [uBlockOrigin/uAssets#21533]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://eatbook.sg/edge-dinner-buffet/`

### Description

The ad from `answers.sg` is being shown inline.

### Other extensions used

Bitwarden
Firefox Multicontainers
Temporary Containers
Singlefile

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/29305375/8467a278-04b7-436c-8a94-288a1b5aa4ce)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 292234
 cosmetic: 243368
 scriptlet: 49385
 html: 1346
listset (total-discarded, last-updated):
 added:
  https://get.letsblock.it/list/b44dfc80-2a55-4994-b94e-27c43888c56e.txt: 27-1, 5h.12m
  adguard-generic: 81373-6947, 3d.4h.33m
  adguard-mobile: 8917-103, 3d.4h.33m
  adguard-spyware-url: 1362-92, 3d.4h.33m
  adguard-spyware: 81709-17040, 3d.4h.32m
  curben-phishing: 79700-30, 2h.54m
  adguard-social: 22101-875, 3d.4h.32m
  adguard-cookies: 28225-65, 3d.4h.32m
  ublock-cookies-adguard: 816-0, 4h.12m
  adguard-popup-overlays: 26629-1650, 3d.4h.32m
  adguard-mobile-app-banners: 4848-1070, 3d.4h.32m
  adguard-other-annoyances: 13966-332, 3d.4h.32m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37374-530, 5h.12m
  ublock-badware: 7672-11, 5h.12m
  ublock-privacy: 948-4, 5h.12m
  ublock-unbreak: 2223-3, 5h.12m
  ublock-quick-fixes: 126-0, 5h.12m
  easylist: 76196-1013, 5h.12m
  easyprivacy: 33136-982, 5h.12m
  urlhaus-1: 11970-0, 2h.54m
  plowe-0: 3778-1, 8d.21h.26m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3561 ms (selfie)
 maxAssetCacheWait: 2117 ms
popupPanel:
 blocked: 25
 network:
  eatbook.sg: 7
  ampproject.org: 4
  facebook.net: 4
  googlesyndication.com: 1
  googletagmanager.com: 3
  maps.googleapis.com: 1
  scorecardresearch.com: 1
  thesmartlocal.com: 1
  webpushr.com: 1
  wp.com: 2
 extended:
  ##.mashsb-container
  ##.mashsb-main
  ##.mashsb-box
  ##.mashicon-facebook
  ##.mashicon-twitter
  ##.social-widget
  ###fb-root:not(body):not(html)
  ##ins.adsbygoogle
  ##.grecaptcha-badge
  ##amp-ad
  ##amp-sticky-ad
  ##a[href^="https://www.facebook.com/sharer.php?"]
  ##a[href^="whatsapp://send"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer.php"]
  ##div[data-insertion]
  ##AMP-AD
  ##+js(set-constant, rwt, noopFunc)
  ##+js(trusted-set-cookie, SOCS, CAESHAgBEhJnd3NfMjAyMzA2MTItMF9S…
  ##+js(remove-attr, ping, div[id="search"] a[data-ved][ping])

```
</details>

**Comment by BlazeFTL** [comment]
Try
```
||answers.sg^$subdocument,domain=eatbook.sg

**Comment by okiehsch** [comment]
@ryanbr fyi
