### ISSUE TITLE
derstandard.de: detection

### ISSUE THREAD

**Issue by rejuce** [uBlockOrigin/uAssets#21534]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.derstandard.de/`

### Category

detection

### Description

reconised ublock, blocks access, also blocking page can not be removed with element blocker

### Other extensions used

audio only for youtube

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 119969
 cosmetic: 201385
 scriptlet: 31204
 html: 1348
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76102-7205, now
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95298-81611, now
  adguard-social: 22113-739, now
  fanboy-thirdparty_social: 68-0, now
  fanboy-cookiemonster: 49185-206, now
  fanboy-social: 16009-17, now
  ublock-annoyances: 6326-11, 9m
 default:
  user-filters: 4-0, never
  ublock-filters: 37357-266, 9m
  ublock-badware: 7667-11, 9m
  ublock-privacy: 948-4, 9m
  ublock-unbreak: 2222-0, 9m
  easylist: 76133-730, 9m
  easyprivacy: 33136-822, 9m
  urlhaus-1: 11970-0, 9m
  plowe-0: 3785-1, now
  DEU-0: 7236-3, 8m
  ublock-quick-fixes: 126-1, 9m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 28 redacted]
 removed:
  about-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 408 ms (selfie)
 maxAssetCacheWait: 206 ms
popupPanel:
 blocked: 16
 network:
  derstandard.de: 2
  doubleclick.net: 2
  googletagmanager.com: 2
  iocnt.net: 4
  npttech.com: 2
  staticfiles.at: 4
 extended:
  ##.tile-ad
  ###ad-slot-1
  ###ad-slot-2
  ###ad-slot-3
  ###ad-slot-4
  ###ad-slot-5
  ##.ad-active
  ##AD-SLOT
```
</details>

**Comment by BlazeFTL** [comment]
I Dont See Anything But Try
```
derstandard.de##+js(rmnt, script, __adblocker)

**Comment by rejuce** [comment]
![grafik](https://github.com/uBlockOrigin/uAssets/assets/28755821/6b2e4766-9b1f-4219-a1e9-d229424d6a21)


no change, its there since yesterday, before it was alright. It comes up after about 5sec on the page

**Comment by okiehsch** [comment]
This is a different top-level domain, `de` instead of `at`.
@rejuce does adding
`derstandard.de##+js(rpnt, script, "adsDisabled":false, "adsDisabled":true)`
to your filter list work for you?

**Comment by okiehsch** [comment]
Well, @ItsProfessional beat me to it.

**Comment by okiehsch** [comment]
No problem.

**Comment by rejuce** [comment]
> This is a different top-level domain, `de` instead of `at`. @rejuce does adding `derstandard.de##+js(rpnt, script, "adsDisabled":false, "adsDisabled":true)` to your filter list work for you?

unfortuantely not

**Comment by okiehsch** [comment]
Hm, seems to be a Firefox only issue,works fine on my end using Chrome but I can reproduce with Firefox.

**Comment by okiehsch** [comment]
Sure. @rejuce continue the discussionm in https://github.com/uBlockOrigin/uAssets/issues/21146
