### ISSUE TITLE
bitzite.com: detection

### ISSUE THREAD

**Issue by smaragdina** [uBlockOrigin/uAssets#21531]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://bitzite.com/how-to-get-paid-to-write-articles-from-home/`

### Category

detection

### Description

`https://bitzite.com/go/QRbR`

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium Mobile: 120
filterset (summary):
 network: 112320
 cosmetic: 37055
 scriptlet: 19844
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 34-0, never
  IDN-0: 9716-3888, now
  adguard-mobile: 8922-49, now
  easylist: 76196-16085, now
  easyprivacy: 33136-77, now
  plowe-0: 3785-1227, now
  ublock-badware: 7662-139, now
  ublock-filters: 36840-614, now
  ublock-privacy: 952-13, 1m
  ublock-quick-fixes: 103-5, 3m
  ublock-unbreak: 2182-36, 1m
  urlhaus-1: 11970-0, 1m
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3210 ms (selfie)
 maxAssetCacheWait: 430 ms
popupPanel:
 blocked: 16
 network:
  bitzite.com: 3
  bmcdn6.com: 2
  d3u598arehftfk.cloudfront.net: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  headerbidding.ai: 3
  pixfuture.com: 4
  purdasseer.com: 1
 extended:
  ##+js(noeval-if, deblocker)
  ##+js(no-fetch-if, googlesyndication)
  ##+js(noeval-if, /chp_?ad/)
  ##+js(abort-on-property-read, adsBlocked)
  ##+js(addEventListener-defuser, load, htmls)
  ##+js(remove-attr, href, .MyAd > a[target="_blank"])
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by BlazeFTL** [comment]
Copy In My Filters
```
bitzite.com##+js(aeld, DOMContentLoaded, antiAdBlockerHandler)
bitzite.com##+js(noeval-if, chp_ad)
bitzite.com##center, .modal-overlay
bitzite.com##form > div[id], [id*="wpsafe"]:style(display: block !important;)

**Comment by okiehsch** [comment]
Adding
`bitzite.com##+js(nano-sib, timer)`
will boost the timer and save you a few minutes waiting time.
You have to click the "Step*/5" modals to continue.

**Comment by smaragdina** [comment]
thank's bro
