### ISSUE TITLE
ad4msan.win [Anti-adblock]

### ISSUE THREAD

**Issue by chelseaislan** [uBlockOrigin/uAssets#2153]
### URL(s) where the issue occurs
https://ad4msan.win/safe?url=aHR0cHM6Ly9saW5rLnNhZmVsaW5rY29udmVydGVyLmNvbS9yZXZpZXcucGhwP2lkPWFIUjBjSE02THk5bktDZ3VaMnd2TVd0dE9EWjYmYz0xJnVzZXI9NTQwOTc=

### Describe the issue
Anti-adblock

### Screenshot(s)
![screenshot 70](https://user-images.githubusercontent.com/30471081/39500954-52f5e5e4-4de2-11e8-811a-a70680214872.png)
![screenshot 71](https://user-images.githubusercontent.com/30471081/39500955-532e2d14-4de2-11e8-892a-75256b2d59be.png)

### Versions

- Browser/version: Chrome 66
- uBlock Origin version: 1.16.2

### Settings
Default settings

**Comment by zaphodbeebblebrox** [comment]
`||ad4msan.win/wp-content/plugins/adunblocker/*$script,first-party`

**Comment by KiLL4FuNK** [comment]
Anti-adblock

`https://ad4msan.win/karbohidrat`
