### ISSUE TITLE
ubereats.com: ads

### ISSUE THREAD

**Issue by TheOddball** [uBlockOrigin/uAssets#21530]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://ubereats.com/orders/`
(Order UID)

### Description

On the "track an order" page, there is a video ad shown.

Blocking `##.dw.ec` successfully blocks this ad.

### Other extensions used

Dark Reader

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/16966979/07f3bdc2-b191-4eec-b6ca-5de5f4fb25e7)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 106629
 cosmetic: 44191
 scriptlet: 19545
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37374-232, 1h.56m
  ublock-badware: 7672-11, 1h.56m
  ublock-privacy: 948-4, 1h.56m
  ublock-unbreak: 2223-2, 1h.56m
  ublock-quick-fixes: 126-0, 1h.56m
  easylist: 76196-717, 1h.56m
  easyprivacy: 33136-810, 1h.56m
  urlhaus-1: 11970-0, 4m
  plowe-0: 3785-1, 4m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1022 ms (selfie)
 maxAssetCacheWait: 242 ms
popupPanel:
 blocked: 13
 network:
  github.com: 13
```
</details>

**Comment by mapx-** [comment]
report directly at easylist repository
