### ISSUE TITLE
serially.it: breakage

### ISSUE THREAD

**Issue by DunkinCoon** [uBlockOrigin/uAssets#21532]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

serially.it

### Category

breakage

### Description

When playing videos, it will not load the actual video, just stuck loading; if you turn off uBlock it will start to play with ads.

The service itself is free, but requires an account. I can provide one if needed.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 119241
 cosmetic: 202900
 scriptlet: 31108
 html: 1344
listset (total-discarded, last-updated):
 added:
  adguard-social: 22107-881, 1d.4h.34m
  adguard-cookies: 28228-63, 1d.4h.33m
  ublock-cookies-adguard: 762-0, 5d.4h.42m
  adguard-popup-overlays: 26658-1646, 1d.4h.33m
  adguard-mobile-app-banners: 4851-1070, 1d.4h.33m
  adguard-other-annoyances: 13970-594, 1d.4h.33m
  adguard-widgets: 2377-1, 1d.4h.32m
  fanboy-thirdparty_social: 68-0, 5d.4h.42m
  easylist-annoyances: 4246-124, 5d.4h.42m
  easylist-chat: 168-12, 5d.4h.42m
  fanboy-cookiemonster: 49096-3817, 5d.4h.42m
  ublock-cookies-easylist: 762-762, 5d.4h.42m
  [5 lists not shown]: [too many]
 default:
  user-filters: 5-0, never
  ublock-filters: 37355-227, 4h.30m
  ublock-badware: 7672-11, 4h.29m
  ublock-privacy: 945-4, 5d.4h.43m
  ublock-unbreak: 2223-1, 4h.29m
  ublock-quick-fixes: 126-6, 1h.28m
  easylist: 75744-802, 5d.4h.43m
  easyprivacy: 33114-902, 5d.4h.43m
  urlhaus-1: 11970-0, 3h.29m
  plowe-0: 3781-1, 5d.4h.43m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1927 ms (selfie)
 maxAssetCacheWait: 251 ms
```

</details>

**Comment by mapx-** [comment]
add & test

`@@||sdk.privacy-center.org^$script,domain=serially.it`

There are video ads too, I'm able to block them only in chrome, Idk why in firefox does not work

```
serially.it##+js(xml-prune, xpath(//*[name()="Period"][.//*[name()="BaseURL" and contains(text()\,'/ad/')]]), , .mpd)
serially.it##+js(json-prune, ads)
```

**Comment by mapx-** [comment]
@Alex-302 the videos are broken due to 
`||privacy-center.org^`
