### ISSUE TITLE
[nsfw] agitwebtoon.xyz: ads

### ISSUE THREAD

**Issue by pololoduck** [uBlockOrigin/uAssets#21535]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://agitwebtoon.xyz/azi_toon/14798.html`

### Category

ads

### Description

All the flashing ads still show up. I've already purged cache and I have KR filters active. 

### Other extensions used

google translate

### Screenshot(s)

<details>

<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/121998563/ef8c7dc3-ce56-41aa-9347-fbf7dee8eef8)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 165221
 cosmetic: 263531
 scriptlet: 49552
 html: 0
listset (total-discarded, last-updated):
 added:
  CHN-0: 25416-134, 1m
  FIN-0: 2248-0, 1m
  JPN-1: 13942-11, 1m
  KOR-1: 4912-12, 1m
  adguard-cookies: 28230-30, 1m
  adguard-generic: 81417-538, 1m
  adguard-mobile-app-banners: 4855-13, 1m
  adguard-other-annoyances: 13974-19, 1m
  adguard-popup-overlays: 26666-95, 1m
  adguard-social: 22113-927, 1m
  adguard-widgets: 2377-4, 1m
  dpollock-0: 11615-56, 1m
  [9 lists not shown]: [too many]
 default:
  user-filters: 9-1, never
  easylist: 76196-2016, now
  easyprivacy: 33136-419, now
  plowe-0: 3785-1554, now
  ublock-badware: 7668-327, now
  ublock-filters: 36486-4060, now
  ublock-privacy: 952-16, now
  ublock-quick-fixes: 109-5, now
  ublock-unbreak: 2177-108, now
  urlhaus-1: 11970-0, now
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 642 ms (selfie)
 maxAssetCacheWait: 506 ms
popupPanel:
 blocked: 0
```
</details>

**Comment by BlazeFTL** [comment]
Add In My Filters
```
agitwebtoon.xyz##.advx.banner

**Comment by piquark6046** [comment]
I will check it today (KST and JST).
