### ISSUE TITLE
rsshort.com: detection

### ISSUE THREAD

**Issue by Kamany89** [uBlockOrigin/uAssets#21549]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

Shortener URL: `rsshort.com/GR8S5kCZFWS`
Domains the shortener uses: `rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com`

### Description

They detected ublock and redirect to another page 'rsgamer.app/youhere.html'

### Other extensions used

Tampermonkey (but this happen when i close it)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 12-24](https://github.com/uBlockOrigin/uAssets/assets/154012912/f5b1941c-af93-4ecb-94d8-fbddf208d7f2)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by huyszn** [comment]
For the anti-adb and speed up timer
```
rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com##+js(set, isRequestPresent, true)
rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com##+js(nano-sib)
```

For annoyances like anti right-click, dev tools, f-keys
```
rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com##+js(aeld, contextmenu)
rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com##+js(set, document.onkeydown, null)
rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com##+js(nowoif)
rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com##+js(nosiif, _0x)
```

**Comment by Kamany89** [comment]
@huyszn thank you sir This helped me a lot

**Comment by Kamany89** [comment]
hello 
the problem still detected and redirect to 'rsgamer.app/youhere.html' today
same issues above 
Shortener URL: 'rsshort.com/GR8S5kCZFWS'

Domains the ![Screenshot 12-24](https://github.com/uBlockOrigin/uAssets/assets/154012912/850794fe-2228-4487-a24b-3c69fd44f96e) uses: rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com

**Comment by D4niloMR** [comment]
Fixed.

**Comment by Kamany89** [comment]
Yes works fine now 
Thank you very much
Is there a solution to this problem as well ?
This one even blocks advertising but the continue button is not showing how can i show button
'earnow.online/ZwCoUB'

**Comment by D4niloMR** [comment]
this filter works?

`*$csp=style-src *,domain=blog.coinscap.info|blog.cryptowidgets.net|blog.insurancegold.in|blog.wiki-topia.com,badfilter`

**Comment by Kamany89** [comment]
no sir, still hidden

**Comment by D4niloMR** [comment]
test these:

```adb
cryptowidgets.net,insurancegold.in,wiki-topia.com##+js(rpnt, script, window.location.href = "/detected.html";)
blog.cryptowidgets.net,blog.insurancegold.in,blog.wiki-topia.com##center > [style] > [id]:style(display: block !important;)
@@||cdn.bmcdn6.com^$script,xhr,domain=cryptowidgets.net|wiki-topia.com|insurancegold.in
*$csp=style-src *,domain=blog.coinscap.info|blog.cryptowidgets.net|blog.insurancegold.in|blog.wiki-topia.com,badfilter
```

**Comment by Kamany89** [comment]
Unfortunately it doesn't work either

**Comment by huyszn** [comment]
The filters work to stop the redirect and I was able to go to step 2. I am stuck on step 2 because the`GO TO STEP 3` button doesn't respond.

**Comment by Kamany89** [comment]
I tested on Firefox but the buttons are completely stuck

**Comment by D4niloMR** [comment]
maybe whitelisting the current filters?

```adb
cryptowidgets.net,wiki-topia.com#@#.floating-banner
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#^script:has-text(adsBlocked)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(acs, document.createElement, adsBlocked)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(ra, disabled, .btn-primary)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#input[type="hidden"]:style(display: block !important;)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(acs, document.getElementById, location.replace)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(aeld, load, htmls)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#^script:has-text(htmls)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(aost, document.createElement, onload)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(nostif, replaceHTMLWithMessage)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(aopr, PerformanceObserver)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(refresh-defuser)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(nostif, , 2500)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(aost, HTMLBodyElement.prototype.removeChild, onload)
*$script,1p,replace=/window\.location\.assign\("\/detected\.html"\);/""/g,domain=coinscap.info|cryptowidgets.net|greenenez.com|insurancegold.in|webfreetools.net|wiki-topia.com,badfilter
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@##countdown ~ :not(center)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#.fa-xmark
*$csp=style-src *,domain=blog.coinscap.info|blog.cryptowidgets.net|blog.insurancegold.in|blog.wiki-topia.com,badfilter
cryptowidgets.net#@#+js(nostif, check, 1)
cryptowidgets.net#@#+js(rmnt, script, adBlockDetected)
cryptowidgets.net#@#^script[data-script='CallAdBlock-script']:has-text(adBlockDetected)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(nostif, /bait|detected/)
coinscap.info,cryptowidgets.net,greenenez.com,insurancegold.in,webfreetools.net,wiki-topia.com#@#+js(set, navigator.brave, undefined)
```

**Comment by huyszn** [comment]
Using the new filters while whitelisting the current filters works

**Comment by Kamany89** [comment]
@huyszn please explain to me what should i do now ?

**Comment by D4niloMR** [comment]
Put the filters above in "My filters" and test

**Comment by Kamany89** [comment]
@D4niloMR i try it now but still hidden 'i.ibb.co/nnTWqYv/Screenshot-2023-12-28-061835.png' (chrome)
and firefox stuck also
maybe something wrong with me

**Comment by huyszn** [comment]
It's working fine for me
<img width="1440" src="https://github.com/uBlockOrigin/uAssets/assets/46979193/952ffbc3-4810-47b7-b354-edf3de2897b5">

**Comment by D4niloMR** [comment]
@Kamany89 try in a new browser profile, without custom filters/lists.

**Comment by Kamany89** [comment]
@D4niloMR after i create new profile its working very good 
but why not working with my current profile ?

**Comment by D4niloMR** [comment]
The cause can be your own filters, external lists, other extensions, bad settings, cookies etc

Save what you want to keep and reset to default.

**Comment by Kamany89** [comment]
I have now removed everything related to these sites from my filters
I just added these codes and now the result works very well
@D4niloMR Thank you for helping me and best regards

**Comment by Kamany89** [comment]
@D4niloMR Sorry for the inconvenience again. Do these filters also work on his brothers
'shortino.link/8ugNl'
'shortano.link/g29awgvl'
@ItsProfessional But I posted this problem two days ago and did not receive a response

**Comment by Kamany89** [comment]
@ItsProfessional thanks sir i understand now 
earnow works fine but Shortino/shortano the buttons do not appear

**Comment by Kamany89** [comment]
no, i update it and wait 10 min 
this is result
'i.ibb.co/jH4L3Ln/shortano.png'
'i.ibb.co/Rhz9dJw/shortno.png'

**Comment by Kamany89** [comment]
@ItsProfessional all works fine now but in shortano only detect adblock in coinsvalue.(net) and cookinguide(net)
https://i.ibb.co/Wgn7MLV/fixit.png

**Comment by D4niloMR** [comment]
This site(earnow) is broken on FF, uBO off and it still detects. These filters fix it though.

btw, I'm not sure why, but on FF I can't get past step 2 on shortino/shortano

**Comment by Kamany89** [comment]
all sites now say 'Disable AdBlocker to continue'

**Comment by Kamany89** [comment]
some time i refresh page and works fine

**Comment by vasyok-92** [comment]
> 

doesn't work for me

**Comment by D4niloMR** [comment]
> **link=** `rsshort.com/GR8S5kCZFWS`
> 
> `rsadnetworkinfo.com,rsinsuranceinfo.com,rsfinanceinfo.com,rsgamer.app,rssoftwareinfo.com,rshostinginfo.com,rseducationinfo.com##+js(adjust-setInterval, count, *, 0.001)`
> 
> cause=> page don't forward from step 1 to 6 anyone confirming?

same here

**Comment by vasyok-92** [comment]
> > > 
> > 
> > 
> > doesn't work for me
> 
> what does not work? describe your issue in step

pressing the button on any step returns to the same page with the same step faster than 20 seconds, the short can be passed only if you wait ~20 seconds per step.

**Comment by Kamany89** [comment]
@ghajini Is the update available for the rsshort problem?

**Comment by Kamany89** [comment]
@ghajini this issues not from ublock "you must wait 15 second before click if you clicked before 15 second the button will not work
Thanks sir

**Comment by kasya55** [comment]
Who can tell me how to solve the problem with rsshort? Stopped clicking on buttons.

**Comment by Kamany89** [comment]
@kasya55 try to remove all filter and update your lists 
and wait 15 sec before clicking on button

**Comment by kasya55** [comment]
Can you send me the completed configuration file?

**Comment by kasya55** [comment]
Today this message appeared. 
 - You Already Visited Our link 20 times today please come back tommorrow.
 How to get around this? Links RSS

**Comment by Kamany89** [comment]
@kasya55 this is rules for rsshort links, not from ubo

**Comment by kasya55** [comment]
When passing rsshort, this began to appear: Bypass/Suspicious activity detected please turn off bypass script or adblocker and open link again! At the same time, Bypass/Suspicious is disabled. Help me how to bypass it.

**Comment by Kamany89** [comment]
@kasya55 This will happen when you click on button without stay at least 10 sec

**Comment by kasya55** [comment]
10 seconds doesn't help.

**Comment by kasya55** [comment]
Apparently no one will help me. By passing rsshort

**Comment by kasya55** [comment]
`в чем проблема? ссылка?`
I wrote everything above. rsshort links cannot be followed. At any step, the following message may pop up: Bypass/Suspicious activity detected please turn off bypass script or adblocker and open link again!
   Need help on how to solve this problem?

**Comment by natandna** [comment]
rsshort bypass detection,
 anyone can help?

**Comment by ItsProfessional** [comment]
#17361
