### ISSUE TITLE
cricbuzz.com: ads

### ISSUE THREAD

**Issue by Malgotra** [uBlockOrigin/uAssets#21542]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.cricbuzz.com/`

### Category

ads

### Description

Ads leftover

### Other extensions used

No

### Screenshot(s)

https://github.com/uBlockOrigin/uAssets/assets/122884037/46657358-00e8-41d3-8367-736eefbd55bf

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 135363
 cosmetic: 172448
 scriptlet: 44569
 html: 1349
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81455-5971, 5m
  easylist-annoyances: 4272-97, 5m
  easylist-chat: 175-0, 6m
  fanboy-cookiemonster: 49201-235, 6m
  ublock-cookies-easylist: 859-0, 6m
  easylist-newsletters: 6809-13, 6m
  easylist-notifications: 2894-4, 6m
  fanboy-social: 16011-7, 6m
  ublock-annoyances: 6395-892, 6m
  IND-0: 12965-2, 6m
 default:
  user-filters: 0-0, never
  ublock-filters: 37750-288, 4m
  ublock-badware: 7692-11, 4m
  ublock-privacy: 948-4, 4m
  ublock-unbreak: 2228-2, 4m
  ublock-quick-fixes: 136-0, 5m
  adguard-mobile: 8924-113, 5m
  easylist: 76263-788, 5m
  easyprivacy: 33152-907, 5m
  urlhaus-1: 11470-0, 5m
  plowe-0: 3787-1, 6m
filterset (user): [empty]
userSettings:
 ignoreGenericCosmeticFilters: false
 showIconBadge: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 897 ms
 maxAssetCacheWait: 327 ms
popupPanel:
 blocked: 5
 network:
  cricbuzz.com: 1
  doubleclick.net: 1
  google.com: 2
  googletagmanager.com: 1
```
</details>

**Comment by mapx-** [comment]
report at easylist repository or at AdGuard repo (for the mobile list)

`m.cricbuzz.com##div.bg-cbLightGrayish.items-center.justify-center`

@ryanbr @Alex-302
