### ISSUE TITLE
garticphone.com: ads

### ISSUE THREAD

**Issue by TheZipCreator** [uBlockOrigin/uAssets#21546]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://garticphone.com/`

### Category

ads

### Description

When joining a room, pressing play opens an ad.

### Other extensions used

dark reader, decentraleyes, privacy badger, I don't care about cookies

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 115
filterset (summary):
 network: 106251
 cosmetic: 44212
 scriptlet: 19565
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 17-2, never
  ublock-filters: 37355-226, now
  ublock-badware: 7698-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2223-1, now
  ublock-quick-fixes: 136-6, now
  easylist: 76263-240, now
  easyprivacy: 33152-87, now
  urlhaus-1: 11470-0, now
  plowe-0: 3787-1154, now
filterset (user): [array of 17 redacted]
switchRuleset:
 added: [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 825 ms (selfie)
 maxAssetCacheWait: 248 ms
popupPanel:
 blocked: 31
 network:
  3lift.com: 2
  4dex.io: 2
  adinplay-venatus.workers.dev: 1
  adnxs.com: 2
  amazon-adsystem.com: 1
  bidswitch.net: 2
  btloader.com: 1
  casalemedia.com: 1
  doubleclick.net: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  indexww.com: 1
  media.net: 1
  onetag-sys.com: 2
  openx.net: 2
  pubmatic.com: 2
  rubiconproject.com: 2
  script.ac: 1
  servenobid.com: 2
  the-ozone-project.com: 1
  unrulymedia.com: 1
  yellowblue.io: 1
 extended:
  ##.jsx-3256658636
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  #@#[id^="google_ads_iframe"]
```
</details>

**Comment by mapx-** [comment]
room ? 

I see a start button, clicking it => an adevertisement

add & test

`||garticphone.com/videos/gio.mp4$media,1p,redirect=noopmp3-0.1s`

**Comment by u-RraaLL** [comment]
A reddit user confirms the filter is working: https://www.reddit.com/r/uBlockOrigin/comments/18pgb6s/garticphonecom_doesnt_block_ads_fully/

Should probably be committed even if OP here doesn't answer.
