### ISSUE TITLE
raspians.com: ads

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#21547]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://raspians.com/how-to-enable-vnc-on-raspberry-pi/`

### Category

ads

### Description

Ad banners appear.

When I remove them with the element picker they keep showing up when I refresh the page.

### Other extensions used

none

### Screenshot(s)

![report](https://github.com/uBlockOrigin/uAssets/assets/149429107/5642cf1c-1ad6-4d1a-8bd1-8284e6b29d45)

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 119
filterset (summary):
 network: 183187
 cosmetic: 197349
 scriptlet: 31930
 html: 1348
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1369-92, now
  adguard-spyware: 81721-16930, now
  adguard-social: 22121-874, now
  adguard-cookies: 28235-63, now
  ublock-cookies-adguard: 821-0, now
  adguard-popup-overlays: 26671-1596, now
  adguard-mobile-app-banners: 4854-9, now
  adguard-other-annoyances: 13975-327, now
  adguard-widgets: 2381-1, now
  fanboy-thirdparty_social: 69-0, now
  easylist-annoyances: 4272-44, now
  easylist-chat: 175-12, now
  [7 lists not shown]: [too many]
 default:
  user-filters: 4-0, never
  ublock-filters: 37355-581, now
  ublock-badware: 7698-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2223-3, now
  ublock-quick-fixes: 136-0, 16m
  easylist: 76263-754, now
  easyprivacy: 33152-905, now
  urlhaus-1: 11470-0, now
  plowe-0: 3787-1, now
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1287 ms
 maxAssetCacheWait: 924 ms
popupPanel:
 blocked: 89
 network:
  raspians.com: 32
  affilimate.io: 1
  amazon-adsystem.com: 4
  doubleclick.net: 1
  ezodn.com: 8
  ezoic.com: 2
  ezoic.net: 30
  gatekeeperconsent.com: 4
  googlesyndication.com: 1
  googletagmanager.com: 1
  gravitec.net: 1
  imasdk.googleapis.com: 1
  mailerlite.com: 2
  pubmatic.com: 1
 extended:
  ##[data-ez-name]
  ##span[data-ez-ph-id]
  ##span[id^="ezoic-pub-ad-placeholder-"]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ezoic-adpicker-ad
  ##.abh_social
  ###ezmobfooter
  ##div.ezmob-footer
  ##.ezmob-footer
  ##.ezoic-floating-bottom
  ##.ezo_ad
  ##.ezmob-footer-desktop
  ###ez-sidebar-wall-left
  ##.ez-sidebar-wall-ad
  ##.ezoic-ad
  ##.adtester-container
  ##ins.adsbygoogle
  ##.ez-video-wrap
  #@#[id^="div-gpt-ad"]
  #@#.ad-unit
  #@#.banner-ads
  #@#.banner_ads
  #@#.ad-zone
  #@#.ad-space
```
</details>

**Comment by mapx-** [comment]
add

`raspians.com##.widget:has([href]):not(*:has([href*="raspians.com"]))`

@ryanbr

**Comment by Dani-1-2** [comment]
> add
> 
> `raspians.com##.widget:has([href]):not(*:has([href*="raspians.com"]))`
> 
> @ryanbr
