### ISSUE TITLE
msn.com: ads

### ISSUE THREAD

**Issue by ChaseKnowlden** [uBlockOrigin/uAssets#21544]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.msn.com/en-us/feed?ocid=hpmsn`

### Category

ads

### Description

When I am on Microsoft Edge, when on the carousel element, there is ads on the carousel, even with default settings.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/46290258/5b559e91-65b3-471b-99c3-78338c3b3517)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 106228
 cosmetic: 44200
 scriptlet: 19765
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76250-16, 1h.3m
  easyprivacy: 33152-65, 1h.3m
  plowe-0: 3787-1153, now
  ublock-badware: 7694-138, 1h.3m
  ublock-filters: 36506-346, 1h.3m
  ublock-privacy: 952-12, 1h.3m
  ublock-quick-fixes: 119-5, 1h.3m
  ublock-unbreak: 2177-33, 1h.3m
  urlhaus-1: 11470-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 812 ms (selfie)
 maxAssetCacheWait: 236 ms
popupPanel:
 blocked: 47
 network:
  msn.com: 28
  adnxs.com: 5
  azure.com: 2
  bing.com: 10
  btloader.com: 1
  scorecardresearch.com: 1
 extended:
  ##display-ads
  ##+js(remove-cookie, MicrosoftApplicationsTelemetryDeviceId)
```
</details>

**Comment by mapx-** [comment]
duplicate
https://github.com/uBlockOrigin/uAssets/issues/16330#issuecomment-1382715214
