### ISSUE TITLE
gsmarena.com: breakage

### ISSUE THREAD

**Issue by b70386** [uBlockOrigin/uAssets#21555]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.gsmarena.com/xiaomi_redmi_pad-pictures-11911.php`

### Category

breakage

### Description

cannot see the 3D images from all devices in gsmarena website

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Xiaomi-Redmi-Pad-pictures-official-photos](https://github.com/uBlockOrigin/uAssets/assets/91832361/8308def2-1e8c-4cca-9f6e-d3ee23009f59)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105978
 cosmetic: 44224
 scriptlet: 19778
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 45-4, never
  easylist: 76300-16, 16m
  easyprivacy: 33156-65, 16m
  plowe-0: 3787-1153, now
  ublock-badware: 7699-138, 28m
  ublock-filters: 36477-296, 16m
  ublock-privacy: 952-12, 28m
  ublock-quick-fixes: 120-5, 28m
  ublock-unbreak: 2177-33, 28m
  urlhaus-1: 11135-0, now
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3864 ms (selfie)
 maxAssetCacheWait: 607 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  uniconsent.com: 1
 extended:
  ###topAdv
  ##.ad-c-label
  ##.ad-top
  ##.ad-label
  ###subHeader
  ##div[id^="crt-"][style]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by mapx-** [comment]
> user-filters: 45-4

try disabling all your custom filters and test again
