### ISSUE TITLE
lowcygier.pl: detection

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uAssets#21554]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

Example article link : 

`https://lowcygier.pl/darmowe/wyrusz-na-postapokaliptyczne-pustkowia-kolejny-tytul-do-odebrania-za-darmo-w-epic-games-store/`

### Description

Anti-adblock in articles (on the right) :
- https://github.com/AdguardTeam/AdguardFilters/issues/169142#issuecomment-1868491976

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ss](https://cdn.adguard.info/sitereports/hlo47m4fw80k0k48g0o00sg44wssocgqi9abijg3io.png?nc=1)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBO dev, Firefox/Opera, default lists

```
</details>

**Comment by mapx-** [comment]
is it about only an annoyance / warning ?

test

`lowcygier.pl##+js(rmnt, script, 'error')`

**Comment by garry-ut99** [comment]
I'm not sure, but it seems just an annoyance.
The provided filter works.

Also I overlooked a fact it's already fixed by `AdGuard – Popup Overlays` list : https://github.com/AdguardTeam/AdguardFilters/issues/169142#issuecomment-1868510755, thus I'm not sure whether it's supposed to be fixed again in `uBO Annoyances`, I only remember that hard anti-adblocks which are fixed in `AdGuard – Ads ` are still fixed in `uBlock filters – Ads` as well, so by the same logic, then maybe annoyance-anti-adblocks which are already fixed in `AdGuard – Annoyances` are to be fixed in `uBlock filters – Annoyances` as well, unfortunately I don't remember the rules.

**Comment by mapx-** [comment]
soft detection has to be fixed in uBO annoyances list
