### ISSUE TITLE
Tubitv Detection

### ISSUE THREAD

**Issue by chabuco** [uBlockOrigin/uAssets#21559]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://tubitv.com/movies/557519/after-earth`

### Description

UBlock Orign gets detected
I tried adding the filter here: https://github.com/uBlockOrigin/uAssets/issues/21414#issuecomment-1856619528
but still doesn't work.

### Other extensions used

Go Back with Space

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![tubi](https://github.com/uBlockOrigin/uAssets/assets/102320635/6075484d-ea73-4eec-9fa5-9f74f12b2eb4)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by mapx-** [comment]
go to uBO dashboard, support tab, copy & paste here: Troubleshooting Information

**Comment by chabuco** [comment]
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 125035
 cosmetic: 53337
 scriptlet: 19910
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  FRA-0: 28894-39, 11h.56m
  easylist: 76300-80, 11h.56m
  easyprivacy: 33156-331, 11h.56m
  plowe-0: 3787-1164, 11h.57m
  ublock-badware: 7694-153, 11h.57m
  ublock-filters: 36472-370, 11h.57m
  ublock-privacy: 952-12, 11h.57m
  ublock-quick-fixes: 119-5, 11h.57m
  ublock-unbreak: 2177-37, 11h.57m
  urlhaus-1: 11135-0, 11h.57m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 619 ms
 maxAssetCacheWait: 209 ms

**Comment by mapx-** [comment]
@smed79 you should remove this bait:

`/cdn.*/ads.`

**Comment by chabuco** [comment]
excuse my ignorance but how?

**Comment by mapx-** [comment]
@chabuco for the moment add this filter in "my filters"

`/cdn.*/ads.$badfilter`

**Comment by chabuco** [comment]
It works! Thanks a lot.
