### ISSUE TITLE
gamedrive.org: detection

### ISSUE THREAD

**Issue by AfsalBaaqirA** [uBlockOrigin/uAssets#21553]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://gamedrive.org/`

### Category

detection

### Description

It detects the uBlock origin, and showing please disable the adblocker to use this site

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/93435400/7ec1f933-2008-4598-99ed-33323c7cf8d5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105940
 cosmetic: 44215
 scriptlet: 19778
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 76300-16, now
  easyprivacy: 33156-65, now
  plowe-0: 3787-1153, now
  ublock-badware: 7694-138, now
  ublock-filters: 36475-296, now
  ublock-privacy: 952-12, now
  ublock-quick-fixes: 120-5, now
  ublock-unbreak: 2177-33, now
  urlhaus-1: 11135-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 7 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1283 ms (selfie)
 maxAssetCacheWait: 300 ms
popupPanel:
 blocked: 9
 network:
  gamedrive.org: 1
  d3qygewatvuv28.cloudfront.net: 1
  doubleclick.net: 1
  googlesyndication.com: 4
  googletagmanager.com: 1
  wp.com: 1
 extended:
  ##+js(abort-current-script, eval, replace)
```
</details>

**Comment by dimisa-RUAdList** [comment]
<details>
<summary>Screenshot(s)</summary>

<img width="1155" height="310" alt="Image" src="https://github.com/user-attachments/assets/622c31d7-b1cb-4379-b080-5176e5c87c8e" />

</details>
