### ISSUE TITLE
citationmachine.net - Anti-Adblock script

### ISSUE THREAD

**Issue by SheepKid12** [uBlockOrigin/uAssets#2155]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`www.citationmachine.net/items/new`

### Describe the issue

After doing 2 citations on the site, you are forced to disable your adblocker.
### Screenshot(s)

![3d68cdf9-1d4a-4d4b-9f0c-bb32d788126e](https://user-images.githubusercontent.com/8013408/39527535-4560e28a-4de7-11e8-8ae3-98698043beb5.png)

### Versions

- Browser/version: Chrome OS 63.0.3239.140 (my school locks the chromebooks to this version)
- uBlock Origin version: 1.16.2

### Settings

- Fresh install of uBlock Origin

### Notes

I can’t tell what the problem is, even after looking in the logger.

**Comment by zaphodbeebblebrox** [comment]
`citationmachine.com##script:inject(abort-current-inline-script.js, LOCKAD, LOCKAD.stickyAd)`

**Comment by krystian3w** [comment]
Still see:

![obraz](https://user-images.githubusercontent.com/35370833/39531358-3bf4aca6-4e2b-11e8-9779-aa759fca853b.png) |
--- |

`www.citationmachine.net##div[id]> span > div`

**Comment by okiehsch** [comment]
Does
`citationmachine.net##script:inject(addEventListener-defuser.js, load, (!o))`
work for you?

**Comment by SheepKid12** [comment]
For some reason now, on a different machine running Firefox, I'm no longer seeing the message. I think this has to do with the AdGuard Base Fillters (everything on the chrome os system was default). I'll probably close this issue now, as I might have found the solution.

**Comment by okiehsch** [comment]
I can reproduce with Chrome using a default setup, I never could with Firefox, it has nothing to do with AdGuard Filters.
Is your issue fixed if you use Chrome and add
`citationmachine.net##script:inject(addEventListener-defuser.js, load, (!o))`?

**Comment by zaphodbeebblebrox** [comment]
Works for me. 
Out of curiosity, do the ads for its grammar checking service fall under self promotion, or should they be removed?

**Comment by okiehsch** [comment]
If you mean
![unbenannt](https://user-images.githubusercontent.com/16838044/39551594-e50e3192-4e65-11e8-8b09-a7a9d1eb6832.PNG)

That is self promotion, it links to `https://www.citationmachine.net/grammar-and-plagiarism`
You can't block that.

**Comment by zaphodbeebblebrox** [comment]
Yes, I did. 
You can block it with `citationmachine.net###paperchecker-cta-choose-source`, I was just asking if you should.

**Comment by okiehsch** [comment]
When I said "You can't block that." I meant that I can not add a blocking filter to uAssets for it, because it is self promotion.

**Comment by okiehsch** [comment]
`bibme.org` has the same issue, so I will add
`bibme.org,citationmachine.net##script:inject(addEventListener-defuser.js, load, (!o))`
