### ISSUE TITLE
curseforge.com: ads

### ISSUE THREAD

**Issue by zax71** [uBlockOrigin/uAssets#21558]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.curseforge.com/minecraft/mc-mods/jei`

(any resource page)

### Category

ads

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/67716263/f7ed9105-0c12-49f9-a593-a48dd25e4b14)
This should be blocked by UBO

```
www.curseforge.com##.rev-container
```

This above fixes the issue ^

### Other extensions used

![image](https://github.com/uBlockOrigin/uAssets/assets/67716263/8323a28e-fb4e-41e9-8565-8ca0d49cde62)
- Bitwarden
- ColorPick
- LanguageTool
- React dev tools
- SponsorBlock
- uBlock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 119
filterset (summary):
 network: 105735
 cosmetic: 44240
 scriptlet: 19574
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 25-0, never
  ublock-filters: 37366-231, now
  ublock-badware: 7703-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2223-2, now
  ublock-quick-fixes: 143-0, now
  easylist: 76317-671, now
  easyprivacy: 33156-810, now
  urlhaus-1: 10900-0, now
  plowe-0: 3787-1, now
filterset (user): [array of 25 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  moz-extension-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5788 ms (selfie)
 maxAssetCacheWait: 1745 ms
popupPanel:
 blocked: 74
 network:
  clarity.ms: 1
  doubleclick.net: 10
  google.com: 45
  googletagmanager.com: 1
  lngtd.com: 1
  overwolf.com: 3
  scorecardresearch.com: 1
  youtube.com: 12
 extended:
  ##+js(adjust-setInterval)
  ##.ytp-chrome-top-buttons > .ytp-cards-teaser
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by mapx-** [comment]
report directly at easylist repository

@ryanbr

**Comment by zax71** [comment]
https://github.com/easylist/easylist/issues/18094
