### ISSUE TITLE
serkarijobresult.com: detection

### ISSUE THREAD

**Issue by agjkp** [uBlockOrigin/uAssets#21556]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://serkarijobresult.com/safeguarding-your-finances-identity-theft-loans-and-leading-providers/`

### Category

detection

### Description

 Dear visitor, it seems that you are using an adblocker please take a moment to disable your AdBlocker it helps us pay our publishers and continue to provide free content for everyone.

Please note that the Brave browser is not supported on our website. We kindly request you to open our website using a different browser to ensure the best browsing experience.

Thank you for your understanding and cooperation.
Once, You're Done?

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 105718
 cosmetic: 44218
 scriptlet: 19572
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 37366-231, 1m
  ublock-badware: 7703-11, 1m
  ublock-privacy: 948-4, 1m
  ublock-unbreak: 2223-2, 1m
  ublock-quick-fixes: 137-0, 1m
  easylist: 76300-670, 1m
  easyprivacy: 33156-810, 1m
  urlhaus-1: 10900-0, 1m
  plowe-0: 3787-1, 1m
filterset (user): [array of 8 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 177 ms (selfie)
 maxAssetCacheWait: 87 ms
popupPanel:
 blocked: 16
 network:
  botman.ninja: 1
  doubleclick.net: 1
  google-analytics.com: 2
  googlesyndication.com: 6
  googletagmanager.com: 2
  gplinks.in: 3
  gstatic.com: 1
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
```
</details>

**Comment by BlazeFTL** [comment]
Test URL
`http://gplinks.co/rJgS`

**Comment by BlazeFTL** [comment]
https://github.com/uBlockOrigin/uAssets/pull/21557
