### ISSUE TITLE
o2online.de: nuisance

### ISSUE THREAD

**Issue by B1ack3ye** [uBlockOrigin/uAssets#21563]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.o2online.de/`

### Category

nuisance

### Description

Chat widget bottom left

### Other extensions used

TwitchNoSub
0.7
ID: pcdaafbjlogkeapgkmjpcncdekndikam

FastForward
0.2334
ID: icallnadddjmdinamnolclfjanhfoafe

FrankerFaceZ
1.57
ID: fadndhdgpmmaapbmfcknlfgcflmmmieb

Grammatik- und Rechtschreibprüfung – LanguageTool
8.3.9
ID: oldceeleldhonbafppcapldpdifcinji

Gumbo: Twitch Begleiter
1.18.6
ID: aalmjfpohaedoddkobnibokclgeefamn

Postman Interceptor
3.0.4
ID: aicmkgpgakddgnaphhhpliifpcfhicfo

Refined GitHub
23.12.17
ID: hlepfoohegkhhmjieoechaddaejaokhf

Return YouTube Dislike
3.0.0.14
ID: gebbhagfogifgggkldgodflihgfeippi

SimpleLogin:Receive & Send emails anonymously
2.10.2
ID: dphilobhebphkdjbpfohgikllaljmgbn

SponsorBlock für YouTube - Überspringe gesponserte Videosegmente
5.4.28
ID: mnjggcdmjocbbbhaepdhchncahnbgone

Violentmonkey
2.16.0
ID: jinjaccalgkegednnccohejagnlnfdag

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/63259739/24e5d81a-6584-4c94-b465-b949d0b4b15f)
![image](https://github.com/uBlockOrigin/uAssets/assets/63259739/1a4b5586-3938-4eb1-b556-de4e583f2fae)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 112246
 cosmetic: 122334
 scriptlet: 27506
 html: 0
listset (total-discarded, last-updated):
 added:
  easylist-annoyances: 4274-33, 2m
  easylist-chat: 175-0, 2m
  easylist-newsletters: 6816-15, 2m
  easylist-notifications: 2894-86, 2m
  fanboy-cookiemonster: 49211-166, 2m
  fanboy-social: 16011-13, 2m
  ublock-annoyances: 6399-79, 2m
  ublock-cookies-easylist: 822-822, 2m
 default:
  user-filters: 0-0, never
  DEU-0: 7240-0, 2m
  easylist: 76324-23, 2m
  easyprivacy: 33156-160, 2m
  plowe-0: 3787-1154, 2m
  ublock-badware: 7543-137, 2m
  ublock-filters: 36507-330, 2m
  ublock-privacy: 952-14, 2m
  ublock-quick-fixes: 124-6, 2m
  ublock-unbreak: 2177-39, 2m
  urlhaus-1: 10900-0, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1099 ms
 maxAssetCacheWait: 20 ms
popupPanel:
 blocked: 5
 network:
  baqend.com: 3
  trbo.com: 1
  usercentrics.eu: 1
```
</details>

**Comment by D4niloMR** [comment]
`||library.telefonica.de/*/components/contact-link/bundle.js`

@ryanbr @Alex-302
