### ISSUE TITLE
birgun.net: breakage

### ISSUE THREAD

**Issue by bozkurtovski** [uBlockOrigin/uAssets#21572]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.birgun.net/son-dakika-haberleri`

### Category

breakage

### Description

There are some problems on the page I mentioned. The image breaks as shown in the image below, there are also scrolls. When I disable ublock origin, the ads come and the page recovers. I use Fedora Linux, my browser is Chromium(120.0.6099.129 ).

### Other extensions used

dark reader, deepl, bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20231225_154546](https://github.com/uBlockOrigin/uAssets/assets/72918227/ececbd9d-876a-427e-8eba-81e34fbb8110)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105436
 cosmetic: 44225
 scriptlet: 19794
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76289-16, 40m
  easyprivacy: 33156-65, 40m
  plowe-0: 3787-1153, 40m
  ublock-badware: 7543-137, 40m
  ublock-filters: 36507-296, 40m
  ublock-privacy: 952-12, 40m
  ublock-quick-fixes: 126-5, 40m
  ublock-unbreak: 2177-33, 40m
  urlhaus-1: 10780-0, 40m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 599 ms (selfie)
 maxAssetCacheWait: 195 ms
popupPanel:
 blocked: 12
 network:
  birgun.net: 4
  bik.gov.tr: 1
  cloudflareinsights.com: 1
  doubleclick.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
  insurads.com: 1
 extended:
  ##.sticky-ads
  ##.container-ads
```
</details>

**Comment by mapx-** [comment]
- reset uBO to default settings / lists, be sure having the regional turkish list enabled too
- disable any other extension when testing
