### ISSUE TITLE
isthischannelmonetized.com: breakage

### ISSUE THREAD

**Issue by codex1001** [uBlockOrigin/uAssets#21576]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://isthischannelmonetized.com/`

### Category

breakage

### Description

When ublock is turned on, the form on the site becomes inoperable. and the form is always on hold and does not yield results. When ublock is closed, the form on the site is actively running. It detects ublock.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![cw121](https://github.com/uBlockOrigin/uAssets/assets/135052551/335e0493-871c-4200-a1c2-872736e6e099)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 115
filterset (summary):
 network: 105736
 cosmetic: 44245
 scriptlet: 19596
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 16-6, never
  ublock-filters: 37402-230, now
  ublock-badware: 7547-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2224-2, now
  ublock-quick-fixes: 134-0, now
  easylist: 76351-628, now
  easyprivacy: 33157-852, now
  urlhaus-1: 11035-0, now
  plowe-0: 3787-1, now
filterset (user): [array of 16 redacted]
trustedset:
 added: [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 181 ms (selfie)
 maxAssetCacheWait: 82 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by huyszn** [comment]
Test `@@||googletagmanager.com/gtag/js$script,domain=isthischannelmonetized.com`
