### ISSUE TITLE
dotabuff.com: ads

### ISSUE THREAD

**Issue by lfmnovaes** [uBlockOrigin/uAssets#21579]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dotabuff.com/heroes/arc-warden`

### Category

ads

### Description

BetBoom ads everywhere

### Other extensions used

7tv, Bitwarden, daily.dev, Google Translate, Grammarly, Stylus, Tab Session Manager, and TTV LOL PRO.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/13990675/698d1d87-7244-4f78-b28d-6b60b9ee3dda)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107099
 cosmetic: 48277
 scriptlet: 20713
 html: 0
listset (total-discarded, last-updated):
 added:
  https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt: 1011-0, now
  spa-1: 5685-66, now
 default:
  user-filters: 0-0, never
  easylist: 76351-16, now
  easyprivacy: 33157-66, now
  plowe-0: 3787-1153, now
  ublock-badware: 7543-137, now
  ublock-filters: 36519-317, now
  ublock-privacy: 952-12, now
  ublock-quick-fixes: 125-6, now
  ublock-unbreak: 2178-34, now
  urlhaus-1: 10735-0, now
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 232 ms (selfie)
 maxAssetCacheWait: 79 ms
popupPanel:
 blocked: 10
 network:
  cleverwebserver.com: 1
  elo.io: 6
  google-analytics.com: 1
  hotjar.com: 1
  quantserve.com: 1
 extended:
  ##+js(no-fetch-if, ads)
```
</details>

**Comment by D4niloMR** [comment]
`||crunchy-tango.dotabuff.com^`

@ryanbr
