### ISSUE TITLE
iwb.jp: detection

### ISSUE THREAD

**Issue by Kdroidwin** [uBlockOrigin/uAssets#21578]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://iwb.jp/page/2/`

### Category

detection

### Description

When I scroll through the articles to read, this problem occurs. 
### Other extensions used

ublacklist
 tampermonkey 
DarkReader 
Bypasspaywall

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 102
filterset (summary):
 network: 282715
 cosmetic: 158737
 scriptlet: 25882
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/negi_filter.txt: 201-0, now
  https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/negi_google_hplogo_block.txt: 12-0, 6m
  CHN-0: 25430-134, 2d.20h.52m
  adguard-cookies: 28235-30, 2d.19h.51m
  adguard-mobile-app-banners: 4855-12, 12h.25m
  adguard-other-annoyances: 13976-24, 12h.25m
  adguard-popup-overlays: 26671-84, 2d.20h.52m
  adguard-social: 22124-925, 12h.25m
  adguard-spyware: 81721-211, 2d.19h.51m
  adguard-spyware-url: 1369-5, 2d.20h.53m
  adguard-widgets: 2381-7, 2d.20h.52m
  block-lan: 55-0, 6d.23h.5m
  [6 lists not shown]: [too many]
 default:
  user-filters: 443-16, never
  JPN-1: 13945-12, 2d.20h.53m
  easylist: 76351-389, 7m
  easyprivacy: 33157-16442, 7m
  ublock-badware: 7543-156, 6m
  ublock-filters: 36519-706, 7m
  ublock-privacy: 952-389, 7m
  ublock-quick-fixes: 125-6, 7m
  ublock-unbreak: 2178-87, 6m
  urlhaus-1: 10780-0, 12h.25m
filterset (user): [array of 444 redacted]
switchRuleset:
 added: [array of 10 redacted]
hostRuleset:
 added: [array of 80 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 12017 ms (selfie)
 maxAssetCacheWait: 1492 ms
popupPanel:
 blocked: 3
 network:
  iwb.jp: 3
 extended:
  ##ins.adsbygoogle
  ##a[href^="https://feedly.com/i/subscription/"]
  ##+js(noeval-if, /chp_?ad/)
```
</details>

**Comment by D4niloMR** [comment]
@Yuki2718 detection script `https://iwb.jp/wp-content/themes/twentyseventeen/assets/js/function.js`

**Comment by Yuki2718** [comment]
Yes, the owner updated the script so now `.adsbygoogle`'s height must be 40 px or higher, but your rule works.

**Comment by D4niloMR** [comment]
@Yuki2718 again

**Comment by D4niloMR** [comment]
@Yuki2718

**Comment by roxas1533** [comment]
It appears to have occurred again.
