### ISSUE TITLE
moovitapp.com: breakage

### ISSUE THREAD

**Issue by CamilaLorenzetti** [uBlockOrigin/uAssets#21586]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://moovitapp.com/florianopolis-1907/poi/Praia%20dos%20Ingleses/Centro`

### Category

breakage

### Description

Broken by `uBlock filters – Annoyances`.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![ad](https://github.com/uBlockOrigin/uAssets/assets/151783497/12ee277b-9eb8-428a-8ab9-912e34eceb66)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105706
 cosmetic: 45941
 scriptlet: 24164
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6406-11, now
 default:
  user-filters: 0-0, never
  easylist: 76324-16, 37m
  easyprivacy: 33157-65, 37m
  plowe-0: 3787-1153, 37m
  ublock-badware: 7543-137, 37m
  ublock-filters: 36477-296, 37m
  ublock-privacy: 952-12, 37m
  ublock-quick-fixes: 126-4, 37m
  ublock-unbreak: 2178-34, 37m
  urlhaus-1: 10735-0, 37m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9390 ms
 maxAssetCacheWait: 2830 ms
popupPanel:
 blocked: 8
 network:
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  sentry.io: 5
 extended:
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##.map-ad
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(trusted-click-element, [data-automation="continue-to-ads-b…
  ##+js(remove-node-text, script, Interstitial)
```
</details>

**Comment by 96273** [comment]
Update please. This occurs in Chromium browsers. Select a start destination and an end destination, then click the search button.
<details><summary>Image</summary>

<img width="1057" height="283" alt="Image" src="https://github.com/user-attachments/assets/76d5661f-c5ff-4aea-997e-366b3605fdfc" />

<img width="736" height="768" alt="Image" src="https://github.com/user-attachments/assets/a6297831-00f9-4c88-b730-bd0dca2c868a" />

</details>
