### ISSUE TITLE
cnet.com: nuisance

### ISSUE THREAD

**Issue by beemaster3000** [uBlockOrigin/uAssets#21581]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.cnet.com/tech/gaming/dont-be-a-game-hoarder-share-your-steam-library-with-friends/`

### Category

nuisance

### Description

Non Youtube video pops up and is impossible to remove

### Other extensions used

icloud bookmarks
I don't care about cookies
Chrome remote desktop
augmented steam
checkmarks
reddit enhancement suit
soundcloud downloader
the Camelizer

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 105444
 cosmetic: 44243
 scriptlet: 19596
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  ublock-filters: 37407-312, 33m
  ublock-badware: 7547-11, 33m
  ublock-privacy: 948-4, 33m
  ublock-unbreak: 2224-2, 33m
  ublock-quick-fixes: 142-0, 33m
  easylist: 76351-589, 33m
  easyprivacy: 33157-810, now
  urlhaus-1: 10735-0, now
  plowe-0: 3787-1, now
filterset (user): [array of 3 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 635 ms (selfie)
 maxAssetCacheWait: 277 ms
popupPanel:
 blocked: 24
 network:
  cnet.com: 1
  2mdn.net: 1
  ads-twitter.com: 1
  amazon-adsystem.com: 1
  clrt.ai: 1
  confiant-integrations.net: 1
  doubleclick.net: 3
  facebook.net: 1
  go-mpulse.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
  indexww.com: 1
  moatads.com: 1
  narrativ.com: 1
  qualtrics.com: 1
  redventures.io: 2
  sentry.io: 2
  taboola.com: 1
  tiktok.com: 1
  urbanairship.com: 1
 extended:
  ##.c-adDisplay_container
  ##.c-adSkyBox
  ##.c-adDisplay
  ##.uvpjs__btn-large-play
  ##+js(xml-prune, VAST, , adnxs)
```
</details>

**Comment by mapx-** [comment]
add

```
cnet.com##.c-avVideo
cnet.com##.c-cnetAvShare
```

@ryanbr

**Comment by ryanbr** [comment]
Install FB Annoyances list?
