### ISSUE TITLE
4pda.to: breakage

### ISSUE THREAD

**Issue by roninspin** [uBlockOrigin/uAssets#21585]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [x] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://4pda.to/`

### Category

breakage

### Description

Site's articles get hidden.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Снимок экрана (2)](https://github.com/uBlockOrigin/uAssets/assets/33757249/64edc301-6baa-40cc-aaf8-e764e4af6d14)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 122873
 cosmetic: 65371
 scriptlet: 20995
 html: 1167
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  ublock-filters: 37407-231, 10m
  ublock-badware: 7547-11, 10m
  ublock-privacy: 948-4, 10m
  ublock-unbreak: 2224-2, 10m
  ublock-quick-fixes: 142-0, 10m
  easylist: 76353-670, 10m
  easyprivacy: 33157-810, 10m
  urlhaus-1: 10735-0, 9m
  plowe-0: 3787-1, now
  RUS-0: 40144-156, 10m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 194 ms (selfie)
 maxAssetCacheWait: 107 ms
popupPanel:
 blocked: 2
 network:
  googletagmanager.com: 1
  yadro.ru: 1
 extended:
  ##[style=";background-image:none!important;background-color:tran…
  ##a[href*="utm_campai"]
  ##html[style] > body[style=";background-color:#E6E7E9!important"…
  ##+js(adjust-setTimeout, zat_tick)
  ##+js(no-xhr-if, /m2?_)
```
</details>

**Comment by mapx-** [comment]
I cannot reproduce your issue.

However to block all the ads you have to subscribe to `RU AdList: Counters` too

go here: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links
and subscribe that list
