### ISSUE TITLE
auth.claro.com.br: nuisance

### ISSUE THREAD

**Issue by CamilaLorenzetti** [uBlockOrigin/uAssets#21587]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://auth.claro.com.br/authorize?client_id=MINHA_CLARO_RESIDENCIAL&redirect_uri=https%3A%2F%2Fminhaclaroresidencial.claro.com.br%2Flogin&response_type=code&scope=openid+minha_net+net_profile`

### Category

nuisance

### Description

They hide the password field by default for no reason (pressing "Continuar" reveals it without checking if the "Login" info is valid). This is annoying because it breaks the "auto-fill" feature of external password managers.

This rule fixes this:

    auth.claro.com.br#$#.cred-InputContainer{display:block!important}

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 197722
 cosmetic: 174579
 scriptlet: 46940
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28225-30, 27m
  adguard-generic: 81443-487, 24m
  adguard-mobile-app-banners: 4856-10, 26m
  adguard-other-annoyances: 13973-8, 27m
  adguard-popup-overlays: 26686-89, 26m
  adguard-social: 22133-926, 27m
  adguard-spyware: 82392-1203, 24m
  adguard-spyware-url: 1370-5, 24m
  adguard-widgets: 2382-5, 27m
  block-lan: 55-0, 24m
  spa-1: 5687-78, 25m
  ublock-annoyances: 6406-197, 25m
  [1 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  easylist: 76324-1724, 1h.7m
  easyprivacy: 33157-16411, 1h.7m
  plowe-0: 3787-1253, 1h.7m
  ublock-badware: 7543-315, 1h.7m
  ublock-filters: 36477-4032, 1h.7m
  ublock-privacy: 952-390, 1h.7m
  ublock-quick-fixes: 126-5, 1h.7m
  ublock-unbreak: 2178-151, 1h.7m
  urlhaus-1: 10735-0, 1h.8m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4543 ms
 maxAssetCacheWait: 2688 ms
popupPanel:
 blocked: 1
 network:
  googletagmanager.com: 1
```
</details>

**Comment by gorhill** [comment]
I don't think it's something to be dealt with by stock filter lists. Also, your URL doesn't work.

**Comment by mapx-** [comment]
You should contact the site for this "issue"
