### ISSUE TITLE
maxroll.gg: detection

### ISSUE THREAD

**Issue by UserPizza** [uBlockOrigin/uAssets#21582]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://maxroll.gg/lost-ark`

### Description

adblock warning.. 

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![a](https://github.com/uBlockOrigin/uAssets/assets/146446273/2cbd3c2e-a15d-499d-a109-75b00cefda91)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107940
 cosmetic: 50579
 scriptlet: 20171
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76353-16, 3m
  easyprivacy: 33157-65, 3m
  plowe-0: 3787-1153, 3m
  spa-0: 3774-20, 3m
  spa-1: 5685-209, 3m
  ublock-badware: 7543-137, 3m
  ublock-filters: 36520-319, 3m
  ublock-privacy: 952-12, 3m
  ublock-quick-fixes: 126-6, 3m
  ublock-unbreak: 2178-35, 4m
  urlhaus-1: 10735-0, 4m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 297 ms (selfie)
 maxAssetCacheWait: 99 ms

```
</details>

**Comment by mapx-** [comment]
@UserPizza enable `uBlock filters – Annoyances`

**Comment by dev0T** [comment]
Still being detected even with Annoyances being enabled and updated

**Comment by UserPizza** [comment]
true , takes a while to appear but still the issue..
tested in other browser ( opera ) 

Before entering the site I updated the filters

**Comment by UserPizza** [comment]
is not true.. my bad i was testing:  `@@||s.nitropay.com/ads-$script,from=maxroll.gg,badfilter`

sorry for confuse

**Comment by UserPizza** [comment]
this site have other anti adblock if I click in any link here:

`https://maxroll.gg/d2/guides/lightning-fury-amazon-guide`
![11](https://github.com/uBlockOrigin/uAssets/assets/146446273/f6e2a49b-b75a-41ea-a6dc-8ae43900a5a0)

this happens:
![1](https://github.com/uBlockOrigin/uAssets/assets/146446273/4a02ee21-7e9a-4158-93e6-e9a21efbfafd)


Redirect to: `https://maxroll.gg/404#Rocky-Waste`

**Comment by mapx-** [comment]
I get the same behaviour even disabling uBO on that site
