### ISSUE TITLE
charexempire.com: nuisance

### ISSUE THREAD

**Issue by yuukiAme** [uBlockOrigin/uAssets#21597]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://charexempire.com/qDPX0C`

`https://go.cravesandflames.com/qDPX0C`

### Description

The webpage is a URL shorter with a built-in timer and bot detection. It will do pop-up on a 2nd page.

You will need to original URL to get to the timer page. Otherwise, it will show a normal blog page with a bunch of text and pictures.

### Other extensions used

None. I disabled them for this report.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2023-12-27 13_30_54-Craves and flames — Mozilla Firefox](https://github.com/uBlockOrigin/uAssets/assets/45681604/8c7e833c-febb-4fe1-956d-238f351fd8e0)

![2023-12-27 13_25_17-5 Home Insurance Gaps to Look Out For! – Craves and flames — Mozilla Firefox](https://github.com/uBlockOrigin/uAssets/assets/45681604/f10f327b-c0d2-448f-ae04-f4f1eecb833d)

![2023-12-27 13_25_33-ZSHORT — Mozilla Firefox](https://github.com/uBlockOrigin/uAssets/assets/45681604/46031014-70a6-43cf-8533-0c000f5164de)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 105266
 cosmetic: 44257
 scriptlet: 19617
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37430-229, 1h.4m
  ublock-badware: 7558-11, 1h.4m
  ublock-privacy: 945-4, 6d.22h.34m
  ublock-unbreak: 2224-1, 1h.4m
  ublock-quick-fixes: 144-0, 1h.4m
  easylist: 76401-670, 1h.4m
  easyprivacy: 33165-808, 1h.4m
  urlhaus-1: 10505-0, 12h.20m
  plowe-0: 3781-1, 6d.22h.34m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 114 ms (selfie)
 maxAssetCacheWait: 43 ms

```
</details>

**Comment by huyszn** [comment]
For the popup on the last page
`cravesandflames.com##+js(set, go_popup, {})`

**Comment by yuukiAme** [comment]
What about the timer on page 2 and page 3. Any ways to skip them or run down the timer to unlock the continue button?

**Comment by mapx-** [comment]
not fixable (server side stuff)
