### ISSUE TITLE
raspberrytips.com: ads

### ISSUE THREAD

**Issue by Dani-1-2** [uBlockOrigin/uAssets#21590]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [x] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://raspberrytips.com/ftp-server-raspberry-pi/`

### Category

ads

### Description

2 ad banners appear

### Other extensions used

none

### Screenshot(s)

![report2](https://github.com/uBlockOrigin/uAssets/assets/149429107/6a4697f1-20a1-4329-9385-298acf8731a8)

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 119
filterset (summary):
 network: 272642
 cosmetic: 197443
 scriptlet: 32020
 html: 1348
listset (total-discarded, last-updated):
 added:
  adguard-spyware-url: 1370-92, now
  adguard-spyware: 82392-16991, now
  curben-phishing: 78958-30, now
  adguard-social: 22133-875, now
  adguard-cookies: 28228-63, now
  ublock-cookies-adguard: 827-0, now
  adguard-popup-overlays: 26690-1598, now
  adguard-mobile-app-banners: 4856-1071, now
  adguard-other-annoyances: 13977-331, now
  adguard-widgets: 2383-1, now
  fanboy-thirdparty_social: 69-0, now
  easylist-annoyances: 4276-121, now
  [9 lists not shown]: [too many]
 default:
  user-filters: 3-0, never
  ublock-filters: 37418-581, now
  ublock-badware: 7558-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2224-2, now
  ublock-quick-fixes: 143-0, 1h.33m
  easylist: 76378-922, now
  easyprivacy: 33157-981, now
  urlhaus-1: 10505-0, now
  plowe-0: 3787-1, now
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 515 ms (selfie)
 maxAssetCacheWait: 368 ms
popupPanel:
 blocked: 7
 network:
  amazon-adsystem.com: 2
  google-analytics.com: 1
  googletagmanager.com: 1
  mailerlite.com: 1
  mediavine.com: 2
 extended:
  ##.dpsp-share-text
  ##.dpsp-networks-btns-share
  ##.dpsp-network-btn
  ##.dpsp-pinterest
  ##.kadence-conversion-banner
  ##.dpsp-networks-btns-sidebar
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[title="Share on Facebook"]
  ##a[title="Share on Twitter"]
```
</details>

**Comment by Dani-1-2** [comment]
Note: I removed the aditional filter

**Comment by huyszn** [comment]
If you are talking about the banner under the `Join now!` in your screenshot `raspberrytips.com##[href^="https://www.sunfounder.com/"]`

**Comment by mapx-** [comment]
@ryanbr
