### ISSUE TITLE
avclub.com: breakage

### ISSUE THREAD

**Issue by newporpoise** [uBlockOrigin/uAssets#21599]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.avclub.com/fargo-season-5-premiere-review-episodes-1-2-1851031893`

### Category

breakage

### Description

I am attempting to read an article on AV Club. When uBlock Origin is enabled, I am unable to click the "continue reading" button to reveal more of the article content; the button does not respond to any interaction. However, when disabled, the button works and the content is now viewable.

### Other extensions used

I also use YouTube Search Fixer, XKit Rewritten, Purple Ads Blocker and Old Twitter Layout (2023) but these did not have the ability to read any data on the site when I was reading.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105473
 cosmetic: 44262
 scriptlet: 19618
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37434-229, 11m
  ublock-badware: 7558-11, 11m
  ublock-privacy: 948-4, 11m
  ublock-unbreak: 2224-1, 11m
  ublock-quick-fixes: 144-0, 11m
  easylist: 76411-672, 11m
  easyprivacy: 33165-810, 11m
  urlhaus-1: 10700-0, 3m
  plowe-0: 3787-1, 3m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 279 ms (selfie)
 maxAssetCacheWait: 63 ms
popupPanel:
 blocked: 16
 network:
  avclub.com: 1
  adlightning.com: 1
  amazon-adsystem.com: 2
  connatix.com: 2
  doubleclick.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 1
  indexww.com: 1
  kinja-static.com: 1
  scorecardresearch.com: 1
  speedcurve.com: 2
  taboola.com: 1
 extended:
  ###splashy-ad-container-top
  ##.js_sticky-top-ad
  ##.js_desktop-horizontal-ad
  ##.ad-top-banner
  ##.collapsed-ad
  ##.js_related-stories-inset
  ##.ad-mobile-dynamic
  ##.ad-unit:not(.text-ad):not(.textads)
  ##.ad-mobile
  ##.connatix-main-container
  ###taboola-below-article-thumbnails
  ##.js_ad-sticky-footer
  ##.ad-left-top
  ###leftrail_dynamic_ad_wrapper
  ##.japmJB
  ##+js(set-constant, ga, noopFunc)
  ##+js(addEventListener-defuser, click, [native code])
```
</details>

**Comment by peace2000** [comment]
https://github.com/uBlockOrigin/uAssets/issues/21567 related to this

**Comment by peace2000** [comment]
Should be fine now https://github.com/uBlockOrigin/uAssets/commit/1e006007021dfa8e3b7ae5471a0354e0e14cfc07
