### ISSUE TITLE
tv2.idlixplus.com: detection

### ISSUE THREAD

**Issue by TF2BestGame** [uBlockOrigin/uAssets#21595]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://tv2.idlixplus.com/`

### Category

detection

### Description

Hello UBO Team, I come to you in time of great need

Detection of adblocker on site

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/154939631/eac3b42e-528b-45af-8b14-5b69868a2628)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105442
 cosmetic: 44246
 scriptlet: 19820
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 76379-16, 8m
  easyprivacy: 33157-65, 8m
  plowe-0: 3787-1153, 8m
  ublock-badware: 7554-137, 8m
  ublock-filters: 36529-296, 8m
  ublock-privacy: 952-12, 8m
  ublock-quick-fixes: 127-4, 8m
  ublock-unbreak: 2178-32, 8m
  urlhaus-1: 10700-0, 8m
filterset (user): [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 593 ms (selfie)
 maxAssetCacheWait: 291 ms
popupPanel:
 blocked: 0
 extended:
  ##.module_home_ads
```
</details>

**Comment by huyszn** [comment]
For the detection, annoying overlay popup, and anti-devtools. You should also enable `ABPindo` regional list
```
||cdn.jsdelivr.net/npm/disable-devtool$script,domain=idlixplus.com
idlixplus.com##+js(aost, document.getElementsByTagName, adsBlocked)
idlixplus.com###repop
```
