### ISSUE TITLE
hackintosh.zone

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uAssets#216]
### URL(s) where the issue occurs

http://www.hackintosh.zone/

### Describe the issue

BlockAdblock script blocks the page from being accessed by the user as usual.

### Screenshot(s)

https://i.gyazo.com/7bf52fe29e0204467dae65ed1797a1a9.png

### Versions

Browser/version: [here] Chromium 57
uBlock Origin version: [here] 1.10.0

### Settings

Default

### Notes

Investigation reveals that the standard $elemhide/$generichide filters wont work on that site. The working solution is to inject bab-defuser.js in uBO.

**Comment by uBlock-user** [comment]
@gorhill it's happening again.

**Comment by okiehsch** [comment]
`||googlesyndication.com^$xmlhttprequest,redirect=nooptext,domain=hackintosh.zone`
works on my end.

**Comment by uBlock-user** [comment]
I rather get redirected to `https://www.hackintosh.zone/adblock/stop_adblock.html?goback=https://www.hackintosh.zone/`

I'm blocking `googlesyndication` with `$important`. (noeval.js) does stop the redirection however the anti adblock message still appears.

**Comment by okiehsch** [comment]
Works here with just `||googlesyndication.com^$xmlhttprequest,redirect=nooptext,domain=hackintosh.zone`
no `$important` and `(noeval.js)` with both Chrome and Firefox.

**Comment by uBlock-user** [comment]
I'm testing on Chromium 57 and no still the same even after adding that filter.

**Comment by okiehsch** [comment]
For clarification:
With Chrome 55 and the filter `||googlesyndication.com^$xmlhttprequest,redirect=nooptext,domain=hackintosh.zone`, nothing else
it works on my end.
If I also add `hackintosh.zone##script:inject(noeval.js)`, ther is no redirection, but I
get the message "Please disable your adblock and script blockers to view this page."
on a blank white page.

**Comment by uBlock-user** [comment]
>  I also add hackintosh.zone##script:inject(noeval.js), there is no redirection, but I
get the message "Please disable your adblock and script blockers to view this page."
on a blank white page.

I'm facing that only with `noeval.js` That message isn't inside any scripts so blocking inline-script won't help either.

**Comment by okiehsch** [comment]
Does it work if you allow `@@||tpc.googlesyndication.com$xmlhttprequest,domain=www.hackintosh.zone`?

**Comment by uBlock-user** [comment]
I would have to go through the trouble of removing `$googlesyndication.com^$important` for that filter to take effect, I would rather not go through that again which I already did minute ago to test `||googlesyndication.com^$xmlhttprequest,redirect=nooptext,domain=hackintosh.zone`

**Comment by okiehsch** [comment]
Well I am sorry, maybe the redirection doesn't work with Chromium 57.
It works with Chrome 55 and Firefox 50.1., atleast on my end.

**Comment by uBlock-user** [comment]
Don't be. The redirection isn't the issue as it works for others, but those multiple checks are.

**Comment by gorhill** [comment]
This works:

    ||googlesyndication.com^$xmlhttprequest,redirect=nooptext,domain=hackintosh.zone
    ||googlesyndication.com^$important,script,domain=hackintosh.zone

First prevent the site from detecting that requests to `googlesyndication.com` are blocked, second cancel EasyList's exception filters which is what works for ABP.

**Comment by uBlock-user** [comment]
> This works:
Not for me. Not on Chromium 55 either. Nothing changes with those filters on my side.

So I came up with an alternate set of filters without involving `googlesyndication.com` in any case.

````
||hackintosh.zone/advjs/bin/jso.php^$script
hackintosh.zone##script:inject(setTimeout-defuser)
````

That `/jso.php` was the culprit which was making all my efforts pointless. Blocking it made using `setTimeout-defuser` effective, as always.

**Comment by uBlock-user** [comment]
gorhill, that filter has no effect either, you will need to block `/jso.php` or stop it from executing anyway.

**Comment by gorhill** [comment]
It works on my side -- using default settings.

**Comment by gorhill** [comment]
I get different results when using Chrome 57. I put back the two other filters, somehow they are not hit when using Chrome 57 (hence I thought they became useless), but I just verified they are indeed hit when using Chromium 53.

**Comment by uBlock-user** [comment]
My filters also work on Chromium 57 and the Chromium versions I use are from here - https://github.com/henrypp/chromium/releases/tag/v57.0.2970.0-r441047-win64

**Comment by gorhill** [comment]
I can't reproduce without blocking that `jso.php` script, but looking at its content it does look like something which deserved to be blocked -- obfuscated javascript fed to `eval`.

**Comment by gorhill** [comment]
This will need investigation.

**Comment by uBlock-user** [comment]
Yep it's happening again, and on .computer domain too this time so the code was updated/changed.

**Comment by okiehsch** [comment]
`hackintosh.computer` works fine on my end after applying the fix. 
`hackintosh.zone` redirects me to `https://www.hackintosh.zone/adblock/stop_adblock.html`, if I 
click any article, for example `https://www.hackintosh.zone/file/1021-nvidia-web-driver-auto-installer`
![hacki](https://cloud.githubusercontent.com/assets/16838044/25198101/b684c4a6-2546-11e7-87fe-4b8e66d4af0e.PNG)
I can fix this issue if I add
`hackintosh.zone##script:inject(abort-on-property-write.js, history.pushState)`
I don't think that would lead to any site breakage. but maybe you prefer a different solution,
so I wanted to ask before adding that filter.

**Comment by gorhill** [comment]
Go ahead with this filter. It causes an error at the console which makes it easy to understand what is going on, but if ever the site works around that filter, we can look for a more specific solution.

**Comment by okiehsch** [comment]
@gorhill site changed it's code again,
`hackintosh.zone##script:inject(abort-on-property-write.js, onload)` works on my end.

**Comment by Rose2234** [comment]
These don't work anymore

@@/^((?!googlesyndication|adsystem).)*$/$script,third-party,domain=hackintosh.zone
@@||$xmlhttprequest,image,domain=hackintosh.zone,third-party
@@||cdn.hackintosh.zone/ads/ads.js

or these either

||hackintosh.zone/advjs/bin/jso.php^$script
hackintosh.zone##script:inject(setTimeout-defuser)

**Comment by jspenguin2017** [comment]
They added a new detection... It seems... Maybe nooping `document.body.innerHTML` assignment?

**Comment by jspenguin2017** [comment]
They added a new detection...

**Comment by jspenguin2017** [comment]
setTimeout-defuser should work I think...

**Comment by jspenguin2017** [comment]
Seems to be broken again.

**Comment by okiehsch** [comment]
@jspenguin2017 fixed

**Comment by KiLL4FuNK** [comment]
Anti-Adblock  download file

`https://www.hackintosh.zone/file/75-hackintosh-mavericks/`
