### ISSUE TITLE
vrum.com.br: ads

### ISSUE THREAD

**Issue by ittairuf** [uBlockOrigin/uAssets#21603]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.vrum.com.br/`

### Category

ads

### Description

Gray boxes of blocked ads.

### Other extensions used

Keepa
Firefox Multi-Account Containers
Location Guard

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/144939186/13397548-9cca-4374-b07b-8d036d357271

https://github.com/uBlockOrigin/uAssets/assets/144939186/49376d77-da50-47a9-981c-2bd7757cf76b

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 107137
 cosmetic: 48039
 scriptlet: 19988
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37444-250, 3m
  ublock-badware: 7559-11, 3m
  ublock-privacy: 948-4, 3m
  ublock-unbreak: 2222-1, 3m
  ublock-quick-fixes: 145-0, 3m
  easylist: 76402-713, 3m
  easyprivacy: 33166-824, 3m
  urlhaus-1: 10910-0, 3m
  plowe-0: 3787-1, 3m
  spa-1: 5688-11, 3m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1872 ms
 maxAssetCacheWait: 5 ms
popupPanel:
 blocked: 45
 network:
  vrum.com.br: 1
  2mdn.net: 2
  amazon-adsystem.com: 2
  criteo.com: 2
  doubleclick.net: 3
  google-analytics.com: 1
  googlesyndication.com: 1
  googletagmanager.com: 2
  navdmp.com: 4
  scorecardresearch.com: 1
  taboola.com: 26
 extended:
  ##[id^="google_ads_iframe"]:not(.rb-adbanner)
  ##div[data-google-query-id]
  #@#[id^="google_ads_iframe"]
```
</details>

**Comment by mapx-** [comment]
add

```
vrum.com.br##.ad-banner
vrum.com.br##article:has(.ad-banner)
```

@Yuki2718 for spanish - portuguese list

**Comment by ittairuf** [comment]
Another page with same gray boxes.
https://extra.globo.com/
I think is
extra.globo.com##.ad-background-center
extra.globo.com##ad-container-top-placeholder.

By the way how can i contribute direct with developers without having to open a issue here every time?

**Comment by Yuki2718** [comment]
> Another page with same gray boxes. `https://extra.globo.com/` I think is
> 
> ```
> extra.globo.com##.ad-background-center
> extra.globo.com##ad-container-top-placeholder
> ```

Already hidden by an EL rule `##.ad-background-center` and `###ad-container-top-placeholder`.

> By the way how can i contribute direct with developers without having to open a issue here every time?

Keep high-quality PRs maybe for 6 months or so.

**Comment by ittairuf** [comment]
I'm seeing some rest of ads now again.
`##div.publicidade-interna-container`
[Image](https://github.com/user-attachments/assets/b7e301d0-553c-4e38-93bc-8fbaebe97d74)

@Yuki2718
