### ISSUE TITLE
kissanime.co: detection

### ISSUE THREAD

**Issue by sparklesMc** [uBlockOrigin/uAssets#21614]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://kissanime.co/Anime/sora-no-otoshimono-dub.78542/Episode-006?id=42107`

### Category

detection

### Description

It wont allow the video to play while ublock origin is enabled

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot (1)](https://github.com/uBlockOrigin/uAssets/assets/18631141/55a8e972-efa0-45a2-8318-0aee6711229e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 118
filterset (summary):
 network: 105335
 cosmetic: 44266
 scriptlet: 19623
 html: 1142
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37452-229, now
  ublock-badware: 7558-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2222-1, now
  ublock-quick-fixes: 145-0, now
  easylist: 76401-671, now
  easyprivacy: 33167-810, now
  urlhaus-1: 10560-0, now
  plowe-0: 3787-1, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 430 ms
 maxAssetCacheWait: 138 ms
popupPanel:
 blocked: 16
 network:
  kissanime.co: 7
  bebi.com: 2
  demand.supply: 1
  disqus.com: 2
  google-analytics.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ###upgrade_pop
  ##+js(abort-current-script, JSON.parse, break;case $.)
  ##+js(abort-current-script, String.fromCharCode, /btoa|break/)
  ##+js(href-sanitizer, a[href^="https://disq.us/url?url="][title^…
  ##+js(href-sanitizer, a[href^="https://disq.us/?url=http"], ?url…
```
</details>

**Comment by mapx-** [comment]
- do not use Yandex browser
- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example =>  IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
