### ISSUE TITLE
bombuj.si: ads

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [uBlockOrigin/uAssets#21643]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bombuj.si/online-film-jackass-forever-2022`

### Category

ads

### Description

ads

### Other extensions used

no

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 119
filterset (summary):
 network: 105875
 cosmetic: 44728
 scriptlet: 19869
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 20-2, never
  CZE-0: 833-1, 2m
  easylist: 76476-19, 2m
  easyprivacy: 33167-71, 2m
  plowe-0: 3787-1155, 2m
  ublock-badware: 7555-137, 2m
  ublock-filters: 36355-211, 2m
  ublock-privacy: 952-12, 2m
  ublock-quick-fixes: 128-4, 2m
  ublock-unbreak: 2176-32, 2m
  urlhaus-1: 10815-0, 2m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1270 ms (selfie)
 maxAssetCacheWait: 159 ms
popupPanel:
 blocked: 3
 network:
  bombuj.si: 2
  wurfl.io: 1
 extended:
  ##div[id*="banner"]
  ##a[id*="zatvorit"]:remove-attr(href)
```
</details>

**Comment by mapx-** [comment]
@Sh3r1ffCZ 
test for breakege

```
bombuj.si##style:has-text(blink_me_ad):upward(2)
bombuj.si##[href][target="_blank"]
```

**Comment by Sh3r1ffCZ** [comment]
OMG it works! Thanks, where did you find this? 

> @Sh3r1ffCZ test for breakage
> 
> ```
> bombuj.si##style:has-text(blink_me_ad):upward(2)
> bombuj.si##[href][target="_blank"]
> ```
