### ISSUE TITLE
learnmany.in: detection

### ISSUE THREAD

**Issue by GollumArain** [uBlockOrigin/uAssets#21659]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://learnmany.in/how-travel-blogs-monetize-through-partnerships`

### Category

detection

### Description

Detects

### Other extensions used

Bitwarden, IDM, ColorZilla

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 287373
 cosmetic: 171942
 scriptlet: 50223
 html: 0
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  adguard-cookies: 28250-1594, now
  adguard-generic: 81559-740, now
  adguard-mobile: 8947-78, now
  adguard-mobile-app-banners: 4866-18, now
  adguard-other-annoyances: 13992-16, now
  adguard-popup-overlays: 26721-133, now
  adguard-spyware: 82405-1234, now
  adguard-spyware-url: 1377-5, now
  adguard-widgets: 2388-39, now
  block-lan: 55-0, now
  curben-phishing: 79780-20, now
  dpollock-0: 11620-253, now
  [7 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  easylist: 76494-17951, 11m
  easyprivacy: 33169-16505, 11m
  ublock-badware: 7560-324, 11m
  ublock-filters: 36556-4130, 11m
  ublock-privacy: 952-389, 11m
  ublock-quick-fixes: 135-4, 11m
  ublock-unbreak: 2176-151, 11m
  urlhaus-1: 9725-0, now
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 17 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1229 ms (selfie)
 maxAssetCacheWait: 890 ms
popupPanel:
 blocked: 11
 network:
  learnmany.in: 1
  ampproject.org: 2
  doubleclick.net: 2
  googlesyndication.com: 4
  googletagmanager.com: 1
  pubfuture-ad.com: 1
```
</details>

**Comment by huyszn** [comment]
@GollumArain You should have told us that `learnmany.in` came from a link shortener.
