### ISSUE TITLE
Adblock detected, Can't get past the site without disabling

### ISSUE THREAD

**Issue by AfsalBaaqirA** [uBlockOrigin/uAssets#21652]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://studygovtyojana.com/beyond-banking-exploring-the-elite-credit-union-loan-providers/`

### Description

It detect ublock origin and cant get past it without disabling

### Other extensions used

N/A

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105627
 cosmetic: 44218
 scriptlet: 19788
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 76300-16, 4d.23h.49m
  easyprivacy: 33156-65, 4d.23h.49m
  plowe-0: 3787-1153, 4d.23h.49m
  ublock-badware: 7699-138, 4d.23h.49m
  ublock-filters: 36478-296, 4d.23h.49m
  ublock-privacy: 952-12, 4d.23h.49m
  ublock-quick-fixes: 128-1, 1h.9m
  ublock-unbreak: 2177-32, 4d.23h.49m
  urlhaus-1: 10815-0, 22h
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 3 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 8 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 620 ms (selfie)
 maxAssetCacheWait: 200 ms
```
</details>

**Comment by mapx-** [comment]
update your filter lists

**Comment by AfsalBaaqirA** [comment]
I have updated, it removes the "Adblock detected" banner, but the normal process is not available, I'm downloading a file, disabling ublock origin the timer runs and i can go to my destination. but with ublock origin the timer doesn't run, more specifically the time doesn't even show up
