### ISSUE TITLE
tu.no: ads

### ISSUE THREAD

**Issue by ObsoletePremonition** [uBlockOrigin/uAssets#21651]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.tu.no/`

### Category

ads

### Description

The page seems to fully ignore the ad-blocker.

### Other extensions used

LanguageTool, SponsorBlock, LibRedirect, Consent-O-Matic.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 106612
 cosmetic: 46536
 scriptlet: 19536
 html: 1124
listset (total-discarded, last-updated):
 default:
  user-filters: 43-8, never
  ublock-filters: 37225-220, now
  ublock-badware: 7559-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2222-1, now
  ublock-quick-fixes: 145-0, now
  easylist: 76477-590, now
  easyprivacy: 33168-811, now
  urlhaus-1: 10190-0, now
  plowe-0: 3787-1, now
  NOR-0: 3842-4, now
filterset (user): [array of 43 redacted]
trustedset:
 removed:
  about-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 262 ms (selfie)
 maxAssetCacheWait: 65 ms
popupPanel:
 blocked: 6
 network:
  aticdn.net: 1
  cxense.com: 1
  doubleclick.net: 1
  facebook.net: 1
  hotjar.com: 1
  licdn.com: 1
 extended:
  ##+js(abort-current-script, dfpConfig, loadAds)
  ##+js(remove-attr, class, .dfp-loaded)
```
</details>

**Comment by mapx-** [comment]
@ObsoletePremonition 

test

`tu.no##+js(aeld, error)`

@DandelionSprout

**Comment by DandelionSprout** [comment]
I'll take the old-school way and go for these:
```
tu.no##div[class*=-ads-wrapper i]
tu.no##div[id^=row- i]
tu.no##div.relative > div[class*=" items-center hidden " i]
```
Plus extending `digi.no##a[href*="/tumstudio/"]` to TU.
