### ISSUE TITLE
pikabu.ru: nuisance

### ISSUE THREAD

**Issue by k0lenval** [uBlockOrigin/uAssets#21657]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://pikabu.ru/`

### Description

It is not possible to block VK.com authorization because the name of the cosmetic filter is not static.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![qwd](https://github.com/uBlockOrigin/uAssets/assets/152970848/dd182e27-0a2e-4127-8272-60d8adbe8ea1)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.52.2
Chromium: 86
filterset (summary):
 network: 198606
 cosmetic: 65894
 scriptlet: 21878
 html: 0
listset (total-discarded, last-updated):
 added:
  https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 76-0, 9h.38m
  adguard-spyware: 82392-204, 2d.11h.12m
  adguard-spyware-url: 1370-5, 2d.11h.10m
  block-lan: 55-0, 14d.15h
  dpollock-0: 11620-180, 1d.10h.35m
 default:
  user-filters: 331-31, never
  RUS-0: 40126-10, 9h.36m
  easylist: 76401-327, 2d.11h.13m
  easyprivacy: 33156-16365, 4d.9h.58m
  plowe-0: 3787-1601, 1d.10h.34m
  ublock-badware: 7543-138, 4d.11h.41m
  ublock-filters: 36477-360, 4d.11h.40m
  ublock-privacy: 951-465, 9h.37m
  ublock-quick-fixes: 128-4, 9h.35m
  ublock-unbreak: 2177-81, 4d.11h.39m
  urlhaus-1: 9725-0, 2h.42m
filterset (user): [array of 331 redacted]
trustedset:
 added: [array of 12 redacted]
 removed:
  about-scheme
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2713 ms (selfie)
 maxAssetCacheWait: 408 ms
popupPanel:
 blocked: 9
 no-cosmetic-filtering: true
 network:
  pikabu.ru: 4
  googletagmanager.com: 1
  tns-counter.ru: 1
  vk.com: 2
  yandex.ru: 1
 extended:
  ##.header-right-menu > a[href][target="_blank"]
  ##.sidebar-block_placeholder
  ##a[href*="//ads.adfox.ru/"]
  ##.stories-feed__container > .story[data-author-name] ~ .story:n…
  ##.sidebar
  ##article.story:nth-of-type(9)
  ##article.story:nth-of-type(4)
  ###adfox_156570562144159249
  ##.story__share
  ##.story__copy-link.hint
  ##.sidebar-block-links__footer
  ##div[id^="adfox_"]
  ##.stories-feed__container > .story:has(> .story__placeholder)
  ##.footer__inner:style(background-color: var(--color--app__bg) !…
  ##aside > .sidebar-block > div > div > div > div:style(min-heigh…
  ##aside > .sidebar-block > div > div > div:style(min-height: uns…
  ##aside > .sidebar-block > div > div:style(min-height: unset !im…
  ##aside > .sidebar-block > div:style(min-height: unset !importan…
  ##aside > .sidebar-block:style(min-height: unset !important)
  ##header > .header__main:style(background-color: var(--color--he…
  ##+js(abort-on-property-read, Object.prototype.loadBanner)
  ##+js(abort-on-property-read, Ya)
  ##+js(json-prune, data, errors)
  ##+js(json-prune, isVideoAutoplayMode swUrl)
  ##+js(remove-node-text, script, addPlaceholder)

```
</details>

**Comment by dportvine** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Added to [BitBlock](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links)
