### ISSUE TITLE
cnnturk

### ISSUE THREAD

**Issue by snoffer** [uBlockOrigin/uAssets#2166]
Replace the bracketed [...] placeholders with your own information.

`www.cnnturk.com`

cnnturk can detect ublock origin on chrome

https://imgur.com/a/Hk756em

- Browser/version: 66.0.3359.139

**Comment by gorhill** [comment]
Need translation, what does the box says? Is the page content prevented from being accessible?

**Comment by mapx-** [comment]
tested on this page:
`https://www.cnnturk.com/video/turkiye/kazi-yapan-is-makinesi-devrildi`

working for me
```
cnnturk.com##script:inject(set-constant.js, hasAdBlock, false)
@@/comscore/*$script,domain=cnnturk.com
@@||gemius.pl/gplayer.js$script,domain=cnnturk.com
@@||cnnturk.com/action/media/$xmlhttprequest,first-party
```

@snoffer do the filters above work for you ?

**Comment by zaphodbeebblebrox** [comment]
It appears to work for me.

**Comment by smed79** [comment]
> `@@/comscore/*$script,domain=cnnturk.com`

more specific
```
@@||js.dogannet.tv^*/comscore/streamsense.$script,domain=cnnturk.com
```

**Comment by snoffer** [comment]
yes this is video content.this code seem working
 @gorhill
