### ISSUE TITLE
bizjournals.com: detection

### ISSUE THREAD

**Issue by koreachess** [uBlockOrigin/uAssets#21664]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.bizjournals.com/dallas/news/2023/08/22/match-group-justine-sacco-social-issues-sb-8-texas.html`

### Category

detection

### Description

wont let me use ublock and view the wesite

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>
wont let me view

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 104579
 cosmetic: 44343
 scriptlet: 18639
 html: 1978
listset (total-discarded, last-updated):
 default:
  user-filters: 42-0, never
  ublock-filters: 37225-151, now
  ublock-badware: 7569-11, now
  ublock-privacy: 948-4, now
  ublock-unbreak: 2222-1, now
  ublock-quick-fixes: 152-0, now
  easylist: 76515-670, now
  easyprivacy: 33169-811, now
  urlhaus-1: 9710-0, now
  plowe-0: 3784-1, now
filterset (user): [array of 42 redacted]
trustedset:
 added: [array of 8 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 15540 ms (selfie)
 maxAssetCacheWait: 2807 ms
popupPanel:
 blocked: 29
 network:
  adobedtm.com: 11
  brandmetrics.com: 1
  demdex.net: 3
  doubleclick.net: 2
  facebook.net: 1
  googletagmanager.com: 1
  indexww.com: 1
  licdn.com: 1
  marketo.net: 1
  moatads.com: 5
  newrelic.com: 2
 extended:
  ##.adwrap
```
</details>

**Comment by D4niloMR** [comment]
Do you mean this?

`THIS ARTICLE IS FOR SUBSCRIBERS ONLY`
`Continue reading with your subscription`
`Access 4 weeks of business news and insights`
`Subscribe for only $4`

We don't fix paywall.

https://github.com/uBlockOrigin/uAssets/blob/master/README.md

> uAssets will not address the following:
> 
> - Paywalls
> - Porn Farms

**Comment by mapx-** [comment]
@koreachess 

use it as custom filter

`bizjournals.com##+js(nostif, nrWrapper)`

**Comment by D4niloMR** [comment]
I get the paywall even with uBO turned off
