### ISSUE TITLE
wafrost.com: breakage

### ISSUE THREAD

**Issue by huyszn** [uBlockOrigin/uAssets#21669]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.wafrost.com/reservations`

### Category

breakage

### Description

Reservations widget does not show when uBO is enabled. I believe the filter `/^https:\/\/www\.[a-z]{8,14}\.com\/[a-z]{1,4}\.js$/$script,3p,match-case,from=~edu|~gov` in `filters-2022.txt` is causing the breakage, blocking ​`https://www.exploretock.com/tock.js`.

### Other extensions used

Bypass Paywalls Clean, Auto Highlight, Cookie-Editor, EPUBReader, Grammarly, Language Reactor, Network Sniffer, Old Reddit Redirect, Prolific Assistant, Reddit Enhancement Suite, Return YouTube Dislike, Tampermonkey, Video Speed Controller, Word Counter Plus

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104872
 cosmetic: 45962
 scriptlet: 24365
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 6450-16, now
 default:
  user-filters: 55-2, never
  easylist: 76423-15, now
  easyprivacy: 33171-65, now
  plowe-0: 3784-1154, now
  ublock-badware: 7565-137, now
  ublock-filters: 36578-221, now
  ublock-privacy: 952-12, now
  ublock-quick-fixes: 141-4, now
  ublock-unbreak: 2176-33, now
  urlhaus-1: 9710-0, now
filterset (user): [array of 45 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 211 ms (selfie)
 maxAssetCacheWait: 71 ms
popupPanel:
 blocked: 7
 network:
  wafrost.com: 1
  exploretock.com: 1
  facebook.net: 1
  googletagmanager.com: 1
  marketingautomation.services: 1
  squarespace.com: 1
  typekit.net: 1
```
</details>

**Comment by huyszn** [comment]
There are also a lot of restaurant websites that use Tock that have his problem like
```
https://www.barshozan.com/reservations
https://glenmorgan.com/reserve-your-table-with-tock/
https://www.alinearestaurant.com/
https://www.straitsrestaurants.com/
https://www.roisterrestaurant.com/
https://pointeasydenver.com/reserve/
https://www.spence.cafe/reserve
https://cynaraolympia.com/
```
and more so I am not sure if something needs to be changed in the filter or we should just keep adding sites to the filter.

**Comment by mapx-** [comment]
@Yuki2718 maybe the filter should be removed

**Comment by Yuki2718** [comment]
I don't see the request?
