### ISSUE TITLE
pastpapers.co: ads

### ISSUE THREAD

**Issue by NotDaniDev** [uBlockOrigin/uAssets#21680]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pastpapers.co/cie/?dir=IGCSE`

### Category

ads

### Description

Shows ads

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/80210817/cf2fc608-62ee-465a-a11b-682148c37015)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104813
 cosmetic: 44228
 scriptlet: 19933
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76424-15, now
  easyprivacy: 33171-65, now
  plowe-0: 3784-1154, now
  ublock-badware: 7565-137, now
  ublock-filters: 36576-220, now
  ublock-privacy: 952-12, now
  ublock-quick-fixes: 146-4, now
  ublock-unbreak: 2176-32, now
  urlhaus-1: 9965-0, now
filterset (user): [empty]
trustedset:
 added: [array of 23 redacted]
 removed:
  about-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 551 ms (selfie)
 maxAssetCacheWait: 132 ms
popupPanel:
 blocked: 5
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
  gstatic.com: 3
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by u-RraaLL** [comment]
pastpapers.co##tr:not([class]):has([href*="amzn.to"]), .sticky-bottom:has([href="https://ringdad.com"])

@ryanbr
