### ISSUE TITLE
visortmo.com: ads

### ISSUE THREAD

**Issue by GlenGs** [uBlockOrigin/uAssets#21687]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://visortmo.com/`

### Category

ads

### Description

There are multiple ads throughout the page

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/144768077/f57263c9-636f-4c41-9c94-e18dacadd22a)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107353
 cosmetic: 50574
 scriptlet: 20315
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 76463-15, 20m
  easyprivacy: 33171-65, 20m
  plowe-0: 3784-1154, 8m
  spa-0: 3774-20, 20m
  spa-1: 5692-209, 8m
  ublock-badware: 7575-137, 20m
  ublock-filters: 36577-243, 20m
  ublock-privacy: 954-8, 20m
  ublock-quick-fixes: 146-4, 20m
  ublock-unbreak: 2176-34, 20m
  urlhaus-1: 9965-0, 20m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 357 ms (selfie)
 maxAssetCacheWait: 198 ms
popupPanel:
 blocked: 6
 network:
  google-analytics.com: 1
  googletagmanager.com: 1
  nakamasweb.com: 1
  outbrain.com: 2
  taboola.com: 1
 extended:
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by D4niloMR** [comment]
@Yuki2718 to AdGuard Spanish list `visortmo.com##a[href*="offer_id="][target="_blank"] > img` (a similar one already exist, I only modified)

`visortmo.com###pills-populars .element:has(>a[href*="offer_id="][target="_blank"])`
`visortmo.com##.pblu.pbl_t`
