### ISSUE TITLE
(popup) revivelink.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2168]
### URL(s) where the issue occurs

`http://revivelink.com/3EQVTG`

### Describe the issue

There's a popup. 

### Versions

- Browser/version: Chrome 68
- uBlock Origin version: 1.16.2

### Settings

Default

**Comment by zaphodbeebblebrox** [comment]
`revivelink.com##script:inject(abort-current-inline-script.js, atob, tabunder)`

**Comment by ghajini** [comment]
Popup ads
