### ISSUE TITLE
thetrainline.com: ads

### ISSUE THREAD

**Issue by Rudloff** [uBlockOrigin/uAssets#21699]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.thetrainline.com/fr/my-account/bookings/upcoming`

### Category

ads

### Description

An ad is displayed at the top of the bookings list.

### Other extensions used

- Dark Mode Website Switcher
- IPvFoo

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/840125/62c91fd1-dd7d-4c3d-9a34-85cf9e219166)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 126073
 cosmetic: 97281
 scriptlet: 23018
 html: 1981
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49207-172, now
  ublock-cookies-easylist: 841-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37249-226, 37m
  ublock-badware: 7729-11, 37m
  ublock-privacy: 950-0, 37m
  ublock-unbreak: 2222-1, 37m
  ublock-quick-fixes: 162-0, 37m
  easylist: 76467-738, 37m
  easyprivacy: 33178-811, 37m
  urlhaus-1: 10090-0, now
  plowe-0: 3784-1, now
  FRA-0: 28985-336, now
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 372 ms (selfie)
 maxAssetCacheWait: 87 ms
popupPanel:
 blocked: 5
 network:
  datadome.co: 1
  googletagmanager.com: 1
  newrelic.com: 1
  usabilla.com: 2
 extended:
  ##.onetrust-pc-dark-filter
  ##+js(trusted-set-cookie, OptanonConsent, groups=C0001%3A1%2CC00…
  ##+js(trusted-set-cookie, OptanonAlertBoxClosed, $currentDate$, …
```
</details>

**Comment by mapx-** [comment]
report at [regional list repository](https://github.com/easylist/listefr/issues) (provide also a test account eventually)
