### ISSUE TITLE
plus.nhk.jp: nuisance

### ISSUE THREAD

**Issue by yapkenta** [uBlockOrigin/uAssets#21694]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://plus.nhk.jp/watch/ch/g1`

### Category

nuisance

### Description

Watermark over the video feed

### Other extensions used

https://chromewebstore.google.com/detail/stream-recorder-download/iogidnfllpdhagebkblkgbfijkbkjdmm
NordVPN

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 104905
 cosmetic: 44242
 scriptlet: 19952
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 76467-15, now
  easyprivacy: 33178-65, now
  plowe-0: 3784-1154, now
  ublock-badware: 7725-137, now
  ublock-filters: 36584-220, now
  ublock-privacy: 954-8, now
  ublock-quick-fixes: 145-4, now
  ublock-unbreak: 2176-32, now
  urlhaus-1: 9865-0, now
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 600 ms (selfie)
 maxAssetCacheWait: 145 ms
popupPanel:
 blocked: 4
 no-cosmetic-filtering: true
 network:
  nhk.jp: 2
  youborafds01.com: 2
 extended:
  ##.stream_panel--player
```
</details>

**Comment by Yuki2718** [comment]
Already fixed by AdGuard – Popup Overlays (I think it's misclassification though - not a popup). You have to enable either AdGuard – Popup Overlays or EasyList – Other Annoyances.
