### ISSUE TITLE
geektime.co.il

### ISSUE THREAD

**Issue by almog123** [uBlockOrigin/uAssets#217]
ads came back to geektime.co.il
Browser: chrome
Extension Version: 1.9.16
old issue: https://github.com/uBlockOrigin/uAssets/issues/206

screenshot: https://cloud.githubusercontent.com/assets/17848148/20603825/01120464-b26c-11e6-8020-60a862aa9d4a.png

**Comment by gorhill** [comment]
Fixed with uBO 1.10.0+ (which is published in the Chrome store).

**Comment by IDKwhattoputhere** [comment]
Could you reply to the questions asked and if the filters work next time? Otherwise these issues are of no use to all the other users.

**Comment by almog123** [comment]
sorry I didn't saw the questions.
didn't worked with  uBO 1.10.0 on start, I needed to purge the cache from the 3rd party filters, now it is working, thank you gorhill.

@IDKwhattoputhere 
geektime.co.il##a[target="_blank"] is creating a lot of false positive since it's hiding normal images with links to other sites on articles.
