### ISSUE TITLE
gsmarena.com: ads

### ISSUE THREAD

**Issue by Sym8** [uBlockOrigin/uAssets#21707]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://m.gsmarena.com/resident_evil_4_for_iphone_review-news-61067.php`

### Category

ads

### Description

Leftover empty space

### Other extensions used

Dark reader, Google search fixer, tamper monkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2024-01-01-13-09-01-79_3aea4af51f236e4932235fdada7d1643](https://github.com/uBlockOrigin/uAssets/assets/66876418/6d9aeb23-47d4-4e3a-8ccb-7492bda0defb)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 109189
 cosmetic: 87757
 scriptlet: 23920
 html: 2187
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 28253-55, now
  easylist-newsletters: 6853-7, now
  easylist-notifications: 2902-4, now
  ublock-annoyances: 6483-907, now
  ublock-cookies-adguard: 888-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 37373-257, now
  ublock-badware: 7723-11, now
  ublock-privacy: 950-0, now
  ublock-unbreak: 2224-1, now
  ublock-quick-fixes: 169-0, now
  adguard-mobile: 8949-102, now
  easylist: 76481-730, now
  easyprivacy: 33178-893, now
  urlhaus-1: 9960-0, now
  plowe-0: 3784-1, now
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1093 ms
 maxAssetCacheWait: 325 ms
popupPanel:
 blocked: 7
 network:
  doubleclick.net: 2
  google.com: 1
  googletagmanager.com: 1
  uniconsent.com: 2
  youtube.com: 1
 extended:
  ##.top-adv
  ##.adv-bottom
  ##.ad-top
  ##.ad-c-label
  ##.adv-mid
  ##div[id^="crt-"][style]
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##.ytp-chrome-top-buttons > .ytp-cards-teaser
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(trusted-set-cookie, SOCS, CAISNQgDEitib3FfaWRlbnRpdHlmcm9u…
  ##+js(set-constant, ytInitialPlayerResponse.auxiliaryUi.messageR…
  ##+js(json-prune, auxiliaryUi.messageRenderers.upsellDialogRende…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
```
</details>

**Comment by BlazeFTL** [comment]
Try 
```
gsmarena.com###review-body > div[style*="padding-bottom:"][style*="min-height:"]:has(> pgs-ad)
